### ISSUE TITLE
[master] Consistent sharing acceptance test failure

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#26314]
### Steps

1. Send a PR with any kind of changes to master
2. Wait for CI
3. :boom: 

### Expected
No :boom: 

### Actual
:boom: 

The test `/drone/src/tests/acceptance/features/app-files-sharing.feature:23` always fails.

```
    And I accept the share for "/farewell.txt" in the notifications           # NotificationsContext::iAcceptTheShareForInTheNotifications()
      Notifications button in the header could not be found after 100 seconds (NoSuchElementException)
    And I open the Files app                                                  # FilesAppContext::iOpenTheFilesApp()
```

**Comment by PVince81** [comment]
Running the test locally makes it pass.

So could be either a timeout issue or something specific to the CI setup.

**Comment by PVince81** [comment]
Last successful build on master: https://drone.nextcloud.com/nextcloud/server/3568

Then something about php8 didn't run at all: https://drone.nextcloud.com/nextcloud/server/3574

Then the first failure appeared here: https://drone.nextcloud.com/nextcloud/server/3598/61/4

**Comment by PVince81** [comment]
Reproducible locally now with master a75f0e62fa0b9e140ba0dd8ffb2e928a5d3007dd and notifications 3410e5ab517f8435ab2cfd80549d43fbbfb41b1f

**Comment by PVince81** [comment]
okay, getting this with manual test:
<img width="334" alt="image" src="https://user-images.githubusercontent.com/277525/112616049-8ddcf600-8e23-11eb-96fc-c7d85edf2f5b.png">

very likely related to https://github.com/nextcloud/notifications/pull/899

**Comment by PVince81** [comment]
Fix is here: https://github.com/nextcloud/notifications/pull/902

**Comment by PVince81** [comment]
It's still happening on master, for example this recent merge PR https://drone.nextcloud.com/nextcloud/server/4104/61/4 and also existing (rebased) PR: https://github.com/nextcloud/server/pull/25320

**Comment by PVince81** [comment]
A manual test on the master branch of server + master branch of notifications, clicking through the GUI works fine, the notification appears.

However, running `./run.sh features/app-files-sharing.feature:23` in the "tests/acceptance" folder fails.

**Comment by PVince81** [comment]
as discussed with @danxuliu, the Firefox version in the dockers and selenium are outdated and unsupported.

the error is caused by a syntax error, probably due to Babel not transpiling for such old versions

this PR https://github.com/nextcloud/server/pull/25991 updates Selenium and should fix the problem

**Comment by danxuliu** [comment]
> this PR #25991 updates Selenium and should fix the problem

For the record, I actually checked it and it indeed works.

**Comment by skjnldsv** [comment]
Rebased 25991, let's get this in as soon as we can :)

**Comment by skjnldsv** [comment]
Thank you for all the hard work on upgrading selenium :)

**Comment by danxuliu** [comment]
#25991 was merged, so the failure is gone :-)
