### ISSUE TITLE
No permissions for just one folder in external storage

### ISSUE THREAD

**Issue by jp-weiss** [nextcloud/server#26321]
Hello,
I have a strange problem when accessing home directory via an external storage connected to a CIFS share on my file server. I have the ‘You don’t have permissions to upload or create files here’ message, but only on the ‘Documents’ folder while this directory has the same ACLs as others directories.
The problem appear on fresh installations of Nextcloud (V 21.0.0 and V 20.0.6) and with the files_external versions 1.11.1 and 1.12.
But, that’s what is weird, the problem doesn’t appear in a older version of nextcloud (V 18.0.1) and files_external version 1.9.0.
It seems to be a bug.

**Comment by devi69** [comment]
Hello @jp-weiss,

We encountered a similar problem.
The problem of SMB external storage not connecting properly when ACLs are set seems to have been fixed in Nextcloud 20.0.7. https://github.com/nextcloud/server/pull/25421
Updating to v20.0.7 or applying the patch may improve the situation.

```
wget https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/25421.patch
cd /path/to/nextcloud/
patch -p1 < /path/to/25422.patch
```

**Comment by jp-weiss** [comment]
Thank you @devi69 
I have just upgraded my 21.0.0 version to 21.0.1 but the problem is still the same.
For now, I can't upgrade the server in version 20.0.7, but I will as soon as possible.

**Comment by szaimen** [comment]
Hm… Although it sounds like a regression to me, you might be able to overwrite the permissions by, using this app: GitHub - icewind1991/permissions_overwrite: Allow overwriting external storage permissions

**Comment by jp-weiss** [comment]
Thank you @szaimen, I used the permission_overwrite app and now it's OK.
