### ISSUE TITLE
"New text document" is shown twice

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#26328]
I noticed on c.nc.com (Nextcloud 21.0.0) that "New text document" is shown twice:

![image](https://user-images.githubusercontent.com/1589737/112701273-76882200-8e90-11eb-8c7e-4d3b94b65152.png)

**Comment by szaimen** [comment]
I can reproduce it on c.nc.c, too but not on my own instance:
![image](https://user-images.githubusercontent.com/42591237/119265206-26a2ae80-bbe6-11eb-9a2a-a97915728873.png)
So maybe something wrong on c.nc.c?

**Comment by szaimen** [comment]
Doesn't happen anymore on c.nc.c
