### ISSUE TITLE
System tags Javascript erros

### ISSUE THREAD

**Issue by siimaarmaa** [nextcloud/server#26351]
If i open in admin section Flow settings. I start getting javascript erros in systemlogs. Browser console show only : 
`globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.`

**Server configuration**
**OS:** CentOS Linux 8, Linux 4.18.0-240.10.1.el8_3.x86_64
**Webserver:** Apache/2.4.37 (centos)
**Database:**  mysql, 10.2.32
**PHP version:** PHP 7.4.15 (cli) with Zend Engine v3.4.0 and Zend OPcache v7.4.15
**Nextcloud version:** 20.0.8
**Updated from an older Nextcloud/ownCloud or fresh install:** Updated 18 to 20 version
**Where did you install Nextcloud from:** Standalone setup, with tar
**App list:**
`
Enabled:
  - admin_audit: 1.10.0
  - bruteforcesettings: 2.0.1
  - cloud_federation_api: 1.3.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - files: 1.15.0
  - files_automatedtagging: 1.10.1
  - files_pdfviewer: 2.0.1
  - files_retention: 1.9.0
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - officeonline: 1.0.3
  - password_policy: 1.10.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - systemtags: 1.10.0
  - terms_of_service: 1.6.1
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - twofactor_u2f: 6.1.0
  - updatenotification: 1.10.0
  - user_ldap: 1.10.2
  - viewer: 1.4.0
  - workflowengine: 2.2.0
Disabled:
  - accessibility
  - activity
  - comments
  - contactsinteraction
  - dashboard
  - encryption
  - federation
  - files_external
  - files_versions
  - files_videoplayer
  - firstrunwizard
  - photos
  - support
  - survey_client
  - text
  - user_status
  - weather_status
`
**Nextcloud config:**
`
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.8.1",
        "overwrite.cli.url": "http:\/\/***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "force_locale": "et_EE",
        "skeletondirectory": "disabled",
        "enable_previews": false,
        "lost_password_link": "disabled",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "knowledgebaseenabled": false,
        "logdateformat": "j F, Y, H:i:s",
        "logtimezone": "Europe\/Tallinn",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 3
        },
        "remember_login_cookie_lifetime": 43200,
        "session_lifetime": 7200,
        "trashbin_retention_obligation": "90, auto",
        "mysql.utf8mb4": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "tempdirectory": "\/DATA\/tmp",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "htaccess.RewriteBase": "\/nextcloud",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "log_rotate_size": 104857600,
        "auto_logout": true,
        "csrf.disabled": true,
        "auth.webauthn.enabled": false,
        "app_install_overwrite": [
            "files_retention"
        ]
    }
}
`
**Nextcloud logs:**
`
[jsresourceloader] Error: Could not find resource core/js/oc-backbone-webdav.js to load

GET /index.php/settings/admin/workflow
from ***REMOVED SENSITIVE VALUE*** by ***REMOVED SENSITIVE VALUE*** at 2021-03-29T09:18:12+03:00
`
`
[jsresourceloader] Error: Could not find resource core/js/systemtags/systemtags.js to load

GET /index.php/settings/admin/workflow
from ***REMOVED SENSITIVE VALUE*** by ***REMOVED SENSITIVE VALUE*** at 2021-03-29T09:18:12+03:00
`
`
[jsresourceloader] Error: Could not find resource core/js/systemtags/systemtagmodel.js to load

GET /index.php/settings/admin/workflow
from ***REMOVED SENSITIVE VALUE*** by ***REMOVED SENSITIVE VALUE*** at 2021-03-29T09:18:12+03:00
`
`
[jsresourceloader] Error: Could not find resource core/js/systemtags/systemtagscollection.js to load

GET /index.php/settings/admin/workflow
from ***REMOVED SENSITIVE VALUE*** by ***REMOVED SENSITIVE VALUE*** at 2021-03-29T09:18:12+03:00
`

**Comment by C00kiekiller** [comment]
Hi, got this issue too in my new NC 21.0.2 installation.

OS: Ubuntu 20.0.4
PHP 7.4.3, Zend Engine v3.4.0, Copyright (c) Zend Technologies with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

- `"GET","url":"/index.php/settings/admin/workflow","message":"Could not find resource core/js/systemtags/systemtagscollection.js to load"`
- `"GET","url":"/index.php/settings/admin/workflow","message":"Could not find resource core/js/systemtags/systemtagmodel.js to load"`
- `"GET","url":"/index.php/settings/admin/workflow","message":"Could not find resource core/js/oc-backbone-webdav.js to load"`
and so on...

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.4? If not, please close this issue. Thanks! :)

**Comment by siimaarmaa** [comment]
@szaimen  In the meantime, it must be open as there is still an error at the moment and the update will take place on August 20th.

**Comment by siimaarmaa** [comment]
@szaimen version 21.0.4 not fixed this problem

**Comment by Schmuuu** [comment]
This issue still occurs in version 21.0.5. I just updated my instance and went through the admin section. Afterwards I noticed these error messages in the logs:
```
{"reqId":"VBTznVmFhPNI2bHBQ8Ul","level":3,"time":"2021-10-02T16:48:29+02:00","remoteAddr":"192.168.1.2","user":"admin","app":"jsresourceloader","method":"GET","url":"/settings/admin/workflow","message":"Could not find resource core/js/oc-backbone-webdav.js to load","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0","version":"21.0.5.1"}
{"reqId":"VBTznVmFhPNI2bHBQ8Ul","level":3,"time":"2021-10-02T16:48:29+02:00","remoteAddr":"192.168.1.2","user":"admin","app":"jsresourceloader","method":"GET","url":"/settings/admin/workflow","message":"Could not find resource core/js/systemtags/systemtags.js to load","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0","version":"21.0.5.1"}
{"reqId":"VBTznVmFhPNI2bHBQ8Ul","level":3,"time":"2021-10-02T16:48:29+02:00","remoteAddr":"192.168.1.2","user":"admin","app":"jsresourceloader","method":"GET","url":"/settings/admin/workflow","message":"Could not find resource core/js/systemtags/systemtagmodel.js to load","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0","version":"21.0.5.1"}
{"reqId":"VBTznVmFhPNI2bHBQ8Ul","level":3,"time":"2021-10-02T16:48:29+02:00","remoteAddr":"192.168.1.2","user":"admin","app":"jsresourceloader","method":"GET","url":"/settings/admin/workflow","message":"Could not find resource core/js/systemtags/systemtagscollection.js to load","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:92.0) Gecko/20100101 Firefox/92.0","version":"21.0.5.1"}
```

These error messages are always triggered when I access the flow configuration page (myserverdomain.tld/settings/admin/workflow).
My server exists since NC 11 and it received every major version update up to 21.0.5 now (so not a recent fresh installation), if this information matters. 

PHP: 8.0.11
```
8.0.11
Modules loaded: Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, PDO, bz2, posix, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, bcmath, Phar, curl, exif, ftp, gd, gmp, intl, iconv, pdo_mysql, pdo_sqlite, sockets, sqlite3, zip, apcu, igbinary, imagick, redis, smbclient, libsmbclient, Zend OPcache
```

Webserver: nginx 1.20.1

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
