### ISSUE TITLE
Deleting user from group in Group Filtered view not rendering correctly 

### ISSUE THREAD

**Issue by hanscomps** [nextcloud/server#26350]
Steps (under Settings -> Users):
1. Add multiple users to a group1
2. Choose the group1 to see a filtered list of the group1 users 
3. Choose a user halfway in the list, edit and remove (untick) the group1

Behaviour:
The user disappears from the list, but the "Edit user" state is applied to user next in the list.

Expected Behaviour:
The user should only be removed from the list after the "Edit user" is committed ("ticked")

**Comment by sndrr** [comment]
I cannot reproduce this exact scenario in NC 20.0.8.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)
