### ISSUE TITLE
I transferred the ownership of a file or folder, everything is normal and no error is reported, but the receiving user did not receive a prompt whether to accept or reject the incoming, why?

### ISSUE THREAD

**Issue by fan4905** [nextcloud/server#26354]
I transferred the ownership of a file or folder, everything is normal and no error is reported, but the receiving user did not receive a prompt whether to accept or reject the incoming, why?

**Comment by fan4905** [comment]
The 20.0.8 version I use

**Comment by szaimen** [comment]
Duplicate of https://github.com/nextcloud/server/issues/21856
