### ISSUE TITLE
Form-Fields for Upload-Shares

### ISSUE THREAD

**Issue by mamo2021** [nextcloud/server#26369]
Hello,

for upload shares it would be helpful if the user could define one or more input fields in order to have the uploaded files better separated. We use shares in the association for several recipients. As a rule, you don't usually know who they came from based on the uploaded files. It would therefore be ideal if you could define 2-3 fields (entering an individual field name).

The entries should then be created as a folder and the uploaded files should be placed there.

An example: I create an upload share for a folder and indicate that two fields have to be filled:
Field 1: Name
Field 2: Subject

![grafik](https://user-images.githubusercontent.com/81615041/112961047-4b7a2880-9145-11eb-9c58-00af0353982c.png)

The recipient of the approval uses the uploadlink and enters:
Name: Mustermann
Subject: Samplesubject

The files are stored in Nextcloud as follows:
/Mustermann/Samplesubject/File1.png
/Mustermann/Samplesubject/File2.png

If the same person uploads several times on different topics, appropriate folders are created and everything is organized.
I would be happy if such a function could be implemented via an upload release for 2-3 input fields.

I am aware that this could also be solved in another ways (for example, by recipients naming their files accordingly), but it's the case, that publicly distributed upload links are often used by people who are not very affine with the use of computers or are from other reasons do not affect file names. The use of such input fields would therefore be very advantageous, especially when used by non-profit organizations, associations or other comparable institutions.

Regards

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by szaimen** [comment]
Hi, I imagine your request could maybe be solved in the forms app: https://github.com/nextcloud/forms/issues/42
Please have a look there.
Thanks!

**Comment by mamo2021** [comment]
I can't see any solution yet. So I ask for reopening this feature request. It's even a difference between forms and file-upload. I don't want to create a form every time I have to create a upload-link. The main reason for a upload-link is to upload files. The main reason for a form is to collect data and (by the way) get a file.

**Comment by szaimen** [comment]
cc @nextcloud/server-triage is this feasible?
