### ISSUE TITLE
Creating a task list creates / links a calendar with the same name

### ISSUE THREAD

**Issue by fredddd1** [nextcloud/server#26388]
I really just wish to have a task list, not another calendar.

I have many task lists and now my calendar is just filled with unnecessary linked and empty calendars.

**Comment by szaimen** [comment]
Hi, you can create new tasks only lists in the tasks app directly.
![image](https://user-images.githubusercontent.com/42591237/119265035-92d0e280-bbe5-11eb-88fb-9a35635d0cb7.png)

**Comment by fredddd1** [comment]
@szaimen Doing this, will also create a calendar with the same name as the task list.

**Comment by szaimen** [comment]
No, it doesn't if you uncheck this option in the calendar:
![image](https://user-images.githubusercontent.com/42591237/119265729-ffe57780-bbe7-11eb-9e41-866a41258064.png)

**Comment by fredddd1** [comment]
Thanks! I must have missed that option.
