### ISSUE TITLE
nextcloud 21 with php8 have some issues

### ISSUE THREAD

**Issue by littlesum** [nextcloud/server#26387]
` sudo -u www php occ `

> PHP Warning:  Missing arginfo for Imagick::__tostring() in Unknown on line 0
> PHP Warning:  Missing arginfo for Imagick::getimagehistogram() in Unknown on line 0
> PHP Notice:  fwrite(): Write of 2880 bytes failed with errno=69 Disc quota exceeded in /usr/local/www/nextcloud/lib/private/Log/File.php on line 90
>

**Comment by kesselb** [comment]
You have no quota left ;)

getImageHistogram we are not using this function in nextcloud/server.

Closing as unrelated.
