### ISSUE TITLE
Critical changes for developers & admins for Nextcloud 22

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#26407]
Continuation of #23210 

# Front-end

- Moving to node lts (14)
- IE11 removal. https://github.com/nextcloud/server/issues/20855

### Deprecated global variables

tbd

# Backend

* `OCP\LDAP\ILDAPProviderFactory` now also needs to implement a method `isAvailable()` #25326 
* Boolean database fields can not be NotNull anymore #24055
* If an invalid user+password combination is provided a proper 401 is now returned #26572 and #26846 

## Removed from public namespace:

* `OCP\User` was removed after the grace period of 3 years - #25679

## Removed from private namespace:

* `OC_User::getDisplayName()` - #24318 

## Deprecations

tdb

### Deprecations of Events & Hooks

tdb

## Behavorial changes

* `migration:*` commands are not available anymore (unless in debug). See #27113 for information. If you thought you needed them, feel free to ping the author or a reviewer of the PR to solve the problem correctly. Running migrations directly mostly breaks the database status and is therefor only ment for debugging faulty migrations.
* The JSON log format no longer contains full exception in the message field, but adds a separate `exception` entry is added and the existing message will only contain the exception message text. This might need adjustments by administrators when logs are extracted to external sources.
* EHLO for SMTP connections is now generated from `overwrite.cli.url`: https://github.com/nextcloud/server/pull/27306

**Comment by nickvergessen** [comment]
Added:
> Boolean database fields can not be NotNull anymore #24055

**Comment by caugner** [comment]
> Boolean database fields can not be NotNull anymore #24055

Does this only concern Oracle? Or does this mean that boolean database fields have to always be nullable (= not NotNull?!) for all database systems?

**Comment by nickvergessen** [comment]
It's only about Oracle, but to make sure apps work on all supported databases we basically enforce this.

**Comment by caugner** [comment]
> It's only about Oracle, but to make sure apps work on all supported databases we basically enforce this.

Hm, my main question is: Can I still declare boolean database fields as NotNull and this flag is just not passed to Oracle database (when creating these fields), or does Nextcloud prevent me from this and possibly even convert all existing boolean database fields to nullable, for *all* supported databases, not just Oracle?

**Comment by nickvergessen** [comment]
You can fix your app in the same way we fixed Talk https://github.com/nextcloud/spreed/pull/5445

**Comment by nickvergessen** [comment]
Added:
> If an invalid user+password combination is provided a proper 401 is now returned #26572 and #26846

**Comment by Grotax** [comment]
Maybe add #27113 ?

**Comment by nickvergessen** [comment]
Why? See the PR description of that PR. If you used it you are doing something wrong?

**Comment by Grotax** [comment]
Because the title says this list is also for developers, or is that a typo?

**Comment by nickvergessen** [comment]
added

**Comment by marius-wieschollek** [comment]
The end of support for the database.xml should definitely be in here. Causes https://github.com/marius-wieschollek/passwords/issues/390

**Comment by mejo-** [comment]
Maybe it would be worth mentioning that the Circles app changed a lot. The frontend JS API got replaced by OCS API routes and the backend PHP API also changed significantly. Developers who interact with Circles probably need to migrate their code.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/documentation/pull/6900 for the collected changes. Please help review.

> Maybe it would be worth mentioning that the Circles app changed a lot. The frontend JS API got replaced by OCS API routes and the backend PHP API also changed significantly. Developers who interact with Circles probably need to migrate their code.

I'll leave that to the developers of the app.

**Comment by nickvergessen** [comment]
23 changes will be tracked in https://github.com/nextcloud/server/issues/27846
