### ISSUE TITLE
Unable to change website and address

### ISSUE THREAD

**Issue by Jojo-Burger** [nextcloud/server#26420]
Hello
Since this morning, it has been impossible to change the phone number, address and website of an account on my nextcloud instance.

### Server configuration

**Operating system:** Raspbian

**Web server:** Nginx

**Database:** Mysql

**PHP version:** 7.3.27

**Nextcloud version:** 20.0.8

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
`No errors have been found.`
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

https://s.jordand.fr/pbVUTJKZyC.gif

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

### Client configuration
**Browser:** Brave and Chrome

#### Browser log
<details>
<summary>Browser log</summary>

``globals.js:60 moment is deprecated: please ship your own, this will be removed in Nextcloud 20
The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.`

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
