### ISSUE TITLE
[self-solved] migrating nc20 to 21: login loop ➤ Crypto.php + phpseclib  failure

### ISSUE THREAD

**Issue by plouflechien** [nextcloud/server#26425]
### Steps to reproduce
1. migrating from NC20.0.0.8 to NC21.0.0.18
2. occ commands (upgrade -v / db:add-missing-columns / db:add-missing-indices / db:add-missing-primary-keys / db:convert-filecache-bigint / maintenance:repair --include-expensive / integrity:check-core / etc...)
3. login failed with weird lib/private/Security/Crypto.php errors (seems to be linked to 2016's phpseclib v2)

### Expected behaviour
Im my opinion, when encrypting sessions vars, cipher->encrypt (lib/private/Security/Crypto.php line 100) should produce encrypted data, not a boolean::FALSE, closing any login attempts (keyword: **login loop**).

### Actual behaviour

- login loop
- session cookies badly recorded (empty file) an/or badly re-read between queries with the famous error message "**bin2hex() expects parameter 1 to be string, bool given**" produced from /lib/private/Security/Crypto.php:100 called from lib/private/Session/CryptoSessionData.php:180 (see "nextcloud.log" for complete log).

### Server configuration

**Operating system:**
FreeBSD 12.2p4 

**Web server:**
nginx-1.18.0_36 + php-fpm_7.3.27

**Database:**
postgresql13-server-13.2 (same result with postgresql 10)

**PHP version:**
php73-7.3.27 (tested with latest 74 with no more luck)
(recompiled without ZTS, just in case)

**Nextcloud version:** (see Nextcloud admin page)
$OC_Version = array(21,0,0,18);
$OC_Build = '2021-02-19T08:52:18+00:00 8985b7930653139859002eb3eca2852999ed8f0d';

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated in command line 's occ 
This installation was very old; migrated from oc9 => nc10,11,12,13,14...20,21.
_Even with new start same error, within the same file.
I have 5 installation all in the same bogus status._

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-21.0.0.tar.bz2 
**Signing status:**
<details>
<summary>(checked OK with it's sha512 fingerprint)</summary>
occ integrity:check-core is happy
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
**can't log into server**
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - admin_audit: 1.11.0
  - calendar: 2.2.0
  - cloud_federation_api: 1.4.0
  - contacts: 3.5.1
  - contactsinteraction: 1.2.0
  - dav: 1.17.1
  - duplicatefinder: 0.0.6
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_external: 1.12.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.10.0
  - notes: 4.0.4
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - provisioning_api: 1.11.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - tasks: 0.13.6
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - workflowengine: 2.3.0
Disabled:
  - accessibility
  - activity
  - comments
  - dashboard
  - encryption
  - federation
  - files_pdfviewer
  - firstrunwizard
  - ocsms
  - privacy
  - recommendations
  - support
  - user_ldap
  - weather_status
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "dbtype": "pgsql",
        "version": "21.0.0.18",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "has_internet_connection": true,
        "theme": "",
        "maintenance": false,
        "defaultapp": "contacts,calendar,files",
        "default_language": "fr",
        "session_lifetime": 2592000,
        "remember_login_cookie_lifetime": 7776000,
        "trusted_domains": [
            ***REMOVED SENSITIVE VALUE***
        ],
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "versions_retention_obligation": "30,60",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "default_phone_region": "FR",
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no (dedicated server)
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
no

### Client configuration
**Browser:**
firefox, chrome, etc... server side problem
**Operating system:**
any (windows 10, mac osx, etc..)

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"J9YuiUolfdoQROKtPxM5","level":3,"time":"2021-04-04T22:35:38+00:00","remoteAddr":"10.0.0.28","user":"--","app":"index","method":"GET","url":"/login","message":{"Exception":"TypeError","Message":"bin2hex() expects parameter 1 to be string, bool given","Code":0,"Trace":[{"file":"[redacted]/lib/private/Security/Crypto.php","line":100,"function":"bin2hex","args":[false]},{"file":"[redacted]/lib/private/Session/CryptoSessionData.php","line":180,"function":"encrypt","class":"OC\\Security\\Crypto","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"[redacted]/lib/private/AppFramework/Middleware/SessionMiddleware.php","line":69,"function":"close","class":"OC\\Session\\CryptoSessionData","type":"->","args":[]},{"file":"[redacted]/lib/private/AppFramework/Middleware/MiddlewareDispatcher.php","line":144,"function":"afterController","class":"OC\\AppFramework\\Middleware\\SessionMiddleware","type":"->","args":[{"__class__":"OC\\Core\\Controller\\LoginController"},"showLoginForm",{"__class__":"OCP\\AppFramework\\Http\\TemplateResponse"}]},{"file":"[redacted]/lib/private/AppFramework/Http/Dispatcher.php","line":165,"function":"afterController","class":"OC\\AppFramework\\Middleware\\MiddlewareDispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\LoginController"},"showLoginForm",{"__class__":"OCP\\AppFramework\\Http\\TemplateResponse"}]},{"file":"[redacted]/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\LoginController"},"showLoginForm"]},{"file":"[redacted]/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\LoginController","showLoginForm",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"core.login.showLoginForm"}]},{"file":"[redacted]/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/login"]},{"file":"[redacted]/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"[redacted]/lib/private/Security/Crypto.php","Line":100,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0","version":"21.0.0.18"}
</details>

**Comment by plouflechien** [comment]
If it can help others:
openssl 1.1**K** on freebsd 12.2p4 fail on kernel's <tt>crypto_dev</tt>  module is loaded and have no sufficient rights (the case of web apps usually). (keywords: <tt>error message SSL: error:0201502D:system library:ioctl:Operation not supported</tt> )
Within phpseclib openssl_encrypt returning null doesn't throw an exception. Crypto.php happilly accept FALSE return then feed bin2hex with this boolean value.  (keywords: <tt>bin2hex() expects parameter 1 to be string, bool given</tt> at Crypto.php:100 )

patch  Openssl @freebsd bug described here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254643
or you can disable <tt>crypto_dev</tt> kernel module within /boot/loader.conf (freebsd kernel modules config at boot)

_private message : Mathieu de Makina un grand merci , si tu passe par ici ;-)_

**Comment by szaimen** [comment]
> If it can help others:
> openssl 1.1**K** on freebsd 12.2p4 fail on kernel's crypto_dev module is loaded and have no sufficient rights (the case of web apps usually). (keywords: error message SSL: error:0201502D:system library:ioctl:Operation not supported )
> Within phpseclib openssl_encrypt returning null doesn't throw an exception. Crypto.php happilly accept FALSE return then feed bin2hex with this boolean value. (keywords: bin2hex() expects parameter 1 to be string, bool given at Crypto.php:100 )
> 
> patch Openssl @freebsd bug described here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254643
> or you can disable crypto_dev kernel module within /boot/loader.conf (freebsd kernel modules config at boot)
> 
> _private message : @kiorky de Makina un grand merci , si tu passe par ici ;-)_

So I suppose this issue is solved then?

**Comment by plouflechien** [comment]
not really, code in https://github.com/nextcloud/server/blob/master/lib/private/Security/Crypto.php not changed; bad values from $this->cipher->encrypt($plaintext) are not handled (failure to encrypt the plaintext not properly handled). 
My solving method implie to disable openssl hardware support to avoid phpseclib from using it. 
In my own opinion, it's just a patch, not the good way to solve phpseclib failure to return encrypted values.

**Comment by szaimen** [comment]
Would you be able to provide a PR with a patch to fix this?

**Comment by plouflechien** [comment]
I'll try but I'm not fluent with php ;

**Comment by plouflechien** [comment]
diff ./lib/private/Security/Crypto.php.ORIG ./lib/private/Security/Crypto.php
100c100,107
<               $ciphertext = bin2hex($this->cipher->encrypt($plaintext));
---
>               $dummy=$this->cipher->encrypt($plaintext);
>               if ($dummy===false) {
>                 throw new \Exception('cipher->encrypt returnd false (check openssl and hardware support of cryto device)');
>               } else {
>                  $ciphertext = bin2hex($dummy);
>                  unset($dummy);
>               }
>

something like this should works, and solve numerous "blank pages" logins issues

**Comment by szaimen** [comment]
Cool! Could you create a PR with this patch for discussion?
Thank you!

**Comment by plouflechien** [comment]
I'll try ;-)

**Comment by plouflechien** [comment]
done (https://github.com/nextcloud/server/pull/27769) hopes that's help.

**Comment by szaimen** [comment]
Thanks! But could you please base your patch on the Master branch?
