### ISSUE TITLE
files:scan - option to ignore permission errors

### ISSUE THREAD

**Issue by kuba-orlik** [nextcloud/server#26426]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

`files:scan` stops the scan once it encounters a directory with access permissions set in a way that the `nextcloud` user can't access it.

**Describe the solution you'd like**
An option for `files:scan` command that would just skip scanning the directories with permission problems and continue to the next dir, instead of abandoning the scan entirely.

**Describe alternatives you've considered**
Going through the hard drive and fixing permissions on files I don't care about until the `files:scan` command stops crashing

**Comment by kesselb** [comment]
Should be fixed by https://github.com/nextcloud/server/pull/24989

**Comment by Psy-Virus** [comment]
> 
> 
> Should be fixed by #24989

Fix doesn't work for directories on OC 22.2. :(
Still aborting the scan for the user the directory belongs to and continues with the next user.

**Comment by dschrempf** [comment]
See #29514, I also still have this problem.

**Comment by FlattusBlastus** [comment]
Still broken in 28.0.4
