### ISSUE TITLE
Share password is tripping browser saved passwords

### ISSUE THREAD

**Issue by daveatpinellas** [nextcloud/server#26440]
This issue has been reported by two of our users and caused them to share their Nextcloud credentials with an outside person.  It's simple to do this, especially if you are not a technical user and it's extremely dangerous.   We have seen this on IE and Chrome, and probably the other browsers do the same thing.  

### Steps to reproduce
1. Enter account and password into Nextcloud and click the button in the browser to save your passwords
2. Share a folder with an outside email address.  In our case we force password and it's generated automatically
3. Click the (...) next to the outside email address and open the child window
4. Click into the password field, and eliminate the auto generated password
5. At this point the browser detects this as a password entry box for your nextcloud domain and offers you the password saved in step #1.
6. Send this password to the outside email address, and they can now see your private password.

### Expected behaviour
I understand this is the browser, but the users saved passwords should not appear as an option in this entry field.  It's too dangerous, especially for regular users.

### Actual behaviour
The saved passwords should not appear when you click into the folder share password.

### Server configuration

**Operating system:**
Redhat Enterprise Linux 8

**Web server:**
Apache
**Database:**
Maria DB
**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
20.0.8
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 20.0.7
**Where did you install Nextcloud from:**
Downloaded directly from Nextcloud
**Signing status:**
<details>
<summary>Signing status</summary>

```
File not found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - bruteforcesettings: 2.0.1
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_accesscontrol: 1.10.2
  - files_automatedtagging: 1.10.1
  - files_external: 1.11.1
  - files_retention: 1.9.0
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - impersonate: 1.7.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - oauth2: 1.8.0
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - systemtags: 1.10.0
  - twofactor_backupcodes: 1.9.0
  - user_ldap: 1.10.2
  - viewer: 1.4.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - contactsinteraction
  - dashboard
  - encryption
  - files_pdfviewer
  - files_videoplayer
  - firstrunwizard
  - nextcloud_announcements
  - notifications
  - password_policy
  - recommendations
  - survey_client
  - text
  - theming
  - updatenotification
  - user_status
  - weather_status

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "entnc2p",
            "entnc2p.co.pinellas.fl.us",
            "localhost",
            "10.95.134.21",
            "pcgcloud.pinellascounty.org",
            "bayoucloud.pinellascounty.org",
            "hrcloud.pinellascounty.org",
            "oticloud.pinellascounty.org",
            "ombcloud.pinellascounty.org",
            "pwcloud.pinellascounty.org",
            "stormcloud.pinellascounty.org",
            "drscloud_entnc2p"
        ],
        "auth.webauthn.enabled": false,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.8.1",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/entnc2t",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "simpleSignUpLink.shown": false,
        "lost_password_link": "disabled",
        "app_install_overwrite": [
            "files_retention"
        ],
        "maintenance": false,
        "loglevel": 2,
        "theme": "pcgcloud"
    }
}
```
</details>

**Are you using external storage, if yes which one:**  LOCAL

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** ActiveDirectory

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```

```
</details>

### Client configuration
**Browser:** CHROME, IE

**Operating system:** MS WINDOES

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by JJlVAP** [comment]
I ended up disabling my credentials for nextcloud on my password manager (bitwarden) for this reason.

**Comment by szaimen** [comment]
cc @nextcloud/security

**Comment by LukasReschke** [comment]
I am unable to reproduce this on the latest Chrome and demo.nextcloud.com. @daveatpinellas, are you still able to reproduce this on the latest release?

**Comment by daveatpinellas** [comment]
Thank you for reviewing.  I just replicated again and users are doing it by accident still.  Nextcloud is 20.0.10 and Chrome is 91.  This was also reported on other browsers.  This is the technique I used:

* Logged into Nextcloud 20.0.10 with Chrome, and when prompted to save the password in the browser did so.
* Nextcloud instance is configured to always force passwords on all shares
* Share a file to an email address
* Click the (...) next to the email address and the popup appears
* The auto generated password appears
* Click into the password field and backspace out the auto generated password
* When the field is empty, the browser sees this as an empty password field and offers your own credentials
* You can then easily pick your own credentials and it will fill them in and then sends them right to the email recipient.

Users for some reason are drawn into that field and feel they should be tinkering in there and are getting their own passwords submitted.  Here is a screenshot.

![nextcloud_prefill](https://user-images.githubusercontent.com/82096976/124611747-bb343980-de3f-11eb-9203-6aca52f32902.png)
