### ISSUE TITLE
Generic error message if quota exceeded on files_drop upload

### ISSUE THREAD

**Issue by fancycode** [nextcloud/server#26446]
The files_drop JavaScript shows a rather generic error message (`Could not upload "{filename}"`) for all errors during upload:
https://github.com/nextcloud/server/blob/6fcd075730dbd63d5dbb69da0ca5983b51a7240e/apps/files_sharing/js/files_drop.js#L110

It would be better to show a dedicated message if the upload fails due to quota limitations. Happy to provide a PR this is accepted as valid issue.

**Comment by szaimen** [comment]
Please go ahaed :)

**Comment by skjnldsv** [comment]
Fixed since 28
