### ISSUE TITLE
German translation: sharing a link of a file with others: Imperativ of "geben" is "gib" and not "gebe"

### ISSUE THREAD

**Issue by githubmeier** [nextcloud/server#26445]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. log-in into your nextcloud web-client (german language)
2. make sure you have at least one file being shown in the file-browser
3. click the share icon (a side bar opens up)
4. click "Link teilen"
5. the Text next to the "i" symbol shows the following text: "Bitte gebe die benötigten Informationen ein bevor die Freigabe erstellt wird"

### Expected behaviour
The correct german translation is: "Bitte gib die benötigten Informationen ein bevor die Freigabe erstellt wird"

### Actual behaviour
"Bitte gebe die benötigten Informationen ein bevor die Freigabe erstellt wird"

### Server configuration

**Operating system:**
n. a.

**Web server:**
n. a.

**Database:**
n. a.

**PHP version:**
n. a.

**Nextcloud version:** (see Nextcloud admin page)
cannot say for real, but its copyright 2020.

**Updated from an older Nextcloud/ownCloud or fresh install:**
n. a.

**Where did you install Nextcloud from:**
n. a.

**Comment by caugner** [comment]
The Nextcloud translation is managed on [the Transifex platform](https://transifex.com/nextcloud). 

Feel free to sign-up there, join the German translation team and perform the change yourself.

**Comment by kesselb** [comment]
cc @rakekniven

**Comment by rakekniven** [comment]
@githubmeier Fixed. Thanks for reporting.
