### ISSUE TITLE
Translation Issue after upgrading to 10.0.2

### ISSUE THREAD

**Issue by tryncatchDE** [nextcloud/server#2645]
### Expected behaviour
The whole UI should be displayed in German. Like NC 10.0.1.

### Actual behaviour
But after upgrading NC to 10.0.2 the left panel in Administration is displayed in English, while the settings are still in German.

### Server configuration
**Operating system**: maybe Debian

**Web server:** Apache + NGinx Proxy

**Database:** MySQL 5.6.30

**PHP version:** 5.6.28

**Nextcloud version:** 10.0.2

**Updated from an older Nextcloud install:** 10.0.1

**Where did you install Nextcloud from:** Internal Updater

**List of activated apps:**
bookmarks (3rdparty), calendar (3rdparty), contacts (3rdparty), documents (3rdparty), ownnote (3rdparty), tasks (3rdparty)

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 50.0.2

**Operating system:** Ubuntu 16.04LTS

**Comment by nickvergessen** [comment]
Reoccuring with every release

**Comment by nickvergessen** [comment]
Seems to be a 10 only issue

**Comment by nickvergessen** [comment]
Fix is in https://github.com/nextcloud/server/pull/2667
