### ISSUE TITLE
11: Installer does not create database

### ISSUE THREAD

**Issue by lightonflux** [nextcloud/server#2646]
### Steps to reproduce
1. Get Ubuntu 16.04 server, install dependencies (mysql + apache2)
2. Move folder from tar.gz in your web root 
3. Open installer page
4. Enter valid mysql credentials (with CREATE priv) e.g. debian-sys-maint
5. for mysql but use a DB name that does not yet exist

[As ansible](https://github.com/lightonflux/ansible-nextcloud)

### Expected behaviour

NC 11 should create that database. And does that in 10.

### Actual behaviour

NC 11 complains that no database of that name exists 

### Server configuration
**Operating system**:
Ubuntu 16.04 on Digital Ocean (not sure if they use unchanged Ubuntu Server)
 
**Web server:**
Apache2 from repos
**Database:**
Mysql from repos
**PHP version:**
From Ubuntu Repos
**Nextcloud version:** (see Nextcloud admin page)
11
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh tar.gz. install
**Where did you install Nextcloud from:**
The tar file
**Signing status:**
OK

**List of activated apps:**
Default after fresh 11 install

**Are you using encryption:** 

no

**Are you using an external user-backend, if yes which one:** 
no

**Comment by nickvergessen** [comment]
Code is still in place, anything in your log file?
https://github.com/nextcloud/server/blob/2b7d63f56551bcbb67f4104104614ea314158779/lib/private/Setup/MySQL.php#L58-L71

**Comment by lightonflux** [comment]
The normal log? It is empty. 

```
root@nc:/var/www/nextcloud/data# ls 
index.html  nextcloud.log
root@nc:/var/www/nextcloud/data# cat nextcloud.log 
root@nc:/var/www/nextcloud/data# file nextcloud.log 
nextcloud.log: empty
root@nc:/var/www/nextcloud/data# 

```

![bildschirmfoto von 2016-12-13 19-01-00](https://cloud.githubusercontent.com/assets/1377943/21152502/bc8c7c2a-c166-11e6-8759-6826cd7b4c89.png)


So i manually created the db again, just in case nc could not write before finishing the installer. (Now with new location as defined in the webUI.)

```
root@nc:/var/www/nextcloud/data# cd /data
root@nc:/data# ls
appdata_ocpbg3pj1nxp  index.html  test  nextcloud.log
root@nc:/data# cat nextcloud.log 
root@nc:/data# file nextcloud.log 
nextcloud.log: empty
root@nc:/data# 
```

Shall i redo the steps with DEBUG enabled before accessing the install webUI?

**Comment by lightonflux** [comment]
I just realised that i don't know how change the log level without writing to the config file (which does not exist yet.

**Comment by greyltc** [comment]
I'm seeing the same issue. Looks like the database is not being created as it was previously.
