### ISSUE TITLE
Updater performs major update to Nextcloud 21 despite Update notification & Administration Overview advertising patch update to 20.0.9

### ISSUE THREAD

**Issue by caugner** [nextcloud/server#26469]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. See new patch version in update notification: ![grafik](https://user-images.githubusercontent.com/495429/114155408-c00d4e00-9921-11eb-92d6-61419aabd051.png)
2. See same version in Administration / Overview: ![grafik](https://user-images.githubusercontent.com/495429/114155499-dca98600-9921-11eb-8c7f-a408869c8bb4.png)
3. See different version in Updater: ![grafik](https://user-images.githubusercontent.com/495429/114155546-e7641b00-9921-11eb-9778-b33be5f2bbf7.png)

### Expected behaviour
The Updater should update to the version as announced in the update notification and in the Administration / Overview.

### Actual behaviour
The Updater executes a major update instead of a patch update.

### Server configuration

**Operating system:** Ubuntu

**Web server:** Apache 2.4

**Database:** MySQL 5.7.28

**PHP version:** 7.4.14

**Nextcloud version:** 20.0.8

**Updated from an older Nextcloud/ownCloud or fresh install:** ~ ownCloud 5

**Where did you install Nextcloud from:** Updater?

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
n/a
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
n/a
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** Yes / No (one instance each)

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox Browser Nightly 89.0.a1 (2021-04-08)

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
(on demand)
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
(on demand)
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
(on demand)
```
</details>

**Comment by eibex** [comment]
I replicated the admin overview issue too, and did so before noticing this post.

The admin overview was offering 20.0.9, while the server actually updated to 21.0.1 (and now half of my files are unusable since e2ee is not compatible with NC21).

OS: Ubuntu 20.04
Server: Apache2
PHP: 7.4
DB: Postgres 12

**Comment by emtie** [comment]
Hi all,

ran into the same Problem and additionally the occ upgrade command failed with the following:

OS Ubuntu 20.04
Apache: Apache/2.4.41 (Ubuntu)
PHP 7.4-fpm
mysql 8.0.23-0ubuntu0.20.04.1

`
An unhandled exception has been thrown:
TypeError: Argument 2 passed to OC\Comments\Manager::__construct() must implement interface Psr\Log\LoggerInterface, instance of OC\AppFramework\Logger given, called in /var/www/nextcloud/apps/spreed/lib/Chat/CommentsManager.php on line 46 and defined in /var/www/nextcloud/lib/private/Comments/Manager.php:77
Stack trace:
#0 /var/www/nextcloud/apps/spreed/lib/Chat/CommentsManager.php(46): OC\Comments\Manager->__construct()
#1 [internal function]: OCA\Talk\Chat\CommentsManager->__construct()
#2 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(101): ReflectionClass->newInstanceArgs()
#3 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(109): OC\AppFramework\Utility\SimpleContainer->buildClass()
#4 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): OC\AppFramework\Utility\SimpleContainer->resolve()
#5 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(459): OC\AppFramework\Utility\SimpleContainer->query()
#6 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(431): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#7 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query()
#8 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#9 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(101): array_map()
#10 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(109): OC\AppFramework\Utility\SimpleContainer->buildClass()
#11 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): OC\AppFramework\Utility\SimpleContainer->resolve()
#12 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(459): OC\AppFramework\Utility\SimpleContainer->query()
#13 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(431): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#14 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query()
#15 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#16 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(101): array_map()
#17 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(109): OC\AppFramework\Utility\SimpleContainer->buildClass()
#18 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): OC\AppFramework\Utility\SimpleContainer->resolve()
#19 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(459): OC\AppFramework\Utility\SimpleContainer->query()
#20 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(431): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#21 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(87): OC\AppFramework\DependencyInjection\DIContainer->query()
#22 [internal function]: OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
#23 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(101): array_map()
#24 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(109): OC\AppFramework\Utility\SimpleContainer->buildClass()
#25 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(126): OC\AppFramework\Utility\SimpleContainer->resolve()
#26 /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php(459): OC\AppFramework\Utility\SimpleContainer->query()
#27 /var/www/nextcloud/lib/private/ServerContainer.php(146): OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback()
#28 /var/www/nextcloud/lib/private/Repair.php(130): OC\ServerContainer->query()
#29 /var/www/nextcloud/lib/private/legacy/OC_App.php(1047): OC\Repair->addStep()
#30 /var/www/nextcloud/lib/private/legacy/OC_App.php(996): OC_App::executeRepairSteps()
#31 /var/www/nextcloud/lib/private/Installer.php(212): OC_App::updateApp()
#32 /var/www/nextcloud/lib/private/Updater.php(417): OC\Installer->updateAppstoreApp()
#33 /var/www/nextcloud/lib/private/Updater.php(268): OC\Updater->upgradeAppStoreApps()
#34 /var/www/nextcloud/lib/private/Updater.php(132): OC\Updater->doUpgrade()
#35 /var/www/nextcloud/core/Command/Upgrade.php(255): OC\Updater->upgrade()
#36 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#37 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#38 /var/www/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#39 /var/www/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#40 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#41 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#42 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
`

**Comment by caugner** [comment]
> And additionally the occ upgrade command failed with the following:

@emtie Please open a new issue for the occ upgrade failure. I used the Web updater which completed just fine.

**Comment by emtie** [comment]
@caugner thx for your feedback. I am going to do that.

**Comment by toxpal** [comment]
There were tons of complaints about the same problem with version 19.x as well. NC displayed a notification about minor upgrade from v19 to v19.x, but upgrade wizard actually downloaded v20. Seems the issue won't be fixed anytime soon.

**Comment by caugner** [comment]
@AndyScherzinger Is 21.0.1 supposed to be on the stable channel already?

**Comment by bcutter** [comment]
Ran into the same stupid thing. Wanted 20.0.9, got 21.0.1.1. Really annoying because of E2EE now broken https://github.com/nextcloud/end_to_end_encryption/issues/224 !

**Comment by smsm1** [comment]
I ran into this and now I've been hit with the high memory usage in #26530

**Comment by kesselb** [comment]
Fixed by https://github.com/nextcloud/updater_server/pull/558

**Comment by caugner** [comment]
Thanks, I can confirm that the Updater now updates from 20.0.8 to 20.0.9. 👍

**Comment by mlsxlist** [comment]
Worked for me as well. Thanks.
