### ISSUE TITLE
Trouble upgrading from NC20 to 21 with 'loglevel' => 0

### ISSUE THREAD

**Issue by marcogaio** [nextcloud/server#26460]
I've had a private instance on NC that i keep updated, from owncloud till now. All upgrades went smooth.

Upgrading from 20 to 21, the 'occ upgrade' command get stuck, no output at all. PHP start to eat memory, leading to trashing the system, or OOM killer intervention.

Fiddling a bit, i've found that setting log level to the (default) '2' value, fix the upgrade, that went smooth as for previous upgrade.

My system is:
 - LXC unprivileged container, Debian buster
 - standard buster php (7.3.27-1~deb10u1)
 - NC from 20.0.8 to 21.0.0, using Ivan Jurišić excellent debian package
 
Thanks.

**Comment by kesselb** [comment]
```
* Please search the existing issues first, it's likely that your issue was already reported or even fixed.
    - Go to https://github.com/nextcloud and type any word in the top search/command bar. You probably see something like "We couldn’t find any repositories matching ..." then click "Issues" in the left navigation.
    - You can also filter by appending e. g. "state:open" to the search string.
    - More info on search syntax within github: https://help.github.com/articles/searching-issues
```

**Comment by marcogaio** [comment]
Ahem, i've done that yesterday, but probably i've not found a bug that seems relevant to my trouble.

Can point me against the bug for which this is a 'dupe'? Thanks.
