### ISSUE TITLE
The upgrade to 10.0.2 deleted 3rdparty Apps

### ISSUE THREAD

**Issue by tryncatchDE** [nextcloud/server#2647]
### Expected behaviour
The upgrade to 10.0.2 should backup installed Apps and restore them after upgrade.

### Actual behaviour
But after upgrading NC to 10.0.2 all installed 3rdparty Apps was removed. I must install them again. Since this task is going on, the lower tooltip (in this picture) is present whole time while being on this site in the Appstore.

![nc1](https://cloud.githubusercontent.com/assets/24548044/21147247/a862dd32-c154-11e6-9bf4-2e5a225077ff.jpeg)

### Server configuration
**Operating system**: maybe Debian

**Web server:** Apache + NGinx Proxy

**Database:** MySQL 5.6.30

**PHP version:** 5.6.28

**Nextcloud version:** 10.0.2

**Updated from an older Nextcloud install:** 10.0.1

**Where did you install Nextcloud from:** Internal Updater

**List of activated apps:**
bookmarks (3rdparty), calendar (3rdparty), contacts (3rdparty), documents (3rdparty), ownnote (3rdparty), tasks (3rdparty)

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 50.0.2

**Operating system:** Ubuntu 16.04LTS

**Comment by enoch85** [comment]
FYI: https://github.com/Fmstrat/ownnote/pull/329

Also, the ownNote dev has taken a looong vaccation (joke). Haven't seen him commit anything for a while now.

**Comment by MorrisJobke** [comment]
We improved here a lot with the update to 12. Could you try again with 12 and report if still all apps are disabled/removed, because we made quite some changes. Regarding disabled apps: they only stay enabled if you use PHP 7.0+ because there we can catch errors with the apps - in PHP 5.6 not completely.
