### ISSUE TITLE
Nested Group support for Zimbra LDAP integration

### ISSUE THREAD

**Issue by stefan0xC** [nextcloud/server#26478]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
In Zimbra you can have nested distribution lists but the current way membership is checked in the LDAP integration does not resolve group memberships down to accounts and LDAP groups with only groups as members are empty in Nextcloud. So that I have to either add the members manually in a new Nextcloud group or share folders to multiple LDAP groups.

**Describe the solution you'd like**
The membership check should also resolve group accounts recursively to accounts.

**Describe alternatives you've considered**
Alternatively it would be nice to have the ability to define nested groups (#12443) in Nextcloud so I can add multiple LDAP groups (and users) to a new group.

**Additional context**
The nested group flag does not work. This might be a problem with Zimbra not supporting the matching rule in chain state / memberOf function but I don't know.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
