### ISSUE TITLE
Incorrect displaying of popup menu within folders sharing (with editing featuring) over the link

### ISSUE THREAD

**Issue by neerro** [nextcloud/server#26480]
### Steps to reproduce
When folders open for sharing and editing over the link.

### Expected behaviour
Full displaying of popup menu for the first level shared folder. The popup menu have to be moved for some steps right for full displaying. 

### Actual behaviour
Attached pictures are self-explanatory.

### Server configuration

**Operating system:** Linux 5.4.0-70

**Web server:** Apache

**Database:** Maria DB

**PHP version:** 7.4

**Nextcloud version:** 21.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 21.0.0 to 21.0.1

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox last update

### Attached pictures

![pic1](https://user-images.githubusercontent.com/75830569/114235632-211c3c80-9989-11eb-8529-163ca6f6f682.jpg)
![pic2](https://user-images.githubusercontent.com/75830569/114235634-21b4d300-9989-11eb-9f47-677f97b8d045.jpg)
![pic3](https://user-images.githubusercontent.com/75830569/114235635-224d6980-9989-11eb-8005-2db6969879ba.jpg)

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/27588

**Comment by neerro** [comment]
The issue is still exist but I couldn't find the issue mentioned on the link above with number 27588.

**Comment by szaimen** [comment]
This was fixed in https://github.com/nextcloud/text/pull/1574
