### ISSUE TITLE
Handle non-accessible /proc more gracefully

### ISSUE THREAD

**Issue by mbiebl** [nextcloud/server#2648]
Version: 11.0.0

My hosting provider is all-inkl.com. In that hosting environment I do not have access to /proc and therefore /proc/meminfo.

When accessing the "Server Info" page as admin, "CPU Load" shows
Load average: undefined (Last minute)
"Memory usage" shows
Memory info not available

In the log file I get flodded with messages like this
```
	file_get_contents(/proc/meminfo): failed to open stream: Permission denied at /www/htdocs/xxxxx/nextcloud/apps/serverinfo/lib/SystemStatistics.php#71
```

It would be nice if nextcloud would handle a non-accessible /proc more gracefully, and not floods the log file.
Also, the "Load average: undefined" message should be improved in such a case

**Comment by nickvergessen** [comment]
Can i ask you to reopen your issue at https://github.com/nextcloud/serverinfo ?
