### ISSUE TITLE
Server setup verification

### ISSUE THREAD

**Issue by HiranChaudhuri** [nextcloud/server#26492]
It seems there are numerous problems related to faulty server setups. Especially the configuration of a reverse proxy seems to require some wisdom - but even if you you got it right the very next day you may run into issues. Examples are https://github.com/nextcloud/android/issues/6576 and https://help.nextcloud.com/t/nextcloud-immediate-white-screen-empty-response/93713.

So I suggest to create a verification  procedure that ensures some setup is good or not. To ease this, an application could be created that will run enough diagnostics to pinpoint to some problem or certify some installation is good to be used. This application could verify setups with and without reverse proxy the same way and thus be used very versatile.

An advanced version of this diagnostic application could then not only list problems but probably point to fixing procedures in the wiki once they are known.

**Comment by acsfer** [comment]
IMO, this is the job of server administrator...
Onte thing is check for dependencies, another is check for a server setup.

**Comment by HiranChaudhuri** [comment]
I am running my own nextcloud installation (not unusual I guess). In this case I am the server administrator, and regardless how much documentation I read or how many forum questions I ask, there is still something that does not work.

Meanwhile I 'repaired' the web UI, verified that my mobiles and desktop applications can share calendar entries and contacts. But still the Nextcloud app cannot connect and I have no means of finding out what is missing. Tried to figure out via https://github.com/nextcloud/android/issues/8242 but all I get is "your server setup is wrong".

Agreed, this is the job of the server administrator. But what is this guy going to do?

**Comment by szaimen** [comment]
cc @nextcloud/server-triage is this feasible?

**Comment by artonge** [comment]
Isn't this what the Overview panel in the settings already does ? Unfortunately, there is a million reason why a server could be broken so it is hard to track them all. There is also https://scan.nextcloud.com/ for security.

@HiranChaudhuri were you thinking of something else ?

**Comment by artonge** [comment]
FYI: You can submit pull requests to add more checks in this file: https://github.com/nextcloud/server/blob/master/apps/settings/lib/Controller/CheckSetupController.php :)
