### ISSUE TITLE
CSP Image not load

### ISSUE THREAD

**Issue by TutoRapide** [nextcloud/server#26498]
Hello,
I have a small problem with the profile images (contact) not loading. Due to a CSP blocking which is the following

![sessionID](https://sharemedia.tutorapide.xyz/k2Xy5G30.png)

`Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "img-src 'self' data: blob:".`

### Server configuration

**Operating system: debian 10**

**Web server: nginx**

**Database: mysql**

**PHP version: 7.4**

**Nextcloud version: 20.0.9** 

#### Browser

Chrome ,
Opera GX,
Firefox,
Vivaldi.

Ps: Sorry for my english , I am french

**Comment by acsfer** [comment]
Hi, please reach the forum first for issues (Github for bug reports) next time ;-)
And check https://help.nextcloud.com/t/nextcloud-wont-load-any-mixed-content/13565/2
