### ISSUE TITLE
Nextcloud server 21 installation erro

### ISSUE THREAD

**Issue by timbabcock** [nextcloud/server#26490]
An unhandled exception has been thrown:
Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection timed out in /media/external/nextcloud/lib/private/DB/Connection.php:85

**Comment by timbabcock** [comment]
MySQL server stops during the upgrade process and has to be restarted manually.  Restarted MySQL server manually.  When manual update was performed (several times that database server was restared).
When ./occ install was started, the installation stops at workflow engine.

Can the workflow app be removed too if the app or database table is corrupted?

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
