### ISSUE TITLE
WebDav access

### ISSUE THREAD

**Issue by miroklarin** [nextcloud/server#26506]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. fresh install v20 from tar (port 80, 443, root /var/www/nextcloud) + nginx (+doc config) + openmediavault (port 81)
2.
3.

### Expected behaviour
Navigate to files, contacts should display files and contacts. Should be able to sync contact using Dav capable apps. Should be able to browse files with Nextclud Android App...

### Actual behaviour
Any request to remote.php fails with 500

`nextcloud.log`

```
{"reqId":"aObiUFPbgO9Ghis6dBDL","level":3,"time":"2021-04-12T00:27:33+00:00","remoteAddr":"192.168.0.201","user":"admin","app":"remote","method":"PROPFIND","url":"/remote.php/dav/","message":{"Exception":"TypeError","Message":"substr() expects parameter 1 to be string, int given","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/sabre/http/lib/Sapi.php","line":211,"function":"substr","args":[6,0,5]},{"file":"/var/www/nextcloud/3rdparty/sabre/http/lib/Sapi.php","line":52,"function":"createFromServerArray","class":"Sabre\\HTTP\\Sapi","type":"::","args":[{"PATH":"/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","0":"C.UTF-8","SHELL":"/bin/bash","HOSTNAME":"","USER":"www-data","1":"And 42 more entries, set log level to debug to see all entries"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":233,"function":"getRequest","class":"Sabre\\HTTP\\Sapi","type":"::","args":[]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Server.php","line":43,"function":"__construct","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"OCA\\DAV\\Connector\\Sabre\\CachingTree"}]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":97,"function":"__construct","class":"OCA\\DAV\\Connector\\Sabre\\Server","type":"->","args":[{"__class__":"OCA\\DAV\\Connector\\Sabre\\CachingTree"}]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":34,"function":"__construct","class":"OCA\\DAV\\Server","type":"->","args":[{"__class__":"OC\\AppFramework\\Http\\Request"},"/remote.php/dav/"]},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/3rdparty/sabre/http/lib/Sapi.php","Line":211,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0","version":"21.0.1.1"}
```

workaround `nextcloud/3rdparty/sabre/http/lib/Sapi.php`
```
 default:
                    if (gettype($key) == "string" && 'HTTP_' === substr($key, 0, 5)) {
```

### Server configuration

**Operating system:**

`raspberryPiLinux raspberrypi 5.10.17-v7l+`

**Web server:**

`nginx 1.14.2-2+deb10u3`

**Database:**

`mariadb-server/stable,now 1:10.3.27-0+deb10u1`

**PHP version:**

`PHP 7.3.27-1~deb10u1`

**Nextcloud version:** (see Nextcloud admin page)

`nextcloud-21.0.1.tar.bz2`

**Updated from an older Nextcloud/ownCloud or fresh install:**

same error was on fresh install v20 then replaced with v21 but ./data, ./config and database remained same

**Where did you install Nextcloud from:**

`nextcloud-21.0.1.tar.bz2`

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
`No errors have been found`

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

smb is running and mapping different partition, but not used by nextcloud

**Are you using encryption:** yes/no

turned it on and off after first installation, was on 5 seconds, nothing was done

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

**Comment by miroklarin** [comment]
Updated to v22, still same issue
```
{"reqId":"5l2735TScZ3qknjBBWQt","level":3,"time":"2021-09-10T08:30:06+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"--","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/xxxx/","message":"TypeError: substr() expects parameter 1 to be string, int given at /var/www/nextcloud/3rdparty/sabre/http/lib/Sapi.php#211","userAgent":"Mozilla/5.0 (Windows) mirall/3.3.3stable-Win64 (build 20210903) (Nextcloud, windows-10.0.19042 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"22.1.0.1"}

```

**Comment by szaimen** [comment]
Honestly, this sounds like a setup issue to me. You might be able to get some help on https://help.nextcloud.com

**Comment by miroklarin** [comment]
I used nginx config provided in documentation, but I have some custom things around
Not sure why http header key would be integer type
Will investigate more
