### ISSUE TITLE
Update server branch in travis files of apps

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#2650]
- [x] https://github.com/nextcloud/templateeditor/pull/13
- [x] https://github.com/nextcloud/activity/pull/89
- [x] https://github.com/nextcloud/survey_client/pull/44
- [x] https://github.com/nextcloud/serverinfo/pull/66
- [x] https://github.com/nextcloud/password_policy/pull/30
- [x] https://github.com/nextcloud/notifications/pull/51
- [x] https://github.com/nextcloud/nextcloud_announcements/pull/18
- [x] https://github.com/nextcloud/firstrunwizard/pull/27
- [x] https://github.com/nextcloud/files_texteditor/pull/21
- [x] https://github.com/nextcloud/files_retention/pull/13
- [x] https://github.com/nextcloud/files_pdfviewer/pull/16
- [x] https://github.com/nextcloud/files_automatedtagging/pull/19
- [x] https://github.com/nextcloud/files_accesscontrol/pull/49

@LukasReschke @MorrisJobke @rullzer

**Comment by rullzer** [comment]
All done => Close
