### ISSUE TITLE
Theming Cross-compatibility : Named parameter "file_id" does not have a bound value.

### ISSUE THREAD

**Issue by Ad3nine** [nextcloud/server#26507]
When uploading a .png, .jpeg, .bpm, or .tiff file as a Login image, I receive the following message : _Named parameter "file_id" does not have a bound value._

The issue disappears when disabling the app : [EPUB/CBZ/PDF ebook reader](https://github.com/e-alfred/epubreader)

{"reqId":"BE8NzK7ptJn70ZSyConX","level":3,"time":"2021-04-12T01:45:05+00:00","remoteAddr":"","user":"--","app":"documentserver_community","method":"","url":"--","message":{"Exception":"Doctrine\\DBAL\\ArrayParameters\\Exception\\MissingNamedParameter","Message":"Named parameter \"file_id\" does not have a bound value.","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/ExpandArrayParameters.php","line":64,"function":"new","class":"Doctrine\\DBAL\\ArrayParameters\\Exception\\MissingNamedParameter","type":"::"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/SQL/Parser.php","line":79,"function":"acceptNamedParameter","class":"Doctrine\\DBAL\\ExpandArrayParameters","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/SQL/Parser.php","line":96,"function":"Doctrine\\DBAL\\SQL\\{closure}","class":"Doctrine\\DBAL\\SQL\\Parser","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1692,"function":"parse","class":"Doctrine\\DBAL\\SQL\\Parser","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1128,"function":"expandArrayParameters","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/Connection.php","line":257,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":213,"function":"executeStatement","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":286,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/epubreader/lib/Hooks.php","line":50,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/nextcloud/apps/epubreader/lib/Hooks.php","line":27,"function":"deleteFile","class":"OCA\\Epubreader\\Hooks","type":"::"},{"function":"OCA\\Epubreader\\{closure}","class":"OCA\\Epubreader\\Hooks","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Hooks/EmitterTrait.php","line":107,"function":"call_user_func_array"},{"file":"/var/www/nextcloud/lib/private/Hooks/PublicEmitter.php","line":41,"function":"emit","class":"OC\\Hooks\\BasicEmitter","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/Root.php","line":139,"function":"emit","class":"OC\\Hooks\\PublicEmitter","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/Node.php","line":117,"function":"emit","class":"OC\\Files\\Node\\Root","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/Folder.php","line":400,"function":"sendHooks","class":"OC\\Files\\Node\\Node","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/SimpleFS/SimpleFolder.php","line":68,"function":"delete","class":"OC\\Files\\Node\\Folder","type":"->"},{"file":"/var/www/nextcloud/apps/documentserver_community/lib/Document/DocumentStore.php","line":219,"function":"delete","class":"OC\\Files\\SimpleFS\\SimpleFolder","type":"->"},{"file":"/var/www/nextcloud/apps/documentserver_community/lib/Document/SaveHandler.php","line":64,"function":"closeDocument","class":"OCA\\DocumentServer\\Document\\DocumentStore","type":"->"},{"file":"/var/www/nextcloud/apps/documentserver_community/lib/BackgroundJob/Cleanup.php","line":71,"function":"flushChanges","class":"OCA\\DocumentServer\\Document\\SaveHandler","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":80,"function":"run","class":"OCA\\DocumentServer\\BackgroundJob\\Cleanup","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":128,"function":"execute","class":"OCP\\BackgroundJob\\Job","type":"->"}],"File":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/ArrayParameters/Exception/MissingNamedParameter.php","Line":17,"CustomMessage":"Error while applying changes for document 717740893"},"userAgent":"--","version":"21.0.0.18","id":"6073a640bb8c9"}

**Comment by kesselb** [comment]
Please report this issue to https://github.com/e-alfred/epubreader
