### ISSUE TITLE
Incorrect warning in the setup checks "PHP output_buffering must be disabled"

### ISSUE THREAD

**Issue by castillo92** [nextcloud/server#26501]
### Steps to reproduce
1. Upgrade to NC 21.0.1
2. Upgrade to php8.0
3. Access NextCloud and visist the Settings - Setup Warnings
4. Found: `Warning: “PHP configuration option output_buffering must be disabled”`

### Expected behaviour
If `output_buffering = Off`, it should not show any warning.

### Actual behaviour
`output_buffering` must be setup as `zero` to avoid the warnings.

As I could se in NC Docs: https://docs.nextcloud.com/server/stable/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=big%20files#configuring-php

I changed the parameters `output_buffering = 0` inside to avoid the warning. 

> 	sudo nano /var/www/nextcloud/.user.ini
> 	sudo nano /etc/php/8.0/fpm/php.ini
> 	sudo nano /var/www/nextcloud/.htaccess

My question is: why `zero` instead of `Off`, because php.ini calls `disabled` as `Off`

### Server configuration

**Operating system:** Debian 10

**Web server:** Apache2

**Database:** MariaDB

**PHP version:** 8.0.3

**Nextcloud version:** 21.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from v20.0.4

**Comment by acsfer** [comment]
Check https://github.com/nextcloud/server/pull/23824

**Comment by castillo92** [comment]
Thanks to @acsfer to remember the right thread.

I search in this files `output_buffering` and I found `'Off'` instead of directly `Off` in the `user.ini`. Then I restart the services and solve the warnings.
```
sudo nano /etc/php/8.0/fpm/php.ini
sudo nano /var/www/nextcloud/.user.ini
sudo nano /var/www/nextcloud/.htaccess
sudo systemctl restart php8.0-fpm
sudo systemctl restart apache2
```

And as we can see in https://github.com/php/php-src/blob/master/php.ini-production#L56

```
; Boolean flags can be turned on using the values 1, On, True or Yes.
; They can be turned off using the values 0, Off, False or No.
```
But to avoid parsing problems or future issues... I am going to set zero.

**Comment by castillo92** [comment]
I found that Apache2 is not overriding the PHP8 configuration with the .htaccess:

https://github.com/nextcloud/server/blob/4be2e1601e80a09aebac57eabb0aaf60e744362e/.htaccess#L51-L58

Changing `output_buffering` does not trigger any warning in PHP8.

I launched the OCC command:
sudo -u www-data php /var/www/nextcloud/occ maintenance:update:htaccess


In the `.htaccess` file, changed `<IfModule mod_php7.c>` to `<IfModule mod_php8.c>` and tried:
```
php_value output_buffering 512
php_value output_buffering '512'
```
Changed the parameter in the files:
```
sudo nano /etc/php/8.0/apache2/php.ini
sudo nano /etc/php/8.0/fpm/php.ini
```
But nothing seems to trigger the warning.


Only changing `output_buffering` to a value `>0` in `.user.ini` creates the warning.

This is a bug?

**Comment by castillo92** [comment]
> @castillo92:
> 
> > I found that Apache2 is not overriding the PHP8 configuration with the .htaccess
> 
> If you're using PHP in FPM mode, the .htaccess one is irrelevant since it's ignored.

Wooow! Long time ago from the opening of this bug

Could you please tell me how can I check if I am using FPM mode?

**Comment by joshtrichards** [comment]
I suppose a quick and dirty method would be to see if you have any `php-fpm` processes running (assuming your web and app layers are running on the same host).
