### ISSUE TITLE
Templates: whiteboard related templates are not recognized

### ISSUE THREAD

**Issue by dacoex** [nextcloud/server#26504]
### Steps to reproduce
1. Define a template direcory
2. Upload the templates `Impact effort matrix.whiteboard` & SWOT `analysis.whiteboard` from `nextcloud/core/skeleton/Templates/` of [nextcloud-21.0.1.zip](https://download.nextcloud.com/server/releases/nextcloud-21.0.1.zip) 
3. Create a new whiteboard file

### Expected behaviour
The dialogue should offer me the templates above to choose from

### Actual behaviour
a fresh, blank new whiteboard is created but not from the template

### Server configuration

**Operating system:** 
Linux

**Web server:** 
Apache

**Database:**
Mysql

**PHP version:**
7

**Nextcloud version:** (see Nextcloud admin page)
21.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from an older Nextcloud

**Where did you install Nextcloud from:**
stable canal

**Comment by szaimen** [comment]
I can reproduce this on NC21.0.2. 

cc @juliushaertl

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by juliushaertl** [comment]
Templates are only copied over to new users on the first login, so this is expected behaviour.
