### ISSUE TITLE
TinyMCE and ownNote does not work

### ISSUE THREAD

**Issue by Revertron** [nextcloud/server#2651]
I was using the ownNote app for ownCloud, and successfully migrated to Nextcloud just after the fork.
But now, starting from NC 11 betas I can not use it because of 'unsafe-eval' Content-Security-Policy.

It uses TinyMCE for editor, but it is not working - I can't see and edit my notes.

Is there a workaround or I need just to say goodbye to this app with a working Android client? :(

**Comment by georgehrke** [comment]
have you contacted the respective developers yet?

**Comment by Revertron** [comment]
I think that the developer of ownNote is gone somewhere and is not supporting his project.

**Comment by LukasReschke** [comment]
In this case there is not much that we can do. The hardened CSP may require some apps to adjust their code.

**Comment by q4z1** [comment]
I did a workaround for that - disabling the nonce feature and enabling unsafe-line js:

https://github.com/Fmstrat/ownnote/issues/333
