### ISSUE TITLE
cron and occ command line tools don't work after upgrade to 21.0.1

### ISSUE THREAD

**Issue by hul51u** [nextcloud/server#26519]
### Steps to reproduce
1. Upgrad from 20.0.8 to 21.0.0
2. In my case there was an update error, I hat to manually disable maintenance mode in config.php. (occ maintance-mode:off did not work)
3. try to run an command line php script like occ, cron or status.php. Even simple scripts like occ app:list 

### Expected behaviour
Normal behaviour please.

### Actual behaviour
Extremly high cpu load, webserver and other services almost completly knocked out until the process kills itself or gets killed by the os. Status "Killed" after some time (up to several minutes).
Every cron job fails after several minuets. Server is knocked out every time a nextcloud cron job runs.

### Server configuration

**Operating system:**
Ubuntu 20.04

**Web server:**
 Apache/2.4.41 (Ubuntu)

**Database:**
 10.3.25-MariaDB-0ubuntu0.20.04.1 Ubuntu 20.04

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
21.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 20.0.8

**Signing status:**
<details>
<summary>Signing status</summary>

```
https://*/index.php/settings/integrity/failed
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```

<?php
$CONFIG = array (
  'instanceid' => '*',
  'passwordsalt' => '*',
  'secret' => '*',
  'trusted_domains' =>
  array (
    0 => '*',
    1 => '192.168.178.41',
    2 => '192.168.178.50',
  ),
  'datadirectory' => '/media/*',
  'dbtype' => 'mysql',
  'version' => '21.0.1.1',
  'overwrite.cli.url' => 'https://*',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '*',
  'dbpassword' => '*',
  'installed' => true,
  'mysql.utf8mb4' => true,
  'maintenance' => false,
  'mail_from_address' => '*',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => '*',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => '*',
  'mail_smtpname' => '*de',
  'mail_smtppassword' => '***',
  'theme' => '',
  'loglevel' => 0,
  'updater.release.channel' => 'stable',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'updater.secret' => '*****',
  'app_install_overwrite' =>
  array (
    0 => 'whiteboard',
    1 => 'spreed',
    2 => 'twofactor_totp',
    3 => 'socialsharing_email',
  ),
);

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb and local

**Are you using encryption:** yes/no
no

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
[no app in context] Info: Deprecated event type for {"[object] (OCP\SabrePluginEvent)":{"*statusCode":200,"*message":"","*server":{"[object] (OCA\DAV\Connector\Sabre\Server)":{"tree":"[object] (OCA\DAV\Connector\Sabre\ObjectTree)","*baseUri":"/nextcloud/remote.php/webdav/","httpResponse":"[object] (Sabre\HTTP\Response)","httpRequest":"[object] (Sabre\HTTP\Request)","sapi":"[object] (Sabre\HTTP\Sapi)","*plugins":[],"transactionType":null,"protectedProperties":{"...":"Over 20 items, aborting normalization"},"debugExceptions":false,"resourceTypeMapping":[],"enablePropfindDepthInfinity":true,"xml":"[object] (Sabre\DAV\Xml\Service)","*logger":null,"*listeners":{"...":"Over 20 items, aborting normalization"},"*wildcardListeners":[],"*listenerIndex":[]}},"Symfony\Contracts\EventDispatcher\EventpropagationStopped":false}}: null

PROPFIND /nextcloud/remote.php/webdav/*********
from ************ by ******* at 2021-04-12T11:33:31+00:00
```
</details>

**Comment by WinRose-C** [comment]
me to.
PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /usr/*******/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php on line 133

**Comment by kesselb** [comment]
Looks like https://github.com/nextcloud/server/issues/25742.
