### ISSUE TITLE
OAuth2 does not return id_token

### ISSUE THREAD

**Issue by MeiKatz** [nextcloud/server#26517]
### Expected behaviour
The OAuth2 api should return an `id_token`.

### Actual behaviour
It doesn't. It only returns `access_token`, `token_type`, `expires_in`, `refresh_token` and `user_id` **but not** `id_token`.

### Details
Details doesn't matter because it is not in the code but should.

### Problem
I try to connect my WordPress with NextCloud and use NextCloud as the identity provider. The plugin I am using for this (https://github.com/oidc-wp/openid-connect-generic) expects an `id_token` as result of calling `/apps/oauth2/api/v1/token` ([OauthApiController#getToken](https://github.com/nextcloud/server/blob/905e1918d2796b9a79025283cd6edf2c40f49d77/apps/oauth2/lib/Controller/OauthApiController.php#L93)) but it cannot because it is not implemented (but it [should](https://openid.net/specs/openid-connect-core-1_0.html#TokenResponse)). Is there any reason why?

**Comment by rullzer** [comment]
id_token is not part of the Oauth2 standard
It is from OIDC. Which we do not have currently

**Comment by MeiKatz** [comment]
So, if somebody would do the work and would implement it, it would be added? I am no expert here but I think I can give it a try.

**Comment by rullzer** [comment]
There isa  PR with this. The main issue is that we'd first need full acceptance and integration tests on the OAuth endpoint. So that we know we don't break things.

**Comment by szaimen** [comment]
@MeiKatz feel free to create a PR for discussion. :)
Thank you!
