### ISSUE TITLE
Load a custom page before index.php with cookie set up

### ISSUE THREAD

**Issue by biraj7** [nextcloud/server#26528]
Hi Nextcloud dev team,

I've an internal requirement that I must display an 'agreement' page prior users login to upload files. It's right below the contributors email in /var/www/nextcloud/index.php file. 

`function checkCookie() {
  $cookie = 'eula_agree';
  if (isset($_COOKIE[$cookie]) && $_COOKIE[$cookie] == 1) {
    return TRUE;
  }
  return FALSE;
}
if (!checkCookie()) {
  require 'agreement.html';
  die();
}
require_once __DIR__ . '/lib/versioncheck.php';``

While there is no issue uploading files, but we hit inception (that the blank page pops up randomly) while downloading the file. Upon t-shooting I've noticed that when I take out the custom code block there is no issue. 

Can someone please review/test this case. It will be greatly appreciated. It's been a week I'm yet to resolve the issue. : (

Thanks for your help and understanding in advance. 

Thanks,
Biraj

**Comment by acsfer** [comment]
Please use https://help.nextcloud.com
Github is dedicated for bug reports only, not customizations.

Thanks for understanding 👍
