### ISSUE TITLE
Update app version and requirement in master branch

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#2652]
- [x] https://github.com/nextcloud/notifications/pull/52
- [x] https://github.com/nextcloud/activity/pull/90
- [x] https://github.com/nextcloud/nextcloud_announcements/pull/19
- [x] https://github.com/nextcloud/templateeditor/pull/14
- [x] https://github.com/nextcloud/survey_client/pull/45
- [x] https://github.com/nextcloud/serverinfo/pull/67
- [x] https://github.com/nextcloud/password_policy/pull/31
- [x] https://github.com/nextcloud/firstrunwizard/pull/28 
- [x] https://github.com/nextcloud/files_texteditor/pull/22
- [x] https://github.com/nextcloud/files_retention/pull/14
- [x] https://github.com/nextcloud/files_pdfviewer/pull/17
- [x] https://github.com/nextcloud/files_automatedtagging/pull/20
- [x] https://github.com/nextcloud/files_accesscontrol/pull/50
- [x] https://github.com/nextcloud/user_saml/pull/57
- [x] https://github.com/nextcloud/files_videoplayer/pull/15

@MorrisJobke @LukasReschke @rullzer

**Comment by rullzer** [comment]
Requires https://github.com/nextcloud/server/pull/2654

**Comment by rullzer** [comment]
All done!
