### ISSUE TITLE
Missing avatar menu entry when email is set to private

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#26537]
## Steps to reproduce
1. Create a user called "user_private"
1. Login as "user_private"
1. Set an email address
1. Set its scope to "Private"
1. Create a user called "user_trusted"
1. Login as "user_trusted"
1. Set an email address
1. Set its scope to "Trusted"
1. Login as a third non-admin user
1. Create a conversation
1. Invite both user_* users
1. Open the participant panel
1. Open the avatar menu of both

### Expected behaviour
Avatar menu of "user_trusted" has two entries "Talk to user_trusted" and one with the email address.
Avatar menu of "user_private" has only one entry "Talk to user_private" without email address.

### Actual behaviour
Avatar menu of "user_trusted" works.
Avatar menu of "user_private" does not open at all!

## Talk app

Happens on Talk stable21 (640939a84fe271a91d3b4f5fdb2a27c216858d7d) with server stable21 (83b7b6f4748c154e3fb5bb4203e3668d526a1619)
Works works fine on Talk master (ff87cab42544a62278d3a797f8e089f397e09b4f) with server master (6b4cfc580588b459fb3ca6053f645633241fdd7a)

## Analysis

Could be either related to vue library differences or some changes in the user menu backend logic.
Potentially a regression also.

**Comment by szaimen** [comment]
I suppose this is still valid on NC21.0.3?
