### ISSUE TITLE
User quota set to 10gb but user only seeing 1003.2 MB .

### ISSUE THREAD

**Issue by meldarionqeusse** [nextcloud/server#26538]
I have set the quota to 10GB from my admin account. 
![image](https://user-images.githubusercontent.com/21668964/114566689-d04f6100-9c72-11eb-8bc5-332d08b2e45b.png)

But the user still sees this :
![image](https://user-images.githubusercontent.com/21668964/114566618-bf9eeb00-9c72-11eb-9f81-37f4fac93890.png)

Setting the quota to unlimited updates the user side to this: ![image](https://user-images.githubusercontent.com/21668964/114566854-f70d9780-9c72-11eb-9702-86af58a0ce2e.png). And setting the limit to 500 mb updates to this: 
![image](https://user-images.githubusercontent.com/21668964/114566946-1278a280-9c73-11eb-9b4a-7e6a30dfc8df.png)

The problem occurs with values above 1GB. I am running Nextcloud 21.0.1. Any help on this issue would be greatly appreciated. Thank you

**Comment by newhinton** [comment]
Check if your nextcloud instance has enough free raw storage.
If your hard disk only has 2Gb free space left, Nextcloud reduces the assigned quota by the missing amount. (At least it behaved this way a few versions back, but this may be the cause and easy to check)

**Comment by meldarionqeusse** [comment]
I feel like an utter idiot. I forgot I moved my data folder because I had to upgrade and I was certain I had enough storage space. Thanks for the help
