### ISSUE TITLE
Sharing api do not throws on existing share creation

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#26532]
After https://github.com/nextcloud/server/pull/25533

Now we can add the same share an unlimited amount of times. Frontend is broken!
Having the api NOT throw on conflict seems like a bad idea to me. Please fix this for 22!
@icewind1991 @nickvergessen @rullzer

**Comment by nickvergessen** [comment]
Maybe it should just send the notification and stuff and then throw?

**Comment by skjnldsv** [comment]
This is a blocker for 22 btw :)

**Comment by blizzz** [comment]
> This is a blocker for 22 btw :)

~~22~~ 24

**Comment by blizzz** [comment]
maybe a blocker for 26 now? :eyes:

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
