### ISSUE TITLE
External storage support - SMB - cannot access files

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/server#26549]
Hi,

I have a folder "scans" from my scanner mounted via SMB/CIFS (localhost)
Since my upgrade to 21.0.1, I cannot download / open files from that folder.

Usually I'm scanning a doc, the PDF appears in NC, and I can read the PDF.
That's no long working...

**Comment by szaimen** [comment]
Duplicate of https://github.com/nextcloud/server/issues/26457
