### ISSUE TITLE
Search for folders results in parent directory

### ISSUE THREAD

**Issue by AlbiWe** [nextcloud/server#26546]
If one search for a folder and found it, the click on it leads to the parent directory. If this includes several thousand directories or files, the result is unusable.

If the search result is a directory, clicking on it should either show that directory at the top of the list or lead into that directory.

**Comment by szaimen** [comment]
Related to https://github.com/nextcloud/server/issues/22541

**Comment by szaimen** [comment]
Lets track this in #22541
