### ISSUE TITLE
New Folder Inputfield cut off

### ISSUE THREAD

**Issue by newhinton** [nextcloud/server#26554]
In the Copy/Move Dialog of the Filesapp, creating a new folder is not possible when the current folderpath is too long. It moves out of the modal, and the "create"-button is hidden and does not react to the enter-key. 

The inputfield should open to its left, not its right when there is not enough space. Also, when opened, it should react to the enter-key

![grafik](https://user-images.githubusercontent.com/25279821/114669255-f708a880-9d01-11eb-84a1-07e147ae8a7b.png)

**Comment by szaimen** [comment]
I can reproduce this on NC22 RC2

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
