### ISSUE TITLE
Email invitation sent out when configured not to

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#26561]
### Steps to reproduce
1. Create an event via web UI
2. Add an attendee (regardless if registered user or email address)
3. Open the ... menu for the attendee
4. Uncheck "Send e-mail"
5. Hit "save" (or "update")

### Expected behaviour
Attendee doesn't receive an email

### Actual behaviour
Attendee receives invitation email - as if the checkbox had never been unchecked

### Calendar app
**Calendar app version:** 2.1.3

### Server configuration

**Nextcloud Version:** 21.0.0

**Comment by szaimen** [comment]
I suppose this is still valid on NC21.0.3?

**Comment by siccovansas** [comment]
@szaimen this is still valid on NC22.1.1.

Additionally/related, when I add an attendee, below their name it says 'Invitation sent.' even before I click on 'Save'. I deselect 'Send email' and only after I click 'Save' the email is send. So showing 'Invitation sent.' is not true until I click save. And then again an email should not be sent if I deselect 'Send email'.

As always, thanks for making this great software!

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
