### ISSUE TITLE
PHP8 in the .htaccess

### ISSUE THREAD

**Issue by castillo92** [nextcloud/server#26569]
Should be moddified L51 or add a new block to consider `<IfModule mod_php8.c> ` 

https://github.com/nextcloud/server/blob/8ef920fdf90bc54d6f17134ebd80a71db2f9d8ea/.htaccess#L51-L58

**Comment by marcos-guerrero** [comment]
In apache2 with mod_php php8 the name of the module is mod_php.c so the text that should be used must start with
`<IfModule mod_php.c>`
without the 8
