### ISSUE TITLE
Stay logged in not displaying

### ISSUE THREAD

**Issue by ram0042** [nextcloud/server#2656]
### Steps to reproduce
1. Navigate to nextcloud instance.
2. Look for the "Stay logged in" check box
### Expected behaviour
Find the "Say logged in" check box
### Actual behaviour

The login page appears
### Server configuration

**Operating system**: GNU/linux

**Web server:** nginx

**Database:** mariadb

**PHP version:** 7.0.13

**Nextcloud version:** 11.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Manually upgraded from a fresh install

**Where did you install Nextcloud from:** I downloaded a tar.gz archive

**Signing status:**
<details>
<summary>

Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

</details>

**List of activated apps:**
<details>
<summary>

App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

</details>

**The content of config/config.php:**
<details>
<summary>

Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

<details>
<summary>

LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

</details>
### Client configuration

**Browser:**

**Operating system:**
#### Web server error log

<details>
<summary>

Web server error log</summary>

```
Insert your webserver log here
```

</details>
#### Nextcloud log (data/nextcloud.log)

<details>
<summary>

Nextcloud log</summary>

```
Insert your Nextcloud log here
```

</details>
#### Browser log

<details>
<summary>

Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by LukasReschke** [comment]
Do you happen to have the files_external app enabled? This one is at the moment not compatible with the remember me login from what I can remember.

**Comment by ram0042** [comment]
I think I have external storage app enabled. Is that the one?

**Comment by LukasReschke** [comment]
Yep.

**Comment by ram0042** [comment]
Is that a requirement or is it an issue to not display the logged in box?

**Comment by LukasReschke** [comment]
If the external storage app is enabled then the remember me box is currently not displayed due to incompatibilities. This is something that we want to address in the future, but at the moment the only solution here is to disable the files_external app.

Closing since there is already a ticket about this somewhere.

**Comment by ram0042** [comment]
Got it. Thanks.
