### ISSUE TITLE
Provide JS-Only version of OCA.Search

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/server#2657]
It would be good to have a js-only version of OCA.Search.
OCA.Search requires you to implement PHP APIs at the moment.
This is not practical for apps like Calendar or Contacts, which don't store the data on themselves.

https://github.com/nextcloud/server/blob/b4f36d44c43aac0efdc6c70ff8e46473341a9bfe/lib/private/Search.php#L59L82
https://github.com/nextcloud/server/blob/d2fab66d49b6f13b9afd4817f064d8531303142f/core/search/js/search.js#L135L142

**Comment by nickvergessen** [comment]
Sounds good to me, @nextcloud/javascript
