### ISSUE TITLE
Upgrade to 19.0.10 need help !

### ISSUE THREAD

**Issue by MootoolsSoftware** [nextcloud/server#26577]
Hello,

I first have the following error upgrading to 19.0.10:

      _Étape de réparation : Repair MySQL collation
      Informations de réparation : Change row format for oc_addressbooks ...
      Informations de réparation : Change collation for oc_addressbooks ...
      Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_addressbooks CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes_

I look at #15058 :

1. I have no access to the conf file and modify innodb_large_prefix.
2. INNODB utf8 VARCHAR(255)
    INNODB utf8mb4 VARCHAR(191)
    does not work in the phpMyAdmin

So I applied :

    _ALTER TABLE oc_addressbooks MODIFY COLUMN principaluri VARCHAR (191);
    ALTER TABLE oc_addressbooks MODIFY COLUMN displayname VARCHAR (191);
    ALTER TABLE oc_addressbooks MODIFY COLUMN uri VARCHAR (191);
    ALTER TABLE oc_addressbooks MODIFY COLUMN description VARCHAR (191);_

But now I am still stuck... I launched the update again and now the error is:
      
      _Informations de réparation : Change row format for oc_authtoken ...
      Informations de réparation : Change collation for oc_authtoken ...
      Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_authtoken CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
      
I understand the field are too narrow butdon't know what to do exactly.
When I look at the oc_authtoken  table I don't know which field has to be promoted to VARCHAR(191)

![image](https://user-images.githubusercontent.com/15813085/114914830-18ad8100-9e23-11eb-8368-3d749d0bf42f.png)

I supposed I should use something like :
    ALTER TABLE oc_authtoken  MODIFY COLUMN _WHICH_FIELD_IS_TO_MODIFIED_ VARCHAR (191);

But don't know which of the table field I should changed !
Anyone can help ?
Thanks !

Manuel

**Comment by acsfer** [comment]
Please check https://github.com/nextcloud/server/issues/23369#issuecomment-707313974
If this doen't help, please use https://help.nexcloud.com thanks 👍

**Comment by MootoolsSoftware** [comment]
This works like a charm.
Thanks for your help !
