### ISSUE TITLE
Internal Server Error after Upgrade from 20.0.6 to 21.0.1 - no login possible anymore

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/server#26573]
### **NC Upgrade: from 20.0.6 to 21.0.1** 

**LOGIN to the CLOUD is not possible anymore**

(it remains to mention that the release 20.0.9 was skipped, although announced via GUI )!?)

2021-04-14T18:02:09+0000 ZAibphg2Gb [info] storage location: /media/updater-ocxxxxxx/downloads/nextcloud/
2021-04-14T18:02:09+0000 ZAibphg2Gb [info] call opcache_reset()
2021-04-14T18:02:09+0000 ZAibphg2Gb [info] end of finalize()
2021-04-14T18:02:09+0000 ZAibphg2Gb [info] endStep("12")
2021-04-14T18:02:09+0000 ZAibphg2Gb [info] ### **update of code successful.**
2021-04-14T18:05:58+0000 ZAibphg2Gb [info] maintenance mode is disabled - return code: 0
2021-04-14T23:29:50+0000 hFMVCO5GKg [info] updater cli is executed
2021-04-14T23:29:50+0000 hFMVCO5GKg [info] currentStep()
2021-04-14T23:29:50+0000 hFMVCO5GKg [info] current version: 21.0.1 build time: 2021-04-08T13:32:52+00:00 bd555dbe8568b2509bd7d82fabbe38d76c86afbe
2021-04-14T23:29:50+0000 hFMVCO5GKg [info] getUpdateServerResponse()
2021-04-14T23:29:50+0000 hFMVCO5GKg [info] updaterServer: https://updates.nextcloud.com/updater_server/
2021-04-14T23:29:50+0000 hFMVCO5GKg [info] releaseChannel: stable
2021-04-14T23:29:50+0000 hFMVCO5GKg [info] internal version: 21.0.1.1
2021-04-14T23:29:50+0000 hFMVCO5GKg [info] updateURL: https://updates.nextcloud.com/updater_server/?version=21x0x1x1xxxstablexx2021-04-08T13%3A32%3A52%2B00%3A00+bd555dbe8568b2509bd7d82fabbe38d76c86afbex7x4x16
2021-04-14T23:29:50+0000 hFMVCO5GKg [info] checkForUpdate() Array

![ScreenShot1392](https://user-images.githubusercontent.com/32612067/114856570-8b007000-9de7-11eb-9730-8ada9ca717a5.jpg)

I explicitly checked if propably the appdata_xxx instance-directory has got wrong permissions - but everything was ok
(all on apache:apache permissions).

The only workaround here was to setup a **new config.php** with a new "**instanceid**" .. the consequence of that, was
, that **a new "appdata_xxxxx" Instance-directory data directory was created.** 

After that i tried to restore some users data (avatar & more) to the new instance-Directory - but - the **Server crashed again.**

I had to rebuild a new Instanceid again - now the user Login is possible.

### **One additional issue is here:**

* how the users get their appdata-contents back without to bring the NC-Instance again in danger
* in the appdata-<instance> Directory there is also the E2EE stuff (meta data).
   
### Steps to reproduce

repeat the above steps

### Expected behaviour

* There is no "internal Server ERROR"
* User can login to the CLOUD
* special care should be taken, when NC does create a new InstanceID - prior to that important content should be copied the new structure to guarantee no user-data config loss (like E2EE) or there should be some other steps required to improve stability & security.

I think, this i an important issuse/case ! If you would need additional information (log report & more) - let me know.

### --------------------------------
Windows 10/Mac

### --------------------------------

Version: Intel(R) Xeon(R) E-2136 CPU @ 3.30GHz Max Speed : 4300 MHz Current Speed: 3300 MHz
Memory: 16GB
----------------------------------------------

Operating System: CentOS Linux release 8.3.2011

Upstream OS : Derived from Red Hat Enterprise Linux 8.3

Webserver: Apache/2.4.37 (centos)

Database: mysql 10.3.27-MariaDB,

PHP version: PHP Version => 7.4.16

[PHP Modules] apcu bcmath bz2 calendar Core ctype curl date dom exif fileinfo filter ftp gd gettext gmp hash iconv igbinary imagick intl json ldap libsmbclient libxml mbstring memcached msgpack mysqli mysqlnd openssl pcntl pcre PDO pdo_mysql pdo_sqlite Phar posix readline redis Reflection session shmop SimpleXML smbclient sockets sodium SPL sqlite3 standard sysvmsg sysvsem sysvshm tokenizer xml xmlreader xmlwriter xsl Zend OPcache zip zlib [Zend Modules] Zend OPcache

Nextcloud: - version: 21.0.1.1
### Updated from an older Nextcloud/ownCloud or fresh install:

Upgrade from NC 20.0.6

### Where did you install Nextcloud from:

Origin NC Source

### Signing status:

Login as admin user into your Nextcloud and access http://example.com/index.php/settings/integrity/failed
paste the results here.

No errors have been found.

{
    "system": {
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "21.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "auth.bruteforce.protection.enabled": true,
        "check_for_working_htaccess": true,
        "updater.release.channel": "stable",
        "logfile": "\/media\/log\/nextcloud.log",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "session_lifetime": 1200,
        "session_keepalive": false,
        "default_phone_region": "CH",
        "knowledgebaseenabled": false,
        "log_rotate_size": 3145728,
        "mail_sendmailmode": "smtp",
        "app_install_overwrite": [
            "passman",

Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - analytics: 3.4.1
  - announcementcenter: 5.0.0
  - apporder: 0.12.0
  - audioplayer: 3.1.0
  - audioplayer_editor: 0.3.0
  - audioplayer_sonos: 1.2.0
  - bookmarks: 4.1.0
  - bruteforcesettings: 2.1.0
  - calendar: 2.2.0
  - circles: 0.21.0
  - cloud_federation_api: 1.4.0
  - cms_pico: 1.0.15
  - comments: 1.11.0
  - contacts: 3.5.1
  - contactsinteraction: 1.2.0
  - cookbook: 0.8.4
  - cospend: 1.3.0
  - dashboard: 7.1.0
  - data_request: 1.8.0
  - dav: 1.17.1
  - deck: 1.4.0
  - dicomviewer: 1.2.2
  - documentserver_community: 0.1.9
  - drawio: 1.0.0
  - event_update_notification: 1.2.0
  - extract: 1.3.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_automatedtagging: 1.11.0
  - files_downloadactivity: 1.10.0
  - files_external: 1.12.0
  - files_external_onedrive: 1.1.0
  - files_markdown: 2.3.3
  - files_mindmap: 0.0.24
  - files_pdfviewer: 2.1.0
  - files_photospheres: 1.21.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - flow_notifications: 1.1.0
  - forms: 2.2.4
  - gpxmotion: 0.1.0
  - gpxpod: 4.2.8
  - groupfolders: 9.0.0
  - impersonate: 1.8.0
  - integration_discourse: 1.0.0
  - integration_dropbox: 1.0.0
  - integration_github: 1.0.0
  - integration_gitlab: 1.0.0
  - integration_google: 1.0.0
  - integration_jira: 1.0.0
  - integration_mastodon: 1.0.0
  - integration_moodle: 1.0.0
  - integration_onedrive: 1.0.0
  - integration_openproject: 1.0.0
  - integration_reddit: 0.0.11
  - integration_suitecrm: 0.0.4
  - integration_twitter: 1.0.0
  - integration_whiteboard: 0.0.14
  - integration_zammad: 1.0.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - maps: 0.1.8
  - nextcloud_announcements: 1.10.0
  - notes: 4.0.4
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - onlyoffice: 6.3.0
  - passman: 2.3.7
  - password_policy: 1.11.0
  - photos: 1.3.0
  - polls: 1.8.1
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - quicknotes: 0.7.1
  - quota_warning: 1.10.0
  - rainloop: 7.1.2
  - ransomware_protection: 1.10.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - social: 0.4.2
  - spreed: 11.1.2
  - support: 1.4.0
  - suspicious_login: 4.0.0
  - systemtags: 1.11.0
  - tasks: 0.13.6
  - text: 3.2.0
  - theming: 1.12.0
  - timemanager: 0.1.8
  - twofactor_backupcodes: 1.10.0
  - twofactor_totp: 6.0.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - video_converter: 1.0.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - welcome: 0.0.5
  - workflow_ocr: 1.21.0
  - workflow_pdf_converter: 1.6.0
  - workflow_script: 1.6.0
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - breezedark
  - drop_account
  - encryption
  - end_to_end_encryption
  - external
  - files_3d
  - files_accesscontrol
  - files_antivirus
  - files_fulltextsearch
  - flowupload
  - fulltextsearch
  - fulltextsearch_elasticsearch
  - gpxedit
  - health
  - issuetemplate
  - joplin
  - ojsxc
  - passwords
  - registration
  - side_menu
  - socialsharing_diaspora
  - socialsharing_email
  - socialsharing_facebook
  - socialsharing_googleplus
  - socialsharing_twitter
  - survey_client
  - talk_matterbridge
  - terms_of_service
  - user_ldap
  - weather

**Comment by kesselb** [comment]
nextcloud.log is missing. The updater.log looks fine. Files are replaced successfully. 

> "memcache.local": "\OC\Memcache\APCu",

APCu is causing issues on upgrade via CLI: https://github.com/nextcloud/server/issues/25742

> So i suppose - some of my users lost access to their encrypted folders ?!

Copy nextcloud.log and updater.log. Restore the working configuration from the backup.

**Comment by Githopp192** [comment]
Update.log appended - the other logs will follow 

[updater.log](https://github.com/nextcloud/server/files/6320250/updater.log)

about the working configuration .. i think you mean config.php .. that's i did - restore the old config.php - but replaced the config with a new instance_id (that one, which was replaced by NC).

Nextcloud will crash with the old appdata_ocxxxxx folder and the appropriate instanceid in config.php

Of course .. i could again restore this folder (appdata_ocxxx) and replace the old "instanceid" in the config.php

But the NC would crash again i think. There must be some inconsistencies into the appdata_ocxxx folder !?

Only with the config.php with a new instanceid NC does run again.

**Comment by Githopp192** [comment]
NC 21.0.1 crashed again with the new appdata_ocxxx instance.
Internal Server ERROR
Many users are affected. 

I think about to go back to versino 20.0.6

**Comment by Githopp192** [comment]
Now - the Environment is running stable - finally i did run --> occ files:scan-app-data

Thanks for your support & and i wish you a great day
