### ISSUE TITLE
Upgrade to 19.0.10 from web tools fails.

### ISSUE THREAD

**Issue by MootoolsSoftware** [nextcloud/server#26570]
Hello,

I was upgrading nextcloud using web upgrader from 19.0.2 to 19.0.10 and it fails.
Here is the error reported.

Étape de réparation : Repair MySQL collation
Informations de réparation : Change row format for oc_addressbooks ...
Informations de réparation : Change collation for oc_addressbooks ...
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

I am now stuck with this bug and don't know what to do.

How can I go further and finish the upgrade.

Thanks
Manuel

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1:  Please check https://github.com/nextcloud/server/issues/15058 for more details.

Usually there are two ways to fix this:

A) Configure your database server to support utf8mb4 (https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/mysql_4byte_support.html).

B) If the database server does not support utf8mb4 disable it by setting 'mysql.utf8mb4' => false in your config.php (emojis in filename, calendar events, etc. are not possible than and you have to accept the warning).

**Comment by MootoolsSoftware** [comment]
I have no access to the conf file.

So I applied :
ALTER TABLE oc_addressbooks MODIFY COLUMN principaluri VARCHAR (191);
ALTER TABLE oc_addressbooks MODIFY COLUMN displayname VARCHAR (191);
ALTER TABLE oc_addressbooks MODIFY COLUMN uri VARCHAR (191);
ALTER TABLE oc_addressbooks MODIFY COLUMN description VARCHAR (191);

But now the error is

Informations de réparation : Change row format for oc_authtoken ...
Informations de réparation : Change collation for oc_authtoken ...

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_authtoken` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
