### ISSUE TITLE
Prevent unsharing files and folders

### ISSUE THREAD

**Issue by diemelone** [nextcloud/server#26589]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Users unshare files and folders accidentally and I have to reshare those files/folders with them

**Describe the solution you'd like**
Adding the option while sharing to add a checkbox ([ ] can unshare) to prevent unsharing from this particular file/folder

**Describe alternatives you've considered**
groupfolder and external storage work fine with folders but not with files

**Additional context**
esp. readme and similar files are crucial for clouds to stay organized in my opinion, thats why the should get some extra protection

I have seen that statement ([Request  ##11612](https://github.com/nextcloud/server/issues/11612#issuecomment-427021583)) before, but I am sure that to every rule there has to be exceptions.

**Comment by acsfer** [comment]
Well, i don't believe that https://github.com/nextcloud/server/issues/11612#issuecomment-427021583 will be overruled.

**Comment by diemelone** [comment]
no need to overrule that, just add exceptions. Groupfolders are a exception (or workaround) as well, we just need that for files too.

**Comment by szaimen** [comment]
Hm... Maybe you can use this app instead for important notes and such?
https://apps.nextcloud.com/apps/login_notes

**Comment by diemelone** [comment]
i have already looked into it but no, that wouldn't be a sufficient alternative, i especially want readme.md files to be "fixed in place" and not modifiable or else

**Comment by szaimen** [comment]
cc @nextcloud/server-triage is this feasible?
