### ISSUE TITLE
Hamburger menu is often hidden

### ISSUE THREAD

**Issue by diemelone** [nextcloud/server#26596]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Open different pages (appstore, mail, etc...) in nc
2.
3.

### Expected behaviour
hamburgermenu should have its own line, main content needs padding-top: 44px;

### Actual behaviour
hamburgermenu disappears behind (or maybe on top?) of the first entry a list

### Server configuration

**Operating system:**
linux

**Web server:**
?

**Database:**
mysql

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
21
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh
**Where did you install Nextcloud from:**
webhoster installation package
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
only standard apps + mail, tasks and groupfolders
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
no changes have been made, fresh installation
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
different mozilla browsers and edge, all with most recent updates

**Operating system:**
win 10

### Logs

should be a css problem

add
.app-content-vue{
padding-top:44px;
}
problem solved... but after updating changes are deleted...

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

![grafik](https://user-images.githubusercontent.com/46229652/115051348-055eec00-9edd-11eb-96c2-a6ff725ffed7.png)

**Comment by diemelone** [comment]
further information and screenshots are in this issue [mail #4956](https://github.com/nextcloud/mail/issues/4956)

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/16934
