### ISSUE TITLE
Changing from `pt_PT` to `pt_BR` does not change the language at all

### ISSUE THREAD

**Issue by Beltran1337** [nextcloud/server#26599]
Hello guys, hope you are doing well...

So, I translate a lot of phrases on transifex to **pt_BR** (which is the language that we use in our production _NC 21.0.1_).

I realized that there was some words that in **pt_PT** were right but in the Brazilian dictionary, they were wrong.

So I identified that even forcing the **pt_BR** inside the config.php it does not change the words at all.

The pt_PT is always in use and not the pt_BR.

What can I do?

Thank you!

**Comment by rakekniven** [comment]
Confirmed behaviour.

If switching language in user profile at apps.nextcloud.com it works. 

NC version: 21.0.1
webserver: apache
db: postgresql

**Comment by szaimen** [comment]
I supose this is still valid on NC21.0.3? What happens if you set both language and locale to BR ?

**Comment by marcelomera** [comment]
Problema continua na versão 27.0
