### ISSUE TITLE
Sharing link expiration based on groups

### ISSUE THREAD

**Issue by salagula** [nextcloud/server#26595]
Perfect would be an option to set expiration of links based on group membership. The reason is simple: sometimes I have users audiences (internal users) where I’d like to do long-term sharing and for the rest (e.g. customers) I’d like to have an automatic expiration date of 7 days.

**Comment by szaimen** [comment]
I wonder why this doesn't work for you?
https://help.nextcloud.com/t/sharing-expiration-based-on-user-propery/113933/3

**Comment by salagula** [comment]
as of now - correct me if I'm wrong - you can only enforce sharing link expiration based on anonymous links or in general. More flexibility would be appreciated. One thing I could imagine would be to have a group that is excluded from link sharing expiration (similar to the already existing field in the settings)
![image](https://user-images.githubusercontent.com/65948353/115138804-9beef280-a02e-11eb-9129-fb7f06b9d723.png)

The overall goal would be to automatically enforce sharing expiration after 7 days for all external users and for internal user group sharing there is no expiration enforced.
