### ISSUE TITLE
Nextcloud doesn't remember login

### ISSUE THREAD

**Issue by DrCarsonBeckett** [nextcloud/server#26610]
### How to use GitHub
* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Update to 21.0.1
2. Login (2FA is enabled)
3. On the next day (PC shutdown over night) the browser needs to re-login into the website.

### Expected behaviour
You start your browser and visit your Nextcloud's website and é voila you are logged in because it remebers your session.

### Actual behaviour
Sadly I need to login every damn time I open the browser ones I restart the PC. And no, I don't clear the cache or delete any cookies on shutdown.

### Additional note
It worked like this before and only malfunctioned like this in 1-3 versions of the Nextcloud server release.
I had that issue with the last release of the Nextcloud 20 version if I recall correctly.
Or one version before that. When I updated to Nextcloud 21 I hoped it will be fixed again and it was. Worked fine as hoped and expected to be honest. Sadly with Nextcloud 21.0.1 it doesn't anymore.
I did a quick check to find any similar issues/tickets, but couldn't find any. That's why I opened one.

### Server configuration
**Operating system:**
Debian 10

**Web server:**
Apache2

**Database:**
MySQL

**PHP version:**
7.4.16 (fpm)

**Nextcloud version:** (see Nextcloud admin page)
21.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 21.0.0

**Where did you install Nextcloud from:**
Uploaded via ftp and installed through browser. Got the package from the official Nextcloud page.
Updated to 21.0.1 through upload via ftp and then run the update via occ.

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - bruteforcesettings: 2.1.0
  - checksum: 1.1.2
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - data_request: 1.8.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_downloadactivity: 1.10.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trackdownloads: 1.10.0
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - guests: 2.0.0
  - impersonate: 1.8.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - metadata: 0.13.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - quota_warning: 1.10.0
  - ransomware_protection: 1.10.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - support: 1.4.0
  - survey_client: 1.9.0
  - suspicious_login: 4.0.0
  - systemtags: 1.11.0
  - terms_of_service: 1.7.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_totp: 6.0.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - user_usage_report: 1.5.0
  - viewer: 1.5.0
  - weather: 1.7.5
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - encryption
  - files_external
  - groupfolders
  - photos
  - ransomware_detection
  - twofactor_admin
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.domain.tld"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.1.1",
        "overwrite.cli.url": "https:\/\/cloud.domain.tld\/nc",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "simpleSignUpLink.shown": false,
        "integrity.check.disabled": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "memcache.distributed": "\\OC\\Memcache\\APCu",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "default_phone_region": "DE",
        "defaultapp": "files",
        "session_keepalive": true,
        "auto_logout": false,
        "remember_login_cookie_lifetime": 2678400,
        "session_lifetime": 86400,
        "check_for_working_wellknown_setup": "true"
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "activity": {
            "enable_email": "no",
            "enabled": "yes",
            "installed_version": "2.14.3",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "992"
        },
        "bookmarks": {
            "enabled": "no",
            "installed_version": "4.0.5",
            "types": ""
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "2.1.0",
            "types": ""
        },
        "checksum": {
            "enabled": "yes",
            "installed_version": "1.1.2",
            "types": "filesystem"
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "logging"
        },
        "contactsinteraction": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "dav"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "enterpriseLogoChecked": "yes",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1585509747.4013",
            "lastcron": "1618742702",
            "lastupdateResult": "[]",
            "lastupdatedat": "1618734766",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "shareapi_default_expire_date": "yes",
            "shareapi_default_internal_expire_date": "yes",
            "shareapi_enforce_expire_date": "yes",
            "shareapi_internal_enforce_expire_date": "yes",
            "theming.variables": "02cbab506c89be73ee38ad5306a46fe1",
            "updater.secret.created": "1617969516",
            "vendor": "nextcloud"
        },
        "dashboard": {
            "enabled": "yes",
            "installed_version": "7.1.0",
            "types": ""
        },
        "data_request": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "generateBirthdayCalendar": "no",
            "installed_version": "1.17.1",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "sendEventReminders": "no",
            "sendInvitations": "no",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.16.0",
            "types": "filesystem"
        },
        "files_downloadactivity": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "2.1.0",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.13.1",
            "types": "filesystem"
        },
        "files_trackdownloads": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.10.0",
            "types": "logging"
        },
        "groupfolders": {
            "enabled": "no",
            "installed_version": "9.0.0",
            "types": "filesystem,dav"
        },
        "guests": {
            "allow_external_storage": "false",
            "enabled": "yes",
            "hide_users": "false",
            "installed_version": "2.0.0",
            "types": "authentication",
            "usewhitelist": "true",
            "whitelist": "files_trashbin,files_versions,files_sharing,files_texteditor,text,activity,firstrunwizard,photos,notifications"
        },
        "impersonate": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.6.0",
            "live": "1",
            "relativedates": "",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "authentication"
        },
        "metadata": {
            "enabled": "yes",
            "installed_version": "0.13.0",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.9.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "enforceHaveIBeenPwned": "1",
            "enforceNumericCharacters": "1",
            "enforceSpecialCharacters": "1",
            "enforceUpperLowerCase": "1",
            "historySize": "2",
            "installed_version": "1.11.0",
            "maximumLoginAttempts": "3",
            "types": "authentication"
        },
        "photos": {
            "enabled": "no",
            "installed_version": "1.0.0",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "readableLocation": "de",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "prevent_group_restriction"
        },
        "quota_warning": {
            "alert_email": "yes",
            "alert_percentage": "90",
            "enabled": "yes",
            "info_email": "yes",
            "info_percentage": "50",
            "installed_version": "1.10.0",
            "types": "filesystem",
            "warning_email": "yes",
            "warning_percentage": "75"
        },
        "ransomware_detection": {
            "debug": "0",
            "enabled": "no",
            "installed_version": "0.10.0",
            "types": ""
        },
        "ransomware_protection": {
            "enabled": "yes",
            "extension_exclusions": "[\"***REMOVED SENSITIVE VALUE***"]",
            "installed_version": "1.10.0",
            "notes_include_biased": "yes",
            "types": "logging"
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "filesystem"
        },
        "support": {
            "SwitchUpdaterServerHasRun": "yes",
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "session"
        },
        "survey_client": {
            "apps": "no",
            "database": "no",
            "enabled": "yes",
            "encryption": "no",
            "files_sharing": "no",
            "installed_version": "1.9.0",
            "php": "no",
            "server": "no",
            "stats": "no",
            "types": ""
        },
        "suspicious_login": {
            "enabled": "yes",
            "installed_version": "4.0.0",
            "types": "authentication"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "logging"
        },
        "terms_of_service": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "term_uuid": "6078b19de6299",
            "types": "filesystem"
        },
        "text": {
            "enabled": "yes",
            "installed_version": "3.2.0",
            "types": "dav"
        },
        "theming": {
            "backgroundMime": "image\/jpeg",
            "cachebuster": "22",
            "color": "#214076",
            "enabled": "yes",
            "faviconMime": "image\/png",
            "imprintUrl": "***REMOVED SENSITIVE VALUE***",
            "installed_version": "1.12.0",
            "logoheaderMime": "image\/png",
            "name": "Cloud.DrCB.space",
            "privacyUrl": "***REMOVED SENSITIVE VALUE***",
            "slogan": "***REMOVED SENSITIVE VALUE***",
            "types": "logging",
            "url": "***REMOVED SENSITIVE VALUE***"
        },
        "twofactor_admin": {
            "enabled": "no",
            "installed_version": "3.0.0",
            "types": ""
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": ""
        },
        "twofactor_totp": {
            "enabled": "yes",
            "installed_version": "6.0.0",
            "types": ""
        },
        "updatenotification": {
            "bruteforcesettings": "2.0.0",
            "checksum": "1.1.2",
            "core": "20.0.6.1",
            "enabled": "yes",
            "groupfolders": "8.2.0",
            "guests": "2.0.0",
            "impersonate": "1.5.2",
            "installed_version": "1.11.0",
            "metadata": "0.12.0",
            "ransomware_detection": "0.7.1",
            "ransomware_protection": "1.10.0",
            "suspicious_login": "3.2.1",
            "terms_of_service": "1.5.1",
            "twofactor_admin": "3.0.0",
            "twofactor_totp": "5.0.0",
            "types": "",
            "update_check_errors": "0",
            "user_usage_report": "1.2.2"
        },
        "user_status": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "user_usage_report": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "weather": {
            "enabled": "yes",
            "installed_version": "1.7.5",
            "openweathermap_api_key": "***REMOVED SENSITIVE VALUE***",
            "types": ""
        },
        "weather_status": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.3.0",
            "types": "filesystem"
        }
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** yes/no
Not yet.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.

### Client configuration
**Browser:**
Firefox 87 64bit

**Operating system:**
Windows 10 20H2

#### Web server error log
<details>
<summary>Web server error log</summary>
Log file content can be provided if necessary.
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Log file content can be provided if necessary.
</details>

#### Browser log
<details>
<summary>Browser log</summary>
Log file content can be provided if necessary.
</details>

**Comment by acsfer** [comment]
Check https://github.com/nextcloud/server/blob/master/config/config.sample.php#L242-L257

**Comment by szaimen** [comment]
Maybe related to #26502?

**Comment by DrCarsonBeckett** [comment]
> 
> 
> Check https://github.com/nextcloud/server/blob/master/config/config.sample.php#L242-L257
I already did checked that and tested it, it doesn't help ... meaning it doesn't change the behavior. Also it worked before upgrading to 21.0.1 (as mentioned).

> 
> 
> Maybe related to #26502?
I don't think so since its about a different thing. Its still about logins, but about a different type for a different useage.

**Comment by DrCarsonBeckett** [comment]
This report seems to have some things in common this this one: https://github.com/nextcloud/server/issues/26806 .

**Comment by osm-frasch** [comment]
Sorry to ask, but has anything happened on this or is more info needed? Since Nextcloud has so explicitly advertised the Fido2 feature publicly and companies like ours now have over 200 Fido2 keys in use, it would be great if there was a solution to this problem.

**Comment by DrCarsonBeckett** [comment]
Also still happens with 21.0.2 .

**Comment by DrCarsonBeckett** [comment]
And still happens with 21.0.3 .

**Comment by DrCarsonBeckett** [comment]
Surprise, surpriseor ... or not. 😞 
Still happens with 22.0.0 .

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/26806
