### ISSUE TITLE
[Error cron] TypeError Argument 1 passed to OC\DB\SchemaWrapper::__construct() must be an instance of OC\DB\Connection

### ISSUE THREAD

**Issue by thepra** [nextcloud/server#26611]
![immagine](https://user-images.githubusercontent.com/7032509/115143460-b6819580-a047-11eb-9b7a-850fc145b0a0.png)
I'm having this cron error that does constantly repeat, is there something I can do or it's a code bug?

**Comment by kesselb** [comment]
cc @nextcloud/talk

**Comment by nickvergessen** [comment]
Please update to the latest version

**Comment by thepra** [comment]
I'm already at the 21.0.1, no further updates I see for the Stable channel

**Comment by nickvergessen** [comment]
But your Talk version is not the newest

**Comment by thepra** [comment]
aaah, got it, understood, it must be then one of my relatives without an updated app. Thanks.
