### ISSUE TITLE
NC11.0.0: Printing backup codes fails when Adblock Plus is activated, ABP prevents the new window for printing the backup codes to be opened.

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/server#2662]
One page is printed, but this is only covering the upper left part of the whole browser window (section "Persönlich" and start of the Profile), but not the codes.

The maintainer expressly asked me to file it here, see his comment on https://github.com/nextcloud/twofactor_totp/issues/103#issuecomment-266965735 .

**Comment by LukasReschke** [comment]
cc @ChristophWurst

**Comment by ChristophWurst** [comment]
@Wikinaut could you please fill out the issue template? E.g. which browser are you using?

**Comment by Wikinaut** [comment]
* Nextcloud server 11.0.0 on debian 8 fully patched
* Browser: Firefox ESR 45.5.1 (up-to date version) on debian 8

**Comment by nickvergessen** [comment]
Works quite fine here, please fill out the complete issue template as requested already.

**Comment by Wikinaut** [comment]
@nickvergessen pls. post a (possibly) redacted output of how the prints look at your computer.

**Comment by nickvergessen** [comment]
Please see https://github.com/nextcloud/server/issues/new for the issue template and use it.

My output is something like
> ![personal_-_nextcloud_-_2016-12-15_10 05 59](https://cloud.githubusercontent.com/assets/213943/21217755/1c920426-c2ae-11e6-8506-db62cea7e430.png)

**Comment by Wikinaut** [comment]
@nickvergessen Hmm, and I get the upper part of the whole web page. But pls. keep in mind that the installation of the latest app still fails, see https://github.com/nextcloud/twofactor_totp/issues/95 and my duplicate https://github.com/nextcloud/twofactor_totp/issues/102#issuecomment-266965848 . I hope that @ChristophWurst and the core developers will soon find a solution, or the reason.

I don't want to make you crazy with this report, but I am quite nervous because of the TOTP update failure. Should not happen... (Nextcloud regression to ownCloud-update behaviour?)

**Comment by nickvergessen** [comment]
The backup codes are unrelated to TOTP, they are in a separate app.

I will close this issue now, feel free to reopen once the issue template (especially the browser network log) was **fully** provided.

**Comment by Wikinaut** [comment]
@nickvergessen Your output is the printed version ?

**Comment by Wikinaut** [comment]
Template: too much data. No time.

**Comment by Wikinaut** [comment]
@nickvergessen Your output is the printed version ? I wanted an image of the print-out. The screen output works for me and looks like yours. The issue is about the _printed_ version, perhaps you overlooked.

**Comment by Wikinaut** [comment]
@ChristophWurst @nickvergessen Problem found.

Reason for this: on my browser, I have Adblock Plus activated. This prevents the browser from opening the new window for the backup codes.

**Comment by Wikinaut** [comment]
Title changed

**Comment by Wikinaut** [comment]
@LukasReschke when do you add Label "0. Needs triage" (is there a description, when to apply what label?)
