### ISSUE TITLE
`occ files:scan` Home storage for user `$USER` not writable

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#26634]
When running `occ files:scan --all`, if the user has been created but **never logged in**, `occ` outputs an error like:

```
Home storage for user `$USER` not writable
Make sure you're running the scan command only as the user the web server runs as
```

Some logic should be included to detect if user has logged in once so it's home is created and populated, otherwise, bypass the scan for this user instead of displaying this error.

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/server/pull/27538
