### ISSUE TITLE
Seach function 

### ISSUE THREAD

**Issue by NBorg93** [nextcloud/server#26635]
Hello,
I use nextcloud in a medical facility for patient documentation on my mobile device. The documents we use must be able to be written on and painted on. For this reason, we primarily use PDF files for patient documentation. 
The problem that arises now is that the search function in the mobile app does not work when uploading the PDF from Acrobat Reader. The same problem occurs when documents have to be copied or moved within the app.

Is there a possibility that the PDF can be edited via the Nextcloud app without having to open the Adobe Acrobat app separately?

Thanks for your help!

Nils

**Comment by kesselb** [comment]
For questions: https://help.nextcloud.com/
