### ISSUE TITLE
Share is overruling the smb mount

### ISSUE THREAD

**Issue by Webserve** [nextcloud/server#2664]
### Steps to reproduce
1. Create an smb external storage. Every user his own folder (/$user)
2. Make it possible to share the storage
3. Share the smb share to a group. The share is overruling the smb mount. 

### Expected behaviour
The share name should be like "Folder (Shared by user X)" now it is "Folder" and my mount name is also "Folder"

### Actual behaviour
The share is overruling the smb mount. My mount is called "Bestanden" and the share has the same name. 

### Server configuration
**Operating system**:
Ubuntu
**Web server:**
apache
**Database:**
Maria
**PHP version:**
7
**Nextcloud version:** (see Nextcloud admin page)
11.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh
**Where did you install Nextcloud from:**
website...
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 0.5.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - templateeditor
  - user_external
  - user_saml

</details>



**Are you using external storage, if yes which one:** local/smb/sftp/...

SMB

**Are you using encryption:** yes/no

NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

FF

**Operating system:**

windows 10

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

**Comment by nickvergessen** [comment]
@rullzer `(2)` logic problem again

**Comment by rullzer** [comment]
@icewind1991 I need help here. Basically when we setup the mountpoints we do check for what is there. But I have no way to check for mountstuff that isn't there yet. (Which is the case here).

If we find overlapping mountpoints. We should just try to move the last moveable one I guess.

**Comment by rullzer** [comment]
Fixed with https://github.com/nextcloud/server/pull/3497
