### ISSUE TITLE
Invalidate app store cache if server version changes

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#2666]
I noticed this during my update to Nextcloud 11. Some apps where disabled during upgrade,  in the apps manager I just saw that the version is not compatible with my Nextcloud version without a possibility to update the app and to enable it again. Only after the app store cache was refreshed I could update and enable the app again. This is really confusing if you don't know what happens in the background.

I would suggest to invalidate the cache if the Nextcloud version changes so that the app store gets updated right away and the admin can re-enable the apps directly after the update.

cc @BernhardPosselt @LukasReschke

**Comment by nickvergessen** [comment]
👍
