### ISSUE TITLE
Drag and drop PDF

### ISSUE THREAD

**Issue by sdenecheau-opendsi** [nextcloud/server#26664]
Hello, I have a problem on nextcloud thanks for your help.

### Steps to reproduce
1. Put a pdf file, in nextcloud.
2. Tried to Drag and Drop the pdf file into a folder.

I don't have the problem with other type of file (.md, .ods, .xlsx) and I can move using the button "Actions / Move or copy" without error.
 

### Expected behaviour
Moving the pdf file without error.

### Actual behaviour
Error display.

![erreur_web](https://user-images.githubusercontent.com/46525265/115430601-cb575800-a204-11eb-88ff-e163f486a45d.png)
![erreur_console](https://user-images.githubusercontent.com/46525265/115430815-fd68ba00-a204-11eb-850f-a12d018d47f6.png)

apache2/acces.log:
MOVE /remote.php/dav/files/XXXXXX-XXXX-XXXX-XXXXX-XXXXXXXX/XXXXX.pdf HTTP/1.0" 423 239

### Server configuration

**Operating system:**
Debian 10.9

**Web server:**
Apache/2.4.38

**Database:**
 10.3.27-MariaDB

**PHP version:**
PHP 7.4.16

**Nextcloud version:** (see Nextcloud admin page)
20.0.8

**Updated from an older Nextcloud/ownCloud or fresh install:**
15.0.6

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-20.0.8.zip

**List of activated apps:**
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dav: 1.16.2
  - deck: 1.2.6
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - impersonate: 1.7.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - richdocuments: 3.7.17
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.7
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_ldap: 1.10.2
  - user_saml: 3.3.4
  - viewer: 1.4.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - dashboard
  - encryption
  - firstrunwizard
  - photos
  - polls
  - support
  - user_status
  - weather_status

**Comment by kesselb** [comment]
Hi,

are you able to reproduce with https://try.nextcloud.com/?

**Comment by hul51u** [comment]
I just reproduced this behaviour with https://try.nextcloud.com/. just as described by @sdenecheau-opendsi.

**Comment by kesselb** [comment]
https://user-images.githubusercontent.com/3902676/116358498-01e13400-a7fe-11eb-9ec5-a4c8ca29b347.mp4
