### ISSUE TITLE
Random “unknown error has occurred” and “connection to server lost”

### ISSUE THREAD

**Issue by manu-p** [nextcloud/server#26682]
Nextcloud version: 20.0.6
Operating system and version: Debian 10
Apache or nginx version: Apache 2.4
PHP version: 7.4.16
DB: MySQL 5.7

On a shared hosting (IONOS Web Pro), users are randomly experiencing [these 2 following errors](https://help.nextcloud.com/uploads/default/original/3X/d/4/d4cfd781c4c5de8f397098745a1f72ad5df37e89.png):

- unknown error has occurred
- connection to server lost

This happens on any app, not only Files, for instance Calendar.

No error message in Nextcloud.log.

I could reproduce the error by uploading a 100MB mp4 file using FF 87.0.
I could trace the event and uploaded a [HAR file here](https://www.grosfichiers.com/xtcjkTVKKSv).
I did not find anything in this log.
In this log, the “event” happened at 2021-04-02T10:43:08.

The same upload has been working fine three times at different moments using Brave browser, making me think this might be related to the browser, in some way.

Nothing in apache access.log. No access to error.log

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
