### ISSUE TITLE
`files:transfer-ownership` stops at 280 files

### ISSUE THREAD

**Issue by mseiwald** [nextcloud/server#26687]
Hi,

I'm running the following command for a <source-user> with multiple thousand files:

```sudo -u www-data php occ files:transfer-ownership <source-user> <destination-user>```

After a short time I get the following error:

```Validating quota
Analysing files of <source-user> ...
 15002 [============================]
Collecting all share information for files and folders of <source-user> ...
   25 [============================]
Transferring files to <destination-user>/files/transferred from <Source User> on 2021-04-21 16-13-24 ...
Could not transfer files.
```

In the resulting folder I can see that it transferred 280 files and then stopped. I repeated it multiple times with the same result.

Please assist.

Nextcloud version: 21.0.0

**Comment by mseiwald** [comment]
Just saw in the log files that it cannot load a certain file from S3 which seems to lead to the error.

**Comment by kesselb** [comment]
Issue template and especially logs are missing.

**Comment by gary-kim** [comment]
Seems like this can be closed. Feel free to reopen if there is still abug to resolve.
