### ISSUE TITLE
SQL Server Support

### ISSUE THREAD

**Issue by mightymop** [nextcloud/server#26680]
**Is your feature request related to a problem? Please describe.**
I'd like to see SQL Server support for nextcloud. Its frustating to run an extra mariadb cluster only for nextcloud although we have a sql server cluster in our firm :/

**Describe the solution you'd like**
I think the supported databases are connected via pdo? So is it difficult to integrate sql server /mssql too?

**Comment by kesselb** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future.

**Comment by mightymop** [comment]
Currently this sounds bad for me and many other firms/departments :/ 
Without reading the whole nextcloud source, how is it realized with the allready supported databases? Is there a database controller which we could extend with mssql methods or are there many if/else/swich in every class which has to interact with the database?

**Comment by kesselb** [comment]
> Without reading the whole nextcloud source, how is it realized with the allready supported databases? Is there a database controller which we could extend with mssql methods or are there many if/else/swich in every class which interacts with the database?

https://www.doctrine-project.org/projects/dbal/latest.html
https://github.com/nextcloud/server/tree/master/lib/private/DB

Adding another database is more then overwriting some methods. For example the automated tests must run with mssql too.  

> Currently this sounds bad for me and many other firms/departments :/
> So maybe it would be nice to take it to your roadmap too.

Feature development is primarily driven by our customers and community contributors. I'd be happy to give some pointers if you feel like implementing this. If you need it in your business and can't do it yourself, feel free to discuss it with one of our account managers. You can submit an inquiry over https://nextcloud.com/enterprise/buy
