### ISSUE TITLE
file_get_contents(): read of 8192 bytes failed with errno=21

### ISSUE THREAD

**Issue by apryaldy** [nextcloud/server#26707]
NextCloud Version 21.0.0
PHP Version: 7.4.15
MariaDB Version: 10.3.28

Security and setup warning: All checks passed.

Using External Storage, Linode object storage
But in the log file, receive so many error log like below:
`Error: file_get_contents(): read of 8192 bytes failed with errno=21 Is a directory at /var/www/clients/client1/web4/web/3rdparty/aws/aws-sdk-php/src/functions.php#461`

And CPU Usage always 100%

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)
