### ISSUE TITLE
archive_tar: Fails extracting specific app archives

### ISSUE THREAD

**Issue by icedream** [nextcloud/server#26708]
pear/archive_tar currently contains code that rejects relative symlinks with references to parent folders that are inside TAR archives as described in pear/Archive_Tar#35 and pear/Archive_Tar#37 (dupe).

This leads to apps such as [Social](https://apps.nextcloud.com/apps/social) failing to install since they are falsely detected as extracting out-of-path.

I am creating this ticket merely to track this issue until a fix is released.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

**Comment by icedream** [comment]
I'm closing this issue since we don't seem to be running into it on the newest version anymore. Thanks!

**Comment by marcelklehr** [comment]
I have come across this issue again: https://github.com/marcelklehr/recognize/issues/52

**Comment by szaimen** [comment]
Should be fixed in the next release

**Comment by marcelklehr** [comment]
One of my users just hit this error again with v23.0.4: https://github.com/marcelklehr/recognize/issues/198

**Comment by dontinelli** [comment]
I have same error with v25.0.2
