### ISSUE TITLE
Cron LDAP: Trying to access array offset on value of type bool at /apps/user_ldap/lib/Access.php#556

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#26739]
This error is produced at each Cron run with Nextcloud 21.0.1, for different users.

```
[PHP] Error: Error: Trying to access array offset on value of type bool at /apps/user_ldap/lib/Access.php#556 at <<closure>>

0. /apps/user_ldap/lib/Access.php line 556
   OC\Log\ErrorHandler::onError(8, "Trying to acces ... l", " ... p", 556, {0: "And 7 more  ... l})
1. /apps/user_ldap/lib/Access.php line 913
   OCA\User_LDAP\Access->dn2ocname("uid=yassine_ahm ... r", "Ahmad Yassine", true)
2. /apps/user_ldap/lib/Access.php line 894
   OCA\User_LDAP\Access->batchApplyUserAttributes([{0: "And 2 more ... "])
3. /apps/user_ldap/lib/Jobs/Sync.php line 174
   OCA\User_LDAP\Access->fetchListOfUsers("(&(|(objectclas ... )", ["entryuuid","ns ... "], 500, 2500, true)
4. /apps/user_ldap/lib/Jobs/Sync.php line 143
   OCA\User_LDAP\Jobs\Sync->runCycle({prefix: "s02",offset: 2500})
5. /lib/private/BackgroundJob/Job.php line 52
   OCA\User_LDAP\Jobs\Sync->run(null)
6. /lib/private/BackgroundJob/TimedJob.php line 59
   OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
7. /cron.php line 128
   OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})
```

https://github.com/nextcloud/server/blob/8676d77eeceb1bc74e0fa2b045b4346a5afb1e8d/apps/user_ldap/lib/Access.php#L553-L559

**Comment by acsfer** [comment]
Setting 'ldapIgnoreNamingRules' => true fixes the error.

**Comment by szaimen** [comment]
I suppose this is still valid on NC21.0.3?

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/27798

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
