### ISSUE TITLE
Exception: Database error when running migration latest for app core

### ISSUE THREAD

**Issue by akash3230** [nextcloud/server#26754]
hi I upgraded to nc 21.0.1 and on the upgrade screen I keep on receiving this error. Exception: Database error when running migration latest for app core

**Comment by acsfer** [comment]
Please note, this is a bug report system and you have a template to fill when you create the issue. Please complete it.

**Comment by 0xBYTESHIFT** [comment]
I got it too, will open a new issue on it

**Comment by inok16** [comment]
I got it aswell

**Comment by ElTimablo** [comment]
Closing the bug doesn't make the problem go away. I'm running into this as well.

**Comment by Coderdude112** [comment]
Has anyone found a fix for this? I'm running into the same problem when upgrading from 21.0.3 to the latest (22.0.0.11)

**Comment by serjsv87** [comment]
I join the problem (

**Comment by riodda** [comment]
I have the same problem with update from 20 to 21 with mariadb 10.1.47

Thread on the forum

https://help.nextcloud.com/t/upgrade-failed-from-20-to-21/127760
