### ISSUE TITLE
[21.0.1] "Shared" label isn't removed automatically if the end date of a share has been reached

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#26756]
## Current behavior
After sharing a folder by email with a dedicated end date set, the "Shared" (![20210426_nc_files_share_label-1](https://user-images.githubusercontent.com/2572764/116055876-75a80300-a67d-11eb-9ba8-38d5394e5c17.png)) label hasn't been removed although the end date has already been reached and the share has automatically been disabled/removed.

![20210426_nc_files_share_label-2](https://user-images.githubusercontent.com/2572764/116056096-ae47dc80-a67d-11eb-961f-95c3257edb3a.png)

## Expected behavior
The "Shared" label should also been reset once the end date of a share has been reached and a share gets automatically disabled/removed.

#### Server Configuration
OS: Linux 5.10.31
Web server: Apache2 2.4.46
Database: MariaDB 10.3.23
PHP version: 7.4.15
Nextcloud version: 21.0.1

#### Client Configuration
Browser: Mozilla Firefox 88.0
Operating system: Windows 10

**Comment by szaimen** [comment]
Hi @j-ed did you try to reload the page? I suppose this doesn't solve the issue?

**Comment by j-ed** [comment]
@szaimen Yes, I tried to reload the page but without success.

**Comment by szaimen** [comment]
I suppose this is still happening on NC21.0.3?
