### ISSUE TITLE
"Would you like to update this password?" on navigation in Firefox

### ISSUE THREAD

**Issue by mortie** [nextcloud/server#2675]
In firefox, when navigating around the web interface, you're asked if you want to update your password at every page load. This didn't happen in nextcloud 9, but happens in nextcloud 11. I believe this piece of HTML is responsible:

```
	<div id="sudo-login-form" class="hidden">
		This action requires you to confirm your password:<br>
		<input type="password" class="question" autocomplete="off" name="question" value=" "
			placeholder="Confirm your password" />
		<input class="confirm icon-confirm" title="Confirm" value="" type="submit">
	</div>
```

The password input element is prepopulated with the value " ", and because it's a populated password input, Firefox asks if you want to update your password. I believe removing the space would fix it, though I haven't confirmed this for myself. **EDIT**: I see the space is a hack to fix firefox ignoring autocomplete="off". I don't know what the solution is then.

### Steps to reproduce
1. Go to the nextcloud instance's website in firefox (tested with Mozilla Firefox 52.0a2)
2. Log in
3. Navigate somewhere

### Expected behaviour
No message asking me to update the password

### Actual behaviour
A message asking me whether I want to update the password, like this: [!Screenshot](https://d.mort.coffee/img/scr-1727828.png)

### Server configuration
**Operating system**: Debian Wheezy with kernel 3.2.0-4-amd64

**Web server:** Apache/2.2.22 (Debian)

**Database:** sqlite

**PHP version:** PHP 5.6.29-1~dotdeb+zts+7.1

**Nextcloud version:** 11

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgraded from nextcloud 9, but "upgraded" by downloading the zip file and doing a fresh install and pointing the data directory to the old data directory

**Where did you install Nextcloud from:** https://nextcloud.com/install/#instructions-server

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** only SSL for the web interface

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Mozilla Firefox 52.0a2

**Operating system:** Arch Linux

**Comment by nickvergessen** [comment]
Annoying firefox ignores `autocomplete` the wide spread workaround is use `value=" "` and empty it on rendering. But seems like firefox also tries to save this now....

Anyone any idea? @MorrisJobke @ChristophWurst @LukasReschke

**Comment by nickvergessen** [comment]
PS this is from the password confirmation thing,

Only happens on 52 (alpha and maybe later as well)

**Comment by mortie** [comment]
I've just done a bit of testing, and it seems that if the password element is in a <form> element, Firefox won't offer to remember the password, as it knows the page load wasn't as a result of the form. Making #sudo-login-form a `<form>` (with an `onsubmit` handler running `preventDefault`) instead of a `<div>` would thus probably fix the issue.

Side note: I like to have all my form-like things in a `<form>`, and run all my "form submission logic" in an `onsubmit` event handler, even when the form isn't supposed to trigger a page load, to automatically meet any expectations a user has; pressing enter in an input element, clicking the submit button, any "done" buttons on touch keyboards, etc. all trigger `onsubmit`. Could be something to look into.
