### ISSUE TITLE
/data/nextcloud.log grows when staying on the administration/system page

### ISSUE THREAD

**Issue by jp-weiss** [nextcloud/server#26761]
Hi everybody,
I had just experienced a problem while staying on the administration/system page of Nextcloud.
The data/nextcloud.log file is filled with those messages :
`{"reqId":"En0rXRTVczzpzMff2J9a","level":3,"time":"2021-04-26T11:58:31+00:00","remoteAddr":"10.5.0.50","user":"administrateur","app":"PHP","method":"GET","url":"/index.php/apps/serverinfo/update","message":{"Exception":"Error","Message":"Invalid argument supplied for foreach() at /var/www/nextcloud/lib/private/Installer.php#440","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Installer.php","line":440,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"Invalid argument supplied for foreach()","/var/www/nextcloud/lib/private/Installer.php",440,{"appId":"workflowengine","allowUnstable":false}]},{"file":"/var/www/nextcloud/apps/serverinfo/lib/SystemStatistics.php","line":177,"function":"isUpdateAvailable","class":"OC\\Installer","type":"->","args":["workflowengine"]},{"file":"/var/www/nextcloud/apps/serverinfo/lib/SystemStatistics.php","line":86,"function":"getAppsInfo","class":"OCA\\ServerInfo\\SystemStatistics","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/serverinfo/lib/Controller/PageController.php","line":57,"function":"getSystemStatistics","class":"OCA\\ServerInfo\\SystemStatistics","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"update","class":"OCA\\ServerInfo\\Controller\\PageController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\ServerInfo\\Controller\\PageController"},"update"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\ServerInfo\\Controller\\PageController"},"update"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\ServerInfo\\Controller\\PageController","update",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"serverinfo.page.update"}]},{"file":"/var/www/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/serverinfo/update"]},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0","version":"21.0.0.18"}`
I can't upgrade to the 21.0.1 version because we have a lot of problems with externals storages (but that's another pb ;))

**Comment by andyxheli** [comment]
I had the same issue go into the config.php and make sure your logging is set too 2 for ware gongs and errors.

**Comment by jp-weiss** [comment]
> I had the same issue go into the config.php and make sure your logging is set too 2 for warnings and errors.

Thank you Andrea, I have added the line `'loglevel' => 2,` in the config.php file but the problem persist.

**Comment by andyxheli** [comment]
You made sure debug is unchecked on the logger almost try rebooting the web service

**Comment by jp-weiss** [comment]
> > I had the same issue go into the config.php and make sure your logging is set too 2 for warnings and errors.
> 
> Thank you Andrea, I have added the line `'loglevel' => 2,` in the config.php file but the problem persist.

That's it ! I have added th line `'debug' => true,` in the config.php file and the log file works normally now.

**Comment by andyxheli** [comment]
Happy to hear you got it all fixed
