### ISSUE TITLE
Copy shared address with password

### ISSUE THREAD

**Issue by suozq1** [nextcloud/server#26777]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

When I share the file and set the password, I can not get the password again！I must remember it by myself !
There is no limit to the date of sharing, but my memory is; I cann't always remember the password.

**Describe the solution you'd like**

I expect  that when I copy the connection,there is not only the address but also the password.
e.g:  link:https://nextcloud.com/s/1mFAitVw7mpIO9iS1vJXZQg  password:f34s3 

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/10241390/116186963-32ba5e00-a757-11eb-8feb-e41506e6b7c0.png)

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
