### ISSUE TITLE
Failed to upgrade from 20.07 to 20.09

### ISSUE THREAD

**Issue by ytc-1** [nextcloud/server#26786]
Upgrade produced the following error in the log, I've rolled back to 20.07. Any tips on something to change or check before trying again ?

Checked for update of app "workflowengine" in appstore

Repair step: Repair MySQL collation

Repair info: Change row format for oc_activity ...

Repair info: Change collation for oc_activity ...

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_activity` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. This includes storage overhead, check the manual. You have to change some columns to TEXT or BLOBs

**Comment by ytc-1** [comment]
[NC20_09upgrade.log](https://github.com/nextcloud/server/files/6384750/NC20_09upgrade.log)

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
