### ISSUE TITLE
FTP files_external Normalizing failed

### ISSUE THREAD

**Issue by mellow2012** [nextcloud/server#26783]
Nextcloud 21.0.1

i have just this:
Warning | core | normalizing failed for "Geräte-liste in und out.xlsx"

![Unbenannt](https://user-images.githubusercontent.com/53937799/116227426-6cd63080-a754-11eb-8b3d-e1c25ae54c6b.JPG)

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

I'm closing your report in favor of https://github.com/nextcloud/server/issues/15787.
