### ISSUE TITLE
Share permissions misbehaving

### ISSUE THREAD

**Issue by andreas-p** [nextcloud/server#2679]
Testing using the web GUI:
I have a folder shared to others, with privileges limited to create only. With NC10, the behaviour was as expected: other users could add files to the directory and view them, but couldn't edit or delete them (archiving access). Files uploaded by me were read-only for other users.
For maintenance purposes, the owner of the share (me) was allowed everything on the files (the share owner is considered to be the owner of files in shared folders as well).

With NC11, I see files created with filecache.permissions=1 if other users upload to my shared directory, preventing me from changing/deleting those files (subdirectories as well). I have to add the delete permission bit to filecache.permissions to delete them.

**Comment by andreas-p** [comment]
More bad behaviour:
Other uses can delete directories on that share, even if they can't delete files that are in those directories.

**Comment by LukasReschke** [comment]
@icewind1991

**Comment by LukasReschke** [comment]
@icewind1991 Also please add integration tests. Thanks. Preferably real ones and not the ones in PHPunit ;)

**Comment by LukasReschke** [comment]
@icewind1991 I'd also appreciate to have such kind of tests for any permission related changes. 

cc @rullzer FYI

**Comment by rullzer** [comment]
The permission=1 thing is solved by https://github.com/nextcloud/server/pull/2673

**Comment by rullzer** [comment]
> More bad behaviour:
Other uses can delete directories on that share, even if they can't delete files that are in those directories.

I can't reproduce this on NC11
Can you post detailed steps?

**Comment by andreas-p** [comment]
I can't reproduce that delete directory issue now. 
I *think* I've seen the share user being able to delete a file created by the share owner, but couldn't reproduce it either. 
I'm not sure if it's a spurious program issue or a user glitch.

**Comment by rullzer** [comment]
Ok then this is solved by https://github.com/nextcloud/server/pull/2673

@andreas-p if you manage to reproduce the delete problem. Please open a new issue.

**Comment by andreas-p** [comment]
Will do so.
