### ISSUE TITLE
Grant posssibility to open an navbar token in new tab in the browser

### ISSUE THREAD

**Issue by ChrisCano66** [nextcloud/server#26790]
Hello,

I am an trainee in a public structure that uses nextcloud. Their goal is to use free software and propose improvements for the free community.

In this context, I am working on improving the External module for NextCloud.
We would like to give to users the opportunity to open external links in a new tab of their browser.

To do this, we have to modify the core of NextCloud by adding an option when clicking on links in the navbar. This will allow to External to use this option and for users. However, this will give all applications a chance to do the same.

That’s why we want to ask for your permission to do it if you want it to be possible. On the other hand we would understand that your want to leave the application intuched and don't authorize the following modification for security or other reasons.

By paying attention to our request.

Thank you.

**Comment by kesselb** [comment]
Hi @ChrisCano66 :wave: 

I guess you are talking about external sites right? Repository for external sites is at https://github.com/nextcloud/external.

https://github.com/nextcloud/external/issues/79 sounds like a discussion about this feature.

**Comment by ChrisCano66** [comment]
Hi, @kesselb 

I know for the External Repository and the issue I'm tallking about. But, to respond to it, I need to know if I can modify the Nextcloud Core and add the ability to every links on a nav bar to possibly open in a new tab in the browser.
It's not the way you choose to implement it so, before doing something, I need to now if I can do it.

I need a proper response from NextCloud's guys and not from External's guys.

Thanks for your Help !

**Comment by kesselb** [comment]
A pull request adding a new optional flag new-tab true/false to navigation manager sounds mergeable.

**Comment by ChrisCano66** [comment]
Okay ! Thank you for your response !

**Comment by szaimen** [comment]
Thanks for the PR! Lets track the overlaying issue then back in https://github.com/nextcloud/external/issues/79 :)
