### ISSUE TITLE
User created date not available in user metadata API response

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/server#26791]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
The user management is missing information about the creation date of a user.

**Describe the solution you'd like**
Add "date created" information to the user metadata API response.

**Additional context**
- This is similar to https://github.com/nextcloud/server/issues/22640 and could probably be added in a common PR.
- Unclear if this information is already available in the database. Could someone point out in which table/column it can be found?

**Comment by kesselb** [comment]
Afaik we don't store the user created date.

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/22640
