### ISSUE TITLE
How to rebrand Nextcloud fully and change the appearance 

### ISSUE THREAD

**Issue by MadMacMig** [nextcloud/server#26795]
I have been wondering and trying to figure out how to remove all Nextcloud branding and also how to change the look of the whole web interface to my own. One of the big things that I'd like to take out is the Reasons to use Nextcloud footer in settings and more.

Because Nextcloud is truly open source, ii'd like to try and make a fully custom version based on Nextcloud but with a complete different look, and not only use Nextcloud for storage, but also find a way to make it into an OS so that I can also integrate VMs into user's account.

You might wonder why I would like to do this, and the reason is that I am looking to try and start up a cloud company like Dropbox and AWS but all in one. And I thought, because Nextcloud is already very advanced, I thought it would be a great place to start.

**Comment by kesselb** [comment]
> I have been wondering and trying to figure out how to remove all Nextcloud branding and also how to change the look of the whole web interface to my own. 

Some branding can be changed via theming app or an custom theme. 

> One of the big things that I'd like to take out is the Reasons to use Nextcloud footer in settings and more.

https://github.com/nextcloud/server/issues/26006

> Because Nextcloud is truly open source, ii'd like to try and make a fully custom version based on Nextcloud but with a complete different look, and not only use Nextcloud for storage, but also find a way to make it into an OS so that I can also integrate VMs into user's account.

Cool :+1:

**Comment by MadMacMig** [comment]
> > I have been wondering and trying to figure out how to remove all Nextcloud branding and also how to change the look of the whole web interface to my own.
> 
> Some branding can be changed via theming app or an custom theme. As nextcloud is open source you may change everything.
> 
> > One of the big things that I'd like to take out is the Reasons to use Nextcloud footer in settings and more.
> 
> #26006
> 
> > Because Nextcloud is truly open source, ii'd like to try and make a fully custom version based on Nextcloud but with a complete different look, and not only use Nextcloud for storage, but also find a way to make it into an OS so that I can also integrate VMs into user's account.
> 
> Cool 👍

How am I able to make a custom theme? I am pretty new with this sort of stuff. And should I send you an example of what id like the interface to look like to see if it is possible through a custom theme?

**Comment by kesselb** [comment]
> How am I able to make a custom theme? I am pretty new with this sort of stuff. 

You need to know php, html, css and js.  https://docs.nextcloud.com/server/15/developer_manual/core/theming.html is the old documentation for custom themes. As this way to customize is not recommended anymore there is no documentation for newer versions.

> And should I send you an example of what id like the interface to look like to see if it is possible through a custom theme?

No.

**Comment by MadMacMig** [comment]
One more thing. How do I delete the create a new user account for free link on public pages? And how do I delete the help button in the top right menus and also how to remove the privacy tab in the settings window menu.
