### ISSUE TITLE
External Storage CIFS/SMB 0Byte (mount SMB2)

### ISSUE THREAD

**Issue by habaneroman** [nextcloud/server#268]
### Parent

https://github.com/owncloud/core/issues/17044
### Steps to reproduce
1. Confige CIFS/SMB als external Storage. 
2. Upload files bigger than 68kByte.
### Actual behaviour

The file is created but empty.
### Server configuration

NAS: EMC ISILON 7.2.1.2
NextCloud: 9.0.51
Linux: Ubuntu 16.4 LTS, Ubuntu 15.10
Samba 4
### Logs:

samba_tevent: EPOLL_CTL_DEL EBADF for fde[0x7f2d20011830] mpx_fde[(nil)] fd[6] - disabling
cli_push returned NT_STATUS_CONNECTION_DISCONNECTED
### Posible Solution:

OC user via sms4php smbclient to access the external Storage.
#### Workarround 1)

If Samba 3 is used every thinks works fine. But Samba 3 can't be used under Ubuntu 14,15 and 16.
#### Workarround 2)

Manual copying data with smbclient using the smb2 or smb3 protocol works fine.
<code> /etc/samba/smb.conf
 [global]
 client max protocol = SMB2
</code>
but subdirectorys cant't be seen in nextcloud.
### Question

Ist the a way to use SMB2 or SMB3 insted of CIFS?

**Comment by mar1u5** [comment]
I think this is something what will be fixed in `owncloud/core`, because they have already assigned a milestone on this 😉 ... I would vote for waiting, until we can make an backport 😈

**Comment by MorrisJobke** [comment]
> ...other hand is, that nothing was done since Jun 19, 2015 😅

@mar1u5 There was nothing done on this yet. There is no linked PR. :(

**Comment by mar1u5** [comment]
Then nothing will happen ... Its feature freeze time 😁 They will move the milestone :( You're right.

**Comment by habaneroman** [comment]
What can I do to advance the solution?

**Comment by icewind1991** [comment]
> Ist the a way to use SMB2 or SMB3 insted of CIFS?

configuring it in smb.conf is the only way atm

**Comment by habaneroman** [comment]
I already changed the smb.conf to use SMB2.
<code> /etc/samba/smb.conf
 [global]
 client max protocol = SMB2
</code>
but there was no way to open any subdirectory of the mounted device.

**Comment by habaneroman** [comment]
### Server Configuration
-  Nextcloud 11
-  Ubuntu 16.04.2 LTS 
-  php-smbclient
-  ISILON OneFS Version: 7.2.1.2

### Result
-  Everything works fine. 

### Comments
-  Using php-smbclient instead of smbclient solved the problem.
-  libsmbclient-php announced in (https://docs.nextcloud.com/server/11/admin_manual/configuration_files/external_storage/smb.html) is not found in Ubuntu 16.4.2 LTS. php-smbclient does the same.
