### ISSUE TITLE
Bad file info on conflicting upload

### ISSUE THREAD

**Issue by andreas-p** [nextcloud/server#2680]
Webgui NC11.0:
Consider user A having the GUI showing a shared directory. User B uploads a file test.txt to that directory. Now user A tries to upload a test.txt to that directory as well. After the server-side conflict, the GUI will try to preview.png that B-Version of test.txt, but fails since an invalid URL is created. Apparently, the fileInfo.directory as expected by oc-dialogs isn't filled, so the URI is assembled as undefined/DirName. As a result, not only the preview image won't show up, but the file information isn't retrieved from B-test.txt but from the root directory.
This definitively did work correctly in NC10.

NB: If the A-GUI already shows the B-version, the conflict is identified right from the filelist without server roundtrip, giving the correct preview image and file information.

**Comment by LukasReschke** [comment]
@icewind1991
