### ISSUE TITLE
Carry Theming to Maintenance Mode Page

### ISSUE THREAD

**Issue by derkeljoe** [nextcloud/server#26812]
Love Nextcloud!  I have a request. I wrote a script to do an hourly backup which places my Nextcloud instance into maintenance mode during the backup. It only takes a few minutes but when users attempt to log in during the backup, they see the Nextcloud logo and a background they are unfamiliar with, leading to emails asking if the site has been compromised and if it’s safe to log in. 

It would be really nice if the custom theme (like my logo) could be carried into the maintenance page so users are more comfortable and aren’t questioning the security of the site. 

Thanks, and thank you for all your hard work making a great product!

**Comment by kesselb** [comment]
Hi, see https://github.com/nextcloud/server/issues/5789
