### ISSUE TITLE
README.md box shows on top of Collabora Office for external users

### ISSUE THREAD

**Issue by zynexiz** [nextcloud/server#26828]
Not sure if this is a NextCloud issue, or a Collabora Office issue? This is NOT an issue when you access the document from a user with an account on the server, just for non users.

### Steps to reproduce
1. Share a folder with an external user (I did thru e-mail)
2. Make sure there is a README.md file inside that folder with some text
3. Open a document in Collabora office
4. The README.md text bar is still shown on top of Collabora Office view

![Screenshot_20210429_112818](https://user-images.githubusercontent.com/22789493/116530274-2280bb00-a8de-11eb-95e8-d9b1c0895791.png)

### Expected behaviour
When open a document, the README.md text bar should be hidden.

### Server configuration

**Operating system:**
CentOS 8 Stream

Server version: Apache/2.4.37 (centos)
Server built:   Jul 31 2020 20:44:41

mysql  Ver 15.1 Distrib 10.3.27-MariaDB, for Linux (x86_64) using readline 5.1

PHP 7.4.18 (cli) (built: Apr 27 2021 14:35:46) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.18, Copyright (c), by Zend Technologies

**Nextcloud version:**
NextCloud 21.0.1
Upgraded from older version since a long time thru web interface.

**Comment by mikesmichael** [comment]
I have the exact same problem.

Only happen on office or open Office document opened with Collabora viewer. Other document opened with another viewer are correctly displayed.Same document opened without the share link will correctly display.

In my case the share link is read only, but is the same behavior if the edition is enabled.

**Comment by mikesmichael** [comment]
I found a solution. Check the pull request on projet nextcloud/text: https://github.com/nextcloud/text/pull/1631

Quick fix on local to test without compiling: change the value of css position `unset` to `sticky` in  `apps/text/js/public.js`  search for` #rich-workspace`  `#editor-wrapper`

Exemple of what you have to find:
`(#rich-workspace[data-v-374052d2] #editor-wrapper{position:unset !important;overflow:visible}`

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/27588
