### ISSUE TITLE
Change of group membership activity notification 

### ISSUE THREAD

**Issue by tglemser** [nextcloud/server#26829]
In the configuration for activity notifications
a) the field E-Mail is "disabled" client side for notifications regarding group changes of my account
b) notification of group changes of users I'm confihgured as an administrator is not available

Feature Requests:
a) As a user I want to be able to disable E-Mail notifications for changes in my groups.
b) As a group administrator I want to be able to configure notifications for changes of other users in groups, I'm configured as an administrator.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
