### ISSUE TITLE
sync nextcloud tags to s3 tags ?

### ISSUE THREAD

**Issue by philpep** [nextcloud/server#26833]
I use s3 external storage and noticed tags created to s3 are not created on s3 as well.

See https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-tagging.html

It might not be easy to make it work because tags in s3 are key value and tags in nextcloud are simple text.

But I think this could be considered since it make nextcloud a perfect user frontend to manage files used by applications using s3. Also we could consider bidirectional-sync.

Thanks!

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
