### ISSUE TITLE
Suggest Installing PHP Database and PDO Module If not Installed

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#26839]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I was deploying an instance, however I forgot to install database and PDO module so I ran into an internal server error.

**Describe the solution you'd like**
Suggest installing PHP database and PDO module if not Installed.
``php-mysql`` and ``php-pdo_mysql`` for Mysql/MariaDB
``php-pqsql`` and ``php-pdo_pqsql`` for PostgresQL
``php-sqlite3`` and ``php-pdo_sqlite`` for SQLite

**Describe alternatives you've considered**
Nothing else.

**Additional context**
#21296
```json
{
  "reqId": "6xQagzSVcZiy9cyc724G",
  "level": 3,
  "time": "2021-04-29T18:59:29+00:00",
  "remoteAddr": "127.0.0.1",
  "user": "--",
  "app": "index",
  "method": "GET",
  "url": "/nextcloud/",
  "message": {
    "Exception": "Error",
    "Message": "Class 'PDO' not found",
    "Code": 0,
    "Trace": [
      {
        "file": "/usr/local/www/nextcloud/lib/private/Setup.php",
        "line": 197,
        "function": "getAvailableDbDriversForPdo",
        "class": "OC\\Setup",
        "type": "->",
        "args": []
      },
      {
        "file": "/usr/local/www/nextcloud/lib/private/legacy/OC_Util.php",
        "line": 758,
        "function": "getSupportedDatabases",
        "class": "OC\\Setup",
        "type": "->",
        "args": []
      },
      {
        "file": "/usr/local/www/nextcloud/lib/base.php",
        "line": 650,
        "function": "checkServer",
        "class": "OC_Util",
        "type": "::",
        "args": [
          {
            "__class__": "OC\\SystemConfig"
          }
        ]
      },
      {
        "file": "/usr/local/www/nextcloud/lib/base.php",
        "line": 1076,
        "function": "init",
        "class": "OC",
        "type": "::",
        "args": []
      },
      {
        "file": "/usr/local/www/nextcloud/index.php",
        "line": 35,
        "args": [
          "/usr/local/www/nextcloud/lib/base.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/usr/local/www/nextcloud/lib/private/Setup.php",
    "Line": 143,
    "CustomMessage": "--"
  },
  "userAgent": "Mozilla/5.0 (X11; FreeBSD amd64; rv:78.0) Gecko/20100101 Firefox/78.0",
  "version": ""
}
```

**Comment by szaimen** [comment]
@HouraisanNEET do you mind creating a PR with a patch for discussion?
Thank you!

**Comment by HouraisanNEET** [comment]
So do I work on this? Maybe it's not that hard as I thought and I would give it a try.

**Comment by HouraisanNEET** [comment]
Okay I submitted a PR. It looks like a bug instead.
