### ISSUE TITLE
Add Redis Cluster Key Prefix 

### ISSUE THREAD

**Issue by r4nc0r** [nextcloud/server#26830]
**Is your feature request related to a problem? Please describe.**
When adding Redis Cluster to Nextcloud, the Redis Cluster is overrun from nextcloud keys, which all lie on the top level. Wouldnt it be good to add a Prefix to the keys for a better overview in a shared Redis Cluster Deployment (Our Redis Cluster serves multiple apps)

**Describe the solution you'd like**
Possibility to specify a Redis Key Prefix

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by Yannik** [comment]
Adding my interest for this feature.

**Comment by sansna** [comment]
nice to me.

**Comment by KD0BPV** [comment]
Please add this! At this point, it's a basic necessity for redis security. This is NOT a "Nice to have", this is a SECURITY ESSENTIAL!

**Comment by Robert-Riedl** [comment]
just FYI this has now been added 
https://github.com/nextcloud/server/pull/58705
