### ISSUE TITLE
More values for administrative shared link expiration date settings

### ISSUE THREAD

**Issue by nilskamm** [nextcloud/server#26854]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I use the Administration - Sharing setting "Set default expiration date for link shares" and "Enforce expiration date". Now we will have our first link share and just stumbled upon a problem. If "Expire after XX days" is set, this is the ultimate maximum and users can only choose within this time.

**Describe the solution you'd like**
I would like to have one field for "standard expiration time" and one for "maximum expiration time". So that for example 14 days will be the pre-defined standard for every link but it is possible to choose within 90 days. Hope more people are interessted in it and it becomes a thing. 

Thanks a lot!

**Comment by artonge** [comment]
Unfortunately the described feature is not really high on our priority list. But this doesn't mean that we don't like the idea or that we are against this feature per se. Quite the opposite! slightly_smiling_face

There are many way to get new features in Nextcloud:

1. The easiest and most straight forward way (especially here at Github): pull request.
       Nextcloud is completely Free Software, this means that everyone is welcome to join and to contribute. If you or anyone else want to work on this feature, this would be great! We appreciate every pull request, and we are definitely able to help in case of questions, reviews, etc.

2. Another option is creating a bounty at [Bountysource](https://www.bountysource.com/search?query=nextcloud), although just putting money on an issue doesn't guarantee that someone picks it up (in time). But in general it is a nice way to support the huge Nextcloud community. In case of a Nextcloud GmbH employee picks up the bounty we will give it back to the community by putting the money back on other bounties to make sure all bounties benefit the Nextcloud community.

3. We have a [category for Freelancers in our form](https://help.nextcloud.com/c/nextcloud-freelancing). Another option would be to post an offer there and try to find a freelancer who want to work on it.

4. The most direct way for a company or organization to get the issue addressed is to get a [Enterprise Subscription](https://nextcloud.com/pricing/). This includes everything to enable you to run Nextcloud in a productive environment with guaranteed SLA's and more. The Enterprise Subscription also includes optional professional services such as custom development. Feel free to [reach out to us](https://nextcloud.com/contact/). We are happy to explore the possibilities how to make Nextcloud fit your needs.
