### ISSUE TITLE
Missing cache control for (some) static resources

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#26851]
Is there any reason why extensions like `jpg` or `png` are not included here?
https://github.com/nextcloud/server/blob/5cccbbdd453c742ba13b3a0fd01aba406389411f/.htaccess#L41-L44

**Comment by szaimen** [comment]
cc @juliushaertl

**Comment by juliushaertl** [comment]
Yes, would indeed make sense to add that. pull requests are very welcome.
