### ISSUE TITLE
index.php/core/apps/recommended

### ISSUE THREAD

**Issue by huabai** [nextcloud/server#26868]
My environment
nextcloud 20.01
ubuntu 20.04
apache2
php8.0
mariadb-server 10.5.9

My apache2 config file
--------------------------------------------------------------------------
<VirtualHost *:80>
 DocumentRoot "/var/www/html/nextcloud"
 ServerName your-domain.com
 ErrorLog ${APACHE_LOG_DIR}/nextcloud.error
 CustomLog ${APACHE_LOG_DIR}/nextcloud.access combined
 <Directory /var/www/html/nextcloud/>
 Require all granted
 Options FollowSymlinks MultiViews
 AllowOverride All
 <IfModule mod_dav.c>
 Dav off
 </IfModule>
 SetEnv HOME /var/www/html/nextcloud
 SetEnv HTTP_HOME /var/www/html/nextcloud
 Satisfy Any
 </Directory>
 </VirtualHost>
--------------------------------------------------------------------
My php.ini file
-----------------------------------------------
max_execution_time = 300
max_input_time = 600
memory_limit = 512M
upload_max_filesize = 512M
-----------------------------------------------

and install nextcloud 
error:index.php/core/apps/recommended

How to solve this problem
thanks your

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
