### ISSUE TITLE
Filename *_adblue* renders file unusable within the webinterface

### ISSUE THREAD

**Issue by Djoraan** [nextcloud/server#26876]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. create a file with "_adblue" as part of its name, e.g. test_adblue.txt
2. try to access or delete the file
3. 

### Expected behaviour
file can be edited, renamed or deleted

### Actual behaviour
Error PopUp is being shown
I was able to reproduce this error in multiple setups. It does not seem to relate to any webserver, db or whatever configuration

### Server configuration

**Operating system:**
Raspberry Pi OS, Docker, Ubuntu, you name it...

**Web server:**
Apache (several)

**Database:**
MySQL, MariaDB

**PHP version:**
7.x

**Nextcloud version:** (see Nextcloud admin page)
20.x.x last 4 Versions up to 20.0.9 at least had this problem

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Where did you install Nextcloud from:**
---

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

### Logs

<!--- Reports without logs might be closed as unqualified reports! -->

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Prog1563** [comment]
21.0.1 Can confirm this.

What a weird bug!

**Comment by Djoraan** [comment]
I actually forgot a "." in the filemask. The precise error-filemask is \*_adblue.\* (upper-/lower-case doesn't matter: e.g.: *_AdBlue.md)

Btw. you can fix the file by renaming it on your computer and then use the sync client to push it to nextcloud, you just can't do this via web interface.

**Comment by Prog1563** [comment]
Works just fine on the Android client as well.

**Comment by artonge** [comment]
Hi,

I can't reproduce your error and it seems that the issue you have created is lacking the essential information to help us understand your problem. Please either open a new one and use the appropriate template, or edit your first comment to ensure that we can continue to work with you.

**Comment by Prog1563** [comment]
Update: I don't think this is an issue with Nextcloud. It appears that in my case ublock origin is causing the issue like @kosmosac noted.

Any file that had *"_ad"* in it caused this issue and I noticed that the counter on UBo went up when the error occurred.

@Djoraan Can you confirm this?

**Comment by Djoraan** [comment]
Yes uBlock Origin blocklist was causing the issue.
