### ISSUE TITLE
Auto Upload Videos 

### ISSUE THREAD

**Issue by Dreadlocke12** [nextcloud/server#26888]
I already opened a bug report in the android section of nextcloud they told me to write here my issue: 

I currently have an issue with the autoupload function in nextcloud. I use Android 11 with the Nextcloud App 3.15.1. The application is hosted on an Ubuntu Server and only accessable (for now) in my own Network. I added to the user i am using a smb share where the uploads should land. If i enable the automatic upload it uploads the pictures without any issues but skips the videos. If i choose a different upload folder and not the smb share folder video upload works as well so it must be an issue connecting to the smb share. Do i need to enable a special feature to use the video upload straight to the smb share?

**Comment by kesselb** [comment]
needs info because issue template is missing. Also no reference to the mentioned issue for android.
