### ISSUE TITLE
[USER] Username can’t entered / will automatically created

### ISSUE THREAD

**Issue by Gunnar-GO** [nextcloud/server#26885]
same @ help.nextcloud.com: https://help.nextcloud.com/t/username-cant-entered-will-automatically-created/115460
____
In one instance the username for new user can not be entered anymore. It says "will be generated automatically".

![](https://help.nextcloud.com/uploads/default/original/3X/5/0/50f677b2c30df425602d7c0282d78c08c292c7c8.png)

At the moment no external user-management (LDAP, via SQL etc.) is activated.

**The point is few days before all act as normal. Which change could cause this issue?**

### Expected behaviour
Username can set up

### Actual behaviour
Inputfield is greyed out "will automatically generated"

### Server configuration

**Nextcloud version:** 21.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** install script

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
- accessibility: 1.7.0
- activity: 2.14.3
- apporder: 0.12.0
- bruteforcesettings: 2.1.0
- calendar: 2.2.1
- cloud_federation_api: 1.4.0
- contacts: 3.5.1
- dashboard: 7.1.0
- dav: 1.17.1
- deck: 1.4.2
- drawio: 1.0.0
- event_update_notification: 1.2.0
- federatedfilesharing: 1.11.0
- files: 1.16.0
- files_pdfviewer: 2.1.0
- files_sharing: 1.13.1
- files_trashbin: 1.11.0
- files_versions: 1.14.0
- group_everyone: 0.1.7
- groupfolders: 9.0.1
- logreader: 2.6.0
- lookup_server_connector: 1.9.0
- mail: 1.9.5
- notifications: 2.9.0
- oauth2: 1.9.0
- occweb: 0.0.7
- password_policy: 1.11.0
- provisioning_api: 1.11.0
- serverinfo: 1.11.0
- settings: 1.3.0
- sharebymail: 1.11.0
- spreed: 11.1.2
- systemtags: 1.11.0
- tasks: 0.13.6
- timetracker: 0.0.55
- twofactor_backupcodes: 1.10.0
- user_status: 1.1.1
- viewer: 1.5.0
- workflowengine: 2.3.0Disabled:
- admin_audit
- comments
- contactsinteraction
- encryption
- federation
- files_external
- files_rightclick
- files_videoplayer
- firstrunwizard
- ldap_write_support
- nextcloud_announcements
- photos
- privacy
- recommendations
- richdocuments
- richdocumentscode
- support
- survey_client
- text
- theming
- updatenotification
- user_ldap
- weather_status
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
  "system": {
 "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": ***REMOVED SENSITIVE VALUE***,
        "datadirectory": ***REMOVED SENSITIVE VALUE***,
        "tempdirectory": "\/home\/www\/cloud_data\/temp",
        "dbtype": "mysql",
        "version": "21.0.1.1",
        "overwrite.cli.url": ***REMOVED SENSITIVE VALUE***,
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "simpleSignUpLink.shown": false,
        "maintenance": false,
        "default_language": "de",
        "default_locale": "de_DE",
        "default_phone_region": "DE",
        "lost_password_link": "disabled",
        "skeletondirectory": "",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "app_install_overwrite": [            "occweb"        ]    
}
```
</details>

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** not now

### Client configuration
**Browser:**
several 
* Chrome
* Edge
* etc.
 
**Operating system:**
Windows 10 several

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

**Comment by Gunnar-GO** [comment]
Didn't read the first line. 👍

**Comment by kesselb** [comment]
I read the first line.
