### ISSUE TITLE
Imported VCARD wil not sync via CARDDAV

### ISSUE THREAD

**Issue by mrAceT** [nextcloud/server#26884]
### Steps to reproduce
1. have an active CARDDAV connection (in my case EMclient)
2. go to contacts in the webinterface
3. import vcf containing this:
BEGIN:VCARD
VERSION:3.0
PRODID:-//MailClient.VObject/7.2.34208.0
N:A firstname;A test contact;;;
SORT-STRING:A test contact
FN:A firstname 
TEL;TYPE=HOME;TYPE=VOICE;TYPE=PREF:0513541234
item1.ADR;type=HOME;type=pref:;;A Street 6;A City;;;
item1.X-ABADR:NL
REV:2020-04-04T07:53:17Z
END:VCARD
4. import goes OK, one sees the imported contact in the webinterface

### Expected & Actual behaviour
One would expect to see the contact come into view in the DAV share also. Manually added contacts do get synced

### Server configuration

**Operating system:** CentOS Linux release 8.3.2011

**Web server:**  Apache/2.4.37

**Database:** mysql 8.0.21

**PHP version:** PHP 7.4

**Nextcloud version:** 21.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from version 20

**Where did you install Nextcloud from:** from/via nextcloud

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - calendar: 2.2.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 3.5.1
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - deck: 1.4.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - groupquota: 0.1.5
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - mail: 1.9.5
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - quota_warning: 1.10.0
  - recommendations: 1.0.0
  - richdocuments: 4.0.4
  - richdocumentscode: 6.4.705
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - spreed: 11.1.2
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.knoopbeheer.nl"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.1.1",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "nl",
        "default_phone_region": "NL",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": 465,
        "mail_smtpsecure": "STARTTLS",
        "mail_smtpauthtype": "LOGIN",
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2
    }
}
```
</details>

**Are you using external storage, if yes which one:**  dat storage is an extra drive mounted via fuse.bindfs

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome 90.0.4430.93

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
none in connection with..
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
none in connection with..
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
none in connection with..
```
</details>

**Comment by mrAceT** [comment]
Could some confirm this bug? (Or is it just me?)

**Comment by BernieO** [comment]
I just tried that and imported your example vcf to the contacts app of the webinterface of Nextcloud 21.0.1 (contacts app version 3.5.1).
The contact gets synced to my iOS device (iOS 14.5).

So I can _not_ confirm this bug.

**Comment by mrAceT** [comment]
OK, thank you for testing, this helps.

I'll investigate further

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)
