### ISSUE TITLE
wrong redirect after install

### ISSUE THREAD

**Issue by christianwohlgemuth** [nextcloud/server#26887]
### Steps to reproduce
1. docker run nextcloud
2. goto URL => nextcloud.home.net
3. type usernname & password
4. select SQLite
5. uncheck "install apps" 
6. Submit

### Expected behaviour
redirect to http://nextcloud.home.net/index.php/apps/files/

### Actual behaviour
redirect to http://index.php/apps/files/ (without fqdn)

### Server configuration

**Operating system:**
docker image on debian 10

**Nextcloud version:** (see Nextcloud admin page)
21.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Comment by artonge** [comment]
Hi,

I can't reproduce your error and it seems that the issue you have created is lacking the essential information to help us understand your problem. Please either open a new one and use the appropriate template, or edit your first comment to ensure that we can continue to work with you.

**Comment by christianwohlgemuth** [comment]
this is my docker-compose.yml. maybe traffic cause the error...

version: '3.8'
services:
  nextcloudone:
    image: nextcloud
    networks:
      - nextcloudone
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloudone.entrypoints=web
      - traefik.http.routers.nextcloudone.rule=Host(`nextcloudone.home.net`)
      - traefik.http.routers.nextcloudone.middlewares=httpsRedirect@file
      - traefik.http.routers.nextcloudonesecure.entrypoints=websecure
      - traefik.http.routers.nextcloudonesecure.rule=Host(`nextcloudone.home.net`)
      - traefik.http.routers.nextcloudonesecure.tls=true
      - traefik.http.routers.nextcloudonesecure.tls.certresolver=letsEncrypt
      - traefik.http.services.nextcloudonesecure.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.enable=true

**Comment by artonge** [comment]
Could you share your whole `doker-compose.yml` file so I can try to reproduce ?

**Comment by christianwohlgemuth** [comment]
root@homeserver:/opt/docker/nextcloud# cat docker-compose.yml
version: '3.8'
services:
  nextcloudone:
    image: nextcloud
    networks:
      - nextcloudone
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloudone.entrypoints=web
      - traefik.http.routers.nextcloudone.rule=Host(`nextcloudone.home.net`)
      - traefik.http.routers.nextcloudone.middlewares=httpsRedirect@file
      - traefik.http.routers.nextcloudonesecure.entrypoints=websecure
      - traefik.http.routers.nextcloudonesecure.rule=Host(`nextcloudone.home.net`)
      - traefik.http.routers.nextcloudonesecure.tls=true
      - traefik.http.routers.nextcloudonesecure.tls.certresolver=letsEncrypt
      - traefik.http.services.nextcloudonesecure.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.enable=true
  nextcloudtwo:
    image: nextcloud
    networks:
      - nextcloudtwo
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloudtwo.entrypoints=web
      - traefik.http.routers.nextcloudtwo.rule=Host(`nextcloudtwo.home.net`)
      - traefik.http.routers.nextcloudtwo.middlewares=httpsRedirect@file
      - traefik.http.routers.nextcloudtwosecure.entrypoints=websecure
      - traefik.http.routers.nextcloudtwosecure.rule=Host(`nextcloudtwo.home.net`)
      - traefik.http.routers.nextcloudtwosecure.tls=true
      - traefik.http.routers.nextcloudtwosecure.tls.certresolver=letsEncrypt
      - traefik.http.services.nextcloudtwosecure.loadbalancer.server.port=80
      - com.centurylinklabs.watchtower.enable=true
networks:
  nextcloudone:
    external: true
  nextcloudtwo:
    external: true

root@homeserver:/opt/docker/traefik# cat docker-compose.yml
version: '3.8'
services:
  traefik:
    restart: always
    image: traefik:v2.3
    container_name: traefik
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.port53udp.address=:53/udp
      - --certificatesresolvers.letsEncrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsEncrypt.acme.email=nospam@example.com
      - --certificatesresolvers.letsEncrypt.acme.storage=acme.json
      - --serverstransport.insecureskipverify
      - --pilot.token=#token
    ports:
      - 80:80
      - 443:443
      - 53:53/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/docker/traefik/acme.json:/acme.json
      - /opt/docker/traefik/dynamic.yml:/etc/traefik/dynamic.yml
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.rule=Host(`traefik.home.net`)
      - traefik.http.routers.traefik.middlewares=httpsRedirect@file
      - traefik.http.routers.traefiksecure.entrypoints=websecure
      - traefik.http.routers.traefiksecure.rule=Host(`traefik.home.net`)
      - traefik.http.routers.traefiksecure.tls=true
      - traefik.http.routers.traefiksecure.tls.certresolver=letsEncrypt
      - traefik.http.routers.traefiksecure.tls.domains[0].main=traefik.home.net
      - traefik.http.routers.traefiksecure.tls.options=default
      - traefik.http.routers.traefiksecure.middlewares=traefik-auth,secHeaders@file
      - traefik.http.routers.traefiksecure.service=api@internal
      - traefik.http.middlewares.traefik-auth.basicauth.users=
      - com.centurylinklabs.watchtower.enable=true
    healthcheck:
      test: wget --spider http://localhost:8080 || exit 1
      interval: 10s
      timeout: 1s
      start_period: 10s
      retries: 1
    networks:
      - pihole
      - demodocs
      - nextcloudone
      - nextcloudtwo
networks:
  pihole:
    external: true
  demodocs:
    external: true
  nextcloudone:
    external: true
  nextcloudtwo:
    external: true

root@homeserver:/opt/docker/traefik# cat dynamic.yml
tls:
  options:
    default:
      minVersion: VersionTLS12
      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256
      curvePreferences:
        - CurveP521
        - CurveP384
      sniStrict: true
http:
  middlewares:
    httpsRedirect:
      redirectScheme:
        scheme: https
        permanent: true
    secHeaders:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        sslRedirect: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        contentSecurityPolicy: "default-src 'self' https://pilot.traefik.io; img-src 'self' 'data:'; style-src 'self' 'unsafe-inline'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'; form-action 'self' http://nextcloudone.home.net/login/flow;"
        publicKey: "pin-sha256=\"mo1jUh9+bN5f6pMQl02vZBzkVY1o0VPeYVV2FFO1LgA=\"; max-age=2592000; includeSubDomains;"
        referrerPolicy: "no-referrer"
        customResponseHeaders:
          Permissions-Policy: "accelerometer=(),ambient-light-sensor=(),autoplay=(),battery=(),camera=(),display-capture=(),document-domain=(),encrypted-media=(),fullscreen=(),geolocation=(),gyroscope=(),layout-animations=(),legacy-image-formats=(),magnetometer=(),microphone=(),midi=(),oversized-images=(),payment=(),picture-in-picture=(),publickey-credentials-get=(),sync-xhr=(),unoptimized-images=(),unsized-media=(),usb=(),vibrate=(),vr=(),wake-lock=(),xr-spatial-tracking=()"
          Expect-CT: "enforce, max-age=30"
          Server: "Apache"

**Comment by mylesmarkevich** [comment]
I had the same issue when I installed NextCloud in a virtual machine today.

I used the setup-nextcloud.php script to install, typed in my username and password and mariadb information, I left the checkmark to install reccomended apps, and I got forwarded to `https://index.php/core/apps/recommended` instead of `https://home.mydomain.com/index.php/core/apps/recommended`

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/27575
