### ISSUE TITLE
Upgrade to v10.0.2 failed on a Migration Exception : ALTER TABLE oc_oc_appconfig

### ISSUE THREAD

**Issue by klorydryk** [nextcloud/server#2691]
### Steps to reproduce
1. From version 10.0.1, launch the automatic updater from administration page
2. At the end of the file update, launch the automatic database update
3. I got this "update failed"
"OC\DB\MigrationException: An exception occurred while executing 'ALTER TABLE oc_oc_appconfig_8cdes1sj5mh4t ADD PRIMARY KEY (`appid`, `configkey`)': SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'activity-enabled' for key 'PRIMARY'"

### Expected behaviour
Update with success :D

### Actual behaviour
Blocked on the update page. Why this "oc_oc_appconfig_8cdes1sj5mh4t" ? My actual database is something like "oc_appconfig"

### Server configuration
**Operating system**:
Debian / Synology DS214+
**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
5.6
**Nextcloud version:** (see Nextcloud admin page)
~Between 10.0.1 and 10.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Owncloud

**List of activated apps:**
Contacts, Agenda, Gallery

**Are you using external storage, if yes which one:** local/smb/sftp/...
Nope
**Are you using encryption:** yes/no
Nope
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Nope

### Client configuration
**Browser:**
Firefox

**Comment by LukasReschke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
What? Not my cause, update simulation failure because the primary key checking failed. The primary key on that table is also not new, so it shouldn't be created.

My advice would be to make a backup and then update with `--skip-migration-test` on the console.

**Comment by klorydryk** [comment]
I tried to update via the console with "sudo php56 occ upgrade --skip-migration-test"
-> "Nextcloud is already latest version"
So I wrote:  "sudo php56 occ upgrade -V"
-> "Nextcloud version 10.0.1"

**Comment by nickvergessen** [comment]
Did you revert the files update?

**Comment by klorydryk** [comment]
I've just copied the backup "nextcloud/updater-oclxfiphcr70/backups/nextcloud-9.1.1.5" again, to be sure, and same message.

**Comment by nickvergessen** [comment]
Upload the new files again and then instead of running the update, run `occ upgrade --skip-migration-test` from the console, see https://docs.nextcloud.com/server/10/admin_manual/maintenance/manual_upgrade.html

**Comment by MorrisJobke** [comment]
I can't reproduce this issue.

I this is still a problem on your side then we are happy to reopen this ticket. Thanks
