### ISSUE TITLE
Check availablity of apps before doing a server major update

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#2692]
Happened to one of the participants of the Stuttgart meetup.
He updated the instance and suddenly one app was disabled and he couldn't enable it anymore,
because back then the tasks app was not available for NC11.

It should be fairly easy to check this up-front before the person even starts the updater.

What do you think? @LukasReschke @MorrisJobke @jancborchardt

**Comment by MorrisJobke** [comment]
> It should be fairly easy to check this up-front before the person even starts the updater.

Yep - makes sense. But for the CLI updater this is hard to accomplish, because I don't want to have any dependencies between updater and server. For the web updater this is fine, because the "Open updater" button is part of the server.

**Comment by nickvergessen** [comment]
No, I wouldn't do that in the updater, but on the admin page

**Comment by MorrisJobke** [comment]
Provided by the caniupdate app https://github.com/nextcloud/caniupdate

We maybe should think about adding this to the update notification app later.

**Comment by nickvergessen** [comment]
Yeah, lets keep that issue open as a reminder for me to "fix" the update notification app.

**Comment by nickvergessen** [comment]
I just noticed, I use vue.js in the "Can I update?" app.
Now when I move all the code to the "Update notification" app, which is in the server repo, should I move the vue.js to that app, or to core?

cc @nextcloud/javascript for best practice

**Comment by MorrisJobke** [comment]
To the app. The goal is to have no dependency to apps.
