### ISSUE TITLE
Delay file sync in the presence of lock-file

### ISSUE THREAD

**Issue by RREE** [nextcloud/server#26926]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I maintain a Nextcloud system for a small architecture office. The CAD files from ArchiCAD get very big (a few hundred MB, rarely a GB) and have special features when getting written to disk. The manufacturer Graphisoft therefore recommends against any file syncing program (https://helpcenter.graphisoft.com/knowledgebase/95438/). 
 The solution that we use right now is to stop nextcloud when starting to draw in ArchiCAD and to restart Nextcloud manually after work. I'd like to get that automated as the users quite often forget to restart Nextcloud.

**Describe the solution you'd like**
Inhibit syncing files while there is a lock file in the same directory. i.e. if there is a lock file drawing1.pbn.lck don't sync drawing1.pbn
When the lock file disappears the locked file may now by synced

**Describe alternatives you've considered**
sync files not immediately after they get written but on schedule, e.g. daily at 08:00, or every two hours
 
**Additional context**

**Comment by szaimen** [comment]
Please refer to https://github.com/nextcloud/files_lock/issues/27
Thanks!
