### ISSUE TITLE
[UX] Allow deletetion of recently uploaded files in public share

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/server#26927]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

## Is your feature request related to a problem? Please describe.
As an external user I want to be able to delete a recently uploaded file in a public share with only file drop, because an accidentially uploaded file could countain (sensible) information, which I don't want to be seen by another person. Beeing able to immediatly revert the mistake raises the trust in using such features by external users and supports the NC promise of "control your data".

## Describe the solution you'd like
Each uploaded file is listed after the upload is complete, so I can check, if the process was successful. Add a delete button near the file, so the user is able to undo the upload while the current session is active.

## Describe alternatives you've considered
No idea

## Additional context
We should give users the ability to be able to revert recognized mistakes while using Nextcloud. Public share drops are commonly used by users, which are not familiar with Nextcloud and are often not technically orientated. Mistakes are quite common and often only recognized after the action. 

Proposal mockup for the UI: 
![grafik](https://user-images.githubusercontent.com/26707476/117533744-cfe68380-afee-11eb-8ae8-9dd282f926a0.png)

**Comment by szaimen** [comment]
cc @nextcloud/designers

**Comment by dartcafe** [comment]
I would at least recomment a review, before automatically closing feature requests.

**Comment by juliushaertl** [comment]
cc @jancborchardt @nimisha-vijay 

Technically this is not that easy as the folder is then shared only with permission to create new files, listing and update/delete is blocked by the storage layer.

**Comment by bes1002t** [comment]
mh difficult to decide.

There are use cases which require upload only permissions and the user must be not able to remove his uploaded files. But there are also many use cases which work perfectly if users are able to delete only their uploaded files. Would be reasonable if it is not too much effort.

But I also think this is not a trivial implementation.

**Comment by dartcafe** [comment]
> There are use cases which require upload only permissions and the user must be not able to remove his uploaded files.

This is abolutely ok, if the user uploads, closes the window and wants to come back after her recognizes he made an error. 

My use case is to be able to delete an uploaded file immediately after the upload, like an undo feature. IMHO The user should be able to correct his mistaken upload to protect his privacy. I was hoping, that it would be possible to allow the deletion while the session in which the upload was done is still active. #ownyourdata

This was just for clarification of my request. But I absolutely understand the technical caveat.

**Comment by bes1002t** [comment]
I never toucht a Nextcloud backend line of code, but I can image that it would be quite difficult to decide in backend whether a user already closed the browser and came back.

But I think a 5 minutes time range that enables the user to delete the uploaded file could fit such requirements. So from a data safety point of view this would make sense. What do you think @jancborchardt ?

**Comment by nimisha-vijay** [comment]
It definitely makes sense to have a step like this. 
What would be even better would be the ability to first select the files you want to upload, see them like this, and then upload them. But again it is probably even more difficult to implement technically.
An undo is a good workaround for now.
