### ISSUE TITLE
Can not use redis sentinel

### ISSUE THREAD

**Issue by jsalatiel** [nextcloud/server#26929]
According to https://github.com/nextcloud/server/blob/v21.0.1/config/config.sample.php#L1225, to use redis sentinel one should "use the single  server configuration above, and perform HA on the hostname." Although it is not clear for me what perform HA on the hostname means ( DNS RR? HAProxy? ), I tried to use the single server configuration pointing to the DNS of the redis service ( k8s ) and port 26379 (  redis sentinel port ). Unfortunatelly the nextcloud container will not even start like this.

### Steps to reproduce
1. Configure redis to point to redis service on kubernetes and sentinel port
2. start the container
3. it will hang

### Expected behaviour
It should be able to use sentinel to detect who is the master and connect to that master, failing over when needed.

### Actual behaviour
Just hangs

### Server configuration

**Operating system:**
K8s 1.19
**Nextcloud version:** (see Nextcloud admin page)
Docker container 20.0.1 
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh
**Where did you install Nextcloud from:**
Docker

**Comment by kesselb** [comment]
Configuration and Logs are missing => needs info label.
