### ISSUE TITLE
Allow admins to set a maximum storage capacity per group

### ISSUE THREAD

**Issue by GoudronViande24** [nextcloud/server#26932]
Right now on my Nextcloud, I can allow users to be an admin for a group only, this way they can create users and allow them unlimited storage... 

If you can make an additional setting in groups to set a maximum storage capacity for all the users in the group (not per user, the total usage of the group) that would be so much useful ! It could also be added as an app, I don't know what would be the best.

**Comment by szaimen** [comment]
Hi, I think what you are looking for is this:
https://apps.nextcloud.com/apps/groupquota

**Comment by GoudronViande24** [comment]
The problem with this is that there is no admin GUI, so I cannot configure it (host does not allow ssh)
