### ISSUE TITLE
Cannot add user with utf8 username

### ISSUE THREAD

**Issue by robincafolla** [nextcloud/server#26935]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Navigate to settings/users
2. Click `New User`
3. Try to add a user with a utf8 username such as úna

### Expected behaviour
User should be created

### Actual behaviour
A message appears saying "Please match the requested format."

![utf8-username](https://user-images.githubusercontent.com/1263427/117653499-613f2c80-b18c-11eb-9b72-f530919e6912.png)

### Server configuration

**Operating system:** Ubuntu 20.04

**Web server:** Nginx 1.19.8

**Database:** Mysql 8.0.23-0ubuntu0.20.04.1

**PHP version:** 7.4.16

**Nextcloud version:** 21.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/latest.tar.bz2

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - calendar: 2.2.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - groupfolders: 9.0.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - provisioning_api: 1.11.0
  - ransomware_protection: 1.10.0
  - recommendations: 1.0.0
  - richdocuments: 4.0.4
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sociallogin: 4.5.0
  - survey_client: 1.9.0
  - suspicious_login: 4.0.0
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - viewer: 1.5.0
  - workflowengine: 2.3.0
Disabled:
  - contactsinteraction
  - dashboard
  - encryption
  - federation
  - files_external
  - firstrunwizard
  - nextcloud_announcements
  - photos
  - privacy
  - sharebymail
  - support
  - user_ldap
  - user_status
  - weather_status

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "files.local"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.1.1",
        "overwrite.cli.url": "https:\/\/files.local",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "logfile": "nextcloud.log",
        "loglevel": "1",
        "log_type": "file",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": "True",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "skeletondirectory": ""
    }
}
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 88.0

**Operating system:** Ubuntu 20.04

### Logs

Nothing appears in the logs

#### Web server error log

Nothing appears in the logs

#### Nextcloud log (data/nextcloud.log)
Nothing appears in the logs

#### Browser log

Nothing appears in the logs

**Comment by robincafolla** [comment]
The collation on the `oc_users` table is `utf8mb4_bin` so I suspect this is an issue purely in the frontend validation script.

**Comment by szaimen** [comment]
Related https://github.com/nextcloud/server/issues/21313

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/21313
