### ISSUE TITLE
[S3] Empty files produce upload parts without cleanup

### ISSUE THREAD

**Issue by tsdicloud** [nextcloud/server#26960]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Precondtion
Use S3 as your primary NextCloud storage.

### Steps to reproduce
1. Upload an empty file or execute an action like "Create user" that produces empty file on storage.
2. Review list of open uploads or do a call for `S3Client->'

### Expected behaviour
NextCLoud should not produce open uploads (aka fragments), all uploads eventually are either finished or aborted.

### Actual behaviour
Each empty files produces an upload fragment that is never removed.
Too many open upload fragments reduce the number of possible API calls per second dramatically. 

### Server configuration
**Operating system:**
Ubuntu 20.04
**Web server:**
Apache/Nginx (same effect) 
**Database:**
MySQL 8.0.20
**PHP version:**
8.0
**Nextcloud version:** (see Nextcloud admin page)
21.0.1 (fresh and updated)
Enterprise package
** Storage
Amazon S3 ful compatible object store
**Are you using encryption:** yes (SSE KMS bucket key)

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
