### ISSUE TITLE
Mutualize Shared Folder Storage among users

### ISSUE THREAD

**Issue by OrnithOrtion** [nextcloud/server#26968]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

I have an account on a Nextcloud instance and I am limited with 1G of storage, I wanted to create a folder (about 5G of storage) shared with other student in same class.

**Describe the solution you'd like**
I think it could be an interesting feature that shared folder mutualize storage usage among involved users.

**Describe alternatives you've considered**

It could be simpler just to increase the amount of authorized storage for the folder creator, but I cannot do that.

**Comment by kesselb** [comment]
This use case should be covered by https://github.com/nextcloud/groupfolders
