### ISSUE TITLE
Just after Upgrading OnlyOffice to 7.0.0, Server Files Menu structure does change behave

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/server#26976]
### Actual behaviour

just after Upgrading OnlyOffice to 7.0.0, i did realize, that - after a new login there is complete different behave (or malfunction)
on some menue structures like the most important functionalities --> Files (in German: Dateien).

(i did open this case under the Server context, because OnlyOffice has got side effects on the Server core function).

After Upgrading OnlyOffice, you can click on the left side into the files menu structure .. Favorites, Tags, Shares .. 
There is no context change anymore - (between Favorites .. Tag .. Shares & more).

I've checked the OnlyOffice config also (thaught, that might be a new menu option probably .. but did not find such).

### Steps to reproduce

- by disable OnlyOffice per interim will change the behave to "normal"
- by enable OnlyOffice again - you see the same behave as before.

### Expected behaviour

self explaining (--> steps to reproduce)

### --------------------------------

- Windows 10 (newest Build)
- Tried with different Browsers - same behave

### --------------------------------

Version: Intel(R) Xeon(R) E-2136 CPU @ 3.30GHz Max Speed : 4300 MHz Current Speed: 3300 MHz
Memory: 16GB
----------------------------------------------

Operating System: CentOS Linux release 8.3.2011

Upstream OS : Derived from Red Hat Enterprise Linux 8.3

Webserver: Apache/2.4.37 (centos)

Database: mysql 10.3.27-MariaDB,

PHP version: PHP Version => 7.4.16

[PHP Modules] apcu bcmath bz2 calendar Core ctype curl date dom exif fileinfo filter ftp gd gettext gmp hash iconv igbinary imagick intl json ldap libsmbclient libxml mbstring memcached msgpack mysqli mysqlnd openssl pcntl pcre PDO pdo_mysql pdo_sqlite Phar posix readline redis Reflection session shmop SimpleXML smbclient sockets sodium SPL sqlite3 standard sysvmsg sysvsem sysvshm tokenizer xml xmlreader xmlwriter xsl Zend OPcache zip zlib [Zend Modules] Zend OPcache

Nextcloud: - version: 21.0.1.1
### Signing status:

Login as admin user into your Nextcloud and access http://example.com/index.php/settings/integrity/failed
paste the results here.

No errors have been found.

{
    "system": {
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "21.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "auth.bruteforce.protection.enabled": true,
        "check_for_working_htaccess": true,
        "updater.release.channel": "stable",
        "logfile": "\/media\/log\/nextcloud.log",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "session_lifetime": 1200,
        "session_keepalive": false,
        "default_phone_region": "CH",
        "knowledgebaseenabled": false,
        "log_rotate_size": 3145728,
        "mail_sendmailmode": "smtp",
        "app_install_overwrite": [
            "passman",

Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - analytics: 3.4.1
  - announcementcenter: 5.0.0
  - apporder: 0.12.0
  - audioplayer: 3.1.0
  - audioplayer_editor: 0.3.0
  - audioplayer_sonos: 1.2.0
  - bookmarks: 4.2.0
  - breezedark: 21.0.7
  - bruteforcesettings: 2.1.0
  - calendar: 2.2.1
  - circles: 0.21.2
  - cloud_federation_api: 1.4.0
  - cms_pico: 1.0.15
  - comments: 1.11.0
  - contacts: 3.5.1
  - contactsinteraction: 1.2.0
  - cookbook: 0.8.4
  - cospend: 1.3.4
  - dashboard: 7.1.0
  - data_request: 1.8.0
  - dav: 1.17.1
  - deck: 1.4.2
  - dicomviewer: 1.2.2
  - documentserver_community: 0.1.9
  - drawio: 1.0.0
  - drop_account: 1.0.2
  - event_update_notification: 1.2.0
  - extract: 1.3.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_antivirus: 3.2.0
  - files_automatedtagging: 1.11.0
  - files_downloadactivity: 1.10.0
  - files_external: 1.12.0
  - files_external_onedrive: 1.1.0
  - files_markdown: 2.3.3
  - files_mindmap: 0.0.24
  - files_pdfviewer: 2.1.0
  - files_photospheres: 1.21.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - flow_notifications: 1.1.0
  - forms: 2.2.4
  - gpxmotion: 0.1.0
  - gpxpod: 4.2.8
  - groupfolders: 9.0.1
  - impersonate: 1.8.0
  - integration_discourse: 1.0.0
  - integration_dropbox: 1.0.1
  - integration_github: 1.0.0
  - integration_gitlab: 1.0.0
  - integration_google: 1.0.2
  - integration_jira: 1.0.0
  - integration_mastodon: 1.0.0
  - integration_moodle: 1.0.0
  - integration_onedrive: 1.0.1
  - integration_openproject: 1.0.4
  - integration_reddit: 0.0.11
  - integration_suitecrm: 0.0.4
  - integration_twitter: 1.0.0
  - integration_zammad: 1.0.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - maps: 0.1.8
  - nextcloud_announcements: 1.10.0
  - notes: 4.0.4
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - onlyoffice: 7.0.0
  - passman: 2.3.7
  - password_policy: 1.11.0
  - photos: 1.3.0
  - polls: 1.8.3
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - quicknotes: 0.7.1
  - quota_warning: 1.10.0
  - rainloop: 7.1.2
  - ransomware_protection: 1.10.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - social: 0.4.2
  - socialsharing_diaspora: 2.2.0
  - socialsharing_email: 2.2.0
  - socialsharing_facebook: 2.2.0
  - socialsharing_twitter: 2.2.0
  - spreed: 11.2.1
  - support: 1.4.0
  - systemtags: 1.11.0
  - talk_matterbridge: 1.22.2
  - tasks: 0.13.6
  - terms_of_service: 1.7.0
  - text: 3.2.0
  - theming: 1.12.0
  - timemanager: 0.1.8
  - twofactor_backupcodes: 1.10.0
  - twofactor_totp: 6.0.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - video_converter: 1.0.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - welcome: 0.0.5
  - workflow_ocr: 1.21.0
  - workflow_pdf_converter: 1.6.0
  - workflow_script: 1.6.0
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - encryption
  - end_to_end_encryption
  - external
  - files_3d
  - files_accesscontrol
  - files_fulltextsearch
  - flowupload
  - fulltextsearch
  - fulltextsearch_elasticsearch
  - gpxedit
  - health
  - integration_whiteboard
  - issuetemplate
  - joplin
  - ojsxc
  - passwords
  - registration
  - side_menu
  - socialsharing_googleplus
  - survey_client
  - user_ldap
  - weather

**Comment by szaimen** [comment]
Hi, please report this to onlyoffice directly, thanks!
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/new
