### ISSUE TITLE
Files Sharing: Unclear meaning of "Sharing sending the password by Nextcloud Talk failed because Nextcloud Talk is not enabled"

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/server#26973]
Reported at Transifex. See https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/$/149442095?q=issue%3Aopen

The sentence "Sharing sending the password by Nextcloud Talk failed because Nextcloud Talk is not enabled" is not clear.

Does this mean:
Sharing "Sending the password by Nextcloud Talk" failed because Nextcloud Talk is not enabled?

If so an idea is:

"Sending the password by Nextcloud Talk" for sharing an item failed because Nextcloud Talk is not enabled.

Or:

Sharing: "Sending the password by Nextcloud Talk" failed because Nextcloud Talk is not enabled? (including Apostrophes)

NC version 21.0.1

**Comment by szaimen** [comment]
cc @skjnldsv @juliushaertl

**Comment by nickvergessen** [comment]
> "Sending the password by Nextcloud Talk" for sharing an item failed because Nextcloud Talk is not enabled.
