### ISSUE TITLE
Direct access to ical calendar files 

### ISSUE THREAD

**Issue by tamis-laan** [nextcloud/server#26975]
I have nextcloud running on a raspberry pi and synchronize all files with multiple machines using nextcloud desktop. These machines also act as a backup of my data. However let's say my raspberry pi server fails and the data is destroyed, I would have all my data backed up on my other computers, **except for my calendar**. 

_Would it be possible to expose the ical files used by the nextcloud calendar so they are synchronized between devices?_

An added benefit would be that calendar apps work with ical files but don't implement caldav would be able to work with these files. It also allows for custom scripts that read the ical files and perform actions based on calendar events. In case of possible corruption these ical files could be set to read only, or one way synchronization.

**Comment by kesselb** [comment]
Thanks for the idea :+1: 

I see how this feature could be useful for some people.  An automated ical/vcf export is something that should be done as app for Nextcloud. https://help.nextcloud.com/c/apps/app-ideas/21 is a section to suggest app ideas.

**Comment by tamis-laan** [comment]
> Thanks for the idea 
> 
> I see how this feature could be useful for some people. An automated ical/vcf export is something that should be done as app for Nextcloud. https://help.nextcloud.com/c/apps/app-ideas/21 is a section to suggest app ideas.

I was thinking more in line of exposing the ical files to the file system, i.e. `Nextcloud/.calendar/` instead of a automated ical export.
