### ISSUE TITLE
when canceling upload of a file it still shows as it's uploading  

### ISSUE THREAD

**Issue by bruhdev1290** [nextcloud/server#26979]
steps to reproduce

upload the file to your nextcloud server 

then click the x it will show a message that your upload was canceled but it's still showing its uploading via the progress bar

 https://cloud.woelkli.com/s/f4SGTjf95QHB43F the file is in the link and the password to access the file is b`j7B>]Wpj;=W8pA

**Comment by bruhdev1290** [comment]
Expected behavior

it should show its uploading when the upload is canceled 

actual results 

it shows its uploading when canceled

**Comment by kesselb** [comment]
Same as https://github.com/nextcloud/server/issues/11812
