### ISSUE TITLE
ft: recursive merge when copy/move files (in)to existing directory

### ISSUE THREAD

**Issue by azrdev** [nextcloud/server#26986]
In the files app (web GUI) moving a directory A to a target where there already exists an A results in an error that it already exists. Instead, it would be useful to move all the files in A into target/A/ recursively, merging the two directories.

E.g. this structure
* Adir
  * a_file
* target
  * Adir
    * b_file

should result (when moving Adir to target) in
* target
  * Adir
    * a_file
    * b_file

### alternatives
Local file managers usually can do recursive merges ("paste into"), and I believe the sync client recognizes file moves thus transferring only metadata, making it a feasible operation to perform locally, but having an option in the web gui (in my case: because I have not synced the folder (yet)) would be great.

I'm currently on Nextcloud 20.0.7

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by szaimen** [comment]
cc @nextcloud/server is this feasible?

**Comment by azrdev** [comment]
Well, this is still relevant, at least to me.
