### ISSUE TITLE
Update External Storage to always check for changes 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#26983]
Currently there are two option either check for changes once every direct access or never. I don't know how other people feel about this but it would be nice to have the server always check for changes.

**Comment by q-wertz** [comment]
Kind of "related" https://github.com/nextcloud/server/issues/23988

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by andyxheli** [comment]
@szaimen Thank you for your feedback. Not something I use just though it would be a good idea.
