### ISSUE TITLE
Hacked NextCloud Account via Android App [?]

### ISSUE THREAD

**Issue by Christopher10024** [nextcloud/server#26988]
Because I believe the vulnerability *may* be the Android app, I am posting this. [Disclaimer: I'm a newbie on GitHub. Please excuse any possible errors in posting.]

I've seen possibility of using app verification codes, etc., but have not been able to use/set them up—not sure how to do so properly.

Any advice on how to increase the security of one's NextCloud account security (and the NC app), will be greatly appreciated. 

Details are listed below.

Thanks to any/all (in advance) who care to chime in.

Christopher

---

**Steps to Reproduce:**

1. Was setting up shared files. 
2. Shared folders were connected with another connected NextCloud account (both which I had set up). Separate shared files were set up on both NextCloud accounts, with the hope of exchanging files, back and forth, easily.
3. Some individual shared folders were only shared links (for sending to friends by email).

**Expected Behavior:**

Ability to share files on NextCloud account privately, both between two NC accounts, and via links; while maintaining account control, all via Android **app**.

**Actual Behavior:**

Account suddenly changed over to an another unknown account, with partial access to that stranger's account.

**Actions Attempted to Recover My NC Account:**

• Used NextCloud Android app to attempt to change account info (and possibly password), and regain control.
• Made two attempts to gain control, each time my account *automatically* switched over to the other invading account. Same thing happened on the Web, on laptop (no app).
• Third attempt was via password recovery, via email, apparently worked. Control was regained. 

**NOTE:** On (apparently successful) third attempt, use of the Android app was avoided using. [Subsequently, I deleted the NextCloud Android app.] PW recovery via email was carried out on a laptop running Windows 10, using a secure email service.

**Error Message/Info:**

***

OCA\DAV\Connector\Sabre\Exception\FileLocked "littlewalter.juke@slmail.me/files/Documents/Backup/Secure.upload.part" is locked, existing lock on file: exclusive

This XML file does not appear to have any style information associated with it. The document tree is shown below.

<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">

<s:exception>OCA\DAV\Connector\Sabre\Exception\FileLocked</s:exception>

<s:message>"littlewalter.juke@slmail.me/files/Documents/Backup/Secure.upload.part" is locked, existing lock on file: exclusive</s:message>

...

</d:error>

***

**NOTE:** The email address found in the above listed error message is an alias, procured through - SimpleLogin.io. And must be linked Sabre.io WebDav.

Apparently the holder of that account actually uses the account, as there is an address book saved on the account. It's possible that account was also compromised, and used as a go-between, but I speculate.

**Device Info:**

Samsung Galaxy Tablet 2019 - SM-T290 [Up-to-Date]
Running Android Version 10 (2021)
Borwsers Used: Opera and Tor (Latest versions as of May 14, 2021).

**Android App Info:**

Version 3.16.0
Updated May 5, 2021
Via Google Paystore

**NextCloud Server Info:**

nl.Tab.Digital

**Configuration and Storage:**

Using only online storage. No connected offline storage.

**Activated Apps:**

As far as known, only the Android NextCloud app was active.

**NextCloud Configuration:**

• Only password protected, as administrator of account.
• Was not able to apply more/increased security settings in/for app.
• Need to increase security on these settings, 
• Need more info on how to do so.

--

I look forward to learning more from the GitHub/NextCloud community.

Thanks.

**Comment by Spartachetto** [comment]
@LukasReschke , maybe...

**Comment by szaimen** [comment]
Hm, this looks like https://help.nextcloud.com/t/security-issue-user-account-switching/116165
It seems like tab.digital has had a pretty bad security breach most likely because of misconfigurations on their side.

**Comment by acsfer** [comment]
This seems most likely a (very) bad configuration issue (like caches) at tab.digital.
Just like if they were caching requests at some kind of reverse proxy and random users pick the cached keys...

Advice: switch you provider.

**Comment by acsfer** [comment]
Closing this, please continue the discussion at https://help.nextcloud.com/t/security-issue-user-account-switching/116165/13

**Comment by Christopher10024** [comment]
THANKS for your comments! I appreciate it. I think I will take your advice, Acsfer, and look around for another provider. Too bad. Perhaps 8 Gbs (free) was too good to be true (and secure)?
