### ISSUE TITLE
Add message to login screen to inform user about something

### ISSUE THREAD

**Issue by leon47331** [nextcloud/server#26996]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested in the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status changes and new comments. 

**Is your feature request related to a problem? Please describe.**
No, my feature request is not related to a problem.

**Describe the solution you'd like**
It would be a nice feature if the admin could create a message which pops up on the login screen to inform users about something. Some things to inform users could be upcoming maintenance or to inform that the server is going down for a couple of hours, days...

**Additional context**
I have created an example picture

![Nextcloud_Information_Idea](https://user-images.githubusercontent.com/48152632/118410942-59065600-b692-11eb-9d43-a06c033d87a1.png)

**Comment by kesselb** [comment]
https://apps.nextcloud.com/apps/login_notes

**Comment by leon47331** [comment]
Oh thank you. Didn't know that.
Then I wouldn’t have had to do the work to edit the screenshot. 😂

Have a nice evening! :)
