### ISSUE TITLE
Add time/date format overrides in user's profile

### ISSUE THREAD

**Issue by stavros-k** [nextcloud/server#26995]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

I've always used 24h format in any system/device I used/use. PM/AM (or ΠΜ/ΜΜ for Greek) is not intuitive at all.

**Describe the solution you'd like**
I'd like to be able to override user's profile locale to custom settings instead of having to find a locale that might be close to what i want to use.
* Override time format 12h/24h =>e.g. Use Greek locale but with time in 24h format
* Override time and date separators => Use Greek locale but with date format `dd-mm-yyyy` and time format `HH.mm.ss`
* Override week start day => Use Greek locale but week start day is `Sunday`

**Describe alternatives you've considered**
Search and find a locale that comes close to the format I like / is intuitive to me. But that means it might affect other things later, For example if an app uses the locale to determine the currency, it will cause it to display a wrong currency.

**Additional context**
I hope this is not duplicate, looked in issues but couldn't find something relevant.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by voidzero** [comment]
Every so often this annoyance pops up. I usually use the calendar app on my phone, but when I use the Nextcloud app and come across this date formatting... it's pretty nice to have the Lord's intended formatting 😜 yyyy-mm-dd even though Dutch locale is dd-mm-yyyy and American is, for whatever reason, mm/dd/yyyy...
