### ISSUE TITLE
apporder is not respected directly on activating app, only on refresh

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#2699]
When activating a few apps they are just appended in the navigation:
![capture du 2016-12-15 16-14-44](https://cloud.githubusercontent.com/assets/925062/21229392/b9d4067a-c2e1-11e6-9371-c2826419c116.png)

Only after a refresh they are correctly sorted according to the apporder:
![capture du 2016-12-15 16-15-00](https://cloud.githubusercontent.com/assets/925062/21229391/b9c9fc20-c2e1-11e6-932d-8cad5183077d.png)

cc @nextcloud/javascript

**Comment by MorrisJobke** [comment]
With the reworked app menu this problem is not the case anymore - thanks to @juliushaertl 🚀 

The apps are sorted in in the correct order.
