### ISSUE TITLE
Replace PlaceholderAvatar with NotFoundException in /lib/private/Avatar/AvatarManager.php

### ISSUE THREAD

**Issue by fabiiretro** [nextcloud/server#27004]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When a user sets their profile picture scope to private and someone tries to access their profile picture via a direct link, NC currently generates a placeholder picture with the displayname. However, this behavior makes it to possible to find existing usernames.

**Describe the solution you'd like**
Replacing L142 in [/lib/private/Avatar/AvatarManager.php](https://github.com/nextcloud/server/blob/master/lib/private/Avatar/AvatarManager.php#L142) `return new PlaceholderAvatar($folder, $user, $this->logger);` with `throw new \Exception('user does not exist');` (or any other exception, really) makes it impossible to differentiate between non-existing and private users. This would also make Nextcloud more secure as it would be more difficult to check for existing users to attack.

**Describe alternatives you've considered**
I tried blocking external (and direct to /avatar/username) access via the nginx config but quickly failed with this approach.

**Additional context**

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

**Comment by fabiiretro** [comment]
Well, this line still exists as-is (though in L148 now) and the discussion I hoped to see didn't occur at all. So it can be closed, I guess.
