### ISSUE TITLE
Inheritance of rights

### ISSUE THREAD

**Issue by coinfastman** [nextcloud/server#27005]
Hi guys.
We are interested in inheritance of access rights. Do we understand correctly that it works from the root? All rights are inherited from the root.
We need to implement such a scheme. This can be done in nextcloud.

![sheme](https://user-images.githubusercontent.com/33808421/118544655-4a857080-b75e-11eb-951a-6a7481eddd8a.png)

In general, the scheme is not complicated and straightforward.
We have an administrator who created the folder structure as shown in the diagram.
There are 3 groups which include one user. One group that includes all users.
According to the scheme, all users have read-only rights to the root directory.
Further, if we delve deeper into the tree, we see three directories, each group has access to its own directory with read and write rights, but other users only read.
Unfortunately, when testing such a scheme, we came across that the rights inherited from the root are transferred to other levels regardless if we even assign new rights inside the root directory.
Can this be bypassed or implemented with additional modules ?!
In part, we understand that no, but it's better to ask)))))
Thank you

**Comment by kesselb** [comment]
Hi, https://help.nextcloud.com for support.
