### ISSUE TITLE
cannot open user settings when using external smb storage

### ISSUE THREAD

**Issue by Robert-Schulz** [nextcloud/server#27009]
i authenticate to an AD using ldap and my files are located on a dfs namespace. to access them i want to use the external storage plugin with smb, so i mount it to the nextcloud root folder. normal file access and most setting pages work perfectly, but when i try to edit the user information, the usual error page appears. the relevant error in the log is:
`"NT_STATUS_OBJECT_NAME_NOT_FOUND","Robert/Reasons to use Nextcloud.pdf"`
the problem can be resolved by creating the corresponding file in the root of the mounted folder. this error also doesn't appear when i mount the shared folder to a linux folder using mount.cifs and passing it to nextcloud with the local storage option. 
the name of the user folder in the /data dir is named like the UUID of the user on Active directory, however neither adding the file there nor in a new folder with the username resolved the problem. 
this error does not occur when i mount the smb folder to a different folder than '/'

**Comment by kesselb** [comment]
https://help.nextcloud.com for support.
