### ISSUE TITLE
Apps management is slow or doesn’t load when internet connection is slow/offline

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#2701]
This makes local development especially painful and sometimes impossible when you are offline and need to enable an app.

Instead, all local things should directly load, and the appstore connection be done in the background. cc @LukasReschke @nextcloud/appstore

**Comment by BernhardPosselt** [comment]
Nothing related to the store. We already serve everything in a way that it can be very easily cached. It's just 4 Json files AFAIK which contain everything

**Comment by jancborchardt** [comment]
Yup, just cc’d you for reference :)

**Comment by nickvergessen** [comment]
@LukasReschke time to bring back the async "fetch update info" again?

**Comment by LukasReschke** [comment]
> @LukasReschke time to bring back the async "fetch update info" again?

Mhm. I think we can work around that other ways, let me see. :)

**Comment by ChristophWurst** [comment]
> Mhm. I think we can work around that other ways, let me see. :)

So. What's the status here? :)

**Comment by MorrisJobke** [comment]
> So. What's the status here? :)

Nothing for 12. Plan would be to cache the app store results and also lazy load them to not cause problems when accessing the apps management.

**Comment by nickvergessen** [comment]
> Plan would be to cache the app store results

we do that, iirc? But doesn't help on first load...

**Comment by skjnldsv** [comment]
Is this still relevant? I think I remember seeing a patch being merge which was doing the requests in background?

**Comment by MorrisJobke** [comment]
Yes - we improved this one -> closing. If there are still some issues in special cases we should look into this in separate tickets. Also the App Store stuff is cached now ;)
