### ISSUE TITLE
Groupadmin - rights for group(s)

### ISSUE THREAD

**Issue by jasond2020** [nextcloud/server#27026]
It would be nice if the admin could assign "groupadmin" not only to sinlge users but also to whole groups. This way it would be possible to have a "team" with changing user accounts but always with the assigned "groupadmin" rights for self-administration without "bothering" the technical backend-admin...

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
