### ISSUE TITLE
Big file download fails when on external storage (Samba)

### ISSUE THREAD

**Issue by jasmines** [nextcloud/server#27020]
It seems this bug has been reported in the community, but I think it hasn't received enough attention from official channels.
The issue occurs on a Nextcloud 20.0.9 (stable) installation on Ubuntu 18.04: when trying to download a big file (we're talking of  300-700Mb, so it's not related to 1Gb limit I read somewhere) that is hosted on an external storage mounted via samba, the download starts, then stops after a few seconds and restarts... This happens 3-4 times until the browser stops retrying and considers the download as failed.
Anyway, it's possible to resume the failed download many times, until it completes, but you must agree this can't be a workaround.

**Comment by Kaesewuerfel** [comment]
noice

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)
