### ISSUE TITLE
Resource exhaustion uploading files to large directories

### ISSUE THREAD

**Issue by Maffsie** [nextcloud/server#27033]
It appears this is an issue with the Web UI attempting to generate previews/thumbnails for all images/files in a directory, which causes a DoS when there are many thousands of images in the directory. Notes and logs below.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Drag and drop an image into the Web UI file browser when navigated into a directory with several thousand images in it
2. Observe the NextCloud and database server logs
3. Notice that the database server and NextCloud server logs both report that all available connections are exhausted constantly
4. Check Task Manager or equivalent and observe that the Web UI has caused large amounts of local resources to be used

### Expected behaviour
Uploading a file should not DoS the server

### Actual behaviour
Uploading a file DoSes the server

### Server configuration

**Operating system:**
Docker (latest), nextcloud:21 image

**Web server:**
Traefik 1.8

**Database:**
Docker (latest), postgres:alpine image

**PHP version:**
Whichever is shipped with the official nextcloud:21 image

**Nextcloud version:** (see Nextcloud admin page)
21.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 20.0.9

**Where did you install Nextcloud from:**
Docker (official image)

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
./occ app:list
 Enabled:
  - accessibility: 1.7.0
  - admin_audit: 1.11.0
  - cloud_federation_api: 1.4.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_rightclick: 1.0.0
  - group_everyone: 0.1.7
  - integration_mastodon: 1.0.0
  - integration_twitter: 1.0.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_u2f: 6.1.0
  - user_saml: 4.1.1
  - viewer: 1.5.0
  - webapppassword: 21.3.0
  - workflowengine: 2.3.0
Disabled:
  - activity
  - bookmarks
  - bruteforcesettings
  - checksum
  - comments
  - contactsinteraction
  - deck
  - encryption
  - extract
  - federation
  - files_accesscontrol
  - files_downloadactivity
  - files_external
  - files_markdown
  - files_pdfviewer
  - files_sharing
  - files_texteditor
  - files_trashbin
  - files_versions
  - files_videoplayer
  - firstrunwizard
  - flow_notifications
  - forms
  - groupfolders
  - groupquota
  - integration_github
  - metadata
  - nextcloud_announcements
  - notes
  - password_policy
  - quota_warning
  - ransomware_protection
  - recommendations
  - sharebymail
  - side_menu
  - support
  - survey_client
  - systemtags
  - text
  - updatenotification
  - user_ldap
  - user_status
  - weather_status
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "trusted_domains": [
            "lotus.pup.cloud"
        ],
        "debug": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "21.0.1.1",
        "overwrite.cli.url": "https:\/\/lotus.pup.cloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "loglevel": 2,
        "encryption.key_storage_migrated": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no (decrypted and disabled during troubleshooting)

**Are you using an external user-backend, if yes which one:** SAML

### Client configuration
**Browser:**
Safari

**Operating system:**
iPadOS 14.5

#### Web server error log
<details>
<summary>Web server error log</summary>

```
There are too many errors for me to find the actual start of the issue; will update issue with more logs once at a computer
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
As above, will update shortly
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
As above, will update shortly
```
</details>

**Comment by kesselb** [comment]
Sounds like https://github.com/nextcloud/server/issues/21430

**Comment by Maffsie** [comment]
It seems very similar, however I wasn't sure, as this issue didn't happen in 20.0.9, it only began happening after upgrading to NC21 (maybe the previews in question existed before, and the upgrade invalidated them somehow?). I'm currently filtering out identifying information from my logs and will attach them shortly
