### ISSUE TITLE
Misleading message under users account tab

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#27047]
I think if there users this message should not state no users in here. 
![image](https://user-images.githubusercontent.com/59488153/119039774-3cac3700-b97a-11eb-8e65-c5a1b2451e69.png)

**Comment by PanCakeConnaisseur** [comment]
What is the source of the users? An external user backend? if yes, what kind of?

**Comment by andyxheli** [comment]
> What is the source of the users? An external user backend? If yes, what kind of?

Internal database MariaDB

**Comment by szaimen** [comment]
Duplicate of https://github.com/nextcloud/server/issues/25133
