### ISSUE TITLE
Accessing SMB Share on Web-GUI is not Possible but it works with Android Client

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#27044]
### Steps to reproduce

With a Web Browser of your Choice:
1. You need a Fritzbox with an SMB Share or another SMB Share where you have a hidden file in Root Directory which is not deletable "here .start_indexation".
2. Login to your Nextcloud Website
3. Open your SMB Folder "here FritzBox", When you are in the Root Directory of your SMB Share open a Random Folder "here Bilder"
5. Nextcloud Web-GUI Crashes and goes back to the Overview and shows an Error "Storage Temporaly not available"

With the Android App
6. Open Your Nextcloud Android Client and Open your SMB Folder "here FritzBox", When you are in the Root Directory of your SMB Share open a Random Folder "here Bilder"
7. you can actually access your SMB Share without getting an Error Message on the Android App or the Server Error Logs.

### Expected behaviour
Opening an SMB Share with an Hidden File in The Root Directory Should work on Both ways. Web-Gui and Android App.

### Actual behaviour
Web-GUI Crashes and Android Client Works for this SMB Share.

### Server configuration

**Operating system:**
Ubuntu 21.04

**Web server:**
Nginx 1.18

**Database:**
PostgreSQL 13.2

**PHP version:**
7.4.16

**Nextcloud version:** (see Nextcloud admin page)
21.0.2

**Are you using external storage, if yes which one:** local/smb/sftp/...
SMB only

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### Nextcloud log (data/nextcloud.log)
<details>

OCP\Files\StorageAuthException: Storage unauthorized. /.start_indexation.mp3
Icewind\SMB\Exception\AccessDeniedException: /.start_indexation.mp3
Sabre\DAV\Exception\ServiceUnavailable: Storage with mount id 9 is not available
OCP\Files\StorageAuthException: Storage unauthorized. /.start_indexation.mp3
Icewind\SMB\Exception\AccessDeniedException: /.start_indexation.mp3

</details>

**Comment by NA1144** [comment]
**Update here are the Screenshots**

> Here a Windows Folder Overview

![1](https://user-images.githubusercontent.com/69590277/119721409-6cbc7400-be6b-11eb-9e3f-9216efac1749.png)

>How I mounted the SMB Share in Nextcloud

![2](https://user-images.githubusercontent.com/69590277/119721414-6d550a80-be6b-11eb-8768-a16e5e6624a8.png)

>the Root Directory of the SMB Share

![3](https://user-images.githubusercontent.com/69590277/119721418-6d550a80-be6b-11eb-9081-9e0ad3bfbbcc.png)

>when you try to Open a Folder Like "Bilder" then you get these Errors

![4](https://user-images.githubusercontent.com/69590277/119721420-6deda100-be6b-11eb-902a-f5764f593ba8.png)

>The Error Log after accessing the SMB Share via Web-GUI

![5](https://user-images.githubusercontent.com/69590277/119721422-6deda100-be6b-11eb-8530-99aea1ea2b77.png)

>Retry this with the Nextcloud Android App

![6](https://user-images.githubusercontent.com/69590277/119721423-6deda100-be6b-11eb-97b6-e02cc2993a22.jpg)

>As you can See it works without Errors

![7](https://user-images.githubusercontent.com/69590277/119721425-6e863780-be6b-11eb-84cc-23d6abaf4187.jpg)

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

**Comment by NA1144** [comment]
Is still valid even with a test Installation of NC22 it doesn't work as it should.
________________________________

**Comment by szaimen** [comment]
cc @icewind1991

**Comment by NA1144** [comment]
With Update NC22.1.0 still valid
________________________________

**Comment by marcelfischer** [comment]
Having the same issue still with NC23

**Comment by PeggyFree** [comment]
I have exactly thé opposite behaviour with my up to date stable NC23. Web UI ok, Android NOK

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by PeggyFree** [comment]
Hello, sorry for the late reply. I upgraded nextcloud to the latest V25 mid february and the problem persists. I deleted then recreated the SMB shares with no success.

To be more precise, I have two SMB shares, located on the same host. I declared both in nextcloud. The first one is readable on both web and android, the second one only on the web. This behaviour is identical in V23 and V25.

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/37059 then
