### ISSUE TITLE
Double Clicking Photos Breaks Viewer

### ISSUE THREAD

**Issue by djohnson1865** [nextcloud/server#27049]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Open up Nextcloud UI
2. Double click an image file in the UI
3. Try to exit the image viewer

### Expected behaviour
The image viewer should exit back to the file viewer

### Actual behaviour
The image disappears, but the image viewer widget becomes stuck and the page must be reloaded to remove it

### Server configuration
Tested on two different instances, same behavior. One in a docker container, one a manual install on CentOS 8. The details below are regarding the CentOS 8 install.

**Operating system:**

CentOS Linux release 8.3.2011
(also occurs on the current Nextcloud Docker container)

**Web server:**
nginx/1.14.1

**Database:**
mysql 15.1 (Mariadb 10.3.28)

**PHP version:**
7.3.28

**Nextcloud version:** (see Nextcloud admin page)
20.0.9 (21.0.1 in docker container)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
Manual install from site

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - analytics: 3.4.1
  - bruteforcesettings: 2.1.0
  - calendar: 2.2.1
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dav: 1.16.2
  - deck: 1.2.7
  - documentserver_community: 0.1.9
  - drawio: 1.0.0
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_accesscontrol: 1.10.2
  - files_external: 1.11.1
  - files_fulltextsearch: 20.0.2
  - files_markdown: 2.3.3
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - forms: 2.2.4
  - groupfolders: 8.2.1
  - impersonate: 1.7.0
  - integration_openproject: 1.0.4
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.3.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.7
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - unsplash: 1.2.2
  - updatenotification: 1.10.0
  - user_ldap: 1.10.2
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - dashboard
  - encryption
  - nextcloud_announcements
  - recommendations
  - richdocuments

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "metrocloud.metrolist.net",
            "onlyoffice.metrolist.net"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR",
            "X-Forwarded-For"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.9.1",
        "overwrite.cli.url": "https:\/\/metrocloud.metrolist.net",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "theme": "",
        "loglevel": 2,
        "skeletondirectory": "\/var\/www\/html\/nextcloud\/core\/skeleton.custom",
        "app_install_overwrite": [
            "ojsxc"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:** Yes, SMB, but not for viewing the files in question. Those are local storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory

</details>

### Client configuration
**Browser:**
Firefox, Chrome, Safari

**Operating system:**
Windows 10, Fedora 34, macOS 10.14.6 

I can provide logs if needed, but the error seems fairly easy to reproduce across a number of installs and clients.

**Comment by kesselb** [comment]
https://github.com/nextcloud/viewer/issues/893
