### ISSUE TITLE
Add mounted NTFS drive folder as local storage

### ISSUE THREAD

**Issue by obriankevin11** [nextcloud/server#27073]
Hi,

[Documentation](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/external_storage/local.html)  doesn't say anything about using ntfs partition directory as local storage.

I have a 4TB drive initially used with Windows. 
I mounted its partition on my raspi and followed the doc. Although I still get the red icon...
![Screenshot_20210522_122629_com android chrome](https://user-images.githubusercontent.com/44847483/119221711-38f2ee80-baf9-11eb-9b98-9d45a37a151b.jpg)

Is that even possible? is the ext4 partition type a requirement?

thank you

**Comment by szaimen** [comment]
Hello, yes it is possible. But since this request is a support question, please ask it at https://help.nextcloud.com
Thanks!
