### ISSUE TITLE
Apps can't/aren't removed by `occ` if `appstoreenabled => false`

### ISSUE THREAD

**Issue by acsfer** [nextcloud/server#27074]
1. Set `'appstoreenabled' => false,`
2. issue `app:remove <appname>`
3. It outputs it is removed, but it is not, and command can be run on a loop, ex.:

```
$ php occ app:remove ransomware_protection
ransomware_protection disabled
ransomware_protection 1.10.1 removed

$ php occ app:remove ransomware_protection
ransomware_protection disabled
ransomware_protection 1.10.1 removed

$ php occ app:remove ransomware_protection
ransomware_protection disabled
ransomware_protection 1.10.1 removed
...
```

4. Set `'appstoreenabled' => true,`
5. issue `app:remove <appname>`
6. App is removed

```
$ php occ app:remove ransomware_protection
ransomware_protection disabled
ransomware_protection 0 removed

$ php occ app:remove ransomware_protection
ransomware_protection is not installed
```

While this is the right behaviour to install apps, it should be allowed to remove them even if `'appstoreenabled' => false,`

**Comment by gary-kim** [comment]
This may be the issue. Removing an app relies on `OC_App::getInstallPath()` which returns false if `'appstoreenabled' => false`.

https://github.com/nextcloud/server/blob/56ae87c281d2f54b23f98acf0e138d8e72196a06/lib/private/Installer.php#L513

https://github.com/nextcloud/server/blob/784b059a0132e0e8685a9993bd74d570a5b75ec6/lib/private/legacy/OC_App.php#L462-L475

**Comment by gary-kim** [comment]
I'm working on it :)
