### ISSUE TITLE
Bug when scrolling down on big users list

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#27076]
This is produced after had scroll down 2=3 hundreds of users of an LDAP server.
Can reproduce it in 2 different instances/servers (NC18 and NC 21).

Nothing in the logs or browser console.

See this screenshot (NC18):
![image](https://user-images.githubusercontent.com/12234510/119226722-e3bfd880-bb0a-11eb-81c5-dacb3ded9bdb.png)

Second server (NC21.0.2):
![image](https://user-images.githubusercontent.com/12234510/119226882-9b54ea80-bb0b-11eb-86f9-987b47e6b2e5.png)

cc @nextcloud/designers

**Comment by szaimen** [comment]
I suppose this is still valid on NC21.0.3?

**Comment by acsfer** [comment]
Yes.

**Comment by solracsf** [comment]
Can't reproduce on 24.0.9
