### ISSUE TITLE
Error with PDF

### ISSUE THREAD

**Issue by Jojo-Burger** [nextcloud/server#27071]
Nextcloud version: 21.0.2 RC1
Operating system and version : Ubuntu 8.4.0 for Raspberry PI 4
Apache or nginx version (eg, Apache 2.4.25): NGINX
PHP version: 7.4

When I look at a PDF from the NextCloud WEB interface I get an error: for the PDF I get this error no matter which file
[
![image](https://user-images.githubusercontent.com/38187648/119199666-c39d0480-ba8b-11eb-8767-bf1c15c8bd0c.png)
](url)

I also have another problem on the dashboard the hello (user) stays all day long while before it showed Good night...

**Comment by kesselb** [comment]
Sounds like https://github.com/nextcloud/files_pdfviewer/issues/254 / https://github.com/nextcloud/files_pdfviewer/issues/381
