### ISSUE TITLE
[Security] Increase backup code entropy, which is currently too low

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/server#2708]
Nextcloud 11.0.0

I noticed that the backup code have only 10 characters or digits, this makes entropy = 
log((10+26)^10)/log(2) = about 51 bit.

For secure clouds, and the cloud admin account is a specific target, at least 80 bits are required.

Please increase the length of backup codes to at least, better more than, 16 characters, this is also what Mediawiki uses.

**Comment by nickvergessen** [comment]
@ChristophWurst @LukasReschke I guess it can easily be adjusted, any veto on this?
