### ISSUE TITLE
Unable open PDF file by buildin PDF viewer in version 21.0.2

### ISSUE THREAD

**Issue by aleskomarek** [nextcloud/server#27084]
Hello.
There is problem open PDF file by buildin PDF viewer in new version 21.0.2 with error:

Missing PDF file:
PDF.js v2.5.207 (sestavení: 0974d6052)
Zpráva: Missing PDF "https://SERVERNAME/remote.php/dav/files/PDF_FILE_NAME.pdf".

Trouble is in own files and also in shared folders/files.
If I disable feature of buildin PDF viewer downloading a vieweing of downloaded file is ok.

Thank You for help.
Regards, Komarek.

**Comment by aleskomarek** [comment]
Issue is duplicit.

**Comment by markuman** [comment]
https://github.com/nextcloud/server/issues/27120
