### ISSUE TITLE
Update to next cloud 21.0.2 has get an error

### ISSUE THREAD

**Issue by tardar** [nextcloud/server#27085]
### Steps to reproduce
1. Start Updater
2. Run the updater
3. Error on step9

### Expected behaviour
I'd expected a working upgrade to 21.0.2, but through this error this hasn't happened.

### Actual behaviour
I got this error:
`Doctrine\DBAL\Exception\DriverException: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 4047 InnoDB refuses to write tables with ROW_FORMAT=COMPRESSED or KEY_BLOCK_SIZE.`

more detailed:
`Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturschritt: Repair MySQL collation
Reparaturinformation: All tables already have the correct collation -> nothing to do
Reparaturschritt: Repair SQLite autoincrement
Reparaturschritt: Copy data from accounts table when migrating from ownCloud
Reparaturschritt: Drop account terms table when migrating from ownCloud
Das Datenbankschema wird aktualisiert
Datenbank aktualisiert
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 4047 InnoDB refuses to write tables with ROW_FORMAT=COMPRESSED or KEY_BLOCK_SIZE.
Das Update ist fehlgeschlagen. Bitte melden Sie dieses Problem an die Nextcloud Community.`

If I try to start the upgrade on the terminal, I get this error:
`Doctrine\DBAL\Exception\DriverException: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 4047 InnoDB refuses to write tables with ROW_FORMAT=COMPRESSED or KEY_BLOCK_SIZE.
Update failed`

### Server configuration

**Operating system:** Debian 10

**Web server:** Apache2

**Database:** mariaDB 10.6.1

**PHP version:** 8.0

**Nextcloud version:** updated from 21.0.2 R2 to 21.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from RC to final version

**Where did you install Nextcloud from:**I installed with downloaded package from the next cloud servers

**List of activated apps:**
<details>
<summary>App list</summary>
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - bruteforcesettings: 2.1.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 3.5.1
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - support: 1.4.0
  - survey_client: 1.9.0
  - tasks: 0.13.6
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - whiteboard: 0.0.3
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - firstrunwizard
  - nextcloud_announcements
  - notifications
  - systemtags
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.*.*",
            "*.*.*.*",
            "*.*.*.*"
        ],
        "debug": true,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.2.0",
        "overwrite.cli.url": "https:\/\/*.*.*",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": true,
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "whiteboard"
        ],
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "default_phone_region": "DE",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Safari 14.1

**Operating system:** macOS 11.3.1

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"avpk6SzliVS6VrbPYk3a","level":1,"time":"2021-05-24T09:05:49+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::dbUpgrade: Updated database","userAgent":"--","version":"21.0.2.0"}
{"reqId":"avpk6SzliVS6VrbPYk3a","level":3,"time":"2021-05-24T09:05:49+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing a query: SQLSTATE[HY000]: General error: 4047 InnoDB refuses to write tables with ROW_FORMAT=COMPRESSED or KEY_BLOCK_SIZE.","Code":4047,"Trace":[{"file":"/var/www/clients/***/***/***/cloud/3rdparty/doctrine/dbal/src/Connection.php","line":1728,"function":"convert","class":"Doctrine\\DBAL\\Driver\\API\\MySQL\\ExceptionConverter","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/3rdparty/doctrine/dbal/src/Connection.php","line":1667,"function":"handleDriverException","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/3rdparty/doctrine/dbal/src/Connection.php","line":1146,"function":"convertExceptionDuringQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/DB/Connection.php","line":257,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":213,"function":"executeStatement","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/AppConfig.php","line":236,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/App/AppManager.php","line":407,"function":"setValue","class":"OC\\AppConfig","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/Updater.php","line":375,"function":"disableApp","class":"OC\\App\\AppManager","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/Updater.php","line":259,"function":"checkAppsRequirements","class":"OC\\Updater","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/Updater.php","line":132,"function":"doUpgrade","class":"OC\\Updater","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/core/Command/Upgrade.php","line":255,"function":"upgrade","class":"OC\\Updater","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/3rdparty/symfony/console/Command/Command.php","line":255,"function":"execute","class":"OC\\Core\\Command\\Upgrade","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/3rdparty/symfony/console/Application.php","line":1009,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/3rdparty/symfony/console/Application.php","line":273,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/3rdparty/symfony/console/Application.php","line":149,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/Console/Application.php","line":215,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/console.php","line":100,"function":"run","class":"OC\\Console\\Application","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/occ","line":11,"args":["/var/www/clients/***/***/***/cloud/console.php"],"function":"require_once"}],"File":"/var/www/clients/***/***/***/cloud/3rdparty/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php","Line":114,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDO\\Exception","Message":"SQLSTATE[HY000]: General error: 4047 InnoDB refuses to write tables with ROW_FORMAT=COMPRESSED or KEY_BLOCK_SIZE.","Code":4047,"Trace":[{"file":"/var/www/clients/***/***/***/cloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":84,"function":"new","class":"Doctrine\\DBAL\\Driver\\PDO\\Exception","type":"::"},{"file":"/var/www/clients/***/***/***/cloud/3rdparty/doctrine/dbal/src/Connection.php","line":1136,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/DB/Connection.php","line":257,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":213,"function":"executeStatement","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/AppConfig.php","line":236,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/App/AppManager.php","line":407,"function":"setValue","class":"OC\\AppConfig","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/Updater.php","line":375,"function":"disableApp","class":"OC\\App\\AppManager","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/Updater.php","line":259,"function":"checkAppsRequirements","class":"OC\\Updater","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/Updater.php","line":132,"function":"doUpgrade","class":"OC\\Updater","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/core/Command/Upgrade.php","line":255,"function":"upgrade","class":"OC\\Updater","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/3rdparty/symfony/console/Command/Command.php","line":255,"function":"execute","class":"OC\\Core\\Command\\Upgrade","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/3rdparty/symfony/console/Application.php","line":1009,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/3rdparty/symfony/console/Application.php","line":273,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/3rdparty/symfony/console/Application.php","line":149,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/Console/Application.php","line":215,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/console.php","line":100,"function":"run","class":"OC\\Console\\Application","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/occ","line":11,"args":["/var/www/clients/***/***/***/cloud/console.php"],"function":"require_once"}],"File":"/var/www/clients/***/***/***/cloud/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php","Line":26,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[HY000]: General error: 4047 InnoDB refuses to write tables with ROW_FORMAT=COMPRESSED or KEY_BLOCK_SIZE.","Code":"HY000","Trace":[{"file":"/var/www/clients/***/***/***/cloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":82,"function":"execute","class":"PDOStatement","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/3rdparty/doctrine/dbal/src/Connection.php","line":1136,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/DB/Connection.php","line":257,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":213,"function":"executeStatement","class":"OC\\DB\\Connection","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/AppConfig.php","line":236,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/App/AppManager.php","line":407,"function":"setValue","class":"OC\\AppConfig","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/Updater.php","line":375,"function":"disableApp","class":"OC\\App\\AppManager","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/Updater.php","line":259,"function":"checkAppsRequirements","class":"OC\\Updater","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/Updater.php","line":132,"function":"doUpgrade","class":"OC\\Updater","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/core/Command/Upgrade.php","line":255,"function":"upgrade","class":"OC\\Updater","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/3rdparty/symfony/console/Command/Command.php","line":255,"function":"execute","class":"OC\\Core\\Command\\Upgrade","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/3rdparty/symfony/console/Application.php","line":1009,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/3rdparty/symfony/console/Application.php","line":273,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/3rdparty/symfony/console/Application.php","line":149,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/lib/private/Console/Application.php","line":215,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/console.php","line":100,"function":"run","class":"OC\\Console\\Application","type":"->"},{"file":"/var/www/clients/***/***/***/cloud/occ","line":11,"args":["/var/www/clients/***/***/***/cloud/console.php"],"function":"require_once"}],"File":"/var/www/clients/***/***/***/cloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","Line":82}},"CustomMessage":"--"},"userAgent":"--","version":"21.0.2.0"}
{"reqId":"avpk6SzliVS6VrbPYk3a","level":3,"time":"2021-05-24T09:05:49+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::failure: Doctrine\\DBAL\\Exception\\DriverException: An exception occurred while executing a query: SQLSTATE[HY000]: General error: 4047 InnoDB refuses to write tables with ROW_FORMAT=COMPRESSED or KEY_BLOCK_SIZE.","userAgent":"--","version":"21.0.2.0"}
{"reqId":"avpk6SzliVS6VrbPYk3a","level":3,"time":"2021-05-24T09:05:49+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::updateEnd: Update failed","userAgent":"--","version":"21.0.2.0"}
{"reqId":"avpk6SzliVS6VrbPYk3a","level":1,"time":"2021-05-24T09:05:49+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::maintenanceActive: Maintenance mode is kept active","userAgent":"--","version":"21.0.2.0"}
{"reqId":"avpk6SzliVS6VrbPYk3a","level":1,"time":"2021-05-24T09:05:49+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"--","version":"21.0.2.0"}
{"reqId":"VBYGxEzJpKnDJidV8ep6","level":3,"time":"2021-05-24T09:10:01+00:00","remoteAddr":"10.0.0.6","user":"--","app":"PHP","method":"GET","url":"/cron.php","message":"Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) at Unknown#0","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0","version":"21.0.2.0"}
{"reqId":"WSnjYaOHecGKnueJ3GNh","level":3,"time":"2021-05-24T09:15:01+00:00","remoteAddr":"10.0.0.6","user":"--","app":"PHP","method":"GET","url":"/cron.php","message":"Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) at Unknown#0","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0","version":"21.0.2.0"}
{"reqId":"GxHPsm0e6OODudhOWhEp","level":3,"time":"2021-05-24T09:15:22+00:00","remoteAddr":"84.147.34.246","user":"--","app":"PHP","method":"GET","url":"/index.php/csrftoken","message":"Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) at Unknown#0","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15","version":"21.0.2.0"}
{"reqId":"GFFxTvMVFzljttr9k1NP","level":3,"time":"2021-05-24T09:16:58+00:00","remoteAddr":"84.147.34.246","user":"--","app":"PHP","method":"GET","url":"/index.php/csrftoken","message":"Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) at Unknown#0","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15","version":"21.0.2.0"}
</details>

Thanks if there's anyone who could help :)

Have a nice day
Tardar

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

**Comment by ack210** [comment]
For anyone landing here after DDGing the error like me, this was informative: https://help.nextcloud.com/t/new-setup-docker-compose-not-working/115673/9

**Comment by kesselb** [comment]
Nextcloud does **not** support MariaDB 10.6 for now. The reason is the compressed row format.

A possible solution is:
- To stick with MariaDB 10.5 
- `--innodb-read-only-compressed=OFF` to make compressed tables writeable again.

https://github.com/nextcloud/server/issues/25436 is the issue to track the progress. It's on the roadmap. A solution requires a migration of the row format to something different. Don't expect this migration for Nextcloud 22 / 23.

**Comment by AverageHumanoid** [comment]
I just encounter this as well, thanks for the quick solution.

**Comment by philsson** [comment]
> Nextcloud does **not** support MariaDB 10.6 for now. The reason is the compressed row format.
> 
> A possible solution is:
> 
> * To stick with MariaDB 10.5
> * `--innodb-read-only-compressed=OFF` to make compressed tables writeable again.
> 
> #25436 is the issue to track the progress. It's on the roadmap. A solution requires a migration of the row format to something different. Don't expect this migration for Nextcloud 22 / 23.

Thank you for the advice. Is this as easy as just recreating the mariadb container or does one need to use a backup (if database is migrated and not backwards compatible after upgrade).
Where do I run the ```--innodb-read-only-compressed=OFF``` command from?

Thank you in advance

**Comment by dkoerner85** [comment]
> Where do I run the --innodb-read-only-compressed=OFF command from?

If you are using docker-compose, add a _command_ line like this:

`command: --innodb-read-only-compressed=OFF`

e.g.

```
nc-db:
  image: mariadb:latest
  command: --innodb-read-only-compressed=OFF
  ... additional configuration ...
```

**Comment by philsson** [comment]
> > Where do I run the --innodb-read-only-compressed=OFF command from?
> 
> If you are using docker-compose, add a _command_ line like this:
> 
> `command: --innodb-read-only-compressed=OFF`
> 
> e.g.
> 
> ```
> nc-db:
>   image: mariadb:latest
>   command: --innodb-read-only-compressed=OFF
>   ... additional configuration ...
> ```

This worked wonders! Thank you soo much @dkoerner85

**Comment by R0Wi** [comment]
Anyone who develops NC apps and uses github actions to run tests, change
```yaml
services:
      mysql:
        image: mariadb
        ports:
          - 4444:3306/tcp
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
        options: --health-cmd="mysqladmin ping" --health-interval 5s --health-timeout 2s --health-retries 5
```
to
```yaml
services:
      mysql:
        image: mariadb:10.5
        ports:
          - 4444:3306/tcp
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
        options: --health-cmd="mysqladmin ping" --health-interval 5s --health-timeout 2s --health-retries 5
```

(see also https://github.com/nextcloud/spreed/commit/e8b1456f064b2e9d07aed01c87f25360addeb8d4)

**Comment by goekce** [comment]
For non-docker configuration it is also sufficient to add the option in `/etc/my.cnf.d/server.cnf`:
```
...
# this is only for the mysqld standalone daemon
[mysqld]
innodb_read_only_compressed=OFF
...
```

**Comment by BoleynSu** [comment]
FYI, according to https://mariadb.com/kb/en/innodb-compressed-row-format/#read-only. the workaround is no longer needed starting from v10.6.
