### ISSUE TITLE
Notifications for shared link downloads stopped working (version 20/21)

### ISSUE THREAD

**Issue by melyux** [nextcloud/server#27086]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Share a file through public link
2. Download the file
3. See nothing

### Expected behaviour
I should get a mobile push notification and a Nextcloud browser notification (and something under the bell icon with a red badge) saying someone downloaded the file I shared.

### Actual behaviour
Nothing happens. Not even anything until the bell icon in the web UI. But I still get notifications for two-factor authentication, and test notifications sent using the `occ` command still come through, on both browser and mobile.

It used to work a few versions back, maybe early 20.x. Noticed it stopped working from at the latest 20.0.9. Updated to 21.0.2, but still doesn't work.

### Server configuration

**Operating system:** Linux

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.4.19

**Nextcloud version:** (see Nextcloud admin page) 20.0.10, 21.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 19

**Where did you install Nextcloud from:** Linuxserver Docker image

**Signing status:**
<details>
<summary>Signing status</summary>
`No errors have been found.`
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
```
Enabled:
  - activity: 2.14.3
  - bruteforcesettings: 2.1.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_downloadactivity: 1.10.0
  - files_external: 1.12.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - notes: 4.0.4
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - provisioning_api: 1.11.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_nextcloud_notification: 3.1.2
  - twofactor_totp: 6.0.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - workflowengine: 2.3.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
```json
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "my.domain.com"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.2.1",
        "overwrite.cli.url": "https:\/\/my.domain.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "theme": "",
        "loglevel": 0,
        "updater.release.channel": "stable",
        "default_phone_region": "US",
        "skeletondirectory": "\/data\/skeleton",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Safari, Chrome

**Operating system:** Mac, iPhone, Windows

### Logs
Nextcloud doesn't seem to log successful/unsuccessful notifications, as far as I've seen. I can send test notifications with log level set to 0 (DEBUG), and the log doesn't move at all.

Here's some log lines that include the word "notification" if that helps:

```
{
  "reqId": "Qx0r2zXWX3SyifLfTHpl",
  "level": 0,
  "time": "2021-05-24T09:29:29+00:00",
  "remoteAddr": "x.x.x.x",
  "user": "username",
  "app": "files_sharing",
  "method": "GET",
  "url": "/ocs/v2.php/apps/notifications/api/v2/notifications",
  "message": "/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15",
  "version": "21.0.2.1"
}
```

#### Web server error log
<details>
<summary>Web server error log</summary>

```
N/A (empty)
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{
  "reqId": "Qx0r2zXWX3SyifLfTHpl",
  "level": 0,
  "time": "2021-05-24T09:29:29+00:00",
  "remoteAddr": "x.x.x.x",
  "user": "username",
  "app": "files_sharing",
  "method": "GET",
  "url": "/ocs/v2.php/apps/notifications/api/v2/notifications",
  "message": "/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.1 Safari/605.1.15",
  "version": "21.0.2.1"
}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)
