### ISSUE TITLE
[2FA][Suggestion] When entering the last digit, automatically submit and check (saves users' enter click)

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/server#2709]
* Nextcloud 11.0.0 already solved https://github.com/nextcloud/server/issues/1120 (skip an unneeded page during 2FA).

Please allow me to suggest, if possible, to implement

#### Suggestion

* when user enters the last (i.e. the 6th) digit, that then automatically the entered auth code is submitted.

This saves one click (only disadvantage: a correction of the last digit will be impossible).

**Comment by jancborchardt** [comment]
Great suggestion @Wikinaut! :)

@ChristophWurst does the code always have the same length (like 6 characters) so we can check this? Then it would indeed be cool.

**Comment by Wikinaut** [comment]
@jancborchardt @ChristophWurst 
https://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm#Implementation

"Agree upon a token length, N (default is 6)" -- indeed, other lenghts are possible!

Etwas schwammig, zugegeben, aber die meisten System benutzen "6".

See also https://github.com/archiecobbs/mod-authn-otp/wiki/UsersFile

```
 HOTP            - HOTP event-based token with six digit OTP
#       HOTP/E          - HOTP event-based token with six digit OTP
#       HOTP/E/8        - HOTP event-based token with eight digit OTP
#       HOTP/T30        - HOTP time-based token with 30 second interval and six digit OTP
#       HOTP/T60        - HOTP time-based token with 60 second interval and six digit OTP
#       HOTP/T60/5      - HOTP time-based token with 60 second interval and five digit OTP
#       MOTP            - Mobile-OTP time-based token 10 second interval and six digit OTP
#       MOTP/E          - Mobile-OTP event-based token with six digit OTP
```

**Comment by rullzer** [comment]
The TOTP app defaults to 6

**Comment by Wikinaut** [comment]
The suggested interface could automatically fire the submit if the built-in length is reached.

**Comment by jancborchardt** [comment]
Yup. I mean if it submits on 6 and succeeds – fine. If it submits on 6 and fails, we could just do nothing or wait a bit if typing is continued or the submit button is clicked.

**Comment by Wikinaut** [comment]
@jancborchardt I did not digged into the code, but the comparision should be done in equal time, when the six digits are submitted, this is at server side, I guess. Only change which is required could be most likely done at client side ("add some jquery").

**Comment by MorrisJobke** [comment]
Maybe @stephanruttloff wants to check this out ;)

**Comment by MorrisJobke** [comment]
> Maybe @stephanruttloff wants to check this out ;)

Code for this app is in https://github.com/nextcloud/twofactor_totp

**Comment by Wikinaut** [comment]
This issue should be moved to nextcloud/twofactor_totp . 
BTW, is someone wokring on that ?
