### ISSUE TITLE
Web can support the function of  uploading  whole folder

### ISSUE THREAD

**Issue by suozq1** [nextcloud/server#27092]
**Is your feature request related to a problem? Please describe.**
When I use nextcloud web side to upload a folder which contains some subfolders,I have to create the directory structure in the nextcloud manually.Once the directory structure is complex, this process is quite painful.I know that using the client can solve this problem, but not everyone wants to install the client.

**Describe the solution you'd like**
The web side can support the function of uploading folder, and upload the whole folder directly.
For reference: https://pan.baidu.com/

**Comment by acsfer** [comment]
Web folder is supported by drag and drop. At least in v20 with Chrome based browser.

**Comment by suozq1** [comment]
Thank you so much!
