### ISSUE TITLE
Make "The PHP OPcache is not properly configured" a little bit more tolerant and precise (Suggestion)

### ISSUE THREAD

**Issue by Linuxfabrik** [nextcloud/server#27094]
Related Code: `apps/settings/lib/Controller/CheckSetupController.php: protected function isOpcacheProperlySetup()`
Related Doc: https://docs.nextcloud.com/server/21/admin_manual/installation/server_tuning.html#enable-php-opcache

---
After monitoring our OpCaches, the function `isOpcacheProperlySetup()` should be a bit more tolerant and precise. These are our suggestions:

**max_accelerated_files**
```
		if ($this->iniGetWrapper->getNumeric('opcache.max_accelerated_files') < 10000) {
			return false;
		}
```
According to php.net:
> The maximum number of keys (and therefore scripts) in the OPcache hash table. The actual value used will be the first number in the set of prime numbers `{ 223, 463, 983, 1979, 3907, 7963, 16229, 32531, 65407, 130987, 262237, 524521, 1048793 }` that is greater than or equal to the configured value. The minimum value is 200. The maximum value is 1000000. Values outside of this range are clamped to the permissible range. 

Means: As long as Nextcloud consists of fewer than 16229 files, check on `if ($this->iniGetWrapper->getNumeric('opcache.max_accelerated_files') <= 7963)` (some Admins like to configure the precise values, and 10000 is as good as 7964).

---

**memory_consumption**
```
		if ($this->iniGetWrapper->getNumeric('opcache.memory_consumption') < 128) {
			return false;
		}
```
Nextcloud instances with 30 to 120 active (!) users use between 40 and 60 mb of opcache, so we would suggest that a check for 80 mb is sufficient: `if ($this->iniGetWrapper->getNumeric('opcache.memory_consumption') < 80) {`

---

**interned_strings_buffer**
```
		if ($this->iniGetWrapper->getNumeric('opcache.interned_strings_buffer') < 8) {
			return false;
		}
```
8 MB memory used to store interned strings is not enough (if you configure "8", you get 6 MB Buffer Size). 16 MB seem to be enough (you will get 12 MB Buffer Size): `if ($this->iniGetWrapper->getNumeric('opcache.interned_strings_buffer') < 16) {`

---

**Doc**
It could be emphasized that `opcache.save_comments=1` is a must, because disabling this configuration directive breaks Nextcloud because it relys on comment parsing for annotations.

**Comment by acsfer** [comment]
Feel free to make a PR 👍

**Comment by StarSmasher44** [comment]
There were some mentions of specific apps capable of throwing the memory requirement here upwards toward/on/above 128 MB.. Given that it is the suggested value, wouldn't it be easier and better to just request users set it to 128MB? Its 48 MB more, which is negligible at best and if someone does decide to add so many apps this becomes full, at least 128MB is a buffer many will not or barely reach. Unlike 80MB.

**Comment by MichaIng** [comment]
An alternative solution: #27403

**Comment by victoriat31** [comment]
I don’t know much about computers and I don’t understand what you are asking me to do.

**Comment by melroy89** [comment]
> It could be emphasized that opcache.save_comments=1 is a must, because disabling this configuration directive breaks 
> Nextcloud because it relys on comment parsing for annotations.

I'm just curious after all these years.. whether `opcache.save_comments=1` is still necessary in NC32?
