### ISSUE TITLE
Open the sidebar on scrollTo, and directly trigger the default action from search results

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#27100]
When opening a file, let's directly open the sidebar and trigger the default file action.

- [ ] Provide a FileInfo of the desired file via initialState
- [ ] Don't wait for the full scrollTo pagination before opening the sidebar
- [ ] Don't wait for the full page load to triggering the default action with the `https://dev.domain.com/apps/files/?dir=/&openfile=88` type url

**Comment by gary-kim** [comment]
Any chance we could add the ability to scroll to a file without triggering the default action (or does that already exist)? I can see situations in which you explicit want to scroll to a file without opening it.

**Comment by skjnldsv** [comment]
Right, @artonge there is already the `https://dev.domain.com/apps/files/?dir=/&openfile=88` url, so we should use that.
ScrollTo should just open the sidebar, but the openFile already open the file and trigger the action, it just doesn't work well as it's linked to the scrollTo pagination, so we should take it out and trigger the action also before it's fetched?
https://github.com/nextcloud/server/blob/497440477492b6e7df8ca1eb6c79eb7100a2fe24/apps/files/appinfo/routes.php#L45-L50
https://github.com/nextcloud/server/blob/b1dca57a1ce59bacc4089761275e4366e9760313/apps/files/lib/Controller/ViewController.php#L164-L171


Maybe add a new route like `/f/123456/open` that also trigger the scrollTo but the openfile as well?
https://github.com/nextcloud/server/blob/b1dca57a1ce59bacc4089761275e4366e9760313/apps/files/lib/Controller/ViewController.php#L343-L370

**Comment by artonge** [comment]
> Right, @artonge there is already the `https://dev.domain.com/apps/files/?dir=/&openfile=88` url, so we should use that.

It makes sense indeed. We should also update the search code to use `&openfile=...` then.

> Maybe add a new route like /f/123456/open that also trigger the scrollTo but the openfile as well?

Could the URL support two actions like `&scrollTo=...&openFile=...` so it just uses existing functionality instead of adding a new one.

**Comment by skjnldsv** [comment]
I think openFile was implemented with the inclusion of the scrollTo. But needs confirmation
