### ISSUE TITLE
[meta] The @nextcloud/developers team

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#2710]
Our `@nextcloud/developers` team has no real purpose except causing people to be pissed off when it’s used by someone new to mention around 80 people at once.
https://github.com/orgs/nextcloud/teams/developers

Hence I propose to just remove it. Any of the folks are in more relevant teams like /javascript, /design, /android etc.

Just want to make sure it’s not hooked up to some process. I can’t see anything like that, and even in the repository list there’s only the Mail app, which doesn’t make a lot of sense.

@MorrisJobke @LukasReschke @schiessle any objection?
(I opened this issue here and not in the forum because it directly concerns a topic here, and also for easier public reference.)

**Comment by LukasReschke** [comment]
The developers and maintainers team can from my opinion be removed as LGTM et al is dead.

**Comment by rullzer** [comment]
Go for it!

**Comment by schiessle** [comment]
I agree, I think we can remove them.

**Comment by schiessle** [comment]
done

**Comment by jancborchardt** [comment]
Ehm – I would have mentioned the @nextcloud/developers team one last time so people know what’s happening …

**Comment by jancborchardt** [comment]
Now everyone got a mail »The developers team on the Nextcloud organization has been deleted.« with no context.

So looping in @nextcloud/designers @nextcloud/javascript @nextcloud/android @nextcloud/community-mgmt:
**This is a last notification that the team was simply removed because we have more specific teams and the »developers« team was of no use. :)**

**Comment by enoch85** [comment]
We also have @nextcloud/vm  ;)

**Comment by MariusBluem** [comment]
Got this email and first thought **fuck** 😱😜
