### ISSUE TITLE
Preload files to sync and a list of all changed files

### ISSUE THREAD

**Issue by Niclas-sol** [nextcloud/server#27114]
Hi, I just want to share my idea for improved syncing.

I'm often confronted with adding new clients to my cloud and the long time it needs to sync all files (only the virtual copies of them - so not a bandwidth problem). So maybe it would be possible to create a sync file on the server with every cron execution creating a full list of all files. So the client could download only this one file with all information about the files without taking too much time syncing them. 
The other idea was to create a second file with a record of all changed files, i.e. the files changed over night so in the morning my client first needs to scan the whole cloud for changes.

I think this would be a way to improve sync speed and performance. The whole workload would be done by the server and not by the client.

Let me know what you think
Cheers

**Comment by acsfer** [comment]
`notify_push` tries to solve this: https://github.com/nextcloud/notify_push#client-push

**Comment by szaimen** [comment]
Yes, please use the notify_push app for this :)
