### ISSUE TITLE
Personal settings page wrong anchor

### ISSUE THREAD

**Issue by amittel** [nextcloud/server#2711]
Hi!
The anchor for personal information is wrong. it's `#avatar` but should be `#personal-settings` [link](https://github.com/nextcloud/server/blob/master/settings/templates/personal.php#L35)

NC: 11

**Comment by MariusBluem** [comment]
THX! Mind submitting a Pull request? 🤔👊

**Comment by MorrisJobke** [comment]
Will be fixed in 11.0.1 and 12.0.0
