### ISSUE TITLE
Errors aren't handled gracefully in the user creation modal

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#27115]
The UI is just stuck if one chooses an insecure password on master.

1. Install password_policy app
2. Create user with password "test" in the UI
3. See the XHR request fail
4. There is no indication in the UI of any failure

![Screenshot 2021-05-26 at 12 08 52](https://user-images.githubusercontent.com/878997/119642570-24756580-be1b-11eb-8438-b31a44bec384.png)

```
{"ocs":{"meta":{"status":"failure","statuscode":107,"message":"Password is among the 1,000,000 most common ones. Please make it unique. Password is present in compromised password list. Please choose a different password."},"data":[]}}
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
