### ISSUE TITLE
PDF.js stopped working with spaces

### ISSUE THREAD

**Issue by rico666** [nextcloud/server#27120]
### Steps to reproduce
1. current nextcloud 20.0.10
2. save some PDF file with space in its name
3. try to look at it.

### Expected behaviour

One should see the PDF file

### Actual behaviour

error message

PDF.js Version 2.4.456 (build: 228a591c)
Nachricht: Missing PDF "...yaddayadda/Detail%2520some_file.pdf".

-> observe the %2520, in the original file it is a space
when I replace the space with an underscore, all is well.

did work up to now.

**Comment by rico666** [comment]
confirmed this is persisting and not transient by:

* using with both chromium as well as Firefox and testing with various nextcloud users; Firefox was fresh with clean caches.
* updating the underlying Debian
* rebooting (you could say turning it off and on again)

Problem still there with files that provably worked in a previous version of nextcloud 20.0.7 or so (but not sure about the exact number).

**Comment by szaimen** [comment]
Here a workaround: https://github.com/nextcloud/files_pdfviewer/issues/381#issuecomment-845806364
