### ISSUE TITLE
/settings/admin/overview reports update while /updater/ doesn't

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#27129]
After updating a test instance from NC 21.0.2 to NC 22 beta 2, the version check on /settings/admin/overview reports an available update to NC 22 beta 2 … while /updater/ doesn't: "Current version is 22.0.0 beta 2. No update available."

**Comment by n3cr0cr0w** [comment]
I'm on 20.0.10 and update:check says 2 updates available but updater.phar says no update available.

**Comment by nursoda** [comment]
It was fixed in NC 22.0.0 released today, but as far as I see there, backports haven't been made:
https://github.com/nextcloud/server/pull/27758
