### ISSUE TITLE
Uploading existing file with UI doesn’t provide options to replace

### ISSUE THREAD

**Issue by fossxplorer** [nextcloud/server#27128]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.Upload existing document
2.
3.

### Expected behaviour
Windows with options
### Actual behaviour
Nothing
### Server configuration
Nginx
**Operating system:**
CentOS 7
**Web server:**
Nginx
**Database:**
MariaDB 10.1
**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
stable20 
**Updated from an older Nextcloud/ownCloud or fresh install:**

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
main.js?v=64864097-27:1 TypeError: Cannot read property 'replace' of undefined
    at Object._build (main.js?v=64864097-27:1)
    at Object.init (main.js?v=64864097-27:1)
    at e.fn.init.o.a.fn.octemplate (main.js?v=64864097-27:1)
    at Object.<anonymous> (main.js?v=64864097-27:1)
    at Object.<anonymous> (main.js?v=64864097-27:1)
    at l (main.js?v=64864097-27:1)
    at Object.fireWith [as resolveWith] (main.js?v=64864097-27:1)
    at Object.Deferred.m.each.r.<computed> [as resolve] (main.js?v=64864097-27:1)
    at Object.success (main.js?v=64864097-27:1)
    at l (main.js?v=64864097-27:1) "data:" undefined
```
</details>

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)
