### ISSUE TITLE
occ: Command line /  tab completion with sudo

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/server#27131]
**Is your feature request related to a problem? Please describe.**

It is great that occ offers to set up [tab completion](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html#enabling-autocompletion), but since it is good practice that the web server user has no profile (login shell set to /usr/sbin/nologin), it cannot be used in most cases.

**Describe the solution you'd like**
occ command line completion should be supported for the way occ is typically called via sudo (e.g.  `sudo -u www-data php /var/www/html/nextcloud/occ` ) 

 I am not sure as to how this could be set up, but it would be a great improvement. Maybe there could be a simple shell script wrapper for occ in /usr/local/bin where the web server user and path of the nextcloud installation have to be configured

**Comment by szaimen** [comment]
Hi there, you can create your own alias for the command e.g. like this:
https://github.com/nextcloud/vm/blob/66038488edbb440b2dda02e1d7e9a734417abdcc/static/change-root-profile.sh#L46
