### ISSUE TITLE
Create a script reporting all details about the installation & the bug report & logs to be uploaded to the bugtracker

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#2713]
Hi to All,

everybody who reports a bug or a strange behavior to the bugtracker is kindly asked by the robot to submit detailed information about his current installation: which apps are installed, which version, etc. and perhaps a logfile.

How about a button in the admin panel, which invokes a script, providing all necessary & required details, nicely formatted ready to be submitted to the bugtracker, including bug report and perhaps log file ???

After invoking, it should offer options to be able to select the right app which the user will report an issue on or select ALL just for documentation of the installation !!

That certainly will make bug reporting an easy issue and will help the developers at the same time to keep track and work on the issues much smoother!

I am looking for your input!

regards, hitam4450

**Comment by juliushaertl** [comment]
I created https://github.com/juliushaertl/issuetemplate a while ago, which generates a prefilled issue template. I guess this would just need some more love :see_no_evil:

**Comment by rullzer** [comment]
@juliushaertl :rocket: ! Give it love and get it to the appstore!

**Comment by hitam4450** [comment]
see  https://github.com/juliushaertl/issuetemplate/issues/8 as well!

When will be the birthday of your love ???

**Comment by hitam4450** [comment]
Another reference 

https://github.com/nextcloud/server/issues/127

**Comment by MorrisJobke** [comment]
@juliushaertl @rullzer There is also https://github.com/LukasReschke/issuereporter/tree/initial-import ;) - cc @LukasReschke

**Comment by ChristophWurst** [comment]
On a higher level, it would be great to have some kind of automated bug report for *any* app. How about we add a mechanism to the server that apps can use to easily generate bug reports. E.g. an app could specify which server info is relevant (example: version, logs, installed apps) and can add its own information to that (example: imap log in Mail) which will create the complete markdown one pastes to github.

**Comment by hitam4450** [comment]
A facility of direct Uploading logs or partial logs facilitates the reporting of difficulties and debugging for the developers.

regards, hitam4450

**Comment by hitam4450** [comment]
Any progress on this issue at this time ??

**Comment by MorrisJobke** [comment]
There is an app in the App Store: https://apps.nextcloud.com/apps/issuetemplate
