### ISSUE TITLE
Transifex translation updates

### ISSUE THREAD

**Issue by andypl78** [nextcloud/server#2716]
How fast is updated language from Transifex in the project?
Is it possible to download translations from Transifex through via CLI?

**Comment by jancborchardt** [comment]
Usually it should be every day on master and of course on every release … but I noticed our translation bot hasn’t run for a few days now: https://github.com/nextcloud/server/commits/master?author=nextcloud-bot

Any idea @LukasReschke @MorrisJobke?

**Comment by LukasReschke** [comment]
@MorrisJobke is the translation master. I suppose the bot is in holidays somewhere 🌮

**Comment by MorrisJobke** [comment]
Yes - bot is on holidays, because I'm on holidays. 🙈

**Comment by MorrisJobke** [comment]
> Usually it should be every day on master and of course on every release … but I noticed our translation bot hasn’t run for a few days now:

I'm aware of this, but currently are not at home to look into this (remote sadly doesn't work)

**Comment by MorrisJobke** [comment]
They are back now \o/
