### ISSUE TITLE
App settings/users: "Everyone" is not everyone

### ISSUE THREAD

**Issue by Linuxfabrik** [nextcloud/server#27206]
List of users: The naming or counting for the categories on the left side could be improved.

* "Everyone": The wording is wrong. "Everyone" just shows enabled users, including the Admin. So it should be renamed to "Enabled + Admin" (or should count disabled users, too).
* "Admin" is included in "Everyone", so it could be indented.
* "Disabled": if "Everyone" would count disabled users, this should be indented.

**Comment by szaimen** [comment]
cc @nextcloud/designers

**Comment by skjnldsv** [comment]
`Active users` would be nice
