### ISSUE TITLE
"last login" and "last sync"

### ISSUE THREAD

**Issue by Linuxfabrik** [nextcloud/server#27219]
`settings/users` reports "Last login", which only relates to the web interface and should therefore be renamed to "Last GUI login" (or similar). Unfortunately there is no value like "Last sync", which contains the time of the last sync by a client. Only if a user has not used a sync client and the web gui for a long time can one assume that he is inactive.

Suggestions:
* "Last login" should be renamed to "Last GUI login" or something similar.
* Additionally implement a "Last sync" timestamp column.

**Comment by szaimen** [comment]
cc @nextcloud/designers

**Comment by bes1002t** [comment]
I don't see any advantage of the "last sync" information. Could you please provide some use cases?

**Comment by Linuxfabrik** [comment]
Use case: to make sure that a user is really inactive for a certain period of time.

* "Last login" only reports the last login to the web interface. If a user only uses the sync client, this timestamp is useless.
* Only if "Last Login" and "Last Sync" is greater than n days can we assume that the user is inactive.

**Comment by bes1002t** [comment]
But what's the use case to know whether a user is inactive or not?
Do you want to remove this user? After which period of being inactive?

**Comment by Linuxfabrik** [comment]
Yes, this is the only way to determine if a user is **really** inactive and the user can be removed. After what period of time and in what way we can then decide for ourselves.
