### ISSUE TITLE
NextCloud 20.02 auto update to 21.01 snap Disable group folder app

### ISSUE THREAD

**Issue by igherardia** [nextcloud/server#27216]
hey everyone.

I have nextcloud installed on an ubuntu server it was upgraded to Snap 21 it was on Snap 20 and when it did that it stopped sharing group folders.
The application was deactivated.

Also detect that they generated 1 slugs weighing about 1.2 GB each within the my sql
his all happened after the auto update that nextcloud did last night.

**Comment by acsfer** [comment]
This happens frequently, not only for Group Folders. Sometimes it is OnlyOffice, or LDAP, sometimes others that get automatically disabled when upgrades are performed and absolutely no visibility about it. We control it manuelly each ime we do upgrades to reenable it right away. This should be done automatically.

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1: 

Would you mind to edit your post and add the [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)? The information are required to reproduce your issue.

**Comment by igherardia** [comment]
And this is the mysql log or backup that generates 1gb files and fills the hard disk.
NEXTCLOUD did not send an email warning about a disk almost full

![error nextcloud](https://user-images.githubusercontent.com/51250424/119987361-51508680-bf9b-11eb-80a7-6a9da33d9bf1.png)
