### ISSUE TITLE
Impossible to set password 1 month after receiving welcome message

### ISSUE THREAD

**Issue by palight** [nextcloud/server#27221]
Steps to reproduce
- Create a new user A in group 1 as nextcloud admin
- New user A don't use the welcome mail for one month
- After on month, new user use the link in the mail to set his password

Expected behaviour
- The new user set is password and is able to login

Actual behaviour
- The new user can't set his password with error : incorrect password

Server configuration
Operating system:
Debian 10 - amd64 x86_64

Web server:
nginx/1.14.2 (fpm-fcgi)

Database:
pgsql PostgreSQL 11.10 (Debian 11.10-0+deb10u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

PHP version:
7.3.27-1~deb10u1

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, imap, intl, json, exif, pdo_pgsql, pgsql, apc, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

Nextcloud version: (see Nextcloud admin page)
21.0.0 - 21.0.0.18

Updated from an older Nextcloud/ownCloud or fresh install:
fresh install

List of activated apps:
Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - announcementcenter: 5.0.0
 - calendar: 2.2.2
 - circles: 0.21.2
 - cloud_federation_api: 1.4.0
 - comments: 1.11.0
 - contacts: 3.5.1
 - contactsinteraction: 1.2.0
 - dashboard: 7.1.0
 - dav: 1.17.1
 - deck: 1.4.2
 - documentserver_community: 0.1.9
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_accesscontrol: 1.11.0
 - files_mindmap: 0.0.24
 - files_pdfviewer: 2.1.0
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.10.0
 - firstrunwizard: 2.10.0
 - forms: 2.2.4
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - onlyoffice: 7.0.2
 - password_policy: 1.11.0
 - photos: 1.3.0
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - ransomware_protection: 1.10.1
 - recommendations: 1.0.0
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - side_menu: 1.23.1
 - spreed: 11.2.1
 - support: 1.4.0
 - survey_client: 1.9.0
 - systemtags: 1.11.0
 - tasks: 0.13.6
 - text: 3.2.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.0
 - updatenotification: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.5.0
 - weather_status: 1.1.0
 - workflow_script: 1.6.0
 - workflowengine: 2.3.0
Disabled:
 - admin_audit
 - bruteforcesettings
 - encryption
 - files_external
 - maps
 - nextcloud_announcements
 - user_ldap

Nextcloud configuration:
Config report

Are you using external storage : no

Are you using encryption: no

**Comment by kesselb** [comment]
The token to reset a password is valid for 7 days.

**Comment by palight** [comment]
ok, it makes sense, thanks for your answer. But if admin click sent again welcome message, the token should be reset no ? Cause it isn't the case for me.
i'll edit my message to add this.

**Comment by palight** [comment]
@kesselb Ok, it makes sense, thanks for your answer. But if admin click sent again welcome message, the token should be reset no ? Cause it isn't the case for me
