### ISSUE TITLE
User logged out from talk when session_lifetime parameter set

### ISSUE THREAD

**Issue by kbanaszak** [nextcloud/server#27242]
Hello I have nextcloud version 20.0.2. I have a problem when having conferences with talk (version 11.2.1) I get logged out from nextcloud after 5 minutes during the conversation with session_lifetime parameter set to 300 seconds in config.php.
 
Is there any other parameter which will not allow to log out user from active session when using talk or this is a nextcloud bug? Talk should also send keep alive session packets.

Best regards
Krzysztof Banaszak

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
