### ISSUE TITLE
Change domain URL in shared links

### ISSUE THREAD

**Issue by brucealthompson** [nextcloud/server#27240]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Please see https://help.nextcloud.com/t/change-domain-url-in-shared-links/30972 which has been around for about 3 years now. It provides a basic description of this issue along with a group of users that need the functionality.

In my particular case, I have developed a Nextcloud based solution for home / SMB users that enables a Nextcloud server to be deployed on premises in a local network. The resulting solution consists of a locally deployed Nextcloud Server with a private IP address and an HTTP proxy with a public IP that point back to the locally deployed Nextcloud server. I assume that this type of solution is pretty common in the Enterprise space.

I have also developed a smart redirect feature that redirects users to the local Nextcloud server from the public URL to the local URL transparently if they are on the local network. So if the user is on the local network, Nextcloud will run at LAN speeds and if they are remote Nextcloud will run at WAN speeds. No configuration is required for this this functionality.

The problem comes when a user is using the local Nextcloud server and wants to share a file with someone on the public Internet. I need to switch the local LAN address in the share URL with a public domain for this use case. If could do this, everything would work seamlessly.

**Describe the solution you'd like**
The solution I am pursuing is simple. I would like to have a Nextcloud configuration variable (config.php) that can be set to specify an external domain name that can be used to reach the Nextcloud instance on the public Internet. If this variable is set, then when the user asks to share a file or directory, the share url would include the public domain name instead of a locally accessible domain name or IP address.

**Describe alternatives you've considered**
I keep hearing that the "solution" to this problem is to deploy a local DNS server that resolves the public domain name to a local IP address. I assume this type of solution is the accepted approach for medium / large enterprises that control a local DNS server. Unfortunately, I am working with SMB / home users that have no idea how to deploy or configure a local DNS server. This class of users does not typically have configuration access to the router which is configured as their local DNS server. Bottom line is this type of solution does not fly for the class of users I am working with.

**Additional context**
I have already identified the php code to modify to solve this issue. Here's the good news and bad news on my attempt to fix this issue myself.

I have found the PHP code that creates shared links and modified it to return an external domain name for the shares link if one is configured in config.php. I have checked with a php debugger and it seems to work perfectly. The modified code is in apps/files_sharing/lib/Controller/ShareAPIController.php. I modified the formatShare() function to add this functionality.

Now the bad news: It seems that the Nextcloud javascript code must be ignoring the domain in the url returned by formatShare() and substituting the original domain name in the returned shared URL. I have not gotten to the bottom of this issue.

I would be more than happy to fix this issue myself if someone can point me to the javascript (or other code) that is ignoring the returned domain name from apps/files_sharing/lib/Controller/ShareAPIController.php/formatShare() and replacing it with a Nextcloud server domain name.

Can anyone help? I would be glad to contribute the resulting solution.

Thanks greatly,

Bruce T

**Comment by brucealthompson** [comment]
Good news!!!

I have completed this feature on my Nextcloud implementation based on version 21.0.0. My testing so far indicates it works fine.

Since no one seems interested in this feature, I will leave it as a private enhancement in my Nextcloud implementation for now. If anyone is interested in this feature and is willing to merge it into the Nextcloud trunk, I would be happy to share the changes associated with this feature.

**Comment by GustelDE** [comment]
Hi, is there a way to implement this feature?
I use NC with two URLs, one internal, one external:

internal: cloud.internal.mydomain.com
external: cloud.mydomain.com

If I share links from internal, all sharing-links include the "internal" part of the URL.

**Comment by brucealthompson** [comment]
Your use case is exactly the same as mine. I think there are quite a few people using NC like this.

My implementation is for Nextcloud 21.0.0. I am really hoping someone is interested in applying my implementation to the trunk. Then everyone will be able to use it.

**Comment by acalatrava** [comment]
I'm also interested on this, @brucealthompson did you publish a PR?

**Comment by brucealthompson** [comment]
I am not sure what a PR is.

**Comment by acalatrava** [comment]
A PR (Pull Request) is a request to add your modifications to the main
trunk. If you don’t know how to do it I can do it for you.

What are the modifications you did to accomplish this?

**Comment by jonjon0815** [comment]
I‘m also interessted on this. Could you please describe what changes you did in NC?

**Comment by rodionxabibov** [comment]
Hello @brucealthompson I'm very interested in your solution to this problem.

**Comment by jogaman** [comment]
Would also love to solve this, have the same issue

**Comment by Piceeeeeee** [comment]
hello, did you work on it? i have the same issue, where  my main public domain run trought cloudfare, with a cap of 100 mb max size so upload to share file are limited, i want to run a other public domain just for share file. Some people are working on chunking for share link, so we can bypass the upload limit but it from 2017 and still nothing, so 2 domains can be a solutions
