### ISSUE TITLE
Crashes via Mobile Browsers on large folders

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#27241]
When browsing via mobile browser and then you start to scroll fast on the screen the web request crashes like below video. I can't replicate this on a computer browser only happens via mobile phone or tablet. 

NC 21.0.2
PHP 8
MariaDB 10.5.10

Nothing in the error log. 

https://user-images.githubusercontent.com/59488153/115739933-f9977d80-a353-11eb-9d22-265551d8d1c3.mp4

**Comment by andyxheli** [comment]
Systems to happen on iOS devices

**Comment by szaimen** [comment]
cc @nextcloud/ios

**Comment by andyxheli** [comment]
Still an issue 22.3.0

**Comment by andyxheli** [comment]
Since no response form dev im closing
