### ISSUE TITLE
[v22.0.0beta2] ./occ migrations commands missing

### ISSUE THREAD

**Issue by Grotax** [nextcloud/server#27278]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. checkout current master branch or v22.0.0beta2
2. execute `php ./occ migrations:`

### Expected behaviour
Migrations commands are listed and can be executed.

### Actual behaviour
Error "There are no commands defined in the "migrations" namespace."
`php ./occ` does not list any migrations

### Server configuration

**Operating system:** Manjaro Linux

**Web server:** none

**Database:** sqlite

**PHP version:** 8.0 + 7.4

**Nextcloud version:** v22.0.0beta2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** git

**Signing status:**  ok
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite",
        "version": "22.0.0.5",
        "overwrite.cli.url": "http:\/\/localhost",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "maintenance": false
    }
}

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** none

**Operating system:** none

### Logs

No logs available
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

No logs available
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
No logs available
```
</details>

Additional information, i first noticed it because of our CI failing, https://github.com/nextcloud/news/runs/2683648140

**Comment by go2sh** [comment]
See https://github.com/nextcloud/server/pull/27113

**Comment by Grotax** [comment]
Ah I see, thanks I tried to find something via the search but yea ..
