### ISSUE TITLE
graceful dealing with large files from user perspective

### ISSUE THREAD

**Issue by petesimonic** [nextcloud/server#27285]
Home user doesn't expect a limitation in [half of their device/desktop/VPS/VM RAM for file upload](https://help.nextcloud.com/t/504-gateway-timeout-for-large-file-uploads/87839/18). On the other hand they can posses or rent some big external storage device/service. And it's natural to want to use it for storage of drive images, which could range from installation media or DVD to virtualized HDDs, so it's from 4 GiB to 4 TiB. Common Nc host have less than 8 GiB RAM and none of them have 8 TiB.

So it would be highly reasonable to warn user through client apps, admin interfaces, and via documentation on the file-size that their instance is capable to put through. And to give people hints what to do if they need more performance (for example to recommend managed service, or system upgrade guidelines).

It would be magnificent solution to get rid of this limitation. But I'm not sure if it didn't make into the very core of whole system, and cannot be removed without deep update of arch and refactoring.

**Comment by kesselb** [comment]
Closing in favor of https://github.com/nextcloud/server/issues/17992.
