### ISSUE TITLE
Changing PW of user as admin is lacking Feedback on insecure password

### ISSUE THREAD

**Issue by b-m-f** [nextcloud/server#27284]
### Steps to reproduce
1. Login as Admin
2. Have password policy in place
3. Try to change a users password to an insecure one

### Expected behaviour
Warning pops up that password is not in line with policy

### Actual behaviour
No Feedback. Leaving me to think everythin succeeded.
Feedback is missing on succesfull changes as well.

### Server configuration

**Operating system:**
Docker image: nextcloud:21-apache

**Database:**
PostgresQL

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

**Comment by b-m-f** [comment]
Hi @szaimen,

will test this week and provide an update

**Comment by b-m-f** [comment]
Hello @szaimen,

the problem still persists in **21.0.3**

**Comment by szaimen** [comment]
@nickvergessen does this need to be fixed in the server or password_policy repository?

**Comment by nickvergessen** [comment]
The response is already containing all info:
```json
{
  "ocs": {
    "meta": {
      "status": "failure",
      "statuscode": 103,
      "message": "Password is among the 1,000,000 most common ones. Please make it unique. Password is present in compromised password list. Please choose a different password."
    },
    "data": []
  }
}
```

So needs fixing in the user management to show the returned error

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
