### ISSUE TITLE
Seperate OCC PHP requirement from nextcloud PHP requirement

### ISSUE THREAD

**Issue by lorddoumer** [nextcloud/server#2728]
### Steps to reproduce
1. nextcloud 11.0 installed on a 1&1 linux webspace iwth php 7
2. login via ssh and try to run OCC 

### Expected behaviour
OCC help to appear

### Actual behaviour
error message: "You are currently running 5.5.38. Please update your PHP version."

### Server configuration
**Operating system**:
Linux

**Web server:**
Shared Host, 1&1

**Database:**
MySQL

**PHP version:**
7 (actually used for nextcloud) but 5.5 for CLI

**Nextcloud version:** (see Nextcloud admin page)
11

**Updated from an older Nextcloud/ownCloud or fresh install:**
10

===

Until now I've been using the OCC command to upgrade but since I'm on a shared host (1&1) the CLI-PHP version is another than the on actually used by nextcloud – in case of 1&1 the PHP version can be set to 7 but to use PHP from SSH you have to add "/usr/bin/php5.5-cli" and therefore the CLI-PHP version is only 5.5 regardless what is actually used. Please correct me if I'm wrong but if the OCC command doesn't really need a PHP version >5.6 it would be great to seperate the requirements of nextcloud and OCC so people on shared hosts who have no influence on the CLI-version can still use the OCC command to upgrade (had very bad experiences with updating without the OCC command with owncloud long time ago).

**Comment by LukasReschke** [comment]
The occ command executes code that requires PHP 5.6. This is thus not possible.

**Comment by lorddoumer** [comment]
damit, no more OCC :(
sorry for asking
