### ISSUE TITLE
v21.0.1 is still tagged as latest GitHub release

### ISSUE THREAD

**Issue by bjo81** [nextcloud/server#27299]
It should be v21.0.2.

```
  "tag_name": "v21.0.1",
  "target_commitish": "master",
  "name": "v21.0.1",
  "draft": false,
  "prerelease": false,
  "created_at": "2021-04-08T12:47:59Z",
  "published_at": "2021-04-09T08:24:14Z",
```

**Comment by szaimen** [comment]
Hi, thanks for your report! Where did you see this output?

**Comment by bjo81** [comment]
I get this output when asking the Github API for the lastest release:
`https://api.github.com/repos/nextcloud/server/releases/latest`

**Comment by szaimen** [comment]
This is simple to answer: you don't see NC21.0.2 because no new release on github was tagged since NC21.0.1.
See https://github.com/nextcloud/server/releases

---

cc @nextcloud/infrastructure for tagging a new one

**Comment by gary-kim** [comment]
They are tagged in git but they are not set as GitHub releases. For instance, you can see the v21.0.2 release [here](https://github.com/nextcloud/server/releases).

**Comment by bjo81** [comment]
Yes, I know that they are tagged in git. But I'm wondering why v21.0.2 isn't tagged as GitHub release.

**Comment by gary-kim** [comment]
GitHub releases aren't usually used for artifacts so there is no real necessity to mark them as GitHub releases. You could use the GitHub tags API if you're looking for the latest version of Nextcloud.

https://api.github.com/repos/nextcloud/server/tags

**Comment by bjo81** [comment]
I'm looking for the latest stable version via the API, so using the tags API wouldn't be usable except I filter for RC, beta etc.
But what is the difference between 21.0.1 and 21.0.2 that 21.0.2 isn't tagged as GitHub release?

**Comment by MorrisJobke** [comment]
As of now we don't use github releases. Also we plan to use it in the future but then under a different org due to permission discussions. You will find them in https://github.com/nextcloud-releases/server once we automated this.
