### ISSUE TITLE
Clicking the update banner does not open a new window

### ISSUE THREAD

**Issue by ungesundes-halbwissen** [nextcloud/server#273]
Clicking the update banner at the top reading: "Nextcloud ...is available. Get more information on how to update" opens a page in the documentation where one can learn about how to update.

This page opens in the very same window I run Nextcloud in. It would be better to open this link in a new target window in order not to have to navigate to get my Nextcloud window back.

**Comment by Faldon** [comment]
I was just checking the responsible file. I assume it's notification.js from apps/updatenotification/js.
According to the code, the link already generated with target '_blank':
`element = $('<a>').attr('href', docLink).attr('target','_blank').text(text);`

My personal cloud is up-to-date in the version 8 branch, but if I run the javascript in the console (I tested Chrome and Firefox) and click the notification banner, the link is opened in a new window/tab as expected.

**Comment by ungesundes-halbwissen** [comment]
Thx for checking @Faldon 
I double checked as well and for me the behavior is reproducible. Running NC 9.0.51 using Firefox
Please check the screenshot enclosed (Note, that the system language is set to German, but the upgrade notice is still showing up  in English, despite an existing translation.
The element also seems to be missing the target="_blank" parameter you mentioned
![nc9 0 51](https://cloud.githubusercontent.com/assets/20168451/16562823/05663b6c-41ff-11e6-9c23-11fd4c55fb31.png)

**Comment by Faldon** [comment]
@ungesundes-halbwissen I'm fine with German. :-) I will set up a development server in the evening and try to find out, if the aforementioned JavaScript file is really responsible for creating the update notification.

**Comment by schiessle** [comment]
fix was merged. Thanks @Faldon for debugging and fixing it!
