### ISSUE TITLE
l10n: There are no translated text strings in the search engine

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#27305]
Steps:

1. Select for e.g: Dashboard from the menu.
2. Select Search.

There is an untranslated word "Collectives":

![obraz](https://user-images.githubusercontent.com/47037905/120195239-ced7f900-c21e-11eb-96ba-22dd84b72258.png)

There are also other untranslated word, for example:

![obraz](https://user-images.githubusercontent.com/47037905/120198240-2e83d380-c222-11eb-8171-38a3049862f4.png)

App:
Nextcloud 21.0.2
Collectives 0.6.2
Deck 1.4.2

**Comment by szaimen** [comment]
I think this was fixed in the meantime
