### ISSUE TITLE
Duplicate text string

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#27304]
Steps:
1. Select a conversation in Talk.
2. Select Search.

The word "Messages" is duplicated:

![obraz](https://user-images.githubusercontent.com/47037905/120194324-c29f6c00-c21d-11eb-871f-6cd624ebe6cd.png)

App:
Nextcloud 21.0.2 and 22.0.0 beta 2
Talk 11.2.1 and 12.0.0-alpha.1

**Comment by szaimen** [comment]
I think this was fixed in the meantime
