### ISSUE TITLE
Switching from gallery view to list view not possible

### ISSUE THREAD

**Issue by mediteran** [nextcloud/server#2731]
[###] Steps to reproduce
1. Go to your NextCloud installation via public share link.
2. Switch to gallery view.
3. Try to switch back to list view.

### Expected behaviour
There should be a visible button to switch back to list view.

### Actual behaviour
No possibility to switch back to list view. Obviously, the button for list view is underneath the "download" button in the upper right corner. You should see this clearly in the following screenshot:

![before](https://cloud.githubusercontent.com/assets/24620624/21286216/11f7736a-c44e-11e6-95e7-dd6f2b9a306a.jpg)

### Server configuration
**Operating system**: Debian on web server

**Database:** SQLite

**PHP version:** 5.6

**Nextcloud version:** 10.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:**

### Client configuration
**Browser:** Firefox & Safari

**Operating system:** MacOS 10.8.5 & 10.10.5 & 10.11.4

Solution:

Go to: nextcloud/core/css/header.css
and in

.header-right {
position: absolute;
**right: 0px;**
padding: 7px 5px;
color: #fff;
height: 100%;
max-width: 80%;
white-space: nowrap;
box-sizing: border-box;
}

change "right: 0px;"
to: "right: 50px;"

Then it should look like this:

![after](https://cloud.githubusercontent.com/assets/24620624/21286248/f9df3a46-c44e-11e6-916c-f3533830ef4c.png)

**Comment by tflidd** [comment]
@nextcloud/designers

**Comment by MorrisJobke** [comment]
This is an issue of the gallery app - cc @oparoz

**Comment by schiessle** [comment]
Can reproduce, broken on stable10 but already fixed on stable11 and master
