### ISSUE TITLE
Office File cannot create from template

### ISSUE THREAD

**Issue by anilsson97** [nextcloud/server#27313]
![image](https://user-images.githubusercontent.com/74618677/120244381-526b0780-c26a-11eb-8924-9dc8891efa98.png)
![image](https://user-images.githubusercontent.com/74618677/120244389-572fbb80-c26a-11eb-838e-ca08c8d5ee66.png)

**Comment by szaimen** [comment]
Looks to me like a duplicate of https://github.com/nextcloud/server/issues/26672
