### ISSUE TITLE
More informative automatic mails for changed appointments/invitations

### ISSUE THREAD

**Issue by hani2016** [nextcloud/server#27323]
Dear Community,
when a person accepts an invitation or something changes in an appointment, I get a short mail every time with the headline: "Invitation updated". Unfortunately, this mail never says who exactly did what.

Therefore, it would be very nice if the message would also say who changed the appointment and what they did (acceptance/cancellation).

I hope that I have conveyed my request understandably. If there are still questions, I will be happy to help clarify them.

Attached is a screenshot, which shows a mail without meaningful content.

Thanks a lot
Hani
![68df5788a0570c72ee452a686acb215364375f77](https://user-images.githubusercontent.com/85161706/120301176-e2419d80-c2cc-11eb-9f0f-ca18fb9aa44b.jpg)

**Comment by tcitworld** [comment]
Seems to be a duplicate from https://github.com/nextcloud/server/issues/14127 and https://github.com/nextcloud/server/issues/18508

**Comment by hani2016** [comment]
Oh right, i tried to searched for a duplicate, but obviously not enough. Thank you.

**Comment by tcitworld** [comment]
No worries, it's hard to find since sending invitations emails is handled in the server repo and not the calendar one.
