### ISSUE TITLE
OCC command returns an exit code without any message

### ISSUE THREAD

**Issue by fourstepper** [nextcloud/server#27321]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Run the occ command, under the correct user
2. Observe

### Expected behaviour
the occ command should either stacktrace, or inform me about the possible options

### Actual behaviour
it returns nothing, except for an exit code of 255

```
[test@test nextcloud]$ php occ
[test@test nextcloud]$ echo $?
255
```

### Server configuration

**Operating system:**
CentOS 8

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
PHP 7.3.28 from the IUS repos

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 21.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

</details>

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

Without configuration report and logs nothing we can do.

**Comment by mritzmann** [comment]
We have experienced the same behaviour after upgrading from Nextcloud 20.0.10 to 21.0.2. `php occ` returns nothing, except for an exit code of 255. As soon as we comment out `memcache.local` in `config.php` it works.

You might want to test that too @fourstepper.

Logs and Configuration:

* [php-error.log](https://gist.github.com/mritzmann/064b96e7b82f9e3b00ea80220e9930c8)
* [config.php](https://gist.github.com/mritzmann/b9af0735e5d3667f161b9a8b79bcdcd6)

**Comment by fourstepper** [comment]
this is exactly the same behaviour and local memcache configuration we have configured. thanks @mritzmann , as a temporary fix this is pretty good

**Comment by mritzmann** [comment]
Thanks @kesselb for the link to #25742!

My conclusion from this: Nextcloud 21 requires that apc is also enabled for the cli. For Nextcloud 20, this was not necessary or was not necessary in our setup (therefore not noticed before).

* Quickfix: `php --define apc.enable_cli=1 occ`
* Correct fix: add `apc.enable_cli=1` to the php configuration

Thank you for your help, the problem is solved for me.

**Comment by mritzmann** [comment]
> [..] or inform me about the possible options

But the point made in the opening post is still correct: it would be nice if `occ` output the reason why it doesn't work. But I understand that it is not always possible to catch all circumstances. :-)

**Comment by mritzmann** [comment]
By the way, setting `apc.enable_cli` to `0` by default seems to be normal.

* `0` is the default for `apc.enable_cli`
* `0` is recommended for `apc.enable_cli`

```
apc.enable_cli int
    Mostly for testing and debugging. Setting this enables APC for the CLI version of PHP.
    Under normal circumstances, it is not ideal to create, populate and destroy the APC cache on every CLI request,
    but for various test scenarios it is useful to be able to enable APC for the CLI version of PHP easily.

https://www.php.net/manual/de/apcu.configuration.php
```

But that's just a side note from me :)

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/issues/25742

**Comment by kesselb** [comment]
The next release will include a fix. I suggest to read the linked issue and the related pull request.

**Comment by mritzmann** [comment]
#25742 has more comments and linked commits/PRs than I own socks, so I missed that.... Thanks for the info, i appreciate that.
