### ISSUE TITLE
Expose "Shared" public link expiration dates in a calendar

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#27332]
This is a feature request to allow any "Shared" file or folder expiration date to be exposed in the Calendar app.  It would be useful to use the name as the event title, public share note as description and display expiration as the end date.  Thanks for considering!  I didn't see a previous posting about this.

[Here is the link to OCS API documentation, which I believe is the right place for more info.](https://docs.nextcloud.com/server/20/developer_manual/client_apis/OCS/ocs-share-api.html)

**Comment by tcitworld** [comment]
Makes more sense to expose these in a virtual calendar through dav.

**Comment by tcitworld** [comment]
For anyone who would be interested in creating such an app, you will be able to:
* get a list of `IShare` with `OCP\Share\IManager` for each user
* convert each IShare into a VObject
* register an `OCA\DAV\CalDAV\Integration\ICalendarProvider`. Check the [Deck app](https://github.com/nextcloud/deck/tree/master/lib/DAV) own calendar integration to see how it's done.

**Comment by sunjam** [comment]
Hi!  I was thinking in a public calendar that could be assigned to a group
or publicly shared.

**Comment by tcitworld** [comment]
Those things can be done as well.
