### ISSUE TITLE
PDF files with special chars can’t open in viewer

### ISSUE THREAD

**Issue by sebalis** [nextcloud/server#27330]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Log into Nextcloud in a browser, go to the files app
2. Find or upload a PDF file whose filename contains characters that need to be URL-encoded (so space will do)
3. Click on the file to view it

### Expected behaviour
The file should be opened in the subwindow that appears (which basically is the browser’s native viewer using a DAV URL for the file)

### Actual behaviour
The subwindow appears and shows an error. Here is a sanitised version of the detail message that can be shown in Firefox after clicking on “More information” for a file called “PDF file.pdf”: ```PDF.js v2.5.207 (build: 0974d6052) Message: Missing PDF "https://.../remote.php/dav/files/.../PDF%2520file.pdf".```

The URL is clearly URL-encoded twice. %20 should appear, but %2520 is found. %20 would be a URL-encoded space, %25 is a URL-encoded percentage sign.

### Server configuration

**Operating system:** Linux

**Web server:** Problem encountered on Apache and Nginx

**Database:** MariaDB

**PHP version:** unknown, but recent (Docker setup)

**Nextcloud version:** Problem encountered on 20.0.10 and 21.0.2 (stable/unstable Docker setup, current versions)

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** Docker hub

<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**

**Nextcloud configuration:**

I will add these items on request.

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:** Problem seen on recent Firefox and Chromium

**Operating system:** Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

No relevant errors were found in the logs.
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

No relevant errors were found in the logs.
</details>

#### Browser log
<details>
<summary>Browser log</summary>

The only error found is a 404 response for a request to the doubly-encoded URL.
</details>

**Comment by ttomasini** [comment]
This has been already resolved and will be probably shipped soon: https://github.com/nextcloud/files_pdfviewer/issues/381
