### ISSUE TITLE
Class CardDavBackend does not exist after upgrade to NC11

### ISSUE THREAD

**Issue by mr-gosh** [nextcloud/server#2733]
### Steps to reproduce
1. Upgrade fully patched Nextcloud 10 to 11 without errors
2. try to sync any DAV related resources
3. look into logs to see missing stuff 

### Expected behaviour
Tell us what should happen

Sync of caldav, carddav aso. Should just work

### Actual behaviour
Tell us what happens instead

No dav syncs possible and an error in the owncloud log

### Server configuration
**Operating system**:
Ubuntu 14.04 64bit
**Web server:**
Apache 2.4.7
**Database:**
Mysql 5.5.53
**PHP version:**
7.0.14
**Nextcloud version:** (see Nextcloud admin page)
11.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 10.0.2
**Where did you install Nextcloud from:**
Tar.gz from your website
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
app:list
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - direct_menu: 0.9.3
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - news: 10.1.0
  - nextcloud_announcements: 1.0
  - notes: 2.1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.4
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - files_retention
  - music
  - ownnote
  - user_external
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oclb6yyk0div",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "Changed"
        ],
        "datadirectory": "\/media\/4tb\/owncloud\/",
        "overwrite.cli.url": "http:\/\/changed\/owncloud",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "changes",
        "mail_smtpmode": "php",
        "mail_domain": "changed",
        "htaccess.RewriteBase": "\/",
        "appstore.experimental.enabled": true,
        "updater.release.channel": "stable"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes - lokal
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/
Nope
#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
emty
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment]
File `apps/dav/appinfo/register_command.php` does not exist anymore in Nextcloud 11.
Seems like you didn't remove all files before uploading the new files.

See https://docs.nextcloud.com/server/10/admin_manual/maintenance/manual_upgrade.html step 3 and the following

**Comment by mr-gosh** [comment]
I repeated the whole thing once again and this time i didn't copy the missing apps from the apps folder - so the only copied thing is the config file.

Still the same!

**Comment by nickvergessen** [comment]
Do you still have `apps/dav/appinfo/register_command.php` in your folder?

**Comment by mr-gosh** [comment]
nope - also the nextcloud log es empty and the apache error log shows nothing...

it seems that everythign is working but no caldav or carddav sync is discoverable anymore...
I there only have the error logs from davdroid... :(

in evolution i get an "HTTP Error: Method Not Allowed"

**Comment by papjul** [comment]
I can confirm the same issue, with the same steps to upgrade, DAVDroid doesn't work for me neither. It was working in Nextcloud 10.0.2. I also updated my nginx config according to latest docs. DAVDroid says 404 Not Found.
It is looking for https://<mycloud>/remote.php/caldav/calendars/<Username>/defaultcalendar/ and https://<mycloud>/remote.php/carddav/addressbooks/<Username>/contacts/.

**Comment by mr-gosh** [comment]
perhaps its a combination of changes in nextcloud / apache2 / dav autodiscovery?

i am using LetsEncrypt...

**Comment by papjul** [comment]
We use different HTTP servers. I also use Let's encrypt but the error is a 404 in DAVDroid, not an issue with the certificate.
Maybe URLs changed? Like the default calendar's name has changed?

**Comment by mr-gosh** [comment]
@papjul after you mentioned the renaming of the calendars I deleted all caledars from evolution and than i can re-add them after posting the whole string - so it more likely a auto discovery problem cause some detection things do not work anymore as before...

i will try a few things in davdroid again now.

**Comment by mr-gosh** [comment]
it seems it works if you delete the whole account in davdroid and recreate it with the https://yourdomain/remote.php/dav

@papjul can you confirm this?

**Comment by papjul** [comment]
Confirmed. Can we reopen this bug and change the title?

**Comment by mr-gosh** [comment]
Still the same after an DavDroid update.
Massive problems with carddav sync.

**Comment by kesselb** [comment]
Does this error still occur?

**Comment by mr-gosh** [comment]
Not for me, else won't be able to use nextcloud anymore...
