### ISSUE TITLE
Search Function is Timing out - External Storage via SFTP

### ISSUE THREAD

**Issue by Keaters2913** [nextcloud/server#27335]
Issue: When doing a search for a file that is on a mapped External Storage via SFTP, it will just spin and hang and nothing will happen

### Steps to reproduce
1.Go to Files
2. Click on the Magnify Glass icon and type in the name of a file to find it including the file extension in the search as well
3. All I get is a spinning icon if it is searching for the file, but nothing will come up after 10 minutes

### Expected behaviour
The file and other similar named files should come up in the search field when searching in Files section.

### Actual behaviour
Just spins and hangs and nothing comes up.  Here is a screenshot of a file in a folder called IT Projects that I am searching and nothing is populating

https://user-images.githubusercontent.com/77809014/120216757-6deff700-c205-11eb-97a8-95300ad288da.png

### Server configuration

**Operating system: Ubuntu 20.0.4

**Web server: Apache 2

**Database: MySQL 8.0

**PHP version: 7.4.18

**Nextcloud version:** 21.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install: Updated

**Where did you install Nextcloud from: Snap Github

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.


**Are you using external storage, if yes which one: sftp

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one: No

**Comment by Keaters2913** [comment]
I forgot to add these logs from today, which are new and only populate when I do the search.



Error | PHP | Error:&nbsp;Trying to access array offset on value of type bool at /snap/nextcloud/27920/htdocs/apps/files_external/lib/Lib/Storage/SFTP.php#335 | &nbsp; | 2021-06-01T10:06:50-0400
-- | -- | -- | -- | --
Error | PHP | Error:&nbsp;Trying to access array offset on value of type bool at /snap/nextcloud/27920/htdocs/apps/files_external/lib/Lib/Storage/SFTP.php#331 | &nbsp; | 2021-06-01T10:06:50-0400
Error | PHP | Error:&nbsp;Trying to access array offset on value of type bool at /snap/nextcloud/27920/htdocs/apps/files_external/lib/Lib/Storage/SFTP.php#335 | &nbsp; | 2021-06-01T10:06:50-0400
Error | PHP | Error:&nbsp;Trying to access array offset on value of type bool at /snap/nextcloud/27920/htdocs/apps/files_external/lib/Lib/Storage/SFTP.php#331 | &nbsp; | 2021-06-01T10:06:50-0400

**Comment by Keaters2913** [comment]
[core] Error: Doctrine\DBAL\Query\QueryException: More than 1000 expressions in a list are not allowed on Oracle. at <<closure>>

 0. /snap/nextcloud/27920/htdocs/lib/public/AppFramework/Db/QBMapper.php line 320
    OC\DB\QueryBuilder\QueryBuilder->execute()
 1. /var/snap/nextcloud/27920/nextcloud/extra-apps/mail/lib/Db/MessageMapper.php line 592
    OCP\AppFramework\Db\QBMapper->findEntities(OC\DB\QueryBuilder\QueryBuilder {})
 2. /var/snap/nextcloud/27920/nextcloud/extra-apps/mail/lib/Service/Sync/SyncService.php line 156
    OCA\Mail\Db\MessageMapper->findIdsByQuery(OCA\Mail\Db\Mailbox {id: 10}, OCA\Mail\Service\Search\SearchQuery {}, null, [2,19,21,28,35," ... "])
 3. /var/snap/nextcloud/27920/nextcloud/extra-apps/mail/lib/Service/Sync/SyncService.php line 126
    OCA\Mail\Service\Sync\SyncService->getDatabaseSyncChanges(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox {id: 10}, [], OCA\Mail\Service\Search\SearchQuery {})
 4. /var/snap/nextcloud/27920/nextcloud/extra-apps/mail/lib/Controller/MailboxesController.php line 161
    OCA\Mail\Service\Sync\SyncService->syncMailbox(OCA\Mail\Account {}, OCA\Mail\Db\Mailbox {id: 10}, 42, [], true, "is:pi-starred")
 5. /snap/nextcloud/27920/htdocs/lib/private/AppFramework/Http/Dispatcher.php line 218
    OCA\Mail\Controller\MailboxesController->sync(10, [], false, "is:pi-starred")
 6. /snap/nextcloud/27920/htdocs/lib/private/AppFramework/Http/Dispatcher.php line 127
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Mail\Control ... {}, "sync")
 7. /snap/nextcloud/27920/htdocs/lib/private/AppFramework/App.php line 157
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Control ... {}, "sync")
 8. /snap/nextcloud/27920/htdocs/lib/private/Route/Router.php line 302
    OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "sync", OC\AppFramework\ ... {}, {id: "10",_route: "mail.mailboxes.sync"})
 9. /snap/nextcloud/27920/htdocs/lib/base.php line 993
    OC\Route\Router->match("/apps/mail/api/mailboxes/10/sync")
10. /snap/nextcloud/27920/htdocs/index.php line 37
    OC::handleRequest()

POST /index.php/apps/mail/api/mailboxes/10/sync
from 192.168.1.103 by Scott at 2021-06-03T19:23:49+00:00

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

**Comment by Keaters2913** [comment]
I decided to stop using the snap version of NextCloud and I am using the Cloudron version and it has been flawless with no issues at all.  I will close this thread.
