### ISSUE TITLE
Suggestion: to give an opportunity to share files and folders inside a shared (public) link.

### ISSUE THREAD

**Issue by sosed213** [nextcloud/server#27341]
Make an analogue of file hosting without user authorization.

For example, there is a shared (public) folder where you can upload files and folders. And it would be great to be able to immediately share the downloaded file or folder, receive a direct link to the downloaded file in a public folder.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
