### ISSUE TITLE
Feature request: Nextcloud artifact action for Github Actions

### ISSUE THREAD

**Issue by trympet** [nextcloud/server#27344]
GitHub supports self-hosted runners, which allows you to leverage your own infrastructure for compute. This is great, but only for compute. GitHub does not allow for self-hosted storage nodes. This means that you can't leverage existing storage infrastructure with GitHub Actions artifacts.

Therefore, I propose a GitHub Action, akin to the artifacts action, allowing files to be uploaded and downloaded to Nextcloud, along with a shareable URL.

The proposed Nextcloud action should act such that it can effectively replace the existing artifacts action from GitHub.

I would be happy to contribute. From what I can tell, this should be pretty trivial.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by szaimen** [comment]
Hm... I am not completely sure what this feature request is about. 
cc @LukasReschke

**Comment by trympet** [comment]
Beat you to it: https://github.com/trympet/nextcloud-artifacts-action
