### ISSUE TITLE
Web Updater Fails from 20.0.09 to 20.0.10

### ISSUE THREAD

**Issue by commdogg** [nextcloud/server#27351]
Update failure with:
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_richdocuments_direct ADD share VARCHAR(64) DEFAULT NULL, ADD initiator_host VARCHAR(255) DEFAULT NULL, ADD initiator_token VARCHAR(64) DEFAULT NULL': SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

**Comment by commdogg** [comment]
Hey, thank you for looking at this, i just wanted to leave the "fix" I found here just in case:
`mysqlcheck -u nextclouduser -B nextcloud -p -o`
Whatever was up with the DB was cleared with that command and upgrade proceeded as normal.
