### ISSUE TITLE
Nextcloud tries to invoke chmod despite it already has the needed permissions, polluting the log of Operation not permitted errors

### ISSUE THREAD

**Issue by SMH17** [nextcloud/server#27363]
Nextcloud log is filled with a lot of 

`{"reqId":"someid","level":3,"time":"2021-06-03T00:02:05+00:00","remoteAddr":"...","user":"someuser","app":"PHP","method":"MKCOL","url":"/remote.php/dav/uploads/someuser/web-file-upload-somecode","chmod(): Operation not permitted at /var/www/html/nextcloud/lib/private/Log/File.php#87","userAgent"...`

these errors happen because my configuration doesn't allow the use of chmod() but actually Nextcloud has already the permissions needed to operate as supposed and the invocation of chmod() isn't a desired behavior. 

The problem is caused by 

```
		if ($this->logFileMode > 0 && is_file($this->logFile) && (fileperms($this->logFile) & 0777) != $this->logFileMode) {
			@chmod($this->logFile, $this->logFileMode);
		}
```

in `function write` of  `/lib/private/Log/File.php`

**Comment by szaimen** [comment]
cc @icewind1991

**Comment by SMH17** [comment]
What other info you need?

**Comment by szaimen** [comment]
cc @icewind1991 is it feasible to remove the mentioned code again or to only invoke it if the permissions differ?

**Comment by icewind1991** [comment]
> cc @icewind1991 is it feasible to remove the mentioned code again or to only invoke it if the permissions differ?

doing it conditionally should be fine

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
