### ISSUE TITLE
"Not enough free space" when uploading: Sometimes no freeSpace calculation

### ISSUE THREAD

**Issue by andreas-p** [nextcloud/server#27367]
Somewhere between 20.0.1 and 20.0.9, the calculation of freespace when uploading was changed.

I'm using an app that uploads to not-yet-existing directories, relying on NC creating them implicitely which works fine, unless freeSpace is not calculated (and thus 0) which happens in this case.

Previously, file-upload.js OC.FileUpload.add() would just use the global freeSpace from $('#free_space').val(). Now, freeSpace is initialized as 0, and calculated for some data scenarios. If those scenarios are not met, it will remain 0, failing the upload with "Not enough free space".

freeSpace should be initialized to the global freeSpace as before, and then recalculated for specific situations to make sure freeSpace is valid in all situations.

**Comment by szaimen** [comment]
Please post this on https://help.nextcloud.com/c/dev/11. Thanks!

**Comment by andreas-p** [comment]
@szaimen this wasn't a request for help but a bug report. I don't understand that redirect. AFAICS bugs in the files app should go here.

**Comment by szaimen** [comment]
Please post it there nonetheless. Thanks!

**Comment by andreas-p** [comment]
@szaimen would you mind to explain to me why I should post core bug reports to the developer help forum?
