### ISSUE TITLE
Error loading PNG files for viewing

### ISSUE THREAD

**Issue by variistechnologies** [nextcloud/server#27369]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.    Upload PNG files , 50Mb+ size
2.    Click to open a PNG file in “files” view
3.     Error loading file displayed

### Expected behaviour
Open PNG file for viewing

### Actual behaviour
Error displayed "Error loading_..."

### Server configuration

**Operating system:** Fedora 33

**Web server:** Apache 2.4.46

**Database:** Maria DB mariadb-3:10.4.19-1.fc33.x86_64

**PHP version:** 7.4.19

**Nextcloud version:** (see Nextcloud admin page) 21.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** no

**Where did you install Nextcloud from:** nextcloud site

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

 Accessibility
1.7.0
Featured
Activity
2.14.3
Featured
Breeze Dark
21.0.7
Brute-force settings
2.1.0
Featured
Collaborative tags
1.11.0
Featured
Comments
1.11.0
Featured
Contacts Interaction
1.2.0
Featured
Dashboard
7.1.0
Featured
Deleted files
1.11.0
Featured
Federation
1.11.0
Featured
File sharing
1.13.1
Featured
First run wizard
2.10.0
Featured
Log Reader
2.6.0
Featured
Monitoring
1.11.0
Featured
Nextcloud announcements
1.10.0
Featured
Notifications
2.9.0
Featured
Password policy
1.11.0
Featured
PDF viewer
2.1.0
Featured
Photos
1.3.0
Featured
Privacy
1.5.0
Featured
Recommendations
1.0.0
Featured
Right click
1.0.0
Featured
Share by mail
1.11.0
Featured
Support
1.4.0
Featured
Text
3.2.0
Featured
Theming
1.12.0
Featured
Update notification
1.11.0
Featured
Usage survey
1.9.0
Featured
User status
1.1.1
Featured
Versions
1.14.0
Featured
Video player
1.10.0
Featured
Weather status 

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '+r',
  'trusted_domains' => 
  array (
    0 => '10.0.0.111',
    1 => 'xxxxxxxx',
  ),
  'datadirectory' => '/p/cloud_data',
  'dbtype' => 'mysql',
  'version' => '21.0.2.1',
  'overwrite.cli.url' => 'https://10.0.0.111/nextcloud',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost:3306',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
);

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/... no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** Firefox

**Operating system:** Fedora 34

### Logs

<!--- Reports without logs might be closed as unqualified reports! -->

#### Web server error log
<details>
<summary>Web server error log</summary>

[Sun May 30 16:12:22.215246 2021] [lbmethod_heartbeat:notice] [pid 1610:tid 1610] AH02282: No slotmem from mod_heartmonitor
[Sun May 30 16:12:22.217366 2021] [mpm_event:notice] [pid 1610:tid 1610] AH00489: Apache/2.4.46 (Fedora) OpenSSL/1.1.1j configured -- 
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

"reqId":"YLe7OluunfLJfmQEkU@x0AAAAMQ","level":2,"time":"2021-06-02T17:09:14+00:00","remoteAddr":"10.0.0.201","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php","message":"Could not detect any host in https:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0","version":""}
{"reqId":"YLe7OluunfLJfmQEkU@x0AAAAMQ","level":2,"time":"2021-06-02T17:09:14+00:00","remoteAddr":"10.0.0.201","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/index.php","message":"Could not detect any host in http:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0","version":""}
{"reqId":"YLe8BFuunfLJfmQEkU@x1QAAAMs","level":2,"time":"2021-06-02T17:12:36+00:00","remoteAddr":"10.0.0.201","user":"--","app":"no app in context","method":"POST","url":"/nextcloud/index.php","message":"Could not detect any host in https:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0","version":""}
{"reqId":"YLe8BFuunfLJfmQEkU@x1QAAAMs","level":2,"time":"2021-06-02T17:12:36+00:00","remoteAddr":"10.0.0.201","user":"--","app":"no app in context","method":"POST","url":"/nextcloud/index.php","message":"Could not detect any host in http:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0","version":""}
{"reqId":"YLe9MobQglCsOjj@WC@QbwAAAI4","level":2,"time":"2021-06-02T17:17:38+00:00","remoteAddr":"10.0.0.201","user":"--","app":"no app in context","method":"POST","url":"/nextcloud/index.php","message":"Could not detect any host in https:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0","version":""}
{"reqId":"YLe9MobQglCsOjj@WC@QbwAAAI4","level":2,"time":"2021-06-02T17:17:38+00:00","remoteAddr":"10.0.0.201","user":"--","app":"no app in context","method":"POST","url":"/nextcloud/index.php","message":"Could not detect any host in http:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0","version":""}

</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 244 globals.js:60:15
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 9 globals.js:60:15
Opening viewer for file  /Photos/Pavel's photos/2020/_DSC0072.png Viewer.vue:273
XHRPROPFINDhttps://www.dropme.email/nextcloud/remote.php/dav/files/admin/Photos/Pavel's%20photos/2020/_DSC0072.png
[HTTP/1.1 207 Multi-Status 308ms]

jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 264 globals.js:60:15
XHRPROPFINDhttps://www.dropme.email/nextcloud/remote.php/dav/files/admin/Photos/Pavel's%20photos/2020/
[HTTP/1.1 207 Multi-Status 277ms]

GEThttps://www.dropme.email/nextcloud/index.php/core/preview?fileId=974&x=3072&y=1728&a=true
[HTTP/1.1 404 Not Found 290ms]

GEThttps://www.dropme.email/nextcloud/index.php/core/preview?fileId=1025&x=3072&y=1728&a=true
[HTTP/1.1 404 Not Found 494ms]

GEThttps://www.dropme.email/nextcloud/index.php/core/preview?fileId=1046&x=3072&y=1728&a=true
[HTTP/1.1 404 Not Found 581ms]

Error loading /Photos/Paul's photos/2020/_DSC0061.png 
error { target: img.viewer__file--hidden.viewer__file, isTrusted: true, srcElement: img.viewer__file--hidden.viewer__file, currentTarget: img.viewer__file--hidden.viewer__file, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
Mime.js:127:11
Error loading /Photos/Paul's photos/2020/_DSC0072.png 
error { target: img.viewer__file.viewer__file--active, isTrusted: true, srcElement: img.viewer__file.viewer__file--active, currentTarget: img.viewer__file.viewer__file--active, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
Mime.js:127:11
Error loading /Photos/Paul's photos/2020/_DSC0073.png 
error { target: img.viewer__file--hidden.viewer__file, isTrusted: true, srcElement: img.viewer__file--hidden.viewer__file, currentTarget: img.viewer__file--hidden.viewer__file, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
Mime.js:127:11
    mounted Mime.js:127
    (Async: EventListener.handleEvent)
    mounted Mime.js:126
    VueJS 19
    e Viewer.vue:424
    A runtime.js:63
    _invoke runtime.js:293
    v runtime.js:118
    k viewer-main.js:14
    a viewer-main.js:14
    (Async: promise callback)
    k viewer-main.js:14
    a viewer-main.js:14
    (Async: promise callback)
    k viewer-main.js:14
    a viewer-main.js:14
    S viewer-main.js:14
    S viewer-main.js:14
    openFile Viewer.vue:349
    file Viewer.vue:274
    VueJS 10
    value Viewer.js:137
    default FilesActionHandler.js:36
    action merged-index.js:2961
    _onClickFile merged-index.js:4832
    Underscore 3
    jQuery 2
XHRGEThttps://www.dropme.email/nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications
[HTTP/1.1 304 Not Modified 251ms]

OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 84 util.js:133:11
XHRPUThttps://www.dropme.email/nextcloud/index.php/apps/user_status/heartbeat
[HTTP/1.1 204 No Content 373ms]

XHRGEThttps://www.dropme.email/nextcloud/ocs/v2.php/apps/user_status/api/v1/user_status
[HTTP/1.1 200 OK 48ms]

XHRGEThttps://www.dropme.email/nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications
[HTTP/1.1 304 Not Modified 66ms]

OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 84 util.js:133:11

```
</details>

**Comment by szaimen** [comment]
https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=preview#previews
![image](https://user-images.githubusercontent.com/42591237/124757080-830b2480-df2d-11eb-9946-3b4fb5d52e50.png)
