### ISSUE TITLE
Nextcloud files_sharing app ignores url returned from OCS shares API

### ISSUE THREAD

**Issue by brucealthompson** [nextcloud/server#27364]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Background
This bug was found through code inspection and testing of the Nextcloud web front end as well as the Nextcloud desktop application.

The php code in the server files_sharing app includes a URL which is returned as part of the OCS files_sharing API. The php code is in the formatShare() function in apps/files_sharing/lib/Controller/ShareAPIController.php. The URL is returned in the 'url' element of the array returned by the formatShare() function.  

### Expected behaviour
The Nextcloud desktop application provides expected behavior.

The Nextcloud desktop application correctly returns the url value returned from the files_sharing API when a share link is provided to a user via the Nextcloud sharing window of the desktop application.

### Actual behaviour
The Nextcloud web front end (javascript) exhibits a different (incorrect) behavior from the Nextcloud desktop application.

The Nextcloud web front end ignores the url value returned from the files_sharing API and instead returns a URL which is created from the 'token' value returned from the files_sharing API.

My guess is that the behavior of the Nextcloud web front end is a holdover from previous releases of Nextcloud and has not yet been updated. Unfortunately, this means that the Nextcloud web front end now behaves differently than the Nextcloud desktop application.

### Server configuration

**Operating system:** Debian

**Web server:** Nginx

**Database:** mysql

**PHP version:** 7.3

**Nextcloud version:** (see Nextcloud admin page) 21.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Nextcloud repository

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by brucealthompson** [comment]
Good news!!!

I have fixed this issue in my Nextcloud implementation which is based on 21.0.0. Since no one seems interested in this issue, I will leave this as a private fix for now.

If anyone is interested in applying this fix to the Nextcloud trunk, I would be happy to share the fix.

**Comment by szaimen** [comment]
If you think that this feature is interesting for anyone, feel free to open a PR with your patch. Thanks! :)

**Comment by brucealthompson** [comment]
I assume "PR" stands for "Patch Request". I have no idea what the "PR" process is for Nextcloud.

**Comment by szaimen** [comment]
No, it stands for Pull Request:
https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by brucealthompson** [comment]
I have modified the apps in Nextcloud 21.0.0 for this feature. I have taken a quick look at the trunk code for these same apps and it looks quite different. If anyone wants to take my code and update /test it for the trunk, they are more than welcome to do so.
