### ISSUE TITLE
Destroyed configuration when quota reached

### ISSUE THREAD

**Issue by Sgt-Nukem** [nextcloud/server#27377]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Logging in to NextCloud instance while the personal disk quota (that of the Linux server!) has been reached.

### Expected behaviour
A page denying the login and displaying a message like "Unable to create temporary files. Unable to proceed. Please ask your Server Administrator to free up some space."

### Actual behaviour
1. A page appears "It looks like you are trying to reinstall your Nextcloud" (meanwhile the config has been destroyed)
2. GOTO 1.

### Server configuration

Shared & Managed CentOS 7 Server, Apache, PHP 7.4, MariaDB

### Details

After logging into the Linux server and quickly finding the culprit (because bash completions complain about no space in /tmp -- so no write access anymore because the quota had been reached) I deleted old NextCloud backups to free up 3 GB of space again (*).

**--> The problem remained.**

I looked at `config.php` to realize it had been reinitalized - it was a mostly empty file with only a (newly generated) `instanceID`.

### Solution:
After fetching my old `config.php` from the backup (thank the gods!), everything was working again.

### Expected behaviour
As Adminstrator in Settings (where the update check occurs) have something like:
`"There are 7 backups from previous NextCloud updates, 4 of which are at least 2 major versions back or more than 6 months old. Do you want to delete them now to free up 3.67 GiB?"`

**Comment by acsfer** [comment]
Similar to https://github.com/nextcloud/server/issues/18973 and https://github.com/nextcloud/server/issues/19829

**Comment by szaimen** [comment]
Seems like it doesn't happen anymore since the other affected ones closed their issue.
@Sgt-Nukem are you still able to reproduce this on NC21.0.3?

**Comment by Sgt-Nukem** [comment]
> Similar to #18973 and #19829

FYI: My problem didn't occur during an upgrade, but just between two regular logins in the browser (maybe ~1 week apart).
(The quota got exceeded by other processes on the server meanwhile.)





> Seems like it doesn't happen anymore since the other affected ones closed their issue.
> @Sgt-Nukem are you still able to reproduce this on NC21.0.3?

I'm very relucatant to try to reproduce this as I was shocked my whole NC content was lost. 😱

I'm at 21.0.3 now and have just a couple gigs left. So maybe it will manifest itself on one of the next upgrades because of the big NC backups.
