### ISSUE TITLE
sftp external storage broken with "No compatible server host key algorithms found"

### ISSUE THREAD

**Issue by jgoerzen** [nextcloud/server#27397]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Attempt to set up an external storage with rsync.net at a SFTP destination
2. It shows login failure in the GUI.
3. Server log shows Error: No compatible server host key algorithms found at /var/www/owncloud/3rdparty/phpseclib/phpseclib/phpseclib/Net/SSH2.php#1551

### Expected behaviour

External storage should be established.

### Actual behaviour

It is unable to establish the SSH link.

### Server configuration

**Operating system:**

Linux

**Web server:**

Apache
**Database:**
Mysql
**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

21.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated
**Where did you install Nextcloud from:**
Nextcloud.com
**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

sftp

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no
### Client configuration
**Browser:**
Firefox
**Operating system:**
Linux
### Logs

See above

### See Also

This Owncloud bug looks very similar:

https://github.com/owncloud/core/issues/38353

**Comment by szaimen** [comment]
I suppose this is still valid on NC21.0.3?

**Comment by jgoerzen** [comment]
Yes, it is.  Thanks.

**Comment by szaimen** [comment]
cc @icewind1991

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
