### ISSUE TITLE
Unified search: "Load more options" not working when "in:" filter is used (for some apps)

### ISSUE THREAD

**Issue by ruedigerkupper** [nextcloud/server#27400]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Search for anything, e.g.: go to the files app and search for "a"
2. Search box will show the first five results, both for "files" and for "calendar" (and possibly other apps)
3. Click "load more results" below the file results and observe that it loads more results. (The same works for "calendar" results.)
4. Add "in:files", "in:calendar" or "in:notes", or click the three-dot menu next to the search box and select the respective type.
5. Search box shows first five results of the selected type.
6. Click "load more results" below the results.
7. Observe that *nothing happens*, the "load more results" string simply disappears, no more results are shown.

### Expected behaviour
"Load more results" should load and display more results of the selected type.

### Actual behaviour
The "load more results" string simply disappears, no more results are shown.

Interestingly, it works as it should for some types/apps, for example: "in:audioplayer" works fine.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

**Comment by ruedigerkupper** [comment]
Sorry, still on 21.0.1 (NC snap).
Can anyone test with 21.0.3? Thanks!

**Comment by ruedigerkupper** [comment]
The problem is still present exactly as described above in NC 21.0.3. Do not close!

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
