### ISSUE TITLE
Calendar app: internal server error after upgrading to Nextcloud 11

### ISSUE THREAD

**Issue by BenS89** [nextcloud/server#2741]
**Steps to reproduce:**

 - Use calendar app 1.4.1 with Nextcloud 10
- Upgrade to Nextcloud 11.0
- Re-Activate the Calendar App within the new App Store
- Open the Calendar App

**Expected behavior:**
The calendars created with the calendar app in Nextcloud 10 are loaded without any errors. 

**Actual behaviour:**
The Chrome and Firefox consoles print an internal server error when existing calendars are loaded. The Nextcloud log says:

`{"reqId":"hZjDhApmqGjwQIX\/MvRp","remoteAddr":"87.xxx.xxx.xxx","app":"webdav","message":"Exception: {\"Message\":\"Unsupported VALUE parameter for DTEND property. You supplied \\\"\\\"\",\"Exception\":\"Sabre\\\\VObject\\\\InvalidDataException\",\"Code\":0,\"Trace\":\"#0 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(453): Sabre\\\\VObject\\\\Document->createProperty('DTEND', NULL, Array)\\n#1 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(234): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readProperty('DTEND;TZID=Euro...')\\n#2 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(217): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine('DTEND;TZID=Euro...')\\n#3 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(181): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine('DTEND;TZID=Euro...')\\n#4 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(89): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#5 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(46): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse('BEGIN:VCALENDAR...', 0)\\n#6 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Backend\\\/AbstractBackend.php(142): Sabre\\\\VObject\\\\Reader::read('BEGIN:VCALENDAR...')\\n#7 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/CalDavBackend.php(1123): Sabre\\\\CalDAV\\\\Backend\\\\AbstractBackend->validateFilterForObject(Array, Array)\\n#8 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/Calendar.php(248): OCA\\\\DAV\\\\CalDAV\\\\CalDavBackend->calendarQuery('1', Array)\\n#9 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(624): OCA\\\\DAV\\\\CalDAV\\\\Calendar->calendarQuery(Array)\\n#10 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(250): Sabre\\\\CalDAV\\\\Plugin->calendarQueryReport(Object(Sabre\\\\CalDAV\\\\Xml\\\\Request\\\\CalendarQueryReport))\\n#11 [internal function]: Sabre\\\\CalDAV\\\\Plugin->report('{urn:ietf:param...', Object(Sabre\\\\CalDAV\\\\Xml\\\\Request\\\\CalendarQueryReport), 'calendars\\\/Ben\\\/o...')\\n#12 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#13 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(718): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#14 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#15 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#16 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#17 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#18 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Server.php(227): Sabre\\\\DAV\\\\Server->exec()\\n#19 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#20 \\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/remote.php(165): require_once('\\\/share\\\/MD0_DATA...')\\n#21 {main}\",\"File\":\"\\\/share\\\/MD0_DATA\\\/htdocs\\\/owncloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Document.php\",\"Line\":220,\"User\":\"Ben\"}","level":4,"time":"2016-12-18T21:09:06+00:00","method":"REPORT","url":"\/owncloud\/remote.php\/dav\/calendars\/Ben\/owncloudkalender\/","user":"Ben","version":"11.0.0.10"}`

Enabled apps:
Calendar 	1.4.1
Contacts 1.5.2

PHP-Version: 7.0.5
OS: Embedded QNAP-Linux

**Comment by nickvergessen** [comment]
Ref @rullzer https://github.com/nextcloud/server/pull/2273

**Comment by rullzer** [comment]
Yes *should*(tm) be fixed with #2273

**Comment by BenS89** [comment]
Is there a possibility to run this fix manually? Since there are many calendars which are currently broken, we cannot really wait until the next update comes.

**Comment by BenS89** [comment]
Error is still present in 11.0.1

**Comment by llamallama** [comment]
Error is still present in 11.0.2.

**Comment by rullzer** [comment]
Can you check your oc_jobs table to see if the `ValueFix` job is still in there?

**Comment by Ecphrasis** [comment]
Same problem here : 

- Nextcloud 11.0.2, calendars 1.5.1 and all programs up to date on ubuntu 16.04.1 (apache, mysql-server, etc.).
- Calendars are displayed and synchronized correctly, only the export fail, with this error message : 

`{"reqId":"xOCJnBzuRH\/CVlYiLPh9","remoteAddr":"88.xxx.xxx.xxx","app":"webdav","message":"Exception: {\"Message\":\"Unsupported VALUE parameter for DTEND property. You supplied \\\"\\\"\",\"Exception\":\"Sabre\\\\VObject\\\\InvalidDataException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(453): Sabre\\\\VObject\\\\Document->createProperty('DTEND', NULL, Array)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(234): Sabre\\\\VObject\\\\Parser\\\\MimeDir->readProperty('DTEND;VALUE=:20...')\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(217): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine('DTEND;VALUE=:20...')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(181): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseLine('DTEND;VALUE=:20...')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Parser\\\/MimeDir.php(89): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parseDocument()\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Reader.php(46): Sabre\\\\VObject\\\\Parser\\\\MimeDir->parse('BEGIN:VCALENDAR...', 0)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/ICSExportPlugin.php(307): Sabre\\\\VObject\\\\Reader::read('BEGIN:VCALENDAR...')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/ICSExportPlugin.php(222): Sabre\\\\CalDAV\\\\ICSExportPlugin->mergeObjects(Array, Array)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/ICSExportPlugin.php(151): Sabre\\\\CalDAV\\\\ICSExportPlugin->generateResponse('public-calendar...', NULL, NULL, false, false, 'text\\\/calendar', Array, Object(Sabre\\\\HTTP\\\\Response))\\n#9 [internal function]: Sabre\\\\CalDAV\\\\ICSExportPlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#11 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#12 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#13 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(227): Sabre\\\\DAV\\\\Server->exec()\\n#14 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#15 \\\/var\\\/www\\\/nextcloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/nextcl...')\\n#16 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/vobject\\\/lib\\\/Document.php\",\"Line\":220,\"User\":false}","level":4,"time":"2017-03-18T15:38:44+01:00","method":"GET","url":"\/remote.php\/dav\/public-calendars\/FVCLM447HOAOC0RW?export","user":"--","version":"11.0.2.7"}`

- this is a screenshot of my oc_jobs table, I don't know very well mysql, so I prefer screenshot ;)
![sans titre](https://cloud.githubusercontent.com/assets/11899009/24073107/27798c14-0bf2-11e7-9604-0eea2bc11aa2.png)

**Comment by nickvergessen** [comment]
I think we need to run this job again explicitly, or add a repairstep or something.

**Comment by rullzer** [comment]
I could maybe add it as an OCC command
