### ISSUE TITLE
SMB Connection buggy

### ISSUE THREAD

**Issue by ManOki** [nextcloud/server#27425]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Setup an external SMB share
2. Start Download in WebUI
3. Stop Download after some seconds

### Expected behaviour
As the Download from nextcloud to the user stops, the download from SMB share to nextcloud should also stop.

### Actual behaviour
Nextcloud server keeps downloading the file from the SMB share.

### Server configuration

**Operating system:** Debian Buster

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.

**Nextcloud version:** 21.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** https://github.com/nextcloud/docker

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Are you using external storage, if yes which one:** SMB

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 89.0

**Operating system:** Windows 10

**Comment by ManOki** [comment]
Especially, if the file is very large, this may use the whole network capacity of the nextcloud server for a long time. (I don't know, if there is a cache or the file is discarded right after the download from the SMB server)

Same for SFTP connections: #5668

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/viewer/issues/894 
(is probably the same underlaying issue)

**Comment by ManOki** [comment]
@szaimen This should be reopened like #5668 .

**Comment by szaimen** [comment]
No, for this one I am sure.

**Comment by ManOki** [comment]
What makes you so sure?

The other tickets is a viewer ticket, I don't even use the viewer. Likewise, the other ticket does not use/mention an SMB connection which is the main issue in this ticket.
