### ISSUE TITLE
refresh main.js will not reload /apps/onlyoffice/ajax/settings 

### ISSUE THREAD

**Issue by feizhoulv** [nextcloud/server#27434]
### Steps to reproduce
1.  use nextcloud 20.0.2 with onlyoffice installed
2.  open directory that contains  *.docx, the doc file url should be  **[/index.php/apps/files?dir=/abc.docx]**， and editable.
3.  refresh page, the doc url changed to **[/remote.php/webdav/abc.docx]** and can't edit.
4.  disable cache then refresh page,   docs can edit again, and url changed back.

### Expected behaviour
when refresh page the doc url should always be **[/index.php/apps/files?dir=/abc.docx]**

### Actual behaviour
when main.js loaded from browsers memory cache ，it will not reload [/apps/onlyoffice/ajax/settings] ，then docs can't edit.

**Comment by szaimen** [comment]
Seems like this was solved in https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/484
