### ISSUE TITLE
Create group doesn't work (22.0.0 beta3)

### ISSUE THREAD

**Issue by StCyr** [nextcloud/server#27435]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Go to Users menu
2. Click button "+ Add Group"
3. Nothing happens

### Expected behaviour
NC should prompt me for the group's name

### Actual behaviour
Nothing happens

### Additionnal info

Creating the group using occ works well

### Server configuration

**Operating system:** Debian 

**Web server:** Apache 

**Database:** Mysql

**PHP version:** 7.3

**Nextcloud version:** master

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

Can't get the result, page returns "Integrity checker has been disabled. Integrity cannot be verified." even if I put `'integrity.check.disabled' => false` or `'integrity_check_disabled' => false,` in config.php. Another bug?
```

**List of activated apps:**
<details>
<summary>
Enabled:
  - accessibility: 1.7.0
  - calendar: 2.2.2
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.18.0
  - deck: 2.0.0-alpha1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_sharing: 1.13.2
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - groupfolders: 10.0.2
  - lookup_server_connector: 1.9.0
  - mail: 1.10.0-alpha.6
  - notestutorial: 18.0.0
  - oauth2: 1.9.0
  - provisioning_api: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - systemtags: 1.11.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.1
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.6.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
  - workspace: 0.0.10
Disabled:
  - admin_audit
  - bruteforcesettings
  - circles
  - encryption
  - files_external
  - files_texteditor
  - impersonate
  - testing
  - user_ldap
</summary>
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud-dev.bollu.be",
            "192.168.0.128",
            "127.0.0.1"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.0.0.6",
        "overwrite.cli.url": "http:\/\/nextcloud-dev.bollu.be",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "log_type": "syslog",
        "logfile": "",
        "loglevel": 0,
        "maintenance": false,
        "debug": true,
        "allow_local_remote_servers": true,
        "integrity.check.disabled": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox latest 89.0 64bits

**Operating system:** Windows 10

### Logs

There is no single log. Nothing happens when I click on the button: The browser's console doesn't output anything and no request is sent to the server.

**Comment by GogoFC** [comment]
This is now back on my version 27 install.
