### ISSUE TITLE
Personal Settings - User cannot change language. Missing file.

### ISSUE THREAD

**Issue by Seba0917** [nextcloud/server#2743]
### Steps to reproduce
1. Do a fresh install using https://download.nextcloud.com/server/releases/nextcloud-11.0.0.zip
2. Go to 'settings' and change the language

### Expected behaviour
It should change the language.

### Actual behaviour
Error 404 on the XHR request : settings/ajax/setlanguage.php not found.

### But wait, there's more !

The file settings/ajax/setlanguage.php is not present in the repository, even though it is referenced in /settings/js/personal.js. @line 221

**Comment by schiessle** [comment]
> The file settings/ajax/setlanguage.php is not present in the repository, even though it is referenced in /settings/js/personal.js. @line 221

The route is defined here: https://github.com/nextcloud/server/blob/stable11/settings/routes.php#L71 So changing language should call "setLanguage()" in settings/Controller/PersonalController.php

I tried it and I can't reproduce it. Do you have any additional information in your nextcloud.log, apache error log or the network console of your browser?

**Comment by schiessle** [comment]
Please also check if settings/Controller/PersonalController.php exists? If you uploaded it by FTP it might be possible that the connection timed out before the upload was finished.

**Comment by Seba0917** [comment]
Hello, 

For another reason I have replaced my nginx configuration and this problem does exists anymore. 

Thank you for your interest and sorry for this late answer and the waste of time !

**Comment by DerEnderKeks** [comment]
I've got the same problem. https://keks.cf/GoS5c3HZ.png
I use the nginx config example from https://docs.nextcloud.com/server/11/admin_manual/installation/nginx_nextcloud_9x.html
Nextcloud 11.0.1.

**Comment by aTanCS** [comment]
11.0.2 release archive also doesn't contain /settings/ajax/setlanguage.php so it is not possible to change language.

**Comment by schiessle** [comment]
> 11.0.2 release archive also doesn't contain /settings/ajax/setlanguage.php so it is not possible to change language.

As said here https://github.com/nextcloud/server/issues/2743#issuecomment-267924546 this is just the route, not a path to the physical file. It should call "setLanguage()" in settings/Controller/PersonalController.php

**Comment by aTanCS** [comment]
Sorry, I didn't read it before posting. There is the route in routes.php, no error in NC log, 404 in nginx. Here is additonal nginx settings I've used. Maybe there is something wrong with it.
```
add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
add_header X-Content-Type-Options nosniff;
add_header X-Frame-Options "SAMEORIGIN";
add_header X-XSS-Protection "1; mode=block";
add_header X-Robots-Tag none;
add_header X-Download-Options noopen;
add_header X-Permitted-Cross-Domain-Policies none;
location = /robots.txt {
log_not_found off;
allow all;
access_log off;
}
# The following 2 rules are only needed for the user_webfinger app.
# Uncomment it if you're planning to use this app.
#rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
#rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json
# last;
location = /.well-known/carddav {
return 301 $scheme://$host/remote.php/dav;
}
location = /.well-known/caldav {
return 301 $scheme://$host/remote.php/dav;
}
# set max upload size
client_max_body_size 50G;
fastcgi_buffers 64 4K;
# Disable gzip to avoid the removal of the ETag header
gzip off;
# Uncomment if your server is build with the ngx_pagespeed module
# This module is currently not supported.
#pagespeed off;
error_page 403 /core/templates/403.php;
error_page 404 /core/templates/404.php;
location / {
rewrite ^ /index.php$uri;
}
location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
deny all;
}
location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) {
deny all;
}
location ~ ^/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+|core/templates/40[34])\.php(?:$|/) {
fastcgi_split_path_info ^(.+\.php)(/.*)$;
include fastcgi_params;
fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
fastcgi_param PATH_INFO $fastcgi_path_info;
fastcgi_param HTTPS on;
#Avoid sending the security headers twice
fastcgi_param modHeadersAvailable true;
fastcgi_param front_controller_active true;
fastcgi_pass $socket;
fastcgi_intercept_errors on;
}
location ~ ^/(?:updater|ocs-provider)(?:$|/) {
try_files $uri/ =404;
index index.php;
}
# Adding the cache control header for js and css files
# Make sure it is BELOW the PHP block
location ~* \.(?:css|js|woff|svg|gif)$ {
try_files $uri /index.php$uri$is_args$args;
add_header Cache-Control "public, max-age=7200";
add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
add_header X-Content-Type-Options nosniff;
add_header X-Frame-Options "SAMEORIGIN";
add_header X-XSS-Protection "1; mode=block";
add_header X-Robots-Tag none;
add_header X-Download-Options noopen;
add_header X-Permitted-Cross-Domain-Policies none;
# Optional: Don't log access to assets
access_log off;
}
location ~* \.(?:png|html|ttf|ico|jpg|jpeg)$ {
try_files $uri /index.php$uri$is_args$args;
# Optional: Don't log access to other assets
access_log off;
}
```
