### ISSUE TITLE
Tolerate, but do not follow symlinks in local external storage by default

### ISSUE THREAD

**Issue by haarp** [nextcloud/server#27448]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

Hello,

I've recently had the pleasure of dealing with external storages. To my surprise, Nextcloud completely chokes once it encounters even a single symlink in local external storages. Now I understand that symlinks are not to be followed for security reasons and wholeheartedly agree. That decision can be seen in #1257.

However, refusing to work at all with such storage at all is a horrible solution. In my use case, I do not even care about the symlinks! Deleting all symlinks is a bad workaround and often not an option anyway.

The only other workaround is to enable symlinks globally via `localstorage.allowsymlinks`, as per #24606. This is of course a possible security risk and should be avoided. Especially when you don't even care about the symlinks. Plus it can result in other poblems, such as infinite recursion, which Nextcloud doesn't handle well.

I'd like to propose that Nextcloud simply treat symlinks as files (when `localstorage.allowsymlinks` is disabled). Downloading the symlink would yield a text file with the symlink target as content. This way, security is not a problem and local external storages with symlinks can still be used, albeit with possibly reduced functionality (depending on the use case).

Thanks a lot!

**Comment by szaimen** [comment]
Duplicate of https://github.com/nextcloud/server/issues/22040

**Comment by haarp** [comment]
Not a duplicate. #22040 just got closed, stating the possibility to allow symlinks. However, this follows symlinks, which isn't what I'm proposing here.

**Comment by szaimen** [comment]
Sry but this feature request doesn't fit our roadmap.
