### ISSUE TITLE
[Feature Request] As admin get list of used clients by users

### ISSUE THREAD

**Issue by ThaDaVos** [nextcloud/server#27447]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Partially, there is a know issue with the older Nextcloud Desktop clients (https://github.com/nextcloud/desktop/issues/2593) which causes the Nextcloud Server to freeze up/get overloaded. The fix is simple, update all the clients to the latest version and the issue should be gone. The problem: We have 50+ users using our Nextcloud Server and to fix this, it will be cumbersome to go through each user's X amount of devices to make sure they are all using the latest client version.

**Describe the solution you'd like**
One of the following:
1. A overview page (admin only) to see what client versions are used by who
2. A command line utility, probably `occ` related to get the same overview but through command line
3. An option on the user list page to get a summary of the user, including the used devices + versions without the need to impersonate them

**Describe alternatives you've considered**
Still looking through the data model inside the database to check if something like this is even stored and manually pulling the data out through MySQL queries

**Additional context**
https://github.com/nextcloud/desktop/issues/2593

**Comment by szaimen** [comment]
Hi 👋

We are currently cleaning up our issue tracker. The feature described in this issues sounds like a good idea for a dedicated app. Feel free to post it in our "App ideas" section in the forum, to find a developer that wants to work on it:
https://help.nextcloud.com/c/apps/app-ideas/21

We are closing this issue here now, so the "issue tracker" of the server repository can be used better to track issues instead.

Cheers
