### ISSUE TITLE
Error occurred whilst checking server setup

### ISSUE THREAD

**Issue by dariomkd5** [nextcloud/server#27453]
![bug](https://user-images.githubusercontent.com/85167787/121485660-b14e2080-c9d0-11eb-8e8e-7af7f521b109.PNG)
Some of the php files from the log doesn't exist in my system, one of them is this DataTimeFormater.php.
![image](https://user-images.githubusercontent.com/85167787/121486833-c8d9d900-c9d1-11eb-8eae-68e8c17b806a.png)
![image](https://user-images.githubusercontent.com/85167787/121486894-dc853f80-c9d1-11eb-999f-60837b457607.png)

**Comment by szaimen** [comment]
Hi, please fill out the issue template. Thanks!
