### ISSUE TITLE
Webdav mount no created date

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/server#27461]
### Steps to reproduce
1 Mount webdav with windows or linux
2 Print properties

### Server configuration

**Operating system:** Red hat 7 / Debian 10 

**Web server:** apache2 

**Database:** Mariadb

**PHP version:** php-7.3,7.4

**Nextcloud version:**  21.X 20.

Linux : 
![image](https://user-images.githubusercontent.com/38983960/121533792-e8d4c100-ca00-11eb-8555-c480226f66ff.png)
Windows
![image](https://user-images.githubusercontent.com/38983960/121533857-f8eca080-ca00-11eb-9913-645b248fa095.png)

`

**Comment by tanguy-opendsi** [comment]
> Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

Hi yes this issue still valid also in NC22

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
