### ISSUE TITLE
Mail activity use username/groupname  insted of displayname

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/server#27460]
### Steps to reproduce
1. share files, remove user from groups (generate activity)

### Expected behaviour
 use displayname in mail activity 

### Actual behaviour
The username/groupname is used

### Server configuration

**PHP version:** 7.3 

**Nextcloud version:** 20.0.8

We use OPENID, but same issue with LDAP/SAML 

![image](https://user-images.githubusercontent.com/38983960/121508415-db5e0d80-c9e5-11eb-8d90-b4a3b3b5cc30.png)

Exemple of received mail : 

```

Bonjour XXXX,
 Il y a eu de l'activité sur Plateforme  XXXX
Aujourd’hui 07:17
c4d96a06b7_mimo_service_account vous a retiré du groupe c4d96a06b7_!VVufBxjNJAiLdkXovX:domain.XXX
```

What we want : 
```

Bonjour XXXX,
 Il y a eu de l'activité sur Plateforme  XXXX
Aujourd’hui 07:17
MiMo vous a retiré du groupe Gestion-Projet-2
```
As you can see, it's not user friendly

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

**Comment by tanguy-opendsi** [comment]
> Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

Yes this issue still valid

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
