### ISSUE TITLE
Disable download during on click to prevent accidental downloads of sensitive files

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/server#27462]
Hi.

For some usage download file without prompt is dangerous.

On Edge or Chrome for example 

Ofc we can config Chrome or Edge but by default it's dangerous. 

Best regards

**Comment by szaimen** [comment]
Hi there, 
unfortunately I don't understand this feature request. Please paraphrase your idea and provide some screenshots what this issue is about.
Thanks!

**Comment by tanguy-opendsi** [comment]
Hi :) 
Disable file download when click on filename, or prompt message like "do you want download NAMEFILE" ?

**Comment by szaimen** [comment]
> Disable file download when click on filename, or prompt message like "do you want download NAMEFILE" ?

cc @nextcloud/designers does this make sense and is it feasible?

**Comment by raimund-schluessler** [comment]
I think this is more of a browser issue. E.g. Firefox by default asks before downloading, so having an additional prompt from Nextcloud would lead to a double confirmation necessary.

And downloading sensitive data to a device is only an issue, if you don't trust the device you use (maybe a public PC). But then accessing your Nextcloud instance by putting your password there could already compromise your instance. So I don't see any benefit from having a confirmation before downloading.

**Comment by szaimen** [comment]
Thanks for the feedback! Based on this I am closing this issue. 

@tanguy-opendsi thanks for the idea, though!

**Comment by tanguy-opendsi** [comment]
@szaimen your welcome

i undersand double confirmation issue
An other possibility is to disable this feature and the user need to user other way for dowloading file. 

If it's possible to add in config.php or admin menu feature like disable on click download will be gr8

Best regards
