### ISSUE TITLE
Apps should be able to register custom domain

### ISSUE THREAD

**Issue by cm-t** [nextcloud/server#27473]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

When i I use PicoCMS, I want to add a custom url (CNAME for eg) for a site using automatic configuration, means i must technically know what config in what file i must edit and i have to know if it affect any automatic (Nextcloud image based on ubuntu core/snap) updates. I feels i can't be 'just' a user, but a sysadmin.
Moreover you currently have to add the CNAME in the trusted hostname of Nextcloud while i'm sure we could dodge this.

** **

**Describe the solution you'd like**

Provide for apps (in my case PicoCMS for Nextcloud) a way to add sub route of the node to be join-able by another (sub/parent)domain name; and it won't break with any update or anything unsecure would happend _(it's better if it is done by upstream rather anyone do something manualy)_. 

I didn't find another apps that need this, but i guess we could see new apps appearing such as:
 * an app that allow to share a public file under another domain name such as ` share.my.dn`/fileID
 * an app that allow building shortUrl / redirecUrl under another domain name such as `linkto.my.dn`/CustomUrl
 * an app that allow users to share a basic public profil under antoher domain name such as`me.my.dn`/username 
 * sky is the limit ?
Basicly the custom CNAME would be an alias to `index.php/apps/app_name/optionnal_subfolder`. The optionnal_subfolder is important for the PicoCMS app for Nextcloud. 

And an app could register many CNAME (especialy in the PicoCMS case, see 'additional context'), not just one, so it's not just a manifest file in the build of the app file I think, but a callable thing.

**Describe alternatives you've considered**

I don't have alternative, except a suggestion like it doesn't need to be working on all kind of Nextcloud installation (at least, in the beginning). for example, it could support at first, the snap/ubuntu core image since all the settings are known in the Nextcloud context.
I think apps should not themself modify the settings, but apps could ask Nextcloud to do so. Nextcloud could say no if the setting are not on its control _(for eg: a custom install environment)_ or because it is in conflict _(this app or another already registered a path with this domain)_.

Edit: an alternative would be _(could be temporary or not)_ having a documentation section about how to do this manually. The snippets that can be found on this topic for nextcloud are often partial, not working, not suggesting to backup the original/current and working config file, and impacts of doing it; and moreover they do not even name the files themselves and their path. I guess having a howTo for nextcloud on snap/ubuntu core image would be a great start ?

**Additional context**

 * PicoCMS for Nextcloud [road to 1.1](https://github.com/nextcloud/cms_pico/pull/99) is mentionning this feature but it seems it might need something from the server itself to allow this.
  * There is an issue from PicoCMS explaining the need [here: #83](https://github.com/nextcloud/cms_pico/issues/83) (some apache/nginx snippet are posted or linked)
  * Here a basic use case context:
      * I have my `nextcloud.my.dn`
      * I have a picoCMS site i wish it was at the root: `my.dn`
      * and I have another site i wish it was at: `blog.my.dn` 
      * In PicoCMS for Nextcloud apps config, i should be able to set the CNAME (that i have already registered on DNS) to this or that site _(this is something to implemented from the PicoCMS for Nextcloud side, it could looks like the actual settings page with 1 more radio option followed by a text field for the CNAME, [see this comment](https://github.com/nextcloud/cms_pico/issues/83#issuecomment-787962900) )_
      * And pico will tells Nextcloud my wish, and Nextcloud will update its settings and it won't break with any update or anything unsecure would happend.
      * Something cool too would be that launching `sudo nextcloud.enable-https lets-encrypt` and typing `nextcloud.my.dn my.dn blog.my.dn` at the domain list prompt, will works. _(I'm almost sure we could open a new issue feature request to have this callable from the admin panel, with hooks to apply it everytime a domain is added, or even safer, push a notification to make the admin confirm/adjust the list of domain before)_

** **

_PS: Thank you for all the work that has been done from all the Nextcloud and apps contributors. Really._

edit: typos

**Comment by szaimen** [comment]
Honestly, I don't think that this feature request is feasible. 
But let's cc @nextcloud/server-triage for more opinions on this.

**Comment by skjnldsv** [comment]
Yeah, that's out of scope
