### ISSUE TITLE
Nextcloud Server 21.0.2 on Softaculos giving 1071 error for MySQL 

### ISSUE THREAD

**Issue by vdbhb59** [nextcloud/server#27476]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Login to cPanel, Softaculous. Click Nextcloud install. (This is the first time installation, and not an upgrade).
2. Fill out all details and click next.
3. The progress works till 95-98, but when it moves to the final inflation stage MySQL Error #1071 occurs,

### Expected behaviour
Nextcloud server version 21.0.2 should get installed

### Actual behaviour
Tell us what happens instead
``` Could not make the query numbered : 11
MySQL Error No : 1071
MySQL Error : Specified key was too long; max key length is 767 bytes ```

### Server configuration
cPanel - 68.0 (build 39) - Hosting provider will not update it, and NC old versions until softaculous updated to 21.0.2 were installing correctly, so this error seems specific to the current stable version.
Apache Version | 2.4.48
PHP Version | 7.3.28
MySQL Version | 5.6.38 - Host cannot update to 5.7.X as of now, and latest only by July 2nd week.
Operating System | linux

<!--EndFragment-->

**Operating system:** - Linux

**Web server:** - Not sure

**Database:** - MySQL probably

**PHP version:** - 7.3.28

**Nextcloud version:** (see Nextcloud admin page) - 21.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** - Fresh install

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

### Logs

<!--- Reports without logs might be closed as unqualified reports! -->

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by acsfer** [comment]
This is server configuration problem, not Nextcloud.
Please see https://github.com/nextcloud/server/issues/23369#issuecomment-707313974
