### ISSUE TITLE
Separated Password policies for users and shares

### ISSUE THREAD

**Issue by ichier** [nextcloud/server#27479]
i'd like to force a strong policy on users passwords while enabling simple and common and leaked passwords for shares.
since shares can optionally be unprotected, simple or bad passwords should be optional as well.
quite often such shares should just not be open to everyone so passwords shall be short and memorable while protection from someone breaking in is not the main concern.
accounts nonetheless need to be safe!

So there should be independent password policies for those things.
there could be a checkbox like "[ ] use same policy for shares" and when ticking off, you get to edit all the options. 
best would probably be 2 columns with those options side by side.

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/password_policy/issues/117
