### ISSUE TITLE
Please add a "Nice to Have" label for closed issues where community developers are encouraged

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#27489]
Currently issues and requests which are "nice to have", but not being worked on by the team will be closed with a comment such as "anyone is free to implement this, but we will not be."  I'd like to encourage adding a label such as **Nice to Have** for these issues where the team is encouraging a third party to take the issue over, otherwise it is just buried and lost amongst many other closed issues.

Adding a label helps interested volunteers locate these issues easily.  Thank you for considering!

**Comment by szaimen** [comment]
Done. I've named it "Nice to have" :)
