### ISSUE TITLE
NC Passwort Recovery via Email does not work for .com adresses

### ISSUE THREAD

**Issue by roadrunnerjb** [nextcloud/server#27491]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Press "Passwort vergessen" Button
2. receive email with reset link
3. Link in mail looks like this:
https://cloud.url/index.php/lostpassword/reset/form/eeROtHAAs2qwgiLowlvt6/hugo.maier@gmail.com
4. browser does not open the link but asks for downloading a .com file (Mime Type "application/x-msdos-program-Typ")

This works for most of our users as we request them to set a their own password after user creation with "passwort reset" function. But some of our users have mail adresses like "hugo.maier@gmail.com" and for those we face this issue.

### Expected behaviour
Tell us what should happen
Link should be opened to set new password

### Actual behaviour
Tell us what happens instead
Browser asks for .com file to download

### Server configuration

**Operating system:**
debian
**Web server:**
apache
**Database:**
maradb
**PHP version:**
7.4
**Nextcloud version:** (see Nextcloud admin page)
20,21
**Updated from an older Nextcloud/ownCloud or fresh install:**
-
**Where did you install Nextcloud from:**
-
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:**
Firefox ESR 78.11.0 und Chromium 90.0.4430.212 
Edge, Opera
**Operating system:**
Windows
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)
