### ISSUE TITLE
php updater.phar does not allow resume

### ISSUE THREAD

**Issue by 2019-05-10** [nextcloud/server#27494]
Never mind.
From past experience, I am sure it will never be fixed anyway.

Hint for anybody bitten by the broken updater:
Do not even try.
Delete verything but
``data/``
``config/``
and just unzip new release similar to 
[https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html](https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html)

**Comment by kesselb** [comment]
Duplicate of https://github.com/nextcloud/updater/issues/283

**Comment by kesselb** [comment]
We already spent some time at nextcloud/updater#283 debugging this issue. We don't know why for your setup the filesystem report that deleting the file did not work.
