### ISSUE TITLE
Sync Protokoll

### ISSUE THREAD

**Issue by cla-4** [nextcloud/server#27500]
## Protocol for Admin's
It would be very good to get information about the sync state. Yes you have the local Client which shows some information and you have the different icons. But you normally don't look in the client (if you don't have to for some reason) and you do not check every folder for the icons.

So it can be bad if you think a file or folder is synced but it isn't. And then the file or disk crashes.

The Data wich should be shown:
- Errors (could not copy the file for some reason)
- Duplikat Errors (so you can react as soon as Possible)
- Synced File Count and Size

In my opinion there are to options.
### First Option
There is an Overview page in the admin area. Where you can see Sync Errors and some statistic Data.

Additional it should be a nice feature if an admin can change settings for file download file ofline.
Sometimes it is easier and better if the admin can change things.
It could be difficult if the admin have to say the college: "Click there, then there an check this, then click there...".

**in this case there musst be made some privacy documentation in a company**
But if this was made und the college know that the admin has access and what he see, I think it should be no problem.
Whereat the admin can every time get access to all files if he want ;-)

### The Second Option
The User it self can create / activate an Scheduled E-Mail Report.
So you should get one mail per week or so in which you see errors, File count and summary file size...
On Errors (like duplicate) it would be good can say to get max. on mail per day. So if you have an permanent error you do not get 1.000 mails :-O

**Comment by szaimen** [comment]
Hi 👋

We are currently cleaning up our issue tracker. The feature described in this issues sounds like a good idea for a dedicated app. Feel free to post it in our "App ideas" section in the forum, to find a developer that wants to work on it:
https://help.nextcloud.com/c/apps/app-ideas/21

We are closing this issue here now, so the "issue tracker" of the server repository can be used better to track issues instead.

Cheers
