### ISSUE TITLE
[ Collaborative tags ] Limite tags creation  by groups

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/server#27503]
Hi,
Is there the possibility of limiting the creation of tags by groups? 

Best regards

**Comment by Spartachetto** [comment]
This should be part of what is discussed in issue #4699 in the last part which speculates on access rights and visibility for tags

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/4699
