### ISSUE TITLE
Feature Request: Block outdated or wrong clients

### ISSUE THREAD

**Issue by User65481** [nextcloud/server#27519]
**Is your feature request related to a problem? Please describe.**
Not yet. With more releases and increasing gap between Owncloud we're concerned about future issues regarding sync and rights.

**Describe the solution you'd like**
Possibility to block non-nextcloud clients (namely Owncloud), maybe even outdated nextcloud clients. This could be bundled with server-releases (only allow connections to clients newer than -1y). Our main concern are Owncloud clients.

**Describe alternatives you've considered**
Didn't found any feasible alternatives except blocking IPs from which the requests come from if users refuse to update to a current nextcloud version.

**Additional context**
Example of a few OwnCloud clients connecting in the past few days:
![OldClients](https://user-images.githubusercontent.com/77266803/122173184-ca981680-ce81-11eb-88f3-eb71b5bb6a24.png)
Alternatively there could be a option to block clients with certain strings the admin has to set on his own (for example: refuse connection if UserAgent contains *Owncloud*).

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/b2c2f32968ea9fcf3c28a35bc31c78e4d2caae08/config/config.sample.php#L1640-L1652

**Comment by User65481** [comment]
Unfortunately this setting doesn't seems to work for us, we put it wit 3.0.0 in our config.php, restarted apache, rebooted the whole server and still have lots of 2.6.4 which connect and sync.
Does it matter where its placed in the config.php (as long its not in an array)?
`  'has_rebuilt_cache' => true,
  'minimum.supported.desktop.version' => '3.0.0',
  'preview_max_filesize_image' => 5,
  'preview_max_x' => 512,
  'preview_max_y' => 512,`

![Logins](https://user-images.githubusercontent.com/77266803/124730390-94dece80-df11-11eb-9051-ecf670249601.png)
