### ISSUE TITLE
Unable to delete S3 external storage

### ISSUE THREAD

**Issue by TitanBlast** [nextcloud/server#27513]
Hello,

There is no way to delete the External Storage "folder" on my nextcloud instance. Not via admin view neither though the user one. I shall I do?

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
