### ISSUE TITLE
impossible to create group (in users)

### ISSUE THREAD

**Issue by tiboite** [nextcloud/server#27527]
nextcloud 22.0.0 beta 3 and nextcloud 22.0.0 beta 4
the input window does not open
what should I do?

**Comment by ChicagoGregg** [comment]
I also have this issue with v22.0.0 using 3 different web browsers (Chrome, Brave, and Firefox).

**Comment by JonasBVS** [comment]
can confirm this on v22.0.0

**Comment by LycorisZheng** [comment]
Also met this issue on 22.0.0

**Comment by lerd2805** [comment]
Same issue on 22.0.0.11

**Comment by szaimen** [comment]
Should be fixed with NC22.1.0
