### ISSUE TITLE
Node 14 and NPM 7 

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#27528]
For more background see https://github.com/nextcloud/app-tutorial/pull/319 and feel free to ask your questions there.
I just automated the PRs to set the correct engine everywhere:

- [ ] ~~https://github.com/nextcloud/activity/pull/594~~ https://github.com/nextcloud/activity/pull/593
- [x] https://github.com/nextcloud/files_pdfviewer/pull/429
- [x] https://github.com/nextcloud/files_videoplayer/pull/239
- [x] https://github.com/nextcloud/firstrunwizard/pull/547
- [x] https://github.com/nextcloud/logreader/pull/534
- [x] https://github.com/nextcloud/notifications/pull/1008
- [x] https://github.com/nextcloud/password_policy/pull/210
- [x] https://github.com/nextcloud/privacy/pull/638
- [x] https://github.com/nextcloud/recommendations/pull/412
- [x] https://github.com/nextcloud/viewer/pull/957
- [x] https://github.com/nextcloud/announcementcenter/pull/363
- [x] https://github.com/nextcloud/deck/pull/3139
- [x] https://github.com/nextcloud/external/pull/264
- [x] https://github.com/nextcloud/files_automatedtagging/pull/490
- [x] https://github.com/nextcloud/files_texteditor/pull/423
- [x] https://github.com/nextcloud/flow_notifications/pull/29
- [x] https://github.com/nextcloud/groupfolders/pull/1535
- [x] https://github.com/nextcloud/ldap_write_support/pull/347
- [x] https://github.com/nextcloud/richdocuments/pull/1610
- [x] https://github.com/nextcloud/spreed/pull/5785
- [x] https://github.com/nextcloud/terms_of_service/pull/593
- [x] https://github.com/nextcloud/text/pull/1663
- [x] https://github.com/nextcloud/user_retention/pull/367
- [x] https://github.com/nextcloud/workflow_pdf_converter/pull/332
- [x] https://github.com/nextcloud/bruteforcesettings/pull/322
- [x] https://github.com/nextcloud/calendar/pull/3223
- [x] https://github.com/nextcloud/forms/pull/989
- [x] https://github.com/nextcloud/guests/pull/639
- [x] https://github.com/nextcloud/integration_discourse/pull/14
- [x] https://github.com/nextcloud/integration_github/pull/24
- [x] https://github.com/nextcloud/integration_gitlab/pull/20
- [x] https://github.com/nextcloud/integration_google/pull/61
- [x] https://github.com/nextcloud/integration_jira/pull/18
- [x] https://github.com/nextcloud/integration_mastodon/pull/13
- [x] https://github.com/nextcloud/integration_moodle/pull/20
- [x] https://github.com/nextcloud/integration_reddit/pull/12
- [x] https://github.com/nextcloud/integration_twitter/pull/16
- [x] https://github.com/nextcloud/integration_whiteboard/pull/35
- [x] https://github.com/nextcloud/integration_zammad/pull/15
- [x] https://github.com/nextcloud/mail/pull/5199
- [x] https://github.com/nextcloud/officeonline/pull/162
- [x] https://github.com/nextcloud/registration/pull/315
- [x] https://github.com/nextcloud/social/pull/1279
- [x] https://github.com/nextcloud/suspicious_login/pull/486
- [x] https://github.com/nextcloud/twofactor_totp/pull/1125
- [x] https://github.com/nextcloud/twofactor_u2f/pull/902
- [x] https://github.com/nextcloud/user_oidc/pull/282

**Comment by PVince81** [comment]
all done, only activity remains
