### ISSUE TITLE
Login with device page is not properly styled

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#27530]
* click on the "Login with device" link on the login page
* expect properly designed and styled page - white text, proper border radius for inputs, darker background for errors, error with icon
* actual:
![Bildschirmfoto 2021-06-16 um 16 18 13](https://user-images.githubusercontent.com/245432/122237107-5a0fea80-cebf-11eb-9023-d64c0058eeed.png)
![Bildschirmfoto 2021-06-16 um 16 23 46](https://user-images.githubusercontent.com/245432/122237112-5aa88100-cebf-11eb-8907-0c82eb521cb3.png)

Expected design:

![Bildschirmfoto 2021-06-16 um 16 25 27](https://user-images.githubusercontent.com/245432/122237321-888dc580-cebf-11eb-86a8-16d9faf9c6f9.png)
![Bildschirmfoto 2021-06-16 um 16 25 38](https://user-images.githubusercontent.com/245432/122237325-89265c00-cebf-11eb-8489-2b4e04144be0.png)

cc @nextcloud/designers

**Comment by Pytal** [comment]
I'll take this, @nextcloud/designers design suggestions?

**Comment by skjnldsv** [comment]
For me it is styled :thinking: 
![Peek 17-06-2021 07-53](https://user-images.githubusercontent.com/14975046/122339271-25447780-cf41-11eb-81ee-48329a3d517b.gif)

**Comment by MorrisJobke** [comment]
> For me it is styled 🤔

The border radius of the input field is not correct. Enter also a wrong user name and try to login. Then an error is shown.
