### ISSUE TITLE
[web ui] Open file with local application

### ISSUE THREAD

**Issue by wanningfe** [nextcloud/server#27539]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you want to have the same feature implemented.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Feature description
After installing the native client, I hope I can choose to open the selected file with the local application or display the selected folder in the local file manager in the web user interface.

The web ui integrates many functions that are temporarily missing in the local file management, I don’t want to leave the web ui.

I think the problem can be easily solved by registering a protocol for the local client.

**Comment by szaimen** [comment]
cc @nextcloud/server-triage is this feasible?
