### ISSUE TITLE
Handle internationalized domains

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/server#27546]
Noticed while having a look at https://github.com/nextcloud/server/pull/27474

We make use of `FILTER_VALIDATE_URL` and `FILTER_VALIDATE_EMAIL` but both don't support internationalized domains (IDNs), which need to be converted to punycode before being validated.

The function should be available in `OCP` because a few core apps make use of these filters. It should look like the following:
```php
/**
 * @return string | boolean
 */
function validateEmail(string $email) {
  $pos = strrpos($email, '@');
  if ($pos === false) {
    return false;
  }
  $domain = validateDomain(substr($email, $pos + 1));
  if (!$domain) {
    return false;
  }
  $ascii_email = substr($email, 0, $pos) . '@' . $domain;
  return filter_var($ascii_email, FILTER_VALIDATE_EMAIL);
}

/**
 * @return string|boolean
 */
function validateDomain(string $domain) {
  return filter_var(idn_to_ascii($domain), FILTER_VALIDATE_URL);
}

**Comment by tcitworld** [comment]
`OC\Mail\Message` and `OC\Mail\Mailer` already have respectively `convertAddresses` and `convertEmail` (which is used by `validateMailAddress`, so this is already here basically).

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
