### ISSUE TITLE
MySQL server has gone away during migration script

### ISSUE THREAD

**Issue by artonge** [nextcloud/server#27542]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Run a migration script that can have a long execution time with big DB like `occ db:convert-filecache-bigint`
2. Encounter some network error, or resources limit or anything that will cause the error `MySQL server has gone away`

### Expected behaviour
Handle this kind of error and retry instead of exiting. But maybe that is not a sane thing to do.

### Actual behaviour
Script halt, and the user as to rerun it to complete the task.

**Comment by szaimen** [comment]
cc @nextcloud/server for more input on this
