### ISSUE TITLE
Synchronization checksum error  on a document modified online (onlyoffice)

### ISSUE THREAD

**Issue by ImaCrea** [nextcloud/server#27563]
Hello everyone here :)
Thank you for the great work done on the client. I found this bug which seems pretty preoccupying. 

Hope it helps !
Good luck 🌺

## Description of the bug
In some cases, a document that has been modified online on the cloud in OnlyOffice (integrated in Nextcloud) can no longer be brought back down to local sync. The client indicates a "checksum" error.

Concretely: as long as I don't modify the file locally, in fact its modifications come down quietly... But as soon as I apply a local modification to it, it goes back up to the cloud but if I then modify it in the cloud, then it's over, it doesn't want to go back down.

## Reproduce the bug
1. Create a .docx document in the cloud for example
2. See that it synchronizes locally without any problem
3. Edit the document in the cloud
4. Observe that the modified document synchronizes there too without any problem
5. Now modify the document locally with your onlyoffice editor 
6. Observe that the locally modified document synchronizes and goes up in the cloud
7. Open the locally modified document in the browser, everything seems to be ok
8. Now modify the document in your browser
9. And then it crashes, the client can't get the modified document back down to your local device

## Expected behavior
The modified document should be synced locally without any problem as it is the case in steps 3->4

## Relevant logs
Error message displayed by the client:
![Capture d’écran 2021-06-18 à 12 41 04](https://user-images.githubusercontent.com/764332/122551392-353d8380-d035-11eb-9656-4cf6d2d00502.png)

## Screenshots
We see here in the finder the file with a red cross indicating that it can not be synced
![Capture d’écran 2021-06-18 à 12 44 38](https://user-images.githubusercontent.com/764332/122551397-38d10a80-d035-11eb-975b-ee7f37787809.png)

## Client:
 - Device: NC client 3.2.2 on Mac 10.14.16 (same behavior seen also with latest client on windows)

## Server:
- NC 19.0.12
- OnlyOffice connector into Nextcloud for document edition

## Additional context
- I feel this is a pretty high priority bug because the probability of it happening is pretty high and once this bug happens, you get stuck. The file can't go back down and you have to duplicate the file in the cloud so that its copy can go back down for example. This doesn't seem like an acceptable experience.

**Comment by ImaCrea** [comment]
(sorry for the close/open, just a mistake on my side ^^)

Thanks @FlexW for redirecting it to contributors on server side :)

**Comment by juliushaertl** [comment]
@ImaCrea Are you using object storage like s3 as a primary storage on the Nextcloud instance?

**Comment by hrenard** [comment]
Hi, I'm working with @ImaCrea. 
Indeed, we're using s3 as primary storage. Do you know what the issue might be ?

**Comment by juliushaertl** [comment]
In that case https://github.com/nextcloud/server/pull/27586 might help with that. Testing is very welcome :)

**Comment by ImaCrea** [comment]
> In that case #27586 might help with that. Testing is very welcome :)

Just tested and looks like it fixed it!

**Comment by ImaCrea** [comment]
Thanks !
