### ISSUE TITLE
[NC22 Beta 5] "Error: Class "OCA\User_LDAP\LDAPProviderFactory" not found" when  "LDAP user and group backend" is disabled

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/server#27576]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Disable LDAP user and group backend 
2. Open log
3. See log gets flooded with fatal error: Error: Class "OCA\User_LDAP\LDAPProviderFactory" not found

### Expected behaviour
No Error is thrown

### Actual behaviour
Log gets flooded with fatal error: Error: Class "OCA\User_LDAP\LDAPProviderFactory" not found

### Server configuration

**Operating system:** Ubuntu 20.04.2 LTS

**Web server:** Apache

**Database:** MariaDB 10.5.10

**PHP version:** 8.0.6

**Nextcloud version:** 22.0.0 Beta 3/5
**Updated from an older Nextcloud:**
Update to Beta3 from NC21 via settings and then update to Beta5 via extracting to filesystem due to this error

**Where did you install Nextcloud from:**
Download beta5

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.7.0
  - activity: 2.15.0
  - calendar: 2.2.2
  - circles: 22.0.0-beta.1
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 4.0.0-beta.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.18.0
  - deck: 1.4.2
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_external: 1.12.1
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.13.2
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.11.0
  - integration_github: 1.0.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.9.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - polls: 3.0.0
  - privacy: 1.6.0
  - provisioning_api: 1.11.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - support: 1.5.0
  - suspicious_login: 4.0.0
  - systemtags: 1.11.0
  - text: 3.3.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.1
  - updatenotification: 1.11.0
  - viewer: 1.6.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - appointments
  - apporder
  - bruteforcesettings
  - encryption
  - firstrunwizard
  - forms
  - guests
  - impersonate
  - integration_zammad
  - mail
  - spreed
  - survey_client
  - talk_matterbridge
  - tasks
  - unsplash
  - user_ldap
  - user_status

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
The current PHP memory limit is below the recommended value of 512MB.
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "tempdirectory": "somewhere outside install dir",
        "dbtype": "mysql",
        "version": "22.0.0.8",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_phone_region": "DE",
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "updater.release.channel": "beta",
        "htaccess.RewriteBase": "\/",
        "htaccess.IgnoreFrontController": true,
        "app_install_overwrite": [
            "deck",
            "spreed",
            "impersonate",
            "dashboard",
            "circles",
            "talk_simple_poll",
            "polls",
            "calendar",
            "contacts",
            "unsplash"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
    }

</details>

**Are you using external storage, if yes which one:** none
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

#### Web server error log
No access

#### Nextcloud log (data/nextcloud.log)

<details>
<summary>Nextcloud log</summary>

```
{
    "reqId": "YM4tlJBwTL@bTZJ9JTNjxwAAGh4",
    "level": 4,
    "time": "2021-06-19T17:47:00+00:00",
    "remoteAddr": "37.201.195.253",
    "user": "dartcafe",
    "app": "no app in context",
    "method": "POST",
    "url": "/settings/apps/enable",
    "message": "Could not boot files_external: Class \"OCA\\User_LDAP\\LDAPProviderFactory\" not found",
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0",
    "version": "22.0.0.8",
    "exception": {
        "Exception": "Error",
        "Message": "Class \"OCA\\User_LDAP\\LDAPProviderFactory\" not found",
        "Code": 0,
        "Trace": [{
            "file": "/www/htdocs/w017b2c3/instances/dev/server/lib/private/AppFramework/Utility/SimpleContainer.php",
            "line": 160,
            "function": "OC\\{closure}",
            "class": "OC\\Server",
            "type": "->",
            "args": ["*** sensitive parameters replaced ***"]
        }, {
            "file": "/www/htdocs/w017b2c3/instances/dev/server/3rdparty/pimple/pimple/src/Pimple/Container.php",
            "line": 118,
            "function": "OC\\AppFramework\\Utility\\{closure}",
            "class": "OC\\AppFramework\\Utility\\SimpleContainer",
            "type": "->",
            "args": ["*** sensitive parameters replaced ***"]
        }, {
            "file": "/www/htdocs/w017b2c3/instances/dev/server/lib/private/AppFramework/Utility/SimpleContainer.php",
            "line": 127,
            "function": "offsetGet",
            "class": "Pimple\\Container",
            "type": "->",
            "args": ["OCP\\LDAP\\ILDAPProviderFactory"]
        }, {
            "file": "/www/htdocs/w017b2c3/instances/dev/server/lib/private/ServerContainer.php",
            "line": 136,
            "function": "query",
            "class": "OC\\AppFramework\\Utility\\SimpleContainer",
            "type": "->",
            "args": ["OCP\\LDAP\\ILDAPProviderFactory", false]
        }, {
            "file": "/www/htdocs/w017b2c3/instances/dev/server/lib/private/AppFramework/DependencyInjection/DIContainer.php",
            "line": 435,
            "function": "query",
            "class": "OC\\ServerContainer",
            "type": "->",
            "args": ["OCP\\LDAP\\ILDAPProviderFactory", true]
        }, {
            "file": "/www/htdocs/w017b2c3/instances/dev/server/lib/private/AppFramework/Utility/SimpleContainer.php",
            "line": 87,
            "function": "query",
            "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
            "type": "->",
            "args": ["OCP\\LDAP\\ILDAPProviderFactory", true]
        }, {
            "function": "OC\\AppFramework\\Utility\\{closure}",
            "class": "OC\\AppFramework\\Utility\\SimpleContainer",
            "type": "->",
            "args": ["*** sensitive parameters replaced ***"]
        }, {
            "file": "/www/htdocs/w017b2c3/instances/dev/server/lib/private/AppFramework/Utility/SimpleContainer.php",
            "line": 106,
            "function": "array_map",
            "args": [{
                    "__class__": "Closure"
                },
                [{
                    "name": "l",
                    "__class__": "ReflectionParameter"
                }, {
                    "name": "session",
                    "__class__": "ReflectionParameter"
                }, {
                    "name": "credentialsManager",
                    "__class__": "ReflectionParameter"
                }, {
                    "name": "credentialsStore",
                    "__class__": "ReflectionParameter"
                }, {
                    "name": "eventDispatcher",
                    "__class__": "ReflectionParameter"
                }, "*** sensitive parameter replaced ***"]
            ]
        }, {
            "file": "/www/htdocs/w017b2c3/instances/dev/server/lib/private/AppFramework/Utility/SimpleContainer.php",
            "line": 114,
            "function": "buildClass",
            "class": "OC\\AppFramework\\Utility\\SimpleContainer",
            "type": "->",
            "args": [{
                "name": "OCA\\Files_External\\Lib\\Auth\\Password\\LoginCredentials",
                "__class__": "ReflectionClass"
            }]
        }, {
            "file": "/www/htdocs/w017b2c3/instances/dev/server/lib/private/AppFramework/Utility/SimpleContainer.php",
            "line": 131,
            "function": "resolve",
            "class": "OC\\AppFramework\\Utility\\SimpleContainer",
            "type": "->",
            "args": ["OCA\\Files_External\\Lib\\Auth\\Password\\LoginCredentials"]
        }, {
            "file": "/www/htdocs/w017b2c3/instances/dev/server/lib/private/AppFramework/DependencyInjection/DIContainer.php",
            "line": 460,
            "function": "query",
            "class": "OC\\AppFramework\\Utility\\SimpleContainer",
            "type": "->",
            "args": ["OCA\\Files_External\\Lib\\Auth\\Password\\LoginCredentials"]
        }, {
            "file": "/www/htdocs/w017b2c3/instances/dev/server/lib/private/AppFramework/DependencyInjection/DIContainer.php",
            "line": 432,
            "function": "queryNoFallback",
            "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
            "type": "->",
            "args": ["OCA\\Files_External\\Lib\\Auth\\Password\\LoginCredentials"]
        }, {
            "file": "/www/htdocs/w017b2c3/instances/dev/server/apps/files_external/lib/AppInfo/Application.php",
            "line": 160,
            "function": "query",
            "class": "OC\\AppFramework\\DependencyInjection\\DIContainer",
            "type": "->",
            "args": ["OCA\\Files_External\\Lib\\Auth\\Password\\LoginCredentials"]
        }, {
            "file": "/www/htdocs/w017b2c3/instances/dev/server/apps/files_external/lib/AppInfo/Application.php",
            "line": 119,
            "function": "getAuthMechanisms",
            "class": "OCA\\Files_External\\AppInfo\\Application",
            "type": "->",
            "args": []
        }, {
            "file": "/www/htdocs/w017b2c3/instances/dev/server/lib/private/AppFramework/Bootstrap/Coordinator.php",
            "line": 178,
            "function": "boot",
            "class": "OCA\\Files_External\\AppInfo\\Application",
            "type": "->",
            "args": [{
                "__class__": "OC\\AppFramework\\Bootstrap\\BootContext"
            }]
        }, {
            "file": "/www/htdocs/w017b2c3/instances/dev/server/lib/private/legacy/OC_App.php",
            "line": 205,
            "function": "bootApp",
            "class": "OC\\AppFramework\\Bootstrap\\Coordinator",
            "type": "->",
            "args": ["files_external"]
        }, {
            "file": "/www/htdocs/w017b2c3/instances/dev/server/lib/private/legacy/OC_App.php",
            "line": 139,
            "function": "loadApp",
            "class": "OC_App",
            "type": "::",
            "args": ["files_external"]
        }, {
            "file": "/www/htdocs/w017b2c3/instances/dev/server/lib/base.php",
            "line": 984,
            "function": "loadApps",
            "class": "OC_App",
            "type": "::",
            "args": []
        }, {
            "file": "/www/htdocs/w017b2c3/instances/dev/server/index.php",
            "line": 36,
            "function": "handleRequest",
            "class": "OC",
            "type": "::",
            "args": []
        }],
        "File": "/www/htdocs/w017b2c3/instances/dev/server/lib/private/Server.php",
        "Line": 1038,
        "CustomMessage": "Could not boot files_external: Class \"OCA\\User_LDAP\\LDAPProviderFactory\" not found"
    },
    "id": "60ce2d94f1d5c"
}
```
</details>

**Comment by kesselb** [comment]
`"ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"` in config.php is the issue here. 

https://github.com/nextcloud/server/blob/0447b53bda9fe95ea0cbed765aa332584605d652/lib/private/Server.php#L1031-L1039

https://github.com/nextcloud/server/blob/0447b53bda9fe95ea0cbed765aa332584605d652/apps/user_ldap/lib/Migration/SetDefaultProvider.php#L53-L56


And we have a migration to set this value. Once the app was enabled this key in config.php exist. Maybe a class_exist for $factoryClass would be enough to avoid this error.

**Comment by kesselb** [comment]
cc @nextcloud/server-triage @ChristophWurst

**Comment by blizzz** [comment]
it should also (or in first place) be removed when disabling the app.
