### ISSUE TITLE
Let nextcloud calendar "redistribute" subscribed ical/webcal/etc links

### ISSUE THREAD

**Issue by ilippert** [nextcloud/server#27578]
**Is your feature request related to a problem? Please describe.**
My users use nextcloud to sync calendar items across various devices. However, a calendar that is fed by an ics file on the web cannot be synced and shared with other users. That is frustrating, because it means, the user has to add the ics feed from the web manually for each device.

**Describe the solution you'd like**
An ics feed should  be shareable with other users and also sync-able.

**Comment by tcitworld** [comment]
See https://github.com/nextcloud/server/issues/1600 to follow the sharing subscription feature.

About synching subscriptions, some clients that support subscriptions also support discovering them, allowing to subscribe to them, such as DAVx⁵ on Android. If your client doesn't support subscriptions at all, it's possible to expose subscriptions as regular calendars as discussed in https://github.com/nextcloud/server/issues/17754.
