### ISSUE TITLE
 Fails to load a file and locks everything

### ISSUE THREAD

**Issue by joaopinto14** [nextcloud/server#27594]
![image](https://user-images.githubusercontent.com/61939916/122896893-6f629a00-d341-11eb-9e96-2052f97c5af2.png)

Não aparece nada

![image](https://user-images.githubusercontent.com/61939916/122897164-a769dd00-d341-11eb-975c-47dcf16b7c72.png)

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
