### ISSUE TITLE
Navigation bar on top behaving super inconsistent

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#27601]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Navigate a bit around Nc Files and look at the navigation bar on top (showing the folder structure)
![Screenshot_20210622_163645](https://user-images.githubusercontent.com/551757/122944519-30037000-d378-11eb-803b-0b6e94b60265.png)

### Expected behaviour
As long as there is plenty space, directories shouldn't collapse

### Actual behaviour
It randomly collapses folders. Made a quick video:
![ezgif-3-b56214630f0a](https://user-images.githubusercontent.com/551757/122946631-cf753280-d379-11eb-8db0-497769697453.gif)

### Server configuration
This is with a full screen 1440P chrome using cloud.nextcloud.com, Nextcloud 22 Beta 5.

**Comment by jospoortvliet** [comment]
@nextcloud/designers this known or a regression?

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/issues/21263
