### ISSUE TITLE
Hundreds of odd oc_authtoken entries for a user slow down performance

### ISSUE THREAD

**Issue by raid1** [nextcloud/server#27603]
This is a summary of https://help.nextcloud.com/t/hundreds-of-odd-oc-authtoken-entries-slow-down-performance-for-a-user-bug-report/117742

### Expected behaviour
1 oc_authtoken per user+device

$ curl -s -X PROPFIND "https://SERVER/remote.php/webdav/Handy/DCIM/Camera/IMG_2021-0602_202145.jpg" -u user2
→ 1-2 seconds

### Actual behaviour
hundreds of oc_authtoken entries:
$ mysql mycloud -B -e "select count(\*) from oc_authtoken where uid='andy'"
count(*)
167

$ curl -X PROPFIND "https://SERVER/remote.php/webdav/Handy/DCIM/Camera/IMG_20210602_223758.jpg" -u andy
→ between 12-17 seconds

After "DELETE \* from oc_authtoken where uid=‘andy’"
the server responds quick again. The curl command needs less than a second.

But this was not a permanent solution. 157 new(!) entries were back the next day.
Here is just a short part of it:
![](https://help.nextcloud.com/uploads/default/original/3X/2/5/259256081808f28fa9775c7642e2289c7ca6f77d.png)

### Questions/Doubts
- Where did all these extra DB lines come from?
- Why do they reappear after a while
- Why did they have no effect until the update to NC 21?

### Server configuration

**Operating system:**
4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

**Web server:**
Apache 2.4.38-3+deb10u4

**Database:**
mysql  Ver 15.1 Distrib 10.3.27-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:**
PHP version (eg, 7.4): 2:7.3+69

**Nextcloud version:** (see Nextcloud admin page)
21.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
latest v20

**Where did you install Nextcloud from:**
with the internal NC updater

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - apporder: 0.12.0
  - audioplayer: 3.1.0
  - bbb: 1.4.1
  - bookmarks: 4.2.2
  - bruteforcesettings: 2.2.0
  - calendar: 2.2.2
  - carnet: 0.24.1
  - cloud_federation_api: 1.4.0
  - cms_pico: 1.0.15
  - comments: 1.11.0
  - contacts: 3.5.1
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - data_request: 1.8.0
  - dav: 1.17.1
  - deck: 1.4.2
  - drawio: 1.0.0
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_external: 1.12.0
  - files_markdown: 2.3.3
  - files_pdfviewer: 2.1.0
  - files_retention: 1.10.1
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - forms: 2.2.4
  - gpxmotion: 0.1.0
  - gpxpod: 4.2.8
  - impersonate: 1.8.0
  - integration_google: 1.0.2
  - integration_whiteboard: 0.0.14
  - integration_zammad: 1.0.1
  - keeweb: 0.6.5
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - mail: 1.9.5
  - nextcloud_announcements: 1.10.0
  - notes: 4.0.4
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - openhab: 0.9.5
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - rainloop: 7.1.2
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - socialsharing_email: 2.2.0
  - spreed: 11.2.2
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - tasks: 0.13.6
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - user_usage_report: 1.5.0
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - encryption
  - passwords
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "trusted_domains": [
            "cloud.mydomain.de",
        ],
        "share_folder": "\/Shared",
        "defaultapp": "calendar",
        "trashbin_retention_obligation": "auto, 14",
        "versions_retention_obligation": "auto, 14",
        "default_language": "en",
        "default_phone_region": "DE",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "overwrite.cli.url": "https:\/\/cloud.mydomain.de",
        "blacklisted_files": [
            "._*",
            ".DS_Store",
            ".DS_STORE",
            ".ds_store"
        ],
        "integrity.check.disabled": false,
        "mysql.utf8mb4": true,
        "mail_smtpauthtype": "LOGIN",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "tls",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "apporder",
            "calendar",
            "bookmarks"
        ],
        "has_rebuilt_cache": true,
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
irrelevant

#### Web server error log
<details>
<summary>Web server error log</summary>

```
(only irrelevant lines like:)
[Tue Jun 22 16:57:47.274268 2021] [access_compat:error] [pid 32647] [client 62.216.xx.yy:64788] AH01797: client denied by server configuration: /var/www/nextcloud/config
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"YNIMvrdbUoVOcoItzNhK1QAAAAw","level":3,"time":"2021-06-22T16:15:59+00:00","remoteAddr":"138.246.3.189","user":"andy","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/andy/","message":"Module 'mbstring' already loaded at Unknown#0","userAgent":"Mozilla/5.0 (Linux) mirall/3.2.2-20210531.142805.04afaa1fe-1.0~focal1 (Nextcloud, ubuntu-5.4.0-74-generic ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"21.0.2.1"}
```

The output of your Nextcloud log in Admin > Logging:
 ``Error	PHP	Module 'mbstring' already loaded at Unknown#0``
(shows up every time when I call curl)
</details>

**Comment by noseshimself** [comment]
It's actually getting exponentially worse with the number of tokens.

**Comment by raid1** [comment]
> It's actually getting exponentially worse with the number of tokens.

Yes, definitely. I'd have to delete the tokens every two days.
So, you are experiencing this also?

**Comment by szaimen** [comment]
I suppose cronjobs are configured correctly and running?

**Comment by raid1** [comment]
Yes, running every 5 minutes.

But I think I have a new clue: I compared the "name" field of the oc_authtoken lines and the majority of the entries looks like this:

`Mozilla/5.0 (Linux) mirall/3.2.2-20210531.142805.04afaa1fe-1.0~focal1 (nextcloudcmd, ubuntu-5.4.0-73-generic ClientArchitecture: x86_64 OsArchitecture: x86_64)`
or
`CalDAV-Sync/0.4.32 (Acer; a500_emea_de; Android 4.0.3; de_DE; org.dmfs.caldav.lib/748; like iOS/5.0.1 (9A405) dataaccessd/1.0)`

I do have nextcloudcmd running every 15 minutes on an ubuntu server.
And I have a pretty old Acer A500 Android (version 4.0.3) tablet synching.

Could it be that these two devices are creating the multiple new entries?
Then the problem must be a combination of NC 21 with nextcloudcmd and with (an old version of) the Android app "CardDAV Sync".

**Comment by noseshimself** [comment]
> So, you are experiencing this also?

Yes, but I did it on purpose by connecting about 800 devices to the same account to see if that was a working option if creation of separate accounts was not possible.

**Comment by raid1** [comment]
I can reproduce the problem with nextcloudcmd. Every time I run it a new token is added:

`$ /usr/bin/nextcloudcmd --user andy -h -n --non-interactive /PATH-TO-ownCloud-DIR https://MYCLOUDSERVER.de/`

`# mysql clouddb -B -e "select name from oc_authtoken where name like '%nextcloudcmd%'"
Mozilla/5.0 (Linux) mirall/3.2.2-20210531.142805.04afaa1fe-1.0~focal1 (nextcloudcmd, ubuntu-5.4.0-73-generic ClientArchitecture: x86_64 OsArchitecture: x86_64)
Mozilla/5.0 (Linux) mirall/3.2.2-20210531.142805.04afaa1fe-1.0~focal1 (nextcloudcmd, ubuntu-5.4.0-73-generic ClientArchitecture: x86_64 OsArchitecture: x86_64)
`

**Comment by szaimen** [comment]
Do you use a password or app-token for authentication via nextcloudcmd?

**Comment by raid1** [comment]
I use the "-n" switch which looks for the credentials (password) in .netrc

**Comment by szaimen** [comment]
Does the same happen if you use an app-token for authentication?

**Comment by raid1** [comment]
Good idea.
But I'm having trouble authenticating for nextcloudcmd with an app-token.
Maybe I'm misunderstanding this concept? I created a new app-token "ncc" and then ran:
`$ nextcloudcmd --user andy --password the-just-created-token-passwd ...`

I cannot even log into the web UI with this token password. Tried it with different users and different NC servers.
Where is my mistake in thinking?

**Comment by szaimen** [comment]
It should work like this: https://github.com/nextcloud/desktop/issues/1779#issuecomment-619388046

**Comment by raid1** [comment]
Thanks, that's how I did it. :-)

But I found the cause why it didn't work: bruteforcesettings kicked in. I had to whitelist the IP of my test computer.
Now nextcloudcmd runs fine with an app-token AND it doesn't create extra oc_authtoken at every run anymore.

So, thanks, this is a good workaround for the problem which I still believe is a bug in NC 21.

**Comment by raid1** [comment]
Please advise on how to split it.
Two new issues?

**Comment by noseshimself** [comment]
This is the "Nextcloud is slowing down exponentially with the number of tokens" thread, tight? Maybe a "Tokens are replicating like rabbits on drugs due to defective clients" would be a separate topic. "Add a button to delete more than one/all tokens" would be a third.

**Comment by raid1** [comment]
Splitting this issue was not accepted by @kesselb  :-(

**Comment by AlfredoCubitos** [comment]
Hi, I currently have a similar problem also discussed [here](https://github.com/nextcloud/server/issues/12377)
In my case it seems that the cron.php is not working correctly. Calling `cron.php` returns `success` but does not delete the old sessions from the `oc_authtoken ` 
This behavior  leads to the same problem described by @raid1 first.

**Comment by rfc2822** [comment]
Hi,

I had the same problem. Hundreds of `oc_authtoken`s have polluted the database and caused significant delays. I have now manually cleared it, but how can this be avoided?

**Comment by kesselb** [comment]
> but how can this be avoided?

Usually by using an app password for caldav/carddav.

**Comment by rfc2822** [comment]
> Usually by using an app password for caldav/carddav.

But do I understand it correctly that [`oc_authtoken` entries should be removed after `session_lifetime` (defaulting to one day)](https://github.com/nextcloud/server/blob/0447b53bda9fe95ea0cbed765aa332584605d652/lib/private/Authentication/Token/DefaultTokenProvider.php#L267)? On my server there are `oc_authtoken`s since 2018 (although cronjob is running regularly).

**Comment by AlfredoCubitos** [comment]
some times the cron.php script does not work well, especially if you have an old often upgraded installation.
try running the script on the command line `sudo -u www-data php  cron.php` in your nextcloud directory.
If it throws an error with something like "apc .." try to add `apc.enable_cli=1` in you php.ini
In my case this worked. But this didn't delete the old entries in` oc_authtoken`.  So I deleted them manually.
I will check if @rfc2822 is right, currently I have not enough entries ;-)

**Comment by AlfredoCubitos** [comment]
@rfc2822 in my case this doesn't work either. I have  table entries which are older than 48 hours with type=0 and type=1 I ran a cron job as described above. Nothing deleted :-(
Where is the problem!!??

**Comment by rfc2822** [comment]
@AlfredoCubitos I activated the SQL query log and manually run the cronjob to see what it does. Maybe this would help in your case too.

**Comment by AlfredoCubitos** [comment]
Hi @rfc2822 I found out that there is a query
`DELETE FROM `oc_authtoken` WHERE (`last_activity` < 1631879405) AND (`type` = 0) AND (`remember` = 1) AND (`version` = 2)`
Where last_activity is 15 days ago, this may lead to a huge table entry on sites with a lot of traffic.
While in this query
`DELETE FROM `oc_authtoken` WHERE (`last_activity` < 1633089005) AND (`type` = 0) AND (`remember` = 0) AND (`version` = 2)`
last_activity is only 1 day ago

So, I had a lot of entries with `remember` = 1 that were not deleted because the time was not expired

May be some one can explain when remember=1 is set and why

**Comment by brianjmurrell** [comment]
Same issue here.  I've just run `sudo -u apache bash -c '/usr/bin/php -f /usr/share/nextcloud/cron.php'` and I still have 492 (the same number I had before running the `cron.php` job) `oc_authtoken` entries dating back to: Fri 11 Mar 2022 05:29:15 PM EST on NC 24.0.0.

Looking at `mysqld` with `strace`, it seems to just get hammered with ```UPDATE `oc_authtoken` SET `password` = ...``` queries and is pegging the disk with the mysql database on it.

I have not (until today, as I just changed one app) been using app passwords.  Is my understanding correct that using them will alleviate this hammering of `mysqld` and make the `oc_authtoken` reasonable?

**Comment by perdittmann** [comment]
I keep running into the same problem. 
Recently with a twist: the oc_authtoken table grew to 108,4 MiB, with a couple of hunderd entries. I emptied it (TRUNCATE), since in my experience that's the only thing that works. Now everyone has to re-login, but at least the Nextcloud is still working.
And after I logged in again, I checked the oc_authtoken table again – it contained one entry, with a size of 108,4 MiB.

I am not an overly experienced user of databases, but that seems rather odd to me.
Maybe I am missing something very obvious, I would be grateful for being pointed into the right direction.

I am using version 23.0.4

**Comment by stevleibelt** [comment]
I am using 24.0.2 (Installation is an old ownCloud one with lots of upgrades since than). And I am having the same issue.

Running `php cron.php` as the right user did not result in any error messages.

```sql
SELECT COUNT (*)
FROM `oc_authtoken`
WHERE `uid` = '<user>'

--- Result: 147
```

Would it be an option to create an `occ` command section to "remove authtoken older than x days"?

**Comment by marianrh** [comment]
@stevleibelt
> Is the following sql statement worth a cronjob? Did I miss something? I have no idea what `protocol` and `version` column is good for.

Just to chime in with my current method of cleaning up the table: I'm simply running `delete from nextcloud.oc_authtoken where name not like '%(Nextcloud iOS)';`

This keeps the tokens from the iOS app (which are required, otherwise users have to log in in the app again), but removes all unnecessary tokens that are created by WebDAV/CardDAV/CalDAV and other clients which log in by password anyway.

Of course, depending on the use cases it might be necessary to exclude other names from deletion as well.

**Comment by piiskop** [comment]
i suddenly couldn't use my server machine anymore and had a look at it to see what was wrong. The space was filled up by 63 GB of _mariadb_ binary logs created by nextcloud having commands like:

`UPDATE `oc_authtoken` SET `password` = '3FOXzJ9xZR1kHURCpkbJ6HEAQ/g3ObwOQXSwM1qsjjwQlSdWtVw4DmzuHIRZBmljH3bXVrK4D/SiW2rtVb3fmR0urjfplE3ohcaaXRHLLfHjOf3Uyi8lQJWO9bdYwO0tvDVi8Pmz9+/Q1ilHu/hwU+/THFNiZDu31rJUGUTV3pFs6BY3wP5TaTvrwF4gWG5Cf2b8UedjMuhSOLbVbI7yhJyU7HTnFnzj92sxLt1D0MGYfhXb+ZPfS2yL7B5pmBK4LZxbfBl8VIIRjDlIEoTZfX8PGA7w1+PU3eetvm1LXMwNoqCksh+9a+18A6yiicTLaiyn70iSyDt5/DaQy0xT4w==' WHERE `id` = 13525`

**Comment by marianrh** [comment]
@piiskop Same on my server, I have to delete the unneeded authtokens regularly, otherwise I'm running out of disk space caused by the binary logs (even though the binary logs are only kept for a few days).

**Comment by piiskop** [comment]
@marianrh Does it help to only delete authtokens? What are they and where do they reside? i always delete the binary logs by using `RESET MASTER` as otherwise, wouldn't they still remain in the system? Have you automated deleting binary logs?

**Comment by piiskop** [comment]
> For users without CLI access to the server [this](https://help.nextcloud.com/t/disconnect-all-sessions-revoking-access-for-all-apps-of-a-user/37955/2) workaround from the community may help.

Do i get you right that all the users must do that?

**Comment by max65482** [comment]
> Do i get you right that all the users must do that?

It is a way to get rid of old sessions without terminal access to the server. This helps with managed instances.
My instance was flooded with hundreds of sessions from a DAVx5 app. That made authentications take incredibly long.

**Comment by piiskop** [comment]
> > Do i get you right that all the users must do that?
> 
> It is a way to get rid of old sessions without terminal access to the server. This helps with managed instances. My instance was flooded with hundreds of sessions from a DAVx5 app. That made authentications take incredibly long.

This has to be solved on the server side as there, the database is growing fast and limitless.

**Comment by ckoehler** [comment]
I've got the same issue. My symptom is long login times, which causes cal/carddav to stop working on some of my devices (likely due to timeout)

**Comment by wolframroesler** [comment]
Same problem here: htop shows 10-30 % CPU load from /usr/sbin/mysqld, some clients can't connect because of timeouts, others are sluggish and/or unreliable. Nextcloud version is 24.0.

```
MariaDB [nextcloud]> show processlist;
+------+-----------+-----------+-----------+---------+------+--------+------------------------------------------------------------------------------------------------------+----------+
| Id   | User      | Host      | db        | Command | Time | State  | Info                                                                                                 | Progress |
+------+-----------+-----------+-----------+---------+------+--------+------------------------------------------------------------------------------------------------------+----------+
| 9438 | nextcloud | localhost | nextcloud | Query   |    0 | Init   | show processlist                                                                                     |    0.000 |
| 9689 | nextcloud | localhost | nextcloud | Query   |    0 | Commit | UPDATE `oc_authtoken` SET `password` = 'I3jFGBD9wwi5xhFXw5QK1OcbELF4wu3/...                          |    0.000 |
| 9709 | nextcloud | localhost | nextcloud | Query   |    0 | Commit | UPDATE `oc_authtoken` SET `password` = 'gq8Lhvj1WNMb73z1+rb+QZZXovkbCWEekQr/...                      |    0.000 |
| 9734 | nextcloud | localhost | nextcloud | Query   |    0 | Commit | UPDATE `oc_authtoken` SET `last_activity` = 1660158683 WHERE (`id` = 126380) AND (`last_activity` <  |    0.000 |
+------+-----------+-----------+-----------+---------+------+--------+------------------------------------------------------------------------------------------------------+----------+

MariaDB [nextcloud]> select count(*) from oc_authtoken;
+----------+
| count(*) |
+----------+
|     2790 |
+----------+
1 row in set (0.002 sec)
```

And a few minutes later it's 2791, and more UPDATEs with different hashes.

**Comment by wolframroesler** [comment]
Perhaps someone finds this useful:

```
MariaDB [nextcloud]> delete from oc_authtoken where id in (select id from oc_authtoken as a where last_activity < (select max(last_activity) from oc_authtoken as b where a.name=b.name and a.login_name=b.login_name));
```

This deletes all oc_authtoken records except the oldest one for each combination of user name and client name (where the client name is something like "iOS/15.5 (19F77) dataaccessd/1.0" or "MacBook-Air (Desktop Client - Macintosh)"). Hopefully this will leave all connections intact while removing as many records as possible.

Before you do that you might wish to run the following, which shows how many oc_authtoken records there are for each user name/client name combination:

```
MariaDB [nextcloud]> select login_name,name,count(id) from oc_authtoken group by login_name,name order by login_name,name;
```

**Comment by Gomez** [comment]
Looks like this is the related PR: https://github.com/nextcloud/server/pull/33375
(Havent tested, yet)

**Comment by AlfredoCubitos** [comment]
Hi everybody,

are you sure that your cronjob is running well?
The current version 24.0.4 shows a cronjob error on admin page if the cron.php didn't run for several days .
I had this issue. After running the cron.php manually I fixed that and I had 1 GB more space on my HD

**Comment by ckoehler** [comment]
> Hi everybody,
> 
> are you sure that your cronjob is running well? The current version 24.0.4 shows a cronjob error on admin page if the cron.php didn't run for several days . I had this issue. After running the cron.php manually I fixed that and I had 1 GB more space on my HD

Yep. That was my issue a while ago, too, but the cronjob is running.

**Comment by stevleibelt** [comment]
My cronjob is also working.

How to figure it out?

* Login as admin
* `Settings` -> `Logging`
* Search for entries from `App` `cron`

**Comment by piiskop** [comment]
Clicking _Logging_ brings up a listing for a fraction of a second and displays a white area.

**Comment by stevleibelt** [comment]
@piiskop can you open your browser debugging bar (hit F12 and select the networkstack) **before** clicking on "Logging".
Maybe you see some information there (check the http request code, the answer section etc.).

**Comment by piiskop** [comment]
i only see what resources are loaded - 108 resources within ! This tells me that the creators of Nextcloud have never put performance as a priority. And every now and then, a resource will be reloaded.

**Comment by kartoffelheinz** [comment]
This bug is pretty severe. 

The SQL-Updates produce so much load and Logs that you easily get into hundreds of gigabytes worth of Binlogs in just a few hours. We got lucky a few times and reacted seconds before the database dataset run out of space. I do not understand why this workaround https://github.com/nextcloud/server/issues/26502#issuecomment-821983093 has not been implemented upstream. It's been over 1 year.

Needs to be fixed ASAP, before everybody updates to latest 24.04 (which seem to trigger this bug a lot more than versions before).

**Comment by wolframroesler** [comment]
Second that, @kartoffelheinz. The occurrence of the problem here coincides with the installation of the latest Nextcloud update (to 24.0.4). Need to "delete from oc_authtoken where ..." every couple of days to keep the problem in check (and I have only a handful of users).

No cron-related messages in the log (https://mydomain/settings/admin/logging).

**Comment by cpm1** [comment]
24.0.5 now and I just re-applied the workaround and cleaned up authtoken table once again. 🙄

**Comment by wolframroesler** [comment]
Upgrading to Nextcloud 24.0.5 improved it for me temporarily (number of rows in oc_authtoken went down from 609 to 83), but now a few days later it's back up to 224, so it's not fixed yet.

**Comment by tcitworld** [comment]
24.0.5 has the fix to reactive the cleanup of the authtokens table, not the fix to avoid creating them in the first place.

**Comment by wolframroesler** [comment]
Though not fixed, 24.0.5 has made it a lot better for me. No need to clean up the oc_authtoken every other day anymore.

**Comment by noseshimself** [comment]
Could we get a button "blast all existing entries to pieces and clean up all relevant tables" or at least an occ command doing so? Just in case...

**Comment by stevleibelt** [comment]
@noseshimself I vote +1 for the occ command.

**Comment by mristuccia** [comment]
Hello everyone.
We've tried to use Nextcloud as a storage backend for an application we're developing for an Enterprise customer.
WebDAV access is a necessary integration in such solution, and we faced this terrible slowness of the WebDAV implementation in Nextcloud.
I can assure you that even if we frequently empty the oc_authtoken table, the general slowness is still there. Emptying the table helps a bit, but we still get face many seconds durations for even storing a single file inside Nextcloud.

Unfortunately, in the end we needed to switch to the community edition of OwnCloud, which is tremendously faster as far as WebDAV is concerned.

I strongly encourage the Nextcloud team to work on this problem, which have been there for many major releases now, and it is still currently there on the 25.0.2 version.

**Comment by nachtgeist** [comment]
Confirmed present on 25.0.2, please re-open this issue (or #19247)

**Comment by juliushaertl** [comment]
I think this is partly also an issue with the desktop client when running nextcloudcmd so opening an issue in the respective repo would be highly appreciated.

We have some logic in the server that will create a session token to be returned as a cookie value so that follow up requests of clients can reuse the auth token without the need for using basic auth in follow up requests. This is done by performing a cookie check by setting a cookie on the first request. If any follow up requests contains that cookie a session token will be generated. Now the nextcloudcmd seems to persist cookies but not across multiple calls so every call of nextcloudcmd will generate a new one.

curl to reproduce:
```
curl -v http://nextcloud.dev.local/ocs/v1.php/cloud/user\?format=json -u admin:admin -H 'OCS-APIRequest: true' --cookie 'XDEBUG_SESSION=PHPSTORM; cookie_test=test'
```

From my perspective the client should now either use basic auth for all requests or persist the cookies across multiple calls. A way to avoid this is to not use the user password but generating an app password and using that for authentication.

**Comment by szaimen** [comment]
> I think this is partly also an issue with the desktop client when running nextcloudcmd so opening an issue in the respective repo would be highly appreciated.

Yes, please do that here: https://github.com/nextcloud/desktop/issues/new?assignees=&labels=0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+. Thanks!

**Comment by mristuccia** [comment]
Great way to manage an issue.
Thanks and good luck.
I'm out.

**Comment by kartoffelheinz** [comment]
Problem still occuring to some extent. Not as bad as before, but most definitely not solved. 
Seems this has been closed prematurely.

**Comment by szaimen** [comment]
The PR that fixes this was merged but only into master which will be available with Nc26. 

@juliushaertl I suppose backporting is too much of a risk?

**Comment by juliushaertl** [comment]
Not back ported on purpose because it has some risk of breaking things. Also looking at it with my above debugging comment this might be something that can not be fixed on the server and the PR was actually not targeting the root cause.

This should be fixed in the client implementation for the nextcloudcmd parts. Other clients may need to either reuse cookies or not persist cookies at all.

**Comment by DrGalvany** [comment]
Hello,
first of all, I would like to thank you for this great contribution.
I had the same problem with my database overflowing.
It was already 5.6 GB in size.
I have queried it myself with “nextcloudcmd”.
The call was made every minute with 3 queries, which in turn left 3 entries in the database.
Now I use the token that you can create in Nextcloud, and now the constant entries in the database are a thing of the past.
Thanks again for this contribution.

The text was automatically translated from German to English.

Greetings
Micha

Translated with DeepL.com (free version)
