### ISSUE TITLE
Settings - counts of users are not incremented after user add

### ISSUE THREAD

**Issue by p-bo** [nextcloud/server#27607]
(Nextcloud v21.0.2)

How to reproduce:

Go to users, observe count of All and Admins. Then add normal user (or admin) and after confirming, you will se, that counts of users are not updated. Page refresh (or leaving, coming back there) makes numbers to update. I know, minor thing - but can cause confusion...

Thanks for your attention :-)
PB

**Comment by tarunawast-123** [comment]
is this issue still available?

**Comment by maikhol** [comment]
Does this issue still need to be fixed?

**Comment by p-bo** [comment]
Yes please, this is persisting even in newest 23.0.2 - just tested.
