### ISSUE TITLE
A notification client

### ISSUE THREAD

**Issue by frocelu** [nextcloud/server#27615]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
A simple desktop client that let user can login or auth by token and just recive Announcements  via toast.

**Describe alternatives you've considered**
An websocket route to recive push message for develop?

**Additional context**

**Comment by szaimen** [comment]
Hi, I think this is what you are looking for https://github.com/fds2610/NCT-Desktop
