### ISSUE TITLE
Missing header WWW-Authenticate in HTTP 401 response

### ISSUE THREAD

**Issue by Excpt0r** [nextcloud/server#27641]
### Steps to reproduce
Send HTTP Request to nextcloud, i.e.
curl -v https://yourcloud/index.php/apps/files/
curl -v https://yourcloud/ocs/v2.php/cloud/users

### Expected behaviour
Response HTTP 401 is expected, together with HTTP header WWW-Authenticate.
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate
Past versions seemed to send this header:
https://github.com/nextcloud/server/issues/751

### Actual behaviour
Response code 401 is returned, but without header WWW-Authenticate.

### Server configuration

**Database:**
mysql
Version: 10.5.5 
**PHP version:** 7.4.10

**Nextcloud version:** 20.0.10

**Unrelated**
Btw the git repository has a size of 1.7GB, where 1.6GB are only used for ".git", maybe that could be cleaned up.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.4? If not, please close this issue. Thanks! :)

**Comment by Excpt0r** [comment]
Hi @szaimen 
Yes the problem is still valid with NC21.0.4

You can see how the behaviour SHOULD be, when you execute the following:
curl -v https://jigsaw.w3.org/HTTP/Basic/
One of the response headers is: www-authenticate: Basic realm="test"

Now test similar for NC:
curl -v -H "OCS-APIRequest: true" -H "Accept: application/json" http://yourcloud:port/ocs/v2.php/cloud/users
The result is no www-authenticate is set.

(Note that curl is only used for easy demonstration, and I know how to explicitly provide basic auth there.
But there are other http clients that need this header to be set correctly to use basic authentication)

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
