### ISSUE TITLE
22.0.0RC1 identifies as beta5

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#27650]
After extracting RC1, `occ status` yields
> version: 22.0.0.8
> versionstring: 22.0.0 beta 5

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/blob/stable22/version.php#L33-L36

@blizzz can you check?

**Comment by blizzz** [comment]
cannot reproduce

```
$ suww php occ status
  - installed: true
  - version: 22.0.0.9
  - versionstring: 22.0.0 RC1
  - edition: 
$ cat version.php  | grep VersionString
$OC_VersionString = '22.0.0 RC1';
```

**Comment by nursoda** [comment]
Sure, sorry. But looking at my bash history was embarrassing: It looks like I forgot to unzip RC1, so I replaced b5 with b5. Correctly verifying integrity and unzipping leads to the desired:

> version: 22.0.0.9
> versionstring: 22.0.0 RC1

For completeness, here are the steps I took:

```
sudo -i -u http
cd PATH-CONTAINING-THE-CLOUD-WEB-ROOT
wget https://download.nextcloud.com/server/prereleases/nextcloud-22.0.0rc1.zip
wget https://download.nextcloud.com/server/prereleases/nextcloud-22.0.0rc1.zip.asc
gpg nextcloud-22.0.0rc1.zip.asc 
unzip nextcloud-22.0.0rc1.zip 
mv test b5
mv nextcloud test
cp b5/config/config.php test/config
for i in b5/apps/* ; do test -d test/apps/$(basename $i) || cp -a b5/apps/$(basename $i) test/apps; done
cd test
php occ status
```

Note: I only used this manual approach as I cannot use the web based updater since beta3 as described [here](https://github.com/nextcloud/server/issues/27582#issuecomment-867580608). The update to RC1 did not change that.
I'm effectively not receiving updates this way. I also don't see the app store entries in /settings/apps, only "My Apps".

https://test.seyfarth.de/settings/admin/overview yields:
> Alle Überprüfungen bestanden.
> test.seyfarth.de 22.0.0 RC1
> Eine neue Version ist verfügbar: Nextcloud 22.0.0 beta 3
> Die Verbindung zum App-Store konnte nicht aufgebaut werden oder der App-Store hat keine Apps zurück geliefert. Suche selbst nach Updates oder stelle sicher, dass Dein Server Zugriff auf das Internet hat und eine Verbindung zum App-Store aufbauen kann. 

https://scan.nextcloud.com/results/ad5d1a63-b67b-4220-a16a-f55219fe1f7b yields
> https://test.seyfarth.de
> Rating: A
> Running Nextcloud 22.0.0.9
> NOT on latest patch level
> Major version still supported
> Scanned at 2021-06-24 15:17:07

Not described there but may be related to that: The wheather widget on the dashboard also takes ages and does report weather for an "unknown location" And, yes, access to location is allowed in FX.

Any hint welcome what the cause to these may be. I'm on NGINX/PHP-FPM on Arch, current.
