### ISSUE TITLE
Add NC 20 support to GpxEdit app

### ISSUE THREAD

**Issue by e-gor** [nextcloud/server#27667]
GpxEdit app ([https://apps.nextcloud.com/apps/gpxedit](https://apps.nextcloud.com/apps/gpxedit)) does not work for NC 20 onwards.

**Comment by szaimen** [comment]
Hi there, please follow https://gitlab.com/eneiluj/gpxedit-oc/-/issues/61.
Thank you!

**Comment by e-gor** [comment]
That's exactly the problem, the app's developer is not updating it nor accepting pull requests...

**Comment by szaimen** [comment]
cc @eneiluj

**Comment by e-gor** [comment]
@eneiluj has already solved it, thank you very much!
