### ISSUE TITLE
Issue with old style share link in Chrome

### ISSUE THREAD

**Issue by ZorgeR** [nextcloud/server#2766]
My instance has many share links, old style like:
https://core.z-lab.me:8080/public.php?service=files&t=45c80fd06d27b982f088a17eb82a6074&download
and new style, like
https://core.z-lab.me:8080/s/Ag7lf8l1PvaxhRL/download

I publish this 2 link on any page, and:
old style link open correctly in Chrome only after first click
old style link give 503 error on second and other click in Chrome

new style link work all the time.
old and new style link work all the time in non-Chrome browser (safari, ie).

If i wipe cookie in chrome for my domain, old style link also work, only first click. Second click give 503 error. (cookie name to delete is oc8qshr85aa4, i think its random session cookie, on screenshot)
![cookie name](https://habrastorage.org/files/8d2/d23/7a6/8d2d237a666243219a5446b4e0ebee37.png)

### Steps to reproduce
1. Publish old generated (owncloud) link on the page.
2. Open page in Chrome and click on link, file will download.
3. Go back to this page and click again, you will get 503 error.
4. Wipe cookie in chrome for nextcloud domain, and link will work again for 1 click.

### Expected behaviour
file download on first, second, and other click.
### Actual behaviour
file download on first, get 503 error on second and other click.

### Server configuration
**Operating system**: CentOS 7
**Web server:** nginx 1.10
**Database:** MariaDB
**PHP version:** 5.5
**Nextcloud version:** 11
**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from owncloud 6/7/8/9

**Are you using external storage, if yes which one:** local

### Client configuration
**Browser:** Chrome
**Operating system:** MacOS and Windows.

**Comment by MorrisJobke** [comment]
I just tried this with 11.0.3 and it works. We have code in place that does the redirect from within PHP: https://github.com/nextcloud/server/blob/813f0a0f40dd42b28cd35d91616f3f87ef400861/apps/files_sharing/public.php#L31-L31

So this should work also independent from the used webserver. Please report back if this is working for your now. If not we are happy to reopen the issue.
