### ISSUE TITLE
files_external mapping extended attributes to tags

### ISSUE THREAD

**Issue by noseshimself** [nextcloud/server#27688]
**Is your feature request related to a problem? Please describe.**
I need a way to be able to modify NextCloud tags on files stored in external filesystems easily. Many filesystems offering extended attributes which could be used to store them...

**Describe the solution you'd like**
Iff an external file system is offering support for extended file attributes it would be a good idea to map them onto something functionally equivalent to NextCloud tags. This would make including external support for workflows that are not easily expressed inside NextCloud a lot easier. Not only the obvious way (using inotify and friends) but also as a way to make NextCloud tags exportable.

**Describe alternatives you've considered**
I've been making some first attempts to solve my problems with [SuperTag ](https://github.com/amoffat/supertag) but I feel uncomfortable adding an additional database to the filesystem management. TMSU was more or less doing what I need to get done but is not usable as an external file system for NextCloud either.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
