### ISSUE TITLE
Warning if uploading unsupported files

### ISSUE THREAD

**Issue by rubo77** [nextcloud/server#27689]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Unexperienced users don't know what to do with a downloaded file in an unsupported format, so e.g. if you have a TIFF file, there is only an option to download it, but on standard android devices, the file cannot be opened afterwards anyway.

**Describe the solution you'd like**
When uploading unsupported files, show a warning like

> you are uploading a TIFF file, this is file cannot be viewed inside Nextcloud. do you still want to upload?

**Comment by stavros-k** [comment]
I believe this is great message for non so techy users, but it should be a setting to turn off this messages!

**Comment by szaimen** [comment]
I don't think that this feature request is feasible but

cc @nextcloud/server-triage for mor opinions on this.

**Comment by rubo77** [comment]
Where would be the script, I have to add the message?
Then I will create a pull request

**Comment by rubo77** [comment]
Bump

**Comment by joshtrichards** [comment]
It seems more it would be the *downloads* that are the issue, not the *uploads*. 

The support for opening a given file format is dependent on a mixture of native client support on that device + OS support + third-party apps installed. 

So not sure this is as easy as it may seem on the surface to implement in the real world. :thinking:

**Comment by skjnldsv** [comment]
I don't think this is fully possible. Like Simon said.
We cannot know in advance if a file is supported by Nextcloud or one of its app.

The only thing I could see working, would be checking if we know the mime type.
But honestly, that sounds like over-engineering and a really tiny edge case. Also a bit far from what I think you would like.
Unfortunately then, I'll close that ticket :$
