### ISSUE TITLE
Download recently uploaded images - feature request

### ISSUE THREAD

**Issue by monsieurhannes** [nextcloud/server#27690]
Hi,
I use my NC quite often to download images taken with my phone which automatically uploads all photos. They appear in the recent uploads field in the files section and I'd like to click on them and download them right away.
I know that this "problem" only applies to images and maybe other things that I haven't noticed yet, therefore it might be an addition to the photos app? I'm not sure if the gallery is a server feature or comes with the photo app.

## Current situation
At the moment there is one workaround by clicking on the filename in "Activity" (marked lila in the screenshot below) which jumps to the image in the folder-view.

## Idea
Ideally there could be a download button next to the "Play" symbol (yellow marker), or if that doesn't work with some devices, in the sharing menu (green marker) or the sub-menu (red marker).

## Image
![image](https://user-images.githubusercontent.com/20651440/123549672-3a53ae80-d76a-11eb-8236-9f325ffddef0.png)

## Version
NC 20.0.8

**Comment by szaimen** [comment]
Hi, please update to NC21. Should already be working with that version.
