### ISSUE TITLE
Failed to update to 20.0.10 from an early 20 version

### ISSUE THREAD

**Issue by hunterstabler** [nextcloud/server#27691]
Failed to update to 20.0.10. Broken Nextcloud

Steps to reproduce
1. Attempted to update to 20.0.10 from the Nextcloud web GUI

Expected behaviour:

A successful update

Actual behaviour:

Update was unsuccessful

Server configuration unknown. inmotionhosting. Localhost via UNIX socket?

Operating system: Tried it on Ubuntu, Windows 10, MacOS Big Sur

Web server: inmotionhosting 

Database: MariaDB

PHP version: 7.3.27

Nextcloud version: (see Nextcloud admin page) 20.0.10

Updated from an older Nextcloud/ownCloud or fresh install: updated from 20. something

Where did you install Nextcloud from: web GUI

Signing status: unkown

List of activated apps: caldav, carddav, calendar, files, contacts

Nextcloud configuration: unknown

Config report

Are you using external storage, if yes which one: NO

Are you using encryption: No

Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...
Not sure. I think I set up Dav
LDAP config
Client configuration
Browser: Firefox, Brave

Operating system: Ubuntu, Windows 10, MacOS Big Sur

Logs
Web server error log
Web server error log
Nextcloud log (data/nextcloud.log)
Nextcloud log
Browser log

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_appconfig` (`appid`,`configkey`,`configvalue`) SELECT ?,?,? FROM `oc_appconfig` WHERE `appid` = ? AND `configkey` = ? HAVING COUNT(*) = 0' with params ["core", "oc.integritycheck.checker", "[]", "core", "oc.integritycheck.checker"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

**Comment by szaimen** [comment]
Hi, please fill out the issue template. Thanks!

**Comment by hunterstabler** [comment]
> Hi, please fill out the issue template. Thanks!

I edited my post and copy pasted the template. I don't really use github often, so I am sorry if this isn't the correct protocol to fill out the issue template
