### ISSUE TITLE
Error message on Document creation

### ISSUE THREAD

**Issue by jroussay** [nextcloud/server#27705]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install OnlyOffice (VM)
2. Create a new document

### Expected behaviour
Document created without error.

### Actual behaviour
An error appear (the document is created). If I reload the page, no more error on reload, but come back when the session is reloaded (logout)

### Server configuration

**Operating system:**
Debian 10

**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
21.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from older
**Where did you install Nextcloud from:**
source
**Signing status:**
<details>
<summary>No errors have been found.</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>Enabled:
  - accessibility: 1.7.0
  - admin_audit: 1.11.0
  - bruteforcesettings: 2.1.0
  - calendar: 2.2.2
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 3.5.1
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - drawio: 1.0.0
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_accesscontrol: 1.11.0
  - files_external: 1.12.0
  - files_fulltextsearch: 21.0.2
  - files_linkeditor: 1.1.5
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - fulltextsearch: 21.0.1
  - fulltextsearch_elasticsearch: 21.0.1
  - groupfolders: 9.0.1
  - impersonate: 1.8.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - onlyoffice: 7.0.2
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - theming_customcss: 1.8.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "url"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "url",
        "htaccess.RewriteBase": "\/",
        "overwritehost": "url",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "21.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "installed": true,
        "maintenance": false,
        "auth.bruteforce.protection.enabled": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "loglevel": 2,
        "logfile": "\/var\/www\/nextcloud\/data\/nextcloud.log",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "mysql.utf8mb4": true,
        "onlyoffice": {
            "verify_peer_off": true
        },
        "allow_local_remote_servers": true,
        "app_install_overwrite": [
            "calendar"
        ],
        "mail_sendmailmode": "smtp",
        "debug": false,
        "default_phone_region": "FR"
    }
}
</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox
**Operating system:**
Linux
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>{"reqId":"lWvc9nLbh4XYIc3M0Bwl","level":3,"time":"2021-06-29T09:33:34+00:00","remoteAddr":"xx","user":"xx","app":"PHP","method":"POST","url":"/ocs/v2.php/apps/files/api/v1/templates/create","message":{"Exception":"Error","Message":"Undefined variable: template at /data/nextcloud/lib/private/Files/Template/TemplateManager.php#174","Code":0,"Trace":[{"file":"/data/nextcloud/lib/private/Files/Template/TemplateManager.php","line":174,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[8,"Undefined variable: template","/data/nextcloud/lib/private/Files/Template/TemplateManager.php",174,{"filePath":"//Document.docx","templateId":"","templateType":"user","userFolder":{"__class__":"OC\\Files\\Node\\Folder"},"e":{"__class__":"OCP\\Files\\NotFoundException"},"0":"And 4 more entries, set log level to debug to see all entries"}]},{"file":"/data/nextcloud/apps/files/lib/Controller/TemplateController.php","line":56,"function":"createFromTemplate","class":"OC\\Files\\Template\\TemplateManager","type":"->","args":["//Document.docx","","user"]},{"file":"/data/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"create","class":"OCA\\Files\\Controller\\TemplateController","type":"->","args":["//Document.docx","","user"]},{"file":"/data/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\TemplateController"},"create"]},{"file":"/data/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\TemplateController"},"create"]},{"file":"/data/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files\\Controller\\TemplateController","create",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.files.Template.create"}]},{"file":"/data/nextcloud/ocs/v1.php","line":63,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/files/api/v1/templates/create"]},{"file":"/data/nextcloud/ocs/v2.php","line":24,"args":["/data/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/data/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.102 Safari/537.36","version":"21.0.2.1"}</summary>

```


```
</details>

#### Browser log
<details>
<summary>ConsoleLogger.js:54 [ERROR] files: Error while creating the new file from template {app: "files", uid: "user"}

https://url/ocs/v2.php/apps/files/api/v1/templates/create 403
</summary>

```

```
</details>

**Comment by szaimen** [comment]
This should be fixed with NC21.0.3 See https://github.com/nextcloud/server/pull/27021
