### ISSUE TITLE
Custom Web Interface

### ISSUE THREAD

**Issue by um4ng-tiw** [nextcloud/server#27710]
Hello.
I am currently working on a Nextcloud project and I was curious to know whether Nextcloud web interface(frontend) can be modified in any way. Also, is there a way I can create my own web interface to use it with the Nextcloud server to access the files and completely bypass the default nextcloud web interface.

**Comment by acsfer** [comment]
Please check https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/templates.html

**Comment by szaimen** [comment]
Hi @um4ng-tiw, 
please ask your question in https://help.nextcloud.com
Thank you!
