### ISSUE TITLE
Exception: The root storage could not be initialized

### ISSUE THREAD

**Issue by joshhopkins** [nextcloud/server#27712]
Any insight into this issue would be great: https://github.com/nextcloud/nextcloud-snap/issues/1770

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
