### ISSUE TITLE
Two Factor Authentication Problem With Android Mobile Client

### ISSUE THREAD

**Issue by Wayne-Fagan** [nextcloud/server#2771]
### Steps to reproduce
**1. Install Nextcloud client on Android version 6.0.1, kernal 3.4.0-9493471. And sign in to account
2. Enable TOTP on user account - web interface 
3. Go back to Android client, and try to sign in**

### Expected behaviour
Tell us what should happen

**Should be able to sign in back, or be prompted for a Google Authenticator code to sign**

### Actual behaviour
Tell us what happens instead

**Password for user account is rejected, and therefore refuses access to mobile client**

### Server configuration
**Operating system**:

**Ubuntu server 16.04**

**Web server:**

**Apache 2.0** 

**Database:**

**mysql  Ver 15.1 Distrib 10.0.28-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2**

**PHP version:**

**PHP Version 7.0.8-0ubuntu0.16.04.3**

**Nextcloud version:** (see Nextcloud admin page)

**11.0**

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Main Nextcloud site**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by rullzer** [comment]
Currently it does not work like that.
You have to create an app password (go to your personal settings) for each device.

**Comment by sjash** [comment]
First log-in using web-client and enable T-OTP and then go to personal-->App Passwords.
Create an Application Password say Mobile client it will show your username and an app password.
Copy that password and when you login through android app give that password instead of your original Password/LDAP password.
It will solve your issue.
