### ISSUE TITLE
Some users don't show up in 'search contacts'

### ISSUE THREAD

**Issue by raboof** [nextcloud/server#27724]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a user with a dash in its username
2. Search for that user in the top-right 'Search contacts' box

### Expected behaviour
You find the user

### Actual behaviour
You don't find the user

### Server configuration

**Operating system:**
Linux (using the Nextcloud docker image)

**Web server:**
nginx

**Database:**
mariadb

**PHP version:**
unknown

**Nextcloud version:** (see Nextcloud admin page)
21.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from a not-too-old Nextcloud install, but the problem occurs for new users as well.

**Where did you install Nextcloud from:**
docker

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Are you using an external user-backend, if yes which one:** AFAIK no

### Client configuration
**Browser:** Firefox, but the problem is also observed by other users

**Operating system:** NixOS linux, but the problem is also observed by other users

### Logs

The whole process of creating the new user, logging in as the new user, and searching for that new user does not produce any lines in the log.

#### Browser log
<details>
<summary>Browser log</summary>

Nothing interesting here, only complaining the built-in jQuery is deprecated
</details>

**Comment by szaimen** [comment]
I suppose this is still valid on NC21.0.4?

**Comment by raboof** [comment]
The latest version I've tested this with is 21.0.1, I'll update here when I test with newer versions.

Since filing this issue I've also seen users without dashes in their username not show up in the contact list, though, so I'm no longer sure this is what triggers the issue...

Another thing I noticed since is that while they don't show up in 'Search contacts...', they do show up in the 'share with...' dropdowns.

**Comment by paultaiton** [comment]
@raboof 
I think I'm having the same issue, but am not certain. When I try to search for users and it fails I find in my admin logs "Exception: in_array(): #2 ($haystack) must be of type array, null given".
Can you confirm if you're getting the same? If Not I'll open a different issue to keep them separate, otherwise I can add information here to hopefully help troubleshooting.

Gentoo Linux
Nextcloud 22.1.0
Apache 2.4.48
PHP  8.0.9
Mariadb (on a different host) 10.5.12

**Comment by raboof** [comment]
> When I try to search for users and it fails I find in my admin logs "Exception: in_array(): #2 ($haystack) must be of type array, null given". Can you confirm if you're getting the same?

Hmm, no, nothing in the admin log (`/settings/admin/logging`) for me

**Comment by raboof** [comment]
Another shot in the dark: I just noticed both users for which this is happening have a first name that is shared with another user.

Also their usernames are 'firstname' and 'firstname.lastname', though for the one user it is the 'firstname.lastname' account that cannot be found, and for the other it is 'firstname'.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by raboof** [comment]
I can confirm this is still happening after we updated to 25.0.3

**Comment by joshtrichards** [comment]
Are you still experiencing this? I created variations of co-existing users like this and haven't seen anything weird so far:

`dash-user`
`dash.user`
`dash`

I'm testing against 29.

**Comment by raboof** [comment]
Unfortunately the users that were affected by this have since left our organization, so I can't test with those anymore.

I have made some additional attempts to trigger the issue but haven't managed to. Let's assume it is fixed until we notice anything off again.
