### ISSUE TITLE
[Activity] The notification parameter remains activated even if the application is deactivated

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/server#27730]
### Steps to reproduce
1. Disable Agenda or Contact
2. Go inside user parameters  inside notification activity

### Expected behaviour
Agenda/Task might be hide because not enabled

### Actual behaviour
Agenda/Task is diplayed
![image](https://user-images.githubusercontent.com/38983960/123964216-8180b000-d9b3-11eb-9691-1029adcdf1d0.png)

### Server configuration

**Operating system:** Debian 10

**Web server:** Apache2

**Database:** mariadb

**PHP version:** 7.3-FPM

**Nextcloud version:** 21

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Are you using external storage, if yes which one:**  local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by szaimen** [comment]
Jep, this is by design as the dav provider is part of server and contacts and calendar apps are simply clients.
