### ISSUE TITLE
Substitute icons by Material Design ones?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#27735]
Now that some apps started using material design icons, I thought it would make sense to do the same in the server repository.

What is your opinion on this? @nextcloud/server @nextcloud/designers

**Comment by blizzz** [comment]
Not a fan of googlification.

**Comment by skjnldsv** [comment]
Yes, this is planned. The material design icons are opensourced. We're slowly but surely moving to it. There is a discussion about this already somewhere :)

**Comment by szaimen** [comment]
I could work on it if you need somebody that does this.

**Comment by szaimen** [comment]
🎉🎉🎉
