### ISSUE TITLE
Packages v20.0.11 from releasepage have v21.0.3 inside

### ISSUE THREAD

**Issue by timm2k** [nextcloud/server#27748]
Hi Nextclouders,

packages from https://github.com/nextcloud/server/releases/tag/v20.0.11 have version 21.0.3 inside.
`version.php` shows `$OC_VersionString = '21.0.3';`

Kind regards
Timm

**Comment by timm2k** [comment]
Files from https://download.nextcloud.com/server/releases/ are fine.

**Comment by timm2k** [comment]
now v20.0.11 archives carry out v20.0.11 :-)

**Comment by skjnldsv** [comment]
How could you be so fast?  :rofl: 
We fixed it, thanks for your interest

**Comment by timm2k** [comment]
We're moving von nc 19 to 20.0.11 tomorrow because of my holiday plans (first holidays for almost 18 months) comes closer and I need to hat NC20 one week in production before (to file bug reports or service requests or - my very great hope - to verify everything runs fine). So I need every second to verify my upgrade plan :rocket:

**Comment by timm2k** [comment]
I struggled over a mimetype migration which was introduced in NC21 and confused me a little bit in v20 branch ;-)
I kick them out and run mimetype corrections later when we're back in production to save some (or lots) of time.
