### ISSUE TITLE
Epoch doesn't fit in a PHP integer: Calendar not loading and not syncing

### ISSUE THREAD

**Issue by usrjense** [nextcloud/server#27765]
After Update from PHP 7.4 to 8.0 one of my calendars are not loading and sync stopped for all calendars.

I guess there is a issue with some data length in the DB, because the other calendars are loading properly?
Could be a 32 / 64bit issue as well as my server runs a armv7l (Rpi2 Model B) ?

### Steps to reproduce
Open Calendar App in Nextcloud WebUI

### Expected behaviour
- All calendars should have loaded and are visible
- New / changed calendar items are synced

### Actual behaviour
- 1 of 4 calendar is not loading and raise error message as stated below
- No sync of new / changed calendar items but did'nt raise errors in the log

### Calendar app
2.3.0
CalDAV-clients: SFOS-CalDav and iOS 14.6 CalDav

### Client configuration
Firefox 89 at Ubuntu 20.04

### Server configuration
**OS**: Ubuntu 20.04 (armv7l) => 32bit
**Web server:** Apache 2.4.41
**Database:** MySQL 8
**PHP version:** 8.0.7
**Nextcloud Version:** 21.0.3

**Updated from an older installed version or fresh install:** update from 21.0.2

**List of activated apps:** 

**Nextcloud configuration:**

#### Log file (data/nextcloud.log)

{"reqId":"jvzJQFdiNgPgS2Z5x5lM","level":4,"time":"2021-07-02T10:55:39+02:00","remoteAddr":"xx.xx.xx.xx","user":"username","app":"webdav","method":"REPORT","url":"/remote.php/dav/calendars/username/calendarname/","message":{"Exception":"ValueError","Message":"Epoch doesn't fit in a PHP integer","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/sabre/vobject/lib/Recur/RRuleIterator.php","line":473,"function":"getTimestamp","class":"DateTimeImmutable","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/vobject/lib/Recur/RRuleIterator.php","line":109,"function":"nextMonthly","class":"Sabre\\VObject\\Recur\\RRuleIterator","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/vobject/lib/Recur/EventIterator.php","line":349,"function":"next","class":"Sabre\\VObject\\Recur\\RRuleIterator","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/vobject/lib/Recur/EventIterator.php","line":387,"function":"next","class":"Sabre\\VObject\\Recur\\EventIterator","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/vobject/lib/Component/VEvent.php","line":41,"function":"fastForward","class":"Sabre\\VObject\\Recur\\EventIterator","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/CalendarQueryValidator.php","line":277,"function":"isInTimeRange","class":"Sabre\\VObject\\Component\\VEvent","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/CalendarQueryValidator.php","line":80,"function":"validateTimeRange","class":"Sabre\\CalDAV\\CalendarQueryValidator","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/CalendarQueryValidator.php","line":41,"function":"validateCompFilters","class":"Sabre\\CalDAV\\CalendarQueryValidator","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Backend/AbstractBackend.php","line":139,"function":"validate","class":"Sabre\\CalDAV\\CalendarQueryValidator","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/CalDAV/CalDavBackend.php","line":1431,"function":"validateFilterForObject","class":"Sabre\\CalDAV\\Backend\\AbstractBackend","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/CalDAV/Calendar.php","line":338,"function":"calendarQuery","class":"OCA\\DAV\\CalDAV\\CalDavBackend","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php","line":598,"function":"calendarQuery","class":"OCA\\DAV\\CalDAV\\Calendar","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php","line":258,"function":"calendarQueryReport","class":"Sabre\\CalDAV\\Plugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"report","class":"Sabre\\CalDAV\\Plugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":685,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpReport","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":332,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/3rdparty/sabre/vobject/lib/Recur/RRuleIterator.php","Line":473,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0","version":"21.0.3.1"}

**Comment by tcitworld** [comment]
You mentioned `SFOS-CalDav` as a CalDAV client. Does the issue happens in this client as well?

**Comment by usrjense** [comment]
> You mentioned `SFOS-CalDav` as a CalDAV client. Does the issue happens in this client as well?

Yes, I have updated description.
Tested also with iOS 14.6 CalDav - the same. I suppose sync failed due to the error but did'nt throw any errors in the nextcloud.log. 
So, the CalDav-Clients are not the problem here.

**Comment by usrjense** [comment]
I dropped the "critical" calendar. 
Seems to be similar as here https://github.com/Kovah/LinkAce/issues/286 (32bit problem with year 2038 in Armv7)
But the calendar has no dates behind 19 January 2038 and it is not clear for me why this happen from change PHP 7.4 to 8.0

**Comment by tcitworld** [comment]
From the stacktrace it seems to be related to a recurring event.
