### ISSUE TITLE
help.nextcloud.com is down

### ISSUE THREAD

**Issue by meonkeys** [nextcloud/server#27776]
It looks like the forums are down. https://downforeveryoneorjustme.com/help.nextcloud.com says it's not just me.

Firefox says "unable to connect" and "problem loading page".

![Screenshot from 2021-07-02 11-35-56](https://user-images.githubusercontent.com/50639/124320107-232d0c00-db30-11eb-8ae8-0319720593a8.png)

**Comment by andyxheli** [comment]
Yes I can confirm this

**Comment by joe-eklund** [comment]
Of course this happens on upgrade day for me lol... :(

**Comment by meonkeys** [comment]
Looks like it's back up.

**Comment by meonkeys** [comment]
Down again. https://downfor.io/help.nextcloud.com

![Screenshot from 2023-03-25 11-50-20](https://user-images.githubusercontent.com/50639/227735924-e786f5ea-8a53-4ff1-a05b-d35d5e40dca4.png)

**Comment by meonkeys** [comment]
Back online.
