### ISSUE TITLE
Responsive Design Logging Tab Bug?

### ISSUE THREAD

**Issue by EasyPeasy1** [nextcloud/server#2777]
The menu button dont show up at the logging tab.
Is it a bug?

How to reproduce:
Open the Logging Tab on your mobile phone

**Actual behaviour:**
![screenshot_20161219-111114](https://cloud.githubusercontent.com/assets/24621703/21345049/e4875744-c69e-11e6-9840-b5e196756948.png)

**Expected behaviour should be something like that:**
![screenshot_20161219-111114 2](https://cloud.githubusercontent.com/assets/24621703/21345063/f1da4b36-c69e-11e6-9850-4ee76a878fca.png)

Operating System:
Ubuntu 16.04 LTS
Apache 2.4.18
PHP 7.0.8
Nextcloud 11.0.0

(files_texteditor bug has already been reportet --> https://github.com/nextcloud/files_texteditor/issues/23 )

**Comment by blizzz** [comment]
This indeed seems to be related to the Logreader. The other sections I tried always show the hamburger icon. cc @icewind1991 @skjnldsv

**Comment by skjnldsv** [comment]
I agree with @blizzz !
I don't think it is related to nextcloud but rather to logreader.
The app is overwriting `#app-content > #app-navigation-toggle`.
It does not appear in the page source.

**Comment by MorrisJobke** [comment]
Please reopen in https://github.com/nextcloud/logreader/issues
