### ISSUE TITLE
Can't create text file

### ISSUE THREAD

**Issue by beccon4** [nextcloud/server#27783]
### Steps to reproduce
1. Open Nextcloud e.g.with unorthodox browser (Epiphany, Midori)
2. try to create text file 

### Expected behaviour
Create the file and open Markdown editor

### Actual behaviour
Message above to the right - "the file cannot be created from template"

### Server configuration
* Ubuntu 18.04
* Apache
* Nextcloud 21.0.1.1

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
-> No errors have been found

### Server log
`{"reqId":"6jKXbmqo8cMV2mAPgGfl","level":3,"time":"2021-07-03T09:48:19+00:00","remoteAddr":"100.xx.yy.10","user":"beccon","app":"no app in context","method":"POST","url":"/ocs/v2.php/apps/files/api/v1/templates/create","message":{"Exception":"OCP\\Files\\GenericFileException","Message":"Invalid path","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/files/lib/Controller/TemplateController.php","line":56,"function":"createFromTemplate","class":"OC\\Files\\Template\\TemplateManager","type":"->","args":["/null/xxxx.md","","user"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"create","class":"OCA\\Files\\Controller\\TemplateController","type":"->","args":["/null/xxxx.md","","user"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\TemplateController"},"create"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files\\Controller\\TemplateController"},"create"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files\\Controller\\TemplateController","create",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.files.Template.create"}]},{"file":"/var/www/nextcloud/ocs/v1.php","line":63,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/files/api/v1/templates/create"]},{"file":"/var/www/nextcloud/ocs/v2.php","line":24,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Files/Template/TemplateManager.php","Line":157,"CustomMessage":"Invalid path"},"userAgent":"Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15 Midori/6","version":"21.0.1.1"}
`

**Comment by szaimen** [comment]
Hi, are you able to reproduce this issue on NC21.0.3? :)
