### ISSUE TITLE
Nextcloud Update Issue

### ISSUE THREAD

**Issue by LLCServer** [nextcloud/server#27782]
Hello dear Nextcloud Community,
today we (the LLCServer Network Team) would like to open our Nextcloud and after log in into the Cloud we get the message,
that we must update the extension " Electronic Signatures (electronicsignatures) " [See on the picture update-message.png in the following Google Drive folder: https://drive.google.com/drive/folders/1uGs0GKDLRqHeWofVXSf0a3slbfgolQre?usp=sharing].

When we will start the update, we get the error "Exception: Database error when running migration latest for app electronicsignatures" (see also on a picture in the Google Drive folder on the picture update-error.png) And when we open "Detaillierte Protokollierung" be get the following message:
_Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturschritt: Repair MySQL collation
Reparaturinformation: All tables already have the correct collation -> nothing to do
Reparaturschritt: Repair SQLite autoincrement
Reparaturschritt: Copy data from accounts table when migrating from ownCloud
Reparaturschritt: Drop account terms table when migrating from ownCloud
Das Datenbankschema wird aktualisiert
Datenbank aktualisiert
Exception: Database error when running migration latest for app electronicsignatures_

In the end it tell us to ask the Nextcloud Comminuty for a solution, so now we are here.
I hope you can help us and sorry for my bad english, I am from Germany.

**The operating system of the Server is Linux Ubuntu 18.04,5 LTS and everything is on a v-server on Strato (4 Cores, 8GB Ram, 100GB SSD Storage)**

_**~PokeRaichu[LLC-Owner]**_

**Comment by szaimen** [comment]
Hi there, as this seems to be an issue with the electronicsignature app, Please report this issue to https://github.com/eideasy/nextcloud-electronic-signatures-plugin/. Thanks! :)
