### ISSUE TITLE
Upgrade 21.0.2 to 21.0.3 Exception: Database error when running migration latest for app passwords

### ISSUE THREAD

**Issue by gcclinux** [nextcloud/server#27788]
Post upgrade it failed to upgrade 

$ sudo -u www-data php /server/www/n/updater/updater.phar

Then on the web browser also i can't login without running th post installation upgrade and if fails with the following error:

Update to 21.0.3
Exception: Database error when running migration latest for app passwords 

Detailed logs 
Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: Not a mysql database -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Updated database

Repair step: Check System Requirements

Exception: Database error when running migration latest for app passwords

The update was unsuccessful. Please report this issue to the Nextcloud community.

**Comment by szaimen** [comment]
As this seems to be an issue with the passwords app, please report this to https://github.com/marius-wieschollek/passwords Thanks! :)
