### ISSUE TITLE
Fehler bei Aktualisierung auf 21.0.2

### ISSUE THREAD

**Issue by feli0123** [nextcloud/server#27789]
Das ist die Fehlermeldung:

Exception: App "News" cannot be installed because the following dependencies are not fulfilled: 64bit or higher PHP required.

Detaillierte Protokollmeldungen:

Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: All tables already have the correct collation -> nothing to do

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Datenbank aktualisiert

Exception: App "News" cannot be installed because the following dependencies are not fulfilled: 64bit or higher PHP required.

Das Update ist fehlgeschlagen. Bitte melden Sie dieses Problem an die Nextcloud Community.

Wissen Sie, wie ich dieses Problem beheben kann? (Ich verwende einen Raspberry Pi 4)

**Comment by j-ed** [comment]
@feli0123 This is the bug and feature tracker for the developers only. Please address your configuration problem in the [Nextcloud help forum}(https://help.nextcloud.com/).
