### ISSUE TITLE
Bad encoding when removing maintenance mode from config.php

### ISSUE THREAD

**Issue by Dartypier** [nextcloud/server#27785]
Hi, i noted this bug with nextcloud 21.0.3 on ubuntu 20.04. 

When i put '"maintenance" => true' on config.php nextcloud results in the correct maintenance mode. The problem is when i disable the maintenance mode, then the webpage results in a bad encoding error (verified with Firefox and Gnome browser).

**The problem is solved when i put the maintenance from occ:**
`sudo -u www-data php occ maintenance:mode --on`
and then
`sudo -u www-data php occ maintenance:mode --off`

## Environment
Checked with Ubuntu 20.04 (LXC) , nextcloud 21.0.3, apache2

### Steps to reproduce
1. modify config/config.php in your nextcloud folder 
2. put 'maintenance' => true
3. restart apache2
4. check your nextcloud webpage, now nextcloud should result in maintenance mode (OK)
5. modify config.php back to 'maintenance' => false
6. restart apache2
7. your nextcloud webpage should result in a bad encoding error

### Expected behaviour
Turned off maintenance mode and the webpage should be correctly visible

### Actual behaviour
Bad encoding error

### server configuration
Fresh installation

**Operating system:**
Ubuntu 20.04

**Web server:**
Apache 2

**Database:**
MySQL

**PHP version:**
7.X

**Comment by szaimen** [comment]
> Bad encoding when removing maintenance mode from config.php

Please never remove the maintenance entry from the config.php file.

> **The problem is solved when i put the maintenance from occ:**
> `sudo -u www-data php occ maintenance:mode --on`
> and then
> `sudo -u www-data php occ maintenance:mode --off`

As this works correctly, you must have done something wrong while editing the config.php file. So please use this command as it works for you. Thanks! :)

**Comment by Dartypier** [comment]
Yes, I checked now. I added the maintenance option over another one in the same file.
