### ISSUE TITLE
No bulk move available

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/server#2779]
When selecting multiple files, I'm not given the option to move; rather still only download or delete:

![image](https://cloud.githubusercontent.com/assets/3178412/21349841/1e0a1c1a-c6ac-11e6-99ae-0be127a41fdd.png)

So I can move 30 files one by one using the individual file menu, but I can't move 30 files all at once.

NC11
Ubuntu 16.04

**Comment by SnowMB** [comment]
Yeah, I ran into the same issue today.

**Comment by HLFH** [comment]
Same. Also, I wanted to copy and paste and I can't. Related to https://github.com/owncloud/core/issues/10656

**Comment by mc-comanescu** [comment]
I've been using this app from the owncloud world for a while now, and while it still works, it would be nice if we would integrated on this side of the fence..
https://github.com/eotryx/oc_files_mv/pulls

**Comment by koreywithak** [comment]
1. When working on this, please also include in the dialog box an option to create a new folder in case the user wants to put the files in a folder that does not yet exist.
2. Also, the box that pops up for moving files doesn't show files within the folders. I understand the user is supposed to select a folder, but it is nice to see the files as well (to help ensure that folder is indeed the one you want to move the files into).

**Comment by koreywithak** [comment]
When working on this, please also include in the dialog box an option to create a new folder in case the user wants to put the files in a folder that does not yet exist.
Also, the box that pops up for moving files doesn't show files within the folders. I understand the user is supposed to select a folder, but it is nice to see the files as well (to help ensure that folder is indeed the one you want to move the files into).

**Comment by jasonbayton** [comment]
I second points 1 and 2 above, not bothered about 3 though as it's not something I'd usually see in a file picker and wouldn't much use.

**Comment by flypenguin** [comment]
that is *so* weird that this does not yet exist ... yes, please ASAP. favourites would be nice, but not a game changes. bulk move, in general, is (IMHO ;).

**Comment by geiseri** [comment]
+1 on this feature.  Right now I have to move then locally on the filesystem.

**Comment by oparoz** [comment]
@icewind1991 Could you estimate the complexity?

**Comment by jasonbayton** [comment]
Nextcloud 13 👏 🎉

**Comment by oparoz** [comment]
@icewind1991 Could you estimate the complexity?

**Comment by MQGIT** [comment]
I thought this was added in NC11, but I have NC12 and I don't see it.

**Comment by BloodyIron** [comment]
Can we PLEASE stop closing tickets and actually address this? This was a feature in the owncloud addon that isn't in nextcloud. Code is already written, come on.

**Comment by jasonbayton** [comment]
It's not closed from where I'm looking.

**Comment by BloodyIron** [comment]
There's several other related tickets that have been closed already, eventually pointing to this one. Getting fed up having tickets closed without movement. This feature is a really important one when you have a lot of files to move around, like pictures for example.

**Comment by oparoz** [comment]
@icewind1991 Could you estimate the complexity?

**Comment by pandusen** [comment]
Could an option to copy the file(s) be implemented to this feature? There is no option to copy a file at all.. so when you want to, for instance, edit a template and call it something else, there is no other way but to download the file, rename it and then re-upload the file, which as an unnecessary workaround. This is especially useful when using office tools like Collabora and Onlyoffice, as they do not have a "save as" option.

The old files_mv tool/app had this option, but that tool is outdated and problematic.

**Comment by BloodyIron** [comment]
Copy/Move, the ability to interact with multiple files in such a way at a time is needed! But IMO both should be there, not just multi-move, not just multi-copy.

**Comment by dienteperro** [comment]
I think @pandusen and @BloodyIron have a good point. This could lead to:
1. Select items and them move them to a target location (which could be the very same folder, nowadays if a file with the same filename exists NC drops the action and notifies the user);
2. Have a Copy/Cut/Paste buttons combo which behaves similar to a file explorer. (How the clipboard pool will be managed? Or will just be a 1 item clipboard).
I do prefer option 1.

**Comment by jasonbayton** [comment]
@icewind1991 should hopefully be back from holidays soon to estimate the complexity..
