### ISSUE TITLE
List files modified by a certain user

### ISSUE THREAD

**Issue by drebs** [nextcloud/server#27807]
**Is your feature request related to a problem? Please describe.**

I can't see a list of files modified by a specific user.

**Describe the solution you'd like**

I'd like to be able to list or restrict search results to files modified by a certain user (eg. myself or another user I select).

**Describe alternatives you've considered**

- Have a "dropdown" in "Recent" to select a specific user.
- Have a search page with more options, among which "modified by" could be selected.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
