### ISSUE TITLE
No Shift+Select available NC11

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/server#2780]
I recall a while back seeing the option to select a file, hold shift, select another file some way down the list and have all files between checked being re-introduced for 11, but I am still unable to do so, which means I still need to select 30 files one-by-one.

![image](https://cloud.githubusercontent.com/assets/3178412/21349959/b208243e-c6ac-11e6-8d59-64d4ca31ad5e.png)

NC 11
Ubuntu 16.04

**Comment by SnowMB** [comment]
Shift + click, and Ctrl + click work for me as expected. I can select a range of files with shift and single files with strg. 

There is just one issue with shift + click: 
When I want to select a range of files and the one I shift + click on is already selected, it is deselected while all in between are selected (expected would by that it stays selected):

Before:
![before](https://cloud.githubusercontent.com/assets/7050959/21354822/c35dc832-c6cb-11e6-8849-845e4db62354.png)

After:
![after](https://cloud.githubusercontent.com/assets/7050959/21354821/c3591760-c6cb-11e6-824c-1f6f64155315.png)

**Comment by jasonbayton** [comment]
Oh I take it back, it doesn't work by checking the boxes, you just "select" it with the whitespace, hold shift and select the whitespace on the file below. 

I can't replicate your issue either @SnowMB

**Comment by nickvergessen** [comment]
@nextcloud/javascript

**Comment by MorrisJobke** [comment]
maybe @stephanruttloff wants to look into this ;)

**Comment by jasonbayton** [comment]
It's still weird in 12.0.1 (if I click the whitespace now it downloads the file, but ctrl/shift click selects a couple of files together). But doesn't look like this is now relevant anymore.
