### ISSUE TITLE
Problem with update to nextcloud 21.0.3

### ISSUE THREAD

**Issue by giovanni4517** [nextcloud/server#27817]
Aktualisierung auf 21.0.3

Exception: App "News" cannot be installed because the following dependencies are not fulfilled: 64bit or higher PHP required.
Detaillierte Protokollmeldungen

Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: All tables already have the correct collation -> nothing to do

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Datenbank aktualisiert

Exception: App "News" cannot be installed because the following dependencies are not fulfilled: 64bit or higher PHP required.

What can I do now? Any Idea?

**Comment by skjnldsv** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
