### ISSUE TITLE
Nextcloud sync loop, database error(Sabre/Dav error)

### ISSUE THREAD

**Issue by alexander-lamdan** [nextcloud/server#27819]
Hello, Joplin cannot sync between 3 devices(2 pc and 1 android phone) from nextcloud.

Sync looped, I can't even cancel it.

Last sync was in 12:00 moscow time(05.07.2021)

There is the screenshots of errors from dev tools

![124503997-0dde0900-dde0-11eb-9b46-b642780aaeac.png](https://user-images.githubusercontent.com/38505847/124536640-bb2d3d00-de31-11eb-8065-2383fd8683f5.png)
![124504010-10d8f980-dde0-11eb-9dec-ddbe0f59d61f.png](https://user-images.githubusercontent.com/38505847/124536645-bd8f9700-de31-11eb-8b7c-c3e3035b4b0f.png)

FIX IT NOW. I HAVE A LOT OF IMPORTANT NOTES THERE THAT STOPPED TO SYNC. A lot of files in this storage that IMPORTANT.

And please change the database from mysql to redis. 

Server error: nd.nl.tab.digital

I can't delete, upload nothing todo in this storage.

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
