### ISSUE TITLE
Zotero WebDav sync: HTTP DELETE fails with status code 500

### ISSUE THREAD

**Issue by emwal** [nextcloud/server#27824]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Have a running Nextcloud-Instance with no other issues (I am not selfhosting.)
2. Setup Zotero's WebDAV sync
3. Zotero tests the Webdav server with creating a folder, creating a file, fetching and then deleting it.
4. Fail: 

### Expected behaviour
Zotero should connect to WebDAV without hiccups.

### Actual behaviour
Zotero throws an error:

An unknown error occurred.
Please check your file sync settings or contact your WebDAV server administrator.
HTTP 404

The zotero log shows, that the creation of folder and file have worked, while the deletion failed:

HTTP PUT https://user:********@nextcloud.domain.com/remote.php/dav/files/user/zotero/zotero-test-file.prop succeeded with 201
HTTP GET https://user:********@nextcloud.domain.com/remote.php/dav/files/user/zotero/zotero-test-file.prop succeeded with 200
HTTP DELETE https://user:********@nextcloud.domain.com/remote.php/dav/files/user/zotero/zotero-test-file.prop failed with status code 500: <?xml version="1.0" encoding="utf-8"?> <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns"> <s:exception>Error</s:exception> <s:message>Call to a member function getId() on array</s:message> </d:error> 

### Server configuration

**Operating system:**

Ubuntu Linux (Kernel 5.4.0-72)

**Web server:**

nginx/1.18.0 (fpm-fcgi)

**Database:**

mysql 10.3.30

**PHP version:**

7.4.16

**Nextcloud version:** (see Nextcloud admin page)

20.0.9 - 20.0.9.1

**Updated from an older Nextcloud/ownCloud or fresh install:**

no

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```

**Nextcloud configuration:**

Hosted service.

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** 
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

Webdav

### Logs

see above.
#### 1
[no app in context] Error: OCP\AppFramework\QueryException: Could not resolve OCA\Files_Versions\Versions\IVersionManager! Class can not be instantiated at <<closure>>

 0. /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php line 126
    OC\AppFramework\Utility\SimpleContainer->resolve("OCA\\Files_Vers ... r")
 1. /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php line 455
    OC\AppFramework\Utility\SimpleContainer->query("OCA\\Files_Vers ... r")
 2. /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php line 427
    OC\AppFramework\DependencyInjection\DIContainer->queryNoFallback("OCA\\Files_Vers ... r")
 3. /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php line 56
    OC\AppFramework\DependencyInjection\DIContainer->query("OCA\\Files_Vers ... r")
 4. /var/www/html/apps/files_versions/lib/AppInfo/Application.php line 119
    OC\AppFramework\Utility\SimpleContainer->get("OCA\\Files_Vers ... r")
 5. /var/www/html/apps/files_versions/lib/AppInfo/Application.php line 106
    OCA\Files_Versions\AppInfo\Application->loadBackend({@attributes: {f ... "}, OC\AppFramework\ ... {}, OC\AppFramework\Logger {})
 6. /var/www/html/lib/private/AppFramework/Bootstrap/FunctionInjector.php line 68
    OCA\Files_Versions\AppInfo\Application->registerVersionBackends(OC\AppFramework\ ... {}, OC\App\AppManager {}, OC\AppFramework\Logger {})
 7. /var/www/html/lib/private/AppFramework/Bootstrap/BootContext.php line 52
    OC\AppFramework\Bootstrap\FunctionInjector->injectFn(Closure {})
 8. /var/www/html/apps/files_versions/lib/AppInfo/Application.php line 91
    OC\AppFramework\Bootstrap\BootContext->injectFn(Closure {})
 9. /var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php line 168
    OCA\Files_Versions\AppInfo\Application->boot(OC\AppFramework\Bootstrap\BootContext {})
10. /var/www/html/lib/private/legacy/OC_App.php line 191
    OC\AppFramework\Bootstrap\Coordinator->bootApp("files_versions")
11. /var/www/html/lib/private/legacy/OC_App.php line 131
    OC_App::loadApp("files_versions")
12. /var/www/html/apps/dav/lib/AppInfo/Application.php line 113
    OC_App::loadApps(["dav"])
13. /var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php line 168
    OCA\DAV\AppInfo\Application->boot(OC\AppFramework\Bootstrap\BootContext {})
14. /var/www/html/lib/private/legacy/OC_App.php line 191
    OC\AppFramework\Bootstrap\Coordinator->bootApp("dav")
15. /var/www/html/lib/private/legacy/OC_App.php line 131
    OC_App::loadApp("dav")
16. /var/www/html/lib/private/legacy/OC_Util.php line 201
    OC_App::loadApps(["filesystem"])
17. /var/www/html/lib/private/User/Session.php line 554
    OC_Util::setupFS("*** sensitive parameter replaced ***")
18. /var/www/html/lib/private/User/Session.php line 415
    OC\User\Session->prepareUserLogin(true, "*** sensitive parameter replaced ***")
19. /var/www/html/lib/private/User/Session.php line 624
    OC\User\Session->completeLogin("*** sensitive parameters replaced ***")
20. /var/www/html/lib/private/User/Session.php line 367
    OC\User\Session->loginWithPassword("*** sensitive parameters replaced ***")
21. /var/www/html/lib/private/Setup.php line 436
    OC\User\Session->login("*** sensitive parameters replaced ***")
22. /var/www/html/core/Command/Maintenance/Install.php line 106
    OC\Setup->install("*** sensitive parameters replaced ***")
23. /var/www/html/3rdparty/symfony/console/Command/Command.php line 255
    OC\Core\Command\Maintenance\Install->execute(Symfony\Componen ... {}, Symfony\Componen ... {})
24. /var/www/html/3rdparty/symfony/console/Application.php line 1000
    Symfony\Component\Console\Command\Command->run(Symfony\Componen ... {}, Symfony\Componen ... {})
25. /var/www/html/3rdparty/symfony/console/Application.php line 271
    Symfony\Component\Console\Application->doRunCommand(OC\Core\Command\Maintenance\Install {}, Symfony\Componen ... {}, Symfony\Componen ... {})
26. /var/www/html/3rdparty/symfony/console/Application.php line 147
    Symfony\Component\Console\Application->doRun(Symfony\Componen ... {}, Symfony\Componen ... {})
27. /var/www/html/lib/private/Console/Application.php line 215
    Symfony\Component\Console\Application->run(Symfony\Componen ... {}, Symfony\Componen ... {})
28. /var/www/html/console.php line 100
    OC\Console\Application->run()
29. /var/www/html/occ line 11
    require_once("/var/www/html/console.php")

by admin at 2021-06-21T13:27:53+00:00

#### 2

[no app in context] Error: OCP\AppFramework\QueryException: Could not resolve trashManager! Class trashManager does not exist at <<closure>>

 0. /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php line 126
    OC\AppFramework\Utility\SimpleContainer->resolve("trashManager")
 1. /var/www/html/lib/private/ServerContainer.php line 156
    OC\AppFramework\Utility\SimpleContainer->query("trashManager", true)
 2. /var/www/html/lib/private/AppFramework/DependencyInjection/DIContainer.php line 430
    OC\ServerContainer->query("trashManager", true)
 3. /var/www/html/lib/private/AppFramework/Utility/SimpleContainer.php line 56
    OC\AppFramework\DependencyInjection\DIContainer->query("trashManager")
 4. /var/www/html/lib/private/AppFramework/Bootstrap/FunctionInjector.php line 58
    OC\AppFramework\Utility\SimpleContainer->get("trashManager")
 5. <<closure>>
    OC\AppFramework\Bootstrap\FunctionInjector->OC\AppFramework\Bootstrap\{closure}("*** sensitive parameters replaced ***")
 6. /var/www/html/lib/private/AppFramework/Bootstrap/FunctionInjector.php line 68
    array_map(Closure {}, [ReflectionParam ... "])
 7. /var/www/html/lib/private/AppFramework/Bootstrap/BootContext.php line 52
    OC\AppFramework\Bootstrap\FunctionInjector->injectFn([OCA\Files_Trash ... "])
 8. /var/www/html/apps/files_trashbin/lib/AppInfo/Application.php line 57
    OC\AppFramework\Bootstrap\BootContext->injectFn([OCA\Files_Trash ... "])
 9. /var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php line 168
    OCA\Files_Trashbin\AppInfo\Application->boot(OC\AppFramework\Bootstrap\BootContext {})
10. /var/www/html/lib/private/legacy/OC_App.php line 191
    OC\AppFramework\Bootstrap\Coordinator->bootApp("files_trashbin")
11. /var/www/html/lib/private/legacy/OC_App.php line 131
    OC_App::loadApp("files_trashbin")
12. /var/www/html/apps/dav/lib/AppInfo/Application.php line 113
    OC_App::loadApps(["dav"])
13. /var/www/html/lib/private/AppFramework/Bootstrap/Coordinator.php line 168
    OCA\DAV\AppInfo\Application->boot(OC\AppFramework\Bootstrap\BootContext {})
14. /var/www/html/lib/private/legacy/OC_App.php line 191
    OC\AppFramework\Bootstrap\Coordinator->bootApp("dav")
15. /var/www/html/lib/private/legacy/OC_App.php line 131
    OC_App::loadApp("dav")
16. /var/www/html/lib/private/legacy/OC_Util.php line 201
    OC_App::loadApps(["filesystem"])
17. /var/www/html/lib/private/User/Session.php line 554
    OC_Util::setupFS("*** sensitive parameter replaced ***")
18. /var/www/html/lib/private/User/Session.php line 415
    OC\User\Session->prepareUserLogin(true, "*** sensitive parameter replaced ***")
19. /var/www/html/lib/private/User/Session.php line 624
    OC\User\Session->completeLogin("*** sensitive parameters replaced ***")
20. /var/www/html/lib/private/User/Session.php line 367
    OC\User\Session->loginWithPassword("*** sensitive parameters replaced ***")
21. /var/www/html/lib/private/Setup.php line 436
    OC\User\Session->login("*** sensitive parameters replaced ***")
22. /var/www/html/core/Command/Maintenance/Install.php line 106
    OC\Setup->install("*** sensitive parameters replaced ***")
23. /var/www/html/3rdparty/symfony/console/Command/Command.php line 255
    OC\Core\Command\Maintenance\Install->execute(Symfony\Componen ... {}, Symfony\Componen ... {})
24. /var/www/html/3rdparty/symfony/console/Application.php line 1000
    Symfony\Component\Console\Command\Command->run(Symfony\Componen ... {}, Symfony\Componen ... {})
25. /var/www/html/3rdparty/symfony/console/Application.php line 271
    Symfony\Component\Console\Application->doRunCommand(OC\Core\Command\Maintenance\Install {}, Symfony\Componen ... {}, Symfony\Componen ... {})
26. /var/www/html/3rdparty/symfony/console/Application.php line 147
    Symfony\Component\Console\Application->doRun(Symfony\Componen ... {}, Symfony\Componen ... {})
27. /var/www/html/lib/private/Console/Application.php line 215
    Symfony\Component\Console\Application->run(Symfony\Componen ... {}, Symfony\Componen ... {})
28. /var/www/html/console.php line 100
    OC\Console\Application->run()
29. /var/www/html/occ line 11
    require_once("/var/www/html/console.php")

by admin at 2021-06-21T13:27:53+00:00

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

**Comment by szaimen** [comment]
Hi there, which Nextcloud version are you running?

**Comment by emwal** [comment]
Sorry i forgot these: 

Nextcloud version: 20.0.9 - 20.0.9.1

And the webserver is  nginx/1.18.0 (fpm-fcgi)

**Comment by emwal** [comment]
Since it's a managed install (I didn't want to risk my files) I can't tell you this. 
Sorry – maybe somebody else can?

**Comment by q-wertz** [comment]
Do you have any errors in your nginx error logfile?

**Comment by emwal** [comment]
Sorry for not updating on the issue.
I followed up with the support team over at my hoster and it is semi-solved now. 
The enabled server-encryption has been the culprit. Disabling it and decrypting the files is the solution, then the HTTP requests work as expected.
On the downside you lose the encryption – but that didn't matter in my case anyway.
