### ISSUE TITLE
Critical changes for developers & admins for Nextcloud 23

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#27846]
Continuation of #26407

# Front-end

* …

# Backend

* `\OCP\User\Events\UserLoggedInEvent::getPassword` is now nullable

## Removed from public namespace:

* …

## Removed from private namespace:

* …

## Deprecations

*  \OCP\Calendar\IManager::search
* \OCP\Calendar\IManager::isEnabled
* \OCP\Calendar\IManager::registerCalendar
* \OCP\Calendar\IManager::unregisterCalendar
* \OCP\Calendar\IManager::register
* \OCP\Calendar\IManager::getCalendars
* \OCP\Calendar\IManager::clear

### Deprecations of Events & Hooks

* …

## Behavorial changes

* https://github.com/nextcloud/server/pull/28075
* https://github.com/nextcloud/server/issues/29258

## Changes for admins
* Nginx config was changed so webassembly can be served https://github.com/nextcloud/documentation/pull/7585

**Comment by ChristophWurst** [comment]
@nickvergessen ticket closed but the changes were not put anywhere, were they? https://docs.nextcloud.com/server/stable/developer_manual/app_publishing_maintenance/upgrade-guide.html stops at 22.

**Comment by nickvergessen** [comment]
I was not aware we copy them somewhere. So no I just closed and created the 24 one

**Comment by ChristophWurst** [comment]
Okay but that would be pointless. Nobody will find this closed ticket, would they?

I'll create tickets in the documentation repo.

**Comment by nickvergessen** [comment]
> Nobody will find this closed ticket, would they?

It's linked from the 24 one and the FAQ: https://github.com/nextcloud/server/issues/23369

But yeah sure we should add it to the docs.
