### ISSUE TITLE
NC20/21 after update - index.php/settings/apps and index.php/settings/user redirects to index.php with empty content

### ISSUE THREAD

**Issue by pongraczi** [nextcloud/server#27853]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Upgrade to the latest NC with 20 and 21 (two instances on two different servers)
2. After successfully upgraded these systems, admin user logout and login again.
3. Click on the managing apps/users under my profile picture.
4. Page URL switched to example.tld/index.php/settings/apps or example.tld/index.php/settings/users as expected.
5. The icon bar appeared as expected, but the main content area remains empty.
6. After a short time, the URL changes to example.tld/index.php and the content area keeps empty.
7. That's all. 
8. Other actions: browser forced to reload content by shift-reload -> same result.

### Expected behaviour
Managing apps or users should popup instead of empty content.

### Actual behaviour
![Kijelölés_753](https://user-images.githubusercontent.com/5891983/124773808-945c2d00-df3d-11eb-9972-82a790481a06.png)

~**Browser log seems descriptive:**~  
~`Refused to execute script from 'https://example.tld/index.php/apps/dashboard/' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.`~

### Server configuration

**Operating system:** debian 10

**Web server:** apache

**Database:** Mariadb

**PHP version:** 7.4

**Nextcloud version:** latest 20 and 21.

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from the previous versions.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - analytics: 3.5.1
  - announcementcenter: 4.0.1
  - appointments: 1.9.3
  - apporder: 0.13.0
  - audioplayer: 3.1.0
  - bookmarks: 4.2.2
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.0
  - circles: 0.20.10
  - cloud_federation_api: 1.3.0
  - collectives: 0.9.21
  - comments: 1.10.0
  - contacts: 4.0.0
  - dashboard: 7.0.0
  - data_request: 1.7.0
  - dav: 1.16.2
  - deck: 1.2.7
  - drawio: 1.0.1
  - duplicatefinder: 0.0.8
  - event_update_notification: 1.3.0
  - external: 3.7.3
  - extract: 1.3.1
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_accesscontrol: 1.10.2
  - files_automatedtagging: 1.10.1
  - files_bpm: 0.2.1
  - files_downloadactivity: 1.9.0
  - files_external: 1.11.1
  - files_fulltextsearch: 20.0.4
  - files_linkeditor: 1.1.5
  - files_markdown: 2.3.4
  - files_mindmap: 0.0.24
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_snapshots: 1.0.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - flow_notifications: 1.0.3
  - forms: 2.2.4
  - fulltextsearch: 20.0.2
  - fulltextsearch_elasticsearch: 20.0.2
  - groupfolders: 8.2.2
  - groupquota: 0.1.6
  - guests: 1.6.3
  - impersonate: 1.7.0
  - integration_gitlab: 1.0.0
  - integration_google: 1.0.2
  - jitsi: 0.11.0
  - login_notes: 0.4.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.10.0
  - maps: 0.1.9
  - metadata: 0.13.0
  - news: 16.0.0
  - nextcloud_announcements: 1.9.0
  - notes: 4.1.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.4.2
  - password_policy: 1.10.1
  - passwords: 2021.7.21
  - phonetrack: 0.6.7
  - photos: 1.2.3
  - podcast: 0.3.1
  - polls: 2.0.5
  - previewgenerator: 3.1.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - qownnotesapi: 20.9.0
  - quicknotes: 0.6.7
  - quota_warning: 1.9.1
  - recommendations: 0.8.0
  - registration: 1.3.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - side_menu: 1.24.0
  - spreed: 10.0.8
  - support: 1.3.0
  - survey_client: 1.8.0
  - suspicious_login: 3.2.1
  - systemtags: 1.10.0
  - talk_matterbridge: 1.22.4
  - tasks: 0.13.6
  - terms_of_service: 1.6.1
  - text: 3.1.0
  - theming: 1.11.0
  - timetracker: 0.0.59
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - video_converter: 1.0.1
  - viewer: 1.4.0
  - w2g2: 3.2.6
  - weather_status: 1.0.0
  - workflow_pdf_converter: 1.5.1
  - workflow_script: 1.5.1
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - checksum
  - contactsinteraction
  - emlviewer
  - encryption
  - files_external_gdrive
  - files_lock
  - files_readmemd
  - files_trackdownloads
  - flowupload
  - jsloader
  - keeweb
  - music
  - ocr
  - ocsms
  - printer
  - ransomware_detection
  - scanner
  - user_external
  - user_ldap
  - weather
  - whiteboard

```
</details>

### Client configuration
**Browser:** Brave

**Operating system:** Linux

**Comment by pongraczi** [comment]
Sorry, browser log is irrelevant.  
There is no error messages in php log/nc log.

**Comment by kesselb** [comment]
occ maintenance:repair to rebuild the assets.

**Comment by pongraczi** [comment]
Thank you, I did the following on the NC20:  
* maintenance repair -> shift-reload -> logout -> login -> still not working
* maintenance mode on + maintenance repair + maintenance off -> shift-reload -> logout -> login -> still not working
* server side: `service php7.4-fpm restart; service redis restart; service apache2 restart` -> logout -> login -> still not working
* **browser cache clean -> login -> working**

On NC21 instance, I did the following:  
* **browser cache clean -> login -> working** - the real solution

In fact, I rarely restart my workstation, it is working 24/7 and usually I restart browser once a month, depends on other things.  

**Thank you very much** to pointing to the [PEBCAK](https://www.urbandictionary.com/define.php?term=PEBCAK), I feel stupid to ignore cleaning browser cache.
