### ISSUE TITLE
NC22 cron reports "running maintenenace"

### ISSUE THREAD

**Issue by cscholz** [nextcloud/server#27855]
### Steps to reproduce
Unknown. After updateing to NC22 cron reports periodically "running maintenance" when executing cron.

### Expected behaviour
Execution of cron without any error

### Actual behaviour
```
$ sudo -u USERNAME /usr/bin/nice -n 5 /usr/bin/php -q /.../cron.php 2>&1
running maintenance(2)
running maintenance(1)
```

### Server configuration

**Operating system:**
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

**Web server:**
ii  nginx-full                            1.14.2-2+deb10u4                                                         amd64        nginx web/proxy server (standard version)

**Database:**
ii  mariadb-server-10.3                   1:10.3.29-0+deb10u1                                                      amd64        MariaDB database server binaries

**PHP version:**
ii  php8.0-fpm                            8.0.8-1+0~20210701.21+debian10~1.gbp9ee385                               amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)

**Nextcloud version:** (see Nextcloud admin page)
22.0.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from NC 21.0

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-22.0.0.zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
>> no errors
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.7.0
  - activity: 2.15.0
  - admin_audit: 1.11.0
  - checksum: 1.1.2
  - circles: 22.0.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dav: 1.18.0
  - end_to_end_encryption: 1.7.1
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.13.2
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.11.0
  - impersonate: 1.9.0
  - lookup_server_connector: 1.9.0
  - oauth2: 1.9.0
  - photos: 1.4.0
  - provisioning_api: 1.11.0
  - rainloop: 7.1.2
  - richdocuments: 4.2.0
  - serverinfo: 1.12.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - text: 3.3.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.1
  - twofactor_email: 2.0.0
  - twofactor_totp: 6.1.0
  - updatenotification: 1.11.0
  - viewer: 1.6.0
  - workflowengine: 2.3.0
Disabled:
  - camerarawpreviews
  - dashboard
  - duplicatefinder
  - encryption
  - extract
  - federation
  - files_external
  - firstrunwizard
  - geoblocker
  - logreader
  - metadata
  - nextcloud_announcements
  - notifications
  - officeonline
  - password_policy
  - previewgenerator
  - privacy
  - recommendations
  - support
  - survey_client
  - systemtags
  - testing
  - twofactor_admin
  - twofactor_gateway
  - twofactor_nextcloud_notification
  - twofactor_u2f
  - user_ldap
  - user_status
  - weather_status

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
<?php
$CONFIG = array (
  'instanceid' => 'ocXXXX',
  'passwordsalt' => 'XXX',
  'trusted_domains' =>
  array (
    0 => 'cloud.domain.tld',
  ),
  'datadirectory' => '/.../cloud.domain.tld/data',
  'dbtype' => 'mysql',
  'version' => '22.0.0.11',
  'dbname' => 'DATABASE',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'DATABASE',
  'dbpassword' => 'DB_PASSWORD',
  'installed' => true,
  'forcessl' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpport' => '587',
  'mail_smtppassword' => 'EMAIL_PASSWORD',
  'mail_smtpname' => 'noreply@domain.tld',
  'trashbin_retention_obligation' => 'auto,30',
  'mail_from_address' => 'noreply',
  'mail_domain' => 'domain.tld',
  'log_type' => 'syslog',
  'loglevel' => 1,
  'logdateformat' => 'F d, Y H:i:s',
  'logtimezone' => 'Europe/Berlin',
  'log_query' => false,
  'log_authfailip' => true,
  'log_rotate_size' => '104857600',
  'session_lifetime' => 3600,
  'theme' => '',
  'maintenance' => false,
  'mail_smtpauth' => true,
  'secret' => 'SECRET_123',
  'updatechecker' => true,
  'check_for_working_htaccess' => false,
  'updater.release.channel' => 'stable',
  'overwrite.cli.url' => 'https://cloud.domain.tld',
  'enable_certificate_management' => true,
  'versions_retention_obligation' => '14,auto',
  'filelocking.enabled' => true,
  'filelocking.debug' => true,
  'default_phone_region' => 'DE',
  'twofactor_enforced' => 'false',
  'config_is_read_only' => 'true',
  'twofactor_enforced_groups' =>
  array (
  ),
  'onlyoffice' =>
  array (
    'verify_peer_off' => true,
  ),
  'twofactor_enforced_excluded_groups' =>
  array (
    0 => 'admin',
    1 => 'users',
  ),
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcached_servers' =>
  array (
    0 =>
    array (
      0 => 'localhost',
      1 => 11211,
    ),
  ),
  'app_install_overwrite' =>
  array (
    0 => 'admin_notifications',
    1 => 'files_trackdownloads',
    2 => 'twofactor_email',
    3 => 'metadata',
    4 => 'spreedme',
    5 => 'breezedark',
    6 => 'uploaddetails',
    7 => 'rainloop',
    8 => 'checksum',
    9 => 'spreed',
    10 => 'files_retention',
    11 => 'end_to_end_encryption',
    12 => 'camerarawpreviews',
    13 => 'duplicatefinder',
    14 => 'twofactor_nextcloud_notification',
  ),
  'mysql.utf8mb4' => true,
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
);

</details>

**Comment by anoymouserver** [comment]
See https://github.com/nextcloud/circles/issues/686
