### ISSUE TITLE
Maintenance Mode for certain user groups

### ISSUE THREAD

**Issue by leon47331** [nextcloud/server#27850]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested in the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status changes and new comments. 

**Is your feature request related to a problem? Please describe.**
No, my feature request is not related to a problem.

**Describe the solution you'd like**
It would be nice to implement a feature where the admin can select if the maintenance mode should be enabled for everyone or just for certain user groups. For example: If you do some improvement on the Nextcloud, the user groups "users" should not be allowed to log in and it should be displayed a message saying that the Nextcloud is currently in Maintenance Mode and the login is not possible at the moment.

If a user is not allowed to log in, it saves resources that might be useful to the admin doing the maintenance work in the Nextcloud.

**Comment by szaimen** [comment]
As the database isn't available during the maintenance mode, is this feature request out of scope.
