### ISSUE TITLE
Upgrade from 20.0.11 to 21.0.3: Admin Overview complains about `/.well-known/webfinger` and `/.well-known/nodeinfo`

### ISSUE THREAD

**Issue by MacLemon** [nextcloud/server#27865]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Upgrade from NC 20.0.11.1 to NC 21.0.3.1 using the web-updater
2. Check Admin Overview
3. See Messages: 
> Your web server is not properly set up to resolve "/.well-known/webfinger". Further information can be found in the [documentation](https://docs.nextcloud.com/server/21/go.php?to=admin-setup-well-known-URL).

and

> Your web server is not properly set up to resolve "/.well-known/nodeinfo". Further information can be found in the [documentation](https://docs.nextcloud.com/server/21/go.php?to=admin-setup-well-known-URL).

The link in the admin page redirects to: https://docs.nextcloud.com/server/21/admin_manual/issues/general_troubleshooting.html#service-discovery

### Expected behaviour
The documentation should contain info on how to solve the issues.
Where should `/.well-known/webfinger` redirect to?
Where should `/.well-known/nodeinfo` redirect to?

### Actual behaviour
This documentaton section only covers where to redirect `caldav` autodiscovery to.
It does not mention `webfinger` and where to redirect `/.well-known/webfinger` to.
It does not mention `nodeinfo` and where to redirect `/.well-known/nodeinfo` to.

The documentation (latest) does not mention **[webfinger](https://docs.nextcloud.com/server/21/admin_manual/search.html?q=webfinger&check_keywords=yes&area=default)** at all anywhere.

The documentation (latest) does not mention **[nodeinfo](https://docs.nextcloud.com/server/21/admin_manual/search.html?q=nodeinfo&check_keywords=yes&area=default)** at all anywhere.

The term **webfinger** can be found in the [server/latest](https://docs.nextcloud.com/server/latest/admin_manual/installation/example_openbsd.html?highlight=webfinger) version of the OpenBSD `httpd(8)` example.

I tried to extrapolate a working `location { }` block for `nginx` from that but was unsuccessful. The error remained.

What I tried in relation to the [nginx config example](https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html?highlight=well-known) (latest, but seems the same for [21](https://docs.nextcloud.com/server/21/admin_manual/installation/nginx.html?highlight=well-known).)

```
    location = /.well-known/webfinger {
      return 301 "$scheme://$host/public.php?service=webfinger";
    }
```

In some very old nginx config example I also found
```
    # The following 2 rules are only needed for the user_webfinger app.
    # Uncomment it if you're planning to use this app.
    rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
    rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;
```
which does not work as well.

I dug out the [older documentation for NC 19](https://docs.nextcloud.com/server/19/admin_manual/issues/general_troubleshooting.html) which shows some code for handling `webfinger` but this does not work either.

I've tried pretty much every version suggested in [Unavoidable security & setup warnings with NC 21 update](https://help.nextcloud.com/t/unavoidable-security-setup-warnings-with-nc-21-update/108667/56).
(trying `index.php` and `public.php` with different parameters, etc.)

As user *nursoda*  [suggested in their posting](https://help.nextcloud.com/t/unavoidable-security-setup-warnings-with-nc-21-update/108667/56) I've even replaced my Nextcloud config file for `nginx` which carried me fine all the way from NC 14 until now with the [nginx config template](https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html#nextcloud-in-the-webroot-of-nginx).

I'm happy that my Nextcloud 21 still works and I haven't found anything broken so far, but the `webfinger` error remains. Interestingly the `nodeinfo` error was resolved.

In conclusion after spending way too much time:
- The documentation needs some love to accomodate for the presented error messages
- Using the nginx example configuration still shows the `webfinger` error.
- There may even be a flaw in the test for `webfinger`.
- The `webfinger` error may be related to some combination of NC-Apps or require a specific one to be active which is not installed by default or which may be common, but deactivated on some instances.

### Server configuration

**Operating system:** FreeBSD 12.2-p9

**Web server:** nginx/1.21.0

**Database:** Postgres 13.3

**PHP version:** 7.4.20

**Nextcloud version:** 21.0.3.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgrade from working 20.0.11.1.

**Where did you install Nextcloud from:** Web Updater on Admin Page.

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
> No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - analytics: 3.5.1
  - calendar: 2.3.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 4.0.0
  - contactsinteraction: 1.2.0
  - cookbook: 0.8.4
  - dashboard: 7.1.0
  - dav: 1.17.1
  - deck: 1.4.2
  - event_update_notification: 1.3.0
  - external: 3.8.2
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_accesscontrol: 1.11.0
  - files_automatedtagging: 1.11.0
  - files_pdfviewer: 2.1.0
  - files_retention: 1.10.1
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - flow_notifications: 1.1.0
  - groupfolders: 9.0.2
  - integration_discourse: 1.0.0
  - integration_github: 1.0.0
  - integration_gitlab: 1.0.0
  - integration_zammad: 1.0.1
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - polls: 2.0.6
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - quota_warning: 1.10.0
  - ransomware_protection: 1.10.1
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - socialsharing_email: 2.2.0
  - spreed: 11.2.2
  - systemtags: 1.11.0
  - tasks: 0.13.6
  - terms_of_service: 1.7.1
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_gateway: 0.19.0
  - twofactor_totp: 6.1.0
  - twofactor_u2f: 6.2.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - user_usage_report: 1.5.0
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflow_ocr: 1.21.0
  - workflow_script: 1.6.0
  - workflowengine: 2.3.0

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "blackmoor.maclemon.at"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "21.0.3.1",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "log_type": "owncloud",
        "logfile": "\/usr\/local\/www\/nextcloud_data\/nextcloud.log",
        "loglevel": 0,
        "logdateformat": "c",
        "theme": "",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "preview_max_scale_factor": 1,
        "app_install_overwrite": [
            "joplin"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chromium 91 (irrelevant)

**Operating system:** macOS 10.15.7 (Catalina) (irrelevant)

### Logs

<!--- Reports without logs might be closed as unqualified reports! -->

#### Web server error log
<details>
<summary>Web server error log</summary>
No error is logged.
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Does not apply.
</details>

#### Browser log
<details>
<summary>Browser log</summary>
Does not apply
</details>

**Comment by kesselb** [comment]
> Where should /.well-known/webfinger redirect to?
> Where should /.well-known/nodeinfo redirect to?

To index.php 

![image](https://user-images.githubusercontent.com/3902676/124829959-904e0080-df79-11eb-9cbc-f2c7cfae7707.png)

as described in the documentation https://docs.nextcloud.com/server/21/admin_manual/installation/nginx.html

**Comment by bkraul** [comment]
This does not work for what is reported as the warning remains.

**Comment by masterwishx** [comment]
is it solved ? having same problem
