### ISSUE TITLE
After upgraded to NC 22.0.0, settings is no longer available

### ISSUE THREAD

**Issue by z0ow** [nextcloud/server#27868]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Manually upgrade NC21.0.3 to NC22.0.0 through the official server package (via nextcloud.com -> server).
2. Use `php occ upgrade` to finish the upgrade process.
3. Open the settings page then got `Server Internal Error` with Request ID `YOZWJNxLUDRjOubcPbLajQAAAA4`

### Expected behaviour
Tell us what should happen

The expected behavior is everything working well after upgrading whatever the upgrade method is.

### Actual behaviour
Tell us what happens instead

As described in reproduce steps.

### Server configuration

**Operating system:** CentOS 7.9.2009

**Web server:** Apache 2.4.48

**Database:** MySQL 8.0.25

**PHP version:** 8.0.8

**Nextcloud version:** (see Nextcloud admin page) 22.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** older nextcloud (21.0.3)

**Where did you install Nextcloud from:**https://download.nextcloud.com/server/releases/nextcloud-22.0.0.zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

Enabled:
  - accessibility: 1.7.0
  - activity: 2.15.0
  - apporder: 0.13.0
  - camerarawpreviews: 0.7.11
  - caniupdate: 0.2.0
  - checksum: 1.1.2
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dav: 1.18.0
  - dicomviewer: 1.2.2
  - drawio: 1.0.1
  - duplicatefinder: 0.0.8
  - extract: 1.3.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_external: 1.12.1
  - files_mindmap: 0.0.24
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.13.2
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - groupfolders: 9.0.2
  - logreader: 2.7.0
  - lookup_server_connector: 1.9.0
  - mail: 1.10.0
  - metadata: 0.13.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.9.0
  - ocdownloader: 1.7.11
  - onlyoffice: 7.0.4
  - password_policy: 1.12.0
  - photos: 1.4.0
  - previewgenerator: 3.1.1
  - privacy: 1.6.0
  - provisioning_api: 1.11.0
  - qownnotesapi: 20.9.0
  - quota_warning: 1.10.0
  - recognize: 1.4.2
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - side_menu: 1.25.0
  - survey_client: 1.10.0
  - systemtags: 1.11.0
  - text: 3.3.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.1
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.6.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0

Disabled:
  - admin_audit
  - audioplayer
  - bookmarks
  - bruteforcesettings
  - calendar
  - circles
  - contacts
  - dashboard
  - data_request
  - encryption
  - files_accesscontrol
  - files_antivirus
  - files_downloadactivity
  - files_lock
  - files_readmemd
  - music
  - printer
  - ransomware_detection
  - ransomware_protection
  - sharingpath
  - spreed
  - support
  - uploaddetails
  - user_ldap
  - video_converter
  - w2g2
  - workflow_pdf_converter
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```

{"reqId":"YOZWJNxLUDRjOubcPbLajQAAAA4","level":0,"time":"2021-07-08T01:34:28+00:00","remoteAddr":"192.168.100.96","user":"admin","app":"apporder","method":"GET","url":"/settings/user","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YOZWJNxLUDRjOubcPbLajQAAAA4","level":0,"time":"2021-07-08T01:34:28+00:00","remoteAddr":"192.168.100.96","user":"admin","app":"camerarawpreviews","method":"GET","url":"/settings/user","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YOZWJNxLUDRjOubcPbLajQAAAA4","level":0,"time":"2021-07-08T01:34:28+00:00","remoteAddr":"192.168.100.96","user":"admin","app":"serverDI","method":"GET","url":"/settings/user","message":"The requested alias \"PreviewManager\" is deprecated. Please request \"OCP\\IPreview\" directly. This alias will be removed in a future Nextcloud version.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YOZWJNxLUDRjOubcPbLajQAAAA4","level":0,"time":"2021-07-08T01:34:28+00:00","remoteAddr":"192.168.100.96","user":"admin","app":"caniupdate","method":"GET","url":"/settings/user","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YOZWJNxLUDRjOubcPbLajQAAAA4","level":0,"time":"2021-07-08T01:34:28+00:00","remoteAddr":"192.168.100.96","user":"admin","app":"dicomviewer","method":"GET","url":"/settings/user","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YOZWJNxLUDRjOubcPbLajQAAAA4","level":0,"time":"2021-07-08T01:34:28+00:00","remoteAddr":"192.168.100.96","user":"admin","app":"drawio","method":"GET","url":"/settings/user","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YOZWJNxLUDRjOubcPbLajQAAAA4","level":0,"time":"2021-07-08T01:34:28+00:00","remoteAddr":"192.168.100.96","user":"admin","app":"extract","method":"GET","url":"/settings/user","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YOZWJNxLUDRjOubcPbLajQAAAA4","level":0,"time":"2021-07-08T01:34:28+00:00","remoteAddr":"192.168.100.96","user":"admin","app":"files_mindmap","method":"GET","url":"/settings/user","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YOZWJNxLUDRjOubcPbLajQAAAA4","level":0,"time":"2021-07-08T01:34:28+00:00","remoteAddr":"192.168.100.96","user":"admin","app":"files_sharing","method":"GET","url":"/settings/user","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YOZWJNxLUDRjOubcPbLajQAAAA4","level":0,"time":"2021-07-08T01:34:28+00:00","remoteAddr":"192.168.100.96","user":"admin","app":"metadata","method":"GET","url":"/settings/user","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YOZWJNxLUDRjOubcPbLajQAAAA4","level":0,"time":"2021-07-08T01:34:28+00:00","remoteAddr":"192.168.100.96","user":"admin","app":"ocdownloader","method":"GET","url":"/settings/user","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YOZWJNxLUDRjOubcPbLajQAAAA4","level":0,"time":"2021-07-08T01:34:28+00:00","remoteAddr":"192.168.100.96","user":"admin","app":"qownnotesapi","method":"GET","url":"/settings/user","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YOZWJNxLUDRjOubcPbLajQAAAA4","level":0,"time":"2021-07-08T01:34:28+00:00","remoteAddr":"192.168.100.96","user":"admin","app":"side_menu","method":"GET","url":"/settings/user","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11"}
{"reqId":"YOZWJNxLUDRjOubcPbLajQAAAA4","level":3,"time":"2021-07-08T01:34:28+00:00","remoteAddr":"192.168.100.96","user":"admin","app":"index","method":"GET","url":"/settings/user","message":"Class \"OCP\\User\" not found","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","version":"22.0.0.11","exception":{"Exception":"Exception","Message":"Class \"OCP\\User\" not found","Code":0,"Trace":[{"file":"/home/www-data/ServerData/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/home/www-data/ServerData/nextcloud/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\PersonalSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"personal-info","_route":"settings.PersonalSettings.index"}]},{"file":"/home/www-data/ServerData/nextcloud/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/user"]},{"file":"/home/www-data/ServerData/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/home/www-data/ServerData/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"Error","Message":"Class \"OCP\\User\" not found","Code":0,"Trace":[{"file":"/home/www-data/ServerData/nextcloud/lib/private/legacy/OC_App.php","line":664,"function":"include"},{"file":"/home/www-data/ServerData/nextcloud/lib/private/Settings/Manager.php","line":257,"function":"getForms","class":"OC_App","type":"::","args":["personal"]},{"file":"/home/www-data/ServerData/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":115,"function":"getPersonalSections","class":"OC\\Settings\\Manager","type":"->","args":[]},{"file":"/home/www-data/ServerData/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":63,"function":"formatPersonalSections","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info"]},{"file":"/home/www-data/ServerData/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":147,"function":"getNavigationParameters","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info"]},{"file":"/home/www-data/ServerData/nextcloud/apps/settings/lib/Controller/PersonalSettingsController.php","line":67,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal","personal-info"]},{"file":"/home/www-data/ServerData/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"index","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->","args":["personal-info"]},{"file":"/home/www-data/ServerData/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/home/www-data/ServerData/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Settings\\Controller\\PersonalSettingsController"},"index"]},{"file":"/home/www-data/ServerData/nextcloud/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Settings\\Controller\\PersonalSettingsController","index",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"section":"personal-info","_route":"settings.PersonalSettings.index"}]},{"file":"/home/www-data/ServerData/nextcloud/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/settings/user"]},{"file":"/home/www-data/ServerData/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/home/www-data/ServerData/nextcloud/apps/ocdownloader/settings/personal.php","Line":14},"CustomMessage":"--"}}

</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
The ocDownloader app calls `\OCP\User::checkLoggedIn();` at https://github.com/e-alfred/ocdownloader/blob/0c3acdcbbe88329180a10a4afe61660c948b1e23/settings/personal.php#L14

As `OCP\User` is not available anymore and was deprecated for a while the app crashes. ocDownloader app is not released yet for Nextcloud 22.
