### ISSUE TITLE
NC 22, "Add group" Button just doing nothing

### ISSUE THREAD

**Issue by rotdrop** [nextcloud/server#27866]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Upgrade or install NextCloud v22
2. Become an Admin or Groupd-Admin and navigate to "Users"
3. Click on "Add group"

### Expected behaviour
The "Add group" element should turn into a text input element and prompt for the new group name

### Actual behaviour
NOTHING, the "Add group" element does not turn into a text input element

### Server configuration

**Operating system:**
Linux Ubunt Focal, kernel 5.12.9

**Web server:**
Apache2

**Database:**
mariadb, as installed on Ubuntu Focal

**PHP version:**
PHP 8.0.8, ondrej PPA "deb http://ppa.launchpad.net/ondrej/php/ubuntu focal main"

**Nextcloud version:** (see Nextcloud admin page)
v22, just upgrade to the "beta" channel

**Updated from an older Nextcloud/ownCloud or fresh install:**
v21, after applying the latest update

**Where did you install Nextcloud from:**
YOUR SERVER

**Signing status:**
<details>
<summary>Signing status</summary>

What do you mean by "Signing status"????? This question is just confusing.

I SKIP THE REMAINING QUESTIONS OF THIS QUESTIONAIR. THIS IS JUST TOO MUCH.

"Add Group" is just broken, doing nothing in V22. Full stop.

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by szaimen** [comment]
See https://github.com/nextcloud/server/pull/27864

**Comment by rotdrop** [comment]
Does not seem to be exactly the same. In the video int #27864 the "Add group" button actually turns into a text-input element. However, my experienced behavior of NC 22 is that just NOTHING happens.

I tried to hack the associated Vue source. It seems that the "@click" handler in line 41 of  ```apps/settings/src/views/Users.vue```:

```
@click="toggleAddGroupEntry(true)"
```

just is not triggered. I even replaced that line by a simple "alert('foobar')" and it did not show up. Seemingly the AppNavigationItem is no longer clickable as of NC 22.

**Comment by cwilby** [comment]
@rotdrop it looks like `AppNavigationItem` (the component that `@click` directive is being added to) does not define an `onClick` prop: https://github.com/nextcloud/nextcloud-vue/blob/master/src/components/AppNavigationItem/AppNavigationItem.vue
