### ISSUE TITLE
Drop APC support

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#2786]
Will still allow APC as a memcache backend. However APC has been unmaintained for at least 4 years now https://pecl.php.net/package/APC Not even debian ships it anymore. And I bet that 99.9% of the users that configured the APC backend actually use APCu.

Also we have no way to test this backend.

So I vote to delete it.

CC: @icewind1991 @MorrisJobke @LukasReschke

**Comment by MorrisJobke** [comment]
Makes sense 👍

**Comment by MorrisJobke** [comment]
Fixed with #2946
