### ISSUE TITLE
[CLI] [updater.phar] Upgrade nextcloud to a specific target version and not to the last release

### ISSUE THREAD

**Issue by Benouare** [nextcloud/server#27874]
Hi.

Move to => https://github.com/nextcloud/updater/issues/336

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

_____________________

**Is your feature request related to a problem? Please describe.**
I currently have X nextcloud servers, one of them is used for test purpose. I am currently testing new versions on it, and if everything is ok, i am making the upgrade on others nextcloud instances. 

I am currently using the 
`sudo -u www-data php /var/www/nextcloud/updater/updater.phar --no-interaction`
That's is working well and that is a great tool. 

What happen : 

So on my test server I did the upgrade via CLI. Nextcloud goes from (it's an example, the version used may not exists) from 19.0.1 to 20.1.5. 
I test this server for a while, and after that i have checked that everything was good, I think about upgrade the other instances. Because i know that 'normally' 20.1.5 was/is ok.

After some days, weeks or what ever, it was the time to execute the upgrade on my production servers. 
Same thing, i was running the updater.phar. But, at this time the 20.1.6 was released, and nextcloud goes direclty from 19.0.1 to 20.1.6 that i didnt test on my test server! 

And as "always", I get an issue on this version(20.1.6) that i didnt have on the previous version(20.1.5). 

**Describe the solution you'd like**

I think that upgrade to the last version of nextcloud by default is the good behavior, but i propose to have kind of parameter, to be able to specify the target version that i would like to have. 
Current version : 
`sudo -u www-data php /var/www/nextcloud/updater/updater.phar --no-interaction`
With this feature: 
`sudo -u www-data php /var/www/nextcloud/updater/updater.phar --no-interaction --target 20.1.5`

**Describe alternatives you've considered**

Hum... --target could be the url of the package?  or something like --next-one to get the version available just after the current one. 

**Additional context**

As i said, the version that I used in this example are fake. In my case, I had an issue because of my config.php that completely block my instance on 21.0.3 and didnt block in 21.0.2. 
I clearly need to fix this issue on 21.0.3 BUT, at first, i would like to control my update process.
If i take the time to test/validate the version X, i want to be able to upgrade to X and not to Y. 

Cheers!

**Comment by compumatter** [comment]
Completely agree with this feature request.

**Comment by GregorKopka** [comment]
@Benouare that feature still does not exist, why was this closed?
