### ISSUE TITLE
 Calendar entry marked as busy is also busy for creator 

### ISSUE THREAD

**Issue by bkolbe** [nextcloud/server#2787]
Calendar shows only Busy when selecting as Busy. Also for the creating user. The creating user should see the Calendar-Item with full information.

### Steps to reproduce
1. Create an Calendar item in you personal autogenerated calendar
2. Create Name "Test Meeting"
2. set "when shared show only busy"
3. Now the creator can only see "busy" not "Test Meeting". that is incorrect

### Expected behaviour
The creator should see "Test Meeting"

### Actual behaviour
The Calendar entry is changed to busy also for the creator

### Server configuration
Centos 7

**Web server:**
nginx

**Database:**
mariadb

**PHP version:**
php56
**Server version:** (see your admin page)
11.0.0
**Calendar version:** (see the apps page)
1.4.1
**Updated from an older installed version or fresh install:**
update from 10.0.2
**Signing status (ownCloud/Nextcloud 9.0 and above):**
Nextcloud
```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ldap

### Client configuration
**Browser:**
Chrome, Firefox

**Operating system:**
Windows, Lnux

**CalDAV-clients:**

**Comment by MorrisJobke** [comment]
Please reopen in the calendar app: https://github.com/nextcloud/calendar/issues

**Comment by georgehrke** [comment]
marking events as busy / hiding them is a task of the CalDAV server

**Comment by sehucke** [comment]
Hi!
I think I am facing the same problem with some of my tasks entries. I just upgraded from OC 9.1.2 to NC 11.0.0. Since then, I am not able to read the content of some of my tasks any more:

![grafik](https://cloud.githubusercontent.com/assets/7911080/21619810/a2af68ee-d1f1-11e6-9739-e709b5ad97e7.png)

How to reproduce:
I have set the privacy property to "confidential" via the Android app [OpenTasks](https://play.google.com/store/apps/details?id=org.dmfs.tasks). However, tasks with privacy set to "private", "public" or "none" are not affected and displayed normally.

**Comment by tsdmgz** [comment]
Got hit by this bug too.

Thunderbird 45.6/Lightning 4.7.6

Creating an event with Privacy set to "Show Time and Date Only" triggers it. Mucking around the database and all I see is `SUMMARY:Busy`. Setting event privacy to either Public or Private works as expected.

**Comment by booleon** [comment]
Same for me : 
nginx : 1.10.2
PHP : 7.0.14-2
NC : 11.0.0 fresh install
Calendar : 1.4.1

It's literally renamed, can't recover original  event name. It's happen when the whole calendar is shared to an other intern user.

**Comment by MathiasRenner** [comment]
I can confirm this issue.

**Comment by plauzenbaer** [comment]
I can confirm this issue

**Comment by georgehrke** [comment]
@MathiasRenner @plauzenbaer Please refrain from commenting when you can't provide more information. Just use [GitHub Reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) to signal that you have the same issue. This way you don't spam everyones inbox here.
Thx :)
