### ISSUE TITLE
dropped "\OC_DB::getDbStructure" disabled backup from within nextcloud (No nextbackup more)

### ISSUE THREAD

**Issue by natrius** [nextcloud/server#27892]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
`\OC_DB::getDbStructure` got dropped that leads to nextbackup not working anymore according to https://github.com/pbek/nextbackup/issues/50

**Describe the solution you'd like**
Find a new solution to make it possible to create a backup from within nextcloud again.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/commit/8b64e92b9262d2a2eec6345685ce421050f95c66#diff-0228b9248e0f5948a46a65b54ec89dfbe79280820dcc69c27e0fe7bfc414043aL59
