### ISSUE TITLE
Consider using mailcheck to ensure email addresses are correct

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#279]
This library seems to be useful in a lot of places for Nextcloud: https://github.com/mailcheck/mailcheck

It can give a hint whether the email is correct for:
- the personal settings
- when sharing via email
- for the Contacts app, cc @Henni @irgendwie @skjnldsv 
- for the Calendar app when inviting people, cc @georgehrke @raghunayyar 
- for the Mail app of course when typing a new recipient email, cc @ChristophWurst @Gomez 

So it might make sense to have this library in core if we think it’s useful. We need a proper way to display the hint, likely via tipsy tooltip.

What do you think @karlitschek @LukasReschke @MorrisJobke @nextcloud/designers?

**Comment by karlitschek** [comment]
looks useful :+1:

**Comment by mabkenar** [comment]
That's conceptually very nice to have. But I tried the [demo](http://kicksend.com/join) of this particular library and it is not really exact. It "corrects" perfectly valid email addresses with non-existent domains. For example, when I enter my perfectly valid email address username@fz-juelich.de, it suggests me to change it to username@fz-juelich.net, while the fz-juelich.net domain is not even active.

**Comment by jancborchardt** [comment]
@mabkenar it seems to try to correct basically all .de addresses to .net and .at to .com … try hahaha@gmx.de for example. Maybe something to open an issue about on their end, or I guess it’s possible to modify that via parameters.

**Comment by rullzer** [comment]
I don't think having this makes much sense. Because it is impossible to come up with sane defaults that will work for all our users. The thing is that is just matches on domains you provide or extentions or what not.

But just because I'm in NL doesn't mean that says a lot of the e-mail addresses I want to share with.

**Comment by skjnldsv** [comment]
Like @rullzer , not too sure it's such a great improvement. Sometimes keeping it simple is better. It's cool, but not sure it's worth the time to implement :)

**Comment by skjnldsv** [comment]
Also, with html5 field validation, we already have a email-format validation! Is this enough?

**Comment by georgehrke** [comment]
I think it should be enough. I will be using it in the calendar: https://github.com/nextcloud/calendar/pull/750/files#diff-6f8cfdd1cf41db08991d3be90fa010dcR161

**Comment by skjnldsv** [comment]
And it's already in the users settings and will be soon in the new users list:
![capture d ecran_2018-03-21_15-13-49](https://user-images.githubusercontent.com/14975046/37714743-9829acb0-2d1a-11e8-80f3-cd248d15d86d.png)

**Comment by MorrisJobke** [comment]
> Also, with html5 field validation, we already have a email-format validation! Is this enough?

Yes - makes sense 👍

**Comment by jancborchardt** [comment]
Then I'm closing this. :)
