### ISSUE TITLE
Array to string conversion at /home/jeziks/public_html/nextcloud/lib/private/L10N/L10NString.php#79

### ISSUE THREAD

**Issue by adosix** [nextcloud/server#27907]
this log repeats approximately every 20sec
nextcloud version 21.0.3
deployed on Ubuntu 20.04

![Screenshot from 2021-07-10 13-13-23](https://user-images.githubusercontent.com/44939175/125161122-d0330480-e180-11eb-8fce-627465025f66.png)

**Comment by davidcartwright** [comment]
I'mm having the same issue and it also started yesterday.

**Comment by bpcurse** [comment]
Seems to be related to the update notification of "passwords" app

![Bildschirmfoto_2021-07-19_16-44-39](https://user-images.githubusercontent.com/29312856/126179331-c06d4a84-44ed-4997-ab44-19235ebdb032.png)

**Comment by szaimen** [comment]
I suppose this is still happening on NC21.0.4?

**Comment by squid-f** [comment]
Hi. 
I am on NC21.0.4 with an Nginx server and I have exactly the same issue.
How can I help to troubleshoot this?

**Comment by squid-f** [comment]
I had also the weird Password app update message, as mentioned by @bpcurse . 
I just made the update. I will monitor whether this error message has disappeared.

**Comment by nooblag** [comment]
Getting this error on Nextcloud 22.2.0 with PHP 8.0.11, nginx 1.18.0, psql 10.18.

**Comment by squid-f** [comment]
Hi. I confirmed again today the link with the weird update notification sent by the Password app.
I think this issue should be addressed as well to the Password app developers.
