### ISSUE TITLE
weather status widget: set location programmatically

### ISSUE THREAD

**Issue by yoyoyonas** [nextcloud/server#27908]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
The location for the weather status widget can only be set by each individual user via the web GUI. For organizations, where most users reside in the same city, it would be very helpful to let the admin predefine the location. 

**Describe the solution you'd like**
Two (for my use case equal) non-exclusive solutions:
1. Introduce a default weather location setting in `config.php` or in the admin web GUI, which applies to all/new users.
2. Make the weather location per user available to be set (and read) by `occ`.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
