### ISSUE TITLE
No user avatars in "Shared with others"

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#27900]
### Steps to reproduce

1. Send the image via Talk app.
2. Select "Shared with others" in the Files app.

Avatars of users for whom the image was shared by Talk are not displayed:

![obraz](https://user-images.githubusercontent.com/47037905/125076252-fa70bd80-e0bf-11eb-93ef-b9acfd81c163.png)

**Apps:**

**Nextcloud version:** 22.0.0
**Talk version:** 12.0.0

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
