### ISSUE TITLE
calendar: Not possible to undo "unshare from me"

### ISSUE THREAD

**Issue by storyjesse** [nextcloud/server#27902]
Nextcloud version _(eg, 20.0.5)_: `20.0.8`
Operating system and version _(eg, Ubuntu 20.04)_: `unknown`
Apache or nginx version _(eg, Apache 2.4.25)_:  `unknown`
PHP version _(eg, 7.4)_: `unknown`

I'm filing this as a bug because I believe it's an oversight not a *"feature"*.

**I clicked "unshare from me" on a shared calendar and now I want it back. But there does not seem to be any way to achieve this without editing the database manually.**

What we have tried:
- The user who owns the calendar tried un-sharing it from the group I'm a part of and then re-sharing it to this group again.
- I have been removed and re-added to the group that the calendar is shared with.
- The calendar has been shared with me directly and this results in me having access to the calendar again but this is not a long term solution because the owner of the calendar is a shared system-user account and future admins using this account will see that I am a member of the group and so may remove the direct share as general housekeeping (it doesn't need to be shared with me twice right?)

I assume there must be somewhere in the database that lists me as having "Unshared from me" this calendar and I again assume that this could be manually reset. Can anyone tell me if this is true and/or whether doing so is likely to cause other errors?

EXPECTED BEHAVIOR:
There should be somewhere in the web interface `/index.php/apps/calendar/` to see *Deleted shares* just like there is in the files app `/index.php/apps/files/?dir=/&view=deletedshares`.

---

*Note: I have also posted this on the forum but I believe there is currently no answer to this problem. If I get a response on the forum I will mark this issue closed myself or delete it. (assuming it's not locked and I can do that)*

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.4? If not, please close this issue. Thanks! :)

**Comment by storyjesse** [comment]
> Is this Issue still valid in NC21.0.4? If not, please close this issue. Thanks! :)

I don't have a way to test this I'm sorry. Our system is still running 20.08, it may be upgraded to 20.11 soon but I think that 21.0.4 is a ways off.

@szaimen was this an issue that is supposed to have been fixed by 21.0.4? If so could you link me to that issue?
