### ISSUE TITLE
Account invite for user without password doesn't contain password creation link

### ISSUE THREAD

**Issue by keunes** [nextcloud/server#27914]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Go to the 'Users' panel
2. Add a username & email address
3. Note that you typed the wrong email address
4. Correct the email address
5. Click "Send welcome-email again"

### Expected behaviour
The (resent) welcome email contains a tokenised link to set a password, given that the user hasn't set one yet.

Expected, because of this https://github.com/nextcloud/server/issues/15770#issuecomment-561676850:
> Add user with name and E-Mail: In this case the user receives an E-Mail with a tokenised link to the lostpassword/reset page. This page lets the user set a new password. No change needed.

### Actual behaviour
The (resent) welcome email doesn't contain such link.

### Server configuration

**Operating system:** Raspbian GNU/Linux 10 (buster)

**Web server:** Apache 2

**Database:** Mariadb

**PHP version:** PHP 7.3.27-1~deb10u1

**Nextcloud version:** 20.0.10

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from older version

**Where did you install Nextcloud from:** 

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
I{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.xxx.xx",
            "nextcloud.mydomain.eu"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.10.1",
        "overwrite.cli.url": "https:\/\/nextcloud.mydomain.eu\/",
        "overwriteprotocol": "https",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false
    }
}
```
</details>

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Happy to provide if necessary.
```
</details>

**Comment by szaimen** [comment]
You misinterpreted something here: https://github.com/nextcloud/server/issues/15770 is not yet implemented.
So lets track this in https://github.com/nextcloud/server/issues/15770
