### ISSUE TITLE
Some feedback of a 1st time user / annoyances, usability

### ISSUE THREAD

**Issue by schittli** [nextcloud/server#27911]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

I'm a 1st time nextcloud user because our provider offers '20GB nexcloud' as a free service. Unfortunately, even the basic functions of nextcloud are quite disappointing. To use your words: I'm always frustrated when:

#### Really? nexcloud does not display the release information?
- **nexcloud does not display its version number**. How are your customers able to decide if they are threatened by a security issue? How do you expect to get useful bug reports if they can't tell you the version number?
- Even the default added "**Nextcloud User Manual**" does not say anything about the Nextcloud release, you write **"Release latest"** - what a shame! Do you really tell us, that this manual always describe the 'latest release' of Nexcloud for the next years? Such behaviour actually shows that the manufacturer has no idea about the basic behaviour of software. I am completely sure that nextcloud is professional, but this kind of behaviour fits a rookie.

#### Bad tested releases
Already after 20 seconds I found the first error as a recipient of a nextcloud shared link. What should I think about the product nextcloud? 
If a user opens the shared Website and tries to upload/create content and presses the + (1) button, then the rendering is wrong **(2)**:

![image](https://user-images.githubusercontent.com/8282673/125192133-7ac12b00-e246-11eb-8c95-8e8269515a82.png)

**Describe the solution you'd like**

The Web Interface usability feels like a beta Version: There are exciting concepts, but the homework has not yet been done. If you don't have any good usability concepts of your own, then take a look at the competitor products that are very successful. Basic use cases are very poor or non-existent.
- As the owner, I was not able to read the shared link password. Does NextCloud expect the customers re-send a new link to the recipients if the Owner does not remember the Password?
- As the owner, I was not able to change the shared link password. A quarter of a century ago I met such concepts... Today, we know that changing a password is much more useful (» usability!) than deleting, recreating and sharing a new shared link.
- I use a cloud-hosted nextcloud service. As the user of this service, I can not centrally configure that every shared link expires by default e.g. after 12 months if the user doesn't change the shared link setting himself. I am CSO of a small company with 150 employees and **I would never use nextcloud as a cloud service** because nextcloud by design prevents the data from staying secure. In a company, there is no reason that shared links are forever available.
- We can create multiple shared links. Why is it not possible to give a name and a short description to a shared link? This is a fatal security problem: After only a few days later, most Nextcloud users no longer know why a link was created - and most will likely act like this: _"I no longer know who uses this link, but so that they can keep working, I'll leave the share as it is_ (for the next 100 years)_."_

**Describe alternatives you've considered**
I hope nextcloud knows the market of these products and the extremely successful big players.

I'm sad that nextcloud couldn't manage to implement at least the basic use cases in a remarkably great implementation in the last years.

All the best!

**Comment by Spartachetto** [comment]
It seems to me that you overlooked a key detail: a free '20GB' account from a provider does not offer you a good test environment for using Nextcloud in a small company with 150 employees. 

Clearly if you'll install Nextcloud somewhere, you'll see that you have an easy access to the version of the software and the possibility of configuring several aspects.
Even a lot of hosted accounts give more possibilities than the 'free 20GB' one you are using.

**Comment by kesselb** [comment]
Thanks for your feedback :+1: In general one issue on GitHub for multiple things is bad. If one issue is resolved a issue is closed. I answered most of your points briefly. If you want to evaluate Nextcloud for your business - talk the our sales: https://nextcloud.com/enterprise/

> If a user opens the shared Website and tries to upload/create content and presses the + (1) button, then the rendering is wrong (2):

I'm not able to reproduce locally or at https://try.nextcloud.com/

> nexcloud does not display its version number. How are your customers able to decide if they are threatened by a security issue? How do you expect to get useful bug reports if they can't tell you the version number?

A customer login as administrator and opens Administration -> Overview. For normal users we don't show the version number yet. Nextcloud 23 will https://github.com/nextcloud/firstrunwizard/issues/82. 

> Even the default added "Nextcloud User Manual" does not say anything about the Nextcloud release, you write "Release latest" - what a shame! Do you really tell us, that this manual always describe the 'latest release' of Nexcloud for the next years? Such behaviour actually shows that the manufacturer has no idea about the basic behaviour of software. I am completely sure that nextcloud is professional, but this kind of behaviour fits a rookie.

The pdf is generated when the release is build. I guess we could show the version number somehow. Feel free to create a new enhancement request for it. 

> As the owner, I was not able to read the shared link password. Does NextCloud expect the customers re-send a new link to the recipients if the Owner does not remember the Password?

Yep. The password is only shown once. You have to change it if you don't remember. I guess that's something that could be changed on demand. 

> As the owner, I was not able to change the shared link password. A quarter of a century ago I met such concepts... Today, we know that changing a password is much more useful (» usability!) than deleting, recreating and sharing a new shared link.

Changing a password for a share link is possible.

> I use a cloud-hosted nextcloud service. As the user of this service, I can not centrally configure that every shared link expires by default e.g. after 12 months if the user doesn't change the shared link setting himself. I am CSO of a small company with 150 employees and I would never use nextcloud as a cloud service because nextcloud by design prevents the data from staying secure. In a company, there is no reason that shared links are forever available.

![image](https://user-images.githubusercontent.com/3902676/126754426-0b1005ef-04f6-4e53-b806-2d3e334c729d.png)

As administrator your are able to set a default expiration date and also enforce a expiration date.

> We can create multiple shared links. Why is it not possible to give a name and a short description to a shared link? This is a fatal security problem: After only a few days later, most Nextcloud users no longer know why a link was created - and most will likely act like this: "I no longer know who uses this link, but so that they can keep working, I'll leave the share as it is (for the next 100 years)."

![image](https://user-images.githubusercontent.com/3902676/126754562-ff202ebd-696b-4ae5-ba6a-09b87064b87c.png)

**Comment by schittli** [comment]
> It seems to me that you overlooked a key detail: a free '20GB' account from a provider does not offer you a good test environment for using Nextcloud in a small company with 150 employees.

Thanks, but this is not the point of this issue.
Of course, we're smart enough to select a user group that would be able to test nextcloud.

**Comment by schittli** [comment]
> I answered most of your points briefly. 
Thanks a lot!, I will review nextcloud.
