### ISSUE TITLE
Corruption in file synced from server (PHP exception-text dumped into content)

### ISSUE THREAD

**Issue by vszakats** [nextcloud/server#27926]
### Steps to reproduce
Not sure how to reproduce. I've created a PDF file by scanning a document with Nextcloud for iOS. The file got uploaded to a Nextcloud server. The upload was fine and the physical copy on the server is correct. But, when this file got automatically synced to a desktop machine via Nextcloud Desktop Client 3.1.2 (macOS), the name, timestamp and _size_ of the file was correct, but the first bytes of the file content got replaced by this message:
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>OCA\DAV\Connector\Sabre\Exception\FileLocked</s:exception>
  <s:message>"scan 21-02-11 13-28-04.pdf" is locked</s:message>
</d:error>
```

### Expected behaviour
I expect that files would replicate without corruption.

### Actual behaviour
File synced from the server was corrupted.

### Server configuration
**Operating system:**
Raspberry Pi 4

**Web server:**

**Database:**
sqlite

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 20.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 18 → 19 →

**Where did you install Nextcloud from:**
https://hub.docker.com/_/nextcloud/

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

Please let me know if you need more environment (or other) details. This looks like the DAV server code is susceptible to dump an exception text into the file content being returned to a client request, instead of the corresponding chunk of file content.

Top of corrupted file:
![Screen Shot 2021-02-11 at 14 13 43](https://user-images.githubusercontent.com/1446897/107760294-c91ade00-6d29-11eb-990a-17a18b1a0330.png)

Top of original file:
![Screen Shot 2021-02-11 at 14 14 00](https://user-images.githubusercontent.com/1446897/107641661-2a807580-6c74-11eb-862e-dc1aa8dd03fc.png)

**Comment by josselex** [comment]
I get the same corruption in multiple files:

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception</s:exception>
  <s:message>An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`, `lock`, `ttl`) VALUES(?, ?, ?)' with params ["files\/bb001434841301c62410bd7bf78abe3d", 1, 1626196361]:

SQLSTATE[HY000]: General error: 1205 Lock wait timeout exceeded; try restarting transaction</s:message>
</d:error>
```

**Comment by szaimen** [comment]
Is this still happening on NC21.0.3 or above?

**Comment by vszakats** [comment]
@szaimen: Do you happen to have a pointer to the patch/PR that addressed this issue in 21.0.3?

(Meanwhile, I'm on 22 and more powerful hardware now, but will give it a go to test this again.)

**Comment by vszakats** [comment]
From the PHP exception text (and server version) included in this report, it is possible to tell which lines generated the exception. Then it is probably possible to tell what can trigger such exception. Next is to find out how such an exception output may end-up in a file-content put on the wire, to a client.

If there is any more _essential information_ missing, it'd be probably useful to know what it is.

**Comment by szaimen** [comment]
So it is still valid on NC21.0.3 or above?

**Comment by vszakats** [comment]
@szaimen: Am I assuming incorrectly that you are mentioning 21.0.3 specifically, because there was something changed there that might fix this? If so, could you provide pointers?

If you just want reporters to re-test it to see if the issue "fixed itself", it won't be easy, due its hard-to-reproduce nature.

**Comment by vszakats** [comment]
I think the `needs info` tag should be clarified here. The impression is that developers are waiting some kind of info, possibly blind re-tests with newer versions, without pointers to attempted fixes. This doesn't look productive, so closing this for now.
