### ISSUE TITLE
Notified app update not available

### ISSUE THREAD

**Issue by pludi** [nextcloud/server#27935]
### Steps to reproduce
- Install `nextcloud/cookbook` v0.8.4
- Wait for notification that an update to 0.9.1 is available
- Open the notification

### Expected behaviour
Update to 0.9.1 actually available

### Actual behaviour
No update is shown. The [GitHub release page](https://github.com/nextcloud/cookbook/releases) shows 0.9.1 available, but the entry in the [App directory](https://apps.nextcloud.com/apps/cookbook) doesn't.

## Server configuration detail

**Operating system:** FreeBSD 12.2-RELEASE-p7 FreeBSD 12.2-RELEASE-p7 GENERIC amd64

**Webserver:** nginx/1.18.0 (fpm-fcgi)

**Database:** pgsql PostgreSQL 12.6 on amd64-portbld-freebsd12.2, compiled by FreeBSD clang version 10.0.1 (git@github.com:llvm/llvm-project.git llvmorg-10.0.1-0-gef32c611aa2), 64-bit

**PHP version:** 

7.4.18
Modules loaded: Core, date, libxml, pcre, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, apcu, bcmath, bz2, ctype, curl, dom, mbstring, fileinfo, filter, gd, gmp, iconv, imagick, intl, json, exif, mcrypt, openssl, PDO, pgsql, posix, readline, SimpleXML, xml, xmlwriter, zip, zlib, pdo_pgsql, redis, xmlreader, xsl, Zend OPcache

**Nextcloud version:** 21.0.3 - 21.0.3.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** Source

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - bookmarks: 4.2.2
 - calendar: 2.3.0
 - cloud_federation_api: 1.4.0
 - comments: 1.11.0
 - contacts: 4.0.0
 - contactsinteraction: 1.2.0
 - cookbook: 0.8.4
 - dav: 1.17.1
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_pdfviewer: 2.1.0
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - forms: 2.2.4
 - issuetemplate: 0.7.0
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - news: 16.0.0
 - nextcloud_announcements: 1.10.0
 - notes: 4.1.0
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - password_policy: 1.11.0
 - photos: 1.3.0
 - previewgenerator: 3.1.1
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - recommendations: 1.0.0
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - systemtags: 1.11.0
 - tasks: 0.13.6
 - text: 3.2.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.0
 - twofactor_totp: 6.1.0
 - twofactor_u2f: 6.2.0
 - updatenotification: 1.11.0
 - viewer: 1.5.0
 - workflowengine: 2.3.0
Disabled:
 - admin_audit
 - dashboard
 - encryption
 - files_external
 - files_videoplayer
 - firstrunwizard
 - support
 - survey_client
 - user_ldap
 - user_status
 - weather_status

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nc.ludikovsky.name",
        "darp7imrofm2pwl66fifvftthfkok375efxj3wefkuzpwc7unqanoxyd.onion"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/nc.ludikovsky.name",
    "dbtype": "pgsql",
    "version": "21.0.3.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "log_type": "file",
    "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
    "loglevel": 0,
    "trashbin_retention_obligation": "auto",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "updater.release.channel": "stable",
    "app_install_overwrite": [
        "calendar",
        "twofactor_yubikey",
        "issuetemplate"
    ],
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***",
        "timeout": 0
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0

**Operating system:** Mint

## Logs

<details><summary>Web server error log</summary>

```
N/A
```
</details>

<details><summary>Nextcloud log</summary>

```
N/A
```
</details>

<details><summary>Browser log</summary>

N/A
</details>

**Comment by christianlupus** [comment]
This is no real bug. The update of the 0.9.1 (as well as 0.9.0) was revoked to avoid issues with a database migration. The only bug is that the notification is still present. Looking at apps.nextcloud.com you find the latest cookbook version is 0.8.4. See also nextcloud/cookbook#767.
