### ISSUE TITLE
Hub: pretty icons

### ISSUE THREAD

**Issue by mmeeks** [nextcloud/server#27945]
Just did a new Nextcloud install on my laptop (well perhaps it was an older version) - and saw this:

![image](https://user-images.githubusercontent.com/122848/125076431-cf826b80-e0b7-11eb-9b69-6ca8282a5350.png)

Would be lovely to have something that is not that gear; but worth checking if this is the case in the latest Nextcloud. Pedro - I assume we can provide some artwork - except that I think richdocuments is not installed at the time this is show, so we prolly want this in the NC core somehow (?)

**Comment by juliushaertl** [comment]
Moving over to server. We would basically need to ship the app icons with the server and make sure they are added to the corresponding apps:

https://github.com/nextcloud/server/blob/9c6b01abeba6928bd43dc71ac2f2372f2ea0c49f/core/src/components/setup/RecommendedApps.vue#L70-L90

cc @nextcloud/designers I think we can just reuse the existing app icons we have there, what do you think:

- Collabora Online (richdocuments) https://github.com/nextcloud/richdocuments/blob/master/img/app-dark.svg
- Collabora Online - Built-in CODE server (richdocumentscode) https://github.com/CollaboraOnline/richdocumentscode/blob/master/img/app-dark.svg
- Talk https://github.com/nextcloud/spreed/blob/master/img/app-dark.svg

**Comment by jancborchardt** [comment]
Sounds good @juliushaertl!
