### ISSUE TITLE
Duplicator Update Will not complete update

### ISSUE THREAD

**Issue by JasonNaughton** [nextcloud/server#27954]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Running own cloud version 21.0.3.1
2. Update for the duplicator from 0.08 to 0.09 came out
3. Attempted to update and the Update crashed

### Expected behaviour
I was using my nextcloud instance for the past few weeks without any issues.  The duplicator update came out 0.0.9 and I attempted the update via the web interface.   Sadly the response was:

Update to 21.0.3.1
Exception: Database error when running migration latest for app duplicatefinder

Detailed logs 
Preparing update
Set log level to debug
Repair step: Repair MySQL collation
Repair info: All tables already have the correct collation -> nothing to do
Repair step: Repair SQLite autoincrement
Repair step: Copy data from accounts table when migrating from ownCloud
Repair step: Drop account terms table when migrating from ownCloud
Updating database schema
Updated database
Exception: Database error when running migration latest for app duplicatefinder

The update was unsuccessful. Please report this issue to the Nextcloud community.

### Actual behaviour
nextcloud is no longer operational.

### Server configuration

**Operating system:**
Linux Mint 20.2

**Web server:**
Apache 2.4.41

**Database:**

mysql 8.0.25

**PHP version:**

php 7.4

**Nextcloud version:** (see Nextcloud admin page)

(can't access the admin page right now or any other page as the site is down but I believe the version is 20.0.3)

**Updated from an older Nextcloud/ownCloud or fresh install:**

Updated the app from existing version.

**Where did you install Nextcloud from:**

Downloaded it from the nextcloud site.

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

Sadly All I get when I go to this URL is:

App update required
The following apps will be updated:
Duplicate Finder (duplicatefinder)
Please make sure that the database, the config folder and the data folder have been backed up before proceeding.


</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.naughton.ca"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.3.1",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_phone_region": "CA",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

No

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No


</details>

### Client configuration
Chrome

**Operating system:**
Linux Mint 20.2
### Logs

<!--- Reports without logs might be closed as unqualified reports! -->

#### Web server error log
<details>
<summary>Web server error log</summary>
None
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

Quite large..

</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by szaimen** [comment]
Hi there, please report this to https://github.com/PaulLereverend/NextcloudDuplicateFinder. Thanks!
