### ISSUE TITLE
Update to 21.0.3

### ISSUE THREAD

**Issue by joaoper65** [nextcloud/server#27953]
i juat updated one of the apps  than i got a update and when i hit update it come up with this error.

Exception: Database error when running migration latest for app duplicatefinder
Detailed logs

Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Updated database

Exception: Database error when running migration latest for app duplicatefinder

The update was unsuccessful. Please report this issue to the Nextcloud community.

**Comment by szaimen** [comment]
Hi there, please report this to https://github.com/PaulLereverend/NextcloudDuplicateFinder. Thanks!
