### ISSUE TITLE
Notification Link does not work

### ISSUE THREAD

**Issue by mixim-mixim** [nextcloud/server#27986]
![image](https://user-images.githubusercontent.com/24353892/125745745-227350d4-3450-4415-a425-b8387b338d28.png)
Hi,
before update to v22.0 the notification of new plugin version leads to the plugin update section by clicking the notification.
This does not work any more since update to v22.0 (updated via the beta channel and set back to stable channel)
Cheers MiXiM

**Comment by szaimen** [comment]
This was fixed in the meantime and will work again after the next minor release is installed.
See https://github.com/nextcloud/notifications/pull/883
