### ISSUE TITLE
Calendar doesn't respect timezone for all-day event reminders

### ISSUE THREAD

**Issue by dgsiegel** [nextcloud/server#27987]
Suppose I add an all-day event in the future and add an email reminder to e.g. 1 day before at 9am (which is the default). Being in CEST, I'd expect the reminder at 9am the day before, but it is actually sent 2 hours later (the difference from UTC to CEST).

```
BEGIN:VCALENDAR
PRODID:-//IDN nextcloud.com//Calendar app 2.0.4//EN
CALSCALE:GREGORIAN
VERSION:2.0
BEGIN:VEVENT
CREATED:20201015T180355Z
DTSTAMP:20201015T190502Z
LAST-MODIFIED:20201015T190502Z
SEQUENCE:6
UID:c8097e7a-0eeb-4b69-abc7-e5f27754e2df
DTSTART;VALUE=DATE:20201018
DTEND;VALUE=DATE:20201019
SUMMARY:All Day Test
BEGIN:VALARM
ACTION:EMAIL
TRIGGER;RELATED=START:-PT15H
END:VALARM
END:VEVENT
END:VCALENDAR
```

My guess would be that adding the current timezone to `DTSTART;VALUE=DATE:20201018` would fix this issue.

**Comment by tcitworld** [comment]
There's probably already an issue for that.

**Comment by Pilzinsel64** [comment]
Can confirm, the same. The notification arrives about two hours later then the event. E.g. if I set up to remind on 5pm I get it on 7pm. The calendar app on my mobile phone with DavX5 synced calendars send me a native notification at 5pm. Only the notification via Nextcloud needs at leat 2h longer.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by Pilzinsel64** [comment]
I've tested again with v25.3 yesterday. The reminder was planned for 14:00 and my phone's calender app pushed the reminder at 14:00 but Nextcloud pushed the reminder at 15:00. My timezone on all devices is MEZ.

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/server/pull/36192

**Comment by Luncheon3462** [comment]
I’m just an end user, not a dev but running NC 26.0.3. The time zone drift for all day event reminders still occurs for me. Doesn’t matter if I use the personal calendar that is automatically created or a new calendar that I create. My time zone is set correctly in the nc calendar app settings app. Is this expected still?

**Comment by Fernando-Checa** [comment]
Same here.. I'm on v28 and allday events are still off by one hour.
Regular events are ok.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/issues/43113
