### ISSUE TITLE
custom data folder: issue with update to 22

### ISSUE THREAD

**Issue by SebastianBerlin** [nextcloud/server#27996]
I have installed version 21.0.3 and would like to update to 22.0.0.

At the beginning of the update process it checks for "expected files" and there is the annoying message: „The following extra files have been found:“

It lists the custom data-folder which is specified in the config.php ('datadirectory').

So what to do? Change it manually to "data" and hope it won't crash everything? Or will there be a bugfix for that?

**Comment by kesselb** [comment]
https://github.com/nextcloud/updater/issues/297

> So what to do?

Do a manual update.

**Comment by SebastianBerlin** [comment]
> 
> 
> [nextcloud/updater#297](https://github.com/nextcloud/updater/issues/297)
> 
> > So what to do?
> 
> Do a manual update.

Sorry, I don't understand it right, probably. The workaround is _Create soft link from datadirectory path to /data_ – but there are still more entries (> MySQL) for that folder, or not? So is this 'enough': Moving the custom folder to /data and switch it back to config.php?

You also mentioned a [manual update](https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html)? I don't have full control of the server and my sudo-rights are a bit restricted. So on this instance I cannot stop the server ([step 3](https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html)).

**Comment by SebastianBerlin** [comment]
Any updates to update NextCloud? @kesselb wasn't really helpful...

**Comment by kesselb** [comment]
As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com.

> You also mentioned a manual update? I don't have full control of the server and my sudo-rights are a bit restricted. So on this instance I cannot stop the server (step 3).

The idea of "Stop your Web server." is that no one uses Nextcloud during the upgrade. If you cannot stop the web server you may prevent access via .htaccess (or similar mechanism) or don't stop the web server at all.

**Comment by SebastianBerlin** [comment]
Okay, it wasn't difficult at all, at least you don't stand on the custom data directory and you're fine with the default (/data):

1. **rename** the custom directory to _data_ (via FTP or whatever)
2. in **config.php** switch back the **datadirectory** from custom folder to `.../data`
3. rescan the folder and files with **occ files:scan --all**

That's all. After those steps you can start the update-process here: /settings/admin/overview

**Comment by tuxick** [comment]
It also throws this when i runs into unexpected files or directories. So it should say "found unexpected files" or something.
