### ISSUE TITLE
Unable to 'Add Group' since upgrade to NC 22.x

### ISSUE THREAD

**Issue by lightweight** [nextcloud/server#28002]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Log into an NC 22.x instance (deployed using the NC Docker containers via Docker Compose) as an administrator
2. got to /settings/users#
3. click on the 'Add Group' link

### Expected behaviour
Clicking on the link should reveal an in-place text input form to type in a new group name. 

### Actual behaviour
No response, and no JS errors, either.

### Server configuration

**Operating system:**
Ubuntu Linux host + Docker + Docker Compose using the official NC reference containers.

**Web server:**
Nginx server container, Nginx reverse proxy

**Database:**
MariaDB 10.3.30

**PHP version:**
PHP 7.4.21

**Nextcloud version:** (see Nextcloud admin page)
22.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 21.0.2

**Where did you install Nextcloud from:**
Using official NC Docker conatiners

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
`Enabled:
  - accessibility: 1.7.0
  - activity: 2.15.0
  - admin_audit: 1.11.0
  - audioplayer: 3.1.0
  - audioplayer_editor: 0.3.0
  - bbb: 1.4.2
  - calendar: 2.3.0
  - circles: 22.0.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 4.0.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.18.0
  - deck: 1.5.0
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_markdown: 2.3.4
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.13.2
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - forms: 2.2.4
  - gpxedit: 0.0.14
  - gpxpod: 4.2.8
  - impersonate: 1.9.0
  - integration_mastodon: 1.0.1
  - logreader: 2.7.0
  - lookup_server_connector: 1.9.0
  - mail: 1.10.1
  - maps: 0.1.9
  - music: 1.2.1
  - nextcloud_announcements: 1.11.0
  - notes: 4.1.0
  - notifications: 2.10.1
  - oauth2: 1.9.0
  - onlyoffice: 7.0.4
  - password_policy: 1.12.0
  - phonetrack: 0.6.7
  - photos: 1.4.0
  - polls: 3.0.0
  - privacy: 1.6.0
  - provisioning_api: 1.11.0
  - qownnotesapi: 21.7.0
  - recommendations: 1.1.0
  - richdocuments: 4.2.0
  - serverinfo: 1.12.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - spreed: 12.0.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - suspicious_login: 4.0.0
  - systemtags: 1.11.0
  - text: 3.3.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.1
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - video_converter: 1.0.2
  - viewer: 1.6.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - announcementcenter
  - apporder
  - bruteforcesettings
  - encryption
  - files_external
  - files_readmemd
  - twofactor_email
  - user_ldap
``
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "hub.davelane.nz"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.0.0.11",
        "overwrite.cli.url": "https:\/\/hub.davelane.nz",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mysql.utf8mb4": true,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "loglevel": 2,
        "default_phone_region": "NZ",
        "theme": "",
        "app_install_overwrite": [
            "video_converter",
            "files_readmemd",
            "qownnotesapi",
            "polls",
            "audioplayer",
            "bbb",
            "audioplayer_editor",
            "forms",
            "twofactor_email"
        ]
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Brave and Firefox

**Operating system:**
Linux Mint 20.2

### Logs

<!--- Reports without logs might be closed as unqualified reports! -->

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here

There are no log entries associated with this bug. 
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

Looking at the Javascript console, clicking on 'Add group' does not result in any console entries except another repetition of 

'jQuery is deprecated: The global jQuery is deprecated. It will be removed in a later versions without another warning. Please ship your own.' for global.js

There is a JS error 'Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).' on page load, but this was also present with the NC 21.0.2 instance where the 'Add group' still worked. 
```
</details>

**Comment by szaimen** [comment]
Hi, this will be fixed with NC22.0.1
See https://github.com/nextcloud/server/pull/27878

**Comment by lightweight** [comment]
Brilliant, thanks!
