### ISSUE TITLE
Receiving update to "ownCloud 9.x"

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/server#2801]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Only updates for Nextcloud should be shown, not for ownCloud.

### Actual behaviour
An update for ownCloud is provided to my Nextcloud instance

### Server configuration
**Operating system**: Debian

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.6

**Nextcloud version:** 10.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Err... downloaded the zip file, pushed it to server via ftp and run the installer

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

Admin-Page:

![unbenannt](https://cloud.githubusercontent.com/assets/4741199/21391450/0fce7f3e-c78c-11e6-9fb6-e23cd7b471a4.png)

Notfications:

![er](https://cloud.githubusercontent.com/assets/4741199/21391464/1fbd2d8c-c78c-11e6-8f48-a875db5c55b7.png)

**Comment by LukasReschke** [comment]
There's a bug in 10.0.0, see: https://nextcloud.com/blog/get-up-to-date-with-the-new-nextcloud-updater/
