### ISSUE TITLE
Crash by update duplicatefinder

### ISSUE THREAD

**Issue by mccius03** [nextcloud/server#28012]
the update of the duplicatefinder in nextcloud 21.0.3 crahed. There're the following informatin:

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturschritt: Repair MySQL collation
Reparaturinformation: All tables already have the correct collation -> nothing to do
Reparaturschritt: Repair SQLite autoincrement
Reparaturschritt: Copy data from accounts table when migrating from ownCloud
Reparaturschritt: Drop account terms table when migrating from ownCloud
Das Datenbankschema wird aktualisiert
Datenbank aktualisiert
Exception: Database error when running migration latest for app duplicatefinder

Now I cannot start nextcloud. Everytime it will configure this change an crash

**Comment by szaimen** [comment]
Hi there, please report this to https://github.com/PaulLereverend/NextcloudDuplicateFinder
Thanks!
