### ISSUE TITLE
Update Failure

### ISSUE THREAD

**Issue by adamjay78** [nextcloud/server#28027]
Stuck in update

Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Updated database

Exception: Database error when running migration latest for app duplicatefinder

**Comment by acsfer** [comment]
Duplicate of https://github.com/nextcloud/server/issues/28012
