### ISSUE TITLE
Cron exits 0 on failure

### ISSUE THREAD

**Issue by smichel17** [nextcloud/server#28038]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Break your nextcloud config (e.g. remove all keys except the instance id)
2. Run `php -f cron.php`

### Expected behavior
Cron fails with a nonzero exit status

### Actual behaviour
Cron fails with exit status 0

### Suggested fix

```diff
diff --git a/cron.php b/cron.php
index 815786ada5..43aadb4c34 100644
--- a/cron.php
+++ b/cron.php
@@ -158,6 +158,8 @@ try {
        exit();
 } catch (Exception $ex) {
        \OC::$server->getLogger()->logException($ex, ['app' => 'cron']);
+       exit(1);
 } catch (Error $ex) {
        \OC::$server->getLogger()->logException($ex, ['app' => 'cron']);
+       exit(1);
 }
```

### Context

<details>
<summary>I'm running nextcloud in a probably-unsupported setup and occasionally my config.php file becomes corrupted.</summary>

I host my instance at [hcoop](https://hcoop.net). Among other idiosyncrasies, we use [AFS](https://openafs.org/), which uses a different file permission model, which I suspect is the cause of the bug: Every so often (maybe once every week or two) nextcloud will overwrite the config file with an essentially-empty one, like this:

```php
<?php
$CONFIG = array (
  'instanceid' => 'ID_WAS_HERE',
);
```

I don't know why this happens and nothing else seems to break.
</details>

I don't expect support for my setup. If you want, I can file a proper bug report and the config information I've left out here, but it's not that important to me. The downtime is no big deal, since it's just a personal server, and it has an easy fix: I just keep a regular backup of my config file. When I get email(s) about a failed cron job, I ssh to my server and run the one-liner to restore the config.

However, it would be much nicer if I could automate the restore process. Currently in order to do this I'd need to parse the stderr and grep on some arbitrary string — not a particularly stable approach. So I patched my local `.php` file with the change above, and it seems to work fine. I'm hoping you could do something similar here, so I don't have to re-apply the patch each upgrade.

**Comment by szaimen** [comment]
Hello, do you mind creating a PR with your patch for discussion?
Thank you!

**Comment by smichel17** [comment]
Done. I was actually going to do it originally, but then I wasn't sure about tests and whatnot, so I figured I'd start here instead.
