### ISSUE TITLE
View share permissions in files list

### ISSUE THREAD

**Issue by Mer0me** [nextcloud/server#28049]
**Is your feature request related to a problem? Please describe.**
It's difficult to see if a file was shared with read-only or write permission.

**Describe the solution you'd like**
The UI should show a little "forbidden" or "locked" badge on the file icon when it is read-only

**Describe alternatives you've considered**
If you click on the details button, you can see if you can rename the file (if it is writable) or not (if it is read-only)

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
