### ISSUE TITLE
Investigate using Rector for porting away from internal deprecated methods

### ISSUE THREAD

**Issue by CarlSchwan** [nextcloud/server#28059]
Rector is a nice tool that allows to easily refactor a codebase using rules: https://github.com/rectorphp/rector. This is often used in the Symfony and Laravel communities. Currently, we have a lot of deprecated API usage in the core apps, we should investigate if it would be a good idea to create rector rules for Nextcloud, this would allow us to port away from deprecated methods faster but also this could be helpful for third parties apps by reducing the maintenance cost for third parties developers and bringing updated to the users faster.

**Comment by zak39** [comment]
I would add that this may make it easier to migrate code to PHP8.0, PHP8.1 and PHP8.2 using these rules :  

- PHP8.1 : https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#php81
- PHP8.2 : https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#php82

**Comment by ChristophWurst** [comment]
https://packagist.org/packages/nextcloud/rector :saluting_face:
