### ISSUE TITLE
Error while updating to 20.0.11

### ISSUE THREAD

**Issue by benceww** [nextcloud/server#28060]
Hi, an error has occured while the updater tried to update the "duplicate finder" app.

Message:
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE INDEX duplicatefinder_path_idx ON oc_duplicatefinder_finfo (path)': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes

I found a solution that says this error impacts MYSQL and MariaDB so the commands that you will need to run to correct the error are:
SET GLOBAL innodb_file_format=Barracuda;
SET GLOBAL innodb_file_per_table=on;
SET GLOBAL innodb_large_prefix=on;

The problem about this that the first and the last variables are read only "ERROR 1238 (HY000)"

Any way to fix it? Even removing the app?

**Comment by szaimen** [comment]
Hi there, please report this to https://github.com/PaulLereverend/NextcloudDuplicateFinder. Thanks!
