### ISSUE TITLE
Do not reload Files view when copying a file to another folder

### ISSUE THREAD

**Issue by Booteille** [nextcloud/server#28069]
**Is your feature request related to a problem? Please describe.**
Actually, when copying a file from one folder to another one, the view of the actual folder is reloaded.

This behaviour has two flaws:

* This makes us wait some seconds that the view reload before being able to work on this folder again.
* This clear the « last path » feature: when moving a file to another folder, the view is not reloaded and so, we can move another file to the same folder quickly because the path has been kept in memory.

**Describe the solution you'd like**
It would be neat if the view was reloaded only if we are modifying the current folder. In other situations (as moving a file from Folder A to Folder B or copying a file from Folder A to Folder B), the view should not be reloaded.

**Describe alternatives you've considered**

**Additional context**

Thanks for your work.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
