### ISSUE TITLE
Files to vue

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#28063]
https://github.com/nextcloud/server/projects/6

### Goals
- Accessibility
- Performance
- Testing

### Steps
- [x] Assess existing features
- [x] Split app into multiple independent modules
- [x] Implement APIs
- [ ] Implement each module
- [ ] Migrate acceptance testing from selenium to cypress
- [ ] Deprecate outdated APIs
- [ ] Document modules and new APIs
- [ ] Final QA

#### Optional steps
- Automated lighthouse accessibility testing
- Backend parity (pagination...)

**Comment by skjnldsv** [comment]
## APIs
- [ ] Require proper FileAction API #21835 
- [ ] Require proper FileInfo API (standard between php/js to access a file data, should be a parity with webdav as well? Photos, Files Sidebar and Viewer are already using a facsimile)

- [ ] List existing features
  - Displaying listing files views
  	- files
  	- files_sharing
  	- files_trashbin
  	- files_version
  	- systemtags
  - Uploading
  	- Files and folders
  	- Drag and drop files/folder
  - Creating
    - Files and Folders
    - Custom files
    - Template 
  - Seeing quota
  - ...?

 ______
- [ ] To coordinate with the design team
  - List existing features/issues to be discarded
  - List various UI sections
  - Simplify and change current UI
  - ... `please complete this list`
  
- [ ] List existing libraries to use
  - File upload api
  - ... `please complete this list`
 
- [ ] List existing APIs or integrations from other apps
  - File actions
  - File actions for multiselect (files_zip)
  - Inline file actions (e.g. comment indicator, file sharing indicator)
  - Header section (text app readme integration, recommended files app)
  - Folder icon registration (groupfolders/files_external)
  - Extending propfind with custom data (groupfolders, files_lock)
  - ... `please complete this list`

**Comment by skjnldsv** [comment]
```js
- Name and actions are hardcoded first
- Views can decide what columns to add/ remove after the actions
- We load all the files and virtual-scroll

{
	id: 'files',
	name: 'All files',
	[emptyView: VueComponent (EmptyContent ?)],
	[parent: 'id'],
	icon: VueComponent|string,
	order: 1,
	[sticky: false],
	template: {
		columns: [
			{
				name: 'Name',
				id: 'name',
				property: 'basename',
				[sortFunction: (FileInfoA, FileInfoB) => integer],
				[summary: (FileInfo[]) => string],
				[tooltip: (FileInfo) => string],
				
		]
	}
	
}

```

**Comment by CarlSchwan** [comment]
Potential new feature to add:

* https://github.com/nextcloud/server/issues/22278 (requested quite often by both customers and the community)

**Comment by skjnldsv** [comment]
> Potential new feature to add:
> 
> * [Display Upload Date for Files in Web Interface (and make it sortable) #22278](https://github.com/nextcloud/server/issues/22278) (requested quite often by both customers and the community)

Maybe have a way to enable/disable specific columns per views ?

**Comment by szaimen** [comment]
🎉🎉🎉🎉🎉
