### ISSUE TITLE
No matches for search in external storage when external storage is not available for user but shared for user

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/server#28108]
A user that:
1. is not in the "Available For" of the external storage
2. receives a full share of the external storage

can explore and open files but not search them.

### Steps to reproduce

1. Install Nextcloud 21.0.3
2. Create a local folder with owner `www-data`
```
sudo mkdir /ext-storage
sudo chown www-data.www-data
```
3. In Nextcloud, enable External Storage app.
4. Create External Storage:

```
Folder Name: ext-storage
External Storage: local
Authentication: none
Configuration: /ext-storage
Available for: admin(group)
Options: Enable Preview, Enable Share
```
5. With admin, create user user1
6. With admin, share the folder ext-storage with user1
7. With admin, move all the default files (Nextcloud intro.mp3, ...) into ext-storage
8. With user1, search for "intro" => matches "Nextcloud intro.mp3"
9. Logout admin
10. With user1, remove all the default files, leave only ext-storage
11. With user1, search for "intro" => No results

### Expected behaviour
At step 11, user1 should find a match as in step 8

### Actual behaviour
At step 11, user1 doesn't find a match

### Server configuration
See the system report
[attached](https://github.com/nextcloud/server/files/6861587/system-report-2021-07-22.md)

**Comment by xadhoom76** [comment]
We have tested the problem seems to be after 20.08. We tested external storage webdav,local,smb.

**Comment by PVince81** [comment]
okay, got it reproduced.

at first I was sharing "/ext-storage/subdir" instead of "/ext-storage" directly.
sharing the mount point is a bit special internally which could explain why it's not working.

if it was working before I should be able to bisect to find out what change introduced the problem

**Comment by PVince81** [comment]
here we go 5d08beb3d2e2c25ac765fa54a670bd400a3fac69

introduced through https://github.com/nextcloud/server/pull/26134 which is intended to optimize the speed of the search

@icewind1991 mind having a look ?

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/server/pull/28175
