### ISSUE TITLE
Automatic Login-Flow with OAuth2

### ISSUE THREAD

**Issue by htrampe** [nextcloud/server#28134]
Hi!
It would be great if the OAuth2-App could get the option, that the user does not need to except the authentication against the client. Now, the user has always click two times until he is logged in. It would be better, if after the oauth-client is saved in the admin-settings and the user goes to a external-page to the client, the login flow automaticly logg the user so he is authenticated against the client.
If it is possible, any hints would be great. thx!

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
