### ISSUE TITLE
18.0.3 tag has been forgotten, can you add it?

### ISSUE THREAD

**Issue by Neustradamus** [nextcloud/server#28136]
Dear team,

Can you add the missing 18.0.3 tag?
- https://github.com/nextcloud/server/releases/tag/v18.0.3

18.0.2 and 18.0.4 are here:
- https://github.com/nextcloud/server/releases/tag/v18.0.4
- https://github.com/nextcloud/server/releases/tag/v18.0.2

Of course, it is not only in this repository.

Thanks in advance.

**Comment by szaimen** [comment]
Since NC18 is EOL since a few months now, we will not invest any time into this, sry.
