### ISSUE TITLE
Refresh folder from web interface

### ISSUE THREAD

**Issue by adosix** [nextcloud/server#28137]
I would like to be able to start scanning certain folder for new files, i know that it s possible to do that scan with occ and use bot to call that command every n minutes. But I think that it would be nice to have option when i click on three dots of folder to have "Scan for new files" or "Update folder" and that would start scanning just the one folder i chose. 

My use-case if somebody wonder:
(I check folder where my security camera using ftp drops photos, usually 2-10 photos a day and I check it every week or so. So Bot would be wasting CPU time. Have a nice day and thank you for reading)

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
