### ISSUE TITLE
File checksum for ReadOnly Files (File corruption, Hacking detection, .... )

### ISSUE THREAD

**Issue by dgedgedge** [nextcloud/server#28158]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? No.**
As we know there is a probability of data corruption of files on disk, even in case of RAID solution.
Hacking could be also a reason for those changes.
Errors of manipulation from user having write permission too.

Yet if those happen, the corruption will be only detected at the next access for usage which may be a long time after the corruption, and too long for a backup to have the not corrupted file. 

**Describe the solution you'd like**
The Idea would be to have the server calculate recursively checksums on file directories on designated directory (once / on demand).
Then there would be a background check each xxx days that the files included in the directory have not changed by checking the checksum.
If a change is detected, then a mail/message would be sent to an appropriate person for action.
Check period could be expressed in number of files per days and/or periodicity with an evaluation of the number of file check per day.

I ask the feature to the nextcloud level, because it is a user level.
It could be used and done even with external stores even if this implies network bandwidth....

E.g.: 
- Send a mail to the admin in order to triger the restoration of the file from a backup.

The trigger for the change would not be a write access from a nextcloud client, because in case of underlying corruption nextcloud does not know the file has changed.

**Additional context**
I have allready produce from scripts on Debian, for those checks on the server directly.
It's a machine admin feature, with knowledge of the file organisation of nextcloud.
This works in some usecases, but is not usable by standart users so easily.

**Calculating checksum :** 

```
cat mkchecksum.sh 
#/bin/bash
set -x

CHECKSUMDIR=checksums
CHECKSUMOLD=checksumsold
if [ "$1" = "" ]
then
	echo "Sepcify a file"
	exit
else
	FILE=`basename $1`
fi
if [ "$2" = "" ]
then
        echo "Checksumdir=default = $CHECKSUMDIR"
	mkdir -p $CHECKSUMDIR
else
        CHECKSUMDIR="$2"
	if [ ! -d $CHECKSUMDIR  ]
	then
		echo "$CHECKSUMDIR does not exists"
		exit
	fi
fi

if [ -d $FILE  ]
then
	if [ -f $CHECKSUMDIR/$FILE ]
	then
		mv -f $CHECKSUMDIR/$FILE $CHECKSUMDIR/../$CHECKSUMOLD/$FILE.bkup
	fi

	rm -f $CHECKSUMDIR/checksumchecksum
	find $FILE  -type f -not -path '*/.AppleDouble*' -a -not -path "*/.DS_Store" -a -not -path '*/._*' -a -not -path '*~' -a -not -path '*/Thumbs.db' -a -not -path '*/.~lock.*' -exec md5sum \{\} \; | sort -k 2  >  $CHECKSUMDIR/$FILE
	md5sum $CHECKSUMDIR/* | sort -k 2 | grep -v checksumchecksum > $CHECKSUMDIR/checksumchecksum

	if [ -f $CHECKSUMDIR/../$CHECKSUMOLD/$FILE.bkup ]
	then
		diff $CHECKSUMDIR/$FILE $CHECKSUMDIR/../$CHECKSUMOLD/$FILE.bkup
		# awk '{ ligne="" ; for(i=2; i<=NF; i++) {ligne=ligne " " $i;} print ligne}' checksums/2020 | sort > /tmp/toto1
	fi
fi
```
**checking checksums in a cron:**

```
cat checkall.sh 
#/bin/bash

cd $(dirname $(realpath $0))/..
nice -20 md5sum  --quiet -c checksums/*
```

**Note:** This feature could also be used if checksums are saved in the backup and usable because format are usable ouside nextcloud context.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
