### ISSUE TITLE
Received share prodived by other users apears on a dedicated folder 

### ISSUE THREAD

**Issue by dgedgedge** [nextcloud/server#28154]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**The issue:**
When a user share a folder to me the folder appears on top of my nextcloud tree.
This is disturbing event if I know that I may move the folder/file later.

**The solution I'd like:**
I would like that when an other user shares a file/folder to me nextcloud will put that file/folder in a sharedToMe folder by default instead of the top nextcloud tree.

**Notes:**
The name of the folder where shared elements would be put could be configurable.
By default the configuration could be the top tree (for ascending compatibility).

**Comment by szaimen** [comment]
See 
![image](https://user-images.githubusercontent.com/42591237/128638418-afcde227-0a32-4e25-9717-96758d693936.png)
