### ISSUE TITLE
Files edited via SMB/NFS with filesystem_check_changes=1 show as "pending" size

### ISSUE THREAD

**Issue by DragonQ** [nextcloud/server#28153]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install Nextcloud
2. Set "filesystem_check_changes=1" in config.php
3. Edit a file in the Nextcloud data directory via SMB/NFS

### Expected behaviour
Browsing the file via Nextcloud's web interface or the Android app would show the file's new size, either immediately or after some set period when a background job has recalculated the file's size.

### Actual behaviour
The edited file, _and every single directory above it_, shows a size of "pending" until the directory that contains the edited file is browsed to. At that point its size, and that size of all directories above it, are recalculated.

### Server configuration

**Operating system:**
Ubuntu 20.04 LTS
**Web server:**
Apache 2.4.48-1
**Database:**
MySQL 8.0.25
**PHP version:**
PHP 7.4.3-4ubuntu2.5
**Nextcloud version:** (see Nextcloud admin page)
21.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from many versions, back to 16 or something
**Where did you install Nextcloud from:**
Updated via `sudo -u www-data php updater.phar --no-interaction`
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - apporder: 0.13.0
  - calendar: 2.3.1
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 4.0.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_markdown: 2.3.4
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_snapshots: 1.0.2
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - groupfolders: 9.0.2
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - maps: 0.1.9
  - nextcloud_announcements: 1.10.0
  - notes: 4.1.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - onlyoffice: 7.0.2
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - spreed: 11.3.1
  - systemtags: 1.11.0
  - talk_matterbridge: 1.22.4
  - tasks: 0.14.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_nextcloud_notification: 3.2.1
  - twofactor_totp: 6.1.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - federation
  - files_external
  - mail
  - support
  - survey_client
  - twofactor_email
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.89"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.3.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_phone_region": "GB",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "cache_path": "\/var\/cache\/nextcloud",
        "maintenance": false,
        "theme": "",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 1,
        "mail_sendmailmode": "smtp",
        "updater.release.channel": "stable",
        "filesystem_check_changes": 1,
        "onlyoffice": {
            "verify_peer_off": true
        },
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [
            "Test"
        ],
        "app_install_overwrite": [
            "files_snapshots"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:**
No
**Are you using encryption:**
No
**Are you using an external user-backend, if yes which one:**
No

### Client configuration
**Browser:**
Firefox 90.0.2
**Operating system:**
Windows 10 21H1
#### Web server error log
Nothing shown when directory containing pending file is viewed.

#### Nextcloud log (data/nextcloud.log)
Nothing shown when directory containing pending file is viewed.

#### Browser log
N/A

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
