### ISSUE TITLE
When sharing folder for new owner, a warning should pop if not enough space on receiver's side

### ISSUE THREAD

**Issue by ImaCrea** [nextcloud/server#28169]
**Is your feature request related to a problem? Please describe.**
Hey there, I tried to change ownership of a folder and it wasn't working. Even though notification was sent to receiver and accepted.

I realized then that the folder was too big regarding the remaining space in receiver's account. I asked her to make some space. Then we did again the transfer and finally it worked.

It wasn't easy to understand the error was coming from there. Average user would have been stuck.

**Describe the solution you'd like**

- Receiver should have a warning message in the notification which ask her to be the new owner "Be careful, there's not enough space on your account to accept. Make some space first then come back here to accept the transfer".

- The "accept" button should be disabled while there's not enough space in receiver's account.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
