### ISSUE TITLE
Cannot modify header information (OC_JSON.php#113)

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/server#28183]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. No reproduction, just log entries
2. cron is called via webcron

### Expected behaviour
No error should occur

### Actual behaviour
Error logs every hours
Seems, that the session gets killed while the browser is closed (but no evidence for that, just an observation)

### Server configuration

**Operating system:** Ubuntu 20.04.2 LTS

**Web server:** Apache

**Database:** MariaDB 10.5.10

**PHP version:** 8.0.6

**Nextcloud version:** 22.0.0
**Updated from an older Nextcloud:**
Update from Beta5 

**Where did you install Nextcloud from:**
Internal Update routine

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.7.0
  - activity: 2.15.0
  - calendar: 2.2.2
  - circles: 22.0.0-beta.1
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 4.0.0-beta.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.18.0
  - deck: 1.4.2
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_external: 1.12.1
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.13.2
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.11.0
  - integration_github: 1.0.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.9.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - polls: 3.0.0
  - privacy: 1.6.0
  - provisioning_api: 1.11.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - support: 1.5.0
  - suspicious_login: 4.0.0
  - systemtags: 1.11.0
  - text: 3.3.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.1
  - updatenotification: 1.11.0
  - viewer: 1.6.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0

Disabled:
  - admin_audit
  - appointments
  - apporder
  - bruteforcesettings
  - encryption
  - firstrunwizard
  - forms
  - guests
  - impersonate
  - integration_zammad
  - mail
  - spreed
  - survey_client
  - talk_matterbridge
  - tasks
  - unsplash
  - user_ldap
  - user_status

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```json
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "tempdirectory": "\/tmp",
        "dbtype": "mysql",
        "version": "22.0.0.11",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_phone_region": "DE",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "beta",
        "htaccess.RewriteBase": "\/",
        "htaccess.IgnoreFrontController": true,
        "app_install_overwrite": [
            "deck",
            "spreed",
            "impersonate",
            "dashboard",
            "circles",
            "talk_simple_poll",
            "polls",
            "calendar",
            "contacts",
            "unsplash"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "ldapIgnoreNamingRules": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** none
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

#### Web server error log
No access

#### Nextcloud log (data/nextcloud.log)

<details>
<summary>Nextcloud log</summary>

```json
{
    "reqId": "YP8-nnPsQKuCdE7Q@zmYWgAACiE",
    "level": 3,
    "time": "2021-07-26T23:05:02+00:00",
    "remoteAddr": "***.***.***.***",
    "user": "--",
    "app": "PHP",
    "method": "GET",
    "url": "/cron.php",
    "message": "Cannot modify header information - headers already sent by (output started at htdocs/nextcloud/apps/circles/lib/Service/MaintenanceService.php:143) at htdocs/nextcloud/lib/private/legacy/OC_JSON.php#113",
    "userAgent": "cronBROWSE v0.93",
    "version": "22.0.0.11",
    "exception": {
        "Exception": "Error",
        "Message": "Cannot modify header information - headers already sent by (output started at htdocs/nextcloud/apps/circles/lib/Service/MaintenanceService.php:143) at htdocs/nextcloud/lib/private/legacy/OC_JSON.php#113",
        "Code": 0,
        "Trace": [{
            "function": "onError",
            "class": "OC\\Log\\ErrorHandler",
            "type": "::",
            "args": [2, "Cannot modify header information - headers already sent by (output started at htdocs/nextcloud/apps/circles/lib/Service/MaintenanceService.php:143)", "htdocs/nextcloud/lib/private/legacy/OC_JSON.php", 113]
        }, {
            "file": "htdocs/nextcloud/lib/private/legacy/OC_JSON.php",
            "line": 113,
            "function": "header",
            "args": ["Content-Type: application/json; charset=utf-8"]
        }, {
            "file": "htdocs/nextcloud/cron.php",
            "line": 152,
            "function": "success",
            "class": "OC_JSON",
            "type": "::",
            "args": []
        }],
        "File": "htdocs/nextcloud/lib/private/Log/ErrorHandler.php",
        "Line": 92,
        "CustomMessage": "--"
    },
    "id": "60ff952c2ef5c"
}

```

</details>

**Comment by kesselb** [comment]
Hi,

sounds like https://github.com/nextcloud/circles/issues/686.

**Comment by dartcafe** [comment]
Confirming because of missing symptom after commenting out the echo line.
