### ISSUE TITLE
Migration to nextcloud takes too long (2 days and it's not finished)

### ISSUE THREAD

**Issue by naguirre** [nextcloud/server#2818]
### Steps to reproduce
1. Install new version of of next cloud in /var/www/owncloud
2. launch upgrade process : sudo -u owncloud php ./occ upgrade
3. Process never ends (running for two days and still not finished)

### Expected behaviour
The upgrade process should end, and new version should be available.
It was already the case with owncloud but the database migration (?) takes a very very long time.
I'm wondering what is done during this step to take so much time. 
For owncloud migration from 8 to 9 it took 18hours ... For 9 to nexcloud i launch the process 24hours ago, ans it's still not finished. There is 6 active users with a total of 50 000 files in this installation. It's too much ? What's the maximum numbers of file that nextcloud can serve ?

### Actual behaviour
Set log level to debug
Checking whether the database schema can be updated (this can take a long time depending on the database size)
[2 days later, nothing more]

### Server configuration
**Operating system**:
lsb_release -a

No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.6 (jessie)
Release:        8.6
Codename:       jessie

**Web server:**
nginx

**Database:**
mysql  Ver 14.14 Distrib 5.5.53, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
 php --version
PHP 5.6.27-0+deb8u1 (cli) (built: Oct 15 2016 15:53:28)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
<?php
$OC_Version = array(11,0,0,10);
$OC_VersionString = '11.0.0';
$OC_Edition = '';
$OC_Channel = 'stable';
$OC_VersionCanBeUpgradedFrom = array(9,1);
$OC_Build = '2016-12-13T13:24:49+00:00 ed7b18799f7d57ab9346e224b4dcea0961c9537f';
$vendor = 'nextcloud';
**Updated from an older Nextcloud/ownCloud or fresh install:**
Trying to update from a ownCloud 9

**Where did you install Nextcloud from:**
Still trying
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.2.1
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - lookup_server_connector: true
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - twofactor_backupcodes: true
  - updatenotification: 0.1.0
  - user_ldap: 0.8.0
  - workflowengine: true
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - gallery
  - logreader
  - nextcloud_announcements
  - password_policy
  - serverinfo
  - sharebymail
  - survey_client
  - theming
  - user_external
  - user_saml

</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "enna.me"
        ],
        "datadirectory": "\/home\/yunohost.app\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/",
        "dbtype": "mysql",
        "version": "9.0.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "oc7i4u1770v5",
        "ldapIgnoreNamingRules": false,
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "theme": "",
        "maintenance": true,
        "log_type": "syslog",
        "loglevel": 0,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mail_smtpmode": "php",
        "mail_smtphost": "enna.me",
        "mail_from_address": "nico",
        "mail_domain": "enna.me",
        "trashbin_retention_obligation": "auto",
        "logout_url": "https:\/\/enna.me\/yunohost\/sso\/?action=logout",
        "updatechecker": false,
        "integrity.check.disabled": true,
        "htaccess.RewriteBase": "\/"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

LDAP
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
+-----------+-----------------------------------+--------------------------------------------+
| appid     | configkey                         | configvalue                                |
+-----------+-----------------------------------+--------------------------------------------+
| user_ldap | cleanUpJobOffset                  | 0                                          |
| user_ldap | enabled                           | yes                                        |
| user_ldap | has_memberof_filter_support       | 0                                          |
| user_ldap | home_folder_naming_rule           |                                            |
| user_ldap | installed_version                 | 0.8.0                                      |
| user_ldap | last_jpegPhoto_lookup             | 0                                          |
| user_ldap | ldap_agent_password               |                                            |
| user_ldap | ldap_attributes_for_group_search  |                                            |
| user_ldap | ldap_attributes_for_user_search   |                                            |
| user_ldap | ldap_backup_host                  |                                            |
| user_ldap | ldap_backup_port                  |                                            |
| user_ldap | ldap_base                         | dc=yunohost,dc=org                         |
| user_ldap | ldap_base_groups                  | ou=groups,dc=yunohost,dc=org               |
| user_ldap | ldap_base_users                   | ou=users,dc=yunohost,dc=org                |
| user_ldap | ldap_cache_ttl                    | 600                                        |
| user_ldap | ldap_configuration_active         | 1                                          |
| user_ldap | ldap_display_name                 | displayname                                |
| user_ldap | ldap_dn                           |                                            |
| user_ldap | ldap_dynamic_group_member_url     |                                            |
| user_ldap | ldap_email_attr                   | mail                                       |
| user_ldap | ldap_experienced_admin            | 0                                          |
| user_ldap | ldap_expert_username_attr         | uid                                        |
| user_ldap | ldap_expert_uuid_group_attr       |                                            |
| user_ldap | ldap_expert_uuid_user_attr        |                                            |
| user_ldap | ldap_group_display_name           | cn                                         |
| user_ldap | ldap_group_filter                 | objectClass=posixGroup                     |
| user_ldap | ldap_group_filter_mode            | 0                                          |
| user_ldap | ldap_group_member_assoc_attribute | uniqueMember                               |
| user_ldap | ldap_groupfilter_groups           |                                            |
| user_ldap | ldap_groupfilter_objectclass      | posixGroup                                 |
| user_ldap | ldap_host                         | localhost                                  |
| user_ldap | ldap_login_filter                 | (&(|(objectclass=posixAccount))(uid=%uid)) |
| user_ldap | ldap_login_filter_mode            | 0                                          |
| user_ldap | ldap_loginfilter_attributes       |                                            |
| user_ldap | ldap_loginfilter_email            | 0                                          |
| user_ldap | ldap_loginfilter_username         | 1                                          |
| user_ldap | ldap_nested_groups                | 0                                          |
| user_ldap | ldap_override_main_server         |                                            |
| user_ldap | ldap_paging_size                  | 500                                        |
| user_ldap | ldap_port                         | 389                                        |
| user_ldap | ldap_quota_attr                   | userquota                                  |
| user_ldap | ldap_quota_def                    |                                            |
| user_ldap | ldap_tls                          | 0                                          |
| user_ldap | ldap_turn_off_cert_check          | 0                                          |
| user_ldap | ldap_user_display_name            | cn                                         |
| user_ldap | ldap_user_display_name_2          |                                            |
| user_ldap | ldap_user_filter_mode             | 0                                          |
| user_ldap | ldap_userfilter_groups            |                                            |
| user_ldap | ldap_userfilter_objectclass       | posixAccount                               |
| user_ldap | ldap_userlist_filter              | objectclass=posixAccount                   |
| user_ldap | types                             | authentication                             |
| user_ldap | use_memberof_to_detect_membership | 1                                          |
+-----------+-----------------------------------+--------------------------------------------+

</details>

**Comment by Yomark1** [comment]
I do not know why it takes so long, but you could probably check with a command line utility like "top" to see where is server is most busy(mysql, ngnix?). Maybe mysqld is starving for resources or is not fine-tuned for performance matching your hardware. 
We have hundreds of users and much more files then you have, and the upgrade never took longer then an hour(where the "activity" app table upgrade step takes most of then time last time I upgraded).

**Comment by naguirre** [comment]
Hi,
I finally took the time to see what wer  wrong with my installation.
After looking at the mysql database, there was multiple tables (6 to be exact, one for each user ?) which were more than 20GB each.
The table was names like this oc_oc_cache_UUID
One explanation, could be that some time ago i Added a recursive symbolic link in the Mount point of each users. This would have generate a big tables with a lot of files.
After deleting these tables i lost all my shared folders and files, but the migration has been done correctly, and nextcloud is now working again !
I close this issue. Thanks for you help.
