### ISSUE TITLE
[BUG] Nextcloud admin panel hyperlinks to documentation broken

### ISSUE THREAD

**Issue by savimaki** [nextcloud/server#28180]
Nextcloud 22

Steps to replicate:
1: Go to settings
2: Go to any page that has info buttons next to titles
3: Click the info button and be greeted with a "File not found." 

Solution: Replace "22" from all the URLs with "stable".
e.g. 
```https://docs.nextcloud.com/server/22/go.php?to=admin-encryption```
 to 
```https://docs.nextcloud.com/server/stable/go.php?to=admin-encryption```

**Comment by kesselb** [comment]
Thanks :+1: 

Closing in favor of https://github.com/nextcloud/documentation/issues/7001.
