### ISSUE TITLE
Feature Request: Stock App

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/server#28206]
stock app, where you can monitor your stocks, futures,… in your cloud and maybe even get notifications at specific threshholds

**Comment by Spartachetto** [comment]
These are a lot of feature requests!
My advice would be to split them, verify if something similar already exists, and put them in the appropriate places.

For example _Possibility to search with filters with the default search (for example only in the current folder and better ui if there is alot of results as the dropdown is not the best way for more then 100 results^^)_ seems related to #27078 and #24644 .

The _pricetag to cards_ request belongs to the nextcloud/deck repository (https://github.com/nextcloud/deck ).

You can try to propose the _stock app_ in the users forum (https://help.nextcloud.com/ ).

**Comment by MrLoverLoverMMMM** [comment]
Thank you
-------- Ursprüngliche Nachricht --------Von: Spartachetto ***@***.***> Datum: 01.08.21  08:38  (GMT+01:00) An: nextcloud/server ***@***.***> Cc: MrLoverLoverMMMM ***@***.***>, Author ***@***.***> Betreff: Re: [nextcloud/server] A couple of feature requests which would make
  my day (#28206) 
These are a lot of feature requests!
My advice would be to split them, verify if something similar already exists, and put them in the appropriate places.
For example Possibility to search with filters with the default search (for example only in the current folder and better ui if there is alot of results as the dropdown is not the best way for more then 100 results^^) seems related to #27078 and #24644 .
The pricetag to cards request belongs to the nextcloud/deck repository (https://github.com/nextcloud/deck ).
You can try to propose the stock app in the users forum (https://help.nextcloud.com/ ).

**Comment by MrLoverLoverMMMM** [comment]
I trimmed it

**Comment by szaimen** [comment]
Hi 👋

We are currently cleaning up our issue tracker. The feature described in this issues sounds like a good idea for a dedicated app. Feel free to post it in our "App ideas" section in the forum, to find a developer that wants to work on it:
https://help.nextcloud.com/c/apps/app-ideas/21

We are closing this issue here now, so the "issue tracker" of the server repository can be used better to track issues instead.

Cheers
