### ISSUE TITLE
Problem db:convert from mysql / mariasql to postgressql

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/server#28205]
Hello!
I tried to convert my current mariaSQL-db to a new postgres-DB with the occ db:convert tool within nextcloud 21.3.
At the creation of the shema I already got the error :
An exception occurred while executing ‘DROP INDEX “primary”’
What could be the issue ?

Web Server: Apache 2
OS: Ubuntu 20.04
php: 7.4
Source DB: MariaSQL

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.4? If not, please close this issue. Thanks! :)
