### ISSUE TITLE
can't open the odt spreadsheets

### ISSUE THREAD

**Issue by atkome** [nextcloud/server#28219]
hello, since yesterday and the update of the ios application, I can't open the odt spreadsheets anymore!
is there a solution? thanks

**Comment by stavros-k** [comment]
Yes, the solution is to fill the bug report template, so devs can take a look to what is happening. 
Also ios app problems should be posted here -> https://github.com/nextcloud/ios

**Comment by szaimen** [comment]
It seems that the issue you have created is lacking the essential information to help us understand your problem. Please either open a new one and use the appropriate template, or edit your first comment to ensure that we can continue to work with you.

**Comment by atkome** [comment]
it's close, with the new update there is no problem
