### ISSUE TITLE
Improve App switching UX

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/server#28212]
At the moment upon clicking on an app in the app menu, the only feedback that the user gets is a spinner on the clicked app. The whole UI of the app that the user is leaving stays there, with all its elements still being interactive.
On top of that, in many case, bits of the UI of the next app are displayed even before the app is ready to be interacted with.

I think that upon clicking on another app we should:
- Freeze the UI (blank loading screen);
- Unlock the UI only when the next app has its main components loaded (usually navigation). E.g. In talk we'd unlock once we have the conversations list available.

For reference - here's the current state:

https://user-images.githubusercontent.com/26852655/127316767-85e8b6c1-c3d0-4993-889a-147ddc23b2fc.mov

cc @nextcloud/designers

**Comment by joshtrichards** [comment]
This appears to be the case today. Closing, but if I'm misread this obviously re-open. :)
