### ISSUE TITLE
Display status indicator in top right user avatar

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/server#28232]
It would be nice to visualize at a glance if my status is set to online, away, do not disturb, or invisible.

This can be done by displaying the little status circle on my avatar in the header. I think it's handy in case the status is permanently set.

<img width="486" alt="Screenshot 2021-07-29 at 12 09 41" src="https://user-images.githubusercontent.com/26852655/127474076-993a72e5-02cf-4142-a7df-7d3b7553b2bf.png">

cc @nextcloud/designers

**Comment by JohnCrafton** [comment]
Happy to take this one on.  Just coming around to the code, but having used Nextcloud for some time now, I'd love to give back.

**Comment by jancborchardt** [comment]
This is done now through the automatic status work by @CarlSchwan! :)
