### ISSUE TITLE
Find out who deleted files/folders

### ISSUE THREAD

**Issue by christopheg** [nextcloud/server#28254]
Dear,

When showing the 'Deleted files', would it be possible to indicate who deleted those files?

**Comment by prabhatjoshi321** [comment]
May I take on this Enhancement task

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by dbeniamine** [comment]
Hi,

A frequent issue that I have is users moving or deleting files by error.

I always end up finding the files on the server using the `find` command but it would be very useful to know who made the error and when so we can tell them how not to do this kind of deletions.

Furthermore it would nice to have the possibility for admin to receive email when more than a certain amount of files are deleted so we can retrieve them before user starts to panic.

**Comment by vvpolyakov** [comment]
This function is really needed, someone deleted a bunch of files from the server, we need to punish the culprits
