### ISSUE TITLE
account creation by users

### ISSUE THREAD

**Issue by JensInc** [nextcloud/server#28255]
**Is your feature request related to a problem? Please describe.**
I am using SSL client certificates  for several users. With each certificate each user can use several websites / services (Because the same CA is in the webserver / services. E.g. there is one central Apache server which checks the client certificates and proxy passes to the services.) This is very practical - especially when there is no distinction concerning user rights between the users needed. An administration has ones to manage a client certificate for a new users and not more. Applications like media wiki or grafana allow user account creations by users - e.g. by associating new users to a special group. Nextcloud does not allow it. 

**Describe the solution you'd like**
A dialog "create new account" which is available before login.

**Describe alternatives you've considered**
I know about LDAP or WebAuth ...

**Additional context**

**Comment by kesselb** [comment]
https://github.com/nextcloud/registration
