### ISSUE TITLE
Why remove the CORS partial content loading?

### ISSUE THREAD

**Issue by tio-trom** [nextcloud/server#28278]
My question is simple: Nextcloud used to have a CORS partial content loading feature https://github.com/nextcloud/server/blob/0447b53bda9fe95ea0cbed765aa332584605d652/lib/private/legacy/OC_Files.php#L88 and we used that a lot to pull our books and other files to our main website, using a custom book reader. Now we are unable to do that. I am wondering do you plan to bring it back? And why did you remove that feature?

Thanks!

**Comment by szaimen** [comment]
Hello,

If I understand your issue correctly, you should be able to do what you want to do with this app:
https://apps.nextcloud.com/apps/webapppassword

**Comment by tio-trom** [comment]
Hi,
Am not sure that's what I mean since the way I am accessing the files is by the public URL. We do not use any app. We use a web book reader that pulls a PDF on the fly and transforms it into a book format. We used to do that before the version 20 of Nextcloud, but now Nextcloud does not allow for partial content loading.
