### ISSUE TITLE
Settings -> "Storage is temporarily not available"

### ISSUE THREAD

**Issue by beccon4** [nextcloud/server#28276]
When I try to open the Settings menu from my user account, I'm displayed a rather blank page with a "Storage is temporarily not available" message. Nothing to do except the browser back and Nextcloud still works as expected with the Settings unavailabe for me.

The Settings menu works for other users though as normal.

I have an external SMB/CIFS storage configured to an Synology NAS - and an SSH share to the same machine.

Nothing of use in the log. I only get quite spammed with messages like 

`
{"reqId":"pgMBcIdTuCXpGaZCurPe","level":0,"time":"2021-07-31T13:59:20+00:00","remoteAddr":"89.16.xx.yy","user":"myself","app":"ocsms","method":"GET","url":"/index.php/apps/dashboard/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0","version":"21.0.1.1"}
{"reqId":"pgMBcIdTuCXpGaZCurPe","level":0,"time":"2021-07-31T13:59:20+00:00","remoteAddr":"89.16..xx.yy","user":"myself","app":"rainloop","method":"GET","url":"/index.php/apps/dashboard/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0","version":"21.0.1.1"}
`
and this here in the moment I select Settings

`
{"reqId":"pgMBcIdTuCXpGaZCurPe","level":0,"time":"2021-07-31T13:59:20+00:00","remoteAddr":"89.16.xx.yy","user":"myself","app":"scss_cacher","method":"GET","url":"/index.php/apps/dashboard/","message":"SCSSCacher::process ordinary check follows","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0","version":"21.0.1.1"}
{"reqId":"pgMBcIdTuCXpGaZCurPe","level":0,"time":"2021-07-31T13:59:20+00:00","remoteAddr":"89.16.xx.yy","user":"myself","app":"scss_cacher","method":"GET","url":"/index.php/apps/dashboard/","message":"SCSSCacher::process ordinary check follows","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0","version":"21.0.1.1"}
`
Nextcloud Version is 21.0.1.1 on Debian 9

What's wrong and how I get out of this?

**Comment by kesselb** [comment]
Most likely an app not compatible with Nextcloud 21. Hard to tell without the issue template. Try to disable all apps (note: some core apps are always enabled). If settings work again - enable apps one by one until you found the faulty app.

**Comment by beccon4** [comment]
I did a compliance check with occ - and surprisingly according to this even the files app is not compliant. What will I have to do next?

`www-data@nextcloud-lxd:~/nextcloud$ php ./occ app:check-code files
Analysing /var/www/nextcloud/apps/files/lib/BackgroundJob/ScanFiles.php
 1 errors
    line   94: OC_Util - Static method of private class must not be called
Analysing /var/www/nextcloud/apps/files/lib/Helper.php
 1 errors
    line   51: OC_Helper - Static method of private class must not be called
Analysing /var/www/nextcloud/apps/files/lib/AppInfo/Application.php
 1 errors
    line  146: OC_Helper - Static method of private class must not be called
Analysing /var/www/nextcloud/apps/files/lib/Controller/ViewController.php
 5 errors
    line  125: OC_App - Static method of private class must not be called
    line  145: OC_Util - Static method of private class must not be called
    line  148: OC_Helper - Static method of private class must not be called
    line  251: OC_Helper - Static method of private class must not be called
    line  255: OC_Helper - Static method of private class must not be called
Analysing /var/www/nextcloud/apps/files/lib/Controller/AjaxController.php
 1 errors
    line   44: OC_Util - Static method of private class must not be called
Analysing /var/www/nextcloud/apps/files/templates/appnavigation.php
 1 errors
    line   96: == - is discouraged
Analysing /var/www/nextcloud/apps/files/ajax/list.php
 5 errors
    line   32: OC_JSON - Static method of deprecated class must not be called
    line   84: OC_JSON - Static method of deprecated class must not be called
    line   87: OC_JSON - Static method of deprecated class must not be called
    line   95: OC_JSON - Static method of deprecated class must not be called
    line  103: OC_JSON - Static method of deprecated class must not be called
Analysing /var/www/nextcloud/apps/files/ajax/download.php
 3 errors
    line   32: OCP\User - Static method of deprecated class must not be called
    line   32: OCP\User::checkLoggedIn - Method of deprecated class must not be called
    line   64: OC_Files - Static method of private class must not be called
Analysing /var/www/nextcloud/apps/files/recentlist.php
 2 errors
    line   26: OCP\User - Static method of deprecated class must not be called
    line   26: OCP\User::checkLoggedIn - Method of deprecated class must not be called
Invalid appinfo.xml file found: Element 'settings': This element is not expected. Expected is one of ( contactsmenu, collaboration, sabre, public ).

App is not compliant
www-data@nextcloud-lxd:~/nextcloud$ php ./occ app:check-code files_external
Analysing /var/www/nextcloud/apps/files_external/lib/Command/Notify.php
 1 errors
    line  282: OC_Util - Static method of private class must not be called
Analysing /var/www/nextcloud/apps/files_external/lib/Lib/Storage/SMB.php
 2 errors
    line  582: == - is discouraged
    line  710: OC_Helper - Static method of private class must not be called
Analysing /var/www/nextcloud/apps/files_external/lib/Lib/Storage/FTP.php
 2 errors
    line  144: != - is discouraged
    line  144: != - is discouraged
Analysing /var/www/nextcloud/apps/files_external/lib/Lib/Storage/SFTPReadStream.php
 1 errors
    line  165: == - is discouraged
Analysing /var/www/nextcloud/apps/files_external/lib/Lib/Storage/SFTP.php
 2 errors
    line  219: OCP\Files - Static method of deprecated class must not be called
    line  219: OCP\Files::getStorage - Method of deprecated class must not be called
Analysing /var/www/nextcloud/apps/files_external/list.php
 2 errors
    line   26: OCP\User - Static method of deprecated class must not be called
    line   26: OCP\User::checkLoggedIn - Method of deprecated class must not be called
Analysing /var/www/nextcloud/apps/files_external/ajax/oauth2.php
 3 errors
    line   25: OC_JSON - Static method of deprecated class must not be called
    line   26: OC_JSON - Static method of deprecated class must not be called
    line   27: OC_JSON - Static method of deprecated class must not be called
Analysing /var/www/nextcloud/apps/files_external/ajax/applicable.php
 4 errors
    line   27: OC_JSON - Static method of deprecated class must not be called
    line   28: OC_JSON - Static method of deprecated class must not be called
    line   30: OC_JSON - Static method of deprecated class must not be called
    line   57: OC_JSON - Static method of deprecated class must not be called
App is not compliant
www-data@nextcloud-lxd:~/nextcloud$ php ./occ app:check-code external
Invalid appinfo.xml file found: Element 'documentation': This element is not expected. Expected is one of ( description, version ).

App is not compliant
`

It seems that I have all apps up to date:
`php ./occ app:update
Please specify an app to update or "--all" to update all updatable apps"
www-data@nextcloud-lxd:~/nextcloud$ php ./occ app:update --all
`

What can I do now?

**Comment by kesselb** [comment]
Most likely an app not compatible with Nextcloud 21. Hard to tell without the issue template. Try to disable all apps (note: some core apps are always enabled). If settings work again - enable apps one by one until you found the faulty app.
