### ISSUE TITLE
'files_encryption' files/folders remains after run `occ encryption:decrypt-all`

### ISSUE THREAD

**Issue by acsfer** [nextcloud/server#28286]
- NC 21.0.3

I've run the `occ:decrypt-all` on my instance, completed without troubles. All files are now decrypted correctly (verified by simply downloading somes files trough SFTP), but all `files_encryption` folders (and all it's contents + new `.decrypted.timestamp` files) remains in the data folder for all users.

Here for a test user, the `files_encryption/keys/files` folder:
![image](https://user-images.githubusercontent.com/12234510/127832228-e285a95e-92f8-4b74-bfaf-e1da52035bea.png)

Shouldn't these folders+files be deleted after all files are decrypted?

Thanks.
cc @nextcloud/encryption

**Comment by szaimen** [comment]
Needs info from @nextcloud/encryption

**Comment by andyxheli** [comment]
@szaimen  Yes, I can confirm this. I think once someone decrypts the data the files_encryption folder should be deleted automatically and this is currently not happening. What i did was go into each user and delete the files_encryption folder but its a pain.

**Comment by acsfer** [comment]
Well i could do a `rm -rf data/*/files_encryption` but need to be sure this is safe. 😅

**Comment by andyxheli** [comment]
After i removed all files i did a scan:files -all and scan:files-app-data

**Comment by andyxheli** [comment]
Still an issue

**Comment by acsfer** [comment]
I finally (after a good backup) did a `rm -rf data/*/files_encryption` followed by `files:scan --all` and all went fine.
