### ISSUE TITLE
Add toolset for administrators to tidy up app data after uninstall

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/server#28283]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Is your feature request related to a problem? Please describe.
As an administrator, I want to be able to wipe all data of an app, because of privacy reasons and to avoid data pollution.

### Describe the solution you'd like
I would propose a section in the administration app where uninstalled apps and their data fragments or database tables are listed, so I can decide, which data is no more neccessary. The list gives the options to wipe all or selected left over data.

### Describe alternatives you've considered
No Idea

### Additional context
When an app is removed, the tables still exist inside the database, and this could be maybe forever. This can be a privacy issue, if user data is still stored, where it should be deleted. 

In some situations, it can help to remove the causes of installation and other errors. A manual deletion is possible, but the user has to be aware of the migration system and has to know, where an app is registered inside the core databases. 

The uninstall repair step is no solution because 
* it is also called on disabling an app,
* AFAIK there is no user interaction, that allows the administrator to decide to keep the data or not and
* it is rather possible, that the data should not be deleted, whan removing an app.

Currently we cannot judge, 
* if the administrator is aware, that the data is wiped out or not and
* if the administrator wants the data deleted or preserved.

**Comment by szaimen** [comment]
I would argue that this makes sense but I fear it is currently far away from our roadmap.

**Comment by szaimen** [comment]
cc @nextcloud/server

**Comment by Chartman123** [comment]
Isn't this a duplicate of #5539?

**Comment by dartcafe** [comment]
> Isn't this a duplicate of #5539?

Indeed it is. I'll close it it favour to #5539 . 

Just for the records, in Polls we implemented `occ polls:db:purge` for removing
* all migration records 
* all app configs and
* all tables (oc_polls_*) 

regarding Polls. But the app must be active for that.
