### ISSUE TITLE
folder deleted during webdav sync if '#' character is present in the path

### ISSUE THREAD

**Issue by dsebire** [nextcloud/server#28291]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. sync a fileserver (Synology NAS) to a nextcloud server using webdav
2. use some '#' in folder names (as first character)
     PUBLIC/test/#toto/tata/file.txt
3. rename "tata" to "titi" on the synology

### Expected behaviour
the "tata" folder should be renamed

### Actual behaviour
the folder "test" is deleted with all it's content

i suppose that the # character is interpreted as a comment ! (and the result command is DELETE PUBLIC/test)

this behaviour is very annoying with windows client on the synology, as when you create a folder, you have to rename it just after ! if a folder contains a '#' character, the parent folder will be deleted.
as you'll see in the logs, the complete path is sent to nextcloud, but only the path before the # character is deleted.

### Server configuration

Debian 10.10

Server version: Apache/2.4.38 (Debian)
Server built:   2021-06-10T10:13:06

mysql  Ver 8.0.26 for Linux on x86_64 (MySQL Community Server - GPL)

PHP 7.3.29-1~deb10u1 (cli) (built: Jul  2 2021 04:04:33) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.29, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.29-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies

Nextcloud 21.0.2

updated NC16->17->18->19->20->21

Jurišić debian apt repository (referenced here https://help.nextcloud.com/t/linux-packages-status/10216)

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.14.3
  - cloud_federation_api: 1.4.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - firstrunwizard: 2.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - workflowengine: 2.3.0
Disabled:
  - accessibility
  - admin_audit
  - comments
  - contactsinteraction
  - dashboard
  - encryption
  - files_external
  - files_versions
  - files_videoplayer
  - nextcloud_announcements
  - recommendations
  - support
  - survey_client
  - user_ldap
  - weather_status

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.cty-group.fr"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.2.1",
        "overwrite.cli.url": "http:\/\/cloud.mydom.fr\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "loglevel": 2,
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "log_rotate_size": 104857600,
        "trashbin_retention_obligation": "auto, 15",
        "versions_retention_obligation": "auto, 15",
        "upgrade.disable-web": "true",
        "tempdirectory": "\/var\/www\/nextcloud\/tmp",
        "default_phone_region": "FR"
    }
}
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Webdav

### Client configuration
**Browser:**
NA

#### Web server error log
<details>
<summary>Web server error log</summary>
W.X.Y.Z - root [02/Aug/2021:16:20:03 +0200] "MKCOL /nextcloud/remote.php/webdav/PUBLIC/test HTTP/1.1" 201 6601 "-" "-"
W.X.Y.Z - root [02/Aug/2021:16:20:04 +0200] "PROPFIND /nextcloud/remote.php/webdav/PUBLIC/test HTTP/1.1" 207 7260 "-" "-"
W.X.Y.Z - root [02/Aug/2021:16:20:11 +0200] "MKCOL /nextcloud/remote.php/webdav/PUBLIC/test/%23toto HTTP/1.1" 201 6603 "-" "-"
W.X.Y.Z - root [02/Aug/2021:16:20:11 +0200] "PROPFIND /nextcloud/remote.php/webdav/PUBLIC/test/%23toto HTTP/1.1" 207 7262 "-" "-"
W.X.Y.Z - root [02/Aug/2021:16:20:17 +0200] "MKCOL /nextcloud/remote.php/webdav/PUBLIC/test/%23toto/tata HTTP/1.1" 201 6605 "-" "-"
W.X.Y.Z - root [02/Aug/2021:16:20:17 +0200] "PROPFIND /nextcloud/remote.php/webdav/PUBLIC/test/%23toto/tata HTTP/1.1" 207 7273 "-" "-"
W.X.Y.Z - root [02/Aug/2021:16:20:28 +0200] "PUT /nextcloud/remote.php/webdav/PUBLIC/test/%23toto/tata/file.txt HTTP/1.1" 201 6932 "-" "-"
W.X.Y.Z - root [02/Aug/2021:16:20:29 +0200] "PROPFIND /nextcloud/remote.php/webdav/PUBLIC/test/%23toto/tata/file.txt HTTP/1.1" 207 7260 "-" "-"
W.X.Y.Z - root [02/Aug/2021:16:22:29 +0200] "MOVE /nextcloud/remote.php/webdav/PUBLIC/test/%23toto/tata HTTP/1.1" 404 6838 "-" "-"
W.X.Y.Z - root [02/Aug/2021:16:22:29 +0200] "MKCOL /nextcloud/remote.php/webdav/PUBLIC/test/%23toto/titi HTTP/1.1" 409 6801 "-" "-"
W.X.Y.Z - root [02/Aug/2021:16:22:30 +0200] "DELETE /nextcloud/remote.php/webdav/PUBLIC/test/%23toto/tata HTTP/1.1" 404 6836 "-" "-"
W.X.Y.Z - root [02/Aug/2021:16:22:33 +0200] "MKCOL /nextcloud/remote.php/webdav/PUBLIC/test/%23toto/titi HTTP/1.1" 409 6801 "-" "-"
W.X.Y.Z - root [02/Aug/2021:16:22:37 +0200] "MKCOL /nextcloud/remote.php/webdav/PUBLIC/test/%23toto/titi HTTP/1.1" 409 6807 "-" "-"
W.X.Y.Z - root [02/Aug/2021:16:22:40 +0200] "MKCOL /nextcloud/remote.php/webdav/PUBLIC/test/%23toto/titi HTTP/1.1" 409 6799 "-" "-"
W.X.Y.Z - root [02/Aug/2021:16:22:41 +0200] "MKCOL /nextcloud/remote.php/webdav/PUBLIC/test/%23toto/titi HTTP/1.1" 409 6803 "-" "-"
W.X.Y.Z - root [02/Aug/2021:16:22:44 +0200] "MKCOL /nextcloud/remote.php/webdav/PUBLIC/test/%23toto/titi HTTP/1.1" 409 6801 "-" "-"
W.X.Y.Z - root [02/Aug/2021:16:22:48 +0200] "MKCOL /nextcloud/remote.php/webdav/PUBLIC/test/%23toto/titi HTTP/1.1" 409 6803 "-" "-"
W.X.Y.Z - root [02/Aug/2021:16:22:53 +0200] "MKCOL /nextcloud/remote.php/webdav/PUBLIC/test/%23toto/titi HTTP/1.1" 409 6801 "-" "-"
W.X.Y.Z - root [02/Aug/2021:16:22:54 +0200] "MKCOL /nextcloud/remote.php/webdav/PUBLIC/test/%23toto/titi HTTP/1.1" 409 6805 "-" "-"
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Nothing
</details>

**Comment by szaimen** [comment]
How did you make sure that the issue is on Nextcloud's side and not Synologys?

**Comment by dsebire** [comment]
Because the url sent by synology is correct, and i didn't noticed the problem using apache as webdav server

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by dsebire** [comment]
Hi,
The bug is still occuring with 25.0.3.

thanks
Regards

**Comment by dsebire** [comment]
Hi,
Problem still exists on nextcloud 26.x and 27.x

Could someone have a look at this ?
Thanks
Regards

**Comment by dsebire** [comment]
FYI, problem still exists in nextcloud 28 and 29.

**Comment by dsebire** [comment]
but problem fixed. nextcloud uninstalled.
