### ISSUE TITLE
Privacy bug: user can view all contacts

### ISSUE THREAD

**Issue by VicM68** [nextcloud/server#28308]
Hi.
I'm VicM68.
I have NextCloud 1.6.1-109 extension installed on vps with Plesk Onyx 17.8.11 panel and CentOS 6.10
The bug of NextCloud is that it allows any user, on their desktop, to see **all the contacts (and their emails)** created by the super administrator or administrator, even if the users are created in different groups.
**This is a privacy bug**.

**Comment by socialize-IT** [comment]
This is a matter of your configuration. You can disable autocomplete in the adminsettings "sharing" or limit it to users in the same group.

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
