### ISSUE TITLE
Deleting foreign Shared Files creates duplicate copies in files_trashbin of both ShareR and ShareE users

### ISSUE THREAD

**Issue by stefan123t** [nextcloud/server#28317]
### Steps to reproduce
Create a Shared Folder under user ShareR
Add a (eventually large) file to this Folder

```
user@server ~ $ ls -l /nextcloud-data/*/files/Shared/       
-rw-rw---- 1 www www 1620789496 Aug  4 16:44  file.ext
```

Now as user ShareE who has full access to this folder
Delete the large file in this Shared Folder

looking at the filesystem the large file will be moved into the files_trashbin/files folder of user ShareR 
and a copy of the large file will be copied to the files_trashbin/files folder of user ShareE

```
user@server ~ $ ls -l /nextcloud-data/*/files_trashbin/files/file*
-rw-rw---- 1 www www 1620789496 Aug  4 16:44 /nextcloud-data/ShareR/files_trashbin/files/file.ext.d1628145967
-rw-rw---- 1 www www 1515569152 Aug  5 08:46 /nextcloud-data/ShareE/files_trashbin/files/file.ext.d1628145967
```

When I remove / empty my trashbin as user ShareE the copy in my files_trashbin/files folder is removed 
but the original file in the Deleted Files of the user ShareR continues to exist until it is also removed there.

```
user@server ~ $ ls -l /nextcloud-data/*/files_trashbin/files/file*
-rw-rw---- 1 www www 1620789496 Aug  4 16:44 /nextcloud-data/ShareR/files_trashbin/files/file.ext.d1628145967
```

### Expected behaviour
I would expect that removing the file from a shared folder removes the file directly / completely.
There could be a database pointer to the deleted files of the user ShareR for the user ShareE to recover that deleted file for both users.

### Actual behaviour
Instead it is put into the recycle bin of both users, which could be termed a feature.
Though it is not delegated to the recycle bin of the owner of the file only,
but instead a copy is persisted on disk in the deleted files of the ShareE 
which temporarily takes double disk space than before removing it.
Now both users have to remove it from their recycle bin to actually free the double space on disk again.
This could be prevented either by using hard-/symlinks ?

## Server configuration detail

**Operating system:** Linux 5.10.55 #1 SMP Mon Aug 2 11:32:19 CEST 2021 x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 10.2.36

**PHP version:** 

7.4.21
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, hash, fileinfo, filter, ftp, gd, gettext, gmp, SPL, iconv, session, intl, json, ldap, mbstring, standard, mysqlnd, mysqli, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, Reflection, imap, SimpleXML, soap, sockets, sodium, exif, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, apache2handler, apcu, imagick, memcached, redis, Zend OPcache

**Nextcloud version:** 21.0.1 - 21.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated since Nextcloud 12

**Where did you install Nextcloud from:** Upgraded since Nextcloud 12

<details><summary>Signing status</summary>

Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 23a3fa45757b26795f5cf8f94d9e5bce76fc916288a6458679311b312c167adcf4158ccb2c5c3db791fa0b87703b6c5863afb6c9d790b8cbac5ab3ae8c3418fb
                            [current] => 86c1f1b719b65bf02b1dca9b061ef310c8dfface25c9ccfa243c4090665fa6f305d8a4143d7410350af27b1d9e14968c7d999a965d1e110bc674d30ed5dee4e8
                        )

                )

            [EXTRA_FILE] => Array
                (
                    [.htaccess_20210410] => Array
                        (
                            [expected] => 
                            [current] => 507ce8f37b72f6eaecfec04f486525d3784cdc5dbcf350b1f5166701cd145e74c5bb1419c37458450b1f419bcd0d9a333dc4c4d79cf004ab6578f6bca6ca7d09
                        )

                )

        )

)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - admin_audit: 1.11.0
 - announcementcenter: 5.0.0
 - appointments: 1.9.3
 - apporder: 0.13.0
 - calendar: 2.3.1
 - checksum: 1.1.2
 - circles: 0.21.4
 - cloud_federation_api: 1.4.0
 - comments: 1.11.0
 - contacts: 4.0.1
 - contactsinteraction: 1.2.0
 - dashboard: 7.1.0
 - dav: 1.17.1
 - deck: 1.4.3
 - duplicatefinder: 0.0.11
 - encryption: 2.9.0
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_accesscontrol: 1.11.0
 - files_automatedtagging: 1.11.0
 - files_pdfviewer: 2.1.0
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_videoplayer: 1.10.0
 - firstrunwizard: 2.10.0
 - forms: 2.3.0
 - groupfolders: 9.0.2
 - impersonate: 1.8.0
 - integration_github: 1.0.0
 - integration_moodle: 1.0.0
 - integration_twitter: 1.0.0
 - issuetemplate: 0.7.0
 - keeweb: 0.6.5
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - mail: 1.10.2
 - maps: 0.1.9
 - nextcloud_announcements: 1.10.0
 - notes: 4.1.1
 - notifications: 2.9.0
 - oauth2: 1.9.0
 - occweb: 0.0.7
 - password_policy: 1.11.0
 - photos: 1.3.0
 - polls: 3.0.0
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - quota_warning: 1.11.0
 - recommendations: 1.0.0
 - sensorlogger: 0.0.9
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - social: 0.4.2
 - spreed: 11.3.1
 - support: 1.4.0
 - survey_client: 1.9.0
 - systemtags: 1.11.0
 - tasks: 0.14.1
 - text: 3.2.0
 - theming: 1.12.0
 - twofactor_backupcodes: 1.10.0
 - updatenotification: 1.11.0
 - user_status: 1.1.1
 - viewer: 1.5.0
 - weather_status: 1.1.0
 - workflowengine: 2.3.0
Disabled:
 - files_external
 - files_lock
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "overwriteprotocol": "https",
    "htaccess.RewriteBase": "\/nextcloud",
    "dbtype": "mysql",
    "version": "21.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "***REMOVED SENSITIVE VALUE***",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "updater.release.channel": "stable",
    "app_install_overwrite": [
        "apporder",
        "occweb",
        "issuetemplate",
        "sensorlogger",
        "files_lock"
    ],
    "mysql.utf8mb4": true,
    "encryption.legacy_format_support": false,
    "encryption.key_storage_migrated": false,
    "auth.bruteforce.protection.enabled": true,
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpsecure": "tls",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "data-fingerprint": "***REMOVED SENSITIVE VALUE***",
    "default_phone_region": "DE",
    "filelocking.enabled": true,
    "filelocking.ttl": 3600,
    "filelocking.debug": true
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0

**Operating system:** Linux 5.10.55 #1 SMP Mon Aug 2 11:32:19 CEST 2021 x86_64 AMD Ryzen 5 2600X Six-Core Processor AuthenticAMD GNU/Linux

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```

```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by kinimodmeyer** [comment]
just FYI that current behaivor is intended not a bug: https://docs.nextcloud.com/server/latest/user_manual/ar/files/deleted_file_management.html#what-happens-when-shared-files-are-deleted

**Comment by stefan123t** [comment]
Thanks for clarification, I still hold that the design decision is effectively doubling files and disk usage when moving them into the files_trashbin. This might not be what was intended by either of the users, removing usually tends to free space.

I do not understand the [admin documentation](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#deleted-items-trash-bin) on how to disable trash_bin and this unwanted moving and duplication altogether.

Would I need to set the following to remove `auto` when space needed and to always remove after `0` days ?
`'trashbin_retention_obligation' => 'auto,0', `

**Comment by szaimen** [comment]
cc @nextcloud/server-triage if this behaviour will be changed or not.

**Comment by stefan123t** [comment]
@szaimen did you get a response or feedback from nextcloud/server-triage or could we link it to an issue there ?
Our nextcloud-stale bot seems to get nervous =^D

**Comment by stefan123t** [comment]
Keepalive ping

**Comment by stefan123t** [comment]
Keepalive ping
Is there anything I can do from my side to prevent the nextcloud-stale bot 
or is there a link to the upstream nextcloud/server-triage issue / conversation ?

**Comment by CarlSchwan** [comment]
Yeah this is the intended behavior and I'm currently trying to add that behavior to the groupfolder trashbin implementation too. What we could do at some point is to try to have not to duplicate the file storage-wise, but this seems like a lot of effort for a problem that doesn't affect a lot of users and that has an easy workaround: trash bin retention policies.

**Comment by stefan123t** [comment]
Dear Carl,

Thanks for the quick reply.

Yes this may not affect a lot of users as it becomes only apparent when you are low on storage.

This may even be replicated when you share a file with multiple users, though I only tested with two users (ShareR and ShareE). I did not try it with multiple SharEes or recovering the file in between.

Though the problem becomes more prominent when files become larger .
Though I have no clear evidence (yet), but it may even be related to some file locks not being cleared on my system?

Is there a way to prevent the recycle bin completely. I am only aware that I could shorten retention to 1 day. But nothing like some minutes or no retention at all.

Is this a sane setting to not go via trashbin retention:
'trashbin_retention_obligation' => 'auto,0'

Could you educate me on how to set it to no retention?

Kind regards,
Stefan

**Comment by CarlSchwan** [comment]
You can just disable the trash application in /settings/apps and then Nextcloud won't use the trash anymore.

**Comment by stefan123t** [comment]
Many Thanks!
I finally found it your way under User > Apps > Your Apps: Deleted Files and [Disable]d it.
I will monitor my nextcloud system for its behaviour but I believe this issue can probably be closed as I do not need it anymore.
Cheers, Stefan
