### ISSUE TITLE
Upgrade to 11 from 10.0.2 not proposed by updater

### ISSUE THREAD

**Issue by stanelie** [nextcloud/server#2832]
### Steps to reproduce
1. Go to admin page
2. Read the updater section
3.

### Expected behaviour
It should say "your version is outdated and suggest upgrade to 11 from 10.0.2

### Actual behaviour
It shows that "Your version is up to date." If I switch the channel from "stable" to "beta", then I get a proposition to upgrade to 11.  I guess this is wrong since the 11 release is classified as "stable" on the download page of the Nextcloud website

### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
Apache/2.4.7 (Ubuntu)
**Database:**
mysql  Ver 14.14
**PHP version:**
PHP 5.6.29-1+deb.sury.org~trusty+1
**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgraded from owncloud
**Where did you install Nextcloud from:**
Nextcloud website?
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by stanelie** [comment]
Never mind, I just read this on the https://nextcloud.com/blog/nextcloud-11-sets-new-standard-for-security-and-scalability/ page : 

> If you would like to update, you can do so by downloading the zip file on our download page and following the manual upgrade instructions or wait for 2-3 weeks until we make the new release available in the Nextcloud Updater app. If you prefer to update now already using the easy to use Updater app, you can set the release channel to beta this will give you Nextcloud 11 final. Be sure to set it back to stable after the upgrade is done!

**Comment by floweh** [comment]
It still seems to miss in the stable channel. I updated via the beta channel today.

**Comment by osamak** [comment]
Still missing from the stable channel. I also updated via the beta channel today.

**Comment by CreateWebNZ** [comment]
Same here.

**Comment by kiv57** [comment]
Is there any drawback to switch to beta channel ? (ie for future updates)
