### ISSUE TITLE
Slow upload only over web

### ISSUE THREAD

**Issue by IamAliBaba** [nextcloud/server#28328]
HI,
on Nextcloud 21.0.3 slow upload over web , 
webdev is ok.

seems bug

**Comment by IamAliBaba** [comment]
![2021-08-06_0-49-02](https://user-images.githubusercontent.com/26478599/128419266-8594c677-da98-4b81-99e2-8346190d22cb.gif)

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
