### ISSUE TITLE
Add an option to keep app bar background at Dashboard

### ISSUE THREAD

**Issue by unclev** [nextcloud/server#28343]
If the _Dashboard_ background image is light enough then the application icons are poorly distinguishable. Example:

![DeepinScreenshot_select-area_20210807222617_resized](https://user-images.githubusercontent.com/5719098/128607361-d97b5af1-2c7c-4f73-a280-4ebf2d7c5b34.png)
It would be great having ability to set the app bar background at _Dashboard_ according to the Nextcloud theme, eg.:

![DeepinScreenshot_select-area_20210807224405_resized](https://user-images.githubusercontent.com/5719098/128607785-634fd01d-c692-431f-b57b-e195037274b7.png)
<hr/>

As a workaround I tried to create a _Dashboard_ background image with dark bar at the top that extends to the app icon area, example with the _Dark Breeze_ theme

![DeepinScreenshot_select-area_20210807225918_resized](https://user-images.githubusercontent.com/5719098/128608186-6c2e84a1-1c92-4039-a484-52c0761e4be2.png)

This is not a solution as the area resizes with the browser window, and it also depends on the browser panel size at the top. E.g. - browser in the fullscreen mode:
![DeepinScreenshot_select-area_20210807230757_resized](https://user-images.githubusercontent.com/5719098/128608447-1d068583-54b7-4940-bff1-888a9bf4d268.png)
and not proportionally resized window
![DeepinScreenshot_select-area_20210807231440_resized](https://user-images.githubusercontent.com/5719098/128608619-6e069245-8103-49fb-9299-518eb1580a30.png)
<hr/>

I'm using **Nextcloud 20.0.12** docker image `nextcloud:20-fpm`.

**Comment by szaimen** [comment]
Hi there, if I remember correctly was decided that we will not introduce an option to toggle this.
You can though enable it youself by installing the custom_css app and adding the following css code:
```
#header { background-color: var(--color-primary) !important; }
```

**Comment by unclev** [comment]
Thank you, @szaimen ! This custom CSS works for the standard theming settings.

When using _Breeze Dark_ it differs:

```css
#header { background-color: var(--color-background-darker) !important; }
```

This solves the issue.
