### ISSUE TITLE
Updating from 10.0.2 ->11.0.0

### ISSUE THREAD

**Issue by mixim-mixim** [nextcloud/server#2835]
### Steps to reproduce
1. I followed ur description from here:
    https://docs.nextcloud.com/server/11/admin_manual/maintenance/manual_upgrade.html
2.
3.

### Expected behaviour
<b>NO</b> error in the admin panel ....

### Actual behaviour
<b>Error</b> in the admin panel ....

 Die Ausführung des Cron-Jobs über die Kommandozeile war nicht möglich. Die folgenden technischen Fehler sind dabei aufgetreten:

    Das Schreiben in das „config“-Verzeichnis ist nicht möglich Dies kann normalerweise behoben werden, <a href="https://docs.nextcloud.com/server/11/go.php?to=admin-dir_permissions" target="_blank" rel="noreferrer">indem dem Webserver Schreibzugriff auf das Konfigurationsverzeichnis gegeben wird</a>.

... means the Cron-Job can't be executed on the CLI, because the writing in the config directory failed ...

Something wrong with the filepermissions ... and yes i did these commands from the update description:

chown -R www-data:www-data html
find html/ -type d -exec chmod 750 {} \;
find html/ -type f -exec chmod 640 {} \;

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
mySQL

**PHP version:**

PHP 7.0.8-3+deb.sury.org~wily+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-3+deb.sury.org~wily+1, Copyright (c) 1999-2016, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
from 10.0.2 -> now is 11.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
from 10.0.2

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-11.0.0.zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - apporder
  - audioplayer
  - calendar
  - contacts
  - direct_menu
  - documents
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - news
  - ownnote
  - rainloop
  - tasks
  - user_external
  - user_ldap
  - user_saml

```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oce10857b6d4",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/opt\/fairsoft.koeln\/nextcloud\/data\/",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "dbname": "???",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de",
        "defaultapp": "rainloop",
        "installed": true,
        "loglevel": 0,
        "theme": "",
        "forcessl": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/vhosts\/fairsoft.koeln\/domains\/nextcloud.fairsoft.koeln\/html\/apps",
                "url": "\/apps",
                "writable": false
            }
        ],
        "appstoreenabled": false,
        "appstoreurl": "http:\/\/api.nextcloud.com\/v1",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "localhost",
        "mail_smtpport": "465",
        "mail_smtptimeout": 10,
        "mail_smtpauthtype": "LOGIN",
        "maintenance": false,
        "trusted_domains": [
            "nextcloud.fairsoft.koeln"
        ],
        "mail_smtpauth": 1,
        "xframe_restriction": false,
        "mail_from_address": "contact",
        "mail_domain": "???",
        "mail_smtpsecure": "ssl",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "user_webdavauth_url": "https:\/\/nextcloud.fairsoft.koeln",
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** 

no external storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** 
</details>

### Client configuration
**Browser:**
firefox

**Operating system:**
Ubuntu

#### Web server error log
<details>
<summary>Web server error log</summary>
</details>
Error	PHP	fclose() expects parameter 1 to be resource, boolean given at /var/www/vhosts/fairsoft.koeln/domains/nextcloud.fairsoft.koeln/html/lib/private/Files/Storage/Local.php#218	2016-12-22T21:30:03+0100
Error	PHP	fread() expects parameter 1 to be resource, boolean given at /var/www/vhosts/fairsoft.koeln/domains/nextcloud.fairsoft.koeln/html/lib/private/Files/Storage/Local.php#217	2016-12-22T21:30:03+0100
Error	PHP	fopen(/opt/fairsoft.koeln/nextcloud/data//fairsoftoc/avatar.jpg): failed to open stream: No such file or directory at /var/www/vhosts/fairsoft.koeln/domains/nextcloud.fairsoft.koeln/html/lib/private/Files/Storage/Local.php#216	2016-12-22T21:30:03+0100
Error	PHP	filesize(): stat failed for /opt/fairsoft.koeln/nextcloud/data//fairsoftoc/avatar.jpg at /var/www/vhosts/fairsoft.koeln/domains/nextcloud.fairsoft.koeln/html/lib/private/Files/Storage/Local.php#211	2016-12-22T21:30:03+0100
Error	core	Error while running background job (Doctrine\DBAL\Exception\SyntaxErrorException): An exception occurred while executing 'DELETE FROM `oc_activity_mq` WHERE `amq_timestamp` <= ? AND `amq_affecteduser` IN ()' with params [1482438601]: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1	2016-12-22T21:30:02+0100
Error	PHP	fclose() expects parameter 1 to be resource, boolean given at /var/www/vhosts/fairsoft.koeln/domains/nextcloud.fairsoft.koeln/html/lib/private/Files/Storage/Local.php#218	2016-12-22T21:30:03+0100
Error	PHP	fread() expects parameter 1 to be resource, boolean given at /var/www/vhosts/fairsoft.koeln/domains/nextcloud.fairsoft.koeln/html/lib/private/Files/Storage/Local.php#217	2016-12-22T21:30:03+0100
Error	PHP	fopen(/opt/fairsoft.koeln/nextcloud/data//fairsoftoc/avatar.jpg): failed to open stream: No such file or directory at /var/www/vhosts/fairsoft.koeln/domains/nextcloud.fairsoft.koeln/html/lib/private/Files/Storage/Local.php#216	2016-12-22T21:30:03+0100
Error	PHP	filesize(): stat failed for /opt/fairsoft.koeln/nextcloud/data//fairsoftoc/avatar.jpg at /var/www/vhosts/fairsoft.koeln/domains/nextcloud.fairsoft.koeln/html/lib/private/Files/Storage/Local.php#211	
#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
```
</details>

**Comment by mixim-mixim** [comment]
Everything seems to be ok after i executed my older file permission script 

....
printf "Creating possible missing Directories\n"
mkdir -p $datapath
mkdir -p $ncpath/assets
mkdir -p $ncpath/updater

printf "chmod Files and Directories\n"
find ${ncpath}/ -type f -print0 | xargs -0 chmod 0640
find ${ncpath}/ -type d -print0 | xargs -0 chmod 0750

printf "chown Directories\n"
chown -R ${rootuser}:${htgroup} ${ncpath}/
chown -R ${htuser}:${htgroup} ${ncpath}/apps/
chown -R ${htuser}:${htgroup} ${ncpath}/assets/
chown -R ${htuser}:${htgroup} ${ncpath}/config/
chown -R ${htuser}:${htgroup} ${datapath}
chown -R ${htuser}:${htgroup} ${ncpath}/themes/
chown -R ${htuser}:${htgroup} ${ncpath}/updater/

chmod +x ${ncpath}/occ

printf "chmod/chown .htaccess\n"
if [ -f ${ncpath}/.htaccess ]
 then
  chmod 0644 ${ncpath}/.htaccess
  chown ${rootuser}:${htgroup} ${ncpath}/.htaccess
fi
if [ -f $datapath}/.htaccess ]
 then
  chmod 0644 ${datapath}/.htaccess
  chown ${rootuser}:${htgroup} ${datapath}/.htaccess
fi
...

**Comment by tflidd** [comment]
duplicate: https://github.com/nextcloud/updater/issues/66

**Comment by nickvergessen** [comment]
Closing as such
