### ISSUE TITLE
NextCloud 21.0.3: No update available

### ISSUE THREAD

**Issue by matthias-mo** [nextcloud/server#28367]
### Steps to reproduce
1. execute `sudo -u www-data php /var/www/nextcloud/updater/updater.phar`

### Expected behaviour
I expect to get version 22.1.0 offered as an update

### Actual behaviour

`sudo -u www-data php /var/www/nextcloud/updater/updater.phar`

Nextcloud Updater - version: v20.0.0beta4-11-g68fa0d4

Current version is 21.0.3.

No update available.

### Server configuration

up to date Debian 10 (buster)

**Nextcloud version:**

21.0.3

**Where did you install Nextcloud from:**

we got our self hosted NextCloud from: https://nextcloud.com/install/#instructions-server

**https://nc.example.com/settings/integrity/failed**

No errors have been found.

`sudo -u www-data php occ app:list`

Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - bruteforcesettings: 2.2.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_external: 1.12.0
  - files_pdfviewer: 2.1.0
  - files_retention: 1.10.1
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - impersonate: 1.8.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0

`sudo -u www-data php occ config:list system`

{
    "system": {
        "updatechecker": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nc.example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nc.example.com",
        "dbtype": "mysql",
        "version": "21.0.3.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "AT",
        "installed": true,
        "mail_smtpmode": "sendmail",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "logtimezone": "UTC",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mysql.utf8mb4": true,
        "updater.release.channel": "stable"
    }
}

**Comment by kinimodmeyer** [comment]
> I expect to get version 22.1.0 offered as an update

with stable 21.0.3 you should get 21.0.4.
i also create some days ago a ticket here: https://github.com/nextcloud/updater_server/issues/634

22.1.0 you will get when the 30% roll out started and you part of the first 30%.

**Comment by acsfer** [comment]
Updates are deployed in chunks, so you'll get it sooner or later.
To "force" the upgrade any time, upgrade manually. https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html

**Comment by Arrappathor** [comment]
Me neither get the security/maintenance-update to NC 21.0.4 since announcement 6 days ago.
Are security-updates really deployed in chunks?

**Comment by LiloBzH** [comment]
same here. No update v21.0.4 or v22.1.0

I m blocked with 21.0.3

**Comment by andyxheli** [comment]
Same here i never seen this before it was always quick once it was release somedays i had to wait 2 days but its been 7 plus now.

**Comment by LiloBzH** [comment]
Are we sure there is no bug hum ?

**Comment by andyxheli** [comment]
@acsfer Are we sure there's no bug or the update is sent out strange that its not out by now

**Comment by acsfer** [comment]
Yep, maybe, sorry...
Follow up here, as this is a `updates_server` issue, not a `server` one ;-)

https://github.com/nextcloud/updater_server/issues/634

**Comment by andyxheli** [comment]
> Yep, maybe, sorry...
> 
> Follow up here, as this is a `updates_server` issue, not a `server` one ;-)
> 
> 
> 
> https://github.com/nextcloud/updater_server/issues/634

Thank you so much! 😊

**Comment by LiloBzH** [comment]
Thank you for information ^^

**Comment by kinimodmeyer** [comment]
issue got resolved, you should get the update now! :+1: 

(https://github.com/nextcloud/updater_server/issues/634#issuecomment-898884739)

**Comment by matthias-mo** [comment]
Hi NextCloud team!

I got the update for 21.0.4 after your fix, but I still don't get any offer for 22.X.X

May I ask you to look into this once more?

**Comment by kinimodmeyer** [comment]
> Hi NextCloud team!
> 
> I got the update for 21.0.4 after your fix, but I still don't get any offer for 22.X.X
> 
> May I ask you to look into this once more?

That´s intended. At the moment you only get on beta channel the 22.* versions.

**Comment by Benouare** [comment]
> > Hi NextCloud team!
> > I got the update for 21.0.4 after your fix, but I still don't get any offer for 22.X.X
> > May I ask you to look into this once more?
> 
> That´s intended. At the moment you only get on beta channel the 22.* versions.

Hi, Thx for the information. Do you know when 22.X will be in the stable?
