### ISSUE TITLE
Class \"OCP\\User\" not found",

### ISSUE THREAD

**Issue by Happyfeet01** [nextcloud/server#28364]
Hello, today i made an Update to Hub 22.1.0  over the Beta Channel. Now i can´t access the Settings. i got an internal Server Error.

upgrade from Hub 21 stable Channel to Hub 22.1.0.0

PHP 8
Debian 10
Apache2 Reverse Proxy

`
{"reqId":"XZ7j4UUGQ4cNCX2SbT9t","level":3,"time":"2021-08-09T20:41:33+02:00","remoteAddr":"79.231.215.147","user":"lars","app":"index","method":"GET","url":"/index.php/settings/user","message":"Class \"OCP\\User\" not found","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0","version":"22.1.0.0","exception":{"Exception":"Exception","Message":"Class \"OCP\\User\" not found","Code":0,"Trace":[{"file":"/home/domain.tld/domains/cloud.domain.tld.de/public_html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/home/domain.tld/domains/cloud.domain.tld.de/public_html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/home/domain.tld/domains/cloud.domain.tld.de/public_html/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/home/domain.tld/domains/cloud.domain.tld.de/public_html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/home/domain.tld/domains/cloud.domain.tld.de/public_html/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"Error","Message":"Class \"OCP\\User\" not found","Code":0,"Trace":[{"file":"/home/domain.tld/domains/cloud.domain.tld.de/public_html/lib/private/legacy/OC_App.php","line":664,"function":"include"},{"file":"/home/domain.tld/domains/cloud.domain.tld.de/public_html/lib/private/Settings/Manager.php","line":257,"function":"getForms","class":"OC_App","type":"::"},{"file":"/home/domain.tld/domains/cloud.domain.tld.de/public_html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":115,"function":"getPersonalSections","class":"OC\\Settings\\Manager","type":"->"},{"file":"/home/domain.tld/domains/cloud.domain.tld.de/public_html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":63,"function":"formatPersonalSections","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->"},{"file":"/home/domain.tld/domains/cloud.domain.tld.de/public_html/apps/settings/lib/Controller/CommonSettingsTrait.php","line":147,"function":"getNavigationParameters","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->"},{"file":"/home/domain.tld/domains/cloud.domain.tld.de/public_html/apps/settings/lib/Controller/PersonalSettingsController.php","line":67,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->"},{"file":"/home/domain.tld/domains/cloud.domain.tld.de/public_html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"index","class":"OCA\\Settings\\Controller\\PersonalSettingsController","type":"->"},{"file":"/home/domain.tld/domains/cloud.domain.tld.de/public_html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/home/domain.tld/domains/cloud.domain.tld.de/public_html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/home/domain.tld/domains/cloud.domain.tld.de/public_html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/home/domain.tld/domains/cloud.domain.tld.de/public_html/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/home/domain.tld/domains/cloud.domain.tld.de/public_html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/home/domain.tld/domains/cloud.domain.tld.de/public_html/apps/ocdownloader/settings/personal.php","Line":14},"CustomMessage":"--"}}
`

**Comment by patschi** [comment]
We had a quick chat. Disabling the app `ocdownloader` solves the error, hence app issue and not directly Nextcloud-related.

**Comment by Happyfeet01** [comment]
I write this again at the ocdownloader repo
