### ISSUE TITLE
Unshare public link after X explicit downloads

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#28376]
> One which we are missing is the possibility to limit the number of downloads for a public link. 

cc @jancborchardt what do you think

# SoW content
The permissions for public links will be extended with an option to
define the number of possible downloads. This option will only exist for
single file shares, not for folders.
The public link page will show a download counter which indicated how
often a file can be downloaded before the link expired.
When the maximum number of downloads is reached the link will be
removed

**Comment by szaimen** [comment]
This might interfer with https://github.com/nextcloud/server/pull/28227 depending on how it gets implemented. Just wanted to mention it.

**Comment by AndyScherzinger** [comment]
Looping in @skjnldsv, see comment above from @szaimen
