### ISSUE TITLE
Display tags next to file names

### ISSUE THREAD

**Issue by Luc45** [nextcloud/server#2838]
I would like to propose a small enchancement to tags:

![chrome_2016-12-23_01-01-02](https://cloud.githubusercontent.com/assets/9341686/21446367/62dab028-c8ac-11e6-9f47-7166e28ba4cb.png)
_Display tags next to file names_

There are times where you don't need to do tag search, you just need to have quick access to them in the folder.

**Comment by MorrisJobke** [comment]
cc @jancborchardt @nickvergessen

**Comment by nickvergessen** [comment]
Will add to the meta topic: https://github.com/nextcloud/server/issues/1465

I like the idea, makes the feature a bit more prominent when it's used.

**Comment by jancborchardt** [comment]
Yeah, when using tags it makes sense. The thing though is that we have to hide them when on mobile because there’s not enough space.

**Comment by skjnldsv** [comment]
I like this idea. Agree with @jancborchardt

**Comment by MorrisJobke** [comment]
Duplicate of #6424
