### ISSUE TITLE
Configure a different mail for notifications

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#28380]
## SoW Description

Right now Nextcloud supports only one E-Mail address per-user. The
users profile page will be extended to allow multiple E-Mail addresses.
If more than one E-Mail address is provided the user can select one
address as the primary E-Mail address. This primary E-Mail address will
be used by Nextcloud as sender and recipient, depending on the actual
E-Mail, for all system generated E-Mails.

### Deadline

15.09.2021

Please align with @schiessle if this needs to be backported to Nc22

**Comment by blizzz** [comment]
Part of https://github.com/nextcloud/server/issues/26866
Spec in https://github.com/nextcloud/server/issues/27465

**Comment by AndyScherzinger** [comment]
Closing in favor of https://github.com/nextcloud/server/issues/28380#issuecomment-896941182

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/issues/27465
