### ISSUE TITLE
Unshare public link from receiver

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/server#28391]
**Feature:**
The sharing permissions for public links will be extended with an option to
allow the receiver to delete the public share but not the data. This is an option primary for 1:1 sharing.
This could be a security option because the link can be deleted after download from the receiver.
This option will exists for a single file but also folders.

I think it could be an option in this menu:

![3](https://user-images.githubusercontent.com/58322182/129152393-477ed617-edb2-4012-810d-5ed78c484eb5.png)
    [Link löschen]  (Delete Share)

**Comment by szaimen** [comment]
Sry but this will not be implemented.
What will be implemented though and is alreaddy nearly done is this:
https://github.com/nextcloud/server/issues/28376
