### ISSUE TITLE
app settings dialog visibility should be increased

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#2839]
## Expected behavior

If an app provides a settings dialog, its visibility should be increased by using a different color or by separating the dialog with a small line etc.

Mookup 1:
![20161223_nc_settings_1_new](https://cloud.githubusercontent.com/assets/2572764/21451884/fb4076d0-c902-11e6-9844-cf10b694ee91.png)
Mookup 2:
![20161223_nc_settings_2_new](https://cloud.githubusercontent.com/assets/2572764/21451887/006a4474-c903-11e6-9d9e-88f696adaa9b.png)

## Current behavior

If an app provides a setting dialog, it is only indicated by a gear symbol and the word 'settings' which make difficult to see for many people. Additionally an opened dialog is not separated clear enough from underlying information which makes it also difficult to see where the dialog exactly begins.

Example 1:
![20161223_nc_settings_1](https://cloud.githubusercontent.com/assets/2572764/21451862/cb4597e4-c902-11e6-8773-fe07f3c019da.png)
Example 2:
![20161223_nc_settings_2](https://cloud.githubusercontent.com/assets/2572764/21451875/dbe9683c-c902-11e6-9b54-dca3da5bbd9e.png)

### Steps to reproduce
1. Open the files, calender or contacts app
2. Check how the settings dialog is displayed.

#### Server Configuration

OS: Linux 3.2.82
Web server: Apache2 2.4.25
Database: MariaDB 5.5.53
PHP version: 5.6.23
Nextcloud version: 10.0.2

#### Client Configuration

Browser: Mozilla Firefox 50.1.0
Operating system: Windows 7

**Comment by MorrisJobke** [comment]
cc @jancborchardt

**Comment by skjnldsv** [comment]
For reference, primary on the button:
![img_20170202_092032](https://cloud.githubusercontent.com/assets/14975046/22541807/fb841976-e928-11e6-908d-481eee244302.jpg)![img_20170202_092059](https://cloud.githubusercontent.com/assets/14975046/22541808/ff296e50-e928-11e6-98e6-b24510e65974.jpg)

**Comment by MorrisJobke** [comment]
I don't like it, because it draws too much attention. Sorry @skjnldsv

**Comment by skjnldsv** [comment]
Don't like it either! :p 
Was for reference in case of someone wanted to try it too ^^

**Comment by skjnldsv** [comment]
If we just put a border top we get a slightly difference, and the blue border automatically gets set on hover/open :)
![capture d ecran_2017-02-03_07-27-49](https://cloud.githubusercontent.com/assets/14975046/22581711/652ffc78-e9e2-11e6-9eab-53a3e28445f0.png)
![capture d ecran_2017-02-03_07-28-00](https://cloud.githubusercontent.com/assets/14975046/22581710/652d6e18-e9e2-11e6-8414-300fee61edb6.png)

**Comment by skjnldsv** [comment]
Can we implement this, this is a simple fix.
Top border is okay for you? @nextcloud/designers

**Comment by eppfel** [comment]
Feels a bit out of place...

**Comment by skjnldsv** [comment]
@eppfel, fair enough. An idea? :)

**Comment by eppfel** [comment]
Nope, the issue is only when it the sidebar is full, maybe there is a way to address that in particular. A shadow would be a fitting, but that's not the Nextcloud style.

**Comment by jancborchardt** [comment]
What's the root cause here? It seems that importing is not really visible, and that is an issue which should be solved by a better empty content view. The first run experience should of course also offer import. :)

**Comment by j-ed** [comment]
@jancborchardt From my point of view the problem is not only connected to the import function but the settings dialog in general. If it is difficult to differentiate between the normal dialog and the settings dialog for normal people, how does disabled people feel if they want to work with this color in color dialogs?

**Comment by jancborchardt** [comment]
@skjnldsv good job on the simple fix with adding the left blue border. :)
