### ISSUE TITLE
[LDAP/AD integration] don`t search users in group with many subgrous

### ISSUE THREAD

**Issue by onixd** [nextcloud/server#28392]
I have group with subgroups in my AD, in settings choose "Only from these groups:" and checked the box "Nested Groups", result is " 0 users found". Am I doing something wrong? I also tried "Edit LDAP Query" with my custom filters, it find`s users but don`t places them in group in "settings - users".

**Comment by onixd** [comment]
Maybe a good idea create new button called "Get list of SubGroups". Because all the subgroups need to add it manually.

**Comment by onixd** [comment]
I found decision for my case. In automatic mode, tab "users" - "Only from these groups:" - need to check the root group and all subgroups, in tab "groups" need to choose only root group. It`s very hard to understood. Need more easy mechanism.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
