### ISSUE TITLE
Creating user fails when also entering group and/or storage quota

### ISSUE THREAD

**Issue by bpgitkr** [nextcloud/server#28401]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Open user list
2. Click new user
3. Enter user details, these **must** include a group and/or storage quota
4. Click Add new user

### Expected behaviour
User should be created, welcome e-mail should be sent and user should be visible in the user list.
(Creating a user **without** entering a group and/or storage quota works as expected.)

### Actual behaviour
No welcome mail is sent, user is not listed in the user list. Upon trying again to create the user, following error occurs: "Der Benutzer ist ungültig, da bereits Dateien von diesem Benutzer existieren" (full trace see below).

### Server configuration

**Operating system/Web server/Database/PHP version:** Official Docker image (https://hub.docker.com/_/nextcloud)

**Nextcloud version:** 22.1.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Older version, last update was from 22.0.0 to 22.1.0

**Where did you install Nextcloud from:** Docker

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Accessibility 1.7.0
Activity 2.15.0
Circles 22.1.0
Comments 1.11.0
Contacts Interaction 1.2.0
Dashboard 7.1.0
Deleted files 1.11.0
File sharing 1.13.2
Log Reader 2.7.0
Monitoring 1.12.0
Notifications 2.10.1
Password policy 1.12.0
PDF viewer 2.3.0
Privacy 1.6.0
Right click 1.1.0
Share by mail 1.11.0
Support 1.5.0
Theming 1.12.0
Update notification 1.11.0
Usage survey 1.10.0
User status 1.1.1
Versions 1.14.0
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***:8080",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***:8080"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "22.1.0.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "default_language": "de_DE",
        "default_locale": "de_DE",
        "defaultapp": "files",
        "overwriteprotocol": "https",
        "simpleSignUpLink.shown": "false",
        "loglevel": 2,
        "maintenance": false
    }
}
</details>

**Are you using external storage, if yes which one:** None

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chrome. happens with every browser

**Operating system:** Windows Server 2019, happens with every OS

#### NextCloud error log
<details>
<summary>NextCloud error log (after 2nd attempt to add the same user)</summary>

{"reqId":"Sl6RAOvzf5posFwEqVYf","level":3,"time":"2021-08-09T12:12:54+00:00","remoteAddr":"172.17.0.1","user":"ncadmin","app":"ocs_api","method":"POST","url":"/ocs/v2.php/cloud/users","message":"Failed addUser attempt with invalid argument exeption.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36","version":"22.1.0.1","exception":{"Exception":"InvalidArgumentException","Message":"Der Benutzer ist ungültig, da bereits Dateien von diesem Benutzer existieren","Code":0,"Trace":[{"file":"/var/www/html/lib/private/User/Manager.php","line":395,"function":"createUserFromBackend","class":"OC\\User\\Manager","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***",{"__class__":"OC\\User\\Database"}]},{"file":"/var/www/html/apps/provisioning_api/lib/Controller/UsersController.php","line":409,"function":"createUser","class":"OC\\User\\Manager","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"addUser","class":"OCA\\Provisioning_API\\Controller\\UsersController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Provisioning_API\\Controller\\UsersController"},"addUser"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Provisioning_API\\Controller\\UsersController"},"addUser"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Provisioning_API\\Controller\\UsersController","addUser",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.provisioning_api.Users.addUser"}]},{"file":"/var/www/html/ocs/v1.php","line":62,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/cloud/users"]},{"file":"/var/www/html/ocs/v2.php","line":23,"args":["/var/www/html/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/User/Manager.php","Line":435,"CustomMessage":"Failed addUser attempt with invalid argument exeption."},"id":"61111bde56842"}
</details>

**Comment by bpgitkr** [comment]
Was able to reproduce the error on an unrelated instance of NextCloud (22.1.0; official Docker image, updated from 22.0.1 and older versions before). Gathered additional error logs from the Logs section in the Admin settings. Both of these errors appear after the initial attempt to add the user. Second attempt to add the user results in the log from the initial issue post.

<details>
<summary>Error log 1</summary>
{"reqId":"0Xv643mLb81SgkvpDKEU","level":3,"time":"2021-08-13T13:32:21+00:00","remoteAddr":"sensitive parameter replaced","user":"ncadmin","app":"PHP","method":"POST","url":"/ocs/v2.php/cloud/users","message":"hash_hkdf(): Input keying material cannot be empty at /var/www/html/lib/private/Security/Crypto.php#93","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36","version":"22.1.0.1","exception":{"Exception":"Error","Message":"hash_hkdf(): Input keying material cannot be empty at /var/www/html/lib/private/Security/Crypto.php#93","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"hash_hkdf(): Input keying material cannot be empty","/var/www/html/lib/private/Security/Crypto.php",93,{"plaintext":"*** sensitive parameter replaced ***","password":""}]},{"file":"/var/www/html/lib/private/Security/Crypto.php","line":93,"function":"hash_hkdf","args":["sha512",""]},{"file":"/var/www/html/lib/private/Security/IdentityProof/Manager.php","line":111,"function":"encrypt","class":"OC\\Security\\Crypto","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/Security/IdentityProof/Manager.php","line":134,"function":"generateKey","class":"OC\\Security\\IdentityProof\\Manager","type":"->","args":["sensitive parameter replaced"]},{"file":"/var/www/html/lib/private/Security/IdentityProof/Manager.php","line":147,"function":"retrieveKey","class":"OC\\Security\\IdentityProof\\Manager","type":"->","args":["sensitive parameter replaced"]},{"file":"/var/www/html/apps/notifications/lib/Push.php","line":199,"function":"getKey","class":"OC\\Security\\IdentityProof\\Manager","type":"->","args":[{"__class__":"OC\\User\\User"}]},{"file":"/var/www/html/apps/notifications/lib/App.php","line":58,"function":"pushToDevice","class":"OCA\\Notifications\\Push","type":"->","args":[5570,{"__class__":"OC\\Notification\\Notification"}]},{"file":"/var/www/html/lib/private/Notification/Manager.php","line":294,"function":"notify","class":"OCA\\Notifications\\App","type":"->","args":[{"__class__":"OC\\Notification\\Notification"}]},{"file":"/var/www/html/apps/activity/lib/NotificationGenerator.php","line":53,"function":"notify","class":"OC\\Notification\\Manager","type":"->","args":[{"__class__":"OC\\Notification\\Notification"}]},{"file":"/var/www/html/apps/activity/lib/Consumer.php","line":72,"function":"sendNotificationForEvent","class":"OCA\\Activity\\NotificationGenerator","type":"->","args":[{"__class__":"OC\\Activity\\Event"},1139159]},{"file":"/var/www/html/lib/private/Activity/Manager.php","line":157,"function":"receive","class":"OCA\\Activity\\Consumer","type":"->","args":[{"__class__":"OC\\Activity\\Event"}]},{"file":"/var/www/html/apps/settings/lib/Listener/UserAddedToGroupActivityListener.php","line":92,"function":"publish","class":"OC\\Activity\\Manager","type":"->","args":[{"__class__":"OC\\Activity\\Event"}]},{"file":"/var/www/html/lib/private/EventDispatcher/ServiceEventListener.php","line":75,"function":"handle","class":"OCA\\Settings\\Listener\\UserAddedToGroupActivityListener","type":"->","args":[{"__class__":"OC\\Activity\\Event"}]},{"file":"/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->","args":[{"__class__":"OCP\\Group\\Events\\UserAddedEvent"},"OCP\\Group\\Events\\UserAddedEvent",{"__class__":"Symfony\\Component\\EventDispatcher\\EventDispatcher"}]},{"file":"/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"},{"__class__":"Closure"}],"OCP\\Group\\Events\\UserAddedEvent",{"__class__":"OCP\\Group\\Events\\UserAddedEvent"}]},{"file":"/var/www/html/lib/private/EventDispatcher/EventDispatcher.php","line":88,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[{"__class__":"OCP\\Group\\Events\\UserAddedEvent"},"OCP\\Group\\Events\\UserAddedEvent"]},{"file":"/var/www/html/lib/private/EventDispatcher/EventDispatcher.php","line":100,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":["OCP\\Group\\Events\\UserAddedEvent",{"__class__":"OCP\\Group\\Events\\UserAddedEvent"}]},{"file":"/var/www/html/lib/private/Server.php","line":484,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":[{"__class__":"OCP\\Group\\Events\\UserAddedEvent"}]},{"function":"OC\\{closure}","class":"OC\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/Hooks/EmitterTrait.php","line":106,"function":"call_user_func_array","args":[{"__class__":"Closure"},["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"/var/www/html/lib/private/Hooks/PublicEmitter.php","line":40,"function":"emit","class":"OC\\Hooks\\BasicEmitter","type":"->","args":["\\OC\\Group","postAddUser",["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"/var/www/html/lib/private/Group/Group.php","line":196,"function":"emit","class":"OC\\Hooks\\PublicEmitter","type":"->","args":["\\OC\\Group","postAddUser",["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"/var/www/html/apps/provisioning_api/lib/Controller/UsersController.php","line":413,"function":"addUser","class":"OC\\Group\\Group","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"addUser","class":"OCA\\Provisioning_API\\Controller\\UsersController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Provisioning_API\\Controller\\UsersController"},"addUser"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Provisioning_API\\Controller\\UsersController"},"addUser"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Provisioning_API\\Controller\\UsersController","addUser",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.provisioning_api.Users.addUser"}]},{"file":"/var/www/html/ocs/v1.php","line":62,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/cloud/users"]},{"file":"/var/www/html/ocs/v2.php","line":23,"args":["/var/www/html/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"611674aa303bd"}
</details>

<details>
<summary>Error log 2</summary>
{"reqId":"0Xv643mLb81SgkvpDKEU","level":3,"time":"2021-08-13T13:32:21+00:00","remoteAddr":"sensitive parameter replaced","user":"ncadmin","app":"no app in context","method":"POST","url":"/ocs/v2.php/cloud/users","message":"substr() expects parameter 1 to be string, bool given","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36","version":"22.1.0.1","exception":{"Exception":"Exception","Message":"substr() expects parameter 1 to be string, bool given","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Provisioning_API\\Controller\\UsersController"},"addUser"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Provisioning_API\\Controller\\UsersController","addUser",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.provisioning_api.Users.addUser"}]},{"file":"/var/www/html/ocs/v1.php","line":62,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/cloud/users"]},{"file":"/var/www/html/ocs/v2.php","line":23,"args":["/var/www/html/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":158,"Previous":{"Exception":"TypeError","Message":"substr() expects parameter 1 to be string, bool given","Code":0,"Trace":[{"file":"/var/www/html/lib/private/Security/Crypto.php","line":94,"function":"substr","args":[false,0,32]},{"file":"/var/www/html/lib/private/Security/IdentityProof/Manager.php","line":111,"function":"encrypt","class":"OC\\Security\\Crypto","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/Security/IdentityProof/Manager.php","line":134,"function":"generateKey","class":"OC\\Security\\IdentityProof\\Manager","type":"->","args":["sensitive parameter replaced"]},{"file":"/var/www/html/lib/private/Security/IdentityProof/Manager.php","line":147,"function":"retrieveKey","class":"OC\\Security\\IdentityProof\\Manager","type":"->","args":["sensitive parameter replaced"]},{"file":"/var/www/html/apps/notifications/lib/Push.php","line":199,"function":"getKey","class":"OC\\Security\\IdentityProof\\Manager","type":"->","args":[{"__class__":"OC\\User\\User"}]},{"file":"/var/www/html/apps/notifications/lib/App.php","line":58,"function":"pushToDevice","class":"OCA\\Notifications\\Push","type":"->","args":[5570,{"__class__":"OC\\Notification\\Notification"}]},{"file":"/var/www/html/lib/private/Notification/Manager.php","line":294,"function":"notify","class":"OCA\\Notifications\\App","type":"->","args":[{"__class__":"OC\\Notification\\Notification"}]},{"file":"/var/www/html/apps/activity/lib/NotificationGenerator.php","line":53,"function":"notify","class":"OC\\Notification\\Manager","type":"->","args":[{"__class__":"OC\\Notification\\Notification"}]},{"file":"/var/www/html/apps/activity/lib/Consumer.php","line":72,"function":"sendNotificationForEvent","class":"OCA\\Activity\\NotificationGenerator","type":"->","args":[{"__class__":"OC\\Activity\\Event"},1139159]},{"file":"/var/www/html/lib/private/Activity/Manager.php","line":157,"function":"receive","class":"OCA\\Activity\\Consumer","type":"->","args":[{"__class__":"OC\\Activity\\Event"}]},{"file":"/var/www/html/apps/settings/lib/Listener/UserAddedToGroupActivityListener.php","line":92,"function":"publish","class":"OC\\Activity\\Manager","type":"->","args":[{"__class__":"OC\\Activity\\Event"}]},{"file":"/var/www/html/lib/private/EventDispatcher/ServiceEventListener.php","line":75,"function":"handle","class":"OCA\\Settings\\Listener\\UserAddedToGroupActivityListener","type":"->","args":[{"__class__":"OC\\Activity\\Event"}]},{"file":"/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->","args":[{"__class__":"OCP\\Group\\Events\\UserAddedEvent"},"OCP\\Group\\Events\\UserAddedEvent",{"__class__":"Symfony\\Component\\EventDispatcher\\EventDispatcher"}]},{"file":"/var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"},{"__class__":"Closure"}],"OCP\\Group\\Events\\UserAddedEvent",{"__class__":"OCP\\Group\\Events\\UserAddedEvent"}]},{"file":"/var/www/html/lib/private/EventDispatcher/EventDispatcher.php","line":88,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[{"__class__":"OCP\\Group\\Events\\UserAddedEvent"},"OCP\\Group\\Events\\UserAddedEvent"]},{"file":"/var/www/html/lib/private/EventDispatcher/EventDispatcher.php","line":100,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":["OCP\\Group\\Events\\UserAddedEvent",{"__class__":"OCP\\Group\\Events\\UserAddedEvent"}]},{"file":"/var/www/html/lib/private/Server.php","line":484,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":[{"__class__":"OCP\\Group\\Events\\UserAddedEvent"}]},{"function":"OC\\{closure}","class":"OC\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/Hooks/EmitterTrait.php","line":106,"function":"call_user_func_array","args":[{"__class__":"Closure"},["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"/var/www/html/lib/private/Hooks/PublicEmitter.php","line":40,"function":"emit","class":"OC\\Hooks\\BasicEmitter","type":"->","args":["\\OC\\Group","postAddUser",["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"/var/www/html/lib/private/Group/Group.php","line":196,"function":"emit","class":"OC\\Hooks\\PublicEmitter","type":"->","args":["\\OC\\Group","postAddUser",["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"/var/www/html/apps/provisioning_api/lib/Controller/UsersController.php","line":413,"function":"addUser","class":"OC\\Group\\Group","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"addUser","class":"OCA\\Provisioning_API\\Controller\\UsersController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Provisioning_API\\Controller\\UsersController"},"addUser"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Provisioning_API\\Controller\\UsersController"},"addUser"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Provisioning_API\\Controller\\UsersController","addUser",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.provisioning_api.Users.addUser"}]},{"file":"/var/www/html/ocs/v1.php","line":62,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/cloud/users"]},{"file":"/var/www/html/ocs/v2.php","line":23,"args":["/var/www/html/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/Security/Crypto.php","Line":94},"CustomMessage":"--"},"id":"611674aa3028f"}
</details>

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
