### ISSUE TITLE
BUG: Some Folders show up as ... in the breadcrumbs path bar

### ISSUE THREAD

**Issue by johnnyq** [nextcloud/server#28406]
To replicate

- Create two folders in files
- Create folder **Test Test**
- Create another Folder **Test test**

![image](https://user-images.githubusercontent.com/1812594/129261610-08de6d30-ed7d-4554-9465-b0bc93db30d5.png)

Click on folder **Test Test**
you will notice on the breadcrumb path bar its says Test Test which is correct

![image](https://user-images.githubusercontent.com/1812594/129261678-bd1af1a1-2c8b-467f-959b-056505f801a4.png)

Now click on **Test test**
you will notice on the breadcrumb bar it shows ... which is incorrect it should show Test test

![image](https://user-images.githubusercontent.com/1812594/129261774-6798983a-c5e8-40ec-a28d-43dc16c8caea.png)

This seems to affect folders that are More than one word and the second word is lowercase

I tried previous versions of Nextcloud it looks like nextcloud regression happened on nextcloud 18 It didn't affect 9 through 17

**Comment by johnnyq** [comment]
It looks like the issue was fixed in the new 22.1.0 Release Fantastic This can be closed now Thank you and Great Work!!

**Comment by CarlSchwan** [comment]
Ok closing :) Thanks for reporting the bug ;)
