### ISSUE TITLE
add 'x' to search box to clear search pattern with one click

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#2840]
## Expected behavior

The search box should allow to clear entered search pattern with one click. This is commonly be done by adding a 'x' to the end of an input field.

## Current behavior

The search box doesn't allow to clear entered search pattern with one click. All search pattern need to be deleted one by one.

Current search box layout:
![20161223_nc_add_x_to_search_box](https://cloud.githubusercontent.com/assets/2572764/21452092/afbf3cb2-c904-11e6-919a-42512ce85040.png)
Search box mockup:
![20161223_nc_add_x_to_search_box_new](https://cloud.githubusercontent.com/assets/2572764/21452095/b681dc12-c904-11e6-92a7-8448ec360087.png)

### Steps to reproduce
1. Open e.g. the files app
2. Enter a search pattern.

#### Server Configuration

OS: Linux 3.2.82
Web server: Apache2 2.4.25
Database: MariaDB 5.5.53
PHP version: 5.6.23
Nextcloud version: 10.0.2

#### Client Configuration

Browser: Mozilla Firefox 50.1.0
Operating system: Windows 7

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by stefan-niedermann** [comment]
One has to pay attention for browsers that do implement a truncate-button self. (i think chrome and safari - maybe edge?)

**Comment by skjnldsv** [comment]
Yep, chrome has it already, just badly themed. I'm checking firefox atm! :)

**Comment by claell** [comment]
For the protocol: Firefox doesn't offer it.

@skjnldsv Does your PR "override" the clear button of Chrome?

**Comment by skjnldsv** [comment]
Yes it does!
