### ISSUE TITLE
Monorepo for npm packages [Meta]

### ISSUE THREAD

**Issue by Pytal** [nextcloud/server#28407]
### Proposal

Move all [@nextcloud](https://www.npmjs.com/search?q=%40nextcloud) npm packages into a single monorepo.

### Considerations

- Automated dependency updates may be handled with Renovate [https://docs.renovatebot.com](https://docs.renovatebot.com/)
    - Allows for grouping updates in a single PR [https://docs.renovatebot.com/configuration-options/#groupname](https://docs.renovatebot.com/configuration-options/#groupname)
    - May be self-hosted [https://docs.renovatebot.com/examples/self-hosting](https://docs.renovatebot.com/examples/self-hosting/)
    - May use the GitHub App hosted by WhiteSource [https://github.com/marketplace/renovate](https://github.com/marketplace/renovate)
- Monorepo support through pnpm/npm/yarn
    - pnpm
        - It's pretty fast [https://pnpm.io/benchmarks](https://pnpm.io/benchmarks)
        - Workspace support [https://pnpm.io/workspaces](https://pnpm.io/workspaces)
        - Example of a pnpm monorepo (with rollup used in some packages) [https://github.com/sveltejs/kit](https://github.com/sveltejs/kit)
    - npm Workspace support [https://docs.npmjs.com/cli/v7/using-npm/workspaces](https://docs.npmjs.com/cli/v7/using-npm/workspaces)
    - yarn Workspace support [https://yarnpkg.com/features/workspaces](https://yarnpkg.com/features/workspaces)
    - lerna monorepo tooling [https://github.com/lerna/lerna](https://github.com/lerna/lerna)

Further additions welcome :)

**Comment by ChristophWurst** [comment]
> all [@nextcloud](https://www.npmjs.com/search?q=%40nextcloud) npm packages

I'm not sure if we want *all* in one repo. Like I'm fine if nc/vue stays in its own repo. The other small helper packages make more sense to be combined.

One thing really important to me with the monorepo approach is to keep packages independent. We must not put ourself into the situation where each and every packages has to be released at the same time, under the same version number. Like, for example if the event bus packages has a breaking change we really don't want to push out a major version of the axios package.

**Comment by Pytal** [comment]
> I'm not sure if we want _all_ in one repo. Like I'm fine if nc/vue stays in its own repo. The other small helper packages make more sense to be combined.

Agreed 💯

> One thing really important to me with the monorepo approach is to keep packages independent. We must not put ourself into the situation where each and every packages has to be released at the same time, under the same version number.

Yes that was my thinking as well, the primary goal is to reap the benefits of standardizing our practices across many packages within a single monorepo :)

**Comment by skjnldsv** [comment]
closing as decided against, but moved into dedicated org :)
