### ISSUE TITLE
Typos in config.sample.php key names

### ISSUE THREAD

**Issue by UlrichBoehm** [nextcloud/server#28428]
Not sure, if I'm wrong, but it looks like there are a few copy and paste typos in your sample config file key names:

- `preview_libreoffice_path`
- `preview_office_cl_parameters`

I think the `preview_` part is wrong in both key names and should be removed (it's the path to libre office, no reason to add `preview` to this name). As the config key which is directly above the `preview_libreoffice_path` key is `preview_max_filesize_image` I assume that it is just a copy and paste typo!?

Of course the _wrong_ written key names are used in the code with the _wrong_ written names, too. Therefore no error message should rise and this is just a minor error.

### Steps to reproduce
1. open config.sample.php
2. look for the config keys written above

### Server configuration

**Nextcloud version:** 21.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 21.0.2

Best regards :)

**Comment by szaimen** [comment]
No, they are both named correctly as they are internally called this way.
