### ISSUE TITLE
[Files] Upload folders

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#2842]
It should be possible to upload whole folders.

Ref: https://github.com/owncloud/core/issues/206

http://html5-demos.appspot.com/static/html5storage/demos/upload_directory/index.html

**Comment by sylvainfaivre** [comment]
FYI, this works with recent Firefox and Chrome releases, duplicate of  #3488

**Comment by enoch85** [comment]
Yes, this works on 11.0.2
