### ISSUE TITLE
NC Upgrade 10.0.2 -> 11.0.0 failed, returns a false PHP version to script installer interface

### ISSUE THREAD

**Issue by tryncatchDE** [nextcloud/server#2843]
### Expected behaviour
The upgrade to 11.0.0 with a Softaculous installation of NC should work, because it provides only a special interface for the normal NC upgrade-script.

### Actual behaviour
Upgrade fails, because the NC upgrade-script returns to the special interface, that the required PHP version is to old (5.4.45) it needs a newer one (> 5.6.0). But PHP version (5.6.29) is used.

**Important:** It uses the original NC upgrade-script and not one from Softaculous

![ncbug](https://cloud.githubusercontent.com/assets/24548044/21453015/7c1d3236-c90b-11e6-8a47-a1ef00c25fc5.jpeg)

### Server configuration
**Operating system**: Debian 7u5

**Web server:** Apache + NGinx Proxy

**Database:** MySQL 5.6.30

**PHP version:** 5.6.29

**Nextcloud version:** 11.0.0

**Updated from an older Nextcloud install:** 10.0.2

**Where did you install Nextcloud from:** Softaculous

**List of activated apps:**
bookmarks (3rdparty), calendar (3rdparty), contacts (3rdparty), documents (3rdparty), ownnote (3rdparty), tasks (3rdparty)

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'MYSECRET',
  'passwordsalt' => 'MYSECRET',
  'secret' => 'MYSECRET',
  'trusted_domains' => 
  array (
    0 => 'example.com',
  ),
  'datadirectory' => '/var/www/vhosts/example.com/private/nextclouddata',
  'overwrite.cli.url' => 'https://example.com/nextcloud',
  'dbtype' => 'mysql',
  'version' => '9.1.2.2',
  'dbname' => 'MYSECRET',
  'dbhost' => 'MYSECRET',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'MYSECRET',
  'dbpassword' => 'MYSECRET',
  'logtimezone' => 'UTC',
  'installed' => true,
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'updater.release.channel' => 'stable',
);
```
</details>

### Client configuration
**Browser:** Firefox 50.1.0

**Operating system:** Ubuntu 16.04LTS

**Comment by rullzer** [comment]
Well it seems Softaculous does not launch the upgrader with php >= 5.6. Not much we can do about that. Please fill an issue with them.
