### ISSUE TITLE
version policy unknown

### ISSUE THREAD

**Issue by tinsel-grumble** [nextcloud/server#28437]
what is version policy of nextcloud? how long is version supported? some os not updating old to new maybe unsupporting old will help keep users secure with update.

**Comment by csware** [comment]
See documentation e.g. <https://docs.nextcloud.com/server/latest/admin_manual/release_schedule.html> and wiki <https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule>

**Comment by dirigit** [comment]
Version policy will be funny for some users running NC in hosted environment (i.e. at IONOS / 1and1):
v20 eol 2021/10

MySQL < v8 unsupported. There is v5.5.x active.
