### ISSUE TITLE
Update to 20.0.11 Bug

### ISSUE THREAD

**Issue by casgito** [nextcloud/server#28432]
Detailed logs 
Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Updated database

Repair step: Drop any incompatible music database entries

Repair step: Remove any playlist files mistakenly added to music_tracks table

Repair step: Combine multi-disk albums and store disk numbers per track

Repair step: Set creation and update dates for the library entities without one

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'UPDATE oc_music_albums SET created = ? WHERE created IS NULL' with params ["2021-08-12 19:18:09"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'created' in 'where clause'

The update was unsuccessful. Please report this issue to the Nextcloud community.

I am not savvy enough to answer all the other points, sorry about that.

**Comment by acsfer** [comment]
This appears to be an issue with https://github.com/owncloud/music report it there please.

**Comment by casgito** [comment]
I never used owncloud, only nextcloud.
