### ISSUE TITLE
Multiselect tags issues

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#28456]
This is a follow-up to https://github.com/nextcloud/server/pull/28133, cc @skjnldsv 

2 things off there:
- [ ] Since "Delete" should always be the last entry in action menus as per our guidelines, "Tags" should move one up in the multiselect menu.
- [ ] After clicking "Tags", clicking anywhere _except_ the "Collaborative tags" input field (or even into that one twice) will close the tags section. This is not expected, instead there could be a little "x" button on the top right since it’s 2 rows anyway.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
