### ISSUE TITLE
Basic operation "free_space" is not implemented

### ISSUE THREAD

**Issue by SpamReceiver** [nextcloud/server#28450]
https://github.com/nextcloud/server/blob/9585c4f2561efd04a85b72b1100bd3593129b00c/lib/private/Files/View.php#L1117

The function ```public function free_space($path = '/')``` calls ```$this->basicOperation('free_space', $path);``` but ``basicOperation`` doesn't implement the operation "free_space" and hence always returns null.

In consequence, no free disk space is calculated and e.g. the trashbin retention will keep files forever.

**Comment by kesselb** [comment]
```
	/**
	 * abstraction layer for basic filesystem functions: wrapper for \OC\Files\Storage\Storage
	 *
	 * This method takes requests for basic filesystem functions (e.g. reading & writing
	 * files), processes hooks and proxies, sanitises paths, and finally passes them on to
	 * \OC\Files\Storage\Storage for delegation to a storage backend for execution
	 */
         private function basicOperation($operation, $path, $hooks = [], $extraParam = null) {
```

At least for local storage free_space is correctly forwarded. I'm closing your report. Feel free to create a proper report using the issue template and include for which storage free_space is not implemented.
