### ISSUE TITLE
Available disk space should be calculated for data partition

### ISSUE THREAD

**Issue by SpamReceiver** [nextcloud/server#28451]
https://github.com/nextcloud/server/blob/6844449465a23279596916720e637316bfedcf0d/apps/files_trashbin/lib/Trashbin.php#L776

When the available disk space is calculated to determine the maximum trashbin size, the available space on the root partition ``'/'`` is calculated. This is not an ideal solution if the Nextcloud data folder is located on a different prtition or file system.

The free space should be calculated for the partition which stores the Nextcloud data folder instead.

**Comment by joshtrichards** [comment]
That parameter is specifying the root of the user's home directory. It's guaranteed to be the data folder.

**Comment by H-Sachse** [comment]
> That parameter is specifying the root of the user's home directory. It's guaranteed to be the data folder.

This assumption may be OK most of the time but it is shortsighted. 
One could easily have a user's files folder mounted from some other storage partition.

**Comment by joshtrichards** [comment]
>  One could easily have a user's files folder mounted from some other storage partition.

Sure, if an individual account's `[account]/files/` is mounted on another partition, `[account]/files_trashbin/` will not  be on that partition.

However, that's not what this Issue / OP's report was about.

Feel free to create the suggestion in a dedicated Issue to make the check more specific to cover more edge cases. Or better yet submit a PR. Possibly something modeled after what's done here would work:

https://github.com/nextcloud/server/blob/6844449465a23279596916720e637316bfedcf0d/apps/files_trashbin/lib/Trashbin.php#L209-L213

**Comment by SpamReceiver** [comment]
I understand folder "/" as the root of the Linux file system where Nextcloud is running.

**Comment by mdik** [comment]
> I understand folder "/" as the root of the Linux file system where Nextcloud is running.

same. this was so confusing. but it also makes sense that "/" in the context of the nextcloud app(s) means the root of *nextcloud_data*. if i were a developer i would appreciate that convention 😅  🤙
