### ISSUE TITLE
User quota bar showing full quota while Unlimited

### ISSUE THREAD

**Issue by eyexin** [nextcloud/server#28465]
### Nextcloud has a problem with the user quota. 
I have set an unlimited user quota, but when the user uses more than 60G capacity, it shows that the storage is about to be full.

### Server configuration

**Operating system:** Ubuntu 20.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 7.4

**Nextcloud version:**  20

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** nextcloud.com

**The problem is like this

![image](https://user-images.githubusercontent.com/23228185/129700607-d711526b-2869-4d52-ae1b-3c289c5dd728.png)

I don’t know why there is such a problem, and I don’t know how to solve it

**Comment by acsfer** [comment]
Can confirm this:

- Set a quota for a user
- Upload files to almos fill the quota
- Change quota to Unlimited

Bar is not updated

**Comment by eyexin** [comment]
Thank you very much!
Maybe it is just the visual issue.Although the quota shown here is almost full, it does not seem to actually affect the use of nextcloud. I will continue use and check it. If there is any problem, I will post it immediately
![image](https://user-images.githubusercontent.com/23228185/131953723-5d418197-5a14-4989-916e-6f9fbb19a96c.png)

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
