### ISSUE TITLE
Allow to send system status mails

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#28475]
## SoW Description

Nextcloud will send out monthly status mails. This mails will contain
information about the currently used storage by the user. The user will
be able to opt-out of this status mails with a option in the personal
settings. Beside the information about the used storage another
section with tips are added to mail, depending on some pre-defined
conditions

### Deadline

15.09.2021

**Comment by CarlSchwan** [comment]
I started implementing this feature as an external app, it is still very much in progress but I hope to have something working tomorrow: https://github.com/CarlSchwan/monthly_notifications :D

**Comment by CarlSchwan** [comment]
Hi @AndyScherzinger.

I just finished implementing the opting out feature and sending mails now also mostly works too and sends the currently used storage and the quota. Could you explain a bit more about the tips part of this task and gives some examples?

**Comment by AndyScherzinger** [comment]
I can't but @schiessle can ❤️

**Comment by skjnldsv** [comment]
@schiessle don't forget this one so we can finish Carl's work on the upcoming weeks :)

**Comment by schiessle** [comment]
Chatted already this morning with Carl about it. He should have all necessary information

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/monthly_status_email
