### ISSUE TITLE
JS spam while uploading a file in the UI

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/server#28480]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. go to files
2. upload a file in the UI
3. check your console log

### Expected behaviour
There shouldn't be messages spamming

### Actual behaviour
 the is one log that is spamming:
```
moment is deprecated: please ship your own, this will be removed in Nextcloud 20 main.js:1:1409380
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
```

### Server configuration

**Nextcloud version:** 20.0.12

**Where did you install Nextcloud from:** docker/k8s

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.1
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 4.0.1
  - contactsinteraction: 1.1.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - groupfolders: 8.2.2
  - impersonate: 1.7.0
  - lookup_server_connector: 1.8.0
  - notes: 4.1.1
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - richdocuments: 3.8.4
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - systemtags: 1.10.0
  - tasks: 0.14.1
  - text: 3.1.0
  - theming: 1.11.0
  - theming_customcss: 1.9.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - user_ldap: 1.10.2
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
```
</details>

**Are you using external storage, if yes which one:** s3

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** FF dev edition 92.0.b4

**Operating system:** Mac OS

#### Browser log
<details>
<summary>Browser log</summary>

```
moment is deprecated: please ship your own, this will be removed in Nextcloud 20 main.js:1:1409380
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
```
</details>

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
