### ISSUE TITLE
override prefers-color-scheme for iFrame via URL value

### ISSUE THREAD

**Issue by jonathanmmm** [nextcloud/server#28487]
Hi,

I try to implement nextclouds calendar via iframe into a website, the website is completely held in white, but as my windows settings are set to dark, the iframed calendar is black, which doesn't match the theme.

I tried with like changing all css for iframes, but it takes much time and discolors other.

I propose an enhancement when making iframe like ?force_color_scheme=light
This would make iFrame much more useful. If this is right now possible or somebody knows how I can tweak via the inbuilt CSS app to make it easily only use the light theme for guest/iFrame, that would be great.

Think it has to to with this pull
nextcloud/server#21366
or this issue
https://github.com/nextcloud/server/issues/12276

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by moqmar** [comment]
I agree that this would be great and is needed - this makes it basically impossible to embed a calendar on a website with a consistent color scheme.

There's a line `<link rel="stylesheet" media="(prefers-color-scheme: dark)" ...>`, basically all that's required is to remove it when `?force_color_scheme=light` is set, and to remove the `media` attribute if `?force_color_scheme=dark` is set. I have no idea though if `prefers-color-scheme` is used in other stylesheets as well.

**Comment by jonathanmmm** [comment]
Trying to create this feature in this pull request https://github.com/nextcloud/server/pull/29940 (right now, still a draft)
