### ISSUE TITLE
Exception: {"Message":"HTTP\/1.1 415 This resource only supports valid vCard or jCard data.

### ISSUE THREAD

**Issue by Geni0815** [nextcloud/server#2848]
The address book works despite the error message.
But where is the error?

### Server configuration
Operating system: Synology DSM 6.0.2-8451 Update 6 
Web server: Apache
Database: 5.5.52-MariaDB 
PHP version: 5.6.28 
Nextcloud version: 10.0.2 (stable)
Contacts version: 1.5.1
Updated from an older Nextcloud 10.0.0
Browser: Firefox 50.1.0
Operating system: Windows 10

### I have in the record
Fatal webdav:

> Exception: {"Message":"HTTP\/1.1 415 This resource only supports valid vCard or jCard data. Parse error: This parser only supports VCARD and VCALENDAR files","Exception":"Sabre\\DAV\\Exception\\UnsupportedMediaType","Code":0,"Trace":"#0 \/volume1\/web\/nextcloud\/3rdparty\/sabre\/dav\/lib\/CardDAV\/Plugin.php(315): Sabre\\CardDAV\\Plugin->validateVCard('BEGIN:VLIST\\r\\nPR...', false)\n#1 [internal function]: Sabre\\CardDAV\\Plugin->beforeCreateFile('addressbooks\/us...', 'BEGIN:VLIST\\r\\nPR...', Object(OCA\\DAV\\CardDAV\\AddressBook), false)\n#2 \/volume1\/web\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/volume1\/web\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1034): Sabre\\Event\\EventEmitter->emit('beforeCreateFil...', Array)\n#4 \/volume1\/web\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(523): Sabre\\DAV\\Server->createFile('addressbooks\/us...', Resource id #896, NULL)\n#5 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/volume1\/web\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#7 \/volume1\/web\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#8 \/volume1\/web\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#9 \/volume1\/web\/nextcloud\/apps\/dav\/lib\/Server.php(184): Sabre\\DAV\\Server->exec()\n#10 \/volume1\/web\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php(30): OCA\\DAV\\Server->exec()\n#11 \/volume1\/web\/nextcloud\/remote.php(165): require_once('\/volume1\/web\/ne...')\n#12 {main}","File":"\/volume1\/web\/nextcloud\/3rdparty\/sabre\/dav\/lib\/CardDAV\/Plugin.php","Line":360,"User":"xxxxx"}

**Comment by go2sh** [comment]
I have the same error message in my logs. I think I comes from the clients connecting. I have quiet I few users a cannot say which... Do you know which clients connect, especially those which use CardDAV or CalDAV?

**Comment by Geni0815** [comment]
The client is Thunderbird 45.6.0 with Lightning 4.7.6

**Comment by go2sh** [comment]
Interesting. It's not a Nextcloud bug... The sogo connector uses a non Standard feature called `VLIST`. 

Refs:
https://github.com/inverse-inc/sogo-connector.tb31/blob/2253f36fb2093db6749127ddd48270f70675ed72/chrome/content/sogo-connector/general/vcards.utils.js
https://sogo.nu/bugs/print_bug_page.php?bug_id=1205
https://help.nextcloud.com/t/fehlermeldung-fatal-webdav/3740

**Comment by Geni0815** [comment]
How can I influence this or how to solve it?

**Comment by go2sh** [comment]
From my point of view. Uninstall sogo connector, use something different. :( Or life with the exceptions.

**Comment by go2sh** [comment]
Maybe this one:
https://addons.mozilla.org/de/thunderbird/addon/cardbook/?src=cb-dl-users

**Comment by MorrisJobke** [comment]
Seems to be a problem with the 3rdparty client. I will close this for now.
