### ISSUE TITLE
PHP error in logfile

### ISSUE THREAD

**Issue by nephilim75** [nextcloud/server#285]
### Steps to reproduce
1. Login to nextcloud to admin area
2. Checking logfile
### Expected behaviour

No error log entry
### Actual behaviour

at every cronjob it is telling:
`Error  PHP     Undefined index: REQUEST_URI at /home/xxxxx/nextcloud/lib/base.php#179  2016-07-01T16:30:02+00:00   --
Error   PHP     Undefined index: REQUEST_METHOD at /home/xxxxx/nextcloud/lib/private/route/router.php#77`
### Server configuration

**Operating system**:
Cent OS

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.6

**Nextcloud version:** (see Nextcloud admin page)
9.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh installation

**Where did you install Nextcloud from:**
nextcloud homepage

**Signing status (Nextcloud 9.0 and above):**

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
`No errors have been found.`

**List of activated apps:**

` 
- Activity 2.2.1
- Antivirus App for files 0.8.0.1
- Auditing / Logging 1.0.0
- Collaborative tags 0.2
- Comments 0.2
- Default encryption module 1.2.0
- Deleted files 0.8.0
- External Sites 1.2
- Federation 0.0.4
- First Run Wizard 1.1
- Gallery 14.5.0
- Mail Template Editor 0.1
- Notifications 0.2.3
- PDF Viewer 0.8.1
- Provisioning API 0.4.1
- Share Files 0.9.1
- Text Editor 2.1
- Update notification 0.1.0
- Versions 1.2.0
- Video player 0.9.8
- Calendar 1.2.2
- Contacts 1.3.1.0
  Nur für bestimmte Gruppen aktivieren
  Experimentelle Apps nachfolgend
- Shorten 0.0.15
  `

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

**The content of config/config.php:**

> <?php
> $CONFIG = array (
>   'instanceid' => 'xyzxyzxyz',
>   'passwordsalt' => 'xyzxyzxyz',
>   'secret' => 'xyzxyzxyz',
>   'trusted_domains' => 
>   array (
>     0 => 'sub.domain.com',
>   ),
>   'datadirectory' => '/home/xxxxx/nextcloud/data',
>   'overwrite.cli.url' => 'https://sub.domain.com',
>   'dbtype' => 'mysql',
>   'version' => '9.0.50.0',
>   'dbname' => 'xxxxx_next',
>   'dbhost' => 'localhost',
>   'dbtableprefix' => 'oc_',
>   'dbuser' => 'xxxxx_next',
>   'dbpassword' => 'hash',
>   'logtimezone' => 'UTC',
>   'installed' => true,
>   'memcache.local' => '\OC\Memcache\APCu',
>   'loglevel' => 3,
>   'mail_from_address' => 'nextcloud',
>   'mail_smtpmode' => 'php',
>   'mail_domain' => 'domain.com',
> );

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)

```

With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT \* FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.

```

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
```

Insert your webserver log here

```

#### Nextcloud log (data/owncloud.log)
```

Insert your Nextcloud log here

```

#### Browser log
```

Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...

```
```

**Comment by MorrisJobke** [comment]
> at every cronjob it is telling:
> Error PHP Undefined index: REQUEST_URI at /home/xxxxx/nextcloud/lib/base.php#179 2016-07-01T16:30:02+00:00 -- Error PHP Undefined index: REQUEST_METHOD at /home/xxxxx/nextcloud/lib/private/route/router.php#77

Usually this is a PHP variable: http://php.net/manual/en/reserved.variables.server.php

@LukasReschke Have you ever seen any issues with this variable being not set during cron job execution?

**Comment by nephilim75** [comment]
Hej guys,

any news on this?

Kind regards
//neph

**Comment by MorrisJobke** [comment]
> any news on this?

I thought this was fixed. But sadly I can't find the change anymore. @nephilim75 Does this also happen with a current version of Nextcloud? (9.0.53 or 10.0.0)

**Comment by nephilim75** [comment]
Yes, it actually does. I am currently running NC10 on a shared host.

Kind regards
//neph
-- 
Von unterwegs...

Am 9. September 2016 09:34:10 MESZ, schrieb Morris Jobke <notifications@github.com>:
>> any news on this?
>
>I thought this was fixed. But sadly I can't find the change anymore.
>@nephilim75 Does this also happen with a current version of Nextcloud?
>(9.0.53 or 10.0.0)

**Comment by nickvergessen** [comment]
Which apache and php versions are you using?

**Comment by nephilim75** [comment]
PHP-Version: 5.6.25
Just Apache.

**Comment by nickvergessen** [comment]
Run `apache2 -v`

Should print out something like:
```
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2016-07-14T12:32:26
```

**Comment by nephilim75** [comment]
Apache 2.4.23

**Comment by MorrisJobke** [comment]
We haven't seen this at any other user. We have multiple instance that run on CentOS and usually this environment variable is provided by PHP: http://php.net/manual/en/reserved.variables.server.php

Could you check you installed the PHP provided by your distribution and not from a 3rd party repository or a self compiled version.

I will close this and am happy to reopen if there are more details about this :)

Thanks

**Comment by creopard** [comment]
These kind of error messages in the log appear after(!) switching from an AJAX cron job to a "real" cron job executing every 15 minutes!

> Error	PHP	Undefined index: REQUEST_URI at /lib/base.php#177	2017-04-20T**10:00:02**+0200
Error	PHP	Undefined index: REQUEST_METHOD at /lib/private/Route/Router.php#79	2017-04-20T**10:00:01**+0200
Error	PHP	Undefined index: SCRIPT_NAME at /lib/private/AppFramework/Http/Request.php#713	2017-04-20T**10:00:01**+0200
Error	PHP	Undefined index: REQUEST_URI at /lib/base.php#177	2017-04-20T**09:45:03**+0200
Error	PHP	Undefined index: REQUEST_METHOD at /lib/private/Route/Router.php#79	2017-04-20T**09:45:03**+0200
Error	PHP	Undefined index: SCRIPT_NAME at /lib/private/AppFramework/Http/Request.php#713 2017-04-20T**09:45:03**+0200

**Comment by daN4cat** [comment]
Same error here with CentOS 6.9, Apache 2.4.25 and real cron job every 15 min.

> Error	PHP	Undefined index: REQUEST_URI at /home/XXXXXXXXX/public_html/nextcloud/lib/base.php#177	2017-05-07T09:15:02+0100
> Error	PHP	Undefined index: REQUEST_METHOD at /home/XXXXXXXXX/public_html/nextcloud/lib/private/Route/Router.php#79	2017-05-07T09:15:02+0100
> Error	PHP	Undefined index: SCRIPT_NAME at /home/XXXXXXXXX/public_html/nextcloud/lib/private/AppFramework/Http/Request.php#713

Please note that mod_env is enabled.

This problem should be investigated and not close IMHO.

**Comment by daN4cat** [comment]
Also, not sure if correlated but I cannot run any occ files:scan as complaining that I'm not surring from CLI when I'm clearly doing from an ssh connection!

**Comment by daN4cat** [comment]
Just checked with phpinfo and I can see:

> _SERVER["SCRIPT_NAME"]	/phpinfo.php
> _SERVER["REQUEST_URI"]	/phpinfo.php
> _SERVER["QUERY_STRING"]	no value
> _SERVER["REQUEST_METHOD"]	GET
> _SERVER["SERVER_PROTOCOL"]	HTTP/1.1
> _SERVER["GATEWAY_INTERFACE"]	CGI/1.1
> _SERVER["REMOTE_PORT"]	42148
> _SERVER["SCRIPT_FILENAME"]	/home/XXXXXXXXX/public_html/nextcloud/phpinfo.php

So $_SERVER var are there, I don't understand what's wrong with nextcloud then...

**Comment by daN4cat** [comment]
Checked base.php at line 177 and the issue comes from the if statement with again OC::$CLI, same issue I face when running occ files:scan.
I assume that running from real cron should point to CLI and not a web call and that's why the error above.

What's wrong with this OC::$CLI detection on CentOS?

**Comment by daN4cat** [comment]
OK, I've got to the bottom of this issue, so I believe.

**On CentOS people should not use php in cron or even when invoking occ command but php-cli!**

The first comment from here helped me to get to the bottom of it: http://php.net/manual/en/function.php-sapi-name.php

**Comment by nickvergessen** [comment]
We fixed the logs with https://github.com/nextcloud/server/pull/4873 for NC 12.
However basically that just means we are hidding the problem even more.

**Comment by daN4cat** [comment]
@nickvergessen the solution is to write in the wiki that CentOS users should use php-cli and not simple php.
Hiding the error message will not make people find this issue report anymore IMHO.

**Comment by nickvergessen** [comment]
https://docs.nextcloud.com/server/12/admin_manual/configuration_server/background_jobs_configuration.html#cron

See second blue box:
> On some systems it might be required to call php-cli instead of php.

**Comment by creopard** [comment]
Thank you:
`php-cli -f /home/nextcloud/cron.php`
did the trick!
