### ISSUE TITLE
Shared from information inconsistent 

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#2852]
Following scenario:

1. user1 shares folder1 with user2
2. user2 shares a file from folder1 with user3

Result:

In the file listing user3 sees that the file is shared by user1 (the owner)
Activity shows: "user2 shared `file` with you"  (the initiator)

This looks inconsistent. Not sure what's the right way to do it... Something to discuss.
Initially I think the file listing should also show "user2" because on a large instance the recipient might not know the owner of the file at all so showing the initiator of the share seems to make more sense.

Opinions? @rullzer

**Comment by MorrisJobke** [comment]
This is how it looks on master as if now and is more consistent (left to right: user 1-3):

![bildschirmfoto 2017-08-16 um 11 38 13](https://user-images.githubusercontent.com/245432/29357382-9bf475a8-8277-11e7-97ad-5209587ce825.png)
![bildschirmfoto 2017-08-16 um 11 38 56](https://user-images.githubusercontent.com/245432/29357384-9c17325a-8277-11e7-8e0d-79758a45a127.png)

That means it is resolved.
