### ISSUE TITLE
Therming does not work after update from Nextcloud 21.0.3 to 21.0.4

### ISSUE THREAD

**Issue by hnagasawa** [nextcloud/server#28527]
I update nextcloud from 21.0.3 to 21.0.4 using nextcloud updater.
Nextcloud update sccess. But Therming did not work. 
Therming logo and  color etc reset default.
I uploaded logo image and changed color.But Preview did not display ?
Terming Version,1.12.0

**Comment by jacotec** [comment]
Same issue here!
The log is full of this shows the error:

`ScssPhp\ScssPhp\Exception\CompilerException: Undefined variable $theming-cachebuster: apps/theming/css/theming.scss on line 96, at column 2 Call Stack: #0 import apps/theming/css/theming.scss (unknown file) on line 1`

A hotfix would be highly appreciated.

**Comment by acsfer** [comment]
Duplicate of https://github.com/nextcloud/server/issues/28515
