### ISSUE TITLE
NC22.1: Strange file search results

### ISSUE THREAD

**Issue by andreas-p** [nextcloud/server#28529]
While typing in the search box, the result shown is irritating to me:
  - "15" -> two files
  - "152" -> three files
  - "1521" -> five files and indicator "More results"

This is unexpected/unpredictable behaviour to me: I can't explain the 2 and 3 char search results, they are not even in the current folder.

**Comment by PVince81** [comment]
@andreas-p do you mind posting the results in question ? Please note that the search is searching in all the folders, not only the current one.

Also, are the results regular files/folders or received shares ?

**Comment by andreas-p** [comment]
@PVince81 I know it's searching everywhere (complaining about that in other issues). I can't  post the specific filenames for privacy reasons.

All results are received shares (in general, all users use received shares only, shared by a "superuser" who owns 2.9M files).
As of today, search results are a little different. This changed from the result posted initially. There was no change to the system in the meantime.

- "15" -> one file
- "152" -> three files, one directory
- "1521" -> four files, one directory, "More results"

Doing a full browser refresh, I get the same results (as far as I can see from the cropped result, at the moment... )

**Comment by szaimen** [comment]
Can you still reproduce this with NC22.1.1? I think there were some bugfixes regarding search in this version...

**Comment by andreas-p** [comment]
Seems fixed in 22.1.1, 5+ results right from the start now as expected.

**Comment by PVince81** [comment]
great to hear! closing then
