### ISSUE TITLE
Link share and "Always ask for a password" does not ask for the password.

### ISSUE THREAD

**Issue by jsalatiel** [nextcloud/server#28543]
Enable "Always ask for a password" for sharing is not working. If I enable it and try to share as a link, no pop up will ask for a password. Some random password will be created and not shown.

https://user-images.githubusercontent.com/5522389/130261303-4f1fb201-2139-4552-8a45-951b659bf869.mp4

### Expected behaviour
A popup should ask for some password for the share.

### Actual behaviour
The share link is created with some random password ( which password btw? )  and the user is unaware that a password was even set.

### Server configuration
nextcloud:21.0.2-apache container.

**Comment by szaimen** [comment]
Its not asking you before it automatically sets a random passwordd when you click the share button. What you probably would want is this: https://github.com/nextcloud/server/issues/13229
