### ISSUE TITLE
Duplicate cron.php While Server Is Disconnected 

### ISSUE THREAD

**Issue by wonderfulShrineMaidenOfParadise** [nextcloud/server#28558]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Set ``crond`` to run ``cron.php``.
2. Disconnect the server from Internet.
3. `ps -ax|grep cron.php`. There are a lot of duplicated entries.
4. Everything on Nextcloud is dead due to 504 Gateway timeout.

### Expected behaviour
Tell us what should happen
Maybe ``cron.php`` could exit if there is no Internet connections

### Actual behaviour
 `ps -ax|grep cron.php`. There are a lot of duplicated entries.
Everything on Nextcloud is dead due to 504 Gateway timeout.

### Server configuration

**Operating system:**
postmarketOS v21.06 / Alpine 3.14
**Web server:**
nginx/1.20.1
**Database:**
Mariadb 10.5.12
**PHP version:**
7.4.22
**Nextcloud version:** (see Nextcloud admin page)
22.1.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
Nextcloud official .tar.bz2 archive
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.15.0
  - audioplayer: 3.2.1
  - bookmarks: 4.4.0
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.2
  - checksum: 1.1.2
  - circles: 22.1.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 4.0.1
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.18.0
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.9.0
  - news: 16.0.1
  - nextcloud_announcements: 1.11.0
  - notes: 4.1.1
  - notifications: 2.10.1
  - oauth2: 1.9.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.11.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.3.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.11.0
  - tasks: 0.14.1
  - text: 3.3.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.1
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.6.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - files_external
  - files_sharing
  - files_trashbin
  - passman
  - sharebymail
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.1.0.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "default_language": "ja_JP",
        "default_local": "ja_JP",
        "default_phone_region": "+81",
        "maintenance": false,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox 78.13.0esr (64 bit)
**Operating system:**
Debian 10.10
#### Web server error log
<details>
<summary>Web server error log</summary>

[log.txt](https://github.com/nextcloud/server/files/7027647/log.txt)

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/a8547cc0eadb4e92e1730b98424a413f22f76b50/config/config.sample.php#L749-L754

**Comment by wonderfulShrineMaidenOfParadise** [comment]
@kesselb My situation is that I have gotten a blackout, router failure, ISP server crashing or something else causing disconnection from Internet, after that I get back to the server and try to restore my services. It's not so nice to reboot a server, which is the only solution for me at the meantime.
