### ISSUE TITLE
Apps Filtering

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#28569]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Requirements

- Make it possible for providers to only show selected apps in the apps management
- Make it possible for Nextcloud to only show selected apps for Enterprise users
- Low development effort
- No maintenance of multiple app stores
- No additional work for app developers

### Approach

If the Nextcloud is an Enterprise instance then it should check for a local file that defines the list of allowed apps. If no local file exists then a file from apps.nextcloud.com should be used for the list of allowed Enterprise apps. The subscription key should be transferred to make authentication possible in the future and maybe return a custom list.

### Dummy code

```
if (EnterpriseVersion) {
  if (file_exist(‘config/apps.json’)) {
    //read ‘config/json’ into array $allow_apps;
  } elseif (file_exists(‘https://apps.nextcloud.com/enterpriseapps.json?key=$subscriptionkey'))
    // read ‘https://apps.nextcloud.com/enterpriseapps.json?key=$subscriptionkey' into array $allow_apps;
}

$appstore_apps = readfromappstore();

if exists($allow_apps;) {
  $appstore_apps = array_intersect ($appstore_apps, $allow_apps)
}
```

**Comment by sunjam** [comment]
Have you tried using [AppOrder](https://apps.nextcloud.com/apps/apporder) to change what is shown in the app menu?

You could also restrict apps to specific app groups such as "Enterprise Users"

Hope this helps in some way.  Cheers!
