### ISSUE TITLE
(Feature request to counter a sync client bug and to fix a pain): Show hidden files in web UI

### ISSUE THREAD

**Issue by noseshimself** [nextcloud/server#28567]
### Steps to reproduce
1) Use a client to sync files and interrupt it
1a) Use a broken version of the client that is crashing on its own
2) The client will leave .[name].xyzzy files on the server which are invisible to the web UI

(3) even worse: A client with a set up permitting synchronization of hidden files is pulling them down while you are deleting them on another client and syncing that. The files turn into rabbits and multiply like crazy).

I found out after missing about 800GB of disk space...

Addendum: Even better way:

Create some files on a Linux system with names using different mixes of upper and lower case files. Sync them. (Try finding them on the Web UI...) Sync them to a WIndows system. Syncing will fail AND there will be files starting with dots multiplying like lice on rabbits...

### Expected behaviour
The user should be able to see these files and remove them. There should be a way to find and remove them using occ.

### Actual behaviour
There is no way to get rid of the files easily. The user has to configure a sync client in a way to sync hidden files starting with a ".", too and delete these files locally (sometimes several times because other sync clients might restore (or even create copies of) them) hoping that the deletion will be replicated to the server

## Server configuration detail

**Operating system:** Linux 4.19.0-17-amd64 #1 SMP Debian 4.19.194-3 (2021-07-18) x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 10.3.29

**PHP version:** 

7.3.29-1~deb10u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, ldap, exif, msgpack, mysqli, pdo_mysql, pdo_sqlite, apc, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, memcached, libsmbclient, Zend OPcache

**Nextcloud version:** 21.0.3 - 21.0.3.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated (does not matter)

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.7.0
 - activity: 2.14.3
 - admin_audit: 1.11.0
 - afterlogic: 2.0.1
 - apporder: 0.13.0
 - audioplayer: 3.2.1
 - audioplayer_editor: 0.3.0
 - bbb: 2.0.0
 - bookmarks: 4.4.1
 - breezedark: 21.0.10
 - bruteforcesettings: 2.2.0
 - calendar: 2.3.2
 - camerarawpreviews: 0.7.12
 - checksum: 1.1.2
 - circles: 0.21.4
 - cloud_federation_api: 1.4.0
 - cms_pico: 1.0.15
 - collectives: 0.12.21
 - comments: 1.11.0
 - contacts: 4.0.1
 - contactsinteraction: 1.2.0
 - cospend: 1.3.7
 - customproperties: 2.0.4
 - dashboard: 7.1.0
 - dav: 1.17.1
 - deck: 1.4.3
 - drawio: 1.0.1
 - duplicatefinder: 0.0.11
 - event_update_notification: 1.3.0
 - external: 3.8.2
 - extract: 1.3.2
 - federatedfilesharing: 1.11.0
 - federation: 1.11.0
 - files: 1.16.0
 - files_accesscontrol: 1.11.0
 - files_antivirus: 3.2.1
 - files_bpm: 0.2.1
 - files_external: 1.12.0
 - files_fulltextsearch: 21.0.4
 - files_linkeditor: 1.1.6
 - files_markdown: 2.3.4
 - files_mindmap: 0.0.25
 - files_pdfviewer: 2.1.0
 - files_rightclick: 1.0.0
 - files_sharing: 1.13.1
 - files_snapshots: 1.0.2
 - files_texteditor: 2.14.0
 - files_trackdownloads: 1.10.0
 - files_trashbin: 1.11.0
 - files_versions: 1.14.0
 - files_versions_s3: 0.1.6
 - files_videoplayer: 1.10.0
 - firstrunwizard: 2.10.0
 - forms: 2.3.0
 - fulltextsearch: 21.0.3
 - fulltextsearch_elasticsearch: 21.0.2
 - group_default_quota: 0.1.2
 - group_everyone: 0.1.8
 - groupfolders: 9.0.2
 - groupquota: 0.1.6
 - guests: 2.0.1
 - hsts: 0.8.0
 - imageconverter: 1.3.1
 - impersonate: 1.8.0
 - integration_discourse: 1.0.0
 - integration_dropbox: 1.0.1
 - integration_github: 1.0.0
 - integration_gitlab: 1.0.0
 - integration_jira: 1.0.0
 - integration_mastodon: 1.0.0
 - integration_moodle: 1.0.0
 - integration_openproject: 1.0.4
 - integration_reddit: 0.0.11
 - integration_twitter: 1.0.0
 - integration_whiteboard: 0.0.14
 - issuetemplate: 0.7.0
 - jitsi: 0.11.0
 - jsloader: 1.5.0
 - keeweb: 0.6.6
 - login_notes: 0.4.0
 - logreader: 2.6.0
 - lookup_server_connector: 1.9.0
 - mail: 1.10.3
 - metadata: 0.14.0
 - music: 1.2.1
 - nextcloud_announcements: 1.10.0
 - notes: 4.1.1
 - notifications: 2.9.0
 - notify_push: 0.2.2
 - oauth2: 1.9.0
 - occweb: 0.0.7
 - passman: 2.3.7
 - password_policy: 1.11.0
 - permissions_overwrite: 0.1.5
 - phonetrack: 0.6.9
 - photos: 1.3.0
 - polls: 3.0.0
 - privacy: 1.5.0
 - provisioning_api: 1.11.0
 - qownnotesapi: 21.7.0
 - quickaccesssorting: 1.1.2
 - quota_warning: 1.11.0
 - radio: 1.0.2
 - rainloop: 7.1.2
 - recommendations: 1.0.0
 - richdocuments: 4.2.1
 - richdocumentscode: 6.4.1004
 - riotchat: 0.9.1
 - serverinfo: 1.11.0
 - settings: 1.3.0
 - sharebymail: 1.11.0
 - sharelisting: 1.0.0
 - sharingpath: 0.3.0
 - side_menu: 1.27.2
 - spreed: 11.3.1
 - support: 1.4.0
 - survey_client: 1.9.0
 - systemtags: 1.11.0
 - talk_matterbridge: 1.22.4
 - tasks: 0.14.1
 - terms_of_service: 1.7.1
 - text: 3.2.0
 - theming: 1.12.0
 - theming_customcss: 1.9.0
 - timemanager: 0.2.4
 - timetracker: 0.0.69
 - twofactor_backupcodes: 1.10.0
 - twofactor_nextcloud_notification: 3.2.1
 - twofactor_totp: 6.1.0
 - twofactor_u2f: 6.2.0
 - twofactor_webauthn: 0.2.10
 - updatenotification: 1.11.0
 - user_status: 1.1.1
 - video_converter: 1.0.2
 - viewer: 1.5.0
 - weather: 1.7.5
 - weather_status: 1.1.0
 - welcome: 0.0.5
 - workflowengine: 2.3.0
Disabled:
 - announcementcenter
 - encryption
 - ransomware_protection
 - sharepermissions
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.gerstel.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "21.0.3.1",
    "overwrite.cli.url": "https:\/\/nextcloud.gerstel.com",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "share_folder": "\/Shared",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "twofactor_enforced": "false",
    "twofactor_enforced_groups": [],
    "twofactor_enforced_excluded_groups": [
        "admin"
    ],
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpport": "587",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "app_install_overwrite": [
        "radio",
        "occweb",
        "issuetemplate"
    ],
    "knowledgebaseenabled": true,
    "remember_login_cookie_lifetime": 2419200,
    "session_lifetime": 86400,
    "session_keepalive": true,
    "auto_logout": false,
    "proxy": "proxy.mh.gerstel.com:3128",
    "allow_local_remote_servers": true,
    "log_type": "file",
    "logfilemode": 416,
    "loglevel": 1,
    "syslog_tag": "nextcloud.gerstel.com",
    "logdateformat": "F d, Y H:i:s",
    "logtimezone": "UTC",
    "log_query": false,
    "log_rotate_size": 104857600
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by szaimen** [comment]
Pleas simply fix the broken desktop client since that is the underlying issue here and nothing we can fix.
