### ISSUE TITLE
CardDAV doesn't set correct Read / Write Permissions on Notes Field

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/server#28575]
### Steps to reproduce
1. Add NC Contacts to MacOS / iOS
2. Add a different CardDAV provider 
3. Compare Notes Field - when the Contacts are shared read only, they display differently for NC from other implementations

### Expected behaviour
Notes Field should be visible and readable

### Actual behaviour
Notes field is hidden and only displays it's contents when adding a client only note on MacOS / iOS

This could also be down to the import breaking fields: https://github.com/nextcloud/contacts/issues/2445

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by miaulalala** [comment]
Closed as not reproducible ATM.
