### ISSUE TITLE
Theme background not appearing or overwritten in dashboard app

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#28572]
### Steps

1. Setup NC 21.0.4
2. In the theming app, set the background to a yellow color
3. Go to the files app and see that the background color is applied
4. Go to the dashboard app and force refresh the page

### Expected result
Yellow background.

### Actual result
For one second during loading, I see the yellow background and when the page finished loading it's back to blue.
Maybe some additional CSS gets loaded by the dashboard app which overwrites the theme again.

### Version
NC 21.0.4

**Comment by skjnldsv** [comment]
Fixed in 25
