### ISSUE TITLE
download url latest

### ISSUE THREAD

**Issue by mfeske** [nextcloud/server#28579]
Hello, everyone,

might it be possible to standardize the download url? So that, for example, the last stable version is always available at https://download.nextcloud.com/server/releases/nextcloud-latest-stable.zip? that would greatly simplify automated installations.

**Comment by LukasReschke** [comment]
https://download.nextcloud.com/server/releases/latest.zip should already do this to my knowledge.

See https://download.nextcloud.com/server/releases/
