### ISSUE TITLE
relative imports may lead to segfault in php-fpm

### ISSUE THREAD

**Issue by sh-dvl** [nextcloud/server#28588]
PROBLEM:

we've had problems with updating/installing nextcloud: any browser-request to apps/files/ leads to "Bad Gateway" in nginx due to SegFault in php-fpm.

REASON:
after many tries to trace the problem we've found the reason:

due to local requirements we've moved the apps-folder out of the nextcloud-tree and only use a symlink within the nextcloud-tree to the apps-folder

unfortunatley apps/files/css/merged.scss tries to import '../../../core/css/whatsnew.scss', which originally is at 'core/css/whatsnew.scss' directly below nextcloud-tree.

with the moved/linked apps-folder this leads to an exception somewhere in the nextcloud-php-code.

after this php-fpm loops with calling zend_call_function(), which calls zend_execute_ex() which leads to a call to zend_call_function() and so on

the stack will be flooded with this recursion and many calls later php-fpm segfaults...

SOLUTION:
well we can't say, if this is a problem of php-fpm or the php-code of nextcloud, and even nextcloud does not have to support such moving/linking of containing folders, it should never lead into a segfault, but maximal to an error.

within the trace we see, that php-fpm tries to open the import-file as well by prepending the current folder of import (apps/files/), as prepending the main-css-folder 'core/css/'.

so changing the import from '../../../core/css/whatsnew.scss' to 'whatsnew.scss' should fix this exception and so fix the segfault.

(we can test it with next update, because this import seems only be done the first time after update/install)

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by sh-dvl** [comment]
well, neither this was a question (but a bug-solution), nor we need assistance for setup.

if you think, that's okay, that nextcloud may lead to segfaults, well, than it is as is it is.
