### ISSUE TITLE
Feature request: Duplicate upload notification for all directories

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/server#2858]
I'd like a way to have the server flag a duplicate uploaded file against any folder on the server, maybe through a DB query or directory scan.

Scenario:

I've uploaded several folders of photos, then organised them into Occasion > Year > Month directories.
Forgetting to delete the folders I'd uploaded, I later plan on re-uploading them, but with everything organised into subfolders, they'll all re-uploaded brand new at the top-most level.

That's not ideal when uploading several gigs, but it's also a nice-to-have generally so I don't end up duplicating files already uploaded for no good reason.

It's very much a nice to have rather than a deal breaker, but if it's an option that could be implemented without much hassle (it already exists within the current directory) and I could enable it through a setting that would be wonderful!

**Comment by MorrisJobke** [comment]
It's nearly impossible to do this properly in a performant way. First we need to have checksums to find easily such files.

I guess this is for a very long time out of scope here.

Sorry to say so: but even filesystems have a hard time to properly do de-duplication.

Feel free to comment here if you thing it is nonetheless the way we really should go, but I will close this for now.

cc @karlitschek
