### ISSUE TITLE
Tables aren’t re-created when re-adding the Contacts app

### ISSUE THREAD

**Issue by silverhook** [nextcloud/server#2859]
### Steps to reproduce
1. disable Contacts app
2. `rm -r apps/contacts`
3. drop addressbooks and addressbookchanges tables
4. re-enable Contacts app
5. upload a vCard. (optional)

### Expected behaviour
According to @enoch85, this should (re-)create the `oc_addressbooks` and `oc_addressbookchanges` tables and therefore the Contacts app should just work (with the fresh new tables).

### Actual behaviour
The tables are not (re-)created and therefore the Contacts app doesn’t work.

### Server configuration
**Operating system**:
Debian Jessie GNU/Linux

**Web server:**
Nginx 1.6.2-5+deb8u4

**Database:**
PostgreSQL 9.4+165+deb8u1

**PHP version:**
PHP-fpm 5.6.29+dfsg-0+deb8u1

**Nextcloud version:** (see Nextcloud admin page)
11.0

**Contacts version:** (see Nextcloud apps page)
1.5.2

**Updated from an older Nextcloud or fresh install:**
fresh install

**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_markdown: 1.0.0
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - news: 10.1.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.1.2
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oceto1l6yq0i",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "explorethe7seas.wheremymonkeyis.at"
        ],
        "datadirectory": "\/srv\/nextcloud_data",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "pgsql",
        "version": "11.0.0.10",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "updater.release.channel": "stable"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
no(t yet)

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:**
no

### Client configuration
**Browser:**
Firefox 45.6.0

**Operating system:**
Mageia 5 GNU/Linux

**CardDAV-clients:**
- SailfishOS Calendar
- Akonadi (currently not connected)

### Logs
(seems irrelevant for now)

---

This got moved from https://github.com/nextcloud/contacts/issues/71

**Comment by enoch85** [comment]
Yeah, imo it should, not tested though. Thanks for the report @silverhook!

**Comment by ChristophWurst** [comment]
Hi @silverhook,

why did you "uninstall" the app that way? Where did you find those instructions?

This is *not* how to uninstall an app. I assume settings in the `appconfig` table persist, which maybe should be removed too.
Nevertheless, this should be reported in the contacts app's issue tracker at https://github.com/nextcloud/contacts/issues

**Comment by silverhook** [comment]
Hi, @ChristophWurst ,

I am aware that this is not the official way to disable or uninstall an app. The reason why I **purged** it that way is that I messed up my contact list and on the #nextcloud IRC channel I was told that would likely be ~~a good way~~ the best way that they could think of.

In any case there is nothing in need of rescuing, as that was just a testing instance and I already reinstalled from scratch.

I was actuaaly sent from the nextcloud/contacts#71 here, as the tables are actually made by the core code, not the contacts app code. In any case, one would assume that if a table is missing for whatever reason, that it would be created anew, so I still consider it a bug. Whether this is up to nextcloud/server or nextcloud/contacts, I don’t know.

**Comment by nickvergessen** [comment]
Well the tables are not part of the contacts app, but the dav app (default server app).
So of course they are not recreated when you remove the contacts app.

To fix this what you can do is run the following query, afterwards a normal update should happen and readd the tables:
```sql
UPDATE `oc_appconfig` SET `configvalue` = '1.1.0' WHERE `configkey` = 'installed_version' AND `appid` = 'dav'
```

**Comment by nickvergessen** [comment]
Btw who suggested this way of "reseting the contacts app"?

**Comment by silverhook** [comment]
Sooo, “not a bug”?

I believe @enoch85 suggested it on IRC, but I reserve the possibility that I remember wrongly. It was quite a lively debate going on on the channel at that time.

**Comment by nickvergessen** [comment]
Well of course wrong manual manipulation is "not a bug".
As as said above if you would have manipulated it correctly it even would have worked.

**Comment by enoch85** [comment]
Nope wasn't me :innocent:

**Comment by silverhook** [comment]
> Nope wasn't me :innocent:

My apologies.

**Comment by JanUrlaub** [comment]
After delete the app, you need to remove also the entries from oc_migrations.
That helped on my issue with maps, which seems the same root problem.
(this is maybe a mor general way, to resolve this kind of errors)
