### ISSUE TITLE
Talk app cant be seen in the upper menu after upgrade to 22.1.1

### ISSUE THREAD

**Issue by taavit21** [nextcloud/server#28612]
Behaviour:

I had Talk app disabled in version 22.1.0 because i was getting errors from searching.
I have  now upgraded to version 22.1.1 and when i enable app Talk it simply dosent show up in the upper menu.

![image](https://user-images.githubusercontent.com/47745930/131073708-100063c8-d6fe-47a7-ae27-8479923f0787.png)

**Comment by szaimen** [comment]
Did you make sure that the app is correctly installed and enabled? Maybe try to disable it again and enable it again.

**Comment by taavit21** [comment]
@szaimen 

Yes, i can even see the app under Settings but not as icon on the menu bar.

**Comment by szaimen** [comment]
> Maybe try to disable it again and enable it again.

So that didn't work?

**Comment by taavit21** [comment]
That did not work.

**Comment by szaimen** [comment]
@taavit21 please fill out the issue template so that we are able to help you. Thanks!

(You can copy it from here: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C+0.+Needs+triage&template=Bug_report.md)
