### ISSUE TITLE
External storage: admin should be able to select the global credentials of a user for authentication purposes

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#2861]
## Expected behavior

As an administrator you can choose between different authentication mechanisms if you want to set-up default external storages for your users without even knowing the users password.Therefore it should also be possible to choose `Global credentials of a user` for authentication purposes.

## Current behavior

As an administrator you can choose between the following authentication mechanisms if you set-up default external storages for your users. Unfortunately one option seems to be missing, the `Global credentials of a user` setting so that a user needs to enter the credentials only once and not per share.

![2016-12-26 20_36_43-admin - nextcloud](https://cloud.githubusercontent.com/assets/2572764/21485986/63fde8aa-cbac-11e6-8845-9a639a726ab9.png)
```
...
User entered, store in database -> credentials need to be entered bythe user per share
Global credentials              -> global credentials (entered by the admin)
Global credentials of user      -> missing option!
``` 
### Steps to reproduce
1. Login as an admin
2. Choose Admin -> External storages and check-out the available authentication mechanisms

#### Server Configuration

OS: Linux 3.2.82
Web server: Apache2 2.4.25
Database: MariaDB 5.5.53
PHP version: 5.6.29
Nextcloud version: 10.0.2

#### Client Configuration

Browser: Mozilla Firefox 50.1.0
Operating system: Windows 7

**Comment by MorrisJobke** [comment]
cc @icewind1991 @jancborchardt

**Comment by seimsel** [comment]
Hey

I run Nextcloud for my family (including some in-laws etc.). I would love to be able to alow them to add there own cloud services without them having to be very technical and creating there own app credentials.

Cheers,
Simon

**Comment by jancborchardt** [comment]
I guess this makes sense, yes. :)
