### ISSUE TITLE
After installation open the new page https://index.php/core/apps/recommended 

### ISSUE THREAD

**Issue by MRDO5** [nextcloud/server#28627]
After installation open the new page https://index.php/core/apps/recommended and i see 

https://user-images.githubusercontent.com/35971239/131212677-208d648d-e3d4-4fbf-88b6-c0ff31a42ef4.mp4

I have write ansible role for installation and each new install after version 18 browser tray open page https://index.php/core/apps/recommended what i make wrong or how can i correct it. I using nginx for proxy.
[nginx.conf.txt](https://github.com/nextcloud/server/files/7070450/nginx.conf.txt)

**Comment by kesselb** [comment]
Hey :wave: Closing this report in favor of https://github.com/nextcloud/server/issues/27575.
