### ISSUE TITLE
Text string from js file

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#28633]
In Tranifex there is still a text string from the `js` file in `dav` that should not be translated:

![obraz](https://user-images.githubusercontent.com/47037905/131231673-1daabbe3-9286-49ba-8a93-2146a7b37803.png)

![obraz](https://user-images.githubusercontent.com/47037905/131231908-642f73b6-55ec-4b9a-83e4-de0150198d12.png)

Files excluded in PR: #28285 by @rakekniven on August 4, 2021 and still one text string in Transifex. We don't want him there.

**Comment by rakekniven** [comment]
Thanx for reporting.
Maybe backporting is necessary. Will check tomorrow.

**Comment by Valdnet** [comment]
@rakekniven have you already acted? This text string still exists in Transifex 😉.

**Comment by rakekniven** [comment]
For me the code looks ok.
Now Morris is not here anymore and I don't know who will takeover such issues.

**Comment by Valdnet** [comment]
Is there already a person who can check and fix it?

**Comment by szaimen** [comment]
The PR was not yet backported if needed and is currently only included in the master branch (NC23).

**Comment by rakekniven** [comment]
Backports started. Please review.
