### ISSUE TITLE
App Update Required - Music - Cannot login to Nextcloud server

### ISSUE THREAD

**Issue by martinbook85** [nextcloud/server#28638]
As subject states I am forced to update an app and otherwise I cannot login.

When I try to update the app there is an error message.

I am not on the newest Nextcloud, maybe on NC 19 or 20.

This is what comes up
![AppUpdate](https://user-images.githubusercontent.com/83327909/131262739-27e94131-cec9-4730-84a3-cc56ea3532a4.png)

**Comment by kesselb** [comment]
Hey :wave:, this looks like an error with the music app. Please report this problem here: https://github.com/owncloud/music/issues

**Comment by martinbook85** [comment]
Nextcloud itself directed me to where I put this report. I have now opened it where you asked me instead.

Thanks!
