### ISSUE TITLE
Error menu file via mobile chrome nextcloud v.22.1.x

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#28630]
Since I updated various servers to nextcloud version 22.1.0 and now to 22.1.1 if I browse via mobile web from an android phone with Chrome on my server and try to open the File section, Chrome generates an "UFFA" error as per attachment, if I set desktop version in Chrome mobile everything works.  i also tried anonymous browsing same error and also clearing cache.  is this error to you?

![Screenshot_20210828-150110_Chrome](https://user-images.githubusercontent.com/35575744/131219006-604d9db9-76d6-4d0d-b2b9-e08d47d6c202.png)

**Comment by maretodoric** [comment]
I can confirm this is happening with me too. Came here to submit a bug report and found you already did that.

I would just add. That once you go to Photos/Files in Desktop mode, you can switch back to regular and it will display it just fine

**Comment by tigernero79** [comment]
it will work at the moment, because if you open and close the browser or go back to mobile mode and return to the "File" menu the problem recurs.

**Comment by Salvador1313** [comment]
Чего делать то?. Интернет походу отвалился, страница зависла, а я опять
куда то не туда нажал:(

пн, 30 авг. 2021 г., 00:43 maretodoric ***@***.***>:

**Comment by szaimen** [comment]
I cannot reproduce this anymore. I think this was due to a bug in Chromium.
