### ISSUE TITLE
Favorites (folders/files) are lost at each Nextcloud update

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#28647]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
Update Nextcloud [trough the CLI](https://docs.nextcloud.com/server/latest/admin_manual/maintenance/update.html#using-the-command-line-based-updater), (to a minor or a major version); all users favorites are lost, each time.
No errors are reported either by the updater, Nextcloud log, Webserver log or MySQL log.

As we are using `user_saml` app, this seems related.

### Server configuration

**Operating system:** Ubuntu 20.04

**Web server:** Apache 2.4

**Database:** MySQL 8

**PHP version:** 7.4

**Nextcloud version:** (see Nextcloud admin page) 21.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**

Upgrade since Nextcloud 15, v21.0.4 actually.

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - forms: 2.3.0
  - impersonate: 1.8.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - onlyoffice: 7.1.2
  - password_policy: 1.11.0
  - provisioning_api: 1.11.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - socialsharing_email: 2.2.0
  - systemtags: 1.11.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_totp: 6.1.0
  - user_saml: 4.1.1
  - viewer: 1.5.0
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - dashboard
  - encryption
  - files_external
  - firstrunwizard
  - nextcloud_announcements
  - photos
  - privacy
  - recommendations
  - support
  - survey_client
  - text
  - updatenotification
  - user_ldap
  - user_status
  - weather_status
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.fr"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.4.1",
        "overwrite.cli.url": "https:\/\/cloud.example.com",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 2,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "dbdriveroptions": {
            "1007": "\/etc\/ssl\/mysql\/client-key.pem",
            "1008": "\/etc\/ssl\/mysql\/client-cert.pem",
            "1009": "\/etc\/ssl\/mysql\/ca.pem",
            "1014": false
        },
        "trashbin_retention_obligation": "auto, 14",
        "versions_retention_obligation": "auto, 60",
        "default_language": "fr",
        "force_language": "fr",
        "default_locale": "fr_FR",
        "force_locale": "fr_FR",
        "loglevel": 2,
        "logdateformat": "F d, Y H:i:s",
        "maintenance": false,
        "theme": "",
        "quota_include_external_storage": false,
        "activity_expire_days": 7,
        "upgrade.disable-web": true,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpport": "587",
        "mail_sendmailmode": "smtp",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "skeletondirectory": "",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG"
        ],
        "hashingThreads": 4,
        "hashingMemoryCost": 77824,
        "hashingTimeCost": 3,
        "appstoreenabled": true,
        "updater.release.channel": "stable",
        "data-fingerprint": "e17456da6569df8f9e3ff3ef249019f4"
    }
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** SAML

### Client configuration
**Browser:** Brave

**Operating system:** Windows 10

**Comment by acsfer** [comment]
After a quick search this seems simlar to https://github.com/nextcloud/server/issues/7615

@nickvergessen as you commented at https://github.com/nextcloud/server/issues/7615#issuecomment-386217515 maybe you have an idea here?

**Comment by nickvergessen** [comment]
The content of the comment is still true and the mostlikely explanation

**Comment by JB1985** [comment]
Same here after updated from 21.0.3 to 21.0.4.

A maintance:repair fixed this problem.

**Comment by acsfer** [comment]
@JB1985 Wait, you're saying that that command restored database values previously deleted? 🤔 
Becasue in our case, values from `oc_vcategory` and `oc_vcategory_to_object` are just deleted...

**Comment by JB1985** [comment]
I had the problem that I could no longer see folders and files. The solution was to start the repair mode.

If it's not the same problem then sorry.

**Comment by kingfisher77** [comment]
Same here. Lost favorites  after each update (minor and major). We have LDAP user in a Samba AD. They are repeatedly not amused.

**Comment by kdomke** [comment]
Same Problem here after update to 23. Weary to update to 24 now...

**Comment by onmeac** [comment]
Also seen this happen going from v23 to v24.

What we have seen happen:
- user directories/files marked favorite survives an upgrade.
- group folders marked favorite are lost/gone after upgrading.
