### ISSUE TITLE
Disable pictures preview doesn't prevent new preview to be generated

### ISSUE THREAD

**Issue by biva** [nextcloud/server#28641]
I tried to disable the preview generation following the instructions in https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#previews In my config file, I have tried
`'enable_previews' => false,`
and
`'enable_previews' => 'false',`
I have removed the folder **/data/appdata_xyxyxyxyx/preview/**.
But Nextcloud continues to create previews.

My config:
NC 21.0.4 on Debian Buster
No other preview app installed
I'm not sure if it's important, but my data folder is outside the Nextcloud folder

**Comment by biva** [comment]
Am I the only one with this issue? Do I do something wrong?

**Comment by szaimen** [comment]
> 'enable_previews' => false,

Should actually work.

Would be interesting to see what is inside the newly created preview folder (after you've disabled preview generation and removed the deleted the folder and the folder got automatically created again as you#ve described here.).
You could e.g. run the following command on your server:
```
find /data/appdata_xyxyxyxyx/preview/
```

**Comment by biva** [comment]
Thanks @szaimen 
I see this in the preview folder:
`0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f`

And with the find command, I see a huge list. I share an extract below:
```
preview/5/0/9/d/4/9/a
preview/5/0/9/d/4/9/a/1172053
preview/5/0/9/d/4/9/a/1172053/4032-2268-max.jpg
preview/5/0/9/d/4/9/a/1172053/256-256-crop.jpg
preview/5/0/5
preview/5/0/5/b
preview/5/0/5/b/d
preview/5/0/5/b/d/4
preview/5/0/5/b/d/4/d
preview/5/0/5/b/d/4/d/1171896
preview/5/0/5/b/d/4/d/1171896/256-256-crop.jpg
preview/5/0/5/b/d/4/d/1171896/4032-1908-max.jpg
preview/5/0/1
preview/5/0/1/3
preview/5/0/1/3/b
preview/5/0/1/3/b/3
preview/5/0/1/3/b/3/1
preview/5/0/1/3/b/3/1/1087398
preview/5/3
preview/5/3/9
preview/5/3/9/9

```

**Comment by szaimen** [comment]
And you've made sure that `'enable_previews' => false,` is in your config.php, and you've tested it again by deleting the preview folder again?

**Comment by biva** [comment]
Unfortunately yes :(

**Comment by szaimen** [comment]
strange

**Comment by biva** [comment]
![image](https://user-images.githubusercontent.com/9964305/133458556-07cc8626-a71f-4c3c-8337-9a02634f5f94.png)

**Comment by biva** [comment]
I'll do it again though. Is there a command that I should run after having made the change in config.php ?

**Comment by szaimen** [comment]
> Is there a command that I should run after having made the change in config.php ?

yes, `rm -r /data/appdata_xyxyxyxyx/preview`

**Comment by biva** [comment]
Yes, I deleted the preview folder. I meant a nextcloud server command so that the new config file is taken into account?
Usually, preview come back after a few hours. I'll check and tell you tomorrow.

**Comment by szaimen** [comment]
> I meant a nextcloud server command so that the new config file is taken into account?

No, there is no command that I am aware of. Should be using the new config on the fly.

**Comment by biva** [comment]
Hello @szaimen,
The _preview_ folder is back :(
![image](https://user-images.githubusercontent.com/9964305/134502643-2a034ade-24f2-4fc7-bbfb-e4b3390acf4c.png)

**Comment by szaimen** [comment]
strange

**Comment by biva** [comment]
Does it work on your side?

**Comment by biva** [comment]
Hello @szaimen , I still have the issue, would anybody have a solution to avoid generating the preview?

**Comment by biva** [comment]
Would you need me to show you any specific log or config file?

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
