### ISSUE TITLE
"download" icon of a photo viewer is barely visible (shared link, light theme)

### ISSUE THREAD

**Issue by Alt37** [nextcloud/server#28642]
When you share a folder with pictures unlogged/anonymous user can open them in a viewer. On the right top corner there's three icons - "slides", "download" and "close". With a default light theme "Slides" and "Close" are in a white color but "Download" is black so it's barely visible for a user (screenshot bellow)

![unlogged user menu](https://user-images.githubusercontent.com/44649402/131268302-36a9f79b-15fd-44e8-9069-8db22bff84c5.png)

It's actually in a CSS
```
.icon-download {
    background-image: var(--icon-download-000);
}
```
This color is also used for hidden menu icon of a logged user

![logged user menu](https://user-images.githubusercontent.com/44649402/131268845-37df5ef7-bfc7-4d2c-b5c4-02a751ba0760.png)

But shared links for anonymous user better to use different CSS

 ```
.icon-download {
    background-image: var(--icon-download-fff);
}
```

For now administrator can force some dark theme (e.g. "Breeze Dark") with a "Theming" app.

### Steps to reproduce
1. Share link to a folder with pictures
2. Open new tab with that link
3. Open any picture

### Expected behaviour
All menu icons has the same color

### Actual behaviour
"download" icon is black and barely visible on a dark background

Nextcloud version: 21.0.3 or 22.1.1

**Comment by CarlSchwan** [comment]
This seems to have already been resolved in master, but I can reproduce in stable22

![image](https://user-images.githubusercontent.com/23653902/131338846-2338a708-4fb8-4f8f-ab84-15a5dbdcd572.png)

**Comment by szaimen** [comment]
dup of https://github.com/nextcloud/viewer/issues/848
