### ISSUE TITLE
Export all personal calendars as a zip file

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/server#2864]
When an user who has a lot of calendars wants to leave.

cc https://github.com/nextcloud/calendar/issues/257

**Comment by georgehrke** [comment]
@tcitworld Do you want to take care of this? :)

**Comment by georgehrke** [comment]
ping @tcitworld ^ :)

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest and no respond since around 2 years. Please reopen if you still want to implement this.

**Comment by tcitworld** [comment]
I've actually started working on this.

**Comment by tcitworld** [comment]
Should probably use a background process, just like https://github.com/nextcloud/files_zip

**Comment by Pytal** [comment]
@tcitworld does https://github.com/nextcloud/server/pull/30963 close this?

**Comment by tcitworld** [comment]
Not yet https://github.com/nextcloud/server/pull/30963#discussion_r806406444

**Comment by Pytal** [comment]
So is https://github.com/nextcloud/server/issues/564 would be only *ics files directly and this would be an addition on top for zip files?

**Comment by Pytal** [comment]
In any case since https://github.com/nextcloud/user_migration already exports a zip, an occ option can be added on top to specify which data to export/import https://github.com/nextcloud/user_migration/issues/55 i.e. they can choose to only export calendars

**Comment by Pytal** [comment]
Closed by https://github.com/nextcloud/user_migration/pull/167
