### ISSUE TITLE
Users can't grant other users "edit" function for shared calendars

### ISSUE THREAD

**Issue by manajoe** [nextcloud/server#2865]
With OwnCloud 9.1.0 I can't tick the "Can edit"-Checkbox for shared calendars.
I have a calendar for User "A", where User "B" has the permisson to view the calendar. Now I want to add the permission for User "B" to edit User "A"-calendar. I can tick the checkbox, but the changes will not be saved.
Additionally, if I want to share the calendar with new User "C", I write the username to the textbox, but I can't select User "C", as no username is proposed.
Is there anybody else having these problems?

**Comment by nickvergessen** [comment]
Please open a new issue if that is still the case, I can't reproduce this issue with Nextcloud 10 and 11 with the newest calendar app.
