### ISSUE TITLE
iMIP invitation sent with organizer's preferred language if no language set for attendee

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#28665]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
0. Set the instance default_language to 'en'
1. Set your language to something distinctive, like French
2. Configure your calendar in Thunderbird
3. Create a new event, invite an email attendee
4. Save the event

### Expected behavior

The invitation is sent out in English

### Actual behavior

The invitation is sent out in French

Ref https://github.com/nextcloud/server/pull/12020
Ref https://github.com/nextcloud/server/issues/11795#issuecomment-458510770 @skjnldsv @oparoz

**Comment by ChristophWurst** [comment]
Some debugging findings.

The magic happens in `\OCA\DAV\CalDAV\Schedule\IMipPlugin::schedule`. `\OCP\L10N\IFactory::findLanguage` gives me `fr` as "default language" because the user has set their `lang` is set to `fr`. The global `default_language` is never taken into consideration.

**Comment by ChristophWurst** [comment]
`\OCP\L10N\IFactory::findLanguage` claims to *find the best language*. I would argue this method finds the "best language" for *the current user*. We need something that finds the "best language" *for the instance*. The logic would be a bit of the opposite. It would first check if there is a `default_language` set, then it takes that. Then it can check if the current user has a lang set and use that, last it will use `en`. @nickvergessen what do you think? :)

**Comment by nickvergessen** [comment]
Should first check `force_language` (still a thing?), then `default_language`, then sender and final `en`.
Lots of emails are doing this manually (activity mail) or should do (Talk email invites), so would make sense to have a dedicated method on the IFactory I think?

**Comment by ChristophWurst** [comment]
PR at https://github.com/nextcloud/server/pull/29015
