### ISSUE TITLE
22.1.1.2  (38)Function not implemented: AH00141: Could not initialize random number generator

### ISSUE THREAD

**Issue by msy999** [nextcloud/server#28666]
Steps to reproduce
impossible to install

[Tue Aug 31 12:25:20.188499 2021] [:crit] [pid 1] (38)Function not implemented: AH00141: Could not initialize random number generator

Server configuration
Operating system:
synology 6.2.3
Web server:
Apache
Database:
postgres

Nextcloud version: (see Nextcloud admin page)
22.1.1.2
Fresh install and update
Where did you install Nextcloud from:
Official Nextcloud website

Client configuration
Browser:
crome
Operating system:
windowns 10

**Comment by kesselb** [comment]
This error message is coming from Apache. It does not look related to Nextcloud.

**Comment by msy999** [comment]
synology 6.2.3
I am getting an error in docker image.

docker image : nextcloud:latest   <Currently 22.1.1.2 error occurs.>
docker db : postgres
It looks like the docker image is corrupted.

2021년 8월 31일 (화) 오후 10:53, kesselb ***@***.***>님이 작성:

**Comment by g-work** [comment]
> As a simple "papercut" fix, you could build the docker file with this tiny change in the Dockerfile : instead of: `FROM php:8.0-apache-bullseye` use: `FROM php:8.0-apache-buster`
> 
> [...]

I'm not very familiar with docker - do I need docker-compose to do that?

**Comment by leiterschleife** [comment]
+1 currently I am on nextcloud v20.0.4 using the docker apache image. I am trying to upgrade the container to 20.0.14 in order to upgrade to the current major version after that. However, due to this error the container won't start an I have no upgrade path available. Is this error fixed in v21? Can the upgrade to 20.0.14 be omitted?
