### ISSUE TITLE
Cursor doesn't work when naming a new file [MINOR]

### ISSUE THREAD

**Issue by Clementine46** [nextcloud/server#28669]
When naming a new file, if a mistake is being made in the name, there is no way to place the cursor where the error is. It can only be changed by manually using the keyboard arrows.

![1](https://user-images.githubusercontent.com/50834537/131514681-1422909f-4191-425f-be12-01d73ee00b50.gif)

It would be great if the cursor could be placed directly where needed in the text input section, just like it does when renaming a file.

![2](https://user-images.githubusercontent.com/50834537/131515328-a0336767-d474-4d41-92b1-b10fa8cc7ef1.gif)

**Comment by szaimen** [comment]
Will be fixed with https://github.com/nextcloud/server/pull/28645

**Comment by 488849** [comment]
👍

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
