### ISSUE TITLE
How could I remove filetype of onlyoffice?

### ISSUE THREAD

**Issue by cmdntd** [nextcloud/server#28674]
I disabled and removed onlyoffice, but these filetype still there.
How could I remove these filetype of onlyoffice?
![YuQfRyJUGl](https://user-images.githubusercontent.com/1112881/131554535-afbcb020-5399-4381-8232-13cbe63f6ddf.png)

Client details:
Android 11
Chrome
Deck 1.5.0
Nextcloud 22.1.1
Samsung phone

Server
Google compute
Ubuntu 20.04
PHP 7.4
MySQL

**Comment by szaimen** [comment]
Hi 👋 thanks for your report. 
Please ask your question in https://help.nextcloud.com 
Thanks!

**Comment by cmdntd** [comment]
I tried to login to help.nextcloud.com by Google account, but I have 502 error.

**Comment by szaimen** [comment]
works for me

**Comment by cmdntd** [comment]
I've done with manually account.

**Comment by cmdntd** [comment]
But it seems noone cares
https://help.nextcloud.com/t/how-could-i-remove-filetype-of-onlyoffice/122882
