### ISSUE TITLE
Ensure Files HPB compatibility

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#28687]
### Deadline 
28.09.2021

**Comment by icewind1991** [comment]
- [ ] https://github.com/nextcloud/server/pull/28820

**Comment by AndyScherzinger** [comment]
@icewind1991 is this ready to review and does the PR cover all needed changes for v20 or will there be some more PRs?

**Comment by icewind1991** [comment]
I'll need to do some proper testing to make sure but that should be the main one

**Comment by icewind1991** [comment]
notify_push 0.2.4 has been released to be compatible with the upcoming nc 20.0.13

**Comment by AndyScherzinger** [comment]
Nice @icewind1991 so this is then basically done? :) Just asking so we can ping the customer with your infos:

* Nc 20.0.13 + https://github.com/nextcloud/server/pull/28820
* notify_push 0.2.4

**Comment by AndyScherzinger** [comment]
...and potentially also close this issue 🚀

**Comment by icewind1991** [comment]
Yes, #28820 + notify_push 0.2.4 should make things work
