### ISSUE TITLE
Allow to set-up a read-only account password/token

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#2868]
## Expected behavior
If server information should be monitored by e.g. Nagios, using the serverinfo app, it requires an admin account to be able to access all relevant data. It should be possible to create an account and restrict its access to the serverinfo API only, by e.g. adding the account to a `default 'Server Information'` group (read-only access).

## Current behavior
If server information should be monitored by e.g. Nagios, using the serverinfo app, it is currently not possible to set-up read-only access to the serverinfo data.

### Steps to reproduce
1. Login as as an administrator
2. Choose Users -> Create user

#### Server Configuration
OS: Linux 3.2.82
Web server: Apache2 2.4.25
Database: MariaDB 5.5.53
PHP version: 5.6.29
Nextcloud version: 10.0.2

#### Client Configuration
Browser: Mozilla Firefox 50.1.0
Operating system: Windows 7

**Comment by MorrisJobke** [comment]
cc @icewind1991 @ChristophWurst because you worked on the app specific passwords and the scoping.

**Comment by MorrisJobke** [comment]
This is basically done with #719 - you can remove file system access from the app specific token.
