### ISSUE TITLE
Incorporate files_external and auth changes from customer demo

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#28689]
```$subject```

TBD for Nextcloud 22 and up

### Delivery Date

End of September / Beginning of October (no fixed date, to be aligned with Fabian)

**Comment by joshtrichards** [comment]
I'm guessing this was long ago addressed, probably in #29349 (and maybe also #29484 but unsure if related).

Closable Issue?

**Comment by AndyScherzinger** [comment]
Thanks for the ping, @blizzz what do you think?

**Comment by blizzz** [comment]
ack
