### ISSUE TITLE
Filter unified search in Collectives

### ISSUE THREAD

**Issue by biva** [nextcloud/server#28684]
When I use the unified search, I can filter the results for files or events, using the parameter **in:files** or **in:events**

Would it be possible to filter for the content in **Collectives** only, with a similar parameter **in:collectives**?

An alternative solution would be a search bar within the Collectives app to search only within the app.

**Comment by szaimen** [comment]
Please report this to https://gitlab.com/collectivecloud/collectives thanks!

**Comment by biva** [comment]
Are you sure @szaimen ? Because most of the time, when I post an issue there, it's in fact related to another component of Nextcloud :D . In this case, isn't it related to the search function of Nextcloud, and thus a server feature?
