### ISSUE TITLE
Log spamed

### ISSUE THREAD

**Issue by weinic** [nextcloud/server#28696]
Hi there,

 my log is spammed with this error every 20 minutes.
 This has happened since I added SMB as external storage.
This seems to be due to folders that cannot be accessed.
 The access restriction on some folders is also set and wanted on the part of the SMB share.

 However, this should not cause any errors or other errors in the log.

Server data:

NC 21.0.4
Debian Linux 5.10.0-0.bpo.8-amd64 x86_64
Php Version 7.3.29
Maria db 10.3.29

[files] Error: OCP\Files\NotPermittedException:  at <<closure>>

 0. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/files_external/lib/Lib/Storage/SMB.php line 623
    OCA\Files_External\Lib\Storage\SMB->getFolderContents("petra")
 1. <<closure>>
    OCA\Files_External\Lib\Storage\SMB->getDirectoryContent("petra")
 2. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Files/Cache/Scanner.php line 409
    iterator_to_array(Generator {})
 3. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Files/Cache/Scanner.php line 389
    OC\Files\Cache\Scanner->handleChildren("petra", 2, 3, 15649835, true, 0)
 4. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Files/Cache/Scanner.php line 341
    OC\Files\Cache\Scanner->scanChildren("petra", 2, 3, 15649835, true)
 5. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Files/Cache/Scanner.php line 511
    OC\Files\Cache\Scanner->scan("petra", 2, 3)
 6. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Files/Cache/Scanner.php line 522
    OC\Files\Cache\Scanner->OC\Files\Cache\{closure}("*** sensitive parameters replaced ***")
 7. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Files/Cache/Scanner.php line 510
    OC\Files\Cache\Scanner->runBackgroundScanJob(Closure {}, "petra")
 8. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Files/Utils/Scanner.php line 186
    OC\Files\Cache\Scanner->backgroundScan()
 9. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/files/lib/BackgroundJob/ScanFiles.php line 90
    OC\Files\Utils\Scanner->backgroundScan("")
10. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/files/lib/BackgroundJob/ScanFiles.php line 126
    OCA\Files\BackgroundJob\ScanFiles->runScanner("admin")
11. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/BackgroundJob/Job.php line 52
    OCA\Files\BackgroundJob\ScanFiles->run(null)
12. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/BackgroundJob/TimedJob.php line 59
    OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
13. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/cron.php line 128
    OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2021-09-02T12:00:01+02:00

**Comment by weinic** [comment]
If I activate ACL access check (checks the ACL access when listing files), this error always comes up every time the smb share is accessed:

[PHP] Error: Error: Undefined offset: 1 at /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/files_external/lib/Lib/Storage/SMB.php#222 at <<closure>>

 0. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/files_external/lib/Lib/Storage/SMB.php line 222
    OC\Log\ErrorHandler::onError(8, "Undefined offset: 1", "/srv/dev-disk-b ... p", 222, {file: Icewind\S ... "})
 1. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/files_external/lib/Lib/Storage/SMB.php line 254
    OCA\Files_External\Lib\Storage\SMB->getACL(Icewind\SMB\Native\NativeFileInfo {})
 2. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/files_external/lib/Lib/Storage/SMB.php line 623
    OCA\Files_External\Lib\Storage\SMB->getFolderContents("*** sensitive parameter replaced ***")
 3. <<closure>>
    OCA\Files_External\Lib\Storage\SMB->getDirectoryContent("*** sensitive parameter replaced ***")
 4. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Files/Cache/Scanner.php line 409
    iterator_to_array(Generator {})
 5. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Files/Cache/Scanner.php line 389
    OC\Files\Cache\Scanner->handleChildren("*** sensitive parameter replaced ***", false, 3, 14706224, true, 0)
 6. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Files/Cache/Scanner.php line 341
    OC\Files\Cache\Scanner->scanChildren("*** sensitive parameter replaced ***", false, 3, 14706224, true)
 7. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Files/Cache/Watcher.php line 106
    OC\Files\Cache\Scanner->scan("*** sensitive parameter replaced ***", false)
 8. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Files/View.php line 1354
    OC\Files\Cache\Watcher->update("*** sensitive parameters replaced ***")
 9. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Files/View.php line 1394
    OC\Files\View->getCacheEntry(OCA\FilesAccessC ... l}, "*** sensitive parameter replaced ***", "/admin/files/SMB")
10. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Files/Node/Root.php line 201
    OC\Files\View->getFileInfo("/admin/files/SMB")
11. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Files/Node/Folder.php line 149
    OC\Files\Node\Root->get("/admin/files/SMB")
12. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/photos/lib/Controller/AlbumsController.php line 84
    OC\Files\Node\Folder->get("SMB")
13. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/photos/lib/Controller/AlbumsController.php line 68
    OCA\Photos\Controller\AlbumsController->generate("SMB", false)
14. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 218
    OCA\Photos\Controller\AlbumsController->myAlbums("SMB")
15. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 127
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Photos\Controller\AlbumsController {}, "myAlbums")
16. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/AppFramework/App.php line 157
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Photos\Controller\AlbumsController {}, "myAlbums")
17. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Route/Router.php line 302
    OC\AppFramework\App::main("OCA\\Photos\\Co ... r", "myAlbums", OC\AppFramework\ ... {}, {path: "SMB",_ro ... "})
18. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/base.php line 993
    OC\Route\Router->match("/apps/photos/api/v1/albums/SMB")
19. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/index.php line 37
    OC::handleRequest()

GET /apps/photos/api/v1/albums/SMB
from 109.43.51.40 by admin at 2021-09-02T12:27:16+02:00

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
