### ISSUE TITLE
Installed both nextcloud and owncloud on hostmonster shared server, here is what i found

### ISSUE THREAD

**Issue by isaacgerg** [nextcloud/server#2869]
Apologies for posting here as I cannot find a forum to post this.

I used a mysql database backend which i configured at install time via web interface.

1.  I setup the sync client in windows 10.  I then drug over a large folder of items.  So large that sync begins before the files are finished copying.  I get several internal server errors with nextcloud that prevent the sync from finishing properly.  This didnt happen with owncloud.

2. When trying to delete files, I get severl "file locked" issues which I cannot resolve.  This didnt happen with owncloud.  I had to resort to turning off file locking in the config to fix.

3. The log reports several issues with out of memory in php when calling image related functions.  A quick phpinfo() script in the nextcloud dirrectory shows I have 1024MB for memory_limit.  However, php is reporting that i have around ~6.6MB of RAM, not sure why this issue.  This also happened in ownclound except it said I had ~6.8MB of RAM allocated.

**Comment by thueske** [comment]
Do you have error messages like **MySQL server has gone away** in your log file which is accessible via your admin login in web interface -> settings -> logging? Maybe the shared MySQL server is some kind of overloaded and the files get locked.

Following information can be found here: https://docs.nextcloud.com/server/11/admin_manual/configuration_files/files_locking_transactional.html

> File locking is enabled by default, using the database locking backend. This places a significant load on your database.

**Comment by isaacgerg** [comment]
@thueske No I dont have any of those messages.  Just file locked.

Any idea on the allocation issue?  I can't understand why PHP reports back anything other than 1024M.

**Comment by thueske** [comment]
Hmmm... I got the same problem with file locking like you and that messages - disabling file locking works, but is obviously not the best way... Maybe these are restrictions we have to deal with when using shared hosting environments.

Image functions are in general all very resource hungry, but I never run in problems like you with 1GB of memory_limit when nextcloud is generating e.g. thumbnails - sorry.

**Comment by nickvergessen** [comment]
I'm not really sure there is a lot we can do. As @thueske already said, it might be one of the limitations on a shared hosting.

If someone has additional ideas, feel free to reopen the issue.

**Comment by isaacgerg** [comment]
No problem Joas.  I am posting just for your awareness.
