### ISSUE TITLE
QA Kerberos/Auth/Importer improvements

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#28690]
```$subject```

TBD for Nextcloud 22 and up

### Delivery Date

End of September / Beginning of October (no fixed date, to be aligned with Fabian)

**Comment by joshtrichards** [comment]
Related to since merged #29349 PR?

**Comment by AndyScherzinger** [comment]
Cc @blizzz - resolved or obsolete?

**Comment by blizzz** [comment]
Yes, resolved
