### ISSUE TITLE
Updater app - Check DB privileges

### ISSUE THREAD

**Issue by kehugter** [nextcloud/server#2870]
I keep my DB user with minimum privileges during normal usage for security reasons. The update using the updater app failed because of missing `DROP` and `INDEX` privileges.

### Steps to reproduce
1. Update using the updater app. Finish the first part successfully
2. Return to the main site to finish updating the database
3. Update fails because of missing DB privilleges

### Expected behaviour
During the sanity check, the user is warned about insufficient DB privileges.

### Actual behaviour
No DB privileges check is done, user gets an error message after the Nextcould instance is unusable.

### Server configuration
**Operating system**:
Debian 8.6
**Web server:**
nginx
**Database:**
mysql
**PHP version:**
5.6.29
**Nextcloud version:** (see Nextcloud admin page)
10.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Nextcloud 10.0.1
**Where did you install Nextcloud from:**
tar archive

**Comment by nickvergessen** [comment]
moved to https://github.com/nextcloud/updater/issues/83
