### ISSUE TITLE
Mail Client - Ungelesene Mails - Sortierung

### ISSUE THREAD

**Issue by drmichaelfricke** [nextcloud/server#28714]
Guten Tag,
ich hoffe, ich bin hier richtig...
Kann mir wohl jemand weiterhelfen. wie ich bei den eingegangenen E-Mail die Sortierung nach Datum einstellen kann? Außerdem ist  uns aufgefallen, dass die Anzahl ungelesener Mail in der Regel nicht mit der angezeigten Zahl übereinstimmt.

Bin auf Euere antworten gespannt,
Gruß
Michael

**Comment by szaimen** [comment]
Hi, can you please rephrase your issue in English? Thank you!

**Comment by kesselb** [comment]
https://github.com/nextcloud/mail/issues/679
