### ISSUE TITLE
feature request: Serverless Rclone support 

### ISSUE THREAD

**Issue by phly95** [nextcloud/server#28718]
Not everyone has the means to have a computer running 24/7 or have access to opening ports. Integrating Rclone as a server support into the app would mean that one could create an encrypted vault on cloud storage they already have (eg. Google Drive, Onedrive, etc.) instead of running a server themselves, allowing preservation of privacy without the headaches of self-hosting. 

Processing could be decentralized and use available devices at the time to do the work, be it a phone, computer, or anything with the nextcloud app running.

This feature could make it a viable replacement for big cloud, and something that one could get less tech savvy users to adopt without worrying about maintenance. Privacy does rely on the habits of those around you after all.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
