### ISSUE TITLE
Webdav usage results in massive number of php sessions

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#2871]
### Steps to reproduce
1. A new PHP session is being spun up for every single webdav request. This results in thousands if not tens or hundreds of thousands (depending on workload) of PHP sessions being active. 
2. NextCloud is clearly starting the session and placing encrypted_session_data inside the session data.

### Expected behaviour
WebDav is stateless and should remain as such

### Actual behaviour
Not treated as stateless

**Comment by MorrisJobke** [comment]
We use the sessions in our desktop clients, right? cc @LukasReschke and @rullzer for the details about this whole webdav and sessions discussion we already had multiple times. 🙈

**Comment by ChristophWurst** [comment]
ghost -> close
