### ISSUE TITLE
[Feature] Support Hardware TOTP Token 2FA

### ISSUE THREAD

**Issue by mrnoisytiger** [nextcloud/server#2873]
TOTP via smartphone application has its set of securities issues to consider, such as smartphone security itself, exposure of the QR code, and others. Also, sometimes, it is not necessarily feasible to use a smartphone to generate a 2FA token though I know the backup codes exist. 

It would be great if NextCloud could support the standard OAuth TOTP Hardware based tokens.

**Comment by MariusBluem** [comment]
What about: https://github.com/nextcloud/twofactor_u2f 😅
