### ISSUE TITLE
[NC 22.x.x] Sendmail option not available in webUI but working with config file 

### ISSUE THREAD

**Issue by Epy** [nextcloud/server#28733]
Hello folks !
I did'nt see any relevant issue for this so I'm creating a new one, I hope I didn't miss any

"sendmail" option in web UI configuration on the serveur isn't available, the list only contains "SMTP" since the fresh install of Nextcloud 22.0.1 (IIRC) stable version as it was linked on the official website a few days ago. It wasn't an update from an earlier version.
If I don't make any mistake this sendmail option should be available, it's not the PHP mailer one which was removed. And if I read the documentation correctly and it's up-to-date the installer script detects if sendmail is present or not

It's installed on a Debian buster with a working Postfix configuration as an InvisionPowerboard is already sending e-mail with it.
The 22.1.1 update didn't fixed it

### Steps to reproduce

1. Install Nextcloud 22 on a Debian Buster with Postfix and MariaDB
2. Go to Parameters as the admin user
3. Go to Basic parameters ("Paramètres de base" in my french install)
4. Click on the list in "E-mail server" / "Sending mode" => No other choice than SMTP
5. Go to your config.php file, set "sendmail" for "mail_stmpmode"
6. Set 'pipe' for "mail_sendmailmode"
7. Go to the WebUI, it displays "Sendmail mode" "-t pipe" (but the list is still on SMTP)
8. Modify any parameter, it's automatically saved and SMTP mode is back in UI and config file (and I can't use SMTP mode for this, for users related reasons)

### Expected behaviour
- "Sendmail" and "Pipe" options should be available in WUI

Is there a way to force this detection again ? sendmail command exists on this system, 
```
# which sendmail
/usr/sbin/sendmail
```

### Server configuration

**Operating system:**
Debian Buster
**Web server:**
nginx
**Database:**
MariaDB
**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
22.1.1 (just updated)
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
nextcloud.com archive
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - bruteforcesettings: 2.2.0
  - cloud_federation_api: 1.4.0
  - dashboard: 7.1.0
  - dav: 1.18.0
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.13.2
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.9.0
  - notifications: 2.10.1
  - oauth2: 1.9.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.11.0
  - serverinfo: 1.12.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - systemtags: 1.11.0
  - text: 3.3.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.1
  - updatenotification: 1.11.0
  - viewer: 1.6.0
  - workflowengine: 2.3.1
Disabled:
  - accessibility
  - activity
  - admin_audit
  - circles
  - comments
  - contactsinteraction
  - encryption
  - federation
  - files_external
  - nextcloud_announcements
  - recommendations
  - support
  - survey_client
  - user_ldap
  - user_status
  - weather_status

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.1.1.2",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "pipe",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "default_phone_region": "fr_FR",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

Thank you for reading this !

**Comment by szaimen** [comment]
I am not sure if this option for sendmail was ever implemented in the webui so I think this is rather an enhancement request.

**Comment by Epy** [comment]
I have it on a 21.0.4 version (installed on another server, updated on each successive version from 18 or 19 I don't remember)
I'd be happy to give more info if needed.

**Comment by Kieltux** [comment]
It is on my two 21.0.4 Nextcloud Servers.

![nextcloud_2104_EmailServer](https://user-images.githubusercontent.com/6629537/134560625-7ee7e09a-f823-4fa8-b8d5-a7ed61c54fe3.png)

**Comment by Epy** [comment]
Yes that's why I'm concerned by its absence on a 22.x.x version :)
Maybe just the detection that went wrong ? Is there an occ command to re-detect sendmail ? or anything else ?

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by Epy** [comment]
Hi
Thanks for your answer :)
Upgrading to lastest versions will take some time as I have to upgrade to a not packaged PHP8 on Debian 11, I'll work on it and give a feedback as soon as possible
