### ISSUE TITLE
[Dashboard] Allow administrators to set default settings 

### ISSUE THREAD

**Issue by ya-d** [nextcloud/server#28732]
There should be a settings panel to set a **default dashboard layout for all users**. Maybe even an option to lock it and block individual modifications (see App Order).

This would help providing a meaningful first use experience for users and make it easier to support. Also the cloudy sky defaults to Nextclouds blue and might clash with local design.

Basically the customize modal should be available as a settings page for administrators. Setting a standard weather location would be nice as well.

<img width="884" alt="grafik" src="https://user-images.githubusercontent.com/30781876/132247526-ff1fe768-3fc0-4c8c-bbeb-2c7d62df44be.png">

**Comment by szaimen** [comment]
See https://github.com/nextcloud/server/pull/25309
