### ISSUE TITLE
Nextcloud 2 factor email support

### ISSUE THREAD

**Issue by TheThief** [nextcloud/server#28759]
Previously this was provided by a third-party app, but the developer no longer supports it. This should be a core feature, and Nextcloud should consider taking ownership of this app.

Reference: https://github.com/rullzer/twofactor_email/issues/187#issuecomment-915087779

**Comment by acsfer** [comment]
Well, @rullzer is the developer, and also a **Core** member... if switch it to Core was an option, i belive it would already be done 🤔

**Comment by ChristophWurst** [comment]
> This should be a core feature, and Nextcloud should consider taking ownership of this app.

Who's *Nextcloud* in this statement? The *Nextcloud community*? Nextcloud Gmbh?

We can move the repo to the org, sure, but someone has to maintain it. And that takes effort. According to https://github.com/rullzer/twofactor_email/issues/187#issuecomment-915343142 someone already volunteered to take this responsibility.

**Comment by TheThief** [comment]
I was sort of meaning all of the above and putting it into _this repo_ - apps/twofactor_backupcodes is already in here for example

But honestly whatever people think is best. I'm just a concerned user who currently has a local patch to my twofactor_email app to enable it under NC22.

**Comment by ChristophWurst** [comment]
Okay, so we are talking about *shipped apps*. twofactor_backupcodes is special, there are hard requirements from core onto that app, hence it lives here. Same applies to the other shipped apps. Anything independent is kept outside and installed/updated via the app store.

> But honestly whatever people think is best. I'm just a concerned user who currently has a local patch to my twofactor_email app to enable it under NC22.

Fair point.

In any case, twofactor_email will certainly not be shipped with server. Just like we don't ship any of the maintained and supported providers like TOTP or U2F, not Nextcloud Talk, no groupware and so on. I'm closing this ticket therefore.

**Comment by TheThief** [comment]
That's fair. You should consider taking it into the Nextcloud github org though.
