### ISSUE TITLE
Doctrine\DBAL\Schema\SchemaException: The table with name 'cloud7.oc_direct_edit' already exists.

### ISSUE THREAD

**Issue by marianoju** [nextcloud/server#28766]
Trying to update from Nextcloud 17.0.10 to Nextcloud 18.0.14 the web-updater (not the command line) ran into some trouble: 

```
Prepare update
Log level set to "debug
Maintenance mode switched on
Repair step: Repair MySQL mapping
Repair information: All tables already have the correct sorting -> nothing to do
Repair step: Repair SQLite auto increment
Repair step: Copy data from accounts table when migrating from ownCloud
Repair step: delete accounts table when migrating from ownCloud
Database schema is updated
Doctrine\DBAL\Schema\SchemaException: the table named 'cloud7.oc_direct_edit' already exists.
```

The updater encourages to report this issue to the Nextcloud community and references this repository. 

`.../index.php/settings/integrity/failed` forwards to the updater. 

I have no access to the command line on the server of this Nextcloud instance.

**Comment by szaimen** [comment]
Hey, sry to say but nc17 and nc18 are out of support.
