### ISSUE TITLE
Change thumbnails format to potentially speed-up Load time

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/server#28761]
Feature Request: 
All Icons and pictures used in the ui should be AVIF or WEBP for faster loading time.
Support for those formats for the splash screen would be nice.

**Comment by acsfer** [comment]
A lot, if not all, icons, are SVG.
Can you detail how an AVIF or WEBP hould load faster than SVG (and preserve it as a vector graphics file)?

**Comment by MrLoverLoverMMMM** [comment]
I think you missunderstand my idea.
I talk about automatically converting the non-vectore graphics from the preview generator or the splash-screen or the icon from the users to that format.

**Comment by baozi510** [comment]
I agree.
i vote webp.
avif too radical

**Comment by kowalski7cc** [comment]
@baozi510 I think you can define both and let the browser decide

**Comment by szaimen** [comment]
Duplicate of https://github.com/nextcloud/server/issues/13552
