### ISSUE TITLE
Department Share (Cifs)  files not synced to client

### ISSUE THREAD

**Issue by schmm2** [nextcloud/server#2879]
Hello there
I'm pretty new to nextcloud. I rode alot of different issues and I hope there is not another post like this. Maybe this is even by design. I found this issue which comes pretty close to my [issue](https://github.com/owncloud/core/issues/23394)

Now to the issue:
I have different LDAP users. Everyone has an external Cif shares mounted (department folder).
If the user edits a file locally, the change gets synced to the server.
If another colleague edits a file in the department share, the changes don't get synced to the users client. The folders differ in size (5-26GB) and depth (2-9 Level). In my testshare, I have around 2000 Files.

If I run the **occ files:scan** command. Only a few files are scanned for changes. 
I get this output:

<img width="981" alt="sss" src="https://cloud.githubusercontent.com/assets/11064825/21542588/22891150-cdbf-11e6-9205-2dc7e2fca9ca.png">

If I edit a file locally the counter increases. So I guess this must be by design. Only Filechanges which are changed by the user directly are stored in the Nextcloud DB.

### Steps to reproduce
1. Initial Sync, works great
2. Other Users put Files/Folder on Cifs Share
3. Scan the Users Files with occ files:scan --path="/UserSID/"

### Expected behaviour
Folder/ Files should download immediately

### Actual behaviour
Files/Foder not downloaded
The amount of files which are scaned for changes doesn't increase

### Server configuration
**Operating system**:
Debian 8.6 jessie

**Web server:**
Apache 2.4.10

**Database:**
MariaDB 10.1.20

**PHP version:**
7

**Nextcloud version:** (see Nextcloud admin page)
10.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
Could you try to setup the detection of changes on every request (this is a setting in the gear icon menu for the external storage mount).

Maybe also try the files_notify component described in https://github.com/nextcloud/server/issues/1016#issuecomment-279032265

Thanks
