### ISSUE TITLE
File picker filter with first letters typed

### ISSUE THREAD

**Issue by biva** [nextcloud/server#28807]
In the file picker, it would be great to be able to type the first letters of a file to filter the list, with the filenames _starting_ by these letters on top, and the filenames _including_ these letters below.

For example, I could type **firstl** like this:

![image](https://user-images.githubusercontent.com/9964305/132496845-807d5faf-4528-4922-9b61-d17d9e344f8a.png)

And the list would be reduced and look like:
- firstletter.md
- firstline.md
- bigfirstlemon.md

It would be very useful in Collectives where making links is key, as explained in https://gitlab.com/collectivecloud/collectives/-/issues/237#note_672059570

**Comment by biva** [comment]
Hello @szaimen , I see that you added the _needs info_ tag, happy to provide more detail if needed :)

**Comment by biva** [comment]
Just a short email to un-stale this topic, as I understand that @jancborchardt likes the idea :)

**Comment by mejo-** [comment]
Given that we have the smart picker that allows to search for files now, I'll close this issue.

@biva with Nextcloud 26, you will be able to search for and link several resources with the `/` command in Text, among them being files and Collectives pages.
