### ISSUE TITLE
Streaming a video through a shared link with Nextcloud results into too many logs

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/server#28826]
NC Server Version : 21.0.4
PHP: 7.4.3

How to reproduce:

- Share a video through a public unresitricted link
- Open this link with a browser not logged into the nextcloud system
- Klick on a video to start streaming in within the browser
- you will see multiple logs "video have been downloaded" in the activity logs ==> bad

**Comment by szaimen** [comment]
Duplicate of https://github.com/nextcloud/activity/issues/519
