### ISSUE TITLE
Update from 21.0.4 to 22.1.1 not show on stable channel

### ISSUE THREAD

**Issue by tsumi** [nextcloud/server#28825]
### Steps to reproduce
1. Nextcloud 21.0.4, go to Settings > Overview
2. Is stable channel is selected no update is show, selecting beta channel update to 22.1.1 is show
3. I currently experience this issue on 3 different installation, on 2 different servers

### Expected behaviour
As I understand NC 22.1.1 is current stable version, as shown on download page https://nextcloud.com/install/#instructions-server

### Actual behaviour
NC 22.1.1 is only show on beta channel

### Server configuration

**Operating system:** CentOs 7

**Web server:** apache 2.4

**Database:** MariaDB 10.5.12-1

**PHP version:** 7.4.23

**Nextcloud version:** 21.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from NC 20

**Where did you install Nextcloud from:** manual install from zip package

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - bruteforcesettings: 2.2.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dav: 1.17.1
  - deck: 1.4.4
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - impersonate: 1.8.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - metadata: 0.14.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - onlyoffice: 7.1.2
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - ransomware_protection: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - spreed: 11.3.1
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - dashboard
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.tsumi.it"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/xxx.redacted.xxx",
        "dbtype": "mysql",
        "version": "21.0.4.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mysql.utf8mb4": true,
        "versions_retention_obligation": "auto, 30",
        "app_install_overwrite": [
            "impersonate"
        ],
        "data-fingerprint": "0f3a542eec8d46e1b69783f95338761c",
        "updater.release.channel": "stable",
        "default_phone_region": "IT"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 91.0.2

**Operating system:** Fedora 33

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Tue Sep 14 11:11:54.842609 2021] [access_compat:error] [pid 2790] [client 5.179.179.131:25304] AH01797: client denied by server configuration: /home/xxx/public_html/xxx/cloud/data/.ocdata
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
no errors
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
n/a
```
</details>

**Comment by szaimen** [comment]
Hi, this is expected as currently only 30% of the instances get the update to 22.1.1 offered. See https://github.com/nextcloud/updater_server/blob/11275c219b6972419666860e0294749b13a982e5/config/config.php#L127-L128

Please refer for further help to https://help.nextcloud.com
Thanks!
