### ISSUE TITLE
Files downloaded from preview modal dialog do not use `downloadStartSecret` in the download request

### ISSUE THREAD

**Issue by diego-treitos** [nextcloud/server#28821]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Preview of a file (i.e. an image)
2. Click on the 3 dots upper right corner and select "Download"
3. The file gets downloaded without the `downloadStartSecret` parameter so the file can be cached by intermediate proxy cache.

### Expected behaviour
The file should use the `downloadStartSecret` just like when you download the file from the file list. That way you prevent the file from being cached to an intermediate cache and therefor being available without authentication. This could be considered a security problem.

### Actual behaviour
The files downloads directly without the `downloadStartSecret` and it gets cached in an intermediate proxy cache. Knowing the path to the file (i.e. from a screenshot) can make it available to anyone as it can be downloaded from the proxy cache.

### Server configuration

**Operating system:** Debian 10

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 7.3

**Nextcloud version:** 21.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from Nextcloud

**Where did you install Nextcloud from:** From official tarball

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** Firefox

**Operating system:** Ubuntu

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Url to download a file (from viewer -> download) is something like: `http://server/remote.php/dav/files/admin/4k-wallpaper-architecture-bird-s-eye-view-2246476%20(copy%203).jpg`

Access resource via basic auth: `curl -I "http://admin:admin@server/remote.php/dav/files/admin/4k-wallpaper-architecture-bird-s-eye-view-2246476%20(copy%203).jpg"`

```
HTTP/1.1 200 OK
Date: Mon, 13 Sep 2021 21:07:00 GMT
Server: Apache/2.4.38 (Debian)
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Last-Modified: Tue, 24 Aug 2021 12:54:32 GMT
ETag: "f35e33ad3f14750b34070931cb1cf5d4"
Content-Length: 3990379
OC-ETag: "f35e33ad3f14750b34070931cb1cf5d4"
Content-Type: image/jpeg
```

Isn't it a configuration error when the intermediate proxy ignore no-cache?

**Comment by diego-treitos** [comment]
Well, you can say it is a configuration error but unfortunately many web apps (i.e. wordpress) miss-use the no-cache so some proxy-caches just ignore the no-cache, specially for static files.

I guess that that is the reason why you get `downloadStartSecret` parameter with a random value when you download from the file list. I think that downloading from the preview, the behavior should be the same.

**Comment by kesselb** [comment]
cc @nextcloud/security :eyes:

**Comment by LukasReschke** [comment]
The `downloadStartSecret` is not supposed to act as a security control and is merely a wrongly named variable name. If an intermediate proxy ignores `no-cache` that is a misconfiguration that needs to be fixed.
