### ISSUE TITLE
Comments details of files failed with status code 404

### ISSUE THREAD

**Issue by martinelkb** [nextcloud/server#28836]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Another user comments a shared file in the browser-App
2. Click on the little comment-Icon in the file list

### Expected behaviour
The comment history of the file should be shown 

### Actual behaviour
Error message shown in the right column 
Browser Console shows: `Error while loading the file data Error: Request failed with status code 404` 

### Server configuration

**Operating system:**

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** Nextcloud 21.0.3

**Comment by szaimen** [comment]
Hi, can you still repeoduce this on 21.0.4?

**Comment by martinelkb** [comment]
I testet in Nextcloud 22 (nextcloud 22.1.1) the issue was gone

**Comment by szaimen** [comment]
Thanks for the feedback
