### ISSUE TITLE
trailing slash missing regarding http https redirecting 

### ISSUE THREAD

**Issue by ymk201** [nextcloud/server#28846]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Get domain
2. Edit apache2/site-available/my.conf
3. samsung galaxy default internet app.
4. type "http://myDomain"
5. automatically redirect to "https://mydominindex.php" // The trailing slash("/") is missing between myDomain and index.php
     NG : https://mydominindex.php
     OK : https://mydomin/index.php

### Expected behaviour
Proper redirecting.
This might be a problem of samsung.
Could anyone can explain this problem?? (i am not familiar with web services)

### Actual behaviour
NG : samsung galaxy(S20 FE) default internet app // up to date
OK : samsung galaxy(S20 FE) chrome
OK : ubuntu desktop chrome 
OK : ubuntu desktop firefox

### Server configuration
<VirtualHost *:80>
        DocumentRoot /var/www/myRoot/
        ServerName myDomain
        Redirect permanent "/" "https://myDomain/"

        ErrorLog ${APACHE_LOG_DIR}/yongCloud.error
        CustomLog ${APACHE_LOG_DIR}/yongCloud.access combined

        <Directory /var/www/myRoot/>
            Require all granted
            Options FollowSymlinks MultiViews
            AllowOverride All

           <IfModule mod_dav.c>
               Dav off
           </IfModule>

        SetEnv HOME /var/www/myRoot
        SetEnv HTTP_HOME /var/www/myRoot
        Satisfy Any

       </Directory>

</VirtualHost>

<VirtualHost *:443>
        ServerName myDomain
        SSLEngine on
        SSLCertificateFile /etc/ssl/mycertificate.crt
        SSLCertificateKeyFile /etc/ssl/myprivate.key
        Documentroot /var/www/myRoot/
        
    <IfModule mod_headers.c>
      Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"
    </IfModule>
 </VirtualHost>

**Operating system:**
ubuntu 20.04

**Web server:**
apache 2.4.41

**Database:**

**PHP version:**
7.4.3

**Nextcloud version:** (see Nextcloud admin page)
20.0.8
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
