### ISSUE TITLE
Size of folders and modified date is not showing when Storage is on Amazon S3

### ISSUE THREAD

**Issue by santosh-goundar** [nextcloud/server#28845]
When we have External Storage configured for Amazon S3, the folders are not showing their size, instead they show Pending and modified date\time says seconds ago, I see the same behavior in Amazon S3, but I can see the sizes if I click on Action and then click to see the see the total size, so I think it has to do with the API.

even we checked by upgrading NC version to 21.0.4, let me know if any further information required

Server configuration
Operating system: Linux 5.4.0-1039-aws x86_64
PHP version: 7.4.16
Nextcloud version: 20.0.8

**Comment by szaimen** [comment]
Could you try if running `occ files:scan --all` fixes this?

**Comment by santosh-goundar** [comment]
tried running above command, still same issue, having problem with folders which are stored on S3 bucket, please let me know if any further details required.

**Comment by szaimen** [comment]
Sounds like https://github.com/nextcloud/server/issues/16640 can you confirm?

**Comment by santosh-goundar** [comment]
kind of, its not showing at all in first place, not only modified date also having issue with folder size says "pending" for every folder

**Comment by szaimen** [comment]
> its not showing at all in first place, not only modified date also having issue with folder size says "pending" for every folder

So then were you able to run the command `occ files:scan --all` successfully or did it return any error message?

**Comment by santosh-goundar** [comment]
was able to run it successfully without any error message.

**Comment by szaimen** [comment]
> was able to run it successfully without any error message.

And it still shows `Pending` also after a refresh?

**Comment by santosh-goundar** [comment]
yes, it does

**Comment by szaimen** [comment]
Strange. Could you send your nextcloud.log? Maybe something useful is logged there?

**Comment by santosh-goundar** [comment]
i will share it, but does it due to S3 as external storage, as S3 also doesnt show it for folder on its console

**Comment by szaimen** [comment]
I think S3 should actually work...

**Comment by santosh-goundar** [comment]
log file will be huge to share, can you please confirm which particular stack needs to be shared

**Comment by szaimen** [comment]
> can you please confirm which particular stack needs to be shared

anything external storage, files scan, backgroundjobs or s3 related.

**Comment by santosh-goundar** [comment]
[NextCloud Logs.zip](https://github.com/nextcloud/server/files/7185401/NextCloud.Logs.zip)

please let me know if these are the one which you are looking for

**Comment by santosh-goundar** [comment]
can you confirm where logs for external apps like S3 are stored

**Comment by acsfer** [comment]
Similar to https://github.com/nextcloud/server/issues/7420

**Comment by szaimen** [comment]
Thanks, then lats track this in #7420
