### ISSUE TITLE
make public file links editable

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#2886]
You can share a public folder and make it editable. That way, people can edit for example a odt file or a spreadsheet. But a individual link can't be made editable, hence people only ever get a read-only Collabora Online view.

It'd be great to have a 'allow editing' checkbox for individual file public links too. It only makes sense on files which are editable, perhaps - but if you would allow an anonymous file share to be synced with the client https://github.com/owncloud/client/issues/3938 - it would be useful on ANY file, I suppose.

**Comment by rullzer** [comment]
This is fixed in master
