### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by heyanbing** [nextcloud/server#28870]
The logs：
[Fri Sep 17 07:03:58.680782 2021] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.5. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.5. Set the 'ServerName' directive globally to suppress this message
[Fri Sep 17 07:17:17.535712 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.3.14 configured -- resuming normal operations
[Fri Sep 17 07:17:17.535838 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
192.168.0.108 - - [17/Sep/2021:07:17:22 +0000] "GET / HTTP/1.1" 500 503 "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36"
192.168.0.108 - - [17/Sep/2021:07:17:25 +0000] "GET /favicon.ico HTTP/1.1" 500 503 "http://192.168.0.128:8088/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36"

**Comment by acsfer** [comment]
This seems more a server configuration error than a Nextcloud bug. Use Git for bugs only, please.
Please go to https://help.nextcloud.com for such errors.

**Comment by heyanbing** [comment]
> This seems more a server configuration error than a Nextcloud bug. Use Git for bugs only, please.
> Please go to https://help.nextcloud.com for such errors.

thanks！
I've been using it for more than a year. I suddenly couldn't visit it a few days ago
