### ISSUE TITLE
 NC11: Please ask for confirmation before deleting external storage!

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/server#2888]
### Steps to reproduce
1. Add an external storage
2. Klick on the delete icon
![4eb50b2f0a478fe53283c8bd5fa8787162fa7737](https://cloud.githubusercontent.com/assets/24833757/21570695/d5a1daf6-cec8-11e6-8d16-3d9b075008fb.png)

### Expected behaviour
Should confirm before deleting an external storage.

### Actual behaviour
It simply deletes an external storage without any confirmation.

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MariaDB + Redis

**PHP version:**
7.08

**Nextcloud version:** (see Nextcloud admin page)
11.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 10.x

**Are you using external storage, if yes which one:** local/smb/sftp/...
SFTP
Google
Dropbox
FTP
Samba

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

**Comment by powerpaul17** [comment]
Owncloud/nextcloud always deletes everything without confirmation. It is some sort of new usability paradigm nowadays, I guess, confirmation dialogs are "bad".

**Comment by MorrisJobke** [comment]
@jancborchardt @icewind1991 @ChristophWurst I guess we should include an undo here too, right?

**Comment by Sanookmakmak** [comment]
> Owncloud/nextcloud always deletes everything without confirmation. It is some sort of new usability paradigm nowadays, I guess, confirmation dialogs are "bad".

The desktop sync client removes the folder of the external storage after removing the external storage, so an confirmation would be not so bad i think.

**Comment by jancborchardt** [comment]
Since the whole undo thing takes longer I guess, we can put in a confirmation dialog? :/
