### ISSUE TITLE
"You don’t have permission to upload or create files here" & unable to view files after successful WebDAV "External Storage" mount

### ISSUE THREAD

**Issue by Sgt-Nukem** [nextcloud/server#28890]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Have a Bitrix24 cloud drive - accessible via WebDAV
2. Make a folder there, click "Gear Icon" and "Network Drive": see the WebDAV URL to connect "https://{identifier}.bitrix24.de/company/personal/user/1/disk/path/{folder-name}"
3. As NextCloud Admin, under Settings->Administration->External Storage enable "Allow users to mount external storage" and enable just "WebDAV"
4. Logout as Admin and re-login as regular user
5. Under Settings->External Storage add a new WebDAV mount with the URL from above, "secure https" enabled and the Bitrix username and password
6. See there is a green checkmark - the mounting succeeded
7. Go to "Files->All files" and into the mounted folder - there is "No files in here" displayed along with "You don’t have permission to upload or create files here" at the top

INFO: Connecting with the same URL and username/password from Windows Explorer with "Add a network location" succeeds and shows the remote folder. Adding folders and files works as expected.
In NextCloud the folder still just displays "No files in here".

### Expected behaviour
I want to see my external files and put new files there via NextCloud.

**Nextcloud version:** (see Nextcloud admin page)
22.1.1 - fresh install

If you need any log files tell me which and where to find them please.

**Comment by NixFull** [comment]
Hello i got the same problem 
"You don’t have permission to upload or create files here" 
is a fresh install too

**Comment by EduardoOsquel** [comment]
Im having the same issue, but in my case, i have one system working behind an LDAP user list, but, some of my users, i mean two or  three have not permission to create files... by the way, when i study the structure of those users folders they have used 4,5 MB the other without any issue have 0 MB used, what could be happening here?

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
