### ISSUE TITLE
Update fails if 'lost+found' exists in data directory

### ISSUE THREAD

**Issue by c-schwamborn** [nextcloud/server#28904]
### Steps to reproduce
1.Update 21.0.x to 21.0.4 with a mounted filesystem (containing 'lost+found') at nextcloud/data

### Expected behaviour
it works

### Actual behaviour
it fails - complaining about 'access denied' errors, as 'lost+found' belongs to root in any case as it should be.

**Comment by kesselb** [comment]
We assume to have full control about the data directory. As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

**Comment by c-schwamborn** [comment]
This isn't a setup issue.
During the update, nexcloud performs a backup in which it fails to access those 'lost+found' folders, common to linux filesystems.
As i usually store userdata appart from other stuff on seperate filesystems, */nextcloud/data is a filesystem by itself, having such a 'lost+found' owned by root (mod: 700).
The backup process, running as www-data should simply ignore those folders. Sure you can delete them, but fsck will complain about it and recreate them.
Btw. why was this transfered to nextcloud/calendar?

**Comment by kesselb** [comment]
Again: We assume to have full control about the data directory. Put your data directory in a subdirectory and you are good. Or use the manual way to update Nextcloud.
