### ISSUE TITLE
Update to NC 11 seems to break integration with Gnome

### ISSUE THREAD

**Issue by despens** [nextcloud/server#2890]
### Steps to reproduce
1. Open Gnome Online Accounts
2. Add new "owncloud" account (nextcloud not available) by adding URL of the server
3. Tick all boxes to integrate calendars, contacts, documents and files 

### Expected behaviour
Gnome desktop apps should use nextcloud as a data source

### Actual behaviour
Since NC11, integration with gnome contacts and calendars is not working anymore.

### Server configuration
**Operating system**: Ubuntu 16.04 LTS

**Web server:** Server version: Apache/2.4.18 (Ubuntu)
Server built:   2016-07-14T12:32:26

**Database:** Server version: 10.0.28-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04

**PHP version:** PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )

**Nextcloud version:** 11.0.0 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 10.0.2

**Where did you install Nextcloud from:** tar.bz

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
# sudo -u www-data php occ app:list
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - announcementcenter: 3.0.0
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - direct_menu: 0.9.3
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_external: 1.1.2
  - files_markdown: 1.0.0
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextant: 1.0.1
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.1.2
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.4
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - files_pdfviewer
  - files_retention
  - user_ldap
  - user_saml

```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "51e29b69eaed2",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/nextcloud",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "sendmail",
        "forcessl": true,
        "loglevel": 0,
        "overwrite.cli.url": 1,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "blacklisted_files": [],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\SVG",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trashbin_retention_obligation": "auto",
        "mail_from_address": "robobot",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "appstore.experimental.enabled": true,
        "updater.release.channel": "stable"
    }
}

```
</details>

**Are you using external storage, if yes which one:** sftp

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration
**Browser:** GNOME Shell 3.18.5

**Operating system:** Ubuntu 16.04 LTS

#### Web server error log
<details>
<summary>Web server error log</summary>

```
1.2.3.4 - - [30/Dec/2016:10:38:44 +0000] "OPTIONS /remote.php/webdav HTTP/1.1" 401 4677 "-" "gvfs/1.28.2"
1.2.3.4 - despens [30/Dec/2016:10:39:18 +0000] "OPTIONS /remote.php/caldav/calendars/user/waste-management/ HTTP/1.1" 404 4720 "-" "Evolution/3.18.5"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
	Sabre\DAV\Exception\NotAuthenticated: HTTP/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured

    [internal function] Sabre\DAV\Auth\Plugin->beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466: Sabre\Event\EventEmitter->emit('beforeMethod', Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 60: Sabre\DAV\Server->exec()
    /var/www/nextcloud/remote.php - line 165: require_once('/var/www/nextcl...')
    {main}
```
</details>

**Comment by jancborchardt** [comment]
@despens @der-Daniel with the next version of GNOME, it will be switched to Nextcloud. :)
Thanks to @debarshiray & @jimmac of GNOME for making it happen! :heart: 

But even then, Nextcloud should work fine too, since it’s all WebDAV. Any idea @debarshiray?

**Comment by flortsch** [comment]
It's working for me with Gnome 3.22 at least.
Also related to #3006 I guess.

**Comment by debarshiray** [comment]
There shouldn't be any change between GNOME 3.18 and 3.22 regarding this. The GNOME components expect the following endpoints:
  (a) WebDAV: /remote.php/webdav/
  (b) CalDAV: /remote.php/caldav/
  (c) CardDAV: /remote.php/carddav/

Are those endpoints working? You can point a web browser at them to do a basic smoke test.

Can you browse your ownCloud files using Nautilus?

**Comment by despens** [comment]
The problem has disappeared with upgrade to 11.0.2 (stable)

**Comment by jancborchardt** [comment]
Thanks for testing! Closing hence. :)
