### ISSUE TITLE
Can’t install nextcloud with external DB

### ISSUE THREAD

**Issue by noor-alghamdi** [nextcloud/server#28913]
Hello everyone,
I’m trying to install nextcloud using external db,
but is keeps throwing error :
SQLSTATE[HY000] [2006] MySQL server has gone away

I modefied the config.php file:

`<?php $CONFIG = array ( 'instanceid' => ' ', 'passwordsalt' => ' ', 'secret' => ' ', 'trusted_domains' => array ( 0 => ' ', ), 'datadirectory' => '/var/www/html/nextcloud/data', 'dbtype' => 'mysql', 'version' => '22.1.1.2', 'overwrite.cli.url' => ' ', 'dbname' => 'nextcloud', 'dbhost' => 'ip:3306', 'dbport' => '', 'dbuser' => ' ', 'dbpassword' => ' ', 'dbtableprefix' => 'oc_', ); ~
`

 can you help me please!

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
