### ISSUE TITLE
update fails 

### ISSUE THREAD

**Issue by tomkhlr** [nextcloud/server#28926]
Update from 21.0.1 to 21.0.4 fails with the following exception:
Exception: App "News" cannot be installed because the following dependencies are not fulfilled: 64bit or higher PHP required.
Hardware raspberry pi 3b+

**Comment by szaimen** [comment]
Duplicate of https://github.com/nextcloud/news/issues/1481

**Comment by cClaude** [comment]
This is not really a duplicate.

Nextcloud server should not start migration at all or disable "news" application.
