### ISSUE TITLE
REDIS_MINIMAL_VERSION, Redis connect method mismatch

### ISSUE THREAD

**Issue by selyod-ka** [nextcloud/server#28932]
After upgrading NC-21 -> NC-22 redis-connect fails with the warning:

Warning: Redis::connect() expects at most 5 parameters

and then unhandled exception.

The reason is that 
  `$this->instance->connect($host, $port, $timeout);`
changed to 
  `$this->instance->connect($host, $port, $timeout, null, 0, $readTimeout);` 
in lib/private/RedisFactory.php. This is inconsistent with 
  `public const REDIS_MINIMAL_VERSION = '2.2.5';`
(same file).
For example, phpredis 3, expects:

> ### connect, open
> -----
> _**Description**_: Connects to a Redis instance.
> 
> ##### *Parameters*
> 
> *host*: string. can be a host, or the path to a unix domain socket
> *port*: int, optional
> *timeout*: float, value in seconds (optional, default is 0 meaning unlimited)
> *reserved*: should be NULL if retry_interval is specified
> *retry_interval*: int, value in milliseconds (optional)

I.e. there are 5 parameters defined, not 6.

Please, either state/ check the minimal version of phpredis or modify the connection method.
Thanks!

**Comment by kesselb** [comment]
Thanks :+1: 

Fix #28933

**Comment by selyod-ka** [comment]
Thank you!
