### ISSUE TITLE
Can not change Default Dashboard Background

### ISSUE THREAD

**Issue by xbluemonkx** [nextcloud/server#28940]
Hi,

based on this ticket https://github.com/nextcloud/server/pull/23588 it should be possible to easily change the default background image in the themeing app, but this option is not available in my nextcloud. 

I can change the image for the login screen but there are not adjustable setting to change the dashboard image.

**Comment by szaimen** [comment]
The dashboard will use the login screen image as background if set.

**Comment by xbluemonkx** [comment]
Hi,
that did not work for me. Default Dashboard Background was different to login background.

Started using the custom CSS workaround: https://help.nextcloud.com/t/changing-the-dashboards-default-background-image/95562/5
