### ISSUE TITLE
Login to web interface with phone / app / qr-code

### ISSUE THREAD

**Issue by PhoenixIV** [nextcloud/server#28961]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I use a quite complex password and it's a hassle to type when I log into my NextCloud regularly from various machines.

**Describe the solution you'd like**
I am looking for a way to authenticate a web login with my mobile app.

**Describe alternatives you've considered**
I have seen the link "Login with a device", but, right now, this seems to only refer to things like YubiKey.

**Comment by szaimen** [comment]
Hi there, login with qr code is alread possible. See 
https://docs.nextcloud.com/server/stable/user_manual/en/pim/sync_android.html?highlight=device%20password#files-and-notifications
![Screenshot_20210926-135235_Brave](https://user-images.githubusercontent.com/42591237/134806681-589cdb63-5c44-4726-8a9f-46aecce2561c.png)

**Comment by PhoenixIV** [comment]
@szaimen your suggestion seems to be the wrong way round: I ask to be able to log in to NextCloud web with my phone. You, as I see it, offer to log into the android app using the web GUI.

**Comment by PhoenixIV** [comment]
@szaimen @kesselb This issue was wrongfully closed. Please review.
