### ISSUE TITLE
PHP fatal error due to PSR-11 

### ISSUE THREAD

**Issue by evolozzy** [nextcloud/server#28972]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Upgraded Ubuntu 20.04 on Sep 27, 2021
2.
3.

### Expected behaviour
The server should have worked properly

### Actual behaviour
The server stopped working, when I tried running `occ` I got the error:
```
PHP Fatal error:  Declaration of OC\AppFramework\Utility\SimpleContainer::get(string $id) must be compatible with Psr\Container\ContainerInterface::get($id) in  .../lib/private/AppFramework/Utility/SimpleContainer.php on line 55
```

Changing the lines 55 and 59 from `(string $id)` to `(id)` seems to fix the problem, of course the hash of that file changes and the integrity check results in an error. 
This was helpful when solving the problem. [https://www.php-fig.org/psr/psr-11/](https://www.php-fig.org/psr/psr-11/)

### Server configuration

**Operating system:**
Ubuntu 20.04
**Web server:**
Apache 2.4.41
**Database:**

**PHP version:**
Php 7.4.3 
**Nextcloud version:** (see Nextcloud admin page)
22.1.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
Has been updating since NC11
**Signing status:**
<details>
<summary>Signing status</summary>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- lib/private/AppFramework/Utility/SimpleContainer.php

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [lib/private/AppFramework/Utility/SimpleContainer.php] => Array
                        (
                            [expected] => 5e2725313fa0dcf16f45bae9e0c4fd442a4f525924e8f2dd83be7da4e2e71daac396a79a8d12aad9d93d144c235b5f59d60ec7b015c82ffb4f700fc46ddb8e5b
                            [current] => f752392a717e83a15d19347b4b3c095ff32e51d8b55810f1170e0c0c983d6293abb7f98fa396f90262dbe2acca0076ea45826fb7772d0ed13c39eee48de7a807
                        )

                )

        )

)

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.7.0
  - activity: 2.15.0
  - admin_audit: 1.11.0
  - announcementcenter: 6.0.0
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.3
  - circles: 22.1.1
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 4.0.3
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.18.0
  - deck: 1.5.3
  - documentserver_community: 0.1.11
  - encryption: 2.9.0
  - external: 3.9.0
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_accesscontrol: 1.12.0
  - files_automatedtagging: 1.12.0
  - files_external: 1.12.1
  - files_pdfviewer: 2.3.0
  - files_retention: 1.11.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.13.2
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - forms: 2.3.0
  - groupfolders: 10.0.0
  - impersonate: 1.9.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.9.0
  - maps: 0.1.9
  - news: 16.0.1
  - nextcloud_announcements: 1.11.0
  - notes: 4.1.1
  - notifications: 2.10.1
  - oauth2: 1.9.0
  - onlyoffice: 7.1.2
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.11.0
  - ransomware_detection: 0.10.0
  - ransomware_protection: 1.11.0
  - serverinfo: 1.12.0
  - settings: 1.3.0
  - spreed: 12.1.2
  - survey_client: 1.10.0
  - suspicious_login: 4.0.0
  - systemtags: 1.11.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.12.0
  - twofactor_admin: 3.1.0
  - twofactor_backupcodes: 1.10.1
  - twofactor_totp: 6.1.0
  - twofactor_u2f: 6.2.0
  - updatenotification: 1.11.0
  - user_saml: 4.1.1
  - user_status: 1.1.1
  - viewer: 1.6.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.1
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.evolozzy.net",
            "10.239.157.7",
            "192.168.73.6"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.evolozzy.net\/",
        "version": "22.1.1.2",
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "default_language": "en",
        "default_locale": "en_US",
        "default_phone_region": "US",
        "defaultapp": "files",
        "knowledgebase": "true",
        "allow_user_to_change_display_name": true,
        "installed": true,
        "maintenance": false,
        "loglevel": 0,
        "updater.release.channel": "stable",
        "theme": "",
        "overwritehost": "cloud.evolozzy.net",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "htaccess.RewriteBase": "\/",
        "proxy": "",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "login_form_autocomplete": false,
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "app_install_overwrite": [
            "calendar",
            "social",
            "twofactor_totp",
            "twofactor_admin",
            "ransomware_detection"
        ],
        "data-fingerprint": "9e6d5e6594d3810c54b120670fe0efbb",
        "appcodechecker": true,
        "preview_max_x": 512,
        "preview_max_y": 512,
        "preview_max_scale_factor": 1,
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Webdav

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1: 

Would you mind to edit your post and add the [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)? The information are required to reproduce your issue.

Most likely that's somehow related to an app.

**Comment by evolozzy** [comment]
The issue is in the core, and it occurs due to PHP-FIG PSR-11 Contaniner implementation. It has to be defined as `get($id)` and `has($id)`, instead they are defined as `get(string $id)` and `has(string $id)`. Fixing lines 55 and 59 accordingly in `lib/private/AppFramework/Utility/SimpleContainer.php` fixes the problem. The server with that change is working fine now. I also put the relevant manual as the link above. I don't see the relevance of my logs here.

**Comment by kesselb** [comment]
> The issue is in the core, 

I agree it looks like an issue in server. 

1) https://github.com/nextcloud/server/blob/v22.1.1/lib/private/AppFramework/Utility/SimpleContainer.php#L55-L62
2) https://github.com/nextcloud/3rdparty/blob/v22.1.1/psr/container/src/ContainerInterface.php

1 is the class implementing the interface and 2 the definition of the interface. Both are using a string type hint for $id. 


> and it occurs due to PHP-FIG PSR-11 Contaniner implementation. 

I guess an app is using the container interface as dependency in a wrong version. To validate move all non shipped apps (list of shipped apps https://github.com/nextcloud/server/blob/v22.1.1/core/shipped.json) from the apps directory to somewhere else and restore the type hint.

3) Check if error is gone
4) Move back one app
5) Check if error is gone
6) Move back another app
7) ...

**Comment by evolozzy** [comment]
1. Moved all the apps
2. Run 'occ' 
3. Error persists
4. Downloaded a fresh server folder
5. Run 'occ'
6. The result is the same.
7. Made the above-mentioned changes
8. Works fine

**Comment by evolozzy** [comment]
Found the reason! I had packages `php-psr` and `php-psr-container` installed, removing the packages it solved the problem.

**Comment by evolozzy** [comment]
Now solving the problem I have, I also checked on a fresh install of Ubuntu 20.04. When `php-psr` package is installed it causes the fatal error.

Should there be an open issue on "Installing `php-psr` package causes PHP fatal error on Ubuntu 20.04" or something?

**Comment by kesselb** [comment]
> Should there be an open issue on "Installing php-psr package causes PHP fatal error on Ubuntu 20.04" or something?

I don't know if there is a solution to this problem. The php-psr package is installed to the default include path and loaded/available for each php application then. I guess that makes sense if one maintains a apt package for a php application and manage the dependencies for the php application also via apt.
