### ISSUE TITLE
after NC update to the Version 21.0.4.1 Error: Cannot modify header information - headers already sent by

### ISSUE THREAD

**Issue by alghanim-lab** [nextcloud/server#28985]
After I updated NC Instance to the latest version 21.0.4.1 I unfortunately have many problems that I can not log in from the phone with the App NextCloud (IOS). This is happening after I have logged out and then tried again to login . then I looked in Logging and I found this error message:
![Unbenannt](https://user-images.githubusercontent.com/45328993/135241006-d69e94e1-9b95-47d8-97e8-be70a88cc556.JPG)

**Comment by alghanim-lab** [comment]
{"reqId":"YVQwPOA4MVU9xAquQa5d6gAAAFg","level":3,"time":"2021-09-29T09:22:04+00:00","remoteAddr":"87.79.112.69","user":"Hussen","app":"no app in context","method":"PUT","url":"/remote.php/webdav/InstantUpload/WhatsApp%20Images/IMG-20210928-WA0022.jpg","message":{"Exception":"Sabre\\DAV\\Exception\\BadRequest","Message":"Expected filesize of 101801 bytes but read (from Nextcloud client) and wrote (to Nextcloud storage) 8192 bytes. Could either be a network problem on the sending side or a problem writing to the storage on the server side.","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":156,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1098,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["IMG-20210928-WA0022.jpg",null]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":504,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["InstantUpload/WhatsApp Images/IMG-20210928-WA0022.jpg",null,null]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PUT",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php","line":84,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","Line":246,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.17.0","version":"21.0.4.1","id":"6154303deff05"}

**Comment by alghanim-lab** [comment]
{"reqId":"YVQwPOA4MVU9xAquQa5d6gAAAFg","level":3,"time":"2021-09-29T09:22:04+00:00","remoteAddr":"87.79.112.69","user":"Hussen","app":"PHP","method":"PUT","url":"/remote.php/webdav/InstantUpload/WhatsApp%20Images/IMG-20210928-WA0022.jpg","message":{"Exception":"Error","Message":"fread(): Unable to create temporary file, Check permissions in temporary files directory. at /var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php#55","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"fread(): Unable to create temporary file, Check permissions in temporary files directory.","/var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php",55,{"count":8192}]},{"file":"/var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php","line":55,"function":"fread","args":[null,8192]},{"file":"/var/www/nextcloud/lib/private/Files/Stream/HashWrapper.php","line":64,"function":"stream_read","class":"Icewind\\Streams\\Wrapper","type":"->","args":[8192]},{"function":"stream_read","class":"OC\\Files\\Stream\\HashWrapper","type":"->","args":[8192]},{"file":"/var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php","line":55,"function":"fread","args":[null,8192]},{"file":"/var/www/nextcloud/lib/private/Files/Stream/HashWrapper.php","line":64,"function":"stream_read","class":"Icewind\\Streams\\Wrapper","type":"->","args":[8192]},{"function":"stream_read","class":"OC\\Files\\Stream\\HashWrapper","type":"->","args":[8192]},{"file":"/var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php","line":55,"function":"fread","args":[null,8192]},{"file":"/var/www/nextcloud/lib/private/Files/Stream/HashWrapper.php","line":64,"function":"stream_read","class":"Icewind\\Streams\\Wrapper","type":"->","args":[8192]},{"function":"stream_read","class":"OC\\Files\\Stream\\HashWrapper","type":"->","args":[8192]},{"file":"/var/www/nextcloud/3rdparty/icewind/streams/src/Wrapper.php","line":55,"function":"fread","args":[null,8192]},{"file":"/var/www/nextcloud/3rdparty/icewind/streams/src/CallbackWrapper.php","line":96,"function":"stream_read","class":"Icewind\\Streams\\Wrapper","type":"->","args":[8192]},{"function":"stream_read","class":"Icewind\\Streams\\CallbackWrapper","type":"->","args":[8192]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Local.php","line":282,"function":"file_put_contents","args":["/media/ssd/data/Hussen/files/InstantUpload/WhatsApp Images/IMG-20210928-WA0022.jpg.ocTransferId1405749728.part",null]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Local.php","line":570,"function":"file_put_contents","class":"OC\\Files\\Storage\\Local","type":"->","args":["files/InstantUpload/WhatsApp Images/IMG-20210928-WA0022.jpg.ocTransferId1405749728.part",null]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":629,"function":"writeStream","class":"OC\\Files\\Storage\\Local","type":"->","args":["files/InstantUpload/WhatsApp Images/IMG-20210928-WA0022.jpg.ocTransferId1405749728.part",null,null]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":629,"function":"writeStream","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/InstantUpload/WhatsApp Images/IMG-20210928-WA0022.jpg.ocTransferId1405749728.part",null,null]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","line":207,"function":"writeStream","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files/InstantUpload/WhatsApp Images/IMG-20210928-WA0022.jpg.ocTransferId1405749728.part",null]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":156,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1098,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["IMG-20210928-WA0022.jpg",null]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":504,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["InstantUpload/WhatsApp Images/IMG-20210928-WA0022.jpg",null,null]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PUT",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php","line":84,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.17.0","version":"21.0.4.1","id":"6154303df011c"}

**Comment by alghanim-lab** [comment]
one issue is solved:
after i added this line to config file can i login again in the Nextcloud app (iOS) at the mobile
overwriteprotocol => "https"

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
