### ISSUE TITLE
Error on profile picture upload: `imagedestroy()` expects parameter 1 to be resource, bool given

### ISSUE THREAD

**Issue by jroussay** [nextcloud/server#28980]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Open user settings
2. Select an image to upload as profile picture

### Expected behaviour
Image is uploaded

### Actual behaviour
Error 400

### Server configuration

**Operating system:**
Debian 10
**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
7.4
**Nextcloud version:** (see Nextcloud admin page)
22
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from older
**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
nabled:
  - accessibility: 1.7.0
  - admin_audit: 1.11.0
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.3
  - circles: 22.1.1
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 4.0.3
  - contactsinteraction: 1.2.0
  - customproperties: 2.0.4
  - dashboard: 7.1.0
  - dav: 1.18.0
  - drawio: 1.0.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_accesscontrol: 1.12.0
  - files_external: 1.12.1
  - files_fulltextsearch: 22.0.1
  - files_linkeditor: 1.1.6
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.13.2
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - fulltextsearch: 22.0.1
  - fulltextsearch_elasticsearch: 22.0.1
  - groupfolders: 10.0.0
  - impersonate: 1.9.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.9.0
  - mail: 1.10.4
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.9.0
  - onlyoffice: 7.1.2
  - password_policy: 1.12.0
  - photos: 1.4.0
  - polls: 3.2.0
  - privacy: 1.6.0
  - provisioning_api: 1.11.0
  - rainloop: 7.1.2
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.11.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.12.0
  - theming_customcss: 1.9.0
  - twofactor_backupcodes: 1.10.1
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.6.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.1
Disabled:
  - activity
  - encryption
  - richdocuments.back
  - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "62.210.217.176",
            "cloud.cartong.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/cloud.cartong.org",
        "htaccess.RewriteBase": "\/",
        "overwritehost": "cloud.cartong.org",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "22.1.1.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "installed": true,
        "maintenance": false,
        "auth.bruteforce.protection.enabled": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "loglevel": 2,
        "logfile": "\/var\/www\/nextcloud\/data\/nextcloud.log",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "mysql.utf8mb4": true,
        "onlyoffice": {
            "verify_peer_off": true
        },
        "allow_local_remote_servers": true,
        "app_install_overwrite": [
            "calendar"
        ],
        "mail_sendmailmode": "smtp",
        "debug": false,
        "default_phone_region": "FR",
        "updater.release.channel": "stable"
    }
}

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:**
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Brave
**Operating system:**
Ubuntu
### Logs
﻿

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"1OGvjbchF5UxjFdAk0Up","level":3,"time":"2021-09-28T15:18:01+00:00","remoteAddr":"78.207.28.216","user":"","app":"PHP","method":"POST","url":"/avatar/cropped","message":"imagedestroy() expects parameter 1 to be resource, bool given at /data/nextcloud/lib/private/legacy/OC_Image.php#1046","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36","version":"22.1.1.2","exception":{"Exception":"Error","Message":"imagedestroy() expects parameter 1 to be resource, bool given at /data/nextcloud/lib/private/legacy/OC_Image.php#1046","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[2,"imagedestroy() expects parameter 1 to be resource, bool given","/data/nextcloud/lib/private/legacy/OC_Image.php",1046,{"x":0,"y":0,"w":0,"h":0,"process":false}]},{"file":"/data/nextcloud/lib/private/legacy/OC_Image.php","line":1046,"function":"imagedestroy","args":[false]},{"file":"/data/nextcloud/lib/private/legacy/OC_Image.php","line":1023,"function":"cropNew","class":"OC_Image","type":"->","args":[0,0,0,0]},{"file":"/data/nextcloud/core/Controller/AvatarController.php","line":323,"function":"crop","class":"OC_Image","type":"->","args":[0,0,0,0]},{"file":"/data/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"postCroppedAvatar","class":"OC\\Core\\Controller\\AvatarController","type":"->","args":[{"x":"0","y":"0","w":"0","h":"0"}]},{"file":"/data/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\AvatarController"},"postCroppedAvatar"]},{"file":"/data/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\AvatarController"},"postCroppedAvatar"]},{"file":"/data/nextcloud/lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\AvatarController","postCroppedAvatar",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"core.avatar.postCroppedAvatar"}]},{"file":"/data/nextcloud/lib/base.php","line":1000,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/avatar/cropped"]},{"file":"/data/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/data/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"61533229d4bca"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
https://cloud.cartong.org/avatar/cropped
{data: {message: "An error occurred. Please contact your admin."}}
```
</details>

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
