### ISSUE TITLE
Iframe not allowed from federated servers

### ISSUE THREAD

**Issue by Mystikal57** [nextcloud/server#28989]
Hi, 

### Steps to reproduce
1. Share a file from federated server
2. open file on the second server

### Expected behaviour
File should open

### Actual behaviour

Refused to display 'https://cloudremote.blabla.fr/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Nextcloud version:** 22 or 21

**Updated from an older Nextcloud/ownCloud or fresh install: UPDATED

Added domain to EmptyContentSecurityPolicy.php -> everything works fine

related: https://github.com/nextcloud/officeonline/issues/210

Thank you

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

server provide an api for apps to overwrite the content security policy. The officeonline app is already using this: https://github.com/nextcloud/officeonline/search?q=ContentSecurityPolicy

I'm closing this issue for now. We can always reopen when it's a server issue.
