### ISSUE TITLE
Upgrade Issue

### ISSUE THREAD

**Issue by bueste** [nextcloud/server#2898]
Hi all
I've the same issue when I update from command line or from webupdater:

> Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT DISTINCT(TABLE_NAME) AS `table` FROM INFORMATION_SCHEMA . COLUMNS WHERE TABLE_SCHEMA = ? AND (COLLATION_NAME <> 'utf8_bin' OR CHARACTER_SET_NAME <> 'utf8') AND TABLE_NAME LIKE "oc_%"' with params ["nextcloud_db"]: SQLSTATE[HY000]: General error: 1 Can't create/write to file '/var/tmp/#sql_25eb_0.MAI' (Errcode: 2)

> 

Can anyone help?

Thx
Stefan

**Comment by MariusBluem** [comment]
Hi Stefan,

Please fill out the **[issue template](https://github.com/nextcloud/server/blob/master/issue_template.md)** 😅 
Only with this information we are able to reproduce - and help you best 💪 THX!

**Comment by bueste** [comment]
Server configuration

Operating system: Centos 7

Web server: Apache 2.4.6

Database: MariaDB 10.1

PHP version: 7.0.14

Nextcloud version: 11.0 (Upgrade from lastest 10.0 to 11.0)

Updated from an older Nextcloud/ownCloud or fresh install: Updated from 10

Where did you install Nextcloud from:  I use this Howto: https://www.canox.net/2016/12/upgrade-nextcloud-10-0-2-11-0-0/ - of course with the apache user from centos www-data is debian based

List of activated apps:
App list none

The content of config/config.php:
Config report

> 

<?php
$CONFIG = array (
  'instanceid' => 'ocuidqhd0v6x',
  'passwordsalt' =>'passwordsalted',
  'secret' => 'secret',
  'trusted_domains' =>
  array (
    0 => 'server',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'https://url',
  'dbtype' => 'mysql',
  'version' => '9.1.2.2',
  'dbname' => 'nextcloud_db',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud_db',
  'dbpassword' => 'password',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'user',
  'mail_domain' => 'domain',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'smtp.office365.com',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'mail',
  'mail_smtppassword' => 'password',
  'updater.secret' => '$2y$10$nE56YJtob17TZqNItU5SQudmctGDR0BfvJ7ajzQIw.FOKHXVAX2oe',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'updater.release.channel' => 'stable
',
);

> 

Are you using external storage, if yes which one: local/smb/sftp/... no

Are you using encryption: no


Client configuration

Browser:

Operating system:
Logs
Web server error log

Web server error log

Nextcloud log (data/nextcloud.log)

Nextcloud log

Browser log

Browser log

**Comment by MorrisJobke** [comment]
SQLSTATE[HY000]: General error: 1 Can't create/write to file '/var/tmp/#sql_25eb_0.MAI' (Errcode: 2)

We can't do much, when the DB is just dying. Please check your logs of the DB first and try to fix the issues there.

Thanks
