### ISSUE TITLE
Login loop upon fresh install 

### ISSUE THREAD

**Issue by CountOmega** [nextcloud/server#28993]
PHP: 7.4
Apache: 2.4.48
MariaDB: 10.5.11
NC: 21.0.4.1

Config:

```
<?php
$CONFIG = array (
  'instanceid' => 'secret',
  'passwordsalt' => '',
  'secret' => ',
  'trusted_domains' => 
  array (
    0 => 'IP',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '21.0.4.1',
  'overwrite.cli.url' => 'http:/IP/nextcloud',
  'overwriteprotocol' => 'http',
  'overwritehost' => 'IP',
  'htaccess.RewriteBase' => '/nextcloud',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'dbuser',
  'dbpassword' => 'secret',
  'installed' => true,
);
```
Fresh 21.0 install of nextcloud. I could create an account and login. Then I'm trapped in a login loop. My guess is that this has something to do with the overwrite variables.

The url is something like `/nextcloud/login?redirect_url=/nextcloud/apps/dashboard/` but the login page does not disappear.

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

**Comment by Brandon4466** [comment]
Definitely not something to do with there setup. This is still an issue.
