### ISSUE TITLE
Favicon in NC11 not working anymore

### ISSUE THREAD

**Issue by caco3** [nextcloud/server#2900]
(This issue might already be picked up)

Yesterday (30.12.2016) I did a fresh install of NC11 (daily build).
The favicon is not working any more (no icon shown) in a recent Firefox and Chrome under Linux.

**Comment by MariusBluem** [comment]
I can't reproduce this with the current `stable11-daily` 🤔 Could you please check again - 
...and provide a full-filled **[issue template](https://github.com/nextcloud/server/blob/master/issue_template.md)** 😅 THX!

**Comment by caco3** [comment]
A fresh NC11 (Stable) installation has this in the index.php file:
```
<!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="en" >
[...]
		<link rel="icon" href="/owncloud/core/img/favicon.ico">
```
The browsers are showing the favicon as expected.

Looking at the daily index.php file:
```
<!DOCTYPE html>
<html class="ng-csp" data-placeholder-focus="false" lang="en" >
[..]
		<link rel="icon" href="/index.php/apps/theming/favicon?v=0">
```
There is a significant difference.
The favicon seems now to be provided by a theming app.
Clicking on it reloads the page which then additionally has a lot of lines
`<script nonce="cjRWazFhQVRXRDI2dEVrY3h1cEh4b0p1UWVSYUVLTnNFT1BLemMrWWh3OD06Z09zTXZNTitPMi8veFRCMGdxSVFzZWNoZVlFMldkTUVWSnFGdkxiYXhWYz0=" src="/core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=a86b117dd97264c8dee7f1665d4076af"></script>
					`
In the header

### Steps to reproduce
1. Install a daily snapshot of NC11 (>= 30.12.2016)
2. Load NC webpage in browser

### Expected behaviour
Browser should show favicon

### Actual behaviour
No icon shown

### Server configuration
**Operating system**:
FreeBSD
**Web server:**
Appache
**Database:**
Type: mysql
Version: 5.5.53
Size: 51.9 MB
**PHP version:**
Version: 5.6.29
Memory Limit: 512.0 MB
Max Execution Time: 3600
Upload max size: 511.0 MB
**Server version:** (see your admin page)
11.0.0 (daily, 30.12.2016)
**Calendar version:** (see the apps page)
1.4.1
**Updated from an older installed version or fresh install:**
fresh install, migrated DB
**Signing status (ownCloud/Nextcloud 9.0 and above):**
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - direct_menu: 0.9.3
  - external: 1.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notes: 2.1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - files_automatedtagging
  - user_external
  - user_ldap
  - user_saml


**The content of config/config.php:**
{
    "system": {
        "datadirectory": "\/home\/***\/owncloud_***",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "installedat": "1334086349.5631",
        "lastupdatedat": "1334087083.9888",
        "dbname": "***_owncloud",
        "dbhost": "***.mysql.db.internal",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "5083050d6af67",
        "maxZipInputSize": 419430400,
        "allowZipDownload": true,
        "theme": "",
        "maintenance": false,
        "loglevel": 3,
        "trusted_domains": [
            "owncloud.***.ch",
            "www.***.ch",
            "***.ch"
        ],
        "mail_from_address": "owncloud",
        "mail_smtpmode": "php",
        "mail_domain": "***.ch",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto, auto",
        "appstore.experimental.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.release.channel": "stable"
    }
}


**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

**Comment by caco3** [comment]
BTW:  **stable** and **daily** as used in `stable11-daily` looks like a conflict. A daily build never should be expected as stable, right?

**Comment by MorrisJobke** [comment]
> BTW: stable and daily as used in stable11-daily looks like a conflict. A daily build never should be expected as stable, right?

stable11 is the name of the branch ;) and it's a snapshot of this branch ;)

**Comment by MorrisJobke** [comment]
I also can't reproduce this anymore. The mail app for example uses this and it works here just fine.

Maybe @juliushaertl knows this better.

**Comment by juliushaertl** [comment]
Kind of hard to say, especially without reproducing it. 

@caco3 The difference you are describing in the favicon path between the stable release and the daily build might be in your server setup. The Favicons will only be loaded from the theming app when imagick with svg support is present on the server. (See https://docs.nextcloud.com/server/11.0/admin_manual/configuration_server/theming.html?highlight=theming#theming-of-icons)

**Comment by juliushaertl** [comment]
> The mail app for example uses this and it works here just fine.

@MorrisJobke It is not the app using it, it should be there for all apps automatically. :wink:

**Comment by MorrisJobke** [comment]
> @MorrisJobke It is not the app using it, it should be there for all apps automatically. 😉

Yes, but this is the default favicon. The mail app provides a custom favicon - so I thought it could be caused by that custom favicon code ;)

**Comment by caco3** [comment]
@juliabode @MorrisJobke The issue still persists.
I moved my nextcloud folder to nextcloud.old, then downloaded https://download.nextcloud.com/server/releases/nextcloud-11.0.3.zip (note: this is the official release!) and unzipped it.
After the migration (mysql) I enabled the used apps again.

Result:
Favicon is still broken, the index.php file still contains the lines
```
[..]
		<link rel="icon" href="/index.php/apps/theming/favicon?v=0">
		<link rel="apple-touch-icon-precomposed" href="/index.php/apps/theming/icon?v=0">
		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#1d2d44">
[..]
```
`https://owncloud.ruinelli.ch/index.php/apps/theming/favicon?v=0` does not lead to the icon but instead only shows the same php file again!

So either is a misconfiguration in my database or the downloaded files. Setup is still the same as shown in https://github.com/nextcloud/server/issues/2900#issuecomment-269862271

**Comment by juliushaertl** [comment]
@caco3 Can you post the complete error message from your nextcloud log not only the stack trace? There seems to be something missing.

Might be related to https://github.com/nextcloud/server/issues/3428

**Comment by caco3** [comment]
@juliushaertl This is the log entry created on a single page load:
```{"reqId":"WQXlXtkaOgsAAQa8@8oAAACb","remoteAddr":"188.154.47.18","app":"index","message":"Exception: {\"Exception\":\"ImagickException\",\"Message\":\"not authorized `\\\/tmp\\\/magick-919752ylBEtM6s7qH' @ error\\\/constitute.c\\\/ReadImage\\\/412\",\"Code\":499,\"Trace\":\"#0 \\\/home\\\/****\\\/www\\\/nextcloud\\\/apps\\\/theming\\\/lib\\\/IconBuilder.php(157): Imagick->readimageblob('<?xml version=\\\"...')\\n#1 \\\/home\\\/****\\\/www\\\/nextcloud\\\/apps\\\/theming\\\/lib\\\/IconBuilder.php(55): OCA\\\\Theming\\\\IconBuilder->renderAppIcon('core', 32)\\n#2 \\\/home\\\/****\\\/www\\\/nextcloud\\\/apps\\\/theming\\\/lib\\\/Controller\\\/IconController.php(130): OCA\\\\Theming\\\\IconBuilder->getFavicon('core')\\n#3 [internal function]: OCA\\\\Theming\\\\Controller\\\\IconController->getFavicon('core')\\n#4 \\\/home\\\/****\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#5 \\\/home\\\/****\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Theming\\\\Controller\\\\IconController), 'getFavicon')\\n#6 \\\/home\\\/****\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Theming\\\\Controller\\\\IconController), 'getFavicon')\\n#7 \\\/home\\\/****\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('IconController', 'getFavicon', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/home\\\/****\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#10 \\\/home\\\/****\\\/www\\\/nextcloud\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/theming\\\/f...')\\n#11 \\\/home\\\/****\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/home\\\/****\\\/www\\\/nextcloud\\\/apps\\\/theming\\\/lib\\\/IconBuilder.php\",\"Line\":157}","level":3,"time":"2017-04-30T13:23:42+00:00","method":"GET","url":"\/index.php\/apps\/theming\/favicon?v=9","user":"--","version":"11.0.3.2"}```

**Comment by caco3** [comment]
@juliushaertl Any Idea why this is broken?

**Comment by juliushaertl** [comment]
@caco3 Looks like it is the same issue as #3428

> I've investigated a bit and it's browser independent. It requires an insecure installation of Imagemagick with a policy which authorises the MVG engine.
