### ISSUE TITLE
Setting to change Title of "New document"...

### ISSUE THREAD

**Issue by Thatoo** [nextcloud/server#29008]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I would like to be able to rename "New document" or "New mindmap"... that display when I click on the + button.

**Describe the solution you'd like**
Get the option in admin settings to change this "Titles" to what we think is best.

**Comment by kesselb** [comment]
Thanks :+1: 

Sorry to say but we are not adding a configuration option to overwrite New document with a different text.

**Comment by Thatoo** [comment]
Too bad, I don't how to make the difference between 
New document (markdown)
New document (collabora online)
New document (only office)

I mean, I know but when I share a folder to a collaborator who doesn't know nextcloud, I know it's confusing for them...

However, I understand if not done even though I thought it use to be possible before but couldn't find the way anymore...
