### ISSUE TITLE
Cannot open Nextcloud on macOS

### ISSUE THREAD

**Issue by caribu91** [nextcloud/server#29007]
I installed Nextcloud and synced it with my cloud and folders. Apparently, not all folders were synced. Therefore I wanted to open the app and change it. However, nothing happens as I do open the app. What can I do?

I downloaded the nextcloud installer today, so it must be the newest version. My macOS version is Big Sur 11.6.

Thank you

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
