### ISSUE TITLE
22.2.0 Upgrade Error - Could not decrypt key

### ISSUE THREAD

**Issue by Bables55** [nextcloud/server#29014]
### Steps to reproduce
1. Update from NC 22.1.0 to 22.2.0
2. Login
3.

  ### Expected behaviour
Login Success

### Actual behaviour
  An internal error occurs.
*If I disable Default encryption module and the login will succeed.

### Server configuration

**Operating system:**
CentOS 7.8
**Web server:**
Nginx 1.20.1
**Database:**
MariaDB 10.2.40
**PHP version:**
8.0.10
**Nextcloud version:** (see Nextcloud admin page)
22.2.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
22.1.1
**Where did you install Nextcloud from:**
nextcloud-22.2.0.tar.bz2

**Are you using external storage, if yes which one:** local/smb/sftp/...
SFTP
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
WebDAV

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

[index] Error: Could not decrypt key
POST /index.php/login
[no app in context] Error: Could not decrypt key
POST /index.php/login
</details>

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
