### ISSUE TITLE
Make subscribed calendars shareable

### ISSUE THREAD

**Issue by caco3** [nextcloud/server#2902]
NC11 has now the cool feature to subscribe to a calendar. This works great for Google calendars, thank you very much!

It would be great if I now could share those calendars with other NC members, like I can do this with my local calendars.

Reference: https://github.com/nextcloud/calendar/issues/272

**Comment by MorrisJobke** [comment]
Duplicate of #1440

**Comment by Nils160988** [comment]
I don't think this is a duplicate of https://github.com/nextcloud/server/issues/1440.
@caco3 here wants to share a subscribed calendar, not a federated one.
But maybe I got that wrong and sharing of subscribed calendars will be possible with https://github.com/nextcloud/server/issues/1440.

I just came across this issue when reading #1497 where this was an additional request and I was about to open a new one.

**Comment by caco3** [comment]
Yes, I also think my request is different, please reopen it!

**Comment by Nils160988** [comment]
@MorrisJobke, can you reopen it or should I better open a new issue?

**Comment by tcitworld** [comment]
Duplicate from #1600 (this time it's correct)
