### ISSUE TITLE
Errors about HTTP headers after upgrade to 22.2.0

### ISSUE THREAD

**Issue by smartlot** [nextcloud/server#29025]
### Steps to reproduce
1. Upgrade Nextcloud to 22.2.0
2. Go to Security (/settings/admin/overview)
3. Orange errors that were not there before.
4. Headers are being transmitted but Nextcloud reports otherwise

### Expected behaviour
No issue warnings since headers are correct
### Actual behaviour
Errors stating headers are not being transmitted

### Server configuration

**Operating system:**
Debian 10
**Web server:**
Nginx Reverse Proxy
**Database:**
mysql
**PHP version:**
8.0
**Nextcloud version:** 22.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
Source
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - admin_audit: 1.12.0
  - bookmarks: 10.0.0
  - breezedark: 22.0.1
  - calendar: 2.3.4
  - camerarawpreviews: 0.7.12
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.3
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - deck: 1.5.3
  - extract: 1.3.2
  - federatedfilesharing: 1.12.0
  - files: 1.17.0
  - files_automatedtagging: 1.12.0
  - files_markdown: 2.3.4
  - files_pdfviewer: 2.3.0
  - files_photospheres: 1.22.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - forms: 2.3.0
  - integration_github: 1.0.1
  - integration_gitlab: 1.0.1
  - integration_reddit: 1.0.1
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - maps: 0.1.9
  - music: 1.3.3
  - notes: 4.1.1
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - passwords: 2021.9.20
  - photos: 1.4.0
  - provisioning_api: 1.12.0
  - quicknotes: 0.7.2
  - ransomware_protection: 1.11.0
  - recognize: 1.6.10
  - richdocuments: 4.2.3
  - richdocumentscode: 6.4.1103
  - settings: 1.4.0
  - side_menu: 1.27.2
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_u2f: 6.2.0
  - unsplash: 1.2.3
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - video_converter: 1.0.3
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflow_pdf_converter: 1.7.0
  - workflowengine: 2.4.0
Disabled:
  - accessibility
  - activity
  - announcementcenter
  - apporder
  - carnet
  - circles
  - cospend
  - duplicatefinder
  - encryption
  - event_update_notification
  - federation
  - files_accesscontrol
  - files_external
  - files_reader
  - files_retention
  - files_texteditor
  - groupfolders
  - health
  - imageconverter
  - mail
  - nextcloud_announcements
  - ocsms
  - phonetrack
  - previewgenerator
  - privacy
  - qownnotesapi
  - recommendations
  - serverinfo
  - sharebymail
  - spreed
  - support
  - survey_client
  - systemtags
  - terms_of_service
  - user_ldap
  - user_usage_report
  - whiteboard
  - zenodo
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
</details>

**Are you using external storage, if yes which one:** NFSv4

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** None

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Mind to add the config report? In addition which headers is nextcloud warning about exactly?

**Comment by smartlot** [comment]
My bad, I forgot to add screenshots.
![Nextcloud-error](https://user-images.githubusercontent.com/36937318/135685525-9f913980-86ab-4891-a762-f88570aa8d32.jpg)
![nextcloud-errors](https://user-images.githubusercontent.com/36937318/135685528-5bd20afd-8923-42a3-be08-09cc1d1b7661.jpg)


###Config###
```
<?php
$CONFIG = array (
  'passwordsalt' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
  'secret' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXxx',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'XXXXXXXXXXX',
    2 => 'XXXXXXXXXXXXx',
    3 => 'XXXXXXXXXXXXXXx',
  ),
  'trusted_proxies' => 
  array (
    0 => '10.4.0.100',
    1 => '10.4.0.1',
  ),
  'overwrite.cli.url' => 'https://XXXXXXXXXXXXXXX',
  'htaccess.RewriteBase' => '/',
  'overwriteprotocol' => 'https',
  'datadirectory' => '/data',
  'default_phone_region' => 'US',
  'dbtype' => 'mysql',
  'version' => '22.2.0.2',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => 'XXXXXXXXXXXXXXXXXXXXXXXXX',
  'defaultapp' => 'dashboard',
  'installed' => true,
  'instanceid' => 'XXXXXXXXXXXX',
  'integrity.check.disabled' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'smtp.mailgun.org',
  'mail_smtpport' => '465',
  'mail_from_address' => 'postmaster',
  'mail_domain' => 'XXXX.com',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'XXXXXXXXXXXXxx@XXXXX.com',
  'mail_smtppassword' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'mysql.utf8mb4' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'updater.release.channel' => 'stable',
  'has_rebuilt_cache' => true,
  'app_install_overwrite' => 
  array (
    0 => 'unsplash',
    1 => 'dashboard',
    2 => 'zenodo',
    3 => 'whiteboard',
    4 => 'files_reader',
    5 => 'imageconverter',
  ),
  'updater.secret' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
);
```

**Comment by kesselb** [comment]
As seen in your screenshot all headers are there twice. That's the reason for the failing check. You can validate this with` curl -I yournextcloudurl.com`. It's not valid to set the headers twice.

**Comment by smartlot** [comment]
Odd, I am using an NGINX reverse proxy, perhaps the Apache2 server is sending those as well. At least I have a path to look into now. Thank you.

**Comment by smartlot** [comment]
![image](https://user-images.githubusercontent.com/36937318/135687941-e0bf2aec-aab9-441b-9b0a-68e6962ac970.png)
![image](https://user-images.githubusercontent.com/36937318/135687978-646d711c-e7fe-4fe0-a40a-14d33a95fe3c.png)
I was able to correct all but one. curl -I shows no double headers and shows this header is coming through correctly.

**The "X-Frame-Options" HTTP header is not set to "SAMEORIGIN". This is a potential security or privacy risk, as it is recommended to adjust this setting 

- accordingly.**
