### ISSUE TITLE
Excessive logging of GuzzleHttp exceptions

### ISSUE THREAD

**Issue by ironicx** [nextcloud/server#29038]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Keep loglevel at default (no debug logging)
2. Wait for problems accessing https://apps.nextcloud.com/api/v1/apps.json
3. Review nextcloud logfile

### Expected behaviour
Exceptions are logged without all connect data or debug information

### Actual behaviour
Exception log entry seems to include the complete json response (~4 MB)

### Server configuration

**Operating system:**
Linux, Debian 10

**Web server:**
Apache 

**Database:**
PostgreSQL

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)
22.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from previous version

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - bookmarks: 10.0.0
  - calendar: 2.3.4
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.3
  - contactsinteraction: 1.3.0
  - dav: 1.19.0
  - federatedfilesharing: 1.12.0
  - files: 1.17.0
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notes: 4.1.1
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - richdocuments: 4.2.3
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - spreed: 12.1.2
  - support: 1.5.0
  - systemtags: 1.12.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_u2f: 6.2.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - circles
  - dashboard
  - encryption
  - federation
  - files_external
  - survey_client
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```json
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "test.virtualfreedom.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/test.virtualfreedom.de\/mcloud",
        "htaccess.RewriteBase": "\/mcloud",
        "dbtype": "pgsql",
        "version": "22.2.0.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "DE",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "maintenance": false,
        "loglevel": 2,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "calendar"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
n/a

#### Web server error log
<details>
<summary>Web server error log</summary>
n/a
</details>

#### Nextcloud log (data/nextcloud.log)
Note: log entry is truncated here due to size. Logfile with complete log entry (~4MB) is attached.
<details>
<summary>Nextcloud log</summary>

```json
{"reqId":"ArbYyBa8hvNHzAL52zgL","level":2,"time":"2021-09-19T23:30:32+00:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":"Server error: `GET https://apps.nextcloud.com/api/v1/apps.json` resulted in a `502 Proxy Error` response:\n<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>502 Proxy Error</title>\n</head><body>\n<h1>Proxy E (truncated...)\n","userAgent":"--","version":"22.1.1.2","exception":{"Exception":"GuzzleHttp\\Exception\\ServerException","Message":"Server error: `GET https://apps.nextcloud.com/api/v1/apps.json` resulted in a `502 Proxy Error` response:\n<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>502 Proxy Error</title>\n</head><body>\n<h1>Proxy E (truncated...)\n","Code":502,"Trace":[{"file":"/srv/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":69,"function":"create","class":"GuzzleHttp\\Exception\\RequestException","type":"::","args":[{"__class__":"GuzzleHttp\\Psr7\\Request"},"*** sensitive parameter replaced ***",null,[],null]},{"file":"/srv/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":204,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/srv/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":153,"function":"callHandler","class":"GuzzleHttp\\Promise\\Promise","type":"::","args":[1,"*** sensitive parameter replaced ***",null]},{"file":"/srv/nextcloud/3rdparty/guzzlehttp/promises/src/TaskQueue.php","line":48,"function":"GuzzleHttp\\Promise\\{closure}","class":"GuzzleHttp\\Promise\\Promise","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/srv/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":248,"function":"run","class":"GuzzleHttp\\Promise\\TaskQueue","type":"->","args":[true]},{"file":"/srv/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":224,"function":"invokeWaitFn","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/srv/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":269,"function":"waitIfPending","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/srv/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":226,"function":"invokeWaitList","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/srv/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php","line":62,"function":"waitIfPending","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/srv/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":187,"function":"wait","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"/srv/nextcloud/lib/private/Http/Client/Client.php","line":223,"function":"request","class":"GuzzleHttp\\Client","type":"->","args":["get","https://apps.nextcloud.com/api/v1/apps.json",{"verify":"/srv/nextcloud/resources/config/ca-bundle.crt","timeout":60,"allow_redirects":{"on_redirect":{"__class__":"Closure"}},"headers":{"If-None-Match":"W/\"2021-09-18 04:10:42.425059+00:00\"","User-Agent":"Nextcloud Server Crawler","Accept-Encoding":"gzip"},"nextcloud":{"allow_local_address":false},"0":"And 1 more entries, set log level to debug to see all entries"}]},{"file":"/srv/nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php","line":108,"function":"get","class":"OC\\Http\\Client\\Client","type":"->","args":["https://apps.nextcloud.com/api/v1/apps.json",{"timeout":60,"headers":{"If-None-Match":"W/\"2021-09-18 04:10:42.425059+00:00\""}}]},{"file":"/srv/nextcloud/lib/private/App/AppStore/Fetcher/AppFetcher.php","line":79,"function":"fetch","class":"OC\\App\\AppStore\\Fetcher\\Fetcher","type":"->","args":["W/\"2021-09-18 04:10:42.425059+00:00\""
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
n/a</details
[nextcloud-22.1.1.log](https://github.com/nextcloud/server/files/7271470/nextcloud-22.1.1.log)
>

**Comment by ironicx** [comment]
[nextcloud-22.1.1.log](https://github.com/nextcloud/server/files/7271482/nextcloud-22.1.1.log)

**Comment by acsfer** [comment]
When https://apps.nextcloud.com/ is down, slow or other problems, these can be logged, but safely ignored (nothing to worry about nextcloud installation).

As you can see, this file https://apps.nextcloud.com/api/v1/apps.json can't be loaded at this time, trowing these errors.

Errors (or log lines) are meant to be **interpreted**, and sysadmins are the only ones who should evaluate if an action is needed, or not, like in these cases.

**Comment by MichaIng** [comment]
To make it easier for admins to evaluate whether an action is needed or not, wouldn't it be beneficial to actually log that "the Nextcloud apps store is currently not reachable"? If the actual URL is added as well, it would be trivial for admins to test in in browser or via curl to verify that it is most likely a temporary issue and none with their Nextcloud server.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by ironicx** [comment]
Running on 25.0.x since some months but could not reproduce this issue.

**Comment by szaimen** [comment]
Thanks for verifying!
