### ISSUE TITLE
Naming of versions for Maintainance releases

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#2903]
Our current plan is to offer our maintainance releases for Nextcloud 11 in the following format:

**Nextcloud 11.0.X**

I think it does not make any sense, because we will never use the "11 **.0.** X" in this format ...
To conclude: In my opinion, Nextcloud 11.X is shorter and easier to understand IMHO ;) 

What do you think? @karlitschek @MorrisJobke @LukasReschke @schiessle

**Comment by karlitschek** [comment]
Well it is best practice in open source to use the third digit for patch/bugfix releases. It we use the second digit then this means that it contains new features. So I think we should keep it as it is.
