### ISSUE TITLE
Update-Server for addons aren't reachable

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/server#29043]
Hi,

my Nextcloud 21.0.4 say that since 3 days the update server for addons isn't reachable.

Log file documented the the ssl certificate for https://curl.haxx.se has expired.

Fully log:
`
Error | internet_connection_check | GuzzleHttp\Exception\RequestException: cURL  error 60: SSL certificate problem: certificate has expired (see  https://curl.haxx.se/libcurl/c/libcurl-errors.html) for  https://www.nextcloud.com//var/www/clients/client39/web136/web/nc/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php - line 158: GuzzleHttp\Handler\CurlFactory::createRejection()/var/www/clients/client39/web136/web/nc/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php - line 110: GuzzleHttp\Handler\CurlFactory::finishError()/var/www/clients/client39/web136/web/nc/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php - line 47: GuzzleHttp\Handler\CurlFactory::finish()/var/www/clients/client39/web136/web/nc/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php - line 28: GuzzleHttp\Handler\CurlHandler->__invoke()/var/www/clients/client39/web136/web/nc/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php - line 48: GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}("*** sensiti ... *")/var/www/clients/client39/web136/web/nc/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php - line 35: GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}("*** sensiti ... *")/var/www/clients/client39/web136/web/nc/3rdparty/guzzlehttp/guzzle/src/Middleware.php - line 31: GuzzleHttp\PrepareBodyMiddleware->__invoke()/var/www/clients/client39/web136/web/nc/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php - line 71: GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensiti ... *")/var/www/clients/client39/web136/web/nc/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php - line 99: GuzzleHttp\RedirectMiddleware->__invoke()/var/www/clients/client39/web136/web/nc/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php - line 73: GuzzleHttp\RedirectMiddleware->checkRedirect()/var/www/clients/client39/web136/web/nc/3rdparty/guzzlehttp/promises/src/FulfilledPromise.php - line 41: GuzzleHttp\RedirectMiddleware->GuzzleHttp\{closure}("*** sensiti ... *")/var/www/clients/client39/web136/web/nc/3rdparty/guzzlehttp/promises/src/TaskQueue.php - line 48: GuzzleHttp\Promise\FulfilledPromise::GuzzleHttp\Promise\{closure}("*** sensiti ... *")/var/www/clients/client39/web136/web/nc/3rdparty/guzzlehttp/promises/src/Promise.php - line 248: GuzzleHttp\Promise\TaskQueue->run()/var/www/clients/client39/web136/web/nc/3rdparty/guzzlehttp/promises/src/Promise.php - line 224: GuzzleHttp\Promise\Promise->invokeWaitFn()/var/www/clients/client39/web136/web/nc/3rdparty/guzzlehttp/promises/src/Promise.php - line 269: GuzzleHttp\Promise\Promise->waitIfPending()/var/www/clients/client39/web136/web/nc/3rdparty/guzzlehttp/promises/src/Promise.php - line 226: GuzzleHttp\Promise\Promise->invokeWaitList()/var/www/clients/client39/web136/web/nc/3rdparty/guzzlehttp/promises/src/Promise.php - line 62: GuzzleHttp\Promise\Promise->waitIfPending()/var/www/clients/client39/web136/web/nc/3rdparty/guzzlehttp/guzzle/src/Client.php - line 187: GuzzleHttp\Promise\Promise->wait()/var/www/clients/client39/web136/web/nc/lib/private/Http/Client/Client.php - line 236: GuzzleHttp\Client->request()/var/www/clients/client39/web136/web/nc/apps/settings/lib/Controller/CheckSetupController.php - line 178: OC\Http\Client\Client->get()/var/www/clients/client39/web136/web/nc/apps/settings/lib/Controller/CheckSetupController.php - line 161: OCA\Settings\Controller\CheckSetupController->isSiteReachable()/var/www/clients/client39/web136/web/nc/apps/settings/lib/Controller/CheckSetupController.php - line 734: OCA\Settings\Controller\CheckSetupController->hasInternetConnectivityProblems()/var/www/clients/client39/web136/web/nc/lib/private/AppFramework/Http/Dispatcher.php - line 218: OCA\Settings\Controller\CheckSetupController->check()/var/www/clients/client39/web136/web/nc/lib/private/AppFramework/Http/Dispatcher.php - line 127: OC\AppFramework\Http\Dispatcher->executeController()/var/www/clients/client39/web136/web/nc/lib/private/AppFramework/App.php - line 157: OC\AppFramework\Http\Dispatcher->dispatch()/var/www/clients/client39/web136/web/nc/lib/private/Route/Router.php - line 302: OC\AppFramework\App::main()/var/www/clients/client39/web136/web/nc/lib/base.php - line 993: OC\Route\Router->match()/var/www/clients/client39/web136/web/nc/index.php - line 37: OC::handleRequest()
`

**Comment by kesselb** [comment]
Sounds like https://letsencrypt.org/2021/10/01/cert-chaining-help.html. 

https://www.ssllabs.com/ssltest/analyze.html?d=www.nextcloud.com&latest does not show any errors related to our tls configuration.

**Comment by kesselb** [comment]
Thanks @lookshe for the hint. I've sent a pull request to update the certificate bundle. Yet the connection to our updater server works fine for me even with the expired certificate :shrug:

**Comment by grosjo** [comment]
Issue still existing for NC24
