### ISSUE TITLE
SQL problems (using MariaDB) - but MariaDB seems to be OK

### ISSUE THREAD

**Issue by GER-HerrS** [nextcloud/server#29045]
Hi.
I wanted to update my Nextcloud server (just lastest minor update) but now I can't finish it.
Trying to update I get the following details shown in the browser (some word are german but I think you will understand):

> Aktualisierung auf 22.2.0
> Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused
> 
> An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
> Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused
> Detaillierte Protokollmeldungen 
> Update vorbereiten
> 
> Log-Level auf "debug" gesetzt
> Wartungsmodus eingeschaltet
> Repair MySQL collation
> All tables already have the correct collation -> nothing to do
> Repair SQLite autoincrement
> Copy data from accounts table when migrating from ownCloud
> Drop account terms table when migrating from ownCloud
> Das Datenbankschema wird aktualisiert
> Datenbank aktualisiert
> Fix component of birthday calendars
> 4 birthday calendars updated.
> Regenerating birthday calendars to use new icons and fix old birthday events without year
> Repair step already executed
> Fix broken values of calendar objects
> [0 / 0]: Fix broken values of calendar objects
> Registering building of calendar search index as background job
> Repair step already executed
> Register building of social profile search index as background job
> Registering background jobs to update cache for webcal calendars
> Added 0 background jobs to update webcal calendars
> Registering building of calendar reminder index as background job
> Repair step already executed
> Clean up orphan event and contact data
> An exception occurred while executing a query: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
> Remove activity entries of private events
> Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused
> Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused
> 
> Das Update ist fehlgeschlagen. Bitte melden Sie dieses Problem an die Nextcloud Community.

Connected via SSH to the server I tried to log in into MariaDB. It works well. User and password are working. I can select some tables in the "nextcloud" database.

I can't figure out the reason for this problem.

Maybe interesting to know:
Long ago I made the nextcloud server setup as shown here:
https://www.samueldowling.com/2020/07/24/install-nextcloud-on-freenas-iocage-jail-with-hardened-security/

Thank you!

**Comment by acsfer** [comment]
Please go to https://help.nextcloud.com for such (infrastructure) problems. Thanks 👍
