### ISSUE TITLE
`occ log:watch` fails with TypeError: array_map(): Argument #2 ($array) must be of type array, null given

### ISSUE THREAD

**Issue by jaakristioja** [nextcloud/server#29054]
### Steps to reproduce
1. run `occ log:watch`
2. wait

### Expected behaviour
Prints Nextcloud log messages until closed by the user.

### Actual behaviour
The program exists with status 1 after printing the first error message, e.g.:

```
cloud ~ # occ log:watch
An unhandled exception has been thrown:
TypeError: array_map(): Argument #2 ($array) must be of type array, null given in /var/www/htdocs/apps/logreader/lib/Log/Formatter.php:65
Stack trace:
#0 /var/www/htdocs/apps/logreader/lib/Log/Formatter.php(65): array_map()
#1 /var/www/htdocs/apps/logreader/lib/Log/Formatter.php(48): OCA\LogReader\Log\Formatter->formatTraceLine()
#2 [internal function]: OCA\LogReader\Log\Formatter->OCA\LogReader\Log\{closure}()
#3 /var/www/htdocs/apps/logreader/lib/Log/Formatter.php(49): array_map()
#4 /var/www/htdocs/apps/logreader/lib/Log/Formatter.php(35): OCA\LogReader\Log\Formatter->formatException()
#5 /var/www/htdocs/apps/logreader/lib/Command/Watch.php(114): OCA\LogReader\Log\Formatter->formatMessage()
#6 /var/www/htdocs/apps/logreader/lib/Command/Watch.php(98): OCA\LogReader\Command\Watch->printItem()
#7 /var/www/htdocs/3rdparty/symfony/console/Command/Command.php(255): OCA\LogReader\Command\Watch->execute()
#8 /var/www/htdocs/core/Command/Base.php(168): Symfony\Component\Console\Command\Command->run()
#9 /var/www/htdocs/3rdparty/symfony/console/Application.php(1009): OC\Core\Command\Base->run()
#10 /var/www/htdocs/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#11 /var/www/htdocs/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#12 /var/www/htdocs/lib/private/Console/Application.php(209): Symfony\Component\Console\Application->run()
#13 /var/www/htdocs/console.php(99): OC\Console\Application->run()
#14 /var/www/htdocs/occ(11): require_once('...')
#15 {main}cloud ~ # echo $?
1
cloud ~ #
```

### Server configuration

**Operating system:** Gentoo Linux

**Database:** PostgreSQL

**PHP version:** 8.0

**Nextcloud version:** 22.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgraded

**Where did you install Nextcloud from:** Gentoo ebuilds

**Signing status:** No errors have been found.

**Comment by graphius** [comment]
I have not used the occ log:watch before.
When I ran it today, it locked up, no output. I assume a similar issue to above

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
