### ISSUE TITLE
Unable to close pdf on Chrome Browser

### ISSUE THREAD

**Issue by SkrixlerAnon** [nextcloud/server#29060]
### Steps to reproduce
1. Open nextcloud on Chrome Browser for Android 
2. Open pdf and scroll down 

### Expected behaviour
- Going back to the files by clicking X

### Actual behaviour
- When I open a pdf file and scroll down (nextcloud on a Chrome Browser) then the close button X will disappear. 

### Can you reproduce this problem on https://try.nextcloud.com?
- No. 
![Screenshot_20211004-103705_Chrome](https://user-images.githubusercontent.com/88060511/135819965-b7e634f8-2084-4ba5-a061-b1e10877db5d.jpg)
![Screenshot_20211004-104603_Chrome](https://user-images.githubusercontent.com/88060511/135821078-13432990-ab6d-46ef-9827-5f7660334864.jpg)

![Screenshot_20211004-103636_Chrome](https://user-images.githubusercontent.com/88060511/135819969-fcc79794-cc4b-4835-a801-04cf2327b1ac.jpg)

### Environment data
Android version: Android 10

Device model: SM-G975F 

Chrome Browser: 94.0.4606.71

**Comment by AndyScherzinger** [comment]
Transfered to server since this is the webUI not th enative client.

@SkrixlerAnon which server version are you running?

**Comment by acsfer** [comment]
@AndyScherzinger this seems more a "files_pdfviewer" app issue, instead of "server", no?

**Comment by szaimen** [comment]
This was already fixed with https://github.com/nextcloud/files_pdfviewer/pull/443

**Comment by AndyScherzinger** [comment]
@acsfer right! Thanks for the update @szaimen ❤️
