### ISSUE TITLE
Group admin cannot create new users

### ISSUE THREAD

**Issue by bpgitkr** [nextcloud/server#29063]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Open user list (as group admin)
2. Click new user
3. Additional form field without caption and with red border appears between e-mail field and group field:

![2021-10-04 13_20_37-Window](https://user-images.githubusercontent.com/72573979/135843866-ed7d8302-8d4a-422f-a756-76f14b28e8eb.png)

4. User cannot be saved

### Expected behaviour
Field should not be displayed. Group admin should be able to create new user.
(Note: The global admin account ncadmin does not have this behavior. Only group admins do.)

### Actual behaviour
User cannot be created.

### Server configuration

**Operating system/Web server/Database/PHP version:** Official Docker image (https://hub.docker.com/_/nextcloud)

**Nextcloud version:** 22.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Older version, last update was from 22.1.0 to 22.2.0

**Where did you install Nextcloud from:** Docker

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***:8080",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***:8080"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "22.2.0.2",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "default_language": "de_DE",
        "default_locale": "de_DE",
        "defaultapp": "files",
        "overwriteprotocol": "https",
        "simpleSignUpLink.shown": "false",
        "loglevel": 2,
        "maintenance": false
    }
}
</details>

**Are you using external storage, if yes which one:** None

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chrome. happens with every browser

**Operating system:** Windows Server 2019, happens with every OS

#### NextCloud error log
No error visible in the Log in the admin GUI.

**Comment by bbx-github** [comment]
I can confirm partly. As groupadmin it is not possible to add a user, without applying a group. If a group is applied the red framed field (in the picture above) gets filled with `[object Object]` (what is weird ux) and the user gets created.
- this field should be invisible
- if user is only groupadmin for one group the `add user to group` field should be pre-filled (and maybe invisible as well)

nc22.2.0

![nc22 2 0-weird-field-for-groupadmin-account-creation](https://user-images.githubusercontent.com/53237674/138290601-03b91fff-f29a-4bf3-97df-0b6fa2efaf5e.png)
