### ISSUE TITLE
Write federated share events to audit log

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#29088]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 
---

**Is your feature request related to a problem? Please describe.**
Certain audit log relevant events aren't written/send to the audit log but should be

**Describe the solution you'd like**
write the following events to the audit log:
* Federated share permission increase (also generate an activity entry)
* Federated share accepting/declining

**Describe alternatives you've considered**
None

**Additional context**

**Comment by joshtrichards** [comment]
Theoretically this was implemented in #31594 and released in NC24.

**Comment by joshtrichards** [comment]
Fixed in #31594
