### ISSUE TITLE
Add occ command/UI to create user encryption public/private key

### ISSUE THREAD

**Issue by zecke** [nextcloud/server#2908]
In the UI oen can only generate a new key if the old password is known (but on a new account there is no old password) and if one wants to wipe all data maybe throwing away the existing key is good enough. Alternatively a occ command to create a new keypair would be nice.

It would help with #2907 and #427.

**Comment by schiessle** [comment]
I create a pull request to first backup the users private/public key and then create new ones on password reset https://github.com/nextcloud/server/issues/427

This should solve all the issues or do you still see a need for a occ command to reset the users private/public key once this is merged?

**Comment by zecke** [comment]
Thank you!
