### ISSUE TITLE
Having "Sharing" admin privilege only throws an error

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#29092]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. As user userB be in a group "Team"
2. As admin add admin privilege "Sharing" for group "Team

![Bildschirmfoto von 2021-10-06 11-57-16](https://user-images.githubusercontent.com/213943/136181763-8f5f6c5f-c6f5-4f91-8d37-4e54d7ed9012.png)

3. As userB open the "Sharing" admin section

### Expected behaviour
Works

### Actual behaviour
The group inputs are missing and you are unable to make group restrictions for sharing (because the group list is not loaded)

![Bildschirmfoto von 2021-10-06 11-59-15](https://user-images.githubusercontent.com/213943/136182132-4b735025-bb6c-411d-8451-a8229d76a717.png)

**Comment by CarlSchwan** [comment]
I can't reproduce with master :) Probably fixed https://github.com/nextcloud/server/pull/29240
