### ISSUE TITLE
occ status is NOT json format and does not honor --no-warnings option

### ISSUE THREAD

**Issue by erik78se** [nextcloud/server#29103]
Output from:

`sudo -u www-data /usr/bin/php occ status --output=json --no-warnings`

`Nextcloud is not installed - only a limited number of commands are available
{"installed":false,"version":"20.0.6.1","versionstring":"20.0.6","edition":""}`

Produces an output which is NOT json and includes warnings. This breaks code which parses the output, expecting json as return value.

### Steps to reproduce
1. Extract nextcloud version 20.0.6 into /var/www/nextcloud
2. Run `sudo -u www-data /usr/bin/php occ status --output=json --no-warnings`
3. The output is not json.

You can validate this with the following python code:

```
import subprocess as sp
cmd = "sudo -u www-data /usr/bin/php occ status --output=json --no-warnings"
r = sp.run(cmd.split(), cwd='/var/www/nextcloud',
     stdout=sp.PIPE, stderr=sp.PIPE, universal_newlines=True)

print("stdout:" + r.stdout)
print("stderr:" + r.stderr)

```

### Expected behaviour
The output should be ONLY: {"installed":false,"version":"20.0.6.1","versionstring":"20.0.6","edition":""}
Possibly the "stderr" could be the message about the not-installed-nextcloud. But definetly not stdout.

### Actual behaviour
I get the message + the json in stdout.

### Server configuration

**Operating system:**
Ubuntu focal.

**Web server:**
apache2

**Database:**
postgresql

**PHP version:**
PHP 7.4.3 (cli) (built: Aug 13 2021 05:39:12) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
20.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
Official releases tarball.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
