### ISSUE TITLE
Event link to calendar, opens calendar and the details pane keeps loading.

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/server#29117]
### Steps to reproduce
1. Have userA and userB
2. userA share a calendar with userB
3. userA creates an event
4. userB goes to activity tab
5. userB sees the activity with the name of the event
6. userB click on the name of the event to get more details

### Expected behaviour

The event should show on the event detailed view of their calendar.

### Actual behaviour

The panel is loading forever.

This relates to this PR:
https://github.com/nextcloud/activity/pull/420/files

I also noticed that the link in the calendar itself and the activity app is not the same, these are the 2 links:
```
L3JlbW90ZS5waHAvZGF2L2NhbGVuZGFycy9hZG1pbi90ZXN0LXRlc3QvQTQ3MkI4RTktQzQ1Ni00NEUwLUE2NzQtNzc4RDJFRjAyMzRELmljcw==/next
L3JlbW90ZS5waHAvZGF2L2NhbGVuZGFycy9sLmZ1ZW50ZXMvdGVzdC10ZXN0X3NoYXJlZF9ieV9hZG1pbi9BNDcyQjhFOS1DNDU2LTQ0RTAtQTY3NC03NzhEMkVGMDIzNEQuaWNz/1627344000
```

And I tried to reproduce on another instance, but I couldn't and the links were the same.

So I guess there is something wrong with this instance, where the activity app has somehow the wrong links to the calendar app. It doesn't affect other apps as far as I know.

### Server configuration

**Operating system**: debian/kubernetes

**Web server:** nginx

**Database:** pg

**PHP version:** docker

**Nextcloud version:** 20.0.10

**Where did you install Nextcloud from:** docker

**Signing status:** ok

**List of activated apps:** calendar, activity

**Are you using an external user-backend, if yes which one:** SAML

### Client configuration
**Browser:** ff 

**Operating system:** debian

#### Browser log

```
Uncaught (in promise) Error: 
    n https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    m https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    _invoke https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    M https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    fe https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    i https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    ge https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    ge https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    getEventByObjectId https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    h https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    dispatch https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    dispatch https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    n https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    m https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    _invoke https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    M https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    Q https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    i https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    H https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    H https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    resolveClosestRecurrenceIdForCalendarObject https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    h https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    dispatch https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    dispatch https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    t https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    m https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    _invoke https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    M https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    yf https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    i https://nextcloud_url/apps/calendar/js/calendar.js?v=8924b48d-7:2
    ```
```

**Comment by ImaCrea** [comment]
Hello, we've add a similar feedback from our users today. It happens when they try to get to an event from a notification in the activity app. Very frustrating from what they told us.

**Comment by JotaPin** [comment]
Hi, same problem here (server 23.0.3), this is really a problem for our 20 users, as they must approve calendar events created by others using the list appearing in the activity app.

**Comment by pierreozoux** [comment]
Today, the user wanted to add that when you are the owner of the event it does work as expected, it is just when the user receives the notification about a shared event with them that this user can't go to the event.

**Comment by pierreozoux** [comment]
Is this the right place for this bug? Or should it be moved to the app calendar or activity?

**Comment by FTB-Volmarstein** [comment]
Hi, Problem still exists on Nextcloud 24.0.6 and Calendar 3.4.2 and Activity 2.16.0. 
Any news? Tested NC 25-demo yesterday. There it works.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
