### ISSUE TITLE
Calendar-App and Contacts-App allow sharing with groups even if this feature is disabled

### ISSUE THREAD

**Issue by Linuxfabrik** [nextcloud/server#29112]
### Steps to reproduce
Suppose we have a group called "user" that contains all the users on the system. These are our settings:

![image](https://user-images.githubusercontent.com/24634880/136357138-7cee8681-14c8-4b3a-9b35-931595df8cdb.png)

**Problem**: 

In the _Calendar app_, when you use "share" you can start typing and get all the matching _group names_. It does not autocomplete users (as expected).

![image](https://user-images.githubusercontent.com/24634880/136357730-6055ef45-8b69-40a7-8c5b-1d7b88378354.png)

The same is true for the _Contact app_, although it looks a little different. Start typing "u" and you will get a slightly truncated autocomplete list. If you click on it, you can share your contacts with all users of the system. It is even enough to type "user" completely and press Enter.

Searching for group names:

![image](https://user-images.githubusercontent.com/24634880/136358758-dd7f022a-2a03-4b55-97d2-d9edf9ec0180.png)

After clicking the cropped auto-complete list item, or by typing "user" and hitting Enter:

![image](https://user-images.githubusercontent.com/24634880/136358674-ba99eb83-1d6c-46a5-84cf-c8ad02023dbc.png)

### Expected behaviour
"Allow sharing with groups": If the option is turned off, nobody should be able to share any content with a group.

### Actual behaviour
See above

### Server configuration

**Operating system:** 4.18.0-305.10.2.el8_4.x86_64

Software: Apache httpd 2.4.37, MariaDB 10.5.11, PHP 7.4.22, Python2 2.7.18, Redis Server 6.0.15

**Nextcloud version:** 21.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Comment by ChristophWurst** [comment]
This is not reproducible with Nextcloud 23 at least. The checkbox *Allow sharing with groups* does what it promises.
