### ISSUE TITLE
Webauthn as second factor

### ISSUE THREAD

**Issue by virtualdxs** [nextcloud/server#29127]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I want to use a webauthn device as my second factor, i.e. in addition to my password, not instead of.

**Describe the solution you'd like**
Allow webauthn devices to be configured as second factors instead of only first

**Describe alternatives you've considered**
- The U2F plugin does what I want, but only on platforms that support U2F. Notably, Firefox mobile supports webauthn but not U2F. As a result I cannot use my Yubikey to authenticate to Nextcloud on Firefox mobile when using the U2F plugin.
- There's a webauthn 2fa plugin in the app store, but the github makes it clear that it's not production ready.

**Comment by ChristophWurst** [comment]
dup of https://github.com/nextcloud/server/issues/21215?

**Comment by virtualdxs** [comment]
Not a dupe. That issue is about 1FA via webauthn - just `username/webauthn`. This issue is about `username/password + webauthn`.

**Comment by virtualdxs** [comment]
I should also add that this flow currently exists for U2F, but not webauthn. The issue there being that certain platforms (notably Firefox for Android) do not support the legacy U2F standard, so when logging in on there I need to use TOTP for 2FA.

**Comment by frdbonif** [comment]
Firefox desktop supports U2F however Chrome and Edge do not, only supporting webauthn.  U2F is becoming difficult to use in business environments where browsers are up-tp-date.

**Comment by joshtrichards** [comment]
https://github.com/nextcloud/twofactor_webauthn

https://apps.nextcloud.com/apps/twofactor_webauthn
