### ISSUE TITLE
Self signed SSL WebDav as external Storage

### ISSUE THREAD

**Issue by Zerod159** [nextcloud/server#2917]
With the extension for external storage support and an self signed ssl certificate from my own https:// server, i get the error message: [...]Sabre\HTTP\ClientException: SSL certificate problem, verify that the CA cert is OK. Details: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed.[...].

**Comment by nickvergessen** [comment]
You need to import the self-signed certificate with the console command:
```
sudo -u www-data ./occ security:certificates:import --help
Usage:
  security:certificates:import <path>

Arguments:
  path                  path to the certificate to import
```

**Comment by febs** [comment]
I did imported the certificate but I still get the

> [curl] 60: SSL certificate problem: unable to get local issuer certificate 

error. Thanks,

**Comment by nickvergessen** [comment]
Does the cert show in `sudo -u www-data ./occ security:certificates`

Because it works just fine here, I develop with self signed certs locally.

**Comment by febs** [comment]
Yes, it does!
I added both the server cert and its CA as well. No success.

**Comment by febs** [comment]
Any hints? I am stuck. Thanks

**Comment by mstyp** [comment]
> path to the certificate to import

How do I find out where this is? I am pretty sure the certificate is not actually on the same computer I have nextcloud running. I cant find any information online on how get the self signed cert and move it to my nextcloud install.
