### ISSUE TITLE
Birthday without year specification shows: "(1904)"

### ISSUE THREAD

**Issue by JDPDO** [nextcloud/server#29193]
### Steps to reproduce
1. Add contact with birthday without year _(For example with Thunderbird)_
2. Look for day and month of birth in some year

### Expected behaviour
It should be no year shown for birthday.

### Actual behaviour
The year 1904 is shown

### Calendar app
**Calendar app version:** 2.3.4
**CalDAV-clients used:** DAVx5

### Client configuration
**Browser:** Firefox 93.0

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
