### ISSUE TITLE
Shared files no longer visible on NC 11 with encryption

### ISSUE THREAD

**Issue by sushidave** [nextcloud/server#2919]
On a Nextcloud server with server-side encrpytion files that are shared with its users don't show up anymore.

### Steps to reproduce
1. Log in as a user or an admin.
2. Open the files app and click on the "shared with you" view.

### Expected behaviour
The shared files should be shown - or - a message telling that there are no files.

### Actual behaviour
The content area of the "shared with you" view is blank: No files are displayed and no message appears that there are no files.

- The view is empty for admin and regular user accounts that already existed before the update.
- The view is empty for user accounts created after the update, too.
- Files shared both before and after the upgrade don't show up.
- The invitations for new file sharings arrive normally. After accepting them the files don't appear.
- The "shared by you" view is fine and the message appears that there are no files.
- Files that were shared by users of that encrypted Nextcloud are still visible on a Nextcloud without encryption.
- The admin page shows that server-side encryption and also the Encryption default module are active.
- Deactivating and reactivating the Encryption default module app didn't help.

### Server configuration
**Operating system**:
Linux

**Web server:**
Apache

**Database:**
mysql 
Version: 5.6.26

**PHP version:**
5.6.26

**Nextcloud version:**
11.0.0 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from an older Nextcloud

**Where did you install Nextcloud from:**
updater app

**Signing status:**
<details>
<summary>Signing status</summary>
Can't get the status by http://************/index.php/settings/integrity/failed. It results in a redirecton error ("Umleitungsfehler").
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Activity 2.4.1
Auditing / Logging 1.1.0
Collaborative tags 1.1.3
Comments 1.1.0
Default encryption module 1.4.1
Deleted files 1.1.0
Federation 1.1.1
File sharing 1.1.1
First run wizard 2.0
Gallery 16.0.0
Log reader 2.0
Mail template editor 0.2
Nextcloud annoucements 1.0
Notifications 1.0.1
Password policy 1.1.0
PDF viewer 1.0.1
Server info 1.1.1
Share by mail 1.0.1
Text editor 2.2
Theming 1.1.1
Updated notification 1.1.1
Usage survey 0.1.5
Versions 1.4.0
Video player 1.0.0
Spreed video calls 1.1.2
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
<?php
$CONFIG = array (
  'instanceid' => '**************',
  'passwordsalt' => '***********************',
  'secret' => '*****************************************',
  'trusted_domains' => 
  array (
    0 => '***************',
  ),
  'datadirectory' => '/home/httpd/vhosts/*********/cloud_data',
  'dbtype' => 'mysql',
  'version' => '11.0.0.10',
  'dbname' => '************',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nc',
  'dbpassword' => '*************',
  'logtimezone' => 'UTC',
  'installed' => true,
  'forcessl' => true,
  'memcache.local' => '\\OC\\Memcache\\ArrayCache',
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => '*******',
  'mail_domain' => '****************',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => '**********************',
  'mail_smtpport' => '25',
  'overwrite.cli.url' => 'https://*****************:443',
  'overwriteprotocol' => 'https',
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
);
</details>

**Are you using external storage, if yes which one:**
no

**Are you using encryption:**
yes

**Are you using an external user-backend, if yes which one:**
no

### Client configuration
**Browser:**
Firefox

**Operating system:**
various (OS X, Windows 7)

#### Web server error log
<details>
<summary>Web server error log</summary>
2017-01-02 20:18:39	Warning	***.***.***.***		mod_fcgid: stderr: PHP Fatal error: Call to a member function getMimetype() on boolean in /home/httpd/vhosts/**********/*********/apps/files_sharing/lib/Controller/RemoteController.php on line 115				Apache-Fehler

(...this warning repeats itself...)
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
https://example.com/index.php/settings/admin/logging shows this:

Error	Default encryption module not loaded	2017-01-02T21:18:43+0100
Error	Default encryption module not loaded	2017-01-02T21:18:43+0100
Error	Default encryption module not loaded	2017-01-02T21:18:43+0100
Error	Default encryption module not loaded	2017-01-02T21:18:43+0100
Error	Default encryption module not loaded	2017-01-02T21:18:42+0100
Error	Default encryption module not loaded	2017-01-02T21:18:42+0100
Error	Default encryption module not loaded	2017-01-02T21:18:42+0100
Error	Default encryption module not loaded	2017-01-02T21:18:42+0100
Error	Default encryption module not loaded	2017-01-02T21:18:42+0100
Error	Default encryption module not loaded	2017-01-02T21:18:42+0100
Error	Default encryption module not loaded	2017-01-02T21:18:42+0100
Error	Default encryption module not loaded	2017-01-02T21:18:42+0100
(...)
</details>

**Comment by anonymosh** [comment]
Ran into the same issue. The page stays blank and the network request to {server}/owncloud/ocs/v1.php/apps/files_sharing/api/v1/remote_shares?format=json returns a 500.

For me this was caused by a corrupted (?) external share.
After deleting the entry from the mysql table oc_share_external the error message disappeared and the webbrowser did load the shares correctly again.

I can't say what was the problem with this peticular shared file, though.

**Comment by nickvergessen** [comment]
@schiessle

**Comment by laenan8466** [comment]
@anonymosh This doesn't solved the problem for me. Still working on this issue.
I don't get the 500-error, because access is forbidden, due to failed CSRF check. 

Anyone an idea how to solve this?

**Comment by noresistence** [comment]
I experience the same behaviour on NC 12 - no external shares are shown, encryption is activated. Deleting everything from the mysql table oc_share_external and later accepting new shares does not change anything; they still don't show up.

**Comment by schiessle** [comment]
can't reproduce it. Feel free to re-open if this is still an issue with the latest version of Nextcloud

**Comment by J0WI** [comment]
> Feel free to re-open if this is still an issue with the latest version of Nextcloud

I assume you forgot to close this.
