### ISSUE TITLE
Dynamic share providers / share types in Nextcloud

### ISSUE THREAD

**Issue by Potherca** [nextcloud/server#29215]
My colleague @ylebre is working on [a project](https://github.com/pondersource/nc-sciencemesh) that makes it possible to connect Nextcloud servers to [Sciencemesh](https://sciencemesh.io/).
For this project we need to add custom handling for [File Sharing](https://docs.nextcloud.com/server/latest/user_manual/en/files/sharing.html). This also means we need a custom sharing _type_.

For our custom install, we can just add another class constant to the [`lib/public/Share/IShare.php`](https://github.com/nextcloud/server/blob/HEAD/lib/public/Share/IShare.php) interface, and custom handling logic for this type.

But when we were looking at the code, we saw a comment in [the Share20 `Manager` class](lib/private/Share20/Manager.php) that says:

> We can't handle other types yet

Hmmm... "yet"? :thinking:

And in the Share20 [`ProviderFactory`](https://github.com/nextcloud/server/blob/master/lib/private/Share20/ProviderFactory.php), the latest addition (for share type `IShare::TYPE_DECK`)
uses `$this->getProvider('deck')` instead of `$this->getDeckShareProvider()`.

This got us thinking that Nextcloud might benfit from an implementation that makes is possible to dynamically add share providers (types and logic). This could be very useful for Nextcloud plugins.

So my question is:

**Is there any interest in merging such functionality, if provided?** (Including any docs or tests deemed necessary)

From what we can see, we _think_ this would be a relatively small change.
Files that we can see that need to be touched are:

- [`apps/files_sharing/lib/Controller/ShareAPIController.php`](https://github.com/nextcloud/server/blob/master/apps/files_sharing/lib/Controller/ShareAPIController.php) and [related test](https://github.com/nextcloud/server/blob/master/apps/files_sharing/tests/Controller/ShareAPIControllerTest.php)
- [`lib/private/Share20/Manager.php`](https://github.com/nextcloud/server/blob/b585cf1ea1baeb7bbfaf22953e48bbd33e8381fa/lib/private/Share20/Manager.php) and [related test](https://github.com/nextcloud/server/blob/b585cf1ea1baeb7bbfaf22953e48bbd33e8381fa/tests/lib/Share20/ManagerTest.php)
- [`lib/private/Share20/ProviderFactory.php`](https://github.com/nextcloud/server/blob/master/lib/private/Share20/ProviderFactory.php) (no tests seem to be available?)

Is the information I've shared here complete and correct? Am I missing anything?
And if there's an interest, which steps would we need to take in order to make this happen?

- - -

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kesselb** [comment]
cc @skjnldsv @ChristophWurst @juliushaertl

**Comment by Potherca** [comment]
For an implementation, we were thinking along the lines of leaving the constants as-is and adding a mechanism through which other types could be dynamicly added. 

Changes to the front-end would be small, if any, as the majority of the existing logic can already be (re-)used. The connected clients would most likely only be the plugins that introduce custom types (at least to begin with). 

We had an idea for registering (and listing) providers without using the database as well, to help keep code changes to a minimum.

Would it be helpfull if we open an MR to demonstrate what the impact of our current thinking would be on the code?

**Comment by juliushaertl** [comment]
> Would it be helpfull if we open an MR to demonstrate what the impact of our current thinking would be on the code?

Sure, it would make sense to discuss the code in question and a draft pull request might be good for that.

 I agree that modularising the share provider code is generally a good idea.

**Comment by PVince81** [comment]
might be interesting to grep for the share type email and circles and see where it's used, and whether any additional types would require to be there as well or not ? or opt-in ?

**Comment by joshtrichards** [comment]
https://github.com/nextcloud/server/issues/36227#issue-1538631991
