### ISSUE TITLE
Suspicious login information notification should allow text selection

### ISSUE THREAD

**Issue by jficz** [nextcloud/server#29236]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Security notifications about suspicious logins do not allow text selection.
People don't usually remember IP addresses, that's what DNS is for, therefore printing an IP address does not give much information to the user unless the user has an option to somehow reverse-check the IP address, which they don't because there is no (simple) way to copy-paste the IP.

**Describe the solution you'd like**
Text in notifications should be selectable so that users can copy-paste the IP address and check it using their preferred tool.

**Describe alternatives you've considered**
Alternatively, the IP address itself could be a hyperlink to some IP check service, such as whoisip.org or similar, or to a dedicated hosted site which can show relevant information like reverse DNS lookup, GeoIP map and/or Whois entry.

**Comment by joshtrichards** [comment]
Implemented in nextcloud/suspicious_login#535 and released with NC25.

This Issue can be closed out.
