### ISSUE TITLE
Integrity checks to accept missing .htaccess file

### ISSUE THREAD

**Issue by Dieter15** [nextcloud/server#29232]
I run NC (v21.0.5) on Debian 10 and Apache 2.4.38. I appreciate very much and follow all suggestions and recommendations for securing my website as fas as NC is concerned (I use ssllabs.com to look for recommendations to harden my apache webserver).

For performance reasons I incorporated the whole contents of NC’s .htaccess file into my apache main configuration file and then I deleted the .htaccess file in /path/to/NC. The webserver was successully restarted (i.e. no problems at all).

The NC integrity check complained about the missing .htaccess file (the file is NOT mandatory anyway).

The feature request is related to the fact that a missing .htaccess file causes an error message.

**Describe the solution you'd like**
If there is no .htaccess file the integrity check should accept this fact and therefore should not complain about it. At least there should be no impediments / obstacles which prevent an upgrade of NC to be accomplished successfully. If you want you may output an informative text message (but NOT an error message) that .htaccess is missing.
Leave it up to the NC administrator to keep / delete the .htaccess file. They know what is best for their websites.

**Describe alternatives you've considered**
I don't know of any sensible alternatives

**Additional context**
None.

**Comment by kesselb** [comment]
Currently there are no plans to implement such a feature. Thus I will close this ticket for now.
