### ISSUE TITLE
Contacts with umlaut cannot be selected via search

### ISSUE THREAD

**Issue by BFallert** [nextcloud/server#29242]
when I search for a name with an umlaut in the first name or surname in the Contacts web interface, the record is found in the search list, but when I click on it, the message "Contact not found" appears after some time.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Add a contact with Umlaut in his name, for example "Jürgen Testcontact"
2. Search this contact via "Magnifying glass icon" top right
3. Select the name in the list, for example "Jürgen Testcontact"
4. the message "Contact not found" appears after some time

### Expected behaviour
The record should be displayed for editing, as it is possible when the record is displayed via the normal name list.

### Actual behaviour
the message "Contact not found" appears after some time,  Contact cannot be selected via search, but only from the name list

### Server configuration

**Operating system:** raspberrypi, Linux 5.10.60-v7+ armv7l

**Web server:** apache2

**Database:**  mysql 10.3.31

**PHP version:** 7.3.29

**Nextcloud version:** Nextcloud Hub 22.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from older Versions 

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

Server configuration detail

Operating system: Linux 5.10.60-v7+ #1449 SMP Wed Aug 25 15:00:01 BST 2021 armv7l

Webserver: Apache/2.4.38 (Raspbian) (apache2handler)

Database: mysql 10.3.31

PHP version: 7.3.29-1~deb10u1

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

Nextcloud version: 22.2.0 - 22.2.0.2

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from: unknown

<details><summary>Signing status</summary>

Array ( )

</details>

<details><summary>List of activated apps</summary>

Enabled:
 - accessibility: 1.8.0
 - activity: 2.15.0
 - bookmarks: 10.0.0
 - bruteforcesettings: 2.2.0
 - calendar: 2.3.4
 - circles: 22.1.1
 - cloud_federation_api: 1.5.0
 - comments: 1.12.0
 - contacts: 4.0.3
 - contactsinteraction: 1.3.0
 - dashboard: 7.2.0
 - dav: 1.19.0
 - federatedfilesharing: 1.12.0
 - federation: 1.12.0
 - files: 1.17.0
 - files_antivirus: 3.2.2
 - files_external: 1.13.0
 - files_markdown: 2.3.4
 - files_mindmap: 0.0.25
 - files_pdfviewer: 2.3.0
 - files_rightclick: 1.1.0
 - files_sharing: 1.14.0
 - files_trashbin: 1.12.0
 - files_versions: 1.15.0
 - files_videoplayer: 1.11.0
 - firstrunwizard: 2.11.0
 - gpxpod: 4.2.8
 - integration_discourse: 1.0.1
 - integration_github: 1.0.1
 - keeweb: 0.6.6
 - logreader: 2.7.0
 - lookup_server_connector: 1.10.0
 - nextcloud_announcements: 1.11.0
 - notes: 4.1.1
 - notifications: 2.10.1
 - oauth2: 1.10.0
 - password_policy: 1.12.0
 - photos: 1.4.0
 - privacy: 1.6.0
 - provisioning_api: 1.12.0
 - qownnotesapi: 21.7.0
 - recommendations: 1.1.0
 - serverinfo: 1.12.0
 - settings: 1.4.0
 - sharebymail: 1.12.0
 - support: 1.5.0
 - survey_client: 1.10.0
 - systemtags: 1.12.0
 - tasks: 0.14.2
 - text: 3.3.0
 - theming: 1.13.0
 - twofactor_backupcodes: 1.11.0
 - updatenotification: 1.12.0
 - user_status: 1.2.0
 - viewer: 1.6.0
 - workflowengine: 2.4.0
Disabled:
 - admin_audit
 - drawio
 - encryption
 - groupfolders
 - news
 - previewgenerator
 - user_external
 - user_ldap
 - weather_status
 - workflow_pdf_converter
</details>

<details><summary>Configuration (config/config.php)</summary>

{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.1.40",
        "xxxx"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "XXXX",
    "overwriteprotocol": "https",
    "htaccess.RewriteBase": "\/",
    "dbtype": "mysql",
    "version": "22.2.0.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "log_type": "file",
    "logtimezone": "Europe\/Berlin",
    "logfile": "\/var\/log\/nextcloud.log",
    "loglevel": 2,
    "maintenance": false,
    "theme": "",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "sendmail",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "enable_previews": true,
    "preview_max_x": 400,
    "preview_max_y": 400,
    "preview_max_scale_factor": 1.5,
    "jpeg_quality": 60,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG"
    ],
    "updater.release.channel": "stable",
    "mysql.utf8mb4": true,
    "memcache.local": "\\OC\\Memcache\\Redis",
    "default_phone_region": "DE",
    "mail_sendmailmode": "pipe"
}

</details>

External storages: yes

Encryption: no

User-backends:

OC\User\Database

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome / FF

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by BFallert** [comment]
I have already updated my installation to 25.0.3. The error can currently no longer be reproduced. Currently everything works perfectly. The error occurred only in the mentioned version 22.2.0.  It is best to close this issue.
