### ISSUE TITLE
JS tests are not executed

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#29250]
Some big brain time here.
With some update the regex pattern of jest changed (`--testRegex` is available to configure it)

### To test

modify
https://github.com/nextcloud/server/blob/4322aaba227117af65d288baf602348a2c96cc96/package.json#L16

to 
```json
    "test": "jest core/",
```

Since then only one test in core is executed:
```
> nextcloud@1.0.0 test
> jest core/

 PASS  core/src/tests/OC/requesttoken.spec.js
  request token
    ✓ reads the token from the document (4 ms)
    ✓ remembers the updated token (1 ms)
    @nextcloud/auth integration
      ✓ fires off an event for @nextcloud/auth (2 ms)

Test Suites: 1 passed, 1 total
Tests:       3 passed, 3 total
Snapshots:   0 total
Time:        1.335 s
Ran all test suites matching /core\//i.
```

### With matching pattern
```json
    "test": "jest core/ --testRegex='[sS]pec.[tj]s'",
```
the result is much worse:
```
Test Suites: 15 failed, 1 passed, 16 total
Tests:       244 failed, 3 passed, 247 total
Snapshots:   0 total
Time:        7.081 s
```

I guess the tests were not adjusted since they were not executed anymore.

cc @nextcloud/server-frontend

**Comment by artonge** [comment]
Looking into it with more expertise about NC front-end tests, it looks to me that everything is alright.

[This PR](https://github.com/nextcloud/server/pull/27286) introduced jest as a test runner to replace mocha, but there was already only one test executed. All the other tests are executed by karma.

Closing, feel free to reopen if I am wrong.
