### ISSUE TITLE
Deprecation of php7.3

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#29258]
Continuation of https://github.com/nextcloud/server/issues/19341

php7.3 will run out of security support end of year. So I assume Nextcloud 23 will still support it but for 24 it makes no sense.

Should Nextcloud 23 warn that it's the last version to support 7.3? We did that for previous releases.

Ref https://www.php.net/supported-versions.php

cc @skjnldsv @nickvergessen @juliushaertl

**Comment by juliushaertl** [comment]
I'm all in for dropping 7.3 with 24 and showing a warning on 23 :+1: 

Distributions seem to have widely adopted 7.4 from the official packages with the latest releases according to https://pkgs.org/download/php. From older release we would basically only loose support for Debian 10 which is still on 7.3. But of course there are 3rdparty repo options like https://deb.sury.org/ or https://rpms.remirepo.net/.

**Comment by MichaIng** [comment]
Many thanks for showing theses stats and arguments, looks like it's worth it.

> Generally speaking it's how we've also handled other outdated php versions in the past, so this process isn't new.

This is why I mentioned that exactly this caused us quite some short and long term trouble in the past 😉. But it's fine, we have a strategy, I was just hoping to have some more time (less affected systems/users) until it takes effect.
