### ISSUE TITLE
Garbled text at top-right of add attachment popup

### ISSUE THREAD

**Issue by koreywithak** [nextcloud/server#2926]
![uploading](https://cloud.githubusercontent.com/assets/11006655/21616520/cafaef2c-d1af-11e6-8360-086535514ecb.png)

### Steps to reproduce
1. Within the Mail app of Nextcloud 11, click on the add attachment button for in a newly composed e-mail
2. At the top right there is a bunch of garbled text

### Expected behaviour
The text is probably supposed to be something meaningful

### Actual behaviour
I can't read it because it looks like many overlapping text boxes

### Mail app

**Mail app version:** (see apps admin page)
0.6.2
**Mailserver or service:** (e.g. Outlook, Yahoo, Gmail, Exchange,...)
Gmail
**Transport security - IMAP:** (None, SSL, TLS, STARTTLS) 
Unknown
**Transport security - SMTP:** (None, SSL, TLS, STARTTLS)
Unknown
**Number of accounts:**
1
**Mail app version build date:** (only if you are using a Nightly Build)
N/A

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Nginx 1.10
**Database:**
mariadb
**PHP version:**
7.0
**Version:** (see admin page)
Nextcloud 11
**Updated from an older version or fresh install:**
Fresh install, but migrated nextcloud folder, database
**List of activated apps:**
All available official apps
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```

**The content of config/config.php:**

<details>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your server installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

#### Client configuration
**Browser:**

**Operating system:**

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
<details>
```
Insert your server log here
```
</details>

##### Horde IMAP log (data/horde_imap.log)
<details>
```
Insert your horde IMAP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Horde SMTP log (data/horde_smtp.log)
<details>
```
Insert your horde SMTP log here, see https://github.com/nextcloud/mail#debug-mode
```
</details>

##### Browser log
<details>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```
</details>

**Comment by koreywithak** [comment]
This issue originated [HERE](https://github.com/nextcloud/mail/issues/269)

**Comment by MorrisJobke** [comment]
cc @jancborchardt @te-online @icewind1991 @nextcloud/javascript

**Comment by jancborchardt** [comment]
This has been fixed in the Mail app thanks to @lcalaresu! :)
https://github.com/nextcloud/mail/pull/380
