### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function getLogger()

### ISSUE THREAD

**Issue by InitusJames** [nextcloud/server#29270]
I've tried full reinstall of this docker image multiple times.

it's using a remove volume
and an MySQL database

It was working perfectly until the server was restarted due to a power outage,

Ive tried deleting all files from the NAS and deleting the DB from mySQL

it creates all the files and recreates the DB objects, but time and again it just fails to start :(

Fatal error: Uncaught Error: Call to a member function getLogger() on null in /var/www/html/index.php

my stack is basically jus this...

version: '2'

services:
  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    volumes:
      - NextCloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=user
      - MYSQL_HOST=192.168.0.252:3306
      
volumes:
  NextCloud:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=192.168.0.151,rw"
      device: ":/mnt/D2_310/nextcloud"

**Comment by InitusJames** [comment]
Fatal error: Uncaught Error: Call to a member function getLogger() on null in /var/www/html/index.php:71 Stack trace: #0 {main} thrown in /var/www/html/index.php on line 71

**Comment by InitusJames** [comment]
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.2. Set the 'ServerName' directive globally to suppress this message

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.2. Set the 'ServerName' directive globally to suppress this message

[Fri Oct 15 23:55:31.968609 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.51 (Debian) PHP/8.0.11 configured -- resuming normal operations

[Fri Oct 15 23:55:31.968674 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'

192.168.0.1 - - [15/Oct/2021:23:55:48 +0000] "GET / HTTP/1.1" 200 664 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36"

**Comment by martinorpa** [comment]
It works when running non NFS, but NFS don't

**Comment by martinorpa** [comment]
Works just point /var/www/html/data to your NFS NAS 

volumes:
  nextcloudnfs:
    driver: local # Must be set to avoid issues.
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.XX,timeo=14,tcp,rw,noatime" # XX NAS IP ADDRESS
      device: ":/mnt/nextcloud/"

 nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    links:
      - mysql
    ports:
      - 8080:80
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    volumes:
      - ./nextcloud:/var/www/html
      - nextcloudnfs:/var/www/html/data
    networks:
      - proxy-tier

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_ROOT_PASSWORD=nextcloud
    volumes:
      - ./nextcloud/db:/var/lib/mysql
    networks:
      - proxy-tier

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
