### ISSUE TITLE
feat: allowing or disallowing different accounts to be accessed through internet

### ISSUE THREAD

**Issue by jerabaul29** [nextcloud/server#29294]
Not sure if this is the right location to ask for the feature; if not, sorry, let me know where I should post it :) .

When having set up a nextcoud server to be accessible through the internet (for example with a guided, reverse DNS), is there a way to decide on an account to account basis if the account can be accessed through the internet vs from local network only?

For example, I would like to disable logging over the internet for my admin account (allowing only connection through the local network to the admin account), while allowing some user accounts to be accessed through the internet and the reverse DNS.

**Comment by joshtrichards** [comment]
See #46473 for a possible solution

**Comment by joshtrichards** [comment]
Fixed in #46473 (at least for admin accounts)
Documented in nextcloud/documentation#12059
