### ISSUE TITLE
Nextcloud Bug since V 22.x

### ISSUE THREAD

**Issue by Admin-Viatos** [nextcloud/server#29292]
English summary:

    after installation of a new Nextcloud 22 I create/store 50 Files/Folders
    all Files/Folders are visible
    I activate app " External storage support" without any connection
    now the bug appears
    only ca. 20 Files/Folders are visible

Seit dem Update auf NC22 kommt folgender Effekt zum Vorschein: es werden in jedem Verzeichnis nur noch so ca. 20 Files oder Folder angezeigt. Wenn man mit der Maus weiter nach unten fährt, werden nur noch in der unteren Zeile die Dateinamen als “Mouseover” angezeigt.

Eine tiefergehende Recherche zeigte als Ursache die App " External storage support". Wenn sie deaktiviert ist, sind alle Files / Folder im Verzeichnis sichtbar. Ist sie aktiviert, sind wieder nur noch ca. 20 Files / Folder im Verzeichnis sichtbar.

Es ist unabhängig von einer Verbindung; die aktivierte App führt zum Fehler.
Dieser Fehler erscheint auch auf einer neu installierten NC.

Server:

    Debian 11
    PHP7.4-FPM
    Apache 2.4.51
    MariaDB-Version 10.5.12
    8 Core / 32 GB RAM

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
