### ISSUE TITLE
X-Authenticated-User authentication mode

### ISSUE THREAD

**Issue by jmthackett** [nextcloud/server#2929]
https://tools.ietf.org/html/draft-stecher-icap-subid-00#section-3.4 describes a method of auth that delegates responsibility to a reverse proxy. The proxy sets the header and the application should trust that header, something like this:

X-Authenticated-User: my@user.account

This would be very useful for SSO scenarios, although I understand it is not a method that will work with desktop/mobile apps.

Being able to use this while still allowing LDAP auth from the apps would be fantastic.

Does this sound viable?

**Comment by go2sh** [comment]
There is already a  “Environment variable” authentication provider. I think its independent from where the variable comes from. This should already work. :-)

**Comment by LukasReschke** [comment]
> There is already a “Environment variable” authentication provider. I think its independent from where the variable comes from. This should already work. :-)

Correct.

**Comment by jmthackett** [comment]
Sorry to be a bother, but I can't find documentation for this anywhere.
Tried quite a few searches through the docs for 9, 10 and 11. Would
somebody charitably point me to the correct page?
