### ISSUE TITLE
CalDAV availibility settings design polishing

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#29319]
We should polish the design of the availability settings from https://github.com/nextcloud/server/issues/27422 / https://github.com/nextcloud/server/pull/27466 before the release of 23

This is what it looks like right now

![Bildschirmfoto von 2021-10-19 11-52-36](https://user-images.githubusercontent.com/1374172/137888475-85c49ccf-386f-4dd5-b2ed-180f6cc39688.png)

* Delete/Add buttons not aligned with the time pickers
* Text between time pickers has unbalanced white space left/right
* "Please select a time zone:" should possibly lose the ":"

@GretaD @nimishavijay may I ask you two to look into this? You've worked on the first version :)

**Comment by nimishavijay** [comment]
Got it! Some more thoughts from my end:
- Agreed with points 1 and 2
- Left align time zone picker with the time fields
- For point 3, how about "Please select a time zone:" → "Time zone:" (leaving out the ":" makes it look sort of like a heading of a table, especially if you align the time zone field with the time fields below)
- Change colour of trash icon to something lighter like grey, full black makes look harsh
- Maybe we can also add some text when there are so slots set in a day, like "No working hours set" or something similar
- I was also wondering if it would make sense to change the "Add slot" button to a plus icon and align all of them, regardless of whether or not a time field is filled
- How would it look with multiple time slots for one day? 
- What is the function of the save button? If this automatically saves then we can get rid of it

![image](https://user-images.githubusercontent.com/52440189/138048318-bc51e7e6-ccbf-453d-a4d4-0a989ad2b849.png)
Made some quick mockups, would love to hear thoughts from you and @GretaD as well
cc @jancborchardt whenever he sees this
