### ISSUE TITLE
Consider moving Profile into dedicated app

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#29323]
Doing that would make disabling the feature a bit easier.
Will clean up core a lot too

cc @Pytal

**Comment by blizzz** [comment]
State of consideration?

**Comment by Pytal** [comment]
> State of consideration?

Sounds good to me

**Comment by skjnldsv** [comment]
Care to tackle that for 26 ? :grin: :bowing_woman:

**Comment by Pytal** [comment]
> Care to tackle that for 26 ? 😁 🙇‍♀️

Sure :)
