### ISSUE TITLE
Invitation to see a link is classified as SPAM

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/server#2932]
### Steps to reproduce
1. send link to external user
2.
3.

### Expected behaviour
Tell us what should happen
should not be classified as SPAM

### Actual behaviour
Tell us what happens instead
mail program ( https://www.world4you.com/ ) classifies the message as SPAM - gmail works fine

### Server configuration
**Operating system**:
Debian 8
**Web server:**
apache
**Database:**
mysql
**PHP version:**
php7
**Nextcloud version:** (see Nextcloud admin page)
10
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated
**Where did you install Nextcloud from:**
source
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by ferdiga** [comment]
got many complaints - about classification as SPAM - probably also Apple

**Comment by Bugsbane** [comment]
This can be many, many things that have nothing to do with Nextcloud. It can be the setup of your mailer, who was previously using your dynamically signed IP address, the configuration of the spam filter on the receiving end, none of which the Nextcloud team has any influence over. 

I don't see anything likely to trigger spam filters in the default e-mail template, so I don't really see anything the Nextcloud team can do.

**Comment by ferdiga** [comment]
thanks for your comments, I was sending the mail from the nextcloud server instead via my mail provider.

**Comment by Gomez** [comment]
You check the mail/mailserver with this service to get more info: https://www.mail-tester.com/

**Comment by ferdiga** [comment]
Thanks Gomez
mail-tester gives the following result
IMO the "red" issues should be addressed by nextcloud developers, the user/admin can not change this.

![image](https://cloud.githubusercontent.com/assets/6248560/21698547/c0069c76-d397-11e6-8449-f90a4552854d.png)

**Comment by nickvergessen** [comment]
Do I understand that correctly? The issues are:
1. Reply-to and from have different emails
2. The HTML email has too few characters?

**Comment by ferdiga** [comment]
1. - I am not sure how the test works

the message source shows 
From: FGF via Nextcloud <user@my.domain>
Reply-To: fgf@gmail.com

probably the from should be the users mail not the the servers mail , would be logical, the recipient does not ans should not know the servers email.

2. - yes it says - "images with 800 - 1000 bytes of words- you should use more text in your input"

**Comment by FlorianFranzen** [comment]
@ferdiga To your first point: This is the proper way to do it. Else, depending on the domain you are impersonating, their SPF record might flag your mail as spam, making the issue even worse.

**Comment by MorrisJobke** [comment]
@LukasReschke While fixing #4209 could you also set the proper reply to header. Thanks

**Comment by MorrisJobke** [comment]
#4209 is fixed and we also improved the emails in 12 to be longer and contain more text. This issue should be solved then.
