### ISSUE TITLE
No printer icon present in official logos

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/server#29337]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Sort of. I am working on some issues on a NC app and found that there is no official icon for a printer. It would be very nice, if you could provide a logo with a printer/printout or something like that.

In [the dev manual](https://docs.nextcloud.com/server/22/developer_manual/design/icons.html) no printer icon is present.

Reference to the issue: https://github.com/nextcloud/cookbook/issues/728

**Describe the solution you'd like**
A logo visually compatible with the other logos ready to be used by app developers.

**Describe alternatives you've considered**
We could create and add our own logo. The risk is that if other apps start to allow for printing, there is a mixture of logos in the world.

If the chances are low that any other apps start printing and we should design something on ourself, feel free to tell us. We will do this then.

**Comment by joshtrichards** [comment]
Hi @christianlupus - Looks like you ended up using `vue-material-design-icons` in nextcloud/cookbook#1106 and that that is now documented in the Dev Manual:

https://docs.nextcloud.com/server/latest/developer_manual/html_css_design/icons.html?highlight=icons

Please close this Issue if you feel it's no longer necessary. :-)
