### ISSUE TITLE
OAuth2 authentication problem

### ISSUE THREAD

**Issue by JuanDaniel** [nextcloud/server#29348]
Hi everyone,

Today I upgraded my self-hosting Nextcloud to version 22.2.0 and I found that OAuth2 authentication is not working. I use it to connect to an external website (Wordpress). So I made somes test, this time with Postman and every time I get the same result when I try to get the token; **{"message":""}**. Take a look to the following image.

[https://drive.google.com/file/d/10QoNKHSXFEBUdKKdVxNHrw1Mz-zcqBXA/view?usp=sharing](url)

Here somes variables of my enviroment

- Ubuntu server 20.04
- PHP 7.4.3
- Mysql 8.0.26-0ubuntu0.20.04.3
- Apache 2.4.41

I remain at your disposal for any other specific needs you may have.

Thanks in advance

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
