### ISSUE TITLE
OC_Image->loadFromBase64, could not load

### ISSUE THREAD

**Issue by koreywithak** [nextcloud/server#2935]
### Steps to reproduce
1. The debug-level error "OC_Image->loadFromBase64, could not load" shows up often in my admin log.
2. This error seems to show even when I'm not specifically clicking on any pictures. It may be related to simply displaying thumbnails.
3. I did look around the forums but didn't see any issues I thought were related.

### Expected behaviour
No such error

### Actual behaviour
I receive this error

### Server configuration
**Operating system:**
Ubuntu 16.04.1
**Web server:**
nginx 1.10.0
**Database:**
mariadb 10.0
**PHP version:**
PHP7.0
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 11.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install, but migrated Nextcloud folder and database from an install on another computer, but also NC11.0
**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-11.0.0.tar.bz2
**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>
**List of activated apps:**
<details>
<summary>App list</summary>
All official apps as of 1/1/2017
</details>
**The content of config/config.php:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "ocw2lrcmig6j",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED BY USER***"
        ],
        "datadirectory": "\/media\/cloud_main\/nextcloud_data",
        "overwrite.cli.url": "https:\/\/***REMOVED BY USER***\/nextcloud",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "maintenance": false,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "loglevel": 0,
        "mail_smtpmode": "smtp",
        "mail_domain": "gmail.com",
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED BY USER***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "updater.release.channel": "stable"
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:**
no

### Client configuration
**Browser:**
Chrome 53.0.2785.116 or Nextcloud App 1.4.0
**Operating system:**
Windows 10 or Android 6.0.1

#### Web server error log
<details>
<summary>Web server error log</summary>
{"reqId":"uALaQ3zuVlfAiodNLzO4","remoteAddr":"***REMOVED BY USER***","app":"core","message":"OC_Image->loadFromBase64, could not load","level":0,"time":"2017-01-04T13:35:01+00:00","method":"GET","url":"\/nextcloud\/core\/preview.png?file=%2Fissues.txt&c=6d46be858619ff65de7bd44f5e8ec43b&x=32&y=32&forceIcon=0","user":"***REMOVED BY USER***","version":"11.0.0.10"}
</details>
#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
N/A
</details>
#### Browser log
<details>
<summary>Browser log</summary>
N/A
</details>

**Comment by nickvergessen** [comment]
Yeah, but that's just a debug log. Debug should not be selected for productive.
