### ISSUE TITLE
[Plasma highdpi] Status icon on the top right too big on highdpi

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#29353]
### Steps

1. Setup from git master 23582089f0ff6579706ebd80323cd4e45b9be732
2. Force font DPI to 144 (in fonts settings of Plasma) on a screen of 1980x1080
3. Login

### Expected result
Status icon has the same size like in Talk and other places.

### Actual result
Status icon is too big

<img width="50" alt="image" src="https://user-images.githubusercontent.com/277525/138245865-53b9dde1-1414-482e-8bad-c980548de314.png">

### Versions
Nextcloud server 23 git master 23582089f0ff6579706ebd80323cd4e45b9be732
Chromium Version 94.0.4606.81 (openSUSE Build) stable (64-bit)
Firefox 93
Opensuse Tumbleweed 20211016
plasma5 5.23.0-1.1

### Notes
I suspect that we maybe using the wrong units for that icon, need to check how it's done in other locations like in Talk.

@CarlSchwan

**Comment by PVince81** [comment]
still happening

we still need to [release nextcloud-vue](https://github.com/nextcloud/nextcloud-vue/issues/2357) and then update the lib on the server

**Comment by nickvergessen** [comment]
Unlikely to merge vue 5.0 into server within 2 weeks.
I guess we should backport that branch to 4.2.1 and release that?

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
