### ISSUE TITLE
Hide download button in Share Options does not hide the download button

### ISSUE THREAD

**Issue by dklinger** [nextcloud/server#29354]
### Steps to reproduce
1. Upload a photo to nextcloud
2. Share the photo via a link
3. Choose the option to hide the download button in the share options

### Expected behaviour
The download button is hidden when opening the link.

### Actual behaviour
The download button is shown and works.

### Server configuration

**Operating system: Unknown - Hosted Environment

**Web server: Unknown - Hosted Environment

**Database: MariaDB 10.4

**PHP version: PHP 8-0-FCGI

**Nextcloud version:** 22.2.0

**Updated from an older Nextcloud/ownCloud or fresh install: Updated from 20.something

**Where did you install Nextcloud from: Manual download from https://nextcloud.com/install/

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
![image](https://user-images.githubusercontent.com/2249766/138251524-2a98d75e-9668-4612-8630-71666432b0f5.png)

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'trusted_domains' => 
  array (
    0 => '.de',
    1 => '',
  ),
  'datadirectory' => '/xyz_data/data',
  'dbtype' => 'mysql',
  'version' => '22.2.0.2',
  'dbname' => '',
  'dbhost' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'forcessl' => true,
  'mail_from_address' => 'cloud',
  'mail_smtpmode' => 'sendmail',
  'mail_domain' => '',
  'loglevel' => 2,
  'log_rotate_size' => 536870912,
  'theme' => '',
  'maintenance' => false,
  'secret' => '',
  'forceSSLforSubdomains' => true,
  'trashbin_retention_obligation' => 'auto',
  'overwrite.cli.url' => '',
  'updater.release.channel' => 'stable',
  'mail_sendmailmode' => 'smtp',
  'app_install_overwrite' => 
  array (
    0 => 'jsloader',
    1 => 'occweb',
  ),
  'mysql.utf8mb4' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'updater.secret' => '',
  'hashingMemoryCost' => 2048,
  'hashingTimeCost' => 2,
  'hashingThreads' => 1,
  'mail_smtpsecure' => 'ssl',
  'mail_smtpport' => '465',
  'default_phone_region' => 'DE',
);
</details>

**Are you using encryption:** no

### Client configuration
**Browser:** Edge 95.0.1020.20

**Operating system:** Windows 10

**Comment by GAS85** [comment]
Will add that there are 2 Download buttons and only one is hidden. Please find below 2 screenshots with Download enabled and disabled:
![grafik](https://user-images.githubusercontent.com/6813635/142864529-50c774b0-ec4c-4e34-875e-de69b526de17.png)
![grafik](https://user-images.githubusercontent.com/6813635/142864538-ced6c47a-418c-4983-a739-85663d99c339.png)

**Comment by szaimen** [comment]
fixed with https://github.com/nextcloud/server/pull/31169
