### ISSUE TITLE
Grant access visual / graphic issue

### ISSUE THREAD

**Issue by JuanDaniel** [nextcloud/server#29350]
Hi there,

This time I would report a visual / graphic issue. I made a video describing in detail the detected problem, so please look at it in the following link.

https://user-images.githubusercontent.com/3902676/138261115-28f32b9a-42c6-4db7-b387-9d89a3bbc804.mp4

In fact, when the user click the button to grant access, the buton move indicating a false idea to the user who must click on it again. 90% of the users of my institution click again, so the system denies them access. I think one idea could be to disable the button after clicking or hide it.

Thanks in advance

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
