### ISSUE TITLE
[21.0.5] command line update to 22.2.0 fails with certificate exception

### ISSUE THREAD

**Issue by tuxmaster5000** [nextcloud/server#29352]
### Steps to reproduce
1. call sudo -u apache scl enable php74 "php --define apc.enable_cli=1 updater/updater.phar"

### Expected behaviour
Like in any upgrade before, that the upgrade starts,

### Actual behaviour
Only this error will shown:
Nextcloud Updater - version: v20.0.0beta4-11-g68fa0d4
Current version is 21.0.5.
                                                                                    
[Exception]                                                                           
Could not do request to updater server: Peer's Certificate issuer is not recognized.  

### Server configuration

**Operating system:** CentOS 7.9

**Web server:** apache

**Database:** mariadb

**PHP version:** 7.4 (from remi)

**Nextcloud version:**  21.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** Updates from version to version

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.4
  - camerarawpreviews: 0.7.12
  - checksum: 1.1.2
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 4.0.3
  - contactsinteraction: 1.2.0
  - dav: 1.17.1
  - dicomviewer: 1.2.2
  - drawio: 1.0.1
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_videoplayer: 1.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - piwik: 0.8.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - quota_warning: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - socialsharing_email: 2.2.0
  - support: 1.4.0
  - survey_client: 1.9.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_u2f: 6.2.0
  - updatenotification: 1.11.0
  - viewer: 1.5.0
  - workflowengine: 2.3.1
Disabled:
  - accessibility
  - activity
  - admin_audit
  - dashboard
  - encryption
  - federation
  - files_external
  - files_trashbin
  - files_versions
  - firstrunwizard
  - systemtags
  - user_ldap
  - user_status
  - weather_status

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "speicher.terrortux.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "maxZipInputSize": 83886080,
        "allowZipDownload": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "log_type": "file",
        "loglevel": "1",
        "logfile": "data\/nextcloud.log",
        "logtimezone": "Europe\/Berlin",
        "log_authfailip": true,
        "theme": "",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "maintenance": false,
        "asset-pipeline.enabled": true,
        "updatechecker": false,
        "htaccess.RewriteBase": "\/",
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mysql.utf8mb4": true,
        "overwrite.cli.url": "https:\/\/XXXXXXXX",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "dicomviewer"
        ],
        "default_phone_region": "DE",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

The server itself is using an cacert.org cert.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by tuxmaster5000** [comment]
same on 24.0.9 
```
sudo -u apache -- scl enable php80 "php updater/updater.phar"
Nextcloud Updater - version: v24.0.0beta3-1-g67bf13b dirty

Current version is 24.0.9.

                                                                                        
  [Exception]                                                                           
  Could not do request to updater server: Peer's Certificate issuer is not recognized.  
                                                                                        

update [--no-backup]
```
I think the simplest solution will be switch to another ca.

**Comment by szaimen** [comment]
Is it possible that your servers CA are not up-to-date?

**Comment by tuxmaster5000** [comment]
It will be up to date, but for security reasons, the Let's Crypt CA is blocked. Because it will not supporting of revoking misused certificates.

**Comment by szaimen** [comment]
Can you re-add the Lets Crypt CA and check if that makes it work?

**Comment by tuxmaster5000** [comment]
Not really, until the installer has an option to specify another CA file.
