### ISSUE TITLE
!!! Path '' is not accessible or present !!!

### ISSUE THREAD

**Issue by koreywithak** [nextcloud/server#2936]
### Steps to reproduce
1. This happens every 15 minutes with the maintenance cron job
2. It displays as a debug error in the admin logs via the web

### Expected behaviour
No such error

### Actual behaviour
I receive this error

### Server configuration
**Operating system:**
Ubuntu 16.04.1
**Web server:**
nginx 1.10.0
**Database:**
mariadb 10.0
**PHP version:**
PHP7.0
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 11.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install, but migrated Nextcloud folder and database from an install on another computer, but also NC11.0
**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-11.0.0.tar.bz2
**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>
**List of activated apps:**
<details>
<summary>App list</summary>
All official apps as of 1/1/2017
</details>
**The content of config/config.php:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "ocw2lrcmig6j",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED BY USER***"
        ],
        "datadirectory": "\/media\/cloud_main\/nextcloud_data",
        "overwrite.cli.url": "https:\/\/***REMOVED BY USER***\/nextcloud",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "maintenance": false,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "loglevel": 0,
        "mail_smtpmode": "smtp",
        "mail_domain": "gmail.com",
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED BY USER***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "updater.release.channel": "stable"
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:**
no

### Client configuration
**Browser:**
Chrome 53.0.2785.116 or Nextcloud App 1.4.0
**Operating system:**
Windows 10 or Android 6.0.1

#### Web server error log
<details>
<summary>Web server error log</summary>
{"reqId":"\/8MWPYpEPl05KbMGuC6p","remoteAddr":"","app":"OC\\Files\\Cache\\Scanner","message":"!!! Path '' is not accessible or present !!!","level":0,"time":"2016-10-30T02:45:03+00:00","method":"--","url":"--","user":"--"}
</details>
#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
N/A
</details>
#### Browser log
<details>
<summary>Browser log</summary>
N/A
</details>

**Comment by nickvergessen** [comment]
Well increase your log_level to 1 or something, when you don't want to see debug messages in your log.

**Comment by koreywithak** [comment]
@nickvergessen  Regardless of what log level this is set as, it sounds like something that shouldn't be happening (probably should be "info", "warning" or "error"). I don't recall seeing it before upgrading to NC11.  Increasing the log level will just hide the issue. I'd prefer a good (less snide) explanation of why it is acceptable for the default cron job to not be able to locate a path.

**Comment by nickvergessen** [comment]
Can you provide a backup of your `jobs` database table?

**Comment by koreywithak** [comment]
I know where most logs are and how to get to the mariadb table, but I don't know what the jobs database table is...

**Comment by nickvergessen** [comment]
in mariadb in your database `nextcloud` there should a table named `oc_jobs`

**Comment by koreywithak** [comment]
-- MySQL dump 10.15  Distrib 10.0.28-MariaDB, for debian-linux-gnu (x86_64)
--
-- Host: localhost    Database: localhost
-- ------------------------------------------------------
-- Server version	10.0.28-MariaDB-0ubuntu0.16.04.1

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `oc_jobs`
--

DROP TABLE IF EXISTS `oc_jobs`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `oc_jobs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `class` varchar(255) COLLATE utf8_bin NOT NULL DEFAULT '',
  `argument` varchar(4000) COLLATE utf8_bin NOT NULL DEFAULT '',
  `last_run` int(11) DEFAULT '0',
  `last_checked` int(11) DEFAULT '0',
  `reserved_at` int(11) DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `job_class_index` (`class`)
) ENGINE=InnoDB AUTO_INCREMENT=19 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
/*!40101 SET character_set_client = @saved_cs_client */;

--
-- Dumping data for table `oc_jobs`
--

LOCK TABLES `oc_jobs` WRITE;
/*!40000 ALTER TABLE `oc_jobs` DISABLE KEYS */;
INSERT INTO `oc_jobs` VALUES (1,'OCA\\Files\\BackgroundJob\\ScanFiles','null',1484084701,1484084701,0),(2,'OCA\\Files\\BackgroundJob\\DeleteOrphanedItems','null',1484083801,1484084701,0),(3,'OCA\\Files\\BackgroundJob\\CleanupFileLocks','null',1484084701,1484084701,0),(4,'OCA\\DAV\\CardDAV\\Sync\\SyncJob','null',0,1484064002,1484064002),(5,'OCA\\Files_Versions\\BackgroundJob\\ExpireVersions','null',1484083801,1484084701,0),(6,'OCA\\Federation\\SyncJob','null',1484047801,1484084701,0),(7,'OCA\\Activity\\BackgroundJob\\EmailNotification','null',1484083801,1484084701,0),(8,'OCA\\Activity\\BackgroundJob\\ExpireActivities','null',1484040601,1484084701,0),(9,'OCA\\UpdateNotification\\Notification\\BackgroundJob','null',1484040601,1484084701,0),(10,'OCA\\Files_Sharing\\DeleteOrphanedSharesJob','null',1484083801,1484084701,0),(11,'OCA\\Files_Sharing\\ExpireSharesJob','null',1484073001,1484084701,0),(13,'OCA\\Files_Trashbin\\BackgroundJob\\ExpireTrash','null',1484082901,1484084701,0),(14,'\\OC\\Authentication\\Token\\DefaultTokenCleanupJob','null',1484084701,1484084701,0),(15,'OCA\\UpdateNotification\\ResetTokenBackgroundJob','null',1484084701,1484084701,0),(17,'OCA\\DAV\\CardDAV\\SyncJob','null',1484008202,1484084701,0),(18,'OCA\\NextcloudAnnouncements\\Cron\\Crawler','null',1484008202,1484084701,0);
/*!40000 ALTER TABLE `oc_jobs` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2017-01-10 16:47:43

**Comment by mirko** [comment]
I'm seeing this very message on the v18 branch and wonder what the fix is - and why this ticket was closed without any reason / solution stated.

**Comment by nickvergessen** [comment]
This issue is more than 3 years old. Please create a new one and fill the issue template
