### ISSUE TITLE
Remote shares may be created even if the remote server is not a Nextcloud server

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#29369]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

## Description
When [a remote share is created](https://github.com/nextcloud/server/blob/b78f3a57d1d05fb5f81ec8361139b64a3e54d7b0/apps/federatedfilesharing/lib/FederatedShareProvider.php#L290) first [the OCM endpoint of the remote server is tried](https://github.com/nextcloud/server/blob/b78f3a57d1d05fb5f81ec8361139b64a3e54d7b0/apps/federatedfilesharing/lib/Notifications.php#L351). If [that is not available](https://github.com/nextcloud/server/blob/ebf35fb38a770f26b5db4d6eebba18a28fa10dcd/lib/private/Federation/CloudFederationProviderManager.php#L137) then the legacy endpoint is tried instead.

If the remote server [does not provide a different endpoint](https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/private/OCS/DiscoveryService.php#L68), a [POST request to _/ocs/v2.php/cloud/shares_ is sent](https://github.com/nextcloud/server/blob/b78f3a57d1d05fb5f81ec8361139b64a3e54d7b0/apps/federatedfilesharing/lib/Notifications.php#L380). If that request succeeds it is assumed that there is a Nextcloud server listening and that the remote share could be successfully created.

However, if the target domain just runs a regular web server that, instead of returning an error 404, redirects to a different page without an error when a URL is not found, the share would be created too.

## Steps to reproduce
- Open the Sharing section in the Administration settings
- Ensure that _Allow users on this server to send shares to other servers_ is enabled
- Open the Files app
- Open the _Sharing_ tab for a file
- In the field to set the sharee ID, type _test@ecosia.org_ (or the domain of any other webpage that redirects to its home page when trying to access a not found URL)
- In the autocompletion suggestions click on _test on ecosia.org_

### Expected behaviour

An error is shown and the remote share is not created

### Actual behaviour

The remote share is created

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
