### ISSUE TITLE
Push Notification for shared calendar although deactivated

### ISSUE THREAD

**Issue by hul51u** [nextcloud/server#29379]
### Steps to reproduce
1. User A shares a calendar with user user B (readonly permissions).
2. User B deactivates calendar push notifications.
3. User A changes or creates calendar events.

### Expected behaviour
User B souldn't get push notifications on such events.

### Actual behaviour
User B gets push notifications on calendar changes by User A.

### Calendar app
2.3.4

### Server configuration

**Operating system**: (e.g. Debian 8)
Ubuntu 20.04.3

**Web server:** (e.g. Apache, Nginx,...)
Apache 2.4.41

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
mariadb  Ver 15.1 Distrib 10.3.31-MariaDB

**PHP version:** 
7.4.3

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
22.2.0

**Updated from an older installed version or fresh install:**
update

**List of activated apps:**
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - apporder: 0.13.0
  - audioplayer: 3.2.2
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.4
  - camerarawpreviews: 0.7.12
  - checksum: 1.1.2
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.3
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - event_update_notification: 1.3.0
  - external: 3.9.0
  - extract: 1.3.2
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_external: 1.13.0
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - forms: 2.3.0
  - health: 1.3.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - mail: 1.10.5
  - maps: 0.1.9
  - metadata: 0.14.0
  - music: 1.4.0
  - nextcloud_announcements: 1.11.0
  - notes: 4.1.1
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - polls: 3.3.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - richdocuments: 4.2.3
  - richdocumentscode_arm64: 6.4.1303
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - spreed: 12.1.2
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_totp: 6.1.0
  - updatenotification: 1.12.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflow_pdf_converter: 1.7.0
  - workflowengine: 2.4.0

Disabled:
  - encryption
  - firstrunwizard
  - user_ldap
  - user_status

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
