### ISSUE TITLE
"CSRF check failed" error message

### ISSUE THREAD

**Issue by koreywithak** [nextcloud/server#2938]
### Steps to reproduce
1. This seems to happen when I try to delete a file using the Nextcloud App from my Android phone
2. It displays as a debug error in the admin logs via the web and "no app in contex"
3. The app also states that "removal failed" for the file, however, after refreshing, the file is indeed removed.
4. I found other posts in the nextcloud support community with similar errors but not clear indication of a resolution that applies to my situation.

### Expected behaviour
No such error and no "removal failed" toast on my android device

### Actual behaviour
I receive this error

### Server configuration
**Operating system:**
Ubuntu 16.04.1
**Web server:**
nginx 1.10.0
**Database:**
mariadb 10.0
**PHP version:**
PHP7.0
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 11.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install, but migrated Nextcloud folder and database from an install on another computer, but also NC11.0
**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-11.0.0.tar.bz2
**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>
**List of activated apps:**
<details>
<summary>App list</summary>
All official apps as of 1/1/2017
</details>
**The content of config/config.php:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "ocw2lrcmig6j",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED BY USER***"
        ],
        "datadirectory": "\/media\/cloud_main\/nextcloud_data",
        "overwrite.cli.url": "https:\/\/***REMOVED BY USER***\/nextcloud",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "maintenance": false,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "loglevel": 0,
        "mail_smtpmode": "smtp",
        "mail_domain": "gmail.com",
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED BY USER***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "updater.release.channel": "stable"
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:**
no

### Client configuration
**Browser:**
Chrome 53.0.2785.116 or Nextcloud App 1.4.0
**Operating system:**
Windows 10 or Android 6.0.1

#### Web server error log
<details>
<summary>Web server error log</summary>
{"reqId":"\/s0KCD7opDe7NY1IiPy7","remoteAddr":"*****REMOVED BY USER******","app":"no app in context","message":"CSRF check failed","level":0,"time":"2017-01-03T03:28:33+00:00","method":"GET","url":"\/nextcloud\/ocs\/v1.php\/cloud\/users\/*****REMOVED BY USER******?format=json","user":"*****REMOVED BY USER******","version":"11.0.0.10"}
</details>
#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
N/A
</details>
#### Browser log
<details>
<summary>Browser log</summary>
N/A
</details>

**Comment by nickvergessen** [comment]
Well that's a debug message. You see that because you enabled debug in your config:
```
'loglevel' => 0,
```
Setting the value to 1 should stop doing that.

For the delete error please open an issue in the android repository.

**Comment by koreywithak** [comment]
@nickvergessen  I'll make a separate issue for the deletion problem. Nevertheless, according to these other posts, the CSRF check doesn't seem to be something benign. Is it really something to be ignored?
[post 1](https://github.com/owncloud/core/issues/25927)
[post 2](https://forum.owncloud.org/viewtopic.php?f=26&t=21889&start=10)
