### ISSUE TITLE
"Error uploading File Not Found" when uploading files > 25MB 

### ISSUE THREAD

**Issue by DatCSharpDev** [nextcloud/server#2939]
Hi,

I cannot upload files bigger than 25 MB. When I do, I get the following error message "Error uploading FILENAME.extension, Not Found"

### Steps to reproduce
1. Select a folder
2. Click Add file > Upload
3. Select a file bigger than 25MB
4. An error message shows at the top of the windows, reading "Error uploading FILE, Not Found"

### Expected behaviour
The file gets uploaded and is accessible from the Web interface.

### Actual behaviour
I get the error above, refreshing doesn't show the file and it isn't present in the filesystem either.

### Server configuration
**Operating system**: Ubuntu 16.04 Server

**Web server:**
Apache 2.4

**Database:**
MySQL

**PHP version:**
PHP 7.0.8-0ubuntu0.16.04.3 with Zend Engine v3.0.0

**Nextcloud version:** (see Nextcloud admin page)
10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
No

**Where did you install Nextcloud from:**
From the official Nextcloud website

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

Enabled:                                      
  - activity: 2.3.2                           
  - calendar: 1.4.1                           
  - comments: 1.0.0                           
  - contacts: 1.5.1                           
  - dav: 1.0.1                                
  - documents: 0.13.1                         
  - federatedfilesharing: 1.0.1               
  - federation: 1.0.1                         
  - files: 1.5.2                              
  - files_pdfviewer: 0.8.1                    
  - files_sharing: 1.0.0                      
  - files_texteditor: 2.1                     
  - files_trashbin: 1.0.0                     
  - files_versions: 1.3.0                     
  - files_videoplayer: 0.9.8                  
  - firstrunwizard: 1.1                       
  - gallery: 15.0.0                           
  - notifications: 0.3.0                      
  - ownbackup: 16.11.0                        
  - ownnote: 1.08                             
  - password_policy: 1.0.0                    
  - provisioning_api: 1.0.0                   
  - serverinfo: 1.1.1                         
  - survey_client: 0.1.5                      
  - systemtags: 1.0.2                         
  - templateeditor: 0.1                       
  - theming: 1.0.1                            
  - updatenotification: 1.0.1                 
  - workflowengine: 1.0.1                     
Disabled:                                     
  - admin_audit                               
  - encryption                                
  - external                                  
  - files_accesscontrol                       
  - files_automatedtagging                    
  - files_external                            
  - files_retention                           
  - user_external                             
  - user_ldap                                 
  - user_saml                                 
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'MY_INSTANCE_ID',
  'passwordsalt' => 'MY_SALT',
  'secret' => 'MY_SECRET',
  'trusted_domains' =>
  array (
    0 => 'MY_IP',
    1 => 'MY_DOMAIN',
  ),
  'datadirectory' => '/media/NAS/',
  'overwrite.cli.url' => 'http://MY_IP/nextcloud',
  'dbtype' => 'mysql',
  'version' => '9.1.1.5',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => 'MY_DB_PASSWORD',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'MY_NAME',
  'mail_domain' => 'MY_EMAIL',
  'mail_smtphost' => 'MY_SMTP_SERVER',
  'mail_smtpport' => '25',
  'updater.secret' => 'MY_SECRET',
  'maintenance' => false,
  'loglevel' => 0,
);

```

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

SMB

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No

#### LDAP configuration (delete this part if not used)

<details>
<summary>LDAP config</summary>

</details>

### Client configuration

**Browser:**

Firefox 50.1.0

**Operating system:**

Windows 7 Pro / Ubuntu Desktop 16.04

#### Web server error log

<details>
<summary>Web server error log</summary>
</details>

#### Nextcloud log (data/nextcloud.log)

<details>
<summary>Nextcloud log</summary>
</details>

#### Browser log

<details>
<summary>Browser log</summary>

</details>

**Comment by MorrisJobke** [comment]
Please ask for help in the forums. This works on many instances and we haven't seen any issues. This looks more like a setup issue. 

See also this page in the documentation https://docs.nextcloud.com/server/12/admin_manual/installation/source_installation.html#apache-web-server-configuration

Otherwise ask for help in the forums: https://help.nextcloud.com/
