### ISSUE TITLE
Fixing authentication to servers without mod_rewrite (Webfaction)

### ISSUE THREAD

**Issue by filipesaraiva** [nextcloud/server#294]
Hello NextCloud developers, I had this problem since the old times of ownCloud, and all the time when I need to update my ownCloud instance I need to apply this patch. It have the same behavior in NextCloud.

The problem is described [here](https://community.webfaction.com/questions/7249/is-possible-http-authentication-with-php):

> The main HTTP authentication examples in the PHP documentation don't work on our servers because we use php-cgi to serve your PHP sites.
> The common workarounds for that problem involve setting a HTTP_AUTHENTICATION environment variable via mod_rewrite, but that doesn't work on our servers because our php-cgi environment runs on Apache with suExec, which does not pass environment variables to CGI scripts.

A developer created a [patch](http://www.blaicher.com/2012/07/fixing-authentication-of-owncloud-for-webfaction/) to solve it. In past I submitted an [issue](https://github.com/owncloud/core/issues/10318) and a [pull request](https://github.com/owncloud/core/pull/13411) with this patch, but a developer talked the best way to fix it is creating an application to provide authentication using a specific method for this case.

Cheers;

**Comment by MorrisJobke** [comment]
The app basically should do this:

```
//sett http auth headers for Webfaction workaround
if(isset($_GET['Authorization']) && preg_match('/Basic\s+(.*)$/i', $_GET['Authorization'], $matches))
{
    list($name, $password) = explode(':', base64_decode($matches[1]));
    $_SERVER['PHP_AUTH_USER'] = strip_tags($name);
    $_SERVER['PHP_AUTH_PW'] = strip_tags($password);
}
```

within the `appinfo/app.php` and specify that it is an authentication app (so it's loaded earlier): https://github.com/nextcloud/server/blob/969cfa24f79318338793a6e8f310764a2345d33a/apps/user_ldap/appinfo/info.xml#L13-L15

Is this correct @LukasReschke ?

**Comment by filipesaraiva** [comment]
Does the app need to change the .htaccess too?

**Comment by nickvergessen** [comment]
No, the app only needs to execute the code from above in it's app.php

**Comment by filipesaraiva** [comment]
Hi, why did you close it? Was that code added in NextCloud?

**Comment by nickvergessen** [comment]
No, since it should be an app on it's own
