### ISSUE TITLE
Double quotes in folder name creates display problem

### ISSUE THREAD

**Issue by camillem** [nextcloud/server#2942]
### Steps to reproduce
1. In your file browser, inside a synchronised folder, Create a subfolder named 1-NormalName
2. Create a subfolder named 2-Name"With"Quotes
3. Create a subfolder named 3-OtherNormalName
4. Let your folder get synhronized
5. Open the folder in your web browser
### Expected behaviour
The three subfolders should be displayed

### Actual behaviour
Only the first subfolder is displayed
Please see attached screenshots
![nautilusafter](https://cloud.githubusercontent.com/assets/438000/21655123/f608c9aa-d2b8-11e6-926a-b141e2bc42ba.png)
![nautilusbefore](https://cloud.githubusercontent.com/assets/438000/21655126/f60f89c0-d2b8-11e6-9cd3-6e6bc6aa569e.png)
![webafter](https://cloud.githubusercontent.com/assets/438000/21655124/f60f5734-d2b8-11e6-8102-c8b284e00260.png)
![webbefore](https://cloud.githubusercontent.com/assets/438000/21655125/f60f6972-d2b8-11e6-9861-b80ae9a02f8b.png)

### Server configuration
**Operating system**:

**Web server:**

**Database:**
Type: mysql
Version: 10.0.28
**PHP version:**
Version: 5.6.28
**Nextcloud version:** (see Nextcloud admin page)
11.0.0 (stable)
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
Installed at owncube.com
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Firefox 50.1.0
**Operating system:**
Ubuntu 16.04 LTS
#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment]
Should be fixed with https://github.com/nextcloud/server/pull/2776
Can you test it?

**Comment by camillem** [comment]
Thanks for the fix. I can't test right now as I haven't set up any dev env (I'm just using an hosted instance)
