### ISSUE TITLE
Files scan complains even when NFD compatibility is on

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#29438]
### Steps

1. Setup SMB external storage
2. Put a file called "bête.txt" (make sure to **copy-paste this exact string** as it contains an NFD encoded accented character)
3. Run `occ files:scan --all`
4. Enable NFD encoding compatibility for the external storage
5. Run `occ files:scan --all`

### Expected result
At step 3 a warning appears that the file might not be accessible.
No warning at step 5.
File is accessible in the web UI after enabling compatibility mode.

### Actual result
Warning appears at both step 3 and 5.
File is accessible in the web UI after enabling compatibility mode.

### Versions
Tested with v21.0.4

### Analysis

It seems that the scanner is not checking if the compatibility wrapper was enabled on the current storage so it always compares the file names to show the warning.
https://github.com/nextcloud/server/blob/v21.0.4/apps/files/lib/Command/Scan.php#L111

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
