### ISSUE TITLE
MacOSX CalDAV/CardDAV + LDAP not working ===> Nextcloud UUID used in LDAP authentication instead of Username

### ISSUE THREAD

**Issue by itmanagerro** [nextcloud/server#29433]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Enable LDAP Authentication
2. Generate new users ==> UUID
3. Export "Nextcloud Profile" to iOS and install it
4. "Unable to authenticate with username/password"

### Expected behaviour
CalDav/CardDav should work with LDAP auth backend

### Actual behaviour
Nextcloud does not know the "UUID" of the LDAP generated (only available inside Nextcloud)

### Server configuration

**Operating system:** Doesn't matter

**Web server:** Nginx

**Database:** SQL

**PHP version:** 7.4

**Nextcloud version:** 22

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated gradually from 14

**Where did you install Nextcloud from:** Source

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by itmanagerro** [comment]
^^ push ^^

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by htbrown** [comment]
FWIW I'm still facing this issue on Nextcloud 25.0.3. Let me know if there's anything more I can provide to help other than that I'm using the latest apache image from Docker, an Active Directory domain as an LDAP backend and have changed the internal username attribute to samaccountname for the sake of keeping federation IDs neat.

**Comment by htbrown** [comment]
Having just said that, I've just been able to connect through macOS/iOS anyway. Not sure if that shows whether it's unreliable or just my server playing up. Sorry to be unhelpful.

**Comment by cybertschunk** [comment]
hey everybody, we are experiencing the same issue on Nextcloud 25.0.3.

**Comment by tekeous** [comment]
Yes I can reproduce the issue on Nextcloud 27.1.4. LDAP provisioned my account with UUID as username, although I login with UID or email. My email is on my Nextcloud profile. However when generating a iOS config it uses UUID as the username and does not work. 

I see from the [LDAP documentation](https://docs.nextcloud.com/server/stable/admin_manual/configuration_user/user_auth_ldap.html?highlight=ldap) that using UUID as Nextcloud’s internal username is recommended and expected behavior, so mapping UID into Nextcloud is not a solution. 

Config generation should check for “was this account made by LDAP” and if so, use email or UID to log in. Group assignment could work for this.

**Comment by joshtrichards** [comment]
Closing per:

- https://github.com/nextcloud/server/pull/31038#pullrequestreview-874090201
