### ISSUE TITLE
Date shown on event invitation not working for repeating event set in nextcloud agenda when next occurence is edited

### ISSUE THREAD

**Issue by ImaCrea** [nextcloud/server#29460]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Edit the date of the next occurrence of an event which has a repetition activated
1. Receive an invitation through email about it
2. See that date shown is the one from the first event in the serie and not the most recent to come which has been modified

### Expected behaviour
The date shown in the mail invitation should be one of the next event to come with the updated date. It should show Thursday November 4th 2021.

### Actual behaviour
Our monthly call is on Wednesday but I changed the date of our next one exceptionally to happen on Thursday. That change triggered a new invitation mail to our guests but inside was written the "date" of the first Wednesday of the serie and not the date of next event which is actually happening on Thursday.

![Capture d’écran 2021-10-27 à 15 41 45](https://user-images.githubusercontent.com/764332/139078155-8112edec-e734-44d3-91aa-325412a431e3.png)

### Server configuration

**Nextcloud version:** 20.0.13

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
