### ISSUE TITLE
No invitation email for events of read only calenders

### ISSUE THREAD

**Issue by eri451** [nextcloud/server#29471]
### Problem
* Alice is member of group grpA
* Bob is member of group grpB
* admin created a calendar calA, that is shared with group grpA (writable) and group grpB (read only)
* Alice creates an event on calendar calA and invites Bob to the appointment
* Bob will __not__ be notified
* Bob cannot confirm nor deny the invite

### workaround
* Calendar calA is writable to both group grpA and group grpB

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by shu0406** [comment]
Still no Mail invitation and no push notification for person B who has only read access to Calendar A. 

NC 25.0.4 , Calendar 4.2.4

**Comment by SebastianKrupinski** [comment]
Tested on version 30. Working correctly
