### ISSUE TITLE
Remove expire data

### ISSUE THREAD

**Issue by antiuser** [nextcloud/server#29499]
Hi there!
Will be great if folder author has feature to point expire date file/folder after which date file/folder will be removed.
Thats comfortable to save dynamic data which we are published, but this files not useful after some date and author forget to remove them (this is useful for compact data on disk array).
What are you thinking about this?
Thanks!

**Comment by alx-tuilmenau** [comment]
Maybe use https://apps.nextcloud.com/apps/files_retention in combination with some flow "Files automated tagging" rules ?

**Comment by antiuser** [comment]
> Maybe use https://apps.nextcloud.com/apps/files_retention in combination with some flow "Files automated tagging" rules ?

Hmmm, interesting, but how can i use auto tagging for files in specified group folders?

**Comment by joshtrichards** [comment]
https://docs.nextcloud.com/server/latest/admin_manual/file_workflows/automated_tagging.html
