### ISSUE TITLE
Allow Folder upload when select file drop "upload only" shared link

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/server#29496]
Currently when creating a share via linl and select file drop upload only the user will only be able to upload files but if a user has a-lot off files and organized within folders when dragging the folder only the files upload. It would be nice to have the option under the files upload to also be able to upload folders 

 I know when i select the option Allow upload and editing the shared link will allow the users to then upload the files and folders but then I'm giving the users editing right and i just want them to upload.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by hoccontrol** [comment]
This would be tremendously useful, having nothing organized makes life so much harder. This is also a standard for any other similar feature types i know off. Eg. Synology or Dropbox etc.

**Comment by stleitner** [comment]
+1
