### ISSUE TITLE
File not found on welcome screen with Nginx

### ISSUE THREAD

**Issue by Neraste** [nextcloud/server#295]
Hi Nextcloud team !

I have troubles on a fresh install of Nextcloud using Nginx (with config file from the [documentation](https://docs.nextcloud.org/server/9/admin_manual/installation/nginx_owncloud_9x.html)): I get a "File not found" error message on the front page of the app (root URL). No login screen.

The problem may come from this directive in the nginx config file (see the logs):

```
location / {
    rewrite ^ /index.php$uri;
}
```

### Steps to reproduce
1. Install Nextcloud;
2. Set up the trusted URL;
3. Go on that URL.

### Expected behaviour
If logged, the file app (or another one) should appear.
If not, the login screen should appear.

### Actual behaviour
I get the following error message:

> File not found
> The specified document has not been found on the server.
> You can click here to return to Nextcloud.

I get the login screen by adding `/login` to the URL, and I get the File app with `apps/files/`.

### Server configuration
**Operating system:** OpenSUSE 13.2 on armv7l

**Web server:** nginx 1.10.1

**Database:** MariaDB 10.0.25-2.24.1

**PHP version:** PHP 5.6.1-66.1

**Nextcloud version:** 9.0.51.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** From sources

**Signing status (Nextcloud 9.0 and above):**

```
No errors have been found.
```

**List of activated apps:** (fresh install, should be the default ones)

```
Enabled:
  - activity: 2.2.1
  - admin_audit: 1.0.0
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.org"
        ],
        "datadirectory": "\/data\/safe\/cloud",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "9.0.51.0",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "ocmou0sxfmfl"
    }
}
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 47, Chromium 51.0.2704.103 (64-bit)

**Operating system:** OpenSUSE Tumbleweed

#### Web server error log
```
2016/07/02 22:55:09 [error] 30503#30503: *587 FastCGI sent in stderr: "Unable to open primary script: /srv/www/cloud/nextcloud-latest/index.php/index.php (No such file or directory)" while reading response header from upstream, client: 192.168.1.11, server: cloud.example.org, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "cloud.example.org"
```

**Comment by Bugsbane** [comment]
I don't know if it's the same issue, but when I set strong directory permissions as outlined at:
https://docs.nextcloud.org/server/9/admin_manual/installation/installation_wizard.html#setting-strong-directory-permissions

...I also get a blank screen with just "file not found". When I set my permissions to something much more insecure, my Nextcloud server goes back to operating as normal (albeit not secure). I'm also on NGINX (I installed Yunohost, which is based on Debian Jessie). I'm in the process of trying to figure out how to get the most secure settings that still let Nextcloud function.

**Comment by Neraste** [comment]
> ...I also get a blank screen with just "file not found"

I get more than a blank screen. It is the regular 404 screen with the "file not found" message (i.e. not a Nginx error message).

>  When I set my permissions to something much more insecure

What permission did you set on which file?

**Comment by Bugsbane** [comment]
> What permission did you set on which file?

Well, remember, this was for testing, not production, but basically I 755'd the entire Nextcloud directory+ the entire separate Data directory (as a test, I VBhave no intention of keeping it open like that). I could probably do some testing and narrow it down if it's of any particular help.

**Comment by Neraste** [comment]
I have tried it and it does not do anything. I am pretty sure it comes from the Nginx site configuration.

**Comment by MorrisJobke** [comment]
@Neraste Could you try: https://github.com/nextcloud/server/issues/316#issuecomment-230627194 ?

**Comment by Neraste** [comment]
Thanks @MorrisJobke, this put me on the tracks. I have mutualized my PHP Nginx configuration and it seems that is not compatible with Nextcloud 9.

I don't know what did the trick, but my mutualized configuration was communicating with `php-fpm` is like this:

```
fastcgi_pass unix:/var/run/php-fpm.sock;
```

Instead of the `upstream` way.

**Comment by saitoh183** [comment]
Im also getting this problem. I tried the #316 but i get the same problem

http://paste.ubuntu.com/19948173/ --nginx log
http://paste.ubuntu.com/19948326/ --php.ini
http://paste.ubuntu.com/19948430/ --www.conf
http://paste.ubuntu.com/19948541/ --nextcloud nginx conf
http://paste.ubuntu.com/19948679/ --nginx.conf
http://paste.ubuntu.com/19948857/ -- permissions /var/www/nextcloud
 http://paste.ubuntu.com/19948979/ -- permissions /var/www/nextcloud/config

**Comment by grubshka** [comment]
Just add : 

location = / {
  index index.php;
}

Before "location /"

Regards,

**Comment by bgemmill** [comment]
For anyone who ends up here trying to make this work with apache, as of 2017-03-28, nextcloud works out of the box on apache 2.2 and not 2.4.

**Comment by MorrisJobke** [comment]
> For anyone who ends up here trying to make this work with apache, as of 2017-03-28, nextcloud works out of the box on apache 2.2 and not 2.4.

It works fine with Apache 2.4. What is the problem?

**Comment by bgemmill** [comment]
@MorrisJobke I'm sure it works in some environments, for others, it's not obvious why things fail (for example):
https://help.nextcloud.com/t/synology-dsm6-file-not-found-the-specified-document-has-not-been-found-on-the-server/8278

My apologies for polluting this thread, it's the first google link to the problem.

**Comment by Weej1** [comment]
I too am facing the exact problem described here but for apache 2.4 on Ubuntu 16.04. @bgemmill is correct in saying this is the first google link that pops up. Will create a new ticket if the issue persists.

**Comment by pdreissen** [comment]
Same here Debian 8 Apache 2.4 exact same problem on several servers PHP5.6 PHP7.x PHP7.1.x all the same error.

**Comment by Neraste** [comment]
People, this ticket was about a problem between Nginx web server and Nextcloud 9, which roots were the way to call `php-fpm` from Nginx config files. The problem has been solved and the ticket closed. End of the story.

If you have a problem with Apache and expect help, then please create a new ticket for that. if this thread comes first in Google, just add a final post here redirecting to the corresponding ticket.
