### ISSUE TITLE
`imagecreatefrombmp()` fails with many error messages in log on broken `*.bmp`

### ISSUE THREAD

**Issue by alx-tuilmenau** [nextcloud/server#29513]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Some user has uploaded broken .bmp file
2. User views folder listing for creating preview

### Expected behaviour
If creation of preview fails. default file symbol should displayed. No messages in Log.

### Actual behaviour
10000s of log messages similar to:
```
{
  "reqId": "aEM9xqvhC6VRtW9Ny2qr",
  "level": 3,
  "time": "2021-11-01T15:10:29+00:00",
  "remoteAddr": "***",
  "user": "***",
  "app": "PHP",
  "method": "GET",
  "url": "/core/preview?fileId=46340540&c=9c7ada13963af4f886fdb7264337f5a8&x=250&y=250&forceIcon=0&a=0",
  "message": {
    "Exception": "Error",
    "Message": "Trying to access array offset on value of type bool at /data/nextcloud_19/lib/private/legacy/OC_Image.php#819",
    "Code": 0,
    "Trace": [
      {
        "file": "/data/nextcloud_19/lib/private/legacy/OC_Image.php",
        "line": 819,
        "function": "onError",
        "class": "OC\\Log\\ErrorHandler",
        "type": "::"
      },
      {
        "file": "/data/nextcloud_19/lib/private/legacy/OC_Image.php",
        "line": 617,
        "function": "imagecreatefrombmp",
        "class": "OC_Image",
        "type": "->"
      },
      {
        "file": "/data/nextcloud_19/lib/private/Preview/Image.php",
        "line": 52,
        "function": "loadFromFile",
        "class": "OC_Image",
        "type": "->"
      },
      {
        "file": "/data/nextcloud_19/lib/private/Preview/GeneratorHelper.php",
        "line": 63,
        "function": "getThumbnail",
        "class": "OC\\Preview\\Image",
        "type": "->"
      },
      {
        "file": "/data/nextcloud_19/lib/private/Preview/Generator.php",
        "line": 245,
        "function": "getThumbnail",
        "class": "OC\\Preview\\GeneratorHelper",
        "type": "->"
      },
      {
        "file": "/data/nextcloud_19/lib/private/Preview/Generator.php",
        "line": 140,
        "function": "getMaxPreview",
        "class": "OC\\Preview\\Generator",
        "type": "->"
      },
      {
        "file": "/data/nextcloud_19/lib/private/Preview/Generator.php",
        "line": 109,
        "function": "generatePreviews",
        "class": "OC\\Preview\\Generator",
        "type": "->"
      },
      {
        "file": "/data/nextcloud_19/lib/private/PreviewManager.php",
        "line": 190,
        "function": "getPreview",
        "class": "OC\\Preview\\Generator",
        "type": "->"
      },
      {
        "file": "/data/nextcloud_19/core/Controller/PreviewController.php",
        "line": 170,
        "function": "getPreview",
        "class": "OC\\PreviewManager",
        "type": "->"
      },
      {
        "file": "/data/nextcloud_19/core/Controller/PreviewController.php",
        "line": 143,
        "function": "fetchPreview",
        "class": "OC\\Core\\Controller\\PreviewController",
        "type": "->"
      },
      {
        "file": "/data/nextcloud_19/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 218,
        "function": "getPreviewByFileId",
        "class": "OC\\Core\\Controller\\PreviewController",
        "type": "->"
      },
      {
        "file": "/data/nextcloud_19/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 127,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/data/nextcloud_19/lib/private/AppFramework/App.php",
        "line": 157,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->"
      },
      {
        "file": "/data/nextcloud_19/lib/private/Route/Router.php",
        "line": 302,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::"
      },
      {
        "file": "/data/nextcloud_19/lib/base.php",
        "line": 993,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->"
      },
      {
        "file": "/data/nextcloud_19/index.php",
        "line": 37,
        "function": "handleRequest",
        "class": "OC",
        "type": "::"
      }
    ],
    "File": "/data/nextcloud_19/lib/private/Log/ErrorHandler.php",
    "Line": 92,
    "CustomMessage": "--"
  },
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36 Edg/95.0.1020.40",
  "version": "21.0.5.1",
  "id": "61800391cee44"
}
```

(I removed IP and username)

### Server configuration

**Operating system:** Debian 11.0

**Web server:** Apache2

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud version:** 21.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Are you using encryption:** no

### Client configuration
**Browser:** see error message

**Operating system:** unknown

### Logs
see above

### temporary/possible fix
Because all of the messages are in line 819 of OC_Image.php, i added a line before to get rid of the messages:
`if (!is_array($color)) return false`

(maybe you want to log a warning too.. but please no "error", so it can turned off without loosing critical errors)

**Comment by viulian** [comment]
I have an identical issue with Nextcloud 25.0.1.1 - except:

a) the BMP is not actually broken (you can see it in IrfanView) - they are around 400x240 / 4 bit BMP.
b) 5 small BMP files will create a 2Gb log file when previews are generating for them.
c) Previews are also corrupted, most of the previews are white.

Error in my case is:

`Trying to access array offset on value of type bool at /var/www/html/nextcloud/lib/private/legacy/OC_Image.php#938`

I see that code on line 938 is called in a loop for each pixel of the image! Which will create about 450000 log lines (approx 1.4Gb log file).

I am not sure why that code still calls that legacy method that is buggy / broken, when there is a similar method already part of PHP7: https://www.php.net/manual/en/function.imagecreatefrombmp.php

Thus, my fix was to comment out the call to the private method in OC_Image.php and call directly the built in one:

```
                        case IMAGETYPE_BMP:
#                               $this->resource = $this->imagecreatefrombmp($imagePath);
                                $this->resource = @imagecreatefrombmp($imagePath);
                                break;
```

No more errors and previews look good.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by alx-tuilmenau** [comment]
Hi, since the update to 24.0.9 the error no longer occurred.
