### ISSUE TITLE
Federated shared folder can't be used / displayed: "Storage is temporarily not available"

### ISSUE THREAD

**Issue by mhellmeier** [nextcloud/server#29515]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Click on a shared folder in my personal Nextcloud instance that is hosted on another Nextcloud instance
2. The loading-image is showing up for a minute or so
3. The error message "Storage is temporarily not available" appears

### Expected behaviour
The content of the shared folder should be displayed.

### Actual behaviour
An error message shows up on the upper right corner: "Storage is temporarily not available".
A while ago, the shared folder works. No changes are made with it. The external Nextcloud instance that hosts the folder works as expected. It is also listed in the settings menu under "trusted servers" with a green dot.

A similar problem is also described in #9125 (issue was closed due to missing information).

### Server configuration

**Operating system:**
Ubuntu 20.04.3 LTS

**Web server:**
(Latest version from Nextcloud Docker image)

**Database:**
MariaDB 10.5

**PHP version:**
(Latest version from Nextcloud Docker image)

**Nextcloud version:**
22.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated every time after a new stable release was published. The problem has existed for several versions now.

**Where did you install Nextcloud from:**
Docker image

**Signing status:**
<details>
<summary>Signing status</summary>
Integrity checker has been disabled. Integrity cannot be verified.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.8.0
  - admin_audit: 1.12.0
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contactsinteraction: 1.3.0
  - dav: 1.19.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_external: 1.13.0
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - richdocuments: 4.2.3
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - activity
  - bruteforcesettings
  - dashboard
  - encryption
  - external
  - files_markdown
  - logreader
  - qownnotesapi
  - richdocumentscode
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.***REMOVED SENSITIVE VALUE***.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.***REMOVED SENSITIVE VALUE***.de",
        "dbtype": "mysql",
        "version": "22.2.0.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "vKSSJ_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "tempdirectory": "\/var\/www\/html\/app\/tmp\/",
        "integrity.check.disabled": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 1,
        "theme": "",
        "mail_sendmailmode": "smtp",
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mysql.utf8mb4": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded-for-headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "overwriteprotocol": "https",
        "overwritehost": "cloud.***REMOVED SENSITIVE VALUE***.de",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "richdocuments"
        ],
        "default_phone_region": "DE"
    }
}
```
</details>

**Are you using external storage, if yes which one:**
No.

**Are you using encryption:**
No.

**Are you using an external user-backend, if yes which one:**
No.

### Client configuration
**Browser:**
Chrome

**Operating system:**
macOS / Windows / Linux

#### Web server error log
During the loading process after I click on the (broken) shared folder, no logs appear.
<details>
<summary>Web server error log</summary>
-
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
-
</details>

#### Browser log
**The following error appears when I click on the folder:**
<details>
<summary>Browser log</summary>

```
translate.js:1112 Uncaught (in promise) Error: getTranslators: detection is already running
    at Zotero.Translate.Web.<anonymous> (translate.js:1112)
    at Zotero.Translate.Web.getTranslators (promise.js:36)
    at Object.init (inject.js:108)
    at Object.historyChanged (inject.js:692)
    at messageListener (messaging_inject.js:122)
    at messaging_inject.js:132
```
</details>

**Comment by mhellmeier** [comment]
More information from the community can be found in the discussion of the legacy issue:
https://github.com/nextcloud/server/issues/9125#issuecomment-977319919

**Comment by grinapo** [comment]
Additional info (v22.2.3 + ldap): the error comes on a locally shared file, the file does exists:
```json
  "app": "webdav",                                                                                                                  
  "method": "GET",                                                                                                                  
  "url": "/remote.php/webdav/Incoming%20shared%20stuff/xx.ods",                                                              
  "message": "Storage is temporarily not available",                                                                                
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0",                                            
  "version": "22.2.3.0",                                                                                                            
  "exception": {                                                                                                                    
    "Exception": "Sabre\\DAV\\Exception\\ServiceUnavailable",     
    "Message": "Storage is temporarily not available",                                                                              
    "Code": 0,                                                                                                                      
    "Trace": [                                                                                                                      
      {                                                                                                                             
        "file": "/var/www/nc.tarr.hu/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",                                                    
        "line": 76,                                                                                                                 
        "function": "getNodeForPath",                             
        "class": "OCA\\DAV\\Connector\\Sabre\\ObjectTree",                                                                          
        "type": "->"                                                                                                                
      },                                                                                                                            
      {                                                                                                                             
        "file": "/var/www/nc.tarr.hu/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",                                            
        "line": 89,                                                                                                                 
        "function": "httpGet",                                                                                                      
        "class": "Sabre\\DAV\\CorePlugin",                                                                                          
        "type": "->"
      },
...
```

And displays internal error for the user. For about 20-30 seconds. Then it self-healed, and the file works again. Nothing seems to be logged about why it was unavailable and how did it heal.

**Comment by PVince81** [comment]
please update to at least Nextcloud 23.0.8 (it will be out in a week or two) as Nextcloud 22 is EOL already, see https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule#nextcloud-24

if the problem persists, please try the following:

1. `update oc_storages set available=1`, this will reset the timeout and force a recheck (it only rechecks after 10 minutes otherwise)
2. try accessing the shared folder immediately
3. check nextcloud.log for the PROPFIND on the share folder for errors

don't use 23.0.7 yet as .8 comes with a patch that will log more information to debug connection issues: https://github.com/nextcloud/server/pull/33103

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
