### ISSUE TITLE
Approval workflow / Workflow creator

### ISSUE THREAD

**Issue by pieter-groeneweg** [nextcloud/server#2952]
It would be very nice to have some sort of approval workflow on files. Withing a group there is one "manager" that can approve for sharing outside the group / public and will automatically do so if required.
Maybe a workflow creator like activiti in Alfresco (brrrr what a d!5a5ter) but way better.. 

I can see workflow and file access control but can't think of a way to achieve this.

ie.

user creates content and saves to user's folder tree.
- nothing can be shared outside users group by default.
user adds activity "ask for approval" 
- notification and share link to group manager is sent.
manager tags file with "approved"
- now file can be shared outside the group.

This in a nutshell. Very usefull for corporate use.

**Comment by Nightwelf** [comment]
i want it too

**Comment by Laykou** [comment]
👍

**Comment by F0rth** [comment]
js librairies already exist: https://github.com/bpmn-io .

**Comment by szaimen** [comment]
I think this will be covered with https://github.com/nextcloud/approval -> closing.
