### ISSUE TITLE
Align new mount defaults set thorugh web UI and occ command

### ISSUE THREAD

**Issue by Pytal** [nextcloud/server#29537]
When adding a new external storage mount through the web UI vs using the `occ files_external:create` command the mount options, for example the "Check for changes" option, are set to different defaults.

All options should be set to the same defaults regardless of whether the mount is created through web UI or occ command.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
