### ISSUE TITLE
cannot delete group with a slash in its name

### ISSUE THREAD

**Issue by hirschrobert** [nextcloud/server#2954]
### Steps to reproduce
1. create a group with a slash in its name
2. try to delete that group
3.

### Expected behaviour
group should be deleted

### Actual behaviour
group name vanishes but comes back after page refresh

### Server configuration
**Operating system**:
debian

**Web server:**
apache 2.4

**Database:**
mysql 5.5.53

**PHP version:**
5.6.29

**Nextcloud version:** (see Nextcloud admin page)
10.0.2

### Solutions?
Could have something to do with https://github.com/owncloud/core/pull/24072

**Comment by kroka** [comment]
Using Nextcloud 13 I cannot delete a user group containing a slash although this bug should already be fixed.

 * Nextcloud 13.0.1
 * PHP 7.0.28
 * PostgreSQL 9.4.15 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit

**Comment by brknkfr** [comment]
Problem still exists in Nextcloud 13.0.6, please reopen.

**Comment by danielkesselberg** [comment]
Management for a Group with / in name is broken for me. I cannot view users in there. Does this work for you?

**Comment by danielkesselberg** [comment]
https://github.com/nextcloud/server/blob/228d1cfbd731b5452ca0d35f833e39a488224add/apps/provisioning_api/appinfo/routes.php#L40

When i replace the line above with
`['root' => '/cloud', 'name' => 'Groups#getGroupUsersDetails', 'url' => '/groups/{groupId}/users/details', 'verb' => 'GET', 'requirements' => ['groupId' => '.+']],` than i can view groups with / inside
