### ISSUE TITLE
Exceptions on environment- and update-check because of CURLOPT_RESOLVE

### ISSUE THREAD

**Issue by neufeind** [nextcloud/server#29554]
In the certificate pinning option CURLOPT_RESOLVE is used at:
lib/private/Http/Client/DnsPinMiddleware.php

That only exists in newer curl-versions. According the the php-docs starting cURL 7.21.3.
I'm using a Nextcloud updated from 21.x to 22.2.0 just now when the problem started to appear.
curl-version on this machine (unfortunately) is curl-7.19.7-54.el6_10.x86_64 with no easy way to bring this to 7.21.3 or newer soon.

Can you add a check if the constant CURLOPT_RESOLVE is actually defined and only in that case use the pinning-magic there? Otherwise using that undefined constant leads to exceptions and thus checks failing.

Workaround: Comment out that option-setting with CURLOPT_RESOLVE *sigh*

**Comment by kesselb** [comment]
> Can you add a check if the constant CURLOPT_RESOLVE is actually defined and only in that case use the pinning-magic there? Otherwise using that undefined constant leads to exceptions and thus checks failing.

No. 

![image](https://user-images.githubusercontent.com/3902676/140306720-f08fb5f4-161b-4a75-8332-6cbcf4e20ffa.png)
