### ISSUE TITLE
New IBootstrap registration for resource and room back ends

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#29563]
``\OCP\Calendar\Resource\IManager::registerBackend`` and ``\OCP\Calendar\Room\IManager::registerBackend`` use an old style of service registration. You can't use them in ``\OCA\CalendarResourceManagement\AppInfo\Application::register`` of an app because you have to fetch the container.

This raises the next problem: the full service and its dependencies have to be built for every single request, despite resource being used in it or not. So this has a small but factual performance penalty on installations that have apps with resource back-ends.

I propose to move the registration to the registration context and fetch the registered backends from the registration context on demand. Then the registration itself becomes lightweight and we don't have to build services that won't be used for the majority of requests.

**Comment by miaulalala** [comment]
See 2factor_auth providers as an example.
