### ISSUE TITLE
Groups with slashes brakes calendar and contacts.

### ISSUE THREAD

**Issue by Sevlin** [nextcloud/server#2957]
### Steps to reproduce
1. Add group(s) with slash in the name. E.g. **foo/bar** and **foo/baz**;  
2. Add user(s) to newly created group(s);  
3. Open Contacts or Calendar.

### Expected behaviour
Show contacts and calendar.

### Actual behaviour
Stucks at loading groups list available for sharing, as far as I can see.  
No contacts/calendars are displayed.

Escape sequences or limitations are needed for group names.

Also affects CalDAV, CardDAV:
```
curl -u testuser -X PROPFIND https://cloud.mydomain.com/remote.php/dav/calendars/testuser/
Enter host password for user 'testuser':
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>Principal with name foo not found</s:message>
</d:error>
```

### Server configuration
**Operating system**:
Slackware64-14.2 GNU/Linux

**Web server:**
Nginx 1.10

**Database:**
PostgreSQL 9.6

**PHP version:**
5.6

**Nextcloud version:**
11.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**  
* Old installation: oC 5->9 => Nc 9->11 **(broke around oC 8)**
* Fresh installation **(broken)**

**Where did you install Nextcloud from:**
Official website.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - audioplayer: 1.4.0
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_markdown: 1.0.0
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.1.2
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.4
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
```
</details>

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by MorrisJobke** [comment]
cc @georgehrke @rullzer

**Comment by rullzer** [comment]
uhm yeah.... hehe... let me thing about this. Maybe we have to url encode or something....
