### ISSUE TITLE
can't acccess to files and mail

### ISSUE THREAD

**Issue by Paullux** [nextcloud/server#29581]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. go to files app
2. this message appears : "Ce répertoire est indisponible, merci de consulter les journaux ou de contacter votre administrateur"
3. `sudo -u sc-nextcloud cat data/nextcloud.log | grep error` return 
```
{"reqId":" ","level":3,"time":"2021-11-06T11:45:04+00:00","remoteAddr":"192.168.1.254","user":"myName","app":"index","method":"GET","url":"/webstation_error_page_custom_default_403","message":"The requested uri(/webstation_error_page_custom_default_403) cannot be processed by the script '/nextcloud/index.php')","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36","version":"22.0.0.11","exception":{"Exception":"Exception","Message":"The requested uri(/webstation_error_page_custom_default_403) cannot be processed by the script '/nextcloud/index.php')","Code":0,"Trace":[{"file":"/volume1/web_packages/nextcloud/lib/base.php","line":944,"function":"getRawPathInfo","class":"OC\\AppFramework\\Http\\Request","type":"->","args":[]},{"file":"/volume1/web_packages/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/volume1/web_packages/nextcloud/lib/private/AppFramework/Http/Request.php","Line":770,"CustomMessage":"--"}}
```

### Expected behaviour
Tell us what should happen
see my files

### Actual behaviour
Tell us what happens instead
error

### Server configuration

**Operating system:**
DSM7

**Web server:**
NAS Synology DS218

**Database:**
PL/pgSQL

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
22.0.0 from http://digital.box.free.fr/dsm7/

**Updated from an older Nextcloud/ownCloud or fresh install:**
the problem is appears after i tried to upgrade to 22.2.0 in nextcloud interface 

**Where did you install Nextcloud from:**
http://digital.box.free.fr/dsm7/

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
<?php
$CONFIG = array (
  'instanceid' => ' ',
  'passwordsalt' => ' ',
  'secret' => ' ',
  'trusted_domains' =>
  array (
    0 => '176.170.xxx.xxx',
    1 => ' .synology.me',
  ),
  'trusted_proxies' =>
  array (
    0 => '192.168.1.254',
  ),
  'forwarded_for_headers' =>
  array (
    0 => 'HTTP_X_FORWARDED_FOR',
  ),
  'datadirectory' => '/volume1/web_packages/nextcloud/data',
  'dbtype' => 'pgsql',
  'version' => '22.0.0.11',
  'overwrite.cli.url' => 'https:// .synology.me/nextcloud/',
  'dbname' => 'nextcloud',
  'dbhost' => '127.0.0.1:5433',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_',
  'dbpassword' => '',
  'installed' => true,
  'maintenance' => false,
  'updater.secret' => '',
);


```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder
 There are no commands defined in the "ldap" namespace.

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Google Chrome Linux

**Operating system:**
ArchLinux
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
