### ISSUE TITLE
Minor, confusing messaging after Instant trial expiration

### ISSUE THREAD

**Issue by obziva** [nextcloud/server#29587]
Hello,
- yesterday, signed to trial (Webo hosting), received mail for confirmation, clicked link for confirmation, playing with Nexcloud then received mail "Your Nextcloud by Webo.hosting account .... has been disabled because it was not verified in time. Please contact your provider for further assistance.". Cunfusing message because I did confirm.
- Today, trying again with the same email address, not possible to access. Expected. Trying to reset password. No mail is coming. Expected but page shows info that email has been sent to account for this email... Seems not true. 
- I can not sign up with the same email address because "Error: User already exists". It is expected I can't get in because 60minutes from yesterday is gone. But message is again confusing.

**Comment by acsfer** [comment]
Please contact Webo hosting directly about this issue.
