### ISSUE TITLE
Bookmarked openfile url to no more existing file downloads zipped root folder

### ISSUE THREAD

**Issue by jhomola79** [nextcloud/server#29586]
### Steps to reproduce
1. https://demo2.nextcloud.com/apps/files/?dir=/&openfile=123456789 where 123456789 stands for notexisting file id

### Expected behaviour
Probably error message similar to that for filed=123456789 kind of links could be ok

### Actual behaviour
download of zipped root(directory of dir param) directory.

**Comment by jhomola79** [comment]
This works for me in OCA.Files.FileList._nextPage() :
`.... else {
                        OC.Notification.show(t('files', 'File could not be found'), {type: 'error'});
                        /** 
                        var url = this.getDownloadUrl(filename, dir, true);
                        OCA.Files.Files.handleDownload(url);
                         */
                    } ...`
, but I'm not sure if it brakes something else.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
