### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by Schnappa** [nextcloud/server#2958]
### Steps to reproduce
1. update from 9.0.54 successful as described here: https://nextcloud.com/blog/get-up-to-date-with-the-new-nextcloud-updater/
2. login to web fronting of nextcloud
3. click on "update" produces error (see below)

### Expected behaviour
update to 10.0.2

### Actual behaviour
error message:

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet 
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TEMPORARY TABLE __temp__oc_activity AS SELECT activity_id, timestamp, priority, type, user, affecteduser, app, subject, subjectparams, message, messageparams, file, link, object_type, object_id FROM oc_activity': SQLSTATE[HY000]: General error: 11 database disk image is malformed

### Server configuration
**Operating system**: Raspberry Pi Linux version 4.4.19+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611) ) 

**Nextcloud version:**
10.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
9.0.54

**Where did you install Nextcloud from:**
internal updater

**Signing status:**
<details>
<summary>Signing status</summary>

**Comment by MorrisJobke** [comment]
> SQLSTATE[HY000]: General error: 11 database disk image is malformed

We can't do anything against database file corruption. Please try to get a working backup in place and retry the upgrade.

Sorry for this sad answer, but sadly we can't do anything here.
