### ISSUE TITLE
Disabled appstore in config.php still access the store

### ISSUE THREAD

**Issue by Gomez** [nextcloud/server#2959]
### Steps to reproduce
1. Add 'appstoreenabled' => false to config.php
2. Access https://cloudurl.com/settings/apps

### Expected behaviour

Only apps that exits on the filesystem should be installable. No other category than "Enabled" and "Not enabled" should be shown. (Like in Nextcloud 10)

### Actual behaviour

Many categories are shown like Files, Multimedia ... 
All Apps from the store are shown. 

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
Version 11.0.0 (git)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh

**Where did you install Nextcloud from:**
GIT

```

**Comment by Gomez** [comment]
Related https://github.com/nextcloud/server/issues/2701

**Comment by Gomez** [comment]
Thanks to @nickvergessen just a "return [];" in https://github.com/nextcloud/server/blob/master/lib/private/App/AppStore/Fetcher/Fetcher.php#L97 solves it. 

I will create a proper PR.

**Comment by MorrisJobke** [comment]
Fix is in #3287
