### ISSUE TITLE
Button regressions in 23

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#29591]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Upgrade to Nextcloud 23 (dev instance)
2. Use Calendar or Mail

### Expected behavior

Buttons render the same way as in Nextcloud 22

![Bildschirmfoto von 2021-11-08 11-42-26](https://user-images.githubusercontent.com/1374172/140728180-dc5018f5-b32d-4ca9-8b62-5359f5c56fcd.png)
![Bildschirmfoto von 2021-11-08 11-43-37](https://user-images.githubusercontent.com/1374172/140728320-15620054-90c1-4c18-a085-c7a6010cf9da.png)

^ latest and greatest 22 production instance

### Actual behavior

![Bildschirmfoto von 2021-11-08 11-43-01](https://user-images.githubusercontent.com/1374172/140728237-54f8d7c7-73db-4664-a715-c485bdea5662.png)
![Bildschirmfoto von 2021-11-08 11-44-47](https://user-images.githubusercontent.com/1374172/140728479-c9ec77eb-d0ee-4f11-a7e3-294960476f25.png)
^ today's server master

---

This is possibly caused by https://github.com/nextcloud/server/pull/25721

cc @GretaD @marcoambrosini

**Comment by GretaD** [comment]
I cannot reproduce this. Are you sure you were not on my "move new msg into a modal" branch? Because on that branch is broken because its an old one.

@marcoambrosini can you reproduce?

**Comment by ChristophWurst** [comment]
>  its an old one.

Right. Latest Mail master looks better. Did we fix this in nc/vue? Calendar is still broken.

**Comment by marcoambrosini** [comment]
summary of the problem: 
adding the :not(.button-vue) pseudo class makes some rules "more important" than they were before, therefore the rules hierarchy is messed up and this results in potentially many regressions across the apps that rely on this. 

On the other hand, afaik this is the only way we can avoid targeting the Vue components with server css. 
@skjnldsv what do we do about this?

**Comment by raimund-schluessler** [comment]
This also happens with server 22.2.3, so not only 23. I guess this is because https://github.com/nextcloud/server/pull/29113 never was reverted and 22.2.1 onwards now also ships the new button color variables.

**Comment by ChristophWurst** [comment]
Right, that solves the mystery of why 22 is suddenly affected as well :see_no_evil:

**Comment by raimund-schluessler** [comment]
@blizzz Shouldn't this rather belong to the Nextcloud 23.0.x milestones?

**Comment by blizzz** [comment]
> @blizzz Shouldn't this rather belong to the Nextcloud 23.0.x milestones?

the backport of the fixing PR would be
