### ISSUE TITLE
External storage configuration duplicates itself

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#29604]
### Steps

1. Setup an external storage of type "Local"
2. Do some testing then come back
3. Enable encoding mode
4. Do some testing then come back
5. Disable encoding mode
6. Repeat until unlucky :four_leaf_clover: 

### Expected result
Config stays only one.

### Actual result
Sometimes the configuration duplicates itself.
```
% occ files_external:list
+----------+-------------+---------+---------------------+--------------------------+---------+------------------+-------------------+
| Mount ID | Mount Point | Storage | Authentication Type | Configuration            | Options | Applicable Users | Applicable Groups |
+----------+-------------+---------+---------------------+--------------------------+---------+------------------+-------------------+
| 6        | /local4     | Local   | None                | datadir: "\/srv\/ocdata" |         | All              |                   |
| 7        | /local4     | Local   | None                | datadir: "\/srv\/ocdata" |         | All              |                   |
+----------+-------------+---------+---------------------+--------------------------+---------+------------------+-------------------+
```
Once I even had it up to three times, and the third one had encoding enabled.

### Version
Observed on NC 23 git master 81b60c14c985b0a46fd31733db2add9efd7bedba

### Notes
I suspect that maybe the frontend is not blocking saves, so maybe when changing options it might save the same thing multiple times and there is no collision detection...
Still very strange...

**Comment by PVince81** [comment]
might be related to the fact that I tend to click on the tick mark at the end of the row because I never know if it's saved or not

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
