### ISSUE TITLE
Nextcloud desktop log in fails on ubuntu 20.04.3

### ISSUE THREAD

**Issue by nusch-22** [nextcloud/server#29602]
Hi!
Today I installed nextcloud desktop via 'sudo apt install nextcloud-desktop'. I logged in to the server 'https://surfdrive.surf.nl/files' and everything worked fine. I could sync the files. Then I rebooted my laptop and when I opened nextcloud I got the following:

![nextcloud-error](https://user-images.githubusercontent.com/67695276/140896394-cefa54b6-f3d5-441c-9cbe-61c301895a9d.png)

Nothing happens when I click on 'Re-open Browser' or 'Copy link'. Can someone please help me?

Thanks a lot!
Nusch

**Comment by szaimen** [comment]
Hi, please contact surfdrive.surf.nl on this
