### ISSUE TITLE
Improve overall Nextcloud Search experience

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#29614]
Hi,

Right now, we have a few issues with the search, some of the main ones are:
1. it is slow
2. the dialog is too small for all but the most trivial searches
3. it shows a lot of irrelevant results

To deal with this, we now have a work-around in the app store and Files app, as well as in Deck.
Files and the app store have implemented a filter in the UI, showing search results there while the universal search pop-up is still doing its thing:

<img width="1920" alt="Screenshot_20211109_184507" src="https://user-images.githubusercontent.com/551757/140976768-601eae07-c77f-4cb1-aa62-099b3685f016.png">

Deck just implemented a second, direct search:
<img width="1920" alt="Screenshot_20211109_184559" src="https://user-images.githubusercontent.com/551757/140976930-f645d736-ba88-40fe-86df-bd5036e75ff3.png">

Discussing it today with Andy, perhaps there is a good way we can solve all three problems in one.

We make 2 changes:
* The search is first only in context. That is, if in Talk, it shows only Talk results, in Mail shows Mail results, in Deck only Deck results and so on. This solves problems 1 (performance) and 3 (showing irrelevant results). Apps can still do a quick filter in the main dialog, but Deck, Files etc should have no more need to show the 'results from other boards' (Deck) or 'results from other folders' (Files).
* Below the results is a button: [search everywhere] This opens up a modal with results from all apps. Being a bigger modal and perhaps filters on top and some advanced search options, it should solve problem 2 quite well.

Best part is that this is probably not too crazy much work.

What do you think, @nextcloud/designers ?

**Comment by juliushaertl** [comment]
In addition we should consider always showing the current search input then if some local filtering applies, otherwise users might be confused by a filtered view when there is no clear indication where to reset or change that filter.

**Comment by stefan-niedermann** [comment]
cc @korelstar for the Notes app

**Comment by acsfer** [comment]
This is directly tied to https://github.com/nextcloud/server/issues/23835

**Comment by Spartachetto** [comment]
The second change proposed deals with the proposal in #27078

**Comment by bes1002t** [comment]
Very good proposal. :)

Only question is, how sophisticated and complex could be the modal filters? But probably this is another issue to address.

**Comment by putt1ck** [comment]
Q. isn't the slow performance directly related to the number of items (in the file search at least)? If so while "de-universalising" the output is great for non-files search, how does it improve performance for file search (which I'd guess was the most common requirement for search outside of Deck-heavy installs)

**Comment by pmarini-nc** [comment]
Copy/pasting my thoughts on #29989, inappropriately marked as duplicate:

> **Is your feature request related to a problem?**
> 
> Sometimes the user knows the search scope in terms of where he/she wants to search (e.g the App) and when (e.g the time period, for example a file created in the last week). Currently the App (or Apps) can be selected once the search has been already launched and no possibilities are given to the user to select the period.
> 
> The ability to pre-filter the search before launching it, would lead to a generally shorter search time and less load on the server, ultimately bringing an improved user experience.
> 
> This pre-filtering capabilty is already present in other mainstream collaboration platforms and can be also enriched with other items atributes, for example the owner.
> 
> **Describe the solution you'd like**
> 
>    - Make the three-dots menu available before launching the search
>    -  Add to the three-dots menu the option to pre-filter based on last modification date and creation date.

**Comment by jospoortvliet** [comment]
> Q. isn't the slow performance directly related to the number of items (in the file search at least)? If so while "de-universalising" the output is great for non-files search, how does it improve performance for file search (which I'd guess was the most common requirement for search outside of Deck-heavy installs)

Yes, but this isn't a regression - search for all files became no slower since the introduction of universal search. If anything, it got faster. But much of the time you want to filter in the current folder, and suddenly you always had to wait for the full search. which is fixed with 23 already. With my proposal we lower the server load from search and focus on the common case of app-specific search. That does indeed not fix slow all-files search.

**Comment by acsfer** [comment]
Adding this https://github.com/nextcloud/server/pull/30311 here as it also improves it in some way.

**Comment by brtptrs** [comment]
@jospoortvliet For us the universal search meant a huge regression. In the last couple of versions we always hat to deactivate the file search on code level.
If a user with many files (many GBs ) do a search it causes huge db loads. A single users doing many searches in a short time could (and has on our system) brought down the whole system. At the moment on NC22 the file search is still deactivated for the whole system.
We have a support request on this open for a long time.

**Comment by Aeredren** [comment]
@bes1002t 
> Only question is, how sophisticated and complex could be the modal filters? But probably this is another issue to address.

I'll be working on search modals for the next month and a half, I'll have more info then on how difficult it is : https://help.nextcloud.com/t/looking-forward-to-develop-sorts-files-visualisation-improvement-and-filters/128314

**Comment by jospoortvliet** [comment]
Hi @Aeredren any update perhaps?

**Comment by pmarini-nc** [comment]
There's a very good application that can be taken inspiration from.

Sorts, developed by Framasoft, the code repository is [here](https://framagit.org/framasoft/nextcloud/sorts) and a short demo is [here](https://aperi.tube/w/ipjoNXNhmE1udKo5ZimKmD?start=5m24s)

**Comment by XueSheng-GIT** [comment]
Just want to reference https://github.com/nextcloud/server/issues/35776#issuecomment-1407427087 which shows an alternative approach by @Mer0me.
Being able to put a lot of information/files into a cloud is great. But not being able to find this info afterwards (in a quick way) is really annoying. Searching for files on my productive server (NC25) takes more than 30 seconds as detailed here https://github.com/nextcloud/server/issues/35776.

**Comment by gennaios** [comment]
Concerning point 2, i think it should be full screen similar to desktop search in file managers or even most web sites. 

An example of ownCloud OCIS. It has a link to show all results and its search is fast such that it will show all results. Such is possible only if one moves away from LIKE searches which I think needs to happen anyway. Websites typically do not use such for search and i think it's time for NC also change. 

https://ocis.owncloud.com/

![image](https://github.com/nextcloud/server/assets/12172/766bc0f6-e5c5-4240-a418-47f7f5004cb5)
![image](https://github.com/nextcloud/server/assets/12172/13ac3ac9-c1d0-4dd5-9f46-821c8d9f5357)

**Comment by gennaios** [comment]
An example of improved search for MySQL https://www.youtube.com/watch?v=7tffuHLCXn8&pp=ygUWTXlzcWwgZnVsbCB0ZXh0IHNlYXJjaA%3D%3D

**Comment by gennaios** [comment]
> **2. Move the global search to a big dialog or full screen**

I think full screen is preferred. As one could potentially have thousands or tens of thousands or more files, and search result count could be any number, full screen would be better suited. The filter buttons in your screen shot could be moved to some sidebar similar to categories in Settings. 

Concerning the previous comment about search performance, such I think goes together and was part of the original comment for this issue. Think of any search of any large web site, database, mobile app (e.g. contacts, calendar, music, etc.), none uses LIKE searches. Isn't it about time Nextcloud also abandons such?

**Comment by marcoambrosini** [comment]
closing in favor of #39162
