### ISSUE TITLE
Error: Trying to access array offset on value of type null at /apps/dav/lib/CalDAV/BirthdayService.php#306

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#29617]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. No Sure
2.
3.

### Server configuration

**Operating system:**
Ubuntu 20.4
**Web server:**
Apache 2
**Database:**
10.5.12
**PHP version:**
8.0.12
**Nextcloud version:** (see Nextcloud admin page)
22.2.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install
**Where did you install Nextcloud from:**
Nextcloud website 

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"IoPpj4uCj4eCF585ahy3","level":3,"time":"2021-11-09T20:25:01+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Trying to access array offset on value of type null at /var/www/nextcloud/apps/dav/lib/CalDAV/BirthdayService.php#306","userAgent":"--","version":"22.2.0.2","exception":{"Exception":"Error","Message":"Trying to access array offset on value of type null at /var/www/nextcloud/apps/dav/lib/CalDAV/BirthdayService.php#306","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/dav/lib/CalDAV/BirthdayService.php","line":306,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/dav/lib/BackgroundJob/GenerateBirthdayCalendarBackgroundJob.php","line":69,"function":"resetForUser","class":"OCA\\DAV\\CalDAV\\BirthdayService","type":"->"},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/Job.php","line":51,"function":"run","class":"OCA\\DAV\\BackgroundJob\\GenerateBirthdayCalendarBackgroundJob","type":"->"},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/QueuedJob.php","line":45,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":127,"function":"execute","class":"OC\\BackgroundJob\\QueuedJob","type":"->"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"618aebfd2848f"}
```
</details>

**Comment by aleadco** [comment]
The error is obtained after the scheduled task in crontab runs every 10 min. I have not been able to identify the cause.

`{"reqId":"V3E8mX5q3kfXj6ZCUMyr","level":3,"time":"2021-11-10T00:20:01-05:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job (class: OCA\\DAV\\BackgroundJob\\EventReminderJob, arguments: )","userAgent":"--","version":"22.2.0.2","exception":{"Exception":"TypeError","Message":"Argument 1 passed to OCA\\DAV\\CalDAV\\Reminder\\ReminderService::parseCalendarData() must be of the type string, null given, called in /var/www/nextcloud/apps/dav/lib/CalDAV/Reminder/ReminderService.php on line 122","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/dav/lib/CalDAV/Reminder/ReminderService.php","line":122,"function":"parseCalendarData","class":"OCA\\DAV\\CalDAV\\Reminder\\ReminderService","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/BackgroundJob/EventReminderJob.php","line":66,"function":"processReminders","class":"OCA\\DAV\\CalDAV\\Reminder\\ReminderService","type":"->"},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/Job.php","line":51,"function":"run","class":"OCA\\DAV\\BackgroundJob\\EventReminderJob","type":"->"},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php","line":58,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":127,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/nextcloud/apps/dav/lib/CalDAV/Reminder/ReminderService.php","Line":666,"CustomMessage":"Error while running background job (class: OCA\\DAV\\BackgroundJob\\EventReminderJob, arguments: )"},"id":"618b573a387f6"}`

**Comment by proletarius101** [comment]
This can also happen to other calendars, when downloading that calendar

**Comment by andyxheli** [comment]
@tcitworld Any updates on this ? still present NC 23

**Comment by Infixz** [comment]
{
    "reqId": "LTSSRmKwOqT0FpFFQksj",
    "level": 3,
    "time": "2022-04-28T12:43:16+00:00",
    "remoteAddr": "",
    "user": "--",
    "app": "PHP",
    "method": "",
    "url": "--",
    "message": "Trying to access array offset on value of type null at /var/www/html/apps/dav/lib/CalDAV/BirthdayService.php#307",
    "userAgent": "--",
    "version": "23.0.3.2",
    "exception": {
        "Exception": "Error",
        "Message": "Trying to access array offset on value of type null at /var/www/html/apps/dav/lib/CalDAV/BirthdayService.php#306",
        "Code": 0,
        "Trace": [
            {
                "file": "/var/www/html/apps/dav/lib/CalDAV/BirthdayService.php",
                "line": 306,
                "function": "onError",
                "class": "OC\\Log\\ErrorHandler",
                "type": "::",
                "args": [
                    2,
                    "Trying to access array offset on value of type null",
                    "/var/www/html/apps/dav/lib/CalDAV/BirthdayService.php",
                    306
                ]
            },
            {
                "file": "/var/www/html/apps/dav/lib/BackgroundJob/GenerateBirthdayCalendarBackgroundJob.php",
                "line": 69,
                "function": "resetForUser",
                "class": "OCA\\DAV\\CalDAV\\BirthdayService",
                "type": "->",
                "args": [
                    "yunjiaitadmin"
                ]
            },
            {
                "file": "/var/www/html/lib/private/BackgroundJob/Job.php",
                "line": 51,
                "function": "run",
                "class": "OCA\\DAV\\BackgroundJob\\GenerateBirthdayCalendarBackgroundJob",
                "type": "->",
                "args": [
                    {
                        "userId": "yunjiaitadmin",
                        "purgeBeforeGenerating": true
                    }
                ]
            },
            {
                "file": "/var/www/html/lib/private/BackgroundJob/QueuedJob.php",
                "line": 45,
                "function": "execute",
                "class": "OC\\BackgroundJob\\Job",
                "type": "->",
                "args": [
                    {
                        "__class__": "OC\\BackgroundJob\\JobList"
                    },
                    {
                        "__class__": "OC\\Log"
                    }
                ]
            },
            {
                "file": "/var/www/html/cron.php",
                "line": 150,
                "function": "execute",
                "class": "OC\\BackgroundJob\\QueuedJob",
                "type": "->",
                "args": [
                    {
                        "__class__": "OC\\BackgroundJob\\JobList"
                    },
                    {
                        "__class__": "OC\\Log"
                    }
                ]
            }
        ],
        "File": "/var/www/html/lib/private/Log/ErrorHandler.php",
        "Line": 92,
        "CustomMessage": "--"
    }
}
same here

**Comment by miyata-i** [comment]
@tcitworld Any updates on this ? still present NC 24.  
This error occurred on my server as well.

**Comment by tcitworld** [comment]
@miyata-i Feel free to try #33341
