### ISSUE TITLE
disabling of users after brute force mechanism kicked in should be optional

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#29613]
I experienced that a user was disabled automatically after having changed the password and a client tried to login in with the old one a couple of times. I assume the brute force mechanism kicked in and disabled the user. Though I didn't find any hint that this is the case.

Other devices cannot login in then - even with the new password - , which is pretty confusing for the user.
so if that is true, it would be helpful to make that mechanism optional.

**Comment by joshtrichards** [comment]
This isn't how the brute force protection works. It only slows down login attempts - and only up to a maximum of 25 seconds. It never disables accounts. Perhaps you were running some other app or mechanism that disables accounts?

In any case, it can be disabled:
