### ISSUE TITLE
LDAP User names not shown in Quick Notes sharing feature.

### ISSUE THREAD

**Issue by efetzer** [nextcloud/server#29637]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.  Create a quick note
2. Click the Share icon
3. List of users shows their unique id and not username

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system:** Ubuntu 20.04

**Web server:** Apache2

**Database:** MYSQL

**PHP version:** 7.4

**Nextcloud version:** (see Nextcloud admin page) 22.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:**  Updated sequentially from 18

**Where did you install Nextcloud from:** Online Update

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - apporder: 0.13.0
  - bruteforcesettings: 2.2.0
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.6
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - deck: 1.5.3
  - drawio: 1.0.1
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_pdfviewer: 2.3.0
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - forms: 2.3.0
  - gpxpod: 4.2.8
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - mail: 1.10.5
  - nextcloud_announcements: 1.11.0
  - notes: 4.1.1
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - onlyoffice: 7.2.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - quicknotes: 0.7.2
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_external: 2.1.0
  - user_ldap: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - audioplayer
  - calendar
  - encryption
  - external
  - files_antivirus
  - files_external
  - gpxmotion
  - groupfolders
  - pdfdraw
  - spreed
  - workflow_ocr
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.fetzerwood.com"
        ],
        "onlyoffice": {
            "verify_peer_off": true
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/nextcloud.xxxxxx.com",
        "dbtype": "mysql",
        "version": "22.2.0.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "user_backends": [
            {
                "class": "OC_User_SMB",
                "arguments": [
                    "localhost"
                ]
            }
        ],
        "theme": "",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": 0,
        "debug": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.15.0",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "logging"
        },
        "apporder": {
            "enabled": "yes",
            "installed_version": "0.13.0",
            "order": "[\"\/index.php\/apps\/files\/\",\"\/index.php\/apps\/photos\/\",\"\/index.php\/apps\/tasks\/\",\"https:\/\/nextcloud.fetzerwood.com\/index.php\/apps\/spreed\/\",\"\/index.php\/apps\/mail\/\",\"\/index.php\/apps\/contacts\/\",\"\/index.php\/apps\/calendar\/\",\"\/index.php\/apps\/activity\/\",\"\/index.php\/apps\/audioplayer\/\",\"\/index.php\/apps\/quicknotes\/\",\"\/index.php\/apps\/gpxpod\/\",\"\/index.php\/apps\/gpxmotion\/\",\"\/index.php\/apps\/notes\/\",\"\/index.php\/apps\/deck\/\",\"\/index.php\/apps\/forms\/\"]",
            "types": ""
        },
        "audioplayer": {
            "enabled": "no",
            "installed_version": "2.13.1",
            "types": "filesystem"
        },
        "auto_mail_accounts": {
            "enabled": "no",
            "installed_version": "0.1.0",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "7466"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "2.2.0",
            "types": ""
        },
        "calendar": {
            "enabled": "no",
            "installed_version": "2.3.4",
            "types": ""
        },
        "circles": {
            "enabled": "yes",
            "installed_version": "22.1.1",
            "loopback_tmp_scheme": "http",
            "types": "filesystem,dav"
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "4.0.6",
            "types": "dav"
        },
        "contactsinteraction": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "dav"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "enterpriseLogoChecked": "yes",
            "installedat": "1533570580.7566",
            "lastcron": "1632169015",
            "lastupdateResult": "[]",
            "lastupdatedat": "1636520147",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "scss.variables": "7b268e68f0de4300e0da7ad2b86b660a",
            "shareapi_default_expire_date": "yes",
            "shareapi_enforce_expire_date": "no",
            "shareapi_expire_after_n_days": "14",
            "theming.variables": "ead80cd038a1c31aa24e43c142280bc6",
            "updater.secret.created": "1636519139",
            "vendor": "nextcloud"
        },
        "dashboard": {
            "enabled": "yes",
            "installed_version": "7.2.0",
            "types": ""
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "installed_version": "1.19.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "types": "filesystem"
        },
        "deck": {
            "enabled": "yes",
            "installed_version": "1.5.3",
            "types": "dav"
        },
        "drawio": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "filesystem"
        },
        "external": {
            "enabled": "no",
            "installed_version": "3.6.0",
            "max_site": "1",
            "sites": "***REMOVED SENSITIVE VALUE***",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.17.0",
            "types": "filesystem"
        },
        "files_antivirus": {
            "av_path": "\/usr\/bin\/clamscan",
            "enabled": "no",
            "installed_version": "3.2.2",
            "types": "filesystem,dav"
        },
        "files_downloadactivity": {
            "enabled": "no",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_external": {
            "allow_user_mounting": "yes",
            "enabled": "no",
            "installed_version": "1.5.0",
            "types": "filesystem",
            "user_certificate_scan": "not-run-yet",
            "user_mounting_backends": "files_external_gdrive"
        },
        "files_external_gdrive": {
            "enabled": "no",
            "installed_version": "0.4.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "2.3.0",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "no",
            "installed_version": "2.8.0",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.11.0",
            "types": "logging"
        },
        "forms": {
            "enabled": "yes",
            "installed_version": "2.3.0",
            "types": ""
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "18.4.0",
            "types": ""
        },
        "gpxmotion": {
            "enabled": "no",
            "installed_version": "0.0.11",
            "types": ""
        },
        "gpxpod": {
            "enabled": "yes",
            "installed_version": "4.2.8",
            "reset304": "1",
            "resetPics404": "1",
            "types": ""
        },
        "groupfolders": {
            "enabled": "no",
            "installed_version": "10.0.0",
            "types": "filesystem,dav"
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.7.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "yes",
            "installed_version": "1.10.5",
            "types": ""
        },
        "mindmaps": {
            "enabled": "no",
            "installed_version": "0.1.0",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "4.1.1",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.10.1",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "authentication"
        },
        "ocr": {
            "enabled": "no",
            "installed_version": "3.3.6",
            "languages": "eng",
            "redisDb": "0",
            "redisHost": "127.0.0.1",
            "redisPassword": "OCR",
            "redisPort": "6379",
            "types": ""
        },
        "onlyoffice": {
            "DocumentServerInternalUrl": "",
            "DocumentServerUrl": "https:\/\/onlyoffice.xxxxxx.com\/",
            "StorageUrl": "",
            "defFormats": "{\"csv\":\"true\",\"doc\":\"true\",\"docm\":\"false\",\"docx\":\"true\",\"dotx\":\"false\",\"epub\":\"false\",\"html\":\"false\",\"odp\":\"false\",\"ods\":\"false\",\"odt\":\"false\",\"pdf\":\"false\",\"potm\":\"false\",\"potx\":\"false\",\"ppsm\":\"false\",\"ppsx\":\"true\",\"ppt\":\"false\",\"pptm\":\"false\",\"pptx\":\"true\",\"rtf\":\"false\",\"txt\":\"false\",\"xls\":\"true\",\"xlsm\":\"false\",\"xlsx\":\"true\",\"xltm\":\"false\",\"xltx\":\"false\"}",
            "demo": "{\"available\":true,\"enabled\":false,\"start\":{\"date\":\"2021-09-17 17:03:35.540724\",\"timezone_type\":3,\"timezone\":\"UTC\"}}",
            "editFormats": "{\"csv\":\"true\",\"odp\":\"false\",\"ods\":\"false\",\"odt\":\"false\",\"rtf\":\"false\",\"txt\":\"true\"}",
            "enabled": "yes",
            "installed_version": "7.2.0",
            "jwt_secret": "",
            "sameTab": "false",
            "settings_error": "",
            "skey": "1540570501248",
            "types": "prevent_group_restriction",
            "verify_peer_off": "true"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "authentication"
        },
        "pdfdraw": {
            "enabled": "no",
            "installed_version": "0.1.2",
            "types": ""
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "prevent_group_restriction"
        },
        "quicknotes": {
            "enabled": "yes",
            "installed_version": "0.7.2",
            "types": ""
        },
        "radio": {
            "enabled": "no",
            "installed_version": "0.6.6",
            "types": ""
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "richdocuments": {
            "enabled": "no",
            "installed_version": "3.8.6",
            "types": "filesystem,dav,prevent_group_restriction",
            "wopi_url": "https:\/\/office.xxxxxx.com"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "no",
            "has_reference_id": "yes",
            "installed_version": "12.1.2",
            "project_access_invalidated": "1",
            "signaling_ticket_secret": "***REMOVED SENSITIVE VALUE***",
            "stun_servers": "***REMOVED SENSITIVE VALUE***",
            "types": "dav,prevent_group_restriction"
        },
        "support": {
            "SwitchUpdaterServerHasRun": "yes",
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.14.2",
            "types": ""
        },
        "text": {
            "enabled": "yes",
            "installed_version": "3.3.0",
            "types": "dav"
        },
        "theming": {
            "backgroundMime": "image\/jpeg",
            "cachebuster": "21",
            "color": "#BD2915",
            "enabled": "yes",
            "installed_version": "1.13.0",
            "logoMime": "image\/jpeg",
            "name": "xxxxxx Nextcloud",
            "types": "logging",
            "url": "***REMOVED SENSITIVE VALUE***"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": ""
        },
        "updatenotification": {
            "audioplayer": "2.9.0",
            "bruteforcesettings": "2.1.0",
            "calendar": "2.0.5",
            "contacts": "2.1.7",
            "core": "19.0.13.1",
            "deck": "1.2.7",
            "drawio": "0.9.1",
            "enabled": "yes",
            "external": "3.0.4",
            "files_antivirus": "1.3.2",
            "files_rightclick": "0.15.1",
            "gpxmotion": "0.0.11",
            "gpxpod": "4.2.2",
            "groupfolders": "2.0.3",
            "installed_version": "1.12.0",
            "mail": "1.4.3",
            "notes": "2.5.0",
            "onlyoffice": "6.3.0",
            "radio": "0.6.4",
            "spreed": "9.0.9",
            "tasks": "0.9.7",
            "types": "",
            "update_check_errors": "0",
            "user_external": "0.10.0",
            "zimbradrive": "0.8.20"
        },
        "user_external": {
            "enabled": "yes",
            "installed_version": "2.1.0",
            "types": "prelogin,authentication"
        },
        "user_ldap": {
            "cleanUpJobOffset": "100",
            "enabled": "yes",
            "installed_version": "1.12.0",
            "s01_lastChange": "1636559139",
            "s01has_memberof_filter_support": "0",
            "s01home_folder_naming_rule": "",
            "s01last_jpegPhoto_lookup": "0",
            "s01ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_attributes_for_group_search": "",
            "s01ldap_attributes_for_user_search": "",
            "s01ldap_backup_host": "",
            "s01ldap_backup_port": "",
            "s01ldap_base": "OU=CiscoVPN,DC=xxxxxx,DC=com",
            "s01ldap_base_groups": "OU=CiscoVPN,DC=xxxxxx,DC=com",
            "s01ldap_base_users": "OU=CiscoVPN,DC=xxxxxx,DC=com",
            "s01ldap_cache_ttl": "600",
            "s01ldap_configuration_active": "1",
            "s01ldap_default_ppolicy_dn": "",
            "s01ldap_display_name": "displayname",
            "s01ldap_dn": "CN=xxxxxx,OU=CiscoVPN,dc=xxxxxxx,dc=com",
            "s01ldap_dynamic_group_member_url": "",
            "s01ldap_email_attr": "mail",
            "s01ldap_experienced_admin": "0",
            "s01ldap_expert_username_attr": "",
            "s01ldap_expert_uuid_group_attr": "",
            "s01ldap_expert_uuid_user_attr": "",
            "s01ldap_gid_number": "gidNumber",
            "s01ldap_group_display_name": "cn",
            "s01ldap_group_filter": "",
            "s01ldap_group_filter_mode": "0",
            "s01ldap_group_member_assoc_attribute": "uniqueMember",
            "s01ldap_groupfilter_groups": "",
            "s01ldap_groupfilter_objectclass": "",
            "s01ldap_host": "192.168.2.24",
            "s01ldap_login_filter": "(&(|(objectclass=person))(|(samaccountname=%uid)(|(userPrincipalName=%uid))))",
            "s01ldap_login_filter_mode": "0",
            "s01ldap_loginfilter_attributes": "userPrincipalName",
            "s01ldap_loginfilter_email": "0",
            "s01ldap_loginfilter_username": "1",
            "s01ldap_nested_groups": "0",
            "s01ldap_override_main_server": "",
            "s01ldap_paging_size": "500",
            "s01ldap_port": "389",
            "s01ldap_quota_attr": "",
            "s01ldap_quota_def": "",
            "s01ldap_tls": "0",
            "s01ldap_turn_off_cert_check": "0",
            "s01ldap_turn_on_pwd_change": "0",
            "s01ldap_user_avatar_rule": "default",
            "s01ldap_user_display_name_2": "",
            "s01ldap_user_filter_mode": "0",
            "s01ldap_userfilter_groups": "",
            "s01ldap_userfilter_objectclass": "person",
            "s01ldap_userlist_filter": "(|(objectclass=person))",
            "s01use_memberof_to_detect_membership": "1",
            "types": "authentication"
        },
        "user_saml": {
            "enabled": "no",
            "general-allow_multiple_user_back_ends": "1",
            "general-idp0_display_name": "SSO",
            "general-uid_mapping": "UID",
            "installed_version": "1.7.0",
            "saml-attribute-mapping-email_mapping": "",
            "type": "environment-variable",
            "types": "authentication"
        },
        "user_status": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "weather_status": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "workflow_ocr": {
            "enabled": "no",
            "installed_version": "1.22.2",
            "types": "filesystem"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.4.0",
            "types": "filesystem"
        },
        "zimbradrive": {
            "allow_zimbra_users_login": "true",
            "enabled": "no",
            "installed_version": "0.8.19",
            "preauth_key": "xxxxxxx",
            "types": "authentication,prelogin",
            "zimbra_port": "443",
            "zimbra_url": "mail.xxxxxxxxx.com"
        }
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

+-------------------------------+-------------------------------------------------------------------------------+
| Configuration                 | s01                                                                           |
+-------------------------------+-------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                             |
| homeFolderNamingRule          |                                                                               |
| lastJpegPhotoLookup           | 0                                                                             |
| ldapAgentName                 | CN=xxxxxx,OU=CiscoVPN,dc=xxxxxx,dc=com                               |
| ldapAgentPassword             | ***                                                                           |
| ldapAttributesForGroupSearch  |                                                                               |
| ldapAttributesForUserSearch   |                                                                               |
| ldapBackupHost                |                                                                               |
| ldapBackupPort                |                                                                               |
| ldapBase                      | OU=CiscoVPN,DC=xxxxxx,DC=com                                              |
| ldapBaseGroups                | OU=CiscoVPN,DC=xxxxxx,DC=com                                              |
| ldapBaseUsers                 | OU=CiscoVPN,DC=xxxxxx,DC=com                                              |
| ldapCacheTTL                  | 600                                                                           |
| ldapConfigurationActive       | 1                                                                             |
| ldapDefaultPPolicyDN          |                                                                               |
| ldapDynamicGroupMemberURL     |                                                                               |
| ldapEmailAttribute            | mail                                                                          |
| ldapExperiencedAdmin          | 0                                                                             |
| ldapExpertUUIDGroupAttr       |                                                                               |
| ldapExpertUUIDUserAttr        |                                                                               |
| ldapExpertUsernameAttr        |                                                                               |
| ldapExtStorageHomeAttribute   |                                                                               |
| ldapGidNumber                 | gidNumber                                                                     |
| ldapGroupDisplayName          | cn                                                                            |
| ldapGroupFilter               |                                                                               |
| ldapGroupFilterGroups         |                                                                               |
| ldapGroupFilterMode           | 0                                                                             |
| ldapGroupFilterObjectclass    |                                                                               |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                  |
| ldapHost                      | 192.168.2.24                                                                  |
| ldapIgnoreNamingRules         |                                                                               |
| ldapLoginFilter               | (&(|(objectclass=person))(|(samaccountname=%uid)(|(userPrincipalName=%uid)))) |
| ldapLoginFilterAttributes     | userPrincipalName                                                             |
| ldapLoginFilterEmail          | 0                                                                             |
| ldapLoginFilterMode           | 0                                                                             |
| ldapLoginFilterUsername       | 1                                                                             |
| ldapMatchingRuleInChainState  | unknown                                                                       |
| ldapNestedGroups              | 0                                                                             |
| ldapOverrideMainServer        |                                                                               |
| ldapPagingSize                | 500                                                                           |
| ldapPort                      | 389                                                                           |
| ldapQuotaAttribute            |                                                                               |
| ldapQuotaDefault              |                                                                               |
| ldapTLS                       | 0                                                                             |
| ldapUserAvatarRule            | default                                                                       |
| ldapUserDisplayName           | displayname                                                                   |
| ldapUserDisplayName2          |                                                                               |
| ldapUserFilter                | (|(objectclass=person))                                                       |
| ldapUserFilterGroups          |                                                                               |
| ldapUserFilterMode            | 0                                                                             |
| ldapUserFilterObjectclass     | person                                                                        |
| ldapUuidGroupAttribute        | auto                                                                          |
| ldapUuidUserAttribute         | auto                                                                          |
| turnOffCertCheck              | 0                                                                             |
| turnOnPasswordChange          | 0                                                                             |
| useMemberOfToDetectMembership | 1                                                                             |
+-------------------------------+-------------------------------------------------------------------------------+

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
"user_ldap","cleanUpJobOffset","100"
"user_ldap","enabled","yes"
"user_ldap","installed_version","1.12.0"
"user_ldap","s01_lastChange","1636559139"
"user_ldap","s01has_memberof_filter_support","0"
"user_ldap","s01home_folder_naming_rule",
"user_ldap","s01last_jpegPhoto_lookup","0"
"user_ldap","s01ldap_agent_password","UG9rZW1vbjE="
"user_ldap","s01ldap_attributes_for_group_search",
"user_ldap","s01ldap_attributes_for_user_search",
"user_ldap","s01ldap_backup_host",
"user_ldap","s01ldap_backup_port",
"user_ldap","s01ldap_base","OU=CiscoVPN,DC=xxxxxx,DC=com"
"user_ldap","s01ldap_base_groups","OU=CiscoVPN,DC=xxxxxx,DC=com"
"user_ldap","s01ldap_base_users","OU=CiscoVPN,DC=xxxxxx,DC=com"
"user_ldap","s01ldap_cache_ttl","600"
"user_ldap","s01ldap_configuration_active","1"
"user_ldap","s01ldap_default_ppolicy_dn",
"user_ldap","s01ldap_display_name","displayname"
"user_ldap","s01ldap_dn","CN=xxxxxx,OU=CiscoVPN,dc=xxxxxx,dc=com"
"user_ldap","s01ldap_dynamic_group_member_url",
"user_ldap","s01ldap_email_attr","mail"
"user_ldap","s01ldap_experienced_admin","0"
"user_ldap","s01ldap_expert_username_attr",
"user_ldap","s01ldap_expert_uuid_group_attr",
</details>

### Client configuration
**Browser:**

**Operating system:**

### Logs

<!--- Reports without logs might be closed as unqualified reports! -->

#### Web server error log
<details>
<summary>Web server error log</summary>

No errors as this is displaying the LDAP UID and not the LDAP username
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by blizzz** [comment]
Please report it to the Quick Notes developers https://github.com/matiasdelellis/quicknotes/issues
