### ISSUE TITLE
Make Search Field Selection Behavior Configurable (ScrollTo and Open)

### ISSUE THREAD

**Issue by WorksAtAUni** [nextcloud/server#29633]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Actually, the implementation of this feature: https://github.com/nextcloud/server/issues/7874#issue-288737043 / Open files directly from "search result in another folder" instead of using scrollto

**Describe the solution you'd like**
To make search behavior configurable, choose whether it opens/downloads the file or scrolls to in the share.

**Describe alternatives you've considered**
None.  Users have to suck it up.

**Additional context**
Don't think there are any. I get why the new feature was created and it makes sense, but removing existing functionality like this was an ugly surprise (and I have looked for configuration options to see if it is there, there is a possibility it was missed)>

**Comment by szaimen** [comment]
I think it was decided that this is the better flow. And I don't think that we'll make this configurable. But cc @skjnldsv and @artonge on this

**Comment by WorksAtAUni** [comment]
Ty for the CC, actually, I did leave out a little context (feels like a Monday). My guys use it as an anchor file for mass downloads. So they go "there" and then download it and the ones around it they want (our use case, btw, is remote sftp files shares from a vendor. We don't control the target shares and the NC provides the AAA layer for us). We download the ones we want to keep before the vendor culls them from the share.

**Comment by WorksAtAUni** [comment]
What essential information was missing? Happy to provide it.

**Comment by skjnldsv** [comment]
> What essential information was missing? Happy to provide it.

Me, I'm the missing information.
So, I think this is too complex unfortunately. We already try our best to not end up with a crazy config like 
![image](https://user-images.githubusercontent.com/14975046/148731129-11110b34-73ab-4e17-a025-53cccf96546d.png)

We took decisions over the last few versions to open the main action, and that's the way we want to go for now.
For your friend's specific use case, if he's doing public shares, he can link the download url straight away.
Cheers :)

**Comment by WorksAtAUni** [comment]
Appreciate the reply. It’s a corporate use case, but just on/off for the old behavior. Since right now it looks like I’m the only one complaining I know what that means!!! Lol.

Seriously, thank you for taking the time to reply.

**Comment by brendan-pike** [comment]
Throwing my hat in the ring.  Please provide configurable options of how search results function. Currently clicking a doc goes straight to edit, this seems insane to me and is a huge time and hardware resource waster.
