### ISSUE TITLE
Wrong simplified Chinese translation due to a typo

### ISSUE THREAD

**Issue by SonireolxXx** [nextcloud/server#2963]
### Steps to reproduce
1. Create two users, A and B
2. Login as user A, share a folder to user B, uncheck "can edit" box.
3. Login as user B, set webUI language to Chinese (Simplified), open the shared folder.

### Expected behaviour
Tell us what should happen
You should see "您没有权限在此上传或创建文件" (You don't have permission to upload orcreate files here)
### Actual behaviour
Tell us what happens instead
Wrong translation due to a typo "您没有权限来上传湖州哦和创建文件", 
### How to fix
This can be easily fixed by revise 2 files.
--> nextcloud/apps/files/l10n/zh_CN.json line:61
--> nextcloud/apps/files/l10n/zh_CN.js line:63

I'm a native Chinese speaker.

**Comment by rullzer** [comment]
Thanks for noticing!

You could join Nextcloud on [transifex](https://www.transifex.com/nextcloud/nextcloud/dashboard/) and directly edit it.

**Comment by MorrisJobke** [comment]
This is fixed on transifex now :)
