### ISSUE TITLE
get "security and setup warnings" via occ command

### ISSUE THREAD

**Issue by colttt** [nextcloud/server#29646]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
we have a bigger installation, if we do an upgrade and then we start everything on the "security and setup warnings"-Page we see sometimes some issues (like database-things or so), so now we should stop everything and solve these things, in between a lot of users try to use NC, because it was only for a short time.

**Describe the solution you'd like**
It would be nice if we can get this issues via cli/occ command, so we can fix the issues before we go back online.

**Comment by joshtrichards** [comment]
Fixed in #41081
