### ISSUE TITLE
stable23 branch split off

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#29647]
- [x] https://github.com/nextcloud/activity/pull/651
- [x] https://github.com/nextcloud/firstrunwizard/pull/633
- [x] https://github.com/nextcloud/logreader/pull/607
- [x] https://github.com/nextcloud/nextcloud_announcements/pull/89
- [x] https://github.com/nextcloud/notifications/pull/1109
- [x] https://github.com/nextcloud/password_policy/pull/290
- [x] https://github.com/nextcloud/photos/pull/925
- [x] https://github.com/nextcloud/serverinfo/pull/335
- [x] https://github.com/nextcloud/survey_client/pull/119
- [x] https://github.com/nextcloud/announcementcenter/pull/410
- [x] https://github.com/nextcloud/circles/pull/841
- [x] https://github.com/nextcloud/data_request/pull/61
- [x] https://github.com/nextcloud/deck/pull/3418
- [x] https://github.com/nextcloud/end_to_end_encryption/pull/271
- [x] https://github.com/nextcloud/files_accesscontrol/pull/219
- [x] https://github.com/nextcloud/files_automatedtagging/pull/512
- [x] https://github.com/nextcloud/files_retention/pull/144
- [x] https://github.com/nextcloud/groupfolders/pull/1745
- [x] https://github.com/nextcloud/impersonate/pull/137
- [x] https://github.com/nextcloud/ldap_contacts_backend/pull/36
- [x] https://github.com/nextcloud/ldap_write_support/pull/414
- [x] https://github.com/nextcloud/quota_warning/pull/81
- [x] https://github.com/nextcloud/sharepoint/pull/113
- [x] https://github.com/nextcloud/spreed/pull/6470
- [x] https://github.com/nextcloud/text/pull/1944
- [x] https://github.com/nextcloud/contacts/pull/2507
- [x] https://github.com/nextcloud/files_antivirus/pull/210
- [x] https://github.com/nextcloud/files_downloadactivity/pull/80
- [x] https://github.com/nextcloud/files_zip/pull/35
- [x] https://github.com/nextcloud/forms/pull/1070
- [x] https://github.com/nextcloud/guests/pull/788
- [x] https://github.com/nextcloud/mail/pull/5717
- [x] https://github.com/nextcloud/officeonline/pull/218
- [x] https://github.com/nextcloud/registration/pull/356
- [ ] https://github.com/nextcloud/twofactor_totp/pull/1155
- [x] https://github.com/nextcloud/twofactor_u2f/pull/956
- [x] https://github.com/nextcloud/user_oidc/pull/346
- [x] https://github.com/nextcloud/user_saml/pull/560

**Comment by PVince81** [comment]
I went through a lot of them.

Now most of the remaining ones are failing with `Could not find package christophwurst/nextcloud in a version matching dev-stable23', so we need to first upgrade that one @ChristophWurst

**Comment by nickvergessen** [comment]
- [ ] https://github.com/nextcloud/activity/pull/652
- [ ] https://github.com/nextcloud/files_pdfviewer/pull/518
- [ ] https://github.com/nextcloud/files_rightclick/pull/123
- [ ] https://github.com/nextcloud/files_videoplayer/pull/250
- [ ] https://github.com/nextcloud/firstrunwizard/pull/634
- [ ] https://github.com/nextcloud/logreader/pull/608
- [ ] https://github.com/nextcloud/nextcloud_announcements/pull/90
- [ ] https://github.com/nextcloud/notifications/pull/1110
- [ ] https://github.com/nextcloud/password_policy/pull/291
- [ ] https://github.com/nextcloud/photos/pull/926
- [ ] https://github.com/nextcloud/privacy/pull/661
- [ ] https://github.com/nextcloud/recommendations/pull/451
- [ ] https://github.com/nextcloud/serverinfo/pull/336
- [ ] https://github.com/nextcloud-gmbh/support/pull/115
- [ ] https://github.com/nextcloud/survey_client/pull/120
- [ ] https://github.com/nextcloud/viewer/pull/1065
- [ ] https://github.com/nextcloud/announcementcenter/pull/411
- [ ] https://github.com/nextcloud/backup/pull/60
- [ ] https://github.com/nextcloud/circles/pull/842
- [ ] https://github.com/nextcloud/data_request/pull/62
- [ ] https://github.com/nextcloud/deck/pull/3419
- [ ] https://github.com/nextcloud/end_to_end_encryption/pull/272
- [ ] https://github.com/nextcloud/external/pull/280
- [ ] https://github.com/nextcloud/files_accesscontrol/pull/220
- [ ] https://github.com/nextcloud/files_automatedtagging/pull/513
- [ ] https://github.com/nextcloud/files_fulltextsearch/pull/141
- [ ] https://github.com/nextcloud/files_retention/pull/145
- [ ] https://github.com/nextcloud/flow_notifications/pull/40
- [ ] https://github.com/nextcloud/fulltextsearch/pull/657
- [ ] https://github.com/nextcloud/fulltextsearch_elasticsearch/pull/173
- [ ] https://github.com/nextcloud/groupfolders/pull/1746
- [ ] https://github.com/nextcloud/impersonate/pull/138
- [ ] https://github.com/nextcloud/ldap_contacts_backend/pull/37
- [ ] https://github.com/nextcloud/ldap_write_support/pull/415
- [ ] https://github.com/nextcloud/quota_warning/pull/82
- [ ] https://github.com/nextcloud/ransomware_protection/pull/106
- [ ] https://github.com/nextcloud/sharepoint/pull/114
- [ ] https://github.com/nextcloud/spreed/pull/6471
- [ ] https://github.com/nextcloud/terms_of_service/pull/633
- [ ] https://github.com/nextcloud/text/pull/1947
- [ ] https://github.com/nextcloud/user_retention/pull/389
- [ ] https://github.com/nextcloud/user_usage_report/pull/76
- [ ] https://github.com/nextcloud/workflow_pdf_converter/pull/356
- [ ] https://github.com/nextcloud/bruteforcesettings/pull/333
- [ ] https://github.com/nextcloud/calendar/pull/3636
- [ ] https://github.com/nextcloud/contacts/pull/2508
- [ ] https://github.com/nextcloud/files_antivirus/pull/211
- [ ] https://github.com/nextcloud/files_downloadactivity/pull/81
- [ ] https://github.com/nextcloud/files_downloadlimit/pull/24
- [ ] https://github.com/nextcloud/files_texteditor/pull/501
- [ ] https://github.com/nextcloud/files_zip/pull/36
- [ ] https://github.com/nextcloud/forms/pull/1071
- [ ] https://github.com/nextcloud/guests/pull/789
- [ ] https://github.com/nextcloud/integration_discourse/pull/24
- [ ] https://github.com/nextcloud/integration_github/pull/32
- [ ] https://github.com/nextcloud/integration_gitlab/pull/33
- [ ] https://github.com/nextcloud/integration_google/pull/85
- [ ] https://github.com/nextcloud/integration_jira/pull/24
- [ ] https://github.com/nextcloud/integration_mastodon/pull/20
- [ ] https://github.com/nextcloud/integration_moodle/pull/30
- [ ] https://github.com/nextcloud/integration_reddit/pull/20
- [ ] https://github.com/nextcloud/integration_twitter/pull/28
- [ ] https://github.com/nextcloud/integration_whiteboard/pull/41
- [ ] https://github.com/nextcloud/integration_zammad/pull/23
- [ ] https://github.com/nextcloud/jsloader/pull/27
- [ ] https://github.com/nextcloud/mail/pull/5718
- [ ] https://github.com/nextcloud/officeonline/pull/219
- [ ] https://github.com/nextcloud/preferred_providers/pull/27
- [ ] https://github.com/nextcloud/registration/pull/357
- [ ] https://github.com/nextcloud/richdocuments/pull/1857
- [ ] https://github.com/nextcloud/suspicious_login/pull/571

**Comment by nickvergessen** [comment]
> Now most of the remaining ones are failing with `Could not find package christophwurst/nextcloud in a version matching dev-stable23', so we need to first upgrade that one

Done, but currently waiting for 23 rebuilding
