### ISSUE TITLE
User cannot log in the web interface

### ISSUE THREAD

**Issue by florian434** [nextcloud/server#2967]
### Steps to reproduce
1. Log in with a user account on the Web Page
2.
3.

### Expected behaviour
The user is logged and can access the main page with his folder / files

### Actual behaviour
The account page "loops" and the user is invited to loggin again and again. The same account is working fine with the desktop client / ios Client or Webdav

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache 2.4

**Database:** MySQL 5.6

**PHP version:** 5.6

**Nextcloud version:** (see Nextcloud admin page) 11.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** OC9.1 -> NC10.2 -> NC11.0.0

**Where did you install Nextcloud from:** 

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here. 

No errors have been found.

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

  - activity: 2.4.1
  - admin_audit: 1.1.0
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - gallery: 16.0.0
  - keeweb: 0.3.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 0.5.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - documents
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - files_videoplayer
  - firstrunwizard
  - spreed
  - user_external
  - user_ldap
  - user_saml

</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
<pre>
{
    "system": {
        "instanceid": "oc86wi0oh5xi",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "XXX",
            "XXX",
            "XXX"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/XXX\/owncloud",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "dbname": "OwnCloudDB",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "owncloud",
        "mail_domain": "XXX",
        "mail_smtphost": "mail.XXX",
        "mail_smtpport": "25",
        "theme": "",
        "maintenance": false,
        "loglevel": 0,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "appstore.experimental.enabled": true,
        "preview_libreoffice_path ": "\/usr\/bin\/libreoffice",
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
</pre>
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/... No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/ No

### Client configuration
**Browser:** Chrome / Edge / IE

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

_{"reqId":"HDTOaGKjaK2vONtjRARI"	remoteAddr:"XXX.XXX.XXX.XXX"	app:"no app in context" message:"Current user is not logged in"	level:0	time:"2017-01-05T13:07:55+00:00"	method:"GET" url:"\/index.php\/apps\/files\/"	user:"--"	version:"11.0.0.10"}	_
{"reqId":"O6NWJu3MuvcjcEpuN6IC"	remoteAddr:"XXX.XXX.XXX.XXX"	app:"no app in context" message:"Current user is not logged in"	level:0	time:"2017-01-05T13:07:56+00:00"	method:"GET" url:"\/index.php\/apps\/gallery\/config?extramediatypes=1"	user:"--"	version:"11.0.0.10"}

</details>

#### Browser log
<details>
<summary>Browser log</summary>

</details>

**Comment by MorrisJobke** [comment]
Can I ask you to show us the network tab of the web developer tools in your browser?

**Comment by florian434** [comment]
Do you want the complete Network tad or just the errors ? 

Here are just the error : 
![1](https://cloud.githubusercontent.com/assets/24958237/21799279/d545e162-d718-11e6-9c68-2abd9ff895c1.PNG)

**Comment by MorrisJobke** [comment]
> Do you want the complete Network tad or just the errors ?

Which page is this? The login page? Also the 400 on the loginbackground looks suspicious.

**Comment by florian434** [comment]
This is on the login page yes with a user that can't connect.

**Comment by MorrisJobke** [comment]
I can't see why this should happen. The config of the gallery is normally not loaded on the login page and the login background should be fine.

Could you try to disable one app after another and check if the login then works. Maybe it's an app that causes this. Maybe start with keeweb.

**Comment by florian434** [comment]
I try to disable the following app with no luck : 

Keeweb
totp
Usage Survey
Gallery
Theming
Text Editor
Share by Email
PDF Viewer
Server Info
Password Policy
Notifications
Nextcloud announcements
Mail template editor
Log Reader
Federation
Comments
Collaborative tags
Auditing / Logging

**Comment by MorrisJobke** [comment]
@rullzer Any ideas?

**Comment by florian434** [comment]
Any news ?

It's getting urgent, my user cannot connect anymore to the web page......

Thanks

**Comment by MorrisJobke** [comment]
> It's getting urgent, my user cannot connect anymore to the web page......
> 
> Thanks

Can you check again your log and maybe check if entries are logged when the user logs in.

Does this only happen for one user? Can you create a separate user and try to log in with this user? Does that work?  Does the user has received federated shares? (for this check the table `oc_share_external`)

**Comment by florian434** [comment]
It happens for all the user, even mine with a browser with no cache : on my laptop with cache on Chrome I can log with all users but if I try the same thing on another laptop (same accounts or Chrome version) it does not work. I also tried with Edge or IE and it does not work.

Same logs : 
_{"reqId":"HDTOaGKjaK2vONtjRARI"	remoteAddr:"XXX.XXX.XXX.XXX"	app:"no app in context" message:"Current user is not logged in"	level:0	time:"2017-01-05T13:07:55+00:00"	method:"GET" url:"/index.php/apps/files/"	user:"--"	version:"11.0.0.10"}	_
{"reqId":"O6NWJu3MuvcjcEpuN6IC"	remoteAddr:"XXX.XXX.XXX.XXX"	app:"no app in context" message:"Current user is not logged in"	level:0	time:"2017-01-05T13:07:56+00:00"	method:"GET" url:"/index.php/apps/gallery/config?extramediatypes=1"	user:"--"	version:"11.0.0.10"}

For new users, it is the same : I can log with Chrome on my laptop but not on the other laptop or with different browser.

I checked that cookies are enable.

**Comment by florian434** [comment]
Ok for the record, I applied the 11.0.1 RC1 update and everything is working fine again.

**Comment by tetienne** [comment]
Hi,

I have exactly the same issue explain in the first message by@florian434. I've done a fresh install of NextCloud 11.0.1 on a CentOs 7 with PHP 7.1 and Nginx. I can use the Android application (upload file, use calendar and contact sync etc.) but I'm not able to login on the Web Interface.
There is no error in the server log nor Nextcloud log. 
I've also the same 401 status shown [here](https://github.com/nextcloud/server/issues/2967#issuecomment-271517098)

Can we open this issue? How can I help?

**Comment by sgumirov** [comment]
Same issue. Arch, Nginx, MariaDB, Nextcloud 11.0.1 (stable). Should I create new issue or someone can  reopen this one?

**Comment by thibaut-sticky** [comment]
Any update on this still valid issue?

**Comment by tisc0** [comment]
Same issue, centos 7, fresh install 11.0.2, php7.0.17, selinux disabled.
Thanks !

**Comment by tisc0** [comment]
Got my mistake, thanks to this post : 
https://help.nextcloud.com/t/fresh-install-of-11-0-1-login-loop/8724/7

Using phpfpm from remi, with multiple versions installed, I had no rights to write my sessions files.
Checked my nextcloud.log file and quickly solved it :

{"reqId":"WMxSsmZuq88aEg9ZlzQ89QAAABA","remoteAddr":"192.168.190.10","app":"PHP","message":"session_write_close(): Failed to write session data (files). Please verify that the current setting of session.save_path is correct (\/var\/opt\/remi\/php70\/lib\/php\/session) at \/var\/www\/html\/nextcloud\/lib\/private\/Session\/Internal.php#104","level":3,"time":"2017-03-17T21:18:42+00:00","method":"GET","url":"\/index.php\/apps\/gallery\/config?extramediatypes=1","user":"--","version":"11.0.2.7"}

So finally started and so far so good, thanks again !

**Comment by benvdh** [comment]
Had a similar issue, though I didn't see it appear in the logs. Note that remi's packages do not store their sessions in /tmp, nor /var/lib/php/session, but in /var/opt/remi/php71/lib/php/session.

This path is set in /etc/opt/remi/php71/php-fpm.d/www.conf, not in /etc/opt/remi/php71/php.ini.

Now fixed by chowning them to nginx:nginx...

**Comment by ml31415** [comment]
I had to restore the `.tmp` folder in order for the login to work and being able to create session files.

**Comment by wayneoutthere** [comment]
having similar issue with nextcloudpi - opening https://github.com/nextcloud/server/issues/9054

**Comment by robertpavlovic10** [comment]
In my case on NC13 we are using two apps: user_ldap and user_saml. Accidently I have setted value "enabled" to "no" for bouth apps in DB and the final result was this log error.

**Comment by nkostovsky** [comment]
same issue again, but clearing coockies doesn't work now

**Comment by MorrisJobke** [comment]
> same issue again, but clearing coockies doesn't work now

New ticket please.



> In my case on NC13 we are using two apps: user_ldap and user_saml. Accidently I have setted value "enabled" to "no" for bouth apps in DB and the final result was this log error.

Enabling both should work, but please never just edit the DB. This can break your instance. ;) Just use the buttons in the web UI or the CLI tool `occ app:enable`. There is more than a config switch to be made.

**Comment by milksomelier** [comment]
same issue again , will hope it fixes alone in an update or something , but this login loop from the web interface is anoying . The calendar and app..etc works fine
