### ISSUE TITLE
22.2.1 is very slow

### ISSUE THREAD

**Issue by DmDS** [nextcloud/server#29678]
after upgrading to 22.2.1, nextcloud is very slow. after opening the page, everything is fine. after 1-2 minutes (possibly inactivity), the load on the web server increases greatly during rendering (I tried apache and nginx. php 7.4 and 8.0. and installed nextcloud from scratch). the site loads very slowly. if you log out of the account and log in again or restart the browser, it starts working fine, but after 1-2 minutes everything slows down again.
on a test machine with one user, this is still fast enough. in the working environment, it slows down much more.

<details>
 <summary>gif</summary>

![Запись_2021_11_12_14_24_27_953](https://user-images.githubusercontent.com/1803032/141460412-c436b2fc-0576-4e89-adb0-d64cd6b6402f.gif)
</details>

**Comment by jacotec** [comment]
I copy this! Updated by "test cloud" and the "felt performance" dropped by around factor 10! Switching to a different app in the menu takes around 5 or more seconds, while it was "immediately" before.

I've rolled back the snapshot and I'm currently retesting. But for now I explicitely warn anyone from upgrading to 22.2.1 in production environments!

**Comment by DmDS** [comment]
when disabling the Theming application, rendering is faster, but still much slower than in the first 1-2 minutes after opening the page. and the load on the web server is the same high.

**Comment by jacotec** [comment]
Confirmed on a second instance!

Some times to compare on the instance before and after the upgrade (from clicking until all page elements have been loaded):

Changing from files view to the room overview of BigBlueButton:
22.2.0: 1,4 sec     /     22.2.1: 16,7 sec

Back to the file view:
22.2.0: 3.2 sec     /    22.2.1: 27,3 sec

To calendar view:
22.2.0: 3,8 sec   /    22.2.1: 30,2 sec

@szaimen Pulling back immediately the 22.2.1 release is a wise decision! ;-)

**Comment by JB1985** [comment]
Are there any problems with 21.0.6?  Can anybody confirm this?

**Comment by szaimen** [comment]
21.0.6 should work fine as https://github.com/nextcloud/server/pull/29380 wasn't merged yet

**Comment by tdoerschel** [comment]
I can confirm this on apache 2.4.51 and PHP 8.0-FPM

**Comment by nickvergessen** [comment]
Patch forward is at https://github.com/nextcloud/server/pull/29681

**Comment by jacotec** [comment]
@nickvergessen Will there be a bugfix release (22.2.2) in short term, or what is the plan?

**Comment by nickvergessen** [comment]
Not my department sorry, but you can apply the patch manually for now:
https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html#getting-a-patch-from-a-github-pull-request

**Comment by cwilby** [comment]
This was some fast work 😐

Nice work all
