### ISSUE TITLE
App button is looking weird

### ISSUE THREAD

**Issue by cyberpower678** [nextcloud/server#29696]
<img width="128" alt="Screen Shot 2021-11-13 at 21 40 05" src="https://user-images.githubusercontent.com/1476075/141665519-57615614-9cf9-4b79-a96b-34447f373b3f.png">
On 22.2.2

**Comment by szaimen** [comment]
Hi there, please report this to https://gitnet.fr/deblan/side_menu.
Thanks!

**Comment by cyberpower678** [comment]
@szaimen please explain why I need to report an issue with the NextCloud UI with some third party app on some other repo on a completely different repo farm?
