### ISSUE TITLE
Onlyoffice document server no copy and paste function using share link once download is locked in NC

### ISSUE THREAD

**Issue by w202mg** [nextcloud/server#29704]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a shared link for a document
2. Switch off download option in sharing options
3. Open the shared link in another browserm copy some text and try to paste

### Expected behaviour
The copied text shall be pasted

### Actual behaviour
The text/picture were copied before is pasted, not the text that was just copied in the document

### Server configuration

**Operating system:**
The server is running on Debian 11
I reproduced on Debian and Windows, both in Firefox and Chrome.
**Web server:**
Nginx
**Database:**
Mira DB
**PHP version:**
7.4
**Nextcloud version:** (see Nextcloud admin page)
22.2.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated, but teh same issue I had also on a fresh install
**Where did you install Nextcloud from:**
official repo
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - approval: 1.0.7
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.4
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.6
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - deck: 1.5.5
  - documentserver_community: 0.1.11
  - extract: 1.3.2
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_accesscontrol: 1.12.1
  - files_automatedtagging: 1.12.0
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trackdownloads: 1.11.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - flow_notifications: 1.2.0
  - keeweb: 0.6.6
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - metadata: 0.14.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - onlyoffice: 7.2.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - polls: 3.3.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - spreed: 12.1.2
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflow_ocr: 1.22.2
  - workflow_pdf_converter: 1.7.0
  - workflow_script: 1.7.0
  - workflowengine: 2.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - mail
  - user_ldap</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "default_phone_region": "DE",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.net",
            "office.example.net",
            "cloud.example2.ru"
        ],
        "onlyoffice": {
            "verify_peer_off": true,
            "jwt_header": "Authorization",
            "jwt_secret": "XXX"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.2.0",
        "overwrite.cli.url": "https:\/\/cloud.example.net",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2
    }
}</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Separate HDD in same PC Tower
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
#### LDAP configuration (delete this part if not used)
<details>
<summary> There are no commands defined in the "ldap" namespace.</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Firefox and Chrome
**Operating system:**
Windows and Debian 11
#### Web server error log
<details>
<summary>error log of Nginx is empty</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>{"reqId":"I7fG8TFe0xWeFOWpkrY4","level":2,"time":"2021-10-07T20:10:32+00:00","remoteAddr":"127.0.0.1","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in https:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64;>
{"reqId":"I7fG8TFe0xWeFOWpkrY4","level":2,"time":"2021-10-07T20:10:32+00:00","remoteAddr":"127.0.0.1","user":"--","app":"no app in context","method":"GET","url":"/","message":"Could not detect any host in http:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linux x86_64; >
{"reqId":"jktuYuF2LxVXiICp0WQo","level":2,"time":"2021-10-07T20:15:27+00:00","remoteAddr":"127.0.0.1","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Could not detect any host in https:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Lin>
{"reqId":"jktuYuF2LxVXiICp0WQo","level":2,"time":"2021-10-07T20:15:27+00:00","remoteAddr":"127.0.0.1","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Could not detect any host in http:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linu>
{"reqId":"kpySiBn8wf0zxSiMsdPH","level":2,"time":"2021-10-07T20:17:55+00:00","remoteAddr":"127.0.0.1","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Could not detect any host in https:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Lin>
{"reqId":"kpySiBn8wf0zxSiMsdPH","level":2,"time":"2021-10-07T20:17:55+00:00","remoteAddr":"127.0.0.1","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":"Could not detect any host in http:///data/htaccesstest.txt","userAgent":"Mozilla/5.0 (X11; Linu>
</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Can't find any...</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by szaimen** [comment]
Hello, please report this to https://github.com/ONLYOFFICE/onlyoffice-nextcloud.
Thanks!

**Comment by w202mg** [comment]
@szaimen I did but the opinion for the monent is that this is not related to the OO but to NC.

**Comment by w202mg** [comment]
I forgot to mentiom that I'm using a selfhosted OO.

**Comment by w202mg** [comment]
Meanwhile using NC 22.2.3, same issue. Only on Android it works proeprly with every browser. On 2 different computeers with Windows 10 and Linus still the same.
