### ISSUE TITLE
Apply theme to manifest.json

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#29703]
The current manifest.json has the app name and icons hard-coded: https://github.com/nextcloud/server/blob/v22.2.0/core/img/manifest.json#L2

We should replace this file with an endpoint that returns the product name and custom icons when applicable.

This file is used mostly for browsers that allow to "add this website as app".

**Comment by szaimen** [comment]
Why not enable the theming app? It has all of this automatically applied...

**Comment by PVince81** [comment]
alright, my bad. I got a report and assumed that it didn't work.

just tested locally and the manifest is now taken from https://vvortex.local/index.php/apps/theming/manifest/settings?v=3 and returns the product name

sorry for the noise
