### ISSUE TITLE
Unable to open Settings (or Passwords App) because of an authentication issue

### ISSUE THREAD

**Issue by Kev-kr** [nextcloud/server#29719]
After using WebAuth for Loging in and then restarting the Browser, you are unable to open the Settings menu and Nextcloud Passwords App because of an authentication issue, reported by the Nextcloud Server. Everything else works as normal. This issue only happens when using WebAuth for Loging in
(Nextcloud 22.2.2)

**Comment by GitHubBrainstorm** [comment]
When sharing a folder with users. Search does not work. For Ldap and local users. - version 22.2.2.0
