### ISSUE TITLE
Create github release for version 22.2.2

### ISSUE THREAD

**Issue by ntimo** [nextcloud/server#29713]
Hey,
I noticed that there is no release for the latest bug fix version of nextcloud on github. This is quite bad since I would guess a few people including myself are using automations (Renovate) to auto create merge requests to update nextcloud. We are therefore missing out on this update and since this update also seems to be quite important there should be a github release for it the moment the update got released :)

### Steps to reproduce
1. Open the nextcloud github project page
2. Go to the releases
3. See that there is no release for version 22.2.2

### Expected behaviour
For every new Nextcloud release there should be a github release at https://github.com/nextcloud/server/

### Actual behaviour
There should be  a release for the latest version of nextcloud.

**Comment by acsfer** [comment]
There is 22.2.3 already.

**Comment by ntimo** [comment]
@Stunkymonkey  Yeah that are tags and not Github releases, that makes a big difference :D 
There is no 22.2.2 and 22.2.3 on https://github.com/nextcloud/server/releases

**Comment by ntimo** [comment]
Seems like the release is now available thanks :)

**Comment by ntimo** [comment]
For ref: https://github.com/nextcloud/server/releases/tag/v22.2.3 https://github.com/nextcloud/server/releases/tag/v22.2.2
