### ISSUE TITLE
Disable right click on shared file when hide download

### ISSUE THREAD

**Issue by leviia** [nextcloud/server#29722]
Hello 

It would be a great enhancement to prevent right click on shared file when "hide download" is on 

It can be as simple as adding this js to the file  apps/files_sharing/js/public.js

```
//prevent right-click when download is hidden
if (hideDownload === 'true') {
    document.addEventListener("contextmenu", function(e){
        e.preventDefault();
    }, false);
}
```
Or this code (using JQuery)
```
//prevent right-click when download is hidden
if (hideDownload === 'true') {
    $(document).on('contextmenu', function () {
        return false;
    });
}
```

I know the user is still able to bypass that but at least it is not that easy to download a file 

I know also here we prevent the right click on the whole page (because of ```document```), you can narrow it down to the exact div if you know which one). 

At least it works 

Has something like this a chance to be implemented in mainline ? So everyone will get this functionality.

All the best 

Arnaud

**Comment by elhananjair** [comment]
@leviia that's awesome.
Can you mention this issue directly on right click app repo...

**Comment by skjnldsv** [comment]
Done for 31 https://github.com/nextcloud/viewer/pull/2482
