### ISSUE TITLE
Reuse compliance / license identifier / SPDX

### ISSUE THREAD

**Issue by CarlSchwan** [nextcloud/server#29723]
There is now a specification about how to declare license in for our source code: [reuse.software](https://reuse.software/)

This would allow to replace:

```php
<?php
/**
 * @copyright Copyright (c) 2016, ownCloud, Inc.
 *
 * @author Christoph Wurst <christoph@winzerhof-wurst.at>
 * @author Joas Schilling <coding@schilljs.com>
 *
 * @license AGPL-3.0
 *
 * This code is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License, version 3,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License, version 3,
 * along with this program. If not, see <http://www.gnu.org/licenses/>
 *
 */
```

with 

```php
<?php
/**
 * SPDX-FileCopyrightText: 2016, ownCloud, Inc.
 * SPDX-FileCopyrightText: Christoph Wurst <christoph@winzerhof-wurst.at>
 * SPDX-FileCopyrightText: Joas Schilling <coding@schilljs.com>
 * SPDX-License-Identifier: AGPL-3.0-only
 */
```

This has the following advantages:

* It's shorter :)
* It's machine-readable, so we can have a CI job verify that no file is missing licensing statements
* It's standardized using SPDX identifiers and is starting to get adopted in many other large open-source projects: e.g. Linux kernel, KDE

For porting to SPDX, I had a good experience using [licensedigger](https://invent.kde.org/sdk/licensedigger). It supports a wide range of licenses and is easy to add more in our case AGPL-3.0-or-later and AGPL-3.0-only. If people are okay I could do that in some small apps first so that we can look at the result before doing the server repo.

**Comment by CarlSchwan** [comment]
I ported the profiler repo to use it https://github.com/nextcloud/profiler/pull/14

**Comment by schiessle** [comment]
It would be really great if we would become reuse compliant, thanks for bringing this up @CarlSchwan 

Sometimes we also need to provide a overview over all Free Software licenses withing Nextcloud, this would also make it easier to compile such a list.

**Comment by mgallien** [comment]
Switching to reuse compliant license/copyright notices would also allow to automatically check for compliance in our CI pipelines on pull requests
see https://reuse.software/dev/#ci

**Comment by CarlSchwan** [comment]
I started porting groupfolders to reuse here: https://github.com/nextcloud/groupfolders/pull/2046

This requires the following patch to teach licensedigger to correctly identify Nextcloud headers https://invent.kde.org/sdk/licensedigger/-/merge_requests/99

**Comment by juliushaertl** [comment]
Has been done with https://github.com/nextcloud/server/pull/45244 and several follow up prs.
