### ISSUE TITLE
Force sync a ldap GROUP through command line or API

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/server#29727]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Today, an internal workflow allows a user to create a share for a group (groupfolder).
The group creation is done in our LDAP, and once the group created, a script triggers on Nextcloud side the creation of the share.
The existence of the group can be chacked via a occ ldap :search --group myGroup.
The group then exists on Nextcloud side, but isn't populated: we then set permissions on an empty group, users seeing the group only once the group content had been updated by the Cron job.

**Describe the solution you'd like**
A command `occ ldap: group-update myGroup` (or a group content feeding when a `occ ldap :search --group` command if the group wouldn't be referenced) would then make our process "immediate".

like `occ ldap:check-group --fetch $GROUPNAME` or `occ ldap:check-group --update $GROUPID`

**Additional content**
A similar demand exists to force the sync of a specific LDAP user : https://github.com/nextcloud/server/issues/27948

**Comment by Constey** [comment]
any news on this? could need it aswell :-)

**Comment by come-nc** [comment]
> any news on this? could need it aswell :-)

It was merged in master and will be in 28, I forgot to link the PR to the issue.
It will be a new ldap:check-group command inspired by the ldap:check-user command. Documentation is not there yet.

**Comment by joshtrichards** [comment]
Fixed in #39446 
Docs added in nextcloud/documentation#11079
