### ISSUE TITLE
After updating to Nextcloud 22.2.3, error 503, maintenance mode

### ISSUE THREAD

**Issue by siSSSou** [nextcloud/server#29725]
### Steps to reproduce
1. Upgrade nextcloud to 22.2.3 with web updater

### Expected behaviour
I should be able to log in

### Actual behaviour
Maintenance mode is set to false in config but message is on with nginx error 503 and "Maintenance mode" message

### Server configuration

**Operating system:**
Debian 10 64bit

**Web server:**
Nginx

**Database:**
10.3.31

**PHP version:**
PHP 7.3.31-1~deb10u1 (cli) (built: Oct 24 2021 15:18:08) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)
22.2.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 22.2.2

**Where did you install Nextcloud from:**
Manual install with downloaded zip

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - appointments: 1.10.2
  - apporder: 0.13.0
  - bookmarks: 10.0.2
  - calendar: 2.3.4
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.6
  - contactsinteraction: 1.3.0
  - dav: 1.19.0
  - deck: 1.5.5
  - drawio: 1.0.1
  - external: 3.9.0
  - extract: 1.3.2
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_mindmap: 0.0.25
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - maps: 0.1.9
  - metadata: 0.14.0
  - nextcloud_announcements: 1.11.0
  - notes: 4.2.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - polls: 3.3.0
  - previewgenerator: 3.2.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - qownnotesapi: 21.7.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - bruteforcesettings
  - circles
  - dashboard
  - encryption
  - files_external
  - phonetrack
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.roger1.fr"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.3.0",
        "overwrite.cli.url": "https:\/\/nextcloud.roger1.fr",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_smtpmode": "sendmail",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 3,
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "drawio",
            "keeweb",
            "previewgenerator"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Firefox

**Operating system:**
Debian 11

#### Web server error log
<details>
<summary>Web server error log</summary>
192.168.0.254 - - [16/Nov/2021:07:10:28 +0100] "GET /status.php HTTP/2.0" 200 168 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - vincent [16/Nov/2021:07:10:44 +0100] "POST /index.php/apps/bookmarks/public/rest/v2/lock HTTP/2.0" 503 10993 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - vincent [16/Nov/2021:07:10:44 +0100] "DELETE /index.php/apps/bookmarks/public/rest/v2/lock HTTP/2.0" 503 10993 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - - [16/Nov/2021:07:10:48 +0100] "GET /status.php HTTP/2.0" 200 168 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - vincent [16/Nov/2021:07:10:56 +0100] "PROPFIND /remote.php/dav/files/vincent/ HTTP/1.1" 503 282 "-" "Mozilla/5.0 (Linux) mirall/3.1.1-2+deb11u1 (Nextcloud)"
192.168.0.254 - - [16/Nov/2021:07:11:09 +0100] "GET /status.php HTTP/2.0" 200 168 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - vincent [16/Nov/2021:07:11:23 +0100] "PROPFIND /remote.php/dav/calendars/vincent/personnel/ HTTP/1.1" 503 2331 "-" "Evolution/3.38.3"
192.168.0.254 - vincent [16/Nov/2021:07:11:23 +0100] "REPORT /remote.php/dav/calendars/vincent/personnel/ HTTP/1.1" 503 2331 "-" "Evolution/3.38.3"
192.168.0.254 - vincent [16/Nov/2021:07:11:26 +0100] "GET /ocs/v2.php/apps/notifications/api/v2/notifications?format=json HTTP/1.1" 503 107 "-" "Mozilla/5.0 (Linux) mirall/3.1.1-2+deb11u1 (Nextcloud)"
192.168.0.254 - vincent [16/Nov/2021:07:11:26 +0100] "PROPFIND /remote.php/dav/files/vincent/ HTTP/1.1" 503 282 "-" "Mozilla/5.0 (Linux) mirall/3.1.1-2+deb11u1 (Nextcloud)"
192.168.0.254 - - [16/Nov/2021:07:11:29 +0100] "GET /status.php HTTP/2.0" 200 168 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - vincent [16/Nov/2021:07:11:44 +0100] "POST /index.php/apps/bookmarks/public/rest/v2/lock HTTP/2.0" 503 10993 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - vincent [16/Nov/2021:07:11:44 +0100] "DELETE /index.php/apps/bookmarks/public/rest/v2/lock HTTP/2.0" 503 10993 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - - [16/Nov/2021:07:11:49 +0100] "GET /status.php HTTP/2.0" 200 168 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - vincent [16/Nov/2021:07:11:56 +0100] "PROPFIND /remote.php/dav/files/vincent/ HTTP/1.1" 503 282 "-" "Mozilla/5.0 (Linux) mirall/3.1.1-2+deb11u1 (Nextcloud)"
192.168.0.254 - - [16/Nov/2021:07:12:09 +0100] "GET /status.php HTTP/2.0" 200 168 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - vincent [16/Nov/2021:07:12:26 +0100] "PROPFIND /remote.php/dav/files/vincent/ HTTP/1.1" 503 282 "-" "Mozilla/5.0 (Linux) mirall/3.1.1-2+deb11u1 (Nextcloud)"
192.168.0.254 - - [16/Nov/2021:07:12:29 +0100] "GET /status.php HTTP/2.0" 200 168 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - vincent [16/Nov/2021:07:12:38 +0100] "GET /ocs/v2.php/cloud/capabilities?format=json HTTP/1.1" 503 107 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.17.1"
192.168.0.254 - vincent [16/Nov/2021:07:12:44 +0100] "POST /index.php/apps/bookmarks/public/rest/v2/lock HTTP/2.0" 503 10993 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - vincent [16/Nov/2021:07:12:44 +0100] "DELETE /index.php/apps/bookmarks/public/rest/v2/lock HTTP/2.0" 503 10993 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - - [16/Nov/2021:07:12:49 +0100] "GET /status.php HTTP/2.0" 200 168 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - vincent [16/Nov/2021:07:12:56 +0100] "PROPFIND /remote.php/dav/files/vincent/ HTTP/1.1" 503 282 "-" "Mozilla/5.0 (Linux) mirall/3.1.1-2+deb11u1 (Nextcloud)"
192.168.0.254 - - [16/Nov/2021:07:13:09 +0100] "GET /status.php HTTP/2.0" 200 168 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - vincent [16/Nov/2021:07:13:26 +0100] "PROPFIND /remote.php/dav/files/vincent/ HTTP/1.1" 503 282 "-" "Mozilla/5.0 (Linux) mirall/3.1.1-2+deb11u1 (Nextcloud)"
192.168.0.254 - - [16/Nov/2021:07:13:29 +0100] "GET /status.php HTTP/2.0" 200 168 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - vincent [16/Nov/2021:07:13:44 +0100] "POST /index.php/apps/bookmarks/public/rest/v2/lock HTTP/2.0" 503 10993 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - vincent [16/Nov/2021:07:13:44 +0100] "DELETE /index.php/apps/bookmarks/public/rest/v2/lock HTTP/2.0" 503 10993 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - - [16/Nov/2021:07:13:49 +0100] "GET /status.php HTTP/2.0" 200 168 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - vincent [16/Nov/2021:07:13:56 +0100] "PROPFIND /remote.php/dav/files/vincent/ HTTP/1.1" 503 282 "-" "Mozilla/5.0 (Linux) mirall/3.1.1-2+deb11u1 (Nextcloud)"
192.168.0.254 - - [16/Nov/2021:07:14:09 +0100] "GET /status.php HTTP/2.0" 200 168 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - vincent [16/Nov/2021:07:14:26 +0100] "PROPFIND /remote.php/dav/files/vincent/ HTTP/1.1" 503 282 "-" "Mozilla/5.0 (Linux) mirall/3.1.1-2+deb11u1 (Nextcloud)"
192.168.0.254 - - [16/Nov/2021:07:14:30 +0100] "GET /status.php HTTP/2.0" 200 168 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - vincent [16/Nov/2021:07:14:44 +0100] "POST /index.php/apps/bookmarks/public/rest/v2/lock HTTP/2.0" 503 10993 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - vincent [16/Nov/2021:07:14:44 +0100] "DELETE /index.php/apps/bookmarks/public/rest/v2/lock HTTP/2.0" 503 10993 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
192.168.0.254 - - [16/Nov/2021:07:14:50 +0100] "GET /status.php HTTP/2.0" 200 168 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0"
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
no nextcloud log ?!
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by szaimen** [comment]
If this is a bug with Nextcloud, there must be a log somewhere. Please provide it!

**Comment by szaimen** [comment]
Maybe its the same issue like https://github.com/nextcloud/server/issues/29724

**Comment by siSSSou** [comment]
Unfortunately, log file (/var/www/nextcloud/data/nextcloud.log is empty : what loglevel should be specified in config.php to get useful logs ?

My Nextcloud instance is back : I had to restart php7.3-fpm !!??

**Comment by acsfer** [comment]
> My Nextcloud instance is back : I had to restart php7.3-fpm !!??
Well, this is a setup problem. Maybe Opcode had to be flushed.
