### ISSUE TITLE
"Global credentials" in "External storage" is unclear

### ISSUE THREAD

**Issue by jbicha** [nextcloud/server#2972]
### Steps to reproduce
1. Install Nextcloud 11.
2. In Apps, ensure "External storage support" is enabled.
3. In Admin, click "External storage".

### Actual behavior
There is a "Global credentials" section with no explanation. It is not documented in the [Admin Manual](https://docs.nextcloud.com/server/11/admin_manual/configuration_files/external_storage/auth_mechanisms.html).

![nextcloud-global-credentials](https://cloud.githubusercontent.com/assets/876259/21740529/37c0c636-d48a-11e6-9bb0-214493213900.png)

I think it is only used for SMB style sharing but since I don't have php-smbclient on this Ubuntu server, it probably shouldn't even show up.

### Expected behavior
- Reword the section to include an explanation of what the Credentials are for.
- Provide a slightly wordier explanation in the Admin Manual.

**Comment by nickvergessen** [comment]
When you add an external storage on the table above, you can select "Global credentials" in the Authentication dropdown.

See the last point of https://docs.nextcloud.com/server/11/admin_manual/configuration_files/external_storage/auth_mechanisms.html#password-based-mechanisms
