### ISSUE TITLE
Rename "External storages" to "External storage"

### ISSUE THREAD

**Issue by jbicha** [nextcloud/server#2973]
Nextcloud 11 with the "External storage support" enabled.

In the right sidebar, "External storages" should be renamed to "External storage". Storage is a collective plural noun in English and does not need a letter S at the end. Dropping the S would also match the text on the external storage settings page.

![nextcloud-global-credentials](https://cloud.githubusercontent.com/assets/876259/21740529/37c0c636-d48a-11e6-9bb0-214493213900.png)

**Comment by MariusBluem** [comment]
THX! I've seen your commits. Feel free to submit them as a PR - then we can discuss and review them ✊

**Comment by tflidd** [comment]
ref: https://github.com/nextcloud/server/pull/2975

**Comment by jbicha** [comment]
My pull request was incomplete. Since I don't know how to fix it up and this isn't a priority, we're just leaving this issue open until someone gets around to fixing this up.

**Comment by MorrisJobke** [comment]
cc @jancborchardt because you renamed this in #4551 

I guess we can close this ticket here then as won't fix, right?

**Comment by jancborchardt** [comment]
Oh, I wasn’t aware of this issue when I did that pull request. @jbicha do you mind going over the occurences and fixing them? Since you seem to be a native speaker it might be better for you to go over it. :)

**Comment by jbicha** [comment]
@jancborchardt I tried to take care of it myself, but it ended up getting complicated. Please take a look at
https://github.com/nextcloud/server/pull/2975 and feel free to fix it up.

**Comment by szaimen** [comment]
PR here: #27039
