### ISSUE TITLE
Downloadproblems with 16MBit connection

### ISSUE THREAD

**Issue by Micha-Btz** [nextcloud/server#2974]
This can be also found in https://help.nextcloud.com/t/file-download-not-possible-debug-help/6879

hi there,

I'm not able to download files with ca 350-400MB android nextcloud stable/beta, foldersync app, smartphone browser and desktop firefox. The download cancelled mostly after 250MB.

i have tried to debug this more and here are some infos. All downloads are worked fine today on work with 100MBit internet connection. At home with 16Mbit internet connection all downloads are go about 200MB and then break up.

### Steps to reproduce
1. Download files

### Expected behaviour
download went fine

### Actual behaviour
download break about 200MB

### Server configuration - Hosting Package
**Operating system**:
Debian stable

**Web server:**
apache 2.4.1
**Database:**
MariaDB
**PHP version:**
7.01
**Nextcloud version:** 
10.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from oc to nc 9, then update with new updater scrpit
**Where did you install Nextcloud from:**
website
**Signing status:**
all fine

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

~/mdomann.tk/owncloud/htdocs$ php occ config:list 
{
    "system": {
        "instanceid": "oca2cf00c606",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "tdl.tdl"
        ],
        "datadirectory": "\/var\/www\/virtual\/web41856.pfweb.eu\/mdomann.tk\/owncloud\/htdocs\/data",
        "dbtype": "mysql",
        "version": "9.1.2.2",
        "dbname": "332_owncloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_from_address": "mdomann",
        "mail_smtpmode": "php",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "mdomann.tk",
        "loglevel": 0,
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true,
        "htaccess.RewriteBase": "\/",
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
        "updater.release.channel": "stable"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.3.2",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "no",
            "installed_version": "1.0.0",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "62"
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.4.1",
            "ocsid": "168707",
            "types": ""
        },
        "comments": {
            "enabled": "no",
            "installed_version": "0.2",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "1.5.1",
            "ocsid": "168708",
            "types": ""
        },
        "core": {
            "OC_Channel": "stable",
            "backgroundjobs_mode": "webcron",
            "default_encryption_module": "OC_DEFAULT_MODULE",
            "encryption_enabled": "yes",
            "global_cache_gc_lastrun": "1439756921",
            "installedat": "1411057215.221",
            "lastcron": "1483778643",
            "lastupdateResult": "[]",
            "lastupdatedat": "1483721042",
            "oc.integritycheck.checker": "[]",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "shareapi_allow_group_sharing": "no",
            "shareapi_allow_links": "yes",
            "shareapi_allow_public_notification": "yes",
            "shareapi_allow_public_upload": "no",
            "shareapi_allow_resharing": "no",
            "shareapi_allow_share_dialog_user_enumeration": "no",
            "shareapi_default_expire_date": "yes",
            "shareapi_enabled": "yes",
            "shareapi_enforce_expire_date": "yes",
            "shareapi_enforce_links_password": "yes",
            "updater.secret.created": "1481558007",
            "vendor": "nextcloud"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "filesystem"
        },
        "direct_menu": {
            "enabled": "yes",
            "installed_version": "0.9.2",
            "ocsid": "169148",
            "types": ""
        },
        "documents": {
            "enabled": "no",
            "installed_version": "0.8.2",
            "ocsid": "168711",
            "types": ""
        },
        "encryption": {
            "enabled": "yes",
            "installed_version": "1.3.1",
            "masterKeyId": "master_0fd308d8",
            "publicShareKeyId": "pubShare_7432598f",
            "recoveryKeyId": "recoveryKey_a6e43d46",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": ""
        },
        "federation": {
            "autoAddServers": "0",
            "enabled": "no",
            "installed_version": "0.0.4",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.5.2",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.8.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "no",
            "installed_version": "1.0.0",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "no",
            "installed_version": "0.9.8",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "no",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "15.0.1",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "1.1.5",
            "levels": "00111",
            "ocsid": "170871",
            "types": ""
        },
        "notifications": {
            "enabled": "no",
            "installed_version": "0.2.3",
            "types": "logging"
        },
        "ownbackup": {
            "enabled": "yes",
            "installed_version": "16.11.0",
            "ocsid": "170674",
            "types": ""
        },
        "password_policy": {
            "enabled": "yes",
            "enforceNumericCharacters": "1",
            "enforceUpperLowerCase": "1",
            "installed_version": "1.0.0",
            "minLength": "8",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "no",
            "installed_version": "0.4.1",
            "types": "prevent_group_restriction"
        },
        "search_lucene": {
            "enabled": "no",
            "installed_version": "0.5.3",
            "ocsid": "168709",
            "types": "filesystem"
        },
        "serverinfo": {
            "enabled": "no",
            "installed_version": "1.1.1",
            "types": ""
        },
        "survey_client": {
            "enabled": "no",
            "installed_version": "0.1.5",
            "types": ""
        },
        "systemtags": {
            "enabled": "no",
            "installed_version": "0.2",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.9.3",
            "ocsid": "164356",
            "types": ""
        },
        "templateeditor": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": ""
        },
        "theming": {
            "cachebuster": "3",
            "color": "#004C75",
            "enabled": "yes",
            "installed_version": "1.0.1",
            "logoMime": "image\/gif",
            "types": "logging"
        },
        "updatenotification": {
            "calendar": "1.4.1",
            "contacts": "1.5.0",
            "core": "9.1.2.2",
            "enabled": "yes",
            "installed_version": "1.0.1",
            "ownbackup": "16.11.0",
            "tasks": "0.9.4",
            "types": ""
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        },
        "user_webdavauth": {
            "enabled": "no",
            "installed_version": "1.1.0.2",
            "types": "authentication"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "filesystem"
        }
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
firefox 50.1.0 on linux and win

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
nothing logged
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Uncaught Error: Access to undeclared static property: OC\Files\Filesystem::$normalizedPathCache in /var/www/virtual/web41856.pfweb.eu/mdomann.tk/owncloud/htdocs/lib/private/Files/Filesystem.php:776 Stack trace: #0 /var/www/virtual/web41856.pfweb.eu/mdomann.tk/owncloud/htdocs/lib/private/Files/View.php(2034): OC\Files\Filesystem::normalizePath('/MichaDO/files/...') #1 /var/www/virtual/web41856.pfweb.eu/mdomann.tk/owncloud/htdocs/lib/private/Files/View.php(1152): OC\Files\View->unlockFile('/own/backup/sys...', 1) #2 [internal function]: OC\Files\View->OC\Files\{closure}() #3 /var/www/virtual/web41856.pfweb.eu/mdomann.tk/owncloud/htdocs/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure)) #4 [internal function]: Icewind\Streams\CallbackWrapper->stream_close() #5 {main} thrown at /var/www/virtual/web41856.pfweb.eu/mdomann.tk/owncloud/htdocs/lib/private/Files/Filesystem.php#776
</details>

#### Client log
<details>
<summary>Browser log</summary>
i have created har files from downloads at work and at home which i can send per mail for debug tests.
also i can create a account on my instance to debug.

mdomann@sysiphus:~$ curl -v -u USER:PASS https://tdl.tdl/remote.php/webdav/own/backup/sysiphus/home-20170104.tar.bz2.gpg --output home-20170104.tar.bz2.gpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 79.133.37.107...
* TCP_NODELAY set
* Connected to TDL:TDL (79.133.37.107) port 443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 696 certificates in /etc/ssl/certs
* ALPN, offering h2
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: TDL:TDL (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: CN=TDL:TDL
* 	 start date: Sun, 27 Nov 2016 09:35:00 GMT
* 	 expire date: Sat, 25 Feb 2017 09:35:00 GMT
* 	 issuer: C=US,O=Let's Encrypt,CN=Let's Encrypt Authority X3
* 	 compression: NULL
* ALPN, server did not agree to a protocol
* Server auth using Basic with user 'USER'
> GET /remote.php/webdav/own/backup/sysiphus/home-20170104.tar.bz2.gpg HTTP/1.1
> Host: tdl.tdl
> Authorization: Basic XXXXXXXX User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 04 Jan 2017 19:51:41 GMT
< Server: Apache/2.4.10 (Debian)
< X-Powered-By: PHP/7.0.1
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: Sameorigin
< X-Robots-Tag: none
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< Content-Security-Policy: default-src 'none';
< Content-Disposition: attachment; filename*=UTF-8''home-20170104.tar.bz2.gpg; filename="home-20170104.tar.bz2.gpg"
< OC-ETag: "23c733d4e0bc71de08ddebeacf62200a"
< Set-Cookie: oc_sessionPassphrase=XXXXXX; path=/; secure; HttpOnly
< Set-Cookie: nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
< Set-Cookie: nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
< Set-Cookie: oca2cf00c606=XXXXX; path=/; secure; HttpOnly
< Set-Cookie: cookie_test=test; expires=Wed, 04-Jan-2017 20:51:41 GMT; Max-Age=3600
< Last-Modified: Wed, 04 Jan 2017 06:58:06 GMT
< ETag: "23c733d4e0bc71de08ddebeacf62200a"
< Content-Length: 406796707
< Strict-Transport-Security: max-age=31536000
< Content-Type: application/octet-stream
< 
  0  387M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0{ [6911 bytes data]
 51  387M   51  199M    0     0  1575k      0  0:04:12  0:02:09  0:02:03 1612k* GnuTLS recv error (-110): The TLS connection was non-properly terminated.
* Curl_http_done: called premature == 1
* stopped the pause stream!
 51  387M   51  199M    0     0  1575k      0  0:04:12  0:02:09  0:02:03 1608k
* Closing connection 0
curl: (56) GnuTLS recv error (-110): The TLS connection was non-properly terminated.

https://gist.github.com/Micha-Btz/c1343a0f19e86aee956962f71334f7f5

i have also tried this at home with the newest knoppix same problem and same behaviour from curl.

**Comment by rullzer** [comment]
So this sounds like a timeout issue. Can you verify your `max_execution_time` of php?

**Comment by LukasReschke** [comment]
@Micha-Btz You just posted your username and password in this issue. You may want to change it everywhere you use it. (MichaDO:isb***********)

**Comment by Micha-Btz** [comment]
@LukasReschke stupid thing thanks for mention.
@rullzer max_execution time are 60 but it makes no different if i set it to 259200
maybe i must adjust more than only this variable.

**Comment by juergen963** [comment]
Is there a firewall between you and your nextcloud server?
Try switching it off for a test.

**Comment by Micha-Btz** [comment]
in both cases work and home are no firewall used.

**Comment by chocholik** [comment]
Hello, did someone resolve the problem? Thanks

**Comment by Micha-Btz** [comment]
don't know how the current situation is. will give it a try today.

**Comment by Micha-Btz** [comment]
I can download a file with 310MB without problems. 
I have created a custom .php.ini which seems it solved this.

> upload_max_filesize=2G
> post_max_size=2G
> memory_limit=1024M
> mbstring.func_overload=0
> always_populate_raw_post_data=-1
> default_charset='UTF-8'
> output_buffering=0
> max_execution_time=259200
> max_input_time=300
I'm on NC 11.0.3.
