### ISSUE TITLE
Transfers to the previous directory

### ISSUE THREAD

**Issue by Sevinfolds** [nextcloud/server#29756]
From about version 20 I noticed a problem. Example: we have a directory in which there are many subdirectories with files, and we want to find a specific subdirectory through a search. There are no problems here, we found the directory, we go into it, and after a few seconds it throws it into the general directory.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
