### ISSUE TITLE
[NC 23] l10n: No translation of text strings in "Profile visibility"

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#29768]
No translation for "Profile visibility" in the user settings. The translation of the text strings is in the files l10n.

![obraz](https://user-images.githubusercontent.com/47037905/142428876-646ad113-3d70-4e97-b39f-47e16d03c356.png)

@Pytal please check the code and fix it 😉.

https://github.com/nextcloud/server/blob/2df7ea7daeb4745c7bfc4a12f34480e47eacf9f9/apps/settings/src/constants/AccountPropertyConstants.js#L48-L62

App:
Nextcloud 23.0.0 RC2

**Comment by Pytal** [comment]
It looks like they're in the l10n files already 🤔 https://github.com/nextcloud/server/blob/d42a28cd7ced228545e0f7b77ee60db8ad26d9e1/lib/l10n/de_DE.json#L105

not sure why they aren't translated, any idea @Valdnet?

**Comment by Valdnet** [comment]
Displaying the text string for [Talk](https://github.com/nextcloud/spreed/blob/e9eac83e3e71ab447e986cda5b7e8febe565bbcd/lib/Profile/TalkAction.php#L78-L80) is correct:

![obraz](https://user-images.githubusercontent.com/47037905/143398907-5efb02e6-0ca4-45d0-b50e-6dea954583f7.png)

The problem is in the code above.

**Comment by Valdnet** [comment]
After adding the translation to the `l10n` files in the `core` directory, the text strings are translated in the NC. Turns out what we're seeing is taken from the code for `core`.

![obraz](https://user-images.githubusercontent.com/47037905/143431176-9020997c-34c5-4617-a5cb-f915d782e19d.png)

**Comment by Valdnet** [comment]
@Pytal Part of the text strings are taken from here:

https://github.com/nextcloud/server/blob/d9d54ce782d34656d2e53cb7588fcad80182a1fe/lib/private/Profile/ProfileManager.php#L396-L425

**Comment by Pytal** [comment]
Fix in https://github.com/nextcloud/server/pull/29917
