### ISSUE TITLE
old keynote-files (.key) from 2015 are online shown as folders and not as files

### ISSUE THREAD

**Issue by steinhmor** [nextcloud/server#29767]
### Steps to reproduce
1. find an old keynote-file and sync it with the desktop-client to the server
2. open nextcloud in your browser
3. navigate to the folder where the file is uploaded
4. you can see that the .key file is shown as folder and can be opened

### Expected behaviour
the file should be downloaded

### Actual behaviour
the file is shown as folder and can be opened
![grafik](https://user-images.githubusercontent.com/11630531/142421430-4d0a0f48-9557-4728-b270-6a01a038374f.png)

### Server configuration
SaaS-Nextcloud by Hetzner: NX20 Storageshare https://www.hetzner.com/de/storage/storage-share

**Operating system:**
?

**Web server:**
?

**Database:**
?

**PHP version:**
?

**Nextcloud version:** (see Nextcloud admin page)
22.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
 Accessibility
1.8.0
Activity
2.15.0
Announcement center
6.1.1
Appointments
1.11.2
AppOrder
0.13.0
Approval
1.0.9
Auditing / Logging
1.12.0
Automated PDF conversion
1.7.0
Bookmarks
10.0.2
Brute-force settings
2.2.0
Calendar
2.3.4
Circles
22.1.1
Client Push
0.2.4
Collaborative tags
1.12.0
Collectives
0.15.22
Comments
1.12.0
Community Document Server
0.1.11
Contacts
4.0.6
Contacts Interaction
1.3.0
Dashboard
7.2.0
Deck
1.5.5
Deleted files
1.12.0
Draw.io
1.0.1
Eml Viewer
1.0.0
External sites
3.9.0
Extract
1.3.2
Federation
1.12.0
File access control
1.12.1
File sharing
1.14.0
Files automated tagging
1.12.0
First run wizard
2.11.0
Flow Notifications
1.2.0
Forms
2.4.0
Full text search
22.0.1
Full text search - Files
22.0.1
GitLab integration
1.0.3
Group folders
10.0.0
Impersonate
1.9.0
Jitsi Integration
0.12.0
Link editor
1.1.6
Log Reader
2.7.0
Mail
1.10.5
Maps
0.1.9
Metadata
0.14.0
Monitoring
1.12.0
News
16.2.1
Nextcloud announcements
1.11.0
Notes
4.2.0
Notifications
2.10.1
ONLYOFFICE
7.2.0
Password policy
1.12.0
PDF viewer
2.3.0
Photos
1.4.0
Polls
3.3.0
Privacy
1.6.0
Ransomware protection
1.11.0
Recommendations
1.1.0
Right click
1.1.0
Share by mail
1.12.0
Simple poll for Nextcloud Talk
1.3.1
Social sharing via email
2.4.0
Support
1.5.0
Talk
12.1.2
Talk Matterbridge
1.22.4
Tasks
0.14.2
Text
3.3.0
Theming
1.13.0
Two-Factor TOTP Provider
6.1.0
Update notification
1.12.0
Usage survey
1.10.0
User status
1.2.0
Versions
1.15.0
Video player
1.11.0
Weather status
1.2.0
Whiteboard integration
0.0.14
Workflow external scripts
1.7.0
Workflow OCR
1.22.2

```
</details>

**Nextcloud configuration:**
<details>
no access
</details>

**Are you using external storage, if yes which one:**  no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
Firefox 94.0.1
**Operating system:**
Mac OS 11.6

#### Web server error log
<details>
no access
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
no issue-specific logs
</details>

#### Browser log
<details>
<summary>Browser log</summary>
no issue-specific logs
</details>

**Comment by szaimen** [comment]
Hi, see https://github.com/nextcloud/desktop/issues/1111

**Comment by steinhmor** [comment]
sorry, did not find this issue – but is it realy a sync-client related problem?
my first guess was, that the mimetype-config might be faulty...

**Comment by szaimen** [comment]
Sry, I linked to the wrong issue. Please read the discussion in https://github.com/nextcloud/desktop/issues/1640
