### ISSUE TITLE
Web interface should automatically update when deleting a photos in view mode 

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#29775]
Currently if you open a photo and then hit delete the we will not refresh you have to manually refresh so its removed like below vide. It would be nice to have the web interface automatically update 

https://user-images.githubusercontent.com/59488153/142554941-aca5482b-c999-4f82-adee-e6aea95bb11e.mp4

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/viewer/pull/2620
