### ISSUE TITLE
Accepting Invitations as external user does not work

### ISSUE THREAD

**Issue by jc97** [nextcloud/server#29778]
The option "Restrict users to only share with users in their groups" prevents people (who don't have an account on the nc instance) invited to appointments by email from accepting the invitation. If this option is not enabled, accepting invitations works.

### Steps to reproduce
1. Set 'Restrict users to only share with users in their groups'
2. Create an arbitrary calendar event
3. Invite a person by email using an email address which is not used by any registered user.
4. Open the "accept" button link of the email invitation in another browser or a private browsing tab.

### Expected behaviour
The acceptance of the invitation is processed and stored. 

### Actual behaviour
The invitee gets the error message "Es ist ein Fehler beim Aktualisieren Deines Teilnehmerstatus aufgetreten." (German) which means "An error occurred while updating your attendance status". 

### Calendar app
**Calendar app version:** 2.3.4

**CalDAV-clients used:** None

### Client configuration
**Browser:** Firefox 94.0

**Operating system:** Linux Mint

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.4.25

**Nextcloud Version:** 21.0.6

**List of activated apps:**

```
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - calendar: 2.3.4
  - cloud_federation_api: 1.4.0
  - contacts: 4.0.6
  - dav: 1.17.1
  - external: 3.8.2
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_external: 1.12.0
  - files_pdfviewer: 2.1.1
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - notifications: 2.9.0
  - photos: 1.3.0
  - provisioning_api: 1.11.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - tasks: 0.14.2
  - text: 3.2.0
  - theming: 1.12.0
  - updatenotification: 1.11.0
  - viewer: 1.5.0
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "21.0.6.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "appstore.experimental.enabled": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "logtype": "owncloud",
        "logfile": "***REMOVED SENSITIVE VALUE***",
        "log_rotate_size": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de",
        "allow_user_to_change_display_name": false,
        "enable_avatars": true,
        "check_for_working_webdav": true,
        "check_for_working_htaccess": true,
        "has_internet_connection": true,
        "theme": "",
        "maintenance": false,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enable_previews": true,
        "share_folder": "\/Shared",
        "singleuser": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/",
        "enable_certificate_management": true,
        "updater.release.channel": "stable",
        "integrity.check.disabled": true,
        "filesystem_check_changes": 1,
        "app_install_overwrite": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "default_phone_region": "DE"
    }
}
```

**Comment by jc97** [comment]
Maybe you have some hints where (i.e., in which file / class / component) to fix this issue? I might take a look at it by myself.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
