### ISSUE TITLE
After upgrade PHP5.5.9 to 5.6.29: An exception occured in driver: could not find driver' in /var/www/nextcloud/lib/private/DB/Connection.php

### ISSUE THREAD

**Issue by nodje** [nextcloud/server#2978]
I was running 9.0.50 with php 5.5.9
I wanted to upgrade to latest 11.0.0
I had to upgrade to PHP 5.6.29 to be able to perform the upgrade.

upgrade to 11.0.0 and 10.0.2 failed with exception
`An exception occured in driver: could not find driver' in /var/www/nextcloud/lib/private/DB/Connection.php`

When I reverted my 9.0.50 backup and tried to put it off maintenance mode I got the same exception.

I can't run any occ command anymore.

### Steps to reproduce
1. put in maintenance mode
2. upgrade PHP from 5.5.9 to 5.6.29
3. run any occ command

### Server configuration
**Operating system**:
Ubuntu 14.04 LTS
**Web server:**
Apache2
**Database:**
sqlite3

**List of activated apps:**
calendar, contacts

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => '52046ad573f5f',
  'passwordsalt' => '67449150809cb3e917977e8e8afbae',
  'datadirectory' => '/var/www/nextcloud/data',
  'dbtype' => 'sqlite3',
  'version' => '9.0.50.0',
  'installed' => true,
  'theme' => '',
  'maintenance' => true,
  'forcessl' => true,
  'trusted_domains' =>
  array (
    0 => 'domain.org',
    1 => 'ip.ip.ip,ip',
  ),
  'mail_from_address' => 'xxxx',
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'xxxx',
  'mail_smtppassword' => 'xxxxxxxx',
  'mail_domain' => 'domain.org',
  'secret' => 'xxxxxxxxxxxxxxxxxxxx',
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto',
  'updatechecker' => false,
);
```

**Comment by MorrisJobke** [comment]
> An exception occured in driver: could not find driver' in /var/www/nextcloud/lib/private/DB/Connection.php

This indicates, that the required driver is not installed anymore. Please make sure that the sqlite PHP module is loaded.

I will close this because it is an setup issue. For further questions please open an thread in our forums: https://help.nextcloud.com/
