### ISSUE TITLE
HTTPS-WebDAV mount on Windows failes if NC is installed to webserver-root

### ISSUE THREAD

**Issue by michag86** [nextcloud/server#2979]
### Steps to reproduce
1. Install Nextcloud to the webroot on the webserver
2. Try to mount a webdav folder from nextcloud

### Expected behaviour
The webdav folder should be mounted.

### Actual behaviour
Error 0x80070043 “The network name cannot be found.” occurs

### Server configuration
**Operating system**: CentOS 7
**Web server:** Apache 2.4
**Database:** MySQL
**PHP version:** 5.4
**Nextcloud version:** 10.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:** OC8.2 -> NC 9.0 -> NC 10.0.1
**Where did you install Nextcloud from:** tar from website
**Signing status:** No errors have been found.

### Client configuration
**Operating system:**
Windows 8.1 / Windows 10

### Additional Informations
For ownCloud the problem is discussed here:
https://github.com/owncloud/core/issues/26350
And here are the workarounds documented:
https://doc.owncloud.org/server/latest/admin_manual/issues/general_troubleshooting.html#troubleshooting-webdav
https://doc.owncloud.org/server/latest/user_manual/files/access_webdav.html?highlight=webdav#known-problems

Maybe Windows is not the only client that works this way:
https://www.ibm.com/support/knowledgecenter/SSHRKX_8.0.0/admin/webdav_http_options.html

The Windows Webdav Client Sends an OPTIONS to the root of the URL.
NC redirects to the login form (/index.php/login). The client sends an OPTIONS to this URL und gets 405 Method not allowed because there is no defined route in core/routes.php.

### Possible Solution
If we add a route for / with method OPTIONS that redirects to /remote.php/webdav everything should work fine.

**Comment by MorrisJobke** [comment]
> If we add a route for / with method OPTIONS that redirects to /remote.php/webdav everything should work fine.

This solutions looks more sensible than to document this and let people run into this.

@rullzer @LukasReschke @icewind1991 Opinions on this?

**Comment by rullzer** [comment]
Mmmm I'm not sure. The issue I have with this is that it might lead to people not entering the full url and then running into other issues.

I guess the bigger question is why do they not respect the url provided.

Maybe adding the redirect is the easiest solution...

**Comment by michag86** [comment]
@rullzer OPTIONS on / (or NC root) redirects to remote.php/webdav ?
That would help 😄

**Comment by MorrisJobke** [comment]
https://github.com/nextcloud/server/blob/54f96e5f58d0e5f7239e7274ac239fec807fa206/lib/base.php#L1020-L1028 <- the PROPFIND is handled directly in the `lib/base.php`

**Comment by MorrisJobke** [comment]
@michag86 Could you give https://github.com/nextcloud/server/commit/6f31b73d410c73085b90e1ca7eebd098772120a3 a try?

**Comment by JulienPalard** [comment]
NC 11.01 here, with or without 6f31b73, still got the `Error 0x80070043 “The network name cannot be found.”` on a Windows 8.1 (But works on Debian and MacOS).

**Comment by Flole998** [comment]
Sometimes Windows is a little broken and requests / even though the correct path is specified. When DavClnt is the user agent as it is when using net use to mount a share, it should redirect to the appropriate directory as in my pull request #3370

**Comment by michag86** [comment]
Fixed with #3370
