### ISSUE TITLE
Email sent - Intermittent issue  - DNS request

### ISSUE THREAD

**Issue by MosfetN** [nextcloud/server#29805]
Hello,

I'm facing an intermittent issue while sending emails.
Sometimes test email is sent and sometimes not.
While occuring, the error is :
_A problem occurred while sending the email. Please revise your settings. (Error: Connection could not be established with host mail.protection.outlook.com :stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known Log data: ++ Starting Swift_SmtpTransport !! Connection could not be established with host mail.protection.outlook.com :stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known (code: 0))_

I found that the server is requesting "_mail.protection.outlook.com.mydomain.tld_" via DNS instead of "_mail.protection.outlook.com_"

I don't figure out why server alternatively requests the good record and the wrong one.

Does someone have a clue to fix this please?

**Comment by acsfer** [comment]
If you're using Office365, use `smtp.office365.com` as smtp server address.
Else, please address these questions at the forum in the future. Thanks 👍 

https://help..nextcloud.com

**Comment by MosfetN** [comment]
Hello acsfer,
Thanks for your quick answer.
Unfortunately, I guess I wasn't clear enough with my issue.

I could test with another email serveur and I have the same intermittent DNS request issue.
Here is the dump :
_nextcloud.mydomain.tld.59397 > dns.mydomain.tld.53: 10135+ A? relay.domain.tld. (66)
nextcloud.mydomain.tld.59397 > dns.mydomain.tld.domain: 10135+ A? relay.domain.tld. (66)
dns.mydomain.tld.domain > nextcloud.mydomain.tld.59397: 10135 NXDomain 0/0/0 (66)
nextcloud.mydomain.tld.33244 > dns.mydomain.tld.domain: 15443+ A? relay.domain.tld.mydomain.tld. (85)
dns.mydomain.tld.domain > nextcloud.mydomain.tld.33244: 15443 NXDomain* 0/1/0 (172)_

I my be related to my DNS server which sometimes reply with NXDOMAIN but why is nextcloud requests another pointer with adding "mydomain.tld" ?
