### ISSUE TITLE
WebDAV properties are not shared when sharing files

### ISSUE THREAD

**Issue by michelwilson** [nextcloud/server#29817]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Share a folder with another user
2. Create a file, set a custom WebDAV property on that file
3. As the user that has set the property, the property is returned
4. For any other user, no custom properties are returned!

### Expected behaviour
Properties set on a shared file should also be shared, and visible to everyone

### Some extra notes
Looking at the `oc_properties` table it's clear what happens if you set the same property on the same (shared) file using different users, the `propertypath` is always the users private path to the file, i.e., `files:/username/folder/some_file`. I'd say this could be fixed by always using the username of the user that shared `folder` to compose/access the `propertypath`, but I don't have sufficient knowledge of NextCloud internals to know if this is as simple as it seems :)

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
