### ISSUE TITLE
22.2.3 Jquery and Underscore Versions

### ISSUE THREAD

**Issue by stondino00** [nextcloud/server#29818]
I've just done a nessus scan against my fully upgraded Nextcloud snap install running 22.2.3.  It's showing me this.  Can someone confirm the versions of jquery and underscore.js in nextcloud 22.2.3?

![image](https://user-images.githubusercontent.com/54154986/142729295-2d014fde-b1d2-4abe-8163-98b5d773edc7.png)

**Comment by acsfer** [comment]
See https://github.com/nextcloud/server/issues/17959#issuecomment-554622334 for jQuery and https://github.com/nextcloud/server/pull/27279 for Underscore.
