### ISSUE TITLE
Portainer (Docker) Nextcloud 22 with MariaDB 10.5 - Internal Server Error after restart

### ISSUE THREAD

**Issue by uhsa779** [nextcloud/server#29822]
I had a working Nextcloud 22 running on Portainer with MariaDB. 

I restarted Nextcloud container because I was having issues seeing my Pic folder (which kept complaining it's locked and unavailable) 

Next thing I see is "Internal Server" error. I tried restarted couple times - no change. 

So I restart my MariaDB (10.5) container - didn't help me at all. 

Unfortunately, I am not a pro here so I am unable to "debug" or parse through the logs but if someone can point me in the right direction and tell me what to look for, I can hopefully do that. 

I appreciate the help - currently I am unable to access Nextcloud. 

I know I would probably need to post some log file here 

[nextcloud issues.txt](https://github.com/nextcloud/server/files/7575074/nextcloud.issues.txt)
}

**Comment by ajitesh-sivakumar** [comment]
Hi, I am also facing the same issue.
Firstly, I wasn't able to see apps in '+Apps', so I tried increasing timeouts limits in 3 files. Then, I was able to see apps.

After some time, suddenly Internal Server Error. 

Kindly assist on the same.

**Comment by acsfer** [comment]
You will probably get more help at https://help.nextcloud.com
Use Github for (reproducible) bugs only (with the issues template).

Thanks 👍
