### ISSUE TITLE
Can't open documents from public shares using Collabora online

### ISSUE THREAD

**Issue by Butanal** [nextcloud/server#2983]
### Steps to reproduce
1. Install the latest nextcloud.
2. Add Collabora to nextcloud, installing it using Docker
3. Try to open a document using Collabora online from a publicly shared link

### Expected behaviour
From my research I'm pretty sure that you're suppposed to be able to open documents using Collabora from public shares.

### Actual behaviour
This is where it gets hard. Most of the time I'm not able to access this file, and an "Access forbidden" error gets thrown at me. Thing is, for some folders it does work, and I've not been able to track down what causes these differences.
Only once did I get more details, with the error being completed with a "CSRF check failed".

### Server configuration
**Operating system**: Ubuntu 16.04 LTS running in an HyperV VM with Windows Server 2016.

**Web server:** Apache 2 - 2.4.18-2ubuntu3.1

**Database:** MySQL - 5.7.16-0ubuntu0.16.04.1

**PHP version:** PHP 7.0.8

**Nextcloud version:** 11.0.0 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** Full fresh 11.0.0 install

**Where did you install Nextcloud from:** Classic archive install

**Signing status:** No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - activity: 2.4.1
  - announcementcenter: 3.0.0
  - apporder: 0.3.3
  - calendar: 1.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - external: true
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - richdocuments: 1.1.25
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 0.5.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "ock3f8l0vbal",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.50",
            "example.com"
        ],
        "datadirectory": "\/var\/nextcloud\/",
        "overwrite.cli.url": "http:\/\/192.168.0.50",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true
    }
}

</details>

**Are you using external storage, if yes which one:** None

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Any (tested with latest Google Chrome and Firefox)

**Operating system:** Windows 10 (tested with Home and Enterprise editions)

#### Web server error log
<details>
<summary>Web server error log</summary>
Empty (seems weird to me, but it should be properly configured) as access log is in fact working the same : in my virtualhost I have 
`ErrorLog /var/log/apache2/example.com/error.log`
</details>

#### Nextcloud log (data/nextcloud.log)
Provides no useful information whatsoever to help (I checked, when the error occurs the last edited date isn't changed). 
Should I change to verbose log ?

I know that I am not providing that much information, so please, tell me what info I could add.

**Comment by LukasReschke** [comment]
Reopen at https://github.com/nextcloud/richdocuments
