### ISSUE TITLE
Allow Server admin to change user profile pictures

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/server#29838]
It would be  nice to have an option for server admin to be able to upload and change user profile pictures via the users tab. It would also be nice if the admins can have a setting to turn off users from changing their own password. For example one the admin changes their user profile users can't change it anymore

**Comment by andyxheli** [comment]
@CarlSchwan sorry to bug you. Do you think this should be something that the NC Team would be interested in? I think it would be a really nice addition

**Comment by rawtaz** [comment]
It seems to me that (super) administrators don't have a way in the GUI to edit regular/other users' profile information (e.g. phone number, address, etc). Being able to do this would be pretty expected for an admin I think :) Either way, it kind of goes hand in hand with the profile image request this issue is about.

**Comment by ruedigerkupper** [comment]
Exactly what I am looking for.

**Comment by icarus747** [comment]
I would like to expand on this request.  Enable an API, as well as GUI management, so you can pull images from an external source eg: employee badges, and upload to the corresponding employee #.

**Comment by rawtaz** [comment]
Too bad this was closed. Issues being closed after several years of not being attended in any way does not add to pressuring the Nextcloud company to attend stuff. Quite the contrary it shows them that all they need to do is not look at things, and those things will magically go away by themselves :)
