### ISSUE TITLE
As a administrator (super user) unable to view other users activities.

### ISSUE THREAD

**Issue by iwvworks** [nextcloud/server#29843]
Hi, i have administrator access but when anyone of my user delete files or create folders or make any changes in the file system, i am unable to view. even i marked as super user. Kindly fix this bug or let me know the procedure as this is creating lot of issue.

**Comment by szaimen** [comment]
Hi, you can use this app https://apps.nextcloud.com/apps/impersonate

**Comment by iwvworks** [comment]
Hi its not helpful.

As i said i am super user but still i can't see other user activities.
Please assist on this.

Thank you.

    On Tuesday, 23 November 2021, 06:40:33 pm GMT+8, szaimen ***@***.***> wrote:  
 
 


Hi, you can use this app https://apps.nextcloud.com/apps/impersonate

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kinimodmeyer** [comment]
@iwvworks when users have folders you need to be aware of what happens, then they need to share the folder with you.
in that case you will see all the activities.

or even better: you create the important folders and share them with the user/groups.
