### ISSUE TITLE
Nextcloud 22.2.3 slow

### ISSUE THREAD

**Issue by wwwwiii** [nextcloud/server#29857]
I have installed the update since people we're saying the 22.1 isseu got fixed. But mine 22.2.3 is extreemly slow.
Any hotfixes availible

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by wwwwiii** [comment]
Nevermind fixed it already a collegae of mine made a change on smb shares.They became unavailible, everything became really slow because of that. 
Sry @szaimen
