### ISSUE TITLE
writing notes to an external storage will not work any more

### ISSUE THREAD

**Issue by marcogaida** [nextcloud/server#29860]
Error: fopen(ftp://...@xxx.xxx.xxx.xxx/path/README.md): Failed to open stream: Remote file already exists and overwrite context option not specified&lt;br /&gt; FTP server reports 213 1 at /snap/nextcloud/28654/htdocs/apps/files_external/lib/Lib/Storage/FTP.php#110

The file is created on that storage but without content. everytime i want to write something to it i will get this message:

![grafik](https://user-images.githubusercontent.com/57146698/143039422-23289ff8-3f5f-4634-a89c-cb58a23845a2.png)

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
