### ISSUE TITLE
After upgrading to Nextcloud 22.2.3 , it is not possible to move to message body (when using Rainloop 7.1.2)

### ISSUE THREAD

**Issue by Anonym69** [nextcloud/server#29873]
This problem came with NextCloud 22.2.3 and occurs when using Rainloop 7.1.2 (and to my knowledge, Rainloop has not been updated since NC 22.2.3)

### Steps to reproduce
1.  Compose an email, fill in the email address
2.  Fill in a subject
3.  Place the mouse in the message body
4.  This will not work, it jumps up to the subject line again

### Workaround

1.  Compose an email, fill in the email address
2.  Fill in a subject
3.  Save it as a draft
4.  Exit the draft
5.  Reload the page with SHIFT-F5
6.  Fetch the draft
7.  Go directly to the message window, do NOT place the cursor in the address field or on the subject line
8.  Continue to write the message
9.  Send it

### Expected behaviour

That it worked like it used to before NC 22.2.3. No exiting, just compose it all and send it.

### Actual behaviour

See the "Steps to reproduce"

### Server configuration

**Operating system:**
Debian GNU/Linux 10 (buster)   - (10.11)

**Web server:**
Server version: Apache/2.4.38 (Debian)
Server built:   2021-09-30T03:50:49

**Database:**
mysql  Ver 15.1 Distrib 10.3.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:**
PHP 8.0.13 (cli) (built: Nov 22 2021 09:48:13)

**Nextcloud version:** (see Nextcloud admin page)
22.2.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from release just before

**Where did you install Nextcloud from:**
Command line installation using the OCC

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.


Please see attached file, the rest of this message made the message too long.

[nc-info.txt](https://github.com/nextcloud/server/files/7591996/nc-info.txt)

**Comment by acsfer** [comment]
You should report to https://github.com/pierre-alain-b/rainloop-nextcloud/issues not here.

**Comment by Anonym69** [comment]
This happened after updating to NC 22.2.3, but fine. I will.
