### ISSUE TITLE
Impossible to login while using http basic auth as "admin" on the same domain

### ISSUE THREAD

**Issue by spyjo** [nextcloud/server#29880]
### Steps to reproduce
1. Have Nextcloud hosted on https://some-secure.domain.com/cloud/ with http basic auth enabled for https://some-secure.domain.com/ , with a login "admin" for http basic auth (which is the same login as the Nextcloud admin user, but not the same credentials).
2. Go to https://some-secure.domain.com/cloud/
3. See "Error" directly on the page, not even a login form.

### Expected behaviour
It should show the login form to be able to login.
It was working great before, so I think this problem was introduced "recently" (may be before Nextcloud 22.2.0 ? I'm not sure.)

### Actual behaviour
It shows directly "Error" for a failed login (as seen in the logs) when I'm auth with http basic on the main domain.
Emptying cookies datas does nothing.
Going in private browsing session directly to the /cloud/ folder makes the login works, because in nginx configuration the "/cloud/" has "auth_basic off;" and I'm not authenticated with http basic.

### Server configuration

**Operating system:** Debian 10

**Web server:** Nginx 1.14.2

**Database:** MariaDB 10.5.12

**PHP version:** 7.3.31

**Nextcloud version:** 22.2.3.0 (same problem with previous version 22.2.0)

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** from sources

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contactsinteraction: 1.3.0
  - dav: 1.19.0
  - encryption: 2.10.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - support: 1.5.0
  - systemtags: 1.12.0
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - dashboard
  - files_external
  - survey_client
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "secure.domain.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.3.0",
        "overwrite.cli.url": "https:\/\/secure.domain.com\/cloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "default_phone_region": "FR",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Safari 15.1

**Operating system:** Mac OS 10.15

#### Web server error log
<details>
<summary>Web server error log</summary>

```
82.66.XX.YY - admin [24/Nov/2021:12:11:48 +0100] "GET /cloud/ HTTP/1.1" 401 3872 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"uSAlYf8OfwkyGU6rpMHu","level":2,"time":"2021-11-24T11:11:48+00:00","remoteAddr":"82.66.XX.YY","user":"--","app":"core","method":"GET","url":"/cloud/","message":"Login failed: 'admin' (Remote IP: '82.66.XX.YY')","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.1 Safari/605.1.15","version":"22.2.3.0"}
```
</details>

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
