### ISSUE TITLE
Resources are only pending not "booked"

### ISSUE THREAD

**Issue by jonathanmmm** [nextcloud/server#29899]
Hi,

I am running nextcloud-fpm in docker with nginx (also docker) in front on debian bullseye.

I created a resource with this tool https://github.com/nextcloud/calendar_resource_management

I am assigning the room to a calendar entry and wait but it doesn't get booked (using only webinterface of nextcloud calendar)
Same happens if multiple accounts try to book the same resource, I can't see that the resource was booked.

https://github.com/nextcloud/calendar_resource_management/issues/19
is the original issue

**Comment by ChristophWurst** [comment]
Mind opening a full bug report? https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C+0.+Needs+triage&template=Bug_report.md

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
