### ISSUE TITLE
oc_ldap_group_members remains empty when using MemberUid

### ISSUE THREAD

**Issue by bjo81** [nextcloud/server#2990]
### Steps to reproduce
1. install nextcloud
2. connect it to a LDAP server which uses MemberUid
3. try to use groups

### Expected behaviour
MemberUid is used to map groupmenbers into oc_ldap_group_members

### Actual behaviour
Groups remain empty, the groups have no members

oc_ldap_group_members contains
```
+--------------+---------------+
| owncloudname | owncloudusers |
+--------------+---------------+
| users        | a:0:{}        |
| users_10     | a:0:{}        |
```
etc.

### Server configuration
**Operating system**:
Ubuntu 16.04.1 LTS

**Web server:**
Apache/2.4.18 (Ubuntu)

**Database:**
5.7.16-0ubuntu0.16.04.1 (Ubuntu)

**PHP version:**
7.0.8-0ubuntu0.16.04.3

**Nextcloud version:** (see Nextcloud admin page)
11.0.0 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Where did you install Nextcloud from:**
zip from nextcloud.com

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.1
  - workflowengine: 1.1.1
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oc3j14fwj0lu",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.foo.tld"
        ],
        "datadirectory": "\/data\/www\/allgemein\/nextcloud-data",
        "overwrite.cli.url": "https:\/\/nextcloud..foo.tld",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
}

```
</details>

**Are you using external storage, if yes which one:** 

none

**Are you using encryption:**

none

**Are you using an external user-backend, if yes which one:** 

LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+-------------------------------------------+
| Configuration                 |                                           |
+-------------------------------+-------------------------------------------+
| hasMemberOfFilterSupport      |                                           |
| hasPagedResultSupport         |                                           |
| homeFolderNamingRule          | attr:cn                                   |
| lastJpegPhotoLookup           | 0                                         |
| ldapAgentName                 |                                           |
| ldapAgentPassword             | ***                                       |
| ldapAttributesForGroupSearch  | gidNumber                                 |
| ldapAttributesForUserSearch   | uidNumber                                 |
| ldapBackupHost                |                                           |
| ldapBackupPort                |                                           |
| ldapBase                      | dc=company,dc=net                        |
| ldapBaseGroups                | dc=company,dc=net                        |
| ldapBaseUsers                 | dc=company,dc=net                        |
| ldapCacheTTL                  | 600                                       |
| ldapConfigurationActive       | 1                                         |
| ldapDynamicGroupMemberURL     |                                           |
| ldapEmailAttribute            | mail                                      |
| ldapExperiencedAdmin          | 0                                         |
| ldapExpertUUIDGroupAttr       | gidNumber                                 |
| ldapExpertUUIDUserAttr        | uid                                       |
| ldapExpertUsernameAttr        |                                           |
| ldapGroupDisplayName          | cn                                        |
| ldapGroupFilter               | (&(|(objectclass=zarafa-group)))          |
| ldapGroupFilterGroups         |                                           |
| ldapGroupFilterMode           | 0                                         |
| ldapGroupFilterObjectclass    | zarafa-group                              |
| ldapGroupMemberAssocAttr      | memberUid                                 |
| ldapHost                      | ldaps://ldap.company.net             |
| ldapIgnoreNamingRules         |                                           |
| ldapLoginFilter               | (&(|(objectclass=zarafa-user))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                           |
| ldapLoginFilterEmail          | 0                                         |
| ldapLoginFilterMode           | 0                                         |
| ldapLoginFilterUsername       | 1                                         |
| ldapNestedGroups              | 0                                         |
| ldapOverrideMainServer        |                                           |
| ldapPagingSize                | 0                                         |
| ldapPort                      | 636                                       |
| ldapQuotaAttribute            |                                           |
| ldapQuotaDefault              |                                           |
| ldapTLS                       | 0                                         |
| ldapUserDisplayName           | cn                                        |
| ldapUserDisplayName2          |                                           |
| ldapUserFilter                | (|(objectclass=zarafa-user))              |
| ldapUserFilterGroups          |                                           |
| ldapUserFilterMode            | 0                                         |
| ldapUserFilterObjectclass     | zarafa-user                               |
| ldapUuidGroupAttribute        | auto                                      |
| ldapUuidUserAttribute         | auto                                      |
| turnOffCertCheck              | 0                                         |
| turnOnPasswordChange          | 0                                         |
| useMemberOfToDetectMembership | 1                                         |
+-------------------------------+-------------------------------------------+
```
</details>

### Client configuration
**Browser:**
Firefox 50.1.0

**Operating system:**
Debian 8.6

#### Web server error log
<details>
<summary>Web server error log</summary>
nothing
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"uVOcVYvpcE0diXHT5J1j","remoteAddr":"<some-remote-addr>","app":"core","message":"Error while running background job (class: OCA\\User_LDAP\\Jobs\\UpdateGroups, arguments: ): {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\UniqueConstraintViolationException\",\"Message\":\"An exception occurred while executing '\\n\\t\\t\\tINSERT\\n\\t\\t\\tINTO `oc_ldap_group_members` (`owncloudname`, `owncloudusers`)\\n\\t\\t\\tVALUES (?, ?)\\n\\t\\t' with params [\\\"users_14\\\", \\\"a:0:{}\\\"]:\\n\\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'users_14' for key 'PRIMARY'\",\"Code\":0,\"Trace\":\"#0 \\\/data\\\/www\\\/allgemein\\\/nextcloud.company.net\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/data\\\/www\\\/allgemein\\\/nextcloud.company.net\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(177): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), '\\\\n\\\\t\\\\t\\\\tINSERT\\\\n\\\\t\\\\t\\\\tI...', Array)\\n#2 \\\/data\\\/www\\\/allgemein\\\/nextcloud.company.net\\\/lib\\\/private\\\/legacy\\\/db\\\/statementwrapper.php(74): Doctrine\\\\DBAL\\\\Statement->execute(Array)\\n#3 \\\/data\\\/www\\\/allgemein\\\/nextcloud.company.net\\\/apps\\\/user_ldap\\\/lib\\\/Jobs\\\/UpdateGroups.php(140): OC_DB_StatementWrapper->execute(Array)\\n#4 \\\/data\\\/www\\\/allgemein\\\/nextcloud.company.net\\\/apps\\\/user_ldap\\\/lib\\\/Jobs\\\/UpdateGroups.php(73): OCA\\\\User_LDAP\\\\Jobs\\\\UpdateGroups::handleCreatedGroups(Array)\\n#5 \\\/data\\\/www\\\/allgemein\\\/nextcloud.company.net\\\/apps\\\/user_ldap\\\/lib\\\/Jobs\\\/UpdateGroups.php(56): OCA\\\\User_LDAP\\\\Jobs\\\\UpdateGroups::updateGroups()\\n#6 \\\/data\\\/www\\\/allgemein\\\/nextcloud.company.net\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(53): OCA\\\\User_LDAP\\\\Jobs\\\\UpdateGroups->run(NULL)\\n#7 \\\/data\\\/www\\\/allgemein\\\/nextcloud.company.net\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(54): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#8 \\\/data\\\/www\\\/allgemein\\\/nextcloud.company.net\\\/cron.php(145): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#9 {main}\",\"File\":\"\\\/data\\\/www\\\/allgemein\\\/nextcloud.company.net\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":66}","level":3,"time":"2017-01-09T13:24:47+00:00","method":"GET","url":"\/cron.php","user":"--","version":"11.0.0.10"}
</details>

**Comment by rullzer** [comment]
Summoning our LDAP overload @blizzz

**Comment by blizzz** [comment]
First things first, works for me 😝 

Interesting exception in the Nextcloud log. It is supposed to update this row instead of overwriting it. But it would be empty anyway, looking at the backtrace.

@bjo81 is my understanding correct, that all groups are listed? For example in the users page, or in the oc_ldap_group_mapping table. Also, could you get me an example LDAP record of a group that is supposed contain one or more users?

**Comment by bjo81** [comment]
Yes, your understand is correct. All groups appear in oc_ldap_group_mapping.

Here is an example of a LDAP record:

`dn: cn=cmp-staff,ou=company.net,dc=company,dc=net
cn: cmp-staff
gidNumber: 400
memberUid: 3715
memberUid: 3717
memberUid: 3702
memberUid: 3700
memberUid: 3713
memberUid: 3701
memberUid: 3709
memberUid: 3705
memberUid: 3703
memberUid: 3708
memberUid: 3714
objectClass: posixGroup
objectClass: zarafa-group
`

**Comment by blizzz** [comment]
Looks good so far.

Could you set the log leve to debug, please? Subsequently, could you place [this script](https://gist.github.com/blizzz/736339dc4938a920e087) into your Nextcloud root folder and execute it with

``sudo -u www-data php getUserGroupMemberships.php  3715 cmp-staff``

and provide the output? And also what was logged during this request. Afterwards you can remove the script.

Expected output is like:

```
$ suww php getUserGroupMemberships.php user_5 group_5
[sudo] password for blizzz: 
Nicholls, Nora is member of following groups:
group_5

group_5 has following members:
Browne, Candice (user_4)
Nicholls, Nora (user_5)
Gallagher, Kelli (user_32)
Bennett, Veronica (user_36)
Allen, Vivian (user_44)
Dean, Becky (user_59) 
```

**Comment by bjo81** [comment]
Loglevel is already at 0 (debug).

Output of the script is "Invalid UserID" and the log during the request:

> {"reqId":"8fMY0m51Nr1Qc3CyVxrw","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\APCu not available for local cache","level":1,"time":"2017-01-11T19:49:25+00:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
> {"reqId":"8fMY0m51Nr1Qc3CyVxrw","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\APCu not available for distributed cache","level":1,"time":"2017-01-11T19:49:25+00:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
> {"reqId":"8fMY0m51Nr1Qc3CyVxrw","remoteAddr":"","app":"user_ldap","message":"No DN found for 3715 on ldaps:\/\/ldap.company.net","level":0,"time":"2017-01-11T19:49:25+00:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
>

**Comment by blizzz** [comment]
> Output of the script is "Invalid UserID" and the log during the request:

That's interesting. This is the first uid referenced in your output from https://github.com/nextcloud/server/issues/2990#issuecomment-271824600

With the LDAP settings this is also expected to be the internal username for this user. Unless, he was mapped before the UUID attribute was changed.

Can you look this user up in the oc_ldap_user_mapping table? And try again with the value found in the owncloud_name column?

**Comment by bjo81** [comment]
Our uids contain something like "john", for instance:

> dn: uid=john,cn=users,ou=company.net,dc=company,dc=net
> givenName: John
> mail: doe@company.net
> sn: Doe
> cn: John Doe
> gidNumber: 300
> homeDirectory: none
> uid: john
> uidNumber: 3717
> objectClass: inetOrgPerson
> objectClass: person
> objectClass: posixAccount
> objectClass: zarafa-user

Searching for john with the script:

> John Doe is member of following groups:
> (none)
> 
> cmp-staff has following members:
> (none)

So should I set "UUID Attribute for Users" to uidNumber?

**Comment by blizzz** [comment]
Ah, now we got the thing.

memberUid is supposed to link to the uid of the user record, but in your case it references the uidNumber. that's why it doesn't work.

At least that's how we expect it and e.g. openldap does it. didn't verify with RFC though (on mobile right now). Also right now I don't have an idea about a workaround unfortunately.

**Comment by blizzz** [comment]
@bjo81 which LDAP server are you using?

**Comment by bjo81** [comment]
We are using OpenLDAP and use it among others for Zarafa which expects the uidNumber as MemberUid.

**Comment by blizzz** [comment]
Well, it can be configured, and if you don't use posixAccount objectclass you don't have this attribute. In their doc they talk generically about a "unique user attribute", and the doc gives uid as a config example (i.e. it'S configurable).  https://documentation.zarafa.com/zcp_administrator_manual/configure_zcp_components.html#group-configuration

Well, this does not help however, probably.

What would help you would avoid the hardcoding of the uid attribute and introduce another setting (perhaps cli only) to override the default. Essentially you'd need to replace ``uid`` with ``uidNumber`` within ``apps/user_ldap/lib/Group_LDAP.php::getUserGroups()``. There's also a place where we reuse the LoginFilter to get the users from within a group, and this is essentially why the group members cannot be identified. Adding uidNumber as possible login attribute to the filter should solve  that, too.

**Comment by bjo81** [comment]
Thanks for the hint to the Zarafa documentation, but I think it would be difficult to change it in our setup, due to it is really huge. Introducing another setting for making the DN configurable would be great.

I've replaced now uid with uidNumber in getUserGroups and add uidNumber as a search attribute. 

Some user users have groups now in the users overview, but the groups themselves remain empty as also  oc_ldap_group_members.

**Comment by blizzz** [comment]
> uidNumber as a search attribute.

you'd need to add it as **login** attribute.

> Some user users have groups now in the users overview, but the groups themselves remain empty as also oc_ldap_group_members.

This is filled and updated by a background job. It can take a bit until  you see there changes (if everything else works).

**Comment by bjo81** [comment]
Ok, I added uidNumber as login attribute and will look later if the groups get updated.

**Comment by bjo81** [comment]
I've tried getUserGroupMemberships again now and get the following result:

> sudo -u www-data php getUserGroupMemberships.php 3715  cmp-staff
> John Doe is member of following groups:
> cmp-staff
> workers
> miners
> 
> cmp-staff has following members:
> (none)
>

**Comment by bjo81** [comment]
After talking to a colleague we will use uniqueMember additionally or  a Dynamic Group
Member URL.
