### ISSUE TITLE
Critical changes for developers & admins for Nextcloud 24

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#29914]
Continuation of #27846

# Front-end

* …

# Backend

* Support for PHP7.3 removed: #29286
* Support for PHP8.1 added: #29432 #29862
* Database tables of apps that support Oracle are now required to have a primary key (this is necessary to be able to scale in database clusters also for Postgres and MySQL/MariaDB, but we assume scaling apps also support Oracle): #31513 #31580
* Database columns of apps that support Oracle can not be longer than 4k characters #31679 

## Removed from public namespace:

* …

## Removed from private namespace:

* `OC\Authentication\Token\DefaultToken`
* `OC\Authentication\Token\DefaultTokenCleanupJob`
* `OC\Authentication\Token\DefaultTokenMapper`
* `OC\Authentication\Token\DefaultTokenProvider`

## Deprecations

* ``\OCP\AppFramework\Db\Entity::slugify`` https://github.com/nextcloud/server/pull/30259

### Deprecations of Events & Hooks

* …

## Behavorial changes

* Avatars are only available in 64 and 512 pixels: https://github.com/nextcloud/server/pull/31010
* default right-click options get hidden on public pages: https://github.com/nextcloud/server/pull/31372

## Changes for admins
* Config setting ``config_is_read_only`` prevents Nextcloud from writing to the config file https://github.com/nextcloud/server/pull/30130

**Comment by nickvergessen** [comment]
Added:

> ## Behavorial changes
> 
> * Avatars are only available in 64 and 512 pixels: https://github.com/nextcloud/server/pull/31010

**Comment by nickvergessen** [comment]
Added:

> # Backend
> 
> * Database tables of apps that support Oracle are now required to have a primary key (this is necessary to be able to scale in database clusters): #31513 #31580

**Comment by nickvergessen** [comment]
Added

> ## Backend
> * Database columns of apps that support Oracle can not be longer than 4k characters #31679

**Comment by nickvergessen** [comment]
25 list in https://github.com/nextcloud/server/issues/32117

**Comment by matiasdelellis** [comment]
Hi everyone,
I maintain two applications, and one depends heavily on jQuery.

That is https://github.com/matiasdelellis/quicknotes and now stopped working in NC24, but I can't find any relevant changes that refer to something related.

```
Uncaught ReferenceError: jQuery is not defined
    <anonymous> https://delellis.com.ar/apps/quicknotes/vendor/colorPick.js?v=30f1e4c7-79:173
colorPick.js:173:1
```

Of course I am aware of the deprecation warnings for several versions, but it does not seem that you finally remove it.. 🤔 
My first attempt is to add jquery to my own installation, but the result is exactly the same. I don't have enough time to port it to VUE, and working with vanilla will still be an important job, but first I need to know what changed in NC24

Please, any help is welcome..

**Comment by nickvergessen** [comment]
25 continuation in https://github.com/nextcloud/server/issues/32117
