### ISSUE TITLE
User_LDAP/Jobs/CleanUp not deleting users datas

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/server#29927]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.Remove ldap user in your LDAP
2. verify task execution ( in oc_jobs)

### Expected behaviour
Delete user and datas

### Actual behaviour
User is only marked as remnant

### Server configuration

**Operating system:** debian 10

**Web server:** apache2

**Database:** mariadb

**PHP version:** 7.4

**Nextcloud version:**  20/21/22

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Comment by kesselb** [comment]
https://docs.nextcloud.com/server/stable/admin_manual/configuration_user/user_auth_ldap_cleanup.html
