### ISSUE TITLE
Down push-notifications.nextcloud.com

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#29946]
https://push-notifications.nextcloud.com/notifications seems to be down. 

GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 30001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://push-notifications.nextcloud.com/notifications

{"reqId":"VrP9F1ZEcnIkglstz8SA","level":3,"time":"2021-11-29T01:05:59+00:00","remoteAddr":"172.58.141.49","user":"admin","app":"notifications","method":"POST","url":"/ocs/v2.php/apps/spreed/api/v4/call/rtigoini","message":"cURL error 28: Connection timed out after 30001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://push-notifications.nextcloud.com/notifications","userAgent":"Mozilla/5.0 (iOS) Nextcloud-Talk v12.4.0","version":"22.2.3.0","exception":{"Exception":"GuzzleHttp\\Exception\\ConnectException","Message":"cURL error 28: Connection timed out after 30001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://push-notifications.nextcloud.com/notifications","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","line":158,"function":"createRejection","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","line":110,"function":"finishError","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php","line":47,"function":"finish","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::"},{"file":"/var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php","line":113,"function":"__invoke","class":"GuzzleHttp\\Handler\\CurlHandler","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php","line":64,"function":"OC\\Http\\Client\\{closure}","class":"OC\\Http\\Client\\DnsPinMiddleware","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":31,"function":"__invoke","class":"GuzzleHttp\\PrepareBodyMiddleware","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php","line":71,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":63,"function":"__invoke","class":"GuzzleHttp\\RedirectMiddleware","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php","line":75,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":331,"function":"__invoke","class":"GuzzleHttp\\HandlerStack","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":168,"function":"transfer","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":187,"function":"requestAsync","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/nextcloud/lib/private/Http/Client/Client.php","line":294,"function":"request","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/nextcloud/apps/notifications/lib/Push.php","line":303,"function":"post","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/var/www/nextcloud/apps/notifications/lib/Push.php","line":124,"function":"sendNotificationsToProxies","class":"OCA\\Notifications\\Push","type":"->"},{"file":"/var/www/nextcloud/apps/notifications/lib/App.php","line":90,"function":"flushPayloads","class":"OCA\\Notifications\\Push","type":"->"},{"file":"/var/www/nextcloud/lib/private/Notification/Manager.php","line":360,"function":"markProcessed","class":"OCA\\Notifications\\App","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/Notification/Listener.php","line":286,"function":"markProcessed","class":"OC\\Notification\\Manager","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/Notification/Listener.php","line":109,"function":"markCallNotificationsRead","class":"OCA\\Talk\\Notification\\Listener","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"OCA\\Talk\\Notification\\{closure}","class":"OCA\\Talk\\Notification\\Listener","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":88,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/Service/ParticipantService.php","line":768,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/apps/spreed/lib/Controller/CallController.php","line":124,"function":"changeInCall","class":"OCA\\Talk\\Service\\ParticipantService","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"joinCall","class":"OCA\\Talk\\Controller\\CallController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":156,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":62,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":23,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","Line":210,"CustomMessage":"cURL error 28: Connection timed out after 30001 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://push-notifications.nextcloud.com/notifications"},"id":"61a4410c86148"}

**Comment by acsfer** [comment]
Wait for it to be back up again. 🥱 

This PR will help keeping it up https://github.com/nextcloud/server/pull/29363 and maybe Nextcloud, someday, releases the code to build you own server on https://github.com/nextcloud/notifications/issues/82

**Comment by andyxheli** [comment]
@acsfer thank you!! It would be really nice if we can have our own push notifications server
