### ISSUE TITLE
S3 external storage broken for buckets without versioning support

### ISSUE THREAD

**Issue by bernhara** [nextcloud/server#29949]
Im using a Minio S3 server in *NAS* mode (=> no replication, no version, ...).

The upgrade from 22.2.0 to 22.0.3 has broken my configuration.

The S3 API responds to the GetBucketVersionning request (ie. <s3 url>/<bucket>?versioning" with a code **501: Not implemented**.

This case is no more handled by the AmazonS3.php file of NextCloud. A global exception is raised and the file browsing from NextCloud GUI becomes impossible.

As a temporary workaround, I changed locally the code of apps/files_external/lib/Lib/Storage/AmazonS3.php that way

        /** !!!!!!!private $versioningEnabled = null; **/
        private $versioningEnabled = false;

**Comment by bernhara** [comment]
Still broken in 23.0.0.

**Comment by dabo-devconsole** [comment]
I would like to see this as an optional flag (like legacy authentication). There are more providers, which do not implement this feature.

**Comment by bernhara** [comment]
My feeling is that we are more facing an implementation bug rather than a missing option. And I was unable to understand if the bug is part of the Amazon S3 library used by NextCloud, or if it is in the NextCloud code itself.

Since you have the ability to declare a Bucket without the versioning functionality activated, the NextCloud client code seems to be OK for me: if the functionality is activated on the bucket, NextCloud uses it.

The fact that an exception is raised with the 501 HTTP to say that the versioning functionality is not activated, instead of a normal "boolean" return of a function call is the real source of the problem.

So the easy solution would be to catch that exception to be able to return a "False". But this may hide the real source of the problem.

I was also about to check if the implementation of min.io was correct for that case...

However, your "option" proposal is an easy way to work around this problem. Since the "versioning" functionality is automatically discovered by NextCloud, I would suggest to call this option something like "force NextCloud versioning disabling".

**Comment by bernhara** [comment]
This is exactly what I did :-)

**Comment by JameZUK** [comment]
Great minds and all that :) Here is a diff patch too:
```
--- AmazonS3.php        2022-02-14 15:10:20.927334149 +0000
+++ ./apps/files_external/lib/Lib/Storage/AmazonS3.php  2022-02-14 15:01:28.127564776 +0000
@@ -732,8 +732,9 @@
                if ($this->versioningEnabled === null) {
                        $cached = $this->memCache->get('versioning-enabled::' . $this->getBucket());
                        if ($cached === null) {
-                               $result = $this->getConnection()->getBucketVersioning(['Bucket' => $this->getBucket()]);
-                               $this->versioningEnabled = $result->get('Status') === 'Enabled';
+                               //$result = $this->getConnection()->getBucketVersioning(['Bucket' => $this->getBucket()]);
+                               #$this->versioningEnabled = $result->get('Status') === 'Enabled';
+                               $this->versioningEnabled = False;
                                $this->memCache->set('versioning-enabled::' . $this->getBucket(), $this->versioningEnabled, 60);
                        } else {
                                $this->versioningEnabled = $cached;
```

**Comment by bernhara** [comment]
Great news: I updated my NextCloud **AND** S3 Minio installation and everything is working as previously without patching.

The _gateway_ functionality of S3 Minio has been deprecated and the standard Minio launched by "server /data" (ie. without cache nor replication) seem to do the same job.

The real good news is that the "versioningEnabled  request" coming from NextCloud does not fail anymore.

**Comment by kesselb** [comment]
Fixed by https://github.com/nextcloud/server/pull/31498
