### ISSUE TITLE
Preview of Office document is again not possible

### ISSUE THREAD

**Issue by StefCGN** [nextcloud/server#29956]
Hi,
after upgrading to Nextcloud 22.2.3 - there is again the problem, that no office preview is created.

Following errors are appearing:
<html><body>

Error | core | ImagickException: unable to open image '/tmp//Address.png': No such file or directory @ error/blob.c/OpenBlob/3533
-- | -- | --

</body>
</html>
<html><body>

Error | PHP | Error: unlink(/tmp//Address.png): No such file or directory at /usr/local/www/nextcloud/lib/private/Preview/Office.php#66
-- | -- | --

</body>
</html>

Seems, that the instance-id or the folder is not returned properly.

**Comment by mejo-** [comment]
Nextcloud 23 contains PR #26531, which fixes preview generation for office files. The relevant change is [this oneliner](https://github.com/nextcloud/server/pull/26531/files#diff-62fb6666c02b6513b84dd18703e4f0d9c45ec74f96fa98612704344d1b024b51L77-R87).

To those who suffer from this bug on Nextcloud 22, could you try patching `lib/private/Preview/Office.php` the following way and report back whether it fixes the issue for you:

```diff
index fef218823e..50c016737e 100644
--- a/lib/private/Preview/Office.php
+++ b/lib/private/Preview/Office.php
@@ -74,7 +74,7 @@ abstract class Office extends ProviderV2 {
                }
 
                $image = new \OC_Image();
-               $image->loadFromData($png);
+               $image->loadFromData((string) $png);
 
                $this->cleanTmpFiles();
                unlink($pngPreview);
```
