### ISSUE TITLE
Save VEVENT CATEGORIES as vcategory

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/server#29950]
Currently only files tags are saved into `vcategory` and `vcategory_to_object`. We should extract `CATEGORIES` from `VEVENT`s when saving/updating an event and insert them here.

Then they can be queried by the calendar app through DAV's TagsPlugin (or OCS ?), in order to be suggested in the calendar app.

**Comment by rotdrop** [comment]
Hi there,

I am in the progress to give the calendar app at least the possibility to let the admin define further default categories.

Now concering this open issue: my impression is that neither vcategory nor vcategory_to_object is used for anything at the moment. The initial comment at the top of this issue states that file-categories are saved in these tables. But that does not seem to be the case. At least the "collaborative" tags seemingly do not affect these two left-over database table.

Could perhaps someone with more insight in the code clarify if these two category tables are anywhere used? In my NC instances those tables only have some leftover categories related to calendar events, but nothing relating to files.

**Comment by rotdrop** [comment]
The table `oc_calendarobjects_props` also already stores categories, so `vcategory_to_object` would be redundant.

**Comment by SebastianKrupinski** [comment]
Fixed with https://github.com/nextcloud/calendar/pull/5161
