### ISSUE TITLE
Dry-run with SQL commands for occ db:add-* commands

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#29959]
### How to use GitHub

**Is your feature request related to a problem? Please describe.**
With bigger databases running "occ db:add-*" commands that add indices, columns, etc might take longer than expected and cause disruptions of service.

Admins might want to run those commands in advance.
This would also apply for clustered databases where an admin might run the commands only on a single node while bringing it offline, then back online.

**Describe the solution you'd like**
Add an option like "--show-sql" that will display the SQL commands that would be run but doesn't run them.

**Comment by rtt-mmk** [comment]
This would be a nice enhancement for huge already running instances.
