### ISSUE TITLE
Table 'oc_appconfig' is read only when upgrade to 22.2.2 to 22.2.3

### ISSUE THREAD

**Issue by Bulliby** [nextcloud/server#29971]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.Version 22.2.2
2.Upgrade to version 2.2.3

### Expected behaviour
A successful upgrade

### Actual behavior
Actually the server is in maintenance mode and fail with the following error :

`Table 'oc_appconfig' is read only"`

### Server configuration

**Operating system:**
Archlinux

**Web server:**
Nginx

**Database:**
Mysql

**PHP version:**
PHP 8.0.13

**Nextcloud version:** (see Nextcloud admin page)
version 2.2.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgrade to version 2.2.3

**Where did you install Nextcloud from:**
Nextcloud from official archlinux package

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{
    "system": {
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "config_is_read_only": true,
        "apps_paths": [
            {
                "path": "\/usr\/share\/webapps\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/lib\/nextcloud\/apps",
                "url": "\/wapps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "dbtype": "mysql",
        "version": "22.2.2.0",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "logtimezone": "Europe\/Paris"
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.15.0",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "100"
        },
        "circles": {
            "enabled": "yes",
            "installed_version": "22.1.1",
            "loopback_tmp_scheme": "http",
            "maintenance_run": "0",
            "maintenance_update": "{\"maximum\":3,\"3\":1636811528,\"2\":1636811528,\"1\":1636811528}",
            "migration_22": "1",
            "migration_22_1": "1",
            "migration_run": "0",
            "types": "filesystem,dav"
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "logging"
        },
        "contactsinteraction": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "dav"
        },
        "core": {
            "installedat": "1617911141.2203",
            "lastcron": "1637980418",
            "lastupdateResult": "{\"version\":\"22.2.2.0\",\"versionstring\":\"Nextcloud 22.2.2\",\"url\":\"https:\\\/\\\/download.nextcloud.com\\\/server\\\/releases\\\/nextcloud-22.2.2.zip\",\"web\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/22\\\/admin_manual\\\/maintenance\\\/upgrade.html\",\"changes\":\"https:\\\/\\\/updates.nextcloud.com\\\/changelog_server\\\/?version=22.2.2\",\"autoupdater\":\"1\",\"eol\":\"0\"}",
            "lastupdatedat": "0",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "theming.variables": "d41d8cd98f00b204e9800998ecf8427e",
            "vendor": "nextcloud"
        },
        "dashboard": {
            "enabled": "yes",
            "installed_version": "7.2.0",
            "types": ""
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "installed_version": "1.19.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "authentication"
        },
        "files": {
            "enabled": "yes",
            "installed_version": "1.17.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "2.3.1",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.11.0",
            "types": "logging"
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.7.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.10.1",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "enforceHaveIBeenPwned": "1",
            "enforceNumericCharacters": "0",
            "enforceSpecialCharacters": "0",
            "enforceUpperLowerCase": "1",
            "historySize": "0",
            "installed_version": "1.12.0",
            "maximumLoginAttempts": "3",
            "minLength": "10",
            "types": "authentication"
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "prevent_group_restriction"
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "serverinfo": {
            "cached_count_filecache": "719",
            "cached_count_storages": "2",
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "filesystem"
        },
        "support": {
            "SwitchUpdaterServerHasRun": "yes",
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "logging"
        },
        "text": {
            "enabled": "yes",
            "installed_version": "3.3.0",
            "types": "dav"
        },
        "theming": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": ""
        },
        "updatenotification": {
            "core": "22.2.2.0",
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "",
            "update_check_errors": "0"
        },
        "user_status": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "weather_status": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.4.0",
            "types": "filesystem"
        }
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
TLS

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```

{
  "reqId": "vqXIaKFZ9jCpSLsZNlW6",
  "level": 3,
  "time": "2021-11-28T21:22:18+01:00",
  "remoteAddr": "********",
  "user": "--",
  "app": "no app in context",
  "method": "GET",
  "url": "/core/ajax/update.php?requesttoken=x0196wEas%2Bjmu%2BuWC4YoUtaq3tZOfjuWYiEBBDo9OPg%3D%3AnyEVhVV00LuNzt3ZfNQYNJrmk7cgBnn4MFYxUgwND4A%3D",
  "message": "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1036 Table 'oc_appconfig' is read only",
  "userAgent": "Mozilla/5.0 (Android 8.0.0; Mobile; rv:94.0) Gecko/94.0 Firefox/94.0",
  "version": "22.2.2.0",
  "exception": {
    "Exception": "Doctrine\\DBAL\\Exception\\DriverException",
    "Message": "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1036 Table 'oc_appconfig' is read only",
    "Code": 1036,
    "Trace": [
      {
        "file": "/usr/share/webapps/nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
        "line": 1780,
        "function": "convert",
        "class": "Doctrine\\DBAL\\Driver\\API\\MySQL\\ExceptionConverter",
        "type": "->"
      },
      {
        "file": "/usr/share/webapps/nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
        "line": 1719,
        "function": "handleDriverException",
        "class": "Doctrine\\DBAL\\Connection",
        "type": "->"
      },
      {
        "file": "/usr/share/webapps/nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
        "line": 1173,
        "function": "convertExceptionDuringQuery",
        "class": "Doctrine\\DBAL\\Connection",
        "type": "->"
      },
      {
        "file": "/usr/share/webapps/nextcloud/lib/private/DB/Connection.php",
        "line": 267,
        "function": "executeStatement",
        "class": "Doctrine\\DBAL\\Connection",
        "type": "->"
      },
      {
        "file": "/usr/share/webapps/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php",
        "line": 354,
        "function": "executeStatement",
        "class": "OC\\DB\\Connection",
        "type": "->"
      },
      {
        "file": "/usr/share/webapps/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php",
        "line": 287,
        "function": "execute",
        "class": "Doctrine\\DBAL\\Query\\QueryBuilder",
        "type": "->"
      },
      {
        "file": "/usr/share/webapps/nextcloud/lib/private/AppConfig.php",
        "line": 258,
        "function": "execute",
        "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
        "type": "->"
      },
      {
        "file": "/usr/share/webapps/nextcloud/lib/private/AllConfig.php",
        "line": 231,
        "function": "deleteKey",
        "class": "OC\\AppConfig",
        "type": "->"
      },
      {
        "file": "/usr/share/webapps/nextcloud/lib/private/IntegrityCheck/Checker.php",
        "line": 474,
        "function": "deleteAppValue",
        "class": "OC\\AllConfig",
        "type": "->"
      },
      {
        "file": "/usr/share/webapps/nextcloud/lib/private/IntegrityCheck/Checker.php",
        "line": 590,
        "function": "cleanResults",
        "class": "OC\\IntegrityCheck\\Checker",
        "type": "->"
      },
      {
        "file": "/usr/share/webapps/nextcloud/lib/private/Updater.php",
        "line": 300,
        "function": "runInstanceVerification",
        "class": "OC\\IntegrityCheck\\Checker",
        "type": "->"
      },
      {
        "file": "/usr/share/webapps/nextcloud/lib/private/Updater.php",
        "line": 132,
        "function": "doUpgrade",
        "class": "OC\\Updater",
        "type": "->"
      },
      {
        "file": "/usr/share/webapps/nextcloud/core/ajax/update.php",
        "line": 200,
        "function": "upgrade",
        "class": "OC\\Updater",
        "type": "->"
      }
    ],
    "File": "/usr/share/webapps/nextcloud/3rdparty/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php",
    "Line": 114,
    "Previous": {
      "Exception": "Doctrine\\DBAL\\Driver\\PDO\\Exception",
      "Message": "SQLSTATE[HY000]: General error: 1036 Table 'oc_appconfig' is read only",
      "Code": 1036,
      "Trace": [
        {
          "file": "/usr/share/webapps/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php",
          "line": 94,
          "function": "new",
          "class": "Doctrine\\DBAL\\Driver\\PDO\\Exception",
          "type": "::"
        },
        {
          "file": "/usr/share/webapps/nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
          "line": 1165,
          "function": "execute",
          "class": "Doctrine\\DBAL\\Driver\\PDO\\Statement",
          "type": "->"
        },
        {
          "file": "/usr/share/webapps/nextcloud/lib/private/DB/Connection.php",
          "line": 267,
          "function": "executeStatement",
          "class": "Doctrine\\DBAL\\Connection",
          "type": "->"
        },
        {
          "file": "/usr/share/webapps/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php",
          "line": 354,
          "function": "executeStatement",
          "class": "OC\\DB\\Connection",
          "type": "->"
        },
        {
          "file": "/usr/share/webapps/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php",
          "line": 287,
          "function": "execute",
          "class": "Doctrine\\DBAL\\Query\\QueryBuilder",
          "type": "->"
        },
        {
          "file": "/usr/share/webapps/nextcloud/lib/private/AppConfig.php",
          "line": 258,
          "function": "execute",
          "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
          "type": "->"
        },
        {
          "file": "/usr/share/webapps/nextcloud/lib/private/AllConfig.php",
          "line": 231,
          "function": "deleteKey",
          "class": "OC\\AppConfig",
          "type": "->"
        },
        {
          "file": "/usr/share/webapps/nextcloud/lib/private/IntegrityCheck/Checker.php",
          "line": 474,
          "function": "deleteAppValue",
          "class": "OC\\AllConfig",
          "type": "->"
        },
        {
          "file": "/usr/share/webapps/nextcloud/lib/private/IntegrityCheck/Checker.php",
          "line": 590,
          "function": "cleanResults",
          "class": "OC\\IntegrityCheck\\Checker",
          "type": "->"
        },
        {
          "file": "/usr/share/webapps/nextcloud/lib/private/Updater.php",
          "line": 300,
          "function": "runInstanceVerification",
          "class": "OC\\IntegrityCheck\\Checker",
          "type": "->"
        },
        {
          "file": "/usr/share/webapps/nextcloud/lib/private/Updater.php",
          "line": 132,
          "function": "doUpgrade",
          "class": "OC\\Updater",
          "type": "->"
        },
        {
          "file": "/usr/share/webapps/nextcloud/core/ajax/update.php",
          "line": 200,
          "function": "upgrade",
          "class": "OC\\Updater",
          "type": "->"
        }
      ],
      "File": "/usr/share/webapps/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php",
      "Line": 26,
      "Previous": {
        "Exception": "PDOException",
        "Message": "SQLSTATE[HY000]: General error: 1036 Table 'oc_appconfig' is read only",
        "Code": "HY000",
        "Trace": [
          {
            "file": "/usr/share/webapps/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php",
            "line": 92,
            "function": "execute",
            "class": "PDOStatement",
            "type": "->"
          },
          {
            "file": "/usr/share/webapps/nextcloud/3rdparty/doctrine/dbal/src/Connection.php",
            "line": 1165,
            "function": "execute",
            "class": "Doctrine\\DBAL\\Driver\\PDO\\Statement",
            "type": "->"
          },
          {
            "file": "/usr/share/webapps/nextcloud/lib/private/DB/Connection.php",
            "line": 267,
            "function": "executeStatement",
            "class": "Doctrine\\DBAL\\Connection",
            "type": "->"
          },
          {
            "file": "/usr/share/webapps/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php",
            "line": 354,
            "function": "executeStatement",
            "class": "OC\\DB\\Connection",
            "type": "->"
          },
          {
            "file": "/usr/share/webapps/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php",
            "line": 287,
            "function": "execute",
            "class": "Doctrine\\DBAL\\Query\\QueryBuilder",
            "type": "->"
          },
          {
            "file": "/usr/share/webapps/nextcloud/lib/private/AppConfig.php",
            "line": 258,
            "function": "execute",
            "class": "OC\\DB\\QueryBuilder\\QueryBuilder",
            "type": "->"
          },
          {
            "file": "/usr/share/webapps/nextcloud/lib/private/AllConfig.php",
            "line": 231,
            "function": "deleteKey",
            "class": "OC\\AppConfig",
            "type": "->"
          },
          {
            "file": "/usr/share/webapps/nextcloud/lib/private/IntegrityCheck/Checker.php",
            "line": 474,
            "function": "deleteAppValue",
            "class": "OC\\AllConfig",
            "type": "->"
          },
          {
            "file": "/usr/share/webapps/nextcloud/lib/private/IntegrityCheck/Checker.php",
            "line": 590,
            "function": "cleanResults",
            "class": "OC\\IntegrityCheck\\Checker",
            "type": "->"
          },
          {
            "file": "/usr/share/webapps/nextcloud/lib/private/Updater.php",
            "line": 300,
            "function": "runInstanceVerification",
            "class": "OC\\IntegrityCheck\\Checker",
            "type": "->"
          },
          {
            "file": "/usr/share/webapps/nextcloud/lib/private/Updater.php",
            "line": 132,
            "function": "doUpgrade",
            "class": "OC\\Updater",
            "type": "->"
          },
          {
            "file": "/usr/share/webapps/nextcloud/core/ajax/update.php",
            "line": 200,
            "function": "upgrade",
            "class": "OC\\Updater",
            "type": "->"
          }
        ],
        "File": "/usr/share/webapps/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php",
        "Line": 92
      }
    },
    "CustomMessage": "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1036 Table 'oc_appconfig' is read only"
  }
}
```
</details>

**Comment by acsfer** [comment]
Generally is not the application that modify the tables readability; please Google for "[Table is read only](https://www.google.com/search?q=Table+is+read+only)" if it helps.

**Comment by Bulliby** [comment]
Hello Thx for your reply. In fact it's Mariadb update to[10.6.0](https://mariadb.com/kb/en/mariadb-1060-release-notes/) who put table with "row format COMPRESSED" in read only. I installed mariadb 10.6.0 on August 2021 i don't why it breaks now. 

The solution i found is to put `innodb_read_only_compressed=0` in my `mysqld` conf.

References :
https://mariadb.com/docs/reference/mdb/system-variables/innodb_read_only_compressed/
https://help.nextcloud.com/t/mariadb-10-6-0-compressed-row-format-depreciation/115008

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/issues/25436
