### ISSUE TITLE
Disallow creation of "local" storage for web UI admins

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#29973]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
In some setups, the sys admin (CLI) is not the same person as the Nextcloud admin (web UI).
A sys admin will want to allow web UI admins to mount external storages, but disable the "Local" one for security reasons because "Local" could allow one to mount the whole filesystem.
The current workaround is to never allow external storages on such setups.

**Describe the solution you'd like**
A config.php option that disallows creation and modification of "Local" storages.
If such storages are already configured, they stay as is but cannot be modified through the web UI or APIs.
The occ command for managing external storages still allows the sys admin to configure "Local" storages when needed.

**Comment by acsfer** [comment]
Agree. The most common setups of this kind are simple shared server setups.

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/server/pull/30111
