### ISSUE TITLE
video preview 404

### ISSUE THREAD

**Issue by wangzhengzhen** [nextcloud/server#29972]
nextcloud for docker 

version: 22.2.3

apt install ffmpeg exiftool imagemagick imagemagick-common ghostscript

config.php:

![image](https://user-images.githubusercontent.com/6226945/143999799-70008dbd-7901-4981-90e6-c8fcd0640ead.png)

image preivew no problem
video preview 404

![image](https://user-images.githubusercontent.com/6226945/143999623-57ab2492-5b9d-405e-bb1d-46b914864d92.png)

**Comment by acsfer** [comment]
Please ask this on forum as this is a setup/configuration issue. Thanks for understanding 👍 
https://help.nextcloud.com
