### ISSUE TITLE
Any user can modify or delete other users

### ISSUE THREAD

**Issue by PatriceVigier** [nextcloud/server#29981]
Nextcloud version (eg, 20.0.5): Next cloud 20.0.5
Operating system and version (eg, Ubuntu 20.04): Debian 9
Apache or nginx version (eg, Apache 2.4.25): Apache 2.4.25
PHP version (eg, 7.4): PHP 7.3.33

The issue you are facing:

As the main admin, I have created a new user and made him part of a group, this user is not an admin.

This new user can now login and from menu users==>everyone can see some of the users and for some of these users, he can deleted them or wipe their data while.

(“Some of the users” means, he can see users that are part of a group (any group), but he cannot see users that have no group.)

It look like, as long as a non admin user is part of a group he has the possibility to delete or update other users as long as they are part of a group.

This is a “dangerous” possibility, how can I correct this behavior?
Thank you

**Comment by PatriceVigier** [comment]
More info about it here
[https://help.nextcloud.com/t/any-user-can-modify-or-delete-other-users/127913](url)

**Comment by szaimen** [comment]
cc @nextcloud/security

**Comment by nickvergessen** [comment]
> As the main admin, I have created a new user and made him part of a group, this user is not an admin.

Did you make them a group administrator? Then this expected

**Comment by PatriceVigier** [comment]
no, a simple user

**Comment by nickvergessen** [comment]
But the user section of the settings only appears once you are a subadmin of at least one group. And then it's expected that you can administrate those users.

**Comment by acsfer** [comment]
I've tried to reproduce this on a freshly instance, and it only happens IF the user is a group admin. Regular user can't see the User menu at all. Even if the regular users goes to `https://example.com/settings/users` URL, it gets a **403 Forbidden**.

Anyway, feel free to produce a screencast where the problem can be reproduced the same you than you do. 👍

**Comment by PatriceVigier** [comment]
While I was making screen shot, I found that I'm an idiot and made you waste your time, sorry about this, the user was part of an admin group. So there are no problem.
Very sorry.

**Comment by nickvergessen** [comment]
Thanks for coming back @PatriceVigier 
Mistakes happen as we are all humans 💙
