### ISSUE TITLE
Custom default dashboard background?

### ISSUE THREAD

**Issue by almulder** [nextcloud/server#29993]
So I was reviewing the "[Override default dashboard background with theming one #23588](https://github.com/nextcloud/server/pull/23588)"

and it shows there is a spot for a custom default dashboard background, but I do not see that option.

I have Theming 1.13.0 enabled, but I can only set the login background, I see no option for the dashboard. Was this never added?

**Comment by acsfer** [comment]
Does this answer your question? https://github.com/nextcloud/server/pull/23588#issuecomment-724648655
