### ISSUE TITLE
Theming app: allow to limit width/height on retrieving logo

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#29998]
Sometimes users/admin add a very large logo via theming app.
This is then retrieved from clients and can lead to a crash on Android.
But in general (even without a crash) such a big image (>500px) is not needed.

Therefore it would be great to allow to resize the logo when retrieving it:
http:\/\/localhost\/nc\/index.php\/apps\/theming\/image\/logo?useSvg=1&v=140&x500

**Comment by skjnldsv** [comment]
Is it still an issue @tobiasKaminsky ?

**Comment by tobiasKaminsky** [comment]
Not that I am aware of.
But might re-occur again.
We can still close it :)
