### ISSUE TITLE
RFE: Override config.php pathname with environment variable

### ISSUE THREAD

**Issue by gdamjan** [nextcloud/server#300]
Allow to override the pathname of the config file (or config directory) so that it can be placed outside the nextcloud installed files.

This would make it easier to update the server code, and/or also to use a single code for several installations (with different configs).

ps.
if the idea is accepted, I can try make a PR too

**Comment by mar1u5** [comment]
Mhmm... Interessting. This would mean we need a 2nd config file where we set the path to the "real" config? :grin:

**Comment by gdamjan** [comment]
that's part of the php hosting environment, afaik with apache you'd use SetEnv, and with uwsgi (my app-server of choice) you'd use --env (or Environment in its systemd service file). 
You need a config file for those anyway.

**Comment by MorrisJobke** [comment]
This would make the CLI tool also harder to execute and it makes the complexity of the system a bit bigger. Beside that I don't have anything in mind, why this would not work out.


Maybe @nickvergessen @schiessle or @LukasReschke has something in mind.

**Comment by gdamjan** [comment]
yes, the CLI would have to have the same env var. I consider this an advanced setting, so the default would still be as it is now. people that have it configured would have to remember to set the same env var.

**Comment by gdamjan** [comment]
btw, there are random places in the code-base that create paths based on OC::$SERVERROOT. Going forward it might be more practical to change those to an interface through OC, i.e. functions or properties.

**Comment by kyrofa** [comment]
> btw, there are random places in the code-base that create paths based on OC::$SERVERROOT. Going forward it might be more practical to change those to an interface through OC, i.e. functions or properties.

:+1:

**Comment by gdamjan** [comment]
this was merged in #660

**Comment by MorrisJobke** [comment]
> this was merged in #660

And will be available with Nextcloud 11 🎉

**Comment by jospoortvliet** [comment]
Hi guys,

It would help us a fair bit if this was backported to 10 stable - it means we don't have to apply a patch for our Snap. Then we can even do daily snaps!!!  Is it feasible to backport?

**Comment by MorrisJobke** [comment]
> It would help us a fair bit if this was backported to 10 stable - it means we don't have to apply a patch for our Snap. Then we can even do daily snaps!!! Is it feasible to backport?

cc @karlitschek because this is usually a feature and we only backport bug fixes 🙈

**Comment by nickvergessen** [comment]
Already backported in https://github.com/nextcloud/server/pull/1081

**Comment by jluttine** [comment]
This is a great feature, thanks. I searched if this was supported or not for many hours and couldn't find that it was. Until finally now. Would it be possible to add something about this into the documentation? Or did I just miss any mentioning of it there..?

**Comment by nickvergessen** [comment]
No, I don't think so. Can you add an issue in https://github.com/nextcloud/documentation/issues/new
Thanks

**Comment by jluttine** [comment]
@nickvergessen Done.
