### ISSUE TITLE
Admin right priviledge configuration does nothing - user does not get the admin rights in 23.0.0

### ISSUE THREAD

**Issue by jasond2020** [nextcloud/server#30004]
* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. create a user and a group
2. go to Admin right priviledge settings and allow the configured group to have some admin rights
3. log in with the created user and try to configure something with this new rights

### Expected behaviour
in 3. the user should see the corresponding settings he just got the rights to adjust

### Actual behaviour
in 3.  no admin settings are available

### Server configuration

**Operating system:** ubuntu 20.04
 
**Web server:** apache

**Database:** mysql 

**PHP version:** 7.4

**Nextcloud version:** 23.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 22.2.3

only some local users, no ldap-backend or third-party authorization

**Comment by jasond2020** [comment]
it works on a debian 11.1 system
are there some known interferences with acticated or deactivated apps? or maybe something concerning user-attributes like "group admin"
i do not see any error messages in the logs

**Comment by Mastertomspirit** [comment]
I have the same problem with existing users.
Regardless of whether the group is newly created or changed to an existing one.
There are also no log messages.

However, it works fine with newly created users.

It runs on Ubuntu 21.10 raspberry in Docker-Containers

Nextcloud-fpm 23.0.0 
nginx  
postgresql 14
redis


no ldap using

-auto-groups
-encryption
-two-factor TOTP Provider
-two-factor U2F
+ 2fa is required

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by rosa2** [comment]
with the update, we got the problem fixed.

**Comment by szaimen** [comment]
Great! Thanks for verifying!
