### ISSUE TITLE
Generating previews for animated webp images fails

### ISSUE THREAD

**Issue by pawanrai9999** [nextcloud/server#30029]
Steps to reproduces bug:-

1. Upload files to nextcloud(which include .jpeg, .gif, .webp)
2. run `php occ preview:pre-generate`
3. delete the .webp file
4. run `php occ preview:pre-generate`
5. the issue goes away

Nextcloud Log: - 
`{
  "reqId": "QLuWknpRbkVx8NK49QA6",
  "level": 3,
  "time": "2021-11-11T14:58:35+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "PHP",
  "method": "",
  "url": "--",
  "message": "gd-webp cannot allocate temporary buffer at /var/www/html/lib/private/legacy/OC_Image.php#620",
  "userAgent": "--",
  "version": "22.2.0.2",
  "id": "618dc9bac3434"
}`

I guess this is similar [issue.](https://stackoverflow.com/questions/61394477/php-e-error-gd-webp-cannot-allocate-temporary-buffer)

[Uploading this file definitely causes issues
](https://thumbs.gfycat.com/JointUnnaturalEnglishsetter.webp)

**Comment by Zipdox** [comment]
Could imagemagick be used for this instead?

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by lachlantula** [comment]
i'm still able to reproduce this issue with animated webp files on 25.0.3 upon running `occ preview:generate-all`: `PHP Fatal error:  gd-webp cannot allocate temporary buffer in /var/www/html/lib/private/legacy/OC_Image.php on line 722`.
