### ISSUE TITLE
External storage user access dropdown is broken

### ISSUE THREAD

**Issue by CarlSchwan** [nextcloud/server#30035]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Configure an external storage

### Expected behaviour
Name of users and groups are displayed

### Actual behaviour

![image](https://user-images.githubusercontent.com/23653902/144392649-8705c104-4c7a-4b3f-a6a2-c68a04e277bc.png)

### Server configuration

**Operating system:** docker from julius

**Web server:** apache

**Database:** mysql

**PHP version:** 7.4

**Nextcloud version:** master

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** s3

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

```
</details>

### Client configuration
**Browser:** Firefox

**Operating system:** openSUSE

### Logs

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

Nothing relevant found
</details>

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
