### ISSUE TITLE
Error: Call to undefined method `OCP\Util::isIE()`

### ISSUE THREAD

**Issue by RyanNeumann** [nextcloud/server#30031]
Hey all, 

Recently upgraded to Nextcloud 23 and am experiencing an issue.  
My current setup:

Ubuntu 20.04
PHP8.0-fpm
Nginx

Since the upgrade, my nextcloud webpage shows only a 500 error.  If I downgrade to PHP7.4-fpm, then the screen turns into "Internal Service Error", with no indication of why in the logs.  Obviously, upgrading to PHP8.1-fpm throws the "Nextcloud is not compatible with the version of PHP" 

Below is the nextcloud log of attempting to access the site.  From the log, it seems that it is an issue with nextcloud rather than PHP.  I'm hoping some of the experts here can provide some clarity on where I am going wrong.  Thank you! 

> {
>   "reqId": "0PRZwmfr3h9jEmTjxxaJ",
>   "level": 1,
>   "time": "2021-12-01T22:42:21+00:00",
>   "remoteAddr": "***.***.*.***",
>   "user": "--",
>   "app": "core",
>   "method": "GET",
>   "url": "/nextcloud/",
>   "message": "Trusted domain error. \"***.***.*.***\" tried to access using \"***.***.*.***\" as host.",
>   "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
>   "version": "23.0.0.10"
> }
> {
>   "reqId": "0PRZwmfr3h9jEmTjxxaJ",
>   "level": 3,
>   "time": "2021-12-01T22:42:21+00:00",
>   "remoteAddr": "***.***.*.***",
>   "user": "--",
>   "app": "index",
>   "method": "GET",
>   "url": "/nextcloud/",
>   "message": "Call to undefined method OCP\\Util::isIE()",
>   "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
>   "version": "23.0.0.10",
>   "exception": {
>     "Exception": "Error",
>     "Message": "Call to undefined method OCP\\Util::isIE()",
>     "Code": 0,
>     "Trace": [
>       {
>         "file": "/var/www/html/nextcloud/lib/private/legacy/OC_Template.php",
>         "line": 182,
>         "function": "__construct",
>         "class": "OC\\TemplateLayout",
>         "type": "->"
>       },
>       {
>         "file": "/var/www/html/nextcloud/lib/private/Template/Base.php",
>         "line": 132,
>         "function": "fetchPage",
>         "class": "OC_Template",
>         "type": "->"
>       },
>       {
>         "file": "/var/www/html/nextcloud/lib/base.php",
>         "line": 786,
>         "function": "printPage",
>         "class": "OC\\Template\\Base",
>         "type": "->"
>       },
>       {
>         "file": "/var/www/html/nextcloud/lib/base.php",
>         "line": 1087,
>         "function": "init",
>         "class": "OC",
>         "type": "::"
>       },
>       {
>         "file": "/var/www/html/nextcloud/index.php",
>         "line": 35,
>         "args": [
>           "/var/www/html/nextcloud/lib/base.php"
>         ],
>         "function": "require_once"
>       }
>     ],
>     "File": "/var/www/html/nextcloud/lib/private/TemplateLayout.php",
>     "Line": 83,
>     "CustomMessage": "--"
>   }
> }
> {
>   "reqId": "0PRZwmfr3h9jEmTjxxaJ",
>   "level": 3,
>   "time": "2021-12-01T22:42:21+00:00",
>   "remoteAddr": "***.***.*.***",
>   "user": "--",
>   "app": "PHP",
>   "method": "GET",
>   "url": "/nextcloud/",
>   "message": "Error: Call to undefined method OCP\\Util::isIE() at /var/www/html/nextcloud/lib/private/TemplateLayout.php#83",
>   "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36",
>   "version": "23.0.0.10"
> }

**Comment by MichaIng** [comment]
Please check PHP-FPM and webserver logs, likely `/var/log/php8.0-fpm.log` and `/var/log/nginx/error.log`. Also restart both to assure that all caches are cleared:
```sh
systemctl restart php8.0-fpm nginx
```

The first Nextcloud log `Trusted domain error` btw means that someone tried to access that instance with an untrusted domain, e.g. if another host proxies requests to your Nextcloud. Or was this an attempt by you to access via IP instead of domain?

The main error seems to be `Call to undefined method OCP\Util::isIE()`. Strange about it is that this has been remove here: #29966
But this was just to days ago into the master branch for Nextcloud 24, not affecting Nextcloud 23. You are on the stable channel, aren't you?

**Comment by RyanNeumann** [comment]
I restarted both php8.0-fpm and nginx to no avail.  I restarted the machine as well.  The php8.0-fpm.logs are empty besides opened/closed connections (no errors).  The Trusted domain error was me accessing my instance from another computer.  I am on the stable branch and updated using the `sudo -u www-data php updater/updater.phar` command.  

I managed to create a new nextcloud instance successfully using 23.0.  However, I had to use the "/var/www/" directory instead of "/var/www/html/".  This seemed to work as a fresh install, while attempting to do a fresh install in "/var/www/html" always resulted in the same issue as above.  

My nextcloud instance is up and running, but I'm still curious as to why the error occured in the first place.

**Comment by MichaIng** [comment]
> I had to use the "/var/www/" directory instead of "/var/www/html/".

But you do take care that this matches the webservers document root, don't you? If so, it shouldn't matter at all and you should be likewise able to put it into `/this/is/my/nextcloud/dir` as long as the webserver's webroot (and in case full directory paths in it's configs) does match that.
