### ISSUE TITLE
Nextcloud 23 Who ...

### ISSUE THREAD

**Issue by jm3west** [nextcloud/server#30049]
Hi,

who releases something like that?

Everytime new release are new issues!
The macOS-client spits only errors ...

... Bad Request, MD5, network error, .....

Nextcloud is a tinker-cloud

New release three day search for errors. Google up and down.

And professionals pay money for this? wow

**Comment by acsfer** [comment]
Sorry but this has nothing to do with specific and detailed bug reports, which Github is made for.
Feel free to publish at https://help.nextcloud.com 👍
