### ISSUE TITLE
All PDF files uploaded to Nextcloud downloaded with content-length: 0

### ISSUE THREAD

**Issue by kwisatz** [nextcloud/server#30059]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Upload a PDF file using the desktop client 
2. Open the PDF through the Web UI or download it

### Expected behaviour
The PDF file should be downloaded having the same file-size and being functional.

### Actual behaviour
The uploaded file in this example has 285kb.

![PDF-Fill-Files-TenTwentyFour-Cloud-Storage](https://user-images.githubusercontent.com/237949/144815110-8e9f40ad-07de-4043-85be-f76e184d7ef5.png)

The web-interface shows it as 285kb, but when downloading the file, the server sends the following header:

```
content-disposition: attachment; filename*=UTF8''EMI-TRIM.pdf; filename="EMI-TRIM.pdf"
content-length: 0
content-type: application/pdf
```

When attempting to open the pdf using pdf.js, it complains:

```
Invalid or corrupt PDF file.
Message: The PDF file is empty, i.e. its size is zero bytes.
```

When using the virtual files, a timeout occurs:

```
Error 0x800701AA: The cloud operation was not completed before the time-out period expired.
```

When not using virtuel files, the error log of the client states:

```
EMI-TRIM.pdf: The downloaded file is empty, but the server said it should have been 285KB.
```

On the server, pdf files uploaded through the desktop-client are indeed of size 0kb:

```
root@nidor:/var/nextcloud/data/kwisatz/files# ls -l Shares/PDF-Fill/*.pdf
-rw-r--r-- 1 www-data www-data       0 Dec  2 18:45 Shares/PDF-Fill/EMI-TRIM.pdf
-rw-r--r-- 1 www-data www-data       0 Dec  2 18:40 Shares/PDF-Fill/EMI_TRIM.pdf
-rw-r--r-- 1 www-data www-data 1629152 Nov 21 16:41 Shares/PDF-Fill/some-new-form.pdf
```

### Server configuration

**Operating system:** Debian 10.11

**Web server:** apache 2.4.38

**Database:** posgresql 11+200+deb10u4

**PHP version:** 7.3+69

**Nextcloud version:** (see Nextcloud admin page) 22.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated regularly from an original Nextcloud 18

**Where did you install Nextcloud from:** jurisic

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```json
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.tentwentyfour.lu"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "htaccess.RewriteBase": "\/",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "22.2.2.0",
        "overwrite.cli.url": "https:\/\/cloud.tentwentyfour.lu",
        "overwritehost": "cloud.tentwentyfour.lu",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "352",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "upgrade.disable-web": "true",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "maintenance": false,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud\/server.log",
        "loglevel": 1,
        "app_install_overwrite": [
            "ownpad"
        ],
        "has_rebuilt_cache": true,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": []
    }
}
```
</details>

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** various

**Operating system:** Linux/Windows

#### Web server error log
<details>
<summary>Web server error log</summary>

no log entries

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

no log entries

</details>

#### Browser log
<details>
<summary>Browser log</summary>

relevant network tab details posted above
</details>

**Comment by cr-bruderer** [comment]
When using the desktop client, PDFs are not properly synced either. The upload somehow fails with the same error as described above, resulting in a .part-File in the folder where they should have been uploaded to.

Dragging them into the WebGUI uploads them just fine.

**Comment by kwisatz** [comment]
I just noticed that the PDF is only corrupted after a while. If it is opened straight away after synchronisation, it opens fine.
After a while, it no longer does so. This got me thinking and by checking the logs, I also found this:

```
{"reqId":"pkIWmdvySD51cHB8VW6D","level":1,"time":"2021-12-06T16:34:42+00:00","remoteAddr":"85.208.5.*","user":"08ece906-d7b8-1035-9c8d-97c38bc36d8d","app":"workflowengine","method":"PUT","url":"/apps/text/session/create","message":"Flow handling done for event \\OCP\\Files::postCreate","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36","version":"22
.2.2.0"}                                                                                                                                                                                                          
```

I deleted the OCR rule from flow (the only one we had actually) and PDFs are no longer corrupted or 0-sized. So the real culprit here seems to be the OCR plug-in. It's version is 1.22.3

**Comment by R0Wi** [comment]
Because it seems to be an issue with the OCR workflow plugin we'll discuss further at https://github.com/R0Wi/workflow_ocr/issues/79. Closing this here.
