### ISSUE TITLE
Tasks not syncing in Evolution (Ubuntu 16.04 Evolution v3.18.5.2)

### ISSUE THREAD

**Issue by zeigerpuppy** [nextcloud/server#3006]
Calendar Sync is working well in Evolution, but tasks don't sync.
The task app says that tasks should sync automatically when CalDAV calendar sync is enabled.

### Steps to reproduce
1. set up CalDAV calendar sync in evolution
2. create Tasks locally and on Nextcloud Server
3. try to refresh

### Expected behaviour
Tasks should sync

### Actual behaviour
Tasks don't sync

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
nginx

**Database:**
MySQL (MariaDB)

**PHP version:**
7.1

**Nextcloud version:** (see Nextcloud admin page)
9.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
no, fresh install

**Where did you install Nextcloud from:**
installer tarball

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - activity: 2.3.2
  - bookmarks: 0.9.0
  - calendar: 1.4.1
  - comments: 1.0.0
  - contacts: 1.5.1
  - dav: 1.0.0
  - documents: 0.13.1
  - external: true
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.4
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_external: 0.4
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - mail
  - ojsxc
  - ownnote
  - templateeditor
  - user_ldap
  - user_saml
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Yes, IMAP

### Client configuration
**Browser:**
Evolution v3.18.5.2

**Operating system:**
16.04

#### Web server error log
<details>
<summary>Web server error log</summary>
```
no errors
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
no errors on sync
```

**Comment by jancborchardt** [comment]
Any idea here @nextcloud/tasks @nextcloud/calendar? :)

**Comment by tcitworld** [comment]
Hmm, just tested and it works for me by adding my account through the Gnome Online Accounts.

I'm using Gnome (and Evolution) 3.22.6 though, so it may be related to your Gnome version.
By the way, you should also update your Nextcloud version.
