### ISSUE TITLE
Reopening issue #26861 which still persist in NC 23

### ISSUE THREAD

**Issue by elhananjair** [nextcloud/server#30066]
Please check out this video: 
https://user-images.githubusercontent.com/69236638/137284240-9852366e-bdb9-49ea-8727-271f32df34db.mp4
This bug isn't fixed since NC 21.0.5

**Comment by acsfer** [comment]
https://github.com/nextcloud/server/issues/26861#issuecomment-943172397
> As I already said: NC 21.0.4 uses nextcloud/vue@v3.2.0. This fix has only made it to nextcloud/vue@v4.0.0 which will be used in NC 23

Please upgrade to v23.0.0. Report back if not fixed. Thanks 👍

**Comment by elhananjair** [comment]
> [#26861 (comment)](https://github.com/nextcloud/server/issues/26861#issuecomment-943172397)
> 
> > As I already said: NC 21.0.4 uses nextcloud/vue@v3.2.0. This fix has only made it to nextcloud/vue@v4.0.0 which will be used in NC 23
> 
> You are using 21.0.5. Please upgrade to v23.0.0. Report back if not fixed. Thanks +1

@acsfer I don't think you read the topic of my issue or this "This bug isn't fixed since NC 21.0.5"! 

I have tried on NC 23 and the issue still exists! The video I mentioned is to show how the problem could be reproduced by anyone who wants to try it (SINCE THE PROBLEM IS THE SAME I USED AN OLD VIDEO THAT I HAVE USED BEFORE TO POST THIS ISSUE).

**Comment by acsfer** [comment]
I just can't guess if title reports one thing and video another...
Original issue reopened.
