### ISSUE TITLE
Calendar provider can not provide shared calendars

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#30068]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Use `\OC\Calendar\Manager::getCalendarsForPrincipal` with an empty array of calendar URIs (search all)
  * -> Get a full list of owned and shared calendars
2. Use `\OC\Calendar\Manager::getCalendarsForPrincipal` to load one of those owned calenars
  * -> Get that calendar object
3. Use `\OC\Calendar\Manager::getCalendarsForPrincipal` to load one of the shared calendars

### Expected behavior

Get the shared calendar object.

### Actual behavior

Run into an error because the calendar isn't found

### Server configuration

**Nextcloud version:** 23.0

---

`\OCA\DAV\CalDAV\CalendarProvider::getCalendars` calls `\OCA\DAV\CalDAV\CalDavBackend::getCalendarsForUser` and that doesn't work with shared URIs. We'll have to decode the `shared_by` parts or apply another trick to detect that an URI represents a shared calendar.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by SebastianKrupinski** [comment]
Resolved with https://github.com/nextcloud/server/pull/48621
