### ISSUE TITLE
Files uploaded are shared to all users

### ISSUE THREAD

**Issue by jetadidas** [nextcloud/server#30063]
When uploading into Nextcloud local file the file shows up to all users

Steps to reproduce
1.setup local storage 
2.upload file
3.log in with different user and check to see I that file shows up

### Expected behaviour
Each user should have the own file storage and not uploaded to all users unless shared 
### Actual behaviour
Files uploaded shares across all users 

### Server configuration

**Operating system:**
NextCloudPI 4gb
**Web server:**

**Database:**
My sql

**PHP version:**
8.0.1
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 23 hub II
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh initial 
**Where did you install Nextcloud from:**
Update from updater 
**
```
Login as admin user into your Nextcloud and access 
No errors have been found.
```

Thank you for your great work

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
