### ISSUE TITLE
upgrade from 20.0.14.2 to 21.0.7

### ISSUE THREAD

**Issue by dkryszak** [nextcloud/server#30127]
Doctrine\DBAL\Exception\TableExistsException: An exception occurred while executing a query: SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "oc_migrations" already exists
Update failed

any idea what is wrong. Table exists but has 125 records. I can drop it or clear whole data but maybe this is not good idea.

**Comment by dkryszak** [comment]
{"reqId":"Ya87c@N-s3YKzcoaGakBmwAAAAI","level":1,"time":"December 07, 2021 11:46:11","remoteAddr":"199.217.7.233","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=cIGrkdEzCY56UaM7qEFJ6EEX5moqfbt85SO3ILTWqJs%3D%3AOdeb9odSask%2FGZdX7gkBv3dYolJsFfIygQzfZOKi6vk%3D","message":"\\OC\\Updater::setDebugLogLevel: Set log level to debug","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36","version":"20.0.14.2"}
{"reqId":"Ya87c@N-s3YKzcoaGakBmwAAAAI","level":1,"time":"December 07, 2021 11:46:11","remoteAddr":"199.217.7.233","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=cIGrkdEzCY56UaM7qEFJ6EEX5moqfbt85SO3ILTWqJs%3D%3AOdeb9odSask%2FGZdX7gkBv3dYolJsFfIygQzfZOKi6vk%3D","message":"\\OC\\Updater::maintenanceEnabled: Turned on maintenance mode","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36","version":"20.0.14.2"}
{"reqId":"Ya87c@N-s3YKzcoaGakBmwAAAAI","level":0,"time":"December 07, 2021 11:46:11","remoteAddr":"199.217.7.233","user":"--","app":"core","method":"GET","url":"/core/ajax/update.php?requesttoken=cIGrkdEzCY56UaM7qEFJ6EEX5moqfbt85SO3ILTWqJs%3D%3AOdeb9odSask%2FGZdX7gkBv3dYolJsFfIygQzfZOKi6vk%3D","message":"starting upgrade from 20.0.14.2 to 21.0.7.0","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36","version":"20.0.14.2"}
{"reqId":"Ya87c@N-s3YKzcoaGakBmwAAAAI","level":1,"time":"December 07, 2021 11:46:11","remoteAddr":"199.217.7.233","user":"--","app":"no app in context","method":"GET","url":"/core/ajax/update.php?requesttoken=cIGrkdEzCY56UaM7qEFJ6EEX5moqfbt85SO3ILTWqJs%3D%3AOdeb9odSask%2FGZdX7gkBv3dYolJsFfIygQzfZOKi6vk%3D","message":"Deprecated event type for \\OC\\Repair::step: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36","version":"20.0.14.2"}
{"reqId":"Ya87c@N-s3YKzcoaGakBmwAAAAI","level":1,"time":"December 07, 2021 11:46:11","remoteAddr":"199.217.7.233","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=cIGrkdEzCY56UaM7qEFJ6EEX5moqfbt85SO3ILTWqJs%3D%3AOdeb9odSask%2FGZdX7gkBv3dYolJsFfIygQzfZOKi6vk%3D","message":"\\OC\\Repair::step: Repair step: Repair MySQL collation","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36","version":"20.0.14.2"}
{"reqId":"Ya87c@N-s3YKzcoaGakBmwAAAAI","level":1,"time":"December 07, 2021 11:46:11","remoteAddr":"199.217.7.233","user":"--","app":"no app in context","method":"GET","url":"/core/ajax/update.php?requesttoken=cIGrkdEzCY56UaM7qEFJ6EEX5moqfbt85SO3ILTWqJs%3D%3AOdeb9odSask%2FGZdX7gkBv3dYolJsFfIygQzfZOKi6vk%3D","message":"Deprecated event type for \\OC\\Repair::info: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36","version":"20.0.14.2"}
{"reqId":"Ya87c@N-s3YKzcoaGakBmwAAAAI","level":1,"time":"December 07, 2021 11:46:11","remoteAddr":"199.217.7.233","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=cIGrkdEzCY56UaM7qEFJ6EEX5moqfbt85SO3ILTWqJs%3D%3AOdeb9odSask%2FGZdX7gkBv3dYolJsFfIygQzfZOKi6vk%3D","message":"\\OC\\Repair::info: Repair info: Not a mysql database -> nothing to do","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36","version":"20.0.14.2"}
{"reqId":"Ya87c@N-s3YKzcoaGakBmwAAAAI","level":1,"time":"December 07, 2021 11:46:11","remoteAddr":"199.217.7.233","user":"--","app":"no app in context","method":"GET","url":"/core/ajax/update.php?requesttoken=cIGrkdEzCY56UaM7qEFJ6EEX5moqfbt85SO3ILTWqJs%3D%3AOdeb9odSask%2FGZdX7gkBv3dYolJsFfIygQzfZOKi6vk%3D","message":"Deprecated event type for \\OC\\Repair::step: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36","version":"20.0.14.2"}
{"reqId":"Ya87c@N-s3YKzcoaGakBmwAAAAI","level":1,"time":"December 07, 2021 11:46:11","remoteAddr":"199.217.7.233","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=cIGrkdEzCY56UaM7qEFJ6EEX5moqfbt85SO3ILTWqJs%3D%3AOdeb9odSask%2FGZdX7gkBv3dYolJsFfIygQzfZOKi6vk%3D","message":"\\OC\\Repair::step: Repair step: Repair SQLite autoincrement","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36","version":"20.0.14.2"}
{"reqId":"Ya87c@N-s3YKzcoaGakBmwAAAAI","level":1,"time":"December 07, 2021 11:46:11","remoteAddr":"199.217.7.233","user":"--","app":"no app in context","method":"GET","url":"/core/ajax/update.php?requesttoken=cIGrkdEzCY56UaM7qEFJ6EEX5moqfbt85SO3ILTWqJs%3D%3AOdeb9odSask%2FGZdX7gkBv3dYolJsFfIygQzfZOKi6vk%3D","message":"Deprecated event type for \\OC\\Repair::step: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36","version":"20.0.14.2"}
{"reqId":"Ya87c@N-s3YKzcoaGakBmwAAAAI","level":1,"time":"December 07, 2021 11:46:11","remoteAddr":"199.217.7.233","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=cIGrkdEzCY56UaM7qEFJ6EEX5moqfbt85SO3ILTWqJs%3D%3AOdeb9odSask%2FGZdX7gkBv3dYolJsFfIygQzfZOKi6vk%3D","message":"\\OC\\Repair::step: Repair step: Copy data from accounts table when migrating from ownCloud","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36","version":"20.0.14.2"}
{"reqId":"Ya87c@N-s3YKzcoaGakBmwAAAAI","level":1,"time":"December 07, 2021 11:46:11","remoteAddr":"199.217.7.233","user":"--","app":"no app in context","method":"GET","url":"/core/ajax/update.php?requesttoken=cIGrkdEzCY56UaM7qEFJ6EEX5moqfbt85SO3ILTWqJs%3D%3AOdeb9odSask%2FGZdX7gkBv3dYolJsFfIygQzfZOKi6vk%3D","message":"Deprecated event type for \\OC\\Repair::step: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36","version":"20.0.14.2"}
{"reqId":"Ya87c@N-s3YKzcoaGakBmwAAAAI","level":1,"time":"December 07, 2021 11:46:11","remoteAddr":"199.217.7.233","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=cIGrkdEzCY56UaM7qEFJ6EEX5moqfbt85SO3ILTWqJs%3D%3AOdeb9odSask%2FGZdX7gkBv3dYolJsFfIygQzfZOKi6vk%3D","message":"\\OC\\Repair::step: Repair step: Drop account terms table when migrating from ownCloud","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36","version":"20.0.14.2"}
{"reqId":"Ya87c@N-s3YKzcoaGakBmwAAAAI","level":1,"time":"December 07, 2021 11:46:11","remoteAddr":"199.217.7.233","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=cIGrkdEzCY56UaM7qEFJ6EEX5moqfbt85SO3ILTWqJs%3D%3AOdeb9odSask%2FGZdX7gkBv3dYolJsFfIygQzfZOKi6vk%3D","message":"\\OC\\Updater::dbUpgradeBefore: Updating database schema","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36","version":"20.0.14.2"}
{"reqId":"Ya87c@N-s3YKzcoaGakBmwAAAAI","level":3,"time":"December 07, 2021 11:46:11","remoteAddr":"199.217.7.233","user":"--","app":"core","method":"GET","url":"/core/ajax/update.php?requesttoken=cIGrkdEzCY56UaM7qEFJ6EEX5moqfbt85SO3ILTWqJs%3D%3AOdeb9odSask%2FGZdX7gkBv3dYolJsFfIygQzfZOKi6vk%3D","message":{"Exception":"Doctrine\\DBAL\\Exception\\TableExistsException","Message":"An exception occurred while executing a query: SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation \"oc_migrations\" already exists","Code":7,"Trace":[{"file":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1780,"function":"convert","class":"Doctrine\\DBAL\\Driver\\API\\PostgreSQL\\ExceptionConverter","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDO\\Exception"},{"__class__":"Doctrine\\DBAL\\Query"}]},{"file":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1719,"function":"handleDriverException","class":"Doctrine\\DBAL\\Connection","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDO\\Exception"},{"__class__":"Doctrine\\DBAL\\Query"}]},{"file":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1067,"function":"convertExceptionDuringQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDO\\Exception"},"CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, PRIMARY KEY(app, version))",[],[]]},{"file":"/var/www/html/nextcloud/lib/private/DB/Connection.php","line":231,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, PRIMARY KEY(app, version))",[],[],null]},{"file":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1809,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, PRIMARY KEY(app, version))"]},{"file":"/var/www/html/nextcloud/lib/private/DB/Migrator.php","line":256,"function":"query","class":"Doctrine\\DBAL\\Connection","type":"->","args":["CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, PRIMARY KEY(app, version))"]},{"file":"/var/www/html/nextcloud/lib/private/DB/Migrator.php","line":90,"function":"applySchema","class":"OC\\DB\\Migrator","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/html/nextcloud/lib/private/DB/Connection.php","line":529,"function":"migrate","class":"OC\\DB\\Migrator","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/html/nextcloud/lib/private/DB/MigrationService.php","line":178,"function":"migrateToSchema","class":"OC\\DB\\Connection","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/html/nextcloud/lib/private/DB/MigrationService.php","line":192,"function":"createMigrationTable","class":"OC\\DB\\MigrationService","type":"->","args":[]},{"file":"/var/www/html/nextcloud/lib/private/DB/MigrationService.php","line":265,"function":"getMigratedVersions","class":"OC\\DB\\MigrationService","type":"->","args":[]},{"file":"/var/www/html/nextcloud/lib/private/DB/MigrationService.php","line":423,"function":"getMigrationsToExecute","class":"OC\\DB\\MigrationService","type":"->","args":["latest"]},{"file":"/var/www/html/nextcloud/lib/private/Updater.php","line":309,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->","args":[]},{"file":"/var/www/html/nextcloud/lib/private/Updater.php","line":251,"function":"doCoreUpgrade","class":"OC\\Updater","type":"->","args":[]},{"file":"/var/www/html/nextcloud/lib/private/Updater.php","line":134,"function":"doUpgrade","class":"OC\\Updater","type":"->","args":["21.0.7.0","20.0.14.2"]},{"file":"/var/www/html/nextcloud/core/ajax/update.php","line":214,"function":"upgrade","class":"OC\\Updater","type":"->","args":[]}],"File":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php","Line":70,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDO\\Exception","Message":"SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation \"oc_migrations\" already exists","Code":7,"Trace":[{"file":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php","line":87,"function":"new","class":"Doctrine\\DBAL\\Driver\\PDO\\Exception","type":"::","args":[{"errorInfo":["42P07",7,"ERROR:  relation \"oc_migrations\" already exists"],"__class__":"PDOException"}]},{"file":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1062,"function":"query","class":"Doctrine\\DBAL\\Driver\\PDO\\Connection","type":"->","args":["CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, PRIMARY KEY(app, version))"]},{"file":"/var/www/html/nextcloud/lib/private/DB/Connection.php","line":231,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, PRIMARY KEY(app, version))",[],[],null]},{"file":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1809,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, PRIMARY KEY(app, version))"]},{"file":"/var/www/html/nextcloud/lib/private/DB/Migrator.php","line":256,"function":"query","class":"Doctrine\\DBAL\\Connection","type":"->","args":["CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, PRIMARY KEY(app, version))"]},{"file":"/var/www/html/nextcloud/lib/private/DB/Migrator.php","line":90,"function":"applySchema","class":"OC\\DB\\Migrator","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/html/nextcloud/lib/private/DB/Connection.php","line":529,"function":"migrate","class":"OC\\DB\\Migrator","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/html/nextcloud/lib/private/DB/MigrationService.php","line":178,"function":"migrateToSchema","class":"OC\\DB\\Connection","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/html/nextcloud/lib/private/DB/MigrationService.php","line":192,"function":"createMigrationTable","class":"OC\\DB\\MigrationService","type":"->","args":[]},{"file":"/var/www/html/nextcloud/lib/private/DB/MigrationService.php","line":265,"function":"getMigratedVersions","class":"OC\\DB\\MigrationService","type":"->","args":[]},{"file":"/var/www/html/nextcloud/lib/private/DB/MigrationService.php","line":423,"function":"getMigrationsToExecute","class":"OC\\DB\\MigrationService","type":"->","args":["latest"]},{"file":"/var/www/html/nextcloud/lib/private/Updater.php","line":309,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->","args":[]},{"file":"/var/www/html/nextcloud/lib/private/Updater.php","line":251,"function":"doCoreUpgrade","class":"OC\\Updater","type":"->","args":[]},{"file":"/var/www/html/nextcloud/lib/private/Updater.php","line":134,"function":"doUpgrade","class":"OC\\Updater","type":"->","args":["21.0.7.0","20.0.14.2"]},{"file":"/var/www/html/nextcloud/core/ajax/update.php","line":214,"function":"upgrade","class":"OC\\Updater","type":"->","args":[]}],"File":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php","Line":26,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation \"oc_migrations\" already exists","Code":"42P07","Trace":[{"file":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php","line":82,"function":"query","class":"PDO","type":"->","args":["CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, PRIMARY KEY(app, version))"]},{"file":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1062,"function":"query","class":"Doctrine\\DBAL\\Driver\\PDO\\Connection","type":"->","args":["CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, PRIMARY KEY(app, version))"]},{"file":"/var/www/html/nextcloud/lib/private/DB/Connection.php","line":231,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, PRIMARY KEY(app, version))",[],[],null]},{"file":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Connection.php","line":1809,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, PRIMARY KEY(app, version))"]},{"file":"/var/www/html/nextcloud/lib/private/DB/Migrator.php","line":256,"function":"query","class":"Doctrine\\DBAL\\Connection","type":"->","args":["CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, PRIMARY KEY(app, version))"]},{"file":"/var/www/html/nextcloud/lib/private/DB/Migrator.php","line":90,"function":"applySchema","class":"OC\\DB\\Migrator","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/html/nextcloud/lib/private/DB/Connection.php","line":529,"function":"migrate","class":"OC\\DB\\Migrator","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/html/nextcloud/lib/private/DB/MigrationService.php","line":178,"function":"migrateToSchema","class":"OC\\DB\\Connection","type":"->","args":[{"__class__":"Doctrine\\DBAL\\Schema\\Schema"}]},{"file":"/var/www/html/nextcloud/lib/private/DB/MigrationService.php","line":192,"function":"createMigrationTable","class":"OC\\DB\\MigrationService","type":"->","args":[]},{"file":"/var/www/html/nextcloud/lib/private/DB/MigrationService.php","line":265,"function":"getMigratedVersions","class":"OC\\DB\\MigrationService","type":"->","args":[]},{"file":"/var/www/html/nextcloud/lib/private/DB/MigrationService.php","line":423,"function":"getMigrationsToExecute","class":"OC\\DB\\MigrationService","type":"->","args":["latest"]},{"file":"/var/www/html/nextcloud/lib/private/Updater.php","line":309,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->","args":[]},{"file":"/var/www/html/nextcloud/lib/private/Updater.php","line":251,"function":"doCoreUpgrade","class":"OC\\Updater","type":"->","args":[]},{"file":"/var/www/html/nextcloud/lib/private/Updater.php","line":134,"function":"doUpgrade","class":"OC\\Updater","type":"->","args":["21.0.7.0","20.0.14.2"]},{"file":"/var/www/html/nextcloud/core/ajax/update.php","line":214,"function":"upgrade","class":"OC\\Updater","type":"->","args":[]}],"File":"/var/www/html/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Connection.php","Line":82}},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36","version":"20.0.14.2"}
{"reqId":"Ya87c@N-s3YKzcoaGakBmwAAAAI","level":3,"time":"December 07, 2021 11:46:11","remoteAddr":"199.217.7.233","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=cIGrkdEzCY56UaM7qEFJ6EEX5moqfbt85SO3ILTWqJs%3D%3AOdeb9odSask%2FGZdX7gkBv3dYolJsFfIygQzfZOKi6vk%3D","message":"\\OC\\Updater::failure: Doctrine\\DBAL\\Exception\\TableExistsException: An exception occurred while executing a query: SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation \"oc_migrations\" already exists","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36","version":"20.0.14.2"}
{"reqId":"Ya87c@N-s3YKzcoaGakBmwAAAAI","level":3,"time":"December 07, 2021 11:46:11","remoteAddr":"199.217.7.233","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=cIGrkdEzCY56UaM7qEFJ6EEX5moqfbt85SO3ILTWqJs%3D%3AOdeb9odSask%2FGZdX7gkBv3dYolJsFfIygQzfZOKi6vk%3D","message":"\\OC\\Updater::updateEnd: Update failed","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36","version":"20.0.14.2"}
{"reqId":"Ya87c@N-s3YKzcoaGakBmwAAAAI","level":1,"time":"December 07, 2021 11:46:11","remoteAddr":"199.217.7.233","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=cIGrkdEzCY56UaM7qEFJ6EEX5moqfbt85SO3ILTWqJs%3D%3AOdeb9odSask%2FGZdX7gkBv3dYolJsFfIygQzfZOKi6vk%3D","message":"\\OC\\Updater::maintenanceActive: Maintenance mode is kept active","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36","version":"20.0.14.2"}
{"reqId":"Ya87c@N-s3YKzcoaGakBmwAAAAI","level":1,"time":"December 07, 2021 11:46:11","remoteAddr":"199.217.7.233","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=cIGrkdEzCY56UaM7qEFJ6EEX5moqfbt85SO3ILTWqJs%3D%3AOdeb9odSask%2FGZdX7gkBv3dYolJsFfIygQzfZOKi6vk%3D","message":"\\OC\\Updater::resetLogLevel: Reset log level to Debug(0)","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.150 Safari/537.36","version":"20.0.14.2"}

**Comment by ChristophWurst** [comment]
Please ask for assistance on https://help.nextcloud.com/c/support/7 but also search the forum for existing topics. This is a bug tracker.
