### ISSUE TITLE
[F2V] Files list

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#30135]
This ticket is part of the [files to vue migration](https://github.com/nextcloud/server/issues/28063)

### Goal
Have the files list content based on the `OCA.Files.Views` Views
WITH VIRTUAL SCROLLING :warning: 

### QA
- [x] No design changes (other than finally using existing vue components)
- [x] Handle URL more elegantly
  - [x] `/f/{fileId}` still redirects to the default view
  - [x] `/apps/files/{view}/{fileid}`
- [ ] Breadcrumbs
  - [x] Split current path
  - [x] Each folder is clickable and load the files
  - [ ] Last folder can have a button that trigger a js action (e.g sharing icon)
        Requires `OCA.Files.List.Breadcrumbs` (pick better name if you want)
- [x] Columns (first 3 are hardcoded)
  - [x] Checkbox
  - [x] Name
  - [x] Actions provided by the OCA.Files.Actions
  - [x] Provided by [`OCA.Files.Views`](https://github.com/nextcloud/server/issues/30070)
- [ ] Listing
  - [x] Retrieve full list of files: virtual scrolling :warning: 
  - [ ] ScrollTo if `path` is a direct file
  - [x] Cache FileInfos by fileId
  - [x] When browsing away and back, all the files should be displayed directly and a loading indicator stating the list is being refreshed. Indicator should be a the bottom of the list. If most of the refreshes are fast enough (to be tested), ignore the indicator and just refresh silently in the back.
  - [x] Clicking the main name triggers the default action if defined, the download action if none defined
  - [x] Sort folders before files in ALL sorting modes. Not only name sorting.
- [x] Multiselect
  - [x] When a multiselect starts, store the list of selected FileInfo
  - [x] Reset when changing folder/view
  - [x] Show list of available options filling as much with as possible. The rest of the actions are put into a dropdown
- [x] Right click on an item open the menu at the location of the cursor
  - [ ] Deprecate files_rightclick
  - [ ] Make the right-click enabled by default but togglable in the files settings (per user)
- [ ] Error handling
  - [ ] Try to redirect to first parent if direct link to file doesn't exists
  - [ ] Redirect to root if both file nor direct parent exists

#### Bonus for later
- [ ] Design this in an API-kind of way so later we can also just call the list with the default view (e.g. a filepicker) (and without the actions :question:)
- ~~Can decide which column to show/hide per view~~ Design team said no

### Listing API and discussion
Currently I actually don't know if there is any need to let other scripts/apps interact with the content.
Any idea/comments?

**Comment by icewind1991** [comment]
> /apps/files/{view}/{fileid}

Using only the fileid in the url wont work, as multiple paths can point to the same fileid (trough sharing mostly), this can lead to cases where a user is browsing `/somefolder/foo`, reload and have the path change to `/someotherfolder/foo`. It will still show the same folder contents, but the path shown in the breadcrumb will be different.
