### ISSUE TITLE
Remove expiration date limit

### ISSUE THREAD

**Issue by go2sh** [nextcloud/server#3013]
### Steps to reproduce
1. Share folder by link
2. Set expire expiration date

### Expected behaviour
It should be possible to set any future date.

### Actual behaviour
Only dates within 3 Month are allowed.

### Details
We use nextcloud as a file exchange service with our customers and in many case we work together more than three months. So we need to refresh the links from time to time, which is inconvenient and can become very time consuming with many shared folders.

**Comment by rullzer** [comment]
We only enforce a limit if you set one in the admin settings.
Could you double check that there is no expiration date enforced there?

**Comment by go2sh** [comment]
Ayyy, that's it. Thx @rullzer. Sorry for the bug report, totally missed that.

**Comment by runout-at** [comment]
The text in the admin settings is misleading:
_Set default expiration date_
would mean a _default_ value not a _maximum_ value - changing the text will help.
Both values makes sense so it would be nice to have the _default_ value too.
