### ISSUE TITLE
Nextcloud 23 - Cannot add missing indices

### ISSUE THREAD

**Issue by drudgede** [nextcloud/server#30149]
### 

I just upgraded to Nextcloud 23 from Nextcloud 22 and get the post install warning that I have missing indices and I should run `db:add-missing-indices`. However, after running the command, the message still appears

### Steps to reproduce
1. Update to Nextcloud 23 via the web based updater
2. Check security and setup warnings in the Nextcloud settings. Here, the message appears:
```
In der Datenbank fehlen einige Indizes. Auf Grund der Tatsache, dass das Hinzufügen von Indizes in großen Tabellen einige Zeit in Anspruch nehmen kann, wurden diese nicht automatisch erzeugt. Durch das Ausführen von "occ db:add-missing-indices" können die fehlenden Indizes manuell hinzugefügt werden, während die Instanz weiter läuft. Nachdem die Indizes hinzugefügt wurden, sind Anfragen auf die Tabellen normalerweise schneller.
Fehlender Index "fs_id_storage_size" in der Tabelle "oc_filecache".
Fehlender Index "fs_storage_path_prefix" in der Tabelle "oc_filecache".
````
3. run the corresponding OCC command:
```
sudo -u mywwwuser /opt/plesk/php/7.4/bin/php /var/www/vhosts/mydomain.de/nextcloud/occ db:add-missing-indices
```
I replaced the name of my actual user and my domain.
4. Re-check the page in the settings again

### Expected behaviour
The given warning should be gone.

### Actual behaviour
The message still appears. Also, it does not seem like the occ command affects the mentioned table `oc_filecache`:

```
sudo -u mynextclouduser /opt/plesk/php/7.4/bin/php /var/www/vhosts/mydomain.de/nextcloud/occ db:add-missing-indices
The current PHP memory limit is below the recommended value of 512MB.
Check indices of the share table.
Check indices of the filecache table.
Check indices of the twofactor_providers table.
Check indices of the login_flow_v2 table.
Check indices of the whats_new table.
Check indices of the cards table.
Check indices of the cards_properties table.
Check indices of the calendarobjects_props table.
Check indices of the schedulingobjects table.
Check indices of the oc_properties table.
Done.
```
I replaced the name of my actual user and my domain.

### Server configuration

**Operating system:**

```
cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Web server:**

```
nginx -V
nginx version: nginx/1.20.1
built with OpenSSL 1.1.1  11 Sep 2018
TLS SNI support enabled
configure arguments: --prefix=/usr/share --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --modules-path=/usr/share/nginx/modules --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --lock-path=/var/lock/nginx.lock --pid-path=/run/nginx.pid --http-client-body-temp-path=/var/lib/nginx/body --http-fastcgi-temp-path=/var/lib/nginx/fastcgi --http-proxy-temp-path=/var/lib/nginx/proxy --http-scgi-temp-path=/var/lib/nginx/scgi --http-uwsgi-temp-path=/var/lib/nginx/uwsgi --user=nginx --group=nginx --with-file-aio --with-compat --with-http_ssl_module --with-http_realip_module --with-http_sub_module --with-http_dav_module --with-http_gzip_static_module --with-http_stub_status_module --with-http_v2_module --add-dynamic-module=mod_brotli --add-dynamic-module=mod_passenger/src/nginx_module --add-dynamic-module=mod_pagespeed --add-dynamic-module=mod_security
```

**Database:**

MySQL 10.3.32

**PHP version:**

```
/opt/plesk/php/7.4/bin/php -v
PHP 7.4.26 (cli) (built: Nov 18 2021 12:28:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.5, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.4.26, Copyright (c), by Zend Technologies
```

**Nextcloud version:** (see Nextcloud admin page)

Nextcloud Hub II (23.0.0)

**Updated from an older Nextcloud/ownCloud or fresh install:**

Updated from an older Nextcloud version (22.x.x).
Update channel: stable

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - announcementcenter: 4.0.2
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.4
  - camerarawpreviews: 0.7.12
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 4.0.3
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - deck: 1.2.9
  - encryption: 2.8.1
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - polls: 2.0.6
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - richdocuments: 3.8.6
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - welcome: 1.0.0
  - workflowengine: 2.2.1
Disabled:
  - files_antivirus
  - files_external
  - firstrunwizard
  - privacy
  - support
  - survey_client
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.13.1",
        "overwrite.cli.url": "http:\/\/***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "mysql.utf8mb4": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "skeletondirectory": "",
        "default_language": "de",
        "default_locale": "de_DE",
        "mail_smtpport": "25",
        "knowledgebaseenabled": false,
        "allow_user_to_change_display_name": false,
        "htaccess.RewriteBase": "\/",
        "theme": "",
        "loglevel": 2,
        "data-fingerprint": "01a6ef919050049503b488a3d33371a2",
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "mail_smtpsecure": "tls",
        "updatechecker": false
    }
}
```
</details>

**Are you using external storage, if yes which one:**

No

**Are you using encryption:**

Yes

**Are you using an external user-backend, if yes which one:**

No

### Client configuration
**Browser:**

Safari 15.1

**Operating system:**

MacOS Montenerey 12.0.1

#### Web server error log
<details>
<summary>Web server error log</summary>

I replaced my original domain with mydomain.de.
Nginx error log:

```
[Wed Sep 29 06:11:04.155469 2021] [core:crit] [pid 30438:tid 139665130637056] (13)Permission denied: [client 31.17.40.122:55156] AH00529: /var/www/vhosts/mydomain.de/nextcloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/var/www/vhosts/mydomain.de/nextcloud/data/' is executable
[Wed Sep 29 08:52:44.639061 2021] [core:crit] [pid 934:tid 139665055102720] (13)Permission denied: [client 195.37.187.245:54372] AH00529: /var/www/vhosts/mydomain.de/nextcloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/var/www/vhosts/mydomain.de/nextcloud/data/' is executable
[Wed Sep 29 08:52:51.581136 2021] [core:crit] [pid 934:tid 139665105458944] (13)Permission denied: [client 195.37.187.245:54686] AH00529: /var/www/vhosts/mydomain.de/nextcloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/var/www/vhosts/mydomain.de/nextcloud/data/' is executable
[Wed Sep 29 08:52:55.255347 2021] [core:crit] [pid 30439:tid 139665071888128] (13)Permission denied: [client 195.37.187.245:54908] AH00529: /var/www/vhosts/mydomain.de/nextcloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/var/www/vhosts/mydomain.de/nextcloud/data/' is executable
[Wed Oct 13 21:27:22.755484 2021] [core:crit] [pid 9588:tid 140379714213632] (13)Permission denied: [client 31.17.40.122:60426] AH00529: /var/www/vhosts/mydomain.de/nextcloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/var/www/vhosts/mydomain.de/nextcloud/data/' is executable
[Wed Oct 13 21:27:35.611367 2021] [core:crit] [pid 9588:tid 140379579930368] (13)Permission denied: [client 31.17.40.122:32784] AH00529: /var/www/vhosts/mydomain.de/nextcloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/var/www/vhosts/mydomain.de/nextcloud/data/' is executable
[Wed Oct 13 22:58:01.490333 2021] [core:crit] [pid 9588:tid 140379638679296] (13)Permission denied: [client 31.17.40.122:50410] AH00529: /var/www/vhosts/mydomain.de/nextcloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/var/www/vhosts/mydomain.de/nextcloud/data/' is executable
[Fri Oct 15 18:28:21.395669 2021] [core:crit] [pid 19040:tid 140379420600064] (13)Permission denied: [client 31.17.40.122:32780] AH00529: /var/www/vhosts/mydomain.de/nextcloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/var/www/vhosts/mydomain.de/nextcloud/data/' is executable
[Sat Oct 16 22:33:53.581630 2021] [core:crit] [pid 3036:tid 140379621893888] (13)Permission denied: [client 31.17.40.122:54318] AH00529: /var/www/vhosts/mydomain.de/nextcloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/var/www/vhosts/mydomain.de/nextcloud/data/' is executable
[Sat Oct 16 22:43:46.080972 2021] [core:crit] [pid 3036:tid 140379554752256] (13)Permission denied: [client 31.17.40.122:46570] AH00529: /var/www/vhosts/mydomain.de/nextcloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/var/www/vhosts/mydomain.de/nextcloud/data/' is executable```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

I replaced my original domain with mydomain.de.

```
{"reqId":"qUuIUPi5uHnxyhTVUara","level":3,"time":"2021-11-24T14:19:56+00:00","remoteAddr":"2.57.122.107","user":"--","app":"PHP","method":"GET","url":"/login","message":{"Exception":"Error","Message":"file_exists(): open_basedir restriction in effect. File(/templates/) is not within the allowed path(s): (/var/www/vhosts/mydomain.de/:/tmp/:/dev/urandom:/proc/meminfo:/proc/uptime:/proc/cpuinfo:/sys/devices/virtual/net/venet0:/sys/devices/virtual/net/venet0/power:/sys/devices/virtual/net/venet0/statistics) at /var/www/vhosts/mydomain.de/nextcloud/lib/private/Template/Base.php#68","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/Template/Base.php","line":68,"function":"file_exists"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/legacy/OC_Template.php","line":147,"function":"getAppTemplateDirs","class":"OC\\Template\\Base","type":"->"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/legacy/OC_Template.php","line":89,"function":"findTemplate","class":"OC_Template","type":"->"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php","line":204,"function":"__construct","class":"OC_Template","type":"->"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":123,"function":"render","class":"OCP\\AppFramework\\Http\\TemplateResponse","type":"->"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36","version":"20.0.13.1"}
{"reqId":"qUuIUPi5uHnxyhTVUara","level":3,"time":"2021-11-24T14:19:56+00:00","remoteAddr":"2.57.122.107","user":"--","app":"PHP","method":"GET","url":"/login","message":{"Exception":"Error","Message":"file_exists(): open_basedir restriction in effect. File(/templates/) is not within the allowed path(s): (/var/www/vhosts/mydomain.de/:/tmp/:/dev/urandom:/proc/meminfo:/proc/uptime:/proc/cpuinfo:/sys/devices/virtual/net/venet0:/sys/devices/virtual/net/venet0/power:/sys/devices/virtual/net/venet0/statistics) at /var/www/vhosts/mydomain.de/nextcloud/lib/private/Template/Base.php#68","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/Template/Base.php","line":68,"function":"file_exists"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/legacy/OC_Template.php","line":147,"function":"getAppTemplateDirs","class":"OC\\Template\\Base","type":"->"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/legacy/OC_Template.php","line":89,"function":"findTemplate","class":"OC_Template","type":"->"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/TemplateLayout.php","line":153,"function":"__construct","class":"OC_Template","type":"->"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/legacy/OC_Template.php","line":183,"function":"__construct","class":"OC\\TemplateLayout","type":"->"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php","line":210,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":123,"function":"render","class":"OCP\\AppFramework\\Http\\TemplateResponse","type":"->"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36","version":"20.0.13.1"}
{"reqId":"DymKpiMRe5nbTF7FML7u","level":3,"time":"2021-11-24T16:20:03+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":{"Exception":"Error","Message":"Call to a member function getPath() on null","Code":0,"Trace":[{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/Encryption/Update.php","line":107,"function":"getPath","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/Encryption/HookManager.php","line":40,"function":"postUnshared","class":"OC\\Encryption\\Update","type":"->"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/legacy/OC_Hook.php","line":110,"function":"postUnshared","class":"OC\\Encryption\\HookManager","type":"::"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/Share/Share.php","line":376,"function":"emit","class":"OC_Hook","type":"::"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/Share/Share.php","line":302,"function":"unshareItem","class":"OC\\Share\\Share","type":"::"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/apps/files_sharing/lib/ExpireSharesJob.php","line":77,"function":"unshare","class":"OC\\Share\\Share","type":"::"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/BackgroundJob/Job.php","line":52,"function":"run","class":"OCA\\Files_Sharing\\ExpireSharesJob","type":"->"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/BackgroundJob/TimedJob.php","line":59,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/cron.php","line":127,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/Files/Filesystem.php","Line":901,"CustomMessage":"Error while running background job (class: OCA\\Files_Sharing\\ExpireSharesJob, arguments: )"},"userAgent":"--","version":"20.0.13.1"}
{"reqId":"9yHouuzhUd3GrzQcJC2J","level":3,"time":"2021-11-25T16:25:02+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":{"Exception":"Error","Message":"Call to a member function getPath() on null","Code":0,"Trace":[{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/Encryption/Update.php","line":107,"function":"getPath","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/Encryption/HookManager.php","line":40,"function":"postUnshared","class":"OC\\Encryption\\Update","type":"->"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/legacy/OC_Hook.php","line":110,"function":"postUnshared","class":"OC\\Encryption\\HookManager","type":"::"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/Share/Share.php","line":376,"function":"emit","class":"OC_Hook","type":"::"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/Share/Share.php","line":302,"function":"unshareItem","class":"OC\\Share\\Share","type":"::"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/apps/files_sharing/lib/ExpireSharesJob.php","line":77,"function":"unshare","class":"OC\\Share\\Share","type":"::"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/BackgroundJob/Job.php","line":52,"function":"run","class":"OCA\\Files_Sharing\\ExpireSharesJob","type":"->"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/BackgroundJob/TimedJob.php","line":59,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/vhosts/mydomain.de/nextcloud/cron.php","line":127,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/vhosts/mydomain.de/nextcloud/lib/private/Files/Filesystem.php","Line":901,"CustomMessage":"Error while running background job (class: OCA\\Files_Sharing\\ExpireSharesJob, arguments: )"},"userAgent":"--","version":"20.0.13.1"}
{"reqId":"nCgN0po3J8tk1yx3Fhsw","level":2,"time":"2021-11-26T16:31:03+00:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":"Could not connect to appstore: cURL error 28: Operation timed out after 60000 milliseconds with 602100 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)","userAgent":"--","version":"20.0.13.1"}
{"reqId":"ouWvSJ2J43umLZwBviSd","level":2,"time":"2021-11-29T16:46:03+00:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":"Could not connect to appstore: cURL error 28: Operation timed out after 60001 milliseconds with 1113868 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)","userAgent":"--","version":"20.0.13.1"}
{"reqId":"rYAuzBveykmtr5369OTT","level":2,"time":"2021-12-02T17:00:33+00:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":"Could not connect to appstore: cURL error 7: Failed to connect to apps.nextcloud.com port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)","userAgent":"--","version":"20.0.13.1"}
```

**Comment by drudgede** [comment]
Another thing I figured out:

The  `occ status` returned the following output:

```
The current PHP memory limit is below the recommended value of 512MB.
  - installed: true
  - version: 20.0.13.1
  - versionstring: 20.0.13
  - edition:
```

However, I'm definitely on version 23/Hub II. What can be the cause that `occ status` shows the wrong version? I only have one instance of Nextcloud installed on this server.

**Comment by acsfer** [comment]
Well, this seems more like a bad setup than a bug.
You should try https://help.nextcloud.com to seek for help debugging your setup.

**Comment by drudgede** [comment]
I'm just maximally stupid.. I migrated my server ago since NC 22 and newer was not supported on my old server anymore. Forgot to modify the SSH alias and worked for days on the wrong server. 🤦‍♂️
Nevermind, thanks for the support.
