### ISSUE TITLE
Calendar event invitation automatically creates a new 'personal' calendar

### ISSUE THREAD

**Issue by icedieler** [nextcloud/server#3014]
### Steps to reproduce
1. Create a new event and invite attendees to it.

If an invited attendee doesn't have the personal calendar it automagically is created for her and the event is added to that newly created personal calendar.

### Expected behaviour
Nextcloud **must not** create new calendars in an invited attendee's account. The receiver of the invitation should decide to which calendar she wants to add the event.

### Actual behaviour
It appears that the server looks in an invited attendee's account for a calendar under the URL **dav/calendars/.../personal**. If it doesn't exist the calendar is created for the account and the event is added to that calendar. In our case the calendar URL is **dav/calendars/.../defaultcalendar**.

### Server configuration
**Operating system**:
Linux, Debian Jessie

**Web server:**
Apache 2

**Nextcloud version:** (see Nextcloud admin page)
11

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Nextcloud 10

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

**Comment by nickvergessen** [comment]
This is currently not supported. But you can adjust this manually in https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/Schedule/Plugin.php#L86-L92
By replacing `CalDavBackend::PERSONAL_CALENDAR_URI` with `'defaultcalendar'`

**Comment by p5n** [comment]
But I did not understand why it adds invitation to personal calendar, send invitation and this invitation cannot be accepted because of same UID already exists in personal calendar? I think this is a real bug.

**Comment by eibex** [comment]
I already have a calendar named "Personal", yet another "Personal" calendar is still created. Are we sure this is working as expected?
