### ISSUE TITLE
Add `'maximum.supported.desktop.version'` parameter

### ISSUE THREAD

**Issue by eibex** [nextcloud/server#30143]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Prevent issues like https://github.com/nextcloud/desktop/issues/4016 by allowing admins to test new versions. 

**Describe the solution you'd like**
Add `'maximum.supported.desktop.version'` config parameter, especially considering that `'minimum.supported.desktop.version'` already exists

**Describe alternatives you've considered**
Conflicts between local and remote should result in user prompts and/or remote having more importance. This alternative should be discussed in the desktop repository though. 

**Additional context**
n.a.

**Comment by eibex** [comment]
Relevant again with https://github.com/nextcloud/desktop/issues/5564

**Comment by joshtrichards** [comment]
Should be a relatively straightforward PR (I think!) for someone with light PHP skills that is looking to get involved or contribute to Nextcloud.

Basically this, slightly modified:

https://github.com/nextcloud/server/blob/master/apps/dav/lib/Connector/Sabre/BlockLegacyClientPlugin.php

I.e. An adaptation of the existing support for `minimum.supported.desktop.version` that already exists.

**Comment by flooxo** [comment]
I have added a configuration parameter, but I am not sure if these tests need to be adjusted as well. Maybe you can give me some advice?
For example here:
https://github.com/nextcloud/server/blob/master/apps/dav/tests/unit/Connector/Sabre/BlockLegacyClientPluginTest.php?#L77-L81

**Comment by skjnldsv** [comment]
Thanks @flooxo for the work on #41183 !
