### ISSUE TITLE
Files and folders disappear from Webinterface when using external storage

### ISSUE THREAD

**Issue by rogo19** [nextcloud/server#30154]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Mount NFS share on Synology TeraStation TS4800D from Raspberrypi and use it as local storage in Nextcloud.

2. Log in to Nextcloud and upload 40 Gigabytes of Photos in various folders from a Windows computer with drag and drop through the webinterface. You can also copy files and folders to storage by other means, and watch as your folder get populated in Nextcloud webinterface.

### Expected behaviour
You should be able to work with folders and files through the webinterface, and synchronize to desktop and mobile client.

### Actual behaviour
When you are done uploading, wait for 10, 20 minutes or an hour or so and experience that all of the uploaded content has disappeared from the webinterface. Content is still available on storage.

If you use a foldername in the addressbar of your browser, you can access the folder, but it is empty. If you then use a filename in the addressbar to get to a file, you can view it, and the file and folder stays visible in Nextcloud.

If you have set up sync between your windows computer and Nextcloud, Nextcloud client will delete the files and folders on your windows computer as they disappear from the webinterface.

### Server configuration

**Operating system:**
Raspbian GNU/Linux 11 (bullseye)

**Web server:**
Server version: Apache/2.4.51 (Raspbian)
Server built:   2021-10-07T17:49:44
**Database:**
Server:                 MariaDB
Server version:         10.5.12-MariaDB-0+deb11u1 Raspbian 11
Protocol version:       10
Connection:             Localhost via UNIX socket
Server characterset:    utf8mb4
Db     characterset:    utf8mb4
Client characterset:    utf8
Conn.  characterset:    utf8
UNIX socket:            /run/mysqld/mysqld.sock

**PHP version:**
PHP 7.4.25 (cli) (built: Oct 23 2021 21:53:50) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)
23.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/latest.tar.bz2

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - circles: 23.0.0
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_external: 1.15.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - user_ldap</summary>

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

 "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.0.10",
        "overwrite.cli.url": "https:\/\/example.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
NFS
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
</details>

### Client configuration
**Browser:**
Brave 1.32.113 Chromium: 96.0.4664.45
**Operating system:**
Windows 11 Home 21H2 (22000.348)
#### Web server error log
<details>
<summary>Web server error log</summary>

[error.log](https://github.com/nextcloud/server/files/7676126/error.log)

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

[nextcloud.log](https://github.com/nextcloud/server/files/7676183/nextcloud.log)

</details>

#### Browser log
<details>
<summary>Browser log</summary>

a) The javascript console log
[1638967207969.log](https://github.com/nextcloud/server/files/7676096/1638967207969.log)

</details>

**Comment by Glandos** [comment]
May be linked to #20995

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
