### ISSUE TITLE
404 on avatars and previews on activity tab

### ISSUE THREAD

**Issue by TheColin21** [nextcloud/server#30165]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Have a Nextcloud instance with multiple users, files_downloadactivity extension and users with avatars
2. upload an image and make another user download a file
3.  take a look at the activity tab

### Expected behaviour
User avatars should be displayed and there should be previews for newly uploaded images

### Actual behaviour
User avatars and previews return a 404 error

### Server configuration

**Operating system:** Ubuntu 20.04

**Web server:** Apache behind Nginx reverse proxy

**Database:** MariaDB 10

**PHP version:** 8.0

**Nextcloud version:** 23.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** upgraded since (estimated) 19

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - apporder: 0.13.0
  - audioplayer: 3.2.2
  - breezedark: 23.0.0
  - bruteforcesettings: 2.2.0
  - camerarawpreviews: 0.7.15
  - checksum: 1.1.3
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - extract: 1.3.3
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_antivirus: 3.2.2
  - files_downloadactivity: 1.12.0
  - files_external: 1.15.0
  - files_mindmap: 0.0.25
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_texteditor: 2.14.0
  - files_trackdownloads: 1.11.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - files_zip: 1.0.0
  - firstrunwizard: 2.12.0
  - imageconverter: 1.3.2
  - impersonate: 1.10.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.1
  - maps: 0.1.9
  - metadata: 0.15.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - onlyoffice: 7.2.1
  - password_policy: 1.13.0
  - passwords: 2021.12.20-build4303
  - photos: 1.5.0
  - previewgenerator: 3.4.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - ransomware_protection: 1.12.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.0
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "clnp.cloud",
            "cloud.clnp.eu",
            "cloud.saef-zf.de",
            "cloud.ti19.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.0.10",
        "overwrite.cli.url": "https:\/\/clnp.cloud",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "sendmail",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "updater.release.channel": "stable",
        "loglevel": 0,
        "maintenance": false,
        "theme": "",
        "app_install_overwrite": [
            "camerarawpreviews",
            "files_texteditor",
            "extract",
            "documentserver_community",
            "previewgenerator",
            "imageconverter",
            "apporder",
            "breezedark",
            "bruteforcesettings",
            "checksum",
            "files_downloadactivity",
            "files_trackdownloads",
            "files_mindmap",
            "metadata",
            "onlyoffice",
            "twofactor_totp"
        ],
        "ldapIgnoreNamingRules": false,
        "default_language": "de",
        "default_locale": "de",
        "default_phone_region": "DE",
        "defaultapp": "files",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "allow_local_remote_servers": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Edge Chromium and Firefox tested

**Operating system:** Windows 11

#### Web server error log
<details>
<summary>Web server error log</summary>

```
2021-12-09 16:37:02	Error	clientIP	404	GET /avatar/account%20(IP%3A%20 userIP)/27 HTTP/1.0		Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.43	881	SSL/TLS-Zugriff für Apache
2021-12-09 16:37:02	Error	clientIP	404	GET /core/preview.png?file=/path/to/file.png&x=150&y=150&c=524486e0b6514e462d3c71f609151df4 HTTP/1.0		Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.55 Safari/537.36 Edg/96.0.1054.43	881	SSL/TLS-Zugriff für Apache
2021-12-09 16:37:02	Error	clientIP	404	GET /avatar/user%20(IP%3A%20client IP)/27 HTTP/1.0
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
 Failed to load resource: the server responded with a status of 404 ()
/avatar/user%20(IP%3A%20client IP)/27:1 
        
       Failed to load resource: the server responded with a status of 404 ()
preview.png:1 
```
</details>

**Comment by TheColin21** [comment]
I already read about similar errors if `user_usage_report` is enabled. As you can see this app is not installed on my instance.

**Comment by r-t-f-m** [comment]
I have similar issue on installation that was working previously. Unfortunately, I do not know exactly when it stopped.

Preview of pictures when trying to change profile picture, for example, doesn't work. 

FreeBSD 13.0, Nextcloud 23.0.0, Nginx 1.20.1, PHP 8.0.15, MariaDB 10.6.4 
<details>
<summary>Apps</summary>
<pre>
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - announcementcenter: 6.1.1
  - breezedark: 23.2.0
  - calendar: 3.0.5
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.0.7
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - deck: 1.6.0
  - event_update_notification: 1.4.0
  - federatedfilesharing: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_texteditor: 2.14.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - flow_notifications: 1.2.0
  - impersonate: 1.10.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - maps: 0.1.10
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - notify_push: 0.3.0
  - oauth2: 1.11.0
  - onlyoffice: 7.3.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - previewgenerator: 3.4.1
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.2
  - support: 1.6.0
  - systemtags: 1.13.0
  - tasks: 0.14.2
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_external: 2.1.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflow_ocr: 1.23.1
  - workflowengine: 2.5.0
Disabled:
  - apporder
  - circles
  - encryption
  - federation
  - files_automatedtagging
  - files_external
  - recommendations
  - survey_client
  - user_ldap
</pre>
</details>

<details>
<summary>Config</summary>
<pre>
    $CONFIG = [
        'instanceid'                 => '********',
        'passwordsalt'               => '********',
        'secret'                     => '********',
        'trusted_domains'            =>
            [
                0 => 'cloud.********.**',
            ],
        'trusted_proxies'            =>
            [
                0 => '127.0.0.1',
                1 => '10.0.1.1/24',
            ],
        'datadirectory'              => '/usr/home/nextcloud/data',
        'overwrite.cli.url'          => 'https://cloud.********.**',
        'dbtype'                     => 'mysql',
        'version'                    => '23.0.0.10',
        'dbname'                     => 'nextcloud',
        'dbhost'                     => 'localhost',
        'dbport'                     => '',
        'dbtableprefix'              => 'oc_',
        'dbuser'                     => '********',
        'dbpassword'                 => '********',
        'logtimezone'                => 'UTC',
        'installed'                  => true,
        'filelocking.enabled'        => true,
        'memcache.local'             => '\\OC\\Memcache\\APCu',
        'memcache.distributed'       => '\\OC\\Memcache\\Redis',
        'memcache.locking'           => '\\OC\\Memcache\\Redis',
        'redis'                      =>
            [
                'host'    => '/tmp/redis.sock',
                'port'    => 0,
                'timeout' => 0.0,
            ],
        'user_backends'              =>
            [
                0 =>
                    [
                        'class'     => 'OC_User_IMAP',
                        'arguments' =>
                            [
                                0 => 'mail.********.**',
                                1 => 143,
                                2 => 'tls',
                                3 => null,
                                4 => false,
                            ],
                    ],
            ],
        'theme'                      => '',
        'maintenance'                => false,
        'updater.release.channel'    => 'stable',
        'appstoreenabled'            => true,        
        'apps_paths'                 =>
            [
                0 =>
                    [
                        'path'     => '/usr/local/www/nextcloud/apps',
                        'url'      => '/apps',
                        'writable' => true,
                    ],
                1 =>
                    [
                        'path'     => '/usr/local/www/nextcloud/apps-pkg',
                        'url'      => '/apps-pkg',
                        'writable' => false,
                    ],
            ],
        'app_install_overwrite'      =>
            [
                0  => 'tasks',
                1  => 'spreed',
                2  => 'contacts',
                3  => 'impersonate',
                4  => 'whiteboard',
                5  => 'user_external',
                6  => 'breezedark',
                7  => 'files_texteditor',
                8  => 'polls',
                9  => 'announcementcenter',
                10 => 'flow_notifications',
                11 => 'previewgenerator',
            ],
        'mysql.utf8mb4'              => true,
        'data-fingerprint'           => '********',
        'mail_smtpsecure'            => 'tls',
        'mail_sendmailmode'          => 'smtp',        
        'simpleSignUpLink.shown'     => false,
        'enable_previews'            => true,
        'enabledPreviewProviders'    =>
            [
                0  => 'OC\\Preview\\PNG',
                1  => 'OC\\Preview\\JPEG',
                2  => 'OC\\Preview\\GIF',
                3  => 'OC\\Preview\\BMP',
                4  => 'OC\\Preview\\XBitmap',
                5  => 'OC\\Preview\\MP3',
                6  => 'OC\\Preview\\TXT',
                7  => 'OC\\Preview\\MarkDown',
                //8 => 'OC\\Preview\\OpenDocument',
                9  => 'OC\\Preview\\Krita',
                10 => 'OC\\Preview\\PDF',
                11 => 'OC\\Preview\\Photoshop',
                12 => 'OC\\Preview\\Postscript',
            ],
        'debug'                      => false,
        'loglevel'                   => 2,
        'allow_local_remote_servers' => true,
    ];
</pre>
</details>

<details>
<summary>nginx error log</summary>
<pre>
2022/02/02 16:25:19 [error] 15670#224810: *89 open() "/usr/local/www/nextcloud/core/preview.png" failed (2: No such file or directory), client: client_ip, server: server_domain, request: "GET /core/preview.png?file=%2FPhotos%2Fxxxxx.jpg&x=100&y=100 HTTP/2.0", host: "server_domain"
</pre>
</details>

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
