### ISSUE TITLE
Enforce password on share-links for everybody except a defined group

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#30161]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

> The rule for creating external links to files only with a password is enabled for everyone, but only a certain group of users can create external links to files without a password. This come from Security.

**Describe the solution you'd like**
--> Basically the ability to enforce passwords for external link shares for every user _except_ when you are in a special group

**Describe alternatives you've considered**
none

**Additional context**
> basically we need to get the users group memberships in https://github.com/nextcloud/server/blob/ee987d74303cb38b864f96660cd2ee6d6552ebfd/lib/private/Share20/Manager.php#L1777-L1779 and then check it additionally against the configured groups.

- [ ] A few more locations in the code where this config setting is read separately from this one (like capabilities and some legacy things that might still be in use).

- [ ] We also need to clarify whether we need to also adjust the UI to add a new field "The following groups are exempted from password enforcement"

- [ ] Needs to be available within Q1 for customers (so backport to 23 will be needed, likely not for v22)

**Comment by CarlSchwan** [comment]
Implemented in https://github.com/nextcloud/server/pull/31194, I still need to adapt the tests and ideally add a few new ones to cover this case

**Comment by AndyScherzinger** [comment]
It'll need backporting, likely v22

@CarlSchwan does your latest comment imply that the feature is implemented besides the tests part? 👀

**Comment by CarlSchwan** [comment]
yes, it is. I'll try to find some time this week to fix the tests.
