### ISSUE TITLE
Incorrect status code by OCS spec as mentioned in the documentation

### ISSUE THREAD

**Issue by lil5** [nextcloud/server#30163]
### Steps to reproduce
1. send a curl to `/ocs/v2.php/cloud/capabilities?format=json`
2. see the response meta

### Expected behaviour
(JSON Path)
`$.ocs.meta.statuscode`
Should as defined by the [nextcloud documentation](https://docs.nextcloud.com/server/latest/developer_manual/core/externalapi.html#statuscodes) on statuscodes should be defined as `100` 

### Actual behaviour
(JSON Path)
`$.ocs.meta.statuscode`
returns `200`

**Nextcloud version:**  22.2.3 and 25.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
Docker

### Client configuration
Insomnia API Tester

**Operating system:** Linux

### Logs

```log
* Preparing request to http://localhost:8081/ocs/v2.php/cloud/capabilities?format=json
* Current time is 2021-12-09T12:32:09.002Z
* Using libcurl/7.73.0 OpenSSL/1.1.1i zlib/1.2.11 brotli/1.0.9 zstd/1.4.9 libidn2/2.3.1 libssh2/1.9.0 nghttp2/1.42.0
* Using default HTTP version
* Disable timeout
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 22 cookies
* Connection 28 seems to be dead!
* Closing connection 28
*   Trying ::1:8081...
* connect to ::1 port 8081 failed: Connection refused
*   Trying 127.0.0.1:8081...
* Connected to localhost (127.0.0.1) port 8081 (#29)

> GET /ocs/v2.php/cloud/capabilities?format=json HTTP/1.1
> Host: localhost:8081
> User-Agent: insomnia/2021.6.0
> OCS-APIRequest: true
> Accept: */*

* Mark bundle as not supporting multiuse

< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< Date: Thu, 09 Dec 2021 12:32:09 GMT
< Content-Length: 1240


* Received 1240 B chunk
* Connection #29 to host localhost left intact
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by lil5** [comment]
- Open your browser to a nextcloud server and record any `XHR` calls
- Click around until you find some requests to `/ocs/v2.php/*` or `/ocs/v1.php/*`
- View the json response body of each request

The response **ocs.meta.statuscode** should be one of the following, documented here https://docs.nextcloud.com/server/latest/developer_manual/core/externalapi.html#statuscodes

- 100 - successful
- 996 - server error
- 997 - not authorized
- 998 - not found
- 999 - unknown error

Instead the http status code is given. e.g.: `200`, `400`

I advise that the documentation be changed to fit the current implementation

**Comment by szaimen** [comment]
Which nc version did you test?

**Comment by lil5** [comment]
@szaimen v25.0.3

I've found that OwnCloud also shows **ocs.meta.statuscode** as being the same as the http status code.
https://doc.owncloud.com/server/next/developer_manual/core/apis/ocs-user-sync-api.html
