### ISSUE TITLE
E-Mail: Credentials in GUI does not work

### ISSUE THREAD

**Issue by Huster-at-github** [nextcloud/server#3019]
## Issue
* E-Mail is working correctly
* "Test Member 1" is not available inside sent e-mails
* Correct credentials are "nextcloudadmin@gmx.net"

## Config in GUI

![e-mail-config-gui](https://cloud.githubusercontent.com/assets/3857906/21826740/f216d68c-d788-11e6-9f8c-666288056edf.JPG)

## Config in config.php

[2017-01-10-config.php.txt](https://github.com/nextcloud/server/files/697520/2017-01-10-config.php.txt)

> 
> <?php
> $CONFIG = array (
>   'updatechecker' => false,
>   'passwordsalt' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxx',
>   'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
>   'trusted_domains' =>
>   array (
>     0 => 'localhost',
>     1 => '192.168.178.37',
>     2 => 'domain.my',
>     3 => 'owncloud',
>   ),
>   'datadirectory' => '/var/ocdata',
>   'overwrite.cli.url' => 'https://domain.my/',
>   'dbtype' => 'mysql',
>   'version' => '11.0.0.10',
>   'dbname' => 'owncloud_db',
>   'dbhost' => 'localhost',
>   'dbtableprefix' => 'oc_',
>   'dbuser' => 'oc_ocadmin',
>   'dbpassword' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxx',
>   'logtimezone' => 'Europe/Berlin',
>   'installed' => true,
>   'instanceid' => 'xxxxxxxxxxxx',
>   'appstore.experimentalogl.enabled' => 'true',
>   'mail_smtpmode' => 'smtp',
>   'mail_smtpauth' => 1,
>   'mail_smtpport' => '587',
>   'mail_smtphost' => 'mail.gmx.net',
>   'mail_smtpauthtype' => 'PLAIN',
>   'mail_from_address' => 'nextcloudadmin',
>   'mail_domain' => 'gmx.net',
>   'mail_smtpsecure' => 'tls',
>   'mail_smtpname' => 'old_nextcloudadmin@gmx.net',
>   'mail_smtppassword' => 'xxxxxxxx',
>   'preview_libreoffice_path' => '/usr/bin/libreoffice',
>   'memcache.local' => '\\OC\\Memcache\\Redis',
>   'filelocking.enabled' => 'true',
>   'memcache.distributed' => '\\OC\\Memcache\\Redis',
>   'memcache.locking' => '\\OC\\Memcache\\Redis',
>   'redis' =>
>   array (
>     'host' => '/var/run/redis/redis.sock',
>     'port' => 0,
>     'timeout' => 0,
>     'dbindex' => 0,
>   ),
>   'loglevel' => 1,
>   'debug' => false,
>   'maintenance' => false,
>   'htaccess.RewriteBase' => '/',
>   'singleuser' => false,
>   'theme' => '',
>   'updater.release.channel' => 'stable',
>   'appstore.experimental.enabled' => true,
>   'share_folder' => '/Shared with me',
> );

## Environment
- Mail template editor 0.2
- Browser Name and version: Firefox 50.1.0
- Operating System and version (desktop or mobile): Ubuntu 16.04
- Nextcloud version: 11.0.0
- PHP version: PHP 7.0.8-0ubuntu0.16.04.3
- Database version: mysql Ver 14.14 Distrib 5.7.16
- Are you using encryption: no

## Sorry ...
... for the display of config.php ...... I'm currently under Windows  👎

**Comment by nickvergessen** [comment]
You need to use the full email address in the credential field for gmx, not the user name.
I use that in my development instance and it works quite fine:
> ![administration_-_nextcloud_-_2017-01-11_12 27 31](https://cloud.githubusercontent.com/assets/213943/21846867/5b821efe-d7f9-11e6-8b16-f7d851b1cdeb.png)

**Comment by Huster-at-github** [comment]
Found the issue:
* KeeFox installed
* Several accounts for Nextcloud domain configured
* First account is "Test Member 1"

I deactivated "Test Member 1" in KeeFox.

Now the next KeeFox account "ocadmin" is filled in:

![e-mail-config-gui1](https://cloud.githubusercontent.com/assets/3857906/21862007/b5ec5a6a-d837-11e6-9eb6-51e14e5507a9.JPG)
So I resume:
* "Admin - Additional settings" triggers KeeFox to fill in the data

Is this a new issue?

**Comment by nickvergessen** [comment]
Kee fox will fill any username+password field I guess?
Just enter the correct credentials click on "Store credentials" and never save the settings again?
