### ISSUE TITLE
Wrong URL for address book CardDAV links?

### ISSUE THREAD

**Issue by despens** [nextcloud/server#302]
### Steps to reproduce
1. Go to Contacts app
2. Click "settings" cogwheel
3. Click link icon

### Expected behaviour
URL to a CardDAV endpoint should be shown
https://mah-servor.com/remote.php/carddav/addressbooks/despens/contacts/

### Actual behaviour
URL to a WebDAV endpoint is shown
https://mah-servor.com/remote.php/dav/addressbooks/users/despens/contacts/

### Server configuration
**Operating system**:
Ubuntu 14.04.4

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
PHP 5.5.9-1ubuntu4.14

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 9.0.50 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
From Owncloud

**Where did you install Nextcloud from:**
Downloaded tarball

**Signing status (Nextcloud 9.0 and above):**
unknown

```
No errors have been found.
```

**Comment by irgendwie** [comment]
Not a bug! Since ownCloud/Nextcloud 9.0, carddav and caldav were moved as backend into the core/server repository. The contacts and calendar apps are just JavaScript Frontends for that.
Therefore also the URLs changed!
