### ISSUE TITLE
CRUD permissions for internal & external shares

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#30227]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
For external shares we only have “read only” and “allow upload and editing”. 

**Describe the solution you'd like**
We would need to extend the permissions to have "read", “create”, “edit”, “delete”. In the past we went in the other direction, making share permissions less complex. So now we would revert it and add the complexity again (maybe as a config option so that admins can chose between simple and advanced share permissions?)

**Describe alternatives you've considered**
None

**Comment by szaimen** [comment]
cc @jancborchardt

**Comment by jancborchardt** [comment]
This could be put in the "Advanced settings" of sharing, as a "Custom permissions" checkbox which has subitems when checked.
If it is checked and modified from the defaults, on the top there will be another entry "Custom permissions". This one does not show by default and is merely informative. One can then quickly switch back to more general "View", "Edit" or "File drop".
![Link details vertical advanced with permissions](https://user-images.githubusercontent.com/925062/147103855-0ba85651-6b85-40c7-bdad-d89aa30f71f0.png)

**Comment by szaimen** [comment]
Though if upload+editing at the same time is used often which I suppose it would be (at least for private users), I think it shouuld be one of the default options as well...

**Comment by jancborchardt** [comment]
> Though if upload+editing at the same time is used often which I suppose it would be (at least for private users), I think it shouuld be one of the default options as well...

Could be – but do we have a reason to think that this is very common? Others definitely don’t offer it in their sets of standard options instead focusing on "View" and "Edit".

**Comment by szaimen** [comment]
> Could be – but do we have a reason to think that this is very common?

I'd say sharing your own pictures after an event with friends with a link and allowing them to upload files at the same time is a very common usecase but yeah...

Just wanted to bring this into focus ;)

**Comment by schiessle** [comment]
While working on the permissions and harmonize the permissions for internal and external shares it would be nice to add following permissions for internal share:

* read-only (no download, people just can view the documents in the browser)
* prevent printing (if possible)

This permissions are often requested for Virtual Data Room scenarios. Question is how to handle this permissions in the clients, my idea:

* desktop client would not sync this read-only files
* mobile clients could show the document in the embedded viewer if possible but not allow to download it

**Comment by AndyScherzinger** [comment]
This would change the scope and if not needed for this one I'd like them to be a separate issue because it doesn't just change the scope it also leads to new open issues that potentially slow down the implementation since they now also impact clients and a read-only file I think should still be "one way synced" server-to-client but any local change would have to be overwritten or create a warning or an error or else. So let's not add further aspects to the issue please.

**Comment by jancborchardt** [comment]
As also communicated with @artonge, for the record here:

The mockup for the extended permissions is based on the new sharing design https://github.com/nextcloud/server/issues/26691

If that is not ready, this is how the extended permissions could look like in the current view
- Submenu like we use in the menu of Deck
- Would be called "Custom permissions"
- subline could be "Create, read & update" (or whichever settings are set: "Create & read", "Read only", etc.)

![Deck actions submenu](https://user-images.githubusercontent.com/925062/150770038-ce37d428-07cf-406d-b233-ea9a0d43a088.gif)

**Comment by Mer0me** [comment]
Is Delete permission working ? https://github.com/nextcloud/server/issues/33917
