### ISSUE TITLE
after deleting a file in the "recent" view, the view must be refreshed

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/server#30234]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Usability issue
After deleting a file in the "recent" list, the file is still displayed

**Describe the solution you'd like**
after deleting a file in the "recent" list, the file should "disappear" , auto-refresh the view.

**Describe alternatives you've considered**
manually refresh/reload the page - works if you know that's an issue.

**Additional context**

**Comment by joshtrichards** [comment]
Similar to #29775 and #2742. And related to #1611, #28063, and #30135

**Comment by joshtrichards** [comment]
Duplicate of #29775 

@ferdiga Feel free to follow that issue :)
