### ISSUE TITLE
Some preview images are created incorrectly (partly grey)

### ISSUE THREAD

**Issue by PatricB** [nextcloud/server#30232]
When I visit my NextCloud (v22.2.3) server via the web interface and use the fotos app, I finde sometimes only "partly generated" preview images. 
I already disabled the previews and cleared the previews but with the next try again some of the images (most times different) get incorrectly previews.

Attached ist a example of a incorrect preview image.

**System:**
NextCloud: 22.2.3
OS: Linux 3.10.0
PHP: 7.4.26
MySQL: 10.3.24

<img width="179" alt="Bildschirmfoto 2021-12-12 um 21 31 22" src="https://user-images.githubusercontent.com/8460035/145728521-3468fec6-5287-4974-8986-ac99eaf57e1a.png">

**Comment by acsfer** [comment]
Is it possible to attach any (full) image to reproduce it?
