### ISSUE TITLE
[F2V] Migrate tags view

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#30249]
This ticket is part of the [files to vue migration](https://github.com/nextcloud/server/issues/28063)

### Goal
Unify and improve the system tags view

### QA
- [x] Display tags as folders (new API :warning:)
  - [ ] Implementing this as a DAV might give us opportunity to directly catch DELETE/PUT/MOVE requests
      BUT it will create issues with the paths considering a file located in `dav/USER/files/Photos/vacation.jpg` will be seen with a path like `dav/USER/tags/Summer 2021 vacations/vacation.jpg` while all the actions would expect the real dav path to work :thinking: 
  - [ ] Implementing this with OCS API will allow us to return different data like path that fixes the issue above
- [x] Opening the tag (folder) list all files belonging to it
- [ ] Actions
  - [ ] Rename
  - [ ] Delete
  - [ ] There is no sidebar for those tags/fake-folders, we need to check how to handle this :warning: 
- [x] Assess this global way of managing this. Considering it will use the same API as the real Files/Folders: https://github.com/nextcloud/server/issues/30070, check potential pitfalls of storing and caching "fake folders".
  - [x] Actions might be displayed while not theoretically supporting it on those folders

#### Future
- [ ] Show most recent/used tags in the navigation same as favorites

**Comment by icewind1991** [comment]
> BUT it will create issues with the paths considering a file located in dav/USER/files/Photos/vacation.jpg will be seen with a path like dav/USER/tags/Summer 2021 vacations/vacation.jpg while all the actions would expect the real dav path to work thinking

Given that the same problem would exist for other dav views, it probably makes sense to have the view expose some form of "canonical path" to give apps the "expected" path

**Comment by skjnldsv** [comment]
> Given that the same problem would exist for other dav views, it probably makes sense to have the view expose some form of "canonical path" to give apps the "expected" path

Well, the main issue is not about display, but about the context passed to the actions for example.
If I display a list of files in https://cloud.domain.com/apps/files/tags/Tagged-folder/file.ext, then the actions for a file should still apply to https://cloud.domain.com/remote.php/dav/user/files/path/to/file.ext
But I guess you can list files with ocs fine, and it can provide different paths. But we need to be careful about potential pitfalls :thinking:

**Comment by Spartachetto** [comment]
I do not see in the action list for the "virtual folders" defined by tags the possibility to share all the tagged files with one action. This functionality has been asked several times. If needed I can link the issues that ask for it.
