### ISSUE TITLE
Bad Request when creating a user without password

### ISSUE THREAD

**Issue by kagmole** [nextcloud/server#30241]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce

This error only occures if in your password policy (Settings > Security) you have the minimal password length set to 0.

1. Connect to the web Front-End of NextCloud
2. Go to: Users > New user
3. Try to create a user with a login, username and mail but no password

### Expected behaviour

A mail is sent to the new user with an invitation to create its password.

### Actual behaviour

A Bad Request occures. The error comes from `UserManager` which does not have a valid password for the account.  
It is because the fallback below does not work: the generated password is an empty string and not `null`. 

https://github.com/nextcloud/server/blob/e8ce7a3e5f0441623ec6d39873f20e8e70f38a37/apps/provisioning_api/lib/Controller/UsersController.php#L397-L408

Adding `|| $password === ''` would fix the issue.  
The workaround right now is to configure a greater minimal password length than 0.

**Comment by acsfer** [comment]
Mind to open a pull request?
