### ISSUE TITLE
Install deletes .user.ini file and breaks .htaccess

### ISSUE THREAD

**Issue by Skywalker-11** [nextcloud/server#3025]
### Steps to reproduce
1. Downlaod zip archive and extract to install folder
2. `chown -R www-data` on that folder
3. create sql db and user
4. open install page in browser, insert data

### Expected behaviour
After install there should be .htaccess and .user.ini files in the install directory

### Actual behaviour
During the install the .user.ini file is removed and .htaccess only contains this:

    #### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####

    ErrorDocument 403 //core/templates/403.php
    ErrorDocument 404 //core/templates/404.php

Because of this the integrity check fails.

### Server configuration
**Operating system**: 
Debian 8.6

**Web server:**
Apache 2.4.10

**Database:**
MariaDB 10.0.28

**PHP version:**
5.6.29-0+deb8u1

**Nextcloud version:** (see Nextcloud admin page)
11.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
Zip

**Signing status:**
<details>
<summary>Signing status</summary>

```Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .htaccess
	- FILE_MISSING
		- .user.ini

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => 11e2db30f0cf23df1b5aa1cdf329a8c88d253f86e43f9e7af1b30969eb0175030103b138e2f7ab7608c902bbb57a5d578c2c0ca09f3abf2ef83415f4bc6f6e20
                            [current] => cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
                        )

                )

            [FILE_MISSING] => Array
                (
                    [.user.ini] => Array
                        (
                            [expected] => 467d4f028c447895716a2b7859ed6e569f8ee34b87b51d73dab2e6a9ca4fbe63172c7be3e365ae864a60408286afcce852dd38ee544b61685ed4ee5e021fecb0
                            [current] => 
                        )

                )

        )

)

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

``` - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1

```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'ocqavz74tyfz',
  'passwordsalt' => '*****',
  'secret' => '****',
  'trusted_domains' =>
  array (
    0 => '****',
  ),
  'datadirectory' => '/opt/test-nextcloud/data',
  'overwrite.cli.url' => 'http://*****',
  'dbtype' => 'mysql',
  'version' => '11.0.0.10',
  'dbname' => '******',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '*****',
  'dbpassword' => '*****',
  'logtimezone' => 'UTC',
  'installed' => true,
);

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)
no

### Client configuration
**Browser:**
Chrome 55.0.2883.87

**Operating system:**
Win 10

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```

{"reqId":"RWkdCe2UQippKeUjtZot","remoteAddr":"192.168.90.23","app":"mysql.setup","message":"Specific user creation failed: An exception occurred while executing 'SELECT user FROM mysql.user WHERE user=?' with params [\"oc_skywalker\"]:\n\nSQLSTATE[42000]: Syntax error or access violation: 1142 SELECT command denied to user 'test-nextcloud'@'localhost' for table 'user'","level":3,"time":"2017-01-11T11:07:30+00:00","method":"POST","url":"\/index.php","user":"--","$
{"reqId":"RWkdCe2UQippKeUjtZot","remoteAddr":"192.168.90.23","app":"PHP","message":"file_get_contents(\/opt\/test-nextcloud\/.htaccess): failed to open stream: No such file or directory at \/opt\/test-nextcloud\/lib\/private\/Setup.php#434","level":3,"time":"2017-01-11T11:07:33+00:00","method":"POST","url":"\/index.php","user":"--","version":"11.0.0.10"}
{"reqId":"RWkdCe2UQippKeUjtZot","remoteAddr":"192.168.90.23","app":"no app in context","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"The given object name is invalid\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/test-nextcloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(892): OC\\\\Activity\\\\Event->setObject('files', 2, false)\\n#1 \\\/opt\\\/test-nextcloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(184): OCA\\\\Activity\\\\FilesH$
{"reqId":"RWkdCe2UQippKeUjtZot","remoteAddr":"192.168.90.23","app":"PHP","message":"copy(\/opt\/test-nextcloud\/.user.ini): failed to open stream: No such file or directory at \/opt\/test-nextcloud\/lib\/private\/IntegrityCheck\/Checker.php#196","level":3,"time":"2017-01-11T11:07:35+00:00","method":"POST","url":"\/index.php","user":"skywalker","version":"11.0.0.10"}
{"reqId":"RWkdCe2UQippKeUjtZot","remoteAddr":"192.168.90.23","app":"files","message":"Can't write upload limit to \/tmp\/oc_tmp_NzpB4j-folder\/.user.ini. Please check the file permissions","level":2,"time":"2017-01-11T11:07:35+00:00","method":"POST","url":"\/index.php","user":"skywalker","version":"11.0.0.10"}

```

</details>

**Comment by nickvergessen** [comment]
Can you post the result of `ls -la` before you submit the installation form?

**Comment by Skywalker-11** [comment]
drwxr-xr-x 15 www-data root      4096 Jan 11 12:43 .
drwxr-xr-x 16 root     root      4096 Jan 11 12:42 ..
drwxr-xr-x 29 www-data root      4096 Dez 13 13:25 3rdparty
drwxr-xr-x 41 www-data root      4096 Dez 13 13:24 apps
-rw-r--r--  1 www-data root      8868 Dez 13 13:23 AUTHORS
drwxr-xr-x  2 www-data root      4096 Jan 11 12:43 config
-rw-r--r--  1 www-data root      3638 Dez 13 13:23 console.php
drwxr-xr-x 16 www-data root      4096 Dez 13 13:25 core
-rw-r--r--  1 www-data root      5080 Dez 13 13:23 cron.php
drwxr-xr-x  2 www-data www-data  4096 Jan 11 12:43 data
-rw-r--r--  1 www-data root     40622 Dez 13 13:23 db_structure.xml
-rw-r--r--  1 www-data root      2635 Dez 13 13:23 .htaccess
-rw-r--r--  1 www-data root       179 Dez 13 13:23 index.html
-rw-r--r--  1 www-data root      2471 Dez 13 13:23 index.php
drwxr-xr-x  3 www-data root      4096 Dez 13 13:23 l10n
drwxr-xr-x  6 www-data root      4096 Dez 13 13:23 lib
-rw-r--r--  1 www-data root       283 Dez 13 13:23 occ
drwxr-xr-x  2 www-data root      4096 Dez 13 13:23 ocs
drwxr-xr-x  2 www-data root      4096 Dez 13 13:23 ocs-provider
-rw-r--r--  1 www-data root      3184 Dez 13 13:23 public.php
-rw-r--r--  1 www-data root      5431 Dez 13 13:23 remote.php
drwxr-xr-x  4 www-data root      4096 Dez 13 13:23 resources
-rw-r--r--  1 www-data root        26 Dez 13 13:23 robots.txt
drwxr-xr-x 11 www-data root      4096 Dez 13 13:23 settings
-rw-r--r--  1 www-data root      2110 Dez 13 13:23 status.php
drwxr-xr-x  3 www-data root      4096 Dez 13 13:23 themes
drwxr-xr-x  2 www-data root      4096 Dez 13 13:24 updater
-rw-r--r--  1 www-data root       163 Dez 13 13:23 .user.ini
-rw-r--r--  1 www-data root       259 Dez 13 13:25 version.php

**Comment by Skywalker-11** [comment]
Not sure why but this time the files weren't changed. 
The three times I tried before there was that issue

**Comment by nickvergessen** [comment]
You should use `chown -R www-data:www-data`

**Comment by Skywalker-11** [comment]
I tried install some more times and the issue did not happen again. So I close this.

**Comment by tinppaviiva** [comment]
I had the same issue, no idea what caused this. I have these messages in logging.

Warning	files	Can't write upload limit to /tmp/oc_tmp_KRSJXJ-folder/.user.ini. Please check the file permissions	2017-01-24T13:57:48+0200
Error	PHP	copy(/var/www/html/.user.ini): failed to open stream: No such file or directory at /var/www/html/lib/private/IntegrityCheck/Checker.php#196	2017-01-24T13:57:48+0200
Warning	files	Can't write upload limit to /tmp/oc_tmp_EE4tRH-folder/.user.ini. Please check the file permissions	2017-01-24T13:56:34+0200
Error	PHP	copy(/var/www/html/.user.ini): failed to open stream: No such file or directory at /var/www/html/lib/private/IntegrityCheck/Checker.php#196	2017-01-24T13:56:34+0200
Warning	files	Can't write upload limit to /tmp/oc_tmp_FkmnPO-folder/.user.ini. Please check the file permissions	2017-01-24T13:52:57+0200
Error	PHP	copy(/var/www/html/.user.ini): failed to open stream: No such file or directory at /var/www/html/lib/private/IntegrityCheck/Checker.php#196	2017-01-24T13:52:57+0200
Error	PHP	file_get_contents(/var/www/html/.htaccess): failed to open stream: No such file or directory at /var/www/html/lib/private/Setup.php#434	2017-01-24T13:52:53+0200

Copied the two files from archive manually to fix this error.

**Comment by kBite** [comment]
FTR: I experienced the same issue. After finishing the wizard, `.user.ini` is gone and `.htaccess` is reduced to:
```
#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####

ErrorDocument 403 //core/templates/403.php
ErrorDocument 404 //core/templates/404.php
```
I used `nextcloud-13.0.0.tar.bz2`. SHA1:
```
19af5eabd1ec34c0d7d7a7e3982e63b5bad586dc  nextcloud-13.0.0.tar.bz2
```
Copied the two files from archive manually to fix this error.

**Comment by michag86** [comment]
@kBite I had the same issue with fresh NC13 install. I've copied the files from /tmp/nextcloud/* to the target folder. But this doesn't includes the .htaccess and .user.ini. So this was the cause of the problem.

**Comment by TheColin21** [comment]
just had exactly the same problem while upgrading from 15.0.5 to 16
