### ISSUE TITLE
Aktualisierung auf 23.0.0 / Exception: Database error when running migration latest for app core

### ISSUE THREAD

**Issue by Raul1975** [nextcloud/server#30255]
Aktualisierung auf 23.0.0

Exception: Database error when running migration latest for app core

Detaillierte Protokollmeldungen 

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Repair MySQL collation
Not a mysql database -> nothing to do
Repair SQLite autoincrement
Copy data from accounts table when migrating from ownCloud
Drop account terms table when migrating from ownCloud
Das Datenbankschema wird aktualisiert
Exception: Database error when running migration latest for app core

Das Update ist fehlgeschlagen. Bitte melden Sie dieses Problem an die Nextcloud Community.

**Comment by acsfer** [comment]
Duplicate of https://github.com/nextcloud/server/issues/30226
