### ISSUE TITLE
TypeError: OCA\DAV\CalDAV\Reminder\ReminderService::parseCalendarData

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/server#30265]
Log Message:

![image](https://user-images.githubusercontent.com/24530680/145996887-31c114ec-2961-4349-8e29-f33a4df373c9.png)

Nextcloud Hub II (23.0.0)

**Comment by nursoda** [comment]
Same here in NC 23.0.0.10 – I see many of those ReminderService errors.
