### ISSUE TITLE
Failure when trying to import a deleted calendar event

### ISSUE THREAD

**Issue by juliusknorr** [nextcloud/server#30277]
## Steps taken:

- Delete a recurring event from the personal calendar
- See that it occurs in the trashbin
- Trying to reimport the calendar entry from the ics received by mail through Thunderbird

## Expected behavior

Either the calendar entry is restored or the new one is added

## Current behavior

Import fails, thunderbird error: CalDAV: Unexpected status adding item to Nextcloud Personal: 400

- Server version: 23.0.0
- Thunderbird version: 91.3.2

Happened on c.nc.com so there might be a log entry for my user that could be obtained.

I can share the ics file in private if needed.

@nextcloud/groupware

**Comment by ChristophWurst** [comment]
@miaulalala probably related to the fixed you currently work on, right?

**Comment by Joshndroid** [comment]
This error seems almost identical to the issue explained in #30096
Its currently killing my ability to set my work schedule usinf FlexR pro with davx5 and nextcloud caldav...

**Comment by ChristophWurst** [comment]
@miaulalala is working on this.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
