### ISSUE TITLE
Level 3 /appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead.

### ISSUE THREAD

**Issue by motoride** [nextcloud/server#30274]
I’m getting this error as a level 3 error for the files_external app. Other issues I’ve seen have this error in debug level and also usually 3rd party apps.

I have NC with installatron on my host. 22.2.3

I’ve deactivated the visibility on error level since it appears several times per second, but it’s still filling the log file. The issue has persisted through several version upgrades and I’ve tried deactivating and reactivating the app. I don’t seem to be able completely uninstall and reinstall the app.

Is anyone else experiencing this/any suggestions? 

Thanks,

**Comment by acsfer** [comment]
Can you post an log excerpt ?
Even if this is on Level 3 (wrongly IMO), it still a debug message and has zero impact on the functionalities.
https://github.com/nextcloud/server/issues/23046

**Comment by motoride** [comment]
Here is a log excerpt. 

I agree that it doesn't appear to impact functionalities, but since it is on the wrong level it means that if there are other error messages I'm not likely to see them since there is so much information on the level. 

Also, I'm not certain but it may impact performance since it seems to writes the error for each user every second, for every client, and it completely fills the log ever few days causing a new log file to be generated.

[log_excerpt.txt](https://github.com/nextcloud/server/files/7720002/log_excerpt.txt)

**Comment by joshtrichards** [comment]
Your provided logs all start with:

`/appinfo/app.php is not loaded`

rather than the title of your Issue which says:

`/appinfo/app.php is deprecated`

These are (somewhat) different situations (and also logged differently).

The deprecated message (what's in your subject, but not your provided logs) only logs at the debug level. The latter message logs at error level.

**Comment by joshtrichards** [comment]
This issue should be closed: Given all the other work that has occurred since this report occurred (to eliminate app.php + to reduce the logging + the "not loaded" variation being a local installation matter at this point).
