### ISSUE TITLE
Timed-based background jobs

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#30273]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Some background jobs are long-runners and create heavy load, this can also happen during office hours impacting the system's performance for users during such times.

**Describe the solution you'd like**
Provide a way to define a time when a background job should run.
e.g. to ensure heavy load jobs don't run during office hours but rather at night.

**Describe alternatives you've considered**
none

**Additional context**
-

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/server/pull/30945

**Comment by AndyScherzinger** [comment]
pinging @ChristophWurst to check if this would then fit your view of using this to implement the mail adoption, else best to align with the files team

**Comment by ChristophWurst** [comment]
> mail adoption

can you tell me which one specifically? We can certainly move any cleanup job. But inbox synchronization should remain an hourly job so when you open the app the cache is somewhat up to date.

I've opened https://github.com/nextcloud/groupware/issues/28 for our team.

**Comment by AndyScherzinger** [comment]
@ChristophWurst no idea tbh, it is referenced in some place in general and I believe given the cross reference for mail scheduling the outlined approach won't be an enabler for implementating scheduled mail sending.

**Comment by nickvergessen** [comment]
> can you tell me which one specifically? We can certainly move any cleanup job. But inbox synchronization should remain an hourly job so when you open the app the cache is somewhat up to date.

Yeah it's mostly about the "daily" things. Priority scanning comes to mind or pruning data

**Comment by blizzz** [comment]
that's done, afaik?! closing.
