### ISSUE TITLE
OCC doesn't work when APCu is enabled

### ISSUE THREAD

**Issue by StCyr** [nextcloud/server#30292]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Set 'memcache.local' => '\OC\Memcache\APCu',
2. sudo -u www-data php occ status

### Expected behaviour
root@bollu:/var/www/nextcloud# sudo -u www-data php occ status
  - installed: true
  - version: 23.0.0.10
  - versionstring: 23.0.0
  - edition:
  - maintenance: false
  - needsDbUpgrade: false
  - productname: Nextcloud
  - extendedSupport: false

### Actual behaviour
root@bollu:/var/www/nextcloud# sudo -u www-data php occ status
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)

I've followed the administration guide to install and upgrade my NC instance and from what I can see all needed php modules are there:

<Summary>root@bollu:/var/www/nextcloud# php -m
[PHP Modules]
apc
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imagick
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
</Summary>

<Summary>
root@bollu:/var/www/nextcloud# apt show php-apcu
Package: php-apcu
Version: 5.1.19+4.0.11-3
Priority: optional
Section: php
Maintainer: Debian PHP PECL Maintainers <team+php-pecl@tracker.debian.org>
Installed-Size: 190 kB
Provides: php7.4-apcu
Pre-Depends: php-common (>= 2:69~)
Depends: phpapi-20190902, libc6 (>= 2.14)
Recommends: php-apcu-bc
Suggests: php-gd
Conflicts: php-xcache, php-yac
Homepage: https://pecl.php.net/package/APCu
Download-Size: 44.9 kB
APT-Manual-Installed: yes
APT-Sources: http://deb.debian.org/debian bullseye/main amd64 Packages
Description: APC User Cache for PHP
 The APCu is userland caching: APC (Alternative PHP Cache) stripped of
 opcode caching after the deployment of Zend OpCache in PHP 5.5 as the
 primary solution to opcode caching in future versions of PHP.
 .
 The APCu is a fast solution for userland caching (and dumping) of PHP
 variables locally, it is not distributed like MemcacheD, but they can
 be used together for optimal caching.
</Summary>

### Server configuration

**Operating system:** Debian 11

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.4

**Nextcloud version:** 23.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Updater

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - calendar: 3.0.2
  - circles: 23.0.0
  - cloud_federation_api: 1.6.0
  - cms_pico: 1.0.16
  - comments: 1.13.0
  - contacts: 4.0.6
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - deck: 1.6.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.4
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - polls: 3.4.2
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.1
  - support: 1.6.0
  - systemtags: 1.13.0
  - text: 3.4.0
  - theming: 1.14.0
  - theming_customcss: 1.10.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.bollu.be"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "default_phone_region": "BE",
        "version": "23.0.0.10",
        "debug": true,
        "log_type": "syslog",
        "logfile": "",
        "loglevel": 0,
        "overwrite.cli.url": "https:\/\/nextcloud.bollu.be",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updater.release.channel": "stable",
        "theme": "",
        "mail_sendmailmode": "smtp",
        "app_install_overwrite": [
            "calendar",
            "issuetemplate",
            "spreed",
            "social",
            "contacts",
            "files_markdown",
            "files_texteditor",
            "polls"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.15.0",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "2146"
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "3.0.2",
            "types": ""
        },
        "circles": {
            "enabled": "yes",
            "installed_version": "23.0.0",
            "loopback_tmp_scheme": "https",
            "maintenance_run": "0",
            "maintenance_update": "{\"maximum\":3,\"3\":1637830776,\"2\":1637830776,\"1\":1637830776,\"5\":1632803654,\"4\":1632803654}",
            "migration_22": "1",
            "migration_22_1": "1",
            "migration_run": "0",
            "types": "filesystem,dav"
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "cms_pico": {
            "custom_plugins": "{\"PicoComments\":{\"name\":\"PicoComments\",\"type\":2,\"compat\":true}}",
            "custom_themes": "{\"ethereal\":{\"name\":\"ethereal\",\"type\":2,\"compat\":true},\"story\":{\"name\":\"story\",\"type\":2,\"compat\":true}}",
            "enabled": "yes",
            "installed_version": "1.0.16",
            "limit_groups": "[]",
            "plugins_etag": "nUZCDOMxYN",
            "system_plugins": "{\"PicoDeprecated\":{\"name\":\"PicoDeprecated\",\"type\":1,\"compat\":true}}",
            "system_templates": "{\"empty\":{\"name\":\"empty\",\"type\":1,\"compat\":true},\"sample_pico\":{\"name\":\"sample_pico\",\"type\":1,\"compat\":true}}",
            "system_themes": "{\"default\":{\"name\":\"default\",\"type\":1,\"compat\":true}}",
            "themes_etag": "YCgTdnGmrf",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "4.0.6",
            "types": "dav"
        },
        "contactsinteraction": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "dav"
        },
        "core": {
            "backgroundjobs_mode": "ajax",
            "enterpriseLogoChecked": "yes",
            "installedat": "1543267085.0022",
            "lastcron": "1639651720",
            "lastupdateResult": "[]",
            "lastupdatedat": "1639651718",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_host-meta": "social\/lib\/hostmeta.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "public_webfinger": "social\/lib\/webfinger.php",
            "scss.variables": "ecb0ac968dcb3cf842684733be34c74c",
            "theming.variables": "41545bc493ea402b7a9b19b640ab406b",
            "updater.secret.created": "1639644792",
            "vendor": "nextcloud"
        },
        "cospend": {
            "enabled": "no",
            "installed_version": "1.4.3",
            "types": ""
        },
        "dashboard": {
            "enabled": "yes",
            "installed_version": "7.3.0",
            "types": ""
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "installed_version": "1.21.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "types": "filesystem"
        },
        "deck": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "dav"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": ""
        },
        "federation": {
            "autoAddServers": "1",
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.18.0",
            "types": "filesystem"
        },
        "files_advancedsearch": {
            "enabled": "no",
            "installed_version": "0.0.1",
            "types": "filesystem"
        },
        "files_markdown": {
            "enabled": "no",
            "installed_version": "2.3.1",
            "types": ""
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "2.4.0",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "no",
            "installed_version": "2.12.0",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.16.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.12.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "18.4.0",
            "types": ""
        },
        "groupfolders": {
            "enabled": "no",
            "installed_version": "9.0.3",
            "types": "filesystem,dav"
        },
        "issuetemplate": {
            "enabled": "no",
            "installed_version": "0.7.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.8.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "yes",
            "installed_version": "1.11.4",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notes": {
            "enabled": "no",
            "installed_version": "2.5.1",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.11.1",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "authentication"
        },
        "ojsxc": {
            "apiSecret": "Q5s8NQLi6T1FE9t16aieEoi",
            "enabled": "no",
            "installed_version": "3.4.2",
            "types": "prelogin"
        },
        "password_policy": {
            "enabled": "yes",
            "enforceHaveIBeenPwned": "1",
            "enforceNumericCharacters": "1",
            "enforceUpperLowerCase": "1",
            "installed_version": "1.13.0",
            "minLength": "10",
            "types": "authentication"
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "polls": {
            "enabled": "yes",
            "installed_version": "3.4.2",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "readableLocation": "be",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "prevent_group_restriction"
        },
        "quicknotes": {
            "enabled": "no",
            "installed_version": "0.1.5",
            "types": ""
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "serverinfo": {
            "cached_count_filecache": "489848",
            "cached_count_storages": "11",
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "filesystem"
        },
        "social": {
            "address": "https:\/\/nextcloud.bollu.be",
            "cloud_url": "https:\/\/nextcloud.bollu.be\/index.php",
            "enabled": "no",
            "installed_version": "0.4.1",
            "social_address": "bollu.be",
            "social_url": "https:\/\/nextcloud.bollu.be\/index.php\/apps\/social\/",
            "types": "",
            "update_checked": "0.3"
        },
        "spreed": {
            "conversations_files_public_shares": "0",
            "enabled": "yes",
            "has_reference_id": "yes",
            "installed_version": "13.0.1",
            "project_access_invalidated": "1",
            "signaling_ticket_secret": "***REMOVED SENSITIVE VALUE***",
            "stun_servers": "***REMOVED SENSITIVE VALUE***",
            "types": "dav,prevent_group_restriction"
        },
        "support": {
            "SwitchUpdaterServerHasRun": "yes",
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "no",
            "installed_version": "1.2.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "no",
            "installed_version": "0.9.8",
            "types": ""
        },
        "text": {
            "enabled": "yes",
            "installed_version": "3.4.0",
            "types": "dav"
        },
        "theming": {
            "cachebuster": "2",
            "enabled": "yes",
            "installed_version": "1.14.0",
            "slogan": "***REMOVED SENSITIVE VALUE***",
            "types": "logging",
            "url": "***REMOVED SENSITIVE VALUE***"
        },
        "theming_customcss": {
            "cachebuster": "1637831134612",
            "customcss": ".app-talk .top-bar .primary {\n    display: none !important;\n}",
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": ""
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": ""
        },
        "updatenotification": {
            "calendar": "2.3.4",
            "cms_pico": "1.0.16",
            "contacts": "4.0.6",
            "core": "22.2.3.0",
            "cospend": "1.4.2",
            "deck": "1.5.5",
            "enabled": "yes",
            "files_rightclick": "0.15.1",
            "groupfolders": "10.0.0",
            "installed_version": "1.13.0",
            "issuetemplate": "0.7.0",
            "mail": "1.10.5",
            "polls": "3.2.0",
            "spreed": "12.1.2",
            "theming_customcss": "1.10.0",
            "types": "",
            "update_check_errors": "0"
        },
        "user_status": {
            "enabled": "yes",
            "installed_version": "1.3.1",
            "types": ""
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "weather_status": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.5.0",
            "types": "filesystem"
        },
        "workspace": {
            "enabled": "no",
            "installed_version": "0.9.3",
            "types": ""
        }
    }
}
</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

No

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No

### Client configuration
**Browser:** Firefox 95.0 64bits

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by ChristophWurst** [comment]
you have to disable it via config https://help.nextcloud.com/t/occ-wont-run-with-memcache-apcu/119724/3

**Comment by StCyr** [comment]
Damned! it's written in red in the admin manual 🙈 

Thanks Christoph
