### ISSUE TITLE
[RFC] FileInfo API

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#30297]
## Goals
Provides a way to add new properties to a Node and have a parity between the DAV properties and what a dedicated method could output via an OCS API request

### Use case
Whether I am processing a list of files from the dav Endpoint or returning a list of files from an ocs API endpoint, I expect the same kind of data to be available with the same property names for a back-front parity. Reducing the frontend complexity and increase code readibility.

### Issue example
Photos currently gets the list of files via SEARCH request, but get the gallery files set via ocs API, forcing us to do something like that:
https://github.com/nextcloud/photos/blob/aebb6e6695885cd5adf5d41c06a6b5c917f6cf7e/lib/Controller/AlbumsController.php#L107-L117
```php
$result[] = [
	'basename' => $isRoot ? '' : $node->getName(),
	'etag' => $node->getEtag(),
	'fileid' => $node->getId(),
	'filename' => $path,
	'lastmod' => $node->getMTime(),
	'mime' => $node->getMimetype(),
	'size' => $node->getSize(),
	'type' => $node->getType(),
	'hasPreview' => $this->previewManager->isAvailable($node),
];
```
https://github.com/nextcloud/photos/blob/aebb6e6695885cd5adf5d41c06a6b5c917f6cf7e/src/utils/fileUtils.js#L99-L122
```js
const genFileInfo = function(obj) {
	const fileInfo = {}

	Object.keys(obj).forEach(key => {
		const data = obj[key]

		// flatten object if any
		if (!!data && typeof data === 'object') {
			Object.assign(fileInfo, genFileInfo(data))
		} else {
			// format key and add it to the fileInfo
			if (data === 'false') {
				fileInfo[camelcase(key)] = false
			} else if (data === 'true') {
				fileInfo[camelcase(key)] = true
			} else {
				fileInfo[camelcase(key)] = isNumber(data)
					? Number(data)
					: data
			}
		}
	})
	return fileInfo
}
```
 ## Proposal
Create a dedicated php API for apps allowing to extend a file with some custom properties for a given namespace (e.g `http://nextcloud.org/ns`)

The API will ensure the following
- Register those new properties to the DAV ServerPlugin
  ```php
  $propFind->handle(self::MOUNT_TYPE_PROPERTYNAME, function () use ($node) {
      return $node->getFileInfo()->getMountPoint()->getMountType();
  });
   ```
- Register those properties to the FileInfo API
- Allow a node to be directly serialised to a similar output as the dav requests after processing from the webdav API
  ```js
  {
    basename: 'file.txt',
    path: '/folder/file.txt',
    ...
    'nc/has-preview': true,
  }
  ```
- A node library should be created to help matching both back and front I assume. Helping making sure all apps can manage that easily.

### Questions
- Should we drop or keep the namespace for the final serialised object ?
- If namespaced, what format do we use for the keys? 
	- `@nc/has-preview`
	- `nc/has-preview`
	- `nc-has-preview`
	- `nc_has-preview`
	- `@nc/hasPreview`
	- `nc/hasPreview`
	- `nc_hasPreview`
	- `nc-hasPreview`
	- ...
- ...

Comments, questions, arguments? @ChristophWurst @juliushaertl @nextcloud/server @nickvergessen

**Comment by ChristophWurst** [comment]
Is this related to the discussion we had two weeks ago? Was there a follow-up discussion? Because the proposal is quite different to the points we discussed there.

Wasn't the goal to have a common data structure that is also extensible?

**Comment by skjnldsv** [comment]
> Is this related to the discussion we had two weeks ago? Was there a follow-up discussion? Because the proposal is quite different to the points we discussed there.

No, this is straight from my notes from that discussion, is anything you had in mind missing/different? Can you explain a bit further?

**Comment by ChristophWurst** [comment]
What we discussed was different. We talked about standardizing the format of a file info object. The goal was to get the same object from any endpoint.

Data is from OCS/REST -> standardized JSON representation
Data is from DAV -> XML representation -> standardized JSON representation

The standard file info object and its default properties has to be defined somewhere, e.g. our dev docs. The definition would specify what the JSON representation looks like.

E.g.

```
{
    basename: '', // string
    lastmod: null, // int|null
}
```

Then we discussed how to handle custom props. Those will be possible to add to this object. Due to likely naming conflicts there should be a prefix to name space them.

The conversion from the DAV XML representation to the standardized JSON representation can be offered as a helper function in a node package. To work with custom props the helper function also needs to accept custom mappings of namespaces. E.g. so that an app can extend the file info for its purposes and use the extende file info object in the front-end.

On the back-end we can also offer a helper to generate a standard and extended file info object with the namespaced props.

Another point about the standardization. When a custom prop is used by more than one app, then it should be considered to be promoted as standard property, without the namespace. All helpers have to be adapted for this. So we probably need (semantic) versioning on the file info API.

**Comment by ChristophWurst** [comment]
I've refined my comment from yesterday.

**Comment by skjnldsv** [comment]
> E.g. when you get a v1.0 file info object you know that there is a `basename` prop. However, if you expect a `metadata` property then only v1.3 has it.
> 
> File objects created dynamically will be easy to handle. Where the versioning will help is whenever a file info is serialized (to cache, database, other) for later use.

This is interesting.
I initially thought about using the same way DAV does it. If you request a prop that is not her,e it's in the 404 section and not here. If the front end knows it straight away, it's easy to turn on and off features based on what prop is available (or namespaces)
If you see the metadata key, then you know it's here, and usable, else: :shrug:

**Comment by ChristophWurst** [comment]
Guess it comes down to preferences. A versioned, typed object would give you static guarantees but if you check for existence every time you use a property and also code the patch for the lack of it then it's fine to do duck typing.

**Comment by skjnldsv** [comment]
First front implementation done in 
https://nextcloud.github.io/nextcloud-files/classes/File.html
https://nextcloud.github.io/nextcloud-files/classes/Folder.html

**Comment by skjnldsv** [comment]
@CarlSchwan ideally, for all dav-related props, the backend should dictate the frontend yep.
Having a library or mappings between what exists and what can be requested to the backend would be nice.

For the new files app, there will be no plugins system.
Each view is responsible for their own data fetch and will have to return an array of [File](https://nextcloud.github.io/nextcloud-files/classes/File.html) and [Folder](https://nextcloud.github.io/nextcloud-files/classes/Folder.html).
