### ISSUE TITLE
Chunked uploads of two files with duplicate filenames results in data loss

### ISSUE THREAD

**Issue by Pytal** [nextcloud/server#30290]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Open a shared folder as userA in one tab and the same shared folder as userB in another tab
2. Have two files with the same filename, at least one should be a big file >10 MiB (the default size to trigger chunked uploading)
3. As userA start uploading the big file and as userB start uploading the second file

### Expected behaviour
Both files should upload successfully with auto-renaming done to resolve the duplicate filename conflict

### Actual behaviour
The last fully uploaded file overwrites the other file

### Server configuration
**Nextcloud version:** 23.0.0

**Comment by acsfer** [comment]
Is there a version created at least (if version app enabled)?
This does not invalidate the issue, but just to full understand it.

**Comment by Pytal** [comment]
@acsfer yes you're right there is a version created, then I guess this would be a UX issue as there is a conflict but it doesn't notify the user with something like the conflict dialog that is displayed if you try to upload a duplicate file after it's already in the filelist

**Comment by acsfer** [comment]
> but it doesn't notify the user with something like the conflict dialog that is displayed if you try to upload a duplicate file after it's already in the filelist

I've tried to reproduce it a few times with a 60Mb file, but I **always** get asked if i want to replace the previous file or keep it... 🤔

**Comment by acsfer** [comment]
Can you try to disable the app version and watch the behavior in that case?

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by mgallien** [comment]
I can confirm the following behavior.

- folder `a` is already existing and contain a big file names `big`
- user upload via web UI the same folder `a` with a new version of file `big` inside.
- no conflict dialog is shown for big files being uploaded via chunked upload

Users would expect the same dialog to be shown no matter the file size.

**Comment by szaimen** [comment]
Which nc version?
