### ISSUE TITLE
502 Bad Gateway on log/sign-in onto help.nextcloud.com

### ISSUE THREAD

**Issue by pavelkryl** [nextcloud/server#30302]
### Steps to reproduce
1. try to log in/sign in onto help.nextcloud.com
2. choose Google account to sign in
3. 502 BAD GATEWAY
4. Nobody from nextcloud team interested?? for half year?? https://help.nextcloud.com/t/login-with-google-doesnt-work/122053
 
### Expected behaviour
Sign in with Google oauth should suceed.

### Actual behaviour
502 BAD GATEWAY

Sorry for posting it here, but I refuse to create my millionth account just to post my question about failing nextcloud update, especially when there are unanswered requests to delete accounts on the help forum. Does anybody care?

**Comment by szaimen** [comment]
I think this is solved in the meantime
