### ISSUE TITLE
Carddav/Caldav api confusion

### ISSUE THREAD

**Issue by farao** [nextcloud/server#3031]
Hi!

I'm using Nextcloud with Lighttpd instead of Apache. Also, I'm syncing calendar and contacts using the Davdroid App as suggested by the Nextcloud Android App.

After updating from Nextcloud 10 to 11, my sync stopped working, because the APIs changed from /remote.php/carddav and /remote.php/caldav to /remote.php/dav. I thus introduced a rewrite of the urls in Lighttpd (not quite sure if this is the best way to solve the problem?).

But furthermore, also the lookup for calendars and contacts on the server failed because Davdroid was looking for them on remote.php/carddav/principals resp. /remote.php/caldav/principals (carddav and caldav were now rewritten to dav) but Nextcloud 11 seems to have changed those to /remote.php/dav/calendars and (-- url for contacts that I don't remember --).

If I was the only one using my Nextcloud instance, I would just delete and recreate my davdroid account on the phone. But I don't want all my users to have to do this. Is there another way than having a lot of hand written rewrite rules in lighttpd? And why is there no information about the API change on the Nextcloud upgrade page?

Thanks for your help,
Marius

**Comment by nickvergessen** [comment]
As far as I know, we just introduced remote.php/dav additionally. The old endpoints should still work as before. There code is also still in place.

**Comment by octotree** [comment]
I don't know it yet for sure, but I have the feeling that something else changed... With my desktop pc I have no problem at all, but my caldav and carddav syncs stopped working too :-/

**Comment by MorrisJobke** [comment]
It is know that lighttpd has issues with our DAV library - see http://sabre.io/dav/webservers/ for more info. We recommend to use a different web server for this.
