### ISSUE TITLE
 NC 23 occ segmentation fault

### ISSUE THREAD

**Issue by Amenophisphp** [nextcloud/server#30312]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.sudo -u www-data php occ

### Actual behaviour
segmentation fault

### Server configuration

Operating system: 
Ubuntu 20.04.3 LTS

Web server:
Apache 2.4.51

Database:
Mysql 5.7

PHP version:
8.0.13

Nextcloud version:
23.0.0

Updated from an older Nextcloud:
22.0.2

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Segmentation fault
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
<?php
$CONFIG = array (
  'defaultapp' => 'apporder',
  'instanceid' => '***',
  'passwordsalt' => '***',
  'secret' => '***',
  'trusted_domains' => 
  array (
    0 => 'cloud.marcleroi.be',
  ),
  'datadirectory' => '/var/www/html/nextcloud/data',
  'overwrite.cli.url' => 'http://cloud.marcleroi.be',
  'dbtype' => 'mysql',
  'version' => '23.0.0.10',
  'dbname' => 'nextclouddb',
  'dbhost' => ***',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => '***',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'nextcloud',
  'mail_domain' => 'marcleroi.be',
  'mail_smtphost' => '192.168.0.24',
  'mail_smtpport' => '25',
  'theme' => '',
  'maintenance' => false,
  'loglevel' => 2,
  'updater.release.channel' => 'stable',
  'onlyoffice' => 
  array (
    'verify_peer_off' => true,
    'jwt_header' => 'AuthorizationJwt',
  ),
  //'memcache.local' => '\\OC\\Memcache\\APCu',
  /*'memcache.local' => '\\OC\\Memcache\\Redis',
'memcache.locking' => '\\OC\\Memcache\\Redis',
'filelocking.enabled' => 'true',
'redis' =>
array (
'host' => '/var/run/redis/redis.sock',
'port' => 0,
'timeout' => 0.0,
),*/
  'app_install_overwrite' => 
  array (
    0 => 'apporder',
    1 => 'spreed',
    2 => 'fbsync',
    3 => 'activitylog',
    4 => 'issuetemplate',
    5 => 'radio',
    6 => 'twainwebscan',
    7 => 'occweb',
    8 => 'mindmap_app',
    9 => 'social',
    10 => 'ransomware_detection',
    11 => 'files_external_gdrive',
    12 => 'gluusso',
    13 => 'fulltextsearch',
    14 => 'fulltextsearch_elasticsearch',
    15 => 'files_fulltextsearch',
    16 => 'files_fulltextsearch_tesseract',
    17 => 'twofactor_email',
    18 => 'ocr',
    19 => 'breezedark',
    20 => 'unsplash',
    21 => 'cookbook',
    22 => 'drawio',
    23 => 'epubreader',
    24 => 'files_ebookreader',
    25 => 'deck',
    26 => 'facerecognition',
  ),
  'has_rebuilt_cache' => true,
  'mail_sendmailmode' => 'smtp',
  'mail_smtpauthtype' => 'PLAIN',
  'default_phone_region' => 'BE',
  'allow_local_remote_servers' => true,
);

</details>

**Are you using external storage, if yes which one:** local/smb

**Are you using encryption:**
no
**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Firefox 95.0
**Operating system:**
Linux Mint 20.2
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"wreQiJlKd3etlDfvaeHm","level":2,"time":"2021-12-16T11:10:04+00:00","remoteAddr":"","user":"--","app":"OC\\Log\\Rotate","method":"","url":"--","message":"Log file \"/var/www/html/nextcloud/data/nextcloud.log\" was over 104857600 bytes, moved to \"/var/www/html/nextcloud/data/nextcloud.log.1\"","userAgent":"--","version":"23.0.0.10"}
{"reqId":"Anm7K6yZEq2k97KivbWb","level":2,"time":"2021-12-16T15:57:49+00:00","remoteAddr":"94.109.159.178","user":"--","app":"user_ldap","method":"DELETE","url":"/ocs/v2.php/apps/notifications/api/v2/push","message":"Bind failed: 49: Invalid credentials","userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v13.0.0","version":"23.0.0.10"}
{"reqId":"Anm7K6yZEq2k97KivbWb","level":2,"time":"2021-12-16T15:57:50+00:00","remoteAddr":"94.109.159.178","user":"--","app":"user_ldap","method":"DELETE","url":"/ocs/v2.php/apps/notifications/api/v2/push","message":"Bind failed: 49: Invalid credentials","userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v13.0.0","version":"23.0.0.10"}
{"reqId":"Anm7K6yZEq2k97KivbWb","level":2,"time":"2021-12-16T15:57:50+00:00","remoteAddr":"94.109.159.178","user":"--","app":"core","method":"DELETE","url":"/ocs/v2.php/apps/notifications/api/v2/push","message":"Login failed: 'test' (Remote IP: '94.109.159.178')","userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v13.0.0","version":"23.0.0.10"}
{"reqId":"OxUYl7zwhLwx2hKPtTWd","level":2,"time":"2021-12-17T03:58:01+00:00","remoteAddr":"172.16.1.252","user":"--","app":"user_ldap","method":"DELETE","url":"/ocs/v2.php/apps/notifications/api/v2/push","message":"Bind failed: 49: Invalid credentials","userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v13.0.0","version":"23.0.0.10"}
{"reqId":"OxUYl7zwhLwx2hKPtTWd","level":2,"time":"2021-12-17T03:58:02+00:00","remoteAddr":"172.16.1.252","user":"--","app":"user_ldap","method":"DELETE","url":"/ocs/v2.php/apps/notifications/api/v2/push","message":"Bind failed: 49: Invalid credentials","userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v13.0.0","version":"23.0.0.10"}
{"reqId":"OxUYl7zwhLwx2hKPtTWd","level":2,"time":"2021-12-17T03:58:03+00:00","remoteAddr":"172.16.1.252","user":"--","app":"core","method":"DELETE","url":"/ocs/v2.php/apps/notifications/api/v2/push","message":"Login failed: 'test' (Remote IP: '172.16.1.252')","userAgent":"Mozilla/5.0 (Android) Nextcloud-Talk v13.0.0","version":"23.0.0.10"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by acsfer** [comment]
Check https://github.com/nextcloud/server/issues/25761

**Comment by Amenophisphp** [comment]
> Check #25761

Hello thanks.
I have already read this post :(
I have also a problem when I activate the cache (apcu or redis). I recieve an Internal Error on the web page

Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

**Comment by Amenophisphp** [comment]
The segmentation fault seem occur at 3rdparty/composer/autoload_real.php load

**Comment by Amenophisphp** [comment]
I found the cause: Backup 1.0.3 application.
No more segmentation fault after uninstallation
