### ISSUE TITLE
Allow to "Replace" a file so it doesn't lose its sharing link and permissions

### ISSUE THREAD

**Issue by luminous706** [nextcloud/server#30333]
**Is your feature request related to a problem? Please describe.**
Yes, when I upload a file and want to delete a previous one, such as a revised PDF document, I have to share it again with all my users.

**Describe the solution you'd like**
Right-click on the file, select "Replace", search the file to replace it with on the local PC, then upload the file with the same name, UID, and permissions/shares as the old one.

**Describe alternatives you've considered**
At the moment, sharing a directory with only this file in it is a workaround.

**Comment by eibex** [comment]
If you upload a file with the same filename it replaces your file without losing its sharing and other properties.
Just tested this to make sure.

**Comment by luminous706** [comment]
> If you upload a file with the same filename it replaces your file without losing its sharing (link sharing at least) and other properties. Just tested this to make sure.

Thanks, I had never tried that!

Closing this issue then.
