### ISSUE TITLE
🚀Feature Request: Granular File Permissions for App Passwords

### ISSUE THREAD

**Issue by larssorenson** [nextcloud/server#30331]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Currently, Nextcloud does not support a way to restrict access to files within a single account on a per-client (really, on a per-app-password) basis.

**Describe the solution you'd like**
When I set up a new client to sync with my Nextcloud account, I use an app password for authentication. However, I may not necessarily want that client to have access to all of the files in my account and I would like the ability to configure file permissions on a granular level for any given app password.

For example, I might set up a new laptop that I want to only use for work on a certain project. I may not want my other computers to be able to sync down the files from this project, or I may want this laptop to only be able to sync certain files related to this project.

Note, this is different from configuring the client to only sync certain files. I want an enforcement on the server-side to ONLY allow access to certain files.

**Describe alternatives you've considered**
There are two alternatives that I see as feasible at the moment, both have drawbacks and limitations.

1) Create individual user accounts that I only share certain files and folders to, on a per device/client basis. This is not ideal because it induces overhead and practically invalidates the use of app passwords. It may not easily allow for convenient synchronization of other resources (contacts, calendar, etc.).
For me, I only need it for one user, but in a multi-user scenario this isn't scalable in a practical way. Especially with non-admin users wanting to employ this type of security.

2) Use the single account to sync to one location, then employ a third party synchronization tool for point-to-point sync (e.g., rsync, borg, syncthing, etc.). This has the advantage of being less complex on the Nextcloud end and the third party tool may provide better synchronization than Nextcloud (e.g. only sync'ing deltas rather than whole files). However it creates a single point of failure in the end-to-end syncing process. Additionally, it requires the use of a third party tool which introduces configuration burden on the user-side which makes it unfriendly for non-tech-savvy users, it can have unexpected interactions with Nextcloud, it doesn't actually add a security control on the server-side, and it assumes a stable and convenient network path between the two devices.

**Additional context**
My specific use case is in Qubes OS, where I don't actually have convenient point-to-point network connectivity between the individual Qubes. Being able to set up a Nextcloud client on each Qube that has an app password only ACL'd to a specific folder would be incredibly convenient for isolating the individual work flows, per Qubes' security model.

Happy to chat more about this feature and its use cases.
Thanks!

**Comment by larssorenson** [comment]
Bearing in mind I lack context on specifics of Nextcloud internals, I envision an implementation (for anyone interested) should be something along the lines of:

1. Add an ACL in the database (if an appropriate one doesn't already exist, perhaps leverage the sharing infrastructure?)
2. Each entry in the ACL is an Allow or Deny that maps to a specific file or folder and to a specific identity's app password
3. Hook the file synchronization API to check the ACL and allow/deny appropriately
4. Default deny if an ACL isn't explicitly configured
5. Expose a UI to configure these permissions

**Comment by jsalatiel** [comment]
It works be great if we could get this. If granular permission for files is too much, at least "per folder app-password" would be great.

**Comment by Digi92** [comment]
I think the issue https://github.com/nextcloud/server/issues/2866 means the same as this.

**Comment by jospoortvliet** [comment]
Duplicate of https://github.com/nextcloud/server/issues/2866 - as this has an interesting discussion I liked to it.
