### ISSUE TITLE
Bandwidth cap when switching from NC18 to any newer version

### ISSUE THREAD

**Issue by bcantera** [nextcloud/server#30334]
When you use any version superior to NC18 on docker, you get a bandwidth cap to more or less 30MB/s (over gigabit network).

Step to reproduce:
1- Deploy and setup NC18 server (in docker container) and client
2- Copy a big ISO file to NC folder locally and wait for it to sync. You will see that it will take advantage of all your gigabit link (more or less 90MB/s upload speed)
3- Deploy and setup NC19 server or any newer version, on same server infrastructure and reconfigure client for it
4- Copy a big ISO file to NC folder locally and wait for it to sync. You will see that it will transfer at 30MB/s max (upload speed)
5- If you switch back to NC18, full speed is again available

What I tested:
- Network bottlenecks: iperf directly to NC server containers shows me that gigabit speed is perfectly capable.
- I ran the following command to check disk speed on both containers (NC18 and newer):  dd if=/dev/zero of=test.bin bs=1M count=1024. Disk write speed also checked and it is not an issue
- Upload chunks, in any case I see 96MB file chunks when uploading, so no difference there
- Set up php memory limit and php max file size to a higher level, nothing changes

### Expected behaviour
NC should use all avaliable bandwitdth

### Actual behaviour
NC use 30-40% of available bandwidth

### Server configuration

**Operating system:**
Debian - Docker

**Web server:**
Apache (which comes by default in NC docker image)

**Database:**
Mariadb (separate container)

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by bcantera** [comment]
Excellent news!!

I just deployed a fresh new docker container with NEXTCLOUD_VERSION: 25.0.3

And it works flawlessly!! Now it uses all the available gigabit connection, thank you for the update and the fix! Now I can move the project to NC again 

Cheers
