### ISSUE TITLE
Nextcloud renaming files to "...conflict..." destroys open SQLite databases

### ISSUE THREAD

**Issue by daniel-hmc** [nextcloud/server#3036]
In case of a file conflict, the NextCloud client renames local files to a new file name containing the term "conflict". This automatic renaming leads to problems, if the original file is opened in an application. So this renaming should be avoided. Maybe instead download the server version of the file and save that under the new name ...conflict....
IN my case, I used the information manager "NoteCase Pro" with its ncdb file format (SQLite-based). During the file was opened, Nextcloud renamed the data file. I worked a lot on the file, did changes and additions, saved them from time to time. A few hours later, I realized that none of the changes really made it into the file, all work from last hours was lost. Analysis turned out that Nextcloud renamed the file, so SQLite journal writes could not be applied to the actual database file.

Renaming is an official way to destroy an SQLite database: https://www.sqlite.org/howtocorrupt.html#_unlinking_or_renaming_a_database_file_while_in_use

### Steps to reproduce
1. Use a program that uses SQLite as its data file format, open and edit a file (e.g. NoteCase Pro with ncdb data file format)
2. simulate a Nextcloud conflict situation's renaming procedure, e.g. by manually renaming the local data file of that application to another name
3. Try to save changes to the file

### Expected behaviour
Ideally, the application continues to work as it should (and NextCloud would not rename local files on its own).
Or the client could have an interactive conflict solution mode, so that the user is presented a dialog where he can choose what to do BEFORE nextcloud client renames the file (skip, exclude, rename and continue, ...)

### Actual behaviour
NextCloud client renames the *local* file in a conflict situation and the SQLite-file-using application is not able anymore to save changes to file. It may or may not have error handling for that situation, if it has not, user will see the problem only when it's too late and data loss has happened. Also if it has, it may already be too late to handle the problem, when the application is reported write errors from the SQLite engine.

### Server configuration
**Operating system**:
Mac OS X 10.11.6 (also reproducible under Linux, not sure about Windows, as SQLite files are locked when opened so that they cannot be renamed manually. Not sure if Nextcloud could rename the file then.

**Web server:**
irrelevant

**Database:**
irrelevant 

**PHP version:**
irrelevant 

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud version: Nextcloud 11.0.0 (stable)
Client version: Version 2.2.4 (build 1)

** Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
-->  No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - dav: 1.1.1
  - encryption: 1.4.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - comments
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - user_external
  - user_ldap
  - user_saml

**The content of config/config.php:**
hermocom@kronos:~/domains/daniel-hertrich.photo/httpdocs/wordpress/cloud$ php occ config:list system
{
    "system": {
        "instanceid": "ocyha2qe6jid",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "daniel-hertrich.photo",
            "www.daniel-hertrich.photo"
        ],
        "datadirectory": "\/srv\/www\/vhosts\/hermocom.com\/domains\/daniel-hertrich.photo\/owncloud9_data",
        "overwrite.cli.url": "http:\/\/daniel-hertrich.photo\/cloud",
        "dbtype": "mysql",
        "version": "11.0.0.10",
        "dbname": "dhf_owncloud9",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "daniel",
        "mail_smtpmode": "php",
        "mail_domain": "daniel-hertrich.photo",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2,
        "htaccess.RewriteBase": "\/cloud"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "ldap" namespace. 

### Client configuration
**Browser:**
- irrelevant

**Operating system:**
Mac OS X 10.11.6

**Comment by nickvergessen** [comment]
More of a client issue, @rullzer what do you think? Close here and reopen in the client?
But then again I don't even see a way to work around this.

**Comment by daniel-hmc** [comment]
oops, sorry, I didn't know there is an own tracker for the clients. :-)
Otherwise I had put it there. 

No way around it? What do you think about my suggestion about a workaround? (not renaming the local file, but instead download the server file and save that under the "...conflict..." name and leaving the local file untouched)?

**Comment by MorrisJobke** [comment]
> oops, sorry, I didn't know there is an own tracker for the clients. :-)
> Otherwise I had put it there.

Yes - this is clearly a client repo. Technically we use the same client as ownCloud. So maybe open the ticket there and ask for the background for this way of handling conflicts. I guess there was a reason to do it in that way. https://github.com/owncloud/client



> No way around it? What do you think about my suggestion about a workaround? (not renaming the local file, but instead download the server file and save that under the "...conflict..." name and leaving the local file untouched)?

At least from the server side we can't do much :/ Regarding the conflict file we need to check with the client devs what they think about this.

I will close this one here as this is a client problem. Thanks for your report anyway, @daniel-hmc

**Comment by daniel-hmc** [comment]
Thanks, done:
https://github.com/owncloud/client/issues/5521
