### ISSUE TITLE
[Bug] Fresh Install with No "memory_limit" in php7.4.conf causing error about memory limit.

### ISSUE THREAD

**Issue by seanmitch** [nextcloud/server#30373]
New Ubuntu 20.04 LTS Install, getting error on "Administration > Overview" page at "/index.php/settings/admin/overview".
<img width="1124" alt="Screen Shot 2021-12-22 at 12 26 46 AM" src="https://user-images.githubusercontent.com/20157708/147040339-9642b1e6-9c65-4cb6-bb9d-f7ad32ba90f3.png">

When trying to resolve by editing the PHP config at "/etc/php/7.4/cli/php.ini", "memory_limit" is set to -1 which according to the documentation, specifies no limit. The desired functionality would be to have the server just check if the system has more than 512 MB available to it for memory with os calls, and only error when the OS doesn't have 512 MB free.
<img width="551" alt="Screen Shot 2021-12-22 at 12 22 24 AM" src="https://user-images.githubusercontent.com/20157708/147039927-0e00d4a7-7bc3-4639-8c21-edf9e995d2c6.png">

Yes, I have more than 512 MB of memory free.
![image](https://user-images.githubusercontent.com/20157708/147040086-b9998a87-c3c8-42d7-a0d5-5f49bc98ec4e.png)

**Comment by acsfer** [comment]
> When trying to resolve by editing the PHP config at "/etc/php/7.4/cli/php.ini"...
You're editing the CLI ini file. THis is wrong.
Edit `/etc/php/7.4/fpm/php.ini` (or similar).

**Comment by seanmitch** [comment]
> > When trying to resolve by editing the PHP config at "/etc/php/7.4/cli/php.ini"...
> 
> You're editing the CLI ini file. This is wrong. Edit `/etc/php/7.4/fpm/php.ini` (or similar).

After editing “/etc/php/7.4/apache2/php.ini”, it had the memory_limit set to “128M”. I set it to “-1” and the issue was resolved as expected. Thank you, closing issue.
