### ISSUE TITLE
VerifyUserData job always gets readded

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#30374]
In cases the VerifyUserData job fails or terminates immediately (due to no validation being required) the job is instantly readded again due tot he updateAccount logic. It seems that there was some change to fetch the old account data now in an indexed array rather then one with the property names as key. In the following $oldMail will just always be null and the job gets readded:

![image](https://user-images.githubusercontent.com/3404133/147065046-2c1ab10b-c21c-4b81-899a-341f4174b590.png)

Steps to reproduce:
- set `'lookup_server' => '',` in config.php
- run the cron job runs and is removed due to https://github.com/nextcloud/server/blob/f49a7512837ff5d297d9c75389a55660f0556272/apps/settings/lib/BackgroundJobs/VerifyUserData.php#L99

Expected:
- There is no job present anymore after the removal

Actual:
- The job gets added again right away

@blizzz @Pytal As a quick fix i thought about just bringing back the property name array key but I don't feel familiar enough with the code to tell if that is a good idea right away. Maybe you have a better insight there.

Could potentially cause quite some cron delay or unnecessary load on systems with larger user count.

**Comment by Pytal** [comment]
The account properties were switched from an associative to indexed array to allow for multiple email entries https://github.com/nextcloud/server/pull/27474

Fixed by https://github.com/nextcloud/server/pull/30491

**Comment by Pytal** [comment]
Account properties were switched from an associative to indexed array to allow for multiple email addresses https://github.com/nextcloud/server/pull/27474

**Comment by Pytal** [comment]
Fixed by https://github.com/nextcloud/server/pull/30491

**Comment by Pytal** [comment]
Wasn't able to test as the job wasn't run with the repro steps so let me know if this fixes it @juliushaertl

**Comment by Pytal** [comment]
Wasn't able to test as the job wasn't run after doing the repro steps so let me know if this fixes it @juliushaertl

**Comment by Pytal** [comment]
Wasn't able to test this as the job wasn't run on my instance after doing the repro steps so let me know if this fixes it @juliushaertl

**Comment by Pytal** [comment]
Account properties were switched from an associative to indexed array to allow for multiple email addresses https://github.com/nextcloud/server/pull/27474

Wasn't able to test this as the job wasn't run on my instance after doing the repro steps so let me know if https://github.com/nextcloud/server/pull/30491 fixes it @juliushaertl
