### ISSUE TITLE
Color for each icon folder

### ISSUE THREAD

**Issue by emillod** [nextcloud/server#3037]
Hello.
I think you should add option to change icon color for each folder. This is really great function to recognize folders.

**Comment by MariusBluem** [comment]
Marking Folders is important. But this is something you could do with Tags ... but colorizing would not make any sense in my opinion, becsuse it would be synced to the clients (Windows, ...) without an large implementation. 

Maybe we could do something similar to macOS Tags ... but the folder-colour should stay ;)

@nextcloud/designers But what do you think 🤔

**Comment by skjnldsv** [comment]
Agreed with MariusBluem. Don't really like the idea of colors.
What we can do is link a tag to a color and apply it. I could agree with that.

**Comment by jancborchardt** [comment]
Additionally, relying on color for marking as a main feature will not work for people with visual impairment like color blindness. Right now you can use favorites, which clearly differentiates important folders and makes them easily recognizable and filterable.

**Comment by emillod** [comment]
I don't know.. Maybe you're right and this idea is bad solution for marking folders. I'm using Google Drive from many years and i used to those colors, because i can fast recognize folders. Now I'm using Nextcloud on two servers and I'm really grateful for this script :)

**Comment by MariusBluem** [comment]
@jancborchardt from this accessibility point of view - closing this feature request here 😉 We should keep Nextcloud as easy to use as possible for everybody ♿️ ...

**Comment by skjnldsv** [comment]
Well I kinda liked the idea of assigning a color to a tag now! 😈

**Comment by jancborchardt** [comment]
@skjnldsv ideally especially when syncing tags with the desktop, colors should be preserved. I think @nickvergessen had some script or PR some time ago for that. (Especially for macOS this makes sense where colored tags are used by default.) However keep in mind that tagging is not something the majority of people use.

**Comment by Espina2** [comment]
I would love to have support for tagging in macOS.
