### ISSUE TITLE
Wrong time when I use command user:lastseen or files:transfer-ownership

### ISSUE THREAD

**Issue by ParametricIce** [nextcloud/server#30387]
1) When I use the command:
`occ user:lastseen admin`
It returns incorrect time. (-3 hours from my local time)
**Example output:**
`admin last login: 23.12.2021 05:33`
But now system time is 23.12.2021 08:33

2) Also when I transfered a files the time is incorrect.
`occ files:transfer-ownership user1 user2`
**Example of folder name in mailbox's user2:**
_transfered from user1 on 2021-12-23 07-00-52_
But now system time is 2021-12-23 10-00-52

Server has the correct time.
Log files have the correct time.
So my local TimeZone is UTC+03:00. And I think the above commands don't include the TimeZone (UTC only).

### Server configuration
**Operating system:**
Centos 
**Web server:**
Apache
**Database:**
Mariadb
**PHP version:**
7.4
**Nextcloud version:**
21.0.7

**Comment by kmotseki** [comment]
I am experiencing the same issue on Nextcloud 24.0.5. lastseen result is 2 hours behind. 'logtimezone' is set correctly. php.ini set to correct timezone. Server (Ubuntu 20.04 LTS) set to correct timezone, MySQL set to use system timezone.

**Comment by joshtrichards** [comment]
Related: #44641

**Comment by nooblag** [comment]
Yes, please, I have a [PR open](https://github.com/nextcloud/server/pull/44666) to address this problem, but the developers seem to have strong views about hardcoding UTC. Any help convincing them to change their mind would be useful :)
