### ISSUE TITLE
Logging in with email generates errors in log

### ISSUE THREAD

**Issue by mariuslangz** [nextcloud/server#3038]
Hi!

I've seen on my Nextcloud-server that if a user logs in with their registered e-mail, then they are able to logging in, but it throws errors to the server log. I've seen this in all versions up to 10.0.2, and I'm still experiencing the issue. If I ask users to log in with username only, then there's no errors in the log anymore.

### Server configuration
**Operating system**: Ubuntu 16.04.1

**Web server:** Apache

**Database:** Mysql 14.14

**PHP version:** 7.0.8

**Nextcloud version:** 10.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Clean install

**Where did you install Nextcloud from:** Downloaded zip file from webpage

**Log entries:**
Warning	core	Login failed: 'marius@domain' (Remote IP: '10.0.0.0')	2017-01-12T07:02:53+00:00	--
Warning	core	Login failed: 'rolf@domain' (Remote IP: '10.0.0.0')	2017-01-12T06:59:17+00:00	--
Warning	core	Login failed: 'rolf@domain' (Remote IP: '10.0.0.0')	2017-01-12T06:59:11+00:00	--
Warning	core	Login failed: 'rolf@domain' (Remote IP: '10.0.0.0')	2017-01-12T06:59:11+00:00	--
Warning	core	Login failed: 'rolf@domain' (Remote IP: '10.0.0.0')	2017-01-12T06:59:10+00:00	--
Warning	core	Login failed: 'rolf@domain' (Remote IP: '10.0.0.0')	2017-01-12T06:59:11+00:00	--
Warning	core	Login failed: 'rolf@domain' (Remote IP: '10.0.0.0')	2017-01-12T06:59:10+00:00	--

**Comment by nickvergessen** [comment]
Yeah I see that too.
Will have a look if we can prevent that message from being written, if it was an email login.

**Comment by MorrisJobke** [comment]
Other occurrence also reported in #2631

**Comment by stetie** [comment]
I still see this bug in Nextcloud 13.0.5. Please reopen.

**Comment by MorrisJobke** [comment]
> I still see this bug in Nextcloud 13.0.5. Please reopen.

This is then a different issue. Please open a new ticket and fill out the issue template.
