### ISSUE TITLE
[meta] where / how to ask for new features / apps etc

### ISSUE THREAD

**Issue by jerabaul29** [nextcloud/server#30380]
This may be a quite "meta" question: how to ask for new features / apps etc? Is there / could there be a "users requests" repository or something like that?

For example, I would love to see a NextCloud app that allows to host a gitlab server "as an app" with just the click of a button to install and some help for setting it up. I have no idea if / how this is possible, to ask for: where / how could this be discussed?

**Comment by szaimen** [comment]
Hello, feel free to ask for new apps/features here: https://help.nextcloud.com/c/apps/26
Cheers!
