### ISSUE TITLE
Exception: Database error when running migration latest for app core

### ISSUE THREAD

**Issue by ofedotov51** [nextcloud/server#30381]
Hi! App is down! Update error! 

Обновление до версии 23.0.0

Exception: Database error when running migration latest for app core
Подробные журналы 
Подготовка к обновлению
Установлен отладочный уровень протоколирования
Включён режим обслуживания
Шаг восстановления: Repair MySQL collation
Информация восстановления: Not a mysql database -> nothing to do
Шаг восстановления: Repair SQLite autoincrement
Шаг восстановления: Copy data from accounts table when migrating from ownCloud
Шаг восстановления: Drop account terms table when migrating from ownCloud
Выполняется обновление схемы базы данных
Exception: Database error when running migration latest for app core
Обновление не удалось. Сообщите об этой проблеме сообществу Nextcloud.

**Comment by smasharov** [comment]
у меня онлайн последние два раза тоже не обновлялось, из консоли прошло без проблем.
`occ upgrade` пробовали?

**Comment by ofedotov51** [comment]
> у меня онлайн последние два раза тоже не обновлялось, из консоли прошло без проблем. `occ upgrade` пробовали?

да. вот такой вывод 
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Exception: Database error when running migration latest for app core
Update failed
Maintenance mode is kept active
Resetting log level

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
