### ISSUE TITLE
Index for table 'oc_filecache' is corrupt

### ISSUE THREAD

**Issue by Bevito** [nextcloud/server#30395]
Hi, 
I just upgraded from Nextcloud 22.2.3 to Nextcloud 23.0.0 and the occ db:add-missing-indices reports some errors and doesn't end properly.

### Steps to reproduce
1. Launch `sudo -u www-data php occ db:add-missing-indices` after updating from Nextcloud 22.2.3 to 23.0.0

### Expected behaviour
The database maintenance script should update everything without errors.

### Actual behaviour
occ report errors : 

```
Check indices of the share table.
Check indices of the filecache table.
Adding additional size index to the filecache table, this can take some time...
Filecache table updated successfully.
Adding additional path index to the filecache table, this can take some time...

In ExceptionConverter.php line 114:
                                                                                                                                                   
  An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1034 Index for table 'oc_filecache' is corrupt; try to repair it  
                                                                                                                                                   

In Exception.php line 26:
                                                                                                    
  SQLSTATE[HY000]: General error: 1034 Index for table 'oc_filecache' is corrupt; try to repair it  
                                                                                                    

In Connection.php line 82:
                                                                                                    
  SQLSTATE[HY000]: General error: 1034 Index for table 'oc_filecache' is corrupt; try to repair it  
                                                                                                    

db:add-missing-indices
```

### Server configuration

**Operating system:**
Debian 11.2

**Web server:**
Apache 2.4 (2.4.51-1~deb11u1)

**Database:**
MariaDB (10.5.12-0+deb11u1)

**PHP version:**
7.4 (7.4.25-1+deb11u1)
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud Hub II (23.0.0)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 22.2.3

**Where did you install Nextcloud from:**
Auto updater 

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - bruteforcesettings: 2.3.0
  - circles: 23.0.0
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - drawio: 1.0.2
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_external: 1.15.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - onlyoffice: 7.2.1
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - tasks: 0.14.2
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_ldap: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - announcementcenter
  - encryption
  - groupfolders
  - quota_warning
  - 
**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.0.10",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "maxZipInputSize": 1073741824,
        "allowZipDownload": true,
        "theme": "",
        "overwrite.cli.url": "https:\/\/cloud.iut-orsay.fr",
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "default_language": "fr",
        "default_phone_region": "FR",
        "defaultapp": "files,dashboard",
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 0,
        "trusted_domains": [
            "cloud.iut-orsay.fr"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "15, auto",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "dbindex": 0,
            "timeout": 0
        },
        "onlyoffice": {
            "jwt_secret": "REMOVED SENSITIVE VALUE",
            "jwt_header": "REMOVED SENSITIVE VALUE"
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "ldapUserCleanupInterval": "60",
        "updater.release.channel": "stable",
        "mysql.utf8mb4": true,
        "mail_sendmailmode": "smtp",
        "app_install_overwrite": [
            "printer"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}


### Client configuration
**Browser:**
Mozilla Firefox 91.4.1esr

**Operating system:**
Linux Debian 11.2

**Comment by acsfer** [comment]
Check https://www.heelpbook.net/questions/topic/mysql-error-1034-index-for-table-db-is-corrupt-try-to-repair-it/#postid-181

**Comment by Bevito** [comment]
Hi, 
Thank your for your link.
I checked the table : 

MariaDB [nextcloud]> CHECK TABLE `oc_filecache`;
+------------------------+-------+----------+----------+
| Table                  | Op    | Msg_type | Msg_text |
+------------------------+-------+----------+----------+
| nextcloud.oc_filecache | check | status   | OK       |
+------------------------+-------+----------+----------+
1 row in set (7 min 27.515 sec)

I rerun the occ script : 
sudo -u www-data php occ db:add-missing-indices

Check indices of the share table.
Check indices of the filecache table.
Adding additional path index to the filecache table, this can take some time...

In ExceptionConverter.php line 114:
                                                                                                                                                   
  An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1034 Index for table 'oc_filecache' is corrupt; try to repair it  
                                                                                                                                                   

In Exception.php line 26:
                                                                                                    
  SQLSTATE[HY000]: General error: 1034 Index for table 'oc_filecache' is corrupt; try to repair it  
                                                                                                    

In Connection.php line 82:
                                                                                                    
  SQLSTATE[HY000]: General error: 1034 Index for table 'oc_filecache' is corrupt; try to repair it  
                                                                                                    

db:add-missing-indices

I tried to repair the table, even if it seems not needed : 

MariaDB [nextcloud]> REPAIR TABLE `oc_filecache`;
+------------------------+--------+----------+---------------------------------------------------------+
| Table                  | Op     | Msg_type | Msg_text                                                |
+------------------------+--------+----------+---------------------------------------------------------+
| nextcloud.oc_filecache | repair | note     | The storage engine for the table doesn't support repair |
+------------------------+--------+----------+---------------------------------------------------------+
1 row in set (0.000 sec)

MariaDB [nextcloud]> SHOW CREATE TABLE `oc_storages`;
+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table       | Create Table                                                                                                                                                                                                                                                                                                                                                                                       |
+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| oc_storages | CREATE TABLE `oc_storages` (
  `id` varchar(64) COLLATE utf8mb4_bin DEFAULT NULL,
  `numeric_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `available` int(11) NOT NULL DEFAULT 1,
  `last_checked` int(11) DEFAULT NULL,
  PRIMARY KEY (`numeric_id`),
  UNIQUE KEY `storages_id_index` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=17175 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPRESSED |
+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.000 sec)

**Comment by acsfer** [comment]
**Make a backup** (mysqldump) an try this:

```ALTER TABLE `oc_filecache` ENGINE = InnoDB;```

and also check you MySQL error log.

**Comment by Bevito** [comment]
Thanks @acsfer 

I found the source of the problem.
When i tried the sql command 'ALTER TABLE xxx'  I had an error : ERROR 1878 (HY000): Temporary file write failure.

In the end, MariaDB use /tmp as tmpdir and in my case, /tmp is a tmpfs dir, wich is too small for this kind of operation.
I set a bigger filesystem as tmpdir and the command occ db:add-missing-indices worked like a charm.

Thank you very much.

**Comment by JkBoyo** [comment]
> Check https://www.heelpbook.net/questions/topic/mysql-error-1034-index-for-table-db-is-corrupt-try-to-repair-it/#postid-181

So I'm running into a similar issue and this link is now deprecated.  Anyone have another link that shows how to fix the DB table?

**Comment by kcshaw** [comment]
> **Make a backup** (mysqldump) an try this:
> 
> `` ALTER TABLE `oc_filecache` ENGINE = InnoDB; ``
> 
> and also check your MySQL error log file.

For what it's worth, this worked for me when trying to address a "Index for table 'oc_filecache' is corrupt; try to repair it" error. Well, I did have to drop the ' around oc_filecache but that may be a syntax variant depending on the version one is running.
