### ISSUE TITLE
Try to remove Files External Onedrive to fix nextcloud internal server error problem.

### ISSUE THREAD

**Issue by mm10079** [nextcloud/server#30408]
This is my first report
If something worng,tell me.
thx
<img width="1632" alt="000" src="https://media.discordapp.net/attachments/895238106159124490/924673988226080768/14063080cac1853d.png?width=2685&height=1366">

### Steps to reproduce
1.Install External Storage: OneDrive
2.Not work,And buttom's text dosent change to display cancel
3.Try click button,The Web GUI stock
4.Reload the page
5.Web display 'internal server error problem'
6.In shell
7.Remove /usr/local/www/nextcloud/apps/files_external_onedrive
8.Remove /usr/ports/net/onedrive
9.internal server error problem has been fix
10.In 'Configuring External Storage' page, Lot of error Onedive file setting(Unknown: files_external_onedrive)
11.I cant remove those error file

### Expected behaviour
Fixed internal server error and nothing worng

### Actual behaviour
Fixed internal server error
In 'Configuring External Storage' page, Lot of error Onedive file setting(Unknown: files_external_onedrive)

### Server configuration

**Operating system:TrueNAS-12.0-U7**

**Web server:Ngnix(IDK)**

**Nextcloud version:23.0.0** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:fresh install**

**Where did you install Nextcloud from:Truenas/Plugin/iXsystems**

### Client configuration
**Browser:Chrome**

**Operating system:Windows 10**

**Comment by szaimen** [comment]
Hello, please report this to https://github.com/hevelius/files_external_onedrive
Thanks!
