### ISSUE TITLE
Set default sharing permissions still not working for me

### ISSUE THREAD

**Issue by QuentinWertz** [nextcloud/server#30414]
### Steps to reproduce
Set in /settings/admin/sharing default sharing permissions to active.

Create and share a folder to an external email address, i.e. a gmail account.
Check the real share permissons.

### Expected behaviour
Shared folder should be "writeable and editable".

### Actual behaviour
Shared folder is "read only".

## Server configuration detail

**Operating system:** Linux 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 10.3.31

**PHP version:** 

7.4.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 20.0.14 - 20.0.14.2

**Updated from an older Nextcloud/ownCloud or fresh install:** updated for years

**Where did you install Nextcloud from:** web-based

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.4
 - bruteforcesettings: 2.2.0
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.2
 - federatedfilesharing: 1.10.2
 - files: 1.15.0
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.2
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - nextcloud_announcements: 1.9.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - photos: 1.2.3
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - support: 1.3.0
 - systemtags: 1.10.0
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_ldap: 1.10.3
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.1
Disabled:
 - admin_audit
 - encryption
 - federation
 - files_downloadactivity
 - files_external
 - files_pdfviewer
 - files_retention
 - files_trashbin
 - files_versions
 - files_videoplayer
 - firstrunwizard
 - password_policy
 - quota_warning
 - survey_client

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
     ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/wolke.dhw.de",
    "dbtype": "mysql",
    "version": "20.0.14.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Berlin",
    "installed": true,
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "default_language": "de_DE",
    "default_locale": "de_DE",
    "knowledgebaseenabled": false,
    "enable_avatars": false,
    "allow_user_to_change_display_name": false,
    "lost_password_link": "disabled",
    "trashbin_retention_obligation": "3, 7",
    "theme": "",
    "maintenance": false,
    "loglevel": 2,
    "skeletondirectory": "",
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": "true",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "mail_smtpmode": "sendmail",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "updater.release.channel": "stable",
    "mysql.utf8mb4": true,
    "mail_sendmailmode": "smtp",
    "activity_expire_days": 30
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP

<details><summary>LDAP configuration (delete this par if not used)</summary>

```
User auth works...
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36 Edg/96.0.1054.62

**Operating system:** W10

## Logs

<details><summary>Web server error log</summary>

```
No error.
```
</details>

<details><summary>Nextcloud log</summary>

```
No log entry in timescale of sharing
```
</details>

<details><summary>Browser log</summary>

-
</details>

**Comment by QuentinWertz** [comment]
No idea?
No one?
Maybe fixed in 21.*?

**Comment by jdaviescoates** [comment]
I think this could be related to the fact you're sharing by email. See this thread over on the [Cloudron](https://cloudron.io/?refcode=5adcafc820c53c3d) forum:

https://forum.cloudron.io/post/43564

It seems links included in email shares are read-only!

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
