### ISSUE TITLE
Can't add folder shared by link

### ISSUE THREAD

**Issue by gjedeer** [nextcloud/server#3042]
### Steps to reproduce
1. Share a folder by link
2. Open the link while logged in as another user on the same server
3. Try adding that folder to your NC account

### Expected behaviour
IDEALLY: I click "add to your Nextcloud" and the folder appears in Shared
ACCEPTABLY: I enter myusername@mynextcloudinstance.com and the folder appears in Shared

### Actual behaviour
I enter myusername@mynextcloudinstance.com, I'm redirected to Calendar app (which is my default app), when I go to Files app the folder is not there.

5 minutes later I receive a notification from my desktop client that otheruser@mynextcloudinstance.com shared a folder with me.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Nginx

**Database:** SQLite

**PHP version:** 5.6

**Nextcloud version:** Nextcloud 11.0.0 (production)

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** occ update

**Signing status:**
<details>
Integrity checker has been disabled. Integrity cannot be verified.
</details>

(but I have no customizations)

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - external: 1.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - ownbackup: 16.11.0
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.1.2
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: true
Disabled:
  - admin_audit
  - encryption
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - user_external
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "datadirectory": "\/********************\/owncloud-data",
        "dbtype": "sqlite3",
        "version": "11.0.0.10",
        "installedat": "1328029564.0652",
        "lastupdatedat": "1342961822.3781",
        "installed": true,
        "instanceid": "51c89bd926532",
        "maintenance": false,
        "forcessl": true,
        "defaultapp": "calendar",
        "remote_core.css": "\/core\/minimizer.php",
        "remote_core.js": "\/core\/minimizer.php",
        "theme": "",
        "trusted_domains": [
*************************
        ],
        "share_folder": "\/Shared",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "127.0.0.1",
        "mail_smtpport": "25",
        "mail_smtptimeout": 10,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "log_type": "owncloud",
        "logfile": "owncloud.log",
        "check_for_working_webdav": false,
        "mail_smtpdebug": true,
        "mail_from_address": "owncloud",
        "mail_domain": "**********************",
        "enable_previews": true,
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "production",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "dbindex": 2
        }
    }
}

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 50.1

**Operating system:** Ubuntu 16.04

#### Web server error log
<details>
<summary>Web server error log</summary>
```
2017-01-12 12:22:56: (mod_fastcgi.c.2673) FastCGI-stderr: {"reqId":"VDvzNZh2wEnCdQxScxLG","remoteAddr":"**************","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-01-12T11:22:56+00:00","method":"POST","url":"\/index.php\/apps\/calendar\/v1\/config","user":"*********","version":"11.0.0.10"}
2017-01-12 12:23:07: (mod_fastcgi.c.2673) FastCGI-stderr: {"reqId":"N9PfBkmiVOedoFB6TYEM","remoteAddr":"**************","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-01-12T11:23:07+00:00","method":"POST","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/remote_shares\/pending\/1","user":"*********","version":"11.0.0.10"}
2017-01-12 12:23:53: (mod_fastcgi.c.2673) FastCGI-stderr: {"reqId":"L62Pn79T90PywHb847Q5","remoteAddr":"**************","app":"PHP","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","level":3,"time":"2017-01-12T11:23:53+00:00","method":"POST","url":"\/index.php\/apps\/calendar\/v1\/config","user":"admin","version":"11.0.0.10"}
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
{"reqId":"UWh5Jg4XVM3AN9RaabYp","remoteAddr":"","app":"PHP","message":"PHP Startup: Unable to load dynamic library '\/usr\/lib\/php\/20160303\/redis.so' - \/usr\/lib\/php\/20160303\/redis.so: undefined symbol: php_var_unserialize_init at Unknown#0","level":3,"time":"2017-01-12T11:15:01+00:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"GLpb5Aa9ym2RCyccB7cP","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\Redis not available for local cache","level":1,"time":"2017-01-12T11:30:01+00:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"GLpb5Aa9ym2RCyccB7cP","remoteAddr":"","app":"cli","message":"Memcache \\OC\\Memcache\\Redis not available for distributed cache","level":1,"time":"2017-01-12T11:30:01+00:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"GLpb5Aa9ym2RCyccB7cP","remoteAddr":"","app":"no app in context","message":"Invalidating session tokens older than 2017-01-11T11:30:03+00:00","level":0,"time":"2017-01-12T11:30:03+00:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"GLpb5Aa9ym2RCyccB7cP","remoteAddr":"","app":"no app in context","message":"Invalidating remembered session tokens older than 2016-12-28T11:30:03+00:00","level":0,"time":"2017-01-12T11:30:03+00:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
{"reqId":"GLpb5Aa9ym2RCyccB7cP","remoteAddr":"","app":"DeleteOrphanedSharesJob","message":"0 orphaned share(s) deleted","level":0,"time":"2017-01-12T11:30:03+00:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.  (unknown)
JQMIGRATE: Migrate is installed, version 1.4.0
```
</details>

**Comment by nickvergessen** [comment]
@schiessle any reason why that would not work with a different default app?

**Comment by schiessle** [comment]
Do you have a notification app enabled? You should see directly after the redirect a notification at the top left which will allow you to accept the share.

**Comment by gjedeer** [comment]
Possibly. I can work now, just wanted to report how confusing the process is. If you think otherwise just close the issue.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by schiessle** [comment]
> If you think otherwise just close the issue.

Let's keep it open and explore ways to improve it. Especially after we introduce internal shares which need to be accepted first we could create internal shares directly if people click on "Add to your Nextcloud" and enter a cloud id on the same server.

**Comment by gjedeer** [comment]
Going further, if you're logged in to the server perhaps you don't need to type your ID and the button could just create the share without asking for id.

On January 13, 2017 11:17:15 AM CET, "Björn Schießle" <notifications@github.com> wrote:
>> If you think otherwise just close the issue.
>
>Let's keep it open and explore ways to improve it. Especially after we
>introduce internal shares which need to be accepted first we could
>create internal shares directly if people click on "Add to your
>Nextcloud" and enter a cloud id on the same server.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/server/issues/3042#issuecomment-272408852

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by skjnldsv** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
