### ISSUE TITLE
LDAP user backend may throw exception if server is not available when counting users

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#30422]
According to the documentation `countUsers()` [returns either an int or false](https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/public/User/Backend/ICountUsersBackend.php#L36), but it does not throw any exception.

However, the LDAP user backend may throw an exception if the server is not available ([`User_Proxy`](https://github.com/nextcloud/server/blob/f3dcbfe146782d2c7dec8760651e79605ddc96e7/apps/user_ldap/lib/User_Proxy.php#L348) calls [`User_LDAP`](https://github.com/nextcloud/server/blob/f3dcbfe146782d2c7dec8760651e79605ddc96e7/apps/user_ldap/lib/User_LDAP.php#L593), which in turn may call [`Access`](https://github.com/nextcloud/server/blob/f3dcbfe146782d2c7dec8760651e79605ddc96e7/apps/user_ldap/lib/Access.php#L1021)); it should return `false` instead to match the expected behaviour, as clients of the user backend might not catch exceptions when calling `countUsers()`, which could lead to internal server errors.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
