### ISSUE TITLE
Share API returns truncated circleId in share_with value

### ISSUE THREAD

**Issue by jmptbl** [nextcloud/server#30458]
I hope the brevity of this report can be forgiven - it's a really simple bug fix.

The Share API is returning a truncated circleId in share_with in share elements of IShare::TYPE_CIRCLE.  Example API outputs below.

Nextcloud 22.2.3
PHP 8.0.13

Never upgraded, fresh install.

Attached patch fixes it for me: [share-api-circleid.txt](https://github.com/nextcloud/server/files/7797056/share-api-circleid.txt)

Share element from the Share API showing the truncation in share_with: [share-api-example.txt](https://github.com/nextcloud/server/files/7797062/share-api-example.txt)

The Circle element in share_with above, but from the Circle API: [circle-api-example.txt](https://github.com/nextcloud/server/files/7797063/circle-api-example.txt)

**Comment by acsfer** [comment]
Do you mind open a pull request for review?

**Comment by jmptbl** [comment]
@acsfer done!

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
