### ISSUE TITLE
Mergerfs pool as an External storage not working

### ISSUE THREAD

**Issue by mikulik86** [nextcloud/server#30465]
### Steps to reproduce
When mounting Mergerfs pool as an local external storage (as described here: https://docs.nextcloud.com/server/22/admin_manual/configuration_files/external_storage/local.html), Nextcloud accepts new setting, but shows no files.

However, when mounting hard drives them selves (for example /mnt/NAS_1 or /mnt/NAS_2 instead of /mnt/NAS ) files are shown.
Also if I point to anything within the mount point (for example /mnt/NAS/Movies) it works fine. It's just the root of the mount that fails.

### Expected behaviour
Nextcloud showing files present in root of Mergerfs pool mounted as local external storage.

### Actual behaviour
Nextcloud not showing files present in root of Mergerfs pool mounted as local external storage.

## Server configuration detail

**Operating system:** Linux 5.11.0-43-generic #47~20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64

**Webserver:** Apache/2.4.41 (Ubuntu) (apache2handler)

**Database:** mysql 10.3.32

**PHP version:** 

7.4.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, pdo_sqlite, apc, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 22.2.3

**Updated from an older Nextcloud/ownCloud or fresh install:** an older Nextcloud

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

No errors have been found.

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.8.0
 - activity: 2.15.0
 - circles: 22.1.1
 - cloud_federation_api: 1.5.0
 - comments: 1.12.0
 - contactsinteraction: 1.3.0
 - dashboard: 7.2.0
 - dav: 1.19.0
 - federatedfilesharing: 1.12.0
 - federation: 1.12.0
 - files: 1.17.0
 - files_external: 1.13.0
 - files_pdfviewer: 2.3.1
 - files_rightclick: 1.1.0
 - files_sharing: 1.14.0
 - files_trashbin: 1.12.0
 - files_versions: 1.15.0
 - files_videoplayer: 1.11.0
 - firstrunwizard: 2.11.0
 - issuetemplate: 0.7.0
 - logreader: 2.7.0
 - lookup_server_connector: 1.10.0
 - nextcloud_announcements: 1.11.0
 - notifications: 2.10.1
 - oauth2: 1.10.0
 - password_policy: 1.12.0
 - photos: 1.4.0
 - privacy: 1.6.0
 - provisioning_api: 1.12.0
 - recommendations: 1.1.0
 - serverinfo: 1.12.0
 - settings: 1.4.0
 - sharebymail: 1.12.0
 - support: 1.5.0
 - survey_client: 1.10.0
 - systemtags: 1.12.0
 - text: 3.3.0
 - theming: 1.13.0
 - twofactor_backupcodes: 1.11.0
 - updatenotification: 1.12.0
 - user_status: 1.2.0
 - viewer: 1.6.0
 - weather_status: 1.2.0
 - workflowengine: 2.4.0
Disabled:
 - admin_audit
 - bruteforcesettings
 - encryption
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.1.100",
        "mikulik86.duia.eu"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "22.2.3.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "default_phone_region": "CZ",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "overwritehost": "mikulik86.duia.eu",
    "htaccess.RewriteBase": "\/nextcloud",
    "filesystem_check_changes": 1,
    "overwrite.cli.url": "https:\/\/mikulik86.duia.eu\/nextcloud",
    "app_install_overwrite": [
        "issuetemplate"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

**Operating system:** Windows 10 Pro, Version 20H2, OS build 19042.1415

**Comment by mikulik86** [comment]
As discussed before: https://github.com/trapexit/mergerfs/issues/1001

**Comment by acsfer** [comment]
Well, it is working for someone here https://github.com/trapexit/mergerfs/issues/679 https://github.com/trapexit/mergerfs/issues/616

Nextcloud should work fine as long as DATADIR is POSIX compliant, no matter the filesystem.

So I believe this should probably be a setup issue. Reach https://help.nextcloud.com

**Comment by mikulik86** [comment]
> It is working for someone here as the main DATADIR at least. [trapexit/mergerfs#679](https://github.com/trapexit/mergerfs/issues/679) [trapexit/mergerfs#616](https://github.com/trapexit/mergerfs/issues/616)

Obviously there is a difference between an External storage and main DATADIR or tmp folder.

**Comment by mikulik86** [comment]
I think this should be addressed.

**Comment by ZanzyTHEbar** [comment]
I have the exact same issue. My mergerfs and snapraid configuration works perfectly fine on the host. I have nextcloud running in a docker container, mounted the disks. The issue i am facing rn is the same as the OP's. If i crate a file on the linux machine, nextcloud can't see it. If i create a file on nextcloud, it doesn't get saved to the actual drive - just to the docker containers mount point - which is taking up space on my main drive. It's honestly infuriating. Been dealing with this for over a week and can't solve it.

**Comment by trapexit** [comment]
I'm not sure if something changed but just to provide an update: it appears that it requires some time for nextcloud to show contents of directories. Not sure the mechanism involved but over time files show up.

**Comment by mikulik86** [comment]
In deed in Nextcloud Hub 3 (25.0.5) it works now.
