### ISSUE TITLE
Long app names overlap others in navigation

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#30474]
### Steps to reproduce
1. Have an app with a long app name enabled, like "Announcements" (in other languages like German app names are also very likely to be longer)
2. Hover/focus the app in the nav
3. See the app name overlap the other apps on the left and right of it

### Expected behaviour
There should be no overlap of the app names because it leads to legibility issues and doesn’t look clean.

### Actual behavior
![Nav current](https://user-images.githubusercontent.com/925062/147936584-3147e111-187b-4ac1-ba3d-dd13f5805aaf.png)

### Possible solution
![Nav fixed](https://user-images.githubusercontent.com/925062/147936587-8877cf63-9371-4301-9996-4f2910f9df21.png)

This is with the following code on the spans (app name container) of the app to either side of the hovered/focused one (margin-left respectively for the one right of it.)
```
width: 22px;
margin-right: 20px;
opacity: 0.3;
```
(The px values of course need to be dynamic based on the length of the app name in question.)

This needs some Javascript because:
- This should only happen if there’s overlap, that is if the name is longer than the 50px container
- CSS only can not select/modify the previous element of the current one.

**Comment by jancborchardt** [comment]
Additionally, if the text is longer, we can also reduce the tracking of the text (distance between letters). This is exactly what iOS does for home screen app icons as well. But it only gives ~1 extra character, so might be too much investment for little benefit.

**Comment by AE720** [comment]
I didn't find any clear cut answer to the current status on this but IMO, at least as a work around, only show the text of apps your cursor is focused on sort of like this:
![image](https://user-images.githubusercontent.com/63013864/187210106-120a5a91-8b27-4201-9a52-830af55c5e39.png)

Also maybe Dashboard (Since it's a core button) can also be visible in this hover over state and the app next to it is more focused to shy away from the "Dashboard" text. That's just my 2 cents.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
