### ISSUE TITLE
Change a files date modified?

### ISSUE THREAD

**Issue by edelrost** [nextcloud/server#3047]
Is there a possibility to implement an option to change a files date metadata? Like date created and date modified.

When I revisit a text file from 2007, a entry in my diary actually, to add some information and I save the file, the date modified is changed and its then not on the right position among my other entrys.

Is there possibility or do I have to download the entry, modify the date with windows explorer and reupload the file back to nextcloud?

Regards, and thank you very much for the good work you did with NEXTCLOUD so far.

**Comment by nickvergessen** [comment]
No, the modified date needs to be changed, otherwise sync clients and other features of nextcloud will not work as expected anymore.
