### ISSUE TITLE
Keyboard shortcuts for common actions in Files

### ISSUE THREAD

**Issue by nimishavijay** [nextcloud/server#30484]
Files right now is not super accessible by keyboard, with other software like Gdrive, Onedrive and Dropbox having nice keyboard shortcuts for common actions. It would be great if NC also had better keyboard accessibility. Here are the most common actions and their keyboard shortcuts across different software, and any similar actions in other Nextcloud apps also. Since there are sometimes slightly different shortcuts for different actions across softwares, we can't have something that's 100% familiar to everyone, but we can use the most common shortcut key.

| Action                  | Gdrive                                            | Dropbox      | Onedrive    | Other Nextcloud apps | Recommended shortcut                            |
|-------------------------|---------------------------------------------------|--------------|-------------|----------------------|-------------------------------------------------|
| Navigate through files  | ↑ ↓ → ← / k j h l                                 | ↑ ↓          | ↑ ↓ → ←     | ↑ ↓ in Mail          | ↑ ↓ → ← (left and right to support grid view)   |
| Select/unselect         | Ctrl+Space or x                                   |              | Space       |                      | Ctrl+Space                                      |
| Select range            | Shift+↑ ↓ → ←                                     |              |             |                      |                                                 |
| Select all              | Ctrl + a                                          | Ctrl + a     | Ctrl + a    |                      | Ctrl + a                                        |
| Unselect all            | Ctrl + n                                          | Esc          | Ctrl + d    |                      | Esc (Ctrl + n is used in Firefox for opening a new window, so Esc can be used for unselect as long as no popup is open)                                 |
| Search                  | /                                                 | /            | /           | / for quick find     | /                                               |
| Delete                  | Del                                               | Del          | Del         |                      | Del                                             |
| Rename                  | n                                                 | F2           | F2          |                      | F2                                              |
| Open file/folder        | Enter or o                                        | →            | Enter       | Enter in Mail        | Enter                                           |
| Close open file/popup   | Esc                                               |              | Esc         |                      | Esc                                             |
| Go up a folder          | g p                                               | ←            | Alt + ↑     |                      | Alt + ↑                                         |
| Upload                  | Shift + u (upload file), Shift + i (upload folder) |              |             |                      | Shift + u (open upload menu)                    |
| Share                   | .                                                 |              | s           |                      | . (s is used for favouriting)                                               |
| Favourite/star  | s                                               |              |            | s in Mail                     | s                                               |
| Toggle sidebar/details  | g d                                               |              | i           |                      | d                                               |
| Open actions menu       | a                                                 |              | Shift + F10 |                      | a (we could implement this across all apps)                               |
| Cut/copy/paste          | Ctrl + x/c/v                                      | Ctrl + x/c/v |             |                      | Ctrl + x/c/v                                    |
| Switch grid/list view   | v                                                 |              |             |                      | v                                               |
| Go to navigation        | g n                                               |              |             |                      | n (we could implement this across all the apps) |
| Show keyboard shortcuts | ?                                                 | ?            | ?           |                      | ?                                               |

What do you think? 
cc @jancborchardt who also worked on this and @skjnldsv for Files

**Comment by Spartachetto** [comment]
In case you don't remember it, there is the old issue #1444 . 

I cite it because it has a synthesis of the shortcuts of the different apps. No idea if it is up to date, though.

**Comment by Tanman897** [comment]
Hey, I am not of much help here to contribute anything useful but want to say that I do find it very frustrating that shift + click to select a batch of files on the server is not a functionality in the year 2021. It makes moving batches of files around in folders a task that would take seconds in literally any other application into hours (no exaggeration) when I am dealing with thousands of files.

**Comment by MacsKavana** [comment]
This is a super important feature. Can we expect anything?

**Comment by skjnldsv** [comment]
@nimishavijay do you have a bit more insight on the mac Meta key?
Does it replace Ctrl on the keyboard shortcuts you listed? :)

**Comment by skjnldsv** [comment]
Relevant
- https://github.com/nextcloud/server/issues/31765
- https://github.com/nextcloud/server/issues/1444

**Comment by Aveyron-RetD** [comment]
Browsing through Nextcloud github issues trying to find the best place to request a way for adding a shortcut to tags i think this might be the best place. Ignore my comment if not.
i would suggest the letter t for tags 
Tags are on three main apps and the core of nextcloud
Tags for the file app, tags for the photo app
Tags for the mail app
To add a tag on any of the core app is quite a chore on V28
BTW we have lost the possibility to tags multiple item on V28 if you would like me to open a bug report let me know.

Files app
Find the document you want to tag => Right click => Open the details => Right click on the submenu => Add a tag => Select the tags you want to add
Photo app
Find the picture you want to tag => Open the picture => Open the details => Right click on the submenu => Add a tag => Select the tags you want to add
Mail app
Select the mail you want to tag => Right click on the sub menu => Modify the tags ?? => Add a tag



Could i suggest also the @ for sharing

**Comment by nickvergessen** [comment]
> Someone suggested @ for sharing, what do you think of that ?

*/me stares at german keyboard*

Not sure if AltGr+Q is viable… Do we actually need to make different shortcuts for different languages?

**Comment by skjnldsv** [comment]
dot in French keyboard is `shift+;`, same issue

**Comment by skjnldsv** [comment]
Let's continue in dedicated tickets:

- Upload lib PR: https://github.com/nextcloud-libraries/nextcloud-upload/pull/1529
- Copy/paste Issue: https://github.com/nextcloud/server/issues/49892
- Share shortcut issue: https://github.com/nextcloud/server/issues/49910
