### ISSUE TITLE
external storage user access restrictions on file deletion

### ISSUE THREAD

**Issue by kavitha271** [nextcloud/server#30495]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
yes , I was trying to restrict user access on files in external storage.
we want restrict users on deletion of files and only admin can delete files.
I was unable to find any settings related to external storage files access.

**Describe the solution you'd like**
Please add more permissions on external storage for users/admin access.

**Describe alternatives you've considered**

**Additional context**

**Comment by q-wertz** [comment]
Maybe a workaround:

Create the same share two times, add the groups that are not allowed to delete to the second one and mark the share as `Read only`
![image](https://user-images.githubusercontent.com/20948931/148352749-ea6faa9d-c5ce-4136-9fa5-a617954014a3.png)

**Comment by joshtrichards** [comment]
Related: #14436

**Comment by joshtrichards** [comment]
Set-up External Storage, then when you set-up the Sharing options, specify *Custom permissions* and toggle off the Delete option: https://docs.nextcloud.com/server/latest/user_manual/en/files/sharing.html#internal-shares-with-users-and-groups
