### ISSUE TITLE
Hiding navigation bar

### ISSUE THREAD

**Issue by emillod** [nextcloud/server#3049]
I think you should consider option to hide left navigation bar.
This bar should have option minimize to icons, because for example in my case, I'm not using this bar at all.

**Comment by nickvergessen** [comment]
You mean to switch between the different file filters?

@jancborchardt your call, fix or close?

**Comment by emillod** [comment]
I mean to switch between look with bar naviagtion and without:
with: http://i.imgur.com/WYZTACV.png
or without: http://i.imgur.com/V3yzpb5.png

**Comment by jancborchardt** [comment]
The bar is present in most main apps like Files, Mail, Contacts, Calendar, Notes, Tasks etc and performs an important navigational function. It is reduced to a menu icon on mobile or small tablets, and then hidden by default.

Hiding it in general, or providing a function for it, will lead to confusion and findability issues. Reducing it to icons will make the individual icons not understandable as it’s too many icons without text, for a primary navigation mechanism.

If you want to disable that bar permanently, beyond the means we do automatically, I suggest you do so in a custom fashion with CSS.
