### ISSUE TITLE
Please package a default text editor

### ISSUE THREAD

**Issue by bitshiftnetau** [nextcloud/server#30504]
Right now I'm trying to transition away from using other cloud based collaborative editors or local text files, without a default editor installed in Nextcloud just makes the introduction period really painful. I'll get around to Openoffice or Collabora at some point but I have to setup servers for them as well bla bla bla, just another service I have to maintain.... default text editor please. Make it easy to use your product. 

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by szaimen** [comment]
Hello, there is a default text editor. It is even installed by default. See https://github.com/nextcloud/text

**Comment by bitshiftnetau** [comment]
> Hello, there is a default text editor. It is even installed by default. See https://github.com/nextcloud/text

Oh ok cool, so how do I access that? Why don't my files open using that editor?

**Comment by szaimen** [comment]
> Oh ok cool, so how do I access that? Why don't my files open using that editor?

Maybe it is disabled on your instance? Or it is a bug.

**Comment by szaimen** [comment]
It opens md (markdown) and txt by default

**Comment by bitshiftnetau** [comment]
> > Oh ok cool, so how do I access that? Why don't my files open using that editor?
> 
> Maybe it is disabled on your instance? Or it is a bug.

Fresh install using the following docker-compose file:

```services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /opt/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<password>
      - MYSQL_PASSWORD=<password>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=<user>
    command:
      - --innodb-read-only-compressed=OFF

  app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - /opt/nextcloud/www:/var/www/html
    environment:
      - MYSQL_PASSWORD=<password>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=central_local
      - MYSQL_HOST=db
```

**Comment by bitshiftnetau** [comment]
![nextcloud5](https://user-images.githubusercontent.com/26871600/148361313-e723deeb-a81f-48e3-9d88-13f4633d90b8.png)
![nextcloud7](https://user-images.githubusercontent.com/26871600/148361314-c5222381-9f53-41fc-9579-989308e12db4.png)

**Comment by Spartachetto** [comment]
If you are looking for help in your configuration, you should try to ask for suggestions in the user forum ( https://help.nextcloud.com/ ).

Hope that helps!

**Comment by bitshiftnetau** [comment]
> If you are looking for help in your configuration, you should try to ask for suggestions in the user forum ( https://help.nextcloud.com/ ).
> 
> Hope that helps!

Haha I knew someone was going to say that eventually 🤣 no it doesn't but I think you know that... this turned out to be a combination of a bug with .ps1 extensions prompting a download, and the basic functionality inherent in Nextcloud for downloading vs opening a file i.e. single click vs double click to open a file, which is absolutely horrible. 

I've opened a new bug related to .ps1 extensions. Thanks!
