### ISSUE TITLE
Clean up server repo for old unused/not existing translation files

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/server#30501]
This repo contains many old unused translation files.

Some are remains because languages have been renamed or deleted on Transifex and the files (js and json) are still in the repository.

**Comment by rakekniven** [comment]
I will start cleaning in smaller PRs by each language instead of creating a big monster PR.

@blizzz @nickvergessen Any objections?

**Comment by nickvergessen** [comment]
No, if they are not removed correctly by the bot right now, we should fix the bot to do that properly.

**Comment by rakekniven** [comment]
Ok, but this is something I can not do.

https://github.com/nextcloud/server/tree/master/apps/files_sharing/l10n is a good starting point.
There are "de_AT" files (6 years untouched) as an example. Many more there.
