### ISSUE TITLE
Instance Profile is not being used for S3 with External Storage Plugin

### ISSUE THREAD

**Issue by santosh-goundar** [nextcloud/server#30505]
have created instance profile with proper permissions and attached to EC2 instance, still asking for access keys while adding S3 bucket, how to avoid mentioning access key, running 20.0.8 on prod, also tried by updating NC to 22.2.3 on stage, still same issue, please suggest

as per the comments in #23178 this should have been working 21.0.2 and above versions

**Comment by ynott** [comment]
I am experiencing the same phenomenon.

This is my assumption, I assume that the mechanism was created in the following PR, but it has not been built into the management UI for external storage (apps/files_external).

https://github.com/nextcloud/server/pull/20891

**Comment by ynott** [comment]
This PR seems to have something to do with it.
It seems to have been merged into 23.0.0, but I haven't tested it yet.

https://github.com/nextcloud/server/pull/28941

**Comment by ynott** [comment]
This is so awful.
It's slipping from NC23 to NC24.
I hope it's backported...

**Comment by avinash-singhSF** [comment]
I have tested and it has been resolved in NC 22.x version. Just you have to do some additional changes.

apps/files_external/lib/Lib/Backend/AmazonS3.php

you have to copy the code from [here](https://github.com/howardZa/server/commit/5c821c713669d138f0dfa910163dd4770fb59a1c) and paste it on above file path, and you are done. You can see there is extra option added on NC Amazon S3
Select none if you want to connect using Instance profile and AWS keys to connect using AWS secret and access key


<img width="1045" alt="Screenshot 2022-02-08 at 4 12 47 PM" src="https://user-images.githubusercontent.com/66307135/152971475-7f4b50ae-de15-4b1f-ac16-5f6b9d089382.png">
