### ISSUE TITLE
LDAP Server settings get overritten by web browser and gets saved automatically. (Perhaps SAML too)

### ISSUE THREAD

**Issue by xpufx** [nextcloud/server#30507]
### Steps to reproduce

When changing existing LDAP settings, field values get filled in and revert to old values. Since the form saves automatically, these get saved. To make matters worse, the configuration check does not update so it shows green, causing one to miss that something went wrong. It can happen with changing an existing configuration. I don't know where the values are coming from. Probably the browser's form history.

It can also happen when you add a second LDAP server. Settings inevitably get mixed up and SAVED automatically as you switch between servers. 

The same issue happens with SAML too. I know it's not part of the core, but this is a GUI issue so I am mentioning it. I can't test because every time I go to those pages it takes me an hour to fix using OCC since incorrect ldap values cause a server error and nobody can log in anymore.

Does nextcloud have to autosave every form at every field focus? None of this would happen if only there was a proper SAVE button on critical configuration pages.

**Nextcloud version:** 22.2.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** OS Package then inplace update

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by xpufx** [comment]
Thanks. I am on an up to date version now and I even changed my firefox settings not to autofill anything because when the bug happens it's quite distruptive. But I will check it out again when I can find the time and open an issue.
