### ISSUE TITLE
[CalDav] emclient sync problem with task notes

### ISSUE THREAD

**Issue by Nitaro209** [nextcloud/server#30548]
### Steps to reproduce
1. Create task in emclient with some notes sync ok
2. editing task notes in nextcloud notes via browser sync ok
3. editing task notes in emclient sync ok
4. editing task notes in nextcloud notes via browser sync ok
5. editing task notes in emclien, changes not synced

No Problem with opentask for Android. I think it is emClient related but
i have no support because its the free version and the forum cant help.
I think i need infos how to debug the issue.

### Expected behaviour
I think i should editing task notes overall and every change is synced

### Actual behaviour
Syncing of task notes ended in emclient but closing the task via emclient worked.

## Server configuration detail

**Operating system:** Linux 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l

**Webserver:** Apache/2.4.38 (Raspbian) (apache2handler)

**Database:** mysql 10.3.31

**PHP version:** 7.4.27

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, pdo_sqlite, apc, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 23.0.0 - 23.0.0.10

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.9.0
 - admin_audit: 1.13.0
 - calendar: 3.0.4
 - circles: 23.0.0
 - cloud_federation_api: 1.6.0
 - comments: 1.13.0
 - contacts: 4.0.7
 - contactsinteraction: 1.4.0
 - dashboard: 7.3.0
 - dav: 1.21.0
 - federatedfilesharing: 1.13.0
 - federation: 1.13.0
 - files: 1.18.0
 - files_pdfviewer: 2.4.0
 - files_rightclick: 1.2.0
 - files_sharing: 1.15.0
 - files_versions: 1.16.0
 - files_videoplayer: 1.12.0
 - firstrunwizard: 2.12.0
 - logreader: 2.8.0
 - lookup_server_connector: 1.11.0
 - nextcloud_announcements: 1.12.0
 - notifications: 2.11.1
 - oauth2: 1.11.0
 - onlyoffice: 7.2.1
 - password_policy: 1.13.0
 - photos: 1.5.0
 - privacy: 1.7.0
 - provisioning_api: 1.13.0
 - serverinfo: 1.13.0
 - settings: 1.5.0
 - sharebymail: 1.13.0
 - support: 1.6.0
 - survey_client: 1.11.0
 - systemtags: 1.13.0
 - tasks: 0.14.2
 - text: 3.4.0
 - theming: 1.14.0
 - twofactor_backupcodes: 1.12.0
 - updatenotification: 1.13.0
 - user_status: 1.3.1
 - viewer: 1.7.0
 - weather_status: 1.3.0
 - workflowengine: 2.5.0
Disabled:
 - activity
 - documentserver_community
 - encryption
 - files_external
 - files_trashbin
 - recommendations
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.1.104"
    ],
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\Movie",
        "OC\\Preview\\PDF",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown"
    ],
    "activity_expire_days": 14,

nextcloud.log is empty

Webserver log:
192.168.1.40 - - [08/Jan/2022:11:19:07 +0100] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 805 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"
192.168.1.40 - ***** [08/Jan/2022:11:19:22 +0100] "REPORT /remote.php/dav/calendars/*****/todos/ HTTP/1.1" 207 1074 "-" "eMClient/8.2.1659.0"
192.168.1.40 - ***** [08/Jan/2022:11:19:29 +0100] "PROPFIND /remote.php/dav/files/*****/ HTTP/1.1" 207 3742 "-" "Mozilla/5.0 (Windows) mirall/3.4.1stable-Win64 (build 20211221) (Nextcloud, windows-10.0.19044 ClientArchitecture: x86_64 OsArchitecture: x86_64)"
192.168.1.40 - ***** [08/Jan/2022:11:19:29 +0100] "REPORT /remote.php/dav/calendars/*****/personal/ HTTP/1.1" 207 1074 "-" "eMClient/8.2.1659.0"
192.168.1.40 - ***** [08/Jan/2022:11:19:29 +0100] "REPORT /remote.php/dav/calendars/*****/todos/ HTTP/1.1" 207 933 "-" "eMClient/8.2.1659.0"
192.168.1.40 - ***** [08/Jan/2022:11:19:29 +0100] "PROPFIND /remote.php/dav/calendars/*****/ HTTP/1.1" 207 1759 "-" "eMClient/8.2.1659.0"
192.168.1.40 - ***** [08/Jan/2022:11:19:29 +0100] "PROPFIND /remote.php/dav/addressbooks/users/*****/ HTTP/1.1" 207 1402 "-" "eMClient/8.2.1659.0"
192.168.1.40 - ***** [08/Jan/2022:11:19:30 +0100] "PROPFIND /remote.php/dav/calendars/*****/inbox/ HTTP/1.1" 207 1272 "-" "eMClient/8.2.1659.0"
192.168.1.40 - - [08/Jan/2022:11:19:37 +0100] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 805 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0"

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by Nitaro209** [comment]
I updated and the issue still persist.
Here is a better description what happened in detail
[https://forum.emclient.com/t/caldav-sync-of-notes-field-in-tasks-does-not-work-properly/76642](url)

**Comment by szaimen** [comment]
Thanks for the link! Seems to be indeed a problem of emclient and not nextcloud
