### ISSUE TITLE
“smbclient” 未安装。无法挂载 "SMB/CIFS", "使用 OC 登录的 SMB/CIFS"。请联系管理员安装

### ISSUE THREAD

**Issue by snakwu** [nextcloud/server#30555]
系统：ubuntu2.04
snap install nextcloud
sudo apt install “smbclient

仍然提示：“smbclient” 未安装。无法挂载 "SMB/CIFS", "使用 OC 登录的 SMB/CIFS"。请联系管理员安装

 
![QQ图片20220109103728](https://user-images.githubusercontent.com/5343595/148667006-91d30009-347f-4879-aa93-776665aaa18e.png)

**Comment by Drqf** [comment]
这个是nextcloud snap的原因。snap里面对于php无法配置，所以smbclient即使安装好了，snap里的php也无法加载。要等nextcloud snap更新了可以编辑了以后才可以。 我上周刚搞过

**Comment by Drqf** [comment]
你参照nextcloud snap工程： https://github.com/nextcloud-snap/nextcloud-snap

**Comment by snakwu** [comment]
> 这个是nextcloud snap的原因。snap里面对于php无法配置，所以smbclient即使安装好了，snap里的php也无法加载。要等nextcloud snap更新了可以编辑了以后才可以。 我上周刚搞过

请问你有搞定吗？可否指导一下方法，谢谢！

**Comment by Drqf** [comment]
> 请问你有搞定吗？可否指导一下方法，谢谢！

没有， 我看了snap的nextcloud下面，那个系统是个只读的系统，那里面的php配置无法更改。snap里的php配置文件在/snap/nextcloud/current/config/php/php.ini ，里面写的扩展路径在：extension_dir = "${SNAP}/lib/php/extensions/no-debug-non-zts-20200930"。 /snap/nextcloud/current这个路径是个只读文件系统， 目前无法更改，所以没办法追加so扩展。 除非等以后snap更新了，可配置so了才可以。

**Comment by Drqf** [comment]
> 请问你有搞定吗？可否指导一下方法，谢谢！

我也很需要smb挂载，可以挂载外部文件夹，且自动刷新。  但是snap版的目前没有办法。 除非你用docker版的，那样就可以配置php了，但是不能自动升级。 docker compose安装起来应该会简单些

**Comment by Drqf** [comment]
> 请问你有搞定吗？可否指导一下方法，谢谢！

你看一下这个：
https://github.com/nextcloud-snap/nextcloud-snap/issues/60
。 snap那边好像搞不定这个了， arm上的smb不支持，所以一直没有加进去。 x86应该是没问题的

**Comment by snakwu** [comment]
@Drqf  我就是x86，也是很需要加载smb配合aria2用，这个连接我看过，也搞不定，也找到个snap版的smbclient来安状
装，也不行，是的用snap就是为了方便，可自动更新，看来只能是把smb挂载到media，再用本地挂到nextcloud了

**Comment by PVince81** [comment]
please report this issue to whoever is maintaining the snap packages

this is likely a setup issue or related to the snap build.

if you think that it's a bug in Nextcloud itself, feel free to reopen but please use English so that more people can help :smile: 

这个好像不是Nextcloud源代码问题。下次请用英文 :-)
