### ISSUE TITLE
[weather_status] Snowfall

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#30551]
@eneiluj There is rainfall in "weather status". What about snowfall?

For meteorologists, these are two different types of precipitation.

**Comment by joshtrichards** [comment]
Breadcrumbs for future work (by someone): 

https://docs.api.met.no/doc/weathericons.html

https://github.com/metno/weather_symbol

https://github.com/nextcloud/server/blob/a62a8fab9782a26516b6443c395dd8673f4c1098/apps/weather_status/src/App.vue#L101

**Comment by XxTysweezyxX** [comment]
I'd like to work on this issue if possible

**Comment by joshtrichards** [comment]
Hi @XxTysweezyxX - Absolutely. Have at it. :-)

**Comment by XxTysweezyxX** [comment]
could i get some feedback on the code?
