### ISSUE TITLE
Translation issue

### ISSUE THREAD

**Issue by LiudasLT** [nextcloud/server#30553]
Hello,
**Please, change "Tinkinti" to "Personalizuoti" in stock files:**
var/www/nextcloud/apps/dashboard/l10n/lt_LT.js
var/www/nextcloud/apps/dashboard/l10n/lt_LT.json

**Background**
"Tinkinti" exists, but its very uncommon because of its negative associations with other words and because it doesnt represent its meaning as well as "Personalizuoti". "Personalizuoti" is also used in Windows 10 and 11 to represent meaning of Customize.

**Comment by CarlSchwan** [comment]
Hello @LiudasLT, you can propose your suggestion to the transations here: https://www.transifex.com/nextcloud/nextcloud/dashboard/
