### ISSUE TITLE
share by mail not offers an password and send this to initiator

### ISSUE THREAD

**Issue by awo-in-sachsen** [nextcloud/server#30573]
### Steps to reproduce
1. activate option "always ask for a password" at "settings/sharing/allow users sharing by mail and link" and "reply to initiator" at "settings/sharing/Share by mail"
2. share an folder or file per mail (input mail adress in sharing field and click)
3. open sharing details and look for password setting, there is no password set

### Expected behaviour
in an older releas (I think, 21.x and before) the settings for sharing with links and mails where separate. We used mailsharing with enforced password and linksharing without enforced password. Now linksharing is the default and mailsharing is an addon.
i understand, that now password enforce is one option for both sharing methods.
However, our users are used to the fact that when sharing by mail, a password is given and sent to the initiator by mail. But we also need the ability to create a share via a link without a password.
Therefore, the requirement for a password cannot be used for us. The option to propose a password would be one possibility, but this only works when sharing via link, not when sharing via email. If a password is subsequently set for sharing by mail, this will not be sent to the initiator by mail, although this function is activated.

### Actual behaviour
If the user shares via e-mail, no password is proposed or requested. The password is also not sent to the initiator.
Only if you force the use of a password with the option "enforce password protection" will a mail be sent to the initiator with a password. Unfortunately, this option also applies to links.

### Server configuration

**Operating system:**
Ubuntu 18.04 LTS
**Web server:**
Apache/2.4.41 (Ubuntu)
**Database:**
mysql 8.0.27
**PHP version:**
7.4.3
**Nextcloud version:** (see Nextcloud admin page)
22.2.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated
**Where did you install Nextcloud from:**
via install script
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Accessibility	1.8.0	Featured	
Activity	2.15.0	Featured	
Appointments	1.11.10		
BigBlueButton Integration	2.1.0		
Brute-force settings	2.3.0	Featured	
Calendar	3.0.4	Featured	
Circles	22.1.1	Featured	
Collaborative tags	1.12.0	Featured	
Comments	1.12.0	Featured	
Contacts Interaction	1.3.0	Featured	
Deleted files	1.12.0	Featured	
Draw.io	1.0.2		
Federation	1.12.0	Featured	
File sharing	1.14.0	Featured	
Forms	2.4.0	Featured	
Guests	2.1.0		
Log Reader	2.7.0	Featured	
Mind Map	0.0.25		
Monitoring	1.12.0	Featured	
Nextcloud announcements	1.11.0	Featured	
Notifications	2.10.1	Featured	
ONLYOFFICE	7.2.1	Featured	
Password policy	1.12.0	Featured	
PDF viewer	2.3.1	Featured	
Photos	1.4.0	Featured	
Polls	3.4.2		
Right click	1.1.0	Featured	
Share by mail	1.12.0	Featured	
Support	1.5.0	Featured	
Talk	12.2.2	Featured	
Text	3.3.0	Featured	
Theming	1.13.0	Featured	
Update notification	1.12.0	Featured	
Usage survey	1.10.0	Featured	
User status	1.2.0	Featured	
Versions	1.15.0	Featured	
Video player	1.11.0	Featured	
Weather status	1.2.0	Featured	
Auditing / Logging	1.12.0	Featured	
Dashboard	7.2.0	Featured	
Default encryption module	2.10.0	Featured	
External storage support	1.13.0	Featured	
First run wizard	2.11.0	Featured	
LDAP user and group backend	1.12.1	Featured	
Privacy	1.6.0	Featured	
Recommendations	1.1.0	Featured	
Social sharing via email	2.4.0	Featured
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "tempdirectory": "\/var\/nextcloud\/tmp",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***\/nextcloud",
        "dbtype": "mysql",
        "version": "22.2.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "htaccess.RewriteBase": "\/nextcloud",
        "skeletondirectory": "",
        "default_language": "de",
        "default_phone_region": "DE",
        "filesystem_check_changes": 1,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_sendmailmode": "smtp",
        "mail_smtpstreamoptions": {
            "ssl": {
                "allow_self_signed": true,
                "verify_peer": false,
                "verify_peer_name": false
            }
        },
        "mail_smtpdebug": false,
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
</details>

### Client configuration
**Browser:**
Chrome
**Operating system:**
Win10
### Logs
there is no log entry when investigating the problem
<!--- Reports without logs might be closed as unqualified reports! -->

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by awo-in-sachsen** [comment]
Hello Simon,

sorry, we have to wait for Bug #740. There is only a manual fix for this Bug and we wait for a new release. I hope, it´s comming soon, but we can´t missing the onlyoffice functions.
I reply to this mail, when we going to NC25

Thanks a lot
Jan

Von: Simon L. ***@***.***>
Gesendet: Montag, 23. Januar 2023 13:54
An: nextcloud/server ***@***.***>
Cc: Knizek, Jan (AWO, Netzwerkadministrator, GS) ***@***.***>; Author ***@***.***>
Betreff: Re: [nextcloud/server] share by mail not offers an password and send this to initiator (Issue #30573)


Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

-
