### ISSUE TITLE
LDAP assistant broken if clicked too fast

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#3059]
If you click on the first screen of the LDAP assistant "continue" and then on the second screen also "continue" before the loading icon is replaced by the values the whole server setup is broken and you need to delete and recreate it.

Possible solution: disable the continue button on the second page until the content is loaded.

![ldap assistant](https://cloud.githubusercontent.com/assets/245432/21927055/c7af4ed0-d984-11e6-8014-5879c1bda97b.gif)

**Comment by ChristophWurst** [comment]
cc @nextcloud/ldap

**Comment by MorrisJobke** [comment]
Nothing for 12 I would say.

**Comment by mhow2** [comment]
@MorrisJobke hi, what does that mean "Nothing for 12 I would say" ?

**Comment by MorrisJobke** [comment]
> @MorrisJobke hi, what does that mean "Nothing for 12 I would say" ?

It was too short before the Nextcloud 12 release and I removed it from that milestone.

**Comment by szaimen** [comment]
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!

**Comment by MorrisJobke** [comment]
Fine to be closed. I guess @jancborchardt will most likely bring it up if it is still the case - I don't have an LDAP setup at hand to properly test it.
