### ISSUE TITLE
Login Security Feature Request

### ISSUE THREAD

**Issue by MrHumanRebel** [nextcloud/server#30604]
1. Google reCAPTCHA support at login screen: 
    This would prevent bots spamming login attempts to the Jellyfin server.
    https://www.google.com/recaptcha/about/

2. Bruteforce blocker:
    Disable/lock login page for the IP address if wrong Username or Password until the admin unlocks it, or for "X" minutes.

**Comment by acsfer** [comment]
1. It will never be implemented by Nextcloud as it depends on external libraries.
You (or someone) can always develop it as an app.
2. https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/bruteforce_configuration.html
and https://apps.nextcloud.com/apps/bruteforcesettings
