### ISSUE TITLE
[NC 22.2.3] Deprecated event type for OCP\IPreview:PreviewRequested

### ISSUE THREAD

**Issue by GAS85** [nextcloud/server#30639]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Open any UI Page with Pictures
2. See Logs flood with
![grafik](https://user-images.githubusercontent.com/6813635/149304081-886d60b9-1975-422c-a21c-75c7dab8f1d4.png)

```json
{"reqId":"tJI9rQ4bC5JlMobuiATV","level":1,"time":"2022-01-13T09:29:28+00:00","remoteAddr":"256.256.256","user":"USER","app":"no app in context","method":"GET","url":"/index.php/core/preview?fileId=3559166&c=66307dcfa2f549c84826b1eea5bf1423&x=250&y=250&forceIcon=0&a=0","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0","version":"22.2.3.0","id":"61dff21de59ee"}
```
3. Find an old ticket #18331
4. Be sad

### Expected behaviour
No Deprecated events being used in UI

### Actual behaviour
Logs flood with same event

## Server configuration detail

**Operating system:** Linux 5.4.0-94-generic #106-Ubuntu SMP Thu Jan 6 23:58:14 UTC 2022 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.3.32

**PHP version:** 7.4.27

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdlib, pdo_mysql, pdo_sqlite, apc, posix, readline, redis, shmop, SimpleXML, snmp, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 22.2.3 - 22.2.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Official

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.8.0
 - activity: 2.15.0
 - admin_audit: 1.12.0
 - audioplayer: 3.2.4
 - bookmarks: 10.0.3
 - bruteforcesettings: 2.3.0
 - calendar: 3.0.4
 - camerarawpreviews: 0.7.15
 - checksum: 1.1.3
 - cloud_federation_api: 1.5.0
 - comments: 1.12.0
 - contacts: 4.0.7
 - contactsinteraction: 1.3.0
 - cospend: 1.4.3
 - dashboard: 7.2.0
 - data_request: 1.9.0
 - dav: 1.19.0
 - deck: 1.5.5
 - drawio: 1.0.2
 - external: 3.9.0
 - extract: 1.3.3
 - facerecognition: 0.9.1
 - federatedfilesharing: 1.12.0
 - files: 1.17.0
 - files_automatedtagging: 1.12.0
 - files_downloadactivity: 1.12.0
 - files_external: 1.13.0
 - files_mindmap: 0.0.25
 - files_pdfviewer: 2.3.1
 - files_retention: 1.11.1
 - files_rightclick: 1.1.0
 - files_sharing: 1.14.0
 - files_trashbin: 1.12.0
 - files_versions: 1.15.0
 - files_videoplayer: 1.11.0
 - firstrunwizard: 2.11.0
 - forms: 2.4.0
 - gpxedit: 0.0.14
 - gpxpod: 4.3.0
 - impersonate: 1.9.0
 - integration_discourse: 1.0.2
 - integration_github: 1.0.2
 - integration_gitlab: 1.0.3
 - keeweb: 0.6.8
 - logreader: 2.7.0
 - lookup_server_connector: 1.10.0
 - mail: 1.11.5
 - maps: 0.1.10
 - news: 17.0.1
 - nextcloud_announcements: 1.11.0
 - notes: 4.2.0
 - notifications: 2.10.1
 - oauth2: 1.10.0
 - ocdownloader: 1.8.0
 - password_policy: 1.12.0
 - phonetrack: 0.6.9
 - photos: 1.4.0
 - polls: 3.4.2
 - previewgenerator: 3.4.1
 - privacy: 1.6.0
 - provisioning_api: 1.12.0
 - recognize: 1.8.0
 - recommendations: 1.1.0
 - serverinfo: 1.12.0
 - settings: 1.4.0
 - sharebymail: 1.12.0
 - side_menu: 2.1.0
 - spreed: 12.2.2
 - support: 1.5.0
 - survey_client: 1.10.0
 - systemtags: 1.12.0
 - text: 3.3.0
 - theming: 1.13.0
 - transmission: 0.7.2
 - twofactor_backupcodes: 1.11.0
 - twofactor_totp: 6.2.0
 - unsplash: 1.2.4
 - updatenotification: 1.12.0
 - user_status: 1.2.0
 - video_converter: 1.0.4
 - viewer: 1.6.0
 - weather_status: 1.2.0
 - workflowengine: 2.4.0
Disabled:
 - circles
 - encryption
 - federation
 - files_accesscontrol
 - flowupload
 - gpxmotion
 - integration_jira
 - radio
 - user_ldap
 - weather

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "22.2.3.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "filesystem_check_changes": 0,
    "filelocking.enabled": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 1.5
    },
    "default_phone_region": "DE",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "logfile": "\/var\/nextcloud\/data\/nextcloud.log",
    "loglevel": 1,
    "trashbin_retention_obligation": "14, auto",
    "versions_retention_obligation": "14, auto",
    "data-fingerprint": "7be51475e95ea13b254cd880319d98ec",
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\Movie",
        "OC\\Preview\\PDF",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown"
    ],
    "preview_max_x": 1920,
    "preview_max_y": 1080,
    "jpeg_quality": 90,
    "auth.bruteforce.protection.enabled": true,
    "simpleSignUpLink.shown": false,
    "mail_sendmailmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "twofactor_enforced": true,
    "twofactor_enforced_groups": [
        "admin"
    ],
    "twofactor_enforced_excluded_groups": [],
    "has_rebuilt_cache": true,
    "updater.release.channel": "stable",
    "app_install_overwrite": [
        "transmission"
    ]
}
```
</details>

**External storages:** Local, Webdav

**Encryption:** no

**User-backends:** 
 * OC\User\Database

**Talk configuration:** 

STUN servers
 * stun.nextcloud.com:443

TURN servers
 * no custom server configured

Signaling servers (mode: internal):
 * no custom server configured

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0

**Comment by szaimen** [comment]
Does this still happen if you set the loglevel to `2` as it is recommended in the admin docs?

**Comment by GAS85** [comment]
For sure not, but this will simply suppress messages below `WARN`. My expectation that UI not using any deprecated endpoints / methods.

`INFO` is also important for me, because it is providing such kind of information as:

>  Activity such as user logins and file activities,

**Comment by szaimen** [comment]
> Activity such as user logins and file activities,

You should use the admin_audit app for such things

**Comment by Lars1963** [comment]
> You should use the admin_audit app for such things

Just a dumm question: I don't seem to find that app in the app_store. 🤔 Under which Name is it released there?

**Comment by szaimen** [comment]
> Just a dumm question: I don't seem to find that app in the app_store. 🤔 Under which Name is it released there?

It is integrated into the server: https://github.com/nextcloud/server/tree/master/apps/admin_audit

See https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/logging_configuration.html?highlight=admin_audit#admin-audit-log

Everything will then be logged to this file.

Also, see this PR: https://github.com/nextcloud/logreader/pull/476

**Comment by Lars1963** [comment]
> It is integrated into the server: https://github.com/nextcloud/server/tree/master/apps/admin_audit
> 
> See https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/logging_configuration.html?highlight=admin_audit#admin-audit-log for how to configure it
> 
> Everything will then be logged to this file.
> 
> Also, see this PR: [nextcloud/logreader#476](https://github.com/nextcloud/logreader/pull/476)

@szaimen Thank you very much. 👋 I must confess, I didn't read the manual for this specific case. 🙈 I only have been using the logging untill now with Level `3`.

**Comment by GAS85** [comment]
> You should use the admin_audit app for such things

😄  Thanks, I use it too, but `INFO` Level is not limited to the list above, so more relevant information is flying there that been used for monitoring.

**Comment by GAS85** [comment]
This is a good comment from other issue: https://github.com/nextcloud/server/issues/24380#issuecomment-1032168588

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by GAS85** [comment]
Nextcloud 24.0.9 still presented:
```json
{"reqId":"X9Ez064xV7jPfC5H9xPT","level":1,"time":"2023-01-30T15:18:24+00:00","remoteAddr":"255.255.255.255","user":"USER","app":"no app in context","method":"GET","url":"/index.php/core/preview?fileId=4638250&c=e56af70963f1e875f00ea57d18634fb2&x=250&y=250&forceIcon=0&a=0","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:107.0) Gecko/20100101 Firefox/107.0","version":"24.0.9.2","data":[],"id":"63d7dfc05d75f"}
```

**Comment by szaimen** [comment]
Hi, please update to 25.0.7 or better 26.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 26-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by GAS85** [comment]
Seems no such kind of messages appears any more in NC 24.
