### ISSUE TITLE
File picker scrolling issues when breadcrumb too long

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#30640]
### Steps

1. Create a set of folders with long names: "first folder > second folder > third folder > fourth folder > fifth folder"
2. Make the window narrow horizontally
3. Open the three dots menu of another entry in the root and pick "move or copy"
4. Navigate into "fifth folder" (or make it so that the "+" button is on the right side of the dialog)
5. Try creating another subdirectory from within the dialog

### Expected result
Able to see the field properly

### Actual result
Field cannot be fully viewed even with horizontal scrolling

### Versions
22.2.0 and git master
<img width="453" alt="image" src="https://user-images.githubusercontent.com/277525/149305691-4956a085-d2e5-4b5d-8a4b-29fe7e2dba66.png">

### Notes
Ideally the breadcrumb should replace itself with an ellipsis so that no scrollbars become visible,
or the dropdown needs to position itself more to the left

**Comment by CarlSchwan** [comment]
An easy fix would be to add the right padding to the `+` button, so that the button go early enough inside a new row. This is a bit ugly but would make it possible to properly click on the button.

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/pull/30828
