### ISSUE TITLE
Re-label "English" to "English (US)" in user preferences

### ISSUE THREAD

**Issue by dnel** [nextcloud/server#3064]
### Steps to reproduce
1. Go to personal settings
2. See that "English" is already configured, think to oneself "Indeed old chap, I speak English, that is correct."
3. Walk away

### Expected behaviour

* System is configured for the Queen's own British English.

### Actual behaviour
Tell us what happens instead

* Find that the calendar uses this setting to assume I am American and presents calendar dates in backwards US format and a poorly designed 12-hour clock dialogue (but that's a bug report for another day).
* Spend some time tracking this problem back and discover that there is also a "English (British)" option that I needed to choose instead.

It would be much clearer if the default "English" option was specifically labeled "English (US)", like almost every other language selection menu that exists, that way as a minority in the Anglosphere, I will instinctively check for a better alternative and find it.

**Comment by nickvergessen** [comment]
Well there is "English" and "English (British English)"
But I guess we could make that clear, yes.

**Comment by dnel** [comment]
#3070 Not entirely sure what I'm doing but I've given it a try.

**Comment by ccoenen** [comment]
[off-topic]Original post gets 10/10 for style @dnel[/off-topic]
