### ISSUE TITLE
occ upgrade runs again in circles

### ISSUE THREAD

**Issue by XDAmaniac** [nextcloud/server#30641]
Once more my nextcloud instance runs in circles:
occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <fileslibreofficeedit> ...
Updated <fileslibreofficeedit> to 1.0.4
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Resetting log level

over and over again.

**Comment by XDAmaniac** [comment]
disabling Upgrades doesn't solve the problem either:
entering my cloud url into a browser gives me:

-------------------------------------------------------------------------------------------------------------------------------
Aktualisierung erforderlich
Da automatische Updates in der config.php deaktivert sind, nutzen Sie bitte den Updater über die Kommandozeile.

Für weitere Hilfen, schauen Sie bitte in die Dokumentation.
-------------------------------------------------------------------------------------------------------------------------------

So Nextcloud could (and does as we see in this example) disables instances by declaring a buggy upgrade as mandatory.

**Comment by XDAmaniac** [comment]
I ask myself more and more often:
a) Is Nextcloud a solution for a reliable cloud for home users at all?
and b) why to force users to change running systems into buggy systems,- who wins what on that?

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by XDAmaniac** [comment]
occ app:disable fileslibreofficeedit
solved the problem, nexcloud should declare alpha & beta as such instead of prod or stable
