### ISSUE TITLE
drag and drop folder with accent

### ISSUE THREAD

**Issue by hregnier** [nextcloud/server#3065]
Hello there,

I have a problem with freshly upgraded version of nextcloud (from 10.0.1 to 11). When I try to drag and drop a folder with an accent (like "Création") it doesn't work. Nextcloud create a file named "InvalidStateError" with inside "[object DOMError]". When there are no accent, it works perfectly.

I tried with IE : nothing happens at all, with or without accent. No problem with Chrome or Opera.

Thanks for your answers!

**Comment by MorrisJobke** [comment]
> @MorrisJobke you have IE access , right?

You could have too: https://modern.ie 😉

**Comment by H4ndl3** [comment]
This also happens when my brother tries to upload a folder without any special characters in its name via drag and drop to my Nextcloud instance. He's using Firefox 50.1.0, Nextcloud version is 11.0.1. A file named `InvalidStateError` is created but the folder seems to be uploaded anyways.

**Comment by ncist2011** [comment]
@H4ndl3 
the same problem to me with Firefox51.0.1 on windows7, but i must use Firefox to upload folder.
How to fix this problem?

thanks!

**Comment by ncist2011** [comment]
![qq20170221-0](https://cloud.githubusercontent.com/assets/4124982/23198053/a494dc04-f8ff-11e6-98f4-2acf576ff5c6.png)

**Comment by MorrisJobke** [comment]
> the same problem to me with Firefox51.0.1 on windows7, but i must use Firefox to upload folder.
> How to fix this problem?

Folder upload via Firefox is not supported, because Firefox doesn't have an API for this.

**Comment by individual-it** [comment]
@ncist2011 FF 52 does support folder upload and it works with NextCloud (tested with current master)

**Comment by nickvergessen** [comment]
Yeah just tested and it works fine also with accents.
So it's down to IE not supporting this.

**Comment by skjnldsv** [comment]
Closing, please don't use ie
