### ISSUE TITLE
Cannot retrieve value of undefined directive HTML.TargetNoreferrer

### ISSUE THREAD

**Issue by nc0815** [nextcloud/server#3066]
### Steps to reproduce
1. see at Nextcloud logfile

### Expected behaviour
No errors expected

### Actual behaviour
At every run of cron.php and Mail-App the following error is thrown:

`Cannot retrieve value of undefined directive CSS.AllowDuplicates invoked on line 28 in file /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/AttrDef/CSS.php at /var/www/html/nextcloud/apps/news/vendor/ezyang/htmlpurifier/library/HTMLPurifier/Config.php#901 `

see Nextcloud.log-section for details

### Server configuration
**Operaton system**: Ubuntu 16.04
**Web server:** Apache 2.4.18
**Database:** Mysql 5.7
**PHP version:** 7.0.4
**Nextcloud version:** 11.0
**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 10.0.1
**Where did you install Nextcloud from:** tarball from Nextcloud download and updater-app

**Signing status:**
```
No errors have been found.
```

**List of activated apps:**
```
Enabled:
  - bookmarks: 0.9.1
  - calendar: 1.4.1
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - direct_menu: 0.10.0
  - federatedfilesharing: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - gallery: 16.0.0
  - keeweb: 0.3.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - news: 10.1.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - activity
  - admin_audit
  - encryption
  - external
  - federation
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - firstrunwizard
  - systemtags
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
```

**The content of config/config.php:**
```
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'xxx',
    1 => 'xxx',
  ),
  'datadirectory' => '/media/usb-hdd/xxx/xxx',
  'overwrite.cli.url' => '/',
  'version' => '11.0.0.10',
  'session_lifetime' => 43200,
  'appstore.experimental.enabled' => false,
  'htaccess.RewriteBase' => '/',
  'theme' => '',
  'maintenance' => false,
  'updatechecker' => true,
  'upgrade.disable-web' => false,
  'check_for_working_htaccess' => true,
  'has_internet_connection' => true,
  'trashbin_retention_obligation' => 'auto',
  'installed' => true,
  'dbtype' => 'mysql',
  'dbname' => 'xxx',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'xxx',
  'mail_smtppassword' => 'xxx',
  'mail_smtphost' => 'smtp.url.tld',
  'mail_smtpport' => '465',
  'mail_from_address' => 'xxx',
  'mail_domain' => 'url.tld',
  'mail_smtpdebug' => true,
  'loglevel' => 0,
  'logfile' => '/var/log/nextcloud.log',
  'logtimezone' => 'Europe/Berlin',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '/var/run/redis.sock',
    'port' => 0,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'preview_max_scale_factor' => 1,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    11 => 'OC\\Preview\\Illustrator',
    12 => 'OC\\Preview\\Postscript',
    13 => 'OC\\Preview\\Photoshop',
    14 => 'OC\\Preview\\TIFF',
  ),
  'updater.release.channel' => 'stable',
  'filelocking.enabled' => true,
  'updater.secret' => 'xxx',
```

**Are you using external storage, if yes which one:** USB-HDD mounted on /media/usb-hdd/...
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

#### Nextcloud log (data/nextcloud.log)

This will thrown when accessing Mail-app:

`{"reqId":"3Ud+J6g+x6oth8iya553","remoteAddr":"12.34.56.78","app":"PHP","message":"Cannot retrieve value of undefined directive HTML.TargetNoreferrer invoked on line 276 in file \/var\/www\/nextcloud\/apps\/news\/vendor\/ezyang\/htmlpurifier\/library\/HTMLPurifier\/HTMLModuleManager.php at \/var\/www\/nextcloud\/apps\/news\/vendor\/ezyang\/htmlpurifier\/library\/HTMLPurifier\/Config.php#901","level":3,"time":"2017-01-13T15:32:05+01:00","method":"GET","url":"\/index.php\/apps\/mail\/accounts\/2\/folders\/SU5CT1g%3D\/messages?ids=17852%2C17851%2C17850%2C17849%2C17848%2C17847%2C17846%2C17836%2C17827%2C17819","user":"xxx","version":"11.0.0.10"}`

This will thrown when running cron.php:

`{"reqId":"x8eMuZPpVm6eJjuAT+y9","remoteAddr":"","app":"PHP","message":"Cannot retrieve value of undefined directive HTML.TargetNoreferrer invoked on line 276 in file \/var\/www\/nextcloud\/apps\/news\/vendor\/ezyang\/htmlpurifier\/library\/HTMLPurifier\/HTMLModuleManager.php at \/var\/www\/nextcloud\/apps\/news\/vendor\/ezyang\/htmlpurifier\/library\/HTMLPurifier\/Config.php#901","level":3,"time":"2017-01-13T12:00:11+01:00","method":"--","url":"--","user":"--","version":"11.0.0.10"}
`

**Comment by nickvergessen** [comment]
Please report at https://github.com/nextcloud/news/

**Comment by nc0815** [comment]
moved to https://github.com/nextcloud/news/issues/83
