### ISSUE TITLE
Storage warning at 5,9TB 96% full but 13TB available - Ubuntu LTS 20.40@Windows WSL2 

### ISSUE THREAD

**Issue by zackfuchtel** [nextcloud/server#30710]
Hello,

running nextcloud 21.0.2 on Ubuntu LTS 20.40@Windows WSL2 on Windows 11. I Got a persisten storage warning popup about stor is 96% full at 5,9TB, but disk size is about 13TB.

Is this a bug or what is going on? Thanks.

```
"Dein Speicher ist beinahe voll (96%)."

Linux freak_w11 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

drvfs            13T  5.4T  7.4T  42% /mnt/n 
```

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
