### ISSUE TITLE
occ encryption:encrypt-all changes file attributes

### ISSUE THREAD

**Issue by TheSpaceGod** [nextcloud/server#30725]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Upload files to nextcloud server using desktop client (folder sync).
2. Turn on file encryption in settings.
3. Run "occ encryption:encrypt-all" on server to encrypt all existing files.
4. Take server out of maintenance mode from encryption.
5. Run desktop client sync.

### Expected behaviour
Nothing should really happen since I am not syncing any "new" files.

### Actual behaviour
Desktop client starts overwriting each file in sync folder with an identical file, just with file properties said the date created was the day of the server encryption.  This is a problem if you have a photo collection folder and you use date file attributes to sort photos.

### Server configuration

**Operating system:**
Fedora 33 Host (Docker Image nextcloud)
https://hub.docker.com/_/nextcloud

**Database:**
MySQL

**Nextcloud version:** (see Nextcloud admin page)
Version 23.0.0

</details>

**Comment by TheSpaceGod** [comment]
Just tried starting from scratch and still getting the same issue.

Steps:

- Removed client sync folder.
- Deleted all user files one server via web browser.
- Ensured that encryption was enabled.
- Remade sync folder in client and completed an entire sync.
- Files on server say their modification date was day of sync, not day of photo taken like it should with other photos.
- Sync client then tries to replace files on local system with server version of file with newer date modified file attribute.

**Comment by TheSpaceGod** [comment]
Luckily I keep a Windows local file history backup of my files so I can revert them, but this is an image example showing the Nextcloud server date modified file attribute and the Windows "true" date modified file attribute:

![unknown](https://user-images.githubusercontent.com/17182063/150288039-49116ea8-7c5e-4988-8c3e-74e1da3e1d92.png)
![unknown (1)](https://user-images.githubusercontent.com/17182063/150288043-431a4720-2dec-4520-9fae-77d9d00951dc.png)

**Comment by TheSpaceGod** [comment]
As a sanity check, it does look like some of my files get the proper date modified file attribute on Nextcloud:
![unknown (2)](https://user-images.githubusercontent.com/17182063/150288305-897c3220-b591-4771-b873-c830857ef303.png)

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
