### ISSUE TITLE
Cannot change logo by replacing logo.svg or logo.png as explained in the documentation

### ISSUE THREAD

**Issue by elpraga** [nextcloud/server#3073]
### Steps to reproduce
1. Make a custom theme as described [in the documentation](https://docs.nextcloud.com/server/11/developer_manual/core/theming.html)
2. try to chage the logo on the login page by replacing the `logo.svg` and `logo.png` files. 

### Expected behavior
Logo on the login page gets replaced

### Actual behavior
Logo on the login page stays the same.

### Server configuration
**Operating system**:
Lubunt 16.04
**Web server:**
Apache2 2.4.18
**Database:**
Sqlite3
**PHP version:**
php7.0
**Nextcloud version:** (see Nextcloud admin page)
11.0.0.10
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated
**Where did you install Nextcloud from:**
Nextcloud.com

**Comment by schiessle** [comment]
I would suggest to use the theming app. It should be enabled by default. To replace the logo go to your admin panel -> Theming

**Comment by elpraga** [comment]
I did try that, but when changing the logo via theming app, both the login screen logo and the smaller logo get changed.
The documentation explains how to change them separately.  If the way described in the documentation  doesnt work anymore, the documentation should be changed.

Is changing the icons separately still suported?

**Comment by schiessle** [comment]
Please try to disable the theming app, then it should work. As long as the theming app is enabled, the app control the look of Nextcloud. If disabled we fall back to the old theming.

**Comment by elpraga** [comment]
Unfortunatelly I cannot confirm that @schiessle . 

Not even after disabling Themes app theaming behaves as described in documentation. 

Could you please verify?

I would understand if you made a change, the Theaming app is quite nice and easy to use, but if a change has been made it should be reflected in the documentation.

**Comment by nickvergessen** [comment]
Yeah seems like this was changed, for me in both cases `core/img/logo-icon.svg` is used.

But maybe we can adjust the theming app, to have a small (header) and a big logo (login page)

**Comment by elpraga** [comment]
Great! It would be nice to change the logo on the login screen separately using the Theming app!

**Comment by juliushaertl** [comment]
Discussion about a separate logo is taking place in https://github.com/nextcloud/server/issues/5779

I've created a PR to update the documentation on the logo-wide removal: https://github.com/nextcloud/documentation/pull/559
