### ISSUE TITLE
Every single community is the same

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#30746]
Are you kidding me? Seriously? Stop locking the files. Not that hard and it is beyond me that duplicati, nextcloud and github all all supposedly trying to help me.

What info you do you the gods need to assist a retard like me?

I run a backup and the server gets locked. Your program is locking up and causing issues.

**Comment by utcutr** [comment]
I do not get it why every community is the same with the same people and same attitudes.

**Comment by utcutr** [comment]
I hate you all
