### ISSUE TITLE
View-only permission for internal shares

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#30744]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

While working on the permissions via #30227 and harmonize the permissions for internal and external shares it would be nice to add following permissions for _internal_ share:

* view-only (no download, people just can view the documents in the browser)
* prevent printing (if possible)

This permissions are often requested for Virtual Data Room scenarios. Question is how to handle this permissions in the clients, @schiessle's idea:

* desktop client would not sync this view-only files
* mobile clients could show the document in the embedded viewer if possible but not allow to download it
* regular webdav clients should not show the file/folder at all or prevent to copy/download/open it

**Comment by PVince81** [comment]
we can use https://github.com/nextcloud/server/issues/22220

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/server/pull/32482

**Comment by PVince81** [comment]
am checking the ownCloud code further, especially for the backend approach and I'm not too happy about it (I also wasn't back then)

it seems that FileActions are not modified. In my test, I see that the "Download" action still appears but clicking on it will show an error page.

to me this anyway means that we'll need a different frontend approach, possibly as follows:
- [ ] add DAV attribute for share attributes
- [ ] add share attribute on the frontend's FileInfo model after parsing from DAV attribute, this way apps also have access to it
- [ ] process share attributes in frontend code that handles share permissions (ex: SharingEntry.vue)
- [ ] make sure reshare logic works: it should **not be possible to increase permissions** , only reduce

further things to check:
- [ ] public link page should also hide download when a link share got created on a received share with download disabled  (remap to "hide download" ?)
