### ISSUE TITLE
IPv6 support for Federated Shares

### ISSUE THREAD

**Issue by Tie-fighter** [nextcloud/server#30757]
### Steps to reproduce
1. Create a federated storage share between a dual stack server and an IPv4-only server
2. Everything works
3. Switch the IPv4-only server to IPv6-only
4. Federated share stops working

### Expected behaviour
Federated share should work as before

### Actual behaviour
When sharing from DS to IPv6 only this error message occurs:
> Error creating the share: Sharing _Exchange failed, could not find [redacted]@next.thomas-steinbrenner.net, maybe the server is currently unreachable or uses a self-signed certificate.

When sharing from the IPv6 only server to the DS server it works, as in the invitation is displayed.
After accepting however, the shared folder is not displayed and can only be found under Shares.
When browsing into it it says:
> File not found The document could not be found on the server. Maybe the share was deleted or has expired?

### Server configuration

**Operating system:**
DS: unknown
ipv6-only: TrueNAS jail

**Web server:**
DS: unknown
ipv6-only: nginx

**Database:**
DS: unknown
ipv6-only: MariaDB

**PHP version:**
DS: unknown
PHP: 

**Nextcloud version:** (see Nextcloud admin page)
DS: 22.2.0
ipv6-only: 23.0.0

### Logs

no relevant logs available :(

Sorry for being this vague. I already opened a ticket with the provider (Hetzner) too.
I am hoping that maybe somebody knows if there is an php-function in use somewhere that relies on IPv4.
Or maybe somebody has a working IPv6-only setup and can rule IPv6 out.

**Comment by Tie-fighter** [comment]
`15 Jan 19 11:21:28 nextcloud[00000]: {"reqId":"tb3up9nL7ZU7kOHRGSlR","level":3,"time":"2022-01-19T10:21:28+00:00","remoteAddr":"84.115.223.158","user":"thomas","app":"no app in context","method":"POST","url":"/ocs/v2.php/apps/files_sharing/api/v1/shares","message":"{\"Exception\":\"Exception\",\"Message\":\"Sharing _Exchange failed, could not find Tie-fighter@next.thomas-steinbrenner.net, maybe the server is currently unreachable or uses a self-signed certificate.\",\"Code\":0,\"Trace\":[{\"file\":\"/var/www/html/apps/federatedfilesharing/lib/FederatedShareProvider.php\",\"line\":252,\"function\":\"createFederatedShare\",\"class\":\"OCA\\\\FederatedFileSharing\\\\FederatedShareProvider\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Share20\\\\Share\"}]},{\"file\":\"/var/www/html/lib/private/Share20/Manager.php\",\"line\":804,\"function\":\"create\",\"class\":\"OCA\\\\FederatedFileSharing\\\\FederatedShareProvider\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Share20\\\\Share\"}]},{\"file\":\"/var/www/html/apps/files_sharing/lib/Controller/ShareAPIController.php\",\"line\":657,\"function\":\"createShare\",\"class\":\"OC\\\\Share20\\\\Manager\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Share20\\\\Share\"}]},{\"file\":\"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php\",\"line\":217,\"function\":\"createShare\",\"class\":\"OCA\\\\Files_Sharing\\\\Controller\\\\ShareAPIController\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\Files\\\\Node\\\\Folder\"},31,6,\"Tie-fighter@next.thomas-steinbrenner.net\",\"false\",\"\",null,\"\",\"\"]},{\"file\":\"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php\",\"line\":126,\"function\":\"executeController\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\",\"args\":[{\"__class__\":\"OCA\\\\Files_Sharing\\\\Controller\\\\ShareAPIController\"},\"createShare\"]},{\"file\":\"/var/www/html/lib/private/AppFramework/App.php\",\"line\":156,\"function\":\"dispatch\",\"class\":\"OC\\\\AppFramework\\\\Http\\\\Dispatcher\",\"type\":\"->\",\"args\":[{\"__class__\":\"OCA\\\\Files_Sharing\\\\Controller\\\\ShareAPIController\"},\"createShare\"]},{\"file\":\"/var/www/html/lib/private/Route/Router.php\",\"line\":301,\"function\":\"main\",\"class\":\"OC\\\\AppFramework\\\\App\",\"type\":\"::\",\"args\":[\"OCA\\\\Files_Sharing\\\\Controller\\\\ShareAPIController\",\"createShare\",{\"__class__\":\"OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer\"},{\"_route\":\"ocs.files_sharing.ShareAPI.createShare\"}]},{\"file\":\"/var/www/html/ocs/v1.php\",\"line\":62,\"function\":\"match\",\"class\":\"OC\\\\Route\\\\Router\",\"type\":\"->\",\"args\":[\"/ocsapp/apps/files_sharing/api/v1/shares\"]},{\"file\":\"/var/www/html/ocs/v2.php\",\"line\":23,\"args\":[\"/var/www/html/ocs/v1.php\"],\"function\":\"require_once\"}],\"File\":\"/var/www/html/apps/federatedfilesharing/lib/FederatedShareProvider.php\",\"Line\":318,\"CustomMessage\":\"--\"}","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36","version":"22.2.0.2"}`

**Comment by CarlSchwan** [comment]
Can you do a wget/ping from your nextcloud instance to next.thomas-steinbrenner.net?

**Comment by Tie-fighter** [comment]
@CarlSchwan Here it is:
(Hops 9 and 10 are not set up for IMCPv6)

```
# traceroute6 next.thomas-steinbrenner.net
traceroute to txen.nsupdate.info (2a02:8388:6c83:eb90:ff:60ff:feba:b582) from 2a01:4f8:252:614a::2, 30 hops max, 24 byte packets
1 2a01:4f8::a:25:b (2a01:4f8::a:25:b) 0.6478 ms 0.3679 ms 0.3979 ms
2 2a01:4f8:0:3::79 (2a01:4f8:0:3::79) 5.0329 ms 10.5710 ms 0.4444 ms
3 juniper5.nbg1.hetzner.com (2a01:4f8:0:3::401) 2.5912 ms 2.5759 ms 5.9696 ms
4 po20-ugwix103r401.t-mobile.at (2001:7f8:30:0:2:1:0:8412) 11.6658 ms 11.5048 ms 11.6020 ms
5 * * *
6 2a02:8380:103:a::2 (2a02:8380:103:a::2) 11.7885 ms 11.7252 ms 11.6994 ms
7 2a02:8382:0:134:74ad:15da:32ab:57fb (2a02:8382:0:134:74ad:15da:32ab:57fb) 23.8901 ms 29.7564 ms 20.3469 ms
8 2a02-8388-6c83-eb80-84b0-f594-053c-d9ce.cable.dynamic.v6.surfer.at (2a02:8388:6c83:eb80:84b0:f594:53c:d9ce) 21.4041 ms 24.0904 ms 19.6581 ms
9 * * *
10 * * *
```

```
# mtr -rc10 -6 next.thomas-steinbrenner.net
Start: 2022-01-21T11:24:25+0100
HOST: shareweb213.your-storagesha Loss% Snt Last Avg Best Wrst StDev
1.|-- 2a01:4f8::a:25:b 0.0% 10 0.3 0.5 0.3 0.7 0.1
2.|-- 2a01:4f8:0:3::79 0.0% 10 8.5 2.5 0.3 8.5 3.1
3.|-- juniper5.nbg1.hetzner.com 0.0% 10 2.6 3.7 2.6 11.8 2.9
4.|-- po20-ugwix103r401.t-mobil 0.0% 10 11.6 11.6 11.5 11.8 0.1
5.|-- ??? 100.0 10 0.0 0.0 0.0 0.0 0.0
6.|-- 2a02:8380:103:a::2 0.0% 10 11.7 11.8 11.7 12.0 0.1
7.|-- 2a02:8382:0:134:74ad:15da 0.0% 10 22.5 31.0 19.4 74.8 20.5
8.|-- 2a02-8388-6c83-eb80-84b0- 0.0% 10 18.6 26.3 18.6 70.4 16.3
9.|-- ??? 100.0 10 0.0 0.0 0.0 0.0 0.0
```

```
# wget next.thomas-steinbrenner.net
--2022-01-21 11:25:28-- http://next.thomas-steinbrenner.net/
Resolving next.thomas-steinbrenner.net (next.thomas-steinbrenner.net)... 2a02:8388:6c83:eb90:ff:60ff:feba:b582
Connecting to next.thomas-steinbrenner.net (next.thomas-steinbrenner.net)|2a02:8388:6c83:eb90:ff:60ff:feba:b582|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://next.thomas-steinbrenner.net/ [following]
--2022-01-21 11:25:28-- https://next.thomas-steinbrenner.net/
Connecting to next.thomas-steinbrenner.net (next.thomas-steinbrenner.net)|2a02:8388:6c83:eb90:ff:60ff:feba:b582|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://next.thomas-steinbrenner.net/login [following]
--2022-01-21 11:25:28-- https://next.thomas-steinbrenner.net/login
Reusing existing connection to [next.thomas-steinbrenner.net]:443.
HTTP request sent, awaiting response... 200 OK
Length: 13273 (13K) [text/html]
Saving to: ‘index.html’

index.html 100%[==========================================================>] 12.96K --.-KB/s in 0s
2022-01-21 11:25:28 (405 MB/s) - ‘index.html’ saved [13273/13273]
```

```
# wget https://next.thomas-steinbrenner.net
--2022-01-21 11:27:47-- https://next.thomas-steinbrenner.net/
Resolving next.thomas-steinbrenner.net (next.thomas-steinbrenner.net)... 2a02:8388:6c83:eb90:ff:60ff:feba:b582
Connecting to next.thomas-steinbrenner.net (next.thomas-steinbrenner.net)|2a02:8388:6c83:eb90:ff:60ff:feba:b582|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://next.thomas-steinbrenner.net/login [following]
--2022-01-21 11:27:47-- https://next.thomas-steinbrenner.net/login
Reusing existing connection to [next.thomas-steinbrenner.net]:443.
HTTP request sent, awaiting response... 200 OK
Length: 13273 (13K) [text/html]
Saving to: ‘index.html.1’

index.html.1 100%[==========================================================>] 12.96K --.-KB/s in 0s
2022-01-21 11:27:47 (428 MB/s) - ‘index.html.1’ saved [13273/13273]
```

The index.html contains an intact login page.

**Comment by Tie-fighter** [comment]
🤷

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
