### ISSUE TITLE
Files from chunked uploads are not deleted from S3, no ability to view them

### ISSUE THREAD

**Issue by otherguy** [nextcloud/server#30762]
As a fairly new user I just set up Nextcloud via Kubernetes with an S3 (compatible) primary backend for file storage. I have only one user and deleted all the welcome files, also from the trash. `filelocking.enabled` is set to `false`.

The user interface correctly shows 0B used.

My S3 bucket however, shows over 100 objects with over 400MB usage.

<img width="1155" alt="CleanShot 2022-01-19 at 14 37 02@2x" src="https://user-images.githubusercontent.com/6072721/150141464-b71d61a8-fe09-4c1b-a741-3eca674d7628.png">

The `occ` tool gives me no ability to view them and tells me there are no files.

```
k exec -it nextcloud-666466c988-12345 -- su www-data -s /bin/bash -c "php occ files:scan --all"
Starting scan for user 1 out of 1 (admin)
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 0       | 0     | 00:00:00     |
+---------+-------+--------------+
```

Many of the files appear to have exactly the same size but their binary content doesn't tell me what the file is. I assume this is part of a chunked upload that I canceled, because they are referenced in the database as part of `uploads/web-file-upload-*/`.

<img width="1128" alt="CleanShot 2022-01-19 at 14 48 43@2x" src="https://user-images.githubusercontent.com/6072721/150143363-7ea68424-c5b8-49d4-b51e-17d84b9c0eb9.png">

I found a related [help topic](https://help.nextcloud.com/t/chunked-files-are-not-deleted-after-failed-uploads/39792) that was never answered.

So the questions are:
- does Nextcloud, at some point, delete chunks from failed/canceled uploads by itself?
- if not, how can I view those and delete them manually?

**Comment by acsfer** [comment]
This is a known issue, non only multipart but other files too.
Take a look at https://github.com/nextcloud/server/labels/feature%3A%20object%20storage

**Comment by otherguy** [comment]
Thanks! No real solution, but I might need to write a script that searches the database for these canceled uploads and deletes the files manually.

This should really be a part of nextcloud!

**Comment by otherguy** [comment]
I have solved this by writing a cleanup cronjob that deletes chunks older than a given time.

The script is public and can be found here: https://github.com/otherguy/nextcloud-cleanup
