### ISSUE TITLE
Disable BackgroundCleanupJob when previews are disabled

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#30793]
When disabling previews altogether, the job "OC\Preview\BackgroundCleanupJob" is still registered.

Now, it's ok that the job is there still but it shouldn't be performing any database queries.

A fix would add a check in it "run()" function to see if previews are enabled in config.php before proceeding.

**Comment by Lucarnosky** [comment]
Hello, I think I've implemented the solution but I can't test it. When I'm trying to run BackgroundCleanupJobTest.php it give me this error. PHP Fatal error:  Uncaught Error: Class "Test\TestCase" not found. How can I test my modification?

**Comment by PVince81** [comment]
@Lucarnosky see https://docs.nextcloud.com/server/latest/developer_manual/core/unit-testing.html#running-unit-tests-for-the-nextcloud-core-project

`./autotest.sh sqlite lib/Preview/BackgroundCleanupJobTest.php`

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
