### ISSUE TITLE
Unify sharing messages

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#3079]
It seems like we have some inconsistency how re-shares are presented to the user, as noted by @nickvergessen here https://github.com/nextcloud/server/pull/3033#discussion_r96202712

If a user reshares a file file by mail, he gets a mail saying `<owner> shared <file> with you on behalf of <the user who shared it>`

While this is technically correct, it probably doesn't add any useful information for the recipient.

Another interesting situation:

If a file gets reshared internally the recipient gets a activity, saying `<user who shared the file> shared <file> with you`. The owner is not mentioned and I think this is OK. The strange thing here, in the file listing we display the owner and not the user who shared the file next to the share icon. This can lead to confusions. Imaging you get a activity saying "user1 shared a file with you", then you open your browser, look at the file listing and will find no file shared by "user1" because in the file listing we show the owner.

Suggestion: Never show the owner or any "behalf on..." message. Instead only show the initiator. That's the important information for the recipient, mentioning the owner doesn't add any useful additional information.

Opinions? @rullzer @jancborchardt @nextcloud/designers

**Comment by jancborchardt** [comment]
I’ll close this as there wasn’t activity for 2 years. Reopen if it’s still current and important.
