### ISSUE TITLE
Federated cloud share icons overlap in button

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#30819]
See screenshot (22.2.3 here)

![image](https://user-images.githubusercontent.com/12234510/150692735-b6380b03-473c-4f57-954a-4fd2e2cba667.png)

**Comment by shubham2o** [comment]
I would like to work on this, can you please assign me this issue?

**Comment by acsfer** [comment]
Go to /settings/user/sharing

**Comment by Lucarnosky** [comment]
Hello, I see that is some time the issue is not been worked. I've fixed it, if you wanna you can assign this problem to me and I can send the pull request.
