### ISSUE TITLE
PHP 8.1: Return type of OC\\Memcache\\Cache::offsetUnset($offset) should either be compatible

### ISSUE THREAD

**Issue by ckujau** [nextcloud/server#30813]
I could not find this mentioned in #29287 ("Support PHP8.1") or #29862 ("Support PHP 8.1 - Second batch"), this now hitting the logs with PHP-FPM 8.1.2:

```
{
  "reqId": "VwuRT3uwj7cEAbRYDXyv",
  "level": 3,
  "time": "2022-01-22T00:15:02+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "PHP",
  "method": "",
  "url": "--",
  "message": "Return type of OC\\Memcache\\Cache::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily su
ppress the notice at /usr/share/webapps/nextcloud/lib/private/Memcache/Cache.php#93",
  "userAgent": "--",
  "version": "23.0.0.10"
}
```

Everything appears to be working just fine, but maybe this message needs to be taken care of in the future?

**Comment by come-nc** [comment]
Already fixed in master: https://github.com/nextcloud/server/pull/29432/files#diff-b20e24bbb18fc3f9aae629ec2d2761c7d0c919052d1245e4c39dc9e02bedb54fL78
