### ISSUE TITLE
CardDAV Error: VCard object with uid already exists in this addressbook collection

### ISSUE THREAD

**Issue by reos-rcrozier** [nextcloud/server#30827]
### Steps to reproduce

I have Nextcloud installed in my own server, details below. Recently I have started to receieve the follwoing error from my Cron job (which is set to email output to me):

```
Sabre\DAV\Exception\BadRequest: VCard object with uid already exists in this addressbook collection. in /var/www/nextcloud/apps/dav/lib/CardDAV/CardDavBackend.php:667
Stack trace:
#0 /var/www/nextcloud/apps/dav/lib/CardDAV/SyncService.php(276): OCA\DAV\CardDAV\CardDavBackend->createCard()
#1 /var/www/nextcloud/apps/dav/lib/AppInfo/Application.php(231): OCA\DAV\CardDAV\SyncService->updateUser()
#2 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(264): OCA\DAV\AppInfo\Application->OCA\DAV\AppInfo\{closure}()
#3 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch()
#4 /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
#5 /var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php(123): Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
#6 /var/www/nextcloud/lib/private/Accounts/AccountManager.php(278): OC\EventDispatcher\SymfonyAdapter->dispatch()
#7 /var/www/nextcloud/lib/private/Accounts/AccountManager.php(765): OC\Accounts\AccountManager->updateUser()
#8 /var/www/nextcloud/apps/settings/lib/BackgroundJobs/VerifyUserData.php(284): OC\Accounts\AccountManager->updateAccount()
#9 /var/www/nextcloud/apps/settings/lib/BackgroundJobs/VerifyUserData.php(103): OCA\Settings\BackgroundJobs\VerifyUserData->resetVerificationState()
#10 /var/www/nextcloud/cron.php(127): OCA\Settings\BackgroundJobs\VerifyUserData->execute()
#11 {main}
```
I receive the roughly error three times (from three separate runs of cron) each day, and the time this starts varies. I'm not quite sure if I receive this every single day at the moment.

I checked the Contacts app gihub repo, and it stated CardDAV errors should be reported here.

I posted the error on the Nextcloud forum [here](https://help.nextcloud.com/t/vcard-object-with-uid-already-exists-in-this-addressbook-collection/130742). A second user then came forward with the same issue. However, in their case, the Contacts app is reportedly completely disabled. They see the same error when running the cron job manually. 

### Expected behaviour

There should be no error from the Cron job.

### Actual behaviour

I get the error described above

### Server configuration

**Operating system:**

Ubuntu 20.04

**Web server:**

Apache/2.4.41 (Ubuntu)

**Database:**

MariaDB 

**PHP version:**

PHP 7.4.3

**Nextcloud version:** (see Nextcloud admin page)

Nextcloud 22.2.3

**Updated from an older Nextcloud/ownCloud or fresh install:**

Updated from an older Nextcloud

**Where did you install Nextcloud from:**

Source package originally (some years ago, on a different server, in fact 2 servers ago)

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Comment by CorentinS6** [comment]
Upgrade to 23.0.2 don't fix the issue for me.

**Comment by j-ed** [comment]
1. You can try to export a calendar to a file, export **my-file.ics**, and then use the followings 
2. `grep "^UID:" my-file.ics | sort | uniq -c`

**Comment by pacohope** [comment]
I saw this same thing on my instance. Here's what I have done and I think I have fixed it. I'll put all my specs below, but one interesting aspect of my system is that it is very old. Like Nexcloud 10.0 upgraded over and over year after year. So the likelihood of database cruft and weird records in my database is pretty good.

Addressbook 2 appears to be the "System Addressbook", which appears to be created/maintained automatically to contain all users on the system. My nightly cron job was sending me emails, and I was able to reproduce the problem by running `sudo -u www occ dav:sync-system-addressbook --verbose` For me, this `occ` command consistently yielded:
```
Syncing users ...
    2 [->--------------------------] < 1 sec
In CardDavBackend.php line 667:

  [Sabre\DAV\Exception\BadRequest]
  VCard object with uid already exists in this addressbook collection.
```

### quick backup

I logged into my MariaDB with phpMyAdmin. I made a backup table called `oc_cards_backup`. (Browse the `oc_cards` table, choose Operations, then choose "Copy Table" and select "Structure Only"). Then I did this query to make backup copies of the records I was about to delete:
```
INSERT into `oc_cards_backup` select from `oc_cards` where `addressbookid` = 2;
```

### empty the system address book

With the records safely backed up, I deleted them from the `oc_cards` table:
```
DELETE from `oc_cards` where `addressbookid`=2;
```

### recreate the system address book

Then, on my nextcloud server, at the command line, I ran `sudo -u www occ dav:sync-system-addressbook --verbose`. This time I got successful output:
```
Syncing users ...
   24 [============================]  1 sec
```

If I look for those records in my `oc_cards` table, I find them now. Importantly, I have **24** rows in addressbook 2, where my backup table has only 17 rows. Clearly there was some problem that was preventing this job from running, and its failures generated emails. I can't say whether this is YOUR problem or not, but the error messages are basically identical.

The other thing I think is true (but I'm not sure) is that it's harmless to delete these records and then run `occ` to recreate them.

I'm a little bit of the "blind leading the blind" here. I don't know much about Nextcloud. I just kinda hack on stuff and see if I can make errors go away. Hopefully this will give someone else a clue or even a mechanism that works for them, too.

### My setup
* Nextcloud: 22.2.3
* OS: FreeBSD 13.0-RELEASE-p4
* PHP: PHP 7.4.27
* Database: MariaDB 10.4.14
* Interesting Apps: User and Group SQL Backends, Onlyoffice

**Comment by LionelHoudelier** [comment]
The problem has came again. Here my solution:
In a script:
```
#extract the UID of the vcf file (xfile) with:
uid=$(grep UID "$xfile" | sed 's/.*://')
#add it to the curl command url + ".vcf":
curl -X PUT -u "$user":"$pass" "https://${cloud}/remote.php/dav/addressbooks/users/$user/$addressbook/$uid.vcf" -T "$xfile" 
```
then it works
PS: we have to have added first the new contacts with this procedure.

Here is my script to upload a vcf file if it is created or updated in a given folder:
Enter the personal data, run it, and create or update the VCARD_FILE in the folder. It will parse the vcards from it, puts them in temp files, then curl PUT the vcard to the server.

```
#!/bin/bash
#### ENTER YOUR DATAS ##########
# folder to parse the file
temp_folder=/home/.....
# folder where is the vcf file
folder='/home/...'
filename='VCARD_FILE.vcf'
user='XXX'
pass='XXXXX'
addressbook='XXXX'
cloud='your.nextcloud.url'
##########################################################
filepath="$folder""$filename"
url="https://${cloud}/remote.php/dav/addressbooks/users/$user/$addressbook"
# parse the file in multiple random files name
mkdir -p $temp_folder
rm -f $temp_folder/*
echo "$folder"
inotifywait --format="%w%f" -m "$folder" -e moved_to |
    while read file; do
  if [[ "$file" == *".vcf" ]]
  then 
  awk -v temp_folder="$temp_folder" 'BEGIN {
        RS="END:VCARD";
        }
        {
        command = "echo -n '$temp_folder'/$(pwgen 20 1).vcf"
        command | getline filename
        close(command)
        print $0 "END:VCARD" > filename
        close(filename)
        }' "${filepath}"
      for xfile in "$temp_folder"/*.vcf; do
        if grep -q "BEGIN:" "$xfile"; then
          uid=$(grep UID "$xfile"  | sed 's/.*://')
          echo "UID : " "$uid"
          curl -X PUT -u "$user":"$pass" "$url/$uid.vcf" -T "$xfile"
          echo "ok"
          rm "$xfile"
        fi
      done
  fi
done
command = "echo -n '$temp_folder'/$(pwgen 20 1).vcf"
        command | getline filename
        close(command)
        print $0 "END:VCARD" > filename
        close(filename)
        }' "${filepath}"
# upload the files
      for xfile in "$temp_folder"/*.vcf; do
        if grep -q "BEGIN:" "$xfile"; then
      for xfile in "$temp_folder"/*.vcf; do
        if grep -q "BEGIN:" "$xfile"; then
          uid=$(grep UID "$xfile"  | sed 's/.*://')
          echo "UID : " "$uid"
          curl -X PUT -u "$user":"$pass" "$url/$uid.vcf" -T "$xfile"
          echo "ok"
          rm "$xfile"
        fi
      done
  fi
done
```
