### ISSUE TITLE
[Feature Request] -  Add Geo tag in CardDAV

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/server#3083]
There are some Map addins which are able to show some Data. It could be a good Idea to support 
the geo tag in DAV to allow use it with Contact.

http://geouri.org/2010/06/10/geo-and-vcards/

**Comment by nickvergessen** [comment]
Well if SabreDav supports it, we do too. If they don't we might not be able to....

**Comment by Mannshoch** [comment]
A Quick search about GEO in SabreDAV tells me it is something there.
[https://github.com/search?q=org%3Afruux+geo&type=Code](https://github.com/search?q=org%3Afruux+geo&type=Code)

So I have to do a Feature Request on https://github.com/nextcloud/contacts and https://github.com/nextcloud/maps ?

**Comment by nickvergessen** [comment]
Sounds good!
