### ISSUE TITLE
[Bug]: Just testing to make sure it works as it should

### ISSUE THREAD

**Issue by acsfer** [nextcloud/server#30833]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

This is just a test

### Steps to reproduce

1. This is just a test

### Expected behavior

This is just a test

### Installation method

Official VM scripts

### Operating system

Other

### PHP engine version

PHP 7.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

```shell
This is just a test
```

### List of activated Apps

```shell
This is just a test
```

### Nextcloud Signing status

```shell
This is just a test
```

### Nextcloud Logs

```shell
This is just a test
```

### Additional info

This is just a test

**Comment by acsfer** [comment]
@szaimen @artonge

**Comment by artonge** [comment]
Perfect :)
