### ISSUE TITLE
[NC23][Warning][Bug]: upgrade 22.2.3 to 23.0.0 - php 8.1.2 not supported for OCC

### ISSUE THREAD

**Issue by EricThi** [nextcloud/server#30849]
### ⚠️ Before submitting, please verify the following: ⚠️

- [X] This is a **bug**, not a question or a configuration issue.
- [X] This issue is **not** already reported on Github (I've searched it).
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/)

### Bug description

```
sudo -u http php occ db:add-missing-indices
This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.2.
```

### Steps to reproduce

1. upgrade nextcloud 22.x to 23.0.0
2. see warning on admin panel : The database is missing some indexes. Due to the fact that adding indexes on big tables could take some time they were not added automatically. By running "occ db:add-missing-indices" those missing indexes could be added manually while the instance keeps running. Once the indexes are added queries to those tables are usually much faster.
3. launch command occ and get warning for occ and php
...

### Expected behavior

Finish batch to compatibility NC23 and php 8.1
I previously read : 
https://github.com/nextcloud/server/issues/29287
https://github.com/nextcloud/server/pull/29432
https://github.com/nextcloud/server/pull/29862
https://github.com/nextcloud/server/issues/30813

Before upgrade and found error with occ

### Installation method

Manual installation

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### Are you using an external user-backend?

- [X] Default internal user-backend
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
I can't, occ "broken"
```

### List of activated Apps

```shell
I can't, occ "broken"
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
log after upgrade :

{"reqId":"cikiplWb5LzZiJB0XVpm","level":1,"time":"2022-01-26T10:25:49+00:00","remoteAddr":"x.x.x.98","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=token%3D%3AVq097LIceBwq57JNEDUWQwgUt3%2F3Xz7XIPH9KtotzW8%3D","message":"\\OC\\Updater::finishedCheckCodeIntegrity: Finished code integrity check","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0","version":"22.2.3.0"}
{"reqId":"cikiplWb5LzZiJB0XVpm","level":1,"time":"2022-01-26T10:25:49+00:00","remoteAddr":"x.x.x.98","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=token%3D%3AVq097LIceBwq57JNEDUWQwgUt3%2F3Xz7XIPH9KtotzW8%3D","message":"\\OC\\Updater::updateEnd: Update successful","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0","version":"23.0.0.10"}
{"reqId":"cikiplWb5LzZiJB0XVpm","level":1,"time":"2022-01-26T10:25:49+00:00","remoteAddr":"x.x.x.98","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=token%3D%3AVq097LIceBwq57JNEDUWQwgUt3%2F3Xz7XIPH9KtotzW8%3D","message":"\\OC\\Updater::maintenanceDisabled: Turned off maintenance mode","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0","version":"23.0.0.10"}
{"reqId":"cikiplWb5LzZiJB0XVpm","level":1,"time":"2022-01-26T10:25:49+00:00","remoteAddr":"x.x.x.98","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=token%3D%3AVq097LIceBwq57JNEDUWQwgUt3%2F3Xz7XIPH9KtotzW8%3D","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:97.0) Gecko/20100101 Firefox/97.0","version":"23.0.0.10"}
```

### Additional info

nginx -v
nginx version: nginx/1.20.2

php --version
PHP 8.1.2 (cli) (built: Jan 19 2022 17:12:32) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies

OpenSSL> version
OpenSSL 1.1.1m  14 Dec 2021

mariadb --version
mariadb  Ver 15.1 Distrib 10.6.5-MariaDB, for Linux (x86_64) using readline 5.1

uname -a
Linux cloud 5.14.8-arch1-1 #1 SMP PREEMPT Sun, 26 Sep 2021 19:36:15 +0000 x86_64 GNU/Linux

**Comment by szaimen** [comment]
Thanks for your report but lets track php 8.1 compatibility in https://github.com/nextcloud/server/issues/29287
