### ISSUE TITLE
Sync storage quota error, tracked down to NullStorage.php

### ISSUE THREAD

**Issue by mikecardwell** [nextcloud/server#3085]
I am running Nextcloud 11.0.1 on a Debian Jessie box behind Nginx.

I noticed that calendar events that I was adding on my Android phone weren't appearing in the web interface. I forced a sync using CalDav Sync on my Android phone and saw the following logs in my nextcloud.log appear:

```
{"reqId":"ttttbLPPvbEnVElv8lwo","remoteAddr":"192.168.0.1","app":"core","message":"Exception when running cache gc: This request is not allowed to access the filesystem","level":2,"time":"2017-01-16T13:52:03+00:00","method":"PUT","url":"\/remote.php\/dav\/calendars\/mike\/personal\/b079b859-68b6-459a-828a-8fc6d03ae71c.1484574723624.ics","user":"mike","version":"11.0.1.2"}
{"reqId":"ttttbLPPvbEnVElv8lwo","remoteAddr":"192.168.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 507 Insufficient Storage\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\InsufficientStorage\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\QuotaPlugin->checkQuota('calendars\\\/mike\\\/...', Resource id #14, Object(OCA\\\\DAV\\\\CalDAV\\\\Calendar), false)\\n#1 \\\/srv\\\/www\\\/cloud\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/srv\\\/www\\\/cloud\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1070): Sabre\\\\Event\\\\EventEmitter->emit('beforeCreateFil...', Array)\\n#3 \\\/srv\\\/www\\\/cloud\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('calendars\\\/mike\\\/...', Resource id #14, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/srv\\\/www\\\/cloud\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/srv\\\/www\\\/cloud\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/srv\\\/www\\\/cloud\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/srv\\\/www\\\/cloud\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(227): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/srv\\\/www\\\/cloud\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#10 \\\/srv\\\/www\\\/cloud\\\/nextcloud\\\/remote.php(165): require_once('\\\/srv\\\/www\\\/cloud\\\/...')\\n#11 {main}\",\"File\":\"\\\/srv\\\/www\\\/cloud\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/QuotaPlugin.php\",\"Line\":113,\"User\":\"mike\"}","level":4,"time":"2017-01-16T13:52:03+00:00","method":"PUT","url":"\/remote.php\/dav\/calendars\/mike\/personal\/b079b859-68b6-459a-828a-8fc6d03ae71c.1484574723624.ics","user":"mike","version":"11.0.1.2"}
```

First thing I checked was filesystem quotas. They are fine and I'm nowhere near using them up for any user on any partition.

Second thing I checked was user quotas inside Nextcloud. All users have "Unlimited" set.

Disk usage is fine. No partitions are anywhere near full.

So I started digging through the code. I found that the checkQuota function in "apps/dav/lib/Connector/Sabre/QuotaPlugin.php" was throwing the InsufficientStorage error. If I updated it to just always return true, then syncing started working. Obviously, that is not a permanent fix. Further inspection showed that the function was internally calling getFreeSpace which was returning "0". I tracked this back to the "free_space" function in lib/private/Lockdown/Filesystem/NullStorage.php being called, which has "0" hard coded. I know that function was being called because I stuck an "error_log" in it.

NullStorage.php sounds like it should be some sort of placeholder/mock lib, and that the function should never be called. Am I right? 

What further information do you need from me in order to debug this?

**Comment by schiessle** [comment]
Calendar entries are stored in the database. That's probably also why we use a "NullStorage" here, but of course it doesn't make sense to check the quota in this case. @icewind1991 any idea?

**Comment by schiessle** [comment]
Maybe also @georgehrke ... do you have some ideas?

**Comment by Tarry91** [comment]
I have the same warning in my nextcloud logs, but the syncing of the calendar events works fine (iPhone). The log is completely flooded.

**Comment by calis2002** [comment]
I also got the "Exception when running cache gc" messages. Calendar sync works for me too.
`	OC\ForbiddenException: This request is not allowed to access the filesystem

    /var/www/nextcloud/lib/private/Files/View.php - line 1124: OC\Lockdown\Filesystem\NullStorage->mkdir('files_encryptio...')
    /var/www/nextcloud/lib/private/Files/View.php - line 266: OC\Files\View->basicOperation('mkdir', '/USERNAME/files_en...', Array)
    /var/www/nextcloud/lib/private/Encryption/Keys/Storage.php - line 321: OC\Files\View->mkdir('/USERNAME/files_en...')
    /var/www/nextcloud/lib/private/Encryption/Keys/Storage.php - line 212: OC\Encryption\Keys\Storage->keySetPreparation('/USERNAME/files_en...')
    /var/www/nextcloud/lib/private/Encryption/Keys/Storage.php - line 110: OC\Encryption\Keys\Storage->setKey('/USERNAME/files_en...', '-----BEGIN PUBL...')
    /var/www/nextcloud/apps/encryption/lib/KeyManager.php - line 287: OC\Encryption\Keys\Storage->setUserKey('USERNAME', 'publicKey', '-----BEGIN PUBL...', 'OC_DEFAULT_MODU...')
    /var/www/nextcloud/apps/encryption/lib/KeyManager.php - line 246: OCA\Encryption\KeyManager->setPublicKey('USERNAME', '-----BEGIN PUBL...')
    /var/www/nextcloud/apps/encryption/lib/Users/Setup.php - line 77: OCA\Encryption\KeyManager->storeKeyPair('USERNAME', 'CLEARTEXT_PASSWORD', Array)
    /var/www/nextcloud/apps/encryption/lib/Hooks/UserHooks.php - line 166: OCA\Encryption\Users\Setup->setupUser('USERNAME', 'CLEARTEXT_PASSWORD')
    /var/www/nextcloud/lib/private/legacy/hook.php - line 106: OCA\Encryption\Hooks\UserHooks->login(*** sensitive parameters replaced ***)
    /var/www/nextcloud/lib/private/Server.php - line 303: OC_Hook emit('OC_User', 'post_login', Array)
    [internal function] OC\Server->OC\{closure}(Object(OC\User\User), 'CLEARTEXT_PASSWORD')
    /var/www/nextcloud/lib/private/Hooks/EmitterTrait.php - line 99: call_user_func_array(Object(Closure), Array)
    /var/www/nextcloud/lib/private/Hooks/PublicEmitter.php - line 33: OC\Hooks\BasicEmitter->emit('\\OC\\User', 'postLogin', Array)
    /var/www/nextcloud/lib/private/User/Session.php - line 534: OC\Hooks\PublicEmitter->emit('\\OC\\User', 'postLogin', Array)
    /var/www/nextcloud/lib/private/User/Session.php - line 297: OC\User\Session->loginWithToken('XXXXX-XXXXX-XXX...')
    /var/www/nextcloud/lib/private/User/Session.php - line 329: OC\User\Session->login(*** sensitive parameters replaced ***)
    /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php - line 130: OC\User\Session->logClientIn(*** sensitive parameters replaced ***)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php - line 105: OCA\DAV\Connector\Sabre\Auth->validateUserPass(*** sensitive parameters replaced ***)
    /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php - line 252: Sabre\DAV\Auth\Backend\AbstractBasic->check(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php - line 155: OCA\DAV\Connector\Sabre\Auth->auth(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php - line 199: OCA\DAV\Connector\Sabre\Auth->check(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php - line 150: Sabre\DAV\Auth\Plugin->check(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    [internal function] Sabre\DAV\Auth\Plugin->beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466: Sabre\Event\EventEmitter->emit('beforeMethod', Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/apps/dav/lib/Server.php - line 227: Sabre\DAV\Server->exec()
    /var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 30: OCA\DAV\Server->exec()
    /var/www/nextcloud/remote.php - line 165: require_once('/var/www/nextcl...')
    {main}`
