### ISSUE TITLE
[Bug]: When file / folder moved -- recent document list doesnt change

### ISSUE THREAD

**Issue by trickiegt** [nextcloud/server#30861]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Honestly, it's not a big deal and nobody probably cares but it would make for better continuity if it was correct.

Editing a file and then moving it -> Recently edited doesn't know its been moved
The system will attempt to load it from the last known location in which it was edited and it never times out.
I feel like at the very least, it should time out and say that it could not find file at /location/location/file.ext

Anyway, just a thought.
Thanks for everything yall do! Great system and I love it as well as everyone contributing to this project!
-Chris

### Steps to reproduce

How to create condition.
1) Edit a file in file editor
2) Move that file somewhere else
3) Goto "Files" main tab
4) Click on recently modified document (which you moved)

### Expected behavior

Click on Document and it opens document in from new location or timeout and say file not found at /location/file.ext

### Installation method

Official All-in-One appliance

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
honestly, you dont need this.
```

### List of activated Apps

```shell
honestly, you dont need this either.
```

### Nextcloud Signing status

```shell
No need wasting your time with this.
```

### Nextcloud Logs

```shell
Still no need to review this information either
```

### Additional info

Much love =)

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by trickiegt** [comment]
Tested on [Nextcloud Hub 3](https://cloud.~~~.net/) (25.0.2)
I successfully edited a file and it showed in the recent tab...  Then moved the file... clicked on the file from 'recent' list and it did indeed find the file in its new location.

Thanks again for all your hard work and effort!
