### ISSUE TITLE
Mattermost integration

### ISSUE THREAD

**Issue by furai** [nextcloud/server#3086]
Hello,

This is actually more of a feature request than issue. Is nextcloud going to be integrated with https://about.mattermost.com/ ? I'd love to see this happen.

Cheers,
Furai

**Comment by schiessle** [comment]
Can your elaborate on what kind of integration you have in mind? Using Nextcloud as a storage back-end for files uploaded to Mattermost? Let Nextcloud access files uploaded to Mattermost (depending on the APIs of Mattermost this can probably be done with our external storage app).

Something completely different?

**Comment by furai** [comment]
I was thinking of using Nextcloud as storage back-end for files uploaded to Mattermost. Especially that I have self-hosted instance of Nextcloud. That would be really neat to have.

**Comment by jancborchardt** [comment]
Hey @furai, sorry for missing your opened issue on this! Just before I opened a fresh issue with all the background info and existing discussions at https://github.com/nextcloud/server/issues/3202 – let’s continue there because we have all the links to their tracker and their input there too. :)
