### ISSUE TITLE
User Profile - 3 - Global toggle

### ISSUE THREAD

**Issue by Pytal** [nextcloud/server#30866]
- Disable/enable profile feature globally in `config.php` and let admins set the default state which can be overridden by users https://github.com/nextcloud/server/pull/29372

**Comment by grisu48** [comment]
I just came here via the release notes of Nextcloud 23 to complain, that I find it the user profiles a cool feature but a very very very bad decision to make them public by default. I'm sure many people out there have now their user profiles exposed to the public without even knowing.

I for sure was mildly panicking when I checked the `/u/$username` and saw that part of the user information I assumed is only shared instance-internally is accessible to the public without authentication (Real name, Website, Twitter account).

I hope it remains a one-time issue to introduce privacy-hostile defaults for actually cool features on a pretty cool product.
