### ISSUE TITLE
Wrap instance reporting for database schema in an API

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/server#30877]
## Problem
Currently, we're checking for the Database Type of an instance something like this:

```php
$schema->getDatabasePlatform() instanceof PostgreSQL94Platform
 ```

If we ever change the underlying structure, these checks might break.

## Proposed solution

Add a new API method for `ISchemaWrapper` that will return the database type as a string and a few constants that map to the [supported databases](https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/linux_database_configuration.html#:~:text=Nextcloud%20requires%20a%20database%20in,PostgreSQL) to compare the Database string too:

```php

public CONST PostgreSQL94Platform = 'PostgreSQL94Platform';
....

public function getDatabaseType(): string;
```

[Context](https://github.com/nextcloud/mail/pull/5935/files#r792481561)

**Comment by ChristophWurst** [comment]
I'd rather put this onto `\OCP\IDBConnection` to make it also usable outside the context of migrations.

This will be a solid replacement for the leaky `\OCP\IDBConnection::getDatabasePlatform`. Ref https://github.com/nextcloud/server/blob/34f425c1504a79ef81f400862232bbd6776f5f7a/lib/private/DB/ConnectionAdapter.php#L194
