### ISSUE TITLE
[Bug]: SearchOperator on favorite is boolean but never return non-favorite

### ISSUE THREAD

**Issue by Aeredren** [nextcloud/server#30875]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I search for this SearchOperator :
``` php
$searchComparison->type = 'eq';
$searchComparison->field = 'favorite';
$searchComparison->value = false;
```
through ```OCP\Files\Folder::search()```, I expect it to return nodes which **are not** favorite (as the favorite search operator can take a boolean as value). Instead it returns nodes that **are** favorites.

The reason is in  ```OC\Files\Cache\SearchBuilder``` : 

https://github.com/nextcloud/server/blob/3500d8b9805555211438509885b34e5ba60a9c8e/lib/private/Files/Cache/SearchBuilder.php#L163-L165

The value of a ```'favorite'``` searchOperator is never evaluate, and replace by a searchOperator on tags with the value ```'_$!<Favorite>!$_'```

The value of a ```'favorite'``` searchOperator must be check here
https://github.com/nextcloud/server/blob/3500d8b9805555211438509885b34e5ba60a9c8e/lib/private/Files/Cache/SearchBuilder.php#L109-L110
and here
https://github.com/nextcloud/server/blob/3500d8b9805555211438509885b34e5ba60a9c8e/lib/private/Files/Cache/SearchBuilder.php#L122-L123
and the ```searchOperatorMap``` must be inverted if the value is false.

### Steps to reproduce

1. Make a ```SearchOperator mySearchOperator``` with field 'favorite' and value false
2. Call ```Folder::search(mySearchOperator)```

### Expected behavior

Resulting nodes should be the one which **are not** favorite. We have the one which **are** favorite instead

### Installation method

Manual installation

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

SQlite

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
No comment
```

### List of activated Apps

```shell
No comment
```

### Nextcloud Signing status

```shell
No comment
```

### Nextcloud Logs

```shell
No comment
```

### Additional info

No comment

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
