### ISSUE TITLE
Generating preview for RAW files.

### ISSUE THREAD

**Issue by Leicas** [nextcloud/server#3088]
This is more a feature request than an issue.

Each time I update my nextcloud installation, I have to manually redo the modifications in https://github.com/owncloud/core/pull/14878 , is it possible to integrate this into the core code ?

Thanks for all the work done 👍

**Comment by cowai** [comment]
I would appreciate this too.

**Comment by cowai** [comment]
My employer would probably be willing sponsor this. Making CR2 images open in the gallery app and having the preview cache shared among users (for shared external storage), would be a big feature.

**Comment by cowai** [comment]
@Leicas Check out my app: https://github.com/cowai/CameraRawPreviews
You need php-imagick and exiftool.

**Comment by SilentT-FR** [comment]
+1

**Comment by Progdrasil** [comment]
+1

**Comment by MorrisJobke** [comment]
> @Leicas Check out my app: https://github.com/cowai/CameraRawPreviews
> You need php-imagick and exiftool.

cc @rullzer @oparoz If you missed that app.

**Comment by oparoz** [comment]
Thanks @MorrisJobke and @cowai . It's a nice temporary solution.
Our current goal is to have an app to manage these additional media types

**Comment by skjnldsv** [comment]
Hum, what is the status here?
It's been a while, but I'm guessing @cowai's awesome app does the trick? :)

**Comment by IvanKazak** [comment]
Any update on that?

**Comment by skjnldsv** [comment]
Please have a look at the raw camera preview generator app https://github.com/ariselseng/camerarawpreviews
