### ISSUE TITLE
Remove php 7.3 from testing of apps

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#30896]
- [x] https://github.com/nextcloud/activity/pull/714
- [x] https://github.com/nextcloud/files_pdfviewer/pull/556
- [x] https://github.com/nextcloud/firstrunwizard/pull/669
- [x] https://github.com/nextcloud/logreader/pull/644
- [x] https://github.com/nextcloud/nextcloud_announcements/pull/96
- [x] https://github.com/nextcloud/notifications/pull/1143
- [x] https://github.com/nextcloud/password_policy/pull/319
- [x] https://github.com/nextcloud/photos/pull/1020
- [x] https://github.com/nextcloud/privacy/pull/689
- [x] https://github.com/nextcloud/recommendations/pull/476
- [x] https://github.com/nextcloud/serverinfo/pull/357
- [x] https://github.com/nextcloud/viewer/pull/1150
- [x] https://github.com/nextcloud/announcementcenter/pull/431
- [x] https://github.com/nextcloud/backup/pull/178
- [x] https://github.com/nextcloud/circles/pull/923
- [x] https://github.com/nextcloud/data_request/pull/63
- [x] https://github.com/nextcloud/deck/pull/3561
- [x] https://github.com/nextcloud/end_to_end_encryption/pull/276
- [x] https://github.com/nextcloud/files_accesscontrol/pull/230
- [x] https://github.com/nextcloud/files_automatedtagging/pull/534
- [x] https://github.com/nextcloud/files_retention/pull/151
- [x] https://github.com/nextcloud/flow_notifications/pull/43
- [x] https://github.com/nextcloud/groupfolders/pull/1886
- [x] https://github.com/nextcloud/impersonate/pull/147
- [x] https://github.com/nextcloud/quota_warning/pull/90
- [x] https://github.com/nextcloud/sharepoint/pull/117
- [x] https://github.com/nextcloud/spreed/pull/6844
- [x] https://github.com/nextcloud/terms_of_service/pull/679
- [x] https://github.com/nextcloud/text/pull/2137
- [x] https://github.com/nextcloud/user_retention/pull/418
- [x] https://github.com/nextcloud/workflow_pdf_converter/pull/373
- [x] https://github.com/nextcloud/workflow_script/pull/110
- [x] https://github.com/nextcloud/.github/pull/44

**Comment by come-nc** [comment]
@nickvergessen Shouldn’t we add 8.1 as well?

**Comment by artonge** [comment]
Wondering if this could be defined globally 🤔 . @skjnldsv might know that

**Comment by skjnldsv** [comment]
Yes, with org environment, but this is a hard restriction, people might not like it.

**Comment by nickvergessen** [comment]
> Shouldn’t we add 8.1 as well?

One after the other. Especially since dropping would make apps fail after the merge of #29286  but adding 8.1 to server doesn't break anything.
On that note, 8.1 might require a new phpunit version and might therefor require more back and forth

**Comment by nickvergessen** [comment]
> Wondering if this could be defined globally

We can't really as there are many apps which support multiple branches. And e.g. if your app supports 20-23 you need to lint and test on 7.2 + 7.3 as well. This is also the reason why I only send my update to apps with stable branches

**Comment by nickvergessen** [comment]
- [ ] https://github.com/nextcloud/files_pdfviewer/pull/561
- [ ] https://github.com/nextcloud/nextcloud_announcements/pull/97
- [ ] https://github.com/nextcloud/photos/pull/1028
- [ ] https://github.com/nextcloud/privacy/pull/696
- [ ] https://github.com/nextcloud-gmbh/support/pull/132
- [ ] https://github.com/nextcloud/viewer/pull/1157
- [ ] https://github.com/nextcloud/announcementcenter/pull/436
- [ ] https://github.com/nextcloud/backup/pull/185
- [ ] https://github.com/nextcloud/circles/pull/925
- [ ] https://github.com/nextcloud/deck/pull/3582
- [ ] https://github.com/nextcloud/end_to_end_encryption/pull/283
- [ ] https://github.com/nextcloud/groupfolders/pull/1892
- [ ] https://github.com/nextcloud/quota_warning/pull/91

**Comment by nickvergessen** [comment]
Added as todo for next week

**Comment by nickvergessen** [comment]
Adding 8.1 is in https://github.com/nextcloud/server/issues/31817
