### ISSUE TITLE
[Bug]: Favicon in Theeming App not applied.

### ISSUE THREAD

**Issue by hanzbrech** [nextcloud/server#30898]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

A Uploaded Favicon in the Theeming App does not get applied.

Favicon is uploaded as .ico or .png and is shown next to the field. Showing like everything is "correct".
But it does not get applied and shown when opening the site. The default blue Nextcloud favicon is shown.

I saw in html, that a Hetzner Theme is used (just as side Info)

### Steps to reproduce

1. supported Nextcloud host on Hetzner (Storage Share)
2. Adding Theeming App to Instanz via Webinterface
3. Uploading Favicon as PNG or ICO
4. It shows everything right, but does not get applied.
5. 

### Expected behavior

Favicon get applied to the website

favicon is upload currently on this website:
you can check out the problem of getting the default fav
cloud.hanneskleinteich.com

### Installation method

Other

### Operating system

Other

### PHP engine version

Other

### Web server

Other

### Database engine version

Other

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other

### Configuration report

```shell
i do not know, its Hetzner Shared Storage
```

### List of activated Apps

```shell
Calendar, Contact, all default apps and Theeming
```

### Nextcloud Signing status

```shell
Storage Share
```

### Nextcloud Logs

```shell
Storage Share
```

### Additional info

Storage share and on every hosted Storage Share I booked on Hetzner Nextcloud.
Please understand I don't have the technical background here just a user of the Nextcloud.

<img width="533" alt="Bildschirmfoto 2022-01-28 um 18 39 24" src="https://user-images.githubusercontent.com/79469246/151595358-2d9f873c-203d-4b50-a172-1f76b8ebd948.png">

**Comment by szaimen** [comment]
Please see https://help.nextcloud.com/t/favicon-uber-einstellung-design-nicht-aktivierbar-wird-nicht-im-browser-angezeigt/134513/7?u=szaimen
