### ISSUE TITLE
different default values are used for parameters 'preview_max_x`and `preview_max_x`

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#3090]
refers to https://github.com/nextcloud/server/issues/3069

## Expected behavior
For all parameters a default value should be set and the same default value should be used for all appearances in the source code.

## Current behavior
Not all of the parameters are set to a fixed default value, nor have they the same default value assigned in the source code.

As far as I understood the default values of the parameters `preview_max_x` and `preview_max_x` should both be **2048** but other values have been assigned in the source code:

```
+ getSystemValue('preview_max_x', 2048)                            # default value: 2048
- /var/www/htdocs/nextcloud/lib/private/Preview/Generator.php:152
- /var/www/htdocs/nextcloud/lib/private/Preview.php:126
+ getSystemValue('preview_max_x', 1024)                            # <<< wrong value
 - /var/www/htdocs/nextcloud/apps/files_sharing/lib/Controller/ShareController.php:369

getSystemValue('preview_max_y', 2048)                              # default value: 2048
- /var/www/htdocs/nextcloud/lib/private/Preview/Generator.php:153
- /var/www/htdocs/nextcloud/lib/private/Preview.php:127
+ getSystemValue('preview_max_y', 1024)                            # <<< wrong value
  - /var/www/htdocs/nextcloud/apps/files_sharing/lib/Controller/ShareController.php:370
```

### Steps to reproduce
1. search and compare the assigned values in the getSystemValue() call.

#### Server Configuration
OS: Linux 3.2.82
Web server: Apache2 2.4.25
Database: MariaDB 5.5.53
PHP version: 5.6.29
Nextcloud version: 11.0.0

#### Client Configuration
Browser: Mozilla Firefox 50.1.0
Operating system: Windows 7

**Comment by nickvergessen** [comment]
Intended difference.
