### ISSUE TITLE
different default values are used for parameter 'datadirectory`

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#3091]
refers to https://github.com/nextcloud/server/issues/3069

## Expected behavior
For all parameters default values should be set and the same default value should be used for all appearances in the source code.

## Current behavior
Not all of the parameters are set to a fixed default value, nor have they the same default value assigned in the source code.

As far as I understood the default value of the parameter `datadirectory` should be **\OC::$SERVERROOT.'/data'** but other values have been assigned in the source code:
```
+ getSystemValue('datadirectory', \OC::$SERVERROOT.'/data')             # default value !!

+ getSystemValue('datadirectory', \OC::$SERVERROOT . '/data/')          # <<< backslash at the end
  - /var/www/htdocs/nextcloud/apps/files_external/lib/config.php:261
  - /var/www/htdocs/nextcloud/apps/theming/lib/Util.php:131
  - /var/www/htdocs/nextcloud/lib/private/Repair/RepairLegacyStorages.php:162

+ getSystemValue('datadirectory', \OC::$SERVERROOT)                     # <<< '/data' missing
  - /var/www/htdocs/nextcloud/lib/private/Repair/MoveUpdaterStepFile.php:47

+ getSystemValue('datadirectory')                                       # <<< \OC::$SERVERROOT . '/data/' missing
  - /var/www/htdocs/nextcloud/apps/gallery/preview/preview.php:71
  - /var/www/htdocs/nextcloud/apps/files_trashbin/lib/Trashbin.php:893
  - /var/www/htdocs/nextcloud/apps/files_external/lib/Lib/Storage/SFTP.php:210
  - /var/www/htdocs/nextcloud/lib/private/User/User.php:264

+ getSystemValue('datadirectory', '')                                   # <<< \OC::$SERVERROOT . '/data/' missing
  - /var/www/htdocs/nextcloud/lib/private/Template/JSConfigHelper.php:124
  - /var/www/htdocs/nextcloud/lib/private/IntegrityCheck/Iterator/ExcludeFoldersByPathFilterIterator.php:50
+ getSystemValue('datadirectory', null)
  - /var/www/htdocs/nextcloud/lib/private/Repair/UpdateCertificateStore.php:67
```

### Steps to reproduce
1. search and compare the assigned values in the getSystemValue() call.

#### Server Configuration
OS: Linux 3.2.82
Web server: Apache2 2.4.25
Database: MariaDB 5.5.53
PHP version: 5.6.29
Nextcloud version: 11.0.0

#### Client Configuration
Browser: Mozilla Firefox 50.1.0
Operating system: Windows 7

**Comment by MorrisJobke** [comment]
Fix is in #3176
