### ISSUE TITLE
RFE: adding session management to admin functions

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/server#30918]
In the scenario of a security breach being uncovered, of the type where user credentials have been compromised, it should be possible for administrators to access the user session info (as is shown to the users in Settings -> Security) and issue revokes/wipes on a per session basis.

While the existing user management UI allows a revoke/delete option for all devices, in some contexts that's not really appropriate; listing the sessions with the additional info is also part of the diagnosis of the nature and extent of the security breach.

I think access to the per user session info and revoke/wipe command should be available via the occ command as a subset of user, probably "user:session" with subset of :list/:revoke/:wipe <username>.

**Comment by szaimen** [comment]
Hi, would that app work for you? https://apps.nextcloud.com/apps/impersonate

**Comment by putt1ck** [comment]
I'm not a fan of the impersonation approach; if I absolutely need to log in as a user (which is more or less limited to a user reporting an issue that only they are experiencing) then it's done by resetting their password, which leaves a clear, user-visible, audit trail.

**Comment by szaimen** [comment]
Impersonating leaves a log entry, too...

**Comment by putt1ck** [comment]
That's not user visible i.e. with impersonation someone can access a user's account and the user will not know. Changing the password leaves a user visible trail.

**Comment by szaimen** [comment]
Hm... How do you make sure that an admin doesn't simply install the impersonate app and does this either way?

**Comment by putt1ck** [comment]
And we're back to why I'm not a fan of impersonation functionality. We'd know, of course, if someone did that, and given it's against our policies it'd be a disciplinary offence as well as damaging to the reputation of the support team.

**Comment by putt1ck** [comment]
And of course in NC23 we can limit what apps are available https://github.com/nextcloud/server/issues/28569 (obviously with a determined admin with CLI functionality they could still force installation of the impersonate app, but we're deep into bad actor territory at this point)

**Comment by joshtrichards** [comment]
Fixed in #40026
Docs addition was missing. Pending in nextcloud/documentation#12331
