### ISSUE TITLE
OneDrive for Business Support without creating app

### ISSUE THREAD

**Issue by afzl-wtu** [nextcloud/server#30922]
Every university student have Terrabytes of  free storage from the account provided by Office365 mail account.
Please add support for it natively. So that files can be directly uploaded to onedrive in encrypted names, seemlessley shared and videos can be played from nextcloud links.
There is a great [Onedrive client for linux](https://github.com/abraunegg/onedrive) that supports OneDrive for Business may be it can help.

**Comment by szaimen** [comment]
Hi, please ask for this enhancement here: https://github.com/hevelius/files_external_onedrive
