### ISSUE TITLE
different default values are used for parameter 'dbtype`

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#3092]
refers to https://github.com/nextcloud/server/issues/3069

## Expected behavior
For all parameters default values should be set and the same default value should be used for all appearances in the source code.

## Current behavior
Not all of the parameters are set to a fixed default value, nor have they the same default value assigned in the source code.

As far as I understood the default value of the parameter `dbtype` should be **sqlite** but other values have been assigned in the source code:

```
+ getSystemValue('dbtype', 'sqlite')                 # default value !!
- /var/www/htdocs/nextcloud/lib/private/Setup/AbstractDatabase.php:140
- /var/www/htdocs/nextcloud/lib/private/AllConfig.php:438
- /var/www/htdocs/nextcloud/lib/private/App/Platform.php:72
- /var/www/htdocs/nextcloud/lib/private/DB/MDB2SchemaWriter.php:46
- /var/www/htdocs/nextcloud/lib/private/DB/MDB2SchemaWriter.php:53
- /var/www/htdocs/nextcloud/lib/private/Settings/Admin/TipsTricks.php:45

+ getSystemValue('dbtype', '')                       # <<< 'sqlite' missing
  - /var/www/htdocs/nextcloud/core/Command/Db/ConvertType.php:132

+ getSystemValue('dbtype')                           # <<< 'sqlite' missing
  - /var/www/htdocs/nextcloud/apps/survey_client/lib/Categories/Database.php:74
  - /var/www/htdocs/nextcloud/apps/survey_client/lib/Categories/Database.php:81:
  - /var/www/htdocs/nextcloud/apps/survey_client/lib/Categories/Database.php:122
  - /var/www/htdocs/nextcloud/apps/serverinfo/lib/DatabaseStatistics.php:51
  - /var/www/htdocs/nextcloud/apps/serverinfo/lib/DatabaseStatistics.php:58
  - /var/www/htdocs/nextcloud/apps/serverinfo/lib/DatabaseStatistics.php:93
```

### Steps to reproduce
1. search and compare the assigned values in the getSystemValue() call.

#### Server Configuration
OS: Linux 3.2.82
Web server: Apache2 2.4.25
Database: MariaDB 5.5.53
PHP version: 5.6.29
Nextcloud version: 11.0.0

#### Client Configuration
Browser: Mozilla Firefox 50.1.0
Operating system: Windows 7

**Comment by MorrisJobke** [comment]
That's okay. Only the setup calls need to proper default value. This is a mandatory setting and a fallback to the default can be better detected as failure if it is a not allowed value.
