### ISSUE TITLE
different default values are used for parameter 'dbname`

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#3093]
refers to https://github.com/nextcloud/server/issues/3069

## Expected behavior
For all parameters default values should be set and the same default value should be used for all appearances in the source code.

## Current behavior
Not all of the parameters are set to a fixed default value, nor have they the same default value assigned in the source code.

As far as I understood the default value of the parameter `dbname` should be **nextcloud** but other values have been assigned in the source code:

```
+ getSystemValue('dbname', 'owncloud')               # <<< wrong value, should be 'nextcloud'
  - /var/www/htdocs/nextcloud/lib/private/DB/MDB2SchemaWriter.php:43
  - /var/www/htdocs/nextcloud/lib/private/DB/MDB2SchemaReader.php:68

+ getSystemValue('dbname')                           # <<< 'nextcloud' missing
- /var/www/htdocs/nextcloud/apps/survey_client/lib/Categories/Database.php:124
- /var/www/htdocs/nextcloud/apps/survey_client/lib/Categories/Database.php:156
- /var/www/htdocs/nextcloud/apps/serverinfo/lib/DatabaseStatistics.php:95
- /var/www/htdocs/nextcloud/apps/serverinfo/lib/DatabaseStatistics.php:125

+ getSystemValue("dbname");                          # <<< 'nextcloud' missing
  - /var/www/htdocs/nextcloud/lib/private/Repair/InnoDB.php:61
  - /var/www/htdocs/nextcloud/lib/private/Repair/Collation.php:97
```

### Steps to reproduce
1. search and compare the assigned values in the getSystemValue() call.

#### Server Configuration
OS: Linux 3.2.82
Web server: Apache2 2.4.25
Database: MariaDB 5.5.53
PHP version: 5.6.29
Nextcloud version: 11.0.0

#### Client Configuration
Browser: Mozilla Firefox 50.1.0
Operating system: Windows 7

**Comment by MorrisJobke** [comment]
This is a required parameter set during setup (or will be set during setup) -> no need for a default value.
