### ISSUE TITLE
[settings] There are no text strings in Transifex

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#30941]
The following text strings do not appear in Transifex. I can't find them in the source code. Where are they downloaded from?

![obraz](https://user-images.githubusercontent.com/47037905/151807361-a06e54e7-aa83-42de-9dae-1e1ae848fd63.png)
They apply to the "core" module.

@rakekniven do you know anything about it?

**Comment by tcitworld** [comment]
These strings can be found here 

https://github.com/nextcloud/server/blob/4d7bd5a7fca1108aa69653cf01c5846990daa5e1/apps/settings/lib/Controller/CheckSetupController.php#L495-L514

**Comment by Valdnet** [comment]
@tcitworld Thanks for pointing out the place 😉.

@MichaIng The code should be changed so that it can be translated.

**Comment by MichaIng** [comment]
Makes sense. This is done by wrapping the string into `$this->l10n->t('string', [$var1, $var2, ...])`, right? In case of the settings values, the `<code>` tag can be added to the variable, but how to do best with e.g. `<code>opcache.max_accelerated_files</code>` within the text? Making code+endtags variables themselves, making the whole `<code>opcache.max_accelerated_files</code>` a variable or just leaving it literally in the string to be translated?

**Comment by Valdnet** [comment]
> just leaving it literally in the string to be translated?

I also think that it is better to leave it in translation. Then the translator will understand the meaning of the sentence more.

Of course, all text strings from this code should be added to the translation 😉.

**Comment by MichaIng** [comment]
Is there a translation available for the single word "currently", or a "now" or something else with same meaning? This is used as fallback when for some reason the numerical value of the setting cannot be obtained. This should only be possible in case of the interned strings buffer set to zero via `opcache.interned_strings_buffer=0` in which case the value is not defined at all and "currently" is shown instead in the text. In this specific case actually "0" would be a better replacement, but "currently" or "now" is a more generic fallback in case there are other cases/reasons where the numerical value cannot be obtained. I'm open for better suggestions, but when not changing something on the wording, it should be at least translated as well.

**Comment by Valdnet** [comment]
Or maybe "No data" would be good for this solution?

**Comment by MichaIng** [comment]
I fear this causes questions. If really no value can be obtained, and it says "now" or "currently", I guess it has a better chance that admins check for mentioned `opcache.*` setting in their PHP ini files and raise whichever value they find. In the only known case where this is shown, they should find `opcache.interned_strings_buffer=0` and raising this above zero is then the correct way to solve the warning, and the correct recommendation as well, considering the great benefit of the OPcache interned strings buffer, where I cannot imagine any case where not using it (giving that space back to `opcache.memory_usage`) would be better with Nextcloud.

**Comment by MichaIng** [comment]
The circles app has the string `now` for translation: https://www.transifex.com/nextcloud/search/?q=source_text%3Anow
Could be moved to core, I guess, to make it available elsewhere?

However, I opened a PR now with the simplest possible solution, moving variables only into the parameters array, leaving HTML code and the PHP `opcache.*` settings in the translation string: #30950
Please review, I'm open for suggestions whether to move code/settings out of the string.
