### ISSUE TITLE
[Bug]: Username and password fields do not appear on Login page in Chrome if Nextcloud is behind Cloudflare with Rocket Loader enabled

### ISSUE THREAD

**Issue by janipewter** [nextcloud/server#30951]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Pretty much as the title says.

If your NC is proxied through Cloudflare and you have [Rocket Loader](https://support.cloudflare.com/hc/en-us/articles/200168056-What-does-Rocket-Loader-do-) enabled (it's on by default), Chrome will block the login fields due to Content Security Policy:

`Refused to load the script 'https://<removed>.com/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js' because it violates the following Content Security Policy directive: "script-src 'nonce-eDVIU2JENGw3OENlTlRXWEdFblQwK0djUktkQ0hNYmRWY2JNWEx2ZE5wND06aGNHK05BWkNvL1RNUVZueFZqcWc1YVN0Q01NbGM2V2ZOcEd0Q05Hc1g5RT0='". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.`

Disabling Rocket Loader in the Cloudflare control panel resolves this issue.

Server specifics:
linuxserver.io Nextcloud docker running on Unraid behind linuxserver.io Swag docker (nginx + Let's Encrypt)
Whole site behind Cloudflare (orange cloud) to preserve privacy of origin server IP

Nextcloud version 23.0.1 RC3
PHP 7.4

Tested also on Chrome Android with same result. I suspect any browser which respects CSP will have this issue.

Disabling Rocket Loader in Cloudflare fixes the issue 100% of the time.

### Steps to reproduce

1. Put your Nextcloud behind Cloudflare
2. Ensure Rocket Loader is enabled under Speed -> Optimizations
3. Go to Nextcloud login page

### Expected behavior

Login page loads as normal

### Installation method

Other

### Operating system

Other

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
root@5e84f8fde1f9:/config/www/nextcloud# sudo -u abc php occ config:list system
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "<removed>",
            "<removed>"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.1.1",
        "overwrite.cli.url": "https:\/\/<removed>",
        "overwritehost": "<removed>",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "gb",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpport": "465",
        "updatechecker": false,
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "updater.release.channel": "beta",
        "trashbin_retention_obligation": "auto, 30",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60"
    }
}
```

### List of activated Apps

```shell
root@5e84f8fde1f9:/config/www/nextcloud# sudo -u abc php occ app:list
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - bruteforcesettings: 2.3.0
  - camerarawpreviews: 0.7.15
  - checksum: 1.1.3
  - circles: 23.0.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contactsinteraction: 1.4.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_external: 1.15.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - imageconverter: 1.3.2
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - metadata: 0.15.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.2.0
  - unsplash: 1.2.4
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - user_usage_report: 1.7.0
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - dashboard: 6.0.0
  - encryption: 2.0.0
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by flyingstones** [comment]
Thanks for helping me find where the problem is! I already knew that the problem was in the CloudFlare cache, but you! exactly right! It's better to disable that than the whole cache...

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by szaimen** [comment]
Right, this is a config issue caused b the rocket loader feature
