### ISSUE TITLE
wrong default values are used for parameter 'dbtableprefix`

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#3095]
refers to https://github.com/nextcloud/server/issues/3069

## Expected behavior
For all parameters default values should be set and the same default value should be used for all appearances in the source code.

## Current behavior
Not all of the parameters are set to a fixed default value, nor have they the same default value assigned in the source code.

As far as I understood the default value of the parameter `dbtableprefix` should be **nc_** (abbreviation for Nextcloud) but other values have been assigned in the source code:

```
getSystemValue('dbtableprefix', 'oc_')                      # <<< wrong value, should be 'nc_'
- /var/www/htdocs/nextcloud/core/Command/Db/ConvertType.php:235:
- /var/www/htdocs/nextcloud/core/Command/Db/ConvertType.php:254:
- /var/www/htdocs/nextcloud/lib/private/DB/OracleMigrator.php:78
- /var/www/htdocs/nextcloud/lib/private/DB/PgSqlTools.php:51
- /var/www/htdocs/nextcloud/lib/private/DB/Migrator.php:140
- /var/www/htdocs/nextcloud/lib/private/DB/Migrator.php:191
- /var/www/htdocs/nextcloud/lib/private/DB/Migrator.php:294
- /var/www/htdocs/nextcloud/lib/private/DB/MDB2SchemaReader.php:69
```
### Steps to reproduce
1. search and compare the assigned values in the getSystemValue() call.

#### Server Configuration
OS: Linux 3.2.82
Web server: Apache2 2.4.25
Database: MariaDB 5.5.53
PHP version: 5.6.29
Nextcloud version: 11.0.0

#### Client Configuration
Browser: Mozilla Firefox 50.1.0
Operating system: Windows 7

**Comment by nickvergessen** [comment]
We don't want to touch this, since it breaks all the example SQL commands in docs, blog and forum posts for upgraded or newly installed users.

**Comment by j-ed** [comment]
Ok, the `oc_` prefix is already documented in the configuration file.
