### ISSUE TITLE
[Bug]: Update NextCloud 23.0.0 to 23.0.1

### ISSUE THREAD

**Issue by JordanDIG** [nextcloud/server#30956]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I just received an email saying that my NextCloud instance can be updated to version 23.0.1 but when I go to the settings it says that I have the latest version but I am in 23.0.0.
How to solve this problem ?

### Steps to reproduce

Be in version 23.0.0 and go to the settings to update nextcloud

### Expected behavior

Nextcloud updated to 3.0.1

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MySQL

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
"system": {
        "knowledgebaseenabled": false,
        "memcache.local": "\\OC\\Memcache\\ArrayCache",
        "trashbin_retention_obligation": "auto",
        "default_language": "fr",
        "default_phone_region": "FR",
        "default_locale": "fr_FR",
        "defaultapp": "apporder",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.0.10",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "app_install_overwrite": [
            "apporder"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - apporder: 0.14.0
  - breezedark: 23.2.0
  - bruteforcesettings: 2.3.0
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.0.7
  - dashboard: 7.3.0
  - dav: 1.21.0
  - deck: 1.6.0
  - extract: 1.3.3
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_downloadactivity: 1.12.0
  - files_external: 1.15.0
  - files_linkeditor: 1.1.8
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - files_zip: 1.0.0
  - integration_github: 1.0.2
  - integration_gitlab: 1.0.3
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.6
  - metadata: 0.15.0
  - nextcloud_announcements: 1.12.0
  - notes: 4.3.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - onlyoffice: 7.3.0
  - password_policy: 1.13.0
  - passwords: 2022.1.20
  - photos: 1.5.0
  - provisioning_api: 1.13.0
  - quota_warning: 1.13.0
  - ransomware_protection: 1.12.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - socialsharing_email: 2.4.0
  - survey_client: 1.11.0
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.2.0
  - twofactor_u2f: 6.3.0
  - updatenotification: 1.13.0
  - video_converter: 1.0.4
  - viewer: 1.7.0
  - workflow_pdf_converter: 1.8.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - circles
  - contactsinteraction
  - encryption
  - firstrunwizard
  - privacy
  - spreed
  - support
  - systemtags
  - twofactor_admin
  - user_ldap
  - user_status
  - weather_status
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
/
```

### Additional info

/

**Comment by andrewheeler82** [comment]
Nextcloud is getting worse and worse. Are bug fixes tested at all.😭😭😭

**Comment by andyxheli** [comment]
I think they pulled back the update i don't see it available anymore

**Comment by andrewheeler82** [comment]
seems to me they have lost control of their software.

**Comment by brzd** [comment]
See here:
https://github.com/nextcloud/updater_server/pull/707

Seems to be some confusion on the releases.

**Comment by g4njawizard** [comment]
I have the feeling that this isn't the first time this is happening. Happened in the past already twice. 
Only way around for me was to use the beta channel. But yes... got the same as u guys. Notification but no update.

**Comment by PVince81** [comment]
the update got pulled due to a regression, we'll release a new version soon. stay tuned

**Comment by andyxheli** [comment]
@PVince81 so what happens to the people that are already on 23.0.1 ?

**Comment by PVince81** [comment]
> @PVince81 so what happens to the people that are already on 23.0.1 ?

as far as I can see the error https://github.com/nextcloud/server/pull/30930 was only in 22.2.4

so now there's an outstanding issue with LDAP with a broken migration: https://github.com/nextcloud/server/issues/30936

for setups without LDAP, people can simply stay on 23.0.1

**Comment by come-nc** [comment]
> for setups without LDAP, people can simply stay on 23.0.1

Even for setups with LDAP, if the migration to 23.0.1 did not fail, you can stay on it without trouble.
