### ISSUE TITLE
Show in the admin overview if no mail server was configured

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#30962]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Opening the admin overview doesn't show that currently no mail server is configured. This possibly leads to wrong expectations that mails work out of the box. The overview should be the single point of truth regarding the setup.

**Describe the solution you'd like**
It should show that no mail server was configured in order to function correctly. 

**Describe alternatives you've considered**
Adding a section for this into the overview?

**Additional context**
The Overwiew doesn't show that the mail server settings are missing:
![image](https://user-images.githubusercontent.com/42591237/152029203-1c7e56f3-4463-4a55-827d-a57dff4a2453.png)
The basic settings show it but the overview is then no overview anymore as mail sendings won't work...
![image](https://user-images.githubusercontent.com/42591237/152029236-361d9b63-3fbc-4f96-80a7-702d2a26b7da.png)

**Comment by szaimen** [comment]
@nickvergessen @MichaIng could you maybe point me to some code snippets where this should be implemented? That would be much appreciated :)

**Comment by MichaIng** [comment]
See this PR: https://github.com/nextcloud/server/pull/27403/files
- Backend: `apps/settings/lib/Controller/CheckSetupController.php` does the check and sets the flag, which is then passed via `return new DataResponse(` array at the bottom.
- Frontend: `core/js/setupchecks.js` reads the array and forges the HTML accordingly.
- The other two files are the tests which can/need to be extended.

**Comment by szaimen** [comment]
Thanks! Will have a look at this probably tomorrow...
