### ISSUE TITLE
[Bug]: OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache 

### ISSUE THREAD

**Issue by shaun-ba** [nextcloud/server#30988]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Seems like this issue cropping up again?

https://github.com/nextcloud/vm/issues/2039

This has broke my background cron, and happened when I set up apcu.

Running 23.0.1 RC1

### Steps to reproduce

1. install apcu

### Expected behavior

shouldn't break

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)
```

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by shaun-ba** [comment]
@szaimen Sorry how can you tell that exactly? The previous report of this error message was 100% a bug. I followed all steps correctly and cannot see any error logs that would suggest this is a setup issue.

**Comment by creopard** [comment]
It is a setup issue.
Please find the solution how to modify the cron job:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html#id1

This issue was posted before and there are also mentions of the appropriate solution, e.g:
https://github.com/nextcloud/server/issues/27781
