### ISSUE TITLE
[Bug]: index.php not rendering due to syntax error

### ISSUE THREAD

**Issue by colluca** [nextcloud/server#30983]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I installed the Nextcloud server (version 23.0.0) following the official installation guide for Ubuntu 20.04 based on the LAMP stack.

When I open the homepage `index.php` on a browser I do not see the rendered page, but the source code.

The file is apparently missing a closing `?>` at the end. I added this and it renders correctly.

### Steps to reproduce

1. Follow [installation guide](https://docs.nextcloud.com/server/latest/admin_manual/installation/example_ubuntu.html) for Ubuntu 20.04 
2. Open the homepage at example-domain.com/index.php

### Expected behavior

Expect the source code of `index.php` to appear instead of the rendered webpage.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - bruteforcesettings: 2.3.0
  - circles: 23.0.0
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```

**Comment by szaimen** [comment]
Feel free to provide a PR for discussion

**Comment by MichaIng** [comment]
The `?>` at the end of the file is optional, commonly skipped by most PHP applications. If you see the source code, then it is not a syntax error (which would lead to a 5xx error) but that the webserver does not forward the request to PHP.

When you use Apache2, either you need to install and enable mod_php (the `libapache2-mod-php` package on Debian/Ubuntu), or use the dedicated PHP-FPM (`php-fpm` package on Debian/Ubuntu) handler with event MPM and `proxy_fcgi` module to forward `*.php` requests. The PHP package provides an Apache2 configuration for this, MPM and modules however need to be enabled manually.
