### ISSUE TITLE
[Bug]: IAddressBook#search() sometimes returns contacts with the photo property as a HTTP URL that requires user authentication

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/server#30982]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

[IAddressBook#search()](https://nextcloud-server.netlify.app/classes/ocp-iaddressbook#method_search) sometimes returns contacts with the photo property as a HTTP URL that requires user authentication.

So far both cases are running NC 22.2.3.0

See https://github.com/marcelklehr/recognize/issues/139 and https://github.com/marcelklehr/recognize/issues/137

### Steps to reproduce

1. Upload contacts with pictures from iOS (possibly from other clients as well)
2. Call [IAddressBook#search()](https://nextcloud-server.netlify.app/classes/ocp-iaddressbook#method_search)
3. Get a URI that requires authentication

### Expected behavior

Get a URI not requiring authentication or get a binary blob.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
at least recognize and contacts
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
