### ISSUE TITLE
different default values are used for parameter 'default_language`

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#3098]
refers to https://github.com/nextcloud/server/issues/3069

## Expected behavior
For all parameters default values should be set and the same default value should be used for all appearances in the source code.

## Current behavior
Not all of the parameters are set to a fixed default value, nor have they the same default value assigned in the source code.

As far as I understood the default value of the parameter `default_language` should be **en** but other values have been assigned in the source code:

```
+ getSystemValue('default_language', 'en')                # ok, default value !!
- /var/www/htdocs/nextcloud/apps/activity/lib/BackgroundJob/EmailNotification.php:109

+ getSystemValue('default_language', false)               # <<< wrong value, should be 'en'
  - /var/www/htdocs/nextcloud/lib/private/L10N/Factory.php:16
```

### Steps to reproduce
1. search and compare the assigned values in the getSystemValue() call.

#### Server Configuration
OS: Linux 3.2.82
Web server: Apache2 2.4.25
Database: MariaDB 5.5.53
PHP version: 5.6.29
Nextcloud version: 11.0.0

#### Client Configuration
Browser: Mozilla Firefox 50.1.0
Operating system: Windows 7

**Comment by nickvergessen** [comment]
No, false is used here, to check if a value is set. It will fallback to en in the end, but in case it returns false here, we dont need to check availability of the default language, because en is always available.
