### ISSUE TITLE
different default values are used for parameter 'trashbin_retention_obligation`

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#3099]
refers to https://github.com/nextcloud/server/issues/3069

## Expected behavior
For all parameters default values should be set and the same default value should be used for all appearances in the source code.

## Current behavior
Not all of the parameters are set to a fixed default value, nor have they the same default value assigned in the source code.

As far as I understood the default value of the parameter `trashbin_retention_obligation` should be **auto** but other values have been assigned in the source code:

```
+ getSystemValue('trashbin_retention_obligation', 'auto')   # ok, default value !!
- /var/www/htdocs/nextcloud/apps/files_trashbin/lib/Expiration.php:52

+ getSystemValue('trashbin_retention_obligation', null)     # <<<wrong value, should be 'auto'
  - /var/www/htdocs/nextcloud/apps/files_trashbin/appinfo/update.php:29
```

### Steps to reproduce
1. search and compare the assigned values in the getSystemValue() call.

#### Server Configuration
OS: Linux 3.2.82
Web server: Apache2 2.4.25
Database: MariaDB 5.5.53
PHP version: 5.6.29
Nextcloud version: 11.0.0

#### Client Configuration
Browser: Mozilla Firefox 50.1.0
Operating system: Windows 7

**Comment by nickvergessen** [comment]
Same here, null is used to check if the value is set, if it is the update is skipped.
