### ISSUE TITLE
different default values are used for parameter 'mail_domain`

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#3100]
refers to https://github.com/nextcloud/server/issues/3069

## Expected behavior
For all parameters default values should be set and the same default value should be used for all appearances in the source code.

## Current behavior
Not all of the parameters are set to a fixed default value, nor have they the same default value assigned in the source code.

As far as I understood the default value of the parameter `mail_domain` should be **$host_name** but other values have been assigned in the source code:

```
+ getSystemValue('mail_domain', $host_name)               # host name is a good choice!
  - /var/www/htdocs/nextcloud/lib/public/Util.php:382

getSystemValue('mail_domain', '')                         # <<< should be '$host_name'
- /var/www/htdocs/nextcloud/lib/private/Settings/Admin/Additional.php:56

+ getSystemValue('mail_domain', 'domain.org')             # <<< bad choice because this is an
                                                          # <<< officially registered domain,
                                                          # <<< should be '$host_name'
  - /var/www/htdocs/nextcloud/apps2/calendar/controller/viewcontroller.php:291
```

### Steps to reproduce
1. search and compare the assigned values in the getSystemValue() call.

#### Server Configuration
OS: Linux 3.2.82
Web server: Apache2 2.4.25
Database: MariaDB 5.5.53
PHP version: 5.6.29
Nextcloud version: 11.0.0

#### Client Configuration
Browser: Mozilla Firefox 50.1.0
Operating system: Windows 7

**Comment by MorrisJobke** [comment]
> getSystemValue('mail_domain', '')                         # <<< should be '$host_name'
> - /var/www/htdocs/nextcloud/lib/private/Settings/Admin/Additional.php:56

This is valid there. 

> + getSystemValue('mail_domain', $host_name)               # host name is a good choice!
>   - /var/www/htdocs/nextcloud/lib/public/Util.php:382

Makes only sense because the default there is used to create the default email address. So it makes no sense to use this also as mail_domain default.

The calendar one needs to be fixed in the calendar app.
