### ISSUE TITLE
[Bug]: webDAV should disallow user password after enabling SSO

### ISSUE THREAD

**Issue by theoneandonly-vector** [nextcloud/server#31016]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

username + userpassword is still allowed on webdav after enabling SSO.
there needs to be an option to only allow app-tokens,
otherwise 2FA in SSO doesn't make sense.

### Steps to reproduce

1. Install Nextcloud
2. Setup SSO for nextcloud
3. Navigate to remote.php/webdav

### Expected behavior

username + app-password is allowed, but username + userpassword is not.

### Installation method

Official SNAP package

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.8.0
  - bruteforcesettings: 2.3.0
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contactsinteraction: 1.3.0
  - dav: 1.19.0
  - deck: 1.5.5
  - external: 3.9.0
  - extract: 1.3.3
  - federatedfilesharing: 1.12.0
  - files: 1.17.0
  - files_lock: 20.1.0
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - jsloader: 1.5.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharelisting: 1.0.0
  - spreed: 12.2.3
  - systemtags: 1.12.0
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - user_ldap: 1.12.1
  - user_saml: 4.1.1
  - user_status: 1.2.0
  - viewer: 1.6.0
  - workflowengine: 2.4.0
```

**Comment by szaimen** [comment]
yep: https://github.com/nextcloud/server/blob/88ded737ce61a7d05f871ab6c79281baa04b8cff/config/config.sample.php#L276-L283

**Comment by theoneandonly-vector** [comment]
@szaimen 
I set:
```
  'token_auth_enforced' => 'true',
```
but it still lets me login like this:
https://mynextcloud/index.php/login?direct=1

**Comment by l00v3** [comment]
> @szaimen I set:
> 
> ```
>   'token_auth_enforced' => 'true',
> ```
> 
> but it still lets me login like this: https://mynextcloud/index.php/login?direct=1

This is still the case in 27.0.2. If we have OIDC enabled (with 2FA), users (or somebody else with a password) can login directly and bypass OIDCs 2FA. That is a huge security issue for this configuration. How can we totally disable normal Nextcloud login?
Also  'hide_login_form' => true  - does not hide the login form if we use ?direct=1 in URL.
This issue should not be closed, how can we reopen it? I will open a new one if this one cannot be reopened.
Thank you!
