### ISSUE TITLE
Caching mount points per user

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#31012]
Goal: Avoid database queries during setupFS 

- Idea to cache mountpoints (could be sharing or all others like groupfolders)
- Caching instead of querying the mount providers per user with short TTL
- Caching could happen in lots of places (Redis, APCu, Filesystem)
- Invalidate the cache
  - Adding mount point
  - Renaming a mount point
  - Deleting a mount point
  - During membership change of Talk rooms, Deck boards, circles, group folders, groups, external storage group changes
- Clarify what exactly needs to be cached from the MountPoint object 
- Risks
  - Talk has long running requests, so the request could have been started before the cache was invalidated
  - Users need to wait until the cache gets invalidated if we miss a case
  - Potentially affected apps are only ones that register mount points 

### Additional ideas
- Cache per mount provider instead of all mounts
  - Allows exceptional handling of individual providers, to only enabled it for ones that are not that problematic (e.g. caching for federated shares could be turned off)
  - Benefit to iteratively be able to work on it on the apps once server part is finished

## Next steps
- [ ] Build a prototype (possibly with a config switch)

**Comment by PVince81** [comment]
@icewind1991 please review the above proposal and extend with more technical details, like:
- how is the mountpoint list stored in PHP
- at what point in the code do we need to interact with the cache
- see "clarification" parts
- ...

**Comment by icewind1991** [comment]
In general, just caching a list of mountpoints isn't to useful atm.

There is an (in database) cache of the mount points for the user, which is used to optimize some cases.

https://github.com/nextcloud/server/pull/30978 has come early work for trying to make that cache usable in more cases by allowing more selected setup of the filesystem for more cases.

Once the logic is in place for that I can look into if it makes sense to do more aggressive caching.

**Comment by PVince81** [comment]
To clarify:
- the information to put in the cache is similar to what we already have in `oc_mounts`
- the information in `oc_mounts` is not enough as we need the mount provider class name to be able to tell it to setup the mount, so https://github.com/nextcloud/server/pull/30978 will bring this part

**Comment by PVince81** [comment]
released as part of 24 beta1

the only part that was not done is caching oc_mounts in redis, this could be done separately if needed (would probably save just 1 DB query)
