### ISSUE TITLE
Nextcloud support for Vitess.io / Planetscale databases? 🌎

### ISSUE THREAD

**Issue by pcgeek86** [nextcloud/server#31034]
Has Nextcloud ever been tested against the open source, shardable Vitess database? It would be pretty cool if it worked, although one major drawback of Vitess is that it doesn't support foreign key relationships across shards.

https://vitess.io/docs/12.0/user-guides/vschema-guide/shared-vindexes/

Planetscale uses Vitess under the hood, and they provide a generous 10 GB free tier. That would make an awesome data store for small, self-managed Nextcloud environments.

For larger deployments of Nextcloud, I would imagine that performance would benefit significantly from the horizontal sharding that Vitess offers.

**Comment by szaimen** [comment]
Hello, please ask your question here: https://help.nextcloud.com
Thanks!
