### ISSUE TITLE
[Bug]:Importing ics in one calendar fails in another calendar it can be imported

### ISSUE THREAD

**Issue by DigiNecro** [nextcloud/server#31049]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I'm trying to import a ics-File [ical-1644195858-a1c863538540cc678e6ed9b5e11757c5.txt](https://github.com/nextcloud/server/files/8014372/ical-1644195858-a1c863538540cc678e6ed9b5e11757c5.txt).

I tried importing with Thunderbird and nextcloud webgui.

In one calendar it works (https://DOMAIN.TDL/remote.php/dav/calendars/USER/privat/), in another not (https://DOMAIN.TDL/remote.php/dav/calendars/USER/privat/   This one I named: Rund ums Haus). It doesn't matter if I use the webgui oder Thunderbird, the behaviour is the same for both calenders.

I tried deleting the events from "privat" and clearing the trash bin. 

In webgui there is no error message but is not imported.

In Thunderbird I get this error:
```
Calendar: CalDAV: Unexpected status adding item to Nextcloud Christian (Rund ums Haus): 412
BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VEVENT
DTSTAMP:20220207T010418Z
UID:event-uid37
SUMMARY:Kunststoffe und Metalle
DTSTART;VALUE=DATE:20220207
DTEND;VALUE=DATE:20220207
END:VEVENT
END:VCALENDAR
```

Request:
```
PUThttps://DOMAIN.TDL/remote.php/dav/calendars/USER/hausss/event-uid37.ics
[HTTP/2 412 Precondition Failed 5445ms]

1 BEGIN:VCALENDAR
2 PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
3 VERSION:2.0
4 BEGIN:VEVENT
5 DTSTAMP:20220207T010418Z
6 UID:event-uid37
7 SUMMARY:Kunststoffe und Metalle
8 DTSTART;VALUE=DATE:20220207
9 DTEND;VALUE=DATE:20220207
10 END:VEVENT
11 END:VCALENDAR

```

Answer:
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\PreconditionFailed</s:exception>
  <s:message>An If-None-Match header was specified, but the ETag matched (or * was specified).</s:message>
  <s:header>If-None-Match</s:header>
</d:error>
```

I can create, change and delete events in both calendars (Thunderbird and webgui) even other ics importing works ([ferien_2022.txt](https://github.com/nextcloud/server/files/8014566/ferien_2022.txt))

I think only the calendar hausss has a problem. How can I solve this without creating a new calendar? 

### Steps to reproduce

1.  Importing ics in Calendar https://DOMAIN.TDL/remote.php/dav/calendars/USER/hausss/ => Doesn't work

### Expected behavior

Events should be imported.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MariaDB

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "DOMAIN.TDL"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.4.3",
        "overwrite.cli.url": "https:\/\/DOMAIN.TDL",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "appstore.experimental.enabled": true,
        "ldapIgnoreNamingRules": false,
        "mail_smtpmode": "smtp",
        "forcessl": true,
        "loglevel": 2,
        "blacklisted_files": [
            ".htaccess"
        ],
        "theme": "",
        "maintenance": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "stable",
        "singleuser": false,
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "auth.bruteforce.protection.enabled": false,
        "app_install_overwrite": [
            "calendar",
            "cookbook",
            "ocsms"
        ],
        "logtimezone": "Europe\/Berlin",
        "default_phone_region": "DE",
        "has_rebuilt_cache": true,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - bookmarks: 10.0.3
  - calendar: 3.0.5
  - circles: 22.2.0
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.7
  - contactsinteraction: 1.3.0
  - cookbook: 0.9.9
  - dashboard: 7.2.0
  - dav: 1.20.0
  - deck: 1.5.5
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_markdown: 2.3.5
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - firstrunwizard: 2.11.0
  - groupfolders: 10.0.2
  - health: 1.5.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notes: 4.3.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - ocsms: 2.2.0
  - password_policy: 1.12.0
  - phonetrack: 0.7.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - quota_warning: 1.13.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - spreed: 12.2.3
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - tasks: 0.14.2
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.12.0
  - user_ldap: 1.12.2
  - user_status: 1.2.0
  - viewer: 1.6.0
  - workflowengine: 2.4.0
Disabled:
  - bruteforcesettings: 2.3.0
  - encryption
  - files_external
  - files_videoplayer: 1.10.0
  - text: 3.2.0
  - weather_status: 1.0.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
-
```

### Additional info

Brave: [Version 1.35.100 Chromium: 98.0.4758.87 (Offizieller Build) (64-Bit)]

Thunderbird: 91.5.1 (64-Bit) + TbSync 3.0.1 + Provider für CalDAV & CardDAV 2.0.2

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by DigiNecro** [comment]
The above mentioned ics  seems still not working (checked with 24.0.9 and 25.0.3). 
But this file is meanwhile outdated. With newer files it works. 
So it isn't a problem anymore for me.

**Comment by szaimen** [comment]
Okay, thanks for checking!

**Comment by DigiNecro** [comment]
You're welcome!
