### ISSUE TITLE
[Bug]: File drop (Upload Only) styling issue starting from version 23

### ISSUE THREAD

**Issue by kemoantemo** [nextcloud/server#31040]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After updating to the new version (23) Hub II, I've seen this issue and I was thinking that this is only my instance so I've freshly started a new demo instance to test if that a public problem or just me and here is the results

### Steps to reproduce

docker-compose Deployment

### Expected behavior

with the nextcloud:apache tag for the image which installs the 23.0.1 image I got this.
![Screenshot 2022-02-07 090622](https://user-images.githubusercontent.com/19779701/152742265-0d23aa65-3724-43f2-b9c0-c8160e7d8b51.png)

And then I started another fresh instance with the tag nextcloud:22-apache and I got this and it was correct.
![Screenshot 2022-02-07 091023](https://user-images.githubusercontent.com/19779701/152742283-5de5742f-a84c-412d-b23e-5da92cadbc44.png)

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
only the default installation
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by acsfer** [comment]
@CarlSchwan is this related to your centering work on public pages recently? 🤔
