### ISSUE TITLE
[Bug]: Changes done by different users on the same external storage (SMB) are not propagated to all users syncing the share with NDC

### ISSUE THREAD

**Issue by casasfernando** [nextcloud/server#31067]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When more than one user have access to the same external share (SMB) and they use Nextcloud Desktop client as the only mean to access the share, they can easily end up with a "partial view" of the real content of the share. Meaning that they will never see changes done (added/modified/deleted files and folders) by other users on the same share replicated locally because Nextcloud Desktop client will not get the changes from the server.

As a workaround to prevent this the server administrator can create a cron job of "occ files:scan" on the share for each user that have access to it. Obviously this workaround doesn't scale at all and can easily become a nightmare if you have more than a dozen users accessing the share and it can get even worst if you have several shares that can be accessed by more than one user.

I think this was already reported in https://github.com/nextcloud/server/issues/15033 but unfortunately that issue was already closed due to inactivity without a solution. @szaimen mentioned there https://github.com/nextcloud/server/issues/15033#issuecomment-866977827 that he thinks is a duplicate of https://github.com/nextcloud/server/issues/23988 which may be partially correct.

### Steps to reproduce

I will try to describe the scenario as best as possible.

Nextcloud server version: 23.0.0.10
Nextcloud Desktop client version: 3.4.1 (Debian)
Storage: external storage using SMB to access a shared folder on a Windows fileserver. The storage name is TeamShare. All users have read/write access to this external storage.
Client computers: three different client computers. ComputerA, ComputerB and ComputerC.
Users: two different users. UserA, working from ComputerA and ComputerC, and UserB working only on ComputerB

Nextcloud desktop client is configured exactly in the same way on the three computers. It will sync TeamShare locally. After the initial sync all computers have exactly the same data locally no matter the user working on each.

1. UserA, working from ComputerA, creates a new file locally in the TeamShare folder synced by Nextcloud Desktop client. The new file is synced to the Nextcloud server on next synchronization without any problems.
2. UserA working from ComputerC, get this update on the next Nextcloud Desktop client sync and the new file created in step 1 is successfully synced locally. On the other hand UserB, working on ComputerB which also have Nextcloud Desktop client configured to sync TeamShare, doesn't get the update and the new file created in step 1 is never synced.
3. UserB working from ComputerB, creates a new subfolder locally in the TeamShare folder synced by Nextcloud Desktop client. The new subfolder is synced to the Nextcloud server on the next synchronization without any problems.
4. UserA working from ComputerA and UserA working from ComputerC doesn't get the update and the new subfolder created in step 3 is never synced.

All the computers end up with different content in the local replica of TeamShare.

### Expected behavior

In step 2 above, UserB working from ComputerB should also get the change done by UserA working from ComputerA in TeamShare on step 1 in the next Nextcloud Desktop client sync and correctly sync the new file created in the same way as UserA working from ComputerC.
In step 4 above, UserA working from ComputerA and ComputerC should also get the change done by UserB working from ComputerB in TeamShare on step 3 in the next Nextcloud Desktop client sync and correctly sync the new subfolder created.

Bottom line all users that sync the same external share (SMB) through Nextcloud Desktop client should be able to get all the changes done by any user on the share and replicated them locally to keep the local replicate in sync with the content of the share.

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "filelocking.enabled": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***:8085",
            "***REMOVED SENSITIVE VALUE***:8085",
            "***REMOVED SENSITIVE VALUE***:8448",
            "***REMOVED SENSITIVE VALUE***:8448",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "dbtype": "mysql",
        "version": "23.0.0.10",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "overwritecondaddr": "^XXX\\.XXX\\.XXX\\.XXX$",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 30",
        "default_phone_region": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - bruteforcesettings: 2.3.0
  - calendar: 3.0.5
  - checksum: 1.1.3
  - circles: 23.0.0
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.0.7
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_external: 1.15.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - news: 17.0.1
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - richdocuments: 5.0.1
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - tasks: 0.14.2
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.13.0
  - user_ldap: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - encryption
```

**Comment by glorenzutti** [comment]
Im on the same page than you.

Waiting for a solution...

I did try leaving the notify smb client running. But this didnt solve the problem either.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
