### ISSUE TITLE
[Bug]: Failed to create document from template & failed to initialize templates directory to user language..

### ISSUE THREAD

**Issue by NiTRoeSE** [nextcloud/server#31070]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Some users got the error message "Failed to create document from template" while creating a new document (onlyoffice) in Nextcloud. The same users also can not create a template folder and get error message "failed to initialize templates directory to user language.."..

In Server logs the error messages are in both case the same:
Invalid path --> The path is always "/null/document_name.docx"

Creating new document exception:

`{file=/var/www/nextcloud/apps/files/lib/Controller/TemplateController.php, line=57, function=createFromTemplate, class=OC\Files\Template\TemplateManager, type=->, args=[/null/22.docx, /Vorlagen/vorlage1.docx, user]}, {file=/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php, line=217, function=create, class=OCA\Files\Controller\TemplateController, type=->, args=[/null/22.docx, /Vorlagen/vorlage1.docx, user]}, {file=/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php, line=126, function=executeController, class=OC\AppFramework\Http\Dispatcher, type=->, args=[{__class__=OCA\Files\Controller\TemplateController}, create]}, {file=/var/www/nextcloud/lib/private/AppFramework/App.php, line=156, function=dispatch, class=OC\AppFramework\Http\Dispatcher, type=->, args=[{__class__=OCA\Files\Controller\TemplateController}, create]}, {file=/var/www/nextcloud/lib/private/Route/Router.php, line=302, function=main, class=OC\AppFramework\App, type=::, args=[OCA\Files\Controller\TemplateController, create, {__class__=OC\AppFramework\DependencyInjection\DIContainer}, {_route=ocs.files.Template.create}]}, {file=/var/www/nextcloud/ocs/v1.php, line=62, function=match, class=OC\Route\Router, type=->, args=[/ocsapp/apps/files/api/v1/templates/create]}, {file=/var/www/nextcloud/ocs/v2.php, line=23, args=[/var/www/nextcloud/ocs/v1.php], function=require_once}`

Creating template folder exception:

`{file=/var/www/nextcloud/lib/private/Files/Node/Folder.php, line=146, function=get, class=OC\Files\Node\Root, type=->, args=[/klemm.uwe/files/null]}, {file=/var/www/nextcloud/lib/private/Files/Template/TemplateManager.php, line=306, function=get, class=OC\Files\Node\Folder, type=->, args=[/null]}, {file=/var/www/nextcloud/apps/files/lib/Controller/TemplateController.php, line=68, function=initializeTemplateDirectory, class=OC\Files\Template\TemplateManager, type=->, args=[/null/Vorlagen, null, true]}, {file=/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php, line=217, function=path, class=OCA\Files\Controller\TemplateController, type=->, args=[/null/Vorlagen, true]}, {file=/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php, line=126, function=executeController, class=OC\AppFramework\Http\Dispatcher, type=->, args=[{__class__=OCA\Files\Controller\TemplateController}, path]}, {file=/var/www/nextcloud/lib/private/AppFramework/App.php, line=156, function=dispatch, class=OC\AppFramework\Http\Dispatcher, type=->, args=[{__class__=OCA\Files\Controller\TemplateController}, path]}, {file=/var/www/nextcloud/lib/private/Route/Router.php, line=302, function=main, class=OC\AppFramework\App, type=::, args=[OCA\Files\Controller\TemplateController, path, {__class__=OC\AppFramework\DependencyInjection\DIContainer}, {_route=ocs.files.Template.path}]}, {file=/var/www/nextcloud/ocs/v1.php, line=62, function=match, class=OC\Route\Router, type=->, args=[/ocsapp/apps/files/api/v1/templates/path]}, {file=/var/www/nextcloud/ocs/v2.php, line=23, args=[/var/www/nextcloud/ocs/v1.php], function=require_once}`

### Steps to reproduce

I don´t know.. only some users are affected. But all have together that storage is SMB Storage.

### Expected behavior

Creation of new documents and template folder should work.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

After upgrade from 21.03 to 22.2.3.0 ( maybe it was also present in 21.03 ) 

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.mydomain.de",
            "10.1.1.12"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "22.2.3.0",
        "overwrite.cli.url": "https:\/\/nextcloud.mydomain.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "skeletondirectory": "\/opt\/nextcloud\/skeleton",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "default_language": "de",
        "default_locale": "de_DE",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpstreamoptions": {
            "ssl": {
                "allow_self_signed": true,
                "verify_peer": false,
                "verify_peer_name": false
            }
        },
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "activity_expire_days": 30,
        "updater.release.channel": "stable",
        "default_phone_region": "DE"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - announcementcenter: 6.1.1
  - bbb: 2.2.0
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - deck: 1.5.5
  - drawio: 1.0.2
  - external: 3.9.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_external: 1.13.0
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_videoplayer: 1.11.0
  - integration_moodle: 1.0.2
  - integration_zammad: 1.0.3
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - onlyoffice: 7.3.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - polls: 3.4.2
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - quicknotes: 0.7.3
  - quota_warning: 1.13.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - text: 3.3.0
  - theming: 1.13.0
  - theming_customcss: 1.10.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_ldap: 1.12.1
  - user_saml: 4.1.1
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - comments
  - contacts
  - encryption
  - files_versions
  - firstrunwizard
  - nextcloud_announcements
  - previewgenerator
  - sharebymail
  - support
  - survey_client
  - systemtags
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

To much sensitive information .. relevant error messages are above..

### Additional info

We use SMB Storage / Homefolders from every user are connected through External Storage module, user must insert his credentials in personal settings.

**Comment by slater0013** [comment]
Hello,
Can confirm the bug on 21.0.7

Happens only if you mark a folder as favorites, or if you share it. Then you need to browse via the left menu "Favorites" or "Shared with..." and try to create a file inside it.

Should have been fixed with #26672 (backported in 21.0.5) but It's not.

GS

**Comment by szaimen** [comment]
Hi, I think this will be fixe with https://github.com/nextcloud/server/pull/30995/files. Can you confirm?

**Comment by NiTRoeSE** [comment]
> Hi, I think this will be fixe with https://github.com/nextcloud/server/pull/30995/files. Can you confirm?

I tested that potential fix in our live instance but unfortunately it didn't fix the problem.

**Comment by NiTRoeSE** [comment]
> Hello, Can confirm the bug on 21.0.7
> 
> Happens only if you mark a folder as favorites, or if you share it. Then you need to browse via the left menu "Favorites" or "Shared with..." and try to create a file inside it.
> 
> Should have been fixed with #26672 (backported in 21.0.5) but It's not.
> 
> GS

I have tested this and it happens also on folders which are not marked as favorite. :(

**Comment by slater0013** [comment]
> > Hello, Can confirm the bug on 21.0.7
> > Happens only if you mark a folder as favorites, or if you share it. Then you need to browse via the left menu "Favorites" or "Shared with..." and try to create a file inside it.
> > Should have been fixed with #26672 (backported in 21.0.5) but It's not.
> > GS
> 
> I have tested this and it happens also on folders which are not marked as favorite. :(

Does it work in your home dir ?

GS

**Comment by TheZackCodec** [comment]
This issue is occurring for me in 21.0.3, 21.0.7, and 22.2.3. 
I think I have further narrowed down how to reproduce this issue 
Steps To Reproduce.
1. Have a user navigate to a folder using favorites tab.
- For the rest of the session, regardless of where the user goes or how they navigate to a folder, only office documents and text documents will report "Unable To Create File From Template" and 

Work around
+ Tell users to not use Favorites to navigate to anything and creation of new documents SHOULD work.
NOTE:  If user already has the "Unable To Create File From Template" have the user logout and log back in. This will fix the problem as long as they don't use the favorites tab to navigate to a folder again anytime in the session. 

@szaimen I will try this fix and report back

**Comment by zachrybaker** [comment]
This is a pretty important issue for those running this app in Docker where they use SMB for most/all folders.

**Comment by slater0013** [comment]
resolved before 24.0.9 !

**Comment by biva** [comment]
Hello @szaimen, thanks, this is solved for me on 25 as well :) Nevertheless, I have a lot of "old" templates, and I don't know how to clean them. Could you please share the path where they are stored? I didn't find the information in the documentation.

**Comment by szaimen** [comment]
> Nevertheless, I have a lot of "old" templates, and I don't know how to clean them. Could you please share the path where they are stored? I didn't find the information in the documentation.

Sorry, no idea.

**Comment by biva** [comment]
Should I create a new issue?

**Comment by szaimen** [comment]
Maybe here https://github.com/nextcloud/documentation, yes
