### ISSUE TITLE
different default values are used for parameter 'asset-pipeline.enabled`

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#3108]
refers to https://github.com/nextcloud/server/issues/3069

## Expected behavior
For all parameters default values should be set and the same default value should be used for all appearances in the source code.

## Current behavior
Not all of the parameters are set to a fixed default value, nor have they the same default value assigned in the source code.

As far as I understood the default value of the parameter `asset-pipeline.enabled` should be **false** but other values have been assigned in the source code:

```
getSystemValue('asset-pipeline.enabled', false)     # ok, default value
- /var/www/htdocs/nextcloud/apps2/calendar/controller/viewcontroller.php:108
- /var/www/htdocs/nextcloud/apps2/calendar/controller/viewcontroller.php:169

+ getSystemValue('asset-pipeline.enabled')          # <<< missing value, should be 'false'
  - /var/www/htdocs/nextcloud/apps/survey_client/lib/Categories/Server.php:74
```

### Steps to reproduce
1. search and compare the assigned values in the getSystemValue() call.

#### Server Configuration
OS: Linux 3.2.82
Web server: Apache2 2.4.25
Database: MariaDB 5.5.53
PHP version: 5.6.29
Nextcloud version: 11.0.0

#### Client Configuration
Browser: Mozilla Firefox 50.1.0
Operating system: Windows 7

**Comment by nickvergessen** [comment]
Value does not exist anymore, but yes default value was false.
Can you reopen in the survey_client repo?
