### ISSUE TITLE
[Bug]: Collective App: File links not working

### ISSUE THREAD

**Issue by osm-frasch** [nextcloud/server#31089]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.==> Sorry, I have already posted this in nextcloud-collectives. But nothing happened
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I have just updated to version 0.19.22. When I select text and then link a file. In this case a -.jpg screenshot, nothing happens.
The file is not opened. The -jpgs are in the same collective folder.

I have the NC version 22.2.2, PhP: 7.3.16, mysql 10.4.12

Ubuntu 18.04.4 LTS x86_64 
Host: KVM RHEL 7.6.0 PC (i440FX + PIIX, 1996) 

![Kollektive-Nextcloud](https://user-images.githubusercontent.com/63851138/153219979-95eb87c3-09d7-4d94-ac63-ca55bb36b230.png)

### Steps to reproduce

1. open collectives app
2. add a page
3. Paste text into the page and select, for example, a word. Mark & link the text to a file.
4. Nothing happens when I click on this text. Link is not active!!

### Expected behavior

Linked files should working

### Database engine version

MySQL

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - announcementcenter: 6.1.1
  - appointments: 1.11.12
  - approval: 1.0.9
  - bookmarks: 10.0.3
  - calendar: 3.0.5
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - collectives: 0.19.22
  - comments: 1.12.0
  - contacts: 4.0.7
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - deck: 1.5.5
  - documentserver_community: 0.1.11
  - event_update_notification: 1.4.0
  - external: 3.9.0
  - extract: 1.3.3
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_accesscontrol: 1.12.1
  - files_antivirus: 3.2.2
  - files_automatedtagging: 1.12.0
  - files_downloadactivity: 1.12.0
  - files_markdown: 2.3.5
  - files_mindmap: 0.0.26
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - forms: 2.4.0
  - groupfolders: 10.0.2
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - mail: 1.11.6
  - news: 17.0.1
  - nextcloud_announcements: 1.11.0
  - notes: 4.3.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - onlyoffice: 7.3.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - polls: 3.4.2
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - quota_warning: 1.13.0
  - ransomware_protection: 1.12.0
  - recommendations: 1.1.0
  - registration: 1.4.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - spreed: 12.2.3
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_admin: 3.2.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_totp: 6.2.0
  - twofactor_u2f: 6.3.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - user_usage_report: 1.6.0
  - video_converter: 1.0.4
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflow_script: 1.7.0
  - workflowengine: 2.4.0
Disabled:
  - drawio
  - encryption
  - files_external
  - files_pdfviewer
  - user_ldap
```

**Comment by szaimen** [comment]
Hello, please report this to https://gitlab.com/collectivecloud/collectives. Thanks!
