### ISSUE TITLE
[Bug]: issues with "video verification" enabled shares

### ISSUE THREAD

**Issue by StCyr** [nextcloud/server#31100]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Several issues occur after enabling "video verification" for a share:

1. It's not possible to disable "video verification" except by unsharing the file  and re-sharing it;
2. It's not possible to disable "password protect" for the share (the corresponding server request fails and the password is not reset in the db;
3. UI glitch resulting from the 2nd issue listed here above (see also "steps to reproduce" for more details

### Steps to reproduce

1. Share a file with an email recipient;
2. Check the "password protect" checkbox;
3. Check the "video verification" checkbox.

=> First issue: the "video verification" checkbox becomes disabled and it's not possible to uncheck it.

4. Uncheck the "password protect" checkbox

=> Second issue: The "update share" network request fails with

```
{
	"ocs": {
		"meta": {
			"status": "failure",
			"statuscode": 400,
			"message": "Cannot enable sending the password by Talk with an empty password"
		},
		"data": []
	}
}
```

And, the password isn't reset for the corresponding oc_share entry in the database.

5. Check the "password protect" checkbox again

=> Third issue: The UI shows the error returned by the server at step 4 ("Cannot enable sending the password by Talk with an empty password")

![image](https://user-images.githubusercontent.com/8179031/153379136-12aaa56b-1b35-4058-a507-710271825541.png)

### Expected behavior

1. User should be able to disable video verification without the need to unshare the file and re-share it;
2. User should be able to disable password protection on the share;
3. UI glitch should not occur

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud-dev.bollu.be"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.0.4",
        "overwrite.cli.url": "https:\/\/nextcloud-dev.bollu.be\/nc23",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "debug": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "loglevel": 2
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_sharing: 1.16.0
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - lookup_server_connector: 1.12.0
  - oauth2: 1.12.0
  - provisioning_api: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - spreed: 14.0.0-dev.0
  - systemtags: 1.14.0
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - testing
  - user_ldap
```

### Nextcloud Signing status

```shell
Integrity checker has been disabled. Integrity cannot be verified.
```

### Additional info

This issue has been reported from a development environment running the master branch but I've also confirmed it on my NC22 production instance.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
