### ISSUE TITLE
[Bug]: No longer synchronizing through CALDAV

### ISSUE THREAD

**Issue by Woodhousemelena** [nextcloud/server#31105]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I have not made any changes to my installation but suddenly it is impossible to synchronize calendars through caldav on either the phone or through the gnome online account function for the gnome desktop.

There are no error messages whatsoever. The calendar stays unchanged and/or empty on new client

In the web interface the calendar is usable a normal and all items are stored and updated.

### Steps to reproduce

1.Connect Gnome oneline accounts to your nextcloud or you phone through Davx5
2.Observe no updates from nextcloud i.e. empty calendar
3.No error messages. and connection is ok.

### Expected behavior

Calendars get updated , or get an error message.

### Installation method

Official SNAP package

### Operating system

Debian/Ubuntu

### PHP engine version

Other

### Web server

Other

### Database engine version

Other

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Waiting for PHP...
```

### List of activated Apps

```shell
Waiting for PHP...
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by loicfavory** [comment]
Hi, did you find a way to sync nextcloud & gnome ?
I have the same issue with no errors in logs

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
