### ISSUE TITLE
Clients: use cookies instead of auth every time

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#31118]
Hi,

currently we (at least on Android) ignore cookies.
I remember that Roeland/Morris back then said that it would be good to send/store cookies along any request so that auth/session handling on server side is less cost intensive and faster.
Currently we auth every time via user/appToken.

As Android migrates internally soon to new http client, this is something we can do meanwhile.

@PVince81 @ChristophWurst @nickvergessen @juliushaertl

**Comment by ChristophWurst** [comment]
that's already in place

**Comment by PVince81** [comment]
depending what endpoint is used for the auth, it is possible that the server will not return cookies any more (on OCS and Webdav endpoints) after https://github.com/nextcloud/server/pull/28311

**Comment by tobiasKaminsky** [comment]
Thanks for the insights and explanation 👍

> unless a client still uses the login password to authenticate.

All clients only use login password for first authentication via web login flow v1/2 and from then on only app token.

So this means, I can ignore cookies with our new http library. 👍
