### ISSUE TITLE
Login via Script

### ISSUE THREAD

**Issue by Sen5ation** [nextcloud/server#3111]
Hi,

i'm wondering if there is or should be a way to login via script? Or like an api-call?
Is there something like that? Did i miss it?
I want to do a SingleSignOn-Script for some apps including nextcloud.

Whould be great to hear some advices.

Grz.

**Comment by MorrisJobke** [comment]
Just send the username and password as HTTP basic auth headers. This is for example how the WebDAV clients work. This also works for all of our other API endpoints.
