### ISSUE TITLE
Change location of the `appdata_[instanceid]` folder

### ISSUE THREAD

**Issue by summersab** [nextcloud/server#31138]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
The `appdata_[instanceid]` folder contains cached files used to render templates and other parts of certain apps. The purpose of the `data` folder is primarily for user data storage, so storing these files in the same location doesn't necessarily make sense. Also, when using object storage, this is PAINFULLY slow since the `appdata` folder is now stored inside the object storage mount. 

**Describe the solution you'd like**
It should be possible to change the location of the `appdata` folder by setting a value in `config.php`. This would improve performance when object storage is used. It would also allow Docker users to mount user data and appdata separately as volumes.

**Describe alternatives you've considered**
N/A

**Additional context**
I have a _really_ rough working concept that simply modifies the constructor of `OC\Files\AppData\AppData`, but I'm sure there are better ways to solve the problem. I'd be happy to share my code if anyone is interested.

**Comment by solracsf** [comment]
Let's move it to https://github.com/nextcloud/server/issues/12873 (feel free to copy/paste you post there and maybe share your code snippets too.)
