### ISSUE TITLE
[Bug]: Collabora editable public share link opens with document half off screen

### ISSUE THREAD

**Issue by meichthys** [nextcloud/server#31133]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The collabora shared document opens half off the screen:
![image](https://user-images.githubusercontent.com/10717998/153605823-2ebc28a3-4460-414d-ab6b-ea15a296e751.png)

### Steps to reproduce

1. Create a new Collabora document
2. Share the document and copy the public link
3. Open the document using the public link

### Expected behavior

The document should be full screen

### Installation method

Official VM scripts

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
 - accessibility: 1.9.0
 - activity: 2.15.0
 - admin_audit: 1.13.0
 - bookmarks: 10.0.3
 - breezedark: 23.2.0
 - calendar: 3.0.5
 - circles: 23.0.1
 - cloud_federation_api: 1.6.0
 - comments: 1.13.0
 - contacts: 4.0.7
 - contactsinteraction: 1.4.0
 - dashboard: 7.3.0
 - dav: 1.21.0
 - deck: 1.6.0
 - drawio: 1.0.2
 - extract: 1.3.3
 - federatedfilesharing: 1.13.0
 - federation: 1.13.0
 - files: 1.18.0
 - files_antivirus: 3.2.2
 - files_fulltextsearch: 23.0.0
 - files_pdfviewer: 2.4.0
 - files_retention: 1.12.0
 - files_rightclick: 1.2.0
 - files_sharing: 1.15.0
 - files_trashbin: 1.13.0
 - files_versions: 1.16.0
 - files_videoplayer: 1.12.0
 - firstrunwizard: 2.12.0
 - fulltextsearch: 23.0.0
 - impersonate: 1.10.0
 - integration_github: 1.0.2
 - logreader: 2.8.0
 - lookup_server_connector: 1.11.0
 - news: 17.0.1
 - nextcloud_announcements: 1.12.0
 - notifications: 2.11.1
 - oauth2: 1.11.0
 - password_policy: 1.13.0
 - photos: 1.5.0
 - privacy: 1.7.0
 - provisioning_api: 1.13.0
 - recommendations: 1.2.0
 - richdocuments: 5.0.1
 - serverinfo: 1.13.0
 - settings: 1.5.0
 - sharebymail: 1.13.0
 - spreed: 13.0.2
 - support: 1.6.0
 - survey_client: 1.11.0
 - systemtags: 1.13.0
 - tasks: 0.14.2
 - text: 3.4.0
 - theming: 1.14.0
 - twofactor_backupcodes: 1.12.0
 - twofactor_totp: 6.2.0
 - updatenotification: 1.13.0
 - user_status: 1.3.1
 - viewer: 1.7.0
 - weather_status: 1.3.0
 - workflowengine: 2.5.0
Disabled:
 - encryption
 - files_external
 - nextbackup: 21.1.0
 - user_ldap
```

**Comment by szaimen** [comment]
should be solved with https://github.com/nextcloud/server/pull/31077

**Comment by meichthys** [comment]
Thanks, sorry i didn't see the other issues. The github issue search has been horrendous recently.
