### ISSUE TITLE
[Bug]: command-line installer fails when database host is an ipv6 address

### ISSUE THREAD

**Issue by aburch** [nextcloud/server#31142]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Using the comand-line installer fail when an IPv6 address (plus optionally a port) is passed as the argument for `--database-host`.
The following error message is shown (full error, including traceback, included below):
```
Failed to connect to the database: An exception occurred in the
 driver: SQLSTATE[HY000] [2002] Failed to parse IPv6 address "[2a01:3306"
```
Notice how most of the IPv6 address is missing: everything between the first colon up to the port is missing!

I traced this back to `lib/private/Setup/AbstractDatabase.php`:
```php
                } elseif (strpos($this->dbHost, ':')) {
                        // Host variable may carry a port or socket.
                        [$host, $portOrSocket] = explode(':', $this->dbHost, 2);
                        if (ctype_digit($portOrSocket)) {
                                $connectionParams['port'] = $portOrSocket;
                        } else {
                                $connectionParams['unix_socket'] = $portOrSocket;
                        }
                        $connectionParams['host'] = $host;
                }
```
If I change the first line to
```php
                } elseif (false && strpos($this->dbHost, ':')) {
```
the installation succeeds (but this is not a proper fix).

This might be similar to #9157, in particular [this comment](https://github.com/nextcloud/server/issues/9157#issuecomment-382374985).

The full error, including traceback:
```
Error while trying to create admin user: Failed to connect to the database: An exception occurred in the
 driver: SQLSTATE[HY000] [2002] Failed to parse IPv6 address "[2a01:3306"                               Trace: #0 /srv/nextcloud/web/nextcloud/lib/private/DB/ConnectionAdapter.php(69): OC\DB\Exceptions\DbalEx
ception::wrap()                                                                                         
#1 /srv/nextcloud/web/nextcloud/lib/private/DB/MySqlTools.php(59): OC\DB\ConnectionAdapter->executeQuery
()                                                                                                      
#2 /srv/nextcloud/web/nextcloud/lib/private/DB/MySqlTools.php(39): OC\DB\MySqlTools->isMariaDBWithLargePrefix()                                                                                                 #3 /srv/nextcloud/web/nextcloud/lib/private/Setup/MySQL.php(47): OC\DB\MySqlTools->supports4ByteCharset()                                                                                                       #4 /srv/nextcloud/web/nextcloud/lib/private/Setup.php(354): OC\Setup\MySQL->setupDatabase()             
#5 /srv/nextcloud/web/nextcloud/core/Command/Maintenance/Install.php(108): OC\Setup->install()          
#6 /srv/nextcloud/web/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Maint
enance\Install->execute()                                                                               
#7 /srv/nextcloud/web/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Consol
e\Command\Command->run()
#8 /srv/nextcloud/web/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Console
\Application->doRunCommand()
#9 /srv/nextcloud/web/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Console
\Application->doRun()
#10 /srv/nextcloud/web/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\App
lication->run()
#11 /srv/nextcloud/web/nextcloud/console.php(99): OC\Console\Application->run()
#12 /srv/nextcloud/web/nextcloud/occ(11): require_once('/srv/nextcloud/...')
#13 {main}

Previous: Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the drive
r: SQLSTATE[HY000] [2002] Failed to parse IPv6 address "[2a01:3306"
Trace: #0 /srv/nextcloud/web/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1519): OC\DB\Connection
->connect()
#1 /srv/nextcloud/web/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1041): Doctrine\DBAL\Connectio
n->getWrappedConnection()
#2 /srv/nextcloud/web/nextcloud/lib/private/DB/Connection.php(236): Doctrine\DBAL\Connection->executeQue
ry()
#3 /srv/nextcloud/web/nextcloud/lib/private/DB/ConnectionAdapter.php(66): OC\DB\Connection->executeQuery
()
#4 /srv/nextcloud/web/nextcloud/lib/private/DB/MySqlTools.php(59): OC\DB\ConnectionAdapter->executeQuery
()
#5 /srv/nextcloud/web/nextcloud/lib/private/DB/MySqlTools.php(39): OC\DB\MySqlTools->isMariaDBWithLargeP
refix()
#6 /srv/nextcloud/web/nextcloud/lib/private/Setup/MySQL.php(47): OC\DB\MySqlTools->supports4ByteCharset(
)
#7 /srv/nextcloud/web/nextcloud/lib/private/Setup.php(354): OC\Setup\MySQL->setupDatabase()
#8 /srv/nextcloud/web/nextcloud/core/Command/Maintenance/Install.php(108): OC\Setup->install()
#9 /srv/nextcloud/web/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Maint
enance\Install->execute()
#10 /srv/nextcloud/web/nextcloud/3rdparty/symfony/console/Application.php(1009): Symfony\Component\Conso
le\Command\Command->run()
#11 /srv/nextcloud/web/nextcloud/3rdparty/symfony/console/Application.php(273): Symfony\Component\Consol
e\Application->doRunCommand()
#12 /srv/nextcloud/web/nextcloud/3rdparty/symfony/console/Application.php(149): Symfony\Component\Consol
e\Application->doRun()
#13 /srv/nextcloud/web/nextcloud/lib/private/Console/Application.php(211): Symfony\Component\Console\App
lication->run()
#14 /srv/nextcloud/web/nextcloud/console.php(99): OC\Console\Application->run()
#15 /srv/nextcloud/web/nextcloud/occ(11): require_once('/srv/nextcloud/...')
#16 {main}
```

### Steps to reproduce

1. Prepare new Nextcloud install (version 23.0.0.10) using MariaDB over IPv6
2. Run `occ maintenance:install --database=mysql --database-host=[1:2:3:4::5]:3306"  "--database-port=3306"` (+ other options)

I also tried with:
- `--database-host=[1:2:3:4::5] --database-port=3306`
- `--database-host=[1:2:3:4::5]:3306` (no --database-port)
- `--database-host=[1:2:3:4::5]` (no --database-port)
without success.

I also tried adding the database host in `/etc/hosts` (using only an IPv6 address) which resulted in a different error:
```
Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known
```

### Expected behavior

The installations succeeds without error.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
N/A
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
