### ISSUE TITLE
[Bug]: user_status app issue

### ISSUE THREAD

**Issue by moatazrabeea** [nextcloud/server#31156]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

there is no set status button in web ui when upgrade from nextcloud 21 to nextcloud 23.

the error in web console is `Uncaught TypeError: q is null` in main-user-status-menu.js:46

the app user status is enabled and the update goes well

but I have this unexpected error 

also when click avatar it shows user statuses instead of set status in dropdown menu when click on it it redirects to dashboard.

### Steps to reproduce

1.trying to disable and enable user status app again doesn't fix the proplem

### Expected behavior

set status component show in the web view and in avatara dropdown menu

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.3

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Accessibility
Activity
Auditing / Logging
Calendar
Collaborative tags
Comments
Contacts
Contacts Interaction
Dashboard
Deleted files
Draw.io
Federation
File access control
File sharing
Full text search
Log Reader
Monitoring
Nextcloud announcements
Notifications
Notifications for calendar event updates
Office Online integration
Password policy
PDF viewer
Photos
Privacy
Recommendations
Share by mail
Support
Talk
Text		
Update notification		
Usage survey		
User status		
Versions		
Video player		
Weather status		
Circles
Default encryption module	
External storage support		
First run wizard		
LDAP user and group backend	
Right click	
Theming
```

**Comment by moatazrabeea** [comment]
This only happen when using custom theme but when removing custom theme it shows again I don't know why my theme doesn't contain any thing related to javascript

**Comment by moatazrabeea** [comment]
@Georg Ehrke
this error in web console`Uncaught TypeError: Cannot read properties of null (reading 'dataset')`

**Comment by rawtaz** [comment]
Can you please edit the title of this issue so it's not empty after the `[Bug]:` part? :)

**Comment by moatazrabeea** [comment]
Ok I did it, thanks.

**Comment by szaimen** [comment]
So do I understand correctly that you tried to upgrade from NC21 directly to NC23 without updating to NC22 first?

**Comment by moatazrabeea** [comment]
@szaimen  No I updated first to NC22 then to NC23 and suddenly there is error with user status as I described

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
