### ISSUE TITLE
Set user status to busy when own calendar contains busy event

### ISSUE THREAD

**Issue by alexandremottier** [nextcloud/server#31177]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

## Is your feature request related to a problem? Please describe.
Availability status seems not to be synced with Nextcloud Calendar like Microsoft Outlook with Teams.

### Describe the solution you'd like
When a "busy" event is in progress in Nextcloud Agenda, set availability status in Talk as "busy" or "to not disturb" and eventually share informations about the event in progress as status message (in option).

### Describe alternatives you've considered**
Microsoft does the same with Outlook and Teams/Skype for Business. If a calendar event is in progress with "busy" status, Teams status is "busy" or "in a meeting". If an event is "out of office", Teams status is "out of office".

Nextcloud is an open source and very powerful alternative to GAFAM, so it would be very interesting, in my opinion.

## Work packages

- [ ] Status automation
- [ ] User documentation
- [ ] Admin documentation (if any)

### Follow up
- https://github.com/nextcloud/server/issues/40760

**Comment by jancborchardt** [comment]
Some additions after talking with @miaulalala:
- If there is an event in your calendar and you are busy, the status text is set to "Busy"
- We could set the status type to "Do not disturb", but after thinking about it we don’t do it either for calls and this might make you miss messages you get while this meeting occurs. So we shouldn’t implicitly set it.
- If you happen to be in a call, where we use "In a call", this will override the calendar "Busy" state since it is more specific

**Comment by miaulalala** [comment]
@nimishavijay @jancborchardt I will use the existing "In a meeting" as a text.

But the question is which status we should use (Away isn't really correct, neither is DnD, nor is Online true either.) Can we create a new status which is "Busy" and add it to the status modal?

Would need a new icon for the status:

![image](https://github.com/nextcloud/server/assets/7427347/afd7be00-f12d-4fdc-bc3f-082b820bae98)

**Comment by ChristophWurst** [comment]
Reopening because we had to disable the feature for now via https://github.com/nextcloud/server/pull/41714.

**Comment by miaulalala** [comment]
Reimplement this with an index table that is written to onEventCreate and onEventUpdate for the calendar

**Comment by ChristophWurst** [comment]
The purpose of the index will be to have quick access to events that start in a given timeframe (e.g. next/last 5mins).

**Comment by ChristophWurst** [comment]
OTOH we already have that, kind of, with firstoccurrence and lastoccurrence in oc_calendarobjects. The only thing missing are recurring events.

So the question is: how much performance benefit do we get from another index vs just using the existing infrastructure and a range request? Do we have flame graphs of the previous meeting automation and how it slowed down the system when a call started?
