### ISSUE TITLE
[Bug]: Logfile settings not honored for audit logs, logfilemode malfunctioning

### ISSUE THREAD

**Issue by tgoeg** [nextcloud/server#31172]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I explicitly configured an audit.log logfile location:
```
'log_type' => 'file',
'log_rotate_size' => 10000000,
'loglevel' => 3,
'logfile' => '/home/nextcloud-user/nextcloud-data/nextcloud.log',
'logfilemode' => 0600,
'log.condition' => [
  'apps' => ['admin_audit'],
  ],
'log_type_audit' => 'file',
'log_rotate_size_audit' => 10000000,
'logfile_audit' => '/home/nextcloud-user/nextcloud-data/audit.log',
'logfilemode_audit' => 0600,
```

The documentation at https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html reads:
`Previously the logfile could be defined in the app config. This config is still used when the system config is not provided`
I do provide a system config for the audit log, still it does not get honored.
That is, it *does*, for `occ` commands, but not for messages generated by the web interface!
It only works for all messages if I set
`occ config:app:set --value "/home/nextcloud-user/nextcloud-data/audit.log" admin_audit logfile`

Additionally, the logfilemode option works for the audit log but not for the "normal" nextcloud.log.

audit.log gets created correctly:
```
drwxrwx--- 37 nextcloud-user     www-data    4096 Feb 14 14:42 ./
drwxr-x---  4 nextcloud-user     www-data     146 Feb 14 14:46 ../
-rw-------  1 www-data           www-data     471 Feb 14 14:39 audit.log
-rw-rw-r--  1 www-data           www-data    8026 Feb 14 14:57 nextcloud.log
```
nextcloud.log however does not.
The log says:
```
{"reqId":"Lf3rc9EYU8XsgfWca5tF","level":3,"time":"2022-02-14T14:40:44+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"chmod(): Operation not permitted at /var/www/my.nextcloud.domain/lib/private/Log/File.php#86","userAgent":"--","version":"22.2.3.0"}
```
It does not mention which file chmod() wanted to change (which would really be beneficial, these are the details that are always missing from the logs, also when files cannot be created, read, etc!) but I know it is the nextcloud.log file.
Which is strange, as can be seen from the listing above: The www-data user (Apache runs under) *does* have permission to write to files in the directory (it would not have been able to create the file, otherwise).
`sudo -u www-data chmod 0600 ~nextcloud-user/nextcloud-data/nextcloud.log`
also works as expected.

### Steps to reproduce

1. Configure as stated above
2. Perform some actions (failed logins, opening of inexistant file path, etc.) to generate log messages
3. See wrong file permissions/wrong log file locations

### Expected behavior

Documentation should be correct and/or configuration should behave as described.
'logfilemode' should be described in the docs.
Settings should be honored.
Remove redundant parallel options of configuring the audit.log location.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "config_is_read_only": "true",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "my.nextcloud.domain"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/my.nextcloud.domain",
        "dbtype": "mysql",
        "version": "22.2.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": false,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "log_type" => "file",
        "log_rotate_size" => 10000000,
        "loglevel" => 3,
        "logfile" => "/home/nextcloud-user/nextcloud-data/nextcloud.log",
        "logfilemode" => 0600,
        "log.condition" => [
          "apps" => ["admin_audit"],
          ],
        "log_type_audit" => "file",
        "log_rotate_size_audit" => 10000000,
        "logfile_audit" => "/home/nextcloud-user/nextcloud-data/audit.log",
        "logfilemode_audit" => 0600,        
        "loglevel": 3,
        "logfile": "\/home\/nextcloud_user\/nextcloud.log",
        "logfilemode": 0600,
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "maintenance": false,
        "updater.release.channel": "stable",
        "trashbin_retention_obligation": "auto, 14",
        "mail_sendmailmode": "smtp",
        "app_install_overwrite": [
            "impersonate",
            "spreed",
            "files_accesscontrol",
            "quota_warning",
            "richdocuments"
        ],
        "encryption.key_storage_migrated": false,
        "defaultapp": "files"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - bruteforcesettings: 2.2.0
  - calendar: 3.0.1
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contactsinteraction: 1.3.0
  - dav: 1.19.0
  - encryption: 2.10.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_accesscontrol: 1.11.1
  - files_downloadactivity: 1.12.0
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - groupquota: 0.1.7
  - impersonate: 1.8.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - quota_warning: 1.13.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: true
  - sharebymail: 1.12.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - text: 3.3.0
  - theming: 1.13.0
  - theming_customcss: 1.10.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_ldap: 1.12.1
  - viewer: 1.6.0
  - workflowengine: 2.4.0
Disabled:
  - dashboard
  - files_external
  - files_trackdownloads
  - spreed
  - user_status
  - weather_status
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
see above
```

**Comment by tgoeg** [comment]
Since the audit.log file has been configured, I see audit output to the console when using occ commands (again, see below).
e.g.
```
# sudo -u $ncsysuser ${ncbasedir}/occ files:scan -q -- asdf
{"reqId":"NvkIjjdJMZqxf4dAP66a","level":1,"time":"2022-02-15T09:08:33+00:00","remoteAddr":"","user":"--","app":"admin_audit","method":"","url":"--","message":"Console command executed: files:scan -q -- asdf","userAgent":"--","version":"21.0.7.0"}
```
These entries do *not* end up in the audit.log (where they should go).

This is also related to #27029 as again, -q does not silence the output.

Apart from this output problem, this ticket is generally related to https://github.com/nextcloud/server/issues/493#issuecomment-1039250277 as well in a way (that's why I wanted to have a correct audit.log in the first place).

**Comment by tgoeg** [comment]
Things checked:
* audit.log gets created
* with correct permissions
* when configured in config.php only (app config removed with `occ config:app:delete admin_audit logfile`)

* nextcloud.log gets created with correct permissions

What still does not work:
* occ errors do not get sent to audit log, though I get the above mentioned audit message stanzas on the CLI
* they can still not be silenced with `-q` (but that's a different story)

**Comment by szaimen** [comment]
Thanks for checking!

> * occ errors do not get sent to audit log, though I get the above mentioned audit message stanzas on the CLI

I think occ errors are indeed not sent to the audit log but that is a feature request.

> * they can still not be silenced with `-q` (but that's a different story)

I think there is already an open issue about this somewhere.
