### ISSUE TITLE
New inputs.scss design

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#3121]
Since the inputs.scss file is a bit messy, I was wondering if it won't be better to rewrite everything.
Here's my results so far.

__**Side-by-side comparison: [Codepen](http://codepen.io/skjnldsv/embed/QGLjMx/?height=1500&theme-id=dark&embed-version=2)**__

Do you like the change? Do you find t more readable? What are the changes you would do?

@nextcloud/designers @jancborchardt

**Comment by Espina2** [comment]
You want opinions about code or visual?

**Comment by skjnldsv** [comment]
@Espina2 visual

**Comment by MorrisJobke** [comment]
I really like it a lot 👍

**Comment by Espina2** [comment]
I think the buttons can have a bit more padding and bit bigger.

**Comment by skjnldsv** [comment]
@Espina2 What do you suggest? :)
Could be a good idea!

**Comment by MorrisJobke** [comment]
And the time input is higher than all other inputs and therefore looks out of place.

**Comment by Espina2** [comment]
All the elements are the exact same thing as in the app? So I can have a quick overview how this are going to look?

**Comment by blizzz** [comment]
I also really like it! One thing range seems kaput (on FF 50)? Nothing is visible.

**Comment by skjnldsv** [comment]
@blizzz Noticed this too. Will fix.
@Espina2 I don't understand what you mean 😆

**Comment by Espina2** [comment]
Sorry my english sometimes is bad. 

What I'm trying to ask is if are any visual changes to what we have now in nextcloud.

**Comment by skjnldsv** [comment]
Yes, the codepen have two rows: the left one is the current nextcloud design, the right is my submission :)

**Comment by skjnldsv** [comment]
@Espina2 @MorrisJobke @blizzz I updated the codepen. New feedback? 😄

**Comment by MorrisJobke** [comment]
> @Espina2 @MorrisJobke @blizzz I updated the codepen. New feedback? 😄

Awesome 🚀 🎉

**Comment by jancborchardt** [comment]
@skjnldsv great stuff! Some points:

- the hover and focus states shouldn’t modify the background. It’s especially confusing that it’s »greyed out« when you are in the field. Just leaving it white always (except when disabled) should be fine.
- the active state with the blue border is also a bit strange since it only appears on mousedown for a splitsecond. Better: for hover, focus and active give the field that blue border, but leave the background white.
- the button looks too much like an input field now, with the border. The current style with flat grey and border on hover has more affordance.
- good on changing the select to be more styled like an input field than a button :)

**Comment by skjnldsv** [comment]
@jancborchardt Updated! :)
What do you think now? I tried something new to completely differentiate buttons/select from other inputs.

cc @MorrisJobke @Espina2 @ChristophWurst @Henni @blizzz

**Comment by eppfel** [comment]
If we are on it, can we add :focus states for checkboxes and radio buttons?

**Comment by skjnldsv** [comment]
@eppfel We can. I tried adding it to the codepen, but it's a pain adding svg to codepen as base64 ^^
Is there a possibility we could get rid of the svg and only use the checkmark?

Like we could set the border and stuff with css, would be easier to theme !

**Comment by skjnldsv** [comment]
Okay, i figured it's pretty easy to do for the radio without svg at all. And for the checkbox, it won't be that hard. I will update the codependent (which the radio part is already updated) this afternoon.

It will be much more easier to theme and apply custom design with the incoming variables! :tada:

**Comment by blizzz** [comment]
> @Espina2 @MorrisJobke @blizzz I updated the codepen. New feedback? 😄

@skjnldsv same codepen link? Still have no range elements with FF 50 😿

**Comment by skjnldsv** [comment]
@blizzz The range element seemed broken. Not coming from me: http://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_range

Broken here too for me (ff 50.1.0). Seemed to be related to GTK+

**Comment by blizzz** [comment]
Aw rly? On mobile currently and codepen works here with FF 50.1.0 mobile. Clearly, the Qt port should be revived ;)

**Comment by juliushaertl** [comment]
@skjnldsv Great! Especially the buttons are a big improvement. :tada:

**Comment by eppfel** [comment]
For a future PR of this, consider changes made in #2098

**Comment by skjnldsv** [comment]
@eppfel, well the border on focus fit this purpose didn't it?

**Comment by skjnldsv** [comment]
Aaaaaaaand! Here we go!
Absolutely NO IMAGES used on the new inputs. Including the radio and checkboxes.

**Comment by skjnldsv** [comment]
Added white checkbox and radio! 🚀 
![capture d ecran_2017-01-20_18-50-10](https://cloud.githubusercontent.com/assets/14975046/22159468/529dfd0e-df41-11e6-9ea6-8c8e75e628db.png) ![capture d ecran_2017-01-20_18-50-24](https://cloud.githubusercontent.com/assets/14975046/22159467/529e027c-df41-11e6-8475-d0fae5b694e3.png)

**Comment by skjnldsv** [comment]
Okay, this is starting to be a monologue, but I'm not gonna lie, I like it a lot! :D 


![capture d ecran_2017-01-20_19-05-54](https://cloud.githubusercontent.com/assets/14975046/22159971/ae63ffc4-df43-11e6-82e1-d6cbcd0fff39.png)


Please more feedback!

**Comment by eppfel** [comment]
> @eppfel I added the border to the focus state. But I don't think @jancborchardt will like it. :)

We need focus highlighting and that's what he proposed earlier.

> Better: for hover, focus and active give the field that blue border

I think for the checkboxes and radios this is still missing.

Overall I like it a lot, too 😍 

But from the screenshot it still looks a bit odd. Maybe just because it is unfamiliar. I guess we need a PR to see it more in context.

**Comment by skjnldsv** [comment]
Pr will follow tomorrow ;)
