### ISSUE TITLE
Unable to display video thumbnail

### ISSUE THREAD

**Issue by lanzaiergesi** [nextcloud/server#31222]
Synced videos cannot display video thumbnails, which is very uncomfortable

**Comment by lanzaiergesi** [comment]
Videos in MP4 and MOV format do not show video thumbnails on nextcloud

**Comment by szaimen** [comment]
in the webinterface?

**Comment by lanzaiergesi** [comment]
yes

**Comment by szaimen** [comment]
Thanks! As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
