### ISSUE TITLE
Use new button component

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#31237]
- use new button component from nextcoud-vue 5.0.0: https://github.com/nextcloud/nextcloud-vue/pull/1808
- locations:
    - [x] Availability.vue: 3 buttons
    - [x] TransferOwnershipDialog

- in apps/settings:    
    - [x] AdminTwoFactor https://github.com/nextcloud/server/pull/31336
    - [x] AppList
    - [x] AuthTokenSetupDialogue: 2 buttons
    - [x] UserList https://github.com/nextcloud/server/pull/31378
    - [x] AddButton/HeaderBar https://github.com/nextcloud/server/pull/31409

- in apps/user_status
    - [x] SetStatusModal: 3 buttons https://github.com/nextcloud/server/pull/31397 

- in core
    - installButton (is a custom button on auto focus with white border.  Leave it for now)

- apps/dashboard & apps/user_status https://github.com/nextcloud/server/pull/31520
     - [x] App change focus on ActionButtons (included from apps/weather_status/src/App.vue)
     - [x] UserStatus  change focus on button (opening Status modal)
 
TODO: 

 - in apps/twofactor_backupcodes:
    - PersonalSettings: 3 buttons  ( Difficulties with testing. The library gmp is not available. Leave it for now)

- in apps/WebAuthn:
    - [x] AddDevice and Challenge: 4 buttons https://github.com/nextcloud/twofactor_webauthn/pull/209

- in apps/workflowengine
    - [x] Operation
    - [x] Rule: 3 buttons
    - [x] workflow https://github.com/nextcloud/server/pull/33056

- find other locations from release tarball: [nextcloud-23.0.4.tar.bz2](https://download.nextcloud.com/server/releases/nextcloud-23.0.4.tar.bz2) (Leave for now)
   - [x] privacy app
   - [x] survey_client app
   - [x] support app (existing non-Vue buttons are already compliant)

   - [x] updater: buttons: https://github.com/nextcloud/updater/blob/master/index.php

**Comment by szaimen** [comment]
I did a fast github search and found this:
https://github.com/nextcloud/server/search?l=Vue&q=button&type=

**Comment by PVince81** [comment]
yeah, I think grepping for "<button" will make it easier to convert the results into a checkbox list :smile:

**Comment by vanpertsch** [comment]
Changing the button in AppList has this result.

**Before**
<img width="631" alt="Screenshot 2022-02-22 at 17 34 38" src="https://user-images.githubusercontent.com/38529028/155298491-521041b9-afb7-4fa0-840b-67bbe76e8aba.png">

**After**
<img width="596" alt="Screenshot 2022-02-22 at 17 33 58" src="https://user-images.githubusercontent.com/38529028/155298461-7178f716-651d-40f0-8605-9de0f619cd32.png">

**Comment by PVince81** [comment]
@vanpertsch you'll likely need to tinker with the CSS around the button to fix alignment

**Comment by vanpertsch** [comment]
@PVince81 ok. I can do that :).  There are still a few css things coming that need to be adjusted. The new button is a bit bigger than the old one. So the height of the container needs to be increased. And then the margin-top of the following element needs to be adjusted. 

I can do that, but I don't want to mess around with the css too much.

**With the new button:**
![Screenshot 2022-02-23 at 11 58 33](https://user-images.githubusercontent.com/38529028/155306559-9a4db999-f93c-4f68-bb47-adcbd4784934.png)

**possible adjustment**
![Screenshot 2022-02-23 at 11 57 55](https://user-images.githubusercontent.com/38529028/155306568-4040720e-1fe7-4c5a-911b-6b7c5eacc366.png)

**Comment by szaimen** [comment]
> **possible adjustment**
> ![Screenshot 2022-02-23 at 11 57 55](https://user-images.githubusercontent.com/38529028/155306568-4040720e-1fe7-4c5a-911b-6b7c5eacc366.png)

I like this 👍
How does it look when the button is not shown? (when all apps are up-to-date)

**Comment by vanpertsch** [comment]
@szaimen it could look like this, if the increased height of the container would stay in both options the same.

![Screenshot 2022-02-23 at 14 05 52](https://user-images.githubusercontent.com/38529028/155327353-be99bf0d-e84a-48ce-9b01-5586b4537fc1.png)

to have two different container heights -depending on the showing of the button- i guess, we could have two different counter classes. https://github.com/nextcloud/server/blob/bf4acd54526d0b07ec7c305ef68d2fec4323b0b1/apps/settings/css/settings.scss#L1036

**Comment by szaimen** [comment]
> @szaimen it could look like this, if the increased height of the container would stay in both options the same.
> 
> ![Screenshot 2022-02-23 at 14 05 52](https://user-images.githubusercontent.com/38529028/155327353-be99bf0d-e84a-48ce-9b01-5586b4537fc1.png)
> 
> to have two different container heights -depending on the showing of the button- i guess, we could have two different counter classes.
> 
> https://github.com/nextcloud/server/blob/bf4acd54526d0b07ec7c305ef68d2fec4323b0b1/apps/settings/css/settings.scss#L1036

looks fine by me. cc @GretaD on this.

**Comment by vanpertsch** [comment]
@PVince81, @skjnldsv i am not sure how to tackle the buttons in the last three parts:  apps/workflowengine, apps/WebAuthn, apps/twofactor_backupcodes.

if they are to be adjusted quickly, i would need some help.

**Comment by PVince81** [comment]
> @PVince81 The buttons from privacy app, survey client app, and support app can not be replaced with the button component. Should we take them off the list again?

in that case just make sure that they have focus border and can be reached with the keyboard, I think that's the minimum needed for a11y

**Comment by Pytal** [comment]
All button additions excluding the leave for now ones are either merged or open for review

Only the find other locations from the 23.0.4 release tarball task is remaining which is not high priority @PVince81?

**Comment by PVince81** [comment]
let's finish https://github.com/nextcloud/twofactor_webauthn/pull/209 and then move on
