### ISSUE TITLE
SessionInternal::clear() erroneously calls start_session() when session is still open

### ISSUE THREAD

**Issue by rotdrop** [nextcloud/server#31248]
`SessionInternal::clear()` does strange things:

https://github.com/nextcloud/server/blob/f5d1365bbd32fdcf2084eb2ad727a574529898d0/lib/private/Session/Internal.php#L103-L108

```
Error: session_start(): Ignoring session_start() because a session is already active at /var/www/localhost/htdocs/nextcloud-git/lib/private/Session/Internal.php#208 
```

1. session_unset() -- ok, destroys all values
2. regenerateId() -- ok, generate a new session id
3. start_session() -- oops. But the session is still open.

So either the start_session is  superfluous and can be omitted -- at least in current versions of php -- or there is missing something like a `session_destroy()` (but then regenerate_id() could be omitted?) or a `session_write_close()` which would write the (now empty) session file to disk.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
