### ISSUE TITLE
[Bug]: Disappearing message when creating the user account

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#31260]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When creating the user account from the administration panel, the displayed message disappears by itself. Unable to read the error message.
An example message is shown below:

![obraz](https://user-images.githubusercontent.com/47037905/154698800-3a7ffe33-3adf-49c0-a16f-b208088d4421.png)

### Steps to reproduce

1. Select "Users" from the menu.
2. Select "New user".
3. Enter, for example, a username that already exists in Nextcloud.
4. Enter the rest of the data.
5. Select the "Add a new user" button.

### Expected behavior

Displaying an error message. Close the message with an "X".

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
-
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
