### ISSUE TITLE
Hi, new on Github and on Nextcloud.

### ISSUE THREAD

**Issue by gessel** [nextcloud/server#31268]
Hi, new on Github and on Nextcloud.
Indeed, I installed NC on my web hosting service because of it advertising E2EE...  :-D

I am unable to find a (F)OSS and privacy respecting solution that allows me to E2E encrypt and sync files, contacts and calendars. If NextCloud would manage this, I would gladly abandon the default contacts and calendar apps on my devices. Unluckily there are no calendar/contacts apps for iOS, and the web interface is too inconvenient for this...
Anyway thank you to all the developers for the effort.

_Originally posted by @ItsMeOnceMore in https://github.com/nextcloud/end_to_end_encryption/issues/271#issuecomment-1042872424_

**Comment by gessel** [comment]
@andyxheli - I understand, trying to help @ItsMeOnceMore who posted in a different thread. Feel free to close/remove this, it is not a bug.

@ItsMeOnceMore hopefully this is an appropriate place to add a little more color:

Nextcloud is fully FOSS, you can self host on your own hardware on your own LAN on your own premises.  This provides the highest level of legal protection for your data.  Hosting your data on anyone else's physical hardware is "abandoning" it.

Nextcloud does support E2E and server-side encryption.  The two are a little different and there are well-written descriptions of how they each work in the documentation.  The net result is similar. The thread you originally posted to regarding the E2E plugin is about the latest version in the plugin "store"  (1.8.1) not supporting the latest version of NC (23.x) - there's a newer version on github that does the trick, but the store (and FreeBSD port) will, I  hope, be updated soon.

Files are synced on a folder basis rather than a remote drive model.  There's a lot of discussion about enabling or even adopting a remote drive model.  Some of us sincerely hope this won't disable folder-based synchronization since that's why we chose NC in the first place and there are plenty of other solutions for remote drive.  So far, so good. 

Contacts and calendars sync very well.  I use the plugins that enable these CalDav/WebDav features and sync contacts and calendar to Thunderbird on multiple platforms and to various Android devices.  It has been a very solid and reliable solution.  The data is not encrypted at rest on the server, though it is in transit (via SSL).  Encrypting DAV data E2E isn't supported by the clients I use and doesn't seem to be on any roadmaps I'm aware of.  I believe enabling server-side encryption will do so, but review the details of server-side encryption to be sure.  I don't use this feature, but I believe the server adds an encrypt/decrypt layer which prevents OS level access to the data at rest.

**Comment by ItsMeOnceMore** [comment]
Wow, not even the time to thank and it is already closed!  :-D

**Comment by acsfer** [comment]
These things are better discussed at https://help.nextcloud.com 👍
