### ISSUE TITLE
[Bug]: Jcrop plugin not displaying correctly

### ISSUE THREAD

**Issue by arielnmz** [nextcloud/server#31279]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The problem is that the version used by the Nextcloud server (Jcrop 0.9.12) cannot correctly determine the image's width and height, causing the Jcrop widget to be initialized incorrectly:

![image](https://user-images.githubusercontent.com/24735547/154823603-47c3fb40-8dbc-49d7-93a9-9ae38813c6b3.png)

This makes the client side submit an incorrect geometry when setting the profile picture (0,0,0,0) making the server fail to save the image.

### Steps to reproduce

1. Go to user settings
2. Open the avatar upload dialog

### Expected behavior

Jcrop widget to be shown correctly

### Installation method

Official Docker image

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - bruteforcesettings: 2.3.0
  - circles: 23.0.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```

### Additional info

I upgraded from a v21 fresh install to v22 and now v23. Still experiencing this issue

**Comment by arielnmz** [comment]
Related posts:

https://github.com/nextcloud/server/issues/14455

https://github.com/nextcloud/server/issues/28556#issuecomment-1046121987

https://github.com/nextcloud/server/issues/8984#issuecomment-1046123845

**Comment by arielnmz** [comment]
For some reason this part is not passing the right width and height:

https://github.com/tapmodo/Jcrop/blob/v0.9.12/js/jquery.Jcrop.js#L316

**Comment by wokawoka** [comment]
I'm experiencing [the same issue as OP ](https://github.com/nextcloud/server/issues/31279#issue-1144881743).
The avatar upload doesn´t work using a chrome based browser but it works with firefox.

**Comment by Joriempie** [comment]
> I'm experiencing [the same issue as OP ](https://github.com/nextcloud/server/issues/31279#issue-1144881743). The avatar upload doesn´t work using a chrome based browser but it works with firefox.

I used Chrome which won't let me upload my profile picture. I changed my browser to Firefox and it worked! #:+1: 

Under "Settings > Logging" I also got a Error warning: Exception: imagecreatetruecolor(): Argument #1 ($width) must be greater than 0 in file '/var/www/nextcloud/lib/private/legacy/OC_Image.php' line 1175

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
