### ISSUE TITLE
[Bug]: Only installed apps shows in the App menu

### ISSUE THREAD

**Issue by githule** [nextcloud/server#31282]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello,

Like other people before I currently have issues to upgrade apps.

=> App menu shows, but only installed apps can be enabled/disabled
=> App new versions are not showed
=> Unlike other people, with similar issues, I can curl https://apps.nextcloud.com.
So, It does not seems to be linked to a DNS issue. 

Apps version are some months late so I worry about security issues.
No logs related to updater however debug mode is activated and log level down to 0

I cant say if this bug is related to an upgrade of the NC server.
Must be related to Nextcloud 22 code, dont think its older.

To avoid any doubt I disabled any caching option (Redis, OpCache...)

### Steps to reproduce

1. Go to App menu
2. Try to install a new app or see update for an installed app
3. Only installed apps shows, no update possible

### Expected behavior

Old App version should be upgradable

### Installation method

Official Docker image

### Operating system

Other

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
php occ config:list system
{
    "system": {
        "debug": true,
        "htaccess.RewriteBase": "\/",
        "filelocking.enabled": "true",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "***REMOVED SENSITIVE VALUE***",
            "1": "***REMOVED SENSITIVE VALUE***",
            "3": "***REMOVED SENSITIVE VALUE***"
        },
        "enabledPreviewProviders": [
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "versions_retention_obligation": "auto",
        "check_data_directory_permissions": true,
        "check_for_working_htaccess": true,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "logtimezone": "Europe\/Berlin",
        "log_type": "file",
        "logfile": "\/var\/lib\/nextcloud\/data\/nextcloud.log",
        "loglevel": 0,
        "has_internet_connection": true,
        "has_rebuilt_cache": true,
        "default_phone_region": "FR",
        "maintenance": false,
        "data-fingerprint": "1d0665a6dd942750228fe3f0fb437bfc",
        "log_rotate_size": 1048576,
        "mysql.utf8mb4": true,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "2FA",
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - bookmarks: 4.4.1
  - bruteforcesettings: 2.2.0
  - calendar: 2.3.2
  - carnet: 0.24.2
  - cloud_federation_api: 1.5.0
  - contacts: 4.0.2
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.20.0
  - federatedfilesharing: 1.12.0
  - files: 1.17.0
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - metadata: 0.14.0
  - music: 1.2.1
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - previewgenerator: 3.1.1
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - suspicious_login: 4.0.0
  - tasks: 0.14.1
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_nextcloud_notification: 3.2.1
  - twofactor_totp: 6.1.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - workflowengine: 2.4.0
Disabled:
  - accessibility: 1.4.0
  - checksum: 1.1.2
  - circles: 22.2.0
  - comments: 1.12.0
  - encryption
  - federation: 1.6.0
  - files_external
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.10.0
  - systemtags: 1.6.0
  - user_ldap
  - weather_status: 1.1.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Lots of debug element. Did some grep nothing apparently related to appstore, curl, certificates. Mostly warning about deprecated functions.
```

### Additional info

OS is raspbian buster on armv7 Armada 388 SOC (migrated today to x86 docker on Ubuntu Server)

### EDITs:
- After migrated to ubuntu server => issue still present
- Seems tied to my datas or how my datas are interpreted by the code.
 - Indeed, before migrating, I tried to put my database on a fresh install in a dev env (no data) => Apps were Ok and I could upgrade.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
