### ISSUE TITLE
disable the use of apps

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/server#31289]
Add the function to disable the use of apps.  That some apps can be allowed by the administrator and some apps are forbidden.

**Comment by szaimen** [comment]
See https://github.com/nextcloud/server/blob/2996f71d201ac0aaf4b087406edd01a1f22f2985/config/config.sample.php#L1007-L1011 for whitelisting. Blacklist was decided to not get implemented.

**Comment by R7JANV1** [comment]
I mean apps that can be installed on devices which means that the administrator can disable or enable in the admin menu to which extension (Nextcloud app), apps (on the devices) can be used.
