### ISSUE TITLE
Upgrade NC from 9.55 to NC 10 ->Error: Please use the command line updater because you have a big instance

### ISSUE THREAD

**Issue by nextdini** [nextcloud/server#3128]
Hi

I have a running  NC 9.55 on all-inkl.com.

1.I delete all the files except DATA and CONFIG
2. Then uploaded the NC 10 files.
After i go back to the browser and point on the link of the NC Path
I cannot upgrade 
This shows me
`

    Update needed

    Please use the command line updater because you have a big instance
`
I have no SSH just FTP.

Thx

**Comment by nextdini** [comment]
Just for info there are just 1 user.

**Comment by MorrisJobke** [comment]
The web updater is disabled if either the config flag is set (`upgrade.disable-web` https://github.com/nextcloud/server/blob/master/config/config.sample.php#L1296) or user_ldap is enabled or user_shibboleth is enabled (https://github.com/nextcloud/server/blob/30689f338faf5327e13b65d3b4a2d85f9e79064d/lib/base.php#L340-L351).

If you have one of those apps enabled but don't need them: disable them and the web updater should work.
