### ISSUE TITLE
[Bug]: User <...> still has unscanned files after running background scan

### ISSUE THREAD

**Issue by simonspa** [nextcloud/server#31283]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After updating to NC 22.2.5, for one out of two dozen users, the following message keeps reappearing in the NC server logs:

```
[files] Warning: User <USERNAME> still has unscanned files after running background scan, background scan might be stopped prematurely
```

Background jobs are run using `cron` and have been working perfectly for about nine years ;)

I was trying to perform a re-scan from command line, but to no avail:

```
$ sudo -u www-data php occ files:scan <USERNAME> --unscanned
Starting scan for user 1 out of 1 (<USERNAME>)
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 0       | 0     | 00:00:01     |
+---------+-------+--------------+
$ sudo -u www-data php occ files:scan <USERNAME>
Starting scan for user 1 out of 1 (<USERNAME>)
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 7838    | 40193 | 00:00:45     |
+---------+-------+--------------+
```

This Nextcloud instance does not use any external storage (also no local external), since I have found an old issue linking this problem with external storage.

### Steps to reproduce

I don't know how to reproduce on a bare system. For me:

1. Update to NC 22.2.5 from 22.2.3
2. Wait a few minutes
3. Check the logs

### Expected behavior

Logs empty :)

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
# sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "data-fingerprint": "58897020af7835d5d5eebe9f70033c28",
        "dbtype": "mysql",
        "version": "22.2.5.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "mail_smtpsecure": "ssl",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": "104857600",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 0
        },
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "preview_max_y": 2048,
        "preview_max_x": 2048,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mail_smtpauth": 1,
        "simpleSignUpLink.shown": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "knowledgebaseenabled": false,
        "loglevel": 2,
        "filelocking.enabled": "true",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "activity_expire_days": 90,
        "mail_smtpmode": "smtp",
        "theme": "",
        "default_phone_region": "DE",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    }
}
```

### List of activated Apps

```shell
# sudo -u www-data php occ app:list
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - apporder: 0.14.0
  - bookmarks: 10.0.3
  - bruteforcesettings: 2.3.0
  - calendar: 3.0.6
  - circles: 22.2.0
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.8
  - contactsinteraction: 1.3.0
  - cospend: 1.4.3
  - dashboard: 7.2.0
  - dav: 1.20.0
  - deck: 1.5.5
  - event_update_notification: 1.4.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_downloadactivity: 1.12.0
  - files_markdown: 2.3.5
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - impersonate: 1.9.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - metadata: 0.15.0
  - music: 1.5.1
  - news: 17.0.1
  - notes: 4.3.0
  - notifications: 2.10.1
  - notify_push: 0.3.0
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - passwords: 2021.12.20
  - photos: 1.4.0
  - previewgenerator: 4.0.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - quota_warning: 1.13.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - spreed: 12.2.3
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.13.0
  - theming_customcss: 1.10.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_totp: 6.2.0
  - twofactor_u2f: 6.3.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"0XoqKZQZdMGRdezaQ0sa","level":2,"time":"2022-02-20T12:50:04+01:00","remoteAddr":"","user":"--","app":"files","method":"","url":"--","message":"User <USERNAME> still has unscanned files after running background scan, background scan might be stopped prematurely","userAgent":"--","version":"22.2.5.1","id":"62122d171ab60"}
```

**Comment by thomasmerz** [comment]
I have the same problem here with Nextcloud Hub II 23.0.2 😞

**Comment by tboerner** [comment]
Same here on v.22.2.5; 
There was an orphaned entry in oc_mounts. 
in the Nextcloud database I executed 
SELECT * FROM oc_mounts WHERE user_id ='<USER>' AND mount_id IS NOT NULL;
and found an old entry not belonging to any existing mount. 
Removing this entry fixed the issue.

**Comment by simonspa** [comment]
Good catch, I indeed found one row with `mound_id IS NOT NULL`, likely from an onld installation of the `files_external` app and a trial mount point. However, after removing the line in question, and even after a rescan of the user files, for me the problem persists.

**Comment by tboerner** [comment]
The warning is generated in /var/www/owncloud/apps/files/lib/BackgroundJob/ScanFiles.php, depending on the result of
<code>
        private function getUserToScan() {<p>
               <tab> $query = $this->connection->getQueryBuilder();<p>
                $query->select('user_id')<p>
                        ->from('filecache', 'f')<p>
                        ->innerJoin('f', 'mounts', 'm', $query->expr()->eq('storage_id', 'storage'))<p>
                        ->where($query->expr()->lt('size', $query->createNamedParameter(0, IQueryBuilder::PARAM_INT)))<p>
                        ->andWhere($query->expr()->gt('parent', $query->createNamedParameter(-1, IQueryBuilder::PARAM_INT)))<p>
                        ->setMaxResults(1);<p>
                return $query->execute()->fetchOne();<p>
        }
</code>

(Sorry the indents are broken here)
Perhaps you can enlighten the situation by executing the query manually, such as 
<code>
SELECT DISTINCT *  FROM oc_filecache INNER JOIN oc_mounts ON storage_id = storage WHERE size < 0 AND parent > 1;
</code>

**Comment by simonspa** [comment]
This is what I get

```
SELECT DISTINCT * FROM oc_filecache AS f INNER JOIN oc_mounts AS m ON m.storage_id = f.storage WHERE size < 0 AND parent > 1;
+--------+---------+-----------------------------------------+----------------------------------+--------+----------------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+----------+-----+------------+---------+---------+----------------------+----------+
| fileid | storage | path                                    | path_hash                        | parent | name           | mimetype | mimepart | size | mtime      | storage_mtime | encrypted | unencrypted_size | etag          | permissions | checksum | id  | storage_id | root_id | user_id | mount_point          | mount_id |
+--------+---------+-----------------------------------------+----------------------------------+--------+----------------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+----------+-----+------------+---------+---------+----------------------+----------+
| 292306 |      37 | appdata_oc0e7rzi20xo/css/files_trashbin | ec452777115641b8fead58a610a36f9d | 285864 | files_trashbin |        1 |        2 |  -22 | 1558426407 |    1558426407 |         0 |                0 | 5ce3b327e2c79 |          31 |          | 231 |         37 |  297443 | USER    | /USER/files/Music/   |     NULL |
| 777374 |      37 | appdata_oc0e7rzi20xo/css/support        | cf2c7ca96e2f3f06abcb7e152b3262ae | 285864 | support        |        1 |        2 | -758 | 1555453468 |    1555453468 |         0 |                0 | 5cb6561c58380 |          31 |          | 231 |         37 |  297443 | USER    | /USER/files/Music/   |     NULL |
| 292306 |      37 | appdata_oc0e7rzi20xo/css/files_trashbin | ec452777115641b8fead58a610a36f9d | 285864 | files_trashbin |        1 |        2 |  -22 | 1558426407 |    1558426407 |         0 |                0 | 5ce3b327e2c79 |          31 |          | 600 |         37 | 1837025 | USER    | /USER/files/Testing/ |     NULL |
| 777374 |      37 | appdata_oc0e7rzi20xo/css/support        | cf2c7ca96e2f3f06abcb7e152b3262ae | 285864 | support        |        1 |        2 | -758 | 1555453468 |    1555453468 |         0 |                0 | 5cb6561c58380 |          31 |          | 600 |         37 | 1837025 | USER    | /USER/files/Testing/ |     NULL |
+--------+---------+-----------------------------------------+----------------------------------+--------+----------------+----------+----------+------+------------+---------------+-----------+------------------+---------------+-------------+----------+-----+------------+---------+---------+----------------------+----------+
4 rows in set (4.178 sec)

```

**Comment by tboerner** [comment]
Thanks for the backticks :-)

So these are the culprits. I'd verify whether these files (`files_trashbin` and `support`) are still present under the `path` on the server, and at the `mount_point` if you look at what `USER` can see. I guess they don't. In that case I'd delete these records right away.
Otherwise, I'd create a dump of the `oc_filecache` table for backup (in maintenance mode) and delete them anyway. If they were really needed, you can still recreate them with a manual scan.

I am under the impression that it's a data inconsistency that has existed since a long time but is now revealed by the latest version of Nextcloud. In my own case I am even certain.

**Comment by simonspa** [comment]
Great, thanks for digging @tboerner this solved it.

I however don't fully agree with your statement that these files are not supposed  to be accessible bu users. For example all preview files of images are stored at `appdata_*/preview` and they are of course linked to users and accessible.

That said, I would agree with your assessment that these file cache entries were probably a long-standing inconsistency that now surfaced. Dropped and done. :)

**Comment by nokoa77** [comment]
Hi, are you sure it is a good idea to close this issue ? Sorry I'm not a Github expert, but would it be better to close the issue once it is resolved by a "bug fix" in a future server release ?

**Comment by simonspa** [comment]
@nokoa77 as far as we could tell in our investigation, this is *not* a server issue but stemmed a data inconsistency in my installation. After solving this, the hint/warning in the logs does not longer appear. Hence there is nothing to "fix" on the server code and I closed the issue.

**Comment by tboerner** [comment]
**@simonspa:** Glad I could be helpful. And yes, you are right in users having access to this data. But this is not my point. They are not supposed to access them directly through a mount.

**Comment by Terrox** [comment]
I have this issue after upgrading from 22 to 23, I used to have files_external app too, not sure how to easily fix.

**Comment by Terrox** [comment]
Oh I just ran the command and it looks like this, not the path has "news" which seems really wrong.
`fileid	storage	path	path_hash	parent	name	mimetype	mimepart	size	mtime	storage_mtime	encrypted	unencrypted_size	etag	permissions	checksum	id	storage_id	root_id	user_id	mount_point	mount_id 	
108 	1 	news 	508c75c8507a2ae5223dfd2faeb98122 	1 	news 	2 	1 	-1 	1496476044 	1496476044 	0 	0 	5932698ce1bfd 	31 		6 	1 	15316 	replacedusername 	/replacedusername/files/TV/ 	NULL
108 	1 	news 	508c75c8507a2ae5223dfd2faeb98122 	1 	news 	2 	1 	-1 	1496476044 	1496476044 	0 	0 	5932698ce1bfd 	31 		7 	1 	15334 	replacedusername 	/replacedusername/files/Torrent Downloads/ 	NULL
108 	1 	news 	508c75c8507a2ae5223dfd2faeb98122 	1 	news 	2 	1 	-1 	1496476044 	1496476044 	0 	0 	5932698ce1bfd 	31 		11 	1 	19994 	replacedusername 	/replacedusername/files/Movies/ 	NULL
108 	1 	news 	508c75c8507a2ae5223dfd2faeb98122 	1 	news 	2 	1 	-1 	1496476044 	1496476044 	0 	0 	5932698ce1bfd 	31 		13 	1 	28458 	replacedusername 	/replacedusername/files/Pictures/ 	NULL `

**Comment by fenris** [comment]
anyone can help to confirm the solution for this issue is the only to remove the fileid?

SELECT DISTINCT * FROM oc_filecache AS f INNER JOIN oc_mounts AS m ON m.storage_id = f.storage WHERE size < 0 AND parent > 1;

DELETE FROM oc_filecache WHERE fileid = <your id>

**Comment by espressoelf** [comment]
Quickie if you just want to delete (backup before): `DELETE FROM oc_filecache WHERE fileid IN(SELECT DISTINCT f.fileid FROM oc_filecache AS f INNER JOIN oc_mounts AS m ON m.storage_id = f.storage WHERE size < 0 AND parent > -1);`

Helped me as I had outdated entries from external storage.

**Comment by dakontiva** [comment]
I too am getting the same warning but when I ran `SELECT DISTINCT *  FROM oc_filecache AS f INNER JOIN oc_mounts AS m ON m.storage_id = f.storage WHERE size < 0 AND parent > -1;` I got  about 24000 entries. Is it safe to delete those?

**Comment by kubrickfr** [comment]
I've deleted those cache entries and the warning "still has unscanned files after running background scan, background scan might be stopped prematurely" keeps on coming back...

**Comment by kubrickfr** [comment]
Also, files belonging to user A show up as user_id='B' in oc_filecache

**Comment by ostasevych** [comment]
I have the same issue with NC 27.1.6. Executing above mentioned select gives me 1110 rows. However the error related to only one user out of 25.
Meanwhile, I use groupfolders.

**Comment by JohanBoshoffWebAware** [comment]
Same here, only local storage used and I have the same problem from early version of Nextcloud 26.  I just upgraded to latest 27.0.7 over the weekend and the issue is still there.

Is there any fix for this?  Seems like more and more problems and I think it is because Nextcloud wants to release newer versions without fixing old bugs frustrating everyone with no fixes.

**Comment by ostasevych** [comment]
Would that be possible to investigate HOW this bug originates, and WHAT to do to overcome it and WHICH changes are to be made in the code to prevent it from appearing and dealing with it in case of appearing.
