### ISSUE TITLE
Path '' is not accessible or present !!!

### ISSUE THREAD

**Issue by allorder** [nextcloud/server#313]
I got this error at each cron job:

"app":"OC\\Files\\Cache\\Scanner","message":"!!! Path '' is not accessible or present !!!","level":0,"time":"2016-07-05T10:30:01-04:00","method":"--","url":"--","user":"--"}

But, when doing: **sudo -u www-data php -f /var/www/nextcloud/cron.php** I got no error...

Should I ignore this error or ..?

**Comment by MorrisJobke** [comment]
> Should I ignore this error or ..?

This is debug log: https://github.com/nextcloud/server/blob/master/lib/public/Util.php#L60 - you can ignore it.
