### ISSUE TITLE
After upgrade disable/enable 2fa generates a new code 

### ISSUE THREAD

**Issue by wahlis** [nextcloud/server#3130]
### Steps to reproduce
1. Upgrade to 11.0.1
2. Log in after session timout
3. 

### Expected behaviour
After entering code I should be able to login 

### Actual behaviour
TOTP (Google Authenticator) Swedish error message "Fel vid verifiering av tvåfaktorsautentisering." 
New prompt to add  Authentication code

After using a backup code I was able to login. Disabling 2fa let me login again. When I re-enable it a new key is generated. 

This behaviour was not before the upgrade. I have had some issues with OPDS not working with app passwords so I have disabled and the re-enabled 2fa several times before.

### Server configuration
**Operating system**:
Ubuntu 16.04.1 LTS 

**Web server:**
Apache 2.4.18

**Database:**
mysql-server-core-5.7.16

**PHP version:**
7.0.13

**Nextcloud version:** (see Nextcloud admin page)
11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update

**Comment by nickvergessen** [comment]
@ChristophWurst

**Comment by ChristophWurst** [comment]
@wahlis could you please open an issue at https://github.com/nextcloud/twofactor_totp/issues/new (just copy the text from above into a new issue). If you have anything related to this issue in the logs please provide your log entries too. I will have a look then. Thanks!
