### ISSUE TITLE
[Bug]: Download file > 512MB from SMB external storage not possible (NC 23.0.2)

### ISSUE THREAD

**Issue by spiezmaestro** [nextcloud/server#31308]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I try to download files larger than 512 MB from SMB/CIFS shares (attached via the "External storage support" Nextcloud), the download fails (downloading starts then stops at 512 MB and finally results in failure).

This is on a NC 23.0.2. / External Storage app version 1.15.0 (latest). When I copy the directory /var/www/html/apps/files_external/3rdparty/icewind from the backup of NC 23.0.0 than it works again.

Therefore there is an issue at least with the combination of the external storage app with the used icewind 3rdparty app.

### Steps to reproduce

1. Upgrade to NC 23.0.2 with external storage app  1.15.0 (most likely fresh install will have the same issue)
2. Try to download a file larger than 512 MB from a via SMB connected share
3.

### Expected behavior

Download without issue

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - announcementcenter: 6.1.1
  - apporder: 0.14.0
  - bookmarks: 10.0.3
  - breezedark: 23.2.0
  - bruteforcesettings: 2.3.0
  - calendar: 3.0.6
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.0.8
  - contactsinteraction: 1.4.0
  - cospend: 1.4.3
  - dav: 1.21.0
  - dicomviewer: 1.2.3
  - epubreader: 1.4.7
  - event_update_notification: 1.4.0
  - federatedfilesharing: 1.13.0
  - files: 1.18.0
  - files_downloadactivity: 1.12.0
  - files_external: 1.15.0
  - files_markdown: 2.3.5
  - files_pdfviewer: 2.4.0
  - files_readmemd: 1.2.1
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - forms: 2.4.0
  - gpoddersync: 3.2.0
  - health: 1.5.0
  - impersonate: 1.10.0
  - joplin: 0.0.25
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.6
  - maps: 0.1.10
  - metadata: 0.15.0
  - news: 17.0.1
  - nextcloud_announcements: 1.12.0
  - notes: 4.3.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - occweb: 0.0.7
  - onlyoffice: 7.3.0
  - password_policy: 1.13.0
  - phonetrack: 0.7.0
  - photos: 1.5.0
  - polls: 3.5.4
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - quota_warning: 1.13.0
  - rainloop: 7.1.3
  - ransomware_protection: 1.12.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - suspicious_login: 4.1.0
  - systemtags: 1.13.0
  - tasks: 0.14.2
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_nextcloud_notification: 3.3.1
  - twofactor_totp: 6.2.0
  - twofactor_webauthn: 0.2.15
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - welcome: 1.0.1
  - workflowengine: 2.5.0
Disabled:
  - circles: 0.20.2
  - cms_pico: 1.0.17
  - dashboard: 7.2.0
  - encryption
  - extract: 1.3.3
  - federation: 1.7.0
  - files_antivirus: 3.2.2
  - files_texteditor: 2.14.0
  - files_trackdownloads: 1.11.0
  - files_trashbin: 1.7.0
  - flowupload: 1.1.3
  - gpxedit: 0.0.14
  - gpxmotion: 0.1.0
  - gpxpod: 4.3.0
  - groupfolders: 11.1.2
  - guests: 2.1.0
  - integration_discourse: 1.0.2
  - integration_github: 1.0.2
  - integration_gitlab: 1.0.3
  - integration_twitter: 1.0.2
  - integration_whiteboard: 0.0.14
  - music: 1.5.1
  - ncdownloader: 0.7.1
  - ocsms: 2.2.0
  - previewgenerator: 4.0.0
  - quickaccesssorting: 1.1.3
  - radio: 1.0.3
  - ransomware_detection: 0.10.0
  - recommendations: 0.8.0
  - richdocuments: 5.0.2
  - richdocumentscode: 21.11.103
  - smb_test: 0.3.3
  - support: 1.3.0
  - survey_client: 1.5.0
  - terms_of_service: 1.9.2
  - twofactor_u2f: 6.3.0
  - unsplash: 1.2.4
  - user_ldap
```

**Comment by XueSheng-GIT** [comment]
I had the same issue using Ubuntu 20.04 and smbclient. After installing php-smbclient (using an additional ppa) this issue was solved.

**Comment by spiezmaestro** [comment]
Thanks, tried that and solved my issue as well.

**Comment by dd4y** [comment]
Samo issue here, max 512mb download on NC 23.0.2 with external storage app 1.15.0 on Ubuntu 20.04 . Installed PPA php-smbclient 7.4 1.0.6 from https://dannyda.com/tag/ubuntu-20-04-1-lts-php-smbclient/ 

Still not working.

**Comment by plaing1** [comment]
Same issue here, nextcloud 22.2.5, external storage app (files_external) version 1.13.1, OS Ubuntu 20.04

Works with php7.4-smbclient version 1.0.6-6+ubuntu20.04.1+deb.sury.org+10 as per instructions from https://dannyda.com/tag/ubuntu-20-04-1-lts-php-smbclient/

Restart php-fpm with systemctl restart php7.4-fpm after installing php7.4-smbclient.

**Comment by icsy7867** [comment]
Not sure if this is helpful for anyone.  I am running the latest nextcloud 23.0.3 docker container.  Ran into this as well.

I simply installed libsmbclient-dev and then ran:
```
pecl install smbclient
echo "extension=smbclient.so" >> /usr/local/etc/php/conf.d/nextcloud.ini
```

Anyone feeling lazy and running docker, I made a docker container (I only update this every few minor releases):
docker pull icsy7867/nextcloud:23

You can see the dockerfile here, pretty simple:
https://github.com/icsy7867/nextcloud/blob/master/nextcould-23/Dockerfile

**Comment by Oroo9CeL** [comment]
I can confirm this bug with version 24.0.0
Stumbled across this when I wanted to move files larger than 512 MB between external SMB drives.

**Comment by valvanet** [comment]
I'm using the docker Image, but pecl isn't working for me:

After installing libsmclient-dev and smbclient within apt I get the following error:

```
No releases available for package "pecl.php.net/smbclient"
install failed
```

Also `echo "extension=smbclient.so" >> /usr/local/etc/php/conf.d/nextcloud.ini`
causes nextcloud not to start anymore.

Any ideas what might be wrong?

**Comment by valvanet** [comment]
My Host is a RaspberryPi with Pi OS arm64 (Bullseye) with Samba 4.13.13 installed.

I am using a Portainer Stack to run the containers:

- nextcloud:latest
- postgres:14.2

My ENV file:

```
TZ=Europe/Berlin
DISABLE_IPV6=true
POSTGRES_DB=***
POSTGRES_HOST=***
POSTGRES_PASSWORD=***
POSTGRES_USER=***
NEXTCLOUD_ADMIN_PASSWORD=***
NEXTCLOUD_ADMIN_USER=***
NEXTCLOUD_DATA_DIR=/var/www/html/data
NEXTCLOUD_TRUSTED_DOMAINS=***
NEXTCLOUD_UPDATE=1
TRUSTED_PROXIES=<nginx-container>
PHP_MEMORY_LIMIT=512M
PHP_UPLOAD_LIMIT=10G 
```

I can reproduce my issue after deleting the image and running it from nextcloud:latest..

Could this be related to the RaspberryPi only?

**Comment by icsy7867** [comment]
> My Host is a RaspberryPi with Pi OS arm64 (Bullseye) with Samba 4.13.13 installed.
> 
> I am using a Portainer Stack to run the containers:
> 
> * nextcloud:latest
> * postgres:14.2
> 
> My ENV file:
> 
> ```
> TZ=Europe/Berlin
> DISABLE_IPV6=true
> POSTGRES_DB=***
> POSTGRES_HOST=***
> POSTGRES_PASSWORD=***
> POSTGRES_USER=***
> NEXTCLOUD_ADMIN_PASSWORD=***
> NEXTCLOUD_ADMIN_USER=***
> NEXTCLOUD_DATA_DIR=/var/www/html/data
> NEXTCLOUD_TRUSTED_DOMAINS=***
> NEXTCLOUD_UPDATE=1
> TRUSTED_PROXIES=<nginx-container>
> PHP_MEMORY_LIMIT=512M
> PHP_UPLOAD_LIMIT=10G 
> ```
> 
> I can reproduce my issue after deleting the image and running it from nextcloud:latest:
> 
> ```
> root@nextcloud:/var/www/html# apt-get update && apt-get install libsmbclient-dev smbclient
> 
> [...]
> The following additional packages will be installed:
>   dbus dirmngr gnupg gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client gpg-wks-server gpgconf gpgsm libapparmor1 libarchive13 libassuan0 libavahi-client3 libavahi-common-data libavahi-common3 libcap2 libcups2 libdbus-1-3 libgpgme11 libksba8
>   libldb2 liblmdb0 libmpdec3 libnpth0 libpython3-stdlib libpython3.9 libpython3.9-minimal libpython3.9-stdlib libsmbclient libtalloc2 libtdb1 libtevent0 libwbclient0 pinentry-curses python3 python3-gpg python3-ldb python3-minimal python3-samba
>   python3-talloc python3-tdb python3.9 python3.9-minimal samba-common samba-common-bin samba-dsdb-modules samba-libs
> 
> Suggested packages:
>   default-dbus-session-bus | dbus-session-bus dbus-user-session libpam-systemd pinentry-gnome3 tor parcimonie xloadimage scdaemon lrzip cups-common pinentry-doc python3-doc python3-tk python3-venv python3.9-venv python3.9-doc binfmt-support
>   heimdal-clients python3-markdown python3-dnspython cifs-utils
> 
> The following NEW packages will be installed:
>   dbus dirmngr gnupg gnupg-l10n gnupg-utils gpg gpg-agent gpg-wks-client gpg-wks-server gpgconf gpgsm libapparmor1 libarchive13 libassuan0 libavahi-client3 libavahi-common-data libavahi-common3 libcap2 libcups2 libdbus-1-3 libgpgme11 libksba8
>   libldb2 liblmdb0 libmpdec3 libnpth0 libpython3-stdlib libpython3.9 libpython3.9-minimal libpython3.9-stdlib libsmbclient libsmbclient-dev libtalloc2 libtdb1 libtevent0 libwbclient0 pinentry-curses python3 python3-gpg python3-ldb python3-minimal
>   python3-samba python3-talloc python3-tdb python3.9 python3.9-minimal samba-common samba-common-bin samba-dsdb-modules samba-libs smbclient
> 
> 0 upgraded, 51 newly installed, 0 to remove and 4 not upgraded.
> Need to get 26.6 MB of archives.
> After this operation, 101 MB of additional disk space will be used.
> Do you want to continue? [Y/n] 
> 
> [...]
> Fetched 26.6 MB in 2s (12.5 MB/s)           
> debconf: delaying package configuration, since apt-utils is not installed
> 
> [...]
> Setting up samba-common (2:4.13.13+dfsg-1~deb11u3) ...
> **debconf: unable to initialize frontend: Dialog
> debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78.)
> debconf: falling back to frontend: Readline**
> Creating config file /etc/samba/smb.conf with new version
> 
> [...]
> Setting up samba-common-bin (2:4.13.13+dfsg-1~deb11u3) ...
> Checking smb.conf with testparm
> Load smb config files from /etc/samba/smb.conf
> Loaded services file OK.
> Weak crypto is allowed
> Server role: ROLE_STANDALONE
> 
> Done
> Processing triggers for libc-bin (2.31-13+deb11u3) ...
> Processing triggers for mailcap (3.69) ...
> ```
> 
> ```
> root@nextcloud:/var/www/html# pecl install smbclient
> No releases available for package "pecl.php.net/smbclient"
> install failed
> ```
> 
> Could this be related to the RaspberryPi only?

I'm not sure.
https://hub.docker.com/_/php mentions deleting 
/etc/apt/preferences.d/no-debian-php

But just a guess.

**Comment by icsy7867** [comment]
https://github.com/nextcloud/vm/issues/1232

Someone also mentioned pihole blocking pecl

**Comment by valvanet** [comment]
Thanks a million times for pointing me that direction! It was the pihole blocking..

**Comment by eivamu** [comment]
> I had the same issue using Ubuntu 20.04 and smbclient. After installing php-smbclient (using an additional ppa) this issue was solved.

I had the same issue with NC 24.0.4, External Storage Support 1.16.1, Ubuntu 20.04.4 LTS, PHP 8.1.8.
Installing the package php-smbclient using apt immediately solved the issue.

**Comment by Decstasy** [comment]
Same Issue here...

**Comment by szaimen** [comment]
Please simply install php-smbclient then

**Comment by Decstasy** [comment]
Please alter the Documentation then https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_files/external_storage/smb.rst

**Comment by v1-valux** [comment]
Case closed.. lol

**Comment by szaimen** [comment]
I've created this issue for you to not forget it: https://github.com/nextcloud/documentation/issues/9428

**Comment by Oroo9CeL** [comment]
> Please simply install php-smbclient then

Installing php-smbclient can only be a workaround, since not all linux distribution provides a package for this. Installation via pecl or adding external repositories may affect the consistency of the installation and its maintainability. This is not acceptable in professional environments. Since smbclient is the CIFS client which is present on all linux distributions, the focus should be on finding the actual bug instead of using workarounds and closing bugreports. So please reopen the bug. Thanks!

**Comment by maxi1134** [comment]
I also have this issue!

**Comment by icsy7867** [comment]
> Unable

Is this in a docker container?  Try doing and apt-get update first.

I also used a different set of commands personally.
https://github.com/nextcloud/server/issues/31308#issuecomment-1102022732

**Comment by maxi1134** [comment]
> > Unable
> 
> Is this in a docker container? Try doing and apt-get update first.
> 
> I also used a different set of commands personally. [#31308 (comment)](https://github.com/nextcloud/server/issues/31308#issuecomment-1102022732)

That worked!

Could you share the docker file? It does not exist anymore

**Comment by Ryushin** [comment]
Today I noticed php-smclient is not working with Samba 4.17.5 from Debian.  Recompiled again as well against the new lib-smbclient:
pecl uninstall smbclient ; pecl install smbclient
Found other are having the same problem:
https://www.spinics.net/lists/centos/msg181966.html

So I've reverted to using smbclient and now have the 512MB bug again.  Really, smbclient is standard and should be the path forward.  So whatever bug is causing this really needs to be looked at.  If the ticket is not re-opened in the next couple of days, I'll open a new ticket as I don't know if the admins are notified if a comment takes place on a closed ticket.

**Comment by icsy7867** [comment]
> > > Unable
> > 
> > 
> > Is this in a docker container? Try doing and apt-get update first.
> > I also used a different set of commands personally. [#31308 (comment)](https://github.com/nextcloud/server/issues/31308#issuecomment-1102022732)
> 
> That worked!
> 
> Could you share the docker file? It does not exist anymore

https://github.com/icsy7867/nextcloud

I also finally got around the playing with gitlab.  I am automatically rebuilding these weekly with the latest major versions (24 and 25):
https://hub.docker.com/r/icsy7867/nextcloud/tags
icsy7867/nextcloud:25
icsy7867/nextcloud:24

Feel free to use them if you like.

**Comment by onethree7** [comment]
on nextcloud 27, php8+
with kernel
```
root@pop-os:/home/nextcloud# uname -a
Linux pop-os 6.2.6-76060206-generic #202303130630~1689015125~22.04~ab2190e SMP PREEMPT_DYNAMIC Mon J x86_64 x86_64 x86_64 GNU/Linux
```

one command fixed this, as stated by others before.

` apt-get install php-smbclient`

it installed

```
php-smbclient (1.0.6-6) unstable; urgency=medium

  * Fix the d/control for PHP 8.1

```

**Comment by FrancisHGR** [comment]
Had the same bug, got it solved by running the following commands within the docker container:

apt update && apt -y install libsmbclient-dev libmagickwand-dev && pecl install smbclient && echo “extension=smbclient.so” > /usr/local/etc/php/conf.d/docker-php-ext-smbclient.ini && pecl install inotify


Still, this bug should be fixed, ideally php-smbclient directly integrated in Nextcloud

**Comment by TomKuge** [comment]
I’m also running Nextcloud 31.0.9.
Spent about 4 hours troubleshooting this before finding the solution here, so thanks for the issue.
It might be helpful if the Nextcloud installation guide mentioned that the php-smbclient package needs to be installed when using SMB shares.
Cheers.

**Comment by f22raptorroland** [comment]
I had the same on the Turnkey Proxmox container. it's not running on Docker so it's a bit different
Had to install php-dev and make, also the ini file is located elsewhere.

apt update
apt install -y build-essential
apt install -y libsmbclient-dev 
apt install -y php-dev
pecl install smbclient
echo "extension=smbclient.so" > /etc/php/8.2/mods-available/smbclient.ini
phpenmod smbclient


reboot or restart apache 2 / php8.2-fpm
"php -m | grep smb" Should give you smbclient
