### ISSUE TITLE
[Bug]: tags button still shown even though tags app is disabled

### ISSUE THREAD

**Issue by JordanDIG** [nextcloud/server#31315]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When we deactivate the application "Collaborative tags" in the application manager and we go to the file manager and select a folder or a file we click on the 3 small dots to see the available actions the "Tags" option is still present although the application is deactivated.
When we click on it the menu is closed. 

### Steps to reproduce

1) Disable the Collaborative tags application
2) Go to the file manager and select an item
3) Click on the 3 little dots

### Expected behavior

That the "Tag" element is hidden when the application is disabled.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Fresh Install
```

### List of activated Apps

```shell
Fresh Install
```

### Nextcloud Signing status

```shell
Fresh Install
```

### Nextcloud Logs

```shell
No logs
```

### Additional info

This bug is present on all the instances I tested

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by JordanDIG** [comment]
> Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!
> 
> My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!
> 
> If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

The problem is still there on my side, can you test on your side?

**Comment by szaimen** [comment]
with which nc version did you test?

**Comment by JordanDIG** [comment]
> 25.0.3

25.0.4

**Comment by szaimen** [comment]
Or rather lets keep https://github.com/nextcloud/server/issues/31583

**Comment by JordanDIG** [comment]
okay
