### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Magke** [nextcloud/server#31311]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

What happens: a normal user (only group admin) deletes a user of his own group and this deleted user is completely removed from the cloud.

### Steps to reproduce

1.create two users according to the above scenario
2.add both users to multiple groups
3.make one user the group admin for a common group
4.the guppenadmin deletes the other user
5.the deleted user is completely removed from the cloud 

### Expected behavior

A normal user (only group admin) deletes a user of his own group and this user is only deleted from that group and the other groups and the account remains in existence.

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
i can't do that now, the it-crew would have to make up for it
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
