### ISSUE TITLE
User backend OC_User_IMAP already initialized

### ISSUE THREAD

**Issue by tflidd** [nextcloud/server#3132]
### Steps to reproduce
1. Use and update Nextcloud with IMAP external user backend.
2. Open News app or click on Nextcloud-logo on the top left corner
3. If I choose the files-app directly or any other app there seems to be no issue.

### Expected behaviour
Nextcloud should be used without error.

### Actual behaviour

Click on nextcloud-logo:
````
"reqId":"4NVm1YB1Z7+JYPQ7e8eb","remoteAddr":"ip","app":"core","message":"User backend OC_User_IMAP already initialized.","level":0,"time":"2017-01-17T22:06:31+00:00","method":"GET","url":"\/nextcloud\/index.php","user":"user","version":"11.0.1.2"}
````
News app (without any feeds):
```
{"reqId":"HE7cJlFy1KviaSsvuBXN","remoteAddr":"ip","app":"core","message":"User backend OC_User_IMAP already initialized.","level":0,"time":"2017-01-17T22:08:00+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/news\/%7B%7B%20::Content.getFeed(item.feedId).faviconLink%20%7D%7D","user":"user","version":"11.0.1.2"}

```
https://github.com/nextcloud/news/issues/84

It's doesn't matter if I use a local user or a IMAP user.

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache

**Database:** Maria-DB

**PHP version:** 7.0 (dot-deb packages)

**Nextcloud version:** 11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 11.0.0 (was a new NC 10 setup, not migrated from ownCloud). Manual upgrade.

**Where did you install Nextcloud from:** archive-file

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - announcementcenter: 3.0.0
  - apporder: 0.3.3
  - audioplayer: 1.4.0
  - bookmarks: 0.9.1
  - calendar: 1.5.0
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - direct_menu: 0.10.0
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_downloadactivity: 1.0.0
  - files_external: 1.1.2
  - files_markdown: 1.0.0
  - files_pdfviewer: 1.0.1
  - files_reader: 0.8.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - githubmergetracker: 0.0.15
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - news: 10.1.0
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - passman: 2.0.0-RC4
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - systemtags: 1.1.3
  - tasks: 0.9.4
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 0.5.0
  - twofactor_u2f: 0.1.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - workflowengine: 1.1.1
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocx7851qw981",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "data.aspekte.net"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/example.net\/nextcloud",
        "dbtype": "mysql",
        "version": "11.0.1.2",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "{mail.example.net:993\/imap\/ssl}"
                ]
            }
        ],
        "updater.release.channel": "stable",
        "loglevel": 0,
        "log_rotate_size": 10485760,
        "maintenance": false,
        "allow_user_to_change_display_name": true,
        "theme": ""
    }
}

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** IMAP.

### Client configuration
**Browser:** Firefox/Chromium

**Operating system:** Ubuntu 16.04

### Logs

Already provided above. Nothing in the server error logs. Browser logs only warns about some deprecated function (tipsy).

**Comment by tflidd** [comment]
On NC 11.0.2 I still have the problem with some apps:

- news-app (@BernhardPosselt)
- weather (5 log entries) @nerzhul 

other apps have no problem (Files, activity, gallery, mail, contacs, calendar, announcements, notes)

**Comment by ChristophWurst** [comment]
This is a debug log statement. Seeing this does not mean there's a problem: https://github.com/nextcloud/server/blob/e3de4edc51b5a7444f99f4b4ca5ce9f70b3b3e8c/lib/private/legacy/user.php#L148.

I'm closing this therefore.
