### ISSUE TITLE
[Bug] Admin privileges function does not apply to group members being group admins

### ISSUE THREAD

**Issue by JB1985** [nextcloud/server#31327]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If the username and group name are the same, then the admin privileges function will not work.

The user cannot see the administration section at: mycloud//index.php/settings/user

![image](https://user-images.githubusercontent.com/9932751/155283917-0af03663-f45d-4282-93e4-d46a554d7af8.png)

"1331" is available as a user and as a group. If I create a new user - with diffrent name - in the group 1331, then it works.

### Steps to reproduce

1. Create a group and user with the same name.
2. Add the group into the admin privileges
3. Login into the cloud and go to settings. You will see not the admin section.

### Expected behavior

Should actually work. :)

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - bookmarks: 10.0.3
  - calendar: 3.0.6
  - circles: 23.0.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.0.8
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - deck: 1.6.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_mindmap: 0.0.26
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - forms: 2.4.0
  - groupfolders: 11.1.2
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.6
  - nextcloud_announcements: 1.12.0
  - notes: 4.3.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - registration: 1.4.0
  - richdocuments: 5.0.2
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.3
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
```

**Comment by JB1985** [comment]
Can nobody confirm this?

**Comment by JB1985** [comment]
@nickvergessen @MichaIng

**Comment by nickvergessen** [comment]
Can you try with a non numeric user? Maybe the problem is from that.

Anyway not sure why you ping me.

**Comment by nickvergessen** [comment]
Just did a quick test, works fine here with numeric users and a clash of userid+groupid

**Comment by JB1985** [comment]
That's strange. I have the problem with all installations of version 23.0.2

**Comment by MichaIng** [comment]
Cannot replicate either:
- Fresh install of Nextcloud 23.0.2
- Created user named `1337` and group named `1337`
- Added user `1337` to group `1337`
- Gave group `1337` access to theming and group ware via admin privileges settings
- Logged in as user `1337` and verified that it sees and can change (admin) theming and group ware settings

**Comment by JB1985** [comment]
Ok, The problem is that if the user is also a group admin, then the administration does not see it.

Is it intended that only group members are allowed to use the function and if you are also a group admin, then not?

Why?

**Comment by MichaIng** [comment]
You are right, now I'm able confirm this @nickvergessen:
- Doing the [above](https://github.com/nextcloud/server/issues/31327#issuecomment-1054319667) steps it works fine, but as fast as user `1337` is made group admin for group `1337`, it cannot see or change the granted admin settings anymore.
- The user and group names do not need to be numeric, the same is true when using `test`/`test`.
- Also user and group names do not need to be the same: I can replicate using `text`/`1337`, and as fast as the user `text` is not group admin for group `1337` anymore, it can see the admin settings, making it group admin again, hides the settings.

So the issue is that group admins do not get their group's admin settings privileges 😄.

**Comment by JB1985** [comment]
Wow, why you close so fast?

Of course he's a member of the group AND member of any Group Admin.  But if a user is a group administrator, no matter what group, then it doesn't work.

Please reopen, that is a bug.

**Comment by MichaIng** [comment]
> Being a group administrator does not mean you are a member of the group.

Ehm, of course the issue is true when the group admin is a group member as well.

**Comment by nickvergessen** [comment]
I closed it because that works fine for me:

### User row
![Bildschirmfoto von 2022-03-10 16-21-13](https://user-images.githubusercontent.com/213943/157693942-8ab92305-15be-409f-a77f-99429e1508ec.png)

### Permission row
![Bildschirmfoto von 2022-03-10 16-21-16](https://user-images.githubusercontent.com/213943/157693972-ebdf99cf-167b-45a4-b04b-66bcd86c598d.png)

### Settings show
![Bildschirmfoto von 2022-03-10 16-21-19](https://user-images.githubusercontent.com/213943/157694036-95e21605-94b4-459f-9551-234426cdaff7.png)

**Comment by JB1985** [comment]
Fresh install [Nextcloud Hub II](23.0.2)

![image](https://user-images.githubusercontent.com/9932751/157695063-c329fb74-586a-48ea-ae11-d6db8733a107.png)

![image](https://user-images.githubusercontent.com/9932751/157695279-5a399b28-969d-4ee8-8047-b0fbbf8e1793.png)

![image](https://user-images.githubusercontent.com/9932751/157695383-c254c6bb-924c-46df-91f4-ad0fcdd168a4.png)

**Comment by nickvergessen** [comment]
Also tested with stable23 and it works there

**Comment by nickvergessen** [comment]
Still works.

Can you check the table content of:
* oc_authorized_groups
* oc_groups
* oc_group_user
* oc_group_admin

This is my content:
```sql
INSERT INTO `oc_authorized_groups` (`id`, `group_id`, `class`) VALUES
(3, 'Gruppenadmin', 'OCA\\Theming\\Settings\\Admin'),
(4, 'Gruppenadmin', 'OCA\\DAV\\Settings\\CalDAVSettings');


INSERT INTO `oc_groups` (`gid`, `displayname`) VALUES
…
('Gruppenadmin', 'Gruppenadmin'),
…;


INSERT INTO `oc_group_admin` (`gid`, `uid`) VALUES
('Gruppenadmin', '39797ffa-12d6-43c1-8613-84947bd35175');


INSERT INTO `oc_group_user` (`gid`, `uid`) VALUES
…
('Gruppenadmin', '39797ffa-12d6-43c1-8613-84947bd35175'),
…
```

**Comment by JB1985** [comment]
> SELECT * FROM oc_authorized_groups
    -> ;
+----+--------------+---------------------------------+
| id | group_id     | class                           |
+----+--------------+---------------------------------+
|  1 | Gruppenadmin | OCA\Theming\Settings\Admin      |
|  3 | Gruppenadmin | OCA\DAV\Settings\CalDAVSettings |
+----+--------------+---------------------------------+

+--------------+--------------+
| gid          | displayname  |
+--------------+--------------+
| Gruppenadmin | Gruppenadmin |

+--------------+-------------+
| gid          | uid         |
+--------------+-------------+
| Gruppenadmin | jb-test |

+--------------+-------------+
| gid          | uid         |
+--------------+-------------+
| Gruppenadmin | jb-test |


The only difference is that I see the username and by you a UID for the users? Are you using database authentication? Or LDAP?

**Comment by MichaIng** [comment]
```
2022-03-10 17:34:07 root@VM-Bullseye:~# mysql -e 'select * from nextcloud.oc_authorized_groups;'
+----+-----------+-----------------------------------------+
| id | group_id  | class                                   |
+----+-----------+-----------------------------------------+
|  1 | testgroup | OCA\DAV\Settings\CalDAVSettings         |
|  2 | testgroup | OCA\Theming\Settings\Admin              |
|  3 | testgroup | OCA\ShareByMail\Settings\Admin          |
|  4 | testgroup | OCA\Federation\Settings\Admin           |
|  5 | testgroup | OCA\FederatedFileSharing\Settings\Admin |
|  6 | testgroup | OCA\Settings\Settings\Admin\Sharing     |
|  7 | testgroup | OCA\Settings\Settings\Admin\Mail        |
|  8 | testgroup | OCA\Settings\Settings\Admin\Server      |
|  9 | testgroup | OCA\Support\Settings\Admin              |
| 10 | testgroup | OCA\Settings\Settings\Admin\Overview    |
+----+-----------+-----------------------------------------+
2022-03-10 17:36:04 root@VM-Bullseye:~# mysql -e 'select * from nextcloud.oc_groups;'
+-----------+-------------+
| gid       | displayname |
+-----------+-------------+
| admin     | admin       |
| testgroup | testgroup   |
+-----------+-------------+
2022-03-10 17:36:16 root@VM-Bullseye:~# mysql -e 'select * from nextcloud.oc_group_user;'
+-----------+----------+
| gid       | uid      |
+-----------+----------+
| admin     | admin    |
| testgroup | testuser |
+-----------+----------+
2022-03-10 17:36:21 root@VM-Bullseye:~# mysql -e 'select * from nextcloud.oc_group_admin;'
+-----------+----------+
| gid       | uid      |
+-----------+----------+
| testgroup | testuser |
+-----------+----------+
```

**Comment by JB1985** [comment]
Is there a chance that the bug will be fixed by the next version?

**Comment by MichaIng** [comment]
First of all someone with more insights into the code needs to be able to replicate and identify related code and the bug within.

Whether the UID is a real name or a UUID-like string shouldn't matter, as long as it matches the `uid` field in:
```sh
mysql -e 'select * from nextcloud.oc_users;'
```
which is correct in my case.

It seems @nickvergessen added everything directly via SQL from command-line. The inserts match our output, but probably the GUI does something else? At least worth it to try it all via GUI, as we both did to replicate the issue.

**Comment by JB1985** [comment]
Who is the main developer of this function admin privileges? Maybe you can put him in CC?

**Comment by JB1985** [comment]
Yes! With 23.0.3 this bug is fixed!
