### ISSUE TITLE
Unable to load users / groups

### ISSUE THREAD

**Issue by dc3nity** [nextcloud/server#31334]
### Steps To Reproduce

1. Logged in via administrator account
2. Opened drop down menu to > "Users"

### Expected Result

- List of users to be shown

### Actual Result

- Popup : "An error occured during the request. Unable to proceed."
- Loading icon on list of users that never finishes loading

### Screenshots, Videos, or Pastebins

![image](https://user-images.githubusercontent.com/100349011/155503725-04d6ba19-6dfb-413d-9899-798853ddb219.png)

### Additional Context

- List of users visible via occ user:list
- List of users visible in db via pgsql

### Build Version

Nextcloud HanssonIT VM (23.0.2)

### Environment

By using the scripts

### Environment Details

Ubuntu 20.04.4 LTS
PSQL 12.9
Hosted on MS Azure

**Comment by CarlSchwan** [comment]
Please provide the server log as well as information about the user backend used (db, ldap, saml, ...)

**Comment by dc3nity** [comment]
[nextcloud.log](https://github.com/nextcloud/server/files/8132810/nextcloud.log)
Attached server log

No additional user backend, only in db via nextcloud

**Comment by chcioni** [comment]
Hi,
the same problem after updating from 22.2.3 to 22.2.5. When view an user list over 30  members saw the message "An error occured during the request. Unable to proceed."
Users defined only on mysql db.

**Comment by dc3nity** [comment]
Update:
Reinstall with same config lead to same error
Removal of reverse proxy (azure frontdoors) seems to have solved it

**Comment by chcioni** [comment]
The request is https://xxxxxxxx/ocs/v2.php/cloud/users/details?offset=0&limit=25&search= with exception Object { users: Getter & Setter, apps: Getter & Setter, settings: Getter & Setter, oc: Getter & Setter, route: Getter & Setter, … }
 Error: Request failed with status code 404
