### ISSUE TITLE
[Bug]: getBaseUrl should not guess server protocol (HTTP/HTTPS)

### ISSUE THREAD

**Issue by charlax** [nextcloud/server#31349]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When serving nextcloud server on HTTP behind an HTTPS-terminating reverse proxy such as nginx, nextcloud will assume that its base URL is `http://...`

This is because of:

`lib/private/URLGenerator.php`

```php
	public function getBaseUrl(): string {
		// BaseUrl can be equal to 'http(s)://' during the first steps of the intial setup.
		if ($this->baseUrl === null || $this->baseUrl === "http://" || $this->baseUrl === "https://") {
			$this->baseUrl = $this->request->getServerProtocol() . '://' . $this->request->getServerHost() . \OC::$WEBROOT;
		}
		return $this->baseUrl;
	}
```

This is an issue with OAuth2 redirection flow, this line will generate an `http://` link:

```php
	public function getBaseUrl(): string {
		// BaseUrl can be equal to 'http(s)://' during the first steps of the intial setup.
		if ($this->baseUrl === null || $this->baseUrl === "http://" || $this->baseUrl === "https://") {
			$this->baseUrl = $this->request->getServerProtocol() . '://' . $this->request->getServerHost() . \OC::$WEBROOT;
		}
		return $this->baseUrl;
	}
```

### Steps to reproduce

1. Serve nextcloud on HTTP behind a reverse proxy terminating HTTPS such as nginx
2. Start the OAuth2 flow
3. Nextcloud server issues a redirection to an `http://`, which nginx will redirect to `https://` dropping URL params in the process, which will fail the OAuth2 process.

### Expected behavior

Nextcloud server always uses `https://...` base URL.

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.3

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
N/A
```

### Additional info

A simple fix would be to always use the configureable base URL when redirecting.

Note: as I write this, I see that such a setting exists `overwriteprotocol`, described in https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html#overwrite-parameters

I will use this setting in the meantime, but I'm wondering if it wouldn't be more intuitive to have a configureable base URL.

**Comment by acsfer** [comment]
Well, as you've stated, `overwriteprotocol` parameter exists exactly for that reason 🤔

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
