### ISSUE TITLE
NC 11  LDAP issue on server profiles

### ISSUE THREAD

**Issue by we-sell-bags** [nextcloud/server#3135]
### Steps to reproduce
1. enter at-least TWO different LDAP servers
2. ensure the one you want to use is SECOND (2)
3. disable the first one, in advanced tab

### Expected behaviour
when I disable an LDAP server I expect it to say disabled, until i physically re-enable it.

### Actual behaviour
sometimes the web browser will start up with the first menu item selected for ldap server (default value?)

1. even though the second one is being used, this forces the 1st ldap server to be re-enabled, so in affect you have multiple LDAP servers serving next cloud.

2. If you want to  duplicate, or  want to review another DISABLED LDAP server ,the process of selecting it in the menu box , automatically re-enables the LDAP you are looking at!!!!!

both these action , re-enable the "advanced->configuration active" flag

### Server configuration
NC 11.0.0   provided VM  stock install for LAMP

**Comment by nickvergessen** [comment]
@blizzz any idea?

**Comment by blizzz** [comment]
> sometimes the web browser will start up with the first menu item selected for ldap server (default value?)

What does it mean, exactly? When you go to the admin page, the first LDAP server in the list is presented. However, no auto-activation is supposed to happen. So far I fail to reproduce it.

> even though the second one is being used, this forces the 1st ldap server to be re-enabled, so in affect you have multiple LDAP servers serving next cloud.

This is not covered in the reproduction steps. I assume the following:

scenario 1:

4. Open LDAP  Admin page again and do nothing else
→ First configuration is activated

scenario 2:

4. Open LDAP  Admin page again 
5. While test is running, switch immediately to second server
→ First configuration is activated

Both scenarion work fine for me, i.e. no auto-enabling of server 1.

> If you want to duplicate, or want to review another DISABLED LDAP server ,the process of selecting it in the menu box , automatically re-enables the LDAP you are looking at!!!!!

I cannot confirm this either. Perhaps I am missing a detail?

Which browser are you using?

**Comment by we-sell-bags** [comment]
ok let me re-check with multiple browsers (ill snapshot some screens)

basically what i am saying is:
if you have an "inactive" AD server at list position 1, and an active at list position 2
the configuration at list position 1 is re-enabled... which shows as "double users" with different id's

**Comment by we-sell-bags** [comment]
the original analysis was not fully the trigger.

The position of the configs does not matter.
2 AD configs  setup,  one is disabled.

Random navigation round the admin screen menus, unrelated to the AD setup triggers BOTH configs to be enabled.

works with both:
Safari 10.0.2
firefox 50.1.0

**Comment by blizzz** [comment]
Can you tell me more about the "random navigation"? Perhaps take a screencast?

**Comment by MorrisJobke** [comment]
I will close this due to inactivity. We are happy to open this again once more information is available.
