### ISSUE TITLE
[Bug]: File Download/Preview/Streaming Gets Truncated/Corrupted when Served from SMB/CIFS Share (Not Using NC smbclient)

### ISSUE THREAD

**Issue by GuyPaddock** [nextcloud/server#31361]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

We recently upgraded an installation of Nextcloud from 18.0.14 to 19.0.13 and now are experiencing a serious problem where most files that are larger than about 2 MB do not download properly from Nextcloud when they are sourced from an SMB/CIFS share. Almost all of our files are hosted on Azure Files over SMB, so this is a big problem for us. **(We can reproduce the issue with ALL VERSIONS OF NEXTCLOUD after 19 -- see below).**

When working with image files that were previously uploaded (it does not matter if the image was uploaded before or after the upgrade), we will see one of the following happen:
1. The image file won't load at all when being previewed: ![image](https://user-images.githubusercontent.com/2631799/155801609-0ad8d9aa-bc75-463d-9214-cf3cbbf7b94a.png) ![image](https://user-images.githubusercontent.com/2631799/155803066-ec5ebedd-ce29-40cf-8223-ae668411f3c4.png) 

2. OR - The image loads, but is truncated or corrupt: 
![image](https://user-images.githubusercontent.com/2631799/155802925-d1b1d97f-e181-4c3d-8e0c-3566c3a02cf4.png)
![image](https://user-images.githubusercontent.com/2631799/155805515-5c7e126c-0ef8-4583-a777-a6e45fefadac.png)

3. When we try to download the image, the download fails with a "Network error". 
![image](https://user-images.githubusercontent.com/2631799/155803696-a193c233-218b-40d9-a814-6a0ab1770704.png)

With video files, we find that the video either does not play or plays with artifacts and corruption throughout the image (the source video does NOT have this corruption).
![image](https://user-images.githubusercontent.com/2631799/155805655-71cda1fa-229b-4383-a0ba-0774f5e85faa.png)

Oddly, if we select multiple files and select "Download" (so that they download as a single ZIP), the resulting ZIP downloads without issue and the files inside are not corrupt, so this is only affecting the behavior of streaming/loading individual files from the web UI directly.

I saw https://github.com/nextcloud/server/issues/26457 and https://github.com/nextcloud/server/issues/26933 but our issue differs from those issues in significant ways:
- We are not using any of the SMB functionality of Nextcloud itself. Rather, we are mounting storage from SMB into the Docker container via the Kubernetes Azure Files and SMB drivers.
- Both of those issues were against 21.0.1.0 which did not have the fix from https://github.com/nextcloud/server/pull/26627 / https://github.com/nextcloud/server/pull/26704, which got released in 21.0.2 and 20.0.9, but we are seeing this in all recent versions of Nextcloud that already have the Icewind fixes.

When nginx is being used to host Nextcloud, it is significantly more strict about the issue and will terminate the connection if something isn't right, failing with the following error:
```
[alert] 32#32: *1 readv() failed (14: Bad address) while reading upstream
```
![image](https://user-images.githubusercontent.com/2631799/155810963-22c1097a-38f3-4465-a36f-bcd1107798e9.png)

If we switch to Apache-based Docker containers, Apache does not report any errors but the file it serves-up has corruption throughout, which is arguably way worse (because users might not realize that the file is corrupt since they still get the right number of bytes that they asked for, but the bytes are corrupt).

### Steps to reproduce

1. Setup Nextcloud to run in a Kubernetes-powered container (PHP-FPM or Apache; it does not matter).
2. Setup the *container* to mount a volume over an Azure Files or SMB to the path `/mnt/share/test`.
    For example, a container with a volume mount like (the rest of the container boilerplate has been omitted):
    ```yaml
        volumeMounts:
        - mountPath: /mnt/share/test
          name: volume-nextcloud-test
    ```

    Declared as:
    ```yaml
      volumes:
      - name: volume-nextcloud-test
        persistentVolumeClaim:
          claimName: claim-nextcloud-test
    ```

    With PVs and PVCs of (secrets omitted):
    ```yaml
    apiVersion: v1
    kind: PersistentVolume
    metadata:
      annotations:
      name: vol-share-nextcloud-test
    spec:
      accessModes:
      - ReadWriteMany
      azureFile:
        secretName: nextcloud-storage-azure-files-creds
        shareName: nextcloud-test
      capacity:
        storage: 1Ti
      mountOptions:
      - uid=33
      - gid=33
      - dir_mode=0770
      - file_mode=0770
      persistentVolumeReclaimPolicy: Retain
    ---
    apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      annotations:
      name: claim-nextcloud-test
    spec:
      accessModes:
      - ReadWriteMany
      resources:
        requests:
          storage: 1Ti
      storageClassName: ""
      volumeName: vol-nextcloud-test
    status:
      accessModes:
      - ReadWriteMany
      capacity:
        storage: 1Ti
      phase: Bound
    ```
4. Configure Nextcloud with a local External storage that points to `/mnt/share/test`: 
![image](https://user-images.githubusercontent.com/2631799/155809185-e78982b1-55bb-4663-8d20-451cf735fb26.png)
5. Turn image previews OFF for the share, so that the preview lightbox shows full-resolution images (makes this easier to reproduce).
6. Upload an image or video file that is larger than 5 MB to the share (for example, the 25 MB Rome, Italy image from https://effigis.com/en/solutions/satellite-images/satellite-image-samples/).
7. Attempt to open the image or video file in the preview lightbox. Repeat this step at least 5 times, clearing browser cache in between attempts.
8. Attempt to download the image or video file through the Nextcloud web UI. Repeat this step at least 5 times, clearing browser cache in between attempts.

### Expected behavior

The image or video should load without error.

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "simpleSignUpLink.shown": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "dev.cloudvault.inveniem.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.2.1",
        "overwrite.cli.url": "https:\/\/dev.cloudvault.inveniem.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "appstoreenabled": false,
        "enable_previews": true,
        "preview_max_filesize_image": 50,
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": false
            }
        ],
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": 1,
        "filelocking.enabled": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "6379",
            "timeout": 1.5,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "dbdriveroptions": {
            "1009": "\/etc\/ssl\/certs\/Baltimore_CyberTrust_Root.pem"
        },
        "config_is_read_only": true,
        "skeletondirectory": "",
        "mysql.utf8mb4": true,
        "preview_max_x": 1024,
        "preview_max_y": 1024,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "user_external",
            "user_saml"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - checksum: 1.1.3
  - circles: 23.0.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contactsinteraction: 1.4.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_downloadactivity: 1.12.0
  - files_external: 1.15.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - metadata: 0.15.0
  - music: 1.5.1
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_external: 2.1.0
  - user_saml: 4.1.1
  - viewer: 1.7.0
  - workflowengine: 2.5.0
Disabled:
  - dashboard: 7.0.0
  - encryption
  - files_antivirus: 2.4.1
  - files_automatedtagging
  - firstrunwizard: 2.4.0
  - previewgenerator
  - user_ldap
  - user_status: 1.0.1
  - weather_status: 1.0.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
N/A (container logs)
```

### Configurations Attempted
This issue appears when using files > 2 MB over SMB with ALL of the following configurations:
- Nextcloud 19.0.13, 20.0.14, 21.0.9, 22.2.5, and 23.0.2
- nginx 1.19.6, 1.21.0, 1.21.3, 1.21.6:
  - nginx with `sendfile off` and `sendfile on`.
  - nginx with `sendfile on` and `sendfile_max_chunk 1m`.
- Apache 2.4.52 (Debian) and PHP/8.0.16.
- SMB version 3.0.0 and version 3.1.1.
- SMB with `cache=none` and `cache=strict`.
- Firefox 97.0.1 (64-bit) and Microsoft Edge 98.0.1108.56.
- Kubernetes 1.15.10 and 1.22.6
- Both the Azure Files and SMB CSI drivers
- Both Azure Files and a Qumulo-based SMB cluster.

The issue does NOT appear if we create a folder inside the container (e.g., `mkdir -p /mnt/local/test`) and then mount that as external storage. The issue also was not reproducible with Nextcloud 18.0.14.

**Comment by GuyPaddock** [comment]
UPDATE: I tried rolling Icewind back to the version that was in Nextcloud 20.0.18, per comments in https://github.com/nextcloud/server/issues/26457, but the rollback had no effect on the behavior, so this is not looking like an Icewind issue per say.

**Comment by GuyPaddock** [comment]
Another update: It appears that this issue is either related to a change in PHP or a change in Sabre/HTTP.

It is documented elsewhere that mmap combined with SMB volumes can lead to corrupt file reads:
- https://serverfault.com/questions/1044724/apache2-sends-corrupt-responses-when-using-a-cifs-share
- https://superuser.com/questions/1483696/cifs-mounted-on-linux-from-windows-shows-corrupt-distorted-images
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=900821

Now, it looks like Sabre HTTP 5.0.3 added enhancements to make better use of `mmap()` through the `stream_copy_to_stream()` method:
![image](https://user-images.githubusercontent.com/2631799/155827715-35c553ee-918f-48e5-ba06-bd3836e39c5c.png)

For more context, the MR referenced by the Sabre HTTP changelog is:
https://github.com/sabre-io/http/pull/119

And that version was pulled into Nextcloud 19.0.0 (coincidentally, we started seeing this issue upon upgrading from 18.0.14 to 19.0.13 as mentioned in the issue description):
https://github.com/nextcloud/3rdparty/commit/b0afba6d6508a1c85332cf8c61e90ad91b289ebc

Prior to NC 19, NC was using version 4.2.4 of Sabre HTTP.

---
Now, I thought I had a slum dunk here because this theory would have worked perfectly to explain the behavior that we are seeing, except that the code in https://github.com/sabre-io/http/pull/119 doesn't actually call `mmap()` at all. Rather, it ensures that data is read in chunks of 4 MB so that under the hood, PHP uses `mmap()` within its implementation of `stream_copy_to_stream()`. In our container image, I created a patch to Nextcloud 23.0.2 that reverted Sabre HTTP to version 5.0.2 (the version right before https://github.com/sabre-io/http/pull/119 was merged) and tried that but we got the same behavior.

HOWEVER one last thing I tried was -- in addition to reverting 119 -- I modified `\Sabre\HTTP\Sapi::sendResponse()` so that instead of this:
```php
        if (null !== $contentLength) {
            $output = fopen('php://output', 'wb');
            if (is_resource($body) && 'stream' == get_resource_type($body)) {
                if (PHP_INT_SIZE !== 4) {
                    // use the dedicated function on 64 Bit systems
                    stream_copy_to_stream($body, $output, (int) $contentLength);
                } else {
                    // workaround for 32 Bit systems to avoid stream_copy_to_stream
                    while (!feof($body)) {
                        fwrite($output, fread($body, 8192));
                    }
                }
            } else {
                fwrite($output, $body, (int) $contentLength);
            }
        } else {
            file_put_contents('php://output', $body);
        }
```

It read as:
```php
        if (null !== $contentLength) {
            $output = fopen('php://output', 'wb');
            if (is_resource($body) && 'stream' == get_resource_type($body)) {
                // workaround for 32 Bit systems to avoid stream_copy_to_stream
                while (!feof($body)) {
                    fwrite($output, fread($body, 8192));
                }
            } else {
                fwrite($output, $body, (int) $contentLength);
            }
        } else {
            file_put_contents('php://output', $body);
        }
```

... and that works. Attached is the resulting patch (for debugging only). This is obviously not a fix because it seems to have a significant performance hit, but it does seem to narrow down where the issue is.

[sabre-http-revert-5.0.2-and-mmap.patch.txt](https://github.com/nextcloud/server/files/8145860/sabre-http-revert-5.0.2-and-mmap.patch.txt)

**Comment by GuyPaddock** [comment]
More surgical patch that _just_ removes calls to `stream_copy_to_stream()` from Sabre/HTTP.
[sabre-http-avoid-mmap.patch.txt](https://github.com/nextcloud/server/files/8145923/sabre-http-avoid-mmap.patch.txt)

**Comment by GuyPaddock** [comment]
It looks like our Nextcloud v18.0.14 image was running PHP 7.3.26 whereas the v19.0.13 image is running PHP 7.4.21. That's significant because, in addition to the `mmap()` enhancement that was made to Sabre/HTTP, [the maintainers](https://github.com/sabre-io/http/pull/119#issuecomment-483025246) filed [an enhancement request](https://bugs.php.net/bug.php?id=77930) to the PHP core team, which resulted in this change to PHP code:
https://github.com/php/php-src/commit/333d607d47ca6eec96637c1c8686591dec6f5a0b.

Which... rolled out in PHP 7.4.

My hypothesis is that files on an SMB share that are < 4 MB can be read with minimal or no side effects through `mmap()`, while files > 4 MB are unstable via `mmap()`. Since [PHP 5.4](https://github.com/nikic/php-src/commit/f8f01a1fd1ef00c2797da5f2f8125a3b9d78f046) through 7.3 avoided using `mmap()` for files > 4 MB, this defect was avoided. Now that PHP 7.4 no longer has that logic, it's not safe to use `stream_copy_to_stream()` on files from SMB until the underlying kernel bug or whatever is causing these reads to be unstable is fixed.

**Comment by andyxheli** [comment]
Hi @GuyPaddock NC19 is EOL I would upgrade to the NC 22 or NC 23 and see if the issue is still present. Please see release schedule in the below link.

https://docs.nextcloud.com/server/latest/admin_manual/release_schedule.html

**Comment by GuyPaddock** [comment]
@andyxheli Please re-read my message. :)

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
