### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by FranciscoBigWings** [nextcloud/server#31375]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I cant send emails from nextcloud from mail app. Test email doesnt work either.

----------------------------------
**In the Nextcloud server cloud.mydomain.com** 
The error when I click "Send email" in email server: A problem occurred while sending the email. Please revise your settings. (Error: Connection could not be established with host mail.mydomain.com :stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed)

Everything else in Nextcloud works besides email service. 
The error is present since the fresh install of Nextcloud 22.1.1. but I didnt have the time to find a solution.

------------------------------------
**In the email server mail.mydomain.com** 
I get the following log in Postfix:
1. warning: hostname server2.mydomain.com does not resolve to address 123.123.123.1
2. warning: TLS library problem: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:../ssl/record/rec_layer_s3.c:1544:SSL alert number 48:

Related to warning 1: obviously server2.mydomain.com cant resolve to 123.123.123.1 as it is resolving to Cloudflares IPs
Related to warning 2: if I disable proxied DNS of server2 in Cloudflare, it dissapears in future logs; disabling proxy DNS is not desireble

### Steps to reproduce

1. Send mode SMTP; Encrypthon SSL/TLS; Authentication method "Login"; Authentication required. Set the other email address and credentials information.
2. Mail.mydomain.com is a different server running mailcow mailserver. There is a third server with a CRM service that can send and receive emails through mail.mydomain.com with SMPT mode.
3. Nextcloud is only service in cloud.mydomain.com server with FQDN "server2.mydomain.com" and IP 123.123.123.1
4. Nextcloud server is running behind apache and signed with Letsencrypt certificates
5. Nextcloud server is running behind Cloudflare service with proxied DNS

### Expected behavior

It should allow to send emails

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
"system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.mydomain.com",
            "123.123.123.1",
            "office.mydomain.com",
            "111.111.111.1", (cloudflare IP)
            "111.111.111.2" (cloudflare IP)
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.3.0",
        "overwrite.cli.url": "https:\/\/cloud.mydomain.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "auth.bruteforce.protection.enabled": false,
        "log_type": "file",
        "logtimezone": "Europe\/Madrid",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": 2,
        "overwriteprotocol": "https",
        "default_phone_region": "ES",
        "default_language": "es",
        "simpleSignUpLink.shown": false,
        "app_install_overwrite": {
            "0": "onlyoffice",
            "verify_peer_off": true
        },
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [
            "office"
        ],
        "maintenance": false,
        "theme": "",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465"
    }
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - breezedark: 22.3.0
  - bruteforcesettings: 2.3.0
  - calendar: 3.0.6
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.8
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - encryption: 2.10.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_accesscontrol: 1.12.1
  - files_antivirus: 3.2.2
  - files_automatedtagging: 1.12.0
  - files_fulltextsearch: 22.0.1
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - fulltextsearch: 22.0.1
  - fulltextsearch_elasticsearch: 22.0.1
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - mail: 1.11.7
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - onlyoffice: 7.3.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - ransomware_protection: 1.12.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - spreed: 12.2.3
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - workflowengine: 2.4.0
Disabled:
  - admin_audit
  - files_external
  - nextcloud_announcements
  - onlyoffice-nextcloud
  - user_ldap
  - weather_status
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
No server logs
Everything is working fine
```

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
