### ISSUE TITLE
file chunk upload returns 404 error

### ISSUE THREAD

**Issue by tracymacding** [nextcloud/server#3137]
set maxChunkSize to 1048576 in apps/files/js/jquery.fileupload.js
then upload a big file, got error:
```
target dir '/' does not exist any more
```

look into http request as below:
```
Request URL:http://192.168.100.50:8081/remote.php/dav/uploads/tracymacding/web-file-upload-0d3479de911192171b7592829c45897f-1484708715226/0-1048575
Request Method:PUT
Status Code:404 Not Found
Remote Address:192.168.100.50:8081
```

what's wrong?

**Comment by nickvergessen** [comment]
I guess you upload took too long. Why do you want to manipulate the chunksize anyway?

**Comment by MorrisJobke** [comment]
We are happy to reopen this request but for now I will close this issue. Thanks

**Comment by cowai** [comment]
@nickvergessen To not have to rely on having a fast connection and have very high timeout limits. My guess. This would be a huge benefit for me if chunked upload worked in the web ui.

**Comment by MorrisJobke** [comment]
> @nickvergessen To not have to rely on having a fast connection and have very high timeout limits. My guess. This would be a huge benefit for me if chunked upload worked in the web ui.

That is a different topic. In this case the chunk size was increased not decreased.

**Comment by cowai** [comment]
the maxchunksize setting is set to undefined as default which disables the chunking, as far as I am aware.

**Comment by MorrisJobke** [comment]
> the maxchunksize setting is set to undefined as default which disables the chunking, as far as I am aware.

Where is this setting?

**Comment by cowai** [comment]
@MorrisJobke [jquery.fileupload.js#L151](https://github.com/nextcloud/server/blob/master/apps/files/js/jquery.fileupload.js#L151)

**Comment by DavidMarekCZ** [comment]
@cowai agree, this is must-have in web ui... to chunk and upload larger files.
