### ISSUE TITLE
[Bug]: not able to set custom status-icon without status-message via api

### ISSUE THREAD

**Issue by mahibi** [nextcloud/server#31452]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The api https://docs.nextcloud.com/server/latest/developer_manual/client_apis/OCS/ocs-status-api.html?highlight=status#set-a-custom-message-user-defined doesn't allow us to set a custom status-icon without a status-message.
If the sent status-message is empty or it's not contained at all in the request, then also the the statusIcon and clearAt is set to null.

So for the mobile apps it's currently not possible to set a status icon without message.
See https://github.com/nextcloud/talk-android/pull/1841#issuecomment-1057023445

### Steps to reproduce

1. set icon in api request but leave message empty
2. icon won't be set

### Expected behavior

icon is set successfully

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
see CNC or sermo
```

### Additional info

bug occurs for
CNC: 23.0.2.1
Sermo: 24.0.0.4

not aware if it ever worked

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
