### ISSUE TITLE
Choose non empty template and set file name

### ISSUE THREAD

**Issue by msi-tl** [nextcloud/server#31468]
In corporates it is mostly common to use a name scheme for documents.
If you want to use templates for documents, it is not quite easy to remember the correct name of that schemas.

Currently the sequence of creating a document from template is:
1. Choose file name
2. Choose template
3. Click rename file to set correct name manually

**Describe the solution you'd like**
It would be much better to select template first (showing the name schema) and then set the name for the new file.
The default name for the new file should be taken from template.

Example:
1. If the are non empty templates, "create new document" pops up the template selector otherwise go to "set name" directly. 
2. After selecting the template, go to "set name". The suggested name is taken from template. I.e. "vacation_request_yyyy.docx"

**Comment by jancborchardt** [comment]
> @jancborchardt What do you think about that? Would be something we'd need to implement in the server template picker so moving this over.

Sounds good actually – it was always the original design that name input and template picker are on the same step (name input on top). And with this adjustment, unless you already modified the name from "New document" (or "New text file" etc) it could take the name from the template.

**Comment by skjnldsv** [comment]
We recently had that, where we could set the name after the template, but this as rolled back and decided against.
Seems like it was creating more issues than benefits :(
