### ISSUE TITLE
[Bug]: Daten werden nach einem Scan aus der App nicht synchronisiert 

### ISSUE THREAD

**Issue by nicobauernodered** [nextcloud/server#31472]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Ich habe mit der offiziellen Nextcloud App aus iOS scanns von Dokumenten erstellt und diese als pdf auf den Server kopiert. Dies hat auch funktioniert und wurde ohne Fehlermeldung durchgeführt. 
leider wurden diese Scanns nicht auf den Rechner übertragen. 
Dieser Fehler ist mir aufgefallen, da ich ein älteres Backup des Servers einspielen musste und die Scanns waren in dem Backup nicht enthalten. 
in der Synchronisation Historie auf der Rechnerapp wurden sie nach dem Zurückspielen des Backups nicht als gelöscht markiert und sind aber auch nicht im Sync Ordner. 
auf dem Mac ist die aktuellste Version der Desktopapp installiert. Dateien die ich über die Desktop App nach dem Backup des Servers synchronisiert habe, sind auch nach dem Zurückspielen des Backups verfügbar. 

Für mich stellt sich der Fehler im Zusammenspiel zwischen iOS App Upload und Desktop App dar. 

### Steps to reproduce

1.Backup Server anlegen 
2.Daten mit iOS App scannfunktion erstellen und auf Server kopieren
3.Desktopapp in Betrieb haben und Daten auf Server kopieren
4. Backup ohne neue Daten zurückspielen

### Expected behavior

Daten aus der iOS werden beim nächsten Starten der Desktop App synchronisiert 

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MariaDB

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Reiche ich gerne nach.
```

### Nextcloud Signing status

```shell
Keine Fehler wurden gefunden
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
