### ISSUE TITLE
Custom favicon not showing up in Mac Safari

### ISSUE THREAD

**Issue by crasherwosa** [nextcloud/server#31471]
I also have the same problem. I have changed the favicon via Settings/Design/Favicon. Now it is attracted in Opera, Firefox or even Chrome. But not in Safari. In Safari, only the favicon color is adjusted to the set color of the navigation. If now the color is changed to purple under Settings/Design, the favicon is also purple with the Nextloud logo. 

Is there any more info in the meantime on what this is? File format? Size? Bug?

I use Nextcloud Hub II (23.0.2) - Safari Version 15.2

_Originally posted by @crasherwosa in https://github.com/nextcloud/server/issues/14818#issuecomment-1052000610_

**Comment by szaimen** [comment]
Please fill out the issue template
