### ISSUE TITLE
[Bug]: External storage files only recognized after viewing in web GUI

### ISSUE THREAD

**Issue by FloMiLe** [nextcloud/server#31483]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I use an External storage folder for backup files that are supposed to be synchronized from the server to a client. The problem is that newly added files to the External storage do not get automatically synchronized. NC does not seem to be aware of them. Even triggering a "Force sync now" in the Nextcloud Desktop Client (Version 3.4.2, macOS) does not help.

However, using the web UI helps. At first, when I open the UI, the modified date and the folder size are outdated. When I descend into the folder where new backup files where stored by the server's cron job, i.e. a daughter of the included External storage, I see all the expected files. Afterward, the modified dates and sizes of the parent folders have been updated and are accurate. Furthermore, the Nextcloud Desktop Client also gets triggered and syncs the files to the client computer.

So it seems that only displaying the files in the web UI makes NC aware of them.

### Steps to reproduce

1. Configure External storage in a NC instances.
2. Set up a sync connection to that folder.
3. Copy or create files in the External storage folder in the background, i.e. not through NC, but via the CLI for example.

### Expected behavior

NC should immediately sync the new or modified files to the client computer. 

But that only happens after the files have been viewed in the web UI.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
"system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.2.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "default_phone_region": "CH",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
```

### List of activated Apps

```shell
Enabled:
  - backup: 1.0.4
  - bruteforcesettings: 2.3.0
  - cloud_federation_api: 1.6.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - files: 1.18.0
  - files_external: 1.15.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - groupfolders: 11.1.2
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - polls: 3.5.4
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - survey_client: 1.11.0
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - viewer: 1.7.0
  - workflowengine: 2.5.0
Disabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit
  - circles: 23.0.0
  - comments: 1.13.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - encryption
  - federation: 1.13.0
  - firstrunwizard: 2.12.0
  - photos: 1.5.0
  - recommendations: 1.2.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - systemtags: 1.13.0
  - user_ldap
  - user_status: 1.3.1
  - weather_status: 1.3.0
```

**Comment by pkmkrishnakumar** [comment]
Create Cron Job to NC aware of the changes made directly in the folder (either by command prompt / samba share / any other means)

For example here , i use every 10 minutes, NC checks for any change in External Storage Directory (Mounted via NFS Share)

*/10 * * * *    sudo -u www-data php /var/www/nextcloud/occ files:scan --path="/path-to-external-storage/"

**Comment by szaimen** [comment]
Honestly the better way is to use this https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/external_storage/smb.html?highlight=notify#smb-update-notifications or this https://github.com/icewind1991/files_inotify and then it should work automatically without the need to open the webview.

**Comment by FloMiLe** [comment]
Thanks, @pkmkrishnakumar and @szaimen, for your suggestions!

Unfortunately, I seem to be too much of a dummy to get the INotify file watcher to work. (After installing ''inotify-tools'' on Ubuntu, INotify still says that the inotify library is not available.) So the cron job seems to be the simpler solution. I am curious though: Why would INotify be the better way?
