### ISSUE TITLE
themed site title shows as „Nextcloud“ again in the Files app using Safari

### ISSUE THREAD

**Issue by cmdr8** [nextcloud/server#3148]
### Steps to reproduce
1. Change name to ‚xcloud‘ using the theming app
2. open Files Screen with Safari for Mac (10.0.2) – or latest mobile Safari on iOS

### Expected behaviour
site title should be „Files - xcloud“  or in my case: „Dateien - xcloud“ in German

### Actual behaviour
site title shows as „Dateien - xcloud“ for about a second, then changes to „Dateien - Nextcloud“
(but both Firefox and Chrome show it correctly)

### Server configuration
**Operating system**:
Ubuntu (shared hosting with all-inkl.com)

**Web server:**
unknown

**Database:**
MySQL

**PHP version:**
7.0 (cgi)

**Nextcloud version:** (see Nextcloud admin page)
11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 10.3 today (or was it 10.0.3?)

**Where did you install Nextcloud from:**
web installer

**Signing status:**
<details>
<summary>Signing status</summary>

no errors found</details>

**List of activated apps:**
<details>
<summary>preactivated apps 
+ 
Activities for shared file downloads, AppOrder, Calendar, Contacts, Direct Menu, Reader (ebook reader), Tasks
</summary>
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
 <?php
$CONFIG = array (
  ‚instanceid‘ => ‚*****‘,
  'passwordsalt' => ‚*****‘,
  'secret' => ‚*****‘,
  'trusted_domains' => 
  array (
    0 => ‚***cloud.de‘,
    1 => ‚cloud.***.li‘,
  ),
  'datadirectory' => '/www/htdocs/*****/cloud/data',
  'overwrite.cli.url' => 'https://*****cloud.de',
  'dbtype' => 'mysql',
  'version' => '11.0.1.2',
  ‚dbname‘ => ‚d*****e6‘,
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  ‚dbuser‘ => ‚d0*****6‘,
  'dbpassword' => ‚*****‘,
  'logtimezone' => 'UTC',
  'installed' => true,
  'maintenance' => false,
  'mail_from_address' => 'no-reply',
  'mail_smtpmode' => 'php',
  'mail_domain' => ‚*****cloud.de',
  'theme' => '',
  'loglevel' => 2,
  'updater.secret' => ‚*****‘,
  'updater.release.channel' => 'stable',
);

```
</details>
(the mess with that ‚typographic quotation marks‘ is made by me here and not found in the original php file :) )

**Are you using external storage, if yes which one:** SFTP

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
Safari 10.0.2

**Operating system:**
macOS 10.12.2 (macOS Sierra)

#### Web server error log
<details>
<summary>Web server error log</summary>
```
n/a
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
opendir(/tmp): failed to open dir: Permission denied at /www/htdocs/*****/cloud/lib/private/TempManager.php#189	
```
(on each cron run)
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
n/a
```
</details>

**Comment by JaredBoone** [comment]
I have reproduced this issue with Nextcloud 11.0.1RC1 and Safari 10.0.2.

**Comment by nickvergessen** [comment]
@Ivansss can you test this quickly, whether that works on your instance?
