### ISSUE TITLE
[Bug]: 2FA using u2f device broken in chromium browsers

### ISSUE THREAD

**Issue by dmolineus** [nextcloud/server#31489]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since february 2022 chromium browser does not support the U2F protocol anymore. Web applications should and websites like Github/Gitlab/etc. already did switching to webauth for a device driven U2F solution.

More resources:

- https://developer.chrome.com/blog/deps-rems-95/#deprecate-u2f-api-cryptotoken
- https://developer.chrome.com/blog/deps-rems-95/#chrome-98
- https://groups.google.com/a/chromium.org/g/blink-dev/c/xHC3AtU_65A
- https://thenewstack.io/deprecation-from-u2f-api-to-webauthn/

### Steps to reproduce

1. To to login with a u2f device you have already registered. Nothing will happen

Or
1. Go to security setttings
2. Try to register a u2f device
4. Nothing happens

### Expected behavior

Login with a 2FA security stick should continue working as it did before february 2022.

### Installation method

Manual installation

### Operating system

RHEL/CentOS

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MySQL

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - apporder: 0.14.0
  - calendar: 3.1.0
  - carnet: 0.24.4
  - circles: 23.0.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - event_update_notification: 1.4.0
  - extract: 1.3.3
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - keeweb: 0.6.8
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - polls: 3.5.4
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - systemtags: 1.13.0
  - tasks: 0.14.2
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_u2f: 6.3.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - forms: 2.4.0
  - survey_client: 1.7.0
  - user_ldap: 1.8.0
```

**Comment by ph00lt0** [comment]
This is should be reported here: https://github.com/nextcloud/twofactor_u2f

**Comment by ph00lt0** [comment]
Seems to already been reported here: https://github.com/nextcloud/twofactor_u2f/issues/947
Closing this.

**Comment by ph00lt0** [comment]
Solution is here: https://github.com/nextcloud/twofactor_webauthn#migration-from-two-factor-u2f

**Comment by 4oo4** [comment]
@ph00lt0 What version implements the `twofactorauth_webauthn` command for occ? I just upgraded to 23.0.3, and I only have a `twofactor` auth command, but not `twofactorauth_webauthn`.

**Comment by ph00lt0** [comment]
Yep new app is required, you can remove the old one after.
