### ISSUE TITLE
Admin/logging page can be disabled and cannot be re-enabled

### ISSUE THREAD

**Issue by jiml8** [nextcloud/server#3149]
### Steps to reproduce
1.  go to admin/logging page
2.  uncheck all options for logging
3.  observe page become blank except for top bar and message "No server logs
Everything is working fine"

### Expected behaviour
Tell us what should happen
Page should become blank, and the message is OK.  However the checkboxes to re-enable various degrees of logging should be available.

### Server configuration
**Operating system**:
Nas4Free (FreeBSD 11)

**Web server:**
litghttpd
**Database:**
sqlite
**PHP version:**
7.something
**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**
problem started on upgrade from Nextcloud 10 to Nextcloud 11.0.0 and persists after upgrade to 11.0.1
**Where did you install Nextcloud from:**
Nextcloud site

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by icewind1991** [comment]
Already fixed with https://github.com/nextcloud/logreader/commit/c77ee8186f61018afe78de41a4811e639e08edf9
