### ISSUE TITLE
[Bug]: Comments limited to 1000 chars

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#31495]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Despite https://github.com/nextcloud/server/pull/16088 comments are limited to 1000 chars.

### Steps to reproduce

1. Go to try.nextcloud.com
2. Comment on a folder the text here below

> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Vel quam elementum pulvinar etiam non quam. Eu tincidunt tortor aliquam nulla facilisi cras fermentum. Cursus in hac habitasse platea. Maecenas ultricies mi eget mauris. Dictum non consectetur a erat nam. Habitant morbi tristique senectus et. Cursus sit amet dictum sit. At consectetur lorem donec massa sapien. Adipiscing tristique risus nec feugiat in fermentum posuere. Lorem donec massa sapien faucibus et molestie ac feugiat. Viverra ipsum nunc aliquet bibendum enim facilisis gravida. At augue eget arcu dictum. Sed ullamcorper morbi tincidunt ornare massa eget egestas purus. Tellus cras adipiscing enim eu turpis egestas pretium aenean pharetra. Eu non diam phasellus vestibulum lorem. Viverra tellus in hac habitasse platea dictumst vestibulum rhoncus. Gravida in fermentum et sollicitudin ac orci phasellus. In egestas erat imperdiet sed euismod nisi porta. Id faucibus nisl tincidunt eget nullam. Et tortor at risus viverra adipiscing at in tellus. Tellus in metus vulputate eu scelerisque. Odio morbi quis commodo odio aenean sed adipiscing diam. At tellus at urna condimentum mattis pellentesque id. Eleifend quam adipiscing vitae proin sagittis nisl rhoncus. Convallis posuere morbi leo urna molestie at elementum. Tempor commodo ullamcorper a lacus vestibulum sed arcu non. Amet volutpat consequat mauris nunc congue nisi vitae suscipit tellus. Facilisi nullam vehicula ipsum a arcu cursus. Donec adipiscing tristique risus nec feugiat in. Nulla at volutpat diam ut venenatis. Cursus mattis molestie a iaculis at erat pellentesque adipiscing commodo. Lobortis elementum nibh tellus molestie. Quis blandit turpis cursus in hac habitasse. Tortor id aliquet lectus proin nibh nisl. Et tortor at risus viverra adipiscing at. Odio aenean sed adipiscing diam donec adipiscing tristique. Lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Donec massa sapien faucibus et molestie ac. Nunc sed velit dignissim sodales ut eu. Sit amet porttitor eget dolor morbi. Turpis massa sed elementum tempus egestas sed sed risus. Id aliquet lectus proin nibh nisl condimentum id venenatis. Vitae et leo duis ut diam quam nulla porttitor. Lorem sed risus ultricies tristique nulla aliquet enim tortor. Varius morbi enim nunc faucibus a. Accumsan sit amet nulla facilisi. Metus aliquam eleifend mi in nulla posuere. Ac tortor dignissim convallis aenean et tortor at risus viverra. Et ultrices neque ornare aenean. Est placerat in egestas erat imperdiet sed euismod. Imperdiet nulla malesuada pellentesque elit eget gravida. Sit amet nisl suscipit adipiscing bibendum. Ornare suspendisse sed nisi lacus sed viverra tellus. Quam viverra orci sagittis eu volutpat. Hendrerit dolor magna eget est. Amet commodo nulla facilisi nullam vehicula. Faucibus purus in massa tempor nec feugiat nisl pretium fusce. Et ultrices neque ornare aenean euismod elementum. Ullamcorper eget nulla facilisi etiam dignissim diam. Convallis tellus id interdum velit laoreet id donec. Lorem ipsum dolor sit amet. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Elementum facilisis leo vel fringilla est. Ut faucibus pulvinar elementum integer. Pretium vulputate sapien nec sagittis aliquam.

### Expected behavior

Comment should be posted

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
N/A
```

### Additional info

![screenshot_2022_03_08_at_17_19_59](https://user-images.githubusercontent.com/12234510/157280423-a2e5dc68-2fce-4d5f-ae65-53dc12f1b3a2.jpg)

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
