### ISSUE TITLE
`OC\Files\Storage\Local::calculateEtag()` Argument #2 ($stat) must be of type array, bool given

### ISSUE THREAD

**Issue by dhenry123** [nextcloud/server#31509]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Each time i tried to sync my phone client, i got an error 503 and the same with displaying activity in browser app.
In log i got : "OC\\Files\\Storage\\Local::calculateEtag(): Argument #2 ($stat) must be of type array, bool given, called in /var/www/html/lib/private/Files/Storage/Local.php on line 491 in file '/var/www/html/lib/private/Files/Storage/Local.php' line 494"

### Steps to reproduce

i dont know exactly why my server now, is in this context, may be, i had a problem with disk storage....

but you could try to put a new file with nextcloud, and delete it on final nextcloud storage (not by nextcloud) and try to display activity or folder which content this file (with nextcloud app).

The xhr /ocs/v2.php/apps/activity/api/v2/activity/all?format=json&previews=true&since=0 will send 503 error code

### Expected behavior

i will get http code 200 :)

### Installation method

Official Docker image

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - bruteforcesettings: 2.3.0
...
```

### Nextcloud Logs

```shell
{
[...]
"url": "/ocs/v2.php/apps/activity/api/v2/activity/all?format=json&previews=true&since=0",
"message": "OC\\Files\\Storage\\Local::calculateEtag(): Argument #2 ($stat) must be of type array, bool given, called in /var/www/html/lib/private/Files/Storage/Local.php on line 491 in file '/var/www/html/lib/private/Files/Storage/Local.php' line 494",
[...],
"version": "23.0.2.1",
[...],
}
```

### Additional info

to fix temporaly : 

file : /var/www/html/lib/private/Files/Storage/Local.php
Line : 490
        public function getETag($path) {
                $stat = $this->stat($path); //stat return array|false
                if (! $stat){ return "";}
                return $this->calculateEtag($path, $stat);
        }

**Comment by hvillemoes** [comment]
This case may be same problem in another environment: [https://help.nextcloud.com/t/display-activity-loops-forever/135875](https://help.nextcloud.com/t/display-activity-loops-forever/135875)

**Comment by AryehGielchinsky** [comment]
Same issue on my server running ubuntu server 22.04. I used the official docker compose to setup my server. Originally I was on 24.03 and then upgraded to 24.05 but the problem persists.

I can view the files but not download them from a web browser. I have one desktop  (ubunutu 20.04, nextcloud 3.54) that I am trying to sync for the first time that cannot sync the files, and another desktop  (same setup) that was previously synced, and was able to sync the files.

**Comment by AryehGielchinsky** [comment]
To fix the issue I un-synced the folder with the problematic files in it (by unchecking the folder) and then resynced that folder (by check marking the folder).

Pausing the overall sync and restarting didn't fix the issue.

This isn't a great solution as it doesn't work for files that are at the top level of the sync folder (which can't be un-synced).

**Comment by AryehGielchinsky** [comment]
> 2\. occ files:repair-tree

Thank you for the suggestions. As mentioned above I got my server working again by un-syncing and re-syncing the folders with the problematic files, but I'll try your method in the future.

I'm having trouble finding documentation on `occ files:repair-tree -vvv`, what does it do?

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
