### ISSUE TITLE
Static Web Assets available through Share Folder Path

### ISSUE THREAD

**Issue by joe-cole1** [nextcloud/server#31506]
I tried searching and apologize if this is a repeat.

I have a fairly robust access control to my server using Cloudflare Access to restrict access to specific users authenticated through other means (not nextcloud authentication) prior to even being able to reach my NextCloud site.

The problem I've run into is sharing public links.

I have an exception in place for public access to the share path (e.g. https://cloud.example.com/s/)

This, however, does not allow loading assets, so the CSS and whatever else does not load, leading the share page to look like this:

![image](https://user-images.githubusercontent.com/101269914/157463415-bcd69143-9f88-4f2b-9565-e61f62dab0fa.png)

An alternative I've seen is with Synology Photos, which will load asssets for public share through the same public share path.

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by joe-cole1** [comment]
> Thank you for taking the time to report a bug! 👍
> 
> As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

I'll post there, but it's not really a setup issue, as the functionality just doesn't exist right now. It would have to be a change in the code.

**Comment by greccode** [comment]
Closing this as a setup issue is wild.
