### ISSUE TITLE
doesn't detect php modules arch/php modules don't work

### ISSUE THREAD

**Issue by debian-user-france1** [nextcloud/server#31502]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nextcloud seems to not detect the modules php7-gd and php7-sqlite on ARCH with the default nginx configuration from the documentation. 

### Steps to reproduce

1. Install Manjaro Linux
2. Install nginx - port 444 with SSL
3. Install nextcloud
4. Install php with yay -S php7
5. Launch a php-server
6. Install all missing modules and restart your server

Somehow all  other php modules seem to be preinstalled that are required.

### Expected behavior

It works and continues the setup

I installed it using the Nextcloud Archive provided on Nextcloud.com

### Installation method

Manual installation

### Operating system

Other

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Nextcloud is not installed - only a limited number of commands are available
No database drivers (sqlite, mysql, or postgresql) installed.


PHP module GD not installed.
Please ask your server administrator to install the module.
```

### List of activated Apps

```shell
-
```

### Nextcloud Signing status

```shell
-
```

### Nextcloud Logs

```shell
-
```

### Additional info

I did not configure php yet but will do that now.

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by debian-user-france1** [comment]
I have a quiestion... How does Nextcloud check if the modules are available. Do you know that?
