### ISSUE TITLE
After update to nc 11.0.1: Webdav isnt working in single user mode

### ISSUE THREAD

**Issue by EasyPeasy1** [nextcloud/server#3153]
Hi

After the update to nc 11.0.1 i'll get this error:

`{"reqId":"2sxTDjO6080lzdf4ulTH","remoteAddr":"79.220.197.102","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 System in single user mode.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/nextcloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/nextcl...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":82,\"User\":\"mherborn\"}","level":4,"time":"2017-01-16T23:36:39+01:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"mherborn","version":"11.0.1.2"}
`

Is it a bug??

It's not possible to see any files if the single user mode is set to 'true'

How to reproduce:

Turn on the Single User mode and try to see any file

Operating System:
Ubuntu 16.04 LTS
Apache 2.4.18
PHP 7.0.8
NC 11.0.1

**Comment by nickvergessen** [comment]
Yeah single user mode is supposed to not allow everything, clients syncing is one of those things that are blocked intentionally.

**Comment by EasyPeasy1** [comment]
Shouldn't the admin be allowed to do everything if the single user mode is set to true
