### ISSUE TITLE
Do not recommend web updater on big installations

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#31533]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Web updater on big installations might run into time outs.

**Describe the solution you'd like**
Use CLI updater.

**Describe alternatives you've considered**
/

**Additional context**
When NC detects big installations (many users, many files, …?) then sysadmin should be urged to use CLI with a link how to do it.
Currently sysadmins might not be aware that the updater can run into timeouts.

---

Some related PRs that might be helpful:
https://github.com/nextcloud/server/pull/25689/files
https://github.com/nextcloud/updater/pull/331/files

--- 

https://github.com/nextcloud/server/blob/a06001e0851abc6073af678b742da3e1aa96eec9/lib/private/Support/Subscription/Registry.php#L187-L214

**Comment by PVince81** [comment]
disablings seems a bit hard, did you consider showing a big warning instead ?

**Comment by szaimen** [comment]
https://github.com/nextcloud/server/pull/31537 will only disable the link to the updater. The updater will still work.
