### ISSUE TITLE
Middle-Click copy-paste not working for share links

### ISSUE THREAD

**Issue by despens** [nextcloud/server#3154]
### Steps to reproduce
1. Share file or folder via link in files app ([x] Share link)
2. Mark input field with link url
3. Paste selection with middle mouse button in another window (for instance email, text editor)

### Expected behaviour
Share URL should be pasted

### Actual behaviour
Random part of the URL is pasted, from a few characters to an arbitrary section in the middle of the string.

### Server configuration
**Nextcloud version:** Nextcloud 11.0.1 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 11

**Where did you install Nextcloud from:** installed via tarball, updated via updater app

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

### Client configuration
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 *Firefox/50.0*

**Operating system:** Ubuntu 16.04 with GNOME Shell 3.18.5

### Logs

No log entries related to that interaction

**Comment by nickvergessen** [comment]
How do you mark the value in the input field? Are you using the small copy icon? Or do you just click in the field and then Ctrl+C? Anyway all of these methods work here with Firefox 50.1 on Ubuntu, so you need to provide more info

**Comment by despens** [comment]
I am using classic X11 middle-click paste. For that, you select mark a piece of text (hold main mouse button down at start of text and drag towards the end of the desired text; release mouse button, resulting in marked/selected text. Double-clicking to select words or whole input fields is also common.)

Selecting text, without any further interaction, usually copies it to the X11 clipboard. It can then be pasted with the middle mouse button into any widget that accepts text input.

Using Ctrl-C and Ctrl-V works as expected. But it seems nextcloud's share link field is doing something funny with the selection via javascript. :)

**Comment by nickvergessen** [comment]
@schiessle any idea?

**Comment by josch** [comment]
It seems that recent nextcloud releases don't display a textbox at all anymore. Now there is only a "Copy URL" button. While this "solved" the issue of this bug report it also made middle click copy/paste impossible. This is really frustrating if one doesn't have any application open where CTRL+V pasting works...

**Comment by despens** [comment]
I agree with @josch but probably this specific issue should be closed and a new one about the current interface should be opened.
