### ISSUE TITLE
[Bug]: Blank/White page on custom domain

### ISSUE THREAD

**Issue by RedVelocity** [nextcloud/server#31545]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I get a blank/white dashboard while accessing my nextcloud server through custom link(eg: nextcloud.example.com)
I've looked up this issue and tried playing around with the accessibility plugin but it hasn't helped. I've even went to lengths of re-installing the whole server but the issue persists.

Curiously, accessing the same server from my server IP works just fine!

Setup: Nextcloud v23.0.3 on Ubuntu LTS 20.04, Apache2 server with MariaDB

### Steps to reproduce

1. Login through nextcloud.example.com, the dashboard will be white/blank as shown below

<img width="960" alt="image" src="https://user-images.githubusercontent.com/14160702/157881776-a144b05d-abec-4fe8-afd7-b8b072032cae.png">

2. Same server while accessing from server IP

<img width="952" alt="image" src="https://user-images.githubusercontent.com/14160702/157882013-68c0086f-2e7e-4845-8ef8-efc03c82cf6e.png">

### Expected behavior

The Dashboard should be visible from both IP and custom domain

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Could not open input file: occ
```

### List of activated Apps

```shell
Could not open input file: occ
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Login failed: 'Redvelocity' (Remote IP:)
```

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
