### ISSUE TITLE
Wrong Logout URL with Apache Reverse proxy

### ISSUE THREAD

**Issue by jkalousek** [nextcloud/server#3155]
I have running instance of NextCloud 11.0.1 (stable) on Apache/2.4.18 (Ubuntu).
I can access this instance on IP 192.168.6.83. Now I want to access NextCloud from outside/Internet, I have Apache reverse proxy server. Everything is working OK (upload, download, apps etc.) except I can't logout from administration. 

Every menu item has correct URL:
**https**://subdomain.domain.net/...

But Logout button has:
**http**://subdomain.domain.net/index.php/logout...

So, when I click Logout button, it redirect me to non secure (http) version which is of course not accessible and I get 404 error.

It almost looks similar to: [https://github.com/owncloud/core/issues/17201](https://github.com/owncloud/core/issues/17201)

Is there setting that can influence Logout URL, or did I configure something wrong, or Is this bug?

Thanks in advance for looking at this problem.

**Comment by nickvergessen** [comment]
Please provide the information as asked by the issue template. Especially the configs

**Comment by jkalousek** [comment]
### Server configuration
**Operating system**:
UBUNTU 16.04.1 LTS (Xenial Xerus)"

**Web server:**
 Apache/2.4.18

**Database:**
mysql  Ver 14.14 Distrib 5.7.16, for Linux (x86_64) using  EditLine wrapper

**PHP version:**
PHP 7.0.13-0

**Nextcloud version:** (see Nextcloud admin page)
11.0.1 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install

**Where did you install Nextcloud from:**
Installed from official tar
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - calendar: 1.5.0
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - rainloop: 4.26.0
  - richdocuments: 1.1.25
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.4
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocrr96vg9j0c",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.6.83",
            "cloud.detesk.net"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/192.168.6.83\/",
        "dbtype": "mysql",
        "version": "11.0.1.2",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Comment by jkalousek** [comment]
# Apache Virtual Host (Proxy reverse)

`<VirtualHost *:443>
        ProxyRequests Off
        SSLProxyEngine On
        ProxyPreserveHost On
        <proxy *>
                Order deny,allow
                Allow from all
        </proxy>
        <Location />
                ProxyPassReverse /
                Order deny,allow
                Allow from all
        </Location>

        ProxyPass / http://192.168.6.83/
        ProxyPassReverse / http://192.168.6.83/
        SSLEngine on
        ServerAdmin ***REDACTED***
        ServerName ***REDACTED***.net
        SSLCertificateFile      /etc/letsencrypt/live/***REDACTED***.net/cert.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/***REDACTED***.net/privkey.pem
        SSLCertificateChainFile /etc/letsencrypt/live/***REDACTED***.net/fullchain.pem

</VirtualHost>
`

**Comment by nickvergessen** [comment]
In your config change `overwrite.cli.url` to
```php
"overwrite.cli.url": "https:\/\/***REDACTED***.net\/",
```

If that does not work, try the proxy settings in your config:
https://github.com/nextcloud/server/blob/61d4198ae1d5a0914e40be9985284298c2a9b750/config/config.sample.php#L384-L386

**Comment by jkalousek** [comment]
`'overwriteprotocol' => 'https',`
In config seems to do the trick, thank you. Sadly now I can't access NC from intranet (192.168.6.83), which makes sense but it would be good to know why is this happening only in case of Logout button but everything else works.

**Comment by hkahl** [comment]
Same problem here.

'overwriteprotocol' => 'https'  solves the one problem, but then I am not able to connect via http from intranet anymore.

**Comment by MorrisJobke** [comment]
Duplicate of #1075

**Comment by godfuture** [comment]
Why is this ticket a dup of https://github.com/nextcloud/server/issues/1075? 1075 is about CSRF check, This ticket is about...some kind of redirection problem?! Or does a failed CSRF check lead to this behaviour? If yes, isn't this then critical?

I have this issue since nc15. Logout falls back to http. Using nginx as reverse proxy. 
As others I don't like to let nc force me to https. As others I am interested in a solution that lets me connect without ssl internally.

Did someone find out what we need to do on the proxy to get nc going also for logout?

**Comment by karloluiten** [comment]
I have the same problem with my apache proxy since upgrade to 15. Let me know if I can provide logs.
