### ISSUE TITLE
UI to Manage Tags Featurerequest

### ISSUE THREAD

**Issue by MrLoverLoverMMMM** [nextcloud/server#31576]
Currently there is no way to manage all collaborative tags as an administrator.
It would be useful if tags could be deleted or edited from the list of all tags in the admin UI.

NV Server Version: 22.2.5 (latest stable)

**Comment by RegisPerdreau** [comment]
Yes, we need a CRUD for tags, it's a pain to manage them one to one.

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/issues/4842
