### ISSUE TITLE
[Bug]: Tags are still displayed in the explorer after deactivation

### ISSUE THREAD

**Issue by JordanDIG** [nextcloud/server#31583]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The "Tags" tab is always displayed even if the application is disabled.

### Steps to reproduce

1. Disable Collaborative tags app
2. Open the files application
3. Select an item

### Expected behavior

That the "Tags" tab is no longer displayed

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "knowledgebaseenabled": false,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "trashbin_retention_obligation": "auto",
        "default_language": "fr",
        "default_phone_region": "FR",
        "default_locale": "fr_FR",
        "defaultapp": "apporder",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            ""
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.2.1",
        "overwrite.cli.url",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "app_install_overwrite": [
            "apporder"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.15.0
  - apporder: 0.14.0
  - bruteforcesettings: 2.3.0
  - cloud_federation_api: 1.6.0
  - contacts: 4.0.8
  - dashboard: 7.3.0
  - dav: 1.21.0
  - deck: 1.6.1
  - extract: 1.3.3
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_downloadactivity: 1.12.0
  - files_external: 1.15.0
  - files_linkeditor: 1.1.8
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - fileslibreofficeedit: 1.0.4
  - group_default_quota: 0.1.3
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - metadata: 0.15.0
  - music: 1.5.1
  - nextcloud_announcements: 1.12.0
  - notes: 4.3.1
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - onlyoffice: 7.3.2
  - password_policy: 1.13.0
  - passwords: 2022.3.20
  - photos: 1.5.0
  - provisioning_api: 1.13.0
  - quota_warning: 1.13.1
  - rainloop: 7.1.3
  - ransomware_protection: 1.12.0
  - recommendations: 1.2.0
  - registration: 1.4.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - socialsharing_email: 2.4.0
  - text: 3.4.0
  - theming: 1.14.0
  - theming_customcss: 1.10.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_nextcloud_notification: 3.3.1
  - twofactor_totp: 6.2.0
  - twofactor_u2f: 6.3.0
  - updatenotification: 1.13.0
  - viewer: 1.7.0
  - welcome: 1.0.1
  - workflow_pdf_converter: 1.8.0
  - workflowengine: 2.5.0
Disabled:
  - accessibility: 1.9.0
  - admin_audit
  - circles: 22.1.1
  - comments: 1.13.0
  - contactsinteraction: 1.4.0
  - encryption
  - firstrunwizard: 2.12.0
  - privacy: 1.5.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - user_ldap
  - user_status: 1.1.1
  - weather_status: 1.3.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
No errors have been found.
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by JordanDIG** [comment]
Duplicate of #31315

**Comment by JordanDIG** [comment]
@szaimen What information do you need?

**Comment by szaimen** [comment]
I removed this label...

**Comment by JordanDIG** [comment]
This problem is also present in version 26 @szaimen

**Comment by skjnldsv** [comment]
Fixed 28 and above
(the [action](https://github.com/nextcloud/server/blob/afa48a4e0ed4515aec458db13a07e11a7e0f5981/apps/systemtags/src/actions/inlineSystemTagsAction.ts) is registered by the systemtags app now, disabling it stop loading the script)
