### ISSUE TITLE
[Bug]:  share link

### ISSUE THREAD

**Issue by rladelman771** [nextcloud/server#31599]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Share link missing in browsers, tried chrome, edge, Firefox. Share link shows in app on iOS, but gives error 404 requested resource could not be found. 

Running nextcloud 23.02 on truenas core 12u8

### Steps to reproduce

1. Restarting nextcloud in jail
2. 
3.

### Expected behavior

Share link to be there

### Installation method

Other

### Operating system

Other

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MySQL

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other

### Configuration report

```shell
.
```

### List of activated Apps

```shell
.
```

### Nextcloud Signing status

```shell
.
```

### Nextcloud Logs

```shell
.
```

### Additional info

.

**Comment by szaimen** [comment]
Do you have an ad blocker enabler?

**Comment by rladelman771** [comment]
Not on the edge browser, also no ad blocker via the app

Robert L. Adelman, DMD
Website: http://robertadelman.dentist
Water’s Edge Dental
1244 Wrights Lane
West Chester, PA 19380
Work: 610-696-6070
Mobile: 215-771-3427
Work Email: ***@***.***
Home Email: ***@***.***

Disclaimer:

This message may contain confidential information and is intended only for the individual(s) or entities named above. Any review, re-transmission, dissemination, distribution, copying or other use of this information by persons or entities other than the intended recipient is prohibited. Please notify the sender immediately by e-mail from any and all computers it may be stored on. No liability is accepted for any errors or omissions in the contents of this message which arise as a result of e-mail transmission. If verification is required, please request a hard-copy version. No liability is accepted for any damage caused by any virus transmitted by this e-mail. The recipient should check this e-mail and any attachments for the presence of viruses.

**Comment by rladelman771** [comment]
Figured it out. For some reason only on my iPad safari browser I was able to see the three dots and check to allow sharing on external storage. Once I did that it appeared in the browser and the 404 error went away. 

Robert L. Adelman, DMD
Website: http://robertadelman.dentist
Water’s Edge Dental
1244 Wrights Lane
West Chester, PA 19380
Work: 610-696-6070
Mobile: 215-771-3427
Work Email: ***@***.***
Home Email: ***@***.***

Disclaimer:

This message may contain confidential information and is intended only for the individual(s) or entities named above. Any review, re-transmission, dissemination, distribution, copying or other use of this information by persons or entities other than the intended recipient is prohibited. Please notify the sender immediately by e-mail from any and all computers it may be stored on. No liability is accepted for any errors or omissions in the contents of this message which arise as a result of e-mail transmission. If verification is required, please request a hard-copy version. No liability is accepted for any damage caused by any virus transmitted by this e-mail. The recipient should check this e-mail and any attachments for the presence of viruses.

**Comment by szaimen** [comment]
thanks
