### ISSUE TITLE
[Bug]: "Recently contacted" feature creates duplicates in Contacts

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#31606]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The "Recently contacted" feature adds duplicates there even if a user with that email address is already in contacts. This could possibly be if an instance uses a shared address book and yourself is not owner of that address book?

The "Recently contacted" mechanism needs to check if an address already exists in Contacts, in which case they should not create another entry, also in other address books you have (at least those which are enabled).

@ChristophWurst as mentioned

### Steps to reproduce

1. Send a mail to an email of a person you already have in contacts
2. Check in contacts, they will be twice in the "All contacts" list

### Expected behavior

No duplicates should be created. :)

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
This is on our `cloud.nc.com` instance
```

### List of activated Apps

```shell
This is on our `cloud.nc.com` instance
```

**Comment by ChristophWurst** [comment]
Caused by https://github.com/nextcloud/server/tree/master/apps/contactsinteraction
