### ISSUE TITLE
[Bug]: Accessibility: High Contrast theme does not apply to all icons in app list

### ISSUE THREAD

**Issue by rexbron** [nextcloud/server#31604]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![image](https://user-images.githubusercontent.com/587341/158808343-b7b14b90-e6cf-41df-968c-7ec25ade6407.png)

When high contrast is selected, not all icons have their opacity changed to 1 to increase the contrast. 

This is also true with the dark theme enabled:

![image](https://user-images.githubusercontent.com/587341/158808644-6d0abf3b-c290-4698-9c68-3ca6aa2b52e1.png)

### Steps to reproduce

1. Enable High Contrast theme
2. Navigate to apps list
3. Observe the inconsistency in icon presentation

### Expected behavior

Icons should be high contrast

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - bruteforcesettings: 2.3.0
  - calendar: 3.2.2
  - circles: 22.2.0
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.8
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.20.0
  - documentserver_community: 0.1.12
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_external: 1.13.1
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - groupfolders: 10.0.2
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - maps: 0.1.10
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - onlyoffice: 7.3.2
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - spreed: 12.2.3
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - tasks: 0.14.2
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - encryption
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by moosavisa** [comment]
Hi Nextcloud developers 

I wasn't sure this issue be reported in here or not. But when in windows 10 the "high contrast" option is enabled there are some more issues with icons. I mean after enabling "Dark them" and "High contrast mode" in next cloud plus "Windows 10 High contrast mode" in same time there are some more icons which are not displayed properly.

As an example, here in this screen shot both options are enabled but the check mark is not displayed.
![image](https://user-images.githubusercontent.com/105066435/167165093-ae5db578-0f88-4113-8e28-262fc6f42135.png)

Best Regards

**Comment by moosavisa** [comment]
Version 24.0.0

**Comment by szaimen** [comment]
Hi, please update to 25.0.7 or better 26.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 26-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
