### ISSUE TITLE
Allow admins to install beta releases of apps

### ISSUE THREAD

**Issue by max65482** [nextcloud/server#31611]
**Is your feature request related to a problem? Please describe.**
Beta versions of apps must be installed via CLI. There is no way to do this via web UI.

**Describe the solution you'd like**
Admins can install beta versions and release candidates via web UI. It is impossible to downgrade back from the beta version ("the only way is up").

**Describe alternatives you've considered**
As discussed in #31588, downgrading may lead to inconsistencies and security vulnerabilities.

**Comment by max65482** [comment]
Let me kick off the design discussion:

![grafik](https://user-images.githubusercontent.com/56191773/158854276-5cfb9c36-b750-45ec-b9a0-fb2ac61fe846.png)

@jancborchardt @nimishavijay

**Comment by jancborchardt** [comment]
Seems good to allow for testing, yes. Howeber to avoid the primary action being something we don't advise, I'd still say let's put it in a 3-dot menu next to the "Disable" button.

There we can also state the info that downgrading might be an issue, thanks for helping testing, please report issues if you find any, etc.

**Comment by max65482** [comment]
Maybe

![grafik](https://user-images.githubusercontent.com/56191773/158995780-0af32720-ed44-4fac-89d8-dc9181739efc.png)

**Comment by max65482** [comment]
And shall we show the dots even if there is no beta release available?

**Comment by max65482** [comment]
For clarification: What versions shall be offered? Betas? RCs?
Can I simply match version strings ('-rc', '-beta')?

**Comment by max65482** [comment]
I'm starting to wonder if this feature is even needed. Admins can select the beta update channel which also influences the app updates:

![grafik](https://user-images.githubusercontent.com/56191773/159168820-4d58a304-8cef-49ef-8353-ede7c3ad8874.png)

Implementation for apps is here:
https://github.com/nextcloud/server/blob/d0b3e7c4720a82e5f49f84bed91954f124513d4e/lib/private/App/AppStore/Fetcher/AppFetcher.php#L93-L94

**Comment by szaimen** [comment]
Hey, thanks for investigating this! 
I still think it makes sense to allow to install beta versions from the app store with a dedicated button for each of those because on some instances is the updatenotifications app disabled and thus no way to change the channel using the UI. Also, it is not really expected in my opinion, that this setting also influences which updates get offered in the app store. I get why it was implemented that way (much less engineering effort) but I think it is better from a UX perspective to be able to choose to upgrade to a beta version from the apps page directly.

What do you think @jancborchardt ?

**Comment by jancborchardt** [comment]
> I'm starting to wonder if this feature is even needed. Admins can select the beta update channel which also influences the app updates. This already allows the installation of beta versions.

I’d agree with you @max65482 – if app betas are already used when you are in the beta channel, then you can have a test setup, and that’s fine – doesn’t overcomplicate things and you have 1 place where you can say "sign me up for possible breakage". Closing then :)

**Comment by kescherCode** [comment]
Yeah this issue should probably be re-opened. I want to remain on stable versions of Nextcloud, but use beta versions of some specific apps.

**Comment by kescherCode** [comment]
I'm aware that one can switch the channel to achieve this, but that's clunky. Instead, I'd like to switch the channel per-app, ideally.
