### ISSUE TITLE
Increase the loglevel of errors reported when parsing calendar subscriptions

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/server#31612]
Needs to go from `debug` to `warning` or `info`.

https://github.com/nextcloud/server/blob/6b4ab04a4461ebfb3ee175d2f824a63e95ba021a/apps/dav/lib/CalDAV/WebcalCaching/RefreshWebcalService.php#L255

https://github.com/nextcloud/server/blob/6b4ab04a4461ebfb3ee175d2f824a63e95ba021a/apps/dav/lib/CalDAV/WebcalCaching/RefreshWebcalService.php#L265

https://github.com/nextcloud/server/blob/6b4ab04a4461ebfb3ee175d2f824a63e95ba021a/apps/dav/lib/CalDAV/WebcalCaching/RefreshWebcalService.php#L276

_Originally posted by @thewavelength in https://github.com/nextcloud/calendar/issues/2146#issuecomment-1067166720_

**Comment by KlokMiraj** [comment]
Hello @tcitworld 
I'd like to work on this issue. Is it closed yet?

**Comment by tcitworld** [comment]
Unfortunately I've already taken care of it in https://github.com/nextcloud/server/pull/31622, as there's a few issues related to it.

**Comment by KlokMiraj** [comment]
Thank you 
I'll see some other open issues
