### ISSUE TITLE
[Bug]: The storage quota is counting against my local VM (25gb) only and not against my external s3 (250 gb) storage.  Also media does not play videos

### ISSUE THREAD

**Issue by Farhan-CSE** [nextcloud/server#31630]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I am not being able to merge my VM local storage (25gb) with my external linode s3 storage (250 gb) , my total space is shown 25 gb in the nextcloud UI and the user quotas are also counted against 25 gb. How can I utilise my external storage to increase the primary storage and how can I add storage quota.

### Steps to reproduce

1. Mounted external storage and then
2. Set users to have a minimum of 5 gb storage upload limit
3. only to see it is being counted against local storage (25gb) and notifying that storage is full after a point.
4. The external storage is not being counted here
5. Also I made object storage as primary storage, only to see that my objects get corrupted and is irreversible to recover them with (uid) given to them and still local storage (25gb) is being counted as storage quota for users
6. Also video is not working - ( only audio works sometimes, sometimes video works, sometimes it doesn't all being the same format mp4) 

### Expected behavior

storage quota should be counted against external storage too. External storage should be able to merge with local storage to be one big data directory- drive.

Also video player has problem - doesn't work properly 

### Installation method

Official All-in-One appliance

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.3

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
- accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - calendar: 3.0.5
  - circles: 23.0.0
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.0.7
  - contactsinteraction: 1.4.0
  - dav: 1.21.0
  - documentserver_community: 0.1.12
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_accesscontrol: 1.13.0
  - files_automatedtagging: 1.13.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - groupfolders: 11.1.2
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - maps: 0.1.10
  - metadata: 0.15.0
  - notifications: 2.11.1
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - systemtags: 1.13.0
  - text: 3.4.0
  - theming: 1.14.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - files_external
  - dashboard
Disabled:
  - encryption
  - nextcloud_announcements
  - user_ldap
```

**Comment by solracsf** [comment]
This is not a bug, please reach https://help.nextcloud.com with your setup question. Thanks for understanding 👍
