### ISSUE TITLE
[Bug]: Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "xyz.xyz.index" as such route does not exist.

### ISSUE THREAD

**Issue by brianjmurrell** [nextcloud/server#31631]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I am seeing lots of errors of the form:

```
{
   "time" : "2022-03-19T18:40:25+00:00",
   "version" : "23.0.2.1",
   "userAgent" : "gvfs/1.48.1",
   "message" : "{\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\RouteNotFoundException\",\"Message\":\"Unable to generate a URL for the named route \\\"photos.page.index\\\" as such route does not exist.\",\"Code\":0,\"Trace\":[{\"file\":\"/usr/share/nextcloud/lib/private/Route/Router.php\",\"line\":365,\"function\":\"generate\",\"class\":\"Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator\",\"type\":\"->\",\"args\":[\"photos.page.index\",[],1]},{\"file\":\"/usr/share/nextcloud/lib/private/URLGenerator.php\",\"line\":91,\"function\":\"generate\",\"class\":\"OC\\\\Route\\\\Router\",\"type\":\"->\",\"args\":[\"photos.page.index\",[]]},{\"file\":\"/usr/share/nextcloud/lib/private/NavigationManager.php\",\"line\":287,\"function\":\"linkToRoute\",\"class\":\"OC\\\\URLGenerator\",\"type\":\"->\",\"args\":[\"photos.page.index\"]},{\"file\":\"/usr/share/nextcloud/lib/private/NavigationManager.php\",\"line\":113,\"function\":\"init\",\"class\":\"OC\\\\NavigationMan
 ager\",\"type\":\"->\",\"args\":[]},{\"file\":\"/usr/share/nextcloud/apps/theming/lib/ThemingDefaults.php\",\"line\":194,\"function\":\"getAll\",\"class\":\"OC\\\\NavigationManager\",\"type\":\"->\",\"args\":[\"guest\"]},{\"file\":\"/usr/share/nextcloud/lib/private/legacy/OC_Defaults.php\",\"line\":280,\"function\":\"getShortFooter\",\"class\":\"OCA\\\\Theming\\\\ThemingDefaults\",\"type\":\"->\",\"args\":[]},{\"file\":\"/usr/share/nextcloud/lib/public/Defaults.php\",\"line\":177,\"function\":\"getLongFooter\",\"class\":\"OC_Defaults\",\"type\":\"->\",\"args\":[]},{\"file\":\"/usr/share/nextcloud/core/templates/layout.guest.php\",\"line\":55,\"function\":\"getLongFooter\",\"class\":\"OCP\\\\Defaults\",\"type\":\"->\",\"args\":[]},{\"file\":\"/usr/share/nextcloud/lib/private/Template/Base.php\",\"line\":180,\"args\":[\"/usr/share/nextcloud/core/templates/layout.guest.php\"],\"function\":\"include\"},{\"file\":\"/usr/share/nextcloud/lib/private/Template/Base.php\",\"line\":150,\"funct
 ion\":\"load\",\"class\":\"OC\\\\Template\\\\Base\",\"type\":\"->\",\"args\":[\"/usr/share/nextcloud/core/templates/layout.guest.php\",null]},{\"file\":\"/usr/share/nextcloud/lib/private/legacy/OC_Template.php\",\"line\":179,\"function\":\"fetchPage\",\"class\":\"OC\\\\Template\\\\Base\",\"type\":\"->\",\"args\":[null]},{\"file\":\"/usr/share/nextcloud/lib/private/legacy/OC_Template.php\",\"line\":210,\"function\":\"fetchPage\",\"class\":\"OC_Template\",\"type\":\"->\",\"args\":[null]},{\"file\":\"/usr/share/nextcloud/lib/private/Template/Base.php\",\"line\":132,\"function\":\"fetchPage\",\"class\":\"OC_Template\",\"type\":\"->\",\"args\":[]},{\"file\":\"/usr/share/nextcloud/lib/private/legacy/OC_Template.php\",\"line\":298,\"function\":\"printPage\",\"class\":\"OC\\\\Template\\\\Base\",\"type\":\"->\",\"args\":[]},{\"file\":\"/usr/share/nextcloud/remote.php\",\"line\":83,\"function\":\"printErrorPage\",\"class\":\"OC_Template\",\"type\":\"::\",\"args\":[\"Path not found\",\"\",404]
 },{\"file\":\"/usr/share/nextcloud/remote.php\",\"line\":168,\"function\":\"handleException\",\"args\":[{\"__class__\":\"RemoteException\"}]}],\"File\":\"/usr/share/nextcloud/3rdparty/symfony/routing/Generator/UrlGenerator.php\",\"Line\":143,\"CustomMessage\":\"--\"}",
   "app" : "no app in context",
   "reqId" : "YjYje6uIPH8RFhjKvRdP9gAAAJA",
   "remoteAddr" : "10.75.22.184",
   "level" : 1,
   "method" : "OPTIONS",
   "url" : "/remote.php/",
   "user" : "[redacted]"
}
```

This seems to have been [reported many many times in the past](https://www.google.com/search?q=nextcloud+%22Unable+to+generate+a+URL+for+the+named+route%22&oq=nextcloud+%22Unable+to+generate+a+URL+for+the+named+route%22&aqs=chrome.0.69i59j0i22i30l2.2598j0j7&sourceid=chrome&ie=UTF-8) and there was even a [PR landed](https://github.com/nextcloud/server/pull/21993) at some time to supposedly lower the error level but is `INFO` really appropriate for this message?

### Steps to reproduce

[Guessing]
1. Install nextcloud 23.0.2
2. Connect to it with GNOME Online Accounts and enable Files

### Expected behavior

This message should not be logged if there is nothing the user/admin is expected to do about them.

### Installation method

Other

### PHP engine version

PHP 7.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Request if necessary.  Last attempt resulted in Github complaining:

"Comment too long"

Which could not even be edited to fit.  I had to start a new issue and copy and paste to it so not risking having that happen again.
```

### List of activated Apps

```shell
Request if necessary.  Last attempt resulted in Github complaining:

"Comment too long"

Which could not even be edited to fit.  I had to start a new issue and copy and paste to it so not risking having that happen again.
```

### Nextcloud Signing status

```shell
Request if necessary.  Last attempt resulted in Github complaining:

"Comment too long"

Which could not even be edited to fit.  I had to start a new issue and copy and paste to it so not risking having that happen again.
```

### Nextcloud Logs

```shell
Request if necessary.  Last attempt resulted in Github complaining:

"Comment too long"

Which could not even be edited to fit.  I had to start a new issue and copy and paste to it so not risking having that happen again.
```

### Additional info

It's really frustrating to fill out your very long bug report form only to have GitHub refuse it due to it being too long, and then not even just being able to trim it to fit.  The only option is to abandon the issue and start from scratch.

That's really going to make people not want to provide the necessary information up front due to the waste of time it is to have to restart issues from scratch.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
