### ISSUE TITLE
Can't upload files with windows [Operation cancelled]

### ISSUE THREAD

**Issue by notaduck** [nextcloud/server#3164]
I recently reinstalled Nextcloud 11.0.1 on a new server. But I'm having some trouble with uploading files to it.....  
Everything wen't flawless while uploading files with the linux client, but then I ad to sync some files from a windows machine and I'm getting the error `Operation canceled` for a big bunch of files. I'm not really sure what to do here?

Client log : https://hastebin.com/ixawotekok.php  
                 https://hastebin.com/raw/ixawotekok Plain white paper

Server information: 
      `OS - Ubuntu 16.04 LTS`

     $sudo -u www-data php occ status
      - installed: true
      - version: 11.0.1.2
      - versionstring: 11.0.1
      - edition:

  
    $apache2 -v
    Server version: Apache/2.4.18 (Ubuntu)
    Server built:   2016-07-14T12:32:26

     php -v
    PHP 7.0.13-0ubuntu0.16.04.1 (cli) ( NTS )
    Copyright (c) 1997-2016 The PHP Group
    Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
        with Zend OPcache v7.0.13-0ubuntu0.16.04.1, Copyright (c) 1999-2016, by Zend Technologies

**Comment by nickvergessen** [comment]
Anything in your server and nextcloud log?

**Comment by notaduck** [comment]
Here is a full paste of the log.

http://pastebin.com/Q80tSwmZ

**Comment by zishbu** [comment]
I have this same issue with 11 all the versions and now even with the beta.

"Operation canceled" "Unable to write"

My Nextcloud forum getting no traction, but growing increasingly frustrated :(

https://help.nextcloud.com/t/unable-to-write-operation-cancelled/11537

Any ideas?
I tried changing the temp upload directory and am happy to provide any log needed.

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
