### ISSUE TITLE
[Bug]: Theme colors not applied to 'Login with a device' and 'Register' button

### ISSUE THREAD

**Issue by misterredwood** [nextcloud/server#31657]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After updating to Nextcloud version 23 the buttons for 'Log in with a device' and 'Register' are shown in blue instead of the theme color red set in Settings > Theming
![nextcloud23_login](https://user-images.githubusercontent.com/102147692/159450890-a7a78071-e397-4b74-9bca-e16c6e0e0d35.jpg)
.

### Steps to reproduce

1. Update from Nextcloud 22.x to Nextcloud 23.x
2. Visit the login page
3.

### Expected behavior

The buttons 'Login with device' and 'Register' should have the color set in the theme settings.

### Installation method

Manual installation

### Operating system

RHEL/CentOS

### PHP engine version

PHP 7.3

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
- accessibility: 1.9.0                                                                                                                                                            [14/1721]
  - activity: 2.15.0
  - bruteforcesettings: 2.3.0
  - calendar: 3.2.2
  - circles: 23.1.0
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - deck: 1.6.1
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_markdown: 2.3.5
  - files_mindmap: 0.0.26
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - fulltextsearch: 23.0.0
  - group_everyone: 0.1.9
  - groupfolders: 11.1.2
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notes: 4.3.1
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - polls: 3.4.2
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - registration: 1.4.0
  - richdocuments: 5.0.3
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.1
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.2.0
  - twofactor_u2f: 6.3.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
```

**Comment by p00rt** [comment]
I'm experiencing the same on a docker install of 23.0.1-fpm.
related: https://github.com/nextcloud/registration/issues/347
seems like it might not get fixed until branch 24.x.x

**Comment by ressit** [comment]
After upgrade from R23.0.12 to R24.0.9 the issue seems to be still present.
The workaround from https://github.com/nextcloud/registration/issues/347#issuecomment-1147334529 needs to be modified.

My personal CSS expert suggests to add the following lines in the nextcloud "custom css" app:

```
/* fix login screen register button color and hover */
.alternative-logins a.button,
#alternative-logins.alternative-logins .button.register-button {
  background-color: #150080 !important;
  color: var(--color-primary-text) !important;
  border: 1px solid gray;
} 

.alternative-logins .button:focus, 
.alternative-logins .button:hover{
  background-image: linear-gradient(40deg, #150080 0%, #2600e6 100%%);
}

```
The linear-gradient starts with your background-color at 0%.
The background-color at 100% could be calculated using the nice calculator from
https://hslpicker.com/
Enter your background-color value and add 20 to the saturation (3. row from top).

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by misterredwood** [comment]
Hi, I updated to Nextcloud 25.0.3 and with the new login page design the color is now applied to the register button. I did not make any modifications, e.g. changing the css,

**Comment by szaimen** [comment]
Thanks for verifying!
