### ISSUE TITLE
Allowed upgrade/migration check is inaccurate

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#3165]
We are going to run in a problem very soon. OC increased their next version to 10.0(OC), so far all good and expected. However this 10.0(OC) version is more like our 12.0(NC).
In fact currently you can run the update from 10.0(OC) to 10.0(NC)~9.1(OC), which should of course not be allowed.

So we need to increase the vendor sensitivity on this things. Instead of trusting the version and then comparing the vendor in case someone wants to do a downgrade, we must **first** compare the vendor and then check the version. For NC versions this will remain the "last major" for now,  but for OC we need to make new and different restrictions.

My plan would be the following:

Version | Allowed NC | Allowed OC
--------|------------|-----------
NC 9 | 9 | 8.2, 9.0
NC 10 | 9, 10 | 9.0, 9.1
NC 11 | 10, 11 | 9.1
NC 12 | 11, 12 | 10.0

Everyone okay with this?
cc @LukasReschke @MorrisJobke @karlitschek @schiessle 

Also fyi @oparoz

**Comment by karlitschek** [comment]
yes. this makes sense!

**Comment by MorrisJobke** [comment]
I'm also more and more concerned that we will more likely run into issues while we are diverging. 🙈
