### ISSUE TITLE
[Bug]: Deleted users are shown as `undefined` in file comments

### ISSUE THREAD

**Issue by Pytal** [nextcloud/server#31654]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

File comments by deleted users are shown as undefined

### Steps to reproduce

1. Add a file comment as user Tim
2. Go to Users page and delete Tim
3. Open file comments

### Expected behavior

Something like "Deleted user" should be shown instead of undefined

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
N/A
```

### List of activated Apps

```shell
N/A
```

**Comment by solracsf** [comment]
@Pytal shouldn't this be handled directly at https://github.com/nextcloud/nextcloud-auth/blob/master/lib/user.ts ?

**Comment by Pytal** [comment]
> @Pytal shouldn't this be handled directly at [https://github.com/nextcloud/nextcloud-auth/blob/master/lib/user.ts](https://github.com/nextcloud/nextcloud-auth/blob/master/lib/user.ts?rgh-link-date=2022-03-22T08%3A31%3A18Z) ?

As the comments app is in this repo then I think this is a good place, if the issue is to be fixed upstream in https://github.com/nextcloud/nextcloud-auth then we can close this when the fix gets in

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
