### ISSUE TITLE
Ability to use # character to help reference any linkable object on the Nextcloud instance

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#31667]
**Just like @ works for people and : for emojis, # would work for objects**

Similar to Twitter hashtags and GitHub reference to issues / pull requests, `#` would help reference objects of any type in the Nextcloud instance. It could be used in apps like Talk and Text, but also elsewhere. It would essentially be a little quick search-in-place to help quickly post links/references.

It’s probably best to do it as Twitter does it, because in their implementation you can still just type a number like `#1` (referring to "number 1") normally, while the suggestion dropdown shows as soon as you type the first alphabetic character after the `#`.

Twitter | GitHub
-|-
![Hashtag Twitter](https://user-images.githubusercontent.com/925062/159505760-aec727c7-ad57-488e-9e78-c76ceeec7a99.gif)|![Hashtag Github](https://user-images.githubusercontent.com/925062/159505754-4c0d29aa-9914-4bf9-9f7a-56da9fc496b1.gif)

Objects which could be referenced are
- Files & folders
- Talk conversations
- Deck cards or Tasks
- Calendar events
- Collectives pages
- Profiles
- Systemtags?
- …

References from this can also count towards being a related resource https://github.com/nextcloud/server/issues/28320

cc @marcelklehr @sunjam @nickvergessen @max-nextcloud @nimishavijay @marcoambrosini @juliushaertl @gretad as discussed in the design call.

Also cc @andyscherzinger @karlitschek and @PVince81 @ChristophWurst since this is all about cross-app integration.

**Comment by sunjam** [comment]
Other maybes...

- _Add to_ Project
- Bookmarks
- Comments (on files & folders) visibility
- Perhaps supported Nextcloud Flows could be called from this.

Might by completely out of scope, but this would also make for an awesome way to quickly share with others if it was possible to share by referencing a:
- circle
- group
- user

I'm think of how mentioning a github issue causes the original issue to also have a link (to where it is being mentioned and by whom)

**Comment by ChristophWurst** [comment]
The implementation would be similar to the unified search. Each app that wants to hook into this needs to register this capability and when the user searches we need to ask all n apps for their results.

**Comment by nickvergessen** [comment]
the main question would be how to store the data afterwards as well.

Not sure it is satisfying if we store the resulting link afterwards in the text message, or if possible instead we find a way to map it to [RichObjects](https://github.com/nextcloud/server/blob/master/lib/public/RichObjectStrings/Definitions.php) so "clients"/consumers of the API can render the items afterwards, showing potentially changed names/previews etc for the items.

**Comment by Spartachetto** [comment]
First of all the idea is really cool!

Second, for your consideration: what about a character to reference  **tags** ?

I put this question here as:
1. It could be useful to have a comprehensive discussion 
2. You could pick in advance the most intuitive characters, as often the # is for referencing tags (at least in twitter)

**Comment by nickvergessen** [comment]
We can not have a character per object, tags are one object and they need to live under the same control character as well.

**Comment by karlitschek** [comment]
really good idea!!

**Comment by Spartachetto** [comment]
@nickvergessen , thanks for considering my proposal

**Comment by Spartachetto** [comment]
If you follow the syntax suggested by @nickvergessen , you could have a "default" object type that can be omitted. 

What would be the default type is up to consideration. I'd think that files are too much to put them as the default. 
Maybe tags...? :grin:

**Comment by max-nextcloud** [comment]
> Default is "user" as already used across comments in all kind of apps

Default is user when starting with a `@` - but i think @Spartachetto was proposing a default for starting with a `#`. One problem there might be that the default could not contain `/` in order to enable this. I just checked and tags can contain slashes.

However I'm not sure if the default even matters for objects... wouldn't we just have an autocomplete that lists all things matching the typed chars? Similar to unified search as @ChristophWurst pointed out.

**Comment by nickvergessen** [comment]
> One problem there might be that the default could not contain / in order to enable this. I just checked and tags can contain slashes.

I still think we should use `@` and then make it quoted like we do in talk. If you mention a guest, we insert `@"guests/sessionid"`. Basically we can split on the first slash and then have the type and the identifier. For tags that could then be the ID as well and the data is translated on rendering then to show the actual tag name that has any characters.

**Comment by juliushaertl** [comment]
Just leaving this here for later, once implementing the autocompletion this can be based on the reference rendering work that has been done with #33494 which currently matches http/https links but could be reused to match any `#hashreference` or `@reference` in a text.

**Comment by juliushaertl** [comment]
- [ ] Come up with a UX/UI spec for the insertion/search (similar to `/` on notion/confluence)

**Comment by juliushaertl** [comment]
@jancborchardt @nimishavijay Could you mabye come up with some UI mockups about how this autocompletion should behave for different examples like:

- Insert a file
- Insert a deck card
- Insert a github ticket
- Insert a calendar events
- Insert a link to a profile

From the previous discussion i think we should mostly stick to how notion does it and avoid directly searching due to performance reasons, but it would be good to have some spec available from the UI side.

**Comment by jancborchardt** [comment]
@juliushaertl btw, since Notion and Confluence (and Slack) use `/` we should probably do the same.

And interaction-wise, I agree we should stay pretty close to them.

So to be light on performance and do it similar to Notion, when you put in a slash, it would show a list like the emoji inserter, just with the list you posted above? And then when you type more it could start searching?

Let me know what the technical possibilities and restrictions are, maybe a call is better to spec this out.

**Comment by juliushaertl** [comment]
@julien-nc A few things we chatted about but also some more things to keep in mind:

- Actual implementations of reference autocomplete/picker still needs discussion with designers (e.g. for GitHub a proper search/autocomplete might be hard)
- We need to implement this autocomplete mechanism in text but also https://nextcloud-vue-components.netlify.app/#/Components/NcRichContenteditable

**Comment by juliushaertl** [comment]
From the discussion with @julien-nc

## UI flow

- UI User enters `/`
	- First level picker is shown for the reference provider type
	- After picking that the individual picker 
		- If registered: Custom UI with registering a vue componentn for the reference provider picker
			- e.g. for files, potentially github/gitlab
		- If available: Search through unified search (backend of reference providers would need to expose supported search providers)
			- Same layout as unified search UI
		- Default: Text input for URL

## Implementation details
- Require a reference provider to be able to search and autocomplete, as without a rendering, inserting doesn't make much sense
- Server: Add new interface to let reference providers return a list of supported search provider ids
- Server: We need to pass registered reference providers and search handlers from the backend to the frontend
- No automatic matching for search providers
- Text/talk input component
	- on type / render the vue-richtext PickerComponent
- vue-richtext
	- Used for registering custom picker views
	- Implements the PickerComponent which emits an event to text/talk input once the reference was selected
- Possible design discussions:
	- Search results may have different title/description than what the reference provdider will show then actually. 
- Implementation steps:
	- Server: Implement the new interface for returning serach provider ids in the reference provider
	- PickerComponent: Implement picker component with input field + search results
	- Text: Implement `/`command and triger the picker component
	- vue-richtext: API to register custom picker view for reference providers and render them in the PickerComponent
	- nextcloud-vue: Implement `/`command in the -   [NcRichContenteditable](https://nextcloud-vue-components.netlify.app/#/Components/NcRichContenteditable) component
	- Talk: Switch to the -   [NcRichContenteditable](https://nextcloud-vue-components.netlify.app/#/Components/NcRichContenteditable) component for the message input

**Comment by nickvergessen** [comment]
Since in talk we use `/` for commands (and that is expected pattern across many chat platforms), is there a way to have that either suggest commands as well, or at least display something telling users that commands also work, etc?
It's only relevant on the first character of a message as commands are the full message.

**Comment by juliushaertl** [comment]
Right, might be something to then discuss with @nimishavijay and @jancborchardt if we should settle on a different character (like `#`)

**Comment by AndyScherzinger** [comment]
@ChristophWurst could you please check with @julien-nc if there is an "easy" way to integrate the link-picker component in mail? Potentially in a stripped down way to limit it to features that work for mail? Thanks in advance.

**Comment by juliushaertl** [comment]
Closing as the server related topics are finished

**Comment by ChristophWurst** [comment]
> @ChristophWurst could you please check with @julien-nc if there is an "easy" way to integrate the link-picker component in mail? Potentially in a stripped down way to limit it to features that work for mail? Thanks in advance.

https://github.com/nextcloud/mail/issues/7986. Sorry, somehow missed the comment here.
