### ISSUE TITLE
[Bug]: Select All Checkbox Targets Hidden Files/Folders

### ISSUE THREAD

**Issue by arcanefeenix** [nextcloud/server#31671]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When working with a share with hidden files or folders, if you use the top-most checkbox to "select all" and perform an action such as "Delete," the hidden files/folders are also targeted. 

### Steps to reproduce

1. Have a share within Nextcloud
2. Inside the share, create a hidden file or folder along with normal files.
3. Use the top-most checkbox to select all and perform an action such as Delete.

### Expected behavior

I would expect that the checkbox would only target files that are listed and visible to the user, not hidden files that they cannot see. If I were to select all on a macOS system and delete the files, it would not target and delete any hidden files such as a `.DS_Store` file. Doing the same on Windows, it wouldn't delete any hidden files such as pagefile.sys (unless the hidden files are being shown). Nextcloud is not showing the hidden files so they should not be targeted.

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "simpleSignUpLink.shown": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "dev.cloudvault.inveniem.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.2.1",
        "overwrite.cli.url": "https:\/\/dev.cloudvault.inveniem.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "appstoreenabled": false,
        "enable_previews": true,
        "preview_max_filesize_image": 50,
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": false
            }
        ],
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": 1,
        "filelocking.enabled": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "6379",
            "timeout": 1.5,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "dbdriveroptions": {
            "1009": "\/etc\/ssl\/certs\/Baltimore_CyberTrust_Root.pem"
        },
        "config_is_read_only": true,
        "skeletondirectory": "",
        "mysql.utf8mb4": true,
        "preview_max_x": 1024,
        "preview_max_y": 1024,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "user_external",
            "user_saml"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - checksum: 1.1.3
  - circles: 23.0.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contactsinteraction: 1.4.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_downloadactivity: 1.12.0
  - files_external: 1.15.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - metadata: 0.15.0
  - music: 1.5.1
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_external: 2.1.0
  - user_saml: 4.1.1
  - viewer: 1.7.0
  - workflowengine: 2.5.0
Disabled:
  - dashboard: 7.0.0
  - encryption
  - files_antivirus: 2.4.1
  - files_automatedtagging
  - firstrunwizard: 2.4.0
  - previewgenerator
  - user_ldap
  - user_status: 1.0.1
  - weather_status: 1.0.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
N/A (container logs)
```

**Comment by Bonnee** [comment]
This also applies when I search inside a folder. If I use the "select all" checkbox, all files gets selected instead of only the search results. I've just lost a couple GBs because of this bug.
