### ISSUE TITLE
occ files:scan reports error "Implicit conversion from float XXX to int loses precision"

### ISSUE THREAD

**Issue by spicemint** [nextcloud/server#31692]
Linux archlinux 5.16.11-arch1-1, nextcloud 23.0.2, nginx/1.20.2, PHP 8.1.3, mariadb 10.7.3, preview generator 4.0.0
Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz (12 cores), 24GB RAM

command:
sudo -u nextcloud /usr/bin/php /usr/share/webapps/nextcloud/occ files:scan --all

should result in completing scan for all users without errors but runs into following issue:

sudo -u nextcloud /usr/bin/php /usr/share/webapps/nextcloud/occ files:scan --all
Starting scan for user 1 out of 3 (joe)
Starting scan for user 2 out of 3 (david)
Starting scan for user 3 out of 3 (herb)

In Scan.php line 293:

  Implicit conversion from float 39.31666666666667 to int loses precision

**Comment by cld4h** [comment]
https://github.com/nextcloud/server/blob/dd736fa1da93a2cb65611cefa209da703f263775/apps/files/lib/Command/Scan.php#L294

```php
return sprintf('%02d:%02d:%02d', (int)($secs / 3600), ((int)($secs / 60) % 60), $secs % 60);
```
