### ISSUE TITLE
[Bug]: System tags workflows not working anymore

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#31709]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The systemtags workflow component throws an error in the console:
```
 Uncaught TypeError: e.Files is undefined
    53076 systemtagmodel.js:28
    53076 systemtagmodel.js:75
    Webpack 7
```

https://github.com/nextcloud/server/blob/14e57bf70a612c16eccdd733b3562d46053419c5/core/src/systemtags/systemtagmodel.js#L28-L34

The problem seems that this bit is loaded before the OC.Files one in 
https://github.com/nextcloud/server/blob/b664aad7abdca5327684b1218ac78fa172f8acb3/apps/workflowengine/lib/Listener/LoadAdditionalSettingsScriptsListener.php#L44

### Steps to reproduce

1. Have a workflow app installed, e.g. https://github.com/nextcloud/files_automatedtagging
2. Go to the admin settings
3. Open the console

### Expected behavior

All good

### Installation method

Other

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Master of all components
```

### List of activated Apps

```shell
files_automatedtagging + default install
```

**Comment by nickvergessen** [comment]
cc @skjnldsv Maybe you can help as master of the dependency ordering work?

**Comment by nickvergessen** [comment]
cc @PVince81

**Comment by PVince81** [comment]
@artonge can you fix this one too ?

**Comment by nickvergessen** [comment]
Thanks :)
