### ISSUE TITLE
[Bug]: Bug in users administration in Nextcloud 22.2.4 and later when a user has a space in username

### ISSUE THREAD

**Issue by FlorianMarine53** [nextcloud/server#31702]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I update Nextcloud from 22.2.3 in 22.2.4 or later, I can't go in users administration's page.
An error occure and I can't see my users.

### Steps to reproduce

1. Update Nextcloud in 22.2.4 or later
2. Go to Users administration page
3. Error in the page

### Expected behavior

I  expect I'll update my Nextcloud withe no problems

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.florianmarine53.duckdns.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.florianmarine53.duckdns.org",
        "dbtype": "mysql",
        "version": "22.2.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "FR",
        "memcache.local": "\\OC\\Memcache\\Memcached",
        "installed": true,
        "logtimezone": "Eruope\/Paris",
        "logfile": "\/var\/www\/data\/nextcloud.log",
        "loglevel": 2,
        "log_authfailip": true,
        "auth.bruteforce.protection.enabled": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updater.release.channel": "stable",
        "theme": "",
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "calendar",
            "occweb",
            "previewgenerator"
        ],
        "mail_sendmailmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "trashbin_retention_obligation": "auto",
        "versions_retention_obligation": "1, 7"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - apporder: 0.14.0
  - audioplayer: 3.2.4
  - bruteforcesettings: 2.3.0
  - calendar: 3.2.2
  - checksum: 1.1.3
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.1.0
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - event_update_notification: 1.4.0
  - federatedfilesharing: 1.12.0
  - files: 1.17.0
  - files_downloadactivity: 1.12.0
  - files_external: 1.13.0
  - files_pdfviewer: 2.3.1
  - files_retention: 1.11.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trackdownloads: 1.11.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - imageconverter: 1.3.2
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - metadata: 0.15.0
  - nextcloud_announcements: 1.11.0
  - notes: 4.3.1
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - occweb: 0.1.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - quota_warning: 1.13.1
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - socialsharing_email: 2.4.0
  - spreed: 12.2.4
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - tasks: 0.14.4
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - user_usage_report: 1.6.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - encryption
  - external
  - federation
  - ransomware_protection
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional info

I restore my VM to Nextcloud 2.2.3 when update crash my Nextcloud

**Comment by szaimen** [comment]
something in nextcloud log or console log?

**Comment by FlorianMarine53** [comment]
Where are Nextcloud logs ? console log ?

**Comment by FlorianMarine53** [comment]
I find a solution.
A user with a space in username was the problem.
I delete this user and I can update Nextcloud !
It's a bug since 22.2.4 version of Nextcloud.

**Comment by alonso71** [comment]
> I find a solution. A user with a space in username was the problem. I delete this user and I can update Nextcloud ! It's a bug since 22.2.4 version of Nextcloud.

Hello!
How could you delete user?
The GUI doesn't show this user for me...

**Comment by FlorianMarine53** [comment]
Hi,
I restaured my server before the update and I deleted user whith a space in username.
After update, no more problems.
I always backup servers before updates.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by FlorianMarine53** [comment]
Hi,

I'm up to date in 25.0.3 and I can create and delete users with space in username !
It's OK for me with this bug. Thank's

**Comment by szaimen** [comment]
Thanks for verifying!
