### ISSUE TITLE
[Bug]: Doctrine\DBAL\Schema\SchemaException: The table with name `oc_authorized_groups` already exists - on update from v22.2.6 to v23.0.3

### ISSUE THREAD

**Issue by Raul1975** [nextcloud/server#31710]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Update from NC 22.2.6 to 23.0.3

### Steps to reproduce

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Repair MySQL collation
Not a mysql database -> nothing to do
Repair SQLite autoincrement
Copy data from accounts table when migrating from ownCloud
Drop account terms table when migrating from ownCloud
Das Datenbankschema wird aktualisiert
Doctrine\DBAL\Schema\SchemaException: The table with name 'benderk_1.oc_authorized_groups' already exists.

### Expected behavior

Update from NC 22.2.6 to 23.0.3 should work fine

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Folgende Apps werden aktualisiert:
Accessibility (accessibility)
Circles (circles)
Cloud Federation API (cloud_federation_api)
Comments (comments)
Contacts Interaction (contactsinteraction)
WebDAV (dav)
Federated file sharing (federatedfilesharing)
Federation (federation)
Files (files)
PDF viewer (files_pdfviewer)
Right click (files_rightclick)
File sharing (files_sharing)
Deleted files (files_trashbin)
Versions (files_versions)
Video player (files_videoplayer)
First run wizard (firstrunwizard)
Log Reader (logreader)
Lookup Server Connector (lookup_server_connector)
Nextcloud announcements (nextcloud_announcements)
Notifications (notifications)
OAuth 2.0 (oauth2)
Password policy (password_policy)
Photos (photos)
Privacy (privacy)
Provisioning API (provisioning_api)
Recommendations (recommendations)
Monitoring (serverinfo)
Nextcloud settings (settings)
Share by mail (sharebymail)
Support (support)
Usage survey (survey_client)
Collaborative tags (systemtags)
Text (text)
Theming (theming)
Two factor backup codes (twofactor_backupcodes)
Update notification (updatenotification)
User status (user_status)
Viewer (viewer)
Weather status (weather_status)
Nextcloud workflow engine (workflowengine)

Diese inkompatiblen Apps werden deaktiviert:
Deck (deck)
Group folders (groupfolders)
Impersonate (impersonate)
```

**Comment by skorpions2000** [comment]
Update from NC 22.2.6 to 23.0.3 not work, have problem:
Doctrine\DBAL\Schema\SchemaException: The table with name 'mi_cloud.oc_authorized_groups' already exists.

**Comment by fti7** [comment]
Run into the same Problem. Any Updates here?

**Comment by puntopaz** [comment]
I had the same problem updating from v22.2.3 to v23.0.8.

Digging into the code, I found this update file [Version23000Date20210721100600.php](https://github.com/nextcloud/server/blob/master/core/Migrations/Version23000Date20210721100600.php) whichis missing a check for the table existance.

So, before clicking the `start update` button, I modified the code from:

```php
public function changeSchema(IOutput $output, Closure $schemaClosure, array $options): ?ISchemaWrapper {
	/** @var ISchemaWrapper $schema */
	$schema = $schemaClosure();
        $table = $schema->createTable('authorized_groups');
        <other table instructions>
	return $schema;
}
```

to:

```php
public function changeSchema(IOutput $output, Closure $schemaClosure, array $options): ?ISchemaWrapper {
	/** @var ISchemaWrapper $schema */
	$schema = $schemaClosure();
	if (!$schema->hasTable('authorized_groups')) {
            $table = $schema->createTable('authorized_groups');
            <other table instructions>
        }
    return $schema;
}
```

After this change I had also to disable the plugin `group_folders` which generated another error, but in the end the update was successful.

**Comment by puntopaz** [comment]
Please note that before trying this change I also checked the table structure to be sure it was compatible with the table schema introduced by the update.

So first I connected to the database
```bash
  mysql --user=root --password=$NEXTCLOUD_DB_PWD
```
I'm currenly using [Nethserver](https://www.nethserver.org/) so my real command line was slightly different:
```bash
  /opt/rh/rh-mariadb105/root/bin/mysql --socket="/var/run/rh-mariadb105-mariadb/nextcloud-mysql.sock" --user=root --password=$NEXTCLOUD_DB_PWD
```

and then checked the table with:

```
SHOW DATABASES;
USE nextcloud;
DESCRIBE nextcloud.oc_authorized_groups;
DESCRIBE oc_authorized_groups;
SHOW INDEX FROM oc_authorized_groups;
SELECT * from oc_authorized_groups;
\q
```

The output was:

```
MariaDB [(none)]> SHOW DATABASES;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| mysql              |
| nextcloud          |
| performance_schema |
+--------------------+
4 rows in set (0.040 sec)

MariaDB [(none)]> USE nextcloud;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [nextcloud]> DESCRIBE oc_authorized_groups;
+----------+--------------+------+-----+---------+----------------+
| Field    | Type         | Null | Key | Default | Extra          |
+----------+--------------+------+-----+---------+----------------+
| id       | int(11)      | NO   | PRI | NULL    | auto_increment |
| group_id | varchar(200) | NO   | MUL | NULL    |                |
| class    | varchar(200) | NO   |     | NULL    |                |
+----------+--------------+------+-----+---------+----------------+
3 rows in set (0.002 sec)

MariaDB [nextcloud]> SHOW INDEX FROM oc_authorized_groups;
+----------------------+------------+----------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table                | Non_unique | Key_name             | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+----------------------+------------+----------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| oc_authorized_groups |          0 | PRIMARY              |            1 | id          | A         |           0 |     NULL | NULL   |      | BTREE      |         |               |
| oc_authorized_groups |          1 | admindel_groupid_idx |            1 | group_id    | A         |           0 |     NULL | NULL   |      | BTREE      |         |               |
+----------------------+------------+----------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
2 rows in set (0.001 sec)

MariaDB [nextcloud]> SELECT * from oc_authorized_groups;
Empty set (0.001 sec)
```

The existing table had exactly the same schema introduced by the update (and was also empty),
so I was confident the patch would not introduce database errors.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by puntopaz** [comment]
Hi, I updated to 24.0.x right after I updated to 23.0.8, without any problems. 
I just didn't mention it in the post because this thread was about the update 22.x -> 23.x

I updated from 24.0.x to 25.0.3 just a couple of days ago and didn't notice any errors, so for me this problem is fixed.

Please also note that the master branch file I referenced in my previous post: [Version23000Date20210721100600.php](https://github.com/nextcloud/server/blob/master/core/Migrations/Version23000Date20210721100600.php) is one of the few files in `Migrations` which doesn't contains the `if (!$schema->hasTable()) { .. }` guard.

Maybe who wrote those files just forgot the guard?

**Comment by szaimen** [comment]
> Please also note that the master branch file I referenced in my previous post: [Version23000Date20210721100600.php](https://github.com/nextcloud/server/blob/master/core/Migrations/Version23000Date20210721100600.php) is one of the few files in `Migrations` which doesn't contains the `if (!$schema->hasTable()) { .. }` guard.

That is a good observation. Cc @PVince81 what would you say: is it okay to add this even though nc23 is already eol?

**Comment by PVince81** [comment]
as this will prevent upgrade issues and is a minimal and safe change, it's ok to have in NC 23

**Comment by szaimen** [comment]
Okay, let me do this then 👍

**Comment by szaimen** [comment]
PR here: https://github.com/nextcloud/server/pull/36407
