### ISSUE TITLE
[NC 11.0.1] Desktop client shows notification, but the Web-GUI login as admin does not

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/server#3171]
I permanently receive notifications in the desktop client (owncloud 2.2.4 on debian 8) that my instance needs 

When logging in as admin to my NC, I do not see a notification banner.

I suppose, the message comes from an App which "cries" for update (Calendar App wants to be updated).

#### Proposal

I propose to check (implement) a way that apps can push their messages, too.

**Comment by MorrisJobke** [comment]
> When logging in as admin to my NC, I do not see a notification banner.

There is a little bell sign in the top right:

<img width="379" alt="bildschirmfoto 2017-01-19 um 19 21 14" src="https://cloud.githubusercontent.com/assets/245432/22131942/7ea35964-de7c-11e6-9277-894b8efb4d79.png">

There should be the notification shown. Those are also propagated to the clients.

**Comment by Wikinaut** [comment]
@MorrisJobke Ah, yes. But I meant the more striking **yellow** banner on top of the file view (NC start) screen.

**Comment by Wikinaut** [comment]
I often overlooked the very small "bell sign". This should be changed (make that more conspicuous.)

**Comment by nickvergessen** [comment]
This is from an app: https://github.com/nextcloud/notifications

And no, no need to open a new issue there, we won't change it.

**Comment by Wikinaut** [comment]
I meant the yellow label which says that an update of the server code is available.

**Comment by Wikinaut** [comment]
@nickvergessen "we won't change it." Risking a new fork ?

**Comment by MorrisJobke** [comment]
The yellow bar is the old way of notification. It only supports to show one and blocks the UI - so we went for this notification area. And this has nothing to do with a new fork. This was the reason for the design of this.

**Comment by Wikinaut** [comment]
perhaps, it should be changed to become more apparent.

**Comment by nickvergessen** [comment]
Yeah feel free to fork the notification app and adjust the UI of it like you want, no problem with that. But we won't do it in the default shipped notifications app.

**Comment by Wikinaut** [comment]
One proposal: a smart animation, fired only on the first view. I remember to have seen that somewhere, but don't know where.

**Comment by nickvergessen** [comment]
We have an animation when you receive a new notification while the page is open...

**Comment by jancborchardt** [comment]
Btw just for the record @Wikinaut we actually adjusted the notification icon to be fully whote when there are notifications. Should be way better visible. :)
