### ISSUE TITLE
[NC 10/11] Improve the Updater App: currently it deinstalls apps but does not reload and restart them

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/server#3172]
On my debian 8 servers running previously NC 10, now NC 11.0.1, I noticed that the updater works very well but

#### installed apps were stopped and not reloaded and not restarted when server software was updated.

The update app disabled i.a. Music Player, Contacts, Calendar, TOTP Provider, Disable Remember Login, but did not reinstall and reload these apps.

#### ad-hoc proposal: a check list of apps which requires manual re-installation and re-activation

At least a `check list` (of previously installed and enabled apps) should be available with which the NC Admin can re-install and enable these apps one by one.

The current way how the updater works is, in my view, unsatisfying in that respect.

**Comment by MariusBluem** [comment]
The updater shows at the end of the upgrade-process which `3rdparty`-apps were disabled, so you are able to re-activate them - or maybe (if required) update them 😉 ...

**Comment by Wikinaut** [comment]
@MariusBluem You explain what I noticed. This is not a solution, I want that the updater automatically re-installs them, or a static list (or additional page) is shown with a kind of "check list".

**Comment by MariusBluem** [comment]
The Updater has its own issue-tracker, so if you still see places to improve - please re-open the ticket over here: https://github.com/nextcloud/updater THX 👊

**Comment by Wikinaut** [comment]
okay
