### ISSUE TITLE
Unshare menu has too high line-height

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#3174]
For longer translation texts the menu is multi-line and then looks a bit odd.

<img width="405" alt="bildschirmfoto 2017-01-19 um 16 34 36" src="https://cloud.githubusercontent.com/assets/245432/22128231/3d177320-de65-11e6-9dc7-7315a6f4d175.png">

Maybe @skjnldsv or @ChristophWurst could have a look ;)

**Comment by MorrisJobke** [comment]
If it's unclear: this is the sidebar with the share panel.

**Comment by skjnldsv** [comment]
@MorrisJobke with master?

**Comment by JSoko** [comment]
Under Nc 10.0.2 with de_DE it looks like this:
![unshare](https://cloud.githubusercontent.com/assets/5583290/22139860/2ac6ac66-dee9-11e6-9cc6-f263761861eb.jpg)

**Comment by nickvergessen** [comment]
Should just be wider ...

**Comment by MorrisJobke** [comment]
> @MorrisJobke with master?

Yes - master

**Comment by MorrisJobke** [comment]
cc @jancborchardt
