### ISSUE TITLE
Failed to enable app workflowengine

### ISSUE THREAD

**Issue by MichaelHeimann** [nextcloud/server#3175]
### Steps to -reproduce-
1. have nextcloud 10.0.3
2. upgrade to 11.0.1 via web updater

Comment:
As nickvergessen posted here (https://github.com/nextcloud/server/issues/2617) that this might happen it the upgrade was already done in the past: it wasn't.
The upgrade succeeded as far as I can say - no issues observed and the occ app:list doesn't give a version for the workflowengine, so I guess it's fine.

### Expected behaviour
No error.

### Actual behaviour
upgrade error'd: "Failed to enable app workflowengine"
needed to upgrade via occ upgrade on cli

### Server configuration
**Operating system**:
Linux owncloud 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
apache2/xenial-security,xenial-updates,xenial-security,now 2.4.18-2ubuntu3.1 amd64  [installiert]

**Database:**
  'dbtype' => 'sqlite3',

**PHP version:**
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)
now  11.0.1 - before 10.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Started with Owncloud 8.1.1.3

**Where did you install Nextcloud from:**
zip file from homepage

**Signing status:**

all checks passed.
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - calendar: 1.5.0
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - workflowengine: true
Disabled:
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - mail
  - user_ldap
  - user_saml

</details>

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oc65c7d2aa6b",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "owncloud.heimann.ws",
            "heimann.cloud"
        ],
        "datadirectory": "\/var\/nextcloud-data",
        "dbtype": "sqlite3",
        "version": "11.0.1.2",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "192.168.43.1",
        "mail_smtpport": "25",
        "forcessl": true,
        "mail_from_address": "no-reply",
        "mail_domain": "heimann.ws",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "loglevel": 0,
        "trashbin_retention_obligation": "auto",
        "overwrite.cli.url": "https:\/\/owncloud.heimann.ws\/owncloud",
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
        "updater.release.channel": "stable",
        "appstore.experimental.enabled": false,
        "appstoreurl": "https:\/\/apps.nextcloud.com\/api\/v0",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Google Drive
**Are you using encryption:** yes/no
Yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Chrome Version 55.0.2883.87 (64-bit)

**Operating system:**
Linux michael 4.8.13-100.fc23.x86_64 #1 SMP Fri Dec 9 14:51:40 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

#### Web server error log
no entry from today
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
http://pastebin.com/nC1VBpi8
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
not a browser issue hence no log gathered.
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment]
See https://github.com/nextcloud/server/issues/2617#issuecomment-272871665

**Comment by MichaelHeimann** [comment]
@nickvergessen I've just upgraded from 11.0.1 to 11.0.2 and again this error. (workflowengine: Failed to enable app workflowengine)

I've not restored a backup before as mentioned in #2617. The Script you reference to, gives me "App workflowengine is not installed and disabled 1488233735 [Error] Table flow_checks of app workflowengine exists although the app is not installed 1488233735 [Info] Table flow_checks has 0 entries 1488233735 [Error] Table flow_operations of app workflowengine exists although the app is not installed 1488233735"

What is this workflowengine thingy, I can't remember installing or uninstalling it. Do I need it? How do I not get this error when I do the next upgrade?
