### ISSUE TITLE
Favorites: Allow Dropping onto Favorite folders + Navigation in "Move/Copy" dialog

### ISSUE THREAD

**Issue by YouveGotMeowxy** [nextcloud/server#31764]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

1. When several subfolders deep and wanting to move or copy files to one of your Favorites/Quick Access folders, your only choice is to click the context menu and select the Move/Copy option, then drill down to one of those Favorites. Needlessly tedious when you're already looking at the folder you'd like to drop them into right in the left menu area.
2. When in said Move/Copy dialog, you still have to drill down to wherever you have your favorite folders. This often results in just WAY too much back and forth navigation to do simple move/copy operations, when you do it a LOT, like with photographers.

**Describe the solution you'd like**

1. Just allow dropping selected files onto whichever folder you want that is shown in the Favorites list, just like you would any other folder. Perhaps use the keyboard the same as you would in any Explorer window (hold Shift while dropping to move; hold Ctrl while dropping to copy).
2. Add a "Favorites" icon in the Move/Copy dialog that when clicked "jumps" you to that folder. When the icon is clicked, a simply dropdown that lists the Favorites, just like the Favorites to the left. i.e.

![image](https://user-images.githubusercontent.com/39491297/160914277-7a11d39f-2cb7-42f5-8d7f-9d0b3edf77d0.png)

**Describe alternatives you've considered**

None. There are no other alternatives in this case.

**Additional context**

**Comment by susnux** [comment]
Tgis is available in 27.1 and later
