### ISSUE TITLE
[Enhancement?] Use Keyboard to select multiple items?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [nextcloud/server#31765]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

In almost every other app (i.e. any Explorer type app) you can **select 1 item in a list, then hold Shift and click another item in the list, and it along with every file in between will get selected**; in Nextcloud you can't seem to do that (I just tried several times). Is there some reason why?

When I want to for example, select a hundred pictures to drag into a  subfolder, it makes it monotonous to 1 by 1 select each image. And then after moving those, have to do it all over again for another bunch of files to place into another sub folder.

**Describe the solution you'd like**

For the lists of items to use all the same standard basic Explorer (type of) keyboard combos.

In this case, allow shift+click to select multiple items.

**Describe alternatives you've considered**

None other apply AFAIK.

**Additional context**

**Comment by z3ntu** [comment]
For selecting multiple files I just found this https://github.com/nextcloud/server/issues/17313#issuecomment-552958640 and can confirm that works on Nextcloud 24 for me. Very unintuitive though in my opinion.

**Comment by skjnldsv** [comment]
Closing for https://github.com/nextcloud/server/issues/30484
