### ISSUE TITLE
Add max file upload in JS before upload 

### ISSUE THREAD

**Issue by gaalos** [nextcloud/server#31762]
Hi,
Because of Nextcloud chunks it's not possible to limit max file upload..
When user upload large file he is not blocked by max size but he go time out.. 
If i'm right the chunks are generated with JS that mean JS can easly know the file zize.
Maybe it's could be nice if javascript test the file size and test if the file size is biger than VARIABLE.
If  it's, then prompt message to the user like "file is too big".
please don't talk about https://docs.nextcloud.com/server/latest/admin_manual/file_workflows/access_control.html
The goal here is to stop upload before any Nextcloud work, chunk, reconstruct file ect... 

Using jquery(3.3.1) like that for exemple : 
http://jsfiddle.net/fu0pnLxs/4/

**Comment by HannesJo0139** [comment]
I think webserver or php max upload restrictions are meant to protect the server against being blocked or kind of 'no space left in cache' stuff. The idea behind chunked uploading is, as far as I know, to avoid these issues by splitting big files and so it is correct to bypass the max upload filesize limits. So I think best you can do is disabling chunked uploading `sudo -u www-data php occ config:app:set files max_chunk_size --value 0`

**Comment by skjnldsv** [comment]
Hi,

That would defeat the purpose of the chunk upload.
The exact issue you're experiencing is the reason (amongst other), that made chunk upload possible.
The max file upload php config is not made to limit the size of files your user can upload.
This is more what user quota and the flow app are for. :)
