### ISSUE TITLE
[Bug]: sudo -u www-data php occ files:scan --all

### ISSUE THREAD

**Issue by JordanDIG** [nextcloud/server#31786]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After running the occ scan -all command following a server migration, all modification and creation dates are wrong.
Is it possible to restore them? They are correctly displayed when you click on the 3 small dots and then details on nextcloud files

### Steps to reproduce

1. Run sudo -u www-data php occ files:scan --all

### Expected behavior

A way to fix it...

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MySQL

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other

### Configuration report

```shell
/
```

### List of activated Apps

```shell
/
```

### Nextcloud Signing status

```shell
/
```

### Nextcloud Logs

```shell
/
```

**Comment by PVince81** [comment]
how did you migrate the files ? if you used scp or rsync, you need to make sure that the mtime of the files are preserved **on disk** because occ files:scan is going to read the mtime value on disk and update the database

please verify and reopen if the mtimes on disk were correct, then it's a bug.
otherwise, the scanner works as expected

**Comment by JordanDIG** [comment]
> how did you migrate the files ? if you used scp or rsync, you need to make sure that the mtime of the files are preserved **on disk** because occ files:scan is going to read the mtime value on disk and update the database
> 
> please verify and reopen if the mtimes on disk were correct, then it's a bug. otherwise, the scanner works as expected

I have migrated my data using the scp command. The modification dates of the files were correct.

**Comment by PVince81** [comment]
does scp preserve the mtimes ?

can you post an example of file mtime on disk (with ls -la) and then show the matching entry in oc_filecache after running a scan ?

for the oc_filecache, use this query: select * from oc_filecache where path like '%nameoffile%'

**Comment by JordanDIG** [comment]
> does scp preserve the mtimes ?
> 
> can you post an example of file mtime on disk (run `stat` on the file) and then show the matching entry in oc_filecache after running a scan ?
> 
> for the oc_filecache, use this query: select * from oc_filecache where path like '%nameoffile%'

I didn't quite understand what I should do exactly?

**Comment by PVince81** [comment]
1. go to the original location / your backup
2. pick an example file, I'll call it "test.txt"
3. run `stat test.txt`
4. then go to the new location where you scp'd the files, run `stat test.txt`
5. then go to the Nextcloud instance and run: `occ files:scan --all` (if needed, you already did)
6. then connect to the Nextcloud database and run: `select * from oc_filecache where path like '%test.txt%'`

This will show us the timestamps of the file before the copy, after the copy and after the scan.
If they are all the same, then you might have found a bug of sorts.

**Comment by JordanDIG** [comment]
> 1. go to the original location / your backup
> 2. pick an example file, I'll call it "test.txt"
> 3. run `stat test.txt`
> 4. then go to the new location where you scp'd the files, run `stat test.txt`
> 5. then go to the Nextcloud instance and run: `occ files:scan --all` (if needed, you already did)
> 6. then connect to the Nextcloud database and run: `select * from oc_filecache where path like '%test.txt%'`
> 
> This will show us the timestamps of the file before the copy, after the copy and after the scan. If they are all the same, then you might have found a bug of sorts.

Unfortunately the original location of the data is no longer accessible.

**Comment by PVince81** [comment]
> > 1. go to the original location / your backup
> > 2. pick an example file, I'll call it "test.txt"
> > 3. run `stat test.txt`
> > 4. then go to the new location where you scp'd the files, run `stat test.txt`
> > 5. then go to the Nextcloud instance and run: `occ files:scan --all` (if needed, you already did)
> > 6. then connect to the Nextcloud database and run: `select * from oc_filecache where path like '%test.txt%'`
> > 
> > This will show us the timestamps of the file before the copy, after the copy and after the scan. If they are all the same, then you might have found a bug of sorts.
> 
> Unfortunately the original location of the data is no longer accessible.

you can still do the other steps.

occ files:scan should take whatever mtime is on disk, the one from step 4.
if it does, it works as expected. if it doesn't, it's a bug.

**Comment by JordanDIG** [comment]
> 

So you think this will give me the original modification dates of my files?

**Comment by JordanDIG** [comment]
> > > 1. go to the original location / your backup
> > > 2. pick an example file, I'll call it "test.txt"
> > > 3. run `stat test.txt`
> > > 4. then go to the new location where you scp'd the files, run `stat test.txt`
> > > 5. then go to the Nextcloud instance and run: `occ files:scan --all` (if needed, you already did)
> > > 6. then connect to the Nextcloud database and run: `select * from oc_filecache where path like '%test.txt%'`
> > > 
> > > This will show us the timestamps of the file before the copy, after the copy and after the scan. If they are all the same, then you might have found a bug of sorts.
> > 
> > 
> > Unfortunately the original location of the data is no longer accessible.
> 
> you can still do the other steps.
> 
> occ files:scan should take whatever mtime is on disk, the one from step 4. if it does, it works as expected. if it doesn't, it's a bug.

Okay I will try 😉

**Comment by JordanDIG** [comment]
> > > 1. go to the original location / your backup
> > > 2. pick an example file, I'll call it "test.txt"
> > > 3. run `stat test.txt`
> > > 4. then go to the new location where you scp'd the files, run `stat test.txt`
> > > 5. then go to the Nextcloud instance and run: `occ files:scan --all` (if needed, you already did)
> > > 6. then connect to the Nextcloud database and run: `select * from oc_filecache where path like '%test.txt%'`
> > > 
> > > This will show us the timestamps of the file before the copy, after the copy and after the scan. If they are all the same, then you might have found a bug of sorts.
> > 
> > 
> > Unfortunately the original location of the data is no longer accessible.
> 
> you can still do the other steps.
> 
> occ files:scan should take whatever mtime is on disk, the one from step 4. if it does, it works as expected. if it doesn't, it's a bug.

Indeed the scp does not keep the dates of modifications. And the little test you gave me works perfectly so it's not a bug.
Thanks for all
