### ISSUE TITLE
[Bug]: Comments field looks broken

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#31781]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![Bildschirmfoto von 2022-03-31 16-18-09](https://user-images.githubusercontent.com/213943/161077581-917f6c8a-c085-4594-a4ba-43689c49804e.png)

### Steps to reproduce

1. Enable comments
2. Open the sidebar
3. Switch to comments tab

### Expected behavior

✨ 

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
master
```

**Comment by szaimen** [comment]
Is this just since 24 or already earlier?

**Comment by nickvergessen** [comment]
![Bildschirmfoto von 2022-04-01 11-07-29](https://user-images.githubusercontent.com/213943/161232599-91fe52ad-85a7-4bf7-b0d0-0ecf6000e08d.png)

In 23 it's broken differently (only the error is overlapping the text, but the text is not floating out of the box)
