### ISSUE TITLE
[Bug]: 24 Beta 2 - PDFs do not open

### ISSUE THREAD

**Issue by SimplyCorbett** [nextcloud/server#31795]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

PDF.js v2.13.216 (build: 399a0ec60)
Message: Setting up fake worker failed: "Cannot load script at: https://cloud.myurl.com/apps/build/pdf.worker.js".

### Steps to reproduce

1. Update PHP from 7.4 to 8.1, update nextcloud from 23.0.3 to 24 beta 2

### Expected behavior

PDF's open

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
.
```

### List of activated Apps

```shell
.
```

### Nextcloud Signing status

```shell
.
```

### Nextcloud Logs

```shell
{"reqId":"nNOZVVGSlnsD06tSWOmT","level":3,"time":"2022-04-01T21:46:48+00:00","remoteAddr":"blah","user":"simplycorbett","app":"core","method":"GET","url":"/core/preview?fileId=2594&c=c9aaedd369801d15fd1aa85032f7903e&x=250&y=250&forceIcon=0&a=0","message":"File: /simplycorbett/files/MXRoute/Receipts/MXroute - 47264.pdf Imagick says:","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0","version":"24.0.0.7","exception":{"Exception":"ImagickException","Message":"attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/421","Code":499,"Trace":[{"file":"/var/www/nextcloud/lib/private/Preview/Bitmap.php","line":95,"function":"readImage","class":"Imagick","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Bitmap.php","line":56,"function":"getResizedPreview","class":"OC\\Preview\\Bitmap","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/GeneratorHelper.php","line":65,"function":"getThumbnail","class":"OC\\Preview\\Bitmap","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":321,"function":"getThumbnail","class":"OC\\Preview\\GeneratorHelper","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":157,"function":"getMaxPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/lib/private/Preview/Generator.php","line":110,"function":"generatePreviews","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/lib/private/PreviewManager.php","line":212,"function":"getPreview","class":"OC\\Preview\\Generator","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":169,"function":"getPreview","class":"OC\\PreviewManager","type":"->"},{"file":"/var/www/nextcloud/core/Controller/PreviewController.php","line":142,"function":"fetchPreview","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"getPreviewByFileId","class":"OC\\Core\\Controller\\PreviewController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1022,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Preview/Bitmap.php","Line":95,"CustomMessage":"File: /simplycorbett/files/MXRoute/Receipts/MXroute - 47264.pdf Imagick says:"}}

```

### Additional info

.

**Comment by SimplyCorbett** [comment]
@skjnldsv I see you're pretty active on files_pdfviewer. Any ideas?

Not sure if this bug should go under files_pdfviewer either.

**Comment by artonge** [comment]
I can't reproduce. Is it happening with every PDF? On Chrome and Firefox?

From the logs, it looks like a server issue:

```
		"Exception": "ImagickException",
		"Message": "attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/421",

**Comment by SimplyCorbett** [comment]
I tested with the release bundle

**Comment by sagitariozod** [comment]
I haver the sama issue after upgrade to v24beta2.
php versión 7.4.

**Comment by prghix** [comment]
Same here. Rocky linux with PHP 8.1:

![image](https://user-images.githubusercontent.com/52444671/162400675-5322971d-d256-42ba-ae1f-6c6977fbe7d3.png)

**Comment by skjnldsv** [comment]
Fix in https://github.com/nextcloud/files_pdfviewer/pull/589

**Comment by sagitariozod** [comment]
I have the same issue after upgrade to v24beta2.
php version 7.4.

PDF.js v2.13.216 (build: 399a0ec60)
Mensaje: Setting up fake worker failed: "Cannot load script at: https://minube.miserver.com/index.php/apps/build/pdf.worker.js".

**Comment by PVince81** [comment]
the fix was done post-beta3, so you'll get it in RC1

**Comment by AndyFx12** [comment]
Bug ist still present at NC24 RC1. PHP:8.0
