### ISSUE TITLE
Public links for calendar

### ISSUE THREAD

**Issue by krueuw** [nextcloud/server#318]
Hello,

it would be very nice if you add stabil support for "Public links for calendars". This was possible in owncloud 4, with special patch in owncloud 6 and in the app calendar+ in owncloud 8.1. Owncloud 9 hasnt this feature.

**Comment by MorrisJobke** [comment]
Related to https://github.com/owncloud/core/issues/22735

**Comment by hitam4450** [comment]
This feature is very much appreciated!

regards, hitam4450

**Comment by gour** [comment]
:+1:

**Comment by rullzer** [comment]
Done in https://github.com/nextcloud/server/pull/1197
