### ISSUE TITLE
[Bug]: Weather service on the dashboard displayed while the application is disabled

### ISSUE THREAD

**Issue by JordanDIG** [nextcloud/server#31808]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On the dashboard when you click on the Customize button and the application is deactivated the text about the methéo service is always displayed

### Steps to reproduce

1. Disable Weather status
2. Go to the dashboard
3. and you will see that the text is always displayed

### Expected behavior

That the text appears only when the application is active

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other

### List of activated Apps

```shell
Basic App after fresh install
```

**Comment by JordanDIG** [comment]
cc @nickvergessen

**Comment by SimplyCorbett** [comment]
It's probably just the template having warning text on it. I doubt the service itself is still requesting location data or running.

Still, it doesn't hurt to check.

**Comment by JordanDIG** [comment]
> Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!
> 
> My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!
> 
> If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

The problem is still there on my side tested in nextcloud 25.0.4
![image](https://user-images.githubusercontent.com/38187648/223178051-17424826-bb72-48e1-ae9a-ef9b953c6799.png)

**Comment by JordanDIG** [comment]
@seal20 What information do you need?

**Comment by joshtrichards** [comment]
Fixed in #39527
