### ISSUE TITLE
share by mail: notification mail uses internal username, not displayname

### ISSUE THREAD

**Issue by 4001982248998** [nextcloud/server#3180]
### Steps to reproduce
1. logon as ldap user that has a uuid as (internal) username
2. share a file via share-by-mail
2. regard the mail that is being sent
3. the subject will say: “37B60CC4-911B-42E7-A331-1AE2D9F61E84 shared »a file« with you”, the body will be likewise

### Expected behaviour
The e-mail should mention the file owner's displayname, not an internal username (that cannot be changed). This is especially expected following the discussion at https://github.com/owncloud/core/issues/6984.

### Actual behaviour
Notification mail uses an internal username, not the human-readable displayname.

### Server configuration
**Operating system**: Ubuntu Xenial

**Web server:** Apache 2.4

**Database:** MariaDB

**PHP version:** 7.0

**Nextcloud version:** 11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>
```
Integrity checker has been disabled. Integrity cannot be verified.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - user_ldap: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - files_automatedtagging
  - files_retention
  - richdocuments
  - templateeditor
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oce4ee771c55",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.comdok.de"
        ],
        "datadirectory": "\/srv\/data",
        "dbtype": "mysql",
        "version": "11.0.1.2",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "forcessl": false,
        "loglevel": 0,
        "logfile": "\/srv\/data\/nextcloud.log",
        "log_rotate_size": 104857600,
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de_DE",
        "trashbin_retention_obligation": "auto",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "updatechecker": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "production",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/... no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
sorry, I do not feel like disclosing that. I just want to emphasize that option ldapExpertUsernameAttr has been changed later, but all user accounts created before still of course have that non-readable UUID username that cannot be changed.
```
```
</details>

### Client configuration
**Browser:** MF 50.1.0

**Operating system:** Arch

**Comment by nickvergessen** [comment]
@schiessle while you are on it (changing from owner to initiator)

**Comment by schiessle** [comment]
That's already fixed and will be released with the next bugfix release https://github.com/nextcloud/server/pull/3033
