### ISSUE TITLE
Automatic updates of apps as an option

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#3182]
It's better now than before, now you at least get a notification when there is a new app update available, but it could be even better.

**Options:**
1. Add an option to update all apps via cron (or automatically in some way, maybe as a setting in config.php: `autoupdate => 'true'`)
2. Add an option to update all apps at once instead of:
a. Notification you have a update available
b. Click on the notification
c. Scroll, scroll, scroll
d. Update each app seperatly

Updating all apps at once is possible in Wordpress, why not here?

**Comment by 001101** [comment]
should really be fast implemented, because it is really annoying

**Comment by mightyBroccoli** [comment]
that would be so nice to have that as a feature maybe even more complex to list apps that should update automatically and one that should not just in case.

**Comment by nickvergessen** [comment]
What is annoying? Logging in and pressing a button?

I see a point in having auto updates. On the other hand since apps are not checked in the slightest way before published in the app store, I wouldn't really recommand auto update for everything.

**Comment by enoch85** [comment]
>  I wouldn't really recommand auto update for everything.

That's why it should be added as an option.

**Comment by 001101** [comment]
@nickvergessen RIGHT, because if you must do this for 10 or more instances it is damn annoying!!

It is no argument that updates get not checked for compatibility, cause you even do not check them in a separate dev environment before you press the button manually.

There should be some CI checks before updates are available, but this requires the implantation of a dedicated marketplace.

**Comment by konstin** [comment]
Any progress on this? This would require not much more than hooking the existing update routines into the cron tasks and it would be a great usability improvements.

**Comment by nickvergessen** [comment]
We will add a "Update available" section for Nextcloud 13: #6739

**Comment by nickvergessen** [comment]
Option 2 has been implemented, I don't think we want to do Option 1 at the moment, so I'm closing this.

**Comment by konstin** [comment]
I'd definitely want option 1, but I guess that's something for a separate app.

**Comment by enoch85** [comment]
@konstin Please open another issue asking to improve the current function. Don't forget to link this issue.

And thank you  @juliushaertl for implementing this!

**Comment by YouveGotMeowxy** [comment]
Not to sound rude, but based on the date of the OP, I guess this is never gonna happen?

**Comment by szaimen** [comment]
If you have root access to your server you could create a cronjob with:
`occ app:update --all`

**Comment by 001101** [comment]
> `occ app:update --all`

I mean devs, you should know this function, why did nobody tell this earlier?

Just the question if the app updates could break if the base got not updated?

**Comment by nickvergessen** [comment]
Because it didn't exist 3years ago when this issue was discussed.

An app could break on update when it doesn't specify it's requirements correctly

**Comment by connelhooley** [comment]
Is there way to only update minor or patch versions? Ideally I'd like to avoid auto-updating major version numbers but still do the rest. It would also be good to not get the current notification if an app is auto-updated too.

**Comment by skamuuu** [comment]
It's June 2026, more than 1 year have passed since the last comment here... and I am still hoping this feature could become available. Any update??
