### ISSUE TITLE
Search tool for apps

### ISSUE THREAD

**Issue by diyoyo** [nextcloud/server#31822]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Yes. I have been setting up NextCloud many times this week for the first time of my life, trying different hostings, crashing the app etc. and it felt very frustrating to not have either an "All Apps" list, or a Search bar in the App Store, when reinstalling new apps.

**Describe the solution you'd like**
Either a All Apps list in the App store, or a search button.

**Describe alternatives you've considered**

**Additional context**
Also, It could be nice to display everything in a compact mode, when we know what we're looking for.

**Comment by joshtrichards** [comment]
Hi @diyoyo - Thanks for your report and suggestion. I'm able to to search for apps (ones from anywhere in the app store as well as installed ones) when I'm in the Apps section in NC by clicking on the usual NC Search icon. Are you saying you want something more than this or that this wasn't working for you?

![image](https://github.com/nextcloud/server/assets/1731941/d0cc9c14-713c-4072-bcd2-a1bd5c2141df)

**Comment by joshtrichards** [comment]
Related: #23127

**Comment by joshtrichards** [comment]
Closing due to no response received >1 year + other Issues covering.
