### ISSUE TITLE
Mimetype detection for hidden files

### ISSUE THREAD

**Issue by mwalbeck** [nextcloud/server#3183]
Implement mimetype detection for hidden files, so hidden images and text files gets recognized as such, and not as generic files. This would also ensure that if you upload a hidden file to Nextcloud, and then rename it to a none hidden file, you don't have to update the filecache for it to have the correct mimetype.

This is something I would be willing to look into myself.

Any thoughts?

**Comment by nickvergessen** [comment]
Sounds good, and feel free to look into it.

**Comment by rullzer** [comment]
Fixed by #3212
