### ISSUE TITLE
[Bug]: User status modal hides only set button in new modal height

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#31854]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![Bildschirmfoto von 2022-04-06 07-48-13](https://user-images.githubusercontent.com/213943/161904745-0d6ad415-b201-4d78-8f33-b8f96e9e2c65.png)

The modal is high enough to show everything perfectly fine, but the submit button. Maybe we can make the height depend on the content so you don't have to scroll to discover it. You have to guess by the remaining bits of the missing scrollbar that you can scroll. When changing the height it should not be hard coded but grow by content because e.g. german needs 2 rows for the DND description and would therefor cut it off otherwise:

![Bildschirmfoto von 2022-04-06 07-54-08](https://user-images.githubusercontent.com/213943/161905032-76aa727c-3bbf-47b1-810a-797d505a7df2.png)

### Steps to reproduce

1. Open the status modal
2. Set a custom status
3. For a brief moment wonder if there is a save button but you don't see any.

### Expected behavior

Save button shows by default instead of scroll bar

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
master
```

**Comment by szaimen** [comment]
@nickvergessen maybe it would make sense to discuss the fixed modal height in the frontenders channel?

**Comment by nickvergessen** [comment]
> maybe it would make sense to discuss the fixed modal height in the frontenders channel?

Feel free to.
