### ISSUE TITLE
[Bug]: Mountpoints of Collectives app no longer initialized on all requests

### ISSUE THREAD

**Issue by mejo-** [nextcloud/server#31858]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Starting today, the Nextcloud server master branch broke mountpoint initialization of the Collectives app. When requesting the pages of a collective from the Collectives app backend, the folder that is supposed to hold the mountpoints for all collectives is empty instead.

The second get in this line throws a NotFoundException, because the mountpoints for the users collectives are not mounted yet: https://gitlab.com/collectivecloud/collectives/-/blob/main/lib/Service/PageService.php#L71

I'm updating the Nextcloud server code almost daily, so I suppose that some change within the last days broke this.

After a hint by @CarlSchwan, I tried adding 'Mountprovider::class' as extra argument to [the `parent::_constructor()` call in `CollectiveMountpoint`](https://gitlab.com/collectivecloud/collectives/-/blob/main/lib/Mount/CollectiveMountPoint.php#L40), which indeed seems to fix the issue for me.

@PVince81 @icewind1991 

### Steps to reproduce

1. Checkout latest Nextcloud server master branch.
2. Install Collectives app.
3. Create a collective and try to browse its pages. An error message will be shown that the pages list could not be fetched.

### Expected behavior

The mountpoints for the users collectives should be mounted during the requests to the Collectives app API.

### Installation method

Manual installation

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MariaDB

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
...
```

**Comment by PVince81** [comment]
we merge https://github.com/nextcloud/server/pull/31773 on Monday, so perhaps this could be related

**Comment by PVince81** [comment]
@icewind1991 any update ? did any recent PR fix this ?

**Comment by icewind1991** [comment]
https://github.com/nextcloud/server/pull/31901 fixes the handling of mounts with the `Mountprovider::class` added to the `parent::constructor` call.

**Comment by PVince81** [comment]
@mejo- the PR is merged, please try again with master
