### ISSUE TITLE
[Bug]: config.php empty after occ maintenance:mode --on when disk is full

### ISSUE THREAD

**Issue by mvvvmd** [nextcloud/server#31869]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When the disk is 100% full and the occ command maintenance:mode --on is called the config.php file is overwritten and nearly empty.

### Steps to reproduce

1. Fill the  partition where the config.php is stored to 100%
2. Run `sudo -u www-data php occ maintenance:mode --on`
3. Check config.php

### Expected behavior

If the occ command cannot write because of a lack of disk space it should not attempt to do so, causing the configuration to be lost.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
n/a
```

### List of activated Apps

```shell
n/a
```

### Nextcloud Signing status

```shell
n/a
```

### Nextcloud Logs

```shell
{"reqId":"bosCNWT7ZWEm2r5pVpVF","level":3,"time":"2022-04-06T14:38:21+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"fwrite(): write of 2786 bytes failed with errno=28 No space left on device at /var/www/vhosts/nextcloud/lib/private/Config.php#268","userAgent":"--","version":"23.0.3.2","exception":{"Exception":"Error","Message":"fwrite(): write of 2786 bytes failed with errno=28 No space left on device at /var/www/vhosts/nextcloud/lib/private/Config.php#268","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/vhosts/nextcloud/lib/private/Config.php","line":268,"function":"fwrite"},{"file":"/var/www/vhosts/nextcloud/lib/private/Config.php","line":138,"function":"writeData","class":"OC\\Config","type":"->"},{"file":"/var/www/vhosts/nextcloud/lib/private/SystemConfig.php","line":142,"function":"setValue","class":"OC\\Config","type":"->"},{"file":"/var/www/vhosts/nextcloud/lib/private/AllConfig.php","line":115,"function":"setValue","class":"OC\\SystemConfig","type":"->"},{"file":"/var/www/vhosts/nextcloud/core/Command/Maintenance/Mode.php","line":67,"function":"setSystemValue","class":"OC\\AllConfig","type":"->"},{"file":"/var/www/vhosts/nextcloud/3rdparty/symfony/console/Command/Command.php","line":255,"function":"execute","class":"OC\\Core\\Command\\Maintenance\\Mode","type":"->"},{"file":"/var/www/vhosts/nextcloud/3rdparty/symfony/console/Application.php","line":1009,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->"},{"file":"/var/www/vhosts/nextcloud/3rdparty/symfony/console/Application.php","line":273,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/vhosts/nextcloud/3rdparty/symfony/console/Application.php","line":149,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/vhosts/nextcloud/lib/private/Console/Application.php","line":211,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/vhosts/nextcloud/console.php","line":99,"function":"run","class":"OC\\Console\\Application","type":"->"},{"file":"/var/www/vhosts/nextcloud/occ","line":11,"args":["/var/www/vhosts/nextcloud/console.php"],"function":"require_once"}],"File":"/var/www/vhosts/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
```

### Additional info

I realize having a 100% filled partition is a problem in it self (thanks Elasticsearch +HeapDumpOnOutOfMemoryError by default). We got 500 errors and before realizing the disk was full we set NC in maintenance mode to be save. Finding the config.php empty was surprising, recovered from backup but not something you like to find on a production server you need to get back up asap.

**Comment by tzugen** [comment]
This is probably a duplicate of https://github.com/nextcloud/server/issues/25175

**Comment by mvvvmd** [comment]
Agreed, closed, thanks.
