### ISSUE TITLE
image-optimization.sh: jpegoptim doesn't accept glob patterns; error causes images to be deleted

### ISSUE THREAD

**Issue by SentToDevNull** [nextcloud/server#3186]
### Steps to reproduce
1. Run $NEXTCLOUD_DIR/core/img/image-optimization.sh

### The Issue
Jpegoptim doesn't accept glob patterns (jpegoptim: skipping special file: *.jpg). It doesn't seem to handle errors properly either in that the files matching the glob were deleted instead of left alone.

### Here is a safe replacement you can substitute for the line with jpegoptim:
```
IFS=$'\n'
for f in $(find $(pwd) -maxdepth 1 -name "*.jpg")
do
  jpegoptim --strip-all "$f"
done
```

**Comment by nickvergessen** [comment]
That file should also not be in that directory...
