### ISSUE TITLE
[Bug]: Being clear about Social 

### ISSUE THREAD

**Issue by ShalokShalom** [nextcloud/server#31883]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi :)

Nextcloud currently recommends (in the default Notifications) the Social plugin. 
Not only is it rated at 2 stars, not featured and not stable to use - it is not even runable in the current version. Server 21 or lower is required. 

I question the sense, to recommend a plugin, that can not be used in the first place.
And I can also not image, that it qualifies itself to be on such a prominent place otherwise. 

### Steps to reproduce

1  Install NextCloud
2  Look in the notifications, see the "Social" entry
3  Try to download and use Social. 

### Expected behavior

Social works 

### Installation method

Other

### Operating system

Other

### PHP engine version

Other

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Irrelevant.
```

**Comment by szaimen** [comment]
It is fine by me removing social from the list for now. (and not sending this recommendation anymore)

cc @jancborchardt @AndyScherzinger @karlitschek

**Comment by AndyScherzinger** [comment]
Would be fine with me too
