### ISSUE TITLE
missing entry of email address in oc_users table

### ISSUE THREAD

**Issue by mr-bolle** [nextcloud/server#3188]
### Steps to reproduce
1. Admin Account > Setting > activate 'Show email address'
2. into User Management a new Column 'E-Mail' exist
3. Add a new User or adjust a existing User with the E-Mail Address
4. SQL Request: select * from `oc_users` - only 'uid' 'displayname' 'password' is available

[https://abload.de/img/adminaccount-user-setlns1h.jpg](https://abload.de/img/adminaccount-user-setlns1h.jpg)

### Expected behaviour
Into the oc_users Table the E-Mail Address from the Users should be available

### Actual behaviour
The User Account E-Mail Address is missing into the SQL Table. And that's why it isn't possible to create a Backup of this Information.

### Server configuration
**Operating system**:
Rasbian Debian Jessie - Linux 4.4.38-v7+ on armv7l

**Web server:**
Apache2

**Database:**
MariaDB

**PHP version:**
PHP 5.6.29-0+deb8u1

**Nextcloud version:** (see Nextcloud admin page)
10.0.3 (stable)  - the same behavior i recognize from the previous versions

**Updated from an older Nextcloud/ownCloud or fresh install:**
update from a older install

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by blizzz** [comment]
The email is stored in the preferences table.
