### ISSUE TITLE
[Bug]: ldap logins take a long time and frequently timeout, 504 Bad Gateway

### ISSUE THREAD

**Issue by jamincollins** [nextcloud/server#31885]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I've noticed that when I have to (re)login, authentication takes a long time and frequently fail with a 504 Bad Gateway.

Investigation led me to time the logins and even successful logins tend to take more than 45 seconds to complete.  Oddly, failures (bad username and/or password) responses are almost immediate.

I've checked the LDAP server's response times and watched requests from Nextcloud.  The server respond nearly immediately.

### Steps to reproduce

1. Setup Nextcloud
2. Enable LDAP authentication
3. Try to use LDAP authentication

### Expected behavior

LDAP logins are processed in a timely manner and do not result in 504 Bad Gateway.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "default_phone_region": "US",
        "updatechecker": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.asgardsrealm.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.asgardsrealm.net",
        "dbtype": "mysql",
        "version": "23.0.3.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "loglevel": 1,
        "app.mail.verify-tls-peer": false,
        "appstore.experimental.enabled": true,
        "htaccess.RewriteBase": "\/",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "theme": "",
        "mysql.utf8mb4": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 0
        }
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - calendar: 3.2.2
  - circles: 23.1.0
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.1.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - deck: 1.6.1
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.7
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.4
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - tasks: 0.14.4
  - text: 3.4.1
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.2.0
  - updatenotification: 1.13.0
  - user_ldap: 1.13.1
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - bruteforcesettings: 2.3.0
  - encryption
  - external: 3.10.2
  - files_accesscontrol: 1.13.0
  - files_automatedtagging: 1.13.0
  - files_external
  - files_retention: 1.12.0
  - files_texteditor: 2.14.0
  - talk_matterbridge: 1.23.2
  - templateeditor: 0.2
  - user_external: 1.0.0
  - user_saml: 3.3.1
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Creating the issue fails if I provide these here.
```

**Comment by jamincollins** [comment]
In digging further into this, I found this:
https://stackoverflow.com/a/17511476

Adding the following to my `nginx` `php` configuration _appears_ to have alleviated the **504 Bad Gateway** errors:
```
    fastcgi_read_timeout 180;
```

However, that doesn't explain the _need_ for such a long login validation/response window, especially when an invalid username/password gets an almost immediate response.

I've timed a few fresh logins after making the above change.
T 000:01:17.649
T 000:01:08.032
T 000:01:14.278

By contrast, I've timed a CLI `ldapsearch` (with DN binding) from the system running Nextcloud:

```
real	0m2.282s
user	0m0.027s
sys	0m0.012s
```

The above includes time for me to type in my password.

Providing my password on the CLI results in a far snappier response:
```
real	0m0.069s
user	0m0.024s
sys	0m0.014s
```

I believe this clearly shows that something is happening within Nextcloud that is delaying the acknowledgement and progression of the login.

**Comment by sb0stn** [comment]
We are having the same issues with our instance (Dockerized 24.0.2).

Adding some logs to the methods called in `lib/private/Authentication/Login/Chain.php`, we found that some later steps take a very long time for no apparent reason. This would also explain why failed logins are very quick. From our tests `clearLostPasswordTokensCommand`, `updateLastPasswordConfirmCommand` and `twoFactorCommand` may be related to the issue.

**Comment by nollivier** [comment]
I had the same issue recently. I couldn’t login into my account because the login process took more than 1 minute and the Web server Timeout was set at 1 minute.

I managed to login again after increasing the Web server Timeout. But at this time, it took 3 minutes to login in my account!

But maybe I discovered the cause. Firstly my account was the only affected.
Then, I had 90 session token in my account (caused by the app DEVONthink I tried to sync its data using WebDAV on my Nextcloud) . I deleted all those tokens (following the tip [described on this post](https://help.nextcloud.com/t/disconnect-all-sessions-revoking-access-for-all-apps-of-a-user/37955/2)). After that, login again in my account only take a few seconds, as expected.

So it seems that is you have applications that create too many session tokens, the login process can be slowed down drastically.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by nmo-nollivier** [comment]
@szaimen I updated my Nextcloud tow weeks ago to 25.0.3 and for now, it seems the issue is solved. 

At list, it seems that there is less auth tokens kept in my account. 

I still have about 10 tokens related to Apple Calendar and Reminder apps on iOS, but not older than 1 day. 
Before I updated Nextcloud, I have had around 10 tokens per day, for several days, even weeks.

Thanks!

**Comment by szaimen** [comment]
> I updated my Nextcloud tow weeks ago to 25.0.3 and for now, it seems the issue is solved.

All right. Thanks for verifying!
