### ISSUE TITLE
Zh-CN language error

### ISSUE THREAD

**Issue by LiboGuo** [nextcloud/server#3189]
### Steps to reproduce
1.Select Chinese language
2.
3.

### Expected behaviour
log errord

### Actual behaviour
log error

### Server configuration
**Operating sytem**:windows

**Web server:**linux

**Database:**mysql

**PHP version:**7.0.14

**Nextcloud version:** 11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**yes

**Where did you install Nextcloud from:**The official website

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Warning    l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:54:15+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:54:09+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:40+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:40+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:39+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:39+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/comments/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:39+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:38+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:32+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:32+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:32+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:31+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:31+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:31+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:30+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:30+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:29+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3	2017-01-21T18:53:29+0800
Warning	l10n	Failed to load /var/www/html/cloud/apps/files/l10n/zh_CN.json - json error code: 3</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by go2sh** [comment]
Same here.

**Comment by nickvergessen** [comment]
> Control character error, possibly incorrectly encoded

@MorrisJobke any idea? Are we writing files in a non-utf8 encoding?

**Comment by MorrisJobke** [comment]
> @MorrisJobke any idea? Are we writing files in a non-utf8 encoding?

Error code 3 is JSON_ERROR_CTRL_CHAR. let me check the file.

**Comment by MorrisJobke** [comment]
> @MorrisJobke any idea? Are we writing files in a non-utf8 encoding?

Seems to be an encoding problem. Looks like I need to rewrite this ugly Perl script to be able to fix this.

**Comment by guoyunhe** [comment]
Same issue. Translation files downloaded from Transifex should have the correct encoding. But it is PO file, not JSON file? Transifex support JSON file very well. Maybe here is not need to use PO files, if they won't be used directly.

**Comment by nickvergessen** [comment]
> The text of this item contains an invisible character (ASCII 0x08 BS), which causes language file parsing errors, please unreview and fix it.
这个条目的文本包含一个不可见字符（ASCII 0x08 BS），在语言文件解析时会出错，麻烦取消review然后修正。
> 
> Project: Nextcloud
Resource: files
Language: Chinese (China)

So this seems to be an issue with the string that is in transifex

**Comment by guoyunhe** [comment]
@nickvergessen Can you find which string contains the invisible character?

**Comment by nickvergessen** [comment]
No sorry, I don't have an editor which shows this correctly.

**Comment by MorrisJobke** [comment]
> So this seems to be an issue with the string that is in transifex

Many ... I also tried to fix this on transifex, but hadn't any success 😕

**Comment by helloxinxiang** [comment]
I got the same issue, is there any solutions?

**Comment by nickvergessen** [comment]
Please download the following files and replace the files in `apps/files/l10n/` with those new files:
https://raw.githubusercontent.com/nextcloud/server/stable11/apps/files/l10n/zh_CN.js
https://raw.githubusercontent.com/nextcloud/server/stable11/apps/files/l10n/zh_CN.json

**Comment by nickvergessen** [comment]
We will release a new version next week, so this is fixed soon.

**Comment by guoyunhe** [comment]
I get new errors in contacts app:

Failed to load /srv/www/htdocs/nextcloud/apps/contacts/l10n/zh_CN.json - json error code: 3

Is it another problem?

**Comment by nickvergessen** [comment]
Can't see any error

**Comment by guoyunhe** [comment]
@nickvergessen you need to switch to zh_CN then you may see the error.

JSON error code 3 is JSON_ERROR_CTRL_CHAR, which might caused by wrong encoding. 

http://php.net/manual/function.json-last-error.php

**Comment by nickvergessen** [comment]
well at least the file that is currently in the source has no error.
But you can try to make the following change https://github.com/nextcloud/contacts/commit/45c91676432a6089db4c688d2d256242dceb7690#diff-29d2d44ec1bfe70e0f6748ebc40b8bd6

**Comment by yp05327** [comment]
I have upgraded to 11.0.3(auto upgrade from 11.0.2 to 11.0.3), found that this bug is still available.
Then I opened this file /var/www/html/cloud/apps/files/l10n/zh_CN.json, in line 15, I saw: 

>  "Error occurred while updating comment with id {id}" : "[there is a unknown character]更新 id 为 {id} 的评论出错",

Then I delete the unknown character, and no warning again.
