### ISSUE TITLE
[Bug]: index.php/settings/apps incorrectly shows "All apps are up-to-date." while there is 1 not up-to-date

### ISSUE THREAD

**Issue by march42** [nextcloud/server#31915]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The displayed status for available updates is wrong under some conditions.
- Under "Your apps" and "Updates" shows "All apps are up-to-date." when there is one update available.
- Under "Active apps" shows "All apps are up-to-date." when one and two updates (maybe more) are available.

### Steps to reproduce

1. Nextcloud v23.0.3 and Nextcloud 24.0.0 beta 3
2. 1 or more updates for apps available
3. check index.php/settings/apps etc. for the status line above the apps list

(Your apps, 1 update, 24.0.0 beta 3)
![2022-04-08 (1)](https://user-images.githubusercontent.com/5712929/162565508-d76293c6-e9a5-4e77-a0da-60b0041e134f.png)
(Your apps, 1 update, 23.0.3)
![2022-04-08 (2)](https://user-images.githubusercontent.com/5712929/162565510-7fe59d84-c04e-4be8-88d3-4fc728e30e89.png)
(Active apps, 2 updates)
![2022-04-09 (1)](https://user-images.githubusercontent.com/5712929/162565511-913e89f3-7381-469c-b6a8-11662edecfd9.png)

### Expected behavior

Displaying the actual count of available updates.
![2022-04-09](https://user-images.githubusercontent.com/5712929/162566146-96420557-7e11-4e90-a1f7-966b8d7c7716.png)

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "frija.kleines-miststueck.de",
            "nc.march42.net",
            "march42.net",
            "kleines-miststueck.de",
            "enyo.kleines-miststueck.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.3.2",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "pipe",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "default_language": "de",
        "default_locale": "de_DE",
        "default_phone_region": "DE",
        "logtimezone": "Europe\/Berlin",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": "true",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "timeout": 2,
            "dbindex": 2
        },
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "preview_max_x": 600,
        "preview_max_y": 600,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\TXT",
            "OC\\Preview\\Markdown",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\PDF"
        ],
        "enable_previews": true,
        "filelocking.enabled": true
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.15.0
  - backup: 1.0.6
  - calendar: 3.2.2
  - circles: 23.1.0
  - cloud_federation_api: 1.6.0
  - contacts: 4.1.0
  - contactsinteraction: 1.4.0
  - dav: 1.21.0
  - deck: 1.6.1
  - duplicatefinder: 0.0.13
  - event_update_notification: 1.5.0
  - external: 3.10.2
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_external: 1.15.0
  - files_pdfviewer: 2.4.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - fileslibreofficeedit: 1.0.4
  - groupfolders: 11.1.2
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.7
  - metadata: 0.15.0
  - notes: 4.3.1
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - previewgenerator: 4.0.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.5
  - systemtags: 1.13.0
  - text: 3.4.1
  - theming: 1.14.0
  - transfer: 0.2.1
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_ldap: 1.13.1
  - user_status: 1.3.1
  - viewer: 1.7.0
  - workflowengine: 2.5.0
Disabled:
  - accessibility: 1.9.0
  - admin_audit
  - comments: 1.13.0
  - dashboard: 7.3.0
  - encryption
  - files_antivirus: 3.2.2
  - files_rightclick: 1.2.0
  - firstrunwizard: 2.12.0
  - gpgmailer: 0.0.4
  - nextcloud_announcements: 1.12.0
  - recommendations: 1.2.0
  - richdocuments: 5.0.3
  - richdocumentscode: 21.11.204
  - support: 1.6.0
  - survey_client: 1.11.0
  - weather_status: 1.3.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"MQVHJoaOfUlBNJuttNuN","level":3,"time":"2022-04-08T23:22:15+02:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"OC_Image::fixOrientation(): No image loaded","userAgent":"--","version":"23.0.3.2"}
{"reqId":"MQVHJoaOfUlBNJuttNuN","level":3,"time":"2022-04-08T23:22:18+02:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"OC_Image::fixOrientation(): No image loaded","userAgent":"--","version":"23.0.3.2"}
```

**Comment by JordanDIG** [comment]
I also have the same problem on the 2 instances in version 23.0.3 and nextcloud 24 in beta 2

**Comment by tflidd** [comment]
I can confirm the issue for NC24RC1.

On NC 22.2.6, I don't have the problem on a similar setup.

**Comment by szaimen** [comment]
When this is happening since 23.0.3 too it must be something that was backported to 23...

**Comment by szaimen** [comment]
Question: does it show the update all button when 2 or 3 apps have updates available?

**Comment by szaimen** [comment]
We might be able to fix it by changing this https://github.com/nextcloud/server/blob/70c811742ecc722519c63a6120e5f51d1083cfd5/apps/settings/src/components/AppList.vue#L123
to 
```
return this.apps.filter(app => app.update).length > 0
```

**Comment by szaimen** [comment]
cc @skjnldsv would the above be a good fix or is it not expected that the update all button shows up if only one app update is available?

**Comment by szaimen** [comment]
we should probably also add enabled here: https://github.com/nextcloud/server/blob/70c811742ecc722519c63a6120e5f51d1083cfd5/apps/settings/src/components/AppList.vue#L126

**Comment by szaimen** [comment]
fix in https://github.com/nextcloud/server/pull/32114
