### ISSUE TITLE
[Bug]: unable to receive emails

### ISSUE THREAD

**Issue by laurentvv** [nextcloud/server#31919]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I use sendmail mode for sending emails.
No email is received. Yet I see the log in mailog (postfix) sending successful (not in spam).
I tested with a python script by also sending by the localhost relay the mail is well received.
I don't understand where the problem comes from.

### Steps to reproduce

'mail_smtpmode' => 'sendmail',
'mail_smtphost' => '127.0.0.1',
'mail_smtpport' => '25',
'mail_smtptimeout' => 10,
'mail_smtpauthtype' => 'LOGIN',
'mail_from_address' => 'my_account',
'mail_sendmailmode' => 'smtp',
 'mail_domain' => 'orange.fr',

### Expected behavior

I would like to receive emails

### Installation method

Manual installation

### Operating system

RHEL/CentOS

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.laurentv.camdvr.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.3.2",
        "overwrite.cli.url": "http:\/\/nextcloud.laurentv.camdvr.org",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_phone_region": "FR",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "mail_smtpmode": "sendmail",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtptimeout": 10,
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - bruteforcesettings: 2.3.0
  - calendar: 3.2.2
  - circles: 23.1.0
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.1.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_antivirus: 3.2.2
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - geoblocker: 0.5.4
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.7
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - richdocuments: 5.0.3
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.5
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.1
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional info

none

**Comment by laurentvv** [comment]
postfix log with no error indicated, "satus:sent" but never received when sent by nextcloud...
it's ok with my python script test

Apr 10 12:19:37 nextcloud postfix/master[73289]: daemon started -- version 3.5.8, configuration /etc/postfix
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: connect from localhost[127.0.0.1]
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: smtp_stream_setup: maxtime=300 enable_deadline=0
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: name_mask: chunking
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: > localhost[127.0.0.1]: 220 nextcloud.localdomain ESMTP Postfix
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: watchdog_pat: (nil)
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: < localhost[127.0.0.1]: HELO nextcloud.**HIDE**
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: > localhost[127.0.0.1]: 250 nextcloud.localdomain
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: watchdog_pat: (nil)
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: < localhost[127.0.0.1]: MAIL FROM:<**HIDE**@orange.fr>
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: extract_addr: input: <**HIDE**@orange.fr>
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: extract_addr: in: <**HIDE**@orange.fr>, result: **HIDE**@orange.fr
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: > localhost[127.0.0.1]: 250 2.1.0 Ok
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: watchdog_pat: (nil)
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: < localhost[127.0.0.1]: RCPT TO:<**HIDE**@gmail.com>
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: extract_addr: input: <**HIDE**@gmail.com>
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: extract_addr: in: <**HIDE**@gmail.com>, result: **HIDE**@gmail.com
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: /usr/sbin/postdrop -v: wanted attribute: queue_id
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: input attribute name: queue_id
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: input attribute value: B62C0182014CA
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: /usr/sbin/postdrop -v: wanted attribute: (list terminator)
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: input attribute name: (end)
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: B62C0182014CA: client=localhost[127.0.0.1]
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: > localhost[127.0.0.1]: 250 2.1.5 Ok
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: watchdog_pat: (nil)
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: < localhost[127.0.0.1]: DATA
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: > localhost[127.0.0.1]: 354 End data with <CR><LF>.<CR><LF>
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: /usr/sbin/postdrop -v: wanted attribute: status
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: input attribute name: status
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: input attribute value: 0
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: /usr/sbin/postdrop -v: wanted attribute: reason
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: input attribute name: reason
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: input attribute value: (end)
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: /usr/sbin/postdrop -v: wanted attribute: (list terminator)
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: input attribute name: (end)
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: > localhost[127.0.0.1]: 250 2.0.0 Ok: queued as B62C0182014CA
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: watchdog_pat: (nil)
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: < localhost[127.0.0.1]: QUIT
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: > localhost[127.0.0.1]: 221 2.0.0 Bye
Apr 10 12:19:50 nextcloud postfix/smtpd[73303]: disconnect from localhost[127.0.0.1] helo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
Apr 10 12:19:50 nextcloud postfix/pickup[73290]: BCBAB100D2CBA: uid=48 from=<**HIDE**@orange.fr>
Apr 10 12:19:50 nextcloud postfix/cleanup[73307]: BCBAB100D2CBA: message-id=<3ff440e8b98e98a9d8f4008ed92b3a18@nextcloud.**HIDE**>
Apr 10 12:19:50 nextcloud postfix/qmgr[73291]: BCBAB100D2CBA: from=<**HIDE**@orange.fr>, size=16259, nrcpt=1 (queue active)
Apr 10 12:19:51 nextcloud postfix/smtp[73309]: BCBAB100D2CBA: to=<**HIDE**@gmail.com>, relay=smtp.orange.fr[193.252.22.84]:25, delay=0.73, delays=0.11/0.07/0.28/0.28, dsn=2.0.0, status=sent (250 2.0.0 dUffnkIhwEtmXdUffnpNLh mail accepted for delivery)
Apr 10 12:19:51 nextcloud postfix/qmgr[73291]: BCBAB100D2CBA: removed

**Comment by laurentvv** [comment]
Python Scrpit : email sent email received

same SERVER, same "FROM" address and same "TO" address that nextloud config


#!/usr/bin/python

import smtplib

sender = '**HIDE**@orange.fr'
receivers = ['**HIDE**@gmail.com']

message = """From: From **HIDE** <**HIDE**@orange.fr>
To: To **HIDE**@gmail.com <**HIDE**@gmail.com>
Subject: SMTP e-mail test

This is a test e-mail message.
"""

try:
   smtpObj = smtplib.SMTP('localhost')
   smtpObj.sendmail(sender, receivers, message)
   print("Successfully sent email")
except SMTPException:
   print("Error: unable to send email")

**Comment by laurentvv** [comment]
Test with another smtp (free.fr):
Nextloud : Test parameter = SPAM detected

Apr 15 12:29:57 nextcloud postfix/pickup[140050]: C4AA31003A30F: uid=48 from=<**HIDE**@free.fr>
Apr 15 12:29:57 nextcloud postfix/cleanup[140060]: C4AA31003A30F: message-id=<bc8c8b00d680bedce4af335049c9bb36@**HIDE**>
Apr 15 12:29:57 nextcloud postfix/cleanup[140060]: C4AA31003A30F: warning: header Subject: Test des =?utf-8?Q?param=C3=A8tres?= e-mail from local; from=<**HIDE**@free.fr> to=<**HIDE**@gmail.com>
Apr 15 12:29:57 nextcloud postfix/cleanup[140060]: C4AA31003A30F: warning: header From: Nextcloud <**HIDE**@free.fr> from local; from=<**HIDE**@free.fr> to=<**HIDE**@gmail.com>
Apr 15 12:29:57 nextcloud postfix/cleanup[140060]: C4AA31003A30F: warning: header To: adminlaurent <**HIDE**@gmail.com> from local; from=<**HIDE**@free.fr> to=<**HIDE**@gmail.com>
Apr 15 12:29:57 nextcloud postfix/qmgr[140051]: C4AA31003A30F: from=<**HIDE**@free.fr>, size=16261, nrcpt=1 (queue active)
Apr 15 12:29:58 nextcloud postfix/smtp[140055]: C4AA31003A30F: to=<**HIDE**@gmail.com>, relay=smtp.free.fr[2a01:e0c:1::25]:587, delay=0.36, delays=0.01/0/0.25/0.1, dsn=5.7.1, status=bounced (host smtp.free.fr[2a01:e0c:1::25] said: 550 5.7.1 Spam Detected - Mail Rejected.  Please see our policy at: http://postmaster.free.fr/#spam_detected (in reply to end of DATA command))
Apr 15 12:29:58 nextcloud postfix/bounce[140070]: C4AA31003A30F: sender non-delivery notification: 2B31210039950
Apr 15 12:29:58 nextcloud postfix/qmgr[140051]: C4AA31003A30F: removed

Test with python script : No spam detected

Why ?

**Comment by onny** [comment]
Does this mean sending works via Nextcloud + Sendmail but you don't receive the mail? Is the mail rejected by the recipient because of spam? In this case this would be an issue with your Smtp/Mail provider and or the recipient and not specially an issue with Nextcloud.
I guess most providers will reject Nextcloud messeges send by a freemail provider because this is usally an indication for spam but not sure about this

**Comment by laurentvv** [comment]
In Nexcloud :
Test Parameter : mail ok
Update App notification : mail ok
usage statistics: not ok and not in spam
user notification : not ok  and not in spam

I don't see where it's blocking and I can clearly see the emails having the status sent in postfix

**Comment by laurentvv** [comment]
with the latest version I have no problem

**Comment by szaimen** [comment]
> with the latest version I have no problem

thanks for checking
