### ISSUE TITLE
Upload of files >20 MB fails: Connection to server lost

### ISSUE THREAD

**Issue by pejakm** [nextcloud/server#3191]
I rented web hosting and installed NextCloud 11, just to find out I cannot upload larger files (from what I've noticed, larger than 20 MiB).
'Files' application inside my NextCloud instance reports `Connection to server lost`, and my webdav client reports `Connection terminated`. Uploading via ftp is okay.

My hosting details: unlimited bandwidth, 10 processes, 1 GiB RAM and 10 GiB of disk space. 

Server details:

PHP
Version: 7.0.14
Memory Limit: 256.0 MB
Max Execution Time: 3600
Upload max size: 256.0 MB

Database
Type: mysql
Version: 5.6.33
Size: 7.5 MB

Note: My upload is ~80 KiB, so a 20 MiB file should be uploaded for ~4.5 minutes.
Note 2: No error whatsoever reported in my cpanel instance or NextCloud's admin account.

**Comment by pejakm** [comment]
Follow-up: after research I found out that `mod_security` can interfere with the upload. I've put:

```
<IfModule mod_security.c>
   SecFilterEngine Off
   SecFilterScanPOST Off
</IfModule>
```
to .htaccess file, but it didn't help, unfortunately. I have also turned off `output_buffering`.

**Comment by nickvergessen** [comment]
Please provide the log information as requested by the issue template.

**Comment by pejakm** [comment]
```
No server logs

Everything is working fine
```

That's the log from my Nextcloud instance. I can't get you server logs, I bought web hosting, there isn't option in Cpanel to access those (other than access logs, but I don't then they are relevant). The only thing I can think of is that my host is limiting resources (cpu usage). There is Cpanel module named "CPU and concurent connection usage" where i can see:

```
Your site has been limited within the past 24 hours
CPU resources were limited for your site
```
notice. Unfortunately, the graph display is not working at this time, so I cannot see the exact time the limitation has occurred, but I am almost certain that upload has responsible for what my hoster characterized as "100% cpu usage".

I need to note here that I asked them to turn off `mod_security` for my website, and they did, but this problem still remains.

Please let me know if I can do anything else here to get to the bottom of this problem.

**Comment by pejakm** [comment]
Other info:

```
Resource Limits	max_execution_time		60
Resource Limits	max_input_time		60
Resource Limits	memory_limit		64M
```

**Comment by pejakm** [comment]
I've created a php upload test page, and I can reproduce the problem. Meaning this isn't related to Nextcloud, but to my web hosting service. I apologize for your time, and thanks for your help.
