### ISSUE TITLE
[Bug]: latest version 23.0.3 can not install on Ubuntu 22.04 as it requires PHP v8.0 but Ubuntu 22.04 comes with v8.1.2

### ISSUE THREAD

**Issue by rdelangh** [nextcloud/server#31953]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

- installed a new Ubuntu server with v22.04
- this has PHP v8.1.2
- downloaded latest Nextcloud server bundle, which is version 23.0.3
- "occ" command or web interface to config fails with 

This version of Nextcloud is not compatible with > PHP 8.0. You are currently running 8.1.2.

Installing an older release of PHP on Ubuntu 22.04, such as PHP v7.4 , is not possible due to conflicts with other Ubuntu package versions.

### Steps to reproduce

1. install Ubuntu 22.04
2. install PHP (which is v8.1.2)
3. install latest Nextcloud server bundle (which is v23.0.3)
4. run the "occ maintenance:install"

### Expected behavior

Latest Nextcloud server bundle, should support latest PHP versions of Ubuntu 22.04 ; 

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
# sudo -u www-data php occ config:list system
This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.2.
# php occ config:list system
This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.2.
# ./occ config:list system
This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.2.
```

### List of activated Apps

```shell
# sudo -u www-data php occ app:list
This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.2.
# php occ app:list
This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.2.
# ./occ app:list
This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.2.
```

### Additional info

Related to #29287

**Comment by szaimen** [comment]
So I would close this because NC24 is out now...
