### ISSUE TITLE
Show reset to default button for theming values on hover

### ISSUE THREAD

**Issue by claell** [nextcloud/server#3198]
When in the Theming section of administration there are "restore to default" options offered when changing the logo or Login image. When changing other theming settings this is not offered.
![bildschirmfoto vom 2017-01-22 21-00-20](https://cloud.githubusercontent.com/assets/6171135/22185984/460cb6ca-e0ef-11e6-8516-7601edaca520.png)

At least for the color it would make sense to also offer a reset button.

**Comment by schiessle** [comment]
You need to click into the input field to see the undo buttons inline (only if the input doesn't contain the default value).

cc @nextcloud/designers I think we should show the undo button on hover otherwise it is really hard to discover.

**Comment by eppfel** [comment]
👍 For onHover.
"Always show reset button" was dismissed before (too lazy to search for the discourse), but I am open to it.
@nextcloud/theming

**Comment by MorrisJobke** [comment]
> too lazy to search for the discourse

#770 and #1049

**Comment by claell** [comment]
Ah, did not expected it to be in the input field.

From a user perspective I expected a "pattern". All existing reset buttons are placed on the right or on top of the changed element, so I did not search for it in the input field (and maybe it would make sense to have every button at a similar position).

Regardless showing it when hovering over it or always showing it will improve the current situation.

**Comment by jancborchardt** [comment]
Yeah, also showing the reset function on hover makes a lot of sense. What do you think @juliushaertl?

**Comment by jancborchardt** [comment]
Pull request at https://github.com/nextcloud/server/pull/5319, please review :)
