### ISSUE TITLE
PRs fixing the stable24 branch-off in apps

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#31982]
# Updating the testing target in stable24 branches

🗒️ **Note:** Failing test for `psalm` + `dev-stable24` are currently expected and a force merge needs to happen for the time-being until https://github.com/ChristophWurst/nextcloud_composer has been bumped to serve a stable24 dev branch

- [x] https://github.com/nextcloud/activity/pull/785
- [x] https://github.com/nextcloud/circles/pull/1021
- [x] https://github.com/nextcloud/firstrunwizard/pull/701
- [x] https://github.com/nextcloud/logreader/pull/695
- [x] https://github.com/nextcloud/nextcloud_announcements/pull/100
- [x] https://github.com/nextcloud/notifications/pull/1185
- [x] https://github.com/nextcloud/password_policy/pull/350
- [x] https://github.com/nextcloud/photos/pull/1078
- [x] https://github.com/nextcloud/privacy/pull/758
- [x] https://github.com/nextcloud/serverinfo/pull/368
- [x] https://github.com/nextcloud/survey_client/pull/132
- [x] https://github.com/nextcloud/text/pull/2296
- [x] https://github.com/nextcloud/announcementcenter/pull/459
- [x] https://github.com/nextcloud/data_request/pull/69
- [x] https://github.com/nextcloud/deck/pull/3723
- [x] https://github.com/nextcloud/end_to_end_encryption/pull/293
- [x] https://github.com/nextcloud/files_accesscontrol/pull/238
- [x] https://github.com/nextcloud/files_automatedtagging/pull/557
- [x] https://github.com/nextcloud/files_retention/pull/163
- [x] https://github.com/nextcloud/groupfolders/pull/1952
- [x] https://github.com/nextcloud/impersonate/pull/159
- [x] https://github.com/nextcloud/ldap_contacts_backend/pull/40
- [x] https://github.com/nextcloud/ldap_write_support/pull/470
- [x] https://github.com/nextcloud/quota_warning/pull/101
- [x] https://github.com/nextcloud/sharepoint/pull/135
- [x] https://github.com/nextcloud/spreed/pull/7156
- [ ] https://github.com/nextcloud/user_usage_report/pull/89
- [x] https://github.com/nextcloud/files_antivirus/pull/228
- [ ] https://github.com/nextcloud/files_downloadactivity/pull/90
- [x] https://github.com/nextcloud/forms/pull/1169
- [x] https://github.com/nextcloud/officeonline/pull/296
- [ ] https://github.com/nextcloud/quota_warning/pull/102
- [x] https://github.com/nextcloud/registration/pull/420
- [x] https://github.com/nextcloud/twofactor_totp/pull/1204
- [ ] https://github.com/nextcloud/twofactor_u2f/pull/1004
- [x] https://github.com/nextcloud/user_oidc/pull/419
- [x] https://github.com/nextcloud/user_saml/pull/601
- [x] https://github.com/nextcloud/contacts/pull/2713
- [x] https://github.com/nextcloud/mail/pull/6250
- [x] https://github.com/nextcloud/notify_push/pull/165
- [x] https://github.com/nextcloud/twofactor_webauthn/pull/160
- [x] https://github.com/nextcloud/calendar/pull/4154
- [x] https://github.com/nextcloud/user_migration/pull/120

**Comment by nickvergessen** [comment]
# Bump Nextcloud requirement (and version for stable*-branch apps)

- [ ] https://github.com/nextcloud/activity/pull/786
- [ ] https://github.com/nextcloud/circles/pull/1022
- [ ] https://github.com/nextcloud/files_pdfviewer/pull/591
- [ ] https://github.com/nextcloud/files_rightclick/pull/136
- [ ] https://github.com/nextcloud/files_videoplayer/pull/269
- [ ] https://github.com/nextcloud/firstrunwizard/pull/702
- [ ] https://github.com/nextcloud/logreader/pull/696
- [ ] https://github.com/nextcloud/nextcloud_announcements/pull/101
- [ ] https://github.com/nextcloud/notifications/pull/1186
- [ ] https://github.com/nextcloud/password_policy/pull/351
- [ ] https://github.com/nextcloud/photos/pull/1079
- [ ] https://github.com/nextcloud/privacy/pull/759
- [ ] https://github.com/nextcloud/recommendations/pull/512
- [ ] https://github.com/nextcloud/serverinfo/pull/369
- [ ] https://github.com/nextcloud-gmbh/support/pull/137
- [ ] https://github.com/nextcloud/survey_client/pull/133
- [ ] https://github.com/nextcloud/text/pull/2297
- [ ] https://github.com/nextcloud/user_migration/pull/121
- [ ] https://github.com/nextcloud/viewer/pull/1212
- [ ] https://github.com/nextcloud/backup/pull/267
- [ ] https://github.com/nextcloud/data_request/pull/70
- [ ] https://github.com/nextcloud/deck/pull/3724
- [ ] https://github.com/nextcloud/end_to_end_encryption/pull/294
- [ ] https://github.com/nextcloud/external/pull/297
- [ ] https://github.com/nextcloud/files_accesscontrol/pull/239
- [ ] https://github.com/nextcloud/files_automatedtagging/pull/558
- [ ] https://github.com/nextcloud/files_fulltextsearch/pull/155
- [ ] https://github.com/nextcloud/files_retention/pull/164
- [ ] https://github.com/nextcloud/flow_notifications/pull/49
- [ ] https://github.com/nextcloud/fulltextsearch/pull/681
- [ ] https://github.com/nextcloud/fulltextsearch_elasticsearch/pull/181
- [ ] https://github.com/nextcloud/groupfolders/pull/1953
- [ ] https://github.com/nextcloud/impersonate/pull/160
- [ ] https://github.com/nextcloud/ldap_contacts_backend/pull/41
- [ ] https://github.com/nextcloud/ldap_write_support/pull/471
- [ ] https://github.com/nextcloud/profiler/pull/15
- [ ] https://github.com/nextcloud/sharepoint/pull/136
- [ ] https://github.com/nextcloud/spreed/pull/7157
- [ ] https://github.com/nextcloud/terms_of_service/pull/716
- [ ] https://github.com/nextcloud/user_retention/pull/435
- [ ] https://github.com/nextcloud/user_usage_report/pull/90
- [ ] https://github.com/nextcloud/workflow_pdf_converter/pull/391
- [ ] https://github.com/nextcloud/workflow_script/pull/116

## No version bump required from here on
- [ ] https://github.com/nextcloud/bruteforcesettings/pull/362
- [ ] https://github.com/nextcloud/files_antivirus/pull/229
- [ ] https://github.com/nextcloud/files_downloadactivity/pull/91
- [ ] https://github.com/nextcloud/files_downloadlimit/pull/87
- [ ] https://github.com/nextcloud/files_texteditor/pull/563
- [ ] https://github.com/nextcloud/files_zip/pull/70
- [ ] https://github.com/nextcloud/forms/pull/1170
- [ ] https://github.com/nextcloud/globalsiteselector/pull/67
- [ ] https://github.com/nextcloud/guests/pull/883
- [ ] https://github.com/nextcloud/integration_discourse/pull/29
- [ ] https://github.com/nextcloud/integration_github/pull/37
- [ ] https://github.com/nextcloud/integration_gitlab/pull/41
- [ ] https://github.com/nextcloud/integration_google/pull/105
- [ ] https://github.com/nextcloud/integration_jira/pull/30
- [ ] https://github.com/nextcloud/integration_mastodon/pull/25
- [ ] https://github.com/nextcloud/integration_moodle/pull/34
- [ ] https://github.com/nextcloud/integration_reddit/pull/26
- [ ] https://github.com/nextcloud/integration_twitter/pull/33
- [ ] https://github.com/nextcloud/integration_whiteboard/pull/49
- [ ] https://github.com/nextcloud/integration_zammad/pull/28
- [ ] https://github.com/nextcloud/jsloader/pull/28
- [ ] https://github.com/nextcloud/notify_push/pull/166
- [ ] https://github.com/nextcloud/officeonline/pull/297
- [ ] https://github.com/nextcloud/quota_warning/pull/103
- [ ] https://github.com/nextcloud/ransomware_protection/pull/116
- [ ] https://github.com/nextcloud/registration/pull/421
- [ ] https://github.com/nextcloud/richdocuments/pull/2151
- [ ] https://github.com/nextcloud/social/pull/1371
- [ ] https://github.com/nextcloud/suspicious_login/pull/636
- [ ] https://github.com/nextcloud/talk_matterbridge/pull/68
- [ ] https://github.com/nextcloud/twofactor_totp/pull/1205
- [ ] https://github.com/nextcloud/twofactor_u2f/pull/1005
- [ ] https://github.com/nextcloud/twofactor_webauthn/pull/161

**Comment by ChristophWurst** [comment]
> Update version on main/master

Nitpick: how about "Add Nextcloud xy support" as PR title for the next round of automated PRs. Just to give the notification title more meaning and easy people's lives who have to read through PR titles to create a changelog :)

**Comment by nickvergessen** [comment]
> Nitpick: how about "Add Nextcloud xy support"

Updated my script 😎

**Comment by nickvergessen** [comment]
Majority is merged, so I will close this meta issue.

**Comment by nickvergessen** [comment]
Thanks everyone for the reviews and merges 🚀
