### ISSUE TITLE
[Bug]: Nextcloud did remove almost all user files versions in one touch - also such ones, which were only some days old

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/server#32017]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Server configuration detail

Operating system: Linux 4.18.0-348.20.1.el8_5.x86_64 #1 SMP Tue Mar 8 12:56:54 EST 2022 x86_64

Webserver: Apache (fpm-fcgi)

Database: mysql 10.3.28

PHP version: 7.4.26

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, xmlreader, zip, apcu, igbinary, imagick, msgpack, smbclient, memcached, redis, libsmbclient, Zend OPcache

Nextcloud version: 23.0.3 - 23.0.3.2

Updated from an older Nextcloud/ownCloud or fresh install:
Upgrade from previous version: 22.2.6.2
Where did you install Nextcloud from: origin NC source

Encryption: no

User-backends:

OC\User\Database

Talk configuration:

STUN servers

www.xxxx:3478

TURN servers

turn:www.xxxx:xxxx- udp,tcp

Signaling servers (mode: internal):

no custom server configured

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36 Edg/99.0.1150.36

### Steps to reproduce

1. User exceeds 50% of the his currently available free space
2. As expected (If the stored versions exceed this limit, Nextcloud deletes the oldest file versions until it meets the disk space limit again) user file versions will be deleted

3. The Total amount of user space available: 50GB
    The Total amount of user space used      : 22 GB (without the files versions); Date:17.4.2022/16:00
4.  The Total amount of user space used + files versions ~ 37GB - so the remove action of the files versions is expected
5. There is no special setting about 'versions_retention_obligation' in config.php, so the default value of 'auto' is assumed 

What happend: 

Nextcloud did remove almost all versions in one touch - also such ones, which were only some days old (and which are important for the user).

To analyse this behave, i did create some kind of snap-Clones onto the mirrored Storage to check the situation. 
And this is the result:

snap1restore: (this "Build" has got the full size of the files versions)
17.4.2022-16:00 userx/files_versions
Files:6549
Size:15GB
-------------------------------------------
**snap2restore: (within this "Build" almost all Versions are removed,  (only 36K available !!).
17.4.2022-17:00 userx/files_versions
Files:977
Size:36K**

Other users currently are not affected (i think, because they didn't hit the 50% Limit trigger yet).

Additional questions:

- i did not find the entries about the delete action into the nextcloud.log (could be i missed them !?). 
- Where can i find such information ?

### Expected behavior

The Files Versions app should remove the oldest files versions only and should not touch (remove) the newest ones, when the
delete action is already successful (means: User does not exceed 50% of his currently available free space anymore)

In this used case, the Total Amount of used space after the remove action is 19.9 GB, which is 39.8% of the Total space; 
In my eyes, Nextcloud did remove 5.1GB too much - but may be i missed some dependencies.

Thank you.
Best Mike

### Installation method

manual install (upgraded frm previous version)

### Operating system

Operating system: Linux 4.18.0-348.20.1.el8_5.x86_64 #1 SMP Tue Mar 8 12:56:54 EST 2022 x86_64

### PHP engine version

PHP version: 7.4.26

### Web server

Apache (fpm-fcgi)_

### Database engine version

 mysql 10.3.28

### Is this bug present after an update or on a fresh install?

upgrade from 22.2.6.2 to 23.0.3

### Are you using the Nextcloud Server Encryption module?

no

### What user-backends are you using?

- [x ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
<details><summary>Configuration (config/config.php)</summary>

{
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": true,
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "dbindex": 0,
        "timeout": 1.5,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "xxxx",
        "xxxx"
    ],
    "overwrite.cli.url": "https:\/\/www.xxxx",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "htaccess.RewriteBase": "\/",
    "overwriteprotocol": "https",
    "dbtype": "mysql",
    "version": "23.0.3.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "auth.bruteforce.protection.enabled": true,
    "check_for_working_htaccess": true,
    "updater.release.channel": "stable",
    "data-fingerprint": "aae0353ba8b8c18521f0b4955469111a",
    "logfile": "\/media\/log\/nextcloud.log",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "xxx",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "xxx",
    "session_lifetime": 1200,
    "session_keepalive": false,
    "logtimezone": "Europe\/xxx",
    "default_phone_region": "xxx",
    "knowledgebaseenabled": false,
    "log_rotate_size": 3145728,
    "mail_sendmailmode": "smtp",
    "app_install_overwrite": [
        "passman",
        "dicomviewer",
        "radio",
        "cookbook",
        "health"
    ]
}
```

### List of activated Apps

```shell
Enabled:
 - accessibility: 1.9.0
 - activity: 2.15.0
 - analytics: 4.2.1
 - announcementcenter: 6.1.1
 - apporder: 0.15.0
 - audioplayer: 3.3.0
 - audioplayer_sonos: 1.3.0
 - bookmarks: 10.2.1
 - breezedark: 23.2.1
 - bruteforcesettings: 2.4.0
 - calendar: 3.2.2
 - circles: 23.1.0
 - cloud_federation_api: 1.6.0
 - cms_pico: 1.0.18
 - collectives: 1.0.0
 - comments: 1.13.0
 - contacts: 4.1.0
 - contactsinteraction: 1.4.0
 - cookbook: 0.9.11
 - cospend: 1.4.6
 - dashboard: 7.3.0
 - data_request: 1.10.0
 - dav: 1.21.0
 - deck: 1.6.1
 - dicomviewer: 1.2.3
 - documentserver_community: 0.1.12
 - drawio: 1.0.2
 - electronicsignatures: 1.10.1
 - end_to_end_encryption: 1.9.1
 - event_update_notification: 1.5.0
 - extract: 1.3.3
 - federatedfilesharing: 1.13.0
 - federation: 1.13.0
 - files: 1.18.0
 - files_antivirus: 3.2.2
 - files_automatedtagging: 1.13.0
 - files_downloadactivity: 1.13.0
 - files_external: 1.15.0
 - files_markdown: 2.3.6
 - files_mindmap: 0.0.26
 - files_pdfviewer: 2.4.0
 - files_photospheres: 1.23.0
 - files_rightclick: 1.2.0
 - files_sharing: 1.15.0
 - files_trashbin: 1.13.0
 - files_versions: 1.16.0
 - files_videoplayer: 1.12.0
 - firstrunwizard: 2.12.0
 - forms: 2.5.0
 - gpxpod: 4.3.0
 - groupfolders: 11.1.2
 - health: 1.5.0
 - impersonate: 1.10.0
 - integration_discourse: 1.0.2
 - integration_dropbox: 1.0.4
 - integration_github: 1.0.2
 - integration_gitlab: 1.0.3
 - integration_google: 1.0.6
 - integration_jira: 1.0.2
 - integration_mastodon: 1.0.2
 - integration_moodle: 1.0.2
 - integration_openproject: 1.0.6
 - integration_reddit: 1.0.3
 - integration_suitecrm: 1.0.3
 - integration_twitter: 1.0.2
 - integration_zammad: 1.0.3
 - logreader: 2.8.0
 - lookup_server_connector: 1.11.0
 - maps: 0.1.10
 - nextcloud_announcements: 1.12.0
 - notes: 4.3.1
 - notifications: 2.11.1
 - oauth2: 1.11.0
 - onlyoffice: 7.3.2
 - passman: 2.4.0
 - password_policy: 1.13.0
 - photos: 1.5.0
 - polls: 3.5.4
 - privacy: 1.7.0
 - provisioning_api: 1.13.0
 - quicknotes: 0.7.3
 - quota_warning: 1.14.0
 - rainloop: 7.2.2
 - ransomware_protection: 1.13.0
 - recommendations: 1.2.0
 - serverinfo: 1.13.0
 - settings: 1.5.0
 - sharebymail: 1.13.0
 - socialsharing_diaspora: 2.5.0
 - socialsharing_email: 2.5.0
 - socialsharing_facebook: 2.5.0
 - socialsharing_twitter: 2.5.0
 - spreed: 13.0.5
 - support: 1.6.0
 - systemtags: 1.13.0
 - talk_matterbridge: 1.23.2
 - tasks: 0.14.4
 - terms_of_service: 1.9.3
 - text: 3.4.1
 - theming: 1.14.0
 - timemanager: 0.2.9
 - twofactor_backupcodes: 1.12.0
 - twofactor_totp: 6.2.0
 - updatenotification: 1.13.0
 - user_status: 1.3.1
 - video_converter: 1.0.4
 - viewer: 1.7.0
 - weather_status: 1.3.0
 - welcome: 1.0.1
 - workflow_media_converter: 1.3.6
 - workflow_ocr: 1.23.2
 - workflow_pdf_converter: 1.8.0
 - workflow_script: 1.8.0
 - workflowengine: 2.5.0
Disabled:
 - admin_audit: 1.6.0
 - audioplayer_editor: 0.3.0
 - drop_account: 2.0.0
 - encryption
 - external: 3.10.2
 - files_3d: 0.5.0
 - files_accesscontrol: 1.13.0
 - files_external_onedrive: 1.1.0
 - files_fulltextsearch: 23.0.1
 - flow_notifications: 1.2.0
 - flowupload: 1.1.3
 - fulltextsearch: 23.0.0
 - fulltextsearch_elasticsearch: 23.0.0
 - gpxedit: 0.0.14
 - gpxmotion: 0.1.0
 - integration_onedrive: 1.1.2
 - integration_whiteboard: 0.0.14
 - issuetemplate: 0.7.0
 - joplin: 0.0.25
 - ojsxc: 5.0.0
 - passwords: 2022.4.10
 - podcast: 0.3.1
 - registration: 1.4.0
 - side_menu: 2.3.5
 - social: 0.4.2
 - socialsharing_googleplus: 1.0.4
 - survey_client: 1.3.0
 - talked: 0.3.0
 - user_ldap
 - weather: 1.7.6
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
