### ISSUE TITLE
File Delete Confirmation Dialog

### ISSUE THREAD

**Issue by HaziFlorinMarian** [nextcloud/server#32011]
**Is your feature request related to a problem? Please describe.**
When we right-click on the files we have the last two options from the "Download" and "Delete" list. It is very common for our users to click "Delete" instead of "Download" and the files are deleted directly.

**Describe the solution you'd like**
When we click on "Delete" a popup window will open asking us to confirm if we really want to delete.

**Describe alternatives you've considered**
The "Download" and "Delete" buttons are no longer below each other.

**Additional context**
It's not necessary.

**Comment by szaimen** [comment]
Cc @nimishavijay @jancborchardt

**Comment by killerbees19** [comment]
A confirmation dialog is as much more important if `files_versions` are disabled!

Please implement such a feature at minimum as optional (configurable) setting.

**Comment by giang13297** [comment]
Hi Guys,
Any update for this feature.
Please!!!!

**Comment by delacosta456** [comment]
hi 
i also want to request for this feature and mention that people have also requested for it on forums.
Is it also possible to rename the title of this feature request to something like "Confirmation Dialog for files & folder deletion"
Thanks

**Comment by nimishavijay** [comment]
Interesting problem! One Drive and Dropbox have a confirmation dialogue for deleting files too. However, it seems intrusive to show a confirmation dialogue every time a file is deleted, since deletion is a common action. There is also a trash bin from which files can be recovered. 

We could definitely move the "Download" action up. Another solution is to have a notification with an undo button, similar to sending a message in Mail. This is also the behaviour for Google Drive. So a notification `Design review.md has been deleted. [Undo]`. This would be my preferred solution as it is not as intrusive, and still offers a way to quickly cancel deletion if it was by mistake. What do you think? cc @jancborchardt and @szaimen as well

**Comment by szaimen** [comment]
@nimishavijay I agrees that an undo popup would be the preferred solution in that case since showing a popup might be too intrusive and slow and as you said we have the trashbin for this case.

**Comment by delacosta456** [comment]
hi @nimishavijay intrusive... truly and if your are talking about deleting multiple files,  selecting concerned files/folder with check box method(already present) could present a single confirmation box about select items.
Also, i think Gmail has a setting to configure (enable) "Confirm before deleting.." may be implementing this (if possible) could et te user decide what is comfortable .

**Comment by skjnldsv** [comment]
@nimishavijay @szaimen @jancborchardt 
What about showing a confirm if you are deleting more than one file ?

That would be a sane compromise to move that issue forward I think? :)

**Comment by szaimen** [comment]
> @nimishavijay @szaimen @jancborchardt What about showing a confirm if you are deleting more than one file ?
> 
> That would be a sane compromise to move that issue forward I think? :)

Yes, sounds like a good solution to me :)

**Comment by jancborchardt** [comment]
@skjnldsv yup, sounds like a good first step. :)

**Comment by LMRW** [comment]
If trash & file versions are disabled (which sometimes is required) then being able to delete entire folders of terabytes of data in a single click without confirmation is a HUGE issue. Absolutely nextcloud should ask users if they are sure - every time - if trash can and versions are disabled. This is a massive massive massive usability issue with tremendous danger of incredible file loss.

**Comment by BloodyIron** [comment]
> If trash & file versions are disabled (which sometimes is required) then being able to delete entire folders of terabytes of data in a single click without confirmation is a HUGE issue. Absolutely nextcloud should ask users if they are sure - every time - if trash can and versions are disabled. This is a massive massive massive usability issue with tremendous danger of incredible file loss.

You might have missed this in the history of this issue -> https://github.com/nextcloud/server/pull/43231

Not yet sure what version of nextCloud it comes in though. I'm checking currently.

**Comment by BloodyIron** [comment]
Looks like it made it into v29.0.0-beta1, so prettttyyyy sure it's in RELEASE v29.x : https://github.com/nextcloud/server/releases/tag/v29.0.0beta1

**Comment by BloodyIron** [comment]
Er wait hold on... is there no delete confirmation in v29 for a single file delete instruction? :s

**Comment by skjnldsv** [comment]
No, there is if you delete more than X items at a time. The idea of also asking for confirmation for folder bigger than X GB is pretty nice too.

But if files_trashbin is disabled, I think we should always ask for confirmation, I agree.

@jancborchardt @nimishavijay ?

**Comment by BloodyIron** [comment]
I for one would really want a setting to just ask every time anyways, even if you can toggle it off. Having to go to the trashbin because... OOPS I clicked delete instead of download... is now a waste of time to retrieve it, that could have easily been avoided by an "Are you sure?". To me that I think enables a happy medium for all. I actually can't even fathom why this change even required a minimum # to activate in the first place, that seems very out of place.

**Comment by LMRW** [comment]
For people with no trash bin (pretty much essential for files_external) there is still a giant risk of deleting literally terabytes in a single click of a button next which starts with the same letter as and sits right alongside the Download button.

It's absolutely horrifying to be honest and makes nextcloud completely unusable for large teams where accidents can happen!

Can't we just have a setting in admin to alert users to confirm deleting files, it seems simple a solution and pretty much every single operating system and cloud service already does this! 

With all that said, thank you for the start in a right direction with what we have so far at least it's better than before (although I would say still not enough)

**Comment by BloodyIron** [comment]
Oh and to clarify, I really think there should be no minimum number of selected items for an "Are you sure?" dialogue. Right clicking on a file to delete/download is precariously close together. This is completely avoidable as a problem. Whether trash exists or not.

**Comment by LMRW** [comment]
I love nextcloud and I'm so grateful but I have to be honest it's so crazy and confusing to me this is even debated... if trash can is disabled, confirm every single delete.

**Comment by skjnldsv** [comment]
> if trash can is disabled, confirm every single delete.

this part is definitely not debated, I'll take care of it asap ! :)

**Comment by regs01** [comment]
> No, there is if you delete more than X items at a time. The idea of also asking for confirmation for folder bigger than X GB is pretty nice too.
> 
> But if files_trashbin is disabled, I think we should always ask for confirmation, I agree.
> 
> [@jancborchardt](https://github.com/jancborchardt) [@nimishavijay](https://github.com/nimishavijay) ?

There is no confirmation even if you deleting hundreds of file (whole folder). And doesn't matter if there is trash bin or not, there should be an option. It makes no sense to have an option for extension change, but not deletion.

**Comment by skjnldsv** [comment]
> There is no confirmation even if you deleting hundreds of file (whole folder). And doesn't matter if there is trash bin or not, there should be an option. It makes no sense to have an option for extension change, but not deletion.

![Image](https://github.com/user-attachments/assets/f431e324-e318-41db-86c2-27c7f007b036)
Yes there is 🤔 
https://github.com/nextcloud/server/blob/7b5cd6061488f5219c1f612c92470f1339cdcb8e/apps/files/src/actions/deleteAction.ts#L84-L89

**Comment by regs01** [comment]
` if (!isTrashbinEnabled()) { `

there needs to be regardless trashbin availability, at least as an option enabled by default.

**Comment by skjnldsv** [comment]
> ` if (!isTrashbinEnabled()) { `
> 
> there needs to be regardless trashbin availability, at least as an option enabled by default.

So, your request is to have a popup no matter what, do I get this right?
You want to always ask, whether it's 1 or 29574 items, and no matter if the trash is enabled?

**Comment by regs01** [comment]
Yeah, always. As well as Empty deleted files needs to be password-protected.

**Comment by BloodyIron** [comment]
They're not the only person in this thread wanting a "are you sure?" dialogue for deleting any number of things whether the trash bin is enabled or not. I've been trying to make the case in this thread that this is something expected by default as a typical UX, hence its general presence in countless other tools and ecosystems.

I guarantee you adding this dialogue in every case is going to solve a lot more problems than it "creates".

**Comment by skjnldsv** [comment]
@marcoambrosini @kra-mo thoughts?

**Comment by kra-mo** [comment]
Having confirmation like this presented based on a factor that can dynamically change (eg. number of files) is a bad idea. It might make people too comfortable undertaking actions even when no confirmation would be presented because they expect one from previous experience.

My opinion is that as it stands, if we present a dialog, we should present it all the time, not based on specific factors, as users cannot intuit that without trying destructive actions.

Of course, the proper long-term solution would be undo and ultimately we should strive towards that.

**Comment by admintechblog** [comment]
We are migrating from ownCloud 10.8 to Nextcloud 31.0.6. Our migration is ready for production, but during testing yesterday, we accidentally pressed the "Delete" key on the keyboard. This immediately deleted the directory that was in focus from an external storage mounted via NFS — containing 28 GB of data.

There was no prompt or warning, and we were initially unsure how the directory had disappeared. After some investigation, we found the missing files in the trash bin.

This behavior is extremely concerning. ownCloud does not allow deletion via the "Delete" key alone, and we believe that having a confirmation prompt before deletion is absolutely essential.

Data is valuable, and allowing deletion without confirmation — simply by pressing the "Delete" key — is a potential data loss hazard. For us, this could be a deal-breaker. It creates the expectation that accidental deletions are just a matter of time.

Please consider adding a confirmation dialog before deletion, especially when using keyboard shortcuts.

**Comment by skjnldsv** [comment]
> Having confirmation like this presented based on a factor that can dynamically change (eg. number of files) is a bad idea. It might make people too comfortable undertaking actions even when no confirmation would be presented because they expect one from previous experience.
> 
> My opinion is that as it stands, if we present a dialog, we should present it all the time, not based on specific factors, as users cannot intuit that without trying destructive actions.
> 
> Of course, the proper long-term solution would be undo and ultimately we should strive towards that.

Then I'll reopen and we'll move towards a more definite approach where we always show the dialogue, but add an option to disable the behaviour as we already do for the extension warning :)

**Comment by admintechblog** [comment]
was able to change the dialog to appear when deleting 1 item by modifying the '>=5' value in these files:

dist/files-init.js

dist/files-init.js.map

However, this prompt only appears when you check the box next to a file and select "Delete" from the "Actions" menu. It would be great to have a warning prompt when deleting using the keyboard shortcut, since that shortcut is the most dangerous of all.

Currently, the only way to prevent accidental deletions via the keyboard shortcut is for each user to disable shortcuts in the "Theming" section.

**Comment by BloodyIron** [comment]
> was able to change the dialog to appear when deleting 1 item by modifying the '>=5' value in these files:
> 
> dist/files-init.js
> 
> dist/files-init.js.map
> 
> However, this prompt only appears when you check the box next to a file and select "Delete" from the "Actions" menu. It would be great to have a warning prompt when deleting using the keyboard shortcut, since that shortcut is the most dangerous of all.
> 
> Currently, the only way to prevent accidental deletions via the keyboard shortcut is for each user to disable shortcuts in the "Theming" section.

IMO the "are you sure?" dialogue should _always_ fire when deleting stuff, regardless of method. But as you demonstrate there's inconsistencies in the UX :/

**Comment by admintechblog** [comment]
> > was able to change the dialog to appear when deleting 1 item by modifying the '>=5' value in these files:
> > dist/files-init.js
> > dist/files-init.js.map
> > However, this prompt only appears when you check the box next to a file and select "Delete" from the "Actions" menu. It would be great to have a warning prompt when deleting using the keyboard shortcut, since that shortcut is the most dangerous of all.
> > Currently, the only way to prevent accidental deletions via the keyboard shortcut is for each user to disable shortcuts in the "Theming" section.
> 
> IMO the "are you sure?" dialogue should _always_ fire when deleting stuff, regardless of method. But as you demonstrate there's inconsistencies in the UX :/

Agree, why have the confirmation appear when the boxes are selected on purpose and clicked on the "Delete" action? I simply don't understand this logic. The most dangerous deletion is the one triggered by the Delete keyboard shortcut, this is where the "are you sure?" dialog should appear.

**Comment by skjnldsv** [comment]
It's been scheduled, you can wait for this ticket closure :)
Thanks for whoever participated 🙇

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/pull/53900
