### ISSUE TITLE
no hover feedback on folder name or file name

### ISSUE THREAD

**Issue by eslngr** [nextcloud/server#3201]
### Steps to reproduce
1. Login to Nextcloud
2. Move Cursor on folder name

### Expected behaviour
The cursor should change to give feedback about the link. 

### Actual behaviour
The cursor doesn't change. Its currently not clear if the interaction will follow a link or display the details. 

### Server configuration
**Operating system**: ‪
Debian 8.7‬

**Web server:** 
apache2 2.4.10-10+deb8u7

**Database:**
10.0.28-MariaDB-0+deb8u1

**PHP version:**
5.6.29

**Nextcloud version:** (see Nextcloud admin page)
11.0.1 (production)

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from owncloud

**Where did you install Nextcloud from:**
https://nextcloud.com

**Comment by skjnldsv** [comment]
@eslngr Can you provide a screenshot please?
I can't reproduce, I have a feedback on mine (nc 11 & 12)

**Comment by palantus** [comment]
@skjnldsv 
The same happens for me.
It works if I disable the css rule:
```
span.nametext, span.innernametext, span.extension {
    cursor: default;
}
```
in trash.css
Running on Nextcloud 11.0.1 (stable) downloaded from website.
I've attached a "screenshot" (normal screenshots doesn't include cursor).
![img_20170221_141652](https://cloud.githubusercontent.com/assets/819342/23166598/895caf2a-f841-11e6-9962-353a2864861b.jpg)

**Comment by skjnldsv** [comment]
Coming from here :)

https://github.com/nextcloud/server/blame/master/apps/files/css/files.css#L564

**Comment by palantus** [comment]
It isn't enough to disable that rule. It only affects the link ("a") itself, and not the text. The cursor of the text (filename) is overridden using the rule I listed. I'm not that familiar with nextcloud/owncloud code, so I may very well have missed something :)

**Comment by skjnldsv** [comment]
It should be enough yeah :)
We need to be sure on why it was added on the first place though.

**Comment by palantus** [comment]
I have tried disabling it using Chrome developer tools and there still isn't a pointer cursor when hovering the file name. It does however add a pointer cursor to everything around the name (span) itself.

**Comment by skjnldsv** [comment]
Yep, you're right, there is the other line you mentioned :)
https://github.com/nextcloud/server/blame/master/apps/files_trashbin/css/trash.css#L16

@schiessle ?

**Comment by individual-it** [comment]
The problem was introduced in PR #2436
PR  #3676 fixes this issue and also does not bring the original issue #2407 back

Should we use UI tests for stopping this kind of stuff break?
