### ISSUE TITLE
Run occ files:scan-app-data after a Nextcloud Upgrade ?

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/server#32030]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

Sometimes - but regular - when doing Nextcloud Upgrades (which are successful) - a Nextcloud WEB-Login could fail for all users
with "internal server error" - when looking into the nextcloud.log i often see errors like : 

app":"PHP","method":"GET","url":"/apps/passman/","message":"file_get_contents(/ncdata/appdata_ocnudqtqmhau/css/icons/icons-list.template): failed to open stream: No such file or directory 

or

"app":"index","method":"GET","url":"/apps/passman/","message":"File does not exist"

Restarting apache or/and mysql may not fix this issue and the "Internal Server errors" can persist.

In general i solved those issues by runing "occ files:scan-app-data"  and all users could login again and the "internal server error" was gone.

**Describe the solution you'd like**

I do see that during nextcloud upgrades, there is running a Database repair action, too (and other fixing and correction actions), 
but i think an "occ files:scan-app-data" will not run after a Nextcloud upgrade.

Just an idea  - if this could be built in a regular Nextcloud Upgrade process (post Upgrade action) ?

Because - since i do run this command after each Upgrade, i never touched this situation (internal server error) again.

**Comment by joshtrichards** [comment]
I suspect that adding this into the automated upgrade process wouldn't be acceptable since it could be a very long running high overhead process in various environments. For now, it might be best to consider adding it to the documentation. Sort of like how the regular `files:scan` is already mentioned in the manual installation troubleshooting section:

https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html#troubleshooting

I think the more interesting question is: why is this happening to start with? :-)
Are you running PHP in FPM mode by chance?

**Comment by Githopp192** [comment]
That's correct Josh - this operation might be a long running operation.
I do agree adding this into the Nextcloud Troubleshooting area could be a good idea at least.

Yes, i do run PHP 8.1  with php-fpm.
And yes, i did follow the Tuning recommendations:

https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html

Btw - since PHP 8.1 i never had to run "occ files:scan-app-data" again after an upgrade.

I hope this situation will continue.

**Comment by ruedigerkupper** [comment]
> I think the more interesting question is: why is this happening to start with? :-) Are you running PHP in FPM mode by chance?

I see this problem from time to time after an upgrade or restart of nextcloud. I never tried scan-app-data, though, since restarting PHP (possibly severaltimes) solves it. I run PHP8.1 in FPM mode, so I am curious @joshtrichards why you asked that question? Could you elaborate? Thanks!

**Comment by Githopp192** [comment]
short confirmation .. after PHP-8.x - i never had to run scan-app-data again to solve issues like ""internal server error" ..

**Comment by skjnldsv** [comment]
As this can be a tremendously expensive task, it is best to not automatise this kind of processes :)
I'll close this. If people have issues, they can find help on forum or docs and see that this scan might be manually recommended on errors like those (that should not happen in the first place :shrug:)
