### ISSUE TITLE
Shadow for buttons looks strange and off-style

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#3203]
Check this out @nextcloud/designers:
![capture du 2017-01-23 09-11-29](https://cloud.githubusercontent.com/assets/925062/22196161/0190bfca-e14c-11e6-8077-22da411d725f.png)
![capture du 2017-01-23 09-11-06](https://cloud.githubusercontent.com/assets/925062/22196162/01d6d3f2-e14c-11e6-8bc3-a5aef3654ade.png)

Especially on the upload button and the dropdowns it just looks a bit strange. We do not have 3D-like effects anywhere else really, except the shadows of the app and user menus.
And it separates the style even more from the one we have on the website which is definitely not something I want to do.

@skjnldsv I assume this was part of a recent SCSS overhaul? Could we keep backend changes and severe look changes separate? ;)

**Comment by jancborchardt** [comment]
Fix at https://github.com/nextcloud/server/pull/3204, please review

**Comment by ChristophWurst** [comment]
I don't think it looks that strange/bad :-)

**Comment by eppfel** [comment]
> @skjnldsv I assume this was part of a recent SCSS overhaul? Could we keep backend changes and severe look changes separate? ;)

No, this was part of a separate discussion here: #3121 and the PR got in over the weekend pretty fast: #3187

**Comment by jancborchardt** [comment]
Why do the buttons need to be more prominent? They are not the most important thing on the page. In the Mail app for example, or in Contacts, it just looks strange:
![capture d ecran_2017-01-20_19-05-54](https://cloud.githubusercontent.com/assets/14975046/22159971/ae63ffc4-df43-11e6-82e1-d6cbcd0fff39.png)

The »New contact« button is definitely too distracting with the shadow style. The prominent placement on the top left is already enough to establish it as the action. Having the 3d effect just makes it look extraordinarily out of place.

**Comment by eppfel** [comment]
I also felt it looked a bit weird and therefore I encouraged @skjnldsv to do an PR to see it more in context, but it was merged before it was properly reviewed.

> Why do the buttons need to be more prominent? 

The distinction between inputs and buttons was the shallow IMO. So for forms the 3D buttons work very well for me (see OP).

> The »New contact« button is definitely too distracting with the shadow style.

Maybe this is an issue with buttons in the sidebar? See calendar for example:

<img width="250" alt="bildschirmfoto 2017-01-23 um 11 29 30" src="https://cloud.githubusercontent.com/assets/1899308/22200528/c1cf9942-e15f-11e6-919b-9f767c93bcaa.png">

**Comment by MariusBluem** [comment]
> Maybe this is an issue with buttons in the sidebar? See calendar for example:

This is something introduced with https://github.com/nextcloud/server/pull/3150 and has nothing to do with the buttons, I think 😁 ... Good catch anyway ... Please open a new issue for that 🤔 @eppfel

**Comment by MariusBluem** [comment]
I want to add, that I ❤️ the 3D-Effect at the tags 😁 ... maybe there is a way to keep it 🤔 What do you think about that?

**Comment by eppfel** [comment]
> This is something introduced with #3150 and has nothing to do with the buttons, I think 😁 ... Good catch anyway

I did not meant to show the highlight issue. I wanted to exemplify, that in the sidebar, we maybe do not need a "button" for the "new x" anyway.

**Comment by eppfel** [comment]
<img width="1237" alt="bildschirmfoto 2017-01-23 um 12 24 56" src="https://cloud.githubusercontent.com/assets/1899308/22202128/1271e6c8-e167-11e6-8369-7337bd8b5195.png">

**Comment by jancborchardt** [comment]
This is two different topics:

1. Distinction between input fields and buttons, which I also brought up in https://github.com/nextcloud/server/issues/3121#issuecomment-273632502
2. Making the buttons / add functions in the sidebar have the proper affordance. This was brought up multiple times and we should do it with the border so they look like other clickable buttons.

> So for forms the 3D buttons work very well for me (see OP).

@eppfel forms area very small part of Nextcloud though. Even in the settings, mostly it’s just single fields with confirm buttons.

**Comment by skjnldsv** [comment]
For clarification, this is part of the new inputs design I rewritted from the old one: #3121 
The implementation of the better hover effect is the blue border, not the 3D effect.

Concerning the 3D effect, This is exactly like @eppfel said
> And I feel because, we don't use 3D anywhere it works so good. Buttons need to be more prominent, so if we do not use shadows, I would like to find another option.

I feel like the old buttons looked kinda out of place and those new ones really refresh nextcloud a little bit. 😃

**Comment by Espina2** [comment]
I agree that buttons should be different but this 3D effect...

**Comment by Espina2** [comment]
And we should decide a paradigm, if you use shadows and 3D "styles" it should reflect in the other elements. Like It are now, I dislike it and agree with @jancborchardt.

**Comment by skjnldsv** [comment]
Why is there suddenly so many people discussing this issue AFTER this has been implemented?
I mean, all the designers have been notified, and coming after the talk really bothers me.

I would have loved so more reviews/opinion when I was developing this.

**Comment by Espina2** [comment]
@skjnldsv sometimes people doesn't have the time see all the notifications that they had on github. 

But if we see something that we think its not good enough we should not say nothing? 

If you feel bad for implementing and have "bad" feedback, just wait to people give more feedback.

**Comment by skjnldsv** [comment]
@Espina2 well no, you should obviously said something! But having a hard time to find reviewers and suddenly seeing a lot of active devs for complaining doesn't makes me feel very good.

We'll wait anyway, that's how it works.

**Comment by raimund-schluessler** [comment]
> Why is there suddenly so many people discussing this issue AFTER this has been implemented?
I mean, all the designers have been notified, and coming after the talk really bothers me.

Sorry, for commenting just now, but I just didn't noticed the shadow effect in https://github.com/nextcloud/server/issues/3121.

I would also vote for not using a 3D/shadow effect and use a different solution for making buttons more obvious. However, this just my personal preference.

**Comment by Espina2** [comment]
Don't get me wrong, I know its frustrating to do something and listen people talk "bad" about that. 

Sometimes its difficult to understand how it will look a change in the whole project just with the mockup, so when you see the picture this can happen. 

Design is like this trial and error, sometimes you hit sometimes you not. :)

**Comment by eppfel** [comment]
@jancborchardt @Espina2 I can see the issues with the 3D looking different, although we use depth on pop-overs. 

> this is done via bolding and slightly darker background.

I feel this is not enough, but we could work on this in another issue.

> Making the buttons / add functions in the sidebar have the proper affordance. This was brought up multiple times before when we did not have the button style and we should do it with the border so they look like other clickable buttons. This change was made on purpose already, and it should be separated from this discussion.

Was not aware. I understand.

@skjnldsv I think you are just too fast for all the other nextclouders 😉 ❤️ Your new inputs are not even a week old. So it should not have been merged over the weekend.

**Comment by jancborchardt** [comment]
@skjnldsv I was on the issue and reviewed it, and that was before the very different 3D styles were added. I have a ton of issues in my notifications which I didn’t check over the weekend and assumed it was solved nicely. And it really was – literally my only problem with it is the strange 3D style :)

As you can see from how it looks in the different apps (here also in Calendar), it was really merged too fast:
![bildschirmfoto vom 2017-01-23 14-27-57](https://cloud.githubusercontent.com/assets/213943/22205681/33b18508-e178-11e6-98c8-4ca271e6812c.png)

Sorry about that, but oftentimes people only notice things off when they are in master. And while that’s frustrating sometimes, in this case it was a _very_ fast pull request and this is something I really like in our community: We discuss stuff, but also not limitless. We trust long-term contributors with their actions.

Lots of stuff I did over the years has been changed sooner or later (just look at the log in button / icon stuff ;) so please don’t be discouraged. You do _amazing_ work! This is just one detail.

**Comment by MorrisJobke** [comment]
> Sorry about that, but oftentimes people only notice things off when they are in master. And while that’s frustrating sometimes, in this case it was a very fast pull request and this is something I really like in our community: We discuss stuff, but also not limitless. We trust long-term contributors with their actions.

Yes - we should definitely refine this - but otherwise it wouldn't have been merged and would still be open in 10 months or so ;)

**Comment by skjnldsv** [comment]
@nextcloud/designers Okay, less complaining about the shadow and more propositions now :)

__We've got two issues to work on:__
1. The 3D effect doesn't seems to fit your views on the nextcloud design
2. Our buttons lack of differences compared to a simple text input. What can we do to improve that?

Please make suggestion with screenshots and/or good explanations.

Again, aside from things that are slightly broken (_like the calendar buttons_) **only take the design in consideration**, whatever results from this change is irrelevant since it's normal no have to fix things after such a change.

**Comment by jancborchardt** [comment]
@skjnldsv I made a proposal with »remove button shadow effect #3204« and think that already improves it a lot over the current state.

**Comment by icewind1991** [comment]
Making button more prominent is important but I think we should be selective about which buttons we make more prominent, there are plenty of button in the interface that really don't need to be prominent

**Comment by skjnldsv** [comment]
@jancborchardt I don't think that's enough.
We just roll back to the original problem, there isn't enough distinction over regular stuff we can find all over nextcloud.

What's bothering you the most about the 3d effects? Is it just because we don't use that nowhere else?
I still think they aren't that big and imposing and that they fit pretty well in the overall design 😄

**Comment by jancborchardt** [comment]
- We don’t use that style or something similar anywhere else.
- They are distracting as they pull attention away. Whenever I read my emails now, the »New message« button in the Mail app just stands out like a sore thumb.
- The style was used in websites 3–5 years ago when the inset effect was used for this 3d style. That makes it look outdated.
- The distinction with #3204 is enough via bold typeface, centering of text and different background.
- We have a way of making specific buttons more prominent, and that is via the `.primary` class which we do use (although should sparingly). Like for Reply/Send in the Mail app, or the file picker popup.

I can give the arguments all over again, but sorry – one of our tenets is to be pragmatic. So at some point I just have to make a decision because this detail discussion is keeping us from doing more important things. :)

**Comment by skjnldsv** [comment]
> They are distracting as they pull attention away. Whenever I read my emails now, the »New message« button in the Mail app just stands out like a sore thumb.

It's to encourage you to wite more mails 😆 

> The style was used in websites 3–5 years ago when the inset effect was used for this 3d style. That makes it look outdated.
The current grey one doesn't feel very new either! 😛

**Comment by eppfel** [comment]
> we should be selective about which buttons we make more prominent

@icewind1991 🙏 amen

> The distinction with #3204 is enough via bold typeface, centering of text and different background.

@jancborchardt I disagree.

> We have a way of making specific buttons more prominent, and that is via the .primary class which we do use (although should sparingly). Like for Reply/Send in the Mail app, or the file picker popup.

Yes, we should definitely reevaluate, if there are other places for this one...

>>The style was used in websites 3–5 years ago when the inset effect was used for this 3d style. That makes it look outdated.
>
> The current grey one doesn't feel very new either! 😛

@skjnldsv I feel the same way.

> one of our tenets is to be pragmatic

But this is the important part. This issue and the corresponding PR is only about the shadow effect. All other changes @skjnldsv are not for discussion. I feel we have to acknowledge that there are too many objections and be constructive. I am confident @nextcloud/designers will find something even better. :fist: :heart:

**Comment by jancborchardt** [comment]
Yup – and one of the important learnings from this again is that pull requests should be small so that one small detail doesn’t block the whole thing. ;)
