### ISSUE TITLE
[Bug]: /index.php not consistently in URLs

### ISSUE THREAD

**Issue by sgreen25** [nextcloud/server#32052]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The URLS for Nextcloud seem to change to include /index.php, and on the next release do not include that.  This is causing issues in SAML SSO setup as there are multiple entries required for every Nextcloud deployment

### Steps to reproduce

Each upgrade seems to include and then exclude /index.php

### Expected behavior

URL should remain constant for each refresh.  

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
www-data@fd7e6ac81e9d:~/html$ php occ app:list
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - circles: 22.2.0
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contactsinteraction: 1.3.0
  - dav: 1.20.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_external: 1.13.1
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - firstrunwizard: 2.11.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - password_policy: 1.12.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_ldap: 1.12.2
  - user_saml: 4.1.1
  - viewer: 1.6.0
  - workflowengine: 2.4.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - dashboard: 7.1.0
  - encryption
  - files_sharing: 1.13.1
  - files_videoplayer: 1.10.0
  - photos: 1.3.0
  - sharebymail: 1.11.0
  - user_status: 1.1.1
  - weather_status: 1.1.0
www-data@fd7e6ac81e9d:~/html$
```

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
