### ISSUE TITLE
[Bug]: template selection dialog has nearly invisible horizontal scroll bar

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#32068]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

See screenshots. In firefox (light mode) I thought the dialog was completely broken - with no create button left.
<img width="1920" alt="Screenshot_20220422_121351" src="https://user-images.githubusercontent.com/551757/164698541-15ca7eae-2609-453d-8716-5ff5d32c2654.png">
But then in Chrome (dark mode) it turned out, there was a horizontal scroll bar:
<img width="1920" alt="Screenshot_20220422_121440" src="https://user-images.githubusercontent.com/551757/164698528-c738e131-d4d9-4bbe-af85-9c72626999bc.png">

Sadly that is not very discover-able, to put it mildly. I guess vertical scrolling would be better?

### Steps to reproduce

1. click the plus, select a text document, pick a name, hit enter
2. Select a template - find the create button
3. there is none

### Expected behavior

create button should always be visible and scrolling area should be obvious

### Installation method

Manual installation

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
This is on tech-preview.nextcloud.com - running RC1 of Nextcloud 24
```

### List of activated Apps

```shell
This is on tech-preview.nextcloud.com - running RC1 of Nextcloud 24
```

### Nextcloud Signing status

```shell
This is on tech-preview.nextcloud.com - running RC1 of Nextcloud 24
```

### Nextcloud Logs

```shell
This is on tech-preview.nextcloud.com - running RC1 of Nextcloud 24
```

### Additional info

This is on tech-preview.nextcloud.com - running RC1 of Nextcloud 24

**Comment by szaimen** [comment]
Which version?

**Comment by szaimen** [comment]
ping @jospoortvliet

**Comment by szaimen** [comment]
This should have been addressed with NC24RC1 thats why I am asking for the version...

**Comment by szaimen** [comment]
I'll close this as it should be fixed. Feel free to reopen if it should still happen.
