### ISSUE TITLE
Add option to copy/duplicate files

### ISSUE THREAD

**Issue by agoat** [nextcloud/server#3206]
Currently there is no possibility to copy a file to another (or same) folder in the WebUI. Files can only be moved to other folders.

Usecase 1:
UserA shares a file with UserB. UserB want this file in his own file storage (on the same server), so UserA can unshare and delete the file and UserB have it for his own. 

Usecase 2:
UserA want to share a file with UserB but also give him the option to edit/change/delete the file. But UserA want to save a copy of the original file (in another folder).

**Comment by chrissooo** [comment]
This will be greate when this will be possible.

Another Usecase:
A Templatefile (Business letter as Word Document) is shared as read only for all users. All users can make a copy of it in Webgui for his own use and write a business letter for a customer for example. In this example we have a lot of Template files for many situations.

**Comment by christianh95** [comment]
This would be important! 👍 
I am quite often in the situation that I want to share documents with my fellow students, but they don't need to get everything that I add to the document afterwards 😛 
And I always want to share single documents from a seperate folder that I can keep track of what I shared!

**Comment by jancborchardt** [comment]
Design-wise this could be nicely integrated with the move function. We simply need to rename the function in the dropdown »Move or copy«:
![capture du 2017-04-28 12-31-11](https://cloud.githubusercontent.com/assets/925062/25525387/e96be2b8-2c0e-11e7-90aa-a984adb80a4a.png)

And in the folder picker which gets opened we simply need to add another button for copying:
![capture du 2017-04-28 12-33-02](https://cloud.githubusercontent.com/assets/925062/25525394/f53ba790-2c0e-11e7-924d-432ba977c3f1.png)
Move will be the primary button, and copy a normal one. For better feedback, the copy and move buttons include the current folder in the text. Like »Copy to Pictures« or »Move to Pictures«.

cc @icewind1991 @nickvergessen @rullzer, and also @eotryx of files_move and @leizh of files_clipboard.

**Comment by nickvergessen** [comment]
*unsubscribing*

**Comment by e-alfred** [comment]
Do you think something like "Cut" could be implemented as well? For now it is still a two step operation:

- Move file(s) to new place
- Delete old file(s)

**Comment by jancborchardt** [comment]
@e-alfred the »Move« operation does move the file, that is cut & paste. There is no need to delete the old file.

**Comment by e-alfred** [comment]
@jancborchardt I mixed that up, sorry.

But the second question still stands. How well does it work with a huge amount of files?

**Comment by xraMsamohT** [comment]
> There is no need to delete the old file.

This would be the worst case for Comments, Tags, and Versions.

**Comment by MorrisJobke** [comment]
Fixed with #6014

**Comment by chaeyan** [comment]
This feature is still not present, even after 5 years.
