### ISSUE TITLE
Follow-up #31751

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#32072]
- [ ] Enterprise releases fixes (logo)
- [x] Dyslexia font not working with `index.php` https://github.com/nextcloud/server/pull/32073
- [x] Notifications https://github.com/nextcloud/notifications/pull/1178
- [x] Mixing colours seems off https://github.com/nextcloud/server/pull/32146
- [x] Default guest page loading issues + integration tests https://github.com/nextcloud/server/pull/32147
- [x] Dashboard needs update regarding #32180 
  - [x] background colour and header revert 
  - [x] buttons colours
- [x] Fix logo-bright on primary https://github.com/nextcloud/server/pull/32204
- [ ] Files icons colours 
- [x] Better design of theming https://github.com/nextcloud/server/pull/32213
- [x] Wording of the default theme (fallback to system settings) https://github.com/nextcloud/server/pull/32195
- [x] Theming admin buttons icons colours
- [ ] Fix social icons in `/settings/user/sharing`
- [x] apps management icon colours
- [x] user management icon colours
- [x] help section icon colours
- [x] unified search icon colours
- [ ] user search icon colours
- [x] go through all settings sections and control the icons in dark mode
- [ ] check with dark mode active (and control icons):
  - [x] activity
  - [x] files_pdfviewer
  - [ ] files_rightclick
  - [ ] files_videoplayer
  - [x] firstrunwizard
  - [x] logreader
  - [ ] nextcloud_announcements
  - [ ] password_policy
  - [x] photos
  - [x] privacy
  - [x] recommendations
  - [x] serverinfo
  - [ ] support
  - [ ] survey_client
  - [x] text https://github.com/nextcloud/text/issues/2345
  - [x] viewer
  - [ ] user status in avatar popover menu has no filter (is not color inverted)

## Features

- [x] Remove scss support https://github.com/nextcloud/server/pull/32326
  - [x] Fix icons generation
  - [x] Compile with npm
- [x] Implement theme-switch icon colour revert https://github.com/nextcloud/server/pull/32326
- [ ] Cache [default css theme](https://github.com/nextcloud/server/blob/master/apps/theming/css/default.css) on first successful load

## Related
- [x] https://github.com/nextcloud/server/issues/32176
- [ ] https://github.com/nextcloud/server/issues/32150
- [x] https://github.com/nextcloud/nextcloud-vue/issues/2707

**Comment by szaimen** [comment]
Who will go through the remaining apps?

**Comment by szaimen** [comment]
shall I do it?

**Comment by szaimen** [comment]
Went through a few and reported things under https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Aui-refresh-feedback
