### ISSUE TITLE
Public page styles are broken on

### ISSUE THREAD

**Issue by eppfel** [nextcloud/server#3207]
I could reproduce @ChristophWurst find:
![bildschirmfoto von 2017-01-23 10-58-41](https://cloud.githubusercontent.com/assets/1374172/22199404/08bca6a6-e15b-11e6-9b1b-5ec8d1c5156b.png)

I looked into it and it seems there all stylesheets with the route `/css/core/` are missing (e.g styles.css) .
<img width="1680" alt="bildschirmfoto 2017-01-23 um 11 51 00" src="https://cloud.githubusercontent.com/assets/1899308/22201061/5556576c-e162-11e6-9281-bd7c4095cd6d.png">

There is definitely something wrong with the routing/embedding...

@skjnldsv @MorrisJobke

**Comment by skjnldsv** [comment]
This is strange, because I was testing stuff yesterday for #3187 and everything was working fine!
https://github.com/nextcloud/server/pull/3187#issuecomment-274294552

**Comment by skjnldsv** [comment]
This comes from bde1150d041de5535e9dd3baaaa957e5a9c7ca89
I will take a look asap!

**Comment by eppfel** [comment]
Just reassured. I am on master, Chrome 55∞ macOS 10.11.6.

 It could have to do with the prettyURLs, but very likely with URLGenerator...

**Comment by skjnldsv** [comment]
No, this is a easy one:
https://github.com/nextcloud/server/blob/master/lib/private/TemplateLayout.php#L167

```
// Do not initialise scss appdata until we have a fully installed instance
// Do not load scss for update, errors, installation or login page
if(\OC::$server->getSystemConfig()->getValue('installed', false)
    && !\OCP\Util::needUpgrade()
    && \OC_User::isLoggedIn()) {
	$cssFiles = self::findStylesheetFiles(\OC_Util::$styles);
} else {
	$cssFiles = self::findStylesheetFiles(\OC_Util::$styles, false);
}
```

I didn't realised that public pages don't have a logged-in user!

**Comment by MorrisJobke** [comment]
> \OC_User::isLoggedIn()

The problem seems to be here: why do you disable the SCSS for non-logged in users? The login page should also be done within SCSS.

**Comment by MorrisJobke** [comment]
Is there a way to move CSS and SCSS into different namespaces? So that we know if it is CSS or SCSS - relying on some magic under the hood is always confusing and causes weird bugs as above.

**Comment by MorrisJobke** [comment]
Fix is in #3223

**Comment by ChristophWurst** [comment]
Reopening because the bug is still not fixed for 2FA pages:
![bildschirmfoto von 2017-01-30 14-10-02](https://cloud.githubusercontent.com/assets/1374172/22424282/2d216004-e6f6-11e6-84c9-e61f906d7999.png)

**Comment by MorrisJobke** [comment]
Separate issue -> moved to a new issue.
