### ISSUE TITLE
User Profile MUST NOT be visible to the public per default

### ISSUE THREAD

**Issue by kolewu** [nextcloud/server#32078]
Nextcloud 23 has brought us user profiles and what's visible on them is configurable. That's nice BUT after an update **all** Profile-pages are visible to the public. That is bad behavior and very unexpected. And it is not documented!

Most clouds I set up and use are for registered users only and **no internal information** is allowed to be visible to the public. Even if the user sets all information to "Show to loggend in users only" (this is not the default for some entries!) a page with the username is generated at the address https://my.cloud/u/username

Since profiles are very valuable for the registered users, there must be an option to make them only visible for logged in users to not have to disable them completely.

It must be possible for the administrator to define the level of visibility for all accounts. Maybe as a general non changeable rule or as the current default with the possibility for users to make an educated change.

**Comment by szaimen** [comment]
See https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/profile_configuration.html?highlight=profile

Should work with NC23.0.4 and above.

**Comment by kolewu** [comment]
Thanks for the pointer, but why isn't this mentioned in the Changelog? And why isn't it off by default at least for Updates?
