### ISSUE TITLE
Import personal data from LDAP

### ISSUE THREAD

**Issue by Laurent2916** [nextcloud/server#32085]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
We use the `LDAP/AD integration` app as a login backend and t is frustrating that our users have to fill in personal informations in their profile when they are already in the attributes of our LDAP.

**Describe the solution you'd like**
A simple "Attributes mapping" menu in the `LDAP/AD integration` app where the administrator could link Nextcloud attributes and LDAP fields. For exemple, in our case, we'd like to link the phone number on Nextcloud and the LDAP attribute `mobile`. Likewise for their address, their nickname, their date of birth...

**Describe alternatives you've considered**
We could create a cron job to synchronize our LDAP attributes with the ones displayed on Nextcloud.
It sound doable by looking at the [occ documentation for users](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html#user-commands) (specifically under the `Set a setting` section).

**Additional context**
We use openLDAP, and Nextcloud 23.0.4.
This feature was already reported in 2017, but was closed in 2019 since the issuer deleted his account. (#4365)

**Comment by jonathanmmm** [comment]
The occ documentation for users seems to not include things like address and phone number, have can't see phone number and address of user with `occ user:setting username` , same with `occ user:info username`
If this would be there, I would maybe try to write a script, that can be used via cron (maybe php script that runs with the nextcloud cronjob)

**Comment by march42** [comment]
I tried to implement this and I had some troubles with it, so I postponed it awhile ago.
I found how to add attribute mappings to configuration and settings page. I thought about updating the data via the `processAttributes` method of User class. Then I got stuck looking into the Settings App, how the Personal Info works and how to update it's data.

**Comment by march42** [comment]
You can find my working solution at branch **feature/ldap_update_profile** of my fork.
[https://github.com/march42/nextcloud-server/tree/feature/ldap_update_profile](https://github.com/march42/nextcloud-server/tree/feature/ldap_update_profile)
The updated documentation is in my docu fork at [https://github.com/march42/nextcloud-documentation/tree/feature/ldap_update_profile](https://github.com/march42/nextcloud-documentation/tree/feature/ldap_update_profile)

I would appreciate someone testing and giving feedback. Thanks in advance.

**Comment by jonathanmmm** [comment]
> You can find my working solution at branch **feature/ldap_update_profile** of my fork. https://github.com/march42/nextcloud-server/tree/feature/ldap_update_profile The updated documentation is in my docu fork at https://github.com/march42/nextcloud-documentation/tree/feature/ldap_update_profile
> 
> I would appreciate someone testing and giving feedback. Thanks in advance.

Great, but I wouldn't be testing this in production. Maybe I will create a test environment, maybe in one or two months. Maybe you can create two drafts/PRs for this.

**Comment by tajetaje** [comment]
> You can find my working solution at branch **feature/ldap_update_profile** of my fork. https://github.com/march42/nextcloud-server/tree/feature/ldap_update_profile The updated documentation is in my docu fork at https://github.com/march42/nextcloud-documentation/tree/feature/ldap_update_profile
> 
> I would appreciate someone testing and giving feedback. Thanks in advance.

Would you consider PRing your changes? Or is there an issue with them?

**Comment by march42** [comment]
> Would you consider PRing your changes? Or is there an issue with them?
I created both pull requests.
My issue is/was mostly personal. It seemed nobody cared, so I didn't bother. Sorry about that.

**Comment by tajetaje** [comment]
> 

Thanks! Hope NC accepts them
