### ISSUE TITLE
The ability to obtain the path on "Favorite" documents

### ISSUE THREAD

**Issue by wildernessfamily** [nextcloud/server#32088]
**Is your feature request related to a problem? Please describe.**
In the Nextcloud web GUI clicking on "Favorites" brings you to your favorites; Which of course can contain an assortment of files including folders, text files, photos, etc. For my projects, I create a folder for each project. In that folder, I also create a text file (.md markdown) as a journal in which I keep notes for meetings, calls, etc. I mark the journal text file as a favorite. After a call that is related to my project, I can easily go to my favorites and click on each project journal to quickly add notes. However, there are times I need to add screenshots to the journal. Ex. screenshot from my phone showing how long the call lasted. The problem I'm having is that when you are in your favorites it does not provide the path to the said document. When you click a folder in favorites it provides the path but for all other documents like photos, text documents, etc., no path is given. I've tried clicking on details and in details, no path is given. The only solution I have is to perform a search or click on files and start moving through folders to find the folder that the journal is in and the sub-folder in which I store all images for the journal.

**Describe the solution you'd like**
Some way of being able to see the path and also possibly click on the path of all documents in favorites. Possibly add the path to the documents in the "Details" section that is a link to the destination.

**Describe alternatives you've considered**
The only alternative I can find is having to click on folders and then work your way through the folders to the given sub-folder and or perform a search.

**Additional context**
1. I searched all feature requests and issues and was not able to find a request like what I'm proposing. If there is an existing request that I overlooked I apologize.
2. I have never created a feature request for NextCloud before. There are a lot of extensions and other repositories. I believe this would be the appropriate repository to add said request. If I did choose the wrong repository I do apologize. Please let me know and I will re-create said request in the appropriate repository.

Last but not least, to all the developers thank you for all your hard work and for providing such an awesome and most of all "private and secure" application that is open source!!!

**Comment by Jerome-Herbinet** [comment]
> I have been playing around trying to find a solution to my said feature request. I apologize, I did not know/realize you could "Right Click" on a folder or document. Right-clicking on the document provides a menu that contains "View In Folder". Please feel free to close the feature request. Thank you.

@wildernessfamily, this is the correct way to find the location of a bookmarked file or folder. 
I suggest you close this issue yourself when you have a moment to do so.
Thanks ;-) !
