### ISSUE TITLE
[Bug]: Web Flow v2 Does Not Show Username About to Be Connected

### ISSUE THREAD

**Issue by mikeperalta1** [nextcloud/server#32098]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When authorizing a client (e.g., desktop client for Linux), a browser tab is launched for the web authentication flow (v2). The authentication flow works fine, BUT ... if I am already logged in to NextCloud, the web flow auth never actually displays the username currently logged in. It simply asks if I would like to authorize the app.

I feel this is a security concern, or small bug, because some users may unintentionally authorize an app to an unintended user, if they're not keeping track of their login. I personally separate multiple NC logins using browser containers, but I don't think most users do that.

Path to the flow is: /index.php/login/v2/flow

The following screenshots show no indication of any currently logged-in username. The first one is slightly deceptive because clicking the "Log in" button doesn't prompt me for any credentials; Since I'm already logged in, it simply moves to the second screenshot that asks for access.

![image](https://user-images.githubusercontent.com/26490778/164861717-b193517d-c5d7-4b59-8fff-62da9b4b27ad.png)

![image](https://user-images.githubusercontent.com/26490778/164861734-f23dfa4e-bc35-4394-b78a-18d47bb3c644.png)

![image](https://user-images.githubusercontent.com/26490778/164861740-be91358c-3eb8-4cbe-b298-d4fd50e54278.png)

### Steps to reproduce

1. Be logged in to Account A, in your NextCloud web.
2. Begin to authorize a client that utilizes web flow v2
3. Assume you are about to authorize the client with Account B
4. Fail to notice you're logged in to Account A, because NC doesn't tell you during authorization
5. Proceed intuitively and accidentally authorize Account A, when you intended Account B

### Expected behavior

1. Be logged in to Account A, in your NextCloud web.
2. Begin to authorize a client that utilizes web flow v2
3. Assume you are about to authorize the client with Account B
4. See a clear indication from NextCloud that you are actually logged in to Account A
5. Correct your mistake by logging out, and logging back in, to Account B

### Installation method

Manual installation

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.4.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "default_phone_region": "US",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "objectstore": {
            "class": "\\OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "hostname": "***REMOVED SENSITIVE VALUE***",
                "port": "40828",
                "bucket": "storage",
                "autocreate": true,
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "use_ssl": true,
                "region": "us-west",
                "use_path_style": true
            }
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 0
        },
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
occ app:list
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - apporder: 0.15.0
  - backup: 1.0.6
  - bookmarks: 10.3.1
  - bruteforcesettings: 2.4.0
  - calendar: 3.2.2
  - camerarawpreviews: 0.7.15
  - circles: 23.1.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.1.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - deck: 1.6.1
  - drawio: 1.0.2
  - duplicatefinder: 0.0.13
  - end_to_end_encryption: 1.9.1
  - event_update_notification: 1.5.0
  - extract: 1.3.3
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_markdown: 2.3.6
  - files_mindmap: 0.0.26
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - fileslibreofficeedit: 1.0.4
  - firstrunwizard: 2.12.0
  - flowupload: 1.1.3
  - groupfolders: 11.1.2
  - groupquota: 0.1.8
  - impersonate: 1.10.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.7
  - news: 18.0.0
  - nextcloud_announcements: 1.12.0
  - notes: 4.3.1
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - officeonline: 1.1.3
  - onlyoffice: 7.3.2
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - quota_warning: 1.14.0
  - rainloop: 7.2.3
  - ransomware_protection: 1.13.0
  - recommendations: 1.2.0
  - richdocuments: 5.0.3
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.5
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - tasks: 0.14.4
  - text: 3.4.1
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - user_usage_report: 1.7.0
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflow_script: 1.8.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external: 1.15.0
  - maps: 0.1.10
  - theming: 1.14.0
  - user_ldap
```

### Nextcloud Signing status

```shell
It just says:

> No errors have been found.
```

### Nextcloud Logs

```shell
N/A?
```

**Comment by nickvergessen** [comment]
This should be solved since https://github.com/nextcloud/server/pull/32375
