### ISSUE TITLE
ChangeLog, where?

### ISSUE THREAD

**Issue by hostingnuggets** [nextcloud/server#321]
Where can I find the Change Log? I think it should be at least on the nextcloud.com website under the Download page for each release and maybe also inside the package itself.

For now, where can I find the ChangLog for the newest release 9.0.52?

**Comment by williambargent** [comment]
@hostingnuggets There is a blog post about the new update https://nextcloud.com/nextcloud-9-update-brings-security-open-source-enterprise-capabilities-and-support-subscription-ios-app/. If this isn't useful then might be worth checking out the forums.

In future, GitHub issues are for technical problems and improvements. The Forums are over on https://help.nextcloud.com for questions and queries.

**Comment by hostingnuggets** [comment]
Thanks but I am not looking for the marketing side of the changes to a release. In the past the most important changes would be summarized with each release on the https://github.com/nextcloud/server/releases page but it is missing for v9.0.52. It would be great if you could continue doing that or as suggested on the website under the download page or inside the tarball.

Cheers!

**Comment by jospoortvliet** [comment]
Yeah, we need to do a changelog, thanks for creating the issue in the website. Just a matter of time ;-)

**Comment by mejo-** [comment]
I agree that a changelog would be good to have. It still is the most convenient way to review changes between releases. If one exists, I usually read the changelog before updating software.

For now, you can review all changes between two release branches using the comparing changes log from Github. E.g. for 10.0.0 to 10.0.1, this is: [Comparing changes between v10.0.0 and v10.0.1](https://github.com/nextcloud/server/compare/v10.0.0...v10.0.1)

**Comment by LukasReschke** [comment]
@mejo- There is one since a longer period of time: https://nextcloud.com/changelog/ …
