### ISSUE TITLE
Inputs have wrong border color with theming

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#3211]
> ![bildschirmfoto vom 2017-01-23 14-18-26](https://cloud.githubusercontent.com/assets/213943/22205377/df2e0782-e176-11e6-879b-3fdcdc3fe2b1.png)

E.g. on the calendar.

Problem is the the border-color is not adjusted:
> ![bildschirmfoto vom 2017-01-23 14-19-42](https://cloud.githubusercontent.com/assets/213943/22205415/13c495d8-e177-11e6-8955-33e9d1fa3c87.png)

**Comment by nickvergessen** [comment]
Similar issue with buttons.
E.g. when you create a new calendar and **hover** the "Create" button

**Comment by skjnldsv** [comment]
It will be fixed after we implemented the correct scss variable system for theming (see #2288 )

**Comment by nickvergessen** [comment]
Also checkboxes are two-colored:
> ![bildschirmfoto vom 2017-01-25 11-08-21](https://cloud.githubusercontent.com/assets/213943/22286272/e08a0896-e2ee-11e6-9198-51077498ed80.png)

**Comment by skjnldsv** [comment]
yes, same thing :)

**Comment by nickvergessen** [comment]
Also affecting radio buttons:
> ![admin_-_foobar_-_2017-03-06_11 33 02](https://cloud.githubusercontent.com/assets/213943/23606416/ea752232-0260-11e7-83d1-22850d7123ad.png)

Also a different issue, but I guess variables PR might solve it as well:
> ![bildschirmfoto vom 2017-03-06 11-33-28](https://cloud.githubusercontent.com/assets/213943/23606443/0900ceae-0261-11e7-997a-a49ba5b251ed.png)

**Comment by MorrisJobke** [comment]
Fixed in #3530

**Comment by nickvergessen** [comment]
I just pulled on master and the issues still exist

**Comment by skjnldsv** [comment]
@juliushaertl :)

**Comment by juliushaertl** [comment]
@nickvergessen @MorrisJobke Should be fixed with 

#3530 was just the first step, all the theming related stuff is addressed in https://github.com/nextcloud/server/pull/3531

**Comment by MorrisJobke** [comment]
#3531 was merged and the input border worked here
