### ISSUE TITLE
[Bug]: Database Deadlock with PostgreSQL

### ISSUE THREAD

**Issue by Orangian** [nextcloud/server#32144]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi, 
After moving an existing Nextcloud install across servers to a new install and then switching from MariaDB to PostgreSQL, I have encountered an issue wherein every few minutes, the sync cuts out with a 503 error, and the following logs are seen (these are just snippets, they are repeated quite a lot):
https://pastebin.com/2GRXxQx9
https://pastebin.com/ZCiyBzjU
I have setup the notify_push daemon as well. 

### Steps to reproduce

1. Start sync with desktop client
2. Wait a bit until I get a 503 error
3. See the deadlock in the logs

### Expected behavior

The client syncs with no errors.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.qern-industries.pw"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "23.0.2.1",
        "overwrite.cli.url": "https:\/\/nextcloud.qern-industries.pw",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "5432",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_phone_region": "US",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "updater.release.channel": "stable",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "cookbook",
            "impersonate"
        ],
        "has_rebuilt_cache": true,
        "data-fingerprint": "09072317db24dc4bbd94d7924801d4df",
        "htaccess.RewriteBase": "\/"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - calendar: 3.2.0
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.0.8
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - files: 1.18.0
  - files_external: 1.15.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - impersonate: 1.10.0
  - integration_google: 1.0.6
  - integration_reddit: 1.0.3
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.11.7
  - maps: 0.1.10
  - messagevault: 1.0.0
  - news: 18.0.0
  - nextcloud_announcements: 1.12.0
  - notes: 4.3.1
  - notifications: 2.11.1
  - notify_push: 0.3.0
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - tasks: 0.14.2
  - text: 3.4.0
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_nextcloud_notification: 3.3.1
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - bruteforcesettings: 2.3.0
  - circles: 22.1.1
  - cookbook: 0.9.10
  - deck: 1.6.0
  - encryption: 2.8.1
  - extract: 1.3.3
  - federation: 1.12.0
  - files_antivirus: 3.2.2
  - firstrunwizard: 2.11.0
  - passwords: 2022.3.20
  - richdocuments: 5.0.3
  - richdocumentscode: 21.11.204
  - spreed: 13.0.3
  - support: 1.4.0
  - user_ldap: 1.10.2
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Put in a textfile as it was too big to upload: https://qern-industries.pw/nextcloud.log
```

**Comment by Orangian** [comment]
After re-syncing the files from the Samba share, it seems to have stopped, but no clue why the database errors opened up. These files were originally on a samba external storage, but are now a local external storage. They seemed to be the cause.

**Comment by Orangian** [comment]
It also appears that when it stops for a second, it skips a file, but does not re-sync it later, leading to missing files on the local copy.

**Comment by szaimen** [comment]
Hello, this problem should not appear anymore with the latest NC23.0.4
