### ISSUE TITLE
Display hover in file-list if filename is too long to display

### ISSUE THREAD

**Issue by SKB-CGN** [nextcloud/server#32157]
Hi,
would it please be possible, to have an "hover" in the file-tree, to show the complete name of the file, if it is too long to display?

Like here:
![2022-04-26 11_59_30-Dokumente - Dateien - Kreyenborg koeln - Cloud — Mozilla Firefox](https://user-images.githubusercontent.com/58603329/165275364-78c4d14b-4761-483a-9ce2-766fe4f37e8c.png)
![2022-04-26 11_59_47-Dokumente - Dateien - Kreyenborg koeln - Cloud — Mozilla Firefox](https://user-images.githubusercontent.com/58603329/165275361-f33598af-e661-4da1-bbc6-7d82b6116e61.png)

**Comment by CarlSchwan** [comment]
Done with https://github.com/nextcloud/server/pull/32964

**Comment by SKB-CGN** [comment]
With 24.0.3 on FreeBSD still no hover on filenames.
