### ISSUE TITLE
On the screenshot the new accent color is nearly not visible in contrast to the surroundings espwcially in dark mode. Can we add a bit more contrast there?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#32150]
> > On the screenshot the new accent color is nearly not visible in contrast to the surroundings espwcially in dark mode. Can we add a bit more contrast there?
> 
> We're back on the previous values, please raise the issue to the design team 😉

Cc @jancborchardt @nimishavijay

_Originally posted by @szaimen in https://github.com/nextcloud/server/pull/32146#issuecomment-1109435746_

**Comment by szaimen** [comment]
It is about these screenshots: https://github.com/nextcloud/server/pull/32146#issue-1215473082

**Comment by jancborchardt** [comment]
Yeah, probably makes sense to increase the primary-light from 10% to 15% or something like that in dark mode, as visually it’s different on dark than on light. @skjnldsv?

**Comment by skjnldsv** [comment]
@jancborchardt please do so and tell us which value you prefer :)

https://github.com/nextcloud/server/blob/dffbddcca6fa0221b8f2ac138732cf01154a5187/apps/theming/lib/Themes/DefaultTheme.php#L112
https://github.com/nextcloud/server/blob/dffbddcca6fa0221b8f2ac138732cf01154a5187/apps/theming/lib/Themes/DarkTheme.php#L73

**Comment by szaimen** [comment]
@jancborchardt any update here?

**Comment by skjnldsv** [comment]
We fixed a few values btw, not sure this is still needed. There was some errors in the first PR! :thinking:

**Comment by szaimen** [comment]
Let me test this tomorrow...

**Comment by szaimen** [comment]
## Screenshots from the PR:
| Before | After |
|:---------:|:------:|
|![Peek 26-04-2022 08-38](https://user-images.githubusercontent.com/14975046/165237373-a8ccaedc-86d2-4579-9336-34c26d687b45.gif)|![Peek 26-04-2022 08-37](https://user-images.githubusercontent.com/14975046/165237383-1cb8d091-27b5-43fb-9ae2-98c4c0890a80.gif)|

## My test from today:

| Before | After |
|---|---|
| ![image](https://user-images.githubusercontent.com/42591237/185862730-8b418d93-56b9-48fc-9f81-3135257fa29f.png) | ![image](https://user-images.githubusercontent.com/42591237/185862664-b5c4969a-81b8-477a-92d8-0ddbfcbc99d4.png) |

**Comment by szaimen** [comment]
So it seems like the the color of the bright mode wasn't correct in the initial PR. However I still think the contrast of the color isn't as good as it should be. 

@jancborchardt WDYT?

**Comment by szaimen** [comment]
Seems like we need to rework this anywhay due to accessibility issues? Cc @jancborchardt
