### ISSUE TITLE
Large Simple Signup Installations: "Fair use of push notifications" Warnings

### ISSUE THREAD

**Issue by andristeiner** [nextcloud/server#32165]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

* in b578a1e8b56f6b3ecf7dee837af6bd8265f9c0b0, a new feature got introduced to warn and notify admins on large (>5000) installations without subscription, this was released with Nextcloud 23
* we do participate in the simple signup program and run several installations with a couple of thousand users each
* these installations and the required disk space are provided for free, we did not consider obtaining an enterprise plan for them by now therefore
* we do monitor all our Nextcloud installations to not have any "Security & setup warnings" pending, which is the case for all our shared Nextcloud installations after we upgraded them to version 23 yesterday

**Describe the solution you'd like**

* we'd like to run our simple signup installations with some thousand users each, without having warnings about an improper setup
* maybe, make this 5000 seen users limit configurable through an undocumented setting
* or, provide enterprise subscriptions to each simple signup installation (just the technical subscription to satisfy `$this->subscription->delegateHasValidSubscription()`, without all other bells and whistles)

**Describe alternatives you've considered**

* after the upgrades during yesterday's maintenance window, we monkey patched to corresponding check once
* we could stop to monitor "Security & setup warnings" on the affected installations, and just life with the warnings and notifications

**Comment by andristeiner** [comment]
> We are happy to provide this service for free for community users but if you are a big service provider or company then it's fair that this organisations pay a bit for the infrastructure they use.

I agree. It's just that we provide those accounts as part of the provider signup for free as well. Will contact you directly now :+1:

**Comment by muppeth** [comment]
Sorry for re-opening this issue. I've been running quite behind the update schedule this year so got to version 23 only last night. What are the push notifications used for? I did not know my instance uses any of the nextcloud's infra (running my own stun/turn and anything else I thought is required), and I was surprised to know this isn't the case. So some clarity on this one would be appreciated.

**Comment by nickvergessen** [comment]
Its used to push notifications to mobile apps.
Since this requires a developer certificate of the app we proxy the encrypted content through our server.
We can not give out the cert as otherwise everyone could push to any mobile phone not only ones from their own instance and publish any content as an app update.

You can read how that works at:
https://github.com/nextcloud/notifications/blob/master/docs/push-v2.md

We encrypt and sign it in multiple ways/levels, so our server doesn't know whom we push to (no server/user name) and neither the content. Similarly google/apple don't know the content.

**Comment by muppeth** [comment]
@nickvergessen thanks a lot for fast reply. Would https://github.com/nextcloud/notify_push solve this?

**Comment by AndyScherzinger** [comment]
No that is a different component used by the files desktop clients to not have to poll the server for changes.

**Comment by agru** [comment]
I just get alarmed by several schools that the number of users for the fair use policy has been reduced from 5.000 to one tenth, i.e. 500, with commit "[Fix wording of undeliverable push notifications](https://github.com/nextcloud/server/commit/85eb3b2920189af24f16d8a28503bddc32989b48)" by @nickvergessen on Aug 31, 2022. Also @karlitschek - as the limit of 500 users hits a lot of schools, during an already very very difficult time at the moment, it would really be a big problem to convince schools to switch to Nextcloud. Admins that pushed their schools to use Nextcloud would get under fire and it would be water on the mills of the large number of fan boys for "alternative" solutions. So ... was this reduction by mistake or is this really a decision?

**Comment by karlitschek** [comment]
Hi @agru Thanks for the notification. This warning is triggered because the push notifications might be throttled because it might overload our server. I agree that schools probably have not a big budget. We have a special program for institutions with no budget. Can you send me a message? We can probably provide free subscriptions to solve that.

**Comment by agru** [comment]
@karlitschek - I sent you a mail on your karlitschek.de address.

**Comment by EpeR1** [comment]
@karlitschek 
Please explain a little bit more, how Nextcloud notifications are working!
Why should notification messages leave our infrastructure, and go through Nextcloud GmbH servers?
The Google/Android/IOS requires this?
If yes, where can I switch off push-notifications entirely?
We are using Nextcloud servers exactly to care about data-protection.

**Comment by karlitschek** [comment]
Yes. There is a tricky system in place that enables push notification for everyone without the need of google/apple developer accounts and without open network connections and without leaking any data to big tech. 
@EpeR1 Can you send me a mail please? We can provide free subscriptions if you need it. Thanks

**Comment by patricksebastien** [comment]
2 questions:

Is there a way to remove that message on the login page (and maybe elsewhere) _isFairUseOfFreePushService()_
`This community release of Nextcloud is unsupported and push notifications are limited.`

Is there a way to completely disable push notification?

All this without going on the enterprise version that is.

**Comment by Saphar** [comment]
I too would like these messages to go away. It's enough if the Administrator(s) are notified. Our users should not have to see this very confusing message.

**Comment by JPT580** [comment]
As far as I am concerned, our big installation does not even use push notifications, and I would gladly be able to disable the whole feature instead, as our only use case for nextcloud is to provide a very basic web gui to access a bunch of SMB/CIFS shares.

**Comment by nickvergessen** [comment]
Feel free to disable the notifications app then

**Comment by JPT580** [comment]
The only apps that are active in my instance are:
* Brute-force settings
* External storage support
* LDAP user and group backend
* Log Reader
* Monitoring
* Related Resources
* Right click
* Usage survey 

Still, the warning at the login screen persists.

**Comment by patricksebastien** [comment]
@nickvergessen Is it possible to turn off only push notification (mobile / desktop) but keep the notification app (meaning that someone will only get the notification when logging on the webui)?

**Comment by samweisgamdschie** [comment]
We too would like to disable notifications, and more important the message on the login page. Are there any plans on that?

**Comment by AndyScherzinger** [comment]
Currently there are no plan on that, no.

**Comment by patricksebastien** [comment]
> We too would like to disable notifications, and more important the message on the login page. Are there any plans on that?

You can disable the [notification app](https://nextcloud.agora.studio/settings/apps/installed/notifications) _like stated above, I would like to keep the notification app but without the push notification (so the user needs to login to see notification)._

**Comment by samweisgamdschie** [comment]
Sorry for being that rude, but my solution is now to disable the notification app not to bother Nextcloud GmbH with unused/unnecessary traffic and commenting out the warning in LoginController.php . We really love nextcloud, but our customers bother us for this message :/

**Comment by patricksebastien** [comment]
Like ask earlier, would it be possible to disable push notification (desktop / mobile) but keep the notification app (users can see the notification when login to the web-ui)?

**Comment by svenseeberg** [comment]
> We encrypt and sign it in multiple ways/levels, so our server doesn't know whom we push to (no server/user name) and neither the content. Similarly google/apple don't know the content.

This is only partially correct. The device ID is not encrypted and needed to target the specified device. A device ID is definitely personalized information, according to GDPR. Even small organizations (eingetragener Verein in Germany) need to make sure that this piece of information is not entrusted to any third party without a contract. Therefore this functionality should be disabled by default. Alternatively, I would suggest to change the user message accordingly. That means instead of telling the user something about "unsupported" it would be more to the point to tell the user of Nextclouds w/o a license that the push notifications are not covered by a contract.

I would love an official way to disable the push feature. I know how to adopt the code and can do (and have done) so myself. However, I would love to this the official way and also not have to maintain private patches.

**Comment by kolAflash** [comment]
> Yes. There is a tricky system in place that enables push notification for everyone without the need of google/apple developer accounts and without open network connections and without leaking any data to big tech. @EpeR1 Can you send me a mail please? We can provide free subscriptions if you need it. Thanks

What about optionally offering cost free notifications via an own UnifiedPush server, instead of Google/Apple?
https://unifiedpush.org/

&nbsp;

P.S.  
**As far as I understand:**  
This is NOT "NextPush".  
https://github.com/UP-NextPush/server-app  
NextPush redirects notifications for other applications via a Nextcloud server with UnifiedPush. But I GUESS it does not allow sending Nextcloud's own notifications via UnifiedPush.

**Comment by rokejulianlockhart** [comment]
@kolAflash, could you open that as a separate issue and link it here? I think we should genuinely implement UnifiedPush as a point of importance. Every other FOSS app I use uses it.

**Comment by andristeiner** [comment]
We, and our users of the provider signup program, still suffer from this. Can anyone contact me or point me to the right person to talk to about this?

**Comment by hostingnuggets** [comment]
@andristeiner Don't waste your time, they will just send you their marketing guy and he will try to sell you their subscription. Been there, seen that...

**Comment by svenseeberg** [comment]
I posted a workaround in https://github.com/nextcloud/server/issues/38122#issuecomment-1707778412

**Comment by andristeiner** [comment]
> I posted a workaround in [#38122 (comment)](https://github.com/nextcloud/server/issues/38122#issuecomment-1707778412)

Our installation has tens of thousands of free users through the official provider signup program. For housekeeping reasons, we send them notifications and clean up those who don't log in every 6 months. Just disabling the push gateway is not an option, therefore, but thanks anyway.

**Comment by andristeiner** [comment]
> @andristeiner Don't waste your time, they will just send you their marketing guy and he will try to sell you their subscription. Been there, seen that...

We do participate in the official provider signup program since its initiation. Since then, we provided accounts to tens of thousands of users for free. I'm pretty certain that this use case was not considered when implementing this limit, and hope I can reach someone to figure this out here.

**Comment by nextcloud-crm** [comment]
Hey @andristeiner - I got the feedback from our team that you received a reply to your request. Did you check your spam folder? 

@svenseeberg I am sorry, but I could not find a request from you. Can you send it to sales@nextcloud.com? I will reach out to you then. We regularly provide free licenses for small NGOs, so it was never our intention to ignore you. Thank you!

**Comment by andristeiner** [comment]
> Hey @andristeiner - I got the feedback from our team that you received a reply to your request. Did you check your spam folder?

Yes, we got an answer last Thursday. Looks like we're required to buy an enterprise subscription for this use case now. Currently, about twenty thousand user accounts are registered on our installations through the provider signup program. Since the beginning of the program, we have provided this infrastructure and the corresponding user support for free. To be forced into a paid subscription on top of all the other expenses we already have seems kind of ridiculous.

I still hope this is a misunderstanding and I can reach someone here who can help to figure this out.

**Comment by rokejulianlockhart** [comment]
@andristeiner, which installation are you referring to? I'd like to have a look at your instance.

**Comment by hostingnuggets** [comment]
> Yes, we got an answer last Thursday. Looks like we're required to buy an enterprise subscription for this use case now. Currently, about twenty thousand user accounts are registered on our installations through the provider signup program. Since the beginning of the program, we have provided this infrastructure and the corresponding user support for free. To be forced into a paid subscription on top of all the other expenses we already have seems kind of ridiculous.

As mentioned before you are losing your time, they will simply setup a phone call with their best sales agent in order to sell you a subscription/license. Then a few mails exchanges where you explain your point that you don't want to buy an enterprise license for a service you provide for free and then no more answer...

I totally agree with you it is ridiculous, we provide infrastructure/services/support/and more for free and they want to sell you licenses/subscriptions for their own partner program. Actually it is not ridiculous it is sad. We are soon reaching a point that we are going to explain to +30k free users that because of Nextcloud we are going to shutdown this free service.

**Comment by vaneslie** [comment]
> I still hope this is a misunderstanding and I can reach someone here who can help to figure this out.
GitHub is not the right place to discuss this topic, can you please reach out to sales@nextcloud.com instead?

**Comment by andristeiner** [comment]
> > I still hope this is a misunderstanding and I can reach someone here who can help to figure this out.
> > GitHub is not the right place to discuss this topic, can you please reach out to [sales@nextcloud.com](mailto:sales@nextcloud.com) instead?

Tried that already. Either nobody at Nextcloud Sales does care, or I wasn't able to reach the correct person yet.

**Comment by hostingnuggets** [comment]
@andristeiner any news? Did you get that sales/marketing phone call from Nextcloud to sell you their enterprise subscriptions?

**Comment by andristeiner** [comment]
> @andristeiner any news? Did you get that sales/marketing phone call from Nextcloud to sell you their enterprise subscriptions?

Sorry for the late reply, I was away on vacation for a few weeks. Yes, they want to sell us the enterprise subscriptions for all those free users, indeed. We're discussing the further steps internally as we speak. Most probably, this will lead to our withdrawal from the provider signup program.

I still cannot believe this and have some minimal hope that this is just a misunderstanding. If someone from Nextcloud (besides the sales team) does read this, please contact me.

**Comment by hostingnuggets** [comment]
Thank you very much @andristeiner for your feedback. This really confirms my supposition that they act the same with every Nextcloud partner provider. It is a big disappointment and we are also looking into alternative solutions and shutting down this service we provide for free. We will of course make sure to inform our 70k+ users that this free service shutdown is solely due to wrong acting and non-cooperation from Nextcloud's side.

**Comment by jospoortvliet** [comment]
Hi everybody,

I apologize for the confusion. Not every sales conversation might have gone perfect, Nextcloud has grown recently and not everybody in our team is fully aware of the simple signup program. And, of course, mis-understandings can happen. As I initiated the program and we emailed about it in the past, you could reach out to me about this directly.

Anyhow, how I think we should approach it is quite simple and fair.

By becoming a partner, you get to use our name and logo, and get access to Nextcloud Enterprise with support & features, for all your customers. That of course costs money for the paying customers. But then that is called business - you don't provide your service for free either, developers have to eat. The simple signup program, which would not cost money, would be going forward an (optional) marketing benefit of being a partner.

For the users this is better too - we get quite some complaints, and this way, we can provide proper, priority support to those systems that have issues.

If that works for you, reach out to me directly. For those for whom it does not work, that's fine, no hard feelings and sorry for any confusion we've caused.

Greetings,
Jos

PS will close the issue now, with this it should be resolved.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/nextcloud/server/issues/32165#issuecomment-1768071306

That's not a reason to close the issue! Why not consider the option of using Ntfy like so many others have suggested? There's no reason for this notice, because there's no reason to have notifications go through Nextcloud's own servers.

**Comment by svenb1234** [comment]
> But then that is called business - you don't provide your service for free either, developers have to eat.



> we provide infrastructure/services/support/and more for free and they want to sell you licenses/subscriptions for their own partner program.



> Since the beginning of the program, we have provided this infrastructure and the corresponding user support for free.

I do not understand how the first statement is the answer to the latter two.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/nextcloud/server/issues/32165#issuecomment-1768421927

https://github.com/nextcloud/notifications/issues/1225#issue-1275852008

**Comment by apio-sys** [comment]
I'm getting this message on a 2-user install since upgraded to 27.1.3 today. That looks like a bug in the check of the number of users...

**Comment by joshtrichards** [comment]
@apio-sys If so, that's a different matter than this issue is covering. Would you mind either checking/asking on the Help Forums and/or opening a dedicated Issue?

**Comment by apio-sys** [comment]
Indeed a different issue. But interesting though pertaining to this subject. I temporarily lost connection to my OpenLDAP server and saw following errors in the logs :

"CustomMessage":"Lost connection to LDAP server."
"Can not determine user count for OCA\\User_LDAP\\User_Proxy"

That causes then the faire use message to pop-up. Once LDAP fixed again it disappears.
