### ISSUE TITLE
[Bug]: internal links don't seem to get resolved properly

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#32177]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

It's possible to simply copy the address bar link and send it to another user who has access to the file, for them to open it. This seems, at least for some users in Nc 24RC2, broken. Link for an internal Nextcloud GmbH user to test:
<https://cloud.nextcloud.com/apps/files/?dir=/Marketing/Marketing%20Automation%20plan&openfile=5993281>
worked for Max, not for Jos and Christoph. Magic!

Possibly related, but only for SMB/LDAP scenario's: https://github.com/nextcloud/server/issues/27969

### Steps to reproduce

1. copy address bar to a file/folder
2. share with a colleague who has access to that file/folder
3. have them open the link and see the URL in the Breadcrumbs bar, but their root as folder contents

Video (also internal share, as it has some semi-sensitive stuff):
https://cloud.nextcloud.com/f/5993616

### Expected behavior

Colleague should see the file be opened.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
internal nextcloud server
```

**Comment by CarlSchwan** [comment]
weird this is working fine for me, could you look into your developer console and see if there is any errors reported?

Also what browser are you using?

**Comment by jospoortvliet** [comment]
@CarlSchwan https://cloud.nextcloud.com/f/5995231
hope it helps. Christoph had the same issue, perhaps you can work with him to debug as I'm not terribly technical :D

**Comment by PVince81** [comment]
I also couldn't reproduce it so far but what I saw is that when the private link is opened, while the page is loading the "fileid" is not appended yet. It's only after the folder finished loading that we know the fileid and the URL gets adjusted.

So if someone copies the URL before that it won't contain the file id.

I believe this is related to the removal of the redirect for performance reasons, the redirect would directly send to the URL containing the fileid to have it initially there: https://github.com/nextcloud/server/pull/31143
The new logic requires first loading the folder to know it.

One alternative idea would be to adjust the ViewController to pre-fetch the fileid and include it in initialState so that we have it earlier.

**Comment by alexbijma** [comment]
not sure if it's important to know, but I faced this issue also in earlier versions of NC. I think at least already in NC v22.

**Comment by szaimen** [comment]
Hi, please update to 25.0.7 or better 26.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 26-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
