### ISSUE TITLE
Triangle of user menu missing

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#3217]
Unlike the apps menu, the user menu is missing its pointing triangle:
![capture du 2017-01-23 15-26-30](https://cloud.githubusercontent.com/assets/925062/22207701/677fb03c-e180-11e6-8749-35b86b14580f.png)
cc @nextcloud/designers 

Same is true for the notifications menu, it should get the `:after` element for the triangle as well.

**Comment by skjnldsv** [comment]
I have one on my installation 😕 
![capture d ecran_2017-01-23_15-32-16](https://cloud.githubusercontent.com/assets/14975046/22207869/241dab04-e181-11e6-8a4e-f4454a0c0445.png)

**Comment by jancborchardt** [comment]
@skjnldsv I mean the upwards pointing triangle of the menu itself ;) As you can see above the downward one is displayed.

Like so:
![capture du 2017-01-23 17-10-51](https://cloud.githubusercontent.com/assets/925062/22211880/e89c51bc-e18e-11e6-9307-55b1fb6fc1a7.png)

**Comment by skjnldsv** [comment]
@jancborchardt fixed in #3227
