### ISSUE TITLE
[Bug]: Error: disk_free_space(): No such file or directory at /var/www/html/lib/private/Files/Storage/Local.php#383

### ISSUE THREAD

**Issue by atomicnation** [nextcloud/server#32179]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Error on 23.0.3 trying to edit an .odt file with nc office + collabora online

### Steps to reproduce

1. Activate Next Cloud Office + Collabora Online
2. Login as any user
3. Upload and try to edit an .odt or .docxfile

### Expected behavior

Open the online editor.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Not accessible
```

**Comment by szaimen** [comment]
thanks but lets handle this in https://github.com/nextcloud/server/issues/32178
