### ISSUE TITLE
l10n: String is cutted in half and add variable as placeholder

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/server#32171]
https://github.com/nextcloud/server/blob/fec36ca91323fa72d82e5cc964019c2f21bbbca0/lib/private/legacy/OC_Util.php#L742

Only `The required '` is shown at Transifex.

Please change to use "$requiredConfig" as placeholder.

**Comment by Valdnet** [comment]
@skjnldsv Please correct the code according to @rakekniven recommendation 😉.

Translators are waiting for a quick change 😁.
