### ISSUE TITLE
No way to activate bright mode when in dark mode

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#32176]
After https://github.com/nextcloud/server/pull/31751:

When your system in in dark mode, Nextcloud will be shown in dark mode as well because the default theming option respects this setting. There is unfortunatley no way to enable bright mode then anymore.

cc @skjnldsv @jancborchardt @nimishavijay how could we solve that?

**Comment by xeruf** [comment]
classically as it is done in many android apps: Dropdown to choose dark/light/follow system

**Comment by xeruf** [comment]
See https://github.com/nextcloud/server/issues/12276#issuecomment-903146358, which is about adapting to `prefers-color-scheme` and not yet solved, which is also my experience.

Also, an option to enable dark mode for all users by default from the config.php would be handy.

**Comment by szaimen** [comment]
The feature is implemented by default with https://github.com/nextcloud/server/pull/31751 but we don't have the mentioned switch to let it turn off. So a possible solution to this problem.

**Comment by skjnldsv** [comment]
@jancborchardt @nimishavijay 
![image](https://user-images.githubusercontent.com/14975046/165583047-fa798df0-985d-468e-8fac-9874dc77a327.png)


How do you want to tackle that UX/UI wise? Shall we add a dedicated entry named "system default" ?

**Comment by szaimen** [comment]
> @jancborchardt @nimishavijay ![image](https://user-images.githubusercontent.com/14975046/165583047-fa798df0-985d-468e-8fac-9874dc77a327.png)
> 
> How do you want to tackle that UX/UI wise? Shall we add a dedicated entry named "system default" ?

Sounds good to me. This should then be the default option, imo :)

**Comment by skjnldsv** [comment]
Done @jancborchardt and @nimishavijay, see #32195 :rocket:
