### ISSUE TITLE
[NC 24.0.0 RC2] l10n: There are no translated text strings

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#32187]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

There is no translation of the text strings in the user profile:

![obraz](https://user-images.githubusercontent.com/47037905/165520455-6ba38be9-81e3-4609-8b8e-fb50e2adb297.png)

In NC 23, the strings are displayed correctly.

### Steps to reproduce

1. Select the menu.
2. Select "View profile".

### Expected behavior

Translated text strings in your native language.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
-
```

### Additional info

Nextcloud 24.0.0 RC2

**Comment by szaimen** [comment]
I can confirm. Somehow they seem to not be loaded but they are present in the l10n dir...
I get this error in the console:
![image](https://user-images.githubusercontent.com/42591237/165525800-9a5757aa-2909-498d-9d66-271b4e35f012.png)
cc @artonge @Pytal maybe you have some ideas?
