### ISSUE TITLE
Increase default `max_chunk_size` to `1 GB`

### ISSUE THREAD

**Issue by devnoname120** [nextcloud/server#32208]
Why is `max_chunk_size` set to `10 MB` by default? That's pretty low.

What would you think about upping it to something like `1 GB`?

Code reference: https://github.com/nextcloud/server/blob/0447b53bda9fe95ea0cbed765aa332584605d652/apps/files/lib/App.php#L57

The weird thing is that the VM install script overrides this to `100 MB`. Why is it different from the default?
https://github.com/nextcloud/vm/blob/c4b764acbd4fb3c66acb24cddfe21774a1363126/nextcloud_install_production.sh#L540

**Comment by szaimen** [comment]
just set the value to whatever you want

**Comment by devnoname120** [comment]
> just set the value to whatever you want

Cloud hosted NextCloud often don't give the chance to modify the value, and they used the default.

Can't we change the default?

**Comment by szaimen** [comment]
I tried :)
https://github.com/nextcloud/server/pull/26978

**Comment by devnoname120** [comment]
@szaimen Any ideas if there is a way to fetch `max_chunk_size` from the API? I'm adding support for chunked upload in rclone.org and I'd like to programmatically determine the optimal chunk size (unless overriden by the user).

**Comment by szaimen** [comment]
sry no idea
