### ISSUE TITLE
[Bug]:  Imposible to set max_execution_time and max_input_time in php.ini

### ISSUE THREAD

**Issue by mickenordin** [nextcloud/server#32209]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When configuring max_execution_time and max_input_time in php.ini the new settings will not take and settings/admin/serverinfo will forever show 3600 no matter what you set it to. This is not the case with other settings such as max_file_size.

I am pretty sure that the problem is these two lines of code where these two variables are hard coded to 3600:

https://github.com/nextcloud/server/blob/135bdb3d5830672214149fa0b75fadd29b20b844/lib/base.php#L634-L635

Changing the hard coded value will make the web interface update to the value you set, indicating that indeed Nextcloud is using the hard coded value rather than the value the administrator has configured in php.ini.  

### Steps to reproduce

1. Update max_execution_time and max_input_time in php.ini

### Expected behavior

Settings are honored by Nextcloud, and reported in settings/admin/serverinfo 

### Installation method

Other

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "appstoreenabled": false,
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "forcessl": true,
        "overwriteprotocol": "https",
        "objectstore": {
            "class": "\\OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "***REMOVED SENSITIVE VALUE***",
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "region": "us-east-1",
                "hostname": "***REMOVED SENSITIVE VALUE***",
                "port": "",
                "objectPrefix": "urn:oid:",
                "autocreate": false,
                "use_ssl": true,
                "use_path_style": true,
                "legacy_auth": false
            }
        },
        "csrf.disabled": true,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "localhost",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "config_is_read_only": true,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "dbtype": "mysql",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "gs.enabled": "true",
        "gs.federation": "global",
        "gs.trustedHosts": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "gss.discovery.manual.mapping.file": "\/var\/www\/html\/mappingfile.json",
        "gss.discovery.manual.mapping.parameter": "urn:oid:1.3.6.1.4.1.5923.1.1.1.6",
        "gss.discovery.manual.mapping.regex": true,
        "gss.jwt.key": "***REMOVED SENSITIVE VALUE***",
        "gss.master.admin": [
            "admin",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "gss.master.url": "***REMOVED SENSITIVE VALUE***",
        "gss.mode": "slave",
        "gss.user.discovery.module": "\\OCA\\GlobalSiteSelector\\UserDiscoveryModules\\ManualUserMapping",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "log_type": "file",
        "loglevel": 0,
        "lookup_server": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_template_class": "OCA\\DriveEmailTemplate\\EMailTemplate",
        "mysql.utf8mb4": true,
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "templatedirectory": "",
        "skeletondirectory": "",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "twofactor_enforced_excluded_groups": [],
        "version": "21.0.9.2",
        "app_install_overwrite": [
            "globalsiteselector"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - drive_email_template: 0.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_external: 1.12.1
  - files_pdfviewer: 2.1.1
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - richdocuments: 4.2.4
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_totp: 6.1.0
  - twofactor_u2f: 6.2.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.1
Disabled:
  - encryption
  - files_markdown
  - files_texteditor
  - globalsiteselector: 2.1.0
  - loginpagebutton
  - onlyoffice: 7.2.0
  - twofactor_admin
  - user_ldap
  - user_saml
```

### Nextcloud Signing status

```shell
N/A
```

### Nextcloud Logs

```shell
N/A
```

**Comment by szaimen** [comment]
Hi, can you create a PR with your fix for discussion?

**Comment by kesselb** [comment]
I guess we enforce those values for better compatibility with shared hosting provides. Is your request related to a concrete problem (like things do not work because 1h is not enough)?

**Comment by mickenordin** [comment]
> I guess we enforce those values for better compatibility with shared hosting provides. Is your request related to a concrete problem (like things do not work because 1h is not enough)?

Yes, I am trying to support transfer of large files in one of the instances I run for different clients. These specific settings are mentioned in the docs as things to modify to be able to support large files transfers:
https://docs.nextcloud.com/server/20/admin_manual/configuration_files/big_file_upload_configuration.html

I actually have issues with uploading files as small as 4GiB through the web interface on a somewhat slow connection about 6MiB/sec, so this is one of the things I am investigating.

**Comment by mickenordin** [comment]
> Hi, can you create a PR with your fix for discussion?

I actually just modified the hard coded value directly in the code, but sure, I can see if I can write some code that picks the larger value of 3600 and the value set in php.ini during the day.

**Comment by mickenordin** [comment]
I have created a PR # #32216 that fixes this issue

**Comment by kesselb** [comment]
> I actually have issues with uploading files as small as 4GiB through the web interface on a somewhat slow connection about 6MiB/sec, so this is one of the things I am investigating.

That sounds weird :thinking: 

Web interface is using chunks to upload big files. By default a file is uploaded in 10 MB chunks (https://docs.nextcloud.com/server/20/admin_manual/configuration_files/big_file_upload_configuration.html#adjust-chunk-size-on-nextcloud-side). The last request is then to assembly the files (and in your setup upload to s3). Assembly and upload may take some time but more than 1 hour?

1) Is chunking still enabled? Sometimes people disable it especially if the connections are fast. 
2) What is not working exactly? Is the upload interrupted (e.g. uploading a chunk fails due timeouts) or the assembly request. If the assembly request runs in a timeout that could be a slow disk (where Nextcloud is installed) or something with the S3 connection.  

I guess it's fine when increasing the timeouts solve the problem. Yet it's a bit weird the either assembly or upload run into issues here.

**Comment by mickenordin** [comment]
> > I actually have issues with uploading files as small as 4GiB through the web interface on a somewhat slow connection about 6MiB/sec, so this is one of the things I am investigating.
> 
> That sounds weird thinking
> 
> Web interface is using chunks to upload big files. By default a file is uploaded in 10 MB chunks (https://docs.nextcloud.com/server/20/admin_manual/configuration_files/big_file_upload_configuration.html#adjust-chunk-size-on-nextcloud-side). The last request is then to assembly the files (and in your setup upload to s3). Assembly and upload may take some time but more than 1 hour?
> 
>     1. Is chunking still enabled? Sometimes people disable it especially if the connections are fast.
> 
>     2. What is not working exactly? Is the upload interrupted (e.g. uploading a chunk fails due timeouts) or the assembly request. If the assembly request runs in a timeout that could be a slow disk (where Nextcloud is installed) or something with the S3 connection.
> 
> 
> I guess it's fine when increasing the timeouts solve the problem. Yet it's a bit weird the either assembly or upload run into issues here.

I have noticed that there is a difference between uploads in the web interface and with pure webdav. For instance using rclone with a nextcloud backend will upload the entire file to the temp space, where as when uploading in the web interface will indeed chunk the upload.
