### ISSUE TITLE
[Bug]: trashbin endpoint doesnt return extra properties

### ISSUE THREAD

**Issue by Freundschaft** [nextcloud/server#32215]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

when I query PROPFIND according to https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/trashbin.html
I receive the list of files and recovering works well, but I dont see the extra properties that are supposed to be there.

Anyone else who has the same issue?

### Steps to reproduce

1. connect to trashbin via webdav
2. perform a PROPFIND on /trash

### Expected behavior

I expect to receive the custom properties as outlined in https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/trashbin.html

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
-
```

**Comment by szaimen** [comment]
![image](https://user-images.githubusercontent.com/42591237/165823177-9eac9803-602a-48ae-9a4e-9c49dbfc9f23.png)
?

**Comment by kesselb** [comment]
When dealing with webdav requests it's often helpful to provide your request as curl example to make it easier to reproduce the case.

>  but I dont see the extra properties that are supposed to be there.

I think they are not provided by default. It's necessary to request them. Check https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/basic.html#requesting-properties for more details.

**Comment by Freundschaft** [comment]
aah perfect

> When dealing with webdav requests it's often helpful to provide your request as curl example to make it easier to reproduce the case.
> 
> > but I dont see the extra properties that are supposed to be there.
> 
> I think they are not provided by default. It's necessary to request them. Check https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/basic.html#requesting-properties for more details.

aah perfect, thanks a lot. I assumed they'd just be returned by default. thanks!
