### ISSUE TITLE
Test apps against php 7.1 on travis

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#3221]
- [x] https://github.com/nextcloud/templateeditor/pull/15
- [x] https://github.com/nextcloud/serverinfo/pull/79
- [x] https://github.com/nextcloud/password_policy/pull/35
- [x] https://github.com/nextcloud/notifications/pull/57
- [x] https://github.com/nextcloud/nextcloud_announcements/pull/20
- [x] https://github.com/nextcloud/firstrunwizard/pull/32
- [x] https://github.com/nextcloud/files_texteditor/pull/26
- [x] https://github.com/nextcloud/files_retention/pull/22
- [x] https://github.com/nextcloud/files_pdfviewer/pull/19
- [x] https://github.com/nextcloud/files_automatedtagging/pull/21
- [x] https://github.com/nextcloud/files_accesscontrol/pull/51
- [x] https://github.com/nextcloud/activity/pull/110

@MorrisJobke @rullzer

**Comment by MorrisJobke** [comment]
> nextcloud/nextcloud_announcements#20

Failing tests 😝

**Comment by rullzer** [comment]
All done
