### ISSUE TITLE
[Bug]: Dashboard "Recent Activity" list fails to load. Throws "Error: Request failed with status code 304"

### ISSUE THREAD

**Issue by heyheyhello** [nextcloud/server#32222]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello! In the last week my "Recent Activity" dashboard list stop rendering. It was right around the time I added my first External Storage to Nextcloud. I was running 23.0.2 when it happened, and have since updated to Beta 24.0.0 RC3 but the issue persists.

<img width="1059" src="https://user-images.githubusercontent.com/44614862/166066536-7812237a-b42c-4dac-9d01-a6585cab3cf0.png">

Every few seconds I see a flicker of it trying to refresh `/ocs/v2.php/apps/activity/api/v2/activity/by`

The network request says "cached" despite having "Disable Cache" in my devtools...

![image](https://user-images.githubusercontent.com/44614862/166067029-8cd228a5-b3a6-4bbb-b5bd-cd4d056acbc7.png)

<img width="350" src="https://user-images.githubusercontent.com/44614862/166067285-a0739480-77ff-495a-b264-41af08e25562.png">

This happens in Dashboard.vue:

<img width="450" src="https://user-images.githubusercontent.com/44614862/166067953-b4a4f09d-2657-4fd8-a160-155aedba08b5.png">

The 304 response body is empty for `/ocs/v2.php/apps/activity/api/v2/activity/by`

**This is not a reverse proxy issue because my proxy has not changed in months and everything has been working fine** I believe this is related to turning on External Storage and having it flood the activity log...?

The activity log at URL /apps/activity/ works fine and loads instantly. **It does not have any entries about external storage but I swear it did at first...**

![image](https://user-images.githubusercontent.com/44614862/166067829-0070b678-f829-4d13-8c91-4ff1cd2fcd43.png)

Are you aware of any ways to debug the "activity/by" API?

**If I use manually hit /ocs/v2.php/apps/activity/api/v2/activity (without the /by) then it works:**

<img width="350" src="https://user-images.githubusercontent.com/44614862/166069105-e0a5a355-243b-4711-8f5e-6f3c900d1277.png">

<img width="350" src="https://user-images.githubusercontent.com/44614862/166068295-da6e936c-9c09-437f-98ac-bb35bed03552.png">

Which is surprising but good?

Any debugging advice is appreciated!

### Steps to reproduce

1. Setup a "Recent Activity" tab on the dashboard and make sure it's working.
2. Enable the "External Storage" app in admin settings and add a folder. Mine was "Local" to "/mnt/syncthing" - it's just a bunch of MP3 files (~4000 files).
3. Visit the dashboard
4. The "Recent Activity" tab has stopped working.

### Expected behavior

API /ocs/v2.php/apps/activity/api/v2/activity/by should return 200 OK.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

SQlite

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "domain.tld"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "version": "24.0.0.11",
        "overwrite.cli.url": "https:\/\/domain.tld",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF"
        ],
        "preview_max_x": "1024",
        "preview_max_y": "1024",
        "jpeg_quality": "60",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "beta",
        "app_install_overwrite": [
            "cookbook"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
sudo -u www-data php occ app:list
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - calendar: 3.2.2
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - cookbook: 0.9.11
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - integration_github: 1.0.2
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - mediadc: 0.1.9
  - nextcloud_announcements: 1.13.0
  - notes: 4.3.1
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - photos: 1.6.0
  - previewgenerator: 4.0.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - unroundedcorners: 1.0.3
  - updatenotification: 1.14.0
  - viewer: 1.8.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - bruteforcesettings: 2.4.0
  - circles: 22.1.1
  - encryption
  - password_policy: 1.12.0
  - survey_client: 1.10.0
  - unsplash: 1.2.4
  - user_ldap
  - user_status: 1.2.0
  - weather_status: 1.3.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by heyheyhello** [comment]
Confirmed it is not the proxy layer, as the FsatCGI PHP layer is returning 304 per `$upstream_status`:

```
192.168.0.14 - - [29/Apr/2022:14:55:35 -0700] "GET /ocs/v2.php/apps/activity/api/v2/activity/by HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0" request_time=0.084 upstream_status=304 upstream_cache_status=- upstream_response_time=0.084 upstream_response_length=0
192.168.0.14 - - [29/Apr/2022:14:55:36 -0700] "GET /ocs/v2.php/apps/activity/api/v2/activity/by HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:99.0) Gecko/20100101 Firefox/99.0" request_time=0.084 upstream_status=304 upstream_cache_status=- upstream_response_time=0.084 upstream_response_length=0
```

**Comment by Naweap** [comment]
The issue still occurs to me with Apache

**Comment by szaimen** [comment]
Hi, please update to 25.0.7 or better 26.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 26-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
