### ISSUE TITLE
Header layout issue on narrow screens

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#3225]
The app name and arrow are line-broken, that should not happen:
![capture du 2017-01-23 23-10-10](https://cloud.githubusercontent.com/assets/925062/22225033/30c891c6-e1c1-11e6-8fec-fdda82061029.png)

cc @nextcloud/designers

**Comment by skjnldsv** [comment]
It only happens on very small windows.
Anyhow: #3226

**Comment by jancborchardt** [comment]
Also happens with longer app names + long user names like mine ;)

**Comment by skjnldsv** [comment]
@jancborchardt: don't exaggerate!  😄
