### ISSUE TITLE
[Bug]: `trusted_proxies` does not support IPv6 subnets

### ISSUE THREAD

**Issue by LukeLR** [nextcloud/server#32253]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I'm running Nextcloud behind a reverse proxy, which has dynamic IPv4 and IPv6 addresses. I've added both the IPv4 and IPv6 subnets to the `trusted_proxies`-variable:
```
  'trusted_proxies' =>
   array (
     0 => '192.168.0.0/16',
     1 => '169.254.0.0/16',
     2 => 'fe80:0000:0000:0000:0000:0000:0000:0000/16',
     3 => 'fe80::b41a:99ff:feac:a657',
   ),
```
However, the IPv6 subnet specification is ignored, only the IPv4 subnet specification works. The [reverse proxy documentation](https://docs.nextcloud.com/server/24/admin_manual/configuration_server/reverse_proxy_configuration.html) also only lists IPv4 subnet ranges as supported, IPv6 subnet ranges appear to be unsupported. That is a real deal-breaker for IPv6 support in my case, as IPv6 support will stop working as soon as the IPv6 address of the reverse proxy changes the next time. Is there a reason, why subnet ranges are only supported for IPv4 addresses and not for IPv6? Thanks in advance!

### Steps to reproduce

1. Install Nextcloud behind a reverse proxy with dynamic IPv6 addressing (e.g. a container setup)
2. Add IPv4 and IPv6 subnet ranges to the `trusted_proxies` configuration variable
3. See that only IPv4 access works, IPv6 requests will fail due to the IPv6 subnet range not being recognized in `trusted_proxies`.

### Expected behavior

It shouldn't matter whether Nextcloud is accessed from a IPv4 or IPv6 reverse proxy when dynamic addressing is used.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
        ],
        "version": "21.0.0.18",
        "overwrite.cli.url": "http:\/\/cvjm.rocks",
        "dbport": "",
        "dbtableprefix": "oc_",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - bruteforcesettings: 2.4.0
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - nextcloud_announcements: 1.10.0
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - updatenotification: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"kJ9Z9LhlNoQOgqncqwfY","level":3,"time":"2022-05-01T17:20:10+00:00","remoteAddr":"::1","user":"admin","app":"PHP","method":"GET","url":"/index.php/apps/theming/img/core/filetypes/image.svg?v=0","message":"Module 'zip' already loaded at Unknown#0","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0","version":"21.0.0.18"}
{"reqId":"Jbys6tFhrVfqPokprKws","level":3,"time":"2022-05-01T17:20:24+00:00","remoteAddr":"::1","user":"admin","app":"PHP","method":"GET","url":"/ocs/v2.php/apps/user_status/api/v1/user_status","message":"Module 'zip' already loaded at Unknown#0","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0","version":"21.0.0.18"}
```

**Comment by solracsf** [comment]
See https://github.com/nextcloud/server/blob/master/config/config.sample.php#L1921-L1922

This is not a bug, it's just not implemented yet.

**Comment by Schmuuu** [comment]
It seems you only use the link local IPv6 address (fe80:...) and not the global address. So you could configure the address (the host part) to be static (e.g. disable the IPv6 privacy feature which rotates the link local address).

Only the global IPv6 address is changing due to the changing provider prefix, but that wouldn't be an issue if you only use the link local address.

**Comment by LukeLR** [comment]
If you don't agree that this is a bug, maybe we can transform this issue into a feature request at least?
