### ISSUE TITLE
Allow adding a status only with an Emoji, without the need to include text next to it

### ISSUE THREAD

**Issue by mstolf** [nextcloud/server#32255]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Currently it is not possible to add a status to a user with only an emoji, it is necessary to have a text next to it to save the emoji

**Describe the solution you'd like**
Allow saving user status with emoji only

**Describe alternatives you've considered**
Currently to save the emoji, it is necessary to put a blank space in the status text field

**Comment by joshtrichards** [comment]
Hi @mstolf Can you confirm you're still unable to do so? I can't reproduce this behavior. I'm able to set my status to solely an emoji.
