### ISSUE TITLE
version.php location

### ISSUE THREAD

**Issue by vincentDcmps** [nextcloud/server#32269]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 
hello,

I have switch my nextcloud instance in docker via [nomad](https://git.ducamps.win/vincent/nomad/src/branch/master/nextcloud.nomad)
we must to put all nextcloud root folder to a share because file version.php is statefull. 
my remote folder is a samba share so it's not optimized to get litle file.
do you have in roadmap something like moving version.php file in config directory to avoid to put full root folder on a share?

**Comment by joshtrichards** [comment]
What do you mean `version.php` is statement? It's a static file. Each new version of Server has a different `version.php`, but all the other files in the installation folder would also be different with a new version of Server.

This file isn't written to during normal operation.

**Comment by vincentDcmps** [comment]
Hi honestly don't remember why I have an issue two year ago with this file.
I think that we can close this issue :)
