### ISSUE TITLE
[Bug]: RTF (Rich Text Format) file gets broken when uploading it to Nextcloud and downloading from there again

### ISSUE THREAD

**Issue by claell** [nextcloud/server#32267]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I just discovered that under some conditions, an RTF file gets broken for me in a way that it cannot be opened again in MS Word (crash showing a document restore which is not working).

Not sure what causes this and not that much time right now, but wanted to note this, so this is listed somewhere as a potential issue that can happen in some cases.

### Steps to reproduce

1. Upload the RTF file (either using sync client, folder sync activated, no virtual files; or trough Browser)
2. Download through Browser (Firefox used in my case) - Maybe the issue is introduced here
3. Open downloaded file, it is broken

### Expected behavior

The downloaded file can be opened just fine

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Not known, no admin access
```

### Additional info

File is confidential, but I might be able to share it under certain conditions.

**Comment by claell** [comment]
Files next to each other: Left downloaded version, Right: original version that was uploaded
![grafik](https://user-images.githubusercontent.com/6171135/166686358-f624b5c0-7648-4c85-90c0-92df4153ef4b.png)

**Comment by szaimen** [comment]
which NC version?

**Comment by claell** [comment]
23.0.3 on Server according to help menu.

**Comment by claell** [comment]
If you have a private communication channel, we can try to reproduce together.

**Comment by z0rgster** [comment]
I could not reproduce this with NC 24.0.3. and the desktop client 3.5.4
I created an RTF file, uploaded it via desktop client and downloaded ist via browser. The file could be opened but Word gave a warning because the file was downloaded from the web. That information is stored an [alternative data stream](https://hshrzd.wordpress.com/2016/03/19/introduction-to-ads-alternate-data-streams/). ADS can be viewed with [this tool](https://www.nirsoft.net/utils/alternate_data_streams.html).

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
