### ISSUE TITLE
[Bug]: Folders with single brackets are not accessible - NC24 regression

### ISSUE THREAD

**Issue by tgurr** [nextcloud/server#32286]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

We got user complaints about folders with single brackets being not accessible anymore since the update to nextcloud 24. I was able to reproduce it with e.g.:

![nextcloud24_bug](https://user-images.githubusercontent.com/414984/167084449-ebfaec2b-2008-4862-983b-01e281947eee.png)

### Steps to reproduce

1. create a folder with a single bracket "(" or ")"
2. try to access the folder by clicking it
3. see yourself not being able to access that folder

### Expected behavior

Being able to access the folders (like before with NC <24).

### Installation method

Manual installation

### Operating system

Other

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.0.12",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "versions": "false",
        "maxZipInputSize": 268435456,
        "allowZipDownload": true,
        "forcessl": true,
        "knowledgebaseenabled": false,
        "skeletondirectory": "",
        "force_language": "de_DE",
        "force_locale": "de_DE",
        "default_phone_region": "DE",
        "appstoreenabled": true,
        "updatechecker": false,
        "auth.webauthn.enabled": false,
        "maintenance": false,
        "theme": "",
        "loglevel": "2",
        "trusted_domains": [
            "nextcloud.xxx.xxx"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.xxx.xxx",
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "quota_warning",
            "bruteforcesettings",
            "files_antivirus"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - bruteforcesettings: 2.4.0
  - calendar: 3.2.2
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - files: 1.19.0
  - files_antivirus: 3.2.2
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_videoplayer: 1.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - quota_warning: 1.14.0
  - richdocuments: 6.0.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - spreed: 14.0.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - viewer: 1.8.0
  - workflowengine: 2.6.0
Disabled:
  - dashboard: 7.0.0
  - encryption
  - federation: 1.0.1
  - files_external
  - files_pdfviewer: 2.4.0
  - files_trashbin: 0.8.0
  - files_versions: 1.0.2
  - firstrunwizard: 1.1
  - nextcloud_announcements: 1.0
  - recommendations: 0.4.0
  - support: 1.0.0
  - survey_client: 0.1.5
  - updatenotification: 1.1.1
  - user_ldap
  - user_status: 1.0.0
  - weather_status: 1.0.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Nothing logged.
```

### Additional info

```
merged-index.js?v=9e37fa49-29:495 Uncaught SyntaxError: Invalid regular expression: //(1 test/: Unterminated group (at merged-index.js?v=9e37fa49-29:495:34)
    at String.search (<anonymous>)
    at BreadCrumb.setDirectory (merged-index.js?v=9e37fa49-29:495:34)
    at FileList._setCurrentDir (merged-index.js?v=9e37fa49-29:6188:20)
    at FileList.changeDirectory (merged-index.js?v=9e37fa49-29:6116:9)
    at Object.actionHandler (merged-index.js?v=9e37fa49-29:3625:24)
    at Object.action (merged-index.js?v=9e37fa49-29:3040:13)
    at FileList._onClickFile (merged-index.js?v=9e37fa49-29:4974:13)
    at ge (_executeBound.js:8:65)
    at HTMLAnchorElement.<anonymous> (bind.js:10:12)
    at HTMLAnchorElement.<anonymous> (restArguments.js:16:27)
```

**Comment by RoggerTan** [comment]
Hi @tgurr, 
Nextcloud 24.0.0.12 contains code changes from this [commit](https://github.com/nextcloud/server/commit/0942aed8db353b29d39ed4f895111262af2e755a), but has been [reverted lately](https://github.com/nextcloud/server/commit/66e61be9ca3b6acfc18c72f65afe3f894b76d54e). Here's the related [pull request](https://github.com/nextcloud/server/pull/30925). 
You can fix it by replacing `apps/files/js/breadcrumb.js` with the reverted.

**Comment by solracsf** [comment]
Should be fixed in v24.0.1. Please upgrade, test and report back.

**Comment by tgurr** [comment]
> Should be fixed in v24.0.1. Please upgrade, test and report back.

Fixed it for me.

**Comment by szaimen** [comment]
Thanks for the feedback! Closing then

**Comment by pmocek** [comment]
This appears to be about parentheses, not about brackets.
