### ISSUE TITLE
NC 11.0.1 + Gallery 16.0.0: Upload button has no effect

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/server#3229]
### Steps to reproduce
1. Open the gallery
2. Click on the + sign
3. Try to upload a picture

### Expected behaviour
Picture should be uploaded

### Actual behaviour
Nothing happens

### More information
https://help.nextcloud.com/t/nc-11-gallery-16-0-0-no-picture-upload-possible/

**Comment by MorrisJobke** [comment]
cc @oparoz

**Comment by oparoz** [comment]
Moved to https://github.com/nextcloud/gallery/issues/200
