### ISSUE TITLE
[Bug]: Fields in profile get emptied if not valid

### ISSUE THREAD

**Issue by Luctia** [nextcloud/server#32294]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When editing your profile, there are certain fields that get validated after some time (phone number, website) After a couple of seconds of not typing, the data in these fields gets sent to the backend where this happens (as far as I can see/suspect):
1. Data is received
2. The server tries to make sense of the data, validating it and adding stuff (like a country code in the case of phone number)
3. Saves
4. Sends all data back to the frontend to synchronize

This all works fine, except when the data entered in the field is incorrect. However, unless you're pasting data, you can't provide correct data in one go, you have to type the phone number into the field. If you're a bit slow, the frontend goes "alright, you haven't typed for a while, you must be done" and sends the data to the backend, which then goes "this makes no sense, I will not save this data". The backend still sends all the profile data though, so that includes an empty phone number field, which is then inserted into the field on the frontend.

This all results in a rather frustrating experience where, while you're trying to enter your phone number, the fields constantly gets cleared. On top of this, the frontend will happily display a checkmark in the field when it's empty, almost taunting you and giving you the idea that it might have been saved.

### Steps to reproduce

1. Insert a bad phone number or website
2. Wait

### Expected behavior

The field should not be emptied within one page visit. If you close the page and open it again, the incorrect data should be gone, but not while you're still on the page. This can be established by, for example, getting a change in place in the frontend which checks if a field received from the backend is empty and not replacing the existing value if it is not empty, or the backend sending `null` back if a field is invalid so the frontend can be made to understand that it should at most display a message saying the input is incorrect.

### Installation method

Official All-in-One appliance

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Could not open file: occ (I'm pretty sure this is irrelevant for this issue anyway)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by Luctia** [comment]
@szaimen Seems like now I can't change my phone number at all anymore, or I could be missing a save button? (v25.0.2)

**Comment by szaimen** [comment]
> @szaimen Seems like now I can't change my phone number at all anymore, or I could be missing a save button? (v25.0.2)

Please create a new bug report about this if there shouldnt be one already.
