### ISSUE TITLE
[Bug]: impossible to open folder

### ISSUE THREAD

**Issue by weeger** [nextcloud/server#32307]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After updating to 24.0.0 (Docker version), it is not anymore possible to open folder named with the pattern : "[bracket with a dash] folder name". Example : 

![image](https://user-images.githubusercontent.com/1240307/167385744-03c9421c-5b8c-4b38-9cc8-008bebf0d5ac.png)

When clicking on it, it results on a regular expression fail : 

![image](https://user-images.githubusercontent.com/1240307/167385846-934c2727-e246-45ee-9c52-9f9c7fd87167.png)

The quick fix is just to remove the dash in the folder name.

### Steps to reproduce

1. Create a folder like "[Test-name] My folder"
2. Click on it to open
3. It does not open

### Expected behavior

Folder should open.

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
- accessibility: 1.10.0
  - activity: 2.16.0
  - apporder: 0.15.0
  - breezedark: 24.0.0
  - calendar: 3.3.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.1.0
  - contactsinteraction: 1.5.0
  - dav: 1.22.0
  - deck: 1.7.0
  - event_update_notification: 1.5.0
  - extract: 1.3.5
  - federatedfilesharing: 1.14.0
  - files: 1.19.0
  - files_markdown: 2.3.6
  - files_mindmap: 0.0.26
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - forms: 2.5.0
  - impersonate: 1.11.0
  - lookup_server_connector: 1.12.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - onlyoffice: 7.3.4
  - password_policy: 1.14.0
  - photos: 1.6.0
  - polls: 3.6.1
  - provisioning_api: 1.14.0
  - richdocuments: 6.0.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - side_menu: 2.3.5
  - support: 1.7.0
  - tasks: 0.14.4
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - welcome: 1.0.1
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - circles: 0.21.1
  - dashboard: 7.2.0
  - encryption
  - federation: 1.8.0
  - files_external
  - firstrunwizard: 2.10.0
  - logreader: 2.0.0
  - nextcloud_announcements: 1.1
  - privacy: 1.0.0
  - recommendations: 0.4.0
  - serverinfo: 1.2.0
  - survey_client: 1.4.0
  - systemtags: 1.2.0
  - user_ldap: 1.2.1
```

**Comment by Mer0me** [comment]
Folders with some combination of special chars cannot be open anymore here too, since NC24.

Folder named "1) Test" cannot be opened, but "(1) Test" is OK.
Folders with spaces in names are not problematic on our instance.

This regression is very annoying and should be patched as soon as possible.

**Comment by solracsf** [comment]
Let's track this at https://github.com/nextcloud/server/issues/32286
