### ISSUE TITLE
User App store

### ISSUE THREAD

**Issue by R7JANV1** [nextcloud/server#32319]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Many users want to use different apps individually. One user wants to use app A and B, another user wants to use app A and C. When all apps are installed, all apps are displayed for each user and the overview is quickly lost.

**Describe the solution you'd like**
An app store for users would solve this problem. The function would look like this:
The administrator can enable the App Store feature.
Users have an overview of the apps installed on the server in the settings. Each user can enable or disable apps for themselves. Optionally, the administrator can specify apps that are enabled for everyone or enabled for specific groups.

**Additional context**
With this feature, Large Instances and Nextcloud providers can provide users with many individual features and apps and each user can customize their features to fit themselves.

**Comment by szaimen** [comment]
Hm... I think this is already covered by https://apps.nextcloud.com/apps/apporder so closing

**Comment by R7JANV1** [comment]
unfortunately not, we use App Order for that at the moment but it only covers a small part.  E.g. Extensions like the Video Converter or NC Office cannot be activated or deactivated.  This option is also not suitable for groups.
