### ISSUE TITLE
Switch dark mode detection off

### ISSUE THREAD

**Issue by lars-becker** [nextcloud/server#32338]
**Is your feature request related to a problem? Please describe.**

Since a recent update Nextcloud detects if the system is using dark mode. This is quite annoying because the user has no way to turn it off, but there are so many bugs with the dark design that it is really decreasing the user experience.

**Describe the solution you'd like**
The possibility to switch dark mode off; either globally or on the user level.

**Describe alternatives you've considered**
They're no viable alteratives right now.  The only alternative would be to fix dark mode; which doesn't seem feasible in the near future; especially if one uses third party add-ons.

**Comment by alexanderdd** [comment]
related: https://help.nextcloud.com/t/cant-deactivate-dark-mode/136066/6

I have the same problem. Linux Mint 20.3, Firefox 100, Nextcloud 23.0.4 with all apps up to date.

It works normally in Chromium 101.0.4951.54

**Comment by nickian** [comment]
Any updates on this? Been almost a year. Is it still not possible to turn off dark mode? There should be an "appearance and accessibility option the admin, not just the user, settings. Or at least a value that we can add to config.php to set a theme, either system, dark, or light.

**Comment by joshtrichards** [comment]
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#enforce-theme

**Comment by skjnldsv** [comment]
> Since a recent update Nextcloud detects if the system is using dark mode. This is quite annoying because the user has no way to turn it off, but there are so many bugs with the dark design that it is really decreasing the user experience.

With the last releases, I think we can consider the dark mode pretty stable by now.
I'd say we can close this request for now :)
Thanks and happy New Year everyone! :rocket:
