### ISSUE TITLE
[Bug]: Leaking etag

### ISSUE THREAD

**Issue by sysgerm** [nextcloud/server#32345]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I was running a vulnerability test against a new and updated nextcloud project. I was going to try and get as much info as I can and then stumbled across this base64 encoded string located in "<input type="hidden" id="initial-state-core-capabilities" value=". 

The server is running:
- PHP : 7.4.26
- SQL-Lite : 3.35.5
- Latest NextCloud

Once I decode this massive string, you could gain an etag. Etag discovery can lead to cache poisoning. Thus making it a potential weakness. 

### Steps to reproduce

1. Go to view-source:https://askersoho.cloud/login
2. Locate: <input type="hidden" id="initial-state-core-capabilities" value=
3. Decode the value
4. Read the etag

### Expected behavior

The best thing that would be expected is if it just wasn't there.

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
"accessibility":"/apps/accessibility","activity":"/apps/activity","apporder":"/apps/apporder","breezedark":"/apps/breezedark","bruteforcesettings":"/apps/bruteforcesettings","checksum":"/apps/checksum","circles":"/apps/circles","cloud_federation_api":"/apps/cloud_federation_api","comments":"/apps/comments","contactsinteraction":"/apps/contactsinteraction","dashboard":"/apps/dashboard","dav":"/apps/dav","duplicatefinder":"/apps/duplicatefinder","end_to_end_encryption":"/apps/end_to_end_encryption","external":"/apps/external","extract":"/apps/extract","federatedfilesharing":"/apps/federatedfilesharing","federation":"/apps/federation","files":"/apps/files","files_antivirus":"/apps/files_antivirus","files_pdfviewer":"/apps/files_pdfviewer","files_rightclick":"/apps/files_rightclick","files_sharing":"/apps/files_sharing","files_trashbin":"/apps/files_trashbin","files_versions":"/apps/files_versions","files_videoplayer":"/apps/files_videoplayer","firstrunwizard":"/apps/firstrunwizard","geoblocker":"/apps/geoblocker","integration_github":"/apps/integration_github","integration_twitter":"/apps/integration_twitter","logreader":"/apps/logreader","lookup_server_connector":"/apps/lookup_server_connector","maps":"/apps/maps","metadata":"/apps/metadata","nextcloud_announcements":"/apps/nextcloud_announcements","notifications":"/apps/notifications","oauth2":"/apps/oauth2","passman":"/apps/passman","password_policy":"/apps/password_policy","passwords":"/apps/passwords","photos":"/apps/photos","privacy":"/apps/privacy","provisioning_api":"/apps/provisioning_api","quota_warning":"/apps/quota_warning","ransomware_protection":"/apps/ransomware_protection","recommendations":"/apps/recommendations","root_cache_cleaner":"/apps/root_cache_cleaner","serverinfo":"/apps/serverinfo","settings":"/apps/settings","sharebymail":"/apps/sharebymail","side_menu":"/apps/side_menu","smb_test":"/apps/smb_test","support":"/apps/support","survey_client":"/apps/survey_client","systemtags":"/apps/systemtags","text":"/apps/text","theming":"/apps/theming","twofactor_backupcodes":"/apps/twofactor_backupcodes","updatenotification":"/apps/updatenotification","user_status":"/apps/user_status","viewer":"/apps/viewer","weather_status":"/apps/weather_status","welcome":"/apps/welcome","workflowengine":"/apps/workflowengine"}
```

**Comment by kesselb** [comment]
Some context: The etag (in initial-state-core-capabilities) is related to the direct editing service. 

https://github.com/nextcloud/server/blob/0447b53bda9fe95ea0cbed765aa332584605d652/apps/files/lib/Service/DirectEditingService.php#L45-L87

cc @nickvergessen @juliushaertl

**Comment by nickvergessen** [comment]
It is "an" ETag, not the ETag of the page, so doesn't seem to be bad at all.
Of course it would be nice if the direct editing saves it's work on pages where it is not loaded (like on the login page)

**Comment by juliushaertl** [comment]
> It is "an" ETag, not the ETag of the page, so doesn't seem to be bad at all.

Agreed, I don't see a way how the capabilities etag in that field could lead to cache poisoning. Also we set a proper Cache-Control header on the page response.

> Of course it would be nice if the direct editing saves it's work on pages where it is not loaded (like on the login page)

Yep, we actually only need those for the clients. PR in https://github.com/nextcloud/server/pull/32715

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
