### ISSUE TITLE
[Bug]: NC 24 with php-fpm/php-fcgi can't connect to MariaDB 

### ISSUE THREAD

**Issue by akierig** [nextcloud/server#32340]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After updated to v.24, I started finding this error in my apache2 error logs (it's one line so I'm not putting it in as a code block):

> [Mon May 09 16:09:01.851585 2022] [proxy_fcgi:error] [pid 1841:tid 140660554856192] [client <redacted>] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Doctrine\\DBAL\\Exception: Failed to connect to the database: An exception occurred in the driver: could not find driver in /var/www/nextcloud/lib/private/DB/Connection.php:139\nStack trace:\n#0 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1519): OC\\DB\\Connection->connect()\n#1 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Connection.php(1041): Doctrine\\DBAL\\Connection->getWrappedConnection()\n#2 /var/www/nextcloud/lib/private/DB/Connection.php(261): Doctrine\\DBAL\\Connection->executeQuery()\n#3 /var/www/nextcloud/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php(345): OC\\DB\\Connection->executeQuery()\n#4 /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php(281): Doctrine\\DBAL\\Query\\QueryBuilder->execute()\n#5 /var/www/nextcloud/lib/private/AppConfig.php(411): OC\\DB\\QueryBuilder\\QueryBuilder->execute()\n#6 /var/www/nextcloud/lib/private/AppConfig.php(176): OC\\AppConfig->loadConfigValues()\n#7 /var/www/nextcloud/lib/private/AppConfig.php(367): OC\\AppConfig->getApps()\n#8 /var/www/nextcloud/lib/...'

it was the first time I'd had that error and was surprising given that the error came a few days after I'd upgraded. I'd made no config or package changes between the upgrade and it throwing this error.

It was fixed by disabling the apache modules `proxy_fcgi proxy_http2 http2 mpm_event` and the `php7.4-fpm ` config, and reactivating the default apache `mpm_prefork php7.4` modules.

### Steps to reproduce

1. Update to NC 24 on a server using `php7.4-fpm`, `mpm_event`, `proxy_fcgi`, and `http2`
2. wait a few days (it's possible it was sooner, though everything was fine after the update was complete)
3. find that Nexcloud can't connect to the database

### Expected behavior

Nextcloud would continue to be able to connect to the database when using php-fpm.c

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "styx.hell.rodeo"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.0.12",
        "overwrite.cli.url": "https:\/\/styx.hell.rodeo",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "user": "default",
            "dbindex": 0,
            "timeout": 1.5
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "default_locale": "en_US",
        "default_phone_region": "US",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "updater.release.channel": "stable",
        "maintenance": false,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "app_install_overwrite": [
            "apporder",
            "breezedark",
            "extract",
            "metadata",
            "files_markdown",
            "news"
        ],
        "data-fingerprint": "85956e5b85d35e0b0639becbb141ca26"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - admin_audit: 1.14.0
  - apporder: 0.15.0
  - breezedark: 24.0.0
  - cloud_federation_api: 1.7.0
  - contactsinteraction: 1.5.0
  - dav: 1.22.0
  - deck: 1.7.0
  - extract: 1.3.5
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_markdown: 2.3.6
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - metadata: 0.16.0
  - news: 18.0.1
  - nextcloud_announcements: 1.13.0
  - notes: 4.3.1
  - notifications: 2.12.0
  - notify_push: 0.4.0
  - oauth2: 1.12.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_totp: 6.3.0
  - updatenotification: 1.14.0
  - viewer: 1.8.0
  - workflowengine: 2.6.0
Disabled:
  - activity: 2.15.0
  - bruteforcesettings: 2.4.0
  - circles: 22.1.1
  - comments: 1.11.0
  - dashboard: 7.1.0
  - encryption
  - files_external
  - forms: 2.5.0
  - password_policy: 1.11.0
  - recommendations: 1.0.0
  - systemtags: 1.11.0
  - user_ldap
  - user_status: 1.1.1
  - weather_status: 1.1.0
  - workflow_ocr: 1.23.2
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
nothing relevant in data/nextcloud.log
```

### Additional info

Debian 11/Stable
Apache 2.4.53
MariaDB 10.6.7 (from mariadb.org repository)

packages current and regularly updated.

**Comment by akierig** [comment]
FWIW, I installed/setup another Nextcloud instance on a different machine using the exact same apache2/php/mariadb (with `php-fpm proxy_fcgi` etc) with no issues.

**Comment by kesselb** [comment]
>  Failed to connect to the database: An exception occurred in the driver: could not find driver in

Usually means that a module for php is missing. Likely the mysql module.

**Comment by akierig** [comment]
It's not. That was the first thing I checked. There was nothing installed or removed on that server.

**Comment by kesselb** [comment]
As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

> It was fixed by disabling the apache modules proxy_fcgi proxy_http2 http2 mpm_event and the php7.4-fpm config, and reactivating the default apache mpm_prefork php7.4 modules.

You changed from mod_php to php-fpm (via fcgi). They usually use different php.ini files. On Debian/Ubuntu the module configuration should be changed. Yet that's something for you to figure out ;)

**Comment by Sprinterfreak** [comment]
Same here. Why closing an unresolved issue?
My difference is that with nginx, there is no mod_php.

The issue seem to just affect the occ cli, nextcloud (web) itself seems to work.
A required `occ db:add-missing-indices` should have been issued but currently not possible.

**Comment by akierig** [comment]
@Sprinterfreak I ended up reinstalling it on a new VPS (for reasons unrelated to this issue) when v24.0.1 came out. Sorry I don't have anything more helpful to tell you.

**Comment by Sprinterfreak** [comment]
For me was an unattended-upgrade which updated from php8.0 to php8.1. Therefore all php modules, nextcloud depends on where missing.
While nginx is hard configured to use php8.0, the webui still worked. But on cli php8.1 was used and had no dependecies installed.

**Comment by akierig** [comment]
glad to hear you got it sorted out!
