### ISSUE TITLE
[Bug]: Change of access right on a group share is not promoted to all group members

### ISSUE THREAD

**Issue by Volker-K** [nextcloud/server#32352]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

There is a folder with manuals and further information shared with all users in our installation. To do so I share it with the AD/LDAP Groups the users are member of. Those files should not be deleted oder changed by anyone but me.
Sometimes, I have to re-share the folder because some users leave that share before they realize it might be helpful, and open support tickets because they don't find a manual.
After sharing the folder with a group, all users have CRUD-Rights for this folder (Create, Read, Update, Delete). So in he next step I use the three-dot-context-menu to remove all rights but Read.
Last time I did this, a lot of users still were able to update and delete files from this folder. It was urgent, so I re shared the folder during prime time. 
A look into table oc_share shows, that the share is promoted to the group members by creating hidden shares with the group-share as parent. While removing the rights, there might have been problems, some users still have 31 (CRUD) in the "privileges"-column, some have "17" (READ ONLY) what is wanted.
![NextCloud Group Share rights](https://user-images.githubusercontent.com/34368929/168054011-f68a03d8-930f-4433-9db7-62539675f981.png)
Possibly a locking condition while changing the privileges of all those hidden shares occurred?
I fixed it by just granting and revoking the CRUD-privileges for this group in the evening with less load on the server. 

### Steps to reproduce

1. Share a folder with a group that contains more than 1000 users at Prime Time
2. Remove all rights but Read
3. there you are (sometimes, not always)

### Expected behavior

Rights will be propagated to the group members correctly

### Installation method

Manual installation

### Operating system

Other

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "maintenance": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.domain.de",
            "localhost"
        ],
        "theme": "",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "installed": true,
        "appstoreenabled": true,
        "knowledgebaseenabled": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "updatechecker": false,
        "logtimezone": "Europe\/Berlin",
        "remember_login_cookie_lifetime": 1000,
        "session_lifetime": 900,
        "singleuser": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 4,
        "log_type": "syslog",
        "trashbin_retention_obligation": "auto",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/cloud.domain.de",
        "default_language": "de_DE",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "auth.bruteforce.protection.enabled": false,
        "integrity.check.disabled": true,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "proxy": "proxy.domain.local:8080",
        "defaultapp": "files",
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "whiteboard"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - announcementcenter: 6.1.1
  - calendar: 3.2.2
  - circles: 23.0.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.1.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - deck: 1.6.1
  - federatedfilesharing: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - support: 1.6.0
  - systemtags: 1.13.0
  - tasks: 0.14.4
  - terms_of_service: 1.9.3
  - text: 3.4.0
  - theming: 1.14.0
  - theming_customcss: 1.10.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.2.0
  - user_ldap: 1.13.1
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - whiteboard: 0.0.3
  - workflowengine: 2.5.0
Disabled:
  - encryption: 2.7.0
  - federation: 0.0.4
  - files_external
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - updatenotification: 0.1.0
```

### Nextcloud Signing status

```shell
Integrity checker has been disabled. Integrity cannot be verified.
(had o change some lines in the language files but *.php files are not altered.)
```

### Nextcloud Logs

Nothing relevant found.

**Comment by Volker-K** [comment]
Since it could become a security bug it would be nice to get some reaction ;-)

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by Volker-K** [comment]
> Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

It's a bit tricky to reproduce that effect because it obviously depends on the number of users currently active _and_ we are stuck on Version 23 due to the recursion error (https://github.com/nextcloud/server/issues/32432).

I will report after 24.10 will be available and I migrated our productive environment.
