### ISSUE TITLE
[BITV] "Settings" and "New" action names must be distinct

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#32350]
The term "Settings" and "New" are used in various places and is not distinct enough.
Accessibility requires more distinct names so that one can reach those places for example by getting a listing of links present in the page.

- [x] "Settings"
    - [x] Settings in the bottom left on the files app: always state the app name, see https://github.com/nextcloud/server/issues/32350#issuecomment-1191419585
    - [x] ~~remove aria-label from div of the settings menu~~ not needed
    - [x] keep "Settings menu" aria-label itself in the nav (test that it's detectable/reachable when tabbing on the settings menu item when closed)
    - [x] Settings menu entry on the top right: stay generic as they are in a menu => no-op
- [x] "New" 
    - [x] "New" in the files app
    - ~~"New" in the gallery app~~

@jancborchardt @nimishavijay
<img width="568" alt="2022-07-08 12_59_57-BITV-Dokumentation Settings1" src="https://user-images.githubusercontent.com/1315170/177980091-1be7c46e-0245-436d-adfd-1643907557a2.png">
<img width="566" alt="2022-07-08 13_00_18-BITV-Dokumentation New1" src="https://user-images.githubusercontent.com/1315170/177980105-26551023-b9d1-432c-9411-3f40f816584a.png">
<img width="576" alt="2022-07-08 13_00_41-BITV-Dokumentation New2" src="https://user-images.githubusercontent.com/1315170/177980111-a664b41d-ba18-4658-8cbd-72c3845ad3d6.png">

**Comment by PVince81** [comment]
@jancborchardt @nimishavijay please help to find the appropriate wordings for the accessible names and whether we also want to rename the label to something more explicit

**Comment by PVince81** [comment]
@Pytal  note: when touching the "+" button please also fix it in the file picker as this was reported inconsistent in https://github.com/nextcloud-gmbh/server/issues/461

**Comment by Pytal** [comment]
As per https://github.com/nextcloud-gmbh/server/issues/461#issuecomment-1188086173 and their explanation from https://nextcloud-accessibility-full-april2022.netlify.app/problems/3-2-4-consistent-identification/

> Remember that consistent naming doesn’t necessarily mean identical naming. If these buttons add different things they could be named “Add folder”, “Add document” for instance, at it would be consistent since their function of adding something would be consistently explained.

Everything seems in order @PVince81

**Comment by jancborchardt** [comment]
Agree with @nimishavijay's proposal
- Bottom left settings could always state the app name like "Talk settings", " Files settings" etc
- Top right settings could stay generic as they are in a menu
- The "+" button could use a label "New". This is e.g. also how Google Drive names it

**Comment by PVince81** [comment]
@Pytal cool if the button is fixed already

**Comment by PVince81** [comment]
- [ ] files app: change to "Files settings"
- [x] talk app: already says "Talk settings"
- [ ] activity app. "Settings" => "Activity Settings"
- [ ] calendar app: "Settings and import" => "Calendar settings"
- [ ] contacts app: "Settings" => "Contacts settings"
- [ ] tasks app: "Settings" => "Tasks settings"
- [ ] deck app: "Settings" => "Deck settings"
- [ ] mail app: "Settings" => "Mail settings"
- [ ] photos: "Settings" => "Photos settings"
- [ ] collectives: "Settings" => "Collectives settings"
- dashboard: N/A
- forms: N/A

**Comment by PVince81** [comment]
regarding the top-right menu, I see that the aria-label is kind of duplicate:
<img width="424" alt="image" src="https://user-images.githubusercontent.com/277525/180213312-b5245e8f-95ce-4575-81ad-6c00af79bc58.png">

I've updated the top post to remove the aria-label on the div and keep the one on nav, but one needs to test that it actually works correctly that way

**Comment by PVince81** [comment]
@jancborchardt for calendar I guess we can keep calling it "Settings & import" ? or should we rename to "Calendar settings" still to avoid less duplication and confusion ? But that label would make it less clear that "import" is there too. I suppose it's ok.

**Comment by jancborchardt** [comment]
> @jancborchardt for calendar I guess we can keep calling it "Settings & import" ? or should we rename to "Calendar settings" still to avoid less duplication and confusion ? But that label would make it less clear that "import" is there too. I suppose it's ok.

Yeah – I commented on the PR, I think it's ok to change it, we should probably call out import in another way too like e.g. via the "+ New calendar" menu (cause you might want to import a whole new calendar), as well as the "New event / New task" menu. cc @miaulalala

**Comment by PVince81** [comment]
@juliushaertl can you take care of the collectives one ? https://github.com/nextcloud/server/issues/32350#issuecomment-1191419585

**Comment by juliushaertl** [comment]
Created a merge request at https://gitlab.com/collectivecloud/collectives/-/merge_requests/587 and added to the list

**Comment by PVince81** [comment]
@miaulalala can you take care of the mail app one ?

**Comment by miaulalala** [comment]
Message button already has a button text "New Message", is that sufficient?

![image](https://user-images.githubusercontent.com/7427347/181037152-8ec8ec8a-137d-4dd9-b862-8da5a7b3b176.png)

Settings will follow in a minute.

**Comment by miaulalala** [comment]
https://github.com/nextcloud/mail/pull/6936

**Comment by PVince81** [comment]
https://github.com/nextcloud/server/pull/33271 merged for a better label for the "New" menu

**Comment by PVince81** [comment]
- [ ] another PR to remove an extra occurrence: https://github.com/nextcloud/server/pull/33385
