### ISSUE TITLE
[Bug]: FPM process stuck, using all cpu available

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/server#32385]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I'm in advance sorry, but I don't have much details to tell you, but this is important, and I'd like to track it, and help resolve it.

the 6th of May, we updated from Nc 21, to Nc 22, and since a week, we experienced 4 downtimes.

The best I can show is the CPU profile:
![Screenshot from 2022-05-13 15-58-43](https://user-images.githubusercontent.com/1863453/168299879-04e9e77e-cd80-4848-8e36-9ea92f2a6529.png)

We have 6 php-fpm container running (usually 2 are enough, but I though, this would mitigate the issue, but it didn't.

There are 2 places that I know my config is suboptimal:
 - [fastcgi_read_timeout and fastcgi_send_timeout are too big]https://lab.libreho.st/libre.sh/docker/nextcloud/-/blob/master/web/default.conf.template#L18-20)
 - [max_children is also too big](https://lab.libreho.st/libre.sh/docker/nextcloud/-/blob/master/base/php-fpm.conf#L21)

Even if I change that, it would change the behavior, and how it reacts to the issue, it will not fix the issue in the first place.

What I can also say is that [fpm status](https://lab.libreho.st/libre.sh/docker/nextcloud/-/blob/master/base/php-fpm-healthcheck#L54) doesn't return during the downtime.

Also the number of fpm child is at the maximum.

Basically, I searched the logs, but didn't find anything relevant.. so I'm in the dark. During the event, I'd love to make a dump of whatever to be able to determine what php is doing and be able to report.

Today, I'll change the way I deploy, so if this happens again, the container will be restarted and there is no more way to investigate.

If you could provide me with a procedure to dump the memory or whatever can be useful to help debug that, then I'll go back, wait for the event to happen again, and provide you with this info.

Hope it helps the community! And hope we find the guilty line of code :)
(Well it can also well be php or fpm...)
BTW, I read php 7.3 [here](https://github.com/nextcloud/server/blob/v22.2.7/composer.json#L7=) and the docker image uses 8.0. Do you think it is better to use 7.3?

Thanks for your inputs!

### Steps to reproduce

Unfortunately, I'd love to give you that, but I don't know.

### Expected behavior

FPM process should enter this loop.

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "installed": "true",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nuage.liiib.re"
        ],
        "overwrite.cli.url": "https:\/\/nuage.liiib.re",
        "overwriteprotocol": "",
        "version": "22.2.7.1",
        "debug": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "config_is_read_only": true,
        "skeletondirectory": "",
        "updatechecker": "false",
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
        "updater.release.channel": "stable",
        "upgrade.disable-web": true,
        "sharing.maxAutocompleteResults": 10,
        "sharing.minSearchStringLength": 2,
        "dbtype": "pgsql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "5425",
        "dbtableprefix": "",
        "mysql.utf8mb4": false,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/usr\/src\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            }
        ],
        "default_language": "fr",
        "default_locale": "fr",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "objectstore": {
            "class": "\\OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "nuage-liiib-re",
                "autocreate": false,
                "uploadPartSize": 124288000,
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "region": "default",
                "hostname": "hot-objects.liiib.re",
                "port": "443",
                "use_ssl": true,
                "use_path_style": true
            }
        },
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": true,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "appstoreenabled": false
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - appointments: 1.12.3
  - apporder: 0.15.0
  - bookmarks: 10.3.1
  - calendar: 3.3.0
  - circles: 22.3.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.1.0
  - contactsinteraction: 1.3.0
  - dav: 1.20.0
  - deck: 1.5.6
  - drop_account: 2.0.0
  - external: 3.9.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_linkeditor: 1.1.9
  - files_mindmap: 0.0.26
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_versions_s3: 0.1.8
  - files_videoplayer: 1.11.0
  - forms: 2.5.0
  - groupfolders: 10.0.2
  - indie_external: 3.9.0
  - lookup_server_connector: 1.10.0
  - mail: 1.12.0
  - notes: 4.3.1
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - onlyoffice: 7.3.4
  - passwords: 2021.12.20
  - photos: 1.4.0
  - polls: 3.6.1
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - systemtags: 1.12.0
  - tasks: 0.14.4
  - text: 3.3.1
  - theming: 1.13.0
  - theming_customcss: 1.11.0
  - twofactor_backupcodes: 1.11.0
  - user_saml: 5.0.0
  - viewer: 1.6.0
  - workflowengine: 2.4.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - dashboard: 7.0.0
  - data_request
  - drawio: 1.0.2
  - electronicsignatures
  - files_automatedtagging
  - files_external: 1.11.1
  - firstrunwizard: 2.7.0
  - impersonate: 1.8.0
  - keeweb
  - logreader: 2.5.0
  - multioffice
  - music: 1.4.1
  - nextcloud_announcements: 1.9.0
  - ownpad
  - password_policy: 1.8.0
  - quota_warning
  - registration: 0.4.7
  - richdocuments: 3.7.3
  - side_menu
  - sociallogin
  - survey_client: 1.8.0
  - timemanager
  - user_ldap
  - user_status: 1.0.1
  - weather_status: 1.0.0
```

### Nextcloud Signing status

```shell
Good.
```

### Nextcloud Logs

```shell
Sorry, I searched, but no relevant logs :/
```

**Comment by szaimen** [comment]
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!

**Comment by pierreozoux** [comment]
We did several things which I can't remember. But it seems it doesn't happen any more.
