### ISSUE TITLE
[Bug]: Shared linkpreview will not be displayed and the screen

### ISSUE THREAD

**Issue by Take-Hamamoto** [nextcloud/server#32408]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello. If you open the URL of the shared image with "Share link" and click the thumbnail, the preview will not be displayed and the screen "[]" will be displayed instead.
Is this a bug?
Is there a way to display the preview correctly?

### Steps to reproduce

1.Log in to next-cloud.
2.Upload the image data. (This time I used jpeg.)
3.Click "..."at the bottom right of the thumbnail, and then click "Shared".
4.Click "+" of "Share link" and spectify the password.
5.Click "Create share", and click the "Copy to clipbord" button to copy the image sharing URL.
6.Launch a new web browser, paste the image sharing URL and enter the password you set.
7.Click the thumbnail of image.

### Expected behavior

The preview will not be displayed and the screen "[]" will be displayed instead.

### Operating system

RHEL/CentOS

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
sudo -u apache php /var/www/html/nextcloud/occ config:list system {
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.20.246",
            "next-cloud"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.3.2",
        "overwrite.cli.url": "http:\/\/next-cloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "ja",
        "default_locale": "ja_JP",
        "skeletondirectory": "",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
```

### List of activated Apps

```shell
sudo -u apache php /var/www/html/nextcloud/occ app:list
Enabled:
  - bruteforcesettings: 2.4.0
  - cloud_federation_api: 1.6.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - files: 1.18.0
  - files_external: 1.15.0
  - files_sharing: 1.15.0
  - lookup_server_connector: 1.11.0
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - provisioning_api: 1.13.0
  - settings: 1.5.0
  - theming: 1.14.0
  - twofactor_admin: 3.2.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.2.0
  - user_ldap: 1.13.1
  - viewer: 1.7.0
  - workflowengine: 2.5.0
Disabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - admin_audit
  - circles: 23.1.0
  - comments: 1.13.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - encryption
  - federation: 1.13.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - logreader: 2.8.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - photos: 1.5.0
  - privacy: 1.7.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.1
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - weather_status: 1.3.0
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
