### ISSUE TITLE
[Bug]: Syntax error or access violation: 1118 Row size too large

### ISSUE THREAD

**Issue by brianjmurrell** [nextcloud/server#32436]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Same issue as #15648 but that one has been closed by a bot.  I have no hope that it will actually get reopened.

### Steps to reproduce

Please see #15648 for all of the details.  This still happens on NC 24.0.

### Expected behavior

Should not get the error mentioned.

### Installation method

Other

### Operating system

RHEL/CentOS

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Can be provided if really necessary.
```

### List of activated Apps

```shell
Can be provided if really necessary.
```

### Nextcloud Signing status

```shell
Can't get this as my instance is still in maintenance mode as recommended by https://docs.nextcloud.com/server/24/go.php?to=admin-mysql-utf8mb4
```

### Nextcloud Logs

```shell
Can be provided if really necessary.
```

**Comment by solracsf** [comment]
> I have no hope that it will actually get reopened.
Done.
