### ISSUE TITLE
Share by single file with multiple links.

### ISSUE THREAD

**Issue by geiseri** [nextcloud/server#3243]
This is more of a feature request because right now there is no support for this feature.

The scenario I am in is that I have a single file that I would like to share by link with multiple people who are not users on the system. I want the link to be valid for 1 week from when I shared it with a specific person.  This is for temporary download of a demo and I would like to get around needing an individual login for a user and have that login expire after 1week.  Right now I cannot figure out a way to do this without copying the file into a new folder and then sharing it again.  To get around this I have the same file in 10 folders, so I can share with 10 people at a time.  While this works it becomes cumbersome to maintain that copy in each folder.  I hope this make sense.

**Comment by MorrisJobke** [comment]
This is possible with the share by email feature. Every email is assigned a single URL that can be used like the usual link share. It can also be revoked on a per email address basis.

The feature was added in Nextcloud 11 

😃

**Comment by geiseri** [comment]
The problem is the link expiration.  It would be cumbersome to manually track and purge each user.

**Comment by MorrisJobke** [comment]
Could I ask you to open a separate ticket for the "share expiration for internal/federation/email shares"?  Or maybe add it to the "New sharing UI" issue, that needs to be done to integrate this functionality into the UI: https://github.com/nextcloud/server/issues/434

**Comment by Luxoboy** [comment]
> This is possible with the share by email feature. Every email is assigned a single URL that can be used like the usual link share. It can also be revoked on a per email address basis.

@MorrisJobke I think the requested feature still makes sense. It seems to me that one should be able to share with multiple persons **without** providing their email addresses, and being able to revoke those shares individually.
Thus, being able to have multiple share links per item makes sense and it'd be nice if it would be implemented.
