### ISSUE TITLE
[Bug]: getDirectDownload() returns empty array

### ISSUE THREAD

**Issue by SpechtD** [nextcloud/server#32438]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

[IStorage::getDirectDownload()](https://nextcloud-server.netlify.app/classes/ocp-files-storage-istorage#method_getDirectDownload) always returns an empty array in the code under Steps to reproduce.

### Steps to reproduce

```
/** @var File*/
private $file;

/** @var Folder */
private $userFolder;

/** @var IStorage */
private $storage;

public function __construct(string $path, string $userID, IRootFolder $iRootFolder)
{
	$this->userFolder = $iRootFolder->getUserFolder($userID);
	$this->file = $this->userFolder->get($path);
	$this->storage = $this->file->getStorage();
}

public function generateUrl()
{
	$filePath = $this->file->getInternalPath();
	$url = $this->storage->getDirectDownload($filePath);
	return $url;
}
```

### Expected behavior

Return a URL for direct download of a given file.

### Installation method

Manual installation

### Operating system

Other

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - bbb: 2.2.0
  - calendar: 3.2.2
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.1.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_sharing: 1.16.1
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - lookup_server_connector: 1.12.0
  - mail: 1.11.7
  - oauth2: 1.12.0
  - provisioning_api: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - spreed: 14.0.0-beta.1
  - systemtags: 1.14.0
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - testing
  - user_ldap
```

**Comment by SpechtD** [comment]
Till now I have used this, but from the frontend.: https://docs.nextcloud.com/server/latest/developer_manual/client_apis/OCS/ocs-api-overview.html#direct-download
Now I need to generate the URL in the backend, so I tried using the PHP API.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/master/apps/dav/lib/Controller/DirectController.php

I guess you need to copy the above logic for now.

cc @skjnldsv @icewind1991 do you know if we have a php api to generate a direct download link?

**Comment by sualko** [comment]
I guess it just was forgotten at some point https://github.com/nextcloud/server/blob/459202d54cf891298099c3f793d2b163b9b76541/lib/private/Files/Storage/Common.php#L516-L518

So probably it make sense to implement the method in the Local or Root with the logic from the dav app.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
