### ISSUE TITLE
[Bug]: Cron Error: Call to undefined method `OC\Files\Node\File::getDirectoryListing()`

### ISSUE THREAD

**Issue by escoand** [nextcloud/server#32450]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Executing the cron.php from time to time causes this error:

```
Error: Call to undefined method OC\Files\Node\File::getDirectoryListing() in /var/www/html/apps/dav/lib/BackgroundJob/UploadCleanup.php:74
Stack trace:
#0 /var/www/html/lib/public/BackgroundJob/Job.php(79): OCA\DAV\BackgroundJob\UploadCleanup->run(Array)
#1 /var/www/html/lib/public/BackgroundJob/TimedJob.php(95): OCP\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#2 /var/www/html/cron.php(151): OCP\BackgroundJob\TimedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
#3 {main}
```

This is already happening longer time but just maybe once a week or so.

### Steps to reproduce

unknown

### Expected behavior

no error

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - calendar: 3.3.0
  - cloud_federation_api: 1.7.0
  - contacts: 4.1.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - groupfolders: 12.0.0
  - impersonate: 1.11.0
  - keeweb: 0.6.9
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - mail: 1.12.0
  - metadata: 0.16.0
  - news: 15.4.5
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - previewgenerator: 4.0.0
  - provisioning_api: 1.14.0
  - ransomware_protection: 1.13.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_nextcloud_notification: 3.4.0
  - updatenotification: 1.14.0
  - viewer: 1.8.0
  - workflowengine: 2.6.0
Disabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - circles: 24.0.0
  - comments: 1.11.0
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - encryption
  - facerecognition: 0.8.2
  - files_rightclick: 0.15.1
  - firstrunwizard: 2.2.1
  - nextcloud_announcements: 1.2.0
  - privacy: 1.0.0
  - recommendations: 0.4.0
  - support: 1.0.0
  - survey_client: 0.1.5
  - systemtags: 1.12.0
  - tasks: 0.14.4
  - user_ldap
  - user_status: 1.0.0
  - weather_status: 1.0.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by PVince81** [comment]
assuming you're using Nextcloud 24.0.0

@icewind1991 might look like the issue we fixed recently ?

**Comment by escoand** [comment]
> assuming you're using Nextcloud 24.0.0

Yes, but happening since 22 I think...

**Comment by escoand** [comment]
At the moment the error is thrown once per day. Interesstingly the time is moving, every day it's 5 minutes later than the day before.

**Comment by CarlSchwan** [comment]
Fix in https://github.com/nextcloud/server/pull/32956
