### ISSUE TITLE
[Bug]: touch: setting times of '/var/www/html/nextcloud-init-sync.lock': Operation not permitted

### ISSUE THREAD

**Issue by bbhxwl** [nextcloud/server#32476]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

touch: setting times of '/var/www/html/nextcloud-init-sync.lock': Operation not permitted

in raspberry 

### Steps to reproduce

touch: setting times of '/var/www/html/nextcloud-init-sync.lock': Operation not permitted

in raspberry 
root@raspberrypi:~# docker run  -p 8080:80 nextcloud
Initializing nextcloud 24.0.0.12 ...
touch: setting times of '/var/www/html/nextcloud-init-sync.lock': Operation not permitted
root@raspberrypi:~# 

### Expected behavior

touch: setting times of '/var/www/html/nextcloud-init-sync.lock': Operation not permitted

in raspberry 
root@raspberrypi:~# docker run  -p 8080:80 nextcloud
Initializing nextcloud 24.0.0.12 ...
touch: setting times of '/var/www/html/nextcloud-init-sync.lock': Operation not permitted
root@raspberrypi:~# 

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
.
```

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

**Comment by kesselb** [comment]
I agree, "setup issue" is not the perfect fit here.

But unfortunately we cannot help with this problem.

This repository is for the Nextcloud server code. 
We don't create or update a file `nextcloud-init-sync.lock`. 
It belongs to the docker repository: https://github.com/nextcloud/docker/blob/2ffebc1e3583b87e78eb2098b2386411ebee6bce/25/fpm/entrypoint.sh#L130

> Operation not permitted

`touch nextcloud-init-sync.lock` should update a timestamp. 
Your docker host/operating system said no. 

Good luck :four_leaf_clover:

**Comment by ilonachan** [comment]
Oh I see, thanks for pointing to the right repository! Maybe I should open an issue there, or see if someone already did that.

My temporary solution is to run the container `--privileged`, which _sounds_ like it might be a bad idea, but it'll have to do for now.
