### ISSUE TITLE
macOS - No calendar home was specified for the account

### ISSUE THREAD

**Issue by curious-jim** [nextcloud/server#3247]
### Expected behaviour
show calendar in my Calendar.app

### Actual behaviour
**The server specified an invalid calendar home.**

No calendar home was specified for the account 

### Server configuration
**Operating system**: macOS 10.12.2

**Web server:** nginx/1.10.2

**Database:** mysql  Ver 14.14 Distrib 5.7.17

**PHP version:** PHP 7.0.13-0ubuntu0.16.04.1

**Server version:** Nextcloud 11.0.1 (stable)

**Calendar version:** 1.5.0

**Updated from an older installed version or fresh install:** fresh install, but imported Google Calendar

**Comment by curious-jim** [comment]
sorry, I found what was wrong

**Comment by anknown1** [comment]
And could you please share what was wrong?

**Comment by curious-jim** [comment]
I used the wrong url. I used ownCloud long time ago so I just memorized the url /remote.php/dav/
and it worked back then (maybe I used different Calendar app). But now it didn't, and there is a separate url for OSX, I haven't noticed it before. I tried that one and it worked with Calendar.app

**Comment by psydone** [comment]
So what was that one?

**Comment by curious-jim** [comment]
oh, it was long time ago, but I remember when you open settings at the bottom of the page, there was url and separate url for OSX/iOS, I used the normal url instead of OSX url

**Comment by edgarm1964** [comment]
Still an issue
