### ISSUE TITLE
[Bug]: "Add notes, lists, or links" does not work until thumbnails are loaded

### ISSUE THREAD

**Issue by guystreeter** [nextcloud/server#32505]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I have a slow server. When in list view I go to a folder with a lot of photos, I cannot click the "Add notes, lists, or links..." entry to create a `readme.md` unless all of the thumbnails have been loaded.
Additionally, if I click there before the thumbnails load, it will not work even after the thumbnails are loaded. I have to refresh the page and wait for the thumbnails to display before clicking.
Apparently, (I haven't completely confirmed this because timing matters) I have to scroll down the list and load all the thumbnails before I can click "Add notes".

### Steps to reproduce

1. Load a lot of images into a folder
2. Switch to "list" view
3. Open the folder
4. Quickly click "Add notes, lists, and links..." before the thumbnails have displayed

### Expected behavior

The "Add notes" link should not depend on having images thumbnails loaded in order to work as expected.

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
./occ config:list system
{
    "system": {
        "facerecognition.external_model_url": "http:\/\/pootpoot.duckdns.org:8080",
        "facerecognition.external_model_api_key": "JckaTqawIxerzUV+Lc\/mtBNxUtR+NZ+3u5r2eYY7AH8=",
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "overwritehost": "hwsrv-956351.hostwindsdns.com:8080",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/hwsrv-956351.hostwindsdns.com:8080",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "US",
        "simpleSignUpLink.shown": false,
        "auth.webauthn.enabled": false,
        "knowledgebaseenabled": false,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "hwsrv-956351.hostwindsdns.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.0.12",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "\/nextcloud-data\/my_skeleton",
        "versions_retention_obligation": "auto, 1",
        "auto_logout": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "maintenance": false
    }
}
```

### List of activated Apps

```shell
./occ app:list
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - calendar: 3.3.0
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - facerecognition: 0.9.5
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - groupfolders: 12.0.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - registration: 1.5.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - spreed: 14.0.1
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - viewer: 1.8.0
  - welcome: 1.0.1
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
  - user_status: 1.3.1
  - weather_status: 1.3.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
log is attached
```

### Additional info

[nextcloud.log](https://github.com/nextcloud/server/files/8734439/nextcloud.log)

**Comment by CarlSchwan** [comment]
Do you have some errors in your web console? (Ctrl+Shift+I in firefox to open)

**Comment by MrRinkana** [comment]
Sorry for bumping an old issue, but I figured it was maybe better than crating a new one.

I just upgraded to NC26.0.0, and the text "Add notes, links ...." does **not appear at all**, and if there is a present readme it is opened **in edit mode** from the start (rather than just showing its text until clicked on).
![Screenshot_20230407_202516](https://user-images.githubusercontent.com/39345772/230658941-397bc584-98a3-45a7-a162-913f8e5ff10d.png)

Clicking in the area does nothing (can't create a readme).


In the web console I found some errors about content security policy blocking the loading of inline scripts, namely ```utils.js:42:9```, ```files``` and ```content-script.js:40:65```..
![Screenshot_20230407_202754](https://user-images.githubusercontent.com/39345772/230659288-afd539c3-19e3-4787-b1fb-e78c3ff07c7a.png)


The issue persists if I change language to English_US in NC(was Swedish).

Please let me know if I should add anything, or create a new issue instead as this one is old and for a different NC version.

**Comment by MrRinkana** [comment]
Hello, sorry for late reply, on **26.0.2** the readme is **properly loaded** and in **view mode** + can be clicked on to edit. Scrolling also works

However if there is no readme file present, clicking the area does **not create one** (as it did previously) but that might be intended behaviour (honestly most of the time I just accidentally clicked there and created a readme). However it might introduce a barrier for people who don't know about the functionality.

Also if the window is smaller than the width of the text (in the readme) it does not change row and instead just **gets cut off**.

Let me know if you need more information!

**Comment by szaimen** [comment]
> Hello, sorry for late reply, on **26.0.2** the readme is **properly loaded** and in **view mode** + can be clicked on to edit. Scrolling also works

Nice!

> However if there is no readme file present, clicking the area does **not create one** (as it did previously) but that might be intended behaviour (honestly most of the time I just accidentally clicked there and created a readme). However it might introduce a barrier for people who don't know about the functionality. (see previous comment)

Yes, it is the intended behaviour new with 26.

> Also if the window is smaller than the width of the text (in the readme) it does not change row and instead just **gets cut off**.

This is something to report to https://github.com/nextcloud/text/issues if it is not already reported.
