### ISSUE TITLE
Allow OCS edit user endpoint to edit all user data fields

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#3250]
Such as the ones that we have in the user interface.

Once we've done that we should also migrate the web UI to this endpoint.

As requested by @mario.

FYI @schiessle

**Comment by MorrisJobke** [comment]
It's already implemented in 12: https://docs.nextcloud.com/server/12/admin_manual/configuration_user/user_provisioning_api.html#edit-data-of-a-single-user
