### ISSUE TITLE
Search mimetype filter

### ISSUE THREAD

**Issue by mario** [nextcloud/server#3253]
I would like to be able to search the files in addition to a mime type filter.

Use case:
- I want to fetch all images/videos/documents/whatever in a flat list

Use case 2:
- I want to fetch all images whose name contains "bla" in a flat list

**Comment by Spartachetto** [comment]
If this functionality is realized, it **could** be worthwhile to consider what is needed for #2143 .

I'll try to explain my suggestion: to realize #2143 it would be really practical (I guess) to be able to select all the _tagged_ files that have a specific mime type (or better, from a user's prospective, all the photos...).
Yet, more than a searchable list, a count would be even better.

@nickvergessen was dealing with the tag system, maybe he could say if I am totally off track  😄

**Comment by mario** [comment]
This works already afaik.
