### ISSUE TITLE
[Bug]: Changing your email address sends out 10, 20, or even more of "Email address for $USER changed on https://<Nextcloud>" emails to non-existent accounts

### ISSUE THREAD

**Issue by Sgt-Nukem** [nextcloud/server#32535]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Changing your email address sends out 5, 10, 20, or even more of "Email address for $USER changed on https://$Nextcloud" emails to non-existent accounts

Version: Nextcloud Hub II (23.0.4)

### Steps to reproduce

1. Visit https://$nextcloud/settings/user of an admin account (possibly the same for regular users)

2. change your current email - slowly - with backspace, delete, and typing single letters, etc. - NOT pasting the address from the clipboard all at once

3. for each (debounced) key input the address is saved **and also an email sent out directly** (*)

Example:

Old email: chelsea@github.com
New email: charms@github.com

Moving the cursor behind 'ch' and typing - slowly
- DELETE
- DELETE
- a
- r
- m
- CURSOR-RIGHT
- DELETE
- DELETE

will send "Email address for $USERNAME changed on https://$Nextcloud" emails to the following accounts (*):
- chlsea@github.com
- chsea@github.com
- chasea@github.com
- charsea@github.com
- charmsea@github.com
- (none for CURSOR movement)
- charmsa@github.com
- charms@github.com

(*) -- **all but the last one are _non-existent_** - So these may trigger mail server bounces as well.

P.S.: Be aware that you can see these emails only if you have a catch-all mail account for your domain! Because the names are incomplete and most probably do not exist as real mail addresses.

### Expected behavior

UX: Just have a frickin' checkmark / apply button instead of this debounce bulls**t.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - breezedark: 23.2.2
  - bruteforcesettings: 2.4.0
  - calendar: 3.3.1
  - circles: 23.1.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.1.1
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - deck: 1.6.1
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_external: 1.15.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.12.0
  - nextcloud_announcements: 1.12.0
  - notes: 4.3.1
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - quota_warning: 1.14.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - tasks: 0.14.4
  - text: 3.4.1
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
