### ISSUE TITLE
[Bug]: Cannot update from 23.0.4 to 24.0.1

### ISSUE THREAD

**Issue by JordanDIG** [nextcloud/server#32545]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello,

When I go to the administration page of my instance, it tells me that it is up to date (23.0.4) whereas on [https://nextcloud.com/changelog 2](https://nextcloud.com/changelog) a version 24.0.1 is available.

### Steps to reproduce

1. Install nextcloud 23.04
2. Tried to update

### Expected behavior

My nextcloud is up to date.. While a new version was released

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Défault app
```

**Comment by corsch** [comment]
Is 23.0.5 already released for all users? My 23.0.4 shows "Your version is up to date." in the updater.

**Comment by JSoko** [comment]
> => 23.0.5 is shown after switching to BETA and back to "Stable"

same behavior here...

**Comment by JordanDIG** [comment]
> 

I don't see the update :/

**Comment by JordanDIG** [comment]
> Is 23.0.5 already released for all users? My 23.0.4 shows "Your version is up to date." in the updater.
> 
> Update: => 23.0.5 is shown after switching to BETA and back to "Stable"

Not working for me :/

**Comment by spiezmaestro** [comment]
I have the option to upgrade to 23.0.5 from 23.0.4 since this morning (on stable release)

**Comment by solracsf** [comment]
Updates are released in chunks, so, some user may see them immediately, others later.
On automatic channels of course, one can always update manually.

**Comment by lbdroid** [comment]
I find that running the updater from the commandline is more effective at getting the major updates.

```sudo -u apache php /path/to/nextcloud/updater/updater.phar```
