### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by punithrudrappa** [nextcloud/server#32542]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

A element is being blocked in nextcloud office setup and word documents are not running. 

blocked url: https://**mydomain**/browser/3eff19066/cool.html?WOPISrc=https%3A%2F%2F**mydomain**%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F8_ocerihbbjl9e&title=Welcome%20to%20Nextcloud%20Hub.docx&lang=en&closebutton=1&revisionhistory=1

The log report from browser says as below.

The Content Security Policy (CSP) prevents the evaluation of arbitrary strings as JavaScript to make it more difficult for an attacker to inject unathorized code on your site.
To solve this issue, avoid using eval(), new Function(), setTimeout([string], ...) and setInterval([string], ...) for evaluating strings.
If you absolutely must: you can enable string evaluation by adding unsafe-eval as an allowed source in a script-src directive.
⚠️ Allowing string evaluation comes at the risk of inline script injection.
1 directive
Source Location Directive Status
index.js:13 script-src blocked

This was the reason why it was blocked. This was being blocked ublock origin, chormium browsers and many content blockers also.

### Steps to reproduce

1. setup nextcloud aio in raspberrypi 4b 
2. open any word document

### Expected behavior

Should open the document in .docx or any word formats.

### Installation method

Official All-in-One appliance

### Operating system

Debian/Ubuntu

### Web server

Apache (supported)

### Database engine version

Other

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
all default
```

**Comment by punithrudrappa** [comment]
for reference : https://github.com/nextcloud/all-in-one/issues/692

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
