### ISSUE TITLE
Allow Release Channel to be viewed and updated using occ command line

### ISSUE THREAD

**Issue by chriscroome** [nextcloud/server#32553]
Currently I don't believe there is any way to display or update the [Nextcloud Release Channel](https://nextcloud.com/release-channels/) using `occ`, having additional options such as these would be a great additional feature:

```bash
php occ channel:status
php occ channel:update stable
php occ channel:update beta
```

**Comment by joshtrichards** [comment]
All config parameters specified in `config.php` can also be set from the command line via `occ config:system`- e.g.

```
occ config:system:set --value=stable  updater.release.channel
occ config:system:get updater.release.channel
occ config:system:delete  updater.release.channel
```

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html#config-commands-label
