### ISSUE TITLE
Scss variables

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#3256]
This is part of the scss integration.
This issue has for goal to list all the recurrent variables across nextcloud.

**Main**: #1786
**Refs**: #3211, https://github.com/nextcloud/server/pull/3008#discussion_r96526515, #2288

- [ ] Nextcloud color / theme main color / .primary button: #0082c9
- [ ] white background used everywhere / popover arrow / menu arrow: #fff
- [ ] input background color
- [ ] input border color
- [ ] font color
- [ ] border radius: 3px
- [ ] ...?

feel free to suggest or add what seems to be used a lot. :)
@nextcloud/designers @jancborchardt

**Comment by Henni** [comment]
Just wanted to mention (maybe worth its own issue):
It would be great to pass these SCSS variables over to CSS via [custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables).
This way apps can do whatever they want with it.

**Comment by stefan-niedermann** [comment]
I would like to recommend to not simple use variables like "input-color" or "input-background" or "input-border-color" but to define a color palette and use abstract names like "primary-foreground", "primary-background", "secondary-forecround", "secondary-background", "contrast-background" and "contrast-background" to abstract away the kind of usage of the variables ([compare to android best practices](https://developer.android.com/training/material/theme.html))
This way one could simply switch from a light to a darker or a dark theme based on the same color palette without redefining the color of each element.
Of course the colors itself can be in a variable, too, and inserted into the palette.

**Comment by skjnldsv** [comment]
That's exactly what was planned :) 
We need to keep it simple! The scss came to me while working on the dark mode (#1692).
We need to be able to change the overall design with only a few vars! 😉

**Comment by jancborchardt** [comment]
I put in some of the default values in the original post above @skjnldsv :)

Also, I assume we use some @darker and @lighter methods to automatically calculate the hover/focus/active states?

**Comment by skjnldsv** [comment]
Thanks @jancborchardt 💘 

Right now we don't. But that's what i was working on before being unable to continue without scss on  #1692.
I will probably try both of the solutions:
1. Transparent border
2. Defined border with common variable. :)

**Comment by Darker** [comment]
Did you guys know that when you use @ along with a word, it sends that user an email?

**Comment by skjnldsv** [comment]
@Darker don't you get notifications from all over github? 😂

**Comment by Espina2** [comment]
You can add shadow and variables to z-index by importance.

**Comment by skjnldsv** [comment]
@Espina2 what do you mean? as a superposition?

**Comment by juliushaertl** [comment]
I've just scanned the existing scss code and extracted all the colors we have there:

![2017-02-16-184009_807x307_scrot](https://cloud.githubusercontent.com/assets/3404133/23033183/6948dcae-f477-11e6-9d42-863d40011e4d.png)

I guess we can just go with a those and use darker/lighter functions for the others. Not sure if I'm missing something but this is basically what I end up with:

![newcolors](https://cloud.githubusercontent.com/assets/3404133/23033239/9ab98496-f477-11e6-8758-9c4a7942c218.png)

@skjnldsv Have you already started implementing the variable support? If not, would you mind if i take over then. I'd like to get this in soon, because fixing the theming app for all the recent css adjustments will be a pain otherwise. :wink:

**Comment by skjnldsv** [comment]
Please feel free! 😊
If you got any questions about how the suss compiler works, I'd be happy to help you!! 
My initial work was creating a variable.scss file containing everything and adding it to the import controller function.

**Comment by skjnldsv** [comment]
@juliushaertl I would also like to globalise borders and stuff (inputs, app-navigation...). Since it doesn't appear in your summary, I would like to suggest you add them :)

**Comment by juliushaertl** [comment]
@skjnldsv Ok, I'll have a look. 

I thought we can just start with colors for the first PR and add more stuff like borders, radius, ... afterwards. Makes it easier to review building it step by step. But I'll keep those in mind.

My plan was to add a list of variables to OC_Defaults and inject them into the SCSS compiler from there. The theming app as well as custom themes could then just overwrite those default values without any further changes.

**Comment by skjnldsv** [comment]
Don't bother adding a service in php. For the variable base, a simple scss is enough imo.
We'll need a service when we'll start coding the theming rewriting.

Yes, start simple, the review need to be easy. I think it should be good to do a commit per variable 😉

**Comment by MorrisJobke** [comment]
Fixed in #3530
