### ISSUE TITLE
LDAP breaks local login

### ISSUE THREAD

**Issue by Laeghaire** [nextcloud/server#32566]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I was trying to set ldap to ldaps on port 636 

I made sure I still had a LOCAL admin user in case of failure. The config immediately started saving and
the whole instance started to HANG. NO login possible after that even a server restart, nexcloud is 100% busy on the ldap config and won't even allow a local login, this is pretty catastrophic since I had to do a system restore a day b4..like..what ? this cant be the solution.

### Steps to reproduce

1.change ldap setting
2.
3.

### Expected behavior

Ldap works on port 636 with ldaps...or not..

BUT LOCAL USERS STILL WORK

### Installation method

Web installer on a VPS or web space

### PHP engine version

PHP 7.3

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
na
```

### List of activated Apps

```shell
na
```

### Nextcloud Signing status

```shell
na
```

### Nextcloud Logs

```shell
not avail after change
```

### Additional info

none

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
