### ISSUE TITLE
Use the search bar to search for files by tag

### ISSUE THREAD

**Issue by totalcaos** [nextcloud/server#326]
Currently to find files/folders with a particular tag within NextCloud you need to go to the "Tags" menu option then type in or select the tag(s) that you want to filter with.

Using the search function, it is not possible to search for files/folders with a specified tag as it does a full text search of the files, but not the associated tag.

Can the search function be enhanced to search for not only the full text/file names but also for the tag(s) associated with a file?  Another possible enhancement of the search can be to search for keywords entered in the search function within the comments associated with a file/folder

**Comment by Bugsbane** [comment]
It makes sense to list files that the user has specifically chosen to associate with the searchphrase, even more highly than if the word just appears in the content / filename somewhere.

I second that we should list these files when a user types in the tag name, preferably above other listings.

I would also love to see the ability to limit search results *just* to files tagged with a syntax like in GitHub, eg: tag:holiday2016

**Comment by jancborchardt** [comment]
Yeah, actually the full »Tags« functionality in the sidebar is nothing other than a search. We should combine that part with the actual search to make it more useful.

**Comment by totalcaos** [comment]
@jakobsack Indeed!  When you have terrabytes of data, the search functionality becomes critical.  What are we using to power the search? Is it the Zend_Search engine?

**Comment by Bugsbane** [comment]
From memory, I think I recall it being Lucene...

**Comment by totalcaos** [comment]
Hmmm ... doesn't look like it from the code.  Although there's a very good chance I may be wrong :)

**Comment by Bugsbane** [comment]
You're probably not wrong. I'm remembering this from a long time ago (like OC 5 or something)

**Comment by da3dsoul** [comment]
It also needs to be faster. If people really use tags, then it's not unreasonable to expect this for 3 minutes:
![chrome_2019-06-19_01-43-45](https://user-images.githubusercontent.com/5205810/59739774-ee450980-9233-11e9-8d47-ba546cb0db8d.png)

Followed by a 5 minute hang when you type a letter....
That's after aggressive caching and adding indexes to the systemtag and systemtag_object_mapping tabled.
![AnyDesk_2019-06-19_01-57-03](https://user-images.githubusercontent.com/5205810/59740295-ac1cc780-9235-11e9-9623-a4b5c17d6d23.png)
I don't even think that's unreasonable, really. The issue isn't with the database queries. Those are almost instantaneous with my setup, but the webui still grinds to a halt trying to deal with it.

**Comment by jancborchardt** [comment]
@da3dsoul thanks for the intense research! It is a different issue though, as this is about enhancing the search field to include tags.

Since your comment is about improving the performance, could you open a separate issue for that? Thanks! :)

**Comment by da3dsoul** [comment]
I absolutely can. I brought it here because it's directly a problem with implementing it. If you put it in, then the search bar would lock the whole page any time you clicked on it.

**Comment by jancborchardt** [comment]
@rullzer @MorrisJobke @daita maybe you can give @da3dsoul some pointers? :)

**Comment by da3dsoul** [comment]
#17499

**Comment by antonkarliner** [comment]
Competely agree with the initial topic, ability to include tags in search would be a bless

**Comment by BloodyIron** [comment]
Wait nextCloud has a Tagging ecosystem and the Search can't even filter based on tags? And this request was from 2016? How on earth did this happen? This is like Tagging functionality 101.

Can we PLEASE get Tag search functionality added already??? Like this is a really blatant shortcoming (not to mention how annoying it is to expose and then add tags per file).

Like, why bother tagging if it benefits me in no way in finding said content again? That's just asinine.

**Comment by XueSheng-GIT** [comment]
I was just starting to use the tag feature (using NC21) and realized that I can't find the tagged files afterwards. Is the "Tags" Category still the only way to find tagged files?

**Comment by BloodyIron** [comment]
Yeah why hasn't this been implemented? Tags are generally useless without searching by them. That's often the whole point of tags in any system.

**Comment by BloodyIron** [comment]
yay! \o/
