### ISSUE TITLE
Consider sending Referrer-Policy "strict-origin" security header

### ISSUE THREAD

**Issue by MatejKovacic** [nextcloud/server#32607]
Please add security header `Permissions-Policy`. More about that here:
https://scotthelme.co.uk/goodbye-feature-policy-and-hello-permissions-policy/

Also, please consider sending `Referrer-Policy "strict-origin"` security header.

**Comment by kesselb** [comment]
Sounds like https://github.com/nextcloud/server/issues/22792?

**Comment by joshtrichards** [comment]
For Permissions-Policy, we should close this Issue out in favor of #22792 to avoid confusion/duplicate work.

For Referrer-Policy: it's already set to `no-referrer` which is stricter than `strict-origin`.  Is there a reason you want it loosened?
