### ISSUE TITLE
NC client should not allow modifying a write protected file

### ISSUE THREAD

**Issue by virtnix** [nextcloud/server#3261]
### Steps to reproduce
1. Share a file to a user B with the option "Can Edit" unticked
2. User B : Once downloaded by the NC client, locally modify this file
3. Save the modified file

### Expected behaviour
User B should not be able to save the file, as it is write protected.

### Actual behaviour
File is locally saved, and the following error appears on the NC client :
25/01/2017 15:18:31, TODO_LIST, Nextcloud_test,Continue blacklisting: Error downloading https://share.infranix.eu/remote.php/webdav/TODO_LIST - server replied: Forbidden (Sabre\DAV\Exception\Forbidden)

File is then set as blacklisted on NC client

### Server configuration
**Nextcloud version:** : 11.0.0

Problem is that once the file has been saved, there is no way for User B to "recover" the original file, the file being blacklisted by the NC client.

I would suggest perhaps to :
   1 - Find a way to "physically" avoid the User B to edit the file

If point 1 is not possible :
   2 - Set locally a specific flag (there is already the green and blue one, perhaps a new red one? ) on the write protected files/folders, so that the user will be aware of the permissions set on them.
   3 - If the file has been edited anyway, create an explicit warning on the NC client (This file is write protected !!), and propose to the User B to download again the original file

Thanks !!

**Comment by MorrisJobke** [comment]
This is sadly a problem of the client. We also struggled a lot over this issue but didn't found a good solution that works cross-platform.

I need to refer you to the client repo, because this is a client only problem: https://github.com/owncloud/client/issues

**Comment by virtnix** [comment]
Ah yes, my bad, you are right wrong repo.

New issue created on the good one : 
https://github.com/owncloud/client/issues/5491

Thanks !
