### ISSUE TITLE
[Bug]: getAccessList in ShareByMailProvider uses incorrect array key

### ISSUE THREAD

**Issue by ASerbinski** [nextcloud/server#32630]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Per documentation https://github.com/nextcloud/server/blob/master/lib/private/Share20/Manager.php#L1671 -- share by mail should use the array key "mail". Instead, it is using the array key "public", which collides with array key used in DefaultShareProvider for share by link; https://github.com/nextcloud/server/blob/master/lib/private/Share20/DefaultShareProvider.php#L1368

Change is required here;
https://github.com/nextcloud/server/blob/master/apps/sharebymail/lib/ShareByMailProvider.php#L1211

### Steps to reproduce

Not applicable

### Expected behavior

ShareByMailProvider should use "mail" as array key.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
N/A
```

**Comment by kesselb** [comment]
Sounds good to me. Would you mind to submit a pr?

**Comment by ASerbinski** [comment]
> Sounds good to me. Would you mind to submit a pr?

I'm working on it now.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
