### ISSUE TITLE
Bug to Feature: Mounting special folders inside other folders.

### ISSUE THREAD

**Issue by noseshimself** [nextcloud/server#32645]
**Is your feature request related to a problem? Please describe.**
The root folder is becoming more and more cluttered. Additional external mounts and group folders are not helping that.

**Describe the solution you'd like**
I would like to be able to put everything into sub folders. It's possible with external mounts (although this is more looking like a bug than an intended feature) by selecting a mount point deeper inside the directory tree -- and as soon as the user is creating the directory tree leading to it, the external directory will be accessible. I would like this to be a documented feature and get the same treatment for group folders. If the server administrator really wants to he could add the required folders to the initial files for new accounts, too.

**Describe alternatives you've considered**
There are none I found.

**Comment by joshtrichards** [comment]
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#share-folder

Each individual user can also, by default, set their own default folder for accepted shares under `/settings/user/sharing`.

But I may have misunderstood your request.

**Comment by noseshimself** [comment]
I never noticed the *individual* settings. I guess we can close this now.
