### ISSUE TITLE
[Bug]: You don’t have permission to upload or create files here

### ISSUE THREAD

**Issue by tio-trom** [nextcloud/server#32659]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I moved my Nextcloud to a new server. It has around 3 thousand users. Everything seems to be working great except for 2 admin users that are part of all groups and shared folders. For these two I see the error "You don’t have permission to upload or create files here" after the Files loads for a minute or so. At times it loads all of the files, but more often than not I am seeing that error. All other users seem to work just fine. Everything else works well. The log only throws these errors:

```
[core] Error: More than 1000 expressions in a list are not allowed on Oracle.

PROPFIND /remote.php/dav/files/gianina.fratila/
from 91.90.123.27 by gianina.fratila at 2022-05-30T10:32:37+00:00
```

Or

```
[files] Warning: User gianina.massari still has unscanned files after running background scan, background scan might be stopped prematurely

at 2022-05-30T10:45:56+00:00
```

I have scanned all files with occ and cleaned files cache.

### Steps to reproduce

1. Login as an admin user
2. Click the Files

### Expected behavior

The user should have access to all of its files.

### Installation method

Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.3

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.8.0
  - admin_audit: 1.12.0
  - apporder: 0.15.0
  - auto_groups: 1.4.0
  - calendar: 3.3.1
  - circles: 22.3.1
  - cloud_federation_api: 1.5.0
  - collectives: 1.1.0
  - comments: 1.12.0
  - contacts: 4.1.1
  - contactsinteraction: 1.3.0
  - customproperties: 2.0.4
  - dashboard: 7.2.0
  - dav: 1.20.0
  - deck: 1.5.6
  - event_update_notification: 1.5.0
  - federatedfilesharing: 1.12.0
  - files: 1.17.0
  - files_accesscontrol: 1.12.1
  - files_automatedtagging: 1.12.0
  - files_downloadactivity: 1.13.0
  - files_pdfviewer: 2.3.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - forms: 2.5.0
  - impersonate: 1.9.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notes: 4.3.1
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - onlyoffice: 7.3.4
  - password_policy: 1.12.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - quota_warning: 1.14.0
  - ransomware_protection: 1.13.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - socialsharing_email: 2.5.0
  - spreed: 12.2.5
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - tasks: 0.14.4
  - text: 3.3.1
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - user_usage_report: 1.6.0
  - viewer: 1.6.0
  - w2g2: 3.3.8
  - webapppassword: 22.5.0
  - workflowengine: 2.4.0
Disabled:
  - activity: 2.13.4
  - announcementcenter: 6.3.0
  - encryption
  - external: 3.9.0
  - federation: 1.10.1
  - files_external: 1.11.1
  - files_fulltextsearch: 22.0.2
  - files_texteditor: 2.14.0
  - files_trackdownloads: 1.11.0
  - firstrunwizard: 2.8.0
  - fulltextsearch: 22.0.1
  - groupfolders: 10.0.2
  - metadata: 0.16.0
  - passwords: 2021.12.20
  - photos: 1.2.0
  - richdocuments: 4.2.7
  - richdocumentscode: 21.11.402
  - sharepoint: 1.10.1
  - social: 0.4.2
  - socialsharing_diaspora: 2.5.0
  - socialsharing_facebook: 2.5.0
  - support: 1.2.1
  - talk_simple_poll: 1.3.1
  - user_ldap
  - weather_status: 1.0.0
```

**Comment by tio-trom** [comment]
Update: So the File Sharing app is the one causing this for those accounts. Perhaps because it tries to display tons and tons of folders when accessing the Files. Disabling this app makes everything work well.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
