### ISSUE TITLE
[Bug]: x-download-options not in htaccess after maintainance:update:htaccess

### ISSUE THREAD

**Issue by arch-user-france1** [nextcloud/server#32676]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I updated my htaccess file using occ but the nc scanner still says that x-download-options is not set.

### Steps to reproduce

1. update htaccess
2. scan.nextcloud.com
3. see result (only rating A)

### Expected behavior

x-download-options would be set in the .htaccess file.

### Installation method

Manual installation

### Operating system

Other

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
not required
```

### List of activated Apps

```shell
not required
```

### Nextcloud Signing status

```shell
No  errors have been found.
```

### Nextcloud Logs

```shell
-
```

### Additional info

My Nextcloud had a bug #32578  which now seemed to get fixed up by itself.

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

https://github.com/nextcloud/server/pull/31629 we removed `X-Download-Options` header and forgot to update the security scanner :see_no_evil:

**Comment by szaimen** [comment]
should be fixed now. please try to scan again!

**Comment by arch-user-france1** [comment]
It works. Thank you for fixing.
