### ISSUE TITLE
Email template missing

### ISSUE THREAD

**Issue by veelo** [nextcloud/server#3267]
### Steps to reproduce
1. Enable the mail template editor app.
2. Admin -> Additional Settings -> Mail templates
3. Choose template "Sharing email (HTML or plain)". (The other templates _can_ be edited).

### Expected behaviour
The code for the sharing email should be loaded in the editor.

### Actual behaviour
Popup "Could not load template", "! template file not found: template:internalmail".
If you look in the template directory, the files internalmail.php and internalaltmail.php are indeed missing.

### Server configuration
**Operating system**:
Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-59-generic x86_64)

**Web server:**
Apache 2.4.18

**Database:**
MariaDB 10.0.28

**PHP version:**
7.0.13

**Nextcloud version:** (see Nextcloud admin page)
11.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Where did you install Nextcloud from:**
Nextcloud download page.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - files_versions
  - user_external
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oco82pbm345n",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.200.2"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.example.com",
        "dbtype": "mysql",
        "version": "11.0.1.2",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "loglevel": 2
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Safari

**Operating system:** Max OS X

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
{"reqId":"f5Vej08AeASvn81BN\/Jb","remoteAddr":"192.168.37.77","app":"PHP","message":"Undefined offset: 0 at \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http.php#149","level":3,"time":"2017-01-25T21:55:53+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/templateeditor\/settings\/mailtemplate?theme=example&template=core%2Ftemplates%2Finternalmail.php","user":"admin","version":"11.0.0.10"}
```
</details>

**Comment by nickvergessen** [comment]
Fix is in https://github.com/nextcloud/templateeditor/pull/16
