### ISSUE TITLE
Themed email templates are ignored.

### ISSUE THREAD

**Issue by veelo** [nextcloud/server#3268]
### Steps to reproduce
1. Enable the mail template editor app.
2. Admin -> Additional Settings -> Mail templates
3. Choose template "Lost password mail".
4. Change the wording of the message.
5. Try to log in with a wrong password, request reset.

### Expected behaviour
The mail text should be as in the changed template.

### Actual behaviour
The default mail is sent, changes are ignored.

### Server configuration
**Operating system**:
Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-59-generic x86_64)

**Web server:**
Apache 2.4.18

**Database:**
MariaDB 10.0.28

**PHP version:**
7.0.13

**Nextcloud version:** (see Nextcloud admin page)
11.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Where did you install Nextcloud from:**
Nextcloud download page.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - files_versions
  - user_external
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oco82pbm345n",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.200.2"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.example.com",
        "dbtype": "mysql",
        "version": "11.0.1.2",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "loglevel": 2
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Safari

**Operating system:** Max OS X

**Comment by nickvergessen** [comment]
You can only change these files when you use a theme.
I guess you changed the templates for the example theme? But your config doesn't say that you are using a theme. So make sure that you change the items for the theme you are using.

**Comment by veelo** [comment]
Well I _can_ change them, but I suppose you mean edits only have effect on themed templates. If I am not mistaken I have tried this, but I'll check and get back with the result. Thanks.

**Comment by veelo** [comment]
Update: when I tried customising a theme earlier I still had the Theming app enabled, which is why it didn't work. We prefer not to sacrifice the comfort of the theming app to get customised mails, so we'll let it be.

It would be great if the theming app and the mail template app would play well together. At least a note in the mail template app that it won't work if the theming app is enabled is probably appropriate.

Thanks.

**Comment by moritzthecat** [comment]
tried customizing the themes in NC 10 before to change the email templates but did not really succeed. The theming up instead is easy to use and provides sufficient features to change. It would be very comfortable if the email templates could be edited while using the theming app.
