### ISSUE TITLE
Enhancements for file drop (upload only)

### ISSUE THREAD

**Issue by 42ske** [nextcloud/server#32698]
**Is your feature request related to a problem? Please describe.**
If you use file drop for uploading application documents it would be very helpful to have an ability of automatically renaming the uploaded files as well as sending automated confirmations of receipt via email.

**Describe the solution you'd like**
There should be a form with at least fields for:
- first name
- surname 
- gender
- mail address
- maybe further

file upload should be able in the next step after filling the form.

1st: In the backend it should be possible to define the file names e.g. "surname, first name 'application' upload-date upload-time.pdf" so that all files are renamed following this scheme and than saved in the upload folder.

2nd it should be possible to define which file types are allowed to upload or aren't allowed to upload. The attempt to upload a not allowed file type should result in a user definable error message.

Also it would be fine if the uploaded files were checked in this step if they are damaged. Damaged files should result in an error message „Your file is damaged. Please try again.“

3rd it should be possible to define a default text for the confirmation of receipt, which variables for personal address (also respecting the correct address regarding gender) date of upload and so on. It should be possible to define the senders address.

Advanced would be the ability to upload two or more documents which get different names, e.g. "letter of application", "CV", "attachements" (of course again using the variabeles for surname, first name, dates etc.)

**Describe alternatives you've considered**
—

**Additional context**
—

**Comment by 42ske** [comment]
This is understandable, but would be a great pity. The proposed extensions would be very powerful and would make it easier for many to use.

**Comment by joshtrichards** [comment]
@42ske Did you explore existing approaches for maybe doing this - such as via Flow (as was mentioned by @PVince81) alongside various existing Flow add-ons? Your original request left the "Alternatives you've considered" blank. :-)

* https://docs.nextcloud.com/server/latest/admin_manual/file_workflows/index.html

* https://apps.nextcloud.com/apps/files_scripts
- https://github.com/Raudius/files_scripts/blob/master/docs/Admin.md

* https://apps.nextcloud.com/apps/flow_notifications
* https://apps.nextcloud.com/apps/workflow_script
  - e.g. https://github.com/nextcloud/workflow_script
