### ISSUE TITLE
Default config.php appstore

### ISSUE THREAD

**Issue by agowa338** [nextcloud/server#3269]
The default config.php file (generated by the webinterface after first launch) does not contain the following two lines, so the appstore is not working:
```
'appstoreenabled' => true,
'appstoreurl' => 'https://api.nextcloud.com/v1',
```

**Comment by MorrisJobke** [comment]
The appstore is enabled by default. This option is there to set it to `false` to disable it. See https://github.com/nextcloud/server/blob/d59ffb8bf121b326fe7dd5b67103db306bd0a3ae/settings/Controller/AppSettingsController.php#L111-L111 for example.

Therefore this issue is invalid.

**Comment by agowa338** [comment]
Than there is an issue, i used the Version 11 release attached to this repository.
Than I unziped it into the webserver directory.
Than I opened the browser and completed the first install from the browser.
It was not showing up until I manually added those two lines to the configuration file.

**Comment by MorrisJobke** [comment]
> The Webshop was not showing up until I manually added those two lines to the configuration file.

api.nextcloud.com does not exist 🙈 

What host have you entered there?

**Comment by MorrisJobke** [comment]
> 'appstoreurl' => 'https://api.nextcloud.com/v1',

I also noticed that his is not a valid config key.



> 'appstoreenabled' => true,

This one is usually the default. Maybe it is in another config.php (check the config/ directory for any file that ends on `.config.php`) disabled and placing this in there just overwrites it.

**Comment by agowa338** [comment]
There are no more and no less files than are in the download from here.
As I don't have any files there yet I think I repeat all steps starting with the download.

**Comment by agowa338** [comment]
```
su -s /bin/bash www-data
cd /var/www/public
wget https://download.nextcloud.com/server/releases/nextcloud-11.0.1.zip
unzip nextcloud-11.0.1.zip
nano config/config.php
```
Than I use my webbrowser and go to https://www.website.com/nextcloud and do the following:
 - select MariaDB
 - Enter Database credentials (Databasename "nextcloud")
 - Enter Username and Password of the first administrator
 - Click on "Finish Setup"

Ok and now it's working without that lines.
Should have checked before if it is reproducible...

I'm sorry to have wasted your time.
