### ISSUE TITLE
occ app:list --disabled

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#32699]
Above command can help admins to automate things.
Right now the disabled apps are shown as a subset of "app:list", but not in isolation.

**Comment by JustAdamHere** [comment]
Hi there @tobiasKaminsky. I'm looking to fix my first issue and came across this one, but I'm struggling a little bit in getting started. Could you point me in the right direction?

**Comment by tobiasKaminsky** [comment]
@PVince81 can you help Adam here?
@JustAdamHere I "just" created this issue, but do not have real server development experience.

**Comment by PVince81** [comment]
@JustAdamHere you can start here https://docs.nextcloud.com/server/latest/developer_manual/getting_started/devenv.html

the code in question is here: https://github.com/nextcloud/server/blob/master/core/Command/App/ListApps.php#L46
