### ISSUE TITLE
Accessibility Status in Nextcloud?

### ISSUE THREAD

**Issue by akash07k** [nextcloud/server#32695]
I'm a screen reader user and am visually impaired.
I want to deploy Nextcloud on my homeserver but worried about the state of accessibility.
* Is Nextcloud accessible for screen readers?
* Does Nextcloud team take accessibility seriously?
* Is there any work going on in Nextcloud for improving it's accessibility with screen readers and assistive technologies?

**Comment by JuliaKirschenheuter** [comment]
Hello @akash07k, thank you for asking for this important topic!

Fist of all i would like to say, that we are continuously working on accessibility topics. We are trying to do our best to make a software accessible for everybody!

We have a special label for all our accessibility issues named ```label:"feature: accessibility"```, feel free to search for opened and closed ones in a Issue list.

> * Is Nextcloud accessible for screen readers?

yes

> * Does Nextcloud team take accessibility seriously?

yes

> * Is there any work going on in Nextcloud for improving it's accessibility with screen readers and assistive technologies?

yes, please see https://github.com/nextcloud/server/labels/feature%3A%20accessibility. Of coarse our other Apps have accessibility issues too (opened and closed).

Please keep in mind, that accessibility issues is ongoing improving process, and there are still issues to implement or to improve. If you find stuff, which you would like to have or improve, you could open an Issue each time!

**Comment by tyrylu** [comment]
I'd say, as a screen reader user as well, that the a11y posture is pretty good. Yes, for such a large software system you must expect some issues, but it is pretty hard to find them and when they appear, at least for my usecases, they are nothing big, they are small things. And when they appar and are reported, fixing them is a pretty high priority. For the other context, see the previous comment.

**Comment by akash07k** [comment]
@JuliaKirschenheuter  Amazing! thanks a lot! it's really appreciated.
Even I'm also a developer and I'll fork the code and will try to fix any accessibility issues if I come across.
Will check if codebase is understandable to me or not.
@tyrylu  that's so nice! I'm pretty excited to deploy it on my server now. I'll do it in morning straight away! 
Wow guys, you are amazing.
