### ISSUE TITLE
Very first LDAP config has empty ID

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#3270]
The first created LDAP config has the ID `` (empty string). That makes it hard to use the OCS API in #3162 to manipulate this, because then the response is: 

```
$ curl -X GET http://admin:admin@localhost/server/ocs/v2.php/apps/user_ldap/api/v1/config/ -H  "OCS-APIRequest: true" -i
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>404</statuscode>
  <message>Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services. DEBUG OUTPUT:
</message>
 </meta>
 <data/>
</ocs>
```

@blizzz Any idea how to prevent this and fix it?

**Comment by blizzz** [comment]
Used to be intentional, but changed with  https://github.com/nextcloud/server/pull/3162/commits/689df9a843dd0505088143de039af775a3f92612 in #3162, coming to 12  and 11.0.2.

Workaround until: create 2 and delete the one without prefix subsequently.
