### ISSUE TITLE
Remove constructor from IStorage interface

### ISSUE THREAD

**Issue by come-nc** [nextcloud/server#32709]
`\OCP\Files\Storage\IStorage` and `\OCP\Files\Storage` contain a constructor, which triggers errors and warninigs en classes implementing those that other parameters in their constructor, like `\OC\Encryption\Keys\Storage`.

I’m _pretty_ sure there is no reason to have these constructors in the interfaces, unless we sometime build an instance without knowing which class it is?

**Comment by CarlSchwan** [comment]
yes please kill it with :fire:

**Comment by ArtificialOwl** [comment]
![image](https://user-images.githubusercontent.com/1038617/171674302-769ea2fc-7e71-4918-a9a9-9d9d68c62f4a.png)

**Comment by icewind1991** [comment]
> unless we sometime build an instance without knowing which class it is?

https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/private/Files/Storage/StorageFactory.php#L82

**Comment by come-nc** [comment]
> > unless we sometime build an instance without knowing which class it is?
> 
> https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/lib/private/Files/Storage/StorageFactory.php#L82

Thank you for the reference.
But is seems we do not actually use this function, or at least not in core?
How will that work with encryption storage which have other parameters?

It seems the wrap method should be enough, I do not see the value in building the instance this way.
