### ISSUE TITLE
[Bug]: Quota settings do not "stick" - reproducible

### ISSUE THREAD

**Issue by rightsaidfred99** [nextcloud/server#32714]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello, when creating a new user, the default quota is set. 
If I try to limit that quota to 0 B, it keeps on resetting to "Unlimited". 

One has to set an arbitrary value to like 4 GB or anything other than the default, *then* 0 B and only then, Nextcloud will keep the 0 B. 

### Steps to reproduce

1) One has to set an arbitrary value to like 4 GB or anything other than the default, 
2) *then* 0 B and only then, Nextcloud will keep the 0 B. 

### Expected behavior

You should be able to go from default Unlimited to 0 B

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
default apps
```

**Comment by solracsf** [comment]
I can't reproduce it (v22.2.7):

1. Create user with default quota
2. Edit him and change quota to `0`
3. Validate the check-mark
4. Quota is `0`
5. Navigate to another page (`Files`)
6. Visit `Users` page again, quota of user is still `0`

**Comment by PVince81** [comment]
I've seen reports of this earlier where an update solved the issue, please update to the latest point release and try again.

if the problem persists, please attach your config so we know what exact version you are using
