### ISSUE TITLE
[Bug]: password app: cannot save new password

### ISSUE THREAD

**Issue by martin3000** [nextcloud/server#32717]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I want to manually create a new password entry, I cannot save it. When I press "save", I get a prompt to fill in the password field. Maybe this is because I did not enter a page field name. But the prompt tells me to fill out the password field which I already filled out.

![image](https://user-images.githubusercontent.com/21184101/171815239-1c2f711a-fae9-4e6a-ae5d-c60b1e9f856d.png)

### Steps to reproduce

1. go to http://.....//apps/passwords/#/folders
2. click the "+" sign near the top
3. select new password when prompted
4. enter password, username pagename and name
5. (do not enter a field)
6. click save

### Expected behavior

Password is saved or I should be promtped to enter a field name

### Installation method

Official SNAP package

### Operating system

Debian/Ubuntu

### Database engine version

MySQL

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
sudo nextcloud.occ config:list system
{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "nuc:81",
            "1": "nuc:444",
            "2": "nuc.fritz.box:444",
            "3": "nuc.fritz.box:81",
            "5": "192.168.178.74"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.5.1",
        "overwrite.cli.url": "http:\/\/nuc:81",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "loglevel": 0,
        "theme": ""
    }
}
```

### List of activated Apps

```shell
sudo nextcloud.occ app:list
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - bookmarks: 10.3.1
  - bruteforcesettings: 2.4.0
  - calendar: 3.3.1
  - circles: 23.1.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.1.1
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - documentserver_community: 0.1.12
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_external: 1.15.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.12.1
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - onlyoffice: 7.3.4
  - password_policy: 1.13.0
  - passwords: 2022.5.20
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - tasks: 0.14.4
  - text: 3.4.1
  - twofactor_backupcodes: 1.12.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - encryption
  - occweb: 0.1.0
  - spreed: 13.0.6
  - theming: 1.9.0
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
-
```

### Additional info

-

**Comment by kesselb** [comment]
Hey @martin3000, thanks for reporting an issue :+1: 

Please report this problem to https://github.com/marius-wieschollek/passwords/issues
