### ISSUE TITLE
[Bug]: Contact interaction creates doubled contacts and there is no way to delete them

### ISSUE THREAD

**Issue by vactomas** [nextcloud/server#32721]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After accepting invitation to an event Contacts interaction created set of contacts with emails only. There is no way to delete them or add information. 

The behaviour follows the issue nextcloud/server#27524.

After deleting the event contacts still persist.

NC 24

### Steps to reproduce

1. Accept an event from invitation
2. Contacts are created as read-only
3. Delete the event

### Expected behavior

Contacts disappear or can be deleted

### Installation method

Official Docker image

### Database engine version

MariaDB

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - bruteforcesettings: 2.4.0
  - calendar: 3.3.1
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.1.1
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notes: 4.3.1
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - richdocuments: 6.1.0
  - richdocumentscode: 21.11.402
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - systemtags: 1.14.0
  - tasks: 0.14.4
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_totp: 6.3.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - encryption
  - end_to_end_encryption: 1.10.0
  - files_external
  - survey_client: 1.8.0
  - user_ldap
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by jph76** [comment]
It’s still present in Nextcloud 25.0.3/Contacts Interaction 1.6.0.

**Comment by Mannshoch** [comment]
It's a similar Problem to this one I wrote in 2018:
https://github.com/nextcloud/server/issues/9422

Here about reducing double contacts that appear because of shared Adress books. As a solution I propose to not use address books inside Nextcloud but only as a tool for connection with DAV. 
In that case you could create "Address books" per sharing partner (Nextclouds/Users/Applications)

**Comment by szaimen** [comment]
cc @ChristophWurst @JohannesGGE

**Comment by jph76** [comment]
@ChristophWurst You’re right, it’s data from the system addressbook. I’ve got a dedicated admin account for my familiy Nextcloud and that shows in my phone’s address book, too.

I can’t remove the phone numbers from the profiles… there’s no option to save.

I will now wait for the option to disable system addressbook sync as announced in #38880 .

Thanks for your advice!

**Comment by MicKress** [comment]
Perhaps it's a way if you can exclude the SAB from DAVsync? Like it's possible in OpenXChange. So you can decide which addressbooks are on your mobile device ...

**Comment by jdaviescoates** [comment]
I just hit this issue too

Some contacts randomly end up in my Recently Contacted here:

![image](https://github.com/nextcloud/server/assets/2113743/841c340e-4da0-4460-9fac-f7442aa190da)

But whilst they are then it's impossible to edit them, which is very frustrating. What possible purpose does this serve?

![image](https://github.com/nextcloud/server/assets/2113743/ee07c46c-c422-4da8-9e03-7f7c087a07d5)

I mean, I can see why Recently Contacted could be useful, but why lock them in read-only mode?!?

In my case, it isn't even people I have actually recently contacted (I guess because I'm using the SnappyMail app and not Nextcloud Mail), it's only people the Nextcloud Calendar has recently contacted (and yet, somewhat bizarrely, it isn't even all of them).

**Comment by ChristophWurst** [comment]
> I mean, I can see why Recently Contacted could be useful, but why lock them in read-only mode?!?

The idea is that you can *clone* them to a personal, writable address book.

**Comment by jdaviescoates** [comment]
> > I mean, I can see why Recently Contacted could be useful, but why lock them in read-only mode?!?
> 
> The idea is that you can _clone_ them to a personal, writable address book.

OK, but some of them appear to be _existing_ contacts, not new ones. So cloning them would just create duplicates, no?

**Comment by ChristophWurst** [comment]
> OK, but some of them appear to be _existing_ contacts

Not after https://github.com/nextcloud/server/pull/41046.

Having duplicates after *cloning* is expected
