### ISSUE TITLE
Ellipsize user name in top right

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#3273]
Currently there is no width limit on the username. This can lead to overlays with long names and narrow screens. For that we should either have a maximum width, or flexible so it automatically ellipsizes when the space gets narrow.

This is probably easy now with the switch to flexbox. Before it was a bit finnicky. cc @nextcloud/designers

**Comment by claell** [comment]
A different approach would be the following:
Currently the name is displayed when there is no image set.
Instead of showing the name one could display an image with the initials like in the settings where an image can be set.

**Comment by skjnldsv** [comment]
I would agree to go avatar only in the case of a too narrow screen.
We could ellipsis for too long name but it could be great to go avatar for small screens

**Comment by claell** [comment]
Currently avatar will be always used when set, so why not have it also on larger screens when not set?

**Comment by skjnldsv** [comment]
I don't know. This is a good question.
@nextcloud/designers what do you think?

**Comment by MorrisJobke** [comment]
> I don't know. This is a good question.
> @nextcloud/designers what do you think?

Because we don't want to placeholder be there. The placeholder is okayish, but not super perfect ;)

**Comment by jancborchardt** [comment]
We decided against this actually because then you have a colored placeholder there in the top right. And the color probably clashes with the Nextcloud blue, or theme color. That’s why we use a name.

**Comment by skjnldsv** [comment]
This is indeed a good decision.
Thanks for the heads up @jancborchardt

**Comment by claell** [comment]
Thanks for explanation. Makes sense, if the colour of the placeholder avatar is random.

**Comment by skjnldsv** [comment]
What about removing the user name and put it inside the dropdown menu on narrow screen?
We could use something like a setting icon instead?

**Comment by MariusBluem** [comment]
> What about removing the user name and put it inside the dropdown menu on narrow screen?
We could use something like a setting icon instead?

Wow. Nice idea 👍 I thought about something like this, where you can also change your spreed/chat online status and maybe see your quota:

![img_0409](https://cloud.githubusercontent.com/assets/19711361/22499688/8948d0a4-e860-11e6-9b93-15069659ab15.PNG)

**Comment by skjnldsv** [comment]
This is amazing!! 😱😱😱😍😍

**Comment by skjnldsv** [comment]
@MariusBluem Could you work on it? 😍

**Comment by MariusBluem** [comment]
> Could you work on it? 😍

I'd love to do ... bit I am really not an developer 😅😞 
You see...its not a good idea to give a non-developer a iPad Pro with Pencil 😜

> PS: are you associating administrators with a rotten apple? 😱

You see ... I am at least not able to draw a **gear** 😒

**Comment by skjnldsv** [comment]
Ahaha, so sorry! 😂
But it was a beautiful rotten apple though! 😆

**Comment by skjnldsv** [comment]
So, what icon should we use as the menu-opener-button? :)

A setting icon?

**Comment by MorrisJobke** [comment]
> A rotten ap A setting icon?

I only can find examples that use the avatar -.-

**Comment by eppfel** [comment]
I'd go for a single-user icon. I mean it would duplicate with the personal menu item, but for non-admins, that is actually what the menu is for: profile (personal), help and logout.

**Comment by MariusBluem** [comment]
A single-user icon would conflict with the contacts menu-icon which will be introduced with Nextcloud 12 ... @ChristophWurst - see #3233

**Comment by eppfel** [comment]
Was not aware. What if we use a non-colored avatar then? There was a issue about changing the default avatars. Maybe we have to think this through more...

**Comment by skjnldsv** [comment]
Ahahah, see https://github.com/nextcloud/server/issues/3273#issuecomment-275748570 @eppfel

**Comment by eppfel** [comment]
I was referring to that comment. Therefore I particular propose a

> **non-colored** avatar

Or am I lost here?

**Comment by skjnldsv** [comment]
Hum, could be nice indeed!

**Comment by jancborchardt** [comment]
Sooo this is a great idea -> can you open a separate issue for it @MariusBluem? :)

Because long usernames are still an issue and unrelated to this. Let's not derail the thread. ;)

**Comment by skjnldsv** [comment]
Well, if we go for icon only then the long username will be irrelevant right?

**Comment by jancborchardt** [comment]
Sorry but the top right should always be personalized. Either profile image or ellipsized name. No generic user icon because then you don't know immediately with which user you are logged in if you have multiple.

**Comment by skjnldsv** [comment]
An avatar with fixed colour is a good idea though, and it will help fix nextcloud/notifications#60.

See @eppfel's comment

**Comment by jancborchardt** [comment]
A non colored avatar has two issues:
- We use colored avatar placeholders everywhere else. It’s confusing and not consistent.
- It would be the first letter of the name. So basically how a name would look ellipsized on a small display. On big screens it’s fine though.

Think _responsive_, folks. ;) This is only an issue on small displays, on big screens it’s super nice how we do it. This is simply about ellipsizing long names correctly, nothing more and nothing less. :)

**Comment by skjnldsv** [comment]
I honestly don't see the point of seeing my username on the header in my opinion. :)
But I can understand that people wants to.

Github just put the avatar for example, and without displaying the username.

**Comment by eppfel** [comment]
I see it as @skjnldsv It is only relevant for multi accounts, which I believe to be the minority.

**Comment by MorrisJobke** [comment]
This is fixed with #4074
