### ISSUE TITLE
[Bug]:  Class 'OC\\DB\\OC' not found

### ISSUE THREAD

**Issue by jeesk** [nextcloud/server#32734]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I use window 11. Nextcloud runs in the idea. When I install it, an exception is thrown

env:    window 11 , jectbrains idea, php7.4.3nts, Version: v22.2.0.

{"reqId":"BAiiiFj9EyEfTucnrkEn","level":3,"time":"2022-06-06T10:54:02+00:00","remoteAddr":"::1","user":"--","app":"index","method":"POST","url":"/index.php","message":"Class 'OC\\DB\\OC' not found","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.72 Safari/537.36","version":"24.0.0.5","exception":{"Exception":"Error","Message":"Class 'OC\\DB\\OC' not found","Code":0,"Trace":[{"file":"D:\\myProject\\server\\lib\\private\\DB\\MigrationService.php","line":192,"function":"createMigrationTable","class":"OC\\DB\\MigrationService","type":"->","args":[]},{"file":"D:\\myProject\\server\\lib\\private\\DB\\MigrationService.php","line":265,"function":"getMigratedVersions","class":"OC\\DB\\MigrationService","type":"->","args":[]},{"file":"D:\\myProject\\server\\lib\\private\\DB\\MigrationService.php","line":443,"function":"getMigrationsToExecute","class":"OC\\DB\\MigrationService","type":"->","args":["latest"]},{"file":"D:\\myProject\\server\\lib\\private\\DB\\MigrationService.php","line":418,"function":"migrateSchemaOnly","class":"OC\\DB\\MigrationService","type":"->","args":["latest"]},{"file":"D:\\myProject\\server\\lib\\private\\Setup\\AbstractDatabase.php","line":153,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->","args":["latest",true]},{"file":"D:\\myProject\\server\\lib\\private\\Setup.php","line":371,"function":"runMigrations","class":"OC\\Setup\\AbstractDatabase","type":"->","args":[]},{"file":"D:\\myProject\\server\\core\\Controller\\SetupController.php","line":74,"function":"install","class":"OC\\Setup","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"D:\\myProject\\server\\lib\\base.php","line":955,"function":"run","class":"OC\\Core\\Controller\\SetupController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"D:\\myProject\\server\\index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"D:\\myProject\\server\\lib\\private\\DB\\MigrationService.php","Line":128,"CustomMessage":"--"}}
{"reqId":"BAiiiFj9EyEfTucnrkEn","level":3,"time":"2022-06-06T10:54:02+00:00","remoteAddr":"::1","user":"--","app":"PHP","method":"POST","url":"/index.php","message":"Module 'sqlite3' already loaded at Unknown#0","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.72 Safari/537.36","version":"24.0.0.5"}

### Steps to reproduce

But I click the Install button of nextcloud. I select SQLite3, and then an error is reported

### Expected behavior

i hope install finished

### Installation method

Other

### Operating system

Other

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

SQlite

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
none
```

### List of activated Apps

```shell
none
```

### Nextcloud Signing status

```shell
none
```

### Nextcloud Logs

```shell
{"reqId":"BAiiiFj9EyEfTucnrkEn","level":3,"time":"2022-06-06T10:54:02+00:00","remoteAddr":"::1","user":"--","app":"index","method":"POST","url":"/index.php","message":"Class 'OC\\DB\\OC' not found","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.72 Safari/537.36","version":"24.0.0.5","exception":{"Exception":"Error","Message":"Class 'OC\\DB\\OC' not found","Code":0,"Trace":[{"file":"D:\\myProject\\server\\lib\\private\\DB\\MigrationService.php","line":192,"function":"createMigrationTable","class":"OC\\DB\\MigrationService","type":"->","args":[]},{"file":"D:\\myProject\\server\\lib\\private\\DB\\MigrationService.php","line":265,"function":"getMigratedVersions","class":"OC\\DB\\MigrationService","type":"->","args":[]},{"file":"D:\\myProject\\server\\lib\\private\\DB\\MigrationService.php","line":443,"function":"getMigrationsToExecute","class":"OC\\DB\\MigrationService","type":"->","args":["latest"]},{"file":"D:\\myProject\\server\\lib\\private\\DB\\MigrationService.php","line":418,"function":"migrateSchemaOnly","class":"OC\\DB\\MigrationService","type":"->","args":["latest"]},{"file":"D:\\myProject\\server\\lib\\private\\Setup\\AbstractDatabase.php","line":153,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->","args":["latest",true]},{"file":"D:\\myProject\\server\\lib\\private\\Setup.php","line":371,"function":"runMigrations","class":"OC\\Setup\\AbstractDatabase","type":"->","args":[]},{"file":"D:\\myProject\\server\\core\\Controller\\SetupController.php","line":74,"function":"install","class":"OC\\Setup","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"D:\\myProject\\server\\lib\\base.php","line":955,"function":"run","class":"OC\\Core\\Controller\\SetupController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"D:\\myProject\\server\\index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"D:\\myProject\\server\\lib\\private\\DB\\MigrationService.php","Line":128,"CustomMessage":"--"}}
{"reqId":"BAiiiFj9EyEfTucnrkEn","level":3,"time":"2022-06-06T10:54:02+00:00","remoteAddr":"::1","user":"--","app":"PHP","method":"POST","url":"/index.php","message":"Module 'sqlite3' already loaded at Unknown#0","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.72 Safari/537.36","version":"24.0.0.5"}
```

### Additional info

JQMIGRATE: Migrate is installed, version 3.3.2
session-heartbeat.js:103 session heartbeat polling started

**Comment by kesselb** [comment]
Hi, we don't support windows.

**Comment by jeesk** [comment]
> Hi, we don't support windows.

thanks a lot !
