### ISSUE TITLE
Triangle for Notifications menu

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#3274]
All header menus have the nice triangles now, except the notifications menu. Should be just like for the apps and user menu, see https://github.com/nextcloud/server/issues/3217#issuecomment-274733665

cc @nextcloud/designers @nickvergessen

**Comment by nickvergessen** [comment]
You know the right repository to report this is at https://github.com/nextcloud/notifications
.....

**Comment by skjnldsv** [comment]
I would gladly include that into header.scss and add a specific class for that.

**Comment by MorrisJobke** [comment]
Fixed
