### ISSUE TITLE
"{actor} removed themselves from {file}" notification sentence is not true (bug or feature, i don't know)

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/server#32778]
When you share a file or folder with a user, and the user decides to leave it, a notification is displayed (e-mail and/or push). 

The phrase is: "{actor} removed themselves from {file}".

**This is incorrect, as it is only one person.**

The sentence would be correct if the notification referred to more than one person, but this is not the case.

**I have tested this by sharing a file with two users who both left at the same time. I did receive two separate notifications:** 
- "{user a} removed themselves from {file}"
- "{user b} removed themselves from {file}"

**The sentence should therefore be (2 proposals):** 
- {user} removed herself/himself from {file}
- {user} has left your sharing of {file}

**If I had to summarise, the sentence should be singular (not plural) because it is only about one user (one user per notification) each time.**

**Comment by Jerome-Herbinet** [comment]
Following my suggestion in Transiflex, the french translation is now changed (https://www.transifex.com/nextcloud/nextcloud/translate/#fr/files_sharing/159692462?q=text%3Athem), and integrated in Nextcloud 24.0.2, 23.0.6, and 22.2.9.
As I expected and after re-testing (push notifications and email notifications, as well as activities), the sentence is much more understandable as well as grammatically correct now.
**I suggest that the English texts be modified in the same way. Can somebody take car of that ?**

**Comment by Jerome-Herbinet** [comment]
@ChristophWurst or anyone else, changes have been made in French via https://www.transifex.com/nextcloud/nextcloud/translate/#fr/files_sharing/159692462. I think that the English sentences should be changed as well. Can somebody take care of that in GitHub ? Best regards

**Comment by ChristophWurst** [comment]
https://en.wikipedia.org/wiki/Singular_they the message means that only the actor removed themselves. Nobody else. 

I hope this helps with translation
