### ISSUE TITLE
Do not advertize the use of email as a valid username if explicitely disabled in configuration

### ISSUE THREAD

**Issue by ArnY** [nextcloud/server#3278]
By default, the username input box on the login page has a default value of "Username or email". While this is true with the default configuration, it will still be displayed even if ldap_loginfilter_email is set to false in the ldap configuration, thus misleading users.

The placeholder value for this input should be dependant of the dap_loginfilter_email and ldap_loginfilter_username values.

**Comment by nickvergessen** [comment]
@blizzz can you confirm quickly?

**Comment by blizzz** [comment]
@nickvergessen Yes,  we have this text unconditionally in the template: https://github.com/nextcloud/server/blob/master/core/templates/login.php#L43

@ArnY is right in the way that what you can use for logging in is backend dependent, and we don't know what some backend is accepting. Technically correct would be solely ``Loginname``.

**Comment by nickvergessen** [comment]
I think I would accept "if ldap enabled and that thing is switched off, use a different placeholder"

**Comment by blizzz** [comment]
Wouldn't work exactly, to reliable discover this we'd need to parse the login filter. 

Could be as well an admin setting, with l10ned "Username" and "Username or email" or untranslated free text. Less Voodoo.

**Comment by MariusBluem** [comment]
https://github.com/nextcloud/server/pull/3698

**Comment by stanelie** [comment]
I am using an up to date version of Nextcloud with a LDAP backend, and I unticked the option to use email addresses in the LDAP config.
However, the login field still says I can use usernames or emails to login. Should I do something else for this feature to work?

**Comment by kesselb** [comment]
> I am using an up to date version of Nextcloud with a LDAP backend, and I unticked the option to use email addresses in the LDAP config.
> However, the login field still says I can use usernames or emails to login. Should I do something else for this feature to work?

No. It's not implemented.

**Comment by szaimen** [comment]
I suppose this is still valid?

**Comment by Signum** [comment]
> I suppose this is still valid?

As of version 20.0.10 – yes, it is.

**Comment by szaimen** [comment]
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!

**Comment by max-nextcloud** [comment]
Still an issue in 23, 24 and 25.
