### ISSUE TITLE
user_external should log error message if authentication over imap does not work

### ISSUE THREAD

**Issue by yennor** [nextcloud/server#3279]
### Steps to reproduce
1. activate user_external app
2. change config.php to activate login over imap (but have an error in your configuration)
3. try to login

### Expected behaviour
If it can not login over imap show a message what the error was!

### Actual behaviour
It just shows a general purpose error message, that login was not successful.

It took me over an hour to find out, that the user_external app was properly enabled and even executed, just that the server certificate was wrong.
I managed to find that out by adding only adding a single line to imap.php

OCP\Util::writeLog('user_external', implode('|', imap_errors()), OCP\Util::ERROR);

**Comment by nickvergessen** [comment]
Please open a new issue in the repository of the app:
https://github.com/nextcloud/apps/issues
