### ISSUE TITLE
Tuning of Theming (color) options 

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#328]
I really appreciate the Theming options in the administrator menu to  be able to achieve individual Themes.
Since this is Version 1.0, there might be room for further development.
I would like to see options for 

      **Saturation
      Lightness**

as in (http://www.w3schools.com/colors/colors_picker.asp) for further color fine tuning!

Thanks and best regards, hitam4450

**Comment by jospoortvliet** [comment]
I agree with @juliushaertl  - you can even just insert a hex color so anything is possible already. I think the color selection is fine ;-)

**Comment by hitam4450** [comment]
Yes, the color selection is Ok...but not the tuning of the color selection!

I tried several different colors already, all are to bright and not really nice!

regards, hitam4450

**Comment by Bugsbane** [comment]
It's already possible to alter saturation and lightness. Alter saturation by raising / lowering the circle, alter lightness by raising/lowering the bar on the right. That said, jscolor does already support entering straight HSV (hue, saturation, value/lightness) values very easily. Just take a look at the "HSV/HVS mode" example script (3 lines) [here](http://jscolor.com/examples/).

**Comment by hitam4450** [comment]
Well, that sounds nice. The feature is **not available** in NextCloud theming app!

regards, hitam4450

**Comment by juliushaertl** [comment]
But changing jscolor to HSV / HVS mode will not add any additional value, any possible color can also be selected with the current color picker.

**Comment by jancborchardt** [comment]
Closing this because of aforementioned comments. Any color value is selectable in this color picker. Adding more options will not make it simpler for the majority but more confusing. If you really want to have a specific color, then you can also copy/paste it from the style guide of your organization, or use a full graphics program to adjust the color perfectly. :)
