### ISSUE TITLE
[Bug]: .htaccess RewriteRule for caldav/carddav MAY not use appropriate scheme for redirection

### ISSUE THREAD

**Issue by philippelt** [nextcloud/server#32826]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

IOS Clients failed to synchronize cards and calendar when Nextcloud is run behind a reverse proxy which is terminating the https and sending http request to apache/nextcloud instance.

When the redirection link is sent back to the client, the scheme is http. If the reverse proxy do not support http to https redirection, the client fallback to https to the root and failed with a 405 error in the access log.

I consider this to be a bug of the server as .htaccess is part of Nextcloud server code base and the inside RewriteRule is returning a wrong url for redirection.

### Steps to reproduce

1. Install Nextcloud (I use 24.0.1) listening only http and provide all parameters in config.php to define reverse proxy ('overwriteprotocol' => 'https', 'overwritehost' => <proxy_fqdn>, ...)
2. Install any reverse proxy terminating https and sending back requests to nextcloud in plain http
3. curl -vvv https://<proxy_fqdn>/.well-known/caldav
4. The "location" returned for redirection is http://<proxy_fqdn>/remote.php/dav

### Expected behavior

The location should have been **https**://<proxy_fqdn>/remote.php/dav

If the reverse proxy is listening on http port and automatically redirecting, the problem will not be seen.
In my case, I no longer use any http only service thus, to reduce noise, I closed the 80 port at the firewall level and no redirection happen -> 405 error and no IOS sync.

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - calendar: 3.3.1
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.1.1
  - contactsinteraction: 1.5.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_totp: 6.3.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - workflowengine: 2.6.0
Disabled:
  - dashboard: 7.0.0
  - encryption
  - federation: 1.9.0
  - files_external
  - recommendations: 0.6.0
  - survey_client: 1.7.0
  - user_ldap
  - weather_status: 1.0.0
```

### Additional info

**WORKAROUND**

The Nextcloud config parameters are only accessible to PHP, not Apache. The only way I found was to define a new environment variable : REWRITE_SCHEME specifying the scheme that should be used for rewrite rules.

This environment variable is defined in my docker-compose.yml file with the value "https".

I changed the RewriteRule in .htaccess from :  
```
RewriteRule ^$ /remote.php/webdav/ [L,R=302]
RewriteRule ^\.well-known/carddav /remote.php/dav/ [R=301,L]
RewriteRule ^\.well-known/caldav /remote.php/dav/ [R=301,L]
```

replaced by : 
```
RewriteRule ^$ %{ENV:REWRITE_SCHEME}://%{SERVER_NAME}/remote.php/webdav/ [L,R=302]
RewriteRule ^\.well-known/carddav %{ENV:REWRITE_SCHEME}://%{SERVER_NAME}/remote.php/dav/ [R=301,L]
RewriteRule ^\.well-known/caldav %{ENV:REWRITE_SCHEME}://%{SERVER_NAME}/remote.php/dav/ [R=301,L]
```

This solves the issue.

My concern is that this change is above the line of .htaccess : 
```
#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
```

And so, I suspect that these changes may be cancelled at any time during an upgrade or other kind of housekeeping operation. I added a periodic control of these lines to be informed in case of overwrite.

I would be glad to know if there is a stronger way to fix this problem.

**Comment by kesselb** [comment]
Hi @philippelt, thanks for your bug report :+1: 

I see you already did some research. Indeed the .htaccess file does not has access to overwriteprotocol.

My recommendation is that you setup the redirects for the service discovery on your reverse proxy: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html?highlight=discovery#service-discovery

**Comment by philippelt** [comment]
Thanks for answering.

Sorry , I didn't found the appropriate documentation which is clear and even provide my required settings (I'm using Traefik 2). Nextcloud is definitely awesome !

Does the provided solution also take car of the first line of .htaccess (RewriteRule ^$ ) ?

**Comment by kesselb** [comment]
I don't think so. But there is a good chance this line is not relevant for you.

**Comment by philippelt** [comment]
@kesselb, the today upgrade to 24.0.2 confirmed that my modified .htaccess has been replaced.

Unfortunately, the proposed change failed to solve the problem and I should have noticed that it couldn't work. 

The link sent back by the app is based on the http scheme and, my platform not being listening on port 80, traefik will never receive the bad url to rewrite it with appropriate path => sync will fail again.

I remember that Apache may be able to rewrite response link sent back to client *before* they are actually sent back but I have not enough experience on Apache to do it and I am not sure that there would be no side effects on other parts of Nextcloud.

For security reason, *I do not want* to listen on http port and I will stay with my unsupported method.

As it is very flexible, using an envvar to adapt the .htaccess content to the reverse proxy configuration, I think the nextcloud team should consider a robust way to solve what I still consider a bug of the implementation. As I said, .htaccess is part of the server codebase and this part is returning a definitely wrong url.

I understand that there is a specific issue related to the use of php where tasks are splited between Apache engine and php engine. I am not familiar enough with Apache and even less with php so I am not sure that my suggestions makes sense.

May be simply adding a .well-known html file in the root web tree with appropriate redirection could do the job ? In case you filter any dot-file from being served, may be the .htaccess *updater* could use the php parameter specifying the reverse proxy url to generate appropriate .htaccess rules when checking/updating its content ?

In the meantime, my warning system in case of .htaccess replacement allows me to manually patch again the new version of .htaccess but that is not really satisfying.

Before automating the patch, I would be interested to know if the team would accept to evaluate the opportunity to reliably support reverse proxy which is, at least for me, a no-brainer choice for deployment ?

Many thanks for your support

**Comment by christf** [comment]
I have the same problem. Placing additional rewrite rules specifically to address the .well-known URLs is not a solution:

nextcloud has a config option to override the protocol. If users set that, it should address all aspects of nextcloud, not just the bits that are not implemented via .htaccess. Please re-open.

**Comment by philippelt** [comment]
The problem is still here and this is a BUG because it concerns modifying code that is part of the server code base.

The documentation do not specify as MANDATORY for Nextcloud server to accept incoming requests on http port before redirecting to https and this is the current requirement from this .htaccess.

I have no other solution that patching the .htaccess each time there is a NextCloud update. I also have been obliged to disable security code check as it raises an error with the modified file.

Unfortunately I am not a PHP developper thus I would not try to fix the problem but it should not be so complex because there is a PHP script that build the final version of .htaccess and this script could use config variables to ensure the appropriate scheme is used in redirection.

For the moment, I patch the rewrite rules with :  
```
RewriteRule ^$ %{ENV:REWRITE_SCHEME}://%{SERVER_NAME}/remote.php/webdav/ [L,R=302]
```
```SERVER_NAME``` is a standard variable, I just add ```REWRITE_SCHEME=https``` in the envvar of my running container. 

I hope someone of the project will realize that this is a real issue and take care of it.

**Comment by kesselb** [comment]
> The documentation do not specify as MANDATORY for Nextcloud server to accept incoming requests on http port before redirecting to https and this is the current requirement from this .htaccess.

I'm not aware that HTTP is mandatory. 

> I have no other solution that patching the .htaccess each time there is a NextCloud update. I also have been obliged to disable security code check as it raises an error with the modified file.

You have: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html?highlight=discovery#service-discovery

> Unfortunately, the proposed change failed to solve the problem and I should have noticed that it couldn't work. The link sent back by the app is based on the http scheme and, my platform not being listening on port 80, traefik will never receive the bad url to rewrite it with appropriate path => sync will fail again.

If you configure the redirect, for the service discovery, within your reverse proxy the link is correct. The idea is that your traefik instance responds to `https://domain.com/.well-known/carddav` with `https://domain.com/remote.php/dav`. I don't see why you need a http listener for it? 

> Placing additional rewrite rules specifically to address the .well-known URLs is not a solution: 

Thank you for sharing your opinion with us. 

> Please re-open.

If you insist, I can reopen it. But reopening does not mean that someone will work on it. Or that we accept a pull request that you or someone else is sending us. To bring overwriteprotocol to .htaccess we either require some php code to update the file or some additional environment variables as Philippe suggested. I still think the current solution, to let the reverse proxy do the job, is the best approach here.

**Comment by christf** [comment]
> If you insist, I can reopen it. But reopening does not mean that someone will work on it. Or that we accept a pull request that you or someone else is sending us. To bring overwriteprotocol to .htaccess we either require some php code to update the file or some additional environment variables as Philippe suggested. I still think the current solution, to let the reverse proxy do the job, is the best approach here.

The problem is that the current behavior is inconsistent. There is overwriteprotocol which overwrites the protocol for *some* URIs but not all of them. If rewriting is the solution, then why have the setting at all?

**Comment by kesselb** [comment]
> If rewriting is the solution, then why have the setting at all?

Our recommendation is to set up a redirect, not to rewrite the response. 

If you have a good idea, send us a pull request.

**Comment by christf** [comment]
Thanks. Does that mean you are open to accept pull requests on the matter then?


In this case, please reopen the issue, maybe it'll help attract someone with the right skillset to patch this.

**Comment by szaimen** [comment]
We will not reopen this. Instead feel free to create a feature request and provide up-to-date information. Thanks!
