### ISSUE TITLE
Create button translation breaks after usage

### ISSUE THREAD

**Issue by tuxmaster5000** [nextcloud/server#32836]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After crate an new tag, the translation of the form is broken,
![bild](https://user-images.githubusercontent.com/837503/173232205-5dd00b3f-882f-4ad9-abc8-a7de1ce6b231.png)

### Steps to reproduce

1. open the form to create an new tag
2. fill out the form
3. click on "Erstellen"
4. Now the text of "Erstellen" switch to "Create"

### Expected behavior

That after creating the tag, the button "Erstellen"  don't switch back to English.

### Installation method

Manual installation

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "XXXX.XXXXX"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "23.0.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "maxZipInputSize": 83886080,
        "allowZipDownload": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "log_type": "file",
        "loglevel": "1",
        "logfile": "data\/nextcloud.log",
        "logtimezone": "Europe\/Berlin",
        "log_authfailip": true,
        "theme": "",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "maintenance": false,
        "asset-pipeline.enabled": true,
        "updatechecker": true,
        "htaccess.RewriteBase": "\/",
        "filelocking.enabled": true,
        "mysql.utf8mb4": true,
        "overwrite.cli.url": "https:\/\/XXXX.XXX.XXXX",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "dicomviewer",
            "socialsharing_email"
        ],
        "default_phone_region": "DE",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.15.0
  - admin_audit: 1.13.0
  - bruteforcesettings: 2.4.0
  - calendar: 3.3.1
  - camerarawpreviews: 0.7.15
  - checksum: 1.1.4
  - circles: 23.1.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.1.1
  - contactsinteraction: 1.4.0
  - dav: 1.21.0
  - dicomviewer: 1.2.3
  - drawio: 1.0.2
  - federatedfilesharing: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_retention: 1.12.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_videoplayer: 1.12.0
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - quota_warning: 1.14.0
  - recommendations: 1.2.0
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - socialsharing_email: 2.5.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.1
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - twofactor_totp: 6.3.0
  - twofactor_u2f: 6.3.0
  - updatenotification: 1.13.0
  - viewer: 1.7.0
  - workflowengine: 2.5.0
Disabled:
  - accessibility: 1.2.0
  - dashboard: 7.0.0
  - encryption
  - federation: 1.6.0
  - files_external: 1.7.0
  - files_trashbin: 1.10.1
  - files_versions: 1.0.3
  - firstrunwizard: 1.0
  - support: 1.5.0
  - user_ldap
  - user_status: 1.2.0
  - weather_status: 1.1.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Nothing will logged, when using this function.
```

### Additional info

When editing an existing tag, the translation switch to "Update" instant of "Speichern"

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by tuxmaster5000** [comment]
Using 24.0.8 will result in the same error.
But also editing an existing tag is affected. Here the language of the update button are effected.

**Comment by szaimen** [comment]
Hi, please update to 25.0.7 or better 26.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 26-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by tuxmaster5000** [comment]
The same will happens on 25.0.6 :(

**Comment by joshtrichards** [comment]
Reproduced in 25, but also now fixed in supported versions (>=28).
