### ISSUE TITLE
Implementation of Tag-Search (Gallery View Search?)

### ISSUE THREAD

**Issue by kalckhoff** [nextcloud/server#3283]
## Feature request

**User type**: Logged-in

**User level**: Beginners
### Description

Hi, 

I'm looking for a Tool for our company to organize and sort all of our Pictures and mediafiles. Therefor I was testing the latest version of NextCloud 11, it looks allready quit good, but for our case (and I think for other users as well) it would be fantastic if we could use the Search possibility into the Gallery view. Also it would be helpful to search after tags I setted to our pictures. I know thats two different feartures. 

For example: I have a pictures with yellow sun flowers. I saved the picture with the name flower.jpg and added the tags (sun, flower, yellow, happy) to it. Now I want to search in the Gallery after all our pictures with the tag sun. 

So, you get an idea. It is a little bit like fotolia but for own purpose.

### Benefit / value

Faster, more efficent and more comfortable search possibility.

### Risk / caveats

No risks
### Sponsorship

Maybe a addional Paid Feature like the Outlook integration?
 
**Are you a developer willing to implement this feature?**: yes

**Can you sponsor the development of this feature or do you know someone who can?**: no

**Comment by Bugsbane** [comment]
Yes, I've been looking for similar functionality myself (I would have used the time up reaction, but GitHub doesn't make reactions available on mobile)

**Comment by nickvergessen** [comment]
Please reopen your issue at https://github.com/nextcloud/gallery
