### ISSUE TITLE
[Bug]: Nextcloud 24.0.1 redirects to wrong URL after clicking on 'Install'

### ISSUE THREAD

**Issue by prbt2016** [nextcloud/server#32873]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello,

I was in the process of manual installation of Nextcloud 24.0.1 downloaded from here i.e : 
https://download.nextcloud.com/server/releases/nextcloud-24.0.1.zip
on CentOS Linux release 7.9.2009 (Core) with Apache 2.4, MYSQL 5.7, PHP 7.4.

However after entering the admin and database details script redirects to wrong URL i.e : 

http://{{subfolder}}/index.php/core/apps/recommended instead of  

http://{{DOMAIN.COM}}/{{subfolder}}/index.php/core/apps/recommended

After explicitly providing the correct URL in the browser  i.e 

http://{{DOMAIN.COM}}/{{subfolder}}/index.php/core/apps/recommended

The installation tends to proceed fine further.

As I have tested on three different servers with the same environment. Everywhere I got the same issue.

Is this a known issue ?. Any fix or turnaround for the same ?.

### Steps to reproduce

1. Hit the installation URL in  the browser
2. Enter database and admin details
3. Script redirects to http://{{subfolder}}/index.php/core/apps/recommended instead of  

http://{{DOMAIN.COM}}/{{subfolder}}/index.php/core/apps/recommended

### Expected behavior

Script should redirect to correct apps URL page i.e http://{{DOMAIN.COM}}/{{subfolder}}/index.php/core/apps/recommended.

### Installation method

Manual installation

### Operating system

RHEL/CentOS

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "{{DOMAIN.COM}}"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.1.1",
        "overwrite.cli.url": "https:\/\/{{DOMAIN.COM}}\/{{SUBFOLDER}}",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - bruteforcesettings: 2.4.0
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```

### Nextcloud Logs

```shell
{"reqId":"XwM0C1RotIKJScsKlm4e","level":2,"time":"2022-06-14T06:10:05+00:00","remoteAddr":"{{IP-ADDRESS}","user":"--","app":"no app in context","method":"GET","url":"{{RELATIVE-URL}}/","message":"Could not detect any host in http://{{RELATIVE-URL}}/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0","version":""}
{"reqId":"XwM0C1RotIKJScsKlm4e","level":2,"time":"2022-06-14T06:10:05+00:00","remoteAddr":"{{IP-ADDRESS}","user":"--","app":"no app in context","method":"GET","url":"{{RELATIVE-URL}}/","message":"Could not detect any host in https://{{RELATIVE-URL}}/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0","version":""}
{"reqId":"IpNzK52dDmkMW3Bge6YS","level":2,"time":"2022-06-14T06:12:03+00:00","remoteAddr":"{{IP-ADDRESS}","user":"--","app":"no app in context","method":"POST","url":"{{RELATIVE-URL}}/index.php","message":"Could not detect any host in http://{{RELATIVE-URL}}/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0","version":""}
{"reqId":"IpNzK52dDmkMW3Bge6YS","level":2,"time":"2022-06-14T06:12:03+00:00","remoteAddr":"{{IP-ADDRESS}","user":"--","app":"no app in context","method":"POST","url":"{{RELATIVE-URL}}/index.php","message":"Could not detect any host in https://{{RELATIVE-URL}}/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0","version":""}
```

**Comment by seirdotexe** [comment]
I can confirm that this is still happening as I'm experiencing the same problem. I'm using automatic configuration and upon waiting for the configuration to complete, I get sent to the incorrect url.

**Comment by shoujii** [comment]
Is there any update on this?

It also happens to me on 25.0.2...

**Comment by shoujii** [comment]
Sad that nobody is answering here or in the forums:

https://help.nextcloud.com/t/nextcloud-redirect-after-installation/155577

**Comment by szaimen** [comment]
Hi, please update to 25.0.7 or better 26.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 26-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
