### ISSUE TITLE
Actions in sidebar has weird border

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#3288]
* go to user management
* create a group
* assign a user to this group
* click in the sidebar on the group: a trash icon should appear:

<img width="446" alt="bildschirmfoto 2017-01-26 um 12 54 08" src="https://cloud.githubusercontent.com/assets/245432/22345679/b58f2044-e3c6-11e6-93f6-213afc0f6164.png">

cc @skjnldsv

**Comment by MorrisJobke** [comment]
May be related to https://github.com/nextcloud/calendar/issues/321

**Comment by skjnldsv** [comment]
This is related to a too much global selector used for the blue shadow.
I'm on it. It's also happening on popovermenu in some case.
