### ISSUE TITLE
[Bug]: capabilities contain "user_status" when user is excluded by "limit to groups"

### ISSUE THREAD

**Issue by mahibi** [nextcloud/server#32892]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

when the user status app on server is restricted to only some groups by the "Limit to groups" option, the capabilities for users that are excluded still contains the "user_status" capability.

### Steps to reproduce

1. enable user status app
2. limit to group X
3. check capabilities of a user who should be excluded
4. BUG: user has "user_status" capability

### Expected behavior

user doesn't have "user_status" capability

### List of activated Apps

user status app

### Additional info

found this bug which caused https://github.com/nextcloud/talk-android/issues/2123 on android talk.
(workaround is https://github.com/nextcloud/talk-android/pull/2142)

**Comment by mahibi** [comment]
cc @tobiasKaminsky for android files app

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
