### ISSUE TITLE
No WebDav Error when system is in single user mode

### ISSUE THREAD

**Issue by EasyPeasy1** [nextcloud/server#3289]
![image](https://cloud.githubusercontent.com/assets/24621703/22350216/37bec7b2-e413-11e6-9582-90639a6f7d6a.png)

It shouldn't be normal that this error appears every few seconds when i switch on the single user mode.
Important error messages will get lost in the mass of this error.
Any Workarounds?

ref: https://github.com/nextcloud/server/issues/3153

**Comment by MorrisJobke** [comment]
cc @LukasReschke @nickvergessen @icewind1991 We still have the single user mode? 😕

**Comment by nickvergessen** [comment]
I'm fine with killing it as well...

**Comment by MorrisJobke** [comment]
Fixed with #3605
