### ISSUE TITLE
Within Files details, posting a comment raises an error and page needs to be reloaded to display the new comment

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/server#32911]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Within Files details, in the comment tab, posting a comment raises an error and page needs to be reloaded to diplay the sent comment.
See details below.

### Steps to reproduce

1. In NC Files, open the details panel, go to the comment tab.
2. Write a comment, post it.
3. The waiting symbol (circle) will show up
4. After a while, an error message pops up, and the comment field goes back to edit mode
5. Refreshing the page shows that the comment has been sent.

![image](https://user-images.githubusercontent.com/87175513/174263553-8f065e95-3886-43e9-b760-1bdb2534e9bd.png)
![image](https://user-images.githubusercontent.com/87175513/174263580-3bcd8e1a-7d69-4300-927c-fc2656182642.png)
![image](https://user-images.githubusercontent.com/87175513/174263812-62ef48c4-30e3-47aa-9189-51d38d8f26a4.png)

### Expected behavior

1. Write a comment
2. Post it.
3. The comments displays as posted without raising an error neither having to refresh the page.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
c.nc.com
```

### List of activated Apps

```shell
c.nc.com
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by maximelehericy** [comment]
Hi @szaimen happened on c.nc.c last week, so on 25.0.3 :)

**Comment by joshtrichards** [comment]
I can't reproduce this (at least in v25.0.8). Are you still able to reproduce this today @maximelehericy?

If someone encounters this behavior again:

- try to grab their browser console output (including the Network tab) if there's anything interesting looking
- the server-side log for the related transaction (presumably a stack trace if it's not just an error on the front-end code in the browser)

**Comment by maximelehericy** [comment]
cannot reproduce in "27.0.2", closing :)
