### ISSUE TITLE
[Feature request]: Select View Option:  Hide / Unhide of left-side panel in NC

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#3291]
Hi to All,

It could be very advantageous to introduce  / implement  a GENERAL Option as a  toggle switch to hide / unhide the left side panel for EVERY app to maximize the screen usage - especially on small (e.g. mobile) screens.

regards, hitam4450

**Comment by MorrisJobke** [comment]
On mobile screens the left menu is hidden by default.

cc @jancborchardt

**Comment by nickvergessen** [comment]
Duplicate of https://github.com/nextcloud/server/issues/3049

**Comment by profihost** [comment]
+1 for desktop
