### ISSUE TITLE
Files app: Action buttons instead of Action menu items

### ISSUE THREAD

**Issue by MacsKavana** [nextcloud/server#32928]
**Is your feature request related to a problem? Please describe.**
No problems at all, jut a feature request.

**Describe the solution you'd like**

In Files app it would be nice to have action buttons for the selected items instead of the "...Actions" menu.

The icons should represent the "..Actions" menu items, like 'Download', 'Delete', 'Move/Copy', 'Tags'.

Just like in desktop file managers.

Although this sounds funny, this can significantly speed up work.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by skjnldsv** [comment]
Hey!

I don't fully understand what you mean, you would like the actions within the `...` menu to be put outside of it with icons only?

**Comment by Gwindalmir** [comment]
> Hey!
> 
> I don't fully understand what you mean, you would like the actions within the `...` menu to be put outside of it with icons only?

I came here to say the same thing as OP. Yes, what you said, though it doesn't have to be icons only IMO.

Here's an example from Google Drive:
![image](https://github.com/nextcloud/server/assets/1127170/14907085-2670-4dd2-86ad-535fa2dc655e)

Common actions are in the main toolbar, with the "..." action menu containing those, and less common actions.

Given Nextcloud only really has a handful of actions, most of them could be added to the main bar, like this:
![image](https://github.com/nextcloud/server/assets/1127170/7e4e7706-d285-45ef-b06a-1caafc4eff1e)

Or even collapsed down on smaller screens:
![image](https://github.com/nextcloud/server/assets/1127170/03651baa-032f-4de9-b10d-1241be1d7541)

**Comment by skjnldsv** [comment]
Done for 28
