### ISSUE TITLE
[Bug]: Error while Updating Nextcloud to a newer Version. Duplicate entry XXX for key mounts_user_root_index.

### ISSUE THREAD

**Issue by wolfswolke** [nextcloud/server#32926]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I just upgraded my nextcloud Docker to 24.0.1 and i am getting this error: Exception: Database error when running migration 24000Date20220202150027 for app core An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Ripper-231765' for key 'mounts_user_root_index'

### Steps to reproduce

1. Go to Settings.
2. Click online Updater.
3. After the first window is done continue to the next.
4. Start Upgrade.

### Expected behavior

It to update my nextcloud and not give me a error.

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
root@cb43ee9c4796:/config/www/nextcloud# sudo -u abc php occ config:list system
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "debug": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "194.208.140.70",
            "192.168.1.*",
            "192.168.1.*",
            "cloud.zkwolf.stream"
        ],
        "dbtype": "mysql",
        "version": "23.0.5.1",
        "overwrite.cli.url": "https:\/\/192.168.178.101",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "pipe",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtptimeout": "30",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
root@cb43ee9c4796:/config/www/nextcloud#
```

### List of activated Apps

```shell
root@cb43ee9c4796:/config/www/nextcloud# sudo -u abc php occ app:list
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - accessibility: 1.9.0
  - activity: 2.15.0
  - bruteforcesettings: 2.4.0
  - calendar: 3.3.2
  - circles: 23.1.1
  - cloud_federation_api: 1.6.0
  - comments: 1.13.0
  - contacts: 4.1.1
  - contactsinteraction: 1.4.0
  - dashboard: 7.3.0
  - dav: 1.21.0
  - federatedfilesharing: 1.13.0
  - federation: 1.13.0
  - files: 1.18.0
  - files_pdfviewer: 2.4.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.15.0
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - geoblocker: 0.5.5
  - logreader: 2.8.0
  - lookup_server_connector: 1.11.0
  - mail: 1.13.4
  - nextcloud_announcements: 1.12.0
  - notifications: 2.11.1
  - oauth2: 1.11.0
  - password_policy: 1.13.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - provisioning_api: 1.13.0
  - recommendations: 1.2.0
  - richdocuments: 5.0.5
  - serverinfo: 1.13.0
  - settings: 1.5.0
  - sharebymail: 1.13.0
  - spreed: 13.0.6
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.13.0
  - text: 3.4.1
  - theming: 1.14.0
  - twofactor_backupcodes: 1.12.0
  - updatenotification: 1.13.0
  - user_status: 1.3.1
  - viewer: 1.7.0
  - weather_status: 1.3.0
  - workflowengine: 2.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
root@cb43ee9c4796:/config/www/nextcloud#
```

### Nextcloud Signing status

```shell
The Domain forwards me to the Upgrade screen again.
```

### Nextcloud Logs

```shell
https://zkwolf.stream/Files/log.txt
```

### Additional info

Browser: Google Chrome/Firefox.
How i updated the first time: Browser.
I Tried also to upgrade in the Console but got the same error:
   root@cb43ee9c4796:/config/www/nextcloud# occ upgrade
   Nextcloud or one of the apps require upgrade - only a limited number of commands are available
   You may use your browser or the occ upgrade command to do the upgrade
   Setting log level to debug
   Turned on maintenance mode
   Updating database schema
   Exception: Database error when running migration 24000Date20220202150027 for app core
   An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'Ripper-231765' for key 'mounts_user_root_index'
   Update failed
   Maintenance mode is kept active
   Resetting log level
   root@cb43ee9c4796:/config/www/nextcloud#

**Comment by wolfswolke** [comment]
Finally "solved" it after like 2 weeks now...
I went into my sql -> oc_mounts and deleted every duplicate user. 
After that the Upgrade finished but now I have some users 4 times in here???
Is this wanted behavior or not?
![image](https://user-images.githubusercontent.com/34097612/174441477-6d0602ef-08a7-47fc-97a3-a2ec87ac36c9.png)

**Comment by wolfswolke** [comment]
I pressed the wrong button... Github is kinda confussing some times xD

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
