### ISSUE TITLE
Extract navigation.name from info.xml for translation

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#3292]
Follow up from #2822

**Comment by ChristophWurst** [comment]
From https://github.com/nextcloud/server/pull/2822#discussion_r98099639 I take that @MorrisJobke has maybe been working on this. If so, what's the progress?

Is there anything I could help with? Where can I find the code that extracts the other translations?

**Comment by MorrisJobke** [comment]
> From #2822 (comment) I take that @MorrisJobke has maybe been working on this. If so, what's the progress?

Sadly not.



> Is there anything I could help with? Where can I find the code that extracts the other translations?

That is the code: https://github.com/nextcloud/server/blob/master/l10n/l10n.pl (yes Perl -.-)

This is how it is called: https://github.com/nextcloud/docker-ci/blob/9c1120ac1582f0df918ea659e35eaaab4af0ad0c/translations/handleTranslations.sh#L22

**Comment by MorrisJobke** [comment]
I also added this to all the app scripts. Let's see if it works.

**Comment by MorrisJobke** [comment]
I just trigger a transifex sync for all apps. For activity the tests worked fine 👍
