### ISSUE TITLE
The external shares' "Share label" feature is sadly underused (your opinions are important)

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/server#32923]
Hi,

When sharing anonymously (public link) or non-anonymously (e-mail), there is a "Share label" field. 

**1. When there is a label filled in, it is a pity that it is not displayed (when it is clicked):**

- in the activities
- in push notifications
- in email notifications
Indeed, just to give a simple example, when several public shares are created (and used) and we receive notifications (for example by e-mail), we just know that a public link has been used, but we have no idea which link it is. It would be a real UX improvement if the label was displayed in the notification.

**2. I wonder about one point:** 

If a file or folder is shared with another user or user group or users and/or user groups within a circle ... as well as with outsiders (anonymous and non-anonymous shares via an email address), wouldn't it be interesting if the sharing label was visible to the other users of the instance involved in that same share?

**3. Big problem of translation in French (and maybe in other languages), making this feature incomprehensible:** 

The French translation "Partager étiquette" is understood in french as "Share the label", which makes absolutely no sense in relation to the context of use of this functionality. It is really important that this translation is changed so that French users can understand and use this feature. See my suggestion in Transiflex. It should be checked if the translation is also bad in other commonly spoken languages (that I don't speak, like Spanish or German).

Thanks for reading me.
Jérôme

**Comment by PVince81** [comment]
@nextcloud/designers

**Comment by iljur** [comment]
It would also just make sense if the share label could be visible at the top of the shared page as a headline. 

And also would make sense to really _label_ the share in the share settings of a folder. If you have several shares for one folder it gets confusing quite quickly if there is only the standard label "Link teilen" for every share/link. 

(@Jerome-Herbinet Don't know if this was already your second point...)

**Comment by Jerome-Herbinet** [comment]
> It would also just make sense if the share label could be visible at the top of the shared page as a headline.
> 
> And also would make sense to really _label_ the share in the share settings of a folder. If you have several shares for one folder it gets confusing quite quickly if there is only the standard label "Link teilen" for every share/link.
> 
> (@Jerome-Herbinet Don't know if this was already your second point...)

Not sure @iljur IMO ; I just said in another issue about circles that the share recipients shouldn't see the name of the circle they are member of in the e-mail share notification ... You invite you to read it to understand why 😉
[ Confidentiality and wording issues in sharing notification e-mails (when sharing with a circle) #1239 ](https://github.com/nextcloud/circles/issues/1239)

**Comment by jancborchardt** [comment]
Is this still an issue with the redesigned sharing, or did the requirements change? @Jerome-Herbinet do you maybe have a mockup of how it could work different from the current design?

**Comment by Jerome-Herbinet** [comment]
@jancborchardt, here's a starting point that can be applied to push and e-mail notifications. 
It's nothing more, at least initially compared to what I'd imagined, than the addition of the wording (in bold for good visibility, or even in quotation marks), before “public link”. Please note that the label must not appear on the recipients of the shares, but only on the senders (push and email activity notifications, and email activity notification).
This concerns all the following activities relating to external shares (e-mail and public links): share creation, share deletion, share expiration, downloading of files and/or folders forming part of the share.

![2024-05-23_16-43](https://github.com/nextcloud/server/assets/33763786/5364853d-726e-4587-9899-1990afe3a12d)
![2024-05-23_16-45](https://github.com/nextcloud/server/assets/33763786/7b3e3539-e1e8-4e08-bd56-af22a1226143)
![2024-05-23_16-42](https://github.com/nextcloud/server/assets/33763786/bb1551ec-d3f0-4332-bd0f-e8b7dd126816)

**Comment by skjnldsv** [comment]
Since 30, we changed that a bit.
Share mails and link shares have more informations on emails, activity and on the public rendering.
Including the share label :)

**Comment by Jerome-Herbinet** [comment]
> Since 30, we changed that a bit. Share mails and link shares have more informations on emails, activity and on the public rendering. Including the share label :)

@skjnldsv Are you sure that share labels are included in notifications when (for example) a file is downloaded via a public share link with a share label? On a NC 30 test instance (with the right setting checked in the personal notification settings), I still haven't any share label included in the notification message (not in e-mail notifications, push notifications or activity feeds)
