### ISSUE TITLE
[Bug]: Upload progress bar disappears with upload in progress

### ISSUE THREAD

**Issue by SMH17** [nextcloud/server#32935]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The upload progress in web interface disappears despite the upload is still in progress if during the upload you perform deletions. This issue was present also in older versions and it remained in latest release and it can be reproduced with different host configurations. 

### Steps to reproduce

1. Upload a file using the web interface drag and drop
2. Delete a folder while the upload is still in progress

### Expected behavior

The progress bar should remain till the upload completion regardless user perform other operations.

### Installation method

Manual installation

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
No app added. All the apps are the default included with Nextcloud.
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
