### ISSUE TITLE
[Bug]: security issue allowing to bypass read-only permission when accessing a shared folder through webDAV

### ISSUE THREAD

**Issue by kirmaha** [nextcloud/server#32937]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

A user has access to a shared folder, with read-only permission. If that user access that folder through WebDAV (signing in with his own login and password), he may be able to modify or delete whatever is in that folder.

### Steps to reproduce

Two nextcloud users : "Jan-OWNER" and "Michael".
A folder containing Joplin notes : "Notes (Joplin)"

1. Jan-OWNER fills in the settings of Joplin's Android app to access "Notes (Joplin)" through webDAV on her phone :
- login "Jan-OWNER" + her own password
- webdav url : https://serveurdomain.be/remote.php/dav/files/Jan-OWNER/Notes%20(Joplin)/

App syncs the data as it should, without any error message.

2. Jan-OWNER shares the "Notes (Joplin)" folder with Michael.
She disabled every permission in the sharing properties, which makes it read-only to Michael.
Michael access the shared folder through Nextcloud web interface : he confirms that the folder is read-only.

3. Michael fills in the settings of Joplin's Android app to access "Notes (Joplin)" through webDAV on his phone :
- login "Michael" + his own password
- webdav url : https://serveurdomain.be/remote.php/dav/files/Michael/Notes%20(Joplin)/

The app returns an error (not finding the folder).

4. Michael changes the app's settings to :
- login "Michael" + his own password
- webdav url : https://serveurdomain.be/remote.php/dav/files/Jan-OWNER/Notes%20(Joplin)/

App syncs the data as it should, without any error message.

5. On Joplin app on his phone, Michael deletes Note1, changes the content of Note2, and then sync.

6. On Joplin app on her phone, Jan-OWNER syncs data. Note1 disappears and Note2 has been modified.

### Expected behavior

On step 5, Michael should not be able to spread Note1 deletion and Note2 modifications to the Nextcloud server (whether he gets an error or not).

As a consequence, on step 6, Jan-OWNER should not see any change in her notebook on Joplin app.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Bookmarks 10.3.1
Calendar 3.3.1
Collectives 1.1.0
Deck 1.6.1
Mail 1.13.0
News 18.0.1

Activity 2.15.0
AppOrder 0.15.0
Breeze Dark 23.2.2
Collaborative tags 1.13.0
Comments 1.13.0
Contacts 4.1.1
Cookbook 0.9.12
Custom CSS 1.11.0
Deleted files 1.13.0
File sharing 1.15.0
Forms 2.5.1
Full text search 23.0.0
Full text search - Files 23.0.1
GPodder Sync 3.4.0
Jitsi Integration 0.15.0
Keeweb 0.6.9
Markdown Editor 2.3.6
Nextcloud Office 5.0.5
Notes 4.3.1
Notifications 2.11.1
Password policy 1.13.0
PDF viewer 2.4.0
Photos 1.5.0
Ransomware protection 1.13.0
Splash 1.2.5
Talk 13.0.6
Text 3.4.0
Theming 1.14.0
Versions 1.16.0
Video player 1.12.0
Welcome 1.0.1
```

### Nextcloud Signing status

```shell
Integrity checker has been disabled. Integrity cannot be verified.
```

### Additional info

Using Nextcloud Hub II (23.0.0)

Sorry I can't add much specifications as I use a hosting service and I don't have the required access...

**Comment by hul51u** [comment]
I was not able to reproduce this with my NC 23.0.5.1 instance and windows webDAV.

**Comment by miaulalala** [comment]
Are you able to ask your hosting service for logs at all? Would be interesting to see what API the Joplin app uses and what types of requests.

**Comment by PVince81** [comment]
my local test case:

1. setup 23.0.0
2. create two users "alice" and "bob"
3. login as "alice"
4. create a folder "test"
5. share "test" with "bob"
6. remove all share permissions to make it read-only
7. on the CLI, try to PUT a file there:
```
% curl -u bob:test12345678 -X PUT -H OCS-Apirequest:true "https://vvortex.local/remote.php/dav/files/bob/test/test.txt" -d "data to put"
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>
  <s:message/>
</d:error>
```
8. try to PUT the file using Alice's Webdav path:
```
% curl -u bob:test12345678 -X PUT -H OCS-Apirequest:true "https://vvortex.local/remote.php/dav/files/alice/test/test.txt" -d "data to put"
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File not found: test in 'alice'</s:message>
</d:error>
```

Also I tried a PROPFIND on "alice" and it shows an empty folder, and a PUT there also returns "forbidden".

So not sure what the Joplin app would be doing differently.

**Comment by PVince81** [comment]
also did some tests with Nextcloud 24.0.2 RC1 and got similar results, was not able to overwrite the file using the other user's Webdav path

also tried with COPY and MOVE and they were also blocked

so not sure if there's something specific to this hoster or a third party app that is interfering with Webdav's proper functioning

**Comment by PVince81** [comment]
I've now tested with the Joplin app with Nextcloud 23.0.0 as well and with the user bob I can use the Webdav URL to configure it, the app accepts it.
but then it fails because it **cannot write its lock file**
Also it did not sync down the notes from "Alice", so I cannot read them.

In-between tests I cleared the app's data to make sure there were not remaining settings or data.

then I changed the Webdav URL from Bob's URL to Alice's and it fails with "Webdav directory not found".

@kirmaha here I wonder if you haven't mixed up the steps and perhaps it gave you inaccurate results.

In general, from what I saw the Joplin app is creating a lot of metadata folders, info.json, etc. I don't think it's suitable to share a notes folder read-only as the reader will not be able to apply locks (the error I got above) because it cannot write to the target Webdav, so don't use it that way.

@kirmaha unless you can provide access logs and nextcloud.log from the events which could confirm either a mix up, there isn't much we can do as no one was able to reproduce the issue.

If you do have logs, feel free to reopen.

**Comment by PVince81** [comment]
@kirmaha PS: in general if possible your hoster should upgrade to the latest version as 23.0.0 is already old

**Comment by kirmaha** [comment]
@PVince81 : Thank you so much for your tests and answers.

I will have some time to test it again in a couple of days. I will go through the steps after erasing app's data properly and with new users. If I can reproduce the bug on a clean setup, I will do my best to get access logs and nextcloud.log.

In some way, I'm already reassured that no one seems able to reproduce this.

**Comment by kirmaha** [comment]
Hello again !
It took me some time but I did the tests.

1. In nextcloud (through browser) :
- create 2 regular users with two different passwords : joplinmaster & joplintest
- identify as joplinmaster and create a « Joplin » folder in the root of that user

2. Open Joplin app on a Mac OS X session where Joplin was never opened :
- manually set up sync with joplinmaster username and password, and this WebDAV URL : https://serveurdomain.be/remote.php/dav/files/joplinmaster/Joplin/
- create a new notebook « test » add a new note « test » with some text in it (there are already 5 local welcoming notes as in any new Joplin set up)
- sync

3. In Nextcloud (through browser), as joplinmaster user : check that files have been created in the folder created in step 1.

4. On an Android phone where Joplin app has never been installed, install the app.

5. FIRST TEST : folder is host by joplinmaster user and no sharing has been set.
In Joplin app on the Android phone, set up a Nextcloud sync using joplintest username and password, but this WebDAV URL : https://serveurdomain.be/remote.php/dav/files/joplinmaster/Joplin/ (username and URL are intentionnally not matching). Check the sync by hitting « Check synchronization configuration » button . Result : « WebDAV directory not found:{entered URL} ». 

6. In Nextcloud (through browser), as joplinmaster user : share « Joplin » folder with joplintest user, and uncheck the four first options to prevent modification, creation, deletion and re-sharing. As joplintest user, ensure the « Joplin » shared folder is at the user’s root folder level (if not, move it there). 

7. SECOND TEST : set up sync in Android Joplin app, with the same user/password/URL combination. Check the sync set up with the button. Result : « WebDAV directory not found:{entered URL} ».

8. THIRD TEST : set up sync in Android Joplin app, with the same user/password combination, but with this URL : [https://serveurdomain.be/remote.php/dav/files/joplintest/Joplin/](https://serveurdomain.be/remote.php/dav/files/joplinmaster/Joplin/) . Check the sync set up with the button. Result : « Success! Synchronization configuration appears to be correct. ». Then sync, and an error appears (see printscreen below). You can ensure that no sync happened :
- the new « test » notebook and the related « test » note do not show
- modify one of the Welcome notes on Android app and sync, then check if it changed for joplinmasterby syncing on Mac OS X app (it won’t have)
![Capture d’écran du 2022-07-10 18-20-26](https://user-images.githubusercontent.com/93599009/178154542-de87b1b7-4aa3-497c-a2a4-1895edbdb9d8.png)

9. Set up sync in Android Joplin app using joplinmaster username and password, and this WebDAV URL : https://serveurdomain.be/remote.php/dav/files/joplinmaster/Joplin/. Check sync (which will work) and then sync. This should sync, as those are the same settings than on Mac OS X Joplin app… but I ended up with another error (see printcreen below).
![Capture d’écran du 2022-07-10 18-33-44](https://user-images.githubusercontent.com/93599009/178154550-34c6626e-c59d-448b-9834-3ce636c180ea.png)

As this last step makes absolutely no sense, I assume there is indeed a cache issue. I uninstalled/reinstalled Joplin on Android, and then erased the app’s datas and cache through Android main settings. Then restarted it and went through step 9 again : sync did work perfectly, as expected, without any error message.

10. To test @PVince81's hypothesis, I changed the user name and password to joplintest user, keeping the joplinmaster’s WebDAV URL. I saved sync configuration without using the checktool. Guess what : I could indeed edit notes and sync them. So I suppose that @PVince81‘s hypothesis is the right one : the app is probably still using joplinmaster access even if the settings have changed.

Tapping the « Check synchronization configuration » button ends up with « Success! Synchronization configuration appears to be correct. »

11. Just to make sure, I wiped out app’s data and cache, and reinstalled it again, in order to check step 7 from a clean Android set up : step ends up with the same wrong WebDAV directory error. We can conclude that the app is not able to reach the directory.

Conclusion :
- Joplin’s app can reach the read-only folder but will refuse to sync it (which is ok, as it is not supposed to work that way)
- Joplin’s app can’t bypass read-only restriction by accessing the folder through another user’s WebDAV path
- Joplin’s may look like it is using the current configuration when it is in fact using a previous configuration, ignoring changes (probably because the changes were not functional)

I won’t go any further since I think I reached the limit of my abilities here, also because I see not much interest digging further. No need for logs I guess 

Thanks for your support !
K.
