### ISSUE TITLE
[Bug]: issues when using POSIX ACL for data directory

### ISSUE THREAD

**Issue by ZhaominW** [nextcloud/server#32934]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When the file system uses POSIX ACL instead of CHMOD:
When accessing nextcloud local storage, 
it prompts `You don't have permission to upload or create files here`.

### Steps to reproduce

1.Change the data directory of nextcloud to ACL mode and grant the relevant users read and write permissions, for example, like this:
![image](https://user-images.githubusercontent.com/100418064/174479671-1285271a-740c-4765-900d-692f198112c8.png)

2.In my case, I granted the `smb usergroup (gid1000)` and the `user www(php process)`, write delete and append permissions. 
All the rest of the users are only allowed to traverse folders and not to execute files.
And owner is changed to root and wheel.
Note: ACL permissions need to be applied recursively.

3.Edit config.php
   'check_data_directory_permissions' => false
   'filesystem_check_changes' => 1,

4.In order to refresh the cache, you should casually `touch` it via cli.
I refreshed testuser's home directory here.
touch /mnt/userdata/nextcloud/testuser/123.txt

5.Login to testuser's homepage and you will get an error message.
![image](https://user-images.githubusercontent.com/100418064/174480414-181939eb-1f63-415e-b2e0-4559a8c6b29c.png)

6.In theory, nextcloud has full permission to read, write, delete and append files, but NextCloud reports an error.

7.Looking through the source code, I found out that nextcloud uses the built-in php function stat to get the file's mode, which is used to determine if the file has permission to be modified. 
`/lib/private/Files/Storage/Local.php public function getMetaData($path) {}`

This determination method is simple and crude, but very outdated.

I temporarily tampered with this function and then everything worked fine.
![image](https://user-images.githubusercontent.com/100418064/174480966-ff720443-2e70-4c0e-b866-521990a2bbb8.png)

### Expected behavior

On modern server systems, using ACL is obviously a better choice.

After briefly reading the source code, I think it is not a lot of work to change to support POSIX ACLs.

Code no more than 20 lines~

### Installation method

Other

### Operating system

Other

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
nothing
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
