### ISSUE TITLE
[Bug]: Deutsch (Persönlich Du)

### ISSUE THREAD

**Issue by snetat** [nextcloud/server#32951]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When creating a new document in files, instead of new text document (.md) the following is displayed.

Benötigt keine Übersetzung. Für iOS wird nur die formelle Übersetzung verwendet (de_DE)

this happens when you set the language to "Deutsch (Persönlich Du)" in your personal settings.

![Screenshot from 2022-06-21 10-40-03](https://user-images.githubusercontent.com/5556794/174759804-7087ff95-da5e-476e-9509-653470052774.png)

this error occurs after updates to 23.0.6 and 24.0.2

### Steps to reproduce

.

### Expected behavior

.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other

### Configuration report

```shell
.
```

### List of activated Apps

```shell
.
```

### Nextcloud Signing status

```shell
.
```

### Nextcloud Logs

```shell
.
```

### Additional info

.

**Comment by kesselb** [comment]
cc @rakekniven
