### ISSUE TITLE
Show latest user Activity not just last login

### ISSUE THREAD

**Issue by xbluemonkx** [nextcloud/server#32953]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
The user overview shows the last login of a user. A lot of our users are working very active on mobile devices (Apps not Browser). It looks like this is not counted as "login". Therefore some users have a last login value that is a few days or even weeks ago, while they are using nextcloud apps on a daily basis.

**Describe the solution you'd like**
I would like to see a last activity column in the user overview. - Hope some people can help to define what should considered as "active". (e.g. reading a message / sending a message / opening a file / uploading a file)

**Describe alternatives you've considered**
none

**Additional context**
On the long term it would be nice to get even more infos like what device (apple / android) are they working on. Which app version. Which desktop client version. - But this might conflict with some GDPR rules and is more a long term vision and not part of this Feature request.

**Comment by Noodlesalat** [comment]
In my opinion, the "last login" should always reflect the timestamp of a user's last interaction with the cloud. Therefore, no further column or similar should be added here. I will prepare a corresponding fix that ensures that the last_login timestamp is also updated for token-based logins (app, desktop client, ...).
