### ISSUE TITLE
Error Message if uploading files

### ISSUE THREAD

**Issue by CordlessWool** [nextcloud/server#3296]
### Steps to reproduce
1. updoad files via android app or web interface
2. error message appear that there was an error while uploading 
3. reload the page shows that the file was uploaded correct

### Expected behaviour
There should no error message and the new file should shown without reload

### Actual behaviour
file is not directly shown after upload, only after reloading page and error message is confussing

### Server configuration
Docker container with version 11.0.1 (happens after updating from 10.0.1 to 10.0.3 and then to 11.0.1)

**Web server:**
docker fpm

**Database:**
myslq 5.7

**PHP version:**
5.6

**Nextcloud version:** (see Nextcloud admin page)
11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
from 10.0.1 over 10.0.3, I only  prove after updating to 10.0.3 if the site is loaded and data are already there. 

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 

-- I deleted around 100 files, but this last 4 are not deletable. If I try to delete them, the files directly appear again.

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- core/l10n/sw_KE.json
		- core/l10n/am_ET.js
		- lib/l10n/jv.json
		- lib/l10n/bn_IN.js

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [core/l10n/sw_KE.json] => Array
                        (
                            [expected] => 
                            [current] => fef97ea6864590db2ff15740c8dd50ca664ad0d67cea78705b6fb54cea878210bf340b40391a17e73a8cfb68a1621683bc984113e3cedf572671e6feec3dee9a
                        )

                    [core/l10n/am_ET.js] => Array
                        (
                            [expected] => 
                            [current] => 397528132f9cd976490c1b5248ed5f68709e9ba0e8d26405850b6cde3003f960a1172ce03a3a6fe3509df519c4b4d6739595b86a3d8eb874492060464719f5e4
                        )

                    [lib/l10n/jv.json] => Array
                        (
                            [expected] => 
                            [current] => 544ce328be16f045d9cf108d6b674304ababf802c0fa7687f2db9bc92ad13d80c5d2607bf80695a55cba9e16a42d9e1ba86eb69c01a85170d38d648d3b90d9e3
                        )

                    [lib/l10n/bn_IN.js] => Array
                        (
                            [expected] => 
                            [current] => 06580546e065d2b4dc0239139757c8b2555a4d4ba91ae37da57375d92bd26ba7722e1d4ac94e64519b9c5021e13458daf19114e91a635218f7e28d25410c2442
                        )

                )

        )

)


</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>


**Are you using encryption:** yes




### Client configuration
**Browser: firefox

**Operating system:**
desktop: linux
mobile: android

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>
```
rror	PHP	inet_ntop(): Invalid in_addr value at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#121	2017-01-27T15:18:21+0100
Error	PHP	inet_pton(): Unrecognized address at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#113	2017-01-27T15:18:21+0100
Error	PHP	inet_ntop(): Invalid in_addr value at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#121	2017-01-27T15:18:20+0100
Error	PHP	inet_pton(): Unrecognized address at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#113	2017-01-27T15:18:20+0100
Error	PHP	inet_ntop(): Invalid in_addr value at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#121	2017-01-27T15:18:18+0100
Error	PHP	inet_pton(): Unrecognized address at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#113	2017-01-27T15:18:18+0100
Error	PHP	inet_ntop(): Invalid in_addr value at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#121	2017-01-27T15:18:18+0100
Error	PHP	inet_pton(): Unrecognized address at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#113	2017-01-27T15:18:18+0100
Error	PHP	inet_ntop(): Invalid in_addr value at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#121	2017-01-27T15:18:17+0100
Error	PHP	inet_pton(): Unrecognized address at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#113	2017-01-27T15:18:17+0100
Error	PHP	inet_ntop(): Invalid in_addr value at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#121	2017-01-27T15:18:17+0100
Error	PHP	inet_pton(): Unrecognized address at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#113	2017-01-27T15:18:17+0100
Error	PHP	inet_ntop(): Invalid in_addr value at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#121	2017-01-27T15:18:17+0100
Error	PHP	inet_pton(): Unrecognized address at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#113	2017-01-27T15:18:17+0100
Error	PHP	inet_ntop(): Invalid in_addr value at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#121	2017-01-27T15:16:15+0100
Error	PHP	inet_pton(): Unrecognized address at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#113	2017-01-27T15:16:15+0100
Error	PHP	inet_ntop(): Invalid in_addr value at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#121	2017-01-27T15:16:15+0100
Error	PHP	inet_pton(): Unrecognized address at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#113	2017-01-27T15:16:15+0100
Error	core	Exception while scanning storage "shared::564ea013c62e0806c046bf5f12776c2b": Sabre\HTTP\ClientException: Failed to connect to localhost port 32769: Connection refused	2017-01-27T15:15:31+0100
Error	core	Exception while scanning storage "shared::be86b7b33d16ad0b0eed58527dbbfdb6": Sabre\HTTP\ClientException: Failed to connect to localhost port 32769: Connection refused	2017-01-27T15:15:31+0100
Error	PHP	Call to undefined function OCA\Nextant\Service\msg_get_queue() at /var/www/html/apps/nextant/lib/Service/QueueService.php#72	2017-01-27T15:14:58+0100
Error	core	Exception while scanning storage "shared::564ea013c62e0806c046bf5f12776c2b": Sabre\HTTP\ClientException: Failed to connect to localhost port 32769: Connection refused	2017-01-27T15:14:14+0100
Error	core	Exception while scanning storage "shared::be86b7b33d16ad0b0eed58527dbbfdb6": Sabre\HTTP\ClientException: Failed to connect to localhost port 32769: Connection refused	2017-01-27T15:14:14+0100
Error	PHP	inet_ntop(): Invalid in_addr value at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#121	2017-01-27T15:14:01+0100
Error	PHP	inet_pton(): Unrecognized address at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#113	2017-01-27T15:14:01+0100
Error	PHP	inet_ntop(): Invalid in_addr value at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#121	2017-01-27T15:14:01+0100
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by CordlessWool** [comment]
After Upload I am also not able to delete uploaded files (tested to delete via android app, browser/firefox and webdav)

**Comment by nickvergessen** [comment]
Seems like your Nextant is missconfigured.

**Comment by CordlessWool** [comment]
Yes, now I have config nextant, but I am already not able to delete Folders. I can delete files but not folders, also if they are empty

**Comment by nickvergessen** [comment]
Any message in the log file when you try to delete a folder?

**Comment by CordlessWool** [comment]
there are many, I do not know which of theme is the correct one. Admin User has no problem with deleting a folder.


inet_ntop(): Invalid in_addr value at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#121	2017-02-03T20:10:25+0100
Error	inet_pton(): Unrecognized address at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#113	2017-02-03T20:10:25+0100
Error	Exception while scanning storage "shared::564ea013c62e0806c046bf5f12776c2b": Sabre\HTTP\ClientException: Failed to connect to localhost port 32769: Connection refused	2017-02-03T20:09:59+0100
Error	Exception while scanning storage "shared::be86b7b33d16ad0b0eed58527dbbfdb6": Sabre\HTTP\ClientException: Failed to connect to localhost port 32769: Connection refused	2017-02-03T20:09:59+0100
Error	stream_get_contents() expects parameter 2 to be long, string given at /var/www/html/3rdparty/sabre/http/lib/Message.php#81	2017-02-03T20:09:42+0100
Error	inet_ntop(): Invalid in_addr value at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#121	2017-02-03T20:09:38+0100
Error	inet_pton(): Unrecognized address at /var/www/html/lib/private/Security/Bruteforce/Throttler.php#113	2017-02-03T20:09:38+0100
Error	Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0	2017-02-03T20:09:34+0100
Error	Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0	2017-02-03T20:09:33+0100
Error	Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0	2017-02-03T20:09:00+0100

**Comment by CordlessWool** [comment]
Now I listen directly to the docker output stream and getting following error messages when I try to remove the folder.

WARNING: [pool www] child 78 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 32 bytes) in /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 104"


also after I increase the memory limit to 1024

[04-Feb-2017 01:04:40] WARNING: [pool www] child 8 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 32 bytes) in /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php on line 104"
172.10.11.33 -  04/Feb/2017:01:04:34 +0000 "DELETE /remote.php" 500

**Comment by nickvergessen** [comment]
Please report your issue to https://github.com/nextcloud/nextant/

**Comment by CordlessWool** [comment]
It is no problem of nextant, because I already deinstall it.

**Comment by CordlessWool** [comment]
if i run http://example.com/index.php/settings/integrity/failed
there are no errors anymore, i got deleted the 4 files

**Comment by CordlessWool** [comment]
I do some more test, I create a new User and tested if it can delete folders, and it is possible to delete existing folders. Are there some privilege settings in the database that maybe not changed correct while the upgrade process?

**Comment by CordlessWool** [comment]
I solved it, by giving php 8 gb of ram
