### ISSUE TITLE
[Bug]: The name of the property transfer folder is always written in English while my user is in French

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/server#32978]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The wording of the property transfer file is in English (probably in all languages, starting with French)

When transferring ownership of a file, the transfer file received by the new owner is named as follows (example): 
transferred from John Doe on 2022-06-22 09-05-02

The problem is that this naming is identical in French.

When I search the translation files in the "/l10n" folders, it looks like no translation exists. Maybe the folder name is hard-coded in the code? I couldn't find the "transferred from ..." label in Transiflex either. I think this is a problem in all languages other than English.

The goal is to have a folder named (ideally) : 
transféré par John Doe le 22-06-2022 à 09-05-02

![2022-06-22_14-21](https://user-images.githubusercontent.com/33763786/175027661-5fdc4972-79a5-4e66-84ee-e354dd5227ac.png)

### Steps to reproduce

1. Switch your user interface in french and switch the other user interface in french too (settings)
2. With your user, create a folder and put eventually some content in it
3. Transfer it to the other user (settings)
4. Connect to Nextcloud as the new proprietary user and accept de transfer
5. Wait for the transfer
6. Check the name of the folder. It is written in English instead of French

### Expected behavior

The name of the folder sould be (ideally) : 
transféré par John Doe le 22-06-2022 à 09-05-02

### Installation method

Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.mydomain.fr"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "24.0.2.1",
    "updatechecker": true,
    "overwrite.cli.url": "https:\/\/nextcloud.mydomain.fr",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "default_language": "fr",
    "default_locale": "fr_FR",
    "default_phone_region": "ISO3166-2",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "updater.release.channel": "stable",
    "app_install_overwrite": [
        "occweb"
    ],
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```

### List of activated Apps

```shell
Enabled:
 - accessibility: 1.10.0
 - activity: 2.16.0
 - announcementcenter: 6.3.1
 - bruteforcesettings: 2.4.0
 - calendar: 3.4.0
 - cfg_share_links: 2.0.0
 - circles: 24.0.0
 - cloud_federation_api: 1.7.0
 - comments: 1.14.0
 - contacts: 4.1.1
 - contactsinteraction: 1.5.0
 - dashboard: 7.4.0
 - dav: 1.22.0
 - deck: 1.7.1
 - external: 4.0.0
 - extract: 1.3.5
 - federatedfilesharing: 1.14.0
 - federation: 1.14.0
 - files: 1.19.0
 - files_accesscontrol: 1.14.0
 - files_automatedtagging: 1.14.0
 - files_external: 1.16.1
 - files_linkeditor: 1.1.10
 - files_pdfviewer: 2.5.0
 - files_readmemd: 1.2.2
 - files_rightclick: 1.3.0
 - files_sharing: 1.16.2
 - files_trashbin: 1.14.0
 - files_versions: 1.17.0
 - files_videoplayer: 1.13.0
 - files_zip: 1.1.1
 - firstrunwizard: 2.13.0
 - groupfolders: 12.0.0
 - guests: 2.2.0
 - impersonate: 1.11.0
 - jitsi: 0.15.0
 - logreader: 2.9.0
 - lookup_server_connector: 1.12.0
 - metadata: 0.16.0
 - nextcloud_announcements: 1.13.0
 - notes: 4.3.1
 - notifications: 2.12.0
 - oauth2: 1.12.0
 - occweb: 0.1.0
 - password_policy: 1.14.0
 - passwords: 2022.6.20
 - phonetrack: 0.7.0
 - photos: 1.6.0
 - privacy: 1.8.0
 - provisioning_api: 1.14.0
 - quota_warning: 1.14.0
 - recommendations: 1.3.0
 - richdocuments: 6.1.0
 - richdocumentscode: 21.11.402
 - serverinfo: 1.14.0
 - settings: 1.6.0
 - sharebymail: 1.14.0
 - sharerenamer: 3.0.1
 - spreed: 14.0.2
 - support: 1.7.0
 - survey_client: 1.12.0
 - systemtags: 1.14.0
 - text: 3.5.1
 - theming: 1.15.0
 - theming_customcss: 1.11.0
 - twofactor_backupcodes: 1.13.0
 - twofactor_email: 2.4.0
 - twofactor_nextcloud_notification: 3.4.0
 - twofactor_totp: 6.4.0
 - updatenotification: 1.14.0
 - user_status: 1.4.0
 - video_converter: 1.0.5
 - viewer: 1.8.0
 - weather_status: 1.4.0
 - welcome: 1.0.1
 - workflowengine: 2.6.0
Disabled:
 - admin_audit
 - duplicatefinder: 0.0.14
 - encryption
 - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Heavy file ; I can provide it if needed.
```

**Comment by Jerome-Herbinet** [comment]
Cc @ChristophWurst

**Comment by ChristophWurst** [comment]
There is no localization at https://github.com/nextcloud/server/blob/62d47100ec36a6c7de286f473f91400233edbf4c/apps/files/lib/Service/OwnershipTransferService.php#L135-L139

**Comment by Jerome-Herbinet** [comment]
@ChristophWurst, i don't understand what you mean with this reply (sorry) ; can you explain me simply ?

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by Jerome-Herbinet** [comment]
@szaimen, this problem still occurs in NC 25.0.3.

**Comment by skjnldsv** [comment]
> I don't understand what you mean with this reply (sorry) ; can you explain me simply ?

The new path is hardcoded and not using the translations methods available.
So the new path is never translated
