### ISSUE TITLE
[Bug]: Encryption version migration leaves some files encrypted

### ISSUE THREAD

**Issue by pm98zz-c** [nextcloud/server#32999]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Following an upgrade (quite some time ago), I ran in a bunch of php exceptions trying to run `occ encryption:scan:legacy-format`. I thus tried to run `files:scan` and `encryption:migrate-key-storage-format`.
Problem is that I now realize some (presumably older files) aren't properly decrypted, and they're now stuck encrypted. Header states:
```
HBEGIN:oc_encryption_module:OC_DEFAULT_MODULE:cipher:AES-256-CTR:signed:true:HEND
```

Worse, I also realized that the sync client did pick those up and replaced the local versions too. Not too sure what to do here.

### Steps to reproduce

Tricky,

### Expected behavior

I'd expected the files to be re-encrypted properly using the new format.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cl.example.com"
        ],
        "trashbin_retention_obligation": "auto,30",
        "versions_retention_obligation": "auto,30",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/cl.example.com",
        "dbtype": "mysql",
        "version": "24.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Paris",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 1,
        "log_type": "file",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "maintenance": false,
        "updatechecker": true,
        "theme": "",
        "htaccess.RewriteBase": "\/",
        "updater.release.channel": "stable",
        "mysql.utf8mb4": true,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "pipe",
        "mail_smtpport": "25",
        "encryption.legacy_format_support": true,
        "encryption.key_storage_migrated": false,
        "default_phone_region": "FR"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - encryption: 2.12.0
  - federatedfilesharing: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - bruteforcesettings: 2.1.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - federation: 0.0.4
  - files_external
  - firstrunwizard: 1.1
  - systemtags: 1.10.0
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional info

There are a couple of similar existing (closed) issues, eg https://github.com/nextcloud/server/issues/18709 but they're either too old or not exactly relevant.

**Comment by pm98zz-c** [comment]
Sorry, forgot to add some important info, the `encryption.key_storage_migrated` variable is set to false, but the migrate command did definitively complete and succeed, which is puzzling.

**Comment by pm98zz-c** [comment]
Also, from ` php  occ encryption:scan:legacy-format`:
```
All scanned files are properly encrypted. You can disable the legacy compatibility mode.
```

**Comment by snaildos** [comment]
Yes, can confirm, this issue needs to be escalated.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
