### ISSUE TITLE
Delegated user group administrators should not have the user group creation field

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/server#33005]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Delegated user group administrators should not have the user group creation field.

### Steps to reproduce

1. As an administrator, designate a user as administrator of a user group
2. Log in as this designated user
3. Go to user management
4. You will see that it has the user group creation module. Fortunately, the group creation does not work, but the module should not appear.
5. 
![2022-06-24_10-48](https://user-images.githubusercontent.com/33763786/175499803-7c8ea519-ccbe-4288-b838-df0ba7109446.png)

### Expected behavior

The group creation module should not appear.

### Installation method

Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.mydomain.fr"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "24.0.2.1",
    "updatechecker": true,
    "overwrite.cli.url": "https:\/\/nextcloud.mydomain.fr",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "default_language": "fr",
    "default_locale": "fr_FR",
    "default_phone_region": "ISO3166-2",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "updater.release.channel": "stable",
    "app_install_overwrite": [
        "occweb"
    ]
}
```

### List of activated Apps

```shell
Enabled:
 - accessibility: 1.10.0
 - activity: 2.16.0
 - announcementcenter: 6.3.1
 - bruteforcesettings: 2.4.0
 - calendar: 3.4.0
 - cfg_share_links: 2.0.0
 - circles: 24.0.0
 - cloud_federation_api: 1.7.0
 - comments: 1.14.0
 - contacts: 4.1.1
 - contactsinteraction: 1.5.0
 - dashboard: 7.4.0
 - dav: 1.22.0
 - deck: 1.7.1
 - external: 4.0.0
 - extract: 1.3.5
 - federatedfilesharing: 1.14.0
 - federation: 1.14.0
 - files: 1.19.0
 - files_accesscontrol: 1.14.0
 - files_automatedtagging: 1.14.0
 - files_external: 1.16.1
 - files_linkeditor: 1.1.10
 - files_pdfviewer: 2.5.0
 - files_readmemd: 1.2.2
 - files_rightclick: 1.3.0
 - files_sharing: 1.16.2
 - files_trashbin: 1.14.0
 - files_versions: 1.17.0
 - files_videoplayer: 1.13.0
 - files_zip: 1.1.1
 - firstrunwizard: 2.13.0
 - groupfolders: 12.0.1
 - guests: 2.2.0
 - impersonate: 1.11.0
 - jitsi: 0.15.0
 - logreader: 2.9.0
 - lookup_server_connector: 1.12.0
 - metadata: 0.16.0
 - nextcloud_announcements: 1.13.0
 - notes: 4.3.1
 - notifications: 2.12.0
 - oauth2: 1.12.0
 - occweb: 0.1.0
 - password_policy: 1.14.0
 - passwords: 2022.6.20
 - phonetrack: 0.7.0
 - photos: 1.6.0
 - privacy: 1.8.0
 - provisioning_api: 1.14.0
 - quota_warning: 1.14.0
 - recommendations: 1.3.0
 - richdocuments: 6.1.0
 - richdocumentscode: 21.11.402
 - serverinfo: 1.14.0
 - settings: 1.6.0
 - sharebymail: 1.14.0
 - sharerenamer: 3.0.1
 - spreed: 14.0.2
 - support: 1.7.0
 - survey_client: 1.12.0
 - systemtags: 1.14.0
 - text: 3.5.1
 - theming: 1.15.0
 - theming_customcss: 1.11.0
 - twofactor_backupcodes: 1.13.0
 - twofactor_email: 2.4.0
 - twofactor_nextcloud_notification: 3.4.0
 - twofactor_totp: 6.4.0
 - updatenotification: 1.14.0
 - user_status: 1.4.0
 - video_converter: 1.0.5
 - viewer: 1.8.0
 - weather_status: 1.4.0
 - welcome: 1.0.1
 - workflowengine: 2.6.0
Disabled:
 - admin_audit
 - duplicatefinder: 0.0.14
 - encryption
 - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Can be provided if neccessary.
```

**Comment by kesselb** [comment]
cc @CarlSchwan

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by Jerome-Herbinet** [comment]
@szaimen, this problem still occurs in NC 25.0.3

**Comment by szaimen** [comment]
After thinking about this a 2nd time, this rather looks like a feature request to me to remove the button for group admins.
