### ISSUE TITLE
[Bug]: v24 - Switching loglevel produces white page and browser console JS errors

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#33012]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On NC 24.0.2, trying to switch loglevel by un-checking a checkbox produces a white page and browser console errors.

### Steps to reproduce

1. Go to `/settings/admin/logging`
2. Click on `...` and try to remove some error level by un-checking a checkbox
3. White page and browser console errors

![image](https://user-images.githubusercontent.com/12234510/175661120-1bf009a9-f5e0-44bb-a047-9d0c60b56c00.png)

### Expected behavior

No errors.

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - notify_push: 0.4.0
  - oauth2: 1.12.0
  - onlyoffice: 7.5.2
  - password_policy: 1.14.0
  - photos: 1.6.0
  - provisioning_api: 1.14.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - viewer: 1.8.0
  - workflowengine: 2.6.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Nothing related
```

**Comment by Thyroxine** [comment]
Hi, I found a workaround if somebody needs quick fix of the page:
1. Set `'loglevel' => 2` in `config/config.php` (was `0` before)
(If you have docker version, login as `root` and found the corresponding volume in `/var/lib/docker/volumes`)
2. Clear browser cache and visit the page again.

**Comment by solracsf** [comment]
See https://github.com/nextcloud/logreader/issues/815
