### ISSUE TITLE
[Bug]: Translation error (Hungarian)

### ISSUE THREAD

**Issue by atesz19** [nextcloud/server#33025]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If someone puts me in a group, the activity text not correctly translated to hungarian.

The English version:
![image](https://user-images.githubusercontent.com/24691203/175888075-7f068ea5-f43f-4680-a996-f36b4a95579e.png)

Hungarian version means "Admin has been added to group X"
![image](https://user-images.githubusercontent.com/24691203/175888522-75d7ad4e-4263-4a37-9592-b36061404f6d.png)
The correct translation is '{Admin} hozzáadott téged a(z) {group} csoporthoz'

### Steps to reproduce

If an admin puts me in a group, then i got this activity message.

### Expected behavior

The translation wrong, i suggest this instead: '{Admin} hozzáadott téged a(z) {group} csoporthoz'

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Im not admin so i cant get this information, but i think its not matters for translation bug.
```

**Comment by solracsf** [comment]
Please fix it at https://transifex.com/nextcloud/nextcloud/translate/
