### ISSUE TITLE
Generate random password for file sharing

### ISSUE THREAD

**Issue by EasyPeasy1** [nextcloud/server#3303]
Hi
it would be great if there would be a feature to generate a random password for the file sharing link.
Do you already thought about something like that?

**Comment by szaimen** [comment]
Any update on this?

**Comment by wiswedel** [comment]
@MorrisJobke What do you think?

**Comment by MorrisJobke** [comment]
> @MorrisJobke What do you think?

Sounds good 👍

**Comment by wiswedel** [comment]
duplicate of https://github.com/nextcloud/server/issues/12171
