### ISSUE TITLE
[Bug]: No nonce is added to CSP header for Firefox 100+

### ISSUE THREAD

**Issue by fancycode** [nextcloud/server#33045]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The CSPNonceManager uses a regular expression to check if a browser supports nonces:
https://github.com/nextcloud/server/blob/2956da417841cb045796b5e0ff9ab50d1db4ca94/lib/private/Security/CSP/ContentSecurityPolicyNonceManager.php#L84

However this only detects Firefox versions up to 99 but not the current Firefox 101 (or 100 for that matter), resulting in the nonce not being added to the CSP header.

Example user-agent for Firefox 101:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0`

### Steps to reproduce

1. Open a Nextcloud page in Firefox 100 or newer and inspect the response headers.
2. Check the `Content-Security-Policy` header.
3. Note that there is no nonce in the `script-src` policy.

### Expected behavior

A nonce should be present for `script-src`.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
-
```

### Additional info

Probably the regex could simply be updated to `Request::USER_AGENT_FIREFOX`:
https://github.com/nextcloud/server/blob/2956da417841cb045796b5e0ff9ab50d1db4ca94/lib/private/AppFramework/Http/Request.php#L70

**Comment by kesselb** [comment]
Good catch! 

> Probably the regex could simply be updated to Request::USER_AGENT_FIREFOX:

That sounds good to me. I guess the reason for not using Request::USER_AGENT_FIREFOX back than was to require a minimum version of Firefox:

![image](https://user-images.githubusercontent.com/3902676/176191530-837010e4-2db3-46d4-9ad4-30adb4bfdccc.png)

Firefox 45 was release 2016-03-08 (ESR 2017-04-19 ) so it should be fine to migrate to Request::USER_AGENT_FIREFOX:

![image](https://user-images.githubusercontent.com/3902676/176192138-9a16850e-f9d9-4a45-b814-c6d0a959687b.png)
