### ISSUE TITLE
Collaborative tags

### ISSUE THREAD

**Issue by MJayy94** [nextcloud/server#33046]
Dear all,

is there a way to integreate in "Collaborative tags" a Funtction to delete some Tags? 
Also - is there any Option, do give Permissions to Groups on a Tag? 

Example: 
I want that some users, can Tag some Files with "DONE" <- but not all Users should be allowed to use this tag. Other users (with other groups) should be able to tag files with "CHECK" or smth. like that. 
They should only able to use this one tag and have no View over the other Tags (Thats for Admins only).

Would be nice to have a Integration here.

Is there anything planned?

We are Using: 1.13.0 of this App.
Programmed by: Vincent Petry, Joas Schilling

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by skjnldsv** [comment]
> I want that some users, can Tag some Files with "DONE" <- but not all Users should be allowed to use this tag. Other users (with other groups) should be able to tag files with "CHECK" or smth. like that.
They should only able to use this one tag and have no View over the other Tags (Thats for Admins only).

https://github.com/nextcloud/server/issues/32454
