### ISSUE TITLE
[Bug]: bad UX when configuring "Limit to groups" on apps page

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#33054]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When trying to limit apps to groups, the group selector is hidden behind an app's screenshot, if there is one. It works flawlessly for apps without screenshot. Because one item is visible it is still possible to operate, nevertheless it appears buggy.

![simplescreenrecorder-2022-06-29_00 03 50](https://user-images.githubusercontent.com/2184312/176308441-fa84c2f6-bdca-4a69-b26c-3ca11e06d103.gif)

### Steps to reproduce

1. go to apps
2. open sidebar of an enable app with a screenshot
3. try limit it to a group

### Expected behavior

The whole dropdown visible and usable, as is the case for apps without screenshot:

![Screenshot_20220629_000733](https://user-images.githubusercontent.com/2184312/176308777-1c864670-34a3-4a02-a06a-9b189b95a785.png)

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
see gif :)
```

### Additional info

This affects all versions down to 22.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by szaimen** [comment]
All good! I think this one is actually already fixed in the meantime.
