### ISSUE TITLE
Wrong capitalization in username leads to warning 

### ISSUE THREAD

**Issue by JSoko** [nextcloud/server#3305]
### Steps to reproduce
1. create a user testuser
2. create a acount in NextcloudAndroid 1.41 and name the user Testuser
3. Connection is established without warning
See also https://github.com/nextcloud/android/issues/594

### Expected behaviour
No error
Or decline connection because the username has an other capatilisation (T instead of t)

### Actual behaviour
The account in Android nextcloud works, but while uploading you get following warning in the nextcloud-log:`
initMountPoints() called with wrong user casing. This could be a bug. Expected: "testuser" got "Testuser". Stack: [{"file":"\/media\/ssd\/www\/cloud\/lib\/private\/Files\/Filesystem.php","line":375,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::"},{"file":"\/media\/ssd\/www\/cloud\/lib\/private\/legacy\/util.php","line":235,"function":"init","class":"OC\\Files\\Filesystem","type":"::"},{"file":"\/media\/ssd\/www\/cloud\/apps\/provisioning_api\/lib\/Controller\/UsersController.php","line":634,"function":"setupFS","class":"OC_Util","type":"::"},{"file":"\/media\/ssd\/www\/cloud\/apps\/provisioning_api\/lib\/Controller\/UsersController.php","line":213,"function":"fillStorageInfo","class":"OCA\\Provisioning_API\\Controller\\UsersController","type":"->"},{"function":"getUser","class":"OCA\\Provisioning_API\\Controller\\UsersController","type":"->"},{"file":"\/media\/ssd\/www\/cloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":160,"function":"call_user_func_array"},{"file":"\/media\/ssd\/www\/cloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":90,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/media\/ssd\/www\/cloud\/lib\/private\/AppFramework\/App.php","line":114,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/media\/ssd\/www\/cloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"\/media\/ssd\/www\/cloud\/lib\/private\/Route\/Router.php","line":299,"function":"call_user_func"},{"file":"\/media\/ssd\/www\/cloud\/ocs\/v1.php","line":79,"function":"match","class":"OC\\Route\\Router","type":"->"}]`

### Server configuration
**Operating system**: Linux OdNc 3.10.103 #1 SMP PREEMPT Sat Sep 10 14:43:59 UTC 2016 armv7l

**Web server:** Apache/2.4.25 (Ubuntu) (apache2handler)

**Database:** mysql 10.0.29

**PHP version:** 7.0.13-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 11.0.1 (stable) - 11.0.1.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
update with updater
**Where did you install Nextcloud from:** 

**Signing status:**
<details>
	<summary>Signing status</summary>

```
[]
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.4.1
 - admin_audit: 1.1.0
 - announcementcenter: 3.0.0
 - bookmarks: 0.9.1
 - calendar: 1.5.0
 - comments: 1.1.0
 - contacts: 1.5.2
 - dav: 1.1.1
 - direct_menu: 0.10.0
 - federatedfilesharing: 1.1.1
 - files: 1.6.1
 - files_automatedtagging: 1.1.1
 - files_downloadactivity: 1.0.0
 - files_pdfviewer: 1.0.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - flowupload: 0.4
 - html5_videoplayer: 1.0
 - issuetemplate: 0.2.0
 - keeweb: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - news: 10.1.0
 - nextcloud_announcements: 1.0
 - nextnotes: 0.9.1
 - notes: 2.2.0
 - notifications: 1.0.1
 - ocsms: 1.11.4
 - ownbackup: 16.11.0
 - password_policy: 1.1.0
 - provisioning_api: 1.1.0
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - shorten: 0.0.15
 - spreed: 1.2.0
 - spreedme: 0.3.6
 - survey_client: 0.1.5
 - systemtags: 1.1.3
 - tasks: 0.9.4
 - templateeditor: 0.2
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - updatenotification: 1.1.1
 - workflowengine: 1.1.1

Disabled:
 - audioplayer
 - encryption
 - external
 - federation
 - files_accesscontrol
 - files_external
 - files_retention
 - firstrunwizard
 - flowupload.old
 - gallery
 - qownnotesapi
 - user_external
 - user_ldap
 - user_saml
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "loglevel": 2,
    "maintenance": false,
    "integrity.check.disabled": false,
    "default_language": "de_DE",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "\/var\/www\/cloud\/data",
    "tempdirectory": "\/media\/ssd\/phptemp\/",
    "dbtype": "mysql",
    "version": "11.0.1.2",
    "theme": "",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "dbname": "nextcloud",
    "dbhost": "127.0.0.1",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "logtimezone": "Europe\/Berlin",
    "log_rotate_size": 500000,
    "cron_log": true,
    "maxZipInputSize": 2147483648,
    "overwritewebroot": "\/",
    "overwrite.cli.url": "\/",
    "htaccess.RewriteBase": "\/",
    "allowZipDownload": true,
    "versions": "true",
    "versions_retention_obligation": "1,3",
    "instanceid": "5072f7e9eec7e",
    "knowledgebaseenabled": true,
    "check_for_working_webdav": true,
    "check_for_working_htaccess": true,
    "check_for_working_wellknown_setup": true,
    "has_internet_connection": true,
    "forcessl": true,
    "activity_expire_days": 8,
    "appcodechecker": true,
    "skeletondirectory": "",
    "trashbin_retention_obligation": "auto,15",
    "appstore.experimental.enabled": true,
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***",
        "192.168.1.234"
    ],
    "mail_smtpmode": "smtp",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "no-reply",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "updater.release.channel": "stable"
}
```
</details>

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
	see above
	```
</details>

**Comment by nickvergessen** [comment]
I thought we fixed this for 10 already.

@MorrisJobke can you remember?

**Comment by MorrisJobke** [comment]
> @MorrisJobke can you remember?

Yes - this is only a warning, that this is wrong - we added it there #2007

We autocorrect the wrong casing, but maybe we should try to eliminate the source of this?

**Comment by blizzz** [comment]
Just combed across it. Forget the casing. It seems that the loginname (as in whatever the user typed to connect with) is used, instead of the username.

What's to  do is do go through the stack and check the got for wrong usage… and eliminate it.

**Comment by tobiasKaminsky** [comment]
If something on the client side is needed, please reply here nextcloud/android#594 as we have closed it there already, thinking it is a server only problem ;-)

**Comment by nickvergessen** [comment]
The `cloud/user` endpoint gives you the correct spelling in the `<id>` element:
```
curl -H "OCS-APIREQUEST: true" https://Admin:admin@localhost/ocs/v2.php/cloud/user
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>200</statuscode>
  <message>OK</message>
 </meta>
 <data>
  <id>admin</id>
  <display-name>Administrator</display-name>
 </data>
</ocs>
```
