### ISSUE TITLE
Sort apps alphabetically on apps setting page

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/server#3306]
They are sorted alphabetically already, but divided into 2 sections which i don't know for what they are good for.

![auswahl_001](https://cloud.githubusercontent.com/assets/24833757/22396381/ab325cb8-e558-11e6-8476-bf83c0fcb773.png)

**Comment by DevGoslinga** [comment]
The first section, displays the apps marked as official. Adding a divider will help in making this more obvious.

**Comment by Sanookmakmak** [comment]
> The first section displays the apps marked as official.

That information is useless on the "Enabled Apps" page. It's just confusing.

**Comment by ChristophWurst** [comment]
This should be added to https://github.com/nextcloud/server/issues/3194

**Comment by nickvergessen** [comment]
I will close this in favor of #3194
