### ISSUE TITLE
Do not show twofactor_backupcodes in personal-settings if no twofactor_ is enabled

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#3308]
Why should you create backup codes - if you don't use 2-Factor at all 🤔😜 

@ChristophWurst

**Comment by ChristophWurst** [comment]
Not sure about that.

cc @nextcloud/security

**Comment by nickvergessen** [comment]
👍 also as discussed in the hackweek, there should be a paragraph with an explanation at the settings. Average users don't know what this screen is going to do:

> ### Second-factor backup codes
> `Generate backup codes`

**Comment by schiessle** [comment]
I agree with @MariusBluem. This also confused me in the past. I don't see a need for showing two factor auth backup codes if 2FA is disabled.

**Comment by jancborchardt** [comment]
@ChristophWurst can you give me some hints regarding explanation text? I’m happy to open a pull request there. Something like:

> Generate backup codes to be able to authenticate in case you lose your device used for two-factor authentication.

But still the separate question is: Can we please not show this section when you don’t have a twofactor app enabled?
