### ISSUE TITLE
Mac OS X Client: Display problems with multiple accounts

### ISSUE THREAD

**Issue by daniel-hmc** [nextcloud/server#3311]
Sorry, this is again a client issue. But I have not found the right way to file an issue for the client. Please shift this ticket accordingly to the correct project in the bug tracker.

The icon color of the client does not match actual current behavior.
Sometimes it's green when the client is still syncing.
This seems to happen only with more than one account registered.

See attached screenshot.

![ishot-2017-01-29_16-29-551](https://cloud.githubusercontent.com/assets/25068087/22405311/1b6a3b70-e641-11e6-824c-7c90e00f6d68.jpg)

**Comment by nickvergessen** [comment]
@rullzer

**Comment by MorrisJobke** [comment]
Could you retry with a recent version of the client? (2.3.2 AFAIK)

I will close for now. If this is still the case we can reopen the ticket.

Thanks
