### ISSUE TITLE
occ user:setting doing only half the job!?

### ISSUE THREAD

**Issue by matrixdesert** [nextcloud/server#3312]
Hello!

I'm running NC 11.0.1 (Updated from NC 10.0).
I tried to change some users with the occ - but yea....

When a user is modified using "occ user:setting" adding an e-mailadress the e-mailadress is stored in DB-Table "oc_preferences".
But the e-mailadress does not show up in the WEBUI under "Personal-> Mailadress".

I think the occ-command should also change the entry for the given userid in DB-Table "oc_accounts"!?

Any hints!?
Best regards!

**Comment by nickvergessen** [comment]
Uhh, @schiessle I think it makes sense, do you agree?

**Comment by matrixdesert** [comment]
Thanks @nickvergessen for picking up the issue.
I also noticed that... "occ user:delete" does not clean up DB-Table "oc_accounts" after deletion!?
Do you think i should open an extra issue for that!?
Thx!

**Comment by nickvergessen** [comment]
yes please.

**Comment by samweisgamdschie** [comment]
Please also add a full form for entering all possible user data in WebGUI!
