### ISSUE TITLE
Filepicker for "Move file" should remember the last directory.

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#3313]
It should automatically reopen the last chosen directory, like browsers do for uploads.
This allows easier moving of multiple files in a row.

Agreed? @jancborchardt @icewind1991

**Comment by ChristophWurst** [comment]
Makes sense. We have the same problem in Mail where it is cumbersome to add multiple attachments.

**Comment by jancborchardt** [comment]
I agree, and this is a duplicate of https://github.com/nextcloud/server/issues/644 ;)
