### ISSUE TITLE
Can you change the mail_from_name in Nextcloud?

### ISSUE THREAD

**Issue by g4jsg** [nextcloud/server#3314]
New user, reset passwords and sharing emails all show the senders name as Nextcloud and ignore the theming settings.

Is there a way to change the email FROM name?

Nextcloud 11.0.1 (stable)

Thanks, John

**Comment by nickvergessen** [comment]
Should be a similar issue to #3148

**Comment by g4jsg** [comment]
No, the theme for the web end is fine.

When you make a new user the email comes from Nextcloud, however the signature within the email does show the theme name I have set.

When the sharing email is sent out there's no From name, it only shows the email address. 

So there's a bug here, the New User email isn't picking up on the Theme name change and the sharebyemail system is missing the From Name altogether.

John

**Comment by enoch85** [comment]
I can confirm this. Would be great if it could be fixed in 12.0

**Comment by autrui** [comment]
Yes, please. Some NC users who are not familiar with tech stuff find it "weird" or even "suspicious" when malformed email sender adresses turn up in their inbox.

I (NC 12) can confirm this:

When users of my Nextcloud get emails from the system/notifications (activity, test mails...),
the sender address is not in the standard format **Full Name** _<email@somedomain.com>_

Users keep getting sender adresses like

**"" <no-reply@mydomain.com> <no-reply@mydomain.com>**

for test mails and activity notifications.

I would really appreciate it if the mail_from_name could be set somewhere (even if it's the config.php). That would be great.

Thank you.

**Comment by nickvergessen** [comment]
For me I get the instance name for the test email and activity email:
```
From: Instance name from theming app <no-reply@localhost>
To: admin <admin@localhost>
```

I only get it with empty name, when I clean the Name field in the theming app.

**Comment by juliushaertl** [comment]
Same here, it uses the theming name on 12.0.2 as you would expect it to do. Let's close this.
