### ISSUE TITLE
[Bug]: Wrong/missing german translation

### ISSUE THREAD

**Issue by Herbertholzkopf** [nextcloud/server#33170]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![image](https://user-images.githubusercontent.com/93044485/177976046-b05408c4-1f27-4b81-b8c0-94941948ec12.png)

The translation is wrong / missing at the first word...

It's not "More Aktivitäten" it's "Weitere Aktivitäten"....

### Steps to reproduce

1. Set Nextcloud  to German
2. Go to the Nextcloud-Dashboard
3. Lock at the bottem of the Aktivitäten-Card "activities"

### Expected behavior

It's not "More Aktivitäten" it's "Weitere Aktivitäten"....

### Installation method

Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MariaDB

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - apporder: 0.15.0
  - bookmarks: 10.5.1
  - breezedark: 24.0.1
  - calendar: 3.4.2
  - camerarawpreviews: 0.7.16
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - collectives: 1.2.1
  - comments: 1.14.0
  - contacts: 4.1.1
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - deck: 1.7.1
  - drawio: 1.0.3
  - duplicatefinder: 0.0.14
  - extract: 1.3.5
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_linkeditor: 1.1.10
  - files_markdown: 2.3.6
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - forms: 2.5.1
  - groupfolders: 12.0.1
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - metadata: 0.16.0
  - notes: 4.3.1
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - onlyoffice: 7.5.2
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - riotchat: 0.13.1
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - tasks: 0.14.4
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_nextcloud_notification: 3.4.0
  - twofactor_totp: 6.4.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - announcementcenter: 6.3.1
  - bruteforcesettings: 2.4.0
  - encryption
  - files_antivirus: 3.3.0
  - files_external
  - files_texteditor: 2.14.0
  - mail: 1.13.6
  - news: 18.1.0
  - nextcloud_announcements: 1.13.0
  - openotp_auth
  - openotp_sign: 1.3.2
  - printer: 0.0.5
  - user_ldap
```

### Nextcloud Signing status

```shell
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .htaccess
		- .user.ini
- openotp_auth
	- INVALID_HASH
		- vendor/autoload.php
		- vendor/composer/autoload_real.php
		- vendor/composer/autoload_static.php
		- vendor/composer/installed.php
```

**Comment by solracsf** [comment]
Hi, please help and fix it at https://transifex.com/nextcloud/nextcloud/translate
Thanks 👍
