### ISSUE TITLE
Update fails due to extra files within main directory

### ISSUE THREAD

**Issue by alve89** [nextcloud/server#3317]
If there are extra files within the main directory the updater aborts the update process (see attached image). In my case the extra files were "/logs/" and "/usage/". These folders are set by my hoster automatically.

A configuration with an excluding list was senseful I guess. Or just don't check the existing files. Or enable to skip this abortion.

![bildschirmfoto 2017-01-30 um 11 06 05](https://cloud.githubusercontent.com/assets/11487054/22419191/a79fb1e2-e6dc-11e6-8bf3-da8c828482f5.png)

**Comment by nickvergessen** [comment]
Please report your issue to the updater repository:
https://github.com/nextcloud/updater/issues
