### ISSUE TITLE
Misleading error message regarding X-Frame-Options

### ISSUE THREAD

**Issue by jschlyter** [nextcloud/server#3318]
### Steps to reproduce
1. Configure web server with 'X-Frame-Options: DENY'
2. Watch Nextcloud warn: The "X-Frame-Options" HTTP header is not configured to equal to "SAMEORIGIN".

### Expected behaviour
DENY is better than SAMEORIGIN, allow that as well.

### Actual behaviour
Warning emitted.

### Server configuration
**Operating system**:
Ubuntu Linux 16.04 LTS
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
11.0.1

**Comment by pixelipo** [comment]
Might be worth noting that this effectively disables Mail app (HTML body loaded in iframe)

**Comment by coderkun** [comment]
Duplicate of #3808.
