### ISSUE TITLE
[Bug]: German translation error: wrong name for text file creation.

### ISSUE THREAD

**Issue by HPPinata** [nextcloud/server#33189]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Translation error:
The default filename for creating a new .md document in the German language profile "Deutsch (Persönlich: Du)" is this mess:
"Benötigt keine Übersetzung. Für iOS wird nur die formelle Übersetzung verwendet (de_DE)."
instead of "Neue Textdatei"
I noticed it when did a fresh install of 24.0.2 instead of 24.0.1
![Screenshot_2022-07-10-10-23-28-591](https://user-images.githubusercontent.com/83947761/178137381-c60506ca-0c3c-470d-b82f-81185ab661da.jpeg)
![Screenshot_2022-07-10-10-23-57-323](https://user-images.githubusercontent.com/83947761/178137391-a77d3c28-7a4e-4b2f-9c9b-11640a7b2d93.jpeg)

### Steps to reproduce

1. Select language Deutsch (Persönlich: Du)
2. Go to Dateien (Files)
3. Click on the plus Icon to create / upload a new file and look at the default filename for .md

### Expected behavior

Set the default filename to "Neue Textdatei" the .md extension seems to be added automatically.

### Installation method

Official Docker image

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
- files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by kesselb** [comment]
Hi, thanks for reporting a bug :+1: 

https://github.com/nextcloud/text/commit/a370d8d859444b38ece88330bc60782ce2258783 fixes it and will be available in the next maintenance release
