### ISSUE TITLE
RSVP to Calendar Event does not send update.

### ISSUE THREAD

**Issue by kevincox** [nextcloud/server#33188]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

I am trying to respond to events from other people. They have sent me a calendar event and I update my attendance to Accept or Decline. However Nextcloud doesn't do anything other than update the local event. This happens both from the Nextcloud Calendar App and external CalDAV apps such as Thunderbird.

This is incredibly surprising as I thought others were getting my RSVPs. If a feature this critical is missing it should probably have a warning in the UI.

**Describe the solution you'd like**

Nextcloud should send out emails to the attendees and other participants as expected.

**Describe alternatives you've considered**

A workaround is to use client-side email scheduling (a feature supported only by a few clients such as Thunderbird).

**Additional context**
There are no logs on the server so this doesn't appear to be an error. Just a missing feature.

**Comment by flortsch** [comment]
Same issue is reported here as well: https://github.com/nextcloud/server/issues/38651

**Comment by SebastianKrupinski** [comment]
Fixed with https://github.com/nextcloud/server/pull/44893
