### ISSUE TITLE
The Nextcloud Files "projects" feature really needs a "projects list" feature (see my UX suggestion screenshot)

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/server#33199]
Hello !

**Is your feature request related to a problem? Please describe.**
After testing this feature several times, I find the concept very interesting, but unfortunately, I find that something is really missing to make it really usable and therefore used by the largest number of users possible. Indeed, you never have any idea of how many projects there are, and it can quickly become a little messy. I also noticed that there is no control over the name of the projects, which makes it possible to create duplicate projects.

**Describe the solution you'd like**
I suggest this UI/UX improvement : 
![nc_projects](https://user-images.githubusercontent.com/33763786/178290565-746b0a18-3aa7-4939-8c59-b983ea1afcf0.jpg)
This consists of adding a button to access the list of projects on the left side panel. I'll let you look at the screenshot in detail. You will see how I propose to access the **list of projects**, as well as the details of each one, but also how, from this place, **to add files to it** (or delete).
**I also advise a check on the naming of projects to avoid duplication.**

Best regards,
Jérôme

**Comment by Jerome-Herbinet** [comment]
My suggestion does not take into account the possibility of adding files to the project. It should be imagined at the level of the list of project elements and at the level of the "+" button.

**Comment by Spartachetto** [comment]
This should be more or less similar to what described in #15841
I do agree that something like this would increase a lot the usability of projects.

**Comment by tomotello** [comment]
Fully agree too. I just started using projects, but was concerned not to be able to access my formerly assigned projects easily on something like a "my-projects overview".

**Comment by Jerome-Herbinet** [comment]
> Projects functionality deprecated in nc25.
> 
>     * [Projects rework to automatic "Related resources" #28320](https://github.com/nextcloud/server/issues/28320)

Thanks @sunjam I'm aware of this fact but I forgot my opened issue. So it's not necessary anymore because I obviously think that this feature will never evolve again as long as Nextcloud < 25 are maintained.
