### ISSUE TITLE
[Bug]: Folder is locked message when creating folder, file and then rename folder

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#33207]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

File is locked error is shown when trying to move/rename a freshly created folder

### Steps to reproduce

I used Android on CI, with latest master
1. create a folder
2. upload a small text file in it
3. rename folder
4. see error

### Expected behavior

As webdav calls are done one after another there should be no exception.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
None
```

### Additional info

@juliushaertl

**Comment by juliushaertl** [comment]
Do you have a link to the failing CI steps maybe even with their logs?

**Comment by juliushaertl** [comment]
Suspicion: files_lock may block the lock on the folder if the text app still owns a lock on the readme within.

**Comment by tobiasKaminsky** [comment]
File locking app was not enabled.

This is one example of failing CI, but no relevant server logs:
https://drone.nextcloud.com/nextcloud/android/5454

This is test: https://github.com/nextcloud/android/blob/master/app/src/androidTest/java/com/owncloud/android/FileIT.java#L90

**Comment by juliushaertl** [comment]
Ok, then I have no good idea. From the tests it looks like at least the blocking operations should already be waited for.

Maybe you can turn on `'filelocking.debug' => true,` in config.php on a CI run to get some more verbose logs on the locking.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by tobiasKaminsky** [comment]
Seems not to happen any more.
