### ISSUE TITLE
Don't send security header twice (via .htaccess & php response.php)

### ISSUE THREAD

**Issue by agoat** [nextcloud/server#3322]
### Steps to reproduce
1. Standard nextcloud 11.0.1 installation
2. Login and go to the admin page
3. Also look into the chrome (or firefox) dev tools for the response of the html page

### Expected behaviour
No warnings about Security headers

### Actual behaviour
- The admin page show warnings about security headers (X-XSS-Protection, X-Content-Type-Options, X-Robots-Tag, X-Frame-Options, X-Download-Options, X-Permitted-Cross-Domain-Policies).
- In the chrome dev tool you can see that every security header is send twice. Chrome is also complaining about pasing the header X-XSS-Protection: 1; mode=block, 1;mode=block: ..

### Server configuration
**Operating system**: linux (domainfactory ManagedHosting)

**Web server:** Apache 2.4.20

**Database:** MySQL 5.6

**PHP version:** 7.0.13

**Nextcloud version:** 11.0.1 (production)

**Updated from an older Nextcloud/ownCloud or fresh install:** Installed 11.0.0 and update to 11.0.1

**Where did you install Nextcloud from:** Manuall upload and install script

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```

    "system": {
        "instanceid": "ocdkffw2fsut",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.agoat.info"
        ],
        "datadirectory": "\/***REMOVED SENSITIVE VALUE***\/cloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.agoat.info",
        "dbtype": "mysql",
        "version": "11.0.1.2",
        "dbname": "db30285_16",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "tempdirectory": "\/***REMOVED SENSITIVE VALUE***\/cloud\/tmp",
        "part_file_in_storage": false,
        "filelocking.ttl": 300,
        "loglevel": 0,
        "enable_previews": true,
        "preview_max_x": "1920",
        "preview_max_y": "1920",
        "preview_max_scale_factor": 2,
        "preview_max_filesize_image": 32,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\SVG",
            "OC\\Preview\\MP3",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF"
        ],
        "maintenance": false,
        "theme": "",
        "updater.release.channel": "production",
        "singleuser": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }(Without the database password, passwordsalt and secret)
```
</details>

### Client configuration
**Browser:** Google Chrome 56.0.2924.76 (64bit)

**Operating system:** Windows 10 Pro

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by uok** [comment]
Also if you use "Header always set X-Content-Type-Options nosniff" in your vhost-config you end up with header "X-Content-Type-Options: nosniff, nosniff" in NextCloud and get an admin warning message that "X-Content-Type-Options" is not set to "nosniff" correctly.

**Comment by LukasReschke** [comment]
Please don't set such values in your VHost config but leave that to Nextcloud.
