### ISSUE TITLE
[Bug]: Icon "More" in header should use the primary text colour

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#33229]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Icon _More_ in header is using `icon-more-white`, so its colour depends on whether the light or dark mode is used. However, as it appears with a transparent background on the header, which uses the primary colour and does not change based on whether dark mode is used or not, the icon colour should be set to `var(--primary-color-text)` instead (well, I guess so :-) ).

![Header-Apps-Navigation-Icon-More](https://user-images.githubusercontent.com/26858233/178775448-1b15e49c-66b0-467c-b618-dcd206a9f9ef.png)
![Public-Share-Header-Icon-More](https://user-images.githubusercontent.com/26858233/178775492-1206a847-c79b-4d4c-bfc1-bdc15b8f7438.png)

### Steps to reproduce

Scenario 1:
- If not set already, set the default colour in the Theming app
- Enable dark mode
- Narrow the window until the _More_ icon is shown in the list of apps in the header

Scenario 2:
- If not set already, set the default colour in the Theming app
- Enable dark mode (in the browser)
- Share a file with a public link
- Open the link

### Expected behavior

The icon should be "white", but it is "black" instead.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Default apps from a fresh Git installation + Talk.
```

**Comment by szaimen** [comment]
@danxuliu is this still happening?

**Comment by Pytal** [comment]
Fixed icon on light background in https://github.com/nextcloud/server/pull/34714

Scenario 1 with default color and background already fixed in https://github.com/nextcloud/server/pull/33728/files#diff-c0e4c093ed80a9daa2dbfd0136eeea47ac257eead156c4243f9de1b61042c368R238

Scenario 2 already fixed in https://github.com/nextcloud/server/pull/34028/files#diff-c43c0216867d11378193d94f4c233f97980af311e569572cf1cdc8d06b3f377d
