### ISSUE TITLE
[Bug]: External Storage SMB/CIFS needs 2 subfolders to work

### ISSUE THREAD

**Issue by Flashbert** [nextcloud/server#33232]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Mounting an external storage with SMB works only if i add 2 subfolders. With only one subfolder its not working

We have the structure \\Fileserver\Public\Aushang\Infos

If i try to mount Fileserver like this it works:
Host: fileserver
Share: Public
**Subfolder: Aushang\Infos**

If i got only one subfolder it doesn't work:
Host: fileserver
Share: Public
**Subfolder: Aushang**

I already checked every NTFS/share rules, but they are the same, so it seems like a bug

The problem is also described here: https://dannyda.com/2021/11/16/how-to-fix-nextcloud-22-smb-samba-windows-share-error-fatal-webdav-storage-is-tmporarily-not-available-ocpfilesstoragenotavailableexception-etc/

### Steps to reproduce

1. Mount SMB/CIFS with one subfolder -> not working
2. Mount SMB/CIFS with two folder deep subfolder (folder1/folder2)) -> working

### Expected behavior

One subfolder should be enough for mount SMB/CIFS

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - announcementcenter: 6.3.1
  - bruteforcesettings: 2.4.0
  - cloud_federation_api: 1.7.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - files: 1.19.0
  - files_accesscontrol: 1.14.0
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_totp: 6.4.0
  - updatenotification: 1.14.0
  - user_ldap: 1.14.1
  - viewer: 1.8.0
  - workflowengine: 2.6.0
```

### Nextcloud Logs

```shell
Warnung	no app in context	OCP\Files\StorageNotAvailableException: Storage with mount id 9 is not available
/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 548:

OC\Files\Storage\FailedStorage->getAvailability()

/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 548:

OC\Files\Storage\Wrapper\Wrapper->getAvailability()

/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php - line 81:

OC\Files\Storage\Wrapper\Wrapper->getAvailability()

/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php - line 92:

OC\Files\Storage\Wrapper\Availability->isAvailable()

/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php - line 342:

OC\Files\Storage\Wrapper\Availability->checkAvailability()

/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 334:

OC\Files\Storage\Wrapper\Availability->free_space()

/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 334:

OC\Files\Storage\Wrapper\Wrapper->free_space()

/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 334:

OC\Files\Storage\Wrapper\Wrapper->free_space()

/var/www/nextcloud/lib/private/legacy/OC_Helper.php - line 545:

OC\Files\Storage\Wrapper\Wrapper->free_space()

/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 341:

OC_Helper::getStorageInfo()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 765:

OCA\DAV\Connector\Sabre\Directory->getQuotaInfo()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php - line 95:

Sabre\DAV\CorePlugin->Sabre\DAV\{closure}("*** sensiti ... *")

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 769:

Sabre\DAV\PropFind->handle()

/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

Sabre\DAV\CorePlugin->propFind()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1052:

Sabre\DAV\Server->emit()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 984:

Sabre\DAV\Server->getPropertiesByNode()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1662:

Sabre\DAV\Server->getPropertiesIteratorForPath()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1647:

Sabre\DAV\Server->writeMultiStatus()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 346:

Sabre\DAV\Server->generateMultiStatus()

/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

Sabre\DAV\CorePlugin->httpPropFind()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 472:

Sabre\DAV\Server->emit()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 253:

Sabre\DAV\Server->invokeMethod()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 321:

Sabre\DAV\Server->start()

/var/www/nextcloud/apps/dav/lib/Server.php - line 352:

Sabre\DAV\Server->exec()

/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:

OCA\DAV\Server->exec()

/var/www/nextcloud/remote.php - line 166:

require_once("/var/www/ne ... p")

Verursacht durch OCP\Files\StorageNotAvailableException: Storage with mount id 9 is not available
<<closure>>

OCA\Files_External\Config\ConfigAdapter->OCA\Files_External\Config\{closure}("*** sensiti ... *")

/var/www/nextcloud/apps/files_external/lib/Config/ConfigAdapter.php - line 137:

array_map()

/var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php - line 124:

OCA\Files_External\Config\ConfigAdapter->getMountsForUser()

/var/www/nextcloud/lib/private/Files/SetupManager.php - line 213:

OC\Files\Config\MountProviderCollection->addMountForUser()

/var/www/nextcloud/lib/private/Files/SetupManager.php - line 302:

OC\Files\SetupManager->OC\Files\{closure}("*** sensiti ... *")

/var/www/nextcloud/lib/private/Files/SetupManager.php - line 214:

OC\Files\SetupManager->setupForUserWith()

/var/www/nextcloud/lib/private/Files/SetupManager.php - line 414:

OC\Files\SetupManager->setupForUser()

/var/www/nextcloud/lib/private/Files/Mount/Manager.php - line 95:

OC\Files\SetupManager->setupForPath()

/var/www/nextcloud/lib/private/Files/View.php - line 1386:

OC\Files\Mount\Manager->find()

/var/www/nextcloud/lib/private/Files/Node/Root.php - line 205:

OC\Files\View->getFileInfo()

/var/www/nextcloud/lib/private/Files/Node/LazyUserFolder.php - line 43:

OC\Files\Node\Root->get()

<<closure>>

OC\Files\Node\LazyUserFolder->OC\Files\Node\{closure}("*** sensiti ... *")

/var/www/nextcloud/lib/private/Files/Node/LazyFolder.php - line 69:

call_user_func()

/var/www/nextcloud/lib/private/Files/Node/LazyFolder.php - line 208:

OC\Files\Node\LazyFolder->__call()

/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Node.php - line 247:

OC\Files\Node\LazyFolder->getId()

/var/www/nextcloud/apps/text/lib/DAV/WorkspacePlugin.php - line 102:

OCA\DAV\Connector\Sabre\Node->getId()

/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

OCA\Text\DAV\WorkspacePlugin->propFind()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1052:

Sabre\DAV\Server->emit()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 984:

Sabre\DAV\Server->getPropertiesByNode()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1662:

Sabre\DAV\Server->getPropertiesIteratorForPath()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1647:

Sabre\DAV\Server->writeMultiStatus()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 346:

Sabre\DAV\Server->generateMultiStatus()

/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

Sabre\DAV\CorePlugin->httpPropFind()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 472:

Sabre\DAV\Server->emit()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 253:

Sabre\DAV\Server->invokeMethod()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 321:

Sabre\DAV\Server->start()

/var/www/nextcloud/apps/dav/lib/Server.php - line 352:

Sabre\DAV\Server->exec()

/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:

OCA\DAV\Server->exec()

/var/www/nextcloud/remote.php - line 166:

require_once("/var/www/ne ... p")
```

**Comment by ACGaming** [comment]
Can confirm this, most likely just a path parsing error in the code.

**Comment by jthomson-blackbird** [comment]
+1 on this issue still being in NextCloud 25.

**Comment by maurocampanelli** [comment]
I have this problem after upgrading to v.25.0.3 AND dist-upgrading ubuntu to 22.04.
Any workaroud?

**Comment by mattiasklu** [comment]
> Maybe you're missing php smbclient library? I had this problem after dist-upgrading from Ubuntu 20.04 and php 7.4 to Ubuntu to 22.04 and php 8.1 because library smbclient was missing in 7.4: I had to manually install it because there was no prebuilt package, so during dist upgrade the os had no knowledge about it and didn't install it. After installing package php8.1-smbclient the problem disappeared.

Installtion of package php8.1-smbclient solve the issue for me, i had issues were my SMB/CIFS did not index my sub directories. All sub directories was showing as files: still with Dr in the end.
![image](https://user-images.githubusercontent.com/49496850/216836778-613f3317-8dd9-49a8-a157-bfa70cea22a7.png)

**Comment by joshtrichards** [comment]
Hi @Flashbert - Thanks for the report.

Can you (or someone else experiencing this issue) provide the output of:

`./occ files_external:list --output=json_pretty`

I only need it for a mount experiencing this issue (9 in your original report if it's currently still configured in a way that is experiencing this issue or maybe you can configure a new temporary one, confirm the issue is still present, then run the above occ command).

**Please redact any credentials/private info**

Also, if possible, a full (raw) stack trace would be appreciated. The one that was included is the more limited one. A full one is available either directly from your `nextcloud.log` or from Admin->Logging by hovering to the right of a given log entry and clicking `Copy raw`.

Thanks.

**Comment by Flashbert** [comment]
Hi @joshtrichards,

seems like the problem is gone (probably with version 25). I didn't check on it since my last update and used my workarround.

Just tested again with a new share and only one subfolder and it worked, so problem is solved.

**Comment by pinkfloydFR** [comment]
If someone read this, i am experiancing exactly the same issue with NextCloud 30.0.2 !
