### ISSUE TITLE
[Bug]: 503 Service unavailable & update in process

### ISSUE THREAD

**Issue by Hannes77a** [nextcloud/server#33233]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello community,
we are using a Nextcloud server provided by owncube. Today we had synchronisation problems with one notebook which was logged in with admin rights. While figuring out what I problem was, I have noticed that there is an **update available**. So I started the update, but it crashed. I think it **got stuck at the point with synchronisation** stuff. I'm sorry for not being able to provide more specific details, but at this point I didn't know yet that this problem will actually become the real problem. So I figured out what the problem with the synchronisation was, but not **I couldn't log in anymore**. Any attempts from any device failed. In the browser it just says: 
"**update in process**".
![IMG_20220714_114703](https://user-images.githubusercontent.com/109282096/178972064-f1f05f75-812f-483a-a966-7933cac163a9.jpg)
No matter what browser I use nor which device I use. When trying to log in with the desktop client, it shows "**503 service unavailable**" and that **it cannot connect to the server**.
![IMG_20220714_114626](https://user-images.githubusercontent.com/109282096/178972054-b196df6a-19aa-404b-8e27-cd2217fe4c3c.jpg)

I searched in the forum here but couldn't find anything helpful, since I dont have enough information about the update process and I dont have enough IT knowledge. So I called the Nextcloud support, but they just redirected to this forum here and didnt want to help. 

So is there any way that I can restart the update and fully conduct it? When I try to get to the point in the desktop client where I started the update, I fail to reach this point, since I cannot login anymore. 

I'm very happy for any help since we cannot figure out how to resolve the problem with the update without have the Nextcloud support properly install the update for the server since they dont want to do this.

Kind regards,
Hannes

### Steps to reproduce

see description above with pictures

### Expected behavior

I expected to be able to login.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
I cannot login anymore to check this, but we just had the basic apps as far as I know.
```

**Comment by szaimen** [comment]
Hi, please ask your hoster for support on this

**Comment by Hannes77a** [comment]
> Hi, please ask your hoster for support on this

I already did in the meantime. And indeed, that could finish the update and now everything works again! Thank you!

**Comment by Hannes77a** [comment]
SOLVED:
The Problem was the hoster. They could finish the update and now everything works again.
