### ISSUE TITLE
Add C2 Object Storage to External Storage

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/server#33241]
https://c2.synology.com/en-global/object-storage/overview

Based on what i read you can also use the S3 API to connect to the storage. I tested it in my NC instance 24.0.3 RC2

![image](https://user-images.githubusercontent.com/59488153/179302502-cf28d256-dbf6-4ccf-8c8a-0e7c968c08d6.png)

Not sure if the Amazon S3 code can be copied and added for C2 storage

**Comment by solracsf** [comment]
As long as it is S3 compatible, i don't think we should create a specific API for it.
Otherwise, dozens of providers should be added too. 🤔

**Comment by andyxheli** [comment]
@solracsf thanks for the reply. I did some more reading on this. Im not sure if any of these things on the kb would have an effect on next S3 interface 
https://kb.synology.com/en-global/C2/tutorial/C2_Object_Storage_Compatible_API
