### ISSUE TITLE
I cannot get my custom raw camera preview app to bootstrap properly

### ISSUE THREAD

**Issue by cowai** [nextcloud/server#3325]
### Steps to reproduce
1. Install my app: https://github.com/cowai/CameraRawPreviews (needs imagick, exiv2)
2. Add "OCA\CameraRawPreviews\RawPreview" to "enabledPreviewProviders" array in config.
3. Navigate to a CR2 file (raw camera file)
4. Install latest gallery app (optional) to see the app is actually working.

### Expected behaviour
There should be a thumbnail for the CR2 file. 

### Actual behaviour
It just shows a generic one even though my app registers a provider for it.

The problem is that the PROPFIND request that files app gets, returns <nc:has-preview>false</nc:has-preview>. This value is determined by $PreviewManager->isAvailable(), which seems to also check for hard coded mimetypes. Adding CR2 mimetype inside PreviewManager.php makes the problem go away, but this is hacky and there should be a better way.

I am using this for bootstrapping my preview class:
`$container->getServer()->query('PreviewManager')->registerProvider('/image\/x-dcraw/', function() { return new \OCA\CameraRawPreviews\RawPreview; });`

Is this a kind of race condition or maybe my app is never bootstrapped during the PROPFIND request?

**Comment by MorrisJobke** [comment]
It could be that the bootstrapping happens too late?! cc @rullzer @oparoz

**Comment by cowai** [comment]
With some logging turned on I can confirm that my app is only bootstrapped in getstoragestats.php and not PROPFIND "remote.php/webdav/". So it seems it is never loaded in the webdav requests.

**Comment by cowai** [comment]
With some more checking the core code. I see that OC_App::loadApps(array("filesystem")) is ran before the webdav stuff. So when I added "filesystem" as a type in my info.xml it seems to work :)

**Comment by cowai** [comment]
an idea would be to have a new type for apps "previewprovider" or something. And then explicably load those apps in PreviewManager if not loaded.

**Comment by oparoz** [comment]
>So when I added "filesystem" as a type in my info.xml it seems to work :)

Yes, that's the right way to add DAV access to apps :)

>an idea would be to have a new type for apps "previewprovider" or something. And then explicably load those apps in PreviewManager if not loaded.

Please open a new issue for that to make it possible for others to discuss the idea, thanks.
