### ISSUE TITLE
"Edit locally" option

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#33275]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Find a file online that you want to open on your PC with a specific program.

**Describe the solution you'd like**
- user is in web UI
- finds a file and wants to open it locally (e.g. Collabora is not sufficient, Inkscape for SVG, etc.)
- user clicks "edit locally"
- special link type (tbd: nc://open/$account@Server/$remotePath)
- file is opened on Desktop

**Describe alternatives you've considered**
Doing it manually

**Additional context**
Desktop implementation: https://github.com/nextcloud/desktop/issues/4297

@PVince81 for scheduling
(Desktop side can work on it right now without delay, so there is no rush)

**Comment by PVince81** [comment]
this would require detecting that the browser is running on mobile and only show those entries in that case

cc @jancborchardt

**Comment by PVince81** [comment]
and, should that link appear for all file types or only specific mime types ? if the latter, should it be configurable on the server side ?

**Comment by tobiasKaminsky** [comment]
> this would require detecting that the browser is running on mobile and only show those entries in that case

No, this is not about mobile at all.
It is only about Desktop.

**Comment by tobiasKaminsky** [comment]
> and, should that link appear for all file types or only specific mime types ? if the latter, should it be configurable on the server side ?

I say for all, as this is basically "only" a convenient shortcut so that user do not have to navigate manually to the desired file.

**Comment by PVince81** [comment]
so if the desktop client is not installed the browser will complain about an unknown link.
or is there a way to have that link redirect to a download page

**Comment by JojoBr0** [comment]
The "Edit locally" option is not shown in the right click menu

Ref: https://github.com/nextcloud/files_rightclick/issues/147
