### ISSUE TITLE
index.php showing in URL after migration from OC 9.1 to NC 10.0.3

### ISSUE THREAD

**Issue by cuthulino** [nextcloud/server#3328]
On my OC installation before, the index.php was completely hidden in the URLs.
After migrating (like it is written in the manual) nextcloud does not hide it anymore.
I already checked the config.php, 'htaccess.RewriteBase' => '/', is in there.
Also i ran the occ command to generate the htaccess  and restarted apache but nothing changed.

php ist version 7.0
modrewrite and modenv are enabled in apache

**Comment by MorrisJobke** [comment]
This seems to be a setup issue, please use the forums for this. Also provide the htaccess file there. You maybe want to check the `AllowOverride` setting in you apache config, because this is needed by Apache to read the values from htaccess.
