### ISSUE TITLE
[Bug]: Create User with DisplayName = Username does not work anymore

### ISSUE THREAD

**Issue by maxemann96** [nextcloud/server#33284]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

With the release of nextcloud 23.0.2 it is not possible anymore to create a user with the username equal to the displayName. This was introduced by checking that the edit of the displayName works [[here](https://github.com/nextcloud/server/commit/c0868f93f1175c32379f6e64b245b724c40478be#diff-388d86396b3a70ff465e035b0db5d78bce90716631ab322d00425fbb317042ebR840)]. The edit is not successfull, because it is checked that the old displayName - which fallbacks to the username - is not equal to the new displayName. 

### Steps to reproduce

Start a docker container with the newest release of nextcloud, for example with the following `docker-compose.yml`:
```
version: '3'
services:
  nextcloud:
    image: nextcloud:24.0.3
    environment:
      NEXTCLOUD_ADMIN_USER: "ncadmin"
      NEXTCLOUD_ADMIN_PASSWORD: "ncadminsecret"
      NEXTCLOUD_TRUSTED_DOMAINS: "127.0.0.1 localhost nextcloud"
      SQLITE_DATABASE: nctest
    ports:
      - "127.0.0.1:8080:80"
```
Then login with the admin user and try to [create](http://127.0.0.1:8080/settings/users) a new user with username: _user_, displayname: _user_, a mail and a password.

### Expected behavior

The user gets created with no error message.

### Installation method

Official Docker image

### Operating system

Other

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

SQlite

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "127.0.0.1",
            "localhost",
            "nextcloud"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "24.0.3.2",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - groupfolders: 12.0.1
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"dnja5ranAwyfLfW22cZb","level":2,"time":"2022-07-19T22:32:40+00:00","remoteAddr":"172.19.0.1","user":"ncadmin","app":"ocs_api","method":"POST","url":"/ocs/v2.php/cloud/users","message":"Failed addUser attempt with ocs exeption.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0","version":"24.0.3.2","exception":{"Exception":"OCP\\AppFramework\\OCS\\OCSException","Message":"Invalid displayname","Code":102,"Trace":[{"file":"/var/www/html/apps/provisioning_api/lib/Controller/UsersController.php","line":429,"function":"editUser","class":"OCA\\Provisioning_API\\Controller\\UsersController","type":"->","args":["*** sensitive parameters replaced ***","display","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"addUser","class":"OCA\\Provisioning_API\\Controller\\UsersController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Provisioning_API\\Controller\\UsersController"},"addUser"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Provisioning_API\\Controller\\UsersController"},"addUser"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Provisioning_API\\Controller\\UsersController","addUser",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},["ocs.provisioning_api.Users.addUser"]]},{"file":"/var/www/html/ocs/v1.php","line":62,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/cloud/users"]},{"file":"/var/www/html/ocs/v2.php","line":23,"args":["/var/www/html/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/apps/provisioning_api/lib/Controller/UsersController.php","Line":841,"message":"Failed addUser attempt with ocs exeption.","exception":{},"CustomMessage":"Failed addUser attempt with ocs exeption."}}
```

**Comment by Alwaysin** [comment]
We are also affected on 23.0.7.

**Comment by leviia** [comment]
We are also affected by this bug 

All the best

**Comment by ff0255** [comment]
I'm also affected on nextcloudpi rock64 board NC23.0.9
Error="Invalid displayname" when trying to create user with DisplayName = Username.

**Comment by maxemann96** [comment]
I also do not know if this problem leads to any side effects on the created users. Can for example @Pytal or @nickvergessen  clarify whether the users which were created could be possible broken, since the creation process is aborted, but not rolled back? Or can you confirm this behaviour as a bug?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/blob/253c0641b138d6eeb4397f82ba3738d9adb132a2/lib/private/User/Database.php#L220

Seems it is now blocked when the display name is longer than 64 characters.

That being said, false is also returned when the user did not exist before. So that could be related:
https://github.com/nextcloud/server/blob/a0f5aebb89da4f18b37026e72e543bbe66b32980/lib/private/User/Database.php#L236

Maybe the userExists() state is not reset correctly.

**Comment by wargarblgarbl** [comment]
Confirming that this is still present in 24.0.7

If users are created and the in the interface when adding a user you set the display name and the username to the same string - the user will create (occasionally with an error), but then the user attempting to log in will get all sorts of weird issues, occasionally server 500 errors on the web side, but mobile clients being able to log in. 

Workaround solution for creating users: Create users setting nothing in the displayname parameter.

**Comment by szaimen** [comment]
Hi, please update to 25.0.7 or better 26.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 26-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by maxemann96** [comment]
Seems to work now in at least 26.0.2 and 27.0.0.

**Comment by szaimen** [comment]
Thanks for verifying!
