### ISSUE TITLE
OCP\Files\NotPermittedException: Could not create folder %PHP	Error: Trying to access array offset on value of type null at /var/www/nextcloud/apps/dav/lib/CalDAV/BirthdayService.php#306

### ISSUE THREAD

**Issue by wboy87** [nextcloud/server#33312]
### Steps To Reproduce

Installing Nextcloud using manul https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/bj0vl4ahv0jgrmfm0950/build-your-own-nextcloud-vm

### Expected Result

Everything working without any problem

### Actual Result

Error	index	OCP\Files\NotPermittedException: Could not create folder

    /var/www/nextcloud/lib/private/Files/AppData/AppData.php - line 156:

    OC\Files\Node\Folder->newFolder()

    /var/www/nextcloud/apps/theming/lib/ImageManager.php - line 163:

    OC\Files\AppData\AppData->newFolder()

    /var/www/nextcloud/apps/theming/lib/ImageManager.php - line 178:

    OCA\Theming\ImageManager->getCacheFolder()

    /var/www/nextcloud/apps/theming/lib/Controller/IconController.php - line 90:

    OCA\Theming\ImageManager->getCachedImage()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 225:

    OCA\Theming\Controller\IconController->getThemedIcon()

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 133:

    OC\AppFramework\Http\Dispatcher->executeController()

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 172:

    OC\AppFramework\Http\Dispatcher->dispatch()

    /var/www/nextcloud/lib/private/Route/Router.php - line 298:

    OC\AppFramework\App::main()

    /var/www/nextcloud/lib/base.php - line 1023:

    OC\Route\Router->match()

    /var/www/nextcloud/index.php - line 36:

    OC::handleRequest()

Error	PHP	    Error: Trying to access array offset on value of type null at /var/www/nextcloud/apps/dav/lib/CalDAV/BirthdayService.php#306

    /var/www/nextcloud/apps/dav/lib/CalDAV/BirthdayService.php - line 306:

    OC\Log\ErrorHandler::onError()

    /var/www/nextcloud/apps/dav/lib/BackgroundJob/GenerateBirthdayCalendarBackgroundJob.php - line 70:

    OCA\DAV\CalDAV\BirthdayService->resetForUser()

    /var/www/nextcloud/lib/public/BackgroundJob/Job.php - line 79:

    OCA\DAV\BackgroundJob\GenerateBirthdayCalendarBackgroundJob->run()

    /var/www/nextcloud/lib/public/BackgroundJob/QueuedJob.php - line 47:

    OCP\BackgroundJob\Job->execute()

    /var/www/nextcloud/cron.php - line 151:

    OCP\BackgroundJob\QueuedJob->execute()										 

### Build Version

Nextcloud 24.0.2

### Environment

By using the scripts

### Environment Details

Ubuntu 22.04 LTS, 4xCPU, 4GB ram

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
