### ISSUE TITLE
Content blocked by Security Gateway

### ISSUE THREAD

**Issue by schnello** [nextcloud/server#3332]
Hello.

I update my Nextcloud Server from 11.0.0 to 11.0.1
After this update the Security Gateway blocks some content (see attached log) and the loginpage didnt load.

Is the "Security Gateway" too extremely adjusted or is it realy a security risk?

Br,
Christian

[1485779291148.txt](https://github.com/nextcloud/server/files/741422/1485779291148.txt)

**Comment by nickvergessen** [comment]
@LukasReschke any idea?

**Comment by Flole998** [comment]
You just configured your security gateway wrong. It doesn't want nextcloud to load stylesheets or js from other hosts, but at least in your installation that is required for some reason. Either configure that thing properly or disable it if you do not know how to use it. This is not an issue with nextcloud.
