### ISSUE TITLE
[Bug]: A folder created inside the current folder in the modal window of file transfer won't appear

### ISSUE THREAD

**Issue by piiskop** [nextcloud/server#33323]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Every time i want to move files into a new folder that must reside in the current folder, after creation of the new folder in the file transfer modal window and closing the modal window the list of the current folder won't updated and the newly created folder will be invisible until a manual refresh will be done.

### Steps to reproduce

1. i go into _Files_.
2. i choose a file for moving/copying.
3. In _Choose the target folder_, i click _+_ and create the new folder.
4. i command the file chosen in the step _2_ to be moved into the folder created in the step _3_.
5. The modal window for moving/copying files disappears, an animated circle will be displayed on the file mentioned in the step _2_ and then that file disappears.
6. See that the folder created in the step _3_ isn't visible!

### Expected behavior

i expect the newly created folder to be visible right after moving/copying without a manual refresh.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.3

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
kalmer@test:~$ sudo -u www-data php occ config:list system
[sudo] password for kalmer: 
Could not open input file: occ
kalmer@test:~$ php occ config:list system
Could not open input file: occ
kalmer@test:~$ ./occ config:list system
-bash: ./occ: No such file or directory
```

### List of activated Apps

```shell
kalmer@test:~$ sudo -u www-data php occ app:list
Could not open input file: occ
kalmer@test:~$ php occ app:list
Could not open input file: occ
kalmer@test:~$ ./occ app:list
-bash: ./occ: No such file or directory
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
"/settings/admin/logging" shows a white subpage.

the log: https://nextcloud.tennis24.ee/index.php/s/jNCcpgiedcagJL3
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by piiskop** [comment]
The issue still exists in "25.0.3".

**Comment by skjnldsv** [comment]
cc @susnux, I guess you fire a `files:node:created` event from the new file picker?

**Comment by susnux** [comment]
@skjnldsv
> I guess you fire a files:node:created event from the new file picker?

Nope, just creating the new directory on server using WebDAV and reloading the current directory content for validation.
Quick search shows that is is required on the files app to show the folder properly, so this is a issue with the dialogs package.
Adding it to the todo list :writing_hand:

**Comment by susnux** [comment]
Already fixed in all supported versions
