### ISSUE TITLE
[Bug]: Wrong icon on shared files in navigation on hover

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/server#33328]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Wrong icon and style on hover the shared files link in the left navigation

See this little animation:
![Animation](https://user-images.githubusercontent.com/1473674/180602957-a48b03fa-20ca-49d1-b917-3d49e01bde8f.gif)

### Steps to reproduce

1. Hover the left menu
2. item shared has a wrong icon and wrong style on hover

### Expected behavior

right hover effect and correct icon

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
default apps with:
- LDAP
- Decks
- Calendar
- Talk
- Polls
- Activity
```

**Comment by asheerrizvi** [comment]
I can check this out, can you assign this to me? @Dennis1993

**Comment by asheerrizvi** [comment]
@Dennis1993 something else came up so won't be able to pick this up for some days. I am unassigning myself from the issue. 😢

**Comment by codesmith25103** [comment]
I could check this out. Assign me this issue.

**Comment by codesmith25103** [comment]
I am new to Open source. Can you guide me how to set up environment

**Comment by VincentWoglo** [comment]
codesmith, were you able to fix it?

**Comment by ChiragSharma0208** [comment]
Can you assign this to me so that I can look into it? @Dennis1993

**Comment by VincentWoglo** [comment]
Can you assign this to me? Also is the new icon you already in a folder

**Comment by franzudev** [comment]
![](https://user-images.githubusercontent.com/28902523/193451943-a47fd3b4-b9d0-4cf3-8d13-dccfe9b6a1d9.png)

You're sure this is a bug? The share element is a dropdown, unlike other links. imho it's correct that shows the triangle

**Comment by Ayushbajpai19** [comment]
I would like to take this issue for hacktoberfest

**Comment by lhsazevedo** [comment]
I agree with @franzudev, looks like this is the intended appearance.

**Comment by szaimen** [comment]
This got improved with nc26 so I'd say lets close this as it is indeed the inteded behaviour.
