### ISSUE TITLE
[Bug]: left sidebar on mobile browser

### ISSUE THREAD

**Issue by FALErwi** [nextcloud/server#33333]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When you access to your nextcloud from mobile browser, in the left side bar
 In the file app when you choose all files or recent or favourite and so on, the slide
Closed automatically and this is good when you browsing on small screen size like mobile.
So this should be available on all application that had left side bar.

Like Photos, email, Talk, Contacts, Calender ... etc

[https://drive.google.com/file/d/1cbgldiYYMRHXxxKzDXVst4zhjXLUr-V8/view?usp=drivesdk](url)

[https://drive.google.com/file/d/1cTsSGdpf6u7sD_lo4Us19wZbO2liwURa/view?usp=drivesdk](url)

### Steps to reproduce

1. Open the nextcloud server site from mobile browser 
2. Go to files and click on all file or any option you have there 
3
4. The left side close automatically but the other apps not.

### Expected behavior

Please check the description and the videos

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
It is not BackEnd issue, it is frontend enhancement
```

### List of activated Apps

```shell
It is not BackEnd issue, it is frontend enhancement
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
