### ISSUE TITLE
[Bug]: HTML file is downloaded as plain text in Firefox 91.8.0 ESR

### ISSUE THREAD

**Issue by Mer0me** [nextcloud/server#33362]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

HTML files can't be viewed in nextcloud for security reasons, so we must download and open them with a browser. It works under Chrome, but not in Firefox (91.8.0esr) where the file is downloaded and viewed in firefox as plain text

![image](https://user-images.githubusercontent.com/6248852/181019558-c0c8a7a0-38a4-4bab-a8ce-78913351bf07.png)

![image](https://user-images.githubusercontent.com/6248852/181019653-a19b950a-6e69-41da-9d67-e2516141d418.png)

![image](https://user-images.githubusercontent.com/6248852/181019807-004f235c-634a-4f45-979b-61ae6b716a17.png)

### Steps to reproduce

1. Place a .html file in nextcloud
2. Click on the download button to view it
3. Pick Firefox as html file viewer
4. See the HTML code and not the html file rendered (the downloaded file is named RandomFile.html.txt)

### Expected behavior

Firefox should render the html file as Chrome do.

### Installation method

Manual installation

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.agglo-montbeliard.fr",
            "192.168.50.106",
            "192.168.50.106"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.agglo-montbeliard.fr\/",
        "dbtype": "mysql",
        "version": "24.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "trashbin_retention_obligation": "auto, 15",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "25",
        "mysql.utf8mb4": true,
        "default_phone_region": "FR",
        "has_rebuilt_cache": true,
        "app_install_overwrite": [
            "spreed",
            "files_mindmap",
            "pdfdraw",
            "issuetemplate",
            "files_linkeditor",
            "files_texteditor"
        ],
        "allow_local_remote_servers": true,
        "default_language": "fr",
        "force_language": "fr",
        "default_locale": "fr_FR",
        "force_locale": "fr_FR",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "preview_max_memory": 512
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - analytics: 4.3.1
  - announcementcenter: 6.3.1
  - calendar: 3.4.2
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.2.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - deck: 1.7.1
  - event_update_notification: 1.5.0
  - external: 4.0.0
  - extract: 1.3.5
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_automatedtagging: 1.14.0
  - files_downloadactivity: 1.13.0
  - files_external: 1.16.1
  - files_linkeditor: 1.1.11
  - files_markdown: 2.3.6
  - files_mindmap: 0.0.26
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_texteditor: 2.14.0
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - files_zip: 1.1.2
  - forms: 2.5.1
  - groupfolders: 12.0.1
  - impersonate: 1.11.0
  - issuetemplate: 0.7.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - notify_push: 0.4.0
  - oauth2: 1.12.0
  - onlyoffice: 7.5.2
  - password_policy: 1.14.0
  - photos: 1.6.0
  - polls: 3.7.0
  - provisioning_api: 1.14.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - smb_test: 0.3.4
  - spreed: 14.0.3
  - systemtags: 1.14.0
  - tasks: 0.14.4
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_totp: 6.4.0
  - updatenotification: 1.14.0
  - user_ldap: 1.14.1
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - bruteforcesettings: 2.2.0
  - calendar_resource_management: 0.1.0
  - customproperties: 2.0.4
  - emlviewer: 1.0.0
  - encryption
  - firstrunwizard: 2.12.0
  - group_everyone: 0.1.10
  - pdfdraw
  - privacy: 1.7.0
  - recommendations: 1.3.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - text: 3.5.1
  - workflow_script: 1.8.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
not relevant
```

### Additional info

On the network console of Chrome, the file type is "document".
On the network console of Firefox, the file type is "plain".
A newer version of Firefox solves the problem, but a new profile on Firefox 91.8 ESR won't

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by Mer0me** [comment]
Cannot reproduce bug with newer version of Firefox. Closing this one.
