### ISSUE TITLE
occ user:delete doing only half the job!?

### ISSUE THREAD

**Issue by matrixdesert** [nextcloud/server#3337]
Hello!

I'm running NC 11.0.1 (Updated from NC 10.0).
I tried to delete some users with occ user:delete - i think there is a little flaw...

When a user is deleted using "occ user:delete" the user will be deleted from DB-Table "oc_preferences".
But there are still entries in DB-Table "oc_accounts" regarding the deleted userid.

Best regards!

**Comment by marncz** [comment]
Would like to pick up that issue, so far I have found this function along with preDelete and postDelete:

https://github.com/nextcloud/server/blob/master/lib/private/User/User.php#L196

on what level should deletion of the entry from oc_accounts table occur?

**Comment by skjnldsv** [comment]
Fix in https://github.com/nextcloud/server/pull/4871
