### ISSUE TITLE
[Bug]: SEARCH returns wrong href for favorited files

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#33402]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description
- this happens on latest NC master
- have an incoming shared file (!)
- make this a favorited file
- do webdav SEARCH
- see as 207 response:
```
<?xml version="1.0"?>
<d:multistatus
	xmlns:d="DAV:"
	xmlns:s="http://sabredav.org/ns"
	xmlns:oc="http://owncloud.org/ns"
	xmlns:nc="http://nextcloud.org/ns">
	<d:response>
		<d:href>/nc/remote.php/dav/files/test4/IMG_20211116_074501.jpg/</d:href>
		<d:propstat>
			<d:prop>
				<d:getcontenttype>image/jpeg</d:getcontenttype>
				<d:resourcetype/>
				<d:getcontentlength>200166</d:getcontentlength>
				<d:getlastmodified>Mon, 13 Dec 2021 08:41:32 GMT</d:getlastmodified>
				<d:creationdate>1970-01-01T00:00:00+00:00</d:creationdate>
				<d:getetag>&quot;51dd88987e4e7404abacb9c75cb7f1f0&quot;</d:getetag>
				<nc:sharees/>
				<oc:permissions>SG</oc:permissions>
				<oc:id>00233625ocjycgrudn78</oc:id>
				<oc:size>200166</oc:size>
				<oc:favorite>1</oc:favorite>
			</d:prop>
			<d:status>HTTP/1.1 200 OK</d:status>
		</d:propstat>
		<d:propstat>
			<d:prop>
				<d:displayname/>
				<d:quota-used-bytes/>
				<d:quota-available-bytes/>
			</d:prop>
			<d:status>HTTP/1.1 404 Not Found</d:status>
		</d:propstat>
	</d:response>
</d:multistatus>
```

--> href has a trailing "/" although it is a file

Webdav request is:
```
curl --request SEARCH \
  --url http://localhost/nc/remote.php/dav \
  --header 'Content-Type: text/xml' \
  --header 'OCS-APIRequest: true' \
  --data '<?xml version="1.0" encoding="UTF-8"?>
<d:searchrequest xmlns:d="DAV:" xmlns:oc="http://nextcloud.com/ns">
		<d:basicsearch>
			<d:select>
				<d:prop>
					<d:displayname/>
					<d:getcontenttype/>
					<d:resourcetype/>
					<d:getcontentlength/>
					<d:getlastmodified/>
					<d:creationdate/>
					<d:getetag/>
					<d:quota-used-bytes/>
					<nc:sharees xmlns:nc="http://nextcloud.org/ns"/>
					<d:quota-available-bytes/>
					<oc:permissions xmlns:oc="http://owncloud.org/ns"/>
					<oc:id xmlns:oc="http://owncloud.org/ns"/>
					<oc:size xmlns:oc="http://owncloud.org/ns"/>
					<oc:favorite xmlns:oc="http://owncloud.org/ns"/>
				</d:prop>
			</d:select>
			<d:from>
				<d:scope>
					<d:href>/files/test4</d:href>
					<d:depth>infinity</d:depth>
				</d:scope>
			</d:from>
			<d:where>
				<d:eq>
					<d:prop>
						<oc:favorite xmlns:oc="http://owncloud.org/ns"/>
					</d:prop>
					<d:literal>yes</d:literal>
				</d:eq>
			</d:where>
			<d:orderby/>
	</d:basicsearch>
</d:searchrequest>'
```

### Steps to reproduce

see above

### Expected behavior

No trailing "/" on files, only on folders.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
/
```

**Comment by tobiasKaminsky** [comment]
This is also reproducible on NC24.
@szaimen shall I add another label? It is a serious regression.

**Comment by szaimen** [comment]
added the 24 tag for you 👍

**Comment by szaimen** [comment]
Also cc @PVince81 then

**Comment by tobiasKaminsky** [comment]
Also in NC23.

**Comment by tobiasKaminsky** [comment]
Also in NC16.

**Comment by szaimen** [comment]
> Also in NC16.

Seems like this is then maybe actually intwntional?

**Comment by tobiasKaminsky** [comment]
I also thought about it, but I cannot imagine why.
The href is a path to file/folder, and like on UNIX, we use this in clients to differentiate between files and folders.
Right now it is like this:
- "/test.jpg" when not shared, SEARCH
- "/test.jpg" when not shared, PROPFIND
- "/test.jpg/" when shared, SEARCH
- "/test.jpg" when shared, PROPFIND

This cannot be intentional…

**Comment by tobiasKaminsky** [comment]
Also for background:
as this are then two different paths, Android/clients handle this as two different files.

**Comment by tobiasKaminsky** [comment]
I created an Android library test for this case: https://github.com/nextcloud/android-library/pull/942

**Comment by PVince81** [comment]
in theory you should use the resourcetype to see if it's a folder or not

but using href is a possible shortcut

I had a quick look at TagsPlugin but couldn't find where the result set is built as I'm not familiar with the search code.

Usually the href is built by SabreDAV itself based on the path. Strange that it would append a slash even though the resource type is not "collection".

@icewind1991 @CarlSchwan do you have pointers to the code in question ?

**Comment by solracsf** [comment]
Closed by https://github.com/nextcloud/server/pull/33734
