### ISSUE TITLE
[Bug]: Server folders named xxx/bin are reported as 404 not found 

### ISSUE THREAD

**Issue by bowanner** [nextcloud/server#33400]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I have several folders named /bin, xxx/yyy/bin on both server and locally. When the Windows Desktop Client tries to sync any such folder, the server responds with 404.

Using web interface, clicking on such "bin" server folder just brings me back to the parent folder.

Looking at the server file system, there definitely is a "bin" folder, with files or subfolders. But it does not seem reconized by Nextcloud.

Trying to create a subfolder named "bin" thru the web page interface server responds with "Could not create folder bin" 

### Steps to reproduce

1. On web interface open a folder on the root, try to create a folder named "bin"
2. If a folder named "bin" exists in Nextcloud user file system structure (thru previous disk bulk update and occ files:scan --all )
that folder is visible in the web interface, but clicking on it just returns to the parent folder.  
3. Local "bin" folders on Windows PC can't be synched to server. Server responds with 404 Not found for that bin folder, even if it is visible in the web interface, and exists in the Nextcloud user file system 

### Expected behavior

"bin" folders should be treated  as ANY other folder. They are widely used in many situations and structures that I want to sync to Nextcloud, exactly like in OneDrive, etc

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "log_type": "file",
        "logfile": "\/var\/snap\/nextcloud\/current\/logs\/nextcloud.log",
        "logfilemode": 416,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.16",
            "mydomain.net",
            "www.mydomain.net",
            "192.168.0.15"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.3.2",
        "overwrite.cli.url": "https:\/\/mydomain.net",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "loglevel": 2,
        "overwritehost": "mydomain.net"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - twofactor_backupcodes: 1.13.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - theming: 1.13.0
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by bowanner** [comment]
When I filed this bug report, I thoroughlly filled in a number of questions that are now set as "No response". Weird.
Using default Snap for Nextcloud on Ubuntu  (Intel x64) when installing virtual machine on Windows (11) Hyper-V
apache
mysql
php 8.0.x
No encryption
Fresh install, but user files and folders bulk copied to Nextcloud, occ updated

**Comment by bowanner** [comment]
Please see https://github.com/nextcloud-snap/nextcloud-snap/issues/2093

**Comment by bowanner** [comment]
Ping, anyone?

**Comment by joshtrichards** [comment]
I cannot reproduce this on v24-v26. Can you provide the actual web server and Nextcloud log entries where you're seeing these 404s?

Any chance there is some other filtering happening prior to the NC server (i.e. an upstream proxy)?

**Comment by szaimen** [comment]
Hi, please update to 25.0.7 or better 26.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 26-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
