### ISSUE TITLE
[Bug]: Password reset takes wrong IP

### ISSUE THREAD

**Issue by immomagic** [nextcloud/server#33403]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Password-reset on the login page

When we are resetting a password in the local network (same where the nextcloud server is integrated) we can use the function as it is meant to be. With the input of the mail and by clicking "reset password" the mail is automatically generated and we can click the link in the email `(https://**OUR_NEXTCLOUD_URL**/lostpassword/reset/form/yudEAc9h7zswjOlZXLInY/**USERNAME**)`
If we are **NOT CONNECTED** to the local network the password-reset does **NOT WORK**!
The CTA button in the automatically generated mail we get, takes the local nextcloud IP instead of the public domain.
`(https://**192.168.XX.XXX**/lostpassword/reset/form/ECgifHkRIdTLmLaWrfynd/**USERNAME**)`

### App "Guests" in version 2.2.0

By inviting guests via emailadress to a folder they get an email with the CTA "activate profile" (= password re/set)
This form is the same as the normal password-reset function and acts like described above.
Inside our local network everything works like a charm.
Now there are two scenarios:
1. **Host connected to local network, guest connected to different wifi**
CTA Button in the mail works
`(https://**OUR_NEXTCLOUD_URL**/lostpassword/reset/form/yudEAc9h7zswjOlZXLInY/**USERNAME**)`
Guest enters password, clicks on "reset password"
--> `network Error` <img width="300" src="https://user-images.githubusercontent.com/110220052/181720380-3af0ff9a-21fe-49c7-b261-77bbc24301b9.png">
2. **Host connected to different wifi, guest connected to different wifi**
CTA Button in the mail is broken (local IP)
`(https://**192.168.XX.XXX**/lostpassword/reset/form/ECgifHkRIdTLmLaWrfynd/**USERNAME**)`
Button simply not working for the guest

### Steps to reproduce

1. Be sure to be not connected to the local network where your nextcloud is integrated
2. reset your password
3. look at the hyperlink in the automatically gernerated email, it show the nextcloud local IP instead of the public domain

### Expected behavior

The CTA button inside the password-reset mail or the guest-invitation should always link to the public domain and not to the local IP. Also the Guest-invitation form should not show a network error when entering the new password.

### Installation method

Official VM scrips

### Operating system

Ubuntu 20.4

### PHP engine version

7.4

### Web server

Apache

### Database engine version

MySQL

### Are you using the Nextcloud Server Encryption module?

Encyrption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "OUR_NEXTCLOUD_URL",
            "192.168.XX.XXX",
            "nextcloud",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "24.0.3.2",
        "overwrite.cli.url": "**OUR_NEXTCLOUD_URL**",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 0,
        "auth.webauthn.enabled": false,
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "mail_smtpmode": "smtp",
        "logtimezone": "Etc\/UTC",
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "skeletondirectory": "",
        "theme": "",
        "updater.release.channel": "stable",
        "htaccess.RewriteBase": "\/",
        "default_language": "de_DE",
        "default_phone_region": "DE",
        "force_language": "de_DE",
        "simpleSignUpLink.shown": false,
        "mail_template_class": "OCA\\EmailTemplateExample\\EMailTemplate",
        "overwriteprotocol": "https",
        "app_install_overwrite": [
            "email_template_example",
            "files_external_onedrive"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.16.0
  - cfg_share_links: 2.0.0
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - contacts: 4.2.0
  - contactsinteraction: 1.5.0
  - dav: 1.22.0
  - electronicsignatures: 2.0.1
  - email_template_example: 0.0.1
  - external: 4.0.0
  - federatedfilesharing: 1.14.0
  - files: 1.19.0
  - files_accesscontrol: 1.14.0
  - files_downloadactivity: 1.13.0
  - files_external: 1.16.1
  - files_fulltextsearch: 24.0.1
  - files_fulltextsearch_tesseract: 24.0.0
  - files_mindmap: 0.0.26
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - guests: 2.2.0
  - impersonate: 1.11.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - permissions_overwrite: 0.1.7
  - provisioning_api: 1.14.0
  - quota_warning: 1.14.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - side_menu: 2.4.2
  - smb_test: 0.3.4
  - systemtags: 1.14.0
  - theming: 1.15.0
  - theming_customcss: 1.11.0
  - twofactor_backupcodes: 1.13.0
  - unroundedcorners: 1.0.3
  - updatenotification: 1.14.0
  - viewer: 1.8.0
  - workflowengine: 2.6.0
Disabled:
  - accessibility: 1.8.0
  - admin_audit: 1.12.0
  - announcementcenter: 6.3.1
  - collectives: 1.3.0
  - comments: 1.12.0
  - dashboard: 7.2.0
  - encryption
  - federation: 1.12.0
  - files_trashbin: 1.12.0
  - firstrunwizard: 2.11.0
  - fulltextsearch: 23.0.0
  - nextcloud_announcements: 1.11.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - recommendations: 1.1.0
  - registration: 1.5.0
  - sharebymail: 1.12.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - text: 3.5.1
  - user_ldap
  - user_status: 1.2.0
  - weather_status: 1.2.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional info

Our nextcloud 24.0.3 is running on Ubuntu 20.04

**Comment by CarlSchwan** [comment]
Make sure to set overwrite.cli.url See https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#proxy-configurations

**Comment by immomagic** [comment]
Hello, this does not work. The routing is still false.

**Comment by immomagic** [comment]
I have another problem now... it seems, that the direct document-links i provide to people dont work.
If I send one, the domain is overwritten with the local ip. That means, in our local network everything works, if i send the link to someone else they can not download the desired document.

Any suggestions?

**Comment by immomagic** [comment]
hello, I still have the problem, that links generated for mails take the local IP instead of the public domain.
My users can not:

- reset a password
- initial set a password (guests app)
- can not be provided with shared documents links

I have set up a new Nextcloud and tested this - it does not work! Am i the only one with this problem?
