### ISSUE TITLE
[Bug]: Rename file in Filesystem and occ scan don't execute flows again.

### ISSUE THREAD

**Issue by ChR-iSz** [nextcloud/server#33424]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If i rename files in Filesystem (need for special characters on further processes) and execute `occ files:scan  --path="MyUserName/files"` activated flows will not execute again.

### Steps to reproduce

1. Create a Flow
2. Upload a file in nextcloud.
3. Rename file in Filesystem
4. run files:scan for the folder which renamed file 

### Expected behavior

Flow execution for the new 'renamed' file.

### Installation method

Other

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.2.1",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "app_install_overwrite": [
            "workflow_script"
        ],
        "log_type": "file",
        "logtimezone": "Europe\/Berlin",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": 2,
        "maintenance": false,
        "theme": ""
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - bruteforcesettings: 2.4.0
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_automatedtagging: 1.14.0
  - files_pdfviewer: 2.5.0
  - files_retention: 1.13.1
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflow_script: 1.8.0
  - workflowengine: 2.6.0
Disabled:
  - activity: 2.16.0
  - admin_audit
  - encryption
  - files_external
  - photos: 1.6.0
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by PVince81** [comment]
this is not supported, there is no way for the file scan to detect that a file got renamed/moved directly on the filesystem

in general it is not recommended to touch the filesystem directly, you should always go through Nextcloud and its APIs for everything to be able to work properly.

**Comment by ChR-iSz** [comment]
Ok. Can i move the File via API, which re-trigger the flow automatically ?

**Comment by PVince81** [comment]
@ChR-iSz if the file is already in the storage, you can use curl with the user's credential.
on the top of my head it might look like this:

`curl -u userid:password -X MOVE -H Destination: https://domain.tld/remote.php/webdav/path/to/destination-file.txt https://domain.tld/remote.php/webdav/path/to/source-file.txt` (not tested)

**Comment by ChR-iSz** [comment]
@PVince81 Thanks again... 👍
