### ISSUE TITLE
[Bug]: missing time zone and wrong language in download info mail 

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/server#33427]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

NC 24.0.2
Downloads using a public link trigger this EMail:

<img width="240" alt="20220802 080621 Inbox - Unified Folders" src="https://user-images.githubusercontent.com/6248560/182254302-8a3e7090-eb58-4cf1-8f30-e5f695be7aae.png">

- IMO the TZ Info should be added to make the massage usable for travellers 
- The text is in German instead of English.

### Steps to reproduce

1. download via public link

### Expected behavior

add TZ info and use correct language (of the recipient of the mail)

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
as I use a SAAS installation I can not access the command line
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
