### ISSUE TITLE
Feature Request - directly mount external storage as home directory

### ISSUE THREAD

**Issue by zikona** [nextcloud/server#3343]
Hello:

I was wondering if I can submit a Feature Request to directly mount external storage as home directory. For example a group of users will be presented with external storage that is shared among all members of this group. This way, anything that is uploaded or shared out would be visible by group members.

My version of NC is 11.0.1.

If there is already a feature like this, my apologizes.

**Comment by MorrisJobke** [comment]
@icewind1991 Are there plans to allow external storage to be mounted as home?

**Comment by j-ed** [comment]
👍 I would like to see this feature in Nextcloud too. From an administrators point of view it would guaranty that all home directories are located on a dedicated storage without an exception and would ease the separation of the machine where the software is running and the data is stored.

**Comment by MorrisJobke** [comment]
> 👍 I would like to see this feature in Nextcloud too. From an administrators point of view it would guaranty that all home directories are located on a dedicated storage without an exception and would ease the separation of the machine where the software is running and the data is stored.

You can also do this easily and with higher performance on a filesystem level. Mount an SMB/NFS share to `/data` via `/etc/fstab` and then use this as you data dir. ;)

**Comment by xInsertx** [comment]
@MorrisJobke can you give a practical example for a system linked to ldap? Because adding a ton of users to fstab seems like a bad idea. This is very easy to achieve using pydio by using the provided variable.

Providing a variable would be a good first step.
https://help.nextcloud.com/t/mount-a-users-share-based-on-username/7845

**Comment by MorrisJobke** [comment]
> @MorrisJobke can you give a practical example for a system linked to ldap? Because adding a ton of users to fstab seems like a bad idea. Adding the users root directory could screw with permissions also. This is very easy to achieve using pydio by using the provided variable.

Here I meant that only one mount point would be added and then all the data is on the remote store, but access via one pair of credentials.

**Comment by MorrisJobke** [comment]
Fixed in #3438

**Comment by tomharristech** [comment]
For now, is there a way to just install smbclient manually in the snap?
