### ISSUE TITLE
[Bug]: AccountManager clears input field during typing (User profile)

### ISSUE THREAD

**Issue by MrRinkana** [nextcloud/server#33440]
<details>
  <summary>(Bug report checklist)</summary>
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).
</details>

### Bug description

When adding information to the user profile, such as phone number or website the input field gets cleared even during typing.

### Steps to reproduce

1. Go to User profile

2. Try to add a phone number or website but do it wrong (without http:// or https:// in the website field, use a "+" in the phone field, etc.) or type slowly.

3. What you have typed disappears, a check-mark shows and nothing is saved. No feedback about why the field was cleared is shown.

Gif showcasing problem:
![ ](https://user-images.githubusercontent.com/39345772/182444576-9e1efad8-d2f1-414a-a8c0-f95f2032ddc6.gif)
The enter button was not pressed during the clip.

At the end I type "https://" fast enough for it to not get cleared. Not all can type fast enough, especially "://" might cause trouble.

The website field at least shows you the correct start ("Link https://...") when its empty, which might give clues to what is missing, but the phone number field only shows "Your phone number" and no clue about not using "+" for example.

### Expected behavior

If the input field is being filled incorrectly a red cross should appear where the check mark usually goes, and stay there until user **deselects** the field or the entered text is **correct/approved**.

A text should appear next to or under the input field **explaining** what is missing or wrong (such as "website must start with http:// or https://" or "phone number should NOT start with + and has to consist of 10 numbers").

In either case the text should **not be cleared** until the user has deselected the field or pressed enter.

Currently these input fields may give the impression that they are broken. 
It could result in frustration because no feedback is given, nor a chance to correct what is written (must start over and be fast or copy it in + requires knowledge what is correct).

### Other details:
<details>
  <summary>(Click to expand)</summary>
  

### Operating system

RHEL/CentOS

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### List of activated Apps

```shell
- accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - appointments: 1.12.7
  - apporder: 0.15.0
  - breezedark: 24.0.2
  - bruteforcesettings: 2.4.0
  - calendar: 3.4.2
  - checksum: 1.1.4
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.2.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - files: 1.19.0
  - files_accesscontrol: 1.14.0
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - fileslibreofficeedit: 1.0.4
  - firstrunwizard: 2.13.0
  - forms: 2.5.1
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - metadata: 0.16.0
  - notes: 4.4.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - previewgenerator: 5.0.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - registration: 1.5.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - viewer: 1.8.0
  - workflowengine: 2.6.0
Disabled:
  - camerarawpreviews: 0.7.16
  - contactsinteraction: 1.2.0
  - dashboard: 7.2.0
  - encryption
  - federation: 1.11.0
  - files_videoplayer: 1.11.0
  - nextcloud_announcements: 1.11.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - user_ldap
  - user_status: 1.2.0
  - weather_status: 1.1.0
```

### Nextcloud Logs

```shell
Event does not generate logs, at least on non debug levels (I have not tested debug logging).
```
</details>

**Comment by koolandrew** [comment]
I have stumbled across a not-so-great solution, but it worked for me. Simply open up some type of notepad, type the number there and copy and then paste it to the phone number field. It actually worked for me, i would imagine others who are experiencing this issue.
For you more advanced technical wizards, i believe that the data entry times out for some reason, as i could only manually type a few digits before the checkmark was to appear.

**Comment by MrRinkana** [comment]
@koolandrew This is indeed the current workaround. But it is a user experience issue, and also requires knowledge about for example the phone number should not contain a "+".

I don't think it times out, it just checks to frequently (and during typing) for if what you have written is correct - and since few partially typed phone numbers or addresses are correct, it removes what is written.

I will recheck this issue once i get my hands on nc25, since some major UX redesigns seem to have happened.

**Comment by MrRinkana** [comment]
Sorry for updating this late, but the main problem presented in this issue was fixed with the redesign in nc25 (in that the text field no longer is cleared when incorrect input is given).

What remains is the description for url should be more specific (it requires "http://" or "https://" in the beginning) **and** the phone number has no description at all or indication if something is wrong - and simply does not save the change (for example without a "+").

These things should probably be separate issues, and probably no longer a server issue but rather translation/descriptions.
