### ISSUE TITLE
Wrong time in nextcloud.log

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/server#3345]
### Steps to reproduce
1. `date`
2. `tail -f nextcloud.log`

### Expected behaviour
Output of the `date` command should be the same as in `nextcloud.log`

### Actual behaviour
Date in `nextcloud.log` is wrong

### Server configuration
**Operating system**:
Ubuntu 16.04

**Comment by skjnldsv** [comment]
Hi!
Is your php timezone correctly set?

**Comment by KB7777** [comment]
[root@nextcloud ~]# grep timezone /var/www/html/nextcloud/config/config.php
  'logtimezone' => 'Europe/Warsaw',
[root@nextcloud ~]#

https://docs.nextcloud.com/server/11/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=trash#logging

**Comment by skjnldsv** [comment]
And your php settings?

**Comment by Sanookmakmak** [comment]
> And your php settings?

'logtimezone' => 'UTC',

;-)

Thank you!
