### ISSUE TITLE
[Bug]: Sharing a picture witht the "hide download", strange behaviour

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#33463]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Sharing a picture as a public link with the "hide download" option results in a strange behaviour, the ficture gets first opened with Collabora Draw and when you close it you have the normal picture preview like without the hide download option.

### Steps to reproduce

0. You need to have a Nextcloud instance with Nextcloud Office enabled
1. Share a picture as public link
2. Enable the hide download option
3. Open the link

First the document will be opened with Collabora Draw:

![image](https://user-images.githubusercontent.com/1589737/183037387-477e9462-eef4-46ba-ac0e-44b0c299c03f.png)

When I close collabora I'm back to the normal preview without a download button:

![image](https://user-images.githubusercontent.com/1589737/183037587-289a3b18-ab45-4055-bc13-96c3a1de55da.png)

### Expected behavior

I think we should just show the normal preview without the download option and don't open it with Collabora.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Nextcloud Office needs to be enabled
```

**Comment by Jerome-Herbinet** [comment]
I just opened the exactly same issue yesterday XD : #33459

**Comment by schiessle** [comment]
Ah, sorry. Didn't saw it. Let's close my ticket than and continue here: https://github.com/nextcloud/server/issues/33459

**Comment by Jerome-Herbinet** [comment]
> Ah, sorry. Didn't saw it. Let's close my ticket than and continue here: #33459

No problem, thanks and have a nice day !
