### ISSUE TITLE
[Bug]: File and folder sharing in Nextcloud 24 : Expiration calendar display problem (overflow hidden)

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/server#33464]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

**Is your feature request related to a problem? Please describe.**

When you create a share (file or folder), and want to choose an expiry date for the share link, the calendar does not display completely, and you have to scroll down to see the whole calendar. 

**This problem :** 
- only occurs in Nextcloud 24 (no problem with Nextcloud 22 and 23)
- apparently occurs systematically for file shares. 
- also occurs for folder shares, but it depends on whether the popup is displayed upwards or downwards, which determines the position of the calendar picker and thus the occurrence of the problem.
- occurs whether the share is public (anonymous), or with an email address, or to a user / group / circle.

**Describe the solution you'd like**
The calendar should display as before in Nextcloud 22 and 23 (and be able to overflow the share's properties block). Although I am very familiar with Nextcloud, if I put myself in the shoes of an average user, I think that many will not understand what is going on and may not be able to create their shares correctly.

Nextcloud 22 and 23 (no problem) : 
![2022-08-05_10-51](https://user-images.githubusercontent.com/33763786/183040875-9444b959-e9b8-4c6e-b5d4-395f936bcf78.png)

Nextcloud 24 issue : 
File sharing : 
![2022-08-05_10-30](https://user-images.githubusercontent.com/33763786/183040857-e8b51366-613d-4505-8cde-3e9670fec52a.png)
Folder sharing : 
![2022-08-05_10-54](https://user-images.githubusercontent.com/33763786/183041415-b3d20eb3-c26a-4471-ae39-428b973173cf.png)

### Steps to reproduce

1. Connect to a Nextcloud 24 instance
2. Share a file (for example a public sharing of a file, I mean a public link)
3. Enable (check) the expiry date option in order to display the calendar
4. Find that the calendar is not displayed correctly
5. Notice that the calendar does not display properly and that the only way to see the rest is to scroll down.

### Expected behavior

The calendar should display as before in Nextcloud 22 and 23 (and be able to overflow the share's properties block). 

### Installation method

Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_

### Configuration report

```shell
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.mydomain.fr"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "24.0.3.2",
    "updatechecker": true,
    "overwrite.cli.url": "https:\/\/nextcloud.mydomain.fr",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "default_language": "fr",
    "default_locale": "fr_FR",
    "default_phone_region": "ISO3166-2",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "updater.release.channel": "stable",
    "app_install_overwrite": [
        "occweb"
    ]
}
```

### List of activated Apps

```shell
Enabled:
 - accessibility: 1.10.0
 - activity: 2.16.0
 - announcementcenter: 6.3.1
 - apporder: 0.15.0
 - bruteforcesettings: 2.4.0
 - calendar: 3.4.2
 - cfg_share_links: 2.0.0
 - circles: 24.0.0
 - cloud_federation_api: 1.7.0
 - comments: 1.14.0
 - contacts: 4.2.0
 - contactsinteraction: 1.5.0
 - dashboard: 7.4.0
 - dav: 1.22.0
 - deck: 1.7.1
 - external: 4.0.0
 - extract: 1.3.5
 - federatedfilesharing: 1.14.0
 - federation: 1.14.0
 - files: 1.19.0
 - files_accesscontrol: 1.14.0
 - files_automatedtagging: 1.14.0
 - files_external: 1.16.1
 - files_linkeditor: 1.1.11
 - files_pdfviewer: 2.5.0
 - files_readmemd: 1.2.2
 - files_rightclick: 1.3.0
 - files_sharing: 1.16.2
 - files_trashbin: 1.14.0
 - files_versions: 1.17.0
 - files_videoplayer: 1.13.0
 - files_zip: 1.1.2
 - firstrunwizard: 2.13.0
 - groupfolders: 12.0.1
 - guests: 2.2.0
 - impersonate: 1.11.0
 - jitsi: 0.15.0
 - logreader: 2.9.0
 - lookup_server_connector: 1.12.0
 - metadata: 0.16.0
 - nextcloud_announcements: 1.13.0
 - notes: 4.4.0
 - notifications: 2.12.0
 - oauth2: 1.12.0
 - occweb: 0.1.0
 - password_policy: 1.14.0
 - passwords: 2022.6.20
 - phonetrack: 0.7.0
 - photos: 1.6.0
 - privacy: 1.8.0
 - provisioning_api: 1.14.0
 - quota_warning: 1.14.0
 - recommendations: 1.3.0
 - richdocuments: 6.1.1
 - richdocumentscode: 22.5.401
 - serverinfo: 1.14.0
 - settings: 1.6.0
 - sharebymail: 1.14.0
 - sharerenamer: 3.0.1
 - spreed: 14.0.3
 - support: 1.7.0
 - survey_client: 1.12.0
 - systemtags: 1.14.0
 - text: 3.5.1
 - theming: 1.15.0
 - theming_customcss: 1.11.0
 - twofactor_backupcodes: 1.13.0
 - twofactor_email: 2.5.0
 - twofactor_nextcloud_notification: 3.4.0
 - twofactor_totp: 6.4.0
 - updatenotification: 1.14.0
 - user_status: 1.4.0
 - video_converter: 1.0.5
 - viewer: 1.8.0
 - weather_status: 1.4.0
 - welcome: 1.0.1
 - workflowengine: 2.6.0
Disabled:
 - admin_audit
 - duplicatefinder: 0.0.15
 - encryption
 - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Can be provided if necessary.
```

**Comment by szaimen** [comment]
Hi, please update to 25.0.7 or better 26.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 26-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by Jerome-Herbinet** [comment]
> Hi, please update to 25.0.7 or better 26.0.2 and report back if it fixes the issue. Thank you!
> 
> My goal is to add a label like e.g. 26-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!
> 
> If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

@szaimen I have 25.0.6 and the problem seems to be solved.

**Comment by szaimen** [comment]
> @szaimen I have 25.0.6 and the problem seems to be solved.

Great! Thanks for verifying! :)
