### ISSUE TITLE
Left shadow in app-navigation missing from user settings

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#3346]
Since we're using anchor, the active state isn't applied.
We need to change that.
- [ ] Change the active state while scrolling with the screen position
    - [ ] Screen position
    - [ ] Active state on last item too (since the window height might be too much)

OR, we switch from a single page to a multiple page like the admin settings

@nextcloud/designers

**Comment by MorrisJobke** [comment]
This is now implemented in Nextcloud 13
