### ISSUE TITLE
[Bug]: nextcloud 24 rc1 Hmmm… can't reach this page after upgrade from 24.0.3

### ISSUE THREAD

**Issue by FALErwi** [nextcloud/server#33462]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

after I upgrade my server is down 🚨 

### Steps to reproduce

1. upgrade to 24.0.4 rc1
2.
3.

### Expected behavior

no issue

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "filebox.vip",
            "www.filebox.vip",
            "10.0.0.122"
        ],
        "objectstore": {
            "class": "\\OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "FileBox",
                "autocreate": true,
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "hostname": "axafy8lihann.compat.objectstorage.me-jeddah-1.oraclecloud.com",
                "port": 443,
                "use_ssl": true,
                "region": "me-jeddah-1",
                "use_path_style": true
            }
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.4.0",
        "overwrite.cli.url": "https:\/\/www.filebox.vip",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "activity_expire_days": 14,
        "allow_local_remote_servers": true,
        "auth.bruteforce.protection.enabled": true,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "cron_log": true,
        "default_phone_region": "DE",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "filesystem_check_changes": 0,
        "filelocking.enabled": "true",
        "htaccess.RewriteBase": "\/",
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "log_rotate_size": "104857600",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 2,
        "logtimezone": "Europe\/Berlin",
        "maintenance_window_start": 1,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "overwriteprotocol": "https",
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "profile.enabled": false,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0.5,
            "dbindex": 1
        },
        "quota_include_external_storage": false,
        "share_folder": "\/Freigaben",
        "skeletondirectory": "",
        "trashbin_retention_obligation": "auto, 7",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "beta",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": ""
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - announcementcenter: 6.3.1
  - calendar: 3.4.2
  - circles: 24.0.1
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.2.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_videoplayer: 1.13.0
  - files_zip: 1.1.2
  - groupfolders: 12.0.1
  - impersonate: 1.11.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - mail: 1.14.0-alpha.4
  - music: 1.5.2
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - side_menu: 2.4.2
  - sociallogin: 4.16.1
  - socialsharing_email: 2.5.0
  - spreed: 14.0.3
  - survey_client: 1.12.0
  - text: 3.5.1
  - theming: 1.15.0
  - transfer: 0.6.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - encryption
  - files_versions: 1.17.0
  - firstrunwizard: 2.13.0
  - support: 1.7.0
  - systemtags: 1.14.0
  - user_ldap
  - user_status: 1.4.0
```

### Nextcloud Logs

```shell
{"reqId":"NiqI6NAkvGOfcFzxcVXI","level":2,"time":"2022-08-05T08:04:55+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static172/common/js/infobox.js>
{"reqId":"ChFbVjfc67ddZKF52Orz","level":2,"time":"2022-08-05T08:04:56+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static185/rightsidebar/css/pro>
{"reqId":"97x0JSZWebS657cvuNFi","level":2,"time":"2022-08-05T08:04:57+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static158/classic/css/msie.css>
{"reqId":"1KmKWmbttU7mRjM5Zc0Q","level":2,"time":"2022-08-05T08:04:58+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static10/img/moin-search.gif",>
{"reqId":"NK1o5XSBvucnvD4Xr1RZ","level":2,"time":"2022-08-05T08:04:59+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static155a/common/ie7/ie7-over>
{"reqId":"PIxTI95gBDiPCIAaHObr","level":2,"time":"2022-08-05T08:05:00+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static181/modernized/css/scree>
{"reqId":"eu40UGRmzCm7rcFNngsa","level":2,"time":"2022-08-05T08:05:01+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static170rc1/classic/css/scree>
{"reqId":"5bAbXEG14kQpBMSQslrh","level":2,"time":"2022-08-05T08:05:02+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static172/modern/css/common.cs>
{"reqId":"td0xw6hNmckowfS7m0ns","level":2,"time":"2022-08-05T08:05:03+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static12/classic/css/common.cs>
{"reqId":"aS9Y73JND843yUXjDZs5","level":2,"time":"2022-08-05T08:05:04+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static160beta1/robots.txt","me>
{"reqId":"beIGDytRDcVMgLLMX9Wo","level":2,"time":"2022-08-05T08:05:05+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static183/classic/css/common.c>
{"reqId":"N0uayhkGtBvDb2YBmhRW","level":2,"time":"2022-08-05T08:05:07+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static12/classic/css/print.css>
{"reqId":"upM6TLguHRSjr4nEunps","level":2,"time":"2022-08-05T08:05:08+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static130/modern/css/screen.cs>
{"reqId":"4uaKuiq3yuBenWKiyVJC","level":2,"time":"2022-08-05T08:05:09+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static193/modernized/css/Slide>
{"reqId":"xQbJqCU8aKkW93tWOmyi","level":2,"time":"2022-08-05T08:05:10+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static182/modern/css/print.css>
{"reqId":"ql7tXOefrD5r59yK3v20","level":2,"time":"2022-08-05T08:05:12+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/modules/system/assets/ui/js/inspect>
{"reqId":"LhbezGu8iuPY7Q419NMY","level":2,"time":"2022-08-05T08:05:13+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/modules/system/assets/ui/js/inspect>
{"reqId":"dfJ0cbz3Ze443HhZPO90","level":2,"time":"2022-08-05T08:05:14+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/themes/demo/assets/less/theme/boot.>
{"reqId":"0Ztp19osSiHeQjuNsiO8","level":2,"time":"2022-08-05T09:00:32+02:00","remoteAddr":"82.167.1.150","user":"google-105128508013889939885","app":"appstoreFetcher","method":"GET","url":>
{"reqId":"aMZNRiDqF8kSnyZMgCzD","level":2,"time":"2022-08-05T09:06:58+02:00","remoteAddr":"82.167.1.150","user":"google-105128508013889939885","app":"appstoreFetcher","method":"GET","url":>
{"reqId":"DDHWsf2xiwyKsYHuf4J1","level":2,"time":"2022-08-05T09:08:22+02:00","remoteAddr":"205.210.31.15","user":"--","app":"core","method":"GET","url":"/","message":"Trusted domain error.>
{"reqId":"0XrpQU631cjl7mHH5Xy6","level":2,"time":"2022-08-05T09:24:20+02:00","remoteAddr":"31.7.58.162","user":"--","app":"core","method":"GET","url":"/","message":"Trusted domain error. \>
```

**Comment by FALErwi** [comment]
{"reqId":"NiqI6NAkvGOfcFzxcVXI","level":2,"time":"2022-08-05T08:04:55+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static172/common/js/infobox.js>
{"reqId":"ChFbVjfc67ddZKF52Orz","level":2,"time":"2022-08-05T08:04:56+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static185/rightsidebar/css/pro>
{"reqId":"97x0JSZWebS657cvuNFi","level":2,"time":"2022-08-05T08:04:57+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static158/classic/css/msie.css>
{"reqId":"1KmKWmbttU7mRjM5Zc0Q","level":2,"time":"2022-08-05T08:04:58+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static10/img/moin-search.gif",>
{"reqId":"NK1o5XSBvucnvD4Xr1RZ","level":2,"time":"2022-08-05T08:04:59+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static155a/common/ie7/ie7-over>
{"reqId":"PIxTI95gBDiPCIAaHObr","level":2,"time":"2022-08-05T08:05:00+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static181/modernized/css/scree>
{"reqId":"eu40UGRmzCm7rcFNngsa","level":2,"time":"2022-08-05T08:05:01+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static170rc1/classic/css/scree>
{"reqId":"5bAbXEG14kQpBMSQslrh","level":2,"time":"2022-08-05T08:05:02+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static172/modern/css/common.cs>
{"reqId":"td0xw6hNmckowfS7m0ns","level":2,"time":"2022-08-05T08:05:03+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static12/classic/css/common.cs>
{"reqId":"aS9Y73JND843yUXjDZs5","level":2,"time":"2022-08-05T08:05:04+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static160beta1/robots.txt","me>
{"reqId":"beIGDytRDcVMgLLMX9Wo","level":2,"time":"2022-08-05T08:05:05+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static183/classic/css/common.c>
{"reqId":"N0uayhkGtBvDb2YBmhRW","level":2,"time":"2022-08-05T08:05:07+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static12/classic/css/print.css>
{"reqId":"upM6TLguHRSjr4nEunps","level":2,"time":"2022-08-05T08:05:08+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static130/modern/css/screen.cs>
{"reqId":"4uaKuiq3yuBenWKiyVJC","level":2,"time":"2022-08-05T08:05:09+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static193/modernized/css/Slide>
{"reqId":"xQbJqCU8aKkW93tWOmyi","level":2,"time":"2022-08-05T08:05:10+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/moin_static182/modern/css/print.css>
{"reqId":"ql7tXOefrD5r59yK3v20","level":2,"time":"2022-08-05T08:05:12+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/modules/system/assets/ui/js/inspect>
{"reqId":"LhbezGu8iuPY7Q419NMY","level":2,"time":"2022-08-05T08:05:13+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/modules/system/assets/ui/js/inspect>
{"reqId":"dfJ0cbz3Ze443HhZPO90","level":2,"time":"2022-08-05T08:05:14+02:00","remoteAddr":"64.39.108.32","user":"--","app":"core","method":"GET","url":"/themes/demo/assets/less/theme/boot.>
{"reqId":"0Ztp19osSiHeQjuNsiO8","level":2,"time":"2022-08-05T09:00:32+02:00","remoteAddr":"82.167.1.150","user":"google-105128508013889939885","app":"appstoreFetcher","method":"GET","url":>
{"reqId":"aMZNRiDqF8kSnyZMgCzD","level":2,"time":"2022-08-05T09:06:58+02:00","remoteAddr":"82.167.1.150","user":"google-105128508013889939885","app":"appstoreFetcher","method":"GET","url":>
{"reqId":"DDHWsf2xiwyKsYHuf4J1","level":2,"time":"2022-08-05T09:08:22+02:00","remoteAddr":"205.210.31.15","user":"--","app":"core","method":"GET","url":"/","message":"Trusted domain error.>
<ror. \"31.7.58.162\" tried to access using \"150.230.244.223\" as host.","userAgent":"Go-http-client/1.1","version":"24.0.4.0","data":{"app":"core"}}

**Comment by FALErwi** [comment]
[appstoreFetcher] Warning: Could not connect to appstore: cURL error 28: Failed to connect to apps.nextcloud.com port 443 after 30201 ms: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://apps.nextcloud.com/api/v1/apps.json

GET /apps/serverinfo/update
from 82.167.1.150 by google-105128508013889939885 at 2022-08-05T09:00:32+02:00

[appstoreFetcher] Warning: Could not connect to appstore: cURL error 28: Operation timed out after 60001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://apps.nextcloud.com/api/v1/apps.json

GET /apps/serverinfo/update
from 82.167.1.150 by google-105128508013889939885 at 2022-08-05T09:06:58+02:00

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
