### ISSUE TITLE
Absolute redirects in .htaccess

### ISSUE THREAD

**Issue by TiMESPLiNTER** [nextcloud/server#3347]
### Steps to reproduce
1. Install Nextcloud into a sub-folder (yourdomain.com/nextcloud/
2. Call the .well-known URL you get redirected to yourdomain.com/.well-known/ instead of yourdomain.com/nextcloud/.well-known/

### Expected behaviour
I would expect that the redirect of those URLs also work if I install nextcloud into a sub directory

### Actual behaviour
The redirects point to the root if the domain (yourdomain.com/.well-known...)

### Server configuration
**Operating system**:
Synology DSM 6.0 (Linux)

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
5.6

**Nextcloud version:** (see Nextcloud admin page)
11.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
From source code downloaded over nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
contacts
calendar
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
n/a
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
Contacts app of macOS

**Operating system:**
macOS 10.12

#### Web server error log
<details>
<summary>Web server error log</summary>
```
n/a
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
n/a
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
n/a
```
</details>

**Comment by MorrisJobke** [comment]
> The redirects point to the root if the domain (yourdomain.com/.well-known...)

There is no way to do this from a subfolder. The .htaccess file is only loaded when that subfolder is in use. So you need to set up your web server accordingly to forward request to .well-known to the `subfolder/...` URL.
