### ISSUE TITLE
[Bug]: OCC does not work when memcache configuration is invalid

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#33486]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

This is a generalization of #30292

When the configured memcache is not available OCC can not be used, not even to delete the memcache configuration that is preventing OCC from bein used; `config.php` needs to be manually edited in that case.

### Steps to reproduce

- Make a typo when setting `memcache.local` with OCC:
```
php occ config:system:set memcache.local --value "ridiculousTypoToMakeTheIssueClear" --type string
```
- Try to fix the typo (note that `php --define apc.enable_cli=1` would have no effect, as APCu is not even used yet)
```
php occ config:system:set memcache.local --value "\OC\Memcache\APCu" --type string
```

The configuration value was not updated and OCC exited with:
```
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache ridiculousTypoToMakeTheIssueClear not available for local cache (Is the matching PHP module installed and enabled?)
```

### Expected behavior

The configuration should be updated.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Not relevant.
```

**Comment by Ezwen** [comment]
Same problem here. More generally, I would find it really great if `occ config:system:set` could work in all cases where either the database or the cache would not be working/valid, eg. wrong configurations (as in op) or a crashed database.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
