### ISSUE TITLE
The given author user is invalid when activity stream wants to report an expired link

### ISSUE THREAD

**Issue by jkoopmann** [nextcloud/server#3348]
### Steps to reproduce
1. Share a folder via link
2. set an expiry date
3. wait for the expiry to happen

### Expected behaviour
No error to start with. :-)

In the activity stream of the user I suppose a notification should pop up.

### Actual behaviour

Error:
`
{"reqId":"NMof78i2R8TVMwHkOYSv","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"The given author user is invalidN;\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(889): OC\\\\Activity\\\\Event->setAuthor(NULL)\\n#1 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(750): OCA\\\\Activity\\\\FilesHooks->addNotificationsForUser('j.koopmann', 'link_expired', Array, 88373, '\\\/temp\\\/Ellmau', false, true, 3600)\\n#2 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(565): OCA\\\\Activity\\\\FilesHooks->shareFileOrFolderByLink(88373, 'folder', 'j.koopmann', false)\\n#3 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/activity\\\/lib\\\/FilesHooksStatic.php(101): OCA\\\\Activity\\\\FilesHooks->unShare(Array)\\n#4 [internal function]: OCA\\\\Activity\\\\FilesHooksStatic::unShare(Array)\\!
n#5 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/hook.php(106): call_user_func(Array, Array)\\n#6 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Share\\\/Share.php(1541): OC_Hook::emit('OCP\\\\\\\\Share', 'pre_unshare', Array)\\n#7 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Share\\\/Share.php(977): OC\\\\Share\\\\Share::unshareItem(Array, NULL)\\n#8 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/public\\\/Share.php(290): OC\\\\Share\\\\Share::unshare('folder', '88373', 3, NULL, 'j.koopmann')\\n#9 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/ExpireSharesJob.php(72): OCP\\\\Share::unshare('folder', '88373', 3, NULL, 'j.koopmann')\\n#10 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(53): OCA\\\\Files_Sharing\\\\ExpireSharesJob->run(NULL)\\n#11 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(54): OC\\\\BackgroundJob\\\\Job->exec!
ute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#12 \
\
PHP Fatal error:  Call to a member function getPath() on null in /usr/local/www/nextcloud/lib/private/Files/Filesystem.php on line 913
{"reqId":"NMof78i2R8TVMwHkOYSv","remoteAddr":"","app":"PHP","message":"Call to a member function getPath() on null at \/usr\/local\/www\/nextcloud\/lib\/private\/Files\/Filesystem.php#913","level":3,"time":"2017-02-01T06:00:03+00:00","method":"--","url":"\/nextcloud\/cron.php","user":"--","version":"11.0.0.10"}
`

### Server configuration
**Operating system**: 
FreeBSD

**Web server:** 
Apache 2.4

**Database:** 
Mysql

**PHP version:**
5.6.29

**Nextcloud version:** (see Nextcloud admin page)
11.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Comment by nickvergessen** [comment]
The Exception was fixed with https://github.com/nextcloud/activity/pull/109 already.
Will be released with 11.0.2

Translations for these events however are missing. Will readd them and also backport for 11.0.2

**Comment by nickvergessen** [comment]
Btw @rullzer the share initiator is not included in the hook when the expired link is deleted:
https://github.com/nextcloud/server/blob/a56717673f57c24b9b9ae228ca2fff6478fc16d3/lib/private/Share/Share.php#L1527-L1535

Means we can't even post an activity for them.
So I tried to change it to use the new ShareManager in https://github.com/nextcloud/server/blob/813f0a0f40dd42b28cd35d91616f3f87ef400861/apps/files_sharing/lib/ExpireSharesJob.php#L72
But then it didn't even dispatch the event at all anymore :(

**Comment by rullzer** [comment]
@nickvergessen as far as I can see that part is not used anymore. We use https://github.com/nextcloud/server/blob/master/lib/private/Share20/Manager.php#L825

However, I don't like modifying or extending that.
How about I emit an event with the share object on deletion?

**Comment by nickvergessen** [comment]
Sounds good to me

**Comment by MorrisJobke** [comment]
Fixed with #3844
