### ISSUE TITLE
federated cloud sharing 503

### ISSUE THREAD

**Issue by evook** [nextcloud/server#335]
Hi, 

I have two identically set up servers, both connected to the same ldap. While login and syncing works as expected, I am having trouble to share folders to an federated cloud id of the other server. The direction doesn't matter. 

For later use, it is planned to have on local server and in the datacenter, but for testing purposes both are sitting on the same hyper-visor and are automatically deployed so consider those servers to be similiar configured.
 
php7.0-fpm              7.0.4-7ubuntu2.1
nginx                        1.10.0-0ubuntu0.16.04.2
mariadb-server        10.0.25-0ubuntu0.16.04.1
lets-encrypt certs with a valid configuration if ask http://testssl.sh/

When sharing something from Server A to Server B via "fc-id@serverb.com", I can accept the share on Server B and have it listed in the Webinterface. 

Trying to access the folder with the client who accepted it, I'll get a

`{"reqId":"m0MalIOdldlas304nwaep","remoteAddr":"10.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Storage not available\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(903): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('share1 (2)')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(334): Sabre\\\\DAV\\\\Server->getPropertiesForPath('share1 (2)', Array, 1)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/nextcloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/nextcl...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/objecttree.php\",\"Line\":159,\"User\":\"2313231asd-b5231d876edc\"}","level":4,"time":"2016-07-07T10:33:01+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/share1%20(2)","user":"4e776114-ff81-102f-83ee-b5231d876edc"}
`
Server A log is empty.

I can switch Servers and reproduce this exact error sharing from Server B to Server A. I'd be glad if someone knows where to start debugging.

**Comment by LukasReschke** [comment]
Please fill out the issue template, there is information missing such as which version etc.

**Comment by MorrisJobke** [comment]
No response for 2 months -> closing
