### ISSUE TITLE
[Bug]: User access by share to Group Folder file, changes not saved. Versioning APP fatal error.

### ISSUE THREAD

**Issue by enbata** [nextcloud/server#33509]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

File created inside a Group Folder, give access to user (not in group) sharing the document directly. When the user tries to save the document the server return ERROR 500. The File Versioning APP causes the error.

Disabling the File Versioning APP the changes are saved.

### Steps to reproduce

1. Create a Group Folder.
2. Create file inside The Group Folder.
3. User A with acces to that Group Folder, gives write access to user B for the file.
4. User B made changes to the file ant try to save.
5. The changes are not saved, not error given.
6. Disable File Versioning APP
7. User B mades changes and save them.
8. The changes are saved.

### Expected behavior

The system must save the changes of User B.

### Installation method

Official Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MySQL

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
iametza-app php occ config:list system
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud-demo.iametza.eus"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.3.2",
        "overwrite.cli.url": "http:\/\/nextcloud-demo.iametza.eus",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "eu",
        "default_locale": "eu",
        "default_phone_region": "ES",
        "loglevel": 0,
        "maintenance": false,
        "allow_local_remote_servers": true,
        "overwriteprotocol": "https",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "richdocuments"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - announcementcenter: 6.3.1
  - apporder: 0.15.0
  - bruteforcesettings: 2.4.0
  - calendar: 3.4.2
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.2.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - deck: 1.7.1
  - external: 4.0.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_markdown: 2.3.6
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - forms: 2.5.1
  - groupfolders: 12.0.1
  - impersonate: 1.11.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - mail: 1.13.7
  - nextcloud_announcements: 1.13.0
  - notes: 4.4.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - onlyoffice: 7.5.4
  - password_policy: 1.14.0
  - photos: 1.6.0
  - polls: 3.7.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - side_menu: 2.4.2
  - spreed: 14.0.3
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - tasks: 0.14.4
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"VyrYSExXqf4dh9IBoK6O","level":3,"time":"2022-08-11T14:16:39+00:00","remoteAddr":"172.22.0.1","user":"proba2","app":"index","method":"POST","url":"/apps/onlyoffice/track?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJwcm9iYTIiLCJvd25lcklkIjoicHJvYmExIiwiZmlsZUlkIjozNjY1LCJmaWxlUGF0aCI6IlwvcGFydGVrYXR6ZWtvLnhsc3giLCJzaGFyZVRva2VuIjpudWxsLCJhY3Rpb24iOiJ0cmFjayJ9.H5W0-vpmFKH3Qopg8kHQzb_khLDEtelnO0G_o8GpI-w","message":"Call to a member function getId() on bool in file '/var/www/html/apps/files_versions/lib/Storage.php' line 197","userAgent":"Node.js/6.13","version":"24.0.3.2","exception":{"Exception":"Exception","Message":"Call to a member function getId() on bool in file '/var/www/html/apps/files_versions/lib/Storage.php' line 197","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Onlyoffice\\Controller\\CallbackController"},"track"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Onlyoffice\\Controller\\CallbackController","track",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},["onlyoffice.callback.track"]]},{"file":"/var/www/html/lib/base.php","line":1023,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/onlyoffice/track"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":165,"Previous":{"Exception":"Error","Message":"Call to a member function getId() on bool","Code":0,"Trace":[{"file":"/var/www/html/apps/files_versions/lib/Hooks.php","line":56,"function":"store","class":"OCA\\Files_Versions\\Storage","type":"::","args":["/Proba/partekatzeko.xlsx"]},{"file":"/var/www/html/lib/private/legacy/OC_Hook.php","line":106,"function":"write_hook","class":"OCA\\Files_Versions\\Hooks","type":"::","args":[[true,"/Proba/partekatzeko.xlsx"]]},{"file":"/var/www/html/lib/private/Files/View.php","line":1290,"function":"emit","class":"OC_Hook","type":"::","args":["OC_Filesystem","write",[true,"/Proba/partekatzeko.xlsx"]]},{"file":"/var/www/html/lib/private/Files/View.php","line":1160,"function":"runHooks","class":"OC\\Files\\View","type":"->","args":[["update","write"],"/Proba/partekatzeko.xlsx"]},{"file":"/var/www/html/lib/private/Files/View.php","line":711,"function":"basicOperation","class":"OC\\Files\\View","type":"->","args":["file_put_contents","/proba1/files/Proba/partekatzeko.xlsx",["update","write"],null]},{"file":"/var/www/html/lib/private/Files/Node/File.php","line":71,"function":"file_put_contents","class":"OC\\Files\\View","type":"->","args":["/proba1/files/Proba/partekatzeko.xlsx",null]},{"file":"/var/www/html/custom_apps/onlyoffice/controller/callbackcontroller.php","line":543,"function":"putContent","class":"OC\\Files\\Node\\File","type":"->","args":[null]},{"file":"/var/www/html/custom_apps/onlyoffice/controller/callbackcontroller.php","line":771,"function":"OCA\\Onlyoffice\\Controller\\{closure}","class":"OCA\\Onlyoffice\\Controller\\CallbackController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/custom_apps/onlyoffice/controller/callbackcontroller.php","line":544,"function":"retryOperation","class":"OCA\\Onlyoffice\\Controller\\CallbackController","type":"->","args":[{"__class__":"Closure"}]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"track","class":"OCA\\Onlyoffice\\Controller\\CallbackController","type":"->","args":["eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJwcm9iYTIiLCJvd25lcklkIjoicHJvYmExIiwiZmlsZUlkIjozNjY1LCJmaWxlUGF0aCI6IlwvcGFydGVrYXR6ZWtvLnhsc3giLCJzaGFyZVRva2VuIjpudWxsLCJhY3Rpb24iOiJ0cmFjayJ9.H5W0-vpmFKH3Qopg8kHQzb_khLDEtelnO0G_o8GpI-w",["ocmrcl51z5aq_proba2"],"1298913786",2,"https://onlyoffice-demo.iametza.eus/cache/files/1298913786_3234/output.xlsx/output.xlsx?md5=XpgQbqcNcj9Fy3K9jTyUoA&expires=1660228300&filename=output.xlsx",null,["7.1.0",[["2022-08-11 14:16:32",["ocmrcl51z5aq_proba2","Proba2"]]]],"https://onlyoffice-demo.iametza.eus/cache/files/1298913786_3234/changes.zip/changes.zip?md5=Pv51cOfo-Tzx0OcTw0diuw&expires=1660228300&filename=changes.zip",null,[[0,"ocmrcl51z5aq_proba2"]]]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Onlyoffice\\Controller\\CallbackController"},"track"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Onlyoffice\\Controller\\CallbackController"},"track"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Onlyoffice\\Controller\\CallbackController","track",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},["onlyoffice.callback.track"]]},{"file":"/var/www/html/lib/base.php","line":1023,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/onlyoffice/track"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/apps/files_versions/lib/Storage.php","Line":197},"CustomMessage":"--"}}
```

### Additional info

Nextcloud Docker Log:

`nextcloud-demo-iametza-onlyoffice | 
nextcloud-demo-iametza-onlyoffice | ==> /var/log/onlyoffice/documentserver/docservice/out.log <==
nextcloud-demo-iametza-onlyoffice | [2022-08-11T14:07:34.312] [ERROR] nodeJS - sendServerRequest error: docId = 3878033061;url = https://nextcloud-demo.iametza.eus/apps/onlyoffice/track?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiJwcm9iYTIiLCJvd25lcklkIjoicHJvYmExIiwiZmlsZUlkIjozNjY1LCJmaWxlUGF0aCI6IlwvcGFydGVrYXR6ZWtvLnhsc3giLCJzaGFyZVRva2VuIjpudWxsLCJhY3Rpb24iOiJ0cmFjayJ9.H5W0-vpmFKH3Qopg8kHQzb_khLDEtelnO0G_o8GpI-w;data = {"key":"3878033061","status":2,"url":"https://onlyoffice-demo.iametza.eus/cache/files/3878033061_5391/output.xlsx/output.xlsx?md5=nQ5bk8wvg8VwvhWEn-Re4w&expires=1660227755&filename=output.xlsx","changesurl":"https://onlyoffice-demo.iametza.eus/cache/files/3878033061_5391/changes.zip/changes.zip?md5=JsAqwJIPGGiIT8eKrPE8gg&expires=1660227755&filename=changes.zip","history":{"serverVersion":"7.1.0","changes":[{"created":"2022-08-11 14:07:13","user":{"id":"ocmrcl51z5aq_proba2","name":"Proba2"}}]},"users":["ocmrcl51z5aq_proba2"],"actions":[{"type":0,"userid":"ocmrcl51z5aq_proba2"}],"lastsave":"2022-08-11T14:07:13.000Z","notmodified":false,"filetype":"xlsx"}
nextcloud-demo-iametza-onlyoffice | Error: Error response: statusCode:500; headers:{"server":"nginx/1.14.2","date":"Thu, 11 Aug 2022 14:07:34 GMT","content-type":"text/html; charset=UTF-8","content-length":"5415","connection":"keep-alive","referrer-policy":"no-referrer","x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN","x-permitted-cross-domain-policies":"none","x-robots-tag":"none","x-xss-protection":"1; mode=block","x-powered-by":"PHP/8.0.21","set-cookie":["ocmrcl51z5aq=4db0d65f0ec52240efbd64204b42171b; path=/; secure; HttpOnly; SameSite=Lax","oc_sessionPassphrase=jT7ConkUII0%2BCtDV73i9rD0rssLD7fwWbLEdUqKgSh4ia2GzF5%2FKFHESpKjjPOj5PPcm6GQQ5RsfrQPCGxVPCHESRYUIwM4Ub7BA8AiVmVULQaUUZkFZTYFIMBS36pUZ; path=/; secure; HttpOnly; SameSite=Lax","ocmrcl51z5aq=832e0d67c708461402ab76f9146fbb7a; path=/; secure; HttpOnly; SameSite=Lax","__Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax","__Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict"],"expires":"Thu, 19 Nov 1981 08:52:00 GMT","cache-control":"no-store, no-cache, must-revalidate","pragma":"no-cache","content-security-policy":"default-src 'self'; script-src 'self' 'nonce-V09URkROREp3TFdvSmFjbTUrNlh4Yndrb1Jya2tJZUtBak55VW5EUnZmMD06Rjc2T1FKNytnZUh2WFpOU3FZL0R2ZWhuMGxIVHBjbnVRRVZGTURtaDJMbz0='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';","strict-transport-security":"max-age=15768000; includeSubDomains;"}; body:
nextcloud-demo-iametza-onlyoffice | <!DOCTYPE html>
nextcloud-demo-iametza-onlyoffice | <html class="ng-csp" data-placeholder-focus="false" lang="eu" data-locale="eu" >
nextcloud-demo-iametza-onlyoffice | 	<head
nextcloud-demo-iametza-onlyoffice |  data-requesttoken="">
nextcloud-demo-iametza-onlyoffice | 		<meta charset="utf-8">
nextcloud-demo-iametza-onlyoffice | 		<title>
nextcloud-demo-iametza-onlyoffice | 		Nextcloud		</title>
nextcloud-demo-iametza-onlyoffice | 		<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
nextcloud-demo-iametza-onlyoffice | 				<meta name="apple-itunes-app" content="app-id=1125420102">
nextcloud-demo-iametza-onlyoffice | 				<meta name="theme-color" content="#0082c9">
nextcloud-demo-iametza-onlyoffice | 		<link rel="icon" href="/core/img/favicon.ico">
nextcloud-demo-iametza-onlyoffice | 		<link rel="apple-touch-icon" href="/core/img/favicon-touch.png">
nextcloud-demo-iametza-onlyoffice | 		<link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#0082c9">
nextcloud-demo-iametza-onlyoffice | 		<link rel="manifest" href="/apps/theming/manifest?v=0">
nextcloud-demo-iametza-onlyoffice | 		<link rel="stylesheet" href="/custom_apps/side_menu/css/sideMenu.css?v=06950f48-0">
nextcloud-demo-iametza-onlyoffice | <link rel="stylesheet" href="/core/css/guest.css?v=9fa0ea43-0">
nextcloud-demo-iametza-onlyoffice | 		<script nonce="V09URkROREp3TFdvSmFjbTUrNlh4Yndrb1Jya2tJZUtBak55VW5EUnZmMD06Rjc2T1FKNytnZUh2WFpOU3FZL0R2ZWhuMGxIVHBjbnVRRVZGTURtaDJMbz0=" defer src="/dist/core-common.js?v=9fa0ea43-0"></script>
nextcloud-demo-iametza-onlyoffice | <script nonce="V09URkROREp3TFdvSmFjbTUrNlh4Yndrb1Jya2tJZUtBak55VW5EUnZmMD06Rjc2T1FKNytnZUh2WFpOU3FZL0R2ZWhuMGxIVHBjbnVRRVZGTURtaDJMbz0=" defer src="/dist/core-main.js?v=9fa0ea43-0"></script>
nextcloud-demo-iametza-onlyoffice | <script nonce="V09URkROREp3TFdvSmFjbTUrNlh4Yndrb1Jya2tJZUtBak55VW5EUnZmMD06Rjc2T1FKNytnZUh2WFpOU3FZL0R2ZWhuMGxIVHBjbnVRRVZGTURtaDJMbz0=" defer src="/core/l10n/eu.js?v=9fa0ea43-0"></script>
nextcloud-demo-iametza-onlyoffice | <script nonce="V09URkROREp3TFdvSmFjbTUrNlh4Yndrb1Jya2tJZUtBak55VW5EUnZmMD06Rjc2T1FKNytnZUh2WFpOU3FZL0R2ZWhuMGxIVHBjbnVRRVZGTURtaDJMbz0=" defer src="/dist/core-files_fileinfo.js?v=9fa0ea43-0"></script>
nextcloud-demo-iametza-onlyoffice | <script nonce="V09URkROREp3TFdvSmFjbTUrNlh4Yndrb1Jya2tJZUtBak55VW5EUnZmMD06Rjc2T1FKNytnZUh2WFpOU3FZL0R2ZWhuMGxIVHBjbnVRRVZGTURtaDJMbz0=" defer src="/dist/core-files_client.js?v=9fa0ea43-0"></script>
nextcloud-demo-iametza-onlyoffice | <script nonce="V09URkROREp3TFdvSmFjbTUrNlh4Yndrb1Jya2tJZUtBak55VW5EUnZmMD06Rjc2T1FKNytnZUh2WFpOU3FZL0R2ZWhuMGxIVHBjbnVRRVZGTURtaDJMbz0=" defer src="/js/core/merged-template-prepend.js?v=9fa0ea43-0"></script>
nextcloud-demo-iametza-onlyoffice | <script nonce="V09URkROREp3TFdvSmFjbTUrNlh4Yndrb1Jya2tJZUtBak55VW5EUnZmMD06Rjc2T1FKNytnZUh2WFpOU3FZL0R2ZWhuMGxIVHBjbnVRRVZGTURtaDJMbz0=" defer src="/apps/comments/l10n/eu.js?v=9fa0ea43-0"></script>
nextcloud-demo-iametza-onlyoffice | <script nonce="V09URkROREp3TFdvSmFjbTUrNlh4Yndrb1Jya2tJZUtBak55VW5EUnZmMD06Rjc2T1FKNytnZUh2WFpOU3FZL0R2ZWhuMGxIVHBjbnVRRVZGTURtaDJMbz0=" defer src="/dist/comments-comments-app.js?v=9fa0ea43-0"></script>
nextcloud-demo-iametza-onlyoffice | <script nonce="V09URkROREp3TFdvSmFjbTUrNlh4Yndrb1Jya2tJZUtBak55VW5EUnZmMD06Rjc2T1FKNytnZUh2WFpOU3FZL0R2ZWhuMGxIVHBjbnVRRVZGTURtaDJMbz0=" defer src="/apps/files_sharing/l10n/eu.js?v=9fa0ea43-0"></script>
nextcloud-demo-iametza-onlyoffice | <script nonce="V09URkROREp3TFdvSmFjbTUrNlh4Yndrb1Jya2tJZUtBak55VW5EUnZmMD06Rjc2T1FKNytnZUh2WFpOU3FZL0R2ZWhuMGxIVHBjbnVRRVZGTURtaDJMbz0=" defer src="/dist/accessibility-accessibilityoca.js?v=9fa0ea43-0"></script>
nextcloud-demo-iametza-onlyoffice | <script nonce="V09URkROREp3TFdvSmFjbTUrNlh4Yndrb1Jya2tJZUtBak55VW5EUnZmMD06Rjc2T1FKNytnZUh2WFpOU3FZL0R2ZWhuMGxIVHBjbnVRRVZGTURtaDJMbz0=" defer src="/custom_apps/side_menu/js/sideMenu.js?v=9fa0ea43-0"></script>
nextcloud-demo-iametza-onlyoffice | 		<link rel="stylesheet" media="(prefers-color-scheme: dark)" href="/apps/accessibility/css/user-a82fd95db10ff25dfad39f07372ebe37"/><link rel="stylesheet" href="/apps/side_menu/css/stylesheet?v=0"></link><script defer nonce="V09URkROREp3TFdvSmFjbTUrNlh4Yndrb1Jya2tJZUtBak55VW5EUnZmMD06Rjc2T1FKNytnZUh2WFpOU3FZL0R2ZWhuMGxIVHBjbnVRRVZGTURtaDJMbz0=" src="/apps/side_menu/js/script?v=0"></script>	</head>
nextcloud-demo-iametza-onlyoffice | 	<body id="body-login">
nextcloud-demo-iametza-onlyoffice | 		<noscript>
nextcloud-demo-iametza-onlyoffice | 	<div id="nojavascript">
nextcloud-demo-iametza-onlyoffice | 		<div>
nextcloud-demo-iametza-onlyoffice | 			Aplikazio honek JavaScript eskatzen du ondo funtzionatzeko. Mesedez <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">JavaScript gaitu</a> eta webgunea birkargatu.		</div>
nextcloud-demo-iametza-onlyoffice | 	</div>
nextcloud-demo-iametza-onlyoffice | </noscript>
nextcloud-demo-iametza-onlyoffice | 					<input type="hidden" id="initial-state-comments-max-message-length" value="MTAwMA==">
nextcloud-demo-iametza-onlyoffice | 					<input type="hidden" id="initial-state-comments-maxAutoCompleteResults" value="MTA=">
nextcloud-demo-iametza-onlyoffice | 					<input type="hidden" id="initial-state-accessibility-data" value="eyJjaGVja01lZGlhIjpmYWxzZSwidGhlbWUiOmZhbHNlLCJoaWdoY29udHJhc3QiOmZhbHNlfQ==">
nextcloud-demo-iametza-onlyoffice | 				<div class="wrapper">
nextcloud-demo-iametza-onlyoffice | 			<div class="v-align">
nextcloud-demo-iametza-onlyoffice | 									<header role="banner">
nextcloud-demo-iametza-onlyoffice | 						<div id="header">
nextcloud-demo-iametza-onlyoffice | 							<div class="logo">
nextcloud-demo-iametza-onlyoffice | 								<h1 class="hidden-visually">
nextcloud-demo-iametza-onlyoffice | 									Nextcloud	</h1>
nextcloud-demo-iametza-onlyoffice | 											</div>
nextcloud-demo-iametza-onlyoffice | 						</div>
nextcloud-demo-iametza-onlyoffice | 					</header>
nextcloud-demo-iametza-onlyoffice | 								<main>
nextcloud-demo-iametza-onlyoffice | 					<div class="error error-wide">
nextcloud-demo-iametza-onlyoffice | 	<h2>Zerbitzariaren barne-errorea</h2>
nextcloud-demo-iametza-onlyoffice | 	<p>Zerbitzariak ezin izan du zure eskaera bete.</p>
nextcloud-demo-iametza-onlyoffice | 	<p>Berriz gertatzen bada, mesedez bidali ondoko datu teknikoak zure administratzaileari.</p>
nextcloud-demo-iametza-onlyoffice | 	<p>Xehetasun gehiago zerbitzariaren egunkarian aurki daitezke.</p>
nextcloud-demo-iametza-onlyoffice | 
nextcloud-demo-iametza-onlyoffice | 	<h3>Xehetasun teknikoak</h3>
nextcloud-demo-iametza-onlyoffice | 	<ul>
nextcloud-demo-iametza-onlyoffice | 		<li>Urruneko helbidea: 172.22.0.1</li>
nextcloud-demo-iametza-onlyoffice | 		<li>Eskariaren IDa: UlVWxWrW2OmoNBZcU4xw</li>
nextcloud-demo-iametza-onlyoffice | 			</ul>
nextcloud-demo-iametza-onlyoffice | 
nextcloud-demo-iametza-onlyoffice | 	</div>
nextcloud-demo-iametza-onlyoffice | 				</main>
nextcloud-demo-iametza-onlyoffice | 			</div>
nextcloud-demo-iametza-onlyoffice | 		</div>
nextcloud-demo-iametza-onlyoffice | 		<footer role="contentinfo">
nextcloud-demo-iametza-onlyoffice | 			<p class="info">
nextcloud-demo-iametza-onlyoffice | 				<a href="https://nextcloud.com" target="_blank" rel="noreferrer noopener" class="entity-name">Nextcloud</a> – zure datu guztientzako toki segurua			</p>
nextcloud-demo-iametza-onlyoffice | 		</footer>
nextcloud-demo-iametza-onlyoffice | 	</body>
nextcloud-demo-iametza-onlyoffice | </html>
nextcloud-demo-iametza-onlyoffice | 
nextcloud-demo-iametza-onlyoffice |     at Request._callback (/snapshot/server/build/server/Common/sources/utils.js)
nextcloud-demo-iametza-onlyoffice |     at Request.callback (/snapshot/server/build/server/Common/node_modules/request/request.js:185:22)
nextcloud-demo-iametza-onlyoffice |     at Request.emit (events.js:400:28)
nextcloud-demo-iametza-onlyoffice |     at Request.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1154:10)
nextcloud-demo-iametza-onlyoffice |     at Request.emit (events.js:400:28)
nextcloud-demo-iametza-onlyoffice |     at IncomingMessage.<anonymous> (/snapshot/server/build/server/Common/node_modules/request/request.js:1076:12)
nextcloud-demo-iametza-onlyoffice |     at Object.onceWrapper (events.js:519:28)
nextcloud-demo-iametza-onlyoffice |     at IncomingMessage.emit (events.js:412:35)
nextcloud-demo-iametza-onlyoffice |     at endReadableNT (internal/streams/readable.js:1317:12)
nextcloud-demo-iametza-onlyoffice |     at processTicksAndRejections (internal/process/task_queues.js:82:21)
nextcloud-demo-iametza-onlyoffice | [2022-08-11T14:07:34.312] [WARN] nodeJS - commandSfcCallback backoff limit exceeded: docId = 3878033061
nextcloud-demo-iametza-onlyoffice | [2022-08-11T14:07:34.313] [WARN] nodeJS - storeForgotten: docId = 3878033061`

**Comment by enbata** [comment]
Most clearly, the error is this one:

Call to a member function getId() on bool in file '/var/www/html/apps/files_versions/lib/Storage.php' line 197

The versioning APP is crashing when try to create a new version.

When we disable this APP, the changes are saved with no problems.

**Comment by cheneraie** [comment]
Same error for us.

File in SMB storage → shared with another user → modifications by this another user are not saved.
Log = « Call to a member function getId() on bool in file '/var/www/html/apps/files_versions/lib/Storage.php' line 197 »

**When I disable the Versions app, the problem is solved.**

Nextcloud 23.0.8, Versions 1.17.

**Comment by MaadixNet** [comment]
Same error for different installations.
It appears in :
Nextcloud 24.0.2  - Versions 1.17.0
Nextcloud 22.2.0  - Versions 1.15.0

**Comment by rosa2** [comment]
Hello
Same error with Nextcloud 24.0.2 - Versions 1.17.0

I have being searching and I think it is a regression because it started to happen when we updated to 24.0.2

After some users reported that saves weren't saved (not always), we have being testing a lot. When user closes the document after waiting 5 seconds, we don't get any error, but the document is not saved and doesn't appears in Versions or Activity. We get the error if in OnlyOffice when we save by the menu

`Exception: Call to a member function getId() on bool in file '/var/www/nextcloud/nextcloud/apps/files_versions/lib/Storage.php' line 197`

Just in case that this helps on the solution, i put other issues on richdocuments and OnlyOffice that had this problem and they solved.

https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/118
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/pull/162
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/660
https://github.com/nextcloud/richdocuments/issues/781
https://github.com/nextcloud/richdocuments/issues/780

The temporary solution to disable Versions for us is very bad because we work many people in different documents and need to be able to recover versions.

We notice also that the Activity fails to write when changes are made
 Activity 2.16.0

Thanks a lot for NextCloud :)

**Comment by enbata** [comment]
OK, with the last version of 'files_versions' app the problem is solved [files_versions](https://github.com/nextcloud/server/tree/master/apps/files_versions).


For who uses docker, get the last version of the using image (with docker-composer):
`# docker-compose pull
# docker-compose up -d`

Regards
