### ISSUE TITLE
Grid view not working as expected

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/server#3351]
Instead of displaying the grid view of the documents (i.e. PDF files), an empty page comes up with the text "No media files found".

![auswahl_001](https://cloud.githubusercontent.com/assets/24833757/22509906/33c2d9f6-e890-11e6-87a2-3ff618616aae.png)

Confusing. I don't expect the gallery view behind the grid view button.

![auswahl_002](https://cloud.githubusercontent.com/assets/24833757/22509910/39b5b630-e890-11e6-8447-0423d59035fe.png)

**Comment by nickvergessen** [comment]
Currently we don't have a grid-view, only the gallery.
Since PDFs are no images they don't show up here.

**Comment by nickvergessen** [comment]
Grid view request for all files is at #6

**Comment by Sanookmakmak** [comment]
> Currently we don't have a grid-view

A good example of a grid view is Google Drive.

;-)

**Comment by rebeccaformfx** [comment]
I am strongly +1-ing this.  Grid layout is an important usability feature and makes organizing files much more intuitive.  Please consider adding this to the UI.  The icon you have chosen for Gallery looks far more like a Grid View controller than a gallery, which I would expect to be an icon that looks like a picture frame.
