### ISSUE TITLE
Make the "reloading page in 5 seconds" count down

### ISSUE THREAD

**Issue by MG2R** [nextcloud/server#3354]
### Steps to reproduce
1. Have problems loading the page data

### Expected behaviour
Have a timer which counts down to the reload

### Actual behaviour
A static message says the page will be reloaded in 5 seconds

This is a pretty trivial change, but it is one I'd like to implement nonetheless. I went looking through the repository, but I can only seem to find the message itself, not where it is called. I'm pretty new to this project, can someone point me in the right direction?

**Comment by nickvergessen** [comment]
@nextcloud/javascript

**Comment by ChristophWurst** [comment]
Hey @MG2R,

this sounds like a nice enhancement and a good starting point for learning more about the code base. You can start here: https://github.com/nextcloud/server/blob/b946ec9d6cb987afae9c4ffd2a6efff5f18c41c9/core/js/js.js#L766-L797 😉

**Comment by MorrisJobke** [comment]
@stephanruttloff - yeah - I know you are busy 😉 but maybe you are just waiting for the perfect mention 😄

**Comment by MG2R** [comment]
I'm working on this, however I find it difficult to reliably get the relevant code to fire. Got any ideas to reliably fail the correct requests upon loading the user's file list?

**Comment by MorrisJobke** [comment]
> I'm working on this, however I find it difficult to reliably get the relevant code to fire. Got any ideas to reliably fail the correct requests upon loading the user's file list? (not quite the JS expert here ;) )

What I did: I pasted the code in the JS console in the browser ;)

**Comment by MG2R** [comment]
Hm, apparently I missed #3371. Seems there's not much point for this ticket to exist?

**Comment by MorrisJobke** [comment]
> Hm, apparently I missed #3371. Seems there's not much point for this ticket to exist?

Oh - I mixed you up with @m3ntalsp00n ... This ticket still exists, because it is not yet fully solved, but there is a proposal for a fix.  @MG2R Maybe help to review it. Try out the code and check if it runs properly. Then comment in the pull request that it works (or not) :) Thanks for helping here

**Comment by MorrisJobke** [comment]
#3371 was merged
