### ISSUE TITLE
Primary/Secondary choosing querybuilder

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#33542]
In case of write operations mark table as dirty and if read request comes in _and_ table is in a "primary-enforced reads after writes list", so primary-forced reads only happen if write happen and table is configured in the static list where this behavior needs to happen.

**Comment by CarlSchwan** [comment]
We could use something like this https://github.com/nalgoo/cluster-connection to determine to which nodes to send the DB query

**Comment by juliushaertl** [comment]
- Figure out a test setup for a cluster through docker
- Try wrapping dbal PrimaryReadReplicaConnection into our connection handling
- To discuss: Do we need separate handling of core/app code
- To discuss: Do we need a way for apps to manually decide to pick primary/replica

**Comment by mickenordin** [comment]
I think this would be very useful to get high availability with the use of proxysql or similar software proxies in between nextcloud and the database cluser. If I can help out in any way, I will. I have many Galera clusters where Nextcloud is running that I can test stuff out on.

**Comment by ChristophWurst** [comment]
28 port for pre-production testing: https://github.com/nextcloud/server/pull/43261
