### ISSUE TITLE
App name is not shown / positioned correct

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#3355]
### Expected behaviour
App name "Files" shown; App name "Video calls" (works for other apps) should be positioned correct.

### Actual behaviour
Shows "Apps" instead; App name "Video calls" (works for other apps) is positioned in Nextcloud logo;

<img width="524" alt="bildschirmfoto 2017-02-01 um 20 04 41" src="https://cloud.githubusercontent.com/assets/19711361/22521994/39069ab8-e8ba-11e6-8316-cd9f43719232.png">

<img width="368" alt="bildschirmfoto 2017-02-01 um 20 10 22" src="https://cloud.githubusercontent.com/assets/19711361/22522085/9b761048-e8ba-11e6-964c-839839201e82.png">

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Apache
**Database:**
sqlite3
**PHP version:**
7.1
**Nextcloud version:** (see Nextcloud admin page)
12.0 alpha Build:2017-01-31T22:01:17+00:00 db5af891c3c9536faf1f0a62374459242bfeedaf

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Where did you install Nextcloud from:**
daily build

### Client configuration
**Browser:**
Safari 10.1
**Operating system:**
macOS 10.12.4 beta

**Comment by nickvergessen** [comment]
Yeah actually it's the public page code of the spreed app which breaks this:
https://github.com/nextcloud/spreed/issues/239
