### ISSUE TITLE
Search post processing is taking a lot of time > 7000 queries

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#33554]
Possible fix: https://github.com/nextcloud/server/pull/33550

**Comment by PVince81** [comment]
@icewind1991 the PR is merged

can you provide before/after measurements before closing ?

**Comment by icewind1991** [comment]
https://github.com/nextcloud/server/pull/33550 seems to work as expected

- 3368 -> 227 for search
- 3375 -> 528 for recent

Have some ideas for the remaining ones that I'll investigate before closing this

**Comment by icewind1991** [comment]
I'll trigger the backports

With https://github.com/nextcloud/server/pull/33574

- 50 for search
- 340 for recent

Recent is mostly larger because of a larger result set, more improvements can probably be done but I'll close this for now.

**Comment by icewind1991** [comment]
With https://github.com/nextcloud/server/pull/33575/commits

- 50 for search
- 153 for recent
