### ISSUE TITLE
Allow to set the homepage from the UI

### ISSUE THREAD

**Issue by melMass** [nextcloud/server#33560]
Hi,

### The problem
I'm using NextCloud on an [Hetzner instance](https://www.hetzner.com/storage/storage-share), as they control the shared server we only have access to admin stuff from the GUI. It's mostly enough for my needs but one thing I find very frustrating and that IMO should be fixed upstream (here) is the homepage selection. I want all my new user (myself included) to be redirected to the files section of next cloud, there is a way to do that apparently if you control the server using [App Order](https://apps.nextcloud.com/apps/apporder).

### Expects
A simple setting to control where users/groups are redirected on login from the GUI only (no server access/control).

Thanks

**Comment by kesselb** [comment]
Thanks for your feature request :+1: 

Available with Nextcloud 28: https://github.com/nextcloud/server/issues/40241

**Comment by melMass** [comment]
Much appreciated! Let's hope hetzner update it soonish, they usually do
