### ISSUE TITLE
 NC 11.0.1 Show version Bug

### ISSUE THREAD

**Issue by andypl78** [nextcloud/server#3356]
After the upgrade to the latest version Nextcloud have info
In config.php have `'version' => '11.0.1.2',`

![nt-ver](https://cloud.githubusercontent.com/assets/7813646/22549892/e2721814-e94d-11e6-9afb-0eb52834a27a.jpg)

**Comment by nickvergessen** [comment]
The 4th digit is an internal counter only. 

But weird that you see the update message, while you already updated.

**Comment by MorrisJobke** [comment]
Looks like a not cleared cache. We did quite some overhaul on this lately. Could you check if the message is gone once you change the channel to another one and back to stable?

This should solve this issue and in future versions of 11.0.1 we didn't see this anymore. So I will close this ticket here.
