### ISSUE TITLE
[Bug]: Creating new (database) user show misleading error message and loses data

### ISSUE THREAD

**Issue by kesselb** [nextcloud/server#33572]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

[Screencast from 17.08.2022 11:37:45.webm](https://user-images.githubusercontent.com/3902676/185087099-bdc6e7e2-7501-43af-abd3-da2c0dd03f83.webm)

### Steps to reproduce

Tested on

[38037c8de461e6605b96383f841f91593226a54f](https://github.com/nextcloud/server/pull/33001/commits/38037c8de461e6605b96383f841f91593226a54f)

 [312b719acf686f51065e83290cd88704d703a50c](https://github.com/nextcloud/server/commit/312b719acf686f51065e83290cd88704d703a50c)
 (hard to reproduce as something with the password confirmation dialog is broken)

1. Go to users manager
2. Click New User
3. Fill out the form (use a available user name)
4. Click Add a new user
5. See a warning "User already exist"
6. Reload the page
7. User is there but email is missing

### Expected behavior

- No "User already exist" warning
- Attributes like email is saved

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Doom 2
```

### Additional info

Looks like a regression of https://github.com/nextcloud/server/pull/33052

setDisplayName returns false for various cases. For example:
- the display name is already up to date
- backend does not support editing a display name

Example request:

```fetch("http://__SERVERURL__/ocs/v2.php/cloud/users", {
  "headers": {
    "accept": "application/json, text/plain, */*",
    "accept-language": "en-US,en;q=0.9",
    "content-type": "application/json",
    "requesttoken": "__REQUESTTOKEN__"
  },
  "referrerPolicy": "no-referrer",
  "body": "{\"userid\":\"user3\",\"password\":\"rohkohYe7osh\",\"displayName\":\"user3\",\"email\":\"test+user3@kesselb.dev\",\"groups\":[],\"subadmin\":[],\"quota\":\"default\",\"language\":\"en\"}",
  "method": "POST",
  "mode": "cors",
  "credentials": "include"
});
```

**Comment by PVince81** [comment]
@Pytal can you double check ?

**Comment by PVince81** [comment]
note: user creation works for me with occ on master, so maybe it's specific to the web UI flow

**Comment by Pytal** [comment]
Fixed in https://github.com/nextcloud/server/pull/33625

**Comment by Pytal** [comment]
> note: user creation works for me with occ on master, so maybe it's specific to the web UI flow

On `master` when entering the same Username and Display name `displayName` will match `oldDisplayName` so this condition fails https://github.com/nextcloud/server/blob/4a77a687343c3c858051cefeab3ac800504baafe/lib/private/User/User.php#L161 making the function return false and then throwing which skips saving the user email and displays the misleading error message
