### ISSUE TITLE
[Bug]: Typo "Organisation" On Settings>Personal Info

### ISSUE THREAD

**Issue by MrMetacomCode** [nextcloud/server#33587]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On the Personal Info page under settings the word "Organisation" is misspelled.

### Steps to reproduce

1. Go to settings.
2. Go to personal info.
3. Realize there's a typo.

### Expected behavior

There to not be a typo.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Honestly couldn't get any of these commands to work cause I'm not smart.
```

**Comment by andyxheli** [comment]
Is not really a typo organization is used in American English, while both organization and organisation can be used in British English to. so organisation  is used in the British English

**Comment by szaimen** [comment]
all right, then closing
