### ISSUE TITLE
Wiki update needed 

### ISSUE THREAD

**Issue by Spartachetto** [nextcloud/server#33585]
The [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) page needs an update. 

Both rows for 23 and 24 are outdated, as they list as **next** version 23.0.8 and 24.0.4 which are already released. In fact for both of them the release date of the next version is in the past

**Comment by szaimen** [comment]
cc @AndyScherzinger

**Comment by AndyScherzinger** [comment]
Thanks for the ping @Spartachetto 🙏 Updated just now 👍
