### ISSUE TITLE
Raise for all teams: use display name cache

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#33589]
- Activity providers
- Notification providers
- spreed/lib/Chat/Parser/UserMention.php 94
- comments mentions
- apps/user_status/lib/Dashboard/UserStatusWidget.php

**Comment by nickvergessen** [comment]
IUserManager::getDisplayName is a heavily cached method. When only the display name of a user is required. It reduces roughly 1-2 query per existing user backend database queries.

The method is new in 25, so when the minimum version of the app allows it please use this. Prime examples as per above are rendering activities and notifications and similar things.

Please raise for your teams and apps:
- [ ] Groupware @ChristophWurst 
- [ ] Office @juliushaertl 
- [ ] Talk @nickvergessen 
- [ ] Server @PVince81

**Comment by PVince81** [comment]
does LazyUser also count as display name cache ? because I saw a bunch of PRs from @icewind1991 for using that as well

**Comment by nickvergessen** [comment]
Yes, LazyUser uses the cache iirc

**Comment by nickvergessen** [comment]
@PVince81 shall we close as all teams reacted? You can create a follow up for server if you think it makes sense, but a generic ticket for server is probably also not helpful and fixes must be applied once a spot is found.
