### ISSUE TITLE
[Bug]: Used space and icon are not aligned properly

### ISSUE THREAD

**Issue by karlitschek** [nextcloud/server#33583]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Used space and icon are not aligned properly.
Server version: 24.0.4rc1
Visible on Chrome and Safari / MacOS

<img width="376" alt="Screenshot 2022-08-17 at 15 03 48" src="https://user-images.githubusercontent.com/867445/185141945-1d8bb247-7c13-46d8-a3bb-6965f616cb60.png">

### Steps to reproduce

1. look at the files sidebar
2. ??
3. profit

### Expected behavior

text is aligned like the 'deleted files'

### Installation method

Other

### Operating system

Other

### PHP engine version

Other

### Web server

Other

### Database engine version

Other

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
..
```

### List of activated Apps

```shell
..
```

### Nextcloud Signing status

```shell
..
```

### Nextcloud Logs

```shell
..
```

### Additional info

..

**Comment by krillinkills** [comment]
are you still working on this or i can take it?

**Comment by arnavk1872** [comment]
Working on this issue.

**Comment by Arpit-Gulgulia** [comment]
Just a basic CSS fix should fix the issue. Can I work on and create a PR for this issue?

**Comment by szaimen** [comment]
I think this is fixed with nc26, right?
