### ISSUE TITLE
Restoring items from the recycle bin is based on the parent folder's name and not its database ID (I explain why this is a problem).

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/server#33621]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 
Hi !

**Is your feature request related to a problem? Please describe.**
Restoring items from the recycle bin is based on the parent folder's label and not its database ID, is this relevant?
In my humble opinion, when restoring an item that is in the trash, it should be restored to its parent folder, even if it has been renamed or moved in the meantime.
But this is not the case? If the parent folder has been renamed or moved in the meantime (or an intermediate folder has been renamed), the restored file is moved to the root. Do you think this is relevant? I think not, but that's just my opinion.
Shouldn't the restoration of a file (and its belonging to a parent folder before deletion) be based on the folder ID in the database and not on its name, which could have the advantage that the file is restored to the right place, whether the parent folder has been renamed and/or moved in the meantime?
The only case where the restored file should be in the root would be if the parent folder (direct parent) has been deleted (regardless of whether it has been renamed and/or moved).

**Describe the solution you'd like**
The restoration of a file (and its belonging to a parent folder before deletion) should be based on the folder ID in the database and not on its name

**Additional context**
Same for deleted folders.

Best regards,
Jérôme

**Comment by despens** [comment]
Related: #31200
