### ISSUE TITLE
sharing with comment/suggest rights

### ISSUE THREAD

**Issue by KiaraGrouwstra** [nextcloud/server#33628]
**Is your feature request related to a problem? Please describe.**
As a person sharing documents with colleagues, I would like to be able to request feedback without having to give out the right to edit my documents.

**Describe the solution you'd like**
A permission sharing system more similar to that of GDocs, where aside from permission to read or edit a document, there is an intermediate option for non-destructive additions, in their case to allow editing suggestions and comments.

**Describe alternatives you've considered**
Use GDocs instead

**Additional context**
What qualifies as non-destructive depends on the file format, which makes implementing this feature perhaps non-trivial.

**Comment by joshtrichards** [comment]
Related: nextcloud/richdocuments#1896

**Comment by KiaraGrouwstra** [comment]
thanks, closing as duplicate then
