### ISSUE TITLE
Continuous integration tests for Postgres 14

### ISSUE THREAD

**Issue by Chartman123** [nextcloud/server#33655]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
docs.nextcloud.com currently doesn't state that PostgreSQL 14 are supported. 

**Describe the solution you'd like**
To make sure it is supported the Postgres version should be added to the integration tests so that it can then be added to the docs

**Describe alternatives you've considered**
Keep older Postgres versions

**Comment by joshtrichards** [comment]
It does today. :) We test up to PG15. Also the docs have since bee updated.
