### ISSUE TITLE
Add "Prohibit to download" or like features to user share (not public share)

### ISSUE THREAD

**Issue by s8321414** [nextcloud/server#33666]
Please add "Prohibit to download" or like features to user share (or internal share link, but not public share link). 
It is good to some use cases. :smiley:

**Comment by csware** [comment]
Does this make any sense? When I use the sync client I already have the files and when I use the web UI I can just copy the files to some other folder.

**Comment by joshtrichards** [comment]
Duplicate of #16413 
Closed by #32482
