### ISSUE TITLE
Files downloaded notification - when thumbnail is displayed in Recommended files on dashboard

### ISSUE THREAD

**Issue by aquananu** [nextcloud/server#33687]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If we have shared any file via deck card or in talk, the icon of same is displayed in the recommended files app on the dashboard.

everytime a user logs on and the thumbnails are generated which is triggering the notification that the file was downloaded, whereas the user hasnt clicked on the file to download the same. This is generating a lot of notification and the useful ones are getting lost in the heap.

The notification should not get triggered if the icon is displayed in the app dashboard.

kindly change necessary code

### Steps to reproduce

1. upload a file on card on a board of deck, the board should be shared one or more people
2. ask the other user to login to the nextcloud
3. on the dashboard of the other user the recommend files app dashboard should be present
4. the notification of file download by the other user will appear for all png jpg or pic file whose thumbnails can be shown
5. the notification will be there every time the user logs on or visits the dashboard
6.

### Expected behavior

the notification should not be triggered if the files are getting listed in the dashboard Recommended files list

### What user-backends are you using?

- [ ] Default user-backend _(database)_ yes
- [ ] LDAP/ Active Directory yes
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "log_type": "file",
        "logfile": "\/var\/snap\/nextcloud\/current\/logs\/nextcloud.log",
        "logfilemode": 416,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.3.2",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "IN",
        "maintenance": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 2,
        "app_install_overwrite": [
            "flowupload"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - analytics: 4.3.1
  - announcementcenter: 6.3.1
  - appointments: 1.12.7
  - apporder: 0.15.0
  - approval: 1.0.10
  - backup: 1.1.2
  - bruteforcesettings: 2.4.0
  - calendar: 3.4.3
  - cloud_federation_api: 1.7.0
  - collectives: 1.4.3
  - comments: 1.14.0
  - contacts: 4.2.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - data_request: 1.11.0
  - dav: 1.22.0
  - deck: 1.7.1
  - duplicatefinder: 0.0.15
  - emlviewer: 1.0.2
  - end_to_end_encryption: 1.10.0
  - event_update_notification: 1.5.0
  - external: 4.0.0
  - extract: 1.3.5
  - federatedfilesharing: 1.14.0
  - files: 1.19.0
  - files_accesscontrol: 1.14.1
  - files_automatedtagging: 1.14.0
  - files_downloadactivity: 1.13.0
  - files_lock: 24.0.1
  - files_pdfviewer: 2.5.0
  - files_retention: 1.13.2
  - files_rightclick: 1.3.0
  - files_scripts: 1.1.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - files_zip: 1.1.2
  - firstrunwizard: 2.13.0
  - flow_notifications: 1.4.0
  - flowupload: 1.1.3
  - forms: 2.5.1
  - geoblocker: 0.5.6
  - gestion: 2.1.6
  - groupfolders: 12.0.1
  - hidesidebars: 2.1.0
  - impersonate: 1.11.0
  - ldap_contacts_backend: 1.4.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - ncdownloader: 1.0.1
  - nextcloud_announcements: 1.13.0
  - notes: 4.5.0
  - notifications: 2.12.0
  - notify_push: 0.4.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - phonetrack: 0.7.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - quota_warning: 1.14.0
  - ransomware_protection: 1.13.0
  - recommendations: 1.3.0
  - richdocuments: 6.2.0
  - richdocumentscode: 22.5.502
  - root_cache_cleaner: 0.1.2
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - side_menu: 2.4.3
  - spreed: 14.0.4
  - support: 1.7.0
  - survey_client: 1.12.0
  - suspicious_login: 4.2.0
  - systemtags: 1.14.0
  - tables: 0.2.0
  - talk_matterbridge: 1.25.2
  - talked: 0.4.0
  - tasks: 0.14.4
  - text: 3.5.1
  - theming: 1.15.0
  - transfer: 0.6.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_gateway: 0.20.0
  - user_ldap: 1.14.1
  - user_migration: 1.1.0
  - user_status: 1.4.0
  - user_usage_report: 1.8.0
  - viewer: 1.8.0
  - w2g2: 3.3.9
  - webhooks: 0.4.0
  - workflowengine: 2.6.0
Disabled:
  - circles: 24.0.0
  - encryption
  - facerecognition
  - federation: 1.14.0
  - files_external
  - mail: 1.13.8
  - weather_status: 1.4.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
see attached log
```z


### Additional info

**Comment by aquananu** [comment]
adding log file
[nextcloud.log](https://github.com/nextcloud/server/files/9422540/nextcloud.log)
[cloud.xxxxxxx.com-1661409127373.log](https://github.com/nextcloud/server/files/9422541/cloud.xxxxxxx.com-1661409127373.log)
s

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by aquananu** [comment]
Hi I am using snap, it's still on 25.0.2.

Once it gets updated, will surely let you know

Navneet kakkar

**Comment by szaimen** [comment]
Please report this to files_downloadactivity. Thanks!
