### ISSUE TITLE
Integration of Zulip

### ISSUE THREAD

**Issue by Iwios** [nextcloud/server#33693]
Hello, 
I've find a rocketchat plugin to connect Nextcloud and rocketchat..

I use Zulip instead of rocketchat, it's possible to develop a plugin to connect to zulip with nextcloud account ?

**Comment by solracsf** [comment]
Yes, it is possible, but this has nothing to do with Nextcloud Server, sorry.
Please ask the community at https://help.nextcloud.com
Thanks for understanding 👍
