### ISSUE TITLE
Sharing of folders are not possible

### ISSUE THREAD

**Issue by CordlessWool** [nextcloud/server#3369]
Here are all the details to my configs, there are lots of error since the update: https://github.com/nextcloud/server/issues/3296

This is the error log, of sharing a folder by link and try to open it.
The link is password protected and all data on the server are encrypted.
After enter the password on the top appears an error message and it is only shown an empty folder.
There should be two files.
From an other account is a pdf file shared, only one file and its works.

Error	no app in context	OC\User\NoUserException: Backends provided no user object

    [internal function] OC\Files\Node\Root->getUserFolder(NULL)
    /var/www/html/lib/private/Files/Node/LazyRoot.php - line 65: call_user_func_array(Array, Array)
    /var/www/html/lib/private/Files/Node/LazyRoot.php - line 282: OC\Files\Node\LazyRoot->__call('getUserFolder', Array)
    /var/www/html/apps/files_downloadactivity/lib/Activity/Listener.php - line 141: OC\Files\Node\LazyRoot->getUserFolder(NULL)
    /var/www/html/apps/files_downloadactivity/lib/Activity/Listener.php - line 77: OCA\FilesDownloadActivity\Activity\Listener->getSourcePathAndOwner('/koala/files_en...')
    /var/www/html/apps/files_downloadactivity/lib/AppInfo/Application.php - line 47: OCA\FilesDownloadActivity\Activity\Listener->readFile('/koala/files_en...')
    [internal function] OCA\FilesDownloadActivity\AppInfo\Application->listenReadFile(Array)
    /var/www/html/lib/private/legacy/hook.php - line 106: call_user_func(Array, Array)
    /var/www/html/lib/private/Files/View.php - line 1245: OC_Hook emit('OC_Filesystem', 'read', Array)
    /var/www/html/lib/private/Files/View.php - line 1113: OC\Files\View->runHooks(Array, '/koala/files_en...')
    /var/www/html/lib/private/Files/View.php - line 577: OC\Files\View->basicOperation('file_get_conten...', '/koala/files_en...', Array)
    /var/www/html/lib/private/Encryption/Keys/Storage.php - line 195: OC\Files\View->file_get_contents('/koala/files_en...')
    /var/www/html/lib/private/Encryption/Keys/Storage.php - line 84: OC\Encryption\Keys\Storage->getKey('/koala/files_en...')
    /var/www/html/apps/encryption/lib/KeyManager.php - line 402: OC\Encryption\Keys\Storage->getFileKey('/koala/files/Do...', 'fileKey', 'OC_DEFAULT_MODU...')
    /var/www/html/apps/encryption/lib/Crypto/Encryption.php - line 195: OCA\Encryption\KeyManager->getFileKey('/koala/files/Do...', NULL)
    /var/www/html/lib/private/Files/Stream/Encryption.php - line 258: OCA\Encryption\Crypto\Encryption->begin('/koala/files/Do...', NULL, 'r', Array, Array)
    [internal function] OC\Files\Stream\Encryption->stream_open('ocencryption //', 'r', 0, NULL)
    /var/www/html/lib/private/Files/Stream/Encryption.php - line 198: fopen('ocencryption //', 'r', false, Resource id #185274)
    /var/www/html/lib/private/Files/Stream/Encryption.php - line 180: OC\Files\Stream\Encryption wrapSource(Resource id #185273, Resource id #185274, 'ocencryption', 'OC\\Files\\Stream...', 'r')
    /var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php - line 461: OC\Files\Stream\Encryption wrap(Resource id #185273, 'files/Documents...', '/koala/files/Do...', Array, NULL, Object(OCA\Encryption\Crypto\Encryption), Object(OC\Files\Storage\Wrapper\Quota), Object(OC\Files\Storage\Wrapper\Encryption), Object(OC\Encryption\Util), Object(OC\Encryption\File), 'r', 1939572, 1431542, 8192, true)
    /var/www/html/lib/private/Files/Storage/Wrapper/Wrapper.php - line 294: OC\Files\Storage\Wrapper\Encryption->fopen('files/Documents...', 'r')
    /var/www/html/lib/private/Files/View.php - line 1122: OC\Files\Storage\Wrapper\Wrapper->fopen('files/Documents...', 'r')
    /var/www/html/lib/private/Files/View.php - line 967: OC\Files\View->basicOperation('fopen', '/koala/files/Do...', Array, 'r')
    /var/www/html/lib/private/Files/View.php - line 978: OC\Files\View->fopen('/koala/files/Do...', 'r')
    /var/www/html/apps/nextant/lib/Service/FileService.php - line 263: OC\Files\View->toTmpFile('/koala/files/Do...')
    /var/www/html/apps/nextant/lib/Service/IndexService.php - line 273: OCA\Nextant\Service\FileService->generateAbsolutePath(Object(OCA\Nextant\Items\ItemDocument), Object(OCA\Nextant\Items\ItemError))
    /var/www/html/apps/nextant/lib/Command/Index.php - line 269: OCA\Nextant\Service\IndexService->extract('files', 'koala', Array, Array)
    /var/www/html/apps/nextant/lib/Command/Index.php - line 205: OCA\Nextant\Command\Index->indexesFiles(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    /var/www/html/3rdparty/symfony/console/Command/Command.php - line 256: OCA\Nextant\Command\Index->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    /var/www/html/core/Command/Base.php - line 161: Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    /var/www/html/3rdparty/symfony/console/Application.php - line 818: OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    /var/www/html/3rdparty/symfony/console/Application.php - line 186: Symfony\Component\Console\Application->doRunCommand(Object(OCA\Nextant\Command\Index), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    /var/www/html/3rdparty/symfony/console/Application.php - line 117: Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
    /var/www/html/lib/private/Console/Application.php - line 169: Symfony\Component\Console\Application->run(NULL, NULL)
    /var/www/html/console.php - line 90: OC\Console\Application->run()
    /var/www/html/occ - line 11: require_once('/var/www/html/c...')
    {main}

**Comment by nickvergessen** [comment]
Please report to the https://github.com/nextcloud/files_downloadactivity app
