### ISSUE TITLE
Updater failed - The Process class relies on proc_open, which is not available on your PHP installation

### ISSUE THREAD

**Issue by Rouzax** [nextcloud/server#337]
### Steps to reproduce
1. goto xxx.yyy/updater/

### Expected behaviour
Show the updater

### Actual behaviour
Gives an error

### Server configuration
**Operating system**:

**Web server:**

**Database:**
Mysql
**PHP version:**
5.6

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 9.0.50 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgrade from OC

**Where did you install Nextcloud from:**
tar

**Signing status (Nextcloud 9.0 and above):**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

```

Fatal error: Uncaught exception 'Symfony\Component\Process\Exception\RuntimeException' with message 'The Process class relies on proc_open, which is not available on your PHP installation.' in /home/xxx/public_html/_cloud/updater/vendor/symfony/process/Process.php:144 Stack trace: #0 /home/xxx/public_html/_cloud/updater/src/Utils/OccRunner.php(45): Symfony\Component\Process\Process->__construct('php /home/xxx/...') #1 /home/xxx/public_html/_cloud/updater/src/Utils/OccRunner.php(56): Owncloud\Updater\Utils\OccRunner->run('config:list --p...') #2 /home/xxx/public_html/_cloud/updater/src/Utils/ConfigReader.php(106): Owncloud\Updater\Utils\OccRunner->runJson('config:list --p...') #3 /home/xxx/public_html/_cloud/updater/src/Utils/ConfigReader.php(50): Owncloud\Updater\Utils\ConfigReader->load() #4 /home/xxx/public_html/_cloud/updater/src/Controller/IndexController.php(96): Owncloud\Updater\Utils\ConfigReader->init() #5 /home/xxx/public_html/_cloud/updater/src/Controller/IndexController.php(70): Owncloud\Updater\Control in /home/xxx/public_html/_cloud/updater/vendor/symfony/process/Process.php on line 144
```

**Comment by MorrisJobke** [comment]
@LukasReschke Caused by the old updater ...

@karlitschek Another argument to move to the new version ;)

**Comment by LukasReschke** [comment]
🙈 🙉 🙊

**Comment by MorrisJobke** [comment]
@Rouzax This is the old updater, that only works if you have this method available. This should also be listed in the admin settings check. Sadly we can't do much here for the old updater and we wrote a new one, that is a lot simpler and doesn't require this method anymore. Feel free to test it. See https://help.nextcloud.com/t/test-our-new-work-in-progress-upgrader-script/1214 for more details

**Comment by karlitschek** [comment]
@MorrisJobke Agreed. I'm just not sure we we still have the time to bring this into shape for the next release. Aka. Add the needed features and do testing. I suggest to do this for the next one.

**Comment by MorrisJobke** [comment]
> @MorrisJobke Agreed. I'm just not sure we we still have the time to bring this into shape for the next release. Aka. Add the needed features and do testing. I suggest to do this for the next one.

Therefore we only show this when a "I'm super sure to use this, because it is still in beta" config switch was set ;) Then eager people can set it and try the new updater without copying files around. And on the other side we are safe, because it is not enabled by default :)
