### ISSUE TITLE
OCS Share API - why is not possible to ‘hide download’ when creating a new share via the API?

### ISSUE THREAD

**Issue by dthory** [nextcloud/server#33717]
When creating a new share via the OCS API, why is not possible to specify ‘hide download’ as a POST argument / parameter? All the other options seem to be available that you can do via the web interface when creating a new public share e.g. add note, expiry date, password etc but not the hide download property. I have tried hideDownload=1  and hideDownload=true but neither works. 

Is this already available (and just not in the docs), or if not could it be added at some point soon please?

**Comment by SViarbitskaya** [comment]
same question..how to enable hide download via API?

**Comment by dthory** [comment]
See https://github.com/nextcloud/documentation/issues/9186 - i think this has been added

**Comment by skjnldsv** [comment]
It's supported, the api allows you to specify the attributes you want https://docs.nextcloud.com/server/latest/developer_manual/client_apis/OCS/ocs-share-api.html#share-attributes

**Comment by dthory** [comment]
Hi John

Thanks for this, is this a recent update or was it already implemented
a while ago? I'm using v27 so do you know if it would be available on v27
or current version only?

Best wishes
Dan

**Comment by skjnldsv** [comment]
Multiple PRs, but I think most of the polishing came for Nextcloud 30 :$

**Comment by dthory** [comment]
Can this be used in V29.0.6, I've tried the following [{"scope":"permissions","key":"download","enabled":"false"}] - serialized json as attributes argument but its still returning   <hide_download>0</hide_download> ? Thanks
