### ISSUE TITLE
How to add mail to everyone?

### ISSUE THREAD

**Issue by tach-tm** [nextcloud/server#33716]
I ask you not to be sent to the site https://help.nextcloud.com, it is blocked for me. I can not open.
it is necessary for all users to add mail as they have no mail. domain 1. For example: domain.com mail should be done like this user@domain.com

Somewhere I found such a script but I don't know how to use it.
`do sudo -u nextcloud-user /var/www/nextcloud-wwwroot/occ user:info "$user$"; done < <(sudo -u nextcloud-user php /var/www/nextcloud-wwwroot/occ user:list | sed 's#[ -]*\([^:]*\).*#\1#')
`
Possibility to add mail by command:
`sudo -u nextcloud-user /var/www/nextcloud-wwwroot/occ user:setting "$user$" settings email "$user$"@domain.com `

question: how to make a user receive data from NEXTCLOUD one by one command through a loop?

**Comment by tach-tm** [comment]
tgoeg 
Friend you know this solution please help.
https://github.com/nextcloud/server/issues/9494#issuecomment-425810052

**Comment by kesselb** [comment]
Closing as support request.

**Comment by tach-tm** [comment]
Hi. I'm sorry I can't get through to support. please help on this issue. How can everyone set an email address using a template. For example ***@***.***"
Thanks for the help.
