### ISSUE TITLE
[Bug]: occ fails to run config:system:delete when "apps_paths" are misconfigured 

### ISSUE THREAD

**Issue by quoing** [nextcloud/server#33727]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

My goal:
If you want to re-configure (by script) the apps_path parameter, so my steps are to delete all apps_path entries, and then add one by one new ones, but it deletion fails due to non-existent directory.. which doesn't make really sense.
```
$ ./occ config:system:delete apps_paths
App directory "/apps2" not found! Please put the Nextcloud apps folder in the Nextcloud folder.
```
it is the same for other parameters
```
$ ./occ config:system:delete trusted_domains
App directory "/apps2" not found! Please put the Nextcloud apps folder in the Nextcloud folder. You can also configure the location in the config.php file.
```

of course with properly configured entries in configuration file are deleted.

### Steps to reproduce

1. configure apps_path that one of etries contains NON-existing path
2. try to run "occ config:system:delete" on any parameter

### Expected behavior

Configuration keys should be deleted regardless of of current configuration.

### Installation method

Community Docker image

### Operating system

Other

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
$ ./occ config:list:system
App directory "/apps2" not found! Please put the Nextcloud apps folder in the Nextcloud folder. You can also configure the location in the config.php file.

Sorry but this is way too funny :-D

<?php
$CONFIG = array (
...
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/apps2',
      'url' => '/apps2',
      'writable' => true,
    ),
  ),
...
```

### List of activated Apps

```shell
irrelevant
```

### Nextcloud Signing status

```shell
irrelevant
```

### Nextcloud Logs

```shell
irrelevant
```

**Comment by quoing** [comment]
yeah, still same issue.. once app_paths contain non-existent directory many occ commands simply fail (and it needs manual update of config.php)..

`
/nextcloud # date
Tue Jan 24 16:12:44 UTC 2023
/nextcloud # ./occ status
The current PHP memory limit is below the recommended value of 512MB.
  - installed: true
  - version: 25.0.3.2
  - versionstring: 25.0.3
  - edition: 
  - maintenance: false
  - needsDbUpgrade: false
  - productname: Nextcloud
  - extendedSupport: false
/nextcloud #
/nextcloud # ./occ config:system:delete trusted_domains; echo
App directory "/apps2" not found! Please put the Nextcloud apps folder in the Nextcloud folder. You can also configure the location in the config.php file.
/nextcloud # 

`
once I create missing path of course it starts working
`
/nextcloud # mkdir /apps2
/nextcloud # ./occ config:system:delete trusted_domains; echo
The current PHP memory limit is below the recommended value of 512MB.
System config value trusted_domains deleted

/nextcloud # 
`

**Comment by quoing** [comment]
I expect configuration update (at least of basic parameters) should be possible event if paths are missing.. the purpose is to provide CLI for config.php modifications, so there is no reason for check if the path actually exists (for commands that are not touching app configuration - but it is not stored in apps path anyways..) 

I can understand that occ would fail installing new app in this case :)

**Comment by come-nc** [comment]
I understand the idea but this is really low priority, there are easy workarounds (fix config or create directory).
If you want to dive into it and propose a pull request go ahead, but I won’t allocate time on this.

**Comment by quoing** [comment]
I would say lets close this one, I tried to check if I'm able to repair it, so it works as I expect.. but I'm running into more issues with OCC (another one is I cannot configure database when database connection is not available, occ ends up on "maintenance mode", and not allow me to change anything again) and in the end I will probably resolve all these by simply compiling the config.php directly without occ.
