### ISSUE TITLE
[Bug]: SQLSTATE[42P07]: Duplicate table: 7 FEHLER: Relation »share_id_index« existiert bereits

### ISSUE THREAD

**Issue by surbier9** [nextcloud/server#33726]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Aktualisierung auf 24.0.4
Exception: Database error when running migration 070400Date20220607111111 for app onlyoffice An exception occurred while executing a query: SQLSTATE[42P07]: Duplicate table: 7 FEHLER: Relation »share_id_index« existiert bereits

Detaillierte Protokollmeldungen 
Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: Not a mysql database -> nothing to do

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Datenbank aktualisiert

Exception: Database error when running migration 070400Date20220607111111 for app onlyoffice An exception occurred while executing a query: SQLSTATE[42P07]: Duplicate table: 7 FEHLER: Relation »share_id_index« existiert bereits

Das Update ist fehlgeschlagen. Bitte melde dieses Problem an die [Nextcloud Community](https://github.com/nextcloud/server/issues).

### Steps to reproduce

1. Update Server
2.
3.

### Expected behavior

upgrade successful to version 24.0.4

### Installation method

Community Docker image

### Operating system

Other

### Database engine version

SQlite

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
i cannot do this point - this host is univention docker
```

### List of activated Apps

```shell
i cannot do this point - this host is univention docker
```

### Nextcloud Signing status

```shell
i cannot do this point - this host is univention docker
```

**Comment by surbier9** [comment]
https://help.nextcloud.com/t/general-error-after-reenable-onlyoffice-after-update-to-nextcloud-24/141516

**Comment by kesselb** [comment]
Hey :wave: 

Please report it at https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues
