### ISSUE TITLE
QueryBuilder: UPDATE SET does wrong escaping

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/server#3373]
### Steps to reproduce
1. Check out this bit of code: https://github.com/nextcloud/server/blob/master/lib/private/DB/QueryBuilder/QueryBuilder.php#L660
2. And consider all possible inputs for $value, like a direct value, a parameter.

### Expected behaviour
The $value should be escaped correctly in each case.

### Actual behaviour
All supplied values are escaped with `quoteColumnName`, while [parameters](https://github.com/nextcloud/bookmarks/pull/332/files#diff-60bf617da66ab938849bb119ba377bc5R427) [don't seem to be replaced at all](https://travis-ci.org/nextcloud/bookmarks/jobs/197972122#L395) and raw values are escaped [the wrong way](https://travis-ci.org/nextcloud/bookmarks/jobs/197803504#L395) (see the url value being quoted like a column name)

### Server configuration
**Operating system**: all

**Web server:** all

**Database:** all

**PHP version:** all

**Nextcloud version:** master

**Comment by LukasReschke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
As explained in the PR, you just need to fully use the QueryBuilder.
`$qb->where($qb->expr()->eq('abc', $qb->createNamedPlaceholder($value)))` instead of `$qb->where('abc = :placeholder')`

Then it works correctly.

**Comment by marcelklehr** [comment]
Thank you @nickvergessen! And sorry for the noise :)
