### ISSUE TITLE
New avatar styles

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#33735]
- [ ] Figure out a way to regenerate avatars
- [ ] New style based on lighter color palette https://github.com/nextcloud/server/blob/368f83095d443c28b0d90d2308549349cc28dd05/lib/private/Avatar/Avatar.php
- [ ] Clarify about contacts which uses the same color palette iirc?

The mockup:
![IMG_20220819_035451.jpg](https://user-images.githubusercontent.com/925062/185525677-ea5aa1f1-8c22-4cef-81df-080e454e3070.jpg)
The values would basically be the current avatar colors, but:
- The dark background color used as the text color instead
- a 10% light version of the color (much like primary-light) as the text color

@CarlSchwan also posted a nice article somewhere on accessible color combinations for tags somewhere, as a future step we could adapt that too.

**Comment by CarlSchwan** [comment]
https://github.com/nextcloud/server/pull/33752
