### ISSUE TITLE
[BITV] Settings page a11y issues

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#33744]
* [ ] https://github.com/nextcloud/server/issues/35626
* [x] aria-current needed for currently active navigation entry => https://github.com/nextcloud/server/issues/33739
* [x] Keyboard tabbing order is weird with the rightmost column, should go row by row (profile page) https://github.com/nextcloud/server/pull/35628

@CarlSchwan @Pytal please link in case some of these were fixed already in recent PRs

**Comment by ChristophWurst** [comment]
> When clicking a nav entry, recommendation is to put the focus into the heading of the content

That is included in https://github.com/nextcloud/server/issues/35626

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
