### ISSUE TITLE
Wrong error: Maintenance Mode is On

### ISSUE THREAD

**Issue by Huster-at-github** [nextcloud/server#3374]
* NC 11.0.1
* Ubuntu 16.04 LTS

Want to update app Audio Player. Get this error:

![bildschirmfoto vom 2017-02-04 17-00-34](https://cloud.githubusercontent.com/assets/3857906/22619728/7a1d432e-eafb-11e6-96ef-2ed25852a6fb.png)

And logging says that I'm in maintenance mode. **But I'm for sure not!**

Fatal	webdav	Sabre\DAV\Exception\ServiceUnavailable: HTTP/1.1 503 System in maintenance mode.

    [internal function] OCA\DAV\Connector\Sabre\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466: Sabre\Event\EventEmitter->emit('beforeMethod', Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 60: Sabre\DAV\Server->exec()
    /var/www/nextcloud/remote.php - line 165: require_once('/var/www/nextcl...')
    {main}
	2017-02-04T16:47:59+0100

**Comment by Huster-at-github** [comment]
Now 4 App Updates are pending ....   :-(

But I have other issues too:
* Cannot send E-Mails with app Mail
* Amazon S3 no more working

**Comment by Flole998** [comment]
When upgrading apps your site gets automatically put in maintenance mode. That is intended and not an issue. Your logs are incomplete and do not show the update but instead a webdav request.

**Comment by tcitworld** [comment]
FYI, it happened to me after migrating my instance to another server.
I resolved this by updating all the apps, putting nc in maintenance mode on and off, and then `files:scan`.
