### ISSUE TITLE
mod_rewrite.c apache

### ISSUE THREAD

**Issue by acrix** [nextcloud/server#33747]
using mod_rewrite and apache currently non productive and user troling aproach, remove this

**Comment by kesselb** [comment]
Hey @acrix :wave: 

Thanks for your bug report. Can you provide some more details?

**Comment by acrix** [comment]
this is feature request, not bug
but i like u point of view, using mod_rewrite is bug

**Comment by kesselb** [comment]
Can you provide some more details? It's unclear what your feature request is about?

**Comment by acrix** [comment]
1. make [ nginx->php-fpm ] official recommended  way
2. drop apache support completely, even mark big red warning if apache used
3. make clear routing, use websockets, remove polling

**Comment by acrix** [comment]
In fact, it slows down Apache even if your .htaccess is empty since it’s reloaded on every request! Thus, server admins should import the contents of .htaccess into Apache’s server config, where it is only compiled once. After which, you should disable the use of .htaccess completely.

**Comment by kesselb** [comment]
Thanks :+1: 

We don't plan to drop support for Apache2. In fact there is not much code related to Apache2 in Nextcloud itself. 

> make [ nginx->php-fpm ] official recommended way

Feel free to run Nextcloud that way.

> In fact, it slows down Apache even if your .htaccess is empty since it’s reloaded on every request! Thus, server admins should import the contents of .htaccess into Apache’s server config, where it is only compiled once. After which, you should disable the use of .htaccess completely.

Copy .htaccess to your virtual host and set AllowOverride None. Don't forget to check your .htaccess file after updates for possible changes.

**Comment by acrix** [comment]
> Feel free to run Nextcloud that way.
> Copy .htaccess to your virtual host and set AllowOverride None.

This make maintenance and upgrade painful.
You can answer "it always has been".
I think it not best practice.

**Comment by kesselb** [comment]
I don't see any problem here. You have plenty of options how to run Nextcloud:

- Don't like Apache2? Use Nginx.
- Don't like mod_rewrite? Don't enable clean urls. 

> I think it not best practice.

What is not best practice? If you want to discuss something try to write a proper sentence.

**Comment by acrix** [comment]
I think further discussion is not productive.
php script kiddie go scripts
