### ISSUE TITLE
Missing expected parameters in change user hook

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#3375]
Seems related to https://help.nextcloud.com/t/error-is-filling-my-logs-missing-expected-parameters-in-change-user-hook/7065, I got the following log message reported:

```
{"reqId":"9E6VIXwf6cOgmxLjiCnR","remoteAddr":"XX.XX.XX.XX","app":"no app in context","message":"Missing expected parameters in change user hook","level":2,"time":"January 23, 2017 17:21:50","method":"POST","url":"\/index.php\/login","user":"XYZ","version":"11.0.0.10"}
```

**Comment by LukasReschke** [comment]
@schiessle Any idea on that? :)

**Comment by scroom** [comment]
@MorrisJobke won't the solution be backported to the next release of the 11 branch? (11.0.6?)
