### ISSUE TITLE
[Bug]: updating displayName twice using curl with same Text causes a 102 error the second time

### ISSUE THREAD

**Issue by lightaffaire** [nextcloud/server#33751]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Running 24.0.3.

1. update an existing users displayName with a new text “MyName”

$ curl -u admin:PASSWORD https://yoursite.com:443/ocs/v1.php/cloud/users/MyUser --silent --header "OCS-APIRequest: true" -X PUT -d key=displayname -d value="MyName"

returns 100 OK

 2. update the same users displayName again with the same text “MyName”

$ curl -u admin:PASSWORD https://yoursite.com:443/ocs/v1.php/cloud/users/MyUser --silent --header "OCS-APIRequest: true" -X PUT -d key=displayname -d value="MyName"

returns 102 Invalid displayname

The second call should return 100 OK as the input value is OK.

For example updating language, locale, quota with the same value 2 times works OK.

Iain

### Steps to reproduce

1. see curl command above... run it twice... second time returns a 102 instead of 100 status code.
2.
3.

### Expected behavior

Expected is that if i run the same command twice that it works both times with status code 100.

### Installation method

Community Docker image

### Operating system

Other

### PHP engine version

Other

### Web server

Nginx

### Database engine version

MariaDB

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
no apps installed
```

**Comment by kesselb** [comment]
cc @Pytal @PVince81 

https://github.com/nextcloud/server/pull/33625
https://github.com/nextcloud/server/pull/33052

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
