### ISSUE TITLE
Add occ-command to set URL in Collabora App settings

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#3377]
I have just [scripted the Collabora install](https://github.com/nextcloud/vm/blob/master/static/collabora.sh), and the only missing piece to make it perfect is to add the URL in Collabora App settings.

Would be great if someone could add a occ command for it.

**Comment by nickvergessen** [comment]
If they use the oc_appconfig you can use:
```
./occ config:app:set --help
Usage:
  config:app:set [options] [--] <app> <name>

Arguments:
  app                    Name of the app
  name                   Name of the config to set

Options:
      --output[=OUTPUT]  Output format (plain, json or json_pretty, default is plain) [default: "plain"]
      --value=VALUE      The new value of the config
      --update-only      Only updates the value, if it is not set before, it is not being added
  -h, --help             Display this help message
  -q, --quiet            Do not output any message
  -V, --version          Display this application version
      --ansi             Force ANSI output
      --no-ansi          Disable ANSI output
  -n, --no-interaction   Do not ask any interactive question
      --no-warnings      Skip global warnings, show command output only
  -v|vv|vvv, --verbose   Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
 Set an app config value
```

If not, it needs to be implemented on that app, or they should switch to this config system.

**Comment by enoch85** [comment]
@nickvergessen Ok, where do I open an issue? Couldn't find their issue tracker...

**Comment by enoch85** [comment]
Found it: libreoffice@collabora.com

**Comment by timar** [comment]
@enoch85 The issue tracker of richdocuments app is here: https://github.com/nextcloud/richdocuments/issues
Please not that the maintainer of this app is Nextcloud, not Collabora.

**Comment by enoch85** [comment]
Thanks @timar! If you have time, please test the scripted installation and suggest improvements, if any.
