### ISSUE TITLE
Removed background image from theming should apply on new UI

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#33797]
Both dashboard and the theming app have the option to remove the background image and use the plain theming color. This is currently not being handled by the new page background in DefaultTheme.php

**Comment by nursoda** [comment]
Example where this does lead to unexpected results: System is set to dark mode, as is Firefox. NC is set to follow system. In settings/admin/theming (global) BG color is set to #888888 and a BG image is set to a (slightly darker) image. In /settings/user/theming, BG is set to "Plain Background". Thus, the BG image should only be used on the login page (and public pages?).

![grafik](https://user-images.githubusercontent.com/8425483/191108687-78aa75df-57ad-4289-a19d-41e094a78970.png)
![grafik](https://user-images.githubusercontent.com/8425483/191110393-8d287bd4-79cc-4a08-8cdb-3ad4743e366b.png)

[Sidenote: There's also a localization glitch here.]

With this setting, I expect all pages while logged in to NOT show the BG image. In fact, /settings/user/theming honors that, but all other pages don't:

![grafik](https://user-images.githubusercontent.com/8425483/191110765-18501733-5c04-4e31-9c58-68e5e9839872.png)
![grafik](https://user-images.githubusercontent.com/8425483/191110804-4fd8344b-df2c-4ad9-9dad-d12aa9772dc4.png)

Additionally, the man navigation icons' color should not change.

**Comment by skjnldsv** [comment]
As far as I undrstood, there is a check now for the admin to properly disable user-defined background (and primary after #34272)
When the admin disabled that option, THEN the background removal would apply and be enforced everywhere, using the primary only 

Please confirm @jancborchardt

**Comment by jancborchardt** [comment]
> With this setting, I expect all pages (while logged in) to NOT show the BG image. 

@nursoda yes, that expectation is correct.

@skjnldsv admin settings have (almost) nothing to do with this, it's about the user setting of plain background.

@Pytal can you confirm that what @juliushaertl and @nursoda describe is fixed, or is there something in progress / to do?

**Comment by skjnldsv** [comment]
> @skjnldsv admin settings have (almost) nothing to do with this, it's about the user setting of plain background.

@nursoda's screenshot shows the admin section, which also include a "disable background image", which is very weird to have considering all those values now.
Like the primary colour (chosen by admin), it almost have no visible effect on the user since there are custom themes enabled by default.

**Comment by Pytal** [comment]
> @Pytal can you confirm that what @juliushaertl and @nursoda describe is fixed, or is there something in progress / to do?

Yes, fixed in https://github.com/nextcloud/server/pull/34204
