### ISSUE TITLE
Folder with quotation marks are created but not shown in webinterface

### ISSUE THREAD

**Issue by guddl** [nextcloud/server#3379]
### Steps to reproduce
1. Login on https://demo.nextcloud.com
2. Got to e.g. Documents folder and create a folder named "Test"-Folder (with the quotation marks)
3. Reload 

### Expected behaviour
The new folder should be shown up in the webinterface.

### Actual behaviour
The folder is not shown. But folder count at the bottom of the page counts up. And the Folder is on the filesystem. Files are only shown, if you switch the sort sequence. 

### Server configuration
Ubuntu 14.04

Apache 2.4.x

Maria DB

php 7.0

**Nextcloud version: Nextcloud 11.0.1 (stable)**

**Comment by MorrisJobke** [comment]
I tried with master, stable11, 11.0.1 and the version on the demo and can't reproduce this. Could you please check again. We also recently improved the escaping - see #2776. Looks like this fixes it. Can you try with the stable11-daily or the upcoming 11.0.2 and report back if this is still an issue for you with this code. Thanks

**Comment by guddl** [comment]
Hi @MorrisJobke,

I tried it again this morning on https://demo.nextcloud.com. I can reproduce is. I made some screenshots. You can have a look here: https://oc.wgxs.org/index.php/s/gxxff5IviPFcNi7

I upgraded my main Nextcloud to daily - still the same problem :-/

**Comment by MorrisJobke** [comment]
Which browser do you use?

**Comment by guddl** [comment]
Ahhh. In my Chrome browser its okay ... with the daily version.
On the demo with Chrome the problem still exists.

**Comment by nickvergessen** [comment]
This was fixed for 11.0.2:
https://github.com/nextcloud/server/pull/3138
