### ISSUE TITLE
Issue with horizontal resize and sidebar responsiveness in files app (Chromium 104)

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#33808]
- [ ] BUG: issue with horizontal resize and sidebar responsiveness in files app (Chromium 104)

![resize-sidebar-issue](https://user-images.githubusercontent.com/277525/187643108-ec671551-9b92-495a-852f-10e7628dc2e2.gif)

### Steps to reproduce:
1. Reduce width until the left sidebar disappears
2. Click the hamburger menu to make it appear
3. Resize horizontally while the sidebar is still open
4. Be unlucky :four_leaf_clover: 

### Expected
No sizing issue

### Actual
If you're lucky, the content width animates back to the correct position.
If unlucky, the animation gets stuck/reset and the content does not readjust.

Maybe related to the snap.js library which is known to have race condition issues.
=> **If not easy to reproduce (I tend to be unlucky), let's skip this**

_Originally posted by @PVince81 in https://github.com/nextcloud/server/issues/33568#issuecomment-1232680186_

**Comment by jancborchardt** [comment]
> Maybe related to the snap.js library which is known to have race condition issues.

I was thinking that as well. To be quite honest, we can also get rid of this library if it causes so many issues.

**Comment by szaimen** [comment]
+1 getting rid of the library

**Comment by szaimen** [comment]
cc @server-front

**Comment by szaimen** [comment]
cc @nextcloud/server-frontend

**Comment by skjnldsv** [comment]
This happens in other areas too, it's not just that library.

**Comment by skjnldsv** [comment]
Cannot reproduce anymore
