### ISSUE TITLE
 BUG: public link image share, footer overlaps with scrollbar:

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#33803]
![image](https://user-images.githubusercontent.com/3404133/187960652-284cd52b-9354-4f6e-9680-67ea6146ec74.png)

**Comment by danxuliu** [comment]
Note that this is not limited to image shares, it happens with any preview.

You may need to reduce the height of the window to notice it, and also try with a file share, as [the summary of the file list in folder shares is too tall](https://github.com/nextcloud/server/blob/4389e6903fe8eebe897e506e2350ba96838b932f/apps/files/css/files.scss#L742-L744) and prevents a visual overlap (although the overlap is still there).

The [content height](https://github.com/nextcloud/server/blob/6579b6c3c84070eb625033aacfc07c80a11f6ee1/core/css/apps.scss#L669) is the [full height minus the header and a little margin at the bottom to show the background](https://github.com/nextcloud/server/blob/6579b6c3c84070eb625033aacfc07c80a11f6ee1/core/css/apps.scss#L27), so it "stretches" to the bottom of the page. However, the footer in public pages is [fixed](https://github.com/nextcloud/server/blob/03b9047e95be95592773d01b8e86cf03ee9a9f0a/core/css/public.scss#L71) at the [bottom](https://github.com/nextcloud/server/blob/03b9047e95be95592773d01b8e86cf03ee9a9f0a/core/css/public.scss#L77) (with [a little margin](https://github.com/nextcloud/server/blob/03b9047e95be95592773d01b8e86cf03ee9a9f0a/core/css/public.scss#L79) to show the background), so it overlaps the lower [65px](https://github.com/nextcloud/server/blob/03b9047e95be95592773d01b8e86cf03ee9a9f0a/core/css/public.scss#L1) of the content, and therefore hides the lower part of the preview (in the case of file shares, [the `Download` button](https://github.com/nextcloud/server/blob/702b0cccd6f0d7c44a8199154d738beeb3a34086/apps/files_sharing/templates/public.php#L83-L86)).

**Comment by szaimen** [comment]
> @juliushaertl I assume the screenshot/report is out of date, as we worked on a different design for the footer? :)

How should it look like? Can you post a screenshot of the mockup?

**Comment by szaimen** [comment]
ping @jancborchardt :)

**Comment by szaimen** [comment]
Looks great! Can you create a PR? :)

**Comment by jancborchardt** [comment]
I mean even better would actually be if it’s just below the content, not permanently displayed. Cause currently on small displays, a significant amount of the image or share is overlapped. :\

**Comment by jancborchardt** [comment]
This is also how we had it before the ui change, so I assume this has to do with how the containers now work?

**Comment by szaimen** [comment]
I'll check this later!

> I mean even better would actually be if it’s just below the content, not permanently displayed

**Comment by szaimen** [comment]
This seems to fixes it:
```
#imgframe img {
    max-height: calc(100vh - var(--header-height) - 270px) !important;
    width: unset !important;
}

#imgframe video {
    max-height: calc(100vh - var(--header-height) - 270px) !important;
}


#imgframe .text-preview {
overflow-y: scroll !important;
}

.app-files_sharing #app-content {
    max-height: calc(100vh - var(--header-height) - 65px);
}
```

**Comment by Chartman123** [comment]
@jancborchardt @szaimen By the way, the footer height is too small when there is a imprint/privacy link set in the settings. See https://github.com/nextcloud/forms/issues/1337
