### ISSUE TITLE
User settings navigation actions are out of place

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#33812]
![Screenshot 2022-09-01 at 18 55 46](https://user-images.githubusercontent.com/3404133/187970491-75d38ae3-7948-436a-936c-c0ae635e36a9.png)

**Comment by juliushaertl** [comment]
Partly related to the vue components it seems https://github.com/nextcloud/mail/issues/7093

**Comment by szaimen** [comment]
should be fixed with the nexxt vue 7.0.0 release after https://github.com/nextcloud/nextcloud-vue/pull/3157 and https://github.com/nextcloud/nextcloud-vue/pull/3157. Let's see

**Comment by szaimen** [comment]
fixed in the meantime as well
