### ISSUE TITLE
Navigation flashes when navigating between entries on new design

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#33824]
This seems to be because the whole content is overlaid with a very transparent white overlay for the loading spinner, resulting in the left navigation to look glitched as it does not have a fully white background anymore. The loading overlay should only cover the content area.

https://user-images.githubusercontent.com/925062/188040226-a13dcdfa-3c03-4dc8-9181-5b2551a293fb.mp4

**Comment by joshtrichards** [comment]
No longer applicable and looks good today. :-)
