### ISSUE TITLE
Placeholder of share sidebar input field glitches

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#33825]
Not sure if this is related to the new design, or the input component – but you can see the placeholder moves around when clicking into it. Not sure if the size is non-standard and that is the reason? cc @marcoambrosini 

https://user-images.githubusercontent.com/925062/188040551-b572c683-f9e0-4507-a683-a8f52f68c53a.mp4

**Comment by szaimen** [comment]
wasn't this fixed with the new vue update? cc @CarlSchwan

**Comment by marcoambrosini** [comment]
Seems fixed, closing for now
