### ISSUE TITLE
high-contrast-mode bright makes icons unvisilbe

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#33836]
See 
![image](https://user-images.githubusercontent.com/42591237/188102812-c0281da0-c3ec-4da9-9548-48dd1ee9e002.png)

**Comment by szaimen** [comment]
Unfortunately I didn't find a solution to this in an appropriate timeframe.  @skjnldsv I think it is something with the theme...

**Comment by skjnldsv** [comment]
Missing `light` in body `data-themes`

**Comment by skjnldsv** [comment]
I guess this goes back to us adding a LIGHT/DARK binary property to each themes

**Comment by szaimen** [comment]
> ```diff
> diff --git a/apps/theming/lib/Service/ThemesService.php b/apps/theming/lib/Service/ThemesService.php
> index 26dcbfed0d5..eabd903734a 100644
> --- a/apps/theming/lib/Service/ThemesService.php
> +++ b/apps/theming/lib/Service/ThemesService.php
> @@ -87,9 +87,9 @@ class ThemesService {
>                 }
>  
>                 /** @var ITheme[] */
> -               $themes = array_map(function($themeId) {
> +               $themes = array_filter(array_map(function($themeId) {
>                         return $this->getThemes()[$themeId];
> -               }, $themesIds);
> +               }, $themesIds));
>  
>                 // Filtering all themes with the same type
>                 $filteredThemes = array_filter($themes, function(ITheme $t) use ($theme) {
> ```

is this fix already complete? I can then create a PR with this and the above fix :)

**Comment by skjnldsv** [comment]
No, it was inspiration, I thought you were working on it.
Like mentioned above, this doesn't solve the filtering of unknown themes

**Comment by szaimen** [comment]
Okay, I'll focus on fixing the theme for now...
