### ISSUE TITLE
New folder input fields look strange

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#33835]
See 
![image](https://user-images.githubusercontent.com/42591237/188102621-01a2cc4d-c4a0-4ea2-9045-9e9014543ad8.png)

**Comment by szaimen** [comment]
same for other input fields, e.g. in the privacy app: 
![image](https://user-images.githubusercontent.com/42591237/188110416-f467d168-2e10-4288-8b72-e7b253574a24.png)

**Comment by juliushaertl** [comment]
Related to https://github.com/nextcloud/server/issues/33815
