### ISSUE TITLE
files rightclick doesn't seem to work in the files app

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#33837]
However it may be related to my test instance. So not sure.

See 
![image](https://user-images.githubusercontent.com/42591237/188104189-6ad6b295-076e-461b-b220-c2a6ad076054.png)

**Comment by szaimen** [comment]
I tried again and it still doesnt work. cc @nextcloud/server can you reproduce this?

**Comment by blizzz** [comment]
does not work on tech-preview

**Comment by szaimen** [comment]
> does not work on tech-preview

all right! Then this is a valid issue 👍

I suppose it was introduced with the refactoring of some classes/ids in the files app. cc @PVince81

**Comment by PVince81** [comment]
yeah, it seems that exotic jQuery selector escaped my intense grepping sessions

I'll have a look

**Comment by PVince81** [comment]
PR here https://github.com/nextcloud/files_rightclick/pull/142
