### ISSUE TITLE
Share by mail notification not working correct

### ISSUE THREAD

**Issue by dargon85** [nextcloud/server#3384]
### Steps to reproduce
1. Create folder
2. Share using the "Share by mail" option
3. Sent email is barely working its way through the templates

### Expected behaviour
With NextCloud 9 the option to share items by mail has been a dedicated app.
That worked fine picking the correct language (depending on defaults auf users language settings).
Even with MS Active Directory (LDAP) user mapping the Display Name was used inside the notification.
That was an awesome feature that I pretty much used all the time items had to be shared.

NextCloud9, Ubuntu 16.04 LTS Server, MariaDB 10.1, Apache and php7

### Actual behaviour
After Upgrading and this time, fresh install, the mail notification is a mess.
I noticed that the dedicated app has been migrated to an internal "share feature" and this turned out not to work properly.
There is no automatic translation of the share notification mail. The username iteself is no longer the display name but the SID if LDAP is used.
Anyway even the mail template editior app is not able to help resolving the issue.
Might be caused that the "old" mailing templates from NextCloud9 still exist and that is where the template editor is looking at.

After some try and error I managed to copy the "old" templated to the new folder. The only thing happend is the text inside the mail has slightly changed.
Unfortunately the username (probably the whole details, incl. language settings) are not fetched corretly.
Therefore the Notification mail still staged "Hey there, just letting you know that %SID% shared "File" with you.".
No translation even using default language options within nextcloud.

Thank you for your support.

Mark

### Server configuration
**Operating system**: Linux nextcloud 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64

**Web server:** nginx/1.10.0 (fpm-fcgi)

**Database:** mysql 10.1.20

**PHP version:** 7.0.8-0ubuntu0.16.04.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, ldap, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 11.0.1 (stable) - 11.0.1.2

**Updated from an older Nextcloud/ownCloud or fresh install:** both, currently fresh install

**Where did you install Nextcloud from:** official nextcloud downlad tar.gz file

**Signing status:**
<details>
	<summary>Signing status</summary>

```
[]
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.4.1
 - comments: 1.1.0
 - dav: 1.1.1
 - federatedfilesharing: 1.1.1
 - federation: 1.1.1
 - files: 1.6.1
 - files_downloadactivity: 1.0.0
 - files_external: 1.1.2
 - files_pdfviewer: 1.0.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - firstrunwizard: 2.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.0
 - keeweb: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.0
 - notifications: 1.0.1
 - password_policy: 1.1.0
 - provisioning_api: 1.1.0
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - survey_client: 0.1.5
 - systemtags: 1.1.3
 - templateeditor: 0.2
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - updatenotification: 1.1.1
 - user_ldap: 1.1.1
 - workflowengine: 1.1.1

Disabled:
 - admin_audit
 - audioplayer
 - calendar
 - contacts
 - encryption
 - external
 - files_accesscontrol
 - files_automatedtagging
 - files_retention
 - mail
 - ownpad
 - richdocuments
 - tasks
 - user_external
 - user_saml
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "oco2ba2sdz8a",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.wiechers.cc"
    ],
    "datadirectory": "\/var\/nextcloud_data",
    "overwrite.cli.url": "https:\/\/cloud.wiechers.cc",
    "dbtype": "mysql",
    "version": "11.0.1.2",
    "dbname": "nextcloud_db",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Berlin",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mail_smtpmode": "smtp",
    "mail_from_address": "postmaster",
    "mail_domain": "wiechers.cc",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "mail.noip.com",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "ldapIgnoreNamingRules": false,
    "ldapUserCleanupInterval": "5",
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "updater.release.channel": "stable",
    "maintenance": false,
    "loglevel": 2
}
```
</details>

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OCA\Files_External\Lib\Storage\FTP
    [2] => \OC\Files\Storage\DAV
    [3] => \OCA\Files_External\Lib\Storage\OwnCloud
    [4] => \OCA\Files_External\Lib\Storage\SFTP
    [5] => \OCA\Files_External\Lib\Storage\AmazonS3
    [6] => \OCA\Files_External\Lib\Storage\Dropbox
    [7] => \OCA\Files_External\Lib\Storage\Google
    [8] => \OCA\Files_External\Lib\Storage\Swift
    [9] => \OCA\Files_External\Lib\Storage\SFTP
    [10] => \OCA\Files_External\Lib\Storage\SMB
    [11] => \OCA\Files_External\Lib\Storage\SMB
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
	<summary>LDAP config</summary>

	```
	With access to your command line run e.g.:
	sudo -u www-data php occ ldap:show-config
	from within your Nextcloud installation folder

	Without access to your command line download the data/owncloud.db to your local
	computer or access your SQL server remotely and run the select query:
	SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


	Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
	```
</details>
### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0

**Operating system:**

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	Insert your webserver log here
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
	Insert your Nextcloud log here
	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
	Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
	```
</details>

**Comment by nazilus** [comment]
HI,
Same here i can't get any email notification working
This happen after i upgrade from OC to NC.

I've try a fresh install and still no Luck.

**Email setting is working fine and i'm able to send a test email.**

But Activity email or Share Email nothing seem to work here.

**Comment by schiessle** [comment]
> I noticed that the dedicated app has been migrated to an internal "share feature" and this turned out not to work properly.

Actually it is the other way arround. The old feature was part of the internal (link) sharing. The new one is now a (more powerful) dedicated app.

> There is no automatic translation of the share notification mail. 

If you look at the template you will see that all strings are translated. Possible problem: that a translation for your language wasn't ready in time for the Nextcloud 11 release

> The username iteself is no longer the display name but the SID if LDAP is used.

It is already fixed and will be released soon with 11.0.2: https://github.com/nextcloud/server/pull/3080

Anything left?

**Comment by schiessle** [comment]
seems like the translations are not yet on Transifex... cc @MorrisJobke can you fix this? Thanks!

**Comment by dargon85** [comment]
Could you please explain the altmail note.

> If you look at the template you will see that all strings are translatable (https://github.com/nextcloud/server/blob/master/apps/sharebymail/templates/altmail.php). Possible problem: that a translation for your language wasn't ready in time for the Nextcloud 11 release

The "original" OC9 / NC9" has been translated to German by default.
Is this addressed by the comment about Transifex...?

Thank you!

**Comment by schiessle** [comment]
> Could you please explain the altmail note.

Just wanted to show that on source code level translations are implemented. But I just noticed that Transifex wasn't updated with the new translation files. That's the reason why it is not yet translated. We will get them on Transifex as fast as possible and then we should have translations soon.

**Comment by MorrisJobke** [comment]
> seems like the translations are not yet on Transifex... cc @MorrisJobke can you fix this? Thanks!

I was never told to do so 🙈 I will add it.

**Comment by MorrisJobke** [comment]
> I was never told to do so 🙈 I will add it.

Sync is set up: #3422

**Comment by schiessle** [comment]
Thanks @MorrisJobke 

So translation should come in soon. I think all the other issues are addressed as well. If still something missing, feel free to re-open.
