### ISSUE TITLE
[BITV] Contrast ratio is a general issue with white on our default blue

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#33842]
"The contrast ratio is a general issue with white on our default blue, we only pass AA with large text"

Need to check if this still applies with the new design and if yes, what changes are required to fix this.

@jancborchardt @nimishavijay

**Comment by Pytal** [comment]
Before | After
--- | ---
![image](https://user-images.githubusercontent.com/24800714/201177640-8380295e-6a4e-42d4-b8c9-ccd2bbd40547.png) | ![image](https://user-images.githubusercontent.com/24800714/201177665-fc22d888-253e-4ed4-a805-743a5022a1ea.png)

Done in https://github.com/nextcloud/server/pull/34298
