### ISSUE TITLE
the list/gallery view button does not work in public view anymore

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#33847]
See 

https://user-images.githubusercontent.com/42591237/188108107-3571272e-826b-45d7-acb8-d59a7578ea84.mp4

**Comment by szaimen** [comment]
The other buttons for sorting like `name` and `size` are also not working anymore
See 

https://user-images.githubusercontent.com/42591237/188118567-92710ab0-457e-4864-944a-cf17efe26d8c.mp4

**Comment by PVince81** [comment]
sorting works for me on master in the "shared with others" view

however as you said the gallery view button is broken
I suspect it might be related to the switch from ids to class names

**Comment by PVince81** [comment]
grid view toggle fix is here: https://github.com/nextcloud/server/pull/34071

**Comment by szaimen** [comment]
@PVince81 I think it doesn't work on publish shares as well, so there is probably something missing still...

**Comment by szaimen** [comment]
Yes, just tested. This button doesn't work on latest RC: 
![image](https://user-images.githubusercontent.com/42591237/192502301-b8d2e2a1-ed21-458a-8c90-1a8983da33ed.png)

**Comment by PVince81** [comment]
@szaimen fix is here: https://github.com/nextcloud/server/pull/34292

because the code was moved to a higher level, it needs to be done there as well
