### ISSUE TITLE
[BITV] Dark mode needs higher contrast

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#33843]
e.g. for input field placeholders on log in

Need to check if this still applies with the new design and if yes, what changes are required to fix this.

@jancborchardt @nimishavijay

**Comment by Pytal** [comment]
> e.g. for input field placeholders on log in

No longer applicable @AndyScherzinger @jancborchardt?

![image](https://user-images.githubusercontent.com/24800714/201178371-c3d2adb8-3cbf-423f-96cb-bb9a00a4d7e9.png)

**Comment by AndyScherzinger** [comment]
Can't tell looking at it, can somebody check the contrast ratio? @jancborchardt maybe showing Chris how to check it himself in the future? 🙏 Thanks!

**Comment by Pytal** [comment]
Already using https://webaim.org/resources/contrastchecker/ to check things

The screenshot was to show that the login inputs don't have placeholders anymore so it seems not applicable @jancborchardt?

**Comment by AndyScherzinger** [comment]
True, while I can't tell if the input field's boarder in the unfocused state would have enough contrast

**Comment by Pytal** [comment]
Suggestions on the above @jancborchardt?

**Comment by jancborchardt** [comment]
@Pytal yeah, both the regular and the focused border of the input fields would need to pass the "Graphical Objects and User Interface Components".

**Comment by Pytal** [comment]
"Graphical Objects and User Interface Components" requires a 3:1 minimum contrast ratio

### Brand color borders

The accessible brand color was recently changed from `#0082c9` to `#00639a` to increase contrast when backgrounded against white text i.e. for primary buttons

While light mode has no border contrast issues, in dark mode `#00639a` as a border against `#171717` is too dark to satisfy the minimum 3:1 contrast ratio, so we can slightly lighten it to `#006aa3` while maintaining the primary button minimum 4.5:1 contrast ratio

### General-purpose borders

Contrast requirements are not met in both light and dark modes with the current border colors

The new colors which satisfy contrast requirements are below

#### Dark mode
`#646464` `--color-border`
`#787878` `--color-border-dark`

#### Light mode
`#949494` `--color-border`
`#808080` `--color-border-dark`

Dark mode (`--color-border`) | Light mode (`--color-border`)
--- | ---
![image](https://user-images.githubusercontent.com/24800714/202339297-d1ac4a8f-265c-4a00-a4b5-7b610b33108d.png) | ![image](https://user-images.githubusercontent.com/24800714/202339314-f50e885c-11e1-4086-8915-4d50733dbb6b.png)

### Example with new colors

![image](https://user-images.githubusercontent.com/24800714/202339428-338275d8-69c6-415b-8014-37bbb3b1bb48.png)

Look good @jancborchardt @AndyScherzinger?

**Comment by AndyScherzinger** [comment]
Looks good to me while Jan or Nimisha should also give it a thumbs up if fine by them.

👍

**Comment by nimishavijay** [comment]
Looks good! 👍

**Comment by Pytal** [comment]
- [ ] https://github.com/nextcloud/server/pull/35346
