### ISSUE TITLE
some buttons and text in the viewer editor overlap/are out of bounds

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#33869]
See 
![image](https://user-images.githubusercontent.com/42591237/188125747-430b1dd3-febb-4ddf-b59b-4fe098368ac2.png)

**Comment by szaimen** [comment]
cc @skjnldsv

**Comment by szaimen** [comment]
@skjnldsv is this solved with https://github.com/nextcloud/viewer/pull/1379?

**Comment by skjnldsv** [comment]
No clue, mind to try again?

**Comment by szaimen** [comment]
Editing is no longer available on mobile
