### ISSUE TITLE
dashboard app has an outer scrolling but shouldn't have one

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#33868]
See in blue on the right
![image](https://user-images.githubusercontent.com/42591237/188125199-cb24e00d-a716-4a11-ab43-f67d39b79079.png)

**Comment by juliushaertl** [comment]
Should be enough to change https://github.com/nextcloud/server/blob/b6a68028576e4c497e2e23e2b45121412522b030/apps/dashboard/src/DashboardApp.vue#L432 to 100% instead of 100vh. 

In addition we could consider https://caniuse.com/css-overflow-overlay with a fallback to auto for some browsers.
