### ISSUE TITLE
[Bug]: NC 25 Login Screen shows in dark mode 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#33878]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The login screen is showing in dark mode 

![image](https://user-images.githubusercontent.com/59488153/188205144-63839627-3048-459e-8112-d8b776ee9ba4.png)

### Steps to reproduce

Please see attached 

### Expected behavior

Should not be in dark mode 

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
NA
```

**Comment by szaimen** [comment]
This is expected and not a bug. It uses the system dark mode to find out if you are using dark mode or not

**Comment by andyxheli** [comment]
ahh okay thank you
