### ISSUE TITLE
the profile page doesnt scroll

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#33873]
See 
![image](https://user-images.githubusercontent.com/42591237/188137968-dc712ab5-76bf-45e3-b5b1-2d4cdee079d9.png)

**Comment by CarlSchwan** [comment]
> cc @CarlSchwan do you have a clue what is needed to make it scrollable? Doesn't seem like it is an app-content...

I'll look into it today

**Comment by szaimen** [comment]
Thanks! :)

**Comment by CarlSchwan** [comment]
> > cc @CarlSchwan do you have a clue what is needed to make it scrollable? Doesn't seem like it is an app-content...
> 
> I'll look into it today

or Monday :see_no_evil:

**Comment by szaimen** [comment]
> or Monday 🙈

All fine! I also still have a few that I want to look into next week! :)
