### ISSUE TITLE
[Bug]: NC 25 unable to add phone number for LDAP users

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#33886]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nothing happens when inputting phone number. 

### Steps to reproduce

1. Go to Personal Info
2.. Add number under Phone Number

### Expected behavior

Number should save. Or have an option to intergrate phone number via LDAP so it can pull from active directory just like it dose for the email 

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
NA
```

**Comment by Boogie55** [comment]
Pierre nick John with your vulnerability hacking software. Remove me immediately

**Comment by andyxheli** [comment]
Since has had multiple to location to input phone number here are the most used 

attributes: telephoneNumber
attributes: mobile

**Comment by andyxheli** [comment]
Closing this we can work on LDAP "Import Address info & Phone Numbers from Active Directory users" #33987
