### ISSUE TITLE
CSS files no longer have a cache buster 

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#33881]
Just noticed this when upgrading my personal instance to 25 beta 3

With the removal of the scss cacher the css files no longer have a cache buster when being loaded which means that after an upgrade the browser may still use the outdated cache files, so a force refresh was needed to bring up the new design and not end up in a broken UI state.

- Plain css files should probably have one depending on the app/nextcloud version
- Generated theming css should have one depending on the theming version value

cc @skjnldsv @PVince81

**Comment by CarlSchwan** [comment]
Cache buster works fine here if the debug mode is not enabled? Do you have maybe debug => true in your personal instance?

**Comment by skjnldsv** [comment]
No issues for me as well :thinking:
