### ISSUE TITLE
NC 25 Users status icon stops working 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#33890]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

While at the dashboard the status icon is green if going into files, photos stats icon turns while this also happens on dark mode but on dark mode the status icon is always white. This happens on mobile view and regular web 

### Steps to reproduce

https://user-images.githubusercontent.com/59488153/188273843-6003d2d1-400a-4e5b-a466-8062a862abf7.mp4

### Expected behavior

Should show the right status

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Na
```

**Comment by CarlSchwan** [comment]
Css before:

![image](https://user-images.githubusercontent.com/23653902/189116087-7afa73ff-89e1-4e7c-999e-746bcd3f554e.png)

Css after:

![image](https://user-images.githubusercontent.com/23653902/189116190-0551e28a-abb5-45b7-913e-ebe2e3a34b5d.png)

No idea what is causing this :( but I guess a webpack regression @skjnldsv @raimund-schluessler

**Comment by AndyScherzinger** [comment]
@CarlSchwan could you have another look please? @jospoortvliet can still reproduce issues with beta6 😢

**Comment by ChristophWurst** [comment]
Icons work for me on `master` and `v25.0.0beta6`.

**Comment by andyxheli** [comment]
Just updated to beta 6 and looks like its also working for me  @AndyScherzinger maybe clear Brower cache im using chrome

https://user-images.githubusercontent.com/59488153/189401283-e5b99c86-98a0-493d-a819-1d9d3b085536.mp4

**Comment by blizzz** [comment]
Works for me as well using Firefox

**Comment by AndyScherzinger** [comment]
Then maybe @jospoortvliet can add some more details on the issue he is facing
