### ISSUE TITLE
How to know if parameters in API requests need to be in the query parameters or in the body

### ISSUE THREAD

**Issue by jld3103** [nextcloud/server#33897]
Hi, I'd like to know how the API request parameters have to be specified when looking at the code. For example in https://github.com/nextcloud/spreed/blob/master/lib/Controller/ChatController.php you need to provide them in the query, but for example in https://github.com/nextcloud/notes/blob/master/lib/Controller/NotesApiController.php you need to provide them in the body. There has to be a way to know how the parameters have to be specified. I already searched through some code, but couldn't find an answer.

**Comment by CarlSchwan** [comment]
Checkout https://github.com/nextcloud/spreed/blob/master/appinfo/routes.php, all the parameters that are not defined in the root itself can be then either specified as `?key=value` or better in the body of the request. The rooting will then take care of fetching the parameters from the body and/or the GET request paremeters.

**Comment by jld3103** [comment]
Thanks :)

**Comment by jld3103** [comment]
This actually helps me a lot because I thought for some endpoints you had to use the body, but OpenAPI is annoying around that, so using query parameters makes my work a lot easier :tada:
