### ISSUE TITLE
[Bug]: Design issues with notification, search, … popups (NC25 design refresh)

### ISSUE THREAD

**Issue by ya-d** [nextcloud/server#33908]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

* Notifications and Search popups are missing the rounded corners while Contacts and Profile have them. Also the arrow is placed underneath the drop shadow (appears grey instead of white in light theme).
<img width="371" alt="image" src="https://user-images.githubusercontent.com/30781876/188508593-8ea4710d-70c7-42b1-aff2-b775c6d241a1.png">
* While Notifications and Search appear aligned to the window corner, Contacts and Profile seam to be right aligned to the respective icon
* Hover effect for Profile popup is still squared and spills over the rounded corners
<img width="282" alt="image" src="https://user-images.githubusercontent.com/30781876/188508401-90789f64-e54d-474f-a36b-cfc610a65b78.png">
* Cancel button in Contacts is different than cancel button in Search and uses wrong color in dark theme (black on dark)
<img width="377" alt="image" src="https://user-images.githubusercontent.com/30781876/188508427-a438dbe1-6fbd-4e93-b17b-aaa85912659f.png">

### Steps to reproduce

1. Use NC25 Beta 
2. Open popups on the upper right with light and dark theme activated
3.

### Expected behavior

All popups behave consistent

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
.
```

**Comment by CarlSchwan** [comment]
I can't reproduce but https://github.com/nextcloud/server/pull/33910 might help :)
