### ISSUE TITLE
Cron is not running properly for news

### ISSUE THREAD

**Issue by obsidiannonparity** [nextcloud/server#3390]
### Steps to reproduce
this is in relation to the news app

News feeds stop updating after upgrading nextcloud from 11.0.0 to 11.0.1.
In the database ResetTokenBackgroundJob in OCJobs has a reserved at number in it. after changing it to 0 it runs again but this occurs again in a day or two.

Origianlly opened this at https://github.com/nextcloud/news/issues/93 but BernhardPosselt recommend I open an issue for this here.

### Expected behaviour
cron should run and reserved be set to 0 after it completes

### Actual behaviour
appears cron runs but does not change reserved to 0 so it will not run again

### Server configuration
ubuntu 16.04

**Web server:**
Apache 2.4.18

**Database:**
occurs on both mysql 5.7.17 and Postgres 9.5.5

**PHP version:**
7.1.1

**Nextcloud version:** (see Nextcloud admin page)
11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
11.0.0

**Where did you install Nextcloud from:**
official download
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**
activity
collaborative tags
comments
deleted files
federation
file sharing
gallery
log reader
notifications
password policy
pdf viewer
news
share by email
calendar
contacts

<summary>App list</summary>

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => '****REMOVED****',
  'passwordsalt' => '****REMOVED****',
  'secret' => '****REMOVED****',
  'trusted_domains' => 
  array (
    0 => '****REMOVED****',
    1 => '****REMOVED****',
  ),
  'datadirectory' => '/home/tricloud/public_html/data',
  'overwrite.cli.url' => 'https://****REMOVED****',
  'dbtype' => 'mysql',
  'version' => '11.0.1.2',
  'dbname' => '****REMOVED****',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '****REMOVED****',
  'dbpassword' => '****REMOVED****',
  'logtimezone' => 'America/Denver',
  'installed' => true,
  'mail_from_address' => 'webmaster',
  'mail_smtpmode' => 'php',
  'mail_domain' => '****REMOVED****',
  'overwriteprotocol' => 'https',
  'maintenance' => false,
  'loglevel' => 2,
);

<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "ldap" namespace.  
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
Google Chrome 56
Ubuntu 16.10

#### Web server error log
no errors last 5 days and this has occured twice in the past 3 days<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
not browser dependent
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
This looks like the background job crashed and doesn't properly freed the job execution. @nickvergessen do you have deeper insight into this?

**Comment by nickvergessen** [comment]
Job locks are ignored after 12 hours. However, if it crashes all the time it will then be locked for 12 hours again.

**Comment by Bugsbane** [comment]
I'm using news with 11.0.1 without problems. I'm running Debian 8 with nginx

**Comment by MorrisJobke** [comment]
looks like the 11 and 12 version doesn't have this issue anymore
