### ISSUE TITLE
[Bug]: app's new thumbnail not replaced in a cloud instance's app details sidebar

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#33901]
### Bug description

An instances /settings/apps pages still shows the prior image content (as inline data) in an app's details sidebar despite of the maintainer having the image content of the first screenshots file modified/replaced and a new app version released.

### Steps to reproduce

1. create an app, take screenshots and a thumbnail and add them to the project files
2. reference these graphics in appinfo/info.xml, like 
    ```<screenshot small-thumbnail="https://raw.githubusercontent.com/nursoda/twofactor_email/main/screenshots/select-auth_thumb.png">https://raw.githubusercontent.com/nursoda/twofactor_email/main/screenshots/challenge.png</screenshot>```
4. check that they are shown in the app store
5. install the app from the app store to a cloud instance
6. check what is shown in the instance's **app detail view**, e.g. CLOUD/settings/apps/installed/APP – the first of the screenshots (not the thumbnail)
7. modify/replace the image of that first screenshot file without changing the filename/path/URL, in my case [this is new image](https://raw.githubusercontent.com/nursoda/twofactor_email/main/screenshots/challenge.png):
   <img src="https://raw.githubusercontent.com/nursoda/twofactor_email/main/screenshots/challenge.png" width="337">
9. release a new version of the app
10. update the app in the instance
11. check that they are shown in the app store: new screenshots are shown upon a normal page reload
12. check what is shown in the instance's app detail view: original screenshot remains even after clearing browser cache etc.
![grafik](https://user-images.githubusercontent.com/8425483/188462189-be05862f-7d0a-4898-9f6a-c281261e180a.png)

### Expected behavior

The new screenshot should be shown not only in the store but also in the instance.

### Installation method

Community Web installer on a VPS or web space

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 8,
            "timeout": 1.5
        },
        "logtimezone": "Europe\/Berlin",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "skeletondirectory": "",
        "default_locale": "de_DE",
        "default_phone_region": "DE",
        "theme": "",
        "loglevel": 2,
        "simpleSignUpLink.shown": false,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "htaccess.IgnoreFrontController": true,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "version": "25.0.0.8",
        "updater.release.channel": "beta",
        "maintenance": false,
        "app_install_overwrite": [
            "twofactor_webauthn",
            "twofactor_nextcloud_notification",
            "twofactor_admin",
            "impersonate"
        ],
        "blacklisted_files": [],
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": []
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - cloud_federation_api: 1.8.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - files: 1.20.0
  - impersonate: 1.11.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - provisioning_api: 1.15.0
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - theming: 2.0.0
  - twofactor_admin: 0.2.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_email: 2.6.0
  - twofactor_gateway: 0.20.0
  - twofactor_nextcloud_notification: 3.4.0
  - twofactor_totp: 6.4.0
  - twofactor_webauthn: 0.3.1
  - updatenotification: 1.15.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit: 1.13.0
  - circles: 25.0.0-alpha.0
  - comments: 1.12.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.2.0
  - encryption
  - federation: 1.12.0
  - files_external
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - nextcloud_announcements: 1.12.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - recommendations: 1.2.0
  - sharebymail: 1.12.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.12.0
  - text: 3.5.1
  - user_ldap
  - user_status: 1.2.0
  - weather_status: 1.2.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by nursoda** [comment]
Yes, that seems fixed, the new image appears in /settings/apps. However, it is not shown fully due to the new design:
![grafik](https://user-images.githubusercontent.com/8425483/215969813-ac6c7886-c6c6-4b77-8baf-7245ed8c713e.png)
Shall I open a new issue for that or is that addressed already?

**Comment by szaimen** [comment]
Please open a new one for this. Thanks!
