### ISSUE TITLE
Existing config.php values for database are ignored if "installed" key isn't set

### ISSUE THREAD

**Issue by edrex** [nextcloud/server#3391]
Downstream: https://github.com/indiehosters/nextcloud/issues/11

### Steps to reproduce
1. Prepopulate `config/config.php` with `dbtype` etc, but leave `installed` key unset. This is needed when the platform provisions a database but the admin user still needs to be set up.
2. Browse to server.

### Expected behaviour

DB form should be pre-populated with DB settings.

### Actual behaviour

DB form is not populated with existing values.

![screen shot 2017-02-06 at 4 12 48 pm](https://cloud.githubusercontent.com/assets/14615/22673429/10be4af0-ec8f-11e6-80c5-05ed72a9972a.png)

### Server configuration
**Operating system**:
CoreOS

**Web server:**
Nginx/php-fpm

**Database:**
Mysql

**PHP version:**
Zend Engine v2.6.0

**Nextcloud version:** (see Nextcloud admin page)
11.0.1 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Where did you install Nextcloud from:**
https://github.com/indiehosters/nextcloud

(on Libre.sh via `sudo libre provision -a github.com/indiehosters/nextcloud -u nextcloud.pdxhub.org -s`)

**Signing status:**
CLA? I haven't signed one.

**The content of config/config.php:**

Before

```
<?php
$CONFIG = array (
  'trusted_domains' =>
  array (
    0 => 'nextcloud.pdxhub.org',
  ),
  'datadirectory' => '/var/www/html/data',
  'overwrite.cli.url' => 'https://nextcloud.pdxhub.org',
  'dbtype' => 'mysql',
  'dbname' => 'owncloud',
  'dbhost' => 'db:3306',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'root',
  'dbpassword' => 'REDACTED',
  'theme' => '',
  'maintenance' => false,
  'mail_domain' => 'indie.host',
  'mail_from_address' => 'noreply.nextcloud.pdxhub.org',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'mail.indie.host',
  'mail_smtpport' => '587',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => 'noreply.nextcloud.pdxhub.org@indie.host',
  'mail_smtppassword' => 'randompass',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'instanceid' => 'ocd0nb6l4ag2',
);
```

After:
```
<?php
$CONFIG = array (
  'trusted_domains' =>
  array (
    0 => 'nextcloud.pdxhub.org',
  ),
  'datadirectory' => '/var/www/html/data',
  'overwrite.cli.url' => 'https://nextcloud.pdxhub.org',
  'dbtype' => 'mysql',
  'dbname' => 'owncloud',
  'dbhost' => 'db:3306',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'root',
  'dbpassword' => 'REDACTED',
  'theme' => '',
  'maintenance' => false,
  'mail_domain' => 'indie.host',
  'mail_from_address' => 'noreply.nextcloud.pdxhub.org',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'mail.indie.host',
  'mail_smtpport' => '587',
  'mail_smtpauth' => 1,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => 'noreply.nextcloud.pdxhub.org@indie.host',
  'mail_smtppassword' => 'randompass',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'instanceid' => 'ocd0nb6l4ag2',
  'passwordsalt' => 'REDACTED',
  'secret' => 'REDACTED',
  'version' => '11.0.1.2',
  'dbport' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
);
```

**Comment by MorrisJobke** [comment]
We don't support this kind of setup. Use the `occ maintenance:install` command if you want to script this. Or use the password reset functionality if the admin password is unknown for the first login. 

It's not very likely that we will include such half-preprovisioning in our official installation method. If you need this, then you could put a script in front that does this and then call occ maintenance:install.

Thanks
