### ISSUE TITLE
[Bug]: Versions

### ISSUE THREAD

**Issue by chasset** [nextcloud/server#33929]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The history of file changes are not working despite "Versions" is activated on server.

### Steps to reproduce

1. Activate versions in applications list
2. Import a file and modify it
3. Show details of the file : Version tab is empty

### Expected behavior

A file changes history should appear and old file versions should be accessible.

### Installation method

Community Docker image

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
No access to server
```

### List of activated Apps

```shell
All recommended apps
```

### Nextcloud Signing status

```shell
-
```

### Nextcloud Logs

```shell
-
```

### Additional info

-

**Comment by szaimen** [comment]
So E2EE is enabled as well?

**Comment by chasset** [comment]
Yes. I remove E2EE and it works!
