### ISSUE TITLE
Header icons need to invert to black/dark on specific preset background images (like the Dashboard does)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#33969]
The Dashboard already does this correctly, and as discussed with @juliushaertl we should use the same logic for the other pages. Specifically, this applies to these 4 backgrounds:
- bernie-cetonia-aurata-take-off-composition.jpg
- lali-masriera-yellow-bricks.jpg
- rawpixel-pink-tapioca-bubbles.jpg
- tommy-chau-lion-rock-hill.jpg

The logic seems to be with the `--primary-invert-if-bright` variable as far as I can see.

Correct in Dashboard – I would additionally say that we need to invert the logo as well (only if it is our default Nextcloud logo though) cc @karlitschek 
![image](https://user-images.githubusercontent.com/925062/189111950-4925aa10-f995-4a74-a997-77b08429870a.png)

Needs to be adjusted in the other apps. I assume with Julius’ move of the header to Vue this might be easier?
![image](https://user-images.githubusercontent.com/925062/189112039-2d78ed68-7629-45eb-8086-8c4d19fa5701.png)

**Comment by szaimen** [comment]
@CarlSchwan could you maybe also have a fast look into this? I think it is pretty bad...

**Comment by skjnldsv** [comment]
Once #34272 is done, we can easily adjust `--primary-invert-if-bright` accordingly 
I can handle it if no one is diving into this. :)

cc @Pytal

**Comment by Pytal** [comment]
Preset colors of shipped backgrounds are used as primary in https://github.com/nextcloud/server/pull/34298

If this touches the same code then it can be handled by @skjnldsv after the above PR

**Comment by skjnldsv** [comment]
Fixed with #34298

**Comment by Pytal** [comment]
Fixed on dashboard and appearance pages but not globally like on the files page

The `--primary-invert-if-bright` variable needs to be adjusted then @skjnldsv?

**Comment by skjnldsv** [comment]
Isn't the primary-invert-if-bright already using the primary colour?
Why does it needs extra work then?

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/blob/e4d3344076957f40b3cdbab779c3d54fd4c17377/apps/theming/lib/Themes/DefaultTheme.php#L193

**Comment by skjnldsv** [comment]
Ah, this should be properly fixed by https://github.com/nextcloud/server/pull/34437 I guess

**Comment by szaimen** [comment]
> Ah, this should be properly fixed by #34437 I guess

no, not for custom background. It will probably only get fixed with https://github.com/nextcloud/server/issues/34512

**Comment by Pytal** [comment]
> Ah, this should be properly fixed by #34437 I guess

👌

**Comment by skjnldsv** [comment]
Merged and fixed
