### ISSUE TITLE
Search modal design issues

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#33963]
This happens with latest master (not yet on tech-preview):

- The modal has too much margin on all sides, resulting in floating scrollbar and text being cut off on the bottom
- The boxed-in-ness might also be the reason for the horizontal scrollbar
- The text of the entries is not vertically aligned with the icon, but moved a bit to the bottom

![Search screenshot](https://user-images.githubusercontent.com/925062/189102223-72293426-ee4b-4180-b055-e28a6fcd3d98.png)

**Comment by szaimen** [comment]
cc @Pytal

**Comment by CarlSchwan** [comment]
I have a fix, gonna push it in 3min :)
