### ISSUE TITLE
Contacts menu has horizontal scrollbar when email addresses or names are long

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#33965]
See here – the actions are even pushed out of view. This happens with latest master:
![image](https://user-images.githubusercontent.com/925062/189105391-5d8f403b-08fd-4b4f-abf7-54cf6ea7509f.png)

**Comment by szaimen** [comment]
Wasn't this addressed with https://github.com/nextcloud/server/pull/33967?
