### ISSUE TITLE
Contacts menu "more actions" button changes width and is styled incorrectly

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#33966]
The "more actions" button has variable width based on the length of the email address or name on the left. Also, it has a background and border, which it didn’t have before and which incorrectly make it stand out. Happens on current master:
![image](https://user-images.githubusercontent.com/925062/189105846-8db244ea-3d5a-45ea-a05e-11aa3e758b68.png)

**Comment by CarlSchwan** [comment]
Yeah that menu should be ported to vue and the sooner the better. There is also some overflow issues when the email is too big

**Comment by jancborchardt** [comment]
> Yeah that menu should be ported to vue and the sooner the better. There is also some overflow issues when the email is too big

Yes, that is tracked at https://github.com/nextcloud/server/issues/33965

**Comment by szaimen** [comment]
Wasnt this addressed with https://github.com/nextcloud/server/pull/33967?
