### ISSUE TITLE
[Bug]: Login fields overlap container on Safari

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#33972]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On Safari, the inputs and button of the login screen overlap the content:
![image](https://user-images.githubusercontent.com/925062/189118963-860d9f6b-2fe0-4557-9f8a-1abfe7f2dd43.png)

As reported by @karlitschek.

### Steps to reproduce

1. Have macOS
2. Open the login page with Safari

### Expected behavior

The inputs and button do not overlap the container. On Chrome and Firefox it looks good:
![image](https://user-images.githubusercontent.com/925062/189119554-cdc1f770-ea01-461c-ab40-89ab74a39065.png)

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
(Reported by Frank, so not sure. Assume default installation.)
```

**Comment by szaimen** [comment]
I guess this needs fixing by someone with macOS. Maybe @marcoambrosini ?

**Comment by CarlSchwan** [comment]
This was fixed with https://github.com/nextcloud/server/pull/33781 The width of the text fields are not hardcoded anymore and instead just use 100% of the width simplifying the code and removing this bug :)

**Comment by szaimen** [comment]
Great :)

**Comment by jancborchardt** [comment]
Ah awesome, thanks a lot @CarlSchwan! :)
