### ISSUE TITLE
[Bug]: user settings / security: Icons don't adapt to dark mode

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#33996]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Icons stay "black" in dark mode:
<img width="1068" alt="User - Security - Settings -IconsDarkMode" src="https://user-images.githubusercontent.com/1315170/189321338-a8e70e0c-018d-4eff-859e-58e4cabb04d0.png">

### Steps to reproduce

1. Open <server>/settings/user/security

### Expected behavior

Icons should turn "light" in dark mode

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
tech-preview
```

**Comment by szaimen** [comment]
Already fixed with https://github.com/nextcloud/server/pull/33962
