### ISSUE TITLE
[Bug]: User management settings button is broken

### ISSUE THREAD

**Issue by CarlSchwan** [nextcloud/server#33994]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![image](https://user-images.githubusercontent.com/23653902/189305844-ba0ec9db-23d7-42f5-92e7-1a8690372038.png)

### Steps to reproduce

Open user management app

### Expected behavior

More rounded button

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
all the default one
```

**Comment by szaimen** [comment]
Already done in the meantime
