### ISSUE TITLE
Dashboard : Graphical consistency of note and activity widget buttons (and all widgets in general)

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/server#34005]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
The buttons on the widgets are different, which is not very nice or consistent.
![2022-09-09_17-33](https://user-images.githubusercontent.com/33763786/189388012-74d0132c-3314-442c-9065-f41fe7ea7b32.png)

**Describe the solution you'd like**
Ideally, the buttons at the bottom of all widgets should have the same graphic appearance.

**Describe alternatives you've considered**

This may also be an opportunity to look at the next problem regarding the activity widget button : nextcloud/activity#919

**Comment by szaimen** [comment]
Does this need a fix in the activity app?

**Comment by szaimen** [comment]
If yes, I can have a look at it...

**Comment by Jerome-Herbinet** [comment]
The zimbra widget's bottom button seems to have the same design as the activities' one. I don't know if this button design style is the reference to follow 🤔
![Screenshot_2022-09-14-06-50-59-043_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/33763786/190062396-f07e301e-c6c3-414f-bbdc-0412970b3d8a.jpg)

**Comment by szaimen** [comment]
Fixed with https://github.com/nextcloud/nextcloud-vue/pull/3372
