### ISSUE TITLE
Follow up new login background

### ISSUE THREAD

**Issue by CarlSchwan** [nextcloud/server#34003]
Follow up #34000

- [ ] Check if theming still work fine
- [ ] ...

**Comment by xf-** [comment]
@CarlSchwan i think this is the right issue.
Upgrading from beta 3 to beta 6 the issues increaed

Beta 3
- I got a gradient in menu bar and no secondary color in theming to fix it.

(skipped 4 and 5)

Beta 6
- All Theme settings are gone
  - Background image everywhere
  - Dashboard plain won't work, only an image (i think it is related to point above)
  - Blue menu bar
  - Favicon has now a background color (maybe on purpose to account for light and dark themed browsers)
  - Disable caching in developer tools fixed some parts, but not everything (looks like cache busting had an issue)

I use dark Theme in "Appearance and accessibility" and beta looks nothing like the screenshots. Always the cloud image in Background.
