### ISSUE TITLE
Collaborative tagging

### ISSUE THREAD

**Issue by JediMaster25** [nextcloud/server#34014]
I would like to allow access to my nextcloud instance in the following way. People would be allowed to edit the metadata and vote on other peoples edits and would earn points from doing so. They could use those points to download files. I could choose to accept the edits manually or set a given number of total (positive minus negative) votes at which the edits are accepted automatically.

I got the idea from musicbrainz and the adult wiki stash-box.

**Comment by CarlSchwan** [comment]
Sorry but I don't think we want to implement this feature in the core of nextcloud, but you are welcome to implement this in a third party nextcloud app. The API should be sufficient extensible for that.
