### ISSUE TITLE
Suggestion: Share Center

### ISSUE THREAD

**Issue by RogerSik** [nextcloud/server#3401]
Hello,

it would be nice if there is a sharing center / summarize shares. 

When I have 5 different shares of my Photo album to the same person they get 5 links / shares. To link different folder into one folder (maybe with renaming the share) would make sharing like different photo albums easier.

Example:
- New Years Eve\2016  (on share it appears as New Years Eve 2016)
- Event 1\2016-07-xx\  ("")
- Event 2\2017-01-02\ ("")
- Event 1\2014-04-3\ ("")

into Share for Person X.

Currently Person X sees New Years Eve\2016 as 2016 share. Giving them New Years Eve as share they would see every year.

**Comment by MorrisJobke** [comment]
This seems like a very complicated way to handle shares - especially as the owner renames stuff in the scope of the recipient. We try to avoid that another person can mess with the recipients share names. Nevertheless we are trying to make the sharing experience a bit nicer - please follow #434 for this. 

Thanks.
