### ISSUE TITLE
Hook for after uploading a new file

### ISSUE THREAD

**Issue by chris001** [nextcloud/server#3402]
Goal is to use hooks API trigger code to run after a new file is fully uploaded and saved to storage.

Looking at the hooks API, in the `Files` hooks, the only interesting hooks are `afterCreate` and `afterWrite`.

If these hooks, `afterCreate` and `afterWrite`, correspond to their operating system meanings of the terms create file and write file, then neither one of these would trigger at the correct moment.  Create file means the operating system has created an empty file.  Write file means the operating system has written some data, maybe the first few bytes, many some in the middle, maybe the last bytes.

Where is the hook for After Creating Writing  and Closing a New File, or the equivalent?

### Server configuration
**Operating system**:

**Web server:**

**Database:**   Mysql MariaDB 5.6

**PHP version:**  7.0

**Nextcloud version:** (see Nextcloud admin page)  11.

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:**  wget

**Signing status:**
<details>
<summary>Signing status</summary>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- .tag
		- COPYING-AGPL
		- .htaccess.old

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.tag] => Array
                        (
                            [expected] => 
                            [current] => c705b8c49f2b8c93980d737a73b560bfff8a580af236236a174ada1570464904ab469c4195745619d1864832406648cd87f2d494cedcf85f946db85add5bcfdb
                        )

                    [COPYING-AGPL] => Array
                        (
                            [expected] => 
                            [current] => a0a86214ea153fb07ff35ceec0848dd1703eae22de036a825efc8394e50f65e3044832f3b49cf7e45a39edc470bdf738abc36a3a78ca7df3a6e73c14eaef94a8
                        )

                    [.htaccess.old] => Array
                        (
                            [expected] => 
                            [current] => a1ffad2555b862252fd04fe2ec731b02992d6117390258dd89ba91f8ab37d8d9d91430edb1977ce0ec42b7faeda5ac5416b26ad175e6f9d0d7aae958d018019b
                        )

                )

        )

)
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment]
You need to use a storage wrapper for that.
So you need to extend: https://github.com/nextcloud/server/blob/stable11/lib/private/Files/Storage/Wrapper/Wrapper.php#L33-L33

**Comment by codepushr** [comment]
Is this supported with the new hook "postCreate"?
