### ISSUE TITLE
Title for log in page

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#34037]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
The log in page feels a bit off at the moment, possibly due to directly having fields, but not a title like we have on other pages like for errors etc.
![image](https://user-images.githubusercontent.com/925062/189688594-1964e643-e6de-4207-bf1e-5dddbc5efe3f.png)

**Describe the solution you'd like**
Standard heading above the fields:
![image](https://user-images.githubusercontent.com/925062/189688385-9ce4c645-51a9-47ab-a45f-51d48b97fbd5.png)

What do you think @nimishavijay @CarlSchwan?

**Comment by szaimen** [comment]
I'll take this one
