### ISSUE TITLE
File name to long when not English code page 

### ISSUE THREAD

**Issue by kuimovvg** [nextcloud/server#3405]
### Steps to reproduce
this error you can reproduce on demo server when try upload to server file from attachment 

[2)Свидетельство о внесении записи в Единый государственный реестр юридических лиц о юридическом лице, зарегистрированном до 1 июля .txt](https://github.com/nextcloud/server/files/760224/2.1.txt)

I have the same bug on my server with next configuration:
### Server configuration
**Operating system**: Ubuntu 16.04.1

**Web server:** Apache/2.4.18

**Database:** mysql  Ver 15.1 Distrib 10.0.29-MariaDB

**PHP version:** PHP 7.0.13

**Nextcloud version:** 11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** i install Nextcloud from official site

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - calendar: 1.5.0
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml

**The content of config/config.php:**
{
    "system": {
        "instanceid": "oc1anjqz0dx3",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/mnt\/data",
        "dbtype": "mysql",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***\/nextcloud",
        "version": "11.0.1.2",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "loglevel": 0
    }
}

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Webdav

### Client configuration
**Browser:** tested in Google Chrome Version 56.0.2924.76 (64-bit), Chromium Version 49.0.2623.108 Ubuntu 15.10 (64-bit), Firefox 51.0.1 (64-bit)

**Operating system:** Ubuntu 15.10 (64-bit), Ubuntu 16.10 (64-bit)

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"c8gpn+NdmyyKjNbtjZBz","remoteAddr":"**.**.**.**","app":"PHP","message":"fopen(\/mnt\/data\/kuimovvg\/files\/2)\u0421\u0432\u0438\u0434\u0435\u0442\u0435\u043b\u044c\u0441\u0442\u0432\u043e \u043e \u0432\u043d\u0435\u0441\u0435\u043d\u0438\u0438 \u0437\u0430\u043f\u0438\u0441\u0438 \u0432 \u0415\u0434\u0438\u043d\u044b\u0439 \u0433\u043e\u0441\u0443\u0434\u0430\u0440\u0441\u0442\u0432\u0435\u043d\u043d\u044b\u0439 \u0440\u0435\u0435\u0441\u0442\u0440 \u044e\u0440\u0438\u0434\u0438\u0447\u0435\u0441\u043a\u0438\u0445 \u043b\u0438\u0446 \u043e \u044e\u0440\u0438\u0434\u0438\u0447\u0435\u0441\u043a\u043e\u043c \u043b\u0438\u0446\u0435, \u0437\u0430\u0440\u0435\u0433\u0438\u0441\u0442\u0440\u0438\u0440\u043e\u0432\u0430\u043d\u043d\u043e\u043c \u0434\u043e 1 \u0438\u044e\u043b\u044f .txt.ocTransferId1857815681.part): failed to open stream: File name too long at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#287","level":3,"time":"2017-02-08T09:42:44+00:00","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/2)%D0%A1%D0%B2%D0%B8%D0%B4%D0%B5%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D1%82%D0%B2%D0%BE%20%D0%BE%20%D0%B2%D0%BD%D0%B5%D1%81%D0%B5%D0%BD%D0%B8%D0%B8%20%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%B8%20%D0%B2%20%D0%95%D0%B4%D0%B8%D0%BD%D1%8B%D0%B9%20%D0%B3%D0%BE%D1%81%D1%83%D0%B4%D0%B0%D1%80%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9%20%D1%80%D0%B5%D0%B5%D1%81%D1%82%D1%80%20%D1%8E%D1%80%D0%B8%D0%B4%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D1%85%20%D0%BB%D0%B8%D1%86%20%D0%BE%20%D1%8E%D1%80%D0%B8%D0%B4%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%BC%20%D0%BB%D0%B8%D1%86%D0%B5%2C%20%D0%B7%D0%B0%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%BE%D0%BC%20%D0%B4%D0%BE%201%20%D0%B8%D1%8E%D0%BB%D1%8F%20.txt","user":"kuimovvg","version":"11.0.1.2"}
{"reqId":"c8gpn+NdmyyKjNbtjZBz","remoteAddr":"**.**.**.**","app":"webdav","message":"\\OC\\Files\\Filesystem::fopen() failed","level":3,"time":"2017-02-08T09:42:44+00:00","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/2)%D0%A1%D0%B2%D0%B8%D0%B4%D0%B5%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D1%82%D0%B2%D0%BE%20%D0%BE%20%D0%B2%D0%BD%D0%B5%D1%81%D0%B5%D0%BD%D0%B8%D0%B8%20%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%B8%20%D0%B2%20%D0%95%D0%B4%D0%B8%D0%BD%D1%8B%D0%B9%20%D0%B3%D0%BE%D1%81%D1%83%D0%B4%D0%B0%D1%80%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9%20%D1%80%D0%B5%D0%B5%D1%81%D1%82%D1%80%20%D1%8E%D1%80%D0%B8%D0%B4%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D1%85%20%D0%BB%D0%B8%D1%86%20%D0%BE%20%D1%8E%D1%80%D0%B8%D0%B4%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%BC%20%D0%BB%D0%B8%D1%86%D0%B5%2C%20%D0%B7%D0%B0%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%BE%D0%BC%20%D0%B4%D0%BE%201%20%D0%B8%D1%8E%D0%BB%D1%8F%20.txt","user":"kuimovvg","version":"11.0.1.2"}
{"reqId":"c8gpn+NdmyyKjNbtjZBz","remoteAddr":"**.**.**.**","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 500 Could not write file contents\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(137): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #91)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1072): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('2)\\\\xD0\\\\xA1\\\\xD0\\\\xB2\\\\xD0\\\\xB8\\\\xD0\\\\xB4\\\\xD0\\\\xB5\\\\xD1\\\\x82\\\\xD0...', Resource id #91)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('2)\\\\xD0\\\\xA1\\\\xD0\\\\xB2\\\\xD0\\\\xB8\\\\xD0\\\\xB4\\\\xD0\\\\xB5\\\\xD1\\\\x82\\\\xD0...', Resource id #91, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/nextcloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/nextcl...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":131,\"User\":\"kuimovvg\"}","level":4,"time":"2017-02-08T09:42:44+00:00","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/2)%D0%A1%D0%B2%D0%B8%D0%B4%D0%B5%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D1%82%D0%B2%D0%BE%20%D0%BE%20%D0%B2%D0%BD%D0%B5%D1%81%D0%B5%D0%BD%D0%B8%D0%B8%20%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%B8%20%D0%B2%20%D0%95%D0%B4%D0%B8%D0%BD%D1%8B%D0%B9%20%D0%B3%D0%BE%D1%81%D1%83%D0%B4%D0%B0%D1%80%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9%20%D1%80%D0%B5%D0%B5%D1%81%D1%82%D1%80%20%D1%8E%D1%80%D0%B8%D0%B4%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D1%85%20%D0%BB%D0%B8%D1%86%20%D0%BE%20%D1%8E%D1%80%D0%B8%D0%B4%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%BC%20%D0%BB%D0%B8%D1%86%D0%B5%2C%20%D0%B7%D0%B0%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%BE%D0%BC%20%D0%B4%D0%BE%201%20%D0%B8%D1%8E%D0%BB%D1%8F%20.txt","user":"kuimovvg","version":"11.0.1.2"}

</details>

#### Browser log
<details>
<summary>Browser log</summary>
a) The javascript console log
PUT https://*********:17684/nextcloud/remote.php/webdav/2)%D0%A1%D0%B2%D0…%BD%D0%BD%D0%BE%D0%BC%20%D0%B4%D0%BE%201%20%D0%B8%D1%8E%D0%BB%D1%8F%20.txt 500 (Internal Server Error)
send @ jquery.js:8630
ajax @ jquery.js:8166
send @ jquery.fileupload.js?v=4bf479b…:906
(anonymous) @ jquery.js:3256
j @ jquery.js:3099
add @ jquery.js:3145
(anonymous) @ jquery.js:3255
each @ jquery.js:374
(anonymous) @ jquery.js:3252
a.Deferred @ jquery-migrate.min.js?v=4bf479b…:2
then @ jquery.js:3251
_onSend @ jquery.fileupload.js?v=4bf479b…:950
(anonymous) @ jquery-ui.custom.js?v=4bf479b…:405
data.submit @ jquery.fileupload.js?v=4bf479b…:674
(anonymous) @ file-upload.js?v=4bf479b…:251
(anonymous) @ jquery.js:3256
j @ jquery.js:3099
add @ jquery.js:3145
(anonymous) @ jquery.js:3255
each @ jquery.js:374
(anonymous) @ jquery.js:3252
a.Deferred @ jquery-migrate.min.js?v=4bf479b…:2
then @ jquery.js:3251
submit @ file-upload.js?v=4bf479b…:250
(anonymous) @ file-upload.js?v=4bf479b…:489
_.each._.forEach @ underscore.js?v=4bf479b…:153
submitUploads @ file-upload.js?v=4bf479b…:487
onNoConflicts @ file-upload.js?v=4bf479b…:880
checkExistingFiles @ file-upload.js?v=4bf479b…:691
add @ file-upload.js?v=4bf479b…:898
_trigger @ jquery-ui.custom.js?v=4bf479b…:789
(anonymous) @ jquery.fileupload.js?v=4bf479b…:1037
each @ jquery.js:374
_onAdd @ jquery.fileupload.js?v=4bf479b…:1030
(anonymous) @ jquery-ui.custom.js?v=4bf479b…:405
(anonymous) @ jquery.fileupload.js?v=4bf479b…:1235
j @ jquery.js:3099
add @ jquery.js:3145
always @ jquery.js:3246
_onChange @ jquery.fileupload.js?v=4bf479b…:1225
(anonymous) @ jquery-ui.custom.js?v=4bf479b…:405
handlerProxy @ jquery-ui.custom.js?v=4bf479b…:706
dispatch @ jquery.js:4435
r.handle @ jquery.js:4121
b) Request URL:https://*******:17684/nextcloud/remote.php/webdav/2)%D0%A1%D0%B2%D0%B8%D0%B4%D0%B5%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D1%82%D0%B2%D0%BE%20%D0%BE%20%D0%B2%D0%BD%D0%B5%D1%81%D0%B5%D0%BD%D0%B8%D0%B8%20%D0%B7%D0%B0%D0%BF%D0%B8%D1%81%D0%B8%20%D0%B2%20%D0%95%D0%B4%D0%B8%D0%BD%D1%8B%D0%B9%20%D0%B3%D0%BE%D1%81%D1%83%D0%B4%D0%B0%D1%80%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9%20%D1%80%D0%B5%D0%B5%D1%81%D1%82%D1%80%20%D1%8E%D1%80%D0%B8%D0%B4%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D1%85%20%D0%BB%D0%B8%D1%86%20%D0%BE%20%D1%8E%D1%80%D0%B8%D0%B4%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%BC%20%D0%BB%D0%B8%D1%86%D0%B5%2C%20%D0%B7%D0%B0%D1%80%D0%B5%D0%B3%D0%B8%D1%81%D1%82%D1%80%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%BE%D0%BC%20%D0%B4%D0%BE%201%20%D0%B8%D1%8E%D0%BB%D1%8F%20.txt
`
</details>

**Comment by kuimovvg** [comment]
this bug is related with limitation of linux fs and kernel. max file size can be 255 byte. one english character - one byte, russian character is two byte. that's why we have limitation to 128 russian character file name length. If we have just 64 russian character and other character english, then we can create file with file name length 192 and etc.
But when nextcloud is uploading file, in one step created temp file with name consisting file name plus postfix like ".ocTransferId812922278.part". because of this, max file name lenght with all locale is less than 27 characters.

**Comment by MorrisJobke** [comment]
Fixed in #5812 and is available in 12.0.1.
