### ISSUE TITLE
[Bug]: Workflow "File Delete" with specific "System Tag" not being triggered

### ISSUE THREAD

**Issue by marwins** [nextcloud/server#34052]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I might have found a bug with a deleted file workflow based on system tags.
Workflow is not triggered.

The bug seems to be located in this function : https://github.com/nextcloud/server/blob/91040283b131a064dd5d97a804c68c88fe08b673/apps/workflowengine/lib/Check/FileSystemTags.php#L135

**The function returns ids of parents but not file itself (probably because it's deleted).**

Call `$cache->getId($path)` on the total file path returns "-1" (https://github.com/nextcloud/server/blob/91040283b131a064dd5d97a804c68c88fe08b673/apps/workflowengine/lib/Check/FileSystemTags.php#L166)
As the file ids array doesn't contains the file itself, only directories system tags are checked.

#### What I've tried
- Modify flow in database (no way to do it from interface)  to be executed with the `preDelete` event instead of the 'postDelete`: I've got an error `Must set file info before running the check`.

#### What I haven't try yet :
- Change cache configuration
- Debug the ICache::getId function (why does it return -1)
- Debug the solution to set the workflow on `preDelete` instead of `postDelete` event

### Steps to reproduce

1. Create a workflow through the `Webhooks` application
2. Set up file deleted event
3. Set up file system tag filter

![Capture d’écran de 2022-09-13 15-07-53](https://user-images.githubusercontent.com/20090626/189911709-9ee8e2fd-f8b8-4484-8ff4-4eff4430e840.png)

4. Tag a random file with the system tag defined in workflow
5. Delete the file
 

### Expected behavior

The workflow should trigger a post request to the defined url.

### Installation method

Community Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

SQlite

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "log_type": "file",
        "logFile": "nextcloud.log",
        "logLevel": 3,
        "logdateformat": "F d, Y H:i:s",
        "debug": true,
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost:8888",
            "nextcloud"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "24.0.5.1",
        "overwrite.cli.url": "http:\/\/localhost:8888",
        "installed": true,
        "maintenance": false,
        "loglevel": 2,
        "theme": ""
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - bruteforcesettings: 2.4.0
  - circles: 24.0.1
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_automatedtagging: 1.14.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.1
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - webhooks: 0.4.0
  - workflow_ocr: 1.24.4
  - workflow_script: 1.9.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```

### Nextcloud Logs

```shell
No error
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
