### ISSUE TITLE
[Bug]: new design: no focus during weblogin flow

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#34077]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

no focus

### Steps to reproduce

1. use latest master
2. log in via Android
3. after "login" try to enter account name or email
4. see that no focus is in username

### Expected behavior

focus in username field so that one can directly type

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
/
```

### Additional info

also happens on tech-preview

**Comment by PVince81** [comment]
it's also happening on the regular login page, the first field is not automatically focussed

**Comment by PVince81** [comment]
seen by passing by:
<img width="394" alt="image" src="https://user-images.githubusercontent.com/277525/190212420-d55578a7-4c17-4c4d-896c-df3040b35ea8.png">

@CarlSchwan maybe you have a quick clue ?

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/server/pull/34050
