### ISSUE TITLE
[Bug]: NC 25 Error: Undefined array key "extension" at /var/www/nextcloud/apps/files_versions/lib/Storage.php#489

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#34085]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I was trying to delete alot of files and folders at once

### Steps to reproduce

1.Go into a group folder with alot of times
2. Delete the files and folder errors out but deletes 
3.

### Expected behavior

Should delete with no errors

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
NA
```

### Nextcloud Logs

```shell
{"reqId":"lNyX2jZtca5uPedBAk5D","level":3,"time":"2022-09-14T16:38:00+00:00","remoteAddr":"10.99.0.65","user":"admin","app":"PHP","method":"DELETE","url":"/remote.php/dav/files/axheli/IT%20Share/KeePass","message":"Undefined array key \"extension\" at /var/www/nextcloud/apps/files_versions/lib/Storage.php#489","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36","version":"25.0.0.11","exception":{"Exception":"Error","Message":"Undefined array key \"extension\" at /var/www/nextcloud/apps/files_versions/lib/Storage.php#489","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/files_versions/lib/Storage.php","line":489,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/files_versions/lib/Storage.php","line":273,"function":"getVersions","class":"OCA\\Files_Versions\\Storage","type":"::"},{"file":"/var/www/nextcloud/apps/files_versions/lib/Hooks.php","line":71,"function":"delete","class":"OCA\\Files_Versions\\Storage","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Hook.php","line":106,"function":"remove_hook","class":"OCA\\Files_Versions\\Hooks","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1284,"function":"emit","class":"OC_Hook","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1212,"function":"runHooks","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":349,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":305,"function":"rmdir","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":179,"function":"delete","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":281,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":360,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"632203e06c6e9"}

{"reqId":"lNyX2jZtca5uPedBAk5D","level":3,"time":"2022-09-14T16:38:00+00:00","remoteAddr":"10.99.0.65","user":"admin","app":"webdav","method":"DELETE","url":"/remote.php/dav/files/axheli/IT%20Share/KeePass","message":"Unsupported operand types: int - string","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36","version":"25.0.0.11","exception":{"Exception":"TypeError","Message":"Unsupported operand types: int - string","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/files_versions/lib/Storage.php","line":493,"function":"getHumanReadableTimestamp","class":"OCA\\Files_Versions\\Storage","type":"::"},{"file":"/var/www/nextcloud/apps/files_versions/lib/Storage.php","line":273,"function":"getVersions","class":"OCA\\Files_Versions\\Storage","type":"::"},{"file":"/var/www/nextcloud/apps/files_versions/lib/Hooks.php","line":71,"function":"delete","class":"OCA\\Files_Versions\\Storage","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Hook.php","line":106,"function":"remove_hook","class":"OCA\\Files_Versions\\Hooks","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1284,"function":"emit","class":"OC_Hook","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1212,"function":"runHooks","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":349,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":305,"function":"rmdir","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":179,"function":"delete","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":281,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":360,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/files_versions/lib/Storage.php","Line":573,"message":"Unsupported operand types: int - string","exception":[],"CustomMessage":"Unsupported operand types: int - string"},"id":"632203e06c5d4"}
```

### Additional info

https://user-images.githubusercontent.com/59488153/190214133-de0a77e4-6c0e-4efb-9804-7f6df7d3033c.mp4

**Comment by come-nc** [comment]
@andyxheli Or if you can test: https://github.com/nextcloud/server/pull/34528 it should log an error when the name is not as expected and avoid type errors.

**Comment by andyxheli** [comment]
After applying this patch heres the error log

{"reqId":"iqnECMJp20fT3kvlrUWM","level":3,"time":"2022-10-11T13:48:45+00:00","remoteAddr":"10.0.10.90","user":"axheli","app":"files_versions","method":"DELETE","url":"/remote.php/dav/files/axheli/IT%20Share/Software","message":"Version file Software has incorrect name format","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36","version":"25.0.0.15","data":{"app":"files_versions"},"id":"6345745274466"}

{"reqId":"dr3rrgXr2wv5oXHqNt1r","level":3,"time":"2022-10-11T13:48:44+00:00","remoteAddr":"10.0.10.90","user":"axheli","app":"files_versions","method":"DELETE","url":"/remote.php/dav/files/axheli/IT%20Share/Account%20Review","message":"Version file Account Review has incorrect name format","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36","version":"25.0.0.15","data":{"app":"files_versions"},"id":"63457452744f6"}

**Comment by come-nc** [comment]
@andyxheli Thank you for testing.

So, do you have files named "Software" and "Account Review" in files_version folder? (if you do, can you use "ls -lh" to see how old they are and try to see if they are created by a current bug or were leftover of an old bug?)

**Comment by andyxheli** [comment]
What would you like me to do ?

**Comment by come-nc** [comment]
Those folders are in files_version?
Can you do `ls -lh` in there to see how old they are?
I am trying to understand if the bug is that these folders are in there, or that they do not get ignored correctly.

**Comment by andyxheli** [comment]
Yes doing it right now :)

**Comment by andyxheli** [comment]
Also when i go into these folders nothing inside. 

I also have this in my config.php 

'versions_retention_obligation' => 'auto,1',

**Comment by come-nc** [comment]
Ok so I checked it is expected to have folders in `files_versions`. The problem is the cleanup code does not handle correctly getting called on a folder I think.

**Comment by come-nc** [comment]
Hum but I cannot reproduce your error if I have versions for files in a folder and I delete the folder it works. The mystery thickens.

**Comment by andyxheli** [comment]
Do you wanna do a remote  session so i can show you ?

**Comment by come-nc** [comment]
No I need to stop for today, sorry.

**Comment by andyxheli** [comment]
No worries! Let me know. Also these folder and files are with a group folder not sure if that matters

**Comment by come-nc** [comment]
> No worries! Let me know. Also these folder and files are with a group folder not sure if that matters

Oh yeah groupfolder is a whole other beast.
@CarlSchwan Any idea what could go wrong here given it’s a groupfolder with versions?

**Comment by andyxheli** [comment]
Here's what i got when i just deleted everything 

![image](https://user-images.githubusercontent.com/59488153/195128729-1f086e9e-c8e9-4248-8873-26290fee9387.png)

**Comment by come-nc** [comment]
Is the NotPermittedException the same as https://github.com/nextcloud/server/issues/34484 ? If so can you post there that you can reproduce?

**Comment by andyxheli** [comment]
I updated that ticket with NotPermittedException. Thank you! Sorry all these errors happening at once domino effect :(

**Comment by come-nc** [comment]
> Do you wanna do a remote session so i can show you ?

Would you be available this afternoon?
Are you on cloud.nextcloud.com yet?

**Comment by andyxheli** [comment]
Hey @come-nc Yes this afternoon works for me. I am not on cloud.nextcloud.com 

I should be available in about 2 hours if that works for me

**Comment by come-nc** [comment]
> Hey @come-nc Yes this afternoon works for me. I am not on cloud.nextcloud.com
> 
> I should be available in about 2 hours if that works for me

Yes, that works.
Where can I find your email to send you an invite for cloud.nextcloud.com ?

**Comment by andyxheli** [comment]
Send it too axheli at axtsolutions. com please

**Comment by come-nc** [comment]
So, this bug seems specific to groupfolders in the end, which have their own backend for both trash and versions.

From what I understand, the bug is related to:

1. A file is created outside groupfolders
2. The file is modified and versions are stored
3. The file is moved into a groupfolder (most likely a whole folder is moved into a groupfolder, containing versioned files)
4. The file is deleted from groupfolder (most likely its parent folder)
5. Somehow this results in the event trying to delete versions on a folder rather than a file

What I could reproduce already is that moving a versioned file into a groupfolder results in having versions with local system for the groupfolder path, which does not happen for files created directly in the groupfolder.

**Comment by AndyXheli** [comment]
Hi @come-nc issues is back on NC 26.0.1 running GP Folder 14.0.1

{"reqId":"MrIJw0AChp1Cvu2tK0h5","level":3,"time":"2023-04-20T14:19:57+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined array key 176125 at /var/www/nextcloud/apps/files_versions/lib/Storage.php#615","userAgent":"--","version":"26.0.1.1","data":{"app":"PHP"},"id":"644157038ef6d"}

**Comment by come-nc** [comment]
> Hi @come-nc issues is back on NC 26.0.1 running GP Folder 14.0.1
> 
> {"reqId":"MrIJw0AChp1Cvu2tK0h5","level":3,"time":"2023-04-20T14:19:57+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined array key 176125 at /var/www/nextcloud/apps/files_versions/lib/Storage.php#615","userAgent":"--","version":"26.0.1.1","data":{"app":"PHP"},"id":"644157038ef6d"}

Please open an issue on groupfolders application

**Comment by AndyXheli** [comment]
You got it! Thank you!
