### ISSUE TITLE
[Bug]: Opening up a password shared link 'This share is password-protected'. Arrow does not work.

### ISSUE THREAD

**Issue by parts223** [nextcloud/server#34094]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Opening up a password shared link 'This share is password-protected'. When entering password on Chrome and Safari, the arrow does not work. Users are forced to press enter which is inconvenient on Mobile devices.

### Steps to reproduce

1.Share a file using a password.
2.Try to open the link and enter the password.
3. Press the arrow after entering the password. Nothing happens, You need to press enter.

### Expected behavior

Share should be opened after pressing arrow.

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
a
```

### Nextcloud Signing status

```shell
a
```

### Nextcloud Logs

```shell
a
```

### Additional info

az

**Comment by EchoPhalcon** [comment]
I found this issue.
Could I make the pull request ?
Can someone advance in dev skills dm me on discord - EchoPhalcon#5705

**Comment by parts223** [comment]
Can you please write the changes that need to be made here. File name, line number, function name and the change would be great. This way, in the meantime I can make the change for my users while the pull gets looked at.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
