### ISSUE TITLE
Theming app: Change page title to configured name

### ISSUE THREAD

**Issue by mtraeger** [nextcloud/server#341]
For the Theming feature it might be interesting to exchange also the HTML page tile with the new name. At the moment there is `Nextcloud` or `<App> - Nextcloud`.

`<Name>` or `<App> - <Name>` might be interesting for some users.

**Comment by MorrisJobke** [comment]
@schiessle @LukasReschke

**Comment by nickvergessen** [comment]
I'd even say this is a bug, I expected the `Name` option to do that. Took me a while to discover that it only changes the text in the footer.

**Comment by fancycode** [comment]
I guess I'm a bit late to the party, but this causes some confusion with custom themese where you can implement a `getTitle` method - which was used for the page title before (NC 10 and 11).
Now with NC 12 the `getName` is used and the `getTitle` is ignored. With that, I can no longer just change the page title to my custom string and keep `Nextcloud` everywhere else...

**Comment by fancycode** [comment]
Reading the changes more, this is probably not the issue where my problem was introduced - sorry for the noise, will open a new one.
