### ISSUE TITLE
[Bug]: WebDAV Search - Nextcloud 24.0.5 - (25 beta6)

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/server#34109]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The search webDAV return 404.

### Steps to reproduce

We use this query for search the video/photo in date: now / now - 1 month , max 1000 items.

<?xml version="1.0"?>
        <d:searchrequest xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
          <d:basicsearch>
            <d:select>
              <d:prop>
                <d:displayname/>
                <d:getcontenttype/>
                <d:resourcetype/>
                <d:getcontentlength/>
                <d:getlastmodified/>
                <d:getetag/>
                <d:quota-used-bytes/>
                <d:quota-available-bytes/>
                <permissions xmlns="http://owncloud.org/ns"/>
                <id xmlns="http://owncloud.org/ns"/>
                <fileid xmlns="http://owncloud.org/ns"/>
                <size xmlns="http://owncloud.org/ns"/>
                <favorite xmlns="http://owncloud.org/ns"/>
                <creation_time xmlns="http://nextcloud.org/ns"/>
                <upload_time xmlns="http://nextcloud.org/ns"/>
                <is-encrypted xmlns="http://nextcloud.org/ns"/>
                <mount-type xmlns="http://nextcloud.org/ns"/>
                <owner-id xmlns="http://owncloud.org/ns"/>
                <owner-display-name xmlns="http://owncloud.org/ns"/>
                <comments-unread xmlns="http://owncloud.org/ns"/>
                <has-preview xmlns="http://nextcloud.org/ns"/>
                <trashbin-filename xmlns="http://nextcloud.org/ns"/>
                <trashbin-original-location xmlns="http://nextcloud.org/ns"/>
                <trashbin-deletion-time xmlns="http://nextcloud.org/ns"/>
              </d:prop>
            </d:select>
            <d:from>
              <d:scope>
                <d:href>username</d:href>
                <d:depth>infinity</d:depth>
              </d:scope>
            </d:from>
            <d:orderby>
              <d:order>
                <d:prop>
                  <d:getlastmodified/>
                </d:prop>
                <d:descending/>
              </d:order>
              <d:order>
                <d:prop>
                  <d:displayname/>
                </d:prop>
                <d:descending/>
              </d:order>
            </d:orderby>
            <d:where>
              <d:and>
                <d:or>
                  <d:like>
                    <d:prop>
                      <d:getcontenttype/>
                    </d:prop>
                    <d:literal>image/%</d:literal>
                  </d:like>
                  <d:like>
                    <d:prop>
                      <d:getcontenttype/>
                    </d:prop>
                    <d:literal>video/%</d:literal>
                  </d:like>
                </d:or>
                <d:or>
                  <d:and>
                    <d:lt>
                      <d:prop>
                        <d:getlastmodified/>
                      </d:prop>
                      <d:literal>2022-09-16T11:03:23+02:00</d:literal>
                    </d:lt>
                    <d:gt>
                      <d:prop>
                        <d:getlastmodified/>
                      </d:prop>
                      <d:literal>2022-08-29T00:32:19+02:00</d:literal>
                    </d:gt>
                  </d:and>
                </d:or>
              </d:and>
            </d:where>
            <d:limit>
                <d:nresults>1000</d:nresults>
            </d:limit>
          </d:basicsearch>
        </d:searchrequest>

### Expected behavior

Return items.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
/
```

**Comment by PVince81** [comment]
```
% curl 'https://vvortex.local/remote.php/dav/' -X SEARCH -H "Content-Type: text/xml" -u admin:admin --data "@search.xml"     
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File not found: username in 'root'</s:message>
</d:error>
```

on master

**Comment by tobiasKaminsky** [comment]
``` 
<d:scope>
            <d:href>username</d:href>
            <d:depth>infinity</d:depth>
          </d:scope>
```

href must be: /files/username

**Comment by marinofaggiana** [comment]
/files/username ?

**Comment by tobiasKaminsky** [comment]
Yes:
```
    <d:searchrequest xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
      <d:basicsearch>
        <d:select>
          <d:prop>
            <d:displayname/>
            <d:getcontenttype/>
            <d:resourcetype/>
            <d:getcontentlength/>
            <d:getlastmodified/>
            <d:getetag/>
            <d:quota-used-bytes/>
            <d:quota-available-bytes/>
            <permissions xmlns="http://owncloud.org/ns"/>
            <id xmlns="http://owncloud.org/ns"/>
            <fileid xmlns="http://owncloud.org/ns"/>
            <size xmlns="http://owncloud.org/ns"/>
            <favorite xmlns="http://owncloud.org/ns"/>
            <creation_time xmlns="http://nextcloud.org/ns"/>
            <upload_time xmlns="http://nextcloud.org/ns"/>
            <is-encrypted xmlns="http://nextcloud.org/ns"/>
            <mount-type xmlns="http://nextcloud.org/ns"/>
            <owner-id xmlns="http://owncloud.org/ns"/>
            <owner-display-name xmlns="http://owncloud.org/ns"/>
            <comments-unread xmlns="http://owncloud.org/ns"/>
            <has-preview xmlns="http://nextcloud.org/ns"/>
            <trashbin-filename xmlns="http://nextcloud.org/ns"/>
            <trashbin-original-location xmlns="http://nextcloud.org/ns"/>
            <trashbin-deletion-time xmlns="http://nextcloud.org/ns"/>
          </d:prop>
        </d:select>
        <d:from>
          <d:scope>
            <d:href>/files/{{ _.username }}</d:href>
            <d:depth>infinity</d:depth>
          </d:scope>
        </d:from>
        <d:orderby>
          <d:order>
            <d:prop>
              <d:getlastmodified/>
            </d:prop>
            <d:descending/>
          </d:order>
          <d:order>
            <d:prop>
              <d:displayname/>
            </d:prop>
            <d:descending/>
          </d:order>
        </d:orderby>
        <d:where>
          <d:and>
            <d:or>
              <d:like>
                <d:prop>
                  <d:getcontenttype/>
                </d:prop>
                <d:literal>image/%</d:literal>
              </d:like>
              <d:like>
                <d:prop>
                  <d:getcontenttype/>
                </d:prop>
                <d:literal>video/%</d:literal>
              </d:like>
            </d:or>
            <d:or>
              <d:and>
                <d:lt>
                  <d:prop>
                    <d:getlastmodified/>
                  </d:prop>
                  <d:literal>2022-09-16T11:03:23+02:00</d:literal>
                </d:lt>
                <d:gt>
                  <d:prop>
                    <d:getlastmodified/>
                  </d:prop>
                  <d:literal>2022-08-29T00:32:19+02:00</d:literal>
                </d:gt>
              </d:and>
            </d:or>
          </d:and>
        </d:where>
        <d:limit>
            <d:nresults>1000</d:nresults>
        </d:limit>
      </d:basicsearch>
    </d:searchrequest>
 ```

**Comment by marinofaggiana** [comment]
moment check

**Comment by PVince81** [comment]
I can't seem to make it work.
Assuming that this is a regression, did it work with Nextcloud 24.0.4 ?

My steps:

1. Setup v24.0.4 locally
2. Upload a recent picture (mine is from today)
3. Take this ticket's first post payload and replace "username" with "/files/admin" and put it into "search.xml"
4. Run: `curl 'https://vvortex.local/remote.php/dav/' -X SEARCH -H "Content-Type: text/xml" -u admin:admin --data "@search.xml"`

Expected: some results?

Actual: empty multistatus:
```
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns"/>
```

Either the request I tried is wrong or it was already broken in Nextcloud 24.0.4 ?

**Comment by tobiasKaminsky** [comment]
@PVince81 

check this restriction:
``` 
 <d:lt>
                  <d:prop>
                    <d:getlastmodified/>
                  </d:prop>
                  <d:literal>2022-09-16T11:03:23+02:00</d:literal>
                </d:lt>
                <d:gt>
                  <d:prop>
                    <d:getlastmodified/>
                  </d:prop>
                  <d:literal>2022-08-29T00:32:19+02:00</d:literal>
                </d:gt>
```

**Comment by PVince81** [comment]
ok, I've adjusted my steps and am getting results.

I'll try recent versions now

**Comment by marinofaggiana** [comment]
files/username works

**Comment by PVince81** [comment]
works for me as well on master, no regression then ? @marinofaggiana

**Comment by marinofaggiana** [comment]
Strange ... I must indagate in my code ... sorry for the noise.

**Comment by marinofaggiana** [comment]
> works for me as well on master, no regression then ? @marinofaggiana

with files/ works ... something is change I think in my code
