### ISSUE TITLE
Error: The given author user is invalidN

### ISSUE THREAD

**Issue by EasyPeasy1** [nextcloud/server#3410]
Hi, 
I found this Error in my logs.
I think it always appears if a shared link expires.

`{"reqId":"ldEFD98xxyGWYO3\/Ot4O","remoteAddr":"","app":"no app in context","message":"Exception: {\"Exception\":\"InvalidArgumentException\",\"Message\":\"The given author user is invalidN;\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(889): OC\\\\Activity\\\\Event->setAuthor(NULL)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(749): OCA\\\\Activity\\\\FilesHooks->addNotificationsForUser('myusername', 'link_expired', Array, 172, '\\\/myFolder1\\\/myFolder2', false, true, 0)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(565): OCA\\\\Activity\\\\FilesHooks->shareFileOrFolderByLink(172, 'folder', 'myusername', false)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/activity\\\/lib\\\/FilesHooksStatic.php(101): OCA\\\\Activity\\\\FilesHooks->unShare(Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/hook.php(106): OCA\\\\Activity\\\\FilesHooksStatic::unShare(Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Share\\\/Share.php(1541): OC_Hook::emit('OCP\\\\\\\\Share', 'pre_unshare', Array)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Share\\\/Share.php(977): OC\\\\Share\\\\Share::unshareItem(Array, NULL)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/public\\\/Share.php(290): OC\\\\Share\\\\Share::unshare('folder', '172', 3, NULL, 'myusername')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_sharing\\\/lib\\\/ExpireSharesJob.php(72): OCP\\\\Share::unshare('folder', '172', 3, NULL, 'myusername')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php(53): OCA\\\\Files_Sharing\\\\ExpireSharesJob->run(NULL)\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php(54): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#11 \\\/var\\\/www\\\/nextcloud\\\/cron.php(128): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Activity\\\/Event.php\",\"Line\":165}","level":3,"time":"2017-02-08T23:00:11+01:00","method":"--","url":"--","user":"--","version":"11.0.1.2"}`

Operating System:
Ubuntu 16.04 LTS
Apache 2.4.18
PHP 7.0.8
Nextcloud 11.0.1

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/activity/pull/109
