### ISSUE TITLE
[Bug]: Template dialog is to small and unintuitive 

### ISSUE THREAD

**Issue by danir-de** [nextcloud/server#34116]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

We're getting many requests from users, that are unable to create new files. When looking into it, the issue seems to be the template chosser for new files, that is badly designed.

When creating a file which has many/mutliple templates available for it, it becomes unclear to many users, that they have to scroll in order to find the Create file button or to see more templates.

A quick demonstration of how bad the current design is, on a standard WQHD monitor (on 4K it's even worse):
![image](https://user-images.githubusercontent.com/4672840/190681933-cf5a2613-ce13-4564-94bf-ea5c978fa437.png)
This is a problem even on a FullHD monitor, as seen in [#32068](https://user-images.githubusercontent.com/551757/164698541-15ca7eae-2609-453d-8716-5ff5d32c2654.png) and is made even worse on [mobile](https://user-images.githubusercontent.com/4672840/190685029-ca5d8d04-2bfa-4d25-afab-1500657ef2b4.png).

In addition to wasting the complete screen realestate, if more than 2 templates exist, the usability goes downhill by clipping the viewable frame-contents instead of making a vertically scrollable list, thus hiding all other templates and the "Create" button. 

### Steps to reproduce

1. Create more than two templates for a document type.
2. Create a new document - opening the template dialog.
3. Observe template dialog in "hard mode".

### Expected behavior

The dialog should use more of the horizontal space (currently max 600px) and expand vertically (not horizontally) if needed to show more templates.
The cancel and create buttons should be kept visible at all times - making it possible to use the dialog without having to know you'd have to scroll. Placing them at top, would make usage on mobile easier, by not having to scroll to see the buttons.

Maybe even indicate that you can scroll downwards with a small animation.

### Installation method

Community Manual installation with Archive

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)
Currently on 24.0.4.

### List of activated Apps

```shell
Not relevant.
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
