### ISSUE TITLE
[Bug]: NC25 new theming: markdown parsing glitch (apps' changelog)

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#34149]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

A markdown changelog typically consists of headings such as "Added", "Changed", "Removed", … and a list of items within that heading. These are typically displayed as bullet list. In /settings/apps, Nextcloud displays the changelog (if provided) when displaying an app's details (as separate tab).

However, at least since NC25 theming redesign, consecutive headers are displayed indented in the unordered list instead of outside that list (left-aligned) if they do not contain empty lines between the list and the next header. The HTML source shows that in this the next heading is parsed into the <li> element.

![grafik](https://user-images.githubusercontent.com/8425483/191126636-9094660d-67fa-481e-8716-244b4722951c.png)

### Steps to reproduce

1. Install an app that provides a changelog with multiple sections but without empty lines between "- …" list items and the next "### …" header
2. open details→changes tab in /settings/apps

### Expected behavior

Markdown headings should be parsed as main headings, not to be contained within a list. `<li>` and `<ul>` should be closed, then the next heading should be leftmost as standalone `<h3>`. Only then the next `<ul>` list should be opened.

### Installation method

Community Manual installation with Archive

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - cloud_federation_api: 1.8.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - files: 1.20.0
  - impersonate: 1.11.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - provisioning_api: 1.15.0
  - related_resources: 0.9.2
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_email: 2.7.0
  - twofactor_gateway: 0.20.0
  - twofactor_nextcloud_notification: 3.5.0-beta.1
  - twofactor_totp: 6.4.0
  - twofactor_webauthn: 0.3.1
  - updatenotification: 1.15.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit: 1.13.0
  - circles: 25.0.0-alpha.0
  - comments: 1.12.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.2.0
  - encryption
  - federation: 1.12.0
  - files_external
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - nextcloud_announcements: 1.12.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - recommendations: 1.2.0
  - sharebymail: 1.12.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.12.0
  - text: 3.5.1
  - twofactor_admin: 0.2.1
  - user_ldap
  - user_status: 1.2.0
  - weather_status: 1.2.0
```

**Comment by joshtrichards** [comment]
Fixed in v27.0.2
