### ISSUE TITLE
[Bug]: NC 25 Users Layout missing check marks and layout is off 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#34148]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Please see images between NC 24 & NC 25 

Tested on NC 25 Beta 7 & NC 24.0.5

![image](https://user-images.githubusercontent.com/59488153/191105356-78b0f0f7-03f3-4b97-8de1-0171a731f0f1.png)
![image](https://user-images.githubusercontent.com/59488153/191105690-ac285c3e-0caf-405f-a841-20f1e2c338ac.png)
![image](https://user-images.githubusercontent.com/59488153/191106689-650582f3-5bae-42e8-8a55-5371ca77b6c7.png)
![image](https://user-images.githubusercontent.com/59488153/191106804-1172a575-f958-4820-96a5-d6fbe90c4872.png)

### Steps to reproduce

1. Open settings
2.Users
3.Click on the user and add them to the group

### Expected behavior

There should be check marks next on the group that the user is a member off and the boxes should not be that close. 

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
NA
```

**Comment by szaimen** [comment]
cc @nextcloud/server-frontend it seems like the user page is indeed very broken on master and stable25. Just verified and there are a lot of issues.

**Comment by szaimen** [comment]
For example, you cannot scroll sidewayss on smaller display sizes and thus not see the entries.... also the 3-dot button seems to be broken and other stuff...

**Comment by szaimen** [comment]
@Pytal could you maybe take a look at this? :)

**Comment by Pytal** [comment]
> @Pytal could you maybe take a look at this? :)

Sorry can't have a look soon @szaimen, wanna have a go?

**Comment by skjnldsv** [comment]
![image](https://user-images.githubusercontent.com/14975046/203515488-a40489f1-9ff9-4d5d-9c84-112b15c60307.png)

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/nextcloud-vue/pull/3513

**Comment by szaimen** [comment]
Reopening since a vue lib update is required and backported to stable25. Also the layout was not completely fixed in my testing

**Comment by PVince81** [comment]
- [x] master: https://github.com/nextcloud/server/issues/34148
    - [ ] stable25: https://github.com/nextcloud/server/pull/35375
- [ ] master: https://github.com/nextcloud/server/pull/35380
    - [ ] stable25: todo
- [ ] update nextcloud-vue to fix multiselect tick marks
    - [ ] stable25: todo
