### ISSUE TITLE
[Bug]: NC25 new theming glitches: app details app icon, app details sidebar alignment

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#34150]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

(1) The default app icon seems to have to be white on transparent (unexpected but OK when properly documented). In that case, in NC 25 beta 7, most app icons are displayed properly in light and dark theme – except for the App Details page, if there is no app image.

(2) If one reduces the browser window's hight too much, the sidebar slides down from it's top edge.

![grafik](https://user-images.githubusercontent.com/8425483/191152578-957487e1-034a-45ce-a8b3-8238da251201.png)

### Steps to reproduce

0. Install any app that provides a default icon that is display "properly" in theming and that does not include a preview picture in the app store.
1. Display the app's details in /settings/apps → The icon is displayed in dark in dark mode and light in light mode (should be inversed)
2. Reduce the browser window size (especially it's height) and until the sidebar starts to move out of alignment.

### Expected behavior

The icon should be displayed the same way it is displayed in the app list.
The sidebar should be top-aligned no matter of the window size.

### Installation method

Community Manual installation with Archive

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - cloud_federation_api: 1.8.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - files: 1.20.0
  - impersonate: 1.11.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - provisioning_api: 1.15.0
  - related_resources: 0.9.2
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_email: 2.7.0
  - twofactor_gateway: 0.20.0
  - twofactor_nextcloud_notification: 3.5.0-beta.1
  - twofactor_totp: 6.4.0
  - twofactor_webauthn: 0.3.1
  - updatenotification: 1.15.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit: 1.13.0
  - circles: 25.0.0-alpha.0
  - comments: 1.12.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.2.0
  - encryption
  - federation: 1.12.0
  - files_external
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - nextcloud_announcements: 1.12.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - recommendations: 1.2.0
  - sharebymail: 1.12.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.12.0
  - text: 3.5.1
  - twofactor_admin: 0.2.1
  - user_ldap
  - user_status: 1.2.0
  - weather_status: 1.2.0
```

**Comment by szaimen** [comment]
Hi, can you try again with 25.0.1?

**Comment by nursoda** [comment]
**Issue (1)**

still exists in 25.0.1. Screenshots are taken with "follow system theme" set in NC personal appearance and in Firefox, System theme is set to "dark" in KDE Plasma on Arch:

![grafik](https://user-images.githubusercontent.com/8425483/201081992-394c6f01-ffaa-4c00-9fad-5716f65171ca.png)
![grafik](https://user-images.githubusercontent.com/8425483/201081895-cbeee362-2c2f-4ba9-a65e-cdf009deb565.png)

It cannot be reproduced with twofactor_webauthn as there now is a (wrong!) app preview:

![grafik](https://user-images.githubusercontent.com/8425483/201082786-8f64d912-372c-4838-99c5-2577a3038176.png)

**Issue (2)**

at first seems resolved, and is, for static browser sizes. However, if you reduce the browser window's width until it only shows the main content column and then widen it again, you end up like this (no matter how wide the browser windows is afterwards):

![grafik](https://user-images.githubusercontent.com/8425483/201083485-8a6b74ea-5c68-4402-8306-b411d00982ca.png)

So both issues still exist.

**Comment by joshtrichards** [comment]
These look fixed not only in NC28, but also in later patch releases of NC25 based on my testing. Feel free to comment back if you disagree and I'll re-open. I'm not going to try find the relevant PRs because they're likely spread across several library repositories.
