### ISSUE TITLE
[Bug]: New app's thumbnail is not loaded if image is replaced inline (without changing its URL)

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#34151]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I have this line in my app's appinfo/info.xml:

`<screenshot small-thumbnail="https://raw.githubusercontent.com/nursoda/twofactor_email/main/screenshots/select-auth_thumb.png">https://raw.githubusercontent.com/nursoda/twofactor_email/main/screenshots/challenge.png</screenshot>`

I replaced that screenshot image on GitHub two weeks ago. In the app store, the new screenshots and thumbnails are displayed:

![grafik](https://user-images.githubusercontent.com/8425483/191154901-31cf3bbe-2159-49a0-a050-13a8f275676b.png)
![grafik](https://user-images.githubusercontent.com/8425483/191155295-41b28620-0741-44d2-8a5e-0bca12592b78.png)

Not so in /settings/apps App's Details – there, the old image remains:

![grafik](https://user-images.githubusercontent.com/8425483/191155172-71ec8b9b-be65-4a43-ba54-7c6b29e11647.png)

Clearing cache and reloading does not solve it.

### Steps to reproduce

1. Create a NC app, do screenshots, link them with a static URL in info.xml, publish the app in the NC app store. Install the app in a NC instance. Check that images are shown in app store and NC instance.
2. Change screenshots and upload them to the SAME static URL. Check the app's details page in the store: new images are shown. Check in the NC instance: old image remains.

### Expected behavior

The new thumbnails should be displayed in /settings/apps aswell.

### Installation method

Community Manual installation with Archive

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - cloud_federation_api: 1.8.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - files: 1.20.0
  - impersonate: 1.11.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - provisioning_api: 1.15.0
  - related_resources: 0.9.2
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_email: 2.7.0
  - twofactor_gateway: 0.20.0
  - twofactor_nextcloud_notification: 3.5.0-beta.1
  - twofactor_totp: 6.4.0
  - twofactor_webauthn: 0.3.1
  - updatenotification: 1.15.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit: 1.13.0
  - circles: 25.0.0-alpha.0
  - comments: 1.12.0
  - contactsinteraction: 1.4.0
  - dashboard: 7.2.0
  - encryption
  - federation: 1.12.0
  - files_external
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.2.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.12.0
  - firstrunwizard: 2.12.0
  - nextcloud_announcements: 1.12.0
  - photos: 1.5.0
  - privacy: 1.7.0
  - recommendations: 1.2.0
  - sharebymail: 1.12.0
  - support: 1.6.0
  - survey_client: 1.11.0
  - systemtags: 1.12.0
  - text: 3.5.1
  - twofactor_admin: 0.2.1
  - user_ldap
  - user_status: 1.2.0
  - weather_status: 1.2.0
```

**Comment by szaimen** [comment]
I think the image may be cached...

**Comment by nursoda** [comment]
Yes, it seems like it, but not locally in the browser but on `usercontent.apps.nextcloud.com`:

This is the image URL I see in my browser:

`https://usercontent.apps.nextcloud.com/aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL251cnNvZGEvdHdvZmFjdG9yX2VtYWlsL21haW4vc2NyZWVuc2hvdHMvY2hhbGxlbmdlLnBuZw==`

The base64-encoded path part of the URL resolves to `https://raw.githubusercontent.com/nursoda/twofactor_email/main/screenshots/challenge.png`

So, do I have to report an issue to the app store repo?

**Comment by szaimen** [comment]
> So, do I have to report an issue to the app store repo?

Sounds like it

**Comment by nursoda** [comment]
Closing in in favor of https://github.com/nextcloud/appstore/issues/925.
