### ISSUE TITLE
[Bug]: graphical glitch on setup page on nc25-beta7

### ISSUE THREAD

**Issue by ArtificialOwl** [nextcloud/server#34158]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

<img width="974" alt="beta7_setup_popup" src="https://user-images.githubusercontent.com/1038617/191222313-06dcc084-ac23-4101-b4ab-4ba24a7dc5bb.png">

Tested on firefox and IE
Tested on different hosting location

### Steps to reproduce

1. download nc25-beta7
2. extract the file at the right place
3. open the page to start the setup of nextcloud

### Expected behavior

better display of the popup

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
no config at this point of the setup process
```

### List of activated Apps

```shell
none
```

### Nextcloud Logs

```shell
data/ is not created at this point of the process
```

**Comment by PVince81** [comment]
bisect points at df40fc91729ebd66941705637b440033036c8b8e as the breaking commit

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/server/pull/34197

**Comment by PVince81** [comment]
fixed in https://github.com/nextcloud/server/pull/34222
