### ISSUE TITLE
[Bug]: Error updating from 24 to 24.0.5: Onlyoffice app migration failed

### ISSUE THREAD

**Issue by pixxelfactory** [nextcloud/server#34153]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Just wanted to update my nextcloud installation from 24 to 24.0.5
It went smooth until i got to the step where it tried to update the onlyoffice app.
I got the following message:

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturschritt: Repair MySQL collation
Reparaturinformation: Not a mysql database -> nothing to do
Reparaturschritt: Repair SQLite autoincrement
Reparaturschritt: Copy data from accounts table when migrating from ownCloud
Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert
Datenbank aktualisiert

Exception: Database error when running migration 070400Date20220607111111 for app onlyoffice An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 index share_id_index already exists

Tried it a couple of times, but it seems a bug in the migration procedure.

### Steps to reproduce

1. Get a nextcloud installation version 24(.0) with the onlyoffice app installed
2. Try to update to 24.0.5 via the web-based updater
3. Go to the step where it wants to update the onlyoffice app

### Expected behavior

Just update the app and return to the administration

### Installation method

Community Web installer on a VPS or web space

### Operating system

RHEL/CentOS

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Dont have root ssh access to the server, but i'm running the Onlyoffice app & the community document server
```

**Comment by szaimen** [comment]
Hi, please report this to https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues. Thanks!
