### ISSUE TITLE
[Bug]: NC 25 Password Policy warning show up under authentication required

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#34166]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![image](https://user-images.githubusercontent.com/59488153/191302170-763e59db-eacf-478b-9f8b-b07a7875cb5c.png)

### Steps to reproduce

1. I was going to download ad app from the app store 
2. asked me to authenticate 
3.

### Expected behavior

I think should should only come up if a user is changing their password unless this is intended 

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
NA
```

**Comment by szaimen** [comment]
This is intended afaik
