### ISSUE TITLE
admin password confirmation problem

### ISSUE THREAD

**Issue by KB7777** [nextcloud/server#3416]
Hello.

Where LDAP user is added to local admin group he can't confirm password for changing some settings. I checked it with local admin password and LDAP user password

Log shows:
Warning	core	Login failed: 'admin' (Remote IP: 'XXXXXX')	2017-02-09T13:45:36+0100
Warning	core	Login failed: 'admin' (Remote IP: 'XXXXXX')	2017-02-09T13:45:31+0100

**Comment by nickvergessen** [comment]
Issues was fixed for 11.0.2
You can copy the fix from https://github.com/nextcloud/server/pull/2953/files if you can't wait until then
