### ISSUE TITLE
[Bug]: NC 25 Button issue in LDAP\ AD Integration when expanding box

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/server#34177]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

This only seems to happen in NC 25. Tested it on NC 24 no issues. 

Happens in both dark theme and white mode 

### Steps to reproduce

https://user-images.githubusercontent.com/59488153/191549794-ac7719ca-eccd-4078-ab0e-ada4cd0a309a.mp4

### Expected behavior

Should not do this

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
NA
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by andyxheli** [comment]
Still an issue on NC 25.0.3

**Comment by zmijunkie** [comment]
Same here - NC 25.0.3

**Comment by zmijunkie** [comment]
well ... I am trying to set everything with `occ ldap:set-config s0` by now ... also I am watching /var/log/nextcloud/nextcloud.log - I guess I find out what is going on ... error messages are not to bad so far

**Comment by joshtrichards** [comment]
What web server are you using?

If NGINX - make sure you have these two lines:

https://github.com/nextcloud/documentation/blob/32559abb2d9995d9de094747b754d0eea5c0af60/admin_manual/installation/nginx-root.conf.sample#L145-L146

If Apache:

Are you relying on the .htaccess bundled with Nextcloud or did you roll your own Apache config (for NC specific headers, rewrite rules, etc).

**Comment by AndyXheli** [comment]
Closing not seeing this issue on NC 29 RC2
