### ISSUE TITLE
[Bug]: Unable to connect to NC web

### ISSUE THREAD

**Issue by SDISPO** [nextcloud/server#34175]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello

Since a couple of days, I can no longer access my server from the web with "simple" user accounts or admin accounts (not a password issue)

Nevertheless, with the clients, app or webdav, you can access to the documents.

Any help will be appreciated

### Steps to reproduce

1.Enter server adress into browser (Mozilla, Edge, Chome, etc)
2.Enter user account and Pwd
3.

### Expected behavior

Access to the documents and the rest

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Calendar
Contact
File sharing
External Site
Activity
Notif
Deleted files
User status
Comments
Etc
```

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
