### ISSUE TITLE
Prevent upload of file with names having a case clash with other file names in the same folder

### ISSUE THREAD

**Issue by mgallien** [nextcloud/server#34174]
Currently it is possible for files to be uploaded with names only differing in casing.
For example `owl.gif` and `OWL.GIF` can be uploaded in `Test`. In this case, users running a desktop client to sync their files on operating system like windows and macOS will have to manually fix those name clash to prevent sync errors (see https://github.com/nextcloud/desktop/issues/4963).

It would be nice to be able to configure the server to block any upload (or other file operations) that would create such a case clash. That would put the burden of solving the issue on the user creating the case clash and not on the user syncing the files.

**Comment by mgallien** [comment]
@tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
@AndyScherzinger @jancborchardt I think we discussed this already at some time.
The question is when and who shall take action
- the one that creates the problem: obviously this works for them, so they help to avoid such problems for others
- the one that has the problem. Downside here is that it is already synced to server and then needs to be rolled out to all others

Config flag sounds good as the server admin knows if such a hybrid environment is used at all.
If e.g. only Windows clients are used, then there is no such problem possible.

Famous question: Do you know how other do this? e.g. Dropbox?

**Comment by tobiasKaminsky** [comment]
Doing it with approach in https://github.com/nextcloud/desktop/issues/5099
