### ISSUE TITLE
🆕 Bump app requirements and testing in apps

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#34189]
## Shipped apps

- [x] https://github.com/nextcloud/activity/pull/928
- [x] https://github.com/nextcloud/circles/pull/1159
- [x] https://github.com/nextcloud/files_pdfviewer/pull/657
- [x] https://github.com/nextcloud/files_rightclick/pull/145
- [x] https://github.com/nextcloud/files_videoplayer/pull/285
- [x] https://github.com/nextcloud/firstrunwizard/pull/741
- [x] https://github.com/nextcloud/logreader/pull/786
- [x] https://github.com/nextcloud/nextcloud_announcements/pull/104
- [x] https://github.com/nextcloud/notifications/pull/1279
- [x] https://github.com/nextcloud/password_policy/pull/384
- [x] https://github.com/nextcloud/photos/pull/1280
- [x] https://github.com/nextcloud/privacy/pull/788
- [x] https://github.com/nextcloud/recommendations/pull/551
- [x] https://github.com/nextcloud/related_resources/pull/51
- [x] https://github.com/nextcloud/serverinfo/pull/399
- [x] https://github.com/nextcloud/survey_client/pull/145
- [x] https://github.com/nextcloud/suspicious_login/pull/702
- [x] https://github.com/nextcloud/text/pull/2981
- [x] https://github.com/nextcloud/twofactor_totp/pull/1265

---
## Other apps

- [x] https://github.com/nextcloud/data_request/pull/72
- [x] https://github.com/nextcloud/deck/pull/4068
- [x] https://github.com/nextcloud/end_to_end_encryption/pull/328
- [x] https://github.com/nextcloud/external/pull/311
- [x] https://github.com/nextcloud/files_accesscontrol/pull/267
- [x] https://github.com/nextcloud/files_automatedtagging/pull/594
- [x] https://github.com/nextcloud/files_retention/pull/200
- [x] https://github.com/nextcloud/groupfolders/pull/2096
- [x] https://github.com/nextcloud/impersonate/pull/162
- [x] https://github.com/nextcloud/ldap_contacts_backend/pull/45
- [x] https://github.com/nextcloud/ldap_write_support/pull/515
- [x] https://github.com/nextcloud/richdocuments/pull/2453
- [x] https://github.com/nextcloud/sharepoint/pull/144
- [x] https://github.com/nextcloud/spreed/pull/7979
- [x] https://github.com/nextcloud/user_migration/pull/244
- [x] https://github.com/nextcloud/user_usage_report/pull/109
- [ ] https://github.com/nextcloud/announcementcenter/pull/528
- [x] https://github.com/nextcloud/recognize/pull/332
- [x] https://github.com/nextcloud/calendar/pull/4533
- [x] https://github.com/nextcloud/contacts/pull/2956
- [x] https://github.com/nextcloud/files_antivirus/pull/244
- [x] https://github.com/nextcloud/files_downloadactivity/pull/102
- [x] https://github.com/nextcloud/files_zip/pull/98
- [x] https://github.com/nextcloud/forms/pull/1354
- [ ] https://github.com/nextcloud/guests/pull/933
- [x] https://github.com/nextcloud/mail/pull/7306
- [x] https://github.com/nextcloud/notify_push/pull/189
- [ ] https://github.com/nextcloud/officeonline/pull/355
- [x] https://github.com/nextcloud/quota_warning/pull/114
- [x] https://github.com/nextcloud/registration/pull/462
- [ ] https://github.com/nextcloud/social/pull/1480
- [ ] https://github.com/nextcloud/twofactor_u2f/pull/1024
- [x] https://github.com/nextcloud/twofactor_webauthn/pull/261
- [x] https://github.com/nextcloud/user_oidc/pull/503
- [ ] https://github.com/nextcloud/user_saml/pull/657

**Comment by nickvergessen** [comment]
# Allow Nextcloud 26


- [ ] https://github.com/nextcloud/activity/pull/929
- [ ] https://github.com/nextcloud/bruteforcesettings/pull/394
- [ ] https://github.com/nextcloud/circles/pull/1160
- [ ] https://github.com/nextcloud/files_pdfviewer/pull/658
- [ ] https://github.com/nextcloud/files_rightclick/pull/146
- [ ] https://github.com/nextcloud/files_videoplayer/pull/286
- [ ] https://github.com/nextcloud/firstrunwizard/pull/742
- [ ] https://github.com/nextcloud/logreader/pull/787
- [ ] https://github.com/nextcloud/nextcloud_announcements/pull/105
- [ ] https://github.com/nextcloud/notifications/pull/1281
- [ ] https://github.com/nextcloud/password_policy/pull/385
- [ ] https://github.com/nextcloud/photos/pull/1281
- [ ] https://github.com/nextcloud/privacy/pull/789
- [ ] https://github.com/nextcloud/recommendations/pull/552
- [ ] https://github.com/nextcloud/serverinfo/pull/400
- [ ] https://github.com/nextcloud-gmbh/support/pull/152
- [ ] https://github.com/nextcloud/survey_client/pull/146
- [ ] https://github.com/nextcloud/suspicious_login/pull/703
- [ ] https://github.com/nextcloud/text/pull/2982
- [ ] https://github.com/nextcloud/twofactor_totp/pull/1266
- [ ] https://github.com/nextcloud/viewer/pull/1383
- [ ] https://github.com/nextcloud/data_request/pull/73
- [ ] https://github.com/nextcloud/deck/pull/4070
- [ ] https://github.com/nextcloud/end_to_end_encryption/pull/330
- [ ] https://github.com/nextcloud/external/pull/312
- [ ] https://github.com/nextcloud/files_accesscontrol/pull/268
- [ ] https://github.com/nextcloud/files_automatedtagging/pull/595
- [ ] https://github.com/nextcloud/files_fulltextsearch/pull/199
- [ ] https://github.com/nextcloud/files_retention/pull/201
- [ ] https://github.com/nextcloud/flow_notifications/pull/58
- [ ] https://github.com/nextcloud/fulltextsearch/pull/718
- [ ] https://github.com/nextcloud/fulltextsearch_elasticsearch/pull/224
- [ ] https://github.com/nextcloud/groupfolders/pull/2099
- [ ] https://github.com/nextcloud/impersonate/pull/163
- [ ] https://github.com/nextcloud/ldap_contacts_backend/pull/46
- [ ] https://github.com/nextcloud/ldap_write_support/pull/516
- [ ] https://github.com/nextcloud/profiler/pull/75
- [ ] https://github.com/nextcloud/richdocuments/pull/2455
- [ ] https://github.com/nextcloud/sharepoint/pull/145
- [ ] https://github.com/nextcloud/spreed/pull/7980
- [ ] https://github.com/nextcloud/terms_of_service/pull/749
- [ ] https://github.com/nextcloud/user_migration/pull/245
- [ ] https://github.com/nextcloud/user_retention/pull/470
- [ ] https://github.com/nextcloud/user_usage_report/pull/110
- [ ] https://github.com/nextcloud/workflow_pdf_converter/pull/417
- [ ] https://github.com/nextcloud/workflow_script/pull/121
- [ ] https://github.com/nextcloud/announcementcenter/pull/529
- [ ] https://github.com/nextcloud/calendar/pull/4534
- [ ] https://github.com/nextcloud/contacts/pull/2957
- [ ] https://github.com/nextcloud/files_antivirus/pull/246
- [ ] https://github.com/nextcloud/files_downloadactivity/pull/103
- [ ] https://github.com/nextcloud/files_downloadlimit/pull/127
- [ ] https://github.com/nextcloud/files_texteditor/pull/606
- [ ] https://github.com/nextcloud/files_zip/pull/99
- [ ] https://github.com/nextcloud/forms/pull/1355
- [ ] https://github.com/nextcloud/globalsiteselector/pull/76
- [ ] https://github.com/nextcloud/guests/pull/934
- [ ] https://github.com/nextcloud/integration_discourse/pull/33
- [ ] https://github.com/nextcloud/integration_github/pull/45
- [ ] https://github.com/nextcloud/integration_gitlab/pull/49
- [ ] https://github.com/nextcloud/integration_google/pull/117
- [ ] https://github.com/nextcloud/integration_jira/pull/35
- [ ] https://github.com/nextcloud/integration_mastodon/pull/34
- [ ] https://github.com/nextcloud/integration_moodle/pull/37
- [ ] https://github.com/nextcloud/integration_reddit/pull/30
- [ ] https://github.com/nextcloud/integration_twitter/pull/38
- [ ] https://github.com/nextcloud/integration_whiteboard/pull/52
- [ ] https://github.com/nextcloud/integration_zammad/pull/33
- [ ] https://github.com/nextcloud/mail/pull/7307
- [ ] https://github.com/nextcloud/notify_push/pull/190
- [ ] https://github.com/nextcloud/officeonline/pull/356
- [ ] https://github.com/nextcloud/preferred_providers/pull/30
- [ ] https://github.com/nextcloud/quota_warning/pull/115
- [ ] https://github.com/nextcloud/ransomware_protection/pull/118
- [ ] https://github.com/nextcloud/recognize/pull/333
- [ ] https://github.com/nextcloud/registration/pull/463
- [ ] https://github.com/nextcloud/social/pull/1481
- [ ] https://github.com/nextcloud/talk_matterbridge/pull/76
- [ ] https://github.com/nextcloud/twofactor_webauthn/pull/262
- [ ] https://github.com/nextcloud/user_oidc/pull/504
- [ ] https://github.com/nextcloud/user_saml/pull/658

**Comment by nickvergessen** [comment]
Sorry I messed up the version number in the "Add Nextcloud … support" for the half of the PRs

**Comment by nickvergessen** [comment]
### Migrate to nextcloud/ocp package

- [ ] https://github.com/nextcloud/activity/pull/935
- [ ] https://github.com/nextcloud/activity/pull/936
- [ ] https://github.com/nextcloud/activity/pull/937
- [ ] https://github.com/nextcloud/activity/pull/938
- [ ] https://github.com/nextcloud/firstrunwizard/pull/743
- [ ] https://github.com/nextcloud/firstrunwizard/pull/745
- [ ] https://github.com/nextcloud/firstrunwizard/pull/746
- [ ] https://github.com/nextcloud/firstrunwizard/pull/747
- [ ] https://github.com/nextcloud/logreader/pull/789
- [ ] https://github.com/nextcloud/logreader/pull/790
- [ ] https://github.com/nextcloud/logreader/pull/791
- [ ] https://github.com/nextcloud/logreader/pull/792
- [ ] https://github.com/nextcloud/nextcloud_announcements/pull/108
- [ ] https://github.com/nextcloud/nextcloud_announcements/pull/109
- [ ] stable24 install failed
- [ ] stable23 install failed
- [ ] https://github.com/nextcloud/notifications/pull/1292
- [ ] https://github.com/nextcloud/notifications/pull/1293
- [ ] https://github.com/nextcloud/notifications/pull/1294
- [ ] stable23 install failed
- [ ] https://github.com/nextcloud/related_resources/pull/60
- [ ] https://github.com/nextcloud/related_resources/pull/61
- [ ] https://github.com/nextcloud/serverinfo/pull/401
- [ ] https://github.com/nextcloud/serverinfo/pull/402
- [ ] https://github.com/nextcloud/serverinfo/pull/403
- [ ] stable23 install failed
- [ ] https://github.com/nextcloud/survey_client/pull/147
- [ ] https://github.com/nextcloud/survey_client/pull/148
- [ ] https://github.com/nextcloud/survey_client/pull/149
- [ ] stable23 install failed
- [ ] https://github.com/nextcloud/text/pull/3059
- [ ] https://github.com/nextcloud/text/pull/3060
- [ ] https://github.com/nextcloud/text/pull/3061
- [ ] https://github.com/nextcloud/text/pull/3062

**Comment by come-nc** [comment]
> ### Migrate to nextcloud/ocp package
Can you open this one on user_migration as well please?

**Comment by nickvergessen** [comment]
Will look into the non packaged apps after the conf so CI is not overloaded

**Comment by nickvergessen** [comment]
Next chunks of apps:


- [ ] https://github.com/nextcloud/files_accesscontrol/pull/273
- [ ] https://github.com/nextcloud/files_accesscontrol/pull/275
- [ ] https://github.com/nextcloud/files_accesscontrol/pull/276
- [ ] https://github.com/nextcloud/files_accesscontrol/pull/277
- [ ] https://github.com/nextcloud/data_request/pull/74
- [ ] https://github.com/nextcloud/data_request/pull/75
- [ ] https://github.com/nextcloud/data_request/pull/76
- [ ] https://github.com/nextcloud/deck/pull/4091
- [ ] https://github.com/nextcloud/deck/pull/4092
- [ ] https://github.com/nextcloud/deck/pull/4093
- [ ] https://github.com/nextcloud/deck/pull/4094
- [ ] https://github.com/nextcloud/end_to_end_encryption/pull/337
- [ ] https://github.com/nextcloud/end_to_end_encryption/pull/338
- [ ] https://github.com/nextcloud/end_to_end_encryption/pull/339
- [ ] https://github.com/nextcloud/external/pull/314
- [ ] https://github.com/nextcloud/external/pull/315
- [ ] https://github.com/nextcloud/files_automatedtagging/pull/602
- [ ] https://github.com/nextcloud/files_automatedtagging/pull/603
- [ ] https://github.com/nextcloud/files_automatedtagging/pull/604
- [ ] https://github.com/nextcloud/files_automatedtagging/pull/605
- [ ] https://github.com/nextcloud/files_retention/pull/203
- [ ] https://github.com/nextcloud/files_retention/pull/204
- [ ] https://github.com/nextcloud/files_retention/pull/205
- [ ] https://github.com/nextcloud/files_retention/pull/206
- [ ] https://github.com/nextcloud/groupfolders/pull/2108
- [ ] https://github.com/nextcloud/groupfolders/pull/2109
- [ ] https://github.com/nextcloud/groupfolders/pull/2110
- [ ] https://github.com/nextcloud/groupfolders/pull/2111
- [ ] https://github.com/nextcloud/impersonate/pull/164
- [ ] https://github.com/nextcloud/impersonate/pull/165
- [ ] https://github.com/nextcloud/impersonate/pull/166
- [ ] https://github.com/nextcloud/impersonate/pull/167
- [ ] https://github.com/nextcloud/ldap_contacts_backend/pull/47
- [ ] https://github.com/nextcloud/ldap_contacts_backend/pull/48
- [ ] https://github.com/nextcloud/profiler/pull/79
- [ ] https://github.com/nextcloud/profiler/pull/80
- [ ] https://github.com/nextcloud/profiler/pull/81
- [ ] https://github.com/nextcloud/richdocuments/pull/2477
- [ ] https://github.com/nextcloud/richdocuments/pull/2478
- [ ] https://github.com/nextcloud/richdocuments/pull/2479
- [ ] https://github.com/nextcloud/richdocuments/pull/2480
- [ ] https://github.com/nextcloud/user_migration/pull/256
- [ ] https://github.com/nextcloud/user_migration/pull/257
- [ ] https://github.com/nextcloud/user_migration/pull/258
- [ ] https://github.com/nextcloud/user_usage_report/pull/116
- [ ] https://github.com/nextcloud/user_usage_report/pull/117
- [ ] https://github.com/nextcloud/user_usage_report/pull/118
- [ ] https://github.com/nextcloud/workflow_script/pull/123
- [ ] https://github.com/nextcloud/workflow_script/pull/124
- [ ] https://github.com/nextcloud/workflow_script/pull/125
- [ ] https://github.com/nextcloud/workflow_script/pull/126

**Comment by nickvergessen** [comment]
Closing as majority is merged
