### ISSUE TITLE
[Bug]: videoplayer is shown twice

### ISSUE THREAD

**Issue by ArtificialOwl** [nextcloud/server#34203]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Public share of a video displays 2 (different) video players (tested on firefox)

![image](https://user-images.githubusercontent.com/1038617/191869585-9e0abef1-e2bb-4c20-9ea3-30e24cfb5976.png)

### Steps to reproduce

1. Share Nextcloud Intro.mp4 using public link
2. Open link in a new tab/window

### Expected behavior

Only one viewer should be displayed

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
basic install from scratch; no cache, nothing.
```

### List of activated Apps

```shell
basic install from scratch; no cache, nothing.
```

**Comment by szaimen** [comment]
Cc @PVince81

**Comment by szaimen** [comment]
I guess removing files_videoplayer from the bundle would already solve this. Also cc @blizzz

**Comment by blizzz** [comment]
disabled it on the instance, added as todo to remove from bundling

**Comment by ArtificialOwl** [comment]
removed from bundling will disable it on upgrade ?

**Comment by blizzz** [comment]
there should be a repair job added to remove the app cleanly

**Comment by szaimen** [comment]
> there should be a repair job added to remove the app cleanly

Same with the removed acceasibility app?

**Comment by skjnldsv** [comment]
> there should be a repair job added to remove the app cleanly

Hu? It's shipped, so it will just get removed, no?

**Comment by blizzz** [comment]
> Hu? It's shipped, so it will just get removed, no?

Some stuff's in the DB, state, version, etc.

**Comment by blizzz** [comment]
> Same with the removed acceasibility app?

I don't know?

**Comment by blizzz** [comment]
> > there should be a repair job added to remove the app cleanly
> 
> Same with the removed acceasibility app?

Yes, it also has traces.

**Comment by blizzz** [comment]
> Also needs to be removed from shipped.json then...

Don't hurry that old dude, pal! ;)

**Comment by szaimen** [comment]
I think this is fixed with RC3
