### ISSUE TITLE
[Bug]: NC 25 RC1 Unable to update To login you need to provide the unhashed value of "updater.secret" in your config file. 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#34200]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Never seem this before 

https://github.com/nextcloud/updater/issues/228

### Steps to reproduce

1. Click on open updater 
2.
3.

### Expected behavior

Should update

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
NA
```

**Comment by andyxheli** [comment]
Same issue https://github.com/nextcloud/server/issues/34201

**Comment by andyxheli** [comment]
I found a work around cd into your nextcloud updater dir /updater/ mine was 

/var/www/nextcloud/updater/

then run 

sudo -u www-data php updater.phar

**Comment by andyxheli** [comment]
Dup of Same issue https://github.com/nextcloud/server/issues/34201

**Comment by andreybavt** [comment]
@Krautmaster did you manage to solve `Class "Phar" not found` ? I'm getting the same error after an upgrade has failed

**Comment by Krautmaster** [comment]
yeah, goint though my history i think this fixed it:

`sed -i 's/t\.token/t/' dist/updatenotification-updatenotification.js`

but ill try to grab the original thread where i ot it from
