### ISSUE TITLE
Activity not capturing file shared through Next cloud Talk

### ISSUE THREAD

**Issue by agrangaraj** [nextcloud/server#34207]
### Steps to reproduce
1. Share the file in Nexcloud Talk app
2. Activity of sharing the file is not capturing  the chat name from NIWE talk app

### Expected behaviour
When some one share a file from local computer or Next cloud files it should be mention who has downloaded the file in the activity list. Instead it shows as downloaded from public link

### Actual behaviour
The activity should capture who has downloaded the file instead of download from public link

### Server configuration

**Operating system**: Windows, Linux and Android

**Web server:** 

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page) 23.04

**Where did you install Nextcloud from:**

**Signing status:**

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
