### ISSUE TITLE
[Bug]: NC 25 error when trying upgrade from beta 7 to RC1 with GUI

### ISSUE THREAD

**Issue by nicrame** [nextcloud/server#34201]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When i try to upgrade using GUI from 25 beta 7 (25.0.0.11) to 25 RC1 there some strange information appeared asking for password from config file. I did copy & paste the secret, but it didn't work like it would ignore LOGIN button (it didn't show/did anything).

![Zrzut ekranu (754)](https://user-images.githubusercontent.com/5872054/191849765-07c1eb3e-2eab-41f9-b538-d25dd9e7ac5d.png)

Also updating from command line (terminal) did worked well.

### Steps to reproduce

1. Go to setting.
2. Click on update.
3. Error is just appearing.

### Expected behavior

It should just start upgrade page.

### Installation method

Community Manual installation with Archive

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "blacklisted_files": [],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "127.0.0.1",
            "172.25.8.11",
            "love",
            "itos-cloud",
            "192.168.zzz.2",
            "192.168.zzz.5",
            "zzz-NAS",
            "192.168.zzz.2",
            "my.domain.com",
            "zzz.127.zzz.207",
            "192.168.zzz.1"
        ],
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Image",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\SVG",
            "OC\\Preview\\Font",
            "OC\\Preview\\MP3",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI",
            "OC\\Preview\\PNG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\BMP"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.0.13",
        "overwrite.cli.url": "https:\/\/my.domain.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "1c_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "pl",
        "default_locale": "pl",
        "simpleSignUpLink.shown": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 2.5
        },
        "skeletondirectory": "core\/clear-default",
        "maintenance": false,
        "app_install_overwrite": [
            "bruteforcesettings",
            "dicomviewer",
            "files_photospheres",
            "camerarawpreviews",
            "documentserver_community",
            "spreed"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "PL",
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "beta",
        "preview_max_memory": "512",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.0.0-alpha.1
  - camerarawpreviews: 0.8.0
  - circles: 25.0.0-alpha.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.0-alpha.2
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.0-beta.1
  - dicomviewer: 1.2.3
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.0
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_photospheres: 1.24.1
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - files_videoplayer: 1.14.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.0.0-beta.7
  - maps: 0.2.1
  - nextcloud_announcements: 1.14.0
  - notes: 4.5.1
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 1.7.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.0
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.0-rc.1
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - documentserver_community: 0.1.12
  - encryption: 2.9.0
  - extract: 1.3.5
  - forms: 3.0.0-beta.1
  - groupfolders: 13.0.0-beta.1
  - metadata: 0.16.0
  - notify_push: 0.4.0
  - onlyoffice: 7.5.4
  - ransomware_protection: 1.13.0
  - suspicious_login
  - tasks: 0.14.4
  - twofactor_totp
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
There is no any log about this.
```

### Additional info

I'm using RHEL 9, on 64-bit CPU, with 64G RAM.
nginx -v
nginx version: nginx/1.20.1
php81 -v
PHP 8.1.10 (cli) (built: Aug 30 2022 16:09:36) (NTS gcc x86_64)
Copyright (c) The PHP Group
Zend Engine v4.1.10, Copyright (c) Zend Technologies
with Zend OPcache v8.1.10, Copyright (c), by Zend Technologies
mariadb --version
mariadb Ver 15.1 Distrib 10.5.16-MariaDB, for Linux (x86_64) using EditLine wrapper
uname -a
Linux zzz-NAS 5.14.0-70.26.1.el9_0.x86_64 https://github.com/nextcloud/server/issues/1 SMP PREEMPT Fri Sep 2 16:07:40 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by andyxheli** [comment]
I found a work around cd into your nextcloud updater dir /updater/ mine was 

/var/www/nextcloud/updater/

then run 

sudo -u www-data php updater.phar

**Comment by lars-becker** [comment]
Had the same problem. Updated manually via shell.

**Comment by slimshizn** [comment]
Able to move past with these commands.....
``sudo -u abc php updater.phar`` inside of ``/config/www/nextcloud/updater``
Running Docker container on Unraid.
After update in cli, select Y for ``occ upgrade``
After finished select N when asked to keep maintenance mode active.

**Comment by andyxheli** [comment]
Same issue from RC1 to RC2

also reported it here 

https://help.nextcloud.com/t/sixth-beta-of-nextcloud-25/145306/17?u=andyxheli

**Comment by andyxheli** [comment]
Looks like its been fixxed in RC2. Plese see post from below link

**Comment by andyxheli** [comment]
@blizzz im on RC2 going to RC3 and still having this issue. i not you mentioned it should be fixed in RC2

**Comment by blizzz** [comment]
The issue with the forgotten .step file was fixed in RC3. I am actually not sure where this comes from, yet, but it definitely needs a fix. Would recommend the cli update as workaround, or follow the instructions.

**Comment by andyxheli** [comment]
Okay, sounds good. Thanks for the update. We'll do the workaround for now. Until further notice.

**Comment by depesch** [comment]
I't doesn't work via shell, i got this error message:
PHP Fatal error:  Uncaught Error: Call to undefined function NC\Updater\curl_init() in phar:///var/www/vhosts/xxxxx/xxxxxxxxxx/updater/updater.phar/lib/Updater.php:471

Any idea?

**Comment by andyxheli** [comment]
@depesch 

try the following 

I found a work around cd into your nextcloud updater dir /updater/ mine was




cd /var/www/nextcloud/updater/

then run

sudo -u www-data php updater.phar

**Comment by depesch** [comment]
Thanks, but my post is the result when i do exactly this ^^Am 07.10.2022 um 20:03 schrieb Andy Xheli ***@***.***>:﻿
@depesch
try the following
I found a work around cd into your nextcloud updater dir /updater/ mine was
cd /var/www/nextcloud/updater/
then run
sudo -u www-data php updater.phar

**Comment by andyxheli** [comment]
Oh i see sorry about that. Hmmmm try running an 

sudo -u www-data php /var/www/nextcloud/occ check
sudo -u www-data php /var/www/nextcloud/occ upgrade

**Comment by blizzz** [comment]
The fix should come with the next RC.

If you like to give it a try and have sed installed on your server, your may run

```sudo -u www-data sed -i 's/t\.token/t/' dist/updatenotification-updatenotification.js``` 

from within your Nextcloud root directory. Afterwards, with a hard refresh on the admin settings overview page, updater should work again upon clicking "Open Updater".

**Comment by andyxheli** [comment]
@blizzz  this should be fixed once on rc4 correct ?

**Comment by Krautmaster** [comment]
> The issue with the forgotten .step file was fixed in RC3. I am actually not sure where this comes from, yet, but it definitely needs a fix. Would recommend the cli update as workaround, or follow the instructions.

was not fixed with RC3, im on RC3 and get this issue if i try to go to RC5

**Comment by Krautmaster** [comment]
manually searched for ".token" in dist/updatenotification-updatenotification.js and removed it. Webupdater seems to work now
