### ISSUE TITLE
[Bug]: User management broken on "smaller" screens

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#34214]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Depending on your screen size the web interface to edit a user is broken. Seen in Nextcloud 25 RC1

### Steps to reproduce

You can try it by open the user management click on "edit" for one of the existing users and resize the window:

![grafik](https://user-images.githubusercontent.com/1589737/191935234-323b5370-dc71-4a24-a1df-a8984ad09c5f.png)

is I make the window even smaller:

![grafik](https://user-images.githubusercontent.com/1589737/191935355-df25620a-d8e4-4110-8372-702df06d57ad.png)

### Expected behavior

All elements are always allign correctly, independent of the screen size.

As we have a lot of elements in one row I think it would be also fine to stop resizing at some point in time and add a horizontal scrollbar instead. But the interface should always look correct and be functional.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
-
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
