### ISSUE TITLE
[Bug]: Email-links take local IP instead of public domain

### ISSUE THREAD

**Issue by immomagic** [nextcloud/server#34218]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

As described here, the problem is not solved yet.
Please help me... i cant believe that i am the only one with this issue...

Nextcloud 24.0.5 running with a community VM IMAGE installation.

https://github.com/nextcloud/server/issues/33403

### Steps to reproduce

1. Invite a guest, tell him he should try to set a password --> Network error
2. Try to reset your password while not connected to the local network your nextcloud is running --> Button in mail routes to local IP
3.  Share a single file with a link to someone via mail --> Button in Mail routes to local IP

### Expected behavior

The links in the generated emails should all work and take my public domain instead of the local IP.

### Installation method

Community VM appliance

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "portal.immo-magic.de",
            "192.168.77.150",
            "nextcloud",
            "nextcloud.immo-magic.dom",
            "nextcloud.immo-magic.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "24.0.5.1",
        "overwrite.cli.url": "https:\/\/portal.immo-magic.de\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 2,
        "auth.webauthn.enabled": false,
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "mail_smtpmode": "smtp",
        "logtimezone": "Etc\/UTC",
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "skeletondirectory": "",
        "theme": "",
        "updater.release.channel": "stable",
        "htaccess.RewriteBase": "\/",
        "default_language": "de_DE",
        "default_phone_region": "DE",
        "force_language": "de_DE",
        "simpleSignUpLink.shown": false,
        "overwriteprotocol": "https",
        "app_install_overwrite": [
            "email_template_example",
            "files_external_onedrive",
            "files_trackdownloads"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "mail_template_class": "OCA\\EmailTemplateExample\\EMailTemplate"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - cloud_federation_api: 1.7.0
  - dav: 1.22.0
  - email_template_example: 0.0.1
  - external: 4.0.0
  - federatedfilesharing: 1.14.0
  - files: 1.19.0
  - files_accesscontrol: 1.14.1
  - files_downloadactivity: 1.13.0
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - guests: 2.3.0
  - impersonate: 1.11.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - notifications: 2.12.1
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - provisioning_api: 1.14.0
  - settings: 1.6.0
  - side_menu: 2.5.1
  - systemtags: 1.14.0
  - theming: 1.15.0
  - theming_customcss: 1.12.0
  - twofactor_backupcodes: 1.13.0
  - unroundedcorners: 1.0.3
  - updatenotification: 1.14.0
  - viewer: 1.8.0
  - workflowengine: 2.6.0
Disabled:
  - accessibility: 1.8.0
  - announcementcenter: 6.3.1
  - circles: 24.0.0
  - comments: 1.12.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.2.0
  - encryption
  - federation: 1.12.0
  - files_fulltextsearch: 24.0.1
  - files_fulltextsearch_tesseract: 24.0.0
  - files_trackdownloads: 1.11.0
  - files_trashbin: 1.12.0
  - firstrunwizard: 2.11.0
  - fulltextsearch: 23.0.0
  - nextcloud_announcements: 1.11.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - recommendations: 1.1.0
  - serverinfo: 1.14.0
  - sharebymail: 1.12.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - text: 3.5.1
  - user_ldap
  - user_status: 1.2.0
  - weather_status: 1.2.0
```

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by Oink70** [comment]
This happens after upgrading to the latest major upgrade. It seems to be an upgrade issue not processing/modifying the required data during the process.
Please reopen and fix.
