### ISSUE TITLE
[Bug]: The trusted-domains URL Documentation not working on NextCloud 25

### ISSUE THREAD

**Issue by pablolucas890** [nextcloud/server#34224]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I'm start server in a different domain, the untrustedDomain message open to me, the message are ok, but the documentation link isn't working

I check old versions changing the version name on url and olds versions working, but the version 25 opem a error on web (File not found.)

![image](https://user-images.githubusercontent.com/56566628/191975003-46eeb93e-12dd-4312-9a6c-c982af1bfa83.png)
![image](https://user-images.githubusercontent.com/56566628/191975129-101489ce-732b-441f-8be6-e7b621f3f6c9.png)

### Steps to reproduce

1 - Use nextcloud 25
2 - start server in a other domain (for example ```php -S 192.168.68.121:3333```)
3 - click on documentation link
4 - documentation not working

### Expected behavior

The url works

### Operating system

Debian/Ubuntu

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
- amoradev: 0.0.1
  - calendar: 4.0.0-alpha.1
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.0-alpha.2
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - lookup_server_connector: 1.13.0
  - mail: 2.0.0-beta.6
  - oauth2: 1.13.0
  - procedure: 0.0.1
  - provisioning_api: 1.15.0
  - richdocuments: 7.0.0-beta.1
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.0-beta.4
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: true
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - testing
  - user_ldap
```

**Comment by szaimen** [comment]
Can you post your config.php content?

**Comment by kesselb** [comment]
Thanks for your report :+1: 

Documentation is available again.
