### ISSUE TITLE
[Bug]: APCu not compatible with cron 

### ISSUE THREAD

**Issue by avibrazil** [nextcloud/server#34238]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If the following line is added to `config.php`:

`'memcache.local' => '\\OC\\Memcache\\APCu'`

Then cron fails with following error:

`OCP\HintException: [0]: Memcache \OC\Memcache\APCu not available for local cache (Is the matching PHP module installed and enabled?)`

But enabling APCu seems to improve overall performance and I want to use it.

### Steps to reproduce

Enable APCu and try to run cron.php

### Expected behavior

Expected to have cron run successfully even with APCu enabled.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "version": "24.0.5.1",
        "dbtype": "mysql",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "pipe",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updatechecker": false,
        "check_for_working_htaccess": true,
        "asset-pipeline.enabled": false,
        "trusted_domains": [
            "newengland.local",
            "newengland.homeavi.alkalay.net",
            "homeavi.alkalay.net",
            "homeavi.nsupdate.info"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "assetdirectory": "\/var\/lib\/nextcloud",
        "htaccess.RewriteBase": "\/nextcloud",
        "overwrite.cli.url": "https:\/\/newengland.local\/nextcloud",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "apps_paths": [
            {
                "path": "\/usr\/share\/nextcloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/lib\/nextcloud\/apps",
                "url": "\/apps-appstore",
                "writable": true
            }
        ],
        "log_type": "syslog",
        "syslog_tag": "Nextcloud",
        "logfile": "",
        "loglevel": 3,
        "theme": "",
        "ncd_admin_settings": {
            "ncd_aria2_binary": "\/usr\/bin\/aria2c",
            "ncd_yt_binary": "\/usr\/bin\/youtube-dl"
        }
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.16.0
  - bookmarks: 11.0.2
  - bruteforcesettings: 2.4.0
  - cfg_share_links: 2.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_external: 1.16.1
  - files_markdown: 2.3.6
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - groupfolders: 12.0.1
  - impersonate: 1.11.0
  - integration_github: 1.0.4
  - libresign: 5.1.4
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - maps: 0.2.1
  - metadata: 0.16.0
  - music: 1.6.0
  - ncdownloader: 1.0.1
  - news: 18.1.1
  - notifications: 2.12.1
  - oauth2: 1.12.0
  - photos: 1.6.0
  - provisioning_api: 1.14.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - accessibility: 1.10.0
  - admin_audit
  - circles: 24.0.1
  - contactsinteraction: 1.5.0
  - encryption
  - nextcloud_announcements: 1.11.0
  - password_policy: 1.14.0
  - privacy: 1.8.0
  - recommendations: 1.3.0
  - sharebymail: 1.14.0
  - support: 1.5.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - updatenotification: 1.14.0
  - user_ldap
```

### Additional info

a

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by avibrazil** [comment]
I don't think this is a setup issue.

Nextcloud recommends using APCu and it indeed improves performance. But then cron doesn't run because of some internal incompatibility in the code.

**Comment by j-ed** [comment]
You're description is missing important information about your enviornment, especially the PHP configuration (`php -m`). As stated in the error message the APCu module cannot be found, so you should make sure that it has correctly been installed and configured otherwise it won't be possible to use it.

**Comment by joshtrichards** [comment]
@avibrazil https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html?highlight=enable_cli#cron

> For some configurations, it might be necessary to append --define apc.enable_cli=1 to the cron command. Please refer to [Memory caching](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/caching_configuration.html) (section APCu).
