### ISSUE TITLE
[Bug]: Uploading Theme Login Image inexplicably increases image size significantly

### ISSUE THREAD

**Issue by daniel-keller** [nextcloud/server#34233]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Through Settings > Theming I uploaded an jpg as the login background. 

The Image I uploaded was 1079x609 and 47KB in size (I used an unrealistically small image for this example). After the upload completed I logged out and refreshed the login page to find that the correct image is appearing with the same dimensions for the background image but its now 23x larger in size (1.1MB). I tried again with a larger image of 2k at 200KB (what I would consider a realistic size for a background image) and the resulting image to download is 3.4MB which can take up to 30+ seconds to load on slower mobile networks (I aim for my background image to be 100KB-300KB depending on content).

I cleared any browser caching and server caching (I use redis) to ensure the correct image is being delivered but I get the same result.

I could see Nextcloud modifying the image to optimize it after upload but I don't understand why the image size should increase so dramatically (especially without any perceivable difference in the final background image).

<img width="1509" alt="Screen Shot 2022-09-23 at 9 10 04 PM" src="https://user-images.githubusercontent.com/4036797/192074230-00c15de8-8943-43d4-b643-ce44951e24f6.png">

I'm using Nextcloud in the official docker container on Unraid 6.11.0 (Linux 5.19.9-Unraid x86_64)
The browser I am using is Chrome.

### Steps to reproduce

1. Go to Settings > Theming > Login image and upload a ~200kb jpg 
2. After upload saves view the either the preview image in dev tools or logout and view the login background in dev tools
3. See that while the image is the correct image the file size is significantly larger (~3MB) than what was uploaded.

### Expected behavior

I expect the theming login image to remain the same size or at least be smaller (if nextcloud optimizes the image after upload).

### Installation method

Community Docker image

### Operating system

Other

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

PostgreSQL

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "default_phone_region": "us",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "filesystem_check_changes": 1,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "24.0.3.2",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "5432",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "app_install_overwrite": [
            "documentserver_community"
        ],
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - bruteforcesettings: 2.4.0
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - onlyoffice: 7.5.4
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - documentserver_community: 0.1.12
  - encryption
  - federation: 1.14.0
  - files_external
  - firstrunwizard: 2.13.0
  - user_ldap
```

### Additional info

I'm using Nextcloud in the official docker container on Unraid 6.11.0 (Linux 5.19.9-Unraid x86_64)
The browser I am using is Chrome.

**Comment by HeyBanditoz** [comment]
Confirming this with Nextcloud 25.0.1 and PHP 7.4.33.

In my case, it converted a ~1MB JPEG to a ~10MB PNG file.

My workaround is to directly browse to the directory which contains the background (for me, it's in `/nextcloud/data/appdata_aaaaaaaa/theming/global/images/`) and directly copy your file there, naming it `background`.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by daniel-keller** [comment]
I upgraded to 25.0.3 last night and I was able to replicate the bug. Uploading a 500KB jpeg background image resulted in a  background image being used. A good rule of thumb for background images is 500KB or less (ideally 200-300KB) in size to create a fast experience for first time visits. I see that the background image is no longer converted to a png in the latest build which is some progress in the right direction (converting to .webp file would be a nice touch but you lose support for  old versions of Edge).

**Comment by szaimen** [comment]
How mich bigger did it become?

**Comment by daniel-keller** [comment]
oops, I don't know how that was cut out. 
500KB -> 9.4MB

**Comment by skjnldsv** [comment]
closing in favour of https://github.com/nextcloud/server/issues/32779
