### ISSUE TITLE
[Bug]: Broken link 

### ISSUE THREAD

**Issue by sakshi2207** [nextcloud/server#34242]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The documentation link provided here https://docs.nextcloud.com/  are not working for the developer manual and user manual nor for the download link. 
![Uploading Screenshot 2022-09-25 at 8.31.32 PM.png…]()

### Steps to reproduce

Open the https://docs.nextcloud.com/ 
Click on the developer manual or User Manual

### Expected behavior

Need to show the required file 

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
NA
```

**Comment by kesselb** [comment]
Thanks for your report :+1: 

Documentation is available again.
