### ISSUE TITLE
[Bug]: Sort by modification date is wrong

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#34252]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Sorting is wrong.

### Steps to reproduce

1. use techpreview, user christine
2. sort by modification date

![image](https://user-images.githubusercontent.com/5836855/192246342-de8ef8d4-b758-4458-ab0a-f3e4f676d02c.png)

### Expected behavior

Correct sorting.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
/
```

**Comment by skjnldsv** [comment]
The sorting is correct, the favourite icon is missing
