### ISSUE TITLE
Merge contact search into default menubar search

### ISSUE THREAD

**Issue by meichthys** [nextcloud/server#34264]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

![image](https://user-images.githubusercontent.com/10717998/192321618-bcf992d7-5755-494f-9891-a8074f6ba7e7.png)

**Description**
Currently the default search and the contacts search in the menubar seem to duplicate functionality. Perhaps there are more differences, but the primary difference between the contacts search and the default search seems to be limited to:
- The contacts search shows nextcloud users in addition to address book contacts, while the default search only shows contacts in address books?
- The contacts search gives an additional option to compose email from the search (perhaps this could be added to the default search?)

**Describe the solution you'd like**
It seems like we should be able to merge the contact search into the default search since they serve mostly the same purpose.

**Comment by joshtrichards** [comment]
Let's consolidate this into #42386
