### ISSUE TITLE
Auto server Cluster 

### ISSUE THREAD

**Issue by Andreas-Kainz** [nextcloud/server#34265]
## Idea
The idea is that you can connect different NextCloud servers together to a cluster. As simple as you connect as user to the NextCloud server.

## Proposal
When you setup NextCloud server the admin was asked for the url of other NextCloud instance. When add an url the new installation get all the settings.

## Idea come from
WLAN mash.

## Goal
I have more servers and if one is offline, no worry. Would work great with small hardware devices.

**Comment by szaimen** [comment]
This is a good idea in general but unfortunately very much out of scope.
cc @nextcloud/server-triage
