### ISSUE TITLE
How to modify the forgot password link on the login interface?

### ISSUE THREAD

**Issue by liugang926** [nextcloud/server#34273]
I don't need the Forgot Password service for the default login screen, I need to modify it to point to the link I need. My project account authentication uses LDAP to connect to Active Directory, and I implemented the Web function for the service forgot password. Can you tell me what code should I modify?

**Comment by szaimen** [comment]
Please ask your question on https://help.nextcloud.com. thanks!

**Comment by liugang926** [comment]
> [请在https://help.nextcloud.com](https://help.nextcloud.com)上提问。谢谢！

Thank you for your reply.
