### ISSUE TITLE
[Bug]: copying internal links does not work (error: "cannot copy, please copy the link manually")

### ISSUE THREAD

**Issue by vaneslie** [nextcloud/server#34281]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

[Nextcloud 25] Copying internal links in Nextcloud Files does not work with Chrome or Safari on Mac OS. I tried it with a few different files (.ods, .md). If you click on the copy button, nothing happens. If you hover with your cursor over it, it will show "Cannot copy, please copy the link manually".

![Screenshot-2022-09-27-at-10 34 16](https://user-images.githubusercontent.com/17193903/192478671-e84f34b2-8292-4980-8cf1-e69187de0a4a.png)

### Steps to reproduce

1. Click on the "Internal link" icon in the sidebar of a file you want to share.
2. The link is not copied, if you hover of it with your cursor it shows "Cannot copy, please copy the link manually"

### Expected behavior

The internal link will be copied and can be pasted.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
cloud.nc.com / not sure
```

### Additional info

Using Google Chrome 105.0.5195.125 (Official Build) (arm64) on macOS Monterey 12.6 or Safari Version 16.0 (17614.1.25.9.10, 17614).

Console output:

SharingEntryInternal.vue:94 TypeError: Cannot read properties of undefined (reading '$el')
    at SharingEntryInternal.vue:88:1
    at u (runtime.js:63:40)
    at Generator._invoke (runtime.js:294:22)
    at Generator.next (runtime.js:119:21)
    at q (SharingEntrySimple.vue?cb12:20:33)
    at s (SharingEntryInternal.vue:84:1)
(anonymous) @ SharingEntryInternal.vue:94
u @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
q @ SharingEntrySimple.vue?cb12:20
s @ SharingEntryInternal.vue:84
Promise.then (async)
q @ SharingEntrySimple.vue?cb12:20
s @ SharingEntryInternal.vue:84
(anonymous) @ SharingEntryInternal.vue:84
(anonymous) @ SharingEntryInternal.vue:84
copyLink @ SharingEntryInternal.vue:84
click @ SharingEntryInternal.vue?vue&type=template&id=b5df6444&scoped=true&:1
click @ NcActions.js:2
Ct @ vue.runtime.esm.js:2987
n @ vue.runtime.esm.js:1785
Pa.r._wrapper @ vue.runtime.esm.js:7428

**Comment by MariusQuabeck** [comment]
can partly confirm, using Safari 16.1 (18614.2.6.1.1) on Ventura, I do get the "could not copy" message but it **DOES** put the internal link into my clipboard.

**Comment by nickvergessen** [comment]
Could be related to https://github.com/nextcloud/nextcloud-vue/issues/3275#issuecomment-1253436933

**Comment by PVince81** [comment]
the error is valid, there's no `copyButton` in that Vue component for the internal link

there is one for the public link though

I'll have a look for a quick fix

**Comment by binford6000** [comment]
For me it works, too. Getting the same error like @PVince81:
`TypeError: e.$refs.copyButton is undefined
    n SharingEntryInternal.vue:88
    u runtime.js:286
    _invoke runtime.js:262
    F runtime.js:83
    q SharingEntrySimple.vue:20
    s SharingEntryInternal.vue:84
    promise callback*q SharingEntrySimple.vue:20
    s SharingEntryInternal.vue:84
    copyLink SharingEntryInternal.vue:84
    copyLink SharingEntryInternal.vue:84
    copyLink SharingEntryInternal.vue:84
    click SharingEntryInternal.vue:1
    click NcActions.js:2
    VueJS 3` 
Using FireFox 105.0.1 on MacOS

**Comment by PVince81** [comment]
there's a strange issue here: the ref is defined on the link https://github.com/nextcloud/server/blob/master/apps/files_sharing/src/components/SharingEntryInternal.vue#L11, however when I inspect all objects (with breakpoint in `copyLink`) this one never appears in any of the `$refs`.

this is why it fails on https://github.com/nextcloud/server/blob/master/apps/files_sharing/src/components/SharingEntryInternal.vue#L88

**Comment by PVince81** [comment]
seems to be caused by changes in NcActions in nextcloud-vue 6.x+ where the sub-components get rendered through render functions, which I read somewhere don't forward the "ref" (or cannot use refs)

workaround is to set the ref on the NcActions component

PR incoming

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/server/pull/34288

**Comment by timur-g** [comment]
Regarding the previous message, that the issue is back it may be https://github.com/nextcloud/server/issues/36582.
