### ISSUE TITLE
[Bug]: used space disk : dot or comma ?

### ISSUE THREAD

**Issue by jgachelin** [nextcloud/server#34284]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello,
It is a small issue, which is not very disturbing, but still an issue : on Nextcloud (v24.0.5 - French UI - PHP 8.0), by default, the use of disk space indicated on the bottom left of the interface is show with a dot : 205.2 Mo.

When I delete a file, the amount, the use of disk space refresh and it is now a comma : 204,5 Mo.

### Steps to reproduce

1. Show use of disk space
2. Delete a file
3. Show use of disk space

### Expected behavior

Same display (dot) at any time.

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MySQL

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Don't have the access of CLI right now, that seems not really necessary for this issue, but I will update with the list if needed.
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by jgachelin** [comment]
Hello,

Now with Nextcloud 25.0.3 : the bug is still present.

**Comment by joshtrichards** [comment]
This is fixed in >=v26 (although in slightly differently ways) and has been for quite awhile though.
