### ISSUE TITLE
[Bug]: Refused to connect to 'http://nextcloud.example.com/lostpassword/set/token/a.thakur' because it violates the following Content Security Policy directive: "connect-src 'self'".

### ISSUE THREAD

**Issue by proavinashthakur** [nextcloud/server#34280]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Our nextcloud is working all perfect except "Password Reset" API.

Every API is redirecting to HTTPS properly except password reset API, not sure why.

We are using AWS EKS and installed nextcloud stable release with HELM https://github.com/nextcloud/helm 

When I insert password and hit "Reset Password" it shows "Network Error" and getting error in console as below:

`xhr.js:210 Refused to connect to 'http://nextcloud.dasnuve.com/lostpassword/set/token/a.thakur' because it violates the following Content Security Policy directive: "connect-src 'self'".
`

![Uploading Screenshot 2022-09-27 at 1.25.05 PM.png…]()

### Steps to reproduce

1. Try to reset password or invite an user without password to join the cloud
2. Click on "Reset Password" in email we get
3. Enter password and click "Reset Password"
4. Getting "Network Error"

### Expected behavior

It should reset the password

### Operating system

Linux 5.4.209-116.363.amzn2.x86_64 x86_64

### PHP engine version

Version: 8.0.23

### Web server

Nginx

### Database engine version

 Type: mysql
Version: 5.7.37 

### Is this bug present after an update or on a fresh install?

Fresh install

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
I don't have any issue with apps.
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
I removed the nextcloud.log and tried to change the password using "Reset Password" email. It failed with the CSP error stated in description and attached a screenshot above but nothing logged in data/nextcloud.log file.
```

### Additional info

Again, I am using AWS EKS and deployed nextcloud using https://github.com/nextcloud/helm with stable release, everything is working perfect except Password Reset API. It is getting CSP error. All of the APIs are automatically redirecting to HTTPS but password reset API is using http.

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by proavinashthakur** [comment]
@szaimen 

Everything is working except one API, does this seem setup issue?
