### ISSUE TITLE
Fix flaws in encryption module

### ISSUE THREAD

**Issue by rugk** [nextcloud/server#343]
This blog post is a bit older, but it explains why the encrypted used in OwnCloud is somehow flawed:
https://blog.hboeck.de/archives/880-Pwncloud-bad-crypto-in-the-Owncloud-encryption-module.html

I wonder whether there is any plan to change this crypto module and address these concerns in Nextcloud.

**Comment by MorrisJobke** [comment]
@LukasReschke Didn't you implemented something to address some points of this?

**Comment by LukasReschke** [comment]
Reading that article helps: 

> I reported this to Owncloud via Hacker One in January. The first fix they proposed was a change where they used Counter-Mode (CTR) in combination with HMAC. They still encrypt the file in blocks of 8192 bytes size. While this is certainly less problematic than the original construction it still had an obvious problem: All the 8192 bytes sized file blocks where encrypted the same way. Therefore an attacker can swap or remove chunks of a file. The encryption is still malleable.
>
> The second fix then included a counter of the file and also avoided attacks where an attacker can go back to an earlier version of a file. This solution is shipped in Owncloud 9.0, which has recently been released.

**Comment by go2sh** [comment]
It's very sad, that PHP hast no GCM support yet...

**Comment by rugk** [comment]
Continuing reading would also be good... :wink: 

> You may wonder at this point why they didn't switch to an authenticated encryption mode like GCM. The reason for that is that PHP doesn't support any authenticated encryption modes. There is a proposal and most likely support for authenticated encryption will land in PHP 7.1.

So this would be something you can implement - when PHP 7.1 is released.

However I admit I only read the article after I posted the link here. :pensive:

**Comment by rugk** [comment]
However you might also be able to implement it right now using [libsodium](https://download.libsodium.org/libsodium/content/secret-key_cryptography/aes-256-gcm.html) and the [libsodium PHP wrapper](https://github.com/jedisct1/libsodium-php). Or you could even use [ChaCha20-Poly1305](https://download.libsodium.org/libsodium/content/secret-key_cryptography/chacha20-poly1305.html), which is also a symmetric encryption.
Libsodium also has more cryptographic features, for secure password hashing, random number generation and even using the [memory securly](https://download.libsodium.org/libsodium/content/helpers/memory_management.html).

**Comment by rugk** [comment]
Could you reopen this issue? I already adjusted the title.

Using libsodium if installed can provide a significant security advantage compared to "plain PHP" implementations.

**Comment by rugk** [comment]
FYI Libsodium will [be included](http://news.php.net/php.internals/98281) in PHP 7.20 by default, so you can make use of it…

**Comment by MorrisJobke** [comment]
> FYI Libsodium will be included in PHP 7.20 by default, so you can make use of it…

Yes - in 5 years 😞

**Comment by rugk** [comment]
No, users can already install it by themself and use it in earlier versions of PHP. And some hosters have Libsodium pre-installed, so it is a good idea to implement it now…

**Comment by rugk** [comment]
Now, there is even a [pure PHP polyfill](https://github.com/paragonie/sodium_compat) by @paragonie-scott for sodium, so you have no excuse for not using it, anymore.
