### ISSUE TITLE
[Bug]: Update 23.0.9 - Onlyoffice DataBaseError

### ISSUE THREAD

**Issue by JWHBerlin** [nextcloud/server#34303]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Update to 23.0.9, Error Message: 

Aktualisierung auf 23.0.9

Exception: Database error when running migration latest for app onlyoffice
Detaillierte Protokollmeldungen

Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: Not a mysql database -> nothing to do

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Datenbank aktualisiert

Exception: Database error when running migration latest for app onlyoffice

Is there any idea, what we can do to solve the problem?

### Steps to reproduce

1. Start Web Updater
2. Running Web Updater
3. Start DB-Updater

### Expected behavior

Updating successful

### Installation method

Community Web installer on a VPS or web space

### Operating system

RHEL/CentOS

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
No console
```

### List of activated Apps

```shell
OnlyOffice
Accessibility
Activity
Admin_Audit
bruteforcesettings
circles
dashboard
encryption
ouath2
```

### Nextcloud Signing status

```shell
Exception: Database error when running migration latest for app onlyoffice
```

### Nextcloud Logs

```shell
{"reqId":"XXXXXX","level":3,"time":"2022-09-28T09:43:21+00:00","remoteAddr":"84.158.131.93","user":"--","app":"updater","method":"GET","url":"/core/ajax/update.php?requesttoken=XXXXXXX","message":"\\OC\\Updater::updateEnd: Update failed","userAgent":"Mozilla/X.X (Macintosh; XXXXXX OS X XX.XX; rv:XXX.X) Gecko/20100101 Firefox/XXX.X","version":"23.0.9.1","data":{"app":"updater"}}
```

### Additional info

None

**Comment by szaimen** [comment]
Hi, please report thid to https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues. Thanks!
