### ISSUE TITLE
Footer height in public view too small if imprint/privacy link set

### ISSUE THREAD

**Issue by Chartman123** [nextcloud/server#34305]
Currently the footer-height is set to 65px:

https://github.com/nextcloud/server/blob/b739dd580743aa3c339eba28c45f14d930956135/core/css/public.scss#L1

This is too small if the imprint/privacy links are set in the settings of the instance and text gets cut off. (see https://github.com/nextcloud/forms/issues/1337)

If links are set a better value would be 95px.

**Comment by Chartman123** [comment]
Also here in css:

https://github.com/nextcloud/server/blob/b739dd580743aa3c339eba28c45f14d930956135/core/css/public.css#L56

**Comment by suselunarwolf** [comment]
HI,I'm willing to work on it.

**Comment by RyanAveritt** [comment]
@suselunarwolf are you still working on this issue?

**Comment by RyanAveritt** [comment]
@Chartman123 would this be a dynamic change only changing when there are links set in the settings that affect the footer?

**Comment by Chartman123** [comment]
@jancborchardt what do you think? Should the footer height be dynamically adjusted if one of the links is set?

**Comment by RyanAveritt** [comment]
Also, I am a bit lost on testing it myself if we do want it dynamically adjusted; should I go to the forums for advice or may I ask here? (I have the dev environment for forms cloned but am unsure how to add links to the footer)

**Comment by Chartman123** [comment]
@RyanAveritt it's not only Forms related, but you can of course check it there. You have to go to the Settings of your Nextcloud instance and then to the Theming settings... There you can set the links :)

**Comment by RyanAveritt** [comment]
<img width="1207" alt="Screen Shot 2022-10-02 at 7 36 52 AM" src="https://user-images.githubusercontent.com/73580201/193451959-94a82cc0-9ab2-4294-aab7-3170f9b4a47f.png">

Maybe because of my setup but I now can test it if the decision is made to go dynamic; if we do go dynamic, do you have any tips on where to listen for the "event" and changing the size (Sorry if this is asking a lot; first-time contributor)?

Also, thank you for the feedback @Chartman123.

**Comment by RyanAveritt** [comment]
Does omitting the height in body-public footer for core/css/server.css fix it? 
See https://github.com/nextcloud/server/blob/754cef369b694c5a58f006ceafe7e9a943c7770f/core/css/server.css#L5005

**Comment by SakshiT25** [comment]
Hi, I would like to work on this issue if it is still open.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by Chartman123** [comment]
![image](https://user-images.githubusercontent.com/16020496/214084988-5606f7cd-dce6-4ff6-8af7-76411aa973f5.png)

@szaimen Still valid on 25.0.3

**Comment by ShayanFaghihi** [comment]
Hi guys. Is the issue still there? I can contribute if needed

**Comment by RyanAveritt** [comment]
> Hi guys. Is the issue still there? I can contribute if needed

I apologize for the delay in addressing the issue; things have been a bit busy on my end. If you're able to lend a hand, your contribution would be greatly appreciated as the issue should still exist.

**Comment by ShayanFaghihi** [comment]
> > Hi guys. Is the issue still there? I can contribute if needed
> 
> I apologize for the delay in addressing the issue; things have been a bit busy on my end. If you're able to lend a hand, your contribution would be greatly appreciated as the issue should still exist.

No worries, my pleasure. I've read the contribution document, but nothing found about the branch naming. Do you have any standard for naming the branches? Thanks

**Comment by joshtrichards** [comment]
@ShayanFaghihi Name your branch whatever you like in your own tree. Submit PRs against `master`.
