### ISSUE TITLE
Burger Menu Button inside of sidebar

### ISSUE THREAD

**Issue by andreas-traexler** [nextcloud/server#34304]
I do not know if this has already been asked, but I think it would make more sense to incorporate the burger button within the sidebar, as it looks kind of strange, if content overlaps with it.

I would suggest to make the sidebar collapsible then, with "reduced" menu entries, as e.g. Twitch or Gmail handles it.
![image](https://user-images.githubusercontent.com/33902715/192765641-612fb5f4-0e54-45ce-b6ad-0f68e0ed0fd7.png)

Example for collapsible menu:
![image](https://user-images.githubusercontent.com/33902715/192765750-ae5961dc-1332-4227-8365-cef56f22883c.png)

Would that be something that is viable?

BR

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/groupware/issues/2
