### ISSUE TITLE
FR: Passwords App NAME field - [website.url - username] 

### ISSUE THREAD

**Issue by DetroitLibertyPenguin** [nextcloud/server#34314]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
For many websites I have multiple usernames. Unless I have edited the saved Password manually they all have the same name (i.e. 5 passwords saved as GOOGLE.COM) and selecting which one, such as from the Chrome add-on, becomes a guessing game where i keep selecting until I find the one that works. Particularly bad for sites that lock you out for a time for too many wrong attempts. 

**Describe the solution you'd like**
Default name, such as initial import from another app (mine all came from LastPass) to include website.url - username rather than just website.url [I think LastPass just stores the website.url as the default name, but there UX shows on top level NAME - USERNAME] 

**Describe alternatives you've considered**
I've started editing saved Passwords to rename it to NAME - USERNAME as I would expect the default to be (or if not default, perhaps an option?] and/or adding FAVORITE STAR to the one I use more often (i.e. mine rather than my wife's) 

**Additional context**
![image](https://user-images.githubusercontent.com/65328167/192846658-7e3f0f0b-b120-4a2b-8491-0b7ac3d6c4e7.png)

**Comment by kesselb** [comment]
Hi, thanks for your report :+1: 

The repository for the passwords app is here: https://git.mdns.eu/nextcloud/passwords
