### ISSUE TITLE
[Bug]: occ upgrade breaks repairsteps when info.xml holds one single entry for dependencies/database

### ISSUE THREAD

**Issue by tonyguepin** [nextcloud/server#34360]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When info.xml holds one single entry for dependencies/database like so;
```
    <dependencies>
      <nextcloud min-version="18" max-version="23" />
      <database>mysql</database>
    </dependencies>
```

Then during php occ upgrade, the migrationservice breaks on an invalid array reference;
```
./lib/private/DB/MigrationService.php:98
foreach ($info['dependencies']['database'] as $database) {
```
This only is reported in the logfile, the commandline occ command reports no error, but subsequent repairsteps are not executed.

A workaround is to make sure, more that one database entry is present;
```
    <dependencies>
      <nextcloud min-version="18" max-version="23" />
      <database>sqllite</database>
      <database>mysql</database>
    </dependencies>
```
This way, the reference to $info['dependencies']['database'] is always an array.

nextcloud version: 23.0.0.10  
but code has not been repaired yet im later versions (as far as I can see)

### Steps to reproduce

1. for some app, specify a single database entry;
```
   <dependencies>
      <nextcloud min-version="18" max-version="23" />
      <database>mysql</database>
    </dependencies>
```
2. change the app version number
3. php occ upgrade
4. check logfile (maybe raise your php error level first)

### Expected behavior

A single entry for dependencies/database as described in the development documentation;  
https://docs.nextcloud.com/server/23/developer_manual/app_development/info.html  
under dependencies/database

### Installation method

Other Community project

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MySQL

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
none here
```

### List of activated Apps

```shell
none here
```

### Nextcloud Signing status

```shell
none here
```

### Nextcloud Logs

```shell
none here
```

### Additional info

none here

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
