### ISSUE TITLE
Fix descriptions at private/Setup/AbstractDatabase.php

### ISSUE THREAD

**Issue by KB7777** [nextcloud/server#3437]
There are sentences which doesn't make sens even in english :) (c) @nickvergessen 

%s enter the database username and name.
https://www.transifex.com/nextcloud/nextcloud/translate/#pl/lib/91001924

%s enter the database username.
https://www.transifex.com/nextcloud/nextcloud/translate/#pl/lib/91001909

%s enter the database name.
https://www.transifex.com/nextcloud/nextcloud/translate/#pl/lib/91001974

%s you may not use dots in the database name
https://www.transifex.com/nextcloud/nextcloud/translate/#pl/lib/91001886

**Comment by MorrisJobke** [comment]
@MariusBluem @rullzer @nickvergessen Any ideas how to improve them? (%s is the DB pretty name - something like MySQL).

**Comment by rullzer** [comment]
Well first of all we should probably not use `%s` as it adds no context. Something like:

`%dbtype: enter the name of the database and a username to connect to it`

`%dbtype: enter a username to connect to the database`

`%dbtype: enter the name of the database to connect to`

`%dbtype: you may not use dots in the database name`

**Comment by nickvergessen** [comment]
>Something like:
%dbtype: enter the name of the database and a username to connect to it

Please, no! `%s` is sprintf logic.
If we use something else anyway, I'd go with `{dbtype}` which we already use and support in JS.

**Comment by szaimen** [comment]
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!
