### ISSUE TITLE
Add email server functionality in Nextcloud server

### ISSUE THREAD

**Issue by hacknorris-code** [nextcloud/server#34397]
**Is your feature request related to a problem? Please describe.**
right now nextcould email tab only supports importing messages from other platforms (like gmail)

**Describe the solution you'd like**
possibility for mods to easily enable email server connected automatically to mail tab (nextcloud A I O solution like google/apple/microsoft apps)

**Comment by szaimen** [comment]
> This would IMO be better handled as part of one of the downstream appliances (e.g. AIO or some specialized one)

Yes, agreed. See https://github.com/nextcloud/all-in-one/discussions/356 for example.

**Comment by szaimen** [comment]
See https://github.com/nextcloud/all-in-one/discussions/356#discussioncomment-7778035
