### ISSUE TITLE
[Bug]: Public view footer broken

### ISSUE THREAD

**Issue by mejo-** [nextcloud/server#34399]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On latest master (26), public view footer is broken du to #34331.

1. the removed `position: sticky` property from `<footer>`, results in the footer being displayed on the top of the page.
2. The `- 65px` is not enough because `<footer>` actually takes 65px height plus 2x 8px padding on top and bottom. So this should probably be `65px + 8px + 8px` = `81px`.

@szaimen because you tried to fix public view footer in #34331.

### Steps to reproduce

1. Open a document in public share
2. Watch the footer being broken
3. Add `position: sticky` back to `footer` CSS
4. Watch the footer overlapping long content

### Expected behavior

Footer should be at the bottom and not overlap long content.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Unrelated
```

**Comment by szaimen** [comment]
There is already a PR in https://github.com/nextcloud/server/pull/34396

**Comment by mejo-** [comment]
> There is already a PR in #34396

Thanks for the pointer! But the PR seems to only address the first part of this report :)

**Comment by mejo-** [comment]
Thanks, #34396 indeed fixes the stickyness of the footer. But as written, there's an additional problem. The footer overlaps `#app-content-vue`, which results in invisible and unaccessible content at the bottom of the page. So either reduce height of `#app-content-vue` by `81px` (`$footer-height` + 2x `8px` margin), or add a a `padding-bottom: 81px` to `#app-content-vue`.

Screenshot:

![grafik](https://user-images.githubusercontent.com/3582805/193679091-7b840cc9-89c1-45ea-a0a1-66aa8b25eeed.png)

**Comment by szaimen** [comment]
Can you create a PR for this? Not sure how to solve it...
