### ISSUE TITLE
[Bug]: Crash when share a file inside viewer app

### ISSUE THREAD

**Issue by vinicius73** [nextcloud/server#34404]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The page stop to respond when we open sidebar/sharing options while any view handler is open.
The cause is related here https://github.com/nextcloud/nextcloud-vue/issues/3154

Related to: https://github.com/nextcloud/nextcloud-vue/issues/3300

In this particular case, the page stop to respond and crash.

### Steps to reproduce

1. Open an image using `viewer`
2. Open sidebar
3. Click on `Sharing` tab.
4. Click in `+` button in `sharing link` option.
5. Click in `...` button.
6. Move the mouse over the options

### Expected behavior

Everything must work without errors or performance issues like the sidebar/sharing of files list.

### Installation method

Other Community project

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
-
```

**Comment by szaimen** [comment]
should be fixed with 25.0.2
