### ISSUE TITLE
User theming changes original primary colour

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#34431]
There seem to be some bug to happen when you change your personal theming and visit the admin theming. the primary color is then set to the one of the personal color although it should still be the default Nextcloud color IIRC
See 
![image](https://user-images.githubusercontent.com/42591237/192889994-167521e8-ba66-44e8-bfb1-944aa7746b69.png)

_Originally posted by @szaimen in https://github.com/nextcloud/server/pull/34298#pullrequestreview-1124366041_

**Comment by skjnldsv** [comment]
Also applies on the `plain background` option on user theming
![image](https://user-images.githubusercontent.com/14975046/194010854-7d1e8db6-66c1-4e3b-9358-b794b86bee6b.png)

**Comment by skjnldsv** [comment]
> Maybe we could allow the user to pick a color for that too like we plan for the custom background option? See #34433

done

**Comment by PVince81** [comment]
this PR https://github.com/nextcloud/server/pull/34437 is supposed to fix this
