### ISSUE TITLE
[Bug]: WebDAV URL http scheme incorrectly displayed

### ISSUE THREAD

**Issue by gStart9** [nextcloud/server#34430]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When you go to Files -> Settings

WebDAV URL's scheme (http://) does not match the url of the nextcloud server (https://)

![webdavurl-issue](https://user-images.githubusercontent.com/106188942/193996329-d315f7dd-6edd-4c40-9614-53c10facba22.jpg)

### Steps to reproduce

1. Log in
2. Click Files
3. Click Settings
4. See that WebDAV URL is not correct scheme if your site is at https://

### Expected behavior

I expect the URL to be existent and consistent with with the server and instance I am actually on.

### Installation method

Community Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 442368 bytes) in /var/www/html/3rdparty/composer/autoload_real.php on line 35
```

### List of activated Apps

```shell
Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 442368 bytes) in /var/www/html/3rdparty/composer/autoload_real.php on line 35
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional info

A similar bad http:// url is displayed when I go to User Profile > Settings > System > External monitoring tool

My nextcloud is setup on https:// so this url will not work.

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by gStart9** [comment]
I actually think this is a bug.  Nextcloud is configured with environment variable:
NEXTCLOUD_TRUSTED_DOMAINS="$LAN_ADDRESS $SERVICE_ADDRESS"
These are 2 different domains, each of which I need nextcloud available on, and one of them is https:// and one is http://
