### ISSUE TITLE
[Bug]: Searchbar crashes when selecting an application

### ISSUE THREAD

**Issue by come-nc** [nextcloud/server#34441]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When using the unified search bar, clicking an application in the filter menu will make the pop-up close, and when opening it again the search results are not there.

### Steps to reproduce

1. Click on the search icon
2. Enter some text
3. After results are here, click the filter menu and select an application

### Expected behavior

See search result only for the clicked application

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Happens on our instance
```

**Comment by PVince81** [comment]
hitting enter multiple times:
<img width="736" alt="image" src="https://user-images.githubusercontent.com/277525/195881240-edbe5d1e-4749-46b0-bcee-43095d0fd914.png">

it logs that it will search but nothing appears in the network console

**Comment by PVince81** [comment]
I logged the types array and it's empty, so there's nothing to search

need to debug the parsing code

**Comment by PVince81** [comment]
something is wrong with the RegExp, it doesn't seem to match or to be used correctly

**Comment by PVince81** [comment]
need to use the third match, not second:
<img width="445" alt="image" src="https://user-images.githubusercontent.com/277525/195884414-9abb934a-583e-4310-a395-24eeafcdfd70.png">

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/server/pull/34614
