### ISSUE TITLE
[Bug]: Default background and cloud background are the same

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#34449]
### Bug description

With 25 we now have a default background (cloud with blue color)
The list of backgrounds also includes this background, which makes it a duplicate.

![image](https://user-images.githubusercontent.com/14975046/194293654-0cd1853f-dddd-4ca3-9240-c164ff3a02e2.png)

### Steps to reproduce

1. Setup 25
2. Go to user theming and accessibility settingss
4. See at the bottom

### Expected behavior

I suggest we remove it from the list OR we display the default background WITH the text `default background`

cc @jancborchardt @nimishavijay

**Comment by DoM1niC** [comment]
Any chance to make the background and theme color global default by config.php?

**Comment by skjnldsv** [comment]
> Any chance to make the background and theme color global default by config.php?

You will be abble to disable user theming and enforce the admin global theme instead with 26
