### ISSUE TITLE
[Bug]: cachebuster value rising infinitely 

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#34457]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The app config value for cachbuster of theming is constantly rising. This prevents caching on frontend resources, and has side effects on Talk. Because this is used in calculating a hash, it appears that resources were changed and requires a reload. This happens infinitely.

This was introduced in https://github.com/nextcloud/server/pull/34432 specifically the added lines 227 and 230 in `apps/theming/lib/ThemingDefaults.php`. The behaviour becomes normal when the lines are commented out, alas this may have other side effects I am not aware of.

### Steps to reproduce

1. Run Nextcloud 25 RC3 (earlier versions not affected)
2. Have Nextcloud Talk open

### Expected behavior

Talk does not think the instances was updated every 30s.

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [x] Other

### List of activated Apps

```shell
not relevant
```

**Comment by blizzz** [comment]
@Pytal would you mind investigating that?

**Comment by Pytal** [comment]
The cachebuster value was increased here

https://github.com/nextcloud/server/blob/0112a2925af360b23e65908c314a21619a1bcf33/apps/theming/lib/ThemingDefaults.php#L227-L230

in https://github.com/nextcloud/server/pull/34298 to ensure that assets like the favicon would display correctly for the user based on the auto-selected color preset from the shipped background

Will see if I can come up with a solution that will work alongside the latest theming updates

**Comment by PVince81** [comment]
I heard that it's critical because it increases the load on the server and Talk users get a message that they need to reload

**Comment by blizzz** [comment]
Yes, it's an absolute killer. Our instance is patched, as described above, right after the upgrade (as soon as i figured out where it happened).
