### ISSUE TITLE
Dashboard widget for activity returns incompatible icons

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#34466]
API returns SVG, which are not correctly parsed on Android:
![image](https://user-images.githubusercontent.com/5836855/194527203-4cabf2b1-8a45-428d-9a3e-8c5f6f7d304e.png)

I think those are the ones:
https:\/\/cloud.nextcloud.com\/core\/img\/places\/calendar.svg
https:\/\/cloud.nextcloud.com\/apps\/files\/img\/add-color.svg

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/blame/master/apps/files/img/add-color.svg
https://github.com/nextcloud/server/blame/master/core/img/places/calendar.svg

Both icons have a viewbox and size.

**Comment by tobiasKaminsky** [comment]
Strange… Then I check on Android side…
