### ISSUE TITLE
Separate backend admin and user theming

### ISSUE THREAD

**Issue by Pytal** [nextcloud/server#34472]
Theming configuration will need to be split between admin and user configured values

Currently theming values are set instance-wide using `$config->setAppValue()`, the introduction of user theming will require changes to allow for user-specific theming values to be set with `$config->setUserValue()`

This may also require the introduction of a user-specific cachebuster value if it is problematic to increase the instance-wide cachebuster value when a user changes their theming settings

**Comment by PVince81** [comment]
we already have user-specific cache buster for the background ? or does it need a separate one ?

**Comment by PVince81** [comment]
will be solved in https://github.com/nextcloud/server/pull/34599
