### ISSUE TITLE
[Bug]: INVALID_HASH: core/skeleton/Nextcloud Manual.pdf:

### ISSUE THREAD

**Issue by ant0nwax** [nextcloud/server#34475]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi

This File is provided by Nextcloud

this happened after an upgrade from 24.0.5 to 24.0.6

Output from CLI...

`cloud ~]# sudo -u apache php /var/www/html/nextcloud/occ integrity:check-core
  - INVALID_HASH:
    - core/skeleton/Nextcloud Manual.pdf:
      - expected: abf7371b397482bc58efefa57b69dc668f95605a31db558b8ef7e9bf595f44cf31434e879b553d4ee637a82068fdf92e201e85b196226b0c9205aa59aa32e686
      - current: d6313a540657fe3f36d4ba8ba884a0996220fb340af05055aad632e75f4e9458fb4b8fb5b33fb75ae26841f9a9ff06a9919b6a282719593888566541701aa106
`

Output from GUI:

`
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- core/skeleton/Nextcloud Manual.pdf
- files_pdfviewer
	- INVALID_HASH
		- js/pdfjs/build/pdf.worker.js.map

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/skeleton/Nextcloud Manual.pdf] => Array
                        (
                            [expected] => abf7371b397482bc58efefa57b69dc668f95605a31db558b8ef7e9bf595f44cf31434e879b553d4ee637a82068fdf92e201e85b196226b0c9205aa59aa32e686
                            [current] => d6313a540657fe3f36d4ba8ba884a0996220fb340af05055aad632e75f4e9458fb4b8fb5b33fb75ae26841f9a9ff06a9919b6a282719593888566541701aa106
                        )

                )

        )

    [files_pdfviewer] => Array
        (
            [INVALID_HASH] => Array
                (
                    [js/pdfjs/build/pdf.worker.js.map] => Array
                        (
                            [expected] => 6dea795c3fc20801ac14e3d54ce7c4af9bf29ef758e656576f88c459e133314a2c440f58c2953bde8b2011b355cfb53a867344480e76b2587ee6bb017adf2368
                            [current] => c2a3a6bf8c0bbd765d04c3e37f6fbce4d2f4926e78913e8bd739cfb883ed89ca65b6f6c84495fc610bc3439fd13f8fac2f466d75c82851a02cb4ee2a7b545c82
                        )

                )

        )

)
`

### Steps to reproduce

upgrade from 24.0.5 to 24.0.6 on CLI

### Expected behavior

no errors in overview/scan after update

### Installation method

Community Manual installation with Archive

### Operating system

RHEL/CentOS

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
sudo -u apache php /var/www/html/nextcloud/occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "allow_local_remote_servers": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "overwriteprotocol": "https",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.6.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "default_phone_region": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "loglevel": 2
    }
}
```

### List of activated Apps

```shell
sudo -u apache php /var/www/html/nextcloud/occ app:list
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - announcementcenter: 6.3.1
  - bruteforcesettings: 2.4.0
  - calendar: 3.5.0
  - circles: 24.0.1
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.2.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - deck: 1.7.1
  - external: 4.0.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - forms: 2.5.1
  - integration_google: 1.0.8
  - integration_openproject: 2.0.4
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - maps: 0.2.1
  - nextcloud_announcements: 1.13.0
  - notes: 4.5.1
  - notifications: 2.12.1
  - oauth2: 1.12.0
  - onlyoffice: 7.5.4
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - tasks: 0.14.4
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_totp: 6.4.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - encryption
  - mail: 1.13.8
  - user_ldap
```

### Nextcloud Signing status

```shell
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- core/skeleton/Nextcloud Manual.pdf
- files_pdfviewer
	- INVALID_HASH
		- js/pdfjs/build/pdf.worker.js.map

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/skeleton/Nextcloud Manual.pdf] => Array
                        (
                            [expected] => abf7371b397482bc58efefa57b69dc668f95605a31db558b8ef7e9bf595f44cf31434e879b553d4ee637a82068fdf92e201e85b196226b0c9205aa59aa32e686
                            [current] => d6313a540657fe3f36d4ba8ba884a0996220fb340af05055aad632e75f4e9458fb4b8fb5b33fb75ae26841f9a9ff06a9919b6a282719593888566541701aa106
                        )

                )

        )

    [files_pdfviewer] => Array
        (
            [INVALID_HASH] => Array
                (
                    [js/pdfjs/build/pdf.worker.js.map] => Array
                        (
                            [expected] => 6dea795c3fc20801ac14e3d54ce7c4af9bf29ef758e656576f88c459e133314a2c440f58c2953bde8b2011b355cfb53a867344480e76b2587ee6bb017adf2368
                            [current] => c2a3a6bf8c0bbd765d04c3e37f6fbce4d2f4926e78913e8bd739cfb883ed89ca65b6f6c84495fc610bc3439fd13f8fac2f466d75c82851a02cb4ee2a7b545c82
                        )

                )

        )

)
```

### Nextcloud Logs

```shell
you may request that in PM, i will not put all logs publix
```

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by ant0nwax** [comment]
Thank you for trying a marketing approach on me, no luck, i will also not report it... nextcloud works, its just a warning

**Comment by ant0nwax** [comment]
Actually i was reading the description three times and i give myself 2 weeks... there is written...

The solution is to upload the correct “index.php” and “version.php” files, and delete the “test.php” file. For the calendar exception contact the developer of the application. For other means on how to receive support please take a look at https://nextcloud.com/support/. After fixing these problems verify by clicking “Rescan…”.

Upload the correct version???

I never changed the Nextcloud Manual.pdf and from where shall I upload it if i never changed it?
I suppose this will be fixed automagically in 24.0.7

**Comment by ant0nwax** [comment]
In the docs please add:
you can get the original files of your Nextcloud here: [nextcloud.com/changelo](http://nextcloud.com/changelog)

**Comment by ant0nwax** [comment]
reference: https://help.nextcloud.com/t/issue-with-code-integrity-check-invalid-hash-core-folder/4527

**Comment by ant0nwax** [comment]
I replaced the files from the 24.0.6 zip

the Nextcloud Manual pdf error is gone
the pdf worker js map is still there

i reported a bug, and you closed it, because you feel insulted by commuity users...

for what reason do you actually do opensource if you try to force payment to people who work for free for you?
wanna be like Google?

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- files_pdfviewer
	- INVALID_HASH
		- js/pdfjs/build/pdf.worker.js.map

Raw output
==========
Array
(
    [files_pdfviewer] => Array
        (
            [INVALID_HASH] => Array
                (
                    [js/pdfjs/build/pdf.worker.js.map] => Array
                        (
                            [expected] => 6dea795c3fc20801ac14e3d54ce7c4af9bf29ef758e656576f88c459e133314a2c440f58c2953bde8b2011b355cfb53a867344480e76b2587ee6bb017adf2368
                            [current] => c2a3a6bf8c0bbd765d04c3e37f6fbce4d2f4926e78913e8bd739cfb883ed89ca65b6f6c84495fc610bc3439fd13f8fac2f466d75c82851a02cb4ee2a7b545c82
                        )

                )

        )

)
