### ISSUE TITLE
[Bug]: Tagging Multiple Photos Results in Database Connection Exhaustion, and Photos are left Untagged

### ISSUE THREAD

**Issue by dijikul** [nextcloud/server#34482]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

With ~900 vacation photos selected in the Files -> Folder browser, I am attempting to apply a Tag to all the selected files via the Actions menu, however the tag is not applied to all, only a small number of files, caused by Postgres database connection exhaustion.

![image](https://user-images.githubusercontent.com/2670528/194728692-ffef91ab-0e60-4fc3-b2c4-271966f9d39f.png)

My Postgres database is located on an SMB share mounted to my Docker host, which is non-standard, and my be related, but it's unclear to me if this can be solved with Nextcloud doing some kind of connection pooling, rather than the current attempt at Connect -> Tag -> Close-connection, which appears not to scale.

### Steps to reproduce

1. Within Nextcloud's Folder UI, Highlight a large number of files to tag.  In my scenario I have 869:
![image](https://user-images.githubusercontent.com/2670528/194728859-f4a89eb4-3ce9-49e6-944b-2d1e16affd92.png)

2. Observe the server logs while the Tag Menu attempts to load the tags for all selected files.  Things are fine for a few seconds but then quickly result in repeated FATAL errors reporting _Sorry, too many clients alread_: 
![image](https://user-images.githubusercontent.com/2670528/194728943-1ab79325-512b-4651-ae9f-14defe418679.png)

3. At this point the bug is demonstrated, but similar behaviour in server logs is shown when attempting to apply a tag to these selected files.  First, a tag must be created by selecting and applying it to an individual photo, so it appears in the list of tags to apply when multiple are selected.   (For some reason you cannot create new tags from the multiple-apply menu)

4. After applying the tag to a single photo from the sidebar menu, that tag should now be available as an option from the multiple select menu:
![image](https://user-images.githubusercontent.com/2670528/194729066-ffbe4218-f844-41bc-949a-514bce198f5b.png)

5. Attempting to review by the tag provides the total number of files tagged at the bottom of the list.  In my case, 58 files were tagged after multiple attempts to tag while reproducing these steps:
![image](https://user-images.githubusercontent.com/2670528/194729123-85c17fb3-d0c4-4636-b34f-cf33ee640798.png)

### Expected behavior

It should be possible to tag all files selected with the current UI implementation, however some kind of connection-pooling may be required, or depending on the SQL back-end, passing the file references as an array to apply all tags in a single statement, rather than a loop.

### Installation method

_Docker Image via Docker Compose_

### Operating system

_Debian/Ubuntu_

### PHP engine version

_8.0_

### Web server

_Apache_

### Database engine version

_Postgres_

### Is this bug present after an update or on a fresh install?

_Fresh Install using docker-compose_

### Are you using the Nextcloud Server Encryption module?

_No_

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.dijikul.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "24.0.5.1",
        "overwrite.cli.url": "http:\/\/cloud.dijikul.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - bruteforcesettings: 2.4.0
  - cfg_share_links: 2.0.0
  - checksum: 1.1.4
  - circles: 24.0.1
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - duplicatefinder: 0.0.15
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_downloadactivity: 1.13.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - maps: 0.2.1
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.1
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - previewgenerator: 5.1.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - webhooks: 0.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - flow_notifications: 1.4.0
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Logs are too long to post, per Github's comment system.


"message":"Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] FATAL:  sorry, too many clients already",
```
```


### Additional info

Both /var/www/html/data and postgres storage locations are are SMB-mounted shares that exist on a NAS in RAID-5 accessible to this server over gigabit ethernet, mounted as volumes into their respective docker containers.

**Comment by SchoolGuy** [comment]
I don't want to open a second bug but a user of my instance ran into an issue with the same symptoms as well. In my case I have set a CPU limit of 2.0 in my stateful set for the nextcloud pod and when the user sends the request to tag ~1400 files the CPU limit essentially halts the instance. The database is working fine. In my case the DB is on an NVME and the data on a RAID 5 locally.

**Comment by dijikul** [comment]
In my case, when I monitor the cluster with `docker-compose logs -f`, the issue is very specific to database connections.

When you say _the same symptoms_, what do you mean?  In my situation, the UI remains functional and I can navigate away to other pages.  The instance isn't halted; just that the looping/repeated calls to the database result in `2022-10-07 05:20:26.779 UTC [2737] FATAL:  sorry, too many clients already`

**Comment by SchoolGuy** [comment]
I am referring to that I am only able to batch tag files up until 100 circa. Everything over that halts the instance. I believe in your case with Docker there are no CPU limits, meaning you go further in the process. However you are right that the difference in our symptoms is that your WebUI stays responsive.

**Comment by dijikul** [comment]
In my case I don't even get to 100 files tagged.  After repeating the process three times, I'm left with 58 files tagged.

This is definitely a different issue, but related to how the tagging UI executes it's workloads.  My guess is both of our issues could be addressed with a bugfix, but they appear to be separate issues at the root.

**Comment by SchoolGuy** [comment]
@dijikul normally such a messure is only needed when an application is not optinized enough. Keep in mind that you did not change the number of users or you increased the number of tags drastically. So why should we increase the number of connections to the DB? However I will try that in my deployment too...

**Comment by dijikul** [comment]
> normally such a messure is only needed when an application is not optinized enough.

Agreed.  My reason for opening this Bug is caused by the Tagging interface using for-each logic instead of acting on tags as a set.

> why should we increase the number of connections to the DB

My specific errors trace to database connection exhaustion (see original bug, above, with log details).  If you believe your issue to be caused by CPU, I would not think touching database connections to be effort spent in the correct direction.

**Comment by szaimen** [comment]
Hi, please update to 25.0.7 or better 26.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 26-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
