### ISSUE TITLE
[Bug]: Update security.txt Expires field

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/server#34480]
The `Expires` field from `security.txt` should be updated regularly to make sure information is not stale.

> It is RECOMMENDED that the value of this field be less than a year into the future to avoid staleness.

https://datatracker.ietf.org/doc/html/rfc9116#section-2.5.5

Is there a way of automating this to have an up-to-date value at each major release? Or at least add the update to the release steps?

https://github.com/nextcloud/server/blob/afdb75d98b19f9d93723866dd09806e3ec1af9b6/apps/settings/lib/WellKnown/SecurityTxtHandler.php#L41

We could also add the following lines:
```
Preferred-Languages: en
Hiring: https://nextcloud.com/jobs/
```

**Comment by szaimen** [comment]
cc @nickvergessen @miaulalala @julien-nc
