### ISSUE TITLE
[Bug]: logo/background/logoheader/favicon change all the time in capability

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#34496]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

check Capability via {{ base_url  }}/ocs/v1.php/cloud/capabilities, see changing eTag

### Steps to reproduce

1. check Capability via {{ base_url  }}/ocs/v1.php/cloud/capabilities
2. see "logo": "http:\/\/localhost\/core\/img\/logo\/logo.svg?v=27" --> "logo": "http:\/\/localhost\/core\/img\/logo\/logo.svg?v=28"
3. same is true for background, logoheader, favicon

### Expected behavior

Etag stays the same

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
tested with latest NC master
```

### List of activated Apps

```shell
/
```

**Comment by szaimen** [comment]
See https://github.com/nextcloud/server/issues/34457
