### ISSUE TITLE
Add setup warning in case row_format=compressed is still used

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#34497]
Since https://github.com/nextcloud/server/pull/30129 any new install of NC >= 24 will have row_format=dynamic with MariaDB.

Also, we saw reports where having "compressed" might negatively affect performance.

We should look into the following:
- [ ] add a setup check that verifies that all known tables have row_format=dynamic instead of compressed.
- [ ] if possible: add an occ command that migrates the tables to the new format. To be verified whether it's a quick thing or whether it can take hours for lots of data

@icewind1991 @juliushaertl @nickvergessen @CarlSchwan @szaimen

**Comment by nickvergessen** [comment]
> if possible: add an occ command that migrates the tables to the new format. To be verified whether it's a quick thing or whether it can take hours for lots of data

We have that already as a repair step and it's also reachable via `occ db:convert-mysql-charset` ?
https://github.com/nextcloud/server/blob/master/lib/private/Repair/Collation.php#L82

Also your initial statement is wrong, every new install will **NOT** have compressed anymore, but dynamic.

**Comment by PVince81** [comment]
sorry, I typed it wrong. fixed now.

hmm, the command `occ db:convert-mysql-charset` seems a bit obscure.
but if it does the job then we could direct to it from the setup check then

**Comment by ChristophWurst** [comment]
My observation on the dev env that was installed circa 2016 and only upgraded but never reset so far:

![image](https://github.com/nextcloud/server/assets/1374172/3e8910f3-ddce-4d1f-98c3-17fde842acdf)

At some point I must have switched to UTF8 MB4 but that was at a time where we still created tables with row format compressed.

The query in `\OC\Repair\Collation::getAllNonUTF8BinTables` only checks the COLLATION_NAME and CHARACTER_SET.

Would it make sense to add a setup check and repair step for the row format specifically?

```
MariaDB [nextclouddev]> SELECT COUNT(*), ROW_FORMAT FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE 'oc_%' GROUP BY ROW_FORMAT;
+----------+------------+
| COUNT(*) | ROW_FORMAT |
+----------+------------+
|       53 | Compact    |
|      316 | Compressed |
|       52 | Dynamic    |
+----------+------------+
3 rows in set (0,021 sec)
```

My personal production instance of Nextcloud 27 confirms that not all upgrade paths lead to a fully dynamic row format for all tables:

```
MariaDB [(none)]> SELECT COUNT(*), ROW_FORMAT FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE 'oc_%' GROUP BY ROW_FORMAT;
+----------+------------+
| COUNT(*) | ROW_FORMAT |
+----------+------------+
|      214 | Compressed |
|       19 | Dynamic    |
+----------+------------+
2 rows in set (0,008 sec)
```

**Comment by artonge** [comment]
@Altahrim can you take a look and tell us whether we should create a setup check or a repair step?
The question is, if the conversion from compressed to dynamic takes too much time, then a repair step could be an issue, but we at least need to tell the admin about it.

Example code for the future implementation:
- Example of setup check: https://github.com/nextcloud/server/blob/ae0106ef9e9b4a91d385fff7490e17963e73c40d/apps/settings/lib/SetupChecks/MysqlUnicodeSupport.php
- Example of repair step: https://github.com/nextcloud/server/blob/ae0106ef9e9b4a91d385fff7490e17963e73c40d/lib/private/Repair/Collation.php

**Comment by ChristophWurst** [comment]
I would advice against a repair step. This migration takes very long and it roughly doubles the required disk space. Admins need to plan for both.

**Comment by Altahrim** [comment]
I would also vote for a setup check :)

**Comment by ChristophWurst** [comment]
MariaDB enterprise enforces the dynamic row format as well: https://mariadb.com/docs/server/service-management/upgrades/enterprise-server/from-community-server-es10-6/#Convert_InnoDB_Row_Format

UPD: https://mariadb.com/docs/server/server-usage/storage-engines/innodb/innodb-row-formats/innodb-dynamic-row-format

**Comment by sorbaugh** [comment]
@Altahrim let's schedule this

**Comment by andreas-bulling** [comment]
It'd at least be nice if the documentation provided instructions for how to do the migration manually. The setup check only shows the warning but the link goes to the official documentation and is not helpful for this.

**Comment by X4LD1M0** [comment]
I found the following piece of code which might help:

```
SELECT
    @sql :=  GROUP_CONCAT(CONCAT( "ALTER TABLE `", table_schema, "`.`", table_name, "` ROW_FORMAT=DYNAMIC;",CHAR(10)) SEPARATOR " ")
FROM
    information_schema.TABLES 
WHERE
    table_schema = 'testdb'
    AND ROW_FORMAT <> 'Dynamic';

```
Replace 'testdb' with your Nextcloud DB name. From the output take all the ALTER TABLE lines, and past it back into the Mysql/MariaDB prompt, so each line is executed individually. The ALTER TABLE command can only be run one at a time.

Using this has helped me migrate my DB.

**Comment by SolidTux** [comment]
The solution is not that great and I really think that there should be an occ command to fix this. Having to search forums and then trying to copy and paste such a long string on a remote server is not really a good experience when face with this warning.
