### ISSUE TITLE
[Bug]: NC 25 Dark Theme default avatar not showing under Contacts Menu

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/server#34503]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Currently on NC 25 the new avatar was introduced https://github.com/nextcloud/server/pull/33752/files.  Since this was introduced the Contact Menu is only displaying avatars in white  when server theme is set to dark mode 

![image](https://user-images.githubusercontent.com/59488153/194901775-52a17e53-c457-4b9e-b590-6f946f977a63.png)

Current code to load picture would be in here.   Do you have any recommendations for me? So I can create a pull request and do some testing for you guys ? 

https://github.com/nextcloud/server/blob/master/lib/private/Contacts/ContactsMenu/ContactsStore.php

### Steps to reproduce

Open Contact Menue 

### Expected behavior

Should show in dark mode avatar when server them is set to dark

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
NA
```

**Comment by PVince81** [comment]
slightly related but this was only icons, not avatars: https://github.com/nextcloud/server/pull/34571

**Comment by andyxheli** [comment]
@PVince81 what I meant by avatar was the logo of the usernames I'm sorry used tye wrong word. I think that is related now 🤔

**Comment by andyxheli** [comment]
@PVince81 is that fixing the user profile logo ?

**Comment by AndyXheli** [comment]
Still an issue on NC26.0.0

**Comment by AndyXheli** [comment]
Still an issue on NC 27 @szaimen can we please remove NC 25 feedback and put NC 27 ?

**Comment by AndyXheli** [comment]
Looks like this issue has been fixed in NC 28 RC 4 but still an issue on NC 27.1.5

**Comment by joshtrichards** [comment]
Agreed. Confirmed fixed in >=28.
