### ISSUE TITLE
[Bug]: Wrong appPassword behaviour on authv2 flow

### ISSUE THREAD

**Issue by salavursa** [nextcloud/server#34501]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I try to get app password for more than 1 user on my server, something weird happens and sometimes passwords do not work properly with associated username.

### Steps to reproduce

there are 3 steps I do to connect new user in my web application:

1. {serverUrl}//index.php/login/v2 -> I get pollToken&pollUrl and loginUrl
2. user is logging in with provided loginUrl in 1st step
3. once user has logged in I get OK response from {serverUrl}/login/v2/poll?token={pollToken} -> I get username and appPwd
4. with those creds in baseAuth I'm fetching usermetadata like {serverUrl}/ocs/v2.php/cloud/users/{username} -> I get usermetadata
5. if last response is OK I'm saving metadata and creds to my database

for example I have 3 users: user1, user2, user3

It works just fine if I need to login 1 user like user1, but if I try to login user2 after user1, I get such appPassword, which works with dav requests (e.g. getFolderContent) but doesn't work with OCS (e.g. to getMetadata). Further investigation showed that app password, generated for user2 after user1, works to get user1's metadata!! but its supposed to work with user2 only. 

I can reproduce this bug in postman, just try to login user1 and get it's meta, then login with user2 and get its meta. If you get Error, try to get usermetadata of prev username -> it will work.

response I get when login second user, this pwd works to get artemTest02 metadata but not artemTest03
<img width="758" alt="image" src="https://user-images.githubusercontent.com/67692229/194745476-6e1ed1f9-2e76-4b3e-b234-ac6ecae1c9a0.png">
 

Also, when I delete this weird password with DELETE {serverUrl}/ocs/v2.php/core/apppassword (user2’s pwd, witch works to get user1 meta), it also disables previous user’s password and I’m not able to get files for user1 anymore

sometimes I can login 2 users and this is happening with third, randomly. Probably some cache issues or something, please check

### Expected behavior

All appPasswords should be working with corresponding users, but not logged in before (e.g. OCS get metadata / make share). Deleting appPassword should not affect other users were logged in before

### Installation method

Community Docker image

### Operating system

Debian/Ubuntu

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
b79b28190c8f php occ app:list
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - bruteforcesettings: 2.4.0
  - circles: 24.0.1
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```

**Comment by kesselb** [comment]
cc @nextcloud/security

**Comment by szaimen** [comment]
@salavursa which NC version is this?

**Comment by kesselb** [comment]
> @salavursa which NC version is this?

24, you can guess from the circles app ;) 

Still would be nice to add this question back to the form.

**Comment by salavursa** [comment]
@szaimen any additional info required?

**Comment by salavursa** [comment]
@kesselb @szaimen how do we move forward with this issue?

**Comment by salavursa** [comment]
@kesselb  @szaimen  how do we move forward with this issue?

**Comment by salavursa** [comment]
@kesselb @szaimen any chance I get response here?

**Comment by szaimen** [comment]
Sorry, I have no idea how to fix this

**Comment by salavursa** [comment]
@szaimen do you mean you can't reproduce it on your side or literally can't?

**Comment by kesselb** [comment]
Hi, are you sure the http client is not keeping the cookies? 

Postman for example does that by default: https://www.redelijkheid.com/blog/2021/10/8/clear-cookies-in-postman

If you can reproduce with curl please submit to https://hackerone.com/nextcloud and include your issue description, a link to this GitHub issue and the curl commands. 

Thank you :+1:

**Comment by salavursa** [comment]
@kesselb you were right, didnt know that my java client was forcing cookies by default, sorry. All is fine here
