### ISSUE TITLE
enable_avatars=false breaks sharing

### ISSUE THREAD

**Issue by patrakov** [nextcloud/server#3451]
### Steps to reproduce
1. Install OwnCloud 9.x
2. Disable avatars by setting 'enable_avatars' => false in the config
3. Share files between users (works fine)
4. Upgrade to NextCloud 9.x, 10.x and 11.0.1
5. Try to share files

### Expected behaviour
Sharing should continue to work

### Actual behaviour
When a user types a partial name of another user, a JavaScript error appears in the browser console (see below). Therefore, the autocomplete list is never shown, and it is not possible to click on the completed username, and thus it is not possible to share a file.

### Server configuration
**Operating system**: Linux, Ubuntu 16.04

**Web server:** Apache

**Database:** MySQL 5.7

**PHP version:** 7.0.8

**Nextcloud version:** (see Nextcloud admin page) 11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgraded

**Where did you install Nextcloud from:** tar.bz2

**Signing status:** No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - firstrunwizard
  - user_external
  - user_saml

</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
<pre>
{
    "system": {
        "instanceid": "oce0e2e83ff5",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "dbtype": "mysql",
        "version": "11.0.1.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "enable_previews": true,
        "loglevel": 1,
        "session_lifetime": 86400,
        "remember_login_cookie_lifetime": 86400,
        "updatechecker": false,
        "knowledgebaseenabled": false,
        "allow_user_to_change_display_name": false,
        "appstoreenabled": false,
        "skeletondirectory": "",
        "forcessl": true,
        "mail_smtpmode": "php",
        "trashbin_retention_obligation": "30, auto",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/Shared",
        "theme": "",
        "appstore.experimental.enabled": false,
        "mail_from_address": "devel",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "enable_avatars" => false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "memcache.local": "\\OC\\Memcache\\Memcached"
    }
}
</pre>
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### Browser log
<details>
<summary>Browser log</summary>

<pre>
Uncaught TypeError: avatar.avatar is not a function
at $.(anonymous function).(anonymous function).autocompleteRenderItem [as _renderItem] (https://.../core/js/sharedialogview.js?v=...:281:12)
at $.(anonymous function).(anonymous function)._renderItemData (https://.../core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=...:6281:15)
at $.(anonymous function).(anonymous function)._renderItemData (https://.../core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=...:405:25)
at Object.<anonymous> (https://.../core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=...:6276:9)
at Function.each (https://.../core/vendor/jquery/dist/jquery.min.js?v=...:2:2882)
at $.(anonymous function).(anonymous function)._renderMenu (https://.../core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=...:6275:5)
at $.(anonymous function).(anonymous function)._renderMenu (https://.../core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=...:405:25)
at $.(anonymous function).(anonymous function)._suggest (https://.../core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=...:6248:8)
at $.(anonymous function).(anonymous function)._suggest (https://.../core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=...:405:25)
at $.(anonymous function).(anonymous function).__response (https://.../core/vendor/jquery-ui/ui/jquery-ui.custom.js?v=...:6197:9)
</pre>
</details>

**Comment by DJCrashdummy** [comment]
since it does not break sharing itself - shares created before adding this switch still work; and creating shares via links works all the time - i would like to see this bug fixed and the switch kept.

why disable?
- maybe some don't need and/or want avatars...
- without sharing everything works pretty good.
- just when you need sharing and don't like avatars (like me) you are in trouble...

anyway... **at least a hint in the docs (or anywhere else) would be nice!** - _it took me half a day to nail this bug down and then find this bug report! :-(_
