### ISSUE TITLE
allow to choose a custom primary color for custom backgrounds

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#34512]
> > I see. However I fear #34433 is then not really resolved as we still run into the problem that the primary color might in most cases not suit your custom background (since for them always blue is primary color), no?
> 
> A right, I thought it was the ticket about picking custom color only. Yes, extracting a colour from the custom background is another task

I don't agree that extracting a color from the background color is necessary in order to fix the problem. Allowing to pick a custom color would fix it as well but in that case both need to be possible. (custom color and custom background at the same time; we should even ask the user to choose a custom color in that case directly.)

WDYT @jancborchardt @nimishavijay ?

cc @skjnldsv 

_Originally posted by @szaimen in https://github.com/nextcloud/server/issues/34437#issuecomment-1270465199_

**Comment by skjnldsv** [comment]
See https://github.com/nextcloud/server/issues/34560#issuecomment-1277552105
