### ISSUE TITLE
[Bug]: User cacheDir is not removed when user is deleted

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#34510]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

User `$cacheDir` is not removed when user is deleted

### Steps to reproduce

1. Set `cache_path` in config.php (`/opt/nextcloud/cache`)
2. Create user and upload some files
3. Delete user (`occ user:delete user`)
4. `/opt/nextcloud/cache/user` folder is not deleted

### Expected behavior

User `$cacheDir` is also removed when user is deleted

https://github.com/nextcloud/server/blob/master/lib/private/Files/Mount/CacheMountProvider.php#L47-L70

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
