### ISSUE TITLE
[Bug]: 25 RC3 App updater asks for password, entering followed by enter works, pressing button fails

### ISSUE THREAD

**Issue by noci2012** [nextcloud/server#34516]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When updating a app (apps, udpate all) sometimes a password is requested.
If the password is entered the button stays disabled, pressing enter will allow to continue.

### Steps to reproduce

1. Have 25 RC3, and a app to be updated
2. do update after being loggedon several hours, so a password gets requested
3. Try to enter the password using  the button.

### Expected behavior

A working button

### Installation method

Community VM appliance

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Not relevant.
```

### List of activated Apps

```shell
various
```

### Nextcloud Signing status

```shell
N/A
```

### Nextcloud Logs

```shell
N/A
```

### Additional info

N/A

**Comment by PVince81** [comment]
@Pytal likely related to the upcoming fix for the password prompt ?

**Comment by szaimen** [comment]
it will get fixed with 25.0.1 and https://github.com/nextcloud/server/pull/34590

**Comment by noci2012** [comment]
not fixed in 25.0.0 Final, but it was stated to be solved in 25.0.1  so this is just a ack that it is not fixed in this release yet.
