### ISSUE TITLE
Multiple Login-Backgrounds

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#3452]
This request is about the possibility to set multiple images as login-background. They could be shown in a random way. Downside could be the lower/missing recognation value - but I've seen this on other places too, so let's discuss this 😉

This request was taken from Twitter: https://twitter.com/dc7ia/status/830160656708009984

What do you think? @juliushaertl @nextcloud/designers

**Comment by skjnldsv** [comment]
Why not :)

**Comment by eppfel** [comment]
I think this should be an app and not in core.

**Comment by juliushaertl** [comment]
What @eppfel said. :wink: It should be quite easy to build an app that supports that.
We should keep the theming as simple as possible.

**Comment by jancborchardt** [comment]
Yep, what @eppfel and @juliushaertl said ;)
