### ISSUE TITLE
Opening a folder triggers change notification

### ISSUE THREAD

**Issue by riweckr** [nextcloud/server#34530]
Opening a folder that shows a Readme.md through the rich workplace feature triggers a change notification.

### Steps to reproduce
1. Create a new Folder
2. add a file called Readme.md by using rich workspaces feature
3. switch to an other folder
4. come back to the folder created at 1.
5. Go to ...apps/activity/

### Expected behaviour
Do not find a notification about "You changed Readme.md" in the activities (step 4).

### Actual behaviour
A notification about "You changed Readme.md" (step 4) is listed in the activities.

### Server configuration

**Operating system**: Linux 5.13.19-3-pve x86_64

**Web server:** Nginx

**Database:** mariaDB 10.5.15

**PHP version:** 7.4.3

**Nextcloud version:** 23.0.4

**Where did you install Nextcloud from:** nexcloud.com download

**Signing status:** Admin and user

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.

No errors have been found.
```

**List of activated apps:**

```
Calendar	3.4.2
Accessibility	1.9.0
Activity	2.15.0
Brute-force settings	2.4.0
Circles23.	1.1
Collaborative tags	1.13.0
Comments	1.13.0
Contacts	4.2.2
Contacts Interaction	1.4.0
Dashboard	7.3.0
Deleted files	1.13.0
External storage support	1.15.0
Federation	1.13.0
File sharing	1.15.0
Files automated tagging	1.13.0
GitLab integration	1.0.6
Group folders11.	1.5
Log Reader	2.8.0
Monitoring	1.13.0
Nextcloud announcements	1.12.0
Notifications	2.11.1
Password policy	1.13.0
PDF viewer	2.4.0
Photos	1.5.0
Privacy	1.7.0
Recommendations	1.2.0
Retention	1.12.1
Right click	1.2.0
Share by mail	1.13.0
Support	1.6.0
Tasks	0.14.4
Text	3.4.1
Theming	1.14.0
Two-Factor TOTP Provider	6.4.0
Update notification	1.13.0
Usage survey	1.11.0
Versions	1.16.0
Video player	1.12.0
Workflow OCR	1.23.6
```

### Client configuration
**Browser:** FireFox 105

**Operating system:** Ubuntu 18.04.

**Comment by nickvergessen** [comment]
This is not a bug in the activity app.

Moving to server for now, but might also be that it needs to go to the text app.

**Comment by riweckr** [comment]
@XueSheng-GIT maybe it is. IMHO the same issue is described in comment https://github.com/nextcloud/text/issues/3543#issuecomment-1351755667

This is a duplicate now.
