### ISSUE TITLE
[Bug]: Two factor auth cannot be setup

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#34536]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading to NC24 I cannot login, as my user does only have old 2fa.

### Steps to reproduce

1. upgrade to nc24
2. see 
![image](https://user-images.githubusercontent.com/5836855/195093899-6b9f56c7-c82b-4e4e-a371-8ae375fe805d.png)

3. click on blue button leads to same page: /login/selectchallenge?redirect_url=/login/setupchallenge

### Expected behavior

Setup 2fa

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - analytics: 4.4.0
  - bookmarks: 11.0.3
  - calendar: 3.5.0
  - circles: 24.0.1
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.2.1
  - contactsinteraction: 1.5.0
  - cookbook: 0.9.15
  - dashboard: 7.4.0
  - dav: 1.22.0
  - encryption: 2.12.0
  - end_to_end_encryption: 1.10.0
  - event_update_notification: 1.5.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_automatedtagging: 1.14.0
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_retention: 1.13.2
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - grocerylist: 0.0.1
  - guests: 2.3.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - mail: 1.13.8
  - news: 18.1.1
  - notes: 4.5.1
  - notifications: 2.12.1
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - polls: 3.8.1
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - qownnotesapi: 22.5.0
  - richdocuments: 6.2.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - spreed: 14.0.5
  - systemtags: 1.14.0
  - tasks: 0.14.4
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - twofactor_nextcloud_notification: 3.4.0
  - twofactor_totp: 6.4.0
  - twofactor_webauthn: 0.3.3
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - workflowengine: 2.6.0
Disabled:
  - admin_audit: 1.13.0
  - admin_notifications: 1.0.2
  - announcementcenter: 6.3.1
  - deck: 1.7.1
  - documentserver_community: 0.1.12
  - dropit: 0.4.0
  - external: 4.0.0
  - facerecognition: 0.9.1
  - files_fulltextsearch: 24.0.1
  - files_fulltextsearch_tesseract: 24.0.0
  - files_rightclick: 1.1.0
  - fulltextsearch: 24.0.0
  - fulltextsearch_elasticsearch: 24.0.1
  - grocerylist_
  - maps: 0.2.1
  - nextcloud_announcements: 1.11.0
  - onlyoffice: 7.5.4
  - previewgenerator: 5.1.0
  - radio: 1.0.2
  - recommendations: 1.2.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - twofactor_u2f: 6.3.1
  - user_ldap
  - weather: 1.7.6
  - weather_status: 1.2.0
```

**Comment by szaimen** [comment]
Hi, please update to 25.0.7 or better 26.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 26-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
