### ISSUE TITLE
Dark navigation icons for custom backgrounds

### ISSUE THREAD

**Issue by Tealk** [nextcloud/server#34549]
There should be a possibility to darken the navigation icons for own backgrounds

A separate background, the upper edge is bright
Theme Color `#078D4E`

Unfortunately I don't know how to get the navigation dark like it is with some of the preinstalled background images.
![image](https://user-images.githubusercontent.com/12276250/194907656-2d085ef8-4c61-4f2b-8433-e87acd5d4293.png)

_Originally posted by @Tealk in https://github.com/nextcloud/server/issues/33925#issuecomment-1273525150_

**Comment by skjnldsv** [comment]
Allowing to select a different colour with the background should let you do this.
Closing for https://github.com/nextcloud/server/issues/34560#issuecomment-1277552105

**Comment by Tealk** [comment]
@skjnldsv I'm not sure if we are talking about the same thing, I just want a switch that turns the icons black, then they would be easy to read.

If you use the user backgrounds, the icons on some light backgrounds also turn black.
