### ISSUE TITLE
Accept remote share on notification failed

### ISSUE THREAD

**Issue by apg1980** [nextcloud/server#3455]
### Steps to reproduce
1. Accept remote share on notification
2. Failed to perform action appears
3. Following entrys in the log:
Error	PHP	Call to a member function file_exists() on null at /OWNCLOUD-DATA/opt/bitnami/apps/owncloud/htdocs/lib/private/legacy/helper.php#346	2017-02-11T08:45:52+0100
Error	PHP	Argument 3 passed to OC_Helper::buildNotExistingFileNameForView() must be an instance of OC\Files\View, null given, called in /OWNCLOUD-DATA/opt/bitnami/apps/owncloud/htdocs/lib/private/legacy/helper.php on line 323 and defined at /OWNCLOUD-DATA/opt/bitnami/apps/owncloud/htdocs/lib/private/legacy/helper.php#333

### Expected behaviour
Remote share should be accepted

### Actual behaviour
Share is not accepted, is still appearing on notification.

### Server configuration
**Operating system**: Linux linux 4.4.0-34-generic #53~14.04.1-Ubuntu SMP Wed Jul 27 16:56:40 UTC 2016 x86_64

**Web server:** Apache (apache2handler)

**Database:** mysql 5.6.29

**PHP version:** 5.6.19
Modules loaded: Core, date, ereg, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gettext, gmp, SPL, iconv, session, intl, json, ldap, mbstring, mcrypt, standard, mysqlnd, mysqli, mysql, PDO, pdo_mysql, pdo_sqlite, Phar, posix, Reflection, imap, SimpleXML, soap, sockets, exif, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, apache2handler, redis, Zend OPcache

**Nextcloud version:** 11.0.1 (stable) - 11.0.1.2

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** 

**Signing status:**
<details>
	<summary>Signing status</summary>

```
"Integrity checker has been disabled. Integrity cannot be verified."
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.4.1
 - admin_audit: 1.1.0
 - announcementcenter: 3.0.0
 - audioplayer: 1.4.1
 - bookmarks: 0.9.1
 - calendar: 1.5.0
 - comments: 1.1.0
 - contacts: 1.5.3
 - dav: 1.1.1
 - direct_menu: 0.10.0
 - federatedfilesharing: 1.1.1
 - federation: 1.1.1
 - files: 1.6.1
 - files_downloadactivity: 1.0.0
 - files_external: 1.1.2
 - files_pdfviewer: 1.0.1
 - files_reader: 0.8.4
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - firstrunwizard: 2.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mozilla_sync: 1
 - news: 10.1.0
 - nextcloud_announcements: 1.0
 - notifications: 1.0.1
 - ownnote: 1.08
 - password_policy: 1.1.0
 - previewgenerator: 1.0.1
 - provisioning_api: 1.1.0
 - rainloop: 4.27
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - survey_client: 0.1.5
 - systemtags: 1.1.3
 - tasks: 0.9.4
 - templateeditor: 0.2
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - updatenotification: 1.1.1
 - user_ldap: 1.1.1
 - workflowengine: 1.1.1

Disabled:
 - documents
 - encryption
 - external
 - files_accesscontrol
 - files_automatedtagging
 - files_retention
 - keeweb
 - nextant
 - passwords
 - user_external
 - user_saml
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "oca32fe9a93f",
    "trusted_domains": [
        "127.0.0.1",
        "10.10.20.22",
        "cloud.xxxx.de",
        "cloud.xxxx24.de"
    ],
    "datadirectory": "\/OWNCLOUD-DATA\/opt\/data",
    "tempdirectory": "\/OWNCLOUD-DATA\/opt\/tmp\/nextcloud",
    "dbtype": "mysql",
    "version": "11.0.1.2",
    "dbname": "bitnami_owncloud",
    "dbhost": "127.0.0.1",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "log_authfailip": false,
    "cron_log": true,
    "check_for_working_webdav": false,
    "check_for_working_htaccess": false,
    "appcodechecker": false,
    "updatechecker": true,
    "appstoreenabled": true,
    "appstore.experimental.enabled": true,
    "knowledgebaseenabled": true,
    "loglevel": 2,
    "asset-pipeline.enabled": false,
    "mail_smtpmode": "smtp",
    "mail_smtphost": "xxxxxxxx",
    "mail_smtpport": "4425",
    "mail_from_address": "owncloud",
    "mail_domain": "cloud.xxxd.de",
    "mail_smtpdebug": false,
    "theme": "",
    "maintenance": false,
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "ldapIgnoreNamingRules": false,
    "logtimezone": "Europe\/Berlin",
    "log_rotate_size": 902400,
    "forcessl": false,
    "secret": "***REMOVED SENSITIVE VALUE***",
    "xframe_restriction": false,
    "allow_user_to_change_display_name": false,
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": "false",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "\/var\/run\/redis\/redis.sock",
        "port": 0,
        "timeout": 0,
        "dbindex": 0
    },
    "trashbin_retention_obligation": "auto, 30",
    "defaultapp": "files",
    "activity_expire_days": 30,
    "enable_previews": true,
    "lost_password_link": "https:\/\/mail.xxxxd.de\/ecp\/?rfr=owa&p=PersonalSettings\/Password.aspx",
    "versions_retention_obligation": "auto, 30",
    "htaccess.RewriteBase": "\/",
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "auth.bruteforce.protection.enabled": false,
    "token_auth_enforced": false,
    "integrity.check.disabled": true
}
```
</details>

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OCA\Files_External\Lib\Storage\FTP
    [2] => \OC\Files\Storage\DAV
    [3] => \OCA\Files_External\Lib\Storage\OwnCloud
    [4] => \OCA\Files_External\Lib\Storage\SFTP
    [5] => \OCA\Files_External\Lib\Storage\AmazonS3
    [6] => \OCA\Files_External\Lib\Storage\Dropbox
    [7] => \OCA\Files_External\Lib\Storage\Google
    [8] => \OCA\Files_External\Lib\Storage\Swift
    [9] => \OCA\Files_External\Lib\Storage\SFTP
    [10] => \OCA\Files_External\Lib\Storage\SMB
    [11] => \OCA\Files_External\Lib\Storage\SMB
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
	<summary>LDAP config</summary>

	```
	With access to your command line run e.g.:
	sudo -u www-data php occ ldap:show-config
	from within your Nextcloud installation folder

	Without access to your command line download the data/owncloud.db to your local
	computer or access your SQL server remotely and run the select query:
	SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


	Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
	```
</details>
### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; rv:51.0) Gecko/20100101 Firefox/51.0

**Operating system:**

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	Insert your webserver log here
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
	Insert your Nextcloud log here
	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
	Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
	```
</details>

**Comment by MorrisJobke** [comment]
cc @nickvergessen @schiessle

**Comment by coderobe** [comment]
This bug seems to occur when a previously remotely unshared share is reshared to you

**Comment by mattronix** [comment]
We at weho.st have the same issue what we have noticed accepting shares gives that error and the following error:

Call to a member function file_exists() on null at /var/www/nextcloud/lib/private/legacy/helper.php#346

and error:

Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0

On a test server with identical settings and PHP we do not have this issue or these errors another interesting thing from the server that cannot accept shares it can still share with other servers with no issue. 

Let me know if i can give any useful information or test anything :)

**Comment by mattronix** [comment]
@coderobe  i seem to have it with new or unshared/reshared files.

**Comment by mattronix** [comment]
Another interesting note it seems like link sharing no longer works on the top level directory but it does work on sub directories for shares i tried to federate and unshared.
<img width="777" alt="screen shot 2017-03-01 at 4 39 12 pm" src="https://cloud.githubusercontent.com/assets/1733023/23467267/da94f0b6-fe9d-11e6-94d1-07a4d94b2641.png">

**Comment by nickvergessen** [comment]
@schiessle and me both tested this on friday and couldn't reproduce

Maybe it's some proxy settings that are not working as expected?

**Comment by mattronix** [comment]
Indeed possible but the same proxy setup works on one environment and not the other both are configured identicaly.  

If you want i can make an account so you can see first hand?  

If that would help?  

--  
Matthew Frost

**Comment by drycoffee** [comment]
I have the same issue and there is no proxy involved.

I dug a bit in the code and found out, that the problem is, that `$view = \OC\Files\Filesystem::getView();` yields null for some reason.

I changed the function buildNotExistingFileName in lib/private/legacy/helper.php as follows:

```
public static function buildNotExistingFileName($path, $filename) {
                $view = \OC\Files\Filesystem::getView();
                if ($view === null) {
                 if ($pos = strrpos($filename, '.')) {
                        $name = substr($filename, 0, $pos);
                        $ext = substr($filename, $pos);
                } else {
                        $name = $filename;
                        $ext = '';
                }

                return $path . '/' . $name . '_' . time() . '_' . $ext; 
                }
                return self::buildNotExistingFileNameForView($path, $filename, $view);
        }
```


With this dirty hack I can accept the incoming shares without any problem, so this seems to be a bug and no networking issue.

I'm running nextcloud 11.0.2.7 on ubuntu 16.04.2 LTS with PHP 7.0.15

**Comment by Huster-at-github** [comment]
> I changed the function buildNotExistingFileName in lib/private/legacy/helper.php as follows:

@drycoffee :+1: 

Thanks, that works for me also!

### Server configuration
**Operating system**: Linux owncloud 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.17

**PHP version:** 7.0.15-0ubuntu0.16.04.4
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, ldap, exif, mcrypt, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 11.0.2 (stable) - 11.0.2.7

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.4.1
 - activitylog: 0.0.1
 - admin_audit: 1.1.0
 - admin_notifications: 1.0.0
 - announcementcenter: 3.0.0
 - apporder: 0.3.3
 - audioplayer: 1.5.0-beta.4
 - bookmarks: 0.9.1
 - calendar: 1.5.1
 - comments: 1.1.0
 - contacts: 1.5.3
 - dav: 1.1.1
 - external: 1.2
 - federatedfilesharing: 1.1.1
 - federation: 1.1.1
 - files: 1.6.1
 - files_accesscontrol: 1.1.2
 - files_automatedtagging: 1.1.1
 - files_downloadactivity: 1.0.1
 - files_external: 1.1.2
 - files_markdown: 1.0.1
 - files_pdfviewer: 1.0.1
 - files_reader: 1.0.0
 - files_retention: 1.0.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - firstrunwizard: 2.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.1
 - keeweb: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.6.2
 - nextcloud_announcements: 1.0
 - notes: 2.2.0
 - notifications: 1.0.1
 - passman: 2.1.1
 - password_policy: 1.1.0
 - previewgenerator: 1.0.3
 - provisioning_api: 1.1.0
 - qownnotesapi: 17.3.0
 - rainloop: 4.27.0
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - spreed: 1.2.0
 - spreedme: 0.3.8
 - survey_client: 0.1.5
 - systemtags: 1.1.3
 - tasks: 0.9.5
 - templateeditor: 0.2
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - twofactor_totp: 1.1.0
 - twofactor_u2f: 1.1.0
 - updatenotification: 1.1.1
 - weather: 1.3.5
 - workflowengine: 1.1.1

**Comment by Huster-at-github** [comment]
But now have this  :-1: 

Shared file **Test_Dokument FederatedSharing.odt** for Myuser@mydomain.com:
Renamed to **Test_Dokument FederatedSharing_1489841591_.odt** at Myuser@mydomain.com:

```
Info	admin_audit	File accessed: "/Test_Dokument FederatedSharing_1489841591_.odt"
Debug	files_sharing	shareWith after, Myuser
Debug	files_sharing	shareWith before, Myuser
```

**Comment by dafrodo** [comment]
Same here.
the little hack helped, federation share is working now but the name of the shared folger got extended with _145683829.
i renamed the shared folder to the original name. now seems to work fine.

anyone got an idea why the renaming?

running NC 10.0.2.7

**Comment by nickvergessen** [comment]
Please update to 10.0.4

**Comment by dafrodo** [comment]
sorry i wrote the wrong version... 
i am running 11.0.2 not 10.0.2

**Comment by drycoffee** [comment]
@Huster-at-github @dafrodo 

That's why I called it a hack and not a fix. My function does not address the root cause, it's just a workaround to be able to accept shares. The renaming happens on purpose, it's a security measure.

Whenever you receive a shared file or folder the server usually checks if a file with the same name already exists and renames the file if necessary.
As the bug prevents the server from checking if a file by the name already exists, I added a unix timstamp into the filename to make sure that there are no collisions with pre-existing files (actually there still could be collisions, but it is less likely with the added timestamp).

If the timestamp bothers you, you have two options:

1. Simply rename the file back to it's original name after accepting it.

or

2. Change the function as follows:
`public static function buildNotExistingFileName($path, $filename) {
                $view = \OC\Files\Filesystem::getView();
                if ($view === null) {
                    return $path . '/' . $filename; 
                }
                return self::buildNotExistingFileNameForView($path, $filename, $view);
        }`

This will prevent the renaming, however collisions may occur. If so, you can rename the received file/folder manually to resolve the collision. It may be necessary to occ file:scan to retrieve the original files.

**Comment by Huster-at-github** [comment]
@drycoffee 

Thanks a lot for your explenation!

> "As the bug prevents the server from checking if a file by the name already exists,"

Is there any progress on this bug?

**Comment by drycoffee** [comment]
@Huster-at-github 

I don't have any more information on this than this ticket itself provides - there is nobody assigned yet, so I guess for now there's not much progress.

**Comment by runout-at** [comment]
I can confirm this bug here between 2 instances of NC 22.0.2
The workaround does partly work. I can accept the share but not access it (i think) because of the renamed folder: 'Storage is temporarily not available'. Renaming the folder does not work: 'Could not rename...'

For both, access and renaming i get following in the log:
> Sabre\DAV\Exception\ServiceUnavailable: HTTP/1.1 503 Storage is temporarily not available
> /var/lib/nextcloud/nextcloud/apps/dav/lib/Connector/Sabre/FilesPlugin.php - line 194: OCA\DAV\Connector\Sabre\ObjectTree->getNodeForPath('old_name_149080...')
> [internal function] OCA\DAV\Connector\Sabre\FilesPlugin->checkMove('old_name_149080...', 'new_name')
> /var/lib/nextcloud/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
> /var/lib/nextcloud/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 633: Sabre\Event\EventEmitter->emit('beforeMove', Array)
> [internal function] Sabre\DAV\CorePlugin->httpMove(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
> /var/lib/nextcloud/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
> /var/lib/nextcloud/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method MOVE', Array)
> /var/lib/nextcloud/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
> /var/lib/nextcloud/nextcloud/apps/dav/appinfo/v1/webdav.php - line 60: Sabre\DAV\Server->exec()
> /var/lib/nextcloud/nextcloud/remote.php - line 165: require_once('/var/lib/nextcl...')
> {main}

**Comment by nickvergessen** [comment]
Anyone willing to turn the "workaround" into a PR with descriptive reproduction steps?
Then we can have a look how to extend it.

**Comment by LEDfan** [comment]
I experienced the same problem yesterday, but for now I'm unable to reproduce it on my test instances. What happened yesterday is:
 1. I created an directory and shared with one person on another nextcloud instance
 2. Shared it with the problematic user 
 3. user says he didn't receive a notification
 4. I removed the user from the share and re-shared
 5. when clicking accept on the notification, the notification disappears but nothing happens and the error is logged.

I'll re-try to reproduce this.

**Comment by xraMsamohT** [comment]
> This bug seems to occur when a previously remotely unshared remote share is reshared to you

It also affects files that are shared for the first time.

```
TypeError: Argument 3 passed to OC_Helper::buildNotExistingFileNameForView() must be an instance of OC\Files\View, null given, called in /home/www/lib/private/legacy/helper.php on line 323 at /home/www/lib/private/legacy/helper.php#333
```

**Comment by nickvergessen** [comment]
@schiessle did we change something here for NC 11.0.3?

**Comment by schiessle** [comment]
not on purpose but maybe by accident?

**Comment by enoch85** [comment]
I'm also affected on 11.0.3, any update here?

**Comment by LEDfan** [comment]
I'm now running NC 12 beta3 on my server, and I'm experiencing the same problem with the specific other server.

**Comment by nickvergessen** [comment]
Can you test: `apps/files_sharing/lib/External/Manager.php`
find:
```php
$mountPoint = Files::buildNotExistingFileName('/', $share['name']);
```
before add:
```php
\OC_Util::setupFS($this->uid);
```

cc @juliushaertl

**Comment by juliushaertl** [comment]
@nickvergessen Yes that fixes it. :+1:

**Comment by nickvergessen** [comment]
Now the question is, why is the filesystem for some already loaded, but not for others.

I compared the app list, and I only have lesser apps than you. No additional app.

Anyway, can you turn this into a patch for 12 and master please?

**Comment by juliushaertl** [comment]
@nickvergessen just checked if it starts working by disabling apps. After disabling the previewgenerator app it started working again without any changes in code.

cc @rullzer

**Comment by enoch85** [comment]
Fixed it for me as well @nickvergessen
