### ISSUE TITLE
Theming: An admin should be able to disable account-specific customization completely

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#34561]
In the case of white labeling, an admin might not want their users to be able to change a branded background or to pick colors that are not compatible with it.

For this case, an admin should be able to disable this account-specific customization completely, if they would like to keep their cloud on-brand. This would be a setting in "Theming" called "Allow people to personalize their background and color". By default, the customization is enabled.

**Comment by PVince81** [comment]
- [ ] requires https://github.com/nextcloud/server/pull/34359

**Comment by CarlSchwan** [comment]
If we make it possible to hide theming completely, we should make sure that we can still change the accessibility options (high contrast and dyslexic font) otherwise if admins enable this option, they will kill their accessibility and I guess admin will want to have both...

**Comment by skjnldsv** [comment]
Yep, the goal is only to disable primary colour and background customization
