### ISSUE TITLE
Loading a non-existing js/css file may lead to csrf token errors

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#34575]
Encountered in https://github.com/nextcloud/text/pull/3175

Due to our default redirect to the login page users may experience using an invalid CSRF token while browsing a page if one of the requested assets does not exist and therefore redirects to the login page.

Investigation to be continued on the server side ...

**Comment by CarlSchwan** [comment]
We should return 404 already discussed in https://github.com/nextcloud/server/issues/33048#issuecomment-1170093596

**Comment by juliushaertl** [comment]
Then let me close this as a duplicate 🎉
