### ISSUE TITLE
No email notification after file share

### ISSUE THREAD

**Issue by periloung** [nextcloud/server#3458]
### Steps to reproduce
1. UserA share file to Userb
2. File sharing works
3. No email notifation

### Expected behaviour
UserB needs email notifation

### Actual behaviour
No email notication

### Server configuration
**Operating system**:
CentOS Linux release 7.3.1611 (Core)
**Web server:**
Apache
**Database:**
Mysql
**PHP version:**
PHP 5.6.30
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 11.0.1 (stable)
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
nextcloud-11.0.1.zip from https://nextcloud.com/install/
**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
Enabled:
  - activity: 2.3.2
  - audioplayer: 1.4.1
  - bookmarks: 0.9.0
  - calendar: 1.4.1
  - comments: 0.3.0
  - configreport: 0.1.1
  - contacts: 1.5.1
  - dav: 0.2.7
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - ojsxc: 3.0.1
  - ownbackup: 16.11.0
  - ownnote: 1.08
  - provisioning_api: 0.5.0
  - richdocuments: 1.1.17
  - shorten: 0.0.15
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - updatenotification: 0.2.1
Disabled:
  - encryption
  - external
  - files_antivirus
  - files_external
  - user_external
  - user_ldap

</details>

**The content of config/config.php:**
<details>
{
    "system": {
        "instanceid": "ocgoqpajbkai",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "oc.ciseventsgroup.com"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/oc.ciseventsgroup.com",
        "dbtype": "mysql",
        "version": "9.1.4.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Moscow",
        "cron_log": true,
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "owncloud",
        "mail_domain": "emag.ru",
        "mail_smtphost": "relay.emag.ru",
        "mail_smtpport": "25",
        "loglevel": 0
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
### Client configuration
**Browser:**
Chrome 56 on Windows 10
**Operating system:**
Windows 10 x64
#### Web server error log
<details>
<summary>Web server error log</summary>
[Sun Feb 12 11:00:46.881003 2017] [proxy:error] [pid 16359] [client 185.18.6.145:27081] AH00898: Error reading from remote server returned by /http-bind/
[Sun Feb 12 11:01:12.869513 2017] [authz_core:error] [pid 16275] [client 185.18.6.145:18818] AH01630: client denied by server configuration: /var/www/html/nextcloud/data/.ocdata
[Sun Feb 12 11:02:13.952526 2017] [proxy_http:error] [pid 15855] (70007)The timeout specified has expired: [client 185.18.6.145:18817] AH01102: error reading status line from remote server localhost:5280
[Sun Feb 12 11:02:13.952562 2017] [proxy:error] [pid 15855] [client 185.18.6.145:18817] AH00898: Error reading from remote server returned by /http-bind/
[Sun Feb 12 11:03:14.399051 2017] [proxy_http:error] [pid 15855] (70007)The timeout specified has expired: [client 185.18.6.145:18817] AH01102: error reading status line from remote server localhost:5280
[Sun Feb 12 11:03:14.399089 2017] [proxy:error] [pid 15855] [client 185.18.6.145:18817] AH00898: Error reading from remote server returned by /http-bind/
[Sun Feb 12 11:04:14.471528 2017] [proxy_http:error] [pid 15855] (70007)The timeout specified has expired: [client 185.18.6.145:18817] AH01102: error reading status line from remote server localhost:5280
[Sun Feb 12 11:04:14.471584 2017] [proxy:error] [pid 15855] [client 185.18.6.145:18817] AH00898: Error reading from remote server returned by /http-bind/
[Sun Feb 12 11:06:46.523551 2017] [proxy_http:error] [pid 16540] (70007)The timeout specified has expired: [client 185.18.6.145:15784] AH01102: error reading status line from remote server localhost:5280
[Sun Feb 12 11:06:46.523596 2017] [proxy:error] [pid 16540] [client 185.18.6.145:15784] AH00898: Error reading from remote server returned by /http-bind/
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	InvalidArgumentException: The given object name is invalid
/var/www/html/nextcloud/apps/activity/lib/FilesHooks.php - line 892: OC\Activity\Event->setObject('files', 74, false)
/var/www/html/nextcloud/apps/activity/lib/FilesHooks.php - line 184: OCA\Activity\FilesHooks->addNotificationsForUser('mile', 'created_self', Array, 74, false, true, true, 0, 'file_created')
/var/www/html/nextcloud/apps/activity/lib/FilesHooks.php - line 111: OCA\Activity\FilesHooks->addNotificationsForFileAction('/', 'file_created', 'created_self', 'created_by')
/var/www/html/nextcloud/apps/activity/lib/FilesHooksStatic.php - line 45: OCA\Activity\FilesHooks->fileCreate('/')
[internal function] OCA\Activity\FilesHooksStatic fileCreate(Array)
/var/www/html/nextcloud/lib/private/legacy/hook.php - line 106: call_user_func(Array, Array)
/var/www/html/nextcloud/lib/private/Files/View.php - line 1237: OC_Hook emit('OC_Filesystem', 'post_create', Array)
/var/www/html/nextcloud/lib/private/Files/View.php - line 1163: OC\Files\View->runHooks(Array, '/mile/files', true)
/var/www/html/nextcloud/lib/private/Files/View.php - line 266: OC\Files\View->basicOperation('mkdir', '/mile/files', Array)
/var/www/html/nextcloud/lib/private/Files/Node/Folder.php - line 149: OC\Files\View->mkdir('/mile/files')
/var/www/html/nextcloud/lib/private/Files/Node/Root.php - line 380: OC\Files\Node\Folder->newFolder('/mile/files')
[internal function] OC\Files\Node\Root->getUserFolder('mile')
/var/www/html/nextcloud/lib/private/Files/Node/LazyRoot.php - line 65: call_user_func_array(Array, Array)
/var/www/html/nextcloud/lib/private/Files/Node/LazyRoot.php - line 282: OC\Files\Node\LazyRoot->__call('getUserFolder', Array)
/var/www/html/nextcloud/lib/private/Server.php - line 947: OC\Files\Node\LazyRoot->getUserFolder('mile')
/var/www/html/nextcloud/lib/private/User/Session.php - line 411: OC\Server->getUserFolder('mile')
/var/www/html/nextcloud/lib/private/User/Session.php - line 479: OC\User\Session->prepareUserLogin(true)
/var/www/html/nextcloud/lib/private/User/Session.php - line 299: OC\User\Session->loginWithPassword(*** sensitive parameters replaced ***)
/var/www/html/nextcloud/core/Controller/LoginController.php - line 244: OC\User\Session->login(*** sensitive parameters replaced ***)
[internal function] OC\Core\Controller\LoginController->tryLogin(*** sensitive parameters replaced ***)
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Core\Controller\LoginController), 'tryLogin')
/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Core\Controller\LoginController), 'tryLogin')
/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('LoginController', 'tryLogin', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/html/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/html/nextcloud/lib/base.php - line 1010: OC\Route\Router->match('/login')
/var/www/html/nextcloud/index.php - line 40: OC handleRequest()
{main}
</details>

**Comment by nickvergessen** [comment]
You are using activity app version 2.3 which only works on Nextcloud 10.
For Nextcloud 11 you need version 2.4+ Please make sure you correctly replace all apps when updating your nextcloud

**Comment by periloung** [comment]
Thank you for your reply . That was a fresh  download and install on  a new VM  .
I installed 9.5 already . In that version users can send emails when share . 
I'll Thy to install 11  version near , and  check the activity app version  .

**Comment by MorrisJobke** [comment]
https://github.com/nextcloud/server/pull/5897 😉
