### ISSUE TITLE
Widgets in Talk: Show Pictures from more sources

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/server#34580]
Follow up: https://github.com/nextcloud/server/pull/33494
e.g. from Blog Articles and from invidio.us (youtube is working great):
![image](https://user-images.githubusercontent.com/24530680/195614504-d1e50ef6-d572-42da-8cf9-182138cd2f0f.png)

![image](https://user-images.githubusercontent.com/24530680/195614605-02dd7c6c-9247-4933-bc3f-3a9dd52988ce.png)

**Comment by szaimen** [comment]
cc @juliushaertl

**Comment by juliushaertl** [comment]
The default image is taken from open graph data, so this is up to the website to set an image which will then be used for the preview: https://ogp.me 

https://www.opengraph.xyz is quite helpful for testing if a website supports it. 

Our website seems to work fine at least now with the blogpost you linked:

![Screenshot 2022-10-13 at 15 56 22](https://user-images.githubusercontent.com/3404133/195616940-bc508921-61b3-436e-b236-6ac28682d0ab.png)
