### ISSUE TITLE
When set higher quote to user than 8 GB, user still has have fixed 8 GB quote.

### ISSUE THREAD

**Issue by ijurisic** [nextcloud/server#3459]
### Steps to reproduce
1. Log in Nextcloud then go in User list
2. For Specific user change Quota from 1 GB to 40 GB
3. In Nextcloud client I see limit Quota of 8 GB

### Expected behaviour
I try to set quota by user at 40 GB and expect to have for that user quota 40 GB.
![quota](https://www.jurisic.org/nextcloud/index.php/s/oIWXwMvpS2VqYkG/download)

### Actual behaviour
User have report by client to have 8 GB and also when go in browser under Personal I see : You are using 18.9 MB of 8 GB
![quota](https://www.jurisic.org/nextcloud/index.php/s/b3feMpZyNtWfWhU/download)
![client](https://www.jurisic.org/nextcloud/index.php/s/tkS15QDbGsacpn1/download)

### Server configuration
**Operating system**: Debian 8.7 (Jessie)

**Web server:** Apache/2.4.10

**Database:** PostgreSQL 9.4

**PHP version:** PHP 5.6.30

**Nextcloud version:** Nextcloud 11.0.1 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-11.0.1.zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.4.1
  - calendar: 1.5.0
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - direct_menu
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - mail
  - ojsxc
  - richdocuments
  - templateeditor
  - user_external
  - user_saml

</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "ocwgq4wb9xkz",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.jurisic.org"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/www.jurisic.org\/nextcloud",
        "dbtype": "pgsql",
        "version": "11.0.1.2",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "mail_smtpsecure": "ssl"
    }
}

</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

+-------------------------------+--------------------------------------------------------------+
| Configuration                 | s01                                                          |
+-------------------------------+--------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                              |
| hasPagedResultSupport         |                                                              |
| homeFolderNamingRule          | attr:uid                                                     |
| lastJpegPhotoLookup           | 0                                                            |
| ldapAgentName                 | ***REMOVED SENSITIVE VALUE***                                |
| ldapAgentPassword             | ***REMOVED SENSITIVE VALUE***                                |
| ldapAttributesForGroupSearch  |                                                              |
| ldapAttributesForUserSearch   |                                                              |
| ldapBackupHost                |                                                              |
| ldapBackupPort                |                                                              |
| ldapBase                      | ***REMOVED SENSITIVE VALUE***                  |
| ldapBaseGroups                | ***REMOVED SENSITIVE VALUE***               |
| ldapBaseUsers                 | ***REMOVED SENSITIVE VALUE***                |
| ldapCacheTTL                  | 600                                                          |
| ldapConfigurationActive       | 1                                                            |
| ldapDynamicGroupMemberURL     |                                                              |
| ldapEmailAttribute            | mail                                                         |
| ldapExperiencedAdmin          | 0                                                            |
| ldapExpertUUIDGroupAttr       |                                                              |
| ldapExpertUUIDUserAttr        |                                                              |
| ldapExpertUsernameAttr        |                                                              |
| ldapGroupDisplayName          | cn                                                           |
| ldapGroupFilter               | (&(|(objectclass=posixGroup))(|(cn=nextcloud)))              |
| ldapGroupFilterGroups         | nextcloud                                                    |
| ldapGroupFilterMode           | 0                                                            |
| ldapGroupFilterObjectclass    | posixGroup                                                   |
| ldapGroupMemberAssocAttr      | memberUid                                                    |
| ldapHost                      | 127.0.0.1                                                    |
| ldapIgnoreNamingRules         |                                                              |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(|(uid=%uid)(|(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                              |
| ldapLoginFilterEmail          | 1                                                            |
| ldapLoginFilterMode           | 1                                                            |
| ldapLoginFilterUsername       | 1                                                            |
| ldapNestedGroups              | 0                                                            |
| ldapOverrideMainServer        |                                                              |
| ldapPagingSize                | 500                                                          |
| ldapPort                      | 389                                                          |
| ldapQuotaAttribute            |                                                              |
| ldapQuotaDefault              |                                                              |
| ldapTLS                       | 0                                                            |
| ldapUserDisplayName           | cn                                                           |
| ldapUserDisplayName2          |                                                              |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))                               |
| ldapUserFilterGroups          |                                                              |
| ldapUserFilterMode            | 0                                                            |
| ldapUserFilterObjectclass     | inetOrgPerson                                                |
| ldapUuidGroupAttribute        | auto                                                         |
| ldapUuidUserAttribute         | auto                                                         |
| turnOffCertCheck              | 0                                                            |
| turnOnPasswordChange          | 1                                                            |
| useMemberOfToDetectMembership | 1                                                            |
+-------------------------------+--------------------------------------------------------------+

</details>

### Client configuration

**Browser:** Chromium Version 56.0.2924.76

**Nextcloud Client:** Version 2.2.4 , Built from Git revision eaeed0 on Feb 7 2017, 20:21:04 using Qt 5.3.2, OpenSSL 1.0.1t 3 May 2016

**Operating system:** Debian 8 Jessie

**Comment by ijurisic** [comment]
I add picture for better understand of this problem.

**Comment by ijurisic** [comment]
I find what is problem. Free space of 8 GB in my case is free space on my partition data. After moving data on bigger partition all is ok. Plase close this issue as close.

**Comment by bittner** [comment]
Sorry, totally unrelated: (But no idea how to get in touch with you, Ivan, otherwise)

@ijurisic Do you have a public repository of the packaging code for [your Debian repository](https://apt.jurisic.org/) for Nextcloud?

I have installed Nextcloud 12 on Debian 9.1 Stretch today. This is generally successful, but

- a few packages are missing as dependencies (`php-mbstring`, `php-zip`), and ideally
- we should add a VirtualHost configuration or set up Nextcloud as the default host.
