### ISSUE TITLE
Copy Links at a mobile device

### ISSUE THREAD

**Issue by mar1u5** [nextcloud/server#346]
### Expected behavior
Links should be copyable, so that you can put them into CalDAV/CardDAV-configuration of your phone or your tablet or to share links

### Actual behavior
It is not possible to copy them correctly 😢 

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
9.0.52

### Client configuration
**Browser:**
Safari
**Operating system:**
iOS 9.3

**Comment by mar1u5** [comment]
Fix is already in core: https://github.com/owncloud/core/pull/25418

**Comment by rullzer** [comment]
Fixed in NC10 => closing
