### ISSUE TITLE
[Bug]: "Eye" icon on login removes the password instead of converting its state

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/server#34611]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The eye icon removes the value from the password field:

![login issue](https://user-images.githubusercontent.com/7427347/195864264-388e29ec-1d17-4850-9cf2-fc36cd1c57db.gif)

also confirmed by @ChristophWurst on c.nc

### Steps to reproduce

1. Autofill or enter your password, both have this issue
2. Try to see / unsee your password
3. Password disappears

### Expected behavior

The password is still filled

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
-
```

**Comment by szaimen** [comment]
Cc @nextcloud/frontenders

**Comment by Pytal** [comment]
Discovered and fixed in https://github.com/nextcloud/server/pull/34541 due to failing acceptance tests, stable25 backport in https://github.com/nextcloud/server/pull/34590
