### ISSUE TITLE
[Bug]: Error parsing activities' icons in Activity emails

### ISSUE THREAD

**Issue by borjxrroyo** [nextcloud/server#34635]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello there,

We have NextCloud installed in a server of our enterprise. When somebody makes changes, an Activity mail is sent to our corporate E-Mail. But when the list of activities is shown, icons are broken because Google tries to "proxify" the icons that are saved in the local machine. See attached:

![image](https://user-images.githubusercontent.com/72812865/196191266-f0237667-dbad-450d-8145-3816de9869e4.png)

### Steps to reproduce

1. To have the icons saved locally.
2. To receive an email from the server where they are allocated.

### Expected behavior

To see correctly the activities' icons.

### Installation method

Other Community project

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.3

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
n/a
```

**Comment by szaimen** [comment]
Isnt this rather of google parsing?

**Comment by szaimen** [comment]
Please ask this on https://help.nextcloud.com. Thanks!
