### ISSUE TITLE
[Bug]: Contact stop showing under contact menu when unchecking allow autocompletion when entering full name or email address 

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/server#34637]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello so i noticed once i deselected the highlighted below user stop showing under the Contact search. The while goal was to select Allow username autocompletion to users within the same group to only show users that that are in the same group for example if i have some external users. I don't want my external users to see internal users this part dose work but the contacts search menu dose display anything. If do select the below highlighted then they appear back

![image](https://user-images.githubusercontent.com/59488153/196203744-a3233040-76bc-42eb-afa7-a0692583b58c.png)

![image](https://user-images.githubusercontent.com/59488153/196203911-a261776b-c839-49d5-b75e-3b69d48f161c.png)

### Steps to reproduce

1. Settings
2. Admin
3.Sharing
4.Select Allow username autocompletion to users within the same group 
5. deselect Allow autocompletion when entering the full name or email address (ingoing missing phonebook match and being in the same group 
6. Check Contact search  
7. all gone 

### Expected behavior

Should show users under the same group. 

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
NA
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by andyxheli** [comment]
Still effecting NC 25.0.3

**Comment by AndyXheli** [comment]
Still an issue NC 27

**Comment by AndyXheli** [comment]
fixed with https://github.com/nextcloud/server/pull/38907 tested on NC27.0.2
