### ISSUE TITLE
Ram slowly fills up when selecting profile picture from large nextcloud folder

### ISSUE THREAD

**Issue by VasilisThePikachu** [nextcloud/server#34638]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Go to settings
2. On the personal info page click on the folder to change image from a file in nextcloud storage
3. Select a huge folder, even if you don't choose anything the CPU and ram usage will start increasing and nextcloud will fully lockup until the containers are stopped or the host crashes

### Expected behavior 
Ram and CPU don't start spiking, nextcloud does not lock up

### Actual behavior 
Cpu usage spikes to 100% and memory causes the server to crash after running out

### Host OS 
Raspberry pi os 64bit on a pi, moved to another server with ubuntu 20.04 for troubleshooting with the same issue

#### Nextcloud AIO version 
2.0.4
#### Current channel 
latest
#### Other valuable info 
The folder the image was in was 1.4GB filled with other images
This does not happen seem to happen if the folder is not big (example root folder)
This may be a nextcloud issue and not a nextcloud aio issue, don't have a pure metal install to test out
My original setup on a pi had the data folder on an external HDD, on the new machine it's now an internal SATA SSD
Using Cloudflare Tunnels

Only apache container seems to show an error even though nextcloud container is the one filling up with ram
[_nextcloud-aio-apache_logs.txt](https://github.com/nextcloud/all-in-one/files/9801889/_nextcloud-aio-apache_logs.txt)

https://user-images.githubusercontent.com/34938708/196208852-d4287e1e-85cf-469a-9385-777ef79ba3f9.mp4

**Comment by CarlSchwan** [comment]
maybe the preview should be set to lazy so that not everything is generated when loading the filepicker....

**Comment by szaimen** [comment]
> maybe the preview should be set to lazy so that not everything is generated when loading the filepicker....

sounds good to me!

**Comment by VasilisThePikachu** [comment]
> You may use the preview generator for pre-generating thumbnails, though.

Unless I did it wrong (just ran occ preview:generate-all) then pre-generating thumbnails still cause issues

**Comment by szaimen** [comment]
Hi, please update to 25.0.7 or better 26.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 26-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
