### ISSUE TITLE
NC 25 - Theme-Colored Folder-Icons

### ISSUE THREAD

**Issue by SephGER** [nextcloud/server#34654]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
In the new NC25-Theme the thumbnail foldericons have a static greyish color. With this change the themes primary color could be used.

**Describe the solution you'd like**
Switch from the background-image css property to a combination of mask-image and background-color

**Describe alternatives you've considered**
Having multiple icon-sets which could be chosen

**Drawbacks**
If this is used globally for all icons the mime-type specific css would need additional background-color properties either fixed or via theme settings

**Additional context**
```
mask-image: url(/apps/theming/img/core/filetypes/folder.svg?v=16);
background: var(--color-primary);
mask-size: contain;
```
Right now:
![Screenshot 2022-10-18 at 14-31-34](https://user-images.githubusercontent.com/2600864/196430915-1368ed52-5109-4e33-9af6-ce5d26b06891.png)

With mask-image:
![Screenshot 2022-10-18 at 14-32-09](https://user-images.githubusercontent.com/2600864/196430722-6fc07620-5641-439b-9b99-0cf058a03646.png)

CSS-Change in Browser:
![Screenshot_20221018_143243](https://user-images.githubusercontent.com/2600864/196430840-3ad7ca9a-3c0a-4cf7-a962-63714a4e2e90.png)

**Comment by Jerome-Herbinet** [comment]
Probably the same problem as the one I detailed in this issue : #34578

**Comment by szaimen** [comment]
I can confirm this issue:
![image](https://user-images.githubusercontent.com/42591237/196548810-431ca74c-728a-445e-adf2-eef3b37f9e19.png)

**Comment by szaimen** [comment]
cc @nextcloud/server-frontend

**Comment by SephGER** [comment]
> Probably the same problem as the one I detailed in this issue : #34578

I just tried an reset the theme color to the default and now the folder color changed to another color that suits the bg-image. The #396475 color from before was after upgrading from 24 and having a custom color set in the global design settings. After setting the design color to a custom value again the folder color keeps the last color that was applied by the bg-image.

So it should either always be set with the bg-image and/or give the admin the possibility to set it to a static theme-color (or even a custom color field alongside the theme color?)

**Comment by szaimen** [comment]
@nextcloud/frontenders do you have some pointers on how to fix this?

**Comment by skjnldsv** [comment]
> @nextcloud/frontenders do you have some pointers on how to fix this?

Yes, because the user can also change the colour now, the cache buster needs to be using the user cache buster alongside the admin
See  https://github.com/nextcloud/server/blob/b9bbb25771fc704d0f5a9de7bc2ae0cae73cf81b/apps/theming/lib/Service/ThemeInjectionService.php#L90-L96

**Comment by skjnldsv** [comment]
Maybe having some methods to get cachebuster would be nice to have.

**Comment by szaimen** [comment]
Thanks @skjnldsv ! :)
Do you also have a pointer where the folder icons get generated or overwritten? I guess this is where the method then could get used as well to fix this issue.

Also cc @Pytal on this :)

**Comment by juliushaertl** [comment]
The icon is generated in https://github.com/nextcloud/server/blob/7dddbd0c355d1b4761466f9f86b30aed8b112ba1/apps/theming/lib/Controller/IconController.php#L88

The URL generation and adding the cache buster is done here:

https://github.com/nextcloud/server/blob/4a2bbc7af9249364ba2455f627522450262cad75/apps/theming/lib/ThemingDefaults.php#L418-L423

**Comment by szaimen** [comment]
@juliushaertl since you are familiar with this part of the code, could you maybe take a crack at this? Otherwise I will try :)

**Comment by juliushaertl** [comment]
I won't have time to dive further into this but a few more hints.

It seems the cache buster for mimetype icons is rather added here in the frontend:
https://github.com/nextcloud/server/pull/840/files#diff-d449dd50c36a47c4712a44ea7d00bdc21e58449f69f5d3c28c7fbc61c73146c7R109

- Make sure that the cache buster is extended with the user cache buster (like https://github.com/nextcloud/server/blob/19f35f42bcd527a08952681b07d84d008e583437/apps/theming/lib/Service/ThemeInjectionService.php#L94-L95)
- Properly pick the user color when generating the themed icon in https://github.com/nextcloud/server/blob/7dddbd0c355d1b4761466f9f86b30aed8b112ba1/apps/theming/lib/IconBuilder.php#L237 (this should already be the case with the getColorPrimary call
