### ISSUE TITLE
[Bug]: File actions menu links don't span over whole menu width

### ISSUE THREAD

**Issue by mejo-** [nextcloud/server#34653]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In `fileActionsMenu`, the action item links don't span over the whole menu width, which leads to a poor user experience:

![screenshot](https://user-images.githubusercontent.com/3582805/196435147-f26e1298-ba57-47a6-a2db-c71d369be8cd.png)

### Steps to reproduce

1. Open three-dot actions menu of a file in the files list
2. Hover over the white space after an item

### Expected behavior

The links should span over the whole menu width, so it's possible to click behind the text of an action (e.g. "Details").

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
files
```

**Comment by szaimen** [comment]
Screwnshot is not uploaded

**Comment by mejo-** [comment]
Haha, sorry. Not it's uploaded :blush:

**Comment by szaimen** [comment]
Please try again with 25.0.2

**Comment by mejo-** [comment]
Unfortunately still the same. The culprit is `width: fit-content` from https://github.com/nextcloud/server/commit/7801550d33b476505260e8bb6cea6acab95d0171. Seems like you added it on purpose to fix something else, but at least in the actions menu, removing it (or setting to `width: 100%`) solves the issue.

**Comment by szaimen** [comment]
> Unfortunately still the same. The culprit is `width: fit-content` from [7801550](https://github.com/nextcloud/server/commit/7801550d33b476505260e8bb6cea6acab95d0171). Seems like you added it on purpose to fix something else, but at least in the actions menu, removing it (or setting to `width: 100%`) solves the issue.

Did yoi test with the stable25 branch?

**Comment by szaimen** [comment]
@mejo- did you see https://github.com/nextcloud/server/pull/34886#issuecomment-1326850888? I tried to reproduce yesterday and couldnt...

**Comment by mejo-** [comment]
> Did yoi test with the stable25 branch?

The problem still exists on our company instance cloud.nextcloud.com. And that runs 25.0.2-rc2 to my knowledge.

| with `width: fit-content;` | without `width: fit-content;` |
|----|----|
| ![with_fit_content](https://user-images.githubusercontent.com/3582805/204507769-cde7ff59-731a-430e-8a9a-58473ab29c70.png) | ![without_fit_content](https://user-images.githubusercontent.com/3582805/204507775-ea8c29e5-0b7d-480d-ba09-7351b1c09369.png) |

**Comment by szaimen** [comment]
> > Did yoi test with the stable25 branch?
> 
> The problem still exists on our company instance cloud.nextcloud.com. And that runs 25.0.2-rc2 to my knowledge.
> 
> with `width: fit-content;`	without `width: fit-content;`
> ![with_fit_content](https://user-images.githubusercontent.com/3582805/204507769-cde7ff59-731a-430e-8a9a-58473ab29c70.png)	![without_fit_content](https://user-images.githubusercontent.com/3582805/204507775-ea8c29e5-0b7d-480d-ba09-7351b1c09369.png)

I see. Do you have any idea how to fix both, this issue and https://github.com/nextcloud/server/issues/33857? I welcome any suggestions :)

**Comment by mejo-** [comment]
Nope, unfortunately I lack the bandwidth to reproduce the issue with `files_external`. But in https://github.com/nextcloud/server/pull/34886#issuecomment-1301473777 @Pytal suggested to use narrower scoping for `.menuitem { width: fit-content; }` and while I didn't test their approach I agree it would be the way forward.

Since the rule applies to all items in `.popovermenu`, you need to decide whether `width: fit-content;` is a generic rule that is required *everywhere except*  `.fileActionsMenu` (then @Pytal's solution would be appropriate) - or whether it's a rule that is required *only for the files_external context* (then I'd introduce a new CSS class in the files_external menu and add the extra `width: fit-content;` rule in the app's realm).

**Comment by szaimen** [comment]
Found a fix that should work: https://github.com/nextcloud/server/pull/35484
