### ISSUE TITLE
Thumbnails of search results in other folders have different size

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#3466]
Check this screenshot – the search results in other folders have non-standard thumbnail sizes. They should be the same as the file list entries above:
<img width="1254" alt="bildschirmfoto 2017-01-11 um 14 52 07" src="https://cloud.githubusercontent.com/assets/5836855/22114934/60bd2878-de6b-11e6-98d6-353d82cdac26.png">

cc @nextcloud/designers (or @rullzer @icewind1991 maybe?)

**Comment by MorrisJobke** [comment]
Why do you have me as your avatar? 🤔

**Comment by jancborchardt** [comment]
Just nicked the screenshot from another issue you opened where I was reminded of the problem. So, good work ;D

**Comment by marncz** [comment]
I'd like to work on that issue as my fist contribution to the project :)

**Comment by marncz** [comment]
Think it may have been fixed already. Don't know if I did something wrong but the thumbnails seem to work just fine:

![image](https://cloud.githubusercontent.com/assets/9304594/23136529/14f4f39c-f795-11e6-82f1-e9146aa9ae42.png)

Tried different sizes of images but they still appear the same size as the ones above :)

**Comment by MorrisJobke** [comment]
Mmmh ... in Safari it looks like this for me (in both stable11 and master}:

![bildschirmfoto 2017-02-20 um 12 09 35](https://cloud.githubusercontent.com/assets/245432/23137063/8c0cd9ca-f765-11e6-8918-792f1d404b75.png)

**Comment by MorrisJobke** [comment]
The size is fixed by applying this:

```css
background-size: 32px;
```

to https://github.com/nextcloud/server/blob/master/core/search/css/results.css#L70-L72

@marncz Could you create a pull request for this? Sorry for taking the actual fix from you, but I actually was debugging it inside of the dev tools and want to share the solution :)

**Comment by MorrisJobke** [comment]
BTW: I have the same with Chrome. What browser do you use?

**Comment by marncz** [comment]
@MorrisJobke 

no worries, I'm glaid it's fixed :) and the browser I'm using is Chrome on Linux, forgot to check it on a different one

will work on something else then :)

**Comment by MorrisJobke** [comment]
Fix is in #3551
