### ISSUE TITLE
Update detection issues for files external

### ISSUE THREAD

**Issue by khlem** [nextcloud/server#3468]
Hello,

The files are not updated properly when you add an external drive (only with Nextcloud Client software)

Mount an external SMB drive or Windows share drive or local path, add files to your shared drive or local path. 
The files is updated to Web Client but not in Nextcloud Client software you must add a folder or a files to force the refresh.

The command : occ files:scan --all functions only for local folder not for SMB drive.

Debian 8.3.0
PHP 5.6.29-0
Nextcloud version 11.0.1
Mysql  Ver 14.14 Distrib 5.5.54

That issue is already present in Owncloud and never resolved (all version are impacted)

If you need more information don't hesitate to contact me.

Thx for your advice

**Comment by MorrisJobke** [comment]
> That issue is already present in Owncloud and never resolved (all version are impacted)

You can run a notify command that listens for changes and then you don't need to run a files scan regularly:

https://docs.nextcloud.com/server/12/admin_manual/configuration_files/external_storage/smb.html#smb-update-notifications
