### ISSUE TITLE
Filepicker: Show path set on create

### ISSUE THREAD

**Issue by susnux** [nextcloud/server#34693]
**Is your feature request related to a problem? Please describe.**
If you set a start path on the filepicker the path is not shown, meaning you can not go to the parent directory but have to navigate to the home directory first. (breadcrumb navigation for current directory missing).
See screenshots below

**Describe the solution you'd like**
Show same breadcrumb navigation as if you navigated to that directory

**Describe alternatives you've considered**
There is no viable workaround

**Additional context**
e.g. I have the directories: `/ A / B` and want to start picking a file in B in  (maybe because that was the last directory used)

### How it currently looks like (missing breadcrumb navigation)
![Filepicker without breadcrumb naviation](https://user-images.githubusercontent.com/1855448/196926993-6f643f71-7372-4408-8fed-f4dbc3c725b7.png)

### How it should look like (like if you navigated there manually)
![File picker with breadcrumb navigation](https://user-images.githubusercontent.com/1855448/196926812-6dba4d85-5592-4b46-aa99-db66e979a9d7.png)

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by susnux** [comment]
@szaimen This is valid for NC25 and current main branch

**Comment by szaimen** [comment]
Thanks!

**Comment by susnux** [comment]
Fixed with 27.1
