### ISSUE TITLE
allow to enter and differentiate more than one mobile phone number, e.g for business and private use

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#3469]
## Expected behavior
It should be possible to enter separate mobil phone numbers for business and private use, like it is already possible for fax numbers.

## Current behavior
Only one mobile phone number can be entered at the moment. Due to the fact that more and more people own at least a business and a private mobile phone, an option to differentiate mobile phones
for business and private use should be added.

### Steps to reproduce
1. Open the contacts app.
2. try to enter and differentiate more than one mobile phone number.

#### Server Configuration
OS: Linux 3.2.84
Web server: Apache2 2.4.25
Database: MariaDB 5.5.54
PHP version: 5.6.29
Nextcloud version: 11.0.1

#### Client Configuration
Browser: Mozilla Firefox 51.0.1
Operating system: Windows 7

**Comment by MorrisJobke** [comment]
As this is about the UI this should be opened in the contacts app: https://github.com/nextcloud/contacts/issues

Thanks
