### ISSUE TITLE
question about file count

### ISSUE THREAD

**Issue by berho** [nextcloud/server#3475]
Hello,

I installed NextCloud at my hosting provider and it works very well. I have unlimited webspace but the maximum number of files ist limited to ~260.000.

I have a lot of files but the count is much less as this limit. The problem is that Nextcloud create a lot of files in the background (caching, encryption, previews, ???) 

1. What can I do to limit the creation of such files?
1. What files/folders can I delete without getting troubles? (I found encrytion keys for files on external local storage where I don't set encryption!?)
1. Is there another encryption module not using as much files in the background as the default module? 
1. Why does modules not using the database behind?

Thanks!

**Comment by MariusBluem** [comment]
> What can I do to limit the creation of such files?

Not really anything. Nextcloud is needing not only your files and folders ... caching, previews and encryption need additional files to provide you an (optimal) experience. However:

- https://github.com/nextcloud/server/blob/master/config/config.sample.php#L824 gives you the possibility to disable previews
- Consider about Encryption

> What files/folders can I delete without getting troubles? (I found encrytion keys for files on external local storage where I don't set encryption!?)

You should **not** delete any file you think you "don't need" ... this can cause problems with your Instance. Please be careful!

> Is there another encryption module not using as much files in the background as the default module?

No.

> Why does modules not using the database behind?

Let's ask @nextcloud/encryption

**Comment by berho** [comment]
Then I think there is an error on external local storage without encryption!

I add an entry 'test' in the UI for testing this and unset the checkbox for encryption. After uploading several files to this new folder, I found an directory for each file in `'data/files_encryption/keys/files/test'` with keys for all of the users with access to this storage...
I checked the content of the files on the server and: they are encrypted!

How does the system react when there are files in the location and i change the encryption setting? I tried it but nothing happend...

**Comment by jknockaert** [comment]
> Why does modules not using the database behind?
That's actually a fairly interesting suggestion. Never thought of it, but it would definitely make sense in my opinion to store the keys in the database backend rather than in the filesystem.

**Comment by MorrisJobke** [comment]
> I add an entry 'test' in the UI for testing this and unset the checkbox for encryption. After uploading several files to this new folder, I found an directory for each file in 'data/files_encryption/keys/files/test' with keys for all of the users with access to this storage...
> I checked the content of the files on the server and: they are encrypted!

Then it looks like the encryption module is still active. Maybe disable the app and run the decrypt command from the CLI tool (occ encryption...).


As of now there is no way to delete some of those files. All are usually needed and deleting them doesn't make things better.



> Why does modules not using the database behind?

Please open a separate ticket for this. But I think a migration now is super hard and it's better to keep it as it is now.
