### ISSUE TITLE
Cannot declare class OCA\TwigacloudSignup\AppInfo\Application, because the name is already in use in /var/www/nextcloud/apps/twigacloud_signup/lib/AppInfo/Application.php.

### ISSUE THREAD

**Issue by brunoalfred** [nextcloud/server#34765]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I have cloned my app on /var/www/nextcloud/apps folder and when i reached out to the browser for any request made to NC instance i endup with blank(white page) response. When i check the nextcloud.log, the result is:

```json
{"reqId":"ROz2rWuxE0tLPLcffMAz","level":3,"time":"2022-10-24T08:36:41+00:00","remoteAddr":"172.17.17.167","user":"admin","app":"PHP","method":"GET","url":"/settings/apps","message":"Cannot declare class OCA\\TwigacloudSignup\\AppInfo\\Application, because the name is already in use at /var/www/nextcloud/apps/twigacloud_signup/lib/AppInfo/Application.php#13","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0","version":"24.0.6.1","data":{"app":"PHP"}}
{"reqId":"U9A8zSHfyH0PFeXKI0UK","level":3,"time":"2022-10-24T08:52:37+00:00","remoteAddr":"172.17.17.167","user":"admin","app":"PHP","method":"GET","url":"/settings/apps","message":"Cannot declare class OCA\\TwigacloudSignup\\AppInfo\\Application, because the name is already in use at /var/www/nextcloud/apps/twigacloud_signup/lib/AppInfo/Application.php#13","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:107.0) Gecko/20100101 Firefox/107.0","version":"24.0.6.1","data":{"app":"PHP"}}
```

Link to my app is [twigacloud_signup](https://github.com/brunoalfred/twigacloud_signup/).

### Steps to reproduce

1. Clone [twigacloud_signup](https://github.com/brunoalfred/twigacloud_signup/) to /var/www/nextcloud/apps location.
2. Then try to open NC instance on the Browser
3. 

### Expected behavior

I expected the NC instance to continue working and also find the added app in the List of my Apps

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - bruteforcesettings: 2.4.0
  - circles: 24.0.1
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.2.2
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.1
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - richdocuments: 6.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
Disabled:
  - calendar: 3.5.1
  - encryption
  - files_external
  - mail: 1.14.1
  - spreed: 14.0.5
  - user_ldap


I removed the App just to be able to list all the enabled applications.
```

**Comment by brunoalfred** [comment]
@nickvergessen i've seen you explaining about this... i think the apps related were sheet and talk... please could you share your thought on what was the probable cause...!

**Comment by brunoalfred** [comment]
i just changed the app id from twigacloud_signup to twigacloudsignup

**Comment by nickvergessen** [comment]
By removing the `_` the app certificate you requested does not match anymore. Also it should not matter at all.
I guess you just used a wrong namespace string
