### ISSUE TITLE
[Bug]: User list's display broken on users with many groups

### ISSUE THREAD

**Issue by Gwyll** [nextcloud/server#34784]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Users without group or with 2-3 groups are fine.

Users with many groups displayed wrongly. Text on text, spacing errors.

![kép](https://user-images.githubusercontent.com/24811683/197645188-5d88ec30-e723-42ac-9b4d-7b935c6d6b9e.png)
![kép](https://user-images.githubusercontent.com/24811683/197645221-61387280-ea3d-426e-89d2-dc5e8184d2c1.png)

### Steps to reproduce

1. Update to 25
2. Create eg. 10 groups
3. put a user in the created groups.

### Expected behavior

Should not overlay, should keep spacing.

### Installation method

Community Manual installation with Archive

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - admin_audit: 1.15.0
  - calendar: 4.0.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.1
  - contactsinteraction: 1.6.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_downloadactivity: 1.15.0
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - geoblocker: 0.5.7
  - impersonate: 1.11.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - passwords: 2022.10.20
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.2
  - settings: 1.7.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - activity: 2.11.0
  - announcementcenter: 6.4.0
  - bruteforcesettings: 2.4.0
  - dashboard: 7.5.0
  - encryption
  - extract: 1.3.5
  - files_retention: 1.14.0
  - files_trackdownloads: 1.11.0
  - fulltextsearch: 24.0.0
  - fulltextsearch_elasticsearch: 24.0.1
  - groupfolders: 13.0.0
  - logreader: 2.3.0
  - photos: 1.0.0
  - quota_warning: 1.14.0
  - ransomware_protection: 1.13.0
  - serverinfo: 1.8.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - suspicious_login
  - twofactor_totp
  - user_ldap
  - user_retention: 1.8.0
  - user_usage_report: 1.9.0
```

**Comment by Chartman123** [comment]
Can confirm this:

![image](https://user-images.githubusercontent.com/16020496/197764030-c8cebbac-5f9b-418c-8261-168388a5d7f9.png)

**Comment by Bluerazer71** [comment]
With 200 users and many groups, very confusing. In connection with the missing markings in the assignments, the whole thing is unfortunately almost impossible to edit. Exists in 25.0.0 as well as in 25.0.1
