### ISSUE TITLE
App name in Files app says »Apps« instead of »Files«

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#3479]
![capture du 2017-02-14 20-16-56](https://cloud.githubusercontent.com/assets/925062/22944921/a4fe8ca2-f2f2-11e6-92a1-5a6fe3d1cf24.png)

When did that happen @nextcloud/designers? Was it intentional?

**Comment by MorrisJobke** [comment]
> When did that happen @nextcloud/designers? Was it intentional?

Nope - ummm ... I can reproduce. Let's see.

**Comment by skjnldsv** [comment]
This is strange! 😕

**Comment by MorrisJobke** [comment]
I found it, but let me bisect the root cause for this to happen.

**Comment by MorrisJobke** [comment]
That is the commit that caused this: aa8755bd4b2d5a949a35f1308eefa6d00140a1a7

**Comment by MorrisJobke** [comment]
Fix is in #3487
