### ISSUE TITLE
Many errors in log

### ISSUE THREAD

**Issue by emillod** [nextcloud/server#3483]
### Steps to reproduce
1. Log in to NextCloud
2. Check logs in Administration

### Expected behaviour
Clear logs

### Actual behaviour
I have many errors! I send them below

### Server configuration
**Operating system**: Centos 7

**Web server:** Apache

**Database:** MySQL

**Nextcloud version:** 11.0.1.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - apporder: 0.3.3
  - calendar: 1.5.0
  - comments: 1.1.0
  - contacts: 1.5.2
  - dav: 1.1.1
  - direct_menu: 0.10.0
  - encryption: 1.4.1
  - external: true
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_downloadactivity: 1.0.0
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_reader: 0.8.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - issuetemplate: 0.2.0
  - keeweb: 0.3.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - ojsxc: 3.0.2
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - richdocuments: 1.1.25
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - audioplayer
  - files_automatedtagging
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml

</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "192.168.0.43",
            "cloud"
        ],
        "datadirectory": "\/var\/www\/html\/data",
        "overwrite.cli.url": "http:\/\/192.168.0.43",
        "dbtype": "mysql",
        "version": "11.0.1.2",
        "dbname": "cloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "mail_smtpmode": "smtp",
        "updater.release.channel": "stable",
        "maintenance": false
</details>

**Are you using external storage, if yes which one:** other nextcloud

**Are you using encryption:** yes

### Client configuration
**Browser:** Chrome

**Operating system:** Windows

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Illegal offset type at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#217	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	Undefined index: bugs at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#215	2017-02-14T21:56:57+0100
Error	PHP	get_browser(): browscap ini directive not set at /var/www/html/apps/issuetemplate/lib/Settings/Admin.php#262	2017-02-14T21:56:57+0100
Error	index	GuzzleHttp\Exception\RequestException: cURL error 3: <url> malformed	2017-02-14T21:47:43+0100
Error	no app in context	InvalidArgumentException: The given affected user is invalid	2017-02-14T21:47:43+0100
Error	no app in context	InvalidArgumentException: The given affected user is invalid	2017-02-14T17:54:09+0100
Error	no app in context	InvalidArgumentException: The given affected user is invalid	2017-02-14T17:54:08+0100
Error	no app in context	InvalidArgumentException: The given affected user is invalid	2017-02-14T17:54:06+0100
Error	core	Error while running background job (InvalidArgumentException): The given user id is invalid	2017-02-14T17:13:28+0100
Error	no app in context	InvalidArgumentException: The given affected user is invalid	2017-02-14T13:21:41+0100
Error	no app in context	InvalidArgumentException: The given affected user is invalid	2017-02-13T20:55:12+0100
Error	no app in context	InvalidArgumentException: The given affected user is invalid	2017-02-13T20:54:51+0100
Error	no app in context	InvalidArgumentException: The given affected user is invalid	2017-02-13T20:53:56+0100
Error	no app in context	InvalidArgumentException: The given affected user is invalid	2017-02-13T20:53:55+0100
Error	no app in context	InvalidArgumentException: The given affected user is invalid	2017-02-13T20:53:53+0100
Error	no app in context	InvalidArgumentException: The given affected user is invalid	2017-02-13T20:53:52+0100
Error	no app in context	InvalidArgumentException: The given affected user is invalid	2017-02-13T20:53:52+0100
Error	no app in context	InvalidArgumentException: The given affected user is invalid	2017-02-13T20:53:51+0100
Error	no app in context	InvalidArgumentException: The given affected user is invalid	2017-02-13T20:53:50+0100
Error	no app in context	InvalidArgumentException: The given affected user is invalid	2017-02-13T20:53:50+0100
Error	no app in context	InvalidArgumentException: The given affected user is invalid	2017-02-13T20:53:49+0100
Error	no app in context	InvalidArgumentException: The given affected user is invalid	2017-02-13T20:53:48+0100

</details>

**Comment by LukasReschke** [comment]
> bugs at /var/www/html/apps/issuetemplate/lib/Settings

@juliushaertl

**Comment by LukasReschke** [comment]
> Error	no app in context	InvalidArgumentException: The given affected user is invalid	2017-02-13T20:53:48+0100
> Error	core	Error while running background job (InvalidArgumentException): The given user id is invalid	2017-02-14T17:13:28+0100

Did you by any chance delete users or use LDAP or so?

**Comment by emillod** [comment]
For know i can't use LDAP. You want me to delete all users?? And how i can after that using nextcloud ?

**Comment by LukasReschke** [comment]
> For know i can't use LDAP. You want me to delete all users?? And how i can after that using nextcloud ?

No. I was trying to ask if you have deleted users before that log message appeared :)

**Comment by emillod** [comment]
Ahhhh sorry 😃 
No... i have all the same users from the beginning..
I have the same errors in others NextCloud instances.. 😞

**Comment by emillod** [comment]
@LukasReschke 
Do you have any ideas ? 😄

**Comment by juliushaertl** [comment]
@emillod The logspam has already been fixed in https://github.com/juliushaertl/issuetemplate/issues/13 and https://github.com/juliushaertl/issuetemplate/issues/14. I'll release a new version with those fixes included soon.

**Comment by emillod** [comment]
Great, thanks!
