### ISSUE TITLE
Subquery inside IN must not use additional () on the createFunction() call or it breaks in SQLite

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#34836]
And seems there are at least 2 others in server (middle one is not an IN, so it might still work?):
![image](https://user-images.githubusercontent.com/213943/197484079-aa971ea6-f70c-488d-808f-943e689602d8.png)

So we should try to find a programmatic way to prevent this.
Can you raise a tech debt ticket in the server about it?

_Originally posted by @nickvergessen in https://github.com/nextcloud/spreed/issues/8220#issuecomment-1288651806_

**Comment by nickvergessen** [comment]
cc @nextcloud/server-backend for your knowledge

**Comment by PVince81** [comment]
if something breaks it's more a bug than technical debt ?
or was it like that since years and only started breaking right now ?

**Comment by nickvergessen** [comment]
yeah well, so it's both. A bug to fix existing places, a tech debt to find a way to prevent it from happening forward

**Comment by PVince81** [comment]
@come-nc can you have a look ?

**Comment by come-nc** [comment]
The from does not add parenthesis so does not need fixing.
The PR fixes the two other instances of extra parenthesis in IN clause.
