### ISSUE TITLE
11.0.1 shift click bulk select odd behaviour

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/server#3484]
When clicking on a file, holding shift and clicking further down, it always tries to select from the very top.
Similarly when clicking on a file low down, holding shift and clicking a file higher up, it selects from the top to the file rather than from the bottom.

Here are examples:
https://youtu.be/bw3aCo9QSbU

https://youtu.be/ngwYFH70YcA

### Expected behaviour
It should simply select from the first file/folder clicked, to the last.

### Server configuration
**Operating system**: Ubuntu 16.04.2

**Web server:** Apache

**Database:** Maria

**PHP version:** 7

**Nextcloud version:** 11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Update

**Comment by nickvergessen** [comment]
@nextcloud/javascript anyone willing to have a look?

**Comment by jasonbayton** [comment]
I can replicate in 12.0.1.

**Comment by smirkybg** [comment]
This is still not working. What's holding this back? It used to be there...

**Comment by ccomb** [comment]
Just missed that feature in Nextcloud 15, trying to undelete +1000 files after an unwanted deletion... :-(

**Comment by Loafdude** [comment]
Yeah I must say this is a pretty major missing feature atm

**Comment by jcklpe** [comment]
Yo, just wanted to say this is really really needed. It's 2019 and I'm on version 16 and this still isn't back in?

**Comment by ChristophWurst** [comment]
> Yo, just wanted to say this is really really needed. It's 2019 and I'm on version 16 and this still isn't back in?

https://nextcloud.com/contribute/

**Comment by jcklpe** [comment]
Fair point. I'm not a good enough dev yet to contribute to this problem yet. But I will as soon as I can.

**Comment by smirkybg** [comment]
The things is, this is a regression and it used to work. It's not like we are asking for an enhancement :)

**Comment by ChristophWurst** [comment]
Yeah, it's actually also possible to contribute fixes :wink:

**Comment by szaimen** [comment]
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!

**Comment by avocadoVolcano** [comment]
We are on version Nextcloud 25.0.2.3 and this is still an issue. Thanks
