### ISSUE TITLE
Disable browser translation

### ISSUE THREAD

**Issue by raboof** [nextcloud/server#34857]
**Is your feature request related to a problem? Please describe.**

When Google Chrome detects text on a webpage that is in a language different from the browser language, it will offer to 'Google Translate' the page on-the-fly.

This is a bad fit for Nextcloud:
* First of all, Nextcloud has high-quality translations built-in, so it would be better if the user learned to enable those
* Second, when the language Nextcloud is currently using, the language used in the filenames and other contents in the Nextcloud instance, and the browser language don't align, this can lead to all kinds of confusing effects: for example, I saw one instance where the browser was set to Dutch and Nextcloud was set to English, but the filenames of files stored in Nextcloud were in Dutch. This led to Chrome proposing to translate from English to Dutch, which was confusing for the Nextcloud features (the properly-localized manual didn't match the interface anymore), but it also tried to interpret already-Dutch words (in this case 'Rooster.pdf', meaning 'Schedule') as English words, and translated them (in this case to 'Haan.pdf', since the *English* word Rooster translates to Haan in Dutch).

**Describe the solution you'd like**
I would like us to add `translate="no"` to the top-level `html` tag. I tested this on a test page, and confusingly this will still show the 'Google Translate' icon in the address bar, but at least it won't create wrong/confusing translations anymore. See also: https://stackoverflow.com/questions/12238396/how-to-disable-google-translate-from-html-in-chrome

**Describe alternatives you've considered**
Automatically switching the Nextcloud language to the Browser language might make this problem less prevalent, but not reliably, especially when there is content in the non-browser-language.

**Comment by raboof** [comment]
Hmm, this doesn't appear to have the desired effect on Firefox, even though AFAICS https://caniuse.com/mdn-html_global_attributes_translate suggests it should.

Perhaps there it only applies to direct children, and not transitively?

**Comment by Amunak** [comment]
It does seem like the correct course here would have been to only mark elements that should not be translated as untranslatable (i.e. file names and perhaps contents), but not the whole pages and certainly not pages unrelated to stored files.

**Comment by raboof** [comment]
> Therefore could this be a setting or something?

That might make sense

> To be honest I'm still confused about the original rationale, I'm always finding myself in mixed language webpages where I need the browser translations.

In my experience in those cases the translation does more harm than good, like in the example where having the browser translate from "English to Dutch" it would also 'translate' words that were already in Dutch, leading to unintelligible results. 

> It does seem like the correct course here would have been to only mark elements that should not be translated as untranslatable (i.e. file names and perhaps contents), but not the whole pages

Translating only the 'Nextcloud strings' and not the 'user content' does not make sense to me, because Nextcloud already ships with human-curated translations for the 'Nextcloud strings', which will definitely be superior than what a browser would come up with. If I understand correctly it would also not solve the use case mentioned by @ProbablePrime , who AFAICT actually _wanted_ the 'user content' to be translated...

**Comment by ProbablePrime** [comment]
For some clarity, my team wrote a form to be used as a survey for our users. Some of our users do not speak english. So they wanted to translate the survey questions into their language using the browser translations.

We could do this on our end, surfacing different surveys for different languages but, we can't cover all languages so the survey's questions being browser translatable filled in the gaps.


That's my usecase at least, I hope reading about it helps in understanding the issue here.
