### ISSUE TITLE
Search results from other folders: Don’t repeat file name in second line

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#3486]
Check the search results from other folders:
<img width="1254" alt="bildschirmfoto 2017-01-11 um 14 52 07" src="https://cloud.githubusercontent.com/assets/5836855/22114934/60bd2878-de6b-11e6-98d6-353d82cdac26.png">

We don’t need to repeat the file name in the second line with the folder path. It’s already in the first line. ;)

cc @nextcloud/javascript

**Comment by MorrisJobke** [comment]
@stephanruttloff 😉

**Comment by EricHeinrichSchneider** [comment]
Hey i would like to contribute to the project and take the issue as my "starter issue".

**Comment by MorrisJobke** [comment]
> Hey i would like to contribute to the project and take the issue as my "starter issue".

Nice :) You can find most of the UI of the search in `core/search` - https://github.com/nextcloud/server/tree/master/core/search

Feel free to ask questions if something is unclear. We are also happy to help via IRC: #nextcloud-dev on free node. (Most of our names are the same as on github and just ping me and I can delegate to other people ;))

**Comment by MorrisJobke** [comment]
It seems to be the renderer from the files app:

https://github.com/nextcloud/server/blob/a45cfbc2d2754030510ac98607ca2cc53d750b57/apps/files/js/search.js#L83
https://github.com/nextcloud/server/blob/a45cfbc2d2754030510ac98607ca2cc53d750b57/apps/files/js/search.js#L66

**Comment by MorrisJobke** [comment]
Fixed in #3557
