### ISSUE TITLE
[Bug]: New files in External Storage do not appear in NextCloud Immediately

### ISSUE THREAD

**Issue by jthomson-blackbird** [nextcloud/server#34863]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I've searched through existing issues and cannot seem to find a matching issue.

NextCloud is configured on a Server with MySQL and Redis Cache. Server is a Linux VM, 4 CPU and 8GB RAM, with lots of disk capacity.

There are a number of External Storages configured. SMB shares that are mounted to the server via fstab, and configured as External Storages in NextCloud to their mount points. It is configured this way as when the server was initially setup, the required PHP modules were installed, but not detected by NextCloud, to allow for mounting the shares via NextCloud.

This issue has persisted through a number of updates to NextCloud and has occurred irrespective of OS, PHP and NextCloud versions.

The issue found is that when a file is added from the SMB side (not via NextCloud), it takes a long time for the file to appear in the NextCloud web interface and apps. I believe this may be due to the fact that there a significant number of files, so indexing is taking a long time. The file is not ever moved or deleted and remains on the SMB side in view.

I can run `occ files:scan`, but due to the number of files, this takes a very, very long time due to the number of files. This has resulted in files becoming visible on the web interface and the only time I can really run this is on a weekend due to the time it takes.

So in summary, what can be done to tweak NextCloud (or more likely, MySQL), so speed up files coming from the SMB side being visible? Can MySQL be given more CPU cores to use? Is it redis? Is this just a symptom of having so many files and it is unavoidable?

### Steps to reproduce

1. Configure SMB file shares via fstab (SMB shares should have large number of files)
2. Configure External Storage on a NextCloud Server to the local mount points
3. After initial indexing(?), add new files from the SMB side
4. Check the web interface - new file may not always appear in the web interface.

### Expected behavior

When a file is added from the SMB side, the file should be immediately visible in the web interface.

### Installation method

Other Community project

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud-new.[REDACTED BY ME]",
            "nextcloud.[REDACTED BY ME]",
            "192.168.100.58"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.3.2",
        "overwrite.cli.url": "http:\/\/nextcloud-new.[REDACTED BY ME]",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "enable_previews": true,
        "preview_max_x": 256,
        "preview_max_y": 256,
        "jpeg_quality": 75,
        "default_phone_region": "AU",
        "skeletondirectory": "",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
```

### List of activated Apps

```shell
/var/www/nextcloud# sudo -u www-data php occ app:list
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - bruteforcesettings: 2.4.0
  - circles: 24.0.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - encryption: 2.12.0
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_accesscontrol: 1.14.0
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_ldap: 1.14.1
  - user_status: 1.4.0
  - viewer: 1.8.0
  - workflowengine: 2.6.0
Disabled:
  - contactsinteraction: 1.2.0
  - weather_status: 1.1.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
This output contains sensitive data - I will need to send this privately to someone to review.
```

**Comment by szaimen** [comment]
See this app: https://apps.nextcloud.com/apps/files_inotify
