### ISSUE TITLE
[Bug]: Menu elements not display block

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/server#34870]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Menu items not display block.

See animation:
![Animation](https://user-images.githubusercontent.com/1473674/198673855-13b2d61b-90dc-4e68-aa74-1fa122d7b653.gif)

### Steps to reproduce

1. open the menu of a file
2. the entries not 100% width

### Expected behavior

full width is clickable for a user

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
default
```

**Comment by coharms** [comment]
I can reproduce this behavior in my environment. 
I think responsible for this behavior is the class `#content[class*='app-']` in `core/css/apps.scss` and its contained rule `width:fit-content`. I would propose to change it to `width:100%` or remove the whole block based on the deprecated comment. 

![Screenshot from 2022-10-29 18-28-29](https://user-images.githubusercontent.com/97545719/198843119-7f5b7a3b-f1c2-4c55-9a36-673be8d546c0.png)

**Comment by Dennis1993** [comment]
Yes, that works in my environment too!
Do you want to create a pull request or should I?

Thanks for your post and help!

**Comment by coharms** [comment]
Please go on and create a pull request.
Sure no problem

**Comment by Dennis1993** [comment]
I found the same issue here: https://github.com/nextcloud/server/issues/34653

I close this one
