### ISSUE TITLE
File Upload works but can't upload folder

### ISSUE THREAD

**Issue by kenthinson** [nextcloud/server#3488]
### Steps to reproduce
1. Drag folder or click upload button in next cloud interface
2. Will get a "Connection to server lost error"

### Expected behavior
Folder and it's contents should be uploaded.

### Actual behavior
Connection to server lost error message. No upload happens

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Apache 

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
11.0.1.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
11.0

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

Enabled:
  - activity: 2.4.1
  - calendar: 1.5.0
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - richdocuments: 1.1.25
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - bookmarks
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - files_trashbin
  - tasks
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'nextcloud.kenthinson.com',
    1 => '10.0.1.104',
  ),
  'datadirectory' => '/var/www/html/data',
  'overwrite.cli.url' => 'http://10.0.1.84',
  'dbtype' => 'mysql',
  'version' => '11.0.1.2',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
  'maintenance' => false,
  'updater.secret' => '',
  'theme' => '',
  'loglevel' => 2,
);
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Safari 10.0.3, also tried Firefox 51.0.1

**Operating system:**
Mac OSX 10.11.6

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Happyfeet01** [comment]
i try it with my instance. it works for me.

have also Ubuntu 16.04 and Nextcloud 11.

Can you post an Apache Error Log and Nextcloud log entrys?

**Comment by kenthinson** [comment]
I can't test or get logs right now as I'm at school. But I wil get the logs when I get home. I found this 
https://help.nextcloud.com/t/uploading-folders-not-possible/3106
Is chrome still the only supported browser? That might be my issue if so.

**Comment by MorrisJobke** [comment]
What browser do you use? Only chrome supports folders and on Firefox it should show a proper warning, that folders are not supported in the drag and drop upload.

**Comment by nickvergessen** [comment]
Closing as the necessary information is missing.

**Comment by sylvainfaivre** [comment]
In case anyone finds this report with a Google search, just giving some info : folder upload in the web interface works all right with Nextcloud Server 11.0.1 and Firefox 51 or Chrome 56 (tested on Ubuntu).
