### ISSUE TITLE
[Bug]: Upload dialog bubble text is not aligned

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/server#34889]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When uploading a file, the upload bubble text is not aligned between states:

![image](https://user-images.githubusercontent.com/7427347/198967259-b697f2b8-ced3-413d-b7d4-ee9d6819ce92.png)

I couldn't debug further as constant ticks on the `<em>` element cotaining the span(s) made it impossible to look at the styles :sweat_smile: 

### Steps to reproduce

1. Upload a large- ish file so you'll have time to observe the behaiour
2. Look at the text that describes the remaining upload time

### Expected behavior

The text overlaps 100%

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
c.nc
```

### List of activated Apps

```shell
c.nc
```

### Additional info

Observed on c.nc

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by miaulalala** [comment]
Still reproducable:

![image](https://user-images.githubusercontent.com/7427347/214284663-7b7e6a17-ca5f-4db5-a2da-1bce80e4f316.png)

**Comment by szaimen** [comment]
which version did you test?

**Comment by miaulalala** [comment]
> which version did you test?

c.nc

**Comment by szaimen** [comment]
Thanks!

**Comment by skjnldsv** [comment]
Fixed 28
