### ISSUE TITLE
Explain some Settings in Personal/Admin Settings

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#3490]
The idea is to

- put the _information_ **i** behind more configuration options (e.g.) theming and link to a specific part of the documentation ... for settings currently not documented, it should be considered to do that 😅 
- Explain the settings with 1-2 sentences (e.g. that theming is changing colors of folders,...)

Same for Spreed, Updater, ... 

Maybe @jacboy also wants to step-in here 🤔 

cc @jancborchardt @karlitschek

**Comment by MariusBluem** [comment]
cc @ChristophWurst here because of the many questions in `twofactor_totp` why clients are not longer working (app passwords) 😅🙈

**Comment by MorrisJobke** [comment]
@MariusBluem Could you check this again? We added a lot of hints to all settings in the past days. Could you please write down for which settings the info is missing or close this ticket. Thanks 👍

**Comment by MariusBluem** [comment]
@MorrisJobke On it 😉

**Comment by MorrisJobke** [comment]
Let's close this for now until more specific items are listed.
