### ISSUE TITLE
colorSvg should no use a theme's 'mailHeader' color

### ISSUE THREAD

**Issue by leonklingele** [nextcloud/server#3491]
After upgrading to Nextcloud 11, we noticed that the folder icons use a weird, lila-ish color.
It looks like Nextcloud 11 generates these icons based on our theme's 'mailHeader' color.
This should not be the case, as 'mailHeader' and folder icons are completely unrelated.

https://github.com/nextcloud/server/blob/d10be51d40ed3e2e99c3749e5f1ba7c72b4a2e6a/apps/theming/lib/IconBuilder.php#L181

**Comment by leonklingele** [comment]
Throughout the whole Nextcloud codebase, `mailHeader` is used for many things not related to the mail header. I don't know if this is a good practice.

**Comment by MorrisJobke** [comment]
This is actually a feature that @juliushaertl introduced.

I guess we should "rename" it to accent color.

@nextcloud/designers

**Comment by juliushaertl** [comment]
@leonklingele Are you using a custom theme besides the theming app?

**Comment by fancycode** [comment]
We are only using a custom theme:
https://github.com/spreedbox/nextcloud-spreedbox-theme

The folder `spreedbox` is copied to the `themes` folder of Nextcloud. After changing the color in the theme, still the old icons are being shown - how can we force a rebuild of the icons with the new color?

**Comment by juliushaertl** [comment]
@MorrisJobke Yes, it would make sense to rename this. Do we need a seperate mailHeader color?

@fancycode Colored icons are only available when using the theming app. If you want other folder icons within a custom theme you need to store the images inside your theme folder and run ./occ maintenance:mimetype:update-js

**Comment by fancycode** [comment]
Hmm, we're not using the theming app (at least not that I know of), only our custom theme.

In the admin area it shows `You are already using a custom theme` for the `Theming` subsection, so there is no way to enable theming.

**Comment by MorrisJobke** [comment]
@fancycode This is a feature of the theming app, because it adds additional CSS. Maybe you try to use the theming app with spreedbox presets instead?

**Comment by juliushaertl** [comment]
@fancycode That indicades that the theming app is enabled. Can you try to disable it manually in the apps section?

We need to add some proper collission handling for theming app vs custom theme. https://github.com/nextcloud/server/issues/3094

**Comment by nickvergessen** [comment]
So, intended behaviour or bug? Close or fix?

**Comment by jancborchardt** [comment]
> Do we need a seperate mailHeader color?

No we don’t. The mail header should be colored in the primary color chosen in theming. :)
And that also colors the main header and the filetype icons, as intended.

**Comment by MorrisJobke** [comment]
So this is intended behaviour: close.

**Comment by jancborchardt** [comment]
The only confusing thing maybe here is that the function name is `getMailHeaderColor` as mentioned by @MorrisJobke above – we could change that to `getColorPrimary`. Pull request at https://github.com/nextcloud/server/pull/4108, please review :)
