### ISSUE TITLE
[Bug]: Cannot use enter key to confirm admin password prompt

### ISSUE THREAD

**Issue by meichthys** [nextcloud/server#34912]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I feel like this issue may already be reported but i wasn't able to find it, or perhaps it was fixed in 25.0.0 (I'm running 25.0.0RC5)

When installing a new app or making admin changes, we are prompted for admin credentials. Currently it is not possible to click the confirm button to confirm the credentials. Pressing the `enter` key works fine.

### Steps to reproduce

1. Make a change in admin settings like enabling an app
2. Enter credentials
3. Try to click "Confirm"

### Expected behavior

We should be able to click "Confirm"

### Installation method

Community VM appliance

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - calendar: 4.1.0-rc.1
  - circles: 25.0.0-alpha.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.1
  - contactsinteraction: 1.6.0
  - cookbook: 0.9.17
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.1
  - drawio: 1.0.3
  - external: 5.0.0
  - extract: 1.3.5
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_automatedtagging: 1.15.0
  - files_fulltextsearch: 24.0.1
  - files_fulltextsearch_tesseract: 24.0.0
  - files_pdfviewer: 2.6.0
  - files_retention: 1.14.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - files_zip: 1.1.2
  - firstrunwizard: 2.14.0
  - forms: 3.0.1
  - fulltextsearch: 24.0.0
  - fulltextsearch_elasticsearch: 24.0.1
  - impersonate: 1.11.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.1.0-rc.1
  - maps: 0.2.1
  - memories: 4.5.3
  - metadata: 0.17.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - occweb: 0.1.0
  - password_policy: 1.15.0
  - pdf_downloader: 1.0.6
  - photos: 2.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - radio: 1.0.3
  - recognize: 3.1.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - socialsharing_email: 2.5.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - bruteforcesettings: 2.4.0
  - encryption: 2.13.0
  - federation: 1.13.0
  - files_external: 1.15.0
  - support: 1.6.0
  - survey_client: 1.13.0
  - user_ldap
```

**Comment by szaimen** [comment]
will be fixed with 25.0.1
