### ISSUE TITLE
[Bug]: BackgroundImage Cache duration

### ISSUE THREAD

**Issue by AndreKoepke** [nextcloud/server#34911]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I uploaded a very large background-image into my NC-instance. A few days later, I noticed that the large image will be very often downloaded from the clients.  
After inspecting the cache-headers, I saw this:  
![image](https://user-images.githubusercontent.com/15613049/199293249-5a82d5ea-cc84-4133-899d-804d8486d3a1.png)
With other words: It expires after a hour. 

Why did I reported it as a bug? It was the first time, that I read the nextcloud-code. And I found this line https://github.com/nextcloud/server/blob/075a87670d4157086974d84972553914078c203b/apps/theming/lib/Controller/UserThemeController.php#L145-L151

So I guess, that cache should expire after one day. Why has the header only one hour? 
Side note: Can I increase the cache-time for my instance?

### Steps to reproduce

1. Setup a custom image in theming-settings.
2. Open nextcloud.
3. Inspect the headers for `apps/theming/image/background?v=23`

### Expected behavior

The `expires`-header for the background-image should be one day later as the current timestamp.

### Installation method

Community Docker image

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.0.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.1
  - contactsinteraction: 1.6.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - forms: 3.0.1
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.0.3
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - notify_push: 0.5.0
  - oauth2: 1.13.0
  - occweb: 0.1.0
  - password_policy: 1.15.0
  - photos: 2.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recognize: 3.1.0
  - recommendations: 1.4.0
  - related_resources: 1.0.2
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - audioplayer: 3.2.4
  - dashboard: 7.1.0
  - encryption
  - files_external
  - printer: 0.0.3
  - richdocuments: 4.2.3
  - suspicious_login
  - twofactor_totp
  - user_ldap
```

**Comment by szaimen** [comment]
Which nc version?

**Comment by AndreKoepke** [comment]
@szaimen 25.0.0

**Comment by PVince81** [comment]
considering that we're already using cache busting in various places and also for the background image, why not just set it to a month or more ? because as soon as a user changes the background image we use a buster anyway

thoughts ? @skjnldsv @Pytal

**Comment by AndreKoepke** [comment]
@PVince81 sounds good 
https://github.com/nextcloud/server/blob/054d266c70fd1e8762398e68437e533dbb422349/apps/theming/src/helpers/getBackgroundUrl.js#L36
But with the cacheBuster ... why set an expiration at all? I guess that all calls, where the cacheBuster is involved, should be endless in the cache.

**Comment by skjnldsv** [comment]
![image](https://github.com/nextcloud/server/assets/14975046/d8264fd3-6bc8-4c72-a635-f36d303c26f7)

Seems fixed now
