### ISSUE TITLE
[Bug]: Expiration date field doesn't show previously set value

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#34926]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Expiration date field doesn't populate itself with the date

### Steps to reproduce

1. Create a folder "test"
2. Share with link
3. Set an expiration date in the future
4. Refresh the page
5. Open the link share dropdown to edit the date

### Expected behavior

Expiration date is set

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
N/A
```

### Additional info

This is on git master c5b21c59bc1efbeb20dd327ca2649576abf144ac

Discovered through https://github.com/nextcloud/server/issues/34695

The expiration date was set successfully as it's there in the database.
The bug is that the date time input field doesn't set it.

- [x] nextcloud-vue bug: https://github.com/nextcloud/nextcloud-vue/issues/3403 https://github.com/nextcloud/nextcloud-vue/pull/3405
- [x] release nextcloud-vue 7.0.2
- [x] update @nextcloud/vue on master
- [x] update @nextcloud/vue on stable25

**Comment by szaimen** [comment]
@PVince81 cab you check if this is fixed with https://github.com/nextcloud/server/pull/35188?

**Comment by PVince81** [comment]
I've retested on master today and the problem is NOT fixed, the values are still not properly set. :frowning:

**Comment by PVince81** [comment]
to prove that the value is set for regular user share, add:
```
diff --git a/apps/files_sharing/src/components/SharingEntry.vue b/apps/files_sharing/src/components/SharingEntry.vue
index 7cc283e705c..6570f0c24bc 100644
--- a/apps/files_sharing/src/components/SharingEntry.vue
+++ b/apps/files_sharing/src/components/SharingEntry.vue
@@ -22,6 +22,7 @@
 
 <template>
        <li class="sharing-entry">
+               Expiredate: {{ share.expireDate }}
                <NcAvatar class="sharing-entry__avatar"
                        :is-no-user="share.type !== SHARE_TYPES.SHARE_TYPE_USER"
                        :user="share.shareWith"
@@ -99,7 +100,7 @@
                                        :hide-label="true"
                                        :class="{ error: errors.expireDate}"
                                        :disabled="saving"
-                                       :value="share.expireDate"
+                                       value="2022-11-23"
                                        type="date"
                                        :min="dateTomorrow"
                                        :max="dateMaxEnforced"
```

I can see the date set, it says "Expiredate: 2022-11-23 00:00:00".
I tried setting a value directly without the zeroes, just in case.

Still not working.

**Comment by PVince81** [comment]
turns out there's more broken in the sharing code: when I set "2022-11-19" as date, it sends it with a 23h time component:
<img width="401" alt="image" src="https://user-images.githubusercontent.com/277525/202148886-5088f4a5-aa8a-487e-8afb-b91139ef92dc.png">

and in the database the time gets truncated so the stored value is "2022-11-19 00:00:00"

**Comment by PVince81** [comment]
regression likely caused by the recent switch from moment to Date to accomodate for the new native date picker: https://github.com/nextcloud/server/pull/33915

**Comment by PVince81** [comment]
on stable24 the value was passed as follows:

- share with link:
 
<img width="159" alt="image" src="https://user-images.githubusercontent.com/277525/202152914-3576b915-31a3-4899-8db8-8b83237d199c.png">

- share with user:
<img width="162" alt="image" src="https://user-images.githubusercontent.com/277525/202153090-a9f84b77-347a-48c3-9040-fb603dbc9111.png">
