### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by deepwather** [nextcloud/server#34936]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

after upgrading to nextcloud 25, the plugins cannot be updated when a password prompt is needed, because there is a javascript error in the "**vue.runtime.esm.js:3047** _TypeError: Cannot read properties of undefined (reading 'forEach')_" and so the confirmation button does not work after entering the password.

![image](https://user-images.githubusercontent.com/12274612/199691469-a029854a-b447-454d-9226-16df0c1d565e.png)

### Steps to reproduce

1. Upgrade to NC 25
2. Stay logged in for a while
3. Upgrade some apps
4. Try to enter the passwort and click confirm button

### Expected behavior

PW should accepted

### Operating system

RHEL/CentOS

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Only Default apps
```

**Comment by szaimen** [comment]
will be fixed with 25.0.1
