### ISSUE TITLE
[Bug]: \OC::$server->getSession()->set('key', 'value') not saved

### ISSUE THREAD

**Issue by the-djmaze** [nextcloud/server#34935]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

My app is trying to set a custom session value using. But `NULL` is always returned.

### Steps to reproduce

1. first request set value
```php
\OC::$server->getSession()->set('snappymail-uid', 'value');
```
2. second request fetch value
```php
\var_export($ocSession['snappymail-uid']);
```

### Expected behavior

Return 'value' instead of `NULL`

### Installation method

Community Manual installation with Archive

### Operating system

RHEL/CentOS

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

SQlite

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Not relevant
```

### List of activated Apps

```shell
SnappyMail
```

### Nextcloud Signing status

```shell
Not relevant
```

### Nextcloud Logs

```shell
Not relevant
```

### Additional info

```
CryptoSessionData::__construct OC\Session\Internal
CryptoSessionData::close by lib/private/AppFramework/Middleware/SessionMiddleware.php#55
CryptoSessionData::isModified => $this->session->set()
CryptoSessionData->set('key', 'value');
CryptoSessionData::__destruct
CryptoSessionData::isModified => $this->session->set()
```

**Comment by szaimen** [comment]
Which NC version?

**Comment by the-djmaze** [comment]
> Which NC version?

24.0.6

**Comment by CarlSchwan** [comment]
You are probably using `lib/private/Session/Memory.php` instead of `lib/private/Session/Internal.php`, unfortunately I have no idea how the Internal session is used and it seems only the Memory session are actually used

@juliushaertl do you have an idea why we are using the in memory session handling?

**Comment by juliushaertl** [comment]
The only scenario I would have in mind is if your call to getSession is actually taking place before the initSession call of Nextcloud. https://github.com/nextcloud/server/blob/11bedf1c3bc65d70b5601ccfca7cdc3a57a46aa6/lib/base.php#L418

Maybe you could add some logging to that to see if that is the case. Otherwise maybe you can provide the link to where the setSession in your apps code doesn't take effect, then I could have a quick look.

**Comment by the-djmaze** [comment]
The code is executed after the App Controller is called.

```
Go to: /nextcloud/index.php/apps/snappymail/
appinfo/routes.php has `page#index`
Nextcloud calls `OCA\SnappyMail\Controller\PageController::index()`
That calls SnappyMailHelper::startApp()
startApp() tries to do a check due complications with the Impersonate app
```

https://github.com/the-djmaze/snappymail/blob/39a827aa2e4fb11ea7cbea488b768ac2bee1012b/integrations/nextcloud/snappymail/lib/Util/SnappyMailHelper.php#L104-L127

**Comment by juliushaertl** [comment]
You may need to add the `@UseSession` annotation to your controller method then, as otherwise `ISession::set` is called after the session has been closed for writing already.

https://docs.nextcloud.com/server/latest/developer_manual/basics/controllers.html#reading-and-writing-session-variables

**Comment by the-djmaze** [comment]
Well that is a problem.
As i also have `class Provider implements IProvider` but the documentation of search has no `@UseSession`
https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/search.html

**Comment by juliushaertl** [comment]
But why would search need to write the session?

**Comment by the-djmaze** [comment]
I know that you want to close the session immediately.
Else there will be a lock on the data and simultaneous requests have to wait for the unlock.

However, with simultaneous requests there are issues:
1. Request 1 loads session data and closes
2. Request 2 loads session data
3. Request 2 modifies session data and saves
4. Request 1 still running but with old session data (not the changed by request 1)

As this issue is always there, a different approach to sessions could be written.
1. Request 1 loads session data and closes
2. Request 2 loads session data
3. Request 2 modifies session data and saves
4. Request 1 modifies session data
 - Load current session data
 - Set the modified session data
 - Write merged result session data

**Comment by juliushaertl** [comment]
Ok, so for Nextcloud 25 there would be a way to reopen the session with https://github.com/nextcloud/server/pull/32162#issuecomment-1152481556

Now I don't have much insight into the impersonate app but with the described behavior I would imagine this also has all kind of issues with external storages where the login data is stored in the session and probably other session-related cases.

Maybe @blizzz has any further insight as the main contributor to the impersonate app?

**Comment by the-djmaze** [comment]
Yes that would be better.

As for Nextcloud my approach for sessions might be easy to implement to improve #32162

```php
class Internal extends Session {
	/**
	 * @param string $name
	 * @throws \Exception
	 */
	public function __construct(string $name) {
		set_error_handler([$this, 'trapError']);
		$this->invoke('session_name', [$name]);
		try {
			$this->startSession();
			$this->invoke('session_abort'); // ADDED, close immediately
		} catch (\Exception $e) {
			setcookie($this->invoke('session_name'), '', -1, \OC::$WEBROOT ?: '/');
		}
		restore_error_handler();
		if (!isset($_SESSION)) {
			throw new \Exception('Failed to start session');
		}
	}

	public function set(string $key, $value) {
		// ADDED
		$closed = $this->sessionClosed;
		$closed && $this->startSession(); // reopen() ?!?
//		$closed && $this->invoke('session_reset'); // possible? no idea


//		$this->validateSession();
		$_SESSION[$key] = $value;

		// ADDED
		$closed && $this->close();
	}
```

This approach has more IOPS when setting multiple.
So the `->close()` could also be done by process/app itself.

**Comment by the-djmaze** [comment]
Oh never mind my response. I looked at the first code but the real solution was later on in the thread.
You all did what i mention using the $this->reopen() :+1: 

I will use that if Impersonate can't solve this.
