### ISSUE TITLE
Enforce 2FA-Email on internal db before 1st login

### ISSUE THREAD

**Issue by jfieser** [nextcloud/server#34938]
I seek a means of enforcing 2FA for all users including new users that have never signed in.  All the pieces seem to be in place for 2FA via Email to work, but adding new users after Enforcing 2FA for all users, simply locks new users out.  I only need to add a couple of records to the database with a cron job to fake the verification of email and enable it for each user.

In a related requirement, I am requiring admins to use the complete email address for the uid and using the same cron job to not allow users to change their own email address.  This requirement, with 2FA-Email, ensures that the user maintains their relationship with the organization that they had when the account was created.

**Comment by jfieser** [comment]
I developed the code below to do what I needed.  It's a php script that uses the nextcloud config to access the MariaDB.  Requiring Admins to use the full email address for the uid gave me the shortcut to know the original email address, since uid_lower is already available.  This no-input php script is available for Admins to refresh as soon as they create new users, or they can let the cron job make the changes.  Records that are being corrected are truncated when shown in the browser because no one needs to be logged in to run the script - any user could see that content. 

`<?php
header('Cache-Control: no-cache, no-store, must-revalidate');
header('Pragma: no-cache');
header('Expires: 0');

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$log = '/var/log/nc-selfadmin/nc-email.log';
date_default_timezone_set('America/Chicago');
$date = new DateTime();
$date = $date->format("Y-m-d h:i:s");
$logdat = "";

require '/var/www/html/nextcloud/config/config.php';  

echo "<!DOCTYPE html>\n<html>\n  <head>\n<title>Enabling Self Admin of Email 2FA in Nextcloud</title>";

echo "</head>\n<body>Enabling Self Admin of Email 2FA in Nextcloud\n";

$conn = new mysqli($CONFIG['dbhost'], $CONFIG['dbuser'], $CONFIG['dbpassword'], $CONFIG['dbname']);
// Check connection
if ($conn->connect_error) {
   die("Connection failed: " . $conn->connect_error);
}

echo "<p>oc_preferences<br>Check for and repair any records where the email ";
echo "was changed so they can access from an un-approved (personal) email address.";
$sql = "SELECT `uid`, `uid_lower`, `displayname`, `userid`, `configvalue`  FROM oc_preferences ";
$sql .= "JOIN oc_users on uid=userid where appid='settings' and configkey='email' ";
$sql .= "and uid_lower != configvalue;";
$result = $conn->query($sql);
$idarray = $result->fetch_all(MYSQLI_ASSOC);
foreach ($idarray as $idar) {
    echo "<br>";
    echo  substr($idar['userid'],0,3)." - <br>\n"; #$idar['configvalue']
    $sql = "UPDATE `oc_preferences` set configvalue = '".$idar['uid_lower']."' WHERE appid='settings' and ";
    $sql .= "configkey='email' and userid = '".$idar['userid']."';";
    $myfile = fopen($log, "a") or die("Unable to open log file!");
    $logdat = $date."\tpreferences\t".$idar['configvalue']."\t".$sql."\n";
    fwrite($myfile, $logdat);
    fclose($myfile);
    # echo "<p>".$idar['configvalue'];
    echo substr($idar['userid'],0,3)." - ".substr($idar['configvalue'],0,3)."<br>";
    $result = $conn->query($sql);
}
echo "<p>oc_twofactor_providers<br>";

echo "Check for and repair any zeros - set them to 1<br>";
$sql = "SELECT `uid` FROM oc_twofactor_providers where provider_id='email' and enabled='0';";
$result = $conn->query($sql);
$idarray = $result->fetch_all(MYSQLI_ASSOC);
foreach ($idarray as $idar) {
    #echo  $idar['uid']."<br>\n";
    echo  substr($idar['uid'],0,3)." - <br>\n";
    $sql = "UPDATE `oc_twofactor_providers` set enabled = '1' WHERE provider_id='email' and ";
    $sql .= " uid = '".$idar['uid']."';";
    $myfile = fopen($log, "a") or die("Unable to open log file!");
    $logdat = $date."\ttwofactor_providers\t".$idar['uid']."\t".$sql."\n";
    fwrite($myfile, $logdat);
    fclose($myfile);
    echo substr($idar['uid'],0,3)."<br>";
    $result = $conn->query($sql);
}

echo "<p>\nChecking emails that are in users but missing from twofactor_providers\n<p>";
#Check for and correct any missing Email 2FA entries for email in preferences

$sql = "SELECT `uid`, `uid_lower`, `displayname`, `userid`, `configvalue` FROM oc_preferences ";
$sql .= "JOIN oc_users on uid=userid where appid='settings' and configkey='email' and NOT EXISTS ";
$sql .= "(SELECT `uid` FROM oc_twofactor_providers where `userid`=`uid` and provider_id='email' ";
$sql .= "and enabled='1');";
$result = $conn->query($sql);
$idarray = $result->fetch_all(MYSQLI_ASSOC);
foreach ($idarray as $idar) {
    $sql = "INSERT INTO `oc_twofactor_providers` VALUES ('email','";
    $sql .= $idar['uid_lower']."',1);";
#    echo $sql."<p>";
    $myfile = fopen($log, "a") or die("Unable to open log file!");
    $logdat = $date."\ttwofactor_providers\t".$idar['uid']."\t".$sql."\n";
    fwrite($myfile, $logdat);
    fclose($myfile);
    echo substr($idar['userid'],0,3)."<br>";
    $result = $conn->query($sql);
}

echo "<p>\nChecking emails that are in users but missing from preferences verified\n<p>";
#Check for and correct any missing Email 2FA entries for verified in preferences
$sql = "SELECT `uid`, `uid_lower`, `displayname` FROM oc_users WHERE NOT EXISTS (SELECT ";
$sql .= "`userid` FROM oc_preferences where `uid`=`userid` and appid='twofactor_email' ";
$sql .= "and configkey='verified' and configvalue='true');";
$result = $conn->query($sql);
$idarray = $result->fetch_all(MYSQLI_ASSOC);
foreach ($idarray as $idar) {
    $sql = "INSERT INTO `oc_preferences` VALUES ('".$idar['uid']."','twofactor_email',";
    $sql .= "'verified','true');";
#    echo $sql."<p>";
    $myfile = fopen($log, "a") or die("Unable to open log file!");
    $logdat = $date."\ttwofactor_email verified in prefs\t".$idar['uid']."\t".$sql."\n";
    fwrite($myfile, $logdat);
    fclose($myfile);
    echo substr($idar['uid'],0,3)."<br>";
    $result = $conn->query($sql);
}

$conn->close();


?>
  </body>
</html>`

**Comment by joshtrichards** [comment]
Duplicate (enough) of #17584
