### ISSUE TITLE
Appearance and accessibility (really needed at two positions in Nextcloud 25?)

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/server#34939]
Since Nextcloud 25 you can find **Appearance and accessibility**  at the top right menu and after click on Settings also in the left menu. The destination is `https://cloud.server.tld/settings/user/theming`

I think the link in the top right menu is not really needed. Maybe it can be deleted. I think it would be better if the top right menu is minimal. 

Also, one could perhaps think about whether one could not also classify "Apps" under the "Settings" and not directly at the top right menu.

**Comment by szaimen** [comment]
Accessibility wise it was decided that having a shortcut for that makes sense.

cc @nextcloud/accessibility @jancborchardt

**Comment by JuliaKirschenheuter** [comment]
> Accessibility wise it was decided that having a shortcut for that makes sense.

I agree that that makes sense

**Comment by devnull4242** [comment]
> I agree that that makes sense
Thank you. 

It makes no sense to use **Appearance and accessibility** at this  two position.

Maybe you should start a survey how often you make changes there and if that justifies the position on the top right. I think not.
