### ISSUE TITLE
PHP Error of type string is deprecated at - NC25

### ISSUE THREAD

**Issue by killerb77** [nextcloud/server#34962]
I am using the official docker image nextcloud 25.  I am getting all kinds of error PHP messages regarding of type string is deprecated at.  It's happening on file uploads, when nextcloud sends email notifications as well.  I think it's related to the new version 25 using PHP 8.1.  It started happening for version 25.  Didn't happen on version 24 which uses PHP 8.0.

[PHP] Error: Error: strpos(): Passing null to parameter nextcloud/docker#1 ($haystack) of type string is deprecated at /var/www/html/lib/private/Files/Cache/Scanner.php#508 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(8192, "strpos(): Passi ... d", "/var/www/html/l ... p", 508)
 1. /var/www/html/lib/private/Files/Cache/Scanner.php line 508
    strpos(null, ".part/")
 2. /var/www/html/lib/private/Files/View.php line 1384
    OC\Files\Cache\Scanner::isPartialFile(null)
 3. /var/www/html/lib/private/Files/Node/HookConnector.php line 227
    OC\Files\View->getFileInfo(null)
 4. /var/www/html/lib/private/Files/Node/HookConnector.php line 113
    OC\Files\Node\HookConnector->getNodeForPath(null)
 5. /var/www/html/lib/private/legacy/OC_Hook.php line 106
    OC\Files\Node\HookConnector->postWrite([null])
 6. /var/www/html/apps/dav/lib/Connector/Sabre/File.php line 471
    OC_Hook::emit("OC_Filesystem", "post_write", [null])
 7. /var/www/html/apps/dav/lib/Connector/Sabre/File.php line 398
    OCA\DAV\Connector\Sabre\File->emitPostHooks(false)
 8. /var/www/html/apps/dav/lib/Connector/Sabre/Directory.php line 151
    OCA\DAV\Connector\Sabre\File->put(null)
 9. /var/www/html/apps/dav/lib/Upload/UploadFolder.php line 45
    OCA\DAV\Connector\Sabre\Directory->createFile("10485760", null)
10. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 1098
    OCA\DAV\Upload\UploadFolder->createFile("10485760", null)
11. /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 504
    Sabre\DAV\Server->createFile("uploads/bmw/web ... 0", null, null)
12. /var/www/html/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
13. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit("method:PUT", [Sabre\HTTP\Requ ... }])
14. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
15. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
16. /var/www/html/apps/dav/lib/Server.php line 360
    Sabre\DAV\Server->exec()
17. /var/www/html/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
18. /var/www/html/remote.php line 167
    require_once("/var/www/html/a ... p")
![Screenshot 2022-10-27 230350](https://user-images.githubusercontent.com/56096557/198488279-52dbfcb6-429e-45a0-b0b0-d4c941842b21.png)

**Comment by jpgreth** [comment]
+1 For this issue – can confirm: it occurred since 25 update. Didn't happen in 24.

**Comment by artemanufrij** [comment]
Same here (endless spam) on newest Docker image:

![Screenshot_20221201_154453](https://user-images.githubusercontent.com/16517095/205083017-4131b04d-9dc6-4026-9388-77879f3eb373.png)

**Comment by schroeder-hesel** [comment]
Same Problem here. Using latest docker image with version 25.0.1.

![Screenshot 2022-12-02 121715](https://user-images.githubusercontent.com/107101263/205281093-885a7c6b-88ed-4f9b-a57c-a84377dc1f2e.png)

**Comment by fabriziosalmi** [comment]
Same here, docker and nc latest ones.

**Comment by artemanufrij** [comment]
After update to 25.0.2 it seems to be fixed.

**Comment by artemanufrij** [comment]
Still no errors. I'm going to close this issue.
