### ISSUE TITLE
[Bug]: Navigation/app Icons are not visible on background not load

### ISSUE THREAD

**Issue by UteHaus** [nextcloud/server#34965]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Sometimes when the Background not correct load I get a white background and in combination with my background (light brown) I has white navigation app icons (see first picture). 

The bug com with the upgrade from 24.0.7 to 25.0.0. The bug exists also in the newest version 2.5.1 .

Two App icons (Carnet and New) are slightly visible.

![grafik](https://user-images.githubusercontent.com/31124997/199942509-7292acc0-bea8-432c-b922-e60ed1fc42d0.png)

This is my normal view (dashboard).
![grafik](https://user-images.githubusercontent.com/31124997/199943275-17277f1c-4871-40b2-930a-f31e62086693.png)

### Steps to reproduce

The error occurs with high loading times.

### Expected behavior

The App/Navigation Icons are black or the are a default background image/color.

### Installation method

Community Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": false,
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "porta",
            "cloud.wobco.de",
            "localhost:8091"
        ],
        "overwrite.cli.url": "https:\/\/cloud.wobco.de",
        "overwriteprotocol": "https",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "25.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 3,
        "maintenance": false,
        "default_phone_region": "DE",
        "onlyoffice": {
            "verify_peer_off": true
        },
        "app_install_overwrite": [
            "initialcheck",
            "limit_login_to_ip",
            "radio",
            "tasks",
            "occweb",
            "files_reader",
            "files_ebookreader",
            "polls",
            "contacts",
            "drawio",
            "checksum",
            "rainloop",
            "timetracker",
            "passman",
            "calendar",
            "cookbook",
            "dashboardcharts",
            "apporder",
            "bookmarks",
            "passwords",
            "carnet",
            "electronicsignatures",
            "ocdownloader",
            "files_bpm",
            "gestion",
            "audioplayer_editor"
        ],
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Illustrator"
        ],
        "app.mail.imap.timeout": 20,
        "app.mail.smtp.timeout": 2,
        "app.mail.verify-tls-peer": "false",
        "has_rebuilt_cache": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "updater.release.channel": "stable"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - analytics: 4.4.0
  - apporder: 0.15.0
  - audioplayer: 3.3.1
  - bookmarks: 11.0.4
  - calendar: 4.1.0
  - camerarawpreviews: 0.8.0
  - carnet: 0.24.5
  - checksum: 1.1.5
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.1
  - contactsinteraction: 1.6.0
  - cookbook: 0.9.17
  - cospend: 1.5.2
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.1
  - drawio: 1.0.3
  - electronicsignatures: 2.0.1
  - external: 5.0.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_accesscontrol: 1.15.0
  - files_downloadactivity: 1.15.0
  - files_ebookreader: 0.0.1
  - files_external: 1.17.0
  - files_linkeditor: 1.1.12
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - geoblocker: 0.5.7
  - gestion: 2.1.7
  - gpoddersync: 3.6.0
  - groupfolders: 13.0.0
  - libresign: 6.1.2
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.1.0
  - maps: 0.2.1
  - music: 1.7.0
  - news: 19.0.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - occweb: 0.1.0
  - ocdownloader: 1.8.1
  - onlyoffice: 7.6.8
  - passwords: 2022.10.20
  - pax_fax: 1.0.8
  - photos: 2.0.0
  - polls: 4.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - radio: 1.0.3
  - rainloop: 7.2.6
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.1
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - timetracker: 0.0.76
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflow_media_converter: 1.6.2
  - workflowengine: 2.7.0
```

**Comment by szaimen** [comment]
Is this a custom background?

**Comment by UteHaus** [comment]
It is one of the Nextcloud custom backgrounds (picture). 

It is the second in row and column.
![grafik](https://user-images.githubusercontent.com/31124997/200060871-6bd9d021-c3dc-4285-8755-9c04a2c4bf76.png)

**Comment by unknownuser26** [comment]
Same Problem

**Comment by piiskop** [comment]
i had a theme in use and after upgrading to 25.0.1 the theme used is gone and i have the white background again with no app icon visible.

**Comment by Raemsna** [comment]
same issue here when upgrading to 25.0.1

**Comment by PVince81** [comment]
@UteHaus 

> Sometimes when the Background not correct load I get a white background and in combination with my background (light brown) I has white navigation app icons (see first picture).

The question is rather why did the background not load ?
Does it load when you refresh or did you only see it once and never again ?

I don't think we have a fallback for when the background *sometimes* does not load.
An enhancement would be to detect if the background has failed loading and then switch back to some default, at least for color handling.

**Comment by PVince81** [comment]
also: open the network console in the browser when loading the page and see if there are errors there, there could be one related to the background image

also: try a "shift+refresh" when refreshing the page, in cache there's a cache issue

**Comment by UteHaus** [comment]
I replace on the settings the background image with a color and the error did not come back until now.  So I just set one more time the image as background and the background is loaded correctly. Its sames like that migration works not a correctly. 

When the error occurred the first time, I reloaded the page with "shift+refresh" and the error came again and again.
But I not see in the browser logs if the image was not loaded.

**Comment by skjnldsv** [comment]
I cannot reproduce th error.
Is it still happening @UteHaus ?

Btw, selecting a custom color will remove the background. It's per design.

**Comment by piiskop** [comment]
If the background is white by default then why are the icons transparent per design? White icons on a white backgrounds are not visible to human beings. A novice user could not find a way how to make them visible. The color of icons should be according to the background not just white.

**Comment by skjnldsv** [comment]
@piiskop @UteHaus what background? Admin? User? Background image or color?

**Comment by piiskop** [comment]
i mean the background color of the whole application. i only see the icons if a background image is turned on that has dark colors behind the links.

**Comment by skjnldsv** [comment]
Well, how can we know if the background you selected has a bright top header?
We're gonna improve for 26, but until then, it's not a bug, just not implemented.

**Comment by piiskop** [comment]
The icons should be visible no matter what the background. The approach of having them transparent is not user-friendly. It is a bug if no icon is visible as their visibility is not forced currently and without seeing the icons, it is not possible to navigate in Nextcloud unless they are an experienced user who knows to write direct addresses of applications.

**Comment by HannesJo0139** [comment]
> If the background is white by default then why are the icons transparent per design? 

@piiskop But the background is not white by default is it?


> Well, how can we know if the background you selected has a bright top header? We're gonna improve for 26, but until then, it's not a bug, just not implemented.

@skjnldsv At least you could know if one has selected like `#ffffff` in the color picker. Not talking about background image. In fact any picked color tending towards white makes the GUI unusable right now. Call it a bug or broken by design. It is an issue. As long as you cannot set it dynamically, a small toggle switch (switch between light and dark header icons) could also do the trick. Quick and easy.

**Comment by piiskop** [comment]
Who is the one who designed the look of Nextcloud? They should be familiar with design and user experience principles. If an end user is allowed to change the background to any color then all the navigation elements must work with any background color. The icons must not be transparent if the transparency is not automatically adjustable.

i am a user of Nextcloud for many years already and since i started using it i have not seen any remarkable improvements regarding user experience. Even now probably too many processes work in the background while opening the dashboard as opening it just freezes my computer too often. A nice improvement is making a modal window for events in calendar. But the email application still does not find some emails or is very slow. Nextcloud seems to be like a soup being cooked by so many different chefs who put in whatever and whenever they want without tasting meanwhile. This makes Nextcloud an awful solution for group work or document management. we have no better FOSS either, so it is the least-bad solution out of bad FOSS solutions. This is why i still tolerate using Nextcloud.

**Comment by skjnldsv** [comment]
> @skjnldsv At least you could know if one has selected like `#ffffff` in the color picker.

AH! That's a good point.
It's because we changed that option in 26. Now you can have both a custom colour AND a background.
But this is a valid reason, we could at least make sure if there is no background to check against the selected primary, that's a good idea @HannesJo0139 !

**Comment by skjnldsv** [comment]
> The icons should be visible no matter what the background. The approach of having them transparent is not user-friendly. It is a bug if no icon is visible as their visibility is not forced currently and without seeing the icons, it is not possible to navigate in Nextcloud unless they are an experienced user who knows to write direct addresses of applications.

Nextcloud offers out-of-the-box theming with proper contrast and visible navigation.
You decided to pick a custom background. We're not responsible if your pick isn't suitable for the interface. There is a limit to how we can take users by the hand and make the experience flawless. We are helping and mitigating so much already with tons of luminance/contrast calculations.

Now I'm actually gonna lock this thread, aside from HannesJo0139, that is trying to suggest proper technical solutions or ideas. You're just ranting an an issue we said we cannot fix @piiskop . This is now what github issues are for. If you have constructive and proper solutions to offer, please do. If you're just here to complain despite us providing enough informations, please reconsider :)

Thanks :v: 

@HannesJo0139 , I'm gonna re-open a dedicated thread for this specific solution!
