### ISSUE TITLE
[Bug]: Windows11+WSL2 server: High cpu&disk usage after seeking/switching large video. 

### ISSUE THREAD

**Issue by wysaid** [nextcloud/server#34979]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Related to: <https://github.com/nextcloud/server/issues/22334>

Brief: The server keeps high cpu & disk usage for a long time after all connections finished. 

Detail:  

I am hosting several video files on my PC, running `Nextcloud` under Win11+WSL2. ([NUC12WSHi5](https://ark.intel.com/content/www/us/en/ark/products/121628/intel-nuc-12-pro-mini-pc-nuc12wshi5.html))

The server runs well except video sharing.  
All issues in `settings/admin/overview` is passed(green checked).  

<img width="1322" alt="image" src="https://user-images.githubusercontent.com/1430725/200028489-feeb503b-43f3-4a8a-9098-13949a0b7033.png">
<img width="808" alt="image" src="https://user-images.githubusercontent.com/1430725/200026938-a59a0871-457d-4c4d-b7b4-4c66b8dbfa9a.png">

### Steps to reproduce

1. Put large video files (10GB+) in the WSL2 local disk `/home/user/video` or the external mount `/mnt/c/any_share_dir`.
2. Mount the share folder in 'settings/admin/externalstorages'.
3. See the video in Nextcloud url page,  seek the video for a few times or switch different videos (the more seeking or switching, the more resource been taken, the server will hang up if we do these things too much), then close them all.
4. Open terminal, enter `top`, tens of process 'php-fpm8.0' will be shown, keep using a lot cpu resource.
5. In the `Windows` side, open the task manager, the disk is keep reading at high usage.
6. Wait a long time (hours), the usage may go back to normal.
7. The resource usage will restore immediately if I restart the php process via `service php8.0-fpm restart`

>P.S: The same problem happens with default php, too. (__no php-fpm__)

### Expected behavior

1. The cpu&disk usage can keep at a proper level while seeking video, and do not hang up by too much seeking.
2. The cpu&disk usage can return back timely after all connections gone.

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "file.boxiao.wang",
            "cloud.boxiao.wang"
        ],
        "allow_local_remote_servers": true,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "24.0.7.1",
        "overwrite.cli.url": "https:\/\/file.boxiao.wang",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "default_phone_region": "CN",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 0,
        "app_install_overwrite": [
            "spreed"
        ],
        "blacklisted_files": [
            ".DS_Store"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - accessibility: 1.10.0
  - activity: 2.16.0
  - admin_audit: 1.14.0
  - analytics: 4.4.0
  - approval: 1.0.10
  - audioplayer: 3.3.1
  - calendar: 3.4.2
  - circles: 24.0.1
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.2.2
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - diary: 0.0.8
  - drawio: 1.0.3
  - federatedfilesharing: 1.14.0
  - federation: 1.14.0
  - files: 1.19.0
  - files_accesscontrol: 1.14.1
  - files_downloadactivity: 1.15.0
  - files_downloadlimit: 1.0.1
  - files_external: 1.16.1
  - files_pdfviewer: 2.5.0
  - files_readmemd: 1.2.2
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - forms: 2.5.1
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notes: 4.5.1
  - notifications: 2.12.1
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - photos: 1.6.0
  - previewgenerator: 5.1.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - richdocuments: 6.2.0
  - richdocumentscode: 22.5.702
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - spreed: 14.0.6
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - tasks: 0.14.4
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_status: 1.4.0
  - user_usage_report: 1.8.0
  - viewer: 1.8.0
  - whereami: 0.0.9
  - workflowengine: 2.6.0
Disabled:
  - encryption
  - files_trashbin: 1.14.0
  - onlyoffice: 7.5.4
  - talk_matterbridge: 1.23.2
  - user_ldap
  - video_converter: 1.0.5
  - weather_status: 1.4.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by szaimen** [comment]
Wsl is nof supported by us.
