### ISSUE TITLE
[Bug]: apps management page group list display is broken

### ISSUE THREAD

**Issue by punkyard** [nextcloud/server#34977]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

can't read the groups in lists

![Capture d’écran 2022-10-01 à 00 35 23](https://user-images.githubusercontent.com/59349105/200026198-191b8ee9-98f5-4059-bb52-11d5fe66a6c0.png)

### Steps to reproduce

1. go to Apps
2. activate an app
3. select Limit to group, try to add 15 groups amongst 30
4. try to add 5 groups to users amongst 30 groups

### Expected behavior

list with all the groups one under the other
or
list with selected groups one under the other
---- line ----
list of ALL the groups

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
what ever the installed apps
```

### Additional info

thanks

**Comment by szaimen** [comment]
which NC version?

**Comment by punkyard** [comment]
2407

**Comment by bbx-github** [comment]
I can confirm this behavior for nc 25.0.1 if the "edit button" is clicked. Additionally: if you click the group block a list of **all** groups is shown but there is no indication, if a group is selected or not. This makes it really hard to do the group selection right.
I can not confirm this behavior for nc 24.0.7

**Comment by punkyard** [comment]
> I can not confirm this behavior for nc 24.0.7
well.. I can! ;)

**Comment by PVince81** [comment]
need to pick the contacts app when testing because it has a big screenshot in the sidebar, and also have a lower window height

on stable24:
<img width="266" alt="image" src="https://user-images.githubusercontent.com/277525/203531414-fab7d84f-ee96-4bce-88ac-50dffa698526.png">

on stable25:
<img width="263" alt="image" src="https://user-images.githubusercontent.com/277525/203531638-ecc49876-e088-4aac-9e3d-e04c8acf4d8d.png">

it's not wrapping the same way though
