### ISSUE TITLE
[Bug]: Quota is not checked and im able to copy files even when i dont have storage

### ISSUE THREAD

**Issue by GretaD** [nextcloud/server#34975]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I have reached my quota storage and i try to copy a file that i have already uploaded. The file is copied even though i dont have more space for it. 

Error messages are shown (see below)

### Steps to reproduce

1. Upload files on your NC to reach the maximum storage
2. Copy one of those using action menu of that file
3. See what happens

### Expected behavior

The file is not copied

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
mail
calendar
contacts
```

### Additional info

![Screenshot from 2022-11-04 17-11-18](https://user-images.githubusercontent.com/12728974/200024546-676f131e-ac34-4b9d-b64b-73b22623cc34.png)
![Screenshot from 2022-11-04 17-11-05](https://user-images.githubusercontent.com/12728974/200024551-37aa640f-9469-4064-ad4b-f23b25f8a890.png)
![Screenshot from 2022-11-04 17-02-28](https://user-images.githubusercontent.com/12728974/200024554-ebf8dcd2-852f-4cbd-b025-3c2e34ce9fba.png)

**Comment by GretaD** [comment]
comment from Vincent: we likely need to also add a beforeCopy here: https://github.com/nextcloud/server/blob/master/apps/dav/lib/Connector/Sabre/QuotaPlugin.php#L81

**Comment by PVince81** [comment]
likely also happening on previous versions

**Comment by PVince81** [comment]
@come-nc please take care
