### ISSUE TITLE
Error on creating files after update to 11.0.1

### ISSUE THREAD

**Issue by leture** [nextcloud/server#3498]
### Actual behaviour
Windows 7 systems which connect to the Cloud via WebDAV as mounted network drives. After update from 10.0.3 to 11.0.1 creating new files on or copying files to this mounted network drives result in reported errors by Windows. Nevertheless the files are created in the cloud but they are always empty. The log contained entries of the form "No subsystem set a valid HTTP status code. Something must have interrupted the request without providing further detail." which origin from https://github.com/nextcloud/3rdparty/blob/489bcf4f81e462f4d74f0b76f58caeabd58e75de/sabre/dav/lib/DAV/Server.php#L495. Commenting this line out resolved the empty file creation issue but this is obviously just a temporary hack. Maybe some internal code does the right thing but somehow forgets to set the status code of the response and therefore accidentically triggers the exception?

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
Nginx 1.11.9

**Database:**
MySQL 5.7.17

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update from 10.0.3

**Comment by leture** [comment]
Maybe #2887 is related here and/or my issue might be a duplicate?

**Comment by milkomeda** [comment]
Same issue on Windows 10.

**Comment by Flole998** [comment]
Issue #2887 is related, there's also patch there to fix it.

**Comment by MorrisJobke** [comment]
Closing this one in favour of #2887
