### ISSUE TITLE
[Bug]: Nextcloud 24.0.7 is using relative paths, multiple file downloads fail

### ISSUE THREAD

**Issue by joho1968** [nextcloud/server#35006]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Not sure when this happened, but after having upgraded from 24.0.x to 24.0.7, one user reports not being able to select multiple files for download, or rather, the selection goes fine, but the download fails.

This seems to be due to a change in a require_once statement from absolute to relative.

### Steps to reproduce

1. Select multiple files
2. Choose to download them
3. Nextcloud responds with an internal error, displaying a request code (which can be matched with the log)

### Expected behavior

I would expect the files to download properly.

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Not relevant
```

### List of activated Apps

```shell
Not relevant
```

### Nextcloud Signing status

```shell
"No errors have been found"
```

### Nextcloud Logs

```shell
{"reqId":"blablabla","level":3,"time":"2022-11-07T13:50:00+00:00","remoteAddr":"1.2.3.4","user":"johndoe","app\
":"index","method":"GET","url":"/index.php/apps/files/ajax/download.php?dir=%2F&files=Documents&downloadStartSecret=1234","m\
essage":"Failed opening required 'files/ajax/download.php' (include_path='.:/var/www/nextcloud')","userAgent":"Mozilla/5.0 (X11; Ub\
untu; Linux x86_64; rv:106.0) Gecko/20100101 Firefox/106.0","version":"24.0.7.1","exception":{"Exception":"Error","Message":"Failed\
 opening required 'files/ajax/download.php' (include_path='.')","Code":0,"Trace":[{"function":"OC\\Route\\{closu\
re}","class":"OC\\Route\\Route","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/priva\
te/Route/Router.php","line":306,"function":"call_user_func"},{"file":"/var/www/nextcloud/lib/base.php","line":1030,"function":"matc\
h","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC\
","type":"::"}],"File":"/var/www/nextcloud/lib/private/Route/Route.php","Line":155,"CustomMessage":"--"}}
```

### Additional info

If I add the Nextcloud apps directory to the include_path setting, things work again. This was not required prior to the update, according to users.

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

**Comment by joho1968** [comment]
It's not a setup issue, IMHO. The configuration in use had no issues with 24.0.x, it was only after the upgrade to 24.0.7.1 that this because an issue, suggesting a change in the Nextcloud code. 

It was solved by altering the configuration, but that's not the same thing.

Anyway, I've reported it, I can't do much more than that in this case :blush:

**Comment by szotsaki** [comment]
I have the very same problem. After an update it suddenly got broken in Nextcloud.

I checked my config file but I didn't find any relative paths. @joho1968, could you please share what config option did you change?

Thank you!

**Comment by szotsaki** [comment]
The problem is:
In `public function actionInclude($file)` PHP `require_once "$file"` contains `files/ajax/download.php` while the current working directory being `nextcloud`.

So the full path gives: `require_once [...]/nextcloud/files/ajax/download.php`. Which is wrong, because `apps` is missing. The correct one should be: `require_once [...]/nextcloud/apps/files/ajax/download.php`

**Comment by szotsaki** [comment]
What is interesting, that in `nextcloud/lib/base.php:1069` the `match()` function correctly gets `/apps/files/ajax/download.php` as the result of the `$request->getRawPathInfo()` call.

**Comment by szotsaki** [comment]
In `OC\Route\Router->findMatchingRoute()` the parameter `$url` correctly gets populated to `/apps/files/ajax/download.php`. However, in `UrlMatcher->match()` the returned `$parameters['action']['static']['file']` value (which gets require'd literally later) is now only `files/ajax/download.php`.

**Comment by szotsaki** [comment]
This is because the following `$this->root` array is given to the Symphony UrlMatcher:
```
Symfony\Component\Routing\RouteCollection Object
(
    [routes:Symfony\Component\Routing\RouteCollection:private] => Array
        (
            [files_ajax_download] => OC\Route\Route Object
                (
                    [path:Symfony\Component\Routing\Route:private] => /apps/files/ajax/download.php
                                        [defaults:Symfony\Component\Routing\Route:private] => Array
                        (
                            [action] => Closure Object
                                (
                                    [static] => Array
                                        (
                                            [file] => files/ajax/download.php
                                        )
```

**Comment by szotsaki** [comment]
My really ugly workaround for this one problem in `nextcloud/lib/private/Route/Route.php`:

```diff
@@ -152,6 +152,9 @@ class Route extends SymfonyRoute implements IRoute {
                        unset($param["_route"]);
                        $_GET = array_merge($_GET, $param);
                        unset($param);
+                       if ($file == 'files/ajax/download.php') {
+                               $file = 'apps/files/ajax/download.php';
+                       }
                        require_once "$file";
                } ;
                $this->action($function);
```
