### ISSUE TITLE
Deprecation and removal of PHP7.4 support

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#35025]
Continuation of https://github.com/nextcloud/server/issues/29258

php7.4 will run out of security support end of year.

Some usage stats can be found on https://ncpw.mdns.eu/.
Ref https://www.php.net/supported-versions.php

We should do this in two steps again
* [x] Deprecate the version but still support it https://github.com/nextcloud/server/pull/35024
* [x] https://github.com/nextcloud/documentation/issues/9479
* [x] Drop support for the version
* [x] https://github.com/nextcloud/server/pull/34997
* [ ] https://github.com/nextcloud/documentation/issues/9480
* [ ] https://github.com/nextcloud/documentation/issues/9481

cc @nickvergessen @juliushaertl @PVince81

**Comment by AndyScherzinger** [comment]
Decision has been made to drop 7.4 for Nextcloud 26.

@PVince81 can we put a warning into 25 admin settings in case a v25 server runs on PHP/.4 in case we don't have that already?

**Comment by PVince81** [comment]
@szaimen I remember you worked on some warnings, did we add one already ? see above

**Comment by szaimen** [comment]
> @szaimen I remember you worked on some warnings, did we add one already ? see above

I think it was @ChristophWurst ...

**Comment by ChristophWurst** [comment]
Done in https://github.com/nextcloud/server/pull/35024

**Comment by ChristophWurst** [comment]
I've created and linked documentation tickets for this critical change.

**Comment by digitalfox** [comment]
Hello,

Debian will maintain PHP 7.4 till the end of current Debian 11 stable lifecycle (july 2024). Will nextcloud <26 still be supported at this time ?

**Comment by nickvergessen** [comment]
Every version is supported for 1 year. 25 was released October 22, so is supported until October 23

**Comment by digitalfox** [comment]
So between Oct 23 and the release date of the next stable Debian (still unknown) it won't be possible to install NextCloud on Debian stable with supported package. It may lead to lots of outdated Nextcloud installation or non-updated PHP 8 installation. In either case, it may be a security concern...
It was already a discussion during previous Debian stable lifecycle...

**Comment by ChristophWurst** [comment]
If I look at https://en.wikipedia.org/wiki/Debian_version_history#Release_history then Debian pushes out their stable releases in 2 year cycles. Shouldn't that give us a very rough ETA of 2023 for Debian 12?

**Comment by digitalfox** [comment]
If they stick to this (unofficial) release date, yes, everything will be ok.
