### ISSUE TITLE
Some preview images generated with imaginary are incorrect.

### ISSUE THREAD

**Issue by janusn** [nextcloud/server#35026]
Some square preview images generated with command
`$ occ preview:generate-all -vvv`
are a crop of the original images and the aspect ratio are not preserved.
On the other hand, the square preview images generated by web interface of Nextcloud are correctly. They respect the aspect ratios and letterboxed correctly.

Environment:

- Nextcloud docker: linuxserver/nextcloud:latest

> - Nextcloud version 24.0.6
> - previewgenerator version 5.1.0

- imaginary docker: h2non/imaginary:latest

> - Imaginary version 1.2.4

- host OS: DSM 7.1.1-42962 Update 1
- hardware: Synology DS-918+

The content of the config.php:
```
<?php
$CONFIG = array (
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'redis',
    'port' => 6379,
    'timeout' => 1.5,
  ),
  'filelocking.enabled' => true,
  'datadirectory' => '/data',
  'instanceid' => '<omitted for security>',
  'passwordsalt' => '<omitted for security>',
  'secret' => '<omitted for security>',
  'trusted_domains' => 
  array (
    0 => '<omitted> for security>',
  ),
  'dbtype' => 'mysql',
  'version' => '24.0.6.1',
  'trusted_proxies' => ['swag'],
  'overwrite.cli.url' => '<omitted for security>',
  'dbname' => 'nextcloud',
  'dbhost' => '10.27.0.40:3306',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '<omitted for security>',
  'dbpassword' => '<omitted for security>',
  'installed' => true,
  'app_install_overwrite' => 
  array (
    0 => 'files_excludedirs',
  ),
  'default_phone_region' => 'GB',
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_sendmailmode' => 'smtp',
  'mail_smtpauth' => 1,
  'mail_from_address' => 'No.Reply',
  'mail_domain' => '<omitted for security>',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => '<omitted for security>',
  'mail_smtpport' => '465',
  'mail_smtpname' => '<omitted for security>',
  'mail_smtppassword' => '<omitted for security>',
  'preview_max_x' => null,
  'preview_max_y' => null,
  'jpeg_quality' => '60',
  'preview_max_scale_factor' => 1,
  'enabledPreviewProviders' => [
    'OC\Preview\MP3',
    'OC\Preview\TXT',
    'OC\Preview\MarkDown',
    'OC\Preview\OpenDocument',
    'OC\Preview\Krita',
    'OC\Preview\Imaginary',
  ],
  'preview_imaginary_url' => 'http://imaginary:9000',
);
```

The previewgenerator settings:
```
$ php /config/www/nextcloud/occ config:app:get previewgenerator squareSizes
64 256 1024
$ php /config/www/nextcloud/occ config:app:get previewgenerator widthSizes
64 256 1024
$ php /config/www/nextcloud/occ config:app:get previewgenerator heightSizes
64 256 1024
```

A sample of an original image: 
![(m=e-yaaGqaa)(mh=X0mu4De6Iz0XIN25)original_419254021](https://user-images.githubusercontent.com/21253783/200041760-34ad1f18-4f18-42bc-8549-486b11ad6d82.jpg)

The preview generated for both grid view and detailed view on the Files pane.
![1024-1024-crop](https://user-images.githubusercontent.com/21253783/200042005-39e74c9b-b6ce-4833-a9f8-e82b23ada8c3.jpg)

Another example of an original image:
![37](https://user-images.githubusercontent.com/21253783/200042733-9284683a-bf54-4180-b0e4-63faba51b630.jpg)

The preview generated for both grid view and detailed view on the Files pane.
![1024-1024-crop-1](https://user-images.githubusercontent.com/21253783/200042792-55a96c2c-3ce2-4390-b3f3-6d4aa512268d.jpg)

**Comment by st3iny** [comment]
Ref https://github.com/nextcloud/previewgenerator/issues/323
