### ISSUE TITLE
[Bug]: Declaration of OCA\Theming\ThemingDefaults::getScssVariables() must be compatible with OC_Defaults::getScssVariables(bool $brightBackground = true)

### ISSUE THREAD

**Issue by mvvvmd** [nextcloud/server#35038]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading to v25.0.1 running any occ command fails with the following error:

PHP Fatal error:  Declaration of OCA\Theming\ThemingDefaults::getScssVariables() must be compatible with OC_Defaults::getScssVariables(bool $brightBackground = true) in /var/www/vhosts/nextcloud/apps/theming/lib/ThemingDefaults.php on line 347

### Steps to reproduce

1. Upgrade to v25.0.1
2. Run a occ command

### Expected behavior

The occ command should run.

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
n/a
```

### List of activated Apps

```shell
n/a
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"XQhiTDccnIOTajXgB6RP","level":3,"time":"2022-11-08T20:23:31+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Declaration of OCA\\Theming\\ThemingDefaults::getScssVariables() must be compatible with OC_Defaults::getScssVariables(bool $brightBackground = true) at /var/www/vhosts/nextcloud/apps/theming/lib/ThemingDefaults.php#347","userAgent":"--","version":"24.0.6.1","data":{"app":"PHP"},"id":"636abb2041e74"}
```

### Additional info

n/a

**Comment by kesselb** [comment]
Hi,

It looks fine in git. 

https://github.com/nextcloud/server/blob/83d85bd0450c18d9ab218494fef923c51e3c3c78/lib/private/legacy/OC_Defaults.php#L311-L314

https://github.com/nextcloud/server/blob/83d85bd0450c18d9ab218494fef923c51e3c3c78/apps/theming/lib/ThemingDefaults.php#L343-L347

Could be a file not properly replaced during the upgrade or an old state in opcache.

**Comment by mvvvmd** [comment]
Yes, it seems to have been cache, I had restarted Apache and Redis, even upgraded from php 7.4  to 8.1. Just now restarted Apache again and it works.
