### ISSUE TITLE
`OCP\Calendar\ICalendar::getUri` not documented

### ISSUE THREAD

**Issue by susnux** [nextcloud/server#35041]
In NC24 the method `getUri` was added to `ICalendar`,  but not documented, so some hint about its purpose is missing.
Is it the same as `getKey`? Is the URL not build like this: `/remote.php/caldav/calendars/USERID/UNIQUE_KEY`?

**Comment by susnux** [comment]
Thank you, so `Key` is a global unique id whereas `URI` is a local (in user scope) unique "ID".

**Comment by Pytal** [comment]
> Thank you, so `Key` is a global unique id whereas `URI` is a local (in user scope) unique "ID".

Yep :)
