### ISSUE TITLE
showNotification closes Gallery view (probably others too)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#3504]
I just had a picture open in the Gallery view. After a few seconds it closed by itself, seemingly because there was a notification about »Nextcloud daily is available …«

These notifications should obviously not result in closing anything and interrupting the flow. Might be an issue with others like texteditor too.

cc @nextcloud/javascript @nextcloud/gallery

**Comment by MorrisJobke** [comment]
This will be fixed together with removing the OC.Notifications. See https://github.com/nextcloud/server/pull/4102#issuecomment-297214731

**Comment by jancborchardt** [comment]
Didn’t have this issue in some time – let’s close.
