### ISSUE TITLE
There was no plugin in the system that was willing to handle this POST method

### ISSUE THREAD

**Issue by sporykhin** [nextcloud/server#3506]
Hey

I'm trying to implement nextcloud file sharing solution that uses sabre/dav as backend for Calendar web application. In the web browser everything is really nice. Then I connected Calendar.app to this service I got only limited feature list - I cant share calendar and cant send email invitation on some event.
Also I have a lot of errors in server log with main point - Sabre\DAV\Exception\NotImplemented: HTTP/1.1 501 There was no plugin in the system that was willing to handle this POST method.

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/nextcloud/apps/dav/lib/Server.php - line 227: Sabre\DAV\Server->exec()
/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 30: OCA\DAV\Server->exec()
/var/www/nextcloud/remote.php - line 165: require_once('/var/www/nextcl...')

Is it system misconfiguration or some bug?

**Comment by nickvergessen** [comment]
We already have caldav support and it also supports sharing. Not sure what you are trying to do.

**Comment by sporykhin** [comment]
HI
I'm trying to share calendar not from webapp (browser) but from Calendar.app (macos sierra)
So the question is this app support native Apple calendars and can I use this  iCloud alternative

**Comment by sporykhin** [comment]
@nickvergessen What kind of info do you need?
Still the same error with Apple Calendar.app

**Comment by nickvergessen** [comment]
e.g. which request was send to the server

**Comment by sporykhin** [comment]
Sorry for the noob question but how I can get this request?

**Comment by nickvergessen** [comment]
Check your servers access.log file

**Comment by sporykhin** [comment]
@nickvergessen sorry for delay

from nextcloud.log

{"reqId":"lt95m7bJep6XzJtQXh6F","remoteAddr":"188.244.132.5","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 501 There was no plugin in the system that was willing to handle this POST method.\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotImplemented\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/nginx\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/usr\\\/share\\\/nginx\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(227): Sabre\\\\DAV\\\\Server->exec()\\n#2 \\\/usr\\\/share\\\/nginx\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#3 \\\/usr\\\/share\\\/nginx\\\/nextcloud\\\/remote.php(165): require_once('\\\/usr\\\/share\\\/ngin...')\\n#4 {main}\",\"File\":\"\\\/usr\\\/share\\\/nginx\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":487,\"User\":\"nextcloudadmin\"}","level":4,"time":"2017-04-02T19:59:25+00:00","method":"POST","url":"\/remote.php\/dav\/calendars\/nextcloudadmin\/personal\/","user":"nextcloudadmin","version":"11.0.2.7"}

**Comment by sporykhin** [comment]
from access.log

188.244.132.5 - nextcloudadmin [02/Apr/2017:20:13:30 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 401 "-" "Mozilla/5.0 (Macintosh) mirall/2.2.4 (build 1) (Nextcloud)"
188.244.132.5 - - [02/Apr/2017:20:13:35 +0000] "POST /remote.php/dav/calendars/nextcloudadmin/personal/ HTTP/1.1" 401 567 "-" "Mac+OS+X/10.12.4 (16E195) CalendarAgent/386"
188.244.132.5 - nextcloudadmin [02/Apr/2017:20:13:35 +0000] "POST /remote.php/dav/calendars/nextcloudadmin/personal/ HTTP/1.1" 501 288 "-" "Mac+OS+X/10.12.4 (16E195) CalendarAgent/386"
188.244.132.5 - nextcloudadmin [02/Apr/2017:20:13:35 +0000] "POST /remote.php/dav/calendars/nextcloudadmin/personal/ HTTP/1.1" 501 288 "-" "Mac+OS+X/10.12.4 (16E195) CalendarAgent/386"
188.244.132.5 - nextcloudadmin [02/Apr/2017:20:13:35 +0000] "POST /remote.php/dav/calendars/nextcloudadmin/personal/ HTTP/1.1" 501 288 "-" "Mac+OS+X/10.12.4 (16E195) CalendarAgent/386"
188.244.132.5 - nextcloudadmin [02/Apr/2017:20:13:39 +0000] "POST /remote.php/dav/calendars/nextcloudadmin/personal/ HTTP/1.1" 501 288 "-" "Mac+OS+X/10.12.4 (16E195) CalendarAgent/386"
188.244.132.5 - nextcloudadmin [02/Apr/2017:20:13:39 +0000] "POST /remote.php/dav/calendars/nextcloudadmin/personal/ HTTP/1.1" 501 288 "-" "Mac+OS+X/10.12.4 (16E195) CalendarAgent/386"
188.244.132.5 - nextcloudadmin [02/Apr/2017:20:13:39 +0000] "POST /remote.php/dav/calendars/nextcloudadmin/personal/ HTTP/1.1" 501 288 "-" "Mac+OS+X/10.12.4 (16E195) CalendarAgent/386"
188.244.132.5 - - [02/Apr/2017:20:13:39 +0000] "PROPFIND /remote.php/dav/calendars/nextcloudadmin/ HTTP/1.1" 401 567 "-" "Mac+OS+X/10.12.4 (16E195) CalendarAgent/386"
188.244.132.5 - nextcloudadmin [02/Apr/2017:20:13:40 +0000] "PROPFIND /remote.php/dav/calendars/nextcloudadmin/ HTTP/1.1" 207 13763 "-" "Mac+OS+X/10.12.4 (16E195) CalendarAgent/386"
188.244.132.5 - nextcloudadmin [02/Apr/2017:20:13:40 +0000] "PROPFIND /remote.php/dav/calendars/nextcloudadmin/inbox/ HTTP/1.1" 207 501 "-" "Mac+OS+X/10.12.4 (16E195) CalendarAgent/386"
188.244.132.5 - nextcloudadmin [02/Apr/2017:20:13:40 +0000] "PROPFIND /remote.php/dav/calendars/nextcloudadmin/inbox/ HTTP/1.1" 207 501 "-" "Mac+OS+X/10.12.4 (16E195) CalendarAgent/386"
188.244.132.5 - nextcloudadmin [02/Apr/2017:20:13:40 +0000] "POST /remote.php/dav/calendars/nextcloudadmin/personal/ HTTP/1.1" 501 288 "-" "Mac+OS+X/10.12.4 (16E195) CalendarAgent/386"
188.244.132.5 - nextcloudadmin [02/Apr/2017:20:13:40 +0000] "POST /remote.php/dav/calendars/nextcloudadmin/personal/ HTTP/1.1" 501 288 "-" "Mac+OS+X/10.12.4 (16E195) CalendarAgent/386"
188.244.132.5 - nextcloudadmin [02/Apr/2017:20:13:40 +0000] "POST /remote.php/dav/calendars/nextcloudadmin/personal/ HTTP/1.1" 501 288 "-" "Mac+OS+X/10.12.4 (16E195) CalendarAgent/386"
188.244.132.5 - - [02/Apr/2017:20:13:41 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"

**Comment by nickvergessen** [comment]
Yeah, looks like your mac os calendar app (?) is trying to POST instead of PUT against the caldav endpoint. That won't work and is not what the standard says. Please report to the providers of the app.

**Comment by rumkol** [comment]
Hi,
I am having the same issue.
@nickvergessen When the sharing is done

**Comment by sporykhin** [comment]
@rumkol @nickvergessen 
I confirm that

So, You propose me to open an issue ticket in Apple support support about incompatibility with the standard? To be honest I dont believe in success..

**Comment by nickvergessen** [comment]
So you are sharing the calendar via the Mac OS calendar app?

**Comment by sporykhin** [comment]
I tried both from mac app and from web ui.

**Comment by sporykhin** [comment]
@nickvergessen 
So шs there any chance that it will work with Apple calendar app? Or should I look for another solution ?

**Comment by nickvergessen** [comment]
I'm sorry, I have no access to Apple calendar so I can not reproduce and try to fix it.

**Comment by sporykhin** [comment]
May I can help you? I really interested in this product

**Comment by rumkol** [comment]
Hi again,

So, got bit of a spare time and dug a bit more.

What I've tried is adding the plugins and "SharingSupport" interface, as described [here](http://sabre.io/dav/caldav-sharing/), which makes the error mentioned disappear, but seems that is not enough as there are new things implemented(like calendar instances) in the new version of SabreDAV, which is beyond my skill set to handle.

Would be nice, if someone more knowledgeable can help or give some hints how to do it.

Thanks!
