### ISSUE TITLE
Headings need to be h2

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#35098]
@jancborchardt @PVince81 @Pytal could you please give me some examples where should i check headings? I've checked a bit and could find them in ```app-sidebar-header```, ```tags```, everywhere in ```settings/``` (besides ```settings/user```) -> have already ```<h2>```. Besides this there are sites with tables. And i don't really know where should i place ```<h2>``` in this case.

Thanks!

**Comment by Pytal** [comment]
This is for headings in the user status dialog @JuliaKirschenheuter?

![image](https://user-images.githubusercontent.com/24800714/202341092-2a134ca9-870c-4aa4-a04d-e0348ab2649f.png)

Code would be in https://github.com/nextcloud/server/tree/master/apps/user_status
