### ISSUE TITLE
[Feature] Show custom icons in files view

### ISSUE THREAD

**Issue by terenc3** [nextcloud/server#35123]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I've organized my files and also use some cool icons for my folders e.g. car, house icon etc. I've used a desktop.ini file to set the icons, e.g.

```
[.ShellClassInfo]
IconResource=desktop.ico,0
```
now it would be great if Nextcloud could show these icons.

**Describe the solution you'd like**
I'd like to see my custom icons which a used in Windows in the files view. I've created a mock with CSS below

![Bildschirmfoto am 2022-11-12 um 20 43 34](https://user-images.githubusercontent.com/766518/201492035-512039a2-153d-4be4-b4a6-85561c3f6675.png)
Icons used:
<a href="https://www.flaticon.com/free-icons/user-guide" title="user guide icons">User guide icons created by Earthz Stocker - Flaticon</a>
<a href="https://www.flaticon.com/free-icons/car" title="car icons">Car icons created by Konkapp - Flaticon</a>
<a href="https://www.flaticon.com/de/kostenlose-icons/eigentum" title="eigentum Icons">Eigentum Icons erstellt von Icongeek - Flaticon</a>
<a href="https://www.flaticon.com/free-icons/bank" title="bank icons">Bank icons created by IconMarketPK - Flaticon</a>
<a href="https://www.flaticon.com/de/kostenlose-icons/lebenslauf" title="lebenslauf Icons">Lebenslauf Icons erstellt von Freepik - Flaticon</a>

**Comment by pavanvo** [comment]
I also was thinking about folder icons, but I found there is a problem with two type of icons.
NC uses blue folder icon for background, so  foreground icons for Shared, Private folders will not be seen

**Comment by terenc3** [comment]
Hm i've also digged a little bit into the code and it seems that the icons are cached by mime type (also folder, folder-external and folder-shared), so this seem to much trouble. Closing it now.

https://github.com/nextcloud/server/blob/master/lib/private/Files/Type/Detection.php#L341
