### ISSUE TITLE
[Bug]: Context menu too narrow for text when triggered from grid view

### ISSUE THREAD

**Issue by floeschie** [nextcloud/server#35153]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I trigger the context menu in the File app using the three dots, some menu items of the context menu overflow the border:

![Bildschirm­foto 2022-11-14 um 15 17 42](https://user-images.githubusercontent.com/1119719/201683258-02ce1932-184d-422a-ba71-c0dc7d8c8b88.png)

This only happens when grid view is active.

### Steps to reproduce

1. Open files app
2. Switch to grid view
3. Click the 3 dots on a random item to open the context menu

### Expected behavior

When I right-click on the same item instead of left clicking on the three dots, the context menu looks fine:

![Bildschirm­foto 2022-11-14 um 15 21 04](https://user-images.githubusercontent.com/1119719/201683672-1e7eff99-e7b9-449b-b34a-93711f5bd8e8.png)

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "my.host.tld"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.1.1",
        "overwrite.cli.url": "https:\/\/my.host.tld",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "pipe",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "DE",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "trashbin_retention_obligation": "auto, 30"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - bookmarks: 11.0.4
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - music: 1.7.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - ransomware_protection: 1.14.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.1
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - twofactor_webauthn: 1.0.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - activity: 2.17.0
  - admin_audit
  - bruteforcesettings
  - dashboard: 7.5.0
  - encryption
  - firstrunwizard: 2.14.0
  - photos: 2.0.0
  - suspicious_login
  - twofactor_gateway: 0.20.0
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional info

Language set to German (informal) in personal settings.

**Comment by PVince81** [comment]
confirmed on 25.0.1:
<img width="92" alt="image" src="https://user-images.githubusercontent.com/277525/202452277-d6792d3e-3f7b-4f49-966c-8a7d496cd71d.png">

**Comment by salixor** [comment]
Unsure if I should create a different issue, but there's another issue with the menu currently (v25.0.1). Menu items also can't be clicked outside of label. For instance :

![image](https://user-images.githubusercontent.com/12085737/203584940-ddb31874-c6bd-4463-b0a1-0cf58be6133a.png)

It feels out of place as we expect the whole "item" to be clickable.

This is most likely stemming from the same root cause.

**Comment by szaimen** [comment]
Please try again with 25.0.2
