### ISSUE TITLE
[Bug]: 2fa overview looks a bit off

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#35196]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Found on c.nc.c when login in:

![image](https://user-images.githubusercontent.com/5836855/202096598-97a5269b-51eb-47c7-b413-87f3322a08df.png)

### Steps to reproduce

1. log into c.nc.c
2. have different 2fa 

### Expected behavior

better looking, centered, correct margins, maybe not this grey?

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
/
```

**Comment by joshtrichards** [comment]
Looks good today (>=25)
