### ISSUE TITLE
Save backup codes is broken

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#3520]
Try pressing it and the file will contain anything but not the codes in chrome at least 😉

**Comment by MorrisJobke** [comment]
Sure that this is not related to #2704 ?

**Comment by LukasReschke** [comment]
Fails on RC2. Patch should be in RC2 => Pretty sure :)

**Comment by MorrisJobke** [comment]
> Fails on RC2. Patch should be in RC2 => Pretty sure :)

https://github.com/nextcloud/server/commit/e111015afab4e21fb6a722746e9ad9ed86ad0c10 🙈 You forgot to add the RC2 git tag 😉

**Comment by ChristophWurst** [comment]
Dang it. It's broken indeed, possibly by the other "fix". Now printing works but saving doesn't.
