### ISSUE TITLE
[Bug]:  /login redirect when uses HTTPS redirect to http always even when override protocol to https, in docker container

### ISSUE THREAD

**Issue by enginecoremx** [nextcloud/server#35217]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When the user is not login the redirect to  /login always redirects to HTTP.

The server is behind an Nginx. Nginx terminates the SSL sending HTTP traffic to the container
```
<?php
$CONFIG = array (
  'trusted_proxies'   => ['10.0.0.1'],
  'overwritehost'     => 'my.server.com',
  'overwriteprotocol' => 'https',
  'overwritewebroot'  => '/',
  'overwritecondaddr' => '^10\.0\.0\.1$',
);

```

Is the code sending "location" to the browser not a redirect to /login

```
$ curl https://my.server.com -I
HTTP/2 302
server: nginx
date: Wed, 16 Nov 2022 02:14:26 GMT
content-type: text/html; charset=UTF-8
referrer-policy: no-referrer
x-content-type-options: nosniff
x-download-options: noopen
x-frame-options: SAMEORIGIN
x-permitted-cross-domain-policies: none
x-robots-tag: none
x-xss-protection: 1; mode=block
set-cookie: occhkxy75tz7=07caba8dd29e6476091af647df6da9a3; path=/; HttpOnly; SameSite=Lax
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
set-cookie: oc_sessionPassphrase=uTBTGN%2F1ovOE745PWY9pyipCR3FaM862GwSKOXFcasZgoAd%2FrLpWxeaEHM5qhFQI%2F0dFsexyUw60gTLu1yq7XjhvZh77B26kNHumFyija%2BmiPu%2BREXR0bQC04o5MDqLG; path=/; HttpOnly; SameSite=Lax
set-cookie: occhkxy75tz7=8afbaa1b7ea44e4d40e5d64a03203590; path=/; HttpOnly; SameSite=Lax
content-security-policy: default-src 'self'; script-src 'self' 'nonce-akkzVER1cXZLWmpHQWhmVXFVc0Y3eVBrbk9kU1FwbHk5WDA2QmdBNVZTRT06MytpbmRxYUVYOVAwU0ZUam1Ed3pxMmVDeWFrcmUvd1lrRTBNUzBodEpnbz0='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';
set-cookie: nc_sameSiteCookielax=true; path=/; httponly;expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
set-cookie: nc_sameSiteCookiestrict=true; path=/; httponly;expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
**location: http://my.server.com/login**
strict-transport-security: max-age=63072000; incl``
```

### Steps to reproduce

curl https://my.server.com -I

### Expected behavior

the redirect to location: "my.domain.TLD" should be the same X-origin-proto not HTTP

### Installation method

Community Docker image

### Operating system

RHEL/CentOS

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MySQL

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
none
```

**Comment by szaimen** [comment]
Which nc version and can you post your complete nginx config and config.pgp file here?

**Comment by enginecoremx** [comment]
I will close this petition
I discovered the value in 
'overwritecondaddr' => '10\.2\.51\.166',

was not working, I just comment the variable to do not evaluate the condition and always override the protocol and host
