### ISSUE TITLE
occ command to retrieve file information

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#35211]
For debugging purposes we often need to check information about a specific file.

One idea would be to have an occ command that we can ask people to run with a file id.
The command would then retrieve information like:
- filecache entry + storage information
- share information
- maybe mount information

etc.

Otherwise we need to send around SQL queries with complex joins every time.

@icewind1991 as discussed

**Comment by PVince81** [comment]
please link to teh codez

**Comment by icewind1991** [comment]
https://github.com/nextcloud/server/pull/37525
