### ISSUE TITLE
Three dots menu in files in greyed out

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#3522]
<img width="391" alt="bildschirmfoto 2017-02-17 um 00 23 49" src="https://cloud.githubusercontent.com/assets/245432/23054778/90db48bc-f4a7-11e6-8782-f5cfc9884da0.png">

@skjnldsv Do you have an idea why it looks like that? I would say this change came in during the last 1-2 days roughly.

**Comment by skjnldsv** [comment]
You mean the opacity? Hasn't this be always like that?

**Comment by MorrisJobke** [comment]
> You mean the opacity? Hasn't this be always like that?

Nope. Before it looked like the numbers to the right. It's currently super light - barely readable.

**Comment by skjnldsv** [comment]
Comes from there: https://github.com/nextcloud/server/blame/master/apps/files/css/files.css#L669
Have been around since 2 years :p 

Something else must have been changed. There is a lot of strange stuff on the .action class on files 😕

**Comment by MorrisJobke** [comment]
> Comes from there: https://github.com/nextcloud/server/blame/master/apps/files/css/files.css#L669
> Have been around since 2 years :p

This should only be the share icon and the three dots icon, not the whole menu.

**Comment by MorrisJobke** [comment]
Fix is in #4082
