### ISSUE TITLE
only my admin account is able to login

### ISSUE THREAD

**Issue by mariothiel** [nextcloud/server#3525]
### Steps to reproduce
1. Try to login as another user then the "admin account"

### Expected behaviour
It should let me login 

### Actual behaviour
I get this error message in the browser:
Internal Server Error
The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

Technical details
Remote Address: *.*.*.*
Request ID: *******************

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server: Apache 2

**Database: MySQL

**PHP version: PHP7

**Nextcloud version: 11

**Updated from an older Nextcloud/ownCloud or fresh install: fresh install

**Where did you install Nextcloud from: your website

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "ocorwdm8ut47",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "plexchen.com",
            "www.plexchen.com"
        ],
        "datadirectory": "\/media\/usb2\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/www.plexchen.com\/nextcloud",
        "dbtype": "mysql",
        "version": "11.0.1.2",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "htaccess.RewriteBase": "\/nextcloud",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        }
    }
}
</details>

**Are you using external storage, if yes which one: For my data folder only

**Are you using encryption: no

### Client configuration
**Browser:** Chrome, Edge

**Operating system:** Windows

#### Web server error log
<details>
<summary>Web server error log</summary>

[Fri Feb 17 14:51:45.163564 2017] [autoindex:error] [pid 5177] [client 192.168.173.1:9809] AH01276: Cannot serve directory /var/www/html/nextcloud: No matching DirectoryIndex (none) found, and server-generated directory index forbidden by Options direc$
[Fri Feb 17 14:51:52.052107 2017] [:error] [pid 5236] [client 192.168.173.1:57450] script '/var/www/html/status.php' not found or unable to stat
[Fri Feb 17 14:51:54.060574 2017] [:error] [pid 5238] [client 192.168.173.1:9816] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:51:54.091103 2017] [:error] [pid 5238] [client 192.168.173.1:9816] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:52:09.127432 2017] [:error] [pid 5180] [client 192.168.173.1:9826] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:52:24.105052 2017] [:error] [pid 5178] [client 192.168.173.1:57451] script '/var/www/html/status.php' not found or unable to stat
[Fri Feb 17 14:52:24.154973 2017] [:error] [pid 5235] [client 192.168.173.1:9867] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:52:24.727194 2017] [autoindex:error] [pid 5238] [client 192.168.173.1:9868] AH01276: Cannot serve directory /var/www/html/nextcloud: No matching DirectoryIndex (none) found, and server-generated directory index forbidden by Options direc$
[Fri Feb 17 14:52:33.864898 2017] [:error] [pid 5180] [client 192.168.173.1:9872] script '/var/www/html/nextcloud/apps/files/cron.php' not found or unable to stat
[Fri Feb 17 14:52:39.186103 2017] [:error] [pid 5237] [client 192.168.173.1:9881] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:52:54.214087 2017] [:error] [pid 5267] [client 192.168.173.1:9893] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:52:56.064903 2017] [:error] [pid 5237] [client 192.168.173.1:57452] script '/var/www/html/status.php' not found or unable to stat
[Fri Feb 17 14:53:09.243177 2017] [:error] [pid 5266] [client 192.168.173.1:9896] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:53:24.273124 2017] [:error] [pid 5235] [client 192.168.173.1:9947] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:53:28.110532 2017] [:error] [pid 5179] [client 192.168.173.1:57454] script '/var/www/html/status.php' not found or unable to stat
[Fri Feb 17 14:53:39.302231 2017] [:error] [pid 5238] [client 192.168.173.1:9955] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:53:54.334100 2017] [:error] [pid 5237] [client 192.168.173.1:9981] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:54:00.057127 2017] [:error] [pid 5235] [client 192.168.173.1:57455] script '/var/www/html/status.php' not found or unable to stat
[Fri Feb 17 14:54:09.361686 2017] [:error] [pid 5238] [client 192.168.173.1:9982] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:54:24.390405 2017] [:error] [pid 5237] [client 192.168.173.1:10004] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:54:32.094770 2017] [:error] [pid 5266] [client 192.168.173.1:57465] script '/var/www/html/status.php' not found or unable to stat
[Fri Feb 17 14:54:39.420394 2017] [:error] [pid 5238] [client 192.168.173.1:10009] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:54:54.449068 2017] [:error] [pid 5235] [client 192.168.173.1:10014] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:55:04.066036 2017] [:error] [pid 5179] [client 192.168.173.1:57469] script '/var/www/html/status.php' not found or unable to stat
[Fri Feb 17 14:55:09.479810 2017] [:error] [pid 5266] [client 192.168.173.1:10019] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:55:24.510381 2017] [:error] [pid 5177] [client 192.168.173.1:10054] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:55:36.120433 2017] [:error] [pid 5239] [client 192.168.173.1:57470] script '/var/www/html/status.php' not found or unable to stat
[Fri Feb 17 14:55:39.537218 2017] [:error] [pid 5180] [client 192.168.173.1:10062] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:55:54.568272 2017] [:error] [pid 5266] [client 192.168.173.1:10090] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:56:08.057319 2017] [:error] [pid 5176] [client 192.168.173.1:57471] script '/var/www/html/status.php' not found or unable to stat
[Fri Feb 17 14:56:09.595901 2017] [:error] [pid 5235] [client 192.168.173.1:10097] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:56:24.628217 2017] [:error] [pid 5179] [client 192.168.173.1:10099] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:56:39.654898 2017] [:error] [pid 5176] [client 192.168.173.1:10101] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:56:40.193448 2017] [:error] [pid 5235] [client 192.168.173.1:57473] script '/var/www/html/status.php' not found or unable to stat
[Fri Feb 17 14:56:54.685086 2017] [:error] [pid 5266] [client 192.168.173.1:10103] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:57:09.719290 2017] [:error] [pid 5267] [client 192.168.173.1:10131] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:57:12.081964 2017] [:error] [pid 5239] [client 192.168.173.1:57474] script '/var/www/html/status.php' not found or unable to stat
[Fri Feb 17 14:57:24.743729 2017] [:error] [pid 5177] [client 192.168.173.1:10163] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:57:39.774108 2017] [:error] [pid 5238] [client 192.168.173.1:10165] script '/var/www/html/remote.php' not found or unable to stat
[Fri Feb 17 14:57:44.188109 2017] [:error] [pid 5180] [client 192.168.173.1:57475] script '/var/www/html/status.php' not found or unable to stat
[Fri Feb 17 14:57:54.801628 2017] [:error] [pid 5239] [client 192.168.173.1:10167] script '/var/www/html/remote.php' not found or unable to stat

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

Error	index	OCP\Files\NotFoundException: 
/var/www/html/nextcloud/apps/files/lib/Controller/ViewController.php - line 136: OC_Helper getStorageInfo('/', false)
/var/www/html/nextcloud/apps/files/lib/Controller/ViewController.php - line 199: OCA\Files\Controller\ViewController->getStorageInfo()
[internal function] OCA\Files\Controller\ViewController->index('', '', NULL, false)
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Files\Controller\ViewController), 'index')
/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files\Controller\ViewController), 'index')
/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('ViewController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/html/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/html/nextcloud/lib/base.php - line 1010: OC\Route\Router->match('/apps/files/')
/var/www/html/nextcloud/index.php - line 40: OC handleRequest()
{main}

Error	gallery	RedisException: Redis server went away
/var/www/html/nextcloud/lib/private/Memcache/Redis.php - line 114: Redis->incrBy('10b53f42a561be4...', 1)
/var/www/html/nextcloud/lib/private/Lock/MemcacheLockingProvider.php - line 73: OC\Memcache\Redis->inc('files/65d4451b9...')
/var/www/html/nextcloud/lib/private/Files/Storage/Common.php - line 680: OC\Lock\MemcacheLockingProvider->acquireLock('files/65d4451b9...', 1)
/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 588: OC\Files\Storage\Common->acquireLock('files/gallery.c...', 1, Object(OC\Lock\MemcacheLockingProvider))
/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 588: OC\Files\Storage\Wrapper\Wrapper->acquireLock('files/gallery.c...', 1, Object(OC\Lock\MemcacheLockingProvider))
/var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 588: OC\Files\Storage\Wrapper\Wrapper->acquireLock('files/gallery.c...', 1, Object(OC\Lock\MemcacheLockingProvider))
/var/www/html/nextcloud/lib/private/Files/View.php - line 1894: OC\Files\Storage\Wrapper\Wrapper->acquireLock('files/gallery.c...', 1, Object(OC\Lock\MemcacheLockingProvider))
/var/www/html/nextcloud/lib/private/Files/View.php - line 1997: OC\Files\View->lockPath('/mtr/files/gall...', 1, false)
/var/www/html/nextcloud/lib/private/Files/View.php - line 1295: OC\Files\View->lockFile('/mtr/files/gall...', 1)
/var/www/html/nextcloud/lib/private/Files/View.php - line 1342: OC\Files\View->getCacheEntry(Object(OCA\Files_Trashbin\Storage), 'files/gallery.c...', '/mtr/files/gall...')
/var/www/html/nextcloud/lib/private/Files/Node/Root.php - line 196: OC\Files\View->getFileInfo('/mtr/files/gall...')
/var/www/html/nextcloud/lib/private/Files/Node/Folder.php - line 122: OC\Files\Node\Root->get('/mtr/files/gall...')
/var/www/html/nextcloud/lib/private/Files/Node/Folder.php - line 131: OC\Files\Node\Folder->get('gallery.cnf')
/var/www/html/nextcloud/apps/gallery/service/configservice.php - line 191: OC\Files\Node\Folder->nodeExists('gallery.cnf')
/var/www/html/nextcloud/apps/gallery/service/configservice.php - line 101: OCA\Gallery\Service\ConfigService->configExists(Object(OC\Files\Node\Folder))
/var/www/html/nextcloud/apps/gallery/controller/config.php - line 47: OCA\Gallery\Service\ConfigService->getFeaturesList()
/var/www/html/nextcloud/apps/gallery/controller/configcontroller.php - line 64: OCA\Gallery\Controller\ConfigController->getConfig(true)
[internal function] OCA\Gallery\Controller\ConfigController->get(true)
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Gallery\Controller\ConfigController), 'get')
/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Gallery\Controller\ConfigController), 'get')
/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('ConfigControlle...', 'get', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/html/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/html/nextcloud/lib/base.php - line 1010: OC\Route\Router->match('/apps/gallery/c...')
/var/www/html/nextcloud/index.php - line 40: OC handleRequest()
{main}

</details>

**Comment by MorrisJobke** [comment]
```
AH01276: Cannot serve directory /var/www/html/nextcloud: No matching DirectoryIndex (none) found, and server-generated directory index forbidden by Options direc
```

and

```
'/var/www/html/remote.php' not found or unable to stat
```

seems to be the problem. Your apache config seems to be wrong and the /var/www/html folder seems to not contain the correct files.

For more help please ask in the forums at help.nextcloud.com
