### ISSUE TITLE
l10n: String (number) does not need to be translatable

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/server#35252]
Reported at Transifex.

404 is just a number.

https://github.com/nextcloud/server/blob/473647a467d807703818f3d9f55352825a345bea/lib/base.php#L1102

**Comment by szaimen** [comment]
Cc @juliushaertl

**Comment by szaimen** [comment]
I'd say lets just remove the translation of the 404? The text below that is already translated so it should be fine?
https://github.com/nextcloud/server/blob/473647a467d807703818f3d9f55352825a345bea/lib/base.php#L1102-L1103

**Comment by nimishavijay** [comment]
> Though the text feels a bit duplicate there. 

Yes for sure. Would there be a reason for this sort of error? We could specify that, for eg. "The file you are looking for doesn't exist or may have been deleted." or something similar to that.

**Comment by juliushaertl** [comment]
Most likely the URL is just wrong, either mistyped or no longer available (in case of a share link).

**Comment by nimishavijay** [comment]
How about "Check the address or make sure the file is still shared with you"?

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/pull/41036
