### ISSUE TITLE
[Bug]: Editing documents as guest in shared folders no longer possible (NC25)

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/server#35276]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After updating to Nextcloud 25.0.0 it is no longer possible for guests to edit documents in shared folders with read/write access. If users click a document, it will only be offered to download but it will not be opened in the OnlyOffice document editor.

However, the same share works fine as soon as a user is logged in and no longer acts as a guest.

On the other hand when sharing individual documents, editing still works as expected.

So far I don't know if this is an issue with Nextcloud or with the integration app. Also see https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/740

Server: Nextcloud 25.0.1 (also happens with 25.0.0)
OnlyOffice integration app: 7.6.8
OnlyOffice document server (Docker based): Community edition 7.10.215

### Steps to reproduce

1. Install OnlyOffice using the docker container or standalone server by Ascensio
2. Install the OnlyOffice integrationapp (https://apps.nextcloud.com/apps/onlyoffice)
3. Create a folder and share it as link for guests with the option to allow editing and upload
4. Create a new office document in the folder (test.docx)
5. Open the share link as guest
6. Try to open the office document created in step 4 as guest
7. The document will only be offered as download using a link in the form `https://server.example/s/<SOMESTRING>/?path=%2F&openfile=<ID>` and not opened in the OnlyOffice editor with a link like `https://server.example/s/<SOMESTRING>/download/?path=%2F&openfile=<ID>`

### Expected behavior

If the OnlyOffice integration app is active, the links to individual office files in shared folders for guests are in the form `https://server.example/s/<SOMESTRING>/?path=%2F&openfile=<ID>` so guests can still open the document inside the browser and don't need to download them.

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.0x0c.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "overwrite.cli.url": "https:\/\/nextcloud.0x0c.de",
        "dbtype": "mysql",
        "version": "25.0.1.1",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "knowledgebaseenabled": false,
        "theme": "",
        "simpleSignUpLink.shown": false,
        "loglevel": 2,
        "log_authfailip": true,
        "mysql.utf8mb4": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "trashbin_retention_obligation": "auto, 30",
        "app_install_overwrite": [
            "apporder",
            "deck",
            "keeweb",
            "appointments",
            "drawio",
            "bookmarks",
            "spreed",
            "unroundedcorners",
            "fulltextsearch",
            "fulltextsearch_elasticsearch",
            "files_fulltextsearch",
            "files_fulltextsearch_tesseract",
            "passwords",
            "gpxpod"
        ],
        "has_rebuilt_cache": true,
        "onlyoffice": {
            "verify_peer_off": true
        },
        "default_language": "de",
        "default_phone_region": "DE",
        "check_data_directory_permissions": false,
        "log_rotate_size": 52428800
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - apporder: 0.15.0
  - bookmarks: 11.0.4
  - calendar: 4.1.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.1
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.2
  - drawio: 1.0.5
  - external: 5.0.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_fulltextsearch: 24.0.1
  - files_fulltextsearch_tesseract: 24.0.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - forms: 3.0.1
  - fulltextsearch: 24.0.0
  - fulltextsearch_elasticsearch: 24.0.1
  - gpxpod: 5.0.4
  - keeweb: 0.6.10
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - onlyoffice: 7.6.8
  - password_policy: 1.15.0
  - photos: 2.0.0
  - polls: 4.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - theming_customcss: 1.12.0
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - bruteforcesettings: 2.2.0
  - encryption: 2.2.0
  - files_external: 1.15.0
  - quota_warning: 1.15.0
  - recommendations: 0.4.0
  - spreed: 15.0.1
  - suspicious_login
  - twofactor_totp
  - user_ldap
  - weather_status: 1.3.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
(omitted since the log is more than 40 MB big and contains sensitive information)
```

### Additional info

Sharing individual files as links with editing rights directly still works.

**Comment by szaimen** [comment]
Hm... not sure if this not an issue with the onlyoffice app. Can you also open an issue there? Thanks!

https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues

**Comment by arnowelzel** [comment]
> Hm... not sure if this not an issue with the onlyoffice app. Can you also open an issue there? Thanks!
> 
> https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues

I already did a while ago and also references this is in the issue above:

https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/740

But to make sure nothing gets overlooked, I created the issue on both sides.

**Comment by FelixBuehler** [comment]
Can confirm this issue after upgrading to NC25, but not changing anything in onlyoffice docker.

**Comment by PVince81** [comment]
@juliushaertl can you check ?

**Comment by juliushaertl** [comment]
Seems this has been fixed in the ONLYOFFICE app with https://github.com/ONLYOFFICE/onlyoffice-nextcloud/commit/63b68953d807afc3397771507c210be006ed0330

**Comment by michel-thomas** [comment]
After testing (Nextcloud 25.0.4, OnlyOffice 7.6.8), it is mostly [#757](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/pull/757) which correct the problem.
