### ISSUE TITLE
[Bug]: previews are not getting deleted after file removal

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#35290]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Preview files are not getting deleted.

### Steps to reproduce

1. upload an image
2. see 2-x preview files in data/appdata/preview
3. delete file, remove it from trash
4. run cron.php (for potential cleanup)
5. see those files still there

### Expected behavior

Preview files should get deleted after removing the file.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Docker with latest master
```

### List of activated Apps

```shell
/
```

**Comment by tobiasKaminsky** [comment]
In addition it would then be great to have a cleanup task to get the old previews removed.

**Comment by juliushaertl** [comment]
The job is only running once per hour: https://github.com/nextcloud/server/blob/0670118470a9133749d630078f8b69d0e62c3e52/lib/private/Preview/BackgroundCleanupJob.php#L55 Maybe you can check your oc_jobs table if that job was recently executed

**Comment by tobiasKaminsky** [comment]
Right. This works now!

Sorry for the noise.

**Comment by tobiasKaminsky** [comment]
However it does not seem to delete the empty folders, but this might not be needed:
```
./6
./6/7
./6/7/c
./6/7/c/6
./6/7/c/6/a
./6/7/c/6/a/1
./6/7/c/6/a/1/e
./a
./a/d
./a/d/6
./a/d/6/1
./a/d/6/1/a
./a/d/6/1/a/b
./a/d/6/1/a/b/1
./a/d/6/1/a/b/1/74
./a/d/6/1/a/b/1/74/
./a/d/6/1/a/b/1/74/
./d
./d/0
./d/0/9
./d/0/9/b
./d/0/9/b/f
./d/0/9/b/f/4
./d/0/9/b/f/4/1
```
