### ISSUE TITLE
gzipped JSONResponse?

### ISSUE THREAD

**Issue by Rello** [nextcloud/server#3529]
`\OCP\AppFramework\Http\JSONResponse` is used for ajax responses in JSON format.

But there does not seem to be an option to gzip the response from the server?
The manual workaround via

		ob_start('ob_gzhandler');
		header('Content-type: application/json');
		echo json_encode($result);
		ob_end_flush();

des not seem to be very integrated approach in app development.

the nextcloud config suggests to disable it globally (e.g. in nginx)

		-Disable gzip to avoid the removal of the ETag header
		gzip off;

Also you cannot use both ob_gzhandler() and zlib.output_compression if your php is configured like that.

I there a better way to minimize the network traffic for slow connections?
I am talking about several MB metadata for big libraries in Audio Player.

thanks for help on this

**Comment by nickvergessen** [comment]
I don't think so.

**Comment by skjnldsv** [comment]
@Rello what is the usual standard for that? A request header for gzip?

**Comment by Rello** [comment]
Hey,
nice finding of that old thread. I guess it was changes some time in NC server somewhere.
I can see the jsons being compressed now

![Screenshot 2019-06-12 at 16 34 10](https://user-images.githubusercontent.com/13385119/59360159-eb2bb400-8d2f-11e9-8ae2-62fab65562fd.png)

thank you...
