### ISSUE TITLE
Add New User Activity Option To Email When File Changed in Starred Directory 

### ISSUE THREAD

**Issue by cwmke** [nextcloud/server#353]
### Desired Feature
1. Go to the **Activity** tab under **Personal** Settings
2. Select option to email if "A new file or folder has been created in a starred directory"
3. Whenever a file or directory withing a starred directory is created, email the user at the specified time interval.

### Server configuration
**Operating system**: Linux

**Web server:** Apache

**Database:** Postgresql

**PHP version:** 7.0.8-1

**Nextcloud version:** Nextcloud 9.0.52 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** source

I have a specific directory I like to be emailed about after changes occur within.  Currently, the only choice I have is to email when **A new file or folder has been created**.  But this applies to all of my files and diretories and quickly obfuscates the changes I wish to see.

I would like to be able to star a directory/directories and be emailed when changes happen only within these starred directories.  This would require adding an additional option under **Activity** in Personal settings.  I belive this could benefit many users with broad use cases.

Thanks for any consideration!

**Comment by Bugsbane** [comment]
I like this idea in general. I'd also suggest having the notification be triggered when a file or folder in the starred directory is *modified* by another user.

**Comment by cwmke** [comment]
I agree. It could trigger by any modifications by anyone.

**Comment by MorrisJobke** [comment]
This is an activity app feature: https://github.com/nextcloud/activity Please open this over there

**Comment by cwmke** [comment]
Thanks, I opened a new issue there.  nextcloud/activity#4
