### ISSUE TITLE
Provide a direct download link from sharing context menu

### ISSUE THREAD

**Issue by securegh** [nextcloud/server#35304]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

To copy a Direct link to a resource (ie https://…/filename.mp4, https://…/filename.png ). I have to open the public share link  and copy the direct link from there. 
![Capture](https://user-images.githubusercontent.com/113610808/203075099-86fa4f62-81b7-446c-a743-7775840abab0.PNG)

**Describe the solution you'd like**

It would to very convient to have the ability to copy the direct link from the sharing context menu also. (Under or above `Unshare` for example).

![image](https://user-images.githubusercontent.com/113610808/203074608-42ee2853-0532-4bc2-9170-86450b7e8592.png)

**Describe alternatives you've considered**

**Additional context**

I think that is very useful for folks who want to embed their content into social media posts, blogs, forums or stream audio/video directly from a media player(vlc).

This feature is already available with Nextcloud public link share, it’s just need to be conveniently accessible from the sharing context menu.

Thank you considering this feature and thank you for this awesome project!

securegh

**Comment by XueSheng-GIT** [comment]
> This feature is already available with Nextcloud public link share, it’s just need to be conveniently accessible from the sharing context menu.

What's the difference between the "public link share" you are referring to and the link which you can access with "copy to clipboard", which is also shown in your screenshot? Isn't this already the link you want to access?
![grafik](https://user-images.githubusercontent.com/4077683/203309302-8749c54f-e081-4605-83eb-6f27c11076aa.png)

**Comment by SokoFromNZ** [comment]
I also find a direct link to a file way more useful then a webpage showing up when going to `https://nextcloud.tld/s/e3WyR4kyqw3Eb6i`.

What is really anoying: I **cannot** say the following to the people I share public links:
"Just add `download` to the end and you can download the file directly."

Because `https://nextcloud.tld/s/e3WyR4kyqw3Eb6/download` does not work. You have to add/know the filename as well! Only `https://nextcloud.tld/s/e3WyR4kyqw3Eb6/download/filename.mp4` works.

**Comment by securegh** [comment]
@SokoFromNZ We need to rally more people behind this feature it seems like a no brainer to implement!

**Comment by securegh** [comment]
> Also, could this be worked around by appending `/preview` at the end of the URL instead ? for images, it makes the URL display the file only, with no interface or anythng else, maybe that would work for videos too.

The default public share link already provide a preview.  The direct download link is useful for media player or for a download manager. The irony is that it already generated with the default public link, it's just hidden and need to be easily accessible from the sharing context menu. Hopefully someone from the dev team will pick up this feature.

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/issues/3234
