### ISSUE TITLE
[Bug]: Exclude groups from sharing broken

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#35301]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I can't exclude groups from sharing, the required input field in the admin settings is not shown

### Steps to reproduce

1. Go to the admin settings -> sharing
2. check "Exclude Groups from sharing"

Nothing happens:

![grafik](https://user-images.githubusercontent.com/1589737/203062102-a94c1060-b8cb-4eb0-8772-43908e1cc31d.png)

Tested with Nexcloud 25.0.1 and Nextcloud 24.0.7

After the checkbox is checked and I reload the page the input field is there. It seems like "just" the live switch is broken when I check the checkbox

### Expected behavior

A input field show up where I can select the groups I want to exclude:

![grafik](https://user-images.githubusercontent.com/1589737/203061917-c5426eae-21eb-4fba-b00e-379cee150605.png)

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
-
```

**Comment by PVince81** [comment]
confirmed on stable25

**Comment by PVince81** [comment]
it looks like all the checkboxes which have a toggle "hidden" seem to be broken
some only work once when clicking then not again

seems the regression is caused by https://github.com/nextcloud/server/commit/7c8a901b841878c7d63940baa551f5982958874e

@CarlSchwan  can you have a look and make sure that all toggles are working ?

**Comment by CarlSchwan** [comment]
I'm trying to debug this and fun things is that the bug only happen when building in production mode with `npm run build` but not in debug mode

**Comment by PVince81** [comment]
a lot of those visibility management are done with jquery though, not sure why webpack and co would affect it

**Comment by CarlSchwan** [comment]
Yeah and I tried to rewrite it in vanilla js and I got the same result. Work on dev mode breaks in production mode

**Comment by CarlSchwan** [comment]
Looks like the onChange event is not triggered correctly

```
document.getElementById('shareapiExcludeGroups').onclick = () => console.error("clicked") 
document.getElementById('shareapiExcludeGroups').onChange = () => console.error("changed") 
```

Only clicked is displayed when clicking on the checkbox, problem is that clicked is not working for keyboard navigation

**Comment by CarlSchwan** [comment]
I found the issue, patch will arrive soon
