### ISSUE TITLE
[Bug]: logrotate.status is world-readable - nextcloud swag failure on Portainer, OpenMediaVault 6

### ISSUE THREAD

**Issue by CitadelRed** [nextcloud/server#35310]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello, Server was up and running, Swag gives this in logs:
-Server ready (when server was running)
-error: state file /config/log/logrotate.status is world-readable and thus can be locked from other unprivileged users. Skipping lock acquisition...
-run-parts: /etc/periodic/weekly/libmaxminddb: exit status 1
-No MaxMind license key found; exiting. Please enter your license key into /etc/libmaxminddb.cron.conf

### Steps to reproduce

1. install openmediavault 6 from a debian 11 command line only interface along with required packages including sudo. Do so all while using root's user permissions by doing everything after command "su -" and then leaving it root
2. you'll have to add /sbin and /usr/sbin to $PATH but run all commands with sudo or after "su -" so you don't fix this now.
3. now edit ~/.bash_profile and edit path to include sbin pathways.
4. install docker and portainer from server IP. Partition a filesystem for use by omv.
5. implement nextcloud stack and begin running nextcloud on the device using free duckdns.org domain name. There's a youtube video going over it, it'll be the only one that covers this in detail. [[youtube.com](https://www.youtube.com/watch?v=KIhA4RcP4Ug&list=LL&index=2&t=966s)]
6. wait a few hours and the error will display in swag logs in portainer. The nextcloud stack will then fail.

### Expected behavior

I think we should implement the change in permissions for logrotate.status during the setup script for nextcloud. the command to fix this would be "# chmod 600 /config/log/logrotate.status"

just so we don't have to do it in ssh. Thank you.

### Installation method

Community Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
outputs were errors:
could not open input file: occ
or 
-bash: ./occ: No such file or directory
```

### List of activated Apps

```shell
outputs were errors:
could not open input file: occ
or 
-bash: ./occ: No such file or directory
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
[21-Nov-2022 12:20:07] ERROR: unable to bind listening socket for address '127.0.0.1:9000': Address in use (98)
[21-Nov-2022 12:20:07] ERROR: FPM initialization failed
[21-Nov-2022 12:20:08] ERROR: unable to bind listening socket for address '127.0.0.1:9000': Address in use (98)
[21-Nov-2022 12:20:08] ERROR: FPM initialization failed
[21-Nov-2022 12:20:09] ERROR: unable to bind listening socket for address '127.0.0.1:9000': Address in use (98)
[21-Nov-2022 12:20:09] ERROR: FPM initialization failed
[21-Nov-2022 12:20:10] ERROR: unable to bind listening socket for address '127.0.0.1:9000': Address in use (98)
[21-Nov-2022 12:20:10] ERROR: FPM initialization failed
[21-Nov-2022 12:20:11] ERROR: unable to bind listening socket for address '127.0.0.1:9000': Address in use (98)
[21-Nov-2022 12:20:11] ERROR: FPM initialization failed

just keeps repeating this. restarting the stack will temporarily fix this.
```

### Additional info

debian 11 Bullseye

BASIC CLI INTERFACE ONLY - BARE MINIMUM DEBIAN 11

additional packages installed: openmediavault-keyring openmediavault firmware-linux firmware-linux-free firmware-linux-nonfree network-manager gnupg firmware-iwlwifi

additional wgets installed: OpenMediaVault 6 install's wget

Sources.list file and directory commands ran:

```shell
sudo sed -i 's/main/main contrib non-free/g' /etc/apt/sources.list
```
and then

```shell
cat <<EOF >> /etc/apt/sources.list.d/openmediavault.list
deb https://packages.openmediavault.org/public shaitan main
# deb https://downloads.sourceforge.net/project/openmediavault/packages shaitan main
## Uncomment the following line to add software from the proposed repository.
# deb https://packages.openmediavault.org/public shaitan-proposed main
# deb https://downloads.sourceforge.net/project/openmediavault/packages shaitan-proposed main
## This software is not part of OpenMediaVault, but is offered by third-party
## developers as a service to OpenMediaVault users.
# deb https://packages.openmediavault.org/public shaitan partner
# deb https://downloads.sourceforge.net/project/openmediavault/packages shaitan partner
EOF
```

### DEVICE INFO
Celeron Processor
4GB RAM
an earlier mobo that does DDR4
SSD, 120GB
Two HDD Drives, each 2TB running RAID 1
Processor driven Graphics
No sound card or sound processing capability on mobo

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
