### ISSUE TITLE
Update Notification Bugs and Interface Improvements 

### ISSUE THREAD

**Issue by 001101** [nextcloud/server#3532]
**first** issue is that the update notification did not disappear and even worse, it duplicates, this div is it:
<div id="notification-container">
		<div id="notification" style="display: inline-block;"><div class="row">Es sind 2 App-Aktualisierungen für Sie verfügbar</div><div class="row">Es sind 2 App-Aktualisierungen für Sie verfügbar</div></div>
	</div>

**second** is that it appears on modules **which are not activated**, that makes no sense for me, update check is only necessary for activated modules.

**third** the updates need to be bundled in a seperate menu entry

**fourth** the menu entry need rotary colors for better interface experience

**five** the 'wall tile' / 'big icon' overview is not informative or admin friendly, it should be also the option for detailed simple list view, with radio button or some simple on/off switches for
1. activation
2. update
3. delete
4. custom ACL

### Steps to reproduce
1. login
2. click + button
3. click categorie

### Expected behaviour
Should disappear and  update check is only necessary for activated modules.

### Actual behaviour
Not disappear and checking for inactive modules

### Server configuration
**Operating system**:
debian 8
**Web server:**
nginx
**Database:**
MySQL 5.5
**PHP version:**
5.6
**Nextcloud version:** (see Nextcloud admin page)
10 stable

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Where did you install Nextcloud from:**
repo

**Comment by nickvergessen** [comment]
The issues are all covered by #2138 #3193 #1236 #838
