### ISSUE TITLE
Changing upload size in admin panel to 2 Gb on 32bit php7

### ISSUE THREAD

**Issue by JSoko** [nextcloud/server#3533]
### Steps to reproduce
1. Go into admin panel, try to change Max Upload Size to "2 GB", "2G" or  "2048M" => Red Error
2. Enter "2047 M" into the field an press save => green Saved, showing 2 GB in the Field

### Expected behaviour
Should be able to save "2 GB" and not only  <= 2047 M

### Actual behaviour
see above
### Server configuration
**Operating system**: Linux OdNc 3.10.103 #1 SMP PREEMPT Sat Sep 10 14:43:59 UTC 2016 armv7l

**Web server:** Apache/2.4.25 (Ubuntu) (apache2handler)

**Database:** mysql 10.0.29

**PHP version:** 7.0.13-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 11.0.2 RC2 (beta) - 11.0.2.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 11.0.2.RC1
**Where did you install Nextcloud from:** 
Updater
**Signing status:**
<details>
	<summary>Signing status</summary>

```
"Integrity checker has been disabled. Integrity cannot be verified."
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.4.1
 - admin_audit: 1.1.0
 - announcementcenter: 3.0.0
 - bookmarks: 0.9.1
 - calendar: 1.5.0
 - comments: 1.1.0
 - contacts: 1.5.3
 - dav: 1.1.1
 - deck: 0.1.1
 - direct_menu: 0.10.0
 - federatedfilesharing: 1.1.1
 - files: 1.6.1
 - files_automatedtagging: 1.1.1
 - files_downloadactivity: 1.0.0
 - files_pdfviewer: 1.0.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - flowupload: 0.4
 - issuetemplate: 0.2.1
 - keeweb: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - news: 10.1.0
 - nextcloud_announcements: 1.0
 - notes: 2.2.0
 - notifications: 1.0.1
 - ocsms: 1.11.5
 - ownbackup: 16.11.0
 - password_policy: 1.1.0
 - provisioning_api: 1.1.0
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - shorten: 0.0.15
 - spreedme: 0.3.7
 - survey_client: 0.1.5
 - systemtags: 1.1.3
 - tasks: 0.9.4
 - templateeditor: 0.2
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - updatenotification: 1.1.1
 - workflowengine: 1.1.1

Disabled:
 - audioplayer
 - encryption
 - external
 - federation
 - files_accesscontrol
 - files_external
 - files_retention
 - firstrunwizard
 - flowupload.old
 - gallery
 - html5_videoplayer
 - qownnotesapi
 - spreed
 - user_external
 - user_ldap
 - user_saml
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "loglevel": 2,
    "maintenance": false,
    "integrity.check.disabled": false,
    "default_language": "de_DE",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "\/var\/www\/cloud\/data",
    "tempdirectory": "\/media\/ssd\/phptemp\/",
    "dbtype": "mysql",
    "version": "11.0.2.2",
    "theme": "",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "dbname": "nextcloud",
    "dbhost": "127.0.0.1",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "logtimezone": "Europe\/Berlin",
    "log_rotate_size": 500000,
    "cron_log": true,
    "maxZipInputSize": 2147483648,
    "overwritewebroot": "\/",
    "overwrite.cli.url": "\/",
    "htaccess.RewriteBase": "\/",
    "allowZipDownload": true,
    "versions": "true",
    "versions_retention_obligation": "1,3",
    "instanceid": "5072f7e9eec7e",
    "knowledgebaseenabled": true,
    "check_for_working_webdav": true,
    "check_for_working_htaccess": true,
    "check_for_working_wellknown_setup": true,
    "has_internet_connection": true,
    "forcessl": true,
    "activity_expire_days": 8,
    "appcodechecker": true,
    "skeletondirectory": "",
    "trashbin_retention_obligation": "auto,15",
    "appstore.experimental.enabled": true,
    "trusted_domains": [
        "***.net",
        "***.net",
        "192.168.1.234"
    ],
    "mail_smtpmode": "smtp",
    "mail_smtphost": "smtp.***.de",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "no-reply",
    "mail_domain": "***.de",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "updater.release.channel": "beta",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** files_external is disabled
No
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

**Operating system:**
Win 10

**Comment by derkostka** [comment]
same for me !

**Comment by individual-it** [comment]
> Enter "1047 M" into the field an press save => green Saved, showing 2 GB in the Field
I guess you mean   "**2**047 M" 

I don't think you can have more than 2147483647 Bytes as Max Upload Size because that is the maximum what an integer value can take on a 32bit PHP system see PHP_INT_MAX constant

See this Stackoverflow discussion
https://stackoverflow.com/questions/7990703/maximum-upload-file-size-in-php-5-3#7990822

**Comment by nickvergessen** [comment]
Yeah, sadly enough 2GB can not be stored as an integer on 32 bits, because the maximum is 1.999999999GB.
Nothing we can do about that.

**Comment by JSoko** [comment]
I see to options:
1. change the Text Max 2 GB in the Adminpanel to max 1047 M on 32 bit php-Machines
2. If 2 GB is entered, let the adminpanel save 2047M
