### ISSUE TITLE
CalDav: Sync notifications

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#3534]
Scenario: I add an event with a reminder, e.g. 15 min before. On the desired time my 2 mobiles and my laptop and my desktop pc are showing the reminder. If I dismiss it on any of the "clients" I want to have this synced to the others device.
Currently I have to dismiss the reminder on any device.

**Comment by nickvergessen** [comment]
I'm not really sure dav has support for that?

**Comment by tobiasKaminsky** [comment]
Neither I am, but it is something I really need. 
My current workaround is to delete the event on one device and thus it will vanish on the other ones and therefore not remind me any longer ;-)

**Comment by aluxnimm** [comment]
A possible way would be to support
X-MOZ-LASTACK and X-MOZ-SNOOZE-TIME which are used by Thunderbird/Lightning
or this draft
https://tools.ietf.org/html/draft-daboo-valarm-extensions-04

**Comment by SaimenSays** [comment]
Are there any news on this one year issue?
I have reminders for birthdays from my Contacts-calendar. It is impossible to dismiss the reminders in Thunderbird. @tobiasKaminsky workarround is not usable as birthday are everyday repeated events...

**Comment by skjnldsv** [comment]
IS this something to have on dav?

**Comment by tobiasKaminsky** [comment]
As far as I understand this would need some extension to caldav protocol/schema.

**Comment by tobiasKaminsky** [comment]
@georgehrke I am sure you are the best to answer here :-)

**Comment by georgehrke** [comment]
as @aluxnimm already pointed out, there is a draft for it (updated version):
https://tools.ietf.org/html/draft-daboo-valarm-extensions-05

It defines a new property for the `VALARM` component in RFC5545, but this is something that needs to be implemented by the clients. There is not much that we can do from a server's perspective sadly.

**Comment by tobiasKaminsky** [comment]
Sad, but thanks for the confirmation.
