### ISSUE TITLE
Delta sync (copy of #417)

### ISSUE THREAD

**Issue by EnderArchery** [nextcloud/server#35341]
I humbly request to unlock issue #417.
As the issue is still open, it seems, that the feature hasn't been implemented yet. (Observing the behavior of the sync client seems to match this statement)

While issue may not be of high priority, it might have fallen back to the least important issues and feature requests, simply because it is locked.

While it is true, that most archival and encrypted formats don't benefit from this feature, I think that it still is somewhat important.

While I will of course explain why I think it might be important, the main purpose of this issue is just to show, that interest in such a feature hasn't vanished, perhaps get a status update on issue #417 and just maybe have the issue unlocked.

The company I work for has opted to not use NextCloud, as their CAD models are quite large and the synchronisation takes ages, not only blocking other files from being synced, but also making it hard for use as a tool for collaboration, as it takes roughly same amount of time again, for the other clients to then download the whole file.

As for private use... yes, there are quite fewer uses for it, though there are some. Syncing Minecraft worlds as a backup or even a server that can be passed around as needed.
Or perhaps for syncing large OneNote notebooks (unclear if they'd benefit from this behavior, but as OneNote is designed for performing delta synchronisation, the changes seem relatively high)

Was there any progress made since the last update of issue #417?
Is it suitable to be re-unlocked?

I apologize for my... not quite fluid English and the probably as wrong as possible way to get attention to the issue. I can totally understand if it were to get closed again immediately.

**Comment by sunjam** [comment]
Hi, fwiw you can use samba or nfs for migrating those files around.  Or, syncthing as www-data. I have not found nc can outperform syncthing or rsync when dealing with large files.  My .02

**Comment by EnderArchery** [comment]
For both CAD files and Minecraft worlds, the latency and bandwidth of SMB and NFS shares are a big bottleneck. You end up copying them from and to the share over and over again.
Being able to access them from fast local storage while also being able share the files with co-workers and friends (and having centralized backups and versioning) is the whole reason we looked into using NextCloud for those usecases.
It's also way more convenient when working from home. (VPN adds an additional bottleneck to local shares)

And as for both the Minecraft worlds and OneNote files: They were meant to be accessible by users not in the same network. Setting up some type of rsync, nfs or smb system for your friends and all your classmates is not an option.

**Comment by EnderArchery** [comment]
Oh, I think I misunderstood your comment. I'm sorry about that.
If it's about other solutions outperforming NextCloud, then... yes, that's why delta sync would be such a big deal for some of those file types

**Comment by sunjam** [comment]
Agree to disagree. I am very happy with rsync or syncthing for this,
mounted as local storage.

**Comment by kesselb** [comment]
I doubt that something has changed. Please read https://github.com/nextcloud/server/issues/417#issuecomment-589008076. 

> I humbly request to unlock issue https://github.com/nextcloud/server/issues/417.

Done.
