### ISSUE TITLE
Public address book only with email?

### ISSUE THREAD

**Issue by maprambo** [nextcloud/server#3535]
### Steps to reproduce
1. Enable the public address book in the admin settings
2. Make only i.e. the name and twitter username public

### Expected behaviour
The user should appear in the public address book, so that others can find him using his full name or twitter username

### Actual behaviour
The user doesn't appear in the public address book. Only when the email is set to 'public', a confirmation email is sent, after which the user is findable.

### Server configuration
**Operating system**: Ubuntu 16.04.2 LTS

**Web server:** Apache 2.4.18

**Database:** MySQL

**PHP version:** 7.0.13

**Nextcloud version:** 11.0.1 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated, using ownCloud since years

**Where did you install Nextcloud from:** Manual update, downloaded from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_markdown: 1.0.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - richdocuments: 1.1.25
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.1.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - user_external
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocuugavv819x",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***(I hate webcrawlers)***"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "***(I hate webcrawlers)***",
        "dbtype": "mysql",
        "version": "11.0.1.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "php",
        "mail_from_address": "cloud",
        "mail_domain": "***(I hate webcrawlers)***",
        "loglevel": 2,
        "appstore.experimental.enabled": true,
        "theme": "",
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```
</details>

**Are you using external storage, if yes which one:** webdav and dropbox

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Safari 10.0.3

**Operating system:** macOS Sierra 10.12.3

#### Web server error log
<details>
<summary>Web server error log</summary>

```
(nothing in the time I tried the scenario)
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
(nothing in this time)
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
(nothing comes up here)
```
</details>

**Comment by nickvergessen** [comment]
Intended @schiessle ?

**Comment by MorrisJobke** [comment]
@schiessle Ping

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
