### ISSUE TITLE
DB Migration from SQLite to PGSQL fails

### ISSUE THREAD

**Issue by steffenfritz** [nextcloud/server#3536]
### Steps to reproduce

1. Create an empty PostgreSQL database
2. Perform a database conversion: sudo -u www occ db:convert-type --all-apps  pgsql <username> <hostname> <database>

### Expected behaviour

A working database conversion.

### Actual behaviour
Migration process fails with error message "SQLSTATE[22P02]: Invalid text representation: 7 FEHLER:  ungültige Eingabesyntax für Typ bytea" at oc_cards migration 

    0 [>---------------------------]oc_file_locks
    80/80 [============================] 100%oc_comments
    0 [>---------------------------]oc_comments_read_markers
    0 [>---------------------------]oc_credentials
    2/2 [============================] 100%oc_admin_sections
    5/5 [============================] 100%oc_admin_settings
   10/10 [============================] 100%oc_accounts
    3/3 [============================] 100%oc_federated_reshares
    0 [>---------------------------]oc_addressbooks
   3/3 [============================] 100%oc_cards
    65/412 [====>-----------------------]  15%

     [Doctrine\DBAL\Exception\DriverException]
    An exception occurred while executing 'INSERT INTO "oc_cards" ("id", "addressbookid", "carddata", "uri", "lastmodified", "etag", "size") VALUES(?, ?, ?, ?, ?, ?, ?)' with params [ <SNIP/>

### Server configuration
**Operating system**: FreeBSD 11.0

**Web server:** NGINX

**Database:** SQLITE3 to Postgresql 9.3

**PHP version:** 5.6

**Nextcloud version:** 11.0.1 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** MIgrated from Owncloud 9.1

**Where did you install Nextcloud from:** FreeBSD ports

**Signing status:**
<details>
<summary>Signing status</summary>

all files failed
</details>

**List of activated apps:**
<details>
Enabled:
  - calendar: 1.5.0
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_videoplayer: 1.0.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - activity
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - files_trashbin
  - files_versions
  - firstrunwizard
  - spreed
  - survey_client
  - templateeditor
  - user_external
  - user_ldap
  - user_saml

</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "oc8cd111a9dc",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "**REMOVED SENSITIVE VALUE***",
            "**REMOVED SENSITIVE VALUE***",
            "**REMOVED SENSITIVE VALUE***",
            "**REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/usr\/local\/www\/nextcloud\/data",
        "dbtype": "sqlite3",
        "version": "11.0.1.2",
        "installed": true,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "loglevel": 2,
        "htaccess.RewriteBase": "\/"
    }
}

</details>

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by nblock** [comment]
See #173

**Comment by steffenfritz** [comment]
Could you please tell me why?

**Comment by nickvergessen** [comment]
I closed this issue, because it duplicates #173 which covers the same issue and is still open.
There is no need to have 2 issues open for the same problem 😉

**Comment by steffenfritz** [comment]
Ah, ok, thanks you :)
