### ISSUE TITLE
[Bug]: Shared files in Talk chats not able to open

### ISSUE THREAD

**Issue by marvink** [nextcloud/server#35374]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since the update to Nextcloud 25 and also on 25.0.1 we are facing an issue with the Talk app. Especially the files which are uploaded through a chat and tried to be opened by a second person in the chat. 
- I figured out that this is on 1:1 chat's and on chat rooms. 
- I was thought if i open this issue in server or spreed but since i figured out that this is also an issue in the Files App i thought it is probably a global permission issue. I cannot open any files from someone else inside the Files App as well. 
- The error message in the browser console is: "Could not open file /Talk/xyz.jpg Error: Invalid response: 404 Not Found"
- The protocol says: "Sabre\DAV\Exception\NotFound: File with name /Talk/xyz.jpg could not be located"
- I noticed that it seems to be an issue with webdav especially if you have a user inside nextcloud with a space in it: "John Doe" instead of john_doe, but i cannot 100% proof this thought.

### Steps to reproduce

1. Upload an image or file into a talk chat
2. Try to preview or open the file with another user
3. The preview will end up in a black window and not showing the zoomed version or downloading the file.

### Expected behavior

The File should be opened

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - apporder: 0.15.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.1.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - collectives: 2.1.0
  - comments: 1.15.0
  - contacts: 5.0.1
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.2
  - external: 5.0.0
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - groupfolders: 13.1.0
  - impersonate: 1.11.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.0
  - polls: 4.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - richdocuments: 7.0.1
  - richdocumentscode: 22.5.802
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.1
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - terms_of_service: 2.0.0
  - text: 3.6.0
  - theming: 2.0.1
  - theming_customcss: 1.12.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - welcome: 1.0.2
  - workflowengine: 2.7.0
Disabled:
  - drop_account: 2.1.0
  - encryption: 2.13.0
  - federation: 1.15.0
  - mail: 2.1.1
  - suspicious_login: 4.3.0
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Sabre\DAV\Exception\NotFound: File with name /Talk/xyz.jpg could not be located
```

**Comment by 4tler** [comment]
looks like [#34976](https://github.com/nextcloud/server/issues/34976) and will be fixed with next release

**Comment by szaimen** [comment]
> looks like [#34976](https://github.com/nextcloud/server/issues/34976) and will be fixed with next release

Indees
