### ISSUE TITLE
Default .htaccess should include "allow" PUT command

### ISSUE THREAD

**Issue by Xemanth** [nextcloud/server#3537]
### Steps to reproduce
1. Limit Put "Allow from all" is not included in default .htaccess file
2. Uploading files to Nextcloud is not working

### Expected behaviour
Default .htaccess file should include these lines below to enable uploading files. This is important because some server configurations disable by default PUT command and user needs to enable it if needed.

```
<Limit PUT>
      Order deny,allow
      Allow from all
</Limit>
```
### Actual behaviour
Default .htaccess does not enable uploading files

### Server configuration
**Operating system**:

**Web server:**
Apache 2.4

**Database:**
MySQL 5.5.54

**PHP version:**
PHP 5.6

**Nextcloud version:** (see Nextcloud admin page)
11.0.1

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by LukasReschke** [comment]
Unfortunately this is not possible because on the other hand there are also scenarios where `Limit` isn't possible to use in `.htaccess`.

**Comment by Xemanth** [comment]
Is this documented somewhere that Nextcloud requires PUT command to be enabled? Maybe UI should make some kind of misconfiguration popup which tells user PUT's not enabled.
