### ISSUE TITLE
[Bug]: custom Favicon doesn't show on login page NC 25 

### ISSUE THREAD

**Issue by shawnlocal** [nextcloud/server#35397]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi
when you use a custom favicon in theming it only change it for main url and not the login page. On the login page it still shows nextcloud favicon.   

### Steps to reproduce

1. Change the Favicon in theming

### Expected behavior

Favicon changes on everywhere

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Default apps + theming
```

**Comment by andyxheli** [comment]
@shawnlocal had the same issue. i reuploaded the icon and it worked not sure why

**Comment by shawnlocal** [comment]
I did that too but after some times it shows original NC favicon again

**Comment by shawnlocal** [comment]
TBH I think nothing works in NC. Most of the apps are dead. I'm planning to move back to OC again at least on OC I can use the S3 app which it doesn't work correctly on NC.

**Comment by Mike710Shine** [comment]
I have the same issue on NC 26. The custom favicon don't show on the login screen. After i logged in the correct favicon will show.

**Comment by joshtrichards** [comment]
Seems fixed these days. Tested back to 25 even (maintenance releases published after the reports in this Issue). Don't hesitate to reply if you're still seeing this particular issue in >=28.

**Comment by ysalmon** [comment]
I am experiencing this on 26 Winter (that is version 33 iiuc) : the login page has ``<link rel="icon" href="/core/img/favicon.ico">`` (although not always) while the logged-in page correctly have  ``<link rel="icon" href="/index.php/apps/theming/favicon/files?v=112cef07">``.
