### ISSUE TITLE
Federated Cloud sharing on shared Apache -> timeout

### ISSUE THREAD

**Issue by andyboeh** [nextcloud/server#3539]
I have several NextCloud instances on my server, powered by Apache 2.4 and PHP7.0-fpm. They run on different vhosts but share the php-fpm pool.

When I try to share a file or folder using federated sharing between the instances, php fpm becomes unresponsive as soon as a user works with the federated share. I have to restart php-fpm, this affects all websites using this php-fpm pool!

What resolves the issue is to use different php-fpm pools for the NextCloud instances. This was not necessary with NC10, everything worked fine there.

I'm not sure if it's really a NextCloud problem, I'm reporting it here in case somebody else runs into this situation.

 
### Steps to reproduce
1. Set up two NextCloud 11 instances on the same host, PHP 7 FPM and Apache - use different VHosts
2. Share a file or folder using federated cloud sharing between the instances, accept the share
3. Access a shared file

### Expected behaviour
Shared file is opened

### Actual behaviour
Nothing happens until php fpm is restarted very any website using this php fpm instance

### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
Apache 2.4
**Database:**
MariaDB
**PHP version:**
7.0.16
**Nextcloud version:** (see Nextcloud admin page)
11.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated (over the course of years from 5.0)
**Where did you install Nextcloud from:**
Release
**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** user_saml

### Client configuration
**Browser:**
Firefox 51.0
**Operating system:**
Arch Linux
#### Web server error log
no error is logged

#### Nextcloud log (data/nextcloud.log)
no error is logged
#### Browser log
no error is logged

**Comment by nickvergessen** [comment]
I'm not sure there is a lot we can do. I would not remember anything special we did and for sure we didn't break this intentionally.

I will close this, feel free to provide more information or steps we can do to prevent this. Then we can have a look.
