### ISSUE TITLE
Multibucket Object Store as primary storage got runtime error

### ISSUE THREAD

**Issue by tracymacding** [nextcloud/server#3540]
config Multibucket Object Store as primary storage got error as below:

`Error: Class 'Object\Storage\Backend\Class' not found in /home/vagrant/newbox/lib/private/Files/Mount/ObjectHomeMountProvider.php:133 Stack trace: #0 `

follow the guidance
https://docs.nextcloud.com/server/11/admin_manual/configuration_files/primary_storage.html

**Comment by nickvergessen** [comment]
You have to replace `Object\\Storage\\Backend\\Class` with your option of choice.
If you use **Openstack Swift** use `\\OC\\Files\\ObjectStore\\Swift`
If you use **Amazon S3** use `\\OC\\Files\\ObjectStore\\S3`
