### ISSUE TITLE
On Add content popover menu, Items should be 100% width clickable

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#35401]
Because one image is more obvious, here, the red zone is not clickable (apply to all menu items).
Nextcloud 25.

![image](https://user-images.githubusercontent.com/12234510/206560971-3cc25049-3056-46ca-8a03-cee40aeaf7c7.png)

**Comment by szaimen** [comment]
PR: https://github.com/nextcloud/server/pull/34886

**Comment by solracsf** [comment]
@szaimen on 25.0.2

### Fixed
![image](https://user-images.githubusercontent.com/12234510/206560483-370ccdd2-eae7-4819-9b5b-ac530e375ac9.png)

### Right click on a folder, fixed
![image](https://user-images.githubusercontent.com/12234510/206560635-564e2ec5-cfcd-4f2b-8839-83e81a3f774b.png)

### Click on the 3 dots on a folder, NOT fixed
![image](https://user-images.githubusercontent.com/12234510/206560770-f38fff3a-15ad-4b42-806c-80c3adde043b.png)

**Comment by szaimen** [comment]
Will be fixed with 25.0.3
