### ISSUE TITLE
[Bug]: Nothing works after upgrading to 24.0.7, and then to 25.0.1

### ISSUE THREAD

**Issue by manu5801** [nextcloud/server#35413]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading to 24.0.7 most (but not ALL !) logged-in users  get a white page, if not already logged they cannot login.
After upgrading again to 25.0.1, same behaviour.

In the log files we have the same message for both versions, ie:

### Steps to reproduce

1. Upgrade from 24.0.6 to 25.0.1
2. try to login and ask several users to login also
3. Some users can login, other users cannot. I could not determine why the bug does not appear for everybody
4. Some already connected users have a white page and cannot do anything
5. We got the same behaviour in the upgrade from 24.0.6 to 24.0.7

### Expected behavior

Login OK, File application or other applications available after logged in

### Installation method

Community Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
/var/www/html $ php occ config:list system
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.le-pic.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "25.0.1.1",
        "overwrite.cli.url": "https:\/\/cloud.le-pic.org",
        "overwriteprotocol": "https",
        "default_language": "fr",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "skeletondirectory": "\/var\/www\/html\/core\/skeleton_pic",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "maintenance": false,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "theme": "",
        "loglevel": 0,
        "default_phone_region": "ISO 3166-2:FR",
        "mail_smtpsecure": "tls"
    }
}
```

### List of activated Apps

```shell
/var/www/html $ php occ app:list
Enabled:
  - activity: 2.17.0
  - announcementcenter: 6.4.0
  - calendar: 4.1.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.2
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_mindmap: 0.0.27
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - onlyoffice: 7.6.8
  - ownpad: 0.7.1
  - password_policy: 1.15.0
  - photos: 2.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - suspicious_login
  - twofactor_totp
  - user_ldap
/var/www/html $
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"log":"172.18.0.2 - - [23/Nov/2022:22:12:20 +0000] \"GET /apps/theming/image/logo?v=11 HTTP/1.1\" 404 8242 \"-\" \"Mozilla/5.0 (X11; Linux x86_64; rv:107.0) Gecko/20100101 Firefox/107.0\" \"172.18.0.1\"\n","stream":"stdout","time":"2022-11-23T22:12:20.309316458Z"}
{"log":"2022/11/23 22:12:21 [error] 31#31: *150 FastCGI sent in stderr: \"PHP message: PHP Fatal error:  Nesting level too deep - recursive dependency? in /var/www/html/lib/private/Log/ExceptionSerializer.php on line 215\" while reading response header from upstream, client: 172.18.0.2, server: , request: \"PROPFIND /remote.php/dav/files/helene/ HTTP/1.1\", upstream: \"fastcgi://172.24.0.4:9000\", host: \"cloud.le-pic.org\"\n","stream":"stderr","time":"2022-11-23T22:12:21.190263041Z"}
{"log":"172.18.0.2 - helene [23/Nov/2022:22:12:21 +0000] \"PROPFIND /remote.php/dav/files/helene/ HTTP/1.1\" 500 5 \"-\" \"Mozilla/5.0 (Linux) mirall/2.5.1git (Nextcloud)\" \"172.18.0.1\"\n","stream":"stdout","time":"2022-11-23T22:12:21.190669752Z"}
{"log":"2022/11/23 22:12:21 [error] 31#31: *150 FastCGI sent in stderr: \"PHP message: PHP Fatal error:  Nesting level too deep - recursive dependency? in /var/www/html/lib/private/Log/ExceptionSerializer.php on line 215\" while reading response header from upstream, client: 172.18.0.2, server: , request: \"GET /apps/recommendations/api/recommendations/always HTTP/1.1\", upstream: \"fastcgi://172.24.0.4:9000\", host: \"cloud.le-pic.org\"\n","stream":"stderr","time":"2022-
```

### Additional info

We could provide a workaround commenting out lines 205-207 in the file /var/www/html/lib/private/Log/ExceptionSerializer.php, so that the removeValuesFromArg function producing the error is no more called and everything works now

Please note the bug is present in versions 24.0.7 AND 25.0.1, we did not notice it in previous versions.

We use the community container nextcloud:25-fpm-alpine

**Comment by szaimen** [comment]
Please try again with 25.0.2

**Comment by solracsf** [comment]
https://github.com/nextcloud/server/issues/32432 ?

**Comment by MichaelGeil** [comment]
same here, but after using occ upgrade it works fine

**Comment by manu5801** [comment]
We tried php occ upgrade but it said "already upgraded", the upgrade was done when starting the new docker container. So for us this did not fix anything
Yes it looks like #32432 and same workaround, but there is no need creating a user to get the problem.

**Comment by magix2** [comment]
I encounter similar problems. I also upgraded several times and in the end to NC25. During the process, I got the warning that group folders are disabled, because of an incompatibility issue [#2192](https://github.com/nextcloud/groupfolders/issues/2192). Now I only get a blank screen when opening NC in a browser, unless I activate the maintenance mode. In that case, I can see the the maintenance mode screen.

I use apache2 and also php8.0. Any ideas? Should I try to use occ upgrade or how do I get to the bottom of the problem?

**Comment by manu5801** [comment]
@magix2 did you try the workaround I proposed in the issue ? Another workaround (not tested by me) may be to disable if possible the circles app

**Comment by magix2** [comment]
@manu5801 Thanks for your response. I tried disabling circles, but that did not work. However, running ```occ upgrade``` solved the problem. Maybe the upgrade did not go through, because the version was still 24.0.7.1 and now everything works with 25.0.1.1.

**Comment by zaggynl** [comment]
Also getting a 500/blank page after upgrade to 25.0.2
Status page shows:

installed | true
-- | --
maintenance | false
needsDbUpgrade | false
version | "25.0.1.1"
versionstring | "25.0.1"
edition | ""
productname | "Nextcloud"
extendedSupport | false


sudo -u www-data php occ app:list shows circles is disabled

sudo -u www-data php occ upgrade shows:

Nextcloud is already latest version



Not sure how to diagnose?

**Comment by manu5801** [comment]
@zaggynl - looks like you are still using 25.0.1.1, aren't you ?

**Comment by zaggynl** [comment]
> @zaggynl - looks like you are still using 25.0.1.1, aren't you ?

That's the oddity, the upgrade appeared to have gone ok after initial 'sudo -u www-data php occ upgrade'.
But only server error 500/blank screen on page load after the last steps of 'https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html, server status still reports the old version, occ upgrade won't upgrade anymore as says is on latest version.

I couldn't figure it out in the end so I restored the VM snapshot I made before hand.
Will wait for another point release?

For giggles I had another try:
```
# sudo -u www-data php occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Disabled incompatible app: bookmarks
Disabled incompatible app: calendar
Disabled incompatible app: checksum
Disabled incompatible app: contacts
Disabled incompatible app: keeweb
Disabled incompatible app: maps
Disabled incompatible app: metadata
Disabled incompatible app: music
Disabled incompatible app: news
Disabled incompatible app: notes
Disabled incompatible app: onlyoffice
Disabled incompatible app: phonetrack
Disabled incompatible app: ransomware_protection
Disabled incompatible app: spreed
Disabled incompatible app: twofactor_nextcloud_notification
Updating <photos> ...
Updated <photos> to 2.0.1
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Resetting log level
```

an attempt to visit the nextcloud page in an incognito tab shows a http 500 error
status page shows:



installed | true
-- | --
maintenance | false
needsDbUpgrade | false
version | "25.0.1.1"
versionstring | "25.0.1"
edition | ""
productname | "Nextcloud"
extendedSupport | false

**Comment by manu5801** [comment]
> Please try again with 25.0.2



> Please try again with 25.0.2

Hello
We moved to 25.0.2.3 yesterday: same behaviour, the same workaround worked for us...

**Comment by solracsf** [comment]
Feel free to try https://github.com/nextcloud/server/pull/35970

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by manu5801** [comment]
Hi

We updated this evening to 25.0.3..
It appears unfortunately that the issue is NOT fixed. The SAME workaround as described above was still needed.

Cheers
Emmanuel

**Comment by zaggynl** [comment]
After upgrading to 25.04 I did not run into this issue 🎉

**Comment by manu5801** [comment]
Great: we upgraded to 25.04 three days ago and the bug appears to be fixed !
Thanks !
I close the ticket
