### ISSUE TITLE
max upload filesize not working

### ISSUE THREAD

**Issue by TheReal1604** [nextcloud/server#3541]
### Steps to reproduce
1. fresh install of nextcloud 11.0.1
2. configure max file upload size in /etc/php/7.0/apache2/php.ini to 2G
3. edit the max upload file size via administration menu to 2G
4. Upload file to nextcloud bigger 2G

### Expected behaviour
There should be an error message that the file you try to upload is bigger than the file size limit

### Actual behaviour
No error, no warning, upload succeeds with files bigger than the max file size configured.

### Server configuration
**Operating system**: Ubuntu Server 16.04 LTS

**Web server:** apache 2

**Database:** Mysql 5.7.17

**PHP version:** 7

**Nextcloud version:** 11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh installation

**Where did you install Nextcloud from:** .tar.bz2

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Are you using encryption:** no

### Client configuration
**Browser:** Google Chrome 56.0.2924.87

**Operating system:** Windows 8.1 Pro

**Comment by nickvergessen** [comment]
This is intended behaviour. The max. Filesize setting is to prevent errors when uploading bigger files. Files are chunked while uploading to circumvent this setting.

**Comment by TheReal1604** [comment]
@nickvergessen Is the file chunking also active if I upload something via the webinterface?

Thanks for this info!

**Comment by nickvergessen** [comment]
Yes, because some enviroments only allow 2MB uploads and we want everyone to be able to have bigger files.

**Comment by TheReal1604** [comment]
@nickvergessen awesome thanks for your answer!
