### ISSUE TITLE
[Bug]: Don't cache quota when queried in web UI

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#35421]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Quota in web UI only updates after a delay.

From my understanding the purpose of the quota cache is only to save performance with repeated PROPFINDs, not when queried for display.

- idea 1: only use the cached quota value for PROPFINDs
- idea 2: invalidate the quota cache as soon as size propagation happens (ex: through upload operations)

### Steps to reproduce

1. Setup a user with a quota of 5 GB
2. Login as that user
3. Upload a bunch of files
4. Refresh the page
5. Look at the used space at the bottom left

### Expected behavior

Used space must adjust itself immediately.

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
N/A
```

### Additional info

Observed on master and stable25, pre 25.0.2 RC1

**Comment by eltos** [comment]
The quota cache must also be invalidated immediately if the default or per-user limit is changed via the users page in the admin web interface (nextcloud.example.com/settings/users).
Currently, it just makes you think that the change in quota limit was not applied, especially since reloading the page will show the old value again (and there is no hint explaining that it just takes a few minutes).

**Comment by skjnldsv** [comment]
We update it now based on upload or other events (28+)
