### ISSUE TITLE
[Bug]: Talk icon in share menu missing/broken

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#35427]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The share menu used to show icons on the right side indicating what each item is: an email, a user, a chat and so on. In Nextcloud 25.0.1 only the email icon shows, I don't know why, but it makes it much harder to share.

<img width="519" alt="Screenshot_20221125_120220" src="https://user-images.githubusercontent.com/551757/203971389-6cfc9429-9389-4b0b-a482-755df000c919.png">

### Steps to reproduce

1. type a name of a user to share with in the dialog
2. see no icons
3.

### Expected behavior

see icons

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
list from our server (cloud.nextcloud.com)
```

### Additional info

This is on cloud.nextcloud.com

**Comment by szaimen** [comment]
should be fixed in 25.0.2
