### ISSUE TITLE
[Bug]: Setup Installation in 25 version database password parsing broken!!!

### ISSUE THREAD

**Issue by zh54tg234f** [nextcloud/server#35435]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

very polite, idk why or how but your new setup since version 25 is parsing the password for the database wrong.

i just retried the install with 24.7 (see the difference in the older fashion design) and wonder it all works.

i dont know may be a nginx parsing bug what ever, i use special chars in my pw, never was a problem before.

im using php7.4 fpm (in case it matters)

### Steps to reproduce

1. use special chars bunch of them (no " nor ') for mariadb database user pw [maybe the $ % / what ever it is which is suddenly a problem]
2. compare version 24.7 to 25.x
3. see there is some kind failure happening...

### Expected behavior

the right password shall work as in the versions before

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
none
```

**Comment by joshtrichards** [comment]
Is there error message you're seeing? What is the specific indication of a problem?

**Comment by joshtrichards** [comment]
Closing due to lack of response.

For what it's worth, haven't seen other reports of this. And I'm unable to reproduce. Tested with >=v25 via both the Web UI installer and command line.
