### ISSUE TITLE
Confusing external receiver e-mail / password share procedure on NC11

### ISSUE THREAD

**Issue by supremesyntax** [nextcloud/server#3543]
I have updated our Nextcloud instance from 10.0.3 to 11.0.1.

On NC10 our users have shared files/folders the following way:

1. Choose file and select share icon
2. Set tick to share
3. Enter password
4. Enter e-mail address
5. Receiver gets automated e-mail with link from Nextcloud (and second manual e-mail with password from share-owner)
-> Link is password protected

Now on NC11 the e-mail address field is completely missing and got consolidated with user/group field.

My users now 
1. enter the e-mail address in the user/group/e-mail field
2. Tick box to share
3. Enter password and hit enter

**What is expected?**
Now they expect the receiver to get an e-mail to the password protected file!!!

**What happens?**
Receiver gets e-mail with link without password protection.
( Password protected link differs and has to be sent manually )

**I have set "Enforce password protection" in Admin/Sharing so sharing items without password should not be possible!!! Very confusing.**

**Comment by Oz246** [comment]
19/5000
Identical problem

**Comment by supremesyntax** [comment]
**I consider this a security flaw.**
When "Enforce password protection" is set in Admin/Sharing it should not be possible to send a link without password.

So the solution should be a warning that first the item has to be shared and a password has to be set before accepting an e-mail address as recipient. (Only when "Enforce password protection" is set)

When "Enforce password protection" is **not set** everything should work like it already does. There I see the necessity of sharing items with password as well as without password.

**Comment by ccghad** [comment]
same as #2357

**Comment by supremesyntax** [comment]
ok didn't see that. i think this issue could be closed as duplicate?

**Comment by schiessle** [comment]
Just as a explanation. "Share by mail" has nothing to do with the link you can create in the share dialog. Therefore also the password didn't apply. Even if it is similar from a technical point of view, we create a personalized link and sending it to exactly one person, it is quite different from a user point of view.

As already mentioned, discussions on how we could protect mail shares by password can be followed here: https://github.com/nextcloud/server/issues/2357

**Comment by mconsoir** [comment]
Nextcloud version : 12.0.2 PLEASE restore 
"Allow users to send mail notification for shared files"

**Comment by linuxmangr** [comment]
I have the Nextcloud 14.0.3 but not found this check box
