### ISSUE TITLE
[Bug]: Unable to adjust some options of sharing using webui in specific screen resolution

### ISSUE THREAD

**Issue by haoxingxing** [nextcloud/server#35444]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![image](https://user-images.githubusercontent.com/22582237/204086390-34007f49-d71a-4034-84f2-cefaec51c09b.png)
just as the picture,I can't adjust the option "expiration date" because it displayed out of the screen

screen res=2560 × 1600
Nextcloud 25.0.1

### Steps to reproduce

1.  create a sharing link for a folder
2. click "more"

### Expected behavior

the positon of drop box should be adjust to somewhere able for users to click all the options

### Installation method

Community Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - bruteforcesettings: 2.5.0
  - camerarawpreviews: 0.8.0
  - cloud_federation_api: 1.8.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_downloadactivity: 1.15.0
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - photos: 2.0.0
  - provisioning_api: 1.15.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - audioplayer: 3.3.1
  - calendar: 4.1.0
  - checksum: 1.1.5
  - circles: 22.1.1
  - comments: 1.12.0
  - contacts: 5.0.1
  - contactsinteraction: 1.2.0
  - dashboard: 7.4.0
  - deck: 1.8.2
  - drawio: 1.0.5
  - encryption: 2.9.0
  - epubreader: 1.4.7
  - external: 5.0.0
  - extract: 1.3.5
  - federation: 1.11.0
  - files_accesscontrol: 1.15.0
  - files_automatedtagging: 1.15.0
  - files_markdown: 2.3.6
  - files_mindmap: 0.0.27
  - files_retention: 1.14.0
  - files_versions: 1.14.0
  - firstrunwizard: 2.10.0
  - flowupload: 1.1.3
  - forms: 3.0.1
  - integration_gitlab: 1.0.10
  - integration_onedrive: 1.1.4
  - metadata: 0.17.0
  - music: 1.7.0
  - nextcloud_announcements: 1.10.0
  - notes: 4.6.0
  - occweb: 0.1.0
  - password_policy: 1.11.0
  - phonetrack: 0.7.2
  - printer: 0.0.5
  - privacy: 1.6.0
  - qownnotesapi: 22.10.0
  - quicknotes: 0.8.5
  - recommendations: 0.5.0
  - richdocuments: 7.0.1
  - sharebymail: 1.11.0
  - socialsharing_email: 2.5.0
  - spreed: 15.0.1
  - support: 1.4.0
  - survey_client: 1.9.0
  - suspicious_login
  - systemtags: 1.11.0
  - user_ldap: 1.7.0
  - user_status: 1.1.1
  - weather_status: 1.2.0
  - workflow_media_converter: 1.7.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by szaimen** [comment]
Should be fixed with 25.0.2
