### ISSUE TITLE
View::getOwner() returns invalid value for external storages

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#3547]
Found while debugging:
https://github.com/nextcloud/activity/issues/41#issuecomment-279765011

1. Mount an external storage
2. Enable activity
3. Share the storage as "files drop"
4. Upload a file
5. Owner should have an activity entry

### Actual
No entry created, because [View::getOwner()](https://github.com/nextcloud/activity/blob/656568b16ac86bf87a2ff4de39b990bca26be813/lib/FilesHooks.php#L520-L520) returns false. I can add handling for that, no problem, but the docs say:
```php
/**
	 * @return string the user id of the owner
	 * @throws NotFoundException
```

So either the docs should be adjusted or the code.

**Comment by nickvergessen** [comment]
cc @icewind1991

**Comment by icewind1991** [comment]
There isn't any code path that can return `null` there, it get's a user object and returns the `uid` of that

**Comment by icewind1991** [comment]
It should fallback to the current user, is any user loggedin?

**Comment by nickvergessen** [comment]
No, when you are visiting a public links not always?

**Comment by nickvergessen** [comment]
This is fixed nowadays I think
