### ISSUE TITLE
Theming refactoring follow-ups

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#35479]
- should the `Change color` option really be part of the background grid? In my opinion it should be rather outisde as it is not a background option...
-  `Remove background` should be shown as selected if it is selected imho and it should have the background color that is currently active, imho.
        ![image](https://user-images.githubusercontent.com/42591237/204043702-d06744ca-9035-456e-b328-66a3d20694a2.png)

**Comment by szaimen** [comment]
@skjnldsv I hope it is fine that I've assinged you? :)

**Comment by HannesJo0139** [comment]
Seems kind of related to my request
https://github.com/nextcloud/server/issues/35491
