### ISSUE TITLE
[Bug]: RC 25.0.2 RC1 Lines are very noticeable 

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#35472]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Upgrade from NC 25.0.1 to NC 25.0.2 RC1

![image](https://user-images.githubusercontent.com/59488153/204383517-421a0fb9-dbb3-488c-8070-2aab9674bdc4.png)
![image](https://user-images.githubusercontent.com/59488153/204384187-c81e548c-c885-4911-a406-35ef9557fde4.png)

**************************************************************************************************************************************

![image](https://user-images.githubusercontent.com/59488153/204383629-8067bb7f-b480-402a-b458-550d8bc618b3.png)
![image](https://user-images.githubusercontent.com/59488153/204384083-63223665-1d2e-4a5f-b02b-eeab6cdc1d50.png)

### Steps to reproduce

Upgrade to NC 25.0.2 RC1

### Expected behavior

Line should not be so visible 

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
NA
```

**Comment by schiessle** [comment]
I agree, I was just about to open a similar ticket. This was probably done to improve accessibility. But I wonder if it would make sense to have this strong lines only in the high contract mode? cc @nextcloud/designers

**Comment by andyxheli** [comment]
I think it makes more sense to have it under high contrast mode.

**Comment by szaimen** [comment]
https://github.com/nextcloud/server/pull/35454
