### ISSUE TITLE
Download Button is missing at the Gallery App's slideshow (opening thru the File App)

### ISSUE THREAD

**Issue by bergart** [nextcloud/server#3548]
### Steps to reproduce
1. go to the main page and open the Picture Directory
2. click on a image to open it with the Gallary's slideshow viewer
3. at the top you'll see that there's no download button

![no_download_icon](https://cloud.githubusercontent.com/assets/22152652/23133844/d6aa19e8-f792-11e6-832b-758034a6ad2b.png)

1. go back to the main page and open click at the little icon at the top right (underneath your username)
2. this opens the Gallery App. Choose one picture and open it by clicking the Gallary's slideshow viewer
3. at the top right corner you'll see a download button

![with_download_icon](https://cloud.githubusercontent.com/assets/22152652/23135061/5e879062-f797-11e6-948f-1c81b859dc90.png)

### Expected behaviour
their should be a download button

### Actual behaviour
their is no download button

### Server configuration
**Linux**:

**Nextcloud version:** 11.0.1

**Comment by nickvergessen** [comment]
Please report in the gallery app:
https://github.com/nextcloud/gallery
