### ISSUE TITLE
Contact changes in activity stream

### ISSUE THREAD

**Issue by Klaas-** [nextcloud/server#3549]
This was briefly discussed in https://github.com/nextcloud/contacts/issues/141

### Steps to reproduce
1. change a contact
2. not showing in activity stream
3.

### Expected behaviour
changes should show up in activity stream

### Actual behaviour
Not showing up in activity stream

### Server configuration
**Nextcloud version:**  11.0.1

**Contacts version:** 1.5.3

**Updated from an older Nextcloud or fresh install:** updated

As a user I would like to see changes to contacts (especially on shared address books) to show up in activity stream or even trigger an e-mail to me. Other apps (calendar for example) already do this.

Thanks!

From the other discussion:
https://github.com/nextcloud/server/issues/1662 (contacts trashbin)
https://github.com/nextcloud/server/blob/9e32885b34dbf6341551ad981365d5d1742a4f65/apps/dav/lib/CalDAV/Activity/Backend.php#L68 (calendar activity "hooks")

**Comment by georgehrke** [comment]
cc @nickvergessen

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by nickvergessen** [comment]
yeah, will look into it now
