### ISSUE TITLE
View a specific file version in the usual editors

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#35509]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When a file has multiple versions in the versions tab and a user wants to restore a specific one, it is currently impossible to know which one is the "correct" one or intended one. Well, one can download the file and view it locally, assuming that the user has a local viewer installed.

**Describe the solution you'd like**
Having the ability to view a version of a file directly in the browser using the Nextcloud viewers like the viewer app (photos, etc), PDF viewer, text editor, office, in read-only mode.

**Describe alternatives you've considered**
It's currently possible already to download a version as a workaround.

**Additional context**
Popped up while reviewing https://github.com/nextcloud/server/pull/35080

**Extension**
A possible extension of this would be to provide a "diff" view, but this would be much more complex as it requires to be able to select two versions to diff and also the viewers/editors need to support diffing in some way. There's a separate issue for that https://github.com/nextcloud/server/issues/30382

**Comment by juliushaertl** [comment]
Relevant viewer issue https://github.com/nextcloud/viewer/issues/1469

**Comment by PVince81** [comment]
depends on the new view API https://github.com/nextcloud/server/issues/30070 (@skjnldsv fyi)

**Comment by AndyScherzinger** [comment]
resolved via the side-by-side comparison feature
