### ISSUE TITLE
[Bug]: The sidebar appears blank when the PDF viewer is open

### ISSUE THREAD

**Issue by amayr69** [nextcloud/server#35515]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nextcloud 25.0.1
If a PDF document is displayed in the viewer and the sidebar is then opened, the sidebar is absolutely empty.
In the list of PDF documents, the sidebar works via the Details item.

### Steps to reproduce

1. Always occurs since update to 25.0.1
2. Open DPF Document  and open sidebar
3.

### Expected behavior

The sidebar should display the document details

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Only Standard Apps
```

**Comment by szaimen** [comment]
this should be fixed with 25.0.2

**Comment by amayr69** [comment]
Thanks
