### ISSUE TITLE
Reload editor/viewer after restoring a version

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#35511]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When editing a file in the text editor, if I restore a version in the versions tab, the editor needs to automatically reload that version. Not sure what should happen with the current editing session though, maybe it needs to get reset.

**Describe the solution you'd like**
Provide a new global event (event bus?) to tell any components on the page that the current file has been modified on the server.
The versions tab would trigger that event.
The text editor, office and any other viewer/editor currently open would listen to that event and reload the file from disk (Webdav).

**Describe alternatives you've considered**
N/A

**Additional context**

@juliushaertl for text/office
@skjnldsv for viewer, pdf viewer

cc @artonge @CarlSchwan as we talked about this during versions UI review

**Comment by juliushaertl** [comment]
Makes sense. For collaborative editing with text/collabora it would actually be nice to have an event even before the restore request is sent so that we can already end the session(s) and potentially unlock the file before proceeding with the restore.

**Comment by juliushaertl** [comment]
Unmerged PR for the old frontend that was abandoned https://github.com/nextcloud/server/pull/26023

**Comment by skjnldsv** [comment]
Yes, emit with a global event and I'm good with it :)
We started doing so here
https://github.com/nextcloud/viewer/blob/6c29825e135a8846e47ffe0c74d8eb4def2051a0/src/components/ImageEditor.vue#L174-L178

**Comment by skjnldsv** [comment]
```js
emit('files:file:created', { fileid: 123456 })
emit('files:file:updated', { fileid: 123456 })
```
