### ISSUE TITLE
[Bug]: Impossible to change/view expiration date of a share link

### ISSUE THREAD

**Issue by koenige** [nextcloud/server#35514]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The expiration date of a shared link is not displayed correctly and cannot be changed on the Nextcloud website.

When I share a file, the default date for the expiration date is written to the database (in my case 7 days, unchanged from default). Clicking on the shared link on the website backend (three dots) shows: [x] Set Expiration date and below the German format "TT.MM.JJ" (even if I change the language of Nextcloud and browser to English). Tested in latest version of Firefox. In Chrome, it shows tt.mm.jjjj, in Safari the current date, even if the expiration date is in the future. Changing the date with the date picker deletes the expiration date (NULL written to database). So it is impossible for us to change the expiration date at a later time. And: It would be nice to be able to turn off the date picker.

I opened a test account at demo1.nextcloud.com: same behaviour, not an installation issue.

### Steps to reproduce

1. Share a file by clicking on the share icon next to the filename
2. Click on "+" next to "Share Link"
3. Click on "…" which appears instead of "+" next to "Share Link"
4. "Set expiration date" will be shown as "TT.MM.JJJJ"
5. Changing the expiration date with the date picker will delete the expiration date.

### Expected behavior

The expiration date should be shown and be changed correctly if changed.

### Installation method

Community Web installer on a VPS or web space

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
./.
```

### List of activated Apps

```shell
./.
```

### Nextcloud Signing status

```shell
./.
```

### Nextcloud Logs

```shell
./.
```

### Additional info

It looks like on demo1.nextcloud.com, you can change the expiration date (it does not get written as NULL), but I still cannot see the date, the date picker in Firefox just showing TT.MM.JJJJ

**Comment by szaimen** [comment]
Should be fixed with 25.0.2
