### ISSUE TITLE
[Bug]: Empty sidebar in NC 25

### ISSUE THREAD

**Issue by wonx** [nextcloud/server#35542]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I open a picture in Nextcloud's web interface, click on the tree dots in the top right corner, and choose to show the sidebar, a completely blank, white sidebar appears. Picture:

![ed71e5b1-52da-4964-b9a8-6eaafd1b2992](https://user-images.githubusercontent.com/2736639/205081992-a42c049d-914c-409f-8aa7-97790cfff291.jpeg)

However, if in the web interface I browse the folder and click on the three dots next to the file and choose "Details", then the sidebar shows the correct information:
![2cd35609-f940-412d-a4a7-5cf68cb1c3ef](https://user-images.githubusercontent.com/2736639/205082208-d03a2752-8b40-4b57-bdf0-aa3ef32ba636.jpeg)

This is a bug that appeared after upgrading from Nextcloud 24 to 25.

### Steps to reproduce

1. Open picture in Nextcloud's web interface.
2. Show sidebar for that picture

### Expected behavior

Sidebar should show information

### Installation method

Community Docker image

### Operating system

Debian/Ubuntu

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_excludedirs: 1.0.0-beta
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - metadata: 0.17.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.0
  - previewgenerator: 5.1.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - bruteforcesettings: 2.4.0
  - calendar: 3.0.5
  - contacts: 4.0.6
  - encryption
  - mail: 1.11.1
  - maps: 0.1.10
  - spreed: 13.0.0
  - suspicious_login
  - twofactor_totp
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by szaimen** [comment]
will be fixed in 25.0.2
