### ISSUE TITLE
Function tearUpScenario has misleading name

### ISSUE THREAD

**Issue by phil-davis** [nextcloud/server#3558]
### Steps to reproduce
1. Look in the source code of some automated tests and see "tearUpScenario"
2. Wonder why the scenario is being torn up.
3. Realize that it is actually being set up.

### Expected behaviour
The name of the function reflects its use/behavior.

### Actual behaviour
The name of the function implies the opposite use/behavior.

### Server configuration
N/A

### Client configuration
N/A
### Logs
N/A

**Comment by nickvergessen** [comment]
Closed via #3566
