### ISSUE TITLE
[Bug]: Contacts in NC 25 have broken avatar images; user avatars work fine.

### ISSUE THREAD

**Issue by summersab** [nextcloud/server#35582]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

This is a copy of a bug filed over on the contacts app:
https://github.com/nextcloud/contacts/issues/3078

My recent comment on the issue is as follows:

> I just spun up a fresh instance of NC with a SQLite DB, and any new contact has a broken image while users have the default avatars with their initials. While tracing the code, I actually think that this issue has to do with the core user libraries. The failure occurs here:
> https://github.com/nextcloud/server/blob/ec5cbdeb7ffb87c0169c39e6f44846e819b41f14/lib/private/Avatar/AvatarManager.php#L114

None of the libraries in the contacts app are even accessed to trigger this bug, so I am pretty certain it has to do with the core.

The contents of the original bug report is below:

> I noticed this issue after upgrading from Nextcloud 24 to Nextcloud 25, but maybe this also happens with Nextcloud 24:
> 
> When opening the contact menu, images for contacts who don't have an image show as "broken image" and not using the initials as placeholder. In the following screenshot the "C" and "D" are users in Nextcloud. All other entries are just address book contacts without image![image](https://user-images.githubusercontent.com/18727110/205470678-39b3c85c-8094-442f-8090-a8394334fb1f.png)
> 
> The reason for this is, that the respective image URLs (e.g. https://myserver.example/avatar/a5db8598-935c-4935-8ac7-02d89f1226e6/64&size=64) result in 404 errors.

### Steps to reproduce

1. Make sure that the Contacts app is installed and active
2. Create some address book entries without image
3. Click on the "contacts" icon on the top right corner to display the contact drop down menu

### Expected behavior

Address book contacts without image show a placholder similar to user entries based on the first and last name.

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [x] #39859
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - cloud_federation_api: 1.8.0
  - contacts: 5.0.1
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - lookup_server_connector: 1.13.0
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - provisioning_api: 1.15.0
  - settings: 1.7.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
```

**Comment by joshtrichards** [comment]
Fixed in #36735
