### ISSUE TITLE
[V24] Hide allow Download

### ISSUE THREAD

**Issue by ASLLR** [nextcloud/server#35617]
Hi everyone, 

I'm testing the V24 of nextcloud server and i can see a difference (maybe a regression) with v23. That concerne the allowing of download. 
We cannot disbable by default in share administrator menu the download : 
![Sans titre](https://user-images.githubusercontent.com/37147055/205887647-7497f187-e8f3-4da3-ac72-4dfc545bb7f2.png)

In a context where the security of the lesser right is king, it's annoying.

Thank in advance,

**Comment by joshtrichards** [comment]
Hi @ASLLR - Unfortunately this was filed as an enhancement, not as a bug report so it may have gotten overlooked. 

The `Allow Download` option did not exist in v23. It was added in v24.

Note: `Allow Download` is not the same as the `Hide Download` option. That *was* previously available (for public shares).
