### ISSUE TITLE
File automated tagging - cannot select or use any tags as the conditions

### ISSUE THREAD

**Issue by RAurelian** [nextcloud/server#35645]
### Steps to reproduce
1. Go to Administration Settings -> Flow
2. Add a new Automated Tagging flow
3. At Condition, select File System tag
4. Observe that you cannot scroll down in the list of tags, nor can you search for any tag. You can only get the first 5 tags in the system
5. Note that at the action, you can select any of the existing tags
6. Select any of the first 5 tags and create a rule -> observe that after saving the tag at he condition has disappeared

### Expected behaviour
When trying to select a tag for the condition, you should be able to select any available tag.

### Actual behaviour
When trying to configure a flow rule with a File system tag, at the condition I can only select from the first 5 tags. Searching for other tags than those 5 will not show any. I tried creating new tags and those do not show up at all. 
If I select any of these 5 tags and create a rule (you can select any tag at he action side), the tag at the condition disappears. So the rule cannot be created.
These are the only tags I can see in the list:
![image](https://user-images.githubusercontent.com/36531484/206175249-16dbebcc-87fd-4c0f-9f47-edfd0dd2e23b.png)
(but again, they do not stick after Save)

### Server configuration

Issue template is not working on my Nextcloud version (25.0.1)

**Operating system**:
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

**Web server:**
Server version: Apache/2.4.54 (Debian)
Server built:   2022-06-09T04:26:43

**Database:**
10.5.15-MariaDB-0+deb11u1 Debian 11

**PHP version:**
PHP 7.4.33 (cli) (built: Nov  8 2022 11:40:37) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
25.0.1

**Where did you install Nextcloud from:**
[Turnkeyl](https://www.turnkeylinux.org/nextcloud) (v17.1)

**Signing status:**

"No errors have been found."

**List of activated apps:**

Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - announcementcenter: 6.4.0
  - bruteforcesettings: 2.5.0
  - checksum: 1.2.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_accesscontrol: 1.15.0
  - files_automatedtagging: 1.15.0
  - files_downloadactivity: 1.15.0
  - files_pdfviewer: 2.6.0
  - files_retention: 1.14.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - fileslibreofficeedit: 1.1.0
  - firstrunwizard: 2.14.0
  - forms: 3.0.1
  - groupfolders: 13.1.0
  - imageconverter: 1.3.4
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mediadc: 0.2.0
  - metadata: 0.17.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - quota_warning: 1.15.0
  - ransomware_protection: 1.14.0
  - recognize: 3.2.3
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - secrets: 1.0.1
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - terms_of_service: 2.0.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_email: 2.7.1
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - user_ldap: 1.15.0
  - user_status: 1.5.0
  - user_usage_report: 1.9.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflow_pdf_converter: 1.10.0
  - workflowengine: 2.7.0
Disabled:
  - encryption
  - files_external

**Nextcloud configuration:**
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.1.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "simpleSignUpLink.shown": false,
        "default_phone_region": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "app_install_overwrite": [
            "issuetemplate"
        ]
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.17.0",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "logging"
        },
        "announcementcenter": {
            "enabled": "yes",
            "installed_version": "6.4.0",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "586"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "2.5.0",
            "types": ""
        },
        "checksum": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "circles": {
            "enabled": "yes",
            "installed_version": "25.0.0",
            "loopback_tmp_scheme": "http",
            "maintenance_run": "0",
            "maintenance_update": "{\"3\":1670412301,\"2\":1670413801,\"1\":1670413801}",
            "migration_22": "1",
            "migration_run": "0",
            "types": "filesystem,dav"
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "logging"
        },
        "contactsinteraction": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "dav"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "emailTestSuccessful": "1",
            "installedat": "1668132430.7601",
            "lastcron": "1670413802",
            "lastupdateResult": "[]",
            "lastupdatedat": "1670412313",
            "moveavatarsdone": "yes",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "shareapi_default_internal_expire_date": "yes",
            "shareapi_enable_link_password_by_default": "no",
            "vendor": "nextcloud"
        },
        "dashboard": {
            "enabled": "yes",
            "installed_version": "7.5.0",
            "types": ""
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "enabled": "yes",
            "generateBirthdayCalendar": "no",
            "installed_version": "1.24.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "authentication"
        },
        "files": {
            "enabled": "yes",
            "installed_version": "1.20.1",
            "types": "filesystem"
        },
        "files_accesscontrol": {
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "filesystem"
        },
        "files_automatedtagging": {
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "filesystem"
        },
        "files_downloadactivity": {
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "2.6.0",
            "types": ""
        },
        "files_retention": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.17.0",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.18.0",
            "types": "filesystem,dav"
        },
        "fileslibreofficeedit": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.14.0",
            "types": "logging"
        },
        "forms": {
            "enabled": "yes",
            "installed_version": "3.0.1",
            "types": ""
        },
        "groupfolders": {
            "enabled": "yes",
            "installed_version": "13.1.0",
            "types": "filesystem,dav"
        },
        "imageconverter": {
            "enabled": "yes",
            "installed_version": "1.3.4",
            "types": ""
        },
        "issuetemplate": {
            "enabled": "no",
            "installed_version": "0.7.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.10.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "authentication"
        },
        "mediadc": {
            "enabled": "yes",
            "installed_version": "0.2.0",
            "types": ""
        },
        "metadata": {
            "enabled": "yes",
            "installed_version": "0.17.0",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.13.1",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "enforceNumericCharacters": "1",
            "installed_version": "1.15.0",
            "types": "authentication"
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "dav,authentication"
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "readableLocation": "ro",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "prevent_group_restriction"
        },
        "quota_warning": {
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "filesystem"
        },
        "ransomware_protection": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": "logging"
        },
        "recognize": {
            "enabled": "yes",
            "faces.batchSize": "500",
            "faces.enabled": "false",
            "imagenet.batchSize": "100",
            "imagenet.enabled": "true",
            "imagenet.lastFile": "1670339717",
            "imagenet.status": "true",
            "installed_version": "3.2.3",
            "landmarks.batchSize": "100",
            "landmarks.enabled": "true",
            "landmarks.lastFile": "1670339732",
            "landmarks.status": "true",
            "movinet.batchSize": "20",
            "movinet.enabled": "true",
            "movinet.lastFile": "1670338989",
            "movinet.status": "true",
            "musicnn.batchSize": "100",
            "musicnn.enabled": "true",
            "node_binary": "\/var\/www\/nextcloud\/apps\/recognize\/bin\/node",
            "tensorflow.cores": "6",
            "tensorflow.gpu": "false",
            "tensorflow.purejs": "false",
            "types": "filesystem,dav"
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "related_resources": {
            "enabled": "yes",
            "installed_version": "1.0.3",
            "types": ""
        },
        "secrets": {
            "enabled": "[\"OneTime\"]",
            "installed_version": "1.0.1",
            "types": ""
        },
        "serverinfo": {
            "cached_count_filecache": "4360",
            "cached_count_storages": "16",
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "filesystem"
        },
        "support": {
            "SwitchUpdaterServerHasRun": "yes",
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "types": ""
        },
        "suspicious_login": {
            "enabled": "yes",
            "installed_version": "4.3.0",
            "types": "authentication"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "logging"
        },
        "terms_of_service": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "filesystem,dav"
        },
        "text": {
            "enabled": "yes",
            "installed_version": "3.6.0",
            "types": "dav"
        },
        "theming": {
            "backgroundMime": "image\/png",
            "cachebuster": "21",
            "color": "#425563",
            "enabled": "yes",
            "faviconMime": "image\/png",
            "installed_version": "2.0.1",
            "logoMime": "image\/png",
            "name": "***REMOVED SENSITIVE VALUE***",
            "slogan": "***REMOVED SENSITIVE VALUE***",
            "types": "logging",
            "url": "***REMOVED SENSITIVE VALUE***"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": ""
        },
        "twofactor_email": {
            "enabled": "yes",
            "installed_version": "2.7.1",
            "types": ""
        },
        "twofactor_totp": {
            "enabled": "yes",
            "installed_version": "7.0.0",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "",
            "update_check_errors": "0"
        },
        "user_ldap": {
            "background_sync_interval": "43200",
            "background_sync_offset": "0",
            "background_sync_prefix": "s01",
            "cleanUpJobOffset": "0",
            "enabled": "yes",
            "installed_version": "1.15.0",
            "s01_lastChange": "1670249961",
            "s01has_memberof_filter_support": "0",
            "s01home_folder_naming_rule": "",
            "s01last_jpegPhoto_lookup": "0",
            "s01ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_attributes_for_group_search": "",
            "s01ldap_attributes_for_user_search": "",
            "s01ldap_backup_host": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_backup_port": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_base": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_base_groups": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_base_users": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_cache_ttl": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_configuration_active": "1",
            "s01ldap_default_ppolicy_dn": "",
            "s01ldap_display_name": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_dn": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_dynamic_group_member_url": "",
            "s01ldap_email_attr": "mail",
            "s01ldap_experienced_admin": "1",
            "s01ldap_expert_username_attr": "",
            "s01ldap_expert_uuid_group_attr": "",
            "s01ldap_expert_uuid_user_attr": "",
            "s01ldap_ext_storage_home_attribute": "",
            "s01ldap_gid_number": "gidNumber",
            "s01ldap_group_display_name": "cn",
            "s01ldap_group_filter": "",
            "s01ldap_group_filter_mode": "0",
            "s01ldap_group_member_assoc_attribute": "",
            "s01ldap_groupfilter_groups": "",
            "s01ldap_groupfilter_objectclass": "",
            "s01ldap_host": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_login_filter": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_login_filter_mode": "0",
            "s01ldap_loginfilter_attributes": "",
            "s01ldap_loginfilter_email": "0",
            "s01ldap_loginfilter_username": "1",
            "s01ldap_matching_rule_in_chain_state": "unknown",
            "s01ldap_nested_groups": "0",
            "s01ldap_override_main_server": "",
            "s01ldap_paging_size": "500",
            "s01ldap_port": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_quota_attr": "",
            "s01ldap_quota_def": "",
            "s01ldap_tls": "0",
            "s01ldap_turn_off_cert_check": "1",
            "s01ldap_turn_on_pwd_change": "0",
            "s01ldap_user_avatar_rule": "default",
            "s01ldap_user_display_name_2": "",
            "s01ldap_user_filter_mode": "0",
            "s01ldap_userfilter_groups": "",
            "s01ldap_userfilter_objectclass": "",
            "s01ldap_userlist_filter": "***REMOVED SENSITIVE VALUE***",
            "s01use_memberof_to_detect_membership": "1",
            "types": "authentication"
        },
        "user_status": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "user_usage_report": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "filesystem"
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": ""
        },
        "weather_status": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "workflow_pdf_converter": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "filesystem"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.7.0",
            "types": "filesystem"
        }
    }
}

**Are you using external storage, if yes which one:** 
NO

**Are you using encryption:** 
NO

**Are you using an external user-backend, if yes which one:** 
Yes, ActiveDirectory

### Client configuration
tried multiple browsers, latest versions of Chrome, FireFox, Vivaldi, Brave

**Operating system:**
Windows 10 pro x64

### Logs
please let me know exactly which log would be useful and if it contains sensitive information

#### Browser log
```
Insert your browser log here, this could for example include:

[1670414671217.log](https://github.com/nextcloud/files_automatedtagging/files/10175821/1670414671217.log)

**Comment by nickvergessen** [comment]
Moving to the server repository as that is where the system tags and the list of checks live.

**Comment by farhills** [comment]
I seem to be having a similar issue, this may be the flow app though?  None of my configured flows seem to be firing because tag selections aren't saving for any of my rules.

1. Create a new flow
2. Use a tag (I'm currently trying to sandbox with OCR)
3. Save the flow
4. Refresh page
5. Tags missing from the flow

Save a new/exisiting flow:
![image](https://user-images.githubusercontent.com/83388006/206783035-728a4f47-a8a8-4f6c-92a7-506550a4beed.png)


Save, then refresh the page.  Tag missing from filter/rule:
![image](https://user-images.githubusercontent.com/83388006/206783154-b8f891b8-e1e5-4012-9811-85cdca3b3cbe.png)
