### ISSUE TITLE
[Bug]: Rendering mess when httpd.conf has AllowOverride All for /var/www/html

### ISSUE THREAD

**Issue by Bockeman** [nextcloud/server#35658]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

By "Rendering mess" I mean the screen is rendered incorrectly with no icons, no coloured sections, and oddly placed text which looks like the source code for the page.

I've been living with this problem since NC 19.0.3, about 2 years ago, following 
```
    Your web server is not properly set up to resolve "/.well-known/caldav". Further information can be found in the documentation.
    Your web server is not properly set up to resolve "/.well-known/carddav". Further information can be found in the documentation.
```
which was solved according to
https://help.nextcloud.com/t/caldav-and-carddav-error-resolving/39435/13
https://help.nextcloud.com/t/warning-your-web-server-is-not-properly-set-up-to-resolve-well-known-caldav/63715/9
by editing `/etc/httpd/conf/httpd.conf`
```
  # Further relax access to the default document root:
  <Directory "/var/www/html">
    # AllowOverride controls what directives may be placed in .htaccess files.
    # It can be "All", "None", or any combination of the keywords:
    #   Options FileInfo AuthConfig Limit
    #
    AllowOverride None
  
  Change to
    AllowOverride All
```

The problem has something to do with the front_controller, because when I edit `/var/www/html/nextcloud/.htaccess`
and comment our the front_controller variable like this:
```
    #SetEnv front_controller_active true
```
then pages are rendered correctly.

That would be fine except for the annoyance of having to edit `/var/www/html/nextcloud/.htaccess` after each NC upgrade.

### Steps to reproduce

1. Configure "AllowOverride All" for /var/www/html
2. Page rendering is corrupted for all pages 
3.

### Expected behavior

All pages render correctly, regardless of configuration overrides. 

### Installation method

Other Community project

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
sudo -u apache php /var/www/html/verivault/console.php config:list system
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.2.2",
        "overwrite.cli.url": "http:\/\/www.veriserve.co.uk",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "filesystem_check_changes": 1,
        "sqlite.journal_mode": "DELETE",
        "trashbin_retention_obligation": "auto,5",
        "versions_retention_obligation": "auto,5",
        "default_phone_region": "GB",
        "updater.release.channel": "beta",
        "localstorage.allowsymlinks": true,
        "app_install_overwrite": [
            "cms_pico"
        ]
    }
}
```

### List of activated Apps

```shell
sudo -u apache php /var/www/html/verivault/console.php app:list
Enabled:
  - activity: 2.17.0
  - bookmarks: 11.0.4
  - calendar: 4.1.0
  - cloud_federation_api: 1.8.0
  - cms_pico: 1.0.19
  - comments: 1.15.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - passwords: 2022.12.20
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - apporder: 0.15.0
  - bruteforcesettings
  - circles: 23.1.0
  - cms_pico_1.1.0-beta.1
  - contactsinteraction: 1.4.0
  - emlviewer: 1.0.2
  - encryption
  - end_to_end_encryption: 1.11.0-beta.1
  - external: 5.0.0
  - federation: 1.13.0
  - files_external
  - files_trashbin: 1.13.0
  - files_versions: 1.16.0
  - forms: 3.0.1
  - login_notes: 1.1.0
  - ocr: 6.0.58
  - recommendations: 1.2.0
  - suspicious_login
  - systemtags: 1.13.0
  - text: 3.4.1
  - twofactor_totp
  - user_ldap
  - weather_status: 1.3.0
```

### Additional info

Original Installation was via CLI, then successive CLI upgrades. 
OS is Fedora 36

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

![image](https://user-images.githubusercontent.com/3902676/206310705-8fc3adc2-79a4-4b7f-b7f1-a882aac4b5b1.png)

Looks like a configuration issue to me. According to their webseite Nextcloud is installed to /verivault but `"htaccess.RewriteBase": "\/"`. 

I suggest to take a look at our configuration for clean urls https://docs.nextcloud.com/server/latest/admin_manual/installation/source_installation.html#pretty-urls 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

I'm closing your report for now. We can always reopen if it turns out to be a bug in Nextcloud.

**Comment by Bockeman** [comment]
@kesselb Thanks.
Having read the #pretty-urls documentation many times before, I read it again and realised that I had misinterpreted these instructions.
It's obvious now that I have got it right, so I cannot even fault the documentation :-(
All working fine now.
