### ISSUE TITLE
Improve change password dialogue

### ISSUE THREAD

**Issue by te-online** [nextcloud/server#3565]
Recently, a user came to me saying that he couldn't change his password.
Only later I found out that he pressed the “change password” button before even typing, because to him the inputs looked disabled.

The biggest issue is probably that we don't have labels here. I stumbled upon this myself, entering two times the new password, not seeing that the first field requires the **current** password.

Suggestions for optimization:
- [ ] Add labels to the input fields.
- [ ] Create two input fields for the **new** password, to make sure you typed it correctly.
- [ ] Ask for the current password with a modal dialogue like in the App Store when installing an app.

![bildschirmfoto 2017-02-21 um 16 27 51](https://cloud.githubusercontent.com/assets/4127167/23171442/ca9f4c84-f852-11e6-8280-830085ce0615.png)
*current change password form on the »personal« page*

I know it would be really great to have a pull-request from me, but I can't do it at the moment – maybe someone else feels that this is an issue, too, and has the resources to quickly fix it. 😊  😳 

@eppfel @jancborchardt ?

**Comment by nickvergessen** [comment]
Sounds good to me

**Comment by chaoticfree** [comment]
I just want to bump @floeschie's issue on the usability flaw in hiding the password reset link until after a failed attempt. The login page must have the password reset link visible at all times. This is expected behaviour. Without it, administrators like me are spending too much time helping our users gain access. Not to mention that it subtly reinforces to new users (which is most users) that this new platform is too hard for them. Thank you!

**Comment by simison** [comment]
Heya @te-online and others! 👋 

I feel like I could grab this as my first Nextcloud issue as I like to work both with code and design.

Looking at the code it looks like it would need a good overhaul, but I don't want to get too deep into it. I'm sure there are other more important issues to work on!

However, if would like to:
- Move labels from inputs to over the field and leave inputs empty
- add visibility toggle to old password field as well
- disable input button until both passwords are filled

Maybe:
- add 3rd input field to confirm new password

Question; does this need to support IE9 anymore or can I clean out this code:
```js
var isIE8or9 = $('html').hasClass('lte9');
// FIXME - TODO - once support for IE8 and IE9 is dropped
// for IE8 and IE9 this will check additionally if the typed in password
// is different from the placeholder, because in IE8/9 the placeholder
// is simply set as the value to look like a placeholder
if ($('#pass1').val() !== '' && $('#pass2').val() !== ''
  && !(isIE8or9 && $('#pass2').val() === $('#pass2').attr('placeholder'))) {
...
```

**Comment by jancborchardt** [comment]
@simison great! :) Agree with your suggestion for solution, and also with your doubt about adding a 3rd field (sonce we have the option to make the password visible).

_Sent from my Motorola XT1039 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by nickvergessen** [comment]
> and there's always the password recovery

Sadly not, 1. depends on the user backend, 2. with encryption enabled and without master key you just loose everything...

We could also just have new password and confirm and then use the modal which you have to enter when you are logged in for too long already.

**Comment by simison** [comment]
> We could also just have new password and confirm and then use the modal which you have to enter when you are logged in for too long already.

True! On the other hand majority of apps/sites asks for the old password _first_ and then new one. Mixing this other way around might be confusing as users expect to see an input for old password in the form.

WDYT? I'm not strongly invested in this idea so either way is fine! Just wanted to point this out.

Do you know where I could look for the code how to implement such modal?

**Comment by nickvergessen** [comment]
`OC.Dialogs` is the magic word in JS source code:
https://github.com/nextcloud/server/blob/65d52a1ddff74b58155b27e342caf30a554d62f5/core/js/js.js#L1655-L1655
https://github.com/nextcloud/server/blob/a2f6fea4081e7920ed6cd33a96e2b80dc0c51303/core/js/oc-dialogs.js#L28-L28

**Comment by te-online** [comment]
>> We could also just have new password and confirm and then use the modal which you have to enter when you are logged in for too long already.

> True! On the other hand majority of apps/sites asks for the old password first and then new one. Mixing this other way around might be confusing as users expect to see an input for old password in the form.

Honestly, I can't tell if this idea is going to be confusing. I think, what we know is that the current implementation is confusing, because the current layout suggests a lot of stuff that isn't true (e.g. the two equally spaced input fields suggest you have to enter a new password twice here, because this pattern is known from other sites).

Personally, I would prefer two input fields to check whether you can actually type the password consistent repeatedly. It's an established pattern and users know and like or dislike it. I'd like to point out that it can be really frustrating to choose a complex password, save it and only notice when you re-login that the password you typed wasn't what you expected it to be. The double-check can mitigate a lot of these cases. And if you're using a password manager, you can fill in both fields at the same time automatically.

Regarding the „old password“ field: From a security perspective it might make sense to have such field. Although I wouldn't ask for the old password when the user just came from the login screen. This might be the use-case for a modal authentication box: Asking for re-authentication when changing your password is not done shortly after you authenticated yourself. But distinguishing between such cases can be a philosophy in itself. Just consider the case where an attacker gets your password, the first thing they'll do is change it – bottom line: We can only guess when it's safe to not ask for the old password, except:
- We could have general guidelines on when to re-ask for authentication that are based on some basic heuristics (e.g. x minutes after login)
- We could estimate the security implications of not asking for the old password

Unless none of the both exceptions is fulfilled, I'd argue for having one “old password” field and two input fields for the new password. Both have to be visually identifiable as what they do and between both blocks we need spacing to show that they ask for different things.

@simison Very cool that you're looking into this as your first nextcloud coding experience 😊

**Comment by jancborchardt** [comment]
Again: Needing to repeat a password is annoying, just like the pattern of repeating an email.

We will have a field for "Current password" and one for "New password", both with labels above the fielda and the eye-toggle to make the password visible.

**Comment by nickvergessen** [comment]
For email I agree completly. But for password seriously no one will use the eye button. They assume they didn't mistype ... AND their files are encrypted without a way to recover them...

I'd really prefer to have a confirmation when encryption is on, with recovery key being of. To get rid of those reports....

**Comment by te-online** [comment]
@jancborchardt Consider the fact that a user doesn't change a password very often. In my opinion the small amount of time spent to retype the password and the small annoyance outweigh the time to spend and the annoyance happening if you change your password to something unintentional. I'm with you in simplifying interfaces and getting rid of annoying processes, where it touches crucial day-to-day tasks, but I still believe that this annoying pattern has a value here.

That said, I appreciate any optimization of the form.

**Comment by jancborchardt** [comment]
@nickvergessen so when encryption is on, we could display a second field. But considering the small fraction of users who use encryption, this should not intrude on the regular UX.

**Comment by eppfel** [comment]
> the small annoyance outweigh the time to spend and the annoyance happening if you change your password to something unintentional

This. Sometimes you have to stop the user or make him think about his action...

**Comment by MorrisJobke** [comment]
See also #5181 where it is highlighted, that the password input would be useful for accounts with encryption enabled.

**Comment by skjnldsv** [comment]
> @skjnldsv skjnldsv self-assigned this on 25 Feb 2018

I need to stop doing that

**Comment by tory-brown** [comment]
hello is this case still open

**Comment by CarlSchwan** [comment]
Done with https://github.com/nextcloud/server/pull/33429
