### ISSUE TITLE
[Bug]: Copy shared link copy label instead of link

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#35684]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Icon should always copy link, not label.
![image](https://user-images.githubusercontent.com/12234510/206525117-68f9f37e-7d88-4967-8838-dc25f23388ca.png)

### Steps to reproduce

1. Hit copy link icon without set a label, link is copied
2. Set label
3. Hit copy link icon, label is copied

### Expected behavior

Link is always copied

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
N/A
```

**Comment by szaimen** [comment]
cc @Pytal

**Comment by szaimen** [comment]
@solracsf is this on 25.0.2?

**Comment by solracsf** [comment]
Too recent update to know, sorry 😝

**Comment by solracsf** [comment]
It seem it is not on 25.0.2, closing.
