### ISSUE TITLE
[Tech Debt] Global interactive element styles override scoped Vue styles

### ISSUE THREAD

**Issue by Pytal** [nextcloud/server#35690]
### Preface

Global styles are contained within some files such as https://github.com/nextcloud/server/blob/8650aff718cd788e98bb534daea6b9b18aae7f82/core/css/apps.scss, https://github.com/nextcloud/server/blob/8650aff718cd788e98bb534daea6b9b18aae7f82/core/css/inputs.scss, https://github.com/nextcloud/server/blob/8650aff718cd788e98bb534daea6b9b18aae7f82/core/css/styles.scss, and so forth.

This issue will specifically address the styles contained within https://github.com/nextcloud/server/blob/8650aff718cd788e98bb534daea6b9b18aae7f82/core/css/inputs.scss.

### Issue

The codebase contains legacy js code which uses global styles for a number of HTML elements across the interface. New frontend elements are being built with Vue and the https://github.com/nextcloud/nextcloud-vue component library but many of the existing UI elements continue to use the pre-existing legacy js implementation and are styled with global styles.

As parts of the interface are being migrated to Vue and coexist with the non-Vue elements, changes had been made to accomodate for this i.e. additional classes had been added to the Vue components and `:not()` CSS pseudo-classes had been added to global styles so as to not target the Vue based elements which use scoped styles.

Some examples include:
- [`231b5ed` (#25774)](https://github.com/nextcloud/server/pull/25774/commits/231b5edc7b2955a028e63c28a2cd6ce89c782437)
- [`f630bd2` (#33259)](https://github.com/nextcloud/server/pull/33259/commits/f630bd27f7ff881050a4ca516a96d00c8ba8afb6#diff-6110e92a0b40ce196d08574dab48c2359be544165bfdc08190ae60fa44b980b9R195)
- [`61cfe35` (#29327)](https://github.com/nextcloud/server/pull/29327/commits/61cfe35a90e69fd96155d1ba52a4438ece4931bc)

The commit [`f630bd2` (#33259)](https://github.com/nextcloud/server/pull/33259/commits/f630bd27f7ff881050a4ca516a96d00c8ba8afb6#diff-6110e92a0b40ce196d08574dab48c2359be544165bfdc08190ae60fa44b980b9R195) adds the `:not(.multiselect__input)` pseudo-class to not target the multiselect input element https://github.com/shentao/vue-multiselect/blob/2.1.6/src/Multiselect.vue#L65 from the https://github.com/shentao/vue-multiselect library which is used in the `NcMultiselect` https://github.com/nextcloud/nextcloud-vue/blob/56aa6c9aeb9cab1acceb62bf454353c5f17cf5de/src/components/NcMultiselect/NcMultiselect.vue#L177-L238 component.

Due to the addition of the `NcSelect` component https://github.com/nextcloud/nextcloud-vue/pull/3435 which uses the https://github.com/sagalbot/vue-select library, a similar change [`d3d5034` (#35165)](https://github.com/nextcloud/server/pull/35165/commits/d3d5034ea40a10355f2ac9b8d041f87261c35ab7#diff-6110e92a0b40ce196d08574dab48c2359be544165bfdc08190ae60fa44b980b9) was necessary to have the correct styling shown below
![image](https://user-images.githubusercontent.com/24800714/206595780-fa080b9f-3e55-4ed9-8c37-f28bf71ef24b.png)

Because of the increased specificity added by the additional `:not()` some elements which depended on global styles became incorrectly styled. This can be seen in the revert PR of the change above https://github.com/nextcloud/server/pull/35665 in which the scoped Vue background select button styles were being overidden by the global styles.

Now the `NcSelect` component is no longer styled correctly as can be seen below
![image](https://user-images.githubusercontent.com/24800714/206596737-763de89e-e45f-458d-b047-1c642deb7afa.png)

### Next steps

The addition of more `:not()` pseudo-classes is no longer viable as then the respective CSS rules will have higher specificity than those of the scoped Vue styles. The solution then would have to make it so that global CSS rules are not applied to `vue-select` elements without using `:not()` and preserve the existing styles of other UI elements. A solution would only have to correct this in the near future but ideally we could remove all dependencies on global styles completely in favour of component scoped styles.

**Comment by Pytal** [comment]
The current design of the Vue background select buttons are dependent on global styles as well

| | Screenshot
--- | ---
**With global styles** | ![image](https://user-images.githubusercontent.com/24800714/206603564-04318669-c971-4658-af32-df1e59ba423b.png)
**Scoped styles only** | ![image](https://user-images.githubusercontent.com/24800714/206603569-952d6d0b-29ed-4edb-8d4b-1689b3c2ab96.png)

**Comment by Pytal** [comment]
What solutions could we go for @PVince81?

**Comment by PVince81** [comment]
@skjnldsv please assist

is there a Vue way to isolate the styles so that they are not affected ?
shadow DOM ?

**Comment by skjnldsv** [comment]
> is there a Vue way to isolate the styles so that they are not affected ?

We do that already, with scoping.

But the issue is that @Pytal's PR used an attribute selector, which has the same level as the way vue does css scoping (with `data-absdev` attributes)
But since Chris also used :not, this resulted in a higher level than the vue scoping, overulling any conflicting rule from vue apps. If you can use a simple class, then we're good :-1:
