### ISSUE TITLE
Display number of contacts below the contacts list

### ISSUE THREAD

**Issue by SamEliotFisher** [nextcloud/server#357]
### Display total number of contacts
I suggest to display the total number of contacts below the contact list for convenience and verification. 

I imported a .vcf file with several hundred contacts and couldn't verify if all contacts got imported correctly. In fact they didn't and I only found out by chance that contacts were missing.

![numberofcontacts](https://cloud.githubusercontent.com/assets/11375752/16707485/d42d7c48-45cf-11e6-92eb-cfd1fff5f1cf.png)

**Comment by Henni** [comment]
Sounds like a nice and simple addition, but please recreate this issue at https://github.com/owncloud/contacts

**Comment by mar1u5** [comment]
Ref: https://github.com/owncloud/contacts/issues/449
