### ISSUE TITLE
Implement occ status command via return codes 

### ISSUE THREAD

**Issue by leegarrett** [nextcloud/server#35704]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 
---

I propose the `--check-if-disabled` flag to `occ maintenance:mode`. It doesn't write any output, it just returns 0 if maintenance mode is off, and 1 if it's on.

This allows to programmatically check for maintenance mode, which makes automation easier. It allows us to use it as an conditional for the cron job (e.g. `ExecCondition`  in the systemd unit), so the cron job will be skipped when maintenance mode is running. Currently it generates an admin email every 5 minutes during maintenance mode.

**Comment by kesselb** [comment]
Hey, sounds good to me. 

https://github.com/nextcloud/server/blob/master/core/Command/Maintenance/Mode.php is the file to modify. 

Would you mind to send a pull request? I guess everything you need is already in the file ;)

**Comment by solracsf** [comment]
```
if [ "$(occ config:system:get maintenance)" == 'false' ]; then
    //fire
fi
```

**Comment by luddinho** [comment]
Or the same with this occ command combined with grep:

```
if [ "$(occ maintenance:mode | grep -o 'enabled\|disabled')" == "disabled" ]; then
    //fire
fi
```

**Comment by leegarrett** [comment]
> Hey, sounds good to me.
> 
> https://github.com/nextcloud/server/blob/master/core/Command/Maintenance/Mode.php is the file to modify.
> 
> Would you mind sending a pull request? I guess everything you need is already in the file ;)

Thanks, and done in PR #35830. I took a look at `Core/Command/Maintenance/ModeTest.php` but didn't understand the code well enough to add test coverage, too.

**Comment by leegarrett** [comment]
> The two above mentioned minimally more complex methods to programmatically check for maintenance mode already now do not make this redundant?

I'm aware that you can do this over a shell call. However:
- It's not always possible nor desirable to spawn a shell
- Having to spawn a shell with e.g. `sh -c` makes the test hard to read with double enclosure quoting, due to the need to escape inside quotes and newlines, and easy for the test to silently fail
- Depending on textual output is flawed as it's not guaranteed to be stable
- Those examples are not covered by tests, which this ideally should have.

**Comment by leegarrett** [comment]
I've done a second PR which I think is overall cleaner and better thought out. It's a parameter to `./occ status` instead of `maintenance:mode`, and doesn't solely decide on maintenance mode. It's also possible to expand it in the future to return other (non-zero) exit codes for other critical issues that prevent normal operation.

**Comment by leegarrett** [comment]
The new PR also avoids the negation that the old one was plagued with.
