### ISSUE TITLE
[Bug]: SAML Logout broken on 25

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#35708]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When using the SAML backend and the SingleLogoutService of the IdP, logging out is broken in NC 25. 

During logout the session cookies are deleted correctly, but later on restored again. So instead of being redirected to the login page eventually, the user is being redirected to the dashboard.

Reverting https://github.com/nextcloud/server/pull/34934 fixes the problem. 

### Steps to reproduce

1. Configure SAML with SLS
2. Login per SAML
3. Try to Logout

### Expected behavior

Be logged out.

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [x] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
- user_saml 5.1.0 amongst the usual ones
```

**Comment by blizzz** [comment]
cc @juliushaertl

**Comment by juliushaertl** [comment]
Had a quick look and pushed two pull requests as I'll be out on vacation next week. See individual pull requests for details, but in short:

- https://github.com/nextcloud/user_saml/pull/677 Hotfix but the change generally makes sense as well (so you could do the enterprise release without another server release iteration)
- https://github.com/nextcloud/server/pull/35723 to harden the session clean method
