### ISSUE TITLE
[Bug]: cron.php not support background command php 8.2.0

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#35709]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nextcloud not support background command cron.php is i have php 8.2.0

Error command in crontab -u www-data -e

`*/5  *  *  *  * php -f /var/www/Pensierando/nx/cron.php
`

### Steps to reproduce

Nextcloud not support background command cron.php is i have php 8.2.0

Error command in crontab -u www-data -e

*/5  *  *  *  * php -f /var/www/Pensierando/nx/cron.php

### Expected behavior

Nextcloud not support background command cron.php is i have php 8.2.0

Error command in crontab -u www-data -e

*/5  *  *  *  * php -f /var/www/Pensierando/nx/cron.php

### Installation method

Official All-in-One appliance

### Operating system

Debian/Ubuntu

### PHP engine version

Other

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Nextcloud not support background command cron.php is i have php 8.2.0

Error command in crontab -u www-data -e

*/5  *  *  *  * php -f /var/www/Pensierando/nx/cron.php
```

**Comment by szaimen** [comment]
Hi, which nc version?

**Comment by tigernero79** [comment]
Version 25.0.2

**Comment by szaimen** [comment]
Can you share your Nextcloud logs?

**Comment by tigernero79** [comment]
yes
[nextcloud.log](https://github.com/nextcloud/server/files/10199538/nextcloud.log)

**Comment by szaimen** [comment]
Thanks, see https://github.com/nextcloud/server/issues/32595

**Comment by ZennithPT** [comment]
I solved this bug by changing the cronjob to execute with php8.1 instead of php that defaults to php8.2 which isnt supported yet in nextcloud

![image](https://user-images.githubusercontent.com/33848154/206930271-864da8b1-9495-4ac3-96f0-14d238c16596.png)
