### ISSUE TITLE
Unexpected "No such file or directory" in nextcloud.log

### ISSUE THREAD

**Issue by not-a-user** [nextcloud/server#3571]
### Steps to reproduce
1. set `'datadirectory' => '/var/owncloud/data',` in `config.php`
2. upload an mp3 file
3. log out
4. log in

### Expected behaviour
Tell us what should happen

No warnings expected in `nextcloud.log`.

### Actual behaviour
Tell us what happens instead

`nextcloud.log` has

    {"reqId":"nHnd9SzFlfbPvZ7xWdri","remoteAddr":"***REMOVED SENSITIVE VALUE***","app":"PHP","message":"fopen(\/var\/owncloud\/data\/***REMOVED SENSITIVE VALUE***\/files\/var\/www\/owncloud\/core\/img\/filetypes\/audio.svg): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/Local.php#216","level":3,"time":"2017-02-22T06:40:08+00:00","method":"GET","url":"\/owncloud\/index.php\/core\/preview.png?file=%2F***REMOVED SENSITIVE VALUE***.mp3&c=f81d88be86da7b4be5c7553d0a73b09c&x=32&y=32&forceIcon=0","user":"***REMOVED SENSITIVE VALUE***","version":"11.0.1.2"}

and similar, all referring to the same path.

I'm afraid the argument to `fopen` is the concatenation of my data directory and the nextcloud install directory. This looks like a bug.

No similar warnings for other file types.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** apache2 2.4.18-2ubuntu3.1

**Database:** sqlite3 3.11.0-1ubuntu1

**PHP version:** 7.0.13-0ubuntu0.16.04.1

**Nextcloud version:** 11.0.1.2

**Updated from an older Nextcloud/ownCloud or fresh install:** upgraded

**Where did you install Nextcloud from:** tar, then upgraded from web interface

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - user_external
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***:443"
        ],
        "datadirectory": "\/var\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***:443\/owncloud",
        "dbtype": "sqlite3",
        "version": "11.0.1.2",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "loglevel": 1,
        "maintenance": false,
        "theme": ""
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** n/a

### Client configuration
**Browser:** firefox 51.0.1

**Operating system:** Ubuntu 16.04

#### Web server error log
<details>
<summary>Web server error log</summary>

```
***REMOVED SENSITIVE VALUE***
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
***REMOVED SENSITIVE VALUE***
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment]
I remember this, but can't find the issue atm.

cc @rullzer

**Comment by rullzer** [comment]
Should be fixed with https://github.com/nextcloud/server/pull/3794
