### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by FuckingToasters** [nextcloud/server#35720]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When visiting the domain where nextcloud is hosted, you'll see a big chunk of error text:
```
* @author Joas Schilling * @author JÃ¶rn Friedrich Dreyer * @author Lukas Reschke * @author Morris Jobke * @author Robin Appelman * @author Roeland Jago Douma * @author Sergio BertolÃ­n * @author Thomas MÃ¼ller * @author Vincent Petry * * @license AGPL-3.0 * * This code is free software: you can redistribute it and/or modify * it under the terms of the GNU Affero General Public License, version 3, * as published by the Free Software Foundation. * * This program is distributed in the hope that it will be useful, * but WITHOUT ANY WARRANTY; without even the implied warranty of * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the * GNU Affero General Public License for more details. * * You should have received a copy of the GNU Affero General Public License, version 3, * along with this program. If not, see * */ require_once __DIR__ . '/lib/versioncheck.php'; try { require_once __DIR__ . '/lib/base.php'; OC::handleRequest(); } catch (\OC\ServiceUnavailableException $ex) { \OC::$server->getLogger()->logException($ex, ['app' => 'index']); //show the user a detailed error page OC_Template::printExceptionErrorPage($ex, 503); } catch (\OCP\HintException $ex) { try { OC_Template::printErrorPage($ex->getMessage(), $ex->getHint(), 503); } catch (Exception $ex2) { try { \OC::$server->getLogger()->logException($ex, ['app' => 'index']); \OC::$server->getLogger()->logException($ex2, ['app' => 'index']); } catch (Throwable $e) { // no way to log it properly - but to avoid a white page of death we try harder and ignore this one here } //show the user a detailed error page OC_Template::printExceptionErrorPage($ex, 500); } } catch (\OC\User\LoginException $ex) { $request = \OC::$server->getRequest(); /** * Routes with the @CORS annotation and other API endpoints should * not return a webpage, so we only print the error page when html is accepted, * otherwise we reply with a JSON array like the SecurityMiddleware would do. */ if (stripos($request->getHeader('Accept'), 'html') === false) { http_response_code(401); header('Content-Type: application/json; charset=utf-8'); echo json_encode(['message' => $ex->getMessage()]); exit(); } OC_Template::printErrorPage($ex->getMessage(), $ex->getMessage(), 401); } catch (Exception $ex) { \OC::$server->getLogger()->logException($ex, ['app' => 'index']); //show the user a detailed error page OC_Template::printExceptionErrorPage($ex, 500); } catch (Error $ex) { try { \OC::$server->getLogger()->logException($ex, ['app' => 'index']); } catch (Error $e) { http_response_code(500); header('Content-Type: text/plain; charset=utf-8'); print("Internal Server Error\n\n"); print("The server encountered an internal error and was unable to complete your request.\n"); print("Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.\n"); print("More details can be found in the webserver log.\n"); throw $ex; } OC_Template::printExceptionErrorPage($ex, 500); } 
```

### Steps to reproduce

1. execute a installation shell-script which i created https://anonfiles.com/c5t4JeL0y9/install_nextcloud_sh
2. visit hostip/nextcloud
3. see error

### Expected behavior

After installing nextcloud (renaming the folder from `server` to `nextcloud`and moving in the `/var/www/html`, visiting https://hostname/nextcloud should redirect to a working website.

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Could not open input file: occ
Could not open input file: occ
-bash: ./occ: No such file or directory
```

### List of activated Apps

```shell
Could not open input file: occ
Could not open input file: occ
-bash: ./occ: No such file or directory
```

### Nextcloud Signing status

```shell
can't even login due to the error mentioned above
```

### Nextcloud Logs

```shell
can't find these files on the webserver
```

**Comment by szaimen** [comment]
Hi, please report this to https://anonfiles.com/c5t4JeL0y9/install_nextcloud_sh

**Comment by FuckingToasters** [comment]
> > Hi, please report this to https://anonfiles.com/c5t4JeL0y9/install_nextcloud_sh
> 
> that's just a download link for the file i use to install it. the issue was just created and is certainly not solved so why closing it as completed?

Please reopen the issue, i want this issue to be solved and not closed as completed if it's not even completed.

**Comment by szaimen** [comment]
The script seems to configure things incorrectly. For help visit https://help.nextcloud.com

**Comment by FuckingToasters** [comment]
> The script seems to configure things incorrectly. For help visit https://help.nextcloud.com

Well it actually isn't, the script is quite simple and only install required modules, download github repo and move downloaded folder to the webserver.
