### ISSUE TITLE
[Bug]: NC25 dark theme display issues

### ISSUE THREAD

**Issue by punkyard** [nextcloud/server#35730]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

black links
![Capture d’écran 2022-12-11 à 13 45 16](https://user-images.githubusercontent.com/59349105/206904737-5db7242e-8ffe-4631-bcba-3753ade427e9.png)

black links
![Capture d’écran 2022-12-11 à 13 34 42](https://user-images.githubusercontent.com/59349105/206904747-e7609d65-a4c7-436b-8393-71b41504dfe0.png)

burger menu over field
![Capture d’écran 2022-12-09 à 23 17 29](https://user-images.githubusercontent.com/59349105/206904773-475c12ad-af84-41f1-8365-86fa40b92aa6.png)

contacts, black groups and circles
![Capture d’écran 2022-12-09 à 23 14 01](https://user-images.githubusercontent.com/59349105/206904829-3ad1c459-f39e-4952-bba4-515f50e24b51.png)

check boxes
![Capture d’écran 2022-12-09 à 23 08 13](https://user-images.githubusercontent.com/59349105/206904853-a053b6b8-f196-4d07-a620-d87b799e9778.png)

in calendar
![Capture d’écran 2022-12-09 à 23 07 29](https://user-images.githubusercontent.com/59349105/206904962-90c71fa3-bf1a-4fe1-a587-8e15e1406e58.png)

hope this will help

### Steps to reproduce

1. upgrade to NC 25
2. use dark mode
3. with safari and brave

### Expected behavior

different text colour

### Installation method

None

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
calendar
text
circles
```

### Additional info

dark breeze had the perfect scales of greys to display a smooth brightness of the screen for the eye

**Comment by VincentWoglo** [comment]
Can you assign me this issues?

**Comment by punkyard** [comment]
this could be related to php latest updates on ubuntu

**Comment by susnux** [comment]
Probably all, except the burger menu, of those issues are because you probably have set black as custom background color so black is the primary color and is used for links, checkboxes and so on.

This might be related to #36464

**Comment by punkyard** [comment]
ok
i've changed the color to another 👍
