### ISSUE TITLE
Update README Screenshot

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#35741]
Actual one starts dating a little 😉 
https://github.com/nextcloud/server/blob/master/README.md#nextcloud-server-

Idea:
https://nextcloud.com/wp-content/uploads/2022/10/nextcloud-hub-files-25-preview.png

**Comment by szaimen** [comment]
The proposal looks good to me. WDYT @nextcloud/server ?

**Comment by szaimen** [comment]
@solracsf can you open a PR? :)
