### ISSUE TITLE
Very slow uploading files

### ISSUE THREAD

**Issue by g4jsg** [nextcloud/server#3574]
Uploading via web or nextcloud desktop software takes roughly 1 to 2 minutes per 40kb word doc.

Uploading via FTP to the same server is perfect and a 40KB word doc takes 1 second to upload.

Nextcloud Server 11.0.1 (stable)
Server has 8GB ram, 4 core 3.2 ghz intel, 130gb spare ssd drive space. Running ‪Ubuntu 16.04.2 LTS‬, plesk onyx Version 17.0.17 Update #17, and resources rarely get over 10% used.
Database: Type: mysql, Version: 5.7.17
PHP: Version: 7.0.13, Memory Limit: 512.0 MB, Max Execution Time: 3600, Upload max size: 511.0 MB

10 users active on the server.

If 1 users uploads 100 files, totalling around 8mb it can bring down the server so other users see Bad Gateway and can't login. 

We see errors such as, 
AH00484: server reached MaxRequestWorkers setting, consider raising the MaxRequestWorkers setting 

And also errors,
	Uncaught Error: Access to undeclared static property: OC\Files\Filesystem::$normalizedPathCache in /var/www/vhosts/xxxxxxx/httpdocs/lib/private/Files/Filesystem.php:806 Stack trace: #0 /var/www/vhosts/xxxxxxx/httpdocs/lib/private/Files/View.php(2018): OC\Files\Filesystem::normalizePath('/katiepwfm/file...') #1 /var/www/vhosts/xxxxxxx/httpdocs/lib/private/Files/View.php(1156): OC\Files\View->unlockFile('/PWFM SHARE/ALL...', 1) #2 [internal function]: OC\Files\View->OC\Files\{closure}() #3 /var/www/vhosts/xxxxxxx/httpdocs/apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure)) #4 [internal function]: Icewind\Streams\CallbackWrapper->stream_close() #5 {main} thrown at /var/www/vhosts/xxxxxxx/httpdocs/lib/private/Files/Filesystem.php#806

Any ideas would be greatly appreciated.

Thanks

**Comment by nickvergessen** [comment]
Please consider updating php to the latest (7.0.16)

> AH00484: server reached MaxRequestWorkers setting, consider raising the MaxRequestWorkers setting

did you try to increase this number?

>  Access to undeclared static property: OC\Files\Filesystem::$normalizedPathCache

is handled in #1166

**Comment by g4jsg** [comment]
@nickvergessen Sorry, increase which number?

Thanks
John

**Comment by nickvergessen** [comment]
https://httpd.apache.org/docs/2.4/de/mod/mpm_common.html#maxrequestworkers

**Comment by MorrisJobke** [comment]
This is more a setup issue. If you still have troubles: please ask in our forums for help: https://help.nextcloud.com
