### ISSUE TITLE
[Bug]: Wrong colour of menu icons with a small screen (smartphone)

### ISSUE THREAD

**Issue by Octopus2** [nextcloud/server#35760]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nextcloud 25.0.2: Menu icons have wrong colors (light instead of dark) on a small screen (smartphone)

![20221213_081841_defaced](https://user-images.githubusercontent.com/4060419/207430884-6abaef4f-6efe-4b5b-9753-c1a98bbc8e00.png)

### Steps to reproduce

See Picture

### Expected behavior

Icons are visible

### Installation method

Community Web installer on a VPS or web space

### Operating system

None

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Nextcloud themes
```

**Comment by szaimen** [comment]
Hi, can you try to clear your browser cache?

**Comment by susnux** [comment]
I can confirm this with NC 25.0.3.
If you have a bright theme, or default theme and no dark mode requested, the icons are rendered white, but the background of the overflow menu is also white.

For the menu bar this is ok, as the default background is blue, but on the overflow menu this is unreadable.
Also the hover color of the toggle (and active background color) is too bright for white icons:
![image](https://user-images.githubusercontent.com/1855448/216158739-61c5ab8f-fa89-4509-bce5-eb76182d80ae.png)
