### ISSUE TITLE
[BITV]: Replace custom tooltips with native one for files

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#35770]
Replace custom tooltips with native one in files:

- [ ] app.js
- [ ] file-upload.js
- [ ] fileactions.js
- [ ] filelist.js
- [ ] files.js
- [ ] mainfileinfodetailview.js
- [ ] newfilemenu.js
- [ ] operationprogressbar.js
- [ ] mainfileinfodetailviewSpec.js

This is a part of https://github.com/nextcloud/nextcloud-vue/issues/2503

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/blob/master/apps/files/tests/js/mainfileinfodetailviewSpec.js is a test file, not source file.
