### ISSUE TITLE
Debugging error message could be made more useful

### ISSUE THREAD

**Issue by kaosdrachen** [nextcloud/server#3577]
### Steps to reproduce
1. Set log level to 0 (debug)
2. Attempt to install an app via the app store
3. Fail (cause unknown, suspect permission issue)
4. Look at log file

### Expected behaviour
Log file contains message "mkdir(): permission denied while trying to create directory /somewhere/ at /var/www/nextcloud/lib/private/installer.php#299"

### Actual behaviour
Log file contains message: 
`{"reqId":"jrokwlAk4jVtJUM9+gEe","remoteAddr":"89.20.90.250","app":"PHP","message":"mkdir(): Permission denied at \/var\/www\/nextcloud\/lib\/private\/Installer.php#299","level":0,"time":"2017-02-22T13:18:18+00:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php","user":"rhouben@systemec.nl","version":"11.0.1.2"}
`

This is a highly informative log message, only missing one thing -- which is unfortunately the one thing I **really** need to know to find out why it's failing.

### Server configuration
**Operating system**: Debian Jessie x86_64

**Web server:** Apache 2.4

**Database:** Postgres 9.4

**PHP version:** PHP5 using php-fpm

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from owncloud

**Where did you install Nextcloud from:** debian/ubuntu package repository as documented on the official website.

**Comment by MorrisJobke** [comment]
Sadly this is nothing we can control, because this error message is given to Nextcloud by PHP in this way. 

See also https://3v4l.org/Fr1PB

Thus closing and it needs to be fixed by PHP itself.
