### ISSUE TITLE
Redirect users on mobile devices (especially Android) to the Nextcloud app

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#35788]
You might be aware that one of the features of the Android Files app, to open internal file links with the App instead of the Browser is broken since Android 13 and there is no way to fix it with the Android app: https://github.com/nextcloud/android/issues/9346#issuecomment-1326113482

This is a feature many Android user will miss. For me it get regularly in the way when receiving a file link via mail or Talk. Therefore I did some brainstorming with @tobiasKaminsky 

We could bring back the feature server side. You may know it from various news sites, online shops, social media sites, etc which try to push you to their app when opening their webpage on a mobile device. The idea:

1. When opening a internal file link by default the browser will open
2. Nextcloud can detect that it is a file link and that the user access it from a mobile device
3. In this case we show some kind of popup/notification with the option:
   * "Open the file with the App" (when clicked we do a redirect to a ncc link which will open the app)
   * "Install the app", so that there is a easy way to install the app in case the user doesn't have it yet (link to the app store)
   * small link "continue in the browser"
   * maybe a checkbox "remember decision"

The nice thing about it:

1. It works on all devices and all mobile operating systems and versions
2. We could extend it to other links in the future, e.g redirect talk links to the talk app, note links to the note app, deck links to the deck app,...

cc @nextcloud/designers  for the general UX and possible design of the dialog
cc @AndyScherzinger because you face the same issue and also participated in the Android ticket

**Comment by schiessle** [comment]
@tobiasKaminsky I discussed it with Andy this week and it seems that there is a better way available now/soon. He sowed me the new  "app icons" in the client to jump from the files client to Talk and the other way around. If we have this mechanism it should be possible to extend the API to send some parameters like "open the files app and go to fileid XYZ".

So it would be no longer a server topic but a client topic for you (files) and @nickvergessen (talk)

**Comment by schiessle** [comment]
fixed with the latest Android beta client thanks to some hacking from @AndyScherzinger and @tobiasKaminsky during the last conference :tada:

**Comment by major-mayer** [comment]
Is there any current way to open a Nextcloud file link in the android app when coming from the browser (Even if it requires manual user confirmation ) ?
I just tried it with Firefox and Chrome and both didn't offer me a button to open a file link in the app.

**Comment by andrtau** [comment]
> fixed with the latest Android beta client thanks to some hacking from @AndyScherzinger and @tobiasKaminsky during the last conference 🎉

How?
