### ISSUE TITLE
Version Control activities are not showed in File activities

### ISSUE THREAD

**Issue by mitsol** [nextcloud/server#3578]
When I restore a specific file in the Web Interface, this action does not put an entry in the Activities tab of the file. This could be useful to know, even when the related file is shared within a group.

What do you think?

**Comment by nickvergessen** [comment]
We have restore activities and they work pretty well here:
> ![bildschirmfoto vom 2017-02-22 15-23-05](https://cloud.githubusercontent.com/assets/213943/23215505/e80ed544-f912-11e6-93b6-caa614e3bd33.png)
