### ISSUE TITLE
Publish the Release Build Script

### ISSUE THREAD

**Issue by JaredBoone** [nextcloud/server#3582]
Please publish the script used to package the Nextcloud source code for release

**Comment by JaredBoone** [comment]
@LukasReschke @BernhardPosselt @icewind1991 I created this issue as a reminder per our earlier conversation. Thanks!

**Comment by Xuanwo** [comment]
@nickvergessen Any update ?

**Comment by nickvergessen** [comment]
Sorry, I have no idea about the build script.

**Comment by JaredBoone** [comment]
I'd also be interested in an update on this request.

**Comment by Xuanwo** [comment]
I thought there was a script for Nextcloud to build there release like `11.0.3`.

**Comment by skjnldsv** [comment]
Do we wanna do this?

**Comment by nickvergessen** [comment]
For now the answer is "no"

**Comment by gary-kim** [comment]
I have a build script that I use personally. Any objection to me releasing it publicly?

**Comment by nickvergessen** [comment]
As long as it is "correct" and doesnt result in other people publishing broken/custom releases everywhere, I guess no one will stop you.

**Comment by gary-kim** [comment]
Okay, I made the repo public: https://github.com/gary-kim/nc-build-script. Feel free to take a look over it.

**Comment by alepesiy** [comment]
they (NC) just ignore this topic?
