### ISSUE TITLE
File actions menu entries too light

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#3584]
@nextcloud/designers check this out:
![capture du 2017-02-22 17-23-05](https://cloud.githubusercontent.com/assets/925062/23220902/b1bacef6-f923-11e6-8c3e-d3c4eb4dd4b4.png)
it’s way too light, I guess as a result of the latest SCSS restructuring maybe @skjnldsv?

Compare with this how it should be, the #expanddiv links (.5 opacity by default, and 1 opacity on hover):
![capture du 2017-02-22 17-23-38](https://cloud.githubusercontent.com/assets/925062/23220901/b1a06a66-f923-11e6-8ca6-904232b4675d.png)

**Comment by skjnldsv** [comment]
Duplicate: #3522
