### ISSUE TITLE
Feature Request: Open external pages in new tabs/windows

### ISSUE THREAD

**Issue by derritter88** [nextcloud/server#35852]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I have add my personal GitLab server to my Nextcloud account and enabled to show an icon at the app bar.
As soon as I click on it I will go to my GitLab site.

**Describe alternatives you've considered**
Open the GitLab page (or any other external apps) in a new, separate tab.

**Additional context**
-

**Comment by kesselb** [comment]
Are you using https://apps.nextcloud.com/apps/external to add the icon to the top navigation?

**Comment by derritter88** [comment]
No, I am using the regular GitLab integration.

Possible that I created my FR at the wrong side as this would be the right one --> https://github.com/nextcloud/integration_gitlab

**Comment by derritter88** [comment]
https://github.com/nextcloud/integration_gitlab/issues/56
