### ISSUE TITLE
Poor performance for files app with lots of files/photos/videos etc.

### ISSUE THREAD

**Issue by apoorv569** [nextcloud/server#35850]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install the Nextcloud all-in-one docker with all optional feature listed on the AIO web UI on port 8080
2. Create couple of users to start with
3. Upload lots of photos/videos and other files (15-20k files)

### Expected behavior 
Should open files and folders with decent amount of time.

### Actual behavior 
Most of the times it fails to load files and other times it takes a lot of time to open as in up to 5-10 mins.

### Host OS 
I am running this on a VM on my ProxmoxVE OS. The host OS is Ubuntu 22.04 Server LTS.

#### Nextcloud AIO version 
Nextcloud AIO v3.2.0

#### Current channel 
Latest

#### Other valuable info 
ATM I am running the VM with 2 cores and 8GB RAM. I have tried turning all optional containers on/off and increasing the CPU cores to 4 and RAM to 16GB as well but didn't saw much difference.

I do see these error messages when I am either just opening a folder with lots of files or upload more files (if I manage to open the folder first).

![2022-12-21_14-05](https://user-images.githubusercontent.com/53279454/208858207-5a0ed553-7051-4f7c-9f7f-e3acf2981131.png)

In this screenshot there is a error regarding `imaginary` but I have the `imaginary` container turn off.

**Comment by apoorv569** [comment]
> I am sorry but I fear this is nothing we can fix in AIO. It rather needs to be fixed in server. Moving there.
> 
> Also as recommendation: for handling this many files I would always use the desktop client: https://github.com/nextcloud/desktop

I see. So this problem is only with the web UI?

**Comment by szaimen** [comment]
> I see. So this problem is only with the web UI?

I think so. Another workaround would be organizing your files into subfolders with much less files inside one folder which should also make it work.

**Comment by apoorv569** [comment]
> > I see. So this problem is only with the web UI?
> 
> I think so. Another workaround would be organizing your files into subfolders with much less files inside one folder which should also make it work.

I see. Thank you for information. I hope that this could be improved in future. :+1:

**Comment by szaimen** [comment]
Hi, please update to 25.0.7 or better 26.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 26-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by apoorv569** [comment]
> Hi, please update to 25.0.7 or better 26.0.2 and report back if it fixes the issue. Thank you!
> 
> My goal is to add a label like e.g. 26-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!
> 
> If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

Hi, I found a tool online (a python script) called [phockup](https://github.com/ivandokov/phockup) that reads a photo's `exif` data and organizes them in directories according to date the photo was taken, so I don't have this issue now.

I am using AIO container, so I did update it recently, most of the apps I had installed are not working, but I don't have this issue since you first gave me the suggestion to organize them in multiple directories.

**Comment by szaimen** [comment]
> but I don't have this issue since you first gave me the suggestion to organize them in multiple directories.

all right, cool!
