### ISSUE TITLE
Reset password, German translation a bit bumpy

### ISSUE THREAD

**Issue by Tarry91** [nextcloud/server#3586]
When generating the password reset link, the text displayed in german is a bit bumpy to read and has a typo.

The typo is "bette" instead of "bitte" in the last sentence.

I joined transifex to fix this translation myself, bit I my request to join the team hasn't been approved yet, so I opened the issue.

**Comment by LukasReschke** [comment]
> I joined transifex to fix this translation myself, bit I my request to join the team hasn't been approved yet, so I opened the issue.

I've approved you right now :-)
