### ISSUE TITLE
[Bug]: Contacts menu inverts emoji colour when using dark mode for status text

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/server#35869]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![error](https://user-images.githubusercontent.com/7427347/209173167-b92e52e1-2485-4247-af12-3950412039a6.png)

### Steps to reproduce

1. Use a dark theme
2. set an emoji with your status
3. go to a user chat, and click on the three dot menu over their avatar

### Expected behavior

Emojis are in regular colours

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
c.nc
```

### List of activated Apps

```shell
c.nc
```

**Comment by szaimen** [comment]
I suppose this is on 25?

**Comment by szaimen** [comment]
I think this should be resolved with 25.0.3
