### ISSUE TITLE
[Bug]: OpenID Connect Login does not set skeleton in user's profile.

### ISSUE THREAD

**Issue by RegisPerdreau** [nextcloud/server#35875]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

We have set up a skeleton for new nextcloud accounts, but it is not taken into account for users of the "OpenID Connect Login" plugin. For locally created users the skeleton is taken into account.
For "OpenID Connect Login" users, even if we use the default skeleton (without the line "'skeletondirectory' => '/appli/skeleton'," in the config.php) no file is copied to the user's profile.
Nextcloud is 24.0.7, OpenID Connect Login" is version 2.4.0.

### Steps to reproduce

- 
- set OpenID Connect Login
- log in
- nothing is copied from skeleton
- works fine with local login.

### Expected behavior

We expect to have files copied from skeleton when user is logged in.

### Installation method

Community Manual installation with Archive

### Operating system

RHEL/CentOS

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
.
```

### List of activated Apps

```shell
.
```

### Nextcloud Signing status

```shell
.
```

### Nextcloud Logs

```shell
.
```

### Additional info

.

**Comment by szaimen** [comment]
Hi, please report this to https://github.com/pulsejet/nextcloud-oidc-login/issues. Thanks!
