### ISSUE TITLE
[Bug]: webo service doesnt works with emails

### ISSUE THREAD

**Issue by haroldsoixante** [nextcloud/server#35909]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

  hello
  
  (sorry, I dont see anywhere else I could report on this)
  problem is, when going to the free account on nextcloud, I select webo service, then I put my email address, then its blocked :+1: 
  Error: Something happened 
  
  even with the "accept term of service" marked up.
  whats going on?
  thank you vm

### Steps to reproduce

hello

(sorry, I dont see anywhere else I could report on this)
problem is, when going to the free account on nextcloud, I select webo service, then I put my email address, then its blocked :+1: 
Error: Something happened 

even with the "accept term of service" marked up.
whats going on?
thank you vm

### Expected behavior

it works?

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
1
```

**Comment by szaimen** [comment]
cc @jospoortvliet where would be the best place to report this?

**Comment by kesselb** [comment]
https://webo.hosting/contact/ maybe?

**Comment by szaimen** [comment]
> https://webo.hosting/contact/ maybe?

Sounds good

**Comment by haroldsoixante** [comment]
> 

hello

well, I tried to, regarding the https://nextcloud.com/sign-up/ : 

This is the issue on nextcloud.com website, not with us.

is it possible to manage this issue?

I thank you vm!

**Comment by szaimen** [comment]
You need to contact webo. We are not responsible for their service.
