### ISSUE TITLE
App Store: Category for All Apps

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#3592]
Unsure if this is missing here or in App Stores API 😁 but yes, also if we introduce sorting with #3591 we should have this. Would also make searching for apps easier 😅 

<img width="282" alt="bildschirmfoto 2017-02-23 um 10 28 18" src="https://cloud.githubusercontent.com/assets/19711361/23252950/f8a0112a-f9b2-11e6-848e-96cfd0ded866.png">

<img width="250" alt="bildschirmfoto 2017-02-23 um 10 30 10" src="https://cloud.githubusercontent.com/assets/19711361/23252980/1939122e-f9b3-11e6-91e7-037feffd1b3b.png">

@BernhardPosselt @nextcloud/appstore

**Comment by BernhardPosselt** [comment]
App Store API will give you a full database dump for your current Nextcloud version, so EVERYTHING is supported ;)

**Comment by MariusBluem** [comment]
So ... Let's do this 😜

**Comment by MariusBluem** [comment]
#126 sorry 🙄
