### ISSUE TITLE
[Bug]: Regression: NC 25: Copying internal links from sidebar while document is opened does not work

### ISSUE THREAD

**Issue by gohrner** [nextcloud/server#35922]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

It's not possible to copy a document's internal link from the sidebar while the document is opened.

See screencast:

![Copy internal link fails Peek 2022-12-30 17-17](https://user-images.githubusercontent.com/26199042/210091103-90874f44-1d85-4d56-9bd2-9ce27a69aa0f.gif)

### Steps to reproduce

1. Open file in editor in nextcloud
2. Open sidebar
3. Klick the "Copy internal link" icon

The message will state the the link was copied, but in fact this is not the case. The link was NOT copied.

### Expected behavior

The internal link should be copied when clicking the "copy internal link" icon.

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.ohrner.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.2.3",
        "overwrite.cli.url": "https:\/\/nextcloud.ohrner.net\/",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpsecure": "tls",
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "DE",
        "simpleSignUpLink.shown": false,
        "memories.exiftool": "\/mnt\/store\/misc\/var_www_nextcloud\/apps\/memories\/exiftool-bin\/exiftool-amd64-glibc"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - appointments: 1.14.7
  - calendar: 4.2.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.2
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - facerecognition: 0.9.11
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - forms: 3.0.2
  - integration_zammad: 2.0.1
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.2.2
  - maps: 0.2.3
  - memories: 4.9.3
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - passwords: 2022.12.11
  - photos: 2.0.1
  - polls: 4.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recognize: 3.3.4
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - richdocuments: 7.0.2
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.2
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - impersonate: 1.11.0
  - suspicious_login
  - twofactor_totp
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional info

No errors shown in JavaScript console.

**Comment by gohrner** [comment]
This problem already seems to have been reported in the Nextcloud forum on 21st of November already:

https://help.nextcloud.com/t/copying-inner-link-doesnt-work-since-update-nc-25/150364

There was no feedback / reaction to this posting so far, though. :-(

**Comment by EDRi-org** [comment]
We reproduced this bug on our Nextcloud 25 server. It's a bug that's very disruptive for larger teams. :(

**Comment by maximelehericy** [comment]
same on NC 25.0.3
@juliushaertl any thoughts ?

**Comment by pasith3e** [comment]
Hi,
can we please get a fix for this Issue? This a major disruption to the Workflow.

**Comment by gohrner** [comment]
@szaimen: I just noticed (with NextCloud 25.0.3) that also copying the internal link in the regular sidebar simetimes does not work, but a repeated attempt then does...

Is this probably related / the same issue, or shall I open a new bug report for that?

**Comment by szaimen** [comment]
Fis is here afaics: https://github.com/nextcloud/server/pull/36450
