### ISSUE TITLE
[Bug]: Cannot make hidden files starting with periods on Nextcloud

### ISSUE THREAD

**Issue by Starcr0ss** [nextcloud/server#35934]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I cannot make hidden folders on Nextcloud that begin with periods ("."). When I try to do it on the web interface, I get a notification saying "Could not create folder '.a'". On Android, if I try to create a hidden folder "Server not found" appears. (The server itself is fine). I am able to create hidden folders through my server's SSH (and then running `occ files:scan`) but Nextcloud does not play well with these. On web- Clicking the hidden folder sends be back to the root folder of my files. On Android- "The folder /.a/ does not exist anymore", yet refreshing makes it reappear.
This issue creates problems in apps that depend on hidden folders for functionality. For example, Joplin needs a .resource folder to sync to Nextcloud but I get a 404 error when it tries to access it. When I use Memories on Nextcloud, I cannot archive photos because it needs a .archive folder.

### Steps to reproduce

1. Create hidden folder that starts with a period.
2. Nextcloud comes up with an error saying that it is unable to create the directory because it "doesn't exist" (mentioned more specifically in the bug description)
3. Folder is never created

### Expected behavior

Nextcloud should create the folder and not be treated as if it does not exist. Opening the folder should show the contents and other applications should be able to add files to those folders. My server should not show 404 errors when accessing these folders through other applications

### Installation method

Other Community project

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "2": "nextcloud.starcross.ga"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "default_phone_region": "US",
        "version": "25.0.2.3",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "app_install_overwrite": [
            "apporder",
            "carnet"
        ],
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "music.lastfm_api_key": "fc019ce0d58404109cd9e1b183ec648a",
        "has_rebuilt_cache": true,
        "memories.exiftool_no_local": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI"
        ],
        "memories.ffmpeg_path": "\/usr\/bin\/ffmpeg",
        "memories.ffprobe_path": "\/usr\/bin\/ffprobe",
        "memories.transcoder": "\/home\/serena\/web\/nextcloud.starcross.ga\/public_html\/apps\/memories\/exiftool-bin\/go-vod-aarch64",
        "memories.no_transcode": false,
        "memories.qsv": true,
        "preview_max_memory": 4096,
        "preview_max_filesize_image": 256
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.1.2
  - carnet: 0.24.6
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - collectives: 2.1.1
  - comments: 1.15.0
  - contacts: 5.0.2
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.2
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - forms: 3.0.1
  - holiday_calendars: 0.2.1
  - integration_discourse: 1.0.4
  - integration_mastodon: 1.0.3
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.2.2
  - maps: 0.2.1
  - memories: 4.9.3
  - metadata: 0.17.0
  - music: 1.7.0
  - news: 20.0.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - previewgenerator: 5.1.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - ransomware_protection: 1.14.0
  - recognize: 3.3.3
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - richdocuments: 7.0.2
  - richdocumentscode_arm64: 22.5.802
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - side_menu: 3.4.1
  - support: 1.8.0
  - survey_client: 1.13.0
  - suspicious_login: 4.3.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - documentserver_community: 0.1.13
  - encryption: 2.13.0
  - federation: 1.15.0
  - files_external
  - onlyoffice: 7.6.8
  - quota_warning: 1.15.0
  - systemtags: 1.15.0
  - unroundedcorners: 1.0.8
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
There's just a bunch of cron entries. Also /settings/admin/logging page is broken on Nextcloud v25.0.2
```

### Additional info

Running `tail -f /path/to/nextcloud.log` does not show any errors relating to these folders, their creation, or unsuccessfully entering them.
Nextcloud was installed through the quick app installer feature of Hestia Control Panel.

**Comment by szaimen** [comment]
Sorry but I cannot reproduce the issue. Just tried with 25.0.2. This sounds like a configuration issue. You will probably get more help on https://help.nextcloud.com regarding your issue.
