### ISSUE TITLE
App Store: Get rid of the Stars 

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#3593]
On apps.nextcloud.com this is used for rating:

<img width="173" alt="bildschirmfoto 2017-02-23 um 10 31 15" src="https://cloud.githubusercontent.com/assets/19711361/23253056/6e039202-f9b3-11e6-8f6a-fb19f786e256.png">

I think we should introduce this also in the server to show uniformity 😉 Currently we are using the stars (from the old App Store):

<img width="259" alt="bildschirmfoto 2017-02-23 um 10 34 11" src="https://cloud.githubusercontent.com/assets/19711361/23253121/a40f2ece-f9b3-11e6-9677-acc49ab1c62f.png">

@BernhardPosselt @nextcloud/appstore

**Comment by nickvergessen** [comment]
Something for https://github.com/nextcloud/server/issues/3194 maybe?

**Comment by jancborchardt** [comment]
Stars have several advantages over text though:
- Every rating occupies the same width
- They are not language-dependent
- They are an absolute scale. You have no idea if »very positive« is the absolute best, or if there is something better.
- They are used all over the place …


cc @BernhardPosselt @eppfel @nextcloud/designers

**Comment by BernhardPosselt** [comment]
I'm fine with with probably every rating display solution (stars, text, progress bars etc). The only thing that I really want to avoid however is to let users rate an app by giving it a certain amount of stars (reasons for that are explained in the issue tracker).

The reason why it is implemented like that right now on the store is purely to get people off the stars mindset (e.g. I see a star rating but how can I rate it with stars). 

If you feel like this is not enough of a reason to warrant two different rating display styles then I really don't have a problem with adjusting the styling on the store :)

**Comment by jancborchardt** [comment]
@BernhardPosselt I would really strongly advise against having separate means of rating and displaying the rating. Stars is just really simple: It shows the current rating, you can click on it to rate it yourself, and afterwards it can show your rating. :)

I’d really prefer if we can standardize on stars, for the reasons mentioned above. I know that for example Netflix and Youtube moved away from stars but they just have a bit of a different focus. App stores like Apple App store, Google Play store, Amazon and even Facebook use star ratings. And that’s what many many people are used to and which simply works for this. ;)

**Comment by juliushaertl** [comment]
So what's the status here? If we keep using stars, we should change the display in the app store.

**Comment by jancborchardt** [comment]
Yes, the display in the appstore should be changed to stars. It’s already confusing enough that the scale is "Good" "OK" and "Good", where "OK" and "Good" are kind of the same level of enthusiasm.

**Comment by juliushaertl** [comment]
Closing since we stars are a rating system that is known by users and are a common pattern for app ratings. The related app store issue is at https://github.com/nextcloud/appstore/issues/226
