### ISSUE TITLE
App looks strange if no image is provided

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#3594]
If an app provides no image, the app looks quite strange 😕 

<img width="270" alt="bildschirmfoto 2017-02-23 um 10 38 57" src="https://cloud.githubusercontent.com/assets/19711361/23253336/6fc38d08-f9b4-11e6-9ce5-8d7dd2495c03.png">

apps.nextcloud.com solves this problem by showing the following placeholder:

<img width="418" alt="bildschirmfoto 2017-02-23 um 10 40 47" src="https://cloud.githubusercontent.com/assets/19711361/23253381/95efe9cc-f9b4-11e6-91cd-3007278fe6b8.png">

...but I don't think this solves our problem at this place 🤔 Any ideas from our @nextcloud/designers or @nextcloud/appstore guys 😅

**Comment by BernhardPosselt** [comment]
IMHO we need a better default icon in case no screenshots can be created by the dev. I'll let you come up with one and we can reuse that on the app store as well ;)

**Comment by MariusBluem** [comment]
A pixelated files app maybe 🤔

**Comment by BernhardPosselt** [comment]
Most apps are purely backend related (therefore no screenshots possible) so this is what a quick google turned up https://www.google.at/search?q=backend+icon&client=firefox-b-ab&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjbr_PU_6XSAhVEkiwKHZGYDOQQ_AUICCgB&biw=1276&bih=698&dpr=2

**Comment by nickvergessen** [comment]
Something for https://github.com/nextcloud/server/issues/3194 maybe?

**Comment by jancborchardt** [comment]
This is fixed now with merging the apps mgmt redesign. :) 
#3195
