### ISSUE TITLE
Exposing GuzzleHttp\Client::asyncRequest()

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#35959]
Since quite some time Guzzle added support for async requests:
https://docs.guzzlephp.org/en/stable/quickstart.html#async-requests

It is also available in the code base we ship, but currently not accessible as we wrap away guzzle with our 
https://github.com/nextcloud/server/blob/8aea25b5b92dac105f7e862470ee0dcf0e876615/lib/private/Http/Client/Client.php#L51

Async requests would come in very handy and could help to speed up several requests were we don't care about the outcome, e.g. potential webhooks.

A method like the following would work
```php
	public function postAsync(string $uri, array $options = []): void {
		$this->preventLocalAddress($uri, $options);

		if (isset($options['body']) && is_array($options['body'])) {
			$options['form_params'] = $options['body'];
			unset($options['body']);
		}

		$this->client->requestAsync('post', $uri, $this->buildRequestOptions($options));
	}
```

but it hides away the Promise option. But if we'd expose that, it would mean more wrapping or exposing Guzzle.
Unluckily the Async stuff is not part of the PSR, so we can't write a generic wrapper for that.

Other current solutions:
* Make the app/server depend on Guzzle directly
* Ignoring user cancel and send the output while the process continues afterwards: https://github.com/nextcloud/circles/blob/96447086eca1b4dfba21b05f750de3f9c13e605e/lib/Service/MiscService.php#L358-L370

Any preferences?
cc @come-nc @ChristophWurst

**Comment by come-nc** [comment]
If we need it, I’d go with exposing Guzzle but use their interfaces as much as possible, in a try to make it easier to switch the day there is a standard for this.
I’m not convinced wrapping makes sense.

**Comment by nickvergessen** [comment]
> If we need it

Talk needs it for upcoming fields :)

**Comment by ChristophWurst** [comment]
With the trouble we've had with directly exposed 3rdparty structs from Doctrine and Symfony I would prefer a thin wrapper. The underlying lib may still change in a way that doesn't allow us to adapt the changes in a non-breaking way from our exposed APIs perspective but it increases our chances.

**Comment by nickvergessen** [comment]
Looking at https://github.com/nextcloud/3rdparty/blob/c3d7b26c96cb8778c1803ec20c8a04eef0f711b4/guzzlehttp/promises/src/PromiseInterface.php#L14
I would basically add a similar interface and wrap all of those methods apart from resolve() and reject()
