### ISSUE TITLE
[Bug]:  default_phone_region not used when frontend evaluates user phone number

### ISSUE THREAD

**Issue by mafjensengithub** [nextcloud/server#35952]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The users phone numbers cannot be set when using "local" format. It seems like the default_phone_region value is not parsed to libphonenumber-js when evaluating the phonenumber in the frontend. No data is passed to the server until the "universal" phone with a +XX in front is used. This seems to be consistant with the frontend not passing anything back to the server before libphonenumber-js is providing a "valid" result, and if default_phone_region is not passed to libphonenumber-js, the number requires +XX in front no matter how the setting is in config.php.

### Steps to reproduce

Try to change user phone, cannot see any calls to server (number not saved) until +XX is added.

### Expected behavior

Phone should be saved if entered in local format.

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Provided on request
```

### List of activated Apps

```shell
Provided on request
```

### Nextcloud Signing status

```shell
Provided on request
```

### Nextcloud Logs

```shell
No log entries
```

**Comment by mafjensengithub** [comment]
@Pytal (Might be related to: Remake phone number property saving with Vue )

**Comment by szaimen** [comment]
Hi, can you post your config.php?

**Comment by mafjensengithub** [comment]
Config.php
<?php
$CONFIG = array (
  'instanceid' => 'ocycdgfhhfgg',
  'passwordsalt' => 'hgghsdhghsdghsgdhg',
  'secret' => 'Alotofverysecretstuff',
  'trusted_domains' => 
  array (
    0 => '192.168.1.118',
    1 => 'home.hmls.dk',
  ),
  'datadirectory' => '/var/www/html/nextcloud25/data',
  'dbtype' => 'mysql',
  'version' => '25.0.2.3',
  'overwrite.cli.url' => 'https://192.168.1.118/nextcloud25',
  'dbname' => 'nextcloud25',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'webuser',
  'dbpassword' => 'SomeSecretPassword',
  'installed' => true,
  'maintenance' => false,
  'app_install_overwrite' => 
  array (
    0 => 'bookingapp',
    1 => 'financeapp',
    2 => 'impersonate',
  ),
  'skeletondirectory' => '',
  'templatedirectory' => '',
  'default_language' => 'da',
  'default_locale' => 'da_DK',
  'default_phone_region' => 'DK',
  'customclient_desktop' => '',
  'customclient_android' => '',
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => 'TEST',
  'mail_domain' => 'sometest.dk',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'mail.sometest.dk',
  'mail_smtpname' => 'some@sometest.dk',
  'mail_smtppassword' => 'SECRETSTUFF',
  'updater.release.channel' => 'beta',
  'theme' => '',
  'loglevel' => 2,
  'data-fingerprint' => '14318d07285a61b2d2e8eeefb4af47b9',
);

**Comment by mafjensengithub** [comment]
The issue present in 2 different server setups Both 25.0.2 on on beta and on on stable release, both set with 'DK' as phone region.

**Comment by mafjensengithub** [comment]
Seems like the call to isValidPhoneNumber in apps/settings/src/components/PersonalInfo/PhoneSection.vue is missing the 2nd parameter (country code for validation)
