### ISSUE TITLE
[Bug]: check_data_directory_permissions => 'false' not honoured?

### ISSUE THREAD

**Issue by stevenengland** [nextcloud/server#35967]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In my /opt/nextcloud/config/config.php I set the option 'check_data_directory_permissions' => 'false'.

When I access the web UI or run the config lister via

`sudo -u www-data php /opt/nextcloud/occ config:list`

I still get the error
```
Your data directory is readable by other users.
Please change the permissions to 0770 so that the directory cannot be listed by other users.
```

Seems to me that the setting is not honoured or it does not do what I thought it is for... :)

### Steps to reproduce

1. Have a 'datadirectory' => 'xyz' that has other permissions then 770
1. Set option 'check_data_directory_permissions' => 'false'
2. Gather infos about set options via sudo -u www-data php /opt/nextcloud/occ config:list

### Expected behavior

No error appears if the "wrong" directory options are set.

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
with the error described I cannot provide them :)
```

### List of activated Apps

```shell
with the error described I cannot provide them :)
```

**Comment by solracsf** [comment]
What about:
`'check_data_directory_permissions' => false,`
?

**Comment by stevenengland** [comment]
Hi @solracsf , can you tell me a bit more? Because I mentioned twice that I already deactivated check_data_directory_permissions via config file I am now unsure if you missed that or if there is something that I should do now.

**Comment by stevenengland** [comment]
Ahhhh, the single quotes ... should not be there ... Shame on me. So obvious. But I must admit that this error is present throughout my complete config file. Need to check the ansible role I used... Sorry...
