### ISSUE TITLE
[Bug]: When a user is a member of a lot of groups, the row height does not adjust properly

### ISSUE THREAD

**Issue by diabolicvincent-git** [nextcloud/server#35968]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Concerning the user administration page (/settings/users/admin). When a user is a member of a lot of groups, the row height does not adjust properly and text overlaps with other users' rows making it near impossible to use the user administration page.
![6f94600e2ccaa284d364f7cd89d015b1cb260b7e2e8643f4940d0181418273a0 Kopie](https://user-images.githubusercontent.com/72661240/210406167-883360ef-bd2e-49ff-b0d7-3c91321fe984.png)

### Steps to reproduce

1. Have a considerable number of nextcloud groups
2. Add multiple users to a considerable number of these groups
3. Go to the user administration page

### Expected behavior

The rows should expand to fit the text of the group column, or overflow should be scrollable.

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

```shell
Will hand in later.
```

### List of activated Apps

```shell
Will hand in later.
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Will hand in later.
```

### Additional info

-

**Comment by diabolicvincent-git** [comment]
Should be an easy fix with a little CSS :)

**Comment by szaimen** [comment]
Hi, whiwh NC version?

**Comment by diabolicvincent-git** [comment]
25.0.1

**Comment by szaimen** [comment]
Please try to update to 25.0.2 which should have fixed the issue already a while ago.
