### ISSUE TITLE
[Bug]: Three-dots drop-down menu broken on small screen resolution

### ISSUE THREAD

**Issue by Cwpute** [nextcloud/server#35971]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

My small laptop sports a screen resolution of 1366x768.
In file explorer, when i use the drop-down menu attached to the three-dots icon on each file, the size of the window is too small to show the menu in its entirety unless i scroll down pre-emptively (i can't scroll after having opened that menu because any click outside the menu closes it afterwards).
The name of numerous options also copiously overflow the size of the menu.
![firefox_WqoEGQ1S8U](https://user-images.githubusercontent.com/80604512/210430050-6e44c18f-0a94-46d0-8933-5e24fe60f2cd.png)
This screenshot was taken in fullscreen without the windows bar below and without the browser bar above. As you can imagine, the issue is even worse without the browser window in fullscreen.

### Steps to reproduce

1. Use a screen with a resolution of at most 1366x768 pixels
2. Use grid-view in the file-explorer
3. Click on the drop-down menu for any file

### Expected behavior

The drop-down menu in its entirety should be visible without scrolling.
The options in the menu shouldn't have their name overflow the menu borders.

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
can't get that info as i'm only a user, not an admin
```

### Additional info

A similar visual bug regarding low resolution screens was reported here:
* https://github.com/nextcloud/server/issues/34777

**Comment by joshtrichards** [comment]
Related to #35938 (I think)

**Comment by skjnldsv** [comment]
Fixed with 28
