### ISSUE TITLE
[Bug]: Nextcloud Instant Try refuses protonmail

### ISSUE THREAD

**Issue by ShalokShalom** [nextcloud/server#35982]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi there 

I have an email address at https://protonmail.com and both protonmail.ch, as well as protonmail.com addresses are rejected at the free trail. 

I guess proton.me is also not working. 

https://nextcloud.com/instant-trial/

### Steps to reproduce

1. Go to https://nextcloud.com/instant-trial/
2. Try shalokshalom@protonmail.ch 

### Expected behavior

Login

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
.
```

### Additional info

I wonder why you need a phone number for a simple try. If there is any good reason, I suggest adding that info, it looks creepy now.

**Comment by kesselb** [comment]
I forwarded your report and close the report here (as this repository is for the server source code).

If you look for an easy way to setup a Nextcloud instance for testing: https://github.com/nextcloud/all-in-one
