### ISSUE TITLE
[Bug]: Files visible to admins when master key is disabled

### ISSUE THREAD

**Issue by summersab** [nextcloud/server#36036]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I distinctly remember in v24 that when server-side encryption is enabled and the master key is disabled, system admins could not access user files without them being shared. Using the impersonate app, an admin could not log into another user's account and view their files - the contents of the files could not be decrypted.

In v25, this is not the case. Strangely, upon reinstalling v24, I cannot get the files to be restricted, either. Was there a code change to the default encryption app that needs to be reversed?

### Steps to reproduce

1. Install NC
2. Enable encryption:
```
php occ app:enable encryption
php occ encryption:enable
php occ encryption:encrypt-all
php occ encryption:disable-master-key
```
3. Install the impersonate app
4. Create a non-admin user
5. Upload a file with the non-admin user
6. Using the admin account, log into the non-admin account using the impersonate app
7. The file of the non-admin user is able to be opened

### Expected behavior

The admin should be unable to view the contents of other users' files with server-side encryption enabled and the master key disabled (unless the file is shared with them).

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "dbtype": "pgsql",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "version": "24.0.2.1",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.203",
            "127.0.0.1"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "upgrade.disable-web": "0",
        "debug": "true",
        "simpleSignUpLink.shown": "false",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "allow_local_remote_servers": "true",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/nextcloud.nunimbus.com",
        "default_phone_region": "US",
        "dbport": "",
        "dbtableprefix": "oc_",
        "maintenance": false
    }
}
```

### List of activated Apps

```shell
- accessibility: 1.10.0
  - activity: 2.16.0
  - cloud_federation_api: 1.7.0
  - comments: 1.14.0
  - contacts: 4.2.3
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  - encryption: 2.12.0
  - federatedfilesharing: 1.14.0
  - files: 1.19.0
  - files_pdfviewer: 2.5.0
  - files_rightclick: 1.3.0
  - files_sharing: 1.16.2
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - files_videoplayer: 1.13.0
  - firstrunwizard: 2.13.0
  - impersonate: 1.11.0
  - logreader: 2.9.0
  - lookup_server_connector: 1.12.0
  - nextcloud_announcements: 1.13.0
  - notifications: 2.12.0
  - oauth2: 1.12.0
  - password_policy: 1.14.0
  - patch_assets: 1.0.0
  - photos: 1.6.0
  - privacy: 1.8.0
  - provisioning_api: 1.14.0
  - recommendations: 1.3.0
  - serverinfo: 1.14.0
  - settings: 1.6.0
  - sharebymail: 1.14.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - systemtags: 1.14.0
  - text: 3.5.1
  - theming: 1.15.0
  - twofactor_backupcodes: 1.13.0
  - updatenotification: 1.14.0
  - user_saml: 5.1.2
  - user_status: 1.4.0
  - viewer: 1.8.0
  - weather_status: 1.4.0
  - workflowengine: 2.6.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional info

I am taking advantage of the custom SAML user secret provided by this code:
https://github.com/nextcloud/server/blob/0a85829138280310633b07762b01c2709027b38d/lib/private/legacy/OC_User.php#L182

This was not implemented until v25, but I modified my v24 files to add support. As such, not only is the master key disabled, but the user's private key is encrypted by a password inaccessible to my NC instance. Admins should not be able to access user files.

**Comment by szaimen** [comment]
Hi, why not simply upgrade to v25 if you know that it solves your problem?

**Comment by summersab** [comment]
I believe you may have misread my report. In v25, files are accessible to admins (which is a bad thing). I had _thought_ that files were inaccessible to users in v24 (in fact, I distinctly remember this being the case), but after setting up a v24 instance, I can still access user files as an admin.

Upon closer inspection of the code, it looks like admins are able to decrypt user private keys even with the master key disabled. This should not be the case.

**Comment by summersab** [comment]
Interesting. If `enable_previews` is set to `true`, I can open image files. If I turn the setting off, an error is displayed (as expected). I will continue to investigate in a few hours and provide an update.

**Comment by summersab** [comment]
My issue is twofold and completely my fault:

- My custom `config.php` file was not correctly parsing boolean `getenv` values leading to `enable_previews` being permanently set to true regardless of values I passed to my Docker image. File previews are not currently encrypted when server-side encryption is enabled
- I forgot that files created by the text app aren't properly being encrypted when the master key is disabled (this is a bug, and I don't think there is an open bug report)

As a result, it looked like I could access image files while using the impersonate app because previews were available, and due to the bug in the text app, I could definitely access files created by the text app.

I'm going to close this bug report, but is there an appetite to have the file previews and text app fixed to properly respect server-side encryption? If so, I'm happy to make pull requests.
