### ISSUE TITLE
Clear theming assets on upgrade when they have changed 

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#3604]
@juliushaertl Is it needed that the theming assets are cleared on an upgrade? Maybe you want to add a  repair steps once you change the assets to use the new theming code for "after the upgrade".

See https://github.com/nextcloud/server/pull/3589/files/2bbf3b18d90301e4c1afc8deb5ef0cf9b91a6ff9#discussion_r102666011

**Comment by juliushaertl** [comment]
I'll have a look, I'm not sure what the current state is, but I guess we can keep existing files.

**Comment by juliushaertl** [comment]
It makes sense to have such a migration, once we have changes inside the theming app, that require it. For now, I'm not aware of any code change that would need a regeneration of the images. I'll prepare a PR anyway so we don't run in any problems with old theming assets later.

**Comment by MorrisJobke** [comment]
> It makes sense to have such a migration, once we have changes inside the theming app, that require it. For now, I'm not aware of any code change that would need a regeneration of the images. I'll prepare a PR anyway so we don't run in any problems with old theming assets later.

If there is no need, we should be fine. Was just a question that was raised 😉

**Comment by juliushaertl** [comment]
@MorrisJobke Ok, let's close this then and just add a migration step if things change.
