### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by salavursa** [nextcloud/server#36064]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I try to get app password for more than 1 user on my server, something weird happens and sometimes passwords do not work properly with associated username.

### Steps to reproduce

there are 3 steps I do to connect new user in my web application:

{serverUrl}//index.php/login/v2 -> I get pollToken&pollUrl and loginUrl
user is logging in with provided loginUrl in 1st step
once user has logged in I get OK response from {serverUrl}/login/v2/poll?token={pollToken} -> I get username and appPwd
with those creds in baseAuth I'm fetching usermetadata like {serverUrl}/ocs/v2.php/cloud/users/{username} -> I get usermetadata
if last response is OK I'm saving metadata and creds to my database
for example I have 3 users: user1, user2, user3

It works just fine if I need to login 1 user like user1, but if I try to login user2 after user1, I get such appPassword, which works with dav requests (e.g. getFolderContent) but doesn't work with OCS (e.g. to getMetadata). Further investigation showed that app password, generated for user2 after user1, works to get user1's metadata!! but its supposed to work with user2 only.

I can reproduce this bug in postman, just try to login user1 and get it's meta, then login with user2 and get its meta. If you get Error, try to get usermetadata of prev username -> it will work.

response I get when login second user, this pwd works to get artemTest02 metadata but not artemTest03
![image](https://user-images.githubusercontent.com/67692229/211540868-a59a5f32-4093-41e0-89e3-d6e329795c7f.png)

Also, when I delete this weird password with DELETE {serverUrl}/ocs/v2.php/core/apppassword (user2’s pwd, witch works to get user1 meta), it also disables previous user’s password and I’m not able to get files for user1 anymore

sometimes I can login 2 users and this is happening with third, randomly. Probably some cache issues or something, please check

### Expected behavior

All appPasswords should be working with corresponding users, but not logged in before (e.g. OCS get metadata / make share). Deleting appPassword should not affect other users were logged in before

### Installation method

Community Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
NC vervion 25
```

**Comment by kesselb** [comment]
Closing in favor of https://github.com/nextcloud/server/issues/34501.
