### ISSUE TITLE
Add Username for Filedrop like Dropbox

### ISSUE THREAD

**Issue by furchtlos76** [nextcloud/server#36098]
Maybe i just did not found out yet, but i think this feature is missing completly, right? The only way to do a filedrop (for example for cusomers to upload big files to me) is anonymous. So i dont know who uploaded a file. Before i used Dropbox and there the filedrop/filerequest asks for a Name of the uploader and adds that to the filename / folder people upload. I really miss this feature.

**Comment by joshtrichards** [comment]
Hi @furchtlos76 - Thanks for your report. I'm closing this, but only because it's also being tracked  in #39534. Feel free to subscribe to that issue and/or give it a :+1:
