### ISSUE TITLE
Cannot "copy" password in clear text right after creating link (if password enabled by default)

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/server#36090]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello and Happy New Year everybody !

In principle, when you create a public (anonymous) share with a password, you must be able to recover the password to transmit it to the recipient(s) of the share. For this, the password is assumed to be readable. This works well if the password is not enabled by default in the sharing settings. On the other hand, if the passwords are activated by default, the password generated just after the initialization of the share is not readable and therefore also cannot be copied.

I see that this problem has been solved in Nextcloud 25 because the sharing dialog has been revised (UX/UI), which is good news.

However, the problem needs to be corrected in Nextcloud 24 which still has a few months of existence ahead of it (especially in the Enterprise version), as it affects the functionality of sharing with passwords when these are activated by default.

Best regards,
Jérôme

![2023-01-11_14-28](https://user-images.githubusercontent.com/33763786/211818888-4737fa7a-ca86-41d2-9f6a-ac56fa782d6b.png)

![2023-01-11_14-30](https://user-images.githubusercontent.com/33763786/211818829-0a0b5929-da81-4f21-8dc4-49d931ecc751.png)

### Steps to reproduce

1. Enable "Always ask for a password" in the sharing admin settings
2. Create a public share for a folder. 
3. Notice that you cannot read and copy de default random password ; you are obliged to disable / enable (regenerate) a password to be able to read and copy it

### Expected behavior

Writing here, I realise that there is a UX/UI limitation in the share settings window in Nextcloud 24, which is certainly the reason why this has been redone in Nextcloud 25.

2 options : 
- Imagine a solution to fix it without compromising security in Nextcloud 24
- Backport Nextcloud 25 sharing settings popup to Nextcloud 24

I would like to know what you all think about it ... 

### Installation method

Community Manual installation with Archive

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nc24.test.mydomain.fr"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "24.0.7.1",
    "overwrite.cli.url": "https:\/\/nc24.test.mydomain.fr",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "log_type": "file",
    "logfile": "\/var\/log\/nextcloud\/nc24.test.mydomain.fr\/nextcloud.log",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "password": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "dbindex": 8,
        "timeout": 0
    },
    "skeletondirectory": "\/data\/nextcloud\/nc24.test.mydomain.fr\/test-skeleton",
    "logtimezone": "Europe\/Paris",
    "updater.release.channel": "stable",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "default_language": "fr",
    "default_phone_region": "FR",
    "defaultapp": "files",
    "trashbin_retention_obligation": "20,40",
    "versions_retention_obligation": "auto,40",
    "check_for_working_wellknown_setup": false,
    "quota_include_external_storage": false,
    "cron_log": true,
    "has_internet_connection": true,
    "updatechecker": true,
    "appstoreenabled": true,
    "filelocking.enabled": true,
    "session_keepalive": true,
    "knowledgebaseenabled": true,
    "allow_user_to_change_display_name": true,
    "enable_previews": true,
    "enable_avatars": true,
    "auth.bruteforce.protection.enabled": true,
    "loglevel": 0,
    "log_rotate_size": 104857600,
    "mail_smtpauth": 1,
    "mail_smtpport": 465,
    "session_lifetime": 86400,
    "remember_login_cookie_lifetime": 1296000,
    "preview_max_filesize_image": 50,
    "activity_expire_days": 120,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "maintenance": false,
    "sharing.enable_mail_link_password_expiration": true,
    "sharing.mail_link_password_expiration_interval": 3600,
    "has_rebuilt_cache": true,
    "app_install_overwrite": [
        "workspace",
        "groupfolders",
        "rocketchat_nextcloud"
    ],
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "share_folder": "\/test2-reception-partages"
}
```

### List of activated Apps

```shell
Enabled:
 - accessibility: 1.10.0
 - activity: 2.16.0
 - apporder: 0.15.0
 - calendar: 3.5.4
 - carnet: 0.24.6
 - circles: 24.0.1
 - cloud_federation_api: 1.7.0
 - collectives: 1.6.3
 - comments: 1.14.0
 - contacts: 4.2.3
 - contactsinteraction: 1.5.0
 - dashboard: 7.4.0
 - dav: 1.22.0
 - deck: 1.7.3
 - external: 4.0.1
 - extract: 1.3.5
 - federatedfilesharing: 1.14.0
 - federation: 1.14.0
 - files: 1.19.0
 - files_accesscontrol: 1.14.1
 - files_lock: 24.0.1
 - files_mindmap: 0.0.27
 - files_pdfviewer: 2.5.0
 - files_rightclick: 1.3.0
 - files_sharing: 1.16.2
 - files_trashbin: 1.14.0
 - files_versions: 1.17.0
 - files_videoplayer: 1.13.0
 - files_zip: 1.1.2
 - firstrunwizard: 2.13.0
 - flow_notifications: 1.4.0
 - forms: 2.5.1
 - groupfolders: 9.2.0
 - guests: 2.3.0
 - impersonate: 1.11.0
 - logreader: 2.9.0
 - lookup_server_connector: 1.12.0
 - mail: 1.15.0
 - memories: 3.9.3
 - nextcloud_announcements: 1.13.0
 - notes: 4.5.1
 - notifications: 2.12.1
 - oauth2: 1.12.0
 - oidc_login: 2.4.0
 - onlyoffice: 7.5.8
 - password_policy: 1.14.0
 - photos: 1.6.0
 - polls: 3.8.3
 - privacy: 1.8.0
 - provisioning_api: 1.14.0
 - quicknotes: 0.8.1
 - recommendations: 1.3.0
 - richdocuments: 6.3.2
 - rocketchat_nextcloud: 1
 - secrets: 1.0.1
 - serverinfo: 1.14.0
 - settings: 1.6.0
 - sharebymail: 1.14.0
 - sharingpath: 0.4.4
 - snappymail: 2.24.3
 - spreed: 14.0.7
 - support: 1.7.0
 - survey_client: 1.12.0
 - systemtags: 1.14.0
 - text: 3.5.1
 - theming: 1.15.0
 - theming_customcss: 1.12.0
 - twofactor_backupcodes: 1.13.0
 - updatenotification: 1.14.0
 - user_ldap: 1.14.1
 - user_migration: 1.1.0
 - user_oidc: 1.2.1
 - user_retention: 1.7.2
 - user_status: 1.4.0
 - viewer: 1.8.0
 - weather_status: 1.4.0
 - welcome: 1.0.6
 - workflow_pdf_converter: 1.9.0
 - workflowengine: 2.6.0
 - workspace: 1.3.1
Disabled:
 - admin_audit
 - duplicatefinder: 0.0.15
 - encryption
 - files_downloadactivity: 1.15.0
 - files_external
 - music: 1.7.0
 - sharerenamer: 3.1.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Can be provided if necessary
```

### Additional info

Can be provided if necessary

**Comment by Jerome-Herbinet** [comment]
> I think this is not a bug but rather how it was desihned. @jancborchardt @nimishavijay any ideas for better solutions to this?

You are right @szaimen, this is not a real bug, but a UI design problem.

**Comment by CrysK** [comment]
I despair of the same "design issue"!

Scenario:
I am the NC Admin, my colleagues should share something. For this (usually*) a password should be used. Nextcloud creates a password, but it is never displayed or provided to the user.

(* Force a password is out of the question, otherwise colleagues will not share files, but will send them in other ways).

Consequence:
* Either the link is shared like this, without a password. Then there is trouble from the customer.
* Or the colleague goes to Share and removes the checkmark for password. (It's easier than creating a password and entering it yourself).
Both is not so desired and in the sense of the Admin.

Possible solution:
* The password is displayed as a pop-up

Data: NC Server 25.0.4

**Comment by nimishavijay** [comment]
That's a great point! If  "Always ask for password" is not enabled, then when you add a password it is shown by default. Similarly, we could simply show the password by default all the time if it's not a security issue. 

However, I think this flow can be greatly improved by adding the password to the copied link. when the "Always ask for password" setting is enabled and someone creates a share link, the information that is copied on the clipboard could contain both the share link and password, similar to sharing a Zoom meeting link. 
```
Share link: https://cloud.nextcloud.com/s/qwertyuiop
Password: qwerty12
```

What do you think?

**Comment by Jerome-Herbinet** [comment]
> That's a great point! If "Always ask for password" is not enabled, then when you add a password it is shown by default. Similarly, we could simply show the password by default all the time if it's not a security issue.
> 
> However, I think this flow can be greatly improved by adding the password to the copied link. when the "Always ask for password" setting is enabled and someone creates a share link, the information that is copied on the clipboard could contain both the share link and password, similar to sharing a Zoom meeting link.
> 
> ```
> Share link: https://cloud.nextcloud.com/s/qwertyuiop
> Password: qwerty12
> ```
> 
> What do you think?

@nimishavijay, may good ideas in your reflection. Also, it would be nice to have a copy to clipboard button next to the password field, whether it is hidden or not. What do you think?

**Comment by CrysK** [comment]
Or maybe simpler and universally possible on all clients (Webapp, iOS, Android, desktop).
* Automatically Copy the password to the "Note for recipients"

**Comment by Jerome-Herbinet** [comment]
> Or maybe simpler and universally possible on all clients (Webapp, iOS, Android, desktop).
> 
>     * Automatically Copy the password to the "Note for recipients"

"Note for recipient" is supposed to be an additional note which is separately sent to him, only if necessary ... and this note is only sent if you click on the arrow button. I'm not sure if it's compatible with the current UI design.

**Comment by David-Rodriguez-cabrera** [comment]
It would be nice to simply implement an eye to show/hide password
