### ISSUE TITLE
[Bug]: The release download nextcloud-25.0.2.tar.bz2 is corrupted

### ISSUE THREAD

**Issue by theCalcaholic** [nextcloud/server#36128]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I just noticed that at least one of the NC 25.0.2 release archives seems to be corrupted. [nextcloud-25.0.2.tar.bz2](https://download.nextcloud.com/server/releases/nextcloud-25.0.2.tar.bz2) can't be extracted and doesn't match the corresponding md5 checksum.

### Steps to reproduce

1. Download the archive at https://download.nextcloud.com/server/releases/nextcloud-25.0.2.tar.bz2
2. Compare its md5 checksum to the one from https://download.nextcloud.com/server/releases/nextcloud-25.0.2.tar.bz2.md5:
    ```sh
    $ md5sum nextcloud-25.0.2.tar.bz2 
    ee46f7bd5d8022251e961299ef051ec3  nextcloud-25.0.2.tar.bz2
    $ cat nextcloud-25.0.2.tar.bz2.md5 
    8a894e28900ef6d1e506f4b73f671258  nextcloud-25.0.2.tar.bz2
    ```
3. Try to extract the archive:
    ```sh
    $ tar xf nextcloud-25.0.2.tar.bz2 

    bzip2: Data integrity error when decompressing.
	    Input file = (stdin), output file = (stdout)

    It is possible that the compressed file(s) have become corrupted.
    You can use the -tvv option to test integrity of such files.

    You can use the `bzip2recover' program to attempt to recover
    data from undamaged sections of corrupted files.

    tar: Unexpected EOF in archive
    tar: Unexpected EOF in archive
    tar: Error is not recoverable: exiting now
    ````

I have reproduced this behavior about 5 times from different environments and networks (since I use this release in the pipelines for nextcloudpi)

### Expected behavior

The release archive matches the provided md5 checksum and can be extracted successfully

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
not applicable
```

**Comment by szaimen** [comment]
cc @blizzz

**Comment by szaimen** [comment]
Hm... strange that this did not became visible ealier. I think many projects are using this archive and it should already have been reported before if it is really corrupt? 🤔

**Comment by theCalcaholic** [comment]
@szaimen It wasn't until ~ 2pm today - back then my pipelines were fine :)

**Comment by szaimen** [comment]
> @szaimen It wasn't until ~ 2pm today - back then my pipelines were fine :)

oh, that is strange. lets see what @blizzz says...

**Comment by Joulinar** [comment]
I tested NC install yesterday without issues. But today evening the archive it become corrupted.

**Comment by MichaIng** [comment]
Same recognised here on three different locations, we use the `latest.tar.bz2`, which is I guess a symlink to `nextcloud-25.0.2.tar.bz2`.

**Comment by Joulinar** [comment]
Guys, issue is fixed. Today morning a test install was working fine using the `latest.tar.bz2` archive.

**Comment by MichaIng** [comment]
Confirmed.
