### ISSUE TITLE
[Bug]: Snappymail doesn't sync cardDAV if you make contact in snappy contacts

### ISSUE THREAD

**Issue by dbmeerts** [nextcloud/server#36135]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I make a contact on my phone or in the contact list of nextcloud everything will be synced. If I make a contact with snappymail and sync it, it will not appear on my phone or in contacts. 

With rainloop it works. 

### Steps to reproduce

1. Go to snappymail 
2. Go to contacts
3. Add a contact
4. Sync the contacts 
5. Go to contacts in Nextcloud
6. And it is not there

### Expected behavior

That the contacts that I make in snappymail it will be synced to the contacts on my phone and contact in Nexcloud.

### Installation method

None

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

SQlite

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - announcementcenter: 6.4.0
  - bookmarks: 12.0.0
  - calendar: 4.2.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.2
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.3
  - documentserver_community: 0.1.13
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - groupfolders: 13.1.0
  - impersonate: 1.11.0
  - keeweb: 0.6.10
  - ldap_contacts_backend: 1.5.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - notify_push: 0.5.0
  - oauth2: 1.13.0
  - onlyoffice: 7.6.8
  - password_policy: 1.15.0
  - photos: 2.0.1
  - previewgenerator: 5.1.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - quicknotes: 0.8.5
  - rainloop: 7.2.6
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - side_menu: 3.5.1
  - snappymail: 2.24.5
  - spreed: 15.0.2
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - timemanager: 0.3.4
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_ldap: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - federation: 1.15.0
  - files_external
  - firstrunwizard: 2.14.0
  - ldap_write_support: 1.7.0
  - ldapcontacts: 2.0.5
  - notes: 4.6.0
  - suspicious_login
  - twofactor_totp
```

**Comment by szaimen** [comment]
Hi, please report the issue to https://github.com/the-djmaze/snappymail/issues. Thanks!
