### ISSUE TITLE
Nextcloud 25.0.3 with PHP 8.2.X

### ISSUE THREAD

**Issue by Niffecs** [nextcloud/server#36148]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi guys
Unfortunately Nextcloud 25.0.2 still does not run under PHP>=8.2.x. Current version is 8.2.1.
Is there anything you can do or you have to use the old PHP 8.1 from November 2021 ?
Greeting @Niffecs

### Steps to reproduce

1. Installing apache
2. Install PHP 
3. Install PHP Module
4. adjust PHP.ini file
5. Install Databse Server
6. Download lastest nextcloud version
7.  restart apache

### Expected behavior

Nextcloud works ?!

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

Other

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
/var/www/nextcloud [root@xxx] [20:14]
> sudo -u www-data php occ config:list system
php occ config:list system
./occ config:list system
This version of Nextcloud is not compatible with PHP>=8.2.<br/>You are currently running 8.2.1.This version of Nextcloud is not compatible with PHP>=8.2.<br/>You are currently running 8.2.1.This version of Nextcloud is not compatible with PHP>=8.2.<br/>You are currently running 8.2.1.#
```

### List of activated Apps

```shell
/var/www/nextcloud [root@xxx] [20:14]
> sudo -u www-data php occ app:list
php occ app:list
./occ app:list
This version of Nextcloud is not compatible with PHP>=8.2.<br/>You are currently running 8.2.1.This version of Nextcloud is not compatible with PHP>=8.2.<br/>You are currently running 8.2.1.This version of Nextcloud is not compatible with PHP>=8.2.<br/>You are currently running 8.2.1.#
```

### Nextcloud Signing status

```shell
Page can't be reached
```

### Nextcloud Logs

```shell
empty
```

### Additional info

empty

**Comment by szaimen** [comment]
Hi, see https://github.com/nextcloud/server/issues/32595

**Comment by Niffecs** [comment]
So you can't assume that Nextcloud supports the current PHP version or will support it in the distant future. Ok thanks.

**Comment by Niffecs** [comment]
If you want, you can delete the issue.

**Comment by meizuflym** [comment]
for nextcloud 24/25 wrote an easy temporary fix that disables php version checking. everything works stable on nextcloud 24.0.10 and 25.0.4 . just replace versioncheck.php file in /nextcloud/lib/ directory. https://github.com/meizuflym/nextcloudversioncheckfix/releases
