### ISSUE TITLE
Regression when renaming incoming shares

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#36153]
There seems to be a regression from https://github.com/nextcloud/server/pull/36047 where renaming shares is not working properly anymore.

Steps to reproduce:
- Share a file from A to B
- Login as B
- Rename the file
- Reload the file list

Expected:
- The new name should be shown

Actual:
- The old name is still shown

cc @icewind1991 @PVince81

**Comment by PVince81** [comment]
I've switched memcache.local to redis to be able to inspect the key

from what I see the cached value still has the old path name

it seems we're missing some invalidation code, however I'm not sure how it could have worked before...

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/server/pull/36159

**Comment by PVince81** [comment]
ok, so the reason it worked before was because the share target changed, so this made it use a different cache key
after each rename
