### ISSUE TITLE
Performance warning on install page not readable

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/server#3615]
### Steps to reproduce
1. do a clean install of nextcloud

### Expected behaviour
text of warning should be readable

### Actual behaviour
text of warning ain't readable

### Server configuration
**Nextcloud version:** latest master (d0980bec73)

### Screenshot
<img width="1285" alt="chromium" src="https://cloud.githubusercontent.com/assets/1250540/23308717/66f9defe-faac-11e6-873f-1c998ba79753.png">

**Comment by georgehrke** [comment]
@nextcloud/designers

**Comment by MorrisJobke** [comment]
cc @skjnldsv

**Comment by skjnldsv** [comment]
😭

**Comment by MorrisJobke** [comment]
> 😭

Let me check that one out.

**Comment by MorrisJobke** [comment]
Works here fine. I guess this is a caching issue. Please refresh hard to check it. Or maybe use a different browser to verify:

![bildschirmfoto 2017-02-24 um 10 59 17](https://cloud.githubusercontent.com/assets/245432/23312733/653760b8-fa80-11e6-99bc-0d394323bd82.png)


If this doesn't help: right click on the box -> inspect element and send us the applied rules.

**Comment by georgehrke** [comment]
hu? oO

Ok, I will double check

**Comment by MorrisJobke** [comment]
I'm sorry. I had an old version. Latest master has it -.-

**Comment by MorrisJobke** [comment]
Ah ... now I know why. I fixed yesterday a broken rule:

https://github.com/nextcloud/server/commit/1d0710ce3f8e6c109013650bb264b90d9589550a#diff-dc80044ed69944b90aacf3c35d781f94R437

Let me remove it completely.

**Comment by MorrisJobke** [comment]
Fix is in #3618
