### ISSUE TITLE
--skip-migration-test gives a Symfony\Component\Console\Exception\RuntimeException

### ISSUE THREAD

**Issue by esprit-libre** [nextcloud/server#3616]
### Steps to reproduce
1. nextcloud 10.0.3 (freshly updated from owncloud 9.1.3)
2. downloading and extracting nextcloud-11.0.1.tar.bz2
3. copying config.php from 10.0.3 to 11.0.1
4. replacing 10.0.3 by 11.0.1 in /var/www/nextcloud
5. sudo -u www-data php /var/www/nextcloud/occ upgrade --skip-migration-test

### Expected behaviour
Upgrade process should run.

### Actual behaviour
Got this log:
>   [Symfony\Component\Console\Exception\RuntimeException]  
>   The "--skip-migration-test" option does not exist.     
> 
> upgrade [--no-app-disable]

### Server configuration
**Operating system**: Debian 7.11
**Web server:** Apache 2.2.22
**Database:** MySQL 14.14 Distrib 5.5.54
**PHP version:** PHP 5.6.30-1~dotdeb+7.1
**Nextcloud version:** 11.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:** oc 9.1.3 -> nc 10.0.3 -> nc 11.0.1
**List of activated apps:** calendar contacts documents logreader
**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "instanceid": "ocnfh33lnmvb",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.92"
        ],
        "datadirectory": "\/var\/www\/data",
        "overwrite.cli.url": "http:\/\/192.168.1.92\/nextcloud",
        "dbtype": "mysql",
        "version": "9.1.3.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "loglevel": 2,
        "htaccess.RewriteBase": "\/nextcloud"
    }
}

```
</details>

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

Does this option stil exists? It worked with 10.0.3 and it is stil documented here https://docs.nextcloud.com/server/11/admin_manual/configuration_server/occ_command.html#command-line-upgrade-label

I try this on a test environment before upgrading large deployement. So I need this option working, I had some problems without it in the past.
If you have an idea. Many thanks.

**Comment by esprit-libre** [comment]
Tested with 11.0.0 and 11.0.2 and result is the same.

**Comment by nickvergessen** [comment]
The `--skip-migration-test` Option was removed, since the feature itself was also removed.

Just run `sudo -u www-data php /var/www/nextcloud/occ upgrade` instead.

**Comment by esprit-libre** [comment]
Hello and thanks for the answer Nick.

Can you give me some explanation or link about why it has been removed? And I need to know if ''occ upgrade'' still realize a test before upgrading or not? In case of large migration, I don't want to spend the migration time twice.

In all case, it should be good to update the documentation as quoted before.

**Comment by nickvergessen** [comment]
As said above there is no longer any migration testing, so no you will never ever accidently update twice.

**Comment by esprit-libre** [comment]
ok thanks.
