### ISSUE TITLE
Setting Favorite API

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/server#3617]
@rullzer @icewind1991 

Info please :

curl https://cloud.xxx.it/remote.php/dav/files/marino.faggiana/EMC.txt -X PROPPATCH -d @favorite.xml -u marino.faggiana:xxxxxxxxxx -k

return 200 OK

curl https://cloud.xxx.it/remote.php/webdav/files/marino.faggiana/EMC.txt -X PROPPATCH -d @favorite.xml -u marino.faggiana:xxxxxxxxxx -k

return Error 400

Why ? webdav <> dav

Thanks

**Comment by icewind1991** [comment]
because they are different endpoints, `webdav` is the old one, we switched to `dav` since we wanted to add more dav capabilities to the endpoint (caldav, carddav, etc) but there is no way to add it to the `webdav` endpoint without breaking backwards compatbility
