### ISSUE TITLE
[Bug]: copying large files

### ISSUE THREAD

**Issue by Daddyoftwins1** [nextcloud/server#36182]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

this is the error im getting

[PHP] Error: Error: exif_read_data(): File not supported at /var/www/nextcloud/lib/private/Metadata/Provider/ExifProvider.php#59 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError()
 1. /var/www/nextcloud/lib/private/Metadata/Provider/ExifProvider.php line 59
    exif_read_data()
 2. /var/www/nextcloud/lib/private/Metadata/MetadataManager.php line 68
    OC\Metadata\Provider\ExifProvider->execute()
 3. /var/www/nextcloud/lib/private/Metadata/FileEventListener.php line 101
    OC\Metadata\MetadataManager->generateMetadata()
 4. /var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php line 87
    OC\Metadata\FileEventListener->handle()
 5. /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 251
    OC\EventDispatcher\ServiceEventListener->__invoke()
 6. /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 73
    Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
 7. /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php line 88
    Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
 8. /var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php line 100
    OC\EventDispatcher\EventDispatcher->dispatch()
 9. /var/www/nextcloud/lib/private/Files/Node/HookConnector.php line 118
    OC\EventDispatcher\EventDispatcher->dispatchTyped()
10. /var/www/nextcloud/lib/private/legacy/OC_Hook.php line 106
    OC\Files\Node\HookConnector->postWrite()
11. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 471
    OC_Hook::emit()
12. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 398
    OCA\DAV\Connector\Sabre\File->emitPostHooks()
13. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 151
    OCA\DAV\Connector\Sabre\File->put()
14. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1098
    OCA\DAV\Connector\Sabre\Directory->createFile()
15. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 504
    Sabre\DAV\Server->createFile()
16. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPut()
17. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit()
18. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod()
19. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
20. /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php line 85
    Sabre\DAV\Server->exec()
21. /var/www/nextcloud/remote.php line 171
    require_once("/var/www/nextcl ... p")

PUT /remote.php/webdav/4TB%20DRIVE/4TB%20DRIVE/SOUTHCOAST/DRIVE%20C/Program%20Files/Dell/Dell%20Data%20Protection/Access/Help/NO/Data/SkinSleek/Stop.gif
from 192.168.1.1 by josh at 2023-01-17T00:04:45+00:00

### Steps to reproduce

1.copy large file using web interface
2.
3.

### Expected behavior

not to get this error

### Installation method

Official All-in-One appliance

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
- activity: 2.17.0
  - admin_audit: 1.15.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.2.1
  - cfg_share_links: 3.0.2
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.2
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - dicomviewer: 1.2.4
  - documentserver_community: 0.1.13
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_accesscontrol: 1.15.1
  - files_automatedtagging: 1.15.0
  - files_external: 1.17.0
  - files_linkeditor: 1.1.13
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - geoblocker: 0.5.7
  - integration_dropbox: 1.0.6
  - integration_google: 1.0.9
  - libresign: 6.2.4
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.2.2
  - maps: 0.2.4
  - metadata: 0.17.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recognize: 3.3.5
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - richdocumentscode: 22.5.802
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - side_menu: 3.5.1
  - snappymail: 2.24.5
  - spreed: 15.0.2
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - encryption: 2.12.0
  - suspicious_login
  - text: 3.6.0
  - twofactor_totp
  - user_ldap
```

**Comment by szaimen** [comment]
Hi, which nc version?

**Comment by Daddyoftwins1** [comment]
25.0.2 nc

**Comment by Daddyoftwins1** [comment]
I am still getting the same error. even after the upgrade to 25.0.3. and I sill can only get about 400GB of the folder then it stops uploading. I also have noticed. that when I drag and drop the folder. I get a pop up saying the page is unresponsive. I can click wait or reload. when I click wait. it starts to upload.

**Comment by szaimen** [comment]
Hi, can you make sure that all values listed here: https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html are correctly adjusted to handle such big files?

**Comment by Daddyoftwins1** [comment]
![Screenshot_20230118-104252_Samsung Internet](https://user-images.githubusercontent.com/118084832/213217495-81e117ae-e1a2-4c9f-82c8-5e9e8af89275.jpg)
I spent a day messing with the configuration and adjusting them I even went higher than what's on the configuration page for the nextcloud documents. This is why I'm here trying to figure out why this system is doing this. Yes I have the meta app. I've asked them and they said this is not the app that's the problem. It's nextcloud server. So I came here and posted. And everything I'm doing is on the web interface/WebDAV I don't like using the desktop app due to it's always trying to download the contents of my server to my laptop.

**Comment by szaimen** [comment]
The timeout seems much too low for such big files so this still seems to be a config issue if you ask me. Probably better to ask at https://help.nextcloud.com since I dont have the time to help you figuring this out.

**Comment by Daddyoftwins1** [comment]
after messing around with the system for a while i have determind that this error only happens when i try to upload .tib or .tibx file

**Comment by Daddyoftwins1** [comment]
is there any way nextcloud could add support for .tib and .tibx file extensions?

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/36545 then
