### ISSUE TITLE
[Bug]: 25.0.3 theming images (logo) are not displayed

### ISSUE THREAD

**Issue by brunob** [nextcloud/server#36215]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading from 25.0.2 to 25.0.3 SVG used in theming module are not displayed anymore. It seems due to the fact they are served with header `content-disposition: attachment; filename="logo"`.

### Steps to reproduce

1. upgrade from 25.0.2 to 25.03
2. display home page are any loged in page using a custom header image
3. default logo is generate HTML `
<img class="logo logo-icon" alt="cloud.infini logo" src="/core/img/logo/logo.svg?v=24">`
4: custom logo generate HTML ``

### Expected behavior

Custom logo should be displayed here https://cloud.infini.fr/ as it was on previous version cf https://web.archive.org/web/20220804154959/https://cloud.infini.fr/login

```
curl -LI https://cloud.infini.fr/apps/theming/image/logo?useSvg=1&v=26
...
content-disposition: attachment; filename="logo"
```

### Installation method

None

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.infini.fr"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.3.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Paris",
        "installed": true,
        "logfile": "\/var\/www\/infini\/nextcloud\/data\/nextcloud.log",
        "loglevel": 3,
        "log_rotate_size": 10485760,
        "theme": "",
        "appstore.experimental.enabled": true,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "lost_password_link": "disabled",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "default_language": "fr",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "charset": "utf8",
        "htaccess.RewriteBase": "\/",
        "overwrite.cli.url": "https:\/\/cloud.infini.fr",
        "overwriteprotocol": "https",
        "hashingMemoryCost": 2048,
        "hashingTimeCost": 1,
        "hashingThreads": 2,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "memcached_servers": [
            [
                "192.168.105.65",
                11211
            ],
            [
                "192.168.106.65",
                11211
            ],
            [
                "192.168.107.65",
                11211
            ]
        ],
        "mysql.utf8mb4": true,
        "default_phone_region": "FR",
        "app_install_overwrite": [
            "tasks",
            "news",
            "calendar",
            "drawio",
            "documentserver_community"
        ]
    }
}
```
```


### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - calendar: 4.2.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.2
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - documentserver_community: 0.1.13
  - drawio: 2.0.2
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - news: 20.0.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - onlyoffice: 7.6.8
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - accessibility
  - admin_audit
  - bruteforcesettings: 2.0.1
  - encryption
  - files_external
  - files_videoplayer
  - survey_client: 1.4.0
  - suspicious_login
  - twofactor_totp
  - user_ldap
```

**Comment by brunob** [comment]
The header seems to be added in `getImage` here https://github.com/nextcloud/server/blob/dc4c3bc8bccfc67a25228f45cee4052d88ead28c/apps/theming/lib/Controller/ThemingController.php#L335 but this code is there since a while.

**Comment by solracsf** [comment]
All instances, even v24 or v23 ones, are served with that header.
Problem is elsewhere.

**Comment by solracsf** [comment]
You should try https://github.com/nextcloud/server/pull/36193
Previously it was a `div`, so image was served as a background image; it is now a `img` (will be reverted, as PR states)

**Comment by brunob** [comment]
'k, seems the bug was already spotted in https://github.com/nextcloud/server/pull/35071#pullrequestreview-1191802849 before merge. Think we can close this issue, thx for the feedback :)
