### ISSUE TITLE
Support for new 'sciencemesh' share type

### ISSUE THREAD

**Issue by michielbdejong** [nextcloud/server#36227]
This replaces https://github.com/nextcloud/server/issues/29215

Instead of trying to make the share types more dynamic, we propose the simpler approach of just adding the 'sciencemesh' share type that is needed for integration with https://sciencemesh.io/ as simply an additional entry in all the places where share types are enumerated. PR coming soon.

**Comment by joshtrichards** [comment]
Closed by #37139 (got missed because it replaced the original PR that was linked to this Issue).
