### ISSUE TITLE
How to change "Nextcloud" to my own customcloud server name??

### ISSUE THREAD

**Issue by Frooks-here** [nextcloud/server#3625]
![next](https://cloud.githubusercontent.com/assets/24497856/23334103/f4cf8342-fbb9-11e6-84e1-9812fe1c26e7.png)

**Comment by MariusBluem** [comment]
You use Theming right? Is this happening to all mails you are getting from your Nextcloud, or only to this mail (seems to be a Mail from the registration app).

**Comment by Frooks-here** [comment]
Brother its happening with every single email. And yeah i am using theming. Can you please guide how to fix this? Thanks.

**Comment by MariusBluem** [comment]
Umm ... @juliushaertl 🤔

**Comment by georgehrke** [comment]
Probably a bug in the registration app.

**Comment by Frooks-here** [comment]
where can I find the registration app? or how to fix it kindly guide me.

**Comment by georgehrke** [comment]
You can find the corresponding bug tracker on our apps store ;)

https://apps.nextcloud.com/apps/registration

**Comment by Frooks-here** [comment]
but all i want to know is how to change Nextcloud to my custom cloud name. Nextcloud ?

**Comment by georgehrke** [comment]
The email you posted was generated by the registration app. I believe this is a bug in the registration app, not in nextcloud. Please report a bug in the bug tracker of the registration app. :)

**Comment by Frooks-here** [comment]
i dont think there is a bug in registration app. its getting the app name from server i guess. do you know how to change app name?

**Comment by georgehrke** [comment]
You can change the name of your Nextcloud inside the admin area in the theming section.
If the registration app doesn't respect these changes, its a bug in the registration app.

**Comment by Frooks-here** [comment]
can i reinstall the registration app?

**Comment by MariusBluem** [comment]
This is only the nextcloud/server component. We are supporting and developing the components you are installing when you initally install Nextcloud. If you would have problems with the Mails, your Nextcloud sends to you - which are sent to you due activities of core-parts of Nextcloud we would be happy to help you over here.

But as @georgehrke said to you already, you are using the registration app, which is a 3rdparty app by an community-developer. We are not supporting this app or its behaviour in this repository.

If you have bugs with it ... like an un-themed mail (Nextcloud -> customcloud) for registration emails, you need to contact the developer of the app directly. He has his repository over here: https://github.com/pellaeon/registration

...I'll close this issue for now - if you have problems with Mails you get independent from the registration app feel free to comment over here again. Thank you for using Nextcloud! 😊
