### ISSUE TITLE
[Bug]: Can't delete folder on SFTP external storage

### ISSUE THREAD

**Issue by CedricGoby** [nextcloud/server#36288]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

It's impossible to **delete** folders when they are stored on sftp external storage, but it's still possible to create, rename, move or copy folders.
Files are not affected and can be deleted without problem.

### Steps to reproduce

1. Setup an SFTP external storage named "MY-PROJECT"
2. Create a folder named "test-folder" in "MY-PROJECT"
3. Delete the folder "test-folder"
4. The folder "test-folder" seems deleted, "MY-PROJECT" is now empty
5. Click on "MY-PROJECT" in the breadcrumb or refresh the page
6. The folder "test-folder" is back in "MY-PROJECT"

### Expected behavior

The folder "test-folder" should have been definitly deleted.

### Installation method

Community Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version : from 24 to 25.0.2 and 25.0.2.3

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "overwriteprotocol": "https",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": true,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "cloud.mydomain.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.3.2",
        "overwrite.cli.url": "https:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - onlyoffice: 7.6.8
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - dashboard: 7.4.0
  - encryption
  - suspicious_login
  - twofactor_totp
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"YysaRqagNaC4PzsdCh56","level":3,"time":"2023-01-21T11:19:00+00:00","remoteAddr":"***REMOVED SENSITIVE VALUE***","user":"king","app":"text","method":"PUT","url":"/apps/text/session/create","message":"","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0","version":"25.0.3.2","exception":{"Exception":"OCP\\Files\\NotFoundException","Message":"","Code":0,"Trace":[{"file":"/var/www/html/apps/text/lib/Service/ApiService.php","line":96,"function":"getFileById","class":"OCA\\Text\\Service\\DocumentService","type":"->","args":[1300]},{"file":"/var/www/html/apps/text/lib/Controller/SessionController.php","line":58,"function":"create","class":"OCA\\Text\\Service\\ApiService","type":"->","args":[1300,null,null,null,false]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"create","class":"OCA\\Text\\Controller\\SessionController","type":"->","args":[1300,null,false]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Text\\Controller\\SessionController"},"create"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Text\\Controller\\SessionController"},"create"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Text\\Controller\\SessionController","create",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},["text.Session.create"]]},{"file":"/var/www/html/lib/base.php","line":1047,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/text/session/create"]},{"file":"/var/www/html/index.php","line":36,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/apps/text/lib/Service/DocumentService.php","Line":413,"message":"","exception":{},"CustomMessage":""}}
```

### Additional info

I'll try to add useful informations to identify the problem.

I have several instances of Nextcloud hosted on different servers using docker (with traefik and portainer, see here : [https://gitlab.com/CedricGoby/traefik-portainer-compose](https://gitlab.com/CedricGoby/traefik-portainer-compose) ).
All these instances have been upgraded to 25.0.2 (and two of them have been upgraded to 25.0.3).

For all theses instances I host SFTP storages on a synology NAS (with the operating system DSM 7.1.1-42962 Update 1).

Here are the steps I followed to try to understand.

The administrator create an empty SFTP external storage named "MY-PROJECT" and make it available for user "king".
The external storage is physically located in the NAS like mentionned above.
![sftp-external-storage](https://user-images.githubusercontent.com/17612749/213910537-6e15191d-07f5-413c-b9f4-f73d97b0b3a6.png)

![sftp-external-storage-options](https://user-images.githubusercontent.com/17612749/213910714-b6e8a0c9-8239-44e3-92dc-737f6539eb7b.png)

The user "king" access to SFTP storage  "MY-PROJECT" from is Home.
The folder "MY-PROJECT" is empty as expected.
![king-home-empty](https://user-images.githubusercontent.com/17612749/213911075-8a838ba3-0e8a-41df-98bc-43caf1097d3a.png)

The User "king" create a folder named "test-directory".
![king-create-directory](https://user-images.githubusercontent.com/17612749/213911168-240e713a-fee4-44dd-9098-34ddf09fea35.png)
![king-folder-created](https://user-images.githubusercontent.com/17612749/213911362-2e8fa107-3a54-4f21-9c8c-bb773e7d3f29.png)

Below are the Nextcloud logs of the "test-directory" folder creation (this is a WebDAV command)
`***REMOVED SENSITIVE VALUE*** - - [21/Jan/2023:17:33:18 +0000] "MKCOL /remote.php/dav/files/king/MY-PROJECT/test-directory HTTP/1.1" 201 626 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"`

The logs from the NAS confirm the SFTP connexion from Nextcloud and the creation of the "test-directory" folder in the NAS filesystem
![nas-create-folder-file_transfert-log](https://user-images.githubusercontent.com/17612749/213911954-04541c31-32f1-41ef-b4e6-e7836d87bc9a.png)

We can see this "test-directory" folder using the file browser of the NAS
![filestation-directory-created](https://user-images.githubusercontent.com/17612749/213912073-fcb16d8f-5aeb-4cc3-880c-f831dfa1dac0.png)

Back to Nextcloud user "king" delete the "test-directory" folder
![king-delete-directory](https://user-images.githubusercontent.com/17612749/213912207-d9d06038-b3f4-4eef-baca-08f433c7e60d.png)

It seems that the "test-directory" folder has been succesfully deleted with no error message...
![king-home-empty](https://user-images.githubusercontent.com/17612749/213911075-8a838ba3-0e8a-41df-98bc-43caf1097d3a.png)

Below are the Nextcloud logs for the deletion of the "test-directory" folder. This is a WebDAV command but this command is intended for deleting files, not folders [(https://linux.die.net/man/1/cadaver)](https://linux.die.net/man/1/cadaver), we'll see that later.
`***REMOVED SENSITIVE VALUE*** - - [21/Jan/2023:17:42:34 +0000] "DELETE /remote.php/dav/files/king/MY-PROJECT/test-directory HTTP/1.1" 204 537 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0"`

**BUT** if you click on "MY-PROJECT" in the breadcrumb or refresh the page the "test-directory" folder is back !
![king-folder-created](https://user-images.githubusercontent.com/17612749/213911362-2e8fa107-3a54-4f21-9c8c-bb773e7d3f29.png)

In fact, the "test-directory" is back in Netxcloud because it has not been deleted on the NAS, it's still there...
![filestation-directory-created](https://user-images.githubusercontent.com/17612749/213912073-fcb16d8f-5aeb-4cc3-880c-f831dfa1dac0.png)

The logs from the NAS show the deletion attempt.
**There is maybe a clue here** as the log show Nextcloud removing a "test-directory" **FILE** not a "test-directory" **FOLDER**.
![nas-remove-file_transfert-log](https://user-images.githubusercontent.com/17612749/213915548-4b04e91d-b8fd-4adf-aa3c-5fbb76960f67.png)

Let's connect directly to the SFTP storage on the NAS using Filezilla with the same user provided for connecting SFTP external storage in Nextcloud.
![filezilla-home-with-folder](https://user-images.githubusercontent.com/17612749/213916101-099a2a35-eb0e-4d03-bf6e-2a8bb3387882.png)

Let's delete the "test-directory" folder in the NAS using Filezilla.
It seems to work, the "test-directory" folder has been deleted.
![filezilla-home-without-folder](https://user-images.githubusercontent.com/17612749/213916238-514073ca-4498-4d5e-86ce-044e682eaa30.png)

The "test-directory" folder is no longer visible in Nextcloud too.
![king-home-empty](https://user-images.githubusercontent.com/17612749/213911075-8a838ba3-0e8a-41df-98bc-43caf1097d3a.png)

Let's check if the "test-directory" folder has been deleted in the NAS using the file brower of the NAS.
Yes, the "test-directory" folder has been deleted in the NAS.
![filestation-directory-removed](https://user-images.githubusercontent.com/17612749/213916590-061226a3-d0a4-4660-9f6a-bdd1845c69a2.png)

So let's have a look to the logs from the NAS.
![nas-remove-directory-FILEZILLA-file_transfert-log](https://user-images.githubusercontent.com/17612749/213917351-ed3de39e-c071-41c9-8f08-4f75eec7767c.png)

The first line is the successful deletion of the "test-directory" folder using SFTP with Filezilla (Event : Delete Folder | Folder).
The second line is a prevous unsuccessful attempt to delete the "test-directory" folder using Nextcloud SFTP external storage (Event : Delete | File).
Both methods (Filezilla and Nextcloud external storage) use the same host, username and password.

So it seems that Nextcloud send a command to delete a FILE instead of sending a command to delete a FOLDER.

It seems that Nextcloud use a WebDAV "**DELETE**" command (wich delete a file, not a folder as far as I know)
`***REMOVED SENSITIVE VALUE*** - - [21/Jan/2023:17:42:34 +0000] "DELETE /remote.php/dav/files/king/MY-PROJECT/test-directory "`
instead of using a  WebDAV "**RMCOL**" command like this (wich delete a folder)
`"RMCOL /remote.php/dav/files/king/MY-PROJECT/test-directory "`

That could be the reason why we can't remove folders with Nextcloud SFTP external storage and why we succeed using SFTP client like Filezilla.

Can anyone help me with this issue please ?

Have a nice day.

**Comment by CedricGoby** [comment]
Sorry for this post but I think the issue is not a Nextcloud bug.

I made two fresh install for testing purpose (23.0.12 and 24.0.9) and the problem is the same as described in the post.

I never had this problem with previous versions of Nextcloud 25, so I guess this is related to the Synology NAS where SFTP storage are located.

But I still need help, if someone has the same issue and the solution...

**Comment by CedricGoby** [comment]
Hello,

Synology Support resolved the issue.

For your information, it is the fact of activating the recycle bin on the shared folders of the NAS that creates this problem.
Without recycle bin no problem to delete folders.

Here is an excerpt from the logs from the NAS :

`2023-01-23T17:24:59+01:00 Arcad_Syn internal-sftp[26465]: recycle_unlink.c:349 Path(share=/volume1/TEST, rpath=projet-test/folder-test) is not a file.`
`2023-01-23T17:24:59+01:00 Arcad_Syn internal-sftp[26465]: sftp-server.c:1657 SYNORecycleUnlinkFileWithSharePath failed. share_path:[/volume1/TEST] rpath:[projet-test/folder-test] [0x0D00 recycle_unlink.c:350]`
`2023-01-23T17:24:59+01:00 Arcad_Syn internal-sftp[26465]: recycle_unlink.c:349 Path(share=/volume1/TEST, rpath=projet-test/folder-test) is not a file.`
`2023-01-23T17:24:59+01:00 Arcad_Syn internal-sftp[26465]: sftp-server.c:1657 SYNORecycleUnlinkFileWithSharePath failed. share_path:[/volume1/TEST] rpath:[projet-test/folder-test] [0x0D00 recycle_unlink.c:350]`
`2023-01-23T17:24:59+01:00 Arcad_Syn internal-sftp[26465]: recycle_unlink.c:349 Path(share=/volume1/TEST, rpath=projet-test/folder-test) is not a file.`
`2023-01-23T17:24:59+01:00 Arcad_Syn internal-sftp[26465]: sftp-server.c:1657 SYNORecycleUnlinkFileWithSharePath failed. share_path:[/volume1/TEST] rpath:[projet-test/folder-test] [0x0D00 recycle_unlink.c:350]`

I asked Synology support if this is a bug or normal behavior, to be continued...

Have a nice day.

**Comment by schnillerman** [comment]
I think this "bug" might apply to moving files as well ... I use MiXplorer on my Android, and moving or deleting files/folders via SFTP doesn't work, only copying.
