### ISSUE TITLE
[Bug]: Randomly no response until once a minute

### ISSUE THREAD

**Issue by ristein** [nextcloud/server#36285]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

My nextcloud server randomly hangs and does not respond to any web requests for up to one minute.
This mostly happens one more complex tasks like starting an upload, accessing versions of a file, or accessing the settings/admin/overview page.
I recently found I can reproduce this by scrolling through the activity app.
When reaching the end with refreshing circle my nextcloud would halt and not respond to any web request until X seconds after each minute. Where X seems to be a random number that stays constant until refreshing the page in browser. Values I observed for X are 5, 17, 19, 22, 55. So if X is 5 and I reach the end at 20sec after the minute I would have to wait 45sec, if I reach it at 50sec after I would only have to wait 15sec.
If I don't scroll for some time (like 3 minutes) the refreshing circle might disappear instantly about five times without this bug.
If I have recently scrolled through activity I would have to reach the point where I was last time for the bug to appear.

### Steps to reproduce

1. open activity app in browser
2. scroll down about 100 list items max if not been there recently

### Expected behavior

nextcloud responding my web requests

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "127.0.0.1",
            "cloud.XXXXX.XX",
            "internal.IP.XX.XXX"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.3.2",
        "overwrite.cli.url": "https:\/\/cloud.XXXXXX.XX",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "allow_local_remote_servers": true,
        "maintenance": false,
        "default_phone_region": "XX",
        "theme": "",
        "loglevel": 0,
        "preview_max_x": 4000,
        "preview_max_y": 4000,
        "jpeg_quality": 80,
        "trashbin_retention_obligation": "31, 32",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "cookbook",
            "jitsi",
            "user_usage_report"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - approval: 1.0.12
  - bruteforcesettings: 2.5.0
  - calendar: 4.2.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.0.2
  - contactsinteraction: 1.6.0
  - cookbook: 0.10.1
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.3
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_accesscontrol: 1.15.1
  - files_automatedtagging: 1.15.0
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - forms: 3.0.3
  - jitsi: 0.16.2
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - onlyoffice: 7.6.8
  - password_policy: 1.15.0
  - photos: 2.0.1
  - polls: 4.0.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - quota_warning: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.3
  - support: 1.8.0
  - survey_client: 1.13.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_migration: 2.0.1
  - user_status: 1.5.0
  - user_usage_report: 1.9.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - welcome: 1.0.6
  - workflowengine: 2.7.0
Disabled:
  - encryption
  - group_default_quota: 0.1.5
  - ransomware_protection: 1.14.0
  - socialsharing_email: 2.5.0
  - twofactor_totp
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
see file
```

### Additional info

using Firefox.
removed some sensitive data from logs.
Github shows me unicorn with my 71k lines of logs, so adding file here.
Last log lines show me scrolling through activity with X=15, so you will want to look at T20:{16-22}:{14-17}
[nextcloud-sent.log](https://github.com/nextcloud/server/files/10473135/nextcloud-sent.log)

**Comment by ristein** [comment]
This might have something to do with preview generation:
I just scrolled through activity and though files app and while waiting for it to load I opened Apache's server status page each time and six lines of "w" aka "sending reply" there in lines where the request contains something like "GET /core/preview?forceIcon=0&a=0&x=250&y=250&fileId=316279&c=9".
But there seems to be one line with a request like this each time "GET /apps/onlyoffice/download?doc=eyJ0eXAiOiJKV1QiLCJhbGciOiJIU".
[files.txt](https://github.com/nextcloud/server/files/10808224/files.txt)
[activity.txt](https://github.com/nextcloud/server/files/10808225/activity.txt)

**Comment by bjo81** [comment]
Update: Rebooting the system helped, but the issue reoccured and it's unclear what triggers it.

**Comment by dedebenui** [comment]
I also have this issue. I get no error or anything, but when I open the ios app, i cannot download anything and the server gets stuck (cannot access in any way from any machine) for a few minutes, after which everything works fine. This happens very often and renders the whole server kind of useless...

it does seem related to previews, since i guess the ios app is triggering a lot of previews, while, say, the desktop client doesnt need them and thus doesn't trigger the problem. 

While this is not fixed, is there a way to disable previews altogether?

**Comment by dedebenui** [comment]
I realized that specifically PDF previews were causing this issue and while reading [the documentation](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#enabledpreviewproviders) that PDF previews are disabled by default. Since I never enabled them manually, that meant that something else was generating previews. In fact, there is a setting in the OnlyOffice admin parameters to let OnlyOffice generate previews. This seems to be on by default and it generates previews for pdfs. It also seems to be bugged on my machine, which causes the issue discussed here, but since I don't need pdf previews, I just turned it off and let Nextcloud generate previews for images. This solved this issue for me.

**Comment by ristein** [comment]
I have not seen this issue in last few weeks and can not reproduce it anymore, even though I did not change the setting to off mentioned by dedebenui

**Comment by szaimen** [comment]
This might have been fixed with https://github.com/nextcloud/server/pull/41263 and https://github.com/nextcloud/server/pull/41289 in 27.1.4

**Comment by ristein** [comment]
now I could reproduce again by opening folders in trashbin. I disabled onlyoffice preview generation and that hang is gone

**Comment by szaimen** [comment]
Sounds like a bug in the onlyoffice app then?

**Comment by ristein** [comment]
yes, I will file a bugreport there

**Comment by Andreaux** [comment]
I am having the same issue and I don't have Onlyoffice installed. I'm working on a large number of photos in Memories/People and everything regularly hangs for half a minute to one minute, then resumes.

**Comment by joshtrichards** [comment]
Closing since OP's matter was addressed.

@Andreaux Seems your situation isn't the same. I suggest checking your logs (including PHP fpm logs if applicable), troubleshooting at the help forum (https://help.nextcloud.com), and/or creating a dedicated issue with your details if you believe it to be a bug and not an environmental matter.
