### ISSUE TITLE
[Bug]: UI doesn't account for individual external storages being disabled

### ISSUE THREAD

**Issue by nazar-pc** [nextcloud/server#36282]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

It is possible for External Storage UI to say it is enabled, but for it to not be enabled

### Steps to reproduce

1. Enable external storage on `/settings/admin/externalstorages`
2. Disable individual storage options one by one
3. Disable external storage
4. Refresh the page
5. Enable external storage, see all storage options are enabled too
6. Refresh the page

### Expected behavior

External storage remains enabled.

However in practice it is not.

### Installation method

Community Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.mokrynskyi.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.mokrynskyi.com",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "25.0.3.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 1,
        "updater.release.channel": "stable",
        "mysql.utf8mb4": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "default_phone_region": "UA",
        "htaccess.RewriteBase": "\/"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - calendar: 4.2.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - contacts: 5.0.2
  - contactsinteraction: 1.6.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - spreed: 15.0.3
  - support: 1.8.0
  - survey_client: 1.13.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
There were no logs printed in the process
```

### Additional info

Workaround is to "disable" and "re-enable" one of the storage options before doing last page refresh

**Comment by szaimen** [comment]
Hi, can you maybe share a screenshare of the problem? I find it difficult to reproduce what you are experiencing.

**Comment by nazar-pc** [comment]
If you follow the steps one by one it should be trivial to reproduce. I'm actively using external storage right now, so I'd prefer to not turn it on/off breaking clients just to record a video of steps I have already described.

**Comment by szaimen** [comment]
okay then let me ask more in detail:

> * Disable individual storage options one by one

Do you mean the option to disable personal external storages or do you mean deleting the admin configured external storages? (there is no disabling afaik)

> * Disable external storage

Do you mean delete the by the admin configured external storages? (there is not disabling only deleting afaik)

> * Refresh the page

Which page are you refreshing? This one? `/settings/admin/externalstorages`

> * Enable external storage, see all storage options are enabled too

How are you enabling external storage? (there is no option t disable and enable external storages afaik) Do you mean the app in the apps management?

> * Refresh the page

Which page?

**Comment by nazar-pc** [comment]
> Do you mean the option to disable personal external storages or do you mean deleting the admin configured external storages? (there is no disabling afaik)

When you click enable there will be a list of different backends (WebDAV, SFTP, S3, etc.). Just disable those one by one by clicking on them/

> Do you mean delete the by the admin configured external storages? (there is not disabling only deleting afaik)

No, just click the checkbox on the page I mentioned again.

> Which page are you refreshing? This one? /settings/admin/externalstorages

Yes, I didn't mention any steps that involve leaving that page.

> How are you enabling external storage? (there is no option t disable and enable external storages afaik) Do you mean the app in the apps management?

You're making it way more complicated than it is, just click "Allow users to mount external storage" (or whatever English version of it is).

> Which page?

Same page all the time, just click F5

**Comment by szaimen** [comment]
Thanks for your answers! I think you are misunderstanding what this setting does. It limits the options for users that are not admins in `https://yourdomain.com/settings/user/externalstorages` and not for admins in ```https://yourdomain.com/settings/admin/externalstorages`.

**Comment by nazar-pc** [comment]
I understand that well, my concern is not about the feature, it is UI bug. When you re-enable it in step 5 UI shows that all backend options are enabled and settings are saved, but it is a lie. Once you refresh the page you'll see that none of them are enabled, in fact even the checkbox you have just checked is unchecked again.

**Comment by szaimen** [comment]
Sorry, cannot reproduce:

**Comment by nazar-pc** [comment]
Hm, I'm on Nextcloud Hub 3 (25.0.3) if it makes a difference.

**Comment by szaimen** [comment]
I've tested with 25.0.3 so not sure

**Comment by nazar-pc** [comment]
Okay, I'll re-test and record screencast later

**Comment by nazar-pc** [comment]
Can't reproduce, I just have constant caching issues of some kind everywhere since upgrade to 25.0.3 from 25.0.2, I think this is just another manifestation of that.
