### ISSUE TITLE
Add Snap Information

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#363]
Can documentation be created on how to properly create a snap for Nextcloud? Owncloud has it but I am not sure how applicable it is to Nextcloud.

**Comment by MorrisJobke** [comment]
> Can documentation be created on how to properly create a snap for Nextcloud?

What is a snap?

**Comment by c0fe** [comment]
https://insights.ubuntu.com/2016/06/14/universal-snap-packages-launch-on-multiple-linux-distros/

**Comment by juliushaertl** [comment]
By now there shouldn't be much difference to the Owncloud snap.

There is already a repo for a nextcloud-snap
https://github.com/kyrofa/nextcloud-snap

**Comment by MorrisJobke** [comment]
officially we don't offer any snap package. And as already said: most of the stuff that applies to the ownCloud one also applies to that one.
