### ISSUE TITLE
[Bug]: Missing translation, when install an app

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/server#36315]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Dialog is not translated 
![grafik](https://user-images.githubusercontent.com/34692335/214106655-51ef15f8-e27f-479e-bd16-aacbf82b5ed5.png)

### Steps to reproduce

1. Try to download an activate an app
2. click on "Herunterladen und aktivieren"-button
3. See english text in dialog box

### Expected behavior

all text is translated

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
n/a
```

### Additional info

Nextcloud Hub 3 (25.0.3)

**Comment by joshtrichards** [comment]
At this point all supported versions of Server are using different code for this area via #40643.

This problem may be resolved on >=28.

If you're still seeing it, we'll need to move this to the appropriate repo for the underlying library.

Let us know.

**Comment by joshtrichards** [comment]
Confirmed fixed.
