### ISSUE TITLE
[Bug]: Email Server doesn't work

### ISSUE THREAD

**Issue by TechXero** [nextcloud/server#36330]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I am new to NextCloud, I just got a Ubuntu Linode and installed Nextcloud via snap and added it to my own subdomain.. All went well except I cannot get Email server to work with any email service I use, be it Outlook, gmail, Vivaldi webmail etc.. And yes I have checked that I can access them from outside apps.. I been working on this all day reading various reports and solutions nothing works.. All I get is this error with every single one...

![error](https://i.imgur.com/KvIvXIy.png)

Hope you can help...

### Steps to reproduce

1. Install NextCloud on Ubuntu via Snap
2. Login and go to email server
3. Try setting it up = Error

### Expected behavior

Well, for it to work lol

### Installation method

Community SNAP package

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

Other

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
None of the commands are working
```

### List of activated Apps

```shell
None of the commands are working
```

### Nextcloud Signing status

```shell
No errors found
```

### Nextcloud Logs

```shell
I cannot find them
```

**Comment by szaimen** [comment]
Hi, please report thid to https://github.com/nextcloud-snap/nextcloud-snap. Thanks!
