### ISSUE TITLE
[Bug]: Sharing folders with same name will conflict

### ISSUE THREAD

**Issue by absort0** [nextcloud/server#36354]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Sharing two folders that have the same name with another user leads to this user being unable to access the first folder's content as the second folder will "overwrite" the other one because of the name conflict. The user will see only one of the folders in their home folder which will have the contents of the second folder shared. Trying to access the folder using the internal link will return 'File could not be found'. Renaming one of the original folders and sharing it again with the user will solve the issue, confirming that this is a name conflict issue.

### Steps to reproduce

1. Create a top level folder named *Test*
2. Add a text file named *Bar*
2. Create another top level folder named *Foo* 
2. Under *Foo*, create another folder named *Test*
2. Inside *Foo->Test*, add a text file named *Baz* 
2. Share top level folder *Test* with user B
2. Now also share the *Test*  folder under *Foo* with user B 
3. When user B tries to access first folder with internal link they will receive a **'File could not be found'** response
4. If user B access the *Test* folder that now resides in their home directory, they will see *Baz* inside of it

### Expected behavior

Both folders and their contents are accessible to user B.
At least user A should receive an error when trying to share a folder which conflicts with a folder user B already has, but this implies exposing folders owned/shared with user B.
I'm not sure how to solve this, perhaps the folder should be renamed automatically once its shared or if they could retain their original names and the conflict be solved in a lower level.

### Installation method

Community VM appliance

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "integrity.check.disabled": true,
        "allow_local_remote_servers": true,
        "sharing.enable_share_mail": true,
        "dbtype": "mysql",
        "version": "25.0.1.1",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": true,
        "maintenance": false,
        "theme": "",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "default_phone_region": "GB",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "mindmaps",
            "audioplayer",
            "sharerenamer",
            "activitylog",
            "mindmap_app",
            "onlyoffice",
            "files_texteditor"
        ],
        "mysql.utf8mb4": true,
        "activity_expire_days": 30,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        }
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - appointments: 1.14.7
  - calendar: 4.1.1
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - dav: 1.24.0
  - deck: 1.8.2
  - drawio: 1.0.5
  - external: 5.0.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_mindmap: 0.0.27
  - files_sharing: 1.17.0
  - files_texteditor: 2.15.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - forms: 3.0.1
  - keeweb: 0.6.10
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - oauth2: 1.13.0
  - onlyoffice: 7.6.8
  - polls: 4.0.0
  - provisioning_api: 1.15.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - systemtags: 1.15.0
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - timemanager: 0.3.4
  - twofactor_backupcodes: 1.14.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - bruteforcesettings
  - circles: 0.16.9
  - contactsinteraction: 1.1.0
  - dashboard: 6.0.0
  - encryption
  - files_external: 1.16.1
  - files_markdown: 2.3.6
  - files_pdfviewer: 2.4.0
  - files_readmemd: 1.2.2
  - files_rightclick: 0.17.0
  - firstrunwizard: 2.9.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - recommendations: 0.8.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - suspicious_login
  - twofactor_totp
  - updatenotification: 1.10.0
  - user_ldap
  - user_status: 1.0.1
  - weather_status: 1.0.0
```

**Comment by szaimen** [comment]
Hi, can you upgrade to 25.0.3 and check if that resolves your issue?

**Comment by absort0** [comment]
Hi @szaimen even `25.0.2` does!
After you mentioned I decided to test in another instance running `25.0.2` and I couldn't replicate the issue.
Thanks for the quick response.
