### ISSUE TITLE
[Bug]: Fullscreen video playback on iOS browsers

### ISSUE THREAD

**Issue by jdanna** [nextcloud/server#36366]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When viewing an MP4 video from Safari in iOS - fullscreen playback results in non-fullscreen behavior. In portrait orientation, fullscreen moves the windowed video up in the browser, but retains the header and footer. When switched to landscape, the video is just a thin black box, and again the header and footer is retained.

Behavior is the same both logged in to NextCloud and via a public share link.

### Steps to reproduce

1. Upload an MP4 video
2. Create a public share link
3. Access the link from Safari on iOS
4. Click fullscreen, and then rotate to landscape

### Expected behavior

The video should expand to fullscreen completely, without the header/footer from nextcloud and with the video correctly centered and scaled on the device

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.116",
            "cloud.joeydanna.tv"
        ],
        "default_phone_region": "1",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.3.2",
        "overwrite.cli.url": "http:\/\/192.168.1.116",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "simpleSignUpLink.shown": false,
        "maintenance": false,
        "app_install_overwrite": [
            "gluusso",
            "social",
            "flowupload",
            "spreed",
            "deckimportfromtrello",
            "files_3d",
            "socialsharing_email",
            "apporder"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "updater.release.channel": "beta",
        "theme": "",
        "loglevel": 2
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - bruteforcesettings: 2.5.0
  - camerarawpreviews: 0.8.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dav: 1.24.0
  - deck: 1.8.3
  - federatedfilesharing: 1.15.0
  - files: 1.20.1
  - files_archive: 1.1.2
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - imageconverter: 1.3.4
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - metadata: 0.17.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - photos: 2.0.1
  - previewgenerator: 5.1.1
  - provisioning_api: 1.15.0
  - related_resources: 1.0.3
  - richdocuments: 7.1.0
  - richdocumentscode: 22.5.802
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - sociallogin: 5.3.0
  - spreed: 15.0.3
  - tasks: 0.14.5
  - theming: 2.0.1
  - theming_customcss: 1.12.0
  - twofactor_backupcodes: 1.14.0
  - unroundedcorners: 1.0.8
  - updatenotification: 1.15.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit: 1.15.0
  - apporder: 0.15.0
  - calendar: 4.2.1
  - circles: 24.0.1
  - contacts: 5.0.2
  - dashboard: 7.5.0
  - encryption
  - federation: 1.14.0
  - files_trashbin: 1.14.0
  - files_versions: 1.17.0
  - firstrunwizard: 2.13.0
  - mail: 2.2.2
  - nextcloud_announcements: 1.13.0
  - password_policy: 1.14.0
  - privacy: 1.8.0
  - recommendations: 1.3.0
  - support: 1.7.0
  - survey_client: 1.12.0
  - suspicious_login
  - systemtags: 1.14.0
  - text: 3.5.1
  - twofactor_totp
  - user_ldap
  - user_status: 1.4.0
  - weather_status: 1.4.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional info

Screenshots posted here:
https://imgur.com/a/zS1Co3U

**Comment by skjnldsv** [comment]
Fixed in https://github.com/nextcloud/viewer
