### ISSUE TITLE
[Bug]: Star component in sidebar behaves erratically when using the photo viewer

### ISSUE THREAD

**Issue by jsmtux** [nextcloud/server#36379]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When in the Files or in the Gallery app, which use the same sidebar component, clicking the star icon in the sidebar to add a file/photo to the favorites and then changing to a different item breaks the "starred" information for the following files.

When the bug is present, the next image will also show as starred even if it is not. All the following shown files will be seen as "starred" even if they are not. By closing the sidebar or going over a "really starred" file, the issue will momentarily disappear.

This is not only an inconvenience because the wrong things are shown, but also because it makes it confusing to actually set another file as favorite.

### Steps to reproduce

1. Navigate to a folder with several images where none is "starred"
2. Open an image so that it shows over the rest of the UI
3. Reveal the sidebar
4. Click on the star for the current image
5. Navigate to the next image by using the arrow positioned at the right of the image
6. Observer the "starred" status of the new image

### Expected behavior

After starring a file and then moving to another, if the following one is not part of the favorites, the star should go back to being grey.

### Installation method

Official Docker image

### Operating system

Other

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - lookup_server_connector: 1.13.0
  - oauth2: 1.13.0
  - photos: 1.7.0
  - provisioning_api: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - systemtags: 1.15.0
  - theming: 2.0.0
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: true
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - testing
  - user_ldap
```

**Comment by joshtrichards** [comment]
Occurred in <=v27. Confirmed no longer the case in >=28.
