### ISSUE TITLE
TypeError: Argument 1 passed to OC\SubAdmin::createSubAdmin() 

### ISSUE THREAD

**Issue by wallenium** [nextcloud/server#3638]
### Steps to reproduce
Not totally sure. Think it is because of the admin Password to be entered again before changing a user Group. I canceled it by error, afterwards this issue was logged in the error log. If it is caused by that, there is definitly an issue with the permission. If you cancel/decline, the Dropdown is not shown, but a strange behaviour at least on Internet Explorer is visible - there is a one-line-field to be scrolled through. seems that the HTML is not properly blocked.

### Expected behaviour
No error, i think ;)

### Server configuration
**Web server:** Apache, not sure which Version. Shared Hosting.

**Database:** MariaDB, not sure which version

**PHP version:** 7.0.16

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated NC11.0.1 to 11.0.2 RC2 to final

#### Web server error log
<details>
<summary>Web server error log</summary>
TypeError: Argument 1 passed to OC\SubAdmin::createSubAdmin() must implement interface OCP\IUser, null given, called in /home/www/nextcloud/settings/ajax/togglesubadmins.php on line 500./home/www/nextcloud/settings/ajax/togglesubadmins.php - line 50:  OC\SubAdmin->createSubAdmin(NULL, Object(OC\Group\Group))
1./home/www/nextcloud/lib/private/Route/Route.php - line 155):  runtime-created function(1) require_once('/home/www/nextc...')
2.[internal function] __lambda_func()
3./home/www/nextcloud/lib/private/Route/Router.php - line 299:  call_user_func('\x00lambda_16430', Array)
4./home/www/nextcloud/lib/base.php - line 1010:  OC\Route\Router->match('/settings/ajax/...')
5./home/www/nextcloud/index.php - line 40:  OC handleRequest()
6.{main}

</details>

**Comment by nickvergessen** [comment]
Yes, it seems to break the select box, but I can't see any strange behaviour

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
