### ISSUE TITLE
Change of the server name forces user to insert login data in Thunderbird/Lightning again

### ISSUE THREAD

**Issue by fuzsin** [nextcloud/server#3641]
### Steps to reproduce
1. Login into Nextcloud admin GUI
2. Change the name field text to whatever 
![admin_mycloud](https://cloud.githubusercontent.com/assets/25567074/23371692/3d9c11d4-fd19-11e6-9969-de7250cc6a91.png)

3. Logout from Nextcloud
3. Restart the Thunderbird Client

### Expected behaviour
The calender must be synchronized as usual

### Actual behaviour
The user is forced to insert his login data again
![authentifizierung-erforderlich](https://cloud.githubusercontent.com/assets/25567074/23371669/296f69cc-fd19-11e6-80f7-fcbc6d356a2a.png)

### Server configuration

**Database:** mysql 5.6.33

**PHP version:** 5.6.17

**Server version:** 11.0.1

**Calendar version:** 1.5.0

**Updated from an older installed version or fresh install:** Updated from a version 10 (same issue)

**Signing status (ownCloud/Nextcloud 9.0 and above):** No errors

**List of activated apps:**
Activity 2.4.1
Collaborative tags 1.1.3
Comments 1.1.0
Default encryption module 1.4.1
Deleted files 1.1.0
Federation 1.1.1
File sharing 1.1.1
First run wizard 2.0
Gallery 16.0.0
Log Reader 2.0.0
Nextcloud announcements 1.0
Notifications 1.0.1
Password policy 1.1.0
PDF viewer 1.0.1
Server info 1.1.1
Share by mail 1.0.1
Text editor 2.2
Theming 1.1.1
Update notification 1.1.1
Usage survey 0.1.5
Versions 1.4.0
Video player 1.0.0
Calendar 1.5.0
Contacts 1.5.2
Notes 2.2

**Are you using encryption:** no

### Client configuration

**Operating system:** Win 10, Ubuntu 16.10

**CalDAV-clients:** Thunderbird 45.7.1 with Lightning 4.7.7.1

#### Log file (data/owncloud.log)
Debug	webdav	Sabre\DAV\Exception\NotAuthenticated: HTTP/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured

    [internal function] Sabre\DAV\Auth\Plugin->beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /3rdparty/sabre/dav/lib/DAV/Server.php - line 466: Sabre\Event\EventEmitter->emit('beforeMethod', Array)
    /3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /apps/dav/lib/Server.php - line 227: Sabre\DAV\Server->exec()
    /apps/dav/appinfo/v2/remote.php - line 30: OCA\DAV\Server->exec()
    /remote.php - line 165: require_once('/...')
    {main}

**Comment by nickvergessen** [comment]
Did you use your normal password in THunderbird or a "App password"/"App token"?
You should to the later and then it still works for me.

**Comment by fuzsin** [comment]
Sorry for late reply, got no notification. It was a "normal" Password. The same issue with my second Nextcloud installation, regardless of which client is used (tested with TB and FossaMail).

**Comment by MorrisJobke** [comment]
The API itself should still work. This looks more like a security feature inside of TB and FossaMail, because we don't use the themes name to check if a user needs to sign in again. Could I ask you to talk with the TB people about this? I don't see any problem on our side so far. :/

Closing for now until we know more from TB.
