### ISSUE TITLE
[Bug]: Cannot remove error "The "X-Frame-Options" HTTP header is not set to "SAMEORIGIN"?

### ISSUE THREAD

**Issue by tchap2** [nextcloud/server#36430]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Running NC 25.0.3 in docker on UNRAID OS. nginx came embedded in NC with docker installation
In Settings-> overview shows following error:

The "X-Frame-Options" HTTP header is not set to "SAMEORIGIN". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly.

Can someone explain how to remove this error?

Explanation [here](https://github.com/nextcloud/server/issues/24129) and [here](https://github.com/nextcloud/docker/issues/928) are both **total nonsense**. 

**In both cases, everyone comments, but no one can provide a solution. Not even Nextcloud developers. Worse, NC developers keep saying "update NC and report back if issue persists" - THE ISSUE HAS BEEN PERSISTING FOR AT LEAST 6 MAJOR NC RELEASES - Developers- How much proof do you need?**

What is the name of the file that must be edited, where is this file located (full path), and where within the file must "SAMEORIGIN" be added? What is the exact syntax?

I just updated to 25.0.3, and the "The "X-Frame-Options" HTTP header is not set to "SAMEORIGIN" is still there.

Solutions in nextcloud User Guide DO NOT WORK!

**Can someone please put an end to this non-sense and explain STEP-BY-STEP exactly WHERE, WHAT needs to be changed? It's ridiculous that after so many years of complaining, this is the ONLY ERROR that cannot be fixed on nextcloud.**

### Steps to reproduce

See "Bug description"

### Expected behavior

See "Bug description"

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
See "Bug description"
```

### List of activated Apps

```shell
See "Bug description"
```

**Comment by szaimen** [comment]
Lets handle this in https://github.com/nextcloud/server/issues/24129
