### ISSUE TITLE
11.0.2 incredibly slow login

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/server#3645]
Nextcloud version (eg, 10.0.2): 11.0.2
Operating system and version (eg, Ubuntu 16.04): U 16.04.1
Apache or nginx version (eg, Apache 2.4.25): Apache 2.4.18
PHP version (eg, 5.6): 7.0.15
Is this the first time you've seen this error?: Yes

Can you reliably replicate it? (If so, please outline steps):

Yes, at any point by logging out and attempting to log in again.

The issue you are facing:

I upgraded to 11.0.2 earlier, lovely upgrade, nothing went wrong and the logs are clean.

However, logging in from a logged out state takes upwards of 40 seconds. It is insanely slow. 
Once logged in everything is fine, maybe not quite as snappy but no noticeable difference to 11.0.1.

Due to this delay, my mobile clients can't login or upload to the server.

The output of your Nextcloud log in Admin > Logging:

Here's what the mobile clients appear to be doing:

```
Info	admin_audit	Login successful: "jason"	2017-02-28T00:14:40+0000
Info	admin_audit	Login attempt: "jason"	2017-02-28T00:14:40+0000
Info	admin_audit	Logout occurred	2017-02-28T00:14:06+0000
Info	admin_audit	Login successful: "jason"	2017-02-28T00:13:12+0000
Info	admin_audit	Login attempt: "jason"	2017-02-28T00:13:12+0000
Info	admin_audit	Login successful: "jason"	2017-02-28T00:12:43+0000
Info	admin_audit	Login attempt: "jason"	2017-02-28T00:12:43+0000
Info	admin_audit	Login successful: "jason"	2017-02-28T00:09:38+0000
Info	admin_audit	Login attempt: "jason"	2017-02-28T00:09:38+0000
Info	admin_audit	Login successful: "jason"	2017-02-28T00:06:54+0000
Info	admin_audit	Login attempt: "jason"	2017-02-28T00:06:53+0000
Info	admin_audit	Login successful: "jason"	2017-02-28T00:06:51+0000

```
The output of your config.php file in /path/to/nextcloud (make sure you remove any identifiable information!):

N/A

The output of your Apache/nginx/system log in /var/log/____:

I've inspected both Apache and MariaDB logs for errors, absolutely clean as a whistle. Nothing to indicate an issue whatsoever.

**Comment by jasonbayton** [comment]
I have:

* Rebooted Nextcloud
* Rebooted the MariaDB host server
* Rebooted the proxy (same behaviour with proxy or with direct nc server ip)
* Added `'auth.bruteforce.protection.enabled' => false,` to the config
* Inspected the logs for errors (there are none)
* Kept Chrome dev tools opened while trying to load the page (I see HTTP 303 see other on page load)

No improvement as yet.

**Comment by jasonbayton** [comment]
Right.

So now everything is fine.

I did a couple more service restarts on Apache while toggling the bruteforce config entry on and off and now it logs in once again in about 1sec.

Who manages the bruteforce app? If it activates against a user/IP does it have a set timeout?

**Comment by Bullnados** [comment]
Perhaps the same error equal to #2272?

**Comment by aventrax** [comment]
Same here. Restarted VPS, restarted MariaDB, added  'auth.bruteforce.protection.enabled' => false as you suggested -> no success.

My login is slow, it take 10-15s and then everything is perfect and fast!

**Comment by SomeStrangeName** [comment]
I had the same issues after some experiments. Would be nice to have some information about this "slow down" in the admin view on the webpage. It looks like some experiments blocked my own IP and then sync was no longer possible because of the slow down. Checking and deleting the oc_bruteforce_attempts table was the solution.

**Comment by jimbowarrior** [comment]
Same issue !!!! I flushed the database. I think  I disable this features.... Can we use fail2ban instead ?

**Comment by e-alfred** [comment]
@jasonbayton Maybe best to report the bug to the Bruteforce app issue tracker directly?

**Comment by jasonbayton** [comment]
This was closed 11 months ago...

**Comment by e-alfred** [comment]
But it seems to be still a problem for some people:

https://help.nextcloud.com/t/macos-apps-cant-connect-after-upgrade-to-12-0-5/26376/5
https://help.nextcloud.com/t/11-0-2-incredibly-slow-login/9475/26
