### ISSUE TITLE
[Bug]: “warning: (user wwwrun / group www) does not exist - using root”

### ISSUE THREAD

**Issue by rokejulianlockhart** [nextcloud/server#36460]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

[This](https://github.com/nextcloud/server/files/10549958/1675192404.txt.md) demonstrates the problem. Specifically, the 2 repeating warnings:
`warning: user wwwrun does not exist - using root` and
`warning: group www does not exist - using root`.

![image](https://user-images.githubusercontent.com/42837531/215860817-4cea8731-7223-4c93-80f1-901c11940762.png)

### Steps to reproduce

`sudo zypper install nextcloud -y`

### Expected behavior

The installer should create the necessary groups and users.

### Installation method

Other Community project

### Operating system

Other

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
rokejulianlockhart@localhost:~> sudo -u www-data php occ config:list system
sudo: unknown user www-data
sudo: error initializing audit plugin sudoers_audit
rokejulianlockhart@localhost:~> php occ config:list system
Could not open input file: occ
rokejulianlockhart@localhost:~> ./occ config:list system
bash: ./occ: No such file or directory
rokejulianlockhart@localhost:~>
```

### List of activated Apps

```shell
rokejulianlockhart@localhost:~> sudo -u www-data php occ app:list
sudo: unknown user www-data
sudo: error initializing audit plugin sudoers_audit
rokejulianlockhart@localhost:~> php occ app:list
Could not open input file: occ
rokejulianlockhart@localhost:~> ./occ app:list
bash: ./occ: No such file or directory
rokejulianlockhart@localhost:~>
```

### Nextcloud Signing status

```shell
rokejulianlockhart@localhost:~> https://yournextcloud.tld/index.php/settings/integrity/failed
bash: https://yournextcloud.tld/index.php/settings/integrity/failed: No such file or directory
```

### Nextcloud Logs

```shell
rokejulianlockhart@localhost:~> ls /settings/admin/logging
ls: cannot access '/settings/admin/logging': No such file or directory
```

### Additional info

Requested information:
```shell
rokejulianlockhart@localhost:~> uname -a
Linux localhost.localdomain 6.1.8-1-default #1 SMP PREEMPT_DYNAMIC Tue Jan 24 06:29:25 UTC 2023 (baebfe0) x86_64 x86_64 x86_64 GNU/Linux
```

Additional information:
```shell
rokejulianlockhart@localhost:~> zypper info nextcloud
Loading repository data...
Reading installed packages...


Information for package nextcloud:
----------------------------------
Repository     : Main Repository (OSS)
Name           : nextcloud
Version        : 25.0.3-1.1
Arch           : noarch
Vendor         : openSUSE
Installed Size : 452.4 MiB
Installed      : No
Status         : not installed
Source package : nextcloud-25.0.3-1.1.src
Upstream URL   : https://nextcloud.com
Summary        : File hosting service
Description    : 
    Nextcloud is a suite of client-server software for creating file
    hosting services and using them.

```

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

**Comment by rokejulianlockhart** [comment]
@szaimen, did you read the report? If the installer doesn't locate those groups, shouldn't it create them?

**Comment by szaimen** [comment]
This installer is not made by us so you should report it to the correct repository.

**Comment by ecsgh** [comment]
> 



> @szaimen, did you read the report? If the installer doesn't locate that group and user, shouldn't it create them? (What else is an installer for, if not to perform basic tasks such as those automatically?)
> 
> That is, if creation of those is necessary to install the package in an operational manner. If not, I agree.

What does installer mean here?
This is not an installer. This is a normal rpm package.
And this package must not create the user at all.
Because this is the user of the apache. And this is also created during the installation of the apache. Only the apache package is allowed to create the user.
My guess is that the user has changed the default user. Then of course all other applications can not work. Because they get the user from the apache-rpm-macros.rpm.
