### ISSUE TITLE
integrity check is a pain

### ISSUE THREAD

**Issue by dirigit** [nextcloud/server#3646]
Even when using scp to transfer files some TXT files (i.e. core/fonts/LICENSE.txt) fail.

An example for PHP is apps/files-external/3rdparty/Dropbox/API.php. It complains about CSS as well (i.e. core/doc/admin/_static/style.css).

Remark related to note at https://docs.nextcloud.com/server/11/admin_manual/issues/code_signing.html#fixing-invalid-code-integrity-messages:

CSS, TXT, PHP, JS and similar files have to be transferred as text, never ever as binary. They are a security issue in case of being transferred in binary mode. They could be real binaries than and open a can of worms (as such things already did in stone age at mailbox times).

No checksum will prevent of damage for itself and a wrong ^Z in a file causes no real damage for sure. Such issues can be caught with code ...

**Comment by rullzer** [comment]
The thing is that we have no way to know what causes the faulty checksum. It could be an added ^Z or somebody could have messed with the code.

If you don't trust the CSS/TXT/PHP/JS files transfered to your server then probabaly trusting the code that they contain to run on your server is also not ideal :wink: 

So sorry but this is unlikely to change.

**Comment by dirigit** [comment]
Hi,

I'm aware of this but, nevertheless it's uncomfortable. The files mentioned are from distribution of Nextcloud without any changes.
