### ISSUE TITLE
Remaining upload time is wrong

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#3647]
* upload a bigger file via the web UI
* the time somehow behaves crazy - sometimes start with "a few seconds" jumps to multiple minutes or hours" and then quickly gets to "a few seconds" for the rest of the upload

Estimate at the very beginning (first 2 seconds):
![bildschirmfoto 2017-02-28 um 00 14 54](https://cloud.githubusercontent.com/assets/245432/23393839/305b9f62-fd4b-11e6-84b3-c9852038d68e.png)

Then it took nearly a minute to upload and it always said "a few seconds":
![bildschirmfoto 2017-02-28 um 00 14 56](https://cloud.githubusercontent.com/assets/245432/23393856/47be931c-fd4b-11e6-9959-4e53a3034d41.png)

The upload calculation is done here: https://github.com/nextcloud/server/blob/7fc3129f0cb80358c5b8f5c2b93f0aa446d1c317/apps/files/js/file-upload.js#L1003-L1031

cc @nextcloud/javascript for volunteers to fix this 😉

**Comment by rullzer** [comment]
Mandatory xkcd https://xkcd.com/612/

**Comment by marncz** [comment]
@MorrisJobke 
#3727 is it fixed then?

**Comment by blizzz** [comment]
Nope, the PR was closed in favor of https://github.com/nextcloud/server/pull/3896

**Comment by MorrisJobke** [comment]
Fixed with #3896
