### ISSUE TITLE
Easy installation

### ISSUE THREAD

**Issue by lynrayy** [nextcloud/server#36488]
**Is your feature request related to a problem? Please describe.**
Yes. I have windows and absilutly have no idea how to use linux and linux inside VM

**Describe the solution you'd like**
Please make server easy installable on windows as .exe installer and .exe soft which you just starting up and it works

**Describe alternatives you've considered**
Download another program. Not found alternative. Tried to use VM, but i can't change port because everywhere people say "YoU mUsT uSe tHiS lInUx cOmMaNd" but i can't type anything in console in VM

**Comment by szaimen** [comment]
Hi, see https://nextcloud.com/blog/your-guide-to-the-nextcloud-all-in-one-on-windows-10-11/
