### ISSUE TITLE
Fixed footer (banner) blocks view of public shares on smaller screens

### ISSUE THREAD

**Issue by mcnesium** [nextcloud/server#36485]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since the latest theme change, the `position:fixed`-footer on the file drop upload page covers the list of uploaded files:

Here is a screenshot of the page after uploading a file. The page has been scrolled up for a tiny bit so that part of the file name can be seen between the static footer and the end of the browser window:

https://user-images.githubusercontent.com/476060/216149723-2ccf5323-352d-479f-b3ed-dc2f24d9d731.MOV

Furthermore, even without uploading, the page looks pretty odd and the difference in white space makes the overall appearance of the page look pretty ugly imho:

<img src="https://user-images.githubusercontent.com/476060/216148231-0a97e485-cec9-4d8f-8451-0aa42218e057.jpeg" height="20%" width="20%">

### Steps to reproduce

1. go to a "File drop (upload only)" share with a small screen device, e.g. iPhone SE
2. upload a file
3. see the file list covered by the page footer with the slogan and stuff

### Expected behavior

The footer should be static and always stay below anything else on the page.

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Files
```

**Comment by szaimen** [comment]
Hi, which nc version?

**Comment by mcnesium** [comment]
Sorry, I am seeing this on my instance which is on v25.0.3. The screencast was with whatever demo1.nextcloud.com is on today.

**Comment by jmhammond** [comment]
Even on a larger (non-mobile) screen, the footer covers over the uploaded files.

Here my Firefox window isn't full screen, note how it looks like there's nothing under uploaded files
![2023-02-06_15-13-26](https://user-images.githubusercontent.com/84139/217089427-6721e3e2-dc98-4174-853a-2411ab92076d.png)

Here I've made the window larger, and we see that something did in fact upload.
![2023-02-06_15-13-39](https://user-images.githubusercontent.com/84139/217089448-c8026d61-b57d-4a05-bf25-c18c92d47f57.png)

This is on v25.0.3.
