### ISSUE TITLE
Remove Button and Select Field if there are all Actions disabled 

### ISSUE THREAD

**Issue by idna001** [nextcloud/server#36527]
The Screenshot shows the case where all actions are disabled, in this case the button is not needed. 
Also, the selections make no sense in this case, because you can't make anything with it when you have all actions disabled. 
So in my opinion, the button should be invisible.
![IMG_1308](https://user-images.githubusercontent.com/46223359/216662577-d1f91583-58fa-490a-ab3b-6408e9d18e4d.jpeg)

What I also discovered is that the buttons that are not visible are simply hidden. Here would be a small performance improvement possible by not rendering these HTML Elements at all, instead of just hiding them.

**Comment by szaimen** [comment]
I think this should be fixed with 28
