### ISSUE TITLE
SMTP sender name is incorrect

### ISSUE THREAD

**Issue by ronroze** [nextcloud/server#3653]
### Steps to reproduce
1. In Email settings - set send mode to SMTP, enter the appropriate 'from' address, set Authentication Method to Login.
2. Enter credentials for MS Exchange authentication in the form of Domain\User.
3. Share a file with a user outside of your organization.

### Expected behaviour
The external user should receive an email from the address files@company.com, but the name of the sender should be the one configured in Active Directory (displayName or name), for example - 'Company Files Cloud'.

### Actual behaviour
The external user receives an email from the address files@company.com, but the name of the sender is the local part of the email address, i.e. 'files'. This issue appeared after upgrading to v11.0.1.

### Server configuration
**Operating system**: Ubuntu 16.04.2

**Web server:** Apache/2.4.18

**Database:** mysql 10.0.29

**PHP version:** 7.0.15

**Nextcloud version:** (see Nextcloud admin page) 11.0.2 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated through all stable releases from a clean install of the first stable Nextcloud release.

**Where did you install Nextcloud from:** Downloaded .zip file from website.

**Signing status:** Disabled

<details>
<summary>App list</summary>
activity: 2.4.1
comments: 1.1.0
dav: 1.1.1
federatedfilesharing: 1.1.1
federation: 1.1.1
files: 1.6.1
files_pdfviewer: 1.0.1
files_sharing: 1.1.1
files_texteditor: 2.2
files_trashbin: 1.1.0
files_versions: 1.4.0
files_videoplayer: 1.0.0
firstrunwizard: 2.0
gallery: 16.0.0
logreader: 2.0.0
lookup_server_connector: 1.0.0
nextcloud_announcements: 1.0
notifications: 1.0.1
password_policy: 1.1.0
provisioning_api: 1.1.0
serverinfo: 1.1.1
sharebymail: 1.0.1
systemtags: 1.1.3
templateeditor: 0.2
theming: 1.1.1
twofactor_backupcodes: 1.0.0
updatenotification: 1.1.1
user_ldap: 1.1.2
workflowengine: 1.1.1

</details>

<details>
<summary>Config report</summary>
"system": {
        "instanceid": "sdfge5g5g",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.company.local"
        ],
        "auth.bruteforce.protection.enabled": false,
        "integrity.check.disabled": true,
        "datadirectory": "\/home\/nextcloud\/data",
        "overwritehost": "files.company.com",
        "overwrite.cli.url": "https:\/\/nextcloud.company.local",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "Files",
        "mail_domain": "company.com",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "ex10.company.local",
        "mail_smtpport": "587",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }

</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** ActiveDirectory

**Comment by ronroze** [comment]
LDAP configuration:
[LDAP.txt](https://github.com/nextcloud/server/files/806785/LDAP.txt)

**Comment by taut98** [comment]
did you try to use it without authentification? normally you dont need for Exchange Servers with SMTP
