### ISSUE TITLE
Major version swithing

### ISSUE THREAD

**Issue by remixoff** [nextcloud/server#36535]
Hi guys! 
Could you, please, switch the major versions not so frequently? 
It's almost impossible to collect an application set!!! 
I can't use Share Renamer and Transfer at the same time, because Share Renamer written for 18 (afair) version, but Transfer starts to work from 23rd. 
It's made the app going to useless and demotivates side authors to write useful apps. Because it's not enough to write an app, he has to support it for all of his life. It's terrible. Somebody could like even meet a girl instead of infinite coding. Please, care about them.

Please, keep your work useful.... I guess it's also fine for authors to know that they don't write code just to write code, but are making some product that makes life better.

**Comment by szaimen** [comment]
Share renamer is compatible with nc22-25. See https://apps.nextcloud.com/apps/sharerenamer
