### ISSUE TITLE
Remove javascript sources map files (*.js.map) to reduce images size

### ISSUE THREAD

**Issue by Adphi** [nextcloud/server#36536]
Why are the sources map files included in the image ?

In the latest *fpm-alpine* image we can see:

```sh
$ du -hs /usr/src/nextcloud/
535.5M  /usr/src/nextcloud/

$ find /usr/src/nextcloud -name '*.js.map' -exec rm {} \;
$ du -hs /usr/src/nextcloud/
396.5M  /usr/src/nextcloud/
```

We can save 139M, and also decreases boot time. 
Even more so if we remove the source map files from all the `/var/www/html` as this will also remove the plugin ones:

In the latest *apache* image:
```sh
# install the dummy instance
$ su www-data -s /bin/sh -c "./occ maintenance:install --admin-user=admin --admin-pass=admin"
# install some apps
$ for app in mail calendar contacts tasks spreed; do su www-data -s /bin/sh -c "./occ app:install $app && ./occ app:enable $app"; done
# take a look at the size
$ du -hs / 2> /dev/null
2.0G    /
# remove sources map
$ find /usr/src/ -name "*.js.map" -exec rm -f {} \;
$ find /var/www/html/ -name "*.js.map" -exec rm -f {} \;
# take a look at the size again
$ du -hs / 2> /dev/null
1.5G    /
```

**Comment by szaimen** [comment]
cc @nextcloud/server-frontend @juliushaertl @ChristophWurst @nickvergessen for some thoughts on this.

**Comment by nickvergessen** [comment]
They are included because only then JS errors are useful.

**Comment by Adphi** [comment]
Oooops 😬  wrong repo, so sorry. I intended to create the issue on nextcloud/docker.

But as this is the result of the frontend build, I guess it's also relevant here.

Should the source maps be included in the production build ?

**Comment by jvoisin** [comment]
> They are included because only then JS errors are useful.

An alternative would be to use something like `//# sourceMappingURL: http://nextcloud.com/maps/app/static/app.min.js.map` in minified javascript, so that deployments don't have to ship ~200M of javascript map files, while still having meaningful stacktraced.
