### ISSUE TITLE
Setup Imaginary in order to allow it to Rasterise PDF Files for NC Previews

### ISSUE THREAD

**Issue by armouredking** [nextcloud/server#36543]
**Is your feature request related to a problem? Please describe.**
Current configuration of Imaginary as of NC 25.0.3 does not support rendering a preview image for PDF files. Imaginary is capable of doing this seemingly out of the box with Ubuntu 22.04 `libvips42` package (unsure of build for AIO docker but also tested); request to allow for use of Imaginary rather than having to use ImageMagick.

**Describe the solution you'd like**
`Imaginary.php` file in `/lib/private/Preview` requires editing to support mimetype `Application/PDF` and probably some form of logic in the operations section of function `getCroppedThumbnail` to perform the necessary `convert` operation to get a usable preview image for NC. I am not really a coder, so I'm not sure what other logic might be desirable in the operation section of the function for PDF previews. It's likely that you'd still want the other params defined for previews to also be applied to PDF rasterisation images.

**Describe alternatives you've considered**
An evaluation of capability is tested working both with an Imaginary source build on Ubuntu 22.04 and using the Nextcloud AIO Imaginary docker `:develop` branch image.

**Additional context**
See discussion [#1906](https://github.com/nextcloud/all-in-one/discussions/1906#discussioncomment-4866032) from NC AIO that demonstrates the capability.

**Comment by szaimen** [comment]
PR in https://github.com/nextcloud/server/pull/36546
