### ISSUE TITLE
[Bug]: Hovering an input hides validation error

### ISSUE THREAD

**Issue by susnux** [nextcloud/server#36548]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When hovering or focus an invalid input, the border color is changed from `error` to `primary`.
E.g. you are entering text you normally hover the element, but now you can not see that there are validation errors.

(see video below)

### Steps to reproduce

1. Create an input element
2. Set validation to some error
3. Hover the input

### Expected behavior

`input` border color for `:invalid` has higher priority than hovering an input.

### Installation method

Community Docker image

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

SQlite

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
-
```

### Additional info

This is from current server master (Nextcloud 26).

### Screen recording

https://user-images.githubusercontent.com/1855448/216838222-2c50a30d-f91e-4b82-a004-91ca3c83a4de.mp4

**Comment by szaimen** [comment]
Isnt this a nextcloud-vue library issue?

**Comment by susnux** [comment]
> Isnt this a nextcloud-vue library issue?

No both rules for inputs (`:invalid` and `:hover`)  are from `inputs.scss`, but the hover rule has currently a higher priority.

**Comment by susnux** [comment]
`:invalid` border color seems to be dropped from `inputs.scss`
