### ISSUE TITLE
[Bug]: NC26.0.0beta2: Email documentation needs to be adapted (or Email setup dialog lacks security settings)

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#36542]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

According to the latest server admin manual, section [email_configuration](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/email_configuration.html), I should be able to choose Encryption from NONE, SSL/TLS and STARTTLS. I should also be able to choose and set an Authentication method. In my newly installed NC26.0.0beta2 instance, I see that the dialog has changed.

For me, it's unclear what to set. I want STARTTLS. Must I choose "NONE"? If so, will PHP try to use STARTTLS anyway? If so, it should be named "NONE/STARTLS" or "Opportunistic". Else it's a drawback since my server only accepts STARTTLS and setting it to "SSL/TLS" yields an error upon testing. I consider it a drawback anyway since I can no longer enforce encryption using STARTTLS.

Apart from the dialog, the documentation needs to be adapted. Could be worth to also mention it in the NC26 release notes.

NC25:
![grafik](https://user-images.githubusercontent.com/8425483/216798092-4ec030ae-b1bf-4835-8f71-7abcc9bb89d9.png)

NC26:
![grafik](https://user-images.githubusercontent.com/8425483/216798140-5a6fa86d-88ad-4f14-8d59-f1858f72cb26.png)

### Steps to reproduce

1. freshly install OR update to NC26.0.0beta2 (I tested both)
2. open /settings/admin
3. compare Email settings between NC26 and NC25
4. compare Email settings between NC26 and latest documentation

### Expected behavior

- Allow to enforce encryption not only with SSL/TLS but also with STARTTLS (if that's still possible)
- Clearify in dialog that STARTLS is being used (if that's what happens)
- Don't forget to update the docs :)

### Installation method

Community Manual installation with Archive

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "stage.selbstbestimmt-digital.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.0.4",
        "overwrite.cli.url": "https:\/\/stage.selbstbestimmt-digital.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "beta",
        "installed": true,
        "app_install_overwrite": [
            "twofactor_webauthn"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - cloud_federation_api: 1.9.0
  - dav: 1.25.0
  - federatedfilesharing: 1.16.0
  - files: 1.21.1
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - password_policy: 1.16.0
  - provisioning_api: 1.16.0
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - text: 3.7.0
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - twofactor_webauthn: 1.0.0
  - updatenotification: 1.16.0
  - viewer: 1.10.0
  - workflowengine: 2.8.0
Disabled:
  - activity: 2.18.0 (installed 2.18.0)
  - admin_audit: 1.16.0
  - bruteforcesettings: 2.6.0
  - circles: 26.0.0-beta2 (installed 26.0.0-beta2)
  - comments: 1.16.0 (installed 1.16.0)
  - contactsinteraction: 1.7.0 (installed 1.7.0)
  - dashboard: 7.6.0 (installed 7.6.0)
  - encryption: 2.14.0
  - federation: 1.16.0 (installed 1.16.0)
  - files_external: 1.18.0
  - files_pdfviewer: 2.7.0 (installed 2.7.0)
  - files_versions: 1.19.1 (installed 1.19.1)
  - firstrunwizard: 2.15.0 (installed 2.15.0)
  - nextcloud_announcements: 1.15.0 (installed 1.15.0)
  - photos: 2.2.0 (installed 2.2.0)
  - privacy: 1.10.0 (installed 1.10.0)
  - recommendations: 1.5.0 (installed 1.5.0)
  - related_resources: 1.1.0-alpha1 (installed 1.1.0-alpha1)
  - support: 1.9.0 (installed 1.9.0)
  - survey_client: 1.14.0 (installed 1.14.0)
  - suspicious_login: 4.4.0
  - systemtags: 1.16.0 (installed 1.16.0)
  - twofactor_totp: 8.0.0-alpha.0
  - user_ldap: 1.16.0
  - user_status: 1.6.0 (installed 1.6.0)
  - weather_status: 1.6.0 (installed 1.6.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Not relevant.
```

**Comment by szaimen** [comment]
Cc @come-nc @miaulalala

**Comment by miaulalala** [comment]
documentation ticket is here https://github.com/nextcloud/documentation/issues/9600
