### ISSUE TITLE
Change the event invitation email subject to "Invitation updated: ..." in case an existing event gets updated

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/server#36553]
### Is your feature request related to a problem? Please describe.

Currently, the subject of an iMIP email is always "XXX would like to invite you to YYY"

### Describe the solution you'd like

If an old event exists and this is an update to it, change the subject of the email to reflect that.

### Additional context

As a follow up to https://github.com/nextcloud/server/pull/35743

kindly suggested by @onny

**Comment by onny** [comment]
Opened an upstream issue in case this is related to sabre-io/dav https://github.com/sabre-io/dav/issues/1453
