### ISSUE TITLE
[Bug]: Error opcache.interned_strings_buffer still there after correcting it

### ISSUE THREAD

**Issue by Synochy** [nextcloud/server#36581]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In the administration menu I still have the error PHP OPcache not well configure after increasing the opcache.interned_strings_buffer value to 32 in php.ini.
How do I solve this error ?

### Steps to reproduce

1.Error in administration overview
2.Edit value in php.ini to 32
3.Restart Apache 
4.Error still there

### Expected behavior

No Error after Apache restart

### Installation method

None

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
- activity: 2.17.0
  - admin_audit: 1.15.0
  - announcementcenter: 6.4.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.2.3
  - camerarawpreviews: 0.8.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.1.0
  - contactsinteraction: 1.6.0
  - cospend: 1.5.6
  - dashboard: 7.5.0
  - dav: 1.24.0
  - extract: 1.3.5
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - gpxedit: 0.0.14
  - gpxpod: 5.0.4
  - impersonate: 1.11.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - metadata: 0.17.0
  - ncdownloader: 1.0.2
  - news: 20.0.1
  - nextcloud_announcements: 1.14.0
  - notes: 4.6.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - phonetrack: 0.7.4
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - ransomware_protection: 1.14.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - richdocuments: 7.1.0
  - richdocumentscode: 22.5.802
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - side_menu: 3.5.2
  - spreed: 15.0.3
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_ldap: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
```

**Comment by szaimen** [comment]
This should be fixed wirh 25.0.4

**Comment by Synochy** [comment]
I upgraded to nextcloud 25.0.4 and I still have the error

**Comment by szaimen** [comment]
cc @MichaIng

**Comment by MichaIng** [comment]
Did you verify e.g. via [`phpinfo`](https://www.php.net/manual/de/function.phpinfo.php), [opcache-gui](https://github.com/amnuts/opcache-gui) or [`opcache_get_status`](https://www.php.net/manual/en/function.opcache-get-status.php) that those 32 MiB are really applied (and not overwritten by some higher priority drop-in config? And if so, use one of second two ways to check whether those 32 MiB are really used (they are, so this is just for you to see that Nextcloud obtains this info correctly).

If you run other PHP applications on the same server, beside Nextcloud, it is expected that you need a higher OPcache and interned strings buffer. Nextcloud alone should not need more than 4 - 16 MiB.

> Error in administration overview

This is not an error but a performance recommendation, which naturally isn't critical. It may enhance your Nextcloud's performance, but if on a single Nextcloud instance such high strings buffer values are used, then it is some bug/leak in one of the apps, or probably some inefficiency/missing garbage collection in OPcache itself. This is hard to debug, as I'm not aware of a way to see the actual interned strings buffer content. However, I'd then not raise he buffer above 16 MiB.

What is your `opcache.memory_consumption` set to? Nextcloud won't show you a recommendation about the interned strings buffer, if it is a quarter of `opcache.memory_consumption` already, or higher. Since a single Nextcloud instance should never use more than 64 MiB OPcache memory, and the default is 128, an interned strings buffer of 32 MiB should then silence all warnings.

**Comment by Synochy** [comment]
After doing php-i command here are my setting of OPCahe:
Directive => Local Value => Master Value
opcache.blacklist_filename => no value => no value
opcache.consistency_checks => 0 => 0
opcache.dups_fix => Off => Off
opcache.enable => On => On
opcache.enable_cli => Off => Off
opcache.enable_file_override => Off => Off
opcache.error_log => no value => no value
opcache.file_cache => no value => no value
opcache.file_cache_consistency_checks => On => On
opcache.file_cache_only => Off => Off
opcache.file_update_protection => 2 => 2
opcache.force_restart_timeout => 180 => 180
opcache.huge_code_pages => Off => Off
opcache.interned_strings_buffer => 8 => 8
opcache.jit => no value => no value
opcache.jit_bisect_limit => 0 => 0
opcache.jit_blacklist_root_trace => 16 => 16
opcache.jit_blacklist_side_trace => 8 => 8
opcache.jit_buffer_size => 0 => 0
opcache.jit_debug => 0 => 0
opcache.jit_hot_func => 127 => 127
opcache.jit_hot_loop => 64 => 64
opcache.jit_hot_return => 8 => 8
opcache.jit_hot_side_exit => 8 => 8
opcache.jit_max_exit_counters => 8192 => 8192
opcache.jit_max_loop_unrolls => 8 => 8
opcache.jit_max_polymorphic_calls => 2 => 2
opcache.jit_max_recursive_calls => 2 => 2
opcache.jit_max_recursive_returns => 2 => 2
opcache.jit_max_root_traces => 1024 => 1024
opcache.jit_max_side_traces => 128 => 128
opcache.jit_prof_threshold => 0.005 => 0.005
opcache.lockfile_path => /tmp => /tmp
opcache.log_verbosity_level => 1 => 1
opcache.max_accelerated_files => 10000 => 10000
opcache.max_file_size => 0 => 0
opcache.max_wasted_percentage => 5 => 5
opcache.memory_consumption => 128 => 128
opcache.opt_debug_level => 0 => 0
opcache.optimization_level => 0x7FFEBFFF => 0x7FFEBFFF
opcache.preferred_memory_model => no value => no value
opcache.preload => no value => no value
opcache.preload_user => no value => no value
opcache.protect_memory => Off => Off
opcache.record_warnings => Off => Off
opcache.restrict_api => no value => no value
opcache.revalidate_freq => 2 => 2
opcache.revalidate_path => Off => Off
opcache.save_comments => On => On
opcache.use_cwd => On => On
opcache.validate_permission => Off => Off
opcache.validate_root => Off => Off
opcache.validate_timestamps => On => On

I don't have any other PHP application of this server.

**Comment by MichaIng** [comment]
These are the PHP CLI configs, which do not necessarily match the ones of PHP instance(s) used by the webserver. Best is to create a PHP script with one of the functions I linked above, respectively the opcache-gui tool itself, and access it via browser.

Which `php.ini` did you edit explicitly? Where did you install PHP 8.1 from? Is it PHP-FTM or Apache's mod_php?

**Comment by Synochy** [comment]
I edited php.ini which is in etc/php/8.1/apache2/php.ini

**Comment by MichaIng** [comment]
And are you sure that you use Apache2 uses this `mod_php8.1`?
```sh
apachectl -M
```

Better do create a dedicated config, btw:
```sh
echo -e '; Custom config\n; priority=99\nopcache.interned_strings_buffer=16' > /etc/php/8.1/mods-available/custom.ini
phpenmod custom
ls -l  /etc/php/8.1/apache2/conf.d/99-custom.ini
systemctl restart apache2
```

**Comment by Synochy** [comment]
here is my apachectl -M:
Loaded Modules:
 core_module (static)
 so_module (static)
 watchdog_module (static)
 http_module (static)
 log_config_module (static)
 logio_module (static)
 version_module (static)
 unixd_module (static)
 access_compat_module (shared)
 alias_module (shared)
 auth_basic_module (shared)
 authn_core_module (shared)
 authn_file_module (shared)
 authz_core_module (shared)
 authz_host_module (shared)
 authz_user_module (shared)
 autoindex_module (shared)
 deflate_module (shared)
 dir_module (shared)
 env_module (shared)
 filter_module (shared)
 headers_module (shared)
 mime_module (shared)
 mpm_prefork_module (shared)
 negotiation_module (shared)
 php_module (shared)
 reqtimeout_module (shared)
 rewrite_module (shared)
 setenvif_module (shared)
 socache_shmcb_module (shared)
 ssl_module (shared)
 status_module (shared)

**Comment by MichaIng** [comment]
And the config is not defined in another module?
```sh
grep -r 'interned_strings_buffer' /etc/php/8.1/apache2/
```
If so, the second part of my last comment should solve it.

**Comment by Synochy** [comment]
/etc/php/8.1/apache2/php.ini.save:;opcache.interned_strings_buffer=8
/etc/php/8.1/apache2/php.ini.ucf-dist:;opcache.interned_strings_buffer=8
/etc/php/8.1/apache2/php.ini.save.1:;opcache.interned_strings_buffer=32
/etc/php/8.1/apache2/php.ini:;opcache.interned_strings_buffer=32

**Comment by MichaIng** [comment]
The value is currently commented. Only lines without leading `;` are effective.

**Comment by Synochy** [comment]
Sorry for this basic mistake, I uncommented the line and now it is working properly.
Thanks for the help
