### ISSUE TITLE
Nextcloud says "Email sent" even SMTP server rejected with SMTP error 550 5.7.1

### ISSUE THREAD

**Issue by robert-scheck** [nextcloud/server#3662]
### Steps to reproduce
1. Get Nextcloud 11.0.1
2. `./occ maintenance:install --data-dir=/var/www/html/data --database mysql --database-name nextcloud --database-user nextcloud --database-pass nextcloud --admin-user admin --admin-pass admin`
3. Logon at Nextcloud
4. Visit http://localhost/settings/personal and set your e-mail address, e.g. `root@example.net`
5. Visit http://localhost/settings/admin/additional and choose "Send mode" -> "SMTP", a valid "From address" and a valid "Server address"
6. Have a SMTP server rejecting e.g. after "RCPT TO" of SMTP dialog
7. Press "Send email" button
8. Receive "Email sent" message

### Expected behaviour
Nextcloud should say "Sending email failed: [Actual last response from SMTP dialog]"

### Actual behaviour
Nextcloud says "Email sent" even SMTP server rejected with SMTP error 550 5.7.1

### Server configuration
**Operating system**: Red Hat Enterprise Linux 7.3, but doesn't matter here anyway.

**Web server:** Apache Webserver 2.4, but doesn't matter here anyway.

**Database:** MariaDB 5.5, but doesn't matter here anyway.

**PHP version:** 7.1 (via Remi Safe repository), but doesn't matter here anyway.

**Nextcloud version:** 11.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh installation.

**Where did you install Nextcloud from:**  https://download.nextcloud.com/server/releases/nextcloud-11.0.1.tar.bz2

**Signing status:** N/A

**List of activated apps:** N/A

**The content of config/config.php:** N/A

**Are you using external storage, if yes which one:** No external storage.

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

**Comment by nickvergessen** [comment]
Can you try whether the following change makes it return an error:
`settings/Controller/MailSettingsController.php`:
find:
```php
$this->mailer->send($message);
```
replace with:
```php
				$errors = $this->mailer->send($message);
				if (empty($errors)) {
					throw new \RuntimeException('Mail could not be sent.');
				}
```

**Comment by robert-scheck** [comment]
No, this still leads to "Email sent" on failures. But when I fixed your typo, it at least throws the exception:

```php
                                $errors = $this->mailer->send($message);
                                if (!empty($errors)) {
                                        throw new \RuntimeException('Mail could not be sent.');
                                }
```

However, the error message returned by the SMTP server is still not shown. And `$error` only seems to contain the destination e-mail address (in an array), but not the real SMTP error.

**Comment by nickvergessen** [comment]
>  However, the error message returned by the SMTP server is still not shown.

Well that is, because there is no error message returned by the API. Okay I will patch it to error, but we can't really show the error message because there is no way for us to get to it.

**Comment by robert-scheck** [comment]
May I kindly ask which library is being consumed? I would expect a sane developed library being suited for professional use to provide such error messages (at least optionally) via API.

**Comment by nickvergessen** [comment]
https://github.com/swiftmailer/swiftmailer/

**Comment by robert-scheck** [comment]
Shouldn't https://github.com/nextcloud/server/issues/3662 provide the missing error message?

**Comment by nickvergessen** [comment]
You linked the same issue?

**Comment by robert-scheck** [comment]
Sorry, I meant https://github.com/swiftmailer/swiftmailer/issues/891
