### ISSUE TITLE
[Bug]: NC26beta3: The files of the app viewer (viewer) were not replaced correctly. Make sure it is a version compatible with the server.

### ISSUE THREAD

**Issue by mwinkens** [nextcloud/server#36657]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After a clean install of nextcloud26beta3 I ran into the following error:
```
The files of the app viewer (viewer) were not replaced correctly. Make sure it is a version compatible with the server.
```
The preferred solution in [other similar issues](https://github.com/nextcloud/server/issues/11801) was to upgrade nextcloud with `php occ upgrade`, which did not work for me and showed the same error message.

Related issues (which did not help me):
#18382
#11801

### Steps to reproduce

1. Install nextcloud26beta3 from [git](https://github.com/nextcloud/server/releases/tag/v26.0.0beta3)
2. Install thrid party tools with `git clone https://github.com/nextcloud/3rdparty.git`
3. Configure nextcloud in UI (admin user, database, ...)
4. Get nextcloud error in View: 
`The files of the app viewer (viewer) were not replaced correctly. Make sure it is a version compatible with the server.`

### Expected behavior

No Error

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "127.0.0.1"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "git",
        "installed": true,
        "config_is_read_only": false,
        "loglevel": 0,
        "theme": "",
        "debug": true,
        "version": "26.0.0.5",
        "maintenance": true
    }
}
```

### List of activated Apps

```shell
Enabled:
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - lookup_server_connector: 1.13.0
  - oauth2: 1.13.0
  - provisioning_api: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - systemtags: 1.15.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit: 1.16.0
  - encryption: 2.14.0
  - files_external: 1.18.0
  - testing: 1.16.0
  - user_ldap: 1.16.0
```

### Nextcloud Logs

```shell
{"reqId":"ITiQZ3PT0L4DYD24iC95","level":3,"time":"2023-02-10T09:57:54+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"The files of the app \"viewer\" were not correctly replaced before running the update","userAgent":"--","version":"26.0.0.5","exception":{"Exception":"UnexpectedValueException","Message":"The files of the app \"viewer\" were not correctly replaced before running the update","Code":0,"Trace":[{"file":"/var/www/nextcloud26/lib/private/Updater.php","line":271,"function":"checkAppsRequirements","class":"OC\\Updater","type":"->"},{"file":"/var/www/nextcloud26/lib/private/Updater.php","line":140,"function":"doUpgrade","class":"OC\\Updater","type":"->"},{"file":"/var/www/nextcloud26/core/Command/Upgrade.php","line":225,"function":"upgrade","class":"OC\\Updater","type":"->"},{"file":"/var/www/nextcloud26/3rdparty/symfony/console/Command/Command.php","line":255,"function":"execute","class":"OC\\Core\\Command\\Upgrade","type":"->"},{"file":"/var/www/nextcloud26/3rdparty/symfony/console/Application.php","line":1009,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->"},{"file":"/var/www/nextcloud26/3rdparty/symfony/console/Application.php","line":273,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud26/3rdparty/symfony/console/Application.php","line":149,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud26/lib/private/Console/Application.php","line":215,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud26/console.php","line":100,"function":"run","class":"OC\\Console\\Application","type":"->"},{"file":"/var/www/nextcloud26/occ","line":11,"args":["/var/www/nextcloud26/console.php"],"function":"require_once"}],"File":"/var/www/nextcloud26/lib/private/Updater.php","Line":391,"message":"The files of the app \"viewer\" were not correctly replaced before running the update","exception":{},"CustomMessage":"The files of the app \"viewer\" were not correctly replaced before running the update"}}
```

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

**Comment by mwinkens** [comment]
Solved by installing from https://download.nextcloud.com/server/prereleases/ instead of git, because the 3rdparty packages are already delivered there.

**Comment by onny** [comment]
Just as a note:
Got the same error while trying to use a Nextcloud version from Git. Solved it by copying over the "viewer" app folder from a daily/nightly release tarball https://download.nextcloud.com/server/daily/
