### ISSUE TITLE
MP4 Preview Images inserted by MetaZ are not used as Preview Image

### ISSUE THREAD

**Issue by britzke** [nextcloud/server#36663]
I have some MP4 files, for which I set a JPEG-Preview Image file with [MetaZ](https://github.com/griff/metaz). These preview images are not used by the preview app. I made a similar issue in the MetaZ project. Maybe this could trigger some information flow on how to achieve this.
(see https://github.com/griff/metaz/issues/251)

**Comment by skjnldsv** [comment]
Hi, it looks liek this is a very narrow feature request.
Unfortunately, this is not on our roadmap in the near future. Therefore I'll close that ticket.

If anyone is willing to put some effort and develop that feature, please feel free to reopen so we can assist you.

**Comment by griff** [comment]
How is looking at the metadata of a file a narrow feature request?

**Comment by britzke** [comment]
In [server/lib/private/Preview/Movie.php](https://github.com/nextcloud/server/blob/master/lib/private/Preview/Movie.php) in the function generateThumbNail (line 138ff) an ffmpeg command is used to get the thumbnail out of the movie file. I found, the  the mpeg command 
`ffmpeg -i  <movie.m4v> -map 0:v -map -0:V -c copy /tmp/<cover.jpg>`
extracts the movie cover. May be it can be used if a cover could be gotten from it.
