### ISSUE TITLE
[Bug]: v25: Typing `0` in the search bar causes errors

### ISSUE THREAD

**Issue by CanManftw** [nextcloud/server#36664]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I am running multiple stable 25.0.3 NC servers to store data. When I type 0 into the search bar on any of my servers, I get a ton of errors. I get about 20 errors that look exactly like the example below.

An error occurred while searching for [appname]

### Steps to reproduce

1. Go to searchbar
2. Type in 0
3.  Behold

### Expected behavior

Some of my files do start with 0, and it does search for them,but I still get all these errors popping up regardless.

### Installation method

Community Docker image

### Operating system

Other

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Unavailable.
```

**Comment by szaimen** [comment]
Which appname?

**Comment by CanManftw** [comment]
> Which appname?

It'll search through a bunch.

-Settings
-Conversations
-Messages
-Files
-Custom Properties
-Deck
-Collectives
-Contacts 

There are more but I can't screenshot in time for every single one and there's nothing in logs that shows anything, not that I could find at least.

**Comment by solracsf** [comment]
Confirmed.

![image](https://user-images.githubusercontent.com/12234510/218150707-d87ad807-9da8-4819-91cf-1de5b571fb99.png)

**Comment by solracsf** [comment]
Error is not present in v24:

![image](https://user-images.githubusercontent.com/12234510/218151820-4aea25a1-e1f3-4c56-9e03-ab66d9ad4e40.png)

**Comment by CanManftw** [comment]
This bug is in 25.0.4 

![Screenshot from 2023-03-01 14 45 48](https://user-images.githubusercontent.com/119967197/222254937-744fccbb-3a8f-4197-86a0-3942912d8b11.png)

**Comment by joshtrichards** [comment]
Confirmed to still exist today in both NC27 and master.

**Comment by ChristophWurst** [comment]
A fix can be found at https://github.com/nextcloud/server/pull/40675.
