### ISSUE TITLE
NcSelect are broken in dark mode with 25.0.4 rc1

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#36676]
See 
![image](https://user-images.githubusercontent.com/42591237/218282959-c21ed692-d0a4-43c1-93fc-eaf60dc3ef3f.png)

and 

![image](https://user-images.githubusercontent.com/42591237/218282967-1cf5adc1-d26a-45fd-a7c8-73c1a1631737.png)

cc @Pytal 

Also cc @blizzz

**Comment by Pytal** [comment]
Fixed in https://github.com/nextcloud/nextcloud-vue/pull/3707

**Comment by szaimen** [comment]
Thanks Chris! So this requires a new nextcloud/vue release and update in master and stable25 then? Shall I take care of this or is something missing for a new release?

**Comment by Pytal** [comment]
Sure you can go ahead as there is nothing blocking release to my knowledge @szaimen :)

**Comment by szaimen** [comment]
Should be fixed with 25.0.5
