### ISSUE TITLE
Cannot finish update to 11.0.2 using Updater App.

### ISSUE THREAD

**Issue by GrimDemon** [nextcloud/server#3668]
### Steps to reproduce
1. Try yo update using Updater APP from 11.0.1.2 to 11.0.2.
2. Update downloaded and extracted without problems.
3. Cannot update database structure because of "Please use the command line updater because you have a big instance"

### Expected behaviour
Database should update without problems.

### Actual behaviour
"Please use the command line updater because you have a big instance"

### Server configuration
**Operating system:** Webhosting/Linux

**Web server:** Apache 2.4.23

**Database:** MariaDB 10.0.27

**PHP version:** 5.6.30

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 11.0.1.2

**Where did you install Nextcloud from:** Updater App

**The content of config/config.php:**
  'instanceid' => '***',
  'passwordsalt' => '***',
  'secret' => '***',
  'trusted_domains' => 
  array (
    0 => '***',
  ),
  'datadirectory' => '/home/platne/***/public_html/s11/nextcloud/data',
  'overwrite.cli.url' => 'https://***/nextcloud',
  'dbtype' => 'mysql',
  'version' => '11.0.1.2',
  'dbname' => '***',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '***',
  'dbpassword' => '***',
  'logtimezone' => 'Europe/Warsaw',
  'installed' => true,
  'mail_smtpmode' => 'php',
  'maintenance' => false,
  'loglevel' => 2,
  'updater.secret' => '***',

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### Web server error log
N/A

#### Nextcloud log (data/nextcloud.log)
Nothing interesting

**Comment by GrimDemon** [comment]
Unfortunately this information does not helped.
nextcloud/documentation/issues/318

**Comment by nickvergessen** [comment]
You didn't fill out the issue template correctly.
Please post the list of apps you have enabled.
And please also provide the approximated number of users and files in your instance

**Comment by GrimDemon** [comment]
@nickvergessen I'm sorry, I deleted too much content from the issue template.

**Number of users:** 54

**Number of files** ~30, everything in one directory shared with all other users. Seriously it's a fresh installation.

**List of activated apps:**
activity
comments
dav
federatedfilesharing
federation
files
files_pdfviewer
files_sharing
files_texteditor
files_trashbin
files_versions
files_videoplayer
firstrunwizard
gallery
logreader
lookup_server_connector
nextcloud_announcements
notifications
password_policy
provisioning_api
serverinfo
sharebymail
survey_client
systemtags
theming

**Comment by nickvergessen** [comment]
Well the number of users is the point here I guess, if you have more than 50, the web updater is disabled by default

**Comment by LollenJumplan** [comment]
So this is pretty much intended right? Is there a need to leave this open then?

**Comment by GrimDemon** [comment]
@LollenJumplan uh, sorry about that. I forgot about the ticket.
