### ISSUE TITLE
[BITV] Transfer ownership select accessibility

### ISSUE THREAD

**Issue by Pytal** [nextcloud/server#36694]
- [x] Port
https://github.com/nextcloud/server/blob/e01936efa845b579127691bbd41488d997b65440/apps/files/src/components/TransferOwnershipDialogue.vue#L40-L55 https://github.com/nextcloud/server/pull/38306

**Comment by szaimen** [comment]
Fixed with https://github.com/nextcloud/server/pull/38306. Backports?

**Comment by Pytal** [comment]
> Fixed with #38306. Backports?

Nope :)
