### ISSUE TITLE
Correct way to deal with disabled set_time_limit()

### ISSUE THREAD

**Issue by Ko-** [nextcloud/server#3669]
I run Nextcloud 11.0.2 on shared hosting. My error log was completely filled with entries like:

    set_time_limit(): Cannot set max execution time limit due to system policy at /somepath/www/data/apps/dav/appinfo/v2/remote.php#23
    set_time_limit(): Cannot set max execution time limit due to system policy at /somepath/www/data/lib/base.php#646

Apparently the hosting company put `set_time_limit` into the disabled functions in `php.ini`, to which I don't have access.

One workaround is to just comment out all appearances of this function call. Now the log file is usable, but the code integrity check fails and this notifcation keeps popping up. I guess I could disable the integrity check or swap my own signatures and certificate in, but this is far from ideal. Furthermore, the changes would need to be re-applied after every upgrade.

I understand that having no control over PHP's time limit is somewhat dangerous and stuff can break mid-upgrade, but this installation is for some other party and it's hard to convince them to get a VPS.

It's nice that this function call has been made non-blocking a while ago (by prepending `@`), but it would be even nicer if there was some check on the availability of this function.

**Comment by nickvergessen** [comment]
`@` is not enough, just tested. Neither does `function_exists`
We would need to do something like:
```php
		if (strpos(@ini_get('disable_functions'), 'set_time_limit') === false) {
			@set_time_limit(3600);
		}
```
Feel free to make a PR and use that code snippet in all places.
