### ISSUE TITLE
PostgreSQL: installation wizzard claims both the vendor specific and PDO driver are needed

### ISSUE THREAD

**Issue by pmattern** [nextcloud/server#367]
Using PostgreSQL as backend the installation wizzard claims that both the PDO driver ("pdo_pgsql") and the vendor specific driver ("pgsql") are needed. To my knowledge the two drivers are never used in parallel by a single PHP application so there seems to be something wrong either with the wizzard or the PostgreSQL backend itself.

If only `pdo_pgsql` is available the wizzard's initial page doesn't come up but an error message
![nextcloud_postgresql-both-drivers_pdo_pgsql-only](https://cloud.githubusercontent.com/assets/9860801/16734446/d8f16908-4785-11e6-8c28-a83479c8324c.png)
If only `pgsql` is available the initial page does come up but after filing all credentials and clicking "Finish setup" there's
![nextcloud_postgresql-both-drivers_pgsql-only](https://cloud.githubusercontent.com/assets/9860801/16734460/e51f1f72-4785-11e6-8b1e-b8ec994299b4.png)
None of the two messages can be seen when both drivers are available.

Seen running 9.0.52 or 103417f on Arch Linux (PostgreSQL 9.5.3, PHP 7.0.8, Apache 2.4.23 using the PHP module).

**Comment by icewind1991** [comment]
the pgsql driver is currently used during setup, I'll see if I can get rid of it
