### ISSUE TITLE
The "icewind/smb" library throws-out an "unable to create pipe Too many open files" error.

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#3670]
The developer of the audio_player app commented in https://github.com/Rello/audioplayer/issues/152 that this wouldn't be a problem of their app but of the Nextcloud server, because of the used "/apps/files_external/3rdparty/icewind/smb" library.

## Expected behavior
I should be possible to scan for new audio files on e.g. an SMB share from the command line without running into any exception. 

## Current behavior
It isn't possible to scan for new audio files on a SMB share without running into an exception after exactly 198 scanned files. The used "icewind/smb" library throughs-out an `unable to create pipe Too many open files` error.
```
{"reqId":"nenVPAbrqDCLvVpeslMr","remoteAddr":"","app":"PHP","message":"proc_open(): unable to create pipe Too many open files at \/var\/www\/htdocs\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/RawConnection.php#58","level":3,"time":"2017-02-27 18:31:32+01:00","method":"--","url":"\/nextcloud\/occ","user":"--","version":"11.0.2.7"}
{"reqId":"nenVPAbrqDCLvVpeslMr","remoteAddr":"","app":"PHP","message":"include(\/var\/www\/htdocs\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Exception\/ConnectionException.php): failed to open stream: Too many open files at \/var\/www\/htdocs\/nextcloud\/lib\/composer\/composer\/ClassLoader.php#440","level":3,"time":"2017-02-27 18:31:32+01:00","method":"--","url":"\/nextcloud\/occ","user":"--","version":"11.0.2.7"}
{"reqId":"nenVPAbrqDCLvVpeslMr","remoteAddr":"","app":"PHP","message":"include(): Failed opening '\/var\/www\/htdocs\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Exception\/ConnectionException.php' for inclusion (include_path='\/var\/www\/htdocs\/nextcloud\/3rdparty\/pear\/console_getopt:\/var\/www\/htdocs\/nextcloud\/3rdparty\/pear\/pear_exception:\/var\/www\/htdocs\/nextcloud\/3rdparty\/pear\/pear-core-minimal\/src:\/var\/www\/htdocs\/nextcloud\/3rdparty\/pear\/archive_tar:\/var\/www\/htdocs\/nextcloud\/apps:\/var\/www\/htdocs\/nextcloud\/apps2:\/var\/www\/htdocs\/nextcloud\/apps\/files_external\/3rdparty\/google-api-php-client\/src') at \/var\/www\/htdocs\/nextcloud\/lib\/composer\/composer\/ClassLoader.php#440","level":3,"time":"2017-02-27 18:31:32+01:00","method":"--","url":"\/nextcloud\/occ","user":"--","version":"11.0.2.7"}
PHP Fatal error:  Class 'Icewind\SMB\Exception\ConnectionException' not found in /var/www/htdocs/nextcloud/apps/files_external/3rdparty/icewind/smb/src/RawConnection.php on line 60
{"reqId":"nenVPAbrqDCLvVpeslMr","remoteAddr":"","app":"PHP","message":"Class 'Icewind\\SMB\\Exception\\ConnectionException' not found at \/var\/www\/htdocs\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/RawConnection.php#60","level":3,"time":"2017-02-27 18:31:32+01:00","method":"--","url":"\/nextcloud\/occ","user":"--","version":"11.0.2.7"}
```
After this exception is is possible to re-initiate the scan process. Usually the number of unscanned files
will be displayed at the beginning, which shows that it crashes exactly after the same number of scanned files.
```
Final audio files to be processed: 2730
...
Final audio files to be processed: 2532
...
Final audio files to be processed: 2334
...
```
After the crash an instance of the smbclient program is still running and an additional instance will
be started each time the scan process is initiated again. Right after the running instances of the smbclient program have been killed manually the server load returns to normal.

### Steps to reproduce
1. Open a console window and switch to the user under which the web server is running.
2. Start a file scan by executing the following command: `./occ audioplayer:scan --debug <user>`

#### Server Configuration
OS: Linux 3.2.84
Web server: Apache2 2.4.25
Database: MariaDB 5.5.53
PHP version: 5.6.23
Nextcloud version: 11.0.2
Audio Player version: 1.4.1

#### Client Configuration
Browser: Mozilla Firefox 51.0.1
Operating system: Windows 7

**Comment by ChristophWurst** [comment]
cc @icewind1991

**Comment by Rello** [comment]
I just found this advice to use the alternative libsmbclient
https://github.com/owncloud/core/issues/19444

is this still valid, or is there an alternative?

**Comment by nickvergessen** [comment]
This bug here very much sounds like a php limitation on the server. There is a setting in php.ini where you can set the number of allowed open files. I would recommend having a look at that and trying to increase it.

**Comment by j-ed** [comment]
@nickvergessen I've checked the settings using the ` posix_getrlimit()` function and this the result.

```
> php -f ./test-limits.php
Array
(
    [soft core] => 0
    [hard core] => unlimited
    [soft data] => unlimited
    [hard data] => unlimited
    [soft stack] => 8388608
    [hard stack] => unlimited
    [soft totalmem] => unlimited
    [hard totalmem] => unlimited
    [soft rss] => unlimited
    [hard rss] => unlimited
    [soft maxproc] => 63923
    [hard maxproc] => 63923
    [soft memlock] => 65536
    [hard memlock] => 65536
    [soft cpu] => unlimited
    [hard cpu] => unlimited
    [soft filesize] => unlimited
    [hard filesize] => unlimited
    [soft openfiles] => 1024
    [hard openfiles] => 4096
```

**Comment by nickvergessen** [comment]
Yeah I guess the openfiles number might be the problem here, in case the audioplayer app doesnt close the files correctly at the end.

**Comment by Rello** [comment]
Hello,
I am not sure what the App could do here. let me know if you have any suggestion.

in the case of the user, libsmb is not available, so the way via tmpFile has to be chosen.
we just get the localFile and it case its external storage, remove the tmpFile again.
so it should be all external-storage-standard

```
$fileName = $audio->getStorage()->getLocalFile($audio->getInternalPath());				
$ThisFileInfo = $getID3->analyze($fileName);

if (!$audio->getStorage()->isLocal($audio->getInternalPath())) {
	unlink($fileName);
}
```

**Comment by MorrisJobke** [comment]
With Nextcloud 12 the SMB lib was updated: https://github.com/nextcloud/server/pull/2676

Could you check again with Nextcloud 12. Thanks
