### ISSUE TITLE
[Bug]: Broken UI on KDE Plasma online account

### ISSUE THREAD

**Issue by artemanufrij** [nextcloud/server#36708]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

UI seems to be broken on KDE Plasma online account window

### Steps to reproduce

1. Add Nextcloud-Account on KDE Plasma

### Expected behavior

Clean UI

### Installation method

Community Docker image

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
It's not an app bug
```

### Additional info

![image](https://user-images.githubusercontent.com/16517095/218850154-da28b45e-f9ca-43e1-8336-572febc09576.png)

**Comment by szaimen** [comment]
Hi, please report this to the kde project
