### ISSUE TITLE
Lazy js loading overview

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#36728]
- [ ] Allow prefetch with default CSP https://github.com/nextcloud/server/pull/36660
- [ ] Dashboard widgets
  - [ ] User status
  - [ ] Recommendations
  - [ ] Talk
  - [x] Calendar https://github.com/nextcloud/calendar/pull/4968
  - [ ] Mail
  - [x] Activitiy https://github.com/nextcloud/activity/pull/1079
  - [x] Github https://github.com/nextcloud/integration_github/pull/70
  - [x] Mastodon https://github.com/nextcloud/integration_mastodon/commit/98ea154fb03c0069cd4ebd5f35f4be64fbe626ae
  - [x] Zammad https://github.com/nextcloud/integration_zammad/commit/c47e71bf81edf7775139e4d1556c607a4a51961b
  - [ ] Mail
  - [x] Notes https://github.com/nextcloud/notes/pull/964
  - [ ] Tasks
  - [x] Deck https://github.com/nextcloud/deck/pull/4440
- [ ] Files app sidebars
  - [x] https://github.com/nextcloud/spreed/issues/8755
  - [x] Activity: Files sidebar https://github.com/nextcloud/activity/pull/1085
  - [ ] Versions: Files sidebar
- [ ] Documentation for 26 + developer recommenations

**Comment by pulsejet** [comment]
Maybe unrelated to this effort, but the viewer and unsupported browser scripts are loaded synchronously and are super slow. Do you want me to look into this @juliushaertl?

**Comment by juliushaertl** [comment]
Feel free to jump in on those topics, I don't really have much time to focus on this currently. Any contributions are welcome :)

**Comment by szaimen** [comment]
Just wanting to point out that enabling gzip content-encoding in the webserver seems to make a huge difference in terms of transferred js file sizes. core-common.js is then for example reduced from 13.3 MB to 3.5 MB. Dashboard for example loads thus in almost half the time: 7.5s vs 12.5s before in my testing (not the fastest network connection here).

Maybe we should suggest this in the docs at least for js files or does this come with known downsides?

**Comment by szaimen** [comment]
Brotli seems to look even better: reduces core-common.js down to 2.0 MB. I will enable this in AIO by default with https://github.com/nextcloud/all-in-one/pull/2576 for js files.

**Comment by szaimen** [comment]
btw, it looks like for some response content is by default gzip used. Is there a reason this could not be applied by Nextcloud by default for js assets?

**Comment by pulsejet** [comment]
Agree, serving JS without gzip is a disaster. I'd be a bit careful with brotli though. You can't compress brotli on the fly; that'll be too slow. The use-case for brotli is serving _pre-compressed_ artifacats, so need to make sure that is the case.

**Comment by pulsejet** [comment]
We can't do anything about viewer here since it has some side effects (hooks), but lazy loading the components themselves seems to do the trick for performance. https://github.com/nextcloud/viewer/pull/1675
