### ISSUE TITLE
Webdav latest stable build

### ISSUE THREAD

**Issue by ddanielww** [nextcloud/server#3672]
Sabre\DAV\Exception: HTTP/1.1 500 No subsystem set a valid HTTP status code. Something must have interrupted the request without providing further detail.

Is this a known issue with webdav and windows as the client ?

Read online upgrading from php 7 to php 7.1 version was a possible fix ?

**Comment by benediktg** [comment]
You might want to have a look at #2887 and #3370. 😉

**Comment by nickvergessen** [comment]
Or duplicate of https://github.com/nextcloud/server/issues/3628

**Comment by ddanielww** [comment]
This issue has not really been fixed ? Not sure why it worked in nextcloud 10 but not 11.

Can't nextcloud fix this issue in a new patch ?

**Comment by nickvergessen** [comment]
The issue is not fixed intentionally yet.
But there are 3 related issues open, no need to have a forth one.
