### ISSUE TITLE
[Bug]: Avatars don't show initials nor pictures in nextcloud 25 

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/server#36722]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

<img width="410" alt="Screenshot 2023-02-15 at 09 48 43" src="https://user-images.githubusercontent.com/26852655/218993072-09f1e7b1-ed04-4f6b-8d68-d2bd91e0242d.png">

### Steps to reproduce

1. Open files or talk 

### Expected behavior

People's avatars should be have either initials or a picture

### Actual behavior

Only the backgrounds are visible
<img width="482" alt="Screenshot 2023-02-15 at 09 50 15" src="https://user-images.githubusercontent.com/26852655/218995474-de98ba84-f325-4a99-ba13-3bb398dee5b6.png">
 

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Only the ones that come with docker aio, I'm having trouble executing the occ command within my container, but those are the only ones.
```

**Comment by szaimen** [comment]
Hi, is this an alpine based nextcloud instance with imaginary installed and php 8.0?

**Comment by marcoambrosini** [comment]
This is my private docker AIO and also a customer reported this

**Comment by szaimen** [comment]
Already tracked in https://github.com/nextcloud/all-in-one/issues/1628 and https://github.com/nextcloud/server/issues/34755

**Comment by szaimen** [comment]
Btw, see https://github.com/nextcloud/all-in-one#how-to-run-occ-commands for how to run occ commands in aio
