### ISSUE TITLE
[Bug]: Quota misreported using API when logging in as admin with app password / token

### ISSUE THREAD

**Issue by jensb** [nextcloud/server#36760]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The API call does not report the correct quota for users when the admin logs in using an app token which has no "filesystem access". Also the reported values are nonsense instead of an error response.

I think that querying user quotas, which are stored in the database and not on the filesystem, should not require app tokens with "filesystem access". Only accessing or modifying user files and data should.
If there are technical limitations to providing quotas without accessing the disks, then **at least** the API response should indicate an "access denied" kind of message or leave the quota block out altogether so that the API client does not accidentally continue working with incorrect values.

The relevant API output (XML snippet) with incorrect quota:
```
<quota>
   <free>-2</free>
   <used>0</used>
   <total>-2</total>
   <relative>0</relative>
   <quota>-3</quota>
</quota>
```

I propose something like the following response instead of the above if quotas cannot be reported without "filesystem access":
```
<quota>
  <error>Authenticated without filesystem access</error>
</quota>
```

I am using the following Ruby code to query the API:

```
 require 'httparty'
 res = HTTParty.get("https://MY_NC_DOMAIN/ocs/v1.php/cloud/users/MY_USER",
   { headers: { 'OCS-APIRequest' => 'true' },
     basic_auth: {username: 'Admin', password: 'TOKEN_OR_PASSWORD' }
   } )
  res["ocs"]["data"]["quota"]
```

### Steps to reproduce

1. Setup Nextcloud 25.0.3 (current release)
2. Add admin app token for login without "file system access"
3. Add some users with quota
4. Try above code snippet to query users quota, once with real admin password and once with admin app token.

Result: With the app token, the quota display is incorrect (-2 and -3 as above).
Using the real admin password, the quota display is correct.

### Expected behavior

Quota should be reported correctly in both cases.

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.2.3",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - recommendations: 1.4.0
  - related_resources: 1.0.3
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - suspicious_login
  - twofactor_totp
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Logging area was empty (no warnings or errors)
```

**Comment by joshtrichards** [comment]
>  Also the reported values are nonsense instead of an error response.

The reported values are the constants from here:

https://github.com/nextcloud/server/blob/890c5b8594fdebb221071bffbd17276cd3e6a4eb/lib/public/Files/FileInfo.php#L54-L63

- Quota is set to SPACE_UNLIMITED (-3) for this user. [looked up from the db]

- Space can't be computed for this user aka SPACE_UNKNOWN (-2) [looked up from the filesystem, if accessible]

With FS access:

```
    <quota>
      <free>587580518400</free>
      <used>3309024808</used>
      <total>590889543208</total>
      <relative>0.56</relative>
      <quota>-3</quota>
    </quota>
```

Without FS access:

```
    <quota>
      <free>-2</free>
      <used>0</used>
      <total>-2</total>
      <relative>0</relative>
      <quota>-3</quota>
    </quota>
```

> If there are technical limitations to providing quotas without accessing the disks, then at least the API response should indicate an "access denied" kind of message or leave the quota block out altogether so that the API client does not accidentally continue working with incorrect values.

I think you can just check for `total` being `-2` since indicates unknown, in this case because of a lack of filesystem access. So the quota *setting* can be looked up, but the current *usage* cannot if the token/user lacks filesystem access.
