### ISSUE TITLE
Better error handling in occ

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#368]
I'm aware of at least 2 occ commands which print a "success" message even if the operation fails, the one which writes the htaccess and the one which signs apps.

This should be fixed as it's very confusing to users.

Is this a global occ issue or should it be handled on a case by case basis?
Maybe it's a combination of both, some global catcher and making sure each command exits with the proper code.

**Comment by MorrisJobke** [comment]
@LukasReschke: your commands 😝

**Comment by nickvergessen** [comment]
I'll take a look

**Comment by MorrisJobke** [comment]
> htaccess

Fixed: https://github.com/nextcloud/server/blob/5bad417e57231e129b7113ebb110b1f2b282f349/core/Command/Maintenance/UpdateHtaccess.php#L46



> signs apps

Fixed: https://github.com/nextcloud/server/blob/5bad417e57231e129b7113ebb110b1f2b282f349/core/Command/Integrity/SignApp.php#L109
