### ISSUE TITLE
[Bug]: Password textbox too small after generating new app password

### ISSUE THREAD

**Issue by sedrubal** [nextcloud/server#36822]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When you create a new app token, the text field where the token is displayed is (unnecessarily) too small to show the entire generated password.

### Steps to reproduce

1. Go to `/settings/user/security`
2. Under "Devices & sessions" enter a new app name and click on <kbd>Create new app password</kbd>
3. Check the password text box which is too small

![app-token-field-too-small](https://user-images.githubusercontent.com/5571650/220844017-8071af0b-f4a8-4fab-b863-2e4de0b13e55.png)

### Expected behavior

As the app password is generate and has always the same length, the width of the text box should be set to a value that is big enough so that the password is shown completely.

### Installation method

Community Docker image

### NC Version

25.0.3

### Operating system

Other

### PHP engine version

None

### Web server

nginx

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
This information is not relevant
```

**Comment by sedrubal** [comment]
25.0.3

**Comment by joshtrichards** [comment]
Fixed in #42334
