### ISSUE TITLE
Add Icons to Devices/Sessions on Personal Page

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#3683]
We could add some logos for browsers and devices to the personal page so that the devices could be better recognized by the users 😉 

Example for Dropbox:

<img width="1009" alt="bildschirmfoto 2017-03-02 um 17 52 29" src="https://cloud.githubusercontent.com/assets/19711361/23517627/36495220-ff71-11e6-9e68-c51c03b7ebda.png">
<img width="843" alt="bildschirmfoto 2017-03-02 um 17 53 06" src="https://cloud.githubusercontent.com/assets/19711361/23517638/3d5e95de-ff71-11e6-920f-d4ec898a2c04.png">

I remember that this was in the initial drafts of this feature but ... well 😅 

cc @jancborchardt @nextcloud/designers

**Comment by MariusBluem** [comment]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=42608620)](https://www.bountysource.com/issues/42608620-add-icons-to-devices-sessions-on-personal-page?utm_source=42608620&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by jancborchardt** [comment]
@MariusBluem maybe collect some icons from https://thenounproject.com or somewhere like that, and fiddle with opening a pull request? :)

**Comment by fti7** [comment]
+1
Also a column with the IP Address + (Optional the Geo Location of the IP) would be interesting to see 😄
