### ISSUE TITLE
High number of db queries while preview generation

### ISSUE THREAD

**Issue by chr1s692** [nextcloud/server#3685]
Hey guys,
I have a large collection of pictures (~20.000) . I used the app "Preview Generator" to pre generate the thumbnails, so the directory appdata/preview contains a lot (more) files.

Meanwhile uploading a new single(!) file takes about 1-2 minutes. By using the webfrontend or the app (android) the upload stops at 100% (for 1-2 minutes).
On my Server the apache, mysql and redis processes consume a lot of cpu. I activated the query log of the mysql server and recognized the following db queries:
```
.....
                 1626 Query     SELECT `fileid`, `storage`, `path`, `parent`, `name`, `mimetype`, `mimepart`, `size`, `mtime`,
                                           `storage_mtime`, `encrypted`, `etag`, `permissions`, `checksum`
                                FROM `oc_filecache` WHERE `storage` = '3' AND `path_hash` = '9cefee3881c46e587b4d447f4cee6483'
                 1626 Query     SELECT `fileid`, `storage`, `path`, `parent`, `name`, `mimetype`, `mimepart`, `size`, `mtime`,
                                           `storage_mtime`, `encrypted`, `etag`, `permissions`, `checksum`
                                FROM `oc_filecache` WHERE `storage` = '3' AND `path_hash` = '8a00abec3e0e285ae578047595dad78d'
                 1626 Query     SELECT `fileid`, `storage`, `path`, `parent`, `name`, `mimetype`, `mimepart`, `size`, `mtime`,
                                           `storage_mtime`, `encrypted`, `etag`, `permissions`, `checksum`
                                FROM `oc_filecache` WHERE `storage` = '3' AND `path_hash` = '8477aeebb9a90167d606de0235e170db'
                 1626 Query     SELECT `fileid`, `storage`, `path`, `parent`, `name`, `mimetype`, `mimepart`, `size`, `mtime`,
                                           `storage_mtime`, `encrypted`, `etag`, `permissions`, `checksum`
                                FROM `oc_filecache` WHERE `storage` = '3' AND `path_hash` = '5478eb60c9479ebfe3ee296fc3f41211'
                 1626 Query     SELECT `fileid`, `storage`, `path`, `parent`, `name`, `mimetype`, `mimepart`, `size`, `mtime`,
                                           `storage_mtime`, `encrypted`, `etag`, `permissions`, `checksum`
                                FROM `oc_filecache` WHERE `storage` = '3' AND `path_hash` = 'c3e5b0a811d4d9c92e50d7e4cc895241'
....
```
The whole dimension can be taken from the attachment. Actual there are about 40.000 of these queries. That's really pain!

### Steps to reproduce
1. have a lot of pictures
2. use the app "Preview Generator"
3. upload a file (webfrontend or android app)

### Expected behaviour
???

### Actual behaviour
???

### Server configuration
**Operating system**:
Linux version 3.14.79-105 (root@a53_b1) (gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.1) ) #1 SMP PREEMPT Tue Jan 31 21:16:32 BRST 2017

**Web server:**
Server version: Apache/2.4.18 (Ubuntu)

**Database:**
mysql Ver 15.1 Distrib 10.0.29-MariaDB, for debian-linux-gnu (aarch64) using readline 5.2

**PHP version:**
PHP 7.0.16-3+deb.sury.org~xenial+1 (cli) (built: Feb 22 2017 10:05:52) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 11.0.2 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install of Nextcloud 11.0.1 (stable) -> upgraded to Nextcloud 11.0.2 (stable)

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - previewgenerator: 1.0.1
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - audioplayer
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml

```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocxhdj3iwdd0",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.104",
            "nextcloud.fritz.box",
            "nextcloud.local"
        ],
        "datadirectory": "\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/192.168.1.104",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "loglevel": 1,
        "logtimezone": "Europe\/Berlin",
        "logfile": "\/nextcloud\/data\/nextcloud.log",
        "log_rotate_size": 10485760,
        "cron_log": true,
        "filesystem_check_changes": 1,
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\Movie"
        ],
        "maintenance": false,
        "theme": ""
    }
}

```
</details>

**Are you using external storage, if yes which one:** some directories are on local storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 

**Operating system:** Ubuntu

[queries.txt](https://github.com/nextcloud/server/files/814685/queries.txt)

**Comment by chr1s692** [comment]
Here some more information:
After activating the slow log in mysql, the following was logged:
`# Time: 170301 18:45:40
# User@Host: nextcloud[nextcloud] @ localhost []
# Thread_id: 72  Schema: nextcloud  QC_hit: No
# Query_time: 10.797222  Lock_time: 0.000405  Rows_sent: 349891  Rows_examined: 349891
SET timestamp=1488390340;
SELECT `fileid`, `storage`, `path`, `parent`, `name`,
                                `mimetype`, `mimepart`, `size`, `mtime`, `encrypted`,
                                `etag`, `permissions`, `checksum`
                        FROM `oc_filecache`
                        WHERE `storage` = '3' AND `name` COLLATE UTF8_general_ci LIKE '%%';
`

It seems to be the function, with calls the function "search" in the file "lib/private/Files/Cache/Cache.php" while generating a preview thumbnail, responsible for the high number of queries.

I don't have a profound knowledge about the code of nextcloud, can anybody help me?

**Comment by MorrisJobke** [comment]
cc @rullzer @icewind1991

**Comment by rullzer** [comment]
Well the preview generator app does doe a lot of looping over files. And the preview generation process also checks if a file exists etc. So there is a lot of queries and I/O going on.

What kind of system are you running on?

**Comment by chr1s692** [comment]
While running the preview generator app i think it's normal to have a lot oft queries.Thats not the problem Herr.

After the app finished generating thumbnails and no additional processes were running, I uploaded one new file. The upload of this single new file generates these queries - not the generator app. As i also noticed these queries startet when the file upload reach 100%. I think the problem might be at the on demand thumbnail generation.

Current system: odroid c2

**Comment by chr1s692** [comment]
Hello guys,
After i updated to 11.0.3 i have still the same problem.
I also noticed that the same problem occure, when i open the app "store".

To avoid misunderstandings: its NOT the preview generation app, which generates that high number of queries. I think its the preview handling in the core of the nextcloud-server. 

Does somebody has any idea?

**Comment by rullzer** [comment]
@chr1s692 ok lets try this:

1. Open the web interface
2. Open your network console
3. navigate to an entry you want to get a preview from
4. See one of the urls to <host>/core/preview.png? come by. Copy it
5. Enable the query log on your db
6. Go to the url obtained in 4 and hard refresh
7. Stop the query log
8. Post the query log :wink:

**Comment by chr1s692** [comment]
@rullzer : When I open <server>/core/preview.png? I only get "[]". Can you explain this step more detailed for me? 0:-)
thank you

**Comment by chr1s692** [comment]
so what i've done:
1. navigate to the folder "test"
2. uploaded a new picture
3. opened it in "fullscreen" and copied the url `<server>/apps/files/?dir=/Bilder/test&fileid=1512143#/Bilder/test/P1030671.JPG`
4. started query log
5. open that url again / refresh
6. wait until queries stopped in logfile
7. stop query log

[query.txt](https://github.com/nextcloud/server/files/990560/query.txt)

**Comment by rullzer** [comment]
@chr1s692 aaah no it should be a full request to the preview endpoint. But let me take a look at the query log

**Comment by rullzer** [comment]
@chr1s692 how many files are in your 'Bilder/test' dir?

**Comment by chr1s692** [comment]
@rullzer there are 10 files/pictures in 'Bilder/test'

**Comment by rullzer** [comment]
Some of your requests seem to have a really high number of queries indeed. Is that folder on external storage or anything?

Since I just have locally only ~30 queries for a single preview image

**Comment by chr1s692** [comment]
The picture I opened is local. 
I use the plugin for external storage to share the folder "Gemeinsame Dateien" with any user in the group "home" by default. I created that folder as a subfolder of the datafolder.

So my setup looks as follows:
Data folder: /nextcloud/data
"External Folder": /nextcloud/data/shared_files (logical foldername = "Gemeinsame Dateien")

**Comment by chr1s692** [comment]
@rullzer: any other ideas? 
I reinitialized my environment (deleted the complete database, deleted all php files) and startet to generate previews.
The folder for the "external folder" is now "/nextcloud/data_external"

Same Problem again :/

**Comment by rullzer** [comment]
@chr1s692 could you verify on a setup without external folders?

**Comment by chr1s692** [comment]
@rullzer: i can try...probably at the weekend.
Until now the preview generation app only generated pictures from local storage (verified from the output of the cli command).

**Comment by chr1s692** [comment]
@rullzer Yesterday i created a new environment without the external storage app enabled. 
After some preview pictures were generated over night, the same problem occurred again :(

I looked at the database and the query.txt and perhaps it can be useful:
The queries that occured a look have all "`storage` = '3'". Storage "3" is "local::/nextcloud/data/" (in my case the datafolder of nextcloud)
`+-----------------------------------------------+------------+-----------+--------------+
| id                                            | numeric_id | available | last_checked |
+-----------------------------------------------+------------+-----------+--------------+
| home::admin                                   |          1 |         1 |         NULL |
| 1                                             |          2 |         1 |         NULL |
| local::/nextcloud/data/                       |          3 |         1 |         NULL |
| 4                                             |          5 |         1 |         NULL |
| home::christian                               |          6 |         1 |         NULL |
| 6                                             |          7 |         1 |         NULL |
| home::christina                               |          9 |         1 |         NULL |
`
Before the queries start, there is always the following sql statement 
> SELECT `id`, `numeric_id`, `available`, `last_checked` FROM `oc_storages` WHERE `id` IN ('local::/nextcloud/data/')
I tried to search that statement in the php code without success

I also noticed that these queries occur, when i open the "app store"

**Comment by chr1s692** [comment]
@rullzer: good news - currently the error no longer occurs. so what i've done:
- upgraded to nextcloud 12 (the high number of queries still occured)
- run the cli commands:
`sudo -u www-data php occ files:scan --all`
`sudo -u www-data php occ files:scan-app-data` 
=> queries are gone :)
