### ISSUE TITLE
[Bug]: Files reload via top icon leads to log-out

### ISSUE THREAD

**Issue by mkrecek234** [nextcloud/server#36891]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Browsing in files and clicking the Files icon in top bar, leads to log-out of user
Seen after upgrading to 25.0.4; upgrading then to latest v26 beta yesterday did not fix the issue, it remained the same. 

### Steps to reproduce

1. You browse through various folders
2. Then you click on the Files icon in the top menu
3. After some loading, you end-up at the login-page

### Expected behavior

You return to root folder of the files app.

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a minor version (ex. 22.2.3 to 22.2.4)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.habelschwerdt.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.0.7",
        "overwrite.cli.url": "https:\/\/cloud.habelschwerdt.de",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "overwritehost": "cloud.habelschwerdt.de",
        "overwriteprotocol": "https",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "127.0.0.1",
                11211
            ]
        ],
        "default_phone_region": "DE",
        "updater.release.channel": "beta",
        "theme": "",
        "loglevel": 0,
        "app_install_overwrite": [
            "files_mindmap",
            "files_linkeditor",
            "polls",
            "extract",
            "appointments",
            "apporder",
            "talk_matterbridge",
            "integration_whiteboard",
            "news",
            "approval",
            "files_trackdownloads",
            "quota_warning"
        ],
        "maintenance": false,
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.18.0
  - admin_audit: 1.16.0
  - appointments: 1.14.11
  - apporder: 0.15.0
  - approval: 1.0.12
  - bruteforcesettings: 2.6.0
  - circles: 26.0.0-beta2
  - cloud_federation_api: 1.9.0
  - collectives: 2.3.0
  - comments: 1.16.0
  - contacts: 5.1.0
  - contactsinteraction: 1.7.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - deck: 1.9.0-beta.1
  - external: 5.1.0
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_automatedtagging: 1.16.0
  - files_linkeditor: 1.1.13
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trackdownloads: 1.11.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - firstrunwizard: 2.15.0
  - flow_notifications: 1.6.0
  - integration_whiteboard: 0.0.15
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - news: 21.0.0-beta1
  - nextcloud_announcements: 1.15.0
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - password_policy: 1.16.0
  - polls: 4.1.2
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - quota_warning: 1.15.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0-alpha1
  - richdocuments: 8.0.0-beta.1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - sociallogin: 5.4.1
  - spreed: 16.0.0-beta.2
  - support: 1.9.0
  - systemtags: 1.16.0
  - talk_matterbridge: 1.25.2-1
  - text: 3.7.1
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - twofactor_totp: 8.0.0-alpha.0
  - updatenotification: 1.16.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - workflowengine: 2.8.0
Disabled:
  - backup: 1.2.0 (installed 1.2.0)
  - calendar: 4.2.4 (installed 4.2.4)
  - encryption: 2.14.0
  - extract: 1.3.5 (installed 1.3.5)
  - files_external: 1.18.0 (installed 1.17.0)
  - files_mindmap: 0.0.27 (installed 0.0.27)
  - mail: 2.2.4 (installed 2.2.4)
  - phonetrack: 0.7.4 (installed 0.7.4)
  - photos: 2.2.0 (installed 1.4.0)
  - survey_client: 1.14.0 (installed 1.13.0)
  - suspicious_login: 4.4.0 (installed 4.3.0)
  - timemanager: 0.3.4 (installed 0.3.4)
  - timetracker: 0.0.77 (installed 0.0.77)
  - user_ldap: 1.16.0
  - workflow_pdf_converter: 1.10.0 (installed 1.10.0)
  - workflow_script: 1.10.0 (installed 1.10.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by skjnldsv** [comment]
Hum, I cannot reproduce the issue :thinking: 
Clicking this? 
![image](https://user-images.githubusercontent.com/14975046/222073906-f58935e8-a491-46ff-9dd5-bd7cd7efa0f6.png)

**Comment by mkrecek234** [comment]
@skjnldsv Correct - the issue started after the update that NC seems to log-out especially when browsing/clicking there. Could well be my installation got corrupted through the minor update process. The error log does not show anything that is related to a log-out. The log-out happens independent of if I am logged in as a NC user, or a social-login user.

**Comment by skjnldsv** [comment]
I personally don't see how that could happen, so i'd like to dive a bit more into this.
Can you share your browser log before the logout happens maybe?
Since there is a page change, you might want to enable the "preserve log" checkbox on the console settings
![image](https://user-images.githubusercontent.com/14975046/222111292-242d80c3-0eda-40d1-ba6e-ee4de912eb09.png)

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by skjnldsv** [comment]
Other than this, nothing in the nextcloud log file?

**Comment by mkrecek234** [comment]
Nothing in the log file, just a redirect to the login-window. I will continue to keep an eye on it. Right now mysterically, the issue does not happen...

**Comment by skjnldsv** [comment]
> Nothing in the log file, just a redirect to the login-window. I will continue to keep an eye on it. Right now mysterically, the issue does not happen...

A classic ahah. No worries, feel free to re-open if the issue pops up again!

**Comment by mkrecek234** [comment]
This is happening again on a completely fresh install NC25 final release with a freshly setup social_login (connected to OAuth on mailcow). Still no log entry, and no JS console error, only warnings unrelated. Anyone else experiencing this? It makes NC web GUI unusably currently.

**Comment by mkrecek234** [comment]
Can we reopen the issue please?
