### ISSUE TITLE
./.htaccess: values of directives involved in uploading not suitable

### ISSUE THREAD

**Issue by pmattern** [nextcloud/server#369]
The values of PHP directives `upload_max_filesize`, `post_max_size` and `memory_limit` should increase in this order but the current `./.htaccess` is setting rather the opposite.
```
<IfModule mod_php7.c>
  php_value upload_max_filesize 513M
  php_value post_max_size 513M
  php_value memory_limit 512M
  [...]
```
(same values for mod_php5.c).

**Comment by nickvergessen** [comment]
the order is the same as you mention?

**Comment by pmattern** [comment]
Yes. The order is described e. g. in [section post_max_size](http://php.net/manual/en/ini.core.php#ini.post-max-size) of the PHP Manual.

**Comment by pmattern** [comment]
According to the PHP manual section linked [above](https://github.com/nextcloud/server/issues/369#issuecomment-232157451) the order should be `$memory_limit > $post_max_size > $upload_max_filesize` which isn't met by #1395.

But there's another issue worth considering, IMO.
If the difference between `$memory_limit` and `$post_max_size` / `$upload_max_filesize` is rather small not much memory is remaining for the application itself when files of the maximum size are uploaded which makes it seem likely the application may run into trouble then.
Documentation about an optional minimum size of this difference seems hard to find but e. g. this
```
php_value   upload_max_filesize   5M
php_value   post_max_size         6M
php_value memory_limit 64M
```
is what [Roundcube](https://github.com/roundcube/roundcubemail) is setting by default. Note the rather large difference between `$memory_limit` and `$post_max_size` / `$upload_max_filesize`.

**Comment by nickvergessen** [comment]
Right, I missed the post > upload implication. @pmattern mind creating a PR?
I'd just use 512 > 511 > 510 for now

**Comment by pmattern** [comment]
>  @pmattern mind creating a PR? I'd just use 512 > 511 > 510 for now

Basically I sure could. But I fear I'd need some advice on this signing magic as seen in `tests/lib/IntegrityCheck/CheckerTest.php` in #1395 and you're probably quicker off writing the comlementary PR yourself then.

**Comment by michag86** [comment]
I don't think that it is really required to set memory_limit > post_max_size.
I run a system with 2GB Ram and 1GB swap with this values:
post_max_size 4097MB
upload_max_filesize 4096MB
memory_limit 512MB

I can upload 4GB files via web interface without problems.

Ok the the documentation says memory_limit > post_max_size. But if you want to upload very large files and set the memory_limit larger than ram+swap, that makes no sense.

Part in documentation about memory_limit:
"This sets the maximum amount of memory in bytes that a script is allowed to allocate. This helps prevent poorly written scripts for eating up all available memory on a server." [Source](http://php.net/manual/en/ini.core.php#ini.memory-limit)
