### ISSUE TITLE
Sort shares by title and then creation date

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#36906]
![image](https://user-images.githubusercontent.com/14975046/221916922-ca7d14cd-b4a7-4e9a-acf5-e6e64fb1cffd.png)

Currently they are not sorted at all
https://github.com/nextcloud/server/blob/078203afeab667cbe1ffbcfa76a635e1bf59b9d3/apps/files_sharing/src/views/SharingTab.vue#L264-L265

**Comment by oraliahdz** [comment]
HI, I would like to help. Is this still available?

**Comment by tarunsamanta2k20** [comment]
I'd like to work on this issue. Please assign it to me.

**Comment by skjnldsv** [comment]
To both of you , you don't have to ask, feel free to fork and fix the issue, then create a pull request :)
https://github.com/nextcloud/server#contribution-guidelines-

**Comment by tarunsamanta2k20** [comment]
@skjnldsv how to run on localhost? Please type the command here.

**Comment by skjnldsv** [comment]
> @skjnldsv how to run on localhost? Please type the command here.

https://github.com/nextcloud/server#join-the-team-

**Comment by tarunsamanta2k20** [comment]
@skjnldsv please check my latest pr as I couldn't run it on localhost

**Comment by skjnldsv** [comment]
Create a file, share it multiple times with different users
Click the share button on the file
- https://docs.nextcloud.com/server/stable/admin_manual/configuration_user/user_configuration.html#creating-a-new-user
- https://docs.nextcloud.com/server/stable/user_manual/en/files/access_webgui.html
- https://docs.nextcloud.com/server/stable/user_manual/en/files/access_webgui.html#sharing-status-icons
- https://docs.nextcloud.com/server/stable/user_manual/en/files/sharing.html

**Comment by tarunsamanta2k20** [comment]
@skjnldsv


now tell me what i have to do? 
![image](https://user-images.githubusercontent.com/55488549/226105054-c09efe85-9521-4691-bb2b-b1caaf1e8b34.png)

**Comment by tarunsamanta2k20** [comment]
@skjnldsv 
![image](https://user-images.githubusercontent.com/55488549/226105569-7e370fcd-1914-49d5-bcbd-ef333aa82a25.png)

**Comment by tarunsamanta2k20** [comment]
@skjnldsv 

I believe it's working. You can merge now.

**Comment by skjnldsv** [comment]
![image](https://user-images.githubusercontent.com/14975046/226110354-bab1d0bc-5f1f-43f9-bcc1-2c35c302e361.png)
This doesn't look alphabetically sorted

**Comment by tarunsamanta2k20** [comment]
@skjnldsv  it will not look alphabetically sorted as temp2 is created after temp1. So first Sort will be according to the title, then by creation time.

**Comment by tarunsamanta2k20** [comment]
can we connect via chat?

**Comment by tarunsamanta2k20** [comment]
Do you want only alphabetically sorted?

**Comment by tarunsamanta2k20** [comment]
@skjnldsv please connect with me via Google chat.

email id: tsamanta296@gmail.com

**Comment by tarunsamanta2k20** [comment]
Because i want to complete this issue by EOD.

**Comment by tarunsamanta2k20** [comment]
@skjnldsv  i got your point.
