### ISSUE TITLE
[BITV] 9.1.3.1b/2.1 - "Contacts" menu - The list of contacts represents a list, but it was not marked as such with a list item using HTML or ARIA. (9)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#36916]
- [ ] Fix
- [ ] Backport

<img width="424" alt="a09c0e05fb4977cb4d22a782c7c83883" src="https://user-images.githubusercontent.com/1315170/221930814-ec0f8216-e30b-4898-bd0c-755e9c0993d2.png">

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-1d5eadb58d-v2-n1

</details>

- [ ] 9\.1.3.1b/3.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-1d5eadb58d-v3-n1
- [ ] 9\.1.3.1b/4.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-1d5eadb58d-v4-n1
- [ ] 9\.1.3.1b/5.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-1d5eadb58d-v5-n1
- [ ] 9\.1.3.1b/6.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-1d5eadb58d-v6-n1
- [ ] 9\.1.3.1b/7.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-1d5eadb58d-v7-n1
- [ ] 9\.1.3.1b/8.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-1d5eadb58d-v8-n1
- [ ] 9\.1.3.1b/9.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-1d5eadb58d-v9-n1
- [ ] 9\.1.3.1b/10.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-1d5eadb58d-v10-n1

**Comment by JuliaKirschenheuter** [comment]
Fix: 

- [ ] https://github.com/nextcloud/server/pull/37421

Backports:
