### ISSUE TITLE
[BITV] 9.1.3.1a/6.3 - It is recommended to remove the "h1" heading "Nextcloud's homepage" and mark up the "h2" heading "Personal info" as "h1" instead. (1)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#36914]
- [x] Fix
- [x] Backport

![ea791921f8d91989b62585d40226bf0f](https://user-images.githubusercontent.com/1315170/221929095-be918e62-4c20-4ade-a09d-7847b13b51c9.png)

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-be75bbae42-v6-n3

</details>

**Comment by JuliaKirschenheuter** [comment]
Related (same) issue is here: https://github.com/nextcloud/server/issues/35626
