### ISSUE TITLE
[BITV] 9.1.3.1a/6.2 - The navigation on the left side is visually structured clearly by the headings "Personal" and "Administration," but these two headings were not marked up as such with a heading markup. (1)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#36913]
- [ ] Fix
- [ ] Backport

![ea791921f8d91989b62585d40226bf0f](https://user-images.githubusercontent.com/1315170/221928471-8792cdf7-a072-428b-be81-9398d9ad170b.png)

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-be75bbae42-v6-n2

</details>

**Comment by JuliaKirschenheuter** [comment]
@AndyScherzinger  Moving this issue to review session: 4

**Comment by JuliaKirschenheuter** [comment]
possible solution will be done as suggested here https://github.com/nextcloud/server/issues/36915#issuecomment-1463448790 
Closing issue for not having a duplicate.
