### ISSUE TITLE
"fseek() stream does not support seeking" when libsmbclient-php not installed?

### ISSUE THREAD

**Issue by Rello** [nextcloud/server#3691]
Within Audio Player we changed the getID3 extraction from LocalFile (and tmpFile for external files) to directly accessing the files via stream.

```
...
$userView = $this->rootFolder->getUserFolder($this -> userId);
$audio = $userView->searchByMime(...
in getID3:
fseek($audio->fopen('r'), $this->info['avdataoffset']);
...
```

when scanning the audio files, I am receiving issues in the nextcloud.log for every file which is being accessed via SMB
`{"reqId":"H6fC\/xIXGgi+OJBQFDIp","remoteAddr":"","app":"PHP","message":"fseek(): stream does not support seeking at \/var\/www\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/streams\/src\/Wrapper.php#74","level":3,"time":"2017-03-03T06:54:26+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
`

Analysis showed that it seems to be related libsmbclient. once it is installed, fseek access is working correctly and fast..

What is the way to go from here?
- due to the importance of libsmbclient, should it be included in the checks of NC?
- on the other hand declaring a manual install as required might bring issues on shared hosts
- or would every App need to check the availability of the feature and step back to the tmpFile logic in case it is not installed?

I see two possibilities:
- check for fseek possibilities similar as the encryption utils does:
```
$handle = $this->view->fopen($path, 'r');
if (is_resource($handle)) {
if (fseek($handle, -24, SEEK_END) === 0) {
```

- or should apps go via the NativeServer from @icewind1991 to recognize the installed lib?
```
use Icewind\SMB\NativeServer;
if (Server::NativeAvailable()) {
```

what is the best was to approach this?
I think using fseek compared to copying the whole file to tmp is very important to keep NC server on low resource needs.

I think @gnarula has the same issue in his Music app

**Comment by Rello** [comment]
topic is "solved"
I had a difference between the test-instances. on the NC-Installation, libsmbclient-php was missing

**Comment by Rello** [comment]
reopened and rephrased, as a proper solution/error handling could be beneficial

**Comment by Rello** [comment]
https://docs.nextcloud.com/server/11/admin_manual/configuration_files/external_storage/smb.html?highlight=smb

"The PHP smbclient module is preferred, but either will work"

**Comment by nickvergessen** [comment]
So your suggestion is to update the docs?

**Comment by Rello** [comment]
Hello,
I am not sure.

in the Install docu, it is mentioned (in earlier versions even with a stronger wording).
https://docs.nextcloud.com/server/11/admin_manual/configuration_files/external_storage/smb.html?highlight=smb

So NC is supposed to work with both implementations - but now there is a case where this is not true if I understand the issue correctly.

So the question is: 

- Does this library need to be "mandatory" and as a consequence part of the Admin-Page-Checks?
- Or would the apps need to take care of this on their own? then the question would be on how to do it  the best way

**Comment by nickvergessen** [comment]
@icewind1991 can you maybe comment on this?

**Comment by icewind1991** [comment]
fseek should be avoided where possible since multiple external storage backends to do not support seeking on streams.

**Comment by Rello** [comment]
ok, good to know.
for streaming audio files I think SMB is the most common version (local NAS).

The win for using fseek on SMB (with the library installed) is enormous. We have users with several 1.000 audio files and currently they all are copied over the network via tmpFile.
When extending to FLAC, the file sizes will raise even more.

I just tested locally to check for fseek capability for every file being accessed:
if yes, use the fast way.
if not, use the slow way.

do you think it would be an usable compromise to gain at least some performance where libsmb is installed?
```
$handle = $audio->fopen('rb');
if (fseek($handle, -24, SEEK_END) === 0) {
```

**Comment by gnarula** [comment]
> fseek should be avoided where possible since multiple external storage backends to do not support seeking on streams.

TIL. Guess we need to add some checks in Music. Does /OCP/Files/File::fopen() return a handle for resources which don't support streaming?

> The win for using fseek on SMB (with the library installed) is enormous. We have users with several 1.000 audio files and currently they all are copied over the network via tmpFile.
When extending to FLAC, the file sizes will raise even more.

Couldn't agree more. Music (actually getID3) uses it extensively for thumbnail generation and metadata parsing.

**Comment by Rello** [comment]
@gnarula 

I decided to go via checking for a valid fseek-return. from current tests, it works in the combinations I could test. 

first I check for `@fseek($handle, -24, SEEK_END) === 0`. if yes, provide the $handle to getID3.
if no, I go via `$audio->getStorage()->getLocalFile($audio->getInternalPath())`. In case a tmpFile is created, it needs to be cleaned afterwards - or the /tmp folder will explode

The final code is here - any better approach is welcome
https://github.com/Rello/audioplayer/blob/master/controller/scannercontroller.php#L974-L993

**Comment by icewind1991** [comment]
If the getID3 library itself doesn't rely on seek could "fake" fseek by reading from the stream until you're at the location you want to be.

That way you don't have to deal with tempfiles but you'll still have to read the entire file

**Comment by Rello** [comment]
it does - e.g. here it only reads part of the file to get its data
https://github.com/Rello/audioplayer/blob/master/3rdparty/getid3/getid3.php#L401-L402

**Comment by MorrisJobke** [comment]
Please retry with upcoming 12.0.3 and 13. We updated the SMB lib a bit: #6157 

If there are still problems please open a new ticket.
