### ISSUE TITLE
[BITV] 9.1.3.1a/3.1 - Although the page has some headings, these only partially help to structure the page content as the main content of the page, the tables/list view, is not structured by the headings.

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#36911]
It is recommended to remove the current "h1" heading "Nextcloud's homepage" and replace it e.g. with a visually hidden heading "All files" at the beginning of the main landmark. (1)

Fix:
- [x] https://github.com/nextcloud/server/pull/37583
- [ ] https://github.com/nextcloud/photos/pull/1727
- [x] https://github.com/nextcloud/nextcloud-vue/pull/3957

![Image](https://user-images.githubusercontent.com/1315170/221930207-8cd69f6b-f42c-4f83-8420-deea13a69caf.png)

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-be75bbae42-v3-n1

</details>

**Comment by JuliaKirschenheuter** [comment]
Related (same) issue is here: https://github.com/nextcloud/server/issues/35626

**Comment by JuliaKirschenheuter** [comment]
- [ ] Fix: https://github.com/nextcloud/server/pull/37174
- [ ] Backport NC26:
- [ ] Fix NC25: https://github.com/nextcloud/server/pull/37232

**Comment by JuliaKirschenheuter** [comment]
https://www.w3.org/TR/WCAG21/#adaptable
https://ergebnis.bitvtest.de/pruefschritt/bitv-20-web/9-1-3-1a-html-strukturelemente-fuer-ueberschriften

**Comment by JuliaKirschenheuter** [comment]
HI @michaelnissenbaum,

could i ask you about this ticket? 
This part: 

> It is recommended to remove the current "h1" heading "Nextcloud's homepage" and replace it e.g. with a visually hidden heading "All files" at the beginning of the main landmark. (1)

is already solved. I would like to ask you about main content of the page. In this ticket is mentioned "the tables/list view, is not structured by the headings" what should we do in that case? 

**? Should we place something like "Main content" as `<h2>` for pages with tables/lists view?** 

On pages without table/lists view there are already `<h2>` headings taking place:

![Screenshot from 2023-03-09 14-02-48](https://user-images.githubusercontent.com/6078378/224031498-3ed01589-af28-424e-89fb-b98baf44d337.png)

"Appearance and accessibility", "Keyboard shortcuts", "Background" ..and so on are already `<h2>`.

**Comment by JuliaKirschenheuter** [comment]
HI @michaelnissenbaum,

could i ask you about this ticket? 
This part: 

> It is recommended to remove the current "h1" heading "Nextcloud's homepage" and replace it e.g. with a visually hidden heading "All files" at the beginning of the main landmark. (1)

is already solved. I would like to ask you about main content of the page. In this ticket is mentioned "the tables/list view, is not structured by the headings" what should we do in that case? 

**? Should we place something like "Main content" as `<h2>` for pages with tables/lists view?** 

On pages without table/lists view there are already `<h2>` headings taking place:

![Screenshot from 2023-03-09 14-02-48](https://user-images.githubusercontent.com/6078378/224031498-3ed01589-af28-424e-89fb-b98baf44d337.png)

"Appearance and accessibility", "Keyboard shortcuts", "Background" ..and so on are already `<h2>`.

**Comment by JuliaKirschenheuter** [comment]
HI @michaelnissenbaum,

could i ask you about this ticket? 
This part: 

> It is recommended to remove the current "h1" heading "Nextcloud's homepage" and replace it e.g. with a visually hidden heading "All files" at the beginning of the main landmark. (1)

is already solved. I would like to ask you about main content of the page. In this ticket is mentioned "the tables/list view, is not structured by the headings" what should we do in that case? 

**? Should we place something like "Main content" as `<h2>` for pages with tables/lists view?** 

On pages without table/lists view there are already `<h2>` headings taking place:

![Screenshot from 2023-03-09 14-02-48](https://user-images.githubusercontent.com/6078378/224031498-3ed01589-af28-424e-89fb-b98baf44d337.png)

"Appearance and accessibility", "Keyboard shortcuts", "Background" ..and so on are already `<h2>`.

**Comment by JuliaKirschenheuter** [comment]
HI @michaelnissenbaum,

could i ask you about this ticket? 
This part: 

> It is recommended to remove the current "h1" heading "Nextcloud's homepage" and replace it e.g. with a visually hidden heading "All files" at the beginning of the main landmark. (1)

is already solved. I would like to ask you about main content of the page. In this ticket is mentioned "the tables/list view, is not structured by the headings" what should we do in that case? 

**? Should we place something like "Main content" as `<h2>` for pages with tables/lists view?** 

On pages without table/lists view there are already `<h2>` headings taking place:

![Screenshot from 2023-03-09 14-02-48](https://user-images.githubusercontent.com/6078378/224031498-3ed01589-af28-424e-89fb-b98baf44d337.png)

"Appearance and accessibility", "Keyboard shortcuts", "Background" ..and so on are already `<h2>`.

**Comment by michaelnissenbaum** [comment]
Hi @JuliaKirschenheuter, 

as I see it, the current implementation at https://try.nextcloud.com/ltd/a11y/ is not entirely correct or at least not what I proposed. For example, my suggestion was to place the h1 heading for "All Files" not in the header element, but in the main landmark, preferably in the DOM right after the navigation. If implemented this way, a screen reader user would have multiple options - to jump directly to a specific landmark/section or to the h1 heading. By jumping directly to the h1 heading, the user would be able to navigate through the main content of the page immediately.

![CleanShot 2023-03-31 at 20 37 22@2x](https://user-images.githubusercontent.com/48948959/229204271-3f08f207-7413-41c2-b11d-62bc2c6d07b8.png)

**Comment by JuliaKirschenheuter** [comment]
Thank you @michaelnissenbaum!

**Comment by JuliaKirschenheuter** [comment]
@michaelnissenbaum in current implementation it is really hard to move `<h1>` heading directly under the navigation. It is possible to do it only in apps which are already using Vue. But in older ones it is really hard. I've put `<h1>` right after the navigation in Photos App. In all other places I've put it as a first node of the `<main>`.

![Screenshot from 2023-04-05 10-33-34](https://user-images.githubusercontent.com/6078378/230026812-ef24ac1c-ecf7-4923-8c8f-1af7fa86435c.png)
![Screenshot from 2023-04-05 10-34-01](https://user-images.githubusercontent.com/6078378/230026908-a33447e2-4025-47e4-bae5-9fbba322558a.png)
![Screenshot from 2023-04-05 10-34-22](https://user-images.githubusercontent.com/6078378/230026995-722db52e-d2ac-413f-b38f-3de5acc2ec8c.png)

Hope it is ok 🙏

**Comment by JuliaKirschenheuter** [comment]
Fix:
- [ ] https://github.com/nextcloud/server/pull/37583

**Comment by michaelnissenbaum** [comment]
Hi @JuliaKirschenheuter screenshots you attached to this tickets are looking good to me.
