### ISSUE TITLE
[BITV] 9.1.3.2/2.1 - Mobile (responsive) view - The elements of the menu (Dashboard, Files, etc.) do not immediately receive screen reader focus after the menu is opened, but rather as the last elements on the page, as they are at the very bottom in the DOM order. (9)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#36924]
- [x] https://github.com/nextcloud/nextcloud-vue/pull/4084
- [x] Trap focus (Already in NcPopover)
- [x] https://github.com/nextcloud/nextcloud-vue/pull/4183
- [x] https://github.com/nextcloud/server/pull/38715

<img width="324" alt="c35f09f4d847ae9b61501e7d22b52c4d" src="https://user-images.githubusercontent.com/1315170/221937432-5ca6de8d-00ef-4fab-add3-f8811a638cb2.png">

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-1782286125-v2-n1

</details>

- [x] 9\.1.3.2/3.2 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-1782286125-v3-n2
- [x] 9\.1.3.2/4.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-1782286125-v4-n1
- [x] 9\.1.3.2/5.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-1782286125-v5-n1
- [x] 9\.1.3.2/6.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-1782286125-v6-n1
- [x] 9\.1.3.2/7.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-1782286125-v7-n1
- [x] 9\.1.3.2/8.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-1782286125-v8-n1
- [x] 9\.1.3.2/9.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-1782286125-v9-n1
- [x] 9\.1.3.2/10.2 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-1782286125-v10-n2

**Comment by Pytal** [comment]
Works on `master` and https://try.nextcloud.com/ltd/a11y/index.php with menu entries receiving screen reader focus on open

Can you confirm that the menu is accessible on https://try.nextcloud.com/ltd/a11y/index.php @michaelnissenbaum?

The container element is still at the bottom of the DOM though as it's a `v-popper`

Focus is not trapped though so a checkbox has been added to the description

**Comment by michaelnissenbaum** [comment]
The elements of the menu now receive keyboard and screen reader focus in the correct order. This issue appears to be resolved. Please ensure that the menu itself is correctly implemented with the appropriate elements/roles. Currently, for example, ARIA role="menu" has been used even though this is not an application menu, and the implementation is not complete. For further information, please refer to https://inclusive-components.design/menus-menu-buttons/.
