### ISSUE TITLE
Please save the thumbnails instead of processing them every time.

### ISSUE THREAD

**Issue by astrometrics** [nextcloud/server#36937]
Please save the thumbnails, process them just once (when the file is  uploaded or created). Save them in png or webp as a highly compressed format. It takes too long to process the thumbnails each time a page is rendered... also consumes processing power.
thanks

**Comment by joshtrichards** [comment]
Already supported if that's your preference, but you have to install/enable the app: https://apps.nextcloud.com/apps/previewgenerator
