### ISSUE TITLE
Collabora doenst work after Update to 11.0.2

### ISSUE THREAD

**Issue by taut98** [nextcloud/server#3694]
### Steps to reproduce
1. Create new Document
2. Open it
3. Look at Error-Message 

### Expected behaviour
The document should open and i should be able to edit it

### Actual behaviour
Recieving errormessage "Access forbidden"

### Server configuration
**Operating system**:
Debian 8.7 Jessie

**Web server:**
Apche2 
**Database:**
Mariadb 10.0.29
**PHP version:**
7.0.16
**Nextcloud version:** (see Nextcloud admin page)
11.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Yes updated from 11.0.1 today, didnt work before also
**Where did you install Nextcloud from:**
nextcloud.com
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Mail
Contacts
Calendar
Collabora
Notes
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>
</details>

### Client configuration
**Browser:**
Firefox 51
**Operating system:**
Win 7Pro
#### Web server error log
<details>
<summary>none</summary>
None
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nothing strange only infos</summary>
To much to insert, but nothing that looks like strange errors
```
Insert your Nextcloud log here
```
</details>

**Comment by nickvergessen** [comment]
"Access forbidden" sounds like access was blocked by the files access control app.
Can you check your rules for that?
