### ISSUE TITLE
[BITV] 9.1.3.5/6.1 - Input fields that clearly refer to the user, such as "Last Name," "First Name," etc., do not convey the purpose of each field through a language-independent attribute (currently, only the "autocomplete" attribute is adequately supported). (1)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#36945]
See also https://html.spec.whatwg.org/multipage/forms.html "Enabling client-side automatic filling of form controls" and Section 7 under https://www.w3.org/TR/WCAG21/ "Input Purposes for User Interface Components" for more information. 

- [ ] - [ ] Fix
- [ ] Backport

![ea791921f8d91989b62585d40226bf0f](https://user-images.githubusercontent.com/1315170/222219554-73d060c6-4096-468c-816d-1da35f0d7fd0.png)

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-2841f578da-v6-n1

</details>

**Comment by JuliaKirschenheuter** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
