### ISSUE TITLE
[BITV] 9.1.4.3/3.6 - "Details" section / "Sharing" tab - The list items within the combobox "Search for share recipients" are barely visually recognizable and do not meet the contrast requirements for texts. (2)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#36956]
- [x] Verify color contrast ratio of text

<img width="435" alt="011bb8a284f9ab6abc27b822335de8ed" src="https://user-images.githubusercontent.com/1315170/222224289-0c029315-b381-481f-9152-63596f6ad2f6.png">

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-6fe46b78da-v3-n6

</details>

- [x] 9.1.4.3/10.6 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-6fe46b78da-v10-n6

**Comment by Pytal** [comment]
Fixed on `master`
