### ISSUE TITLE
[BITV] 9.1.4.3/3.4 - "Details" section / "Share" menu - Both the label and note do not meet the contrast requirements for text. (2)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#36954]
- [x] https://github.com/nextcloud/nextcloud-vue/pull/4049
- [x] https://github.com/nextcloud/nextcloud-vue/pull/4092
- [x] https://github.com/nextcloud/server/pull/38214

![9a74478ddfe340c9129213eff5b58e70](https://user-images.githubusercontent.com/1315170/222223837-b8ba1f65-0356-4991-886a-a507fb634d74.png)

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-6fe46b78da-v3-n4

</details>

- [x] 9.1.4.3/10.4 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-6fe46b78da-v10-n4

**Comment by Pytal** [comment]
On `master`

- [x] Share label
- [ ] Share note

**Comment by Pytal** [comment]
NcAction* components are using opacity to indicate focus/hover

The share note is using NcActionTextEditable

To ensure we are using contrast-verified colors we should stop using opacity in NcAction* components and go with one of 2 options below

1. Replace `$opacity_normal: .7` → `--color-text-maxcontrast` and `$opacity_full: 1` → `--color-main-text`
    ![image](https://user-images.githubusercontent.com/24800714/236083149-1d45f883-e4dc-4a77-b574-8f58d084a948.png)
2. Set the base color to `--color-main-text` and like the tertiary NcButton:
  ![image](https://user-images.githubusercontent.com/24800714/236083181-7a53a2ce-f580-4014-9cfe-bad6378052ea.png)
  only use the background color, `--color-background-hover`, alongside input-specific colors, e.g. `--color-primary-element` for text field borders, to indicate focus/hover
  ![image](https://user-images.githubusercontent.com/24800714/236083208-7f592d26-7d63-418c-8c24-e110639d542e.png)

Option 2 seems better to me as all options have high readability regardless of focus/hover

### NcActionTextEditable examples

Option 1 | Option 2
--- | ---
![image](https://user-images.githubusercontent.com/24800714/236083302-031443b7-568b-4e15-a307-4b632f719b55.png) | ![image](https://user-images.githubusercontent.com/24800714/236083305-a0d0679d-793e-4bb3-8b7c-3011f8c8451a.png)

This change will affect all NcAction* components, not just NcActionTextEditable, to maintain consistency

Which option should we go for @jancborchardt?

**Comment by nimishavijay** [comment]
Agreed, option 2 sounds like it has better readability overall :) Here's how it would look like in Mail and Files. 

<img src="https://user-images.githubusercontent.com/52440189/236284685-394b09f1-437a-449f-ba3e-0daa0a43fef2.png" width=50% height=50%>

<img src="https://user-images.githubusercontent.com/52440189/236285254-080de1a1-63ee-4667-8f01-4d84f6260ed8.png" width=75% height=75%>
