### ISSUE TITLE
[BITV] 9.1.4.10/6.2 - At a browser window width of 320 CSS pixels (or at a browser window width of 1280 CSS pixels and 400% zoom magnification), the page contents do not wrap - some information and functions are not available without users having to scroll horizontally. (1)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#36965]
The issue affects both Firefox and Chromium-based browsers, with the whole page being affected in the case of Chromium-based browsers.

Page — Personal info
Personal info - Personal settings - Nextcloud
https://try.nextcloud.com/ltd/a11y/index.php/settings/user

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-81d891d46b-v6-n2

</details>

**Comment by JuliaKirschenheuter** [comment]
https://ergebnis.bitvtest.de/pruefschritt/bitv-20-web/bitv-20-web-9-1-4-10-inhalte-brechen-um

**Comment by ShGKme** [comment]
Note:

> In the alternative test with 1280px viewport width and 400% zoom, it should not be rated negatively if permanently positioned content (such as drop-out menus) is not fully accessible due to the very low available height of the browser window. The only check is whether content successfully breaks into a view that does not need to be scrolled horizontally. To check the loss of information and functionality, the test at 320px viewport width is crucial.

So only the width is checked, not the height.

**Comment by JuliaKirschenheuter** [comment]
closing ticket. As follow up (not exactly related to this ticket with horizontal scrolling):

- [BITV] Fix left sidebar from a11y perspective, https://github.com/nextcloud/server/issues/40954
- [BITV]: Sidebar is broken, https://github.com/nextcloud/activity/issues/1360

**Comment by ShGKme** [comment]
> So only the width is checked, not the height.

UPD: this is not correct.

According to the requirement:

> 2.2 Alternative test with 1280px viewport width
> 1. In a browser that supports zoom enlargement by 400% (e.g. B. Chrome) set the browser window to a width of 1280 CSS pixels and a height of 1024 CSS pixels. For this, the Resize-function of Web Developer Toolbar use.

Height `1024px + 400%` or `256px` also should work.

**Comment by ShGKme** [comment]
Files | Sidebar | Settings dialog | Apps sidebar
---|---|---|---
![image](https://github.com/nextcloud/server/assets/25978914/38864e7b-d39f-486f-8159-c5beb5cf4003) | ![image](https://github.com/nextcloud/server/assets/25978914/2ae20206-8fb3-4d0a-b8e2-5d6dce728394) | ![settings](https://github.com/nextcloud/server/assets/25978914/5f81428a-549d-4a8c-b839-c1daa57ee822) | ![apps](https://github.com/nextcloud/server/assets/25978914/d1f40891-336b-4f21-a8db-9a93ac6782c1)

Most problematic places are sidebars and dialogs

**Comment by ShGKme** [comment]
To fix the sidebar, we can add:
```css
.app-sidebar-tabs__content] {
  min-height: 512px; // or whatever, but not 0 px
}
```

**Comment by ShGKme** [comment]
The same with `NcAppSettingsDialog`
