### ISSUE TITLE
[BITV] 9.1.4.10/3.1 - At a browser window width of 320 CSS pixels (or at a browser window width of 1280 CSS pixels and 400% zoom magnification), the jump links at the top of the page are overlaid and displayed cut off. (8)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#36963]
- [ ] Fix
- [ ] Backport

<img width="329" alt="7eb4ebd78421bc6778e18486e3d94dc8" src="https://user-images.githubusercontent.com/1315170/222238600-411f049c-3bb0-46de-ba77-ecc82fedbc05.png">

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-81d891d46b-v3-n1

</details>

- [ ] 9.1.4.10/4.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-81d891d46b-v4-n1
- [ ] 9.1.4.10/5.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-81d891d46b-v5-n1
- [ ] 9.1.4.10/6.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-81d891d46b-v6-n1
- [ ] 9.1.4.10/7.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-81d891d46b-v7-n1
- [ ] 9.1.4.10/8.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-81d891d46b-v8-n1
- [ ] 9.1.4.10/9.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-81d891d46b-v9-n1
- [ ] 9.1.4.10/10.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-81d891d46b-v10-n1

**Comment by Pytal** [comment]
These issues were created back when we needed to backport to `stable25` but now target is NC27 so you may ignore the backport checkbox @susnux :)
