### ISSUE TITLE
[BITV] 9.1.4.11/2.1 - Unselected (inactive) elements of the main navigation on the upper left side of the page do not meet the contrast requirements for graphical user interface components - actual contrast is 2.9:1. (9)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#36967]
- [ ] Fix
- [ ] Backport

<img width="162" alt="6a0f6855fdca84823d6633bbd5cd8fc0" src="https://user-images.githubusercontent.com/1315170/222240018-f8543a58-1d7e-4153-bcd9-99b0080f840f.png">

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-3dbfb7615a-v2-n1

</details>

- [ ] 9.1.4.11/3.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-3dbfb7615a-v3-n1
- [ ] 9.1.4.11/4.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-3dbfb7615a-v4-n1
- [ ] 9.1.4.11/5.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-3dbfb7615a-v5-n1
- [ ] 9.1.4.11/6.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-3dbfb7615a-v6-n1
- [ ] 9.1.4.11/7.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-3dbfb7615a-v7-n1
- [ ] 9.1.4.11/8.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-3dbfb7615a-v8-n1
- [ ] 9.1.4.11/9.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-3dbfb7615a-v9-n1
- [ ] 9.1.4.11/10.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-3dbfb7615a-v10-n1

**Comment by JuliaKirschenheuter** [comment]
@nimishavijay , @jancborchardt 

Which colors could i take to fix this issue?

**Comment by nimishavijay** [comment]
That sounds like a good solution to me! :) 

I also experimented with::
- changing the size of the active app icon to 22px 
![image](https://github.com/nextcloud/server/assets/52440189/9db1cca5-f273-4179-8989-8c6fb4f18018)

- increasing the width of the active app indicator to 16px
![image](https://github.com/nextcloud/server/assets/52440189/06092989-6ca7-4b81-a8ad-398072cde544)

Neither of these make any significant difference so we can go ahead with just increasing the opacity to 1 :) cc @jancborchardt @szaimen

**Comment by szaimen** [comment]
Increasing the opacity also sounds good to me :)
