### ISSUE TITLE
WebDav Appears Broken

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#3697]
Installed on Shared Hosting with InMotion Hosting

It is using PHP5.

I am getting this error:

`Your web server is not yet set up properly to allow file synchronization because the WebDAV interface seems to be broken.`

What can I check or do to get this fixed?

**Comment by Schmuuu** [comment]
Isn't this something you could ask for in the community/ forum first? Maybe they can help you there to find out the root cause and then you will see if this is really an issue that needs a fix. But maybe this is just a miss-configuration and not an issue.

**Comment by nickvergessen** [comment]
Yes, please reopen the issue in the forum.
