### ISSUE TITLE
[BITV] 9.1.4.11/3.2 - Table - Non-active checkboxes (excluding the checkbox in the row with column headers) do not meet the contrast requirements for graphical interface components. The same problem also affects the list view. (2)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#36970]
- [ ] Fix
- [ ] Backport

![5e2cbbfe0fd4258eab94ad65371fb1fa](https://user-images.githubusercontent.com/1315170/222241811-55cb7deb-6f81-4d64-9a34-8485294f64e0.png)

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-3dbfb7615a-v3-n2

</details>

- [ ] 9.1.4.11/10.2 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-3dbfb7615a-v10-n2

**Comment by skjnldsv** [comment]
Probably fixed already

![image](https://github.com/nextcloud/server/assets/14975046/fb42ce5a-3c8d-4b2d-b627-037137671669)
