### ISSUE TITLE
[BITV] 9.2.1.1/8.1 - The "Groups" column in the table - The input field is only focusable if no group has been selected yet. (1)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#36986]
Once a group has already been selected, it is no longer possible to focus the field with the keyboard and select another group. 

![4b98244143224a248f230b7ff75c24c8](https://user-images.githubusercontent.com/1315170/222246571-58426b51-587d-4640-9496-ef3d0f9292e4.png)

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-6bd94ebc49-v8-n1

</details>

**Comment by JuliaKirschenheuter** [comment]
Seems that this issue is already resolved, @michaelnissenbaum could you please make a double-check in testing instance and confirm that? Thank you!

**Comment by michaelnissenbaum** [comment]
Hi @JuliaKirschenheuter I can confirm that this issue has been resolved.

**Comment by JuliaKirschenheuter** [comment]
closing because already fixed via https://github.com/nextcloud/server/pull/38839
