### ISSUE TITLE
[BITV] 9.2.4.3/3.2 - When the menu "New file/folder menu" is open, it is still possible to navigate through the elements on the page behind the menu, causing visually hidden elements to receive keyboard focus in some cases. It is best to close the menu when leaving it. (2)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#36988]
- [ ] Fix
- [ ] Backport

<img width="297" alt="82cfc43572162aad1ef576c3571a55d6" src="https://user-images.githubusercontent.com/1315170/222247584-87209b86-3030-446d-b1cf-19e19b0882fc.png">

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-89806fe784-v3-n2

</details>

- [ ] 9.2.4.3/10.2 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-89806fe784-v10-n2

**Comment by Fenn-CS** [comment]
This is being handled with files migration to vue

**Comment by skjnldsv** [comment]
Fixed with F2V
