### ISSUE TITLE
[BITV] 9.2.1.2/8.1 - When using keyboard navigation to go forward, the keyboard focus stays stuck on the "Add Group" button (page navigation on the left side) and does not move any further. However, backward navigation works. (1)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#36987]
![4b98244143224a248f230b7ff75c24c8](https://user-images.githubusercontent.com/1315170/222246913-f6105aa2-5a75-4d2d-829f-6fd4aff46afc.png)

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-79869d405e-v8-n1

</details>

**Comment by Fenn-CS** [comment]
This is not clear enough.

- What button is used in "moving forward'?

cc; @JuliaKirschenheuter do you have any ideas? (Thanks in advance :) )

**Comment by ShGKme** [comment]
> * What button is used in "moving forward'?

It seems to be <kbd>TAB</kbd> for moving forward and <kbd>SHIFT + TAB</kbd> backward

**Comment by JuliaKirschenheuter** [comment]
this seems to be already fixed
![Peek 2023-08-21 15-58](https://github.com/nextcloud/server/assets/6078378/b01e138f-b5d2-4d98-92b3-8c6aa76bf6b5)
and
![Peek 2023-08-21 15-53](https://github.com/nextcloud/server/assets/6078378/831f2fc5-a025-4a1e-b981-1913d5f6154f)
