### ISSUE TITLE
[BITV] 9.2.4.3/3.7 - "Change view" button - The button has been implemented as a checkbox with a label. (2)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#36993]
Incorrectly, the label element has been made focusable using tabindex="0". Note - the title element should also be removed from label element. 

<img width="61" alt="d8d62a701941522d2687bd0cc6865e6f" src="https://user-images.githubusercontent.com/1315170/222249797-dcf34ad3-cffc-4040-b3a0-f9bd6f174822.png">

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-89806fe784-v3-n7

</details>

- [ ] 9.2.4.3/10.7 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-89806fe784-v10-n7

**Comment by JuliaKirschenheuter** [comment]
@michaelnissenbaum using checkbox in that case seems suspicious to me. Is it ok to leave using a checkbox or is it better to use just a common button instead? 

![Peek 2023-08-11 14-50](https://github.com/nextcloud/server/assets/6078378/7e9ab2a4-eab9-404e-bfb9-a0f0cffe9668)

**Comment by michaelnissenbaum** [comment]
Hi @JuliaKirschenheuter. I would recommend using a button instead of a checkbox. Just make sure to ensure that the accessible name of the button is appropriately adjusted based on the context.

**Comment by JuliaKirschenheuter** [comment]
This issue is (not relevant) anymore because the whole view have to be re-created in Vue (files2vue project). Moving this issue to parked now.
