### ISSUE TITLE
[BITV] 9.2.4.3/7.4 - The "Log levels" menu does not close automatically when it is left and overlays some table contents, making it difficult to work with the table. (1)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#36996]
- [ ] Fix
- [ ] Backport

![414c728086658dfdb595a873bd04deeb](https://user-images.githubusercontent.com/1315170/222251284-00a811ea-a3ac-443c-8655-5d0e238c8961.png)

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-89806fe784-v7-n4

</details>

**Comment by szaimen** [comment]
I think this was fixed with the logreader rewrite right @susnux?

**Comment by susnux** [comment]
Fixed with the vue ligreader
