### ISSUE TITLE
[BITV] 9.2.4.3/3.5 - Usability Note: Both accordion buttons "Favorites" and "Shares" in the navigation on the left side are not visually recognizable as such. It is recommended to use an appropriate symbol such as an arrow. (2)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#36991]
- [x] Fix
- [x] Backport

![5e2cbbfe0fd4258eab94ad65371fb1fa](https://user-images.githubusercontent.com/1315170/222248803-a4e11ec1-5b8a-4434-9025-f30031ffb99d.png)

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-89806fe784-v3-n5

</details>

- [x] 9.2.4.3/10.5 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-89806fe784-v10-n5

**Comment by Pytal** [comment]
Fixed on master
