### ISSUE TITLE
[BITV] 9.2.4.3/8.4 - It is recommended to keep the "submit" element visible, as sudden disappearance of the keyboard focus when jumping from one input field to another in the table can confuse some users. (1)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#36997]
- [ ] Fix
- [ ] Backport

```
<input data-v-dd76953c="" type="submit" value="" class="icon-confirm">
```

![4b98244143224a248f230b7ff75c24c8](https://user-images.githubusercontent.com/1315170/222251530-05104921-cae2-4c5e-a515-62aa09a02138.png)

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-89806fe784-v8-n4

</details>

**Comment by JuliaKirschenheuter** [comment]
Seems to be already fixed, as done via https://github.com/nextcloud/server/pull/38839 

![Peek 2023-08-16 13-46](https://github.com/nextcloud/server/assets/6078378/3171749f-6f36-40ea-8d0f-e38b06d473e5)
