### ISSUE TITLE
[Bug]: Nextcloud responds with previously authorized user data instead of current user

### ISSUE THREAD

**Issue by shinelev** [nextcloud/server#37008]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I am working on OAuth authorization for my .net core application within Nextcloud. For this purposes I use default Microsoft OAuth extensions.
I can retrieve access token for each authorized user, but can't get information about specific user.
Every time sending request to `ocs/v2.php/cloud/user?format=json` I get information about first authorized in Nextcloud user.
For example, `user1` is authorized within Nextcloud. Access token for this user is retrieved, and after that my application can get information about this user by sending request to `ocs/v2.php/cloud/user?format=json`. Then if another user (let it be user2) wants to use my application, he sucessfully can be authorized within Nextcloud. Application gets correspoding access token, BUT when it it tries to get info about user2 Nextcloud responds with data about user1.

Same results happens when I try to reproduce this logic via Postman (see steps to reproduce section).

I found workaround. I need to remove `os_sessionPassphrase` or make request without cookies to get correct response. But it seems to me that it is not standard OAuth (v2) flow.

### Steps to reproduce

1. Register your client for using OAuth authorization in Nextcloud and get you ClientId and SecretId.
2. Open Postman and try to get access token for `user1`
![image](https://user-images.githubusercontent.com/39155477/222478452-5cf4c621-5da3-4ab3-9bab-c7cd06000b3b.png)
3. Send request with access token for `user1`
![image](https://user-images.githubusercontent.com/39155477/222479885-d3f5c3aa-fc2f-4ba5-a87e-9e50d5ef6c25.png)
4. Open new request window in Postman and get access token for `user2`
5. Send same request with access token for `user2` and get results
![image](https://user-images.githubusercontent.com/39155477/222481401-144d9eb9-ba6e-49f1-a017-cf1d1483a553.png)
6. Remove cookie `oc_sessionPassphrase` and repeat request from step 5. See results.
![image](https://user-images.githubusercontent.com/39155477/222482206-3e4863cf-97ae-4365-b760-bb3391124a25.png)

### Expected behavior

Nextcloud should responds with correct data for currently authorized user without removing specific cookies or making request without cookies at all.

### Installation method

None

### Operating system

Other

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - bookmarks: 12.0.0
  - calendar: 4.2.4
  - calendar_resource_management: 0.3.1
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.1.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.3
  - end_to_end_encryption: 1.11.1
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_external: 1.17.0
  - files_markdown: 2.3.6
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - forms: 3.0.4
  - impersonate: 1.12.0
  - keeweb: 0.6.5
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - mail: 2.2.2
  - notes: 4.6.0
  - notifications: 2.13.1
  - notify_push: 0.6.0
  - oauth2: 1.13.0
  - onlyoffice: 7.3.4
  - photos: 2.0.1
  - polls: 3.4.1
  - previewgenerator: 5.1.0
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - related_resources: 1.0.4
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.4
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - talk_matterbridge: 1.25.2
  - tasks: 0.14.5
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - user_ldap: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - bruteforcesettings
  - encryption: 2.12.0
  - firstrunwizard: 1.1
  - nextcloud_announcements: 1.1
  - password_policy: 1.2.2
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - support: 1.0.1
  - survey_client: 1.0.0
  - updatenotification: 0.1.0
```

### Additional info

Nextcloud version 25.0.4

**Comment by kesselb** [comment]
Hi @shinelev :wave: 

Sounds similar to https://github.com/nextcloud/server/issues/34501.

> I need to remove os_sessionPassphrase or make request without cookies to get correct response.

Some http clients store the response cookies by default. 
It sounds reasonable to me to use a fresh http client instance for another user.

> But it seems to me that it is not standard OAuth (v2) flow.

I understand it's unexpected that the session cookie has a higher priority than an authorization header. 

cc @ChristophWurst @skjnldsv

**Comment by shinelev** [comment]
Thanks for extra details and a link to another issue. Now I got the idea about how it works.
