### ISSUE TITLE
[BITV] 9.2.4.7/6.1 - The "Change scope..." buttons receive keyboard focus, but it is not easily noticeable as the contrast ratio between the background and focus border is less than 3:1. (1)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#37014]
- [ ] Fix
- [ ] Backport

Personal info - Personal settings - Nextcloud
https://try.nextcloud.com/ltd/a11y/index.php/settings/user
<img width="303" alt="3090a032945687f879d88ed9c0e70d64" src="https://user-images.githubusercontent.com/1315170/222542629-a5608b80-5896-4d96-96aa-9d6868380fcd.png">

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-91f2646afa-v6-n1

</details>

**Comment by JuliaKirschenheuter** [comment]
seems to be already fixed 🥳

![Peek 2023-08-16 15-37](https://github.com/nextcloud/server/assets/6078378/9a9f40ad-b927-4db3-b6c4-2218d75dcd75)
