### ISSUE TITLE
[Bug]: multiple .config.php files: ./occ, writes everything back in one config.php.

### ISSUE THREAD

**Issue by ernolf** [nextcloud/server#37049]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

According to the [manual](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html#multiple-config-php-file), I devided my config over multiple `/config/*.config.php` files: *db.config.php*, *log.config.php*, *mail.config.php* etc.

After each write access, be it through `./occ maintenance:mode --on/--off` or through `./occ config:system:set`, these files are all merged back into one ./config.php

When I now try to change such a value, like loglevel, wich resides in `/config/log.config.php`, it gives me a success echo that looks like this:
```
:~# ncc  config:system:get loglevel
2
:~# ncc  config:system:set loglevel --value=3
System config value loglevel set to string 3
```
instead of a message like `loglevel cannot be changed by occ because the value is defined in log.config.php which takes precedence` or something like that.

After a new query, it returns the value from /config/log.config.php, since that one takes precedence as described in the manual:
```
:~# ncc  config:system:get loglevel
2
```

### Steps to reproduce

1. devide config.php into multiple *.config.php files with at least one value (like loglevel) to reproduce behaviour as described above.
2. run `.occ maintenance:mode --on/--off` results in merged config
3. try to change a value which is in its own *.config.php (like loglevel) and observe the behavior

### Expected behavior

* No merging of *sub*.config.php files
* A meaningful echo when trying to change unchangeable values,
* `./occ  config:system:set` should first test, if "new" value is already set. Like when I do `./occ mantenance:mode --on/--off`, when I try to switch it to the state it already is, I get a meaningful echo.

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
*
```

**Comment by szaimen** [comment]
Hi, this is not a bug but how it was designed. Please refer to the forum for help on this: https://help.nextcloud.com

**Comment by ernolf** [comment]
@szaimen:
> this is not a bug but how it was designed

OK, not a bug, so far I go with you but let it be a feature request, to provide better meaningfull echoes.

> Please refer to the forum for help on this: https://help.nextcloud.com/

Thank you. You know that I offer my help where I can there 😉

**Comment by szaimen** [comment]
> but let it be a feature request, to provide better meaningfull echoes.

feel free to create a feature request for this 👍
