### ISSUE TITLE
demo.nextcloud.com better description of user "admin"

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#3705]
When starting an instant trial you have to fill in your desired nextcloud name and your password.
As these are two input fields it leads to the assumption that the first is your username and the last the password for this user. 
Therefore user might trying this combination instead of "admin" and "password".

To make this clearer, I suggest to add a hint on both input fields, which are basically saying the same, but the user gets more attracted to it.
On the login site the user should be prefilled with "admin", at least for the very first run.

(btw: I hope I chose the right repo)

**Comment by kahnwong** [comment]
I thought the 'username' part is 'Name of your Nextcloud' as well. Still didn't click after a few tries. I second this.

**Comment by MorrisJobke** [comment]
@LukasReschke Whom to ping for the demo?

**Comment by LukasReschke** [comment]
@MorrisJobke Let me send you details via IRC:
