### ISSUE TITLE
Possibillity to filter by issuing app in protocoll view

### ISSUE THREAD

**Issue by Vollstrecker** [nextcloud/server#37053]
Hi,

I just tried the recognize app and it seems to have a problem somewhere. Unfortunately this information goes into debug category which is really crowded.

It would be a real pleasure to have something like the log level selector for the installed apps.

**Comment by SystemKeeper** [comment]
Hey, take a look at https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#logging at `log.condition`

**Comment by Vollstrecker** [comment]
With the log condition I can set the level for the app to debug, but that's what they are at already. If this field doesn't support something like "only this app goes to debug" it doesn't help.

I get many of webdav NotAuthenticated and no app InvalidTokenException plus everthing about the stuff the cronjob does. The messages I'm searching for come only once per hour sometimes less, so it's a real pita to find them and a quick filter that only selected apps (or only one selected app) would be a great help for this.

**Comment by SystemKeeper** [comment]
> With the log condition I can set the level for the app to debug, but that's what they are at already.

Yes, the point is that you don't set everything to `debug`, but use `log.condition` to just set the desired app to `debug`:
> Once one of these conditions is met, the required log level is set to debug.

But if you need to leave everything at debug, then yes, that won't help. See the request at https://github.com/nextcloud/logreader/issues/268

**Comment by Vollstrecker** [comment]
Now I got it, will try this evening.

I guess my request should then be altered to "Filter or make this setting easier accessible". And I'm confused why I didn't find the other issue as I search for "filter by app" and got nothing.

**Comment by SystemKeeper** [comment]
> And I'm confused why I didn't find the other issue as I search for "filter by app" and got nothing.

Note that the linked issue is not in this (= the server) repository but in its own repository of the app "logreader". Maybe you searched only here on server?

**Comment by joshtrichards** [comment]
@Vollstrecker Does the Issue in nextcloud/logreader#268 reflect your request here? If so, let's close this one here out.

**Comment by Vollstrecker** [comment]
The description is a bit short, but yes.
