### ISSUE TITLE
[BITV] 9.3.3.2/0.1 - Note: "Placeholder" attributes are not a substitute for visual labels - they disappear as soon as users start entering data. (1)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#37082]
<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-9f92015c98-v0-n1

</details>

* #37083
* #37084
* #37085
* nextcloud/nextcloud-vue#3871
* #37086
* #37087
*  #37088
* #37089
* nextcloud/photos#1685
* #37090

**Comment by AndyScherzinger** [comment]
@JuliaKirschenheuter @artonge @Pytal you sure this is "XS" ?

**Comment by JuliaKirschenheuter** [comment]
> @JuliaKirschenheuter @artonge @Pytal you sure this is "XS" ?

I will change this ticket to "S" for now.

not sure but actually can be covered by https://github.com/nextcloud-libraries/nextcloud-vue/pull/4394. All places have to be  adjusted to new component.

**Comment by JuliaKirschenheuter** [comment]
Places to be replaced:

![Screenshot from 2023-08-28 19-00-07](https://github.com/nextcloud/server/assets/6078378/ddc37a5a-7ac0-4db1-a280-c64adfcd21c1)
![Screenshot from 2023-08-28 18-59-51](https://github.com/nextcloud/server/assets/6078378/e94405f3-86fc-421a-88c6-4cbdca186ae3)
![Screenshot from 2023-08-28 18-59-38](https://github.com/nextcloud/server/assets/6078378/541cd3ac-2f1b-498b-9a2d-b88ee847179e)
![Screenshot from 2023-08-28 18-53-09](https://github.com/nextcloud/server/assets/6078378/48466355-d6ab-4a98-8956-0d051f77e68a)
![Screenshot from 2023-08-28 18-52-53](https://github.com/nextcloud/server/assets/6078378/2782ba27-3c17-4761-85f3-49ff93b37037)
![Screenshot from 2023-08-28 18-52-15](https://github.com/nextcloud/server/assets/6078378/0568065c-2e7e-4779-a13b-3dfbf2002674)
![Screenshot from 2023-08-28 18-46-25](https://github.com/nextcloud/server/assets/6078378/f6ed5c3b-13e6-4131-9b31-60ecc1d90c08)
![Screenshot from 2023-08-28 18-45-16](https://github.com/nextcloud/server/assets/6078378/d3755120-4e70-4ea2-b6bd-34203402d6ce)
![Screenshot from 2023-08-28 18-43-40](https://github.com/nextcloud/server/assets/6078378/e4fbbe6f-e9ab-4d96-b118-7329bc46a48e)
![Screenshot from 2023-08-28 18-40-31](https://github.com/nextcloud/server/assets/6078378/0e004300-a8b4-4f1f-96f5-df0fba5a6656)
![Screenshot from 2023-08-28 18-40-18](https://github.com/nextcloud/server/assets/6078378/11afb3c6-9d4d-4d58-a322-9197d05ce697)

**Comment by JuliaKirschenheuter** [comment]
Changing ticket to "L"

> > @JuliaKirschenheuter @artonge @Pytal you sure this is "XS" ?
> 
> I will change this ticket to "S" for now.

**Comment by JuliaKirschenheuter** [comment]
everything what was known is done now
