### ISSUE TITLE
[BITV] 9.3.3.2/2.1 - Modal dialog "Online status" - The input field "What is your status" has a label, but it is not available to visually impaired users due to the use of "hidden-visually." (1)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#37083]
see also https://github.com/nextcloud/server/issues/37091

![51e36c48b52ba8aa27249843b98fe342](https://user-images.githubusercontent.com/1315170/223561060-75d8c46c-ceb5-4fff-9bab-0762835ff5e1.png)

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-9f92015c98-v2-n1

</details>

**Comment by JuliaKirschenheuter** [comment]
Dear @michaelnissenbaum sorry for a stupid question but what is wrong with our `hidden-visually` class? 

![Screenshot from 2023-08-15 11-38-23](https://github.com/nextcloud/server/assets/6078378/519855ef-1bfa-493c-9fd6-fbf1ad542c70)

**Comment by michaelnissenbaum** [comment]
Hi @JuliaKirschenheuter. There's nothing wrong with the class. The issue lies elsewhere. It needs to be ensured that the input field has a visual label, and in our case, you are hiding the label element. Please make sure that placeholder attributes are not a substitute for a visual label.
![CleanShot 2023-08-16 at 19 55 17@2x](https://github.com/nextcloud/server/assets/48948959/45e910cd-bdf0-4d0c-917e-c31d19876f1b)

**Comment by JuliaKirschenheuter** [comment]
Thank you @michaelnissenbaum!
I think design-wise there is no place for visual label. Should i in that case take a placeholder completely away?

**Comment by michaelnissenbaum** [comment]
@JuliaKirschenheuter , as I've mentioned before, we need a visual label. We can't do without it. Placeholder attributes are not a substitute for visual labels. In this case, you'll need to adjust the design accordingly or use flyout labels.

**Comment by JuliaKirschenheuter** [comment]
Hi @jancborchardt 
what do you mean could we find a solution here with visible label?

**Comment by marcoambrosini** [comment]
@JuliaKirschenheuter [we have this coming soon](https://github.com/nextcloud-libraries/nextcloud-vue/pull/4394)

**Comment by susnux** [comment]
> [we have this coming soon](https://github.com/nextcloud-libraries/nextcloud-vue/pull/4394)

I think this will help fixing a lot of those issues, where a "plain" label does not match and re misuse a placeholder for it instead :)

**Comment by JuliaKirschenheuter** [comment]
@michaelnissenbaum would you approve such solution? https://github.com/nextcloud-libraries/nextcloud-vue/pull/4394#issuecomment-1683925162

**Comment by michaelnissenbaum** [comment]
I will accept the solution, just ensure that the contrasts of labels and graphical user interface elements such as input field borders meet the requirements.
