### ISSUE TITLE
Add background-color to hover and active links on the left navigation

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/server#3708]
It is possible to add a background-color like **#F8F8F8** to the left navigation?
At the moment the link color ist changed from darkgrey to black and I can't see ist every time where I am. For the filelist we use this color too to highlight the current entry.

![background_leftnav](https://cloud.githubusercontent.com/assets/1473674/23579568/82dd5200-00f0-11e7-93f0-19b5eff01e29.png)

**Comment by MariusBluem** [comment]
Will be fixed in another way with https://github.com/nextcloud/server/pull/3150 in Nextcloud 12 💪

**Comment by Dennis1993** [comment]
Ah ok, perfect! Thank you!
