### ISSUE TITLE
[BITV] 9.4.1.2/2.1 - The "More apps" menu in the mobile (responsive) view has been implemented as an application menu with the role="menu". (9)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#37093]
- [x] https://github.com/nextcloud-libraries/nextcloud-vue/pull/4436
- [x] https://github.com/nextcloud/server/pull/40084

However, the implementation is not complete as both the role="menuitem" for the individual menu items and the attributes aria-expanded and aria-haspopup have not been used. For more information, see, for example, https://www.w3.org/WAI/ARIA/apg/patterns/menu-button/examples/menu-button-actions-active-descendant/. 

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-bfbf07e5c3-v2-n1

</details>

- [x] 9.4.1.2/3.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-bfbf07e5c3-v3-n1
- [x] 9.4.1.2/4.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-bfbf07e5c3-v4-n1
- [x] 9.4.1.2/5.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-bfbf07e5c3-v5-n1
- [x] 9.4.1.2/6.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-bfbf07e5c3-v6-n1
- [x] 9.4.1.2/7.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-bfbf07e5c3-v7-n1
- [x] 9.4.1.2/8.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-bfbf07e5c3-v8-n1
- [x] 9.4.1.2/9.2 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-bfbf07e5c3-v9-n2
- [x] 9.4.1.2/10.1 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-bfbf07e5c3-v10-n1

**Comment by Pytal** [comment]
`aria-expandad` and `aria-haspopup` present on master

- [ ] Add `role="menuitem"`

**Comment by Pytal** [comment]
`aria-expanded` and `aria-haspopup` present on master

- [ ] Add `role="menuitem"`

**Comment by Pytal** [comment]
menuitem on master
![image](https://github.com/nextcloud/server/assets/24800714/33c9bc4d-621b-41ab-b4a1-255a7be1c478)
