### ISSUE TITLE
Upgrade with SSL-enabled MySQL DB fails

### ISSUE THREAD

**Issue by MEitelwein** [nextcloud/server#3709]
### Steps to reproduce
I am having SSL enabled for the connection to my MySQL database server by using the following settings in my config.php:

----------------------

  'dbdriveroptions' => 
  array (
    1007 => '/etc/keys/SSL_client_owncloud.key',
    1008 => '/etc/keys/SSL_client_owncloud.crt',
    1009 => '/etc/keys/SSL_CA_Eitelwein.crt',
  ),
  'dbtype' => 'mysql',

----------------------

When upgrading to a newer release, e.g. 11.0.2

1. sudo -u www-data php occ upgrade

### Expected behaviour
Nextcloud upgrades to new release

### Actual behaviour
Upgrade breaks with the following output:

----------------------

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
Disabled 3rd-party app: calendar
Disabled 3rd-party app: contacts
Disabled 3rd-party app: direct_menu
Disabled 3rd-party app: keeweb
Disabled 3rd-party app: notes
Disabled 3rd-party app: rainloop
Update 3rd-party app: calendar
Update 3rd-party app: contacts
Update 3rd-party app: direct_menu
Update 3rd-party app: keeweb
Update 3rd-party app: notes
Update 3rd-party app: rainloop
Drop old database tables

 Done
 31/31 [============================] 100%
Remove old (< 9.0) calendar/contact shares
 Done
 4/4 [============================] 100%
Fix permissions so avatars can be stored again
 Done
 2/2 [============================] 100%
Starting code integrity check...
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_appconfig` (`appid`,`configkey`,`configvalue`) SELECT ?,?,? FROM `oc_appconfig` WHERE `appid` = ? AND `configkey` = ? HAVING COUNT(*) = 0' with params ["core", "oc.integritycheck.checker", "[]", "core", "oc.integritycheck.checker"]:

SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
Update failed
Maintenance mode is kept active
Reset log level

----------------------

Upgrade works as intended when the dbdriveroptions in config.php are disabled (no SSL connection to MySQL). 

### Server configuration
**Operating system**: Ubuntu 16.04.01 server

**Web server: Apache/2.4.18 (Ubuntu)

**Database: MySQL 5.5.54-0+deb8u1 (Debian)

**PHP version: 7.0.15

**Nextcloud version: 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:  Update from 11.0.1

**Where did you install Nextcloud from: Source from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - calendar: 1.5.1
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - direct_menu: 0.10.0
  - external: 1.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - keeweb: 0.3.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - rainloop: 4.26.1
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - files_retention
  - logreader
  - user_external
  - user_ldap
  - user_saml
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
{
    "system": {
        "appcodechecker": false,
        "asset-pipeline.enabled": false,
        "assetdirectory": "\/srv\/http\/nextcloud",
        "check_for_working_htaccess": true,
        "check_for_working_webdav": true,
        "datadirectory": "\/srv\/cloud-data",
        "dbdriveroptions": {
            "1007": "\/etc\/keys\/SSL_client_owncloud.key",
            "1008": "\/etc\/keys\/SSL_client_owncloud.crt",
            "1009": "\/etc\/keys\/SSL_CA_Eitelwein.crt"
        },
        "dbtype": "mysql",
        "dbname": "nextcloud_11_00_02",
        "dbhost": "sql.eitelwein.net",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": "files",
        "default_language": "de",
        "filelocking.enabled": "true",
        "forcessl": true,
        "installed": true,
        "installedat": "1336329504.63",
        "instanceid": "51057b493ec84",
        "knowledgebaseenabled": "true",
        "lastupdatedat": "1337539013.06",
        "loglevel": "2",
        "logtimezone": "Europe\/Berlin",
        "log_type": "syslog",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "nextcloud",
        "mail_domain": "eitelwein.net",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "mail.eitelwein.net",
        "mail_smtpport": "25",
        "mail_smtpauth": "1",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "overwrite.cli.url": "\/owncloud",
        "overwritewebroot": "\/owncloud",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "session_lifetime": 1800,
        "session_keepalive": false,
        "share_folder": "\/Shared",
        "theme": "",
        "trashbin_retention_obligation": "90, auto",
        "trusted_domains": [
            "www.eitelwein.net"
        ],
        "updatechecker": false,
        "version": "11.0.2.7"
    }
}
</details>

**Are you using external storage, if yes which one: no

**Are you using encryption: no

**Are you using an external user-backend, if yes which one: no

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Mar  4 20:10:32 www ownCloud[12758]: {core} starting upgrade from 11.0.1.2 to 11.0.2.7
Mar  4 20:10:32 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Repair MySQL database engine
Mar  4 20:10:32 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Repair MySQL collation
Mar  4 20:10:32 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Repair SQLite autoincrement
Mar  4 20:10:32 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Repair duplicate entries in oc_lucene_status
Mar  4 20:10:32 www ownCloud[12758]: {updater} \OC\Repair::info: Repair info: removing duplicate entries from lucene_status
Mar  4 20:10:32 www ownCloud[12758]: {updater} \OC\Updater::dbUpgradeBefore: Updating database schema
Mar  4 20:10:34 www ownCloud[12758]: {updater} \OC\Updater::dbUpgrade: Updated database
Mar  4 20:10:35 www ownCloud[12758]: {updater} \OC\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: calendar
Mar  4 20:10:35 www ownCloud[12758]: {updater} \OC\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: contacts
Mar  4 20:10:36 www ownCloud[12758]: {updater} \OC\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: direct_menu
Mar  4 20:10:37 www ownCloud[12758]: {updater} \OC\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: keeweb
Mar  4 20:10:37 www ownCloud[12758]: {updater} \OC\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: notes
Mar  4 20:10:37 www ownCloud[12758]: {updater} \OC\Updater::thirdPartyAppDisabled: Disabled 3rd-party app: rainloop
Mar  4 20:10:40 www ownCloud[12758]: {updater} \OC\Updater::upgradeAppStoreApp: Update 3rd-party app: calendar
Mar  4 20:10:46 www ownCloud[12758]: {updater} \OC\Updater::upgradeAppStoreApp: Update 3rd-party app: contacts
Mar  4 20:10:48 www ownCloud[12758]: {updater} \OC\Updater::upgradeAppStoreApp: Update 3rd-party app: direct_menu
Mar  4 20:10:49 www ownCloud[12758]: {updater} \OC\Updater::upgradeAppStoreApp: Update 3rd-party app: keeweb
Mar  4 20:10:52 www ownCloud[12758]: {updater} \OC\Updater::upgradeAppStoreApp: Update 3rd-party app: notes
Mar  4 20:11:00 www ownCloud[12758]: {updater} \OC\Updater::upgradeAppStoreApp: Update 3rd-party app: rainloop
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Repair MySQL collation
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Repair mime types
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Repair legacy storages
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Remove asset cache
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::info: Repair info: Asset cache cleared.
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Generate ETags for file where no ETag is present.
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::info: Repair info: ETags have been fixed for 0 files/folders.
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Clean tags and favorites
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::info: Repair info: 0 tags of deleted users have been removed.
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::info: Repair info: 0 tags for delete files have been removed.
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::info: Repair info: 0 tag entries for deleted tags have been removed.
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::info: Repair info: 0 tags with no entries have been removed.
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Drop old database tables
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::startProgress: Starting ... Drop old database tables (31)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: calendar_calendars (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: calendar_objects (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: calendar_share_calendar (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: calendar_share_event (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: file_map (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: foldersize (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: fscache (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: gallery_sharing (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: locks (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: log (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: media_albums (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: media_artists (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: media_sessions (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: media_songs (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: media_users (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: permissions (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: pictures_images_cache (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: principalgroups (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: principals (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: queuedtasks (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: sharing (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: clndr_calendars (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: clndr_objects (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: clndr_share_event (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: clndr_share_calendar (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: clndr_repeat (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: contacts_addressbooks (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: contacts_cards (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: contacts_cards_properties (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: gallery_albums (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance: Drop old database table: gallery_photos (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::finishProgress
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Drop old background jobs
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Remove getetag entries in properties table
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::info: Repair info: Removed 0 unneeded "{DAV:}getetag" entries from properties table.
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Repair outdated OCS IDs
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Repair invalid shares
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Remove old share propagation app entries
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Remove old (< 9.0) calendar/contact shares
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::startProgress: Starting ... Remove old (< 9.0) calendar/contact shares (4)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance:  (1)
Mar  4 20:11:06 www ownCloud[12758]: message repeated 3 times: [ {updater} \OC\Repair::advance:  (1)]
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::finishProgress
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Fix permissions so avatars can be stored again
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::startProgress: Starting ... Fix permissions so avatars can be stored again (2)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::advance:  (1)
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::finishProgress
Mar  4 20:11:06 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Remove shares of a users root folder
Mar  4 20:11:07 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Repair unmerged shares
Mar  4 20:11:07 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Move .step file of updater to backup location
Mar  4 20:11:07 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Add move avatar background job
Mar  4 20:11:07 www ownCloud[12758]: {updater} \OC\Repair::info: Repair info: Repair step already executed
Mar  4 20:11:07 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Add preview cleanup background jobs
Mar  4 20:11:07 www ownCloud[12758]: {updater} \OC\Repair::step: Repair step: Fix potential broken mount points
Mar  4 20:11:07 www ownCloud[12758]: {updater} \OC\Repair::info: Repair info: No mounts updated
Mar  4 20:11:07 www ownCloud[12758]: {updater} \OC\Updater::startCheckCodeIntegrity: Starting code integrity check...
Mar  4 20:11:17 www ownCloud[12758]: {PHP} PDOStatement::execute(): SSL operation failed with code 1. OpenSSL Error messages:#012error:0906D06C:PEM routines:PEM_read_bio:no start line#012error:0906D06C:PEM routines:PEM_read_bio:no start line at /srv/http/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#91
Mar  4 20:11:17 www ownCloud[12758]: {PHP} PDOStatement::execute(): MySQL server has gone away at /srv/http/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#91
Mar  4 20:11:17 www ownCloud[12758]: {PHP} PDOStatement::execute(): Error reading result set's header at /srv/http/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#91
Mar  4 20:11:17 www ownCloud[12758]: {core} Exception: {"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'INSERT INTO `oc_appconfig` (`appid`,`configkey`,`configvalue`) SELECT ?,?,? FROM `oc_appconfig` WHERE `appid` = ? AND `configkey` = ? HAVING COUNT(*) = 0' with params [\"core\", \"oc.integritycheck.checker\", \"[]\", \"core\", \"oc.integritycheck.checker\"]:\n\nSQLSTATE[HY000]: General error: 2006 MySQL server has gone away","Code":0,"Trace":"#0 \/srv\/http\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(128): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/srv\/http\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(996): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO `oc...', Array)\n#2 \/srv\/http\/nextcloud\/lib\/private\/DB\/Connection.php(215): Doctrine\\DBAL\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\n#3 \/srv\/http\/nextcloud\/lib\/private\/DB\/Adapter.php(114): OC\\DB\\Connection->executeUpdate('INSERT INTO `oc...', Array)\n#4 \/srv\/http\/nextcloud\/lib\/private\/DB\/Connection.php(253): OC\\DB\\Adapter->insertIfNotExist('*PREFIX*appconf...', Array, Array)\n#5 \/srv\/http\/nextcloud\/lib\/private\/AppConfig.php(172): OC\\DB\\Connection->insertIfNotExist('*PREFIX*appconf...', Array, Array)\n#6 \/srv\/http\/nextcloud\/lib\/private\/AllConfig.php(164): OC\\AppConfig->setValue('core', 'oc.integrityche...', '[]')\n#7 \/srv\/http\/nextcloud\/lib\/private\/IntegrityCheck\/Checker.php(453): OC\\AllConfig->setAppValue('core', 'oc.integrityche...', '[]')\n#8 \/srv\/http\/nextcloud\/lib\/private\/IntegrityCheck\/Checker.php(567): OC\\IntegrityCheck\\Checker->storeResults('core', Array)\n#9 \/srv\/http\/nextcloud\/lib\/private\/IntegrityCheck\/Checker.php(578): OC\\IntegrityCheck\\Checker->verifyCoreSignature()\n#10 \/srv\/http\/nextcloud\/lib\/private\/Updater.php(269): OC\\IntegrityCheck\\Checker->runInstanceVerification()\n#11 \/srv\/http\/nextcloud\/lib\/private\/Updater.php(124): OC\\Updater->doUpgrade('11.0.2.7', '11.0.1.2')\n#12 \/srv\/http\/nextcloud\/core\/Command\/Upgrade.php(261): OC\\Updater->upgrade()\n#13 \/srv\/http\/nextcloud\/3rdparty\/symfony\/console\/Command\/Command.php(256): OC\\Core\\Command\\Upgrade->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#14 \/srv\/http\/nextcloud\/3rdparty\/symfony\/console\/Application.php(818): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#15 \/srv\/http\/nextcloud\/3rdparty\/symfony\/console\/Application.php(186): Symfony\\Component\\Console\\Application->doRunCommand(Object(OC\\Core\\Command\\Upgrade), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#16 \/srv\/http\/nextcloud\/3rdparty\/symfony\/console\/Application.php(117): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#17 \/srv\/http\/nextcloud\/lib\/private\/Console\/Application.php(169): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#18 \/srv\/http\/nextcloud\/console.php(90): OC\\Console\\Application->run()\n#19 \/srv\/http\/nextcloud\/occ(11): require_once('\/srv\/http\/nextc...')\n#20 {main}","File":"\/srv\/http\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":116}
Mar  4 20:11:17 www ownCloud[12758]: {updater} \OC\Updater::failure: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_appconfig` (`appid`,`configkey`,`configvalue`) SELECT ?,?,? FROM `oc_appconfig` WHERE `appid` = ? AND `configkey` = ? HAVING COUNT(*) = 0' with params ["core", "oc.integritycheck.checker", "[]", "core", "oc.integritycheck.checker"]:#012#012SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
Mar  4 20:11:17 www ownCloud[12758]: {updater} \OC\Updater::updateEnd: Update failed
Mar  4 20:11:17 www ownCloud[12758]: {updater} \OC\Updater::maintenanceActive: Maintenance mode is kept active
Mar  4 20:11:17 www ownCloud[12758]: {updater} \OC\Updater::resetLogLevel: Reset log level to Warning(2)
</details>

**Comment by tcitworld** [comment]
Having the same issue with upgrade from 11.0.3 to 11.0.4.
On another server with same SSL connexion to MySQL, upgrading from 12.0.0 to 12.0.2 went without issues.

**Comment by tcitworld** [comment]
Got the same issue again with the 12.0.2 to 12.0.3 upgrade :
```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT DISTINCT(TABLE_NAME) AS `table`FROM INFORMATION_SCHEMA . COLUMNS       WHERE TABLE_SCHEMA = ?  AND (COLLATION_NAME <> 'utf8_bin' OR CHARACTER_SET_NAME
 <> 'utf8')    AND TABLE_NAME LIKE "oc_%"' with params ["framadrive"]:                                                                      
                                                                                                                                                  
SQLSTATE[HY000]: General error: 2006 MySQL server has gone away                                                       
Update failed
```
Again fixed by deactivating SSL connexion during upgrade.

**Comment by glz-io** [comment]
Similar issue with mysql ssl when upgrading 13.0.0 to 13.0.1

```
Starting code integrity check...
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_appconfig` (`appid`,`configkey`,`configvalue`) SELECT ?,?,? FROM `oc_appconfig` WHERE `appid` = ? AND `configkey` = ? HAVING COUNT(*) = 0' with params ["core", "oc.integritycheck.checker", "[]", "core", "oc.integritycheck.checker"]:

SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
Update failed
Maintenance mode is kept active

```

**Comment by MorrisJobke** [comment]
> Upgrade work fine when disabling SSL.

Thanks for the hint. Let's continue this one as well in #8863. @MEitelwein @tcitworld Does disabling the SSL work for you or is the problem then still there?
