### ISSUE TITLE
[BITV] 9.4.1.1/0.2  On the page, there are multiple IDs that are identical - see "resourceNameFintestExplorer".

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#37098]
<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-3fd73cfb9c-v0-n2

</details>

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-3fd73cfb9c-v0-n1

</details>

---

- [x] Page 1 — Login (_seems to be fixed already_)
  Anmelden – Nextcloud
  https://try.nextcloud.com/ltd/a11y/index.php/login
- [x] Page 2 — Dashboard
  https://github.com/nextcloud/server/pull/40768
  Dashboard - Nextcloud
  https://try.nextcloud.com/ltd/a11y/index.php/apps/dashboard/
- [x] Page 3 — Files
  https://github.com/nextcloud-libraries/nextcloud-vue/pull/4606
  https://github.com/nextcloud-libraries/nextcloud-vue/pull/4607
  https://github.com/nextcloud/server/pull/40771
  Files - Nextcloud
  https://try.nextcloud.com/ltd/a11y/index.php/apps/files/
- [x] Page 4 — Photos (incl. Viewer) (_same as files_)
  All your media - Photos - Nextcloud
  https://try.nextcloud.com/ltd/a11y/index.php/apps/photos/
- [x] Page 5 — Activity (_seems to be fixed already_)
  All activities - Activity - Nextcloud
  https://try.nextcloud.com/ltd/a11y/index.php/apps/activity/
- [x] Page 6 — Personal info (_seems to be fixed already_)
  Personal info - Personal settings - Nextcloud
  https://try.nextcloud.com/ltd/a11y/index.php/settings/user
- [x] Page 7 — Logging (_seems to be fixed already_)
  Logging - Administration settings - Nextcloud
  https://try.nextcloud.com/ltd/a11y/index.php/settings/admin/logging
- [x] Page 8 — Active users
  https://github.com/nextcloud-libraries/nextcloud-vue/pull/4607
  Active users - Users - Nextcloud
  https://try.nextcloud.com/ltd/a11y/index.php/settings/users
- [x] Page 9 — User documentation (_seems to be fixed already_)
  User documentation - Help - Nextcloud
  https://try.nextcloud.com/ltd/a11y/index.php/settings/help
- [x] Page 10 — Documents (_same as Files_)
  Documents - Files - Nextcloud
  https://try.nextcloud.com/ltd/a11y/index.php/apps/files/?dir=/Documents&fileid=689

**Comment by ShGKme** [comment]
Simple scrip for testing

```js
const ids = new Map();
for (const el of document.querySelectorAll('[id]')) {
    if (ids.has(el.id)) {
        ids.get(el.id).push(el)
    } else {
        ids.set(el.id, [el])
    }
}
const duplicates = [...ids.entries()].filter(([id, els]) => els.length > 1)
console.log(duplicates.length ? '❌' : '✅', new Map(duplicates))
```

**Comment by ShGKme** [comment]
Reopen until `@nextcloud/vue` is updated on the server.
