### ISSUE TITLE
[BITV] 9.4.1.2/3.10 - The "Details" section contains a tab list that has not been implemented correctly. (2)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#37107]
- [x] https://github.com/nextcloud-libraries/nextcloud-vue/pull/4456
- [x] https://github.com/nextcloud/server/pull/40084
- [x] Clarify whether navigation quirks https://github.com/nextcloud-libraries/nextcloud-vue/pull/4456#pullrequestreview-1595982598 are acceptable with @michaelnissenbaum
- [x] https://github.com/nextcloud-libraries/nextcloud-vue/pull/4663
- [x] https://github.com/nextcloud-libraries/nextcloud-vue/pull/4680
- [x] https://github.com/nextcloud/server/pull/41070

It is recommended to set the role="tablist" on the ul element and remove the nav element. 

```
<nav data-v-76ae79ca="" role="tablist" class="app-sidebar-tabs__nav">
```

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-bfbf07e5c3-v3-n10

</details>

- [x] 9.4.1.2/10.10 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-bfbf07e5c3-v10-n10

**Comment by Pytal** [comment]
The current implementation 
![image](https://github.com/nextcloud/server/assets/24800714/975f99d7-1da5-4c39-aa44-49094bfa9650)
uses a `nav` wrapper with `role="tablist"` around `span` elements with `role="tab"`

Will changing `nav` → `ul` and `span` → `li` while keeping the roles meet a11y requirements @michaelnissenbaum?

**Comment by Pytal** [comment]
Understood 👍

Would making the input `type="button"` be sufficient or is a `button` element necessary to meet a11y requirements @michaelnissenbaum?

**Comment by michaelnissenbaum** [comment]
From my perspective, it's irrelevant in this case, as shown in the example **the native role is overridden by the role="tab"**.

```

<button id="tab-1"
            type="button"
            role="tab"
            aria-selected="true"
            aria-controls="tabpanel-1">
      <span class="focus">
        Maria Ahlefeldt
      </span>
    </button>
```

**Comment by Pytal** [comment]
Is the tablist implementation on https://try.nextcloud.com/ltd/a11y/ accessible @michaelnissenbaum ?

**Comment by michaelnissenbaum** [comment]
From my perspective, the implementation of the tab bar is still not 100% accessible. The use of button elements (type="button") nested within "span" elements with the role "tab" results in being able to access the individual tabs one by one using the TAB key. Depending on the screen reader, they may not be identified as tabs but rather as buttons. Additionally, navigation through the tabs should only be possible using arrow keys. Even when using Chromium-based browsers, both the "tab" and "group" roles are announced in the reading mode. Here's another example for reference: [https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Tab_Role).
