### ISSUE TITLE
[BITV] 9.4.1.2/3.5 - The "New file/folder menu" button opens a menu and should therefore be implemented as a button and not as a link. (2)

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#37102]
- [x] Additionally, make sure that the value of the aria-expanded attribute is updated as it always has a value of "true". 

<details>
<summary>Details</summary>

https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-bfbf07e5c3-v3-n5

</details>

- [x] 9.4.1.2/10.5 - https://report.bitvtest.de/default-en/d63601ac-cb34-4645-8256-66bec78964a0.html#checkpoint-bfbf07e5c3-v10-n5

**Comment by Pytal** [comment]
New file/folder button not available on master with F2V

Pending upload implementation

**Comment by Pytal** [comment]
Uploader on master
