### ISSUE TITLE
Missing border in Contacts

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/server#3710]
I use your demo of NextCloud and founded a missing border. On the left is a grey border for the sidebar. On the next 2 divs is no border anymore. It would be good, if a border is here too to seperate it.

![unbenannt-1](https://cloud.githubusercontent.com/assets/1473674/23582222/fd0546ac-0125-11e7-979e-253d3e4447d4.png)

**Comment by MariusBluem** [comment]
In my opinion yes, but what do the others think? Was there a design-decision to skip this border 🤔
@nextcloud/contacts

**Comment by MariusBluem** [comment]
Thank you for your report! This is the wrong repository. Contacts issues are handled over here: 
https://github.com/nextcloud/contacts/issues ... Please re-open your issue over there 👊
