### ISSUE TITLE
Question and Improvement of "Contacts"

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/server#3711]
I use your demo on NextCloud.com and have a question and enhancement.

1. How I can show the contacts which I have assigned a addressbook? (see screenshot, please)
2. If I create a addressbook, the Label is missing by select an addressbook in the contact form (see screenshot, please)
3. If I create an contact, the placeholder of the name is not deleted, when I will type the name. I must delete "Neuer Kontakt" manually. It is possible to delete it by highlighting the input? (like an "placeholder in HTML5)

Thanks in advance!

![unbenannt-1](https://cloud.githubusercontent.com/assets/1473674/23582289/9f440272-0127-11e7-95b6-3d688e67ec85.png)

**Comment by MariusBluem** [comment]
Thank you for your report! This is the wrong repository. Contacts issues are handled over here: 
https://github.com/nextcloud/contacts/issues ... Please re-open your issue over there 👊
