### ISSUE TITLE
nextcloud upgrades break apps, doesn't explain why, have zero documentation online as to why

### ISSUE THREAD

**Issue by bahbarnett** [nextcloud/server#3713]
### Steps to reproduce
1.  Upgrade from 11.0.1 to 11.0.2
2.  A quick, cryptic message about 'calendar' and 'contacts' being disable flashes on the screen for a split second
3. 'calendar' and 'contact' apps aren't in admin/apps enabled or disable, can't be found
4. https://docs.nextcloud.com/server/11/admin_manual/maintenance/manual_upgrade.html mentions nothing of this, doesn't explain it will happen, doesn't describe what to do when it does

### Expected behaviour
At the very least, there should be some documentation about how to re-enable and/or upgrade the calendar and contacts app.

### Actual behaviour
Contact and calendar apps are missing, can't be found in the enabled or disable apps list with the admin portal. 

### Server configuration
Debian Jessie
Apache, MySQL

**Comment by bahbarnett** [comment]
Wait.

So, when I enable apps they show up in 'enabled'.  When apps aren't enabled, they don't show up in 'disabled'?

This strangeness is the source of my pain. :/

1) Nextcloud says 'disabling apps'
2) I log in
3) Apps aren't in disabled

I don't understand why 'official' apps are sometimes in 'disabled' and sometimes not.

There should be:

- all apps are in either enabled or disabled

OR

- get rid of 'disabled', or call it something else (like, 'generic' apps or something?!)

**Comment by bahbarnett** [comment]
To further comment on this -- if 'disabled apps' are for apps I've disabled, why aren't disabled apps (like my calendar and contacts app) in there as well?

Either they were manually disabled, or not...

**Comment by nickvergessen** [comment]
> A quick, cryptic message about 'calendar' and 'contacts' being disable flashes on the screen for a split second

That's weird, for me (I just did an update today) the message was displayed until I manually reloaded the page or followed the link to reload the page.

All apps that are not enabled are listed in the disabled section. Please make sure to scroll through the complete list or use the search to find the app you are looking for, since the list is currently bugged a bit and is sorted by alphabet twice (first official apps, then unofficial apps).

**Comment by bahbarnett** [comment]
Er?  You're saying it paused during the upgrade, and said "disabling contacts and calender", then made you manually reload the page, or click on a link?

For me, about 100 info / update messages appeared on my browser, flashing by rapidly.  Had I not been staring at the screen, I would not have even noticed the disable message.

Once the upgrade was done, I had to log in again.

You're saying all apps are supposed to be in the disable section, but that is most certainly not the case for me.  Contacts and apps weren't there, and only a handful of apps are in that pane.

In fact, I just clicked on '+ apps' at the top of the screen now, and the only thing I am presented with are 'enabled' and 'not enabled' apps, along with 'developer documentation'.

At times, I've gone into the +app page, and there have been categories for apps.  Those aren't there today.

There is indeed something 'weird' here.

- I randomly have 'categories' for +apps, like 'productivity' or whatever they are called in the +app page (they aren't there now, but there are sometimes about 6 or 7 of them)

- 'disabled' apps sometimes appear in categories, and sometimes in 'disabled' apps

- it seems like when 'categories' appear, they take precedence over 'disabled apps'

When I had the issue with contacts, there were at best 5 apps in 'disabled' apps, but many apps in 'categories', some disabled, some not.

**Comment by nickvergessen** [comment]
Ah then you watched the full log of the update. there is a message that the apps were disabled right below/above the log. So actually you shouldn't miss it.
I guess you just refreshed the page out of panic after the upgrade was done, without reading the message ;)

As for the apps stuff, that sounds odd. but yeah categories should still exist. Can you check your config.php whether you set a custom app store URL there?

**Comment by bahbarnett** [comment]
As a 20 year old sysadmin, I assure you upgrading a personal nextcloud server, which I'm just playing with (with intentions to move there perm), has no potential to instill panic.  If production servers going down at 2am doesn't, this won't. :P

I saw that apps were disabled, and that they should be re-enabled.  Yet, I *couldn't* find them to do so.

They didn't show in 'disabled', were in categories only, and when I first went to that page .. categories were MIA!  In other words, 're-enable these apps' became cryptic -- because they were utterly and completely missing *to* re-enable.

Couple that with the wonder of Google, and some people complaining that one needs to perform update statements on the DB to re-enable them, AND the fact that there is ZERO documentation ANYWHERE about this behaviour, why it is done, and what is required to re-enable them?

Well.  If something goes wrong, there's zero clue.  Not without a bug report, or poking at code directly.

Back to your question.

There's no custom app store config in config.php.  The file is only 25 lines long.

Note, that this is a completely stock install, with contact + calendar installed afterwards.

Also note that this VM/nextcloud instance has zero network access, except to my local lan.

If this causes issues with apps being undetectable to re-enable them, then that's weird.  I even opened up my firewall, after I couldn't initially find those apps, and still had issues with them not being in 'disabled'.

Regardless of the stance on 'we support' or don't, there's no guarantee that upstream connectivity will exist during an upgrade.  Bad routing, downed servers, you name it -- and, anyone else would experience this edge-case behaviour.

Not to mention anyone sandboxing, or like myself?

Never, ever wanting to expose nextcloud (or any app like it) to the net.  All my syncing only happens when I'm home...

**Comment by MorrisJobke** [comment]
Starting with 12 we no longer disable apps by default if you run PHP 7.0+ also we try to get updates from the App Store during the upgrade to make sure, that the app is compatible with the new version of the server.

If the App Store is not reachable we just use the local version. At least those changes in 12 should make the update a bit better. Also if there is something going wrong we increased the log output a lot to make trouble shooting easier.

I hope this helps for this problem here and I will close this ticket now. If there are still problems with the upgrade to 12 feel free to report back.

Thank you
