### ISSUE TITLE
.htacces and .user.ini missing from the zip archive 

### ISSUE THREAD

**Issue by Unknown-0** [nextcloud/server#3715]
### Steps to reproduce
1.When download and extract the zip archive .user.ini and .htacces are missing
2. Have to download and extract the tar.bz2 to recover this files

### Expected behaviour
Installation of nextcloud work fine

### Actual behaviour
I have an error in the administration page : "Des fichiers n'ont pas passé la vérification d’intégrité. Consultez la documentation pour avoir plus d'informations sur comment résoudre ce problème."

### Server configuration
**Operating system**:
Debian 8

**Web server:**
Nginx
**Database:**
Mysql
**PHP version:**
php5
**Nextcloud version:** (see Nextcloud admin page)
10.0.2

**Where did you install Nextcloud from:**
From the zip archive of the website

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

```

**Comment by nickvergessen** [comment]
Can not reproduce. They are in the package just fine.
It might be that the program you use to unzip the package didn't make them visible or extract them correctly.
Please try another one.
