### ISSUE TITLE
Update Dockerfile and docker-compose in .devcontainer directory

### ISSUE THREAD

**Issue by sorbaugh** [nextcloud/server#37169]
The current implementation of the Docker Image in/.devcontainer uses PHP7.4, which is no longer compatible with the minimal PHP requirement of PHP 8.0 for developers trying to set up a local development environment with docker. Updating (and maybe tweaking a bit) the current implementation would help developers interested in contributing to set up their local environment quicker. What do you think?

**Comment by kesselb** [comment]
Sounds good! Please send a pull request ;)
