### ISSUE TITLE
Possibility to exclude trashbin from automatic backup

### ISSUE THREAD

**Issue by djamn** [nextcloud/server#37160]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I have enabled automatic backups on Nextcloud. On my small system with a few users, a lot of deleted files have accumulated over time. All deleted files were included in the automatic backup. So my backup had 80GB before a trashbin delete, while it only had ~35GB afterwards. 

**Describe the solution you'd like**
I would like to have a way to not have to include the recycle bin in the automatic backup creation by e.g. using a setting. This way I don't have to delete the recycle bin of every user from time to time (because otherwise the backup file would become quite large again over time) and be still able to restore older deleted files from the recycle bin.

**Comment by joshtrichards** [comment]
Hi @djamn - What automatic backups are you referring to? NC core (server) doesn't have a built-in backup mechanism.
