### ISSUE TITLE
Allow fine grained control of permissions for shared links

### ISSUE THREAD

**Issue by 5er** [nextcloud/server#3716]
It would be nice to have an option to allow "fine grained control" of permissions for shared links.
Right now it is only possible to limit, for example, deleting files if you are sharing with other users and groups.
![2017-03-05 14_33_37-settings](https://cloud.githubusercontent.com/assets/1439227/23587769/53d26ab8-01b3-11e7-8eb2-fede1b4a60df.png)

It would be awesome to have the same amount of control for shared links:
![untitled-1](https://cloud.githubusercontent.com/assets/1439227/23587685/1907b2cc-01b2-11e7-89cf-482eca22b593.jpg)

Here is a [link to the forum discussion](https://help.nextcloud.com/t/allow-public-upload-and-show-but-not-delete/2874) about this feature.

**Comment by MorrisJobke** [comment]
We are currently working on simplify the whole interface:

* combine link shares into the list with user shares: #5336
* reduce the permissions to a few useful ones: #8479 
* moving the link permissions into a popup: #7010

I will close this one here then in favor of the 3 mentioned ones above.
