### ISSUE TITLE
[Bug]: Data corruption after moving or copying files

### ISSUE THREAD

**Issue by TPrieser** [nextcloud/server#37171]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After copying or moving files from one folder to another, inside our nextcloud, the files get corrupted.
This happens from time to time, sometimes copying/moving works just fine.

Workaround for us right now is to download the file from one folder and upload them to the new folder.

### Steps to reproduce

1. Select one or multiple files or subfolders from a folder
2. copy or move them to another folder
3. file corrupted, cant be opened anymore, preview is not working, after download it cant be opened in excel or word and so on

### Expected behavior

Files should not corrupt because of copy/move function within Nextcloud.

### Installation method

Community Manual installation with Archive

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - bruteforcesettings: 2.5.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - documentserver_community: 0.1.13
  - encryption: 2.13.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_antivirus: 4.0.2
  - files_external: 1.17.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - groupfolders: 13.1.1
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - onlyoffice: 7.6.8
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - ransomware_protection: 1.14.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - sharingpath: 0.4.4
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - twofactor_backupcodes: 1.14.0
  - twofactor_totp: 7.0.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - checksum: 1.2.0
  - files_pdfviewer: 2.0.1
  - officeonline: 1.1.4
  - ransomware_detection: 0.10.0
  - richdocuments: 7.1.1
  - richdocumentscode: 22.5.802
  - suspicious_login: 4.2.1
  - user_ldap
```

**Comment by szaimen** [comment]
Hi, which nc version?

**Comment by TPrieser** [comment]
[Nextcloud Hub 3] (25.0.3)

**Comment by PVince81** [comment]
encryption + group folders, probably you moved something inside a group folder or from outside to inside or the other way around, known issue here: https://github.com/nextcloud/groupfolders/issues/1896

if you can confirm this, please close as duplicate of the group folder issue

**Comment by TPrieser** [comment]
> encryption + group folders, probably you moved something inside a group folder or from outside to inside or the other way around, known issue here: [nextcloud/groupfolders#1896](https://github.com/nextcloud/groupfolders/issues/1896)
> 
> if you can confirm this, please close as duplicate of the group folder issue

This seems to be it, thank you for the help, will close this issue
