### ISSUE TITLE
User can share root directory

### ISSUE THREAD

**Issue by Ko-** [nextcloud/server#3718]
I would like my users to be able to share their root folder with other users, as a means of allowing admin users to see all data stored by other users.

This is very similar two [this ownCloud issue](https://github.com/owncloud/core/issues/14049) and based on [this forum topic](https://help.nextcloud.com/t/sharing-root-directory/9666).

**Comment by nickvergessen** [comment]
IIRC this was removed intentionally, but maybe @schiessle or @rullzer know more.

**Comment by rullzer** [comment]
It was possible (but that was a bug!). We have no way to properly indicate this. Plus you risk running into cyclic shares very very fast.

Long story short it opens up a big can of worms.

Admins most likely have other means of inspecting your data.

**Comment by Ko-** [comment]
Admins with server access, sure, but I'm talking about people who don't know ssh/sftp/anything.

Personally I don't see why cyclic shares should necessarily be a problem, but I'm not familiar with the Nextcloud codebase. I imagine that it could behave just as a symlink pointing to a parent directory, where you just keep appending to the current working directory while traversing directories. Then you only have to make sure that you never search for all content, but only consider one depth level at a time, but that appears feasible to me.

Would it be an easy patch to re-introduce this bug?

**Comment by rullzer** [comment]
> Would it be an easy patch to re-introduce this bug?

Nope.

Basically the point is that it introduces a level of nesting and possible cycles. Since the whole nextcloud fs of a user is presented as is. And if in the depths of one directory a file changes we have to propegate this change way back up to the root so sync clients etc know something has changed.

**Comment by rullzer** [comment]
I suggest to try the https://apps.nextcloud.com/apps/impersonate that seems to solve this problem.
