### ISSUE TITLE
installing under user account Run as Administrator /win7/

### ISSUE THREAD

**Issue by lustikummut** [nextcloud/server#3719]
### Steps to reproduce
1. use windows computer (i have win 7 x64) and install Nextcloud computer app. account used was user rights. Run as Administrator; type admin password and install (next; next etc) and installer says that not possible to open folder because it does not exist. so created Nextcloud folder for user user and pointed sync app to it. 
i found that installer installs and syncs Administrator users folder. not the user folder.

**Comment by nickvergessen** [comment]
Can you please report this to https://github.com/owncloud/client
We only theme the client currently, so the issue should be with the owncloud client as well.
