### ISSUE TITLE
Design improvements to "Shared" indicator in files list

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#37208]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
2 issues with the "Shared" indicator in the files list:
- It is not super present
- The icons are not aligned with the icons of non-shared files

**Describe the solution you'd like**
- The text and icon of the "Shared" indicator could be colorized in `var(--color-primary-element)`
- The icons would look better if to the right of the "Shared" text, so they align with the other icons in the list

**Additional context**
Current:
![image](https://user-images.githubusercontent.com/925062/224966680-db5c41d3-597d-4603-8cfe-c9039ee9b89b.png)

Proposed:
![Sharing colorized](https://user-images.githubusercontent.com/925062/224966705-ca66773f-b6b1-4abe-a7a3-b170873e9db4.png)

**Comment by gennaios** [comment]
I think the share action could be moved to the action menu. I don’t think users are constantly sharing files such that it needs a separate icon. Then the current icon could be shown only for shared files. Such would make it I think much more visible plus there would be more space for longer file names.

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/issues/38156
