### ISSUE TITLE
Issues with External Nextcloud Storage

### ISSUE THREAD

**Issue by stefanovazzocell** [nextcloud/server#3720]
Similar Issue here

### Steps to reproduce
1. Add share from another NextCloud server trough the External Storage plugin

### Expected behaviour
I should be able to access the folder.

### Actual behaviour
Get an error (503 | Sabre\DAV\Exception\ServiceUnavailable): Storage is temporarily not available

### Server configuration
**Operating system**:
Ubuntu
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
7.0+
**Nextcloud version:** (see Nextcloud admin page)
11.0.2 (stable)
**Updated from an older Nextcloud/ownCloud or fresh install:**
(Fresh) New Install
**Where did you install Nextcloud from:**
https://nextcloud.com/ - Archive version
**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.

Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - comments: 1.1.0
  - dav: 1.1.1
  - encryption: 1.4.1
  - external: true
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.1.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml

</details>

$CONFIG = array (
  'instanceid' => '***',
  'passwordsalt' => '***',
  'secret' => '***',
  'trusted_domains' =>
  array (
    0 => 'cloud.stefanovazzoler.com',
  ),
  'datadirectory' => '***',
  'overwrite.cli.url' => 'https://cloud.stefanovazzoler.com',
  'dbtype' => 'mysql',
  'version' => '11.0.2.7',
  'dbname' => '***',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '***',
  'dbpassword' => '***',
  'logtimezone' => 'UTC',
  'installed' => true,
);

<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "ockdlk2gei4x",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.stefanovazzoler.com"
        ],
        "datadirectory": "\/var\/www\/other\/cloud-data",
        "overwrite.cli.url": "https:\/\/cloud.stefanovazzoler.com",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true
    }
}

</details>

**Are you using external storage, if yes which one:** nextclout

**Are you using encryption:** yes (disabled on external storage)

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

# No Errors

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"***","remoteAddr":"***","app":"core","message":"Default encryption module not loaded","level":3,"time":"2017-03-05T17:00:00+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Sharename","user":"***","version":"11.0.2.7"}
{"reqId":"***","remoteAddr":"***","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Storage is temporarily not available\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/subdomain\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(939): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('Sharename')\\n#1 \\\/var\\\/www\\\/subdomain\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(336): Sabre\\\\DAV\\\\Server->getPropertiesForPath('Sharename', Array, 1)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/subdomain\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/subdomain\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#5 \\\/var\\\/www\\\/subdomain\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/subdomain\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/subdomain\\\/cloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/subdom...')\\n#8 {main}\",\"File\":\"\\\/var\\\/www\\\/subdomain\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":162,\"User\":\"***\"}","level":4,"time":"2017-03-05T17:00:00+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Sharename","user":"***","version":"11.0.2.7"}
</details>

#### Browser log
<details>
<summary>Browser log</summary>

PROPFIND https://cloud.stefanovazzoler.com/remote.php/webdav/Tungsten 503 ()
</details>

**Comment by LuCu11** [comment]
I have the an similar issue, I get the same 503 error, but I access the SMB-Share via WebDav, and the message comes after several minutes without access

**Comment by LuCu11** [comment]
I have new infos:
I did a clean installation with nextcloud 11, all works pretty fine!
yesterday a did a Debian upgrade, and the issue comes back :-(
I have no idea where should be the problem, is there anybody who can help us?

**Comment by LuCu11** [comment]
it seems the issue only occours, when the option Username and Password (Benutzername und Passwort in german) is set, when I set the option "username recorded, saved in Database"? (Benutzer eingetragen, in Datenbank gespeichert) it works fine

**Comment by MorrisJobke** [comment]
> I have no idea where should be the problem, is there anybody who can help us?

Sadly we can't reproduce this. Maybe ask in the forums (https://help.nextcloud.com) for help, because that is the place were setup specific problems are discussed. If you have a clear way to reproduce this, we are happy to build a fix for that into our code. Sorry for the inconvenience

Thanks
