### ISSUE TITLE
notifications: Failed to enable app notifications

### ISSUE THREAD

**Issue by mlsxlist** [nextcloud/server#3721]
### Steps to reproduce
Update Nextcloud via web updater app

### Expected behaviour
Nextcloud should update without an error message

### Actual behaviour
Nextcloud updates with the error message **notifications: Failed to enable app notifications**

### Server configuration
**Operating system**: Debian GNU/Linux 8

**Web server:** Apache/2.4.10

**Database:**   sqlite3 Version: 3.8.7

**PHP version:** 5.6.29

**Nextcloud version:** Nextcloud 11.0.2 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 11.0.1. to 11.0.2 

**Where did you install Nextcloud from:** web updater

**Comment by nickvergessen** [comment]
Anything in the nextcloud.log file?

**Comment by mlsxlist** [comment]
Not really. This is what I see in the nextcloud.log file:

{"reqId":"arcww83ix0rwFsGIml0d","remoteAddr":"1.2.3.4","app":"notifications","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Failed to enable app notifications\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/myinstancename\\\/lib\\\/private\\\/Installer.php(445): OC\\\\Installer::installShippedApp('notifications')\\n#1 \\\/var\\\/www\\\/myinstancename\\\/lib\\\/private\\\/Updater.php(252): OC\\\\Installer::installShippedApps(true)\\n#2 \\\/var\\\/www\\\/myinstancename\\\/lib\\\/private\\\/Updater.php(124): OC\\\\Updater->doUpgrade('11.0.2.7', '11.0.1.2')\\n#3 \\\/var\\\/www\\\/myinstancename\\\/core\\\/ajax\\\/update.php(194): OC\\\\Updater->upgrade()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/myinstancename\\\/lib\\\/private\\\/Installer.php\",\"Line\":481}","level":3,"time":"2017-03-06T06:15:04+01:00","method":"GET","url":"\/myinstancename\/core\/ajax\/update.php?requesttoken=ysToeeUlzGAFD6gW7rcVyRhs%2BFLWUua%2BonsM5cs8QJU%3D%3AuZyKKrVhvTZ2bsAvotNjhGg7oCqZP6XuxC9mqJFIDdg%3D","user":"--","version":"11.0.1.2"}
{"reqId":"arcww83ix0rwFsGIml0d","remoteAddr":"1.2.3.4","app":"updater","message":"\\OC\\Updater::failure: notifications: Failed to enable app notifications","level":3,"time":"2017-03-06T06:15:04+01:00","method":"GET","url":"\/myinstancename\/core\/ajax\/update.php?requesttoken=ysToeeUlzGAFD6gW7rcVyRhs%2BFLWUua%2BonsM5cs8QJU%3D%3AuZyKKrVhvTZ2bsAvotNjhGg7oCqZP6XuxC9mqJFIDdg%3D","user":"--","version":"11.0.1.2"}

**Comment by mlsxlist** [comment]
Anything else you need?

**Comment by nickvergessen** [comment]
Did you have the notifications app disabled before? and also did you install 11.0.1 or 10 or something earlier?

**Comment by MorrisJobke** [comment]
We can't reproduce this with and upgrade path from 10 and from 11. I will close thus this ticket. We will reopen if this is still a case for you and you can provide the information that @nickvergessen requested.
