### ISSUE TITLE
webp thumbnail feature here

### ISSUE THREAD

**Issue by YTOAA** [nextcloud/server#37220]
You must click on the "webp" pie to view the file. Thumbnail pictures do not displayed. This is very surprising in 2023.

**Comment by szaimen** [comment]
WebP support can already be easily added by installing and enabling imagemagick and the WebP preview provider or adding one docker container: https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html#previews

For further help on this refer to https://help.nextcloud.com

**Comment by YTOAA** [comment]
> WebP support can already be easily added by installing and enabling imagemagick and the WebP preview provider or adding one docker container: https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html#previews
> 
> For further help on this refer to https://help.nextcloud.com
I don't see the imageagick or WebP preview provider app. Where should I find it?

**Comment by solracsf** [comment]
WebP preview works fine if configured correctly, even if animated.
![image](https://user-images.githubusercontent.com/12234510/226347398-85bb1ffc-4b5d-4ea3-9ab2-f8c514a57d46.png)

Original file is https://www.photoshoplus.fr/images/articles/informatique/poupeeanime3.webp

**Comment by YTOAA** [comment]
> WebP 미리보기는 애니메이션이 적용된 경우에도 올바르게 구성되어 있으면 제대로 작동합니다. ![영상](https://user-images.githubusercontent.com/12234510/226347398-85bb1ffc-4b5d-4ea3-9ab2-f8c514a57d46.png)
> 
> 원본 파일은 [https://www.photoshopplus.fr/images/articles/informatique/poupeeanime3.webp 입니다.](https://www.photoshoplus.fr/images/articles/informatique/poupeeanime3.webp)



gd-webp cannot allocate temporary buffer at /config/www/nextcloud/lib/private/legacy/OC_Image.php#722
--

Even with the above image, the thumbnail still fails to be created with the same error as above.
