### ISSUE TITLE
Auth  - Session

### ISSUE THREAD

**Issue by patrikx3** [nextcloud/server#3723]
It is a simple question.
I am using the users_ldap component.
What is weird is that when I refresh a page or click multiple times on the web page I can see on my server it generates a new LDAP/Samba Auth.

Which is weird. It doesn't need to use any other user backend once we are in an authed session.
I was thinking that once the user is in the session, it is not hitting the auth backend, 
but it is not. every time http request, it also generates a new auth backend.

So then why do we use the session?

right now with users_ldap / samba it is very high cpu usage and it is weird why it hits the auth backend every time a new request is generated when it is in the session already,

**Comment by patrikx3** [comment]
when i click multiple times on the web, it hits samba every times (via the ldap component)

when i use the admin which does not use ldap in owncloud/nextcloud, it does not hit samba
it should use ldap only when i login, still it constant does auth.

not using *cloud:
![image](https://cloud.githubusercontent.com/assets/4770180/23606370/b383350c-0260-11e7-8b27-72f49f9718a1.png)

i use owncloud for its own admin user (root) - multiple refreshes, not using samba at all
![image](https://cloud.githubusercontent.com/assets/4770180/23606793/9066c974-0262-11e7-9042-964e31de757d.png)

i use ldap backend user (patrikx3) - it uses samba with high cpu usage
![image](https://cloud.githubusercontent.com/assets/4770180/23606708/34887738-0262-11e7-8560-cf44521c40fc.png)

**Comment by patrikx3** [comment]
hello, the auth / session is not correct is not replied, why?

**Comment by patrikx3** [comment]
sorry i use nextcloud now, but i migrated and i cannot change everything, so the user name is owncloud in my server...

**Comment by MorrisJobke** [comment]
Closing due to deleted account. Sorry to not have seen this earlier.
