### ISSUE TITLE
add Content-Length header when returning xmls

### ISSUE THREAD

**Issue by PechenTreski** [nextcloud/server#3724]
### Steps to reproduce
1. make a request like https://nextcloud.example.com/remote.php/dav/addressbooks/users/juza/contacts/
2. take a look at response headers
3. "content-type:application/xml; charset=utf-8" presents, but there is no header about the content length :)

### Expected behaviour
Content-Length should present, so nginx could compress the response with gzip

### Actual behaviour
No headers make nginx ignore compressing. My nextcloud server is run at home, where I have only 5 Mbps of upload speed, so the list of contacts is being downloaded for 3 annoying sec

### Server configuration
**Nextcloud version:** (see Nextcloud admin page) 11.0.2

**Contacts version:** (see Nextcloud apps page) 1.5.3

**Comment by nickvergessen** [comment]
Just had a look and this needs to be done in the 3rd party project:
https://github.com/fruux/sabre-dav

https://github.com/nextcloud/3rdparty/blob/a5036f09aca6d817f55e36c101684ac95120bdea/sabre/dav/lib/DAV/Server.php#L317-L319

Feel free to report the issue to them
