### ISSUE TITLE
Error on files drop has no visible feedback

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#3726]
### Steps to reproduce
1. Add Access Control rule that prevents uploads (just block by time and select the full range)
2. Share a file as "files drop"
3. Upload a file into the files drop

### Expected behaviour
There should be something like ❌  as a feedback on the file list

### Actual behaviour
Loading spinner continues forever

@nextcloud/javascript

**Comment by MorrisJobke** [comment]
Maybe @danxuliu wants to look into this.

Or @individual-it because of #4212

**Comment by individual-it** [comment]
Need some investigation but might be a relative of #4389

**Comment by individual-it** [comment]
if you don't want to show the reason why the upload failed this PR should fix it #4545
