### ISSUE TITLE
Allow multiselect and assign tags in Tags tab

### ISSUE THREAD

**Issue by LovelyA72** [nextcloud/server#37288]
**Is your feature request related to a problem? Please describe.**
There's currently no way to multi-select photos in `systemtagsfilter` to further assign tags.

I have a lot of photos stored in my private nextcloud. I assigned them with tags that covers different scope sizes. For example photos tagged with `Disneyland` may contains smaller tags like `Splash Mountain` or `Main Street USA` while photos tagged with `Universal Studios` might also contains smaller tags like `Super Nintendo World` or `Studio Tour`. 

**Describe the solution you'd like**
When I am in `systemtagsfilter`, i'd like to be able to multi-select items to assign more tags to them. 

**Describe alternatives you've considered**
Assign tags in the Photos app. There's an issue in Photos back in 2020 but there was also no update to that issue since 2020. https://github.com/nextcloud/photos/issues/551

**Additional context**
This feature is already present in the `All files` tab. But that tab only show files by folder. There's just need to have a simple port to port this feature to the `Tags` tab.

**Comment by skjnldsv** [comment]
Merged with https://github.com/nextcloud/server/issues/45935
