### ISSUE TITLE
Limit drone push builds to master and stable branches

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#3729]
We currently have two CI runs for each PR: push+pr. This redundancy is wasting CI power, possibly resulting in slower builds. How about we exclude any branches except master and stable branches from the push builds, as documented [here](http://readme.drone.io/usage/skipping-builds/)? That's also what we do with [projects that run on travis](https://github.com/nextcloud/mail/blob/2e51ef943be9b09151b4960fd3a6aa1aa81178ad/.travis.yml#L31-L35).

@LukasReschke @MorrisJobke @nextcloud/infrastructure objections? Has anybody tried that before?

**Comment by MorrisJobke** [comment]
> We currently have two CI runs for each PR: push+pr. This redundancy is wasting CI power, possibly resulting in slower builds. How about we exclude any branches except master and stable branches from the push builds, as documented here? That's also what we do with projects that run on travis.

Sadly this doesn't work, because there is a bug in the drone code and it then doesn't execute the PR as well -.- But feel free to test again.

**Comment by MorrisJobke** [comment]
Test PR: #3743

**Comment by MorrisJobke** [comment]
> Test PR: #3743

Seems that it is fixed now \o/
