### ISSUE TITLE
No way to pre-configure system cron versus ajax.

### ISSUE THREAD

**Issue by kyrofa** [nextcloud/server#3732]
I'm one of the maintainers of the [Nextcloud snap](https://github.com/nextcloud/nextcloud-snap). We use `autoconfig.php` to setup the database etc. so all one has to do is visit Nextcloud to setup an admin user (after which Nextcloud considers itself "installed").

Upon snap installation, we fire up a service to run the Nextcloud cron job every 15 minutes. The problem is that there's seemingly no way to tell Nextcloud this before Nextcloud has an admin user setup (i.e. before Nextcloud is "installed"). After the admin user is created this functionality is exposed via `occ`, but that's too late to make this a preconfiguration.

Is there any way to get this exposed via config.php or autoconfig.php?

**Comment by j-ed** [comment]
@kyrofa Have you tried to run the ` ./occ background:cron` after you've created the database?

**Comment by kyrofa** [comment]
> @kyrofa Have you tried to run the ./occ background:cron after you've created the database?

I'm assuming the database creation to which you refer doesn't happen until the admin user is created (which is why Nextcloud doesn't consider itself "installed" until that has happened). After the snap is installed and before the user visits Nextcloud in the browser and creates an admin user, this is what `occ` gives me:

```bash
$ sudo nextcloud.occ list
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Nextcloud is not installed - only a limited number of commands are available
Nextcloud version 11.0.2

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --no-warnings     Skip global warnings, show command output only
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  _completion           BASH completion hook.
  check                 check dependencies of the server environment
  help                  Displays help for a command
  list                  Lists commands
  status                show some status information
 app
  app:check-code        check code to be compliant
 integrity
  integrity:check-app   Check integrity of an app using a signature.
  integrity:check-core  Check integrity of core code using a signature.
  integrity:sign-app    Signs an app using a private key.
  integrity:sign-core   Sign core using a private key.
 l10n
  l10n:createjs         Create javascript translation files for a given app
 maintenance
  maintenance:install   install Nextcloud
```

Note: no `background:cron` option. As I mentioned in the description, that only becomes available after the admin user is created. Creating that user is a completely user-driven process: the snap doesn't know when it's happened. Which is why it'd be nice to be able to PREconfigure this, using autoconfig.php or config.php.

**Comment by j-ed** [comment]
You're right, the mentioned command is only available after the `./occ maintenance:install` command has been executed. As long as you've not installed Nextcloud you cannot set that parameter using occ.

**Comment by kyrofa** [comment]
> As long as you've not installed Nextcloud you cannot set that parameter using occ.

Indeed. Thus my request to expose it via `autoconfig.php` or `config.php`.

**Comment by nickvergessen** [comment]
Just run `./occ config:app:set core backgroundjobs_mode --value="cron"` after your call to `occ install`
We will certainly not add this config in a second place.

**Comment by kyrofa** [comment]
I don't call `occ install`. I use `autoconfig.php` to set things up enough that the user just creates the admin user when first visiting the site.

**Comment by jospoortvliet** [comment]
@nickvergessen so how can one pre-configure this without first running occ install (as that is never run, users have to log in and create an account)? Is there a work-around?

**Comment by nickvergessen** [comment]
Apparently just running `php cron.php` would also set it to `'cron'`
https://github.com/nextcloud/server/blob/0024b67aaf1b5fd79a2e73789a4c903364162e54/cron.php#L106-L108

So just configure the cron job itself and the config will be adjusted on first execution
