### ISSUE TITLE
Cannot connect with OSX client after upgrade to 11.0.2

### ISSUE THREAD

**Issue by huseyin-cakmak** [nextcloud/server#3733]
### Steps to reproduce
1. 
2.
3.

### Expected behaviour
Sync between mac OS and server

### Actual behaviour
The Client (OSX version 2.2.4 (build 1)) cannot connect.
Linux client works fine. 

### Server configuration
**Operating system**:
Ubuntu 16.04 LTS

**Web server:**
Apache2

**Database:**
MySQL  5.7.13

**PHP version:**
7.0.15

**Nextcloud version:** (see Nextcloud admin page)
11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 11.0.1

**Where did you install Nextcloud from:**
Updated using the web interface

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 

No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml

</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by tflidd** [comment]
Did you update from NC 10 or an earlier version of NC 11?

**Comment by huseyin-cakmak** [comment]
It was an upgrade from 11.0.1 to 11.0.2

I also noticed that the login (authentication) is much slower after the upgrade. Our OSX users could not access the server anymore from their desktop client and I noticed the same issue with the Android App. 

I had no choice but to restore the previous version (11.0.1) from my last backup and now everything is back to normal but I could not figure out what the problem was. I wonder if anyone else experienced the issue because it was working fine on Windows and Linux clients.

**Comment by tflidd** [comment]
There was already a report on slow login times:
https://help.nextcloud.com/t/11-0-2-incredibly-slow-login/9475
@LukasReschke 

And regarding OS X, there was one issue with the bruteforce-table:
https://help.nextcloud.com/t/solved-no-more-able-to-connect-via-caldav/9459

**Comment by nickvergessen** [comment]
Are you using a proxy?

**Comment by huseyin-cakmak** [comment]
I'm using nginx as a reverse proxy.

**Comment by nightspotlight** [comment]
@huseyin-cakmak it is possible that your nginx is not forwarding remote client's IP to Nextcloud, or Nextcloud is not properly configured to trust nginx and/or its headers. I am currently battling the same issue in my setup based on Docker with nginx running as a container. Nextcloud sees all incoming requests as coming from nginx and not the real user. Ends up filling oc_bruteforce_attempts table with one IP, resulting in no clients being able to connect:
```
MariaDB [nextcloud]> select * from oc_bruteforce_attempts;
+----+--------+------------+------------+---------------+--------------------------+
| id | action | occurred   | ip         | subnet        | metadata                 |
+----+--------+------------+------------+---------------+--------------------------+
|  1 | login  | 1503170585 | 172.18.0.2 | 172.18.0.2/32 | {"uid":"nightspotlight"} |
|  2 | login  | 1503170650 | 172.18.0.2 | 172.18.0.2/32 | {"uid":"nightspotlight"} |
|  3 | login  | 1503170703 | 172.18.0.2 | 172.18.0.2/32 | []                       |
...
| 29 | login  | 1503205194 | 172.18.0.2 | 172.18.0.2/32 | {"uid":"irina"}          |
| 30 | login  | 1503205237 | 172.18.0.2 | 172.18.0.2/32 | {"uid":"irina"}          |
| 31 | login  | 1503205267 | 172.18.0.2 | 172.18.0.2/32 | {"uid":"irina"}          |
+----+--------+------------+------------+---------------+--------------------------+
31 rows in set (0.00 sec)
```

**Comment by nickvergessen** [comment]
Closing as per above
