### ISSUE TITLE
[Bug]: Broken occ. Failed to connec to database after upgrade

### ISSUE THREAD

**Issue by frisodubach** [nextcloud/server#37332]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After performing an upgrade of my nextcloud docker-image from version 24 to version 25, the occ-command is broken entirely, while reporting that it failed to connect to the database (Postgres in my case). However according to the logs, Postgres is completely fine and no database version upgrade was performed.

Running any command with `occ` (even `occ -h`) results in the follwing error message:
`
Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] timeout expired in /var/www/html/lib/private/DB/Connection.php:139
`

I upgraded by server by turning on `maintenance:mode`, then pulled the new docker image w/ docker-compose, and restarted the new container. After the upgrade, I was unable to turn off maintenance mode, or use the occ-command in general.

### Steps to reproduce

1. `sudo docker exec -u www-data -it nextcloud php occ maintenance:mode --on`
2. `sudo docker-compose pull`
3. `sudo docker-compose up -d`
4. `sudo docker exec -u www-data -it nextcloud php occ maintenance:mode --off`

### Expected behavior

Expected the upgrade to go smoothly and not break occ.

### Installation method

Official All-in-One appliance

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
occ is broken.
```

### List of activated Apps

```shell
occ is broken. Here is a list of installed apps instead:

drwxr-xr-x 11 www-data www-data 4096 Mar 20 02:57 activity
drwxr-xr-x  6 www-data www-data 4096 Sep 13  2021 admin_audit
drwxr-xr-x  9 www-data www-data 4096 Mar 20 02:57 bruteforcesettings
drwxr-xr-x 12 www-data www-data 4096 Mar 20 02:57 circles
drwxr-xr-x  6 www-data www-data 4096 Mar 20 02:57 cloud_federation_api
drwxr-xr-x  7 www-data www-data 4096 Mar 20 02:57 comments
drwxr-xr-x  6 www-data www-data 4096 Sep 13  2021 contactsinteraction
drwxr-xr-x  8 www-data www-data 4096 May  5  2022 dashboard
drwxr-xr-x  9 www-data www-data 4096 Mar 20 02:57 dav
drwxr-xr-x 10 www-data www-data 4096 Sep 13  2021 encryption
drwxr-xr-x  9 www-data www-data 4096 Oct 26 03:27 federatedfilesharing
drwxr-xr-x 10 www-data www-data 4096 Sep 13  2021 federation
drwxr-xr-x 11 www-data www-data 4096 Mar 20 02:57 files
drwxr-xr-x 11 www-data www-data 4096 Mar 20 02:57 files_external
drwxr-xr-x  8 www-data www-data 4096 Mar 20 02:57 files_pdfviewer
drwxr-xr-x  8 www-data www-data 4096 Mar 20 02:57 files_rightclick
drwxr-xr-x 10 www-data www-data 4096 Mar 20 02:57 files_sharing
drwxr-xr-x  8 www-data www-data 4096 Mar 20 02:57 files_trashbin
drwxr-xr-x  7 www-data www-data 4096 May  5  2022 files_versions
drwxr-xr-x  9 www-data www-data 4096 Mar 20 02:57 firstrunwizard
drwxr-xr-x 10 www-data www-data 4096 Mar 20 02:57 logreader
drwxr-xr-x  6 www-data www-data 4096 Sep 13  2021 lookup_server_connector
drwxr-xr-x  8 www-data www-data 4096 Mar 20 02:57 nextcloud_announcements
drwxr-xr-x  9 www-data www-data 4096 Mar 20 02:57 notifications
drwxr-xr-x  7 www-data www-data 4096 May  5  2022 oauth2
drwxr-xr-x  9 www-data www-data 4096 Mar 20 02:57 password_policy
drwxr-xr-x  9 www-data www-data 4096 Mar 20 02:57 photos
drwxr-xr-x  8 www-data www-data 4096 Mar 20 02:57 privacy
drwxr-xr-x  7 www-data www-data 4096 Sep 13  2021 provisioning_api
drwxr-xr-x  6 www-data www-data 4096 Mar 20 02:57 recommendations
drwxr-xr-x  8 www-data www-data 4096 Mar 20 02:57 related_resources
drwxr-xr-x  9 www-data www-data 4096 Mar 20 02:57 serverinfo
drwxr-xr-x 11 www-data www-data 4096 Sep 13  2021 settings
drwxr-xr-x  8 www-data www-data 4096 Oct 26 03:27 sharebymail
drwxr-xr-x 10 www-data www-data 4096 Mar 20 02:57 support
drwxr-xr-x  9 www-data www-data 4096 Mar 20 02:57 survey_client
drwxr-xr-x 11 www-data www-data 4096 Mar 20 02:57 suspicious_login
drwxr-xr-x 10 www-data www-data 4096 Mar 20 02:57 systemtags
drwxr-xr-x  9 www-data www-data 4096 Mar 20 02:57 text
drwxr-xr-x 10 www-data www-data 4096 Oct 26 03:27 theming
drwxr-xr-x  8 www-data www-data 4096 May  5  2022 twofactor_backupcodes
drwxr-xr-x 11 www-data www-data 4096 Mar 20 02:57 twofactor_totp
drwxr-xr-x  9 www-data www-data 4096 Sep 13  2021 updatenotification
drwxr-xr-x 11 www-data www-data 4096 May  5  2022 user_ldap
drwxr-xr-x  8 www-data www-data 4096 May  5  2022 user_status
drwxr-xr-x  7 www-data www-data 4096 Mar 20 02:57 viewer
drwxr-xr-x  6 www-data www-data 4096 May  5  2022 weather_status
drwxr-xr-x  8 www-data www-data 4096 May  5  2022 workflowengine
```

### Nextcloud Signing status

```shell
system stuck in maintenance mode
```

### Nextcloud Logs

```shell
Configuring Redis as session handler,
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.2. Set the 'ServerName' directive globally to suppress this message,
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.20.0.2. Set the 'ServerName' directive globally to suppress this message,
[Wed Mar 22 03:57:31.314287 2023] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.54 (Debian) PHP/8.1.17 configured -- resuming normal operations,
[Wed Mar 22 03:57:31.314322 2023] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

**Comment by frisodubach** [comment]
@szaimen I'll report it on the nextcloud forums as you like, but as it's an issue that occurred after an upgrade, how is it a setup issue?
