### ISSUE TITLE
Recommend doing a external Security Scan over "scan.nextcloud.com"

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#3735]
There are several ways we could do this:

- Notify the Admins over Notifications (as we do if updates are available)
- A warning in "Security & Setup-Warnings"
- A hint in the "Tips & Tricks" section (#3755)

What do you think about this? @LukasReschke

**Comment by KB7777** [comment]
What about internal Security Scan? :)

**Comment by MariusBluem** [comment]
> What about internal Security Scan? :)

Well, something different we could consider about too - but for now we have this nice tool over here: https://scan.nextcloud.com 🙈 I want to add that Nextcloud does some internal checks already (code integrity)

**Comment by rullzer** [comment]
Fixed with #3755

**Comment by ferdiga** [comment]
IMO the scan reports a wrong nextcloud version
Running Nextcloud 9.1.2.2
 NOT on latest patch level
 Major version still supported
Scanned at 2017-03-11 07:37:53
(this was the first version I installed after upgrading from ownlcoud)

the nextcloud admin pages shows
Version Nextcloud 11.0.2 (stable)
Your version is up to date.

**Comment by MorrisJobke** [comment]
@ferdiga Please open a new ticket
