### ISSUE TITLE
Profile picture buttons size on Personal settings page

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#3736]
Nextcloud 11.0:

<img width="187" alt="bildschirmfoto 2017-03-06 um 20 03 17" src="https://cloud.githubusercontent.com/assets/19711361/23625041/0e5658b4-02a8-11e7-9bed-bc47a6c965f3.png">

latest `master:`

<img width="193" alt="bildschirmfoto 2017-03-06 um 20 02 38" src="https://cloud.githubusercontent.com/assets/19711361/23625085/39ebe598-02a8-11e7-928c-a85d904a7971.png">

Do we need this space for a 4rd button? @nextcloud/designers @jancborchardt

**Comment by MorrisJobke** [comment]
Fix is in #3744
