### ISSUE TITLE
Buttons are sized too small

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#3737]
Nextcloud 11.0:

<img width="104" alt="bildschirmfoto 2017-03-06 um 20 16 06" src="https://cloud.githubusercontent.com/assets/19711361/23625526/c57307bc-02a9-11e7-80d6-130f585e92e3.png">

latest `master`:

<img width="61" alt="bildschirmfoto 2017-03-06 um 20 14 26" src="https://cloud.githubusercontent.com/assets/19711361/23625530/c981dd7e-02a9-11e7-80b1-9771ab4bba66.png">

...a bit like #3736 😅😜 - The buttons are hard to click ;)

@nextcloud/designers

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers this is a really bad thing - could somebody look into this?

**Comment by juliushaertl** [comment]
I'll take care of this tomorrow.

**Comment by juliushaertl** [comment]
Fixed with #4583
