### ISSUE TITLE
[Bug]: The CSS class 'externalErroredRow' has a wrong background-color in the dark theme

### ISSUE THREAD

**Issue by AmonBune** [nextcloud/server#37373]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The CSS class 'externalErroredRow' has a wrong background-color in the dark theme (#F2DEDE):

![image](https://user-images.githubusercontent.com/15927695/227273145-e4d2b100-0dc0-4fb6-9d6c-aff3e0cccf9e.png)

### Steps to reproduce

1. Enable dark theme in Accessibility options
2. Add a WebDAV storage
3. Add a random value for the password so the state is erroneous
4. Save
5. Check out the main site /apps/files

### Expected behavior

The background is also dark like the other elements. And more importantly, the text is readable.

### Installation method

Community Manual installation with Archive

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
-
```

**Comment by szaimen** [comment]
Hi, which nc version?

**Comment by AmonBune** [comment]
Nextcloud Version 25.0.4
PHP Version 8.1.13

**Comment by susnux** [comment]
Same on NC 26 and master.
