### ISSUE TITLE
Default user avatars look ugly

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#37381]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Default avatar looks ugly.

### Steps to reproduce

1. create a random user
2. look at the auto-created avatar

**Top bar:**

![image](https://user-images.githubusercontent.com/1589737/227501631-53f8a2f3-68bf-4ee1-8e7f-c360e282690c.png)

(top and left corner are cut and the letters look ugly)

**personal settings:**

![image](https://user-images.githubusercontent.com/1589737/227501930-3ed9d9cb-c3d5-42b0-9c85-6be22317dd17.png)

(top and left corner are cut, letters look OK if the avatar is bigger)

![image](https://user-images.githubusercontent.com/1589737/227502018-7d4925d2-37d4-4f3b-8c9f-8525046c4f1a.png)

(same issues like on the top bar)

### Expected behavior

have nice looking avatars

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
-
```

**Comment by SystemKeeper** [comment]
Probably the same as https://github.com/nextcloud/server/issues/34006 ?

**Comment by schiessle** [comment]
yes, seems to be the same..
