### ISSUE TITLE
[Bug]: Cannot create folder or file within files app

### ISSUE THREAD

**Issue by DrMxxxxx** [nextcloud/server#37382]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I open the files app and want to create a folder or file with the plus button on top, nothing happens.

In the console I can see, that there is something going wrong.

`App.svelte:65 Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at Object.attach (App.svelte:65:8)
    at Object.attach (plugins.js:67:16)
    at r.initialize (merged-index.js?v=736a35a2-14:11160:15)
    at t.View (backbone.js:1310:21)
    at new r (backbone.js:2070:41)
    at FileList._onClickNewButton (merged-index.js?v=736a35a2-14:7965:25)
    at bt (_executeBound.js:8:65)
    at HTMLAnchorElement.<anonymous> (bind.js:10:12)
    at HTMLAnchorElement.<anonymous> (restArguments.js:16:27)
    at HTMLAnchorElement.dispatch (jquery.js:5430:27)
`

### Steps to reproduce

1. Open files app in any folder
2. Click on the plus button to create a new folder/file

### Expected behavior

Expected would be, that the drop down menu appears and I can chose what I want to create (folder, etc.)

### Installation method

Community Docker image

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.mbit-s.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.0.11",
        "overwrite.cli.url": "https:\/\/cloud.mbit-s.com",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "default_phone_region": "DE",
        "app_install_overwrite": [
            "bruteforcesettings",
            "bookmarks",
            "tasks",
            "polls",
            "metadata",
            "passwords",
            "files_external_onedrive",
            "transfer",
            "webhooks",
            "backup",
            "talk_matterbridge",
            "breezedark",
            "mediadc",
            "workflow_ocr"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.18.0
  - backup: 1.2.0
  - bookmarks: 13.0.1
  - bruteforcesettings: 2.6.0
  - calendar: 4.3.1
  - circles: 26.0.0
  - cloud_federation_api: 1.9.0
  - collectives: 2.3.0
  - comments: 1.16.0
  - contacts: 5.2.0
  - contactsinteraction: 1.7.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - deck: 1.9.0
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_external: 1.18.0
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - firstrunwizard: 2.15.0
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - mail: 3.0.2
  - maps: 1.0.2
  - mediadc: 0.3.4
  - metadata: 0.17.0
  - nextcloud_announcements: 1.15.0
  - notes: 4.7.2
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - onlyoffice: 7.8.0
  - password_policy: 1.16.0
  - passwords: 2023.3.21
  - photos: 2.2.0
  - polls: 4.1.8
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0-alpha1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - spreed: 16.0.0
  - support: 1.9.0
  - survey_client: 1.14.0
  - systemtags: 1.16.0
  - talk_matterbridge: 1.25.2
  - tasks: 0.14.5
  - text: 3.7.2
  - theming: 2.1.1
  - transfer: 0.6.0
  - twofactor_backupcodes: 1.15.0
  - updatenotification: 1.16.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - workflowengine: 2.8.0
Disabled:
  - admin_audit: 1.16.0
  - encryption: 2.14.0
  - suspicious_login: 4.4.0
  - twofactor_totp: 8.0.0-alpha.0
  - user_ldap: 1.16.0
  - workflow_ocr: 1.25.4 (installed 1.25.2)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional info

The System is running on a Synology NAS with the latest firmware (Version: 7.1.1-42962 Update 4)

**Comment by szaimen** [comment]
Hi, can you clear the browser cache and try again?

**Comment by DrMxxxxx** [comment]
Hi @szaimen ,
thanks for the tip. But did not solve the issue. :(

**Comment by szaimen** [comment]
Ah so this is your own app?

**Comment by DrMxxxxx** [comment]
No, it is the normal files app and this plus button:
<img width="712" alt="Screenshot 2023-03-24 at 12 39 27" src="https://user-images.githubusercontent.com/41616347/227512025-a7994873-be7e-486c-9d80-0748fb679271.png">

**Comment by szaimen** [comment]
Okay but this looks suspicious:

> App.svelte:65

Can yiu disable all custom apps one-by-one and check if that makes it work again?

**Comment by DrMxxxxx** [comment]
This can be closed, because the issue is already known in the transfers app [github](https://github.com/danth/transfer/issues/79)
