### ISSUE TITLE
[Bug]: Warning for X-Robots-Tag raises for the `none` value

### ISSUE THREAD

**Issue by jooola** [nextcloud/server#37386]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading to 25.0.5, I've checked the admin dashboard, and the I had the following warning:

"The `X-Robots-Tag` header is not equal to `noindex, nofollow`."

But I configured my web server to set this header to `none` which translates to `noindex, nofollow`.

From my nginx configuration:
```nginx
  add_header X-Robots-Tag "none" always;
```

So I think the check should also include the `none` value.

### Steps to reproduce

1. Configure the web server to set the `X-Robots-Tag` header to `none`
2. See warning

### Expected behavior

No warning raised when using `none` for the  `X-Robots-Tag` header.

### Installation method

None

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Irrelevant ?
```

**Comment by ernolf** [comment]
While "none" is indeed equivalent to "noindex, nofollow" for Google, but seems to be not supported by Bing and probably other search engines. /pull/36689

**Comment by MichaIng** [comment]
Also noted in pinged issue for developers and admins: https://github.com/nextcloud/server/issues/34692#issuecomment-1480052361

I will never add another admin check change without linking/explaining the reason right within the admin panel, people just keep asking instead of reading 😄. I already have another important change in pipeline regarding the [X-XSS-Protection](https://github.com/OWASP/CheatSheetSeries/issues/376) header 🙈.
