### ISSUE TITLE
UX: Forgot password form should trim user input

### ISSUE THREAD

**Issue by jtrees** [nextcloud/server#37408]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Frequently users complain that they never received a password reset email. They are certain that the email is not in their spam folder and that the email address or user name they entered was correct.

The logs show that in such cases there is usually additional whitespace in the input, for example " alice" or "bob@example.com ".

**Describe the solution you'd like**
Leading and trailing whitespace from the input should be trimmed and ignored like so:

- " alice" -> "alice"
- "bob@example.com " -> "bob@example.com"

**Describe alternatives you've considered**
There could be a note in the copy that it's the user's responsibility to check for whitespace... But that would probably be even more effort than just trimming in the first place.

**Additional comments**
The copy after submitting the form is misleading (actually it's a lie):

> A password reset message has been sent to the email address of this account.

I understand that for security reasons, it should not be revealed whether this accounts exists or not, but the copy should reflect that limitation. Something along the lines of "If this account exists, an email will be sent [...]".

**Comment by joshtrichards** [comment]
I submitted a PR (#37495) for your trim enhancement suggestion.

I was going to do a second PR to adjust the copy, but I'm unfamiliar with the language translation stuff. It's unclear what'll happen if I just change the default (English). I suspect it'll just flow through for the translators to deal with, but I'm leaving it for the time being (at least until I can confirm).

**Comment by joshtrichards** [comment]
PR submitted to adjust copy inspired by your suggestion: https://github.com/nextcloud/server/pull/37603
