### ISSUE TITLE
Exception: Cannot access private property OC\Console\Application::$application

### ISSUE THREAD

**Issue by Ralf99** [nextcloud/server#37402]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello all,

I have the following error in my logging after updating to version 26.0.0.11:

Exception: Cannot access private property OC\Console\Application::$application in file '/nextcloud/apps/occweb/lib/Controller/OccController.php' line 81

and the app does not work anymore. 

Lines 80-87 are as follows:
  public function list() {
    $defs = $this->application->application->all();
    $cmds = array();
    foreach ($defs as $d) {
      array_push($cmds, $d->getName());
    }
    return new DataResponse($cmds);
  }

Line 81:
$defs = $this->application->application->all();

I know OCC Web is no longer supported but up to version 24 the app still worked to execute occ commands.
**My question now, what has changed in version 26 when calling application?**

### Steps to reproduce

1. update to version 26
2. open occ web
3. Black surface
4. look into the logging

### Expected behavior

the app opens normally again without a black screen

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

None

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:  - activity: 2.18.0  - admin_audit: 1.16.0  - bruteforcesettings: 2.6.0  - circles: 26.0.0  - cloud_federation_api: 1.9.0  - comments: 1.16.0  - contactsinteraction: 1.7.0  - dashboard: 7.6.0  - dav: 1.25.0  - federatedfilesharing: 1.16.0  - files: 1.21.1  - files_pdfviewer: 2.7.0  - files_rightclick: 1.5.0  - files_sharing: 1.18.0  - files_trashbin: 1.16.0  - files_versions: 1.19.1  - groupfolders: 14.0.0  - logreader: 2.11.0  - lookup_server_connector: 1.14.0  - nextcloud_announcements: 1.15.0  - notifications: 2.14.0  - oauth2: 1.14.0  - occweb: 0.1.0  - password_policy: 1.16.0  - photos: 2.2.0  - privacy: 1.10.0  - provisioning_api: 1.16.0  - recommendations: 1.5.0  - related_resources: 1.1.0-alpha1  - serverinfo: 1.16.0  - settings: 1.8.0  - sharebymail: 1.16.0  - support: 1.9.0  - survey_client: 1.14.0  - systemtags: 1.16.0  - text: 3.7.2  - theming: 2.1.1  - twofactor_backupcodes: 1.15.0  - twofactor_totp: 8.0.0-alpha.0  - updatenotification: 1.16.0  - user_status: 1.6.0  - viewer: 1.10.0  - weather_status: 1.6.0  - workflowengine: 2.8.0Disabled:  - encryption: 2.14.0  - federation: 1.16.0 (installed 1.3.0)  - files_external: 1.18.0  - firstrunwizard: 2.15.0 (installed 2.2.1)  - suspicious_login: 4.4.0  - user_ldap: 1.16.0
```

**Comment by szaimen** [comment]
Hi, please report this to https://github.com/adphi/occweb/issues. Thanks!

**Comment by Ralf99** [comment]
@szaimen Thanks I will do but I don't think the author there will answer my question, how would you have to call this command correctly from version 26? (Then I could help myself!)

**$this->application->application->all();**

Thought at least that this would be a question of the server what the NEW correct call is and not a question to occweb....

**Comment by szaimen** [comment]
Sorry, dont know much about this part of the code

**Comment by Ralf99** [comment]
🤷‍♂️ possibly another developer? 🤞
