### ISSUE TITLE
[Bug]: File sharing on External Storage isn't working anymore since NC 26 upgrade (PHP 8.2)

### ISSUE THREAD

**Issue by SofianeLasri** [nextcloud/server#37414]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since I upgraded to Nextcloud 26, the file sharing for external storage is broken. An error message that simply say "Error while creating the share" appear on the screen, and a detailed error log shows up in the console. This one told us that the POST query result in a 404 error.
Then, when we goes to the logs page in the admin dashboard, a very simple message about the error appear: `Share type does not allow to emit interaction event`.
But, if we refresh the page on the same folder, we will see that the file/folder is now shared. But we can't copy it link. And if we have it (because the link was shared before this problem occured), the link ends in a 404 error page.

This error only occurs on external storage (smb, sftp & ftp), not on /data storage.

### Steps to reproduce

1. Connect an external storage.
2. Enter to the newly added folder for this external storage.
3. Create/Select a file and try creating a link for sharing it.

### Expected behavior

A link for this file is created and accessible to the public.

### Installation method

Community Web installer on a VPS or web space

### Operating system

Debian/Ubuntu

### PHP engine version

Other

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.sl-projects.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.0.11",
        "overwrite.cli.url": "https:\/\/cloud.sl-projects.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "default_phone_region": "FR",
        "allow_local_remote_servers": true,
        "updater.release.channel": "stable",
        "overwriteprotocol": "https",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Movie",
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\MP4",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF"
        ],
        "app_install_overwrite": [
            "maps",
            "files_downloadactivity"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.18.0
  - admin_audit: 1.16.0
  - audioplayer: 3.3.1
  - bruteforcesettings: 2.6.0
  - calendar: 4.3.1
  - camerarawpreviews: 0.8.1
  - circles: 26.0.0
  - cloud_federation_api: 1.9.0
  - comments: 1.16.0
  - contacts: 5.2.0
  - contactsinteraction: 1.7.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_downloadactivity: 1.16.0
  - files_external: 1.18.0
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - firstrunwizard: 2.15.0
  - forms: 3.2.0
  - groupfolders: 14.0.0
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - mail: 3.0.2
  - nextcloud_announcements: 1.15.0
  - notes: 4.7.2
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - password_policy: 1.16.0
  - photos: 2.2.0
  - previewgenerator: 5.2.1
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - recognize: 3.7.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0-alpha1
  - richdocuments: 8.0.0
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - smb_test: 0.3.6
  - sociallogin: 5.4.2
  - support: 1.9.0
  - survey_client: 1.14.0
  - suspicious_login: 4.4.0
  - systemtags: 1.16.0
  - tasks: 0.14.5
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - twofactor_totp: 8.0.0-alpha.0
  - updatenotification: 1.16.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - workflowengine: 2.8.0
Disabled:
  - encryption: 2.14.0 (installed 2.13.0)
  - extract: 1.3.5 (installed 1.3.5)
  - files_photospheres: 1.26.0 (installed 1.26.0)
  - maps: 0.2.4 (installed 0.2.4)
  - quota_warning: 1.15.0 (installed 1.15.0)
  - richdocumentscode: 22.5.802 (installed 22.5.802)
  - spreed: 16.0.1 (installed 16.0.1)
  - user_ldap: 1.16.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"Fvqw7mi8jrZxoIQwS5X2","level":0,"time":"2023-03-26T20:46:33+00:00","remoteAddr":"172.71.131.190","user":"SofianeLasri","app":"PHP","method":"GET","url":"/index.php/settings/admin/logging","message":"Creation of dynamic property OCA\\FirstRunWizard\\Settings\\Personal::$urlGenerator is deprecated at /home/serveur-web/cloud.sl-projects.com/apps/firstrunwizard/lib/Settings/Personal.php#40","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.51","version":"26.0.0.11","data":{"app":"PHP"}}
{"reqId":"Fvqw7mi8jrZxoIQwS5X2","level":0,"time":"2023-03-26T20:46:33+00:00","remoteAddr":"172.71.131.190","user":"SofianeLasri","app":"logreader","method":"GET","url":"/index.php/settings/admin/logging","message":"Could not find resource file \"/apps/logreader/css/../js/logreader-main.css\"","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.51","version":"26.0.0.11","data":{"app":"logreader"}}
{"reqId":"3iNRKWuKizgEKt6mJabh","level":0,"time":"2023-03-26T20:46:58+00:00","remoteAddr":"172.71.134.73","user":"SofianeLasri","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/SofianeLasri/334594318/0000000000000022","message":"pathinfo(): Passing null to parameter #1 ($path) of type string is deprecated at /home/serveur-web/cloud.sl-projects.com/lib/private/Files/Cache/Scanner.php#496","userAgent":"Mozilla/5.0 (Windows) mirall/3.7.4stable-Win64 (build 20230309) (Nextcloud, windows-10.0.19045 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.0.11","data":{"app":"PHP"}}
{"reqId":"3iNRKWuKizgEKt6mJabh","level":0,"time":"2023-03-26T20:46:58+00:00","remoteAddr":"172.71.134.73","user":"SofianeLasri","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/SofianeLasri/334594318/0000000000000022","message":"strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated at /home/serveur-web/cloud.sl-projects.com/lib/private/Files/Cache/Scanner.php#499","userAgent":"Mozilla/5.0 (Windows) mirall/3.7.4stable-Win64 (build 20230309) (Nextcloud, windows-10.0.19045 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.0.11","data":{"app":"PHP"}}
{"reqId":"3iNRKWuKizgEKt6mJabh","level":0,"time":"2023-03-26T20:46:58+00:00","remoteAddr":"172.71.134.73","user":"SofianeLasri","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/SofianeLasri/334594318/0000000000000022","message":"pathinfo(): Passing null to parameter #1 ($path) of type string is deprecated at /home/serveur-web/cloud.sl-projects.com/lib/private/Files/Cache/Scanner.php#496","userAgent":"Mozilla/5.0 (Windows) mirall/3.7.4stable-Win64 (build 20230309) (Nextcloud, windows-10.0.19045 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.0.11","data":{"app":"PHP"}}
{"reqId":"3iNRKWuKizgEKt6mJabh","level":0,"time":"2023-03-26T20:46:58+00:00","remoteAddr":"172.71.134.73","user":"SofianeLasri","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/SofianeLasri/334594318/0000000000000022","message":"strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated at /home/serveur-web/cloud.sl-projects.com/lib/private/Files/Cache/Scanner.php#499","userAgent":"Mozilla/5.0 (Windows) mirall/3.7.4stable-Win64 (build 20230309) (Nextcloud, windows-10.0.19045 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.0.11","data":{"app":"PHP"}}
{"reqId":"3iNRKWuKizgEKt6mJabh","level":0,"time":"2023-03-26T20:46:58+00:00","remoteAddr":"172.71.134.73","user":"SofianeLasri","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/SofianeLasri/334594318/0000000000000022","message":"pathinfo(): Passing null to parameter #1 ($path) of type string is deprecated at /home/serveur-web/cloud.sl-projects.com/lib/private/Files/Cache/Scanner.php#496","userAgent":"Mozilla/5.0 (Windows) mirall/3.7.4stable-Win64 (build 20230309) (Nextcloud, windows-10.0.19045 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.0.11","data":{"app":"PHP"}}
{"reqId":"3iNRKWuKizgEKt6mJabh","level":0,"time":"2023-03-26T20:46:58+00:00","remoteAddr":"172.71.134.73","user":"SofianeLasri","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/SofianeLasri/334594318/0000000000000022","message":"strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated at /home/serveur-web/cloud.sl-projects.com/lib/private/Files/Cache/Scanner.php#499","userAgent":"Mozilla/5.0 (Windows) mirall/3.7.4stable-Win64 (build 20230309) (Nextcloud, windows-10.0.19045 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.0.11","data":{"app":"PHP"}}
{"reqId":"3iNRKWuKizgEKt6mJabh","level":0,"time":"2023-03-26T20:46:58+00:00","remoteAddr":"172.71.134.73","user":"SofianeLasri","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/SofianeLasri/334594318/0000000000000022","message":"pathinfo(): Passing null to parameter #1 ($path) of type string is deprecated at /home/serveur-web/cloud.sl-projects.com/lib/private/Files/Cache/Scanner.php#496","userAgent":"Mozilla/5.0 (Windows) mirall/3.7.4stable-Win64 (build 20230309) (Nextcloud, windows-10.0.19045 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.0.11","data":{"app":"PHP"}}
{"reqId":"3iNRKWuKizgEKt6mJabh","level":0,"time":"2023-03-26T20:46:58+00:00","remoteAddr":"172.71.134.73","user":"SofianeLasri","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/SofianeLasri/334594318/0000000000000022","message":"strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated at /home/serveur-web/cloud.sl-projects.com/lib/private/Files/Cache/Scanner.php#499","userAgent":"Mozilla/5.0 (Windows) mirall/3.7.4stable-Win64 (build 20230309) (Nextcloud, windows-10.0.19045 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.0.11","data":{"app":"PHP"}}
{"reqId":"HI8zj62lnUZ4OBQhye0k","level":0,"time":"2023-03-26T20:47:14+00:00","remoteAddr":"172.71.134.154","user":"SofianeLasri","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/SofianeLasri/334594318/0000000000000023","message":"pathinfo(): Passing null to parameter #1 ($path) of type string is deprecated at /home/serveur-web/cloud.sl-projects.com/lib/private/Files/Cache/Scanner.php#496","userAgent":"Mozilla/5.0 (Windows) mirall/3.7.4stable-Win64 (build 20230309) (Nextcloud, windows-10.0.19045 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.0.11","data":{"app":"PHP"}}
{"reqId":"HI8zj62lnUZ4OBQhye0k","level":0,"time":"2023-03-26T20:47:14+00:00","remoteAddr":"172.71.134.154","user":"SofianeLasri","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/SofianeLasri/334594318/0000000000000023","message":"strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated at /home/serveur-web/cloud.sl-projects.com/lib/private/Files/Cache/Scanner.php#499","userAgent":"Mozilla/5.0 (Windows) mirall/3.7.4stable-Win64 (build 20230309) (Nextcloud, windows-10.0.19045 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.0.11","data":{"app":"PHP"}}
{"reqId":"HI8zj62lnUZ4OBQhye0k","level":0,"time":"2023-03-26T20:47:14+00:00","remoteAddr":"172.71.134.154","user":"SofianeLasri","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/SofianeLasri/334594318/0000000000000023","message":"pathinfo(): Passing null to parameter #1 ($path) of type string is deprecated at /home/serveur-web/cloud.sl-projects.com/lib/private/Files/Cache/Scanner.php#496","userAgent":"Mozilla/5.0 (Windows) mirall/3.7.4stable-Win64 (build 20230309) (Nextcloud, windows-10.0.19045 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.0.11","data":{"app":"PHP"}}
{"reqId":"HI8zj62lnUZ4OBQhye0k","level":0,"time":"2023-03-26T20:47:14+00:00","remoteAddr":"172.71.134.154","user":"SofianeLasri","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/SofianeLasri/334594318/0000000000000023","message":"strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated at /home/serveur-web/cloud.sl-projects.com/lib/private/Files/Cache/Scanner.php#499","userAgent":"Mozilla/5.0 (Windows) mirall/3.7.4stable-Win64 (build 20230309) (Nextcloud, windows-10.0.19045 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.0.11","data":{"app":"PHP"}}
{"reqId":"HI8zj62lnUZ4OBQhye0k","level":0,"time":"2023-03-26T20:47:14+00:00","remoteAddr":"172.71.134.154","user":"SofianeLasri","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/SofianeLasri/334594318/0000000000000023","message":"pathinfo(): Passing null to parameter #1 ($path) of type string is deprecated at /home/serveur-web/cloud.sl-projects.com/lib/private/Files/Cache/Scanner.php#496","userAgent":"Mozilla/5.0 (Windows) mirall/3.7.4stable-Win64 (build 20230309) (Nextcloud, windows-10.0.19045 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.0.11","data":{"app":"PHP"}}
{"reqId":"HI8zj62lnUZ4OBQhye0k","level":0,"time":"2023-03-26T20:47:14+00:00","remoteAddr":"172.71.134.154","user":"SofianeLasri","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/SofianeLasri/334594318/0000000000000023","message":"strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated at /home/serveur-web/cloud.sl-projects.com/lib/private/Files/Cache/Scanner.php#499","userAgent":"Mozilla/5.0 (Windows) mirall/3.7.4stable-Win64 (build 20230309) (Nextcloud, windows-10.0.19045 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.0.11","data":{"app":"PHP"}}
{"reqId":"HI8zj62lnUZ4OBQhye0k","level":0,"time":"2023-03-26T20:47:14+00:00","remoteAddr":"172.71.134.154","user":"SofianeLasri","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/SofianeLasri/334594318/0000000000000023","message":"pathinfo(): Passing null to parameter #1 ($path) of type string is deprecated at /home/serveur-web/cloud.sl-projects.com/lib/private/Files/Cache/Scanner.php#496","userAgent":"Mozilla/5.0 (Windows) mirall/3.7.4stable-Win64 (build 20230309) (Nextcloud, windows-10.0.19045 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.0.11","data":{"app":"PHP"}}
{"reqId":"HI8zj62lnUZ4OBQhye0k","level":0,"time":"2023-03-26T20:47:14+00:00","remoteAddr":"172.71.134.154","user":"SofianeLasri","app":"PHP","method":"PUT","url":"/remote.php/dav/uploads/SofianeLasri/334594318/0000000000000023","message":"strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated at /home/serveur-web/cloud.sl-projects.com/lib/private/Files/Cache/Scanner.php#499","userAgent":"Mozilla/5.0 (Windows) mirall/3.7.4stable-Win64 (build 20230309) (Nextcloud, windows-10.0.19045 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"26.0.0.11","data":{"app":"PHP"}}
{"reqId":"55PLpBZZTuGL62cF6fAz","level":1,"time":"2023-03-26T20:47:50+00:00","remoteAddr":"172.71.131.190","user":"SofianeLasri","app":"no app in context","method":"POST","url":"/ocs/v2.php/apps/files_sharing/api/v1/shares","message":"Deprecated event type for OCP\\Share::preShare: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.51","version":"26.0.0.11","data":[]}
{"reqId":"55PLpBZZTuGL62cF6fAz","level":1,"time":"2023-03-26T20:47:50+00:00","remoteAddr":"172.71.131.190","user":"SofianeLasri","app":"no app in context","method":"POST","url":"/ocs/v2.php/apps/files_sharing/api/v1/shares","message":"Deprecated event type for OCP\\Share::postShare: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.51","version":"26.0.0.11","data":[]}
{"reqId":"55PLpBZZTuGL62cF6fAz","level":0,"time":"2023-03-26T20:47:50+00:00","remoteAddr":"172.71.131.190","user":"SofianeLasri","app":"no app in context","method":"POST","url":"/ocs/v2.php/apps/files_sharing/api/v1/shares","message":"hiding hidden file .nomedia","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.51","version":"26.0.0.11","data":[]}
{"reqId":"55PLpBZZTuGL62cF6fAz","level":0,"time":"2023-03-26T20:47:50+00:00","remoteAddr":"172.71.131.190","user":"SofianeLasri","app":"related_resources","method":"POST","url":"/ocs/v2.php/apps/files_sharing/api/v1/shares","message":"flush cache","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.51","version":"26.0.0.11","data":{"app":"related_resources"}}
{"reqId":"55PLpBZZTuGL62cF6fAz","level":0,"time":"2023-03-26T20:47:50+00:00","remoteAddr":"172.71.131.190","user":"SofianeLasri","app":"files_sharing","method":"POST","url":"/ocs/v2.php/apps/files_sharing/api/v1/shares","message":"Share type does not allow to emit interaction event","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.51","version":"26.0.0.11","data":{"app":"files_sharing"}}
```

### Additional info

This a not a permission issue, the sharing right is checked in the admin dashboard. If we uncheck it, an error message that tolds us we don't have the permission shows up.
I am now on PHP 8.2 and `php8.2-smbclient` is installed.

**Comment by SubZero84** [comment]
I have exactly the same problem.
-NC 26.0.0 Hub4
-PHP 8.2
-nginx

I've tried everything, it feels like.
-read + write to the share via NC
-share permissions and ACL set to "everyone" for test purposes
-can create and edit folders from NC on the share, etc.
-can create new text files (.md) from NC on the share, but I get an error when opening (file not found or something like that)
The file is created, though.

**Comment by SubZero84** [comment]
Oh, update.

I have found a workaround for myself.

If you create the share not in the "User" area but "Admin" area (and make it available to the users), everything works.
More specifically:
Administration settings -> Administration -> External Storage
(don't forget to enable "allow share")

**Comment by TheIceMagmaCube** [comment]
I may have something related too.
I can't share or access properties of my samba shares. When I try to do it, I have this error message:

![image](https://user-images.githubusercontent.com/38074756/228078074-5e8138be-5081-4220-a666-4f78ac21c828.png)

I'm on docker server. Image with supervisor with cron.
Intrestingly, I don't have this issue on another instance I upgraded too.

**Comment by xn--nding-jua** [comment]
Umm, I have to extend the problem: regular file-shares are not working, too: on another machine with Nextcloud 26 regular public-shares are not available any more. The password is requested but after the password is typed in the message "Page not found: The page could not be found on the server.". Here I'm not using SMB/CIFS but regular file-system.

So there seems to be a bigger problem with the shares.

**Comment by xn--nding-jua** [comment]
Another update and how I fixed the problem: Somehow the IDs of some folders changed. The folder where I had problems on sharing had a non-working "internal file-link" that directed to a totally different folder that was an external FTP-share. I removed the external sharepoint and suddenly Nextcloud lost the information about my problematic folder, too, and reindexed everything resulting in a new ID for this folder and losing ALL shares... All connected clients deleted the removed folder, too.

Now I had to update all shares using phpMyAdmin and direct the shares to the updated itemIDs in the columns "item_source" and "file_source" manually. Now all shares are working with the original token and password...

Maybe there is a bug in the Nextcloud 26 installer that mixes some IDs? Sounds like a serious problem in larger installations... Keep an eye on this, please!

**Comment by xn--nding-jua** [comment]
I'm still searching the code for an issue and maybe the culprit lies here:
https://github.com/nextcloud/server/commits/master/lib/private/Files/Config/UserMountCache.php

This file has been updated and is directly related to the UserMount-Points... tomorrow I will try to find a solution...

**Comment by DerGenaue** [comment]
I can reproduce the issue where the "internal link" somehow points to that external drive:

Fetching the internal share link for `/folder`
gives me some internal share link: `https://some.next.cloud/f/1337`
That one resolves to: `https://some.next.cloud/apps/files/?dir=/external_drive/files/folder` (html encoded parameter obv,)

which is completely the wrong location and obviously doesn't exist...

**Comment by xn--nding-jua** [comment]
Maybe problem is related to issue https://github.com/nextcloud/server/pull/21049
But obviously something has changed between NC25 and NC26

**Comment by DerGenaue** [comment]
I did a bit of sniffing around my database and the entries in the tables appear to be perfectly fine at first glance.
Currently following the `/f/{fileid}` requrest to the code hoping to figure out how the heck that gets re-routed to the external mount

**Comment by DerGenaue** [comment]
ok, I now see why you think the issue might lie in https://github.com/nextcloud/server/commits/master/lib/private/Files/Config/UserMountCache.php

I was able to trace the issue to this function: https://github.com/nextcloud/server/blob/fc371facd202d7ede86f1adb37fc78a8c478deff/lib/private/Files/Config/UserMountCache.php#L340-L358

In here, in my case, the query returns two elements: the home mount (correct) and the external mount (not correct).
I think this is the case because the folder I'm inspecting right now is both:
* shared to internal users (this creates a mounting point for the other user)
* shared to external users via a link

still investigating...

**Comment by DerGenaue** [comment]
I think I see it now...

In the DB table `mounts`, all my exernal mounts have the same value in the columns `mount_id` and `storage_id`

this by coincidence overlaps with the `storage_id` of my main storage which leads Nextcloud to think it can find the files over there

**Comment by DerGenaue** [comment]
Interesting... If I manually adjust the `storage_id` to the correct value, the shares and links work one time and then the value in the DB is changed back to the wrong one and the links are broken again...

**Comment by DerGenaue** [comment]
Ok, I was able to verify in a DB backup that the `storage_id` field used to contain the `numeric_id` from the `storages` table that related to this `mount`, while now it is just mirrors the `mount_id` for some reason.
I'll create a new issue for this to express the significance of the problem that causes this and probably also a bunch of other issues.

**Comment by mediacrave** [comment]
Nextcloud updated to v26 this morning and my external mounts broke. Just found this.

Do we have any progress or fixes for this?

**Comment by xn--nding-jua** [comment]
The only way to get the external-mounts back to work is to use the "Administrator"-panel instead of the "User"-panel in the Nextcloud-settings. User-space mounts are not working at least for SMB/CIFS- and FTP-mounts. We are waiting for a reacting in this issue here: https://github.com/nextcloud/server/issues/37473

After migrating to the Administrator-space-mounts you will lose all shares. You have to recreate them and - if nescessary - rename the tokens with the ShareRenamer-App from https://apps.nextcloud.com/apps/sharerenamer

**Comment by waja** [comment]
Looks like 26.0.1 did fix it

**Comment by bobvandevijver** [comment]
@waja Did it also fix the wrong ids in the database?

**Comment by waja** [comment]
I did not investigate this, but as 26.0.1 was deployed in the affected setup and users reported that the issue went away, I thought it would be good to report it here too.

**Comment by SofianeLasri** [comment]
> Looks like 26.0.1 did fix it

No it didn't, the problem still occure today even after the update. :/

**Comment by waja** [comment]
So we are just lucky? Hmm ... the external (smb) storages are mounted and I can download files there ...

**Comment by SofianeLasri** [comment]
We can download files but not share them.

https://user-images.githubusercontent.com/43948827/233390797-d0fe1d16-c4c3-4e4d-8502-850006b8b76b.mp4

**Comment by waja** [comment]
But is this related to the reported issue?

**Comment by bobvandevijver** [comment]
Yes, this issue is explicitly regarding creating share links. Downloads were never impacted.

**Comment by serpentes80** [comment]
> Oh, update.
> 
> I have found a workaround for myself.
> 
> If you create the share not in the "User" area but "Admin" area (and make it available to the users), everything works. More specifically: Administration settings -> Administration -> External Storage (don't forget to enable "allow share")

thanks man, you've rescued me today.

I have exactly the same issue on my instance running 26.0.1 on PHP8.1

**Comment by alankeny** [comment]
> Oh, update.
> 
> I have found a workaround for myself.
> 
> If you create the share not in the "User" area but "Admin" area (and make it available to the users), everything works. More specifically: Administration settings -> Administration -> External Storage (don't forget to enable "allow share")

I got hit with the same issue after upgrading my instance to 26.0.1 as well, although I found it in slightly different way.  In my case I could edit Draw.io and OnlyOffice docs on internal storage, but not on SMB mounted external storage.  Moving the SMB shares from Personal settings to Administrative settings allows editing from these two add-ons to work again.

Thanks much!

**Comment by XueSheng-GIT** [comment]
> Moving the SMB shares from Personal settings to Administrative settings allows editing from these two add-ons to work again.

Be careful with this. "Moving" an external storage might add further harm, like broken Shares for other users of your instance. See https://github.com/nextcloud/server/issues/37473#issuecomment-1518529756.

**Comment by efelon** [comment]
I just found another symptom (maybe), which involves the audio player addon. The audio files for it come from an external storage and cannot be played back anymore. Furthermore they dissapear from the player all together. They appear after a rescan but are still not functional afterward. Is it possible that it is related to this?

**Comment by Lipown** [comment]
I have the same issue unfortunately.

**Comment by majneb** [comment]
Same error "Error while creating the share" here when clicking on "share link", either with external S3 storage or with local files or folders.
With local files, after reloading the page and going to the share panel I can see the share link. The link is working but when trying to download the file from this link, I get an error : "page not found on the server".
With files from the S3 storage, reloading the page and going to the share panel, there is no link shown.

Should I create another issue as it also affects local files and folders ?

(fresh nextcloud 26.0.1 / php8.1 / MariaDB manual install)
