### ISSUE TITLE
[Bug]: Error handling when unable to connect to database

### ISSUE THREAD

**Issue by MasterCrake** [nextcloud/server#37424]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

We had a network failure and our nextcloud instance lost connection to the mysql database server we are running. The error handling in this situation was inadequate to troubleshoot the issue. No logs were written to nextcloud.logs (loglevel debug) and no hint about the issue was given to the user. I would like this error to produce some kind of log to nextcloud.logs to enable efficient troubleshooting. My way of solving it was to simply remove the catches in index.php to expose the raw exception to the end user, no other method I tried managed to produce any indication at all about what was wrong.

### Steps to reproduce

1. Setup docker container running mysql:8.0.32.
2. Setup docker container running nextcloud:25.0.3-apache.
3. Disable network connection between containers.
4. Access nextcloud start page.

### Expected behavior

Exceptions thrown in index.php error handling should write to nextcloud.log.

### Installation method

Community Docker image

### Nextcloud Server version

25

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Unable to run command in docker container.
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional info

nextcloud.log only contains logs from before the network failure.

**Comment by Fenn-CS** [comment]
I would like to look into this! 

Steps :

1. Reproduce
2. Correctly log error (if reproduced)

**Comment by MasterCrake** [comment]
Great, initially we had both the nextcloud and the mysql instances working, then there was a network failure between them. There was some exception thrown that landed in the try/catch block in index.php. My usual solution would be to write something helpful to the log in the catch block. I have however not worked very much with php so I did not dare trying to fix it myself.

My guess is that the easiest way of reproducing it is by starting the two instances in docker and after installation shut down the mysql instance.
