### ISSUE TITLE
filepicker dialog problems

### ISSUE THREAD

**Issue by ajleeau** [nextcloud/server#3742]
### Steps to reproduce
1.   Install or upgrade to NC 11.0.2
2.   Login and select Move from the file action menu
3.   Select choosing a profile picture

### Expected behaviour
A well-formatted display/list of the folders available for selection.

### Actual behaviour
The display dialog is flawed.
![screenshot from 2017-03-07 12-00-26](https://cloud.githubusercontent.com/assets/6209619/23638695/e1e5c6f2-032e-11e7-9666-3a3869873a66.png)

### Server configuration
**Operating system**: CentOS 7

**Web server:** Apache 2.4.6

**Database:** MariaDB 5.5.52

**PHP version:** 7.0.16

**Nextcloud version:** (see Nextcloud admin page) 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 11.0.1

**Where did you install Nextcloud from:** downloaded from nextcloud.com

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - encryption: 1.4.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - user_ldap: 1.1.2
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - external
  - files_automatedtagging
  - files_retention
  - files_videoplayer
  - templateeditor
  - user_saml
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
{
    "system": {
        "debug": true,
        "instanceid": "ocz0nifadu1r",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "dev-nextcloud.qriscloud.org.au"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/dev-nextcloud.qriscloud.org.au",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "theme": "qriscloudtheme",
        "loglevel": 1,
        "log_rotate_size": 10485576,
        "apps_paths": [
            {
                "path": "\/var\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            },
            {
                "path": "\/var\/www\/nextcloud\/appslocal",
                "url": "\/appslocal",
                "writable": true
            }
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
</details>

**Are you using external storage, if yes which one:** sftp

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
+-------------------------------+--------------------------------------------------+
| Configuration                 | s01                                              |
+-------------------------------+--------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                |
| hasPagedResultSupport         |                                                  |
| homeFolderNamingRule          |                                                  |
| lastJpegPhotoLookup           | 0                                                |
| ldapAgentName                 | ***REMOVED SENSITIVE DATA***                |
| ldapAgentPassword             | ***                                              |
| ldapAttributesForGroupSearch  | cn                                               |
| ldapAttributesForUserSearch   | cn                                               |
| ldapBackupHost                |                                                  |
| ldapBackupPort                |                                                  |
| ldapBase                      |                       |
| ldapBaseGroups                | ***REMOVED SENSITIVE DATA*** |
| ldapBaseUsers                 | ***REMOVED SENSITIVE DATA*** |
| ldapCacheTTL                  | 600                                              |
| ldapConfigurationActive       | 1                                                |
| ldapDynamicGroupMemberURL     |                                                  |
| ldapEmailAttribute            |                                                  |
| ldapExperiencedAdmin          | 1                                                |
| ldapExpertUUIDGroupAttr       | cn                                               |
| ldapExpertUUIDUserAttr        | cn                                               |
| ldapExpertUsernameAttr        | cn                                               |
| ldapGroupDisplayName          | cn                                               |
| ldapGroupFilter               | (&(|(objectclass=posixGroup)(objectclass=top)))  |
| ldapGroupFilterGroups         |                                                  |
| ldapGroupFilterMode           | 0                                                |
| ldapGroupFilterObjectclass    |                                                  |
| ldapGroupMemberAssocAttr      | memberUid                                        |
| ldapHost                      | ***REMOVED SENSITIVE DATA***                    |
| ldapIgnoreNamingRules         |                                                  |
| ldapLoginFilter               | (&(objectClass=inetOrgPerson)(uid=%uid))         |
| ldapLoginFilterAttributes     |                                                  |
| ldapLoginFilterEmail          | 0                                                |
| ldapLoginFilterMode           | 0                                                |
| ldapLoginFilterUsername       | 1                                                |
| ldapNestedGroups              | 0                                                |
| ldapOverrideMainServer        |                                                  |
| ldapPagingSize                | 500                                              |
| ldapPort                      | 636                                              |
| ldapQuotaAttribute            |                                                  |
| ldapQuotaDefault              |                                                  |
| ldapTLS                       | 0                                                |
| ldapUserDisplayName           | cn                                               |
| ldapUserDisplayName2          |                                                  |
| ldapUserFilter                | (&(objectClass=inetOrgPerson))                   |
| ldapUserFilterGroups          |                                                  |
| ldapUserFilterMode            | 0                                                |
| ldapUserFilterObjectclass     |                                                  |
| ldapUuidGroupAttribute        | auto                                             |
| ldapUuidUserAttribute         | auto                                             |
| turnOffCertCheck              | 0                                                |
| turnOnPasswordChange          | 0                                                |
| useMemberOfToDetectMembership | 1                                                |
+-------------------------------+-------
</details>

### Client configuration
**Browser:** Firefox 51.0.1

**Operating system:** Fedora 24

**Comment by nickvergessen** [comment]
Works fine here, can you make sure to hard refresh the cache of the page (Ctrl + F5), just in case?

**Comment by MorrisJobke** [comment]
Close due to no feedback.
