### ISSUE TITLE
[Bug]: Error 503 via DAVx5 in CalDAV/CardDAV, but not every calendar

### ISSUE THREAD

**Issue by Kalytis** [nextcloud/server#37450]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Connecting my phone (DAVx5, LineageOS 21.0) to my Nextcloud instance leads to Contacts list + Contacts birthdays not being synchronized, and facing a 503 error.

On desktop clients, everything works fine.

Reported on the DAVx5 Github : https://github.com/bitfireAT/davx5-ose/discussions/279

Discussed on the Nextcloud forum : https://help.nextcloud.com/t/caldav-carddav-error-503/155329

### Steps to reproduce

1. Log in to my Nextcloud instance through DAVx5
2. Sync the calendars + contacts

### Expected behavior

Everything should sync well.

### Installation method

Official All-in-One appliance

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.kalytis.gg"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.0.9",
        "overwrite.cli.url": "https:\/\/cloud.kalytis.gg",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "maintenance": false,
        "updater.release.channel": "beta",
        "theme": "",
        "loglevel": 2,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - admin_audit: 1.16.0
  - bruteforcesettings: 2.6.0
  - calendar: 4.3.0-rc.2
  - cloud_federation_api: 1.9.0
  - contacts: 5.2.0-RC.1
  - contactsinteraction: 1.7.0
  - dav: 1.25.0
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - nextcloud_announcements: 1.15.0
  - notes: 4.6.0
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - password_policy: 1.16.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0-alpha1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - support: 1.9.0
  - survey_client: 1.14.0
  - tasks: 0.14.5
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - viewer: 1.10.0
  - workflowengine: 2.8.0
Disabled:
  - activity: 2.18.0 (installed 2.16.0)
  - circles: 26.0.0 (installed 24.0.0)
  - comments: 1.16.0 (installed 1.14.0)
  - cookbook: 0.10.1 (installed 0.10.1)
  - dashboard: 7.6.0 (installed 7.4.0)
  - deck: 1.9.0-beta.2 (installed 1.9.0-beta.2)
  - electronicsignatures: 2.0.3 (installed 2.0.3)
  - encryption: 2.14.0
  - files_external: 1.18.0
  - firstrunwizard: 2.15.0 (installed 2.13.0)
  - photos: 2.2.0 (installed 1.6.0)
  - suspicious_login: 4.4.0
  - systemtags: 1.16.0 (installed 1.14.0)
  - twofactor_totp: 8.0.0-alpha.0
  - updatenotification: 1.16.0 (installed 1.14.0)
  - user_ldap: 1.16.0
  - user_status: 1.6.0 (installed 1.4.0)
  - weather_status: 1.6.0 (installed 1.4.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by solracsf** [comment]
See https://github.com/nextcloud/server/issues/37277
Should be fixed on next release.
