### ISSUE TITLE
Security scan (scan.nextcloud.com) ignores owncloud setup

### ISSUE THREAD

**Issue by tflidd** [nextcloud/server#3746]
I have a nextcloud and an owncloud instance running. When I want to check:
https://example.com/owncloud

The scanner scans https://example.com/nextcloud by default. Even if I disable nextcloud completely (remove the setup), I'm not able to run a test, it just shows the cached result of https://example.com/nextcloud.

**Comment by MariusBluem** [comment]
This is the issue tracker of the Nextcloud Server and not of "scan.nextcloud.com" 🙈😜

The scanner has no bugtracker so I think the forum, ping @LukasReschke on IRC (or maybe! - even if it is not intended for such support - sending a mail to cloud-security-scan(at)nextcloud(dot)com) would help ✌️
