### ISSUE TITLE
chore(strings): ldap_user 'loginname' disambiguation

### ISSUE THREAD

**Issue by silopolis** [nextcloud/server#37464]
Hi,

We, translators, are wondering if that 'loginname' is the name of an LDAP field and, as such, should remain untranslated, or if it really should be 'login name' and thus be translated?

https://github.com/nextcloud/server/blob/31f4f4117e37849dabbf6b3c83790af878c01119/apps/user_ldap/templates/part.wizard-loginfilter.php#L67-L69

Thanks in advance for your clarifications
TY
J

**Comment by blizzz** [comment]
TL;DR: it should be translated

Long story: what ever constitutes the login name can be configured by the admin and vary across installation. It can also be a mixture of fields that are being taken into consideration, e.g. email and an user name on LDAP (would then be similar to local users), or also employee numbers, license plates, phone number or whatever else is stored in the directory, as long as the admin configures the relevant fields/attributes to be included.
