### ISSUE TITLE
No Versioning in NC 11 and Collabora - Worked in Version 10

### ISSUE THREAD

**Issue by devz3r0** [nextcloud/server#3749]
created from Thread: https://help.nextcloud.com/t/collabora-revision-history-and-versioning/6527/11

### Steps to reproduce
1. install NC11
2. Install collabora and set it up correctly
3. Create a Dokument, open it, close it, reopen it, edit it, save it close it, repeat i some times.

### Expected behaviour
you should get a version history either in the Filemanager OR Collabora:
![auswahl_003](https://cloud.githubusercontent.com/assets/13016719/23651542/171c048e-0326-11e7-964f-c320a9acf582.png)

### Actual behaviour
No versioning since 11:
![auswahl_004](https://cloud.githubusercontent.com/assets/13016719/23651553/218cd3a8-0326-11e7-9773-52b7cdff9834.png)

It worked till upgrade to 11:

![auswahl_005](https://cloud.githubusercontent.com/assets/13016719/23651619/4ea8a9fc-0326-11e7-9585-f25040685fa6.png)
After that it just stopped.
### Server configuration
Ubuntu 16.04

**Web server:** Apache 2.4

**Database:** Mysql 5.6

**PHP version:**  7

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Both. 

**Where did you install Nextcloud from:** the nextcloudpage

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Enabled:                                                                                                  - activity: 2.4.1                                                                                       - calendar: 1.5.1                                                                                       - comments: 1.1.0                                                                                       - contacts: 1.5.3                                                                                       - dav: 1.1.1                                                                                            - direct_menu: 0.10.0                                                                                   - federatedfilesharing: 1.1.1                                                                           - federation: 1.1.1                                                                                     - files: 1.6.1                                                                                          - files_external: 1.1.2                                                                                 - files_pdfviewer: 1.0.1                                                                                - files_sharing: 1.1.1                                                                                  - files_texteditor: 2.2                                                                                 - files_trashbin: 1.1.0                                                                                 - files_versions: 1.4.0                                                                                 - files_videoplayer: 1.0.0                                                                              - gallery: 16.0.0                                                                                       - logreader: 2.0.0                                                                                      - lookup_server_connector: 1.0.0                                                                        - nextant: 1.0.6                                                                                        - nextcloud_announcements: 1.0                                                                          - notifications: 1.0.1                                                                                  - ocr: 2.3.0
  - ocsms: 1.11.5
  - password_policy: 1.1.0                                                                                - provisioning_api: 1.1.0                                                                               - richdocuments: 1.1.25                                                                                 - serverinfo: 1.1.1                                                                                     - sharebymail: 1.0.1                                                                                    - sharerenamer: 1.1                                                                                     - spreedme: 0.3.7                                                                                       - survey_client: 0.1.5                                                                                  - systemtags: 1.1.3                                                                                     - templateeditor: 0.2                                                                                   - theming: 1.1.1                                                                                        - twofactor_backupcodes: 1.0.0                                                                          - twofactor_totp: 1.1.0                                                                                 - updatenotification: 1.1.1                                                                             - workflowengine: 1.1.1                                                                               Disabled:                                                                                                 - admin_audit                                                                                           - encryption                                                                                            - external                                                                                              - files_accesscontrol                                                                                   - files_automatedtagging                                                                                - files_reader                                                                                          - files_retention                                                                                       - firstrunwizard                                                                                        - mail                                                                                                  - user_external
  - user_ldap
  - user_saml



```
</details>

**The content of config/config.php:**
<details>
<summary>
<?php
$CONFIG = array (
  'installed' => true,
  'dbtype' => 'mysql',
 'dbtableprefix' => 'oc_',
  'forcessl' => false,
  'blacklisted_files' => 
  array (
    0 => '.htaccess',
  ),
  'enable_previews' => true,
  'preview_max_scale_factor' => 10,
  'defaultapp' => 'files',
  'knowledgebaseenabled' => true,
  'appstoreenabled' => true,
  'mail_smtpdebug' => false,
  'mail_smtpmode' => 'sendmail',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpport' => 25,
  'mail_smtptimeout' => 10,
  'mail_smtpauth' => false,
  'mail_smtpauthtype' => 'LOGIN',
  'trashbin_retention_obligation' => '7, auto',
  'allow_user_to_change_display_name' => true,
  'updatechecker' => true,
  'log_type' => 'owncloud',
  'loglevel' => '3',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0.0,
  ),
  'remember_login_cookie_lifetime' => 1296000,
  'maintenance' => false,
  'instanceid' => 'HIDDEN',
  'datadirectory' => '/var/www/owncloud/data',
  'version' => '11.0.2.7',
  'trusted_domains' => 
  array (
    0 => '192.168.122.42',
    1 => 'owncloud.domain.net',
    2 => 'cloud.domain.net',
  ),
  'secret' => 'HIDDEN',
  'appstore.experimental.enabled' => true,
  'theme' => '',
  'updater.server.url' => 'https://updates.nextcloud.com/updater_server/',
  'updater.release.channel' => 'stable',
  'mysql.utf8mb4' => true,
);

</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** smb federation

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 51.0.1 (64-Bit)

**Operating system:** Ubuntu 16.10/Windows 10

**Comment by michag86** [comment]
I think, this is a Problem of the richdocuments App https://github.com/nextcloud/richdocuments/issues/9

**Comment by devz3r0** [comment]
The patch in  nextcloud/richdocuments#9 works, so this can be closed.
