### ISSUE TITLE
Hi! I stell have a problem after fresh install.

### ISSUE THREAD

**Issue by MRDO5** [nextcloud/server#37502]
Hi! I stell have a problem after fresh install.

![nextcloud-clear-install](https://user-images.githubusercontent.com/35971239/229024577-c8275c42-39f4-4c5f-8799-54f70f10c25a.jpg)

 After installation when i see wrong url i press go back and it's helped.
When finally it's be corrected?

_Originally posted by @MRDO5 in https://github.com/nextcloud/server/issues/27575#issuecomment-1491280072_

**Comment by szaimen** [comment]
Hi, please create a full bug report by following https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
