### ISSUE TITLE
[Bug]: Setting a particular jpg as the profile picture fails even though its size is small enough

### ISSUE THREAD

**Issue by yashirot** [nextcloud/server#37501]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Setting a particular jpg as my profile picture fails even though its size is apparently small enough.

The jpg I tried to set was 169KB in size.

### Steps to reproduce

1. Go to Edit Profile
2. Select a particular jpg to upload
3. Click "Set as profile picture"

These steps end up with a message notifying failure.

Attached jpg I tried:
![icon_square](https://user-images.githubusercontent.com/90631147/229016068-7d80503c-ffdd-4e0c-a731-d932da90b6bb.jpg)

### Expected behavior

Setting succeeds.

FYI, png picture went well through the same steps above even if it's larger than jpg in file size.

### Installation method

None

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Sorry, I have no information
```

### Additional info

* Tried via Firefox 110.0.1
* Server info described above is according to my server admin
* And admin told me that 
   - ownCloud 10.11.0 -> Nextcloud 25.0.4 -> Nextcloud 25.0.5
   - with the `upload_max_filesize` directive in `php.ini`, the server had been configured to limit up to 2MB,
   - and there was the log notifying `/index.php/avatar` exceeded `upload_max_filesize`.
* It was my first time to set the profile pic.
* Asking admin to change temporarily `upload_max_filesize` to 20MB, my setting went well. But again, jpg I had been trying was 169KB in size.

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

**Comment by yashirot** [comment]
Raised a new Support topic with some detailed info at:
https://help.nextcloud.com/t/how-setting-a-particular-jpg-as-profile-picture-failed-even-though-its-file-size-was-apparently-small-enough/159433

It would be appreciated to make sure if this could be a setup issue.

Thanks,
