### ISSUE TITLE
Security & setup warnings: X-Content-Type-Options, X-Frame-Options when configured in vhost

### ISSUE THREAD

**Issue by fmikker** [nextcloud/server#3750]
If the headers below are configured site-wide in the apache vhost file for the site, Nextcloud admin interface will print them as not configured.
The reason for this is that the configuration is shipped with these settings in the .htaccess file in Nextcloud.

### Steps to reproduce
1. Configure mod_headers to be set in the vhost file for the site:
    Header always set X-Frame-Options "SAMEORIGIN"
    Header always set X-Content-Type-Options "nosniff"`

2. Navigate to the admin interface
3. Have a look at the security and setup warnings on the top of the page.

### Expected behaviour
The warnings should not be printed, since they are configured.

### Actual behaviour
Nextcloud should not print the misleading warning message, since the headers are set. They are in fact duplicated and the message should reflect that.
Or Nextcloud should disable the headers in .htaccess if they are already set.

### Server configuration
**Operating system**:
CentOS Linux release 7.3.1611 (Core) 
**Web server:**
httpd-2.4.6-45.el7.centos.x86_64 (Apache)
**Database:**
mariadb-5.5.52-1.el7.x86_64
**PHP version:**
PHP 5.6.25
**Nextcloud version:** (see Nextcloud admin page)
11.0.2 (stable)
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Owncloud 9.x -> Nextcloud 10.x -> 11.0.2
**Where did you install Nextcloud from:**
https://nextcloud.com/changelog/#latest10
Upgraded to latest stable via the update function in the admin view.
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.4.1
  - dav: 1.1.1
  - direct_menu: 0.10.0
  - federatedfilesharing: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - news: 10.1.0
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment]
@LukasReschke

**Comment by fmikker** [comment]
Can confirm that the issue persists on Nextcloud 12.0.2 and PHP 7.0

**Comment by janis91** [comment]
Same here for different setup:

**Web server:**
nginx

**Database:**
Postgresql

like @fmikker I also use NC 12.0.2 and PHP 7.0.

**Comment by Hillside502** [comment]
Why not 12.0.3?

**Comment by janis91** [comment]
@Hillside502 sorry, I made a mistake. 12.0.3 of course ;-)

**Comment by MorrisJobke** [comment]
Okay - just had a long discussion in #8207 - let's close this one here (as there is fewer discussion going on here) and move this over as duplicate of #8207
