### ISSUE TITLE
Backupcodes button sizes

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#3752]
If you want to call something a **papercut** ... then ... this 😅😜 The buttons should all have the same size 😉 @nextcloud/designers 

<img width="772" alt="bildschirmfoto 2017-03-07 um 16 14 01" src="https://cloud.githubusercontent.com/assets/19711361/23662872/301d6682-0351-11e7-9197-d65b3863ce9f.png">

**Comment by MorrisJobke** [comment]
cc @ChristophWurst

**Comment by MorrisJobke** [comment]
Reason for this is that the left one is a link and the right one is a button. Both with the class button.

Maybe somebody from @nextcloud/designers want to have a look.

**Comment by MorrisJobke** [comment]
Or @ChristophWurst wants to migrate the a tag to a button ;)

**Comment by ChristophWurst** [comment]
Doesn't the button size depend on the length of the text (which furthermore depends on the language)?

**Comment by MariusBluem** [comment]
This is about the height of the button.

**Comment by te-online** [comment]
`a` elements are inline elements and generally don't behave like block elements. (https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements)
Why not replace the `a` with a `button`? Would make for a better markup. Unless there is actually a link associated to that `a` element. Then I would experiment with adding something like `display: inline-block`.

**Comment by te-online** [comment]
Cool you made it work 😎 
I'd add it to the specific CSS, since I don't know how other people expect `.button` to work. 

However, I have to say that I'm not really familiar with the CSS structure here. @ChristophWurst, can you help us here? How is the process to change something like this in global CSS? 

I'm wondering if this height difference is something other places also experience, then it would make sense to change it globally.

**Comment by ChristophWurst** [comment]
> However, I have to say that I'm not really familiar with the CSS structure here. @ChristophWurst, can you help us here? How is the process to change something like this in global CSS?
> 
> I'm wondering if this height difference is something other places also experience, then it would make sense to change it globally.

Summoning our export for the standardization: @skjnldsv :raised_hands:

**Comment by skjnldsv** [comment]
> Summoning our export for the standardization: @skjnldsv :raised_hands:

`export default from skjnldsv`
You called? :grin: 

Yes, we should probably force the .button class to an inline-block :)

**Comment by MorrisJobke** [comment]
Fix is in #12138
