### ISSUE TITLE
Display collaborative tags in "Files" lists (list view)

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/server#37548]
**Is your feature request related to a problem? Please describe.**
I think collaborative tags have always been a good idea, but they are not visually prominent enough in the user interface. 

**Describe the solution you'd like**
I propose that the labels be displayed in Nextcloud Files in front of each file name or folder concerned. This would only be displayed in the detail view, but not in the grid view (due to lack of space), but it would be much better than nothing.

![2023-04-03_11-18](https://user-images.githubusercontent.com/33763786/229468828-359d7d44-b273-40e3-94fe-89081cce3219.png)

**Describe alternatives you've considered**
Another solution, graphically a little different, would be to have a small icon indicating the presence of one or more tags. Simply hover the mouse cursor over it to display the tag(s) in a tooltip. But the first solution is IMO much better in terms of UX.

![2023-04-03_11-182](https://user-images.githubusercontent.com/33763786/229469997-079cdca6-5973-4fcf-9ed4-ef65ac70f445.png)

**Comment by delacosta456** [comment]
hi 
is it possible (and make sense)to have column header (Table header) Tags with **sort** option.
Nextcloud actually doesn't a **Per File type ** sorting in file listing . So my own workaround is to:

- Setup Restricted tags of type : IsFolder, IsFile, IsFileDocx, IsFilePDF
- Setup Automated tagging workflow that tag the files on upload (i manually tag Main Folder which are group folder and set up another rules to automatically tag anything in sub-folder it the main is tag with **CreatedRestritedTag**)

This then help user filtering   by folder, by filetype, 
So having a sort by file type can help in list of 200 Files that has multiple file type listed
Thanks

**Comment by Jerome-Herbinet** [comment]
@szaimen @jancborchardt regarding the last Nextcloud major version (27), I think this issue can be closed, isn't it ?

**Comment by szaimen** [comment]
Yes it is. Thanks for pointing that out
