### ISSUE TITLE
[Bug]: search field hidden -> no info visible that it's still active

### ISSUE THREAD

**Issue by hansimausisteffiwurstbrot** [nextcloud/server#37600]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After entering a search, the field "hides" back behind the search icon.

So there is no visual clue that the users are not navigating freeley through their Nextcloud but still have an active search ongoing that limits what is swhon (to the matching list depending on the search)

### Steps to reproduce

1. Open "Files" when accessing your Nextcloud via any browser
2. Enter an "f" in the search field
3. Click elsewhere

### Expected behavior

The field should stay visible

OR 

there should be an explicit information, that the users are seeing search results

### Installation method

Community Docker image

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Multiple but actually not relevant here I guess.
```

**Comment by joshtrichards** [comment]
Thanks for the report.
Resolved since Unified Search in >=28 is a pop-out modal now.
