### ISSUE TITLE
upgrade loop due to error in config.php version handling

### ISSUE THREAD

**Issue by m-st** [nextcloud/server#3760]
I had a hard time updating my Nextcloud version from 9.0.53 upwards (first 10.0.0.4, then 11.0.1.2)
I used the manual upgrade option and was caught in an upgrade loop.
Despite having no errors running "./occ upgrade" the system would always prompt me to upgrade to the new version (10.0.0.4 in that case) again.

After some time I found the following bug (I suppose that this can't be a feature ;) )

### Probable cause
The version detection or config.php-handling probably has an error.
Additional files ending with .config.php are evaluated when they should not be considered.

### Steps to reproduce
1. Execute `./occ config:system:get version` which should respond with `11.0.1.2` (or something similiar)
2. Create a temporary copy of the current configuration with the following command: `sed "s/'version' => '.*'/'version' => '9.0.53.0'/" config/config.php  > config/YY-MM-DD.config.php` - replacing the version number with 9.0.53.0 in the new copy.
- Now, there are two files (at least) in the config directory: `config.php` and `YY-MM-DD.config.php` (My actual filename was 2016-08-15.config.php, but I tested it also with other filenames such as "backup.config.php", "YY-MM-DD.config.php", ...)
3. Execute `./occ config:system:get version` again

### Expected behaviour
Expected: The expected response should be `11.0.1.2` since the real config.php file did not change.

### Actual behaviour
Error: The incorrect actual response is `9.0.53.0`.

However, the command `occ status` reports the correct version:
```
  - installed: true
  - version: 11.0.1.2
  - versionstring: 11.0.1
```
4. Remove the file `YY-MM-DD.config.php` with the old version number and the `occ config:system:get version`-call returns the expected value as in step 1.

Somehow all files ending with config.php are evaluated where only the one "config.php" should be considered.

### Server configuration
**Docker Image**: nextcloud:11-fpm with docker-compose
**Operating system**: ubuntu-server 16.04
**Web server:** not relevant
**Database:** not relevant
**PHP version:** PHP 5.6.30 (cli) (built: Feb 28 2017 17:36:58)
**Nextcloud version:** 11.0.1.2, 10.0.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:** tried to
**Where did you install Nextcloud from:** dockerhub

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "abcdefghijk",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.example.com"
        ],
        "datadirectory": "\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/nextcloud.example.com",
        "dbtype": "mysql",
        "version": "11.0.1.2",
        "dbname": "nextcloud",
        "dbhost": "nextclouddb",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 2,
        "maintenance": false,
        "theme": ""
    }
}
```
</details>

**Are you using external storage, if yes which one:** docker volumes

**Are you using encryption:** not relevant

**Are you using an external user-backend, if yes which one:** not relevant

### Client configuration
not relevant

**Comment by nickvergessen** [comment]
> The version detection or config.php-handling probably has an error.
Additional files ending with .config.php are evaluated when they should not be considered.

That is actually part of our provisioning feature.
https://docs.nextcloud.com/server/11/admin_manual/configuration_server/config_sample_php_parameters.html

> Nextcloud supports loading configuration parameters from multiple files. You can add arbitrary files ending with `.config.php` in the `config/` directory, for example you could place your email server configuration in `email.config.php`. This allows you to easily create and manage custom configurations, or to divide a large complex configuration file into a set of smaller files. These custom files are not overwritten by Nextcloud, and the values in these files take precedence over `config.php`.

so just name your backups `config/config.YY-MM-DD.php` and you are good to go.
