### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by xnoreq** [nextcloud/server#3761]
Hello,

I am already running postgre and would rather not run a second dbms, so how well is postgre supported?
Are there any limitations?

I couldn't find any postgre-specific installation instructions. Does that mean it just works(tm)?

Thanks.

**Comment by LukasReschke** [comment]
=> https://docs.nextcloud.com/server/11/admin_manual/configuration_database/linux_database_configuration.html

=> help.nextcloud.com is the place to ask such questions :)
