### ISSUE TITLE
[Bug]: Invalid Zipped files

### ISSUE THREAD

**Issue by andy-chin** [nextcloud/server#37629]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Downloaded zipped files cannot be extracted. 

### Steps to reproduce

1. Open web UI.
2. Click Download all files.
3. After downloading the zipped file, double-click to open and extract.
4. macOS Archive Utility throws an error "Error 79 - Inappropriate file type or format."

### Expected behavior

Successfully expand/extract files.

### Installation method

None

### Nextcloud Server version

24

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
text
```

**Comment by joshtrichards** [comment]
I'm unable to reproduce this issue on NC v24.

I'm assuming you can download individual files - particularly binary ones - and that they open without problem?

How large are these files?

Can you try opening with `unzip` from a Terminal or using an alternative archive file tool like The Unarchiver?

**Comment by andy-chin** [comment]
Viewing and downloading individual files are alright.  
Scenario: I share a folder with photos and videos in it, viewer clicks Download all. After downloaded the file, when opened, it prompt invalid zipped file.

I created a share folder here for testing. https://awan.andychin.com/index.php/s/peNngRt7dbsFmDK

**Comment by andy-chin** [comment]
See screen recording to simulate the case.
https://share.cleanshot.com/BnMPkGQr

**Comment by solracsf** [comment]
Could be possibly related to https://github.com/nextcloud/server/issues/37745
_(but you should get a TAR instead of a ZIP on MacOS...)_

**Comment by szaimen** [comment]
Hi, please update to 25.0.7 or better 26.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 26-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by joshtrichards** [comment]
Are you a PC user by chance?

I wonder if the issue is you're generating the zip (as a PC user), but then sending it off as a share  to a macOS user?

I say this because the ZipStreamer  has some documented issues with some macOS  versions (hence why they get the TarStreamer presumably):

https://github.com/nextcloud/3rdparty/blob/master/deepdiver/zipstreamer/MANUAL.md

**Comment by szaimen** [comment]
Lets track this further in https://github.com/nextcloud/server/issues/38335
