### ISSUE TITLE
Explicit "Total rows summary" for translators

### ISSUE THREAD

**Issue by silopolis** [nextcloud/server#37641]
This is not explicit enough for translators to do their job easily and accurately.

https://github.com/nextcloud/server/blob/16975ae45720945776155f026835cfdaf8491383/apps/files/src/components/FilesListTableFooter.vue#L25
Could we please get a more explicit wording or a context note to help us?

Thank you in advance
J

PS: forgive me if using the feature request template leads to wrong tagging, but the bug report template is a real pain for such small reports with so many mandatory non-relevant fields

**Comment by skjnldsv** [comment]
cc @nextcloud/a11y do we have a better solution?

**Comment by Pytal** [comment]
The label itself seems fine accessibility-wise after checking various examples

Context note added for translators https://github.com/nextcloud/server/pull/42727
