### ISSUE TITLE
[Bug]: NC 26 upgrade mysql error

### ISSUE THREAD

**Issue by AlfredoCubitos** [nextcloud/server#37643]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

an upgrade to NC 26 fails due to an mysql error

I'm running NC on Freebsd 13.1-RELEASE-p2.
Updating from 25 to 26 it throws the following error:

`Exception: Database error when running migration 25000Date20220905140840 for app core An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1 Can't create/write to file '/var/db/mysql_tmpdir/ibtJW7bS' (OS errno 2 - No such file or directory)`

The directory `/var/db/mysql_tmpdir` does not exist by default. 
I do not know if on other Linux distribution this directory is created by default.

After creating the directory manually I could run the installation procedure without any errors.

May be the installation script can check this and if not exists using the default tmp directory.

### Steps to reproduce

1. run upgrade

### Expected behavior

upgrade runs without mysql error

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

26

### Operating system

Other

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.18.0
  - calendar: 4.3.2
  - circles: 26.0.0
  - cloud_federation_api: 1.9.0
  - comments: 1.16.0
  - contacts: 5.2.0
  - contactsinteraction: 1.7.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_downloadactivity: 1.16.0
  - files_external: 1.18.0
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - firstrunwizard: 2.15.0
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - notes: 4.7.2
  - notifications: 2.14.0
  - notify_push: 0.6.2
  - oauth2: 1.14.0
  - password_policy: 1.16.0
  - photos: 2.2.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0-alpha1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - spreed: 16.0.2
  - support: 1.9.0
  - systemtags: 1.16.0
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - updatenotification: 1.16.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - workflowengine: 2.8.0
```

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

**Comment by AlfredoCubitos** [comment]
well, this is more of a suggestion for improving the upgrade script so that the tmp path for mysql is set correctly on other platforms. ;-)
