### ISSUE TITLE
[Bug]: Document move failed, system notification doesn't turn off by itself

### ISSUE THREAD

**Issue by hongtring** [nextcloud/server#37658]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Document move failed, system notification doesn't turn off by itself

### Steps to reproduce

1. System login
2. Select the document, Click Actions > Move or copy
3. Select a folder > Move

### Expected behavior

Notifications are displayed for a certain period of time and then turn off by themselves

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
.
```

### List of activated Apps

```shell
.
```

**Comment by joshtrichards** [comment]
I noticed this while doing some tinkering with the quota system and its associated notifications. I debated submitting a PR to change the behavior, but ultimately concluded it's a critical message to make sure the user receives. My thinking is that someone walking away to grab a coffee wouldn't want to miss the notification.

That said, the messages can get excessive while testing. ;-)
