### ISSUE TITLE
[Bug]: davs endpoint exposes ALL user names on the server

### ISSUE THREAD

**Issue by super-horst** [nextcloud/server#37655]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I'm currently testing Debian 12 RC1 with Gnome 43.3. Gnome provides a feature to access DAV shares directly inside the file explorer. When I try to access the URL with the following pattern, I can access the nextcloud base directory (addressbooks, files, photos etc.). 
`davs://hostname/nc/remote.php/dav/files/myUser`

The Gnome integration truncates the `files/myUser` part and I land in the base directory. By selecting one of these folders (e.g. files), I get a subdirectory structure containing ALL user names on the server (even disabled users). These user directories are then empty, so only the usernames are exposed.

IMHO I should not be able to see all the user names in the system. Maybe security relevant?
The owner of the server is a friend, due to the current holidays, he is not immediately available. I will update this ticket with more relevant information if need arises.

Note:
1. I use 2FA and an App-Password to access my files.
2. The Nextcloud installation is accessible via subdirectory on the server (hence: davs://hostname/**nc**)

### Steps to reproduce

(0. use 2FA) 
1. create a new app-password
2. use this app password inside Gnome file explorer (formerly known as nautilus) via `davs://hostname/nc/remote.php/dav/files/myUser`
3. due to a Gnome Bug/Quirk the files/myUser part is truncated and the nc base directory is exposed, some of the subdirectories show all users on the server

### Expected behavior

Don't show all users, just my user

### Installation method

None

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
not yet available
```

**Comment by joshtrichards** [comment]
I suspect the owner of the server has `debug` set to `true` in their `config.php` which explicitly enables collection listing... If so, this is a local configuration issue not a bug.

```
/**
 * Set this Nextcloud instance to debugging mode
 *
 * Only enable this for local development and not in production environments
 * This will disable the minifier and outputs some additional debug information
 *
 * Defaults to ``false``
 */
'debug' => false,
```

I tried to replicate - just to doublecheck something didn't change - and I can't replicate this using CyberDuck, WinSCP, or cURL (the three webdav clients available to me at the moment):

`curl -X PROPFIND -H "Depth: 1" -u ncuser:ncuserpass http://nc-test.local:3580/remote.php/dav/files/`

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\MethodNotAllowed</s:exception>
  <s:message>Listing members of this collection is disabled</s:message>
</d:error>
```

(and cURL should be more than sufficient to trigger this)

**Comment by super-horst** [comment]
Thank you very much for that clarification, that solved the issue!
