### ISSUE TITLE
[Bug]: Editing comments does not save the log

### ISSUE THREAD

**Issue by hongtring** [nextcloud/server#37661]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Editing comments does not save the log

### Steps to reproduce

1. Sign in
2. Select document > Details > Comments
3. Edit comment
4. Confirm

### Expected behavior

Save the document's comment history

### Installation method

None

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
.
```

### List of activated Apps

```shell
.
```

**Comment by joshtrichards** [comment]
I'm unable to reproduce this.

Can you clarify whether you're reproducing this via the Web interface (i.e. not in one of the other client apps)?

Can you please provide the configuration report as requested in the initial issue form? i.e. one of:
```
sudo -u www-data php occ config:list system
php occ config:list system
./occ config:list system
```

Same for your activated apps. i.e. one of:
```
sudo -u www-data php occ app:list
php occ app:list
./occ app:list
```

And, similarly, provide time relevant log entries during your reproducing steps - i.e. one of:
```
Shell: ~$NEXTCLOUD_HOME/data/nextcloud.log
Web: /settings/admin/logging (use RAW)
```
