### ISSUE TITLE
[Bug]: No E-Mails sent in Nextcloud 26.0.0

### ISSUE THREAD

**Issue by esvk** [nextcloud/server#37694]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading to nc 26.0.0 no e-mails are sent. I already red https://github.com/nextcloud/server/issues/37329 this bug report and therefore installed the suggested patch 37340 - unfortunetly with no success. We are absolutely sure, that the credentials and sever-data are correct. This data works within WordPress on the same host.

![sshot-66](https://user-images.githubusercontent.com/130596467/231556478-dd7bcd7f-be92-42ec-93d0-e6af9cdda57c.png)

### Steps to reproduce

1. Fill in data about the Mail-Server
2. Press Save (speichern)
3. Press Send-E-Mail (E-Mail-Senden)

### Expected behavior

I would expect that nextcloud sends the test-e-mail to the given e-mail-address.

### Installation method

None

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.domain.de",
            "nextcloud.domain.biz"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.0.11",
        "overwrite.cli.url": "https:\/\/nextcloud.domain.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "default_language": "de_DE",
        "default_phone_region": "de_DE",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpdebug": true,
        "skeletondirectory": "",
        "enable_avatars": false,
        "defaultapp": "files",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "theme": "domain-theme",
        "simpleSignUpLink.shown": false,
        "loglevel": 2,
        "maintenance": false,
        "activity_use_cached_mountpoints": true,
        "app_install_overwrite": [
            "groupfolders"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.18.0
  - bruteforcesettings: 2.6.0
  - circles: 26.0.0
  - cloud_federation_api: 1.9.0
  - comments: 1.16.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_pdfviewer: 2.7.0
  - files_retention: 1.15.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - groupfolders: 14.0.0
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - nextcloud_announcements: 1.15.0
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - password_policy: 1.16.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0-alpha1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - support: 1.9.0
  - survey_client: 1.14.0
  - systemtags: 1.16.0
  - text: 3.7.2
  - theming: 2.1.1
  - theming_customcss: 1.13.0
  - twofactor_backupcodes: 1.15.0
  - updatenotification: 1.16.0
  - user_ldap: 1.16.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - workflowengine: 2.8.0
Disabled:
  - admin_audit: 1.16.0
  - contactsinteraction: 1.7.0 (installed 1.0.0)
  - encryption: 2.14.0
  - files_external: 1.18.0
  - firstrunwizard: 2.15.0 (installed 2.6.0)
  - photos: 2.2.0 (installed 1.1.0)
  - suspicious_login: 4.4.0
  - twofactor_totp: 8.0.0-alpha.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"4w2r2amHKjLha508JPgv","level":2,"time":"2023-04-12T18:46:18+00:00","remoteAddr":"172.16.32.2","user":"423u01","app":"core","method":"PROPFIND","url":"/remote.php/webdav","message":"Login failed: 'yvonne.lederle@lederle-bau.de' (Remote IP: '172.16.32.2')","userAgent":"Microsoft-WebDAV-MiniRedir/10.0.19044","version":"26.0.0.11","data":{"app":"core"}}
```

**Comment by BrookeDot** [comment]
I was not able to replicate this on Nextcloud 26 running on NGINX and PHP 8.2.x. Are there any additional errors that you can report. Or does that SMTP server work outside of Nextcloud?

**Comment by esvk** [comment]
The smtp-server works outside of Nextcloud. It‘s on another host at the same network.

--
Mit freundlichen Grüßen

mareco gmbh & co.kg
Dipl.-Ing.(FH)
Markus Zimmermann
Geschäftsführer der Komplementärin

Rothelebuch 7, 87637 Seeg
Tel. +49 (8364) 984009-0
Fax. +49 (8364) 984009-9
E-Mail. Info@ mareco.de
Internet. www.mareco.de


Sitz Seeg, HRA8889 Amtsgericht  Kempten

Persönlich haftende Gesellschafterin
CRM Verwaltungs-GmbH
Sitz Seeg,HRB9745 Amtsgericht Kempten
Geschäftsführer Markus Zimmermann





Am 12.04.2023 um 21:46 schrieb Brooke. ***@***.***>:

﻿

I was not able to replicate this on Nextcloud 26 running on NGINX and PHP 8.2.x. Are there any additional errors that you can report. Or does that SMTP server work outside of Nextcloud?

**Comment by solracsf** [comment]
Have you tried the other option at https://github.com/nextcloud/server/issues/37329 (SSL options, see **all** comments)?

**Comment by esvk** [comment]
I corrected the syntax errors - and now it works. Thank you!

**Comment by 4001982248998** [comment]
For everyone else having to work around this bug, here is a corrected syntax:

```php
  'mail_smtpstreamoptions' =>
  array (
    'ssl' =>
    array (
      'allow_self_signed' => true,
      'verify_peer' => false,
      'verify_peer_name' => false,
    ),
  ),
```

#37329 is a duplicate issue also with syntax error.

**Comment by Zaferfe** [comment]
thanks a lot

**Comment by facb69** [comment]
I've been struggling with this problem for almost a week now! Thank you so much for the tip, it worked for me.
But I must add that the _config.sample_ lacks explanation on how to use the **mail_smtpstreamoptions** option; maybe some examples would help?
But that's it; thanks again. :+1:

**Comment by Vlad-Star** [comment]
> For everyone else having to work around this bug, here is a corrected syntax:
> 
> ```
>   'mail_smtpstreamoptions' =>
>   array (
>     'ssl' =>
>     array (
>       'allow_self_signed' => true,
>       'verify_peer' => false,
>       'verify_peer_name' => false,
>     ),
>   ),
> ```

I just wanted to thank @4001982248998 for the solution provided here. I was getting the following error from my local mail relay, which was successfully resolved by adding the above block to **config/config.php**. No changes in the mail relay needed.
```
Jan 20 13:17:40 mail postfix/smtpd[4424]: SSL_accept error from www.mydomain.com[192.168.1.4]: -1
Jan 20 13:17:40 mail postfix/smtpd[4424]: warning: TLS library problem: error:0A000418:SSL routines::tlsv1 alert unknown ca:ssl/record/rec_layer_s3.c:1600:SSL alert number 48:
Jan 20 13:17:40 mail postfix/smtpd[4424]: lost connection after STARTTLS from www.mydomain.com[192.168.1.4]
```

**Comment by joshtrichards** [comment]
> But I must add that the config.sample lacks explanation on how to use the mail_smtpstreamoptions option; maybe some examples would help?

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/email_configuration.html#how-can-i-send-mail-using-self-signed-certificates-or-use-starttls-with-self-signed-certificates

**Comment by LeftoversTodayAppAdmin** [comment]
Hey folks! 

I am running the latest version of the all in one docker image, I updated the config.php file in the container according to the instructions but I am still not able to get past the error. Funny thing is I was able to add the same email account in the email tab, but im not able to get to the settings page to use the same settings to work.

Any help here will be appreciated, thank you!
Shri

**Comment by joshtrichards** [comment]
@LeftoversTodayAppAdmin Please post your query on the Help Forum - https://help.nextcloud.com since this isn't a general support channel. Someone there should be able to help you out if you post your config there.

**Comment by GitTimeraider** [comment]
> For everyone else having to work around this bug, here is a corrected syntax:
> 
> ```
>   'mail_smtpstreamoptions' =>
>   array (
>     'ssl' =>
>     array (
>       'allow_self_signed' => true,
>       'verify_peer' => false,
>       'verify_peer_name' => false,
>     ),
>   ),
> ```


Many months later and still fixing the issue for people. Thanks XD
