### ISSUE TITLE
[Bug]: Show Grid view or Show List View dissapear on scroll (expected to be sticky)

### ISSUE THREAD

**Issue by myset** [nextcloud/server#37703]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On pages with more content files, when you scroll the page to content, the "View type (list or grid)" from the right-up corner needs to be sticky/fixed.
Scrolling back on top is the workaround to see it again.

### Steps to reproduce

1. Open Nextcloud Files
2. Go into a folder with multiple files (initially, the List type appears in the right-up corner)
3. Scroll down a few pages and look back into the right-up corner, and List type disappear ;)

### Expected behavior

List type (Grid or List) expected to be sticky/fixed in the right-up corner

### Installation method

Community Docker image

### Nextcloud Server version

26

### Operating system

RHEL/CentOS

### PHP engine version

None

### Web server

None

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - announcementcenter: 6.5.1
  - appointments: 1.14.14
  - calendar: 4.3.2
  - cloud_federation_api: 1.9.0
  - comments: 1.16.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - drawio: 2.1.1
  - federatedfilesharing: 1.16.0
  - files: 1.21.1
  - files_external: 1.18.0
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_texteditor: 2.15.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - forms: 3.2.0
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - nextcloud_announcements: 1.15.0
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - password_policy: 1.16.0
  - provisioning_api: 1.16.0
  - related_resources: 1.1.0-alpha1
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - spreed: 16.0.2
  - suspicious_login: 4.4.0
  - tasks: 0.14.5
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - twofactor_totp: 8.0.0-alpha.0
  - updatenotification: 1.16.0
  - viewer: 1.10.0
  - workflowengine: 2.8.0
Disabled:
  - activity: 2.18.0 (installed 2.17.0)
  - admin_audit: 1.16.0 (installed 1.15.0)
  - bruteforcesettings: 2.6.0 (installed 2.4.0)
  - circles: 26.0.0 (installed 23.1.0)
  - contactsinteraction: 1.7.0 (installed 1.6.0)
  - emlviewer: 1.0.7 (installed 1.0.7)
  - encryption: 2.14.0
  - federation: 1.16.0 (installed 1.13.0)
  - firstrunwizard: 2.15.0 (installed 2.13.0)
  - photos: 2.2.0 (installed 2.0.1)
  - privacy: 1.10.0 (installed 1.9.0)
  - recommendations: 1.5.0 (installed 0.8.0)
  - serverinfo: 1.16.0 (installed 1.15.0)
  - support: 1.9.0 (installed 1.3.0)
  - survey_client: 1.14.0 (installed 1.13.0)
  - systemtags: 1.16.0 (installed 1.10.0)
  - text: 3.7.2 (installed 3.5.1)
  - user_ldap: 1.16.0
  - user_status: 1.6.0 (installed 1.5.0)
  - weather_status: 1.6.0 (installed 1.5.0)
```

**Comment by solracsf** [comment]
This is introduced by https://github.com/nextcloud/server/pull/36027 (cc @kesselb )
