### ISSUE TITLE
[Bug]: Fedora package broken?

### ISSUE THREAD

**Issue by cyberdynesoftware** [nextcloud/server#37715]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

As I understand it, the nextcloud package for fedora package is maintained by nextcloud and not by fedora; is this correct?

I just can't get nextcloud fired up on fedora server. There is a thread about it in the forum:

https://help.nextcloud.com/t/cant-run-installation-wizard-nor-occ/159183

Several issues arose:

nextcloud is installed in /usr/share/nextcloud, instead of in /var/www/html
The owner of the installed files is root instead of apache.
config.php is installed to /etc/nextcloud and then symlinked instead of being in the installation directory.

None of these seemed to be the problem though, applying the changes suggested in the forum did not result in nextcloud running. However, even if they would, such changes should not have to be applied to files installed via the package manager. I'm beginning to doubt that installing an update to the nextcloud package would work, rendering installing nextcloud via the package manager pointless.

Now the basic question is this: Is the package for fedora actually broken?

If not, and everything is as it should be, I would appreciate some documentation on how to get it to actually run. All documentation I could find both on nextcloud and on fedora is severly outdated and predates the availability of packages for nextcloud. I would also appreciate a rationale of why things are put into different places than seem to be expected.

### Steps to reproduce

1. Install the nextcloud package
2. Try to get it to run
3.

### Expected behavior

For nextcloud to actually run

### Installation method

None

### Nextcloud Server version

24

### Operating system

RHEL/CentOS

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
none
```

**Comment by szaimen** [comment]
Hi, please report this to the fedora repository. Nextcloud is not maintaining that one
