### ISSUE TITLE
[Bug]: File copy action is visible even though user doesn't have permission

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/server#37729]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

File copy action is displayed even if the user doesn't have necessary permissions. Trying to copy the shared file is still getting rejected properly.

### Steps to reproduce

1. Open using another account
2. Share a folder to test account
3. Uncheck all rights
4. Go to web app via test account
5. Go to the shared folder
6. Click on the button "..." next to a file inside the shared folder
7. Obtained Results : Also have "Copy" action

### Expected behavior

Expected results : Should not see Copy action

### Installation method

Community Docker image

### Nextcloud Server version

master

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.26.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - lookup_server_connector: 1.15.0
  - oauth2: 1.15.0
  - photos: 2.0.1
  - profiler: 1.3.0
  - provisioning_api: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - systemtags: 1.17.0
  - text: 3.7.2
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - admin_audit: 1.17.0
  - bookmarks: 13.0.0
  - deck: 1.8.1
  - encryption: 2.15.0
  - files_external: 1.19.0
  - recognize: 3.7.0
  - richdocuments: 8.1.0-dev.1
  - tables: 0.3.0
  - testing: 1.17.0
  - user_ldap: 1.17.0
  - user_oidc: 1.3.1
```

**Comment by marcelklehr** [comment]
cc @skjnldsv

**Comment by skjnldsv** [comment]
Which version is it starting from?

**Comment by marcelklehr** [comment]
> Which version is it starting from?

I don't know. I assume it's always been this way.

> Did you reproduce the issue?

Yes, on latest master.

> What is the webdav permission response ?

<oc:permissions>SG</oc:permissions> for the files

<oc:permissions>SGD</oc:permissions> for the folder containing them

**Comment by marcelklehr** [comment]
Seems like this line is to blame

https://github.com/nextcloud/server/blob/1a255379e85f02f3fb301f709720f3210f56b011/apps/files/js/fileactions.js#L685
