### ISSUE TITLE
[Bug]: app-menu doesn't show app names properly

### ISSUE THREAD

**Issue by SelinaGalster** [nextcloud/server#37728]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The names of the apps in the app-menu are truncated because the icons are too close together.
<img width="757" alt="Bildschirm­foto 2023-04-14 um 10 47 40" src="https://user-images.githubusercontent.com/85864205/231993578-9b873f7d-6959-4e31-ae7d-012ea40776a9.png">
I tested for english and German and also for Nextcloud v25 and v26.
Is there a way to fix this with the custom css function?

### Steps to reproduce

1. Open nextcloud in Browser
2. Login
3. hover on app-menu

### Expected behavior

I expected the full name to be visible in any language, by default.

### Installation method

Community Docker image

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "hub.rwy42.com",
            "172.17.10.53"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.5.1",
        "overwrite.cli.url": "https:\/\/hub.rwy42.com",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "maintenance": false,
        "theme": "",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - announcementcenter: 6.5.1
  - appointments: 1.14.13
  - bookmarks: 12.1.0
  - bruteforcesettings: 2.5.0
  - calendar: 4.3.1
  - calendar_resource_management: 0.4.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contacts: 5.2.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - deck: 1.8.3
  - encryption: 2.13.0
  - external: 5.0.2
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_accesscontrol: 1.15.1
  - files_antivirus: 4.0.3
  - files_automatedtagging: 1.15.3
  - files_pdfviewer: 2.6.0
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - forms: 3.2.0
  - groupfolders: 13.1.1
  - login_notes: 1.1.0
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - metadata: 0.18.0
  - nextcloud_announcements: 1.14.0
  - notes: 4.7.2
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - password_policy: 1.15.0
  - photos: 2.0.1
  - polls: 4.1.8
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - quota_warning: 1.16.0
  - ransomware_protection: 1.14.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - richdocuments: 7.1.2
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - sharebymail: 1.15.0
  - spreed: 15.0.5
  - support: 1.8.0
  - survey_client: 1.13.0
  - suspicious_login: 4.3.0
  - systemtags: 1.15.0
  - terms_of_service: 2.1.0
  - text: 3.6.0
  - theming: 2.0.1
  - theming_customcss: 1.13.0
  - twofactor_backupcodes: 1.14.0
  - twofactor_email: 2.7.2
  - twofactor_totp: 7.0.0
  - updatenotification: 1.15.0
  - user_status: 1.5.0
  - viewer: 1.9.0
  - weather_status: 1.5.0
  - workflowengine: 2.7.0
Disabled:
  - admin_audit
  - apporder: 0.15.0
  - breezedark: 25.0.1
  - files_external
  - firstrunwizard: 2.13.0
  - quicknotes: 0.8.5
  - talked: 0.5.0
  - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by szaimen** [comment]
Cc @nextcloud/designers

**Comment by marcoambrosini** [comment]
Is it time yet? By now there should be enough awareness about Nextcloud being more than a file storage and sharing solution.

| Microsoft         | Google     | Apple |
|--------------|-----------|------------|
| <img width="539" alt="Screenshot 2023-04-14 at 14 28 39" src="https://user-images.githubusercontent.com/26852655/232057164-ea2205c5-ff28-4454-ba5f-cebbf051a265.png"> | <img width="357" alt="Screenshot 2023-04-14 at 14 28 21" src="https://user-images.githubusercontent.com/26852655/232057171-49ee49d8-83fa-4b15-9d68-0067bba1774b.png"> | <img width="457" alt="Screenshot 2023-04-14 at 14 26 50" src="https://user-images.githubusercontent.com/26852655/232057176-ca7ce149-a2a4-4ef3-a4c3-d0c5956a2cbc.png"> |

**Comment by szaimen** [comment]
There is this btw: https://apps.nextcloud.com/?search=menu

**Comment by skjnldsv** [comment]
@nextcloud/designers please take a decision or close that ticket :)

**Comment by susnux** [comment]
> The names of the apps in the app-menu are truncated because the icons are too close together.

This is fixed for nextcloud 30
