### ISSUE TITLE
client shows notification to add profile information even though email address is in profile

### ISSUE THREAD

**Issue by sylvainfaivre** [nextcloud/server#3773]
### Steps to reproduce
1. fill email info in profile
2. use desktop client (tested with ubuntu client) to sync files

### Expected behaviour
No notification.

### Actual behaviour
Desktop client shows a server notification : 

> Add your profile information! For example your email is needed to reset your password.

I browsed the code at https://github.com/nextcloud/firstrunwizard/pull/18/files
I think the notification is shown because the user doesn't have a profile picture. My opinion is that the check should only concern the email address, which is needed for password reset, while the profile picture is not needed. At the very least, the notification text should be altered, as it is misleading (mentions email but email is set).

### Server configuration
**Operating system**: CentOS Linux

**Web server:** Apache 2.2

**Database:** MySQL

**PHP version:** 7

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** tar.gz packages

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - calendar: 1.5.0
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - user_external
  - user_ldap
  - user_saml

```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
not relevant
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
not relevant

### Logs
not relevant

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
The text has been adjusted for the next release to only show email, name and avatar when they are missing

**Comment by KlausWie** [comment]
Hi, i have exactly the same issue. After upgrading to NextCloud 11.0.3 i thought the issue would be gone.
However, after 47 days of wondering what i could do, i have now uplodeded a monochrome grey picture as an avatar.
![20170502_nextcloudissue](https://cloud.githubusercontent.com/assets/28111151/25621154/c2f3e03c-2f50-11e7-8e2f-8af1c8362981.PNG)

**Comment by nickvergessen** [comment]
Well it does not fix existing notifications. Just log in on the web ui, open the notifications dropdown and press the ✖️  on the notifications. The notification should then be gone on the next restart of the client.
