### ISSUE TITLE
Add `--no-lock` for `occ files:scan`

### ISSUE THREAD

**Issue by Glandos** [nextcloud/server#37756]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When using `occ files:scan` on my low-end server, the scan is slow. I'm using Redis locking, so this is the fastest path currently available. Using XDEBUG shows that removing the Redis locking triggers DB locking which is *painfully* slower.

Removing the DB lock in https://github.com/nextcloud/server/blob/master/lib/private/Files/Utils/Scanner.php#L269 (by adding `false` as additional parameters) lead to at least 33% decrease in execution time:
```
root@belette64/v/w/c.a.f/nextcloud> sudo -u www-nextcloud -g nas ./occ files:scan --path="/user/files/nas/musique/"
Starting scan for user 1 out of 1 (user)
Scanning musique with lock true
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 532     | 7364  | 00:00:55     |
+---------+-------+--------------+
root@belette64/v/w/c.a.f/nextcloud> vim lib/private/Files/Utils/Scanner.php
root@belette64/v/w/c.a.f/nextcloud> sudo -u www-nextcloud -g nas ./occ files:scan --path="/user/files/nas/musique/"
Starting scan for user 1 out of 1 (user)
Scanning musique with lock false
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 532     | 7364  | 00:00:37     |
+---------+-------+--------------+
```

**Describe the solution you'd like**
A flag could be provided in `files:scan` to percolate the `lock = false` behavior for admins that knows what they are doing.

**Describe alternatives you've considered**
Is running a scan without a lock **really** that bad?

**Additional context**
None.

**Comment by solracsf** [comment]
You already can disable file locking. Disable it, run command, enable it?
https://github.com/nextcloud/server/blob/b21c5c86e5908274e67fc31178e0dff24eed1136/config/config.sample.php#L2090-L2102

**Comment by Glandos** [comment]
That's a valid workaround, thanks, it works better than editing source code.

However, because it has a dot in its name, it's not possible to change this settings via environment like `env NC_filelocking.enabled=false ./occ files:scan` which seems more secure to me, since other users can need them while the scan is in progress.

This ticket is more like a discussion to gather feedback around this.

**Comment by solracsf** [comment]
```
#!/usr/bin/env bash
occ config:system:set filelocking.enabled --value=false --type=boolean
occ files:scan --all
occ config:system:set filelocking.enabled --value=true --type=boolean
```

**Comment by Glandos** [comment]
Thanks for the clarification.
(Un?)fortunately, I'm not running Docker, but Nextcloud on my Debian/testing box, so I already have a glibc environment. And redis is configured with Unix sockets, because I always do that wherever I can :) But the confirmation is good for me though!
