### ISSUE TITLE
[Bug]: Installation was fine but ever since I get "Writing apps directory not possible" even though FS permissions are alright

### ISSUE THREAD

**Issue by burdoto** [nextcloud/server#37755]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello,
I've spent the last days trying to install nextcloud using nginx without any notable success yet;
I was able to get the initial installation working, but ever since I am facing an error saying "writing apps directory not possible" even though my file system permissions are not the problem.

### Steps to reproduce

1. download nextcloud
2. go through installation process using a mysql db
3. bug

### Expected behavior

nextcloud should have been installed correctly using the given db

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

24

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
neither of the commands is available
```

### List of activated Apps

```shell
neither of the commands is available
```

### Nextcloud Signing status

```shell
impossible due to this error
```

### Nextcloud Logs

```shell
no messages generated during accessing the error page
```

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
