### ISSUE TITLE
Feature - Download link - Set filename in headers for download

### ISSUE THREAD

**Issue by drj-io** [nextcloud/server#3776]
When you "Share" with a "direct link" the download comes through as "download"

https://URL.com/index.php/s/[randomstring]/download

if, say, on a linux server, you do `wget https://URL.com/index.php/s/[randomstring]/download`, it names the file "download" 

In my case, I'd like it to be called what the original name was, "filename.wav" -- You should be able to do this by setting headers for "Content-Disposition".

Anyway, I just wanted to share my experience.  Thanks much.

**Comment by rullzer** [comment]
We actually do set the filename. The thing is that wget ignores this by default.

Try: `wget --content-disposition <URL>`

(of course your wget has to support this).

**Comment by drj-io** [comment]
ah ok my bad, you're right.  Thanks.
