### ISSUE TITLE
[Bug]: tabs in the right panel missing when opened via the share button in next to the folder name in the path section

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/server#37847]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If I click the share button in the top path, after I opened and close a file, the right panel opens, but does not display the tabs (sharing, activity...)
![image](https://user-images.githubusercontent.com/87175513/233394661-4aff90a8-194e-4eea-a6cb-79a4915dc34b.png)

### Steps to reproduce

1. Go into a folder
2. Open md file
3. Close the md file
4. Click the sharing icon in the path bar
5. See the right menu without the tabs

NB : 

### Expected behavior

right panel should show the tabs.

### Installation method

None

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
c.nc.c
```

### Additional info

c.nc.c

**Comment by joshtrichards** [comment]
Seems okay today (even in 26).
