### ISSUE TITLE
[Bug]: Icons in the ContactsMenu are too big

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/server#37861]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Icons next to action are too big for the button, probably, `box-sizing: border-box` is missing somewhere:
![image](https://user-images.githubusercontent.com/93392545/233612140-15e27e3f-356e-4ec0-855f-89669ced6884.png)

Source should be here:
https://github.com/nextcloud/server/blob/c08026a92ab020ac327aa7b8d379fc26cfe447bd/core/src/views/ContactsMenu.vue

### Steps to reproduce

1. Launch NC instance
2. Open contacts menu
3. Select contact and click on 3-dot menu button
4. See result

### Expected behavior

Normal size of icons

### Installation method

None

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Default list
```

**Comment by Jerome-Herbinet** [comment]
@juliushaertl can https://github.com/nextcloud/server/pull/37584 be backported to Nextcloud 26 or is it already done ?

**Comment by st3iny** [comment]
Can only be reproduced on Nextcloud 26 which is EOL.
