### ISSUE TITLE
[Bug]: Github releases, old version tagged as `latest`

### ISSUE THREAD

**Issue by aptalca** [nextcloud/server#37869]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Github releases have an older version tagged as the `latest` release:
https://github.com/nextcloud/server/releases

Version 24.0.12 is listed as latest, whereas it should be 26.0.1

### Steps to reproduce

1. Use github api to pull latest release
2. You get `v24.0.12`

### Expected behavior

Getting `v26.0.1`

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
N/A
```

### List of activated Apps

```shell
N/A
```

### Nextcloud Signing status

```shell
N/A
```

### Nextcloud Logs

```shell
N/A
```

**Comment by aptalca** [comment]
I'd also like to add that the current release marked as latest on github (v24) is EOL according to https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

Thanks

**Comment by joshtrichards** [comment]
Technically that is the latest release in the v24 train. The current three trains - v24, v25, v26 all had new releases the same day. 

The v24 one was probably the last release artifact built and therefore the "latest."

For any GH projects that have complicated (parallel) supported release trains, you can't rely on the `/releases/latest` API to represent the highest version number available - just the latest built release artifact.

For that you need to use the GH release API a bit differently - see https://frederic-hemberger.de/notes/ansible/determine-latest-software-release-from-github/

**Comment by aptalca** [comment]
> For any GH projects that have complicated (parallel) supported release trains, you can't rely on the /releases/latest API to represent the highest version number available - just the latest built release artifact.

Github specifically announced a feature last year to tackle that very problem. You can explicitly set the `latest` release independent of the date pushed.
https://github.blog/changelog/2022-10-21-explicitly-set-the-latest-release/

It looks like Nextcloud is relying on manually tagging releases and the person who did the last batch of releases for 24, 25 and 26 did not pay attention to that setting.

We're already doing some code gymnastics to figure out the highest semver, but we shouldn't have to for an upstream foss project of this size:
`curl -sX GET https://api.github.com/repos/nextcloud/server/releases | jq -r '.[] | select(.prerelease != true) | .tag_name' | sed 's|^v||g' | sort -rV | head -1`
All it takes is for them to slightly change the release tag format and our code breaks.

**Comment by aptalca** [comment]
Thanks, so it seems it's an ongoing issue.

I do see that v26.0.1 is now tagged as latest here so closing this.
