### ISSUE TITLE
Directory name

### ISSUE THREAD

**Issue by m4k7im** [nextcloud/server#3786]
### Steps to reproduce
1. Create a new directory in the root directory
2. Assign the name of the new directory Test
3. Create a new directory in the Test directory
4. Assign the name of the new directory "Test2" (the name is in quotation marks "Test2")

### Expected behaviour
Tell us what should happen
I open the directory TEST and I see in it "Test2"
### Actual behaviour
Tell us what happens instead
I open the directory TEST and do not see in it "Test2"
### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Apashe2
**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
11.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**

![test1](https://cloud.githubusercontent.com/assets/25792988/23753312/05d3efbe-04ea-11e7-9613-70f481e45712.png)
![test2](https://cloud.githubusercontent.com/assets/25792988/23753310/05d367b0-04ea-11e7-9420-98d445f06334.png)
![test3](https://cloud.githubusercontent.com/assets/25792988/23753311/05d39b0e-04ea-11e7-8202-bc4c98d6f721.png)
![test5](https://cloud.githubusercontent.com/assets/25792988/23753836/f6511d8a-04eb-11e7-9ec1-0fd47d7d823a.png)

But, if you give a general access, then clicking on the link this directory is visible
![test4](https://cloud.githubusercontent.com/assets/25792988/23753461/a3857e30-04ea-11e7-8531-78ebf6a4db0c.png)

Is there a solution?
Thank you.

**Comment by MorrisJobke** [comment]
Fixed in 11.0.2 https://github.com/nextcloud/server/pull/3138
