### ISSUE TITLE
[Bug]: NextCloud server mailer makes invalid assumptions about how to send the mail

### ISSUE THREAD

**Issue by ShamimIslam** [nextcloud/server#37912]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Premise: Send email locally via an SSH tunnel USING NO ENCRYPTION to my remote mailer

When you set up a mail server, you get to tell the system if the access is secure or not. However, the interpretation of this is not as straightforward as you might think. The options are None and SSL/TLS - which is fine. HOWEVER, if DO NOT PICK SSL/TLS, but your EMAIL SERVER REPORTS STARTTLS as a capability FOR ANY REASON, EVEN IF THE STARTTLS WILL NOT WORK OR IF YOU JUST DON'T WANT THE OVERHEAD, the symfony mailer will ASSUME you mean to use STARTTLS - it's a binary either or. If TLS is disabled, but STARTTLS advertised, STARTTLS will be used. I have an older mail server which I have not been able to migrate yet. When I selected "none" for encryption, my ASSUMPTION was that there WOULD BE NO ENCRYPTION. Not that the mailer developer would override my NO ENCRYPTION REQUIREMENT and  to use STARTTLS based on mailer capability - it was not the stated requirement.

The error is on line 112 and the "You're wrong, I'm right" explanation from the developer is present in the comments above. (I'm pretty sure this is not a very nice comment as, when I read it, I was DEEPLY offended because it basically says, paraphrasing here: 'if you don't agree with me, you must have a broken system and it's not my fault').
The file is 3rdparty/symfony/mailer/Transport/Smtp/EsmtpTransport.php

The file is signed off by anna@nextcloud.com (Anna Larch)

There needs to be an option to use NEITHER STARTTLS NOR SSL/TLS (3 options, None, SSL/TLS, STARTTLS). Developers do not get to decide what is right and wrong for a given situation. I actually had to BLOCK the entire if statement to make my mail tranport succeed. And that comment needs to be edited to be inline with the nextcloud code of conduct.

### Steps to reproduce

1. Set up a mailer with an invalid STARTTLS setup but still advertises STARTTLS
2. Ask nextcloud to send mail using no encryption
3. Nextcloud mailer will fail and the message reported with be a STARTTLS failure

### Expected behavior

The mail should travel unencrypted because that's what I asked for.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Lighttpd

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.mimmc.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "\/var\/www\/nextcloud\/core\/blank",
        "dbtype": "mysql",
        "version": "26.0.0.11",
        "overwrite.cli.url": "https:\/\/cloud.mimmc.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_phone_region": "US",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "read_timeout": 0,
            "user": "",
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 0
        },
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "loglevel": 0,
        "app_install_overwrite": [
            "user_external"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "5025"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - cloud_federation_api: 1.9.0
  - comments: 1.16.0
  - dav: 1.25.0
  - federatedfilesharing: 1.16.0
  - files: 1.21.1
  - files_lock: 26.0.0
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - firstrunwizard: 2.15.0
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - mail: 3.1.1
  - notes: 4.7.2
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - password_policy: 1.16.0
  - provisioning_api: 1.16.0
  - richdocuments: 8.0.1
  - richdocumentscode: 22.5.1301
  - secrets: 1.4.1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - snappymail: 2.27.3
  - suspicious_login: 4.4.0
  - terms_of_service: 2.1.0
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_admin: 4.1.9
  - twofactor_backupcodes: 1.15.0
  - twofactor_email: 2.7.2
  - twofactor_nextcloud_notification: 3.6.0
  - twofactor_totp: 8.0.0-alpha.0
  - user_external: 3.1.0
  - viewer: 1.10.0
  - workflowengine: 2.8.0
Disabled:
  - activity: 2.18.0 (installed 2.18.0)
  - admin_audit: 1.16.0
  - bruteforcesettings: 2.6.0
  - calendar: 4.3.3 (installed 4.3.3)
  - circles: 26.0.0 (installed 26.0.0)
  - contacts: 5.2.0 (installed 5.2.0)
  - contactsinteraction: 1.7.0 (installed 1.7.0)
  - dashboard: 7.6.0 (installed 7.6.0)
  - encryption: 2.14.0
  - federation: 1.16.0 (installed 1.16.0)
  - files_external: 1.18.0
  - nextcloud_announcements: 1.15.0 (installed 1.15.0)
  - photos: 2.2.0 (installed 2.2.0)
  - privacy: 1.10.0 (installed 1.10.0)
  - recommendations: 1.5.0 (installed 1.5.0)
  - related_resources: 1.1.0-alpha1 (installed 1.1.0-alpha1)
  - spreed: 16.0.3 (installed 16.0.3)
  - support: 1.9.0 (installed 1.9.0)
  - survey_client: 1.14.0 (installed 1.14.0)
  - systemtags: 1.16.0 (installed 1.16.0)
  - updatenotification: 1.16.0 (installed 1.16.0)
  - user_ldap: 1.16.0
  - user_status: 1.6.0 (installed 1.6.0)
  - weather_status: 1.6.0 (installed 1.6.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"5Bnny3IVRhhm6NXoxqVJ","level":0,"time":"2023-04-25T01:39:54+00:00","remoteAddr":"68.49.4.45","user":"root","app":"core","method":"POST","url":"/index.php/settings/admin/mailtest","message":"Sending mail to \"Array\n(\n    [shamim@mimmc.com] => root\n)\n\" with subject \"Email setting test\" failed","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0","version":"26.0.0.11","exception":{"Exception":"Symfony\\Component\\Mailer\\Exception\\TransportException","Message":"Unable to connect with STARTTLS: stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:\nerror:0A000102:SSL routines::unsupported protocol","Code":0,"Trace":[{"function":"Symfony\\Component\\Mailer\\Transport\\Smtp\\Stream\\{closure}","class":"Symfony\\Component\\Mailer\\Transport\\Smtp\\Stream\\SocketStream","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/symfony/mailer/Transport/Smtp/Stream/SocketStream.php","line":174,"function":"stream_socket_enable_crypto"},{"file":"/var/www/nextcloud/3rdparty/symfony/mailer/Transport/Smtp/EsmtpTransport.php","line":115,"function":"startTLS","class":"Symfony\\Component\\Mailer\\Transport\\Smtp\\Stream\\SocketStream","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/mailer/Transport/Smtp/SmtpTransport.php","line":253,"function":"doHeloCommand","class":"Symfony\\Component\\Mailer\\Transport\\Smtp\\EsmtpTransport","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/mailer/Transport/Smtp/SmtpTransport.php","line":194,"function":"start","class":"Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/mailer/Transport/AbstractTransport.php","line":72,"function":"doSend","class":"Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/mailer/Transport/Smtp/SmtpTransport.php","line":136,"function":"send","class":"Symfony\\Component\\Mailer\\Transport\\AbstractTransport","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/mailer/Mailer.php","line":45,"function":"send","class":"Symfony\\Component\\Mailer\\Transport\\Smtp\\SmtpTransport","type":"->"},{"file":"/var/www/nextcloud/lib/private/Mail/Mailer.php","line":217,"function":"send","class":"Symfony\\Component\\Mailer\\Mailer","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/MailSettingsController.php","line":168,"function":"send","class":"OC\\Mail\\Mailer","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"sendTestMail","class":"OCA\\Settings\\Controller\\MailSettingsController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":183,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1055,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/3rdparty/symfony/mailer/Transport/Smtp/Stream/SocketStream.php","Line":171,"message":"Sending mail to \"Array\n(\n    [shamim@mimmc.com] => root\n)\n\" with subject \"Email setting test\" failed","exception":[],"CustomMessage":"Sending mail to \"Array\n(\n    [shamim@mimmc.com] => root\n)\n\" with subject \"Email setting test\" failed"},"id":"644735384d268"}
```

### Additional info

This really is an oversight similar to developers not allowing negative charges on a bank account. SSL/TLS vs STARTTLS are not an either or situation, especially if the expectation is "NO ENCRYPTION"

**Comment by szaimen** [comment]
Cc @miaulalala

**Comment by miaulalala** [comment]
Hi, this is something to complain about to the symfony developers and / or to fix on your mailserver:

https://github.com/symfony/symfony/issues/49114
https://github.com/symfony/symfony/pull/34242

Cheers.

**Comment by ShamimIslam** [comment]
There is nowhere to ask the symfony developers to ask to do anything. Can't
find any "Issues" section.

As Nextcloud pulls in the 3rd party code and APPROVES the code, nextcloud
is party to the problem.

My mail server is not the issue. The invalid assumptions that I can NEVER
HAVE A START TLS advertisement with a REQUIREMENT TO NOT USE ENCRYPTION is
invalid on its face.

You are perpetuating the stance of the Symfony development team: your mail
server is at fault.

==============
        // WARNING: !$stream->isTLS() is right, 100% sure :)
        // if you think that the ! should be removed, read the code again
        // if doing so "fixes" your issue then it probably means your SMTP
server behaves incorrectly or is wrongly configured **********************
        if ( !$stream->isTLS() && \defined('OPENSSL_VERSION_NUMBER') &&
\array_key_exists('STARTTLS', $capabilities)) {
==============

Encryption setting NONE does NOT mean USE STARTTLS IF IT IS AVAILABLE.
That's what this code says. It specifically states, there is no reason why
the developer can't choose STARTTLS if it is present even if not requested.
If the intent is NONE, STARTTLS, SSL/TLS, then that should be explicit.

If a capability is provided but the settings say "NO ENCRYPTION" to be
used, how can using encryption be a "mail server problem,"

==============
miaulalala <https://github.com/miaulalala> Add Symfony\Mailer
<https://github.com/nextcloud/3rdparty/commit/16cd747ebb8ab4d746193416aa2448c8114d5084>
Latest commit 16cd747
<https://github.com/nextcloud/3rdparty/commit/16cd747ebb8ab4d746193416aa2448c8114d5084>
Jan
24, 2023
<https://github.com/nextcloud/3rdparty/commits/16cd747ebb8ab4d746193416aa2448c8114d5084/symfony/mailer/Transport/Smtp/EsmtpTransport.php>
*History*
<https://github.com/nextcloud/3rdparty/commits/16cd747ebb8ab4d746193416aa2448c8114d5084/symfony/mailer/Transport/Smtp/EsmtpTransport.php>

Signed-off-by: Anna Larch ***@***.***>
Signed-off-by: nextcloud-command ***@***.***>
==================



If nextcloud is signing off on the merge from the developer, how can it be
a pure Symfony problem when Symfony is not accepting ANY issues in the repo
in question?

Thanks.
