### ISSUE TITLE
Webdav upload file with .properties extension

### ISSUE THREAD

**Issue by dejikocv** [nextcloud/server#3792]
### Steps to reproduce
1. Create a file with .properties extension
2. Upload using webdav
3.

### Expected behaviour
The file should be upload to Nextcloud

### Actual behaviour
File is not upload and the following error is received:
Client: Malformed Content Type
Server log: 
Level: Debug
App: webdav
Message: Sabre\DAV\Exception\NotFound: HTTP/1.1 404 File with name /Phone/ExternalSD/test.properties could not be located

### Server configuration
**Operating system**: openSuse

**Web server:** Apache 2

**Database:** MariaDB

**PHP version:** PHP5

**Nextcloud version:** (see Nextcloud admin page) 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from an older ownCloud

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.

</details>

**Comment by Flux3PO** [comment]
I can confirm this.
This also happens when coming from an earlier NextCloud instance

**Comment by nickvergessen** [comment]
Works fine here. How exactly are you uploading? Are you using a sync client or the normal web UI?

**Comment by Flux3PO** [comment]
@nickvergessen 
I am using Foldersync to sync the stuff from my android phone to NextCloud.
Foldersync is using WebDav to synchronize the data.

**Comment by dejikocv** [comment]
My mistake, I forgot to indicate that I am using Foldersync to sync my files. The normal web UI works without any problem.
Foldersync have a profile for OC and another one for webdav, I tried both of them with the same result.

I just updated from OC to NC, and it was working flawlessly with OC. I checked Foldersync, but they did not have updated the app in a couple of months, so it does not look like an update break something.

**Comment by nickvergessen** [comment]
Please report the issue to Foldersync. Seems to be an issue with how they handle .properties files.

**Comment by Flux3PO** [comment]
Sure, its always easier to point the finger to someone else...

**Comment by nickvergessen** [comment]
Yes, sorry but this is no finger pointing, when uploading of the file works in via web UI and our sync client it has to be related to the one component that is different, which is this Foldersync?

**Comment by xaviermiller** [comment]
Hi!

I can upload a .proterties file with curl without any problem. So the problem seems to be at the side of foldersync.

I will open a bug there.

**Comment by WladyX** [comment]
Can you pls give the link to the bug opened for foldersync?
Sorry for spamming.

**Comment by martin-rueegg** [comment]
PS: It would be great if this issue could be renamed to something like
**File upload from FolderSync client failing**
