### ISSUE TITLE
Improve or remove warning when hiding native login form

### ISSUE THREAD

**Issue by moan0s** [nextcloud/server#37949]
**Is your feature request related to a problem? Please describe.**

Since https://github.com/nextcloud/server/pull/25910 it's possible to disable the native login form. This is a greate feature if you solely rely on SSO to login as users are less confused where to enter their credentials. The problem for me is that the current error message that replaces the form is puzzling for a user as it says: "Please contact your administrator." This is disruptive as the form not being there is expected and there is no reason to contact a system administrator if SSO works as expected.

![image](https://user-images.githubusercontent.com/25753802/234863358-a489134a-fb75-41c4-962c-ba50a976cb84.png)

**Describe the solution you'd like**

Disable the notecard altogether: As the setting is turned on by the admin there will be a reason behind this (SSO is the only one I can think of) and it is to be assumed that there is no information to the user or action from the user needed.

**Describe alternatives you've considered**

Replace the text and re-style the notecard so that it does not show a warning. It could use `notecard--success` or implement something new like `notecard--info`

This is a trough sketch how it could look like

![image](https://user-images.githubusercontent.com/25753802/234866172-b619ceb9-d7b5-4494-be9a-3c4031e4260e.png)

**Additional context**

This issue is also outlined here: https://blog.cubieserver.de/2022/complete-guide-to-nextcloud-oidc-authentication-with-authentik/

**Comment by szaimen** [comment]
Feel free to adjust the wording here: https://github.com/nextcloud/server/blob/5e96228eb1f7999a327dacab22055ec2aa8e28a3/core/src/views/Login.vue#L100

**Comment by moan0s** [comment]
I made two PRs, one removes the message, one rephrases the warning. I think both solutions would enhance the user experience, so feel free to decide which to use (I have a slight personal preference to a removal).

**Comment by danktankk** [comment]
I would also very much like to remove this eyesore after hiding the login form

**Comment by it9exm** [comment]
I've just noticed the warning message after disabling the login form and I can only imagine the hindrance and other nuisances that could happen by delivering the service with that message on, even for a company with less than 50 employees . Please provide a way to customize the message, disable or get rid of it.

**Comment by jpwgnr** [comment]
Hello, 
following up on this and #37952.
Is there a strong reason to not make the removal of the info at least optional for admins?

**Comment by NextBlaubeere** [comment]
> Hello, following up on this and [#37952](https://github.com/nextcloud/server/pull/37952). Is there a strong reason to not make the removal of the info at least optional for admins?

I would also like to see it removed.

**Comment by LabanPheidias** [comment]
I stongly agree that we should be able to hide this box. I now need to use css to remove it
