### ISSUE TITLE
[F2V] Implement files actions

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#37947]
## Common
- [x] Comment action
- [x] Download action
- [x] Rename action
- [x] Move/copy action
- [x] Edit locally action
- [x] Open directory action
- [x] Delete/restore action
- [x] Details(sidebar) action
- [x] View in folder action (open in files view)
- [x] Add/remove to/from favorites

## Sharing
- [x] Restore share
- [x] Accept share
- [x] Reject share
- [x] Share action

## Viewer
- [x] Open preview

## Approval
- [ ] Approve file
- [ ] Reject file

## Contacts
- [ ] nextcloud/contacts#3621

## Text editor 
- [ ] Edit in plain text editor

**Comment by skjnldsv** [comment]
Closing, please engineering leads, dispatch the necessary tasks amongst your team members regarding actions migrations.
@juliushaertl @nickvergessen @ChristophWurst

**Comment by ChristophWurst** [comment]
I think it would make sense to also list this change at http://127.0.0.1:8000/app_publishing_maintenance/app_upgrade_guide/upgrade_to_28.html#changed-apis.

**Comment by skjnldsv** [comment]
> I think it would make sense to also list this change at [docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_28.html#changed-apis](https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_28.html#changed-apis).

On it!!
