### ISSUE TITLE
Assign managers to users and map value in the system address book

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#37963]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

As an organization admin I want to be able to define the hierarchy of the organization inside of Nextcloud. This info shall be used to enhance the system address book (https://github.com/nextcloud/server/issues/19575) so that an organization chart can be drawn in the Contacts app (https://github.com/nextcloud/contacts/pull/2726).

**Describe the solution you'd like**

Extend the user management UI to have a dropdown for a user's manager. This can be any other Nextcloud user or nobody.

**Describe alternatives you've considered**

N/a

**Additional context**

https://github.com/nextcloud/server/issues/37800

**Comment by ChristophWurst** [comment]
@jancborchardt @nimishavijay could you describe where in the UI we should place this?

![Bildschirmfoto vom 2023-05-02 08-11-56](https://user-images.githubusercontent.com/1374172/235592086-59d0d308-0042-4bb9-afd3-9957b0a8709e.png)
![Bildschirmfoto vom 2023-05-02 08-11-59](https://user-images.githubusercontent.com/1374172/235592081-d1b525b6-38ce-4771-9d3a-86c0f9aad7c3.png)

**Comment by ChristophWurst** [comment]
I'm looking into the backend storage of the new manager(s) property for users

**Comment by jancborchardt** [comment]
> @jancborchardt @nimishavijay could you describe where in the UI we should place this?

It seems fine as the very last property on the right (even behind the optional ones like last login etc.).

**Comment by hamza221** [comment]
![image](https://user-images.githubusercontent.com/40746210/235807799-9be99ebc-9108-4717-b3b5-1f2f2c5cbc49.png)
![image](https://user-images.githubusercontent.com/40746210/235807837-ccb8b8e0-5960-4e36-8c08-a8aff523bb5b.png)
I don't think there's enough space, unless we size the existing inputs differently or we enable horizontal scroll (which is already the case on smaller screens). in the latter case , shouldn't there be a visual indication that more options are hidden

**Comment by ChristophWurst** [comment]
@hamza221 please post a screenshot of the select component placed as last property so we can have a short design feedback loop

**Comment by hamza221** [comment]
![image](https://user-images.githubusercontent.com/40746210/235871400-0c448f91-c02f-4bed-9522-8c4565a43340.png)
![image](https://user-images.githubusercontent.com/40746210/235871448-668e9956-5aa3-4484-8e11-2f530debe315.png)

**Comment by nimishavijay** [comment]
Placement of the column is great :) However, could the width of the other columns as well as the headers be adjusted so that everything in one column including the header is left aligned? 
The contents of each column should also not spill over into the next. For example, the quota extends into the region for manager, and so does email.

**Comment by hamza221** [comment]
I posted the final result in the [Pr](https://github.com/nextcloud/server/pull/38013) and for to repost it here mb 🥲
![image](https://user-images.githubusercontent.com/40746210/236007281-5659f370-c8bc-4dd3-85eb-ef89eea95b7c.png)
![image](https://user-images.githubusercontent.com/40746210/236007332-d4f11cb3-4b4e-4dbb-86f8-84e2c00a5a1a.png)
