### ISSUE TITLE
Login page stylesheets not all loaded

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#3796]
seems 0c22a6696703225baabd6a4afaad5759745da8c5 broke the login page. Since we don't have the scss compiler yet.

It seems the guest.css is missing some rules.

@MorrisJobke could you have a look?

**Comment by rullzer** [comment]
Or @skjnldsv as our scss/css man of the hour!

**Comment by MorrisJobke** [comment]
Fixed in #3798
