### ISSUE TITLE
[Bug]: Cannot 'Join conversation' of a file inside a group folder I already had permissions, after it has been shared to me again.

### ISSUE THREAD

**Issue by FuntatAli** [nextcloud/server#37960]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I cannot 'join conversation' of a file in a group folder I already have access to, when it has been shared again with me through the 'search for share recipients' function.
Instead, I am invited to re-share the file.

### Steps to reproduce

1. Alice creates a file in a group folder to which Bob has already access to
2. Alice shares the file with Bob through the 'search for share recipients' function by finding and clicking his name
3. When Bob finds the file in that group folder and enters the 'Chat' sub-menu of that file, he cannot find 'Join conversation'. Instead, he faces a 'Share this file' button.
4. If Bob clicks 'Share this file', as wrongly indicated (because it already is in a group folder), Bob is redirected to the 'Sharing' sub-menu of the same file.
5. Alternatively, if Bob enters his personal folder 'Shared' and finds the file, inside the 'Chat' sub-menu, the 'Join conversation' button is being shown. However, if he clicks on it, nothing happens. 

See below for videos of the behavior. The console indicates an error each time I click the relevant button. 
 
https://user-images.githubusercontent.com/36952462/234609318-b3909335-1495-42d9-bf97-5803453b6be1.mp4

https://user-images.githubusercontent.com/36952462/234609325-0d307ea1-82a2-488d-b44f-49691121eb12.mp4

### Expected behavior

Bob is able to press the 'Join conversation' button and join the conversation. 

'Share this file' button not being shown at all.

### Installation method

Official All-in-One appliance

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

None

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Available on request
```

### Nextcloud Signing status

```shell
No errors have been found
```

**Comment by szaimen** [comment]
Hi, this seems to be an issue of the talk app. Please create an issue for this here: https://github.com/nextcloud/spreed/issues/new?assignees=&labels=0.+Needs+triage%2C+bug&template=bug_report.md
