### ISSUE TITLE
Dev bug: duplicate dependency handlebars

### ISSUE THREAD

**Issue by JL102** [nextcloud/server#37978]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

in package.json, handlebars is listed twice, once in dependencies and once in devDependencies.

I'm not opening a PR about it because I don't know whether it properly belongs in dependencies or devDependencies.

### Steps to reproduce

N/A

### Expected behavior

N/A

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
N/A
```

### List of activated Apps

```shell
N/A
```

### Nextcloud Signing status

```shell
N/A
```

### Nextcloud Logs

```shell
N/A
```

### Additional info

N/A

**Comment by joshtrichards** [comment]
Looks like it got added to `devDependencies` in #30718 just last year (when jsunit dependencies were moved to the main package.json). From the looks of it, the proper thing to do would be to remove it from `devDependencies` since it's superfluous (it'll already be loaded by way of `dependencies`).

If you do up the PR it'll get some extra eyes on it and sorted out there if need be. :)

**Comment by JL102** [comment]
> Looks like it got added to `devDependencies` in #30718 just last year (when jsunit dependencies were moved to the main package.json). From the looks of it, the proper thing to do would be to remove it from `devDependencies` since it's superfluous (it'll already be loaded by way of `dependencies`).
> 
> If you do up the PR it'll get some extra eyes on it and sorted out there if need be. :)

@joshtrichards hm.... `handlebars-loader` is inside `devDependencies`. Is it appropriate to keep `handlebars` in `dependencies` and `handlebars-loader` in `devDependencies`?
