### ISSUE TITLE
Nextcloud Notifications not working with Nextcloud 26

### ISSUE THREAD

**Issue by michag86** [nextcloud/server#37970]
### ⚠️ Before posting ⚠️

- [X] This is a **bug**, not a question or an enhancement.
- [X] #37976
- [X] I've written a clear and descriptive title for this issue, not just "Bug" or "Crash".
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Steps to reproduce

Connect to a server that is running Nextcloud 26 and go to Notifications (Benachrichtigungen).

### Expected behaviour

Notifications are shown

### Actual behaviour

It show "Keine Benachrichtigungen" and "The Nextcloud server is not configured!"

### Android version

13

### Device brand and model

Mi 11 Lite 5G

### Stock or custom OS?

Stock

### Nextcloud android app version

3.24.2

### Nextcloud server version

26.0.0

### Using a reverse proxy?

No

**Comment by AndyScherzinger** [comment]
Transfered to server

**Comment by joshtrichards** [comment]
Does the folder `apps/notifications/` exist under your NC installation directory (I.e. /var/www/html)?

And specifically does the file `apps/notifications/lib/Service/ClientService.php` exist? 

The errors suggest that the folder is missing (or files in it are) or permissions on/in it are preventing the web server UID from accessing it properly.

**Comment by michag86** [comment]
file looks good
$ ls apps/notifications/lib/Service/ClientService.php -la
-rw-rw-r-- 1 www-data www-data 1831 Apr 19 15:38 apps/notifications/lib/Service/ClientService.php

I have two installations on this server. Both with the same errors. These installations were unattended upgraded since years by updater.phar

**Comment by joshtrichards** [comment]
Unless you are super confined on RAM you can probably boost it pretty high. For whatever reason PHP has kept the FPM default for pm.max_children set to 5 for... I couldn't even tell you how long off-hand. They compare it to Apache's MaxClients / MaxRequestWorkers which in currently defaults to 256 (and even other other server models never default to less than 16).

See what your current fpm processes are consuming each on average then see how many children you could multiply that by while still not taxing your system's memory (e.g. still leaving a still substantial buffer). That's a quick and dirty note so google around for better justification. :)

As for why the issue didn't come back immediately.... perhaps there were some syncs queued up that were getting bottlenecked and bumping it up to 10 cleared them out enough that the issue wasn't going to come back immediately even though you tried to bring max_children back down again. I think the mobile client defaults to at least 6 parallel connections or something like that. But any number of other scenarios might have triggered it. Glad it's work for you again!
