### ISSUE TITLE
Update, remove or substitute outdated npm dependencies

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#37991]
Some npm dependencies are outdated and should either be updated, removed or substituted if possible.

See https://github.com/nextcloud/server/actions/runs/4832963839/jobs/8612406101

Cc @nextcloud/server-frontend  @AndyScherzinger 

### todo
- [ ] select2
- [ ] xml2js

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/issues/1831

Regarding xlm2js this is a sub-sub-sub-sub-dependency: https://github.com/Vibrant-Colors/node-vibrant/issues/141
```
10:27 [admin@workstation] ~/Docker/server% npm ls xml2js                                                                  git:(feat/favorites-vue*)
nextcloud@1.0.0 /home/admin/Docker/server
└─┬ node-vibrant@3.1.6
  └─┬ @jimp/custom@0.16.13
    └─┬ @jimp/core@0.16.13
      └─┬ load-bmfont@1.4.1
        └─┬ parse-bmfont-xml@1.1.4
          └── xml2js@0.4.23
```

**Comment by szaimen** [comment]
All right! So close since it is already covered in other issues?

**Comment by crutchcorn** [comment]
Heads up y'all: I just published `node-vibrant` 4.0.0, which comes with some drastically improved stability and updated deps (not that we had many to start with).

Happy to make a PR to upgrade y'all to this version if you'd like 😊

**Comment by AndyScherzinger** [comment]
> Happy to make a PR to upgrade y'all to this version if you'd like 😊

Sounds good to me @crutchcorn 🎉 
Is the update a simple version bump or does 4.x imply a semantic version changes in th3e sense of it being a breaking one that needs code changes using the new version?

**Comment by crutchcorn** [comment]
> Is the update a simple version bump or does 4.x imply a semantic version changes in the sense of it being a breaking one that needs code changes using the new version?

There _are_ technically code changes, as outlined here:

https://github.com/Vibrant-Colors/node-vibrant/releases/tag/v4.0.0

The big ones I can think of are:

- No more callback APIs
- Imports are slightly different

I'll try to open a PR and see if i can't get things working :)

**Comment by AndyScherzinger** [comment]
A PR would be awesome @crutchcorn thanks a lot in advance 🎉
