### ISSUE TITLE
Pressing »enter« should also create app password

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#3799]
In this view in the app passwords:
![capture du 2017-03-11 11-43-28](https://cloud.githubusercontent.com/assets/925062/23822611/fb6d279a-064f-11e7-979c-6d2f6f27318d.png)
you can not just press enter while in the field. Should be possible though.

cc @nextcloud/designers @nextcloud/javascript

**Comment by MorrisJobke** [comment]
Fix is in #3803
