### ISSUE TITLE
Horizontal scroll on mobile not always working

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/server#380]
### Steps to reproduce
1. Log in
2. Open "Users"
3. Try to scroll to the right-hand side to view quota info
### Expected behaviour

It should scroll left/right
### Actual behaviour

Nothing
### Server configuration

**Nextcloud version: 9.0.52** (see Nextcloud admin page)
### Client configuration

**Browser: Chrome**

**Operating system: Android 6.0**

![screenshot_2016-07-12-07-42-16](https://cloud.githubusercontent.com/assets/3178412/16764392/ccd3f708-4825-11e6-9990-848f1e369688.png)

**Comment by mar1u5** [comment]
I can reproduce this 😉 ...with iOS too.

**Comment by MorrisJobke** [comment]
@skjnldsv mind to look into this?

**Comment by skjnldsv** [comment]
Can't reproduce on 12 or 11. :/

**Comment by jasonbayton** [comment]
I can't reproduce currently on 11.0.1 with a Galaxy J3. I'll see if I can on anything else. @MariusBluem can you still?

**Comment by MorrisJobke** [comment]
Seems to be gone :/
