### ISSUE TITLE
url to some images/icons not correct path

### ISSUE THREAD

**Issue by aboogerd** [nextcloud/server#3800]
Hi there, I have a problem with some icons in the activity app and photo album app. The url's  of the image are not rewrite to the correct url. I can't figure out if it's htaccess or other problem. Other images are showing correct.

`Image 1: <img alt="" src="http://my.domain/nextcloud/core/img/actions/share.svg"> and it should be <img alt="" src="http://my.domain/core/img/actions/share.svg">`
`Image 2: <img src="http://my.domain/nextcloud/apps/files/img/delete-color.svg">that should be <img src="http://my.domain/apps/files/img/delete-color.svg">`
`Image 3: <img class="svg" src="/nextcloud/core/img/actions/toggle-filelist.svg" alt="Bestandenlijst"> and this should be <img class="svg" src="/core/img/actions/toggle-filelist.svg" alt="Bestandenlijst">`

Cheers, Alexander

**Comment by tflidd** [comment]
Did you set this parameter in your `config.php`:
```
/**
 * Nextcloud attempts to detect the webroot for generating URLs automatically.
 * For example, if ``www.example.com/nextcloud`` is the URL pointing to the
 * Nextcloud instance, the webroot is ``/nextcloud``. When proxies are in use,
 * it may be difficult for Nextcloud to detect this parameter, resulting in
 * invalid URLs.
 */
'overwritewebroot' => '',
```

If you are using caching modules, make sure that you empty the cache (restart the service).

**Comment by aboogerd** [comment]
Thank you!! It just was the cache.
