### ISSUE TITLE
[Bug]: Can't delete trusted servers

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/server#38029]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The trashbin icon is missing:

![image](https://user-images.githubusercontent.com/7427347/235734564-69a93806-228f-4bae-897e-d1b9d0ed1962.png)

compare 24:

![image](https://user-images.githubusercontent.com/7427347/235734662-ad9a5b3f-510c-4c83-88a3-12905d2bf2fd.png)

### Steps to reproduce

1. Add a trusted server
2. try to delete

### Expected behavior

I can delete a trusted server url

### Installation method

Other Community project

### Nextcloud Server version

master

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
--
```

### List of activated Apps

```shell
---
```

### Nextcloud Signing status

```shell
--
```

### Nextcloud Logs

```shell
--
```

### Additional info

--

**Comment by Fenn-CS** [comment]
So, I am taking this up as a second small issue while I continue to familiarize myself with stuff!

**Comment by Fenn-CS** [comment]
Not able to reproduce on **Nextcloud 27.0.0 beta 1** 

![delete-trusted-servers](https://user-images.githubusercontent.com/14317775/236895763-358cb40d-0111-4818-bd1b-e0c44fe51586.png)
