### ISSUE TITLE
scan.nextcloud.com reports wrong version

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/server#3804]
IMO the scan reports a wrong nextcloud version

> Running Nextcloud 9.1.2.2
> NOT on latest patch level
> Major version still supported
> Scanned at 2017-03-11 07:37:53

(this was the first version I installed after upgrading from ownlcoud)

the nextcloud admin pages shows

> Version Nextcloud 11.0.2 (stable)
> Your version is up to date.

 
### Steps to reproduce
1. enter URL in scan.nextcloud.com

### Expected behaviour
should report correct version

### Actual behaviour
reports old version

### Server configuration
**Operating system**:
Debian 8
**Web server:**
Apache2
**Database:**
mariadb
**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
11.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated
**Where did you install Nextcloud from:**
source
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

> Enabled:
>   - activity: 2.4.1
>   - admin_audit: 1.1.0
>   - admin_notifications: 1.0.0
>   - announcementcenter: 3.0.0
>   - bookmarks: 0.9.1
>   - calendar: 1.5.1
>   - comments: 1.1.0
>   - contacts: 1.5.3
>   - dav: 1.1.1
>   - deck: 0.1.1
>   - external: 1.2
>   - federatedfilesharing: 1.1.1
>   - federation: 1.1.1
>   - files: 1.6.1
>   - files_external: 1.1.2
>   - files_pdfviewer: 1.0.1
>   - files_sharing: 1.1.1
>   - files_texteditor: 2.2
>   - files_trashbin: 1.1.0
>   - files_versions: 1.4.0
>   - files_videoplayer: 1.0.0
>   - firstrunwizard: 2.0
>   - gallery: 16.0.0
>   - logreader: 2.0.0
>   - lookup_server_connector: 1.0.0
>   - mail: 0.6.2
>   - nextant: 1.0.6
>   - nextcloud_announcements: 1.0
>   - notes: 2.2.0
>   - notifications: 1.0.1
>   - ocr: 2.3.0
>   - ojsxc: 3.1.1
>   - password_policy: 1.1.0
>   - provisioning_api: 1.1.0
>   - serverinfo: 1.1.1
>   - sharebymail: 1.0.1
>   - spreed: 1.2.0
>   - survey_client: 0.1.5
>   - systemtags: 1.1.3
>   - tasks: 0.9.5
>   - templateeditor: 0.2
>   - theming: 1.1.1
>   - twofactor_backupcodes: 1.0.0
>   - updatenotification: 1.1.1
>   - workflowengine: 1.1.1
> Disabled:
>   - encryption
>   - files_accesscontrol
>   - files_automatedtagging
>   - files_retention
>   - richdocuments
>   - user_external
>   - user_ldap
>   - user_saml
> 

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

> {
>     "system": {
>         "instanceid": "ocde8d3204fb",
>         "passwordsalt": "***REMOVED SENSITIVE VALUE***",
>         "datadirectory": "\/var\/www\/owncloud_data",
>         "dbtype": "mysql",
>         "version": "11.0.2.7",
>         "dbname": "owncloud",
>         "dbhost": "localhost",
>         "dbtableprefix": "oc_",
>         "dbuser": "***REMOVED SENSITIVE VALUE***",
>         "dbpassword": "***REMOVED SENSITIVE VALUE***",
>         "installed": true,
>         "enable_previews": true,
>         "forcessl": true,
>         "theme": "",
>         "maintenance": false,
>         "mail_smtpmode": "smtp",
>         "mail_smtphost": "smtp.world4you.com",
>         "mail_smtpport": "587",
>         "mail_smtptimeout": 10,
>         "memcache.local": "\\OC\\Memcache\\Redis",
>         "memcache.locking": "\\OC\\Memcache\\Redis",
>         "redis": {
>             "host": "\/var\/run\/redis\/redis.sock",
>             "port": 0,
>             "timeout": 0
>         },
>         "loglevel": 3,
>         "share_folder": "\/Shared",
>         "trusted_domains": [
>             "service.chricar.at"
>         ],
>         "mail_from_address": "xenon",
>         "mail_domain": "***REMOVED SENSITIVE VALUE***",
>         "secret": "***REMOVED SENSITIVE VALUE***",
>         "singleuser": false,
>         "forceSSLforSubdomains": true,
>         "trashbin_retention_obligation": "auto",
>         "filelocking.enabled": "false",
>         "filesystem_check_changes": 1,
>         "mail_smtpauthtype": "PLAIN",
>         "mail_smtpsecure": "tls",
>         "mail_smtpauth": 1,
>         "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
>         "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
>     }
> }
> 

**Are you using external storage, if yes which one:** local/smb/sftp/...
google drive
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
chromium
**Operating system:**
ubuntu 16.04
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MariusBluem** [comment]
This is the issue tracker of the Nextcloud Server and not of "scan.nextcloud.com" 🙈😜

The scanner has no bugtracker so I think the forum, ping @LukasReschke on IRC (or maybe! - even if it is not intended for such support - sending a mail to cloud-security-scan(at)nextcloud(dot)com) would the best place to ask for help ✌️

**Comment by ant0nwax** [comment]
I would like to reopen this issue and transform it into a feature request for an improved functionality. i was tricked by this issue myself yesterday, read here for details: https://help.nextcloud.com/t/nextcloud-security-scan-vs-installed-version-mismatch/158855

1. The Interface shows an outdated version, which is not really helpful to anyone, but you are open to explain this
2. the retrigger button is with very few contrast, instead of a button the retrigger shall be written in the beginning when you entered the URL and then it could write the old result and that we shall come back later for the fresh result... but a manually trigger is not useful if i get a result presented that is super ancient
