### ISSUE TITLE
[Bug]: Files view breaks on master

### ISSUE THREAD

**Issue by barrystyle** [nextcloud/server#38058]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Something after nextcloud/server@88f34433 is breaking the Files view.

### Steps to reproduce

1. Clone https://github.com/nextcloud/server to /var/www/nextcloud (etc as normal). Standard setup.
2. Go to Files view, create a Folder.

### Expected behavior

Receive message 'cannot create folder'.

However if HEAD is reset to 88f344339d, and cache cleared - this problem disappears.

### Installation method

None

### Nextcloud Server version

master

### Operating system

Debian/Ubuntu

### PHP engine version

Other

### Web server

None

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - calendar: 4.4.0-alpha.2
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.26.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - lookup_server_connector: 1.15.0
  - oauth2: 1.15.0
  - provisioning_api: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - systemtags: 1.17.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - admin_audit: 1.17.0
  - encryption: 2.15.0
  - files_external: 1.19.0
  - testing: 1.17.0
  - user_ldap: 1.17.0
```

**Comment by solracsf** [comment]
Cc @susnux

**Comment by susnux** [comment]
I can not reproduce this issue (tried current master (527de8ac9d989baf30144e8f9bc0381226d4aee9).

But I can also not spot any changes related to such an issue, did you try to restart your webserver / php? I often get similar issues when vendored libraries are changed but the server still uses old versions (cache).

**Comment by barrystyle** [comment]
@susnux agreed, it does feel like a transient thing but managed to end up with this outcome 3-4 times, cloning from master onto a clean vps.. if i bump into this again will try to get more details..
