### ISSUE TITLE
predis support

### ISSUE THREAD

**Issue by rugk** [nextcloud/server#3805]
On https://docs.nextcloud.com/server/11/admin_manual/configuration_server/caching_configuration.html#id3 you write one needs `php7.0-redis`. However at least for Debian, such a package does not exist. Only for php5 it is available.

However there is [`libphp-predis`](https://packages.debian.org/stretch/libphp-predis), so is it compatible with Nextcloud?
If not (as I assume) you should add support for it, so Debian users can simply install it and have redis support.

**Comment by tflidd** [comment]
Debian 8 has no PHP 7, you can use 3rd-party packages like dotdeb.org. Then the package name is `php7.0-redis` as well, or with PHP 5 it is just called `php5-redis`.

Debian 9 is coming later this year and will have PHP 7.0.

**Comment by rugk** [comment]
Yes, I meant Debian 9. There however, is no `php7.0-redis`.

**Comment by nickvergessen** [comment]
You may just try it. Anyway such support questions should be asked in our forum:
https://help.nextcloud.com/

**Comment by rugk** [comment]
Actually I tried it and it works (or just install `php-redis`).
However I explicitly not formulated this as a support question, but as a suggestion for an enhancement: What about supporting `predis`?
