### ISSUE TITLE
[Bug]: Adding email addresses is disabled for users without one set already

### ISSUE THREAD

**Issue by mejo-** [nextcloud/server#38053]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On latest master (NC27), setting an email address in their account details is disabled for user who don't already have one set.

![2023-05-03T16:36:44,374435617+01:00](https://user-images.githubusercontent.com/3582805/236026634-3f5c50ab-9cf4-4093-903d-9a52ac6d0f1d.png)

### Steps to reproduce

1. Create a new local user with `occ user:add <username>`
2. Login as that user and navigate to personal settings
3. Try to set a mail address. The button to add an address is disabled in the frontend

### Expected behavior

It should be possible for users to set a first mail address for themselves.

### Installation method

None

### Nextcloud Server version

master

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
...
```

**Comment by saifulslm09** [comment]
I am using LDAP as user-backend. I have the same issue with all my users for not being able to add their email address. Any workaround of this issue?

**Comment by Pytal** [comment]
Please open a new issue @saifulslm09 :)
