### ISSUE TITLE
--color-primary-element has bad contrast with dark primary colors on dark mode

### ISSUE THREAD

**Issue by reos-rcrozier** [nextcloud/server#38061]
Edited by @juliushaertl to match the server issue:

- Set `#1a3c34` as a primary color or pick a very darkish background image
- See that certain elements do not have a proper contrast ratio

It turns out that `--color-primary-element` doesn't really account for the dark mode.

![Screenshot 2023-05-04 at 08 34 52](https://user-images.githubusercontent.com/3404133/236128846-48e48cb4-129d-4ba6-bbec-e8b6865c0727.png)
![Screenshot 2023-05-04 at 08 35 14](https://user-images.githubusercontent.com/3404133/236128881-a8460587-d669-44b2-92e9-28fea4e8a8e8.png)
![image](https://user-images.githubusercontent.com/91322120/235941506-d17f0b90-df46-43db-9351-b4eb1d823b1a.png)

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/blob/9c3e06c046879857e91d7cf40cf2b9b6842ec0e7/apps/theming/lib/Themes/CommonThemeTrait.php#L42

We do not tell if the background is bright or not.
Fix here https://github.com/nextcloud/server/pull/38063
