### ISSUE TITLE
cURL error 77

### ISSUE THREAD

**Issue by davidmitcha** [nextcloud/server#3806]
When attempting to use the web interface apps installer to install any app, I get the following error: 

`cURL error 77: Problem with the SSL CA cert (path? access rights?)`

It appears that during the auto upgrade from 11.0.1 to 11.0.2 that the certs folder went missing? I'd appreciate some guidance here.

Shared Linux host

PHP

Version: 5.6.29
Memory Limit: 512.0 MB
Max Execution Time: 3600
Upload max size: 511.0 MB
Database

Type: mysql
Version: 5.5.51

**Comment by nickvergessen** [comment]
Can you try to replace the resources/config/ca-bundle.crt with a copy from a newly downloaded package? aka. https://raw.githubusercontent.com/nextcloud/server/master/resources/config/ca-bundle.crt

**Comment by MorrisJobke** [comment]
Close due to no feedback

**Comment by ldgbc** [comment]
Hi everyone that is having this same issue with the "cURL error 77: Problem with the SSL CA cert"

It seem like the solution provided by @nickvergessen worked, I renamed my previous ca-bundle.crt (from v11 > update > 12) with it. Upload the new file to the the above mentioned pathway. Went into my Apps installer and "Enable" it and it all working without the error.

I haven't test it for functionality (ie. all working) yet but if it install it should be okay. I think this issue only for Web-installer (Shared Hosting) and people without HTTPS (my host make you pay for it, will be looking to move to one that use Let's Encrypt service).

**Comment by ldgbc** [comment]
Hi everyone that is having this same issue with the "cURL error 77: Problem with the SSL CA cert"

It seem like the solution provided by @nickvergessen worked, I renamed my previous ca-bundle.crt (from v11 > update > 12) with it. Upload the new file to the the above mentioned pathway. Went into my Apps installer and "Enable" it and it all working without the error.

I haven't test it for functionality (ie. all working) yet but if it install it should be okay. I think this issue only for Web-installer (Shared Hosting) and people without HTTPS (my host make you pay for it, will be looking to move to one that use Let's Encrypt service).

Update: look like it a visual bug, it didn't install at all and I'm getting this error again.

**Comment by f00wl** [comment]
I've got a similar issue when adding a feed to the news app, (it solves some other CAfile/CApath related errors).

```
[news] Warning: https://rss.foo.bar/ read error : cURL error 77: error setting certificate verify locations:
  CAfile: /root/cacert.pem
  CApath: none (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

POST /apps/news/feeds
from xxx.xxx.xxx.xxx by xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx at 2019-03-20T17:30:30+00:00
```

**System**:
* AlpineLinux: `3.9`
* PHP: `7.2.14-r0`
* Nextcloud: `15.0.5`
* News: `13.1.3`

The problem came from the `/etc/php7/php.ini` config, I had to adapt these 3 lines:

```php.ini
[curl]
; A default value for the CURLOPT_CAINFO option. This is required to be an
; absolute path.
;curl.cainfo = "/root/cacert.pem"

[openssl]
; The location of a Certificate Authority (CA) file on the local filesystem
; to use when verifying the identity of SSL/TLS peers. Most users should
; not specify a value for this directive as PHP will attempt to use the
; OS-managed cert stores in its absence. If specified, this value may still
; be overridden on a per-stream basis via the "cafile" SSL stream context
; option.
openssl.cafile="/etc/ssl/certs/ca-certificates.crt"

; If openssl.cafile is not specified or if the CA file is not found, the
; directory pointed to by openssl.capath is searched for a suitable
; certificate. This value must be a correctly hashed certificate directory.
; Most users should not specify a value for this directive as PHP will
; attempt to use the OS-managed cert stores in its absence. If specified,
; this value may still be overridden on a per-stream basis via the "capath"
; SSL stream context option.
openssl.capath="/etc/ssl/certs/"
```

**NB**: commented `curl.cainfo`.

Hope it will helps someone !
