### ISSUE TITLE
Nextcloud complains if X-Frame-Options is too 'secure'

### ISSUE THREAD

**Issue by rugk** [nextcloud/server#3808]
### Steps to reproduce
1. Configure your webserver to serve `x-frame-options:"DENY"`
2. Open Nextcloud administration page.

### Expected behaviour
If frames are used/required by Nextcloud, so that this option must be `SAMEORIGIN`, report this as a compatibility error or so and let the admin decrease the "strength" of this header.
If not, just don't complain.

### Actual behaviour

Nextcloud complains that the header should be `SAMEORIGIN` and **reports this** as a "security risk". This is clearly a wrong claim.

### Server configuration
**Web server:** nginx

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** website

**Are you using encryption:** yes

**Comment by nickvergessen** [comment]
@LukasReschke please confirm

**Comment by LukasReschke** [comment]
While not a security risk we don't support `DENY`. This breaks some features built-in with Nextcloud. So one can add another error message here, but we can't just display nothing.

**Comment by rugk** [comment]
Yeah, I also noticed it break with `DENY`.

**Comment by coderkun** [comment]
All security messages have currently the format “The "{header}" HTTP header is not configured to equal to "{expected}". This is a potential security or privacy risk and we recommend adjusting this setting.”. What do you think about the DENY message to be “The "{header}" HTTP header is not configured to equal to "{expected}". Some features might not work correctly and we recommend adjusting this setting.”?

It will only require a small change and I can provide a patch for this change.

**Comment by rugk** [comment]
Yes, that sounds very good.

**Comment by grawlinson** [comment]
Am currently getting this error message:

`The "X-Frame-Options" HTTP header is not configured to equal to "SAMEORIGIN". This is a potential security or privacy risk and we recommend adjusting this setting.`

However, if I perform `curl -I <NC server instance>`, the x-frame-options header is present, and set to "SAMEORIGIN"

I upgraded from NC11 to NC12, this is a new "error" for me.

**Comment by MorrisJobke** [comment]
Fixed in #4856
