### ISSUE TITLE
[Bug]: Front-end build touches *all* apps scss/css

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#38092]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Running `npm run build` touches app scss and creates unexpected css files

I raised this earlier in https://github.com/nextcloud/server/pull/35622#issuecomment-1339442060 already and a discussion spawned at https://github.com/nextcloud/standards/issues/9 but until a decision has been made and docs still recommend people to clone into `apps` I think it's fair to say the server front-end should leave unrelated apps untouched.

### Steps to reproduce

1. Clone server
2. Clone calendar into apps
3. Compile the server front-end

### Expected behavior

No changes in the calendar repo

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
N/a
```

### List of activated Apps

```shell
N/a
```

### Additional info

cc @skjnldsv @AndyScherzinger

**Comment by ChristophWurst** [comment]
Idea: read https://github.com/nextcloud/server/blob/master/core/shipped.json and only run the sass compiler for apps in there.

Added benefit: the local build with additional apps becomes faster.

**Comment by AndyScherzinger** [comment]
Suggestion of @ChristophWurst would be fine with me, so looking for the feedback of @skjnldsv and depending on the efforts and availability I'd be okay with adding this for 27 during the stabilization phase. Not sure what you think @skjnldsv

**Comment by skjnldsv** [comment]
Sure :)
This is really a dev corner case.

You should probably use a dedicated apps folder anyway as it's been discussed multiple times :)
It's the same for composer jobs like `lint` or `php-cs`

**Comment by ChristophWurst** [comment]
The cs fixer is able to ignore anything ignored by git: https://github.com/nextcloud/server/blob/263a6910c41c07614e2a40349f2ae23e2fca0cb9/.php-cs-fixer.dist.php#L12

But yes, lint probably has the same issue. Albeit it doesn't modify additional apps.

**Comment by AndyScherzinger** [comment]
So how much work do we expect this to be and who could take care of it?

**Comment by ChristophWurst** [comment]
2h for an experienced frontender
