### ISSUE TITLE
File and folder comments and System tags not created

### ISSUE THREAD

**Issue by MikeyG** [nextcloud/server#3812]
### Steps to reproduce
1. Attempt adding comments to a file or folder and creating tags
2.
3.

### Expected behaviour
Comments or tags should be saved

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:  Linux (Gentoo)
**Web server:**  Nginx 1.10.2
**Database:**  Postgresql 
**PHP version:**
**Nextcloud version:**  11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**  One system updated the other system new install
**Where did you install Nextcloud from:**  Downloaded from Nextcloud site tar.gz
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Integrity checker has been disabled. Integrity cannot be verified.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - admin_audit: 1.1.0
  - calendar: 1.5.1
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - direct_menu: 0.10.0
  - federatedfilesharing: 1.1.1
  - files: 1.6.1
  - files_automatedtagging: 1.1.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - activity
  - documents
  - encryption
  - external
  - federation
  - files_accesscontrol
  - files_reader
  - files_retention
  - nextant
  - ownnote
  - user_external
  - user_ldap
  - user_saml

```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
  'memcache.local' => '\OC\Memcache\Redis',
  'filelocking.enabled' => true,
  'filelocking.ttl' => 360,
  'memcache.locking' => '\OC\Memcache\Redis',
  'redis' => 
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'dbindex' => 0,
    'timeout' => 1.5,
  ),
  'datadirectory' => '/home/ocdata',
  'dbtype' => 'pgsql',
  'version' => '11.0.2.7',
  'dbname' => 'owncloud',
  'dbhost' => '/var/run/postgresql',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '',
  'logtimezone' => 'America/New_York',
  'installed' => true,
  'loglevel' => 0,
  'log_rotate_size' => 5242880,

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...  NO

**Are you using encryption:**  No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**  Chrome/Edge/IE

**Operating system:**  Windows and Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
 - - [12/Mar/2017:17:00:35 -0400] "GET /apps/workflowengine/operations?class=OCA%5CFilesAutomatedTagging%5COperation HTTP/1.1" 200 2 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
 - - [12/Mar/2017:17:00:40 -0400] "POST /remote.php/dav/systemtags/ HTTP/1.1" 200 418 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
 - - [12/Mar/2017:17:00:40 -0400] "GET /settings/ajax/checksetup HTTP/1.1" 200 663 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
 - - [12/Mar/2017:17:00:43 -0400] "GET /settings/admin/logging HTTP/1.1" 200 27894 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
 - - [12/Mar/2017:17:00:44 -0400] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 74 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
 - - [12/Mar/2017:17:00:44 -0400] "GET /apps/logreader/settings HTTP/1.1" 200 100 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
 - - [12/Mar/2017:17:00:44 -0400] "PROPFIND /remote.php/webdav HTTP/1.1" 207 3666 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
 - - [12/Mar/2017:17:00:44 -0400] "GET /heartbeat HTTP/1.1" 200 5 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
 - - [12/Mar/2017:17:00:44 -0400] "GET /apps/logreader/get?offset=0&count=50 HTTP/1.1" 200 19022 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
 - - [12/Mar/2017:17:00:49 -0400] "GET /settings/ajax/checksetup HTTP/1.1" 200 663 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
 - - [12/Mar/2017:17:00:50 -0400] "GET /apps/logreader/get?offset=50&count=25 HTTP/1.1" 200 6137 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
 - - [12/Mar/2017:17:01:14 -0400] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 74 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
 - - [12/Mar/2017:17:01:41 -0400] "GET /settings/admin/workflow HTTP/1.1" 200 34368 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
 - - [12/Mar/2017:17:01:42 -0400] "PROPFIND /remote.php/dav/systemtags/ HTTP/1.1" 207 977 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
 - - [12/Mar/2017:17:01:42 -0400] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 74 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
 - - [12/Mar/2017:17:01:42 -0400] "PROPFIND /remote.php/dav/systemtags/ HTTP/1.1" 207 977 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
 - - [12/Mar/2017:17:01:42 -0400] "PROPFIND /remote.php/webdav HTTP/1.1" 207 3666 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
 - - [12/Mar/2017:17:01:42 -0400] "GET /heartbeat HTTP/1.1" 200 5 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
 - - [12/Mar/2017:17:01:42 -0400] "GET /apps/workflowengine/operations?class=OCA%5CFilesAutomatedTagging%5COperation HTTP/1.1" 200 2 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
 - - [12/Mar/2017:17:01:48 -0400] "GET /settings/ajax/checksetup HTTP/1.1" 200 663 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
 - - [12/Mar/2017:17:01:58 -0400] "POST /remote.php/dav/systemtags/ HTTP/1.1" 200 418 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Error	PHP	Cannot modify header information - headers already sent at Unknown#0

Error	PHP	ErrorException: Cannot modify header information - headers already sent at /var/www/nextcloud/lib/private/Session/Internal.php#146	

Error	remote	ErrorException: Cannot modify header information - headers already sent
[internal function] OC\Session\Internal->trapError(2, 'Cannot modify h...', '/var/www/nextcl...', 106, Array)
/var/www/nextcloud/lib/private/legacy/response.php - line 106: header('HTTP/1.1 500 In...')
/var/www/nextcloud/lib/base.php - line 439: OC_Response setStatus(500)
/var/www/nextcloud/lib/base.php - line 678: OC initSession()
/var/www/nextcloud/lib/base.php - line 1092: OC init()
/var/www/nextcloud/remote.php - line 110: require_once('/var/www/nextcl...')
{main}

Error	base	ErrorException: Cannot modify header information - headers already sent
[internal function] OC\Session\Internal->trapError(2, 'Cannot modify h...', '/var/www/nextcl...', 51, Array)
/var/www/nextcloud/lib/private/Session/Internal.php - line 51: setcookie('octzg1w6aier', '', -1, '/')
/var/www/nextcloud/lib/base.php - line 428: OC\Session\Internal->__construct('octzg1w6aier')
/var/www/nextcloud/lib/base.php - line 678: OC initSession()
/var/www/nextcloud/lib/base.php - line 1092: OC init()
/var/www/nextcloud/remote.php - line 110: require_once('/var/www/nextcl...')
{main}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

DevTools failed to parse SourceMap: https://<URL>/core/vendor/jquery/dist/jquery.min.map
jquery-migrate.min.js?v=f45245a…:2 JQMIGRATE: Migrate is installed, version 1.4.0
DevTools failed to parse SourceMap: https://<URL>/core/vendor/jquery/dist/jquery.min.map
```
</details>

**Comment by nickvergessen** [comment]
Seems like one of your files is corrupted and produces output.
Can you try to run the integrity check on the admin page?

**Comment by MikeyG** [comment]
Can you give me exactly what I need to run to get an answer?  On the admin page I get:
Security & setup warnings All checks passed.

**Comment by MikeyG** [comment]
Is there any other info I could provide?

**Comment by MikeyG** [comment]
In answer to:  Seems like one of your files is corrupted and produces output.
I had the time to check today:

1. wget https://download.nextcloud.com/server/releases/nextcloud-11.0.2.tar.bz2

2. diff -r /var/www/nextcloud ./nextcloud
Only in /var/www/nextcloud/apps: calendar
Only in /var/www/nextcloud/apps: contacts
Only in /var/www/nextcloud/apps: direct_menu
Only in /var/www/nextcloud/apps: documents
Only in /var/www/nextcloud/apps: files_reader
Only in ./nextcloud/apps/gallery/documentation: wiki
Only in /var/www/nextcloud/apps: nextant
Only in /var/www/nextcloud/apps: ownnote
Only in /var/www/nextcloud/apps: tasks
Only in /var/www/nextcloud/config: config.php
diff -r /var/www/nextcloud/.htaccess ./nextcloud/.htaccess
80,83d79
< #### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
< 
< ErrorDocument 403 //core/templates/403.php
< ErrorDocument 404 //core/templates/404.php

**Comment by MikeyG** [comment]
I have a better nginx log file:

Tag Create @ 05:35  
Folder Comment @ 05:40   
File Comment @ 05:44


2017/03/21 05:35:13 [error] 30959#30959: *3119 NAXSI_FMT: ip=192.168.1.1&server=[MyServer URL]&uri=/settings/admin/workflow&learning=1&vers=0.55&total_processed=63&total_blocked=23&block=1&cscore0=$XSS&score0=16&zone0=HEADERS&id0=1315&var_name0=cookie, client: 192.168.1.1, server: [MyServer URL], request: "GET /settings/admin/workflow HTTP/1.1", host: "[MyServer URL]"
2017/03/21 05:35:14 [error] 30959#30959: *3119 NAXSI_FMT: ip=192.168.1.1&server=[MyServer URL]&uri=/heartbeat&learning=1&vers=0.55&total_processed=64&total_blocked=24&block=1&cscore0=$XSS&score0=16&zone0=HEADERS&id0=1315&var_name0=cookie, client: 192.168.1.1, server: [MyServer URL], request: "GET /heartbeat HTTP/1.1", host: "[MyServer URL]"
2017/03/21 05:35:14 [error] 30958#30958: *3255 NAXSI_FMT: ip=192.168.1.1&server=[MyServer URL]&uri=/settings/ajax/checksetup&learning=1&vers=0.55&total_processed=213&total_blocked=125&block=1&cscore0=$XSS&score0=16&zone0=HEADERS&id0=1315&var_name0=cookie, client: 192.168.1.1, server: [MyServer URL], request: "GET /settings/ajax/checksetup HTTP/1.1", host: "[MyServer URL]"
2017/03/21 05:35:14 [error] 30959#30959: *3119 NAXSI_FMT: ip=192.168.1.1&server=[MyServer URL]&uri=/apps/workflowengine/operations&learning=1&vers=0.55&total_processed=65&total_blocked=25&block=1&cscore0=$XSS&score0=16&cscore1=$TRAVERSAL&score1=8&zone0=HEADERS&id0=1315&var_name0=cookie&zone1=ARGS&id1=1205&var_name1=class, client: 192.168.1.1, server: [MyServer URL], request: "GET /apps/workflowengine/operations?class=OCA%5CFilesAutomatedTagging%5COperation HTTP/1.1", host: "[MyServer URL]"
2017/03/21 05:35:19 [error] 30959#30959: *3119 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0" while reading response header from upstream, client: 192.168.1.1, server: [MyServer URL], request: "POST /remote.php/dav/systemtags/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "[MyServer URL]"
2017/03/21 05:35:19 [error] 30959#30959: *3119 FastCGI sent in stderr: "PHP message: PHP Warning:  Cannot modify header information - headers already sent in Unknown on line 0" while reading upstream, client: 192.168.1.1, server: [MyServer URL], request: "POST /remote.php/dav/systemtags/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "[MyServer URL]"
2017/03/21 05:35:21 [error] 30958#30958: *3255 NAXSI_FMT: ip=192.168.1.1&server=[MyServer URL]&uri=/settings/admin/logging&learning=1&vers=0.55&total_processed=214&total_blocked=126&block=1&cscore0=$XSS&score0=16&zone0=HEADERS&id0=1315&var_name0=cookie, client: 192.168.1.1, server: [MyServer URL], request: "GET /settings/admin/logging HTTP/1.1", host: "[MyServer URL]"
2017/03/21 05:35:22 [error] 30959#30959: *3119 NAXSI_FMT: ip=192.168.1.1&server=[MyServer URL]&uri=/apps/logreader/settings&learning=1&vers=0.55&total_processed=66&total_blocked=26&block=1&cscore0=$XSS&score0=16&zone0=HEADERS&id0=1315&var_name0=cookie, client: 192.168.1.1, server: [MyServer URL], request: "GET /apps/logreader/settings HTTP/1.1", host: "[MyServer URL]"
2017/03/21 05:35:22 [error] 30958#30958: *3256 NAXSI_FMT: ip=192.168.1.1&server=[MyServer URL]&uri=/settings/ajax/checksetup&learning=1&vers=0.55&total_processed=215&total_blocked=127&block=1&cscore0=$XSS&score0=16&zone0=HEADERS&id0=1315&var_name0=cookie, client: 192.168.1.1, server: [MyServer URL], request: "GET /settings/ajax/checksetup HTTP/1.1", host: "[MyServer URL]"
2017/03/21 05:35:22 [error] 30958#30958: *3257 NAXSI_FMT: ip=192.168.1.1&server=[MyServer URL]&uri=/heartbeat&learning=1&vers=0.55&total_processed=216&total_blocked=128&block=1&cscore0=$XSS&score0=16&zone0=HEADERS&id0=1315&var_name0=cookie, client: 192.168.1.1, server: [MyServer URL], request: "GET /heartbeat HTTP/1.1", host: "[MyServer URL]"
2017/03/21 05:35:22 [error] 30959#30959: *3119 NAXSI_FMT: ip=192.168.1.1&server=[MyServer URL]&uri=/apps/logreader/get&learning=1&vers=0.55&total_processed=67&total_blocked=27&block=1&cscore0=$XSS&score0=16&zone0=HEADERS&id0=1315&var_name0=cookie, client: 192.168.1.1, server: [MyServer URL], request: "GET /apps/logreader/get?offset=0&count=50 HTTP/1.1", host: "[MyServer URL]"
2017/03/21 05:40:42 [error] 30958#30958: *3256 NAXSI_FMT: ip=192.168.1.1&server=[MyServer URL]&uri=/settings/admin/workflow&learning=1&vers=0.55&total_processed=217&total_blocked=129&block=1&cscore0=$XSS&score0=16&zone0=HEADERS&id0=1315&var_name0=cookie, client: 192.168.1.1, server: [MyServer URL], request: "GET /settings/admin/workflow HTTP/1.1", host: "[MyServer URL]"
2017/03/21 05:40:42 [error] 30959#30959: *3321 NAXSI_FMT: ip=192.168.1.1&server=[MyServer URL]&uri=/settings/ajax/checksetup&learning=1&vers=0.55&total_processed=68&total_blocked=28&block=1&cscore0=$XSS&score0=16&zone0=HEADERS&id0=1315&var_name0=cookie, client: 192.168.1.1, server: [MyServer URL], request: "GET /settings/ajax/checksetup HTTP/1.1", host: "[MyServer URL]"
2017/03/21 05:40:42 [error] 30959#30959: *3322 NAXSI_FMT: ip=192.168.1.1&server=[MyServer URL]&uri=/heartbeat&learning=1&vers=0.55&total_processed=69&total_blocked=29&block=1&cscore0=$XSS&score0=16&zone0=HEADERS&id0=1315&var_name0=cookie, client: 192.168.1.1, server: [MyServer URL], request: "GET /heartbeat HTTP/1.1", host: "[MyServer URL]"
2017/03/21 05:40:43 [error] 30959#30959: *3320 NAXSI_FMT: ip=192.168.1.1&server=[MyServer URL]&uri=/apps/workflowengine/operations&learning=1&vers=0.55&total_processed=70&total_blocked=30&block=1&cscore0=$XSS&score0=16&cscore1=$TRAVERSAL&score1=8&zone0=HEADERS&id0=1315&var_name0=cookie&zone1=ARGS&id1=1205&var_name1=class, client: 192.168.1.1, server: [MyServer URL], request: "GET /apps/workflowengine/operations?class=OCA%5CFilesAutomatedTagging%5COperation HTTP/1.1", host: "[MyServer URL]"
2017/03/21 05:40:52 [error] 30959#30959: *3321 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0" while reading response header from upstream, client: 192.168.1.1, server: [MyServer URL], request: "POST /remote.php/dav/systemtags/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "[MyServer URL]"
2017/03/21 05:40:52 [error] 30959#30959: *3321 FastCGI sent in stderr: "PHP message: PHP Warning:  Cannot modify header information - headers already sent in Unknown on line 0" while reading upstream, client: 192.168.1.1, server: [MyServer URL], request: "POST /remote.php/dav/systemtags/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "[MyServer URL]"
2017/03/21 05:41:39 [error] 30959#30959: *3321 NAXSI_FMT: ip=192.168.1.1&server=[MyServer URL]&uri=/apps/files/&learning=1&vers=0.55&total_processed=71&total_blocked=31&block=1&cscore0=$XSS&score0=16&zone0=HEADERS&id0=1315&var_name0=cookie, client: 192.168.1.1, server: [MyServer URL], request: "GET /apps/files/ HTTP/1.1", host: "[MyServer URL]"
2017/03/21 05:41:40 [error] 30959#30959: *3321 NAXSI_FMT: ip=192.168.1.1&server=[MyServer URL]&uri=/apps/gallery/config&learning=1&vers=0.55&total_processed=72&total_blocked=32&block=1&cscore0=$XSS&score0=16&zone0=HEADERS&id0=1315&var_name0=cookie, client: 192.168.1.1, server: [MyServer URL], request: "GET /apps/gallery/config?extramediatypes=1 HTTP/1.1", host: "[MyServer URL]"
2017/03/21 05:41:40 [error] 30959#30959: *3322 NAXSI_FMT: ip=192.168.1.1&server=[MyServer URL]&uri=/apps/systemtags/lastused&learning=1&vers=0.55&total_processed=73&total_blocked=33&block=1&cscore0=$XSS&score0=16&zone0=HEADERS&id0=1315&var_name0=cookie, client: 192.168.1.1, server: [MyServer URL], request: "GET /apps/systemtags/lastused HTTP/1.1", host: "[MyServer URL]"
2017/03/21 05:43:19 [error] 30959#30959: *3319 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0" while reading response header from upstream, client: 192.168.1.1, server: [MyServer URL], request: "POST /remote.php/dav/comments/files/3130256/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "[MyServer URL]"
2017/03/21 05:43:19 [error] 30959#30959: *3319 FastCGI sent in stderr: "PHP message: PHP Warning:  Cannot modify header information - headers already sent in Unknown on line 0" while reading upstream, client: 192.168.1.1, server: [MyServer URL], request: "POST /remote.php/dav/comments/files/3130256/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "[MyServer URL]"
2017/03/21 05:44:36 [error] 30959#30959: *3357 FastCGI sent in stderr: "PHP message: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0" while reading response header from upstream, client: 192.168.1.1, server: [MyServer URL], request: "POST /remote.php/dav/comments/files/4919171/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "[MyServer URL]"
2017/03/21 05:44:36 [error] 30959#30959: *3357 FastCGI sent in stderr: "PHP message: PHP Warning:  Cannot modify header information - headers already sent in Unknown on line 0" while reading upstream, client: 192.168.1.1, server: [MyServer URL], request: "POST /remote.php/dav/comments/files/4919171/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "[MyServer URL]"

**Comment by MikeyG** [comment]
This was causing all the problems:
```
FastCGI sent in stderr: "PHP message: PHP Deprecated:  Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0" while reading response header from upstream, client: 192.168.1.1, server: [MyServer URL], request: "POST /remote.php/dav/comments/files/4919171/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "[MyServer URL]"
```
Setting always_populate_raw_post_data = -1 in php.ini fixed issue.

```
; Always populate the $HTTP_RAW_POST_DATA variable. PHP's default behavior is
; to disable this feature and it will be removed in a future version.
; If post reading is disabled through enable_post_data_reading,
; $HTTP_RAW_POST_DATA is *NOT* populated.
; http://php.net/always-populate-raw-post-data
always_populate_raw_post_data = -1
```

**Comment by nickvergessen** [comment]
Glad to hear you found the issue
