### ISSUE TITLE
Config parameter in config.php to disable use of proxy push-notifications.nextcoud.com

### ISSUE THREAD

**Issue by Volker-K** [nextcloud/server#38122]
**Describe the solution you'd like**
Config parameter in config.php to disable use of proxy push-notifications.nextcloud.com

**Describe alternatives you've considered**
Disabling the proxy by redirecting it via /etc/hosts causes error messages, same when using a proxy and putting the host name in proxy exceptions

**Additional context**
Hello, due to the hard implementation of the Fair Use Policy, things have started to move in our organization.

1. we all understand, I think, that Nextcloud GmbH wants to avoid too much load (and thus costs) from large Nextcloud Community Edition instances on the push notification server.
2. Nextcloud is open source and free to use for anyone who wants to use it ("This License explicitly affirms your unlimited permission to run the unmodified Program.").
3. many operators of Nextcloud instances are willing to do without push notifications to mobile devices in order to conserve Nextcloud's resources.
4. by using the server at Nextcloud GmbH, data of the individual instances is processed in "third-party" IT systems. The GDPR stipulates in Article 28 that in these cases, as a rule, an agreement must be concluded with this processor to ensure that the rights of the individuals whose data is processed are respected. In Germany, case law has established that even logging the IP address of a call can be considered processing of personal data, because in many cases the IP address is personally identifiable. 
This means that without a corresponding agreement, the use of push notifications can also be a legal violation. At least that's what our data protection officer says.

It is currently only possible to disable push notifications by deactivating the entire "Notifications" app. However, this also disables the notifications in the browser, which are necessary, for example, when you want to transfer folders or files to other users via GUI. 

Even with the "Notifications" app turned off, however, the fair-use message, which is confusing to say the least due to its wording, is displayed when logging in.

I therefore suggest to be able to deactivate the push notifications to mobile devices by a parameter in config.php. This requires only a little programming effort.

1. file **apps/notifications/lib/Push.php**

At the beginning of the function **protected function sendNotificationsToProxies():** addthe following three lines:

```
if ( $this->config->getSystemValueBool('disable_mobile_push',false) ) {
            return;
}

```

2. file **lib/private/Notification/Manager.php**

Line

`$isFairUse = $this->subscription->delegateHasValidSubscription() || $this->userManager->countSeenUsers() < 1000;`

Replace with

`$isFairUse = $this->subscription->delegateHasValidSubscription() || $this->userManager->countSeenUsers() < 1000 || $this->config->getSystemValueBool('disable_mobile_push',false);
`
Incl., of course, import of the IConfig functions.

With these changes, operators of a cloud instance can completely disable the push notifications via the Nextcoud GmbH proxy by simply adding
  `'disable_mobile_push' => true,`
in their config.php and, as I understand it, including the messages, which are then no longer true.

**Comment by svenseeberg** [comment]
I find it surprising that the Nextcloud internal notifications do not work when the external push gateway is (rightfully so) not available/usable. It should be up to the server operator to make sure that everything works internally.

**Comment by Volker-K** [comment]
> This is the wrong place for this discussion. Contact Nextcloud GmbH directly. See #37322 EDIT: sorry I thought this request was created just today. Anyhow, closed -> see issue above.

I don't see any discussion here. 

This is a serious request for a new feature. 

I have merely described why _we_ need this feature to use the software licensed under GNU AGPLv3. 

I know that operators of other Nextcloud instances would also like to stop using the push proxy for various reasons - because they don't want to cause Nextcloud GmbH any costs, for example. Or because they don't want to connect external servers due to the effort involved (firewall/proxy activations). There are many possible reasons.

If the request cannot/should not be implemented, I think it would be appropriate to justify this other than by saying that I should contact Nextcloud GmbH myself.

**Comment by klorydryk** [comment]
Same : it is not a discussion. Either nextcloud is a free and open source software and there is no need to show this kind of message, or it isn't.
If it is, the connection to Nextcloud GmbH notification server should obviously be disengageable to remove dependancy and not pass on NC GmbH to support the cost of all instances.

**Comment by Lanchon** [comment]
after seeing the shocking manner in which nextcloud handled this issue, i decided that they cannot be trusted. is there a similar project that does not include anti-features, or at least a nextcloud fork determined to remove them? thanks.

**Comment by Lanchon** [comment]
thank you! where is your repo?

**Comment by svenseeberg** [comment]
> thank you! where is your repo?

I'm solving this way:

First, I'm fully disabling the push gateway:

```diff
--- /nextcloud/apps/notifications/lib/Push.php	2023-05-16 13:15:48.481656420 +0200
+++ /nextcloud/apps/notifications/lib/Push.php	2023-05-16 13:04:21.693314809 +0200
@@ -374,7 +374,7 @@
 		if (empty($pushNotifications)) {
 			return;
 		}
-
+     return;
 		if (!$this->notificationManager->isFairUseOfFreePushService()) {
 			/**
 			 * We want to keep offering our push notification service for free, but large
```

Then I'm changing the test:

```diff
--- /opt/nextcloud/lib/private/Notification/Manager.php	2023-05-16 13:14:56.629628812 +0200
+++ /opt/nextcloud/lib/private/Notification/Manager.php	2023-05-16 13:14:02.865599957 +0200
@@ -298,6 +298,7 @@
 	 * {@inheritDoc}
 	 */
 	public function isFairUseOfFreePushService(): bool {
+			return true;
 		$pushAllowed = $this->cache->get('push_fair_use');
 		if ($pushAllowed === null) {
 			/**
```

**Comment by doedje** [comment]
In /nextcloud/apps/notifications/lib/Push.php it says:

```
                if (!$this->notificationManager->isFairUseOfFreePushService()) {
                        /**
                         * We want to keep offering our push notification service for free, but large
                         * users overload our infrastructure. For this reason we have to rate-limit the
                         * use of push notifications. If you need this feature, consider using Nextcloud Enterprise.
                         */
                        return;
                }
```

Since I **don't** need the the feature, I like to be able to **disable** it as proposed in this issue.

**Comment by denis-ismailaj** [comment]
@jospoortvliet can this be reopened?

It was made clear that this is just a feature request for a flag to disable mobile push notifications.

It involves no wording changes and no licensing or sales discussions like the other related issues.

**Comment by netdox** [comment]
I am also a little irritated that we seem to be trying to create a dependency with Nextcloud GmbH? 
My customer uses Nextcloud in a network without internet access, so there is no possibility to use any external services.
And yet we have this message on the login dialogue, it could have been displayed in the admin dashboard, but it doesn't seem to be a friendly hint, rather a kind of blackmail that you should finally use the Enterprice version.
If I am wrong, I wonder where the option is in the config.php to disable this external, unwanted service, like mention from [denis-ismailaj](https://github.com/denis-ismailaj) 

Thanks to [svenseeberg](https://github.com/svenseeberg) I was able to disable the message, but it is difficult to understand how Nextcloud GmbH justifies this message without using the push notifications from Nextcloud GmbH itself.
