### ISSUE TITLE
[Bug]: Share confirmations messages wrong

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#38157]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

https://github.com/nextcloud/server/blob/fc076271c791998272856b640be4b63cfe3263a2/apps/files_sharing/src/mixins/SharesMixin.js#L280

See screenshot

![image](https://github.com/nextcloud/server/assets/12234510/134ee18a-9c7c-411a-ae56-5aac486ee699)

### Steps to reproduce

1. Create a share link
2. Update expiration date or Hide dowload
3. See confirmation messages

### Expected behavior

Variables are implemented (and translated)

### Nextcloud Server version

25

**Comment by solracsf** [comment]
Cc @JuliaKirschenheuter as you're the author of https://github.com/nextcloud/server/pull/35655 😉

**Comment by AndyScherzinger** [comment]
Also cc @Pytal due to the bank holiday in Germany

**Comment by solracsf** [comment]
Having this fixed for v28 would be great.
