### ISSUE TITLE
Usage of getlastmodified and ordering

### ISSUE THREAD

**Issue by mario** [nextcloud/server#3815]
`curl -u mario:bla -X SEARCH http:/bla/nextcloud/remote.php/dav/files/mario/ --data '<?xml version="1.0" encoding="UTF-8"?><d:searchrequest xmlns:d="DAV:" xmlns:oc="http://nextcloud.com/ns"><d:basicsearch><d:select><d:prop><d:displayname/><d:getcontenttype/><d:resourcetype/><d:getcontentlength/><d:getlastmodified/><d:creationdate/><d:getetag/><d:quota-used-bytes/><d:quota-available-bytes/><oc:permissions xmlns:oc="http://owncloud.org/ns"/><oc:id xmlns:oc="http://owncloud.org/ns"/><oc:size xmlns:oc="http://owncloud.org/ns"/><oc:favorite xmlns:oc="http://owncloud.org/ns"/></d:prop></d:select><d:from><d:scope><d:href>/files/mario</d:href><d:depth>infinity</d:depth></d:scope></d:from><d:where><d:gt><d:prop><d:getlastmodifed/></d:prop><d:literal>2017-03-10T22:06:30Z</d:literal></d:gt></d:where><d:orderby><d:order><d:prop><d:getlastmodified/></d:prop><d:descending/></d:order></d:orderby></d:basicsearch></d:searchrequest>'`

I can't seem to get this to work. Two things:

1) Using getlastmodified I want to get files modified in the last 7 days
2) Orderby doesn't seem to work (aka errors out) no matter what query I use

Can you please clarify? :)

**Comment by MorrisJobke** [comment]
Fixed in #3824
