### ISSUE TITLE
Sharing icon not displayed for files shared to the user

### ISSUE THREAD

**Issue by Clementine46** [nextcloud/server#38156]
Most files on Nextcloud have a sharing icon on the right, next to the file's menu.

However, when another user shares a file with me, the sharing icon is replaced by the avatar of said user. This change can be quite confusing for some users, as they won't know where to click if they want to open the sharing panel on the right.

![Artboard Copy 10](https://github.com/nextcloud/server/assets/50834537/007e5ed4-7e9d-4428-879a-8f9f548a4ee9)

I conducted a series of user tests, in which practically all users, even the advanced ones, hesitated when asked to share a folder that had been shared to them. Some of them also bypassed the issue by going into the details, inside the file's menu. 

The lack of sharing icon is confusing for users. I suggest to make it permanent to make things more cohesive and easier to understand. The icon also doesn't take a lot of space.

![Artboard Copy 6](https://github.com/nextcloud/server/assets/50834537/4b8f4b4d-74dc-4999-b257-34b578851c59)

@jancborchardt @nimishavijay what do you think ? :)

**Comment by szaimen** [comment]
In my opinion the mockup looks good. So reaching over to engineering. cc @nextcloud/server-frontend

**Comment by skjnldsv** [comment]
From https://github.com/nextcloud/server/issues/37208

## Two issues with the "Shared" indicator in the files list
- It is not super present
- The icons are not aligned with the icons of non-shared files

## Describe the solution you'd like
- The text and icon of the "Shared" indicator could be colorized in `var(--color-primary-element)`
- The icons would look better if to the right of the "Shared" text, so they align with the other icons in the list

###Additional context
Current:
![image](https://user-images.githubusercontent.com/925062/224966680-db5c41d3-597d-4603-8cfe-c9039ee9b89b.png)

Proposed:
![Sharing colorized](https://user-images.githubusercontent.com/925062/224966705-ca66773f-b6b1-4abe-a7a3-b170873e9db4.png)


I guess we could have both

**Comment by skjnldsv** [comment]
@Clementine46 and @nextcloud/designers 
Since we now have real button-like design int he files app (for accessibility and from the API), can you do me a feedback on this please:
![image](https://github.com/nextcloud/server/assets/14975046/e40913ca-3b70-48ea-a372-d97174e45313)

**Comment by szaimen** [comment]
Looks very good to me now that the status looks like a button that can be clicked :)

**Comment by Jerome-Herbinet** [comment]
I love it !

**Comment by szaimen** [comment]
Reopening due to https://github.com/nextcloud/server/pull/41656

**Comment by skjnldsv** [comment]
> @jancborchardt Jan C. Borchardt removed this from 🖍 Design team 3 weeks ago

So we don't want this?

**Comment by skjnldsv** [comment]
Closing see https://github.com/nextcloud/server/issues/43443
