### ISSUE TITLE
Flat shared (either regular or by link) list via search

### ISSUE THREAD

**Issue by mario** [nextcloud/server#3817]
I'd like to retrieve a flat list of shared files (either normal or by link) via Search.

If there's another way, let me know.

**Comment by nickvergessen** [comment]
There is the OCS share api which also has an endpoint to get all shares?
https://docs.nextcloud.com/server/12/developer_manual/core/ocs-share-api.html?highlight=share or
http://lukasreschke.github.io/OpenCloudMeshSpecification/#list-of-shares

Can you try that one first?

**Comment by mario** [comment]
Will do, thanks @nickvergessen.

**Comment by nickvergessen** [comment]
Feel free to reopen when it is not enough.
