### ISSUE TITLE
[Bug]: Synchronization is not possible due to incorrect file modification time

### ISSUE THREAD

**Issue by miedru** [nextcloud/server#38178]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When trying to sync a folder, this error pops up. the desktop version of Nextcloud is used

### Steps to reproduce

1. Uploading a folder to the Explorer synced by Nextcloud
2. Waiting for the folder to sync with the server
3. 

### Expected behavior

Folder upload to the server

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Could not open input file: occ
Could not open input file: occ
No such file or directory
```

### List of activated Apps

```shell
Could not open input file: occ
Could not open input file: occ
No such file or directory
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by szaimen** [comment]
Hi, please create a new ticket in english

**Comment by miedru** [comment]
@szaimen translated it into English
