### ISSUE TITLE
[Bug]: Style not loaded, no theming, no scrollbar

### ISSUE THREAD

**Issue by Coernel82** [nextcloud/server#38172]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

All sudden most of the style information was gone and I got raw text. The navigation was white on white.
I did not tinker with theming settings - it happened over night and it also is a very fresh install.
The DOM expector said that the stylefile could not be loaded.

First idea was to change them theme from standard to dark. Without success.
After [some research](https://help.nextcloud.com/t/theme-gone-after-upgrade-to-25-and-26rc1/154492/15) I tried to create css files in /var/www/html/apps/theming/theme - no success and deleted the directory again.
Also I tried ```occ maintenance:theme:update```  and ```occ maintenance:repair``` and of course some reboots and forced reloads in the browser bypassing the cache (Ctrl+Shift+F5 in Firefox). Also I used the control panel of nextcloud pi to fix permissions (though there should not have been any changes and cleared the opcache. Nothing helped.

However - again I have done nothing except reloading the page **the theme is back.** Maybe the maintenance:repair took some time to take effect? As this might occur to other I still decided to upen a bug report so you can have this "on your radar".

![css gone](https://github.com/nextcloud/server/assets/19374121/08fe931d-3818-47c0-867a-e49bfc447746)

### Steps to reproduce

I am very sorry - unknown.

### Expected behavior

Theme shows up as normal.

### Installation method

Community NextcloudPi appliance

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "apps": {
        "systems": []
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.18.0
  - calendar: 4.3.3
  - circles: 26.0.0
  - cloud_federation_api: 1.9.0
  - comments: 1.16.0
  - contacts: 5.2.0
  - contactsinteraction: 1.7.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - firstrunwizard: 2.15.0
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - news: 21.1.0
  - nextcloud_announcements: 1.15.0
  - nextcloudpi: 0.0.1
  - notes: 4.7.2
  - notifications: 2.14.0
  - notify_push: 0.6.2
  - oauth2: 1.14.0
  - password_policy: 1.16.0
  - photos: 2.2.0
  - previewgenerator: 99.99.99
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0-alpha1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - support: 1.9.0
  - survey_client: 1.14.0
  - systemtags: 1.16.0
  - tasks: 0.14.5
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - workflowengine: 2.8.0
Disabled:
  - admin_audit: 1.16.0
  - breezedark: 26.0.0 (installed 26.0.0)
  - bruteforcesettings: 2.6.0
  - encryption: 2.14.0
  - files_external: 1.18.0
  - pride: 1.1.0 (installed 1.1.0)
  - suspicious_login: 4.4.0
  - twofactor_totp: 8.0.0-alpha.0
  - updatenotification: 1.16.0 (installed 1.16.0)
  - user_ldap: 1.16.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
log is to long!
```

### Additional info

DOM-Inspector: Could not load style file.

**Comment by joshtrichards** [comment]
Hi @Coernel82 - Thanks for the report. Usually when I come across this it's something environment specific. 

- In your browser console under the Network tab, which resources are returning errors (probably 4xx or 500 errors I'm guessing based on the symptoms)?
- How fresh was this installation, specifically? (Trying to get an idea of whether caching - either server or client side was a factor)
- Can you share a sample of a couple of the entries from the NC or web server logs during one of these events?

**Comment by Coernel82** [comment]
Hello @joshtrichards!
As the error is gone I cannot tell you about 4xx or 500 errors. The installation was very, very fresh. Maybe hours, maybe some days. As the post now is 4 months old I cannot be more specific.
Also I cannot share the logs as they are not there any more. I keep this in mind if it happens the next time.

**Comment by joshtrichards** [comment]
Sounds good. Glad it went away for now. :) If it returns do let us know.
