### ISSUE TITLE
Notes app cannot write to files

### ISSUE THREAD

**Issue by d-jsb** [nextcloud/server#3818]
Tried to create notes with the notes app but could not save.

### Error Log 
Error PHP Undefined variable: data at /www/htdocs/lib/private/Files/Storage/Wrapper/Wrapper.php#251 2017-03-13T10:10:41+0100 
Error PHP Missing argument 2 for OC\Files\Storage\Wrapper\Wrapper::file_put_contents(), called in /www/htdocs/lib/private/Files/View.php on line 1124 and defined at /www/htdocs/w015b9f0/cloud.rudering.de/lib/private/Files/Storage/Wrapper/Wrapper.php#250 2017-03-13T10:10:41+0100 
Error files_texteditor File: /Notes/Neue Notiz.txt modified since opening. 2017-03-13T10:10:28+0100 
 
### Code
			/** @var \OC\Files\Storage\Storage $storage */
...					if (!is_null($extraParam)) {
						$result = $storage->$operation($internalPath, $extraParam);
					} else {
1124 ->					$result = $storage->$operation($internalPath);
					}

maybe add an empty 2nd parameter?

Could not reproduce with a second user yet.

**Comment by nickvergessen** [comment]
This needs to be fixed on the notes app
