### ISSUE TITLE
Calendar App: Overlay issue when having high amount of personal calendars

### ISSUE THREAD

**Issue by DerZeitspringer** [nextcloud/server#382]
I'm having twelve calendars stored within my Nextcloud account at the moment.
With that (high) amount there's an overlay issue with the "Abonnements" section. 
The entry of the last personal calendar (second pink one) is overlaying the headline.

See attached Screenshots for comparison.

**My Calendar:**
![kalender](https://cloud.githubusercontent.com/assets/10948258/16771216/f568e8de-484f-11e6-9df6-b3c51e17aeef.png)
----------

**An empty Calendar:**
![kalender-leer](https://cloud.githubusercontent.com/assets/10948258/16771217/f5954a82-484f-11e6-8224-4fcd96177c21.png)
----------

### Server configuration
**Nextcloud version:** 9.0.52

**Updated from an older Nextcloud/ownCloud:**
Upgrade from OwnCloud 9.0.2 (best decision ever \*g\*)

### Client configuration
**Browser:** Independent (tested with FF 47, IE 10, Chrome 51 on Windows 7)

**Comment by juliushaertl** [comment]
This looks more like an issue in the calendar app. 

Please refile an issue at https://github.com/owncloud/calendar
