### ISSUE TITLE
[Bug]: Portainer, Docker Swarm, OnlyOffice connector with NextCloud behind a reverse proxy doesn't load the documents

### ISSUE THREAD

**Issue by as-shura** [nextcloud/server#38210]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I am running everything in local mode in a docker swarm cluster and everything works fine when I access NextCloud with OnlyOffice connector. Each word file or spreadsheet opens fine and I can edit. The problem is that I made my NextCloud instance available through a tunneling interface online (nextcloud.mydomain.com) which allows me to access the instance with LetsEncrypt automatic generated certificate. All the servers are in http mode in the internal network but there is an HTTPS facade managed by the tunneling public server.

I am getting this error when running from online internet not locally:

![image](https://github.com/nextcloud/server/assets/123847861/a36c0ba3-7285-4d55-ae2d-a50092356802)

![image](https://github.com/nextcloud/server/assets/123847861/1c50b6b2-dadf-4e8b-b00f-2041a19db9c3)

### Steps to reproduce

Create a local docker swarm network with 3 nodes.

1. 1 node is for Postgres, rabbitmq, etc ...
2. 1 node has NextCloud
3. 1 node has OnlyOffice Document Server

Use a public server nextcloud.mydomain.com to login and open an office document.

### Expected behavior

 The file should be showned like in local mode but it doesn't because the NextCloud admin panel is HTTPS when the local instance is non HTTPS and OnlyOffice also is not secured. 

### Installation method

Community Docker image

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
'trusted_domains' => 
  array (
    0 => '192.168.1.4:9090',
	1 => 'nextcloud.mydomain.com', #HTTPS is here handled automatically by reverse proxy tunneling
	2 => '192.168.1.100:8080',
  ),
```

OnlyOffice locally working setup configuration

![image](https://github.com/nextcloud/server/assets/123847861/8e154a1b-a5c8-4ac7-96ee-feacd7877da1)
### List of activated Apps

```shell
Extras
```

### Nextcloud Signing status

```shell
Extras
```

### Nextcloud Logs

```shell
Extras
```

### Additional info

Extras

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
