### ISSUE TITLE
[Bug]: [ERROR] files: SW registration failed: NS_ERROR_CONTENT_BLOCKED

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#38219]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The files service worker doesn't work on my dev instance

```
[ERROR] files: SW registration failed:  
Object { app: "files", uid: "admin", level: 1, error: Exception }
​
app: "files"
​
error: Exception { name: "NS_ERROR_CONTENT_BLOCKED", result: 2153644038, filename: "https://localhost/dist/files-main.js?v=723d337d-53", … }
​​
columnNumber: 0
​​
data: null
​​
filename: "https://localhost/dist/files-main.js?v=723d337d-53"
​​
lineNumber: 2
​​
message: ""
​​
name: "NS_ERROR_CONTENT_BLOCKED"
​​
result: 2153644038
​​
stack: "71030/<@https://localhost/dist/files-main.js?v=723d337d-53:2:64822\nEventListener.handleEvent*71030@https://localhost/dist/files-main.js?v=723d337d-53:2:64666\no@https://localhost/dist/files-main.js?v=723d337d-53:2:113029\ns<@https://localhost/dist/files-main.js?v=723d337d-53:2:114507\no.O@https://localhost/dist/files-main.js?v=723d337d-53:2:113329\n@https://localhost/dist/files-main.js?v=723d337d-53:2:114521\n@https://localhost/dist/files-main.js?v=723d337d-53:2:114527\n"
​​
<prototype>: ExceptionPrototype { toString: toString(), name: Getter, message: Getter, … }
​
level: 1
​
uid: "admin"
​
<prototype>: Object { … }
ConsoleLogger.js:59:10
```

### Steps to reproduce

1. Run server 1399c88ee178d9fd60f3e9356f1d8c498c6c97e1
2. Open /apps/files
3. Look at the console

### Expected behavior

No errors

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
N/a
```

### Additional info

FF on Linux
Nextcloud runs on localhost with TLS

cc @skjnldsv 

The SW was added in https://github.com/nextcloud/server/pull/36534

**Comment by szaimen** [comment]
I think SW dont work with self-signed cert? cc @skjnldsv

**Comment by skjnldsv** [comment]
Self signed isn't compatible for security reason, this is a browser's issue.
You can safely ignore

**Comment by ChristophWurst** [comment]
Is there any limitation in Nextcloud when the SW doesn't run? Asking to understand if this might be an issue for instances that use self-signed certs. For my dev instance I don't care a lot.

**Comment by skjnldsv** [comment]
No, it will fallback as default behaviour.
The SW is a middleware intercepting specific path for faster cache and delivery :)
