### ISSUE TITLE
Adding tag with leading 0

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#38221]
When adding a tag "0123", then it first is shown correctly.
![image](https://github.com/nextcloud/server/assets/5836855/15e0cf4d-c0e7-49f7-aba8-33c9a78d80cf)

But on page refresh it is like this:
![image](https://github.com/nextcloud/server/assets/5836855/d91b58de-794e-465a-ba59-55f0f79a06e2)

_Originally posted by @tobiasKaminsky in https://github.com/nextcloud/server/issues/38067#issuecomment-1541365683_

**Comment by szaimen** [comment]
Cc @nextcloud/server-backend

**Comment by tobiasKaminsky** [comment]
I think this is only @nextcloud/server-frontend, as API is giving correct "0123".

**Comment by Pytal** [comment]
This comes from the `webdav` lib

Fixed upstream in https://github.com/perry-mitchell/webdav-client/pull/341
