### ISSUE TITLE
Usability flaw: Password reset procedure is not clear to non-technical users

### ISSUE THREAD

**Issue by floeschie** [nextcloud/server#3823]
As long as I am using Own/Nextcloud, the "Add new user" and "reset password" process has been confusing for my users, because there is no intuitive way to let the users (re-)set their password.

## Background

I maintain a Nextcloud instance for a small non-profit organization (German: "gemeinnütziger Verein"). Usually, my users (members) are known to me, but I do not meet them regularly in person, or they don't use PGP for e-mail encryption.

When a new member has to be set up, I create an account for them, and they get their username and login URL by e-mail automatically through Nextcloud. However, there is no info about the password or how to obtain it in the notification e-mail. So the open the login form, look at the form labels, and do not know how to proceed, because they do not know the password I entered and there is no "Reset password" call-to-action visible. Especially the non-technical users are too afraid to enter anything into the login form, because some information is missing to them.

So they head back to me by phone or e-mail, and I would either have to explain them they should enter a random string as password, or I would trigger the password reset procedure myself. Both is time consuming, annoying and confusing to the users.

### Expected behaviour
Other systems - like Wordpress for example - provide an initial one-time password or a link to set the password in the welcome e-mail which is sent to the new user. They then can click on the link and have to change the one-time password to some passphrase of their choosing. A new user, who opens the login screen for the first time, and does not know the password, does not know what to do.

The user manual does not contain any hint about the password reset procedure. Only the admin manual describes this, but regular users do not read the admin manual, or are afraid of the technical terms or fear to break anything.

### Actual behaviour
The e-mail does neither contain the user's (one-time) password, nor as link or information how to obtain/set the password. Users have to explicitly enter a wrong password before they get presented the link for the password reset. The link to the password reset page is not recognizable as a link, because it does not change the look on mouseover like other links do. The user manual should cover the "Reset password" use case as well.

**Comment by nickvergessen** [comment]
Can I ask you to merge your information into a comment on https://github.com/nextcloud/server/issues/3565
