### ISSUE TITLE
[BITV]: Bug User management table view regressions

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#38245]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

https://github.com/nextcloud/server/pull/37870 introduced two regressions

1) table doesn't align, td columns float to the left
2) actions background element doesn't match row background
  ![Bildschirmfoto vom 2023-05-12 12-02-14](https://github.com/nextcloud/server/assets/1374172/28755fb5-eae8-4200-8647-c5e5844c2f0d)
3) Overlapping text while the user list loads
   ![image](https://github.com/nextcloud/server/assets/1374172/e0ddb27a-e79b-4dfd-b108-d44b066fd152)

### Steps to reproduce

1. Install Nextcloud
2. Open the user management page
3. Add at least one user

### Expected behavior

Columns align & good design

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
N/a
```

**Comment by ChristophWurst** [comment]
0d3df2c795ad1ae1222c1b3408fe02b7e2e1e1bf is the first bad commit

**Comment by ChristophWurst** [comment]
@JuliaKirschenheuter is this fixable for RC2?

**Comment by JuliaKirschenheuter** [comment]
> @JuliaKirschenheuter is this fixable for RC2?

i will try to fix it for RC2

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/pull/38474 will fix the issue for 27
