### ISSUE TITLE
Preview tests should not require the DB

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#383]
Right now the preview tests require the DB. There is not really a need for this.
I think this is because the tests are on a low level of abstraction (using views etc). And requiring the user to login.

This login part I think triggers the DB access at some point.

@icewind1991 as our trait master could you take a look?

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by CarlSchwan** [comment]
Preview use the db now
