### ISSUE TITLE
Top spinner is hardly visible

### ISSUE THREAD

**Issue by rugk** [nextcloud/server#3831]
### Steps to reproduce
1. Set your colour to `A2BB59`
2. Install "Direct Menu"
2. Click on some app icons.

### Expected behaviour
I want to see the spinner.

### Actual behaviour
A very light spinner is shown on a light background… not suitable.

### Server configuration
**Operating system**: Debian

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

### Client configuration
**Browser:** Firefox 52.0

**Comment by MorrisJobke** [comment]
cc @juliushaertl because you work on the direct menu app and the theming :)

**Comment by juliushaertl** [comment]
This is an issue of direct_menu, can you reopen the issue over there:
https://github.com/juliushaertl/direct_menu

This issue might also occur with: https://github.com/nextcloud/server/pull/3008
