### ISSUE TITLE
Changing folder should also reset the search

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#38312]
When searching in files, and changing the view (e.g `Recent` to `Trashbin`), it currently resets any ongoing search.
Shall it also do that when changing folder?

EDIT: yes it should

cc @jancborchardt @nimishavijay @szaimen 
ref: https://github.com/nextcloud/server/pull/38303#discussion_r1195333922

**Comment by szaimen** [comment]
I would say yes as it is confusing otherwise. There is also an open issue about this somewhere.

**Comment by szaimen** [comment]
I think it is this one: https://github.com/nextcloud/server/issues/32126

**Comment by jancborchardt** [comment]
Yes, agree as well, the search should be reset on navigation as it is basically its own view.

**Comment by skjnldsv** [comment]
Thanks :)

**Comment by susnux** [comment]
Resolved with https://github.com/nextcloud/server/pull/44882
