### ISSUE TITLE
[Bug]: "Add group" in user management broken

### ISSUE THREAD

**Issue by mejo-** [nextcloud/server#38340]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On latest master (Nextcloud 27), the "Add group" button doesn't work. When entering a group name and submitting, nothing happens. Also no error log in the console and no network request is triggered.

### Steps to reproduce

1. Go to /index.php/settings/users as admin
2. Press the "+ Add group" button in the left panel
3. Type a group name and press the submit button

### Expected behavior

A new group should be created.

### Installation method

None

### Nextcloud Server version

master

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Not relevant
```

**Comment by szaimen** [comment]
Cc @nextcloud/server-frontend

**Comment by Fenn-CS** [comment]
@artonge I would look into this now.

**Comment by mejo-** [comment]
How about adding Cypress tests for things like that to prevent regressions in the future?

**Comment by artonge** [comment]
> How about adding Cypress tests for things like that to prevent regressions in the future?

Cypress tests are always welcome. skjnldsv added the possibility to add some in the server recently

**Comment by Fenn-CS** [comment]
> skjnldsv added the possibility to add some in the server recently

Please can you link me to that? could add it to my backlog

**Comment by artonge** [comment]
> Please can you link me to that? could add it to my backlog

https://github.com/nextcloud/server/tree/master/cypress
