### ISSUE TITLE
bookmarks in the file mover window

### ISSUE THREAD

**Issue by foscone** [nextcloud/server#38342]
Hi, it would be nice to have the links to your favorite folders in the file move window to be able to reach the folders you use most frequently faster.
Something like this:
![disegno](https://github.com/nextcloud/server/assets/29599997/1a0bbeb4-84ef-4dfa-8e60-84cbe00ee142)

**Comment by szaimen** [comment]
Cc @nextcloud/designers

**Comment by jancborchardt** [comment]
Very good point – totally agree. It could be the same component as we use in the Talk settings modal, with a navigation on the left.

@marcoambrosini what do you think?

**Comment by jancborchardt** [comment]
@marcoambrosini right, then let's just say it could look the same. :)

**Comment by jancborchardt** [comment]
Closing this in favor of https://github.com/nextcloud/server/issues/38926 which has some more additional improvements to bring the file picker up to scratch.

Nice mockup @foscone – if you want to get involved more in Nextcloud design, we have a page with more info at https://nextcloud.com/design :)
