### ISSUE TITLE
Welcome panel does not parse user description

### ISSUE THREAD

**Issue by rugk** [nextcloud/server#3834]
### Steps to reproduce
1. Enter HTML `<a href` link into your webserver description.
2. Show the welcome panel.

### Expected behaviour
Just as this kind of "wanted-XSS" is done in the server description on the bottom of the (login) site, also parse the HTML here.

### Actual behaviour
There the HTML seems to be escaped.

### Server configuration
**Operating system**: Debian

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

### Client configuration
**Browser:** Firefox 52

**Comment by MorrisJobke** [comment]
> There the HTML seems to be escaped.

This is by intention. We don't support HTML in the description of the server (I guess you mean the theming app setting)

Right @LukasReschke and @juliushaertl ?

**Comment by rugk** [comment]
Seriously? In this case it would be an XSS for the general login page where this HTML is *not* escaped.
I thought you consider the admin fully trusted and let them execute arbitrary code as I read on HackerOne, that's why I reported it here.

**Comment by MorrisJobke** [comment]
Cc @lukasreschke

**Comment by nickvergessen** [comment]
Looking at https://github.com/nextcloud/server/commit/75fd6d4fde4cd6d9eda5e6b944739f1f2798447d it seems to be used in many places explicitly using print_unescaped. So I'd argue it's intended, in which case the firstrunwizard would need fixing.
