### ISSUE TITLE
Wrong display of sharing (icon is offset)

### ISSUE THREAD

**Issue by JordanDIG** [nextcloud/server#38351]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The icon is offset from the rest of the menu as shown in the attached picture.

### Steps to reproduce

1. Go to file
2. Share a file
2. Right Click on the file

### Expected behavior

A correct display

### Installation method

Community Docker image

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
/
```

### List of activated Apps

```shell
/
```

### Nextcloud Signing status

```shell
/
```

### Nextcloud Logs

```shell
/
```

### Additional info

![image](https://github.com/nextcloud/server/assets/38187648/0c06ca40-4940-435a-948b-2ec4e80a4ec0)

**Comment by skjnldsv** [comment]
FIxed on 27.1 and above
