### ISSUE TITLE
Debian compatibility

### ISSUE THREAD

**Issue by pboguslawski** [nextcloud/server#38363]
According to

https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_26.html#back-end-changes

nc 26+ drops php 7.4 support. One of the most popular linux distros, Debian in it's current stable version 11 does not support php 8.

When upgrading dependencies consider keeping deps compatibility with popular linux distros like Debian.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/issues/35025
