### ISSUE TITLE
[UI]: apps/settings/src/views/Users.vue - "New user" should have a "+" like "+ Add group"

### ISSUE THREAD

**Issue by mjmccarn** [nextcloud/server#38362]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When looking at Settings -> Users:
  * the new user button simply says "New user"
  * the add group button says "+ Add group"

These two buttons do very similar functions (adding entries to the user/group back-end) and the style difference generates cognitive dissonance.  

I see "+ Add group" immediately and look for "+ Add user" for 1 - 2 seconds before noticing "New user" at the top left.  

I have needed to point out the "new user" button 3 times to a coworker who uses this screen only infrequently.

"New User" should get a plus sign ("+ New User")

[I am guessing here!] I think this would be done by editing apps/settings/src/views/Users.vue and adding code to generate the "+"

```

			<NcAppNavigationNew button-id="new-user-button"
				:text="t('settings','New user')"
				button-class="icon-add"
				@click="showNewUserMenu"
				@keyup.enter="showNewUserMenu"
				@keyup.space="showNewUserMenu" />
				+ <template #icon>
				+ 	<Plus :size="20" />
				+ </template>

```

### Steps to reproduce

1. Open "Users"
2.
3.

### Expected behavior

"New User" and "+ Add Group" should be more stylistically similar

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.7",
            "vcloud.aicr.org",
            "aicr.dyndns.org",
            "192.168.1.89"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded-for-headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/vcloud.aicr.org",
        "dbtype": "pgsql",
        "version": "26.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "logtimezone": "Europe\/London",
        "log_authfailip": true,
        "log_rotate_size": 104857600,
        "cache_path": "",
        "knowledgebaseenabled": true,
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\PDF",
            "OC\\Preview\\SVG",
            "OC\\Preview\\Photoshop"
        ],
        "asset-pipeline.enabled": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            },
            {
                "path": "\/var\/www\/nextcloud\/apps-local",
                "url": "\/apps-local",
                "writable": false
            }
        ],
        "xframe_restriction": true,
        "mail_smtpport": "25",
        "updatechecker": false,
        "activity_expire_days": 3652,
        "enable_certificate_management": true,
        "trashbin_retention_obligation": "auto",
        "singleuser": false,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "0",
            "timeout": "0.0"
        },
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mysql.utf8mb4": true,
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "passman",
            "files_mindmap"
        ],
        "mail_sendmailmode": "smtp",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "MFA"
        ],
        "twofactor_enforced_excluded_groups": []
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.18.0
  - admin_audit: 1.16.0
  - announcementcenter: 6.5.1
  - bruteforcesettings: 2.6.0
  - circles: 26.0.0
  - cloud_federation_api: 1.9.0
  - comments: 1.16.0
  - contactsinteraction: 1.7.0
  - dav: 1.25.0
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_external: 1.18.0
  - files_mindmap: 0.0.27
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - firstrunwizard: 2.15.0
  - impersonate: 1.13.0
  - integration_openai: 1.0.7
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - nextcloud_announcements: 1.15.0
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - passman: 2.4.5
  - password_policy: 1.16.0
  - photos: 2.2.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - related_resources: 1.1.0-alpha1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - sharelisting: 1.1.1
  - support: 1.9.0
  - survey_client: 1.14.0
  - systemtags: 1.16.0
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - twofactor_email: 2.7.2
  - twofactor_totp: 8.0.0-alpha.0
  - updatenotification: 1.16.0
  - viewer: 1.10.0
  - workflowengine: 2.8.0
Disabled:
  - dashboard: 7.6.0 (installed 7.0.0)
  - encryption: 2.14.0
  - files_retention: 1.15.0 (installed 1.15.0)
  - groupfolders: 14.0.2 (installed 14.0.2)
  - imap_auth_aicr: 0.1.3 (installed 0.1.3)
  - passwords: 2023.5.30 (installed 2023.5.30)
  - recommendations: 1.5.0 (installed 1.3.0)
  - registration: 2.1.0 (installed 2.1.0)
  - suspicious_login: 4.4.0
  - user_external: 3.1.0 (installed 3.1.0)
  - user_ldap: 1.16.0
  - user_status: 1.6.0 (installed 1.4.0)
  - weather_status: 1.6.0 (installed 1.4.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by nimishavijay** [comment]
Good point! :) The button is not very eye catching. We can add a `+` icon and I would also suggest making the new user button a primary button like in Mail or Contacts, so it would follow the pattern for primary buttons in the navigation. 

![image](https://github.com/nextcloud/server/assets/52440189/43dac8a4-8738-43e8-875f-035068dba71e)

If a `+` icon is added to this button, we should also change the icon next to the `Add group` button to avoid duplicate icons. I suggest the [group add icon](https://fonts.google.com/icons?selected=Material%20Icons%20Round%3Agroup_add%3A) in MDI :)

**Comment by szaimen** [comment]
@mjmccarn would you be up for submitting a PR for this small improvment? Let me know if you need any help :)

**Comment by mjmccarn** [comment]
I can take a stab at it, but...

I found the file I think needs editing in github but I don't see it on my running server.

Do I need to setup a dev environment of some sort?

**Comment by szaimen** [comment]
> I can take a stab at it, but...
> 
> I found the file I think needs editing in github but I don't see it on my running server.

Editing the file on github and creating a PR should be enough for now. You could then use e.g. https://github.com/szaimen/nextcloud-easy-test to test it :)

> Do I need to setup a dev environment of some sort?

Not necessarily, but feel free to have a look at: https://help.nextcloud.com/t/tutorial-how-to-set-up-a-nextcloud-development-environment-on-mac-or-ubuntu/145462

**Comment by Siddhant-Kashyap** [comment]
can i go for this?

**Comment by szaimen** [comment]
> can i go for this?

yes, go ahead :)

**Comment by jancborchardt** [comment]
@Siddhant-Kashyap do you need any help there or do you have an update? If you want to go for it, you can just open a pull request. :)

**Comment by Siddhant-Kashyap** [comment]
yes @jancborchardt  i am going for it i am doing it . if I will be facing any challanges i will get back to you
