### ISSUE TITLE
Umlaute not displayed correctly

### ISSUE THREAD

**Issue by vortex1999** [nextcloud/server#38371]
### Steps To Reproduce

Fresh Install of the Hansson VM image, Umalute on web not displayed correctly.

### Expected Result

Umlaute showing properly

### Actual Result

![image](https://github.com/nextcloud/vm/assets/133097258/3ccb7d09-01c6-4dc4-8e39-ce2b16f91e10)

### Build Version

Nextcloud Hub 4 (26.0.1)

### Environment

By downloading the VM

**Comment by enoch85** [comment]
Moved it instead.

**Comment by joshtrichards** [comment]
Unable to reproduce today in >=28. Seems fixed.
