### ISSUE TITLE
Same issue on:

### ISSUE THREAD

**Issue by Hello-world29** [nextcloud/server#38387]
Same issue on:
Webserver nginx Version: 1.23.4
PHP Version: 8.1.18 / php8.1-fpm
Nextcloud Version: 26.0.1.1
Nextcloud Office App Version: 8.0.1
Recommendations App Version: 1.5.0
CODE Version: 22.05.13.1 (Docker)

Edit:
Opening from Dashboard fromt the recommended files works without issue. Maybe it's a Files issue? I already opened this same issue in the Nextcloud Office github as well, in case it is the implemenation of Office.

_Originally posted by @RuudschMaHinda in https://github.com/nextcloud/recommendations/issues/604#issuecomment-1529058994_

**Comment by szaimen** [comment]
Hi, please fill out the bug report template.
