### ISSUE TITLE
[Bug]: In the new groupfolder view, when trying to open a document you get redirected to home dir

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/server#38394]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In the new groupfolder entry in the left side menu, 
![image](https://github.com/nextcloud/server/assets/87175513/f74ff8ec-75b4-49d9-b22c-48b1ca8da04d)

Navigating into the groupfolders is fine.
However, when you try to open any document, you get redirected straight away to your homedir (All files view).

### Steps to reproduce

1. Go to groupfolder entry
2. NAvigate to e document
3. Try to open it

### Expected behavior

Document opens

### Installation method

None

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
c.nc.c v27
```

### Additional info

c.nc.c v27

**Comment by szaimen** [comment]
cc @skjnldsv

**Comment by skjnldsv** [comment]
I guess duplicates of https://github.com/nextcloud/groupfolders/issues/2402
We're not supposed to navigate to the groupfolders view but to redirect to the files view (until the full files2vue migration is done and we can leave the groupfolders view as is)
