### ISSUE TITLE
Improve support for offset in ldap searches

### ISSUE THREAD

**Issue by come-nc** [nextcloud/server#38417]
When searching for users in LDAP backend and using an offset, the LDAP backend uses a paged search, and loops until the offset if needed.
For this loop it uses the limit asked in the request as page size, I think because some server may not handle correctly switching page size in the middle of a paged search (would need to confirm that).

Because of that, using a big offset with a small page size will result in a ton of small searches.
`occ ldap:search --limit=2 --offset=100 ""` will do 50 requests, while `occ ldap:search --limit=10 --offset=100 ""` will do 10, and return faster despite having more data to fetch.
This is triggered by the disabled user list, because it loops through all users by pages of 25, searching for disabled users.

A request to offset 1925 on my test setup triggered an XDebug error because it was nesting more than 250 function calls.

Ideas for solutions:
- Use maximum (default) page size always and cut results after
- Use maximum page size until desired offset and target page size for final call (but is that supported?)
- Make sure to reuse paged searches cookies when multiple calls are done after one another (will not fix all but will help at least the disabled user list thing)
- For disabled user list, we should have an API endpoint to get this list that does the computing on server side and avoid this looping through all users in frontend

**Comment by blizzz** [comment]
> Use maximum (default) page size always and cut results after

Would find this OK on background actions, on frontend however, it depends. Faster replies are achieved with slower results sizes in general. For instance, responsiveness of share dialog results is much improved by setting `sharing.maxAutocompleteResults` to a low value like 5 in the config.php.  Going to page 78 of disabled users is rather an edge case.

> Use maximum page size until desired offset and target page size for final call (but is that supported?)

If this works reliable, as suggested by the RFC as seen on the side, this seems favourable.

> Make sure to reuse paged searches cookies when multiple calls are done after one another (will not fix all but will help at least the disabled user list thing)

This should be the case already – within handling a request. It does not work across requests and connections.

> For disabled user list, we should have an API endpoint to get this list that does the computing on server side and avoid this looping through all users in frontend

For reasons I see websockets everywhere currently, in combined with the upper point you could keep the state (connections timeouts might be a killer though - should recover, but the paged results "session" may get lost). Generally, again this sounds like an edge case. Normal behaviour would be to search for a user, not scroll across 80 pages and more.

**Comment by come-nc** [comment]
You misunderstood the situation for the disabled user list. I am not scrolling any page, I cannot get a single result.
This is because to get disabled users, it gets all users and search for disabled ones.
Because on my setup there is only one disabled user (and it’s not in the first pages), it browse through all pages without me touching anything, the frontend just shows a never-ending loading icon.

**Comment by blizzz** [comment]
> You misunderstood the situation for the disabled user list. I am not scrolling any page, I cannot get a single result.
This is because to get disabled users, it gets all users and search for disabled ones.

Oops. Yeah, misunderstand, and didn't expect this. That also calls for optimization.
