### ISSUE TITLE
[Bug]: IMAP Server is no reachable

### ISSUE THREAD

**Issue by GVA-Guillaume** [nextcloud/server#38410]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

<img width="308" alt="Capture d’écran 2023-05-23 à 09 33 22" src="https://github.com/nextcloud/server/assets/128600399/8ae04045-02fe-46c0-a109-7b5fe3f64359">

### Steps to reproduce

1. To fill the credentials information in the new mail settings

### Expected behavior

connection and authentication succeed

### Installation method

None

### Nextcloud Server version

24

### Operating system

None

### PHP engine version

PHP 8.1

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "home.fastendclear.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "26.0.1.1",
        "overwrite.cli.url": "http:\/\/home.fastendclear.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "app.mail.transport": "php-mail",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.18.0
  - admin_audit: 1.16.0
  - appointments: 1.15.1
  - bruteforcesettings: 2.6.0
  - calendar: 4.3.4
  - circles: 26.0.0
  - cloud_federation_api: 1.9.0
  - comments: 1.16.0
  - contacts: 5.2.0
  - contactsinteraction: 1.7.0
  - dashboard: 7.6.0
  - dav: 1.25.0
  - encryption: 2.14.0
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_external: 1.18.0
  - files_pdfviewer: 2.7.0
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - firstrunwizard: 2.15.0
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - mail: 3.1.1
  - nextcloud_announcements: 1.15.0
  - notes: 4.7.2
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - password_policy: 1.16.0
  - photos: 2.2.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0-alpha1
  - richdocuments: 8.0.2
  - richdocumentscode: 22.5.1301
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - spreed: 16.0.3
  - support: 1.9.0
  - survey_client: 1.14.0
  - suspicious_login: 4.4.0
  - systemtags: 1.16.0
  - text: 3.7.2
  - theming: 2.1.1
  - twofactor_backupcodes: 1.15.0
  - twofactor_totp: 8.0.0-alpha.0
  - updatenotification: 1.16.0
  - user_ldap: 1.16.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Warning	suspicious_login	Could not predict suspiciousness: No models found		2023-05-23T09:16:23+0200
Warning	suspicious_login	Could not predict suspiciousness: No models found		2023-05-22T14:30:20+0200
Warning	no app in context	Invalid microsoft_oauth_client_id data provided to provideInitialState by mail		2023-05-22T14:15:50+0200
Warning	no app in context	Invalid google_oauth_client_id data provided to provideInitialState by mail		2023-05-22T14:15:50+0200
Warning	user_ldap	Configuration Error (prefix s01): login filter does not contain %uid place holder.		2023-05-22T14:15:45+0200
Warning	user_ldap	Configuration Error (prefix s01): Not a single Base DN given.		2023-05-22T14:15:45+0200
Warning	user_ldap	Configuration Error (prefix s01): No LDAP Port given!		2023-05-22T14:15:45+0200
Warning	user_ldap	Configuration Error (prefix s01): No LDAP Login Filter given!		2023-05-22T14:15:45+0200
Warning	user_ldap	Configuration Error (prefix s01): No LDAP Host given!		2023-05-22T14:15:45+0200
Warning	user_ldap	Configuration Error (prefix s01): login filter does not contain %uid place holder.		2023-05-22T14:15:33+0200
Warning	user_ldap	Configuration Error (prefix s01): Not a single Base DN given.		2023-05-22T14:15:33+0200
Warning	user_ldap	Configuration Error (prefix s01): No LDAP Port given!		2023-05-22T14:15:33+0200
Warning	user_ldap	Configuration Error (prefix s01): No LDAP Login Filter given!		2023-05-22T14:15:33+0200
Warning	user_ldap	Configuration Error (prefix s01): No LDAP Host given!		2023-05-22T14:15:33+0200
Error	no app in context	OCP\Lock\LockedException: "encryption-generateMasterKey"("Encryption: master key generation") is locked, existing lock on file: exclusive		2023-05-22T14:15:02+0200
Warning	no app in context	Invalid microsoft_oauth_client_id data provided to provideInitialState by mail		2023-05-22T14:14:00+0200
Warning	no app in context	Invalid google_oauth_client_id data provided to provideInitialState by mail		2023-05-22T14:14:00+0200
Error	PHP	OCP\HintException: Configuration was not read or initialized correctly, not overwriting /var/www/html/config/config.php at /var/www/html/lib/private/Config.php#266		2023-05-22T10:37:57+0200
Error	PHP	OCP\HintException: Configuration was not read or initialized correctly, not overwriting /var/www/html/config/config.php at /var/www/html/lib/private/Config.php#266		2023-05-22T10:37:57+0200
```

### Additional info

openssl -connect imap.example.com:993
Invalid command '-connect'; type "help" for a list.
ubuntu@ns31051758:~/76671615101115/html/config$ openssl s_client -connect imap.kapdome.com:993
CONNECTED(00000003)
depth=2 C = US, O = (STAGING) Internet Security Research Group, CN = (STAGING) Pretend Pear X1
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=1 C = US, O = (STAGING) Let's Encrypt, CN = (STAGING) Artificial Apricot R3
verify return:1
depth=0 CN = mail.kapdome.com
verify return:1
---
Certificate chain
 0 s:CN = mail.kapdome.com
   i:C = US, O = (STAGING) Let's Encrypt, CN = (STAGING) Artificial Apricot R3
   a:PKEY: rsaEncryption, 4096 (bit); sigalg: RSA-SHA256
   v:NotBefore: May 19 08:44:05 2023 GMT; NotAfter: Aug 17 08:44:04 2023 GMT
 1 s:C = US, O = (STAGING) Let's Encrypt, CN = (STAGING) Artificial Apricot R3
   i:C = US, O = (STAGING) Internet Security Research Group, CN = (STAGING) Pretend Pear X1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep  4 00:00:00 2020 GMT; NotAfter: Sep 15 16:00:00 2025 GMT
 2 s:C = US, O = (STAGING) Internet Security Research Group, CN = (STAGING) Pretend Pear X1
   i:C = US, O = (STAGING) Internet Security Research Group, CN = (STAGING) Doctored Durian Root CA X3
   a:PKEY: rsaEncryption, 4096 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jan 20 19:14:03 2021 GMT; NotAfter: Sep 30 18:14:03 2024 GMT
---
Server certificate
-----BEGIN CERTIFICATE-----
....
-----END CERTIFICATE-----
subject=CN = mail.kapdome.com
issuer=C = US, O = (STAGING) Let's Encrypt, CN = (STAGING) Artificial Apricot R3
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 5483 bytes and written 398 bytes
Verification error: unable to get local issuer certificate
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 4096 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 20 (unable to get local issuer certificate)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 98EAFAA5EC6291453A09C9B2C69906E3F4565B6A92A5809BCB2091AC0381892B
    Session-ID-ctx: 
    Resumption PSK: 71B69C49D00CF92E68706389CC82E37E728774C1FE267A0930F4D4D2A2359F98227EF6B9B45FC3B875A9320D9E2283E2
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 21 94 5d c8 36 5d 08 d9-20 55 e1 36 4f b6 fc 7a   !.].6].. U.6O..z
    0010 - 7c e3 9a 8e 83 7d d9 87-51 ac e0 80 08 4b 0c 20   |....}..Q....K. 

    Start Time: 1684826802
    Timeout   : 7200 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_256_GCM_SHA384
    Session-ID: 20EFDC1C1BEF1B2C2733D79E690E0C424BA23777260AC95212F73EF0EA3CE097
    Session-ID-ctx: 
    Resumption PSK: 36582D98E8862E9657DB713BB432509EED9B063C6BC75055D01461CEB9440B96533538F96EFED73BD762F45FB20C1E96
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 7c b0 22 d3 93 71 2d e6-45 d5 44 b3 48 05 64 5b   |."..q-.E.D.H.d[
    0010 - 04 ee e4 fa bf df 60 0f-89 a4 a6 8c c7 e7 13 b5   ......`.........

    Start Time: 1684826802
    Timeout   : 7200 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN AUTH=LOGIN] Dovecot ready.

**Comment by solracsf** [comment]
Reach out the forums for setup issues please:
https://help.nextcloud.com/t/cant-send-mails-via-nextcloud-basic-settings/160440/4
