### ISSUE TITLE
[Bug]: Time not correct in activity mail sent by nextcloud (25.0.6)

### ISSUE THREAD

**Issue by mathsyx-fr** [nextcloud/server#38422]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hell everyone,

I have a bug with the time of the activities sent by mail.
I already report this bug but when I have open the issue my nextcloud isn't up to date so my issue Has been close #36410 .

Today I have update my nextcloud instance from 24.0.7 to 24.0.12 to 25.0.6 and the bug is still here. 
I also upgrade my php-fpm and modules from 8.0 to 8.1 .

Since execution time of last cron isn't displayed in interface like nextcloud 24.X, the bug now impact only the time in activities mails.

There is 2 hour (minus "-2") difference with the real time in my country (France).

I have configured the time zone in the nextcloud settings... (Europe/Paris)

The time is correct in the activities section : 
![image](https://github.com/nextcloud/server/assets/65737224/5e9f4759-df9a-416e-9feb-3c3a6175c1d5)

above a pic of the bug in mail sent for activities :

![image](https://github.com/nextcloud/server/assets/65737224/f6932118-2b4f-4788-b5ae-333f37234cad)

Thank by advance for your help / suggestions.

### Steps to reproduce

1.Read activities mail sent by nextcloud (verify receive date and time indicated for the activity) compare it with the time indicate in actvity sections in nextcloud web client

### Expected behavior

I expect the time to be the same in activities mail and the activity section in nextcloud.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated to a major version (ex. 22.2.3 to 23.0.1)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***\/",
        "htaccess.RewriteBase": "\/",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "25.0.6.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "templatedirectory": "",
        "skeletondirectory": "",
        "trashbin_retention_obligation": "7, 8",
        "defaultapp": "files",
        "logtimezone": "Europe\/Paris",
        "default_language": "fr",
        "default_locale": "fr_FR",
        "default_phone_region": "FR",
        "activity_expire_days": "30",
        "allow_user_to_change_display_name": false,
        "lost_password_link": "disabled",
        "oidc_login_provider_url": "***REMOVED SENSITIVE VALUE***",
        "oidc_login_client_id": "***REMOVED SENSITIVE VALUE***",
        "oidc_login_client_secret": "***REMOVED SENSITIVE VALUE***",
        "oidc_login_auto_redirect": false,
        "oidc_login_logout_url": "https:\/\/***REMOVED SENSITIVE VALUE***\/",
        "oidc_login_end_session_redirect": false,
        "oidc_login_button_text": "Connexion avec M365 (***REMOVED SENSITIVE VALUE***)",
        "oidc_login_hide_password_form": true,
        "oidc_login_use_id_token": false,
        "oidc_login_attributes": {
            "name": "name",
            "mail": "email",
            "id": "email"
        },
        "oidc_login_default_group": "utilisateurs-openid",
        "oidc_login_use_external_storage": false,
        "oidc_login_scope": "openid profile",
        "oidc_login_proxy_ldap": false,
        "oidc_login_disable_registration": false,
        "oidc_login_redir_fallback": false,
        "oidc_login_tls_verify": true,
        "oidc_create_groups": false,
        "oidc_login_webdav_enabled": false,
        "oidc_login_password_authentication": false,
        "oidc_login_public_key_caching_time": 86400,
        "oidc_login_min_time_between_jwks_requests": 10,
        "oidc_login_well_known_caching_time": 86400,
        "oidc_login_update_avatar": false,
        "maintenance": false,
        "theme": "",
        "loglevel": 1,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "simpleSignUpLink.shown": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.17.0
  - admin_audit: 1.15.0
  - bruteforcesettings: 2.5.0
  - circles: 25.0.0
  - cloud_federation_api: 1.8.0
  - comments: 1.15.0
  - contactsinteraction: 1.6.0
  - dashboard: 7.5.0
  - dav: 1.24.0
  - federatedfilesharing: 1.15.0
  - federation: 1.15.0
  - files: 1.20.1
  - files_accesscontrol: 1.15.1
  - files_antivirus: 5.0.0
  - files_automatedtagging: 1.15.3
  - files_downloadactivity: 1.16.0
  - files_pdfviewer: 2.6.0
  - files_retention: 1.14.1
  - files_rightclick: 1.4.0
  - files_sharing: 1.17.0
  - files_trashbin: 1.15.0
  - files_versions: 1.18.0
  - firstrunwizard: 2.14.0
  - impersonate: 1.12.1
  - logreader: 2.10.0
  - lookup_server_connector: 1.13.0
  - nextcloud_announcements: 1.14.0
  - notifications: 2.13.1
  - oauth2: 1.13.0
  - oidc_login: 2.5.1
  - password_policy: 1.15.0
  - photos: 2.0.1
  - privacy: 1.9.0
  - provisioning_api: 1.15.0
  - quota_warning: 1.17.0
  - recommendations: 1.4.0
  - related_resources: 1.0.4
  - serverinfo: 1.15.0
  - settings: 1.7.0
  - support: 1.8.0
  - survey_client: 1.13.0
  - systemtags: 1.15.0
  - text: 3.6.0
  - theming: 2.0.1
  - theming_customcss: 1.14.0
  - twofactor_backupcodes: 1.14.0
  - updatenotification: 1.15.0
  - user_usage_report: 1.10.0
  - viewer: 1.9.0
  - workflowengine: 2.7.0
Disabled:
  - encryption
  - files_external
  - sharebymail: 1.14.0
  - suspicious_login
  - twofactor_totp
  - user_ldap
  - user_status: 1.4.0
  - weather_status: 1.4.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
logs too long
```

### Additional info

Debian 5.10.179-1 (2023-05-12)

![image](https://github.com/nextcloud/server/assets/65737224/d6a80b19-352a-4c42-94e2-c88c552b5491)
![image](https://github.com/nextcloud/server/assets/65737224/4750e5bb-1a27-48bc-a15c-415332fafa14)

**Comment by solracsf** [comment]
I don't understand you report; in your Outlook screeenshot, the 1st date (at the top right) is the date when you received the email. The date at the bottom center, is the date at wich someone has downloaded the file; it is perfectly normal if those dates are different.

When you go to `/settings/user/notifications` you can set when to receive those emails (at the bottom).

**Comment by mathsyx-fr** [comment]
> I don't fully understand your report; in your Outlook screeenshot, the 1st date (at the top right) is the date when you received the email. The date at the bottom center, is the date at wich someone has downloaded the file; it is perfectly normal if those dates are different.
> 
> When you go to `/settings/user/notifications` you can set when to receive those emails (at the bottom).

I my screen you can see the time of the activity in nextcloud interface on top and on the mail this the same time minus 2 hours. I mark the mail receive time to highlight my problem with activity timestamps.

**Comment by solracsf** [comment]
Ok but this is a setup problem, somewhere, not a bug.
Seek for help fixing this at https://help.nextcloud.com

Activity tab:

![image](https://github.com/nextcloud/server/assets/12234510/9eca614c-e8df-4a47-a7a4-79874a6d64ba)

and email:

![image](https://github.com/nextcloud/server/assets/12234510/d2107852-2588-4a50-ae8b-122dff17006c)

**Comment by joshtrichards** [comment]
@mathsyx-fr I was going to respond to this over in the forum, but I don't see a post from you over there. 

What's in the db for your profile?

https://help.nextcloud.com/t/activity-timestamp-wrong-in-mail-notification/5818/2

**Comment by mathsyx-fr** [comment]
> @mathsyx-fr I was going to respond to this over in the forum, but I don't see a post from you over there.
> 
> What's in the db for your profile?
> 
> https://help.nextcloud.com/t/activity-timestamp-wrong-in-mail-notification/5818/2

Thank for yout help, link of my post on nextcloud forum : 
https://help.nextcloud.com/t/nextcloud-25-0-6-time-not-correct-in-activity-mail-sent-by-nextcloud/162738

For the database in my profile, I don't understand what you're talking about. 
However, my nextcloud instance use mariadb 10.5.19.

**Comment by mathsyx-fr** [comment]
> > @mathsyx-fr I was going to respond to this over in the forum, but I don't see a post from you over there.
> > What's in the db for your profile?
> > https://help.nextcloud.com/t/activity-timestamp-wrong-in-mail-notification/5818/2
> 
> Thank for your help, above the link of my post on nextcloud forum : https://help.nextcloud.com/t/nextcloud-25-0-6-time-not-correct-in-activity-mail-sent-by-nextcloud/162738
> 
> I don't know which sql query I have to use to have this info... Could you help for that ? However, my nextcloud instance use mariadb 10.5.19.

I don't have any timezone related entry for my user... I have the same bug as the post 5818 of the nextcloud forum, could be related that I use an alternative login provider : 
[nextcloud-oidc-login](https://github.com/pulsejet/nextcloud-oidc-login)

My local admin user creates at isntall as the entry for the timezone.

**Comment by davtheultimate** [comment]
I have the same problem. 
All my users from AD sync does not have the timezone set in table oc_preferences ....
And admin local has it.

i use also the same oidc apps. so we use an alternate login and i understand that the standard login is the way to save timezone at login session. 
https://github.com/nextcloud/server/issues/2560

we use this option to do not display the login form :  'oidc_login_auto_redirect' => true,

so i suppose this issue must be reported to [nextcloud-oidc-login](https://github.com/pulsejet/nextcloud-oidc-login)

**Comment by davtheultimate** [comment]
I use this trigger on my MariaDB's DATABASE 

DELIMITER $$
CREATE TRIGGER addtimezone AFTER INSERT ON oc_ldap_user_mapping FOR EACH ROW
BEGIN
IF NOT EXISTS (SELECT 1 FROM oc_preferences WHERE userid = NEW.owncloud_name and configkey ='timezone') THEN
    INSERT INTO oc_preferences VALUES (NEW.owncloud_name,'core','timezone','Europe/Paris');
END IF;
END $$
DELIMITER ;
