### ISSUE TITLE
Swedish sv.js and sv.json for apps not getting updated from Transifex ?

### ISSUE THREAD

**Issue by poisony** [nextcloud/server#3845]
### Steps to reproduce
1. Download latest release of NextCloud 11.0.2 and install
2. Check sv.js and sv.json on most of the apps etc

### Expected behaviour
Daily updated Transifex translations doesnt work for the Swedish language. They are not up to date with the Transifex ones.

### Actual behaviour
It seems that many of the Swedish (sv.js and sv.json) files are not recently updated even tho I have translated them on Transifex and reviewed them, they are not getting updated. They have not been updated for 2 months. The apps I have seen so far not getting updated are the "activity app" and the "mail app" and also a some of the core translation. 

Edited: "File access control", "Theming", "Server info," from the Admin backend are also not getting updated to the latest translations from Transifex.

"Nextcloud announcements" app are not updated to latest translations.

"File retention" app are not updated to latest translations.

"Password policy" on the admin backend are not updated to latest translations.

I guess there are even more. Those are the ones I found right now.

I have manually translated the sv.js and sv.json files for myself but the reason with translating on Transifex is because I want to help others aswell.

### Server configuration
**Operating system**:
Win12 Server HyperV
**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
11.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
Nextcloud.com and techandme.com
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by rullzer** [comment]
Summoning @MorrisJobke our transifex wizzard!

**Comment by MorrisJobke** [comment]
Please check again with 11.0.4 - it was last updated for the activity app and stable11 on 2017-06-04: https://github.com/nextcloud/activity/blob/stable11/l10n/sv.js
