### ISSUE TITLE
User account is locked when enabling apps

### ISSUE THREAD

**Issue by ritchiewilson** [nextcloud/server#3846]
When I try to enable an app, Nextcloud freezes on me until the app is enabled. Normally that happens quickly and I've never noticed. But the Weather app is about 18Mb, and the download from the app store was extremely slow, so that download took a few minutes. During that time, I couldn't navigate away from the apps page, and if I opened a new tab to open a different Nextcloud page, that new tab also wouldn't load until the Weather app was fully downloaded and enabled.

This appears that only the account that is enabling the app is frozen for a while, though. So I could open an incognito window where I wasn't logged in, and there the Nextcloud login page loaded normally, even during those few minutes it took for the Weather app to download and install.

### Steps to reproduce
1. In an Nextcloud installation, click to enable an app that must be downloaded from the app store
2. While that app is downloading, try navigating away from that page, or open a new nextcloud tab in which you are still logged in
3.

### Expected behaviour
The new tab should open to the expected page

### Actual behaviour
The new tab remains empty and trying to connect to the serer until the app is fully downloaded and enabled.

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Apache
**Database:**
Mysql
**PHP version:**
7.0.15
**Nextcloud version:** (see Nextcloud admin page)
11.02
**Updated from an older Nextcloud/ownCloud or fresh install:**
Continuously upgraded since ~OC 6..?
**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors have been found.
```
</details>

**Comment by MariusBluem** [comment]
Well ... Weather is a more than huge app - this is because of all these pictures it ships 😒
I've opened a issue for that over there: https://github.com/nextcloud/weather/issues/28

I don't think it is really necessary to rethink the app installing process here, because the other apps are installed fast enough ... 🤔

**Comment by nickvergessen** [comment]
Hmm I guess it is because the session is still open, and can therefor not be used by a different tab/window.

@LukasReschke any idea?

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
