### ISSUE TITLE
Enhancement for public accessible core-common.js

### ISSUE THREAD

**Issue by technout** [nextcloud/server#38502]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Problem description**
Because of the large file size of 13,5 MB (/dist/core-common.js), this file should only be requested by logged in clients.
But first a big thank you for this great product and hard work of the Nextcloud team!

When i check the bandwidth statistics for this specific file on my Nextcloud server (for a period of 6 weeks when no shares were open and all users were temporary blocked) -  i noticed a very high bandwidth usage, specific from request to this file. This costs hundreds of megabytes a day! Maybe by some search engine crawlers, or botnets?

**Describe the solution you'd like**
I try to maintain a low bandwidth profile on my servers. When this 13,5 MB library is only requested by logged in clients, there will be less bandwidth used and the server will use less energy over the long run.

**Additional context**
My current Nextcloud version: 25.0.6
Operating system and version: Ubuntu 22.04
Apache or nginx version: Apache 2.4.25
PHP version: 8.0

I noticed this pull request for version 28: Optimize webpack chunking - https://github.com/nextcloud/server/pull/38329
This can be an enhancement for Nextcloud 29?

**Comment by kesselb** [comment]
Thanks for your feature request :+1: 

dist/core-common.js is 1,4mb on Nextcloud 28.
