### ISSUE TITLE
feature-policy header should be replaced with permissions-policy

### ISSUE THREAD

**Issue by andrey18106** [nextcloud/server#38515]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
It's a future thing to be updated: feature-policy [renamed](https://scotthelme.co.uk/goodbye-feature-policy-and-hello-permissions-policy/) to permission-policy.

**Describe the solution you'd like**
feature-policy header renamed to permissions policy

**Describe alternatives you've considered**

**Additional context**

**Comment by joshtrichards** [comment]
Context:

https://developer.chrome.com/en/docs/privacy-sandbox/permissions-policy/#changes-to-permissions-policy
https://developer.mozilla.org/en-US/docs/Web/HTTP/Permissions_Policy

Migrating:

https://developer.chrome.com/en/docs/privacy-sandbox/permissions-policy/#migration-from-feature-policy

**Comment by kesselb** [comment]
Existing issues:
https://github.com/nextcloud/server/issues/22792
https://github.com/nextcloud/server/issues/32607

Stale pull request: https://github.com/nextcloud/server/pull/23825
