### ISSUE TITLE
Data corruption when uploading files bigger than Maximum upload size (which is also not honored correctly)

### ISSUE THREAD

**Issue by clohrmann** [nextcloud/server#3852]
### Steps to reproduce
1. Nextcloud 11.0.2 (stable). Max filesize in "Additional Settings - Maximum Upload size" is set to 500 MB.
2. Upload file bigger than 500MB
3. Download file...compare against original

### Expected behaviour
- shouldn't be allowed to upload file bigger than 500MB
- Downloaded file is identical to uploaded file

### Actual behaviour
- NC allows me to upload bigger files...which doesn't make sense, since I limit it on purpose to 500MB

- Webinterface shows me again 511MB after page reload, even though I just updated it with a different value. I did confirm that .htaccess does get properly updated with new values.

- SEVERE: files bigger than configured max limit get corrupted. Files smaller survive without problems.
- No warning/blocking of anything...users therefore experience silent corruption.

- effected files can't be deleted on NC server afterwards, because file-lock is still active. Have to remove lock from database to make them deletable again.

### Server configuration
**Operating system**:
Linux - unknown details...hosting provider
**Web server:**
unknown...presumably apache
**Database:**
MySQL 5.5.54
**PHP version:**
5.6.30
**Nextcloud version:** (see Nextcloud admin page)
11.0.2 (stable)
Encryption and home folder encryption ENABLED

**Updated from an older Nextcloud/ownCloud or fresh install:**
Yes...updated from first Nextcloud install ever released (upgraded twice since then)...can't remember for sure, but might have been 9.x.something...it was the first "relabled" release around the same time the interview in the FLOSS weekly podcast was given.

**Where did you install Nextcloud from:**
Official site/script

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
None

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder:

No command line available
</details>

**The content of config/config.php:**
<details>
<?php
$CONFIG = array (
  'instanceid' => 'redacted',
  'passwordsalt' => 'redacted',
  'secret' => 'redacted',
  'trusted_domains' => 
  array (
    0 => 'redacted',
  ),
  'datadirectory' => '/usr/www/users/redacted/subdomainredacted/data',
  'overwrite.cli.url' => 'https://share.redacted.eu',
  'dbtype' => 'mysql',
  'version' => '11.0.2.7',
  'dbname' => 'redacted',
  'dbhost' => 'redacted',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'redacted',
  'dbpassword' => 'redacted',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_from_address' => 'redacted',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'redacted',
  'trashbin_retention_obligation' => '1,2',
  'loglevel' => 4,
  'theme' => '',
  'maintenance' => false,
  'updater.release.channel' => 'stable',
);
<summary>Config report</summary>
</details>

**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 52...but also applies to various other browsers.
**Operating system:**
various...doesn't effect the problem
</details>

</details>

**Comment by nickvergessen** [comment]
Just a quick comment
> shouldn't be allowed to upload file bigger than 500MB

No, that is not what the option is for. Basically that option is for "when should the file be uploaded in multiple junks instead of one blob".


> effected files can't be deleted on NC server afterwards, because file-lock is still active. Have to remove lock from database to make them deletable again.

You could also wait 1hour, that's the default length of the locks.

**Comment by clohrmann** [comment]
> No, that is not what the option is for. Basically that option is for "when should the file be uploaded in multiple junks instead of one blob".

Then the description/label is miss-leading in my opinion. It clearly states "Maximum upload size". How NC handles it in the background, is invisible to me/the user/the admin.
Also as admin I would like to be able to limit max. upload size and if a user tries to upload more than the defined size, I would expect a warning/denial message before the upload even starts. Both seems not to work in my case; for whatever reason. Even worse, the data gets corrupted without any error/notification shown.

The relevant section in my .htaccess file (as updated by NC) look as follows:
PHP5
  php_value upload_max_filesize 500M
  php_value post_max_size 500M
  php_value memory_limit 512M
  php_value mbstring.func_overload 0
  php_value always_populate_raw_post_data -1
  php_value default_charset 'UTF-8'
  php_value output_buffering 0

I am in the position where my available disk-space is limited and I need to enforce some kind of total quotas and filesize max-limits to the users.

> You could also wait 1hour, that's the default length of the locks.

Good to know. Thanks.

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
