### ISSUE TITLE
"Resharing is not allowed" for LDAP users

### ISSUE THREAD

**Issue by Vshmuk** [nextcloud/server#3854]
### Steps to reproduce
1. Turn on LDAP/AD integration
2. Configure the server, press "Verify settings and count users"
3. Log in as any LDAP user
4. Click on a "Share" link for any file or directory.
5. "Resharing is not allowed" is written in sidebar.

### Expected behaviour
Sharing by link

### Actual behaviour
"Resharing is not allowed" is written, and no more

### Server configuration
**Operating system**: CentOS release 6.8 (Final)

**Web server:** nginx version: nginx/1.10.2 

**Database:**mysql  Ver 14.14 Distrib 5.5.54, for Linux (x86_64) using readline 5.1

**PHP version:**php-fpm v 5.6

**Nextcloud version:** 11.0.2 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** 11.0.1 (had the same issue)

**Where did you install Nextcloud from:** --

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - activitylog: 0.0.1
  - admin_audit: 1.1.0
  - admin_notifications: 1.0.0
  - apporder: 0.3.3
  - comments: 1.1.0
  - dav: 1.1.1
  - direct_menu: 0.10.0
  - federatedfilesharing: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_downloadactivity: 1.0.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.2
  - workflowengine: 1.1.1
Disabled:
  - documents
  - encryption
  - external
  - federation
  - files_automatedtagging
  - files_external
  - files_markdown
  - files_retention
  - mail
  - notes
  - ownbackup
  - ownnote
  - sharebymail
  - survey_client
  - tasks
  - templateeditor
  - user_external
  - user_saml

```
</details>

...Skipped...
See below

**Comment by Vshmuk** [comment]
Okay, I've found a reason.
In my config.php i have an additional string
```
putenv('LDAPTLS_CACERT=./config/dap.crt');
```
to connect to our LDAP server using SSL.

Somewhy this 'setenv' is ignored in the sharing module, leading the Nextcloud to fail the connection to LDAP.
So, my next question is, where should i put the variable LDAPTLS_CACERT?

Maybe a feature-request?

**Comment by blizzz** [comment]
>  So, my next question is, where should i put the variable LDAPTLS_CACERT?

*/etc/ldap/ldap.conf* (might be called differently on different distributions), c.f https://docs.nextcloud.com/server/14/admin_manual/configuration_user/user_auth_ldap.html#ssl-certificate-verification-ldaps-tls
