### ISSUE TITLE
Personal settings icons missing

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#3859]
- External storage
- SSL Root Certificates

<img width="236" alt="bildschirmfoto 2017-03-16 um 11 39 02" src="https://cloud.githubusercontent.com/assets/19711361/23992478/656cadaa-0a3d-11e7-9eae-04e8536a5fc9.png">

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
@MariusBluem for »External storage« you can use icon-external (that the app should also have). For SSL Root Certificates you can use the same icon as for Second-factor backup codes. Time to prepare a nice small pull request? :)

**Comment by MariusBluem** [comment]
@jancborchardt Have unfortunately no reference for personal settings here 😁 ... admin settings would be no problem 😝

**Comment by MorrisJobke** [comment]
@nickvergessen is this the same as you noticed that the id is the l10n version of the app id?

**Comment by nickvergessen** [comment]
I guess its related

**Comment by MorrisJobke** [comment]
Duplicate of #4170
