### ISSUE TITLE
Create specific authentication page for admins on a different port for added security on a wan situation.

### ISSUE THREAD

**Issue by astrometrics** [nextcloud/server#38609]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

Admins can log on on wan... that's a bit problematic.

**Describe the solution you'd like**

Separation of login pages from normal users and admins. Admins would log on to a different port, which could be better managed by firewalls, increasing security greatly I think. This solution may have an appeal to organizations or anyone really focused on security.
That should be easy as an admin config or config.php admin port setting. If admin_port is omitted then same port as normal user is used.

**Describe alternatives you've considered**

**Additional context**

**Comment by astrometrics** [comment]
@joshtrichards, thanks for your answer. The File Access Control app doesn't seem to do more than file access control inside NC but I suspect that with some tinkering some Admin based control can be achieved... That's good but what I'm proposing is a way to improve security in conjunction to firewalls etc (out of NC); the result of that is a reduction of the surface of attack which is someone by any means to have gotten the password and even TOTP seed by some other mean than a net attack. That way a type of attack that has huge impact couldn't really happen because the admin page just won't be available.  The other mentioned hardenings like MFA, IP restrictions can be applied to unprivileged users too. But I think a different port is more useful to be managed by firewalls (not by NC). But I understand the general problem of attack surface and if there's some basic unsuspected flaw happens, all that rigor may me in vain... as always.

Keep the coffee coming!

**Comment by joshtrichards** [comment]
Potentially related and/or a duplicate of #29294

**Comment by joshtrichards** [comment]
Possible of interest: #46473

**Comment by joshtrichards** [comment]
Fixed in #46473
Documented in nextcloud/documentation#12059
