### ISSUE TITLE
allow restriction of external storage to users using two factor authentication

### ISSUE THREAD

**Issue by ArnY** [nextcloud/server#3861]
To enforce a better security of the users data it could be very interesting to restrict access to external storage mounts to users with two factor authentication either on a per mount basis or globally. 

Users would need to have two factor authentication enabled to add external storages but if they disable it afterward the external storage wouldn't be mounted.

This would allow companies to let users add mounts to their company file servers without compromising the security of the data that is usually only accessible from inside their network.

**Comment by MariusBluem** [comment]
Maybe an addition for https://github.com/nextcloud/server/issues/2348 🤔

**Comment by ChristophWurst** [comment]
I'd suggest to close this in favor of https://github.com/orgs/nextcloud/projects/17, esp #11455.
