### ISSUE TITLE
Expose `Node::getFileInfo()` in public API

### ISSUE THREAD

**Issue by mejo-** [nextcloud/server#38647]
[`Node::getFileInfo()`](https://github.com/nextcloud/server/blob/2e111e862fa1835b841a68637454b1cb9e47ba70/lib/private/Files/Node/Node.php#L105) would be useful to expose in [public `Files/Node` API](https://github.com/nextcloud/server/blob/master/lib/public/Files/Node.php).

E.g. we use it in Collectives: https://github.com/nextcloud/collectives/blob/9e4bc540ba6c6592599bd7b54ffc83b82f4dc116/lib/Trash/PageTrashBackend.php#L480

Any objections @nextcloud/server-backend? I could open a pull request.

Also Cc @blizzz.

**Comment by come-nc** [comment]
But the Node itself already implements the FileInfo interface, no?

**Comment by mejo-** [comment]
It does, but `getFileInfo()` is not exposed in the FileInfo interface either. Maybe I'm overseing something, but how can I get the FileInfo of a Node via public API? :thinking:

**Comment by mejo-** [comment]
I have to pass the fileInfo structure to `CollectivePageTrashItem()`, see

https://github.com/nextcloud/collectives/blob/9e4bc540ba6c6592599bd7b54ffc83b82f4dc116/lib/Trash/CollectivePageTrashItem.php#L18

and

https://github.com/nextcloud/server/blob/ffa30ce89bcfa051a040d61250da1f7290e2dfc7/apps/files_trashbin/lib/Trash/TrashItem.php#L47

**Comment by mejo-** [comment]
Sorry, you're right, I was utterly confused :see_no_evil:

I can just pass `$item` instead of `$item->getFileInfo()`. Sorry for the noise.

**Comment by mejo-** [comment]
Ah damn, I can not. Because I have to overwrite `FileInfo::$name` first :cry:

**Comment by come-nc** [comment]
`OCP\Files\FileInfo` does not extend ArrayAccess, and has no setName method, so you are actually depending on `OC\Files\FileInfo` here.
I think this is not the only place where there is this, I’ve seen it in other places. I’d prefer a cleanup than adding a hack on top.

Looking into it the other applications depending on `OC\Files\FileInfo` do so for creating a new one. Not sure how to provide that cleanly in OCP, maybe with a factory.

But for your case of altering the name I’m not sure.
Something like this would work but not really pretty:
```
class RenamedFileInfo implements \OCP\Files\FileInfo {
	public function __construct(
		private FileInfo $wrappedFileInfo,
		private string $newName,
	) {
	}
	
	public function getName() {
		return $this->name;
	}
	
	/* pass all other calls to wrappedFileInfo, either through __call or real methods */
}
```
