### ISSUE TITLE
Timeout after 60 seconds on the web and the desktop client

### ISSUE THREAD

**Issue by ulfklose** [nextcloud/server#3864]
### Steps to reproduce
1. Trying to playback a video file results in a timeout after 60 seconds.
2. Trying to download a video file results in a timeout after 60 seconds

### Expected behaviour
The video files should be playable and downloadable. 

### Actual behaviour
I'm on a low bandwidth connection sometimes. I tried to playback two video files, one is around 50 MB, the other one around 440 MB. I shared both files using a link. Trying to play them back results in a timeout after precisely 60 seconds. The same counts for downloading the file. After 60 seconds the download stops.

Trying to sync these files using the ownCloud client 2.3.0 on macOS results in an error as well.

It looks to me like a web server configuration error but I can't find any timeout related parameters in my configuration which are set to 60 seconds. I'm using PHP5-FPM by the way.

### Server configuration
**Operating system**:
Debian 8.7
**Web server:**
Apache/2.4.10
**Database:**
mysql  Ver 14.14 Distrib 5.5.54, for debian-linux-gnu (x86_64) using readline 6.3
**PHP version:**
PHP 5.6.30-0+deb8u1 (cli) (built: Feb  8 2017 08:50:21)
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 11.0.2 (stable)
**Updated from an older Nextcloud/ownCloud or fresh install:**
Update (from 11.0.1)
**Where did you install Nextcloud from:**
Tarball
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - comments: 1.1.0
  - dav: 1.1.1
  - encryption: 1.4.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.1.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - external
  - files_external
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocfwgdunu68c",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.ulfklose.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***\/nextcloud.ulfklose.de\/data",
        "overwrite.cli.url": "http:\/\/nextcloud.ulfklose.de",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "mail_from_address": "ulf.klose",
        "mail_smtpmode": "php",
        "mail_domain": "gmail.com",
        "maintenance": false,
        "loglevel": 2,
        "theme": ""
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Apple Safari Version 10.0.3 (12602.4.8)
**Operating system:**
Apple macOS Version 10.12.3
#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Thu Mar 16 14:21:11.527893 2017] [fastcgi:error] [pid 24792] (104)Connection reset by peer: [client 83.236.232.206:33102] FastCGI: comm with server "/var/www/php-fpm/uklose/nextcloud.ulfklose.de/ssl-fpm.external" aborted: read failed
[Thu Mar 16 14:21:11.713794 2017] [core:error] [pid 24792] [client 83.236.232.206:33102] AH00524: Handler for fastcgi-script returned invalid result code 1
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No entries at the time of the error
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Doesn't seem to be a browser issue, tried it with two browsers on macOS and one on a Windows PC.
```
</details>

**Comment by nickvergessen** [comment]
I guess the connection is so slow, that the php timeout hits before.
please try to disable FastCGI

**Comment by ulfklose** [comment]
Thanks for the reply. I can't disable FastCGI on the server without trashing the complete setup which isn't an option. Isn't there a way to increase that timeout any further? As I wrote I can't find a 60 second timeout in my PHP configuration files. I set all the obvious timeouts to at least 2400 seconds.

**Comment by ulfklose** [comment]
I found the problematic setting on my web server. No nextCloud error, it is a problem with the PHP-FPM default configuration when using Froxlor. In the configuration files located under /etc/php5/fpm/pool.d you can find a configuration variable:

`request_terminate_timeout = 60s`

Increasing the value to a higher one solved my problem. Thanks for your attention and help.
