### ISSUE TITLE
[Feature Request] Bandwidth Quota Per User (Download/Upload)

### ISSUE THREAD

**Issue by switchupcb** [nextcloud/server#38650]
# Feature Request: Bandwidth Quota Per User

You must understand the difference between Network Speed vs. Bandwidth: https://obkio.com/blog/network-speed-bandwidth-throughput/#understand-the-difference-network-speed-vs-bandwidth-vs-throughput

**Is your feature request related to a problem? Please describe.**
A possible failure state of a NextCloud instance is exceeding the amount of Network Bandwidth provided by an ISP or Cloud service provider. For example, a Cloud service provider such as Digital Ocean may let a single virtual machine transfer 1TB over a month (download and upload bandwidth) at 10 Gbps (Network Speed). So if a user exceeds this amount, NextCloud will experience errors due to the server it's hosted on.

There are suggestions on the internet to implement this feature using a reverse proxy (i.e [nginx](https://www.reddit.com/r/NextCloud/comments/rorrn8/limit_bandwidth_for_user_downloads/)), but this method does not prevent a single user from using all the bandwidth (on purpose or by accident). So it would be helpful to have a bandwidth quota per user that works in a similar manner to the [NextCloud Storage Quota](https://docs.nextcloud.com/server/latest/user_manual/en/files/quota.html). This solution would prevent a single user from using all of the bandwidth of the server that the NextCloud instance is hosted on.

**Describe the solution you'd like**
Add a setting "Bandwidth Quota" that lets the administrator configure a bandwidth quota (both, download, upload) per user. Enabling this setting tracks the bandwidth usage of the user's uploads and downloads to prevent them from exceeding the specified bandwidth limit. When a user exceeds the bandwidth limit, let them know so an administrator can be contacted to review what happened.

**Describe alternatives you've considered**
There are suggestions on the internet to implement this feature by limiting the Network Speed (per user). While this feature is useful for download/upload consistency, limiting the Network Speed does not prevent the user from exceeding bandwidth unless you set the speed so low that the file size of downloaded/uploaded files will be limited over a specific time period.

`<!--- Please keep this note for other contributors -->`

### How To Use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by kesselb** [comment]
Thank you for opening a feature request :+1: 

Your idea could be implemented as Nextcloud app. 

Starting point, for your app, could be https://github.com/nextcloud/user_usage_report as it provides counting for file requests. Instead of counting the requests, you sum up the file size and store it somewhere. If the limit is reached, disable the user account.

We have no plans to add such a feature to Nextcloud server, and therefor close your feature request.
