### ISSUE TITLE
Show actual upload speed in kb/s in tooltip of upload progress bar

### ISSUE THREAD

**Issue by sebastianklein96** [nextcloud/server#3866]
Hey!

Currently I'm running Nextcloud 11.0.2 on Ubuntu 16.04 server and I'd love to be able to display the current upload speed in the web interface. 

Right now my web inteface only displays the usual upload percentage and time remaining. Seeing the upload speed would give the user an overview of the current server performance and would maybe cause them to postpone large file uploads if upload speeds are slow at the moment.

I've [posted about this on the forum](https://help.nextcloud.com/t/can-i-display-the-actual-upload-speed-in-the-web-interface/10224/2) and was redirected to post a feature request here. Is there any chance this could be implemented?

System info:
Nextcloud Version 11.0.2 stable
Ubuntu 16.04 Xenial
Apache 2.4.18
PHP 7.0.15

Sincerely,
Sebastian Klein

**Comment by MorrisJobke** [comment]
@jancborchardt We had this in the past: do you know the reason why we dropped it? I guess it's because we have the rough estimate and that should be fine, right?

**Comment by sebastianklein96** [comment]
@MorrisJobke @jancborchardt I don't really see a reason not to make this an option. The upload speed should be available to grab for display serverside (or maybe client side) anyways since I guess that the remaining upload time is being calculated with it and the file size remaining. Please correct me if I'm wrong.

**Comment by MorrisJobke** [comment]
> @MorrisJobke @jancborchardt I don't really see a reason not to make this an option. The upload speed should be available to grab for display serverside (or maybe client side) anyways since I guess that the remaining upload time is being calculated with it and the file size remaining. Please correct me if I'm wrong.

The speed is not really used. We only do a rough estimate based on bytes upload vs bytes to be uploaded and time that passed by. So this is at most an average speed.

**Comment by sebastianklein96** [comment]
@morrisjobke thanks for the clarification!

**Comment by jancborchardt** [comment]
If we want to display the speed at all, we could do it in a tooltip on hovering the progress bar. Showing it directly is not necessary as the information is less important than the progress.

Does that sound ok @sebastianklein96?

**Comment by sebastianklein96** [comment]
@jancborchardt that sounds awesome! Obviously it's not a feature that the mainstream of nextcloud users is asking for so your suggestion would be a good compromise.

**Comment by jancborchardt** [comment]
@sebastianklein96 would you be interested in diving in to do that? :) If you have any questions, you can ask here or join our IRC channel #nextcloud-dev. :)

**Comment by sebastianklein96** [comment]
@jancborchardt to be honest I most likely don't have the skills to do so. Basic HTML/CSS and a fair bit of Java is probably the limit of what I can offer 😄 but I'll still have a look around when I've got time over the coming weekend. 

On a different note, thanks for making OC/NC happen. It's made working with people a whole lot easier for me!

**Comment by jancborchardt** [comment]
> Basic HTML/CSS

This is absolutely enough. :) Simply use the web inspector a bit to check out which element you need to add it to. Check out how other parts of the app (like the date / size column) do the nice tooltips. Then there’s most likely a tiny bit of PHP involved but the people in #nextcloud-dev are happy to help with that. :) Or even if you just open a pull request with the basic changes (like showing a tooltip there with some content) we can help you add the rest.


> On a different note, thanks for making OC/NC happen. It's made working with people a whole lot easier for me!

Sure, you’re welcome! Would be cool to have you as contributor too. ;)

**Comment by lenusch** [comment]
Yes, i want that too and please with correct Time stamps. Everytime i am uploading files 1GB 10GB it always sais "finished in a few seconds" ... :-D

**Comment by TobiasJu** [comment]
yes please!

**Comment by panacmarcel** [comment]
https://cdn.pbrd.co/images/HAvThFC.jpg

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers 

The idea was to improve the overall upload state within Nextcloud 15. So maybe we can combine it with this as well.

**Comment by jancborchardt** [comment]
My proposal still stands:

> If we want to display the speed at all, we could do it in a tooltip on hovering the progress bar. Showing it directly is not necessary as the information is less important than the progress.

Someone of the many people who do :+1: comments or upvotes surely is able to implement this? :)

**Comment by Nottt** [comment]
In case anyone still looking for this with nextcloud 16:

https://help.nextcloud.com/t/can-i-display-the-actual-upload-speed-in-the-web-interface/10224/8

**Comment by enoch85** [comment]
@Nottt A PR for that maybe? :D

**Comment by reox** [comment]
I recently switched from Seafile to Nextcloud and not having a proper upload status is a little bit annoying.
Personally, I find the design of the Seafile upload status much more appealing and it has more information like currently uploading file, transfer speed etc.

**Comment by kesselb** [comment]
https://apps.nextcloud.com/apps/uploaddetails

**Comment by reox** [comment]
> 
> 
> https://apps.nextcloud.com/apps/uploaddetails

Unfortunately, this seems to not work right now (see the issue in the repo)
Also, why not upstream it?

**Comment by juliushaertl** [comment]
@reox See https://github.com/nextcloud/server/issues/3866#issuecomment-449516908

Everybody is welcome to propse a pull request to add the popover @jancborchardt mentioned.

**Comment by reox** [comment]
@burgha would you like to convert your app into a PR?

**Comment by burgha** [comment]
@reox i cant promise anything but i'll see what i can do

**Comment by jancborchardt** [comment]
And again, if it goes into core we should do it nicely integrated as I described above at https://github.com/nextcloud/server/issues/3866#issuecomment-449516908

> If we want to display the speed at all, we could do it in a tooltip on hovering the progress bar. Showing it directly is not necessary as the information is less important than the progress.

**Comment by burgha** [comment]
@jancborchardt i looked at the code and it seems like a tooltip was already intended but the data is set on the wrong HTML attribute ? i got it to work but i cant figure out how to update the tooltip live while it is open without disposing and reregistering it which causes an ugly flicker. do you know how to pull that off?

**Comment by jancborchardt** [comment]
@juliushaertl @ma12-co maybe you can help @burgha? :)

**Comment by juliushaertl** [comment]
@burgha Maybe you can open a pull request with your current code changes, then we can have a look there.

**Comment by burgha** [comment]
@juliushaertl i opened a [pull request](https://github.com/nextcloud/server/pull/17654). thanks for having a look

**Comment by mariusurbelis** [comment]
Please please implement this!! 💔

**Comment by burgha** [comment]
@mariusurbelis it's already done, as of Nextcloud 18 you can hover over the progressbar to see more details

**Comment by mariusurbelis** [comment]
> @mariusurbelis it's already done, as of Nextcloud 18 you can hover over the progressbar to see more details

How did I not spot this.. Thanks!
