### ISSUE TITLE
[Bug]: Event update email unclear with recurrence exceptions

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#38686]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] Nextcloud Server **is** running on 64bit capable CPU, PHP and OS.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Deleting an instance of a recurring event sends out an event update/invite without any useful information about what really changed.

The email says "Time: <time and date of very first occurence>"

### Steps to reproduce

1. Create an event with one attendee that recurs weekly for three times
2. Accept the invitation as the other user
3. Delete the second occurrence as the organizer

```ics
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VEVENT
CREATED:20230607T094533Z
DTSTAMP:20230607T094848Z
LAST-MODIFIED:20230607T094848Z
SEQUENCE:4
UID:5e8a4ae6-39d7-4cb1-91e0-f04036be45d9
DTSTART;TZID=Europe/Vienna:20230607T133000
DTEND;TZID=Europe/Vienna:20230607T153000
STATUS:CONFIRMED
SUMMARY:Zoo party
ATTENDEE;CN=schiraffe@domain.tld;CUTYPE=INDIVIDUAL;PARTSTAT=ACCEPTED;ROL
 E=REQ-PARTICIPANT;SCHEDULE-STATUS=1.1:mailto:schiraffe@domain.tld
ORGANIZER;CN=Christoph Wurst:mailto:org@domain.tld
RRULE:FREQ=WEEKLY;COUNT=3;BYDAY=WE
LOCATION:At the zoo
DESCRIPTION:Bring your own food
EXDATE;TZID=Europe/Vienna:20230614T133000
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;RELATED=START:-PT1H
END:VALARM
END:VEVENT
END:VCALENDAR
```

### Expected behavior

The attendee receives an email that says something like "Time: <time and date of very first occurence>, recurring weekly except <new exception date>".

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
n/a
```

### Additional info

https://github.com/nextcloud/calendar/issues/3919

**Comment by ChristophWurst** [comment]
The issue is broad. Some scenarios I've experienced in the past
1. Organizer cancels one of the instances of the recurrence
2. Organizer moves one of the occurrences
3. The recurring event changes time/day for all future instances
4. The recurrence ends

**Comment by SebastianKrupinski** [comment]
Hello all,

After looking in to this... yes the notification emails for recurring events are lacking...

Some possible changes to improve this could be...

## Time Section
Currently, the time section of the email only shows the day and time of the first event.

"Wed, Apr 22, 2024 10.00AM - 11.00AM (America/Toronto)".

A possible alternative to this could be to change this line to something more informative for recurring events.

"Weekly on Mo, We, Fr between 10.00AM - 11.00AM (America/Toronto)"

"Weekly on Mo, We, Fr between 10.00AM - 11.00AM (America/Toronto) until Fri, May 10, 2024" (Until would be also calculated for recurrence after count)

"Monthly on the 20th between 10.00AM - 11.00AM (America/Toronto)"

"Monthly on the 1st Friday between 10.00AM - 11.00AM (America/Toronto)"

"Yearly on the 20th of May between 10.00AM - 11.00AM (America/Toronto)"

## Next Recurrence Section
Currently the recurring event email notification does not have a section that indicates when the next occurrence is, this is fine if the recurrence does not change, in the case that there is a change made to a recurrence a simple to read section of when the next event occurs would be very help full. Something like...

- Occurring On
"Mon, Apr 29, 2024 10.00AM - 11.00AM (America/Toronto)"
"Wed, May 1, 2024 10.00AM - 11.00AM (America/Toronto)"
"Fri, May 3, 2024 10.00AM - 11.00AM (America/Toronto)"

## Changed Recurrence Section
Currently there is no indication of any time changes or deletions made to any occurrences. This could be made more clear with a additional section that list all changes made..

- Occurring Changes
"Moved: Fri, May 3, 2024 10.00AM - 11.00AM (America/Toronto) to Fri, May 3, 2024 8.00AM - 9.00AM (America/Toronto)"
"Cancelled: Fri, May 3, 2024 10.00AM - 11.00AM (America/Toronto)"

Thanks
Sebastian

**Comment by jancborchardt** [comment]
Sounds great to me @SebastianKrupinski, very thorough!

Only one details about the time format, cause it looks a bit like non-standard formatting (let me know if this comes from a library though). Instead of
> 10.00AM - 11.00AM

It should be:
> 10:00 am – 11:00 am

- colon `:` to separate hours and minutes
- en-dash `–` to separate from/to
- "am" and "pm" lowercase and separated with a space from the time

**Comment by SebastianKrupinski** [comment]
@jancborchardt Awesome.

The time formatting was just something I typed in as examples. The actual formatting can be what ever we want it to be.

Sebastian

**Comment by jancborchardt** [comment]
@SebastianKrupinski cool, in that case best get what a localized library spits out, so it's translated and universal. :)

**Comment by SebastianKrupinski** [comment]
@jancborchardt yes I will make sure its localized

**Comment by mcp11** [comment]
@SebastianKrupinski thank you very much for your input and effort in this matter. However, I would propose for this issue to be reopened. I made the experience in Nextcloud v31 that the update e-mails sent out when the organizer changes one occurence of a reoccuring event are lacking any useful information. In the current state, it is unclear which event is affected and whether it is a reschedule or cancellation.
Maybe I am missing something, but it seems to me like the original problems of @ChristophWurst mentioned in the very beginning of this issue are still existing.

**Comment by SebastianKrupinski** [comment]
> [@SebastianKrupinski](https://github.com/SebastianKrupinski) thank you very much for your input and effort in this matter. However, I would propose for this issue to be reopened. I made the experience in Nextcloud v31 that the update e-mails sent out when the organizer changes one occurence of a reoccuring event are lacking any useful information. In the current state, it is unclear which event is affected and whether it is a reschedule or cancellation. Maybe I am missing something, but it seems to me like the original problems of [@ChristophWurst](https://github.com/ChristophWurst) mentioned in the very beginning of this issue are still existing.

Hi @mcp11 ,

Yes there are still some instances where the notification emails could be improved, cancelling a single instance of modifying a single instance, I am working on improving these scenarios, there is a lot of legacy code and third party libraries to modify/replace, so it takes some time to fix all the scenarios.
