### ISSUE TITLE
Filerequest with Name like in Dropbox

### ISSUE THREAD

**Issue by furchtlos76** [nextcloud/server#38706]
I am really missing one feature, that i guess would be easy to implement, or maybe one could code a plugin for. Coming from Dropbox i used alot a feature called Filerequest there. This offers a link to give to friends or customers to upload files to your cloud that are for example to big for emails. Nextcloud does have that, but only full anonymous - so i do not see who of my friends or customers uploaded what file.

Sure i could add users or guests, but that feature would be so confortable to have like in Dropbox to just give out a upload url and do nothing else, and people can upload with adding their name or even e-mail adresse so i see who uploaded what. The name is added to the filename with a - before.

Could not find this feature for nextcloud yet. I hope this is the right place to make such a request, if not please tell me. Would be nice to get some responce. Thanks alot!

**Comment by solracsf** [comment]
Did you try https://apps.nextcloud.com/apps/guests
Maybe it fits your need better.

**Comment by joshtrichards** [comment]
Potentially relevant #17147

**Comment by skjnldsv** [comment]
Nextcloud 30! See https://github.com/nextcloud/server/issues/45446
