### ISSUE TITLE
Offer file encryption to other apps

### ISSUE THREAD

**Issue by rugk** [nextcloud/server#3871]
User story: As a NextCloud user I want to be sure all my data I upload to NextCloud is stored encrypted.

Background: I am a(n) ~luser~ ordinary user hearing NextCloud/the "cloud instance I use" uses encryption. I cannot really differentiate between file encryption end encryption of other things and I certainly cannot evaluate what is stored as files in NextCloud.

Current state (correct me if I am wrong): The encryption in NextCloud only encrypts files. All other data (of built-in or third-party apps) such as contacts, calender and so on are **not** encrypted. (They might be stored in the database, but where does not matter very much…)

What I'd like:
* Also offer the file encryption routines (as an API) to app developers, so they can (and should) integrate it into their apps, to automatically use this encryption.
* OR: Transparently do this and encrypt all data send/received by apps. I think, however, this would be quite hard depending how good your APIs are.

Examples: https://github.com/nextcloud/passman/issues/279#issuecomment-287156949

**Comment by MorrisJobke** [comment]
cc @karlitschek @LukasReschke @schiessle

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.
