### ISSUE TITLE
Sharing buttons getting disabled for a split-second should not change appearance

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#38711]
As discussed with @jancborchardt and @nimishavijay, the buttons should not get disabled when loading in order to not cause any flickering visually.

See the following screenshot:
![image](https://raw.githubusercontent.com/nextcloud/documentation/02a3c92edab2984ef47758d0df8076fe3d4492c5/developer_manual/images/action-menu-radio-button.gif)

cc @nextcloud/server-frontend

**Comment by jancborchardt** [comment]
@szaimen isn't this a Vue components issue rather than server?
