### ISSUE TITLE
Table header in file list should be always visible

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#3872]
Imagine you have a large file listing and you are scrolling down the road (the table header is vanished) and now you want to change the sort order, you would have to scroll back to the top.
I think it would be nicer if the table header is always visible to allow a quicker change of the sorting order.

What do you think @jancborchardt ?

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by Bugsbane** [comment]
I like the idea, as long as the header doesn't use up more room than is necessary on scrolling down. On mobile, we need every bit of vertical space we can get.

**Comment by stefan-niedermann** [comment]
May i suggest a solution like [this](http://jsfiddle.net/mariusc23/s6mLJ/31/) at least for mobile?
Hide the header when scroll down, and when scrolling up show it immediately fixed at the top?
So one has much space to view many files if he tires to access the nav table header, he will get this done very quick.

**Comment by jancborchardt** [comment]
@stefan-niedermann there’s also a library for that: https://github.com/nextcloud/server/issues/4047#issuecomment-289615461 – not sure if @MorrisJobke’s comment of rather not adding JS for that is valid here too, since he gave a :+1: to your suggestion. ;)

**Comment by tobiasKaminsky** [comment]
This is a very old issue, but still frustrates me when using web UI.
All of the common file browser have fixed column headers (and now also github).

We also have navigation breadcrumb and "+" fixed, maybe this can the be shifted into it on scrolling?

**Comment by a1pilot** [comment]
@tobiasKaminsky @skjnldsv I can see a lot of these header vanishing when scrolling issues marked as closed, but none explain why / if it was fixed.

Right now, if you don't have the right-click menu installed, it's impossible to perform any tasks such as deleting and moving files.

**Comment by kesselb** [comment]
@a1pilot https://github.com/nextcloud/server/pull/15302 fixed header is coming to nextcloud 17.

**Comment by a1pilot** [comment]
@kesselb Thanks.
