### ISSUE TITLE
[Bug]: NC 27 sort by modifed not saving.

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/server#38758]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I go into photos folder and click on modified and i want to soft from newest to oldes and if i refesh the screen defauls back to oldest to newest. 

### Steps to reproduce

https://github.com/nextcloud/server/assets/59488153/982fff47-7994-46a1-b345-0a9b69c78ff9

### Expected behavior

Should save the settings

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27.0.0 RC4

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
n/a
```

### List of activated Apps

```shell
n/a
```

**Comment by AndyXheli** [comment]
Still an issue on NC 27.0.0

**Comment by d4miano** [comment]
Still an issue on NC 27.0.1

**Comment by chrissi55** [comment]
> Still an issue on NC 27.0.1

so as in NC 27.0.2 ...

**Comment by skjnldsv** [comment]
Folks, you can see the label being set as `to develop` and the ticket not closed, so yeah, it's still happening

**Comment by swisschris** [comment]
> > Still an issue on NC 27.0.1
> 
> so as in NC 27.0.2 ...

and in NC 27.1.0 beta 1

**Comment by swisschris** [comment]
Still an issue on NC 27.1.0 Beta2

**Comment by susnux** [comment]
Fixed in https://github.com/nextcloud/server/pull/39919
Will be released in 27.1.0 beta 3
