### ISSUE TITLE
[Bug]: Inverted app label color for light background color

### ISSUE THREAD

**Issue by Hephi2** [nextcloud/server#38759]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When selecting a plain color as background and choose a light one (e.g., white), the app icons in the top bar are inverted to a dark color but the labels stay white and are therefore not/poorly visible.

![image](https://github.com/nextcloud/server/assets/46924014/c519b052-835d-4e9e-a752-9a9d3b9c28b3)

This is, because the color of the whole app menu entry is inverted for a light background color, while the `--color-primary-element-text'` is inverted as well, leading to a white text color on a light background.

### Steps to reproduce

1. In the appearance and accessibility settings select "No background" 
2. Change the color to white or a very light shade

### Expected behavior

The labels of the apps in the top bar should have a dark colour to be easily readable.

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment]
cc @frontend

**Comment by susnux** [comment]
I remember I had tried to fix this some time ago, not sure why I did not created a PR but maybe ot helps:

https://github.com/nextcloud/server/commit/36986e36c730f0149e4ce772ec982600081d9304

**Comment by Hephi2** [comment]
That is exactly what my fix would have looked like. I'll create a pull request with your branch.
