### ISSUE TITLE
Support FreeDesktop Common Extended (file) Attributes.

### ISSUE THREAD

**Issue by rokejulianlockhart** [nextcloud/server#38779]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**  
I use BTRFS. The `user.xdg.comment` field isn't synchronized between my devices.

**Describe the solution you'd like**  
Synchronize all FreeDesktop-defined Common Extended Attributes.

**Describe alternatives you've considered**  
There isn't one. TagSpaces demonstrates this well.

**Additional context**  
https://github.com/orgs/community/discussions/57080#discussion-5260979

**Comment by joshtrichards** [comment]
See:

#10282
#4216
#4217

**Comment by joshtrichards** [comment]
Closing since there are already other relevant linked issues. Feel free to subscribe to those and/or vote on them.
