### ISSUE TITLE
Grant super administrator to LDAP group

### ISSUE THREAD

**Issue by ndarwincorn** [nextcloud/server#3877]
[This](https://github.com/owncloud/core/issues/10004) doesn't appear to have been implemented.

I was going through @EchoSierra's changes and there's been changes to the functions he modifies in the linked issue. If there's interest in this functionality I could put together a PR.

**Comment by MorrisJobke** [comment]
> This doesn't appear to have been implemented.

Nobody said this.

That ticket suggests to use the provisioning API to set up admin users.

cc @blizzz

**Comment by blizzz** [comment]
Ack, and here is an example how we add an LDAP Admin account to the Nextcloud admin group within the Univention integration using the Provisioning API: https://github.com/nextcloud/univention-app/blob/master/inst.sh#L159-L174 (LDAP config needs to be setup before hand, obviously).

**Comment by MorrisJobke** [comment]
use the provisioning API to grant users admin privileges as of now. We don't plan to add this feature to the LDAP app.

**Comment by benyanke** [comment]
> use the provisioning API to grant users admin privileges as of now. We don't plan to add this feature to the LDAP app.

Is this an active rejection or simply a lack of time to implement?

Even if it were a raw LDAP query stuffed away in the _expert_ options, this seems it would be a valuable option.

**Comment by blizzz** [comment]
@benyanke lack of resources. If you like to work on it, that is welcome and I would support your efforts. Just, let's discuss how a solution would look like first. Do you have an idea already?

**Comment by benyanke** [comment]
Ok - I will start on this when my company begins to roll out NC.

My initial idea was a simple one: provide a plaintext field for ab LDAP query specifying the admins.

This could of course be expanded on in the future, but at the very least this would allow the functionality to exist within the application for those who need it.

**Comment by blizzz** [comment]
It needs to be wired into the server component as for know only the local admin group is checked. This can be opened up, which is more work, or perhaps it is possible to listen to the request on whether the user belongs to the "admin" group  – i think this broadcasted to all backends. It's  rather hackish though. Just two thoughts without looking into details. OK, to be picked up when the time's ripe :)

**Comment by xundeenergie** [comment]
I think, the time's here now...
