### ISSUE TITLE
[Bug]: Errors when uploading to file drop hard to spot

### ISSUE THREAD

**Issue by mejo-** [nextcloud/server#38795]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In a file drop (public share of a folder with upload only permissions), errors that happen during an upload are hard to spot.

A small alert icon with an exclamation mark in front of the file that failed to upload is the only persistent visual presentation that an error occurred. There's a toast with an error message displayed for a few seconds, but that's hard to miss as well, as it's really just displayed for a short period. And when uploading larger files, people might do different stuff in between while waiting for the upload to finish.

The situation is even worse in dark mode where the alert icon is particularly hard to spot. See the following screenshots:

| With toast | When toasts are gone |
|---|---|
| ![2023-06-13T15:43:35,344553795+02:00](https://github.com/nextcloud/server/assets/3582805/990e067b-3815-4452-90e7-67b99a93cbba) | ![2023-06-13T15:52:57,402299043+02:00](https://github.com/nextcloud/server/assets/3582805/9dae5531-8ff8-410c-9eab-0083664cbd2f) | 

@jancborchardt @nimishavijay @szaimen for input from the design team.

### Steps to reproduce

1. Share a folder publically as link with upload only permissions
2. Optionally turn on dark mode (but light mode is not much better)
3. Block requests containing `public.php/webdav` in the network tab of your browser developer tools
4. Upload a file to the public file drop

### Expected behavior

We should find a better and more obvious visual representation of upload errors in the public file drop UI.

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by skjnldsv** [comment]
new UI since 31, closing
