### ISSUE TITLE
[Bug]: Status modal closes unexpectedly

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#38817]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

There was a weird interaction with the status modal for a while. Sometimes it closes before I click *Save*. I've finally been able to figure out reproduction steps.

### Steps to reproduce

1. Log into Nextcloud
2. Open the status modal from the settings top right
3. Enter "a" into the status input
4. Click one of the presets below, like "Vacationing"

### Expected behavior

The preset text is put into my status. The modal *does not close*.

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Rello** [comment]
can we add this bug here also?

- choose a preset
- overwrite the status text
- press save

Actual result:
- default text is used as status
- just 'messageId | "meeting"' is sent back to the endpoint message/predefined
- during a normal status change 'message | "test"' is sent to the endpoint message/custom

**Comment by ChristophWurst** [comment]
I'd say that is separate but I ran into that as well
