### ISSUE TITLE
[Bug]: Nextcloud 27 very slow

### ISSUE THREAD

**Issue by c-prompt** [nextcloud/server#38822]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Just upgraded to Nextcloud 27 (PHP 8.2.7) and all pages are deathly slow. Nextcloud 26 had some lag but was generally snappy.

Based on troubleshooting, it seems to be related to the size of these Javascript files. For example, /dist/core-common.js?v=7308632d-22 seems to be downloading 16.1 MB on all pages (this is on the login screen):

![Nextcloud 27 slow - login screen](https://github.com/nextcloud/server/assets/10625352/9a857bb7-1c7e-4b2d-a07b-bfd2a5b7d665)

In fact, /dist/core-common.js?v=7308632d-22 is redownloading on every new page no matter the browser (i.e., even if the file has to be that big, it's not caching locally).

There are other files that seem huge as well. For example, once I login, file /apps/calendar/js/calendar-main.js?v=7308632d-22 is 9.9 MB:

![Nextcloud 27 slow - after login](https://github.com/nextcloud/server/assets/10625352/753ae7f5-bf0c-475f-aa07-f11fdee3eebb)

I'm not seeing any errors on the Admin Overview page:

![Nextcloud 27 Settings Admin Overview](https://github.com/nextcloud/server/assets/10625352/57fa4088-acac-46c0-bcb3-c3277d721529)

Nothing in the logs suggesting any other hang-up. Perhaps this is a `header` problem? (Ignore the check in Chrome's Disable Cache box - same problem occurs even when cache is enabled/that check isn't there.)

### Steps to reproduce

1. Upgrade to Nextcloud 27.
2. Click on any Nextcloud page.
3.

### Expected behavior

Better than each page taking 2-4 minutes to download.

### Installation method

None

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
With this, files will certainly be redownloaded.
![image](https://github.com/nextcloud/server/assets/12234510/7fa5e6b8-87d1-4709-b4e9-e587b42846b8)

**Comment by c-prompt** [comment]
> With this, files will certainly be redownloaded. ![image](https://user-images.githubusercontent.com/12234510/245881219-7fa5e6b8-87d1-4709-b4e9-e587b42846b8.png)

As I mentioned but probably wasn't clear, the screen print was taken with "Disable cache" checked. However, I've also tried it without it checked and I have the same problem.

**Comment by c-prompt** [comment]
Not directly related (as the file should still be cached in the browser) but linking to #38502 and https://help.nextcloud.com/t/public-library-dist-core-common-js-is-very-large/162339 as the size of the file has grown from v25.

**Comment by c-prompt** [comment]
After fiddling a lot, the issue seems to be gone. Sadly, I can't tell what I changed that made the difference. Closing.
