### ISSUE TITLE
Support PHP 8.3

### ISSUE THREAD

**Issue by zevlee** [nextcloud/server#38828]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
With the [release of PHP 8.3.0 Alpha 1](https://www.php.net/archive/2023.php#2023-06-08-3) on June 8, it would be worthwhile to begin testing for compatibility in Nextcloud so that it can be ready not too long after [the anticipated release date on November 23, 2023](https://wiki.php.net/todo/php83).

**Describe the solution you'd like**
First, have PHP 8.3 nightly included in CI builds ASAP.
Later, include official support for PHP 8.3 once it's stable.

**Describe alternatives you've considered**
None

**Additional context**
* https://github.com/nextcloud/server/issues/32595

**Comment by szaimen** [comment]
Cc @nextcloud/server-backend

**Comment by blizzz** [comment]
I would wait at least until feature freeze (July 18th), and rather for RC1, cf: https://wiki.php.net/todo/php83

**Comment by zevlee** [comment]
The first beta version of PHP 8.3 [has been released](https://www.php.net/archive/2023.php#2023-07-20-1).

**Comment by joshtrichards** [comment]
RC1: Released today

GA: Nov 23 2023

**Comment by joshtrichards** [comment]
@darkBuddha This isn't the place to ask, but you can monitor https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule
