### ISSUE TITLE
[Bug]: External storage and Webinterface not in sync

### ISSUE THREAD

**Issue by rgl1234** [nextcloud/server#38838]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Bug solved here #23988 unfortunately present again after update to V26 and also V27.

### Steps to reproduce

see #23988 

### Expected behavior

see #23988 

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

Other

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.111.13:8080",
            "cloud.domain.example"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.0.0.8",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/cloud.domain.example",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 2,
        "maintenance": false,
        "simpleSignUpLink.shown": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - bookmarks: 13.0.1
  - circles: 27.0.0
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.3.1
  - contactsinteraction: 1.8.0
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - groupfolders: 15.0.0
  - integration_openai: 1.0.10
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.0
  - password_policy: 1.17.0
  - photos: 2.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - support: 1.10.0
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_ldap: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - admin_audit: 1.17.0
  - bruteforcesettings: 2.7.0 (installed 2.4.0)
  - dashboard: 7.7.0 (installed 7.1.0)
  - encryption: 2.15.0
  - firstrunwizard: 2.16.0 (installed 2.10.0)
  - officeonline: 2.0.2 (installed 2.0.2)
  - suspicious_login: 5.0.0
  - twofactor_totp: 9.0.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by joshtrichards** [comment]
I thought this was expected behavior since there's only a "best effort" attempt to always find externally added files. The only entirely reliable solution being:

https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/external_storage_configuration_gui.html#adding-files-to-external-storages

i.e. see #38508

**Comment by rgl1234** [comment]
> I thought this was expected behavior since there's only a "best effort" attempt to always find externally added files. The only entirely reliable solution being:
> 
> https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/external_storage_configuration_gui.html#adding-files-to-external-storages
> 
> i.e. see #38508

@joshtrichards I understand, but fact is, that until Migration to V26/V27 we have been using this funtcionality since years. New files on external storages have always been visible immediately resp. updated during access of the folder on external share....

as you can see in the following screenshot, there is a configuration especially for this on external storages. Usually this worked perfectly until now (only with recent Issues that have been solved here #23988 )

![image](https://github.com/nextcloud/server/assets/11720329/54633d3d-8ad1-4025-a6a0-a7b57330f578)


So for me it is a bug that should be solved (see screenshot)

**Comment by joshtrichards** [comment]
**Don't do the below on a busy system unless you're prepared to change it back quickly. It's also not documented and only being suggested in the spirit of troubleshooting from a fellow community member... so beware**.


1. Look-up your Mount ID for the External Storage in question:

```
./occ files_external:list -a
```

2. Make a note of the # in the first column, then:

```
./occ files_external:option <mount_id> filesystem_check_changes 2
```

3. Try to reproduce the behavior.

4. Change things back to your current setting when you're done testing:

```
./occ files_external:option <mount_id> filesystem_check_changes 1
```

**Comment by rgl1234** [comment]
thanks @joshtrichards for your information, I tried it but it does not change anything. even 1 or 2 does not update changes on eccess of a folder

**Comment by afzl-wtu** [comment]
Same here external storage with mounted with --allow-other do not reflect changes on web ui.

**Comment by rgl1234** [comment]
bug still present in V27.0.2

**Comment by rgl1234** [comment]
bug still present in V27.1.0

**Comment by rgl1234** [comment]
bug still present in V27.1.1

**Comment by rgl1234** [comment]
bug still present in V27.1.2

**Comment by rgl1234** [comment]
bug still present in V27.1.4

**Comment by soapee01** [comment]
I'm also seeing this issue on 27.1.4.

**Comment by sema200** [comment]
bug still present in V28.0.2-fpm
install in docker

**Comment by Grubersky** [comment]
Can confirm, after upgrading to V26, this bug showed up and is now on the latest V27 still existing. We have a "master" account with external storage access that shares everything to other users, so other users have only access through the shares from the mentioned master account.
Refreshing is only working, when the original user is accessing the folder ("check for changes" on folder set to "once every direct access"). If the shared user is accessing the same folder, refreshing is not working.
So I feel like there is a link missing that tells Nextcloud (Or the external files app) to rescan the directory the same way it does if the original user is accessing it.

Just constantly scanning directories is not really a solution since we got over 110'000 directories and 3'500'000 files. Scanning the master user takes about three hours, and it feels like a waste of resources because things worked fine pre V26.

**Nextcloud Server version**
27

**Operating system**
FreeBsd 13.3

**PHP version**
8.2

**Web server**
apache 2.4

**Database engine version**
MariaDB 10.6

**Comment by Karatekid2407** [comment]
bug still present in V29.0.2

**Comment by rgl1234** [comment]
for me problem was solved in V29.0.0 and V29.0.1
V29.0.2 I did not test yet...

**Comment by Grubersky** [comment]
> for me problem was solved in V29.0.0 and V29.0.1 V29.0.2 I did not test yet...

This is interesting! If for you, this problem really was solved in V29.0.0 and V29.0.1 I'd be curious to know if it's also solved on V29.0.2 on your system. Because that would mean it's an inconsistent problem, (since Karatekid2407 mentioned that it's still broken) and I'd be curious to get to the bottom of why it works on some system and doesn't on others... And if it also breaks on V29.0.2 on your machine, I'd be just as curious to know. I'm eager to try it on my test machine, but I'm currently too deep in other projects.

**Comment by rgl1234** [comment]
tested v29.0.2 successfully....I use docker-fpm verssion and external storage on "local" filestystem

**Comment by Grubersky** [comment]
Okay, here's an update from my side:

Now that V29.0.5 got released, I finally updated. I was a bit skeptical, but so far it is indeed working again. Yeyy?

**Comment by soapee01** [comment]
Nextcloud Hub 8  v29.0.5 still has an issue for me. 

I am seeing files that have made it in somewhat recently (at least created this year), but I created a test file on an SMB share and 11 minutes later,  it still hasn't shown up in the nextcloud portal.

I have a script that auto-updates my instance on a daily basis, so it's always fresh and stable. Nothing in version 29 seems to have cleared it up yet. Is there something I'm supposed to do beyond upgrade?

**Comment by soapee01** [comment]
I'll add that on my phone, the android nextcloud app shows that something changed 13 minutes ago, but the file isn't there. Weird.

**Comment by Grubersky** [comment]
> Nextcloud Hub 8 v29.0.5 still has an issue for me.
> 
> I am seeing files that have made it in somewhat recently (at least created this year), but I created a test file on an SMB share and 11 minutes later, it still hasn't shown up in the nextcloud portal.
> 
> I have a script that auto-updates my instance on a daily basis, so it's always fresh and stable. Nothing in version 29 seems to have cleared it up yet. Is there something I'm supposed to do beyond upgrade?

I literally just updated from the latest V28 (where it didn't work) to V29.05 where it just started to work again.

Operating system
FreeBsd 13.3

PHP version
8.2

Web server
apache 2.4

Database engine version
MariaDB 10.6
