### ISSUE TITLE
[Bug]: occ theming:config favicon "/root/nc.ico" Unsupported image type for .ico and .png

### ISSUE THREAD

**Issue by ne0YT** [nextcloud/server#38842]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

setting favicon doesnt work:
occ theming:config favicon "/root/nc.ico"

it tells me:
```
In ImageManager.php line 233:

  Unsupported image type

theming:config [-r|--reset] [--] [<key> [<value>]]
```

also happens with .png and .svg..

### Steps to reproduce

1. having an ico-file named nc.ico inside /root
2. running this:
occ theming:config favicon "/root/nc.ico"

### Expected behavior

it sets my icon as the favicon

### Installation method

Community SNAP package

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment]
You can use an ICO file if the mime type is image/x-icon or image/vnd.microsoft.icon. 
Your file has a different mime type and therefor the exception.

**Comment by ne0YT** [comment]
> You can use an ICO file if the mime type is image/x-icon or image/vnd.microsoft.icon. Your file has a different mime type and therefor the exception.
the error occurs because I download the file from another nextcloud using wget. and even if I convert the ico back and forth (png - ico) using the convert command it wil still give me the same error.
It would make it much easier for me to generally allow .ico files as it works in many other places.

**Comment by ne0YT** [comment]
I now even downloaded the current favicon on my nextcloud setup and used it using the occ commadn and it gives me the same error..

**Comment by kesselb** [comment]
`file --mime-type logo.ico` to print the mime type of the file.

**Comment by ne0YT** [comment]
nc.ico: image/vnd.microsoft.icon

**Comment by kesselb** [comment]
The mime type looks correct. I just had a test with a random ico file. It works over here. 

```
php -r "var_dump(mime_content_type('/path/to/your/file.ico'));"
```

You can run the snippet above. That's the same function we use internally to detect the mime type.

**Comment by ne0YT** [comment]
> '));"

string(24) "image/vnd.microsoft.icon"

**Comment by ne0YT** [comment]
> The mime type looks correct. I just had a test with a random ico file. It works over here.
> 
> ```
> php -r "var_dump(mime_content_type('/path/to/your/file.ico'));"
> ```
> 
> You can run the snippet above. That's the same function we use internally to detect the mime type.

maybe I need to move the file somehwere as I installed nextcloud as a snap-package?

**Comment by kesselb** [comment]
I assume `nextcloud.occ theming:config` won't work as you execute the command on the host, but the file is expected inside the container. But it should also lead to a different error message because the file does not exist :shrug:

**Comment by szaimen** [comment]
Possibly snaps confinements blocks the file_exists check from working correctly? Cc @kyrofa

**Comment by kyrofa** [comment]
> Possibly the snaps confinement blocks the file_exists check from working correctly?

The favicon is in `/root/nc.ico`? Assuming this is an Ubuntu-based distro and it's properly confined, yeah almost certainly. Try putting it in `/var/snap/nextcloud/common/` somewhere.

**Comment by ne0YT** [comment]
works, not a bug
