### ISSUE TITLE
[Bug]: Drop Down in mail settings doesn't work

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#38845]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The drop down for the "Authentication method" in the mail server admin settings doesn't work:

![grafik](https://github.com/nextcloud/server/assets/1589737/7c452079-97b8-472e-aea1-20e70695fbe9)

### Steps to reproduce

1. Go to the mail server settings
2. try to select a authentication method
3. nothing happens

### Expected behavior

Dropdown opens and I can select a authentication method

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment]
Hi, this is intentional. See the information icon to the left

**Comment by schiessle** [comment]
> Hi, this is intentional. See the information icon to the left

If I hover over the "i"-icon I just get a grey empty box (Chromium and Firefox). Unfortunately screenshot tools doesn't capture it... But I'm sure you can reproduce it.

On a general note, if this shouldn't be edited, why do we put it into a drop-down in the first place and not show it as plain text?

**Comment by szaimen** [comment]
Already addressed in https://github.com/nextcloud/server/pull/38868
