### ISSUE TITLE
Custom configuration parameter

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#38870]
Hi! Please, add the possibility to declare and use own configuration parameters in config.php. This may be useful when modifying apps by your own.

**Comment by solracsf** [comment]
Can you give an example?

**Comment by ostasevych** [comment]
> Can you give an example?

I am trying to revive the 2FA using Signal with the help of this docker https://github.com/bbernhard/signal-cli-rest-api implementation, however, specifically this implementation doesn't support configuration for the registered number using the docker run command. So, I would like to pass it to the twofactor gateway app as the option from the config.php file. Is it possible?

**Comment by kesselb** [comment]
> So, I would like to pass it to the twofactor gateway app as the option from the config.php file. 

Apps can read access configuration variables via IConfig.
