### ISSUE TITLE
[Bug]: I cann't create user group on latest version 27.0.0

### ISSUE THREAD

**Issue by ylu19870105** [nextcloud/server#38877]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I cann't create user group on latest version 27.0.0

### Steps to reproduce

1.login in nextcloud by admin.
2.go to users setting
3.create new group

### Expected behavior

add a new group

### Installation method

None

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by imxzz** [comment]
同样遇到了这个问题

**Comment by ylu19870105** [comment]
> 同样遇到了这个问题

运气好

**Comment by ylu19870105** [comment]
someone has reported this bug.so closed to avoid repetition

**Comment by ylu19870105** [comment]
someone has reported this bug.so closed to avoid repetition

**Comment by imxzz** [comment]
这个问题怎么解决呢

**Comment by ylu19870105** [comment]
> 这个问题怎么解决呢

Wait for 27.0.1
