### ISSUE TITLE
[Bug]: Anonymous SMTP Stops Working Upgrading 25 -> 26

### ISSUE THREAD

**Issue by daveatpinellas** [nextcloud/server#38914]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I looked for this issue and so far it seems it has not been reported.  I did see some tickets for the last few days that the UI in this area had some changes and things moved around.

We have our email configured to send via anonymous smtp.  I upgraded one of our servers from 25 to 26 and saw this issue happening.  I reverted the change and built a clone in our test network to confirm and it replicated.

On version 25.0.7, server is configured for SMTP/No Encryption/<email address>/Authentication method NONE/<server address>/25
I click (send email) and everything works great, I hand deliver on the command line of this server via the command line with success.  Everything is working.

I then upgrade to 26.0.2 (and also tried 26.0.3 beta) and it will no longer deliver email.   The UI has changed, with Authentication method at the bottom of the group and showing 'Login' with the checkbox unchecked.  I push the (send email) button and it hangs.   Using my perl test script at the OS level, email delivers fine.  It's almost like even though even with 'authentication required' unchecked, that in some way it's using 'Login' in the code.  Is it checking for the string in this widget and following a path based on the selection?  I cannot activate this widget to set it to 'None' to prove this theory.

This disallows us from upgrading servers, email will not deliver. 

### Steps to reproduce

1. Have a working server using anonymous smtp email, on version 25.0.X
2. Upgrade to version 26.0.X (including 26.0.3)
3. Attempt to deliver email, and it will not send.

### Expected behavior

Email should deliver after upgrade.

### Installation method

None

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment]
See https://docs.nextcloud.com/server/26/admin_manual/configuration_server/email_configuration.html?highlight=starttls#tlspeerverification

**Comment by daveatpinellas** [comment]
Thank you @szaimen , that worked.  Sorry that I missed that in the documentation.
