### ISSUE TITLE
Can nextcloud add organizational structure support?

### ISSUE THREAD

**Issue by tracymacding** [nextcloud/server#3891]
we have about 100 members, it's very difficult for admin to create groups,folders and assign different folder access mode for group.

So, what i want know is: can nextcloud add organizational structure support?

**Comment by MariusBluem** [comment]
Well, this may be solved by a new app called "Circles" (https://github.com/nextcloud/circles) which allows users to define own sharing groups 🤔

**Comment by MorrisJobke** [comment]
Beside that you can use LDAP and import groups and users from there.


@karlitschek

**Comment by MorrisJobke** [comment]
> So, what i want know is: can nextcloud add organizational structure support?

What do you mean exactly by this?

**Comment by karlitschek** [comment]
yes. the usual way is that groups are read from ldap. the cirlces app are use defined groups. differnt usecase imho

**Comment by MorrisJobke** [comment]
Solution here:

* admin defined groups: fetch them from LDAP
* user defined groups: use the circles app
