### ISSUE TITLE
Unable to create groups

### ISSUE THREAD

**Issue by lum4chi** [nextcloud/server#38925]
### Steps to reproduce
1. Installed Nextcloud AIO from scratch, settings:
    a. Default addons: Collabora, Imaginary, Talk
    b. Timezone Europe/Rome
    c. Nextcloud 27 checked
    d. Backup point to external SSHFS (backup working)
3. Go to Settings/Users and try to create a group
4. Input a name and press enter (or click on "->")

### Expected behavior
New group added.

### Actual behavior
Nothing happens.

### Host OS
Debian 11

#### Nextcloud AIO version
Nextcloud AIO v6.1.1

#### Current channel
latest channel

#### Other valuable info
I was unable to find entries on the logs that was time-related to the group creation

**Comment by szaimen** [comment]
This will be resolved with Nextclou 27.0.1
