### ISSUE TITLE
[Bug]: Placement of status emoji picker handle

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#38938]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![Bildschirmfoto vom 2023-06-22 09-14-35](https://github.com/nextcloud/server/assets/1374172/8ca8d7b3-acd2-45a8-8ab7-dfd284f04075)

![Bildschirmfoto vom 2023-06-22 09-14-54](https://github.com/nextcloud/server/assets/1374172/2b8a62e1-e2b6-41b1-b0da-4f73f76c1425)

I think this has already looked better in the past. Labeling as regression.

### Steps to reproduce

1. Log into Nextcloud
2. Open the status modal

### Expected behavior

Good design

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Tested on 27.0.0.8

cc @Antreesy

**Comment by Antreesy** [comment]
Could it be just for you, or a one-time missing of styles, @ChristophWurst ?

master:
![image](https://github.com/nextcloud/server/assets/93392545/80f5ad4b-3a3e-4620-b8b4-36348f5f603a)

stable27:
![image](https://github.com/nextcloud/server/assets/93392545/66eda15f-7b51-4d9a-b419-290f376d04ba)

stable26:
![image](https://github.com/nextcloud/server/assets/93392545/1422ebe9-3441-454f-bb67-b83019358c86)

**Comment by ChristophWurst** [comment]
seems fixed in the meantime, probably with the change that added a border around the handle
