### ISSUE TITLE
Write profile URL into system address book contact

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#38944]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

Nextcloud users have a profile page.

![image](https://github.com/nextcloud/server/assets/1374172/40adfab0-0e60-477d-9eaa-ef8397439358)

**Describe the solution you'd like**

Write the profile URL to the SAB contact if the profile is enabled.
Don't write the URL otherwise.
Optional: write a type or similar attribute that allows us to distinguish *any* URLs from Nextcloud profile URLs for https://github.com/nextcloud/contacts/issues/3365

**Describe alternatives you've considered**

N/a

**Additional context**

* URL property spec: https://www.rfc-editor.org/rfc/rfc6350.html#section-6.7.8

**Comment by ChristophWurst** [comment]
``\OCP\Accounts\IAccountManager::PROPERTY_PROFILE_ENABLED`` is the account manager prop that *should* tell us if the profile is on/off

**Comment by ChristophWurst** [comment]
@jancborchardt @marcoambrosini @nimishavijay does the profile property have to be `WEB` or would it also be okay to use `SOCIALPROFILE` with type=Nextcloud?

**Comment by nimishavijay** [comment]
I would say `SOCIALPROFILE` with type=Nextcloud" works better here :) Would it be possible to render it on the frontend as a different property, similar to how it is shown in the personal settings like a card? That would help with advertising the profile feature more. If that's not possible, we could just show it in the quick actions, without showing it in the list of properties, what do you think? @nextcloud/designers
