### ISSUE TITLE
[Bug]: Nextcloud 26.0.2 email notification error

### ISSUE THREAD

**Issue by cycu85** [nextcloud/server#38957]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

hello

there is a bug in mail notification setting.

in log i have:

```
Exception: Symfony\Component\Mailer\Transport\Smtp\Stream\SocketStream::setTimeout(): Argument #1 ($timeout) must be of type float, string given, called in /var/www/nextcloud/lib/private/Mail/Mailer.php on line 305 in file '/var/www/nextcloud/3rdparty/symfony/mailer/Transport/Smtp/Stream/SocketStream.php' line 37
```

### Steps to reproduce

in config.php i try change 
`"mail_smtptimeout"  => '30',`  to `"mail_smtptimeout"  => 30, `
but no efect.

so i delete `"mail_smtptimeout"  => '30'` from config.php
still nothing.

chnge setting from web admin panel restore  `"mail_smtptimeout"  => '30',` to config.php

only delete `"mail_smtptimeout"  => '30'`, from config.php
and
change  
`/var/www/nextcloud/3rdparty/symfony/mailer/Transport/Smtp/Stream/SocketStream.php  in line 47
`
from 
`return $this->timeout ?? (float) \ini_get('default_socket_timeout');`
to:
`return $this->timeout ?? (float) \ini_get(30);`

help me to workaround problem

### Expected behavior

can you fix it?

### Installation method

None

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment]
If you run into the situation that a configuration value is “unchangeable”, a frequent explanation is another file in the configuration directory ending with `.config.php` (e.g. `my.config.php`).

**Comment by kesselb** [comment]
Do you have another file, in your config directory, ending with `.config.php`?

> I understand, but in this case it is an incorrectly defined variable type or incorrectly fetched from the config.

Our default is 10 (without quotes) which is, in php, a valid float. 

`"mail_smtptimeout"  => '30', `

string, wont work.

`"mail_smtptimeout"  => 30,`

int, should work. 

> so i delete "mail_smtptimeout"  => '30' from config.php
> chnge setting from web admin panel restore "mail_smtptimeout"  => '30', to config.php

- You deleted the config option. 
- Pressed save in web client. 
- `"mail_smtptimeout"  => '30'` reappeared

Correct? 

If mail_smtptimeout => '30' reappears it's defined somewhere else. 
Check your configuration directroy for another configuration file.

**Comment by cycu85** [comment]
I don't have another *.config.php file

there is only:
config.php
config.sample.php
.htaccess
mimetypealiases.json
mimetypemapping.json



>     You deleted the config option.
>     Pressed save in web client.
>     "mail_smtptimeout"  => '30' reappeared
> 
> Correct?`

Exactly

**Comment by kesselb** [comment]
Then `"mail_smtptimeout"  => 30,` will work.

**Comment by cycu85** [comment]
Unfortunately it does not work

**Comment by buzter** [comment]
> change `/var/www/nextcloud/3rdparty/symfony/mailer/Transport/Smtp/Stream/SocketStream.php in line 47 ` from `return $this->timeout ?? (float) \ini_get('default_socket_timeout');` to: `return $this->timeout ?? (float) \ini_get(30);`
> 
> help me to workaround problem

Same problem here on Synology DSM 7.2 with php8.1 and Apache2.4. Many Thanks for the tipp with the workaround - "solved" my problem for now. Best regards

**Comment by daveatpinellas** [comment]
Just documenting, RHEL 8 with PHP 8.0.27, this setting is a gotcha during upgrade.  Prior to version 26, this setting allowed quotes, now that causes email to fail.  I had to make the change documented in this ticket:

33c33
<   'mail_smtptimeout' => '60',
---
>   'mail_smtptimeout' => 60,
