### ISSUE TITLE
[Bug]: Regression in apps using data-apps-slide-toggle for settings toggle button

### ISSUE THREAD

**Issue by AsamK** [nextcloud/server#38981]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The settings can't be opened anymore some apps with NextCloud 27 (and newer). In apps that use the data-apps-slide-toggle attribute for implementing the settings toggle button the settings button doesn't work anymore.
Affects at least the News (https://github.com/nextcloud/news/issues/2242) and Activity (https://github.com/nextcloud/activity/issues/1199) apps.

The issue has been introduced in https://github.com/nextcloud/server/pull/36534, which removed the code handling the data-apps-slide-toggle attribute. This attribute is still documented for NextCloud 27 (https://docs.nextcloud.com/server/27/developer_manual/html_css_design/navigation.html#settings) so it was probably removed unintentionally and should be added back.

This is the code that needs to be added back:
- https://github.com/nextcloud/server/pull/36534/files#diff-ef8ad78d200f5a9cb815161aa620ca6ef324f9c5d9cd1453ac72bb9447174fe8
- https://github.com/nextcloud/server/pull/36534/files#diff-3c9d8a8e67f44448736aac4deec4137721dff26ad5deb9c885518b43e410f66e

### Steps to reproduce

1. Install news (beta) or activity app on NextCloud 27
2. Click the settings button in the left bottom corner
3. -> nothing happens

### Expected behavior

When clicking the settings button, the settings should open.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment]
Cc @skjnldsv

**Comment by skjnldsv** [comment]
Hum, my bad, I don't remember searching for usage of that old feature, but I should have documented it! :warning:
