### ISSUE TITLE
[Feature Request] Disable password requirement to update apps

### ISSUE THREAD

**Issue by STaRDoGG** [nextcloud/server#38998]
Another enhancement that I accidentally posted to the wrong repo: https://github.com/nextcloud/viewer/issues/1748#issue-1772888076

> I can tell you this is never gonna happen.
> Better safe than sorry. :)

"MY Nextcloud, MY choice!" :p

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by STaRDoGG** [comment]
@szaimen 

A couple questions:

- Since this itself is a request, does it still count toward your running total of requests for this? Reason I ask:
- You closed the request; when you close a feature request, does the request still get logged somewhere (other than this closed issue)? So that the "request for this feature count" keeps a running total?
- I've never even looked into making a NC extension ("app"); is this something that could be done via an app? If yes, I might consider just making one for myself, as that confirmation pw has gotten tot he point of annoying me to no end.

**Comment by szaimen** [comment]
> * I've never even looked into making a NC extension ("app"); is this something that could be done via an app? If yes, I might consider just making one for myself, as that confirmation pw has gotten to the point of annoying me to no end.

I dont think this could be done via an app (at least not in an unhacky way) but you could create a pull request and request some reviews. But from security perspective, I don't think this will be mergable.
