### ISSUE TITLE
Use Zeroconf technology (a.k.a. "Bonjour", a.k.a. "Avahi") for DNS-SD (DNS-based Service Discovery)

### ISSUE THREAD

**Issue by KurtPfeifle** [nextcloud/server#39]
It should be easy-peasy for users + clients to discover an <strike>_own_</strike>NextCloud service instance available to them (either on LAN/WLAN, or on Wide Area LAN) and then connect to it.

**_Quotes from the future:**_

> _"After installing Nextcloud, I just started my Android client, and BAMM!, it had already discovered the Nextcloud server and presented to me its login screen."_
> 
> _"After I started my Epiphany browser, a 'Nextcloud' bookmark within the 'Nearby Sites' category was already there. Clicking on it presented me its login screen."_

---

For this to work, the server component should be able to announce its presence and its exact services to potential clients. (Clients also need a way to take notice of these announcements.)

Exactly for this purpose [mDNS](http://www.ietf.org/rfc/rfc6762.txt) (Multicast-based DNS, described in _RFC 6762_) and [DNS-SD](http://www.ietf.org/rfc/rfc6763.txt) (DNS-based Service Discovery, described in _RFC 6763_) have been specified by the IETF.

Given that most Linux distributions nowadays provide [Avahi](http://www.avahi.org/) out of the box, getting this server part of the equation to work should be super-easy. Merely taking advantage of the already existing `_webdav._tcp`, `_http._tcp` and `_https._tcp` service types should already go a long way.

Utilizing the existing Apache module [**`mod_dnssd`**](http://0pointer.de/lennart/projects/mod_dnssd/) (for more docu, [see also here](http://0pointer.de/blog/projects/mod_dnssd.html)) should be a breeze. It may require an additional dependency to install: on Debian the package name is [`libapache2-mod-dnssd`](http://packages.debian.org/libapache2-mod-dnssd).

Finally, you may want to consider to register your own service types `_nextcloud._tcp` and `_owncloud._tcp` (possibly with sub-types for `_contacts`, `_calendar`, etc.) with IANA here: [www.iana.org/cgi-bin/usr-port-number.pl](http://www.iana.org/cgi-bin/usr-port-number.pl).

---

See also **_[at the respective topic in the forums](https://help.nextcloud.com/t/feature-request-nextcloud-servers-and-clients-should-support-zeroconf-a-k-a-bonjour/476)**_, where further hints and some details have been discussed already.

**Comment by aronovgj** [comment]
> "After I started my Epiphany browser, a 'Nextcloud' bookmark within the 'Nearby Sites' category was already there. Clicking on it presented me its login screen."

If Nextcloud would add bookmarks to my browser without asking me, my quote would look different.

**Comment by KurtPfeifle** [comment]
@aronovgj :

Hey, Epiphany already ***DOES*** automatically add bookmarks without asking you (if your box has a running *`avahi-daemon`*) ! 

It adds those bookmarks into a special bookmark department called 'Nearby Sites'. These bookmarks are auto-created whenever there is an Avahi- or Bonjour- or other DNS-SD announcement seen over mDNS which advertises a `_http._tcp` service record.

But stay calm, please! Epiphany also auto-removes these same bookmarks again as soon as Avahi notices that the service has gone away from the network.

It's not a bug, it's a feature -- and it is the whole purpose of Avahi:

* It's the same mechanism as the one which automatically finds nearby AirPrint-capable printers if you want to print from an iPad or an iPhone.
* It's the same mechanism as the one which lets interested clients auto-discover CUPS print queues (if these are set up to be "shared").
* It's the same mechanism as the one which lets you easily find your Amazon Fire TV stick in your home, if you want to access it from a computer.
* It's the same mechanism, that lets you share iTunes music in a shared LAN, or lets you access others' iTunes shares.
* It's the same mechanism, that lets you automatically find all Kodi servers (if set up to make this easy) from a client.

If you don't believe me -- *I guess you won't (because you do not seem to have consciously encountered DNS-SD in your network life so far)* -- just run the following two commands in a terminal, in any order:

```
 $ avahi-publish-service \
     --domain local.     \
     --address nextcloud.com. 88.198.160.129 &

 $ avahi-publish-service \
    --host nextcloud.com.\
    --domain local.      \
    --service "Nextcloud Web Site -- brand-new!" \
      _http._tcp         \
      80                 \
      path="/news" &
```

Now start Epiphany, open bookmarks, open the 'Nearby Sites' list, and admire your brand-new, auto-generated bookmark pointing to the Nextcloud web site.

(If you want to see how it is automatically removed again, type `fg <enter>` then `<ctrl>-c` into your terminal. Your automatically added bookmark is gone again.)

---- 

Congratulations! You've just let Epiphany add a bookmark to your browser without asking you. Now your quote is due  :smiley:
I'm really interested in what your quote looks like now... 
Will you let me know, please?  😃 

----

<sub>(Above commands tested on Debian Jessie 8.0: working. Tested on Raspian on a Pi3: first command [which creates name-to-IP resolution in `.local` domain] doesn't  work -- even though Avahi version was 0.6.31 for both.)</sub>

**Comment by aronovgj** [comment]
I'll change my quote to:
> I'd prefer to not use epiphany

But thats interesting, I learned something new and excuse my ignorance :)

**Comment by MorrisJobke** [comment]
Autodiscovery for servers has very limited user base (those who have their server in their home network). If you want to have this you should set this up on the server independent from the nextcloud server.


Thus I will close this ticket.

**Comment by KurtPfeifle** [comment]
@MorrisJobke:
 
You are completely wrong when stating that *"autodiscovery for servers has a very limited user base". However, that is not your fault -- it's mine, since I don't seem to have been able to explain and put over my ideas in a way which makes them understandable.

Also, you confused me by seemingly saying that the limited user base is equivalent to "those who have their server in their home network". Don't ***MOST*** Nextcloud users run their Nextcloud instances in their home network? How is that a limited user base then?

**Comment by MorrisJobke** [comment]
> You are completely wrong when stating that "autodiscovery for servers has a very limited user base". However, that is not your fault -- it's mine, since I don't seem to have been able to explain and put over my ideas in a way which makes them understandable.
> 
> Also, you confused me by seemingly saying that the limited user base is equivalent to "those who have their server in their home network". Don't MOST Nextcloud users run their Nextcloud instances in their home network? How is that a limited user base then?

Sorry for sounding a bit harsh here.

Let me elaborate a bit more: I fully understand the use case. Nevertheless we are building an web app, that responds to incoming HTTP requests mainly. As far as I understood this mDNS is not based on HTTP, right? It's its own protocol. I doubt that there is an easy way for the PHP runtime (without additional configuration) to respond to those requests.

Therefore I proposed to properly document how to configure the avahi daemon to make this service discoverable instead of putting this into our code and then require a lot of additional wiring to be able to respond to those requests.

Does that make sense or am I completely wrong here?

**Comment by stokito** [comment]
NC API internally uses WebDAV with extensions so instead of creation of a new [DNS-SD key we may use an existing](http://www.dns-sd.org/ServiceTypes.html) `_webdav.tcp_`  with additional TXT record like `product=nextcloud` so mDNS clients can distinguish it and in the same time the same share will be seen in Gnome/KDE's file manager.

Then implement the search for such records in Nexcloud APP for iOS and Android.
Nextcloud may be installed from a package managers in Ubuntu and OpenWRT so we may add an additional package that will create `/etc/avahi/services/nextloud.service` file that advertise the NC instance on a default path.
It's not necessary to publish mDNS record from PHP script.
This simple change may improve user experience a lot
