### ISSUE TITLE
[Bug]: Nextcloud continues reading the file after it has been closed

### ISSUE THREAD

**Issue by realies** [nextcloud/server#39000]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Opening a video file in the web UI and seeking a few times, then closing the file (and stream), does not stop the whole file from being read from the filesystem. 

### Steps to reproduce

1. Open video file, scrub
2. Close the video file
3. Video file continues to be read by Nextcloud

### Expected behavior

1. Open video file, scrub
2. Close the video file
3. Video file stops being read on the filesystem

### Installation method

Official All-in-One appliance

### Nextcloud Server version

27

### Operating system

Other

### PHP engine version

Other

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment]
See https://github.com/nextcloud/server/issues/19567

**Comment by realies** [comment]
> See https://github.com/nextcloud/server/issues/19567

Does this mean a fix is coming to Nextcloud soon?

**Comment by yevon** [comment]
Is this closed? The new version of the sabre-io library have been merged?

**Comment by realies** [comment]
@yevon, check the issue above: https://github.com/nextcloud/server/issues/19567#issuecomment-1607246591
