### ISSUE TITLE
Remind me

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#39030]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Across the Nextcloud ecosystem there are many activities and notifications I see as a user. I don't always have time to act right away. I want a way to postpone my action to a later point in time.

**Describe the solution you'd like**
Allow me to click *Remind me tomorrow* or *Remind me next week*.

**Describe alternatives you've considered**

Use the existing task integrations
* Mail can create tasks from emails
* Talk can create tasks from messages

**Additional context**

* https://github.com/nextcloud/mail/issues/2048

**Comment by jancborchardt** [comment]
Closing this in favor of https://github.com/nextcloud/server/issues/39181 – which is in the boards and has further info also.

Just FYI @AndyScherzinger as the issue by @ChristophWurst already existed.
