### ISSUE TITLE
[Bug]: User address book catches wrong exception

### ISSUE THREAD

**Issue by DominusExult** [nextcloud/server#39054]
### Describe the bug

I accidentally updated my docker Nextcloud from 26.0.2 to 27 (because my docker compose had "latest" instead of "stable" and I didn't pay attention that 27 is now latest and 26.0.3 is now stable instead of 25.x).

Everything seems to work fine, except the web contacts page. This is stuck on "Loading contacts ..." with no menu or anything.

It seems that accessing the contacts via apps on my phone still works

### Steps to reproduce

1. log in to the web interface
2. switch to contacts via the menu icon

### Expected behavior

contacts page to load, show my contacts, show the contacts menu

### Actual behavior

it's stuck on "Loading contacts ..."

### Contact version

5.3.2

### Operating system

docker

### PHP engine version

Other

### Web server

Apache (supported)

### Database

MySQL

### Additional info

PHP 8.2.7

![image](https://github.com/nextcloud/contacts/assets/3313896/e0433be0-f603-43e2-84c5-1ea03aef910e)

**Comment by DominusExult** [comment]
Anything I can do to band aid it?

**Comment by miaulalala** [comment]
> > Autoload path not allowed
> 
> ~#38797 try restarting your web server after the upgrade~
> 
> This is a regression of [bd80a1b](https://github.com/nextcloud/server/commit/bd80a1b2dd4ee46a21fc17dada0cf9c438f92a6d).
> 
> `\OCA\DAV\CardDAV\UserAddressBooks::getChildren` calls `\OC::$server->get` and catches `NotFoundExceptionInterface | ContainerExceptionInterface` but that method doesn't throw those.
> 
> Reproducible with the `federation` app disabled.

Unfortunately the docs are miosleading here:

``` php
\Psr\Container\ContainerInterface

interface ContainerInterface
{
    /**
     * Finds an entry of the container by its identifier and returns it.
     *
     * @param string $id Identifier of the entry to look for.
     *
     * @throws NotFoundExceptionInterface  No entry was found for **this** identifier.
     * @throws ContainerExceptionInterface Error while retrieving the entry.
     *
     * @return mixed Entry.
     */
    public function get(string $id);
```

but the implementation in `\OC\AppFramework\Utility\SimpleContainer::get` doesn't wrap the `$this->query($id)` and thus it throws a `QueryException` only.
