### ISSUE TITLE
Employee time clock (Track Employee Hours) 

### ISSUE THREAD

**Issue by moosavisa** [nextcloud/server#39056]
Dear Nextcloud developers

In some countries SME or either startups ought to track employees working hours. How much time day attend work or how much time off the work. 
To comply with these tracking hour regulations some startups or SMEs use mobile or web-based apps. They collect data from staff and can manage wage and payments. Also the company need to export and save these data to meet regulations. 

Here I suggest: 
"A clock for work" section in Nextcloud, where employees can clock-in and out using either a web or a mobile app. 
Timesheets be created automatically, making payroll processing faster and  more accurate. 
Not only this, but the clock for work let to manage absences, overtime, have an overview of real-time presence in the team (company), and if possible have some basic options for HR analytics. 
Just a simple drawing: 
![clock-for-work1](https://github.com/nextcloud/server/assets/105066435/565523b9-762c-442f-92f1-e4ad52ab9d8b)
![clock-for-work](https://github.com/nextcloud/server/assets/105066435/7941f162-74f7-48a6-b684-f41987e87ba2)

**Comment by kesselb** [comment]
Thank you for opening a feature request :+1: 

Your idea could be implemented as Nextcloud app. Two apps for time tracking already exist. Maybe the app developers are willing to extend their app with a check-in / check-out feature.

https://apps.nextcloud.com/apps/timemanager
https://apps.nextcloud.com/apps/timetracker

We have no plans to add such a feature to Nextcloud server, and therefor close your feature request.
