### ISSUE TITLE
Events of TwoFactor provider and manager names are very confusing (at best)

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#39087]
The names of the typed events are in my opinion wrong and will lead to wrong assumptions:

## Case 1

* Dispatched when a user successfully passes a 2FA challange:
* https://github.com/nextcloud/server/blob/d9f85220038b2421870a36f9b6a860d6444a988a/lib/private/Authentication/TwoFactorAuth/Manager.php#L285-L292
* Legacy dispatcher: IProvider::EVENT_SUCCESS
* Typed: OCP\Authentication\TwoFactorAuth\TwoFactorProviderForUserEnabled
    * 😕  ❓  Was the provider disabled for a user?!
    * 💥 No, it auth was passed and a better name would be OCP\Authentication\TwoFactorAuth\TwoFactorProviderChallangePassed
    * The old event should be deprecated immediately and both events be dispatched for the time being

## Case 2

* Dispatched when a user does not pass a 2FA challange:
* https://github.com/nextcloud/server/blob/d9f85220038b2421870a36f9b6a860d6444a988a/lib/private/Authentication/TwoFactorAuth/Manager.php#L295-L301
* Legacy dispatcher: IProvider::EVENT_FAILED
* Typed: OCP\Authentication\TwoFactorAuth\TwoFactorProviderForUserDisabled
    * 😕  ❓ Was the provider disabled for a user?!
    * 💥 No, it auth was failed and a better name would be OCP\Authentication\TwoFactorAuth\TwoFactorProviderChallangeFailed
    * The old event should be deprecated immediately and both events be dispatched for the time being

## Case 3

* Dispatched when a user is being deleted inside a listener for UserDeletedEvent
* https://github.com/nextcloud/server/blob/f5c361cf44739058b79f322576a1bad2d8c142d9/lib/private/Authentication/Listeners/UserDeletedStoreCleanupListener.php#L44-L50
* https://github.com/nextcloud/server/blob/f5c361cf44739058b79f322576a1bad2d8c142d9/lib/private/Authentication/TwoFactorAuth/Registry.php#L68-L73
* Legacy dispatcher: none
* Typed: OCP\Authentication\TwoFactorAuth\TwoFactorProviderDisabled
    * 😕  ❓ Was the provider disabled for everyone?!
    * 💥 No, all entries of a single user get deleted OCP\Authentication\TwoFactorAuth\TwoFactorProviderForUserDisabled
        * But that name is from case 2, so need a different one Maybe "TwoFactorProviderUnregisteredForUser"
    * The old event should be deprecated immediately and both events be dispatched for the time being

**Comment by ChristophWurst** [comment]
Yep, confusery

**Comment by ChristophWurst** [comment]
Reassuming to find out it wasn't me: https://github.com/nextcloud/server/commit/3c5cf825b396eacdc3e2376137e010552796119e

**Comment by rullzer** [comment]
I blame the approvers
