### ISSUE TITLE
Give proper feedback when server has disabled federated cloud sharing

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#3908]
Person A has federated cloud sharing enabled and wants to share with Person B. Person B is at a provider which has it _disabled_ but the person doesn’t know about it.

The only way this is visible to people right now is that the share field says »Share with users or groups« instead of »users, groups or remote users«.

There’s two scenarios in which the error messages are insufficient, confusing or make it seem like the software is broken:

First:
1. Person A shares a folder via link
2. Person B opens the link and wants to add the folder to their Nextcloud
3. Puts in the federated cloud ID but the error is »Sharing [folder] failed, could not find [user ID], maybe the server is currently unreachable.«

Same for the second:
1. Person A wants to share a folder directly with person B
2. Puts the federated cloud ID in the share input but the error is also: »Sharing [folder] failed, could not find [user ID], maybe the server is currently unreachable.«

In both cases the server can absolutely be reached. Can we not check in some way if federated sharing is disabled? This API capability should be communicated.

cc @schiessle

**Comment by szaimen** [comment]
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!
