### ISSUE TITLE
MultipartUpload for uploading chunks to s3 may break other object store implementations

### ISSUE THREAD

**Issue by EchedeyLR** [nextcloud/server#39088]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Currently, it is not possible to upload large files through the web interface (more than 10 MiB) using the web client starting by Nextcloud 26.

Other clients work. Everything works in Nextcloud 25.

An error is showed as the ObjectStore not supporting MultiPartUploads.

### Steps to reproduce

1. Install Nextcloud
2. Install StorJ app
3. Configure it as ObjectStore

### Expected behavior

Being able to upload big files.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Signing status

```json
{
  "reqId": "EQyBldlkEuO3u4jdtVqY",
  "level": 3,
  "time": "2023-06-30T10:56:49+00:00",
  "remoteAddr": "*.*.*.*",
  "user": "echedeylr",
  "app": "webdav",
  "method": "MKCOL",
  "url": "/remote.php/dav/uploads/echedeylr/web-file-upload-07010de993dce4c44dc3cc1b29e57d38-1688122602929",
  "message": "Object store does not support multipart upload",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0",
  "version": "26.0.3.2",
  "exception": {
    "Exception": "OCP\\Files\\GenericFileException",
    "Message": "Object store does not support multipart upload",
    "Code": 0,
    "Trace": [
      {
        "function": "startChunkedWrite",
        "class": "OC\\Files\\ObjectStore\\ObjectStoreStorage",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/lib/private/Files/Storage/Wrapper/Wrapper.php",
        "line": 524,
        "function": "call_user_func_array"
      },
      {
        "function": "__call",
        "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/lib/private/Files/Storage/Wrapper/Wrapper.php",
        "line": 524,
        "function": "call_user_func_array"
      },
      {
        "function": "__call",
        "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/lib/private/Files/Storage/Wrapper/Wrapper.php",
        "line": 524,
        "function": "call_user_func_array"
      },
      {
        "file": "/var/www/cloud/apps/dav/lib/Upload/ChunkingV2Plugin.php",
        "line": 133,
        "function": "__call",
        "class": "OC\\Files\\Storage\\Wrapper\\Wrapper",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php",
        "line": 89,
        "function": "afterMkcol",
        "class": "OCA\\DAV\\Upload\\ChunkingV2Plugin",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 482,
        "function": "emit",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 253,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 321,
        "function": "start",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/apps/dav/lib/Server.php",
        "line": 366,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/apps/dav/appinfo/v2/remote.php",
        "line": 35,
        "function": "exec",
        "class": "OCA\\DAV\\Server",
        "type": "->"
      },
      {
        "file": "/var/www/cloud/remote.php",
        "line": 172,
        "args": [
          "/var/www/cloud/apps/dav/appinfo/v2/remote.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/cloud/lib/private/Files/ObjectStore/ObjectStoreStorage.php",
    "Line": 638,
    "message": "Object store does not support multipart upload",
    "exception": [],
    "CustomMessage": "Object store does not support multipart upload"
  },
  "id": "649f14d4a11ba"
}
```

### Additional info

      It seems that the #27034 has been merged to master and 26.0.0 recently.
    
      However, this feature also needs the client to support it (since it has limitations). As per my trial, the newest desktop version didn't implement it yet. I have submitted an issue here: https://github.com/nextcloud/desktop/issues/5554. Please upvote that issue if you need this feature.
    
    _Originally posted by @ZE3kr in https://github.com/nextcloud/server/issues/19414#issuecomment-1489598976_

PR: https://github.com/nextcloud/server/pull/27034

**Comment by kesselb** [comment]
Please update your comment to use our usual template for bug reports: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&projects=&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

Also provide more details about your StorJ setup. 
There is an app for Nextcloud, but you mounted it as s3 bucket? 

The error is emitted here: https://github.com/nextcloud/server/blob/83eb6c3205997e32fcc1f276d71c2575d6e27bba/lib/private/Files/ObjectStore/ObjectStoreStorage.php#L660-L662

That means, the provided object store instance does not implement the given interface. But our default object store backend for s3 does implement it, and therefore we need to know which object store you are using?

**Comment by EchedeyLR** [comment]
I am using the native StorJ app in the store. Currently not able to link it here from mobile.

The issue doesn't happen in Nextcloud 25 and it does happen in Nextcloud 26 just in the web interface.

I am using the object store from its extension.

Related to the issue, I created it using the GitHub feature of creating an issue quoting other directly which didn't show me the default template.

I already reported the issue time before in another issue but it seems that got hidden because the original author had an issue with their web server config and was determined to not be the same.

**Comment by EchedeyLR** [comment]
I already filled it.

**Comment by kesselb** [comment]
https://apps.nextcloud.com/apps/storj is not released for Nextcloud 26. 

Please append the configuration report (don't forget to remove sensitive data). 
There should be a log record for the given error with additional information (e.g., a stack trace to know which path the code used).

**Comment by kesselb** [comment]
cc @juliushaertl 

ObjectStoreStorage implements IChunkedFileWrite and therefore provides startChunkedWrite, putChunkedWritePart, completeChunkedWrite and cancelChunkedWrite.  

But ObjectStoreStorage checks, if the concrect object store backend (Azure, S3 or Swift) implements IObjectStoreMultiPartUpload, which is only the case for S3.  

Isn't there something missing to route requests to the default chunking plugin if IObjectStoreMultiPartUpload is not implemented?

**Comment by EchedeyLR** [comment]
> https://apps.nextcloud.com/apps/storj is not released for Nextcloud 26.

I understand the implications but two things first:
* it doesn't fail with clients, just with the default web client
* you use "Not tested" instead of "Not supported" which is a confusing nomenclature. It seems to imply that upstream didn't report supporting or not that Nextcloud version, implying that feature support is not supported.

Given the first implication, I thought that the second was not something to be taken into account since StorJ (based on what I expected) should not be dependent on client support. If a client change is causing the issue and this affects the way files in background are uploaded, why is a plugin issue?

That was my first motivation to make the report. I apologize for the initial format and not re-checking the template. I tries to provide what I considered basic information (and failed on it).

If there is a scope issue of what should be from app upstream development and what Nextcloud upstream development, I would like to know as it is not very clear for me.

**Comment by kesselb** [comment]
Don't worry ;)

Thank you for your bug report. We have the required information now. 
 
The main point for reporting a bug is to provide a clear path how to reproduce a problem. This might be a stack trace (the best option when available) or a description. For UI bugs, screenshots are often helpful. The template is there to make it easier. Too bad it won't work in "Reference in new issue".

**Comment by EchedeyLR** [comment]
BTW, I forgot to mention that the error is not showed in screen to the user end in the web client. Just nothing happens.

I found the error while digging the error in real time and checking the log.

**Comment by EchedeyLR** [comment]
As far as I can see, this only adds a check to throw a previous exception to the error I have. (I would change the message or would integrate it with the previous statement creating a more complex one in the official code).

Would this fallback to the default chunked mode or how?

**Comment by kesselb** [comment]
> Would this fallback to the default chunked mode or how?

That's the plan, please let me know if it works for your setup as well. 
I updated the patch, to use a different error message.

**Comment by EchedeyLR** [comment]
@kesselb it is working as far as I could test.

Upload is now allowed from the web client.

Let me see it it finishes properly to confirm that there is nothing wrong.

**Comment by juliushaertl** [comment]
The patch seems reasonable. @kesselb Would you be up for opening a PR once confirmed?

**Comment by cpuch** [comment]
Hello, I'm facing the issue on Swift Object Storage. I'm trying to a upload a 530Mo ISO image from my web browser.

Let me know if you want more details

**Comment by cpuch** [comment]
Any updates on this issue with Swift object store ?

**Comment by kesselb** [comment]
Fixed in: 

Nextcloud 27.0.2
Nextcloud 26.0.5
