### ISSUE TITLE
More Data in Notification Mail

### ISSUE THREAD

**Issue by FlyingEagle** [nextcloud/server#39092]
Hi,

it would be nice to have the option to setup the amount of informations in the activity mail / push for an appointmant / calendar entry.

I want to have the link, like actual and adjustible more like date, time, place ...

Or is it right now adjustible and I am not able to find it?

Regards

**Comment by joshtrichards** [comment]
This Issue should get moved to https://github.com/nextcloud/activity

**Comment by joshtrichards** [comment]
Closing here as it's now being tracked over at nextcloud/activity#1252
