### ISSUE TITLE
NextCloud crashes because of __tostring

### ISSUE THREAD

**Issue by rugk** [nextcloud/server#3909]
### Steps to reproduce
1. It happened to me when doing these steps: https://help.nextcloud.com/t/users-encryption-key-is-never-generated/10083
2. So log in as a newly created user.

### Expected behaviour
Do not crash.

### Actual behaviour
Whole PHP-FPM crashes…

### Server configuration
**Operating system**: Debian 9

**Web server:** nginx

**PHP version:** PHP 7.0.16-3

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Signing status:** no errors

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - apporder: 0.3.3
  - audioplayer: 1.4.1
  - calendar: 1.5.1
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - deck: 0.1.1
  - direct_menu: 0.10.0
  - encryption: 1.4.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_automatedtagging: 1.1.1
  - files_markdown: 1.0.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - gpxedit: 0.0.4
  - gpxpod: 2.0.2
  - keeweb: 0.3.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - news: 10.1.0
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - ownpad: 0.5.7
  - passman: 2.1.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - richdocuments: 1.1.25
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.1.0
  - twofactor_u2f: 1.1.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - external
  - files_accesscontrol
  - files_downloadactivity
  - files_external
  - files_retention
  - ojsxc
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
nothing special, APCu+Redis used
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

#### Nextcloud log (data/nextcloud.log)
<details>
nothing related
</details>

### PHP/nginx log 

```
2017/03/18 […] [error] 28049#28049: *14758 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Couldn't find implementation for method ::__tostring in Unknown on line 0" while reading response header from upstream, client: […], server: […], request: "GET /nextcloud/logout?requesttoken=UCIUyx/[…] HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm[…]sock:", host: "[…]"
2017/03/18 […] [error] 28049#28049: *14758 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: […], server: […], request: "POST /nextcloud/settings/users/changepassword HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm[…]sock:", host: "[…]"
2017/03/18 […] [error] 28048#28048: *15006 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Couldn't find implementation for method ::__tostring in Unknown on line 0" while reading response header from upstream, client: […], server: […], request: "POST /nextcloud/login?user=ghut HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm[…]sock:", host: "[…]"
```

**Comment by MorrisJobke** [comment]
cc @schiessle

**Comment by ckorn** [comment]
It also happens when setting a password for a share with the Android app. I do not have encryption enabled in Nextcloud. I let apache handle the encryption with my own certs.

**Comment by rugk** [comment]
> I let apache handle the encryption with my own certs.

Arrgh, that's something completely different, but thanks for mentioning you have not enabled file encryption. In this case that's an even stranger error message…

**Comment by ckorn** [comment]
In bug 4019 you can see the error log from apache2. It also lists filenames and filenumbers. But on a quick look I do not see anything special. Maybe there is just a package missing I need to install on my Ubuntu cubieboard.

**Comment by rugk** [comment]
#4019 <-- you can link bugs on GitHub (just place a # before)

**Comment by rkkoszewski** [comment]
Same issue here. PHP 7.0.16-3 and Nginx on a Raspberry Pi. (Fresh install)
You seem to have the same PHP version as me. Maybe it has something to do with this.

**Comment by rkkoszewski** [comment]
Just in case it hasn't been discussed here: By going to **Admin** > **Additional** settings and unticking **Forbid common passwords** seems to fix the problem. It's a fresh Nextcloud install, so I haven't noticed the issue anywhere else still.

**Comment by ckorn** [comment]
@rkkoszewski Thanks, that also works when setting a password in the app.

**Comment by leonklingele-work** [comment]
Commenting here because I got the same issue as @rugk and after disabling __Forbid common passwords__ as described [here](https://github.com/nextcloud/server/issues/3909#issuecomment-295790740), I get these log messages:

```
2017/08/23 13:47:30 [error] 1890#0: *524 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Possible integer overflow in memory allocation (1 * 4294967287 + 104) in /usr/lib/nextcloud/www/lib/private/DB/Connection.php on line 386
PHP message: PHP Fatal error:  Possible integer overflow in number formatting (3 * 4294967295 + 10) in /usr/lib/nextcloud/www/lib/private/Log/File.php on line 86" while reading response header from upstream, client: 10.1.7.130, server: , request: "GET /apps/bruteforcesettings/ipwhitelist HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "spreedbox-dev-leon4"
2017/08/23 13:47:30 [error] 1888#0: *592 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Possible integer overflow in number formatting (3 * 4294967295 + 10) in /usr/lib/nextcloud/www/lib/private/Log/File.php on line 86
PHP message: PHP Fatal error:  Possible integer overflow in number formatting (3 * 4294967295 + 10) in /usr/lib/nextcloud/www/lib/private/Log/File.php on line 86" while reading response header from upstream, client: 10.1.7.130, server: , request: "GET /settings/ajax/checksetup HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "spreedbox-dev-leon4"
2017/08/23 13:47:30 [error] 1890#0: *527 FastCGI sent in stderr: "PHP message: PHP Notice:  Uninitialized string offset: 0 in /usr/lib/nextcloud/www/lib/base.php on line 164
```

Reloading PHP FPM (`service php7.0-fpm reload`) "solved" the issue.

**Comment by dennisheitmann** [comment]
`[Sat Sep 16 15:46:11.093599 2017] [:error] [pid 1095] [client 192.168.0.127:46928] PHP Fatal error:  Couldn't find implementation for method \x94\x11w\xa8r::__tostring in Unknown on line 0
[Sat Sep 16 15:46:11.158126 2017] [:error] [pid 2031] [client 192.168.0.127:46930] PHP Fatal error:  require_once(): \x8f\v\xb3\xd0\xcc\xd6u\xa8\xe8\xd6u\xa8\xa5\xb5\x02\x80\x06 in /var/www/owncloud/owncloud/lib/base.php on line 54`

**Comment by schiessle** [comment]
can't reproduce it. Feel free to re-open if this is still an issue with the latest version of Nextcloud
