### ISSUE TITLE
[Bug]: rich workspaces makes loading jumpy, which makes fast navigation impossible

### ISSUE THREAD

**Issue by JMoVS** [nextcloud/server#39090]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When rich workspaces are activated, them loading in and then displaying the content makes the position of the folders slightly jump around between initial loading spinner and final loading. As that takes more than a second very often, this is very frustrating if someone wants to navigate the folders fast.

### Steps to reproduce

1. Create some content in the Readme.md so that rich workspaces loads the content in
2. navigate to a folder that contains such a readme
3. While the content of the readme gets loaded in, observe that the placeholder area is of different size than the final area used to present the contents of the Readme

### Expected behavior

Reserve and fix a static amount of area for rich workspaces so that there is no difference in the vertical position of folders between start of loading and finished loading of the readme

### Installation method

None

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by rubenferreira97** [comment]
I feel this is a significant deal-breaker for the user experience and causes many users, including myself, to click on folders by mistake.

A user interface should not exhibit content jumping (https://css-tricks.com/content-jumping-avoid).

One solution, as @JMoVS suggested, is to ensure that asynchronously loading content maintains a static size. In this case, you could consider setting a fixed height for the rich workspace and making it scrollable or relocating the rich workspace away from the top.

**Comment by skjnldsv** [comment]
cc @juliushaertl

**Comment by juliushaertl** [comment]
We addressed this in https://github.com/nextcloud/text/pull/4776 for the upcoming Nextcloud 28, where we have all information ready at initial rendering time to reserve space only when needed.
