### ISSUE TITLE
Make groupIDs persistant

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#39107]
GroupIDs can be changed manually from user management interface. This may lead to certain ambiguities in the future, as some apps may refer to only one (elder or last) group name, but not both. That means, that the query may not be accurate. My suggestion is to make the groupIDs persistent and possibly numeric.

**Comment by joshtrichards** [comment]
groupIDs are persistent. Only the displayName is changed:

```
www-data@564eb1fd365d:~/html$ ./occ group:info blahdelete
  - groupID: blahdelete
  - displayName: blahdelete
  - backends:
    - Database
www-data@564eb1fd365d:~/html$ # go rename the group in the user interface from blahdelete to blahdeleteX
www-data@564eb1fd365d:~/html$ ./occ group:info blahdelete
  - groupID: blahdelete
  - displayName: blahdeleteX
  - backends:
    - Database
www-data@564eb1fd365d:~/html$ 
```

Apps should use the persistent groupID. Same idea as user_id.

**Comment by ostasevych** [comment]
> groupIDs are persistent. Only the displayName is changed:
> 
> ```
> www-data@564eb1fd365d:~/html$ ./occ group:info blahdelete
>   - groupID: blahdelete
>   - displayName: blahdelete
>   - backends:
>     - Database
> www-data@564eb1fd365d:~/html$ # go rename the group in the user interface from blahdelete to blahdeleteX
> www-data@564eb1fd365d:~/html$ ./occ group:info blahdelete
>   - groupID: blahdelete
>   - displayName: blahdeleteX
>   - backends:
>     - Database
> www-data@564eb1fd365d:~/html$ 
> ```
> 
> Apps should use the persistent groupID. Same idea as user_id.

What I see that the groupIDs are not numerical but symbolic, and non-latin characters may be used for their naming. Some apps may treat that incorrectly (one of my assumptions regarding fulltextsearch app and its indexing).
