### ISSUE TITLE
Provide web based VR experience for viewing panoramic photos

### ISSUE THREAD

**Issue by jdoxey** [nextcloud/server#39111]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Panoramic images look amazing in VR. It would be incredible to be able to experience panoraic images on Nextcloud Hub in an immersive web VR experience using the web browser on a headset like the Meta Quest.

**Describe alternatives you've considered**
Using a computer monitor... great, but not 3D ;)

**Additional context**
Some engineer would have an absolute blast implementing this. MVP doesn't have to be too sophisticated to still be amazing - maybe a [VR] button on your panoramic images.

**Comment by joshtrichards** [comment]
Issue probably belongs in [nextcloud/viewer](https://github.com/nextcloud/viewer).

**Comment by jdoxey** [comment]
Created new issue on nextcloud/viewer: https://github.com/nextcloud/viewer/issues/1780
Thanks @joshtrichards
