### ISSUE TITLE
Migrate `admin_audit` closure listeners to class listeners

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#39118]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

https://github.com/nextcloud/server/blob/b2f01b72fe402ca3ee8d0059ff266d1893d53d21/apps/admin_audit/lib/AppInfo/Application.php#L269-L279 uses a bunch of closure event listeners. They are heavier than class-based listeners only instantiated when a matching event is emitted.

This will also open the door for unit-testable event listeners.

### Steps to reproduce

1. Look at https://github.com/nextcloud/server/blob/b2f01b72fe402ca3ee8d0059ff266d1893d53d21/apps/admin_audit/lib/AppInfo/Application.php#L269-L279

### Expected behavior

Clean code

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

cc @luka-nextcloud @blizzz as app maintainers

**Comment by joshtrichards** [comment]
Gone/fixed now after #47865
