### ISSUE TITLE
[Bug]: Comment text input placeholder overflows in sidebar

### ISSUE THREAD

**Issue by ZetaTom** [nextcloud/server#39129]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When opening the *Comments* tab of any document in the Details sidebar, the placeholder message for submitting a new comment overflows the text entry field.

![image](https://github.com/nextcloud/server/assets/70907959/1cbcd668-e692-4110-8f44-2ae2929db3dc)

### Steps to reproduce

1. open Nextcloud web interface
2. select any file and open *Details*
3. switch to *Comments* tab

### Expected behavior

Placeholder text is contained within the text entry field.

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Operating system: Arch Linux
Browser name: Firefox (Flatpak from Flathub)
Browser version: 114.0.2

**Comment by tiredofit** [comment]
I can also see this occurs in 26.0.4

**Comment by marcelklehr** [comment]
Fixed in latest master. 
![image](https://github.com/nextcloud/server/assets/986878/3dfc4f4a-ece0-41ff-9723-e657d7ade13a)
