### ISSUE TITLE
Adding CSP Header [Bug]: 

### ISSUE THREAD

**Issue by HomemadeAdvanced** [nextcloud/server#39121]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I loaded have implemented the official security headers into my nextcloud instance. I have scanned the instance with the mozilla tool from Mozilla https://observatory.mozilla.org/.

The tool recommends to set a header for CSP. So I have implemented one like this:
add_header Content-Security-Policy "default-src 'self'; font-src *;img-src * data:; script-src *; style-src *";

The problem is that the fonts seem to be not implemented into my instance anymore. What should I change to set this header but in the right way. Maybe it could be implemented in the official documentation if necessary.

### Steps to reproduce

1. Implenment header into config: add_header Content-Security-Policy "default-src 'self'; font-src *;img-src * data:; script-src *; style-src *";
2. Result: Weird looking website without fonts.

### Expected behavior

The cloud website should look normal.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

We set the csp header in Nextcloud and assume that you don't overwrite it in the webserver.

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

**Comment by HomemadeAdvanced** [comment]
Allright thanks.

I have implemented it like this now:

`add_header Content-Security-Policy "form-action 'self' https://mydomain.com";`

**Comment by HomemadeAdvanced** [comment]
Thanks for answering but every nextcloud instance that I have checked has not set this up. Correct me if I am wrong.

**Comment by joshtrichards** [comment]
Then there is either something configured improperly with those instances or that tool.
 
You didn't provide the exact output you're seeing from that third-party tool, but running it against `https://cloud.nextcloud.com` there is definitely a CSP header:

https://observatory.mozilla.org/analyze/cloud.nextcloud.com

You can also manually check your own server by checking your browser console or using `curl -k <yourURL>` from the command line.
