### ISSUE TITLE
Update Nextcloud - right permissions

### ISSUE THREAD

**Issue by emillod** [nextcloud/server#3912]
Hello. I want to update my Nextcloud in production and update require from me to change permissions. I want to know how to setup right permissions after update to secure my nextcloud.

I'm using Nextcloud on Centos 7 with apache and SSL

**Comment by benediktg** [comment]
I'm using two bash scripts based on [these](https://docs.nextcloud.com/server/11/admin_manual/installation/installation_wizard.html#strong-perms-label) [entries](https://docs.nextcloud.com/server/11/admin_manual/maintenance/update.html#set-updating-permissions-label) in the docs:
[make-nextcloud-updatable.txt](https://github.com/nextcloud/server/files/852766/make-nextcloud-updatable.txt)
[make-nextcloud-secure.txt](https://github.com/nextcloud/server/files/852767/make-nextcloud-secure.txt)
