### ISSUE TITLE
Make persistent versioning available even with groupfolders being activated

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#39137]
* Provide persistent versioning even with groupfolders being activated, yet just as is for non-groupfolders
* might be covered via groupfolders support [#39138](https://github.com/nextcloud/server/issues/39138)

**Comment by artonge** [comment]
- [x] Master: https://github.com/nextcloud/server/pull/39165
- [ ] Stable27: https://github.com/nextcloud/server/pull/39265
