### ISSUE TITLE
Compare 2 versions of a file

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#39140]
Provide an option to compare 2 versions of a file by marking them and opening both side-by-side in some kind of a "dual-pane", so the user can scroll both to visually compare them.

**Comment by AndyScherzinger** [comment]
The idea is to just display 2 versions next to each other for the ones where we have a viewer available.
Like with viewing the version see https://github.com/nextcloud/server/issues/39139 any version should be read-only except for the current version

**Comment by jancborchardt** [comment]
@nextcloud/designers it would be good to have a mockup for this, how to select the 2 versions and compare them. :)

**Comment by marcoambrosini** [comment]
I'm taking this on :) 

The requirements are not very clear from the issue so can we formulate a problem statement for this feature? What is the goal? Is the comparison of the two files oriented at picking one of the two? 

Is it only for text files or also for other files like spreadsheets, pictures, videos and so on?

**Comment by jancborchardt** [comment]
@marcoambrosini it would be a very simple side-by side comparison of 2 documents.

To keep it simple:
- It is only possible to pick one version to compare to the current one. This would be done by an action menu entry "Compare version"
- It is a side-by-side view, no diff or anything like that. The current version is on the right.
- Changes can be made only to the current version, the other document is read-only.
- We will just not make this possible on mobile, the option to "Compare version" will just open the version, as if you clicked on the name.
- The individual views side-by-side could have individual x-close buttons, which would then lead to the other side taking back the whole width.

@artonge do you need mockups beyond this?

**Comment by juliushaertl** [comment]
No further input needed for now from the design side I think. 

@skjnldsv This would require us to have some sort of API to trigger a side-by-side rendering in viewer. My suggestion also considering the short time available would be to simply add an optional parameter to pass a second file info object:

```
OCA.Viewer.open({
	fileInfo: currentFileInfo,
	fileInfoCompare: versionFileInfo,
})
```

This would align with the work already done in https://github.com/nextcloud/server/pull/39171/files#diff-8c16136a0fe1baf1357890af01439aebe1da2380f96f80afb1eab039157311b8R191-R198

Any concerns or objections on that?

**Comment by skjnldsv** [comment]
I'm actually not sure about this.
I think this is not the job of the Viewer, no?

Any other app would benefit from this feature otherwise?
Aside from Text?

**Comment by juliushaertl** [comment]
> Any other app would benefit from this feature otherwise?
> Aside from Text?
> If this is about making it possible to view ANY file in the viewer as side-to-side, sure, then we need it in Viewer. WHile than can be really messy and the layout needs to be updated.

Yes, Collabora, ONLYOFFICE, files_pdfviewer would be obvious others, for image files I'd also consider it useful. But I agree that we probably want to exclude audio/video files for now.

Handling mobile view has been discussed above as that we just not show the split view then but switch to the single version view. Slideshow should probably  just hide the split view and move to the next file. As a user you would need to pick a new version from the sidebar then anyways to compare to.

Moving this to text or other apps seems likes adding a lot of complexity there for what is now a "simple" component to just render a file and would also mean to duplicate a lot of effort bringing this to more apps.

**Comment by AndyScherzinger** [comment]
Anything but the current version shall always be read-only according to Frank and Jan (and I agree). If the current version could be editable (given the user has the permissions) would be a plus. So MVP can be read-only for everything.

**Comment by juliushaertl** [comment]
Relevant PRs currently in draft
- https://github.com/nextcloud/server/pull/39171
- https://github.com/nextcloud/viewer/pull/1835
- https://github.com/nextcloud/files_pdfviewer/pull/791
- https://github.com/nextcloud/text/pull/2832

**Comment by jancborchardt** [comment]
Super nice @juliushaertl! I would say that's awesome for the MVP!
