### ISSUE TITLE
Can't create a new user from iOS Safari

### ISSUE THREAD

**Issue by scottbroadway** [nextcloud/server#3916]
### Steps to reproduce
1. Use mobile Safari on iOS
2. Log in as an admin
3. Go to "Users"
4. Enter username, password, and email address
5. Click "Create" button [which is unacceptably far to the right and totally unable to reach from a mobile UI] 
6. Nothing happens 

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by benediktg** [comment]
Maybe the password you chose was too weak? – see also #3914 for that.

**Comment by tflidd** [comment]
Can't we tell the user that the password is too weak? You can't tell if the software has a bug, if the network connection is bad, ...

**Comment by scottbroadway** [comment]
There is no visual indicator that the password does not meet complexity requirements. If that's the problem, then that's the bug. It's already near impossible to create a user on a mobile screen anyway due to the extreme width and unresponsive section to add a user.

**Comment by nickvergessen** [comment]
Do you have the password policy app installed?

**Comment by benediktg** [comment]
@scottbroadway Are you using nginx – this could be a possible fix: https://github.com/nextcloud/server/issues/3847#issuecomment-287740126

(worked for me)

**Comment by nickvergessen** [comment]
Closing as duplicate
