### ISSUE TITLE
[Bug]:  nc upgrade 25/26 can't disable maintenance mode

### ISSUE THREAD

**Issue by DeepReef11** [nextcloud/server#39172]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Upgrade to 26 stuck in maintenance mode

### Steps to reproduce

1. Update from browser

### Expected behavior

Stop maintenance mode

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Hi @DeepReef11  - Thanks for your report and participating in the community. From the sounds of it, this is likely a configuration/installation issue. This a channel for submitting bugs and enhancement reports to the developers about the software itself. Unfortunately, this isn't a general support forum so you won't necessarily get a direct response.

Your query would be better suited for the [Nextcloud Help Forum](https://help.nextcloud.com) where you're more likely to receive assistance. I encourage you to post over there and close this Issue out.

**Comment by DeepReef11** [comment]
Ok, thank you

**Comment by kesselb** [comment]
https://help.nextcloud.com/t/freebsd-updated-nextcloud-to-26-cant-turn-off-maintenance-mode/165604
