### ISSUE TITLE
File picker: use same sort order as in the main Files view

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#39185]

**Comment by AndyScherzinger** [comment]
@jancborchardt @nimishavijay regarding the sorting. Given the headline, the sorting shall always be matching the main Files view? This is fine for starters I guess. In a future iteration we could also discuss if we have sorting options in the picker and they are persisted and whenever a user changed the sorting in the picker then from that moment on that value will be used indefinitely.

**Comment by jancborchardt** [comment]
Yep @AndyScherzinger, exactly how I would say we should cut it into 2 steps, with the automatic sorting takeover being simplest.
