### ISSUE TITLE
share dialog broken

### ISSUE THREAD

**Issue by jknockaert** [nextcloud/server#3918]
When trying to share a file or a folder using the share dialogue I cannot select any users to share with.

What should happen: while typing the name of a user the autocompete feature should present a dropdown menu with matching user names.

What does happen: not much. No dropdown is shown. Only when the string entered does not match a user name a popup is shown saying "No users or groups found for daeffsfbsf" (provided that you enterred daeffsfbsf and there's no such user).

The interaction between the client (the browser) and the server seems to go fine. While typing calls are made to ocs/v1.php/apps/files_sharing/api/v1/sharees?format=json&search=daeffsfbsf&perPage=200&itemType=folder and the server responds properly (a json with any matching users). It seems to go wrong where the client has to display the returned usernames.

Tested with firefox and safari. Using php 7 on the server.

**Comment by sjash** [comment]
I solved it.
If you have **'enable_avatars' => false**
in your config.php it will not pop-up the name of users. if you set it to true it will.

Thanks...

**Comment by jknockaert** [comment]
Confirmed as a workaround. @sjash Good find, thanks!

**Comment by LukasReschke** [comment]
This has config switch has been removed from master and thus 12.0 will have a fixed behaviour: https://github.com/nextcloud/server/pull/3472
