### ISSUE TITLE
[Bug]: limit avaiable apps from the appstore broken

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#39197]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I added `'appsallowlist' => ['groupfolders', 'user_oidc'],` to my config.php to limit the list of available apps from the appstore but could still see all apps from the app store 

![image](https://github.com/nextcloud-gmbh/portal.nextcloud.com/assets/1589737/e81899c5-2fcf-4246-a120-f2ccb7a9b8bf)

... and install them

![image](https://github.com/nextcloud-gmbh/portal.nextcloud.com/assets/1589737/f2636605-323a-407f-9cba-415e00cadf90)

Did I missed something in the documentation (maybe a additional setting) or is there a bug in the implementation?

### Steps to reproduce

1. set  `'appsallowlist'` in the config.php
2. go to the app management

### Expected behavior

only the apps listed in the config .php setting are shown and can be installed

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/blob/b2f01b72fe402ca3ee8d0059ff266d1893d53d21/lib/private/App/AppStore/Fetcher/AppFetcher.php#L184-L198

**Comment by schiessle** [comment]
seems to be the intended behaviour.

**Comment by AndyScherzinger** [comment]
Just for understanding the matter since it got raised and closed without changes the same day.

What has been the point? 🤔 @schiessle?

**Comment by schiessle** [comment]
I thought it was broken because it didn't worked for me, but it turned out that by design it only works with a subscriptions key. I tested without a subscription key.

So everything works as intended.
