### ISSUE TITLE
Avatar and caret misaligned 

### ISSUE THREAD

**Issue by michaelletzgus** [nextcloud/server#3920]
User avatar and the drop down caret are misaligned in current master.

Problem (Firefox, Chromium):
![nc-old-pic](https://cloud.githubusercontent.com/assets/1718822/24081627/d1e9400c-0cb7-11e7-9160-2cadaf02dac6.png)

![nc-old-pic_model](https://cloud.githubusercontent.com/assets/1718822/24081628/d1ef33a4-0cb7-11e7-8b11-7abef9d596d4.png)

Fixed:
![nc-new-pic](https://cloud.githubusercontent.com/assets/1718822/24081626/d1e00e60-0cb7-11e7-9ce7-f20cb1d95b34.png)

PR: #3919

**Comment by MorrisJobke** [comment]
Fix is in #3919
