### ISSUE TITLE
Firefox: Icons invisible in app menu

### ISSUE THREAD

**Issue by michaelletzgus** [nextcloud/server#3921]
Icons in the new app menu (nc12, current master) are invisible when using latest (52) Firefox@Linux:

![nc-app-menu](https://cloud.githubusercontent.com/assets/1718822/24082216/11d79f38-0cc2-11e7-9f28-fcd097fa20b9.png)

Chromium works well.

**Comment by MorrisJobke** [comment]
cc @juliushaertl

**Comment by juliushaertl** [comment]
Fix is in #3951 
Please test @michaelletzgus

**Comment by michaelletzgus** [comment]
#3951 fixed it.
