### ISSUE TITLE
Integrate scan.netcloud.com warnings into NC admin warnings

### ISSUE THREAD

**Issue by Bugsbane** [nextcloud/server#3922]
Currently we check some things and warn about them in the admin warnings on setting up. We also scan for other server security issues when requested via scan.nextcloud.com.

What would be ideal would be if scan.nextcloud.com was queried for issues automatically on installing / upgrading Nextcloud and any issues were then reported, as we already do, in the admin messages.

This would warn huge numbers of people about vulnerabilities that they are currently unaware of, boosting security and privacy for many of our users. Possibly a small number of people want to run Nextcloud without any outside party (including Nextcloud) knowing though. For them we could make it an install option that is on by default, but clearly visible and easily switched off. For example:

- [x] Get scan.Nextcloud.com to check for basic security problems

Now, I understand that Jan (rightly) prefers to minimize user facing options. In this case though, it's only one checkbox being shown to the one admin installing / upgrading the instance, and only at the time that they're installing/upgrading when we're already asking for far more technical info such as their database type etc. After that, it could be kept invisibly saved in the config file, just like the database type, password etc.

For normal users, none of this would ever be visible, but the security (and thus privacy) benefits of having admins know about server security issues automatically could be huge.

**Comment by MariusBluem** [comment]
https://github.com/nextcloud/server/issues/3735 and a first approach over here #3755 😁

**Comment by Bugsbane** [comment]
Nice! I can't believe I missed that! I think I only looked for open tickets (didn't guess it already would have been implemented before I even wrote the ticket!).

Great work all. Move along.... ;P
