### ISSUE TITLE
[Bug]: Emtpy Templates folder is created even with 'templatedirectory' => ''

### ISSUE THREAD

**Issue by deiansp** [nextcloud/server#39227]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi,

I'm using a custom skeleton folder. In my config file, I have:
```
'skeletondirectory' => '/home/nextcloud/skeleton',
'templatedirectory' => '',
```
When new users are created, they receive by default the files from the above skeleton folder.
But in addition, they receive also an empty folder called "Templates".

This "Templates" folder is not in my skeleton folder and the users should not have it by default.
I've tried all these options (with the same result):
```
'templatedirectory' => '',
'templatedirectory' => ' ',
'templatedirectory' => NULL,
'templatedirectory' => false,
// 'templatedirectory' => '',
```

### Steps to reproduce

1. Add in the config file `'templatedirectory' => '',`
2. Create a new user
3. Login as this user and you'll see an empty "Templates" folder

### Expected behavior

The user should not see an empty "Templates" folder if `'templatedirectory' => '',` is set in the config file.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

27

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by deiansp** [comment]
The previous discussion was here: [#27890](https://github.com/nextcloud/server/issues/27890)
The problem still exists in 27.

**Comment by mcmara** [comment]
Confirming this bug. Note that if the configuration file contains only this line:

`'skeletondirectory' => '',`

then the "Templates" folder is **not** being created. 
Instead, if `skeletondirectory` is set to something such as:

`'skeletondirectory' => '/www/data/iros-2023/skeleton',`

then the empty "Templates" folder appears. Third case:

```
'skeletondirectory' => '/www/data/iros-2023/skeleton',
'templatedirectory' => '',
```

also the empty "Templates" folder is being created.

**Comment by szaimen** [comment]
cc @nextcloud/server-backend

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/blob/0d78334c7d29b8df5e9babe824febcbeec655723/config/config.sample.php#L256-L268

**Comment by deiansp** [comment]
I have created a feature request: #39266
Thank you!

**Comment by x-merlin-x** [comment]
> I have created a feature request: #39266 Thank you!

Appreciated, however this looks more like a bug to me. Or is there any use to this folder? What if the skeleton folder contains a directory with the same name because somebody wants to ship file templates during account creation?
This behaviour is confusing.

**Comment by AndrinS** [comment]
The order of those two parameter seem to play a role.

```
'skeletondirectory' => '/www/data/iros-2023/skeleton',
'templatedirectory' => '',
```
_Template folder is created._

```
'templatedirectory' => '',
'skeletondirectory' => '/www/data/iros-2023/skeleton',
```
_Template folder is **not** created._

**Comment by come-nc** [comment]
It is highly unlikely that the order of the parameters in the array change anything.

**Comment by 31337** [comment]
> It is highly unlikely that the order of the parameters in the array change anything.

I can confirm that AndrinS's statement is true. Tested with Nextcloud 30.0.1 running in Docker.

**Comment by joshtrichards** [comment]
@31337 My best guess is your testing is running up against php opcache caching. In our micro-services image, for example, the cache revalidation time is every 60 seconds. So on-disk config changes don't take effect immediately. 

If you want to know with certainty,  restart the app container after each change.
