### ISSUE TITLE
[Bug]: occ theming:config background backgroundColor as per documentation doesnt work anymore

### ISSUE THREAD

**Issue by ne0YT** [nextcloud/server#39230]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

occ theming:config background backgroundColor as per documentation doesnt work anymore:
The image file needs to be provided as an absolute path: backgroundColor

docs tell me it should work:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/theming.html

### Steps to reproduce

1. run occ theming:config background backgroundColor

### Expected behavior

it should remove the background image

### Installation method

Community SNAP package

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment]
Documentation for 26: https://docs.nextcloud.com/server/26/admin_manual/configuration_server/theming.html

The feature `occ theming:config background backgroundColor` is available from Nexcloud 28.
