### ISSUE TITLE
Read Env variables to configure Nextcloud

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/server#3926]
https://12factor.net/ are recommendations for modern applications.

I tried to look though the documentation, and didn't find much about it.

Does Nextcloud read env variables? If yes, which?
And finally, would it be possible to make it read all config from env?
This would help a lot in a context of a docker cluster for instance.
And this would avoid such file and ease docker images: 
https://github.com/Wonderfall/dockerfiles/blob/master/nextcloud/11.0/setup.sh

**Comment by MorrisJobke** [comment]
@karlitschek @rullzer @nickvergessen @LukasReschke Do we want this? That would mean to downstream this: https://github.com/owncloud/core/pull/26570

Would that make sense?

**Comment by karlitschek** [comment]
i think it is a useful feature.

**Comment by MorrisJobke** [comment]
Fix is in #3966
