### ISSUE TITLE
iOS contacts can't set default _list_

### ISSUE THREAD

**Issue by patzm** [nextcloud/server#39300]
### Setting
I am using iOS 16.5.1 with CalDAV set up for my NextCloud instance. The NC instance has multiple _Contact Groups_. On iOS, these _Contact Groups_ translate to _lists_ (iOS lingo). See the following screenshot:

To avoid confusion: It is possible to set the default _account_ in the iOS settings by navigating _Settings_ `>` _Contacts_ `>` _Default account_. However, it is not possible to set the default _list_ / _Contacts Group_.

### Problem
New contacts are always being added to one group, but not the main _All Contacts_ group. Now you may ask: why open an issue in `nextcloud/server`? Well, I don't think iOS will magically and easily change. So I think it makes sense to first understand whether some server settings / code affect the default contact placement.

### NextCloud
[Nextcloud Hub 5](https://nextcloud.com/) (27.0.0)
Docker compose stack [link](https://github.com/patzm/dockerfiles/tree/master/nextcloud). 

### Reference
             I think what the original author meant is: even though you can set the default _account_ on iOS, you can set the default _list_.

How to set the default account: settings -> contacts -> Default account.

How to do the same for the lists? You can see all list in the contacts app and then click _Lists_ in the upper right.

Is this clearer now @szaimen?

_Originally posted by @patzm in https://github.com/nextcloud/server/issues/24352#issuecomment-1625252566_

**Comment by szaimen** [comment]
Hi, please create a new issue using this template: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&projects=&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
