### ISSUE TITLE
[Bug]: When the name of a shared file is changed, it is not the same for all recipients

### ISSUE THREAD

**Issue by fgapeters** [nextcloud/server#39311]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

For example, User X shares a file with user Y. After sharing the file User X changes the name of the file. This change is not visible for user Y and causes a lot of confusion to our users. 

They complain that when the name of a shared file is changed, it is not the same for all recipients; the recipients still see the old name. So then there is 1 file with different names. This is very confusing.

### Steps to reproduce

1. Share a file or folder
2. Change the name of the shared file or folder and note that this is not changed for the recipient(s) 

### Expected behavior

If a shared file is renamed (by the owner) than the new name should also be visisble to the recipient.

### Installation method

Other Community project

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
This is expected. Use Groupfolders app if you wish to share files and folders and keeps names, have ACLs and more.
https://github.com/nextcloud/groupfolders

**Comment by come-nc** [comment]
This is expected. Each user can name a shared resource as they wish.
If you share the parent folder, then renamed files will be renamed for all who have access to them.
