### ISSUE TITLE
[Bug]: lookup.nextcloud.com IPv4 is blocked by Hetzner

### ISSUE THREAD

**Issue by hidrarga** [nextcloud/server#39338]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I made an issue (https://github.com/nextcloud/lookup-server/issues/130) in the lookup-server repository, but I got no answer from the maintainers :/

I noticed that the IPv4 of lookup.nextcloud.com is blocked by Hetzner, as you can see in the traceroute:
```
traceroute to lookup.nextcloud.com (176.9.217.60), 30 hops max, 60 byte packets
 1  _gateway (192.168.35.1)  1.071 ms  1.443 ms  1.835 ms
 2  bras-02str.bxl.be.edpnet.net (213.219.132.31)  20.538 ms  20.579 ms  20.629 ms
 3  router02.bruix.be.edpnet.net (212.71.11.53)  20.878 ms  20.860 ms  20.844 ms
 4  router01.adamtel.nl.edpnet.net (212.71.11.114)  21.437 ms router02.bruix.be.edpnet.net (212.71.11.126)  21.167 ms router01.adamtel.nl.edpnet.net (212.71.1.70)  22.390 ms
 5  decix2-gw.hetzner.com (80.81.193.164)  29.515 ms router01.adamtel.nl.edpnet.net (212.71.11.222)  23.589 ms router01.adamtel.nl.edpnet.net (212.71.11.177)  23.187 ms
 6  decix2-gw.hetzner.com (80.81.193.164)  36.180 ms  35.228 ms core24.fsn1.hetzner.com (213.239.224.89)  48.393 ms
 7  core23.fsn1.hetzner.com (213.239.224.73)  48.110 ms core24.fsn1.hetzner.com (213.239.224.89)  22.418 ms core23.fsn1.hetzner.com (213.239.224.73)  23.476 ms
 8  * * *
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
14  blocked.hetzner.com (88.198.255.174)  4284.932 ms !X  4292.992 ms !X *
```

However, the server is reachable in IPv6, so this is an issue only for Nextcloud servers that don't have IPv6 enabled.

Could you contact Hetzner to ask them to unblock the IP ?
This is slowing down the Nextcloud cron job.

### Steps to reproduce

1. Try to reach the server in IPv4: `curl -4  lookup.nextcloud.com`
2. Get a timeout error

### Expected behavior

lookup.nextcloud.com is reachable in IPv4

### Installation method

None

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment]
cc @nextcloud/infrastructure

**Comment by hidrarga** [comment]
Unfortunately, lookup.nextcloud.com is still blocked for me. Could you give us some feedback about this issue? Thanks!
