### ISSUE TITLE
Add folder version control

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#39388]
Hi! I am looking for the folders versioning functionality similar to the files do have.

My goal is to recover the state of some folder to the previous one, so just a user may click on "Details", see the versions of the folder and be able to revert all the data contained in the folder (sub-folders, files) to one of the previous states.

In fact the folders will be like a snapshots of data on a particular time.

**Comment by TristanCottam** [comment]
Duplicate of #7473.
