### ISSUE TITLE
[Bug]: Even if SMTP is configured correctly, it will lead to the test fail

### ISSUE THREAD

**Issue by flyhunterl** [nextcloud/server#39404]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

27.0.0
Email Server
encryption → SSL/TLS and port 587
Even if smtp is configured correctly, it will lead to the test faild
In order to pass the test normally Config.php must be revised.
'mail_smtpsecure' => 'tls'
the old version did not have this problem.

### Steps to reproduce

1.Email Server
2.encryption → SSL/TLS and port 587
3.test

### Expected behavior

cheak it

### Installation method

None

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Hi @flyhunterl - Thanks for the report. Can you provide, at a minimum, the output of `./occ config:list system` as requested in the bug report form?

**Comment by flyhunterl** [comment]
> Hi @flyhunterl - Thanks for the report. Can you provide, at a minimum, the output of `./occ config:list system` as requested in the bug report form?

![IMG_20230715_233016.jpg](https://github.com/nextcloud/server/assets/48502470/5af5e584-2511-4377-b141-f7fedaafabcf)

**Comment by flyhunterl** [comment]
> Hi @flyhunterl - Thanks for the report. Can you provide, at a minimum, the output of `./occ config:list system` as requested in the bug report form?

![IMG_20230715_233147.jpg](https://github.com/nextcloud/server/assets/48502470/62ad5ce3-54c8-40d8-a878-369d5f8d2c3f)

**Comment by flyhunterl** [comment]
> Hi @flyhunterl - Thanks for the report. Can you provide, at a minimum, the output of `./occ config:list system` as requested in the bug report form?
> 
> Update: `tls` isn't a valid parameter so I think something else is going on here. It took me a moment to find the PR I was looking for, but #38868 (via #38885 for NC27) cleans up the user interface a bit (pending the next NC27 patch release). Without seeing your config, my best guess is you actually want STARTTLS.

yes I want  STARTTLS  I set this with reference to another project's config, which solved the problem of not being able to send mail.

**Comment by kesselb** [comment]
Remove `mail_smtpsecure` from your configuration file. 
If client and server are compatible, they will use starttls.
