### ISSUE TITLE
[Bug]: Basic Authentication Bypass due to Lack of Rate Limit

### ISSUE THREAD

**Issue by haneefFathani** [nextcloud/server#39410]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi Team,
I hope you are doing well.

Vulnerable URL :- https://nxtcld.abc.com/remote.php/dav/calendars/at3@gmail.com/app-generated--deck--board-5269/
Steps to Reproduce :- 1. Login --> Go to Tasks.
2. Copy private Link.
3. It looks like :- https://nxtcld.abc.com/remote.php/dav/calendars/at3@gmail.com/app-generated--deck--board-5269/
4. Open it in other browser .
5. It asks for username and password .
6. Username/email is in URL , enter same and for password enter random password.
7. Capture this request in burp suite.
8. There is an Auth header --> copy there value and see it's b64 encoded --> decode it --> create payloads of password and encode it as b64.
9. Send to intruder and select that position and paste the payload list.
10. Click on start attack and Boom! after few mins it got bypassed with Response code 200.
Impact
Basic Authentication Bypass.
Full Account takeover because attacker can easily know the password through here because of brute forcing as no rate limit is there.

### Steps to reproduce

1. Go to the URL https://nextcloudshare.abc.com/remote.php/webdav
2.It asks for username and password  in pop up
3.Username/email is in URL , enter same and for password enter random password.
4. Capture this request in burp suite.
5. There is an Auth header --> copy there value and see it's b64 encoded --> decode it --> create payloads of password and encode it as b64.
6. Send to intruder and select that position and paste the payload list.
7. Click on start attack and Boom! after few mins it got bypassed with Response code 200.

### Expected behavior

It shall not ask for popup, or secure the headers 

### Installation method

None

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
See https://github.com/nextcloud/server/pull/38046

**Comment by solracsf** [comment]
Please go to https://hackerone.com/nextcloud if you believe this isn't fixed by https://github.com/nextcloud/server/pull/38046
