### ISSUE TITLE
[BITV]: Not possible to navigate the tabs in sidebar

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#39415]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

It have to be possible to navigate through all tabs with keyboard arrows. For now it is only possible to navigate to to the first neighbor tab on the left or the right side and then focus goes to the photos slider and navigation goes only through images, not on tabs as it should. 

### Steps to reproduce

1. Go to files view
2. Open any image and click to "open sidebar"
3. Go to the tabs navigation (activity, comments, sharing)
4. Try to navigate with keyboard arrows

### Expected behavior

It is possible to navigate with keyboard arrows

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment]
Cc @nextcloud/server-frontend

**Comment by ShGKme** [comment]
Additional info:

Keyboard navigation in tabs themself works and follows https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs-1/tabs.html . It works in files without viewer.

But it doesn't work in files opened in Viewer because `NcModal` intercepts arrow navigation.

I think, we can check current focus element in NcModal and handle arrow navigation, only then the focus is inside modal.

**Comment by ShGKme** [comment]
Arrow navigation is fixed, but there is still a problem with ESC, e.g. from open select or picker
