### ISSUE TITLE
[Bug]: Some buttons are invisible in Google Chrome accross different Nextcloud apps.

### ISSUE THREAD

**Issue by YoannPa** [nextcloud/server#39440]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

This is a very general display bug, I have no idea where I should post it, so I posted it here.
On the user side, using Google Chrome, some buttons on the interface of various apps are simply invisible.
The bug happens independently from the theme selection in the user's parameters : dark or light or high contrast.
Using the same computer, same OS, but in Firefox, buttons are all perfectly visible. So the bug seems to be specific of Google Chrome.

Apps for which I notice the bug are the following:

- Files: button on the left to open/close left lateral panel is invisible. And the button to close the right lateral "Details" panel is also invisible.
![Capture_nextcloud_files](https://github.com/nextcloud/server/assets/12813932/a2ee6ed6-8356-49b8-a229-e755c77802aa)
- Image viewer: the "..." button on the top right corner of the viewer is invisible.
![Capture_nextcloud_image_file_viewer](https://github.com/nextcloud/server/assets/12813932/117319ee-0b4d-4b6a-8281-d5d20f8d17e8)
- Talks: the "+" button to create a conversation is invisible.
![Capture_nextcloud_talks](https://github.com/nextcloud/server/assets/12813932/0f920acd-7757-44a6-96d7-d01e7d367513)
- Text editor: the "✓" button to save modifications made is invisible.
![Capture_nextcloud_text_editor](https://github.com/nextcloud/server/assets/12813932/78dc5b51-c11d-4d54-a899-c2b414e2bcd1)
- Calendar: in the left lateral panel, arrows buttons to navigates to previous or next week are invisible.  The calendar format button (that allows to select between day, week, month or list) is also invisible. Here below I produced 3 screen capture showing the bug persists independently from the different themes Dark, Light Default, Light High Contrast.
![capture_nextcloud_calendar](https://github.com/nextcloud/server/assets/12813932/54482077-564d-40dd-8212-aa1d0d21398b)
![capture_nextcloud_calendar_dflt_light](https://github.com/nextcloud/server/assets/12813932/9ad1394a-13ec-4145-8753-708c397868c2)
![capture_nextcloud_calendar_high_contrast_light](https://github.com/nextcloud/server/assets/12813932/c416da12-e510-42f0-9728-eb4b44ed07f1)

### Steps to reproduce

The bug happens in this case:

**OS: Windows 10 Family
Version: 22h2
Build: 19045.3208
Web Browser: Google Chrome
Version 114.0.5735.199 (Build officiel) (64 bits)**
Activated addons in Google Chrome are: **Ublock Origins** and **Add Block Plus**.

The bug does **not** happen on the same computer, but when using Firefox Version 115.0.2 (64 bits)

So to reproduce the bug, try using Google Chrome on Windows 10 Family and to visit the different nextcloud apps: Files, the Image viewer, Talks, the Textfile editor, Calendar.
**Nextcloud server version: 26.0.3**
The Nextcloud Server has been **installed with Snap.**

### Expected behavior

Invisible buttons listed above should be visible.

### Installation method

Community SNAP package

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment]
Hi, can you clear your browser cache or try with a different browser and check if this helps?

**Comment by joshtrichards** [comment]
Hi @YoannPa: I attempted to reproduce this on a Win 10 workstation running the same Chrome version and I'm unable to do so. For completeness I even changed by background color to the same as that in your screenshots. I too am using uBlock Origin on that workstation (but not the other extension you mentioned).

Maybe try it without Ad Block Plus. Or check what rules (beyond the defaults) you have enabled in either uBlock or Ad Block Plus. Both extensions should indicate if they're filtering something on the page you're on. (Neither should be filtering anything on a typical Nextcloud installation).

After doing so, if you would like us to double-check it's not a bug, can you edit your original report and fill out sections you skipped? Your code integrity (signing) status, config, and installed apps are important bits of information to include.

From my end, this appears to be a configuration or local environment issue. I suggest posting about it on the [Nextcloud Help Forum](https://help.nextcloud.com) if you're unable to resolve it.

**Comment by YoannPa** [comment]
@szaimen @joshtrichards I am so sorry I wasted your time with that: the problem was actually caused by the [Adblock Plus addon](https://chrome.google.com/webstore/detail/adblock-plus-free-ad-bloc/cfhdojbkjhnklbpkdaibdccddilifddb?hl=fr) !
I thought I checked that, but obviously I did not.
Sorry for that. I am closing this.
