### ISSUE TITLE
[Bug]: Can't add new groups

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/server#39469]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I tried to a new user group but it's not being created.

### Steps to reproduce

1. Call example.com/settings/users
2. Click "add group" (deu: "Gruppe hinzufügen")
3. Type in a name e.g. "Test"
4. Click the arrow to confirm
5. Nothing

### Expected behavior

I expected the new group to appear under the list of groups.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

PHP 8.1

### Web server

None

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kaffeeringe** [comment]
This error occurs on two totally different servers.

**Comment by szaimen** [comment]
This will be solved with 27.0.1
