### ISSUE TITLE
Email reporting to security scanner

### ISSUE THREAD

**Issue by burner-** [nextcloud/server#39479]
https://scan.nextcloud.com/ offer great way to check installation. I suggest to add feature what allow admin to register automated checks so that if rating change it will send email to given address of that change. As security view point it will ge good to use some kind token authentication at registration so that it is not possible to register automatic check to instance what user does not own. Even it is possible to do manual check for other instances.

**Comment by szaimen** [comment]
This will likely not happen because it would need an automated scanning which is not implemented and also not permitted by law afaik.

**Comment by szaimen** [comment]
Cc @karlitschek @jospoortvliet

**Comment by szaimen** [comment]
The main reason why I closed this is because it is the wrong place to report this as this is about nextcloud/server and not nextcloud/scanner.

**Comment by burner-** [comment]
yes there is 2 reasons for that.  1)There is no nextcloud/scanner repository. Atleast public one.  2) because it need implementation also to server side to do it so that it is done by leagal and best practices.
