### ISSUE TITLE
✨ Nextcloud-wide mechanism to translate, lengthen text, make more serious, etc.

### ISSUE THREAD

**Issue by julien-nc** [nextcloud/server#39478]
As an extension to the new text processing OCP API (https://github.com/nextcloud/server/pull/38854), we would like to implement a frontend component using this API. It would allow apps to push text content to a UI element that would then let users choose a task to perform. The result would be passed back to the app's frontend.

The event bus could be used to let apps communication with this widget.

**Comment by nimishavijay** [comment]
High level specs and mockups: 

- entry
  - depends on the downstream app (placement of text processing button)
  - AND top right corner text processing button
  - AND smart picker
- click on entry point button
  - choose action in an action menu --> open text processing component 
  - OR directly open the text processing component with no action selected 
- text processing component
  - MVP: modal
- inside the modal
  - Nextcloud assistant chip
  - dropdown with the different actions
  - heading/title
  - description (optional)
  - input text (taken from whatever text is selected in downstream app, editable)
  - submit button 
- on submit
  - synchronous or async
  - synchronous: do not exit the text processing component until processing is finished, show loading status 
    - if processing is taking too long 
      - in loading state buttons to run in bg, indicate notification will be received
    - **after processing**
    - output (editable)
    - insert/replace or copy buttons
  -  asynchronous: exit the TP component during processing, notify that result will be available after completion
    - **after processing**
    - show notification after TP is completed with a button to show results
    - clicking on button opens TP component with input, output and copy button 

General idea:
  
![image](https://github.com/nextcloud/server/assets/52440189/c8b5a683-129a-4050-82ed-9f20ec05c345)


Modal specifics:

| Entry  | Summarizing  | Done  |
|---|---|---|
| ![image](https://github.com/nextcloud/server/assets/52440189/8ef62ae2-ea38-4664-a8d2-9262305ef0b5)  |  ![image](https://github.com/nextcloud/server/assets/52440189/683725c3-1645-4bf5-8aed-ae1193466858) | ![image](https://github.com/nextcloud/server/assets/52440189/0c16cd75-f96f-4050-bb33-57e2cce84616)  |


- nice to haves
  - floating TP component
  - sidebar TP component
  - options for each action
  - additional contextual data for each TP action (like name of conversation in Talk, name of text file, etc)
  - top right history

**Comment by julien-nc** [comment]
Some news:

Since the tasks are most likely long, only the async workflow has been implemented yet.

Workflow when using the header menu button:

https://github.com/nextcloud/server/assets/11291457/56991e98-0929-4242-9e7a-1c95dfb8a590

Opening the assistant from another app:

https://github.com/nextcloud/server/assets/11291457/e04f536c-5740-4064-b77f-e909e12a1d92

Here is the page showing the results when the notification is clicked on a mobile/desktop client (that can't display the modal):
![image](https://github.com/nextcloud/server/assets/11291457/01b0560e-8ea9-4547-9f30-c7c05bc4bc58)

If an app opens the assistant, it gives it some extra info (appId and task identifier) so that when the task finishes, the assistant lets the app decide if the assistant should produce a notification and if the notification should show the "classic" result modal/page or if it should have a custom link target.

TODO:
* [ ] improve the notification title/message
* [ ] add a "discard" button in the result modal (what should it do?)

**Comment by marcelklehr** [comment]
I feel like the current logo for the assistant is sort of non-descript, what do you think about using this one instead? https://pictogrammers.com/library/mdi/icon/assistant/

**Comment by nimishavijay** [comment]
@jancborchardt what do you think about that icon? since it has to do with branding as well? :)

**Comment by jancborchardt** [comment]
Closing this as it has been done and is shipped already. :) Nice work!
