### ISSUE TITLE
Same user gets disabled regulary - reason unknown

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/server#39512]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Have a user (only one), who gets disabled regulary without any admin intervention.

Special monitoring (bash-script) is active only for this user, that i will be informed by email, when this happens.
And this happens from time to time.

Happend today again.

### Steps to reproduce

1. User did report, that he tried to open "Nextcloud TALK" on iPhone
2. Nextcloud TALK on iPhone suddenly closes (this could mean: crashing).
3. Did check the nextcloud.log:

Reporting:  (there you see the iOS- & Nextcloud Version)

":"--","app":"core","method":"OPTIONS","url":"/remote.php/dav/principals/users/<user>/","message":"Login failed: '<user>' (Remote IP: 'xx.xx.xx.xx')","userAgent":"iOS/16.5.1 (20F75) dataaccessd/1.0","version":"26.0.3.2","data":{"app":"core"}}

### Expected behavior

- User should not be disabled without admin intervention (main issue)
- Nextcloud TALK should not crash on iPhone: iOS/16.5.1 

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

26

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "timeout": 1.5,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "26.0.3.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "auth.bruteforce.protection.enabled": true,
        "check_for_working_htaccess": true,
        "updater.release.channel": "stable",
        "upgrade.disable-web": false,
        "data-fingerprint": "***REMOVED SENSITIVE VALUE***",
        "logfile": "\***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
         ***REMOVED SENSITIVE VALUE***
        "session_keepalive": false,
        "logtimezone": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "CH",
        "knowledgebaseenabled": false,
        "log_rotate_size": 3145728,
        "mail_sendmailmode": "smtp",
        "app_install_overwrite": [
            "passman",
            "dicomviewer",
            "radio",
            "cookbook",
            "health",
            "issuetemplate",
            "documentserver_community",
            "imageconverter",
            "epubreader",
            "workflow_pdf_converter",
            "signlive",
            "apporder"
        ]
    }
}
```

### List of activated Apps

```shell
apps:

Enabled:
  - activity: 2.18.0
  - analytics: 4.9.4
  - announcementcenter: 6.6.1
  - audioplayer: 3.4.0
  - bookmarks: 13.0.1
  - breezedark: 26.0.0
  - bruteforcesettings: 2.6.0
  - calendar: 4.4.3
  - calendar_resource_management: 0.5.0
  - circles: 26.0.0
  - cloud_federation_api: 1.9.0
  - collectives: 2.6.1
  - comments: 1.16.0
  - contacts: 5.3.2
  - contactsinteraction: 1.7.0
  - cookbook: 0.10.2
  - cospend: 1.5.10
  - dashboard: 7.6.0
  - data_request: 1.13.0
  - dav: 1.25.0
  - deck: 1.9.2
  - dicomviewer: 1.2.4
  - documentserver_community: 0.1.13
  - drawio: 2.1.2
  - drop_account: 2.2.0
  - end_to_end_encryption: 1.12.5
  - event_update_notification: 2.2.0
  - federatedfilesharing: 1.16.0
  - federation: 1.16.0
  - files: 1.21.1
  - files_antivirus: 5.2.1
  - files_automatedtagging: 1.16.1
  - files_downloadactivity: 1.16.0
  - files_external: 1.18.0
  - files_markdown: 2.4.1
  - files_mindmap: 0.0.28
  - files_pdfviewer: 2.7.0
  - files_photospheres: 1.26.4
  - files_rightclick: 1.5.0
  - files_sharing: 1.18.0
  - files_trashbin: 1.16.0
  - files_versions: 1.19.1
  - firstrunwizard: 2.15.0
  - flow_notifications: 1.6.0
  - forms: 3.3.1
  - gpxpod: 5.0.12
  - groupfolders: 14.0.3
  - health: 1.6.2
  - imageconverter: 1.3.5
  - impersonate: 1.13.1
  - integration_discourse: 2.0.4
  - integration_dropbox: 2.0.1
  - integration_github: 2.0.4
  - integration_gitlab: 1.0.17
  - integration_google: 2.0.2
  - integration_jira: 1.0.5
  - integration_mastodon: 2.0.2
  - integration_openai: 1.0.11
  - integration_openproject: 2.3.7
  - integration_reddit: 2.0.1
  - integration_replicate: 1.0.7
  - integration_twitter: 1.0.6
  - integration_zammad: 2.0.6
  - keeweb: 0.6.13
  - libresign: 7.1.1
  - logreader: 2.11.0
  - lookup_server_connector: 1.14.0
  - mail: 3.2.4
  - maps: 1.1.0
  - money: 0.19.0
  - news: 21.2.0
  - nextcloud_announcements: 1.15.0
  - notes: 4.8.1
  - notifications: 2.14.0
  - oauth2: 1.14.0
  - onlyoffice: 7.8.0
  - passman: 2.4.7
  - password_policy: 1.16.0
  - photos: 2.2.0
  - polls: 5.2.0
  - privacy: 1.10.0
  - provisioning_api: 1.16.0
  - quicknotes: 0.8.10
  - quota_warning: 1.17.0
  - recommendations: 1.5.0
  - related_resources: 1.1.0-alpha1
  - serverinfo: 1.16.0
  - settings: 1.8.0
  - sharebymail: 1.16.0
  - side_menu: 3.10.2
  - signlive: 0.9.0
  - socialsharing_diaspora: 2.6.0
  - socialsharing_email: 2.6.0
  - socialsharing_facebook: 2.6.0
  - socialsharing_twitter: 2.6.0
  - spreed: 16.0.4
  - support: 1.9.0
  - suspicious_login: 4.4.0
  - systemtags: 1.16.0
  - tables: 0.5.1
  - talk_matterbridge: 1.26.0
  - tasks: 0.15.0
  - terms_of_service: 2.2.0
  - text: 3.7.2
  - theming: 2.1.1
  - timemanager: 0.3.8
  - twofactor_backupcodes: 1.15.0
  - twofactor_totp: 8.0.0
  - updatenotification: 1.16.0
  - user_status: 1.6.0
  - viewer: 1.10.0
  - weather_status: 1.6.0
  - welcome: 1.0.9
  - workflow_media_converter: 1.8.4
  - workflow_ocr: 1.26.1
  - workflow_pdf_converter: 1.11.0
  - workflow_script: 1.11.2
  - workflowengine: 2.8.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
":"--","app":"core","method":"OPTIONS","url":"/remote.php/dav/principals/users/<user>/","message":"Login failed: '<user>' (Remote IP: 'xx.xx.xx.xx')","userAgent":"iOS/16.5.1 (20F75) dataaccessd/1.0","version":"26.0.3.2","data":{"app":"core"}}
```

### Additional info

SQL Bruteforce Table show strange entries, too: (coming from yesterday/19.07.2023)

+------+--------------------------------+------------+--------------+-----------------+-----------------------------+
| id   | action                         | occurred   | ip           | subnet          | metadata                    |
+------+--------------------------------+------------+--------------+-----------------+-----------------------------+
| 6565 | PublicSessionController::push  | 1689694149 | xx.xx.xxx.xx | xx.xx.xxx.xx/32 | {"token":"dkdkdkdkdkdkdnN"} |
| 6566 | PublicSessionController::sync  | 1689694149 | xx.xx.xxx.xx | xx.xx.xxx.xx/32 | {"token":"dkdkdkdkdkdkdnN"} |
| 6567 | PublicSessionController::close | 1689694149 | xx.xx.xxx.xx | xx.xx.xxx.xx/32 | {"token":"dkdkdkdkdkdkdnN"} |
| 6568 | PublicSessionController::sync  | 1689694209 | xx.xx.xxx.xx | xx.xx.xxx.xx/32 | {"token":"dkdkdkdkdkdkdnN"} |
| 6569 | PublicSessionController::push  | 1689694209 | xx.xx.xxx.xx | xx.xx.xxx.xx/32 | {"token":"dkdkdkdkdkdkdnN"} |
| 6570 | PublicSessionController::close | 1689694210 | xx.xx.xxx.xx | xx.xx.xxx.xx/32 | {"token":"dkdkdkdkdkdkdnN"} |
| 6571 | PublicSessionController::sync  | 1689694269 | xx.xx.xxx.xx | xx.xx.xxx.xx/32 | {"token":"dkdkdkdkdkdkdnN"} |
| 6572 | PublicSessionController::push  | 1689694269 | xx.xx.xxx.xx | xx.xx.xxx.xx/32 | {"token":"dkdkdkdkdkdkdnN"} |
| 6573 | PublicSessionController::close | 1689694271 | xx.xx.xxx.xx | xx.xx.xxx.xx/32 | {"token":"dkdkdkdkdkdkdnN"} |
| 6574 | PublicSessionController::push  | 1689694330 | xx.xx.xxx.xx | xx.xx.xxx.xx/32 | {"token":"dkdkdkdkdkdkdnN"} |
| 6575 | PublicSessionController::sync  | 1689694332 | xx.xx.xxx.xx | xx.xx.xxx.xx/32 | {"token":"dkdkdkdkdkdkdnN"} |
| 6576 | PublicSessionController::close | 1689694334 | xx.xx.xxx.xx | xx.xx.xxx.xx/32 | {"token":"dkdkdkdkdkdkdnN"} |
| 6577 | PublicSessionController::sync  | 1689694392 | xx.xx.xxx.xx | xx.xx.xxx.xx/32 | {"token":"dkdkdkdkdkdkdnN"} |
| 6578 | PublicSessionController::push  | 1689694392 | xx.xx.xxx.xx | xx.xx.xxx.xx/32 | {"token":"dkdkdkdkdkdkdnN"} |
| 6579 | PublicSessionController::close | 1689694395 | xx.xx.xxx.xx | xx.xx.xxx.xx/32 | {"token":"dkdkdkdkdkdkdnN"} |

**Comment by SystemKeeper** [comment]
> * Nextcloud TALK should not crash on iPhone: iOS/16.5.1

Can you please open a issue at https://github.com/nextcloud/talk-ios and attach the crash report of that iPhone? It can be found under Settings -> Privacy -> Analytics -> Analytics Data.

**Comment by SystemKeeper** [comment]
> ### Nextcloud Logs
> ```shell
> ":"--","app":"core","method":"OPTIONS","url":"/remote.php/dav/principals/users/<user>/","message":"Login failed: '<user>' (Remote IP: 'xx.xx.xx.xx')","userAgent":"iOS/16.5.1 (20F75) dataaccessd/1.0","version":"26.0.3.2","data":{"app":"core"}}
> ```

That looks like the user has set up a calendar or contacts sync with (now) invalid credentials. This is not from the talk app (that would be visible in the user agent). So please check with the user if there’s a account that doesn’t sync anymore and remove that.

**Comment by Githopp192** [comment]
Thx for the good input. Told the user to re-install TALK. Look's like it's working now.
Told the user to re-install all Nextcloud with current credentials on every device.
Let's see, if this works & thx again !
