### ISSUE TITLE
[Bug]: Wrong filenames in trash bin

### ISSUE THREAD

**Issue by csware** [nextcloud/server#39539]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The trashbin view shows filenames as `its.d1686841219` (some abbreviated before the `.`) or `.d1686841232`. When I click to restore the correct filename is used same applies when I click download. This issue occurred after an upgrade from 26.0.4 to 27.0.1. This affects files deleted with the old version before the update and also files deleted after the update.

### Steps to reproduce

1. Delete a file
2. Go to the trashbin view

### Expected behavior

The correct filename of the deleted file is shown as for Nextcloud < 27

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version: 26.0.4 to 27.0.1

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.0.1.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "loglevel": 2,
        "integrity.check.disabled": false,
        "apps_paths": [
            {
                "path": "\/var\/www\/cloud.XXXX.de\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "maintenance": false,
        "theme": "",
        "overwrite.cli.url": "https:\/\/cloud.XXXX.de",
        "overwriteprotocol": "https",
        "activity_expire_days": 31,
        "trusted_domains": [
            "cloud.XXXX.de"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/",
        "mail_smtpmode": "sendmail",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": false,
        "singleuser": false,
        "log_rotate_size": 104857600,
        "logtimezone": "Europe\/Berlin",
        "mail_sendmailmode": "pipe",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "mysql.utf8mb4": true,
        "defaultapp": "files",
        "updater.release.channel": "stable",
        "default_phone_region": "DE",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "preview_imaginary_url": "http:\/\/localhost:9000",
        "enabledPreviewProviders": [
            "OC\\Preview\\Imaginary"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - bruteforcesettings: 2.7.0
  - calendar: 4.4.3
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.3.2
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.10.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - gpxpod: 5.0.12
  - impersonate: 1.14.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - onlyoffice: 8.1.0
  - photos: 2.3.0
  - polls: 5.2.0
  - provisioning_api: 1.17.0
  - related_resources: 1.2.0
  - richdocuments: 8.1.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - spreed: 17.0.2
  - systemtags: 1.17.0
  - tasks: 0.15.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - admin_audit: 1.17.0
  - encryption: 2.15.0
  - password_policy: 1.17.0 (installed 2.0.0)
  - privacy: 1.11.0 (installed 1.0.0)
  - recommendations: 1.6.0 (installed 0.4.0)
  - support: 1.10.0 (installed 1.0.0)
  - survey_client: 1.15.0 (installed 1.4.0)
  - suspicious_login: 5.0.0
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional info

In Firefox I see a lot of HTTP error 400 errors for `https://cloud.XXXX.de/apps/files_trashbin/preview?fileId=4139741&x=32&y=32&a=0`.

**Comment by joshtrichards** [comment]
Confirmed. 

Reproduced in:

- v27.0.1

![image](https://github.com/nextcloud/server/assets/1731941/218ca37d-e8d3-4499-a76f-89241ef972a8)

- master:

![image](https://github.com/nextcloud/server/assets/1731941/12f1e57a-37c6-4aa7-b4dd-fb7c7a1543ff)

Unable to reproduce in:

- v27.0.0 

![image](https://github.com/nextcloud/server/assets/1731941/d74d0181-f6ed-4eac-950b-011be3814d3b)

**Comment by szaimen** [comment]
Cc @skjnldsv

**Comment by csware** [comment]
Might https://github.com/nextcloud/server/pull/36534/files#diff-8c245bdad274c22b28c46f30bb1d3b364c378dcdc240402da558e53a6af6573cR71 be the reason?

**Comment by bcutter** [comment]
I can confirm this too.

**Comment by skjnldsv** [comment]
fix in https://github.com/nextcloud/server/pull/39566

**Comment by gaticssa** [comment]
I'm noticing other problems with the trash bin as well. I'm not sure if they're related, or something completely different:

1. Some file deletion dates are wildly wrong
A couple of hours ago, I deleted a few dozen docx files via the desktop client (all in one go, not one by one). 
The deletion dates for those files listed in the trash bin range from "10 days ago" to "4 minutes ago".

2. Sorting by deletion date doesn't work
No matter if the _Deleted_ column is set to ascending or descending order, the files are not sorted by deletion date. 
The list gets rearranged when clicking the column header, but I can't figure out what criterion it's being sorted by.

Has anyone else seen these issues?

**Comment by skjnldsv** [comment]
@gaticssa it looks good from me.
What browser and version are you using?

**Comment by skjnldsv** [comment]
Can you open a dedicated issue?
When doing so, please also post the response of the dav request.
It should start with `<?xml version="1.0"?><d:multistatus xmlns:d="DAV:"`. Feel free to obfuscate the data with your text editor search and replace feature.

You also don't need to list the entire set of data, just a few files should be enough to check if the returned date fits what is displayed on your web interface.

![image](https://github.com/nextcloud/server/assets/14975046/ff6463a9-7d79-41ce-9c17-b668629da5a2)

<details>
<summary>How to access your browser network tab (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “network” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “network” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “network” tab.
</details>
