### ISSUE TITLE
Disable "Internal link" in UI

### ISSUE THREAD

**Issue by loelkes** [nextcloud/server#39558]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Most users think that “internal link” means “a link that everyone within the instance can access”.

**Describe the solution you'd like**
Hide internal links in the UI.

**Describe alternatives you've considered**
Only show internal links option for a user group (such as admins).

**Additional context**
![image](https://github.com/nextcloud/server/assets/231909/c61c0705-90d2-4ecf-8e6d-caba2bae6faa)
**I know its written below but many users stop reading after the title since they have found what they think they were looking for.** Since it causes a lot of confusion and frustration it would be easier to disable them entirely. 

Already posted here without response: https://help.nextcloud.com/t/disable-internal-links-in-ui/142060

**Comment by skjnldsv** [comment]
Hi @loelkes 
Unfortunately I don't think this is a config we want to have. To keep things simple, it's best to avoid edge cases liek those, and as you can see on this ticket activity, the request for this are quite low :/

I can suggest you use the custom css app and use a css selector to hide it.
There is a limit to customization for Nextcloud :)

```css
li.sharing-entry__internal {
    display: none !important;
}
```

**Comment by loelkes** [comment]
I understand. Thanks for the feedback and the suggestion, I appreciate it :)
