### ISSUE TITLE
[Bug]: Icons use dark mode color on light mode after upgrade NC27.01

### ISSUE THREAD

**Issue by grrdvnk** [nextcloud/server#39551]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I've specified a pretty dark theme color (#002832), which had issues on dark mode on NC 26 and below (fixed in [pr 38159).](https://github.com/nextcloud/server/pull/38159).

Since I upgraded to NC 27.01, icons do not follow the specified theme color any longer in light mode. Instead it always uses the dark mode color (generated by pr 38159). I first noticed the Nextcloud iOS app was off, but is is also present in the web interface. Setting a different (not so dark) theme color does update the icon colors.

### Steps to reproduce

1. Set theme color to HEX 002832
2. Set interface to light mode
3. See icon colors are off:

<img width="605" alt="Screenshot 2023-07-24 at 11 23 53" src="https://github.com/nextcloud/server/assets/20874876/69959239-50ba-4497-bf7e-c478c46361ad">

### Expected behavior

Icon colors should follow theme color as specified when using light mode

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment]
If you choose a primary color that is too dark or too bright it will automatically change the color so that contrast to the background is always guaranteed. That is what https://github.com/nextcloud/server/pull/38159 is doing. So not completely sure what we can do here.
