### ISSUE TITLE
PDF viewer broken in deleted files view

### ISSUE THREAD

**Issue by SteveQi** [nextcloud/server#3956]
### Steps to reproduce
1. Delete a pdf file
2. Go to deleted files List
3. Click PDF files

### Expected behaviour
PDF should open

### Actual behaviour
PDF viewer is broken

![bildschirmfoto 2017-03-20 um 04 14 21](https://cloud.githubusercontent.com/assets/245432/24095672/d05f066a-0d23-11e7-8676-f36df51d481d.png)

**Comment by MorrisJobke** [comment]
I was so kind and improved your bug report :)

Also broken on master

**Comment by MorrisJobke** [comment]
@nextcloud/javascript @ChristophWurst @LukasReschke @icewind1991  interested in looking into this?
