### ISSUE TITLE
Add configurable list of extra files allowed in directory during application update

### ISSUE THREAD

**Issue by brainchild0** [nextcloud/server#39573]
The updater scans the application directory for cleanness before beginning the update process.

Any files present in the application directory not known as being from the application distribution must be removed for the update process to proceed.

Some hosting environments constrain the possibility for managing the application directory so rigidly.

For example, in a Plesk hosting environment, several items have been observed as added to the root level of the application directory, including `.php-ini`, `.php-version`, and `.well-known`. While use of the application directory to store such data may seem as poor design for the hosting software, application administrators who are users of the environment may lack in practice any means to avoid the effects of such design.

Requested is support for a site-configurable list of file names that should be ignored by the updater when checking the integrity of the application directory. For usability, the standard installation may populate it with initial items that are commonly found in certain environments.

The feature might be implemented either through a new configuration field, or through a separate file following the design pattern applied in `.gitignore`.

**Comment by joshtrichards** [comment]
nextcloud/updater#68
