### ISSUE TITLE
[Bug]: Double dots in links in emails

### ISSUE THREAD

**Issue by FedericoHeichou** [nextcloud/server#39594]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

As you can from this issue in Symfony https://github.com/symfony/symfony/issues/50875 seems like the mailer adds double dots if a dot is matched as first character of a line (this is the code)  
https://github.com/symfony/symfony/blob/acd9e3b9922b2f6064dc8bd1f77c52f7ce48ec69/src/Symfony/Component/Mailer/Transport/SendmailTransport.php#L105-L107

If you add the `-i` in the `pipe` (like this `'pipe' => ' -t -i'`)
https://github.com/nextcloud/server/blob/767c42f4596fc077480b3729b344c9a261cabe9c/lib/private/Mail/Mailer.php#L333-L336
This fixes the issue.  

Symphony community is still trying to understand if this is a bug or not, but still this seems a solution.  
What do you think? Can I do a PR for this?

This will resolve these issues too: #33754 and #16379

### Steps to reproduce

1. replace the sendmail binary with the postfix one (I don't know if this is required but I use this one) but stop all postfix daemons (or just run it in a container with a super dummy spool folder)
```bash
mkdir -p /var/spool/postfix/maildrop
chmod ugo+rwx  /var/spool/postfix /var/spool/postfix/maildrop
```
3. set the `mail_sendmailmode` to `pipe`
4. create many users with different string length (for example user1, user12, user123, user1234)
```bash
# create random users
export OC_PASS=Epi1cP4ssword
for i in {1..20}; do php occ user:add user$(python3 -c "print('1'*$i)") --password-from-env; done
# set the email
for i in {1..20}; do USERNAME=user$(python3 -c "print('1'*$i)"); php occ user:setting "$USERNAME" settings email "${USERNAME}.${USERNAME}@example.com"; done
```
5. generate some emails (for example I send all the Welcome emails with the reset password link)
6. check if there are duplicated dots in the postfix spool (grep random things that could appear in your Nextcloud url)
```bash
cd /var/spool/postfix/maildrop
postcat -bh * | grep lostpass -C2
```
7. you will definitely find at least one user with a broken link 
```
Imposta la tua password: https://mydrive.example.com/index=
..php/lostpassword/reset/form/3GOnnGyVaEBzs2JmuYXCU/utente123456
```

### Expected behavior

Dots should not be doubled in emails

### Installation method

Community Docker image

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
[...]
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "pipe",
[...]
    }
}
```

**Comment by kesselb** [comment]
`"mail_sendmailmode": "pipe",`

What could be a reason to use pipe if SMTP (for sendmail) is available?

**Comment by FedericoHeichou** [comment]
> `"mail_sendmailmode": "pipe",`
> 
> What could be a reason to use pipe if SMTP (for sendmail) is available?

Because SMTP requires to contact a listening server, with pipe you can use local queue

**Comment by kesselb** [comment]
> SMTP (for sendmail)

By this, I meant: sendmail -bs

The description at https://www.postfix.org/sendmail.1.html is a bit vague. 

> This mode of operation is implemented by  running  the  [smtpd(8)](https://www.postfix.org/smtpd.8.html) daemon.

Does that means it requires a running smtpd or use smtpd internally to provide this service. 

The initial pull request https://github.com/nextcloud/server/pull/11454 used `-t -oi`.
For a reason, I can't remember I used only `-t` in my extended version: https://github.com/nextcloud/server/pull/12424.

Please submit a pull request, it looks like a reasonable change to me.

**Comment by FedericoHeichou** [comment]
> > SMTP (for sendmail)
> 
> By this, I meant: sendmail -bs
> 
> The description at https://www.postfix.org/sendmail.1.html is a bit vague.
> 
> > This mode of operation is implemented by  running  the  [smtpd(8)](https://www.postfix.org/smtpd.8.html) daemon.
> 
> Does that means it requires a running smtpd or use smtpd internally to provide this service.
> 
> The initial pull request #11454 used `-t -oi`. For a reason, I can't remember I used only `-t` in my extended version: #12424.
> 
> Please submit a pull request, it looks like a reasonable change to me.

Sure, I will submit one tomorrow.

Anyway I really don't remember which parameters are but postfix's sendmail has 3 ways (at least I remember these, I could be wrong):
1. Writing in the local queue, then a demon read there and sends the emails
2. Contacts a SMTP server (default is localhost 25)
3. It fakes a SMTP server emulating a SMTP handshake then put the content in the destination MX server by itself (it could be the -bs because it says "running the smtpd"

I prefer the first one because it works in any containerized environment by default (the default PHP settings has (sendmail -t -i), you just have to mount the spool) even without the network. You can even perform some operations before sending queue mails, like preventing spoofing and similar things
