### ISSUE TITLE
Sabre/dav maintainer is abandoning project

### ISSUE THREAD

**Issue by hogarthj** [nextcloud/server#3960]
Hi,

The sabre/dav developer recently blogged that he's marking the project EOL and no longer going to work on it.

What are you plans to handle this, especially given the nature of the project and the prospect of vulnerabilities?

https://evertpot.com/sabredav-eol/

**Comment by LukasReschke** [comment]
We're in contact with the responsible people about that.

**Comment by schnackOpPlatt** [comment]
Hi,

as far as I now there is no new maintainer for the project sabre/dav. Since this is about one year ago and there is no new maintainer I think this is a security-issue; Or is this that part of code now maintained directly in Nextcloud?
