### ISSUE TITLE
Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent is used

### ISSUE THREAD

**Issue by teto** [nextcloud/server#39621]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
My logs are polluted by 
"method":"POST","url":"/apps/memories/api/image/multipreview","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0","version":"27.0.
```
I am not sure if it's due to previewgenerator or the base install.

**Describe the solution you'd like**
have the message disappear.

**Describe alternatives you've considered**
Nothing. I've seen https://github.com/nextcloud/server/issues/30639 which looks related but it's closed and for older versions of nextcloud.

**Additional context**
running nextcloud 27.0 via the nixos-unstable nextcloud module

**Comment by joshtrichards** [comment]
Hi @teto - These are developer messages. They're normal. Deprecated messages simply mean that an app developer has several development cycles left before they need to switch to a non-legacy way of doing things.

You generally won't see them these days unless you have debug level logging on. The recommended `loglevel` is `2`. It's also the default, unless you override it:

https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html#logging
https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/logging_configuration.html

This is effectively a duplicate of #24380.

**Comment by teto** [comment]
what surprised me is how old those issues were. If it's duplicate let's close then

**Comment by joshtrichards** [comment]
Some things take awhile to completely eliminate. That's why there is a deprecation cycle.

I'll also point out that the one you posted is from a third party app (memories), not a NC project maintained app. :)

Anyhow, as long as your logging is setup reasonably you won't see them. Long ago the default log level configuration was different and up until NC27 there were also spots where we still logged some deprecation messages above debug level. That's fixed now.

What log level are you seeing those messages at anyway?
