### ISSUE TITLE
Croatian not selectable

### ISSUE THREAD

**Issue by andreas-p** [nextcloud/server#3962]
Croatian language can't be selected from personal page in NC11, because core/l10n/hr.json is missing. I created a dummy hr.json and instantly had Hvatski/hr available.

**Comment by MorrisJobke** [comment]
The reason for this is that the Croatian translation rate is quite low. Once there is more translated it will be created. Help out to translate Nextcloud at Transifex: http://transifex.com/nextcloud/nextcloud/
