### ISSUE TITLE
Last folder name in adress bar overlaping <

### ISSUE THREAD

**Issue by Bullnados** [nextcloud/server#3964]
On demo NC

![grafik](https://cloud.githubusercontent.com/assets/11041576/24122350/ccfb95c2-0dbb-11e7-8ad2-c0a813068cb6.png)

![grafik](https://cloud.githubusercontent.com/assets/11041576/24122397/f3f79180-0dbb-11e7-8f19-6e87d1f6a503.png)

**Comment by MorrisJobke** [comment]
I can't reproduce this in Safari, Firefox nor Chrome. What browser do you use?

**Comment by MorrisJobke** [comment]
Also your screenshots are missing the share icon:

<img width="453" alt="bildschirmfoto 2017-03-20 um 18 53 37" src="https://cloud.githubusercontent.com/assets/245432/24127994/90ce7c9e-0d9e-11e7-8e96-53de3ab6822e.png">

**Comment by Bullnados** [comment]
Screenshots are made with ff 52 beta

**Comment by MorrisJobke** [comment]
> Screenshots are made with ff 53.0b4 beta x64 desktop

Tried with Firefox 53 x64 desktop works totally fine. Maybe it's the beta. Could you maybe try with another browser and also clear caches?

**Comment by Bullnados** [comment]
Found the "bug" it is again Adblocker share button problem
