### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Michael-Z-Freeman** [nextcloud/server#39653]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Not a software bug per se but a serious issue in the documentation that seems to be the root of a lot of confusion with crontab. 

[The manual says](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html#cron) to run crontab with "_crontab -u www-data -e_". However the first recommendation should be to use cron under the default account  and use something like "_59 * * * * curl -s https://nextcloud.michaelzfreeman.org/cron.php >/dev/null 2>&1_". This links to the Nextcloud server just like any browser or web application. This means that there will not be any issues with which account or PHP type Nextcloud is being run under which has caused a lot of confusion for users.

### Steps to reproduce

1. Follow current docs.
2. Get endless "Cron not run" messages from admin page.
3. Pull hair out.

### Expected behavior

The docs should give the shortest and easiest route to a solution.

### Installation method

None

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment]
Thanks for your report :+1: 

I see your point about different PHP versions, paths, etc. 
Nevertheless, system cron is the proper way to do it.

**Comment by Michael-Z-Freeman** [comment]
Yes of course cron is the proper way. I'm saying it should be documented as a call to the HTTP address as this gets round the PHP versions problem.

**Comment by kesselb** [comment]
No. The proper way is to call cron.php directly, without a web server involved.

**Comment by Michael-Z-Freeman** [comment]
I was referring to adding the easier way in the documentation to help users, even if its not the proper way.
