### ISSUE TITLE
[Bug]: LLM text processing API fails because migration is not executed automatically

### ISSUE THREAD

**Issue by hamza221** [nextcloud/server#39658]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Migration 28000Date20230616104802 not executed automatically, which leads to Table oc_llm_tasks missing

### Steps to reproduce

oc_llm_tasks missing

### Expected behavior

 28000Date20230616104802  is run and oc_llm_tasks exists 

### Installation method

Community Docker image

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ChristophWurst** [comment]
The internal version number was not bumped in https://github.com/nextcloud/server/pull/38854
