### ISSUE TITLE
Add API for FileAction submenu actions

### ISSUE THREAD

**Issue by Pytal** [nextcloud/server#39718]
An API should be added to https://github.com/nextcloud/server/blob/8606f162c5b5b5d6a355e7e2f27e05585b3d0360/apps/files/src/services/FileAction.ts#L80 to allow for an action to open a submenu of actions

**Comment by Pytal** [comment]
For 28 the "Set reminder" action will require a submenu API is this doable @skjnldsv?

**Comment by skjnldsv** [comment]
(replied in #39181)

**Comment by joshtrichards** [comment]
Specifically in: https://github.com/nextcloud/server/issues/39181#issuecomment-1666461440
