### ISSUE TITLE
Brute Force

### ISSUE THREAD

**Issue by SamuelWei** [nextcloud/server#3971]
Main issue solved
s. last comment

**Comment by rullzer** [comment]
Does your office share a single outgoing ip?

**Comment by SamuelWei** [comment]
@rullzer The issue was a that I routed traffic thought a vpn server, so multiple clients had the same internal ip. 

I think in the userpanel there should be the option for a user to clear the brute force entries for his account. Ex. If I have a client running with my userpassword and the password changes, the failed logins will be detected by the brute force throttle and I'm throttled for 12h.

**Comment by tflidd** [comment]
For clearing brute force entries, there is already an open issue:
https://github.com/nextcloud/server/issues/3058
