### ISSUE TITLE
[feature] occ trashbin:restore should support Groupfolders

### ISSUE THREAD

**Issue by R0Wi** [nextcloud/server#39724]
**Is your feature request related to a problem? Please describe.**

Since https://github.com/nextcloud/server/pull/28935 we have the possibility to restore deleted files from the trashbin via `php occ trashbin:restore`. Unfortunately, like also [stated in the docs](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html#trashbin-label), this command is currently not able to restore files which have been deleted from Groupfolders.

**Describe the solution you'd like**

It would be great if the command would also be able to restore files which have been deleted from Groupfolders. I could imagine adding a new flag `--scope` with values `user`, `groupfolders` or `all`, which controls the scope of the restore. For backward compatibility the default should be set to `user`.

**Describe alternatives you've considered**

Currently there's no (comfortable) way of restoring a huge amout of deleted files from Groupfolders.

**Additional context**

One of our customers make use of the NC sync client combined with Groupfolders. In the past some users accidentally deleted huge folders on their local systems and when they got synced, all the files have been gone for everyone. The only possibility to restore these files right now was to use a backup and do a partial restore to the disk, adjusting file permissions, re-reading the files into Groupfolders etc. Restore via UI was not feasible since we're talking about a few thousand files.

**Contribution**

If you're willing to accept this new feature, I'd be happy to implement it :+1: I just wanted to check your opinion before going into further implementation detail.

**Comment by solracsf** [comment]
Can't find a reason why a PR shouldn't be welcomed to be reviewed :-D
