### ISSUE TITLE
[Bug]: <dav> upgrade step takes hours when server connected to large LDAP directory, or has hundreds of users

### ISSUE THREAD

**Issue by andrewperry** [nextcloud/server#39744]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When upgrading from 26.0.4 to 27.0.1 there is a step in the upgrade flow that says:

"Updating \<dav\> ..."

which seems to query the ldap directory and for every entry in LDAP update the "System Address Book" in the 'addressbooks' table as well as create an account in the 'accounts' table with a corresponding entry in the 'ldap_user_mapping' table.

If a server is connected to an LDAP directory with thousands, tens of thousands or hundreds of thousands of users, this can take hours to recurse through and it does not seem that this is a step that should block the completion of the upgrade. Can this step please be moved to a separate recommendation, like the addition of indexes for performance, that would appear in the admin interface alongside other security & performance recommendations. This would enable the server to get out of maintenance mode quicker, rather than have the server offline for hours (or days) while tens of thousands of LDAP accounts are probed and accounts created and/or carddav 'cards' in the "system" addressbook updated (often without them needing to be as they should only be created when the user attempts to login to nextcloud with their LDAP credentials).

### Steps to reproduce

1. Enable LDAP integration
2. Attempt to upgrade from Nextcloud 26.0.4 to 27.0.1
3. Tail updater.log which gives the impression the upgrade is complete but the cli is still hanging at "Updating \<dav\> ..."
4. Tail nextcloud.log -f to see the large number of ldap queries continuously race by for hours

### Expected behavior

Upgrade should complete without the need to recurse the whole connected LDAP directory.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment]
Thank you :+1: 

Sounds like a reasonable request. 

We run syncInstance from a migration[^1] during the upgrade. 
Indeed, this can take a while if your ldap directory is bigger.

Idea:

- Setup check to show a warning "Please run dav:sync-system-addressbook to synchronizes users to the system addressbook". Should be shown if a appconfig "pending_system_addressbook_sync" is there.
- Change the migration: if (IUserManager.countSeenUsers > 100) then add appconfig "pending_system_addressbook_sync" else run syncInstance.

[^1]: https://github.com/nextcloud/server/blob/92c18b252c12acb06c343b11fb36f322f4d17adf/apps/dav/lib/Migration/Version1027Date20230504122946.php

**Comment by kesselb** [comment]
Good first issue:

- Copy setup check https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/apps/settings/lib/SetupChecks/PhpDefaultCharset.php

- Register the new setup check below and add it to the data response  https://github.com/nextcloud/server/blob/ab70bbd3ffbc3788035588c86984f9508db8edbe/apps/settings/lib/Controller/CheckSetupController.php#L907 

- Register the new setup check below https://github.com/nextcloud/server/blob/d25d5d34f730571f1305d9361fec55a9371409af/core/js/setupchecks.js#L536

- Version1027Date20230504122946 inject `IUserManager $userManager` and `IConfig $config` and store it as class property.
- Modify postSchemaChange to skip syncInstance when $userManager->countSeenUsers() is bigger than X (e.g. 100). 

```
		if ($this->userManager->countSeenUsers() > 100) {
			$this->config->setAppValue('dav', 'pendingSystemAddressbookSync', 'yes');
			$output->warning('Skip system address book sync due the large amount of users. Please run dav:sync-system-addressbook manually.');
			return;
		}
```

**Comment by solracsf** [comment]
Note: this is not an LDAP only issue but a "lot of users" issue: https://github.com/nextcloud/server/issues/39769

**Comment by miaulalala** [comment]
Can you give us a guesstimate of the amount of users you have @andrewperry ?
