### ISSUE TITLE
Add header for HSTS (i.e. Strict Transport Security) to included .htaccess

### ISSUE THREAD

**Issue by brainchild0** [nextcloud/server#39766]
In some cases, the following warning will appear in the section *Security & setup warnings* under *Administration settings*:
> The "Strict-Transport-Security" HTTP header is not set to at least "15552000" seconds. For enhanced security, it is recommended to enable HSTS as described in the [security tips ↗](https://docs.nextcloud.com/server/27/go.php?to=admin-security).

It appears that the header value may be set by a declaration given in `.htaccess`, yet such a declaration is omitted from the included version of the file.

If a declaration were given that would cause insertion the desired header value by the web server, then administrators would not need to be bothered with manual configuration as prompted by the warning.

An example has been given in a [discussion response](https://help.nextcloud.com/t/the-strict-transport-security-http-header-is-not-set-to-at-least-15552000-seconds-for-enhanced-security-it-is-recommended-to-enable-hsts/66568/21).

**Comment by kesselb** [comment]
Thanks for your feature request :+1: 

Not a good idea. 
Strict-Transport-Security is cached by the browser and therefore should be enabled if you are certain about it.

**Comment by brainchild0** [comment]
If the declaration were given in `.htaccess`, then the header value would not change between client requests.

If configurability is an issue, then an application configuration parameter may be used to resolve whether to include the declaration in the generated `.htaccess`. It is unclear, however, what is being considered as the dangerous case.

**Comment by kesselb** [comment]
That sounds good. We look forward to your pull request :+1:

**Comment by brainchild0** [comment]
Would you reopen the issue?
