### ISSUE TITLE
[Bug]: database conversion issues (unable to migrate database in order to be compatible with nextcloud-aio)

### ISSUE THREAD

**Issue by panomitrius** [nextcloud/server#39782]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I'm running the latest nextcloud docker and want to migrate to nextcloud aio on docker. 
I've been trying to use the migration app - but that doesn't work (I've spent extensive time and setup a cron service etc but it never finishes exporting even though the data volume is only a few megabytes)
So resorting to the guide [here](https://github.com/nextcloud/all-in-one/blob/main/migration.md) I'm trying to convert the (default mariadb) database to postgresql. I started a shell inside the nextcloud_app_1 container and installed postgresql from there. Then running this conversion command:

`docker exec -u 33 nextcloud_app_1 php occ db:convert-type --all-apps --password defaultpassword --port 5432 pgsql ncadmin localhost nextcloud_db`

Which ends with this error

```
In MigrationService.php line 605:
                                                                               
  Column "oc_reader_bookmarks"."content" is type String, but exceeding the 4.  
  000 length limit.            
```

Before that it seems to work fine:

```
Creating schema in new database
 - related_resources
 - oauth2
 - support
 - dav
 - bruteforcesettings
 - contactsinteraction
 - nextcloud_announcements
 - twofactor_totp
 - files_sharing
 - photos
 - files_external
 - recommendations
 - survey_client
 - systemtags
 - viewer
 - user_ldap
 - settings
 - privacy
 - provisioning_api
 - files
 - files_pdfviewer
 - admin_audit
 - dashboard
 - comments
 - cloud_federation_api
 - theming
 - user_status
 - workflowengine
 - federatedfilesharing
 - serverinfo
 - activity
 - files_versions
 - circles
 - password_policy
 - notifications
 - logreader
 - lookup_server_connector
 - sharebymail
 - text
 - firstrunwizard
 - suspicious_login
 - federation
 - encryption
 - files_trashbin
 - twofactor_backupcodes
 - weather_status
 - files_rightclick
 - updatenotification
 - notes
 - guests
 - passwords
 - mail
 - carnet
 - officeonline
 - calendar
 - files_markdown
 - apporder
 - forms
 - tasks
 - fulltextsearch
 - files_texteditor
 - spreed
 - richdocuments
 - epubreader

```

I also tried deleting the bookmarks app, deleting the database export and repeating the procedure, but same issue.

Any ideas?

### Steps to reproduce

1. Setup nextcloud docker through docker-compose with default settings
2. Follow the migration guide (part 2) from [here](https://github.com/nextcloud/all-in-one/blob/main/migration.md)

### Expected behavior

Conversion successful.

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost:9000"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.0.1.2",
        "overwrite.cli.url": "http:\/\/localhost:9000",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "overwritehost": "nextcloud.mydomain.com:443",
        "overwriteprotocol": "https",
        "loglevel": 2,
        "maintenance": false,
        "app_install_overwrite": [
            "joplin",
            "files_reader"
        ],
        "has_rebuilt_cache": true,
        "theme": ""
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - calendar: 4.4.4
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.3.2
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - forms: 3.3.1
  - guests: 2.5.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mail: 3.2.6
  - nextcloud_announcements: 1.16.0
  - notes: 4.8.1
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - support: 1.10.0
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - admin_audit: 1.17.0
  - apporder: 0.15.0 (installed 0.14.0)
  - bruteforcesettings: 2.7.0 (installed 2.3.0)
  - carnet: 0.24.7 (installed 0.24.6)
  - deck: 1.10.0 (installed 1.10.0)
  - encryption: 2.15.0
  - epubreader: 1.4.7 (installed 1.4.7)
  - files_markdown: 2.4.1 (installed 2.4.1)
  - files_texteditor: 2.15.1 (installed 2.15.1)
  - fulltextsearch: 27.0.1 (installed 27.0.1)
  - officeonline: 2.0.2 (installed 2.0.2)
  - onlyoffice: 8.1.0 (installed 8.1.0)
  - passwords: 2023.8.31 (installed 2023.8.31)
  - richdocuments: 8.1.1 (installed 8.1.1)
  - spreed: 17.0.3 (installed 17.0.3)
  - suspicious_login: 5.0.0
  - tasks: 0.15.0 (installed 0.15.0)
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0
```

**Comment by kesselb** [comment]
> Column "oc_reader_bookmarks"."content" is type String, but exceeding the 4.000 length limit.   

The table/column belongs to the epubreader app: https://github.com/e-alfred/epubreader/blob/0635b00c17f05547e14ebdb0c951a4762d1bd70d/lib/Migration/Version010404Date20201030180941.php#L71

The app is incompatible with newer Nextcloud versions. In your situation, I would backup the current database, uninstall the app, remove the related database table (that's not done by uninstalling) and try the migration again.

**Comment by panomitrius** [comment]
Ok! How do I remove the related database table?
