### ISSUE TITLE
 Implement calendar notifications by email (sent from the server)

### ISSUE THREAD

**Issue by kbabioch** [nextcloud/server#3979]
The Google calendar allows for notifications to be sent via mail. While I can setup such events with the Google calendar app for a Nextcloud calendar (using a DAVdroid account) this does not work, and I don't get any email notification at all. Mail notifications are often more useful than the native notification subsystem of the client itself, since it can be used for automation, etc.

**Comment by georgehrke** [comment]
The awesome @tcitworld is already working on this :)
https://github.com/nextcloud/server/pull/3044

**Comment by shaky1024** [comment]
Assuming this hasn't been implemented, I hereby announce a $30 USD bounty to be paid in your favorite crypto.

**Comment by kunago** [comment]
This would be a great addon since it would allow much better time organization. Relying on external programs to display the notifications works but it is not reliable enough.
