### ISSUE TITLE
[Bug]: Web Updater missing (404), occ upgrade claims already up-to-date when upgrading from 27.0.1 to 27.0.2

### ISSUE THREAD

**Issue by hugalafutro** [nextcloud/server#39802]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Got notification 27.0.2 is available, updater page gives me 404 and `occ upgrade` claims is already latest version.

### Steps to reproduce

1. Be on 27.0.1
2. Try updating
3. Cry

### Expected behavior

Instance should update to 27.0.2

### Installation method

Other Community project

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "allow_local_remote_servers": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***some ip address***",
            "***some dydns address***",
            "localhost"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_REAL_IP"
        ],
        "dbtype": "mysql",
        "version": "27.0.1.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "has_rebuilt_cache": true,
        "default_phone_region": "UK",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "overwrite.cli.url": "https:\/\/***some dyndns address***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpstreamoptions": {
            "ssl": {
                "allow_self_signed": false,
                "verify_peer": true,
                "verify_peer_name": true
            }
        },
        "app.mail.verify-tls-peer": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Imaginary",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Epub",
            "OC\\Preview\\Movie",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\Font",
            "OC\\Preview\\Krita",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\MP4",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc"
        ],
        "trashbin_retention_obligation": "14,30",
        "app_install_overwrite": [
            "suspicious_login",
            "imageconverter",
            "files_antivirus",
            "video_converter",
            "extract",
            "metadata",
            "maps"
        ],
        "updater.release.channel": "stable",
        "preview_imaginary_url": "http:\/\/imaginary:9000",
        "filelocking.enabled": "true",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - audioplayer: 3.4.0
  - bruteforcesettings: 2.7.0
  - calendar: 4.4.4
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.3.2
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - extract: 1.3.6
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_antivirus: 5.2.1
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - imageconverter: 1.3.5
  - integration_giphy: 1.0.7
  - integration_openai: 1.0.11
  - integration_replicate: 1.0.7
  - integration_tmdb: 1.0.2
  - keeweb: 0.6.13
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - maps: 1.1.0
  - metadata: 0.19.0
  - news: 22.0.0
  - nextcloud_announcements: 1.16.0
  - notes: 4.8.1
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - onlyoffice: 8.1.0
  - password_policy: 1.17.0
  - photos: 2.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - support: 1.10.0
  - survey_client: 1.15.0
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_totp: 9.0.0
  - twofactor_webauthn: 1.2.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - video_converter: 1.0.6
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - encryption: 2.15.0
  - richdocuments: 8.1.1 (installed 8.1.1)
  - user_ldap: 1.17.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Last error entry in log is from 4 days ago, I ain't pasting the log here it's full of sensitive IPs etc
```

### Additional info

![image](https://github.com/nextcloud/server/assets/30209689/23509814-92e2-4656-a19e-de97c5c3f851)

![image](https://github.com/nextcloud/server/assets/30209689/c0650726-3b28-48d9-ba31-5928dec408ae)

```
root@b5f814c6be11:/# occ upgrade
Nextcloud is already latest version
```

**Comment by joshtrichards** [comment]
Hi @hugalafutro - Based on your report it appears you're using a Docker based image of some sort:

> updater page gives me 404 and occ upgrade claims is already latest version.
[..]
> Other Community project
[..]
> ```
> root@b5f814c6be11:/# occ upgrade
> Nextcloud is already latest version
> ```

So what you're seeing isn't a bug in `server`.  Every Docker-based NC image out there - even third-party ones - don't use the web updater and discourage manually upgrading via `occ upgrade` (since it'll break the image upgrade process as well as leave out depending updates).

You must update your image instead. You didn't say which image you're using, but check the maintainer's documentation for their process (and upgrade caveats, if any).

**Comment by hugalafutro** [comment]
I am using linuxserver.io image and have been updating the same image via the updater or occ upgrade when it timed out since NC 19 without any issue. My issue is that the web updater worked for years and suddenly doesn't exist. 

I will defer to your advice and wait for image upgrade though I haven't had to do that ever (image is auto updated so is always latest).

**Comment by joshtrichards** [comment]
https://info.linuxserver.io/issues/2023-06-25-nextcloud/

https://docs.linuxserver.io/images/docker-nextcloud#updating-nextcloud

**Comment by hugalafutro** [comment]
> https://info.linuxserver.io/issues/2023-06-25-nextcloud/

explains it, I wasn't aware of this recent change. Thanks for bringing it to my attention.
