### ISSUE TITLE
Add blurhash to images

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#39807]
Blurhash stores main average color of images.
We can then use this a colored placeholder while waiting for real thumbnails.
https://github.com/woltapp/blurhash

@artonge @ArtificialOwl implemented this in social

It would be great to have this in metadata table.
Photos (@skjnldsv) app and clients (showing gallery) can profit from this.

**Comment by skjnldsv** [comment]
Implemented

**Comment by tobiasKaminsky** [comment]
Thanks for implementing it.
@skjnldsv can you tell me where this is documented?

https://docs.nextcloud.com/server/latest/developer_manual/search.html?q=blurhash&check_keywords=yes&area=default does not show anything.

**Comment by skjnldsv** [comment]
Ask @ArtificialOwl and @artonge :)

**Comment by artonge** [comment]
> [@skjnldsv](https://github.com/skjnldsv) can you tell me where this is documented?

It is available as a metadata: `nc:metadata-blurhash`
