### ISSUE TITLE
[Bug]: It is impossible to restore a file from the trashbin containing Cyrillic characters in the name

### ISSUE THREAD

**Issue by skl256** [nextcloud/server#39823]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

It is impossible to restore a file from the trashbin containing Cyrillic characters in the name.
![image](https://github.com/nextcloud/server/assets/111241000/03eb91a0-1252-4e88-b269-35efbc23d4d2)

In browser console log: *ConsoleLogger.js:59 [ERROR] files: TypeError: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': String contains non ISO-8859-1 code point. {app: 'files', uid: 'admin-test', level: 2}*

### Steps to reproduce

1. Create a file containing Cyrillic characters in the name, for example *мир.md*
2. Delete file
3. Go to the trashbin, try to restore the file.

### Expected behavior

restore the file

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Chrome 115.0.5790.171 (latest), Win 11
nextcloud:27.0.2-fpm

**Comment by kesselb** [comment]
27.1.0 (2023-09-16)
