### ISSUE TITLE
[Bug]: Quota size is displayed higher than set (+7%)

### ISSUE THREAD

**Issue by skl256** [nextcloud/server#39830]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Quota size is displayed higher than set (+7%)
![image](https://github.com/nextcloud/server/assets/111241000/6f0027d2-7606-466a-9649-77613519d51e)
When the user was created, 10 GB was specified.
Displayed 10.7 GB.

### Steps to reproduce

1. Create a new user, specify a quota
2. Go to user account, view quota
3. The quota will be 7% more than set by the administrator

### Expected behavior

The quota will be equal to the value set by the administrator

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Reproducible both for a new installation and when upgrading from 25

**Comment by joshtrichards** [comment]
Duplicate of #39517.

There seems to be some mixing of GB and GiB.

@skl256 If that other issue appears to reflect the same situation you're reporting, please close this Issue here to avoid confusion and give #39517 a :+1: to help prioritize it. Thanks for your report!

**Comment by skl256** [comment]
Duplicate https://github.com/nextcloud/server/issues/39517
