### ISSUE TITLE
[Bug]: "The database is missing some indexes" after upgrages

### ISSUE THREAD

**Issue by olaulau** [nextcloud/server#39844]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

usually after a nextcloud upgrade, admin overview indicates "The database is missing some indexes".
maybe nextcloud upgrade process should do this by its own ?
I know this could be long (depending of the size of the instance), so maybeit could be optional ?

### Steps to reproduce

upgrade to 25.0.10

### Expected behavior

not having to run occ command by my own to solve this warning

### Installation method

None

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by olaulau** [comment]
on this instance I have an unsupported old mysql version.
sorry, forget about it.

**Comment by olaulau** [comment]
after a server migration, I'm now on a supported mysql version (on ubuntu 22.04).
after updating from nextcloud 25 to 26, admin dashboard warns me again about "The database is missing some indexes".
I have to execute "occ db:add-missing-indices" each update ...

**Comment by ChristophWurst** [comment]
> maybe nextcloud upgrade process should do this by its own ?
> I know this could be long (depending of the size of the instance), so maybeit could be optional ?

Exactly why it's not done by default. Nextcloud can work without the indices and so it speeds up the upgrade procedure if they are applied later.

This works as designed. It's not a bug.
