### ISSUE TITLE
Syncing large file ends with Connection Closed

### ISSUE THREAD

**Issue by ovidiub13** [nextcloud/server#3984]
### Steps to reproduce
Record large video file (over 2GB) and upload with instant upload from Android app

I've also tried downloading from my phone the video file onto my laptop, and letting the desktop app sync the file. It fails to sync every time.

### Expected behaviour
Upload to finish successfully.

### Actual behaviour
Upload fails from phone

### Server configuration
**Operating system**:
Linux
**Web server:**
nginx
**Database:**
mysql
**PHP version:**
7.1
**Nextcloud version:** (see Nextcloud admin page)
11.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated
**Where did you install Nextcloud from:**
https://hub.docker.com/r/wonderfall/nextcloud/

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Operating system:**
Linux
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Uncaught Error: Class 'OCP\Lock\ILockingProvider' not found in /nextcloud/lib/private/Files/View.php:1156 Stack trace: #0 [internal function]: OC\Files\View->OC\Files\{closure}() #1 /nextcloud/apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure)) #2 [internal function]: Icewind\Streams\CallbackWrapper->stream_close() #3 {main} thrown at /nextcloud/lib/private/Files/View.php#1156
```
</details>

**Comment by Bugsbane** [comment]
Often these sort of things seems to be triggered by the settings in php.ini, such as the max upload size or the RAM limit, rather than by Nextcloud itself. Have you checked these? (Being aware that there can be more than one php.ini file)

**Comment by ovidiub13** [comment]
I have checked the max upload and keep alive timeout of nginx. I haven't checked out the php.ini.

**Comment by MorrisJobke** [comment]
Please also check out https://docs.nextcloud.com/server/12/admin_manual/configuration_files/big_file_upload_configuration.html

if you still have problems in your instance first ask for help in the forums: https://help.nextcloud.com and if it turns out to be a reproducible problem on multiple instances we can check out if this is a bug.

Currently we don't see any problems with big files being uploaded. It works fine in other instances.

**Comment by georgeeerenee** [comment]
nice article

**Comment by Bugsbane** [comment]
Could this be related to:
https://github.com/nextcloud/server/issues/7799#issuecomment-368197818

**Comment by georgeeerenee** [comment]
Make sure you're not trying to sync one of the file types described in File Types That Should Not Be Synced to Workplace
Confirm that the files you are trying to sync are not open...i use third party software to easy sync like gs richcopy 360

**Comment by georgeeerenee** [comment]
Make sure you're not trying to sync one of the file types described in File Types That Should Not Be Synced to Workplace
Confirm that the files you are trying to sync are not open...i use third party software to easy sync like gs richcopy 360

**Comment by georgeeerenee** [comment]
NICE ARTICLE

**Comment by georgeeerenee** [comment]
"Make sure you're not trying to sync one of the file types described in File Types That Should Not Be Synced to Workplace
Confirm that the files you are trying to sync are not open...i use third party software to easy sync like gs richcopy 360"

**Comment by ovidiub13** [comment]
@georgeeerenee I've checked that. I don't experience this issue anymore, that's why I didn't reopen it.

**Comment by georgeeerenee** [comment]
"Make sure you're not trying to sync one of the file types described in File Types That Should Not Be Synced to Workplace
Confirm that the files you are trying to sync are not open...i use third party software to easy sync like gs richcopy 360"

**Comment by gregharvey** [comment]
We got a very similar behaviour for slower connections, in the end we realised it occurs if `request_terminate_timeout` is set too low in your PHP config. We found ours defaulted to `120s` and that was not enough time for the default 'chunk' size of 10MB to upload on some connections. We use PHP-FPM and there are a couple of things that are noteworthy:

1. While `www.conf` is the usual place for this setting, for us it was commented out and apparently default (`0` or off) but it *also* appeared in `php-fpm.conf` where it was set to `120s` - OK for most connections, but not enough time for a slow ADSL connection to upload 10MB (a chunk);

2. In this case increasing the chunk size in the database (as suggested for what I can only assume is another issue we're not experiencing) does not help at all, rather the opposite is true, you need to *either* increase `request_terminate_timeout` in PHP or decrease the chunk size.

In any case, the `request_terminate_timeout` value in PHP config was the key for us.
