### ISSUE TITLE
Backup through Web Console

### ISSUE THREAD

**Issue by madorian** [nextcloud/server#3986]
Today, if you want a complete backup, you need either SSH access to the server or work with the server provider to run a script dumping all data and databases to a location of your choosing.

Many providers offers nextcloud hosting, but do not grant SSH access. If you're unlucky, you may not get them to dump the database and data to a location for you to download. I think a complete backup should be able to be done through the web console admin login.

**Comment by MariusBluem** [comment]
Well... This may be a providers task 😅 ...or something for an app 😉

OwnBackup (https://apps.nextcloud.com/apps/ownbackup) for example is an 3rdparty app for Nextcloud, offering the possibility to backup and restore tables of your database.
