### ISSUE TITLE
Enable caldav push notifications by default

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#39862]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

As a user of Nextcloud who doesn't use connected clients I want to see a web notification for calendar events.

**Describe the solution you'd like**

Revert https://github.com/nextcloud/server/pull/16970

**Describe alternatives you've considered**

https://github.com/nextcloud/server/issues/39158

**Additional context**

Needs admin upgrade docs because it will have a big influence on existing setups.

**Comment by jancborchardt** [comment]
I’m fine with either, but I would say 27.1 to get it done?

**Comment by AndyScherzinger** [comment]
27.1 would also be fine with me 👍

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/pull/40103 should be ready for merge now. We are at RC3 of 27.1. I would veto merging this for 27 still because we wouldn't have time to roll back if there are issues with this change.

**Comment by ChristophWurst** [comment]
@AndyScherzinger @jancborchardt ^

**Comment by Linkinsoldier** [comment]
I hope this can be disables per settings in the feature. I don't have access to occ and therefore can not disable it ...!
