### ISSUE TITLE
Add icons to navigation of App Store items

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#3987]
With #3151 we introduced these nice little icons for navigation items on personal & admin settings pages.

![capture du 2017-01-19 03-10-45](https://cloud.githubusercontent.com/assets/925062/22091047/08dcc8be-ddf5-11e6-9f8b-4bbc74cb646e.png) <img width="349" alt="bildschirmfoto 2017-03-22 um 13 36 19" src="https://cloud.githubusercontent.com/assets/19711361/24198089/a02a2afa-0f04-11e7-8ff9-ead1e10790f4.png">

@jancborchardt @nextcloud/designers

**Comment by Bugsbane** [comment]
Just off the top of my head, we could use:

Enabled: A "power on" icon (the circle shape, broken at the top with a vertical bar)
Disabled: Same as enabled, but missing the vertical bar
Authentication: Key
Customization: Spanner
Files: Folder
Integration: Plug
Monitoring: Eye / the heartbeat icon from the server monitor app
Multimedia: Play icon
Office and text: The "T" icon used for text in most places
Organization: Filing cabinet?
Social and communication: Speech bubble
Tools: hammer
Developer documentation: Standard document icon

Most of these are already readily available and should be easy to add.

**Comment by MorrisJobke** [comment]
Fix is in #6627
