### ISSUE TITLE
File picker: All files/folders are shown with 0B

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#39880]
Follow-up for [#38926](https://github.com/nextcloud/server/issues/38926)

![2023-08-15 10_54_47-Files - Nextcloud – Mozilla Firefox](https://github.com/nextcloud/server/assets/1315170/780be0ed-e860-40de-a4dc-258274c047f3)

**Comment by susnux** [comment]
Probably should be moved to nextcloud-libraries/dialog (I have no permissions to do so).

Nevertheless I try to fix this within this week.

**Comment by AndyScherzinger** [comment]
@susnux I replicated the issue, you can't transfer between GH orgs.
