### ISSUE TITLE
Remove EXIF from publicly link generated shares for single photos/videos or the whole album

### ISSUE THREAD

**Issue by ph-256** [nextcloud/server#39894]
*Similar to the "Talk EXIF" Issue, but not exactly*

**Is your feature request related to a problem? Please describe.**
- Not an actual problem, it's just that I sometimes do not want to share EXIF data on publicly generated links

**Describe the solution you'd like**
- A toggle/checkbox at the sharing (like the "set expiration date" etc..) which can remove the EXIF only from the shared image/**album**, but actually keep the EXIF on the original photo/video

**Describe alternatives you've considered**
- Probably remove the "Info" button from the shared image, but that probably is a bad solution since the image can still be downloaded and the EXIF extracted, but still an alternative...

**Additional context**
[Screenshot - how I think it should look like](https://i.ibb.co/60B3Ftt/image.png)

### How to use GitHub
* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by ph-256** [comment]
i think i've got the wrong repo hero, i will reopen in in the nextcloud/photos repo

**Comment by meonkeys** [comment]
New issue is https://github.com/nextcloud/photos/issues/2008
