### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by cbrace** [nextcloud/server#3991]
Hi all,

I am encountering a memory leak on my NextCloud installation. With NC active, it is consuming all swap space.

### Steps to reproduce
1. login to server with ssh, start top, order by size
2. six or so httpd threads start growing in size, eventually consuming all available memory.
3. I disable NC in vhosts.conf, and the issue stops

### Server configuration
**Operating system**:
FreeBSD 11.0 RELEASE p8

**Web server:**
apache v2.4.5

**Database:**
mysql v5.6.35

**PHP version:**
v5.6.30
**Nextcloud version:** (see Nextcloud admin page)
11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
update

**Where did you install Nextcloud from:**
freebsd port

<summary>App list</summary>
Files
Activity
Gallery
Contacts
Calendar
Notes
Tasks
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

Insert your config.php content here
(Without the database password, passwordsalt and secret)
<?php
$CONFIG = array (
  'instanceid' => '516ae6f15e855',
  'passwordsalt' => 'XXX',
  'datadirectory' => '/mnt/disk10/data',
  'dbtype' => 'mysql',
  'version' => '11.0.2.7',
  'dbname' => 'owncloud',
  'dbhost' => '127.0.0.1',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'XXX',
  'installed' => true,
  'maintenance' => false,
  'theme' => '',
  'forcessl' => true,
  'trusted_domains' => 
  array (
    0 => 'lim.nl',
    1 => 'cbrace.nl',
  ),
  'mail_from_address' => 'root',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpport' => 10026,
  'mail_domain' => 'cbrace.nl',
  'secret' => 'XXX',
  'logfile' => '/var/log/nextcloud.log',
  'logtimezone' => 'Europe/Amsterdam',
  'trashbin_retention_obligation' => '180, auto',
  'overwrite.cli.url' => '/nextcloud',
  'overwritewebroot' => '/nextcloud',
  'loglevel' => 0,
  'memcache.local' => '\\OC\\Memcache\\APCu',
);
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

**Comment by tflidd** [comment]
Can you share how much memory is used by each process and how much memory you have in total?
Do you just connect the clients and do you have a lot of activity (up/downloads)?

**Comment by cbrace** [comment]
My instance of nextcloud is running on a 1GB VPS.

Typically I see six httpd threads using around 300K apiece, which start consuming more and more memory as soon as a desktop client is connected.

No desktop clients connected = no issues 

I now have a bash script which restarts apache24 when swap use reaches 90%.

When the nextcloud desktop client is connected it immediately startes growing and  the script restarts apache every 4-7 minutes.

My setup files syncs for a small number of clients -- just three desktops -- but a large number of files, around 500GB in total, of which only a tiny number change at a given time.

If I can supply additional information, just let me know.

**Comment by MorrisJobke** [comment]
If you run apache and mod_php a memory leak usually can't cause this issue. Mostly memory leaks only affect php-fpm. We have several instances running with php-fpm and can't see any trouble there.

If your memory get used extensively you maybe want to reduce the apache workers to fit into ram. Beside that we can't do much.
