### ISSUE TITLE
[Bug]: File cache running infinite loop in database

### ISSUE THREAD

**Issue by rarealphacat** [nextcloud/server#39920]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I migrated data folder to new HDD and Database has been running for weeks already with below info from Show full processlist,
```
SELECT `path` FROM `oc_filecache` WHERE (`storage` = 21) AND (`size` < 0) ORDER BY `fileid` DESC LIMIT 1
```
the process showed up for time 40 or so and new process under the same id comes up again.
I think it's part of the cron because cron stopped running and when I tried to run cron.php manually, two of the same info showed up.  I also tried to rebuild filecache with files:scan -all and same happened.

### Steps to reproduce

1. Migrate data folder 

### Expected behavior

Finish indexing quicker (at least not indexing for weeks?)

### Installation method

Official All-in-One appliance

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
PHP Warning:  Module "pdlib" is already loaded in Unknown on line 0
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.*",
            "***REMOVED SENSITIVE VALUE",
            "***REMOVED SENSITIVE VALUE"
        ],
        "default_phone_region": "HK",
        "filelocking.enabled": true,
        "memcache.local": "OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "preview_max_memory": 256,
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\Movie",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP4",
            "OC\\Preview\\MOV",
            "OC\\Preview\\MKV",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\AVI",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\SVG",
            "OC\\Preview\\Font",
            "OC\\Preview\\JPG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\SVG"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": 2,
        "logdateformat": "F d, Y H:i:s",
        "trashbin_retention_obligation": "30, 35",
        "updater.release.channel": "stable",
        "overwrite.cli.url": "https:\/\/"***REMOVED SENSITIVE VALUE\/nextcloud",
        "app_install_overwrite": [
            "camerarawpreviews",
            "ocdownloader",
            "epubreader",
            "facerecognition"
        ],
        "memories.exiftool": "\/var\/www\/html\/nextcloud\/apps\/memories\/lib\/..\/exiftool-bin\/exiftool-amd64-glibc",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "memories.vod.path": "\/var\/www\/html\/nextcloud\/apps\/memories\/exiftool-bin\/go-vod-amd64",
        "memories.vod.disable": true,
        "data-fingerprint": "6b1e9287d8eb7e1e03dcaae551e79592",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - audioplayer: 3.4.0
  - bruteforcesettings: 2.7.0
  - calendar: 4.4.4
  - camerarawpreviews: 0.8.2
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.3.2
  - contactsinteraction: 1.8.0
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - files: 1.22.0
  - files_accesscontrol: 1.17.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - groupfolders: 15.0.2
  - groupquota: 0.1.11
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - memories: 5.2.1
  - metadata: 0.19.0
  - music: 1.8.4
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - previewgenerator: 5.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recognize: 4.3.1
  - related_resources: 1.2.0
  - richdocuments: 8.1.1
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - spreed: 17.0.3
  - support: 1.10.0
  - survey_client: 1.15.0
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0
  - tasks: 0.15.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_totp: 9.0.0
  - twofactor_webauthn: 1.2.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - workflowengine: 2.9.0
Disabled:
  - apporder: 0.15.0 (installed 0.15.0)
  - circles: 27.0.1 (installed 23.1.1)
  - dashboard: 7.7.0 (installed 7.1.0)
  - encryption: 2.15.0
  - extract: 1.3.6 (installed 1.3.6)
  - facerecognition: 0.9.20 (installed 0.9.20)
  - federation: 1.17.0 (installed 1.10.1)
  - files_downloadactivity: 1.16.0 (installed 1.16.0)
  - files_mindmap: 0.0.28 (installed 0.0.28)
  - imageconverter: 1.3.5 (installed 1.3.5)
  - mail: 3.2.6 (installed 3.2.6)
  - maps: 1.1.0 (installed 1.1.0)
  - ocdownloader: 1.9.1 (installed 1.9.1)
  - ransomware_protection: 1.14.0 (installed 1.14.0)
  - recommendations: 1.6.0 (installed 0.5.0)
  - registration: 2.2.0 (installed 2.2.0)
  - richdocumentscode: 23.5.202 (installed 23.5.202)
  - sharebymail: 1.17.0 (installed 1.8.0)
  - talked: 0.5.0 (installed 0.5.0)
  - user_ldap: 1.17.0
  - video_converter: 1.0.6 (installed 1.0.6)
  - weather_status: 1.7.0 (installed 1.1.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Nothing relevant found
Error	no app in context	Sabre\DAV\Exception\BadRequest: Expected filesize of 10240000 bytes but read (from Nextcloud client) and wrote (to Nextcloud storage) 1892352 bytes. Could either be a network problem on the sending side or a problem writing to the storage on the server side.

    /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 149:

    OCA\DAV\Connector\Sabre\File->put()

    /var/www/html/nextcloud/apps/dav/lib/Upload/UploadFolder.php - line 50:

    OCA\DAV\Connector\Sabre\Directory->createFile("*** sensiti ... *")

    /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1098:

    OCA\DAV\Upload\UploadFolder->createFile("*** sensiti ... *")

    /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 504:

    Sabre\DAV\Server->createFile("*** sensiti ... *")

    /var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

    Sabre\DAV\CorePlugin->httpPut()

    /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 472:

    Sabre\DAV\Server->emit()

    /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 253:

    Sabre\DAV\Server->invokeMethod()

    /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 321:

    Sabre\DAV\Server->start()

    /var/www/html/nextcloud/apps/dav/lib/Server.php - line 364:

    Sabre\DAV\Server->exec()

    /var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:

    OCA\DAV\Server->exec()

    /var/www/html/nextcloud/remote.php - line 172:

    require_once("/var/www/ht ... p")
```

**Comment by joshtrichards** [comment]
How, precisely, did you migrate your data folder to a new HDD? If the paths stayed the same it should have been a no-op from NC's perspective.

Or did you also *move* the data folder to a different underlying filesystem path?

Also, what - if any, changes were made to your db environment during this change? Was your db moved/migrated somehow?

Does your system seem busy (CPU, disk I/I)?

Any warnings under Admin->Overview about missing indices?

How are things otherwise? Is all your data accessible via NC just fine?

**Comment by rarealphacat** [comment]
> How, precisely, did you migrate your data folder to a new HDD? If the paths stayed the same it should have been a no-op from NC's perspective.
> 
> Or did you also _move_ the data folder to a different underlying filesystem path?

I copied the data folder to a new HDD, with a different directory, then changed the config.php
  'datadirectory' => '/media/*new_location*/nextcloud/data', 
Then re-scanned the file with occ:file scan.

> Also, what - if any, changes were made to your db environment during this change? Was your db moved/migrated somehow?
> 

I didn't move/migrated the db and NC seems to be working normally.
E.g. I can copy, move, delete everything inside NC without problem.

> 
> Does your system seem busy (CPU, disk I/I)?
> 

SSD is constantly reading (I have NC running on SSD and data folder in HDD) and one of the cpu core is under 60% load because of it.
> 
> Any warnings under Admin->Overview about missing indices?
> 

There is no warnings about missing indices

> How are things otherwise? Is all your data accessible via NC just fine?
> 

all data is accessible just fine.

**Comment by rarealphacat** [comment]
I disabled all the apps and enabled them all then the problem is gone, must've been one of those app acting weird.

**Comment by joshtrichards** [comment]
Glad to hear it's quieted down. :+1: You may need to do some follow-up to clean-up since you changed the datadirectory:

https://docs.nextcloud.com/server/latest/admin_manual/issues/general_troubleshooting.html#troubleshooting-data-directory

It's entirely possible you have duplicate entries for all your files in the db if you didn't follow one of the above processes. 

e.g. https://help.nextcloud.com/t/howto-change-move-data-directory-after-installation/17170

If you run into any challenges related to that, please post them over at the [Nextcloud Help Forum](https://help.nextcloud.com/), since that's the best spot for configuration/local setup matters.

**Comment by rarealphacat** [comment]
It's happening again, the same loop running in database. I followed the instructions above and udpated the oc_storages locations. Should I re-open the issue?

**Comment by rarealphacat** [comment]
I put down log of db and I see this 

Time: 230826 21:50:19
User@Host: nextclouduser[nextclouduser] @ localhost []
Thread_id: 555  Schema: nextcloud  QC_hit: No
Query_time: 34.019169  Lock_time: 0.000029  Rows_sent: 1  Rows_examined: 9473306
Rows_affected: 0  Bytes_sent: 135
SET timestamp=1693083019;
SELECT `path` FROM `oc_filecache` WHERE (`storage` = 21) AND (`size` < 0) ORDER BY >
Time: 230826 21:50:54
User@Host: nextclouduser[nextclouduser] @ localhost []
Thread_id: 555  Schema: nextcloud  QC_hit: No
Query_time: 34.654061  Lock_time: 0.000022  Rows_sent: 1  Rows_examined: 9473848
Rows_affected: 0  Bytes_sent: 133
SET timestamp=1693083054;
SELECT `path` FROM `oc_filecache` WHERE (`storage` = 21) AND (`size` < 0) ORDER BY >
Time: 230826 21:51:30
User@Host: nextclouduser[nextclouduser] @ localhost []
Thread_id: 555  Schema: nextcloud  QC_hit: No
Query_time: 33.193308  Lock_time: 0.000021  Rows_sent: 1  Rows_examined: 9475424
Rows_affected: 0  Bytes_sent: 137
SET timestamp=1693083090;
SELECT `path` FROM `oc_filecache` WHERE (`storage` = 21) AND (`size` < 0) ORDER BY >
Time: 230826 21:52:04
User@Host: nextclouduser[nextclouduser] @ localhost []
Thread_id: 555  Schema: nextcloud  QC_hit: No
Query_time: 33.161851  Lock_time: 0.000020  Rows_sent: 1  Rows_examined: 9475968
Rows_affected: 0  Bytes_sent: 135
SET timestamp=1693083124;
SELECT `path` FROM `oc_filecache` WHERE (`storage` = 21) AND (`size` < 0) ORDER BY >
Time: 230826 21:52:38
User@Host: nextclouduser[nextclouduser] @ localhost []
Thread_id: 555  Schema: nextcloud  QC_hit: No
Query_time: 33.101301  Lock_time: 0.000021  Rows_sent: 1  Rows_examined: 9476458
Rows_affected: 0  Bytes_sent: 133

Notice how Rows_examined keep increasing, thus I went to check number of rows existed 
SELECT COUNT(*) FROM oc_filecache;
+----------+
| COUNT(*) |
+----------+
| 22677925 |
+----------+
Maybe it's not an infinite loop, it's just working hard on big db. I will keep this updated.

**Comment by rarealphacat** [comment]
Took a while, but it was finished after more than 2 months of processing.
