### ISSUE TITLE
App passwords can't be used to log into the web UI

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#3993]
* generate an app password
* use it to log into web UI
* expected: you are logged in
* actual: you are not logged in

@ChristophWurst

**Comment by MariusBluem** [comment]
Well ... I've tried this out some weeks ago too when I had too much time, but I see no real reason for doing this from a usecase POV 🤔

**Comment by MorrisJobke** [comment]
Okay - then it's not supported.
