### ISSUE TITLE
Support for Azure Communications Service (ACS) as a mail provider

### ISSUE THREAD

**Issue by misalcedo** [nextcloud/server#39959]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Setting up and maintaining my own SMTP server for e-mail notifications and password resets is difficult.

**Describe the solution you'd like**
Since I already run my deployment on Azure, it would be great to support Azure Communications Service (ACS) as a mail provider. Auth0 supports this in their system: https://auth0.com/docs/customize/email/smtp-email-providers/configure-azure-comm-service-as-smtp-email-provider and that is what I have in mind in terms of adding support here.

The idea is to add ACS as a option from the SMTP and Sendmail dropdown that takes a connection string instead of a password.

When hosting nextcloud on Azure, I want to avoid running my own SMTP server or relying on an existing mail provider.

**Describe alternatives you've considered**
I've considered creating a "robot" account using an existing mail provider like outlook or gmail. I've also considered e-mailing services like mailchimp. However, I would prefer to not have an actual inbox for e-mails and to centralize my bill in Azure.

**Additional context**

**Comment by solracsf** [comment]
This is a very specific request; as such, PRs are very welcome 👍

**Comment by kesselb** [comment]
We are using https://symfony.com/doc/current/mailer.html for mailing without any additional transport. 
The first step, to support an additional transport, is to add support for it to symfony mailer. 

This sounds like a great feature, but currently there are no plans to implement it. Therefore, I will close this ticket for now. This does not mean we don't want this feature, but it is not on our list of things to do soon. If someone wishes to implement this feature, we are happy to assist.
