### ISSUE TITLE
[Bug]: `default_language` and `default_locale` not work pt_BR

### ISSUE THREAD

**Issue by marcelomera** [nextcloud/server#39982]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

pt_BR language and locale don't work.
issue: #26599

> não funciona idioma e nem localidade pt_BR.

### Steps to reproduce

1. Login screen
2. Forgot password screen
3. Other screens

> 1. tela de login
> 2. tela de esqueci senha.
> 3. demais telas

### Expected behavior

It should have login, forgot password and other screens translated.

> Deveria trazer a página traduziada no login, no esqueci senha e demais.

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by GVodyanov** [comment]
Works now
