### ISSUE TITLE
systemtagsplugin.js generates empty ghost system tags.

### ISSUE THREAD

**Issue by rotdrop** [nextcloud/server#39983]
The following piece of code probably doesn't do what was expected if the systemTags data attribute is there but empty:

https://github.com/nextcloud/server/blob/a4f3088c6eab2c76bf0c64d39d5493dfe184593e/apps/files/js/systemtagsplugin.js#L92-L94

The following happens

1. `systemTags` variable will be the empty string
2. `systemTags?.split?.('|')` will then happily be executed by the browser, calling the split method on this empty string
3. according to MDN this results in `[ '' ]`, i.e. an array containing an empty string
4. later on this will then generate an empty "ghost" system tag in the UI which somehow garbles the file-list

See 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split?retiredLocale=de#using_split

Please note that the same file here

https://github.com/nextcloud/server/blob/a4f3088c6eab2c76bf0c64d39d5493dfe184593e/apps/files/js/systemtagsplugin.js#L77

make sure that the systemTags data attribute **is** defined.

**Comment by joshtrichards** [comment]
No longer applicable. Code has been replaced as in 28 via #40284
