### ISSUE TITLE
[Bug]:  The word "Current version" in the "files_versions" app is not translating.

### ISSUE THREAD

**Issue by vishnu-n23** [nextcloud/server#39986]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The word "Current version" in the "files_versions" app is not translating. Additionally, it is not present in the Transifex source language file.
![image](https://github.com/nextcloud/server/assets/141107715/c605ac60-4f78-4edf-8e78-0bf8e6470271)

### Steps to reproduce

1. Change the language(Select a language other than English)
2. Open 'Files' app
3. Open the context menu for any any files, and click details
4. Click the 'Versions' tab (in right sidebar)

### Expected behavior

The word "Current Version" should be translated to the selected to the selected language.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment]
cc @artonge
