### ISSUE TITLE
File requests / Files Drop for the community

### ISSUE THREAD

**Issue by maprambo** [nextcloud/server#4]
Firstly, I think you made the right decision. There are several things that could be improved from a user's perspective. I'd have never posted this at ownCloud, as there were many issues that were months or even years old and nobody cared about the community. Of course I'll split my suggestions to multiple issues.

Community edition users need Files Drop, too.
I've had several situations in which I asked friends to send me a photo or video (messengers often compress these) or some big files. Just making one folder and share a link with write permissions isn't the ideal situation because of privacy concerns.

**Comment by tobiasKaminsky** [comment]
I do not understand the concept of files drop.
Do you want to have a public link where all users can put files in it, but do not see the previous content?

**Comment by maprambo** [comment]
Yes. https://www.bitblokes.de/2015/05/file-drop-anonymes-hochladen-bei-owncloud-8-0-3/

**Comment by mar1u5** [comment]
Now I understand which function you mean 😅 

To clarify what it is meant for: 

> It is the perfect replacement for attaching large files to email, maintaining an FTP server, and commercial file-sharing services.
_https://doc.owncloud.org/server/8.0/admin_manual/enterprise_files_drop/files_drop.html_

**Comment by maprambo** [comment]
Didn't think of that. Maybe in the future, when it will be recoded?

**Comment by LukasReschke** [comment]
The feature will very be rewritten as open-source component. :)
