### ISSUE TITLE
Allow setting third person pronouns in user's profile

### ISSUE THREAD

**Issue by auroraanna** [nextcloud/server#40017]
**Is your feature request related to a problem? Please describe.**
When referencing a person in a conversation in third person you might want to use third person pronouns instead of their name. Assuming pronouns based on someone's appearance, name, … can be hurtful to the person being referred, because they might not like those pronouns to be used for them.

**Describe the solution you'd like**
A field in the user's profile for entering the pronouns they'd like other people to use. Having an explicit entry for pronouns in a user's profile means you don't have to assume, ask them or look in their profile's bio for pronouns which makes it way easier and more convenient to use their preferred pronouns.

There should be default options like she/her/…, he/him/… and they/them/… but you should also be able to enter custom ones like [fae/faer/faer/faers/faerself](https://pronouns.within.lgbt/fae/faer/faer/faers/faerself) with every grammatical version specified.

**Describe alternatives you've considered**
None.

**Additional context**
This is probably an issue to implement because language have different rules for third person pronouns. Some might not have 5 versions (Subject, Object, Dependent Possessive, Independent Possessive, Reflexive) like English.

Supporting neopronouns with the custom option might be controversial. Neopronouns never really caught on outside of maybe queer communities but this would at least support specifying a generic gender-neutral they/them/…

**Comment by knobhead** [comment]
I would like to support this proposal. I manage a Nextcloud for a small community/Verein with a diverse and inclusive user base and we have a "put pronouns on your name tag in real-life" policy. :-)

If I find the time I'd like to experiment with the [Override Translation](https://apps.nextcloud.com/apps/l10n_override) App to rename/re-purpose one of the more enterprisey profile fields like "Role" oder "Headline".

**Comment by skjnldsv** [comment]
Here we go!
Nextcloud 31 🚀🌈

**Comment by Maximize1107** [comment]
This is a horrible idea.

**Comment by Tzemran** [comment]
How can I remove this?  I would not like to insult my users like this especially given that the basic part mentions plurals as pronouns.  Many of us are educated and know what a pronoun is so this is insulting to us.  Why can't people be treated equally?  This is the exact opposite of inclusive given that it excludes 97% of people.
