### ISSUE TITLE
feature - GUI for max upload size

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/server#40027]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
(relaying from social media..)
"Add gui feature to increase max upload size. 
I’m aware of how to manually increase this via configs and whatnot but it’s an archaic process that could be simplified. "

**Describe the solution you'd like**

Add gui feature to increase max upload size.

**Comment by SriRam-Macha** [comment]
this would be really help full

**Comment by cribbageSTARSHIP** [comment]
Please do this

**Comment by skjnldsv** [comment]
Sorry, but I think this doesn't belong in Nextcloud.
We expect people to be able to maintain and understand webserver and php configs.
To add on top of that, only apache with specific configs would allow user configurations.

I think this is for a custom app, but not made by Nextcloud.
I suggest you post it here: https://help.nextcloud.com/c/apps/app-ideas/21 ? :eyes:
