### ISSUE TITLE
🚢 Ship composer and package lock files

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#40072]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Currently it is not possible to run a license scan on a package/build since we do not ship [composer.lock](https://github.com/nextcloud/server/blob/master/composer.lock) and [package-lock.json](https://github.com/nextcloud/server/blob/master/package-lock.json).

**Describe the solution you'd like**
Ship composer and package lock-files in our release archives for server and the apps in the release archive(s)

**Describe alternatives you've considered**
Currently none. A scan would be possible based on the release tags while that is not the same source as being able to do this based on the content of a release tar-ball.

**Comment by blizzz** [comment]
> Server bit not merged yet.

link?

**Comment by juliushaertl** [comment]
Sorry was referring to the release script not server https://github.com/nextcloud-gmbh/release-script/pull/132

**Comment by blizzz** [comment]
that makes sense. yes, still on me list.

**Comment by AndyScherzinger** [comment]
Merged, thanks @blizzz closing as resolved then 👍

**Comment by susnux** [comment]
Do we still need them now that we ship REUSE?
