### ISSUE TITLE
Disable reset password link

### ISSUE THREAD

**Issue by Bullnados** [nextcloud/server#4008]
Is this also possible in nextcloud:
https://github.com/owncloud/core/issues/27440

**Comment by MariusBluem** [comment]
Maybe something like `'lost_password_link' => 'false',` is possible 🤔

**Comment by BornToBeRoot** [comment]
@MariusBluem But then you are not able to set a custom link anymore... both should be possible... 
changing the link or disable it completly

**Comment by MariusBluem** [comment]
Well, my idea was that an URL is still possible 😁

**Comment by Bullnados** [comment]
Also the reset password textfield should be replaced.

**Comment by nickvergessen** [comment]
lets use 'disabled' like upstream does.

**Comment by nickvergessen** [comment]
patch at https://github.com/nextcloud/server/issues/4809
