### ISSUE TITLE
[Bug]: url share not working

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#40104]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

One way to share a file to a colleague is to just copy over the URL in your browser location bar to a specific file. This works, seemingly, for some people - but it doesn't for me 😢 

### Steps to reproduce

1. (colleague) copy URL to a file
2. (me) paste in top or click link
3. it starts loaded, then I get redirected to https://cloud.nextcloud.com/apps/files/files?dir=/&fileid=350

### Expected behavior

Load the url! It works if I copy a URL myself...

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by jospoortvliet** [comment]
Issue seems to be that the 'mount point' for me is different than for the other user - in this case, by a completely trivial capital character (`/Marketing/` instead of `/marketing/`). As the file id is there, an user would expect the file to be found anyway - which works file when simply a 'internal share' is used (https://`server`/f/`fileID`) - in other words, dir seems to take precedence over file-ID.

Fascinatingly, loading the page often works initially - loading the right folder, then suddenly going back and redirecting to a different file. other colleagues have seen the redirect happen to random other file ID's.

What I would expect to happen is a check if the location given in `dir` can be loaded, failing that, simply using the fileID to locate the file and folder. Perhaps more robust would be to simply ignore `dir`and go to the file ID but I suppose files with the same ID can be in multiple locations...

**Comment by joshtrichards** [comment]
Same as #32177?
