### ISSUE TITLE
virtual hosting feature

### ISSUE THREAD

**Issue by abh2001mah** [nextcloud/server#4012]
Do you have plans to support virtual hosting feature like Amazon S3 does? (top level folder can be used as buckets)
http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html

**Comment by MorrisJobke** [comment]
I guess we don't plan to support multi-tentant that directly. You could accomplish this by using different config files and the same code or just place the code there twice, because you need to maintain those two instances for upgrades anyway separately.

Right @karlitschek?

**Comment by karlitschek** [comment]
right :-)
