### ISSUE TITLE
500 error, don´t know what it means

### ISSUE THREAD

**Issue by MisterCutely** [nextcloud/server#4014]
georgehrke told me to open a new issue for my 500 error.
Link to first problem [https://github.com/nextcloud/calendar/issues/359](url)
Somebody who can explain me the problem and how i can fix it?

### Steps to reproduce
1. Start Nextcloud
2. Open calendar app
3. calender symbol is circling and doesn´t shops the main calendar. Oder calendars were shown.

### Expected behaviour
Calendar should be shown with all events

### Actual behaviour
Main calendar is not shown. And error in Java console.

### Server configuration
**Operating system**: Don´t know (Hoster is www.all-inkl.com)

**Web server:** Don´t know (Hoster is www.all-inkl.com)

**Database:** Myphp

**PHP version:** 7.1.1

**Nextcloud version:** 11.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** nextcloud.com

**List of activated apps:**
Tasks, Mail, contacts,

**The content of config/config.php:**
original untouched

**Are you using external storage, if yes which one:** Dropbox

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox 51.0.1.

**Operating system:** Windows 7

#### Web server error log
`Sabre\VObject\InvalidDataException: Unsupported VALUE parameter for DTEND property. You supplied ""

    /www/htdocs/w0086fc8/cloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 453: Sabre\VObject\Document->createProperty('DTEND', NULL, Array)
    /www/htdocs/w0086fc8/cloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 234: Sabre\VObject\Parser\MimeDir->readProperty('DTEND;TZID=Euro...')
    /www/htdocs/w0086fc8/cloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 217: Sabre\VObject\Parser\MimeDir->parseLine('DTEND;TZID=Euro...')
    /www/htdocs/w0086fc8/cloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 181: Sabre\VObject\Parser\MimeDir->parseLine('BEGIN VEVENT')
    /www/htdocs/w0086fc8/cloud/3rdparty/sabre/vobject/lib/Parser/MimeDir.php - line 89: Sabre\VObject\Parser\MimeDir->parseDocument()
    /www/htdocs/w0086fc8/cloud/3rdparty/sabre/vobject/lib/Reader.php - line 46: Sabre\VObject\Parser\MimeDir->parse('BEGIN VCALENDAR...', 0)
    /www/htdocs/w0086fc8/cloud/3rdparty/sabre/dav/lib/CalDAV/Backend/AbstractBackend.php - line 142: Sabre\VObject\Reader read('BEGIN VCALENDAR...')
    /www/htdocs/w0086fc8/cloud/apps/dav/lib/CalDAV/CalDavBackend.php - line 1123: Sabre\CalDAV\Backend\AbstractBackend->validateFilterForObject(Array, Array)
    /www/htdocs/w0086fc8/cloud/apps/dav/lib/CalDAV/Calendar.php - line 248: OCA\DAV\CalDAV\CalDavBackend->calendarQuery('2', Array)
    /www/htdocs/w0086fc8/cloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php - line 624: OCA\DAV\CalDAV\Calendar->calendarQuery(Array)
    /www/htdocs/w0086fc8/cloud/3rdparty/sabre/dav/lib/CalDAV/Plugin.php - line 250: Sabre\CalDAV\Plugin->calendarQueryReport(Object(Sabre\CalDAV\Xml\Request\CalendarQueryReport))
    [internal function] Sabre\CalDAV\Plugin->report('{urn ietf param...', Object(Sabre\CalDAV\Xml\Request\CalendarQueryReport), 'calendars/Benny...')
    /www/htdocs/w0086fc8/cloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /www/htdocs/w0086fc8/cloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 718: Sabre\Event\EventEmitter->emit('report', Array)
    [internal function] Sabre\DAV\CorePlugin->httpReport(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /www/htdocs/w0086fc8/cloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /www/htdocs/w0086fc8/cloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method REPORT', Array)
    /www/htdocs/w0086fc8/cloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /www/htdocs/w0086fc8/cloud/apps/dav/lib/Server.php - line 227: Sabre\DAV\Server->exec()
    /www/htdocs/w0086fc8/cloud/apps/dav/appinfo/v2/remote.php - line 30: OCA\DAV\Server->exec()
    /www/htdocs/w0086fc8/cloud/remote.php - line 165: require_once('/www/htdocs/w00...')
    {main}`

#### Nextcloud log (data/nextcloud.log)

`{"reqId":"WNPC2VUNm@kAAFruyrcAAAAI","remoteAddr":"141.113.11.13","app":"PHP","message":"Argument 1 passed to OCA\\Mail\\Model\\IMAPMessage::hordeToAssoc() must be an instance of Horde_Mail_Rfc822_Address, instance of Horde_Mail_Rfc822_Group given, called in \/www\/htdocs\/w0086fc8\/cloud\/apps\/mail\/lib\/Model\/ConvertAddresses.php on line 74 and defined at \/www\/htdocs\/w0086fc8\/cloud\/apps\/mail\/lib\/Model\/ConvertAddresses.php#34","level":3,"time":"2017-03-23T12:43:05+00:00","method":"GET","url":"\/index.php\/apps\/mail\/accounts\/-1\/folders\/YWxsLWluYm94ZXM%3D\/messages?from=0&to=20&filter=","user":"Benny","version":"11.0.0.10"}
`

#### Browser log

`"Deprecation warning: use moment.updateLocale(localeName, config) to change an existing locale. moment.defineLocale(localeName, config) should only be used for creating a new locale See http://momentjs.com/guides/#/warnings/define-locale/ for more info."  moment-with-locales.js:282`
`NS_BINDING_ABORTED: Component returned failure code: 0x804b0002 (NS_BINDING_ABORTED) [nsIStreamListener.onDataAvailable]  WebRequest.jsm:231`
`Das textContent-Attribut von Attributen sollte nicht mehr verwendet werden. Verwenden Sie value stattdessen.  app.min.js:2:4429
/remote.php/dav/calendars/Benny/bennyoccalendar/ 500  app.min.js:2`
`A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise
Date: Fri Mar 17 2017 07:29:31 GMT+0100
Full Message: Error: page-thumbnail:error
Full Stack: observe@resource://gre/modules/BackgroundPageThumbs.jsm:116:22
BackgroundPageThumbs._onCaptureOrTimeout@resource://gre/modules/BackgroundPageThumbs.jsm:305:7
Capture.prototype._done/done@resource://gre/modules/BackgroundPageThumbs.jsm:451:7
Capture.prototype._done@resource://gre/modules/BackgroundPageThumbs.jsm:471:7
Capture.prototype.notify@resource://gre/modules/BackgroundPageThumbs.jsm:428:5
  BackgroundPageThumbs.jsm:116`

**Comment by MorrisJobke** [comment]
cc @ChristophWurst @georgehrke

**Comment by georgehrke** [comment]
`/remote.php/dav/calendars/Benny/bennyoccalendar/ 500 app.min.js:2`

The server is never supposed to die with a 500, but catch broken calendar data imho.
That's why I asked @MisterCutely to report a bug here.

https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/CalDavBackend.php#L1141
`validateFilterForObject` will parse the object. So we basically have to add a try-catch here.
