### ISSUE TITLE
[Bug]: Breeze Dark theme - black app icons

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/server#40158]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Reported via social media [here](https://twitter.com/digidweb/status/1696364060088971705)

Summary:

"If one chooses a light color (e.g yellow or light green) while using the Breeze Dark theme, the app icons in the menu bar turn black when it'd be nice if they were white like the system icons."

![image](https://github.com/nextcloud/server/assets/7018928/9eec18b2-599a-4e62-85c3-f255af14d209)

### Steps to reproduce

1. Change theme to Breeze Dark (or presumably any dark theme)
2.
3.

### Expected behavior

Icons would be more legible if they we're assigned an appropriate contrast to the theme menu background. In the case of Breeze Dark, white app icons and text are preferable.

### Installation method

None

### Nextcloud Server version

25

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by gerbrent** [comment]
note: may be partly related to #35730

**Comment by kesselb** [comment]
Breeze Dark is a community app: https://github.com/mwalbeck/nextcloud-breeze-dark

**Comment by gerbrent** [comment]
Filed under community app:

https://github.com/mwalbeck/nextcloud-breeze-dark/issues/338
