### ISSUE TITLE
[Bug]: [DOCS] nextcloud changelog entries for MAJOR release are missing any useful information

### ISSUE THREAD

**Issue by fermulator** [nextcloud/server#40155]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Consider: https://nextcloud.com/changelog/

Up to Nextcloud 24, the changelog for a major release (#.0.0) correctly contained useful information, and usually a post to a blog entry explaining all the new features, major changes, and any breaking changes.

However since Nextcloud 25 and onwards, these are missing entirely!

IF we search github issues (nextcloud/server), we can find posts like this:
* https://github.com/nextcloud/server/issues/32117 (v25)
* https://github.com/nextcloud/server/issues/34692 (v26)
* https://github.com/nextcloud/server/issues/37039 (v27)
^ exactly what is missing

I have also found https://docs.nextcloud.com/server/stable/admin_manual/release_notes/index.html ...

### Steps to reproduce

1. Be a nextcloud home/lab admin
2. Try to keep up with latest/stable releases
3. Read changelogs for major upgrades

### Expected behavior

Can the changelog entries (https://nextcloud.com/changelog) _at least_ contain a link to those github issue entries and the admin link, and ideally also include a high level summary of the big important items?

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment]
> Up to Nextcloud 24, the changelog for a major release (#.0.0) correctly contained useful information, and usually a post to a blog entry explaining all the new features, major changes, and any breaking changes.

![image](https://github.com/nextcloud/server/assets/3902676/669bf8c6-cfd3-4f00-bcb8-2126a9ed055d)

That's still there.
