### ISSUE TITLE
ebook reader update fails

### ISSUE THREAD

**Issue by joebobtechie** [nextcloud/server#4015]
### Steps to reproduce
1. Nextcloud alert to update ebook reader,
2. Navigate to addons menu
3. Push update button

### Expected behaviour
The ebook reader addon should update

### Actual behaviour
Detailed logs
Preparing update
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE `oc_reader_bookmarks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `user_id` VARCHAR(64) DEFAULT '' NOT NULL, `file_id` BIGINT UNSIGNED NOT NULL, `type` VARCHAR(32) DEFAULT '' NOT NULL, `name` VARCHAR(512) DEFAULT '' NOT NULL, `value` VARCHAR(512) DEFAULT '' NOT NULL, `content` VARCHAR(4096) DEFAULT NULL, `last_modified` BIGINT UNSIGNED DEFAULT 0, INDEX reader_bookmarks_file_id_index (`file_id`), INDEX reader_bookmarks_user_id_index (`user_id`), INDEX reader_bookmarks_name_index (`name`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.
### Server configuration
**Operating system**:
linux

**Web server:**
apache
**Database:**
mysql
**PHP version:**
5.6
**Nextcloud version:** (see Nextcloud admin page)
11.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated
**Where did you install Nextcloud from:**
Softaculous
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Not possible -- the site now shows the update notice and the error.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
This is a problem of this app. We can't do here anything, because this app creates an index that is too big on mysql only. Please report this to the apps bug tracker.

**Comment by joebobtechie** [comment]
Okay, clicking on app update is bad. Got it. Is there a way to uninstall the app that doesn't involve the admin page? Because I'm locked out of that by the failed update. Thanks.

**Comment by MorrisJobke** [comment]
You can run occ app:disable ebook on the Colman slime as the Webserver user if you have shell access.

**Comment by joebobtechie** [comment]
Don't think I do, but thanks, anyway.

**Comment by MorrisJobke** [comment]
Sorry there was a autocomplete mess up. I meant "command line". Otherwise delete the apps entries from the oc_appconfig table. Sad to here that it messed up that hard, but on the other side I also have very little ideas how to catch that properly.

Maybe we add another check for the update.

**Comment by MorrisJobke** [comment]
@joebobtechie Sorry for the trouble with this app - I opened #4035 to address this issue.
