### ISSUE TITLE
New apps menu, visual glitches

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#4016]
Steps to reproduce:

1. add enough apps so that the "..." menu appears
2. resize the browsers window to a point sort before it switches to the mobile view
3. click on the '... menu.

Before clicking the '...' menu:

![appmenu1](https://cloud.githubusercontent.com/assets/1589737/24256011/5ebbfe0c-0fe7-11e7-8f53-9f9647444576.png)

After clicking the '...' menu:

![appmenu2](https://cloud.githubusercontent.com/assets/1589737/24256027/6ab8e350-0fe7-11e7-8942-f615005d63b9.png)

cc @nextcloud/designers @eppfel

**Comment by MorrisJobke** [comment]
@schiessle Rule number 1: Fill the issue template or at least state the browser.

**Comment by MorrisJobke** [comment]
I tested this in IE11, Firefox, Safari and Chrome and it works

**Comment by MorrisJobke** [comment]
> resize the browsers window to a point sort before it switches to the mobile view

Ah it's only a super tiny range for the width.

**Comment by MorrisJobke** [comment]
I tested and it turns out to be between 601px and at least 846px - so not tiny as I thought.

**Comment by MorrisJobke** [comment]
@juliushaertl Could you have a look?

**Comment by juliushaertl** [comment]
Fix is in #4026 

Please test :wink:

**Comment by schiessle** [comment]
@juliushaertl thanks for the fast fix! 👍
