### ISSUE TITLE
[Bug]: Favorites list click folder icon to jump incorrectly

### ISSUE THREAD

**Issue by pzytydy** [nextcloud/server#40171]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![nextcloud-router-jump](https://github.com/nextcloud/server/assets/44193243/03a1e1b3-64f6-4ee4-b036-382db99cd931)

In the favorite list, click the folder icon to jump incorrectly

### Steps to reproduce

1. Favorites folder
2. Click the favorite folder icon in the favorite list to return to the list of all files, but the content of the files is incorrect [Note: It is not 100% reproducible]

### Expected behavior

Ability to correctly jump to folder directories

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

Other

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by skjnldsv** [comment]
[Fixed already ](https://github.com/nextcloud/server/issues/38834)
