### ISSUE TITLE
⛑️ Polishing for new sharing design and flow 🤝

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#40172]
Follow-up to #26691 listing the remaining open issues to be fixed in `master` as well as `stable27`

---

https://github.com/nextcloud/server/pull/39472#issuecomment-1680970478
## Share list
- [x] BUG: Quick access menu should close when click outside

### Bugs specific to share settings
- [x] BUG: Setting "Allow public upload" disabled should also disable options to set file drop, according permissions

![Screenshot 2023-08-17 at 12 23 33](https://github.com/nextcloud/server/assets/3404133/e4e97815-69a5-42a3-9daa-6ddc34552165)

- [x] BUG: Lots of optional share settings for the ones that should affect front-end:
  - [x] BUG: Public upload can be blocked
- [x] BUG: https://github.com/nextcloud/server/issues/40289
---

- [x] BUG: https://github.com/nextcloud/server/issues/40228 - Edit (louis): seem unrelated
- [x] BUG: https://github.com/nextcloud/server/issues/40299

---

- [x] BUG: Create a new share to a user, change to custom permission, click save share, go back to the share details -> now update and share check-boxes are missing (the custom permissions are the same as view only, but nevertheless the check-boxes should of course still be available)
- [x] BUG: Creating shares should probably not reload the full file list. Edit (louis): only an issue with 27 as the logic to handle share changes is not fine-grained enough to only refresh the share status of a file. Also, it was not introduced by the new sharing flow.
- [x] BUG: Related resources should not appear in the share details view - https://github.com/nextcloud/server/pull/40365

## Non-blocking
- [x] Accessibility fixes for quick menu
- [x] "Delete share" button does not need to be sticky, can just be a tertiary button (no background by default) below the advanced settings toggle (not inside advanced settings)
- [ ] The "Cancel" and primary button on the bottom need a backdrop to separate them a bit from the background, best a fade from color-main-background on the bottom to transparent on the top.
- [ ] Currently links are sorted below emails once created, but sorting should be: Links, mails, users
- [x] Too many share saved/updated notifications when updating/creating shares
- [ ] QA: Needs side by side testing if all old options are possible or also properly limited with the new one
- [ ] #40436
- [ ] If allow public upload admin setting is unchecked we should rename "Allow upload and editing" to "allow editing" and file drop / create permission should be disabled state

---

https://github.com/nextcloud/server/pull/39472#pullrequestreview-1599979725

### Follow-ups:
- [x] Switching between permissions presets should not close the advanced settings view
- [ ] The content of the sidebar is scroll-able when it should only be the content of the share tab

![Screenshot from 2023-08-29 11-52-15](https://github.com/nextcloud/server/assets/6653109/7e844261-a80a-41fb-a8d4-5a8cfb9f7575)

### UI comments:
- [x] Button at the bottom of the details view should not move when scrolling to the bottom
- [x] "Delete share" button text seems smaller than other buttons
- [ ] It is confusing to have the download permission under "Custom permissions" as it is not taken into account for bundles

**Comment by AndyScherzinger** [comment]
> It is confusing to have the download permission under "Custom permissions" as it is not taken into account for bundles

@artonge can you elaborate on this item, what is meant by it?

**Comment by AndyScherzinger** [comment]
@Fenn-CS better to move the remaining items to a new issue and close this one. The closed ones are resolved with 27.1.0 the remaining ones would then be 27.1.1 and the ticket can't reflect that when not split up 😊

**Comment by sorbaugh** [comment]
@AndyScherzinger on it

**Comment by AndyScherzinger** [comment]
remaining items have been moved to https://github.com/nextcloud/server/issues/40438 as a follow-up issue
