### ISSUE TITLE
adjust icon of shared state in broadcrumb

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#40202]
> Shared
> ![image](https://user-images.githubusercontent.com/14975046/264994803-cd58618a-c5c7-465d-8ce6-b3d234eb819a.png)

I am not sure about this icon. Shouldn't we better use a different icon, e.g. this one?
![image](https://github.com/nextcloud/server/assets/42591237/b55b0294-fa07-4d1a-94dc-be2cca1cabd8)
https://fonts.google.com/icons?icon.style=Outlined&icon.set=Material+Symbols&selected=Material+Symbols+Outlined:folder_shared:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=shar

_Originally posted by @szaimen in https://github.com/nextcloud/server/issues/40192#issuecomment-1702890351_

cc @nextcloud/designers

**Comment by szaimen** [comment]
Also the normal share icon should be better visible then for accessbility reasons:

> Not shared
> ![2023-09-01_18-10](https://user-images.githubusercontent.com/14975046/265073102-f8d4ab7b-d43b-4f51-82e8-a17df32e20cd.png)

**Comment by jancborchardt** [comment]
We should consider moving the "share" icon in general to this more understandable one: https://fonts.google.com/icons?selected=Material%20Icons%3Aperson_add_alt_1%3A

**Comment by jancborchardt** [comment]
We should make sure that the icon there in the breadcrumb is the same as the folder has in the file list of its parent folder next to the "Shared" indicator.

If it’s not shared, it should be the icon as mentioned:
https://fonts.google.com/icons?selected=Material%20Icons%3Aperson_add_alt_1%3A

@szaimen @marcoambrosini can one of you take this on? :)

**Comment by szaimen** [comment]
> @szaimen @marcoambrosini can one of you take this on? :)

I fear I cannot work on this today, because going on vacation tomorrow and need to do other stuff as preparation for that...
