### ISSUE TITLE
Should the empty folder button ask to upload something instead of going back?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#40205]
Should the empty folder button ask to upload something instead of going back?

See 
![image](https://github.com/nextcloud/server/assets/42591237/29810902-83b7-412d-864d-82e600626168)

cc @nextcloud/designers

**Comment by jancborchardt** [comment]
Agree with @szaimen – "Back" button doesn’t really make sense there, "+ New" like on the top would be good.

**Comment by jancborchardt** [comment]
Another small enhancement one of you could implement, right @marcoambrosini @szaimen? :)

**Comment by szaimen** [comment]
> Another small enhancement one of you could implement, right @marcoambrosini @szaimen? :)

I fear I cannot work on this today, because going on vacation tomorrow and need to do other stuff as preparation for that...

**Comment by szaimen** [comment]
🎉🎉🎉
