### ISSUE TITLE
[Bug]: Cannot leave share from conversation

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/server#40228]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I cannot leave some of the shares.

This happens on c.nc.com, with, for example, file identified by 6924818

I noticed that all the shares on which I experience this behaviour are shared via a conversation.

### Steps to reproduce

1. Select the share that you want to leave
2. From the 3-dots menu, select "Leave this share"
3. Reload the page

### Expected behavior

The share is deleted.

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by artonge** [comment]
@pmarini-nc 
I could not reproduce. Can you share more details and also whether you have some errors in the browser console ?

**Comment by pmarini-nc** [comment]
Hello, I cannot see those files anymore.. Maybe it got fixed with the new version?

**Comment by artonge** [comment]
Let's close, feel free to reopen if you have more information :)
