### ISSUE TITLE
🔎 AS - Leverage existing filter logic to limit search in specific apps (e.g. in:files)

### ISSUE THREAD

**Issue by sorbaugh** [nextcloud/server#40239]
The goal is to reuse existing filter logic such as "in:files", "in:settings", and so on but make them more discoverable.

Current state:

<img width="254" alt="Bildschirmfoto 2023-09-04 um 18 09 06" src="https://github.com/nextcloud/server/assets/62374139/7c418e8b-f855-4dd2-9a97-ce8bcbf94859">

**Comment by Fenn-CS** [comment]
Completed via : https://github.com/nextcloud/server/pull/40823
