### ISSUE TITLE
🔎 AS - Implement results listing. The "Load more results" should continue to behave like now as loading the next few results in place.

### ISSUE THREAD

**Issue by sorbaugh** [nextcloud/server#40237]
Basically we should just "move" the current logic to the new search dialog. Mockup for reference:

<img width="736" alt="Bildschirmfoto 2023-09-04 um 13 50 04" src="https://github.com/nextcloud/server/assets/62374139/87924e86-8405-4819-a954-2166cd253804">

**Comment by Fenn-CS** [comment]
Completed via https://github.com/nextcloud/server/pull/40823
