### ISSUE TITLE
🖼️🔄️ Synchronization of the two files

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#40243]
Implement storing of the metadata linking iOS Live Photos files and respect them on DAV operations applying the same DAV operation to the respective other file.

- [x] Allow clients to set a `livephoto` metadata in the `OC\Metadata` API through WebDAV. This metadata is set for the two files and contains the `fileid` of the other file. Another solution would be to use a header, but not a fan of multiplying custom headers. Also, allowing clients to write the `livephotos` metadata allows writing it for already uploaded files
- [ ] Add listeners to react to `Node*Event` - 
    - [x] `NodeDeletedEvent` to remove the second file
    - [x] `NodeRenamedEvent` to rename the second file
        - [x] `BeforeNodeRenameEvent` to block the operation if one of the two files cannot be renamed (ex: file with the same name at the location, or quota limitation, or … ?)
        - [ ] Test when renamed file is a share
    - [ ] `NodeCopiedEvent` to copy the second file
        - [ ] `BeforeNodeCopiedEvent` to block the operation if one of the two files cannot be copied (ex: file with the same name at the location, or quota limitation, or … ?)
        - [ ] Test when renamed file is a share
- [ ] Optional: block write permissions on the `.jpg` to prevent inconsistencies?

**Comment by sorbaugh** [comment]
subtask to #40242
