### ISSUE TITLE
🖼️ iOS live photos support

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#40242]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Support iOS Live Photos

This is splitted into 2 part, supporting them regarding DAV operations on the server (i.e. when the `jpeg` is moved, also move the `mov` file.

- [x] #40243
- [ ] #40244

**Describe alternatives you've considered**

**Additional context**

**Comment by sorbaugh** [comment]
cc @tobiasKaminsky this might also need additional work in the clients?

**Comment by AndyScherzinger** [comment]
> cc @tobiasKaminsky this might also need additional work in the clients

Step 1 would be iOS client sending/setting the meta data.

Step 2 would be the clients marking live photos as such combining the image and video on the visualization, specifics to be discussed with @nextcloud/designers, other platforms just display the image and add a 'live' icon to it. 

Step 3 is to combine dav operations to be applied to both files.

Step 4 display live photos on all clients.

Step 4 would be the stretch goal

**Comment by tobiasKaminsky** [comment]
For Step 2: https://support.apple.com/guide/iphone/edit-live-photos-iphd8dbb3291/ios

**Comment by tobiasKaminsky** [comment]
server: https://livephotos.ltd.nextcloud.com
user: ios

Webdav property: <nc:metadata-files-live-photo/>

On server:
sample.jpg: <nc:metadata-files-live-photo>sample.mov</nc:metadata-files-live-photo>
sample.mov: <nc:metadata-files-live-photo>sample.jpg</nc:metadata-files-live-photo>

**Comment by AndyScherzinger** [comment]
closing, left open is sub-task to display live photos on web, tracked in the remaining task
