### ISSUE TITLE
🔎 AS - Implement new, extended search provider API within files to support the new filter criteria

### ISSUE THREAD

**Issue by sorbaugh** [nextcloud/server#40249]
Depending on what is possible with WebDAVs search capabilities, might need to break this one into further tasks.

## For date 

* Files: modification date (probably more relevant than creation date)
* Calendar: event date (probably more relevant than creation date)
* Deck card: due date (probably more relevant than creation date, if it exists)
* Talk: message date
* Mail: message date
* Contacts: ? birthday
* General fallback would be "Modified date"
* etc. …

## For people

* Files: owners and sharees
* Calendar: participants
* vDeck card: assignee
* Talk: message poster and/or person replied to
* Mail: sender and recipients
* Contacts: the contact itself, possibly manager also
* General fallback would be sharing

**Comment by ChristophWurst** [comment]
Is there a rough timeline for the first version of the API apps integrated with or a draft of it?

**Comment by ChristophWurst** [comment]
> Is there a rough timeline for the first version of the API apps integrated with or a draft of it?

@Altahrim ^ :)

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/pull/40618?

**Comment by Altahrim** [comment]
@ChristophWurst Oh, I forgot this one, sorry…

Yes, the draft is in #40618. We are not sure of the implementation yet, and all early reviews are welcome :)
