### ISSUE TITLE
🔎 AS - "Places" dropdown should be converted to show 3 apps as chips, then a 3-dot menu, otherwise it is not as discoverable

### ISSUE THREAD

**Issue by sorbaugh** [nextcloud/server#40240]
For reference, this is the original mockup referred to in this issue:
<img width="494" alt="Bildschirmfoto 2023-09-04 um 18 20 02" src="https://github.com/nextcloud/server/assets/62374139/58ad0cb6-06c1-48b5-a28f-738d298eda21">

And this is the CURRENT mockup, but without the apps as chips. Basically we should use this mockup BUT add the chips from the old mockup.
<img width="736" alt="Bildschirmfoto 2023-09-04 um 13 50 04" src="https://github.com/nextcloud/server/assets/62374139/bfeac769-6026-4360-9fe6-461b8dde96da">

**Comment by Fenn-CS** [comment]
Completed via : https://github.com/nextcloud/server/pull/40823
