### ISSUE TITLE
↔️ Define an initial default order for apps in top bar

### ISSUE THREAD

**Issue by sorbaugh** [nextcloud/server#40256]
subtask to #40241 

Probably makes sense to have to status quo as the default order -> Dashboard first, Files second, etc.

**Comment by sorbaugh** [comment]
Observation was made that the initial default order should stay as is (meaning the ordering # set by each individual app). If this can be the case, we can omit this subtask and close.

What do you think @AndyScherzinger ?

**Comment by AndyScherzinger** [comment]
Ye, I agree. Should work implicitly 👍

**Comment by sorbaugh** [comment]
^ @susnux @come-nc

**Comment by susnux** [comment]
So this is already done as every app defines an order in the appinfo, that order defines the default menu order.
For Nextcloud maintained apps that order is purposely chosen for best user experience.
