### ISSUE TITLE
[Bug]: Uneven spacing between input checkboxes in file setting modal

### ISSUE THREAD

**Issue by vishnu-n23** [nextcloud/server#40283]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

<img width="955" alt="image" src="https://github.com/nextcloud/server/assets/141107715/45758cc6-75ed-479a-975c-59f8220fb717">

Different vertical spacing between inputs(checkboxes) in 'file setting' and 'additional setting' sections in the file settings modal. When hovering the checkbox inputs under the file setting section background if the input option is highlighting like when we are hovering a button, but not such interactive behaviors (styling on hovering) were given to the checkbox inputs under the 'additional setting' section.

### Steps to reproduce

1. Open Files app
2. Click File settings(bottom left of the screen) to open file setting modal

### Expected behavior

Vertical spacing between the inputs under the 'file setting' and 'additional setting' in the files settings modal should be same, also the Interactive behaviors(styling on hovering, clicking, etc..) should be uniform.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by skjnldsv** [comment]
This needs to be fixed on each app:
- https://github.com/nextcloud/recommendations/blob/d875ac8a1db556cac23cdc11f9dab8eae1f6f6a1/src/components/Settings.vue#L7-L15
- https://github.com/nextcloud/text/blob/3470ecbbe4ec7ae65620c541a6ad657a04bb0548/src/views/FilesSettings.vue#L23-L30
cc @juliushaertl @gary-kim

**Comment by juliushaertl** [comment]
Text is fixed with https://github.com/nextcloud/text/pull/6178

**Comment by skjnldsv** [comment]
Recommendations: https://github.com/nextcloud/recommendations/pull/817
