### ISSUE TITLE
 Slashes in filenames on Google Drive External storage causes sync error

### ISSUE THREAD

**Issue by moretocome** [nextcloud/server#4028]
The title says it all. Whenever someone creates a document on Google Docs that contains a slash ```/``` in the filename, it causes a sync-error in my Nextcloud client. I expect other illegal characters could also produce the same error, but I have only experienced it with slashes.

Login into Drive and changing the file name fixes the error, but maybe some type of escape function should be implemented for illegal file name characters.

NC and External app are both most recent stable versions and the server is a RPI with the latest Raspbian.
 
### Steps to reproduce
1. Enable External Sites App
2. Add Google Drive to Nextcloud
3. Create a document in Google Docs

### Expected behaviour
The file from Google Drive should sync with Nextcloud

### Actual behaviour
The file produces a continuous sync error in the Nextcloud Client

### Server configuration
Latest Raspbian

**Web server:**
NginX

**Database:**
MariaDB

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
11.0.2 (latest stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
Manual install

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Google Drive

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Oauth

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Firefox

**Operating system:**
Linux Mint 18.1

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by konstin** [comment]
I have a related problem: For folders with slashes in their name, only the part after the slash is shown and the folder can not be accessed in any way.

**Comment by moretocome** [comment]
Sounds like the same issue.

**Comment by APenketh** [comment]
Also getting the same issue with any file within Google Drive that contains "/". Will happily post any logs etc that are required if needed.

**Comment by y0va** [comment]
Problem persists.
Nextcloud docker 12.0.5

**Comment by MorrisJobke** [comment]
As this is a separate app: please report it in that repo https://github.com/NastuzziSamy/files_external_gdrive/
