### ISSUE TITLE
Custom permissions should show permissions in subline

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#40289]
<img width="366" alt="2023-09-06 12_10_41-Shared with others - Nextcloud – Mozilla Firefox" src="https://github.com/nextcloud/server/assets/1315170/0983de6b-087d-41ce-a154-6ac51b3ab99e">

* customer permissions should be in a separate line 
* icons are mission (optional - only to be done if quick fix, else just the subline)

**Comment by juliushaertl** [comment]
Seems only an issue on stable27, maybe caused by the different version of `@nextcloud/vue` being used.
