### ISSUE TITLE
[Bug]: Unable to invite guest

### ISSUE THREAD

**Issue by Fenn-CS** [nextcloud/server#40299]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Can't create guest share.
On attempt the following is thrown `Error creating the share: Unknown share type`

### Steps to reproduce

1. Set up https://github.com/nextcloud/guests/
2. Open the sharing sidebar
3. Enter an email address
4. Click Invite guest
5. Click on "Save share"

### Expected behavior

Save share, should successfully register a new share of type guest. 

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by juliushaertl** [comment]
I think we should still call the handlers upfront before triggering the new sharing flow, so that the guest user is already created, iirc @jancborchardt also agreed on that in one of our calls.
