### ISSUE TITLE
Hardening with GeoIP block (little bit) for documentation

### ISSUE THREAD

**Issue by Bullnados** [nextcloud/server#4031]
Would be nice to insert that point into "Hardening and Security Guidance". People searching for "hardening nextcloud" will forwardes to that documents. Perhaps there are more easy hardenings?
I know there are a lot of exceptions like VPN, if supported by webhoster and perhaps not working with Amazon/Google/Dropbox drives. But it is a small step

For all-inkl webhoster and .htaccess/Apache copy simple that code to your .htacces to block all countries instead of Germany

### Whitelist
(all countries blocked instead of exception)

> GeoIPEnable On
Order deny,allow 
Deny from all #
Allow from env=Whitelist
SetEnvIf GEOIP_COUNTRY_CODE DE Whitelist

### Blacklist
(all countries allowed instead of exception)

> GeoIPEnable On
Order deny,allow 
Deny from all #
Deny from env=Blacklist
SetEnvIf GEOIP_COUNTRY_CODE CN Blacklist
SetEnvIf GEOIP_COUNTRY_CODE RU Blacklist
SetEnvIf GEOIP_COUNTRY_CODE LT Blacklist

Here is a list of codes Alpha-2 is working
https://en.wikipedia.org/wiki/ISO_3166-1

**Comment by MorrisJobke** [comment]
@Bullnados Could I ask you to open this in https://github.com/nextcloud/documentation/issues Thanks

This is the server code repo :)

Maybe @MariusBluem Wants to look into this then. It also looks like you need an additional apache module do use the geoIPEnable or am I wrong?

**Comment by Bullnados** [comment]
Sry
