### ISSUE TITLE
Bug or feature: tempnam(): file created in the system's temporary directory at 

### ISSUE THREAD

**Issue by Bullnados** [nextcloud/server#4033]
Webhosting by all-inkl
**Web server:**
apache
**Database:**
MySQL 5.7.15
**PHP version:**
7.1.1
**Nextcloud version:** (see Nextcloud admin page)
11.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
11.0.0

#### Nextcloud log (data/nextcloud.log)

> Error PHP	tempnam(): file created in the system's temporary directory at /www/htdocs/user/folder/folder/lib/private/TempManager.php#126	2017-03-23T08:55:24+0100
Error	PHP	tempnam(): file created in the system's temporary directory at/www/htdocs/user/folder/folder/lib/private/TempManager.php#89	2017-03-23T08:55:21+0100

Here someone wrote it's feature not a bug. But nextcloud throws an error
https://github.com/Glavin001/atom-beautify/issues/1108#issuecomment-272012827

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by Bullnados** [comment]
It seems that this error is thrown only one time. After 27.03 I deleated the log and AG 29.03 the error came again. Since that date no new error message is shown

**Comment by MorrisJobke** [comment]
We use following values to determine in which directory it should be created: https://github.com/nextcloud/server/blob/0215b004da6af887b3e3efa28c425d41a1c76b9b/lib/private/TempManager.php#L216-L233

Feel free to set the config.php value `tempdirectory`to use a different directory (or the php.ini value `upload_tmp_dir`).

**Comment by Bullnados** [comment]
I  had still set the tempdirectory in config.php because of the open tmp dir error with all-inkl. 
I try new permissions perhaps 640\644 don't know exactly is too permissive
