### ISSUE TITLE
Cypress theming admin test fails

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#40347]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
stable27 branch cypress test fails, see https://cloud.cypress.io/projects/37xpdh/runs/8779/overview/e1e5926a-2386-45dd-875e-9d10ee51d0fa?roarHideRunsWithDiffGroupsAndTags=1

<img width="617" alt="2023-09-08 09_38_22-Server – Mozilla Firefox" src="https://github.com/nextcloud/server/assets/1315170/bde38506-1705-40da-b872-da5aa569b901">

**Describe the solution you'd like**
Fix failing test on stable27

**Comment by solracsf** [comment]
Is this fixed now?

**Comment by AndyScherzinger** [comment]
yepp, seems fixed 👍
