### ISSUE TITLE
Changes for developers & admins for Nextcloud 28

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/server#40362]
Not sure, if I am the only dev who misses the announcement change. I'll take the liberty of pinning this here.

* [Changes for developers & admins for Nextcloud 28](https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_28.html)
* [Announcement of moving this information to the docs](https://help.nextcloud.com/t/changes-to-documentation-handling/161436)

**Comment by SystemKeeper** [comment]
Yes, see https://help.nextcloud.com/t/changes-to-documentation-handling/161436

**Comment by dartcafe** [comment]
Nice. Wouldn't it be a good idea to announce the change there, where the annoncement usually is, instead of the forum?

**Comment by dartcafe** [comment]
I would say, it is outdated and can be closed...
