### ISSUE TITLE
Show tags in public shares

### ISSUE THREAD

**Issue by Glandos** [nextcloud/server#40364]
Since the merge of #37938 (Great job!), another use case rised for me: the display of tags in public shares.

I am managing a list of sheet music (along with some records) for a choir, and make it available for all singers. Each song has its own directory, and now, I'm trying to make this list easier to browse for new people, by adding tags with year in it (as 2021 for a song we sang in 2021…). I find it far better than using sub-directories, either for discoverability and for consistency: since we can re-use an old song, it can be both in 2019 and 2023.

Anyway, for now, tags are not a public data, so I open this ticket to track this feature. If it doesn't meet project goals, it can be closed, but it will at least be there for the record.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by skjnldsv** [comment]
@nextcloud/designers is this something that we want? Can easily be done on 31 with the new public view

**Comment by szaimen** [comment]
Yes, I would say this makes sense in general if it does not reveal sensitive data...

**Comment by szaimen** [comment]
🎉🎉🎉
