### ISSUE TITLE
share link not removed from share overview when using delete button

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#40396]
See 

https://github.com/nextcloud/server/assets/42591237/5b5404ec-d2bb-415d-b2e5-fa202848e825

**Comment by szaimen** [comment]
Cc @AndyScherzinger @sorbaugh

**Comment by Fenn-CS** [comment]
@szaimen Thanks for reporting this, would send in a fix for this soon

**Comment by szaimen** [comment]
Fixed with https://github.com/nextcloud/server/pull/40448
