### ISSUE TITLE
⛑️ Polishing for new sharing design and flow -> 27.1.2

### ISSUE THREAD

**Issue by sorbaugh** [nextcloud/server#40438]
This is a follow up to #40172 where the blocking issues were resolved for 27.1.0. Below are the enhancements planned for 27.1.1 and 27.1.2

- [x] The "Cancel" and primary button on the bottom need a backdrop to separate them a bit from the background, best a fade from color-main-background on the bottom to transparent on the top.
- [x] Currently links are sorted below emails once created, but sorting should be: Links, mails, users
- [x] QA: Needs side by side testing if all old options are possible or also properly limited with the new one
- [x] If allow public upload admin setting is unchecked we should rename "Allow upload and editing" to "allow editing" and file drop / create permission should be disabled state
- [x] The content of the sidebar is scroll-able when it should only be the content of the share tab
![image](https://github.com/nextcloud/server/assets/62374139/bc0dae89-80fe-48e6-9968-157f4be0e028)
- [x] It is confusing to have the download permission under "Custom permissions" as it is not taken into account for bundles
- [x] [Do not show unnecessary password expired message #40493](https://github.com/nextcloud/server/issues/40493)

**Comment by Fenn-CS** [comment]
>  It is confusing to have the download permission under "Custom permissions" as it is not taken into account for bundles

@artonge Please, what is the action point for this? It needs clarification

> The "Cancel" and primary button on the bottom need a backdrop to separate them a bit from the background, best a fade from color-main-background on the bottom to transparent on the top.

Not clear to me.

> The content of the sidebar is scroll-able when it should only be the content of the share tab

Does not scroll like that for me, any information on how to make it happen?

>  Currently links are sorted below emails once created, but sorting should be: Links, mails, users

Not the case (Missing context?).
![Screenshot from 2023-09-20 17-45-23](https://github.com/nextcloud/server/assets/14317775/c760cbd4-8da4-4e31-9e5f-7fbb12877fa6)


cc: @AndyScherzinger @jancborchardt @juliushaertl

**Comment by artonge** [comment]
> @artonge Please, what is the action point for this? It needs clarification

It is not a file permission, but a setting of the share. You have to select custom permissions to be able to toggle it. If you toggle the download checkbox, the permissions summary is not changed. All of that is weird.

**Comment by Ornanovitch** [comment]
Hi, thanks for those improvements. There is also this strange layout when in custom mode:

![Screenshot 2023-09-26 at 10-14-42 CPG - Fichiers - Brume](https://github.com/nextcloud/server/assets/34077099/502c9cc8-49df-4609-9e6e-d7df69684fa9)

- buttons are floating on overflow
- delete button has a white background on dark mode, and it's weird to see it as such a dominating "first possible action" above cancel and update, which are more common

A last comment, but this is only my opinion:

![Screenshot 2023-09-26 at 10-22-02 coordination - Fichiers - Brume](https://github.com/nextcloud/server/assets/34077099/261de8a4-20c9-4ae9-bafc-d2cb3408363d)

I think it is disturbing to see this new box only after selecting the Custom mode. This sudden appearance can led the user to think this is "where it happens", while this is just another presentation of the previous dropdown:

![Screenshot 2023-09-26 at 10-26-23 CPG - Fichiers - Brume](https://github.com/nextcloud/server/assets/34077099/7a161446-6f8d-4507-aaf5-9e5f5a5de227)

I hope you'll understand this point.

Best

**Comment by AndyScherzinger** [comment]
Thanks for the feedback @Ornanovitch 

looping in @nextcloud/designers for feedback on https://github.com/nextcloud/server/issues/40438#issuecomment-1735068722 - Thanks

**Comment by Fenn-CS** [comment]
Thanks for the feedback @Ornanovitch ....

Those are being improved here : https://github.com/nextcloud/server/pull/40629

cc: @AndyScherzinger
