### ISSUE TITLE
[Bug]: Upgrade from 25.0.11 to 26.0.6 failed

### ISSUE THREAD

**Issue by JB1985** [nextcloud/server#40456]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

```
Nextcloud Updater - version: v25.0.3-2-gd49ee0d

Current version is 25.0.11.

Update to Nextcloud 26.0.6 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-26.0.6.zip
Open changelog ↗

Steps that will be executed:
[ ] Check for expected files
[ ] Check for write permissions
[ ] Create backup
[ ] Downloading
[ ] Verify integrity
[ ] Extracting
[ ] Enable maintenance mode
[ ] Replace entry points
[ ] Delete old files
[ ] Move new files in place
[ ] Done

Start update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✘] Check for expected files failed
The following extra files have been found:
    package.json
    package-lock.json
    composer.json
    composer.lock

Update failed. To resume or retry just execute the updater again.
Nextcloud is already latest version
```

### Steps to reproduce

1. Update your Nextcloud from 25.0.10 to 25.0.11
2. Start the update again and try to upgrade from 25.0.11 to 26.0.6
3.

### Expected behavior

Upgrade to 26.0.6 without any failed message.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Any chance you are/were running an RC release?

What's the `$OC_VersionString` in your `version.php`?

**Comment by calran** [comment]
I'm seeing the same issue and output using the command line updater. Same OS, same stack.
`$OC_VersionString = '25.0.11';`

**Comment by meisterleise** [comment]
I've got the same problem with the backend updater.

![image](https://github.com/nextcloud/server/assets/14863470/a76adab5-9447-4350-900d-2c0264056b9f)

**Comment by joshtrichards** [comment]
Looks like these files got included in the v25.0.11 final release artifacts. I think that was an intentional change in NC27, but not sure about earlier releases since the v25 `updater` app doesn't have the handling added for them like in nextcloud/updater#488

Cc: @blizzz

**Comment by axelrathey** [comment]
Hi,
is it useful to remove (may be safe before) these 4 files manually?
Thanks Axel

**Comment by blizzz** [comment]
> Looks like these files got included in the v25.0.11 final release artifacts. I think that was an intentional change in NC27, but not sure about earlier releases since the v25 `updater` app doesn't have the handling added for them like in [nextcloud/updater#488](https://github.com/nextcloud/updater/pull/488)
> 
> Cc: @blizzz

That's accurate, yes. The updater fixes should have gone also into 26 and 25 releases, somehow that slipped my mind 😞

We stopped shipping the latest releases of 26 and 25 via the update server now. The next steps are to bring the updater adjustments down to the affected versions, and do a hotfix release.

Those who are on 25.0.11 and 26.0.6 already and want to do the next update have to delete the mentioned files manually I am afraid.

**Comment by blizzz** [comment]
> Is it useful to remove (may be safe before) these 4 files manually?

Yes, just remove them, and re-run the update.

**Comment by axelrathey** [comment]
As you stopped shipping the latest release of 26 and 25 my nextcloud 25.0.11 does not provide me the update to 26.0.6 any more.
Axel

**Comment by solracsf** [comment]
@blizzz shouldn't the update be rolling again ? 🤔 
```
# php updater.phar
Nextcloud Updater - version: v26.0.0beta2-9-g64e2e4c dirty

Current version is 26.0.6.

No update available.

Nothing to do.
```

**Comment by solracsf** [comment]
Updates are still failing, even for minor releases:

```
php updater.phar --no-backup
Nextcloud Updater - version: v26.0.0beta2-9-g64e2e4c dirty

Current version is 26.0.6.

Update to Nextcloud 26.0.7 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-26.0.7.zip
Open changelog ↗

Steps that will be executed:
[ ] Check for expected files
[ ] Check for write permissions
[ ] Create backup
[ ] Downloading
[ ] Verify integrity
[ ] Extracting
[ ] Enable maintenance mode
[ ] Replace entry points
[ ] Delete old files
[ ] Move new files in place
[ ] Done

Start update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✘] Check for expected files failed
The following extra files have been found:
    composer.lock
    package.json
    package-lock.json
    composer.json

Update failed. To resume or retry just execute the updater again.
```

**Comment by blizzz** [comment]
> Updates are still failing, even for minor releases, unless these 4 files are handly removed previously:

Yes, we cannot fix the shipped 26.0.6 and 25.0.11. The updater of the currently installed versions runs. So, when you run any of these versions, the files have to be removed manually unfortunately.

**Comment by LeSpocky** [comment]
Same behavior for minor update from 25.0.11 to 25.0.12!

[Screenshot_20230921_134748](https://github.com/nextcloud/server/assets/661636/6241e354-663a-431e-95bc-54900532a2cf)

**Comment by blizzz** [comment]
> Same behavior for minor update from 25.0.11 to 25.0.12!
> 
> [Screenshot_20230921_134748](https://github.com/nextcloud/server/assets/661636/6241e354-663a-431e-95bc-54900532a2cf)

please see https://github.com/nextcloud/server/issues/40456#issuecomment-1729312370

**Comment by blizzz** [comment]
Issue is resolved once on 25.0.12 or 26.0.7 (only upgrading from 25.0.11 or 26.0.6 is affected).

**Comment by meisterleise** [comment]
And how can I find this files???
Have about 50 files of each of this filenames like "composer.lock"
Instructions please!
Thank you.

**Comment by blizzz** [comment]
Delete the four files composer.json, composer.lock, package.json and package-lock.json from your nextcloud directory.

**Comment by meisterleise** [comment]
thank you. But I don't have a package.json in the root directory of nc. Where can I find it?

<img width="260" alt="image" src="https://github.com/nextcloud/server/assets/14863470/63fdae2b-5435-439d-bcb8-c6fa9f92d38c">

**Comment by meisterleise** [comment]
I have finally been able to update it. Thank you for your help and patience, @blizzz

**Comment by solracsf** [comment]
For those with the same problem, a command like this should do the job:

`cd /var/www/nextcloud; rm -f composer.lock package.json package-lock.json composer.json; php updater/updater.phar`

**Comment by zyll71** [comment]
Same issue when updating from 25.0.11 to 25.0.12.

**Comment by meisterleise** [comment]
@zyll71 This is already known. You've to do the workaround as explained.

**Comment by axelrathey** [comment]
Ok, I got it,
I removed the 4 files 
    package.json
    package-lock.json
    composer.json
    composer.lock
mentioned above via winscp from the nextcloud directory.
Then I installed updated from 25.0.11 to 25.0.12 without problems
Then I tested if version 25.0.12 works good.
As free space on my webspace becomes small I had to remove the backup files of the old 25.0.11
Then I upgraded to 26.0.7
The Upgrade to 26 had run a bit longer then the update 25.0.11 --> 25.0.12
Now I have Nextcloud 26.0.7  on my manitu.de webspace

Now it provides me Version 27.1.1, but I will wait because of 2 Apps are not compatible.

The above 4 file namews are back in my nextcloud directory. I will see whether I need them for version 27 or whether I have to remove them too.

Axel

**Comment by roberix** [comment]
Hi.

My NC Server (currently at 25.0.10 Enterprise) still does not offer me 25.0.12 within the updater. Does anyone here knows if this is normal or do I have the same problems as described in this issue?

Thanks. 

BR

Rob

**Comment by blizzz** [comment]
> Hi.
> 
> My NC Server (currently at 25.0.10 Enterprise) still does not offer me 25.0.12 within the updater. Does anyone here knows if this is normal or do I have the same problems as described in this issue?
> 
> Thanks.
> 
> BR
> 
> Rob

Will be in the course of today

**Comment by roberix** [comment]
> > Hi.
> > My NC Server (currently at 25.0.10 Enterprise) still does not offer me 25.0.12 within the updater. Does anyone here knows if this is normal or do I have the same problems as described in this issue?
> > Thanks.
> > BR
> > Rob
> 
> Will be in the course of today

Thanks for the update.

Regards

Rob
