### ISSUE TITLE
[Bug]: CPU busy after upgrade from 26 to 27.0.2

### ISSUE THREAD

**Issue by marcotrevisan** [nextcloud/server#40457]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I upgraded from 26 to 27.0.2 last week. 
Took the occasion to also upgrade php from 8.0 to 8.2 (using php-fpm, enable opcache, jit and so on...).
I noticed that after the upgrade, one or two cores are almost always busy (php-fpm processes).
The database is not that busy so I guess there must be something else going on which is CPU intensive. 
The instance is consuming overall more CPU than version 26.  
I hence decided to install xdebug in the instance and enable profiling for some seconds when there's no load by users. There's almost no user interaction, only some clients performing PROPFINDS.

Here are the "cachegrind" output files:
https://nextcloud.mrtrevisan.duckdns.org/index.php/s/pQg7zCjycppaNe2

I can monitor it for longer time windows and provide further dumps if it can be helpful. 

### Steps to reproduce

1. Upgrade from 26 to 27.0.2
2. Monitor CPU usage (i.e. using "top" and Zabbix for a complete picture)
3.

### Expected behavior

No major CPU usage change.

### Installation method

Other Community project

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.gate39.it",
            "localhost"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "default_language": "it",
        "default_locale": "it_IT",
        "default_phone_region": "IT",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.0.2.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtpport": "587",
        "maintenance": false,
        "theme": "",
        "allow_local_remote_servers": true,
        "preview_max_filesize_image": -1,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc"
        ],
        "loglevel": 2,
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "diagnostics.logging": true,
        "diagnostics.logging.threshold": 1000,
        "updater.release.channel": "stable",
        "versions_retention_obligation": "10, 60",
        "trashbin_retention_obligation": "10, 65",
        "activity_expire_days": 180,
        "app_install_overwrite": [
            "impersonate"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - announcementcenter: 6.6.2
  - appointments: 1.15.3
  - approval: 1.1.0
  - bruteforcesettings: 2.7.0
  - calendar: 4.5.0
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - collectives: 2.7.1
  - comments: 1.17.0
  - contacts: 5.4.0
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.11.0
  - drawio: 2.1.2
  - external: 5.2.1
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_automatedtagging: 1.17.0
  - files_bpm: 1.2.0
  - files_lock: 27.0.1
  - files_pdfviewer: 2.8.0
  - files_retention: 1.16.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - files_zip: 1.4.0
  - firstrunwizard: 2.16.0
  - forms: 3.3.1
  - groupfolders: 15.2.0
  - guests: 2.5.0
  - impersonate: 1.14.0
  - keeweb: 0.6.13
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mail: 3.4.0
  - metadata: 0.19.0
  - nextcloud_announcements: 1.16.0
  - notes: 4.8.1
  - notifications: 2.15.0
  - notify_push: 0.6.3
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - previewgenerator: 5.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - quicknotes: 0.8.10
  - related_resources: 1.2.0
  - richdocuments: 8.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - spreed: 17.0.3
  - support: 1.10.0
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - tables: 0.6.0
  - tasks: 0.15.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_email: 2.7.3
  - twofactor_totp: 9.0.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflow_script: 1.12.0
  - workflowengine: 2.9.0
Disabled:
  - checksum: 1.2.2 (installed 1.2.2)
  - encryption: 2.15.0
  - files_external: 1.19.0 (installed 1.19.0)
  - integration_openproject: 2.4.4 (installed 2.4.4)
  - maps: 1.1.1 (installed 1.1.1)
  - recommendations: 1.6.0 (installed 1.3.0)
  - suspicious_login: 5.0.0
  - user_ldap: 1.17.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by marcotrevisan** [comment]
Just for the records, I plan to upgrade to 27.1.x asap now that it is out,  probably the next weekend. Maybe the upgrade will solve my issue (or maybe not). Anyway I preferred to and share some profiler data using the 27.0.2 version, I hope it will help.

The php-8.2 configuration is quite similar to the php-8.0 one. As far as I know there aren't any critical/important changes on the php configuration to do. Am I correct?
If you like I can share the php-fpm ini file (and the www pool config file too)

Thanks !

**Comment by joshtrichards** [comment]
Couple quick thoughts:

- Does the issue immediately come back after resetting FPM or does it take some time? Any patterns there?
- Any disk I/O? What's memory usage like? Constant per process? Up and then back down? Etc.
- Any Nextcloud logs? Maybe try setting `loglevel` to `1` or even briefly to `0` to see what shows up 
- Any warnings under Admin->?

**Comment by marcotrevisan** [comment]
Hi @joshtrichards, 

-  I can confirm that the issue immediately come back after resetting FPM. That's what made me suspect it may be not due to a background job
- Disk I/O is low, memory usage stays at around 1 GB. You can see it pops some tens of MB up and down
- I'll change logLevel and come back to you asap 
- I can't see any particular warnings under Admin. 

I'm attaching a screenshot of the last 30 days of CPU user time, where you can see the increase after the upgrade.
![Screenshot 2023-09-17 alle 07 52 11](https://github.com/nextcloud/server/assets/5240630/0a08ea36-3b90-4106-ae76-7efb77b2f16d)

**Comment by marcotrevisan** [comment]
By the way the vm has 6 cores available, it's a Proxmox LXC guest, the host is a low comsumption Atom C2758 system so CPU speed is not very high. In a high end processor the "parasite" workload may stay under 100% of a single core, if you're trying to reproduce it locally you may expect a lower workload in the same conditions.

**Comment by marcotrevisan** [comment]
One very nice thing I noted anyway: the web app stays fairly responsive even when the CPU user time is peaking at 98% of 6 cores. 
NC26 and 27 have much improved over their predecessors on the ability to stay responsive at higher load!

**Comment by marcotrevisan** [comment]
@joshtrichards I saw one strange thing but I don't know if it's worthwile or related in this case..: in the Apps administration page, for those which have an upgrade available, when I click on the news tab, the contents are repearted 4 times (i.e. now there's an upgrade available for Talk and I see the changelog repeated 4 times). Can it be related to the apps loading mechanism?

**Comment by marcotrevisan** [comment]
Update: I just verified that my php-8.2 configuration had _opcache.jit_ disabled because of a config file shipped with the newer package overriding my php.ini. 
After reenabling jit the background CPU occupation is still there, but the DBMS is showing more workload. 
The web app is very responsive. I guess -unless you found out something weird in my dumps- this is the normal operation of v27. I'll watch the situation for another day and then I'll close this issue.
Thanks again and sorry for bothering you.

**Comment by marcotrevisan** [comment]
JIT got things get back to normal.

The history graphs are now quite similar to what was usual in the former NC26 and php-fpm8.0 config. Here attached are the last 1-day view and 7-days view of CPU user time. Clearly JIT makes a lot of difference.

![screen1](https://github.com/nextcloud/server/assets/5240630/74eb7c1a-a866-43c1-b811-e8e4a7650ee3)
![screen2](https://github.com/nextcloud/server/assets/5240630/11296ecd-5497-4e6f-a28c-63a26f4f92fe)

Closing this issue. Thanks again @joshtrichards
