### ISSUE TITLE
[Bug]: Documentation contains non-available `OC::$SERVERROOT`

### ISSUE THREAD

**Issue by danielmarschall** [nextcloud/server#40460]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In the documentation https://docs.nextcloud.com/server/latest/admin_manual/apps_management.html at section "apps_path" (and maybe at several other documentation locations?) there is the following code snippet:

```
"apps_paths" => [
    [
            "path"     => OC::$SERVERROOT . "/apps",
            "url"      => "/apps",
            "writable" => false,
    ],
    [
            "path"     => OC::$SERVERROOT . "/apps2",
            "url"      => "/apps2",
            "writable" => true,
    ],
],
```

This does not work, because neither `OC::$SERVERROOT` nor `\OC::$SERVERROOT` can be used in config.php , probably because the auto-loader has not yet found class "OC".

So either the documentation should be fixed, or OC should be made available in config.php (which would be nice, since you don't need to remember canonical path names).

### Steps to reproduce

1. Include code snippet in config/config.php
2.
3.

### Expected behavior

It should work without error

### Installation method

None

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Hi @danielmarschall - Thanks for your report, I can't reproduce this problem. What's the actual error message you're seeing? 

And what version of NC27 specifically are you using?

This config snippet is widely deployed - e.g.

- https://github.com/nextcloud/docker/blob/1ed450b54059ac9eff184c428a823f31435fe582/.config/apps.config.php#L5
- https://github.com/nextcloud/all-in-one/blob/a2c21829893cdcc8c7ef4c3927aaf1a98b697eed/Containers/nextcloud/config/apps.config.php#L5

Nearly all of my instances use it without any problem.

**Comment by danielmarschall** [comment]
Hello @joshtrichards 
Thanks for your fast reply.

The NextCloud version is 27.0.2 .
No apps except the default encryption module are installed.

The exact message is:
`PHP Fatal error:  Uncaught Error: Class "OC" not found in .../config/config.php`

The system, in case it is important:
`Linux 6.1.0-11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux`
`PHP 8.2.7 (cli) (built: Jun  9 2023 19:37:27) (NTS)`
PHP is accessed through php-fcgi

I can't explain that issue, because the class should be there, so I thought the auto-loader might not have been initialized when config.php is accessed?

**Comment by joshtrichards** [comment]
Does `occ config:list system` generate the same error?

**Comment by danielmarschall** [comment]
Hello. I tested it again with nextcloud version 27.1.0. `OC::$SERVERROOT` now works in config/config.php and it is also correctly resolved in `config:list` . Sorry for the disturbance.
