### ISSUE TITLE
[Bug]: The translation not working for some strings in "files_versions" app

### ISSUE THREAD

**Issue by vishnu-n23** [nextcloud/server#40479]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![image](https://github.com/nextcloud/server/assets/141107715/5ad62b04-91db-4054-9b3d-621af5217fef)
translation are not properly implemented for the strings 'Version name', 'Named versions are persisted, and excluded from automatic cleanups when your storage quota is full.'

### Steps to reproduce

1. Change the language(Select a language other than English)
2. Open 'Files' app
3. Open the context menu for any any files, and click details
4. Click the 'Versions' tab (in right sidebar)
5. Open context menu from there and click 'Name this version option'
6. See the untranslated strings in the modal window

### Expected behavior

The translation should work.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment]
Likely also fixed by https://github.com/nextcloud/server/pull/40411

cc @artonge

**Comment by artonge** [comment]
Not fixed, will push a PR
