### ISSUE TITLE
Android browsers: App Mode - Full Screen / No Address Bar

### ISSUE THREAD

**Issue by Huster-at-github** [nextcloud/server#4047]
Firefox and Chrome have the possibility to run web sites in "App Mode".

Example: Chrome with[FM4 Radio Station](http://fm4.orf.at/player/live):
![image](https://cloud.githubusercontent.com/assets/3857906/24318954/657d920e-110f-11e7-8826-d4813932666c.png)

Currently it looks like this in

Firefox:
![image](https://cloud.githubusercontent.com/assets/3857906/24318959/7f97bf16-110f-11e7-8a81-1e17d8a9c50b.png)

Chrome:
![image](https://cloud.githubusercontent.com/assets/3857906/24318962/97db7fea-110f-11e7-871c-ebd870dd224d.png)

**Comment by MorrisJobke** [comment]
@jancborchardt That's what I meant with "the current CSS is awkward", because we don't scroll the whole page but we scroll inside a fixed container, which breaks basically this browser feature 😉

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
I think this is different, because the Radio FM4 page is not scrolled either, right?

@Huster-at-github do you want to contribute a pull request to fix it? :)

**Comment by Espina2** [comment]
Why not just center the container with login, and have background cover for main div?

It should just fine.

**Comment by eppfel** [comment]
No, I think @MorrisJobke is right. Works with fine with scrolling as well. And this is is related to the complete site, not just the login.

@Huster-at-github FM4 😍

**Comment by jancborchardt** [comment]
Well the issue here is that we have a fixed header. Anyone have a good idea around this?

**Comment by jancborchardt** [comment]
There is also this quite nice library for hiding the header – we could hide the Nextcloud header itself with this: http://wicky.nillia.ms/headroom.js/

**Comment by MorrisJobke** [comment]
> Well the issue here is that we have a fixed header. Anyone have a good idea around this?

No. The reason is, that we have 100% height fixed and in there a scroll area (the app-content). 

> There is also this quite nice library for hiding the header – we could hide the Nextcloud header itself with this: http://wicky.nillia.ms/headroom.js/

no way - why add a JS library where we also can cleanup our mess first and then look into further fixes.

**Comment by Espina2** [comment]
> There is also this quite nice library for hiding the header – we could hide the Nextcloud header itself with this: http://wicky.nillia.ms/headroom.js/

BTW, Im using that on the Website.

**Comment by Vetm** [comment]
I think you guys misunterstood @Huster-at-github 's problem. It is not about the url-bar hiding when scrolling down.

On Chrome and Firefox for Android you can add a webpage to the homescreen so it can be launched like an app. There is also a feature where you can hide the url-bar so the webpage actually feels like a native app.

To use this feature you just have to some simple steps as described [here](https://developer.chrome.com/multidevice/android/installtohomescreen).

I'd be happy to fix this issue.

**Comment by jancborchardt** [comment]
@Vetm sorry for the late reply – it would be awesome if you can fix this issue. :) You are very welcome to open a pull request!

**Comment by juliushaertl** [comment]
As a hint for anyone who wants to dig into this starter issue: We already have a manifest.json file. It seems like it is just loaded for logged in users and not on the login page.

**Comment by MorrisJobke** [comment]
Fix is in #9982
