### ISSUE TITLE
[Bug]: Icon for creating new file

### ISSUE THREAD

**Issue by pschopen** [nextcloud/server#40510]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading from 27.0 to 27.1 the icon for creating new files appears as this

![grafik](https://github.com/nextcloud/server/assets/65334274/37940d87-8ae8-4717-a6b9-a22651925e1f)

I think it needs a decision for either having the + or the "new", not both.

### Steps to reproduce

Upgrade to 27.1

### Expected behavior

Having either the + or the "new"

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by JSoko** [comment]
Hello,

I don't think this is a bug...

When there where only a "+" many Guest-Users asked me how to upload

If you only have New, IMHO it's not clear enough...

So I think it's good as it is:
![grafik](https://github.com/nextcloud/server/assets/5583290/b5e51025-70b0-4b37-8eb8-eb7e9b4dfb1a)

Ciao,
Joachim

**Comment by szaimen** [comment]
You need to clear the browser cache

**Comment by pschopen** [comment]
Oh, I see. But still. There seems to be a conflict with onlyoffice. Ones it is installed, it looks like this: 

![grafik](https://github.com/nextcloud/server/assets/65334274/e6f1ffa8-40f6-4303-8e76-6bffdad49b5b)

It's caused by this line in /apps/onlyoffice/templates.css

![grafik](https://github.com/nextcloud/server/assets/65334274/1a59bb9d-d0a6-48f1-9520-8b508bda546e)

After disabling via the inspector...

![grafik](https://github.com/nextcloud/server/assets/65334274/d873b5f1-759e-43fa-a8b7-485665cf1d77)

it looks as intended:

![grafik](https://github.com/nextcloud/server/assets/65334274/1d09e531-3c76-4a39-b78f-2ffb839fe47e)

**Comment by szaimen** [comment]
> It's caused by this line in /apps/onlyoffice/templates.css

then this needs to be reported to the onlyoffice app and fixed there

**Comment by pschopen** [comment]
Also, if doing some coding on that anyways it could also get aligned properly?

![align properly](https://github.com/nextcloud/server/assets/65334274/e2b48d0f-a406-4fab-8710-b1d8fe8dbc2d)

**Comment by pschopen** [comment]
> > It's caused by this line in /apps/onlyoffice/templates.css
> 
> then this needs to be reported to the onlyoffice app and fixed there

Done: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/879

**Comment by pschopen** [comment]
> Also, if doing some coding on that anyways it could also get aligned properly?
> 
> ![align properly](https://user-images.githubusercontent.com/65334274/269237919-4a9a46ea-e18b-4067-8f00-bc0733094314.PNG)

@szaimen Shall I rather create a new issue for this? What do you prefer?
