### ISSUE TITLE
[Bug]: The Longstanding Nightmare of Nextcloud's Update Process

### ISSUE THREAD

**Issue by x011** [nextcloud/server#40518]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The ongoing issues with the update process are both absurd and inexcusable. It's apparent that those responsible for it are utterly unfit for the job. A quick review of the numerous topics concerning Nextcloud server updates provides enough evidence of this chaos. 

A supposedly straightforward update from version 25.0.7 to 25.0.10 on an Ubuntu server results in a bombardment of errors. When the update process fails, it frustratingly hangs at "Update Nextcloud on step X."

Executing the `sudo -u www-data php --define apc.enable_cli=1 /var/www/html/nextcloud/updater/updater.phar` command should be straightforward, but instead, it is plagued with problems:

```
Current version is 25.0.7.

Update to Nextcloud 25.0.10 available. (channel: "stable")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-25.0.10.zip
Open changelog ↗️

Steps that will be executed:
[ ] Check for expected files
[ ] Check for write permissions
[ ] Create backup
[ ] Downloading
[ ] Verify integrity
[ ] Extracting
[ ] Enable maintenance mode
[ ] Replace entry points
[ ] Delete old files
[ ] Move new files in place
[ ] Done

Start update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔️] Check for expected files
[✔️] Check for write permissions
[✔️] Create backup
[✔️] Downloading
[✔️] Verify integrity
[ ] Extracting ...PHP Warning:  require(/var/www/html/nextcloud/updater/../version.php): failed to open stream: No such file or directory in phar:///var/www/html/nextcloud/updater/updater.phar/lib/Updater.php on line 673
PHP Fatal error:  require(): Failed opening required '/var/www/html/nextcloud/updater/../version.php' (include_path='.:/usr/share/php') in phar:///var/www/html/nextcloud/updater/updater.phar/lib/Updater.php on line 673
```
This isn't just an isolated technical hiccup, but a critical error indicating a disastrous lack of competence. 

In no uncertain terms, the team handling this update process needs to be seriously reevaluated. Perhaps they should be replaced by individuals who can competently manage and streamline the process - because as it stands, this is an organizational catastrophe.

---

There appears to be a potential [workaround](https://help.nextcloud.com/t/update-stuck-on-step-6-extracting/106321/2) to this persistent error, although it remains untested. However, when we delve into this, it's quite startling to see the extent of hoops a user is expected to jump through just to update Nextcloud. This workaround isn't simply a convenient detour – it's a complex, multi-step hurdle that users are being forced to navigate. Such a process should surely be more streamlined, with less burden on the user. This situation highlights the need for an urgent review of the update process within Nextcloud.

### Steps to reproduce

1. sudo -u www-data php --define apc.enable_cli=1 /var/www/html/nextcloud/updater/updater.phar

### Expected behavior

Update nextcloud from version 25.0.7 to 25.0.10

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

25

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 7.4

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Could not open input file: occ
```

### List of activated Apps

```shell
Could not open input file: occ
```

### Nextcloud Signing status

```shell
Update in process.
```

**Comment by joshtrichards** [comment]
I'm fairly certain this is not a common issue, but I understand your frustration. I've only seen a couple documented reports of this (like nextcloud/updater#323 which, not incidentally, documents a similar workaround).

Can you confirm you're running Nextcloud from a subdirectory (it appears you are)? 

Both reports so far have that in common.

Are there any symbolic links involved anywhere along the filesystem path or parent to `/var/www/nextcloud`?

Is your `datadirectory` also located underneath your install directory or is it elsewhere?

Can you provide your `updater.log`?

Anything else unusual about you environment or filesystem that you can think of?

The greatest challenge is reproducing this matter. If it *were* more common it would be easier to fix. :-)

**Comment by n0valis** [comment]
I am just coming from Owncloud where the update process was a nightmare as well. In many cases at least, except you were a nerd who could do it all manually and are prepared to do everything from scratch. But I thought, well give NC a try.

So now I came accross this message now: Nextcloud 27.1.0 is available. 
on my fresh Nextcloud 27 installation (on a Raspi, installed the latest release coupleof days ago, downloaded from webpage).
And it worked fine so far....
So I checked the Updater function (available via Settings, there is a button 'open updater')
What happens is: 
from https://myip:8088/index.php/settings/admin/overview# it opens https://myip:8088/updater
and the result is:
Not Found
The requested URL was not found on this server.
Checked /var/www/nextcloud
there is no such directory 'updater'
hmmm
This is ridiculous isn't it?

**Comment by joshtrichards** [comment]
Hi @n0valis - That sounds more like a config or install method matter, but can't be sure without more details. What install method, specifically, did you use? 

Some NC install methods and community packages (like the community Docker and Snap) don't use the NC web updater and have disabled it by removing it (I don't recall how `nextcloud-pi` handles it offhand).

This is also a different situation than the specific one mentioned in this report. If you think it's a bug it'll be easiest for all involved to move it to it's own issue so that the necessary information can be gathered specific to it. 

But, certainly, if you think you're seeing a bug that is update related please report it.

**Comment by x011** [comment]
[joshtrichards](https://github.com/joshtrichards): A straightforward Google search uncovers a vast number of posts over the years concerning [Nextcloud update error](https://www.google.com/search?q=Nextcloud+update+error). 
For at least five years, I've been using NC and every time I need to update the server, I encounter the same issues: there are errors and I end up resorting to hacks and so on, just to make it function. I don't have any custom setup, my NC server operates on Ubuntu 20.04.

In my situation, I resolved the issue using the following method:

> The `version.php` in nextcloud folder is missing
> Download the package from the nextcloud website and copy “`version.php`” on your instance. Edit the version to match with what you have. (Don’t forget to set the rights to the file)

**Comment by joshtrichards** [comment]
@x011:

> For at least five years, I've been using NC and every time I need to update the server, I encounter the same issues: there are errors and I end up resorting to hacks and so on, just to make it function. I don't have any custom setup, my NC server operates on Ubuntu 20.04.

Every installation is somewhat custom. Data directories, underlying filesystem types, partitioning schemes, active PHP modules, etc. And that is just to name a few examples. Also, since it appears you did a manual installation so there are even more variables.

[...]
> Most importantly, why does this update keep failing? There is an critical issue with the update code's functioning that necessitates immediate rectification.

You ignored nearly every question in my follow-up to your bug report so I have no idea. As a result, I cannot help you.

P.S. In your original report I noticed you stated this for the requested information fields:

> Could not open input file: occ

There are multiple variations of the command suggested in the form like this:

```
sudo -u www-data php occ config:list system
php occ config:list system
./occ config:list system
```
You may want to try a different variation and also a `cd /var/www/html/nextcloud` before trying them. Good luck!

**Comment by x011** [comment]
OCC is non-existent on my system, hence I can't possibly provide any output from it. This is yet another problem. As stated in my previous post, I've already found the solution, yet another workaround. My questions were purely rhetorical, but thanks anyway for attempting to assist.

**Comment by joshtrichards** [comment]
> OCC is non-existent on my system

Then your installation is broken.

**Comment by joshtrichards** [comment]
@n0valis 

> And I'll probably find the files somewhere. Just funny that they are not in the realease here
https://github.com/nextcloud/server

The updater app isn't part of `server`. If the `updater` is missing from your environment there is a reason. If/when you feel like digging into your situation further I encourage you to start by doing so over at the [Nextcloud Help Forum](https://help.nextcloud.com) or the community support channel for whatever underlying installation method you used.
