### ISSUE TITLE
[Bug]: f2v - 3dot menu does not work on newly created folder 

### ISSUE THREAD

**Issue by max-nextcloud** [nextcloud/server#40514]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After creating a new folder and changing the title the three dot menu does not work anymore.

It does work after a page reload and also worked when there already was a file name "New Folder" so it became "New Folder (1)".

### Steps to reproduce

1. Run latest master branch
2. Login (I used the admin user)
3. Click plus button and create a folder
4. Rename the new folder
5. Try to open the three dot menu.

### Expected behavior

Three dot menu should open

### Installation method

Other Community project

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

There are no errors in the browser console.

**Comment by szaimen** [comment]
Just tested on c.nc.c and seems to work
