### ISSUE TITLE
Stop Nagging Popup "Nextcloud x.y.z is available. Get more information on how to update."

### ISSUE THREAD

**Issue by n0valis** [nextcloud/server#40529]
I have disabled "inform members of the following groups of avail. updates' in admin settings. It is empty.
I get this message for every page I load, for every click I do within the NC webapp.
Please give us a relief for this. 
Or am I missing something, how to disable this messages?
Thank you.

**Comment by solracsf** [comment]
In my case i've simply disabled the "Update notification" app.
If you don't want to be notified (well, leaving it empty is what it means) than it's the way to go.

**Comment by n0valis** [comment]
> In my case i've simply disabled the "Update notification" app. 
Thank you. Didn't see that one. An App. Ok then. For me this seems a bit like an overkill. A toggle in the Settings would have done it imho. Anyway...

>If you don't want to be notified (well, leaving it empty is what it means) than it's the way to go.
It didn't work. Still got the popup.

**Comment by joshtrichards** [comment]
If you don't list any groups, it defaults to the "admin" group. 

https://github.com/nextcloud/server/blob/b11ca34bbd0c2d5fdbb6b68b3e1bf93dad02f588/apps/updatenotification/lib/Settings/Admin.php#L97

There is also a config parameter in the documentation to disable outright:

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#updatechecker

Another option would be not to use an admin account for day to day use.
