### ISSUE TITLE
Change default activity settings for new users

### ISSUE THREAD

**Issue by cal940** [nextcloud/server#4052]
I reinstalled my nextcloud application (11.0.2) completely and now all my users get an email notification, then I share a file with them (I don't want that for new users). Is it possible to change the default settings for new users. 

In my previous nextcloud application (9.0.52) there was an app (Activity defaults) for that.

**Comment by nickvergessen** [comment]
The app should still work.

**Comment by cal940** [comment]
But I don't find it in the appstore. This app was „experimental“.

**Comment by cal940** [comment]
I just transfered the app files to the new app folder and got the following message.
![img_0082](https://cloud.githubusercontent.com/assets/23076743/24325895/12f0b7e8-11a3-11e7-889a-3ea964cd1194.PNG)

**Comment by nickvergessen** [comment]
Let's discuss this in https://github.com/nextcloud/activity/issues/131
