### ISSUE TITLE
[Bug]: NC 27.1.0 (Hub 6) : The internal link of a folder generated (retrieved) by the smart picker is incorrect

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/server#40549]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Tested with NC 27.1.0 (may occur in previous major versions).
When you use the smart picker and that you select the "Files" features, you can select a file (no problem for that, it just works), or a folder (which is relevant because internal links also exist for folders).
When a folder is chosen, you get a wrong URL.
E.g., you get something like "https://mydomain.fr/f/%7BfileId%7D" instead of "https://mydomain.fr/f/512"
![2023-09-21_11-16](https://github.com/nextcloud/server/assets/33763786/d7ed6bb6-039f-4e6b-a63b-9b0b69d829ff)

### Steps to reproduce

1. Go in a md file (Nextcloud Text) or a Nextcloud Office (Collabora Online) file 
2. Open the Smart Picker and select "Files"
3. Select a folder and see that the link isn't good (compare it with the internal URL that you can get manually in Nextcloud Files). You will also notice that the preview card (below the link) indicates that de folder can't be found.

### Expected behavior

2 possibilities : 

- Fix the bug because IMO, it's important to allow users to target folders as they already can do it with files (because internal links exist for both files and folders). Also, as you can see, the modal title is : 

![Capture d’écran du 2023-09-21 11-27-16](https://github.com/nextcloud/server/assets/33763786/b305c4e6-1cf1-4d7a-bdda-64e0025123e7)

- Remove the possibility to validate folder selection (just like in previous Nextcloud version ; e.g. 26.0.x, 27.0.2 ...), but I really think its would (and was) not relevant.

### Installation method

None

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "mydomain.fr"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "27.1.0.7",
    "updatechecker": true,
    "overwrite.cli.url": "https:\/\/mydomain.fr",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "default_language": "fr",
    "default_locale": "fr_FR",
    "knowledgebaseenabled": false,
    "default_phone_region": "ISO3166-2",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "activity_use_cached_mountpoints": true,
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "updater.release.channel": "stable",
    "app_install_overwrite": [
        "occweb",
        "files_readmemd",
        "impersonate",
        "apporder",
        "quickaccesssorting",
        "workspace",
        "jitsi",
        "holiday_calendars"
    ],
    "mail_smtpsecure": "ssl"
}
```

### List of activated Apps

```shell
Enabled:
 - activity: 2.19.0
 - announcementcenter: 6.6.2
 - bruteforcesettings: 2.7.0
 - calendar: 4.5.0
 - circles: 27.0.1
 - cloud_federation_api: 1.10.0
 - comments: 1.17.0
 - contacts: 5.4.1
 - contactsinteraction: 1.8.0
 - dashboard: 7.7.0
 - dav: 1.27.0
 - deck: 1.11.0
 - external: 5.2.1
 - federatedfilesharing: 1.17.0
 - files: 1.22.0
 - files_lock: 27.0.1
 - files_pdfviewer: 2.8.0
 - files_readmemd: 2.0.0
 - files_reminders: 1.0.0
 - files_rightclick: 1.6.0
 - files_sharing: 1.19.0
 - files_trashbin: 1.17.0
 - files_versions: 1.20.0
 - firstrunwizard: 2.16.0
 - flow_notifications: 1.7.0
 - groupfolders: 15.3.0
 - guests: 2.5.0
 - holiday_calendars: 0.3.0
 - impersonate: 1.14.0
 - integration_deepl: 1.1.0
 - integration_openstreetmap: 1.0.6
 - integration_replicate: 1.0.7
 - jitsi: 0.18.0
 - logreader: 2.12.0
 - lookup_server_connector: 1.15.0
 - metadata: 0.19.0
 - nextcloud_announcements: 1.16.0
 - notes: 4.8.1
 - notifications: 2.15.0
 - oauth2: 1.15.1
 - password_policy: 1.17.0
 - passwords: 2023.9.30
 - phonetrack: 0.7.6
 - privacy: 1.11.0
 - provisioning_api: 1.17.0
 - quota_warning: 1.17.0
 - recommendations: 1.6.0
 - richdocuments: 8.2.0
 - richdocumentscode: 23.5.301
 - serverinfo: 1.17.0
 - settings: 1.9.0
 - sharebymail: 1.17.0
 - spreed: 17.1.0
 - stt_whisper: 1.0.6
 - support: 1.10.0
 - survey_client: 1.15.0
 - systemtags: 1.17.0
 - text: 3.8.0
 - theming: 2.2.0
 - theming_customcss: 1.14.0
 - translate: 1.1.6
 - twofactor_backupcodes: 1.16.0
 - twofactor_email: 2.7.3
 - twofactor_nextcloud_notification: 3.7.0
 - twofactor_totp: 9.0.0
 - updatenotification: 1.17.0
 - user_status: 1.7.0
 - viewer: 2.1.0
 - weather_status: 1.7.0
 - welcome: 1.0.10
 - workflowengine: 2.9.0
Disabled:
 - admin_audit
 - encryption
 - federation: 1.16.0
 - files_external: 1.18.0
 - photos: 2.3.0
 - related_resources: 1.1.0
 - suspicious_login
 - user_ldap
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Can be provided if necessary
```

### Additional info

Can be provided if necessary

**Comment by logianer** [comment]
Also experiencing this after updating from 27.0.2. Hope someone knows how to fix this.

**Comment by bentuna** [comment]
The issue occurs still in Nextcloud version 27.1.5 here and also in Nextcloud Talk.

**Comment by xbluemonkx** [comment]
is there a local setting that can be done to fix this? I can barely imagine that this central feature was unfixed for three months if every NC instance would be facing it.

**Comment by Jerome-Herbinet** [comment]
The ability to target a folder has probably been removed. The described problem no longer exists, although other bugs are now appearing (not all have been taken into account in the UX; I'll re-open other issues later).
