### ISSUE TITLE
[Bug]: UI glitch in file comments

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/server#40553]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The comments on a file in the files app is visually broken. See screenshot.

### Steps to reproduce

1. Go to the files app
2. open the comments of a file

### Expected behavior

No glitch and text overflowing other texts

### Installation method

None

### Nextcloud Server version

25

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Tested on the conference instance of NC 2023.

![image](https://github.com/nextcloud/server/assets/8202922/ddcc8ebd-a4c9-424c-9d92-21c7c9be2865)

**Comment by XueSheng-GIT** [comment]
Still an issue in NC 27.1.1

**Comment by ShGKme** [comment]
Duplication of https://github.com/nextcloud/server/issues/37087
