### ISSUE TITLE
[Bug]: Unclear text in file sharing dialog

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/server#40554]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The file sharing dialog for sharing a single file is a bit misleading. It claims to allow "uploading and editing". Uploading (for a single file) does not make much sense, though.

### Steps to reproduce

1. Go to the files app
2. Share a single file as a link

### Expected behavior

It should for regular files just be called "edit" or similar.

### Installation method

None

### Nextcloud Server version

25

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

This was seen on the current conf instance 2023 as well as the main instance cloud.nextcloud.com.

![image](https://github.com/nextcloud/server/assets/8202922/bae7ff31-974f-4b63-bdc0-1c9fa2a6a82a)
"Hochladen und Bearbeiten erlauben" is equivalent to "Allow upload and sharing".

**Comment by joshtrichards** [comment]
Looks fixed / no longer applicable. Don't hesitate to nudge me back though if I'm misunderstood. :-)
