### ISSUE TITLE
Show status instead of email in contacts/people menu

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#40559]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

## Is your feature request related to a problem? Please describe.

As a Nextcloud user I want to see what other people are doing. If I click the *people menu* (formerly known as *contacts menu*) in the top right I see the first x contacts sorted by their name. For each contact I see the email address.

## Describe the solution you'd like

Remove the email address subline and show the user status instead. Sort the contacts by their last status update.

- [x] Blocked by https://github.com/nextcloud/server/issues/40558

## Additional context

N/a

**Comment by ChristophWurst** [comment]
@jancborchardt @marcoambrosini @nimishavijay could you create a mockup for this? Should the menu also show the user online status (green dot etc)?

**Comment by jancborchardt** [comment]
- We can pretty much have it look the same as the "Participants" tab in Talk, except with the "(moderator)" indicator removed. That is also very similar to the "Recent statuses" dashboard widget (which should ideally also be adjusted to include the online status).
- Click events and menu items would still stay the same for now, this step is only about the subline, online status indicator and sorting.
- Currently the list is very short at 4 entries (and also not clear one can scroll). We can make it larger to 6½ entries so that there are more entries and the half cut off entry suggests scrollability more.
![image](https://github.com/nextcloud/server/assets/925062/4aa0238e-a6fb-4268-9e10-6b5023b1d500)

**Comment by ChristophWurst** [comment]
Medium-size technical barrier for this feature: https://github.com/nextcloud/server/blob/master/core/src/views/ContactsMenu.vue smells like a Vue components but the internals are still jquery and backbone https://github.com/nextcloud/server/blob/5ddffcb7b41326b5d3d2528e2a0e9cb6f8f8d76a/core/src/views/ContactsMenu.vue#L57-L59. 

To not increase technical debt further I should probably rewrite the menu in Vue first.

**Comment by ChristophWurst** [comment]
This will revert the changes of https://github.com/nextcloud/server/pull/28822. cc @kesselb

**Comment by ChristophWurst** [comment]
> Currently the list is very short at 4 entries (and also not clear one can scroll). We can make it larger to 6½ entries so that there are more entries and the half cut off entry suggests scrollability more.

@jancborchardt I have looked into this problem already with my work on https://github.com/nextcloud/server/pull/40749. Unfortunately the height of the contact entries is not static. E.g. some entries have an email address, others have none. We'll have to see how that changes when we show the status. In the future we also want to show the *latest message* so there is another optional element :/

**Comment by ChristophWurst** [comment]
Alright, I'll add a minimum height.

**Comment by ChristophWurst** [comment]
Just dumping my thoughts here.

Adding status to contacts menu entries is doable with a small backwards-compatible API change. What's tricky is the change of sorting. Right now we read contacts from the contacts manager, which searches on the DB and knows a way to limit the number of results. We can't take that data, enhance it with status messages and sort again. We have to factor in status update time in the initial search. But that is not easy because of the identification mismatch between contacts (based on UUIDs, UID *may* be in the serialized vcf data) and statuses (based on Nextcloud user IDs). The two sources can't be joined on a database level.

Maybe we can first ask user status to give us the x latest user ids. Then we use this UID array to make a contacts search on UID (`\OCP\IAddressBook::search` supports it down to oc_cards_properties having UID indices). This should work, albeit with poor performance because it has the n+1 problem and requires 21 database queries to get 20 contacts.

**Comment by ChristophWurst** [comment]
@jancborchardt do you have any requirements for the handling of contacts with statuses (aka system contacts) and other contacts? say on a small instance there are only three other family members and users. Should the contacts menu only show these three or should the rest of the contacts menu be filled with people from your personal address book?

**Comment by ChristophWurst** [comment]
@jancborchardt would you say that emails should always be hidden or only if the contact is a user (system contact) and has a status?

**Comment by jancborchardt** [comment]
@ChristophWurst it would be nice if there is always a relevant subline, also to distinguish possible different people with the same name. And yes the email seems good for that for people from Contacts. :)

**Comment by jancborchardt** [comment]
> Should the contacts menu only show these three or should the rest of the contacts menu be filled with people from your personal address book?

Not sure if this is resolved already but we talked about this when we defined it, no? The contacts menu should show both, but prioritize system accounts.
