### ISSUE TITLE
Strange behavior when 'appstoreenabled' => false

### ISSUE THREAD

**Issue by jernst** [nextcloud/server#4056]
Attempting to turn off the app store. So I execute:
```
occ config:system:set appstoreenabled --type boolean --value false
```
and indeed,
```
'appstoreenabled' => false,
```
shows up in `config.php`.

However, the only change in behavior is that when I attempt to install an app, I get the error

```
App "" cannot be installed because appinfo file cannot be read.
```

When this value is true, I get no error.

What is the correct way to turn off the app store, and how should it look like when it is indeed off? I was expecting something like the app listing disappearning.

This is NextCloud 11.0.2. on [UBOS](http://ubos.net/) (like Arch). Cross-posted here per request [there](https://help.nextcloud.com/t/appstoreenabled-false/10643).

**Comment by MorrisJobke** [comment]
Fix for this went into the upcoming 11.0.3 (scheduled for April 10th): #3767
