### ISSUE TITLE
Documentation of "NC_" Environment Variables 

### ISSUE THREAD

**Issue by raphaelhilg** [nextcloud/server#40579]
There are some **"NC_"** environmental variables you can use instead of the "config.php" file.
Those are especially useful for docker deployments as those variables do not require manually editing of config files.

However there does not seem to be any documentation around which variables you can use and which not.
The existence of these variables is not mentioned in the official documentation.

The only mention of those that I could find from official Nextcloud sources is right in the 
[source code](https://github.com/nextcloud/server/blob/master/lib/private/Config.php) (line 86 and following) and in the [pull request ](https://github.com/nextcloud/server/pull/3966)

It would be great to have clear documentation that those variables exist, which variables you can use and if there are any drawbacks when using those.

Tested variables in a docker compose deployment:

```
      NC_default_language: de
      NC_default_locale: de_DE
      NC_default_phone_region: DE
      NC_loglevel: 2
```

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kesselb** [comment]
Thanks for your report :+1: 

I'm closing your report in favor of https://github.com/nextcloud/documentation/issues/426. 

In addition, please take note of https://github.com/nextcloud/documentation/pull/9143#issuecomment-1238598774
