### ISSUE TITLE
[Bug]: "App name" InputField on Personal Settings > Security is broken

### ISSUE THREAD

**Issue by Antreesy** [nextcloud/server#40573]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Input event is not set up correctly (probably, whole event ot other object is passed):

![image](https://github.com/nextcloud/server/assets/93392545/30339999-f94e-44cc-9494-b0621f767ddd)

### Steps to reproduce

1. Open `settings/user/security`
2. Try to input something in "App name"
3. See result

### Expected behavior

Only input value from event should be handled

### Installation method

None

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Can't reproduce this today. Seems fixed.
