### ISSUE TITLE
Put link to security-scan on admin page

### ISSUE THREAD

**Issue by tflidd** [nextcloud/server#4057]
If you know you can scan your own instance in terms of security at scan.nextcloud.com

I propose to put a link to scan your instance on your admin page (next to the version number or next to the security & setup warnings). When you setup your server, you check your system. As it is the current version there won't be many errors but you notice this function and will use it later again.

**Comment by Hunter-Github** [comment]
Better still, refrain from scanning people's servers and violating local laws and ethics of pentesting. https://www.reddit.com/r/selfhosted/comments/5ybmf1/nextcloud_scanning_peoples_owncloud_and_nextcloud/

**Comment by tflidd** [comment]
I see no problem when you ask to scan/test your own setup. They check only the version number, so they don't stress the infrastructure.

**Comment by MariusBluem** [comment]
Have a look over here: https://github.com/nextcloud/server/pull/3755

**Comment by tflidd** [comment]
> Have a look over here: #3755

Ok, so we can close this.
