### ISSUE TITLE
[BITV] Replace all places with old NcMultiselect components with NcSelect components

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#40588]
There are still several places in our views where NcMultiselect components are used. Due to several reasons (inclusive contrast issues) we have to switch completely to NcSelect components.

Examples:

index.php/settings/admin/sharing
![Screenshot from 2023-09-22 14-50-22](https://github.com/nextcloud/server/assets/6078378/30b73378-439d-4703-a218-c0414b4330fd)

index.php/settings/admin
![Screenshot from 2023-09-22 15-05-16](https://github.com/nextcloud/server/assets/6078378/92c27841-036f-407f-8560-6754bffcc3a3)

**Comment by susnux** [comment]
@JuliaKirschenheuter there are no `NcMultiselect` components anymore in the server.
The tags selector of the second screeshot is already a NcSelect (`NcSelectTags`).
