### ISSUE TITLE
[Bug]: php-opencloud bug corrupts large file with Swift storage, patch recommended

### ISSUE THREAD

**Issue by vpecinka** [nextcloud/server#40582]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I have reported this bug in `php-opencloud`

https://github.com/php-opencloud/openstack/issues/365

As there can be significant delay until it gets to mainstream, I suggest to provide local patch in nextcloud code base to resolve this issue. 

### Steps to reproduce

Upload any large object to the storage (the default SEGMENT SIZE is 1 GB, so the file has to be more than 10 GB). 

### Expected behavior

segments should have name 00001, 00002, 00003 and so on to be correctly reconstructed.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment]
Good finding, sounds reasonable :+1: 

Would you mind submitting a pull request to the upstream project?

**Comment by vpecinka** [comment]
no problem, https://github.com/php-opencloud/openstack/pull/366

**Comment by vpecinka** [comment]
Upstream PR merged

**Comment by joshtrichards** [comment]
Released in php-opencloud v3.3.0:

https://github.com/php-opencloud/openstack/releases/tag/v3.3.0
