### ISSUE TITLE
Prepare for PHP 8.0 end of life

### ISSUE THREAD

**Issue by come-nc** [nextcloud/server#40636]
PHP version 8.0 official security support will end on November 26: https://www.php.net/supported-versions.php

Also, we may not easily keep supporting it as our dependencies might drop 8.0 as well when adding support for 8.3. (I think this is not currently the case, if you have information please comment)

Preparing for this drop, we need to first update the following CI:

- [x] github:
  - sftp.yml
  - static-code-analysis.yml
  - phpunit-32bits.yml
  - update-psalm-baseline.yml
  - s3-primary-integration.yml
  - s3-primary.yml
  - ftp.yml
  - performance.yml
  - [x] vendor-bin/psalm
  - [x] vendor-bin/cs-fixer https://github.com/nextcloud/server/pull/39271
- [x] drone:
  - [x] ghcr.io/nextcloud/continuous-integration-php8.0:latest
  - [x] ghcr.io/nextcloud/continuous-integration-litmus-php8.0:latest
  - [x] ghcr.io/nextcloud/continuous-integration-samba-native-php8.0:latest
  - [x] ghcr.io/nextcloud/continuous-integration-samba-non-native-php8.0:latest ?
  - [x] ghcr.io/nextcloud/continuous-integration-acceptance-php8.0:latest
  - [x] ghcr.io/nextcloud/continuous-integration-integration-php8.0:latest
  - [x] ghcr.io/nextcloud/continuous-integration-mysql-8.0:mysql-8.0
  - [x] ghcr.io/nextcloud/continuous-integration-php8.0-memcached:latest
  - [x] ghcr.io/nextcloud/continuous-integration-webdav-apache-php8.0:latest

**Comment by isdnfan** [comment]
hi team another heads up - for some reason NC30 still supports PHP 8.0 which is EOL since 26.11.**2023**!! 
please keep in mind PHP 8.1 "*Active support*" ends in less than 2 months on on 1 Jan 2025

**Comment by come-nc** [comment]
> hi team another heads up - for some reason NC30 still supports PHP 8.0 which is EOL since 26.11.**2023**!! please keep in mind PHP 8.1 "_Active support_" ends in less than 2 months on on 1 Jan 2025

No, Nextcloud 30 dropped support for PHP 8.0, as you can see in both the documentation: https://docs.nextcloud.com/server/stable/admin_manual/installation/system_requirements.html#server and source code: https://github.com/nextcloud/server/blob/v30.0.0/lib/versioncheck.php

Where did you get your information?
