### ISSUE TITLE
[Bug]: in the personal settings "X" is still called twitter

### ISSUE THREAD

**Issue by breitsi** [nextcloud/server#40648]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

in the personal settings "X" is still called twitter. It's just a matter of naming

### Steps to reproduce

1. go to settings => personal info

### Expected behavior

Twitter is now called X

### Installation method

Official All-in-One appliance

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by blizzz** [comment]
? The display server?

**Comment by breitsi** [comment]
[image: image.png]

**Comment by breitsi** [comment]
Frontend. Log in to your nextcloud and go to your profile. You can save your “Twitter” account there

**Comment by thrila** [comment]
can i work on this??

**Comment by blizzz** [comment]
> can i work on this??

definitely!

**Comment by anandpotukuchi** [comment]
Any progress @thrila ?You havent made a PR?










/

**Comment by thrila** [comment]
My apologies

**Comment by thrila** [comment]
I already corrected the issue but I haven't pushed yet by 2:00 am WAT I should have made a pr

**Comment by ezhil56x** [comment]
@szaimen  I think changing it to `X (Formerly Twitter)` or `X (Twitter)` would be better visually

**Comment by thrila** [comment]
Well I will not be able to work on it anytime soon so I believe it should be given to another person

**Comment by AndyScherzinger** [comment]
Resolved via https://github.com/nextcloud/server/pull/41385
