### ISSUE TITLE
Out-of-office: Expose data via OCP/OCS APIs

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#40650]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

## Is your feature request related to a problem? Please describe.

Users can enter OOO info via https://github.com/nextcloud/server/issues/40616. Apps want access to this data and react when a users goes to or returns from OOO.

## Describe the solution you'd like

Add an OCP API that exposes the OOO information. Add events for the start and end of OOO.

## Describe alternatives you've considered

N/a

## Additional context

N/a

**Comment by ChristophWurst** [comment]
## Brainstorming the requirements

### Mail
* Get called when the OOO starts -> OCP event
* Get called when the OOO ends -> OCP event
* Get OOO message of a user -> OCP API or OCS endpoint

### Talk
* Get OOO message of a user -> OCP API or OCS endpoint

**Comment by nickvergessen** [comment]
For Talk an OCS endpoint would be preferred. This way also mobile clients can show the information.

If the user status is uniquely identifyable (hardcoded message_id like the in_call), we can use that as an indicator to see if we should contact the OOO endpoint to load more info. The user status is returned on the conversation list, but I guess we wouldn't want to load even more data for all users every 30 seconds.
