### ISSUE TITLE
[Bug]: NC27: While on Trash, Home icon doesn't redirect to home

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#40669]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Home icon on breadcrumb doesn't redirect to Home, it refreshes the Trash.
Also, Home icon is not the same than on Files and not well aligned...

### Steps to reproduce

1. Go to Trash
2. Clic on Home

![image](https://github.com/nextcloud/server/assets/12234510/1ab2f952-51bc-4f1b-9483-95ebaf04337c)

### Expected behavior

Redirect to Home/Files

### Nextcloud Server version

27.1.1

**Comment by JonasMayerDev** [comment]
I think this is intended behavior. The Trash Bin is an independent tab, and the Home button just redirects to the root of this tab, which is needed if you have deleted folders... 
I agree that the alignment is off and different from the Files tab.
