### ISSUE TITLE
[BITV] Bug: background color of active item on a left sidebar won't work after opening file details

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#40663]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Navigate thorough left sidebar and see that colors are broken.

### Steps to reproduce

1. Open files
2. Navigate through left sidebar
3. Open details of random file
4. See that background color on left sidebar is broken

![Peek 2023-09-27 16-28](https://github.com/nextcloud/server/assets/6078378/570f5ce2-fe33-4ded-b134-1e4dec44af0a)

### Expected behavior

Colors are not broken

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by JuliaKirschenheuter** [comment]
@ShGKme @skjnldsv please have a look 🙏

**Comment by skjnldsv** [comment]
Seems like this was fixed in https://github.com/nextcloud-libraries/nextcloud-vue/pull/4155
Another app must create the conflicting css rule because this is [not scoped](https://github.com/nextcloud/nextcloud-vue/blob/5a5f2b24a1cc4e103024f7c8ce684d119b978477/src/components/NcAppNavigationItem/NcAppNavigationItem.vue#L757) :shrug:

**Comment by skjnldsv** [comment]
yep, disabling groupfolders works. 
They should update their components dependency
