### ISSUE TITLE
jQuery.globalEval()={} - Problem with password strength and files_markdown

### ISSUE THREAD

**Issue by michaelletzgus** [nextcloud/server#4067]
Current master, personal settings, type a password into the "new password field"

Expected: Show password strength

Actual: 
`ReferenceError: zxcvbn is not defined` in jquery.strengthify.js

Reason:
The script loading and executing of [/core/vendor/zxcvbn/dist/zxcvbn.js](https://github.com/nextcloud/server/blob/master/core/vendor/zxcvbn/dist/zxcvbn.js) at the bottom of [/core/vendor/strengthify/jquery.strengthify.js](https://github.com/nextcloud/server/blob/master/core/vendor/strengthify/jquery.strengthify.js#L199) is rendered dysfunctional by https://github.com/nextcloud/server/commit/148e7abb5143a4003d01989c89424900d94e65aa due to
```
$.ajaxSetup({
		contents: {
			script: false
		}
	});
jQuery.globalEval = function(){};
```
in [core/js/js.js](https://github.com/nextcloud/server/blob/148e7abb5143a4003d01989c89424900d94e65aa/core/js/js.js#L1274) which is needed by jQuery ajax()/getScript() to execute loaded script.

https://github.com/nextcloud/server/commit/148e7abb5143a4003d01989c89424900d94e65aa also brakes files_markdown (see https://github.com/nextcloud/server/pull/3696#issuecomment-287875965)

**Comment by LukasReschke** [comment]
Patch for jquery.strengthify.js: https://github.com/MorrisJobke/strengthify/pull/14

**Comment by LukasReschke** [comment]
cc @MorrisJobke

**Comment by LukasReschke** [comment]
And for the files_markdown app: https://github.com/nextcloud/server/pull/4068
