### ISSUE TITLE
Add a profile photo

### ISSUE THREAD

**Issue by sidreshot** [nextcloud/server#40673]
It is a pity that there is no way to add a profile photo when integrating LDAP. This is a very important function.
![image](https://github.com/nextcloud/server/assets/10060394/bb182fdd-0de7-4f15-abd7-1e7222d4c7d6)

**Comment by kesselb** [comment]
https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_auth_ldap.html#nextcloud-avatar-integration

If your ldap directory does not provide the avatar then turn the integration off and you are able to upload it manually.

**Comment by kesselb** [comment]
Please raise your next question at https://help.nextcloud.com
