### ISSUE TITLE
[BITV]: Replace `aria-label`'s of background buttons with another name

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#40689]
This is accessibility issue.

For now background buttons have `aria-label`'s which are not really understandable, like "Soft floral (Hannah MacLean, CC0)". The `aria-label` have to be like "Background with abstract ..."

Each name have to unique.

![Screenshot from 2023-09-28 18-51-42](https://github.com/nextcloud/server/assets/6078378/222296f6-f1a7-4c17-8410-4e20536cc509)

**Comment by szaimen** [comment]
So we need to add descriptinos for each picture and adjust the aria-label to show these. Also currently title as well as aria-label are not translated which needs to be adjusted.
