### ISSUE TITLE
[BITV]: NcSelect improvements

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#40697]
This is accessibility issue.

There are several point to improve:

1. Preselected time zone (Europe - Amsterdam) have not enough contrast and seems like 
![Screenshot from 2023-09-29 09-22-10](https://github.com/nextcloud/server/assets/6078378/97d9e979-e67b-42c6-9973-ffbbbb2d2512)

2. Group item like "Africa" have not enough contrast and is not recognizable even if it is disabled item.
![Screenshot from 2023-09-29 09-27-47](https://github.com/nextcloud/server/assets/6078378/6ffcc2b2-af26-450e-809d-d6d8b3fb50e8)

3. Aria-label of combobox is "search for option" and have to be instead "Search for time zone"
![Screenshot from 2023-09-29 09-46-30](https://github.com/nextcloud/server/assets/6078378/dddca3e2-883c-4690-af14-5c83ecfaad3e)

4. `strong` timezone have to be a label for Select
![Screenshot from 2023-09-29 09-48-36](https://github.com/nextcloud/server/assets/6078378/6293f1d7-d737-4be4-b70c-33943a3a9e68)

**Comment by susnux** [comment]
>     1. Preselected time zone (Europe - Amsterdam) have not enough contrast and seems like

- [ ] TBD

>     2. Group item like "Africa" have not enough contrast and is not recognizable even if it is disabled item.

- [x] done with #40773 

>     3. Aria-label of combobox is "search for option" and have to be instead "Search for time zone"

- [ ] TBD

>     4. `strong` timezone have to be a label for Select

- [ ] TBD
