### ISSUE TITLE
Exception: previewgenerator can't be disabled.

### ISSUE THREAD

**Issue by luther1984** [nextcloud/server#40691]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi guys, I tried to update Nextcloud via Edge, Chrome, Opera and Firefox. I always get the same error: Exception: previewgenerator can't be disabled. 
I installed the system on Windows and unfortunately I can't find a way to work around the problem here. 
I have installed Linux or Ubuntu in the meantime. But it is now 10 years ago that I have dealt with it. I have tried to update nextcloud via Linux but it does not work. 

I would be very grateful if someone had a solution to the problem. Without the cloud I'm lost for a week. 

If you have a solution via input in the terminal or other more complex ideas then keep in mind that I am currently a linux greenhorn.

Thanks guys

![nxtcloud 1](https://github.com/nextcloud/server/assets/144477793/a51dea72-43d3-47b8-a0a8-6cc4cc6a810f)

### Steps to reproduce

1.try to access the cloud via browser
2.Update request
3.Update starts and breaks with the error: Exception: previewgenerator can't be disabled

### Expected behavior

Smooth update

### Installation method

None

### Nextcloud Server version

25

### Operating system

Other

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Your Nextcloud instance looks like it's *Managed* by IONOS based on your screenshot. Have you tried contacting them? They may not allow you to update/upgrade yourself (common), but handle that for you.

Either way, this channel is only for bug reports and is not a help forum. If you're managed hosting provider can't help you or you require general troubleshooting assistance, please try the [Nextcloud Help Forum](https://help.nextcloud.com) to try to get some help from the community. You may want to search there before posting as well.
