### ISSUE TITLE
Enhance our of quota check

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#40702]
TODO
- implement optional filesize header for chunked upload
- use it on clients
- until then clients will do a propfind with <d:quota-available-bytes />

- given an user with quota and groupfolders and shared folders
- client uploads a file and receives 507 "quota_exceeded"
- Android would now retry to upload file upon next app start
- instead it would be better to first check if enough quota is available

Problem:
We cannot user user info, as this is only user's quota, but not taking groupfolders or shared folders into account

@kesselb (as we talked about it on chat)

**Comment by kesselb** [comment]
My idea:

The "Destination" is a required header[^1] to start a chunked upload. I assume the destination is everything we need to check if the user has enough quota. 

Therefore it should work to introduce a new optional header "Filesize" for the start chunk request. If the header is given the code should validate if the user has enough quota to upload the file. Without the header, we fall back to the old behavior. 

[^1]: https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/chunking.html#chunked-upload-v2

**Comment by kesselb** [comment]
> We cannot user user info, as this is only user's quota, but not taking groupfolders or shared folders into account

```
curl 'https://server.internal/remote.php/dav/files/admin/TheGroupFolder' \
  --user admin:admin \
  --cookie 'XDEBUG_SESSION=PHPSTORM' \
  --request PROPFIND \
  --data '<?xml version="1.0" encoding="UTF-8"?>
    <d:propfind xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
      <d:prop>
        <d:quota-used-bytes />
        <d:quota-available-bytes />
      </d:prop>
    </d:propfind>' | xmllint --format -
```

Another approach: 
Ask the server for the quota. This should already work for groupfolders, but is not properly documented. 

The properties are:

<d:quota-used-bytes />
<d:quota-available-bytes />

(and not oc:quota-used-bytes/oc:quota-available-bytes as the documenation at https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/basic.html#webdav-basics states)

**Comment by tobiasKaminsky** [comment]
What about non chunked upload?
Desktop uploads 50Mb without, and Android 10MB (which can also get killed by quota)

In general I really like the idea!

**Comment by kesselb** [comment]
> What about non chunked upload?

I think https://github.com/nextcloud/server/blob/master/apps/dav/lib/Connector/Sabre/QuotaPlugin.php should cover non chunked uploads. 

Do you set the X-Expected-Entity-Length, Content-Length or OC-Total-Length header?

**Comment by tobiasKaminsky** [comment]
We set "OC-Total-Length" for non-chunked uploads.
Where and how shall we set it for chunked uploads?
https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/chunking.html

**Comment by tobiasKaminsky** [comment]
Can I check that actually nothing was uploaded on non-chunked uploads?

**Comment by skjnldsv** [comment]
Could this work for you?
https://github.com/nextcloud/server/pull/42679
