### ISSUE TITLE
[BITV]: do we need `tabindex="0"` on `<div id="app-content">`?

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#40708]
This is accessibility issue.

Please check it. Otherwise remove it.

**Comment by ShGKme** [comment]
Is that true that only the "Personal" and "Admin settings" pages have this?

These pages also have `tabindex` on the navigations:

![image](https://github.com/nextcloud/server/assets/25978914/6a87782f-6cf3-41f5-907e-2853961df9a5)

Seems redundant in both keyboard navigation and screen reader navigation to me.

These elements are not interactive, not focused programmatically, and not used in "skip navigation".

Let's remove `tabindex` here.
