### ISSUE TITLE
[BITV]: Contrast of focused checkbox is not enough 

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#40706]
This is accessibility issue.

On this page settings/user/notifications two first checkboxes don't have enough contrast on focused state. 

Check: on master branch this two checkboxes are not available.

![Screenshot from 2023-09-29 12-01-24](https://github.com/nextcloud/server/assets/6078378/571c282a-3e30-4996-9610-f40fa7e2807f)

**Comment by JuliaKirschenheuter** [comment]
same for 

![Screenshot from 2023-10-25 14-15-56](https://github.com/nextcloud/server/assets/6078378/ecd27131-73d9-46ee-a35c-16ff17dbc3ce)

**Comment by marcoambrosini** [comment]
Hi @JuliaKirschenheuter, for all these instances I would go with the same strategy that we have for the button component with the 2 outlines (black and white).

**Comment by JuliaKirschenheuter** [comment]
> 1. Am i right that styles fro the focused state (keyboard as well as mouse click) have to be the same?
> 2. Am i right that "turned off" state must have enough contrasts too?

Fixed both issues

**Comment by michaelnissenbaum** [comment]
Hi @JuliaKirschenheuter I believe you've already made a decision on how to proceed, or do you still need my assistance? Regarding contrasts: In both the "turn on" and "turn off" states, the elements should meet the contrast requirements, which means a minimum of 3:1.

**Comment by JuliaKirschenheuter** [comment]
Hi @michaelnissenbaum,

Thank you! I guess i have no questions on this, thank you!

**Comment by JuliaKirschenheuter** [comment]
Dear @michaelnissenbaum,

After discussion with designers i'm not sure anymore if the the outline _on mouse click_ have to be as same as for the focus via keyboard on interactive elements like radio buttons, toggle buttons. Probably i had some mistaken thinking.

Is it enough to be like this: 

![Peek 2023-10-25 14-43](https://github.com/nextcloud/server/assets/6078378/29efb0ec-92d7-4d32-9fd2-8c133d901a03)

Or have to be like this:

![Peek 2023-10-31 08-58](https://github.com/nextcloud/server/assets/6078378/c02fa55b-3319-4c96-8880-448d6ee6f220)

Thank you!

**Comment by michaelnissenbaum** [comment]
Hi @JuliaKirschenheuter,  From my perspective, the outlines do not need to be identical. What is important from an accessibility perspective is that the interactive elements themselves and their states meet the contrast requirements, and that keyboard focus is clearly visible.

**Comment by JuliaKirschenheuter** [comment]
This problem was soled too:



![Image](https://github.com/nextcloud/server/assets/6078378/08d5dc6a-7f4d-47ec-b0ed-fae59bf982b5)
