### ISSUE TITLE
[BITV]: Modal window improvements

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#40703]
This is accessibility issue.

All necessary dialog parameters like `role="dialog" aria-modal="true" aria-labelledby="modal-name-knqim"` have to be on the modal dialog window, please check. Seems to be already the case 

![Screenshot from 2023-09-29 10-45-33](https://github.com/nextcloud/server/assets/6078378/c8631ebb-d5ac-4d95-8002-8328043277cc)

https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/

**Comment by susnux** [comment]
@JuliaKirschenheuter should the properties be on the modal mask (meaning including the next / prev buttons etc) or just on the modal content (the inner "window")?

**Comment by susnux** [comment]
(They are currently on the mask)

**Comment by JuliaKirschenheuter** [comment]
Actually i think it is right how it is implemented right now. Probably there was some misunderstanding with Michael during our call. I think all this props have to be on the mask.

@michaelnissenbaum could you please make a double check and take as example a modal window on `settings/users` -> "+ New user"?

**Comment by michaelnissenbaum** [comment]
Hi @JuliaKirschenheuter , I've tested it now on both Windows and Mac with NVDA and VoiceOver, and it seems to be working. I have only one note. The close button in the dialog should ideally be labeled "Close" and not "Close modal."
