### ISSUE TITLE
Toggle for opening new tabs from "Recommended Files" widget 

### ISSUE THREAD

**Issue by LokeYourC3PH** [nextcloud/server#40717]
**Is your feature request related to a problem? Please describe.**
Reference to: https://github.com/nextcloud/server/issues/32370

This has now become a feature and it's exactly what we do not like happening on ours. I'd wish it was just turned into a toggle instead in the Administration pages, because now we are forced to open Files/Documents in a new tab when it's something we do not want. Same with the round icon design, who though of that being a good idea? It looks terrible, the icons are now cut off and alpha levels are black, and look like this: 
![image](https://github.com/nextcloud/server/assets/5807595/c623f248-70a1-41f1-9fde-4a3a03db385b)
This doesn't look clean at all anymore, who thought this was a great idea!?

**Describe the solution you'd like**
Round Icons & New Tabs for "Recommended Files" to be turned into toggles, rather than being forced onto users.

**Describe alternatives you've considered**
There are none.

**Additional context**
-

**Comment by kesselb** [comment]
cc @nextcloud/designers

**Comment by szaimen** [comment]
I would agree that cropping the icons here doesnt make much sense so yes, the recommendations app should overwrite this for their widget

**Comment by LokeYourC3PH** [comment]
> I would agree that cropping the icons here doesnt make much sense so yes, the recommendations app should overwrite this for their widget

What's funny is that this didn't used to be a feature in NC 26. It was introduced with NC 27, so it's an odd choice. Same for the fact that recommended files are now opened in different tabs rather than in the same window. That change is fine, _**IF**_ it were introduced as a toggle, not as a forced standard feature.

**Comment by jancborchardt** [comment]
The circular design part of that is indeed not intended, it is already tracked in https://github.com/nextcloud/recommendations/issues/660

**Comment by drankinatty** [comment]
This is the exact same issue I opened on the forum. Clicking in nextcloud should not open pages in a new tab. That sy the browser provides `[ctrl + click]` if the user wants to do so. The webapp should use the existing tab to load the chosen page. The issue on the nextcloud forum is [Nextcloud 28 - Prevent Dashboard From Opening Page in New Tab?](https://help.nextcloud.com/t/nextcloud-28-prevent-dashboard-from-opening-page-in-new-tab/192370/3)

A setting would be fine. Without a setting, this is a bug -- because it cannot be turned off.

**Comment by LokeYourC3PH** [comment]
> This is the exact same issue I opened on the forum. Clicking in nextcloud should not open pages in a new tab. That is why the browser provides `[ctrl + click]` if the user wants to do so. The webapp should use the existing tab to load the chosen page. The issue on the nextcloud forum is [Nextcloud 28 - Prevent Dashboard From Opening Page in New Tab?](https://help.nextcloud.com/t/nextcloud-28-prevent-dashboard-from-opening-page-in-new-tab/192370/3)
> 
> A setting would be fine. Without a setting, this is a bug -- because it cannot be turned off.

Considering that in roughly four months, this issue tracker will be a year old, I'm not really counting on a lot of things being done about this until then or soon thereafter. I understand that the team obviously has plenty to fix, but all it is, is removing the `target="_blank"` from the Dashboard, nothing more than so.

**Comment by drankinatty** [comment]
Should make for a simple quick fix then and be done with it `:)`

**Comment by blackPantherOS** [comment]
Issue (feature) still exists, and this problem prevent to use as Chrome app...
![2024-08-23_07-20](https://github.com/user-attachments/assets/8cf4762e-9025-44ae-9453-b29649341569)

**Comment by jancborchardt** [comment]
Just checked the daily, and "Recommended files" do not open in a new tab anymore:
![image](https://github.com/user-attachments/assets/6e71007f-e4f1-465d-b536-65638a6fb0e9)
