### ISSUE TITLE
[BITV]: resolve statuses in NcSelect

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#40713]
This is accessibility issue.

![image](https://github.com/nextcloud/server/assets/6078378/6f0aafe3-4e1d-468e-a395-815aa3599b5f)

! Please check if this issue is still relevant for current master!

There is an indicator (status) of user inside of select component. This is only visual information which won't be forwarded to a screen reader. There are 2 ways to move forward:

1. Add this information via `aria-label`
2. Remove a statuses from select items

**Comment by AndyScherzinger** [comment]
> 1. Add this information via aria-label

would be the preferred solution from a product perspective
