### ISSUE TITLE
Contacts/Circles - Sort by Ownership first, alphabetically second

### ISSUE THREAD

**Issue by sorbaugh** [nextcloud/server#40746]
Instead of the Circles section being just one list sorted alphabetically, the list should first have the ones you are owner/admin of, then member of, then the rest. Individually these can be sorted alphabetically.

The icons on the left are all the same now, would be good to adjust:
owned/admin: https://pictogrammers.com/library/mdi/icon/account-star/
member: https://pictogrammers.com/library/mdi/icon/account-group/
all others: https://pictogrammers.com/library/mdi/icon/account-group-outline/

This would already make it much more directly obvious which Circles you are member of, without needing to resort to search either.

- [x] #40835
- [x] #40836

**Comment by ArtificialOwl** [comment]
- quick implementation (back-end): https://github.com/nextcloud/circles/pull/1410

**Comment by skjnldsv** [comment]
Front: https://github.com/nextcloud/contacts/pull/3665
