### ISSUE TITLE
[Bug]: can't open documents in new tabs

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/server#40753]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In version 25, it was possible to ctrl-click to open a document in a new tab to work on it.
It is no longer possible since 26.

### Steps to reproduce

1. go to files
2. ctrl-click on a docx file to open an onlyoffice file
3. this opens a new tab
4. and this stays in the "file" app

### Expected behavior

It should open a new tab with onlyoffice.

(It was doing this in Nc25)
(It is still doing this with text app)

### Installation method

Community Docker image

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### Additional info

The js logs:

```
Failed to trigger default action on the file for URL: https://nuage.xxx.xx/index.php/apps/files?dir=/&openfile=2386792 TypeError: context.$file is undefined
    FileClick main.js:169
    action merged-index.js:3080
    initialize merged-index.js:4572
    Underscore 5
    initialize merged-index.js:4567
    FileList merged-index.js:4176
    initialize merged-index.js:83
    <anonymous> merged-index.js:402
    Underscore 5
    <anonymous> merged-index.js:401
    EventListener.handleEvent* merged-index.js:398
[merged-index.js:4587:15](https://nuage.xxx.xx/js/files/merged-index.js?v=fda28b59-23)
    initialize merged-index.js:4587
    Underscore 5
    initialize merged-index.js:4567
    FileList merged-index.js:4176
    initialize merged-index.js:83
    <anonymous> merged-index.js:402
    Underscore 5
    <anonymous> merged-index.js:401
    (Async: EventListener.handleEvent)
    <anonymous> merged-index.js:398
```

**Comment by avatar1024** [comment]
For me it was working in NC26 and NC27 but not possible in NC28 any more.

**Comment by skjnldsv** [comment]
iirc fixed in 28 and above
