### ISSUE TITLE
Lots of SVG source files broken since svgo optimization

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#4076]
When wanting to edit some icons, I stumbled upon this issue:
![capture du 2017-03-26 18-57-33](https://cloud.githubusercontent.com/assets/925062/24333346/66cabfa4-1256-11e7-83cd-71fe9a6aa020.png)
![capture du 2017-03-26 18-55-42](https://cloud.githubusercontent.com/assets/925062/24333345/66ca6284-1256-11e7-8ba0-ab4aa291a459.png)

This seems to be caused by the SVGO optimization: https://github.com/nextcloud/server/pull/1534

While they seem to be correctly displayed, Inkscape has big problems showing them correctly. There’s a reason we use Scour as per https://github.com/nextcloud/server/blob/master/core/img/image-optimization.sh#L10 and not SVGO. ;)

cc @skjnldsv could you check it out? In doubt I’d say your PR needs to be reverted and we should do it via Scour instead – which was already used on most of the icons.

**Comment by jancborchardt** [comment]
@pixelipo while you’re at optimizing, maybe you can look into reverting https://github.com/nextcloud/server/pull/1534 and recompressing the icons using Scour instead (which is not as lossy as SVGO apparently). cc @skjnldsv

**Comment by pixelipo** [comment]
@jancborchardt sure, I'll take a look at it. Assigning myself on this if you don't mind, @skjnldsv

**Comment by jancborchardt** [comment]
@pixelipo awesome, thank you!

**Comment by skjnldsv** [comment]
Is this done? @pixelipo

**Comment by pixelipo** [comment]
I'm working on it, @skjnldsv . There are a lot of files to be fixed...

**Comment by jancborchardt** [comment]
Thank you @pixelipo! :) Most should be possible to fix by getting the state before the PR I mentioned above.

**Comment by skjnldsv** [comment]
sorry @pixelipo I was asking because I was working on something related last month. It wasn't meant to be a reminder, sorry for the poor choice of words! :)
Thanks for your awesome work!

**Comment by pixelipo** [comment]
TO DO:
- [x] optimize remaining `actions` icons #7130 - please review
- [ ] optimize `categories` icons
- [ ] optimize `filetypes` icons
- [ ] optimize `places` icons
- [ ] optimize `rating` icons
- [ ] optimize other icons

**Comment by pixelipo** [comment]
I have to fix other folders as well - see previous comment. At @MorrisJobke suggestion, I will split it across multiple PRs so it's easier to test.

**Comment by MorrisJobke** [comment]
Thanks @pixelipo for all your effort 👍

**Comment by pixelipo** [comment]
Icons in `core/img/`, `apps/files/img/` and `settings/img/` folder have been optimized and cleaned up. In the process, I've managed to cut their size considerably, from 145 kB to 79 kB, without losing quality. It won't make a big difference, but still

Lots of them have also been fixed for better consistency.

**Comment by jancborchardt** [comment]
@pixelipo thank you sooo much for fixing this and the optimization! :) Was a big "design debt" issue.
