### ISSUE TITLE
[Bug]: F2V: Not possible to enter credentials for external storage

### ISSUE THREAD

**Issue by artonge** [nextcloud/server#40776]
### Bug description

When the authentication method for an external storage is set to "User entered, store in database", the file view should display a form to allow the user to enter the credentials.

This was previously done by: https://github.com/nextcloud/server/blob/stable26/apps/files_external/js/statusmanager.js#L389

And I do not see any modal opening in the current implementation: https://github.com/nextcloud/server/blob/7e5e8873070b7fd3071a5eaab5ed467686baa774/apps/files_external/src/actions/enterCredentialsAction.ts#L76-L77

Might be looking at the wrong place. But I was not able to trigger any modal during my testing.

### Steps to reproduce

1. Create an external storage
2. Set the authentication method to "User entered, store in database"
3. Go to the F2V file list
4. Click on the external storage
5. Nothing happens

### Expected behavior

A modal should be displayed to prompt the user for credentials.

### Nextcloud Server version

master

@skjnldsv

**Comment by skjnldsv** [comment]
It was implemented in https://github.com/nextcloud/server/blob/9ebcd287efeea3cf720c2c552a1692f71de5797a/apps/files_external/src/actions/enterCredentialsAction.ts

Why you do not see the button, is another mystery :thinking:

**Comment by skjnldsv** [comment]
> And I do not see any modal opening in the current implementation:

We're using a request for this. Your browser should display a login modal. This is not from a component, this is a vanilla http auth modal.

**Comment by skjnldsv** [comment]
Ah, it works in the external_storage view.
Not in the main files view :thinking: 

I think the config is not fetched, we should do that async, or redirect to the external_storage view if the storage has failed :thinking:
![image](https://github.com/nextcloud/server/assets/14975046/5a9962fd-ed51-4809-9210-4606239c83a8)

**Comment by skjnldsv** [comment]
Ah, this is due to the axios library update...
