### ISSUE TITLE
Separate config option to disallow email changes by users

### ISSUE THREAD

**Issue by akhil1508** [nextcloud/server#40786]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
- As an admin of a nextcloud server, I'd like to disallow users from changing/updating their email
- Currently it is coupled with this `allow_user_to_change_display_name` setting
- I would like to allow them to change their name but not their email i.e. assign them an email at the beginning that cannot be updated later on

**Describe the solution you'd like**
- A config option of `allow_user_to_change_email` to (dis)allow user to update email
- Can default to true

**Describe alternatives you've considered**
- Patching the frontend to make the email field readonly :man_shrugging:

**Comment by kesselb** [comment]
Closing your report in favor of https://github.com/nextcloud/server/issues/16823
