### ISSUE TITLE
[Bug]: Translation mixed content in the new share menu since v27.1.1

### ISSUE THREAD

**Issue by davtheultimate** [nextcloud/server#40801]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since the update in v 27.1.1, a new menu for sharing folder or file is available. But the translations are mixed english / french at it shown on this screenshot :

![image](https://github.com/nextcloud/server/assets/4047863/5a4aac87-138e-4b99-b05a-2de288c02569)

if i edit file fr.js and fr.json from the /apps/file_sharing/l10n/

Translations are present :
server:/var/www/html/nextcloud/apps# grep -r “Note to recipient” files_sharing/l10n/fr.js | more
“Note to recipient” : “Note au destinataire”,
server:/var/www/html/nextcloud/apps# grep -r “Note to recipient” files_sharing/l10n/fr.json | more
“Note to recipient” : “Note au destinataire”,
server:/var/www/html/nextcloud/apps# grep -r “Set password” files_sharing/l10n/fr.json | more
“Set password” : “Définir un mot de passe”,
server:/var/www/html/nextcloud/apps# grep -r “Set password” files_sharing/l10n/fr.js | more
“Set password” : “Définir un mot de passe”,
server:/var/www/html/nextcloud/apps# grep -r “Hide download” files_sharing/l10n/fr.js | more
“Hide download” : “Masquer le téléchargement”,
server:/var/www/html/nextcloud/apps# grep -r “Hide download” files_sharing/l10n/fr.json | more
“Hide download” : “Masquer le téléchargement”,

Who can help me to solve this problem ?

Nextcloud version : 27.1.2
Operating system and version : Ubuntu 22.04)
Apache or nginx version : 2.4.52
PHP version : 8.2

### Steps to reproduce

1. Log in 
2. Share a file or folder with someone
3. click Custom permissions 
4. Check the new menu and translation mixed content

### Expected behavior

we want to have correct use of the selected language and not a mixed content

### Installation method

None

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment]
Cc @Fenn-CS

**Comment by BurtGummer** [comment]
Same problem in version 27.1.2 and the german translation:

![image](https://github.com/nextcloud/server/assets/1249295/0affaab0-5ebc-441d-b64e-da037f2d10cb)

**Comment by davtheultimate** [comment]
One more replacement and it will be perfect. We have two checkboxes that mean the same thing.
"Autoriser le téléchargement" and "Allow Download"

![image](https://github.com/nextcloud/server/assets/4047863/92de4539-b6c2-4df8-89a9-7d1bd28e6fee)
