### ISSUE TITLE
The image was requested to be no SVG file, but converting it to PNG failed: no decode delegate for this image format

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#40811]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrade from 26.0.7 to 27.1.2 in the logs I can observe a warning
``` 
The image was requested to be no SVG file, but converting it to PNG failed: no decode delegate for this image format `' @ error/blob.c/BlobToImage/363
```

### Steps to reproduce

1. Check logs
2. Observe the warning

### Expected behavior

It should be fine

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
In which logs? This seems a ImageMagick warning, not a Nextcloud one.

**Comment by ostasevych** [comment]
> In which logs? This seems a ImageMagick warning, not a Nextcloud one.

Nextcloud logs.

**Comment by solracsf** [comment]
This is a **info** log level from Imagick, you should just ignore it.
https://github.com/nextcloud/server/blob/f2572ebece1e6dc9c6291eb5f6bbb3aa456b011c/apps/theming/lib/ImageManager.php#L117-L119

**Comment by joshtrichards** [comment]
https://github.com/ImageMagick/ImageMagick/discussions/2333

**Comment by joshtrichards** [comment]
Summary to date:

- set your `loglevel` to the default (`2`) and you should be golden from Nextcloud's perspective
- you may wish to investigate why your server's Imagick installation doesn't have `png` support activated in it 

I'm going to close this out since here haven't been any further reports in about a year, and this seems to be an environment matter.

Feel free to follow-up here or at the [community help forum](https://help.nextcloud.com) if you're able to resolve it.
