### ISSUE TITLE
[Bug]: Should not look at IP v6 DNS records i running in PHP without IP v6 support

### ISSUE THREAD

**Issue by walec51** [nextcloud/server#40820]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Update checker and application catalog does not work on hosing the support for IP v6 was not compiled into PHP.

Other users reported it on: https://help.nextcloud.com/t/can-i-stop-nextcloud-from-trying-to-use-ipv6/156683/2

the suggested solution there to comment out the code fixes the problem.

A better solution in `DnsPinMiddleware.php` would be to add  `defined('AF_INET6')` to the `elseif (isset($dnsResponse['ipv6']))` like presented below:

```
			if ($dnsResponses !== false && count($dnsResponses) > 0) {
				foreach ($dnsResponses as $dnsResponse) {
					if (isset($dnsResponse['ip'])) {
						$targetIps[] = $dnsResponse['ip'];
						$canHaveCnameRecord = false;
					} elseif (isset($dnsResponse['ipv6']) &&  defined('AF_INET6')) {
						$targetIps[] = $dnsResponse['ipv6'];
						$canHaveCnameRecord = false;
```

### Steps to reproduce

1. Install nextcloud on a hosting where PHP has no IP v6 support compiled into it.
2.  Go to `/settings/apps` - no apps will be listed

### Expected behavior

Nextcloud should be able to check for updates and download apps catalog 

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment]
Thanks for your report :+1: 

Closing in favor of https://github.com/nextcloud/server/issues/33567
