### ISSUE TITLE
Folder Smart Picker broken

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#40866]
**Describe the bug**
The folder/file smart picker in Office seems broken.
First, it forgets its last used location, every time I open it I have to navigate 6 layers deep again. second, the links it then adds are broken.

Also, the top navigation bar where you pick the smart picker doesn't stick with what I choose, adding extra mouse clicks as well.

**To Reproduce**
1. Open a document, go to insert
2. choose smart picker and go for folder
3. insert a file
4. see a broken link

**Expected behavior**
A working link

**Screenshots**
How about a video:
https://cloud.nextcloud.com/f/7915124
(internally shared to office chat room, sorry for external ppl...)

**Client details:**
Mac OS, Firefox, both in Writer and Spreadsheet

## Server details

**Nextcloud version:**
* 
* 27.2.2
* COOLWSD version: 23.05.3.1 git hash:  a719c0f
* LOKit version: built on Collabora Office 23.05.3.1 git hash: 403de15
* Served by: Ubuntu 22.04.3 LTS 
* 9002c172

**Comment by juliushaertl** [comment]
Relevant code part https://github.com/nextcloud/server/blob/73f3c0aef73dcb08d3e3ac8c6e0f670eb769a8d7/apps/files/src/views/FileReferencePickerElement.vue#L57-L73

**Comment by small1** [comment]
I noice this in the text app. If we pick form a group folder we get a broken link

**Comment by susnux** [comment]
> the dialog is missing thumbnails for me

Fixed with #42057
