### ISSUE TITLE
Lost connection but server but everything works fine except server info

### ISSUE THREAD

**Issue by rulenma** [nextcloud/server#4086]
Iam running nc 11.0.2.7 on nginx with PHP 5.6.30-0+deb8u1 and mysql Ver 14.14 Distrib 5.5.54, for debian-linux-gnu (x86_64) using readline 6.3

It shows up "connection to server lost" with every user.
- What server?

MySQL is connected, the only thing I don't see is the Server Info Page in the Admin menu.
But if I go to the page .../ocs/v2.php/apps/serverinfo/api/v1/info it shows everything what is not display on the server info page.

The logs are looking good. I don't get any connection errors. The only thing what is in the log is this:

{"reqId":"givl1KU7mbt6h4sSCIo4","remoteAddr":"","app":"no app in context","message":"Missing expected parameters in change user hook","level":2,"time":"2017-03-21T10:19:22+00:00","method":"GET","url":"\/ocs\/v1.php\/cloud\/activity?page=0&pagesize=100&format=json","user":"","version":"11.0.2.7"}

**Comment by icewind1991** [comment]
@nickvergessen activity related?

**Comment by rulenma** [comment]
no, all the time

**Comment by bombanfall** [comment]
same error:
nc 11.0.2.7, Ubuntu 16.04.2 LTS, PHP 7.0.15, mysql-server 5.7.17

**Comment by vClouds** [comment]
This problem is clear upon uploading folders/files, It looks like something relevant to apache server timeout, so that, in case of uploading time will be more than the timeout, upload is aborted.
It is completely different than upload_file_size parameter, I set to 512G.
Please advise on how to fix or adjust.

**Comment by MorrisJobke** [comment]
This looks more like a configuration or setup problem. Could you please ask for help in the forums: https://help.nextcloud.com.

Once you found the solution we are happy to make troubleshooting easier by providing more hints from the Nextcloud side, but as of now we don't really know why this fails.
