### ISSUE TITLE
[Bug]: Drag and Drop functionality is not working

### ISSUE THREAD

**Issue by MuhammadShehata** [nextcloud/server#40895]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

drag and drop functionality is not working 

### Steps to reproduce

Dear Nextcloud Support Team,

I hope this message finds you well. I am writing to report a bug that I encountered in my Nextcloud server after updating it to the latest version.

**Issue Details:**
I have noticed that the drag and drop functionality is not working as expected after the update. When I attempt to drag and drop files into Nextcloud, the files do not upload, or I encounter errors. This issue did not exist in the previous version.

Since I rely on Nextcloud for my data management, resolving this issue is crucial for me. I kindly request your assistance in identifying and addressing this bug.

If there are any specific logs or diagnostic information you need from my server to investigate this issue further, please let me know, and I will be happy to provide them.

Thank you for your attention to this matter, and I appreciate your help in resolving this issue. Please let me know if you require any further information.

Best regards

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

master

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "debug": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "XXXXXXXXXXXXXXXX"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.0.2",
        "overwrite.cli.url": "https:\/\/XXXXXXXXXXXXXXXXXXX",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "installed": true,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "app_install_overwrite": [
            "ldap_write_support",
            "customproperties",
            "sms_relentless",
            "welcome",
            "integration_twitter",
            "onlyoffice",
            "passwords",
            "news",
            "announcementcenter"
        ],
        "default_language": "ar",
        "default_locale": "ar_SA",
        "default_phone_region": "SA",
        "auto_logout": true,
        "skeletondirectory": "",
        "lost_password_link": "disabled",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "integrity.check.disabled": true,
        "data-fingerprint": "815b21fcbf7ed67eb07f0dfccfbfaa2e"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - admin_audit: 1.18.0
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.28.0
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 1.23.0
  - files_reminders: 1.0.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - lookup_server_connector: 1.16.0
  - notes: 4.8.1
  - oauth2: 1.16.2
  - provisioning_api: 1.18.0
  - settings: 1.10.0
  - systemtags: 1.18.0
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_ldap: 1.19.0
  - user_status: 1.8.0
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - encryption: 2.16.0 (installed 2.15.0)
  - files_external: 1.20.0
  - sharebymail: 1.18.0 (installed 1.17.0)
  - testing: 1.18.0
```

### Nextcloud Signing status

```shell
NO errors
```

### Nextcloud Logs

```shell
NO errors
```

### Additional info

Thanks

**Comment by vid-bin** [comment]
@szaimen I can confirm on NC 27.1.2 when dragging a folder with 5000 files it doesn't even attempt to create the folder or upload them. However, it did work with a folder that had 600 files.

I can manually create the folder and drag/drop all 5000 files by hand. As long as there are no sub-directories it will at least attempt the upload. Whether it completes or not is another story.

It would be one thing if nextcloud threw an error saying it wasn't going to create the folder because of the file count. But in a production environment where you are uploading a folder with multiple subfolders the silent fail with no error behavior is going to result in data loss for users who aren't aware of it.

**Comment by joshtrichards** [comment]
> Nextcloud Server version
> master
> [...]
> Since I rely on Nextcloud for my data management, resolving this issue is crucial for me.

Hi @MuhammadShehata - While getting early feedback on not yet even released development code is always helpful...

- The code you're running for the Files app is already out of date and does not match current `master` (this likely extends to numerous other pieces of the code you're running since it's under heavy development)
- Are you aware you're running development code in your production environment? 

@vid-bin: Thanks for the feedback but unfortunately it's likely unrelated to this report because there are massive differences between NC27 and the still under heavy development (and unreleased) NC28/master this report is about.  Can you open a separate issue for your matter?
