### ISSUE TITLE
Encryption should be turned on by default if app is activated

### ISSUE THREAD

**Issue by joekerna** [nextcloud/server#4090]
### Steps to reproduce
1. Activate encryption app
2. Upload file as existing or new user
3. Check encryption status of file

### Expected behaviour
In my view once the encryption app is activated, it should automatically be turned on for all users. Or the administrator should be asked if they want it to be turned on for all users. Users might not know about the feature but would still appreciate it. Users who for any reason do not want to use encryption, should be able to deactivate it again.

### Actual behaviour
Encryption is deactivated by default. Only users who know about this feature and knowingly turn it on will have their data encrypted.

### Server configuration
**Operating system**: Ubuntu 16.10

**Web server:** Nginx 1.11

**Database:** MySQL

**PHP version:** 7.0

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Nextcloud website

**Comment by dirigit** [comment]
PLEASE ... don't get me wrong but:

How do you restore a backup when files are encrypted?
How do you restore a file to another place (no web access, server damaged, whatever)?

Set default for encryption OFF as long as there is no solution being independant of web, please!

Changing this will help you and your users to loose all files very fast. You can find it here in "issues" asking why they couldn't decrypt files after some updates ...

**Comment by joekerna** [comment]
I haven't encountered these problems yet, thank for making me aware.

About backup: If I restore my entire Nextcloud installation incl. data directory, the encryption and decryption is still intact

About restoring files without web-interface: Isn't there an option to decrypt using OCC? I've read that somewhere, never used it though?!

**Comment by MorrisJobke** [comment]
cc @jancborchardt @schiessle

**Comment by jancborchardt** [comment]
Encryption is not necessarily something which should be forced upon users. It’s something which can potentially cause you to lose all your files if you forget your password or something unexpected happens. That’s why it should be a conscious choice for something as all your data.

Unless we have a dead-sure approach here, I’d rather not enable it directly for everyone.

**Comment by MorrisJobke** [comment]
@jancborchardt This was more about the two step process we have in place.

**Comment by dirigit** [comment]
@joekerna 
Have a second thought about it, please. ;-)

I give you an example:
You give me a HD, DVD, CD, ... with external backup of several files.

How can I decrypt those files?
How can you decrypt them in case there is no "occ" available / runable?
Be aware that occ is still kind of web app (PHP). Be PHP runable on cli or not - without web there is no PHP on any system normally.

What if en-/decryption changes internal at Nextcloud like it already happened some versions ago?
I would have lost files for this as well. Only my un-encrypted backup saved me.

**Comment by MorrisJobke** [comment]
@dirigit This is the wrong ticket. Please open a new one or ask in the forums for help. This ticket is about the steps to enable encryption.

**Comment by dirigit** [comment]
@MorrisJobke 
I don't think it's wrong ticket because "Encryption should be turned on by default if app is activated" is something where everybody should think about before asking for it.
In both directions: Enycryption and Decryption.

**Comment by MorrisJobke** [comment]
> I don't think it's wrong ticket because "Encryption should be turned on by default if app is activated" is something where everybody should think about before asking for it.

This is for: "default on after I enabled the encryption app". Currently it's a two step mechanism.

**Comment by joekerna** [comment]
Let me describe what made me create this ticket:
I told my users (friends/family) that whatever data they uploaded, that even I couldn't access it. While browsing through my nextcloud directory on my server I randomly discovered, that their data wasn't encrypted after all. This surprised me because I knew I had enabled encryption before.
So this ticket is about the two-step mechanism being inconsistent. My opinion is, that if the administrator enables encryption it should (by default) be enabled for all users. If they should be able to disable it again, is a different question.

**Comment by MorrisJobke** [comment]
> My opinion is, that if the administrator enables encryption it should (by default) be enabled for all users. If they should be able to disable it again, is a different question.

The problem is: there is a second step in the admin settings. Once you as admin click that (because the other users can't) then encryption is enabled.

**Comment by joekerna** [comment]
I've checked 
> Enable server-side encryption 

and
> Encrypt the home storage

Does that mean my users don't have to enable encryption on their own anymore?

**Comment by tflidd** [comment]
it's not related to the feature request itself but you just said:
> I told my users (friends/family) that whatever data they uploaded, even I couldn't access it.

but the documentation tells you this:
https://docs.nextcloud.com/server/11/admin_manual/configuration_files/encryption_configuration.html:
`Encryption keys are stored only on the Nextcloud server, eliminating exposure of your data to third-party storage providers. The encryption app does not protect your data if your Nextcloud server is compromised, and it does not prevent Nextcloud administrators from reading user’s files.`

**Comment by joekerna** [comment]
Thanks @tflidd for pointing that out. I guess I'll have to keep hoping for end-to-end encryption.

**Comment by MorrisJobke** [comment]
Regarding the flow: this is how it was implemented and designed, because different encryption modules can be enabled. So there is no way around the step that the admin needs to select the wanted encryption module.

cc @nextcloud/encryption
