### ISSUE TITLE
[Bug]: File can't be synced and was gone after renaming them

### ISSUE THREAD

**Issue by EvilWatermelon** [nextcloud/server#40953]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After trying to switch the names one file was gone. I can't show the logs because this happened on my work account with limited access. The client says that the sync failed.

### Steps to reproduce

1. Renamed two files (Workshop-01 to Workshop-011 and Workshop-02 to Workshop-01)
2. Switched their names (Workshop-011 to Workshop-02)
3. Workshop-01 is gone.

### Expected behavior

Renaming the files successfully.

### Installation method

None

### Nextcloud Server version

25

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
>  I can't show the logs because this happened on my work account with limited access.

Can you loop in your work NC server admin? Is there a reason you didn't take this to them?

At a minimum, server logs, configuration, and an server apps list will be helpful if to figure out what's going on. There is a reason we ask for them in the bug report form... Since Nextcloud a client-server app, not involving them is troubleshooting blind...

> The client says that the sync failed.

Which client? What version? Etc.

**Comment by EvilWatermelon** [comment]
I asked and they sent me this log entry.

```
{"reqId":"VVBhgzxpMimCp6wx1Vit","level":4,"time":"2023-10-17T14:44:42+00:00","remoteAddr":"93.214.83.72","user":"schroeja","app":"webdav","method":"GET","url":"/remote.php/webdav/Vorlesung%20IT-Sicherheit/Workshops/Workshop-01.pptx?downloadStartSecret=jfggknxzqz8","message":"Datei konnte nicht ge\u00f6ffnet werden","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0","version":"24.0.12.1","exception":{"Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Message":"Datei konnte nicht ge\u00f6ffnet werden","Code":0,"Trace":[{"file":"/srv/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":85,"function":"get","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->"},{"file":"/srv/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpGet","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/srv/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/srv/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/srv/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/srv/www/nextcloud/apps/dav/appinfo/v1/webdav.php","line":87,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/srv/www/nextcloud/remote.php","line":170,"args":["/srv/www/nextcloud/apps/dav/appinfo/v1/webdav.php"],"function":"require_once"}],"File":"/srv/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","Line":496,"CustomMessage":"--"}}
```

**Comment by joshtrichards** [comment]
> 24.0.12.1

Per the log entry you provided this is an end of life version of Nextcloud Server. It's no longer supported.

Feel free to open a new Issue if you can reproduce this on a supported version.
