### ISSUE TITLE
[Bug]:  share-expiration-calendar broken

### ISSUE THREAD

**Issue by MyNameIsRatchet** [nextcloud/server#40982]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In Nextcloud 27.1.2.1, the share-options are broken. If you share something via link and update the settings afterward,
the calendar to define a share-time doesn't work anymore, you can navigate through it but it doesn't accept any date except the next two days. Furthermore you can't set a date by typing, only thing that works is to use arrow-keys.

<img width="200" alt="Bildschirmfoto 2023-10-19 um 15 29 35" src="https://github.com/nextcloud/server/assets/40836975/38f6ca45-6921-4f46-8570-a08b2d2ef363">

I can't find anything in the logs.

### Steps to reproduce

1. Create a folder/file
2. share it (via link/person/mail)
3. Set an expiry date (or try to)

### Expected behavior

It should be possible to choose any date in the future.

### Installation method

Community Docker image

### Nextcloud Server version

27.1.2.1

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

**Comment by szaimen** [comment]
cc @Fenn-CS

**Comment by MyNameIsRatchet** [comment]
Is this supposed to be fixed? Updated today to 27.1.3, issue still exists.
