### ISSUE TITLE
Bug in Plugin Deleted files 1.1.0 in case of using custom user quota?

### ISSUE THREAD

**Issue by thomasimgit** [nextcloud/server#4099]
### Steps to reproduce

1. set user quota to 20GB, use less than 50% of this quota, in my cas 700MB
2. enable external storage (in my case 4 local mounts)
3. delete some files from your cloud
4. check they are displayed in recycle bin, additional you also can check oc_jobs table for new jobs
5. wait some minutes according to cron running jobs table
After cron was running, recycle bin is empty.

In case of setting user quota to a standard value like 10GB I did not observe this behaviour again.

### Expected behaviour
Plugin "Deleted Files" should calculate correct in case of custom user quota limits.

### Actual behaviour
Plugin "Deleted Files" delete files too soon in case of setting custom user quota.

### Server configuration
**Operating system**:
Ubtuntu 16.4 (4.4.0-67)

**Web server:**
Apache/2.4.18 (Ubuntu) 
delivered by Ubtunu

**Database:**
MariaDB
delivered by Ubtunu

**PHP version:**
7.0.15 and additional apcu 5.1.3
delivered by Ubtunu

**Nextcloud version:** (see Nextcloud admin page)
11.0.2

**Where did you install Nextcloud from:**
nextcloud.com

**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - activitylog: 0.0.1
  - apporder: 0.3.3
  - audioplayer: 1.4.1
  - calendar: 1.5.2
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - files: 1.6.1
  - files_automatedtagging: 1.1.1
  - files_downloadactivity: 1.0.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - weather: 1.3.5
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - announcementcenter
  - encryption
  - external
  - federation
  - files_accesscontrol
  - files_retention
  - firstrunwizard
  - notes
  - richdocuments
  - sharebymail
  - survey_client
  - templateeditor
  - user_external
  - user_ldap
  - user_saml

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'instanceid' => 'REMOVED',
  'passwordsalt' => 'REMOVED',
  'secret' => 'REMOVED',
  'trusted_domains' => 
  array (
    0 => 'REMOVED',
    1 => 'REMOVED.REMOVED.REMOVED',
  ),
  'datadirectory' => '/media/storage/nextcloud/data',
  'overwrite.cli.url' => 'http://localhost/nextcloud',
  'dbtype' => 'mysql',
  'version' => '11.0.2.7',
  'dbname' => 'REMOVED',
  'dbhost' => 'REMOVED',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'REMOVED',
  'dbpassword' => 'REMOVED',
  'logtimezone' => 'UTC',
  'installed' => true,
  'versions_retention_obligation' => '180, auto',
  'maintenance' => false,
  'trashbin_retention_obligation' => '180, auto',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'loglevel' => 2,
  'quota_include_external_storage' => false,
  'updater.release.channel' => 'stable',
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
FF 52, Chrome 50

**Operating system:**
Ubuntu 16.4 , Windows 10

*Logs*
there are no error entrys inside the log for this problem

**Comment by thomasimgit** [comment]
Please feel free to contact me, if you need additional informations.

**Comment by MorrisJobke** [comment]
cc @icewind1991 @schiessle

**Comment by skjnldsv** [comment]
There are multiple other issues about this topic iirc.
https://help.nextcloud.com/t/trash-bin-retention-and-threshold-configuration/24650
https://docs.nextcloud.com/server/stable/user_manual/files/deleted_file_management.html
