### ISSUE TITLE
Birthday calendar not generated for shared contacts

### ISSUE THREAD

**Issue by pshlng** [nextcloud/server#410]
### Steps to reproduce
1. Have two users, A with a contact CNTCT with a birthday and B with no contacts, and a contacts and calendar app activated
2. User A shares his contact with user B
3. User A sees the birthday in his calendar user B does NOT

### Expected behaviour
User B should see the birthday

### Actual behaviour
User B does not see the birthday

### Server configuration
**Operating system**: openSUSE Tumbleweed

**Web server:** Apache

**Database:** mariaDB

**PHP version:**

**Nextcloud version:** 9.0.52 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:**

**Signing status (Nextcloud 9.0 and above):**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.2.1
  - admin_audit: 1.0.0
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - password_policy: 1.0.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: 0.9.1
  - templateeditor: 0.1
  - theming: 0.1.0
  - updatenotification: 0.1.0
Disabled:
  - documents
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap
  - user_saml

```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by pshlng** [comment]
I fixed this myself with the patches found at:
https://github.com/owncloud/core/pull/23510/files

and running
sudo -u wwwrun ./occ dav:sync-birthday-calendar

Will this be fixed in an upcomming release?
Will the changed .php files cause problems with updating through the webinterface?

Thank you for owncloud

**Comment by mar1u5** [comment]
The PR you have mentioned above is already merged and in the current Nextcloud `master`.
Will be part of the next major release :wink:

**Comment by GetMike** [comment]
Hi, I just had this problem with a shared addressbook and the birthday calendar. Tried to run the occ with birthday sync, which showed up the calendar-type for user B on the left side under Abonnements (Contact birthdays), but no birthdays are shown in the calendar itself.
For user A all birthdays are shown correctly.

**Comment by pshlng** [comment]
@GetMike: I don't quite understand what you have done so far.
Have you modified or replaced the following file with the changes found
at https://github.com/owncloud/core/pull/23510/files ?:
 apps/dav/appinfo/application.php
 apps/dav/lib/caldav/birthdayservice.php
 apps/dav/lib/dav/groupprincipalbackend.php
 apps/dav/lib/dav/sharing/backend.php
 apps/dav/tests/unit/carddav/birthdayservicetest.php

Did you run "sudo -u wwwrun ./occ dav:sync-birthday-calendar" with
wwwrun changed to your apache user?

Am 29.07.2016 um 10:46 schrieb GetMike:

**Comment by GetMike** [comment]
Sorry - I did not check, that these files have to be replaced. I ran occ dav:sync-birthday-calendar without changing these 5 files. Have to try to get your changes into the affected files first ...
Thanks for your help!

**Comment by pshlng** [comment]
You can view the whole changed file at the link I posted.  Beware that
the files/changes are for version 9.0.52 and not 9.1. According to
mar1u5 the changes should be in the next major release (9.1?) allready.

Am 29.07.2016 um 11:39 schrieb GetMike:

**Comment by GetMike** [comment]
It works! :+1: 
Thanks for your help :)

**Comment by Gurkengewuerz** [comment]
Still had this problem today with NextCloud 10. Update was already in the NextCloud 10. With Website Cron there was no update, had to add "./occ dav:sync-birthday-calendar" to the cronjob for www-data

**Comment by CENTSOARER** [comment]
I upgraded from owncloud 8 to nextcloud 9 (latest version) then again from this to nextcloud 10 and I am having this issue, shared contact bdays from inherited bray calendars are not showing for other users. In NC10 I created a new contacts book for people who don't use a cellphone (mostly babies and chikdren), shared it and it does not have this problem.
