### ISSUE TITLE
[Bug]: "Resend welcome email" does not contain link to set initial password

### ISSUE THREAD

**Issue by pReya** [nextcloud/server#41005]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If you create a new user in the UI and DON'T set a password, the user will receive a welcome E-Mail containing a button/link with the caption "Set your password" ("Setze dein Passwort" in German). It links to `https://cloud.bla.de/lostpassword/reset/form/abcsomeToken123/MisterUsername`.

However, when the admin triggers this E-Mail again via the "Resend welcome mail" button next to the user in the "Users" admin section, the second E-Mail will have different content: It will not contain the same button caption/link. Instead it will only have a link to the home page of the cloud – not to the password set/reset form.

### Steps to reproduce

1. Create a new user via the Admin UI (don't set a password, just username and email)
2. User receives an e-mail with "Set your password" link (don't do it)
3. Resend the email with the "three dots" button next to the user entry
4. User receives another e-mail with a different content/no password set/reset link

### Expected behavior

The second E-Mail should be identical to the first E-Mail

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Looks like the resend option defaults to excluding the password reset token, but when we add a user we first check to see if the password is empty. If it is, we include the password reset token. Seems we need to add the same check in the resend.

https://github.com/nextcloud/server/blob/4828ac352145d2d3eb002e55631bac2d494c96a9/apps/provisioning_api/lib/Controller/UsersController.php#L1569

https://github.com/nextcloud/server/blob/4828ac352145d2d3eb002e55631bac2d494c96a9/apps/settings/lib/Mailer/NewUserMailHelper.php#L100

https://github.com/nextcloud/server/blob/4828ac352145d2d3eb002e55631bac2d494c96a9/apps/provisioning_api/lib/Controller/UsersController.php#L482-L500

**Comment by ezhil56x** [comment]
I would like to work on this issue 🖐🏻. Can I get it assigned ?

**Comment by joshtrichards** [comment]
@ezhil56x No assignment necessary. Feel free to do so.

**Comment by ezhil56x** [comment]
@joshtrichards I have fixed this issue and created a PR on #41038 ⭐️
