### ISSUE TITLE
Honor `Accept` header when downloading directories

### ISSUE THREAD

**Issue by maxnoe** [nextcloud/server#41037]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

The file format one gets when downloading a directory seems to depend on the HTTP `User-Agent` and does not honor the `Accept` header.

macos user agents seem to get `tar` files, while everyone else gets `zip` files.

This makes it hard to write instructions to e.g. download files and unpack them via the command line (e.g. curl / wget) that are valid cross platform.

**Describe the solution you'd like**

It would be great if Nextcloud would honor the `Accept` header when downloading a directory, so that e.g. it is guaranteed that:

```
$ curl -LO -H 'Accept: application/x-tar' <share-link>
# or
$ curl -LO -H 'Accept: application/zip' <share-link>
```

always produces a tar file and a zip file respectively, independent of platform / user agent.

**Describe alternatives you've considered**

A possible alternative would be a query parameter for the filetype.

**Comment by solracsf** [comment]
Yes.
https://github.com/nextcloud/server/blob/5c2610af7dbce72fa1c1b02185a2c28cd5be004e/lib/private/Streamer.php#L43-L44

**Comment by joshtrichards** [comment]
You could always specify the User-Agent too. ;-)

Joking aside, unfortunately even User-Agent wouldn't be sufficient as archive size is also a factor:

https://github.com/nextcloud/server/blob/1de151abd97b892179755012bc448525ca16fe97/lib/private/Streamer.php#L84-L90

Outside of possible [quirks in the zip stream library](https://github.com/nextcloud/3rdparty/blob/master/deepdiver/zipstreamer/MANUAL.md#characteristics) we use (and maybe 32-bit support?), I wonder if there's still a need for different cross-platform archive handling?

**Comment by solracsf** [comment]
I believe this was implemented beacause TAR is native on MacOS, while other formats (ZIP) aren't.

**Comment by skjnldsv** [comment]
Fixed by https://github.com/nextcloud/server/pull/48098
