### ISSUE TITLE
Theming: Force Light or Dark Theme Regardless of System

### ISSUE THREAD

**Issue by wlanowski** [nextcloud/server#41048]
**Is your feature request related to a problem? Please describe.**
Uniform design of our Nextcloud web interface is important to us. Unfortunately, Nextcloud consistently looks entirely different depending on the device settings, especially for unregistered users with whom we want to share data.

**Describe the solution you'd like**
We desire a switch in the administration settings of Nextcloud that enforces either the light or dark theme of Nextcloud for both unauthenticated and authenticated users, regardless of device settings.

**Describe alternatives you've considered**
No alternative ideas. The default, current behavior of Nextcloud should not be influenced. For an alternative solution, such as using custom CSS rules, I would also be grateful.

**Additional context**
Nothing to add

**Comment by joshtrichards** [comment]
Hi @wlanowski - Seems reasonable.

Do you happen to have a specific example (of "looks one way here" versus "looks another way over here")? It'd be helpful to have 1-2  examples to accompany your note. Reproduction steps, screenshots, whatever.

Off the top of my head I recall spots where it's challenging to theme things fully (some fatal error situations for example), but there may be other spots too.

I assume toggling the *Disable user theming* option in the UI as well as setting the `enforce_theme` value in `config.php` weren't fully effective?

**Comment by wlanowski** [comment]
Hey! Thanks for the response!

My issue is that I've customized the branding of Nextcloud (colors and logos) to match the light theme, which registered users also see.

However, when visitors have dark mode enabled at the system level, (non-logged-in) users see Nextcloud in dark mode. This is practical. In my case, though, I want the light mode to be active on every device.

**Comment by pschiffe** [comment]
I'm having the same issue. `'enforce_theme' => 'light'` or _Disable user theming_ option has no effect on non-logged users, for example when sharing files or forms anonymously.

I think the configuration option `enforce_theme` should apply also to non-logged users, at least it makes sense to me. Based on the description I thought that's the option I'm looking for, but no luck.

**Comment by Oriann** [comment]
> Hey! Thanks for the response!
> 
> My issue is that I've customized the branding of Nextcloud (colors and logos) to match the light theme, which registered users also see.
> 
> However, when visitors have dark mode enabled at the system level, (non-logged-in) users see Nextcloud in dark mode. This is practical. In my case, though, I want the light mode to be active on every device.
> 
> EDIT: Adding `'enforce_theme' => 'light'` to the config.php has no effect on non-logged-in users in my case.

Same to me, theming is controllable and applied for registered or signed users but not for visitors of my external links. I wish somebody will make a config switch to force light theme **regardless of system theme that has set up viewing user.**

**Comment by igbjnI05bF** [comment]
This is very important to me as well. The "System Default" setting in Appearance and accessibility seems to default to dark mode for many devices/browsers, including Firefox on my desktop and phone. Dark mode looks very good in Nextcloud, but absolutely terrible and unreadable in Collabora. When I share a link to a spreadsheet and somebody opens it, it's kind of embarrassing. I either have to walk them through manually toggling the light them or else I just tell them to download the file and open locally.

**Comment by ernolf** [comment]
@wlanowski 
> For an alternative solution, such as using custom CSS rules, I would also be grateful.
@pschiffe @Oriann @igbjnI05bF @gravelfreeman @joshtrichards 


Here I described how to achieve this goal:

https://help.nextcloud.com/t/enforce-dark-theme-for-logged-out-users-too/192586/2?u=ernolf

Good luck,
ernolf

**Comment by Oriann** [comment]
> @wlanowski
> 
> @pschiffe @Oriann @igbjnI05bF @gravelfreeman @joshtrichards
> 
> Here I described how to achieve this goal:
> 
> https://help.nextcloud.com/t/enforce-dark-theme-for-logged-out-users-too/192586/2?u=ernolf
> 
> Good luck, ernolf

Thank you for half-easy solution, just tried it and it works right out of box. But still I think we need some official solution because it can broke after few updates if nextcloud staff changes something in frontend.

**Comment by h0lley** [comment]
my current workaround is to create some template overrides within a custom theme:
`/themes/my_theme/core/templates/layout.public.php`
`/themes/my_theme/core/templates/layout.guest.php`

contents:
```php
<?php

$nonce = preg_replace('@^.*nonce-([^\']+).*$@', '$1', apache_response_headers()['Content-Security-Policy']);

# May need to adjust the path if you aren't using docker
$original_include_path = set_include_path(get_include_path().PATH_SEPARATOR.'/var/www/html/core/templates');

ob_start();
include(basename(__FILE__));
$html = ob_get_contents();
ob_end_clean();

set_include_path($original_include_path);

ob_start(); ?>

window.addEventListener('load', function ()
    {
    // Specify your desired permanent theme here
    document.body.dataset.themes = 'dark'
    document.body.dataset.themeDark = true
    })

<?php $js = ob_get_contents();
ob_end_clean();

echo str_replace('</head>', '<script nonce="'.$nonce.'">'.$js.'</script></head>', $html);
```

I am sure there's a cleaner way to retrieve the nonce, but this works for me.
I wrote it so that it still uses the original template files so it wouldn't break any updates.

this is basically this https://github.com/nextcloud/server/issues/41048#issuecomment-2129400726 solution except that it does not use an extra app (originally I used `jsloader` too but looks like it's no longer compatible with current nextcloud version).

if you want to try this and haven't already set up a custom theme, remember to enable it with an entry to your config.php: `'theme' => 'my_theme',`

since this purely lives in your custom theme folder and is only active on pages where we have this issue (e.g. when the user is logged out and the `enforce_theme` config has no effect) for me it's the cleanest workaround atm.

**Comment by skjnldsv** [comment]
Wait a second, I already implemented this :see_no_evil: 
https://github.com/nextcloud/server/pull/32217

https://github.com/nextcloud/server/blob/620d10c842b2fb06f750e9cd2dca29b5c9227b26/config/config.sample.php#L1999-L2005

**Comment by h0lley** [comment]
@skjnldsv people are aware of the `enforce_theme` property for config.php, and it mostly works great (thanks for implementing it!), however the issue here is that it does have no effect for public/guest, i.e. non-logged-in users, which causes pages like the login form or the public share page to appear with broken, inconsistent theming.

@gravelfreeman good to hear that it works for you, too. as for your issues with the logo, I don't have a solution for that on hand as I haven't had this requirement myself, and currently have no capacity to look into this. sorry!

**Comment by skjnldsv** [comment]
Fair point! Let me check the guest one!!

**Comment by skjnldsv** [comment]
Done in https://github.com/nextcloud/server/pull/45875

**Comment by JanBoehme** [comment]
Hi, I just updated from NC 29.0.4 to 29.0.6 and the theme enforcing for embedded content doesn't seem to work anymore.

I have 'enforce_theme' => 'light' in my config, previously (on 29.0.4) this was working fine, also for forms embedded via iframe into a different website. 
Now, when viewed in nextcloud context everything is still looking good, but in the context of the other website, the embedded form will switch to dark mode, when active on the client's system.

Does anybody else experience this behavior and did anything change with the last update?

**Comment by susnux** [comment]
Please open a new issue if you encounter a similar bug.
