### ISSUE TITLE
Mentioning inexistent user has strange feedback

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#4105]
Right now when you mention an inexistent user, your comment looks like this:

![capture du 2017-03-27 22-58-56](https://cloud.githubusercontent.com/assets/925062/24377919/57b3dd70-1341-11e7-8cb1-d3c30ef0538e.png)

It’s a bit much. Instead we should just go for simply this so you can actually see your typo and maybe edit:
![capture du 2017-03-27 22-59-44](https://cloud.githubusercontent.com/assets/925062/24377920/57b61798-1341-11e7-9751-e27532ea564b.png)

Also, we should directly catch it on entry. Like if you typed in `@blabla` and that person does not exist, on click of the submit button show a tooltip saying `@blabla does not exist.` Maybe even with a suggestion afterwards like `Did you mean @blablub?`

@blizzz @nextcloud/javascript

**Comment by blizzz** [comment]
@jancborchardt the username should not be end user visible. _blablub_ might be nice to some degree, however it does not help you to see ``"Heyo @f9590888-8f3f-4549-a796-15e9de8a4da7"``, instead this feels more like a bug.

**Comment by jancborchardt** [comment]
Well the case I mentioned is more for when you @mention someone you can remember the name of, but make a typo (like blizz with 2 z ;)
Your case is some LDAP ID or so which would only appear with autocompletion anyway, so of course there the username would be shown.

**Comment by blizzz** [comment]
OK, so you're case is about mistyping. Honestly, I think it is an OK form of signaling, that something is wrong with the username. You still can edit the comment and fix it. It would work with having the @blabla being not formatted in bold, perhaps, however I am not really convinced it makes a difference.

Agreed, you won't type in a UUID. Now, however, user deletions enters the stage. The admin removes a user, and you'll have the same issue eventually.

**Comment by jancborchardt** [comment]
Ok, closing this then.
