### ISSUE TITLE
[Bug]: share setting shows "download" permission twice

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#41076]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

"Download" permission is showed twice on folder share

### Steps to reproduce

1. go to c.nc.com
2. share a folder
3. click the "..."-menu
4. this is what you see: 
![image](https://github.com/nextcloud/server/assets/1589737/a9abcaf1-a3d7-49b7-91ab-625d01617f91)
5. if you uncheck one of the "allow download" options both get unchecked (same the other way arround)

### Expected behavior

Have only one "allow download" permission

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment]
cc @Fenn-CS
