### ISSUE TITLE
Custom theme filetypes icons not loaded

### ISSUE THREAD

**Issue by ncgu** [nextcloud/server#411]
### Steps to reproduce

A cutom theme is needed.

1. Create in the cusom theme under img a subfolder named filetypes. (<nextcloud_root>\Themes\mytheme\core\img\filetypes)
2. copy modified files like file.png, file.svg, folder.png, folder.svg, .. in the filetypes folder
3. Logon to nextcloud in webbrowser and go to files app
4. Folder icon is still the default icon (<nextcloud_root>\core\img\filetypes).

### Expected behaviour
Filetypes, Actions Images in custom theme should be shown

### Actual behaviour
Folder Icon is still the default icon (<nextcloud_root>\core\img\filetypes).
Same with actions subfolder.

A Workaround is to replace the files in the original location. But after that the integrity check warns. Disabling the integrity check seems not the right way.

### Server configuration
**Operating system**: 
CentOS release 5.11 (Final)

**Web server:**
Apache/2.2.31

**Database:**
MySQL 5.1.73

**PHP version:**
7.0.6

**Nextcloud version:** (see Nextcloud admin page)
9.0.52

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Owncloud 9.0.3

**Where did you install Nextcloud from:**
manually

**Comment by juliushaertl** [comment]
Have you been running `./occ maintenance:mimetype:update-js` after copying the files to your theme?

**Comment by ncgu** [comment]
no, unfortunally I`m not in the sudoers list. I have no right to run occ command.
Is there an alternative way?

**Comment by MorrisJobke** [comment]
> Is there an alternative way?

Not really :(

**Comment by ncgu** [comment]
Thanks, fixed with NC10 (great release)

**Comment by rebeccaformfx** [comment]
Has this been fixed in NextCloud 12?  I'm running into the same problems

**Comment by cromg** [comment]
I'm experiencing the some problem on NC 12

**Comment by juliushaertl** [comment]
@cromg @rebeccaformfx There have been some fixes with 12.0.1 you can already try if it works on the RC4 release. If it is still broken, please open a new issue with details on your setup and log information.
