### ISSUE TITLE
Question: SSL-Postgres

### ISSUE THREAD

**Issue by apvxw** [nextcloud/server#4110]
How I can configure nextcloud to use an ssl connection to a postgres database?

Volker

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by MorrisJobke** [comment]
We have generic dbdriveroptions in the config.php: https://github.com/nextcloud/server/blob/4f752ed1fcb338d1f56037426c8eb77c73599cb7/config/config.sample.php#L1226-L1233

Nevertheless I could not find how to connect via PDO to Postgres via SSL. At least there are not separate parameters. http://php.net/manual/en/ref.pdo-pgsql.php

This is then more a problem with the configuration of the PDO than of Nextcloud. Once you know how to do this you could report back. I couldn't find an obvious way how to configure it.

**Comment by MorrisJobke** [comment]
> This is then more a problem with the configuration of the PDO than of Nextcloud. Once you know how to do this you could report back. I couldn't find an obvious way how to configure it.

Neither could I find a reason, why it should not work.

**Comment by Routhinator** [comment]
SSL params can be passed to the PDO driver:

https://www.php.net/manual/en/ref.pdo-pgsql.connection.php 
https://stackoverflow.com/questions/46852880/connecting-to-pgsql-over-ssl-via-php-pdo

**Comment by Ramblurr** [comment]
> SSL params can be passed to the PDO driver:

Via which parameters in config.php?

**Comment by sundowndev** [comment]
Having the same issue. Is there a way to edit connection string from the config.php file ?

**Comment by Ramblurr** [comment]
It turns out you add additional parms as semi-colon delimited items in the `host` field:

For example:

`my-pg.host.com:5432;sslmode=verify-ca;sslrootcert=/path/to/ca.pem`

Username and password must be specified separately. There is no support for URI style connection strings.

**Comment by chris-makaio** [comment]
are you sure? As soon as I try that the web UI times out...

**Comment by sundowndev** [comment]
> It turns out you add additional parms as semi-colon delimited items in the `host` field:
> 
> For example:
> 
> `my-pg.host.com:5432;sslmode=verify-ca;sslrootcert=/path/to/ca.pem`
> 
> Username and password must be specified separately. There is no support for URI style connection strings.

I tried but it doesn't seem to work.

**Comment by sundowndev** [comment]
Please reopen this issue, database over SSL is a must-have! 

> Nevertheless I could not find how to connect via PDO to Postgres via SSL. At least there are not separate parameters. http://php.net/manual/en/ref.pdo-pgsql.php
>
> This is then more a problem with the configuration of the PDO than of Nextcloud. Once you know how to do this you could report back. I couldn't find an obvious way how to configure it.

According to comments on the PDO Postgres connection string manual, the full DSN string is passed directly to the underlying library function PQconnectdb. Consequently, you should be able to use all the parameters specified in the PostgreSQL documentation for that string.

**Comment by yan12125** [comment]
Ramblurr's trick (https://github.com/nextcloud/server/issues/4110#issuecomment-765237450) works like a charm, thanks! I can also connect with client certificates. For example, I have something like this in `config.php`:
```
'dbhost' => 'db.example.com;sslmode=verify-full;sslrootcert=/etc/ssl/cert.pem;sslcert=/path/to/client-cert.crt;sslkey=/path/to/client-cert.key',
```
