### ISSUE TITLE
[Bug]: Cannot open web-based documents from built-in Office Server

### ISSUE THREAD

**Issue by blessio** [nextcloud/server#41118]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Cannot open any Collabora document inside the browser, can only download to edit them.
If the document is md file or any non-Collabora document, then it opens fine
----
Version: [Nextcloud Hub 6] (27.1.1) snap installation
Settings: In Nextcloud Office select "Use build-in CODE - Collabora Online Development Edition" 

### Steps to reproduce

1. Create a document 
   OR find one in files page
2. Click to open it

### Expected behavior

Expected behaviour:
  - Open the document in a page so that it can be edited within the browser
 
Actual behaviour:
  - a new page opens but stays in permanent loading status and the loading never finish. 
  

### Installation method

Community SNAP package

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Logs

```shell
[index] Error: Exception: OCA\Text\Service\DocumentService::getFileForSession(): Argument #1 ($session) must be of type OCA\Text\Db\Session, bool given, called in /snap/nextcloud/37728/htdocs/apps/text/lib/Service/ApiService.php on line 232 in file '/snap/nextcloud/37728/htdocs/apps/text/lib/Service/DocumentService.php' line 442 at <<closure>>

0. /snap/nextcloud/37728/htdocs/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /snap/nextcloud/37728/htdocs/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main()
2. /snap/nextcloud/37728/htdocs/lib/base.php line 1068
   OC\Route\Router->match()
3. /snap/nextcloud/37728/htdocs/index.php line 36
   OC::handleRequest()

Caused by:

TypeError: OCA\Text\Service\DocumentService::getFileForSession(): Argument #1 ($session) must be of type OCA\Text\Db\Session, bool given, called in /snap/nextcloud/37728/htdocs/apps/text/lib/Service/ApiService.php on line 232 at <<closure>>

0. /snap/nextcloud/37728/htdocs/apps/text/lib/Service/ApiService.php line 232
   OCA\Text\Service\DocumentService->getFileForSession()
1. /snap/nextcloud/37728/htdocs/apps/text/lib/Controller/SessionController.php line 92
   OCA\Text\Service\ApiService->sync("*** sensitive parameters replaced ***")
2. /snap/nextcloud/37728/htdocs/lib/private/AppFramework/Http/Dispatcher.php line 230
   OCA\Text\Controller\SessionController->sync("*** sensitive parameters replaced ***")
3. /snap/nextcloud/37728/htdocs/lib/private/AppFramework/Http/Dispatcher.php line 137
   OC\AppFramework\Http\Dispatcher->executeController()
4. /snap/nextcloud/37728/htdocs/lib/private/AppFramework/App.php line 183
   OC\AppFramework\Http\Dispatcher->dispatch()
5. /snap/nextcloud/37728/htdocs/lib/private/Route/Router.php line 315
   OC\AppFramework\App::main()
6. /snap/nextcloud/37728/htdocs/lib/base.php line 1068
   OC\Route\Router->match()
7. /snap/nextcloud/37728/htdocs/index.php line 36
   OC::handleRequest()

POST /index.php/apps/text/session/sync
from ***sensitive*** by ***sensitive*** at 2023-10-25T13:17:01+00:00
```

### Additional info

I am pretty sure that this was working before then it stopped after an update.
As I was not sure and changed too many settings, I decided to reinstall it completely from scratch. Unfortunately, the reinstalled instance on a fully initialized virtual machine also has the same failure. 

The failure is well defined here: 
   https://help.nextcloud.com/t/nextcloud-office-showing-only-loading/142448

**Comment by joshtrichards** [comment]
The community snap project hasn't supported Office for quite a while:

See nextcloud-snap/nextcloud-snap#2508

**Comment by joshtrichards** [comment]
Though there seems to be some paths:

https://github.com/nextcloud-snap/nextcloud-snap/wiki/FAQ's#q-nextcloud-office-is-not-working-in-nextcloud-snap-what-can-i-do

https://github.com/nextcloud-snap/nextcloud-snap/wiki/Configure-CODE-and-Nextcloud-office-for-Nextcloud-snap
