### ISSUE TITLE
Theming retieving Logo bug

### ISSUE THREAD

**Issue by usselite** [nextcloud/server#4111]
Whenever you try to retrieve the Logo used within Nextcloud while it is set to default, I am unable to retrieve it. This happens in fresh installations as well as a situation where the logo is reset to the default Nextcloud logo.

### Steps to reproduce
1. Get the Nextcloud logo using: https://demo.nextcloud.com/xxx/apps/theming/logo

### Expected behaviour
The SVG file for the Nextcloud logo.

### Actual behaviour
File not found result.

### Steps to reproduce
1. Admin > Theming > Logo: - Upload a random image as logo...
2. Admin > Theming > Logo: - Reset logo to default.
3. Get the Nextcloud logo using: https://demo.nextcloud.com/xxx/apps/theming/logo

### Expected behaviour
The SVG file for the Nextcloud logo.

### Actual behaviour
It downloads the old logo.

### Server configuration
**Nextcloud version:** 11.0.2.

</details>

**Comment by jospoortvliet** [comment]
@juliushaertl that's your baby ;-)

**Comment by juliushaertl** [comment]
The URL should not be used anywhere when theming is disable or no custom logo is set.

@usselite Is the logo missing anyhwere in the UI? Where is the url being called?

**Comment by usselite** [comment]
The logo isn't missing anywhere in the UI itself.

I retrieve the URL from: https://demo.nextcloud.com/xxx/ocs/v2.php/cloud/capabilities, I use it for styling the Outlook Add-In I am developing.

In case the URL shouldn't be used if no custom logo is set, it does not behave as intended when you set the default logo back. It downloads the old, earlier set obsolete logo @see situation 2. There's no way to detect else if the logo is still valid or not.

**Comment by juliushaertl** [comment]
Ok, now I get it. But it works for me as expected on the demo.nextcloud.com instances. Looks tihs is currently broken on master due to moving images to the app data directory but is will be fixed by #3531.

**Comment by MorrisJobke** [comment]
Fixed with #4594
