### ISSUE TITLE
[Bug]: Nextcloud log page is not shown

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#41132]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I try to read logs from webUI with the help of the logreader app `/settings/admin/logging` I cannot see anything apart of infinitely rotating wheel icon. When I remove nextcloud log, the logs appears but not for so long.  Loglevel = 0 in the config file.

### Steps to reproduce

1. Go to settings
2. Click on Log
3. Observe nothing
4. Remove nextcloud.log file
5. Observe that the log shown again.

### Expected behavior

The page with log is shown in full every time I pass on the specific page.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report
```
logtype => file
logfile => /var/log/nextcloud.log
loglevel = 0
```

**Comment by susnux** [comment]
Hey thank you for the report. 
Are there any logs in the browser console?

**Comment by joshtrichards** [comment]
Isn't this a duplicate of your prior report: nextcloud/logreader#1025

**Comment by ostasevych** [comment]
> Isn't this a duplicate of your prior report: [nextcloud/logreader#1025](https://github.com/nextcloud/logreader/issues/1025)

Yes, it is the one. Sorry for duplicating.
