### ISSUE TITLE
[BITV]: Styles of left sidebar will be changed as far right sidebar will be opened

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#41153]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Styles of left sidebar will be changed as far right sidebar will be opened

![Peek 2023-10-27 12-39](https://github.com/nextcloud/server/assets/6078378/9a4e652e-7902-42e8-a4bb-16732fe0b85a)

### Steps to reproduce

1. Go to "files"
2. Navigate though different navigation items
3. Open "details" of any file
4. See that styles of the left sidebar are changed - and won't pass a11y requirements  

### Expected behavior

Left sidebar styles stay unchanged

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ShGKme** [comment]
The problem is not related to the right sidebar, but caused by non-scoped styles in the app navigation components.
