### ISSUE TITLE
[Bug]: Missing 27.1.3 Release

### ISSUE THREAD

**Issue by AdrianSchoennagel** [nextcloud/server#41172]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hey, 

yesterday I updated my linuxserver/nextcloud docker through the WebUI, which brought me to 27.1.3. However, linuxserver only has docker images for 27.1.2 available, which leaves me with a non running instance. 

The issue seems to be that this github does not have a release build (only RC not stable) of v27.1.3. Since linuxserver.io only updates thier docker images based on stable releases listed here https://github.com/nextcloud/server/releases - it means if I swtich to the latest tag lscr.io/linuxserver/nextcloud:latest it will only update to Nextcloud v27.1.2.

This is simmilar to #39845

### Steps to reproduce

see description and #39845

### Expected behavior

One of the following:
- Releases on Github repo as new versions get tagged
- WebUI does not update to a pre-release version

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by AdrianSchoennagel** [comment]
Any reason why this was missed? and would it be possible to get the release?

Thanks :)

**Comment by kesselb** [comment]
Thanks for letting us know 👍

cc @blizzz @skjnldsv

**Comment by skjnldsv** [comment]
Done, missed that one, my bad.
Tags were created though

**Comment by nemchik** [comment]
> Done, missed that one, my bad. Tags were created though

Just to call out, tags don't indicate whether a version is a stable or dev/pre release, so our (LSIO) build system relies on the GitHub releases for detection. Tag naming (ex: including `rc` or `beta` or other things of that nature) could be considered, but we build images for a large number of applications, and unfortunately naming and releases is inconsistent at best across the board. GitHub releases vs pre-releases usually ends up being a pretty safe way for us to pick up when we need a new build (which is automated on our end).

If there's a better recommended way for us to know when there's a new release and whether it's a stable or dev release we would be happy to adjust our build detection to prevent this issue from occuring. Alternatively if your process for releasing new versions could automate releases/pre-releases on GitHub that would also resolve the issue with our image being behind.

Lastly, the logic we implement that checks the version of the container against the version the user installed was largely copied from the official nextcloud image, and the issue occurs only when the user notices and applies an update via the Web UI. If there could be some way for the container environment to indicate that web UI updates should be disabled and notify the user to only update the container via applying an update to the image that would be awesome. I tried removing the update notification app (which seems to be done in the nextcloud aio project) but this also disabled update notifications for user installed apps, not just the core, so I got rid of the logic in our image that removed the update notification app.

**Comment by AdrianSchoennagel** [comment]
Thank you all very much for getting this resolved quickly. 
Hope you guys can find a way to prevent this in the future :)

**Comment by joshtrichards** [comment]
@nemchik 

> [...] the issue occurs only when the user notices and applies an update via the Web UI. If there could be some way for the container environment to indicate that web UI updates should be disabled and notify the user to only update the container via applying an update to the image that would be awesome.

Is `upgrade.disable-web` what you're looking for perhaps?

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#upgrade-disable-web

**Comment by nemchik** [comment]
> @nemchik
> 
> > [...] the issue occurs only when the user notices and applies an update via the Web UI. If there could be some way for the container environment to indicate that web UI updates should be disabled and notify the user to only update the container via applying an update to the image that would be awesome.
> 
> Is `upgrade.disable-web` what you're looking for perhaps?
> 
> https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#upgrade-disable-web

That seems promising. Does that setting affect only the core of Nextcloud, or does it also disable upgrading installed apps? If it's just the core, it would be pretty easy to tuck into our init that runs on each container startup.

**Comment by joshtrichards** [comment]
Just core.

**Comment by nemchik** [comment]
Awesome. That's merged and building a new release for our image (stable and dev tags). Thanks!
