### ISSUE TITLE
Move from Drone to GitHub Actions

### ISSUE THREAD

**Issue by susnux** [nextcloud/server#41187]
* We then can reuse Drone workers more flexible as GitHub runners for other tasks
* No need to maintain two different CI systems
* Ability to restart failed CI processes without Drone admin rights

### Progress
* [x] Move all unit tests
  * https://github.com/nextcloud/server/pull/41003
* [x] Move all integration tests
  * [x] https://github.com/nextcloud/server/pull/44191
  * [x] https://github.com/nextcloud/server/pull/41139
  * [x] WebDav https://github.com/nextcloud/server/pull/43220
  * [x] Samba https://github.com/nextcloud/server/pull/43516
* [x] Move checkers https://github.com/nextcloud/server/pull/43514
* [ ] Move Litmus / CalDAV testsuite
* [x] Move acceptance tests (best case: use Cypress)
  * [x] Login tests: https://github.com/nextcloud/server/pull/41033
  * [x] Access levels: https://github.com/nextcloud/server/pull/41137
  * [x] Contacts menu: https://github.com/nextcloud/server/pull/41190
  * [x] Apps: https://github.com/nextcloud/server/pull/41303

We should prepare all of them and move them together so we can reuse the Drone workers quickly and reduce Drone to 3-5 workers for stable branches and Talk.

cc @skjnldsv @nickvergessen

**Comment by nickvergessen** [comment]
Talk migrated away already, also only using it for stable branches

**Comment by nickvergessen** [comment]
That being said, it would be helpful to execute that before the branch off, or backport it, so any recent fixing isn't cloncking legacy CI immediately

**Comment by susnux** [comment]
Samba seems to be a bit more complex, but I will look into that one so we can finalize this :)
