### ISSUE TITLE
Add endpoint for current bruteforce protection timeout

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#4118]
As discussed with @mario

**Comment by MorrisJobke** [comment]
Endpoint as in what?

**Comment by MorrisJobke** [comment]
I would like to move this to 13. Is this okay?

**Comment by MorrisJobke** [comment]
> I would like to move this to 13. Is this okay?

No response -> moved

**Comment by MorrisJobke** [comment]
Available via https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/lib/private/Security/Bruteforce/Capabilities.php#L50

Added in #5699
