### ISSUE TITLE
Too many DNS queries

### ISSUE THREAD

**Issue by tdltdl** [nextcloud/server#41182]
### ⚠️ This issue respects the following points: ⚠️

- [ ] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In a very short time frame I see that Nextcloud is making a huge number of DNS requests. My DNS server blocked it with error "Client w.x.y.z has been rate-limited (current config allows up to 1000 queries in 60 seconds)".
The queries are always the same (either to my database server or to my file storage host)
This indicates that the DNS client used is not caching any result (not respecting the TTL) and also that the DB connection is not using any pooling mechanism (which means lots of connect disconnect to the database).
This also means extra latency for each and every action will negatively impact responsiveness of NextCloud

### Steps to reproduce

1. Configure DB with a host name (i.e. not localhost/ip address/host defined in /etc/hosts), do the same for an external store (like SMB)
2. Do a TCP dump to monitor the DNS queries from NextCloud or look at the DNS logs

### Expected behavior

A DNS lookup should be cached respecting the TTL returned by the DNS server.

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "27.1.2.1",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "maintenance": false,
        "maintenance_window_start": 1,
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "app_install_overwrite": [
            "googledocsredirect"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "XX"
    }
}
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by solracsf** [comment]
PHP DNS queries respect the TTL (Time to Live) values returned by the DNS servers. When you perform a DNS query in PHP using functions like `gethostbyname()` or `dns_get_record()`, the TTL value is included in the DNS response. The TTL specifies how long the DNS information is considered valid and should be cached.

PHP does not handle DNS caching itself but relies on the underlying system's DNS resolver. The DNS resolver in the operating system typically caches DNS records (or not) for the duration specified by the TTL.

PHP respects the TTL values returned by DNS servers, but the actual caching and TTL management are handled by the operating system's DNS resolver (`systemd-resolved` or `dnsmasq` (examples) respect and cache DNS requests)
