### ISSUE TITLE
[BITV] Make admin collaborative tags markup accessible

### ISSUE THREAD

**Issue by Pytal** [nextcloud/server#41208]
Current markup https://github.com/nextcloud/server/blob/16bfe0cc65c3c4603c24d10c904c1aef39d5a9a2/apps/systemtags/templates/admin.php

![image](https://github.com/nextcloud/server/assets/24800714/7c21698c-0d49-4ead-ac31-a7267e8e820c)

**Comment by Pytal** [comment]
This form is used for editing tags if one is selected or creating tags if no tag is selected

We are placing the "Search for a tag to edit" input for editing existing tags inside the `form`
![image](https://github.com/nextcloud/server/assets/24800714/2caea164-c1d7-4890-a662-dfa69ab6f273)

Is this acceptable @michaelnissenbaum?

**Comment by michaelnissenbaum** [comment]
Visually, it looks okay to me. However, I would like to test a working example to be sure that it is truly accessible.
