### ISSUE TITLE
[Bug]: Files/Folders not visible in trash bin when deleting from shared folder

### ISSUE THREAD

**Issue by christianwolfcodesorcerer** [nextcloud/server#41220]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When deleting folders or files from a shared folder they are not shown in trash bin and can not be restored.

Installation details: 
- helm chart nextcloud-3.5.21
- image: tag: 26.0.5-apache
- db: mariadb
- redis: enabled

### Steps to reproduce

1. Log in as admin
2. Create two users
3. Log in as first user
4. Create a folder with subfolders and files and share it with the second user (permissions: 15)
5. Log in as second user
6. Delete a subfolder or a file in the shared folder and open trash bin 
7. Trash bin is empty
11. Log in as first user again
12. Deleted file/folder is in trash bin and can be restored

### Expected behavior

A user should be able to see deleted files/subfolders from a shared folder and restore them (if he has sufficient rights).

### Installation method

None

### Nextcloud Server version

26

### Operating system

Other

### PHP engine version

Other

### Web server

Other

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by fqueruel** [comment]
Hi,
I'have the same bug in 27.6.1.2.
Trash appears like empty on the web, but not in the iPhone app.

**Comment by joshtrichards** [comment]
@fqueruel Your issue is likely #43134  which was fixed in #43136 this past week.

**Comment by solracsf** [comment]
Should be fixed by https://github.com/nextcloud/server/pull/43259
