### ISSUE TITLE
[bug] Group permissions for external storage is broken in Nextcloud 11

### ISSUE THREAD

**Issue by andrewhotlab** [nextcloud/server#4122]
Since Nextcloud 11, global-defined external storage folders become inaccessible by users. 
For all of them we configured [User and Group Permissions](https://docs.nextcloud.com/server/11/admin_manual/configuration_files/external_storage_configuration_gui.html#user-and-group-permissions). Clearing the "available for" field, or inserting user names instead of a group names, solves the problem.

The issue was first spotted in the [Community support forum](https://help.nextcloud.com/t/group-permissions-for-external-storage-is-broken-in-nextcloud-11-0-x/9252).

### Steps to reproduce
1. enable External Storage Support application;
2. globally add and external folder of type SMB/CIFS;
3. put a group name in the field "available for";
4. login as a user which belongs to the groups you selected at step 3.

### Expected behaviour
You should be able to browse and see files in the external folder.

### Actual behaviour
The user cannot see any content in the external folder until the "available for" field is cleared.

### Server configuration
**Operating system**: FreeBSD 10.3

**Web server:** Apache 2.4.25

**Database:** MariaDB 10.1.21

**PHP version:** 5.6.30

**Nextcloud version:** 11.0.1 / 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 10.0.3 (problem exists in fresh install too)

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory

**Comment by andrewhotlab** [comment]
I have no development knowledge, however I tried to guess where the cause might lie... please excuse my ignorance, but I really need to make this feature work again: this is preventing us to upgrade to the 11.x branch.

Maybe the functions getAllStoragesForUser() and getMountsForUser() are responsible for checking which external storage folder should be presented to the user. I found them in these files:

> apps/files_external/lib/Config/ConfigAdapter.php
> apps/files_external/lib/Service/DBConfigService.php
> apps/files_external/lib/Service/UserGlobalStoragesService.php

**Following this path I finally discovered that things went wrong with [this commit](https://github.com/nextcloud/server/commit/b573c5b8f807eec913c494b0ec4a54f91ff143e6).**

I can confirm this because I upgraded our 10.x instance to the [previous commit](https://github.com/nextcloud/server/commit/8741acf8a6dfb3919c43d3cee5a9c13f6c1e4b9f) (which displays the version "11.0 alpha" in the admin pages) and all external folders, which availability is managed through group membership, were still visible at that point. Upgrading the code to the next commit makes the issue come back.

I only spotted the cause, but I'm unable to actually identify and fix it, please someone help me at this point... thanks! :)

**Comment by icewind1991** [comment]
Cant reproduce the problem using either stable11, master with mysql and postgresql

**Comment by andrewhotlab** [comment]
Hi Robin, thank very much for your reply. I tested and confirmed the issue with versions 11.0, 11.0.1 and 11.0.2. Just checked out stable11 and master, but I cannot even upgrade either of them, with the following error:

> \# sudo -u www php occ upgrade
> PHP Fatal error:  Class 'Stecman\Component\Symfony\Console\BashCompletion\CompletionCommand' not found in /usr/local/www/apache24/data/nextcloud/core/register_command.php on line 36

**Comment by andrewhotlab** [comment]
For the sake of completeness, I just tried without upgrading our 10.x instance. I installed from scratch the master branch: same problem. I did not found anything neither in nextcloud.log and httpd-error.log files to help us identify were the problem lie.

**Comment by andrewhotlab** [comment]
As I wrote, I've no such a competency on PHP, but if it can be helpful to someone: I just reverted the file apps/files_external/lib/Config/ConfigAdapter.php to make use of the function getUniqueStorages() instead of the newer getAllStoragesForUser(), and access to global external folders turns back working.
Maybe that getAllStoragesForUser() has a bug preventing it to check the "available for" setting?

**Comment by andrewhotlab** [comment]
Sorry, but after months of delay in migrating to thee 11 release because of this issue, we are seriously thinking about switching back to OC. If someone read this and have the clue to fix the problem, I'd be happy to sponsor his/her work: please contact me directly. Thanks!

**Comment by icewind1991** [comment]
Ok, I was finally able to reproduce this issue, https://github.com/nextcloud/server/pull/5042 should fix it

**Comment by andrewhotlab** [comment]
STR instead of INT: "one small word for a developer, one giant leap for users"! ;)

Thank you so much Robin: you saved my day!!

Looking forward approvation of #5042
