### ISSUE TITLE
[Bug]: Admin overview displays Nextcloud version as the instance name's version

### ISSUE THREAD

**Issue by TristanCottam** [nextcloud/server#41249]
In the *Overview* tab of the *Administration settings*, the instance's Nextcloud version is formatted as "`instance name` `Nextcloud version`", despite the version number referring to Nextcloud itself. Instead, it should be formatted as "Nextcloud `Nextcloud version`".

**Comment by kesselb** [comment]
![image](https://github.com/nextcloud/server/assets/3902676/f4137197-0331-4e2f-8182-12aa4e4c4cac)

cc @nextcloud/designers

**Comment by solracsf** [comment]
This has been like this for years (also, instance name is clickable).
Never chocked me, I confess. 🧓

**Comment by szaimen** [comment]
Yes, it should definitely be Nextcloud 28.0.0. dev. So without branding.
