### ISSUE TITLE
[BITV]: NcSelect loose a focus during scrolling down a parent content

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#41257]
This is accessibility issue.

![Peek 2023-10-31 10-05](https://github.com/nextcloud/server/assets/6078378/cf23a870-3921-4177-a8c0-9eb6775215a3)

Probably this is a bug of an upstream library. Then we can't fix it for now.

**Comment by susnux** [comment]
This can not be fixed due to virtual scrolling. From testing: When a user is navigating via keyboard, there is no such scroll. When via mouse or mixed, it seems to be fine to focus again.
