### ISSUE TITLE
[BITV]: Replace links for "collaborative tags" with buttons

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#41259]
This is accessibility issue.

- [ ] Replace "Send email" input filed with real button

![Screenshot from 2023-10-30 14-05-20](https://github.com/nextcloud/server/assets/6078378/4805d57b-deab-4572-af13-199c19a83ae0)

**Comment by Pytal** [comment]
Already handling the collaborative tags part in https://github.com/nextcloud/server/issues/41208 ;)

**Comment by JuliaKirschenheuter** [comment]
> Already handling the collaborative tags part in #41208 ;)

great, closing issue
