### ISSUE TITLE
Can not create folders with a unique name when not having update permissions

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#41260]
### Steps

1. As UserA create a folder FolderA
2. As UserA share FolderA with UserB with `read+create` permissions
3. As UserB try to create a FolderB inside FolderA
4. The folder `New folder` gets created and due to lack of update permissions you can not rename it:

![grafik](https://github.com/nextcloud/server/assets/213943/8010a80a-c8ff-4843-bff2-d528fe3754f1)

**Comment by skjnldsv** [comment]
Suggestion:
- If current folder does not have Update permission
- OR if access_control is enabled

 we open a modal to request the name instead of creating before and renaming

**Comment by sorbaugh** [comment]
While this in't good from a UX perspective, due to the lack of Update permissions, Nextcloud is technically behaving "correctly" here, I suppose? Did the behavior change with NC 28?

**Comment by nickvergessen** [comment]
> Nextcloud is technically behaving "correctly" here, I suppose?

The backend yes. The frontend needs to adapt and should only send the MKDIR/PUT request once the user had the chance to give the folder/file name

> Did the behavior change with NC 28?

Yes, its a regression from Files2vue migration, immediatelly creating the folder/file as "New folder" instead of taking user input.

**Comment by szaimen** [comment]
cc @nextcloud/files

**Comment by come-nc** [comment]
Even without the permission situation, using create+rename instead of just create is annoying, for instance it looks weird in activity:
![Screenshot_20240104_142413](https://github.com/nextcloud/server/assets/91878298/c0c687e0-3245-4f0f-996d-dc5f9a244d31)

And users could have flows running at folder creation also.

**Comment by szaimen** [comment]
Cc @nextcloud/server
