### ISSUE TITLE
[Bug]: Status emoji border inconsistent

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#41269]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![image](https://github.com/nextcloud/server/assets/1374172/99842b5a-0c2a-4c31-aeed-15885eb13be6)

### Steps to reproduce

1. Run 28 beta 1
2. Enable user status
3. Open status  modal

### Expected behavior

Solid design

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

cc @Antreesy @nickvergessen

**Comment by Antreesy** [comment]
Maybe we could get rid of this borders at this step? cc @nextcloud/designers  

![image](https://github.com/nextcloud/server/assets/93392545/d5484ada-254f-4163-8d93-0c5f77ed0f18)

**Comment by nickvergessen** [comment]
I guess adding it into the input like with talk breaks the label?
![grafik](https://github.com/nextcloud/server/assets/213943/fef9fa36-f737-4653-9207-2bd9f04d46f5)


Then I would go with your screenshot.

**Comment by marcoambrosini** [comment]
Nice idea @Antreesy, let's just make sure we have some padding between the button and the input
