### ISSUE TITLE
[Bug]: Supported MariaBD versions

### ISSUE THREAD

**Issue by tflidd** [nextcloud/server#41286]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The latest supported MariaDB version in the documentation is 10.6., however the current debian version already ships a newer version. There was a request in the documentation repo:
https://github.com/nextcloud/documentation/issues/10350

However, it is not clear which versions are supported, since there are some changes between the versions (https://github.com/nextcloud/documentation/issues/10350#issuecomment-1595766495).

### Steps to reproduce

1. check https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html

### Expected behavior

Include newer version into testing, so they can officially be supported. Currently, many just use a newer version and it probably runs (perhaps with problems?).

### Installation method

None

### Nextcloud Server version

25

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
At this time, only 10.6 is tested.
10.11 LTS will be tested since https://github.com/nextcloud/server/pull/41003/files is merged.

**Comment by susnux** [comment]
> Include newer version into testing, so they can officially be supported.

You can always try to use newer versions, but the versions from the [documentation](https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html) are the only versions we officially support any newer version might be considered but also requires testing so this is known and we will update the documentation as soon as we officially support that version.
