### ISSUE TITLE
[BITV]: Sharing tab: There is no indicator that "advanced settings" are open

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#41306]
There is no indicator that "advanced settings" are open which have to be a case. I would prefer a toggle button instead.

![Peek 2023-11-06 14-37](https://github.com/nextcloud/server/assets/6078378/f6347f2a-bdee-4a4e-a1e0-eca6fd7c2d20)

@nimishavijay @marcoambrosini could we replace a button with a toggle one?

The description and toggle state have to be visible for screen readers too.

**Comment by nimishavijay** [comment]
We could change the icon on the right to the [expand-more](https://fonts.google.com/icons?selected=Material%20Icons%3Aexpand_more%3A) icon when it is closed and the [expand-less](https://fonts.google.com/icons?selected=Material%20Icons%3Aexpand_less%3A) icon when it is open, would that be enough? :)

**Comment by marcoambrosini** [comment]
@nimishavijay shouldn't that icon be on the left btw?

**Comment by JuliaKirschenheuter** [comment]
Thank you!
I would like to know why a toggle button is wrong on that place? An icon won't solve all a11y issues. Semantically it is a toggle button. @nimishavijay please help. Thank you!

**Comment by susnux** [comment]
I would say the triangle icon needs to point down if open and right if closed. Also I would make the button full width to look like a heading and group the controlled section, like using background?

Something like this?
![Screenshot 2023-11-09 at 17-27-17 Files - Nextcloud](https://github.com/nextcloud/server/assets/1855448/24c26291-2a46-4c3e-a213-f8938b142bca)

**Comment by marcoambrosini** [comment]
@JuliaKirschenheuter could you please link the rule we're breaking, so we can better understand how to solve it? 
As far as I can see, this is an accordion element, and it shouldn't need any visual indicator, not even the icon. Semantically, it should be a regular button with aria-expanded="true" when the content is displayed, not a toggle. 

The problem with adding an outline to it, again, is that we would be confusing keyboard users as to where the focus really is (2 outlined elements at the same time on the screen)

**Comment by marcoambrosini** [comment]
@JuliaKirschenheuter could you link some documentation about why this should be a toggle? If this is the case, we'd have to change the pattern in many places in Nextcloud.
As far as UX goes, toggles don't seem to be recommended for progressively disclose content https://www.nngroup.com/articles/toggle-switch-guidelines/

As far as I can see, this pattern is an **[accordion](https://www.nngroup.com/articles/accordions-on-desktop/#Definition)**, so a button with aria-expanded="true/false" would suffice as a header. There's no need of any other visual indicators.

**Comment by susnux** [comment]
> so a button with aria-expanded="true | false" would suffice as a header. 

And the aria-controlled region tag.

**Comment by JuliaKirschenheuter** [comment]
> could you link some documentation about why this should be a toggle?

I thought that would be better on this place. But you are right, lets move with accordion 👍
