### ISSUE TITLE
[BITV]: Sharing tab: sticky buttons "update share" and "cancel" overlapping important interactive content

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#41304]
That should not be a case ;(

![Peek 2023-11-06 14-32](https://github.com/nextcloud/server/assets/6078378/60f76941-622a-4f85-9851-2568982a9647)

@nimishavijay @marcoambrosini how could we solve a problem?

**Comment by nimishavijay** [comment]
It is useful to not have to scroll all the way to the bottom to save our share settings, so I would vote for it to remain sticky. Would it be better if we added a background behind the buttons?

**Comment by marcoambrosini** [comment]
The buttons container needs to be below the scrolling container. So not `position: sticky` really just another block. I think flex layout column would be the best.

**Comment by JuliaKirschenheuter** [comment]
Dear @michaelnissenbaum 

would it be ok if there would be a white (or dark) background behind this 2 buttons? Then buttons won't overlap each other directly. Thank you!

**Comment by michaelnissenbaum** [comment]
Hi @JuliaKirschenheuter. Changing the background for the two buttons does not solve the problem we have. The two buttons overlap important content and functions behind them, forcing users to scroll constantly to access the content behind these buttons. I would suggest that the container with the two buttons starts where the container with other elements that need to be scrolled ends.

Best regards,
[Your Name]

**Comment by jancborchardt** [comment]
>  I would suggest that the container with the two buttons starts where the container with other elements that need to be scrolled ends.

@michaelnissenbaum our concern was that in this case people might not discover the very important confirmation action button on the bottom as it might be outside of the viewport and needs to be scrolled to. And the confirmation action is always important, whereas the content further down in the share tab gets decreasingly important in comparison.

**Comment by marcoambrosini** [comment]
I think @michaelnissenbaum and I are saying the same thing. @michaelnissenbaum do you mean this?

<img width="700" alt="Screenshot 2023-11-13 at 21 32 00" src="https://github.com/nextcloud/server/assets/26852655/55a2551a-7e96-47d3-8754-96be275f1fcc">

**Comment by michaelnissenbaum** [comment]
Hi @JuliaKirschenheuter. The solution is OK.
