### ISSUE TITLE
[Bug]: LDAP's second display name part is being forgotten

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#41316]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When configuring LDAP with a second display name part, this piece of information is displayed in brackets behind the main name. With enabled memcache, this portion is not cached however, and therefore not displayed in the future anymore. Disabling the distributed memcache shows the full display name again. It is not the LDAP-backend's cache responsible here, but somewhere down the line.

### Steps to reproduce

1. Enable LDAP with users and groups, and the second display name part

![Screenshot_20231106_222320](https://github.com/nextcloud/server/assets/2184312/bf08408b-5ec9-4df2-abae-e18283681078)

2. Go to the users page
3. Click on one of the groups and see the users being shown with their full display name (i.e. including the cyborg_xy in the brackets)

![Screenshot_20231106_223329](https://github.com/nextcloud/server/assets/2184312/3b2d58b8-8329-48f6-89b5-6f1874c73c3f)

4. Press F5, and see that the second part has vanished (i.e. the cyborg_xy in the brackets disappeared)

![Screenshot_20231106_223434](https://github.com/nextcloud/server/assets/2184312/c1fcf9e6-f3c5-4c01-a1dd-ad8562140e26)

### Expected behavior

The full display name is kept

### Installation method

None

### Nextcloud Server version

27

### Operating system

Other

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by blizzz** [comment]
cc @come-nc  in case you have a quick idea

**Comment by come-nc** [comment]
Nope, no idea I never used the feature. It’s so weird that it could be left out of displayname cache I’d expect the getter for the displayname to just include everything from the backend.

**Comment by blizzz** [comment]
I saw it only happenings with the groups, too, so there might be some connection with it as well.

**Comment by blizzz** [comment]
Also reproducing this on stable26 today (that's all by-catch from testing some other matter)

**Comment by blizzz** [comment]
Edge case in an edge case. This happens when using posixUsers where group memberships are referenced via gidNumber. The issue likely is there since the beginning of this feature, 2017.

In https://github.com/nextcloud/server/blob/master/apps/user_ldap/lib/Group_LDAP.php#L499 only few attributes are being read, but nevertheless the displayname is being generated out of the information later on.
