### ISSUE TITLE
Move reminder conditional rendering into action `enabled`

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#41336]
https://github.com/nextcloud/server/blob/32c1aebaae07b9b4d7e2dcdfca6b2cbd36a6cfc3/apps/files_reminders/src/actions/setReminderSuggestionActions.ts#L86

Since the presence of the action should be evaluated ideally on click instead of on script execution I think the `FileAction` enabled callback needs to be set to something like `() => Boolean(getDateTime(option.dateTimePreset))` to be more reactive

_Originally posted by @Pytal in https://github.com/nextcloud/server/pull/41010#discussion_r1385269899_

**Comment by Pytal** [comment]
From the code it looks like the enabled function is run on render of `FileEntryActions` or whenever computed `enabledActions()` dependencies change but not on click

As these actions are time-dependent is there a simple way we can make these run on click @skjnldsv? Or would we need some API changes and would it be worth it?

**Comment by skjnldsv** [comment]
> Or would we need some API changes and would it be worth it?

Let's not complicate things. API have received enough change and tuning, they are officially released and stable now.

The render side can be adjusted though. But if we start doing this on click, it means we risk slowing the render or worse, have entries suddenly disappear on user interaction, leading to confusion. I am not fond of this.
