### ISSUE TITLE
$HTTP_RAW_POST_DATA is deprecated

### ISSUE THREAD

**Issue by wohenbushuang** [nextcloud/server#4133]
### Steps to reproduce
1. I saw a lot in Logs of my demo site

### Server configuration
**Operating system**:
Ubuntu 12.04
**Web server:**
Apache2.2.22
**Database:**
MySQL
**PHP version:**
5.6.29

**Nextcloud version:** (see Nextcloud admin page)
11.0.2 (stable)
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh
**Where did you install Nextcloud from:**
Nextcloud website
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Error	PHP   	Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0
```
</details>

**Comment by LukasReschke** [comment]
> Error	PHP   	Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0

There's not much that we can do except telling you to do that 😉
