### ISSUE TITLE
Remove nearly unused jquery-ui

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#4134]
I tested by removing the jQuery-UI code (and our fixes) and the only thing I noticed that is only the autocomplete bar, that is not properly styled. We should maybe look into this, because we updated this library the last time nearly 3 years ago and don't use it anymore that often. Our dialog windows use something different, the LDAP assistant still works and the calendar also looks fine.

@nickvergessen @jancborchardt @rullzer Do you want to look into get rid of those unneeded 500 kB that are loaded on every page? (that's more than 25% of all bytes we transfer for an uncached page load on files)

**Comment by rullzer** [comment]
I'm all for it. our javascript libs are way to outdated so getting rid of some is an even better approach.

Also loading ~500kb is just bs for such a small thing.

I don't know enough about styling to fix it tough...

**Comment by jancborchardt** [comment]
Yes please. Most of the autocomplete bar I styled over for Nextcloud 11 or already 10 anyway. :)

Can you prepare a pull request so we can see what exactly happens, and adjust the issues?

Great initiative!

**Comment by MorrisJobke** [comment]
Damn - caching got me -.- After properly removing it, many things fell apart. I guess we need to do this in steps. Like the search relies on this somehow and the LDAP assistant as well. :/ So it doesn't seem to be that easy. Nevertheless - I want to get rid of this monster, because it's a huge pile of not upgradable code.

**Comment by MorrisJobke** [comment]
There are just too much cross dependencies. It's just untameable :/ I guess we need to live with if for now 😢

**Comment by jancborchardt** [comment]
Let’s keep this open though and just do it step by step? It’s technical debt after all.

**Comment by MorrisJobke** [comment]
> Let’s keep this open though and just do it step by step? It’s technical debt after all.

I tried some step by step, but we use it sadly at many places. From the LDAP accordion effect, to the autocomplete over to drag and drop behaviour of the files app. :/

**Comment by pixelipo** [comment]
timepicker and datepicker also use jquery-ui

**Comment by jancborchardt** [comment]
True, and otherwise we would need to reimplement these things.

While we should not overuse it, the existing use is valid. Closing hence.
