### ISSUE TITLE
Migrate remaining setup checks to new API

### ISSUE THREAD

**Issue by come-nc** [nextcloud/server#41364]
Remaining checks not using the new API:

- [x] isBruteforceThrottled (Your remote address was identified as "{remoteAddress}" and is bruteforce throttled at the moment slowing down the performance of various requests…) https://github.com/nextcloud/server/pull/41435
- [x] forwardedForHeadersWorking (The reverse proxy header configuration is incorrect, or you are accessing Nextcloud from a trusted proxy. If not, this is a security issue and can allow an attacker…) https://github.com/nextcloud/server/pull/41438
- [x] OpcacheSetupRecommendations (The PHP OPcache module is not properly configured…) https://github.com/nextcloud/server/pull/41547
- [x] missingIndexes (The database is missing some indexes…) https://github.com/nextcloud/server/pull/41460
- [x] missingPrimaryKeys (The database is missing some primary keys…) https://github.com/nextcloud/server/pull/41460
- [x] missingColumns (The database is missing some optional columns…) https://github.com/nextcloud/server/pull/41460
- [x] isImagickEnabled (The PHP module "imagick" is not enabled although the theming app is) https://github.com/nextcloud/server/pull/42177
- [x] imageMagickLacksSVGSupport (Module php-imagick in this instance has no SVG support) https://github.com/nextcloud/server/pull/42177
- [x] pendingBigIntConversionColumns (Some columns in the database are missing a conversion to big int…) https://github.com/nextcloud/server/pull/41468
- [x] isSqliteUsed (SQLite is currently being used as the backend database…) ->  https://github.com/nextcloud/server/pull/41535
- [x] isMemoryLimitSufficient https://github.com/nextcloud/server/pull/41086
- [x] appDirsWithDifferentOwner (Some app directories are owned by a different user than…) https://github.com/nextcloud/server/pull/42176
- [x] hasPassedCodeIntegrityCheck https://github.com/nextcloud/server/pull/41312
- [x] suggestedOverwriteCliURL (Please make sure to set the "overwrite.cli.url" option in your config.php file to the URL that your users mainly use to access this Nextcloud…) https://github.com/nextcloud/server/pull/42796
- [x] cronErrors (It was not possible to execute the cron job via CLI. The following technical errors have appeared:…) https://github.com/nextcloud/server/pull/42802
- [x] isUsedTlsLibOutdated https://github.com/nextcloud/server/pull/42807
- [x] isCorrectMemcachedPHPModuleInstalled (Memcached is configured as distributed cache, but the wrong PHP module "memcache" is installed…) https://github.com/nextcloud/server/pull/42812
- [x] isSettimelimitAvailable (The PHP function "set_time_limit" is not available…) https://github.com/nextcloud/server/pull/42814
- [x] areWebauthnExtensionsEnabled (The PHP modules "gmp" and/or "bcmath" are not enabled) https://github.com/nextcloud/server/pull/42829
- [x] isMysqlUsedWithoutUTF8MB4 (MySQL is used as database but does not support 4-byte characters…) https://github.com/nextcloud/server/pull/42836
- [x] isEnoughTempSpaceAvailableIfS3PrimaryStorageIsUsed https://github.com/nextcloud/server/pull/42839
- [x] temporaryDirectoryWritable https://github.com/nextcloud/server/pull/42839
- [x] isFairUseOfFreePushService https://github.com/nextcloud/server/pull/42939

Checks done on frontend side:
- [x] 'This instance is running in debug mode. Only enable this for local development and not in production environments.' https://github.com/nextcloud/server/pull/42942
- [x] https://github.com/nextcloud/server/pull/43607
- [x] Check whether the WOFF2 URLs works https://github.com/nextcloud/server/pull/43588
- [x] 'Your data directory and files are probably accessible from the internet. The .htaccess file is not working. It is strongly recommended that you configure your web server so that the data directory is no longer accessible, or move the data directory outside the web server document root.' (https://github.com/nextcloud/server/pull/43908)
- [x] 'You are accessing your instance over a secure connection, however your instance is generating insecure URLs. This most likely means that you are behind a reverse proxy and the overwrite config variables are not set correctly.' https://github.com/nextcloud/server/pull/43906
- [x] 'Accessing site insecurely via HTTP. You are strongly advised to set up your server to require HTTPS https://github.com/nextcloud/server/pull/43906
- [x] Check whether the .well-known URLs works ( https://github.com/nextcloud/server/pull/43939 )
- [x] Strict-Transport-Security header (https://github.com/nextcloud/server/pull/44067)
- [x] Other security headers (https://github.com/nextcloud/server/pull/44067)
- [x] Check whether the WebDAV connection works https://github.com/nextcloud/server/pull/44202

**Comment by susnux** [comment]
So now only the backports are missing?
