### ISSUE TITLE
Allow clearing reminders on files

### ISSUE THREAD

**Issue by Pytal** [nextcloud/server#41368]
The clear reminder action should be available if a reminder exists

On 27:
![image](https://github.com/nextcloud/server/assets/24800714/037b39fc-fff6-408d-a251-9057d8f21c78)

Not sure about implementation as FileAction `enabled()` is not awaitable

Previously a request was made to the backend to check if a reminder was set https://github.com/nextcloud/server/blob/6250c7d3a9a9e754f7e7c90afc0267f1d88cddfb/apps/files_reminders/src/main.ts#L57

**Comment by Pytal** [comment]
Any ideas on how we could go about this would be much appreciated @skjnldsv :)

**Comment by skjnldsv** [comment]
Just add a dedicated action ?

**Comment by XueSheng-GIT** [comment]
@Pytal I'm on NC 28.0.2 and once a reminder is set, I cannot even see whether a reminder is set or not (there is no such indication). Is this part and covered by this issue?

**Comment by Pytal** [comment]
No, that is not covered by this issue @XueSheng-GIT but I will do that in a followup

Tracking in https://github.com/nextcloud/server/issues/43540
