### ISSUE TITLE
Custom location for themes

### ISSUE THREAD

**Issue by jluttine** [nextcloud/server#4137]
Currently, `data/`, `apps/` and `assets/` directories can be given custom locations (`datadirectory`, `apps_paths` and `assetdirectory`). This is good because these locations are mutable, so one might want to keep them outside the actual Nextcloud installation. However, I couldn't find similar configuration for `themes/` directory. It says on the docs:

> The default location for themes is `nextcloud/themes/`.

But I couldn't find how to change this default. Perhaps, Nextcloud could support `themedirectory` config value (or, if necessary, an array of paths)?

**Comment by MorrisJobke** [comment]
@LukasReschke @nickvergessen @icewind1991 @rullzer @karlitschek Do we want this? Generally speaking I don't like to add yet another tweak able folder location. This only leads to more complex testing scenarios and possible corner cases

**Comment by jluttine** [comment]
I'll try to provide some motivation here.

I need to be able to have all the files and directories that are modified by the Nextcloud process itself elsewhere. That is `config/`, `data/`, `apps/`, `assets/` and `themes/`. For all others than `themes/` this is already possible. (I wouldn't mind having just one setting for such a directory which would be the parent directory of those instead of having a setting for each directory individually, but that's a different story, I guess.)

Keeping the Nextcloud installation immutable has some beneftis:

- It is possible to use the same installation for several instances by using different configuration for each instance.

- It simplifies managing strong permission security as the actual installation needs to have only read access and the mutable directories located elsewhere have write access for the Nextcloud/HTTP process.

- Upgrading Nextcloud is easy because one can just "switch" the Nextcloud directory old content to the new version content without needing to worry about, for instance, deleting files that no longer exist in the new version or accidentally overwriting some files modified by the Nextcloud instance.

I'm currently writing packaging/configuration for Nextcloud in NixOS which stores package installations as immutable. I want to use the nix package manager for managing the Nextcloud installation/upgrading, thus i need to be able to locate all mutable directories elsewhere.

**Comment by karlitschek** [comment]
Hmm. Well the theme directory is actually not changed by Nextcloud itself. So not sure  why this is a critical feature. Saying that: Making a config.php option that enabled to overwrite the theme folder shouldn't be super hard or risky. Pull requests welcome from my perspective :-)

**Comment by jluttine** [comment]
Yes, the directory isn't changed by Nextcloud itself, true, I was a bit sloppy in my wording. The problem is that it is "mutable": it is modified in order to use new themes, so it's not really part of the core Nextcloud package, which I'd like to keep immutable. Just wanted to know if you supported or were against having a customizable theme location (or if it happened to be possible already). Probably relatively easy task for someone (including me) to tackle and create a pull request.

**Comment by nickvergessen** [comment]
> It is possible to use the same installation for several instances by using different configuration for each instance.

You shouldn't really do that.....

Anyway, the request sounds fine to me and I tend to agree that there shouldn't be a lot wrong with it.

**Comment by MorrisJobke** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
