### ISSUE TITLE
[Bug]: Sharing with internal person, disabling the end date shows up as if it was still enabled

### ISSUE THREAD

**Issue by JMoVS** [nextcloud/server#41376]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When sharing a file or a folder with a colleague, if I want ti disable the end date, the checkbox doesn't get unchecked and instead only the date replaced with "TT.MM.JJJJ"

### Steps to reproduce

1. Select a file to share
2. try to unselect the sharing end date
Observe:
![grafik](https://github.com/nextcloud/server/assets/7354506/0df275f0-b75b-4e78-bbdf-cefc59f4d4b3)

### Expected behavior

It should just unselect the checkbox and show the blank box

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by linuxrrze** [comment]
Same behaviour with my installation:

Nextcloud Server version
27.1.3

Operating system
Ubuntu 22.04 (x86_64)

PHP engine version
8.1.2 (FPM)

Web server
Apache 2.4.52

Database engine version
Postgres

Is this bug present after an update or on a fresh install?
Did not try

Are you using the Nextcloud Server Encryption module?
No

What user-backends are you using?
 LDAP/ Active Directory

**Comment by simon-d-s** [comment]
Same here using Nextcloud Server version 27.1.3.

This issue prevents internal sharing of more than one day, when setting an end date for external shares is enforced in the settings.

**Comment by szaimen** [comment]
Cc @Fenn-CS

**Comment by Fenn-CS** [comment]
Solved via : https://github.com/nextcloud/server/pull/40928 for 27.1.4
