### ISSUE TITLE
Why not update available after 25.0.13?

### ISSUE THREAD

**Issue by JB1985** [nextcloud/server#41394]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nextcloud Updater - version: v25.0.11-5-g06c1bad

Current version is 25.0.13.

No update available.

### Steps to reproduce

1. config.php -> 'updater.release.channel' => 'stable',
2. try to update
3. No update available

### Expected behavior

I expect to update to version 26 after Nextcloud 25 becomes EOF.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment]
A common reason is that the PHP version is incompatible. 
PHP 8.0 should be enough for Nextcloud 26.

> Nextcloud Updater - version: v25.0.11-5-g06c1bad

This looks like the CLI updater. If multiple PHP versions are installed, it's possible that the default for the CLI is different from the web server. You can check that with php -v.

**Comment by JB1985** [comment]
You´re right! PHP CLI 7.4 is active. Change to 8.0 works!

**Comment by DigitalForceEU** [comment]
Had the same problem. Problem was fixed after (re)moving data/updater-ocz3923112ac

**Comment by Cristy94** [comment]
I am also stuck on the same version.

If I upgrade to PHP 8.2, NC doesn't support it.
If I upgrade to PHP 8.0, the dashboard crashes, and can't update.
If I stay on PHP 7.4, it says it's up-to-date, and I can't upgrade to NC 26 or higher.

**Comment by sbley** [comment]
I wasn't able to update from 25 to 26 for similar reasons. The update check always returned "No updates available".

I could fix this by running the occ commands with `php80` instead of `php` (which pointed to 7.4, configured by my hoster). Note that `php81` did not work either. It had to be 8.0.

**Comment by josuedugg** [comment]
I had the same problem and this is how I solved:
1) Install/enable php 8.1 
2) Disable or uninstall php 7.X from your server
3) systemctl restart apache2
4) Execute with the owner (usually www-data) :
sudo -u www-data .../php/8.1/bin/php updater/updater.phar
