### ISSUE TITLE
New sharing flow design

### ISSUE THREAD

**Issue by Ornanovitch** [nextcloud/server#41397]
Since the work done for #40438, I think some little design questions remain (I'm on NC 27.1.3):

![screen](https://github.com/nextcloud/server/assets/34077099/b9522219-8d75-4d06-96d6-e92a23b0ace2)

1. IMHO the `checkbox-radio-switch` list for quick permissions uses counterintuitive colors: I would expect something more immediately understandable and consistent on the first look. That could be done by setting `background-color: var(--color-background-dark)` to all `checkbox-radio-switch__label` elements, and by setting `background-color: var(--color-primary-element-light)` to the checked label (with the same border as the other elements).

2. I thought the delete share button was supposed to be moved to the bottom, as it seemed to be said in https://github.com/nextcloud/server/pull/40629#issuecomment-1738896950. Because it's weird to see it as such a dominating "first possible action" above cancel and update, which are more common

3. On dark mode, the delete share button has a white background. Is this on purpose? It seems really strange.

How it could look (**except for the Delete share button background color, that I accidentally removed in this mock-up**):

![screen2](https://github.com/nextcloud/server/assets/34077099/9375f9e7-87b2-481f-b11f-c70098c6aa13)

4. **edit** I realize there is another potential issue: the `advanced control` button is preceded by an arrow down icon, which can be confusing, because it can lead to think that the last three buttons (cancel, update, delete) _are_ the advanced control. It would be wise to replace it by an arrow right icon when the settings are hided.

**Comment by Ornanovitch** [comment]
Hey @Fenn-CS @jancborchardt :) WDYT about this proposal?

**Comment by jancborchardt** [comment]
Hi @Ornanovitch, we recently had to do some changes for accessibility which cover your suggestions. :)
- The "Delete share" button has been moved inside the scroll container and its presence was reduced to tertiary button (no background) https://github.com/nextcloud/server/pull/41489
- The style of both the main sidebar tabs and the share toggle has been adjusted: https://github.com/nextcloud-libraries/nextcloud-vue/pull/4823

So I would consider this fixed. What do you think?

**Comment by Ornanovitch** [comment]
Thanks for pointing me those improvements! Indeed there seems to be a lot of little changes. So I guess all of those stuff are going to be delivered with NC 28 and nextcloud-vue 8? In that case this issue is soon to be outdated, so I'm going to close and to wait and see if I still have suggestions later! Thanks again :)
