### ISSUE TITLE
[Bug]: Activity of calendars, events and addressbook miss information about the affected collection

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#41410]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Creating a calendar, changing an event and changing address books should create activity that say which calendar/address book changed.

![image](https://github.com/nextcloud/server/assets/1374172/09f98966-b79a-4050-89a0-aadebc03040d)

### Steps to reproduce

1. Create a calendar
2. Look at activities

### Expected behavior

Shows the new calendar name

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by st3iny** [comment]
Calendar fix at: https://github.com/nextcloud/activity/pull/1411
Address book fix at: https://github.com/nextcloud/activity/pull/1412

**Comment by st3iny** [comment]
Activities on creating new calendars is also fixed by the first PR.
