### ISSUE TITLE
[Bug]: move or copy operation fails

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/server#41414]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

move or copy operation fails right from the beginning when clicking on the action from the three dot menu next to a file.
28.0.0 beta 2 c.nc.c

### Steps to reproduce

1.
2.
3.

### Expected behavior

file browser should appear to ask where copy/move the selected file/folder

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by blizzz** [comment]
I see similar. The only outgoing request seems to not satisfy CSP:

![Screenshot_20231113_183331](https://github.com/nextcloud/server/assets/2184312/98a5285d-295c-4d4c-9b7e-91a396e30e64)

**Comment by blizzz** [comment]
cc @susnux

**Comment by blizzz** [comment]
If that helps: The error is triggered here https://github.com/nextcloud-libraries/nextcloud-dialogs/blob/318d22cb3b2fa9004c822d8c96baad6df280886e/lib/filepicker-builder.ts#L78-L106 as it is being called from and everything before executes https://github.com/nextcloud/server/blob/master/apps/files/src/actions/moveOrCopyAction.ts#L205 . 

https://github.com/nextcloud/server/blob/master/apps/files/src/actions/moveOrCopyAction.ts#L156 is never reached.

**Comment by blizzz** [comment]
In master as of today, the file picker opens, but then the copy method still errors with "Cancelled move or copy operation" on web UI. Copying works via  the desktop client.

**Comment by susnux** [comment]
Can have a look tomorrow
