### ISSUE TITLE
[Bug]: Unneeded vertical scrollbar appears in sharing sidebar

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#41421]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Unneeded vertical scrollbar appears in sharing sidebar

![Peek 2023-11-13 13-24](https://github.com/nextcloud/server/assets/6078378/542e5368-67b8-4f04-ad9f-1211f80f5b4b)

### Steps to reproduce

1. Open details for any file or folder
2. Open sharing Tab
3. Click to "share link"
4. Click to "customize link" inside the action menu
5. See that a unneeded vertical scrollbar appears

### Expected behavior

Unneeded vertical scrollbar won't appear

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment]
cc @Fenn-CS
