### ISSUE TITLE
new search modal completely broken on mobile

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#41422]
See 
![image](https://github.com/nextcloud/server/assets/42591237/ae7ea2f7-b913-4320-9b30-3c8e2f66f3f6)

cc @Fenn-CS @marcoambrosini @JuliaKirschenheuter

**Comment by jancborchardt** [comment]
Closing this as it is tracked in the https://github.com/nextcloud/server/issues/41381 already :)

**Comment by Fenn-CS** [comment]
After a re-base I am realizing some updates to the modal component itself has resolved the responsiveness issue for master

![Screenshot from 2023-12-22 18-18-21](https://github.com/nextcloud/server/assets/14317775/0de40d2d-fd6a-42b5-b586-20f856aeb889)

@susnux please can you confirm?

**Comment by susnux** [comment]
@Fenn-CS only for master, stable28 is still broken.

I think it will be fixed with https://github.com/nextcloud/server/pull/42776

**Comment by Fenn-CS** [comment]
Now fixed, see https://github.com/nextcloud/server/pull/42184
