### ISSUE TITLE
[Bug]: Unable to copy/move a file on web

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#41449]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I can not move a simple text file. A toast pops up and says "Cancelled move or copy operation" before I even get a file picker to select a destination.

![image](https://github.com/nextcloud/server/assets/1374172/5f787f48-0881-462e-8806-6f8da5942f35)

### Steps to reproduce

1. Open an existing directory
2. Go to a file
3. Open the actions menu
4. Click *Move or copy*

### Expected behavior

File picker shows, file can be moved/copied.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by SystemKeeper** [comment]
Same as https://github.com/nextcloud/server/issues/41414 ?

**Comment by ChristophWurst** [comment]
The ticket doesn't say anything about the toast but I'm fine closing if you think it's the same

**Comment by blizzz** [comment]
I think it is not mentioned there indeed, but definitely happens.
