### ISSUE TITLE
defect file-list with unicode on samba-share 

### ISSUE THREAD

**Issue by sh-dvl** [nextcloud/server#4144]
### Steps to reproduce
1. configure a external-storage on a samba-share
2. from real-client, not nextcloud: create a directory with following sub-directories: 
AAAA
BBBB
CÄCC
DDDD
EEÖE
FFFF
GGGG
HHHH
3. try to access the directory with the sub-dirs via nextcloud

### Expected behaviour
normal File/directory-List

### Actual behaviour
each unicode-char in a filename leads to a cut-off of the current name and a later entry in directory will be appended at this position:

AAAA
BBBB
DDDD
EE C HHHH
FFFF
GGGG

### Server configuration
**Operating system**:
linux wheezy 32bit-container
**Web server:**
lighttpd
**Database:**
mysql
**PHP version:**
5.6
**Nextcloud version:** (see Nextcloud admin page)
11.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh
**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-11.0.2.zip
**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - admin_notifications: 1.0.0
  - bookmarks: 0.9.1
  - checksum: 0.3.3
  - comments: 1.1.0
  - dav: 1.1.1
  - defaultgroup: 0.2.0
  - direct_menu: 0.10.0
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_clipboard: 0.5.0
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - rainloop: 4.28.1
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - user_external: 0.4
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - firstrunwizard
  - nextcloud_announcements
  - ownpad
  - survey_client
  - updatenotification
  - user_ldap
  - user_saml

**The content of config/config.php:**
{
    "system": {
        "instanceid": "obcaqsdxsjbc",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xchange:8020",
            "sh-xchange:8020",
            "info:8020",
            "sh-info:8020",
        ],
        "datadirectory": "\/import\/data\/xchange",
        "overwrite.cli.url": "http:\/\/xchange:8020",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "has_internet_connection": false,
        "customclient_desktop": false,
        "customclient_android": false,
        "customclient_ios": false,
        "enable_previews": true,
        "preview_max_x": 1024,
        "preview_max_y": 1024,
        "preview_max_scale_factor": 4,
        "preview_max_filesize_image": 2,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF"
        ],
        "user_backends": [
            {
                "class": "OC_User",
                "arguments": []
            },
            {
                "class": "OC_User_SMB",
                "arguments": [
                    "filesrv"
                ]
            }
        ],
        "default_language": "de",
        "defaultapp": "files",
        "knowledgebaseenabled": false,
        "auth.bruteforce.protection.enabled": true,
        "skeletondirectory": "",
        "mail_domain": "XXXXXXXXXXXXX",
        "mail_from_address": "xchange",
        "mail_smtphost": "127.0.0.1",
        "mail_smtpport": 25,
        "mail_smtpsecure": "",
        "trashbin_retention_obligation": "disabled",
        "versions_retention_obligation": "disabled",
        "appcodechecker": true,
        "updatechecker": false,
        "log_type": "file",
        "logfile": "\/var\/log\/lighttpd\/nextcloud.log",
        "loglevel": 1,
        "syslog_tag": "nextcloud",
        "appstoreenabled": false,
        "apps_paths": [
            {
                "path": "\/import\/web\/xchange\/apps",
                "url": "\/apps",
                "writable": true
            },
            {
                "path": "\/import\/web\/xchange\/apps-ext",
                "url": "\/apps-ext",
                "writable": true
            }
        ],
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
**Are you using external storage, if yes which one:** local/smb/sftp/...
smb
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:**
firefox 38 and 46
**Operating system:**
linux and windows
#### Web server error log
nothing relevant
#### Nextcloud log (data/nextcloud.log)
nothing relevant
#### Browser log
nothing seen

**Comment by MorrisJobke** [comment]
cc @icewind1991 Didn't you fix that like half a year ago?

**Comment by sh-dvl** [comment]
ok, problem is _not_ in nextcloud.
because smbclient-php does not work (and has been dropped), nextcloud accesses the share via calls of smbclient.
unfortunately it's default-config in wheezy (and maybe others) does say, that encoding is ascii.
calling smbclient on shell shows same garbage.
adding a line "display charset = UTF8" to the global-section of /etc/samba/smb.conf solves the problem.
