### ISSUE TITLE
[Bug]: Wrong focus and open menu after clicking *New folder*

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#41456]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Clicking *New folder* in a folder should close the actions menu and focus the input. Instead I get this:

![image](https://github.com/nextcloud/server/assets/1374172/8f4677fa-0f70-4d27-b06f-694f660abd35)

### Steps to reproduce

1. Open Files
2. Click *+*
3. Click *New folder*

### Expected behavior

menu closes, folder name input is focused

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by juliushaertl** [comment]
@JuliaKirschenheuter Sounds like this could be relevant for the review?

**Comment by szaimen** [comment]
So IIRC, the close-after-click is set to true: https://github.com/nextcloud-libraries/nextcloud-upload/blob/aff1a28132d2218f25052b599fb2a1fe5460f881/lib/components/UploadPicker.vue#L27-L38 So I am out of ideas why it doesnt seem to work. Maybe the property is broken in nextcloud/vue?
cc @nextcloud/server-frontend

**Comment by schiessle** [comment]
I want to add, that we also don't scroll to the place where the file listing entry was created. if you have files/folders it looks like nothing happened after clicking in "new folder", unless you scroll down and find the input field somewhere in the file listing.

**Comment by skjnldsv** [comment]
I think it's fixed now
