### ISSUE TITLE
[Bug]: shared file link opens folder, not file

### ISSUE THREAD

**Issue by gerbrent** [nextcloud/server#41467]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

opening a shared internal link that is pointing to a file, i.e. https://mynextcloud.url/f/1234567 in a browser opens the folder, not the file itself.

This is seen as a regression.

### Steps to reproduce

1. copy/share/receive an internal link to a file eg. https://mynextcloud.url/f/1234567
2. click on / browse to said link in browser
3. the folder that contains the file is indeed opened, but the file itself is not opened in eg. Files editor for .md

### Expected behavior

expecting the file that was linked to be opened in Files editor for .md, etc.

### Installation method

None

### Nextcloud Server version

28.0.0 beta 3

### Operating system

Other

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Nextcloud Server version 28.0.0 beta 2
Firefox & Chromium 
openSUSE Tumbleweed

**Comment by AndyScherzinger** [comment]
https://github.com/nextcloud/server/pull/27102
