### ISSUE TITLE
[BITV]: Move delete share button into the scrolling container

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#41463]
Just one detail @juliushaertl – the "Delete share" button is not supposed to be sticky, but the last button in the content area. As proposed by @JuliaKirschenheuter and approved by Michael in https://github.com/nextcloud/server/issues/41304#issuecomment-1808090609

_Originally posted by @jancborchardt in https://github.com/nextcloud/server/issues/41444#issuecomment-1810138145_

**Comment by juliushaertl** [comment]
@jancborchardt @JuliaKirschenheuter Is this critical for the review or just polishing?

**Comment by jancborchardt** [comment]
@juliushaertl don't know if it's critical for the review – it's a regression of behavior though, and as @AndyScherzinger also noted on mobile leads to a very small or overlapped scroll area.

**Comment by JuliaKirschenheuter** [comment]
>  and as @AndyScherzinger also noted on mobile leads to a very small or overlapped scroll area.

Yes, critical

**Comment by JuliaKirschenheuter** [comment]
> Viewport: 1280px + 400% zoom

will be moved to another issue

**Comment by ShGKme** [comment]
> Viewport: 1280px + 400% zoom

Is there a problem? The requirement for 400% Zoom and 320px viewport was only about `width`, not `height`

**Comment by JuliaKirschenheuter** [comment]
> will be moved to another issue

https://github.com/nextcloud/server/issues/41504
