### ISSUE TITLE
Search only in a selected folder filter

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#41476]
Quite often it is necessary to perform searching some file **only** in a local (selected) folder (optionally, recursive search in all subfolders).
Please, add the proper filter to the unified search menu, eg

![image](https://github.com/nextcloud/server/assets/5199030/9269ec38-ed15-4a3e-be14-4ffd604775de)

This filter should **also** influence on fulltextsearch results, so only the results from te local folder to be shown.

Optionally, with the recursive search parameter.

**Comment by skjnldsv** [comment]
With Nextcloud 30 you can now filter with a lot of different options on the directory you want. :)
That should give you enough of flexibility already :tada:
