### ISSUE TITLE
Manually arrange files

### ISSUE THREAD

**Issue by andre-paulo98** [nextcloud/server#4148]
I've been looking for something like this for some time now, without any success.
What i'm suggesting is add a custom file order on the "dashboard" without it beeing alphabetic, size or last modified.
All files that get uploaded after the last time you re-arranged the files, it would appear on the top or in the end, depending on user's preferences.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers for triaging this

**Comment by jancborchardt** [comment]
@andre-paulo98 what’s your use-case here, what would you use it for?

**Comment by andre-paulo98** [comment]
for example:
Lets say you have a shared folder and you would like to customize the order of the files. You usually go after the name but it gets "boring" manually changing the name of all files so you get the order that you want.
Here is an example: ![example](http://i.imgur.com/ufcXMME.gif)
It doesn't need to be "enabled" on all folders but on shared ones would be nice 😃

**Comment by MorrisJobke** [comment]
@andre-paulo98 We know what you're mean with reordering, but could you explain, why you want to change the order. Maybe a different way of sorting fixes your problem and it doesn't need a complex feature like that

**Comment by MorrisJobke** [comment]
I still don't see the use case for this. I will close this ticket here now. We are happy to continue discussing this to understand the reason for this.

**Comment by te-online** [comment]
I understand it like this: You have a specific order of folders in mind that is shaped by the way you (and others) work with the folders. One example: You are working on a scientific paper with colleagues. The first step might be reading available sources on the topic, after that you might collect texts from all collaborators, then collect diagrams and graphics that will be included and finally created a final merged paper version. Your folder structure then could look like this:

My crazy paper
∟ Literature
∟ Partial Texts
∟ Graphics
∟ Layout
∟ Final Version

This order can't be achieved by *alphabetic* or *last changed* order. In any ordinary file explorer you would work around this by appending something in front of the folder names, like so:

My crazy paper
∟ 1-Literature
∟ 2-Partial Texts
∟ 3-Graphics
∟ 4-Layout
∟ 5-Final Version

Theoretically, it could be really cool to be able to just custom order the folders for a case like this.
In reality, I think, you have to add up the hours of renaming a lot of folders, until you reach the amount of development-hours a user-friendly implementation of this would take.

However, if @andre-paulo98 or anyone else wants to get into drag & drop javascript and ordering of folder lists, this is a good idea for a separate **helper app**, I would say 😊 

*Disclaimer: I don't know if anyone would collaborate on a paper like this. My description is just for demonstration purposes* 😉

**Comment by jancborchardt** [comment]
A big problem here is that this sorting would only be available in the web interface. Or at most also in the Android and iOS app, should we choose to implement it.

However, the killer is that _no_ desktop environment whatsoever supports custom ordering. Hence you will be confused if it’s not ordered the way you set it in the web interface. And that’s why we should not implement this.
