### ISSUE TITLE
Gzip WebDAV responce

### ISSUE THREAD

**Issue by vitr-nindeco** [nextcloud/server#41494]
I know that nginx gzip module doesn't compressing body if response status code not in [200, 403, 404]. DAV responses use codes 207 etc. It's exist way to compress DAV responses if client send it in header? (Accept-Encoding: gzip)

**Comment by kesselb** [comment]
> I know that nginx gzip module doesn't compressing body

Where do you have this information from?
 https://nginx.org/en/docs/http/ngx_http_gzip_module.html does not mention it. 

Your ticket is neither a bug report nor a feature request, and therefore should go to https://help.nextcloud.com/.
