### ISSUE TITLE
Moveing file/folder selection

### ISSUE THREAD

**Issue by cal940** [nextcloud/server#4149]
![](http://i.imgur.com/hEgPAel.jpg)

In nextcloud 9 there was a  „move“ button. In NC 11 there isn't.

**Comment by MorrisJobke** [comment]
This could not be the case, because we added the feature in NC11: #1754

Anyway this would be nice to have.

cc @icewind1991 @nextcloud/javascript

**Comment by BloodyIron** [comment]
This was a feature of the previous OC/NC app that added the move functionality. Moving single items around is really painful when you can have hundreds of files you want to move. I for one want to see this functionality re-added in some way, to move/cut+paste or equivalent of the selected items.

**Comment by dienteperro** [comment]
Yes, it would be really comfy to move several items at once!

**Comment by ChristophWurst** [comment]
> Yes, it would be really comfy to move several items at once! This is the same issue as in #2779

Right, this ticket is a duplicate, hence I'm closing it now. Let's continue in #2779 :)
