### ISSUE TITLE
[Bug] [NC 28b3]: Translation login window

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#41499]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Text strings for the login window are only displayed in English.

![obraz](https://github.com/nextcloud/server/assets/47037905/a8cdbe8a-59fc-4a00-80be-2d7b66b2ccd8)

Text strings in Transifex translated.
The translation is in l10n files.

### Steps to reproduce

1. Start your browser in a language other than English.
2. Start Nextcloud.

### Expected behavior

Displaying the login window in your native language.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by sorbaugh** [comment]
Fixed with https://github.com/nextcloud/server/pull/42100
