### ISSUE TITLE
Loading bar by clicking at a certian point of a link with MS Edge

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/server#4151]
### Steps to reproduce
1. Use demo.nextcloud.com
2. Open the right panel and click on the icon instead of the text
3. The link is not open but the loading bar is spinning

![image](https://cloud.githubusercontent.com/assets/1473674/24471906/002f9b32-14c4-11e7-9e0e-afb5393d7914.png)

If you click on the Icon the loading bar appears. If you click on the text, the page is loading.

### Expected behaviour
Open the page

### Actual behaviour
nothing, loading bar is displayed

### Server configuration
**Operating system**:
Debian 16.10

**Web server:**
Apache 2.4

**Database:**
MySQL 5.7

**PHP version:**
7.0.14

**Nextcloud version:** (see Nextcloud admin page)
11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Where did you install Nextcloud from:**
NextCloud.com

**Browser**
Microsoft Edge on Windows 10

With Firefox I can't reproduce it

**Comment by MorrisJobke** [comment]
cc @nextcloud/javascript @juliushaertl

**Comment by Dennis1993** [comment]
I tested that with 12.0.4 and Edge. The problem is solved!
