### ISSUE TITLE
Mark calendar read-only

### ISSUE THREAD

**Issue by schaarsc** [nextcloud/server#4152]
to avoid adding events to the wrong calendar by accident I'd like to suggest an option to mark a calendar read-only. 

Use case:
  - standard: read/write 
  - holidays: read-only

in this example, once calendar is synced to a device, "std events" and holidays are displayed but it is not possible to add events to the read-only holidays calendar.

**Comment by MorrisJobke** [comment]
@georgehrke @rullzer Does this need to be done in the server or in the calendar app?

**Comment by skjnldsv** [comment]
Unfortunately the described feature is not really high on our priority list. But this doesn't mean that we don't like the idea or that we are against this feature per se. Quite the opposite! :slightly_smiling_face: 

There are many way to get new features in Nextcloud:

1. The easiest and most straight forward way (especially here at Github): pull request.
Nextcloud is completely Free Software, this means that everyone is welcome to join and to contribute. If you or anyone else want to work on this feature, this would be great! We appreciate every pull request, and we are definitely able to help in case of questions, reviews, etc.

2. Another option is creating a bounty at [Bountysource](https://www.bountysource.com/search?query=nextcloud), although just putting money on an issue doesn't guarantee that someone picks it up (in time). But in general it is a nice way to support the huge Nextcloud community. In case of a Nextcloud GmbH employee picks up the bounty we will give it back to the community by putting the money back on other bounties to make sure all bounties benefit the Nextcloud community.

3. We have a [category for Freelancers in our form](https://help.nextcloud.com/c/nextcloud-freelancing). Another option would be to post an offer there and try to find a freelancer who want to work on it.

4. The most direct way for a company or organization to get the issue addressed is to get a [Enterprise Subscription](https://nextcloud.com/pricing/). This includes everything to enable you to run Nextcloud in a productive environment with guaranteed SLA's and more. The Enterprise Subscription also includes optional professional services such as custom development. Feel free to [reach out to us](https://nextcloud.com/contact/). We are happy to explore the possibilities how to make Nextcloud fit your needs.

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
