### ISSUE TITLE
[Bug]: File modified date is in very far future

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#41537]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![image](https://github.com/nextcloud/server/assets/1374172/927717ec-dfea-4611-8129-912c50713d4e)

this showed on my test instance the last few weeks. Not sure how I ended up there.

```xml
<d:propstat>
      <d:prop>
        <d:getcontentlength>8651588</d:getcontentlength>
        <d:getcontenttype>application/octet-stream</d:getcontenttype>
        <d:getetag>"086d1af85296de0937ce900fcc62f5fc"</d:getetag>
        <d:getlastmodified>Thu, 10 May 2446 22:38:55 GMT</d:getlastmodified>
        <d:resourcetype/>
        <nc:has-preview>false</nc:has-preview>
        <nc:mount-type/>
        <nc:share-attributes>[]</nc:share-attributes>
        <oc:comments-unread>0</oc:comments-unread>
        <oc:favorite>0</oc:favorite>
        <oc:fileid>36291</oc:fileid>
        <oc:owner-display-name>Christoph Wurst</oc:owner-display-name>
        <oc:owner-id>admin</oc:owner-id>
        <oc:permissions>RGDNVW</oc:permissions>
        <oc:share-types/>
        <oc:size>8651588</oc:size>
        <x1:share-permissions xmlns:x1="http://open-collaboration-services.org/ns">19</x1:share-permissions>
        <nc:hidden>false</nc:hidden>
        <nc:system-tags/>
      </d:prop>
      <d:status>HTTP/1.1 200 OK</d:status>
    </d:propstat>
``` 

### Steps to reproduce

1. Upload files, I guess

### Expected behavior

Reasonable modified time **in the past**.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ChristophWurst** [comment]
filecache mtime and storage_mtime are 15032385535

**Comment by susnux** [comment]
Looks like JS timetamp is somewhere used (which is ms instead of seconds)

**Comment by ChristophWurst** [comment]
15032385 is not a reasonable timestamp for my files either

**Comment by artonge** [comment]
Should have been fixed by https://github.com/nextcloud-libraries/nextcloud-upload/pull/946

**Comment by ChristophWurst** [comment]
Thanks a lot for checking!
