### ISSUE TITLE
[Bug]: User status automation sets status to *Away* despite activity

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#41548]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

https://github.com/nextcloud/server/issues/31177 should set user status to busy/in a meeting when there is an event and leave it untouched otherwise. But the online status is now always *Away* outside of events.

### Steps to reproduce

0. Ensure the test user has calendars but opening the Calendar app once
1. Ensure the user has an email address set
2. Have no ongoing events
3. Set personal availability so you are current out of office
4. Clear oc_user_status
5. Reload the page twice

### Expected behavior

Show as *Online*

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by miaulalala** [comment]
\OCA\UserStatus\Listener\UserLiveStatusListener::handle needs to be modified to update just the status to ONLINE if the user is online.

**Comment by nickvergessen** [comment]
Btw for me the availability DND also does not happen anymore. Not sure if that is the same cause, my assumption from the DB is yes:

```
MariaDB [oc]> SELECT * FROM oc_user_status WHERE user_id IN ('myname', '_myname');
+-------+---------+---------+------------------+-----------------+--------------+-------------+--------------------+----------+-----------+--------------------------+
| id    | user_id | status  | status_timestamp | is_user_defined | message_id   | custom_icon | custom_message     | clear_at | is_backup | status_message_timestamp |
+-------+---------+---------+------------------+-----------------+--------------+-------------+--------------------+----------+-----------+--------------------------+
| 63140 | _myname | offline |       1700113209 |               0 | NULL         | ?️           | Dragons are back   |     NULL |         1 |               1700112273 |
| 63882 | myname  | away    |       1700199400 |               1 | availability | NULL        |                    |     NULL |         0 |                        0 |
+-------+---------+---------+------------------+-----------------+--------------+-------------+--------------------+----------+-----------+--------------------------+
``

**Comment by ChristophWurst** [comment]
Cleared my local status and set a conditional breakpoint for status=away. First trigger was at https://github.com/nextcloud/server/blob/158aedb549b253b0b8a84a7c68c0d7bca9e7be54/apps/user_status/lib/Service/StatusService.php#L166.

**Comment by ChristophWurst** [comment]
> Btw for me the availability DND also does not happen anymore

It is related. https://github.com/nextcloud/server/pull/40615 set the status and creates a backup, but never reverts. There can only be one backup. If the availability DND automation tries to backup as well it fails.

https://github.com/nextcloud/server/pull/41570 improves this bit so that calendar automation does revert again, so there is a backup slot for the availability DND automation. There is still a conflict if a user has an event happening into or inside unavailable times. Then either one or the other automation wins.

@nickvergessen says this problem was also there for calls. That is why the availability DND automation resets call automation. We can do the same if availability DND is of higher priority than calendar automation.

**Comment by ChristophWurst** [comment]
The *Away* bug is not reproducible if a user has no email set because `\OCA\DAV\CalDAV\Status\StatusService::processCalendarAvailability` has an early return for that condition.

**Comment by nickvergessen** [comment]
> Same thing happens if the user has no calendars.

This was it for me.

Now I can reproduce locally and your PR fixes this angle at least.
