### ISSUE TITLE
Statistics for group members

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#4155]
It should be possible as admin/subadmin to get following information of all group members via API:

* [x] assigned quota, used quota
* [x] is it an active user?
* [x] number of shared links by week, month, 6 month
* [x] date of invitation (user creation)
* [x] date of last login

cc @oparoz @daita @icewind1991 

Should we add this to the provisioning API? Maybe @rullzer and @schiessle have some feedback for this? Go would also be to collect this information for a whole group with one request, otherwise it could be the case that we need to send 100 requests if the group has 100 members, or what do you think?

**Comment by rullzer** [comment]
> number of shared links by week, month, 6 month

Currently there is no API to efficiently fetch this.

**Comment by icewind1991** [comment]
@rullzer can we add a "share time" collumn for 12?

**Comment by icewind1991** [comment]
> date of invitation (user creation)

Do we know what system will be used for user managements? (internal db, ldap, ...)

**Comment by rullzer** [comment]
@icewind1991 we have a share time already. But the issue is also what do you want

1. A current shapshot of the state
2. a real list of all the shares in the last X days/months/years/millenia because then we also need to keep the old shares around.

**Comment by MorrisJobke** [comment]
It looks like internal db as user system

**Comment by icewind1991** [comment]
@rullzer audit log maybe?

**Comment by icewind1991** [comment]
WIP app with the api is here: https://github.com/icewind1991/userinfo

**Comment by oparoz** [comment]
@daita - Are you taking care of the last 2 items?

**Comment by daita** [comment]
for the Shares, yes. But it will be integrated to the Apswhisperer app. 
Also, haven't seen anything about Date Of Invitation, but I guess I can take care of it too.

**Comment by MorrisJobke** [comment]
> is it an active user?

I guess we mixed something up here: Currently we use the enabled/disabled flag, but I guess it is more like "Was the user active in the last 30 days". I guess this should not be too hard to extract.

**Comment by icewind1991** [comment]
We have a last login, so we could just base it of that

**Comment by MorrisJobke** [comment]
> We have a last login, so we could just base it of that

Exactly - this was also my idea.

**Comment by MorrisJobke** [comment]
> number of shared links by week, month, 6 month
>  date of invitation (user creation)

Ping @icewind1991 @daita
