### ISSUE TITLE
[NC 28b3] Edit name of a file or folder

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#41550]
When renaming a file or folder, you cannot select part of the name. The entire name is automatically selected.

![obraz](https://github.com/nextcloud/server/assets/47037905/adb9cff4-f846-45e7-8768-afc4ca2a3c2a)

I suggest that you can edit the name by selecting part of the name and positioning the cursor between the letters.
This will make it easier to edit the name and maintain a certain standard.

App:
Nextcloud 28b3
Firefox 119.0.1

**Comment by joshtrichards** [comment]
This doesn't seem to be a problem today unless I've misunderstood.
