### ISSUE TITLE
[BITV]: Files list table has invalid HTML layout

### ISSUE THREAD

**Issue by ShGKme** [nextcloud/server#41568]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

* Parent issue: https://github.com/nextcloud/server/issues/37092

File list is a table, but it has a `div` block inside used for `#before` content, for example, text.

This is invalid, `table` is not allowed to have a `div` child:
- It breaks HTML validation analyze for a whole files list table
- It may break a11y tools

![image](https://github.com/nextcloud/server/assets/25978914/3d164748-9711-47ab-b3a2-386d3315c8ee)

```html
<table class="file-list">
  <div class="files-list__before"> <!-- ❌ DIV is not allowed here -->
    <caption class="visually-hidden">TABLE DESCRIPTION</caption> <!-- ❌ Must be out of the table and linked -->
  </div>
  <thead class="files-list__thead"></thead>
  <tbody class="files-list__tbody"></tbody>
  <tfooter class="files-list__tfooter"></tfooter>
</table>
```

**Comment by ShGKme** [comment]
Related issue:

Table is also used in a grid layout.

This is invalid because it doesn't represent a table. It makes screen-reader navigation and information very confusing. E.g. user moves right, but it is read as a next row.

On the image:
- red - table
- green - table row
- orange - table cell

![image](https://github.com/nextcloud/server/assets/25978914/b71f8ae3-45da-493a-a429-457bf7f652f9)

**Comment by susnux** [comment]
ref: https://www.w3.org/WAI/ARIA/apg/patterns/grid/
