### ISSUE TITLE
Status 500 on missing MySQL Database

### ISSUE THREAD

**Issue by christianh95** [nextcloud/server#4157]
### Steps to reproduce
1. MySQL-Server is crashed
2. Try to open nextcloud

### Expected behaviour
If the server is crashed, nextcloud should display an error message describing the problem

### Actual behaviour
I get an HTTP ERROR 500, my apache error_log says the following:

`[Thu Mar 30 09:33:11 2017] [warn] [client xx.xx.xx.xx] mod_fcgid: stderr: PHP Fatal error:  Uncaught exception 'Doctrine\\DBAL\\DBALException' with message 'Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] Connection refused' in /var/www/cloud.xxxxx.de/lib/private/DB/Connection.php:60`

### Server configuration
CentOS 6

**Web server:**
Apache 2.2

**Database:**
MySQL 5.1

**PHP version:**
5.6.21

**Nextcloud version:** (see Nextcloud admin page)
11.0.2

**Comment by MorrisJobke** [comment]
We do this, to not expose the error message. You can find it in the logs and this is there to not expose details that would help an attacker to get internal information. So this is intended.
