### ISSUE TITLE
User provisioning API Unauthorized - HTTP PUT request

### ISSUE THREAD

**Issue by ktagowski** [nextcloud/server#4158]
I'm implementing some sort of Java interface for the **Nextcloud User Provisioning API** and I have following problem, which it was described also here: https://help.nextcloud.com/t/user-provisioning-api-put-method-problems/10156 When I want to use **PUT** method to edit user attributes, I am getting **401 Unauthorized error.** HTTP Post and Delete methods are working normally.

It was tested with Apache HttpClient 4.5.3 and using Advanced REST Client.

**Nextcloud version**:  11.0.2 (stable), and it is also configured to use **HTTPS**.

**Comment by MorrisJobke** [comment]
@schiessle Is there a way to manipulate user attributes already via the provisioning API?

cc @rullzer @nickvergessen 

@daita Because we also talked about this.

**Comment by daita** [comment]
I can share my PHP on how I edit the User Infos:

```
	private function editUserInfos($type, $userId, $value) {

		$this->requestNextcloud(
			[
				'url' => 'ocs/v1.php/cloud/users/' . $userId,
				'put' => 'key=' . $type . '&value=' . $value
			]
		);
	}

	private function requestNextcloud($data) {

		$curl = curl_init($this->nextcloud['host'] . $data['url']);

		curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
		curl_setopt(
			$curl, CURLOPT_HTTPHEADER,
			array('Content-type: application/x-www-form-urlencoded', 'OCS-APIRequest: true')
		);

		curl_setopt(
			$curl, CURLOPT_USERPWD,
			$this->nextcloud['username'] . ':' . $this->nextcloud['password']
		);
		curl_setopt($curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);

/* [...] */
		if (key_exists('put', $data)) {
			curl_setopt($curl, CURLOPT_CUSTOMREQUEST, "PUT");
			curl_setopt($curl, CURLOPT_POSTFIELDS, $data['put']);
		}

		return json_decode(curl_exec($curl));
	}
```


using it like this: 
```
	$this->editUserInfos('quota', "ktagowski", "1GB");
	$this->editUserInfos('email', "ktagowski", "mail@example.com");
```

However, I have an issue when editing "displayname" attribute

**Comment by nickvergessen** [comment]
Can you try whether https://github.com/nextcloud/server/pull/4147 solves your issue?

**Comment by schiessle** [comment]
> @schiessle Is there a way to manipulate user attributes already via the provisioning API?

No, that's not possible at the moment

**Comment by nickvergessen** [comment]
yes there is:
` PUT ocs/v2.php/cloud/users/{userId}`
https://github.com/nextcloud/server/blob/master/apps/provisioning_api/lib/Controller/UsersController.php#L304-L318

**Comment by schiessle** [comment]
I assumed @MorrisJobke is looking for the whole user profile in the accounts table, including phone number, website, address etc . Which is not possible at the moment. Of course the basic stuff which already exists for ages is possible.

**Comment by MorrisJobke** [comment]
> I assumed @MorrisJobke is looking for the whole user profile in the accounts table, including phone number, website, address etc . Which is not possible at the moment. Of course the basic stuff which already exists for ages is possible.

I'm looking for display name and email address basically. But I need the phone number as well for this. 😕

**Comment by nickvergessen** [comment]
Well I guess we can easily add this. Let me create a PR

**Comment by nickvergessen** [comment]
@daita the `displayname` is only called `display` on editing atm.
But I will add a fallback for displayname (because that is what we output and its weird to be different).
