### ISSUE TITLE
cron never finishes with cached credentials SMB storage

### ISSUE THREAD

**Issue by stanelie** [nextcloud/server#416]
### Steps to reproduce
1. start `sudo -u www-data php -f /var/www/owncloud/cron.php`
### Expected behaviour

the task should finish after some time
### Actual behaviour

the task never finishes
### Server configuration

**Operating system**:
Ubuntu 14.04.4 LTS
**Web server:**
apache
**Database:**
mysql 5.5.49-0ubuntu0.14.04.1
**PHP version:**
PHP 5.5.9-1ubuntu4.17
**Nextcloud version:** (see Nextcloud admin page)
9.0.52
**Updated from an older Nextcloud/ownCloud or fresh install:**
migrated from owncloud 9.0.2
**Where did you install Nextcloud from:**
updater script
**Signing status (Nextcloud 9.0 and above):**
<details>
<summary>

Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>

App list</summary>

nothing special
</details>

**The content of config/config.php:**
<details>
<summary>

Config report</summary>

```

```

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes - SMB
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP
#### LDAP configuration (delete this part if not used)

<details>
<summary>

LDAP config</summary>

</details>
#### Web server error log

<details>
<summary>

Web server error log</summary>

```
{"reqId":"3leOz4jU5HWM1y9jMDcw","remoteAddr":"192.168.0.2","app":"webdav","message":"Exception: {\"Message\":\"Invalid request for Invalid path, \\\"*\\\" is not allowed (InvalidPathException)\",\"Exception\":\"Icewind\\\\SMB\\\\Exception\\\\InvalidPathException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeShare.php(63): Icewind\\\\SMB\\\\AbstractShare->verifyPath('\\\/A&O\\\/prod\\\/trans...')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeShare.php(108): Icewind\\\\SMB\\\\NativeShare->buildUrl('\\\/A&O\\\/prod\\\/trans...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/smb\\\/src\\\/NativeShare.php(103): Icewind\\\\SMB\\\\NativeShare->getStat('\\\/A&O\\\/prod\\\/trans...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/smb.php(115): Icewind\\\\SMB\\\\NativeShare->stat('\\\/A&O\\\/prod\\\/trans...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/lib\\\/smb.php(341): OC\\\\Files\\\\Storage\\\\SMB->getFileInfo('A&O\\\/prod\\\/transp...')\\n#5 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(213): OC\\\\Files\\\\Storage\\\\SMB->file_exists('A&O\\\/prod\\\/transp...')\\n#6 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/availability.php(236): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->file_exists('A&O\\\/prod\\\/transp...')\\n#7 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(213): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->file_exists('A&O\\\/prod\\\/transp...')\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(213): OC\\\\Files\\\\Storage\\
```

</details>
#### Nextcloud log (data/nextcloud.log)

<details>
<summary>

Nextcloud log</summary>

```
Insert your Nextcloud log here
```

</details>

After this long list (sorry, I didn't finish it, I will post more relevant details if needed), here are some more details:

From nextcloud's log, I gather that the background job is trying to go do stuff inside some users attached SMB storage. However, these mount points use the user's cached credentials from their client or from their web session. The cron task does not have access to those credentials. Could that be what is preventing the cron task to finish? Maybe it's just taking a very long time and the cron task is still processing stuff after 2 days running?

**Comment by MorrisJobke** [comment]
cc @rullzer @icewind1991

**Comment by stanelie** [comment]
In the mean time, how can I make the cron task run? How can I exclude the problematic shares?

**Comment by nickvergessen** [comment]
@stanelie still an issue with nextcloud 10?

**Comment by stanelie** [comment]
Yup, still no go.

If I try to run the task from the command line, it never finishes either.

**Comment by skjnldsv** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Comment by gorn** [comment]
I still have smilar issue. Cron.php never finishes. The only difference is that I do not use SMB shares but ssh ones.
