### ISSUE TITLE
Updater app doesn't offer update to v10.0.4

### ISSUE THREAD

**Issue by silentcreek** [nextcloud/server#4160]
I have a nextcloud installation at a webhoster (shared webspace). So far, I used the 10.y.z release branch and could easily update the installation via the builtin updater app (e.g. from v10.0.1 to v10.0.2). But recently the updater app only offered the 11.y.z releases. I changed the update channel to production, but still I was only offered the 11.x.y versions to update to. I ended up installing 11.0.2 without any issues, but I would have preferred to stay on the 10.y.z branch while it's supported.

### Steps to reproduce
1. Install an outdated release from the 10.y.z branch, eg. 10.0.3.
2. Set update channel to production.
3. Check for updates in the NextCloud admin panel.

### Expected behaviour
Updater app should offer update to 10.0.4.

### Actual behaviour
Updater app offers update to 11.0.2.

### Server configuration
**Operating system:**: Ubuntu 16.04

**Web server:** Apache (not sure about the version)

**Database:** MySQL 5.5.52

**PHP version:** 7.014

**Nextcloud version:** was 10.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** original installation was 10.0.1, which was updated via the updater app

**Where did you install Nextcloud from:** official web-installer from NextCloud

If more details are required, please let me know.

**Comment by MorrisJobke** [comment]
We roll out updates in stages. In the meantime we have provided it: https://github.com/nextcloud/updater_server/blob/b2daf6e321716cdef29b37ea7486f0362e60a06b/config/config.php#L182-L202
