### ISSUE TITLE
[Bug]: Wrong relative time for events in caldav push notifications

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#41615]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since https://github.com/nextcloud/server/issues/39862 Nextcloud shows push notifications for events. They do not handle recurrence, so an event always shows relative to the first instance, not the next instance. E.g *-1 years*

### Steps to reproduce

1. Enable notifications app
2. Create a recurring event
3. Have cron running
4. Have an open web session or a connected device

### Expected behavior

Notifications shows with correct relative time

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by GretaD** [comment]
![Screenshot from 2023-11-20 16-54-50](https://github.com/nextcloud/server/assets/12728974/8f52b1b4-eef9-4add-8125-555f9e0e7587)

**Comment by GretaD** [comment]
comment from hamza:

`\OCA\DAV\CalDAV\Reminder\ReminderService::getVEventByRecurrenceId`

I think this method is probably where the problem originates

because it joins the event data from `oc_calendar_objects` with the `oc_calendar_reminder `data in `\OCA\DAV\CalDAV\Reminder\Backend::getRemindersToProcess` which does not do a proper recurrence expansion like the search does if I see that correctly.

apps/dav/lib/CalDAV/CalDavBackend.php:1962 onwards does the expansion for the search

**Comment by ChristophWurst** [comment]
Observation shows that is is always *-1 years, 11months*. So it's probably not relative to the first instance of a recurring event but some kind of static value.

**Comment by ChristophWurst** [comment]
Played with it locally. Events recurring daily and weekly do not cause the bug here. I must be missing something.

```sql
SELECT * FROM oc_notifications WHERE user = 'admin' AND app = 'dav' AND subject = 'calendar_reminder'
```

could help debug the raw data written for notifications

**Comment by ChristophWurst** [comment]
![image](https://github.com/nextcloud/server/assets/1374172/e80ca6d9-df9f-4f6d-8f8a-350784579ab6)

From an affected instance. It doesn't matter if the event happens once, daily or weekly

**Comment by ChristophWurst** [comment]
Data looks fine

```json
{
  "title": "Weekly",
  "description": null,
  "location": null,
  "all_day": false,
  "start_atom": "2023-11-22T17:30:00+01:00",
  "start_is_floating": false,
  "start_timezone": "Europe/Vienna",
  "end_atom": "2023-11-22T17:45:00+01:00",
  "end_is_floating": false,
  "end_timezone": "Europe/Vienna",
  "calendar_displayname": "Personal"
}

```

**Comment by ChristophWurst** [comment]
It looks very similar to https://github.com/php/php-src/issues/9699

**Comment by ChristophWurst** [comment]
Bingo!

https://3v4l.org/FG7bP#v8.1.2

vs

https://3v4l.org/FG7bP#v8.1.10

**Comment by ChristophWurst** [comment]
https://3v4l.org/IQnhj for a combined view

**Comment by ChristophWurst** [comment]
@AndyScherzinger @jancborchardt what do you suggest for a workaround if more instances on Ubuntu LTS run into this?

Doing date diffing ourself would be a lot of work. As an alternative we could check if the years difference is <0 and then just hide the relative time.

**Comment by SystemKeeper** [comment]
Could we use the test cases posted above to detect if a faulty PHP version is used and decide with this if we can use relative time or not?

**Comment by ChristophWurst** [comment]
Good idea!

**Comment by AndyScherzinger** [comment]
> Doing date diffing ourself would be a lot of work. 

I agree

> As an alternative we could check if the years difference is <0 and then just hide the relative time.

Sounds good to me

> Could we use the test cases posted above to detect if a faulty PHP version is used and decide with this if we can use relative time or not?

Also I also like this one as a way to deal with it
