### ISSUE TITLE
Unexpected behaviour of "clipboard icon" in the files details

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#4161]
> ![bildschirmfoto vom 2017-03-30 14-34-15](https://cloud.githubusercontent.com/assets/213943/24504292/0c385044-1556-11e7-9edd-3e1f104e5888.png)

I think clicking this icon should do, what the tooltip says. Currently it jsut opens the input field where you then have to copy the link manually (no clipboard icon).

**Comment by rullzer** [comment]
Fixed in master alreaday
