### ISSUE TITLE
Incorrectly Formatted Date & Wrong Language in Notification For Upcoming Meeting

### ISSUE THREAD

**Issue by alperozturk96** [nextcloud/server#41618]
## Steps to reproduce
1. Setup meeting for further date
2. Receive notification before meeting date

### Expected behaviour
Date must be formatted correctly and language must be correct.

### Actual behaviour

Problems:

1. -1 years 11 months ago
2. vor ein paar Sekunden???

<img width="383" alt="wrong_notification_for_meeting" src="https://github.com/nextcloud/spreed/assets/67455295/7a180417-37fc-43a1-9e3d-3c1b7782ffef">

## Browser

**Microphone available:** yes

**Camera available:** yes

**Operating system:** MacOS Sonoma 14.1.1

**Browser name:** ungoogled-chromium

**Browser version:** 118.0.5993.117

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/server/issues/41615
