### ISSUE TITLE
[Bug]: External storage settings layout is mixed emptycontent + actual interface

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#41614]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The current external storage emptycontent view is a bit messy. It sort of looks like a combination of an emptycontent view and an actual settings view:
![image](https://github.com/nextcloud/server/assets/925062/cbb6af15-98b7-4347-ab4c-373d4aace625)

### Steps to reproduce

1. Have no external storages in your Nextcloud
2. Open the external storage settings

### Expected behavior

Have a nice emptycontent view while it is clear what to do next. For example by having the "Global credentials" behind a button like this (or with a primary button, couldn’t get components to work here):

![image](https://github.com/nextcloud/server/assets/925062/cf48f23f-def0-4ffb-8037-e98ac7563349)

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

master

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by jancborchardt** [comment]
@marcoambrosini @szaimen another feedback point for the beta, if one of you can pick it up. :)

**Comment by szaimen** [comment]
I just checked and it is like this since ancient times. E.g. on Nc25: 
![image](https://github.com/nextcloud/server/assets/42591237/58dafc14-b6a0-43eb-ab54-4266d202678c)

I think the reason is this: 
![image](https://github.com/nextcloud/server/assets/42591237/85eca915-7496-4416-965b-5241da765fa7)

What would be the best way to handle this? Just remove the empty content if there are no storages configured?
