### ISSUE TITLE
[Bug]: Wrong Translations in nextcloud-dialogs

### ISSUE THREAD

**Issue by ElSi-DVT** [nextcloud/server#41622]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In #40557 the [_Nextcloud Dialogs Library_](https://github.com/nextcloud-libraries/nextcloud-dialogs) version 4.2.1 was commited.
When opening the dialog to copy or move an object, all strings are always english no matter what language is set in the settings.

I don't know if this issue was fixed in a newer version of _Nextcloud Dialogs_ and only has to be commited again to _Nextcloud Server_ or the issue should be created in their GitHub Repository.

![grafik](https://github.com/nextcloud/server/assets/142410285/3b6127bf-1de1-455f-bd6a-2daccb94d154)

### Steps to reproduce

1. Click on the three dots on a file or folder in Nextcloud Files.
2. Click on "Move or copy".

### Expected behavior

The strings should be in the language of the current user.

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Might be covered by nextcloud-libraries/nextcloud-dialogs#1094 in v4.2.2 of @nextcloud/dialogs though I don't see a chore to update it yet in `server` for the `stable27` branch currently.

Cc: @susnux
