### ISSUE TITLE
"Shared" label takes a lot of space in Files list

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#41620]
There are some drawbacks to the recent change for the "Shared" label that came with the Vue rewrite:
- The "Shared" label takes a lot of space in the files list and makes it look very busy
- Now a lot of entries have the "Shared" label, making it actually more difficult to distinguish your "own" files and files of others at a glance
- Somehow the avatars got smaller

Now we shouldn’t remove the "Shared" label altogether since it is an important indicator of state and it has also been there in prior versions.

Here are 2 other options we could go for:
1. **Medium with avatars + icons** For internal shares coming from others, we use the proposal by @Clementine46 from https://github.com/nextcloud/server/issues/38156
2. **Remove label for shares from others:** This is basically back to how it was before, but keeping the layout and color improvement of the "Shared" label.

Current | Medium with avatars + icons | Remove label for shares from others
-|-|-
![Sharing current](https://github.com/nextcloud/server/assets/925062/e475d9ae-3820-468e-92b1-7f1b0b7eda5c)|![sharing medium](https://github.com/nextcloud/server/assets/925062/f72a03e0-f686-425e-be56-c2358a65ea33)|![Sharing plain](https://github.com/nextcloud/server/assets/925062/a6276772-405e-4b8f-9ea9-465664bcfce0)

cc @nextcloud/designers and @karlitschek since you reported the original issue.

**Comment by karlitschek** [comment]
both options would work for me.
