### ISSUE TITLE
LDAP user cleaneup not working

### ISSUE THREAD

**Issue by git529** [nextcloud/server#41628]
### Steps to reproduce
1. Enable LDAP user and group backend
2. Configure LDAP/AD integration in Administration Settings
3. Nextcloud creates all LDAP users successfully
4. Delete user on LDAP server
5. Nextcloud removes the user as shown on the Users web interface (https://nextcloud.mydomain.com/settings/users)
6. After a while, I run `sudo -u www-data php occ ldap:show-remnants` in the nextcloud-aio-nextcloud container and it shows the deleted user
7. However, upon checking the nextcloud/data folder on the host system, the user's home folder remains and its not deleted

### Expected behavior 
the ldap user's home folder should be deleted

### Actual behavior 
the ldap user's home folder is not deleted

### Host OS 
Synology NAS / Linux

#### Nextcloud AIO version 
Nextcloud AIO v7.6.2

#### Current channel 
Latest

**Comment by solracsf** [comment]
This is expected and intended. One could want to move the data away before delete it, so the user must be **explicitly** removed.
See https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_auth_ldap_cleanup.html#ldap-user-cleanup

(just below _"These examples are for Ubuntu Linux:"_)

**Comment by solracsf** [comment]
_Pro tip: want to clean them automatically / programatically?_

```
sudo -u www-data php /var/www/nextcloud/occ ldap:show-remnants --json | jq -c '.[] | "sudo -u www-data php /var/www/nextcloud/occ user:info \(.ocName)"' | xargs -I {} sh -c {}
