### ISSUE TITLE
LDAP Password Changes -> Encryption App

### ISSUE THREAD

**Issue by orestes910** [nextcloud/server#4162]
### Steps to reproduce
1. Setup Nextcloud to auth against LDAP/AD
2. Enable Encryption App and encrypt files
3. Change user's password in LDAP/AD
4. Log in to Nextcloud
5. Receive message claiming mismatch between password and encryption pass phrase

### Expected behaviour
Encryption pass phrase should automatically update upon login with a new password.

### Actual behaviour
User must manually change pass phrase from "Personal" tab.

### Server configuration
**Operating system**:
CentOS 7.1 64bit

**Web server:**

Apache 2.4

**Database:**

Percona XtraDB Server

**PHP version:**

7

**Nextcloud version:** (see Nextcloud admin page)

11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**

Fresh

**Where did you install Nextcloud from:**

downloaded and extracted

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by blizzz** [comment]
> Encryption pass phrase should automatically update upon login with a new password.

Decryption needs to happen first and therefore we need to old password.

fyi @schiessle

**Comment by schiessle** [comment]
Not possible. How should Nextcloud be able to "magically" decrypt your private key and re-encrypt it with the new login password and still be called secure. If you don't want to use per-user keys I recommend to use the master key approach: https://docs.nextcloud.com/server/11/admin_manual/configuration_files/encryption_configuration.html#occ-encryption-commands

Note: It is not possible to migrate a instance which already uses encryption to the master-key approach or back!

**Comment by bayhaqy** [comment]
Hi @schiessle. I enable feature on menu "Admin->Encryption->Disable recovery key" and "Personal->Basic encryption module->Enable password recovery:Enable". I test to change my user password from Active Directory (I using LDAP for user). When I login, have a notification "Invalid private key for Encryption App. Please update your private key password in your personal settings to recover access to your encrypted files".

When I try to recovery key password on menu personal. Only written "Saving.."
How to troubleshoot that?
Thanks

**Comment by schiessle** [comment]
Do you have any error in your Nextcloud.log or the java script console of your browser?
