### ISSUE TITLE
[Bug]: Invalid type for field favorite

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#41630]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Webdav SEARCH for favorite is not working

### Steps to reproduce

1. create a folder
2. mark it as favorite
3. do webdav SEARCH:
```
curl --request SEARCH \
  --url http://localhost:8080/remote.php/dav \
  --header 'Authorization: Basic dGVzdDp0ZXN0' \
  --header 'Content-Type: text/xml' \
  --header 'OCS-APIRequest: true' \
  --data '<?xml version="1.0" encoding="UTF-8"?>
<d:searchrequest xmlns:d="DAV:" xmlns:nc="http://nextcloud.com/ns"
								 xmlns:oc="http://owncloud.com/ns">
		<d:basicsearch>
			<d:select>
				<d:prop>
					<d:displayname/>
					<d:getcontenttype/>
					<d:resourcetype/>
					<d:getcontentlength/>
					<d:getlastmodified/>
					<d:creationdate/>
					<d:getetag/>
					<d:quota-used-bytes/>
					<nc:sharees xmlns:nc="http://nextcloud.org/ns"/>
					<d:quota-available-bytes/>
					<oc:permissions xmlns:oc="http://owncloud.org/ns"/>
					<oc:id xmlns:oc="http://owncloud.org/ns"/>
					<oc:size xmlns:oc="http://owncloud.org/ns"/>
					<oc:favorite />
				</d:prop>
			</d:select>
			<d:from>
				<d:scope>
					<d:href>/files/test</d:href>
					<d:depth>infinity</d:depth>
				</d:scope>
			</d:from>
			<d:where>
				<d:eq>
					<d:prop>
						<oc:favorite xmlns:oc="http://owncloud.org/ns"/>
					</d:prop>
					<d:literal>yes</d:literal>
				</d:eq>
			</d:where>
			<d:orderby/>
	</d:basicsearch>
</d:searchrequest>'
```
4. See:
```
HTTP 500 error
<?xml version="1.0" encoding="utf-8"?>
<d:error
	xmlns:d="DAV:"
	xmlns:s="http://sabredav.org/ns">
	<s:exception>InvalidArgumentException</s:exception>
	<s:message>Invalid type for field favorite</s:message>
</d:error>

```

### Expected behavior

folder should be shown

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment]
Good one, well spotted :+1: 

I guess we have to drop the type hints from SearchComparison.__construct and SearchComparison.getValue again to make it work and adjust the interface in for the next major release to accept bool|int|string|\DateTime. 

The current type hint int|string|\DateTime converts the boolean for favorite to an int but the actual search expects an boolean. This works without the type hint because no type juggling is done.

**Comment by tobiasKaminsky** [comment]
Indeed, using <d:literal>1</d:literal> instead of <d:literal>yes</d:literal> works.
We could change it for our clients, but not for all the other ones, so this needs be reverted on server.

**Comment by ArtificialOwl** [comment]
> Indeed, using <d:literal>1</d:literal> instead of <d:literal>yes</d:literal> works. We could change it for our clients, but not for all the other ones, so this needs be reverted on server.

just checked on 27 and any value was accepted, even `<d:literal>false</d:literal>` is accepted for `true`. We might want to have a deeper look into this in a future release.

I have fixed it, following @kesselb instruction; seems to work the same than for 27.

To improve the general behavior on boolean value:
- If we want to be more precise and accept `true/false` we might want to check on 
  https://github.com/nextcloud/server/blob/380b81315ab35fd7272fc2c99460f1a8ed4ea086/lib/private/Files/Cache/SearchBuilder.php#L181-L183
- if we want to accept other value than `yes` (like `true` or `1`) this is where we can add entries to accept: 
  https://github.com/nextcloud/server/blob/380b81315ab35fd7272fc2c99460f1a8ed4ea086/apps/dav/lib/Files/FileSearchBackend.php#L421
