### ISSUE TITLE
Add an upload progress bar in "File drop (upload only)" shares

### ISSUE THREAD

**Issue by GetBoz** [nextcloud/server#4164]
### Feature request

When uploading a big file in a "File drop (upload only)" share, we have no idea of the remaining upload time.
It would be a great enhancement to add a progress bar +remaining upload time, like in other uploads.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by MorrisJobke** [comment]
cc @nextcloud/javascript maybe somebody from you want to check this out, but maybe first have an UI mockup ;)

**Comment by BetaLeaf** [comment]
I would also like to see this.

**Comment by MariusBluem** [comment]
> I would also like to see this.

You may also like to code this 🚀🙈

**Comment by BetaLeaf** [comment]
Unfortunately, I know nothing about PHP.

**Comment by tcitworld** [comment]
Good thing this requires javascript skills then. :trollface:

**Comment by BetaLeaf** [comment]
Just goes to show I'm not the right guy for the job. I didn't even know. Unfortunately, I don't know much about javascript either. I simply commented my support for this ticket. Get it back in the spotlight.

**Comment by jancborchardt** [comment]
@lcalaresu maybe something for you, since you do the file upload for the Mail app with nice progress bars too? :)

**Comment by Espina2** [comment]
I can suggest this, https://github.com/jacoborus/nanobar

I will make the UI mockup. Anyway can post the exact specific page?
I can even do the javascript part, if I see any way to make a dev environment faster, like a docker image.

**Comment by lcalaresu** [comment]
@Espina2
Why not just use jquery-ui since it is already included in nextcloud server ?

**Comment by jancborchardt** [comment]
Yup, we shouldn't necessarily include more libraries cause it will lower performance.

@lcalaresu as said, feel free to explore. :)

**Comment by Espina2** [comment]
@icalaresu Go ahead, I didn't use Jquery to much those days, and I don't even know that JqueryUi has used here. Since @jancborchardt said to you I'm backing off.

**Comment by lcalaresu** [comment]
I could use the same simple progress bars that I am using on the mail app, what do you think:

- ongoing upload label is blue, with a progress bar,
- label and progress bar become red when an error occurred,
- when everything went well, label goes back to the "normal" colour, and the progress bar disappear.

However, files dropped are usually larger than email attachments, so remaining time or percentage status would definitely make sense, but which one is better?
I would say remaining time is better, but could be not very reliable sometimes... Percentage is simpler but more reliable.

- Fig.1: Only display percentages, at the right of the filename to save space
- Fig.2: Only display percentages, but under the progress bar
- Fig.3: Display remaining time (under the progress bar is the only option I think, if anyone has another idea)

![dropbox-mockup](https://user-images.githubusercontent.com/28860515/27631345-73bd1d7e-5bf8-11e7-804a-ac18f11eff2c.png)

What do you think ? cc @nextcloud/designers

**Comment by BetaLeaf** [comment]
Not a designer, but my vote is on fig 3

**Comment by andreasjacobsen93** [comment]
I like Fig. 1 the best, clean and easy to read.

**Comment by jancborchardt** [comment]
@lcalaresu good stuff. Showing the remaining time is best since the bar already shows the percentage.

Some changes:

- While uploading, show the filename in normal text color instead of blue
- Show the filetype icon already when uploading
- In error states, show .icon-error left next to the error text, or instead of the filetype icon
- Left-align the time remaining text and error message, that makes it nicer to read
- Make the secondary text normal color and half-transparent, just like the secondary text elsewhere (File extensions, Mail app, Personal settings, etc)
- Use the same style for the bar as in the new quota bar of the Files app: grey bar for full width (no border), and 3px rounded corners
- Probably separate enhancement, but there should also be a cancel function on the right.

Does that work @lcalaresu? Thanks for your great contributions!

**Comment by lcalaresu** [comment]
@jancborchardt :
> Use the same style for the bar as in the new quota bar of the Files app: grey bar for full width (no border), and 3px rounded corners

Yes, I used that one first, but I can barely see the grey part on my screen (that is why I added the borders)... Maybe I need to calibrate my screen :smile: 

I think the cancel function should indeed be added later, coz I am not sure how to do it with the current librairies.

Here is the new version: 
![dropbox-v2](https://user-images.githubusercontent.com/28860515/27677230-326b2a5a-5cb1-11e7-9457-2973075e8716.PNG)

**Comment by jancborchardt** [comment]
Looking good! Only two things:

- The bar still needs 3px border-radius
- Both the bar and the text under it should start a bit more to the right, so they are left-aligned with the filename. The icon could be vertically centered (moved down) a bit for visual balance.

**Comment by lcalaresu** [comment]
I lost my harddrive a few days back... not sure I can contribute to that one quickly :sweat: 
If it's urgent and someone wants to do it, go ahead!!

**Comment by k1ngf15h3r** [comment]
any news about this feature? really like the idea but I am not a developer so I can not assist in coding this. @lcalaresu is your harddrive in any way accessable? maybe testdisk could recover data

**Comment by MarcusLiback** [comment]
> any news about this feature?

I second this. This feature would be tremendously useful.

**Comment by jancborchardt** [comment]
@lcalaresu did you not push to a branch? Or manage to recover the data? Your contribution here would be much appreciated. :)

**Comment by skjnldsv** [comment]
@jancborchardt 
> The bar still needs 3px border-radius
> Both the bar and the text under it should start a bit more to the right, so they are left-aligned with the filename. The icon could be vertically centered (moved down) a bit for visual balance.

We should add a specific class for that and some guidelines in the dev docs!

**Comment by jancborchardt** [comment]
@skjnldsv yep, exactly! We can start from the quota bar style. :)

**Comment by skjnldsv** [comment]
@jancborchardt And support the 'progress' html5

**Comment by skjnldsv** [comment]
html5 progress support have been implemented by #6669

**Comment by sunjam** [comment]
In my .02 it would be helpful for the uploader to see not just per per file progress, but an overall estimation of time left for the upload.  I’ve found users can get antsy when updating from their phone data plan, etc.

`Uploading 12 of 100 files.`
`Estimated 15 minutes`

**Comment by c0fe** [comment]
Having used in business the dropbox feature in Nextcloud many users found it confusing and not informative of what is going on. Certain files failed during upload with 0 information as to what happened. 

meganz/webclient is open and provides a good information on what is uploading.

**Comment by sunjam** [comment]
@c0fe. Agreed, I was thinking of that as probably a different issue, but it
would be great for the server admin to get an activity feed of which files
failed to upload off a file drop.  Right now that info is only displayed to
the client in their web browser.

**Comment by c0fe** [comment]
@sunjam i have had files fail with the only feedback being an exclamation mark icon and that's all.

**Comment by skjnldsv** [comment]
Let's implement this for 14!

**Comment by c0fe** [comment]
@skjnldsv what are your thoughts on the uploader utilized by mega.nz?

**Comment by skjnldsv** [comment]
It seems very neat.
Maybe too much informations but we could do something close to that.

![capture d ecran_2018-03-01_18-25-24](https://user-images.githubusercontent.com/14975046/36859227-fc130052-1d7d-11e8-9328-33f79558ab53.png)

**Comment by c0fe** [comment]
@skjnldsv too much information? how so?

**Comment by skjnldsv** [comment]
No need for status as a text, icons are enough. ETA & spinner on the left & circular progress on the left can be merged into one item (single progress bar). No need for the Type, the extension and file name should be enough. :)

**Comment by sunjam** [comment]
@skjnldsv it would great if the admin could also receive that info you screenshot of which files succeeded and failed, especially errors of files that did not upload via filedrop.  I went on a trip recently and created a file drop for photo sharing with random people  A ton of photos failed to upload, but I cannot tell my friends which ones...

**Comment by skjnldsv** [comment]
It depends on what is he failure related to. If it's a connectivity issue, there's no way we can let the admin know automatically. Nonetheless, if the upload stops in the middle, it could probably be done. Maybe not a priority tough :)

**Comment by c0fe** [comment]
@skjnldsv maybe icons are enough for you or me but the thing is the average user needs text. It is helpful.

I do not think that the design mega.nz has is cluttered, it is informative and good.

**Comment by c0fe** [comment]
@skjnldsv if connectivity, it should log the fact that client x established connection, client x began upload file y, connection with client x dropped.

**Comment by sunjam** [comment]
[Issue #2019](https://github.com/nextcloud/server/issues/2019) could also benefit filedrops so anonymous comments could be left.  
Example:  _Our soccer video failed to upload. Sorry._
Example: anonymous comment could copy pasta error output in their browser to admin or user.

**Comment by c0fe** [comment]
@sunjam not sure, most of the users i have seen won't be bothered to do this at all.

**Comment by sunjam** [comment]
@c0fe Help me out as you just mentioned desiring better reporting in issue #8586.  Do not undermine the need for better reporting.  We need it!
    
What if, at the completion of uploading (with errors) a button button popped up to say:
![13d2af8a-bb8f-4e86-a2cd-d4b6cbdf23b3](https://user-images.githubusercontent.com/1787238/36883131-dcb6d8be-1d8c-11e8-9bd0-5d8032050bde.jpeg)
This could send a copy of the log to the respective user/admin that would otherwise be seen by the anonymous uploader in their browser.

**Comment by c0fe** [comment]
@sunjam in my experience users are very uninterested in taking extra steps to let the admin know if anything went wrong and if they do they really do not provide additional information other than "it didn't work" or "it isn't working".

Having mechanisms that alerts the admins is a better alternative in my opinion.

**Comment by c0fe** [comment]
@skjnldsv has this been started on or is there some internal talks about this? I am wondering if I should just start on this and then issue a pull request.

I was considering just implementing the webclient mega uses now. what are your thoughts?

**Comment by skjnldsv** [comment]
@c0fe I did not start this yet. Feel free to go for it if you want! :)

**Comment by MorrisJobke** [comment]
I still doubt, that sending the admin information here will help at all. There is nothing an admin can do (neither has the admin the files, not does the admin know whom to ask). I would improve the user feedback and not send the admin useless information.

**Comment by c0fe** [comment]
@MorrisJobke I am a bit confused because I was talking about purely aesthetic sense of uploading not sending or grabbing any information.

Oh @MorrisJobke @skjnldsv is there an IRC channel I can ask any additional questions if I have any?

**Comment by MorrisJobke** [comment]
> @MorrisJobke I am a bit confused because I was talking about purely aesthetic sense of uploading not sending or grabbing any information.

Okay :+1:

@nextcloud/designers can also give feedback on that once you have something available.



> Oh @MorrisJobke @skjnldsv is there an IRC channel I can ask any additional questions if I have any?

Yes. #nextcloud-dev on freenode.

**Comment by MorrisJobke** [comment]
Most likely nothing for 14 -> moving to 15.

**Comment by MorrisJobke** [comment]
Maybe something for the polishing, but also fine if it doesn't make it.

**Comment by caugner** [comment]
@rullzer Since you added the Hacktoberfest label, could you shortly describe what needs to be done here? E.g. is this exclusively about the upload progress (see issue description) or does this also include reporting upload errors to the admin (see comments)?

**Comment by ChristophWurst** [comment]
>  or does this also include reporting upload errors to the admin (see comments)?

IMO this still doesn't make sense -> https://github.com/nextcloud/server/issues/4164#issuecomment-371258303.

**Comment by MorrisJobke** [comment]
> @rullzer Since you added the Hacktoberfest label, could you shortly describe what needs to be done here? E.g. is this exclusively about the upload progress (see issue description) or does this also include reporting upload errors to the admin (see comments)?

Let's focus first on the progress bar. Feedback is still useful, but the admin can't do much. If there is a problem with the upload itself then it should be somehow shown to the user (if it makes sense - for example: quota reached).

**Comment by pm-pm** [comment]
Hello,
Could someone please explain what the status of this issue is?

**I think it would be wonderful if this feature finally comes.**

My friends are often not able to estimate how long an upload will take. That's why I can't use "upload only" feature without them being confused.

Please install this feature to convince new users of the advantages of Nextcloud. Otherwise "other" file services will be used again.

Thanks. :-)

**Comment by ChristophWurst** [comment]
Status: someone has to do it.

**Comment by ModestTG** [comment]
Was this issue ever resolved? I see that [#20244](https://github.com/nextcloud/server/pull/20244) was merged, and this issue was closed, but then this issue was then added to the NextCloud 19 Milestone, but we're on version 21? I have tried this in NextCloud 21 and I'm not seeing any progress bar. Just wanted to know if this issue was in fact resolved and potentially buried in the settings somewhere or if this is still potentially being worked on. Thanks in advance!

**Comment by mMuck** [comment]
@ModestTG Sure, there is a great progress bar for "File drop (upload only)" shares

Try by yourself - the 60 seconds test: https://try.nextcloud.com (I think NC 21.0.4.1) -> Select "Instant trial" and click the button. A new instance is created. After you logged in automatically, click the Files App. Share one of the given folders and change the share to a "upload only" share (share context menu). Open the created share token in another browser window/tab. You won't see the folder content but you can upload files now. Pick a sufficient(!) large file. I used some 30 MB setup file from my downloads folder and watch 😉. I got this:
![grafik](https://user-images.githubusercontent.com/8143240/142381166-05820752-8e15-4e13-97b6-77bbfa8ef25c.png)

**Comment by mgutt** [comment]
> @ModestTG Sure, there is a great progress bar for "File drop (upload only)" shares
> 
> Try by yourself - the 60 seconds test: https://try.nextcloud.com

Funny. Did that. Drag & Drop of a 100MB.bin and it showed... nothing. After several seconds the file appeared without any progress bar or similar. It seems this feature is broken again 😒
