### ISSUE TITLE
[Bug]: Multiselect menu missing "Move or copy"

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#41661]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

As reported by @jospoortvliet 

The copy/move can't be found there anymore:
![Screenshot_20231115_033010](https://github.com/nextcloud/server/assets/551757/72519134-ed0e-4a64-a553-8458b79bc2ca)

### Steps to reproduce

1. Use multiselect menu in files
2. Notice there is no way to move or copy multiple files

### Expected behavior

- One should be able to "Move or copy" via multiselect like before
- Order of actions should be exactly like in the single file actions menu: Add to favorites, Move or copy, Download, Delete
- "Move or copy" needs to take into account if you don’t have ability to move/copy one of the selected elements, like e.g. a groupfolder (where "Delete" is also hidden already)

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ShGKme** [comment]
@jancborchardt Is the current "Expected behavior" still actual, and we only need to add a new button here?

**Comment by jospoortvliet** [comment]
@ShGKme if we add copy/move we're in a MUCH better position.
