### ISSUE TITLE
None english users miss half the icons in personal settings

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#4170]
The problem is it tries to use `nav-icon-aktivität` which of course does not exist.
It's because the anchor is created with a hack from the h2 header.

We should fix this with another hack (like a class on h2 or data attribute) when we don't finish the migration to the `ISettings` before the release…

**Comment by MorrisJobke** [comment]
Affected sections discovered:

- external storage
- ssl certs
- two factor backup codes
- activity

**Comment by MorrisJobke** [comment]
Let me check if I could fix this with the hack that @nickvergessen mentioned

**Comment by MorrisJobke** [comment]
Fix is in #4569
