### ISSUE TITLE
Sidebar "mark as favorite" menu item mixed up the menu text

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#41711]
|favorite state|no-favorite state|
|---|---|
|<img width="375" alt="2023-11-24 00_38_32" src="https://github.com/nextcloud/server/assets/1315170/16fb456a-84aa-404b-8806-a32f8e29453d">|<img width="378" alt="2023-11-24 00_38_47" src="https://github.com/nextcloud/server/assets/1315170/b25a78d9-0dbc-4819-94e2-4a463f46263b">|

From my pov the icons in the menu reflect the result of the action while the text reflects the current state instead of the state when hitting the menu item.

What do you think  @marcoambrosini  ?

**Comment by marcoambrosini** [comment]
I agree @AndyScherzinger, I did it like that because that's how it's done files list menu. It seemed strange to me, but I didn't raise that. I'm going to change both then :)

**Comment by marcoambrosini** [comment]
Sidebar is fixed, but I'm unable to fix the bug in the files list @skjnldsv could you help me out?
