### ISSUE TITLE
[Bug]: Right click menu should open at cursor position

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/server#41721]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In NC 28 the right click menu always opens at the "..." menu, not at the cursor location.

### Steps to reproduce

1. Go to the files app
2. Right click on a file / folder

### Expected behavior

Right click menu should open at cursor location

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

https://github.com/nextcloud/server/assets/1580193/c0bcf1cb-aa20-46bf-81e4-dfb0d99b6c6f

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/pull/37669

**Comment by ChristophWurst** [comment]
There was some discussion in the collapsed comments

**Comment by jancborchardt** [comment]
Important is also that when it opens at cursor position, the "Share" entry needs to be first in the menu, just like it was before.

**Comment by skjnldsv** [comment]
> Important is also that when it opens at cursor position, the "Share" entry needs to be first in the menu, just like it was before.

this has nothing to do with that ticket :)
Let's open a dedicated ticket for this because this needs answers :)

**Comment by tflidd** [comment]
> There was some discussion in the collapsed comments

The comment about to keep it simple, is this from a programming point of view?

For me it is an unexpected behavior, different from any user interface (desktop or web-based). Especially on lager screens, it is really strange (you might even miss that there is something opening up at the other end of your screen).

The right click app had this already implemented "the right way".

**Comment by skjnldsv** [comment]
> is this from a programming point of view?

Yes, the perk of having the menu open at the menu button location supersede the many other issues the `files_rightclick` implementation had (lack of action parity, lagging, technical debts...)

But this ticket is opened, so we agree that having the menu open at the mouse cursor is still expected :+1:
