### ISSUE TITLE
[Bug]: When I create a file in a shared folder, it is shown as not shared

### ISSUE THREAD

**Issue by GretaD** [nextcloud/server#41725]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I created a file on a shared folder, the file is shown as not shared. After refresh, it looks good

### Steps to reproduce

1. Open a shared folder
2. Create a file
3. See if its shared

### Expected behavior

the file is shown as shared directly to avoid confusion

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

![Screenshot from 2023-11-24 10-25-58](https://github.com/nextcloud/server/assets/12728974/2a62ef29-4626-4e3b-a130-b53653fa4565)

**Comment by susnux** [comment]
I do not really get the issue here, files inside shared folders are not marked as shared in any case.
The only issue I can see here are folders from other mount-points (e.g. groupfolders) where the mount-type information is missing on creation.

**Comment by susnux** [comment]
Ah I see its about the share info part -> also mount-type related
