### ISSUE TITLE
Multiple highlighted / active elements in left sidebar for favorites

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#41737]
Currently favorites sub items in left sidebar when active also have the parent element highlighted, this is not the case for active sub items of other categories, like shared with...
<img width="518" alt="2023-11-24 16_00_04-Files - Nextcloud – Mozilla Firefox" src="https://github.com/nextcloud/server/assets/1315170/04136a8d-c272-415a-b343-b431fedd8234">

cc @nextcloud/designers on which way to implement it, I tend to say only highlight one item - don't highlight the parent element in addition.

**Comment by szaimen** [comment]
> I tend to say only highlight one item - don't highlight the parent element in addition.

Agreed 👍

**Comment by Sanket-Arekar** [comment]
I would like to work on this issue. Can you Please assign me this issue?

**Comment by marcoambrosini** [comment]
Hi @Sanket-Arekar , sure :)

**Comment by jancborchardt** [comment]
@Sanket-Arekar are you still interested in this issue? You don’t need to be assigned to work on it. :) 

Otherwise @marcoambrosini @szaimen since this is possibly an accessibility issue, could you pick this up, then we can backport it. :)

**Comment by dorelmarian20** [comment]
I am new around here and I can try working on it if you don't mind :)

**Comment by marcoambrosini** [comment]
Sure @dorelmarian20, thank you! We have this Nextcloud Talk room in case you need help getting started :)
https://cloud.nextcloud.com/call/3609520619
 
Feel free to ping me there if you need help!

**Comment by marcoambrosini** [comment]
@skjnldsv I just saw that you self assigned this, is it ok if @dorelmarian20 picks it up?

**Comment by jancborchardt** [comment]
There is a fix in the pull request at https://github.com/nextcloud/server/pull/42095
