### ISSUE TITLE
 503 Storage is temporarily not available

### ISSUE THREAD

**Issue by LuCu11** [nextcloud/server#4173]
### Steps to reproduce
1. Samba Share on selfhosted Server, connected via SMB/CIFS
2. Connect from Win7 via WebDAV
3. Connect via Nextcloud Android App

### Expected behaviour
equal if I connect via Windows WebDAV or Nextcloud Android App, I can connecet to the samba storage via the nextcloud service

### Actual behaviour
After some time, when I connect via Windows 7 WebDAV, integrated with drive letter, i can´t access the strage and get a 503 Storage is temporarily not available message in the nextcloud.log, also in the apache-log
after some further minutes, i works fine, after some further minutes it works not, it seems it has something todo sessions?!

### Server configuration
**Operating system**:
Debian 8.7
**Web server:**
apache 2.4.10
**Database:**
mysql 5.5.54
**PHP version:**
5.6.30
**Nextcloud version:** (see Nextcloud admin page)
11.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

  - activity: 2.4.1
  - bookmarks: 0.9.1
  - calendar: 1.5.1
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - direct_menu: 0.10.0
  - external: true
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - keeweb
  - templateeditor
  - user_external
  - user_ldap
  - user_saml

</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' =>
  array (
    0 => 'xxx.',
  ),
  'datadirectory' => '/var/www/html/ocldata/data',
  'overwrite.cli.url' => 'https://xxx/cloud',
  'dbtype' => 'mysql',
  'version' => '11.0.2.7',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_xxx',
  'dbpassword' => 'xxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'sendmail',
  'mail_from_address' => 'user',
  'mail_domain' => 'xxx',
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Memcached',
  'memcached_servers' =>
  array (
    0 =>
    array (
      0 => 'localhost',
      1 => 11211,
    ),
  ),
  'maintenance' => false,

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes, smb
**Are you using encryption:** yes/no
no 
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Windows WebDAV, Firefox, Internet Explorer
**Operating system:**
Windows 7
#### Web server error log
<details>
<summary>Web server error log</summary>

```
x.x.x.x - xxx [31/Mar/2017:16:09:47 +0200] "GET /cloud/remote.php/webdav/Dataxxx.mp3 HTTP/1.1" 503 1757 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"

"PROPFIND /cloud/remote.php/webdav/Data/desktop.ini HTTP/1.1" 503 1083 "-" "Microsoft-WebDAV-MiniRedir/6.1.7601"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"yEicO3YpHAIRGHWPv0op","remoteAddr":"xxx","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Storage is temporarily not available\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(81): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('Data\\\/medien\\\/pod...')\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/html\\\/cloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/c...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":162,\"User\":\"sync\"}","level":4,"time":"2017-03-31T14:09:47+00:00","method":"GET","url":"\/cloud\/remote.php\/webdav\/Data\xxx.mp3","user":"sync","version":"11.0.2.7"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by LuCu11** [comment]
@all, is there anybody who can help me to solve this problem?

**Comment by ManOki** [comment]
Do you have preview/thumbnails enabled for that storage? 

My setup contains big media files in separated directories stored at my NAS and added to nextcloud via samba/external storage. If i open such a directory with any nc client, the server tries to generate previews i.e. download all files within this directory from nas to server, which sometimes takes a while. During this time, the nc server is completly blocked for every client (and user) and producing 503 server error.

**Comment by skjnldsv** [comment]
Well, 503 error definitely means what it means, it cannot reach the smb server.
So this is not a nextcloud issue.
