### ISSUE TITLE
clicking "recent"  button should refresh the list

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/server#41752]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
to update the "recent" list it currently necessary to click the browser refresh button or choose another NC button and than recent

**Describe the solution you'd like**
click on the NC recent button to refresh the list

**Describe alternatives you've considered**
browser refresh is more time consuming
click on all files + refresh is also more time consuming.

**Additional context**

**Comment by joshtrichards** [comment]
No longer the case in >=28.
