### ISSUE TITLE
[Bug]: Login window disappeared after update to Nextcloud 27.1.4.1

### ISSUE THREAD

**Issue by gmt-it** [nextcloud/server#41756]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The update to Nextcloud 27.1.4.1 went through without errors. According to the admin overview, everything was fine after the update. No config errors were displayed. After logging out, there is no chance of logging in because the login form is not displayed.

### Steps to reproduce

1. Go to https://cloud.suelsen.de
2. no login form is displayed
3.

### Expected behavior

Login form should be displayed

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.suelsen.de",
            "10.200.1.11",
            "10.200.1.1"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.4.1",
        "overwrite.cli.url": "http:\/\/cloud.suelsen.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "log_type": "file",
        "log_type_audit": "file",
        "logfile": "\/var\/www\/nextcloud\/data\/nextcloud.log",
        "logfile_audit": "\/var\/www\/nextcloud\/data\/audit.log",
        "logfilemode": 416,
        "loglevel_frontend": 2,
        "default_phone_region": "DE",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "files_downloadactivity",
            "dicomviewer"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "overwriteprotocol": "https",
        "updater.release.channel": "stable"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - calendar: 4.5.3
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.4.2
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - deck: 1.11.1
  - dicomviewer: 1.2.5
  - encryption: 2.15.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_downloadactivity: 1.16.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - groupfolders: 15.3.1
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - nextcloud_announcements: 1.16.0
  - notes: 4.8.1
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - support: 1.10.0
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - tasks: 0.15.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - bruteforcesettings: 2.7.0 (installed 2.4.0)
  - files_trackdownloads: 1.11.0 (installed 1.11.0)
  - occweb: 0.1.1 (installed 0.1.1)
  - richdocumentscode: 23.5.503 (installed 23.5.503)
  - suspicious_login: 5.0.0
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0
```

### Nextcloud Signing status

```shell
Can not login
```

### Nextcloud Logs

```shell
{"reqId":"silmIUMb1hEEdqCzXaHV","level":3,"time":"2023-11-26T21:01:11+00:00","remoteAddr":"10.200.1.1","user":"--","app":"PHP","method":"GET","url":"/index.php/apps/theming/icon?v=91444be1","message":"file_get_contents(/mnt/storage_1/nextcloud/appdata_oc8zv9jkl98r/theming/global/35/touchIcon-core#D9D9D9): Failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#320","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0","version":"27.1.4.1","data":{"app":"PHP"}}
{"reqId":"silmIUMb1hEEdqCzXaHV","level":3,"time":"2023-11-26T21:01:11+00:00","remoteAddr":"10.200.1.1","user":"--","app":"index","method":"GET","url":"/index.php/apps/theming/icon?v=91444be1","message":"Exception thrown: OCP\\Files\\GenericFileException","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:120.0) Gecko/20100101 Firefox/120.0","version":"27.1.4.1","exception":{"Exception":"OCP\\Files\\GenericFileException","Message":"","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Files/SimpleFS/SimpleFile.php","line":74,"function":"getContent","class":"OC\\Files\\Node\\File","type":"->"},{"file":"/var/www/nextcloud/lib/public/AppFramework/Http/FileDisplayResponse.php","line":67,"function":"getContent","class":"OC\\Files\\SimpleFS\\SimpleFile","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":240,"function":"callback","class":"OCP\\AppFramework\\Http\\FileDisplayResponse","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1068,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Files/Node/File.php","Line":56,"CustomMessage":"Exception thrown: OCP\\Files\\GenericFileException"}}
```

### Additional info

login:1  Refused to apply style from 'https://cloud.suelsen.de/apps/dicomviewer/css/sidebar.css?v=db3daece-35' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
core-common.js:2  Uncaught SyntaxError: Invalid or unexpected token
de.js?v=8e528490-35:1  Uncaught ReferenceError: OC is not defined
    at de.js?v=8e528490-35:1:1
fileinfo.js:181  Uncaught ReferenceError: OC is not defined
    at fileinfo.js:181:4
merged-template-prepend.js?v=8e528490-35:26  Uncaught ReferenceError: OC is not defined
    at merged-template-prepend.js?v=8e528490-35:26:1
de.js?v=8e528490-35:1  Uncaught ReferenceError: OC is not defined
    at de.js?v=8e528490-35:1:1
encryption.js?v=8e528490-35:12  Uncaught ReferenceError: OC is not defined
    at encryption.js?v=8e528490-35:12:1
de.js?v=8e528490-35:1  Uncaught ReferenceError: OC is not defined
    at de.js?v=8e528490-35:1:1
index.js:25  Uncaught ReferenceError: OC is not defined
    at index.js:25:15
de.js?v=8e528490-35:1  Uncaught ReferenceError: OC is not defined
    at de.js?v=8e528490-35:1:1
toolbar.js:8  Uncaught ReferenceError: t is not defined
    at ./components/helpers/toolbar.js (toolbar.js:8:12)
    at __webpack_require__ (bootstrap:19:1)
    at ./components/helpers/index.js (index.js:3:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./components/index.js (index.js:1:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./index.js (index.js:2:1)
    at __webpack_require__ (bootstrap:19:1)
    at bootstrap:83:1
    at bootstrap:83:1
de.js?v=8e528490-35:1  Uncaught ReferenceError: OC is not defined
    at de.js?v=8e528490-35:1:1
script.js:427  Uncaught SyntaxError: Unexpected identifier 'Â'
files.js?v=8e528490-35:122  Uncaught ReferenceError: jQuery is not defined
    at files.js?v=8e528490-35:122:12
de.js?v=8e528490-35:1  Uncaught ReferenceError: OC is not defined
    at de.js?v=8e528490-35:1:1
theming.js?v=8e528490-35:1  Uncaught ReferenceError: OCA is not defined
    at theming.js?v=8e528490-35:1:1
apps/theming/icon?v=35:1 
        
        
        Failed to load resource: the server responded with a status of 500 (Internal Server Error)
login:1  Error while trying to use the following icon from the Manifest: https://cloud.suelsen.de/index.php/apps/theming/icon?v=35 (Download error or resource isn't a valid image)
login:1  Refused to apply style from 'https://cloud.suelsen.de/apps/dicomviewer/css/sidebar.css?v=db3daece-35' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

**Comment by gmt-it** [comment]
Hi. Found a solution: It was this array in config:
`        "app_install_overwrite": [
            "files_downloadactivity",
            "dicomviewer"
        ],
`

**Comment by kesselb** [comment]
Thanks for letting us know :+1: 

Closing as your problem seems resolved.
