### ISSUE TITLE
[Bug]: Not able to create a copy of a file in the same directory

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#41768]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I have a folder in Files with a file template for a meeting protocol. Every week I copy the file to the same directory to get a new copy. This is no longer possible in 28.

### Steps to reproduce

1. Create a folder
2. Create a file in the folder
3. Click the *Move or copy*

### Expected behavior

The file picker lets me pick the source directory for *Copy*.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ChristophWurst** [comment]
This is likely restricted by https://github.com/nextcloud/server/blob/b3e24a6bf274827fe09c604827d0015cc87f1c6f/apps/files/src/actions/moveOrCopyAction.ts#L147.

**Comment by ChristophWurst** [comment]
As a user I would prefer if *Copy* is still possible to the same directory but it makes sense to *disable* *Move* when source directory = target directory.

**Comment by mehlkopf** [comment]
This is one of the main complaints from my team regarding NC28. Honestly, I would find it way better to just add a dedicated "Duplicate" function that duplicates the file or folder and automatically selects its name to be edited, saving 1-2 steps compared to the Copy/Move function in NC<28. Thank you!
