### ISSUE TITLE
[Bug]: "Every instance of the event must have the same organizer."

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#41767]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Unknown what happens. But there is a recurring error on a production system.

### Steps to reproduce

1. Upload a meeting ics with two organizers

### Expected behavior

No error logged

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Logs

```shell
{
  "reqId": "rDTk3zPi12OFt9vTx1Nk",
  "level": 3,
  "time": "2023-11-27T10:18:50+00:00",
  "remoteAddr": "1:2:3",
  "user": "theuser",
  "app": "webdav",
  "method": "PUT",
  "url": "/remote.php/dav/calendars/theuser/default/abcdefg1234%40google.com.ics",
  "message": "Every instance of the event must have the same organizer.",
  "userAgent": "macOS/14.2 (23C5047e) dataaccessd/1.0",
  "version": "28.0.0.7",
  "exception": {
    "Exception": "Sabre\\VObject\\ITip\\SameOrganizerForAllComponentsException",
    "Message": "Every instance of the event must have the same organizer.",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/3rdparty/sabre/vobject/lib/ITip/Broker.php",
        "line": 195,
        "function": "parseEventInfo",
        "class": "Sabre\\VObject\\ITip\\Broker",
        "type": "->",
        "args": [
          [
            "Sabre\\VObject\\Component\\VCalendar",
            "*** sensitive parameters replaced ***",
            "VCALENDAR"
          ]
        ]
      },
      "..."
    ],
    "File": "/var/www/nextcloud/3rdparty/sabre/vobject/lib/ITip/Broker.php",
    "Line": 847,
    "message": "Every instance of the event must have the same organizer.",
    "exception": {},
    "CustomMessage": "Every instance of the event must have the same organizer."
  }
}
```

**Comment by ChristophWurst** [comment]
The data I inspected always has the same organizer mailto:email value, but occasionally the ORGANIZER property had the attribute `SCHEDULE-AGENT=CLIENT` set.

I'm assuming Sabre always compares the full component, including attributes.

**Comment by ChristophWurst** [comment]
> ### Steps to reproduce
> 
>     1. Upload a meeting ics with two organizers

Adjusted. The ics in the database only has one organizer, but the Sentry body shows that the affected user tries to upload a new version of the ics with a second organizer.

**Comment by st3iny** [comment]
Christoph and I investigated this further. The problem seems to be that Google Calendar writes a separate recurrence instance with another organizer. In this specific case the "new" organizer cancelled one instance of the event (`STATUS:CANCELLED`). However, it is not allowed to have another organizer as the root event.

We should tolerate multiple organizers if the current principal is not an organizer of  any component as no scheduling mails will be sent anyway. Unfortunately, the only code path we control in the stack trace is: `\OCA\DAV\CalDAV\Schedule\Plugin::calendarObjectChange`. The rest is all Sabre code. *Worst case:* We might have to actually patch Sabre.

**Note:** Google is definitely producing an invalid ICS file here.

**Comment by st3iny** [comment]
@gohrner As per the RFCs this is not allowed. Our plan is to remove this restriction if the current user principal is not the organizer.

You don't need to track a new issue as it is the same error.
