### ISSUE TITLE
LDAP Integration - Bind failed: 49: Invalid credentials

### ISSUE THREAD

**Issue by kanudas** [nextcloud/server#4177]
### Steps to reproduce
1. Connect to LDAP Server, Configuration OK. 301 Users found, they show up in User category.
2.Try to log in with a user, using the 'username' displayed in NC
3.Wrong Password shows up and user is rejected, log says Bind failed: 49: Invalid credentials

### Expected behaviour
User should be authenticated and logged in

### Actual behaviour
User is rejected

### Server configuration
**Operating system**:
Ubuntu 12.04.5 LTS
**Web server:**
Apache2
**Database:**
MySql
**PHP version:**
PHP 7.0.15-0ubuntu0.16.04.4
**Nextcloud version:** (see Nextcloud admin page)
11,0,2,7
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
Tar from official website: Nextcloud-11.0.2.tar.bz2
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>
No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

> 

Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - user_ldap: 1.1.2
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - password_policy
  - templateeditor
  - user_saml

> 

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

> {

    "system": {
        "instanceid": "ocqigl38jpv6",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx.xxx.org"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/xxx.xxx.org\/nextcloud",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
}

> 

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP:
Kerberos with LDAP as login agent
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```

```

</details>

> 
+-------------------------------+-------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                 |
+-------------------------------+-------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      |                                                                                     |
| hasPagedResultSupport         |                                                                                     |
| homeFolderNamingRule          |                                                                                     |
| lastJpegPhotoLookup           | 0                                                                                   |
| ldapAgentName                 | cn=ADMIN,dc=ds,dc=local                                                             |
| ldapAgentPassword             | ***                                                                                 |
| ldapAttributesForGroupSearch  |                                                                                     |
| ldapAttributesForUserSearch   |                                                                                     |
| ldapBackupHost                |                                                                                     |
| ldapBackupPort                |                                                                                     |
| ldapBase                      | dc=ds,dc=local                                                                      |
| ldapBaseGroups                | dc=ds,dc=local                                                                      |
| ldapBaseUsers                 | ou=people,dc=ds,dc=local                                                            |
| ldapCacheTTL                  | 600                                                                                 |
| ldapConfigurationActive       | 1                                                                                   |
| ldapDynamicGroupMemberURL     |                                                                                     |
| ldapEmailAttribute            | mail                                                                                |
| ldapExperiencedAdmin          | 0                                                                                   |
| ldapExpertUUIDGroupAttr       |                                                                                     |
| ldapExpertUUIDUserAttr        |                                                                                     |
| ldapExpertUsernameAttr        | uid                                                                                 |
| ldapGroupDisplayName          | cn                                                                                  |
| ldapGroupFilter               | (&(|(objectclass=posixGroup)))                                                      |
| ldapGroupFilterGroups         |                                                                                     |
| ldapGroupFilterMode           | 1                                                                                   |
| ldapGroupFilterObjectclass    | posixGroup                                                                          |
| ldapGroupMemberAssocAttr      | memberUid                                                                           |
| ldapHost                      | teller.ds.local                                                                     |
| ldapIgnoreNamingRules         |                                                                                     |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(uid=%uid))                                         |
| ldapLoginFilterAttributes     |                                                                                     |
| ldapLoginFilterEmail          | 0                                                                                   |
| ldapLoginFilterMode           | 1                                                                                   |
| ldapLoginFilterUsername       | 1                                                                                   |
| ldapNestedGroups              | 1                                                                                   |
| ldapOverrideMainServer        |                                                                                     |
| ldapPagingSize                | 1000                                                                                |
| ldapPort                      | 389                                                                                 |
| ldapQuotaAttribute            |                                                                                     |
| ldapQuotaDefault              |                                                                                     |
| ldapTLS                       | 0                                                                                   |
| ldapUserDisplayName           | cn                                                                                  |
| ldapUserDisplayName2          |                                                                                     |
| ldapUserFilter                | (|(objectclass=inetOrgPerson)(objectclass=krb5Principal)(objectclass=posixAccount)) |
| ldapUserFilterGroups          |                                                                                     |
| ldapUserFilterMode            | 0                                                                                   |
| ldapUserFilterObjectclass     | inetOrgPerson;krb5Principal;posixAccount                                            |
| ldapUuidGroupAttribute        | auto                                                                                |
| ldapUuidUserAttribute         | auto                                                                                |
| turnOffCertCheck              | 1                                                                                   |
| turnOnPasswordChange          | 0                                                                                   |
| useMemberOfToDetectMembership | 1                                                                                   |
+-------------------------------+-------------------------------------------------------------------------------------+
+-------------------------------+--------------+
| Configuration                 | s02          |
+-------------------------------+--------------+
| hasMemberOfFilterSupport      | 0            |
| hasPagedResultSupport         |              |
| homeFolderNamingRule          |              |
| lastJpegPhotoLookup           | 0            |
| ldapAgentName                 |              |
| ldapAgentPassword             | ***          |
| ldapAttributesForGroupSearch  |              |
| ldapAttributesForUserSearch   |              |
| ldapBackupHost                |              |
| ldapBackupPort                |              |
| ldapBase                      |              |
| ldapBaseGroups                |              |
| ldapBaseUsers                 |              |
| ldapCacheTTL                  | 600          |
| ldapConfigurationActive       | 0            |
| ldapDynamicGroupMemberURL     |              |
| ldapEmailAttribute            |              |
| ldapExperiencedAdmin          | 0            |
| ldapExpertUUIDGroupAttr       |              |
| ldapExpertUUIDUserAttr        |              |
| ldapExpertUsernameAttr        |              |
| ldapGroupDisplayName          | cn           |
| ldapGroupFilter               |              |
| ldapGroupFilterGroups         |              |
| ldapGroupFilterMode           | 0            |
| ldapGroupFilterObjectclass    |              |
| ldapGroupMemberAssocAttr      | uniqueMember |
| ldapHost                      |              |
| ldapIgnoreNamingRules         |              |
| ldapLoginFilter               |              |
| ldapLoginFilterAttributes     |              |
| ldapLoginFilterEmail          | 0            |
| ldapLoginFilterMode           | 0            |
| ldapLoginFilterUsername       | 1            |
| ldapNestedGroups              | 0            |
| ldapOverrideMainServer        |              |
| ldapPagingSize                | 500          |
| ldapPort                      |              |
| ldapQuotaAttribute            |              |
| ldapQuotaDefault              |              |
| ldapTLS                       | 0            |
| ldapUserDisplayName           | displayName  |
| ldapUserDisplayName2          |              |
| ldapUserFilter                |              |
| ldapUserFilterGroups          |              |
| ldapUserFilterMode            | 0            |
| ldapUserFilterObjectclass     |              |
| ldapUuidGroupAttribute        | auto         |
| ldapUuidUserAttribute         | auto         |
| turnOffCertCheck              | 0            |
| turnOnPasswordChange          | 0            |
| useMemberOfToDetectMembership | 1            |
+-------------------------------+--------------+

> 

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

> 

Due to personal info and IP's I can't admitt the log. Putting warnings and errors here.
Warning	user_ldap	Bind failed: 49: Invalid credentials
Warning	core	Login failed: 'Username'
Error	index	OC\ServerNotAvailableException: Connection to LDAP server could not be established (This one might have showed up when I was tinkering and is probably not a permanent one)
Error	PHP	ldap_search(): Partial search results returned: Sizelimit exceeded at /var/www/nextcloud/apps/user_ldap/lib/LDAP.php#293
>

**Comment by kanudas** [comment]
Additional info: 

> 

ldapsearch -x -D 'cn=admin,dc=xx,dc=xx' -W -b "" -s base -LLL -H \ ldap://xxx.xxx.xxx/
Enter LDAP Password:
'Output'
> 

I can perform a simple bind to the Ldap server just fine from the linux server that is running NextCloud

**Comment by KB7777** [comment]
@blizzz

**Comment by blizzz** [comment]
>  using the 'username' displayed in NC

You need to use the LDAP uid as specified in your login filter:

>  | ldapLoginFilter | (&(|(objectclass=inetOrgPerson))(uid=%uid)) |

**Comment by kanudas** [comment]
@blizzz 

> 
# randomdude1, people, xx.xx
dn: uid=randomdude1,ou=people,dc=xx,dc=xx
objectClass: inetOrgPerson
objectClass: posixAccount
objectClass: krb5Principal
cn: xxx xxx
givenName: xxx
sn: xxx
uid: randomdude1

> 

This is a user as displayed in LDAP on my Ubuntu LDAP server.
In the case of this user, I'm trying to log in as randomdude1, which should be correct no?

**Comment by blizzz** [comment]
>  In the case of this user, I'm trying to log in as randomdude1, which should be correct no?

Yes. And his correct password. The "invalid credentials" message comes directly from the LDAP sever.

**Comment by kanudas** [comment]
Yes, I can confirm the password is correct. It perhaps appears as the bind to the LDAP server fails?

**Comment by blizzz** [comment]
Possible. Recheck  the ldapAgentName and password. you can see the pw on cli when passing ``--show-password`` as additional parameter to ``occ ldap:show-config``.

**Comment by kanudas** [comment]
Well, the output show the correct user and password. But the LDAP system should allow for anonymous acccess.

**Comment by kanudas** [comment]
Yes, and if I do leave it empty the error is the same.

**Comment by blizzz** [comment]
What does ``occ ldap:test-config s01`` return?

Is the uid unique within your user base tree?

**Comment by kanudas** [comment]
/var/www/nextcloud$ sudo -u  www-data php occ ldap:test-config s01

The configuration is valid and the connection could be established!

Yes, the UID of a user in LDAP is unique

**Comment by blizzz** [comment]
Repeat https://github.com/nextcloud/server/issues/4177#issuecomment-290917563 with the DN from randomdude1  and its password?

**Comment by kanudas** [comment]
> 

ldapsearch -x -D 'uid=randomdude1,dc=xx,dc=xx' -W -b "" -s base -LLL -H \ ldap://xxx.xxx.xxx/
Enter LDAP Password:
ldap_bind: Invalid credentials (49)

> 

-D binddn  bind DN
But randomdude1 don't have access to the LDAP files, and the uid specified after the "-D" option should be an LDAPAdmin or a user with the sole purpose of reading the LDAP files no?
Anyway, I still can't log into NC with Admin.

**Comment by blizzz** [comment]
Yes, he does. When the user wants to login, it authenticates at LDAP by binding. That's the only way to verify that the credentials match (and is not blocked by LDAP etc.).

**Comment by kanudas** [comment]
Hmm, I will look at that. But shouldnt I be able to log in with admin then?

**Comment by blizzz** [comment]
If belongs to the ldapBaseUsers tree. With configuration is written above, login would be denied, because his DN is not within the configured tree.

**Comment by kanudas** [comment]
Hmm, that seems reasonable. What configuration should I change to make authentication possible for a user then? The connection seems fine and for other machines running LDAP auth using SASL and similar config in their application works. I seem to have missed something here. 
Here's a capture of a user in LDAP.
![asd](https://cloud.githubusercontent.com/assets/26821252/24650983/5bd002d0-192c-11e7-8dd6-a7821749f32f.JPG)

**Comment by blizzz** [comment]
Any user who should be able to login, must be able to perform a bind against the LDAP server from the server Nextcloud is running on.

Please head over to http://help.nextcloud.com/ for help.

**Comment by kanudas** [comment]
Is there any way to force nextcloud to use SASL against the LDAP server?

**Comment by kanudas** [comment]
@blizzz 
As stated earlier, this bind using simple authentication:  ldapsearch -x -D 'uid=randomdude1,dc=xx,dc=xx' -W -b "" -s base -LLL -H \ ldap://xxx.xxx.xxx/.
Returns "Invalid Credentials".

However, this bind:  ldapsearch -I -D 'uid=randomdude1,dc=xx,dc=xx' -W -b "" -s base -LLL -H \ ldap://xxx.xxx.xxx/.
Returns a succesful bind and search.

Can I make nextcloud use sasl instead of simple authentication when binding?

**Comment by blizzz** [comment]
> Can I make nextcloud use sasl instead of simple authentication when binding?

No, we only support simble auth. Again, please head over to http://help.nextcloud.com/ for help. Please understand, this is a bug tracker here, not a support platform.

**Comment by guymass** [comment]
I have the same issue, my ldap was working fine until we updated the server, I currently no sure why it will not bind as everything is as it was.  Here are my configs and the error message I get:

![Screen Shot 5781-09-23 at 14 45 48](https://user-images.githubusercontent.com/58882903/120640219-e0b5d800-c47a-11eb-8029-c72eccf9bc96.jpg)
![Screen Shot 5781-09-23 at 14 45 35](https://user-images.githubusercontent.com/58882903/120640238-e4e1f580-c47a-11eb-841d-756bb1d6e701.jpg)
![Screen Shot 5781-09-23 at 14 04 50](https://user-images.githubusercontent.com/58882903/120640263-ee6b5d80-c47a-11eb-8167-7d33363df27f.jpg)

Please I cannot access my cloud not even with the original admin account, i am not sure what is going on here and would appreciate any insight.

**Comment by guymass** [comment]
If I search for a user I get a replay but if I try to check-user or reset-user I get errors. not sure what has changed.

![Screen Shot 5781-09-23 at 17 53 05](https://user-images.githubusercontent.com/58882903/120665764-be30b880-c494-11eb-88a4-9e66e45cdc1c.jpg)

**Comment by jlfranklin** [comment]
@guymass -

Can you query the LDAP server directly and get the dn and userPassword of test528?  The command will look like what's below.  

```
ldapsearch -H ldapi:/// -D <admin DN> -W -b dc=example,dc=org -s sub "(uid=test528)" dn userPassword
```
Use those two values to produce a `test-fix.ldif` file.  Note the double colon on the userPassword line.  If the ldapsearch returns `userPassword:: <long base64 string>`, then do the same in the `test-fix.ldif`. 

```
dn: <dn of user test528>
changetype: modify
replace: userPassword
userPassword:: <the userPassword returned from the ldapsearch.>
```

Then use that to "reset" the user's password. 

```
ldapmodify -H ldapi:/// -D <admin DN> -W -f ./test-fix.ldif
```

(Add `-x` to both commands if you use simple auth instead of SASL.)

Yes, this "resets" the password to exactly what it was before.  I have to do this with Nextcloud 21.x to restore my own account on a near daily basis.  Part of NC21's performance improvements include DoS'ing itself and overloading the LDAP server.  Simply restarting `slapd` doesn't fix it.  `ldapmodify` the account with the same password does.

**Comment by guymass** [comment]
Thank you very much @jlfranklin for your help. I followed your steps and was able to get the password and made the test-fix.ldif. Now I see this error when trying to login.

![Screen Shot 5781-09-27 at 1 44 57](https://user-images.githubusercontent.com/58882903/120942503-07516880-c732-11eb-957b-d206613e2886.jpg)

**Comment by guymass** [comment]
Now I get no errors and no login but this works suddenly for me without adding the ou=

![Screen Shot 5781-09-27 at 2 15 26](https://user-images.githubusercontent.com/58882903/120943284-a8dab900-c736-11eb-840b-07fba6d05af5.jpg)

**Comment by guymass** [comment]
It seems that my issue might be ldap_write_support not compatible with the new Nextcloud upgrade 20.0.2. I have opened an issue on their git and hopefully there will be an update for it. MY cloud is currently down till its fixed :(

**Comment by guymass** [comment]
OK I have now version 21.0.2.1 and seems that now it is trying to do something but still I cannot login. This could be my own configuration though.

![Screen Shot 5781-09-27 at 23 46 30](https://user-images.githubusercontent.com/58882903/121085643-d08b5900-c7ea-11eb-8a7e-bfd4c008dd22.jpg)

and I only have a single "s01" config for ldap:

![Screen Shot 5781-09-27 at 23 49 22](https://user-images.githubusercontent.com/58882903/121085832-0597ab80-c7eb-11eb-9e54-73657989baf3.jpg)

![Screen Shot 5781-09-27 at 23 49 13](https://user-images.githubusercontent.com/58882903/121085820-029cbb00-c7eb-11eb-9005-a422da502b6b.jpg)

**Comment by cmdrogogov** [comment]
I am experiencing this issue, but it's only affecting the sync clients.

I can bind to the LDAP server just fine, i can login via LDAP credentials with no errors being generated on the web UI.

However using the android or linux desktop clients immediately results in err 49 spam and shortly thereafter the DS will lock the account.

**Comment by NextClaus** [comment]
Although the root cause may differ, we had the same log entries, namely:
[user_ldap] Warning: Bind failed: 49: Invalid credentials

The "fix" was a lot easier than expected (check the "logon to" AD attribute!):
https://help.nextcloud.com/t/solved-50-ldap-auth-ms-ad-wrong-password/28347/7
