### ISSUE TITLE
[Bug]: Button icons missing in move/copy modal

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#41770]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![image](https://github.com/nextcloud/server/assets/1374172/2fabe4d5-5e3a-4e2f-93cc-a76a3e532d7c)

### Steps to reproduce

1. Open Files
2. Click *...* on a file
3. Click *Move or copy*
4. Look at the buttons of the file picker

### Expected behavior

Icons instead of whitespace, or no whitespace

### Installation method

None

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

cc @susnux for the file picker

**Comment by susnux** [comment]
> Nextcloud Server version
> 26

I guess you meant 28, as the FilePicker was new to 27.1
Nevertheless this is already fixed with https://github.com/nextcloud/server/pull/41707 and https://github.com/nextcloud/server/pull/41715
