### ISSUE TITLE
[Bug]: awaitForShare: TypeError: n is undefined

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#41773]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

```
TypeError: n is undefined
    awaitForShare SharingTab.vue:385
    VueJS 9
    saveShare SharingDetailsTab.vue:828
``` 

### Steps to reproduce

1. Create a file
2. Share it with another user
3. Open the console

### Expected behavior

No errors

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

cc @Fenn-CS

**Comment by vadhavana** [comment]
Hi There, how can I change the nextcloud version from latest to 28? 
I am just checking the code and trying to reproduce it.

**Comment by ChristophWurst** [comment]
28 is under development. you can use a git checkout of this repo and the branch stable28

**Comment by vadhavana** [comment]
Hi @ChristophWurst, I checked out branch stable28, but how to run it using docker command or npm run?

**Comment by ChristophWurst** [comment]
I can not support you on that. Try https://nextcloud.com/developer/ or https://docs.nextcloud.com/server/latest/developer_manual/.
