### ISSUE TITLE
[Bug]: Not possible change cursor or focus of file name by mouse on Firefox

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#41772]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On Firefox, I can no longer click into the name input to change a specific part of a file name. It always selects the full name.

### Steps to reproduce

1. Upload/create a file
2. Click *...*
3. Click *Rename*
4. Try to move to a specific part of the name with the mouse

### Expected behavior

![image](https://github.com/nextcloud/server/assets/1374172/3d993948-4f79-4904-83d9-5fc04955b0b9)

https://github.com/nextcloud/server/assets/1374172/6a0a2e92-9110-4298-85f6-6035cd0f76d9

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ChristophWurst** [comment]
@st3iny has it to and noticed that you can also no drag a selection inside the input. If you try, it triggers the drag and drop handlers.

1) Create a file
2) Try to mark the first three letters

Expected: first free letters are selected
Actual: file is dragged

**Comment by nook24** [comment]
Same for new folders, it is strangely hard (or even impossible?) to rename new folders while creating

https://github.com/nextcloud/server/assets/9019992/2246a5d2-633e-49da-9426-487ff8392f98
