### ISSUE TITLE
Creating New Calendar in NextCloud does not function

### ISSUE THREAD

**Issue by whacky98** [nextcloud/server#4178]
### Steps to reproduce
1.  Click New Calendar
2.  Type Name
3.  Click Create
4.  Fails to Create

### Expected behaviour
When Creating a calandar it should let me create it.

### Actual behaviour
I have tested both Owncloud and Nextcloud the feature I am excited about is the calendar app but I have installed seems to work find under both with one exception.  When I try to click new calendar type a name and click create nothing happens.  The personal calendar seems to work but I want to create a shared calendar seperate from the personal calendar.  When I look at the logs this is what I see.

### Server configuration
**Operating system**:

Ubuntu 16.10 Server

**Web server:**

**Database:**

Type: sqlite3

**PHP version:**

Version: 7.0.15

**Nextcloud version:** (see Nextcloud admin page)

11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

Command line downloaded newest from github

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:**  none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here

Fatal	webdav	Sabre\DAV\Exception\InvalidResourceType: HTTP/1.1 403 You can only create calendars and subscriptions in this collection	2017-03-31T10:54:40-0600

	Sabre\DAV\Exception\InvalidResourceType: HTTP/1.1 403 You can only create calendars and subscriptions in this collection

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1173: Sabre\CalDAV\CalendarHome->createExtendedCollection('test', Object(Sabre\DAV\MkCol))
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 590: Sabre\DAV\Server->createCollection('calendars/chris...', Object(Sabre\DAV\MkCol))
    [internal function] Sabre\DAV\CorePlugin->httpMkcol(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method MKCOL', Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/apps/dav/lib/Server.php - line 227: Sabre\DAV\Server->exec()
    /var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 30: OCA\DAV\Server->exec()
    /var/www/nextcloud/remote.php - line 165: require_once('/var/www/nextcl...')
    {main}

</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by ChristophWurst** [comment]
cc @nextcloud/calendar

**Comment by georgehrke** [comment]
@whacky98 Please use the entire prefilled issue template

**Comment by MorrisJobke** [comment]
No feedback since 5 months: closing
