### ISSUE TITLE
[Bug]: "2 new comments" but no comments

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#41791]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

| List | Sidebar |
|--------|--------|
| ![Bildschirmfoto vom 2023-11-28 10-51-44](https://github.com/nextcloud/server/assets/1374172/01a6589d-7426-4567-b68d-e4cf3d462ae0) | ![Bildschirmfoto vom 2023-11-28 10-51-58](https://github.com/nextcloud/server/assets/1374172/40b4f72d-da8c-40d6-bd0b-c2a9804940b5) | 

### Steps to reproduce

1. ?

I don't know because this is an old file.

### Expected behavior

Either no notification for comments or show me the comments.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ChristophWurst** [comment]
I found other old files where comments do show up

**Comment by susnux** [comment]
Could you please look in your browser dev tools / network tab for a `REPORT` request like `/remote.php/dav/comments/files/NUMBERS`?

If there is no such request then something is fishy in the comments app, otherwise a activity issue.

And please check if the response is empty or not (best case provide the response)
