### ISSUE TITLE
On SSL-secured server, linkToRoute returns http instead of https iframes, violating CSP and preventing iframes from loading, hindering functionality

### ISSUE THREAD

**Issue by SentToDevNull** [nextcloud/server#4180]
I believe this to be an issue with "nextcloud/core/lib/private/URLGenerator.php", which may have been wrongly reported as issue 338 in the "mail" app repo.

### Steps to reproduce
1. Have an SSL-secured nextcloud instance.
2. Install a nextcloud app that returns an iframe within a page, such as "Mail" from the app store.
3. For example, with the "Mail" app, try viewing an HTML (as opposed to plaintext) email (since those are returned as iframes, not text blocks).
4. Watch while the iframe never loads because the CSP prevented it from being shown.
(5. Optional: Confirm that it is a CSP-related problem by inspecting the iframe element with your browser and changing the "http" url referenced to "https". Watch the iframe now load.)

### Expected behaviour
The iframe should load. 

### Actual behaviour
Iframes will not load.

### Possible Fix
On https-enabled servers, linkToRoute should output https links, and it should only output http links on non-https servers.

### Server configuration
**Operating system**: Debian GNU/Linux 8.7 

**Web server:** Apache/2.4.10 (Debian)

**Database:** mysql  Ver 14.14 Distrib 5.5.54, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:** PHP 5.6.30-0+deb8u1

**Nextcloud version:** 11.0.2 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** the latest stable tarball on the nextcloud website

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - admin_notifications: 1.0.0
  - apporder: 0.3.3
  - audioplayer: 1.4.1
  - bookmarks: 0.9.1
  - calendar: 1.5.2
  - checksum: 0.3.4
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - direct_menu: 0.10.1
  - external: true
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_downloadactivity: 1.0.1
  - files_markdown: 1.0.1
  - files_pdfviewer: 1.0.1
  - files_reader: 1.0.3
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - news: 10.1.0
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - ocsms: 1.11.5
  - ojsxc: 3.1.1
  - onlyoffice: 1.0.1
  - ownbackup: 17.3.0
  - passman: 2.1.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocvvew734xze",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.mydomain.com"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/www.mydomain.com\/nextcloud",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Webdav

#### Web server error log
<details>
<summary>Web server error log</summary>
Sadly, nothing related to this shows up in the error log. The only errors are those from the "news" app not finding one of my news feeds.
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Sadly, nothing related to this shows up in this error log either. Still, the only errors are those from the "news" app not finding one of my news feeds.
</details>

**Comment by ChristophWurst** [comment]
> "overwrite.cli.url": "http:\/\/www.mydomain.com\/nextcloud",

Not sure if this URL is used in the URL generator, but this should be HTTPS too 😉 

Did you follow the instructions on https://docs.nextcloud.com/server/11/admin_manual/configuration_server/reverse_proxy_configuration.html? I don't see any proxy-related entries in your config.

**Comment by SentToDevNull** [comment]
@ChristophWurst adding `'overwriteprotocol' => 'https',` to nextcloud/config/config.conf made all the difference. Thanks. I'll try to contact the dev in charge of the mail app and let him/her know that a reverse proxy is necessary for the app to work properly.

**Comment by ChristophWurst** [comment]
> I'll try to contact the dev in charge of the mail app and let him/her know that a reverse proxy is necessary for the app to work properly.

Yeah, well. I guess that's me 🙈 

Great to hear it's working now!
