### ISSUE TITLE
Improve performance of PDF previews in sidebar for large PDFs

### ISSUE THREAD

**Issue by TomFernandes** [nextcloud/server#4181]
### Steps to reproduce
1. Upload a PDF ca. 100MB of size
2. Click on the sharing icon on the right side of the filename
3. The sharing dialog opens on the right side
4. Wait

### Expected behaviour
There should be a preview of the file shown instantly in the upper right corner of the sharing dialog.

### Actual behaviour
The preview of the PDF is not shown and the right top corner of the sharing dialog is empty (white) for a couple of minutes or so. After some minutes the preview is (usually?) shown.
If I want to share a folder, the folder icon is shown in the upper right corner of the sharing dialog (which is fine). The sharing-dialog-preview works fast for simple text files. But even for a small PDF (33K) it takes around 5s to show the sharing-dialog-preview. Until the sharing-dialog-preview is shown, that place is empty (white).

This looks broken to me. Having an icon there for folders or a working preview for text files but no (reliable) preview or icon for PDFs is not consistent. If the preview is not working properly (fast), there should be an option to disable the sharing-dialog-preview altogether or substitute the preview-picture with just an icon. I can't find an option though.

### Server configuration
**Operating system**: Debian Jessie

**Web server:** 1.6.2

**Database:** PostgreSQL 9.4.10

**PHP version:** 5.6.30

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from oC 8.2.X

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - admin_audit: 1.1.0
  - calendar: 1.5.2
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_videoplayer: 1.0.0
  - gallery: 16.0.0
  - impersonate: 0.0.5
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - user_ldap: 1.1.2
  - workflowengine: 1.1.1
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
$CONFIG = array (
  'instanceid' => 'HIDDEN',
  'passwordsalt' => 'HIDDEN',
  'secret' => 'HIDDEN',
  'trusted_domains' =>
  array (
    0 => 'example.com',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'overwrite.cli.url' => 'https://example.com',
  'dbtype' => 'pgsql',
  'version' => '11.0.2.7',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => 'HIDDEN',
  'installed' => true,
  'theme' => '',
  'loglevel' => 2,
  'logfile' => '/var/log/nextcloud.log',
  'maintenance' => false,
  'logtimezone' => 'Europe/Berlin',
  'trashbin_retention_obligation' => '5',
  'default_language' => 'de',
  'lost_password_link' => 'https://example.com/xyz',
  'memcache.local' => '\OC\Memcache\APCu',
  'mail_from_address' => 'support@example.com',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'example.com',
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => 'mail.example.com',
  'mail_smtpport' => '25',
  'mail_smtpauthtype' => 'PLAIN',
  'enable_previews' => false,
  'updater.release.channel' => 'stable',
  'updater.server.url' => 'https://updates.nextcloud.com/updater_server/',
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
```
</details>

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Firefox 52.0.1 and Chromium 57.0.2987.98 

**Operating system:** Debian Testing

### Logs
No relevant Logs from Nginx, PHP or Nextcloud AFAICS

**Comment by MorrisJobke** [comment]
Currently it loads the full PDF and shows it inline. @icewind1991 Any plans to enhance this somehow?

**Comment by TomFernandes** [comment]
A user reported that PDF previews are generated "quite fast" with PDFs of around 100MB size with NC 13.0.3.
