### ISSUE TITLE
[BITV] 9.1.1.1c/4.1 - The user interface elements of the image editor on the left side and at the bottom of the page contain images (SVG elements) that have not been hidden using the "aria-hidden" attribute.  (1)

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#41825]
This results in the screen reader announcing them with the role of "image" but without alternative text.

https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-3a2875951a-v4-n1

![image](https://github.com/nextcloud/server/assets/6078378/843e383d-2ec7-42d8-b651-4cb780cd32c9)

**Comment by ShGKme** [comment]
The issue is located in the viewer which uses external library `filerobot-image-editor` for the editor.

**Comment by JuliaKirschenheuter** [comment]
closing as not relevant anymore
