### ISSUE TITLE
irritating name for system version

### ISSUE THREAD

**Issue by cal940** [nextcloud/server#4182]
Expected: System name always the same (Nextcloud)

Actual: System name depends on the title of the Nextcloud Instance (e.g. CSinA Cloud)
![](http://i.imgur.com/UVRTkgd.jpg)

**Comment by MorrisJobke** [comment]
cc @karlitschek @LukasReschke @juliushaertl Is this intended for the theming?

**Comment by karlitschek** [comment]
This is the intended behavior. If you do branding/theming  then the name 'Nextcloud' is completely invisible.

**Comment by MorrisJobke** [comment]
Right - and there is the Copyright notice just below which says: "Developed by the Nextcloud community, ..." 😉
