### ISSUE TITLE
[BITV] 9.1.3.1a/6.2 - The headings "Profile picture" and "Profile" have been incorrectly implemented as "label" elements instead of headings - e.g. <label data-v-117e8ad0="">Profile</label>. (1)

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#41827]
e.g. `<label data-v-117e8ad0="">Profile</label>.`

https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-be75bbae42-v6-n2

**Comment by Pytal** [comment]
This is done no @JuliaKirschenheuter? Why is this in Parked?

**Comment by ShGKme** [comment]
> This is done no @JuliaKirschenheuter? Why is this in Parked?

Backport was merged just recently, now it can be in done indeed
