### ISSUE TITLE
[BITV] 9.1.1.1a/9.2 - When switching the page to German language, the labels of submit buttons are not consistently labeled. In one case, the label is "Einreichen" and in others, it is "Übermitteln". (1)

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#41823]
**_Need info from Michael_**

https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-cd239865a5-v9-n2

**Comment by ShGKme** [comment]
- `Einreichen` is a "Submit" translation in `@nextcloud/vue`
- `Übermitteln` is a "Submit" translation in `server` (all apps)
