### ISSUE TITLE
[BITV] 9.1.3.1b/5.1 - The "Search" window includes lists, with each of these lists having a heading. However, these headings have been implemented as direct children of the <ul> element, which is not allowed and can lead to issues with screen reader output. (2)

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#41830]
https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-1d5eadb58d-v5-n1

9.1.3.1b/8.1 - https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-1d5eadb58d-v8-n1

![image](https://github.com/nextcloud/server/assets/6078378/a84f8aeb-f429-46e8-9d5d-fdcacfc4be38)

**Comment by ShGKme** [comment]
> Why should it be an issue for screen reader if a h tag is used within ul? examples?

See element specification: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul
