### ISSUE TITLE
[BITV] 9.1.4.1/8.1 - NcTimezonePicker group headings / continents groupings do not meet contrast ratio (1.1:1 instead of the 3:1 contrast ratio that is required)

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#41842]
![image](https://github.com/nextcloud/server/assets/6078378/678dc598-80b9-4e1b-ac51-6ed942bd55d6)

https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-45ae33ca9f-v8-n1

The headers / Continent of the grouped areas in the NcTimezonePicker are visually marked by a light gray background (1,1:1 to white) and remain below the contrast ratio of 3:1 that is needed to indicate the state visually.

**Comment by susnux** [comment]
This is not the active element but a "heading" to group the timezones by continents. 

cc @JuliaKirschenheuter

**Comment by JuliaKirschenheuter** [comment]
From design channel: 
If we would just remove the groups then we would have a problem with ambiguous regions. e.g. /Eastern https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

we could also flatten the structure to Europe/Berlin and remove all groups.
@susnux would you say it is a easy way?

**Comment by susnux** [comment]
My idea was to either have two boxes or to allow to select regions for filtering. E.g. `Europe` and then you can select the zone e.g. `Berlin` within the same box.
While still allowing to select `Europe/Berlin` directly.

**Comment by susnux** [comment]
>  If we would just remove the groups then we would have a problem with ambiguous regions. e.g. /Eastern https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

Need to check if we even provide them, they are only in the legacy timezone db.

**Comment by szaimen** [comment]
The main thing seems to happen here: https://github.com/nextcloud-libraries/nextcloud-vue/blob/efb3b9d08c9ca01e2d0ba0b5344437eec0b50704/src/components/NcTimezonePicker/NcTimezonePicker.vue#L113-L129

**Comment by szaimen** [comment]
And here: https://github.com/nextcloud-libraries/nextcloud-vue/blob/efb3b9d08c9ca01e2d0ba0b5344437eec0b50704/src/components/NcTimezonePicker/timezone.js#L30-L53

**Comment by emoral435** [comment]
Editing the title of the issue to be more descriptive and moving some of the descriptions to the description section

**Comment by susnux** [comment]
@emoral435 simply removing the grouping is enough for the moment, meaning remove the headers should work for the moment :)

**Comment by emoral435** [comment]
@susnux Gotcha, will move forward with that choice then! Thank you :) 🚀

**Comment by emoral435** [comment]
dependency update happening in the library that affects this issue in https://github.com/nextcloud-libraries/nextcloud-vue/pull/5130

**Comment by JuliaKirschenheuter** [comment]
@emoral435 please check in which NcVue version is your PR available

**Comment by emoral435** [comment]
Ah - I got confused on which NcVue version this PR was in, I thought it was for 8.4.0! This one is ready for the a11y28check once https://github.com/nextcloud/server/pull/43064 gets merged!
