### ISSUE TITLE
OCC commands fail when configuring apps_paths

### ISSUE THREAD

**Issue by ThomasLeister** [nextcloud/server#4184]
### Steps to reproduce
1. Install NextCloud 
2. Set apps_paths in config.php via occ config:system:set command:
```php occ config:system:set apps_paths 0 path --value=/var/www/nextcloud/apps --type=string```
4. Set the second parameter 'url': 
```php occ config:system:set apps_paths 0 url --value=/apps --type=string```

### Expected behaviour
Second configuration command should be accepted without any error.

### Actual behaviour
After the first command has been issued, any further commands will fail with error: 
```apps directory not found! Please put the Nextcloud apps folder in the Nextcloud folder or the folder above. You can also configure the location in the config.php file.```

**Configuration cannot be completed with this series of occ commands.** This is probably because the configuration is incomplete after the first command. On the second command config check fails because of incomplete config.

### Server configuration
**Operating system**: Alpine Linux

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.1.2

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Official Nextcloud Website / manually

**List of activated apps:**
<details>
<summary>App list</summary>

```
[Default activated apps]
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'passwordsalt' => 'salt',
  'secret' => 'secret',
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => 'nextcloud.localhost.local',
  ),
  'datadirectory' => '/var/nextcloud/data',
  'overwrite.cli.url' => 'https://nextcloud.localhost.local',
  'dbtype' => 'mysql',
  'version' => '11.0.2.7',
  'dbname' => 'nextcloud',
  'dbhost' => 'db',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_thomas',
  'dbpassword' => 'pass',
  'logtimezone' => 'UTC',
  'installed' => true,
  'instanceid' => 'oczy137ivn5d',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'redis',
    'port' => 6379,
  ),
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'nextcloud',
  'mail_domain' => 'domain.tld',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.domain.tld',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'nextcloud@domain.tld',
  'mail_smtppassword' => 'pass',
  'upgrade.disable-web' => true,
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/nextcloud/apps',
    ),
  ),
);
```
</details>

**Are you using external storage, if yes which one:** No external storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
[empty]
```
</details>

**Comment by MorrisJobke** [comment]
cc @nickvergessen Supported or not supported?

**Comment by nickvergessen** [comment]
I'd say not supported, the problem is you have a wrongly configured app dir on the second call, no way to work around this.

But I think the import method should work here.

**Comment by MorrisJobke** [comment]
Okay - as of now configuring the app paths via the occ command is not supported, because it is a multi config option configuration.

**Comment by Peter2121** [comment]
It is not clear if with the modifications related to #9708, #32511 and #11239 it is possible to set apps_path using occ command. Please, update the status of this ticket.
Anyway, I cannot do it using the syntax mentioned in the documentation. If it should work - I'll open a new ticket.
