### ISSUE TITLE
Preview for files in portrait mode does not fit on the screen

### ISSUE THREAD

**Issue by andreasnuesslein** [nextcloud/server#41843]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When sharing images or videos publicly there is a preview of said media. The preview however doesn't fit on the screen if it's in portrait mode. 

![image](https://github.com/nextcloud/server/assets/320080/de0badbc-f482-403b-a90f-a9e78a9faed5)

**Describe the solution you'd like**
I think it would be good if the preview would always fit onto the screen without scrolling.

**Describe alternatives you've considered**
I checked if there was a config-option for it but couldn't find any. I saw [this](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#previews)  but it didnt seem to apply to the preview window for these public shares.

Cheers! :wave:

**Comment by skjnldsv** [comment]
Fixed on 31
