### ISSUE TITLE
TXT preview is not refreshed

### ISSUE THREAD

**Issue by HuidaeCho** [nextcloud/server#4185]
### Steps to reproduce
1. Create a text file with any content and exit the editor
2. A new preview is created using the current content
3. Edit the same text file and exit the editor
4. The preview is not refreshed

### Expected behaviour
The preview should be updated with new contents.

### Actual behaviour
Once the preview is created from the first version of a text file, it's not refreshed.

### Server configuration
**Operating system**: Linux Slackware 14.2

**Web server:** Apache 2.4.20

**Database:** PostgreSQL 9.4.4

**PHP version:** 5.6.23

**Nextcloud version:** (see Nextcloud admin page) 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
</details>

### Client configuration
**Browser:** Firefox 52.0.2

**Operating system:** Windows 7, Linux Slackware 14.2

#### Web server error log
<details>
<summary>Web server error log</summary>
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
</details>

#### Browser log
<details>
<summary>Browser log</summary>
</details>

**Comment by rullzer** [comment]
I can reproduce. It seems the edit doesn't trigger the purging of the previews. I'll look into this.

**Comment by rullzer** [comment]
Ah got it. The texteditor does not trigger it never triggers the initialisation of the hooks...

**Comment by rullzer** [comment]
Fix in https://github.com/nextcloud/files_texteditor/pull/33
