### ISSUE TITLE
[BITV] 9.1.4.4/0.1 - Note: For the review, the browser window size of 1280x768 px and a 200% zoom magnification was used. (1)

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#41851]
**?? have to be clarified**

https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-c41a0aed27-v0-n1

**Comment by ShGKme** [comment]
Same as #41847, it seems to be a general note, not an issue

**Comment by JuliaKirschenheuter** [comment]
https://github.com/nextcloud/server/issues/41851#issuecomment-1832799590
