### ISSUE TITLE
Desktop client - service unavailable - 11.0.2

### ISSUE THREAD

**Issue by MarcoWilli** [nextcloud/server#4187]
Newly installed the win desktop client since I updated from old owncloud to new nextcloud 11.0.2 a few days ago.
Since it throws an "server replied: service unavailable" I guess it´s a server problem?!

Client log here:
https://pastebin.com/iYVzMcHS

Nextcloud 11.0.2
PHP 5.6
All-inkl.com webhosting
Https

Using mainly for contacts and calender together with Thunderbird and davDroid without problems.

Kind regards

**Comment by MorrisJobke** [comment]
cc @rullzer @pfiff45

**Comment by MarcoWilli** [comment]
Resolved by completely new instance of nextcloud and migrating the data.
It had to do with "broken" encryption that I used before and disabled it but updated version complained about it in the log.
