### ISSUE TITLE
[BITV] 9.2.4.3/3.3 - When opening the "Details" section through the "Actions" menu in the table, the keyboard focus is not shifted to the details view; instead, it is moved to the beginning of the next row of the table. (1)

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#41877]
https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-89806fe784-v3-n3

**Comment by ShGKme** [comment]
What is not clear to me:
- Should the sidebar be focused when it automatically opened on page load?
- Should the sidebar be focused when it was already opened but another tab has been chosen?
- Should the sidebar be focused when it was already opened but a new file/app was chosen?

**Comment by JuliaKirschenheuter** [comment]
Agree with all your points from your video

**Comment by JuliaKirschenheuter** [comment]
closing as done

**Comment by szaimen** [comment]
This is apparently broken again on stable28 😢

https://github.com/nextcloud/server/assets/42591237/eeacedbd-4782-4703-b89f-86db6c719223

**Comment by szaimen** [comment]
I opened https://github.com/nextcloud/server/issues/43477 for this. The issue here is working.
