### ISSUE TITLE
[BITV] 9.2.4.7/3.1 - In the "Details" section under the "Activity" tab, it is possible to open a dropdown list when entering "@", ":" or "/" into the textbox (2)

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#41879]
..., for example, to select from a list of emojis. 

- [x] When navigating through the elements in these lists using the keyboard, the keyboard focus is poorly distinguishable.
- [x] The contrast ratio between the focused and unfocused states is below 3:1.
- [x] Input filed have to be discoverable (increase a border color)
    - https://github.com/nextcloud-libraries/nextcloud-vue/pull/4975

https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-91f2646afa-v3-n1

**_Blocked by https://github.com/nextcloud/server/issues/41896_**

9.2.4.7/11.1 - https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-91f2646afa-v11-n1

**Comment by JuliaKirschenheuter** [comment]
> stop this spam!

could you please explain your point?

**Comment by JuliaKirschenheuter** [comment]
closing as done

**Comment by JuliaKirschenheuter** [comment]
no "pending dependency update" anymore. Closing issue

**Comment by szaimen** [comment]
Seems to work but the smart picker seems to be broken 😢

https://github.com/nextcloud/server/assets/42591237/3ca2c572-2bbb-4fdd-9623-efa367ef2ff5

**Comment by szaimen** [comment]
The issue here seems to work
