### ISSUE TITLE
[BITV] 9.2.4.3/3.2 - When the "New folder" menu item is activated, a new row is created in the table with the "New folder" input field. (2)

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#41876]
However, the keyboard focus is not moved to the input field; it remains on the menu item. To change the folder name, a user has to navigate through all the other elements on the page. 

![image](https://github.com/nextcloud/server/assets/6078378/22acabd1-d0e5-4e6f-b07c-09dabb0f51de)

https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-89806fe784-v3-n2

9.2.4.3/11.2 - https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-89806fe784-v11-n2

**Comment by ShGKme** [comment]
Backport required
