### ISSUE TITLE
Sharing function cant disable "Expiry Date"

### ISSUE THREAD

**Issue by corincorvus** [nextcloud/server#41871]
### Steps to reproduce
1. Create a Folder
2. Share this Folder
3. Expiry Date is already marked, i cant disable it

### Expected behavior 
i can disable expiry date
(Example on Native Installation without Docker)
![image](https://github.com/nextcloud/all-in-one/assets/21257329/2a6f85f1-8a43-448c-9945-b7bc92a01168)

### Actual behavior 
I cant unmark expiry date

I click un the checkbox, date went to tt.mm.jjjj, i save
![image](https://github.com/nextcloud/all-in-one/assets/21257329/8b1875de-d215-49f7-8a38-2251a6899435)

After Save the Date is set:
![image](https://github.com/nextcloud/all-in-one/assets/21257329/4d126203-0e2c-47f2-97a1-e08384c30428)

I remove it again to tt.mm.jjjj with click on checkbox and save, after check i see 01.01.1970
![image](https://github.com/nextcloud/all-in-one/assets/21257329/39a7a37f-9250-4453-aeb0-dbda68bcc4c6)

### Host OS 
Debian

#### Nextcloud AIO version 
Nextcloud AIO v7.7.0

#### Current channel 
Stable

#### Other valuable info 
Nothing special in Logs

I already tried:
Disable and Re-enable Share API
Enable and disable Default Expiry Date (nothing works)
Restart Containers
Rebuild Containers

**Comment by szaimen** [comment]
Should be fixed with 27.1.4 afaik
