### ISSUE TITLE
[BITV] 9.3.1.1/1.1 - Even though the page is in English, the "lang" attribute is set to the value for the German language, which leads to incorrect screen reader output (1)

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#41881]
output - <html class="ng-csp" data-placeholder-focus="false" lang="de-DE" data-locale="de_DE" translate="no">. 

https://report.bitvtest.de/default-en/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-92f1119819-v1-n1

**Comment by ShGKme** [comment]
The page is in German. However, the most important part - the Login form is not translated.

The login page only has translations for the "theming" app, but the login form is translated as a part of the "core" app.

![image](https://github.com/nextcloud/server/assets/25978914/8e45a750-412e-4df8-890c-66de0985b343)

![image](https://github.com/nextcloud/server/assets/25978914/45001e33-892f-43e9-95e4-172aaca38be0)

**Comment by ShGKme** [comment]
Waiting for a backport to stable28
