### ISSUE TITLE
admin_audit should log group creation/deletion

### ISSUE THREAD

**Issue by GitHubUser4234** [nextcloud/server#4190]
Hi,

For some use cases, it would be useful to have audit logs of group creation and deletion. The `postCreate` and `postDelete` hooks are already there, they just need to be hooked in. Thank you.

**Comment by MorrisJobke** [comment]
cc @ChristophWurst @Ivansss @pfiff45

**Comment by GitHubUser4234** [comment]
As it is merged, let's close it. Thanks a lot!
