### ISSUE TITLE
[Bug]: Can not create new app token on v28

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#41915]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

tested on c.nc.com (28rc1). When I try to create a new app token I get this error message:

![image](https://github.com/nextcloud/server/assets/1589737/2917cfc3-42f0-431f-b3ef-cc18165389d5)

### Steps to reproduce

1. go to the personal security settings
2. try to create a app token
3.

### Expected behavior

a app token gets created

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by SystemKeeper** [comment]
I think that's the same as https://github.com/nextcloud/server/issues/41760 because of the password dialog.
Can you try logging and in again and then create a token? That should work, because the password dialog is not needed.

**Comment by schiessle** [comment]
@SystemKeeper yes, seems to be the same issue

**Comment by AndyScherzinger** [comment]
Fixed with RC2
