### ISSUE TITLE
API for file details

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#4193]
For https://github.com/nextcloud/android/issues/795 we need to have an API which accepts a fileID and returns informations of this file, specifically the remote path for the specific user.

Background: Android client currently does not store a file list so we do not know where a shared file is for a specific user.

**Comment by MorrisJobke** [comment]
cc @icewind1991 @rullzer @nickvergessen

**Comment by rullzer** [comment]
@icewind1991 can we somehow reuse the webdav search API for this?

**Comment by nickvergessen** [comment]
Currently the file id can only be selected: `{http://owncloud.org/ns}id`
https://github.com/nextcloud/server/blob/e392d02d80fb347a93e57edf009c1f3ef3549415/apps/dav/lib/Files/FileSearchBackend.php#L131-L131

But the `searchable` flag is false.

**Comment by icewind1991** [comment]
https://github.com/nextcloud/server/pull/4222 adds searching by fileid
