### ISSUE TITLE
Bug in External Storage in combination with OnlyOffice

### ISSUE THREAD

**Issue by TautFlorian** [nextcloud/server#4194]
### Steps to reproduce
1. Integrate OnlyOffice in your Nextcloud
2. Use an SMB / CIFS Storage via External Storage
3. Try to Open an Document f.e. DOCX from the External Storage

### Expected behaviour
The selected Document should be opened by OnlyOffice and i should be able to edit it.

### Actual behaviour
Recieving Error "Download failed"

OnlyOffice' Troubleshooting page says that this error appears when the path to the selected file is incorrect.

### Server configuration
**Operating system**:
Debian 8.7.1
**Web server:**
Apache 2.4
**Database:**
Mysql 
**PHP version:**
PHP 7.0
**Nextcloud version:** (see Nextcloud admin page)
11.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh
**Where did you install Nextcloud from:**
Official

There must be a bug in the External Storage source, i cant find a seperate repo for it on github so i create the issue here.
When i try to open an Document which is stored on a FTP-External Storage there aint any problems.
Didnt try with the other Storagetypes yet.

Another solutions for me would be how to connect to Windows Server Shares without SMB or CIFS.

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by kesselb** [comment]
Is this problem still relevant?

**Comment by Jason-Linux** [comment]
Hi i have same problem

**Comment by Jason-Linux** [comment]
Error in Nextcloud 
<html>
<body>


Fatal | files_sharing | Error while trying to create shared mount |   | 2023-03-13T12:00:15+0100
-- | -- | -- | -- | --
Erreur | files_sharing | OCA\Deck\NoPermissionException: Must be logged in get the attachment folder


</body>
</html>

Error in OnlyOffice 

![image](https://user-images.githubusercontent.com/72259326/224686918-b61ae204-17d8-4579-be15-d94e2cd8e156.png)
