### ISSUE TITLE
[Bug]: Date picker not showing when setting expiration date

### ISSUE THREAD

**Issue by kohrar** [nextcloud/server#41946]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On NextCloud 27, I am unable to set the expiration date of a directory. Clicking on the 'Set expiration date' option shows the date input field, but clicking on the input field does not have any effect. 

I am also unable to type the date in as it seems to only accept one character at a time. For example, trying to enter '2024' in the year field makes the date change to 1902 and then shows immediately an error message: 'Expiration date is in the past'.

![image](https://github.com/nextcloud/server/assets/4450716/f7cd2aa3-19c7-492f-bc3d-9f143d321edb)

Additional notes:
* There is no forced expiration date setting set on this instance of NextCloud. Enabling it made no difference to this UI behavior
* I _am_ able to make the date picker appear if I hit the space key. This behavior is not obvious.
* I am currently using Microsoft Edge 119.0.2151.72 on Windows 10.

### Steps to reproduce

1. Click on the 'share' icon of a directory
2. Create a new share link
3. Attempt to set the expiration date by clicking on the date field.

### Expected behavior

I would expect the date picker to show up when clicking on the date field.

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

Other

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.xxxxxx.ca"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.4.1",
        "overwrite.cli.url": "http:\/\/cloud.xxxxxx.ca",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "overwriteprotocol": "https",
        "overwritehost": "cloud.xxxxxx.ca",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contactsinteraction: 1.8.0
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - user_ldap: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - workflowengine: 2.9.0
Disabled:
  - admin_audit: 1.17.0
  - bruteforcesettings: 2.7.0 (installed 2.2.0)
  - circles: 27.0.1 (installed 22.1.1)
  - dashboard: 7.7.0 (installed 7.1.0)
  - encryption: 2.15.0
  - firstrunwizard: 2.16.0 (installed 2.11.0)
  - nextcloud_announcements: 1.16.0 (installed 1.11.0)
  - photos: 2.3.0 (installed 1.4.0)
  - recommendations: 1.6.0 (installed 1.1.0)
  - sharebymail: 1.17.0 (installed 1.11.0)
  - support: 1.10.0 (installed 1.5.0)
  - survey_client: 1.15.0 (installed 1.10.0)
  - suspicious_login: 5.0.0
  - twofactor_totp: 9.0.0
  - updatenotification: 1.17.0 (installed 1.11.0)
  - weather_status: 1.7.0 (installed 1.1.0)
```

### Nextcloud Signing status

```shell
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- custom_apps/apps

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [custom_apps/apps] => Array
                        (
                            [expected] => 
                            [current] => 
                        )

                )

        )

)
```

**Comment by plazotronik** [comment]
please fix this bug. This is one of the most important features of this product. this creates very big problems when using the nextcloud.

**Comment by Dennis1993** [comment]
Related to https://github.com/nextcloud/server/issues/43230
