### ISSUE TITLE
[BITV]: gain an overview over a11y issues regarding image editor

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#41959]
We have several a11y issues regarding viewer editor which is a third-party library. To make an approximately decision regarding size of this tickets we need to investigate this library.

Connected tickets: 

* https://github.com/nextcloud/server/issues/41899
* https://github.com/nextcloud/server/issues/41820
* https://github.com/nextcloud/server/issues/41825
* https://github.com/nextcloud/server/issues/41863
* https://github.com/nextcloud/server/issues/41883
* https://github.com/nextcloud/photos/issues/2161
* https://github.com/nextcloud/server/issues/41898

**Comment by ShGKme** [comment]
All the issues have size label now on the accessibility project.

**Comment by szaimen** [comment]
Here was nothing to do, so added label
