### ISSUE TITLE
Show sharing to social network button if no link share created

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#4196]
* with #4175 the social sharing buttons are removed if there is no link share
* we should show them anyways and on click create the link in the background if none exists
* that makes it easier to discover the social network sharing feature

**Comment by MorrisJobke** [comment]
cc @nextcloud/javascript @jancborchardt @rullzer

**Comment by schiessle** [comment]
I think this creates some issues, e.g. how to handle the "enforce password" / "suggest password" if link creation happens in the background?

**Comment by MorrisJobke** [comment]
Right .... mmmh - any ideas @jancborchardt ?

**Comment by schiessle** [comment]
On the other hand you could argue that setting a password doesn't make a lot of sense if you share a link to a large audience on social media.

In this case we could even consider disabling the social buttons if the administrator enforces passwords on all links.

**Comment by MorrisJobke** [comment]
Let's close this for now.
