### ISSUE TITLE
webdav broken from windows (explorer) and osx(finder): files uploaded has 0 byte dimensions

### ISSUE THREAD

**Issue by paolomeraviglia** [nextcloud/server#4197]
### Steps to reproduce
1.connect from windows / osx to owncloud
2.try to upload a file
3.

### Expected behaviour
Everithing uploaded correctly

### Actual behaviour
on OSx you get error 36 and files with 0 dimensions, on windows you get "error reading file" and files with 0 byte dimension. Everything ok from davfs2 + linux, cyberduck via webdav,

### Server configuration
**Operating system**:
debian lxc container

**Web server:**
apache as reverse proxy, nginx as webserver

**Database:**
mariadb

**PHP version:**
php fpm 7.1

**Nextcloud version:** (see Nextcloud admin page)
11.02

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 11.01

**Where did you install Nextcloud from:**
tarball

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>
```
Contacts
Calendar
External Storage
```
</details>

**The content of config/config.php:**

$CONFIG = array (
  'instanceid' => '//',
  'passwordsalt' => '//',
  'secret' => '//',
  'trusted_domains' => 
  array (
    0 => 'cloud.domain.tk',
  ),
  'forwarded_for_headers' => 
  array (
    0 => 'HTTP_X_FORWARDED_FOR',
  ),
  'trusted_proxies' => 
  array (
    0 => '10.0.1.2',
  ),
  'overwriteprotocol' => 'https',
  'datadirectory' => '/usr/share/nginx/html/nextcloud/data/nextcloud',
  'overwrite.cli.url' => 'https://cloud.domain.tk',
  'dbtype' => 'mysql',
  'version' => '11.0.2.7',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_tab_',
  'dbuser' => 'oc',
  'dbpassword' => '//',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'versions_retention_obligation' => 'auto, 10',
  'trashbin_retention_obligation' => 'auto, 10',
  'filelocking.enable' => 'false',
  'cache_path' => '/tmp/nextcloud',
  'cache_chunk_gc_ttl' => 28800,
);

<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** glusterfs in local dir

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
I cannot reproduce this problem. Could you try to update to 11.0.3 because we fixed some stuff in there.
