### ISSUE TITLE
Audit app: Add hook for downloading ZIP or TAR file

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#42]
As discussed with @MorrisJobke and @blizzz

**Comment by LukasReschke** [comment]
Done

**Comment by MorrisJobke** [comment]
> Done

Commit? PR?

**Comment by blizzz** [comment]
Teleprogrammasis?

**Comment by MorrisJobke** [comment]
> Teleprogrammasis?

😕

**Comment by blizzz** [comment]
On IRC he told me that file access was logged file by file. Nothing left to fix.
