### ISSUE TITLE
Activity/more link escaping

### ISSUE THREAD

**Issue by rendezvousIY** [nextcloud/server#420]
I noticed that there seems to be an escaping issue in the activity log, see screenshot.

![escaping](https://cloud.githubusercontent.com/assets/6607975/16889268/061daf42-4a9a-11e6-8a7e-2cd0c02dacf1.png)

### Steps to reproduce
1. New account with hostiso.com

### Expected behaviour
Proper variable escaping

### Actual behaviour
Resulting HTML shows:

`<strong data-original-title="Photos/San Francisco.jpg, Photos, <a class=" class="has-tooltip" title="" filename="" has-tooltip"="" href="http://nc.hostiso.cloud/index.php/apps/files/?dir=/">">4 more</strong>`

**Comment by MorrisJobke** [comment]
I moved this to the activity app: https://github.com/nextcloud/activity/issues/5
