### ISSUE TITLE
E-Mail notification "sharebymail" function

### ISSUE THREAD

**Issue by Paddy1112** [nextcloud/server#4200]
It would be useful if you share a folder or file with the function "Sharebymail" - you gets an e-mail notification about download, upload, shares etc.

**Comment by schiessle** [comment]
Did you checked your activities. I didn't tested it but I expect the information to show up there. Can you verify it?

**Comment by Paddy1112** [comment]
Yes, the information shows the activities - but an e-mail notification about the activities would be helpful.

**Comment by schiessle** [comment]
> Yes, the information shows the activities - but an e-mail
> notification about the activities would be helpful.

please check your personal settings and make sure that email
notification is enabled for "A file or folder shared by mail or by
public link was downloaded" under the "Activity" section.
