### ISSUE TITLE
Autocompletion in share dialog fails if avatars are disabled

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#4202]
Autocompletion in the share dialog no longer works if the admin disables avatars in the config.php

Tested with Nextcloud 11.0.2

**Comment by schiessle** [comment]
setting was removed for Nextcloud 12: https://github.com/nextcloud/server/pull/3472

**Comment by StraToN** [comment]
This bug is pretty annoying even for users on Nextcloud 11.*.*. AFAIK, Nextcloud 12 won't be out in the next few days so why isn't this fix integrated in the next minor release ? Just wondering.
