### ISSUE TITLE
[Bug]: Forced expiration date for sharing via link is set for sharing with cloud users, too

### ISSUE THREAD

**Issue by Volker-K** [nextcloud/server#42028]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

We've restricted sharing via external link/mail with an expiration date 40 days in the future. For that, we have set "Set expiration date" für sharing via link to 40 days and "force expiration date" to "yes"
After migrating to 27.1.3.2 both settings for external links also force an expiration date on 'normal' shares with other accounts with the expiration date set to the current date. Since it is forced, it cannot be changed. 
When setting a specific expiration date for normal shares it is used, but the checkbox "force expiration date" for normal shares does not affect the wrong setting.
Sharing is broken.

### Steps to reproduce

1. Migrate to 27.1.3.2
2. enable an forced expiration date for sharing via  link/mail
3. try to share an object with another user
 

### Expected behavior

Settings should work as documented

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Other

### PHP engine version

PHP 8.0

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment]
This should be solved with 27.1.4 IIRC

**Comment by Volker-K** [comment]
> This should be solved with 27.1.4 IIRC

Can't check this today, but this week. Set expiration date to 36525 = 100 years, that will work for most cases :-)
