### ISSUE TITLE
[Bug]: App Store not working Undefined array key "en" at /var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php#375

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/server#42037]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When  click on the APP store nothing shows up it is happening to more then one server

### Steps to reproduce

1. Click on Apps 
2. Shows that is loading 
4. blank 

### Expected behavior

Should populate the apps

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27.1.4

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.axts.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.4.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "simpleSignUpLink.shown": false,
        "skeletondirectory": "",
        "default_locale": "en_US",
        "default_phone_region": "US",
        "allow_local_remote_servers": true,
        "ffmpeg": "\/usr\/bin\/ffmpeg",
        "preview_max_memory": 1280,
        "enabledPreviewProviders": [
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Image",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\SVG",
            "OC\\Preview\\Font",
            "OC\\Preview\\MP3",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI",
            "OC\\Preview\\MOV",
            "OC\\Preview\\HEIC"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "587",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "loglevel": 2,
        "logtimezone": "America\/Chicago",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "theme": "",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "beta",
        "memories.exiftool": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/exiftool-amd64-glibc",
        "memories.vod.path": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "memories.gis_type": 1
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - bruteforcesettings: 2.7.0
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - impersonate: 1.14.0
  - integration_youtube: 0.1.5
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - memories: 6.1.5
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - notify_push: 0.6.5
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - previewgenerator: 5.4.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - richdocuments: 8.2.3
  - sendent: 2.0.4
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - spreed: 17.1.3
  - support: 1.10.0
  - survey_client: 1.15.0
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_admin: 4.4.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_email: 2.7.4
  - twofactor_nextcloud_notification: 3.8.0
  - twofactor_totp: 9.0.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - circles: 27.0.1 (installed 27.0.1)
  - encryption: 2.15.0
  - user_ldap: 1.17.0
```

### Nextcloud Logs

```shell
{"reqId":"y4Vy4RTFxV05qzWBXsyW","level":3,"time":"2023-12-05T08:17:23-06:00","remoteAddr":"20.0.0.23","user":"admin","app":"PHP","method":"GET","url":"/settings/apps/list","message":"Undefined array key \"en\" at /var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php#375","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"},"id":"656f31167329e"}

{"reqId":"y4Vy4RTFxV05qzWBXsyW","level":3,"time":"2023-12-05T08:17:23-06:00","remoteAddr":"20.0.0.23","user":"admin","app":"PHP","method":"GET","url":"/settings/apps/list","message":"Trying to access array offset on value of type null at /var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php#375","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"},"id":"656f311673289"}
```

### Additional info

![image](https://github.com/nextcloud/server/assets/59488153/eb2be537-a3e1-4c34-9e36-383478a1cb6b)

**Comment by MinamiHasaki** [comment]
I also experience this issue this morning.

Here is the error showing in the Chrome console:
```
TypeError: Cannot read properties of null (reading 'toLowerCase')
    at AppList.vue:135:1
    at Array.filter (<anonymous>)
    at o.apps (AppList.vue:135:1)
    at e.get (vue.runtime.esm.js:3446:33)
    at e.evaluate (vue.runtime.esm.js:3547:27)
    at o.apps (vue.runtime.esm.js:5537:25)
    at o.<anonymous> (AppList.vue:1:2020)
    at e._render (vue.runtime.esm.js:2684:28)
    at o.a (vue.runtime.esm.js:3875:27)
    at e.get (vue.runtime.esm.js:3446:33)
Sn @ vue.runtime.esm.js:3049
En @ vue.runtime.esm.js:3041
Tn @ vue.runtime.esm.js:3008
e._render @ vue.runtime.esm.js:2687
a @ vue.runtime.esm.js:3875
e.get @ vue.runtime.esm.js:3446
e.run @ vue.runtime.esm.js:3522
Oa @ vue.runtime.esm.js:4121
(anonymous) @ vue.runtime.esm.js:3143
Dn @ vue.runtime.esm.js:3065
Promise.then (async)
_n @ vue.runtime.esm.js:3090
zn @ vue.runtime.esm.js:3155
Ma @ vue.runtime.esm.js:4207
e.update @ vue.runtime.esm.js:3513
e.notify @ vue.runtime.esm.js:720
set @ vue.runtime.esm.js:963
setAllApps @ apps.js:70
(anonymous) @ vuex.esm.js:844
(anonymous) @ vuex.esm.js:466
(anonymous) @ vuex.esm.js:465
A._withCommit @ vuex.esm.js:624
A.commit @ vuex.esm.js:464
A.commit @ vuex.esm.js:409
(anonymous) @ apps.js:317
Promise.then (async)
getAllApps @ apps.js:316
(anonymous) @ vuex.esm.js:851
A.dispatch @ vuex.esm.js:516
A.dispatch @ vuex.esm.js:406
beforeMount @ Apps.vue:296
yn @ vue.runtime.esm.js:3017
fa @ vue.runtime.esm.js:4031
e @ vue.runtime.esm.js:3854
si.$mount @ vue.runtime.esm.js:8772
init @ vue.runtime.esm.js:4407
n @ vue.runtime.esm.js:4561
(anonymous) @ vue.runtime.esm.js:6567
p @ vue.runtime.esm.js:6521
Qr.nodeOps @ vue.runtime.esm.js:7109
e._update @ vue.runtime.esm.js:3769
a @ vue.runtime.esm.js:3875
e.get @ vue.runtime.esm.js:3446
e.run @ vue.runtime.esm.js:3522
Oa @ vue.runtime.esm.js:4121
(anonymous) @ vue.runtime.esm.js:3143
Dn @ vue.runtime.esm.js:3065
Promise.then (async)
_n @ vue.runtime.esm.js:3090
zn @ vue.runtime.esm.js:3155
Ma @ vue.runtime.esm.js:4207
e.update @ vue.runtime.esm.js:3513
e.notify @ vue.runtime.esm.js:720
set @ vue.runtime.esm.js:963
(anonymous) @ vue-router.esm.js:3005
(anonymous) @ vue-router.esm.js:3004
De.updateRoute @ vue-router.esm.js:2414
(anonymous) @ vue-router.esm.js:2263
(anonymous) @ vue-router.esm.js:2402
a @ vue-router.esm.js:2084
a @ vue-router.esm.js:2091
a @ vue-router.esm.js:2091
Se @ vue-router.esm.js:2095
(anonymous) @ vue-router.esm.js:2397
a @ vue-router.esm.js:2084
(anonymous) @ vue-router.esm.js:2088
(anonymous) @ vue-router.esm.js:2384
(anonymous) @ vue-router.esm.js:2127
(anonymous) @ vue-router.esm.js:2203
Promise.then (async)
(anonymous) @ vue-router.esm.js:2150
(anonymous) @ vue-router.esm.js:2171
(anonymous) @ vue-router.esm.js:2171
_e @ vue-router.esm.js:2170
(anonymous) @ vue-router.esm.js:2106
g @ vue-router.esm.js:2362
a @ vue-router.esm.js:2087
a @ vue-router.esm.js:2091
a @ vue-router.esm.js:2091
Se @ vue-router.esm.js:2095
De.confirmTransition @ vue-router.esm.js:2392
De.transitionTo @ vue-router.esm.js:2260
qe.init @ vue-router.esm.js:2996
beforeCreate @ vue-router.esm.js:1298
yn @ vue.runtime.esm.js:3017
fa @ vue.runtime.esm.js:4031
e._init @ vue.runtime.esm.js:5689
si @ vue.runtime.esm.js:5762
9685 @ main-apps-users-management.js:49
i @ bootstrap:19
(anonymous) @ startup:4
i.O @ chunk loaded:25
(anonymous) @ startup:5
(anonymous) @ startup:5
```

**Comment by netboy3** [comment]
Same issue. Running official Docker NextCloud 27.1.3.
Considering AppSettingsController.php hasn't changed for months, it might be a corrupted AppStore entry that breaks the rendering of the apps list. If that's the case, then the controller code should really ought to be able to catch this instead of barfing on it.

**Comment by TIBI4** [comment]
> Same issue. Running official Docker NextCloud 27.1.3.

Same issue with Snap NextCloud 27.1.3.

**Comment by awo-in-sachsen** [comment]
same here with 27.1.4.1
is it possible, that the app store is down?

**Comment by BeardedTek** [comment]
I am having the same issue.  Logs:
```
{"reqId":"Ax6vTkaGpp4UmmJgXCXq","level":3,"time":"2023-12-05T16:54:29+00:00","remoteAddr":"192.168.2.10","user":"admin","app":"PHP","method":"GET","url":"/settings/apps/list","message":"Undefined array key \"en\" at /var/www/html/apps/settings/lib/Controller/AppSettingsController.php#373","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"},"id":"656f55e2c31d5"}
{"reqId":"Ax6vTkaGpp4UmmJgXCXq","level":3,"time":"2023-12-05T16:54:29+00:00","remoteAddr":"192.168.2.10","user":"admin","app":"PHP","method":"GET","url":"/settings/apps/list","message":"Trying to access array offset on value of type null at /var/www/html/apps/settings/lib/Controller/AppSettingsController.php#373","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"},"id":"656f55e2c31bb"}
{"reqId":"Ax6vTkaGpp4UmmJgXCXq","level":3,"time":"2023-12-05T16:54:29+00:00","remoteAddr":"192.168.2.10","user":"admin","app":"PHP","method":"GET","url":"/settings/apps/list","message":"Undefined array key \"en\" at /var/www/html/apps/settings/lib/Controller/AppSettingsController.php#374","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"},"id":"656f55e2c31a2"}
{"reqId":"Ax6vTkaGpp4UmmJgXCXq","level":3,"time":"2023-12-05T16:54:29+00:00","remoteAddr":"192.168.2.10","user":"admin","app":"PHP","method":"GET","url":"/settings/apps/list","message":"Trying to access array offset on value of type null at /var/www/html/apps/settings/lib/Controller/AppSettingsController.php#374","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"},"id":"656f55e2c3188"}
{"reqId":"Ax6vTkaGpp4UmmJgXCXq","level":3,"time":"2023-12-05T16:54:29+00:00","remoteAddr":"192.168.2.10","user":"admin","app":"PHP","method":"GET","url":"/settings/apps/list","message":"Undefined array key \"en\" at /var/www/html/apps/settings/lib/Controller/AppSettingsController.php#375","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"},"id":"656f55e2c316f"}
{"reqId":"Ax6vTkaGpp4UmmJgXCXq","level":3,"time":"2023-12-05T16:54:29+00:00","remoteAddr":"192.168.2.10","user":"admin","app":"PHP","method":"GET","url":"/settings/apps/list","message":"Trying to access array offset on value of type null at /var/www/html/apps/settings/lib/Controller/AppSettingsController.php#375","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36","version":"27.1.4.1","data":{"app":"PHP"},"id":"656f55e2c314f"}
```

**Comment by netboy3** [comment]
Even if it's down, the code should't barf on it and fail listing locally installed apps. Still a major bug.

**Comment by Gerri1** [comment]
same here with Nextcloud Hub 6 (27.1.4) 😩

**Comment by harddrive67** [comment]
same here with Nextcloud Hub (27.1.3) via snap

**Comment by KonradNN** [comment]
same here after upgrading to 27.1.4 (docker)

**Comment by ostasevych** [comment]
This may be a workaround in config.php 
`'has_internet_connection' => false,`
You will see the apps, though you will not be able to install apps from the AppStore.

**Comment by AndyXheli** [comment]
Looks like its backup and working now, I did not changing anything. Hmm

**Comment by BeardedTek** [comment]
Thank you NextCloud team for getting the app store back up and running.

Perhaps there could be a check to see if the API is up and running, say if it gets a non 200 response code back it tells the user it cannot reach the app store API.

Infrastructure sucks.  I'm not much of a php guy anymore (a decade or 2 ago I dabbled) but if you need any help, please feel free to tap on my shoulder.

**Comment by ostasevych** [comment]
> Thank you NextCloud team for getting the app store back up and running.
> 
> Perhaps there could be a check to see if the API is up and running, say if it gets a non 200 response code back it tells the user it cannot reach the app store API.
> 
> Infrastructure in general sucks. It breaks without notice at times.
> 
> I'm not much of a php guy anymore (a decade or 2 ago I dabbled) but if you need any help, please feel free to tap on my shoulder.

I've checked and the situation hasn't been change, the apps list is still empty and the errors in the log remain. Are any changes at some other sides?

**Comment by ostasevych** [comment]
> Same for me. Would appreciate an error message like "AppStore currently not available - try again later" or so.

The thing is that the AppStore is working! You may install/update apps via CLI
`occ app:install <appname>`
But it doesn't work in webUI!

**Comment by ostasevych** [comment]
> Seems to be up and running for me. Strange. Did you disable this: [#42037 (comment)](https://github.com/nextcloud/server/issues/42037#issuecomment-1841358498) ![image](https://private-user-images.githubusercontent.com/93575915/288167697-130ef0b9-1651-4679-b270-a20a39231eef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MDI4MTAsIm5iZiI6MTcwMTgwMjUxMCwicGF0aCI6Ii85MzU3NTkxNS8yODgxNjc2OTctMTMwZWYwYjktMTY1MS00Njc5LWIyNzAtYTIwYTM5MjMxZWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE4NTUxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyODQzMzU2ODRkOTE0MzkyNmM0ZmJjY2Y2Yjk3MmU3ODc4NWYxNTZjNmI0MTdjMWUxZGQ4ZDNjOGMxYTQ0ZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Jw49Es9KG8-W1gZ1vk1Uy72B8vzHgoJHbhGJMmmb4KY)

Now it works. Perhaps, need to wait a bit xD

**Comment by kesselb** [comment]
Weird, the error message suggests that the en translation for the app description is missing. 
The current code assumes it's always there. 

I used the script below to check the latest apps.json for apps without an english translations, but currently there are none. 


```
<?php

declare(strict_types=1);

$apps = json_decode(file_get_contents('https://apps.nextcloud.com/api/v1/apps.json'), true);

foreach ($apps as $app) {
    $hasEnglishTranslation = isset($app['translations']['en']);
    if ($hasEnglishTranslation === false) {
        echo $app['id'] . ': en translation missing' . PHP_EOL;
    }
}

echo 'done' . PHP_EOL;

```

Maybe an temporary issue with our apps store? 

You can manually replace your local apps.json by changing into the data directory, appdata_*, appstore and replace apps.json with a copy from `https://apps.nextcloud.com/api/v1/apps.json`.

**Comment by 1manprojects** [comment]
There appears to be a bug in the [AppSettingsController.php](https://github.com/nextcloud/server/blob/b0976e4568890b6b6556a7d5f53a83dfda58e4d6/apps/settings/lib/Controller/AppSettingsController.php#L371)

Starting from line 357 the **_currentVersion_** is being set, however in the else block as seen in the code snippet below the **_currentLanguage_** is being overwritten by the version number. This will set the currentLanguage to a version string like 0.7.2 thus the code below it will use the wrong variable as the language. This will cause the expected behaviour and the Apps are no longer shown in the App overview.

```
			$currentVersion = '';
			if ($this->appManager->isInstalled($app['id'])) {
				$currentVersion = $this->appManager->getAppVersion($app['id']);
			} else {
				$currentLanguage = $app['releases'][0]['version'];
			}

			$formattedApps[] = [
				'id' => $app['id'],
				'name' => $app['translations'][$currentLanguage]['name'] ?? $app['translations']['en']['name'],
				'description' => $app['translations'][$currentLanguage]['description'] ?? $app['translations']['en']['description'],
				'summary' => $app['translations'][$currentLanguage]['summary'] ?? $app['translations']['en']['summary'],
				'license' => $app['releases'][0]['licenses'],
				'author' => $authors,
				'shipped' => false,
				'version' => $currentVersion,
				'default_enable' => '',
				'types' => [],
```

The Fix is quite simple replace currentLanguage in Line 371 with currentVersion.

**Comment by ostasevych** [comment]
> There appears to be a bug in the [AppSettingsController.php](https://github.com/nextcloud/server/blob/b0976e4568890b6b6556a7d5f53a83dfda58e4d6/apps/settings/lib/Controller/AppSettingsController.php#L371)

> The Fix is quite simple replace currentLanguage in Line 371 with currentVersion.

PR?

**Comment by 1manprojects** [comment]
PR: https://github.com/nextcloud/server/pull/42044

**Comment by kesselb** [comment]
Good finding :+1: 

I tend to agree that we want to use $currentVersion in the else block as well.

Can someone confirm that the patch works? 


https://github.com/nextcloud/server/blob/a4a120cb0c4f5f3f8856745dcdf7f7a4c7125828/apps/settings/lib/Controller/AppSettingsController.php#L375

The error message `Undefined array key \"en\" at apps/settings/lib/Controller/AppSettingsController.php#375` belongs to the code above. We run a check if the given array element is there and fallback to `en` if not. Therefore, the wrong value for currentLanguage should not trigger the above error :confused:

**Comment by awo-in-sachsen** [comment]
Today it's working again.
It's magic, like Santa's chocolate

**Comment by solracsf** [comment]
Fixed by https://github.com/nextcloud/server/issues/42037

**Comment by ghackelo** [comment]
add this from nextcloud config.php file

  'updatechecker' => true,
  'updater.server.url' => 'https://updates.nextcloud.com/updater_server/',
  'updater.release.channel' => 'stable',
  'has_internet_connection' => true,
  'check_for_working_htaccess' => true,
  'check_for_working_wellknown_setup' => true,
  'connectivity_check_domains' => [
        'www.nextcloud.com',
        'www.startpage.com',
        'www.eff.org',
        'www.edri.org'
  ],
