### ISSUE TITLE
[Bug]: Can't update link share when password is enforced but not set new password

### ISSUE THREAD

**Issue by ElSi-DVT** [nextcloud/server#42047]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When `Enforce password protection` and `Always ask for a password` are enabled and I want to update a link share it's not possible to save if no new password is set.
If a new password is chosen it works to update the share but this behavior is extremely inconvenient as you have to set a new password for every small change.
![grafik](https://github.com/nextcloud/server/assets/142410285/9efbfd0d-dd9d-4ebe-bfb8-9491974b59fa)

### Steps to reproduce

1. Enable `Always ask for password`and `Enforce password protection` in Administration Settings
2. Right click on a folder and choose `Share folder`
3. Create a share link
4. Click on `Customize link`
5. Change e.g. the expiration date
6. Click on `Update share`

### Expected behavior

The expected behavior is that updating the share works with as well as without setting a new password.

### Nextcloud Server version

27

### Additional info

The bug occurs in NC 27.1.2 and NC 27.1.3

**Comment by szaimen** [comment]
Yes, possibly this has been resolved in the latest 27 release...

**Comment by icewind1991** [comment]
Fixed with https://github.com/nextcloud/server/pull/41885
