### ISSUE TITLE
[Bug]: Favorites in Files navigation not expandable anymore

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#42059]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Expanding the favorites folders does not work:
I’m not entirely sure what causes this though. I noticed that the "Conduct" folder is duplicated, once as my own folder and once as a share, if it has something to do with that?
![image](https://github.com/nextcloud/server/assets/925062/f44fbc76-9d26-429d-b37c-51483c2ba16c)

### Steps to reproduce

1. Have a bunch of favorites
2. Expect that you can expand them in the left navigation
3. The expander does not show

### Expected behavior

For few folders it works fine:
![image](https://github.com/nextcloud/server/assets/925062/487b85bd-66be-4014-a9b3-e91cc7fb01ba)

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Our cloud.nc.com
```

**Comment by skjnldsv** [comment]
If you refresh it does show, right?
I think this is a reactivity issue :thinking: :eyes:

**Comment by Pytal** [comment]
Reproduced 🤔

**Comment by jancborchardt** [comment]
@Pytal this is happening again, on cloud.nc but NOT on daily for me. So I guess it only happens above a certain number of favorites?
