### ISSUE TITLE
Nextcloud box reformat hard drive without warning

### ISSUE THREAD

**Issue by farvardin** [nextcloud/server#4205]
### Steps to reproduce
1. Install a nextcloud box. Copy data on it
2. Trash the sd card. Download a new system on a new sd card
3. Upon boot on the new sd card, nextcloud won't recognise there were data from a previous instance on the hard drive and will erase everything without warning

### Expected behaviour
The system should detect the previously copied data, especially if it's from another nextcloud installation, and warn about a possible loss of data

### Actual behaviour
Everything is deleted

### Server configuration
**Operating system**: ubuntu snap

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page) latest on the raspberry pi image

**Updated from an older Nextcloud/ownCloud or fresh install:** update

**Where did you install Nextcloud from:** bought a nextcloud box

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
cc @jospoortvliet

**Comment by jospoortvliet** [comment]
This would be an issue for the Snap repo: https://github.com/nextcloud/nextcloud-snap/issues

And indeed, a fresh SDCard image will install itself to the hard drive, formatting it. I would suggest to backup the SD Card after installation so you can avoid this: https://github.com/nextcloud/nextcloud-snap/wiki/How-to-backup-your-SD-card

This is also the way to fix a broken installation - 'just' put in a new sd card. But it might also not be what some users expect like in your case :cry: 

I'm not entirely sure how to fix this one to be honest.
