### ISSUE TITLE
Documentation of external Storage Signal flow 

### ISSUE THREAD

**Issue by maldag** [nextcloud/server#4206]
Is there an external storage signal flow of data? I was wondering how the desktop sync client behaves when I embed an external storage:
- I add a file in an synchronized external storage and start synchronization
- Will it be transferred from my client to the server, then be cached and upload from the server to the external site asynchronously? 
- It feels like the external storages just takes forever when synchronizing with the desktop client.

So is there a flow chart what happens when external storages will be synchronized?

**Comment by MorrisJobke** [comment]
cc @icewind1991 

the file is usually not cached on the server but directly written to the external storage

**Comment by MorrisJobke** [comment]
cc @jospoortvliet Maybe something for a FAQ

**Comment by maldag** [comment]
I think it's worth to say how the intended case was:

- There is one client and two nextcloud instances involved.
- The client is connected via VPN to the server at home with a bandwidth of approximately 100Mbit/s Up and 100MBit/s down on the client side.
- The home server is attached to a cable network with 32MBit/s down and 2MBit/s up.
- The external storage is on a shared hoster.

The fastest way would probably be to connect directly from the client to the shared hoster but since the desktop client should only have one account connected, this is not used here.

The following seems to happen to me:

1. The client starts the sync process and checks the remote file status (home).
2. After a long while (yes, this can take some minutes) it see's the changed status of the external storage on the remote (home).
3. It starts to upload the data to the remote (home) via VPN tunnel.
4. It blocks the whole process until the external storage has received the data. So the data flow is:
   1. Upload to home with 100 MBit/s and download with 32MBit/s -> 32 MBit/s 
   2. Upload from home to shared hoster with 2MBit/s

Since regular private internet contracts usually have a higher download than upload speed, a caching on the remote home would be great and the other process would be done a lot faster.

**Comment by MorrisJobke** [comment]
Please reopen this in the documentation repo: https://github.com/nextcloud/documentation/issues
