### ISSUE TITLE
[Bug]: Default expiration date for shares is set to one day

### ISSUE THREAD

**Issue by ElSi-DVT** [nextcloud/server#42060]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When sharing internally with another user, the default expiration date is set to one day. Although there is definitely no `default expiration date for shares` configured in the settings.

### Steps to reproduce

1. Go the Sharing in Administration Settings.
2. Configure the sharing options like in the screenshot below.
![grafik](https://github.com/nextcloud/server/assets/142410285/a90f2f05-dd0b-496f-9c00-67e3570266f1)
3. Share a folder or file to another user.
4. The expiration date is set to the following day.

### Expected behavior

If the option is disabled, no default expiration date should be active in the field.

### Nextcloud Server version

27

### Additional info

Tested with Nextcloud Version 27.1.3

**Comment by normic** [comment]
I can confirm that this bug is still there, just retested in 27.1.5

This is obviously only an issue with the datepicker. As a workaround one can do the following:
While creating the share the datepicker opens (with the mentioned 1 day), but now clicking on clear in the lower left will close the date picker with the datefield set to mm/dd/2024.
If one clicks on the datepicker again, it shows the correct sharing dates.

**Comment by blizzz** [comment]
> 4. The expiration date is set to the following day.

I cannot reproduce this behaviour on current 27. There, no expiration date is set, when no default is activated, as in the settings.

**Comment by ElSi-DVT** [comment]
I tested it again and it seems to be fixed.
