### ISSUE TITLE
[Bug]: Issues with newly created files (set name and open automatically)

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#42097]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In previous versions when creating a new file you could set a name and the new file was opened directly with the default file action.

With 28 it seems that this behaviour changed in multiple ways due to the files to vue migration:

- There is no way to edit the file name directly after selecting the template
- The file is not highlighted anymore
- The new file is not opening automatically anymore

### Steps to reproduce

1. Create a new text file through the new file menu

### Expected behavior

- The file name is editable
- The file entry is highlighted
- The file opens automatically after confirming the new name

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ChristophWurst** [comment]
> The file name is editable

related: https://github.com/nextcloud/server/issues/41772

**Comment by szaimen** [comment]
cc @nextcloud/files

**Comment by Luncheon3462** [comment]
Not fixed in 28.0.3 While I can create a file name, the document does not open.   Correct behavior is creating a file name and then the document should open automatically.   NC27 works fine/appropriately.

**Comment by susnux** [comment]
Reopen partly: For template files the file is currently not opened (this includes plain text files).

**Comment by susnux** [comment]
@bentuna thank you for the feedback, but this unrelated to this issue and already tracked in https://github.com/nextcloud/server/issues/43659

**Comment by bentuna** [comment]
> @bentuna thank you for the feedback, but this unrelated to this issue and already tracked in #43659

Oh, you are right - thank you for the hint to the new issue!

**Comment by Luncheon3462** [comment]
This still doesn’t work properly.
