### ISSUE TITLE
[Bug]: "files/ajax/download.php: Failed to open stream: No such file or directory" when downloading multiple files or directory

### ISSUE THREAD

**Issue by szotsaki** [nextcloud/server#42090]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

It's not anymore possible to download multiple files as a compressed (zip) archive

### Steps to reproduce

1. Select multiple files
2. Download them

### Expected behavior

Nextcloud compresses and downloads the data

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

27

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.4.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 0,
        "loglevel_frontend": 0,
        "log_type": "errorlog",
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "default_language": "hu",
        "default_locale": "hu_HU",
        "default_phone_region": "HU",
        "knowledgebaseenabled": false,
        "remember_login_cookie_lifetime": 12960000,
        "debug": false,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpdebug": false,
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 30",
        "simpleSignUpLink.shown": false,
        "theme": "",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - bruteforcesettings: 2.7.0
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - cookbook: 0.10.4
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - files: 1.22.0
  - files_markdown: 2.4.1
  - files_pdfviewer: 2.8.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - gpxpod: 5.0.13
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - metadata: 0.19.0
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - previewgenerator: 5.4.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - related_resources: 1.2.0
  - richdocuments: 8.2.3
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - tasks: 0.15.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_totp: 9.0.0
  - updatenotification: 1.17.0
  - viewer: 2.1.0
  - workflowengine: 2.9.0
Disabled:
  - admin_audit: 1.17.0 (installed 1.11.0)
  - comments: 1.17.0 (installed 1.16.0)
  - contactsinteraction: 1.8.0 (installed 1.2.0)
  - dashboard: 7.7.0 (installed 7.1.0)
  - encryption: 2.15.0
  - federation: 1.17.0 (installed 1.11.0)
  - files_external: 1.19.0
  - files_reminders: 1.0.0 (installed 1.0.0)
  - recommendations: 1.6.0 (installed 1.1.0)
  - serverinfo: 1.17.0 (installed 1.12.0)
  - support: 1.10.0 (installed 1.5.0)
  - survey_client: 1.15.0 (installed 1.10.0)
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0 (installed 1.11.0)
  - user_ldap: 1.17.0
  - user_status: 1.7.0 (installed 1.1.1)
  - weather_status: 1.7.0 (installed 1.1.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
AH01071: Got error 'PHP message: [nextcloud][PHP][3] {"reqId":"Y8Gg9i90XpTXk1w9y9sW","level":3,"time":"2023-12-07T09:32:51+00:00","remoteAddr":"XXXXXXXXX","user":"XXXXXX","app":"PHP","method":"GET","url":"/index.php/apps/files/ajax/download.php?dir=%2F&files=XXXXXXXXXx&downloadStartSecret=XXXXXXXX","message":"require_once(files/ajax/download.php): Failed to open stream: No such file or directory at /[...]/nextcloud/lib/private/Route/Route.php#155","userAgent":"XXXXXXXXX","version":"27.1.4.1","data":{"app":"PHP"}}PHP message: [nextcloud][index][3] {"reqId":"Y8Gg9i90XpTXk1w9y9sW","level":3,"time":"2023-12-07T09:32:51+00:00","remoteAddr":"XXXXXXXXX","user":"XXXXXXX","app":"index","method":"GET","url":"/index.php/apps/files/ajax/download.php?dir=%2F&files=XXXXXXX&downloadStartSecret=XXXXXXX","message":"{\\"Exception\\":\\"Error\\",\\"Message\\":\\"Failed opening required 'files/ajax/download.php' (include_path='/usr/share/php8/PEAR')\\",\\"Code\\":0,\\"Trace\\":[{\\"function\\":\\"OC\\\\\\\\Route\\\\\\\\{closure}\\",\\"class\\":\\"OC\\\\\\\\Route\\\\\\\\Route\\",\\"type\\":\\"->\\",\\"args\\":[\\"*** sensitive parameters replaced ***\\"]},{\\"file\\":\\"/[...]/nextcloud/lib/private/Route/Router.php\\",\\"line\\":324,\\"function\\":\\"call_user_func\\"},{\\"file\\":\\"/[...]/nextcloud/lib/base.php\\",\\"line\\":1068,\\"function\\":\\"match\\",\\"class\\":\\"OC\\\\\\\\Route\\\\\\\\Router\\",\\"type\\":\\"->\\"},{\\"file\\":\\"/[...]/nextcloud/index.php\\",\\"line\\":36,\\"function\\":\\"handleRequest\\",\\"class\\":\\"OC\\",\\"type\\":\\"::\\"}],\\"File\\":...'
```

**Comment by szotsaki** [comment]
The problem is:
In `public function actionInclude($file)` PHP `require_once "$file"` contains `files/ajax/download.php` while the current working directory being `nextcloud`.

So the full path gives: `require_once [...]/nextcloud/files/ajax/download.php`. Which is wrong, because `apps` is missing. The correct one should be: `require_once [...]/nextcloud/apps/files/ajax/download.php`

What is interesting, that in `nextcloud/lib/base.php:1069` the `match()` function correctly gets `/apps/files/ajax/download.php` as the result of the `$request->getRawPathInfo()` call

In `OC\Route\Router->findMatchingRoute()` the parameter `$url` correctly gets populated to `/apps/files/ajax/download.php`. However, in `UrlMatcher->match()` the returned `$parameters['action']['static']['file']` value (which gets require'd literally later) is now only `files/ajax/download.php`.

This is because the following `$this->root` array is given to the Symphony UrlMatcher:
```
Symfony\Component\Routing\RouteCollection Object
(
    [routes:Symfony\Component\Routing\RouteCollection:private] => Array
        (
            [files_ajax_download] => OC\Route\Route Object
                (
                    [path:Symfony\Component\Routing\Route:private] => /apps/files/ajax/download.php
                                        [defaults:Symfony\Component\Routing\Route:private] => Array
                        (
                            [action] => Closure Object
                                (
                                    [static] => Array
                                        (
                                            [file] => files/ajax/download.php
                                        )
```

And that is because in `loadRoutes($app = 'files')` the `$this->getCollection('files')` returns with this array.

At this point I ran out of time further debugging this Nextcloud bug. I think it's a bug because with the default config shown in the documentation this error still stands.

Related bug report: https://github.com/nextcloud/server/issues/35006

**Comment by joshtrichards** [comment]
- Any chance you've customized your `include_path` in your `php.ini` (or equivalent)? Because we populate the include_path with the app folders already[1].
- Can you provide the actual full request entry/stack trace from your `nextcloud.log`?

[1] https://github.com/nextcloud/server/blob/31df9c4d3ccc1feb28918445cf6442cbd2cb0a34/lib/base.php#L228-L240

**Comment by szotsaki** [comment]
I use PHP FPM. These are my current include paths in
* php.ini: `include_path = ".:/usr/share/php8:/usr/share/php/PEAR"` (for CLI) and in
* php-fpm.d/www.conf: `php_admin_value[include_path] = /usr/share/php8/PEAR` (for web)

I don't remember that I changed them.

Here is the debug message:

Type: Error
Code: 0
Message: Failed opening required 'files/ajax/download.php' (include_path='/usr/share/php8/PEAR')
File: /srv/www/htdocs/nextcloud/lib/private/Route/Route.php
Line: 158

Backtrace
```
#0 [internal function]: OC\Route\Route->OC\Route\{closure}()
#1 /srv/www/htdocs/nextcloud/lib/private/Route/Router.php(324): call_user_func()
#2 /srv/www/htdocs/nextcloud/lib/base.php(1068): OC\Route\Router->match()
#3 /srv/www/htdocs/nextcloud/index.php(38): OC::handleRequest()
#4 {main}
```

**Comment by joshtrichards** [comment]
Any chance your web config is missing the `ajax` rewrite handling lines?

I'm not sure if you're relying on the distributed `.htaccess` or not, but that line being missing is typically what causes similar behavior (assuming you're using Apache as your report states). For example, see https://github.com/nextcloud/server/issues/42617#issuecomment-1881958718

**Comment by joshtrichards** [comment]
Closing since this is almost certainly a config problem. You mentioned FPM. Not sure what web server you're using it alongside, but I'd it's Nginx, you need to confirm your config is compliant:

https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html

The handling for that is in there.
