### ISSUE TITLE
[Bug]: "shows conflict dialog when no client side conflict fails" on stable26

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#42092]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The jsunit test fails

### Steps to reproduce

1. https://github.com/nextcloud/server/actions/runs/7126244712/job/19404561588

### Expected behavior

Green CI

### Installation method

None

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by artonge** [comment]
Cannot reproduce locally for now. Maybe CI hiccup? I restarted the job.

**Comment by artonge** [comment]
Job is green now?
