### ISSUE TITLE
Can't download files via Chrome on Android devices.

### ISSUE THREAD

**Issue by Lord-Protector** [nextcloud/server#421]
I faced with very strange problem. ALL desktop browsers download all types of files as should. But mobile webkit-based browsers on Android doesn't! They just say me, that
 `[filename] download failed due to server issues`.

### Steps to reproduce
1. Take Android phone.
2. Try to download any file via web-version by Chrome 
(or something WebKit-based. With other browsers all works as should).

### Expected behaviour
The download should be successful.

### Actual behaviour
Browser tell us, that `download failed due to server issues`

### Server configuration
**Operating system**:
Debian 8.5
**Web server:**
Nginx 1.9.10 (from debian-backports)
**Database:**
MySQL 5.6 
**PHP version:**
PHP 5.6 (from debian-backports)
**Nextcloud version:** (see Nextcloud admin page)
9.0.52
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install
**Where did you install Nextcloud from:**
From Zip-file
**Signing status (Nextcloud 9.0 and above):**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.2.1
  - admin_audit: 1.0.0
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - news: 8.8.0
  - notifications: 0.2.3
  - password_policy: 1.0.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - theming: 0.1.0
  - updatenotification: 0.1.0
  - user_external: 0.4
Disabled:
  - encryption
  - files_external
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocq3t0kae61a",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.krasovsky.me",
            "shorten.pro",
            "l33t.host"
        ],
        "datadirectory": "\/media\/storage\/cloud",
        "overwrite.cli.url": "https:\/\/cloud.krasovsky.me",
        "dbtype": "mysql",
        "version": "9.0.52.0",
        "dbname": "nextcloud_db",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_from_address": "nextcloud",
        "mail_domain": "krasovsky.me",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.yandex.ru",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome
**Operating system:**
Android 6.0 (but I try also on 5.1 and BlackBerry 10)
#### Web server error log
<details>
<summary>Web server error log</summary>
```
Error log is empty.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Nothing serious.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Resource interpreted as Document but transferred with MIME type application/zip: "https://shorten.pro/index.php/apps/files/ajax/download.php?dir=%2F&files=Univercity&downloadStartSecret=2ct5fn0g5k6tisazs482sp2e29".redirect @ js.js?v=082d28a…:234handleDownload @ files.js?v=082d28a…:315actionHandler @ fileactions.js?v=082d28a…:603_onClickAction @ fileactionsmenu.js?v=082d28a…:83dispatch @ jquery.min.js?v=082d28a…:5v.handle @ jquery.min.js?v=082d28a…:5
Resource interpreted as Document but transferred with MIME type application/octet-stream: "https://shorten.pro/remote.php/webdav/db.mysql".

and etc.
```
I get it by debuging directly via USB-connection in desktop Chrome!
How I did that: 
![chrome_2016-07-16_18-44-50](https://cloud.githubusercontent.com/assets/5345489/16895626/ccebd694-4b85-11e6-931a-cc4e7909c95e.png)

</details>

**Comment by MorrisJobke** [comment]
This seems to be the exact same bug as https://github.com/nextcloud/server/issues/342#issuecomment-233110015 

This is already reported upstream (Chrome for Android). Could you try the download with a different browser=
