### ISSUE TITLE
[Bug]: template picker is not showing, new file is created right away

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/server#42116]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

usually when you create a new file, you're suggested some templates in a modal
but this morning, when I create a new file, the file is created right away, without me being able to pick on or the other template.

Some tests I made:

#### Nextcloud instances
bug appears on c.nc.c
feature works fine on tp.nc.c

#### browsers
Firefox and Chromium behave the same
The issue also happens when firefox runs in troujbleshoot mode.

#### template directory
I never had a template directory configured before. Whether or not it is configured in the personal settings > office has no impact on the issue. When testing with template dir, it had been populated with a test md file.

#### language, theme
changing language/theme has no impact

### Steps to reproduce

1.click the + new button at the top of Files, and select a file type
2.the file is created right away

### Expected behavior

a modal should pop up offering various templates to pick from.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by sorbaugh** [comment]
Excerpt from the logs:

Uncaught TypeError: OCA.Files.FileList is undefined
    NextJS 2
circles.files.list.js:42:36
OCA.Comments.View initialized sentry.js:2:63997
Uncaught TypeError: window.OCP.Files.Navigation is undefined
    <anonymous> main.ts:36
    <anonymous> groupfolders.ts:113
    <anonymous> groupfolders.ts:113
main.ts:36:19

**Comment by szaimen** [comment]
cc @juliushaertl

**Comment by juliushaertl** [comment]
I haven't been able to reproduce this, so no further idea. The log messages from @sorbaugh don't look related. 

@maximelehericy If you see this happening can you check the browser console for errors? Also there should be a network request in the browser to GET/ocs/v2.php/apps/files/api/v1/templates. Does that succeed for you and contain any templates in the json response?
