### ISSUE TITLE
[Bug]: STARTTLS for admin mails and for mail app with self-signed certificates

### ISSUE THREAD

**Issue by mamama1** [nextcloud/server#42127]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

So, I absolutely understand the necessity of security, encryption and thus the need for TLS in general.

BUT. I'm using proxmox mail gateway as an internal mail router and this wonderful piece of software doesn't support custom SMTP TLS certificates yet (there was a request in 2016 which was kinda declined). I'd have to manually edit the postfix configuration and take care of that change after every update and I'd have to trust my PKI within nextcloud but for mails to an internal host within a protected DMZ, I just don't feel like it is worth the effort.

As mentioned, I have my private PKI in place and all, which is trusted in my whole network but in that case, since the mails aren't even leaving a protected DMZ network, I'd prefer to just allow self signed certificates.

I had to patch /var/www/html/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php line 258 from

`$streamContext = stream_context_create($options);`

to

`$streamContext = stream_context_create(array('ssl'=>['verify_peer'=>false, 'verify_peer_name'=>false, 'allow_self_signed'=>true]))`

Please, I don't want to have a babysitter here, please just allow me to set these options in the UI or at least in config.php, which I hope persists AIO updates.

This change will be reverted with each update and I already hate it.

This is not about the mailer app, this is about the "Administration settings -> Basic Settings" mailing.
Of course, I'd like to have to option for any mailing happening from the nextcloud server, though.

I do not consider this being a feature request, since this has been working in the past and now with some change is broken, because someone didn't think out of his box.

### Steps to reproduce

Try to send admin test mails to a server with a self-signed certificate from "Administration settings -> Basic Settings"

### Expected behavior

Option to have self-signed certificates accepted

### Installation method

Official All-in-One appliance

### Nextcloud Server version

27

### Operating system

Other

### PHP engine version

Other

### Web server

Other

### Database engine version

Other

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by SystemKeeper** [comment]
You might want to check the documentation about that first: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/email_configuration.html#how-can-i-send-mail-using-self-signed-certificates-or-use-starttls-with-self-signed-certificates

**Comment by SystemKeeper** [comment]
In case there is still a problem, feel free to head over to https://help.nextcloud.com

**Comment by mamama1** [comment]
Thanks for pointing me to the documentation, I was absolutely not capable to find this neat little piece of information.
Just as I am not able to find any info on persistence of changes to the config.php file when using the AIO docker version. Aren't any changes going to be overwritten with each update?

Thanks

**Comment by szaimen** [comment]
> Just as I am not able to find any info on persistence of changes to the config.php file when using the AIO docker version. Aren't any changes going to be overwritten with each update?

Changes to the aio config will be persistant.

**Comment by mamama1** [comment]
were talking about config/config.php and not about the master container config, right?

**Comment by szaimen** [comment]
> were talking about config/config.php and not about the master container config, right?

Yes
