### ISSUE TITLE
[Bug]: Breadcrumb "..." cannot be opened

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/server#42137]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When the breadcrumb is "collapsed" (as in it shows the "..." menu), it is not possible to click on that "..." menu.
Happens on 28 (c.nc.c) and on master.

### Steps to reproduce

https://github.com/nextcloud/server/assets/1580193/15cb3e71-4e33-4808-a0d7-53742e02cc11

### Expected behavior

Menu opens

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

```
vue.runtime.esm.js:3049 TypeError: Cannot read properties of undefined (reading 'resolve')
    at o.render (vue-router.esm.js:1097:22)
    at e._render (vue.runtime.esm.js:2684:28)
    at o.r (vue.runtime.esm.js:3875:27)
    at e.get (vue.runtime.esm.js:3446:33)
    at new e (vue.runtime.esm.js:3436:51)
    at e (vue.runtime.esm.js:3892:5)
    at sa.$mount (vue.runtime.esm.js:8779:12)
    at init (vue.runtime.esm.js:4411:19)
    at vue.runtime.esm.js:6571:17
    at h (vue.runtime.esm.js:6525:13)
```

**Comment by raimund-schluessler** [comment]
It seems to work for my dev environment running latest `master`.

**Comment by raimund-schluessler** [comment]
@SystemKeeper I works with `master` and `28.0.1` for me now. Can you confirm this?

**Comment by SystemKeeper** [comment]
Yes, can confirm! Thanks for testing this :)
