### ISSUE TITLE
[Bug]: Out of office status automation does not set nor reset user status

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#42138]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I was ooo for a public holiday and tried the out of office feature. The automation did not set my user status to DND and the short message when I left. I manually switched to DND and it was not reset either.

### Steps to reproduce

1. Configure ooo (28 RC2)
2. Wait until ooo starts (28 RC3)
3. Look at user status

![Bildschirmfoto vom 2023-12-11 08-29-17](https://github.com/nextcloud/server/assets/1374172/b818ff4f-4ee0-4cb4-aa6d-77f050f43bd7)
![Bildschirmfoto vom 2023-12-11 08-28-48](https://github.com/nextcloud/server/assets/1374172/58c660f6-f9f6-4b5b-8f20-60db24e5bac1)

### Expected behavior

Status is set to DND when my absence starts.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by miaulalala** [comment]
Figured it out. The implementation of https://github.com/nextcloud/server/blob/14718499567a1ba6b146b2eb62ea60414aa4907f/lib/public/BackgroundJob/IJobList.php#L71

does not update the `last_run ` timestamp, only the `last_checked` when the job already exists. That means if an earlier run has set the `last_run` timestamp to a timestamp in the future, the run will not happen.
