### ISSUE TITLE
Upgrade from nc 9.0.51 to 10.0.4 failed - sql transaction error

### ISSUE THREAD

**Issue by evsigneevk** [nextcloud/server#4213]
### Steps to reproduce
1. Enable Maintenance Mode with the command line tool: sudo -u www-data php occ maintenance:mode --on
2. Remove the directory with the Nextcloud
3. Download NC 10.0.4 and extract it to the location where the old Nextcloud code was
4. Copy back the configuration file config.php from the Nextcloud backup to nextcloud/config/config.php
5. Start the upgrade process with the command line tool: sudo -u www-data php occ upgrade

### Expected behaviour
Update successful

### Actual behaviour
Error in console
'Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE "oc_preferences" SET "configvalue" = ? WHERE ("userid" = ?) AND ("appid" = ?) AND ("configkey" = ?)' with params [1491221106, "tur", "user_ldap", "lastFeatureRefresh"]:

SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block
Update failed
Maintenance mode is kept active
Reset log level'

### Server configuration
**Operating system**: Debian 8.6

**Web server:** nginx/1.10.2

**Database:** postgressql 9.5.4

**PHP version:** PHP 5.6.26

**Nextcloud version:** 10.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgrade from nc 9.0.51

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-9.0.51.zip

**Signing status:**
<details>
<summary>Signing status</summary>
Integrity checker has been disabled. Integrity cannot be verified.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - comments: 1.0.0
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.1
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_ldap: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - activity
  - admin_audit
  - encryption
  - external
  - federation
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - user_external
  - user_saml
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "ocwv8nip3l0d",
        "debug": "false",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nexctcloud"
        ],
        "datadirectory": "\/opt\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/nexctcloud",
        "dbtype": "pgsql",
        "version": "9.0.51.0",
        "dbname": "database_name",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "mail_smtpmode": "smtp",
        "default_language": "ru",
        "asset-pipeline.enabled": true,
        "maintenance": true,
        "enable_previews": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "appstore.experimental.enabled": true,
        "loglevel": 2,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
</details>

**Are you using external storage, if yes which one:** yes - local partition

**Are you using encryption:**  no

**Are you using an external user-backend, if yes which one:**  ActiveDirectory

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
Configuration                 | s01                                                                                                                                                                    |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                                      |
| hasPagedResultSupport         |                                                                                                                                                                        |
| homeFolderNamingRule          |                                                                                                                                                                        |
| lastJpegPhotoLookup           | 0                                                                                                                                                                      |
| ldapAgentName                 | login                                                                                                                                                            |
| ldapAgentPassword             | ***                                                                                                                                                                    |
| ldapAttributesForGroupSearch  | cn                                                                                                                                                                     |
| ldapAttributesForUserSearch   | sAMAccountName;firstname;lastname                                                                                                                                      |
| ldapBackupHost                |                                                                                                                                                                        |
| ldapBackupPort                |                                                                                                                                                                        |
| ldapBase                      | CN=Users,DC=*,DC=*,DC=*                                                                                                                                   |
| ldapBaseGroups                |CN=Users,DC=*,DC=*,DC=*                                                                                                                                   |
| ldapBaseUsers                 | CN=Users,DC=*,DC=*,DC=*                                                                                                                                   |
| ldapCacheTTL                  | 600                                                                                                                                                                    |
| ldapConfigurationActive       | 1                                                                                                                                                                      |
| ldapDynamicGroupMemberURL     |                                                                                                                                                                        |
| ldapEmailAttribute            |                                                                                                                                                                        |
| ldapExperiencedAdmin          | 0                                                                                                                                                                      |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                                        |
| ldapExpertUUIDUserAttr        |                                                                                                                                                                        |
| ldapExpertUsernameAttr        | sAMAccountName                                                                                                                                                         |
| ldapGroupDisplayName          | cn                                                                                                                                                                     |
| ldapGroupFilter               | (&(|(objectclass=group)))                                                                                                                                              |
| ldapGroupFilterGroups         |                                                                                                                                                                        |
| ldapGroupFilterMode           | 0                                                                                                                                                                      |
| ldapGroupFilterObjectclass    | group                                                                                                                                                                  |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                                                                                           |
| ldapHost                      | 192.168.1.1                                                                                                                                                         |
| ldapIgnoreNamingRules         |                                                                                                                                                                        |
| ldapLoginFilter               | (&(&(|(objectclass=person))(|(|(memberof=CN=group,CN=Users,DC=*,DC=*,DC=*)))(!(userAccountControl:1.2.840.113556.1.4.804:=2)))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                                                                                        |
| ldapLoginFilterEmail          | 0                                                                                                                                                                      |
| ldapLoginFilterMode           | 0                                                                                                                                                                      |
| ldapLoginFilterUsername       | 1                                                                                                                                                                      |
| ldapNestedGroups              | 1                                                                                                                                                                      |
| ldapOverrideMainServer        |                                                                                                                                                                        |
| ldapPagingSize                | 500                                                                                                                                                                    |
| ldapPort                      | 389                                                                                                                                                                    |
| ldapQuotaAttribute            |                                                                                                                                                                        |
| ldapQuotaDefault              |                                                                                                                                                                        |
| ldapTLS                       | 0                                                                                                                                                                      |
| ldapUserDisplayName           | displayname                                                                                                                                                            |
| ldapUserDisplayName2          |                                                                                                                                                                        |
| ldapUserFilter                | (&(|(objectclass=person))(|(|(memberof=CN=group,CN=Users,DC=*,DC=*,DC=*)))(!(userAccountControl:1.2.840.113556.1.4.804:=2)))                         |
| ldapUserFilterGroups          |                                                                                                                                                                        |
| ldapUserFilterMode            | 1                                                                                                                                                                      |
| ldapUserFilterObjectclass     | person                                                                                                                                                                 |
| ldapUuidGroupAttribute        | auto                                                                                                                                                                   |
| ldapUuidUserAttribute         | auto                                                                                                                                                                   |
| turnOffCertCheck              | 0                                                                                                                                                                      |
| useMemberOfToDetectMembership | 1                                                                                                                                                                      |

</details>

### Client configuration
**Browser:** Chrome

**Operating system:** Windows, Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"0UJ5ahFNiOwuUBcQqaNG","remoteAddr":"","app":"core","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'UPDATE \\\"oc_preferences\\\" SET \\\"configvalue\\\" =
 ? WHERE (\\\"userid\\\" = ?) AND (\\\"appid\\\" = ?) AND (\\\"configkey\\\" = ?)' with params [1491221106, \\\"tur\\\", \\\"user_ldap\\\", \\\"lastFeatureRefresh\\\"]:\\n\\nSQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted,
 commands ignored until end of transaction block\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractPostgreSQLDriver->convertExcep
tion('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Ob
ject(Doctrine\\\\DBAL\\\\Driver\\\\PDOPgSql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'UPDATE \\\"oc_pref...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/Connection.php(210): Doctrine\\\\DBAL\\\\Connection->execut
eUpdate('UPDATE \\\"oc_pref...', Array, Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(208): OC\\\\DB\\\\Connection->executeUpdate('UPDATE `*PREFIX...', Array, Array)\\n#4 \\\/va
r\\\/www\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(142): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/Connection.php(299): OC\\\\DB\\\\QueryBuilder\\\\QueryBuil
der->execute()\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AllConfig.php(231): OC\\\\DB\\\\Connection->setValues('preferences', Array, Array, Array)\\n#7 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/User\\\/User.php(347): OC\\\\AllConf
ig->setUserValue('tur', 'user_ldap', 'lastFeatureRefr...', 1491221106)\\n#8 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/User\\\/User.php(157): OCA\\\\User_LDAP\\\\User\\\\User->markRefreshTime()\\n#9 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/user_
ldap\\\/lib\\\/Access.php(703): OCA\\\\User_LDAP\\\\User\\\\User->processAttributes(Array)\\n#10 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/user_ldap\\\/lib\\\/Access.php(675): OCA\\\\User_LDAP\\\\Access->batchApplyUserAttributes(Array)\\n#11 \\\/var\\\/www\\\/ne
xtcloud\\\/apps\\\/user_ldap\\\/lib\\\/User_LDAP.php(218): OCA\\\\User_LDAP\\\\Access->fetchListOfUsers('(&(&(|(objectcl...', Array, 30, 0)\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/User\\\/Manager.php(223): OCA\\\\User_LDAP\\\\User_LDAP->getUser
s('', 30, 0)\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Repair\\\/RepairLegacyStorages.php(214): OC\\\\User\\\\Manager->search('', 30, 0)\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Repair.php(91): OC\\\\Repair\\\\RepairLegacyStorages->
run(Object(OC\\\\Repair))\\n#15 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(298): OC\\\\Repair->run()\\n#16 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(151): OC\\\\Updater->doUpgrade('9.1.4.2', '9.0.51.0')\\n#17 \\\/var\\\/ww
w\\\/nextcloud\\\/core\\\/Command\\\/Upgrade.php(292): OC\\\\Updater->upgrade()\\n#18 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Consol
e\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#19 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(844): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfon
y\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#20 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->
doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#21 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Ap
plication.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#22 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\
/Console\\\/Application.php(146): Symfony\\\\Component\\\\Console\\\\Application->run(NULL, NULL)\\n#23 \\\/var\\\/www\\\/nextcloud\\\/console.php(98): OC\\\\Console\\\\Application->run()\\n#24 \\\/var\\\/www\\\/nextcloud\\\/occ(11): require_once('\\\/var\\\/
www\\\/nextcl...')\\n#25 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractPostgreSQLDriver.php\",\"Line\":91}","level":3,"time":"2017-04-03T12:05:06+00:00","method":"--","url":"--"
,"user":"--","version":"9.0.51.0"}
</details>

#### Browser log
<details>
<summary>Browser log</summary>

GET https://nextcloud/ 503 (Service Temporarily Unavailable)

</details>

**Comment by MorrisJobke** [comment]
cc @icewind1991 @nickvergessen

**Comment by nickvergessen** [comment]
More like @blizzz because this is ldap stuff?

**Comment by blizzz** [comment]
Yes, the triggering call origins from LDAP (and further down by ``OC\Repair\RepairLegacyStorages``), but it's nothing more than a ``OC\AllConf ig->setUserValue('tur', 'user_ldap', 'lastFeatureRefr...', 1491221106)``. So it is against the preference table and the arguments look OK. No error about wrong keys or anything.

@evsigneevk I wonder if there is anything useful in the database log?

**Comment by evsigneevk** [comment]
@blizzz In addition to the database logs presented in the task, there is nothing on this error.
I can add, if I disable the Ldap/AD synchronization, the update successfully completed in 5-10 minutes.

**Comment by blizzz** [comment]
@evsigneevk can you execute the query by hand? Or does it throw any errors?

```sql
UPDATE oc_preferences SET configvalue = '1491221106' WHERE (userid = 'tur') AND (appid = 'user_ldap') AND (configkey = 'lastFeatureRefresh');
```

**Comment by evsigneevk** [comment]
@blizzz, Update is successful. But if I will run upgrade script I get same error.

**Comment by blizzz** [comment]
@evsigneevk OK, thx, this is not unexpected, but good to have the confirmation.

Do you connect directly against the single database, or do you have a cluster or anything?

> In addition to the database logs presented in the task, there is nothing on this error.

You provided logs from Nextcloud, but I refer to the database logs themselves. By default they should be written to ``/var/log/postgresql`` (cf. https://www.postgresql.org/docs/9.5/static/runtime-config-logging.html).

**Comment by evsigneevk** [comment]
@blizzz 
Postgres doesn't has more logs about this error.

**Comment by evsigneevk** [comment]
Hi all.
Do you have news about this issue?

**Comment by MorrisJobke** [comment]
@evsigneevk Did this still happen to you? Sadly we can't reproduce this on our side. As we didn't heard about this issue since then and Nextcloud 10 is also EoL I will close this ticket for now. If this still happen we are happy to provide maybe some debug patches to properly analyze the issue. Thanks

**Comment by wawont** [comment]
I have too problem.
sudo -u www-data php ./occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Checking whether the database schema can be updated (this can take a long time depending on the database size)
 Done                                     
 27/27 [============================] 100%
Checked database schema update
Checking updates of apps
Checked database schema update for apps
Updating database schema
Updated database
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE "oc_preferences" SET "configvalue" = ? WHERE ("userid" = ?) AND ("appid" = ?) AND ("configkey" = ?)' with params [1542100569, "E4D21EFA-95F4-49C4-B51E-25B2B44ACE2D", "user_ldap", "lastFeatureRefresh"]:

SQLSTATE[25P02]: In failed sql transaction: 7 ERROR:  current transaction is aborted, commands ignored until end of transaction block
Update failed
Maintenance mode is kept active
Reset log level

**Comment by kesselb** [comment]
Is this problem still relevant?
