### ISSUE TITLE
[Bug]: NC 28 Action Button Missing Move or Copy File when multiples files are selected 

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/server#42161]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I wanted to move 10 files from one location to another and im not seeing an option to move or copy files 

![image](https://github.com/nextcloud/server/assets/59488153/f02a0ccb-c508-4b93-aa32-0cf05f739473)

### Steps to reproduce

1. select multipool files 
2. no action button
3.

### Expected behavior

Should have an action button like NC 27 did

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by SystemKeeper** [comment]
https://github.com/nextcloud/server/issues/41661
