### ISSUE TITLE
[Bug]: NC 28 App Password Box very wide

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/server#42162]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![image](https://github.com/nextcloud/server/assets/59488153/873fc585-fca1-462a-9012-37daa5bdbffe)

### Steps to reproduce

https://cloud.nextcloud.com/settings/user/security

### Expected behavior

![image](https://github.com/nextcloud/server/assets/59488153/42b1698d-3a1f-4dac-b46c-b67d41596705)

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by arnowelzel** [comment]
In addition: the elements are also not at the same vertical position since the input element has a top margin and the button right to it does not.

I added the following CSS rules with [Custom CSS](https://apps.nextcloud.com/apps/theming_customcss) as a workaround:

```
.app-name-text-field {
  margin-top: 0 !important;
  max-width: 370px;
}
```

**Comment by sgzmd** [comment]
This no longer seems to be a problem for the version in `master` - WAI?

![image](https://github.com/nextcloud/server/assets/92161/bb26a2b2-c025-4066-a9b3-47af7bc06e2b)

**Comment by AndyXheli** [comment]
Still on issue on NC29.0.3

**Comment by arnowelzel** [comment]
I can not reproduce this here - NC 29.0.3:

![grafik](https://github.com/nextcloud/server/assets/6613614/0186fa1d-4a90-4b15-b2c1-2fd6630081b1)
