### ISSUE TITLE
OCP API for optional indices

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#42169]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

As a Nextcloud app developer I might identify missing database indices like https://github.com/nextcloud/mail/issues/9160. Applying the indices in a migration means they are always added and tables with data block the migration for x seconds/minutes/hours depending on table size.

**Describe the solution you'd like**

Allow apps to hook into the optional indices API of server so that they can also advertise a missing, but optional index that admins can apply later on.

**Describe alternatives you've considered**

N/a

**Additional context**

This was started in https://github.com/nextcloud/server/pull/25471 but closed due to inactivity.

**Comment by ChristophWurst** [comment]
When adding this API we might also consider adding support for *replacing* indices.

I noticed that occasionally we have indices that are not ideal. A migration could drop the old index (relatively cheap) and add the new one through this API (relatively expensive) but that means the instance is slow in the time between the two events. If the API took care of dropping, the time of slowness would be minimal.

**Comment by come-nc** [comment]
But we have that already, no?

https://nextcloud-server.netlify.app/classes/ocp-db-events-addmissingindicesevent

**Comment by come-nc** [comment]
Also documented in https://docs.nextcloud.com/server/latest/developer_manual/basics/storage/migrations.html#adding-indices

**Comment by ChristophWurst** [comment]
Right! I searched closed PRs but could only find the status checks API. Awesome :pray:
