### ISSUE TITLE
[Bug]: Missing space char in german translation file for "Share with " -> "Teilen mit" causing lingual issue

### ISSUE THREAD

**Issue by SebastianHanz** [nextcloud/server#42179]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Problem caused by missing " " in translation files in /apps/files_sharing/l10n/de*.js and de*.json

![2023-12-12_17h34_23](https://github.com/nextcloud/server/assets/66777707/9e860395-a12a-4fcb-aa3b-06be43e6f818)

### Steps to reproduce

1. Go to share view of any shared folder
2. Click on the "three-dotts-button" right beside the persons name to see details of sharing

### Expected behavior

Instead of "Teilen mitPascal" it should be "Teilen mit Pascal"

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by SystemKeeper** [comment]
See also discussion at https://github.com/nextcloud/server/pull/40700

**Comment by SystemKeeper** [comment]
Reported at transifex
