### ISSUE TITLE
[Bug]: gpg key not available

### ISSUE THREAD

**Issue by tobhv** [nextcloud/server#42180]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

According to https://nextcloud.com/install/#instructions-server there is a gpg signature here: https://nextcloud.com/nextcloud.asc but that gives 404 when i visit it. The alternative method to retrieve the key does not work for me. I get a message that the key contains no user id.

### Steps to reproduce

1. Visit https://nextcloud.com/install/#instructions-server
2. go to "community project", "Archive":
![image](https://github.com/nextcloud/server/assets/118474835/e0975442-f811-461f-a0a7-fa06fe0d2735)

4. click on "is here" link.
5.404 error returns:
```
Connecting to nextcloud.com (nextcloud.com)|85.10.195.17|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-12-12 21:14:14 ERROR 404: Not Found.
```

### Expected behavior

nextcloud.asc file is available at the documented place

### Installation method

None

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

8.2

### Web server

Apache

### Database engine version

mariadb 10.6

### Is this bug present after an update or on a fresh install?

I think the issue is there since nextcloud 28 was released. 

### Are you using the Nextcloud Server Encryption module?

No

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment]
cc @peterwebdesign

**Comment by Altahrim** [comment]
Just fixed it :) Thanks!
