### ISSUE TITLE
[Bug]: NC28 F2V Three-dots menu in breadcrumbs does not open

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/server#42199]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The three dots menu that appears when the breadcrumbs bar gets ellipsized does not open.

The console gives the following error:
```
TypeError: n is undefined
    render vue-router.esm.js:1097
    VueJS 19
    o index-daca53bd.mjs:4460
    o index-daca53bd.mjs:4451
    d index-daca53bd.mjs:4488
    o index-daca53bd.mjs:4453
    d index-daca53bd.mjs:4488
    o index-daca53bd.mjs:4453
    d index-daca53bd.mjs:4488
    o index-daca53bd.mjs:4453
    w index-daca53bd.mjs:4542
    w index-daca53bd.mjs:4578
    w index-daca53bd.mjs:4542
    w index-daca53bd.mjs:4578
    w index-daca53bd.mjs:4542
    w index-daca53bd.mjs:4578
    ko index-daca53bd.mjs:4646
    _update index-daca53bd.mjs:3176
    s index-daca53bd.mjs:3206
    get index-daca53bd.mjs:3021
    run index-daca53bd.mjs:3045
    ta index-daca53bd.mjs:3310
    Si index-daca53bd.mjs:2972
    Ci index-daca53bd.mjs:2945
    promise callback*Ai index-daca53bd.mjs:2951
    Si index-daca53bd.mjs:2978
    update index-daca53bd.mjs:3349
    update index-daca53bd.mjs:3042
    notify index-daca53bd.mjs:2184
    set index-daca53bd.mjs:2306
    set index-daca53bd.mjs:3898
    VueJS 5
    gi index-daca53bd.mjs:2916
    run index-daca53bd.mjs:3053
    ta index-daca53bd.mjs:3310
    Si index-daca53bd.mjs:2972
    Ci index-daca53bd.mjs:2945
    promise callback*Ai index-daca53bd.mjs:2951
    Si index-daca53bd.mjs:2978
    update index-daca53bd.mjs:3349
    update index-daca53bd.mjs:3042
    notify index-daca53bd.mjs:2184
    set index-daca53bd.mjs:2306
    set index-daca53bd.mjs:3898
    openMenu NcActions.mjs:197
    gi index-daca53bd.mjs:2916
    n index-daca53bd.mjs:2465
    gi index-daca53bd.mjs:2916
    $emit index-daca53bd.mjs:3152
    VueJS 2
vue.runtime.esm.js:3049:16
```

This comes from my productive setup, so please forgive that this is not the debug output. I will try to reproduce this on my dev environment as well.

### Steps to reproduce

1. Navigate to a folder deeply nested.
2. Resize the window to have the breadcrumbs bar ellipsized.
3. Try to open the three-dots menu containing the hidden crumbs.

### Expected behavior

The menu should open without issue and show the hidden crumbs.

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by SystemKeeper** [comment]
https://github.com/nextcloud/server/issues/42137

**Comment by raimund-schluessler** [comment]
Indeed, the symptom is the same. The error message is slightly different, though. Probably still closely related. Closing then.
