### ISSUE TITLE
Password Protected Shared Directories Upon Opening Are Buggy

### ISSUE THREAD

**Issue by cwmke** [nextcloud/server#422]
### Steps to reproduce
1. Select a directory and click on the sharing icon.
2. Click Share Link and Password Protect
3. Set Password
4. Open newly created link in browser (Chromium or Firefox)
5. Enter Password

### Expected behaviour
After entering the password, you should be in a clean page with no issues and be able to download the items from within the directory.

### Actual behaviour
**Chromium**
![screenshotnextcloud](https://cloud.githubusercontent.com/assets/1923967/16895556/5dd504f0-4b40-11e6-9480-3b026c37388c.png)

**Firefox**
![screenshotnextcloud2](https://cloud.githubusercontent.com/assets/1923967/16895568/bf97eb6c-4b40-11e6-867f-6244e565cba5.png)

### Server configuration
**Operating system**: Arch Linux

**Web server:** Arch Linux

**Database:** Postgresql 9.5.3-1

**PHP version:** 7.0.8-1

**Nextcloud version:** Nextcloud 9.0.52 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated nextCloud

**Where did you install Nextcloud from:** AUR

**Signing status (Nextcloud 9.0 and above):**
<details>
<summary>Signing status</summary>

```
File not found. 
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - activity: 2.2.1
  - admin_audit: 1.0.0
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - mail: 0.5.2
  - notifications: 0.2.3
  - ownnote: 1.08
  - password_policy: 1.0.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: 0.9.1
  - templateeditor: 0.1
  - theming: 0.1.0
  - updatenotification: 0.1.0
Disabled:
  - bookmarks
  - encryption
  - external
  - galleryplus
  - news
  - user_external
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "<Domain Name>",
        ],
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/_<domainname>_\/cloud",
        "htaccess.RewriteBase": "\/cloud",
        "dbtype": "pgsql",
        "version": "9.0.52.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "logtimezone": "America\/Chicago",
        "installed": true,
        "defaultapp": "files",
        "mail_smtpmode": "smtp",
        "mail_from_address": "nextCloud",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "***REMOVED SENSITIVE VALUE***",
        "cipher": "AES-256-CFB",
        "updatechecker": true,
        "check_for_working_htaccess": true,
        "loglevel": 0,
        "preview_libreoffice_path": "\/bin\/libreoffice",
        "theme": "",
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 47.0.1; Chromium 51.0.2704.106 (64-bit)

**Operating system:** Arch Linux

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Error	gallery	Exception: Missing password (401)	2016-07-16T10:06:46-05:00	-- _This appears x20 before this section_
Error	PHP	Undefined variable: share at /usr/share/webapps/nextcloud/lib/private/share20/manager.php#996	2016-07-16T10:06:35-05:00	--
Error	PHP	Undefined variable: share at /usr/share/webapps/nextcloud/lib/private/share20/manager.php#996	2016-07-16T10:06:29-05:00	--
Error	PHP	Undefined variable: share at /usr/share/webapps/nextcloud/lib/private/share20/manager.php#996	2016-07-16T10:06:24-05:00	--
Error	PHP	Undefined variable: share at /usr/share/webapps/nextcloud/lib/private/share20/manager.php#996	2016-07-16T10:06:18-05:00
```
</details>

#### Browser log
<details>
**Firefox**
```
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead. jquery.min.js:5:17117
Content Security Policy: Directive 'frame-src' has been deprecated. Please use directive 'child-src' instead. (unknown)
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead jquery.min.js:1:0
Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src https://DOMAIN 'unsafe-eval'"). 2zngub5XI6Pk5ND
GET 
XHR 
https://DOMAIN/cloud/index.php/apps/gallery/config.public [HTTP/1.1 401 Unauthorized 79ms]
PROPFIND 
XHR 
https://DOMAIN/cloud/public.php/webdav/ [HTTP/1.1 401 Unauthorized 83ms]
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.
```

**Chromium**
```
https://DOMAIN/cloud/index.php/apps/gallery/config.public?extramediatypes=1&token=2zngub5XI6Pk5ND 401 (Unauthorized)send @ jquery.min.js?v=742875b…:6ajax @ jquery.min.js?v=742875b…:6x.(anonymous function) @ jquery.min.js?v=742875b…:6getJSON @ jquery.min.js?v=742875b…:6(anonymous function) @ galleryfileaction.js?v=742875b…:215c @ jquery.min.js?v=742875b…:4fireWith @ jquery.min.js?v=742875b…:4ready @ jquery.min.js?v=742875b…:4q @ jquery.min.js?v=742875b…:4
Navigated to https://DOMAIN/cloud/index.php/s/2zngub5XI6Pk5ND
```
</details>

The download button still works either way but any visitor who sees this would likely be worried and not think to do so.  Thanks for any efforts!

**Comment by MorrisJobke** [comment]
> Error   PHP Undefined variable: share at /usr/share/webapps/nextcloud/lib/private/share20/manager.php#996   2016-07-16T10:06:35-05:00   --

This is https://github.com/nextcloud/server/issues/499

This looks very much like a caching issue (at least I had this when the old JS code was executed after an update to handle the public page). Could I ask you to try to clear the caches in your browser and try again? Could you also try to disable the gallery app and reload the page then?

**Comment by cwmke** [comment]
I just tried both with Gallery enabled and disabled, same problem.

**Comment by MorrisJobke** [comment]
@LukasReschke @schiessle Any idea what this is?

**Comment by rullzer** [comment]
It sounds very familiar.
@oparoz do you remember?

**Comment by oparoz** [comment]
Well there were some auth issues before, but they were related to the regexp responsible to determine where to load Gallery, which isn't the problem here.

Looking at the logs, it seems like the password is not accepted, maybe a problem with 9.0.52?

@cwmke, it would be good if you could upgrade to 9.0.53.

**Comment by cwmke** [comment]
From the limited testing I can do from Android it seems to be all set. I'm away from my Linux computer for the next week so I'll confirm when I'm back home.

**Comment by cwmke** [comment]
I can confirm the problem is gone with Firefox on Linux. Thanks!
