### ISSUE TITLE
[Bug]: drag&drop upload of folder fails

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#42252]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I can't upload a folder via drag&drop

### Steps to reproduce

1. Try to upload a folder via drag&drop from your local file manager

With Chrome the upload get stuck:

![image](https://github.com/nextcloud/server/assets/1589737/d9b56124-2f12-43f4-a47d-6dbc4f930c26)

On Firefox the upload gets shows as successful:

![image](https://github.com/nextcloud/server/assets/1589737/6bfa3c8e-b742-443b-837f-d0a5371f0be3)

But the result is not the folder with the files but a empty file with no mimetype:

![image](https://github.com/nextcloud/server/assets/1589737/d63d1a4b-6e10-4f74-bf82-1ec1a4187379)

### Expected behavior

Either a successful upload or a meaningful error message that drag&drop of folders is not supported

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by hibobmaster** [comment]
In my scenario, firefox can only upload file to root folder. For other sub folder, i got
``` 
XMLHttpRequest.setRequestHeader: Cannot convert argument 2 to ByteString because the character at index 60 has value 25991 which is greater than 255.
```
Upload stuck at `estimating time left` and nothing happen.

**Comment by YYH2913** [comment]
The same problem in chrome
xhr.js:207 Uncaught (in promise) TypeError: Failed to execute 'setRequestHeader' on 'XMLHttpRequest': String contains non ISO-8859-1 code point.
    at xhr.js:207:17
    at Object.T [as forEach] (utils.js:265:10)
    at xhr.js:206:13
    at new Promise (<anonymous>)
    at xhr (xhr.js:49:10)
    at E.p (dispatchRequest.js:51:10)
    at E.request (Axios.js:146:33)
    at Function.request (bind.js:5:15)
    at files-main.js?v=fc5569f1-0:2:313816
    at files-main.js?v=fc5569f1-0:2:313860

Environment:
PHP Version: 8.1.2
MySQL Version: 10.6.12
Apache Version: 2.4.52
Operating System: Ubuntu 22.04.2 LTS
Language: Simplified Chinese

**Comment by solracsf** [comment]
Cc @susnux @skjnldsv 🆘

**Comment by skjnldsv** [comment]
@solracsf already have enough notifications, the right labels are assigned, just wait for someone to start fixing this

**Comment by murray3k** [comment]
Concerning the errors when uploading a folder into a subfolder:
I think there might be a slash "/" missing as a directory separator in line 91 in the DropService.ts between `${path}` and `${directory.name}`:
https://github.com/nextcloud/server/blob/bac05cae5b53cc208b7edaa6b2b2a5de86f25035/apps/files/src/services/DropService.ts#L91

Because when I create a folder "foo" and then drag&drop the folder "bar" into it, `absolutPath` looks like this:
`absolutPath: "/files/[myusername]/foobar"` instead of `absolutPath: "/files/[myusername]/foo/bar"`.

Hope this helps somebody. First time looking at Nextcloud code. I don't feel comfortable submitting a patch just yet.
