### ISSUE TITLE
[Bug]: No drop area for empty folders

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#42251]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Empty folders have no drop area

### Steps to reproduce

1. Create a new empty folder
2. Navigate to the folder
3. Try to upload a file via drag&drop

-> not possible because there is no drop area

### Expected behavior

Having a drop area like for folders with content

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by nook24** [comment]
I have the same issue. Drag&Drop upload is not working, also for folders with files in it. I can see the dropzone, but Firefox and Chrome simply open the image i try to drag and drop

[Nextcloud Hub 7](https://nextcloud.com/) (28.0.0)

**Comment by ethrgeist** [comment]
With 28.0.1 the drop zones are there but are not working.

Any news on that?

**Comment by skjnldsv** [comment]
@ethrgeist https://github.com/nextcloud/server/pull/42409
