### ISSUE TITLE
9.2.5.3/3.1 In the breadcrumb navigation, the directory name is being overridden by the use of "aria-label" attributes. This could cause issues when using voice control programs.

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#42265]
9.2.5.3/3.1 In the breadcrumb navigation, the directory name is being overridden by the use of "aria-label" attributes. This could cause issues when using voice control programs.

![image](https://github.com/nextcloud/server/assets/42591237/d367fd4c-ccd3-4729-bac9-41f9403b7e4b)

**Comment by JuliaKirschenheuter** [comment]
In progress because of https://github.com/nextcloud/server/pull/42379
