### ISSUE TITLE
9.1.3.1b/5.1 The "Search" window includes lists, with each of these lists having a heading. However, these headings have been implemented as direct children of the <ul> element, which is not allowed and can lead to issues with screen reader output.

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#42276]
https://report.bitvtest.de/cbedb5ef-4815-4cba-a83d-995599c178c3.html#checkpoint-1d5eadb58d-v5-n1

9.1.3.1b/5.1 The "Search" window includes lists, with each of these lists having a heading. However, these headings have been implemented as direct children of the <ul> element, which is not allowed and can lead to issues with screen reader output.

![image](https://github.com/nextcloud/server/assets/42591237/3f2ea457-5eb7-4cff-9db6-9f781bc56c9a)

**Comment by JuliaKirschenheuter** [comment]
was already done by https://github.com/nextcloud/server/issues/41830
