### ISSUE TITLE
[Bug]: `occ maintenance:install` fails on read-only htdocs directory

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud/server#42286]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since Nextcloud 27.1.5 and Nextcloud 28.0.0 the occ command for manual install requires write-access to the htdocs directory. This were not the case before and allowed Nextcloud to be deployed via the SNAP environment.

Ref: https://github.com/nextcloud-snap/nextcloud-snap/pull/2631#issuecomment-1855931895

This prevents us from updating our snap packges at the moment as the snap environment is read-only for security reasons.

Is there a workaround for this to execute manual install without the need for write-access?

### Steps to reproduce

1. Create a read-only webspace.
2. Install Nextcloud 27.1.5 or 28.0.0 there.
3. Execute the installation process via the command `occ maintenance:install`.
4. The command will fail because it requires write-access to the htdocs direcotry.

### Expected behavior

Do not require write-access on `occ maintenance:install` or at least try-catch and skip the steps that would write to the htdocs directory, so the command will execute successfully - like in v27.1.4 and earlier.

### Installation method

Community SNAP package

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
The first error in the linked issue is the result of a recently added check to make sure there's enough disk space available before writing out the `config.php`. This is important since avoids truncating the existing `config.php`. It was added in #41544 and the code is as follows:

https://github.com/nextcloud/server/blob/cd32db63f7acba753888c8f5b60a30d1d10035e1/lib/private/Setup.php#L562-L573

As for `occ maintenance:install` I don't see anything significant that's changed lately in regards to write related behavior. The only change made for NC28 was increased verbosity. Which might help you uncover what's going on if you activate it.

The code for the command is here:

https://github.com/nextcloud/server/blob/master/core/Command/Maintenance/Install.php

**Comment by solracsf** [comment]
Problem is at line 568.
To handle these (SNAP) cases, it should just `return false`, but it actually `throw`s.
@szaimen any objections here?

**Comment by szaimen** [comment]
I think we should rather chevk if the dir is read only and then return false...

**Comment by kyrofa** [comment]
Yes, the snap is contained within a squashfs image, which is by definition 100% full and read-only.

**Comment by kyrofa** [comment]
> The first error in the linked issue is the result of a recently added check to make sure there's enough disk space available before writing out the config.php

Remember that config.php could be held entirely out of the webroot.

**Comment by solracsf** [comment]
PR at https://github.com/nextcloud/server/pull/42298

**Comment by kyrofa** [comment]
Thank you, @solracsf!
