### ISSUE TITLE
[Translation]: Menu "Move or copy" is not translated to different Languages

### ISSUE THREAD

**Issue by ZID-TU-Graz** [nextcloud/server#42301]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When using the "Move and Copy", only the title is translated.
Buttons and "Name", "Size", "Modified" in the files table are in english
tested with german and french.
Note: No open translations found on transifex for german language.
Screenshot with german settings:
![275784533-15be2fba-2138-4d09-9277-495c4f800a1a](https://github.com/nextcloud/server/assets/100593683/e4068237-849b-48c4-8872-a7e5a3cb16c4)

### Steps to reproduce

Steps to reproduce

    Choose a Language different than English (e.g. german or french)
    Go to files and right click or use the 3 dots on a file/folder
    Click on "Move or copy" in the dropdown menu (will have a different name due to language change in step 1)

Nextcloud Version: 27.1.3

### Expected behavior

Menu and buttons shown in selected language.

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Nextcloud Version: 27.1.3
```

**Comment by susnux** [comment]
This is already fixed with Nextcloud 27.1.5 in #42034
