### ISSUE TITLE
[Bug]: Links to documentation in "Security & setup warnings" are outdated

### ISSUE THREAD

**Issue by amlamarra** [nextcloud/server#42317]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

This has been a (minor) issue for a while and I figured I'd report it. I just updated to v28.0.0. The links to the documentation in "Security & setup warnings" (under Administration Settings) are outdated. For instance, this warning:

- This instance is missing some recommended PHP modules. For improved performance and better compatibility it is highly recommended to install them: bz2. For more details see the [documentation ↗](https://docs.nextcloud.org/server/9/go.php?to=admin-php-modules).

Not only is it trying to link to version 9, but also "nextcloud.org" which hasn't worked in a while.

### Steps to reproduce

1. Click on your profile button in the top-right corner
2. Go to "Administration settings"
3. If there are any security & setup warnings, check the link to the documentation.

### Expected behavior

Using the example I gave in the description, instead of linking to https://docs.nextcloud.org/server/9/go.php?to=admin-php-modules, it should probably link to https://docs.nextcloud.com/server/latest/go.php?to=admin-php-modules.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by amlamarra** [comment]
Forgot to mention, when I was searching to see if this was already reported, I only found 1 similar (if not the same) issue:
https://github.com/nextcloud/server/issues/15561

**Comment by joshtrichards** [comment]
Hmm. Works for me. :-)

What does the `OC_Version` line contain in the `/version.php` located in your installation directory?

**Comment by amlamarra** [comment]
$ grep OC_Version /var/www/nextcloud/version.php
    $OC_Version = array(28,0,0,11);
    $OC_VersionString = '28.0.0';
    $OC_VersionCanBeUpgradedFrom = array (

**Comment by joshtrichards** [comment]
Do you by chance having a custom theme active?

Because we don't any references to `docs.nextcloud.org` anywhere in the code and the only other place I can see you could pick this up from is via `~/themes` in you rinstallation directory if you have your own from a long time ago.

**Comment by amlamarra** [comment]
I _was_ using the Breeze Dark theme before Nextcloud had a built-in dark theme. I just checked and it was still installed (though disabled since the update). I just uninstalled it and checked, but the links are still old. Any idea how I can fix this?

**Comment by joshtrichards** [comment]
The only two places I can think of are stale parameters that might appear under:

`occ theming:config`
or
`occ config:list theming`

**Comment by amlamarra** [comment]
Those 2 commands did not show any stale values. However, I did see a `defaults.php` file and a `core/` directory in my `/var/www/nextcloud/themes` directory. I removed those, refreshed the page and now the links are working correctly.

That `defaults.php` file has a `class OC_Theme` with a bunch of functions in there. These 2, in particular, are probably the culprits:
```php
    /**
     * Returns the documentation URL
     * @return string URL
     */
    public function getDocBaseUrl() {
        return 'https://docs.nextcloud.org';
    }

    public function buildDocLinkToKey($key) {
        return $this->getDocBaseUrl() . '/server/9/go.php?to=' . $key;
    }
```

**Comment by para28711** [comment]
Stephen f Balogh
