### ISSUE TITLE
[Bug]: trusted_domains stopped working/broken with host with a port number

### ISSUE THREAD

**Issue by levaidaniel** [nextcloud/server#42330]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I'm using nextcloud/nginx-proxy in a docker environment (official images from Docker Hub), worked perfectly until somewhere the beginning of December. Unfortunately I cannot pinpoint the exact version, as I just automatically update the containers to the `latest` tag and restart. Now it's at 27.1.5.1.
I managed to track it down to nextcloud possibly ignoring/messing up the port number in the `trusted_domains` setting.

I have a port number, let's say 123456 forwarded on the host to the nginx container's 443. Then nginx proxies this to the nextcloud container's 80, essentially offloading and taking care of https. This has worked perfectly fine until now, really - it has. No config change, not to _nginx_, not to _nextcloud_, just updating both until recently it broke.

Nextcloud config:
```
$ ./occ config:list system
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.domain.com:123456"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "27.1.5.1",
        "overwrite.cli.url": "https:\/\/cloud.domain.com:123456",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "588",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 0
    }
}
```

This now results in the ominous "Access through untrusted domain\nPlease contact your administrator. If you are an administrator, edit the "trusted_domains" setting in config/config.php like the example in config.sample.php. ", while accessing https://cloud.domain.com:123456 (I get redirected to https://cloud.domain.com:123456/ **login**, though).

If I remove the port number from the `trusted_domains` setting and I try to access the same host again (https://cloud.domain.com:123456), the port gets removed from the URI in the browser, and I get redirected to https://cloud.domain.com/login which of course messes up the https connection and I'm greeted with my browser's perfectly legit warning. So **I add back** the port into the URI, essentially just navigating to https://cloud.domain.hu:123456/login and I'm greeted with the proper login page...
After logging in, the port gets removed from the URI in the browser again, after putting it back in, I can use Nextcloud.

Somewhere along the road, the last couple of (Idk, maybe 2-3) updates to the container on Docker Hub (or Nextcloud release, I don't how closely the container builds follow the actual release cycle) broke this settings with a port number, IMHO.

Does this ring a bell to anyone? Any recent/not so recent commits that could possibly affect this?

Thanks in advance for any pointers,
Daniel

### Steps to reproduce

1. Set trusted_domains to a value with a :PORT 
2. Access is broken.

### Expected behavior

trusted_domains setting works with a host that has a port number defined.

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.domain.com:123456"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "27.1.5.1",
        "overwrite.cli.url": "https:\/\/cloud.domain.com:123456",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "588",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 0
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - bruteforcesettings: 2.7.0
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contactsinteraction: 1.8.0
  - dashboard: 7.7.0
  - dav: 1.27.0
  - encryption: 2.15.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - nextcloud_announcements: 1.16.0
  - notes: 4.9.1
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - photos: 2.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - spreed: 17.1.3
  - support: 1.10.0
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_totp: 9.0.0
  - twofactor_webauthn: 1.3.2
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - admin_audit: 1.17.0
  - files_external: 1.19.0
  - password_policy: 1.17.0 (installed 1.17.0)
  - richdocuments: 8.2.3 (installed 8.2.3)
  - suspicious_login: 5.0.0
  - user_ldap: 1.17.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"xBG8wWV71T3y6BbMDvlj","level":1,"time":"2023-12-16T15:06:56+00:00","remoteAddr":"172.24.0.2","user":"--","app":"core","method":"GET","url":"/","message":"Trusted domain error. \"172.24.0.2\" tried to access using \"cloud.domain.com\" as host.",
"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0","version":"27.1.5.1","data":{"app":"core"}}
{"reqId":"xBG8wWV71T3y6BbMDvlj","level":0,"time":"2023-12-16T15:06:56+00:00","remoteAddr":"172.24.0.2","user":"--","app":"encryption","method":"GET","url":"/","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the
 application class instead.","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0","version":"27.1.5.1","data":{"app":"encryption"}}
```

**Comment by joshtrichards** [comment]
No obvious relevant commits so far, but in the mean time setting `overwritehost` may be a workaround for you.

**Comment by levaidaniel** [comment]
Hah, that did the trick! Nice workaround, thanks!

**Comment by kesselb** [comment]
`overwritehost` is not a workaround. 
Your container is still using port 443 and Nextcloud is therefore unable to detect that actual port. 

As explained in https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html you need to use `overwritehost`. 

I have no idea why it worked in the past only with trusted_domains.
It was likely unintended.

**Comment by kesselb** [comment]
It could also work by configuring trusted_proxies properly. 
But your nginx container does not know the actual port either and therefore cannot forward the port to Nextcloud.
So `overwrite*` is the way to go.
