### ISSUE TITLE
[Bug]: redis configured, but the status page will say not in use

### ISSUE THREAD

**Issue by tuxmaster5000** [nextcloud/server#42340]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After update from 26 to 27 the overview page noted, that the database will be used for file locking
But redis  is configured for use and no error are logged. 

### Steps to reproduce

1. Open the overview page

### Expected behavior

No warnings

### Installation method

Official All-in-One appliance

### Nextcloud Server version

27

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "YYYYY"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "maxZipInputSize": 83886080,
        "allowZipDownload": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpsecure": "",
        "log_type": "syslog",
        "loglevel": 1,
        "logtimezone": "Europe\/Berlin",
        "log_authfailip": true,
        "theme": "",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "maintenance": false,
        "asset-pipeline.enabled": true,
        "updatechecker": true,
        "htaccess.RewriteBase": "\/",
        "mysql.utf8mb4": true,
        "overwrite.cli.url": "https:\/\/XXXXX",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "dicomviewer",
            "socialsharing_email"
        ],
        "default_phone_region": "DE",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        }
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - bruteforcesettings: 2.7.0
  - calendar: 4.6.0
  - camerarawpreviews: 0.8.4
  - checksum: 1.2.2
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.5.0
  - contactsinteraction: 1.8.0
  - dav: 1.27.0
  - deck: 1.11.2
  - dicomviewer: 1.2.5
  - drawio: 2.1.4
  - eidlogin: 1.0.15
  - federatedfilesharing: 1.17.0
  - files: 1.22.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_retention: 1.16.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - groupfolders: 15.3.1
  - guests: 2.5.1
  - lookup_server_connector: 1.15.0
  - metadata: 0.19.0
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - piwik: 0.12.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - quota_warning: 1.18.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - sharelisting: 1.2.0
  - socialsharing_email: 3.0.1
  - survey_client: 1.15.0
  - systemtags: 1.17.0
  - tasks: 0.15.0
  - terms_of_service: 2.3.1
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - twofactor_totp: 9.0.0
  - twofactor_webauthn: 1.3.2
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - workflowengine: 2.9.0
Disabled:
  - dashboard: 7.7.0 (installed 7.0.0)
  - encryption: 2.15.0
  - federation: 1.17.0 (installed 1.6.0)
  - files_external: 1.19.0 (installed 1.7.0)
  - files_trashbin: 1.17.0 (installed 1.10.1)
  - files_versions: 1.20.0 (installed 1.0.3)
  - firstrunwizard: 2.16.0 (installed 1.0)
  - logreader: 2.12.0 (installed 2.10.0)
  - support: 1.10.0 (installed 1.5.0)
  - suspicious_login: 5.0.0
  - user_ldap: 1.17.0
  - weather_status: 1.7.0 (installed 1.1.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
nothing will logged
```

### Additional info

No SELinux denied are logged.

**Comment by joshtrichards** [comment]
Unable to reproduce.

> Official All-in-One appliance

Are you certain you're using the AIO image or was that a typo?

If you're *not* using AIO, please check verify your Redis server is receiving connections from Nextcloud by running something like [`redis-cli monitor`](https://redis.io/commands/monitor/) and generating some Nextcloud traffic. Make sure you use the same UNIX socket path specified in your Nextcloud `config.php` so that you're verifying the same connectivity path.

Unless you see Nextcloud traffic there, this is a configuration/local environment matter. Follow-up at the Nextcloud Help Forum - https://help.nextcloud.com if you need troubleshooting assistance.

Feel free to re-open if you determine this really does look like a bug not a config matter.

**Comment by tuxmaster5000** [comment]
Hi @richardhj 
the config is done like written in the documentation.
And the php process can reach the redis server.

**Comment by tuxmaster5000** [comment]
And creating an "debug" script will also work:
```
<?php

ini_set( 'display_errors', 'On' );
$redis = new Redis();

$redis->pconnect( '/run/redis/redis.sock' );

echo 'sending ping... ';
echo $redis->ping() . "\n";

echo 'setting name ... ' . "\n";
$redis->set( 'Name', 'Renich Bon Ciric' );

echo 'getting name. The name is: ';
echo $redis->get( 'Name' ) . "\n";

?>

So the connection PHP -> Redis will work.

**Comment by tuxmaster5000** [comment]
After hour's of investigation I have found the real problem.
It will be the  OPcache. When the config files was modified, the cache will not be rebuild sometimes.
The solution was: remove all OPcache files, and restart the php-fpm service.
