### ISSUE TITLE
[Bug]: Copy/ Move files to a nested favorite folder returns 404 error

### ISSUE THREAD

**Issue by major-mayer** [nextcloud/server#42363]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When you try to move or copy a file to a favorite folder that is itself a subfolder of another folder, the folder cannot be found, because the path is incorrectly calculated.
The file picker stays at this screen:
![grafik](https://github.com/nextcloud/server/assets/17907799/ea2aeac4-0ab2-4952-a7ce-94a6e8fdf588)

The server returns the following:
```xml
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File with name /[here is the parent path missing]/Sonstiges could not be located</s:message>
</d:error>

```

### Steps to reproduce

1. Create a subfolder
2. Add it to favorites
3. Click on the "move/ copy to" button for some file 
4. Click on "Favorites"
5. Click on the newly added subfolder
6. Loading never finishes

### Expected behavior

The subfolder can be found and opens

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Other

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Web server is Caddy

**Comment by joshtrichards** [comment]
I cannot reproduce this behavior. It succeeds for me.

I wonder if whatever is triggering this in your environment is similar to #42469.

What are the underlying folders? Anything like groupfolders, External Storage, sharing, etc. involved?

What are the underlying filesystem(s)?

**Comment by major-mayer** [comment]
IIRC I just used a normal folder for my test, but maybe it was also shared with some other people.
The problem is, that I cannot check it again currently, because my host system is down right now.
But in general, the underlying file system should be ext4 i guess (standard Ubuntu installation), but the Nextcloud data is within an NFS share to a ZFS (True)NAS system.

**Comment by susnux** [comment]
I can reproduce this and will work on a fix.

**Comment by major-mayer** [comment]
Thanks for the fix ❤️
