### ISSUE TITLE
[Bug]: Allow multi-select for files in trash

### ISSUE THREAD

**Issue by major-mayer** [nextcloud/server#42364]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
In the normal files app you can easily select multiple files by using the checkbox for one file first, holding SHIFT and then clicking on another file.
All files in between those two will be selected and can then e.g. be copied.

I noticed that this is not possible when you are in the trash bin.
Even worse, when you hold SHIFT (as you are used) and then click on another file, it downloads this file in a new browser windows...?
But it would be really useful to have such a feature as well, since there is a good chance that you want to restore/ permanently delete multiple files.
Selecting all files individually can be a very tedious task.

**Describe the solution you'd like**
I would like to have a solution similar to the files app, i.e. select one file, hold SHIFT and then click on another file to select all files in between.

**Describe alternatives you've considered**
None, since this works pretty well.

**Additional context**
None

**Comment by solracsf** [comment]
Juste to be clear; is this request valid for v28?

**Comment by emoral435** [comment]
This works on v29, are you requesting that we backport this feature? What version are you using?

**Comment by major-mayer** [comment]
Ah that's good to know.
I'm currently on v 27.1 and if it's be possible, I would like to see the feature also there.

**Comment by emoral435** [comment]
Perfect! I will look into this, and incorporate it into v27 👍

**Comment by major-mayer** [comment]
Thank you so much :heart:

**Comment by emoral435** [comment]
Checking back here - on the newest, stable version of 27, it seems as if the deleted files section has the newest checkbox features, but main files app has the feature no longer there. Heres how it looks like for me:
![chrome_5J3IBPWnBH](https://github.com/nextcloud/server/assets/110193237/c7e80ae3-dbe0-4fb7-817d-a031704a974f)
Can you confirm if this is how your version looks like?

**Comment by solracsf** [comment]
I can confirm multi-select working on Trash on v27.1.6, but not on Files 🤔

**Comment by emoral435** [comment]
I can assign myself to the issue if people want the feature added back!

**Comment by major-mayer** [comment]
I will probably switch to Nextcloud 28 quite soon anyway, but it would still be good if this feature is working, since 27 is a supported version (yet).

**Comment by emoral435** [comment]
True, will start working on it 👍
