### ISSUE TITLE
[Bug]: Protocol Page blank and External  subscribed calendars not showing up

### ISSUE THREAD

**Issue by Just4Link** [nextcloud/server#42370]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since update to 28.0.0 the protocol page is only a blank page with  no content, even in incognito mode with no browser extensions (firefox and chrome)
When i subscribe to external calendars like google the events will not show up anymore. Same bahavior when i add a holiday calendar in calendar options.

### Steps to reproduce

1. Protocol problem -> just browse to protocol page
2. Calendar problem -> add a holiday calendar from nextcloud calendar settings

### Expected behavior

Protocol should shown and Calendar events should also shown

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloudbak.ffzonecloud.com"
        ],
        "dbtype": "mysql",
        "version": "28.0.0.11",
        "overwrite.cli.url": "https:\/\/nextcloudbak.ffzonecloud.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\APCu",
        "upgrade.disable-web": true
    }
}
```

### List of activated Apps

```shell
- activity: 2.20.0
  - calendar: 4.6.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.0
  - sharebymail: 1.18.0
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - encryption: 2.16.0
  - files_external: 1.20.0
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0
```

### Nextcloud Logs

{"reqId":"sHvqW0zQf78D3kcTN5sr","level":2,"time":"2023-12-19T10:13:54+00:00","remoteAddr":"127.0.0.1","user":"--","app":"no app in context","method":"GET","url":"/","message":"Host localhost was not connected to because it violates local access rules","userAgent":"curl/8.5.0","version":"","data":[]}
{"reqId":"sHvqW0zQf78D3kcTN5sr","level":2,"time":"2023-12-19T10:13:54+00:00","remoteAddr":"127.0.0.1","user":"--","app":"no app in context","method":"GET","url":"/","message":"Host localhost was not connected to because it violates local access rules","userAgent":"curl/8.5.0","version":"","data":[]}
{"reqId":"9zRC13B42evZTXK41JUG","level":2,"time":"2023-12-19T10:14:54+00:00","remoteAddr":"127.0.0.1","user":"--","app":"no app in context","method":"GET","url":"/","message":"Host localhost was not connected to because it violates local access rules","userAgent":"curl/8.5.0","version":"","data":[]}
{"reqId":"9zRC13B42evZTXK41JUG","level":2,"time":"2023-12-19T10:14:54+00:00","remoteAddr":"127.0.0.1","user":"--","app":"no app in context","method":"GET","url":"/","message":"Host localhost was not connected to because it violates local access rules","userAgent":"curl/8.5.0","version":"","data":[]}
{"reqId":"u9CTKkiuM2NYBo24ogQg","level":3,"time":"2023-12-19T10:15:00+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Exception thrown: Exception","userAgent":"--","version":"","exception":{"Exception":"Exception","Message":"Not installed","Code":0,"Trace":[{"file":"/app/www/public/lib/base.php","line":709,"function":"checkInstalled","class":"OC","type":"::"},{"file":"/app/www/public/lib/base.php","line":1200,"function":"init","class":"OC","type":"::"},{"file":"/app/www/public/cron.php","line":43,"args":["/app/www/public/lib/base.php"],"function":"require_once"}],"File":"/app/www/public/lib/base.php","Line":283,"CustomMessage":"Exception thrown: Exception"}}
{"reqId":"haF0DWacxeITXKvcTUe9","level":2,"time":"2023-12-19T10:15:54+00:00","remoteAddr":"127.0.0.1","user":"--","app":"no app in context","method":"GET","url":"/","message":"Host localhost was not connected to because it violates local access rules","userAgent":"curl/8.5.0","version":"","data":[]}
{"reqId":"haF0DWacxeITXKvcTUe9","level":2,"time":"2023-12-19T10:15:54+00:00","remoteAddr":"127.0.0.1","user":"--","app":"no app in context","method":"GET","url":"/","message":"Host localhost was not connected to because it violates local access rules","userAgent":"curl/8.5.0","version":"","data":[]}
{"reqId":"vTXol6hyRDECdib0ORoE","level":2,"time":"2023-12-19T10:16:54+00:00","remoteAddr":"127.0.0.1","user":"--","app":"no app in context","method":"GET","url":"/","message":"Host localhost was not connected to because it violates local access rules","userAgent":"curl/8.5.0","version":"28.0.0.11","data":[]}
{"reqId":"vTXol6hyRDECdib0ORoE","level":2,"time":"2023-12-19T10:16:54+00:00","remoteAddr":"127.0.0.1","user":"--","app":"no app in context","method":"GET","url":"/","message":"Host localhost was not connected to because it violates local access rules","userAgent":"curl/8.5.0","version":"28.0.0.11","data":[]}
{"reqId":"34FKNUUAoX1TCOfo7Pdl","level":3,"time":"2023-12-19T10:17:31+00:00","remoteAddr":"192.168.10.1","user":"User","app":"no app in context","method":"GET","url":"/settings/apps/list","message":"$absolutePath must be relative to \"files\", value is \"/files_external\"","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"28.0.0.11","data":[]}
{"reqId":"34FKNUUAoX1TCOfo7Pdl","level":3,"time":"2023-12-19T10:17:31+00:00","remoteAddr":"192.168.10.1","user":"User","app":"no app in context","method":"GET","url":"/settings/apps/list","message":"Failed to get absolute bundle path. Fallback to default ca-bundle.crt","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"28.0.0.11","exception":{"Exception":"InvalidArgumentException","Message":"$absolutePath must be relative to \"files\"","Code":0,"Trace":[{"file":"/app/www/public/lib/private/Files/View.php","line":1944,"function":"getPathRelativeToFiles","class":"OC\\Files\\View","type":"->"},{"file":"/app/www/public/lib/private/Files/View.php","line":2048,"function":"lockPath","class":"OC\\Files\\View","type":"->"},{"file":"/app/www/public/lib/private/Files/View.php","line":1141,"function":"lockFile","class":"OC\\Files\\View","type":"->"},{"file":"/app/www/public/lib/private/Files/View.php","line":244,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/app/www/public/lib/private/Security/CertificateManager.php","line":125,"function":"mkdir","class":"OC\\Files\\View","type":"->"},{"file":"/app/www/public/lib/private/Security/CertificateManager.php","line":234,"function":"createCertificateBundle","class":"OC\\Security\\CertificateManager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/app/www/public/lib/private/Http/Client/Client.php","line":133,"function":"getAbsoluteBundlePath","class":"OC\\Security\\CertificateManager","type":"->"},{"file":"/app/www/public/lib/private/Http/Client/Client.php","line":80,"function":"getCertBundle","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/app/www/public/lib/private/Http/Client/Client.php","line":230,"function":"buildRequestOptions","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/app/www/public/lib/private/App/AppStore/Fetcher/Fetcher.php","line":120,"function":"get","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/app/www/public/lib/private/App/AppStore/Fetcher/AppFetcher.php","line":86,"function":"fetch","class":"OC\\App\\AppStore\\Fetcher\\Fetcher","type":"->"},{"file":"/app/www/public/lib/private/App/AppStore/Fetcher/Fetcher.php","line":190,"function":"fetch","class":"OC\\App\\AppStore\\Fetcher\\AppFetcher","type":"->"},{"file":"/app/www/public/lib/private/App/AppStore/Fetcher/AppFetcher.php","line":187,"function":"get","class":"OC\\App\\AppStore\\Fetcher\\Fetcher","type":"->"},{"file":"/config/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php","line":314,"function":"get","class":"OC\\App\\AppStore\\Fetcher\\AppFetcher","type":"->"},{"file":"/config/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php","line":208,"function":"getAppsForCategory","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"/config/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php","line":247,"function":"fetchApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"listApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/app/www/public/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/app/www/public/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/app/www/public/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/app/www/public/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/app/www/public/lib/private/Files/View.php","Line":2126,"message":"Failed to get absolute bundle path. Fallback to default ca-bundle.crt","exception":{},"CustomMessage":"Failed to get absolute bundle path. Fallback to default ca-bundle.crt"}}
{"reqId":"VGxYa7Go7TE9PI32Rawa","level":3,"time":"2023-12-19T10:35:01+00:00","remoteAddr":"","user":"--","app":"dav","method":"","url":"--","message":"Exception thrown: Sabre\\VObject\\InvalidDataException","userAgent":"--","version":"28.0.0.11","exception":{"Exception":"Sabre\\VObject\\InvalidDataException","Message":"The supplied iCalendar duration value is incorrect: ","Code":0,"Trace":[{"file":"/config/www/nextcloud/apps/dav/lib/BackgroundJob/RefreshWebcalJob.php","line":96,"function":"parseDuration","class":"Sabre\\VObject\\DateTimeParser","type":"::"},{"file":"/app/www/public/cron.php","line":152,"function":"execute","class":"OCA\\DAV\\BackgroundJob\\RefreshWebcalJob","type":"->"}],"File":"/app/www/public/3rdparty/sabre/vobject/lib/DateTimeParser.php","Line":101,"CustomMessage":"Exception thrown: Sabre\\VObject\\InvalidDataException"}}
{"reqId":"VGxYa7Go7TE9PI32Rawa","level":2,"time":"2023-12-19T10:35:01+00:00","remoteAddr":"","user":"--","app":"dav","method":"","url":"--","message":"Subscription 1 could not be refreshed, refreshrate in database is invalid","userAgent":"--","version":"28.0.0.11","data":{"app":"dav"}}
{"reqId":"NqNURyIMSaSv0jdb559m","level":3,"time":"2023-12-19T10:40:01+00:00","remoteAddr":"","user":"--","app":"dav","method":"","url":"--","message":"Exception thrown: Sabre\\VObject\\InvalidDataException","userAgent":"--","version":"28.0.0.11","exception":{"Exception":"Sabre\\VObject\\InvalidDataException","Message":"The supplied iCalendar duration value is incorrect: ","Code":0,"Trace":[{"file":"/config/www/nextcloud/apps/dav/lib/BackgroundJob/RefreshWebcalJob.php","line":96,"function":"parseDuration","class":"Sabre\\VObject\\DateTimeParser","type":"::"},{"file":"/app/www/public/cron.php","line":152,"function":"execute","class":"OCA\\DAV\\BackgroundJob\\RefreshWebcalJob","type":"->"}],"File":"/app/www/public/3rdparty/sabre/vobject/lib/DateTimeParser.php","Line":101,"CustomMessage":"Exception thrown: Sabre\\VObject\\InvalidDataException"}}
{"reqId":"NqNURyIMSaSv0jdb559m","level":2,"time":"2023-12-19T10:40:01+00:00","remoteAddr":"","user":"--","app":"dav","method":"","url":"--","message":"Subscription 1 could not be refreshed, refreshrate in database is invalid","userAgent":"--","version":"28.0.0.11","data":{"app":"dav"}}
{"reqId":"A6lKROr1lG0RcwTuDpyp","level":3,"time":"2023-12-19T10:45:01+00:00","remoteAddr":"","user":"--","app":"dav","method":"","url":"--","message":"Exception thrown: Sabre\\VObject\\InvalidDataException","userAgent":"--","version":"28.0.0.11","exception":{"Exception":"Sabre\\VObject\\InvalidDataException","Message":"The supplied iCalendar duration value is incorrect: ","Code":0,"Trace":[{"file":"/config/www/nextcloud/apps/dav/lib/BackgroundJob/RefreshWebcalJob.php","line":96,"function":"parseDuration","class":"Sabre\\VObject\\DateTimeParser","type":"::"},{"file":"/app/www/public/cron.php","line":152,"function":"execute","class":"OCA\\DAV\\BackgroundJob\\RefreshWebcalJob","type":"->"}],"File":"/app/www/public/3rdparty/sabre/vobject/lib/DateTimeParser.php","Line":101,"CustomMessage":"Exception thrown: Sabre\\VObject\\InvalidDataException"}}
{"reqId":"A6lKROr1lG0RcwTuDpyp","level":2,"time":"2023-12-19T10:45:01+00:00","remoteAddr":"","user":"--","app":"dav","method":"","url":"--","message":"Subscription 1 could not be refreshed, refreshrate in database is invalid","userAgent":"--","version":"28.0.0.11","data":{"app":"dav"}}
{"reqId":"pUMITuTvrcsIVahQxNu5","level":3,"time":"2023-12-19T10:45:35+00:00","remoteAddr":"192.168.10.1","user":"User","app":"webdav","method":"PROPFIND","url":"/remote.php/dav/calendars/User/","message":"syntax error, unexpected token \"return\"","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"28.0.0.11","exception":{"Exception":"ParseError","Message":"syntax error, unexpected token \"return\"","Code":0,"Trace":[{"file":"/app/www/public/lib/composer/composer/ClassLoader.php","line":427,"function":"Composer\\Autoload\\{closure}","args":["*** sensitive parameters replaced ***"]},{"file":"/config/www/nextcloud/apps/dav/lib/CalDAV/CalendarRoot.php","line":46,"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->"},{"file":"/app/www/public/3rdparty/sabre/dav/lib/DAVACL/AbstractPrincipalCollection.php","line":119,"function":"getChildForPrincipal","class":"OCA\\DAV\\CalDAV\\CalendarRoot","type":"->"},{"file":"/app/www/public/3rdparty/sabre/dav/lib/DAV/Collection.php","line":57,"function":"getChild","class":"Sabre\\DAVACL\\AbstractPrincipalCollection","type":"->"},{"file":"/app/www/public/3rdparty/sabre/dav/lib/DAV/Tree.php","line":117,"function":"childExists","class":"Sabre\\DAV\\Collection","type":"->"},{"file":"/app/www/public/3rdparty/sabre/dav/lib/DAVACL/Plugin.php","line":834,"function":"nodeExists","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/config/www/nextcloud/apps/dav/lib/Connector/Sabre/DavAclPlugin.php","line":106,"function":"beforeMethod","class":"Sabre\\DAVACL\\Plugin","type":"->"},{"file":"/app/www/public/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"beforeMethod","class":"OCA\\DAV\\Connector\\Sabre\\DavAclPlugin","type":"->"},{"file":"/app/www/public/3rdparty/sabre/dav/lib/DAV/Server.php","line":456,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/app/www/public/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/app/www/public/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/apps/dav/lib/Server.php","line":370,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/app/www/public/remote.php","line":172,"args":["/config/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/config/www/nextcloud/apps/dav/lib/CalDAV/CalendarHome.php","Line":187,"message":"syntax error, unexpected token \"return\"","exception":{},"CustomMessage":"syntax error, unexpected token \"return\""}}
{"reqId":"7WabqCe1JsDne9kMQs4h","level":3,"time":"2023-12-19T10:46:25+00:00","remoteAddr":"192.168.10.1","user":"User","app":"webdav","method":"PROPFIND","url":"/remote.php/dav/calendars/User/","message":"syntax error, unexpected token \"return\"","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"28.0.0.11","exception":{"Exception":"ParseError","Message":"syntax error, unexpected token \"return\"","Code":0,"Trace":[{"file":"/app/www/public/lib/composer/composer/ClassLoader.php","line":427,"function":"Composer\\Autoload\\{closure}","args":["*** sensitive parameters replaced ***"]},{"file":"/config/www/nextcloud/apps/dav/lib/CalDAV/CalendarRoot.php","line":46,"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->"},{"file":"/app/www/public/3rdparty/sabre/dav/lib/DAVACL/AbstractPrincipalCollection.php","line":119,"function":"getChildForPrincipal","class":"OCA\\DAV\\CalDAV\\CalendarRoot","type":"->"},{"file":"/app/www/public/3rdparty/sabre/dav/lib/DAV/Collection.php","line":57,"function":"getChild","class":"Sabre\\DAVACL\\AbstractPrincipalCollection","type":"->"},{"file":"/app/www/public/3rdparty/sabre/dav/lib/DAV/Tree.php","line":117,"function":"childExists","class":"Sabre\\DAV\\Collection","type":"->"},{"file":"/app/www/public/3rdparty/sabre/dav/lib/DAVACL/Plugin.php","line":834,"function":"nodeExists","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/config/www/nextcloud/apps/dav/lib/Connector/Sabre/DavAclPlugin.php","line":106,"function":"beforeMethod","class":"Sabre\\DAVACL\\Plugin","type":"->"},{"file":"/app/www/public/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"beforeMethod","class":"OCA\\DAV\\Connector\\Sabre\\DavAclPlugin","type":"->"},{"file":"/app/www/public/3rdparty/sabre/dav/lib/DAV/Server.php","line":456,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/app/www/public/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/app/www/public/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/apps/dav/lib/Server.php","line":370,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/app/www/public/remote.php","line":172,"args":["/config/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/config/www/nextcloud/apps/dav/lib/CalDAV/CalendarHome.php","Line":187,"message":"syntax error, unexpected token \"return\"","exception":{},"CustomMessage":"syntax error, unexpected token \"return\""}}
{"reqId":"fOeQxO16XE6AkgD5dtHD","level":3,"time":"2023-12-19T10:47:22+00:00","remoteAddr":"192.168.10.1","user":"User","app":"webdav","method":"PROPFIND","url":"/remote.php/dav/calendars/User/","message":"syntax error, unexpected token \"return\"","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"28.0.0.11","exception":{"Exception":"ParseError","Message":"syntax error, unexpected token \"return\"","Code":0,"Trace":[{"file":"/app/www/public/lib/composer/composer/ClassLoader.php","line":427,"function":"Composer\\Autoload\\{closure}","args":["*** sensitive parameters replaced ***"]},{"file":"/config/www/nextcloud/apps/dav/lib/CalDAV/CalendarRoot.php","line":46,"function":"loadClass","class":"Composer\\Autoload\\ClassLoader","type":"->"},{"file":"/app/www/public/3rdparty/sabre/dav/lib/DAVACL/AbstractPrincipalCollection.php","line":119,"function":"getChildForPrincipal","class":"OCA\\DAV\\CalDAV\\CalendarRoot","type":"->"},{"file":"/app/www/public/3rdparty/sabre/dav/lib/DAV/Collection.php","line":57,"function":"getChild","class":"Sabre\\DAVACL\\AbstractPrincipalCollection","type":"->"},{"file":"/app/www/public/3rdparty/sabre/dav/lib/DAV/Tree.php","line":117,"function":"childExists","class":"Sabre\\DAV\\Collection","type":"->"},{"file":"/app/www/public/3rdparty/sabre/dav/lib/DAVACL/Plugin.php","line":834,"function":"nodeExists","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/config/www/nextcloud/apps/dav/lib/Connector/Sabre/DavAclPlugin.php","line":106,"function":"beforeMethod","class":"Sabre\\DAVACL\\Plugin","type":"->"},{"file":"/app/www/public/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"beforeMethod","class":"OCA\\DAV\\Connector\\Sabre\\DavAclPlugin","type":"->"},{"file":"/app/www/public/3rdparty/sabre/dav/lib/DAV/Server.php","line":456,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/app/www/public/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/app/www/public/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/apps/dav/lib/Server.php","line":370,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/app/www/public/remote.php","line":172,"args":["/config/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/config/www/nextcloud/apps/dav/lib/CalDAV/CalendarHome.php","Line":187,"message":"syntax error, unexpected token \"return\"","exception":{},"CustomMessage":"syntax error, unexpected token \"return\""}}
{"reqId":"3W6l4wJli9UG9mNgvAl1","level":3,"time":"2023-12-19T10:50:03+00:00","remoteAddr":"","user":"--","app":"dav","method":"","url":"--","message":"Exception thrown: Sabre\\VObject\\InvalidDataException","userAgent":"--","version":"28.0.0.11","exception":{"Exception":"Sabre\\VObject\\InvalidDataException","Message":"The supplied iCalendar duration value is incorrect: ","Code":0,"Trace":[{"file":"/config/www/nextcloud/apps/dav/lib/BackgroundJob/RefreshWebcalJob.php","line":96,"function":"parseDuration","class":"Sabre\\VObject\\DateTimeParser","type":"::"},{"file":"/app/www/public/cron.php","line":152,"function":"execute","class":"OCA\\DAV\\BackgroundJob\\RefreshWebcalJob","type":"->"}],"File":"/app/www/public/3rdparty/sabre/vobject/lib/DateTimeParser.php","Line":101,"CustomMessage":"Exception thrown: Sabre\\VObject\\InvalidDataException"}}
{"reqId":"3W6l4wJli9UG9mNgvAl1","level":2,"time":"2023-12-19T10:50:03+00:00","remoteAddr":"","user":"--","app":"dav","method":"","url":"--","message":"Subscription 1 could not be refreshed, refreshrate in database is invalid","userAgent":"--","version":"28.0.0.11","data":{"app":"dav"}}
{"reqId":"zJD9NVcgwrKzmPgO51NG","level":3,"time":"2023-12-19T10:55:01+00:00","remoteAddr":"","user":"--","app":"dav","method":"","url":"--","message":"Exception thrown: Sabre\\VObject\\InvalidDataException","userAgent":"--","version":"28.0.0.11","exception":{"Exception":"Sabre\\VObject\\InvalidDataException","Message":"The supplied iCalendar duration value is incorrect: ","Code":0,"Trace":[{"file":"/config/www/nextcloud/apps/dav/lib/BackgroundJob/RefreshWebcalJob.php","line":96,"function":"parseDuration","class":"Sabre\\VObject\\DateTimeParser","type":"::"},{"file":"/app/www/public/cron.php","line":152,"function":"execute","class":"OCA\\DAV\\BackgroundJob\\RefreshWebcalJob","type":"->"}],"File":"/app/www/public/3rdparty/sabre/vobject/lib/DateTimeParser.php","Line":101,"CustomMessage":"Exception thrown: Sabre\\VObject\\InvalidDataException"}}
{"reqId":"zJD9NVcgwrKzmPgO51NG","level":2,"time":"2023-12-19T10:55:01+00:00","remoteAddr":"","user":"--","app":"dav","method":"","url":"--","message":"Subscription 1 could not be refreshed, refreshrate in database is invalid","userAgent":"--","version":"28.0.0.11","data":{"app":"dav"}}

**Comment by joshtrichards** [comment]
Hi @Just4Link - These seem to be two distinct matters. Can you please re-submit the calendar related matter as a separate issue? If you want your issues to be looked at, each needs to be focused on one matter at a time. :)

Let's keep this one focused on the "protocol page" matter.

Can you clarify what you mean by "protocol page"? 

Lastly:

> `        "memcache.locking": "\\OC\\Memcache\\APCu",`

I would not use APCu for locking. I'd either comment this line out or use Redis. For further questions on this, refer to the documentation and/or the Nextcloud Help Forum - https://help.nextcloud.com

> Community Docker image

Your configuration suggests this is *not* the community Docker image. If I was to guess, you're using the LinuxServer.io image.

**Comment by jakobroehrl** [comment]
> Can you clarify what you mean by "protocol page"?

 
I think this:
https://github.com/nextcloud/server/issues/42387

**Comment by jakobroehrl** [comment]
You can fix the protocol page with this: https://github.com/nextcloud/forms/issues/1838#issuecomment-1860497200

**Comment by Just4Link** [comment]
To the memcache: this instance is a fresh setup and redis was not integrated to that point. I set this instance up as a fresh installation because on my productive instance i have the same problems.

Protocol: i mean the logging page in the administration settings.

Calendar: this error is spamming the log since the instance is runnung with my holiday calendar subscription as described above:

{"reqId":"Komhxqh2MMepQrsjlcyF","level":3,"time":"2023-12-20T13:40:03+00:00","remoteAddr":"","user":"--","app":"dav","method":"","url":"--","message":"Exception thrown: Sabre\\VObject\\InvalidDataException","userAgent":"--","version":"28.0.0.11","exception":{"Exception":"Sabre\\VObject\\InvalidDataException","Message":"The supplied iCalendar duration value is incorrect: ","Code":0,"Trace":[{"file":"/config/www/nextcloud/apps/dav/lib/BackgroundJob/RefreshWebcalJob.php","line":96,"function":"parseDuration","class":"Sabre\\VObject\\DateTimeParser","type":"::"},{"file":"/app/www/public/cron.php","line":152,"function":"execute","class":"OCA\\DAV\\BackgroundJob\\RefreshWebcalJob","type":"->"}],"File":"/app/www/public/3rdparty/sabre/vobject/lib/DateTimeParser.php","Line":101,"CustomMessage":"Exception thrown: Sabre\\VObject\\InvalidDataException"}}
{"reqId":"Komhxqh2MMepQrsjlcyF","level":2,"time":"2023-12-20T13:40:03+00:00","remoteAddr":"","user":"--","app":"dav","method":"","url":"--","message":"Subscription 1 could not be refreshed, refreshrate in database is invalid","userAgent":"--","version":"28.0.0.11","data":{"app":"dav"}}

**Comment by Just4Link** [comment]
just a quick info ....
i set up a new instance with the original docker container instead from linuxserver.io.
The logging page seems to work fine there.

The only problem left is the issue with the subscribed calendars where no events shown up.

**Comment by nursoda** [comment]
Please create a separate issue for the calendar issue. Let's focus on the log issue here.

I also experience the "empty log page" along with a notification "Could not load log entries" on NC 28.0.1. Log entries do appear after 10 seconds as described above.

I'm not using an image, or LinuxServer.io: I'm on a long standing custom setup on a local machine, installed myself from scratch on Arch, using PHP-FPM, NGINX, Mariadb, Redis and the NC web installer, updating via zip extraction and `occ update`.

I'm using Redis for locking, so, while it might be a good idea not to use APCu for locking, the suggestion in the first answer seems unrelated to this issue:

```
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '/run/redis.sock',
    'port' => 0,
    'dbindex' => 1,
    'timeout' => 1.5,
  ),
```

The issue started with NC28, never happened with NC <28. It happens on my bare minimal test instance (without forms), on my test-all-apps instance as well as on production instances.

@devs What tests/logs/configs do you need to help fix it?

**Comment by joshtrichards** [comment]
Logging is already addressed here: https://github.com/nextcloud/logreader/issues/1073#issuecomment-1866957195

Closing. Feel free to open a dedicated issue for the Calendar matter, @Just4Link
