### ISSUE TITLE
[CSS]: "New" button in Files app is too little when translated in french

### ISSUE THREAD

**Issue by Mer0me** [nextcloud/server#42372]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Description with 2 screenshots : 

Nextcloud 27.1.3 :
![image](https://github.com/nextcloud/server/assets/6248852/c58257c8-9c17-47e2-8ec6-015dc4b6912e)

Nextcloud 28.0.0 :
![image](https://github.com/nextcloud/server/assets/6248852/0882fa53-23b5-42b2-8bfd-13066a4162b9)

### Steps to reproduce

1. Open File App in french and see the size of the button

### Expected behavior

Button should have the size of the content.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
not relevant
```

### List of activated Apps

```shell
not relevant
```

### Nextcloud Signing status

```shell
not relevant
```

### Nextcloud Logs

```shell
not relevant
```

**Comment by skjnldsv** [comment]
Yeah, something was odd, but we fixed it for upcoming 28.0.1 :)

**Comment by skjnldsv** [comment]
![image](https://github.com/nextcloud/server/assets/14975046/dea011ad-a901-4f57-a38d-87db1eb773fc)
