### ISSUE TITLE
Move all features within the contacts menu button on the header to unified search

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/server#42386]
This feature has been duplicated since the global search has been there. Now that the global search is even better, we should remove it.

![Screenshot from 2023-12-20 09-24-44](https://github.com/nextcloud/server/assets/26852655/237685f6-7cb2-4b20-9ab0-60e739211392)

**Comment by marcoambrosini** [comment]
ping @nextcloud/designers

**Comment by nimishavijay** [comment]
It was recently reworked to include more useful information, but I agree that we should check if this is needed, especially because there are already 4 other icons in the right side of the top bar, cc @jancborchardt

**Comment by emoral435** [comment]
If it looks like it can be removed, I can start to work on removing it with nextcloud/designers approval (don't want to ping again ;) ) with the requirements that you guys would propose!

**Comment by marcoambrosini** [comment]
> It was recently reworked to include more useful information

We can move this to the search results in the unified search.

**Comment by emoral435** [comment]
We should then rename the issue, something like eg: "move all features of the contacts menu to unified search" or something along those lines. 

It seemingly just needs to have these additions added:

![image](https://github.com/nextcloud/server/assets/110193237/8997af62-6cda-4c8a-b660-7b970fee57b5)
more information | relative local time

**Comment by joshtrichards** [comment]
Does #22329 still apply? If so, it may be a factor.

**Comment by emoral435** [comment]
That is true. As that issue has not had much traffic for the last three years, I assume its priority is not that high up. However, if its a small change, it can be added within the implementation that I am drafting up!

**Comment by emoral435** [comment]
I'll unassign myself on this issue from now, as I have to work on accessibility issues, but after chatting with Marco, I misunderstood what was needed to be done, we should move the results of the search to be on the main search functionality! Not the filters, whoops!

Around here:
![image](https://github.com/nextcloud/server/assets/110193237/b160041b-2ffe-4ddf-8d02-19753a6c9264)

**Comment by jancborchardt** [comment]
Just FYI @marcoambrosini @emoral435 issue https://github.com/nextcloud/server/issues/22329 was fixed in 28 via https://github.com/nextcloud/server/issues/40559

Moving this to the search does not work, as people should have this info at a glance and not need to search first. So the contacts menu is something we want to improve rather than remove.

Opened a new design spec about this at https://github.com/nextcloud/server/issues/43763
