### ISSUE TITLE
[Bug]:  NextCloud 28 seems to be handling the Oauth authentication wrongly. 

### ISSUE THREAD

**Issue by colonelm** [nextcloud/server#42394]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The token renewal is working properly with NextCloud version 27 and OpenProject (multiple versions including 13.0,13.1) etc.  With NC 28, the OAuth token refresh is not working properly. Even when the token is expired the server return http response code 200 rather than 401. Behavior was proper with NC 27. 

### Steps to reproduce

NC 28 (when logged into OpenProject 13.1 for which session was expired) (NC OP Integration app version - 2.5.1)

1xx.5x.2xx.1xx - - [20/Dec/2023:08:10:56 +0530] "POST /ocs/v1.php/apps/integration_openproject/filesinfo HTTP/1.1" 200 174 "-" "Ruby"

NC 27 (when logged into OpenProject 13.1 for which session was expired) (NC OP Integration app version - 2.4.6/2.5.1)

1xx.5x.2xx.1xx - - [20/Dec/2023:09:28:57 +0530] "POST /ocs/v1.php/apps/integration_openproject/filesinfo HTTP/1.1" 401 140 "-" "Ruby"
1xx.5x.2xx.1xx - - [20/Dec/2023:09:28:57 +0530] "POST /index.php/apps/oauth2/api/v1/token HTTP/1.1" 200 269 "-" "Rack::OAuth2 (2.2.0)"
1xx.5x.2xx.1xx - - [20/Dec/2023:09:28:58 +0530] "POST /ocs/v1.php/apps/integration_openproject/filesinfo HTTP/1.1" 200 251 "-" "Ruby"
1xx.5x.2xx.1xx - - [20/Dec/2023:09:29:01 +0530] "GET /ocs/v1.php/cloud/user HTTP/1.1" 200 519 "-" "Ruby"

### Expected behavior

When the Oauth Token is expired the API response should give 401 error code. 

### Installation method

Other Community project

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by colonelm** [comment]
Bug seems to have have come from the updation of  ExpiredTokenException of OC package - https://github.com/nextcloud/server/blame/e15fcecaf0d382cebff924ec2b1f5319e130c0e8/lib/private/Authentication/Exceptions/ExpiredTokenException.php#L33 seems to have removed the inheritance model assumed between ExpiredTokenException and InvalidTokenException on this code here - https://github.com/nextcloud/server/blob/e15fcecaf0d382cebff924ec2b1f5319e130c0e8/lib/private/User/Session.php#L636 hence the ExpiredTokenExpection is not being caught. The change may have impact on other areas.

**Comment by come-nc** [comment]
Before:

```mermaid
graph BT;
     \OC\ExpiredTokenException --> \OC\InvalidTokenException
     \OC\WipeTokenException --> \OC\InvalidTokenException
     \OC\InvalidTokenException --> \Exception
```

After:

```mermaid
graph BT;
     \OC\ExpiredTokenException --> \OCP\ExpiredTokenException
     \OC\WipeTokenException --> \OCP\WipeTokenException
     \OC\InvalidTokenException --> \OCP\InvalidTokenException
     \OCP\ExpiredTokenException --> \OCP\InvalidTokenException
     \OCP\WipeTokenException --> \OCP\InvalidTokenException
     \OCP\InvalidTokenException --> \Exception
```

So indeed the relation between `\OC\ExpiredTokenException` and `\OC\InvalidTokenException` was broken.
Not sure how to fix that while still having a clear path forward.

**Comment by colonelm** [comment]
what abt updating code to use \OCP\InvalidTokenException where ever \OC\InvalidTokenException was being used; The exception may not be used much outside the core.

**Comment by nickvergessen** [comment]
My suggestion with the least impact would be:
```mermaid
graph BT;
     \OC\ExpiredTokenException --> \OC\InvalidTokenException
     \OC\ExpiredTokenException --> \OCP\ExpiredTokenException
     \OC\WipeTokenException --> \OCP\WipeTokenException
     \OC\InvalidTokenException --> \OCP\InvalidTokenException
     \OCP\ExpiredTokenException --> \OCP\InvalidTokenException
     \OCP\WipeTokenException --> \OCP\InvalidTokenException
     \OCP\InvalidTokenException --> \Exception
```

But PHP does not allow extending 2 classes :(

So I would say we simply add a check for `\OC\ExpiredTokenException` everywhere we check for `\OC\InvalidTokenException` already, because that is not breaking OCP.

**Comment by come-nc** [comment]
> So I would say we simply add a check for `\OC\ExpiredTokenException` everywhere we check for `\OC\InvalidTokenException` already, because that is not breaking OCP.

In this case we can simply change our uses of `\OC\InvalidTokenException` to use `\OCP\InvalidTokenException` and it will work fine.
But I was afraid applications may be using this as well, but since it’s in OC maybe it’s as easy as that, I’ll draft a third PR with that.

**Comment by heisian** [comment]
I am running NextCloud 28.0.1 and OpenProject 13.3.1 and believe I am still running into this issue..

From OpenProject, when opening a work package:
> An internal error has occurred. unexpected token at '<?xml version="1.0"?> <ocs> <meta> <status>failure</status> <statuscode>996</statuscode> <message>Internal Server Error </message> </meta> <data/> </ocs> ' 

From NextCloud using unified search produces no results from OpenProject.

Deleting the OAuth token/connection and re-establishing the connection on each side resolves each issue, respectively.

**Comment by nickvergessen** [comment]
> I am running NextCloud 28.0.1

Please don't.
Update to the latest version 28.0.3 and try again

**Comment by heisian** [comment]
Ok thanks, I was hesitant to do a minor upgrade unless really necessary, but I've gone ahead and done it.

**Comment by nickvergessen** [comment]
Minors are E.g. 28.1.x

28.0.x is a Patch level release and should basically be considered non-optional. They come with important bug and security fixes
