### ISSUE TITLE
User import/export migration ability

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#424]
On large instances it is wise to use federation for the best scalability. At that point, it makes sense to move very active users to a more powerful instance or spit a overloaded instance in two. This requires the ability to export user data from one and import them in another instance; or a direct migration path.

**Comment by MorrisJobke** [comment]
migration

**Comment by MorrisJobke** [comment]
Duplicate of https://github.com/icewind1991/migration/issues/1
