### ISSUE TITLE
[Bug] Cannot create a new user, passwords doesn't match 

### ISSUE THREAD

**Issue by AchMol** [nextcloud/server#42420]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I try to add a new user there is an error that th two passwords doen't match. No additional users can created.

### Steps to reproduce

1. User
2. Add new User
3. Confirm

### Expected behavior

New user account should be created

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Freshly updated from 26.1 to 27 to 28.0

**Comment by joshtrichards** [comment]
> When I try to add a new user there is an error that th two passwords doen't match. No additional users can created.

Hi @AchMol - Can you provide a screenshot? We don't ask for the password twice when creating a new user and I can't reproduce this. I can create new users just fine.

**Comment by AchMol** [comment]
Hi everybody,
I started the docker container today to do the screenshot but now it works as expected. I'm a bit confused, there was definitly a second confirmation password mask yesterday after the first one and the user  weren't created.

But now everything works fine so definitly no bug. Sorry for the question, I'm not sure what happend...

**Comment by joshtrichards** [comment]
It's possible you were prompted for the admin password. Many sensitive activities do require re-auth from time to time.

**Comment by AchMol** [comment]
That may be the solution... Thank you!
