### ISSUE TITLE
cannot delete files in upload-only folder

### ISSUE THREAD

**Issue by individual-it** [nextcloud/server#4243]
### Steps to reproduce
1. create an upload-only folder
2. upload files to that folder via share-link from an other browser session 
3. try to delete/rename/move the uploaded files as the user who owns the folder 

### Expected behaviour
files action dropdown shows buttons to delete/rename/move the uploaded files

### Actual behaviour
only "details&download" buttons are shown
The whole folder can be deleted
When changing the folder share to be a public upload folder with the listing enabled again and uploading more files, the new files can be deleted 

### Server configuration

**Operating system**:
Debian 4.8.15-2~bpo8+2
**Web server:**
Apache 2.0
**Database:**
sqlite
**PHP version:**
7.0.7-5
**Nextcloud version:** (see Nextcloud admin page)
12.0 alpha (git master)
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
git

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - comments: 1.2.0
  - dav: 1.2.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_sharing: 1.2.0
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - lookup_server_connector: 1.0.0
  - provisioning_api: 1.2.0
  - sharebymail: 1.1.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.0
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - contacts
  - encryption
  - files_external
  - testing
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocigom9x0hj5",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/home\/artur\/www\/nextcloud-server\/data",
        "overwrite.cli.url": "http:\/\/localhost\/nextcloud-server",
        "dbtype": "sqlite3",
        "version": "12.0.0.13",
        "installed": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
FF
**Operating system:**
Debian Linux
#### Web server error log
<details>
<summary>Web server error log</summary>

```
::1 - v3g2KXgj6kOcWNT [06/Apr/2017:17:41:28 +0545] "PUT /nextcloud-server/public.php/webdav/file1.txt HTTP/1.1" 201 987 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
::1 - - [06/Apr/2017:17:41:29 +0545] "GET /nextcloud-server/index.php/apps/theming/img/core/filetypes/text.svg?v=0 HTTP/1.1" 304 285 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0"
```
</details>

**Comment by schiessle** [comment]
Hm, seems like the file gets the permission 17 (share and read). Don't know why, I would expect that the permissions gets inherit from the parent folder which has permission 31.

Seems like some file cache magic, @icewind1991 can you have a look? Thanks!

**Comment by rullzer** [comment]
It kicks in because files drop shares have a mask that only allows uploads

**Comment by rullzer** [comment]
The thing is that that is exactly what the wrapper should do. Because we don't want users to be able to delete/read etc with that token.

Basically we should set the permissions to sane ones once they are written in this case...

@icewind1991 any idea where?

**Comment by schiessle** [comment]
> It kicks in because files drop shares have a mask that only allows uploads

But why is it then 17 (only share and read) while the share has create permissions as well. If we would take the permissions from the share it should be at least 21.

**Comment by rullzer** [comment]
Because a file can't have create permissions

**Comment by rullzer** [comment]
@icewind1991 I narrowed it down a bit more. It is because the scanner from `OCA\Files_Sharing` is not used.

**Comment by rullzer** [comment]
@schiessle it is kind of weird it gets share permission tough...

**Comment by rullzer** [comment]
Ah no that is not. We add share permissions for public links by default because they can be mounted etc.

**Comment by rullzer** [comment]
Aaaah the SharedScanner of course does not kick in because it is not seen as shared storage....

**Comment by icewind1991** [comment]
Fixes is here: https://github.com/nextcloud/server/pull/4277
