### ISSUE TITLE
👥 Teams

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#42433]
## Issues in scope
- [x] https://github.com/nextcloud/circles/issues/1505
- [x] https://github.com/nextcloud/circles/issues/1506
  - [x] https://github.com/nextcloud/circles/pull/1510
  - [x] https://github.com/nextcloud/circles/pull/1519
  - [x] https://github.com/nextcloud/circles/pull/1520
- [x] https://github.com/nextcloud/contacts/issues/3816
- [x] https://github.com/nextcloud/contacts/issues/3817
- [x] https://github.com/nextcloud/server/issues/43683
  - [x] https://github.com/nextcloud/server/pull/43855
- [x] https://github.com/nextcloud/related_resources/issues/360
  - [x] https://github.com/nextcloud-libraries/nextcloud-vue/pull/5316
  - [ ] Release library
  - [ ] Bump in apps
- [ ] https://github.com/nextcloud/collectives/issues/1121
- [ ] Team resource providers for apps that share with circles or own resources by a circle
  - [x] https://github.com/nextcloud/deck/pull/5625
  - [x] https://github.com/nextcloud/collectives/pull/1130
  - [x] Files https://github.com/nextcloud/circles/pull/1525
  - [x] Talk https://github.com/nextcloud/spreed/pull/11741
  - [ ] Calendar https://github.com/nextcloud/calendar/issues/5842
  - [ ] Groupfolders https://github.com/nextcloud/groupfolders/issues/2845

## Stretch goal

- [ ] https://github.com/nextcloud/circles/issues/1508

## Polishing

- [ ] #44087

## Out of scope for now

- [ ] Generic way of sharing to a team (through overview page)

<details>
<summary>Previous discussions</summary>

## Discussion

- Based on circles, a circle can be used to create a space for a team or project 
  - We can reuse existing logic in apps
- Breaking this down to smaller workable tasks
- Competitors have similar concepts (Sharepoint, confluence, notion, [Dropbox](https://blog.dropbox.com/topics/product-tips/make-remote-work-easier-with-dropbox-spaces))
- Further input https://github.com/nextcloud/circles/issues/1456

As discussed in the planning call we should aim for a cross app/team implementation of this, so the UI flow to create a new project can be reused. 

- [ ] Clarify with design
  - How does the flow to create a new project look like for individual apps
  - How does the flow of adding a resource to a project look like
- [ ] Clarify technical architecture
  - As we aligned on making this based on circles, my suggestion would be to come up with a generic server API for listing, creating, updating, deleting projects and adding/removing ressources to it. Circles can hold the implementation of this API. 
  - Another part can be providers for the resources which then can be implemented in the individual apps. I'll outline my idea there in more detail to discuss further in the team
- [ ] Split MVP in individual tasks
- [ ] Involve other teams where relevant

## Unified entrypoint

- Allow users to create a team/project with required resources
- Give people an overview and quick navigation to all relevant resources
- Future idea, provide a customizable dashboard like entrypoint
- Using collectives 
  - Collectives already has a shared ownership model, there is a circle automatically created for each collective
  - There are some things that we could nicely reuse for an iterative process of developing such features
  - Collective somehow matches in naming to also cover more then just wiki/knowledge base
  - Also matches the vision Jonas/Max had to be more then just a wiki
- Using contacts UI in circles
  - We got feedback that this is not discoverable (not where users expect it)
- Separate App / UI 
  - Might be better from feature visibility perspective
  - Might give admins a better overview / management interface
  - Larger development effort then reusing existing parts for now
  - Introduces yet another concept

> Suggestion of features to implement:
>
> - **Extend the collectives app to allow creating other resources** 
>   - Those will be shared automatically with this circle
>   - Find a generic approach / API to expose such providers
>   - Decide on what apps should be supported and involve other teams
> - **We display the common resources in Collectives (e.g. navigation or landing page)**
> - This should be a reusable component so it can be added to other apps

![image](https://github.com/nextcloud-gmbh/office-team/assets/3404133/ec597839-c229-41cf-8e1b-c30270295875)

## Cross reference

- Reuse related resources
- Apps could allow creating other resources directly, e.g. when creating a talk room have a checkbox to also create a project with a corresponding collective and deck board

> Suggestion of features to implement:
>
> - **Together with design team: Prioritize circle project relations and show them more prominent, grouped**

![image (4)](https://github.com/nextcloud-gmbh/office-team/assets/3404133/93d0b8c3-5119-4bea-9017-e41627d50f2e)
![image (6)](https://github.com/nextcloud-gmbh/office-team/assets/3404133/b08ebe39-ab4a-475f-a5cf-8b018d8c5d4b)
![image (5)](https://github.com/nextcloud-gmbh/office-team/assets/3404133/5b3e28df-2ead-42cf-98fc-aecb8653f9ef)

## Shared ownership

- We can start with sharing to the circle, for now ownership transfer is a workaround
- Later on we can extend individual apps to have a ownership model of a circle

> Suggestion of features to implement:
>
> - **Together with the design team: Explore who this could work UI wise**

## Out of scope / for future iterations
- https://github.com/nextcloud/server/issues/22897

</details>

**Comment by pschopen** [comment]
Maybe this can serve as inspiration: #38615

**Comment by roberix** [comment]
Hi.

Incredible feature announcement and more then useful.

As enterprise customer I am looking forward to have this implemented.

Regards

Rob

**Comment by juliushaertl** [comment]
- ocs
  - list resource providers
  - create new resource for project (create and share with circle or make the circle the owner)
  - remove resource from project (deletes)
  - list resources for project
  - optional: list projects for user (or entity, see open questions)
- ocp
  - register resource provider
  - provider interface with
    - provider name (e.g. deck)
    - provider entity (e.g deck board)
    - icon as svg
    - create new resource for project
    - remove resource from project
 - apps implementing the provider interface 
 - open questions:
   - one resource in multiple projects
     - how to handle this? Sharing would still allow to share a deck board to multiple circles but it would conflict with the goal of the shared ownership concept for a project and its resources

**Comment by marcoambrosini** [comment]
Here are the final mockups:

**Collectives** 
[prototype](https://www.figma.com/proto/myU2Q1KMtJhpYwigPP6izg/Projects?page-id=239%3A408&type=design&node-id=239-526&viewport=669%2C462%2C0.09&t=fA95jjWSjxSqagVW-1&scaling=min-zoom&starting-point-node-id=245%3A1286&mode=design)
[dev link](https://www.figma.com/file/myU2Q1KMtJhpYwigPP6izg/Projects?type=design&node-id=245-1284&mode=dev)


**Other apps proectj picker flow**

**Comment by juliushaertl** [comment]
After the discussion we had, I have tried to summarize the outcome and separated this into the following individual tasks, to be filed as individual issues once confirmed:

## Teams dashboard widget

- Should list all teams (circles) a user is part of
- Should allow to expand a team to list all items that are shared with this specific team
- Should offer a button to navigate to the team management within contacts
- Requires mockup

## Renaming circles to 'Teams'

- Rename any user facing parts that mention Circle to Team and Circles to Teams

## Renaming contacts app to 'people'

- Rename the contacts app to People

## Improvements to contacts app team view (circles management)

- Simplify UI to hide advanced settings
- Add a related resource list to list all resources that are shared with a team

## Related resources for listing teams and the related resources of it in individual apps

- Should list teams that this item is part of
- Should provide other resources that are part of the same team
- Prioritize larger entities (e.g. folders) over small ones (e.g. files)
- Requires mockup based on existing related resources

## Related resources on Collective page
- Based on the current overview mockups and releated resources

---

## Not in scope for now

- New mechanism of adding existing resources to teams (sharing will be used) and we don't want to introduce another concept
- Create a new team from other places (e.g. dashboard widget, collectives), we guide users to the contacts app for now

**Comment by karlitschek** [comment]
looks good. Missing is an example 'Team' that exists by default. And the Teams widget should be one of the default widgets.

**Comment by karlitschek** [comment]
Another thing related to 'related ressources'. The related 'files' are less important then related Talk rooms, Group-folders, Calendars,...  So the files should be on the bottom. You can see the problem in our Engineering room.

**Comment by AndyScherzinger** [comment]
> Improvements to contacts app team view (circles management)
> 
> Simplify UI to hide advanced settings

Fine as long as hiding means the functionality is still available since circles is heavily used by some of our customers

**Comment by maximelehericy** [comment]
I like this, it looks promising :)

**Comment by sunjam** [comment]
> Rename the contacts app to People

Quick thought: contacts is the term used by Android, iOS, Windows, etc.  :shrug: It might be easier to understand as contacts is such a universal term, but use _people_ if that makes more sense. :heart:

**Comment by strugee** [comment]
@juliushaertl fyi you missed the README of nextcloud/deck - not sure if docs are in scope for this ticket

**Comment by juliushaertl** [comment]
Most relevant parts are in, closing as the rest is tracked in follow up issues.

**Comment by CoreyBurger** [comment]
I added this comment on the Circles issue, but thought I would put it here too:

Can I add a comment here - Teams is a truly terrible name for this project. Assuming it survives trademark issues with MS, I strongly suggest you rename it back to Circles. Why?

There are three groups looking for information under the term "Nextcloud Teams"

    People looking to integrate Nextcloud with Teams (the MS one that everybody just calls teams)
    People looking to compare Teams (the MS one) to Nextcloud
    People looking for information on Nextcloud Teams

All 3 are going to be tripping all over each other and be massively confused.

Circles was unique. Nobody used it, why it worked so well.

Please rename this back

**Comment by CoreyBurger** [comment]
The word teams might be used by lots of people, but when it comes to collaboration software, if you say teams, most people mean Teams (the MS one). This is just needless confusion when an existing name (circles) existing and was unique

**Comment by sunjam** [comment]
Please stop replying . Circles is taken directly from Google+ Circles. It was never unique, by design.

https://duckduckgo.com/?q=google%2B+circles&t=fpas&ia=web

**Comment by jakobroehrl** [comment]
What about adding the tables app to this?

**Comment by jancborchardt** [comment]
@jakobroehrl @pschopen yep, there is an issue open for this at https://github.com/nextcloud/tables/issues/142 :)
