### ISSUE TITLE
file is empty, although server reported x size

### ISSUE THREAD

**Issue by Dikay900** [nextcloud/server#4245]
### Steps to reproduce
1. create a big file directly into the nextcloud data folder
2. update files with occ
3. file acts differently with downloading in different ways

### Expected behaviour
file should have a file size

### Actual behaviour
file size is empty when downloading.
Nextcloud client reports the same thing - ... file is empty, although server reported x size...
Marking the file and press download on the web page (for downloading the marked) is working.
Downloading the file with left click or file menu -> download fails with a zero byte file.

not working link: https://nextcloud.local/remote.php/webdav/file.mp4
working link: https://nextcloud.local/index.php/apps/files/?dir=/&fileid=904413

### Server configuration

**Operating system**:
raspbian

**Web server:**
Apache2

**Database:**
`mysql  Ver 15.1 Distrib 10.0.30-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2`

**PHP version:**
```
PHP 7.0.16-3 (cli) (built: Feb 22 2017 10:03:06) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.16-3, Copyright (c) 1999-2017, by Zend Technologies
```

**Nextcloud version:** (see Nextcloud admin page)
11.0.2.7

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
```
Enabled:
  - bookmarks: 0.9.1
  - calendar: 1.5.2
  - contacts: 1.5.3
  - dav: 1.1.1
  - direct_menu: 0.10.1
  - federatedfilesharing: 1.1.1
  - files: 1.6.1
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - news: 10.1.0
  - notes: 2.2.0
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - tasks: 0.9.5
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.1.0
  - workflowengine: 1.1.1
Disabled:
  - activity
  - admin_audit
  - comments
  - encryption
  - external
  - federation
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_pdfviewer
  - files_retention
  - files_sharing
  - files_texteditor
  - files_trashbin
  - firstrunwizard
  - gallery
  - logreader
  - nextcloud_announcements
  - notifications
  - serverinfo
  - sharebymail
  - survey_client
  - systemtags
  - templateeditor
  - theming
  - updatenotification
  - user_external
  - user_ldap
  - user_saml
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.178.39",
        ],
        "datadirectory": "\/media\/hdd\/nxcloud\/data",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "ochvjilx2s62",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "admin",
        "mail_smtpmode": "php",
        "mail_domain": "yourcloud.local",
        "maintenance": false,
        "singleuser": false,
        "loglevel": "2",
        "log_type": "file",
        "logfile": "\/var\/www\/nextcloud\/data\/nextcloud.log",
        "knowledgebaseenabled": false,
        "enable_avatars": false,
        "enable_previews": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes, local hdd

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
FF 52.0.2

**Operating system:**
Win10 x64

**Comment by Dikay900** [comment]
seems to be #1707

**Comment by Dikay900** [comment]
ok can confirm #1707 is solving this issue as well

**Comment by rikiahmad2** [comment]
whats the solution to this ? pls tell me i have the some problem
