### ISSUE TITLE
[Bug]: Use system timezone in calculation of share times

### ISSUE THREAD

**Issue by Fenn-CS** [nextcloud/server#42453]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

A user encountered an issue when attempting to create share links in Nextcloud before 9:00 AM JST (UTC+09:00). After investigation, it appears there is an error in how we calculate share link expiration times, because looking at the code, we always use UTC irrespective of the users timezone.

![Screenshot from 2023-12-22 06-10-47](https://github.com/nextcloud/server/assets/14317775/fca80262-f0f2-4383-8735-6c2e823c1ff7)

### Steps to reproduce

1. Set the system clock to a time before 9:00 AM JST.
2. Set a default expiration time (which is in number of days).
3. Attempt to create a share link.

### Expected behavior

Share links should be created without encountering any issues irrespective of the time of day.

### Installation method

None

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Fenn-CS** [comment]
Likely culprits

https://github.com/nextcloud/server/blob/7d8741c53f7be7e77139f124e441e2ba10e66bf2/lib/private/Share20/Manager.php#L432-L438

and


https://github.com/nextcloud/server/blob/7d8741c53f7be7e77139f124e441e2ba10e66bf2/lib/private/Share20/Manager.php#L508-L514

**Comment by Fenn-CS** [comment]
Recommended fix : 

- Use `'default_timezone'`in config file which defaults to  `'Europe/Berlin'` (or perhaps should default to UTC as the normal php functions)
- User can then set their timezone in config and it would be respected.
- There is `TimeZoneService` in https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/TimezoneService.php perhaps we can make it a core service so it is used more widely

**Comment by ChristophWurst** [comment]
> * defaults to  `'Europe/Berlin'`

Defaults to UTC. Europe/Berlin is an example.
