### ISSUE TITLE
Shared folder to a group not shown in shared by me

### ISSUE THREAD

**Issue by taker218** [nextcloud/server#4246]
### Steps to reproduce
1. Create a new folder
2. Share it to a group
3. Go to Shared by me

### Expected behaviour
The folder should be visible in the tab Shared by me

### Actual behaviour
It's not showing. Only folders shared to users are shown.

### Server configuration

**Operating system**:
Synology Diskstation
**Web server:**
Apache 2.4
**Database:**
MariaDB
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
11.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
official page
**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

<?php
$CONFIG = array (
  'instanceid' => 
  'passwordsalt' => 
  'secret' => 
  'trusted_domains' => 
  array (
    0 => 'taker.justdied.com',
    1 => 'diskstation',
    2 => 'taker.ddns.info',
  ),
  'datadirectory' => '/volume1/nextclouddata',
  'dbtype' => 'mysql',
  'version' => '11.0.2.7',
  'dbname' => 'nextcloud',
  'dbhost' => '127.0.0.1',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_thomas',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
  'trashbin_retention_obligation' => '2,5',
  'versions_retention_obligation' => '10,30',
  'loglevel' => 0,
); 
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Chrome/Firefox Developer Edition
**Operating system:**
Windows 10
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
No Logs available
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
cc @rullzer @schiessle

**Comment by schiessle** [comment]
I just did a short test and couldn't reproduce it. Works everything as expected here. Do you have any errors in your nextcloud.log or JS Console when you go to "Shared with others"?

**Comment by taker218** [comment]
Strange, it works for me now as well.
Just did the same as yesterday:
Remove the group from the share and readd it. Now it is shown.

**Comment by schiessle** [comment]
maybe some browser caching? But great to hear that it works now for you as well! 😃
