### ISSUE TITLE
[Bug]: Missing v28.0.1 Release set as Latest

### ISSUE THREAD

**Issue by calvin-li-developer** [nextcloud/server#42462]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hey,
It seems like the v28.0.1 tag is there but is not released for v28.0.1 on GitHub nextcloud/server repo page.

This is similar to https://github.com/nextcloud/server/issues/39845

### Steps to reproduce

see description and https://github.com/nextcloud/server/issues/39845 and https://github.com/nextcloud/server/issues/41172

### Expected behavior

One of the following:
    Releases on Github repo as new versions get tagged

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Cc: @blizzz @skjnldsv

**Comment by Mat-DB** [comment]
Any update on this?
Since 28.0.0 has quite a few annoying bugs I am waiting for 28.0.1.
My apologies for asking this on Christmas though.
Thanks and merry Christmas!

**Comment by joshtrichards** [comment]
Fixed: https://github.com/nextcloud/server/releases
