### ISSUE TITLE
[Bug]: Move or copy files and folders fails

### ISSUE THREAD

**Issue by gibelium** [nextcloud/server#42469]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The "move or copy" function in the WebInterface fails for files and folders as well.

- No log entry is written
- Error message "'Move or copy' action failed" is show in the info area at the upper right of the weg interface
- Moving files/folders on a local client machine and syncing the changes via Nextcloud Desktop App works without issues

### Steps to reproduce

1. Create a file or folder in your privat home folder
2. Create a folder "Test" in your home folder
3. Open 3-dots menu for the file or folder created in step 1
4. Select "move or copy" option and select the folder created in step 2
5. Select "Copy to TEST" or "Move to TEST" (both will fail)
6. See the error message "'Move or copy' action failed"
7. Check the log reader and see that no error has been written ti the log file

### Expected behavior

1. "Copy or move" function actually moves or copies files and folders without error.
2. If an error occurs a meaningful log entry is created

### Installation method

Community VM appliance

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
This sounds like #41414, but that shouldn't exist in the general release due to #42057. Are you certain you're not running a Release Candidate build? [Providing the output of `occ config:list system` *and* running an integrity check would probably be the most reliable ways to try confirming that.]

**Comment by melianmiko** [comment]
Ran into same problem, Nextcloud 28.0.1 from [docker image](https://hub.docker.com/_/nextcloud).

> occ config:list system and running an integrity check

[output.txt](https://github.com/nextcloud/server/files/13778587/output.txt)

**Comment by PolishTanker** [comment]
The same story. On Nextcloud Windows Client, everything works. But it is apparently due to different approach to moving files.
Web UI can't do this job and fails when you try to move files. Earlier this worked.

![image](https://github.com/nextcloud/server/assets/16049890/8347c300-e355-4927-9296-db1fbd1382df)

[config list system.txt](https://github.com/nextcloud/server/files/13801496/config.list.system.txt)

**Comment by flysaber** [comment]
I also encountered the same error, which occurred on the server side (I am not using the desktop version). I used the setup-nextcloud.php file for online installation and installed the latest version of nextcloud on Ubuntu 22.04, using Apache, PHP 8.1, and MySQL 8 environments.

**Comment by joshtrichards** [comment]
I'm unable to reproduce this.

> 1. Create a file or folder in your privat home folder
> 2. Create a folder "Test" in your home folder

Already have a test file (a simple document).
I'm creating a folder `/TestMove`
I'm selecting *Move or Copy* from the 3-dot menu next to my test file.
I'm selecting `/TestMove` as the target.

- What are your underlying filesystems/mount types?
- Are either the source or destination shared or External Storage mounts in NC?
- Is encryption and/or end_to_end_encryption in-use?

**Comment by OsirisDBA** [comment]
I'll try to isolate my case, right now it's to complicated.

My case is the following:

Nextcloud:latest docker on unraid
Group folders extension installed
Created a group folder, determined path
Shut down container
Create an unraid share
Mount an unraid path as a volume at the group folder path
Start container
Scan all files

Moves and copies work maybe 1 of 10 tries.
But I'm also moving between mounts.

There are no log entries. I get the move or copy failed message and in the
upper left there are some flashing broken image links.

Like I said, to complicated. I'll try and simplify.

**Comment by alboon** [comment]
Moving in the app works, website ui doesn't work, have the same issue unraid docker. just updated to "version": "28.0.1.1" using nginx as a proxy but never had issues before moving stuff in the web UI.

**Comment by melianmiko** [comment]
Tried this browsers, it don't work:
- Chromium (plain, ArchLinux build, 120.0.6099.129-1)
- Firefox (ArchLinux build, 121.0-1)
- Vivaldi (6.5.3206.48)
- Microsoft Edge (version unknown, built-in to Win10)

**BUT**, sometimes after 2-10 page refreshes it starts working. Found that in Vivaldi & Edge. idk why, disabling cache or clearing cookies don't matter.

> All browsers tested without any third-party extensions, of course. Wipe of cache/cookies don't help.

**Comment by szaimen** [comment]
cc @nextcloud/files

**Comment by novikov1337danil** [comment]
Faced the same problem

**Comment by hiweed** [comment]
I got the same problem, when I clicked move and copy menu item to do the action, the dest dir actually have contents show  nothing ,and I check the chrome console reported "Failed to load resource:https://ip:port/core/preview?fileId=522&x=32&y=32&mimeFallback=true&a=0&c=659a5a5855cf3 the server responded with a status of 404 () ",then the browser shows "move and copy failed"，but no server error log saved in data/nextcloud.log or niginx error logs.

**Comment by mherweg** [comment]
we have the same (or similar) issue since update to 28. If I try to copy a file ____TO THE SAME FOLDER____ then in the Web-UI the 2 buttons "copy to..."  "move to.."  don't appear anymore.  In Nextcloud version 27 the copy is created and renamed to FILENAME_copy

**Comment by ilsawa** [comment]
After upgrading to v28, when copying a file to a subfolder, I get a message that it is impossible to do this. At the same time, there are no messages in the logs.

**Comment by susnux** [comment]
@mherweg that is handled by https://github.com/nextcloud/server/issues/41768

**Comment by Vlad-Star** [comment]
I can confirm a problem with "Copy or Move" button in 28.0.1 attempted through the UI. Drag-n-drop move works just fine. No related errors in a log, even with `'debug' => true` in the **config.php**

**Comment by susnux** [comment]
Please do not spam the tickets if you do not have any additional information but just leave a :+1:  reaction on the initial post.

But please as soon as 28.0.2 is published, test and report back :)

**Comment by alboon** [comment]
Still broken in 28.0.2rc3

**Comment by khlschrnk** [comment]
I ran into the same issues that moving files is not possible without further info. I found out that it happens if the destination folder starts (or maybe contains) with '#' (number sign). Happens with Firefox and Chrome.

After renaming the destination folder to remove the number sign moving files works.

**Comment by maaikez** [comment]
I have the same issue. For one (of the two) user.

So:
- I make a new directory with files
- I share the whole directory with another user
- The other user tries to move the directory to another directory (so it's not in root anymore)
- This fails.

But if he makes a new directory with files and I do exactly the same, it passes. 
Drag and drop does also not work for him.

**Comment by nirurin** [comment]
So 10 months later, and this is still an issue? 
Currently can't move any files. I can upload them and I can copy them inside the folders to make new copies... but I can't move files, and I can't delete files. They appear as moved/deleted briefly but when I refresh the page or window (depending on if I'm doing it via the browser gui or the windows app) they just reappear back where they were. 

Nothing in logs at all.

**Comment by joshtrichards** [comment]
@maaikez & @nirurin: As you can see, this particular Issue has been addressed and closed (it was fixed with weeks of being reported). If you're experiencing anything remotely similar, it likely has a different underlying cause. Please open dedicated Issue(s) so that we have all the pertinent details about your situation in order to look into it.
