### ISSUE TITLE
[Bug]: After upgrade to 28.0.1 errors "Your web server is not properly set up to resolve "/.well-known/caldav". occur

### ISSUE THREAD

**Issue by TheWojtek** [nextcloud/server#42472]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading the Nextcloud instance from 27.1.4 to 28.0.1, the server started throwing errors of:

_Your web server is not properly set up to resolve "/.well-known/caldav"
Your web server is not properly set up to resolve "/.well-known/carddav"_

While the server runs behind a reverse proxy, it has been configured properly for the past 3 years and has always passed the check with flying colors. It also actually **does properly redirect** from https://servername.com/.well-known/caldav and /carddav to https://servername.com/remote.php/dav from a browser or a https client (I am using Cocoa Rest Client on MacOS). There were never any redirection errors in this server anyway.

The upgrade was done to the exact steps of the "manual Nextcloud upgrade", which is how I always do the upgrades. The config file was transferred directly without any changes from 27.1.4 to 28.0.1.

### Steps to reproduce

1. Check a 27.1.4 installation for any errors in "Administration → Overview". If none, proceed.
2. Upgrade the 27.1.4 installation to 28.0.1 using steps from "manual Nextcloud upgrade" guide.
3. Check the server upgraded to 28.0.1 in "Administration → Overview" for configuration errors.

### Expected behavior

Clean (error-free) Admin Overview as it was with the version Nextcloud was upgraded from, without falsely claiming the upgraded Nextcloud instance has configuration problems.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "default_phone_region": "PL",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.3",
            "***REMOVED SENSITIVE VALUE***.gotdns.ch",
            "cloud.***REMOVED SENSITIVE VALUE***.pl",
            "cloud.***REMOVED SENSITIVE VALUE***"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "dbtype": "mysql",
        "version": "28.0.1.1",
        "overwrite.cli.url": "http:\/\/cloud.***REMOVED SENSITIVE VALUE***.pl\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "maintenance": false,
        "theme": "",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 0,
        "0": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtpport": "587",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "occweb",
            "impersonate"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - approval: 1.2.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.0
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_external: 1.20.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - groupfolders: 16.0.1
  - impersonate: 1.15.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - occweb: 0.1.1
  - password_policy: 1.18.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - socialsharing_twitter: 3.0.1
  - spreed: 18.0.1
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - bruteforcesettings: 2.8.0
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 1.11.0)
  - files_pdfviewer: 2.9.0 (installed 2.1.0)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - nextcloud_announcements: 1.17.0 (installed 1.10.0)
  - photos: 2.4.0 (installed 1.3.0)
  - recommendations: 2.0.0 (installed 1.0.0)
  - sharebymail: 1.18.0 (installed 1.11.0)
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
**Numerous erors in type below, not happening before upgrade**:

Exception
HMAC does not match.
Could not decrypt or decode encrypted session data

2023-12-24T09:24:28+00:00	

Error	PHP	
TypeError: OCA\UserStatus\Controller\UserStatusController::__construct(): Argument #3 ($userId) must be of type string, null given at /var/www/nextcloud/apps/user_status/lib/Controller/UserStatusController.php#53
```

**Comment by joshtrichards** [comment]
The check runs from your browser - can you check your browser console including the network tab while running a test?

This is nearly always a configuration matter.

e.g. https://github.com/nextcloud/server/issues/34737#issuecomment-1769669085

One thing that stands out to me in your config:

`        "overwrite.cli.url": "http:\/\/cloud.***REMOVED SENSITIVE VALUE***.pl\/",`

Should that not be `https://`?

Likely unrelated but also of note:

- You have an app force enabled that doesn't support NC28 (e.g. `occweb`)
- This line in your `config.php` is bogus: `"0": true,`

**Comment by TheWojtek** [comment]
@joshtrichards Thank you for your response!
First, the check done from the browser. First of all - the .well-known errors have magically disappeared. I hope you don't mind it's a screenshot: 
<img width="1343" alt="Screenshot 2023-12-26 at 3 01 43 PM" src="https://github.com/nextcloud/server/assets/10579189/dbb2de03-5e47-44c4-b14f-4b1dae8e35b8">
Do I have to care about the webfinger error?

The fixes I did by your suggestions:
- As per the OPCache error description, I double-checked the OPCache settings and adjusted accordingly. After a webserver restart I have no errors in regards of .well-known
- I fixed the `"0": true` line. Can't even remember what I tried to solve with that.
- I fixed the forced OCC Web app by disabling it.

The `http` in `"overwrite.cli.url"` was intended, as this server runs behind a reverse proxy that handles SSL and forces https on clients. The server used to resolve internally with a private IP so if set to https NC gave unexpected results of different certificates for the same server. I switched the DNS to resolve the server to a public IP an will keep an eye on users' experience.

Still unresolved: the log is still plagued ("30 errors in log") with:

`TypeError: OCA\UserStatus\Controller\UserStatusController::__construct(): Argument #3 ($userId) must be of type string, null given at /var/www/nextcloud/apps/user_status/lib/Controller/UserStatusController.php#53`

**Comment by Struppi** [comment]
I just want to add that I actually got the very same curios situation on a fresh docker installation ([Nextcloud Hub 7](https://nextcloud.com/) (28.0.1)). 

10 minutes ago there was the message "Your web server is not properly set up to resolve "/.well-known/caldav"" now it's gone. Also behind a reverse proxy (nginx). and I also have those message in the error logs.

And - that's the reason I am searching about this error message - I can't share folders anymore. but only with a Browsers on desktop. the Android app is still working. When I try to share I got the Message the message browser console "OC.MimeType is undefined"

**Comment by ryanhagen** [comment]
@Struppi FWIW I had this same issue that was solved with a firewall rule that was not allowing the network to access nextcloud.com or apps.nextcloud.com. Fixed that issue and everything magically started working.

**Comment by EBendinelli** [comment]
I think I'm encountering a similar issue here. I upgraded from 27.1.4 to 28.0.1. today. Ran into an issue with the online updater that left the site on maintenance mode and hade to complete the upgrade via ```php occ upgrade```. This worked out well but I know have the follow error message: "Error occurred while checking server setup" in the admin panel

![image](https://github.com/nextcloud/server/assets/12803082/752528dd-6600-437b-853d-4c55d6cd1837)

Looking at the console I'm getting a 404 on those links:
```
https://mysite.com/settings/ajax/checksetup
https://mysite.com/data/.ocdata?t=1704999104205
https://mysite.com/index.php/.well-known/webfinger
https://mysite.com/.well-known/nodeinfo
```

Nextcloud seems to be running well and logs are empty. I've run ```php occ integrity:check-core``` with no error. I haven't touched my nginx config in a while and it's very similar to the documentation one.

**Comment by kesselb** [comment]
@TheWojtek can we close your report?

**Comment by TheWojtek** [comment]
@kesselb Yes, this error is gone now. Thank you.
