### ISSUE TITLE
[Bug]: Downloading multiple files or folder from webgui does not work

### ISSUE THREAD

**Issue by Chamber3399** [nextcloud/server#42470]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When you download a folder or multiple files, it tries to download a htm file ("download.htm"), which fails due to a "site not available". Individual files work fine.

Nginx log shows the following error:

`"OC_Util" not found in /config/www/nextcloud/apps/files/ajax/download.php:31`

### Steps to reproduce

1. Log into webgui
2. Select multiple files or folder
3. Click download button

### Expected behavior

A zip file should be generated and downloaded

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Other

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - bruteforcesettings: 2.8.0
  - calendar: 4.6.1
  - checksum: 1.2.2
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.0
  - contactsinteraction: 1.9.0
  - cookbook: 0.11.0
  - cospend: 1.5.13
  - dashboard: 7.8.0
  - dav: 1.29.1
  - deck: 1.12.0
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_automatedtagging: 1.18.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - integration_openai: 1.2.0
  - integration_replicate: 1.0.8
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - mail: 3.5.0
  - maps: 1.3.1
  - nextcloud_announcements: 1.17.0
  - notes: 4.9.1
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recognize: 6.0.1
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - richdocuments: 8.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.0
  - sharebymail: 1.18.0
  - spreed: 18.0.1
  - support: 1.11.0
  - survey_client: 1.16.0
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0
  - tables: 0.6.5
  - tasks: 0.15.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - twofactor_webauthn: 1.3.2
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - encryption: 2.16.0
  - files_external: 1.20.0
  - files_rightclick: 1.6.0 (installed 1.6.0)
  - forms: 4.0.0 (installed 4.0.0)
  - health: 2.2.2 (installed 2.2.2)
  - metadata: 0.19.0 (installed 0.19.0)
  - polls: 6.0.1 (installed 6.0.1)
  - updatenotification: 1.18.0 (installed 1.17.0)
  - user_ldap: 1.19.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by joshtrichards** [comment]
Unable to reproduce and based on the behavior and error this looks like a configuration/filesystem/image matter in your environment. It appears you're using LInuxServer.io's Docker image[1] (not the community Docker image). Perhaps something went wrong when you transitioned to their new image structure[2]? 

Since this isn't a bug in `server` or the community Docker image, I suggest posting over at either the Nextcloud Help Forum[3] or the LinuxServer.io Forum[4] if you need help troubleshooting.

[1] https://docs.linuxserver.io/images/docker-nextcloud/
[2] https://info.linuxserver.io/issues/2023-06-25-nextcloud/
[3] https://help.nextcloud.com
[4] https://discourse.linuxserver.io/

**Comment by Bastilms** [comment]
I have the same issue using the official `nextcloud:28.0.1-fpm` Docker image. The downloaded File `download.php.html` contains the following line. 
`Fatal error: Uncaught Error: Class "OC_Util" not found in /var/www/html/apps/files/ajax/download.php:31 Stack trace: #0 {main} thrown in /var/www/html/apps/files/ajax/download.php on line 31`

**Comment by joshtrichards** [comment]
See https://github.com/nextcloud/server/issues/42617#issuecomment-1881958718 for an update.

**Comment by kunago** [comment]
It does not apply for non-nginx proxy servers. I have been running a docker version fpm-alpine with Caddy as a proxy and the only dirty hack for now is to hack the download.php file directly as it misses includes for some reason. See https://github.com/nextcloud/server/issues/42617#issuecomment-1898249946.

**Comment by joshtrichards** [comment]
@kunago https://github.com/nextcloud/server/issues/42617#issuecomment-1898493577
