### ISSUE TITLE
Shared filters are not rerendered

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#4248]
1. Create a folder `foo`
2. Share that folder
3. Navigate to `Shared with others`
4. Navigate to `Shared with you`
5. Navigate to `Shared with others`

Expected: View in step 3 and 5 is the same

Actual: No content in step 5

Note that the info is there (the count at the bottom is correct). Also when you sort the folders appear again.

@nextcloud/javascript

**Comment by ChristophWurst** [comment]
Looks like https://github.com/nextcloud/server/pull/3686 broke it.

No idea what the if-condition https://github.com/nextcloud/server/pull/3686/files#diff-dafefd9519924bec4efa9f5af4af8e68R562 does or how we have to adjust it, but the `_onUrlChanged` method returns early in step 5.

cc @MorrisJobke

**Comment by rullzer** [comment]
@ChristophWurst thnx... fix is in #4293
