### ISSUE TITLE
[Bug]: problem of synchronisation with tasks and calendar [BusyCal]

### ISSUE THREAD

**Issue by sgraillat** [nextcloud/server#42492]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

There is a problem with delta sync for calendar and tasks. I use BusyCal on iOS and macOS and sometime I move some tasks and when I asked BusyCal to synchronise the server returns that nothing has changed.

### Steps to reproduce

There is a problem with delta sync for calendar and tasks. I use BusyCal on iOS and macOS and sometime I move some tasks and when I asked BusyCal to synchronise the server returns that nothing has changed.

### Expected behavior

There is a problem with delta sync for calendar and tasks. I use BusyCal on iOS and macOS and sometime I move some tasks and when I asked BusyCal to synchronise the server returns that nothing has changed.

### Installation method

None

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Any chance you can fill out the complete Issue template? All bug reports are appreciated, but we don't have time to go on "wild goose chases".

It would also be helpful to understand how you determined the following:

> when I asked BusyCal to synchronise the server returns that nothing has changed.

... as well as if you could describe the precise reproduction steps. Thank you!

**Comment by flortsch** [comment]
Which Nextcloud 26 version are you running in specific? Could this be related to https://github.com/nextcloud/server/issues/36644?

**Comment by sgraillat** [comment]
Hello,

In fact, I made a mistake. The version of NextCloud used is 25.0.8.2.
It could be related to #36644 but I am not exactly sure.

Best regards.

**Comment by joshtrichards** [comment]
> I used NextCould 25.0.8.2. 

NC25 is no longer supported. Please upgrade to a supported version.
