### ISSUE TITLE
[Bug]: Disabled HTML inputs don't appear disabled visually

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#42498]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The HTML `<input type="text" placeholder="Name" autofocus="autofocus" disabled>` does not *look* disabled inside Nextcloud

![Bildschirmfoto vom 2023-12-27 14-39-37](https://github.com/nextcloud/server/assets/1374172/16e28865-aeaf-4eab-87f7-47b200aa891e)

### Steps to reproduce

1. Render HTML with disabled inputs

### Expected behavior

![image](https://github.com/nextcloud/server/assets/1374172/aaf8417a-f929-4ba9-a817-d7008f806edb)

(manual hack)

### Installation method

Other Community project

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ChristophWurst** [comment]
Styles appear to come from ``core/css/inputs.scss``. The current rules set a background color regardless of disabled state. The default styling of the browsers has no effect.

**Comment by ChristophWurst** [comment]
Not fixed

**Comment by susnux** [comment]
need new nextcloud/vue release

**Comment by ChristophWurst** [comment]
> The HTML `<input type="text" placeholder="Name" autofocus="autofocus" disabled>` does not _look_ disabled inside Nextcloud

I meant to say that *any* HTML `<input>` needs a disabled state, not NcInput specifically ;)

**Comment by jancborchardt** [comment]
Switching assignments over from @marcoambrosini to @szaimen as discussed in design meeting. :)

**Comment by szaimen** [comment]
I had a look and it looks like the best way would be to transform all input fields in `index.php/settings/user` to NCinputfield. However this is a bit of a bigger change than simple css, so I would recommend that one frontender takes over.

**Comment by ChristophWurst** [comment]
Issue remains for HTML inputs that don't use Nc*

The screenshot of my report is from the setup page of Mail

**Comment by jancborchardt** [comment]
@susnux FYI in case you didn’t see Christoph’s comment. :) Also cc @sorbaugh as this can possibly be an accessibility issue, so we should indeed fix it.

**Comment by susnux** [comment]
Yes I saw it but that means our styles need to be adjusted, see pr
