### ISSUE TITLE
[Bug]: No log 'untrusted domain' attempts

### ISSUE THREAD

**Issue by DavidMndz** [nextcloud/server#42514]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When you try to access the Nextcloud server through an untrusted domain, not configured for the server, the software shows an error stating the access is being attempted through an untrusted domain, not letting you log in.

The problem is that this attempt is not logged into the log files anymore, being a security issue as the data there cannot be used for block that IP (like using fail2ban).

The issue has been discussed here: https://help.nextcloud.com/t/nextcloud-27-0-0-not-logging-trusted-domain-errors-in-log/166430

### Steps to reproduce

1.Try to log in your Nextcloud instance using a name / IP that connects to it, but it is not part of trusted domains in the configuration file.
2.Check the nextcloud.log.

### Expected behavior

The nextcloud.log should log this attempt as in previous versions.

### Installation method

None

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
`'loglevel' => 1`

(It's logged at `INFO` level)

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html
