### ISSUE TITLE
[Bug]: Theme color not applied properly to icons

### ISSUE THREAD

**Issue by SMH17** [nextcloud/server#42517]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After the recent upgrade to Nextcloud 28 the theme color for icons isn't applied correctly anymore.

In this picture you can see the folder icon color correctly matches the theme color, archive and document icons ignore the selected color.
![sample_bugx](https://github.com/nextcloud/server/assets/8108287/56551665-c035-4be0-9016-8a8821e49daa)

### Steps to reproduce

1. Select a custom theme color
2. Upload a compressed archive
3. Check the icon color in nextcloud web GUI

### Expected behavior

Theme color should be applied consistently to choice.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Update

**Comment by SMH17** [comment]
After the update to 28.0.2 the theme color is totally ignored even for folders and selection highlight. 

This bug can be reproduced when it is selected "Dark Theme" in "Appearance and accessibility settings".

**Comment by susnux** [comment]
> In this picture you can see the folder icon color correctly matches the theme color, archive and document icons ignore the selected color.

I have to correct myself. This is by design.
Folders are color primary, while documents are by design always that blue.
Like pdf is always red, documents are always blue.
