### ISSUE TITLE
NextCloud demo are outdated

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/server#42536]
The demo on demo1.nextcloud.com and so on are using NC25! We should update this environment to NC28

### Expected behavior

The latest version so we can provide the best experience for everyone.

**Comment by szaimen** [comment]
Cc @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
I will check who can update it.

**Comment by tobiasKaminsky** [comment]
Sysadmin it is.
We will do soon and have it tracked internally.
Added it also as todo in our release overview.
