### ISSUE TITLE
[Bug]: Email server configuration

### ISSUE THREAD

**Issue by hamzaouichaker** [nextcloud/server#42546]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nextcloud version: 27.1.5
I have 2 nextcloud server with the same version: one prod and on test.
the issue is that the email server configuration is not working with my local smtp server for the prod server but it is working for the test nextcloud server.

Configuration For Test Server:
  'mail_from_address' => 'MyEmailAddress',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => 'Mudomain',
  'mail_smtphost' => 'IPhost',
  'mail_smtpport' => '25',
  0 => 'opcache.save_comments = 1',
  1 => 'opcache.revalidate_freq = 60',
  "mail_smtpstreamoptions" => array(
    'ssl' => array(
        'allow_self_signed' => true,
        'verify_peer' => false,
        'verify_peer_name' => false
    )
  ),

===> it is working for the test server fine but not for the prod server.

Configuration of the prod server:
'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => 'hotmail.com',
  'mail_from_address' => 'myhotmailemail',
  'mail_smtphost' => 'smtp.office365.com',
  'mail_smtpport' => '587',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'myhotmailemai@hotmail.com',
  'mail_smtppassword' => 'mupassword',

==> it is working for my prod server.

The issue is I need to use our official email address to send email to customers, it is a workaround but I need to fix it.

### Steps to reproduce

1.use local email address
2. use the port 25
3. disable the Authentification

### Expected behavior

I expect that the Test configuration worked for the prod server.

### Installation method

None

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "NXTC01.domain.local",
            "share.domain.de",
            "72.33.200.220"
        ],
        "overwrite.cli.url": "https:\/\/share.telent.de",
        "htaccess.RewriteBase": "\/",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "\/var\/www\/nextcloud-daten\/eigenes-skeleton\/",
        "dbtype": "mysql",
        "version": "27.1.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "theme": "",
        "loglevel": 1,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trashbin_retention_obligation": "auto",
        "check_for_working_htaccess": true,
        "default_phone_region": "DE",
        "updater.release.channel": "stable",
        "0": "opcache.save_comments = 1",
        "1": "opcache.revalidate_freq = 60",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

root@NXTC01:/var/www/nextcloud# php occ config:list system
Console has to be executed with the user that owns the file config/config.php
Current user id: 0
Owner id of config.php: 33
Try adding 'sudo -u #33' to the beginning of the command (without the single quotes)
If running with 'docker exec' try adding the option '-u 33' to the docker command (without the single quotes)


root@NXTC01:/var/www/nextcloud# ./occ config:list system
-bash: ./occ: Permission denied
```

### List of activated Apps

```shell
root@NXTC01:/var/www/nextcloud# sudo -u www-data php occ app:list
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - announcementcenter: 6.7.0
  - bruteforcesettings: 2.7.0
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contactsinteraction: 1.8.0
  - data_request: 1.14.0
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - fileslibreofficeedit: 1.1.0
  - flow_notifications: 1.7.0
  - impersonate: 1.14.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - nextcloud_announcements: 1.16.0
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - quickaccesssorting: 3.0.0
  - quota_warning: 1.18.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - richdocumentscode: 23.5.604
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - side_menu: 3.11.2
  - socialsharing_email: 3.0.1
  - survey_client: 1.15.0
  - suspicious_login: 5.0.0
  - text: 3.8.0
  - theming: 2.2.0
  - theming_customcss: 1.15.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_ldap: 1.17.0
  - user_retention: 1.11.0
  - viewer: 2.1.0
  - workflow_pdf_converter: 1.12.0
  - workflowengine: 2.9.0
Disabled:
  - apporder: 0.15.0 (installed 0.15.0)
  - dashboard: 7.7.0 (installed 7.0.0)
  - encryption: 2.15.0 (installed 2.15.0)
  - files_external: 1.19.0 (installed 1.10.0)
  - firstrunwizard: 2.16.0 (installed 2.8.0)
  - flowupload: 1.1.3 (installed 1.1.3)
  - hsts: 0.9.0 (installed 0.9.0)
  - ransomware_protection: 1.14.0 (installed 1.14.0)
  - sharingpath: 0.4.4 (installed 0.4.4)
  - support: 1.10.0 (installed 1.2.1)
  - systemtags: 1.17.0 (installed 1.9.0)
  - twofactor_totp: 9.0.0
  - user_status: 1.7.0 (installed 1.4.0)
  - weather_status: 1.7.0 (installed 1.0.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by tzerber** [comment]
Try changing the SMTP port to 465. Sometimes (and i believe it's some library issue with STARTTLS, but never really looked into it) it works, but most of the time it doesn't with 587. I think Micro$oft supports SSL connections to the smtp server.

**Comment by joshtrichards** [comment]
I suggest turning on the appropriate debug modes and troubleshooting as per the manual:

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/email_configuration.html#enabling-debug-mode

Since this seems more like a configuration matter rather than a bug, please follow-up at the Nextcloud Help Forum - https://help.nextcloud.com to get help troubleshooting. If after doing that a likely bug becomes apparent, feel free to come back and create an issue covering it.

**Comment by hamzaouichaker** [comment]
> I suggest turning on the appropriate debug modes and troubleshooting as per the manual:
> 
> https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/email_configuration.html#enabling-debug-mode
> 
> Since this seems more like a configuration matter rather than a bug, please follow-up at the Nextcloud Help Forum - https://help.nextcloud.com to get help troubleshooting. If after doing that a likely bug becomes apparent, feel free to come back and create an issue covering it.

Thank you for your replay.
The problem is since the update from the version 25, the same configuration worked in the test server but not for the Prod server.

**Comment by tzerber** [comment]
It was in fact configuration error. After re-following the documentation SSL works fine for email.

**Comment by hamzaouichaker** [comment]
> It was in fact configuration error. After re-following the documentation SSL works fine for email.

Thank you for your replay.
Can you please provide me more details, which configuration I need to change.

**Comment by tzerber** [comment]
> > It was in fact configuration error. After re-following the documentation SSL works fine for email.
> 
> Thank you for your replay. Can you please provide me more details, which configuration I need to change.
Can you provide me what type of connection you're using ? Plain one, starttls or ssl ? If SSL, is it using self-signed certificates or not ?

**Comment by hamzaouichaker** [comment]
> > > It was in fact configuration error. After re-following the documentation SSL works fine for email.
> > 
> > 
> > Thank you for your replay. Can you please provide me more details, which configuration I need to change.
> 
> Can you provide me what type of connection you're using ? Plain one, starttls or ssl ? If SSL, is it using self-signed certificates or not ?

the connection used is Plain.

**Comment by tzerber** [comment]
> > > > It was in fact configuration error. After re-following the documentation SSL works fine for email.
> > > 
> > > 
> > > Thank you for your replay. Can you please provide me more details, which configuration I need to change.
> > 
> > 
> > Can you provide me what type of connection you're using ? Plain one, starttls or ssl ? If SSL, is it using self-signed certificates or not ?
> 
> the connection used is Plain.

I will not discuss how bad idea unsecured email is, but:
Make sure you're using port 25. 
Make sure you are using the smtp server with it's correct name/ip address and it's reachable (try telnet on the host:25 , type EHLO command and expect reply).

If your mailserver is running docker, make sure the NC instance and mailserver share a network, even if it's separate dedicated network for them otherwise DNS/Connection between them will not work.

Example config:
```php
  'mail_domain' => 'example.com',
  'mail_from_address' => 'cloud',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.example.com',
  'mail_smtpport' => '25',
  'mail_smtpname' => 'cloud@example.com',
  'mail_smtppassword' => 'Sup3rSecr3tPassw0rd',
```

**Comment by hamzaouichaker** [comment]
> > > > > It was in fact configuration error. After re-following the documentation SSL works fine for email.
> > > > 
> > > > 
> > > > Thank you for your replay. Can you please provide me more details, which configuration I need to change.
> > > 
> > > 
> > > Can you provide me what type of connection you're using ? Plain one, starttls or ssl ? If SSL, is it using self-signed certificates or not ?
> > 
> > 
> > the connection used is Plain.
> 
> I will not discuss how bad idea unsecured email is, but: Make sure you're using port 25. Make sure you are using the smtp server with it's correct name/ip address and it's reachable (try telnet on the host:25 , type EHLO command and expect reply).
> 
> If your mailserver is running docker, make sure the NC instance and mailserver share a network, even if it's separate dedicated network for them otherwise DNS/Connection between them will not work.
> 
> Example config:
> 
> ```
>   'mail_domain' => 'example.com',
>   'mail_from_address' => 'cloud',
>   'mail_smtpmode' => 'smtp',
>   'mail_sendmailmode' => 'smtp',
>   'mail_smtpauthtype' => 'PLAIN',
>   'mail_smtpauth' => 1,
>   'mail_smtphost' => 'smtp.example.com',
>   'mail_smtpport' => '25',
>   'mail_smtpname' => 'cloud@example.com',
>   'mail_smtppassword' => 'Sup3rSecr3tPassw0rd',
>   'mail_smtpsecure'   => '',
>   'mail_smtptimeout' => 30,
> ```
> 
> EDIT: don't use this in your config :
> 
> ```
> 'ssl' => array(
> 'allow_self_signed' => true,
> 'verify_peer' => false,
> 'verify_peer_name' => false
> )
> ```

I changed my congiguration as requested but I still have the same issue.
I try to send email via the command line "sendemail" and it works fine

 sendemail -f support@mydomain.com -t me@mydomain.com -u nextcloud -m "test-prod-nextcloud" -s <IPaddress> -o tls=no
Jan 08 12:19:33 nxtc01 sendemail[405040]: Email was sent successfully!

**Comment by hamzaouichaker** [comment]
root@NXTC01:/var/www/nextcloud# telnet smtp-relay.domain.com 25
Trying 10.0.51.23...
Connected to 10.0.51.23.
Escape character is '^]'.
220 smtp-relay.domain.coml Microsoft ESMTP MAIL Service ready at Mon, 8 Jan 2024 13:00:23 +0100

No, I am not using local host to send email.
Yes, I enabled nextcloud's email debug function but I still not able to see email relevant logs.
Yes, I used the command "/usr/sbin/sendmail" to send email from the Nextcloud VM to my personal inbox using the same configuration of the nextcloud and it worked fine,

**Comment by tzerber** [comment]
> Yes, I enabled nextcloud's email debug function but I still not able to see email relevant logs. 

Your NC is probably not logging debug if you didn't saw errors there. Edit the config file and make sure your lines are like the ones below: 
```php
'mail_smtpdebug' => true,
'loglevel' => 0,
```
Save & restart the webserver that servers NC (mandatory). Go to email settings and fill everything (if not already done) and hit the "Test" button. When it fails, go to the logging page and see / copy the error. Post here the log output.  Once you found out what's giving you issues reset the loglevel to the default (or whatever the original values were on your instance) because leaving debug active can output quite a lot of data and reduce performance. 
```php
'mail_smtpdebug' => false,
'loglevel' => 2,
```
