### ISSUE TITLE
[Bug]: SQL errors when inserting data (Data too long for column 'name')

### ISSUE THREAD

**Issue by nc-fkl** [nextcloud/server#42551]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

An user try to upload file with a big file name, but the SQL column size is too small.
The frontend should already decline the upload of that file.

### Steps to reproduce

1. Select a file with a real long filename ( for example: remote.php/webdav/123/abc-defg-hijklmn/img/qr/SnhJUDAwdDU0WHNEWEloYlZNV2RLTnJEdk9xQUt3Z3NEcEZNUk9SL0V2NVFLamJ1TzdJT2dNMzVrSm5IcGVGWFdXUzI3aDZ1QU84S0NVZno5UTZheUdXZExqenkzMTYrd2xYZWJTczlnSEpqdENXL0hqcGFMVTZNOW5NR3ZlM1poK3ZJQUczYwdesgrdhfghnvcbcxfsefsqzedddcferzfdsdxvfseffdfgfgfgdgggfvcvxdf%3D%3D.jpg )
2. Upload it

### Expected behavior

Frontend should decline the upload wit a info/error popup/message

### Installation method

Other Community project

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment]
cc @nextcloud/files

**Comment by skjnldsv** [comment]
Fixed on master already with https://github.com/nextcloud/server/pull/41346
28 backport in https://github.com/nextcloud/server/pull/42591

and additional improvements with https://github.com/nextcloud/server/pull/42598
