### ISSUE TITLE
[Bug]: ooc files:scan can't be cancelled

### ISSUE THREAD

**Issue by mio-19** [nextcloud/server#42562]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

ooc files:scan can't be cancelled

### Steps to reproduce

1. `docker exec --user www-data -it nextcloud-aio-nextcloud php occ files:scan --all`
2. press Ctrl+C

```
^CError during scan: Invalid callback OCA\Files\Command\Scan::cancelOperation, cannot access protected method OCA\Files\Command\Scan::cancelOperation()
^CError during scan: Invalid callback OCA\Files\Command\Scan::cancelOperation, cannot access protected method OCA\Files\Command\Scan::cancelOperation()
^CError during scan: Invalid callback OCA\Files\Command\Scan::cancelOperation, cannot access protected method OCA\Files\Command\Scan::cancelOperation()
^C^CError during scan: Invalid callback OCA\Files\Command\Scan::cancelOperation, cannot access protected method OCA\Files\Command\Scan::cancelOperation()
^CError during scan: Invalid callback OCA\Files\Command\Scan::cancelOperation, cannot access protected method OCA\Files\Command\Scan::cancelOperation()
^CError during scan: Invalid callback OCA\Files\Command\Scan::cancelOperation, cannot access protected method OCA\Files\Command\Scan::cancelOperation()
^C^C^CError during scan: Invalid callback OCA\Files\Command\Scan::cancelOperation, cannot access protected method OCA\Files\Command\Scan::cancelOperation()
^CError during scan: Invalid callback OCA\Files\Command\Scan::cancelOperation, cannot access protected method OCA\Files\Command\Scan::cancelOperation()
^CError during scan: Invalid callback OCA\Files\Command\Scan::cancelOperation, cannot access protected method OCA\Files\Command\Scan::cancelOperation()
^CError during scan: Invalid callback OCA\Files\Command\Scan::cancelOperation, cannot access protected method OCA\Files\Command\Scan::cancelOperation()
^C^C^C^C^CError during scan: Invalid callback OCA\Files\Command\Scan::cancelOperation, cannot access protected method OCA\Files\Command\Scan::cancelOperation()
```

### Expected behavior

It can be cancelled so that I can run the command in a `screen` instead of unstable bare ssh.

### Installation method

Official All-in-One appliance

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
@kesselb maybe backport https://github.com/nextcloud/server/pull/40067?

**Comment by kesselb** [comment]
I have no opinion about it.

Because of its low impact, I didn't backport it back then.
