### ISSUE TITLE
[Bug]: [stable27] Cannot move/copy files from Groupfolder to the Favorites/Recent tab

### ISSUE THREAD

**Issue by ArtificialOwl** [nextcloud/server#42564]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The popup displayed when copying/moving a file displays some glitchs and infinite loading when:

- the original file is stored in a groupfolder
- the destination folder is `Favorites` or `Recent`.
- 

### Steps to reproduce

0. Install a basic NC27 with the groupfolders app
1. Create a new folder at the root of your files, set it as favorites
2. Create a groupfolder
3. Upload a file in a groupfolder
4. Use the Copy/Move option on this freshly uploaded file
5. Click on the Recent or Favorite tab from the opened popup

### Expected behavior

- A list of favorites/recent folder should be available,
- File should be copied/moved to the selected folder

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

This looks like a pure front-end issue, not available in NC28

**Comment by ostasevych** [comment]
Confirmed at 27.1.5 and 27.1.6 as well. Getting infinite loop when I try to choose a starred folder in destinations.

![image](https://github.com/nextcloud/server/assets/5199030/1047b7a7-8b83-4c0a-ac58-2c020f7e763d)

**Comment by skjnldsv** [comment]
Already handled by https://github.com/nextcloud/server/pull/42994 so this will be fixed in 28.0.2

Please upgrade
