### ISSUE TITLE
[Bug]: Two useless authtoken database queries for every anonymous request

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#42589]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Reading query logs I noticed

```
 primary SELECT * FROM `oc_appconfig`
 replica SELECT * FROM `oc_authtoken` WHERE (`token` = :dcValue1) AND (`version` = :dcValue2)
 replica SELECT * FROM `oc_authtoken` WHERE (`token` = :dcValue1) AND (`version` = :dcValue2)
```

for every anonymous request.

The problem is that `\OC\User\Session::tryTokenLogin` tries to find a token for the current PHP session. `\OC\Authentication\Token\PublicKeyTokenProvider::getToken` does up to two lookups when the instance has an instance secret set. **There will never be a hit**. The only exception would be a hash collision of the new session ID and a previous one.

The solution would be to check if the request had sent a cookie with the instance id as name. Those are used for the PHP session. If there is no cookie, this is a new session, and there won't be a token.

### Steps to reproduce

1.  ``curl https://localhost/login``

### Expected behavior

```
 primary SELECT * FROM `oc_appconfig`
```

### Installation method

None

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
Could this fix it?

https://github.com/nextcloud/server/blob/7502c19ddd43853c3b4fad1e2df91aed19e6b626/lib/private/User/Session.php#L861-L866

```
// Check if the request had sent a cookie with the instance id as name
// If there is no cookie, this is a new session
$instanceId = \OC::$server->getConfig()->getSystemValueString('instanceid');
if (!is_null($request->getCookie($instanceId))) {
	try {
		$dbToken = $this->tokenProvider->getToken($token);
	} catch (InvalidTokenException $e) {
		// Can't really happen but better save than sorry
		return true;
	}
}
```

**Comment by ChristophWurst** [comment]
Yes, something like that should do the trick
