### ISSUE TITLE
[Bug]: NC 28 - uploading files via drag&drop into the browser broken

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/server#42587]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Before NC 28 it was possible to upload a file by dragging it into the file list. Now this not possible any longer. When dragging a file into the view, a box at the top appears which says "Drag and drop files here to upload" but it will close and open all the time and you can not drop the file.

### Steps to reproduce

1. Open the files app
2. Drag a file from a local drive into the browser
3. See the error

### Expected behavior

The box "Drag and drop files here to upload" will appear when dragging a file into the view and will stay visible, so you can actually drop the file to upload.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Screen-Capture which shows the problem:

https://github.com/nextcloud/server/assets/6613614/681ab60f-a4e3-4ea3-b332-d81ee70bf002

**Comment by GeneralTab** [comment]
experiencing the same problem please do let me know if there is any temp fixes.

**Comment by solracsf** [comment]
Maybe fixed by https://github.com/nextcloud/server/pull/42366 ?

**Comment by pjrobertson** [comment]
> Maybe fixed by #42366 ?

Quite likely fixed by this yes.

How can I build a production copy of the `files` app to drop in a replacement? I was hoping to just use that PR `.patch` file but the js needs compiling.

I tried following https://docs.nextcloud.com/server/latest/developer_manual/server/code-front-end.html#building-vue-components-and-scripts but the `dist` folder produced didn't have any usable `files` app.

**Comment by baltaner** [comment]
@pjrobertson
Hi, thank you for your investigation - it seems to work for my installation.
But one question: what do you mean with "... and the same for the other 3 files"?
in the [dist-folder](https://github.com/nextcloud/server/commit/4f3eb7c37e83ae6b09d206106fd13a2459a42da9
) are exactly 3 files. I only copy files-main.js and files-main.js.map
Or did I make a mistake?

**Comment by pjrobertson** [comment]
The third file I was referring to is the LICENSE file which doesn't technically need copying over

**Comment by Jordibgzashtita** [comment]
https://github.com/arnowelzel can you show your apache2 config im using nginx proxymanager and it connet to apache2.... 

nextcloud BAD explained that modules need be installed they name and i could find them: https://docs.nextcloud.com/server/latest/admin_manual/installation/php_configuration.html

SO chatgpt help me install this: sudo apt install -y php php-curl php-cli php-mysql php-gd php-common php-xml php-json php-intl php-pear php-imagick php-dev php-common php-mbstring php-zip php-soap php-bz2 php-bcmath php-gmp php-apcu libmagickcore-dev

after it system show good. but throw much error.... i opened issue but they close it: https://github.com/nextcloud/server/issues/42612

THERE IS BUG in file app in nextcloud.... after web install from stable to beta.... all files that has to be showed WILL DISSAPEARE on recycle there show and on photo they show too.: here is file BUG:

`{"reqId":"ZZtWOgSlYZGrGu4PhMnj3QAAAAI","level":3,"time":"2024-01-08T01:56:10+00:00","remoteAddr":"192.168.0.1","user":"root","app":"no app in context","method":"PUT","url":"/nextcloud/ocs/v2.php/apps/user_status/api/v1/heartbeat?format=json","message":"Exception thrown: Exception","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0","version":"28.0.1.1","exception":{"Exception":"Exception","Message":"Call to a member function getTimestamp() on array in file '/var/www/nextcloud/apps/dav/lib/CalDAV/Status/StatusService.php' line 105","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":65,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":23,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":169,"Previous":{"Exception":"Error","Message":"Call to a member function getTimestamp() on array","Code":0,"Trace":[{"function":"OCA\\DAV\\CalDAV\\Status\\{closure}","class":"OCA\\DAV\\CalDAV\\Status\\StatusService","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/dav/lib/CalDAV/Status/StatusService.php","line":97,"function":"array_filter"},{"file":"/var/www/nextcloud/apps/user_status/lib/Listener/UserLiveStatusListener.php","line":70,"function":"processCalendarStatus","class":"OCA\\DAV\\CalDAV\\Status\\StatusService","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php","line":86,"function":"handle","class":"OCA\\UserStatus\\Listener\\UserLiveStatusListener","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":230,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->"},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":59,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":94,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":106,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/apps/user_status/lib/Controller/HeartbeatController.php","line":100,"function":"dispatchTyped","class":"OC\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":230,"function":"heartbeat","class":"OCA\\UserStatus\\Controller\\HeartbeatController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":137,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":65,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":23,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/lib/CalDAV/Status/StatusService.php","Line":105},"CustomMessage":"Exception thrown: Exception"},"id":"659b56437daf3"}`


I need this nextcloud. by the way phonetrack from some time maybe after foud nextcloud updates start work slow. in past only when show nextcloud phonetrack was showing devices.... now maybe it need wait 1 min. to show devices.... im dissapointent. why they dont make some clean cache.... if i was developer will not permit this.

**Comment by Jordibgzashtita** [comment]
![Untitled](https://github.com/nextcloud/server/assets/149943717/27c38d46-87fb-4d98-8d62-0eef569245cf)

**Comment by arnowelzel** [comment]
> THERE IS BUG in file app in nextcloud.... after web install from stable to beta.... all files that has to be showed WILL DISSAPEARE on recycle there show and on photo they show too.: here is file BUG:

Sorry to hear about your problems - but this has nothing to do with this issue here: file upload using drag & drop in the browser.

Also keep in mind that a **BETA** version is not stable and it can be that there are bugs - that's why it is called "BETA". So of course it is NOT a bug, if there are problems in the BETA version.

Also see here: https://nextcloud.com/de/blog/nextcloud-release-channels-and-how-to-track-them/ - quote: "Beta ... These are suitable to check if bugs are fixed but can break any time."

And about "nextcloud BAD explained": the Nextcloud documentation about the required modules in https://docs.nextcloud.com/server/latest/admin_manual/installation/php_configuration.html is very clear. Of course you have to know how to install PHP modules in your Linux distribution.

**Comment by sugartarou** [comment]
> > Maybe fixed by #42366 ?
> 
> Quite likely fixed by this yes.
> 
> How can I build a production copy of the `files` app to drop in a replacement? I was hoping to just use that PR `.patch` file but the js needs compiling.
> 
> I tried following https://docs.nextcloud.com/server/latest/developer_manual/server/code-front-end.html#building-vue-components-and-scripts but the `dist` folder produced didn't have any usable `files` app.
> 
> **EDIT:** - I realised the `dist` files are all checked in to that PR, so tried copying them over to my production install (`files-main.js*`) but unfortunately that doesn't work
> 
> **EDIT #2** copying the files from stable28 did work:
> 
> ```
> cd /var/www/nextcloud/dist
> sudo wget https://raw.githubusercontent.com/nextcloud/server/4f3eb7c37e83ae6b09d206106fd13a2459a42da9/dist/files-main.js.map
> ... and the same for the other 3 files
> ```

I tried this, and successed.
I got and applied only 2 files (dist/files-main.js and dist/files-main.jp.map).
Thank you.

**Comment by corincorvus** [comment]
Hey, can i replace the file-main files with the 27.1.x version without errors for usable drag and drop?
Or get i other errors, if i do that?

Thanks

**Comment by arnowelzel** [comment]
> Hey, can i replace the file-main files with the 27.1.x version without errors for usable drag and drop?
> Or get i other errors, if i do that?

No, this will not work. NC 28 is a major change to NC 27 - many apps needed to get updated to support NC 28 because of that.

In general: do not replace single files in a production installation with stuff you picked from a Github repository. You can not really know, if that will work or not and you also risk get security problems with untested code.
