### ISSUE TITLE
[BITV]: Replace link with NcButton

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#42596]
Contrast issue, html valid elements issue, `<img alt="">` issue

index.php/u/admin: 

![Screenshot from 2024-01-05 13-39-23](https://github.com/nextcloud/server/assets/6078378/a781f328-3cf4-4260-bbdc-65faba37ec43)

**Comment by szaimen** [comment]
Seems to work in general, but this button looks a bit weird when it is selected via keyboard: 
![image](https://github.com/nextcloud/server/assets/42591237/1643aa44-2d9b-488f-814d-ddfa341df7ff)

Also hover in dark-mode is broken: 
![image](https://github.com/nextcloud/server/assets/42591237/8ea4d7fa-941d-4785-b6bb-2af72db540f4)

**Comment by emoral435** [comment]
That's interesting, I am trying this out on my own local instance, but it looks all fine to me 😕 Can you provide a picture of the settings that you use that give you this weird look to the button?

Heres a gif of me checking it out :
![firefox_YpOAKKGQeN](https://github.com/nextcloud/server/assets/110193237/9bec160f-63f4-43bc-8c1d-673682b396c6)

**Comment by susnux** [comment]
@szaimen could it be that you are testing stable28? In this case we probably need to backport https://github.com/nextcloud/server/pull/42668 ?

**Comment by szaimen** [comment]
> @szaimen could it be that you are testing stable28? In this case we probably need to backport #42668 ?

Yes, always testing with stable28 ;)
