### ISSUE TITLE
[BITV]: Replace "Transfer" button with NcVue button

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#42593]
Contrast issue, html valid elements issue.

Replace `<input data-v-67866491="" type="submit" disabled="disabled" class="primary" value="Transfer">` with NcVue button.

![Screenshot from 2024-01-05 11-21-52](https://github.com/nextcloud/server/assets/6078378/79ff1db2-9c77-453d-97d3-b280ef49c2f8)

**Comment by emoral435** [comment]
Just to know before I submit a PR, I tested replacing the input element with our own NcButton component and kept the logic being the same, however, we still run into the issue of color contrast whenever the button is disabled:
![firefox_4jwPcGfbWy](https://github.com/nextcloud/server/assets/110193237/580e24e6-2024-4e4f-85be-018e67eecea4)
Should we change the contrast between the button when it is disabled? So, should we change the actual component, or should I just add styling to this specific component on this view? @JuliaKirschenheuter

**Comment by JuliaKirschenheuter** [comment]
Dear @emoral435 

If you have replaced `input` with `NcButton` then it is all right. I haven't seen that this button is disabled. Contrasts are not important for disabled elements. You can push your changes without any styling changes.
