### ISSUE TITLE
Rebrand stable9 to Nextcloud

### ISSUE THREAD

**Issue by mar1u5** [nextcloud/server#426]
- [ ] Rebrand README.md 
- [ ] Rebrand issue_template.md

@MorrisJobke Do we have badges (build, ...) for `stable9`?

**Comment by MorrisJobke** [comment]
> @MorrisJobke Do we have badges (build, ...) for stable9?

Not yet. We only have this information per PR and not per branch.

**Comment by MorrisJobke** [comment]
Fix is in #518

**Comment by nickvergessen** [comment]
Merged
