### ISSUE TITLE
Share link (public link) shows loading icon forever

### ISSUE THREAD

**Issue by sroopra** [nextcloud/server#4260]
Using the Share link (public link) seems to create successful the link but the UI shows forever the loading icon.
I have to login and logout (sometimes even restart the webserver) to see the change.
### Steps to reproduce
1. Take any file or directory
2. Go into the Sharing sub-menu
3. Click on Share link

### Expected behaviour
Link is created and can be copied

### Actual behaviour
Loading icon beside Share link which never stops.

### Server configuration

**Operating system**: Linux 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux

**Web server:** nginx version: nginx/1.10.3
built by gcc 4.9.2 (Raspbian 4.9.2-10) 
built with OpenSSL 1.0.2k  26 Jan 2017
TLS SNI support enabled

**Database:** mysql  Ver 14.14 Distrib 5.5.54, for debian-linux-gnu (armv7l) using readline 6.3

**PHP version:** PHP 7.0.16-3 (cli) (built: Feb 22 2017 10:03:06) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.16-3, Copyright (c) 1999-2017, by Zend Technologies

**Nextcloud version:** 11.0.2 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Via updater app within Nextcloud

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - user_external
  - user_ldap
  - user_saml
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oc7p7u3kwlf2",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "dummydomain.at"
        ],
        "datadirectory": "\/media\/sda\/owncloud",
        "overwrite.cli.url": "https:\/\/dummydomain.at\/nextcloud",
        "htaccess.RewriteBase": "\/nextcloud",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "loglevel": 0
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Tried Chrome 57.0.2987.133 (64-bit) and Firefox 52.0.2

**Operating system:** Linux 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"H3EPEsoyhFXAEAFsMtVD","remoteAddr":"192.168.0.1","app":"admin_audit","
message":"The file \"\/DSC_3972.jpg\" with ID \"1108\" has been shared via link 
with permissions \"1\" (Share ID: 24)","level":1,"time":"2017-04-08T19:23:53+02:
00","method":"POST","url":"\/nextcloud\/ocs\/v2.php\/apps\/files_sharing\/api\/v
1\/shares?format=json","user":"nexus","version":"11.0.2.7"}
{"reqId":"Vq3Ce7JiqlhEtjkFzfBa","remoteAddr":"","app":"cli","message":"Memcache 
\\OC\\Memcache\\APCu not available for local cache","level":1,"time":"2017-04-08
T19:30:01+02:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"Vq3Ce7JiqlhEtjkFzfBa","remoteAddr":"","app":"cli","message":"Memcache 
\\OC\\Memcache\\APCu not available for distributed cache","level":1,"time":"2017
-04-08T19:30:01+02:00","method":"--","url":"--","user":"--","version":"11.0.2.7"
}
```
</details>

**Comment by MorrisJobke** [comment]
Any errors in the browsers log in the web developers tools?

**Comment by sroopra** [comment]
Hi,
No Browser log in Chrome shows the following:
jquery-migrate.min.js?v=e96eacc…:2 JQMIGRATE: Migrate is installed, version 1.4.0
3js.js?v=e96eacc…:2139 Deprecation warning: tipsy is deprecated. Use tooltip instead.
jQuery.fn.tipsy @ js.js?v=e96eacc…:2139
DevTools failed to parse SourceMap: https://dummydomain.at/nextcloud/core/vendor/jquery/dist/jquery.min.map

That is it also the Network tab is fine:
I get a Response 200 from the following request:
https://dummydomain.at/nextcloud/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json&path=%2FBosnien_Kroatien_Montenegro%2FDSC_3972.jpg&reshares=true

**Comment by sroopra** [comment]
It could also be related to some hardening I was trying to do on the server. The problem is I can not figure out anymore what caused the issue. Update of Nextcloud, making MySQL skip-networking, moving the www root folder to a separate partition with (defaults,nosuid,noexec,nodev).
Also I updated nginx and PHP to version 7. All the time the Nextcloud was working but I never tried that feature :(. If you can point me to the code where this is happening I can also have a look :) thx.

**Comment by MorrisJobke** [comment]
> That is it also the Network tab is fine:
> I get a Response 200 from the following request:
> https://dummydomain.at/nextcloud/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json&path=%2FBosnien_Kroatien_Montenegro%2FDSC_3972.jpg&reshares=true

Then all should be fine.

@sroopra Does it work now properly for you? I would close this ticket then.

**Comment by sroopra** [comment]
No still does not work :(
Updated to 12.0.3. I am still using the Set strong permissions script but that seems to be outdated at least I can not find it in the documentation, maybe that can cause a problem?
So far I had no time to dig deeper into the problem.
Right now as a workaround I can do a logout and then a login and then the UI shows the correct update when I go back to the share "tab".
