### ISSUE TITLE
[Bug]: Downloading multiple files or folder from webgui does not work

### ISSUE THREAD

**Issue by Bastilms** [nextcloud/server#42617]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When you download a folder or multiple files, it tries to download a HTML file ("download.php.html")
The File contains the following line.
`Fatal error: Uncaught Error: Class "OC_Util" not found in /var/www/html/apps/files/ajax/download.php:31 Stack trace: #0 {main} thrown in /var/www/html/apps/files/ajax/download.php on line 31`

Single Files work as expected.

### Steps to reproduce

1. Login
2. Select multiple Files or a folder
3. Click Download

### Expected behavior

a ZIP file should be generated

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "DE",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "overwriteprotocol": "https",
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "28.0.1.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "radio",
            "checksum"
        ],
        "loglevel": 2,
        "maintenance": false
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - audioplayer: 3.4.1
  - camerarawpreviews: 0.8.4
  - checksum: 1.2.2
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_fulltextsearch: 28.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - fulltextsearch: 28.0.0
  - fulltextsearch_elasticsearch: 28.0.0
  - groupfolders: 16.0.1
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - quota_warning: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_email: 2.7.4
  - twofactor_webauthn: 1.3.2
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - cfg_share_links: 4.2.0 (installed 4.2.0)
  - circles: 28.0.0-dev (installed 27.0.1)
  - dashboard: 7.8.0 (installed 7.7.0)
  - encryption: 2.16.0
  - extract: 1.3.6 (installed 1.3.6)
  - files_3dmodelviewer: 0.0.12 (installed 0.0.12)
  - files_automatedtagging: 1.18.0 (installed 1.18.0)
  - files_external: 1.20.0
  - files_fulltextsearch_tesseract: 27.0.0 (installed 27.0.0)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - imageconverter: 1.3.5 (installed 1.3.5)
  - metadata: 0.19.0 (installed 0.19.0)
  - openotp_auth: 1.5.1 (installed 1.5.1)
  - radio: 1.0.3 (installed 1.0.3)
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0
  - weather_status: 1.8.0 (installed 1.8.0)
  - workflow_ocr: 1.28.0 (installed 1.28.0)
  - workflow_pdf_converter: 1.13.0 (installed 1.13.0)
  - workflow_script: 1.13.0 (installed 1.13.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
- Nothing in this time
```

### Additional info

Seems to be the same issue as in #42470 but with the official Image.

**Comment by joshtrichards** [comment]
Are you using Docker bind mount(s) or named volume(s)?

Please provide your Compose file to ease reproducibility. Also, particularly if using bind mounts, please check the permissions (and ownership) of files in host and in-container are reasonable.

Is this a new installation or an upgraded one?

**Comment by Bastilms** [comment]
I'm using bind mounts for this. The issue occurred after an update from 28.0 to 28.0.1.
There shouldn't be a permission issue because it worked before, and I manually adjusted them to 777 just in case for testing. 

```
version: '3.3'
services:
  nextcloud:
    image: nextcloud:28.0.1-fpm
    container_name: nextcloud
    restart: unless-stopped
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - PHP_MEMORY_LIMIT=1G
      - PHP_UPLOAD_LIMIT=10G
    env_file:
      - config/db.env
    depends_on:
      - db
      - redis
    volumes:
      - ./app/:/var/www/html/
      - ./config/www.conf:/usr/local/etc/php-fpm.d/www.conf

  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./database:/var/lib/postgresql/data:Z
    env_file:
      - config/db.env

  nextcloud_web:
    image: nginx:1.21-alpine
    container_name: nextcloud_web
    restart: unless-stopped
    ports:
      - 8080:80
    links:
      - nextcloud
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app:/var/www/html:ro

  elasticsearch:
    image: aaronriedel/elasticsearch
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=
      - ELASTIC_PASSWORD=
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  redis:
    container_name: nextcloud_redis
    image: redis:alpine
    volumes:
      - ./redis_data:/data:rw
    restart: unless-stopped
```

**Comment by joshtrichards** [comment]
I'm 99% confident the underlying cause is a missing line in your web (nginx.conf) configuration. Specifically you're likely missing the rewrite line for handling `ajax` and other URLs:

https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html

Search for "ajax" on that page and compare your config.

Or, alternatively, these lines:

https://github.com/nextcloud/docker/blob/8afd97014cc3445e888a165f8c2d16af7ed036aa/.examples/docker-compose/insecure/mariadb/fpm/web/nginx.conf#L142-L143

**Comment by Bastilms** [comment]
Solved. Thanks

Not sure why it worked before.

**Comment by kunago** [comment]
I am not using Nginx, have been using Caddy as a proxy. I have been running a docker version of fpm-alpine. Never did anything to my configs and there is not much to be set in Caddy to make NC work, yet it stopped working.

For those that did nothing with their configs and it does not work, you can try to use a dirty hack for now fixing the download for you by adding these lines at the top of download.php:

```
$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));
include_once $baseDir . '/lib/base.php';
include_once $baseDir . '/lib/private/legacy/OC_Util.php';
```

This bug is not nginx specific.

**Comment by joshtrichards** [comment]
@kunago

> This bug is not nginx specific.

1) It's not a bug, but a configuration issue.
2) No, it's not nginx specific; any web server can be configured incorrectly

> I am not using Nginx, have been using Caddy as a proxy. I have been running a docker version of fpm-alpine. Never did anything to my configs and there is not much to be set in Caddy to make NC work, yet it stopped working.

If you're using Caddy with FPM, then Caddy is operating as both a proxy and your web server. That means you have a more extensive Caddyfile than merely a few proxy lines. If you don't, then you either:

a) have a web server elsewhere in front of FPM in between Caddy and FPM (look there for the configuration problem)
b) have an incomplete Caddyfile configuration for Nextcloud (which is causing this situation for you; does your Caddy file have rewrite rules equivalent to the ones noted for nginx above? If not, it's exactly the same underlying cause as nginx).

In either case, it's still a web configuration issue somewhere in your environment. Caddy is not immune to needing a valid configuration, keeping it up-to-date with changes noted in the Admin Manual for difference releases of NC, etc.

I know you're just trying to get the word out, but you've posted across at least three different issues I'm on regarding this topic. Maybe oncee you get it resolved you can post the solution, but a better place for this discussion is the Nextcloud Help Forum - https://help.nextcloud.com. Discussions here consume developer time and this isn't meant as a general support channel. :)

**Comment by kunago** [comment]
@joshtrichards , I posted in the hope it would help someone with the issue, at least temporarily, if it was needed. I was in an urgent need to fix it for now and can play with it later, so that's the reason for the post. Yes, I cross-posted, sorry for that.

It was not meant to be a time-waster for anyone. This is not a general purpose topic hence no need to mark my comment that way. Such replies however might put away others from any further involvement, be it on topic but not in the professional developer way. Just my two cents.

**Comment by tschettervictor** [comment]
Can you give this block a try? Uploading of multiple files seems to still be broken, but this looks like it fixes the download.

```
@notlegacy {
                not path /index.php*
                not path /remote.php*
                not path /public.php*
                not path /cron.php*
                not path /core/ajax/update.php*
                not path /status.php*
                not path /ocs/v1.php*
                not path /ocs/v2.php*
                not path /ocs-provider/*.php*
                not path /updater/*.php*
                not path */richdocumentscode/proxy.php*
        }
        rewrite @notlegacy /index.php{uri}
```

**Comment by tschettervictor** [comment]
> I am not using Nginx, have been using Caddy as a proxy. I have been running a docker version of fpm-alpine. Never did anything to my configs and there is not much to be set in Caddy to make NC work, yet it stopped working.
> 
> For those that did nothing with their configs and it does not work, you can try to use a dirty hack for now fixing the download for you by adding these lines at the top of download.php:
> 
> ```
> $vendorDir = dirname(__DIR__);
> $baseDir = dirname(dirname($vendorDir));
> include_once $baseDir . '/lib/base.php';
> include_once $baseDir . '/lib/private/legacy/OC_Util.php';
> ```
> 
> This bug is not nginx specific.

Link to a potential working Caddyfile.
[here](https://caddy.community/t/translate-nginx-rewrite-rule-for-nextcloud/22956/14)

**Comment by Hoeze** [comment]
Hi, I am also facing the same issue, but my reverse proxy configuration looks much simpler:
```
    location /nextcloud/ {
        set $upstream_host 127.0.0.1;
        set $upstream_port 8001;
        set $upstream_proto http;

        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        add_header Front-End-Https on;
        
        proxy_pass $upstream_proto://$upstream_host:$upstream_port;

        rewrite /nextcloud(.*)$ $1 break;
    }
```

Could you please give me a tip how to my rewrite rule?

**Comment by joshtrichards** [comment]
@Hoeze Check your web server config, not reverse proxy config. See https://github.com/nextcloud/server/issues/42617#issuecomment-1881958718

**Comment by Hoeze** [comment]
Thanks @joshtrichards, I think I am mistaken, and this is not exactly my issue.
The official docker image is using apache2 instead of nginx.

**Comment by gruffatremi** [comment]
> > I am not using Nginx, have been using Caddy as a proxy. I have been running a docker version of fpm-alpine. Never did anything to my configs and there is not much to be set in Caddy to make NC work, yet it stopped working.
> > For those that did nothing with their configs and it does not work, you can try to use a dirty hack for now fixing the download for you by adding these lines at the top of download.php:
> > ```
> > $vendorDir = dirname(__DIR__);
> > $baseDir = dirname(dirname($vendorDir));
> > include_once $baseDir . '/lib/base.php';
> > include_once $baseDir . '/lib/private/legacy/OC_Util.php';
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This bug is not nginx specific.
> 
> Link to a working Caddyfile rewrite rule [caddy.community](https://caddy.community/t/translate-nginx-rewrite-rule-for-nextcloud/22956/14)
> 
> ```
>         # required for legacy support
>         @notlegacy {
>                 path *.php *.php/
>                 not path_regexp ^/(index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+|.+/richdocumentscode(_arm64)?/proxy)
>         }
>         rewrite @notlegacy /index.php{uri}
> ```

I have caddy aswell and it fixed it for me ! 

Thanks I can go sleep early tonight :)
