### ISSUE TITLE
Very Slow login fresh installation 11.0.2

### ISSUE THREAD

**Issue by jorgensoares** [nextcloud/server#4261]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Fast login < 3s

### Actual behaviour
Login taking  ~ 16s-18s

### Server configuration

**Operating system**:
Debian 8

**Web server:**
apache 2.4.10-10+deb8u8 amd64

**Database:**
mysql 5.6

**PHP version:**
php 5.6.30+dfsg-0+deb8u1

**Nextcloud version:** (see Nextcloud admin page)
11.0.2 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
nextcloud sources

**Signing status:**

No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - activitylog: 0.0.1
  - admin_audit: 1.1.0
  - admin_notifications: 1.0.0
  - announcementcenter: 3.0.0
  - apporder: 0.3.3
  - audioplayer: 1.5.1
  - bookmarks: 0.9.1
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - deck: 0.1.2
  - external: true
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - gallery: 16.0.0
  - keeweb: 0.3.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.2
  - news: 10.1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - survey_client: 0.1.5
  - tasks: 0.9.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.2
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - firstrunwizard
  - nextcloud_announcements
  - systemtags
  - user_external
  - user_saml

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "ocy5kh9lmr2r",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.14.10.30",
            "mydomain.com",
            "wwwmydomain.com",
            "10.14.10.10"
        ],
        "datadirectory": "\/ocdata",
        "overwrite.cli.url": "https:\/\/www.mydomain.com",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "nextcloud",
        "dbhost": "10.14.10.10",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_from_address": "noreply",
        "mail_smtpmode": "php",
        "mail_domain": "mydoamin.com",
        "loglevel": 0,
        "logfile": "\/shares\/misc\/logs\/nextcloud.log",
        "lost_password_link": "https:\/\/pass.mydomain.com",
        "maintenance": false,
        "auth.bruteforce.protection.enabled": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.4.1",
            "types": "filesystem"
        },
        "activitylog": {
            "enabled": "yes",
            "installed_version": "0.0.1",
            "types": ""
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "logging"
        },
        "admin_notifications": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "logging"
        },
        "announcementcenter": {
            "enabled": "yes",
            "installed_version": "3.0.0",
            "types": "logging"
        },
        "apporder": {
            "enabled": "yes",
            "installed_version": "0.3.3",
            "types": ""
        },
        "audioplayer": {
            "enabled": "yes",
            "installed_version": "1.5.1",
            "ocsid": "174738",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "20"
        },
        "bookmarks": {
            "enabled": "yes",
            "installed_version": "0.9.1",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.5.2",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "1.5.3",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installedat": "1491657049.843",
            "lastcron": "1491684305",
            "lastupdateResult": "[]",
            "lastupdatedat": "1491684295",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "vendor": "nextcloud"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        },
        "deck": {
            "enabled": "yes",
            "installed_version": "0.1.2",
            "types": ""
        },
        "external": {
            "enabled": "yes",
            "installed_version": "",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.6.1",
            "types": "filesystem"
        },
        "files_accesscontrol": {
            "enabled": "yes",
            "installed_version": "1.1.2",
            "types": "filesystem"
        },
        "files_automatedtagging": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "yes",
            "installed_version": "1.1.2",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_retention": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "filesystem"
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.2",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "no",
            "installed_version": "2.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "16.0.0",
            "types": ""
        },
        "keeweb": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "levels": "11111",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "yes",
            "installed_version": "0.6.2",
            "types": ""
        },
        "news": {
            "enabled": "yes",
            "installed_version": "10.1.0",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "no",
            "installed_version": "1.0",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "2.2.0",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "logging"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "prevent_group_restriction"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "prevent_group_restriction"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "0.1.5",
            "types": ""
        },
        "systemtags": {
            "enabled": "no",
            "installed_version": "1.1.3",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.9.5",
            "types": ""
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": ""
        },
        "theming": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "user_ldap": {
            "cleanUpJobOffset": "0",
            "enabled": "yes",
            "installed_version": "1.1.2",
            "s01has_memberof_filter_support": "1",
            "s01home_folder_naming_rule": "",
            "s01last_jpegPhoto_lookup": "0",
            "s01ldap_agent_password": "*********************",
            "s01ldap_attributes_for_group_search": "",
            "s01ldap_attributes_for_user_search": "",
            "s01ldap_backup_host": "",
            "s01ldap_backup_port": "",
            "s01ldap_base": "***************",
            "s01ldap_base_groups": "*********************",
            "s01ldap_base_users": "****************************",
            "s01ldap_cache_ttl": "600",
            "s01ldap_configuration_active": "1",
            "s01ldap_display_name": "displayName",
            "s01ldap_dn": "**************",
            "s01ldap_dynamic_group_member_url": "",
            "s01ldap_email_attr": "userPrincipalName",
            "s01ldap_experienced_admin": "0",
            "s01ldap_expert_username_attr": "",
            "s01ldap_expert_uuid_group_attr": "",
            "s01ldap_expert_uuid_user_attr": "",
            "s01ldap_group_display_name": "cn",
            "s01ldap_group_filter": "(&(|(objectclass=group)(objectclass=top)))",
            "s01ldap_group_filter_mode": "1",
            "s01ldap_group_member_assoc_attribute": "member",
            "s01ldap_groupfilter_groups": "",
            "s01ldap_groupfilter_objectclass": "group\ntop",
            "s01ldap_host": "ldaps:\/\/mydoamin.com",
            "s01ldap_login_filter": "(&(&(|(objectclass=person)))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))",
            "s01ldap_login_filter_mode": "0",
            "s01ldap_loginfilter_attributes": "",
            "s01ldap_loginfilter_email": "1",
            "s01ldap_loginfilter_username": "1",
            "s01ldap_nested_groups": "0",
            "s01ldap_override_main_server": "",
            "s01ldap_paging_size": "500",
            "s01ldap_port": "636",
            "s01ldap_quota_attr": "",
            "s01ldap_quota_def": "",
            "s01ldap_tls": "0",
            "s01ldap_turn_off_cert_check": "1",
            "s01ldap_turn_on_pwd_change": "1",
            "s01ldap_user_display_name_2": "samaccountname",
            "s01ldap_user_filter_mode": "1",
            "s01ldap_userfilter_groups": "",
            "s01ldap_userfilter_objectclass": "person",
            "s01ldap_userlist_filter": "(&(|(objectclass=person)))",
            "s01use_memberof_to_detect_membership": "1",
            "types": "authentication"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "filesystem"
        }
    }
}
ro

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
+-------------------------------+----------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                          |
+-------------------------------+----------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                            |
| hasPagedResultSupport         |                                                                                              |
| homeFolderNamingRule          |                                                                                              |
| lastJpegPhotoLookup           | 0                                                                                            |
| ldapAgentName                 | DOMAIN\MAIL$                                                                                 |
| ldapAgentPassword             | ***                                                                                          |
| ldapAttributesForGroupSearch  |                                                                                              |
| ldapAttributesForUserSearch   |                                                                                              |
| ldapBackupHost                |                                                                                              |
| ldapBackupPort                |                                                                                              |
| ldapBase                      | dc=oxx,dc=zz                                                                              |
| ldapBaseGroups                | CN=xxxx,DC=xxxx,DC=xx                                                                 |
| ldapBaseUsers                 |  CN=xxxx,DC=xxxx,DC=xx                                                                    |
| ldapCacheTTL                  | 600                                                                                          |
| ldapConfigurationActive       | 1                                                                                            |
| ldapDynamicGroupMemberURL     |                                                                                              |
| ldapEmailAttribute            | userPrincipalName                                                                            |
| ldapExperiencedAdmin          | 0                                                                                            |
| ldapExpertUUIDGroupAttr       |                                                                                              |
| ldapExpertUUIDUserAttr        |                                                                                              |
| ldapExpertUsernameAttr        |                                                                                              |
| ldapGroupDisplayName          | cn                                                                                           |
| ldapGroupFilter               | (&(|(objectclass=group)(objectclass=top)))                                                   |
| ldapGroupFilterGroups         |                                                                                              |
| ldapGroupFilterMode           | 1                                                                                            |
| ldapGroupFilterObjectclass    | group;top                                                                                    |
| ldapGroupMemberAssocAttr      | member                                                                                       |
| ldapHost                      | ldaps://mydomain.com                                                                            |
| ldapIgnoreNamingRules         |                                                                                              |
| ldapLoginFilter               | (&(&(|(objectclass=person)))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                              |
| ldapLoginFilterEmail          | 1                                                                                            |
| ldapLoginFilterMode           | 0                                                                                            |
| ldapLoginFilterUsername       | 1                                                                                            |
| ldapNestedGroups              | 0                                                                                            |
| ldapOverrideMainServer        |                                                                                              |
| ldapPagingSize                | 500                                                                                          |
| ldapPort                      | 636                                                                                          |
| ldapQuotaAttribute            |                                                                                              |
| ldapQuotaDefault              |                                                                                              |
| ldapTLS                       | 0                                                                                            |
| ldapUserDisplayName           | displayName                                                                                  |
| ldapUserDisplayName2          | samaccountname                                                                               |
| ldapUserFilter                | (&(|(objectclass=person)))                                                                   |
| ldapUserFilterGroups          |                                                                                              |
| ldapUserFilterMode            | 1                                                                                            |
| ldapUserFilterObjectclass     | person                                                                                       |
| ldapUuidGroupAttribute        | auto                                                                                         |
| ldapUuidUserAttribute         | auto                                                                                         |
| turnOffCertCheck              | 1                                                                                            |
| turnOnPasswordChange          | 1                                                                                            |
| useMemberOfToDetectMembership | 1                                                                                            |
+-------------------------------+----------------------------------------------------------------------------------------------+

### Client configuration
Google Chrome
Mozzila

**Operating system:**
Mac OS

#### Web server error log
No error in log

#### Nextcloud log (data/nextcloud.log)
No error in log

**Comment by MorrisJobke** [comment]
Do you have a proxy in front of your webserver? If so this is very likely a problem with the client IP forwarding in the proxy and triggers the bruteforce detection. To quickly verify turn it off with the config.php setting https://github.com/nextcloud/server/blob/master/config/config.sample.php#L228

If then the login is fast, try to properly configure the proxy: https://docs.nextcloud.com/server/12/admin_manual/configuration_server/reverse_proxy_configuration.html - see forwarded_for_headers
