### ISSUE TITLE
security.txt should end with a newline

### ISSUE THREAD

**Issue by BartG95** [nextcloud/server#42611]
https://github.com/nextcloud/server/blob/9416778ed2e21e961d1a0c5222f718c545138671/apps/settings/lib/WellKnown/SecurityTxtHandler.php#L45

Or at least, according to sectxt: https://github.com/DigitalTrustCenter/sectxt/blob/27d8524ca215d4663539a218e048023da07172f8/sectxt/__init__.py#L308-L315

The grammar in the official standard seems to indicate the same: https://www.rfc-editor.org/rfc/rfc9116#name-file-format-description-and

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/.github/blob/master/SECURITY.md

**Comment by ChristophWurst** [comment]
Sure

**Comment by lovelgeorge99** [comment]
![image](https://github.com/nextcloud/server/assets/36924734/f47751a5-1469-466a-ae4f-710c44d686b1)

is that what it is asking to do?
