### ISSUE TITLE
Addressbook can not be created

### ISSUE THREAD

**Issue by lepidas** [nextcloud/server#4262]
### Steps to reproduce
1. >Contacts>Settings>
2. type addressbook name>hit enter>refresh page
3.

### Expected behaviour
new addressbook should be created

### Actual behaviour
no new addressbook is created

### Server configuration

ubuntu 16.04

apache

mysql

php7

NC 11

updated from 10

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
cc @georgehrke

**Comment by MorrisJobke** [comment]
@lepidas Any special characters in the address book name or spaces or slashes?

**Comment by lepidas** [comment]
no special characters.
I wonder if that the root of the NC installation is a problem with that
/var/www/nextcloud/html

apache error logs 0
NC logs
`Fatal	
webdav	
Sabre\DAV\Exception\MethodNotAllowed: HTTP/1.1 405 The resource you tried to create already exists

    /var/www/nextcloud/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 590: Sabre\DAV\Server->createCollection('addressbooks/us...', Object(Sabre\DAV\MkCol))
    [internal function] Sabre\DAV\CorePlugin->httpMkcol(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method MKCOL', Array)
    /var/www/nextcloud/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/html/apps/dav/lib/Server.php - line 227: Sabre\DAV\Server->exec()
    /var/www/nextcloud/html/apps/dav/appinfo/v2/remote.php - line 30: OCA\DAV\Server->exec()
    /var/www/nextcloud/html/remote.php - line 165: require_once('/var/www/nextcl...')
    {main}`

**Comment by georgehrke** [comment]
> The resource you tried to create already exists

Are you trying to create an address book with a name, that already exists?

**Comment by lepidas** [comment]
No but....I was trying to create a new with the same name an address book couldn't be created.
reproducing:
create  address book name: "sync"
never was created name: "sync" but I can see it on Settings gear with it's options (share,delete,etc)
delete address book name: "sync"
create  address book name: "sync"
![screenshot from 2017-04-10 09-00-46](https://cloud.githubusercontent.com/assets/5602763/24849508/6e785cbc-1dcc-11e7-9e8d-28bf02def5a8.png)

**Comment by georgehrke** [comment]
> but I can see it on Settings gear with it's options (share,delete,etc)

Well, but if you see it in settings, it was created just fine

**Comment by lepidas** [comment]
In Settings it's there but to say that is created must be usable and under there like I have with "Customers", otherwise maybe I have problem understanding how to work with it. Not sure yet...

![screenshot from 2017-04-10 09-00-46](https://cloud.githubusercontent.com/assets/5602763/24852138/aa557b70-1dd6-11e7-8db5-0290939b059a.png)

**Comment by georgehrke** [comment]
Customers is a group, not an address book

**Comment by lepidas** [comment]
False alarm. Sorry for your time.
