### ISSUE TITLE
App from App generator is not visible if description contains Special Chars (Umlauts)

### ISSUE THREAD

**Issue by jonnsn** [nextcloud/server#4263]
### Steps to reproduce
1. Go to https://apps.nextcloud.com/developer/apps/generate
2. Enter the fields and use some special Characters (e.g. German Umlauts ä ö ü) in the description field
3. Copy the app to your installation /apps/myapp

### Expected behaviour
The app should be visible in the app list http://myserver.tld/index.php/settings/apps

### Actual behaviour
The app is not visible and thus cannot be activated. If you change the description in the generator to something without special Characters, download the app again and replace it in your installation the app shows up. I tried to edit appinfo/info.xml and removed the characters there, but the app was still not visible, so I suppose the description is used somehwere else too.

### Server configuration

**Operating system**: Debian

**Web server:** Apache 2.4

**Database:** MySQL5.5

**PHP version:** 7.1

**Nextcloud version:** 11

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** github download

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - calendar
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - firstrunwizard
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oczty6g0f2jo",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "somedomain.tld"
        ],
        "datadirectory": "\/var\/www\/myPrivatePath\/data",
        "overwrite.cli.url": "http:\/\/somedomain.tld",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "my_db_name",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "info",
        "mail_smtpmode": "php",
        "mail_domain": "somedomain.tld",
        "skeletondirectory": "\/var\/www\/myPrivatePath\/skeletondirectory\/",
        "defaultapp": "gallery",
        "default_language": "de"
    }
}
```
</details>

**Are you using external storage, if yes which one:** none

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:** FF 52

**Operating system:** Win10

#### Web server error log
<details>
<summary>Web server error log</summary>
nothing relevant
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
empty
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
nothing relevant
```
</details>

**Comment by MorrisJobke** [comment]
Please reopen in the App Store issue tracker: https://github.com/nextcloud/appstore/issues
