### ISSUE TITLE
[BITV]: Contrast of the "Change color" is not enough

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#42631]
When "Default background" is checked a per-defined "Change color" button have not enough contrast. The color of the text have to be dark and not light.

Probably related to https://github.com/nextcloud/server/issues/42620

![Screenshot from 2024-01-08 15-20-10](https://github.com/nextcloud/server/assets/6078378/02bf719f-ddde-4d6f-bbcf-d02fb7fecb67)

**Comment by szaimen** [comment]
See https://github.com/nextcloud/server/pull/42552

**Comment by szaimen** [comment]
Changed to close as not planned
