### ISSUE TITLE
[BITV] The user status icons do not meet the contrast requirements (3:1) for informative graphics

### ISSUE THREAD

**Issue by Pytal** [nextcloud/server#42644]
![image](https://github.com/nextcloud/server/assets/24800714/786b48c6-f1a8-42ef-ae28-1f0800ff8445)

**Comment by Pytal** [comment]
Needs to be fixed on server and text

**Comment by JuliaKirschenheuter** [comment]
Please don't forget: 

- [ ] In "Edit widgets" for dashboard: 
![Screenshot from 2024-01-10 17-31-29](https://github.com/nextcloud/server/assets/6078378/be1db442-ba8e-4569-87f4-983ea1f31f45)

- [ ] (nice to have) for right menu item:
![Screenshot from 2024-01-10 17-33-39](https://github.com/nextcloud/server/assets/6078378/23183f78-b499-46ef-8172-3f36e90a5ecb)
