### ISSUE TITLE
Issue when updating using built in updater on my pi

### ISSUE THREAD

**Issue by JunkyardCat** [nextcloud/server#4268]
I got this when i update using the built in updater. im using a raspberry pi

not sure if this will help but on my initial install ive changed the data directory to 'datadirectory' => '/var/nextcloud/data', for security purpose

The following places can not be written to:

    /var/www/html/nextcloud/updater/../cron.php
    /var/www/html/nextcloud/updater/../public.php
    /var/www/html/nextcloud/updater/../status.php
    /var/www/html/nextcloud/updater/../.user.ini
    /var/www/html/nextcloud/updater/../apps/templateeditor/templates/settings-admin.php
    /var/www/html/nextcloud/updater/../apps/templateeditor/templates/.

**Comment by MorrisJobke** [comment]
> The following places can not be written to:

@JunkyardCat Give the web server user permissions for those files and the updater should work then.
