### ISSUE TITLE
[BITV]: Increase contrast on dot for status button

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#42687]
- [ ] In "Edit widgets" for dashboard: 
![Screenshot from 2024-01-10 17-31-29](https://github.com/nextcloud/server/assets/6078378/be1db442-ba8e-4569-87f4-983ea1f31f45)

- [ ] (nice to have) for right menu item:
![Screenshot from 2024-01-10 17-33-39](https://github.com/nextcloud/server/assets/6078378/23183f78-b499-46ef-8172-3f36e90a5ecb)

Same issue was already resolved: https://github.com/nextcloud/server/issues/41856

**Comment by Pytal** [comment]
Dupe https://github.com/nextcloud/server/issues/42644
