### ISSUE TITLE
Notification for Emails - Plain Text to HTML

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/server#4270]
How can we send notification emails in HTML format? Application available for this but not functional and is not working well.

How can I convert plain text to HTML Format?

cc @MorrisJobke

**Comment by MorrisJobke** [comment]
See https://github.com/nextcloud/server/blob/ba87db3fccb40aa58d84d12932424c83a4db411f/lib/public/Mail/IMailer.php#L34-L41

**Comment by MorrisJobke** [comment]
We are currently working on making email templates a bit easier to automatically include theming, This is not yet done, but you can see how it works in https://github.com/nextcloud/server/blob/5b4adf66e51e21b3ecbd683397a362b60f792a50/settings/Mailer/NewUserMailHelper.php#L118-L144

keep in mind that this is still in the private namespace and can change it's API.
