### ISSUE TITLE
[Bug]: Some Office documents are not automatically opened with Only Office in the browser, but can only be downloaded. 

### ISSUE THREAD

**Issue by molsondry** [nextcloud/server#42701]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Some Office documents are not automatically opened with Only Office in the browser, but can only be downloaded. This applies to all Office files whose file extension is NOT in lower case. If you change the file extension to lower case, the assignment to the application works again.

### Steps to reproduce

1.Have a nextcloud service with Only Office included
2.Configure Only Office App as the standard for opening xlsx files
3.Try and open files with file extension either .xlsx or .XLSX . First situation works, in the second place downloading the file only will be offered by nextcloud

### Expected behavior

Officefiles are going to be opened by any character capitalization of the file extension

### Installation method

Community VM appliance

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
not available
```

### List of activated Apps

```shell
not available
```

### Nextcloud Signing status

```shell
not available
```

### Nextcloud Logs

```shell
not available
```

### Additional info

not available

**Comment by solracsf** [comment]
Maybe this should be reported to https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/issues/41551

**Comment by molsondry** [comment]
@skjnldsv : I think it is not a duplicate of #41551 The behaviors are different in description. This bug here is deterministic. Use small letters for the file extension: application opens, use capital letters: application does not open and download starts instead. The reported behavior in #41551 concerning empty folders does not happen here.

**Comment by skjnldsv** [comment]
@molsondry the othe rissue is a bit weird, because it covers two different topics.
To double check, if you hover the filename, what does it say for you?
Does one say `View document.xlsx` and the other `Download document.xslx` or something.

This bug is very random and unreliable, what you found with the lowercase or uppercase might not be what you think it is (double checking, I might also be wrong :wink:)

**Comment by molsondry** [comment]
@skjnldsv Please look at these screenshots with one capital letter (can be more as well) in the file extension, Nextcloud is about to download (herunterladen in German) 
<img width="479" alt="image" src="https://github.com/nextcloud/server/assets/5124936/8f409da9-e901-487f-8468-15037e5c3b07">
And here the second file name with small letters only, Nextcloud is about to open OnlyOffice: 
<img width="404" alt="image" src="https://github.com/nextcloud/server/assets/5124936/5a19c31b-cdc3-476f-9d23-ddcfbf3aee19">

**Comment by skjnldsv** [comment]
@juliushaertl would the mimetype detection fail with improper casing?

**Comment by molsondry** [comment]
@juliushaertl possibly the mime type. Anyway you may configure the Onlyoffice App with accepted file extensions when to open the app. In this configuration only small letters are offered to check. 
![image](https://github.com/nextcloud/server/assets/5124936/60436649-b0b4-42cc-ac9c-0ceae0667285)
The behavior definitely changed with update to 28. We tested an old version 27, where Onlyoffice starts with any capitalization of the file name extension.

**Comment by juliushaertl** [comment]
Onlyoffice needed to adapt to the new files API so probably that is where this broke, however it seems to be a bug in https://github.com/ONLYOFFICE/onlyoffice-nextcloud so I'd kindly ask you to file a report over there.

Relevant code part that seems to not match with different casing: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/v9.0.0/src/main.js#L508
