### ISSUE TITLE
[BITV]: Replace entries of action menu for contacts inside of contacts menu

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#42708]
Currently there are entries with images and text. This images are `<img>` without any alternative text.

![Screenshot from 2024-01-11 14-17-30](https://github.com/nextcloud/server/assets/6078378/30632e6b-eee4-482a-a11f-e02f6ba151aa)

Images are not important in this part and we can replace them with `NcActionText`, like:

```
<NcActionText>
<template #icon>
	<Icon :size="20" />
</template>
{{ t('...', 'local time') }}
</NcActionText>						
```

**Comment by ChristophWurst** [comment]
We can't change the img to an svg icon here because the data is provided through a stable API: https://github.com/nextcloud/server/blob/d128b4a04b1d81881e19b93f8a3dd37b729ab91a/lib/public/Contacts/ContactsMenu/IAction.php#L33-L37

Can the img be marked as decorative?

**Comment by JuliaKirschenheuter** [comment]
> Can the img be marked as decorative?

yes, please add `aria-hidden="true"` to each `<img>`
