### ISSUE TITLE
[Bug]: Problems renaming folders on local drives (external) 

### ISSUE THREAD

**Issue by wmeneses** [nextcloud/server#42731]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I have added a local drive (Linux XFS) because on S3 (Compatible)(external) renaming a folder is extremely slow. I have shared this drive and I can create files, edit them rename them, if I create a folder from Webdav it takes too long to respond from nextcloud client it creates fine, in both cases renaming the folder returns lock error when I look at the log, I have disabled the lock (redis) but it is worse. 

In summary creating folders on external drives does not work both local and S3.

### Steps to reproduce

1. create a folder from webdav and rename on windows desktop
2. rename a folder (folder is a external Drive local XFS)
3. imposible rename a folder (lock???)
4. test from client
5. create folder ok (sync) (folder is a external Drive local  XFS)
6. Rename error lock

### Expected behavior

rename folder ok

### Installation method

None

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Logs

```shell
/httpdocs/lib/private/Lock/MemcacheLockingProvider.php","Line":62}},"message":"\"OTRAS/OTRAS$\" is locked, existing lock on file: exclusive","exception":{},"CustomMessage":"\"OTRAS/OTRAS$\" is locked, existing lock on file: exclusive"}}
```

**Comment by wmeneses** [comment]
Form web interface same error, create a folder ok, rename failed

**Comment by wmeneses** [comment]
Is it possible that it is a disk lock? although the permissions are ok this problem also occurs in S3 (compatible)(external). I have created any folder on the server with the same permissions (example /other) and I have shared it as external (local) and it works perfectly renaming the folder in seconds.

**Comment by joshtrichards** [comment]
Unfortunately your report is incomplete.  Please provide:

- your config (i.e. `occ config:list system`)
- your installed apps list (`occ app:list`)
- the full stack trace from the entry from then an excerpt

**Comment by wmeneses** [comment]
I rescanned the entire disk with occ scan and did a flush to redis, renaming the folders again with no errors.
