### ISSUE TITLE
Integrate the "Configurable share links" app directly into Nextcloud

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/server#42752]
**Is your feature request related to a problem? Please describe.**
I think one of the best functions of Nextcloud is to share directories and files. Normally they are shared with random chars and that is ok. But also there is the nice app "Configurable Share Links"  to rename shares. That is quite nice, too. Unfortunately, this function is not included in Nextcloud by default. Many Nextcloud hosters also do not install this app.

**Describe the solution you'd like**
I think the software is only a few hundred kilobytes long. It would be nice to include the software directly in the sharing options. Also there could be an administration setting to enable or disable this functions. 

**Describe alternatives you've considered**
I must install the app ""Configurable Share Links". On some servers i can not install it and so i can not use the function.

**Additional context**
Here is a screenshot. Maybe this is a good position to change the url.

![configshare](https://github.com/nextcloud/server/assets/58322182/dc1e8893-00c3-48a0-94e4-88a81fe4f19d)

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/issues/4536
https://github.com/JonathanTreffler/sharerenamer/issues/26
