### ISSUE TITLE
[Bug]: White page after upgrading

### ISSUE THREAD

**Issue by piiskop** [nextcloud/server#42754]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nextcloud just offered an upgrade, so I did it. After clicking the button _Disable maintenance mode and ..._, Nextcloud was redirected to the main [address](https://nextcloud.ons.ee/) and it is all white - nothing there.

### Steps to reproduce

1. Upgrade Nextcloud!
2. Experience the white page!

### Expected behavior

Nextcloud is working after upgrade.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
OCP\HintException: [0]: Memcache OC\Memcache\Redis not available for local cache (Is the matching PHP module installed and enabled?)
```

### List of activated Apps

```shell
An unhandled exception has been thrown:
OCP\HintException: [0]: Memcache OC\Memcache\Redis not available for local cache (Is the matching PHP module installed and enabled?)
```

### Nextcloud Signing status

```shell
Nothing - all white.
```

### Nextcloud Logs

```shell
{"reqId":"LywhFNduu9mCDdnVr4OY","level":4,"time":"2024-01-13T12:18:22+00:00","remoteAddr":"127.0.0.1","user":"--","app":"emlviewer","method":"GET","url":"/index.php/apps/files/preview-service-worker.js","message":"Error during app service registration: Call to undefined method OC\\Server::getEventDispatcher()","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"27.1.5.1","exception":{"Exception":"Error","Message":"Call to undefined method OC\\Server::getEventDispatcher()","Code":0,"Trace":[{"file":"/srv/nextcloud/apps/emlviewer/lib/AppInfo/Application.php","line":68,"function":"registerScripts","class":"OCA\\EmlViewer\\AppInfo\\Application","type":"->"},{"file":"/srv/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":142,"function":"register","class":"OCA\\EmlViewer\\AppInfo\\Application","type":"->"},{"file":"/srv/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":90,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/srv/nextcloud/lib/base.php","line":700,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/srv/nextcloud/lib/base.php","line":1200,"function":"init","class":"OC","type":"::"},{"file":"/srv/nextcloud/index.php","line":37,"args":["/srv/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/srv/nextcloud/apps/emlviewer/lib/AppInfo/Application.php","Line":73,"message":"Error during app service registration: Call to undefined method OC\\Server::getEventDispatcher()","exception":{},"CustomMessage":"Error during app service registration: Call to undefined method OC\\Server::getEventDispatcher()"}}
{"reqId":"LywhFNduu9mCDdnVr4OY","level":3,"time":"2024-01-13T12:18:22+00:00","remoteAddr":"127.0.0.1","user":"--","app":"PHP","method":"GET","url":"/index.php/apps/files/preview-service-worker.js","message":"Class OCA\\GroupFolders\\Helper\\LazyFolder contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (OCP\\Files\\Folder::searchBySystemTag, OCP\\Files\\FileInfo::getMetadata) at /srv/nextcloud/apps/groupfolders/lib/Helper/LazyFolder.php#32","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"27.1.5.1","data":{"app":"PHP"}}
{"reqId":"3bt2ygMRne1ynIsuP7SO","level":4,"time":"2024-01-13T12:18:35+00:00","remoteAddr":"127.0.0.1","user":"--","app":"emlviewer","method":"GET","url":"/","message":"Error during app service registration: Call to undefined method OC\\Server::getEventDispatcher()","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"27.1.5.1","exception":{"Exception":"Error","Message":"Call to undefined method OC\\Server::getEventDispatcher()","Code":0,"Trace":[{"file":"/srv/nextcloud/apps/emlviewer/lib/AppInfo/Application.php","line":68,"function":"registerScripts","class":"OCA\\EmlViewer\\AppInfo\\Application","type":"->"},{"file":"/srv/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":142,"function":"register","class":"OCA\\EmlViewer\\AppInfo\\Application","type":"->"},{"file":"/srv/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":90,"function":"registerApps","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/srv/nextcloud/lib/base.php","line":700,"function":"runInitialRegistration","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/srv/nextcloud/lib/base.php","line":1200,"function":"init","class":"OC","type":"::"},{"file":"/srv/nextcloud/index.php","line":37,"args":["/srv/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/srv/nextcloud/apps/emlviewer/lib/AppInfo/Application.php","Line":73,"message":"Error during app service registration: Call to undefined method OC\\Server::getEventDispatcher()","exception":{},"CustomMessage":"Error during app service registration: Call to undefined method OC\\Server::getEventDispatcher()"}}
{"reqId":"3bt2ygMRne1ynIsuP7SO","level":3,"time":"2024-01-13T12:18:35+00:00","remoteAddr":"127.0.0.1","user":"--","app":"PHP","method":"GET","url":"/","message":"Class OCA\\GroupFolders\\Helper\\LazyFolder contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (OCP\\Files\\Folder::searchBySystemTag, OCP\\Files\\FileInfo::getMetadata) at /srv/nextcloud/apps/groupfolders/lib/Helper/LazyFolder.php#32","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36","version":"27.1.5.1","data":{"app":"PHP"}}
```

**Comment by piiskop** [comment]
_Apache_ has logged the following error in addition:

> [Sat Jan 13 12:34:16.819125 2024] [php:error] [pid 44143] [client 127.0.0.1:50358] PHP Fatal error:  Class OCA\\GroupFolders\\Helper\\LazyFolder contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (OCP\\Files\\Folder::searchBySystemTag, OCP\\Files\\FileInfo::getMetadata) in /srv/nextcloud/apps/groupfolders/lib/Helper/LazyFolder.php on line 32

**Comment by joshtrichards** [comment]
Hi @piiskop - Every error you shared is a local configuration matter (you have some incompatible apps force installed from the looks of it) and something probably also incomplete with your PHP environment. Please post over at the Nextcloud Help Forum - https://help.nextcloud.com for troubleshooting assistance.

**Comment by piiskop** [comment]
I managed to [solve the issue](https://medium.com/arvutiteadus/ubuntu-20-04-1-lts-server-d0aaf807a9ee).

**Comment by joshtrichards** [comment]
Glad to hear it!

Looks like you have great knack for thoroughly documenting your processes and steps! I encourage you to submit suggestions or improvement to the project's documentation - https://docs.nextcloud.com and/or https://github.com/nextcloud/documentation

**Comment by aetmg** [comment]
That's a bug in the groupfolders app. See also: https://github.com/nextcloud/groupfolders/issues/2796
