### ISSUE TITLE
Question: Apply expire date settings to all shares?

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#4276]
Now that https://github.com/nextcloud/server/pull/4136 is merged we can discuss some small details I didn't want to bring up in the actual PR to stay focused.

In the Admin settings you have following public link settings regarding the expire date:

* Set default expiration date (where you can set a default expire date on every new share X days away from the point in time the share was created)
* optionally this expire date can be enforced, which means that a user can still reduce it but can't remove or increase it.

Now that the expire date exists for all share we could move it out of the "public link" section and make it a general share setting which apply to all shares (users, groups, federated, mail, public links).

I'm undecided. On one hand it would be good to unify stuff. On the other hand this might be to resstrictive, especially in the "enforce expire date" case. I expect that people might want to enforce a expire date  for external shares but would consider it to strict for all internal shares.

We could split it up. "Set default expire date" for all shares and "enforce expire data" as checkbox for link shares and mail shares. But do we really want more share options?

Opinion?

@nextcloud/designers

**Comment by rullzer** [comment]
1 settting is way to restrictive here.

It is nice to have it more unified but I think enforcing an expiration date on internal shares is just going to cost a lot of people effort in setting up shares over and over again...

**Comment by schiessle** [comment]
I agree with rullzer and since no other opinion was mentioned -> close

**Comment by reneglauser** [comment]
@schiessle hi, its exactly what we miss: a possibility to set a default expiration date on all shares, but to set the restriction seperately for shares and links
