### ISSUE TITLE
[BITV]: contrasts of input fields on the login mask are not enough 

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#42785]
Please make a background of the login mask brighter that contrast will be mind. 3:1

Right now contrasts are not enough:

![Screenshot from 2024-01-15 09-39-45](https://github.com/nextcloud/server/assets/6078378/5c78b5ee-1f90-4a9b-9c5c-65939b50331f)

![Screenshot from 2024-01-15 09-39-05](https://github.com/nextcloud/server/assets/6078378/431aa04f-9944-4b87-b4a3-a9088513fe2c)

**Comment by emoral435** [comment]
@nextcloud/designers What color should we use here that we could use? pinging so that we don't forget ;)

**Comment by susnux** [comment]
Thats not the background color, but the border color has a wrong contrast we use `--color-border-maxcontrast` but if we use `--color-text-maxcontrast` it works.
Meaning we should add `--color-border-maxcontrast` the variables that we test contrast for.

**Comment by szaimen** [comment]
Seems to be fullfilled:
![image](https://github.com/nextcloud/server/assets/42591237/b5ce13f8-ae7d-48a5-94b4-f1513192ddff)
