### ISSUE TITLE
[Bug]: File sorting based on numbers (with points ) changed in NC 28

### ISSUE THREAD

**Issue by ONP-ISI** [nextcloud/server#42826]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

File sorting based on numbers with points ( YYYY.MM.DD ) has changed in 28.0.1. No problem is 27.1.5
For example, with 3 folders named 2023.01.08, 2023.04.09, 2023.10.12, if I to do descending sort order or ascending, 2023.01.08 will be in the middle, not at the beginning or the end.
If you replace points with hyphens (2023-01-08, 2023-04-09, 2023-10-12), 2023-01-08 will be at beginning or at the end.

### Steps to reproduce

1.Create 3 folder named  2023.01.08, 2023.04.09, 2023.10.12
2.Clich on file sort by name
3.

### Expected behavior

NOK : Descending sort order or ascending, 2023.01.08 will be in the middle, not at the beginning or the end.
OK  : Replace points with hyphens (2023-01-08, 2023-04-09, 2023-10-12), 2023-01-08 will be at beginning or at the end.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.XXX.XXX",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.1.1",
        "overwrite.cli.url": "https:\/\/XXX.XXX.XXX.fr\/nextcloud",
        "overwritehost": "XXX.XXX.XXX.fr",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "default_phone_region": "FR",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_sendmailmode": "smtp",
        "default_language": "fr",
        "default_locale": "fr_FR",
        "skeletondirectory": "",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "user_email_visible": "true"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_accesscontrol: 1.18.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - groupfolders: 16.0.2
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - quota_warning: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - systemtags: 1.18.0
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_ldap: 1.19.0
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0 (installed 2.4.0)
  - comments: 1.18.0 (installed 1.10.0)
  - contactsinteraction: 1.9.0 (installed 1.1.0)
  - dashboard: 7.8.0 (installed 7.0.0)
  - encryption: 2.16.0
  - files_antivirus: 5.4.0 (installed 5.4.0)
  - files_automatedtagging: 1.18.0 (installed 1.18.0)
  - files_downloadactivity: 1.16.0 (installed 1.16.0)
  - files_external: 1.20.0
  - files_retention: 1.16.0 (installed 1.16.0)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - files_trackdownloads: 1.11.0 (installed 1.11.0)
  - firstrunwizard: 2.17.0 (installed 2.9.0)
  - nextcloud_announcements: 1.17.0 (installed 1.9.0)
  - photos: 2.4.0 (installed 1.1.0)
  - ransomware_protection: 1.14.0 (installed 1.14.0)
  - sharelisting: 1.2.0 (installed 1.2.0)
  - side_menu: 3.11.2 (installed 3.11.2)
  - support: 1.11.0 (installed 1.3.0)
  - survey_client: 1.16.0 (installed 1.8.0)
  - suspicious_login: 6.0.0
  - text: 3.9.1 (installed 3.1.0)
  - twofactor_totp: 10.0.0-beta.2
  - user_status: 1.8.1 (installed 1.0.1)
  - weather_status: 1.8.0 (installed 1.0.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by ONP-ISI** [comment]
https://help.nextcloud.com/t/file-sorting-based-on-numbers-changed-in-nc-28-0-1/179028

**Comment by jop217** [comment]
Same here. Very frustrating for large folders

**Comment by v3DJG6GL** [comment]
Same here super annoying if you have dozen of folders with that naming structure:
![Screenshot 2024-03-07 at 18-33-32](https://github.com/nextcloud/server/assets/72495210/84b37d3d-b334-4b2b-b881-b4e9fdb44124)

**Comment by szaimen** [comment]
Cc @nextcloud/server-frontend

**Comment by visit1985** [comment]
I have a similar issue with slightly different pattern.

Sorting by Name descending in NC 28:
<img width="492" alt="Screenshot 2024-05-05 at 14 22 36" src="https://github.com/nextcloud/server/assets/2237222/a06511e6-ff85-4dbb-a373-d3053c682f57">

This may have the same root cause.

**Comment by v3DJG6GL** [comment]
@szaimen
This issue is still present with Nextcloud 29.0.0. Hopefully it will be addressed soon...

**Comment by autoantwort** [comment]
I don't know if I should create a separate bug report for it, but the files are in the right order for me, but when I open the preview the order is not correct. 

https://github.com/nextcloud/server/assets/41973254/12b876e6-f336-407f-8038-fb1998affea0

**Comment by DevMichaelSabo** [comment]
The 29.0.1 doesn't fix the problem in [https://help.nextcloud.com/t/sorting-doesnt-working/190105](https://help.nextcloud.com/t/sorting-doesnt-working/190105)!

**Comment by susnux** [comment]
You can see from the milestone of the merged PR that the fix will only be available in Nextcloud 29.0.2+ (and 28.0.7+).

**Comment by nightcore500** [comment]
As @autoantwort already mentioned, this sorting problem exists not only in the folder listing in the file browser but also in the file preview.
I am now on release 29.0.2 and unfortunately still have the problem that when scrolling through the images in the file preview, the images are displayed completely mixed up. However, the files are displayed correctly in the file browser according to the timestamp in the file name.

Filebrowser:
![filebrowser Screenshot 2024-06-06 144214](https://github.com/nextcloud/server/assets/25873532/ddb4d73f-cd28-4f4e-9838-e8c54ad5ff3d)

First file:
![first Screenshot 2024-06-06 144226](https://github.com/nextcloud/server/assets/25873532/47d0a7d0-37ca-4afa-af8f-419a4a0f8575)

Next file:
![after Screenshot 2024-06-06 144234](https://github.com/nextcloud/server/assets/25873532/2f6848b0-ac30-4bdc-86cd-cf0f0d698c6d)

**Comment by susnux** [comment]
> I am now on release 29.0.2 and unfortunately still have the problem that when scrolling through the images in the file preview, the images are displayed completely mixed up.

@nightcore500 you screenshot is lacking the table headers, from the content it seems like you are sorting by date not name?

**Comment by nightcore500** [comment]
@susnux That is correct. The folder is sorted by date. In the folder view, it is sorted correctly as shown in the screenshot. After IMG20240605 comes IMG20240604. In the preview, however, IMG20240403 suddenly appears after IMG20240605, which is far in the past. I have just sorted by name. It then no longer seems to occur.

**Comment by susnux** [comment]
Yes if you sort by "Modified" then the mtime of the files is checked not the filename, if you sort by "Name" then the filename is taken into account.

**Comment by nightcore500** [comment]
@susnux Thank you for your help. But after IMG20240605 the file named IMG20240403 is displayed whose mtime does not come after that of IMG20240605. The files are also sorted correctly by mtime in the file browser. IMG20240403 also correctly appears there much later. But not in the preview?

**Comment by susnux** [comment]
I am not sure if I understand you here correctly, this issue is just about the files list.
If you sort by "Name" then only the name is considered, if you sort by "Modified" then only the mtime (the filename is ignored).

If you have issues with the "viewer" (that one that opens if you click on a file), then this is a different issue and should be reported here:

https://github.com/nextcloud/viewer/issues
