### ISSUE TITLE
[Bug]: Creating new shares doesn't use default admin sharing permissions

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#42835]
### Bug description

Since [Nextcloud 27](https://github.com/nextcloud/server/pull/39472), when you create a new share, the FULL permissions `31` gets used, unless you specifically changes the custom permissions (which then, the default are also NOT used in the pre-checked checkboxes)

### Steps to reproduce

1. Changes default permissions in admin settings
  ![image](https://github.com/nextcloud/server/assets/14975046/d9633915-3716-462d-80d6-4ba30bd3c2b1)
3. Create a user share
  ![image](https://github.com/nextcloud/server/assets/14975046/f531ecc6-ca1d-46a0-a234-00c5ba8f85ee)

### Expected behavior

The new share is created with the default permissions and not `31`

### Additional infos

Issue seems to come from the default permissions set being used here: 
https://github.com/nextcloud/server/blob/e35f6d89a271eede8380e9513811edfe923db4de/apps/files_sharing/src/views/SharingDetailsTab.vue#L755-L762

Historically, we used to sen the permissions as `null` to the Share OCS API and the backend would use the default permissions. Now it's always sent as `31` when untouched by the user.

**Comment by szaimen** [comment]
cc @Fenn-CS
