### ISSUE TITLE
Moving files causes re-download and lost of shares with new chunking algorithmn

### ISSUE THREAD

**Issue by f3anaro** [nextcloud/server#4284]
If you move a directory with a file manager on the client side, the moved files should not be re-downloaded and shares should be preserved - like in client v2.2.4. This issue is already known (owncloud/client#5670) and fixed in owncloud (owncloud/core#27508).

My current work around is to disable the new chunking algorithmn in the client with the env var ``OWNCLOUD_CHUNKING_NG=0`` - as suggested [here](https://github.com/owncloud/client/issues/5670#issuecomment-292906563).

### Steps to reproduce
1. Create `test` directory with two subdirectories `shared` and `nested` together with some dummy files
2. Share one `shared` subdirectory with some other user
3. Move `shared` subdirectory into `nested` on the client side (Ctrl+X or drag'N'drop in nautilus)

### Expected behaviour
If you move a directory with a file manager on the client side, the moved files should not be re-downloaded and shares should be preserved - like in client **v2.2.4**.

### Actual behaviour
After "moved to" event is propagated to the server, the client downloads the moved files from the server. The notification messages says "files ... updated". If the folder is a share or contains shares these shares are lost.

### Server configuration

**Operating system**: Ubuntu 14.04.5 LTS

**Web server:** nginx

**Database:** PostgreSQL 9.3.16

**PHP version:** 7.1

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** from source

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - user_ldap: 1.1.2
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - user_saml
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "datadirectory": "\/home\/nextcloud\/data",
        "dbtype": "pgsql",
        "version": "11.0.2.7",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "forcessl": true,
        "mail_from_address": "nextcloud",
        "mail_smtpmode": "php",
        "asset-pipeline.enabled": true,
        "loglevel": 3,
        "log_rotate_size": 14857600,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "production"
    }
}

```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Client version:**

    Nextcloud version 2.3.1
    Git revision 433ba03a2e092fd8de4d2830fff58f65e602d30a
    Using Qt 4.8.7, built against Qt 4.8.7

**Operating system:** Ubuntu 16.04.2 LTS

### Logs

[ownCloud client logwindow](https://gist.github.com/f3anaro/e2c98550ac469643e71bcecf9ba32c59)

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by MorrisJobke** [comment]
I tested this and it is fixed with #4524

**Comment by f3anaro** [comment]
Very nice :smiley:

**Comment by travisbotello** [comment]
> My current work around is to disable the new chunking algorithmn in the client with the env var OWNCLOUD_CHUNKING_NG=0 - as suggested here.

@f3anaro How would I do this? Changing the owncloud.cfg file?

**Comment by MorrisJobke** [comment]
> I tested this and it is fixed with #4524

Done.

**Comment by f3anaro** [comment]
@travisbotello It is an *environment variable* -- you have to set it in your operating system.

**Comment by f3anaro** [comment]
@travisbotello It is an *environment variable* -- you have to set it in your operating system.
