### ISSUE TITLE
[Bug]: Array to string conversion in AllConfig.php on line 164

### ISSUE THREAD

**Issue by pra75011** [nextcloud/server#42884]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

in log i have every second i receive : 
[Array to string conversion in AllConfig.php on line 164](https://help.nextcloud.com/t/array-to-string-conversion-in-allconfig-php-on-line-164/171019)

### Steps to reproduce

1. The 23 september2023  i report this in the community forum and no way / no answer from anyone 
2.forum URL : https://help.nextcloud.com/t/array-to-string-conversion-in-allconfig-php-on-line-164/171019
3.

### Expected behavior

[Sep '23](https://help.nextcloud.com/t/array-to-string-conversion-in-allconfig-php-on-line-164/171019?u=pra)
Hello
hope everybody are good
i have in my log and cron log the error message :
Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
all seems running well but …
seems something wrong in my config file (config.php) if i understand good the file name : AllConfig.php
line 164 =
163 public function getSystemValueString(string $key, string $default = ‘’): string {
164 return (string) $this->getSystemValue($key, $default);
165 }

system information :
Operating system: Linux 6.1.0-7-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.20-2 (2023-04-08) x86_64
Webserver: Apache/2.4.57 (Debian) (fpm-fcgi)
Database: pgsql PostgreSQL 14.5 (Debian 14.5-3) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-7) 12.2.0, 64-bit
PHP version: 8.2.7
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, json, random, Reflection, SPL, session, standard, sodium, cgi-fcgi, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, exif, memcache, msgpack, pdo_pgsql, pgsql, Phar, posix, pspell, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, memcached, Zend OPcache
Nextcloud version: 27.1.1 - 27.1.1.0
Updated from an older Nextcloud/ownCloud or fresh install: fresh

apps :
Enabled:

activity: 2.19.0
admin_audit: 1.17.0
bookmarks: 13.1.1
breezedark: 27.0.0
bruteforcesettings: 2.7.0
calendar: 4.5.1
checksum: 1.2.2
circles: 27.0.1
cloud_federation_api: 1.10.0
comments: 1.17.0
contacts: 5.4.2
contactsinteraction: 1.8.0
dashboard: 7.7.0
dav: 1.27.0
federatedfilesharing: 1.17.0
federation: 1.17.0
files: 1.22.0
files_external: 1.19.0
files_pdfviewer: 2.8.0
files_reminders: 1.0.0
files_rightclick: 1.6.0
files_sharing: 1.19.0
files_trashbin: 1.17.0
files_versions: 1.20.0
firstrunwizard: 2.16.0
logreader: 2.12.0
lookup_server_connector: 1.15.0
mail: 3.4.0
nextcloud_announcements: 1.16.0
notes: 4.8.1
notifications: 2.15.0
oauth2: 1.15.1
password_policy: 1.17.0
photos: 2.3.0
privacy: 1.11.0
provisioning_api: 1.17.0
qownnotesapi: 23.6.0
recommendations: 1.6.0
related_resources: 1.2.0
richdocuments: 8.2.0
richdocumentscode: 23.5.402
serverinfo: 1.17.0
settings: 1.9.0
sharebymail: 1.17.0
side_menu: 3.10.3
spreed: 17.1.1
support: 1.10.0
survey_client: 1.15.0
suspicious_login: 5.0.0
systemtags: 1.17.0
text: 3.8.0
theming: 2.2.0
twofactor_backupcodes: 1.16.0
updatenotification: 1.17.0
user_status: 1.7.0
viewer: 2.1.0
weather_status: 1.7.0
workflowengine: 2.9.0
Disabled:
encryption
twofactor_totp
user_ldap
config file : config.php :
{
“instanceid”: “REMOVED SENSITIVE VALUE”,
“passwordsalt”: “REMOVED SENSITIVE VALUE”,
“secret”: “REMOVED SENSITIVE VALUE”,
“trusted_domains”: [
0 => ‘tls.pra.rip’,
1 => ‘reverse.tech.pra.rip’,
2 => ‘reverse.pra.rip’,
3 => ‘192.168.123.125’,
4 => ‘2a01:e0a:1ef:7591::203’,
5 => ‘192.168.125.0/24’,
6 => ‘2a01:e0a:db9:10f1::/64’,
],
“trusted_proxies”: “REMOVED SENSITIVE VALUE”,
“overwritehost”: “tls.pra.rip”,
“overwritewebroot”: “/”,
“overwritecondaddr”: [
“^192\.168\.123\.125$”,
“^2a01:e0a:1ef:7591::203$”
],
“datadirectory”: “REMOVED SENSITIVE VALUE”,
“dbtype”: “pgsql”,
“version”: “27.1.1.0”,
“overwrite.cli.url”: “https://tls.pra.rip/”,
“dbname”: “REMOVED SENSITIVE VALUE”,
“dbhost”: “REMOVED SENSITIVE VALUE”,
“dbport”: “”,
“dbtableprefix”: “oc_”,
“dbuser”: “REMOVED SENSITIVE VALUE”,
“dbpassword”: “REMOVED SENSITIVE VALUE”,
“installed”: true,
“force_language”: “fr”,
“mail_from_address”: “REMOVED SENSITIVE VALUE”,
“mail_smtpmode”: “smtp”,
“mail_sendmailmode”: “smtp”,
“mail_domain”: “REMOVED SENSITIVE VALUE”,
“mail_smtphost”: “REMOVED SENSITIVE VALUE”,
“mail_smtpport”: “587”,
“mail_smtpauth”: 1,
“mail_smtpname”: “REMOVED SENSITIVE VALUE”,
“mail_smtppassword”: “REMOVED SENSITIVE VALUE”,
“filelocking.enabled”: true,
“memcache.locking”: “\OC\Memcache\Redis”,
“memcache.local”: “\OC\Memcache\Redis”,
“redis”: {
“host”: “REMOVED SENSITIVE VALUE”,
“port”: 6379,
“timeout”: 0
},
“default_phone_region”: “FR”,
“diagnostics.logging”: true,
“diagnostics.logging.threshold”: 5,
“log_type”: “file”,
“log_type_audit”: “file”,
“loglevel_frontend”: 2,
“loglevel”: 2,
“log.backtrace”: false,
“logfile”: “/var/www/nextcloudData/logs/nextcloud.log”,
“logfile_audit”: “/var/www/nextcloudData/logs/audit.log”,
“log_query”: false,
“query_log_file”: “/var/www/nextcloudData/logs/sql.log”,
“redis_log_file”: “/var/www/nextcloudData/logs/redis.log”,
“log_rotate_size”: 104857600,
“logdateformat”: “d F, Y H:i:s”,
“logtimezone”: “UTC”,
“tempdirectory”: “/tmp/nextcloudtemp”,
“trashbin_retention_obligation”: “auto”,
“htaccess.RewriteBase”: “/”,
“updater.release.channel”: “stable”,
“integrity.check.disabled”: false,
“forwarded_for_headers”: [
“HTTP_X_FORWARDED”,
“HTTP_FORWARDED_FOR”
],
“enabledPreviewProviders”: [
“OC\Preview\Image”,
“OC\Preview\MP3”,
“OC\Preview\TXT”,
“OC\Preview\MarkDown”,
“OC\Preview\Epub”,
“OC\Preview\PDF”,
“OC\Preview\OpenDocument”,
“OC\Preview\StarOffice”,
“OC\Preview\MSOfficeDoc”,
“OC\Preview\MSOffice2003”,
“OC\Preview\MSOffice2007”,
“OC\Preview\FB2”
],
“preview_max_x”: 1080,
“preview_max_y”: 1920,
“app_install_overwrite”: [
“files_downloadactivity”,
“admin_notifications”,
“defaultlinkopen”,
“files_reader”
],
“has_rebuilt_cache”: true,
“theme”: “”,
“enforce_theme”: “”
}

what is wrong? ^^

Cron Configuration: Array
(
[backgroundjobs_mode] => cron
[lastcron] => 1695795317
)

for trusted_proxiess it the same format than trusted_domains, means it s an array :
array (
0 => ‘<one_IPv4>’,
1 => ‘<one_IPv6>’,
),

thank you for your help
pra

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
< [11:22:51] - root@webblog:/var/www/nextcloud >
 =>sudo -u www-data php occ config:list system
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "tls.pra.rip",
            "reverse.tech.pra.rip",
            "reverse.pra.rip",
            "192.168.123.125",
            "2a01:e0a:1ef:7591::203",
            "192.168.125.0\/24",
            "2a01:e0a:db9:10f1::\/64"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "tls.pra.rip",
        "overwritewebroot": "\/",
        "overwritecondaddr": [
            "^192\\.168\\.123\\.125$",
            "^2a01:e0a:1ef:7591::203$"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "27.1.5.1",
        "overwrite.cli.url": "https:\/\/tls.pra.rip\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "force_language": "fr",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "default_phone_region": "FR",
        "diagnostics.logging": true,
        "diagnostics.logging.threshold": 5,
        "log_type": "file",
        "log_type_audit": "file",
        "loglevel_frontend": 2,
        "loglevel": 2,
        "log.backtrace": false,
        "logfile": "\/var\/www\/nextcloudData\/logs\/nextcloud.log",
        "logfile_audit": "\/var\/www\/nextcloudData\/logs\/audit.log",
        "log_query": false,
        "log_rotate_size": 104857600,
        "logdateformat": "d F, Y H:i:s",
        "logtimezone": "UTC",
        "tempdirectory": "\/tmp\/nextcloudtemp",
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/",
        "updater.release.channel": "stable",
        "integrity.check.disabled": false,
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Epub",
            "OC\\Preview\\PDF",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\FB2"
        ],
        "preview_max_x": 1080,
        "preview_max_y": 1920,
        "app_install_overwrite": [
            "files_downloadactivity",
            "admin_notifications",
            "defaultlinkopen",
            "files_reader"
        ],
        "has_rebuilt_cache": true,
        "theme": "",
        "enforce_theme": "",
        "maintenance": false
    }
}
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
< [11:22:55] - root@webblog:/var/www/nextcloud >
```

### List of activated Apps

```shell
=>sudo -u www-data php occ app:list
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
Enabled:
  - activity: 2.19.0
  - admin_audit: 1.17.0
  - bookmarks: 13.1.3
  - breezedark: 27.0.0
  - bruteforcesettings: 2.7.0
  - calendar: 4.6.3
  - checksum: 1.2.3
  - circles: 27.0.1
  - cloud_federation_api: 1.10.0
  - comments: 1.17.0
  - contacts: 5.5.1
  - contactsinteraction: 1.8.0
  - dav: 1.27.0
  - federatedfilesharing: 1.17.0
  - federation: 1.17.0
  - files: 1.22.0
  - files_external: 1.19.0
  - files_pdfviewer: 2.8.0
  - files_reminders: 1.0.0
  - files_rightclick: 1.6.0
  - files_sharing: 1.19.0
  - files_trashbin: 1.17.0
  - files_versions: 1.20.0
  - firstrunwizard: 2.16.0
  - logreader: 2.12.0
  - lookup_server_connector: 1.15.0
  - mail: 3.5.3
  - nextcloud_announcements: 1.16.0
  - notes: 4.9.2
  - notifications: 2.15.0
  - oauth2: 1.15.1
  - password_policy: 1.17.0
  - photos: 2.3.0
  - privacy: 1.11.0
  - provisioning_api: 1.17.0
  - qownnotesapi: 23.12.0
  - recommendations: 1.6.0
  - related_resources: 1.2.0
  - richdocuments: 8.2.4
  - richdocumentscode: 23.5.702
  - serverinfo: 1.17.0
  - settings: 1.9.0
  - sharebymail: 1.17.0
  - side_menu: 3.11.3
  - spreed: 17.1.4
  - support: 1.10.0
  - survey_client: 1.15.0
  - suspicious_login: 5.0.0
  - systemtags: 1.17.0
  - text: 3.8.0
  - theming: 2.2.0
  - twofactor_backupcodes: 1.16.0
  - updatenotification: 1.17.0
  - user_status: 1.7.0
  - viewer: 2.1.0
  - weather_status: 1.7.0
  - workflowengine: 2.9.0
Disabled:
  - dashboard: 7.7.0 (installed 7.7.0)
  - encryption: 2.15.0
  - twofactor_totp: 9.0.0
  - user_ldap: 1.17.0
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
PHP Warning:  Array to string conversion in /var/www/nextcloud/lib/private/AllConfig.php on line 164
< [11:23:36] - root@webblog:/var/www/nextcloud >
```

### Nextcloud Signing status

```shell
No errors have been found.
look attachment
```

### Nextcloud Logs

```shell
look attachment
```

### Additional info

attachment for :
integrity :
![nextcloud_integrity](https://github.com/nextcloud/server/assets/64706280/3896b7d9-2abf-400f-a0c5-287edb118a4b)
log :
[nextcloud.log.xz.zip](https://github.com/nextcloud/server/files/13962900/nextcloud.log.xz.zip)

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/e42f511412c3dee98e843d215f6f74d65b8a5120/config/config.sample.php#L618-L626

`overwritecondaddr` is supposed to be a string and not an array. 
In most situations overwritecondaddr is not needed, so please double-check.

**Comment by pra75011** [comment]
thank you for your reply 
i just a question how to write IPv4 and IPv6 if we can't use array ?
perhaps i don't understand ,
i wrote : 
```
    'trusted_proxies' =>
    array (
      0 => '192.168.123.125',
      1 => '2a01:e0a:1ef:7591::203',
    ),
    'overwritehost' => 'tls.pra.rip',
    'overwritewebroot' => '/',
    'overwritecondaddr' => 
    array (
      0 => '^192\\.168\\.123\\.125$',
      1 => '^2a01:e0a:1ef:7591::203$',
```

 192.168.123.125 and 2a01:e0a:1ef:7591::203 is the ip of the reverse proxy

**Comment by joshtrichards** [comment]
Just posted a possible answer here for you:

https://help.nextcloud.com/t/array-to-string-conversion-in-allconfig-php-on-line-164/171019/5?u=jtr
