### ISSUE TITLE
occ files:scan ignores paths with spaces

### ISSUE THREAD

**Issue by tessus** [nextcloud/server#4291]
### Steps to reproduce
1. create a folder `Public/with space` in your web UI
2. copy a file in there on the OS level (correct permissions, correct user)
3. run `occ -vvv files:scan --path="/myuser/files/Public/with space"`

### Expected behaviour
It should find the file and add it to the database

### Actual behaviour
Even with `-vvv` I get the following output:

```
Starting scan for user 1 out of 1 (myuser)

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 0       | 0     | 00:00:00     |
+---------+-------+--------------+
```
I tried to escape the space, but this didn't work either: `occ -vvv files:scan --path="/myuser/files/Public/with\ space"`

If I create a directory `Public/withoutspace`, copy a file in there and run `occ -vvv files:scan --path="/myuser/files/Public/withoutspace"`, it works. But there's no debug output either.

If I specify a non-existent directory, I get the same output as above, which tells me there are actually 2 issues here:

1) No error message is shown, if the directory does not exist
2) Directories with spaces are not valid

### Server configuration
**Operating system**: Linux

**Web server:** Apache 2.4.25

**Database:** MySQL 5.6.25

**PHP version:** 7.1.3

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud or fresh install:** updated: oc 8.2.9 -> nc 9.0.57 -> 10.0.4 -> 11.0.2

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.4.1
  - activitylog: 0.0.1
  - admin_audit: 1.1.0
  - announcementcenter: 3.0.0
  - apporder: 0.3.3
  - bookmarks: 0.9.1
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - direct_menu: 0.10.1
  - external: 1.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_markdown: 1.0.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - survey_client
  - user_ldap
  - user_saml
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "oc2352d53521",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/data\/nextcloud\/data",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "installed": true,
        "forcessl": true,
        "loglevel": 2,
        "maintenance": false,
        "trusted_domains": [
            "cloud.evermeet.cx"
        ],
        "share_folder": "\/Shared",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logdateformat": "Y-m-d H:i:s O",
        "logtimezone": "Europe\/Vienna",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_from_address": "evercloud",
        "mail_domain": "evermeet.cx",
        "mail_smtpsecure": "tls",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/data\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto",
        "updater.release.channel": "stable",
        "htaccess.RewriteBase": "\/",
        "overwrite.cli.url": "https:\/\/cloud.evermeet.cx",
        "auth.bruteforce.protection.enabled": false
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 52, Chrome 57.0.2987.98

**Operating system:** Mac OSX 10.11.6

#### Web server error log
```
no errors (empty)
```

#### Nextcloud log (data/nextcloud.log)
```
no errors (empty)
```

#### Browser log
```
no errors (empty)
```

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by tessus** [comment]
@MorrisJobke @icewind1991 any update on this? could you verify it as a bug?

**Comment by icewind1991** [comment]
How are you calling `occ`, if you have a script that calls it with the correct user or something similar that make sure that that script is passing it's arguments correctly

**Comment by tessus** [comment]
I called it from a script like this:

```
sudo -u nobody /usr/local/php/bin/php /data/projects/nextcloud/occ $@
```

But this gave me an idea. Changing `$@` to `"$@"` fixed the space problem, although I'm not quite sure why. The path was already in quotes, so bash should have interpreted it correctly.

Thank you.

It still would be nice, if I got some sort of feedback from occ. e.g. `Directory not found.` or `You screwed up the command, fix it.`. I found it very strange that I did not even get any info when using -vvv.

In any case, we can close this ticket, if you don't want to discuss error messages here.

**Comment by icewind1991** [comment]
PR for error message: https://github.com/nextcloud/server/pull/4396

**Comment by tessus** [comment]
great, looks good. thx.

**Comment by DaWy** [comment]
Is this fixed yet? Because i'm trying to scan folders with spaces and the folder gets CUT when the space is detected:

```
occ files:scan --path=jvelez/files/SMB/FL/Control of Data
Path not found: /jvelez/files/SMB/FL/Control
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 0       | 0     | 00:00:00     |
+---------+-------+--------------+
```

**Comment by DaWy** [comment]
> Is this fixed yet? Because i'm trying to scan folders with spaces and the folder gets CUT when the space is detected:
> 
> ```
> occ files:scan --path=jvelez/files/SMB/FL/Control of Data
> Path not found: /jvelez/files/SMB/FL/Control
> +---------+-------+--------------+
> | Folders | Files | Elapsed time |
> +---------+-------+--------------+
> | 0       | 0     | 00:00:00     |
> +---------+-------+--------------+
> ```
> I'm using last version of NextCloud: 15.0.6
> 
> Tried also this way:
> 
> ```
> occ files:scan --path='jvelez/files/SMB/FL/Control of Data'
> occ files:scan --path="jvelez/files/SMB/FL/Control of Data"
> occ files:scan "--path=jvelez/files/SMB/FL/Control of Data"
> ```

Nevermind. I was using a script to call the OCC. The fix stated by @tessus worked out like a charm.

Thanks!

**Comment by bitdruid** [comment]
> Nevermind. I was using a script to call the OCC. The fix stated by @tessus worked out like a charm.
> 
> Thanks!

sorry... can you help me out? i dont get it... my command is

`sudo -u nextcloud php /usr/share/webapps/nextcloud/occ files:scan --verbose --path="$dir"`

but it doesnt get the whitespaces. what i've to change?

**Comment by Tom60chat** [comment]
Old, but for people lost like, the answer was actually `occ files:scan --path="my/path/with\ whitespace/"`, it would be nice if it was explained in the wiki....
