### ISSUE TITLE
🍱 Interactive widget: file

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#42916]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

With https://github.com/nextcloud/server/issues/42550 coming to nextcloud implement a file widget that allows interaction, in case of a file:
* preview rendering
* download

**Additional context**
https://github.com/nextcloud/server/issues/42550

**Comment by sorbaugh** [comment]
@marcoambrosini I think it would be good to have the final scope documented in this ticket. Afaik the scope boils down to this:

1. Preview rendering of the file interactive-widget has two options:

![image](https://github.com/nextcloud/server/assets/62374139/b183c8c4-07db-492e-8a9a-c2c379e87abf)

2. We will indicate if a preview is used in the link title https://spec.commonmark.org/0.30/#link-title for markdown files

3. Have a download option.

cc @skjnldsv
