### ISSUE TITLE
🔍🗨️ Unified Search in individual Talk room

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#42914]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Currently you can limit searches via unified search to be limited to a talk room or folder

**Describe the solution you'd like**
Extend the current unified search implementation to allow for limiting a search to a specific Talk room or a folder in Files.

**Describe alternatives you've considered**
none

**Current requirements that need to be discussed:**

- [ ] Implementing filter : value in Unified search
- [ ] Filter translation for non-english speakers, e.g. "conversation" -> "raum", etc.

**Comment by sorbaugh** [comment]
@marcoambrosini do we need some mockups here?

Also, here is an example of the filter : value syntax as it was implemented on deck -> https://github.com/nextcloud/deck/pull/2934

**Comment by marcoambrosini** [comment]
I think that a quick and easy solution for this would be:

- Add a "Conversation" filter in "Apps and settings" 
- Clicking on this filter brings up a small dialog with a search box and a preloaded list of talk conversations (same design as the talk left sidebar)
- There's no need for using a 2 line component for these conversations, one line and small avatar is enough. Total height of the element 44px.
- One can search and click on a conversation there. No need for buttons, the click of a conversation adds the filter.
- Rename the current "Conversations" filter to "Talk" for better clarity
- Rename the current apps and settings into something else more inclusive of all the possibilities. "Places" was suggested by @jancborchardt in the past.
