### ISSUE TITLE
🍱 Interactive widget: folder

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#42917]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

With https://github.com/nextcloud/server/issues/42550 coming to Nextcloud implement a folder widget that allows interaction, in case of a folder:
* scrolling the folder
* browsing deeper into the folder

**Additional context**
https://github.com/nextcloud/server/issues/42550

**Comment by marcoambrosini** [comment]
It would be nice if clicking on the folder opened a dialog that allows us to peek into the folder and browse into subfolders. This would be similar to the file picker component, although stripped of the left navigation. Here's a quick mockup: 

<img width="651" alt="Screenshot 2024-02-01 at 15 38 55" src="https://github.com/nextcloud/server/assets/26852655/41fb4e48-177a-4c27-acdd-9bbd9df5a150">
