### ISSUE TITLE
🗃️ "Personal files" view

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#42919]
## Context
With heavy use of Group Folders, the `All Files` menu view is confusing for the user who gets his/her personal files mixing with organization files. Currently there is no option on top level to have filtered view only showing a user their own files.

### Describe the solution you'd like
Add an entry `Personal files` to the left menu, directly below `All files`, showing:
- only user files
- no groupfolders
- no items shared from other people

**Comment by jancborchardt** [comment]
Updated title and description a bit, so it's clear it should be "Personal files" instead of "My".

**Comment by jancborchardt** [comment]
Also cc @tobiasKaminsky on this regarding adding this to mobile apps.

**Comment by tobiasKaminsky** [comment]
So it would be list of root with
- my files (files and folder) that I own
- all accepted incoming shares

clicking on any of those folders would then show entire content of this folder, or also only limited to above criteria? (would be harder to do)

**Comment by sorbaugh** [comment]
Assuming, we can already filter files by owner, this should probably be frontend only right? @susnux @Fenn-CS

**Comment by skjnldsv** [comment]
@tobiasKaminsky, @sorbaugh edited the first post and lost Jan's description, I added it back :)

**Comment by AndyScherzinger** [comment]
Thanks for the correction and update of the description in the issue @skjnldsv

That now matches also my understanding of how it is supposed to work / the filter to be done 👍

**Comment by susnux** [comment]
> Assuming, we can already filter files by owner, this should probably be frontend only right?

I would say yes

**Comment by tobiasKaminsky** [comment]
> clicking on any of those folders in "personal view" would then show entire content of this folder, or also only limited to above criteria? (would be harder to do)

Let me re-ask this again :-)

**Comment by emoral435** [comment]
@tobiasKaminsky Just based off of the description, I assuming that it is limited to the above criteria. In specific,
> no items shared from other people
So, if my understanding is correct, this would mean that we would have to filter even Files/Nodes within each folder to see if it is shared, etc

**Comment by jancborchardt** [comment]
@tobiasKaminsky @emoral435 according to the comment at https://github.com/nextcloud-gmbh/customer-feature-requests/issues/404#issuecomment-1556626596, the root level is the mainly important one.

**Comment by AndyScherzinger** [comment]
> So since it is likely a lot more work to filter it out at every step, it would make more sense to just start with that? @AndyScherzinger

Fine by me 👍 

Only thing that is not covered then given the referenced comment @jancborchardt https://github.com/nextcloud-gmbh/customer-feature-requests/issues/404#issuecomment-1556626596 is 

> For a folder shared TO others, this entry should display the content created by others in that folder

and maybe 

> This entry should display shared file/folder FROM others moved intentionally by the user inside a created/owned folder at root

Simply because I am not sure if this is easily detectable and if the file ownership is actually with the user and not the sharing party. @sorbaugh can you check this with the team.
Also not sure how we view that and if we would consider these "files of the user" because that is what "personal files" as a term reflects for me.

**Comment by tobiasKaminsky** [comment]
> This entry should display shared file/folder FROM others moved intentionally by the user inside a created/owned folder at root

As I understand this, it means
- folderSharedFromUserAbcToMe is not shown in root folder
- /myReceivedShares/ is my created folder
- /myReceivedShares/folderSharedFromUserAbcToMe is then shown within this view

--> then it would also fit in my "assumption" to have this filter only on top level



> For a folder shared TO others, this entry should display the content created by others in that folder

Same here. This is shown in root view, and content is also shown, as in subfolder those filter does not apply

**Comment by tobiasKaminsky** [comment]
@jancborchardt do we wanna have another icon?

e.g. 
![image](https://github.com/nextcloud/server/assets/5836855/a2c8988a-ec89-47a8-b159-2d10da3b5709)


![2024-01-26-081730](https://github.com/nextcloud/server/assets/5836855/d0da06a7-0b78-431f-b968-f29c3e1452aa) ![2024-01-26-083441](https://github.com/nextcloud/server/assets/5836855/eab5719e-fcc9-40af-9376-36cc2de4b3dc)

**Comment by emoral435** [comment]
Just to get a final confirmation from @AndyScherzinger and @jancborchardt , the filter should only apply to the root folder within the personal files view, correct? I agree with Tobias' assumption

**Comment by AndyScherzinger** [comment]
As far as I read it, yes 😊👍

**Comment by sorbaugh** [comment]
Adding some details here that might get lost due to the discussion taking place in the PR. There is a breadcrumb optimization that was added to the Personal Files View that needs to be applied to all other Files Views as well for consistency. Will create a separate issue so we can get this issue merged and closed while still tracking the Breadcrumb optimization.

See: https://github.com/nextcloud/server/pull/43211#issuecomment-1928631779

**Comment by maximelehericy** [comment]
@emoral435 thanks for the work here ! this one has been expected for a long time and will make happy a lot of people :)
I was testing it, and on our cloud I can still see groupfolders under the Personal Files view, which I think should not be there 🙃
![image](https://github.com/nextcloud/server/assets/87175513/8f51db01-2a0e-4933-924f-7c0c9d808a9b)
