### ISSUE TITLE
Update required but newest Version ???

### ISSUE THREAD

**Issue by taut98** [nextcloud/server#4292]
### Steps to reproduce
1. Dont know how to reproduce this error

### Expected behaviour
Just wanted to Login to my Nextcloud

### Actual behaviour
Nextcloud tells me: 
Update required.
Because youre using an big Instance please update via console.

But my instance isnt big, im using it alone currently and i already have Version 11.0.2

### Server configuration

**Operating system**:
Debian 8.7.
**Web server:**
Apache 2.4
**Database:**
Mysql
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
11.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh
**Where did you install Nextcloud from:**
Nextcloud.com

**What could cause the Problem**
Changed my IP, to recieve Internet Access.
Updated the OnlyOffice Integration app, removing old installing new.
Changed the IP back to the old.

Restartet Apache and Hostsystem and now recieving this error.

`sudo -u www-data php occ status` tells me this:

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
  - installed: true
  - version: 11.0.2.7
  - versionstring: 11.0.2
  - edition:

How can i find out, which app requires an update?

**Comment by ChristophWurst** [comment]
simply run `sudo -u www-data php occ upgrade` and it will update whatever needs to be updated

**Comment by taut98** [comment]
Thanks!
