### ISSUE TITLE
[BITV]: settings modal has double scrollbar under some circumstances

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#42938]
See 
![image](https://github.com/nextcloud/server/assets/42591237/88e0c5f1-cb34-4592-99ee-f5a715877298)

**Comment by JuliaKirschenheuter** [comment]
not sure that it is an issue - min. viewport height is 1024px and because of this double scrolling is there (was fixed here https://github.com/nextcloud/server/issues/36965#issuecomment-1812579291) @ShGKme what do you think?

**Comment by ShGKme** [comment]
I'm almost sure it is a known issue and was fixed somewhere. cc @susnux

**Comment by susnux** [comment]
`.modal-wrapper .modal-container__content` needs to be set to `overflow: hidden` on NcDialog I think.
