### ISSUE TITLE
No connection to Nextcloud at https://my.url. Operation cancelled

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#4294]
### Steps to reproduce

1. Define full-access token
1. Upgrade to 11.0.3 RC1
1. Watch the client explode
1. Log out/login
1. Restart client

### Expected behaviour

At some point, the client should connect

### Actual behaviour

> No connection to Nextcloud at https://my.url. Operation cancelled

------
@LukasReschke @icewind1991

**Comment by LukasReschke** [comment]
So you created the token newly just now?

**Comment by LukasReschke** [comment]
cc @icewind1991

**Comment by oparoz** [comment]
I just created a new token to see if it would help and I get the same result.

I also noticed that one of my calendar can't connect any more using an older restricted token. It could be because I played with the "allow fs access" setting

**Comment by LukasReschke** [comment]
> I also noticed that one of my calendar can't connect any more using an older restricted token. It could be because I played with the "allow fs access" setting

Interesting. Let me see if I can reproduce that somehow.

**Comment by oparoz** [comment]
Something on the server may have changed. The client can now connect.

Still have the calendar issue though.

**Comment by oparoz** [comment]
Closing as the calendar issue is likely a different bug.
