### ISSUE TITLE
[BITV]: focus gap appears through sidebar navigation

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#42957]
1. Open a sidebar with existing sharing links with other users
2. Try to navigate through sidebar with a keyboard
3. See a gap between "avatar" action button and "Open Sharing Details" action button -> there is no element in focus and "avatar" action button will be reloaded

![Peek 2024-01-19 11-26](https://github.com/nextcloud/server/assets/6078378/f8263288-dd14-452e-8e67-f398eee9fb1e)

**Comment by JuliaKirschenheuter** [comment]
Thank you @Pytal for fixing this bug! I will move this issue to the "parked" as far there is a backport open. Is there something more we have to fix regarding this issue?

**Comment by Pytal** [comment]
> Thank you @Pytal for fixing this bug! I will move this issue to the "parked" as far there is a pending dependency open. Is there something more we have to fix regarding this issue?

Nope, all good now!
