### ISSUE TITLE
[Bug]: Show "view in folder" only if it makes sense

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#42956]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The "view in folder" option in the "..." menu is shown when I regularly browse my files:

![image](https://github.com/nextcloud/server/assets/1589737/866b1e6b-352d-4695-a68d-7a63b5b10969)

There it doesn't make sense, I'm already in the folder of the file.

On the other hand if I go to the "shared with you" list, the option is no longer there. But here it would actually make sense to have a way to navigate to the folder where the file is located.

Probably other views are affected as well, this are only two examples.

tested on c.nc.com (28.0.2 RC1)

### Steps to reproduce

see above

~some extra text to allow me to send the ticket :see_no_evil:~

### Expected behavior

"view in folder" should only be available if it makes sense

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment]
cc @nextcloud/server-frontend
