### ISSUE TITLE
two 500MB mp4 files disappeared after upload

### ISSUE THREAD

**Issue by yennor** [nextcloud/server#4297]
I uploaded two big mp4 files, both around 500MB big. The upload was shown as successfull. Today I wanted to get the files again, but they disappeared, they weren't show in any way in the activity log. so I checked out nextcloud.log

`{"reqId":"iOIxOwupFm24xofJ4c2g","remoteAddr":"127.0.0.1","app":"PHP","message":"exec(): Unable to fork [stat -c %Y '\/var\/www\/html\/cloud\/data\/ronney\/files\/Ramona\/Bilder Hochzeit\/Hochzeitsfest\/P1110485.MP4'] at \/var\/www\/html\/cloud\/lib\/private\/LargeFileHelper.php#199","level":3,"time":"2017-04-10T17:33:40+00:00","method":"PUT","url":"\/cloud\/remote.php\/webdav\/Ramona\/Bilder%20Hochzeit\/Hochzeitsfest\/P1110485.MP4","user":"ronney","version":"11.0.2.7"}
{"reqId":"iOIxOwupFm24xofJ4c2g","remoteAddr":"127.0.0.1","app":"PHP","message":"exec(): Unable to fork [stat -c %Y '\/var\/www\/html\/cloud\/data\/ronney\/files\/Ramona\/Bilder Hochzeit\/Hochzeitsfest'] at \/var\/www\/html\/cloud\/lib\/private\/LargeFileHelper.php#199","level":3,"time":"2017-04-10T17:33:40+00:00","method":"PUT","url":"\/cloud\/remote.php\/webdav\/Ramona\/Bilder%20Hochzeit\/Hochzeitsfest\/P1110485.MP4","user":"ronney","version":"11.0.2.7"}
{"reqId":"iOIxOwupFm24xofJ4c2g","remoteAddr":"127.0.0.1","app":"PHP","message":"exec(): Unable to fork [stat -c %Y '\/var\/www\/html\/cloud\/data\/ronney\/files\/Ramona\/Bilder Hochzeit\/Hochzeitsfest\/P1110485.MP4'] at \/var\/www\/html\/cloud\/lib\/private\/LargeFileHelper.php#199","level":3,"time":"2017-04-10T17:33:40+00:00","method":"PUT","url":"\/cloud\/remote.php\/webdav\/Ramona\/Bilder%20Hochzeit\/Hochzeitsfest\/P1110485.MP4","user":"ronney","version":"11.0.2.7"}
{"reqId":"iOIxOwupFm24xofJ4c2g","remoteAddr":"127.0.0.1","app":"PHP","message":"exec(): Unable to fork [stat -c %Y '\/var\/www\/html\/cloud\/data\/ronney\/files\/Ramona\/Bilder Hochzeit\/Hochzeitsfest'] at \/var\/www\/html\/cloud\/lib\/private\/LargeFileHelper.php#199","level":3,"time":"2017-04-10T17:33:40+00:00","method":"PUT","url":"\/cloud\/remote.php\/webdav\/Ramona\/Bilder%20Hochzeit\/Hochzeitsfest\/P1110485.MP4","user":"ronney","version":"11.0.2.7"}
{"reqId":"iOIxOwupFm24xofJ4c2g","remoteAddr":"127.0.0.1","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\\\/Ramona\\\/Bilder Hochzeit\\\/Hochzeitsfest\\\/P1110485.MP4 not found while trying to get owner\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(520): OC\\\\Files\\\\View->getOwner('\\\/Ramona\\\/Bilder ...')\\n#1 \\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(161): OCA\\\\Activity\\\\FilesHooks->getSourcePathAndOwner('\\\/Ramona\\\/Bilder ...')\\n#2 \\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(117): OCA\\\\Activity\\\\FilesHooks->addNotificationsForFileAction('\\\/Ramona\\\/Bilder ...', 'file_created', 'created_self', 'created_by')\\n#3 \\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/activity\\\/lib\\\/FilesHooksStatic.php(45): OCA\\\\Activity\\\\FilesHooks->fileCreate('\\\/Ramona\\\/Bilder ...')\\n#4 [internal function]: OCA\\\\Activity\\\\FilesHooksStatic::fileCreate(Array)\\n#5 \\\/var\\\/www\\\/html\\\/cloud\\\/lib\\\/private\\\/legacy\\\/hook.php(106): call_user_func(Array, Array)\\n#6 \\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(284): OC_Hook::emit('OC_Filesystem', 'post_create', Array)\\n#7 \\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(215): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->emitPostHooks(false)\\n#8 \\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(137): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #14)\\n#9 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1072): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('P1110485.MP4', Resource id #14)\\n#10 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('Ramona\\\/Bilder H...', Resource id #14, NULL)\\n#11 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#13 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#14 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#15 \\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#16 \\\/var\\\/www\\\/html\\\/cloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/c...')\\n#17 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/cloud\\\/lib\\\/private\\\/Files\\\/View.php\",\"Line\":1640}","level":3,"time":"2017-04-10T17:33:40+00:00","method":"PUT","url":"\/cloud\/remote.php\/webdav\/Ramona\/Bilder%20Hochzeit\/Hochzeitsfest\/P1110485.MP4","user":"ronney","version":"11.0.2.7"}
{"reqId":"iOIxOwupFm24xofJ4c2g","remoteAddr":"127.0.0.1","app":"PHP","message":"shell_exec(): Unable to execute 'command -v libreoffice' at \/var\/www\/html\/cloud\/lib\/private\/PreviewManager.php#370","level":3,"time":"2017-04-10T17:33:40+00:00","method":"PUT","url":"\/cloud\/remote.php\/webdav\/Ramona\/Bilder%20Hochzeit\/Hochzeitsfest\/P1110485.MP4","user":"ronney","version":"11.0.2.7"}
{"reqId":"iOIxOwupFm24xofJ4c2g","remoteAddr":"127.0.0.1","app":"PHP","message":"shell_exec(): Unable to execute 'command -v openoffice' at \/var\/www\/html\/cloud\/lib\/private\/PreviewManager.php#373","level":3,"time":"2017-04-10T17:33:40+00:00","method":"PUT","url":"\/cloud\/remote.php\/webdav\/Ramona\/Bilder%20Hochzeit\/Hochzeitsfest\/P1110485.MP4","user":"ronney","version":"11.0.2.7"}
{"reqId":"iOIxOwupFm24xofJ4c2g","remoteAddr":"127.0.0.1","app":"no app in context","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/previewgenerator\\\/lib\\\/Watcher.php(66): OC\\\\Files\\\\Node\\\\NonExistingFile->getId()\\n#1 \\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/previewgenerator\\\/lib\\\/AppInfo\\\/Application.php(55): OCA\\\\PreviewGenerator\\\\Watcher->postWrite(Object(OC\\\\Files\\\\Node\\\\NonExistingFile))\\n#2 [internal function]: OCA\\\\PreviewGenerator\\\\AppInfo\\\\Application->OCA\\\\PreviewGenerator\\\\AppInfo\\\\{closure}(Object(OC\\\\Files\\\\Node\\\\NonExistingFile))\\n#3 \\\/var\\\/www\\\/html\\\/cloud\\\/lib\\\/private\\\/Hooks\\\/EmitterTrait.php(99): call_user_func_array(Object(Closure), Array)\\n#4 \\\/var\\\/www\\\/html\\\/cloud\\\/lib\\\/private\\\/Hooks\\\/PublicEmitter.php(33): OC\\\\Hooks\\\\BasicEmitter->emit('\\\\\\\\OC\\\\\\\\Files', 'postWrite', Array)\\n#5 \\\/var\\\/www\\\/html\\\/cloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php(134): OC\\\\Hooks\\\\PublicEmitter->emit('\\\\\\\\OC\\\\\\\\Files', 'postWrite', Array)\\n#6 \\\/var\\\/www\\\/html\\\/cloud\\\/lib\\\/private\\\/Files\\\/Node\\\/HookConnector.php(84): OC\\\\Files\\\\Node\\\\Root->emit('\\\\\\\\OC\\\\\\\\Files', 'postWrite', Array)\\n#7 [internal function]: OC\\\\Files\\\\Node\\\\HookConnector->postWrite(Array)\\n#8 \\\/var\\\/www\\\/html\\\/cloud\\\/lib\\\/private\\\/legacy\\\/hook.php(106): call_user_func(Array, Array)\\n#9 \\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(292): OC_Hook::emit('OC_Filesystem', 'post_write', Array)\\n#10 \\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(215): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->emitPostHooks(false)\\n#11 \\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(137): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #14)\\n#12 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1072): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('P1110485.MP4', Resource id #14)\\n#13 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('Ramona\\\/Bilder H...', Resource id #14, NULL)\\n#14 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#15 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#16 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#17 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#18 \\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#19 \\\/var\\\/www\\\/html\\\/cloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/c...')\\n#20 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/cloud\\\/lib\\\/private\\\/Files\\\/Node\\\/NonExistingFile.php\",\"Line\":53}","level":3,"time":"2017-04-10T17:33:40+00:00","method":"PUT","url":"\/cloud\/remote.php\/webdav\/Ramona\/Bilder%20Hochzeit\/Hochzeitsfest\/P1110485.MP4","user":"ronney","version":"11.0.2.7"}
{"reqId":"iOIxOwupFm24xofJ4c2g","remoteAddr":"127.0.0.1","app":"PHP","message":"Call to a member function getChecksum() on boolean at \/var\/www\/html\/cloud\/apps\/dav\/lib\/Connector\/Sabre\/File.php#566","level":3,"time":"2017-04-10T17:33:40+00:00","method":"PUT","url":"\/cloud\/remote.php\/webdav\/Ramona\/Bilder%20Hochzeit\/Hochzeitsfest\/P1110485.MP4","user":"ronney","version":"11.0.2.7"}
`

**Operating system**:
debian linux stable

**Web server:**
apache
**Database:**
mysql
**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
11.0.2.7
**Updated from an older Nextcloud/ownCloud or fresh install:**
update from 11.x
**Where did you install Nextcloud from:**
downloaded

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - audioplayer: 1.4.1
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - ocsms: 1.11.5
  - password_policy: 1.1.0
  - previewgenerator: 1.0.5
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - workflowengine: 1.1.1

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
on
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by MorrisJobke** [comment]
Looks like your system has reached the process limit. See http://stackoverflow.com/a/20649541/520507 for how to resolve this. We can't do much here.
