### ISSUE TITLE
Fix two factor button layout

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#4298]
As you can see in https://github.com/nextcloud/server/pull/2618#issuecomment-284352757

The buttons look kind of ugly now. They need to be styles properly.
@nextcloud/designers work your magic please!

**Comment by rullzer** [comment]
Still looks ugly in beta2 :wink: 
![bildschirmfoto von 2017-03-06 11-00-46](https://cloud.githubusercontent.com/assets/1374172/23605311/6fc12f26-025c-11e7-829d-27c912cb5e07.png)

**Comment by nursoda** [comment]
It's not only design/layout of the buttons as shown above, but wrapping of localized buttons as shown in #173.

**Comment by MorrisJobke** [comment]
Fix is in #4865
