### ISSUE TITLE
icon color broken in app-store

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#42998]
See 
![image](https://github.com/nextcloud/server/assets/42591237/b4948a2e-fa53-40ad-b7b2-f55ed9ece5fe)

**Comment by JuliaKirschenheuter** [comment]
It is not a11y issue but a visual bug. removing from the board

**Comment by szaimen** [comment]
I tried to fix this but unfortunately I gave up because apparently we need to use `filter: var(--primary-invert-if-bright);` in dark mode and `filter: var(--primary-invert-if-dark);` in light mode. Unfortunately I did not find a working solution for this. See my WIP in https://github.com/nextcloud/server/pull/43082/files

**Comment by susnux** [comment]
icon classes :tada: :pensive: 
We really need to get rid of them and just use inline svgs.

**Comment by jancborchardt** [comment]
@sorbaugh small frontend bug that could be put on the "To do" as a small item whenever someone has time (we do it similarly in Talk).

**Comment by susnux** [comment]
@jancborchardt will do as part of the appstore overhauling for the discover section

**Comment by joshtrichards** [comment]
Similar: #42803
