### ISSUE TITLE
Calendar gets renamed when shared to someone else

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#4300]
This is on 11.0.3 RC1.

1. Share calendar personal to someone
2. URL is changed to https://example.com/remote.php/dav/calendars/lukas/personal_shared_by_lukas/

This `_shared_by_lukas` should not be there. It breaks existing clients that sync against `personal`. 

cc @georgehrke 
cc @oparoz Your issue.

**Comment by LukasReschke** [comment]
I guess we need to backport https://github.com/nextcloud/server/pull/4060

**Comment by LukasReschke** [comment]
Backport at https://github.com/nextcloud/server/pull/4301, applied on the affected instance and it should work now.

**Comment by rullzer** [comment]
#4301 is merged.
