### ISSUE TITLE
[Bug]: Low contrast for HTML buttons in emails

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#43043]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

| Emails sent with 28.0.1 | Emails sent with 28.0.2 RC1 |
|--------|--------|
| ![Bildschirmfoto vom 2024-01-23 08-54-04](https://github.com/nextcloud/server/assets/1374172/1e740cee-0fd1-4772-8c21-66e36c7c2d9e) | ![Bildschirmfoto vom 2024-01-23 08-53-50](https://github.com/nextcloud/server/assets/1374172/9049b112-5166-4c1b-8aa5-8ca8382e8983) | 

### Steps to reproduce

1. Execute a Nextcloud action that sends out an email with a button

### Expected behavior

Readable, accessible HTML button

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ShGKme** [comment]
I guess that the current button color is more contrast formally by the number, because "before" it was not contrast enough.

Most likely the same change as in other elements with primary style.

![image](https://github.com/nextcloud/server/assets/25978914/5d1f7cf0-b369-47d2-a89c-66c0ea1cc860)

**Comment by susnux** [comment]
It seems the email is forced to be white background but primary colors for dark theme are used. So probably the HTML needs `data-theme="light"` or similar set.
