### ISSUE TITLE
Use Permissions-Policy instead of (or in addition to) Feature-Policy

### ISSUE THREAD

**Issue by SergeyMosin** [nextcloud/server#43056]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
- Looks like `Feature-Policy` is being phased out in favor of `Permissions-Policy` https://github.com/w3c/webappsec-permissions-policy/blob/main/permissions-policy-explainer.md#a-bit-of-history
- `Feature-Policy` triggers ZAP [CWE-16](https://www.zaproxy.org/alerttags/cwe-16/) when performing [Cloud Application Security Assessment (CASA)](https://appdefensealliance.dev/casa) DAST scan against NC server

**Describe the solution you'd like**
Use `Permissions-Policy` header here: https://github.com/nextcloud/server/blob/4dc224fa2cda97465cfbbafb93426b550cfdcbfc/lib/public/AppFramework/Http/Response.php#L257-L263

**Describe alternatives you've considered**
Adding custom middle-ware to convert  `Feature-Policy` header into `Permissions-Policy` header, but it is not such good idea.

**Additional context**
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Permissions-Policy

**Comment by joshtrichards** [comment]
Duplicate of #22792
