### ISSUE TITLE
[Bug]: slow folder loading and actions in Files

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/server#43051]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Using Files (new UI is really good 😍) I noticed I often had to wait quite some time when I was performing an action. I made a few measures :
- opening a "shared with me" folder with 1500+ subfolders take ~22-24s to load
- Inside, Files need between 4 to 10 seconds to display a newly created folder, after I click the create new folder button. This is also true if the newly created folder is in a sub sub folder.
- Files need from 3 to 5s to take into account the renaming action on the newly created folder.

In my personal directory (not shared, and with ~30 entries), all the steps above take ~1s.

### Steps to reproduce

1. create a folder containing 1500+ subfolders
2. open a subfolder, and test creating a folder
3. rename the newly created folder

### Expected behavior

1. When I open a folder, I don't expect to wait for 22s in front of my screen to see the content. Past 10s loading, I tend to reach to the unified search which takes me faster to the folder I am looking for (great new search BTW :).
2. when I create a new (sub)folder, I expect the newly created folder to appear within 2s
3. when I rename a folder, I expect the renaming to be taken into account within 1s

(I gave estimations of time I expect, but I in reality, I don't have a very good idea of what is acceptable. Sure thing is, the current time seem to me too long.)

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

c.nc.c

**Comment by skjnldsv** [comment]
> Inside, Files need between 4 to 10 seconds to display a newly created folder, after I click the create new folder button. This is also true if the newly created folder is in a sub sub folder.

I'd say it should be fixed with 28.0.3 https://github.com/nextcloud/server/pull/42993

**Comment by skjnldsv** [comment]
> * opening a "shared with me" folder with 1500+ subfolders take ~22-24s to load

That is a backend issue, I'm guessing the request is the one taking 20+ seconds to complete :see_no_evil:
