### ISSUE TITLE
[Bug]: inconsistency in creating folders behavior

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/server#43052]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The create a new folder action consequences depends on the number of subfolders and display.

#### Behavior 1
1. In an empty folder, create a new folder
2. The new folder appear in edit mode so you can rename it.
3. Rename it, and hit enter.
4. The new folder is visible.

#### behavior 2
1. Go into a folder with a list a subfolders that exceeds your screen display capacity.
2. Make sure you cannot see the folders starting by "N"
5. Click create a new folder
6. The new folder is instantly created, but is not visible.
7. You have to scroll to the "N" folders to find it.
8. When you found it, it is not in edit mode.
9. To rename it, you must click the three dots menu > rename

### Expected behavior

I don't expect the behaviors to differ. I am surprised in behavior 2 that I can't see my newly created folder. I am surprised I have to scroll up or down to find it.
Also, once renamed, I may have to scroll again to find it (if I renamed it starting with an A, I have to scroll up again to the A).

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

c.nc.c

**Comment by skjnldsv** [comment]
Fixed by https://github.com/nextcloud/server/pull/42993
