### ISSUE TITLE
[Bug]: NC 28 (verify from 0.0 to 0.2 RC2) cosmetic bug in share link ONLY if set "always ask to a password"

### ISSUE THREAD

**Issue by dea-75** [nextcloud/server#43062]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi everyone,

I’ve found this cosmetic problem on NC 28 → 28.0.2 RC2.

If “always ask for a password” on share link IS NOT forced:
Create folder → share → share link works well

If I set “always ask for a password”:
Create folder → share → share link → show random password, than click “create share” → the new share is not displayed
Than close the share, click share on the directory and show the new share

### Steps to reproduce

1.Set "always ask to a password"
2.Create a new share
3.Propose a random password
4. OK
5. Don't show the share (close, re-open share area, than ok)
6. If "always ask to a password" is not set works fine

### Expected behavior

The same without "always ask to a password"

### Installation method

None

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by dea-75** [comment]
I can confirm the same problem on 28.0.2 rc4

**Comment by MalteP** [comment]
This just broke my installation after upgrading from 28.0.1 to 28.0.2 (both stable)...

**Comment by ssiergl** [comment]
solved for us in 28.0.3

**Comment by dea-75** [comment]
Almost. 50% solved.
If you define a new share, the share symbol on the folder does not appear after ok, but only after the directory status refresh.

**Comment by joshtrichards** [comment]
Unless I've misunderstood, this appears to be have been addressed. Feel free to let me know if you disagree and I'll re-open. :)
