### ISSUE TITLE
[Bug]: Empty DND user statuses listed on dashboard

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#43089]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The empty user statues ", seconds ago" are back.

This was fixed in https://github.com/nextcloud/server/pull/41512. https://github.com/nextcloud/server/pull/41714/files#r1404002684 reverted the fix.

### Steps to reproduce

1. Create two users
2. Set availability for one. Make sure the user is unavailable at the time of testing
3. Flush cron jobs
4. Log in as the other user and look at the dashboard

### Expected behavior

No recent user status

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ChristophWurst** [comment]
Bringing back the 0 timestamp in `\OCA\UserStatus\Service\StatusService::setUserStatus` seems to do the trick. Didn't test for any other side effects of this

**Comment by miaulalala** [comment]
> Bringing back the 0 timestamp in `\OCA\UserStatus\Service\StatusService::setUserStatus` seems to do the trick. Didn't test for any other side effects of this

I don't understand what 0 timetamp you're referring to?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/pull/41512
