### ISSUE TITLE
[Bug]: Sorting of files and folders inconsistent in Web UI

### ISSUE THREAD

**Issue by alexs77** [nextcloud/server#43083]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

- When I **sort** files and folders in the Web UI nextcloud/server, folders are shown before files.
- When I **sort by date or size**, folders are NOT shown before files.

This does not make sense to me. In all use cases, folders should or should not be sorted before files. I'd prefer to see folders first all the time, but I expect this behaviour to be consistent and not depending on whether contents are sorted by name or something else.

### Steps to reproduce

1. Have a folder with subfolders and files
2. Sort by name
3. Sort by date

### Expected behavior

In both cases (sorted by name or sorted by date), folders should be shown before files. It would also be fine, if in both cases folders should not be shown before files. It needs to be consistent.

### Installation method

Official All-in-One appliance

### Nextcloud Server version

28

**Comment by szaimen** [comment]
Cc @nextcloud/server-frontend
