### ISSUE TITLE
[Bug]: "Clear status after" has no effect

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#43100]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Overwriting the status clearance (for predefined) messages no longer works. The default value will always be used.

For *Working remotely*, my status will always reset at midnight.

### Steps to reproduce

1. Open the status modal
2. Click *Working remotely*
3. (See a network request saving the status instantly)
4. Change *Clear status after* from *Today* to *Don't clear*

### Expected behavior

My status is never cleared.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Regression of https://github.com/nextcloud/server/commit/86ddc3f3bb1d7d29f68008e90a7f591672a896e1 @Pytal?

cc @Antreesy as user_status frontend engineer

**Comment by Pytal** [comment]
Regression is from https://github.com/nextcloud/server/pull/38832
