### ISSUE TITLE
[Bug]: Nextcloud 28 don't send notification when accept a meeting

### ISSUE THREAD

**Issue by section1** [nextcloud/server#43115]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Using the calendar app in the web interface when i create a meeting with UserB as guest, the calendar server send the invitation notification...As UserB i go to the calendar app in the web and i accept the meeting the calendar DON'T send the email notification saying that the meeting was accepted. Both users in the same instance.

In version 27.x this works fine. I receive an email when meetings are accepted.

 

### Steps to reproduce

1. Log as UserA to Nextcloud and create a meeting with UserB.
2. Email invitation of the new meeting arrives to UserB
3. Log as UserB in NC and accept that meeting in the calendar.

### Expected behavior

An email notification deliver to UserA saying that UserB accepted the meeting.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.1.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "skeletondirectory": "",
        "defaultapp": "calendar",
        "session_lifetime": 14400,
        "remember_login_cookie_lifetime": 172800,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - calendar: 4.6.4
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - contactsinteraction: 1.9.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - systemtags: 1.18.0
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_ldap: 1.19.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - activity: 2.20.0 (installed 2.20.0)
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - comments: 1.18.0 (installed 1.18.0)
  - dashboard: 7.8.0 (installed 7.8.0)
  - encryption: 2.16.0
  - files_external: 1.20.0
  - files_pdfviewer: 2.9.0 (installed 2.9.0)
  - files_reminders: 1.1.0 (installed 1.1.0)
  - files_sharing: 1.20.0 (installed 1.20.0)
  - firstrunwizard: 2.17.0 (installed 2.17.0)
  - photos: 2.4.0 (installed 2.4.0)
  - recommendations: 2.0.0 (installed 2.0.0)
  - sharebymail: 1.18.0 (installed 1.18.0)
  - support: 1.11.0 (installed 1.11.0)
  - survey_client: 1.16.0 (installed 1.16.0)
  - suspicious_login: 6.0.0
  - text: 3.9.1 (installed 3.9.1)
  - twofactor_totp: 10.0.0-beta.2
  - weather_status: 1.8.0 (installed 1.8.0)
```

**Comment by ChristophWurst** [comment]
> In version 27.x this works fine. I receive an email when meetings are accepted.

I doubt that it is the same workflow. As far as I know Nextcloud never sent replies for accepted invites when the response happened through the HTML button in the invitation email or someone used the Calendar app to respond on web.
Only when someone uses an external client, like Thunderbird, there is a response email.

**Comment by section1** [comment]
Im doing a test right now with NC 27.1.6 when i accept the event from here:

![image](https://github.com/nextcloud/server/assets/8985108/3071db6b-729e-445e-99bf-4287a552a673)

The userA receive this email notification:

![image](https://github.com/nextcloud/server/assets/8985108/eb6d1cc6-8362-40c6-8efa-c57d779475d8)

**Comment by section1** [comment]
Hi i have news ... today i test 27.1.5 and breaks this reply notifications... reading the changelog i see something that maybe it's related to this regression:

**Comment by ChristophWurst** [comment]
https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html#reverting-a-patch

**Comment by section1** [comment]
many thanks for the link... i will do that and get back with the result... but i append a log that i found relatable.

`REDACTED,"user":"My_User","app":"dav","method":"PUT","url":"/remote.php/dav/calendars/My_User/personal/sabredav-1e99337b-5d82-4ba1-8a76-44ef8405d984.ics","message":"Could not find recipient myemail@mydomain.tl as attendee for event with UID f649542e-d4c4-4abb-8a6a-a2ef6f9f5a81","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0","version":"27.1.5.1","data":{"app":"dav"}} 
`

**Comment by section1** [comment]
Ok i can confirm that without this patch( https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/41315.patch ) works as expected... and i see the email send it in the debug logs.

`REDACTED,"user":"My_User","app":"core","method":"PUT","url":"/remote.php/dav/calendars/My_User/personal/sabredav-79ac2cc1-4b29-4594-9aa1-d918afa61bca.ics","message":"Sent mail to \"Array\n(\n    [myser@mydomain.tld] => User\n)\n\" with subject \"Re: 13\"","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:120.0) Gecko/20100101 Firefox/120.0","version":"27.1.5.1","data":{"app":"core"}}`

**Comment by ChristophWurst** [comment]
Thanks for testing @section1!

Could you share the ics of the event you reproduced this with? Redact any sensitive data like your email or the description of the event.

https://docs.nextcloud.com/server/stable/user_manual/en/groupware/calendar.html#edit-duplicate-or-delete-an-event
