### ISSUE TITLE
Dialogues are not localised in full

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#43138]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Despite of added localisation to transifex of Nextcloud vue library and Nextcloud dialogs library, and reviewing, the dialogues in webUI still remain not localised in full, in particular, copying/moving files window, requesting passwords to setup an app etc. This goes from version to version.

### Steps to reproduce

Dialogs and prompts are not localised in full.

### Expected behavior

See example:
![image](https://github.com/nextcloud/server/assets/5199030/a1fb054d-1088-4347-92b9-d676b7947c28)

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Fixed in #43216
