### ISSUE TITLE
[Bug]: Contents inside shared directory can be "Unshared" but are effectively deleted

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#43130]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Inside a shared folder I can trigger an *Unshare* of of all files/folders. When I execute the action, the files are **deleted** for the sharerer.

![image](https://github.com/nextcloud/server/assets/1374172/3803f598-c3fd-434c-aef4-000a28196683)

*Unshare* should only be shown for the element that is shared, not it's children.

### Steps to reproduce

1. Create user1 and user2
2. Create "Shared folder" as user1
3. Upload a picture into "Shared folder" as user1
4. Share "Shared folder" with user2
5. Log in as user2
6. Go to "Shared folder"
7. Open the actions menu of the picture
8. Click *Unshare* (and note how there is no *Delete*)
9. Log in as user1
10. Open "Shared folder"

### Expected behavior

The picture is still there because user2 only unshared but didn't delete. At least that is what the UI says.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ChristophWurst** [comment]
Tested on 28.0.2 RC2 and ddc22c857ea699f55a02f780660a1ca609c44fca. cc @sorbaugh

**Comment by sorbaugh** [comment]
Thanks for reporting this. @Fenn-CS for some reason Unshare is behaving like Delete (and Delete is missing).

**Comment by szaimen** [comment]
also cc @nextcloud/server-frontend

**Comment by netzpolitikorg** [comment]
we can reproduce, too :sob:

**Comment by skjnldsv** [comment]
It's my fault https://github.com/nextcloud/server/pull/42584

- if a file doesn't belong to you AND is shared: it's `Unshare`
- if a file doesn't belong to you AND is not shared, it's probably a file within a shared folder and then, it should be `Delete`

But it's only a visual cue, there's no backend change
