### ISSUE TITLE
Embed or optionally replace images in mail notifications

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#43156]
My nc instance is hosted in local domain. That means, that it is not reachable outside. I enabled sending mail notifications on specific events, eg when some release update is available. The emails I am receiving doesn't contain images, as they are referring to the local domain, but Google cannot interpret the local links and show images. 

![image](https://github.com/nextcloud/server/assets/5199030/5fbc28d9-1e57-4cc6-b126-52358d5b0be0)

Is that possible either embed the images as binaries to the emails or let a user do not show the images or replace them with some text?

Thanks!

**Comment by joshtrichards** [comment]
Duplicate of #13557 

And unfortunately embedding images is not an option with major email providers (like gmail).
