### ISSUE TITLE
[Bug]: nextcloud 28.0.2 rc4 breaks passwords for applications (WEBDAV also)

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#43168]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

[Bug]: nextcloud 28.0.2 rc4 breaks passwords for applications (WEBDAV also) 
in practice, old application passwords no longer allow access and creating new ones solves the problem

### Steps to reproduce

1. create password for application

copy password generated

configure url with webdav

### Expected behavior

I would expect nextcloud to give access to folders via webdav having 2fa enabled

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [X] SSO - SAML
- [X] Other

### Nextcloud Signing status

```shell
.
```

### Nextcloud Logs

```shell
.
```

### Additional info

.

**Comment by szaimen** [comment]
Cc @provokateurin

**Comment by tigernero79** [comment]
after restarting the server and restarting qnap for webdav hysinc backup the situation was resolved.

I close the problem
