### ISSUE TITLE
[Bug]: After moving files to a new drive the changes in web are not synced back to client and the shares are lost 

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#43197]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi! I have moved files from the old drive to a new one with preserving the attributes, timestamps command
`tar cf - my_data | (cd /media/my_data; sudo tar xf - )`
After rescanning files I found that
1. I have lost **all** shares
2. the syncing appeared to be broken: so, if I create a file in web it is not synced by the desktop client with local pc. However, it works back: when I create a file at local pc, it is synced at web.

When I return back everything is fine.

Where is the culprit? Perhaps the path is hardcoded somewhere? (in db or elsewhere?) How to move the data securely from one hard drive to another one?

UPD: I am using groupfolders.

### Steps to reproduce

1. Enable maintenance mode
2. Copy files from the old hard drive to a new one with preserving attributes and timestamps
3. Disable maintenance
4. Rescan files
5. Observe that the shares are lost
6. Observe that the syncing is broken

### Expected behavior

Moving data should be safe enough.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
It sounds like you may have overlooked the steps required to move your data directory:

https://docs.nextcloud.com/server/latest/admin_manual/issues/general_troubleshooting.html#troubleshooting-data-directory

**Comment by ostasevych** [comment]
> It sounds like you may have overlooked the steps required to move your data directory:
> 
> https://docs.nextcloud.com/server/latest/admin_manual/issues/general_troubleshooting.html#troubleshooting-data-directory

> **Unofficially moving the data directory can be done as follows:**
> 1. Make sure no cron jobs are running
> 2. Stop apache
> 3. Move /data to the new location
> 4. Change the config.php entry
> 5. Edit the database: In oc_storages change the path on the local::/old-data-dir/ entry

This is the most interesting, as I've inspected this table and found the following results:
MariaDB [nextcloud]> select * from oc_storages;

```
+------------+--------------------------------------+-----------+--------------+
| numeric_id | id                                   | available | last_checked |
+------------+--------------------------------------+-----------+--------------+
|          1 | local::/var/www/nextcloud/my_data/      |         1 |         NULL |
|          2 | home::admin1                          |         1 |         NULL |
|          3 | local::/var/www/html/nextcloud/my_data/ |         1 |         NULL |
|          4 | home::admin2                         |         1 |         NULL |
|          5 | local::/media/cloud/nextcloud/my_data/ |         1 |         NULL |
|          6 | local::/media/nextcloud/my_data/         |         1 |         NULL |
...
|         45 | local::/media/backup/ncdata/         |         1 |         NULL |
|         58 | a24454dbc5d98832e0e0b60c5f09060d29     |         1 |         NULL |
...
|         59 | home::szulfuharov                    |         1 |         NULL |
|         60 | home::izhahaliak                     |         1 |         NULL |
|         61 | home::vkrupiak                       |         1 |         NULL |
|         62 | home::vpirus                         |         1 |         NULL |
|         63 | local::/media/my_data/                |         1 |         NULL
```
So, there's already correct location present in the table oc_storages (the old one is 6 (/media/nextcloud/my_data) and the new one is the last one 63 (/media/my_data). So, NC adds this entry after changing the config.php Should I remove other records?

> 6. Ensure permissions are still correct
> 7. Restart apache
> 

Amongst other advice I see:
> try these 2 commands :
> occ files:scan --all
> occ files:repair-tree
