### ISSUE TITLE
Call to undefined method OCP\\Defaults::shouldReplaceIcons()

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#4319]
On current master when trying to login on a new installed instance I get this:

> {"reqId":"WO3tIX8AAQEAAAzBKDgAAAAH","remoteAddr":"10.211.55.2","app":"index","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to undefined method OCP\\\\Defaults::shouldReplaceIcons()\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\Theming\\\\Controller\\\\IconController->getFavicon('core')\\n#1 \\\/media\\\/psf\\\/stable9\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#2 \\\/media\\\/psf\\\/stable9\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Theming\\\\Controller\\\\IconController), 'getFavicon')\\n#3 \\\/media\\\/psf\\\/stable9\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Theming\\\\Controller\\\\IconController), 'getFavicon')\\n#4 \\\/media\\\/psf\\\/stable9\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Theming\\\\\\\\Con...', 'getFavicon', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#5 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#6 \\\/media\\\/psf\\\/stable9\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#7 \\\/media\\\/psf\\\/stable9\\\/lib\\\/base.php(970): OC\\\\Route\\\\Router->match('\\\/apps\\\/theming\\\/f...')\\n#8 \\\/media\\\/psf\\\/stable9\\\/index.php(40): OC::handleRequest()\\n#9 {main}\",\"File\":\"\\\/media\\\/psf\\\/stable9\\\/apps\\\/theming\\\/lib\\\/Controller\\\/IconController.php\",\"Line\":126}","level":3,"time":"2017-04-12T09:02:26+00:00","method":"GET","url":"\/stable9\/index.php\/apps\/theming\/favicon?v=0","user":"--","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/57.0.2987.133 Safari\/537.36","version":"12.0.0.14"}

**Comment by LukasReschke** [comment]
@MorrisJobke Any idea on how to best address this? Not sure if we should add that to OCP as well.

**Comment by MorrisJobke** [comment]
Let me look into this

**Comment by rullzer** [comment]
I think the solution here is to have the theming app use the correct class.
