### ISSUE TITLE
[Bug]: NC28.0.1 Can not move or copy into folders using Recent or favorites links

### ISSUE THREAD

**Issue by iAm-teapot** [nextcloud/server#43205]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Description
When one wants to move one or several files, using the "Move or copy" actions, then Recent or Favourites sections, then the transfer/copy does not work.
If the destination folder is at the root level, the "Move or Copy" action works as expected. I noticed, the path is not the same, if we navigate to the path from the root or if we use the Recent_or_Favorites sections.
#### Navigation from root:
![image](https://github.com/nextcloud/server/assets/158160657/61e50b9f-8b38-4df5-9ecc-6d8af187cded)
#### Navigation using recent (copy and move buttons should not be visible, by the way, since, Recent is not a folder where to move the files/folders, but a logical group):
![image](https://github.com/nextcloud/server/assets/158160657/8b5ada73-bb61-4682-9ad9-07fc89f25b10)
then (note the path on the top which is missing "Documents" level):
![image](https://github.com/nextcloud/server/assets/158160657/e0bc9874-529f-4cbf-8486-1a25c05b94ff)

Some extra information:
* Move or copy: tested using the "3 dots menu" for a single file and the action button for multi selection
* Tested with copy file(s), move file(s), copy folder(s) and move folder(s)
* Tested on a fresh aio installation

### Results of my searches (probably linked, but symptoms are different):
- https://github.com/nextcloud/server/issues/42009
- https://github.com/nextcloud/server/issues/42564

### Steps to reproduce

I describe only for "Recent", but the problem exists also for "Favourites"
1. Create 1 sub-folder (not at the root level)
2. Select a file
3. Click the button "Move or Copy"
4. Click in "Recent" 
5. Click the created folder in Step 1
6. Click the button "Move to Folder_chosen_name_in_step_1"

### FOUND behavior (the propfind is missing the containing path structure):
![image](https://github.com/nextcloud/server/assets/158160657/dc3ddb9e-8737-4052-babb-cc61c6dafc6e)
and
![image](https://github.com/nextcloud/server/assets/158160657/acb3cd83-068d-48e4-8cf8-ba3630a8e6ad)

### EXPECTED behavior:
![image](https://github.com/nextcloud/server/assets/158160657/a3de395c-cba3-400f-8b0f-79febd113d25)
and
![image](https://github.com/nextcloud/server/assets/158160657/a62ff4d5-23db-4138-b634-9b5388c8b2fe)

### Installation method

Official All-in-One appliance

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "one-click-instance": true,
        "one-click-instance.user-limit": 100,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "appsallowlist": [],
        "check_data_directory_permissions": false,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "overwritehost": "plif.plaf.com",
        "overwriteprotocol": "https",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "plif.plaf.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "28.0.1.1",
        "overwrite.cli.url": "https:\/\/plif.plaf.com\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updatedirectory": "\/nc-updater",
        "loglevel": "2",
        "app_install_overwrite": [
            "nextcloud-aio"
        ],
        "log_type": "file",
        "logfile": "\/var\/www\/html\/data\/nextcloud.log",
        "log_rotate_size": "10485760",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "enabledPreviewProviders": {
            "1": "OC\\Preview\\Image",
            "2": "OC\\Preview\\MarkDown",
            "3": "OC\\Preview\\MP3",
            "4": "OC\\Preview\\TXT",
            "5": "OC\\Preview\\OpenDocument",
            "6": "OC\\Preview\\Movie",
            "7": "OC\\Preview\\Krita",
            "0": "OC\\Preview\\Imaginary"
        },
        "enable_previews": true,
        "upgrade.disable-web": true,
        "mail_smtpmode": "smtp",
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 30",
        "activity_expire_days": "30",
        "simpleSignUpLink.shown": false,
        "share_folder": "\/Shared",
        "one-click-instance.link": "https:\/\/nextcloud.com\/all-in-one\/",
        "upgrade.cli-upgrade-link": "https:\/\/github.com\/nextcloud\/all-in-one\/discussions\/2726",
        "allow_local_remote_servers": true,
        "davstorage.request_timeout": 3600,
        "htaccess.RewriteBase": "\/",
        "dbpersistent": false,
        "files_external_allow_create_new_local": false,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "preview_imaginary_url": "http:\/\/nextcloud-aio-imaginary:9000"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - appointments: 1.15.5
  - calendar: 4.6.4
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.1
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - deck: 1.12.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_antivirus: 5.4.1
  - files_fulltextsearch: 28.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - forms: 4.0.0
  - fulltextsearch: 28.0.0
  - fulltextsearch_elasticsearch: 28.0.0
  - groupfolders: 16.0.3
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - maps: 1.3.1
  - nextcloud-aio: 0.4.0
  - nextcloud_announcements: 1.17.0
  - notes: 4.9.2
  - notifications: 2.16.0
  - notify_push: 0.6.8
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - polls: 6.0.1
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recognize: 6.0.1
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - richdocuments: 8.3.1
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - spreed: 18.0.1
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - tasks: 0.15.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - bruteforcesettings: 2.8.0
  - circles: 28.0.0-dev (installed 28.0.0-dev)
  - encryption: 2.16.0
  - files_external: 1.20.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - suspicious_login: 6.0.0
  - user_ldap: 1.19.0
```

### Nextcloud Signing status

```shell
<html><head><link rel="stylesheet" href="resource://content-accessible/plaintext.css"></head><body><pre>No errors have been found.</pre></body></html>
```

### Nextcloud Logs

```shell
There are no logs from today. Only entries are from previous days, when I installed the instance. There are my domain in it and do not want to provide it or take the effort to anonymize the logs.
```

### Additional info

I really think, that the problem is that using the recent or favorite sections, the path of destination folder is "lost" and the frontend will try with a folder with the same name in the root folder.

**Comment by susnux** [comment]
Already handled by https://github.com/nextcloud/server/pull/42994 so this will be fixed in 28.0.2
