### ISSUE TITLE
[Bug]: ocs/v2.php/core/navigation/apps?absolute=true returns invalid url

### ISSUE THREAD

**Issue by camilasan** [nextcloud/server#43204]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In Nextcloud 26, with the app [nextcloud/external](https://github.com/nextcloud/external) - I have consulted @provokateurin about it - if I request:
`curl -u user:pwd -X GET 'http://stable26.local/ocs/v2.php/core/navigation/apps?absolute=true' -H "OCS-APIRequest: true"`

It returns:
`<href>http://stable26.local/https://duckduckgo.com</href>`

If I request without `absolute=true` then I get:
`<href>https://duckduckgo.com</href>`

### Steps to reproduce

1. Install the External Sites app
2. Add *2* urls - somehow, the issue was only reproducible after adding a second link. 

### Expected behavior

`ocs/v2.php/core/navigation/apps?absolute=true` should return a valid url in `href`.

### Installation method

Community Docker image

### Nextcloud Server version

26

### Operating system

Debian/Ubuntu

### PHP engine version

Other

### Web server

Nginx

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other

**Comment by sorbaugh** [comment]
@come-nc I'm uncertain if the issue is on the external_sites app itself or if it's a server/core issue. What do you think?

**Comment by sorbaugh** [comment]
> I had a look at the code in the external app and it adds the href as-is to the navigation entries. It should be verified that this also is received correctly on the server site, but I'm pretty sure it is.

Yes then it sounds like a server/core issue
