### ISSUE TITLE
[BITV]: Versions: The element button must not appear as a descendant of the a element.

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/server#43237]
![Screenshot from 2024-01-31 17-08-20](https://github.com/nextcloud/server/assets/6078378/f37f5e62-ac56-40e9-b39f-70ab5d3cee42)

Not a valid HTML. Action buttons can't be inside of the links. 

- [ ] Existing links should not be implemented as links because they are linking themselves 
- [ ] ToDo: provide support of `NcListItem` for not_links

**Comment by JuliaKirschenheuter** [comment]
No "pending dependency update" anymore. Closing issue

**Comment by szaimen** [comment]
Do we have any place in our default set of applications where I could check this?
