### ISSUE TITLE
Add option to disable page zooming in mobile browsers

### ISSUE THREAD

**Issue by the-dipsy** [nextcloud/server#43235]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When using the web version of Nextcloud on a mobile browser (tested on iOS 17.2.1), the ability to zoom in and the browsers automatic zooming when using input elements makes the operation of the page pretty cumbersome, especially when zooming out to far leads to page reloading. Without zooming the page would mostly behave like a native app.

**Describe the solution you'd like**
Add an option to disable page zooming on mobile devices for the entire instance and for individual users.

**Describe alternatives you've considered**
As a workaround the outdated but still functional jsloader app can be used to fix this problem with the Javascript code `document.head.querySelector("meta[name=viewport]").content += ", user-scalable=no"`.

**Comment by juliushaertl** [comment]
Fixed by https://github.com/nextcloud/server/pull/47371

**Comment by the-dipsy** [comment]
I haven't tried it but the pull request reads like manual zooming is still possible on iOS, right?

**Comment by juliushaertl** [comment]
Yes.
