### ISSUE TITLE
Filters in the file list

### ISSUE THREAD

**Issue by nimishavijay** [nextcloud/server#43241]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

---

**Is your feature request related to a problem? Please describe.**
Scanning through a long file list when you are looking for specific files or folders can be tedious.

**Describe the solution you'd like**
It would nice to have a way to filter the file list quickly, with some predefined filters, like only spreadsheets, or starred items, or modified in the last week, or shared by your manager, for example.

**Additional context**
Also came up in the [Files gap analysis](https://github.com/nextcloud/server/issues/43238). Google Drive and Dropbox have different versions of this feature

Gdrive (home page)
![image](https://github.com/nextcloud/server/assets/52440189/f8c2b835-c50e-46a2-bd79-7fb64f20a8a7)

Gdrive (root folder): similar filters as the advanced search in NC
![image](https://github.com/nextcloud/server/assets/52440189/1176ba3f-f875-4d6b-b338-1b96ef2a972c)

Dropbox: has recents and favourites
![image](https://github.com/nextcloud/server/assets/52440189/738c6f53-99ea-4e99-98be-96d5825328cb)

cc @sorbaugh @jancborchardt

**Comment by jancborchardt** [comment]
Closing as this was resolved via a duplicate issue https://github.com/nextcloud/server/issues/45437
