### ISSUE TITLE
[Bug]: No more files after update to 28.0.2

### ISSUE THREAD

**Issue by leuedaniel** [nextcloud/server#43269]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After the update from 28.0.1 to 28.0.2, the group folders in the files were no longer displayed. Instead of the "New" button, there was an "Add" button. However, the button could not be clicked, so I rule out a Groupfolders problem as it generally no longer worked. After going back to 28.0.1 and a DB restore it works again and files can be uploaded again. The behavior is the same with php8.2 and php8.3.

### Steps to reproduce

1. update from 28.0.1 to 28.0.2
2. open Nextcloud Files in the browser
3. an "Add" button (up to 28.0.1 "New") is displayed
4. the button cannot be clicked and no new files or folders can be created

### Expected behavior

The group folders should be displayed and you should be able to create new folders or files using the "Add" button.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Unfortunately, I had to switch to the previous version immediately as it is a productive system.

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.hgverwaltung.ch"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.1.1",
        "overwrite.cli.url": "https:\/\/cloud.hgverwaltung.ch",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "filelocking.ttl": 3600,
        "default_language": "de",
        "force_language": "de",
        "default_locale": "de-ch",
        "force_locale": "de-ch",
        "skeletondirectory": "",
        "knowledgebaseenabled": false,
        "updater.release.channel": "stable",
        "default_phone_region": "CH",
        "app_install_overwrite": [
            "user_sql",
            "files_trackdownloads",
            "files_antivirus",
            "user_backend_sql_raw",
            "activity"
        ],
        "data-fingerprint": "fd880a1281a2f40887e135eaa81bc8d4",
        "maintenance_window_start": "1",
        "lost_password_link": "https:\/\/hgverwaltung.ch\/#\/password-reset",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": ""
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - announcementcenter: 6.7.0
  - bruteforcesettings: 2.8.0
  - cloud_federation_api: 1.11.0
  - dav: 1.29.1
  - external: 5.3.1
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_antivirus: 5.4.1
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - groupfolders: 16.0.3
  - impersonate: 1.15.0
  - login_notes: 1.4.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - notify_push: 0.6.9
  - oauth2: 1.16.3
  - previewgenerator: 5.4.0
  - provisioning_api: 1.18.0
  - quota_warning: 1.18.0
  - related_resources: 1.3.0
  - richdocuments: 8.3.1
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - suspicious_login: 6.0.0
  - terms_of_service: 2.3.2
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_sql: 4.7.1
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - circles: 28.0.0-dev (installed 27.0.1)
  - comments: 1.18.0 (installed 1.11.0)
  - contactsinteraction: 1.9.0 (installed 1.2.0)
  - dashboard: 7.8.0 (installed 7.1.0)
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 1.11.0)
  - files_external: 1.20.0
  - firstrunwizard: 2.17.0 (installed 2.10.0)
  - password_policy: 1.18.0 (installed 1.11.0)
  - photos: 2.4.0 (installed 1.2.3)
  - privacy: 1.12.0 (installed 1.6.0)
  - recommendations: 2.0.0 (installed 1.0.0)
  - support: 1.11.0 (installed 1.3.0)
  - survey_client: 1.16.0 (installed 1.9.0)
  - systemtags: 1.18.0 (installed 1.11.0)
  - text: 3.9.1 (installed 3.2.0)
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0
  - user_status: 1.8.1 (installed 1.1.1)
  - weather_status: 1.8.0 (installed 1.1.0)
```

### Nextcloud Logs

```shell
The log files did not show an error and no entry was written because I could not click the button to create a new file.
```

### Additional info

I could run the update again in a maintenance window to analyze the error.

**Comment by francoisautin** [comment]
Suffering from the same issue, JS console displays the following error messages:

```
[ERROR] files: Header workspace already registered 
Object { app: "files", uid: "21341", level: 0, header: {…} }
ConsoleLogger.js:74:18
    value ConsoleLogger.js:74
    value ConsoleLogger.js:100
    j index.mjs:301
    <anonymous> files.js:61
```

```
[ERROR] files: Error while fetching content 
Object { app: "files", uid: "21341", level: 0, error: Error }
​
app: "files"
​
error: Error: Invalid owner type
​​
columnNumber: 88943
​​
fileName: "https://cloud.cuwott.fr/dist/files-init.js?v=585b0d71-0"
​​
lineNumber: 2
​​
message: "Invalid owner type"
​​
stack: "I@https://cloud.cuwott.fr/dist/files-init.js?v=585b0d71-0:2:88943\nS@https://cloud.cuwott.fr/dist/files-init.js?v=585b0d71-0:2:89783\nL@https://cloud.cuwott.fr/dist/files-init.js?v=585b0d71-0:2:91936\nQe@https://cloud.cuwott.fr/dist/files-init.js?v=585b0d71-0:2:19895\n34507/getContents/<@https://cloud.cuwott.fr/dist/files-init.js?v=585b0d71-0:2:30934\n"
​​
<prototype>: Error.prototype { stack: "", … }
​​​
constructor: function Error()
​​​
message: ""
​​​
name: "Error"
​​​
stack: ""
​​​
toString: function toString()
​​​
<get stack()>: function stack()
​​​
<set stack()>: function stack()
​​​
<prototype>: Object { … }
​
level: 0
​
uid: "21341"
​
<prototype>: Object { … }
ConsoleLogger.js:74:18
    value ConsoleLogger.js:74
    value ConsoleLogger.js:100
    fetchContent files-main.js:2

```

**Comment by 7408647n** [comment]
I have the same error. And also the same error message in the browser console. But only in the browser. All folders and files are visible in the Nextcloud app.

**Comment by Ducknuke** [comment]
Is this the same problem? : 
https://github.com/nextcloud/text/issues/5332

**Comment by Ducknuke** [comment]
![2024-02-02 11_47_14-Fichiers - Nextcloud](https://github.com/nextcloud/server/assets/89637250/f29f0684-42f8-430b-b2c1-31b11243da6b)

Same issue here files Dashboard and/or files application is broken for me since 28.0.1 to 28.0.2.5

access.log : "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 0 "https://nextcloud.xxxxxxx.fr/apps/files/files" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36"

If I use my android phone using the nextcloud application files application works.

**Comment by michmoor0725** [comment]
oh goodness im glad im not alone in this. This is my exact same problem.
If i check my /data/userID directory i see my files so they are not gone. They are just not displayed in the Files App. Also i can no longer access any external storage. 
"External mount error
There was an error with this external storage. Do you want to review this mount point config in the settings page?"

**Comment by Ducknuke** [comment]
> oh goodness im glad im not alone in this. This is my exact same problem. If i check my /data/userID directory i see my files so they are not gone. They are just not displayed in the Files App. Also i can no longer access any external storage. "External mount error There was an error with this external storage. Do you want to review this mount point config in the settings page?"

Yes because if you use photos you can find your files, it is therefore "File" which cannot display our folder/files
I hope we will have a correction quickly because I can no longer use it on a browser (80% of my time)

**Comment by max-nextcloud** [comment]
To narrow this down... is everyone affected using the groupfolders app as mentioned in the title?

**Comment by michmoor0725** [comment]
I will also add that the iOS app for me displays no items in my files.
Someone mentioned the Android app is fine. So thats an interesting datapoint as well.

Lastly here is data from my browser

![image](https://github.com/nextcloud/server/assets/47565104/d5fc0253-66dc-4023-99c9-df1d612d1893)

**Comment by max-nextcloud** [comment]
> Lastly here is data from my browser

Looks like there is a 500 response to the propfind (2nd and 3rd error). This should result in an error log entry. Could you try and look for that log message in your `nextcloud.log` file?

**Comment by max-nextcloud** [comment]
I wonder if any of this is related to old browser state (cached scripts, left over data in local storage, etc.)

Could you check if it's fixed by
* a force reload (`ctrl-shift-R` in most browsers)?
* logging in in a private / incognito window?

**Comment by sorbaugh** [comment]
Cc @nextcloud/server-frontend

**Comment by michmoor0725** [comment]
1. force reload did not work. Using chrome. Tried in FF and the same issue is there.
2. Incognito mode in Chrome has the same problem

PROPFIND in the nextcloud log shows old entries, nothing from today.

`cat nextcloud.log | grep -i PROPFIND
{"reqId":"rTvUvYmO2cvKODNRSXR5","level":2,"time":"2024-01-22T05:00:09+00:00","remoteAddr":"10.6.106.2","user":"--","app":"core","method":"PROPFIND","url":"/remote.php/dav/files/michael/","message":"Login failed: 'michael' (Remote IP: '10.6.106.2')","userAgent":"OPNsense Firewall","version":"28.0.1.1","data":{"app":"core"}}
{"reqId":"q39PJTxwKaZJwFWa5ypv","level":2,"time":"2024-01-22T05:00:10+00:00","remoteAddr":"10.6.106.2","user":"--","app":"core","method":"PROPFIND","url":"/remote.php/dav/files/michael/","message":"Login failed: 'michael' (Remote IP: '10.6.106.2')","userAgent":"OPNsense Firewall","version":"28.0.1.1","data":{"app":"core"}}
{"reqId":"cIO1iMXSMa8aWDLHEVh8","level":2,"time":"2024-01-22T06:34:53+00:00","remoteAddr":"10.6.106.2","user":"--","app":"core","method":"PROPFIND","url":"/remote.php/dav/files/michael/","message":"Login failed: 'michael' (Remote IP: '10.6.106.2')","userAgent":"OPNsense Firewall","version":"28.0.1.1","data":{"app":"core"}}
{"reqId":"O5fQdagCYtfSVSqAa0Rq","level":2,"time":"2024-01-22T06:34:58+00:00","remoteAddr":"10.6.106.2","user":"--","app":"core","method":"PROPFIND","url":"/remote.php/dav/files/michael/","message":"Login failed: 'michael' (Remote IP: '10.6.106.2')","userAgent":"OPNsense Firewall","version":"28.0.1.1","data":{"app":"core"}}
`

**Comment by Ducknuke** [comment]
> I wonder if any of this is related to old browser state (cached scripts, left over data in local storage, etc.)
> 
> Could you check if it's fixed by
> 
> * a force reload (`ctrl-shift-R` in most browsers)?
> * logging in in a private / incognito window?

Same thing with Chrome, Edge and a browser on my Samsung never use for nextcloud with logging in a private / incognito mod

**Comment by michmoor0725** [comment]
From Firefox here are the Console errors

![image](https://github.com/nextcloud/server/assets/47565104/f958792f-fdf2-4fbe-80a3-df6b2cc90e73)

**Comment by Ducknuke** [comment]
@michmoor0725 I see that we don't have quite the same error, I have the endless loading circle when I want to display my files while there is a "No files in here" message for you

**Comment by michmoor0725** [comment]
The symptoms are somewhat the same but different error.

I will create a new problem but will be watching this in the meantime.

**Comment by joshtrichards** [comment]
@leuedaniel I read your report as two matters:

> After the update from 28.0.1 to 28.0.2, the group folders in the files were no longer displayed. Instead of the "New" button, there was an "Add" button. However, the button could not be clicked, so I rule out a Groupfolders problem as it generally no longer worked. 

1. Groupfolders no longer visible in the Web UI
2. The *New* button missing 

Can you clarify whether non-groupfolders files were still accessible?

There are others commenting here with issues that may be unrelated to your report.

**Comment by leuedaniel** [comment]
@joshtrichards 
No, even non-groupfolders were no longer visible. I could not create any new files outside the groupfolders either.

**Comment by skjnldsv** [comment]
Okay, I'm gonna try to split things up a bit :)

#### `Error while fetching content: Invalid owner type`
If you're seeing that error, please confirm that your userid is just a number.
e.g.
- Good userid: `admin`, `user123` or `johndoe`
- Bad userid: `235418651`

___
#### `PROPFIND /remote.php/dav/files/michael/ 500 (Internal Server Error)`
<details>
<summary>1. Please do like michael above, and find the matching error in your `data/nextcloud.log`. It should look like this:</summary>
```json
{
    "reqId": "q39PJTxwKaZJwFWa5ypv",
    "level": 2,
    "time": "2024-01-22T05:00:10+00:00",
    "remoteAddr": "10.6.106.2",
    "user": "--",
    "app": "core",
    "method": "PROPFIND",
    "url": "/remote.php/dav/files/michael/",
    "message": "Login failed: 'michael' (Remote IP: '10.6.106.2')",
    "userAgent": "OPNsense Firewall",
    "version": "28.0.1.1",
    "data": {
      "app": "core"
    }
}
```
</details>

<details>
<summary>2. Also post the response of the network request. It should look like this: (post a screenshot after expanding the items OR even BETTER, paste the entire content from the `response` tab</summary>

https://github.com/nextcloud/server/assets/14975046/1821cf2f-a8da-4299-9585-8a32b5d8057f
</details>

**Comment by francoisautin** [comment]
> Okay, I'm gonna try to split things up a bit :)
> 
> #### :one: `Error while fetching content: Invalid owner type`
> If you're seeing that error, please confirm that your userid is just a number.
> e.g.
> - Good userid: `admin`, `user123` or `johndoe`
> - Bad userid: `235418651`
> 
> ___

This error shows up and my userId is indeed wholly numerical.

**Comment by skjnldsv** [comment]
> This error shows up and my userId is indeed wholly numerical.

Ok, this is different than the other issues linked here, so I'm gonna hide both of our messages :)
Two fixes have just been created for your specific issue: 
- https://github.com/nextcloud/server/pull/43318
- https://github.com/nextcloud-libraries/nextcloud-files/pull/882

**Comment by skjnldsv** [comment]
@Ducknuke your issue is also different and only seem to impact favorites.
Can you open the console, and run this for me:
```js
JSON.stringify(OCP.InitialState.loadState('files', 'favoriteFolders', []))
```
Then paste the data here. It should look like this:
```json
[{"fileid":113855,"path":"/1"},{"fileid":113907,"path":"/Collaborators"}]
```

**Comment by Ducknuke** [comment]
> @Ducknuke your issue is also different and only seem to impact favorites. Can you open the console, and run this for me:
> 
> ```js
> JSON.stringify(OCP.InitialState.loadState('files', 'favoriteFolders', []))
> ```
> 
> Then paste the data here. It should look like this:
> 
> ```json
> [{"fileid":113855,"path":"/1"},{"fileid":113907,"path":"/Collaborators"}]
> ```

First of all, thank you very much @skjnldsv  for taking the time to answer me and try to help me because here I am stuck with this error...

The return of what you asked me is a favorites folder in the "/Documents/" folder :
`'["/Documents/PROJET TERRAIN - MAISON"]'`

**Comment by mw171** [comment]
Just disabled "photo sphere viewer" and now all files are again visible.

**Comment by Ducknuke** [comment]
> Just disabled "photo sphere viewer" and now all files are again visible.

@mw171 Not this application on my server : 

root@d291d560a3f2:/#sudo -u abc php app/www/public/occ app:list
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_external: 1.20.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - maps: 1.3.1
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - previewgenerator: 5.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - support: 1.11.0
  - survey_client: 1.16.0
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - encryption: 2.16.0
  - updatenotification: 1.18.0 (installed 1.17.0)
  - user_ldap: 1.19.0

**Comment by Ducknuke** [comment]
Oh my god I just found it...
After 2 days of research... it was you @skjnldsv  who put me on the way.
I removed the folder in question from my favorites and I have the File app working again....

but... If I ever re-add a folder as favorites, it breaks again :/

**Comment by dinand-ginting** [comment]
> Okay, I'm gonna try to split things up a bit :)
> 
> #### 1️⃣ `Error while fetching content: Invalid owner type`
> If you're seeing that error, please confirm that your userid is just a number. EDIT: ⚠️ If so, you can stop interacting with this thread, a fix has been created here: #43318
> 
> #### 2️⃣ `PROPFIND /remote.php/dav/files/michael/ 500 (Internal Server Error)`
> 1. Please do like michael above, and find the matching error in your `data/nextcloud.log`. It should look like this:
> 2. Also post the response of the network request. It should look like this: (post a screenshot after expanding the items OR even BETTER, paste the entire content from the `response` tab)

Hi @skjnldsv . Thank you for your suggestion. I have the first problem, where the userid is just a number. I went to #43318 but in my installation, I don't have the folder apps/files/src. How can I try to apply the fix?

**Comment by skjnldsv** [comment]
@dinand-ginting you cannot. You have to wait for the next update

**Comment by Ducknuke** [comment]
> Oh my god I just found it... After 2 days of research... it was you @skjnldsv who put me on the way. I removed the folder in question from my favorites and I have the File app working again....
> 
> but... If I ever re-add a folder as favorites, it breaks again and with any other folder :/ and still the same text-file error in the chrome console : ![image](https://private-user-images.githubusercontent.com/89637250/302050600-3472f879-2517-42dc-a79a-b646b916315b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMjc4MDksIm5iZiI6MTcwNzEyNzUwOSwicGF0aCI6Ii84OTYzNzI1MC8zMDIwNTA2MDAtMzQ3MmY4NzktMjUxNy00MmRjLWE3OWEtYjY0NmI5MTYzMTViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDEwMDUwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0NjBmMDA0YzZjMjFjOGQyMjcyNzIwMTY4MjFkZDgwODUxN2ZkZTE3OTVjZDE0MjFmZWU2YjA2MmQ3M2FjYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pA-PhVXNAvl2PGEfZFfkofiHU5XR6n-34fACOxZmKwE) I seem to have seen this error on other discussions and I don't know if it's related

![2024-02-05 11_06_06-Window](https://github.com/nextcloud/server/assets/89637250/9b3db3c4-ce5b-41b7-9591-adc03e438ad8)
My error probably comes from the favorites. I will open a new issue.

**Comment by skjnldsv** [comment]
@Ducknuke no, this is the same error you are experiencing.  You can ignore the duplicate header one, there is already one opened ticket and this is NOT what is making the files list empty :)

**Comment by Ducknuke** [comment]
> @Ducknuke no, this is the same error you are experiencing. You can ignore the duplicate header one, there is [already one opened ticket](https://github.com/nextcloud/text/issues/5332) and this is NOT what is making the files list empty :)

Are you sure @skjnldsv that my broken “Favorites” error (files-init.js) is the same problem as the one mentioned above?
I don't want to open a bug if it's dealt with elsewhere. 
I also have the error text-files.js (the duplicate header) but it will apparently be addressed in a future version.
Thank you for your information and help

**Comment by skjnldsv** [comment]
@Ducknuke your favorites issues is part of the 28.0.2 release.
So I'm surprised you're experiencing it.
https://github.com/nextcloud/server/pull/43119/commits/3add75cd16a0a41a4f7c2686d5d6044664ab4995

**Comment by JB1985** [comment]
> Okay, I'm gonna try to split things up a bit :)
> #### 1️⃣ `Error while fetching content: Invalid owner type`
> 
> If you're seeing that error, please confirm that your userid is just a number. EDIT: ⚠️ If so, you can stop interacting with this thread, a fix has been created here: #43318 

Can you explane how to fix this bug, please? I can no longer use my cloud because I can't see any data.

**Comment by skjnldsv** [comment]
> Can you explane how to fix this bug, please? I can no longer use my cloud because I can't see any data.

Roll back to a previous version

**Comment by JB1985** [comment]
Not working: Downgrading is not supported and is likely to cause unpredictable issues (from 28.0.2.5 to 28.0.1.1) 

Can you release a RC please?

**Comment by susnux** [comment]
If a update renders your instance unusable I recommend to gather the logs for reporting and then rollback the backups you did before.

**Comment by JB1985** [comment]
However, the backup would be too old and would overwrite too much data. That's not an option.

**Comment by joshtrichards** [comment]
There will be a new release in a few weeks: https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

Alternatively you can try to find someone to help you patch this yourself (e.g. on help forum: https://help.nextcloud.com) or get an enterprise subscription from Nextcloud GmbH (https://nextcloud.com/enterprise).

As an aside, both NC27 and NC26 are both fully supported still. There's no need to move to the latest and greatest where, unfortunately this sort of thing is more likely to occur just due to the nature of things. I know that doesn't help you now, but it may be something to consider in the future before upgrading production instances without testing in a staging environment and/or early in release cycles.

**Comment by JB1985** [comment]
With this statement, no one will use current versions in the future. We should be able to expect that if a bug breaks Nextcloud, a hotfix or patch will be released. That was the case in the past. But it probably affects few users who have numeric users.

**Comment by joshtrichards** [comment]
> With this statement, no one will use current versions in the future. 

All three of the major versions I mentioned (v26, v27, v28) are "current versions". What major version to upgrade to and how aggressively to do so is a local/sysadmin decision. The Nextcloud project supports 2-3 major versions at the same time, with the earlier two always being the most mature/field tested.

I'm a sysadmin myself (and also a volunteer within the project). I was pointing out that if you don't have a strategy in place for testing in your specific environment and/or at least having a rollback approach, then perhaps you should explore your update strategy and/or upgrade less aggressively. All supported major versions receive bug fixes and security fixes so there's no downside in many cases to sitting on the middle supported major version (or even the oldest if you prefer to be conservative).

If you want to run the latest major release, well, that's great too. It's entirely up to you.

It's no different than deciding which version of a major Linux distribution to run, even though multiple major versions are supported simultaneously. There are always trade-offs to running the latest/least field tested of any software.

> We should be able to expect that if a bug breaks Nextcloud, a hotfix or patch will be released. That was the case in the past.

The code with the fix is there in the links already mentioned just as is always the case:

- https://github.com/nextcloud/server/pull/43318
- https://github.com/nextcloud-libraries/nextcloud-files/pull/882

**Comment by joshtrichards** [comment]
> I was under the impression, correct me if I am wrong, that the Nextcloud project versioning followed the semantic versioning convention. 

As much as anything does, sure.

> Since this bug was introduced between 28.0.1 and 28.0.2, it means it was introduced at a patch level, hence, running 26.x.x or 27.x.x seemingly wouldn't have shielded anyone from such a bug being introduced

I know of nothing in semantic versioning that suggests that minor/patch levels are symmetrical across major versions. You can't compare the minor or patch levels across major version boundaries.

That wouldn't make much sense: after all major versions introduce breaking changes and new APIs. The bugs that arise in new major versions often can't exist in older major release trees because they don't even share the same code.

So running 26.y.z /27.y.z absolutely would have shielded anyone from this bug. That was my point. 

This bug exists because 28 is a newer tree. It was introduced in 28 due to substantial breaking changes that were introduced with a new major version. You won't encounter it in a 26 or 27 release (unless we screw up). 

There's no need to fix this bug in the 26 and 27 code trees because the code in question doesn't exist there. Those are frozen branches outside of critical bug fixes and security updates. And we take the time and the effort to keep them maintained with those critical fixes for the time posted on the schedule I shared previously (https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule#currently-maintained-versions) - which is at least a year.

> In my case, this has not been the first time I had to rollback, and it is always a chore, even with my single user instance. I can not even begin to imagine how annoying and unnecessarily stressful it has to be at a larger scale.

In my experience, large installations rarely run the latest and greatest of anything (and if they do: it's a deliberate decision, taken for a compelling reason, and done with eyes wide open, and extra preparedness).

Look everybody has different comfort levels - I personally run 26.y.z (going on 27.y.z this month) in production even though I'm doing development and support for >=v28. LOL. I prefer significant stability and as much predictability as possible when it comes to my data. Nothing beats lots of field time for that!

I continue to be baffled when people deploy a bleeding edge major release (not yet 60 days old) and want it to behave like the older mature/ battle tested majors (which still routinely - albeit conservatively - receive patches for critical newly discovered bugs as needed!). 

There's a reason all three majors coexist - we don't just maintain all three for the fun of it! :-)

Everybody has different needs, wants, and preferences.

I know some people will *always* install the latest. And that's cool. I'm like that too - just not in my production environment for certain things... Like file storage. :-)

Btw: I'm not necessarily in disagreement with the rest of your comments and ideas. But they take work and we should move this discussion to a dedicated issue or the forum - or a bit of both. :-)

**Comment by JB1985** [comment]
In the past it was more like this: Do not install the first release .0 because there could be many bugs. The .1 version already fixes most of the bugs. The .2 version is then considered stable.

There are still exactly 2 weeks until the release of 28.0.3.

During the time discussed here, an RC could have been released. Everyone would be happy and new bugs would be found.
We as a community would make the software even better.

**Comment by skjnldsv** [comment]
> Not working: Downgrading is not supported and is likely to cause unpredictable issues (from 28.0.2.5 to 28.0.1.1)
> 
> Can you release a RC please?

edit your config and change the current version to 28.0.1.1.
You should be good, there was no DB migrations between 28.0.1 and 28.0.2

**Comment by skjnldsv** [comment]
> During the time discussed here, an RC could have been released.

You do realise we also have a life and we're not supper hero working 24/7 creating code?
We have a schedule for a reason, we need to plan things and coordinate between many factors. You're not paying for that software, having claims towards how things should be going faster and your way will just make this environment more hostile and will not help you. Please reconsider the way you want to colaborate with us :confused:
