### ISSUE TITLE
Moving files in/out of shared storage is broken

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#4327]
1. have two users `user1` and `user2`
2. `user1` creates a folder `foo`
3. `user1` creates `test.txt` inside `foo`
4. `user1` shares `foo` with `user2` with fill access
5. `user2` tries to move `test.txt` out of `foo`

Expected:
File is moved and all is right with the world

Actual:
Forbidden. And not all is right in the world

**Comment by rullzer** [comment]
My bet is this is introduced with the disabling of the encryption wrapper. Since that turned a move in/out of a shared storage in a copy (which is not right!).

@icewind1991 I need your FS knowledge to solve this properly.

**Comment by rullzer** [comment]
As far as I can tell the issue is that the rootpath is set relative to the owner of a shared storage in https://github.com/nextcloud/server/blob/master/apps/files_sharing/lib/SharedStorage.php#L119

Which then breaks https://github.com/nextcloud/server/blob/master/lib/private/Files/Storage/Local.php#L435

Since the rename breaks on `$sourceStorage->getSourcePath($sourceInternalPath)` because that returns somethings like `files/foo/test.txt` which is basically missing the owner part.

**Comment by icewind1991** [comment]
Fix is here: https://github.com/nextcloud/server/pull/4329
