### ISSUE TITLE
[Bug]: NC 28.0.2 - Icons in toolbar are black instead of white

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/server#43298]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

All icons in the toolbar are black instead of white.

### Steps to reproduce

1. Upgrade von NC 28.0.1 to 28.0.2
2. Go to personal settings, Appearanc and accessibility
3. Selelect "Default background" to get the default background and color
4. Select "no background" for the background, so only the color is used as background without an image
5. See icons in the tab bar to turn black instead of staying white - also the small pill below the "active" icon is still white even with the icons in black.

### Expected behavior

Icons in the tab bar are white and not black.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

![image](https://github.com/nextcloud/server/assets/6613614/0afa2187-314d-4a03-abc8-561d2f301ddb)

![image](https://github.com/nextcloud/server/assets/6613614/e80e8e0e-ff9a-4844-9466-de97d6f9a71d)

**Comment by arnowelzel** [comment]
As a workaround I added the following CSS:

```
#header * {
  filter: none !important;
}
```

I understand the intention of the original filter invented with NC 28.0.2 - but maybe it would be better to have some option for the icon color instead of a filter.

**Comment by ozls** [comment]
I also have this issue. The fix @arnowelzel gave worked for the header icons, but in my case the favicons are also generated as black on blue and are not fixed.

**Comment by arnowelzel** [comment]
> I also have this issue. The fix @arnowelzel gave worked for the header icons, but in my case the favicons are also generated as black on blue and are not fixed.

Did you try to clear the cache of your browser? In my case the favicons are ok, but I cleared the browser cache after adding the custom CSS

**Comment by arnowelzel** [comment]
> > I also have this issue. The fix @arnowelzel gave worked for the header icons, but in my case the favicons are also generated as black on blue and are not fixed.
> 
> Did you try to clear the cache of your browser? In my case the favicons are ok, but I cleared the browser cache after adding the custom CSS

I stand corrected - indeed some apps have black favicons, but not all of them. I don't understand, how this can happen at all. Even if the favicons are generated, the colors used for that should be based on global preferences and not depending on some app specific rules.

**Correct favicons:**

Files:
![image](https://github.com/nextcloud/server/assets/6613614/4ef6c11f-1e8c-4aeb-b96e-031aa6bc8ba4)

Activity:
![image](https://github.com/nextcloud/server/assets/6613614/bdd8260d-a708-4cf3-bbf5-20ec3a118087)

Contacts:
![image](https://github.com/nextcloud/server/assets/6613614/82aebb14-1f9f-4bf9-ba40-0c3b9de5b37c)

Calendar:
![image](https://github.com/nextcloud/server/assets/6613614/de0b50b4-7fa2-4d86-a79f-7b4ea1da4ff3)

Deck:
![image](https://github.com/nextcloud/server/assets/6613614/e6a34744-96ff-45a5-92d8-a8792acae8fa)

Collectives:
![image](https://github.com/nextcloud/server/assets/6613614/1ade7324-fc97-46ec-a88a-15a500387b94)

Tasks:
![image](https://github.com/nextcloud/server/assets/6613614/6b19a33f-4531-444c-890b-4380423ad8db)

**Wrong favicons:**

Photos:
![image](https://github.com/nextcloud/server/assets/6613614/399adee1-a44b-412e-a304-17d64bda1170)

Notes:
![image](https://github.com/nextcloud/server/assets/6613614/06f609d7-1aba-4588-9e4d-27a351fc1e3a)

**Comment by susnux** [comment]
The color of the text is based on your background color, it is chosen to have at least 4.5:1 contrast, meaning if you make the background color a bit darker it will be white text.

**Comment by ozls** [comment]
Changing the tone of blue solved it for me, thank you @susnux. I don't believe the behavior should have changed like this, but I guess that is another debate.

**Comment by regs01** [comment]
Just updated to 29.0.0 and it is not fixed. Icons are still black.

There is a filter applies, when shouldn't
```css
.app-menu-main .app-menu-entry img[data-v-62f74e6b] {
  filter: var(--background-image-invert-if-bright);
}
```
