### ISSUE TITLE
[Bug]: File upload via Drag and Drop overwrites existing files without further notice

### ISSUE THREAD

**Issue by JohnathanGoldstein** [nextcloud/server#43313]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since the upgrade to Nextcloud 28.0.2 file upload via Drag and Drop is working again. However if you use Drag and Drop to upload a file with the exact same name as an existing file, the existing file on the server will be overwritten without further notice.

### Steps to reproduce

1. Create for example a **.bin** file locally with any content (**.bin** as **.txt** would be cached by the text editor)
2. Upload the file to the Nextcloud server
3. Locally change the content of the file
4. Upload the changed file via Drag and Drop
5. Check the content of the file now present on the server.

### Expected behavior

When dropping an existing file Nextcloud should display the usual dialogue which lets you select if you like to keep the existing file, the new file, or both files instead of just overwriting any existing data,  as is the case when uploading an existing file using the file chooser.

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.2.5",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "maintenance": false,
        "overwriteprotocol": "https",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "default_phone_region": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - calendar: 4.6.4
  - cloud_federation_api: 1.11.0
  - contacts: 5.5.1
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - survey_client: 1.16.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - updatenotification: 1.18.0
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - circles: 28.0.0-dev (installed 25.0.0)
  - comments: 1.18.0 (installed 1.15.0)
  - contactsinteraction: 1.9.0 (installed 1.6.0)
  - dashboard: 7.8.0 (installed 7.5.0)
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 1.15.0)
  - files_external: 1.20.0
  - files_pdfviewer: 2.9.0 (installed 2.6.0)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - firstrunwizard: 2.17.0 (installed 2.14.0)
  - gpxpod: 5.0.15 (installed 5.0.15)
  - mail: 3.5.5 (installed 3.5.5)
  - nextcloud_announcements: 1.17.0 (installed 1.14.0)
  - recommendations: 2.0.0 (installed 1.4.0)
  - related_resources: 1.3.0 (installed 1.0.3)
  - richdocuments: 8.3.1 (installed 8.3.1)
  - richdocumentscode: 23.5.705 (installed 23.5.705)
  - spreed: 18.0.3 (installed 18.0.3)
  - support: 1.11.0 (installed 1.8.0)
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0 (installed 1.15.0)
  - user_ldap: 1.19.0
  - user_status: 1.8.1 (installed 1.5.0)
  - weather_status: 1.8.0 (installed 1.5.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional info

- Firefox 115 ESR

- `[NcButton.mjs:145:37](webpack:///nextcloud/node_modules/@nextcloud/vue/dist/Components/NcButton.mjs)

You need to fill either the text or the ariaLabel props in the button component. 
Object { text: undefined, ariaLabel: "" }
 
Object { _uid: 241, _isVue: true, __v_skip: true, _scope: {…}, "$options": {…}, _renderProxy: {…}, _self: {…}, "$parent": {…}, "$root": {…}, "$children": (1) […], … }
[NcButton.mjs:145:37](webpack:///nextcloud/node_modules/@nextcloud/vue/dist/Components/NcButton.mjs)​`

**Comment by dinkonin** [comment]
This still occurs for me on 28.0.3 (Chromium 122 and Firefox 123).
