### ISSUE TITLE
[Bug]: Upgrade from 28.0.1 to 28.0.2 fails because php crashes with illegal instruction on FreeBSD.

### ISSUE THREAD

**Issue by zBeeble42** [nextcloud/server#43324]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

As in the title, the upgrade from 28.0.1 to 28.0.2 fails because PHP crashes with in illegal instruction error.  Host is FreeBSD 13.2 on an AMD64 platform.  PHP is 8.2.13 and I verified it on 8.2.14.  Thank-goodness for zfs rollback :).

Here is what I see (this was with php8.2.14, but it is identical to the 8.2.13 output:

![nextlcoud_php_crash](https://github.com/nextcloud/server/assets/8474734/af46df79-4a53-41c9-a1bc-db27ac07a85f)

### Steps to reproduce

1. upgrade 28.0.1 to 28.0.2 on FreeBSD 13.2 with php 8.2.13
2. run occ upgrade manually
3. fail.

### Expected behavior

no fail in step 3.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Other

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
[nextcloud@nextcloud ~/nextcloud]$ php occ app:list
Enabled:
  - activity: 2.20.0

  - deck: 1.12.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_automatedtagging: 1.18.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - forms: 4.0.0
  - integration_mastodon: 2.0.3
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - mail: 3.5.5
  - nextcloud_announcements: 1.17.0
  - notes: 4.9.2
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - onlyoffice: 9.0.0
  - password_policy: 1.18.0
  - photos: 2.4.0
  - previewgenerator: 5.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - socialsharing_email: 3.0.1
  - spreed: 18.0.1
  - support: 1.11.0
  - survey_client: 1.16.0
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0
  - tasks: 0.15.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - encryption: 2.16.0 (installed 2.8.1)
  - files_external: 1.20.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - integration_github: 2.0.6 (installed 2.0.6)
  - maps: 1.3.1 (installed 1.3.1)
  - news: 24.0.0 (installed 24.0.0)
  - twofactor_totp: 10.0.0-beta.2
  - unsplash: 2.2.1 (installed 2.2.1)
  - user_ldap: 1.19.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Pasted in additional info.
```

### Additional info

 
[nextcloud_log_short.txt](https://github.com/nextcloud/server/files/14154641/nextcloud_log_short.txt)

**Comment by joshtrichards** [comment]
Hi @zBeeble42 - I can't think of anything we could remotely do that would be the root cause of this. Even if there's a difference between version v28.0.1 and v28.0.2, at best I suspect the root cause is something else underneath that we just happen to be poking.
 
You'll have to look at the core dump for figure out what's going on locally.

**Comment by susnux** [comment]
This more sounds like an issue with either your PHP runtime or one of the PHP extensions being compiled for a different machine that provides other instructions than the CPU you are using.

**Comment by arnowelzel** [comment]
I also believe, that the error message `Illegal instruction (core dumped)` indicates a problem with your local PHP installation. The instruction is not one executed by Nextcloud but by PHP itself.

**Comment by zBeeble42** [comment]
Well... nice you're washing hands of it, and I suppose you're saying you don't support FreeBSD servers.

_but_  ... and this is something that is in your control:

You didn't trigger this illegal instruction during the 27 to 28 upgrade _or_ the 28.0.0 to 28.0.1 upgrade (if that was a thing).  I upgraded that PHP 6 to 8 months ago ... so all the regular upgrades since then have not triggered this bug.

Now ... I agree that PHP should not do dumb things.  I've cloned my installation and gotten down to testing it for FreeBSD ... but what changed in 28.0.2 in "upgrade apps from app store" ... ?

**Comment by joshtrichards** [comment]
> Well... nice you're washing hands of it, and I suppose you're saying you don't support FreeBSD servers.

I'm not really sure what to tell you: you're the only one suggesting that's the reason. Three different developers replied.

> *but* ... and this is something that is in your control:
>
> You didn't trigger this illegal instruction during the 27 to 28 upgrade or the 28.0.0 to 28.0.1 upgrade (if that was a thing). I upgraded that PHP 6 to 8 months ago ... so all the regular upgrades since then have not triggered this bug.

Triggering something isn't the same thing as being the root cause of it. We're not writing in C over here. :-) There's nothing we could do (in PHP) that would trigger this even if we deliberately wanted to (outside of finding some known bug in PHP or a PHP dependency).

Despite your attitude, I get you merely frustrated so poked around a bit more and noted that another FreeBSD user on the Help Forums has had an issue triggered by the `forms` app upgrade that was somehow connected with how `phpseclib` was built and they provided their solution:

https://help.nextcloud.com/t/failed-to-install-update-apps/162650/4

Hope that helps.

**Comment by zBeeble42** [comment]
thank-you.  That is indeed a pointer that may help that I failed to find.

**Comment by zBeeble42** [comment]
As a place to put this information, the fix is to remove CPU_OPTS options from math/gmp when compiling the ports/packages.
