### ISSUE TITLE
Nginx settings from Manual don't work correctly with ajax

### ISSUE THREAD

**Issue by aTanCS** [nextcloud/server#4332]
### Steps to reproduce
1. install nginx+php5.6+nexcloud11.0.2
2. use nginx configuration from https://docs.nextcloud.com/server/11/admin_manual/installation/nginx_nextcloud_9x.html
3. try to change language in personal settings, try to open Versions tab of a file or try to open ldap settings.

### Expected behaviour
Change language, open versions of a file, open ldap settings

### Actual behaviour
change language: 
```
browser: /settings/ajax/setlanguage.php 404 Not found
```
show Versions: 
```
browser: /apps/files_versions/ajax/getVersions.php?source=%2FNextcloud%20Manual.pdf&start=0 500 Internal Server Error
log: PHP Fatal error:  Class 'OCP\JSON' not found in .../apps/files_versions/ajax/getVersions.php on line 28
```
ldap settings:
```
browser: /apps/user_ldap/ajax/getConfiguration.php 500 Internal Server Error
log: Class 'OCP\JSON' not found in /media/data/www/owncloud/apps/user_ldap/ajax/getConfiguration.php on line 30
```
### Server configuration

**Operating system**: Debian Jessie

**Web server:** Nginx 1.6.2

**Database:** Pgsql 9.6

**PHP version:** 5.6.30

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** official pages archive.

**Comment by MorrisJobke** [comment]
Mmmh ... this all works for me and it looks like Nginx tries to use the actual PHP file instead of using the index.php/ROUTE. @josh4trunks Do you have an idea why this could be interpret in the wrong way? For me the example from the docs works fine.

**Comment by aTanCS** [comment]
I'm sorry. I haven't investigated the issue well. I've put by mistake this at the beginning of nginx config:
```
    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass $socket;
    }
```
After removing everything works as it should.
