### ISSUE TITLE
[Bug]: title of dashboard is "Dashboard - Dashboard - NextCloud"

### ISSUE THREAD

**Issue by ashley-b** [nextcloud/server#43327]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since updating from 28.0.1 to 28.0.2 Dashboard is displayed twice in the title.

Previously (28.0.1): 
Displayed `Dashboard - NextCloud`

Page source
```
<title>
			Dashboard - Nextcloud		</title>
```
Now (28.0.2):
Displayed  ` Dashboard - Dashboard - NextCloud`

Page source
```
<title>
			Dashboard - Dashboard - NextCloud		</title>
```
File and other groups seem unaffected. I wounder if its related to #42413

### Steps to reproduce

1. Update from 28.0.1 to 28.0.2

### Expected behavior

Dashboard title should be as it was in 28.0.1

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment]
Fyi @JuliaKirschenheuter

**Comment by susnux** [comment]
Regression of 94d122deabda6125a4e76a23140e498c402c5afb

`pageTitle` should not be set to app name as the app name will already be used.
Instead it should be empty in this case, then only the heading needs to be fixed.

**Comment by arublov** [comment]
@szaimen can I take this task?
