### ISSUE TITLE
make concurrent chunked file uploads configurable

### ISSUE THREAD

**Issue by realies** [nextcloud/server#43337]
at the moment, uploading a large file is split into chunks, which get pushed to nextcloud server 3 at a time; i've found that 3 connections are not enough for me to max out my network line and think it would be great if this value is configurable via occ

**Comment by joshtrichards** [comment]
Related: nextcloud-libraries/nextcloud-upload#4

**Comment by joshtrichards** [comment]
Btw, are you referring to Web Files uploading or via one of the other clients?

**Comment by realies** [comment]
web files uploading

**Comment by skjnldsv** [comment]
Let's move to the issue linked by Josh :)
