### ISSUE TITLE
External Storage and Tor Hidden Service (.onion) not work

### ISSUE THREAD

**Issue by voxdemonix** [nextcloud/server#4333]
Dear community,
I want mount an sftp [external storage](https://docs.nextcloud.com/server/12/admin_manual/configuration_files/external_storage_configuration_gui.html) (via [Tor Hidden Service](https://www.torproject.org/docs/hidden-services.html.en)) on my Nextcloud but it's not work with Nextcloud (version up-to-date).
It works correctly with my SSH agent by adding in my _/etc/ssh/ssh_config_
```
 Host *.onion
       ProxyCommand nc -xlocalhost:9050 -X5 %h %p`

```
But these modifications don't affect Nextcloud.
I m on Debian&Ubuntu (GNU/Linux).

Thanks all people for your great work :)

**Comment by MorrisJobke** [comment]
cc @icewind1991 

I guess we don#t use the ssh config because we use a lib.

**Comment by MorrisJobke** [comment]
> I guess we don#t use the ssh config because we use a lib.

Just verified. Those files are not used at all by the library we use (http://phpseclib.sourceforge.net). That means, that this will never work, because those are two different components, that don't know of each other. As of now, we do not support such mappings in the files_external app.
