### ISSUE TITLE
Buttons for Add to Favorites, Move or Copy, and Download should not scroll when the file list is scrolled

### ISSUE THREAD

**Issue by mahoneyr** [nextcloud/server#43341]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When you scroll the list of files, the Favorites, Move or Copy, and Download action buttons scroll off the screen with the list. After selecting items from the list, you have to scroll back to the top of the list to see them again.

**Describe the solution you'd like**
These buttons should stay at the top of the list when the list is scrolled.

**Describe alternatives you've considered**
We could continue to live with it the way it is.

**Additional context**
This may be a regression (it may have worked better before).

**Comment by susnux** [comment]
Will be included in 28.0.3

Fixed in: https://github.com/nextcloud/server/pull/43172

**Comment by mahoneyr** [comment]
Thank you!
