### ISSUE TITLE
Big federated shares do not scale

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#4339]
Issue
--------

A friend recently shared a big federated share with me. Containing a lot of images in folders. On top of that he is often updating the images in there which causes my server to often try to fetch the new list from shareinfo.php. Now his server is not located close to mine and his connection is not the best (understatement of the year).

Now because of this the call to `shareinfo.php` times out from time to time because an XML file of several megabytes has to be send over and this doesn't always succeed in the 10 second timeout.

Of course there is no need to send over the whole file list since 99% of the files did not change. We should have a smarter recursive algorithm (like the desktop client uses) to figure out where data has changed and only update those parts.

Proposed solution
-------------------------

We extend the DAV storage to a FederatedNextcloudDAV (or whatever fancy name you want). If we figure out that something has to be updated we do limited depth propfinds (of 1 I think). And just traverse into the directories that have a changed etag.

This results in more requests but they should be a lot smaller and faster to transfer.

@schiessle @icewind1991 feedback is appreciated!

**Comment by schiessle** [comment]
I think we already have a extended DAV storage in case you mount a Nextcloud as external storage. Not sure if we use this for federated shares? Probably not because a federated share can also come from a Pydio server or a ownCloud where we don't know if all the advanced functionality is available.

**Comment by rullzer** [comment]
We do a call to shareinfo if it is an ownCloud/Nextcloud federated share (see https://github.com/nextcloud/server/blob/master/apps/files_sharing/lib/External/Storage.php#L305-L339 ). That just fetches the entire share info at once. Which blows up if it is large.

**Comment by szaimen** [comment]
I suppose this issue is still valid?

**Comment by PVince81** [comment]
we've recently modified the scanner to not rely on getShareInfo any more but gradually scan the remote: https://github.com/nextcloud/server/pull/32852/files#diff-30920f1b2133d1e7455b9a6ba97de5683c3b3f79ba00f686c3b41c178452ca8eL95
