### ISSUE TITLE
New sharing UI

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#434]
The flat sharing model has brought advantages in better control over your data. But it poses a UX problem.

To recap what this means. Flat sharing means that each share has 3 participants.
- Share owner (owner of the data)
- Share initiator (sharer of the data)
- Share recipient (sharee of the data)

This means the following.
- UserA shares with userB
- UserB shares with userC

Now userA should see that the data is shared with userB (by themself) and with userC (by userB). Maybe hover
is good enough here?
# LINK shares
## Situation 1

Now because the shares are flat we also have multiple link shares.
- UserA shares with userB
- UserA shares by link
- userB shares by link

Now userA should see 2 link shares
## Situation 2
- UserA shares a share by e-mail with foo@bar.com
- UserB shares a share by e-mail with hello@xyz.com

We should use different link shares for this so permissions can be revoked separatly
## Situation 3

Very similar to situation 2:
- UserA shares a folder RO to some friends by e-mail
- UserA shares the same folder with fildes drop to some forum for input
- UserA also shares the same folder with files drop to some other forum

All of those should be different links. As to keep control and not to have to
send some people a new link if you want to revoke 1.
# Security considerations

I would like to have permission control before I share.
Right now we share (RW by default). And only after it we limit the permissions. This should be the other way around
- user types in username
- simple box next to it with permissions (RW+S, RW, R?)

This means that before we share we can chose the permissions.
I'm fine with keeping the default as is. But I want to be able to do this before sharing

*\* See how google does this **
# Federated sharing

Something i have been thinking about is abstracting away from local/remote shares.
So instead of userB and userC@remoteinstance.com the users would all be shown as
- userB@localinstance.com
- userC@remoteinstance.com

Or something fancier. And of course we can do awesome autocomplete and all.
Because right now the separation feels weird and users don't care. They just want to share

@nextcloud/designers could you mock something up?

**Comment by NomoreGlitches** [comment]
Just as an additional issue, I'd like my customers not be able to Unshare important files I share with them, because otherwise they are definitely coming back to me asking for those files. In a scenario where one has 1274 customers, this could get crazy!
What about an extra permissions button prohibiting unsharing?

**Comment by rullzer** [comment]
Well we are working on an overiew page where you can retrieve deleted shares (as long as the share owner has still shared it with you). But a possibility to make it impossible to delete shares is not something I would want.

Because then I already see everybody sharing everything with that permission on all the time. We want the user to be in control of their data.

**Comment by NomoreGlitches** [comment]
The concern is definitely understandable, although maybe I could imagine some pure corporate applications where "non-unsharable" files might not be very restrictive for the user, since it is the responsibility of the company to maintain the shared files consistent.
But ok, the ability of retrieving unshared files covers pretty much the same need.

**Comment by mvisser00** [comment]
@rullzer, can you update me on the status of this feature? Is it still being worked on atm?

**Comment by jospoortvliet** [comment]
So the overview of 'undelete shares' is there in NC 14; for shares that shouldn't be deleted there exists the Group Folders app.

**Comment by rullzer** [comment]
Works only for group shares now

**Comment by jancborchardt** [comment]
Created a mockup & spec for the security considerations part at **Ability to set permissions before sharing #13229**

**Comment by jancborchardt** [comment]
@rullzer there has been a bunch of work on this, and more is ongoing. That and also the **Ability to set permissions before sharing #13229** I think make this issue obsolete. Do we close it? :)

**Comment by szaimen** [comment]
Any update here?

**Comment by jospoortvliet** [comment]
together with Jan's ability to set permissions before sharing issue and the changes we did for 18, I agree with him that this can be closed... let me just do that in the interest of cleaning up, feel free to re-open, roeland! And smack me digitally on the head for closing, if you want.
