### ISSUE TITLE
[Bug]: Impossible to add a folder to favorites without breaking the Files application

### ISSUE THREAD

**Issue by Ducknuke** [nextcloud/server#43406]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since 28.0.1 to 28.0.2 it is impossible for me to add a folder to favorites, otherwise File App gets stuck (wheel
 loading which rotates indefinitely).
Remove the favorites folder and File App works again. Bookmarking a file does not cause this problem.

The chrome console seems to indicate a problem with hashUtils.ts :
![image](https://github.com/nextcloud/server/assets/89637250/f3954d91-51ea-4cce-b785-5c78f3f7e3b9)

The `folder` variable seems to indicate my favorite folder (`/InstantUpload`) but the `.path` function returns `undefined` in favorites.ts :
![image](https://github.com/nextcloud/server/assets/89637250/52ca819d-5905-4838-a646-ff1fd116bddc)

From there if I do not remove this folder from the favorites I can no longer view my folders or files. 
The Android application is not affected by this problem and I can add or remove folder and file favorites. I reproduced the problem on Chrome and Edge in normal browsing or in private browsing and doing a refresh (Ctrl + F5) each time.

I would like to add that when adding a folder to favorites if I continue to browse without clicking on the "Files" icon at the top, operation is normal and uninterrupted. When relaunching the Files app or refreshing the page causes the problem

### Steps to reproduce

1. Browse and add any folder to favorites
2. Click on the icon at the top “Files”

### Expected behavior

Have the possibility to add a folder to favorites

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "preview_max_memory": "512",
        "default_phone_region": "FR",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx.xxx.x.xxx",
            "xxxxx.fr",
            "xx.xx.xx.xx"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "overwritehost": "nextcloud.xxxxxxx.fr",
        "overwrite.cli.url": "https:\/\/nextcloud.xxxxxxx.fr",
        "dbtype": "mysql",
        "version": "28.0.2.5",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "updater.release.channel": "stable",
        "maintenance": false,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\Movie",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MP3",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI",
            "OC\\Preview\\PDF"
        ],
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto, 60",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/app\/www\/public\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [
            "admin",
            "utilisateur"
        ],
        "upgrade.disable-web": false
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_external: 1.20.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - maps: 1.3.1
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - previewgenerator: 5.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - support: 1.11.0
  - survey_client: 1.16.0
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_totp: 10.0.0-beta.2
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - circles: 28.0.0-dev (installed 28.0.0-dev)
  - encryption: 2.16.0
  - updatenotification: 1.18.0 (installed 1.17.0)
  - user_ldap: 1.19.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by szaimen** [comment]
cc @nextcloud/server-frontend

**Comment by skjnldsv** [comment]
Can you run an occ integrity check?
According to the code of the 28.0.2 release archive, it doesn't match the code snippet you gave me on the other issue.

**Comment by Ducknuke** [comment]
> ~Can you run an occ integrity check? According to the code of the 28.0.2 release archive, it doesn't match the code snippet you gave me on the other issue.~
> 
> EDIT: Ah, I see it at the bottom. `js/core/merged-template-prepend.js` should not be an extra file. Please fix it and fix your Webserver config if you had issues serving this file.
> 
> But I'll investigate why the hell you're having that

Yes @skjnldsv ! This report intrigues me too.
I noticed that these files were in /data/appdata_ocmx20us7sn3/js/core/ but these are not extra files because if I delete them my instance no longer starts.
I will continue to investigate why this report gives me this result.

**Comment by Ducknuke** [comment]
Strange...I don't know how these files ended up in this folder
It's done for index.php/settings/integrity/failed: 
`No errors have been found.`

**Comment by skjnldsv** [comment]
As you can see, the 28.0.2 does have the proper fix:
https://github.com/nextcloud/server/blob/619dd9396b95e715542106d62054dbbfcf1ea54a/apps/files/lib/Controller/ViewController.php#L228-L237

And as you tried in the other ticket, I don't understand how you are still seeing a single array and not this
![image](https://github.com/nextcloud/server/assets/14975046/dfb20ce0-bbc6-45d4-90ef-3c367aa48840)
```js
JSON.stringify(OCP.InitialState.loadState('files', 'favoriteFolders', []))
```

**Comment by Ducknuke** [comment]
@skjnldsv the problem is here
Maybe because I don't have the correction ! :-S
![image](https://github.com/nextcloud/server/assets/89637250/0d5a1026-7332-4dde-9c5e-1260478ff176)
Update problem?
I just did an `occ app:update files` but no change.
How do I know if I have retrieved the latest version of app files?

**Comment by Ducknuke** [comment]
I can't find why "Files" is not up to date with 28.0.2. It is normally updated at the same time and if "Files" is in 2.0.0 version and the check:integrity says nothing it is valid but when I look I do not have the corrections and that's my problem. And if "Files" is not up to date, other apps may not be up to date in my environment ?

**Comment by Ducknuke** [comment]
Thank you @skjnldsv and sorry but I'm still having trouble understanding all the update mechanics. 

Updates are done automatically by Docker (linuxserver/nextcloud) by Watchtower. 
The files folder is located in my `config/www/nextcloud/apps` folder which is logically not affected when updating the container. If files are not updated via the market either then how the hell am I going to update "Files" ?

**Comment by susnux** [comment]
Seems like a `linuxserver` images issue (again), I do not recommend using it and instead use something like [nextcloud/all-in-one](https://hub.docker.com/r/nextcloud/all-in-one)

**Comment by Ducknuke** [comment]
Thank you @susnux  for your answer. No problem switching to nextcloud/all-in-one but is it as simple as simply changing the repository link in portainer? I'm afraid of breaking my instance.

**Comment by skjnldsv** [comment]
Unfortunately this would be questions for the forum.
This is really about bug tracking on github :(

Linuxserver is up to date too
```bash
# docker run -ti lscr.io/linuxserver/nextcloud:latest sed -n 231,234p /app/www/public/apps/files/lib/Controller/ViewController.php
			$favElements = array_map(fn (Folder $node) =&gt; [
				&apos;fileid&apos; =&gt; $node-&gt;getId(),
				&apos;path&apos; =&gt; $userFolder-&gt;getRelativePath($node-&gt;getPath()),
			], $favElements);
```

**Comment by Ducknuke** [comment]
Yes of course. Thank you all (especially @skydiablo) for taking the time to respond to me and provide suggestions to correct my problem. I'll keep looking. 
I love all the work that is being done on Nextcloud.
Thank you again for this community project!

**Comment by joshtrichards** [comment]
> Updates are done automatically by Docker (linuxserver/nextcloud) by Watchtower.
The files folder is located in my config/www/nextcloud/apps folder which is logically not affected when updating the container.

FYI: I don't believe the below is in a typical Linuxserver.io deployment:

```
        "apps_paths": [
            {
                "path": "\/app\/www\/public\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
```

**Comment by Ducknuke** [comment]
Yes exactly @joshtrichards ! Thanks !
Yesterday waiting to find out why it wouldn't update I did a big cleanup of my config.php, it was still in array format :
```
array (
    0 => 
    array (
      'path' => 'config/www/nextcloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
```
and now for all my config :
```
'apps_paths' => [
	[
		'path'=> OC::$SERVERROOT.'/apps',
		'url' => '/apps',
		'writable' => true,
	],
],
```
I also changed the applications path because I saw a redirection created for /app/www/public/apps :
![image](https://github.com/nextcloud/server/assets/89637250/307dd781-1623-480c-8b8a-d89a1937b50a)

After this major cleaning/compliance and a re-creation of the container everything was updated! Victory !

Nextcloud is my first container for my server and it has an old configuration that I haven't necessarily always looked at compared to the *.sample that are provided. 
It's a mistake I won't make again ;)

Thanks again for all your work and time spent trying to help others

**Comment by skjnldsv** [comment]
Congrats @Ducknuke ! :tada:
