### ISSUE TITLE
The pop-up's Delete button does not change color when hovered over

### ISSUE THREAD

**Issue by nabim777** [nextcloud/server#43416]
## Steps to reproduce:
1. Click on the `user delete` button on a linked workpackage
2. a pop-up will appear
3. hover over the `cancel` button, the color is changed
![image](https://github.com/nextcloud/server/assets/61624650/fcee8f7a-365c-447f-bf4b-f6b7c7fd3f1b)
4. But when hover over `Delete **'s account` button then the color is not changed
![image](https://github.com/nextcloud/server/assets/61624650/0af241e2-7a19-49d7-9af1-c7eeb087e8c3)

**Comment by Happyashbunny** [comment]
hello @nabim777 I'd interested in contributing to this issue. Can you please direct me to the folder in which the code for this resides

**Comment by nabim777** [comment]
Hello @Happyashbunny I think this is the folder where code may be 

https://github.com/nextcloud/server/blob/57f27a14b4ef5a9650b69d5e3be1af6ff16cc4fe/apps/settings/src/components/Users/UserRow.vue#L597

**Comment by Happyashbunny** [comment]
@nabim777 Thank you for helping me out.
