### ISSUE TITLE
[Bug]: three-dot-menu broken on smaller screens

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#43427]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I resize the file list to a size where the icon of the sharee gets hidden, the icon shows up in the three-dot menu

Tested on c.nc.com: 28.0.2

### Steps to reproduce

1. Navigate to a folder where you have files/folders shared with you

![image](https://github.com/nextcloud/server/assets/1589737/ce734251-4fff-4462-b8a1-9ec323a6bcb0)

2. Re-size the window so that the sharee icon disapears

![image](https://github.com/nextcloud/server/assets/1589737/1f43e100-452e-4fcf-915c-e9a8eca54564)

4. Open the three-dot-menu
![image](https://github.com/nextcloud/server/assets/1589737/6443ad83-99e7-4a8b-99fb-2b0ac1a66aff)

### Expected behavior

Icon should not appear in the three-dot-menu

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ShGKme** [comment]
`FileAction` instance has `displayName` and `title`. According to the docs, it is as it is - the text in the menu and the title.

However, actually sometimes `title` is used as a `displayName`, for example, when an inline action is rendered in a menu (grid/small screen like on the screenshot in this issue). And there is a hardcoded case for sharing-status action, where no `displayName` is rendered for a shared file causing this issue.

It seems to me that both cases are only for this sharing-status.

A solution could be to add a new property `displayNameInline` to `FileAction` instance to implicitly support setting different names for labeling inline and menu items.

Was discussed with @skjnldsv

**Comment by skjnldsv** [comment]
Fixed since then
