### ISSUE TITLE
[Bug]: 'forbidden_chars' Not Enforced During File Uploads

### ISSUE THREAD

**Issue by nc-fkl** [nextcloud/server#43423]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The parameter 'forbidden_chars,' introduced in Nextcloud 28 for setting prohibited characters, applies restrictions only when creating or renaming files and folders through the WebUI. This restriction does not extend to file uploads.

Could you please update the functionality to ensure that this parameter is also applied during file uploads?

The restriction does not apply to file uploads through the WebUI drag and drop or the "Upload files" using the +New button. 

### Steps to reproduce

1. + New
2. Upload files
3. Test#.txt

### Expected behavior

Thest "Test#.txt" should also be declined because of the restricted character like it is already done for folders

### Installation method

None

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Fixed in nextcloud-libraries/nextcloud-upload#1132 (fka: nextcloud-libraries/nextcloud-upload#1086) and 079d026d39565e7b5547741bd62bd69082347ad6
