### ISSUE TITLE
Improve lost password email

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#4345]
Followup to #4308

Mockup by @Espina2 

![new password](https://cloud.githubusercontent.com/assets/11150206/24954820/cb81e10a-1f78-11e7-9fa2-dd177bbf3044.png)

Comments by @eppfel:

> Yeah, @Espina2 copy would be much appreciated. 
> 
> Too minor edits:
> 
> This ~~reset~~ password _reset_ is only available... 
> 
> Or:
> 
> This password reset link is only.... 
> 
> And 
> 
> ~~For security,~~ this request...

**Comment by rullzer** [comment]
Mmmm shouldn't it contains the ip? And a link to contact your admin or something? Like if you didn't request it you might want to report that somebody is trying to access your account...

**Comment by jancborchardt** [comment]
But do we really want to put that in the body copy? It's a mighty lot of text for a simple password reset. The button should be one of the first elements because it's fine for the majority of cases.

That extra info text is for the edgecases where malicious stuff is done, so it can be smaller / grey and further down.

**Comment by buoyantair** [comment]
Hello, is this issue still open?

**Comment by MorrisJobke** [comment]
> Hello, is this issue still open?

Yes it is - see the status in the header:

![bildschirmfoto 2017-12-10 um 10 33 06](https://user-images.githubusercontent.com/245432/33803682-8d42e2be-dd95-11e7-8f23-230acb3ff4e5.png)

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest and no respond since around 2 years. Please reopen if you still want to implement this.

**Comment by skjnldsv** [comment]
Superseded by https://github.com/nextcloud/server/issues/48095
