### ISSUE TITLE
Occ command string considered as json (files_external app)

### ISSUE THREAD

**Issue by Ardinis** [nextcloud/server#4347]
### Steps to reproduce
1. in bash: `sudo -u www-data /var/www/nextcloud/occ files_external:config 1 bucket '5.1.2.3'`
2. mysql result: '5.1' (`SELECT value FROM nc_external_config WHERE key='bucket';`)
3.

### Expected behaviour
We should have **5.1.2.3** in the field.

### Actual behaviour
We have **5.1* instead because the $value is considered as a json string https://github.com/nextcloud/server/blob/master/apps/files_external/lib/Command/Config.php#L109
Moreover I don't think that json is needed to be handled for the config command.

### Server configuration

**Operating system**: Debian 8.0

**Web server:** apache2

**Database:** mariadb 10.0

**PHP version:** 5.6.30

**Nextcloud version:** (see Nextcloud admin page) 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** nextcloud website

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
No errors have been found.

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** openstack swift

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** 

### Client configuration
**Browser:** Chrome

**Operating system:**

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
empty
```
</details>

**Comment by MorrisJobke** [comment]
Fixed in #4404
