### ISSUE TITLE
[Bug]:  Username from digits only cannot acces own files anymore

### ISSUE THREAD

**Issue by Mysterycz** [nextcloud/server#43482]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello, after update to NC 28, all users with username from DIGITS cannot access their files anymore. Also they cannot upload or create new files in their home directory. It is grayed out. If you add one character to their digit username, it is working ok. Can you check this out? We broke our production cloud due to this bug. Thank you.

### Steps to reproduce

1. Update to NC 28 last version
2. Create LDAP user with username contains DIGITS only
3. Try to access or create files

### Expected behavior

It should work :-)

### Installation method

None

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Previously reported. Fixed in #43318
