### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by antonioraminhos** [nextcloud/server#43497]
How can I set up a subdomain to share my file links with a custom format, such as changing "https://nextcloud.com/s/iBkGadGXTgarKg6" to "https://files.nextcloud.com/s/iBkGadGXTgarKg6"? Additionally, is there a way to generate direct links that include the file extension, like transforming "https://nextcloud.com/s/iBkGadGXTgarKg6" into "https://nextcloud.com/s/iBkGadGXTgarKg6.pdf," ensuring that the browser directly displays the corresponding .pdf file?

**Comment by joshtrichards** [comment]
Hi @antonioraminhos - This appears to be a support/ configuration/ deployment question. Please use the appropriate channel for that: https://help.nextcloud.com

Thanks!
