### ISSUE TITLE
[App Trashbin] Remove delete buttons

### ISSUE THREAD

**Issue by fbreton37** [nextcloud/server#4349]
Hello,

For security reason, I want disable the possibility to delete permentaly files in the trashbin.
Files will be only delete after the retention date.

I already comment the html part for the delete button in /nextcloud/apps/files_trashbin/template/index.php.
But I don't find how disable the delete button from the action menu in the trashbin.
Can you please help me on this?

## Expected behaviour
Do not show any delete buttons in the trashbin or disable delete fonctionnality from trashbin

### Actual behaviour
"Remove a file" is possible from the trashbin

### Server configuration

**Operating system**:
RHEL 7
**Web server:**
Apache 2.4
**PHP version:**
PHP/7.0.16

**Nextcloud version:**
  ##11.0.2

**Comment by MorrisJobke** [comment]
cc @jancborchardt @karlitschek @schiessle Does this make sense?

**Comment by MariusBluem** [comment]
What, if somebody wants to delete a file permanently by intention before the 30 days are over?

**Comment by karlitschek** [comment]
I can see the usecase. Not sure how important it is.

**Comment by fbreton37** [comment]
To explain the feature need, I will describe the scenario:

I have a cluster of nextcloud servers (Shared Files System with GlusterFS and DB with Galera)

Node 1 in physical zone A (only accessible from the zone A)
Node 2 in physical zone B (only accessible from the zone B)

For security reason (fairly close to the PCI-DSS) we have to keep during 30 days all files uploaded/modified/deleted from the zone B. 

@MariusBluem: - Request to the administrator or impossible to do this request

**Comment by ACTom** [comment]
I think this feature is important to company, just administrator can delete files in trashbin, user can't, or user delete files from trashbin is only move files from user's trashbin to system trashbin, then administrator can restore files.

**Comment by MorrisJobke** [comment]
> I think this feature is important to company, just administrator can delete files in trashbin, user can't, or user delete files from trashbin is only move files from user's trashbin to system trashbin, then administrator can restore files.

This special trashbin should then be a separate app. Disable just the default user centric trashbin and implement the admin centric trashbin as a separate app. I don't see, that we will bring this as a feature flag into the default trashbin, because it involves a completely different flow and is very special.

**Comment by skjnldsv** [comment]
@jancborchardt I think this is out of scope.
I'd say, you can still hide it yourself with the custom css app, but supporting this officially is not what we should do. I suggest we close this issue :)
