### ISSUE TITLE
Option to force update dispite big database (more than 50 users)  ("Please use the command line updater because you have a big instance")

### ISSUE THREAD

**Issue by cmorty** [nextcloud/server#4353]
### Steps to reproduce
1. Update a Nextcloud-Instance with more than 50 users using the web-updater.
2. You get a warning "Please use the command line updater because you have a big instance". See also https://github.com/nextcloud/server/issues/3668 and https://github.com/nextcloud/documentation/issues/318

### Expected behaviour
A button saying "Yes, yes, I know, I can loose all my data. Do it anyway!"
Reasoning: In a hosted environments one does not always have shell access. And having many users does not necessarily also mean having a big database (and vice versa).

### Actual behaviour
There is no way to update the database without shell access. 

### Server configuration

**Nextcloud version:** 10 + 11 (it's in https://github.com/nextcloud/server/blob/30689f338faf5327e13b65d3b4a2d85f9e79064d/lib/base.php#L345-L350)

### Workaround
In `lib/base.php` edit
`$tooBig = ($totalUsers > 50);` (Somewhere around Line 340)
to a number larger your users (e.g. 500).

**Comment by MorrisJobke** [comment]
cc @rullzer @LukasReschke @nickvergessen @karlitschek

**Comment by karlitschek** [comment]
I think this is OK if the user is warned as suggested.

**Comment by MorrisJobke** [comment]
A little mitigation of this can be found in #4804

**Comment by MorrisJobke** [comment]
Fix for this is in #4805
