### ISSUE TITLE
[Bug]: “Your storage is full, files can not be updated or synced anymore!” notification is displayed to users with quota set to 0 Bytes

### ISSUE THREAD

**Issue by jkhradil** [nextcloud/server#43535]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nextcloud shows “Your storage is full, files can not be updated or synced anymore!” notification when user's quota is exceeded or backend storage is full. Since version 28 this notification is also displayed to users with quota set to 0 Bytes. This quota is commonly used to create "read-only" users, to whom this notification is confusing and it would be better if wasn't shown.

### Steps to reproduce

1. Cerate a user with quota set to 0 Bytes.
2. Login as this user.
3. See “Your storage is full, files can not be updated or synced anymore!” notification.

### Expected behavior

“Your storage is full, files can not be updated or synced anymore!” should not be displayed to users with quota set to 0 Bytes.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

I can send PR with a fix if you'll agree.

**Comment by solracsf** [comment]
> I can send PR with a fix if you'll agree.

Please do :)

**Comment by jsobiecki** [comment]
I confirm this issue with latest nextcloud (18.0.2).

**Comment by veitw** [comment]
Same issue for me. My users are only allowed to store files inside group folders and hence have a personal quota of 0 bytes. They are quite confused being permanently confronted with this notification.

Seconding integration of [jkhradil](https://github.com/jkhradil)'s patch.
