### ISSUE TITLE
SMTP password visible in admin page HTML 

### ISSUE THREAD

**Issue by JosefR** [nextcloud/server#4354]
### Steps to reproduce
1. Set up E-Mail sending in the 'Admin' page via SMTP under "Additional settings" -> "Email server".
2. Save the settings and open up the page again.
3. Checking the contents of the input field for the password (next to 'Credentials') shows the full SMTP password as 'value'. 

### Expected behaviour
The SMTP password should not be available via the HTML client.

### Actual behaviour
SMTP password is available in input field value. 

### Server configuration

**Operating system**: Debian 8.7

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 5.6.30

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** yes

**Where did you install Nextcloud from:** official tar.bz2

### Client configuration
**Browser:** Chromium 57.0.2987.98

**Operating system:** Ubuntu 16.10

**Comment by MorrisJobke** [comment]
cc @LukasReschke @nickvergessen
