### ISSUE TITLE
Clients trying to access wrong/missing folders or wrong redirect

### ISSUE THREAD

**Issue by aarpon** [nextcloud/server#4356]
### Steps to reproduce
I think just have Nextcloud clients synchronize with the server. I have a lot of them running all the time, from macOS, Windows, Linux, and Android. Keep an eye of the apache error log. Every 5 - 10 seconds the following entries are logged:

```
[Sat Apr 15 19:33:05.666711 2017] [access_compat:error] [pid 15024] [client 192.168.1.1:62640] AH01797: client denied by server configuration: /var/www/webdav
[Sat Apr 15 19:33:15.861947 2017] [access_compat:error] [pid 14920] [client 192.168.1.1:62652] AH01797: client denied by server configuration: /var/www/apps
```

Notice that var/www/webdav and var/www/apps do not exist (and are outside of the nextcloud root folder).

### Expected behaviour
Clients should not try to access nonexistent folders; or the server should no redirect to the wrong place.

### Actual behaviour
Apache logs the following every 5 to 10 seconds:

```
[Sat Apr 15 19:33:05.666711 2017] [access_compat:error] [pid 15024] [client 192.168.1.1:62640] AH01797: client denied by server configuration: /var/www/webdav
[Sat Apr 15 19:33:15.861947 2017] [access_compat:error] [pid 14920] [client 192.168.1.1:62652] AH01797: client denied by server configuration: /var/www/apps
```

Notice that var/www/webdav and var/www/apps do not exist (and are outside of the nextcloud root folder).

### Server configuration
**Operating system**: Linux silent 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.17

**PHP version:** 7.0.15-0ubuntu0.16.04.4
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 11.0.2 (stable) - 11.0.2.7

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** 

**Signing status:**
<details>
	<summary>Signing status</summary>

```
[]
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.4.1
 - comments: 1.1.0
 - dav: 1.1.1
 - federatedfilesharing: 1.1.1
 - federation: 1.1.1
 - files: 1.6.1
 - files_external: 1.1.2
 - files_markdown: 1.0.1
 - files_pdfviewer: 1.0.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - firstrunwizard: 2.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.0
 - notifications: 1.0.1
 - password_policy: 1.1.0
 - provisioning_api: 1.1.0
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - survey_client: 0.1.5
 - systemtags: 1.1.3
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - updatenotification: 1.1.1
 - workflowengine: 1.1.1

Disabled:
 - admin_audit
 - encryption
 - external
 - files_accesscontrol
 - files_automatedtagging
 - files_retention
 - templateeditor
 - user_external
 - user_ldap
 - user_saml
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "oc4ovwq3yzdp",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "aarpon.name:37873"
    ],
    "datadirectory": "\/data\/storage\/nextcloud\/data",
    "overwrite.cli.url": "https:\/\/aarpon.name:37873\/nextcloud",
    "dbtype": "mysql",
    "version": "11.0.2.7",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mail_from_address": "admin",
    "mail_smtpmode": "php",
    "mail_domain": "aarpon.name",
    "maintenance": false,
    "loglevel": 2
}
```
</details>

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OCA\Files_External\Lib\Storage\FTP
    [2] => \OC\Files\Storage\DAV
    [3] => \OCA\Files_External\Lib\Storage\OwnCloud
    [4] => \OCA\Files_External\Lib\Storage\SFTP
    [5] => \OCA\Files_External\Lib\Storage\AmazonS3
    [6] => \OCA\Files_External\Lib\Storage\Dropbox
    [7] => \OCA\Files_External\Lib\Storage\Google
    [8] => \OCA\Files_External\Lib\Storage\Swift
    [9] => \OCA\Files_External\Lib\Storage\SFTP
    [10] => \OCA\Files_External\Lib\Storage\SMB
    [11] => \OCA\Files_External\Lib\Storage\SMB
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0

**Operating system:**

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	[Sat Apr 15 19:32:54.036871 2017] [access_compat:error] [pid 11478] [client 192.168.1.1:62582] AH01797: client denied by server configuration: /var/www/login
[Sat Apr 15 19:32:54.221052 2017] [access_compat:error] [pid 11478] [client 192.168.1.1:62582] AH01797: client denied by server configuration: /var/www/apps
[Sat Apr 15 19:32:57.696956 2017] [access_compat:error] [pid 13197] [client 192.168.1.1:62583] AH01797: client denied by server configuration: /var/www/apps
[Sat Apr 15 19:33:05.666711 2017] [access_compat:error] [pid 15024] [client 192.168.1.1:62640] AH01797: client denied by server configuration: /var/www/webdav
[Sat Apr 15 19:33:15.861947 2017] [access_compat:error] [pid 14920] [client 192.168.1.1:62652] AH01797: client denied by server configuration: /var/www/apps
[Sat Apr 15 19:33:21.677930 2017] [access_compat:error] [pid 11473] [client 192.168.1.1:62656] AH01797: client denied by server configuration: /var/www/apps

	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
	Insert your Nextcloud log here
	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
	Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
	```
</details>

**Comment by kbabioch** [comment]
I can confirm this behaviour and see basically the exact same error messages in my logs. Not sure where this is coming from, since it is happening both with the official Nextcloud client on Android as well as with the GNOME integration (gvfs) for Nextcloud.

My `access_log` does not contain any such requests, so they must get rewritten to the wrong destination. The generated .htaccess is a clusterfuck, don't see much of a chance for an outsider to investigate or fix this in a sensible amount of time.

**Comment by MorrisJobke** [comment]
cc @nickvergessen for the notifications app

@kbabioch Do you have another apps directory specified in your config.php?

**Comment by nickvergessen** [comment]
also htaccess file would be interesting to see.
Did you enable index.php-less navigation (aka pretty links)?

**Comment by kbabioch** [comment]
> @kbabioch Do you have another apps directory specified in your config.php?

@MorrisJobke No, no other apps directory specified. This is my `config.php`:

    <?php
    $CONFIG = array (
      'instanceid' => 'xxx',
      'passwordsalt' => 'xxx',
      'secret' => 'xxx',
      'trusted_domains' => 
      array (
        0 => 'xxx.de',
      ),
      'datadirectory' => '/srv/nextcloud/data',
      'overwrite.cli.url' => 'https://xxx.de/nextcloud',
      'htaccess.RewriteBase' => '/nextcloud',
      'overwriteprotocol' => 'https',
      'dbtype' => 'mysql',
      'version' => '11.0.3.2',
      'dbname' => 'nextcloud',
      'dbhost' => 'localhost',
      'dbtableprefix' => 'oc_',
      'dbuser' => 'nextcloud',
      'dbpassword' => 'xxx',
      'logtimezone' => 'Europe/Berlin',
      'installed' => true,
      'memcache.local' => '\\OC\\Memcache\\APCu',
      'mail_from_address' => 'nextcloud',
      'mail_smtpmode' => 'sendmail',
      'mail_domain' => 'xxx.de',
      'remember_login_cookie_lifetime' => 2592000,
      'session_lifetime' => 86400,
      'cron_log' => true,
      'enable_previews' => true,
      'enabledPreviewProviders' => 
      array (
        0 => 'OC\\Preview\\PNG',
        1 => 'OC\\Preview\\JPEG',
        2 => 'OC\\Preview\\GIF',
        3 => 'OC\\Preview\\BMP',
        4 => 'OC\\Preview\\XBitmap',
        5 => 'OC\\Preview\\MP3',
        6 => 'OC\\Preview\\TXT',
        7 => 'OC\\Preview\\MarkDown',
        8 => 'OC\\Preview\\Illustrator',
        9 => 'OC\\Preview\\Movie',
        10 => 'OC\\Preview\\MSOffice2003',
        11 => 'OC\\Preview\\MSOffice2007',
        12 => 'OC\\Preview\\MSOfficeDoc',
        13 => 'OC\\Preview\\OpenDocument',
        14 => 'OC\\Preview\\PDF',
        15 => 'OC\\Preview\\Photoshop',
        16 => 'OC\\Preview\\Postscript',
        17 => 'OC\\Preview\\StarOffice',
        18 => 'OC\\Preview\\SVG',
        19 => 'OC\\Preview\\TIFF',
        20 => 'OC\\Preview\\Font',
      ),
      'maintenance' => false,
      'loglevel' => 2,
    );

> also htaccess file would be interesting to see.

@nickvergessen This is my updated `.htaccess`:

    <IfModule mod_headers.c>
      <IfModule mod_setenvif.c>
        <IfModule mod_fcgid.c>
           SetEnvIfNoCase ^Authorization$ "(.+)" XAUTHORIZATION=$1
           RequestHeader set XAuthorization %{XAUTHORIZATION}e env=XAUTHORIZATION
        </IfModule>
        <IfModule mod_proxy_fcgi.c>
           SetEnvIfNoCase Authorization "(.+)" HTTP_AUTHORIZATION=$1
        </IfModule>
      </IfModule>

      <IfModule mod_env.c>
        # Add security and privacy related headers
        Header set X-Content-Type-Options "nosniff"
        Header set X-XSS-Protection "1; mode=block"
        Header set X-Robots-Tag "none"
        Header set X-Frame-Options "SAMEORIGIN"
        Header set X-Download-Options "noopen"
        Header set X-Permitted-Cross-Domain-Policies "none"
        SetEnv modHeadersAvailable true
      </IfModule>

      # Add cache control for static resources
      <FilesMatch "\.(css|js|svg|gif)$">
        Header set Cache-Control "max-age=15778463"
      </FilesMatch>
      
      # Let browsers cache WOFF files for a week
      <FilesMatch "\.woff$">
        Header set Cache-Control "max-age=604800"
      </FilesMatch>
    </IfModule>
    <IfModule mod_php5.c>
      php_value upload_max_filesize 511M
      php_value post_max_size 511M
      php_value memory_limit 512M
      php_value mbstring.func_overload 0
      php_value always_populate_raw_post_data -1
      php_value default_charset 'UTF-8'
      php_value output_buffering 0
      <IfModule mod_env.c>
        SetEnv htaccessWorking true
      </IfModule>
    </IfModule>
    <IfModule mod_php7.c>
      php_value upload_max_filesize 511M
      php_value post_max_size 511M
      php_value memory_limit 512M
      php_value mbstring.func_overload 0
      php_value default_charset 'UTF-8'
      php_value output_buffering 0
      <IfModule mod_env.c>
        SetEnv htaccessWorking true
      </IfModule>
    </IfModule>
    <IfModule mod_rewrite.c>
      RewriteEngine on
      RewriteRule .* - [env=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
      RewriteRule ^\.well-known/host-meta /public.php?service=host-meta [QSA,L]
      RewriteRule ^\.well-known/host-meta\.json /public.php?service=host-meta-json [QSA,L]
      RewriteRule ^\.well-known/carddav /remote.php/dav/ [R=301,L]
      RewriteRule ^\.well-known/caldav /remote.php/dav/ [R=301,L]
      RewriteRule ^remote/(.*) remote.php [QSA,L]
      RewriteRule ^(?:build|tests|config|lib|3rdparty|templates)/.* - [R=404,L]
      RewriteCond %{REQUEST_URI} !^/.well-known/acme-challenge/.*
      RewriteRule ^(?:\.|autotest|occ|issue|indie|db_|console).* - [R=404,L]
    </IfModule>
    <IfModule mod_mime.c>
      AddType image/svg+xml svg svgz
      AddEncoding gzip svgz
    </IfModule>
    <IfModule mod_dir.c>
      DirectoryIndex index.php index.html
    </IfModule>
    AddDefaultCharset utf-8
    Options -Indexes
    <IfModule pagespeed_module>
      ModPagespeed Off
    </IfModule>
    #### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####

    ErrorDocument 403 /nextcloud/core/templates/403.php
    ErrorDocument 404 /nextcloud/core/templates/404.php
    <IfModule mod_rewrite.c>
      Options -MultiViews
      RewriteRule ^core/js/oc.js$ index.php [PT,E=PATH_INFO:$1]
      RewriteRule ^core/preview.png$ index.php [PT,E=PATH_INFO:$1]
      RewriteCond %{REQUEST_FILENAME} !\.(css|js|svg|gif|png|html|ttf|woff|ico|jpg|jpeg)$
      RewriteCond %{REQUEST_FILENAME} !core/img/favicon.ico$
      RewriteCond %{REQUEST_FILENAME} !/remote.php
      RewriteCond %{REQUEST_FILENAME} !/public.php
      RewriteCond %{REQUEST_FILENAME} !/cron.php
      RewriteCond %{REQUEST_FILENAME} !/core/ajax/update.php
      RewriteCond %{REQUEST_FILENAME} !/status.php
      RewriteCond %{REQUEST_FILENAME} !/ocs/v1.php
      RewriteCond %{REQUEST_FILENAME} !/ocs/v2.php
      RewriteCond %{REQUEST_FILENAME} !/updater/
      RewriteCond %{REQUEST_FILENAME} !/ocs-provider/
      RewriteCond %{REQUEST_URI} !^/.well-known/acme-challenge/.*
      RewriteRule . index.php [PT,E=PATH_INFO:$1]
      RewriteBase /nextcloud
      <IfModule mod_env.c>
        SetEnv front_controller_active true
        <IfModule mod_dir.c>
          DirectorySlash off
        </IfModule>
      </IfModule>
    </IfModule>

>  Did you enable index.php-less navigation (aka pretty links)?

I've tried it with and without. Same behaviour in both cases. It works, but an error is logged.

Let me know if you need anything else to narrow this down. I wouldn't be surprised if this affects a lot of users (maybe even all?), but people don't check the `error_log`, when it appears to work fine.

**Comment by kbabioch** [comment]
Just updated to version 12.0.0, which has the same issue. For each request an error is being logged. Very annoying!

**Comment by nickvergessen** [comment]
Hmm I can't seem to find any issue, can you provide your apache config via email to `<my githubname>@nextcloud.com`

**Comment by MorrisJobke** [comment]
No feedback since 3 months -> closing

**Comment by skitter-anton** [comment]
Sorry to re-open but I have the same problem. Any update on this?  @kbabioch Ever got this fixed?
I keep getting:
AH01797: client denied by server configuration: /home/user/domains/domain.com/private_html/index.php in my error logs. In chrome developper tools i get F.E.:
core.js?v=7ab5f3fb12a68d1cc5ae3ccf7badfe28-4:4 PUT https://domain.com/ocs/v2.php/cloud/users/admin 403 (Forbidden)

**Comment by kbabioch** [comment]
@skitter-anton Nope, I'm running 12.0.3 and still have the same issues 👎
