### ISSUE TITLE
Create Mockup for relocation of Download Limit Setting

### ISSUE THREAD

**Issue by sorbaugh** [nextcloud/server#43565]
Subtask to #6841

**Comment by szaimen** [comment]
The mockup is here or do you need more from my side?
https://github.com/nextcloud/server/issues/6841#issuecomment-1924105364

**Comment by sorbaugh** [comment]
> The mockup is here or do you need more from my side? [#6841 (comment)](https://github.com/nextcloud/server/issues/6841#issuecomment-1924105364)

No, just had to do some housekeeping retroactively on some Issues involving more than 1 people for transparency. This part is done ^^
