### ISSUE TITLE
Move the files_downloadlimit setting to new location

### ISSUE THREAD

**Issue by sorbaugh** [nextcloud/server#43566]
Subtask to #6841

**Comment by Pytal** [comment]
Needs backend + frontend upgrade for NC29 compat

**Comment by Pytal** [comment]
- https://github.com/nextcloud/files_downloadlimit/pull/225
- https://github.com/nextcloud/files_downloadlimit/pull/226
- https://github.com/nextcloud/files_downloadlimit/pull/227
- https://github.com/nextcloud/files_downloadlimit/pull/228
