### ISSUE TITLE
Assign group admin privileges to a group

### ISSUE THREAD

**Issue by cal940** [nextcloud/server#4360]
Right now this works only for users and not for groups.

**Comment by LukasReschke** [comment]
So what is the feature request here? An group admin is able to administrate only the group. So you want a group where everybody can administrate the group…?

**Comment by cal940** [comment]
Example: 

1) There are group A and group B
2) Each user of group A should have group admin permission for group B.

**Comment by MorrisJobke** [comment]
I guess this would make things super complicated because we need to add another layer for permissions.

👎 from my side


@karlitschek @blizzz @nickvergessen @schiessle Opinions?

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
