### ISSUE TITLE
Link formatting changed (after upgrading to NC28?) when opening files [same in latest v27 too]

### ISSUE THREAD

**Issue by cguillaumie** [nextcloud/server#43606]
**Describe the bug**
after migration, our links to open files in collabora changed from :
https://ourcloud.contoso.com/apps/files/?dir=/path_to_the_dir&openfile=138540
to :
https://ourcloud.contoso.com/apps/files/files/138540?dir=/path_to_the_dir&openfile=true

**To Reproduce**
nothing to do always the same

**Expected behavior**
reverse this formatting or change it on the fly?

**Client details:**
 - OS: windows 10 or 11
 - Browser chrome or firefox last version
 - Version last
 - Device: all

## Server details

**Operating system**: ubuntu 22.04

**Web server:** nginx

**Database:** mariadb

**PHP version:** 8.1

**Nextcloud version:** 28.02

**Version of the richdocuments app** 8.3.1

**Version of Collabora Online**: 23.5.705

**Configuration of the richdocuments app**
```
{
    "apps": {
        "richdocuments": {
            "canonical_webroot": "",
            "disable_certificate_verification": "yes",
            "enabled": "yes",
            "external_apps": "",
            "installed_version": "8.3.1",
            "public_wopi_url": "https:\/\/cloud.contoso.com",
            "types": "prevent_group_restriction",
            "wopi_allowlist": "0.0.0.0\/0",
            "wopi_url": "https:\/\/cloud.contoso.com\/apps\/richdocumentscode\/proxy.php?req="
        }
    }
}
```

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by szaimen** [comment]
cc @nextcloud/server-frontend

**Comment by susnux** [comment]
The official supported URL to use for linking to files is `/f/FILEID` that worked with "old" versions of Nextcloud and is also working with Nextcloud 28.

Meaning in your case it would be `https://ourcloud.contoso.com/f/138540`

This can also be accessed from the sharing tab by using the "internal link".

**Comment by joshtrichards** [comment]
I took the original report to be about the URLs that show up while opening files (e.g. Office, Markdown) from within Files in the browser URL slot. That's also how I tested against v27 & v28.

**Comment by joshtrichards** [comment]
And this:

> https://ourcloud.contoso.com/apps/files/?dir=/path_to_the_dir&openfile=138540
> to :
> https://ourcloud.contoso.com/apps/files/files/138540?dir=/path_to_the_dir&openfile=true

...also stood out because of the fileId and openfile parameters changing. Mostly the `openfile=true` versus `openfile=<fileId>` which stands out as a little weird to me, but maybe that's just an change internally and not a problem.
