### ISSUE TITLE
[Bug]: Fresh tarbal install doesn't allow (even first) admin login

### ISSUE THREAD

**Issue by greenais** [nextcloud/server#43614]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Fresh latest tarball installation on Debian 12 with nginx and MariaDB, all the latest from Debian repos as well.

After successful, according to final message in web or CLI (tried both ways), installation NC shows login page but doesn't accept admin login/password set during installation.

Resetting password via occ (again success confirmation) doesn't work as well - login/password still don't accepted.

Configs set according to official docs, re-checked plenty of times.
I'm a quite long-term NC user (since OwnCloud times), did installs/upgrages a lot  but encounter such a bug for the first time.

### Steps to reproduce

1.Install tarball prviding admin login/pass
2.Open login page
3.Try to log-in

### Expected behavior

NC lets log-in first time

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "ms",
            "192.168.1.3"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.2.5",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - encryption: 2.16.0
  - files_external: 1.20.0
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0
```

### Nextcloud Signing status

```shell
Not available due to no-login
```

### Nextcloud Logs

```shell
data/nextcloud.log is empty
```

**Comment by greenais** [comment]
Thank you for your prompt reply, I very appreciate such an attention.
In fact I've already found root of the issue (tnx to your advice to deep check browser logs) - just one little thing I missed in nginx site config editing:
`fastcgi_param HTTPS on;` - changing it to off resolved problem immediately

My NC setup is strictly local, so no need in https/TLS stuff with users frightening self-signed certs. 
Unfortunately there is no howto for such cases, despite the phrase _"and it is accessed via http(s)://cloud.example.com/"_ in nginx config docs, no http-only settings. I close this issue as it's obviously not a bug, but leave my answers for those why may bump in similar situation. Thank you again! 

> Which does it say precisely? Is it _Temporarily Error_ or is it _Wrong username or password_ or something else?
Nothing, just reloads login page with empty password field
> What does log entry look like in your Nginx access log?
Nothing special, just ordinary requests for img, css and other usual stuff
> Is this all through `http://localhost` or something else?
It's machine in local network, so URL looks like http://ms/index.php/login?clear=1
> I assume you double-checked in a different browser too, correct?
For sure: FF, Chrome. Chromium, Opera
> Can you also check your browser console and browser console network tab for clues?
That's what worked finally: I noticed warnings like "can't save secure cookie from insecure source" or something like this 
> I know you mentioned you used the documented Nginx config, but just to confirm... You're using the one from the v28 manual and nothing pre-v27 (since the Nginx config was updated), correct?
I'm not sure how to determine v28, it was only offical one I found 
[here](https://docs.nextcloud.com/server/21/admin_manual/installation/nginx.html)

**Comment by joshtrichards** [comment]
> fastcgi_param HTTPS on; - changing it to off resolved problem immediately

Glad you got it worked out!

> Unfortunately there is no howto for such cases, despite the phrase "and it is accessed via http(s)://cloud.example.com/" in nginx config docs, no http-only settings.

The full config there includes an http -> https redirect (the first `server` block). That's  that it's referring to I believe.

> I'm not sure how to determine v28, it was only official one I found here

FYI that link is for Nextcloud v21.

Make sure you're referencing the one from the Admin Manual that matches the version of Nextcloud Server you're using (visit https://docs.nextcloud.com and choose the appropriate version). 

We do update the config at times and it's had several critical changes the past couple versions. You'll definitely have some problems using a v21 config with a v28 installation.
