### ISSUE TITLE
[Bug]: Changing a filename from .md to .txt DELETES everything in the file and creates an EMPTY txt file

### ISSUE THREAD

**Issue by maniac-0s** [nextcloud/server#43615]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I started an .md file there I wanted to collect links. During this I notice that nextcloud for some reason sometimes on instagram links pulls preview from instagram and puts it in **without any possibility to remove it** (except removing the link). To mitigate that I thought I just change it into a txt file instead of md. But that deleted the whole text and created an empty text file. I now have to write everything again...

### Steps to reproduce

1. Create md file
2. write something
3. change .md into .txt
4. this produces an empty text file with everything written previously being deleted without any warning

### Expected behavior

Just change the .md to plain text OR at least give a WARNING before deleting everything.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by DatNoHand** [comment]
I can reproduce it on 28.0.2

**Comment by mejo-** [comment]
This is an issue in the Text app and already tracked here: https://github.com/nextcloud/text/issues/5736

Closing as duplicate.
