### ISSUE TITLE
[Bug]: Invalid Hash `photos` app on new install

### ISSUE THREAD

**Issue by wildBcat** [nextcloud/server#43623]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On a new install of Nextcloud (version 28.0.2) I see the following in security and setup warning: `Some files have not passed the integrity check.`
On checking the info it shows:
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- photos
	- INVALID_HASH
		- js/photos-public.js.map

Raw output
==========
Array
(
    [photos] => Array
        (
            [INVALID_HASH] => Array
                (
                    [js/photos-public.js.map] => Array
                        (
                            [expected] => 156a4e6ebf2f4e618a501a6017e37549ac3042320ea006f4f0b1b30361e43c5b087328cdd8c84a46992d86e03499b3dd8924b6e033f16b60306c80aefe20e51c
                            [current] => 9dd7815c8149a81e3e36ab8b348016c172c10f4710b262224aa6e134f9217ca2a70cfa5ccd6af9479f08473d80ec3b4d92a66e8b38469e92d7a68ae5a07e74f7
                        )

                )

        )

)
```
I have tried replacing the photos-public.js.map file on my instance with the one from here: https://nextcloud.com/changelog/ but it simple hase a different (but still invalid) hash.

### Steps to reproduce

1. Install Nextcloud and connect db
2. login and go to administrator settings
3. wait for security scan to finish

### Expected behavior

I would assume the correct has should come with the install files obtained during docker container download.

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
> Community Docker image

Which image, specifically? 

Are you sure you're not reusing an old persistent data volume/bind mount or something like that with your container?

I don't see this at all in any of my test v28 environments.

Please share:

- your Docker Compose file / run command
- output of `occ config:list` system
- output or `occ app:list`

Thanks!

**Comment by wildBcat** [comment]
@joshtrichards Thank you for the quick response! I am very new to this stuff, so it is possible I am doing something wrong. I just did some more research and found I pulled lscr.io/linuxserver/nextcloud:latest in my yaml file. I am not sure, but I assume that this is not an official image (like https://hub.docker.com/_/nextcloud). I tired accessing occ but I get: `Could not open input file: occ`
My Yaml file:
---
# https://hub.docker.com/r/linuxserver/nextcloud
# https://docs.linuxserver.io/images/docker-nextcloud
# only x86-64 and arm64 are supported
version: "2.1"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - [REDACTED]/nextcloud/config:/config
      - REDACTED]//nextcloud/data:/data
    ports:
      - 1253:443
    restart: unless-stopped

**Comment by joshtrichards** [comment]
Correct. That's a third party image done by the friendly folks @linuxserver. I suggest you post on either our Nextcloud Help Forum or their LinuxServer.io Help Forum to see if you can either find someone else with the same situation or get some help troubleshooting it.

Going to close this Issue out here since there's no evidence it's a bug on our end, but don't hesitate to follow-up if later proven otherwise.

```
volumes: 
- [REDACTED]/nextcloud/config:/config
- REDACTED]/nextcloud/data:/data
```

I don't remember their app folder structure since their latest image reorganization, but if you started up a prior container using these same folders, it's possible you have some outdated app folder(s) somewhere in your data structure. I'll leave that to pin and the forums to troubleshoot. :-)

**Comment by wildBcat** [comment]
Thank you so much for your help!
