### ISSUE TITLE
Conflict dialogue doesn't show preview for new file any more

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#4363]
### Steps to reproduce

1. Upload an image
1. Upload it again

### Expected behaviour

The conflict dialogue should show me the image twice

### Actual behaviour

I only see one image
On the left, there is a blank icon

### Server configuration

**Operating system**: FreeBSD

**Web server:** Apache 2.4

**Database:** MariaDB 10.1

**PHP version:** 7.0.18

**Nextcloud version:** master

**Updated from an older Nextcloud/ownCloud or fresh install:** rolling

**Where did you install Nextcloud from:** git

**Comment by MorrisJobke** [comment]
> On the left, there is a blank icon

What request is made and what is the response?

**Comment by oparoz** [comment]
No HTTP request is being made. The preview is generated in browser iirc. It receives a data stream `data:image/png;base64...`

**Comment by rullzer** [comment]
I just tested on latest master. It works just fine here...

**Comment by MorrisJobke** [comment]
I tested this in chrome, firefox and safari. All works fine. Please state the browser you have used and then we can look into this. Until then: Not reproducible and close ;)

**Comment by oparoz** [comment]
Thanks for checking. It was due to the fact that I'm blocking canvas fingerprinting on my standard browser, so of course this doesn't work... I have to remember to use a vanilla browser for testing...
