### ISSUE TITLE
[Bug]: Android Client Crashes Due to Incorrect Data Type Coming From Backend When Parsing Missing GPS and Photo Size Information

### ISSUE THREAD

**Issue by alperozturk96** [nextcloud/server#43649]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On the Android client side, we handle two types of data: XML and DavProperty. When user have valid gps and photo size metadata Android client parse both xml and dav property correctly. However if some data missing, it cause crash. 

For more detail: reported [issue](https://github.com/nextcloud/android/issues/12379)

When dealing with `<nc:file-metadata-size>` or `<nc:file-metadata-gps>`, we can parse it using either DavProperty or XML data. Backend introduced a new property called "EXTENDED_PROPERTY_METADATA_PHOTOS_SIZE". If this property is null, we switch to using "EXTENDED_PROPERTY_METADATA_SIZE" and try parsing it with DavProperty. If it's not null, we parse XML data instead.

However, some users encounter a class cast exception during XML parsing because certain GPS or size metadata might be missing.

If a new property (xml_data) is already exist, it should consistently return the same data type for `<nc:file-metadata-size>` or `<nc:file-metadata-gps>` so client side wont get class cast exception.

### Steps to reproduce

1. Have missing gps or image size exif info
2. Try to load image

### Expected behavior

The backend must consistently return the same data type for both `<nc:file-metadata-size>` and `<nc:file-metadata-gps>` **regardless if some data missing or not.** 

The client-side code expects these data types to remain consistent for handling purposes.

Any crash or misinformation should not be reflected on the user side.

Client Side [Fix](https://github.com/nextcloud/android-library/pull/1349)

### Installation method

Official All-in-One appliance

### Nextcloud Server version

28

### Operating system

Other

### PHP engine version

PHP 8.3

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by alperozturk96** [comment]
@artonge Have any idea about this? :)

**Comment by limburgher** [comment]
3.28.1 does seem to fix this for me.
