### ISSUE TITLE
Import personal data (address, phone, ...) from LDAP

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#4365]
would be VERY USEFUL to have ability to use phone or mobile (some other LDAP attribute or even scheme) as value for user Profile/Phone. same about address (Profile/Address). it feels very stupid when you have to enter it manually especially since it was already entered in LDAP. i truely believe LDAP module have to be SIGNIFICANTLY extended!

i'm sure many of us find it useful. thank you

**Comment by MorrisJobke** [comment]
cc @nextcloud/ldap

**Comment by mxulrich** [comment]
also for me and my cases it would be very useful!! 
thank you

**Comment by presidente74** [comment]
hi,
at the page nextcloud/ldap i found error 404!!
please, where i find this informations??
thanks!!! :)

**Comment by ChristophWurst** [comment]
ghost -> close
