### ISSUE TITLE
Disable "Video verification"

### ISSUE THREAD

**Issue by arno4000** [nextcloud/server#43662]
How can I disable the option "Video verification" when sharing a file or a folder to an email address? The option only pops up, when I set a password for the share.

I would like to disable it on my whole Nextcloud instance for all users. I am using Nextcloud version `27.1.5.1` with the official helm chart and the `-fpm` docker image.

![image](https://github.com/nextcloud/server/assets/50365065/f06a7280-8a08-4ed5-8620-45965177f4f3)

**Comment by solracsf** [comment]
Please ask your questions at https://help.nextcloud.com or at Reddit: https://www.reddit.com/r/NextCloud/comments/1auq9xn/disable_video_verification/

Use Github for bug reports. Thanks 👍
