### ISSUE TITLE
Dropbox doesn't sync changes as it should and syncing breaks on DMCAed files

### ISSUE THREAD

**Issue by C0rn3j** [nextcloud/server#4367]
https://github.com/owncloud/client/issues/5708

I've already reported the DMCA issue to owncloud's client repo, please read that first, I am not sure whether this should be reported here too but I guess it should, as this is the core of the problem.

After removing said DMCA'd files from Dropbox, Nextcloud doesn't appear to sync (despite set to "sync once every direct access") the files as deleted, and keeps trying to downloading them and failing.

It's also not syncing any other files, even those that aren't flagged.

Trying to download the affected file from the web interface results in this. http://i.imgur.com/nlIBeXR.png

The workaround to this issue is deleting the files through Nextcloud's web interface.

 
### Steps to reproduce
1) Reproduce steps from the issue linked above
2) Delete affected file(s) from Dropbox
3) Try to sync - it'll still fail even though the files are not on Dropbox anymore.

### Server configuration
**Operating system**: Linux c0rn3jRPi3B 4.9.22-1-ARCH #1 SMP Fri Apr 14 19:20:54 MDT 2017 armv7l

**Web server:** nginx/1.12.0 (fpm-fcgi)

**Database:** mysql 10.1.22

**PHP version:** 7.1.4
Modules loaded: Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, PDO, session, posix, readline, Reflection, standard, SimpleXML, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, curl, gd, iconv, intl, mysqli, pdo_mysql, zip

**Nextcloud version:** 11.0.2 (stable) - 11.0.2.7

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** 
ArchARM repositories.

**Signing status:**
<details>
	<summary>Signing status</summary>

```
[]
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.4.1
 - comments: 1.1.0
 - dav: 1.1.1
 - federatedfilesharing: 1.1.1
 - federation: 1.1.1
 - files: 1.6.1
 - files_external: 1.1.2
 - files_pdfviewer: 1.0.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - firstrunwizard: 2.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.0
 - notifications: 1.0.1
 - password_policy: 1.1.0
 - provisioning_api: 1.1.0
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - survey_client: 0.1.5
 - systemtags: 1.1.3
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - updatenotification: 1.1.1
 - workflowengine: 1.1.1

Disabled:
 - admin_audit
 - encryption
 - external
 - files_accesscontrol
 - files_automatedtagging
 - files_retention
 - templateeditor
 - user_external
 - user_ldap
 - user_saml
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "ocy3it817rpk",
    "appstoreenabled": true,
    "apps_paths": [
        {
            "path": "\/usr\/share\/webapps\/nextcloud\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/nextcloud\/apps",
            "url": "\/wapps",
            "writable": true
        }
    ],
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.c0rn3j.com"
    ],
    "datadirectory": "\/usr\/share\/webapps\/nextcloud\/data",
    "overwrite.cli.url": "https:\/\/cloud.c0rn3j.com",
    "dbtype": "mysql",
    "version": "11.0.2.7",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true
}
```
</details>

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OC\Files\Storage\DAV
    [2] => \OCA\Files_External\Lib\Storage\OwnCloud
    [3] => \OCA\Files_External\Lib\Storage\SFTP
    [4] => \OCA\Files_External\Lib\Storage\AmazonS3
    [5] => \OCA\Files_External\Lib\Storage\Dropbox
    [6] => \OCA\Files_External\Lib\Storage\Google
    [7] => \OCA\Files_External\Lib\Storage\Swift
    [8] => \OCA\Files_External\Lib\Storage\SFTP
    [9] => \OCA\Files_External\Lib\Storage\SMB
    [10] => \OCA\Files_External\Lib\Storage\SMB
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Operating system:**

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	Insert your webserver log here
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
	Insert your Nextcloud log here
	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
	Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
	```
</details>

**Comment by MorrisJobke** [comment]
Please test again with the new dropbox external storage app: https://github.com/icewind1991/files_external_dropbox
