### ISSUE TITLE
Bundle the twofactor_nextcloud_notification app and disable by default in order to make 2FA easier to use

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#43682]
As brought up by @jospoortvliet and discussed with @nextcloud/designers, it would be great to bundle the [twofactor_nextcloud_notification app](https://apps.nextcloud.com/apps/twofactor_nextcloud_notification) and enable the app by default in order to make 2FA easier to use without an admin having to know, find, install and enable the app.

cc @sorbaugh @nickvergessen

**Comment by sorbaugh** [comment]
Will be the case for NC30 :)
