### ISSUE TITLE
[Bug]:  Trash bin function failure  27.1.6

### ISSUE THREAD

**Issue by tiandiyiqi** [nextcloud/server#43687]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Upgrade from Skycloud 27.1.5 to Skycloud 27.1.6
Discovered that the Trash bin function is invalid, and there is nothing in the deleted file
The displayed content is:
No files in here
No files or folders have been deleted yet

### Steps to reproduce

1. Installing Skycloud 27.1.5
2. Upgrade to Skycloud 27.1.6 online or offline
3. Delete a file
4. Click on "Delete files",

### Expected behavior

1. Unable to recycle deleted files
2. Waste disk space

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "*.cymmetrik.com",
            "192.*"
        ],
        "defaultapp": "files",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "27.1.6.2",
        "overwrite.cli.url": "https:\/\/fedcloud.cymmetrik.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "job_properties": {
            "remote_info": {
                "login": {
                    "uri": "https:\/\/192.168.1.144:9443",
                    "username": "admin",
                    "password": "admin"
                },
                "action": {
                    "uri": "https:\/\/192.168.1.144:9443"
                },
                "view": {
                    "uri": "https:\/\/192.168.1.144:9443",
                    "path": "\/myworkspace\/#\/viewer",
                    "param": "file:\/\/esko23\/FedCloud\/Viewer\/",
                    "mode": "page"
                }
            },
            "fixed": {
                "Normal": {
                    "tickets": {
                        "filters": {
                            "prop": "description",
                            "values": [
                                "fed",
                                "chk"
                            ]
                        }
                    }
                },
                "Submit": [
                    "CreatJob"
                ],
                "Upload": [
                    "SyncFile"
                ]
            }
        },
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
```

**Comment by joshtrichards** [comment]
There was an accidental change introduced between v27.1.5 and v27.1.6. It's been fixed in #43259 and will be in the about to be released v27.1.7.
