### ISSUE TITLE
nextcloud client crash after changing server adress

### ISSUE THREAD

**Issue by tfourcade** [nextcloud/server#4368]
### Steps to reproduce
1.set up a home nextcloud server
2.install nextcloud client and sync folders
3.change server adress

### Expected behaviour
Not be able to able to sync folders anymore, which is ok. But i should be able to unsync folders and after changing the server adress re-sync folders again. 

### Actual behaviour
The client crashed and tell me there is a segmentation fault (core dumped) when i try to relaunch it. I trie to uninstall the client (apt purge nextcloud-client & apt auto-remove ) and install it again. but i got the same error. It works well on the another login of the computer.

### Server configuration

**Operating system**: ubuntu 16.04

**Web server:** apache2

**Database:** MariaDB

**PHP version:** PHP7

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** freshinstall

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by individual-it** [comment]
Looks like a client problem. The better place to report would be: https://github.com/nextcloud/client_theming

**Comment by tfourcade** [comment]
Ok, thanks
