### ISSUE TITLE
brute force protection for Nextcloud APIs

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#437]
As discussed last week in Stuttgart with @LukasReschke, it would be nice to have some kind of brute force protection for OCS/REST APIs. Maybe with a decorator where you can enable/disable it at the controller.

**Comment by ChristophWurst** [comment]
dup of https://github.com/nextcloud/server/issues/270?

**Comment by rullzer** [comment]
I agree it would be nice. But I still think protection here is better done on a firewall level. A lot of work has already been done at this point which makes DoS attacks way easier then if blocking would happen at the firewall level.

**Comment by jknockaert** [comment]
@rullzer Protection should ideally be done at the firewall level as I already argued in #270.
@ChristophWurst Ja this is a dup.

**Comment by jknockaert** [comment]
@LukasReschke I notice that this feature is to be implemented for 10. It would be good to consolidate the earlier thinking on this topic and link back. There's been discussion on the repo in #270, as well as on the forum.

**Comment by rullzer** [comment]
This is in https://github.com/nextcloud/server/pull/479
The logging that is done there coud be fed to fail2ban for example.
