### ISSUE TITLE
[Bug]: help for nextcloud problem on Umbrel

### ISSUE THREAD

**Issue by 3nricomaz** [nextcloud/server#43771]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I updated nextcloud on my umbrel to the latest version 20.0.2 but I had version 26 installed.
Since the update on Umbrel the app no longer starts and remains in "starting" for days.
I don't know what to do to avoid losing the data I had entered.
I would like some help considering that I am not very practical, I would like step by step help if possible.
I'm waiting, thanks
![next-1](https://github.com/nextcloud/server/assets/125125914/d3b9c1ae-f87b-48cc-8a44-5d0aac8a4dbf)

### Steps to reproduce

1.not run
2. "starting mode
3.

### Expected behavior

run

### Installation method

Other Community project

### Nextcloud Server version

28

### Operating system

Other

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
Please ask for support at https://help.nextcloud.com
Thanks 👍

**Comment by 3nricomaz** [comment]
https://help.nextcloud.com/t/help-update-nextcloud-umbrel/180846

**Comment by 3nricomaz** [comment]
https://community.umbrel.com/t/help-please-to-problem-update/15198

**Comment by 3nricomaz** [comment]
It's incredible that no one knows how to help me. The only solution remains to delete the Nextcloud app and use something else
