### ISSUE TITLE
Scan directories from UI?

### ISSUE THREAD

**Issue by maniac-0s** [nextcloud/server#43793]
Uploading via FTP is for some reason 5 times faster than via UI (and UI upload often fails on huge files).

But as far as I know for my files to be available in UI I need to rescan folders. Is there a way to do that via UI so that I don't have to SSH into my server all the time?

**Comment by ostasevych** [comment]
You may try to play with flows: eg trigger the script to scan files when eg file `scanme` appears in a directory.

**Comment by joshtrichards** [comment]
> Uploading via FTP is for some reason 5 times faster than via UI (and UI upload often fails on huge files).

This might be something to troubleshoot via the community help forum - https://help.nextcloud.com

> But as far as I know for my files to be available in UI I need to rescan folders. Is there a way to do that via UI so that I don't have to SSH into my server all the time?

No. But you can add a scan to your system cron in the same way as is sometimes done for External Storage: https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/external_storage_configuration_gui.html#adding-files-to-external-storages
