### ISSUE TITLE
Files not openning  (PDF and other formats). Decryption Problem

### ISSUE THREAD

**Issue by ConvarDeutschland** [nextcloud/server#43827]
**Describe the bug**
Files can not be opened anymore error in log file "Cannot decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you."

But error also appear if Im logged in as file owner so it it not the shared folder
It seem thet the files can not be decrypted anymore.

Some kind aof problem was already describe here when poeple upgrade to 27 and should be fix with 27.1.1 but we are on 27.1.6

Can I acces the server over ssh and try to decrypt the files over terminal ?
Can someone describe me how to do this

**Client details:**
 - OS: Manjaro Linux
 - Browser Chrome, Firefox
 
**Operating system**:
Debian Linux 12

**Web server:**
APache 2

**Database:**
MariaDB version 10.11.6

**PHP version:**
8.2.8

**Nextcloud version:**
Nextcloud 27.1.6

Thanks for any help

**Comment by joshtrichards** [comment]
When you download the file via ssh is it still encrypted?

What happens when you use the web UI's Download feature (e.g. via the 3-dot menu for the individual file entry) for that file (rather than trying to open it)?

Also please:

- post the entire raw log entry
- your config (e.g. `occ config:list system`
- your apps list (e.g. `occ app:list`)

Thanks 👍

**Comment by ConvarDeutschland** [comment]
@joshtrichards 
Sorry I can not publish to much informations about config on a public server

Yes over ssh the files still encrypted. Starting occ to decrypt it also not working. Downloading with Browser does not work. In the log you will have the error that the file can not be decrypted. I'm pretty sure it has something to do with the problems reported when updated from 26 to 27. So for now we have lost a part of the files because we went back to some backup from some days before the problem was first reported. But we have to stay with this files as the system is needed every day.

So if somebady have an idea what we can do to decrypt it, maybe as standalone we still have a physical copy of the encrypted files to try it. Can somebody tell me how does the OCC decryption command work if we have activated default encryption, we have no recovery key, and some users have deactivated the decryption option in there account. We also have a copy of the complete physical folder from the server (with config, and Private/public keys of each user). Can https://github.com/nextcloud/encryption-recovery-tools help us with this ?

**Comment by ConvarDeutschland** [comment]
So additionnal informations.

Case can be close

I did run an offline decryption using https://github.com/nextcloud/encryption-recovery-tools and most off the files  are decrypted now. So we  consider the case to be close for us. But I still do not know what  happend to the server between the last backup and last week, why some files could not be dectypted on the server

**Comment by KaeTuuN** [comment]
@ConvarDeutschland Please check the following (if still possible):
Compare this two Paths for a working and a not working file:
File: /-(path-to-nextcloud-data)-/-(user)-/files/-(path-to-file)-/filename (This should be an actual file)
Key: /-(path-to-nextcloud-data)-/-(user)-/files_encryption/keys/files/-(path-to-file)-/filename (This should be a folder!)
(Please replace all parts in -()- with your actual paths )

My suggestion: The working file does have a File named "fileKey" in the Key Folder, while the broken file does not.
