### ISSUE TITLE
Inconsistency in casing

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#4383]
\OC\Mail\EMailTemplate::render**HTML**

vs.

\OC\Mail\Message::set**Html**Body

Quite annoying as those are especially usually in the same line. I'd vote for changing the new `EMailTemplate` one into `renderHtml`.

cc @MorrisJobke @nickvergessen

**Comment by nickvergessen** [comment]
:+1:

**Comment by MorrisJobke** [comment]
Fix is in #4384
