### ISSUE TITLE
[Bug]: "+ Add" switches to "+ New" after loading

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#43847]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

| Files loading | Files loaded |
|--------|--------|
| ![Bildschirmfoto vom 2024-02-26 15-52-48](https://github.com/nextcloud/server/assets/1374172/ea326617-8a11-4949-8270-4cec54bf9a88) | ![Bildschirmfoto vom 2024-02-26 15-52-49](https://github.com/nextcloud/server/assets/1374172/cb86733c-6bb2-4744-bbad-86be60cde03b) | 

### Steps to reproduce

1. Open the Files app

### Expected behavior

Button text is always the same

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment]
Cc @nextcloud/server-frontend

**Comment by susnux** [comment]
This needs to be adjusted to `'New'`:

https://github.com/nextcloud/server/blob/656d3a4d825a9227a8c8ae87bd19669ce9c892fc/apps/files/src/views/FilesList.vue#L52
