### ISSUE TITLE
[Bug]: String `(copy)` misplaced with some filenames

### ISSUE THREAD

**Issue by Solar-Simon** [nextcloud/server#43843]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When you copy a File to the same folder as the original file is, the string "(copy)" is added to the file name.
If the filename consists a "." the "(copy)" is missplaced.

file.name.txt -> file (copy).name.txt

### Steps to reproduce

1. copy a File where filename consists a "." e.g. "file.name.txt"
2. copy to the same folder as origin
3. The copied file is renamed file.name.txt -> file (copy).name.txt

### Expected behavior

file.name.txt -> file.name (copy).txt

### Installation method

Other Community project

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by susnux** [comment]
Which version of Nextcloud are you using exactly?
Because I can neither reproduce with 28.0.2 nor with 28.0.3

![image](https://github.com/nextcloud/server/assets/1855448/ba836543-5c5e-44e4-8e00-be7d818eebeb)

**Comment by Solar-Simon** [comment]
apparently my bug report applies only to folders.

![grafik](https://github.com/nextcloud/server/assets/66730800/e97ce93c-6ac9-458c-bda3-f7e83f6ce117)

**Comment by skjnldsv** [comment]
Ah, fun!
Thanks for the report :)
