### ISSUE TITLE
Create a `security.txt` that is shipped with Nextcloud

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#43899]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

Shipping a `security.txt` with every Nextcloud installation could be a great addition.
So every researcher/pentester could report directly to official Nextcloud security channels (hackerone, etc).

**Describe the solution you'd like**

See https://securitytxt.org/

**Comment by joshtrichards** [comment]
See #27628 :-)

https://github.com/nextcloud/server/blob/master/apps/settings/lib/WellKnown/SecurityTxtHandler.php

Or do you mean an actual text file in the distribution package?

**Comment by solracsf** [comment]
No, that's it :-D
