### ISSUE TITLE
Documentation: instructions how to run master checkouts would be helpful

### ISSUE THREAD

**Issue by pmattern** [nextcloud/server#439]
Unlike release archives checkouts of master don't run out of the box, e. g. initializing Git submodules is necessary and then still the JavaScript stuff isn't ready to go. But documentation how to set up a system based upon Git master doesn't seem to be available.

IMO it would help testing a lot if you could write a tiny how to about this topic, maybe something similar as included in the News app's [README.md](https://github.com/nextcloud/news).

(I'm aware of #16. But if I'm not mistaken this is rather about release archives, not so much about VCS checkouts.)

**Comment by MorrisJobke** [comment]
> initializing Git submodules is necessary and then still the JavaScript stuff isn't ready to go.

A `git submodule update --init` should be enough. If there is still something missing it is a bug. What error do you get?

**Comment by pmattern** [comment]
> What error do you get?

The initial overlay informing about clients
![nextcloud_git-vs-installation_pop-up-clients](https://cloud.githubusercontent.com/assets/9860801/16954526/7712f614-4dd1-11e6-9a8f-5a668a547b9a.png)
doesn't come up.
Compared to 9.0.53
![nextcloud_git-vs-installation_all-files-9 0 53](https://cloud.githubusercontent.com/assets/9860801/16954535/7dcf0fe2-4dd1-11e6-8ecd-b860caa85c92.png)
pane "All files" is a bit sparse.
![nextcloud_git-vs-installation_all-files-vcs](https://cloud.githubusercontent.com/assets/9860801/16954547/85eb8caa-4dd1-11e6-8731-68f8ce86ea76.png)
More importantly, the Browser's download dialogue comes up after clicking on some uploaded graphics files with extension `*.jpeg`, `*.jpg` and `*.png` instead of the viewer overlay that can be seen with 9.0.53 (same sample files as well as the ones included in the release archive).
Arch Linux x86_64, Apache 2.4.23, PHP 7.0.8, SQLite 3.13.0. 13a2553 compared with 9.0.53 by setting up both exactly the same way. Memory cache left unconfigured to ease testing, no other complaints in section "Security & setup warnings" of pane "Admin" as seen by a Nextcloud administrator.

IMO some documentation how to run Git checkouts the right way would be helpful even if the findings above are due to bugs and not due to a faulty set up.
It would help users rule out a faulty set up as underlying reason of their findings and hence make them realize it's a bug.

**Comment by MorrisJobke** [comment]
> The initial overlay informing about clients doesn't come up.

That is a separate app you need to get: https://github.com/nextcloud/firstrunwizard (just clone it into the apps folder)



> pane "All files" is a bit sparse.

Just upload some files. (we add some sample files to the release but this is not really of any benefit for the development version)



> More importantly, the Browser's download dialogue comes up after clicking on some uploaded graphics files with extension *.jpeg, *.jpg and *.png instead of the viewer overlay that can be seen with 9.0.53 (same sample files as well as the ones included in the release archive).

Same here: This is the gallery app we just bundle https://github.com/owncloud/gallery (also just clone in the apps folder).



> Memory cache left unconfigured to ease testing, no other complaints in section "Security & setup warnings" of pane "Admin" as seen by a Nextcloud administrator.

Then you need to configure it (this is also not done with the release, because we don't know which one you want to use).



> IMO some documentation how to run Git checkouts the right way would be helpful even if the findings above are due to bugs and not due to a faulty set up.

https://git-scm.com/book/en/v2/Git-Branching-Branches-in-a-Nutshell

or

https://try.github.io/

I don't think that we should document how to use git. There are more then enough tutorials in the internet. We just say: `git clone` and `git submodule update --init` which works just fine. Documenting how to set up an instance with git is not wanted, because this is something we don't officially support (because signatures of the core aren't included in the git code).

**Comment by pmattern** [comment]
> I don't think that we should document how to use git.

Of course not! Maybe I wasn't clear. By "documentation how to run Git checkouts" I meant documentation how to deal with Git checkouts of Nextcloud, not how to handle Git itself.

A simple phrase saying that those two git invocations should allow for running development versions is virtually all I had in mind opening this issue.
This would allow for recognizing whether or not a problem one runs into is due to faulty dealing with the Git checkout and hence help testing which is the actual goal of this issue.
But note something like this is *not* available yet. At least at none of the locations where I'd personally expect it like the `README.md`. I've quickly added some according notes in a branch [readme-dev-version](https://github.com/pmattern/server/tree/readme-dev-version) which is at your disposal if you so wish.

**Comment by nickvergessen** [comment]
@pmattern want to turn the branch into a real Pull Request?

**Comment by pmattern** [comment]
Done and fixed in #1471.
