### ISSUE TITLE
[Bug]: Custom share folder setting isn't displayed anymore

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/server#43905]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Starting in with v28 and in current master the custom share folder setting isn't displayed anymore

### Steps to reproduce

1. Go to Personal settings -> sharing -> scroll down
2. No custom share folder setting, even though it's in the code

### Expected behavior

See the custom share folder setting

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

master

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

SQlite

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by AndyScherzinger** [comment]
@sorbaugh to late for 29.0.0 but to be scheduled for 29.0.1 then.

**Comment by Jerome-Herbinet** [comment]
Can't this be fixed in Nextcloud 28 ?

**Comment by AndyScherzinger** [comment]
> Can't this be fixed in Nextcloud 28 ?

If present in 28 also, than yes, sure.

cc @artonge since @sorbaugh is off atm
