### ISSUE TITLE
[Bug]: Missing releases (28.0.3, 27.1.7, 26.0.12)

### ISSUE THREAD

**Issue by Mat-DB** [nextcloud/server#43913]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The milestones are closed but there are no releases made for these minor versions.
The tags for these 3 versions are created.

Similar to: #41172 and  #39845 

### Steps to reproduce

/

### Expected behavior

The releases are made.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by blizzz** [comment]
thanks for reporting – done!

**Comment by LindezaGrey** [comment]
is there a problem with the release on dockerhub? i can't find it there 🤔

**Comment by blizzz** [comment]
> is there a problem with the release on dockerhub? i can't find it there 🤔

Which docker image do you refer to?

**Comment by LindezaGrey** [comment]
this one on dockerhub:
https://hub.docker.com/_/nextcloud/tags?page=1&name=28.0

**Comment by blizzz** [comment]
> this one on dockerhub: https://hub.docker.com/_/nextcloud/tags?page=1&name=28.0

Please try the team at https://github.com/nextcloud/docker/issues
