### ISSUE TITLE
[Bug]: enable_previews set to false behaviour change

### ISSUE THREAD

**Issue by nicholasmatters** [nextcloud/server#43924]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

We disable previews as we have folders with a lot of images in the folder (10k+) 

if many users scroll this will overwork the webserver cpu
![image](https://github.com/nextcloud/server/assets/110801836/90a57694-f892-44b4-b1e6-9351242d86bf)

In version 27.0.6 setting enable_previews to false would stop the preview requests for previews and avoid the cpu cost of these request. 
![image](https://github.com/nextcloud/server/assets/110801836/3756af3f-48ec-4bf0-a1d7-22e7ea12fbb4)

In version 28.0.2 enable_previews set to false stops previews icons being displayed but doesn't stop the requests for previews.
![image](https://github.com/nextcloud/server/assets/110801836/227689e9-7449-41cc-8f17-0e327f3bc21a)

### Steps to reproduce

1. Disable enable_previews - occ config:system:set enable_previews --value=false
2. Load directory with files and open web tool and monitor the network while scrolling the folder
3. look at CPU impact of server during scrolling

### Expected behavior

Not to send a preview image request when enable_previews is set to false

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.3

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

**Comment by skjnldsv** [comment]
Hey! Thanks for the report!

That's weird, because the dav backend should return false to `hasPreview` :thinking: 
https://github.com/nextcloud/server/blob/475dd6035435e326b0ffab6e74f961757896b97d/lib/private/PreviewManager.php#L241-L244

Can you give us the entire preview url please? (you can leave out the domain)

**Comment by inthreedee** [comment]
A possible explanation for this is that previews may not actually be disabled by following the above steps.

On my snap install of nextcloud, running `occ config:system:set enable_previews --value=false` sets the following in my config:
`'enable_previews' => 'false',`
Previews were still being generated for me.

Looking at other false values in my config, I noticed none of the others had quotes around false. So, I removed the quotes to make the entry:
`'enable_previews' => false,`
And previews were no longer being generated.

**Comment by skjnldsv** [comment]
> On my snap install of nextcloud, running `occ config:system:set enable_previews --value=false` sets the following in my config:

You need to use the `--type=boolean` flag.
![image](https://github.com/user-attachments/assets/ed635fd1-f19b-498d-a0fe-a6e89f9ba287)
