### ISSUE TITLE
Configurable binary path for Mailer/etc

### ISSUE THREAD

**Issue by exi** [nextcloud/server#43922]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I'm running nixOS where binaries are in non-standard locations. I can't use the sendmail sender because I can't give nextcloud the path to the binary or any kind of search path. It would be very helpful to make this configurable.

**Describe the solution you'd like**
A config option with additional paths that get searched in BinaryFinder

**Comment by joshtrichards** [comment]
Just to double-check: you should be able to use SMTP mode instead. It has no dependency on a local `sendmail` binary.

To your enhancement idea: I wonder if we should simply add PHP's own `sendmail_path` parameter value to our `sendmail` binary search path? This would offer an opportunity for local customization.

**Comment by exi** [comment]
@joshtrichards my mail setup uses local delivery without localhost-SMTP, so sendmail is my preferred solution.

Fixing BinaryFinder is the more general solution though since for example under NixOS, it't won't be able to find any of the expected binaries in those hard-coded locations seen in the existing BinaryFinder. Making this configurable would also allow NixOS to properly make nextcloud immutable and reproducible because it would allow us to pin the location of all involved binaries, as is standard in NixOS.

Using sendmail_path would be a working workaround, although not my preferred one.

**Comment by exi** [comment]
@joshtrichards I don't quite agree with changing the title here. This problem goes beyond sendmail.

Finding avconv/ffmpeg/libreoffice/openoffice etc. for preview generation also does not work without customizable search paths. 
Basically BinaryFinder does not work at all under NixOS without the ability to add additional searchPaths to search for.
None of the standard search paths hard-coded in BinaryFinder exist in NixOS.

**Comment by kesselb** [comment]
Adding a configuration option to adjust the binary path sounds okay to me. 
However, our security folks may have a different opinion. 

Please don't hesitate to send a pull request.

**Comment by exi** [comment]
@kesselb See #43968 for the PR, I hope that works out.
