### ISSUE TITLE
quota_include_external_storage is ignored while uploading using the NextCloud client

### ISSUE THREAD

**Issue by r3pek** [nextcloud/server#4394]
### Steps to reproduce
1. Set quota_include_external_storage = false
2. set a user's quota = 0
3. create a file on an external storage via web browser
4. create a file on the "local external folder" synced by the nextcloud desktop client

### Expected behaviour
Steps 3 and 4 should both work.

### Actual behaviour
Step 4 fails with "insufficient storage available"

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by MorrisJobke** [comment]
Could be related to #4816

**Comment by MorrisJobke** [comment]
Fixed by #6483
