### ISSUE TITLE
[Bug]: "Delete file" and "Delete folder" context menu items not localised on v27.1.7

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#43947]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Files context menu items `Delete file` and `Delete folder` appear to be not localised after the last update from 27.1.6 to 27.1.7.

### Steps to reproduce

1. Click context menu and observe the issue.
![image](https://github.com/nextcloud/server/assets/5199030/cbb1f646-b15d-4eb0-a4b9-595d0ac8f315)

### Expected behavior

Should be localised.

### Installation method

None

### Nextcloud Server version

26

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

in uk.js I observe the change of the format from the last version:
in 27.1.6:
```
    "Delete file" : "Вилучити файл",
    "Delete folder" : "Вилучити каталог",
```
in 27.1.7:
```
    "_Delete file_::_Delete files_" : ["Вилучити файл","Вилучити файли","Вилучити файли","Вилучити файли"],
    "_Delete folder_::_Delete folders_" : ["Вилучити каталог","Вилучити каталоги","Вилучити каталоги","Вилучити каталоги"],
```

Is this something related to?

**Comment by susnux** [comment]
My guess here: We take translations from master / stable28 were that string is pluralized due to batch actions being possible.
But we should update changes like that to older stable branches.

Maybe @skjnldsv knows more about the CI that updates the translations?

**Comment by skjnldsv** [comment]
Is this actually translated on transifex?

**Comment by ostasevych** [comment]
> Is this actually translated on transifex?

Sure :)
https://app.transifex.com/nextcloud/nextcloud/translate/#uk/files/483799062?q=text%3A'delete+file'

**Comment by susnux** [comment]
As said my guess it that we update translations from current master -> so the string is now pluralized and thus the frontend translate function can not translate it anymore.

**Comment by skjnldsv** [comment]
I don't remember how it works.
if that was the case, it would mean every non-master releases would have translations missing for years no?
I mean, we change a lot of apps and various strings...

**Comment by ostasevych** [comment]
> "_Delete file_::_Delete files_" : ["Вилучити файл","Вилучити файли","Вилучити файли","Вилучити файли"],
>     "_Delete folder_::_Delete folders_" : ["Вилучити каталог","Вилучити каталоги","Вилучити каталоги","Вилучити каталоги"],

Is this formatting supported in 27.1.x?

**Comment by skjnldsv** [comment]
@blizzz @nickvergessen do you know more?

**Comment by nickvergessen** [comment]
Strings from all versions we translate are combined.

But the string looks a bit weird anyway as the number is not included?
Do you have a link to the respective source code?

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/blob/12fe86573f87f120679b4423c8023a39e63b8868/apps/files/src/actions/deleteAction.ts#L90
https://github.com/nextcloud/server/blob/12fe86573f87f120679b4423c8023a39e63b8868/apps/files/src/actions/deleteAction.ts#L97

**Comment by susnux** [comment]
So yes this is a problem of combining the strings, if it was singular previously and then the same string is provided as plural option we can not use it anymore in the frontend. (Because the translation key is merged into a plural version and thus we can not detect it anymore).

Two fixes possible:
1. Also change 27 and 26 to the plural version (easy)
2. Adjust our translation logic to somehow figure out the plural key and try that one as well. (harder)

**Comment by nickvergessen** [comment]
That being said, the strings in https://github.com/nextcloud/server/blob/12fe86573f87f120679b4423c8023a39e63b8868/apps/files/src/actions/deleteAction.ts#L90 are "undistinct" plurals.

So this could be changed to a "non-pluraled" string as they do not need to follow a dedicated plural rule as you basically want to say "Delete many folders" so something like this would work:
```js
	if (isAllFolders(nodes)) {
		if (nodes.length === 1) {
			return t('files', 'Delete folder')
		}
		// We don't really want to count and show the number, so using generic plural instead of a pluraled-string
		return t('files',  'Delete folders')
	}
```

**Comment by nickvergessen** [comment]
That being said, I think it's a bug from the tooling that it can not handle translations of the same string that is a plural

**Comment by nickvergessen** [comment]
> Far less clean though 🙃

But what you do (translating a plural without a number in it) is confusing for translators of languages that have 6 plural forms. How should they guess that they need to put in the "undistinct" in all of them.

**Comment by nickvergessen** [comment]
the English one is `_singular_::_plural_` 
https://github.com/nextcloud/server/blob/8b4864fcade6a43e72bc6fb6540790885534b691/apps/files/l10n/de.js#L75

but this is really not the way to go. Just don't use plurals for this, unless you have the `%n` in it.

**Comment by ostasevych** [comment]
Hi! How is that solved? In the recent 27.x upgrade I cannot find the updated localisation :(

**Comment by nickvergessen** [comment]
It was fixed right after the release and backporting is still to be done next week

**Comment by ElSi-DVT** [comment]
Problem still exists in 27.1.8
