### ISSUE TITLE
[Bug]: Navigation Menu (sidebar) CSS transition is janky with sharp corners

### ISSUE THREAD

**Issue by RayBB** [nextcloud/server#43969]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When you collapse a navigation menu there is a moment of jank where everything is overlapped, and the corner is sharp and looks bad. You can see it in [this video](https://www.loom.com/share/ae34cf8f8a604076b708d48c718f6df8).

This only occurs on the desktop view, the transition works nice if you have a smaller viewport.

I know this isn't a big issue and questioned if it is even worth reporting but I see so many people complain NC is buggy and has all these problems. While I haven't felt that myself, I do feel that having UI issues like this can contribute to that feeling. 

I couldn't find another issue reporting this but I'm not even entirely sure if this is the right repo.

I'd be happy to take a look and submit a PR. I'd just like to make sure this hasn't been fixed yet on the latest branch and the  issue matters enough that someone would review it before I try getting a dev environment setup.

I think the file that will need to be changed is [apps.scss](https://github.com/nextcloud/server/blob/b4b3e7ceddd0ccac513ae1b0ba53eeba8ffad96a/core/css/apps.scss#L739)

Edit: Actually [NcAppNavigation.vue](https://github.com/nextcloud-libraries/nextcloud-vue/blob/89ba71e5a5647c7a0b6ff195c8cd2383bfe2fc41/src/components/NcAppNavigation/NcAppNavigation.vue#L253-L255) in nextcloud-libraries/nextcloud-vue should be changed.

This fix seems to be to change `&--close` to be just `margin-left: -300px;` (or `margin-left: $navigation-width`). For mobile to look nice we also need to remove the `:not` portion of [this line](https://github.com/nextcloud-libraries/nextcloud-vue/blob/89ba71e5a5647c7a0b6ff195c8cd2383bfe2fc41/src/components/NcAppNavigation/NcAppNavigation.vue#L287).

<details>
  <summary>Video of fix</summary>
  
  

https://github.com/nextcloud/server/assets/921217/0303ae9c-a791-4ed1-98c1-0755f81aa259

  
</details> 

<details>
  <summary>Screenshot of the moment of jank</summary>

  ![image](https://github.com/nextcloud/server/assets/921217/c4fa2ada-deae-4ba4-92c9-2b506e0c6007)
  
</details> 

PS: I also posted about this on [lemmy](https://lemmy.ml/post/12615841) and [reddit](https://old.reddit.com/r/NextCloud/comments/1b4y3eb/how_to_go_about_reportingfixing_this_nextcloud/).

### Steps to reproduce

1. Go to tasks, contacts, or any app with a collapsible sidebar
2. Collapse and open it

### Expected behavior

It collapses smoothly

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
Thanks for your report. 👍 

You should indeed:

1) Test with latest `master` branch first. There is a [Docker image available](https://github.com/szaimen/nextcloud-easy-test) to easily deploy it.
2) Submit your PR to https://github.com/nextcloud-libraries/nextcloud-vue

**Comment by RayBB** [comment]
Confirmed it on master with your image. Your image makes it every easy so thanks!

Will look into contributing to nextcloud-vue following their [development setup guide](https://github.com/nextcloud-libraries/nextcloud-vue?tab=readme-ov-file#development-setup).
