### ISSUE TITLE
Hide redis password when PHP throws an error

### ISSUE THREAD

**Issue by pankid** [nextcloud/server#43961]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I am seeing the redis password in the nextcloud logs when receiving a PHP error showing the session.save_path: 
`[PHP] Error: session_start(): Failed to read session data: redis (path: tcp://nextcloud_redis:6379?auth=<*** PASSWORD SHOWN IN PLAIN TEXT ***>) at /var/www/html/lib/private/Session/Internal.php#222`

**Describe the solution you'd like**
If possible, it would be nice if the redis password was redacted when this error was thrown. Other redis and backend database errors redact the password from being shown in the logs with "*** sensitive parameters replaced ***", such as the `RedisException: WRONGPASS invalid username-password pair or user is disabled` error. Is it possible to omit the redis password when the session.save_path is shown in a PHP error, or is this something that would need to be changed upstream? 

**Describe alternatives you've considered**
NA

**Additional context**
Here is the full error I am seeing my plain text password in logs: 

```
[PHP] Error: session_start(): Failed to read session data: redis (path: tcp://nextcloud_redis:6379?auth=<*** PASSWORD SHOWN IN PLAIN TEXT ***>) at /var/www/html/lib/private/Session/Internal.php#222

PROPFIND /remote.php/dav/files/<PATH TO FILE>
from <CLIENT IP> at 2024-03-02T04:14:37+00:00
```

I am using the community nextcloud docker image with nextcloud version 27.1.6 and php 8.2.16.

**Comment by joshtrichards** [comment]
That would be a question you'd have to take up with the PHP folks, since this isn't a Nextcloud error. It's coming from PHP itself. 

https://bugs.php.net/

Or, perhaps the the Redis PHP extension `phpredis`: https://github.com/phpredis/phpredis?tab=readme-ov-file#php-session-handler
