### ISSUE TITLE
[Bug]: Headers should not be empty when handled by Response.php

### ISSUE THREAD

**Issue by adriangibanelbtactic** [nextcloud/server#43995]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When using an app custom route headers are now empty. That ends up in the request ending up in an error.

Public AppFramework Response.php ' s getHeaders() is not able to handle empty headers.

This did not happen in Nextcloud 27.

### Steps to reproduce

1. Login onto your Zimbra
2. Use Open Drive tab
3. Try to open a file

### Expected behavior

You see the content of the file on your Open Drive tab.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "dev.nextclouddemo.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.3.2",
        "overwrite.cli.url": "https:\/\/dev.nextclouddemo.net",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "30,30",
        "simpleSignUpLink.shown": false,
        "upgrade.disable-web": true,
        "activity_expire_days": 30,
        "default_phone_region": "ES",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcache.locking": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "htaccess.RewriteBase": "\/",
        "user_backends": [
            {
                "class": "OCA\\ZimbraDrive\\Auth\\ZimbraUsersBackend",
                "arguments": []
            }
        ],
        "loglevel": 0,
        "maintenance": false
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - lookup_server_connector: 1.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - provisioning_api: 1.18.0
  - related_resources: 1.3.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - viewer: 2.2.0
  - workflowengine: 2.10.0
  - zimbradrive: 0.8.28
Disabled:
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - circles: 28.0.0-dev (installed 26.0.1)
  - contactsinteraction: 1.9.0 (installed 1.7.0)
  - dashboard: 7.8.0 (installed 7.6.0)
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 1.16.0)
  - files_external: 1.20.0
  - firstrunwizard: 2.17.0 (installed 2.15.0)
  - logreader: 2.13.0 (installed 2.11.0)
  - nextcloud_announcements: 1.17.0 (installed 1.15.0)
  - notifications: 2.16.0 (installed 2.14.0)
  - privacy: 1.12.0 (installed 1.10.0)
  - recommendations: 2.0.0 (installed 1.5.0)
  - serverinfo: 1.18.0 (installed 1.16.0)
  - support: 1.11.0 (installed 1.9.0)
  - survey_client: 1.16.0 (installed 1.14.0)
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - updatenotification: 1.18.0 (installed 1.16.0)
  - user_ldap: 1.19.0
  - user_status: 1.8.1 (installed 1.6.0)
  - weather_status: 1.8.0 (installed 1.6.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"3zms48Oezqi7E7HxMD70","level":3,"time":"2024-03-04T18:41:03+00:00","remoteAddr":"1.2.3.4","user":"6d170465-4e25-4454-bee6-36dc15fd7625","app":"PHP","method":"POST","url":"/apps/zimbradrive/api/1.0/GetFile","message":"Undefined array key \"\" at /home/dev.nextclouddemo.net/public_html/lib/private/AppFramework/Http.php#128","userAgent":"Apache-HttpClient/4.5.8 (Java/17.0.2)","version":"28.0.3.2","data":{"app":"PHP"}}
{"reqId":"3zms48Oezqi7E7HxMD70","level":3,"time":"2024-03-04T18:41:03+00:00","remoteAddr":"1.2.3.4","user":"6d170465-4e25-4454-bee6-36dc15fd7625","app":"index","method":"POST","url":"/apps/zimbradrive/api/1.0/GetFile","message":"array_merge(): Argument #2 must be of type array, null given","userAgent":"Apache-HttpClient/4.5.8 (Java/17.0.2)","version":"28.0.3.2","exception":{"Exception":"TypeError","Message":"array_merge(): Argument #2 must be of type array, null given","Code":0,"Trace":[{"file":"/home/dev.nextclouddemo.net/public_html/lib/public/AppFramework/Http/Response.php","line":273,"function":"array_merge"},{"file":"/home/dev.nextclouddemo.net/public_html/lib/private/AppFramework/Http/Dispatcher.php","line":179,"function":"getHeaders","class":"OCP\\AppFramework\\Http\\Response","type":"->"},{"file":"/home/dev.nextclouddemo.net/public_html/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/home/dev.nextclouddemo.net/public_html/lib/private/Route/Router.php","line":315,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/home/dev.nextclouddemo.net/public_html/lib/base.php","line":1069,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/home/dev.nextclouddemo.net/public_html/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/home/dev.nextclouddemo.net/public_html/lib/public/AppFramework/Http/Response.php","Line":273,"message":"array_merge(): Argument #2 must be of type array, null given","exception":{},"CustomMessage":"array_merge(): Argument #2 must be of type array, null given"}}
```

### Additional info

1) In order to properly test this you would need Zimbra 8.8.15 OSE installed with ZimbraDrive configured on it.

2) As I said:
- Nextcloud 27: This works ok.
- Nextcloud 28.0.2: Error described above.
- Nextcloud 28.0.3: Error described above.

3) My current workaround is to patch Nextcloud as here: https://github.com/adriangibanelbtactic/nextcloud-server/commit/b7e0b809eef6b6c01b4a658ecb053681a90f2394 .

4) zimbradrive versions you want to use:
- https://github.com/btactic/zimbra-drive/releases/tag/app-v0.8.27 for testing working scenario in Nextcloud 27
- https://github.com/btactic/zimbra-drive/tree/feature/nextcloud-28-v001 for testing non working scenario in Nextcloud 28

5) I know this is not easy to test if you don't master zimbradrive but I would like to have some feedback on this issue. Maybe you are not supposed to get into the getHeaders with empty headers from the main Nextcloud but you have not thought that this comes from an app handler?

Any feedback on what commit might have modified how headers are handled in Nextcloud 28 ?

Thank you very much!

**Comment by kesselb** [comment]
Hi,

https://github.com/nextcloud/server/blob/e072035e863e90191e9fc1ec460e8ee694b42672/lib/public/AppFramework/Http/Response.php#L53

Indeed $headers is defined as null.

https://github.com/nextcloud/server/blob/e072035e863e90191e9fc1ec460e8ee694b42672/lib/public/AppFramework/Http/Response.php#L101

The default constructor initializes headers with an empty array.

I think the proper fix, in your app, would be to call the parent constructor when extending the response class.

**Comment by adriangibanelbtactic** [comment]
> The default constructor initializes headers with an empty array.
> 
> I think the proper fix, in your app, would be to call the parent constructor when extending the response class.

It seems you were right.
I still need to do more tests but a quick test seemed to work.

For anyone that's interested this is how I solved it: https://github.com/btactic/zimbra-drive/commit/6f2e2217ab47a25b259a0bbe2c04bf994ec4a908 .

It's interesting how Dispatcher handles apps calls in https://github.com/nextcloud/server/blob/master/lib/private/AppFramework/Http/Dispatcher.php#L138 .
In the logs I had no reference to the app files so I thought that this was a problem of Nextcloud, that somehow, before the Http query ended up onto the app controller, there was something wrong with their headers and everything stopped to work.

Thank you very much!
