### ISSUE TITLE
small glitch in share permission drop down

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#4399]
As you can see at the screenshot below it looks like I could click at the current mouse pointer position to change the permissions but if I click nothing happens. 

![popover](https://cloud.githubusercontent.com/assets/1589737/25188702/3ed62ff4-2527-11e7-83d6-2410de16f9be.png)

I assume that this was introduced here where we expended the clickable area https://github.com/nextcloud/server/pull/3585

cc @MorrisJobke @jancborchardt @skjnldsv

**Comment by MorrisJobke** [comment]
Let me check that. Maybe the `<a>` as well needs to be extended.

**Comment by MorrisJobke** [comment]
Fix is in #4402

**Comment by schiessle** [comment]
fix merged
