### ISSUE TITLE
OC\AppFramework\Http\Request::REGEX_LOCALHOST does not match IPv6 localhost

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#440]
Found in https://github.com/nextcloud/server/pull/436#discussion_r71203760, not sure if this is really an issue, I didn't test it. See https://github.com/nextcloud/server/blob/f7d26e4aa523d684be6feda2b7a091b2c1548965/lib/private/AppFramework/Http/Request.php#L73

cc @MorrisJobke

**Comment by coderkun** [comment]
The regex for IPv6 localhost would look like

`/^(127\.0\.0\.1|localhost|::1)$/`

**Comment by MorrisJobke** [comment]
@coderkun Could I ask you to open a Pull Request with this change applied? That would be awesome :)
