### ISSUE TITLE
[Bug]: when using search to navigate into Files, the location path is not changing

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/server#44005]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

on c.nc.c

when navigating to another location when trying to copy/move a file, the location path remains the source one instead of following the user navigation

![image](https://github.com/nextcloud/server/assets/87175513/877d896b-2f04-4a17-822f-d52772209900)

### Steps to reproduce

0. navigate to some sub subfolder in your files
1. select a few files to move
2. click the copy/move button
3. click the home icon
4. you see the location path is not changing
5. navigate to another location, the path is still not changing

### Expected behavior

when navigating the files, location path should change accordingly.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by maximelehericy** [comment]
editing the issue, as this seems to be true not only in the copying modal, but also in the Files interface.

**Comment by maximelehericy** [comment]
it changes when I navigate clicking on subfolders to dive into the file tree. however, when using the search, if I click a folder among search results, the location path is not changing.

**Comment by sorbaugh** [comment]
odd, thanks for reporting!

**Comment by sorbaugh** [comment]
@Pytal can you take a look? I think we should get this one in for 28.0.4

**Comment by maximelehericy** [comment]
no it doesn't.

**Comment by maximelehericy** [comment]
@Pytal I can reproduce again...

**Comment by Pytal** [comment]
This is on the latest 29 beta @maximelehericy?

I checked again and cannot reproduce :(

Could you paste any errors or warnings that you see in the browser devtools?
