### ISSUE TITLE
[Bug]: Share views show everything as modified a few seconds ago

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#44026]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![Bildschirmfoto vom 2024-03-06 12-09-49](https://github.com/nextcloud/server/assets/1374172/d12d8942-66c5-41ed-9477-2ab3b9d1f8a7)

### Steps to reproduce

1. Open `/apps/files/sharingout`

### Expected behavior

Real modified dates

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ChristophWurst** [comment]
Actually the same for all of these views:

![image](https://github.com/nextcloud/server/assets/1374172/34e3b55f-6fb8-491f-bf29-cf9e19138327)

**Comment by skjnldsv** [comment]
![image](https://github.com/nextcloud/server/assets/14975046/94bb1145-81b2-4995-9428-9c57279fff92)

**Comment by skjnldsv** [comment]
Found!
Because every time we update an attribute, we assume the mtime changes

https://github.com/nextcloud-libraries/nextcloud-files/blob/e6d6537fe16745b83a37cee86ad10421056c405b/lib/files/node.ts#L49-L60

https://github.com/nextcloud/server/blob/7b9581129014f0c430272b8288ed9e45c0362499/apps/files_sharing/src/services/SharingService.ts#L179-L183
