### ISSUE TITLE
[Bug]: Sharing menu state not updated after "Create a new share link" with "Always ask for a password" admin setting

### ISSUE THREAD

**Issue by andrey18106** [nextcloud/server#44032]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

With Nextcloud 27.1.7 when the "Admin settings -> Sharing -> Always ask for a password" there is an incorrect sidebar sharing menu UI update after you "Create a new share link".

**Note**: After page reload it's displayed correctly.

### Steps to reproduce

1. Tick the Admin settings -> Sharing -> Always ask for a password checkbox
2. Try to create a new link share on any file
![1](https://github.com/nextcloud/server/assets/29692256/ca055631-4276-465f-be9d-a263c96cfdc9)

3. See the issue, after creating a link share sidebar menu UI does not refresh the state with created link share
![2](https://github.com/nextcloud/server/assets/29692256/d42b174e-eff3-4872-8c09-b9182a5ce866)

4. It's displayed correctly only after page reload

### Expected behavior

The sharing sidebar menu state is correctly reflected and refreshed after link share is created.

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

PHP 8.2

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by DatNoHand** [comment]
I can confirm that we have this issue aswell with 28.0.2

**Comment by andrey18106** [comment]
> I can confirm that we have this issue aswell with 28.0.2

With 28.0.3 it works fine

**Comment by sorbaugh** [comment]
> > I can confirm that we have this issue aswell with 28.0.2
> 
> With 28.0.3 it works fine

@Fenn-CS can we fix this in NC27 as well? I imagine backporting isn't an option due to files2vue but I'm not 100% sure..

**Comment by demkr** [comment]
The same problem on 29.0.14. If there is context present, even with Custom public Links where you put custom link token. Also when you create share with Context, not only that share icon is not updated, there is also Error deleting share notification when you Unshare that kind of share link.
If you create share without any context, icon is refreshed automatically and no Error deleting share notification is showing up.
