### ISSUE TITLE
Ship files_downloadlimit and enable by default

### ISSUE THREAD

**Issue by Pytal** [nextcloud/server#44038]
- [x] commit compiled js assets https://github.com/nextcloud/files_downloadlimit/pull/231
- [ ] Update shipped.json https://github.com/nextcloud/server/pull/44040
- [x] Add to release script https://github.com/nextcloud-gmbh/release-script/pull/169
- [x] Add to documentation https://github.com/nextcloud/documentation/pull/11618
- [x] Add to github helpers https://github.com/nextcloud/github_helper/pull/106

**Comment by blizzz** [comment]
@Pytal  added another todo - bundled apps have to have their js assets compiled in the repository. at the moment javascript is not being build by the packaging script.

**Comment by Pytal** [comment]
Thanks @blizzz!

We have a number of PRs which touch the compiled assets pending review, I've updated the TODO checkbox to commit these to source control after getting the linked PRs in

**Comment by blizzz** [comment]
@Pytal is this all realistic for beta1?

**Comment by Pytal** [comment]
From my side at least everything is ready @blizzz!

Thanks for all your preparatory PRs as well!
