### ISSUE TITLE
Skip version check for upgrades

### ISSUE THREAD

**Issue by Dreamsorcerer** [nextcloud/server#44045]
**Is your feature request related to a problem? Please describe.**
After upgrading my server and having a newer PHP version installed, I then needed to upgrade Nextcloud.
As upgrading Nextcloud must be done one version at a time, I found that installing the next version immediately gives an error because it doesn't support the latest version of PHP.

It can be incredibly difficult to downgrade PHP on a server, and is not really a viable solution just to upgrade the DB.

**Describe the solution you'd like**
When an upgrade is needed, skip the version check and allow the upgrade to run on newer versions of PHP. It seems rather unlikely that a newer version will break the upgrade code.

**Describe alternatives you've considered**
I ended up manually commenting out the version check to get the upgrade to run. Through 5 different version upgrades, no issues were encountered in relation to the PHP version installed.

**Comment by joshtrichards** [comment]
> When an upgrade is needed, skip the version check and allow the upgrade to run on newer versions of PHP. It seems rather unlikely that a newer version will break the upgrade code.

That's something of a gamble. "Unlikely" isn't sufficient reason for us to skip the checks. I'd say this is a "won't fix".

> It can be incredibly difficult to downgrade PHP on a server, and is not really a viable solution just to upgrade the DB.

I generally suggest people use the Sury packages (for Debian or Ubuntu via https://deb.sury.org/) or Remi Repository (Red Hat/etc via https://blog.remirepo.net/)

We also generally support 3 different versions of PHP per major Server version, so it's usually not necessary to do this more than once unless a deployed Server is many years out of date.

**Comment by Dreamsorcerer** [comment]
> maybe unless a deployed Server is many years out of date.

With Nextcloud, yes. Because there is still no Debian packages to automatically stay updated with (something I've been trying to work towards in #11075, but it took 6 years just to get the first step done).

I think requiring people to install different PHP packages, when the code should be reasonably backwards compatible seems a little extreme. As mentioned, I upgraded 5 different versions without an issue by removing the version check.
