### ISSUE TITLE
[Bug]: Can’t use `@` and Name for comments in Activity since comments and activities where merged together

### ISSUE THREAD

**Issue by imadevel** [nextcloud/server#44068]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello,

The issue you are facing: can’t use @ and Name vor comments in Activity since comments and activities where merged together.

Is this the first time you’ve seen this error? (Y/N): y

Nextcloud version: 28.0.2
Operating system: Debian GNU/Linux 12 (bookworm)
Apache 2.4.57-2
PHP 8.2.7

In our Nextcloud setup, user accounts are sourced from LDAP. Previously, users were displayed with their “Display Name” (real name) and a UUID beneath it in the user section. Moreover, the folders within /var/www/html/nextcloud/data also utilized UUIDs. However, this setup did not cause any issues since, in the old comment field, users could be found using their real name, displayed as ‘@givenname surname’ rather than ‘@UUID’.

This scenario applies to our test Nextcloud instance. Our production version has not yet been upgraded to version 28.x, but everything worked as expected there. I conducted some experiments with this test Nextcloud instance: under the LDAP Integration expert tab, I specified ‘sAMAccountName’ as the ‘Internal Username Attribute’ and cleared the LDAP mapping, despite warnings against doing so in a production environment. This change led to an interesting outcome: it became possible to search for usernames and use them after an ‘@’. However, this resulted in the test user receiving a completely new folder named after their username. Consequently, all files remained in the original folder labeled with the UUID and were no longer accessible to the test user. Although it might be feasible to move the files around, this task is complicated by the fact that the CalDAV URL no longer includes the UUID, necessitating changes on all user devices. Additionally, while it was possible to utilize the usernames, they did not appear in the user search; only the default 2-letter icon was displayed.

Now, I am somewhat perplexed. Is there a way to revert to the previous behavior in the Activities section when writing a comment, considering users are familiar with names, not UUIDs?

Also the Username Field is empty after the logo with the 2 letters (no pictures are shown of users like before), this happens also to internal users (not created by LDAP), but these users have the correct name not a UUID

This is how it looks, the search window looks like this
![2](https://github.com/nextcloud/server/assets/70377943/c5078fe5-381f-4578-9e3b-e1bd1c15b023)
![1](https://github.com/nextcloud/server/assets/70377943/0e45b8a4-d4ea-4d21-bb6f-130f15a41f68)

### Steps to reproduce

Hard to tell but having Users from LDAP Server in this case Zentyal, that have UUID as internal User names on a working Nextloud 27 and Update to 28

### Expected behavior

Users are visible by Name after you begin typing @Useername 

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.111.50.158",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.2.5",
        "overwrite.cli.url": "http:\/\/10.111.50.158\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "ISO 3166-2:DE",
        "force_language": "en_GB",
        "force_locale": "en_GB",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtptimeout": "30",
        "bulkupload.enabled": false,
        "maintenance_window_start": 1,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "Security"
        ],
        "twofactor_enforced_excluded_groups": [],
        "app_install_overwrite": [
            "pdfdraw"
        ]
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - announcementcenter: 6.7.0
  - approval: 1.2.0
  - calendar: 4.6.4
  - calendar_resource_management: 0.6.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.1
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - deck: 1.12.1
  - event_update_notification: 2.3.0
  - external: 5.3.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_accesscontrol: 1.18.0
  - files_automatedtagging: 1.18.0
  - files_external: 1.20.0
  - files_mindmap: 0.0.30
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_scripts: 4.0.2
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - flow_notifications: 1.8.0
  - forms: 4.1.0
  - impersonate: 1.15.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notes: 4.9.2
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - onlyoffice: 9.0.0
  - password_policy: 1.18.0
  - photos: 2.4.0
  - polls: 6.0.1
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - spreed: 18.0.3
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - tables: 0.6.6
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_ldap: 1.19.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflow_pdf_converter: 1.13.0
  - workflow_script: 1.13.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - circlesdb: 1.8.2 (installed 1.8.2)
  - collectives: 2.9.2 (installed 2.9.2)
  - discretepdfsigner: 0.0.4 (installed 0.0.4)
  - electronicsignatures: 2.0.5 (installed 2.0.5)
  - encryption: 2.16.0
  - files_fulltextsearch: 28.0.0 (installed 28.0.0)
  - files_fulltextsearch_tesseract: 27.0.0 (installed 27.0.0)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - fulltextsearch: 28.0.0 (installed 28.0.0)
  - fulltextsearch_elasticsearch: 28.0.0 (installed 28.0.0)
  - libresign: 7.1.1 (installed 6.3.1)
  - mailnotifier: 0.0.3 (installed 0.0.3)
  - maps: 1.3.1 (installed 1.3.1)
  - richdocumentscode: 23.5.705 (installed 23.5.705)
  - suspicious_login: 6.0.0
  - twofactor_gateway: 0.20.0 (installed 0.20.0)
  - twofactor_totp: 10.0.0-beta.2 (installed 7.0.0)
  - twofactor_webauthn: 1.3.2 (installed 1.3.2)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional info

LDAP Server is a Zentyal Server

**Comment by solracsf** [comment]
Please upgrade to 28.0**.3** and report back. Thanks.

**Comment by imadevel** [comment]
28.0.3 fixed it
