### ISSUE TITLE
[Bug]: Nonstandard server port ignored, redirecting to :443

### ISSUE THREAD

**Issue by michnovka** [nextcloud/server#44071]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I open
https://my.nextcloud.domain.com:9443/ I get HTTP 302 redirecting me to https://my.nextcloud.domain.com/apps/files/

When I open https://my.nextcloud.domain.com:9443/apps/files/ directly it works

### Steps to reproduce

1. Setup nextcloud with nginx on custom port
2. go to root location /
3. cry

### Expected behavior

redirection respecting configured port

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "XXXXXXXXXXXXXXXx",
            "192.168.1.229"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.3.2",
        "overwrite.cli.url": "http:\/\/XXXXXXX:9443",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 1
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "updater.release.channel": "stable",
        "default_phone_region": "CZ",
        "defaultapp": "files",
        "maintenance_window_start": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - bruteforcesettings: 2.8.0
  - calendar: 4.6.6
  - checksum: 1.2.3
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.3
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - previewgenerator: 5.4.0
  - provisioning_api: 1.18.0
  - related_resources: 1.3.0
  - richdocuments: 8.3.2
  - richdocumentscode: 23.5.705
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - encryption: 2.16.0
  - files_external: 1.20.0 (installed 1.6.0)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - metadata: 0.19.0 (installed 0.19.0)
  - music: 1.9.1 (installed 1.9.1)
  - news: 24.0.0 (installed 24.0.0)
  - privacy: 1.12.0 (installed 1.0.0)
  - recommendations: 2.0.0 (installed 0.4.0)
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by invario** [comment]
This sounds like an nginx configuration problem, not nextcloud.

**Comment by joshtrichards** [comment]
I agree this is likely a configuration issue rather than a bug. Unless you're saying this didn't happen in v28.0.2 in the same environment or something like that.

Can you confirm you're using [the up-to-date NGINX configuration in the Admin Manual](https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html)?  

Also:

```
        "overwrite.cli.url": "http:\/\/XXXXXXX:9443", 
```
The above is likely a mistake in your config (http != https)

**Comment by susnux** [comment]
Yes this seems to be a reverse proxy error as the host is not correctly forwarded (not including the port).

**Comment by michnovka** [comment]
My reverse proxy is configured correctly, its exactly as the latest version in only docs.

I have set up nginx upstream log to confirm this is the upstream doing redirect (PHP unix sock)

```
[10/Mar/2024:00:38:07 +0100] 192.168.1.116 - "GET / HTTP/3.0" 302 0 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0" - to: unix:/var/run/php/php8.1-fpm.sock: GET / HTTP/3.0 302 upstream_response_time 0.257 msec 1710027487.536 request_time 0.256
```

@joshtrichards 

> Also:
> 
> ```
>         "overwrite.cli.url": "http:\/\/XXXXXXX:9443", 
> ```
> 
> The above is likely a mistake in your config (http != https)

yes, thats a typo, I have fixed it. Same results.

**Comment by michnovka** [comment]
Also, after some debugging:

https://my.cloud.domain:9443/ -> redirects to https://my.cloud.domain/

but

https://my.cloud.domain:9443/something -> works fine (shows 404 page, or actual page if its /apps/files or other existing URL)

**Comment by michnovka** [comment]
Further proof this is PHP error and not nginx:

I have edited index.php and put

```php
<?php
echo 'PHP handled';
exit;
```

on top. And when I open https://my.cloud.domain:9443/ I see this printed out. If I remove it, I get 302 redirect to wrong port.

**Comment by invario** [comment]
Can you elaborate on your setup a bit more?

**Comment by michnovka** [comment]
What info do you need? I have Ubuntu 22.04 with PHP 8.1 and nginx 1.25.3. I have Nextcloud 28.0.3.

I did not notice this error prior to Nextcloud 28, but I am not sure. I think I would have noticed it, as when I click on Nextcloud logo in top left (to got to root folder of list of files), it points to https://my.cloud.domain:9443/ and this ends up in the wrong redirect. I use this shortcut a lot, so I believe this was not present in the past.

**Comment by michnovka** [comment]
btw I do see this in logs:
```
	
ConnectException cURL error 7: Failed to connect to my.cloud.domain port 443 after 3 ms: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://my.cloud.domain/apps/richdocumentscode/proxy.php?req=/hosting/capabilities
Failed to fetch the Collabora capabilities endpoint: cURL error 7: Failed to connect to my.cloud.domain port 443 after 3 ms: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://my.cloud.domain/apps/richdocumentscode/proxy.php?req=/hosting/capabilities 
```

so richdocuments for whatever reason is also trying port 443, not 9443

**Comment by michnovka** [comment]
Actually when I open in blank page https://my.cloud.domain:9443/ I see this in nextcloud log (set to debug) IMMEDIATELY:
```
{"reqId":"aoTpZKuOHjDzgEl7yja7","level":3,"time":"2024-03-10T01:39:43+00:00","remoteAddr":"192.168.1.116","user":"admin","app":"richdocuments","method":"GET","url":"/index.php/apps/files/preview-service-worker.js","message":"Failed to fetch the Collabora capabilities endpoint: cURL error 7: Failed to connect to my.cloud.domain port 443 after 11 ms: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://my.cloud.domain/apps/richdocumentscode/proxy.php?req=/hosting/capabilities","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:123.0) Gecko/20100101 Firefox/123.0","version":"28.0.3.2","exception":{"Exception":"GuzzleHttp\\Exception\\ConnectException","Message":"cURL error 7: Failed to connect to my.cloud.domain port 443 after 11 ms: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://my.cloud.domain/apps/richdocumentscode/proxy.php?req=/hosting/capabilities","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","line":158,"function":"createRejection","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","line":110,"function":"finishError","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::"},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php","line":47,"function":"finish","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::"},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":137,"function":"__invoke","class":"GuzzleHttp\\Handler\\CurlHandler","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php","line":121,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php","line":35,"function":"OC\\Http\\Client\\{closure}","class":"OC\\Http\\Client\\DnsPinMiddleware","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":31,"function":"__invoke","class":"GuzzleHttp\\PrepareBodyMiddleware","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php","line":71,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":63,"function":"__invoke","class":"GuzzleHttp\\RedirectMiddleware","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php","line":75,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":331,"function":"__invoke","class":"GuzzleHttp\\HandlerStack","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":168,"function":"transfer","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php","line":187,"function":"requestAsync","class":"GuzzleHttp\\Client","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/lib/private/Http/Client/Client.php","line":230,"function":"request","class":"GuzzleHttp\\Client","type":"->"},{"file":"/var/www/html/nextcloud/apps/richdocuments/lib/Service/CapabilitiesService.php","line":165,"function":"get","class":"OC\\Http\\Client\\Client","type":"->"},{"file":"/var/www/html/nextcloud/apps/richdocuments/lib/Service/CapabilitiesService.php","line":73,"function":"fetchFromRemote","class":"OCA\\Richdocuments\\Service\\CapabilitiesService","type":"->"},{"file":"/var/www/html/nextcloud/apps/richdocuments/lib/AppInfo/Application.php","line":96,"function":"getCapabilities","class":"OCA\\Richdocuments\\Service\\CapabilitiesService","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Bootstrap/FunctionInjector.php","line":66,"function":"OCA\\Richdocuments\\AppInfo\\{closure}","class":"OCA\\Richdocuments\\AppInfo\\Application","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Bootstrap/BootContext.php","line":50,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\FunctionInjector","type":"->"},{"file":"/var/www/html/nextcloud/apps/richdocuments/lib/AppInfo/Application.php","line":151,"function":"injectFn","class":"OC\\AppFramework\\Bootstrap\\BootContext","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Bootstrap/Coordinator.php","line":200,"function":"boot","class":"OCA\\Richdocuments\\AppInfo\\Application","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/App/AppManager.php","line":434,"function":"bootApp","class":"OC\\AppFramework\\Bootstrap\\Coordinator","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/App/AppManager.php","line":213,"function":"loadApp","class":"OC\\App\\AppManager","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/legacy/OC_App.php","line":125,"function":"loadApps","class":"OC\\App\\AppManager","type":"->"},{"file":"/var/www/html/nextcloud/lib/base.php","line":1049,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/var/www/html/nextcloud/index.php","line":39,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","Line":210,"message":"Failed to fetch the Collabora capabilities endpoint: cURL error 7: Failed to connect to my.cloud.domain port 443 after 11 ms: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://my.cloud.domain/apps/richdocumentscode/proxy.php?req=/hosting/capabilities","exception":{},"CustomMessage":"Failed to fetch the Collabora capabilities endpoint: cURL error 7: Failed to connect to my.cloud.domain port 443 after 11 ms: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://my.cloud.domain/apps/richdocumentscode/proxy.php?req=/hosting/capabilities"}}
```

**Comment by invario** [comment]
So not reverse proxied then, just being served up via nginx? Gotcha. Hmm.

**Comment by joshtrichards** [comment]
Can you provide the output of `curl -I --http2 https://XXXXXXX:9443`?

**Comment by michnovka** [comment]
well I dont get this. When I use browser, it returns the Location: to :443/. When I use curl, it shows clearly Location: 9443:/login.

I have tested Chrome and firefox, same results. If I add on top `echo 'something';exit;` then I see this in both browsers and curl.

I have even tried to copy request as cURL from web developer tools, and it is also redirecting me to :9443/login . This cURL request contains all cookies, user agent etc.

**Comment by michnovka** [comment]
Well I have disabled quick support in nginx (HTTP/3) and its working good now.

Even the 
	
> ConnectException cURL error 7: Failed to connect to my.cloud.domain port 443 after 3 ms: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://my.cloud.domain/apps/richdocumentscode/proxy.php?req=/hosting/capabilities
> Failed to fetch the Collabora capabilities endpoint: cURL error 7: Failed to connect to my.cloud.domain port 443 after 3 ms: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://my.cloud.domain/apps/richdocumentscode/proxy.php?req=/hosting/capabilities 

have disappeared. So this looks like some nginx bug, though I am not entirely sure what it is and how to diagnose it, since I did not reproduce it with curl. Maybe it is even firefox and chrome bug, though its strange that 2 independent engines would have same issue. cURL replies would however suggest that.

**Comment by invario** [comment]
Very interesting. I had QUIC enabled in nginx on standard port 443 for a while but disabled it during troubleshooting for something unrelated. Haven't looked back since.

**Comment by michnovka** [comment]
I have updated to nginx 1.25.4 from 1.25.3 and its working fine now.

**Comment by joshtrichards** [comment]
HTTP/3 and QUIC were only recently added into Nginx (v1.25.1) and only via the mainline (development) branch. There is no stable branch release of Nginx that includes it AFAIK.

There's a reason we don't include h3 in our documented configs. :-)

Glad you got it figured out!

**Comment by michnovka** [comment]
I want to let you know there are random issues with http/3 still happening. Mainly together with built in collabora server. For some reason it detects port as 443, not 9443. And there are multiple errors in logs. And random redirection to :443 still ongoing.

Since HTTP/3 is still experimental, I understand you might not want to work to fix it. I have disabled it and all problems are gone. But it is something that should be looked into before the adoption happens.

**Comment by susnux** [comment]
This issue was resolved, if you encountered new issues please open a new ticket.
For general discussions please use our forms:
https://help.nextcloud.com
