### ISSUE TITLE
[Bug]: Error migrating from Nextcloud 27 to 28

### ISSUE THREAD

**Issue by csh4rp** [nextcloud/server#44106]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I run the migration for nextcloud from 27 to 28 this error occurs:

Updating database schema

Exception: Database error when running migration 28000Date20231004103301 for app core An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 4025 CONSTRAINT `oc_file_metadata.metadata` failed for `nextcloud`.`oc_file_metadata`

This migrations script seems to be only creating a table, so I'm not sure what's it all about.

### Steps to reproduce

1. Changed docker base image to 28-fpm
2. Restarted nextcloud

### Expected behavior

Application should be updated

### Installation method

None

### Nextcloud Server version

28

### Operating system

RHEL/CentOS

### PHP engine version

None

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by csh4rp** [comment]
Turns out table `file_metadata` had stored location as text instead of json from one of mine devices and simply deleting this data that was not in JSON format fixed the issue. Still seems like a bug that either migration did not change it or that it was possible to put it there in the first place.

**Comment by baartch** [comment]
I ran into the same issue when updating from 27 to 28.
My metadata column was completely empty.
```
MariaDB [nextcloud]> select * from oc_file_metadata;
+-------+------------+----------+-------------------------------+
| id    | group_name | metadata | value                         |
+-------+------------+----------+-------------------------------+
|    26 | size       |          | {"width":1920,"height":1281}  |
|    27 | size       |          | {"width":1600,"height":1067}  |
|    28 | size       |          | {"width":1600,"height":1066}  |
|    29 | size       |          | {"width":3000,"height":2000}  |
.... and so on
```

since it's only a metadata table, I simply truncated the whole table (of course, after backing up the DB).
```
MariaDB [nextcloud]> truncate oc_file_metadata;
Query OK, 0 rows affected (0.005 sec)
```
Afterwards `./occ upgrade` went through like a charm...
