### ISSUE TITLE
files app - if scrolling down and right-clicking, the view jumps to the top and opens the menu there

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#44123]
Just tested on nc29.0.0b1

files app - if scrolling down and right-clicking, the view jumps to the top and opens the menu there

https://github.com/nextcloud/server/assets/42591237/050df38c-a7dd-48ce-ab66-7c26b7835895

**Comment by szaimen** [comment]
cc @nextcloud/server-frontend

**Comment by SystemKeeper** [comment]
https://github.com/nextcloud/server/issues/43300 ?

**Comment by szaimen** [comment]
Thanks @Pytal for fixing this! :)
