### ISSUE TITLE
[Bug]: Deleted calendar objects included in initial sync

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#44127]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

https://github.com/nextcloud/server/blob/f4beb95cdc3161a99e048e03ab486e5218d10e0a/apps/dav/lib/CalDAV/CalDavBackend.php#L2419-L2430 returns all object URIs regardless of the deleted_at flag. If a client runs into this, they might see download deleted events.

### Steps to reproduce

1. Have an existing calendar with deleted events
2. Connect a new caldav client
3. Synchronize

### Expected behavior

No deleted events synchronized

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by st3iny** [comment]
I can't reproduce the problem. Deleted events are pulled from the DB in the above code block. However, they are filtered again before being sent to the client and thus deleted events never actually get sent. I tested with Thunderbird and mitmproxy.

https://github.com/nextcloud/server/blob/eeb6ddb176adc7488b74d004dceafee960603ebc/apps/dav/lib/CalDAV/CalDavBackend.php#L1163-L1168
