### ISSUE TITLE
opening sidebar hides broadscrombs totally with some screen resolutions

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#44120]
Just tested on nc29.0.0b1,
opening the sidebar hides the broadscrumbs totally under some circumstances:
### Sidebar open:
![image](https://github.com/nextcloud/server/assets/42591237/936e5b3e-a875-4959-b9bc-2e4f102e8e3b)
### Sidebar closed:
![image](https://github.com/nextcloud/server/assets/42591237/bd6b44f0-b9ba-4c06-bb46-6c8ec49412ce)

**Comment by szaimen** [comment]
cc @nextcloud/server-frontend

**Comment by emoral435** [comment]
Interesting, I will try to take a look at this when I can 🤔
