### ISSUE TITLE
[Bug]: Upgrade 27.1.4.1 to 27.1.7.2 to 28.0.3.2 server error

### ISSUE THREAD

**Issue by stanke-sk** [nextcloud/server#44133]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello 
I did an upgrade from 27.1.4.1 to 27.1.7.2 , after upgrade restart php-fpm, then did another upgrade with php updater to latest 28.0.3.2 since that I am getting error 500 with several missing files. 
Ussualy I'm doing it with snapshots but currently due to pci passthrough gpu for face detection and recognize I was not able to do that :-( 

### Steps to reproduce

1.upgrade 27.1.4.1
2.through 27.1.7.2
3.to 28.0.3.2

### Expected behavior

nextcloud working after the upgrade. 

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.4",
            "nextcloud.example.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.3.2",
        "overwrite.cli.url": "http:\/\/192.168.0.4\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "maintenance": true,
        "theme": "",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": "0",
        "logtimezone": "Europe\/Bratislava",
        "updater.release.channel": "stable",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\Krita",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MP4",
            "OC\\Preview\\MKV",
            "OC\\Preview\\AVI",
            "OC\\Preview\\Image",
            "OC\\Preview\\TIFF"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "memories.exiftool_no_local": true,
        "memories.vod.path": "\/var\/www\/html\/nextcloud\/apps\/memories\/bin-ext\/go-vod-amd64",
        "preview_max_x": 8192,
        "preview_max_y": 8192,
        "preview_max_memory": 4096,
        "preview_max_filesize_image": 300,
        "memories.vod.ffmpeg": "\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/bin\/ffprobe"
    }
}
```

### List of activated Apps

```shell
Nextcloud is in maintenance mode, no apps are loaded.
Commands provided by apps are unavailable.
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - circles: 28.0.0-dev
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_automatedtagging: 1.18.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - maps: 1.3.1
  - memories: 6.2.2
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - phonetrack: 0.7.7
  - photos: 2.4.0
  - previewgenerator: 5.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - spreed: 18.0.5
  - support: 1.11.0
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - bruteforcesettings: 2.8.0 (installed 2.4.0)
  - encryption: 2.16.0 (installed 2.5.0)
  - files_external: 1.20.0
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0
```

### Nextcloud Signing status

```shell
Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the webserver log.
```

### Nextcloud Logs

```shell
nothing currently there.
```

### Additional info

php error log
[11-Mar-2024 16:38:35 UTC] PHP Warning:  require(/var/www/html/nextcloud/3rdparty/composer/../symfony/polyfill-iconv/bootstrap.php): Failed to open stream: No such file or directory in /var/www/html/nextcloud/3rdparty/composer/autoload_real.php on line 46
[11-Mar-2024 16:38:35 UTC] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/nextcloud/3rdparty/composer/../symfony/polyfill-iconv/bootstrap.php' (include_path='/var/www/html/nextcloud/3rdparty/pear/archive_tar:/var/www/html/nextcloud/3rdparty/pear/console_getopt:/var/www/html/nextcloud/3rdparty/pear/pear-core-minimal/src:/var/www/html/nextcloud/3rdparty/pear/pear_exception:/var/www/html/nextcloud/apps') in /var/www/html/nextcloud/3rdparty/composer/autoload_real.php:46
Stack trace:
#0 /var/www/html/nextcloud/3rdparty/composer/autoload_real.php(50): {closure}('def43f6c87e4f8d...', '/var/www/html/n...')
#1 /var/www/html/nextcloud/3rdparty/autoload.php(25): ComposerAutoloaderInit2f23f73bc0cc116b4b1eee1521aa8652::getLoader()
#2 /var/www/html/nextcloud/lib/base.php(622): require_once('/var/www/html/n...')
#3 /var/www/html/nextcloud/lib/base.php(1196): OC::init()
#4 /var/www/html/nextcloud/status.php(37): require_once('/var/www/html/n...')
#5 {main}
  thrown in /var/www/html/nextcloud/3rdparty/composer/autoload_real.php on line 46

**Comment by solracsf** [comment]
You'll probably get more help for this at https://help.nextcloud.com than here on Github.
Thanks 👍
