### ISSUE TITLE
Existing preview in conflict dialogue is not cropped properly

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#4414]
### Steps to reproduce

1. Upload a tall image
2. Upload it again

### Expected behaviour

The conflict dialogue should present identical images

### Actual behaviour

The image on the right is cropped at the top of the image instead if in the middle.
This makes it difficult to tell if it's the same image...

<img width="382" alt="wonky preview" src="https://cloud.githubusercontent.com/assets/323220/25254075/047d4286-2624-11e7-9214-bbbf97917629.png">

### Server configuration

**Nextcloud version:** master

**Comment by rullzer** [comment]
Can you send me an example image?

**Comment by oparoz** [comment]
Of course :)

![1_tall](https://cloud.githubusercontent.com/assets/323220/25269079/761a4054-267b-11e7-949c-e173ea898b2d.png)

**Comment by rullzer** [comment]
Thnx I'll have a look

**Comment by rullzer** [comment]
Aaaah ok. so. we create previews of thumbnails like this because else text looks weird. (we center horizontally but vertically we take the top). So I'm not really sure how to quickly fix this without adding another preview parameter (which I really don't want to do).

**Comment by szaimen** [comment]
I think this works now -> closing.
See 
![image](https://user-images.githubusercontent.com/42591237/119112912-dc260400-ba24-11eb-899c-7e28859a984b.png)
