### ISSUE TITLE
[Bug]: Impossible to add an external storage in 29

### ISSUE THREAD

**Issue by come-nc** [nextcloud/server#44204]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When trying to add an external storage, nothing happens, the UI is broken.

Error is:
```
Uncaught Error: cannot call methods on tooltip prior to initialization; attempted to call method 'dispose'
    at Function.error (jquery.js:336:1)
    at HTMLSpanElement.<anonymous> (jquery-ui.js:245:1)
    at Function.each (jquery.js:383:1)
    at jQuery.fn.init.each (jquery.js:205:1)
    at $.fn.<computed> [as tooltip] (jquery-ui.js:235:1)
    at MountConfigListView.updateStatus (settings.js:1332:16)
    at MountConfigListView._onChange (settings.js:761:8)
    at executeBound (_executeBound.js:8:1)
    at HTMLInputElement.<anonymous> (bind.js:10:1)
    at HTMLInputElement.<anonymous> (restArguments.js:16:1)
```

If I comment out the dispose call at https://github.com/nextcloud/server/blob/f316edb9ff448077fa8494dbbb2c6fdacd158bed/apps/files_external/js/settings.js#L1332 the UI is buggy (impossible to close the 3dot menu), but adding storages works again.

### Steps to reproduce

1. Enable `files_external` application
2. Login as admin and go to settings
3. Attempt to add a local external storage

### Expected behavior

Working UI

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by oculos** [comment]
I can confirm this on beta 3. Spinning wheel on the gui. Previously mounted shares show as empty.
