### ISSUE TITLE
[Bug]: Webdav availability request gives malformed response

### ISSUE THREAD

**Issue by GVodyanov** [nextcloud/server#44205]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Webdav availability request gives malformed response, especially when a user doesn't have any availability slots configured so far

### Steps to reproduce

1. Create a new user
2. Go to availability settings
3. See "Failed to load availability" (first issue)
4. Set some availability slots and save
5. Reload the page
6. The availability slots aren't shown

### Expected behavior

No errors and slots are saved

### Installation method

Other Community project

### Nextcloud Server version

master

### Operating system

Other

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by st3iny** [comment]
This is caused by [webdav](https://github.com/perry-mitchell/webdav-client) switching their http client library from axios to "native" fetch[^1].

The property `response.data` is not available any more as it was populated by axios. Instead, we have to manually await the body now, e.g. `await response.text()`.

I wonder if there are more instances of this across our code base.

[^1]: https://github.com/perry-mitchell/webdav-client?tab=readme-ov-file#requests

**Comment by st3iny** [comment]
I did not find another broken usage inside the server repository.

**Comment by ChristophWurst** [comment]
> This is caused by [webdav](https://github.com/perry-mitchell/webdav-client) switching their http client library from axios to "native" fetch[1](#user-content-fn-1-b66d1c302afaba6605eea77952bf95f2).

https://github.com/perry-mitchell/webdav-client?tab=readme-ov-file#customrequest oh no

**Comment by st3iny** [comment]
Yeah, they should definitely adjust their readme :sweat_smile:

**Comment by st3iny** [comment]
> Yeah, they should definitely adjust their readme 😅

https://github.com/perry-mitchell/webdav-client/pull/371
