### ISSUE TITLE
[Bug]: When creating email share expiry date is set by default without enforcement

### ISSUE THREAD

**Issue by ElSi-DVT** [nextcloud/server#44219]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When creating an email share with the option "Set expiration date" unchecked and "Enforce expiry date" unchecked, the default expiry date is set anyway.
You can see it by clicking "customize link".

This is how it looks like when creating the email share:
![grafik](https://github.com/nextcloud/server/assets/142410285/a5f77552-f3f4-4974-a3fa-b39aa8dfdfad)

This is how it looks like when customizing the share afterwards:
![grafik](https://github.com/nextcloud/server/assets/142410285/2c3486b6-a452-443e-8844-ba53e69885a7)

After unchecking "Set expiration date" and updating share again, the values stays ok.

### Steps to reproduce

1. Configure the Sharing options like this.
    - [x] Allow users to share via link end emails
    - [x] Always ask for a password
    - [x] Enforce password protection
    - [x] Set default expiry date -> Expire after 30 day(s)
    - [ ] Enforce expiry date
2. Create an email share and uncheck the option "Set expiration date"
3. Click on "customize link" and see that it's wrong.
4. Uncheck "Set expiration date" again and update the link.
5. Click on "customize link" again and see that now it worked how it should work in first place.

### Expected behavior

If the option "Set expiration date" is unchecked when creating the share, it should be stored correctly in the database like this and not only at the second updating

### Nextcloud Server version

27.1.7 28.0.3

**Comment by susnux** [comment]
cc @Altahrim

**Comment by sorbaugh** [comment]
also cc-ing @Fenn-CS

**Comment by Altahrim** [comment]
When creating the share, the frontend don't send any info on `expireDate`:
```json
{
  "path":"/file.test",
  "permissions":1,
  "shareType":4,
  "shareWith":"mail@test.com",
  "attributes":"[]"
}
```
In this case, backend use the default

During update, frontend send an empty `expireDate` and backend update it:
```json
{
  "permissions":"17",
  "attributes":"[]",
  "note":"",
  "expireDate":"",
  "label":"",
  "password":"",
  "hideDownload":"false"
}
```

I think frontend should send the info so the backend don't have to use default

**Comment by ElSi-DVT** [comment]
@Fenn-CS this bug still exists in 27.1.8

**Comment by ElSi-DVT** [comment]
@susnux @Altahrim this bug still exists in 27.1.9

**Comment by susnux** [comment]
@Fenn-CS  is working on this in https://github.com/nextcloud/server/pull/44485

**Comment by ElSi-DVT** [comment]
Bug still exists in 28.0.6

**Comment by ElSi-DVT** [comment]
Sorry my fault, didn't notice it.
