### ISSUE TITLE
login mask - login with username or email not translated anymore

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#44222]
Just tested on nc29.0.0b3

The login with username or email field is not translated anymore.

See 
![image](https://github.com/nextcloud/server/assets/42591237/22bb06fd-8a98-4c3b-ba9d-96dc610e9acb)

**Comment by susnux** [comment]
This is only a problem on "de" on "de_DE" it works -> The translation is simply missing on transifex.
(I added the one from "de_DE" also to "de").

**Comment by szaimen** [comment]
> This is only a problem on "de" on "de_DE" it works -> The translation is simply missing on transifex. (I added the one from "de_DE" also to "de").

I see, thanks! :)
