### ISSUE TITLE
Nextcloud 9 (error: could not generate a preview of this file) If the picture is into cifs share and reshared

### ISSUE THREAD

**Issue by husisusi** [nextcloud/server#443]
Same like Owncloud BUG #23407
Hope Nextcloud fix it

Steps to reproduce

```
Mount cifs share
Re-share this CIFS Folder
Find one Image (picture) in this shared cifs share and try to open it (Preview)
error: could not generate a preview of this file
```

Expected behaviour

Thumbnails is visibile of photos
A preview of the opened photo should appear.
Actual behaviour

Thumbnails is visibile of photos, but No preview appears (Size of photo does not matter), instead on the top of the page: "error: could not generate a preview of this file"
Server configuration

Operating system:
Debian 8.3

Web server:
nginx/1.6.2
Database:
mysql Ver 14.14
PHP version:
PHP 5.6.17
Nextcloud version:
OC 9
Updated from an older Nextcloud or fresh install:
Fresh

Where did you install Nextcloud from:
https://download.nextcloud.com/server/releases/nextcloud-9.0.53.zip
Signing status (Nextcloud 9.0 and above):
All checks passed
the results here.
No errors have been found

List of activated apps:
activity
comments
dav
external
federatedfilesharing
federation
files
files_external
files_pdfviewer
files_sharing
files_texteditor
files_trashbin
files_versions
files_videoplayer
firstrunwizard
gallery
notifications
provisioning_api
systemtags
templateeditor
updatenotification
user_ldap

The content of config/config.php:
<?php
$CONFIG = array (
'instanceid' => '',
'passwordsalt' => 'pass',
'secret' => 'pass',
'trusted_domains' =>
array (
0 => 'https://myURL',
),
'datadirectory' => '/data',
'overwrite.cli.url' => 'https://myURL',
'dbtype' => 'mysql',
'version' => '9.0.0.19',
'dbname' => 'nameofDB',
'dbhost' => '127.0.0.1',
'dbtableprefix' => 'oc_',
'dbuser' => 'XY',
'dbpassword' => 'some',
'installed' => true,
'ldapIgnoreNamingRules' => false,
'loglevel' => 2,
'theme' => '',
'maintenance' => false,
'mail_smtpmode' => 'smtp',
'mail_smtpauthtype' => 'LOGIN',
'mail_smtphost' => 'smtp DNS',
'mail_smtpport' => 'port',
'mail_from_address' => 'someting',
'mail_domain' => 'my domain',
'mail_smtpsecure' => 'tls',
'memcache.local' => '\OC\Memcache\APCu',
'trashbin_retention_obligation' => 'auto',
);

Are you using external storage, if yes which one: local/smb/sftp/...
Yes: smb
Are you using encryption: yes/no
No
Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...
Yes: LDAP
LDAP configuration (delete this part if not used)

hasMemberOfFilterSupport 1

hasPagedResultSupport

homeFolderNamingRule

lastJpegPhotoLookup 0

ldapAgentName domain\user

ldapAgentPassword *******

ldapAttributesForGroupSearch

ldapAttributesForUserSearch

ldapBackupHost

ldapBackupPort

ldapBase dc=ad1, dc=domain, dc=com

ldapBaseGroups dc=ad1, dc=domain, dc=com

ldapBaseUsers dc=ad1, dc=domain, dc=com

ldapCacheTTL 600

ldapConfigurationActive 1

ldapDynamicGroupMemberURL

ldapEmailAttribute mail

ldapExperiencedAdmin 0

ldapExpertUUIDGroupAttr

ldapExpertUUIDUserAttr

ldapExpertUsernameAttr

ldapGroupDisplayName cn

ldapGroupFilter (&((objectclass=group))((cn=Domänen-Benutzer)))
ldapGroupFilterGroups Domänen-Benutzer

ldapGroupFilterMode 1

ldapGroupFilterObjectclass group

ldapGroupMemberAssocAttr member

ldapHost IP address

ldapIgnoreNamingRules

ldapLoginFilter (&(&((objectclass=user)))(samaccountname=%uid))

ldapLoginFilterAttributes

ldapLoginFilterEmail 0

ldapLoginFilterMode 1

ldapLoginFilterUsername 1

ldapNestedGroups 0

ldapOverrideMainServer

ldapPagingSize 500

ldapPort 389

ldapQuotaAttribute

ldapQuotaDefault

ldapTLS 1

ldapUserDisplayName displayname

ldapUserDisplayName2

ldapUserFilter (&((objectclass=user)))

ldapUserFilterGroups

ldapUserFilterMode 0

ldapUserFilterObjectclass user

ldapUuidGroupAttribute auto

ldapUuidUserAttribute auto

turnOffCertCheck 0

useMemberOfToDetectMembership 1
Client configuration

Browser:
Firefox, Chrome
Operating system:
Linux, Windows

Logs
Web server error log

No errors and nothing important

**Comment by rullzer** [comment]
As far as I can tell this is working on current master
