### ISSUE TITLE
[Bug]: Wrong fields for pending remote shares in OpenAPI

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#44317]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Remote shares have [several base fields](https://github.com/nextcloud/server/blob/efe68d012c354598820121c0ff91dd4db937afdc/apps/files_sharing/lib/External/Manager.php#L791) which are then extended from [the information of the file based on its mountpoint](https://github.com/nextcloud/server/blob/755de1e0b57aa9c7275257142b6f852fbcd1961e/apps/files_sharing/lib/Controller/RemoteController.php#L128-L132).

However, when [pending remote shares are got they are not extended with those extra fields](https://github.com/nextcloud/server/blob/755de1e0b57aa9c7275257142b6f852fbcd1961e/apps/files_sharing/lib/Controller/RemoteController.php#L69), but [the return value is documented](https://github.com/nextcloud/server/blob/755de1e0b57aa9c7275257142b6f852fbcd1961e/apps/files_sharing/lib/Controller/RemoteController.php#L64) as [including all the fields](https://github.com/nextcloud/server/blob/82b5a19a35b780bf18ebac46711166158a5a6cb2/apps/files_sharing/lib/ResponseDefinitions.php#L97-L114).

Moreover, pending remote shares may not even have a mountpoint; when they are initially created they have a temporary mountpoint, and only after being accepted a real mountpoint is set. Therefore, although getting a remote share tries to add the extra fields no field may get added and only the base fields may be returned. Due to that the response from [getting a specific share may not have all the documented fields](https://github.com/nextcloud/server/blob/755de1e0b57aa9c7275257142b6f852fbcd1961e/apps/files_sharing/lib/Controller/RemoteController.php#L159).

@provokateurin FYI

### Steps to reproduce

- Setup Nextcloud server A
- Setup Nextcloud server B
- In server A, share a file with user X of server B
- Check fields with `curl -u {USER_X_ID}:{PASSWORD} --header "OCS-APIRequest: true" {SERVER_B}/ocs/v2.php/apps/files_sharing/api/v1/remote_shares/pending`
- Check fields with `curl -u {USER_X_ID}:{PASSWORD} --header "OCS-APIRequest: true" {SERVER_B}/ocs/v2.php/apps/files_sharing/api/v1/remote_shares/{PENDING_SHARE_ID}`

### Expected behavior

OpenAPI should describe the right fields.

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by provokateurin** [comment]
The documentation is correct. The endpoint is generic for all shares so it is possible that any combination of the fields might be set. The API is not great because all fields are set to be required and nullable. Ideally the fields would be set to be non-nullable (where it makes sense) and only the fields that are always present set to required.
