### ISSUE TITLE
[Bug]: Broken avatar placeholders for federated users in new search

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#44319]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In the search dialog there is no handling for not found avatars, resulting in broken images being displayed for example for federated users.

### Steps to reproduce

1. have a trusted server pairing
2. open the search dialog and there open the people one
3. check for federated users

### Expected behavior

a placeholder will be shown (as long as we do not build in support for actual federated avatars)

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by blizzz** [comment]
It is similar to https://github.com/nextcloud/server/issues/44287

**Comment by Fenn-CS** [comment]
https://github.com/nextcloud/server/pull/44972
