### ISSUE TITLE
Update icons in "New" menu

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#44340]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

we aim to have the icons updated for v29, the remaining parts can be ignored or implemented given the 29-timebox

  - [x] Upload files: current icon
  - ~Upload folders: [drive-folder-upload](https://fonts.google.com/icons?selected=Material%20Icons%20Round%3Adrive_folder_upload%3A) in `--color-primary-element`~ (New entry pushed to 30)
  - ~Folder: [folder](https://fonts.google.com/icons?selected=Material%20Icons%3Afolder%3A) in `--color-primary-element`~ (New design with headings pushed to 30)
  - [x] https://github.com/nextcloud/text/issues/5535
    - Text file: [article](https://fonts.google.com/icons?selected=Material%20Icons%3Aarticle%3A) in `--color-text-maxcontrast`
    - Description: [notes](https://fonts.google.com/icons?selected=Material%20Icons%3Anotes%3A)
  - [x] https://github.com/nextcloud/richdocuments/issues/3537
    - Document: [description](https://fonts.google.com/icons?selected=Material%20Icons%3Adescription%3A) in `#49abea`
    - Spreadsheet: [file-table-box](https://pictogrammers.com/library/mdi/icon/file-table-box/) in `#9abd4e`
    - Presentation: [file-presentation-box](https://pictogrammers.com/library/mdi/icon/file-presentation-box/) in `#f0965f`
    - Diagram: [drawing-box](https://pictogrammers.com/library/mdi/icon/drawing-box/) in `#b39114`

| Before | After |
|---|---|
| ![image](https://github.com/nextcloud/server/assets/52440189/9051a0af-28f9-42b0-91f1-554eb379f7c1) | ![image](https://github.com/nextcloud/server/assets/52440189/1eb9d878-e385-4b34-9a98-501c217ff723) |

**Comment by jancborchardt** [comment]
Just FYI @tobiasKaminsky @juliushaertl @sorbaugh we had to adjust the colors of 2 icons:

>  - [ ] Text file: [article](https://fonts.google.com/icons?selected=Material%20Icons%3Aarticle%3A) in `--color-text-maxcontrast`

Considering this is also used in the file list and grid view (and in the widgets) and black this would be very dark then, we will keep it grey.

  - [ ] Diagram: [drawing-box](https://pictogrammers.com/library/mdi/icon/drawing-box/) in `#b39114`

This fulfills the proper 3:1 contrast requirement and works in both light and dark theme.

cc @nimishavijay

**Comment by mejo-** [comment]
https://github.com/nextcloud/text/pull/5540 for the text side.

**Comment by AndyScherzinger** [comment]
@jancborchardt 

>  Text file: [article](https://fonts.google.com/icons?selected=Material%20Icons%3Aarticle%3A) in `--color-text-maxcontrast`

Wouldn't this than also apply to the file listing, so the general mime type icon if there is no preview? And if so wouldn't this also lead to the need to adapt all "grey" mimetype icons (!)

**Comment by Pytal** [comment]
New PRs:
- https://github.com/nextcloud/server/pull/44368
- https://github.com/nextcloud/richdocuments/pull/3538

Updated:
- https://github.com/nextcloud/text/pull/5540

**Comment by Pytal** [comment]
> > Text file: [article](https://fonts.google.com/icons?selected=Material%20Icons%3Aarticle%3A) in `--color-text-maxcontrast`
> 
> Wouldn't this than also apply to the file listing, so the general mime type icon if there is no preview? And if so wouldn't this also lead to the need to adapt all "grey" mimetype icons (!) which we would want to prevent atm since that change is way larger to implement and should than be moved to v30 in my opinion. (or we just do it for the text mime type, than it would be okay)

Noticed this in the rendering of the mimetype icons (e.g. in the sidebar) which uses a background-image url and doesn't support CSS variables so I used the same grey as before `#969696`
