### ISSUE TITLE
[Bug]: Remove extra css margin for URL in task title

### ISSUE THREAD

**Issue by RayBB** [nextcloud/server#44364]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Originally reported in https://github.com/nextcloud/tasks/issues/2500

This issue is in the tasks app but the code causing it lives here.

### Steps to reproduce

1. Add a new task with a URL as the title https://wikipedia.org

### Expected behavior

The task title is in line with non-URL titles.

### Actual behaviour

It is off by 3px

<img width="258" alt="image" src="https://github.com/nextcloud/tasks/assets/921217/43709fb5-5b14-4260-b92b-7c0d14d33e9b">

### Towards solutions

This appears to be caused by the `a.external` CSS which adds a margin.

```css
a.external {
	margin: 0 3px;
	text-decoration: underline;
}
``` 

Looks like it actually comes from [here](https://github.com/nextcloud/server/blob/1d100bdcd989b1343d644f554a8990318abeed80/core/css/styles.scss#L81-L84) in `nextcloud/server/.../styles.scss`.

The external class is added by calling linkify on this line:
https://github.com/nextcloud/tasks/blob/8a1a4ab193e02a0c3e9c22817e39e46c99b6e180/src/components/TaskBody.vue#L53

The linkify function always adds the external class:
https://github.com/nextcloud-libraries/nextcloud-vue/blob/87322fabb7f12ed9a64862903a204969ee45c632/src/utils/Linkify.js#L30-L39

So the way I see it there are a few options:

* Add our a CSS to [taskbody.vue](https://github.com/nextcloud/tasks/blob/8a1a4ab193e02a0c3e9c22817e39e46c99b6e180/src/components/TaskBody.vue) that looks something like: `.task-body__info .title a { margin: unset; }`
  * Easy to do but maybe not the best for maintainability
* change styles.scss in nextcloud/server 
  * Probably not a good idea since it may be used many places but at the same time. But why would all external links in all of nextcloud be indented by 3px? Maybe this should be fixed?
  * The Margin was added way back in https://github.com/nextcloud/server/pull/7680 for a specific use case
* Don't use linkify
  * Honestly not totally sure of the purpose/history of linkify. It's probably there for a reason.
* Modify linkify to have an option to not add the external class.
  * Seems not ideal

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by jadjoud** [comment]
hello @RayBB 
checkout our PR #45070 me and @RayanBekri
We found the problem and it's fixed now! 
Thank you so much for mentioning the issue
