### ISSUE TITLE
Some apps do not support encryption

### ISSUE THREAD

**Issue by despens** [nextcloud/server#4436]
Some nice apps, like preview generator and OCR, do not support encryption enabled.

File access API for apps should handle encryption transparently, so developers do not need to care about encryption being enabled or not.

**Comment by MorrisJobke** [comment]
cc @icewind1991 @schiessle

**Comment by nickvergessen** [comment]
I think those apps are hacking there way around the view, to save time and resources...

**Comment by rullzer** [comment]
The issue with the preview generator is that we don't have access to the keys because it runs in cron. There is really nothing we can do about that. If you want cron jobs to have access to your files you should not use encryption.

**Comment by despens** [comment]
Nextcloud already uses a cronjob, should apps hook into that one?

**Comment by MorrisJobke** [comment]
> Nextcloud already uses a cronjob, should apps hook into that one?

We are talking about this one. We should maybe also disable given cron job tasks if encryption is enabled.

**Comment by schiessle** [comment]
Well, it can and should work if encryption is used with the master key. If encryption is used with individual per-user keys (which is the default) there is no way to make it work with cronjob because in order to decrypt your files we need your decrypted private key which is only available as long as you are logged in.

**Comment by MorrisJobke** [comment]
> If encryption is used with individual per-user keys (which is the default) there is no way to make it work with cronjob because in order to decrypt your files we need your decrypted private key which is only available as long as you are logged in.

In this case we should just not execute the jobs that will not work, or am I wrong? It will just be slower, but if previews are not generated in the background it will be fine.

**Comment by despens** [comment]
Since documentation in apps has much improved (most state if they support encryption or not) and the *purpose* of encryption is that not every user or script has access, I would suggest to close this issue.
