### ISSUE TITLE
Add fuctionality to handle .HEIC files

### ISSUE THREAD

**Issue by likeadragonmaid** [nextcloud/server#44372]
Please add functionality to generate thumbnails for .heic files and also allow them to viewed on webapp. HEIC image format is used by both Samsung and Apple devices.

**Comment by solracsf** [comment]
HEIC file are supported on correctly configured Nextcloud.

### PREVIEW
![image](https://github.com/nextcloud/server/assets/12234510/d36982dc-161a-4645-9a4a-7598ccf569de)

### IMAGE
![image](https://github.com/nextcloud/server/assets/12234510/ccca8aa3-f430-430b-9faa-ba6801b28845)



Please ask for help to confiure it at https://help.nextcloud.com 👍
