### ISSUE TITLE
Internal server error in Additional Settings

### ISSUE THREAD

**Issue by michaelletzgus** [nextcloud/server#4437]
Current master, open menu administration, additional settings:

https://server/settings/admin/additional

This Gives an internal server error and some js problems:

```
ReferenceError: oc_appconfig is not defined
	shareconfigmodel.js:24:4
	<anonym> https://<server>/core/js/shareconfigmodel.js:24:4
	<anonym> https://<server>/core/js/shareconfigmodel.js:13:2
```

Caused by gpxedit app, maybe related to problem above:

```
TypeError: $(...).fileupload is not a function
	admin.js:64:5
	<anonym> https://<server>/apps/gpxedit/js/admin.js:64:5
	j https://<server>/core/vendor/jquery/dist/jquery.min.js:2:26920
	fireWith https://<server>/core/vendor/jquery/dist/jquery.min.js:2:27738
	ready https://<server>/core/vendor/jquery/dist/jquery.min.js:2:29530
	I https://<server>/core/vendor/jquery/dist/jquery.min.js:2:29721

```

**Comment by MorrisJobke** [comment]
> This Gives an internal server error and some js problems:

And what is in the nextcloud.log? What happens if you disable gpxedit?

**Comment by michaelletzgus** [comment]
Disabling gpxedit changes nothing - but OwnBackup causes the failure.
So this is not core problem.
