### ISSUE TITLE
[Bug]: Cannot use database over IPv6

### ISSUE THREAD

**Issue by edocod1** [nextcloud/server#44370]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When using an IPv6 address as database host, or a domain that resolves only to a IPv6 address, nextcloud does not work.

`Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] could not translate host name "[fd09:f000:9a0::1]" to address: Name or service not known in /var/www/nextcloud/lib/private/DB/Connection.php:139`

### Steps to reproduce

1. Edit config/config.php with an IPv6 server as dbhost
2. ????
3. Internal server error

### Expected behavior

Nextcloud works correctly by using the database connection.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
<?php
$CONFIG = array (
  'passwordsalt' => '?????????????????',
  'secret' => '?????????????????',
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/var/www/nextcloud_data',
  'dbtype' => 'pgsql',
  'version' => '28.0.3.2',
  'overwrite.cli.url' => 'http://localhost',
  'dbname' => 'nextcloud',
  'dbhost' => '[fd09:f000::1]',
  'dbport' => '5432',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => '?????????????????',
  'installed' => true,
  'instanceid' => 'aaaaaa',
  'debug' => true,
  'log_type' => 'file',
  'logfile' => 'nextcloud.log'
);
```

**Comment by susnux** [comment]
Could you try:
```
  'dbhost' => 'fd09:f000:9a0:120:be24:11ff:fe28:4b63:5432',
```


Because this error is thrown by PostgreSQL not Nextcloud and I think Postgres does not support the `[...]` notation.

**Comment by susnux** [comment]
(When using IPv6 you should not need to use ports, as you can assign an address per application)

**Comment by edocod1** [comment]
> Could you try:
> 
> ```
>   'dbhost' => 'fd09:f000:9a0:120:be24:11ff:fe28:4b63:5432',
> ```
> 
> Because this error is thrown by PostgreSQL not Nextcloud and I think Postgres does not support the `[...]` notation.

Without brackets, it will try instead to resolve as a hostname.

`Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] could not translate host name "fd09:f000:9a0:120:be24:11ff:fe28" to address: Name or service not known in /var/www/nextcloud/lib/private/DB/Connection.php:139`

Notice the missing **:4b63** at the end of the host name, i assume this is caused by something somewhere trying to split the hostname and port in a naive way.

I've tried to add the 5432 port at the end of the dbhost to compensate for this, but now i get an endlessly hanging page (which then times out).

> (When using IPv6 you should not need to use ports, as you can assign an address per application)

That is incorrect, you still need to define the port (unless it's default) because ipv6 changes the addressing scheme but TCP/UDP connections are the same and require a server port.

**Comment by susnux** [comment]
> Using
>   'dbhost' => '[fd09:f000:9a0:120:be24:11ff:fe28:4b63]:5432',
> 
> Doctrine\DBAL\Exception: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[08006] [7] could not translate host name "[fd09:f000:9a0:120:be24:11ff:fe28:4b63]" to address: Name or service not known in /var/www/nextcloud/lib/private/DB/Connection.php:139


Since Nextcloud 28 we use Doctrine DBAL 3.7 which is using `pg_connect`, that function does not support the `[]` notation.
So we need to use it without the [ ].

The infinite loading could be a connection issue, doctrine does not set a timeout as far as I can see, so if the server can not be reached it will load infinite.

> That is incorrect, you still need to define the port (unless it's default) because ipv6 changes the addressing scheme but TCP/UDP connections are the same and require a server port.

Yes but there is no need anymore for custom ports as you have a whole address block available for services. But thats probably a matter of preferences.

**Comment by susnux** [comment]
> `pg_connect`, that function does not support the `[]` notation.

Because of the underlying `PQconnectdb` from libpq. This allows either the `[]` notation for the `postgres://[...]/db` format or without `[]` when using the key value notation (which is used by doctrine).
