### ISSUE TITLE
Chrome and Firefox slow upload of files

### ISSUE THREAD

**Issue by Nicolaj-ITS** [nextcloud/server#4438]
### Steps to reproduce
1. Open Chrome/Firefox drag file to folder
2. Look at the network speed, 10Mbps

### Expected behaviour
In IE when doing the same i get 500Mbps

### Actual behaviour
Only getting 10Mbps upload speed with Chrome and Firefox but getting 500Mbps with IE

### Server configuration

**Operating system**: Debian Stretch 4.9.18-1

**Web server:** Apache2

**Database:** Mariadb 10.1.22

**PHP version:** PHP 7.0.16-3

**Nextcloud version:** Nextcloud 11.0.2 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh Install

**Where did you install Nextcloud from:** Source

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
  - activity: 2.4.1
  - camerarawpreviews: 0.0.1
  - dav: 1.1.1
  - direct_menu: 0.10.1
  - federatedfilesharing: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "oczknmu8u0wp",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "domain.tld"
        ],
        "datadirectory": "\/data",
        "overwrite.cli.url": "https:\/\/domain.tld\/nextcloud",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "default_language": "en_GB",
        "theme": "",
        "enabledPreviewProviders": [
            "OC\\Preview\\Raw",
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF"
        ],
        "singleuser": false,
        "asset-pipeline.enabled": true
    }
}
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** None

### Client configuration
**Browser:** Chrome 58 / Firefox 53 / Internet Explorer 11

**Operating system:** Windows Server 2012R2(Remote Desktop Services)

**Comment by MorrisJobke** [comment]
I would not know, why there should be a difference. Both ways use the same code. :/ Are you 100% sure, that this is because of Chrome/Firefox? Could you try it with another PC (best in another network) and do the upload there as well? Do you see maybe high CPU load during the upload on the desktop? Are you sure, that the server is not the bottleneck (if there is another upload happening when testing the upload in chrome/firefox or the server is doing other stuff like backups).

**Comment by RicRood** [comment]
In a test environment I experience the same issues. Chrome is not able to do the upload at all, and MSIE without any delay.

**Comment by MorrisJobke** [comment]
@RicRood Could you provide some information about the stuff I asked?

**Comment by oparoz** [comment]
Could everybody try with a virgin profile (no extensions)?

**Comment by Nicolaj-ITS** [comment]
I just had time to test with 11.0.3, i still get the slow speeds on FF and Chrome, but not on MSIE.

Server is spec'd fine, it handles 500Mbps in IE without problems both ways, no other users on it since it's my private backup site, we are looking into using nextcloud in the company, that is why i stumbled over the issue.

on the desktop i see almost no CPU usage, but with 32 cores that should't be a problem and it is on a Gbit line, I also tested from another location and got the same result, that location had a 500Mbit line, and the desktop where with 16 cores and could't see any big CPU usage on it.

I just tryed in Incognito mode on chrome since that disables extensions and such and i still only get around the 10Mbps.

**Comment by MorrisJobke** [comment]
Maybe somebody from @nextcloud/javascript could have a look at this.

**Comment by skjnldsv** [comment]
Speed is pretty nice here :/
I can cap my server bandwidth
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen. on chrome and ff.
