### ISSUE TITLE
[Bug]: file upload drag and drop doesn't process multiple files upload in empty folder

### ISSUE THREAD

**Issue by DorraJaouad** [nextcloud/server#44390]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Drag and drop does not initiate upload if multiple files were selected. On v28, first drop leads to nothing and the second attempt functions normally. (no error shown in browser)

### Steps to reproduce

1. Create a folder and open it
2.  select multiple files and use drag and drop to upload them

### Expected behavior

Files uploaded but it only happens if you drag and drop again.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by LM-vb** [comment]
see #43074

**Comment by DorraJaouad** [comment]
It's not the same issue I think. Multiple files are not uploaded at all and not only one file of them is uploaded. It happens only when the folder is newly created and empty.

**Comment by solracsf** [comment]
It may be the same issue; can you use Firefox and retry?

**Comment by D3nnis3n** [comment]
This still persists, when dragging multiple files on the appearing upload marker only one file is actually uploaded.
I don't use Firefox and it doesn't work well with big file uploading, as they tend to get cancelled mid-upload, which doesn't happen with Chrome, so I can't test that.

**Comment by skjnldsv** [comment]
@DorraJaouad 28.0.3 or 28.0.4 ?

**Comment by susnux** [comment]
I can not reproduce this on 28.0.4 and current master (neither chromium nor firefox).

Are you sure you dropped the files on the drop area? Because dropping outside the drop zone does not work.

**Comment by DorraJaouad** [comment]
> Are you sure you dropped the files on the drop area? Because dropping outside the drop zone does not work.

Trying it again now does not reproduce the issue 🙈  so probably I was dropping next to the zone like this:

![image](https://github.com/nextcloud/server/assets/84044328/364a3e18-4831-433b-8352-4a5c64405b10)
