### ISSUE TITLE
Update docs so httpoxy is mitigated 

### ISSUE THREAD

**Issue by longsleep** [nextcloud/server#444]
As Nextcloud is using Guzzle it might be vulnerable to https://httpoxy.org/#affected-summary - as it seems that there is no way to prevent this from PHP userland code, the documentation should be updated to include the corresponding removal of incoming Proxy header.

**Comment by LukasReschke** [comment]
We did already release a patched release yesterday :-) – It's a 9.0.52 with the Guzzle patch cherry-picked on top. (the patch stops using the `HTTP_PROXY` variable in Guzzle) 

https://nextcloud.com/httpoxy-can-affect-nextcloud-get-your-update-now/
