### ISSUE TITLE
[Bug]: Changes to a file located in an AWS S3 bucket are not being saved if it's edited via an external link

### ISSUE THREAD

**Issue by SergeyKorneyev** [nextcloud/server#44402]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The issue was originally reported as related to the ONYLOFFICE integration, but it can also be reproduced with the Text app.

### Steps to reproduce

1. Install the External Storage app
2. Connect AWS S3 to Nextcloud with the app and enable sharing
3. Open the S3 folder and create a new folder
4. Create an editable file in the new folder
5. Share the new folder via an external link with editing and uploading permissions 
6. Open the link and open the file with ONLYOFFICE or Text
7. Make changes to file and save it
8. Open the file without using the external share link

Depending on the version of Nextcloud and the editing application used, you might or might not get an error, but the file will be missing the changes made in step 7 in any case.

### Expected behavior

Changes to the file should be saved regardless of whether it was opened directly or via an external share.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/server/pull/44294 is a more general PR to resolve this, however https://github.com/nextcloud/server/pull/43613 also made its way to the stable branches already so this should be addressed meanwhile with the latest maintenance releases.

@SergeyKorneyev Could you check and verify this as well?
