### ISSUE TITLE
Move permission for shared files/subfolders

### ISSUE THREAD

**Issue by enjeck** [nextcloud/server#44404]
When sharing files/folders publicly, I have the option to specify permissions like "edit", "copy", "delete". It would be nice if there was an additional "move" permission for moving files between subfolders.  

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When sharing files/folders publicly, I have the option to specify permissions like "edit", "copy", "delete". It would be nice if there was an additional "move" permission for moving files between subfolders.  When I share files/folders with the "edit", "create" and "read" permissions, but _without_ the "delete" permission, users are unable to move files. Even though they can't move things, the "Move or copy" button still shows, which is confusing.  
![Screenshot from 2024-03-22 11-34-42](https://github.com/nextcloud/server/assets/32180937/fc69f133-5b16-4c43-8523-5032fa62cea4)

**Describe the solution you'd like**
Either there's a special "move" permission. Or the "Move or copy" option is removed (or modified) since the user can't perform that action.

**Describe alternatives you've considered**

**Additional context**

**Comment by godfuture** [comment]
I think splitting "delete" permission into "move" and "delete" is more important than adjusting UI to specific permissions in the folder. It totally makes sense to differ between move and delete, because when allowing to move files the sharing user can rest asured files will not disappear. Whilst giving delete permission allows them to change the amount of files available.

**Comment by krupper** [comment]
In my opinion, the UI should not display any options that are not available. In our organization, we increasingly have questions as to why folders in shares (without delete permission) cannot be moved. The corresponding error message for the recipient of a share is also not meaningful.

**Comment by airbenich** [comment]
Same here +1
