### ISSUE TITLE
Title on public pages is truncated

### ISSUE THREAD

**Issue by punkyard** [nextcloud/server#44405]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
author name truncated in public share

<img width="244" alt="form title author" src="https://github.com/nextcloud/forms/assets/59349105/6c44c789-4a8d-44a2-8a1d-01aa22d5d488">

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 27.1.5 AiO 7.12.1
- Forms-Version: 3.4.5

**Desktop (please complete the following information):**
 - OS: macos ventura
 - Browser safari and brave 1.62.165

**Comment by susnux** [comment]
cc @nextcloud/designers
