### ISSUE TITLE
Issues running tests

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/server#4440]
`./autotest.sh sqlite` works fine without errors (also executes dav tests)

`./autotest.sh sqlite apps/dav` throws plenty of `::__construct() must implement interface OCP\IDBConnection, null given` errors

`phpunit --bootstrap tests/bootstrap.php -c apps/dav/tests/unit/phpunit.xml` throws the same errors.

@LukasReschke was also able to reproduce this

All three commands work just fine on `stable11`.

### Server configuration

**Operating system**: ubuntu 17.04

**Web server:** apache

**Database:** sqlite / mysql

**PHP version:** 7.0.15-1ubuntu4

**PHPUnit version:** 5.7.19

**Nextcloud version:** 1bd3bd33f9 (but also before, not stable11)

**Comment by juliushaertl** [comment]
I had the same issues running tests of the deck app locally. Those were caused by test classes that inherited from \Test\TestCase that implemented a setup method without calling parent::setUp().

Adding those fixed it for me, maybe that is also the case somewhere in the dav app.

**Comment by georgehrke** [comment]
Hm. no.
`parent::setUp()` is present everywhere in the dav app :/

**Comment by georgehrke** [comment]
@juliushaertl It was indeed a missing `parent::setUp()`
But why does a missing `parent::setUp()` in one test break everything else? 😖
