### ISSUE TITLE
Maximum upload size 2GB is not accepted, while 1.99 is

### ISSUE THREAD

**Issue by futurechild** [nextcloud/server#4441]
### Steps to reproduce
admin panel -> additional settings -> File Handling -> maximum upload size
1. Enter 2 GB produces error notification
2. Enter 1.99 GB accepts and saves setting, change text to 2GB, pressing save again results in error notifiation

### Expected behaviour
Maximum upload size should accept 2 GB as a valid value.

### Actual behaviour
Error notification when 2 GB is entered

### Server configuration
**Operating system**: Ubuntu 14.04.5
**Web server: Apache 2.4.7
**Database: MySQL 5.5.54
**PHP version: 7.0.18
**Nextcloud version:11.0.2 (stabble)
**Updated from an older Nextcloud/ownCloud or fresh install: updated from owncloud 9.0 
**Where did you install Nextcloud from: 
https://github.com/nextcloud/updater/raw/4858b8fd322a228cba2efab35488085ec407efc9/updater.phar

**Comment by MorrisJobke** [comment]
cc @nextcloud/javascript maybe?

**Comment by nickvergessen** [comment]
Are you running on 32bit OS?

**Comment by futurechild** [comment]
Yes it's running on a 32 bit OS
More specific, it's a repurposed HP T520 thin client (It's just for personal use).

But if 2GB is too large to handle, should the 1.99GB setting not be left as is instead of being rounded up to 2 GB ?

**Comment by nickvergessen** [comment]
The problem is, that 2 GB is 2147483648 bytes which is bigger (by 1) then MAX_INT on 32 bits. Therefor the value can not be created and written. Sorry

**Comment by a-schild** [comment]
Would be nice to have a error handling in the UI not allowing too large values. It's definitively not what the users would see as logical behaviour
