### ISSUE TITLE
External storage global OAuth app ID

### ISSUE THREAD

**Issue by zauguin** [nextcloud/server#4442]
When users are allowed to configure external storage for example with a Dropbox backend, each user has to enter app credentials.
It would be very useful to add a global configurarion value for server wide app credentials, so that every user can individually login with their own Dropbox accounts, but reuse the same global app ID/secret.
The same applies to Google Drive.

**Comment by MorrisJobke** [comment]
> It would be very useful to add a global configurarion value for server wide app credentials, so that every user can individually login with their own Dropbox accounts, but reuse the same global app ID/secret.
> The same applies to Google Drive.

This would not really work well, because on both Google Drive and Dropbox are quite low rate limits and quite fast the external storage would not be read-/writable anymore.

cc @icewind1991

**Comment by zauguin** [comment]
@MorrisJobke According to the documentation, on Dropbox at least the rate limiting only applies on a per-user basis, so it shouldn't have different effects if we share an app ID for multiple users.
Or do you refer to the user count limit for non-production apps?

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
