### ISSUE TITLE
[Bug]: Cannot view full file/folder modification date on web interface when hovering mouse

### ISSUE THREAD

**Issue by kimimaru4000** [nextcloud/server#44441]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since upgrading to Nextcloud 28, hovering the mouse over the date for a file or folder in the Modified column does not show the date it was last modified. This worked fine in Nextcloud 26 and Nextcloud 27, so this is a regression.

### Steps to reproduce

1. On the web interface, either create a new file or folder or go to an existing file or folder.
2. Hover the mouse over the string in the Modified column (Ex. "last year" or "2 days ago")
3. Observe how there's no longer a tooltip showing the exact date and time the file or folder was modified.

### Expected behavior

It shows a tooltip with the exact date and time the file or folder was modified.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.0.10.1",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.3.2",
        "overwrite.cli.url": "http:\/\/10.0.10.1\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "maintenance": false,
        "theme": "",
        "maintenance_window_start": 1,
        "enable_previews": false,
        "preview_max_x": 256,
        "preview_max_y": 256,
        "preview_max_filesize_image": 25,
        "data-fingerprint": "43eade95926d4becbb7517427469b589"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - bruteforcesettings: 2.8.0
  - checksum: 1.2.3
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contactsinteraction: 1.9.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_automatedtagging: 1.18.0
  - files_external: 1.20.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - groupfolders: 16.0.4
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - support: 1.11.0
  - systemtags: 1.18.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - viewer: 2.2.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - circles: 28.0.0-dev (installed 26.0.0)
  - dashboard: 7.8.0 (installed 7.0.0)
  - encryption: 2.16.0
  - files_markdown: 2.4.1 (installed 2.4.1)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - recommendations: 2.0.0 (installed 0.8.0)
  - survey_client: 1.16.0 (installed 1.15.0)
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0
  - user_status: 1.8.1 (installed 1.0.1)
  - weather_status: 1.8.0 (installed 1.0.0)
```

### Additional info

Nextcloud Hub 7 (Nextcloud 28.0.3)
PHP 8.1.2-1ubuntu2.14
mariadb  Ver 15.1 Distrib 10.6.16-MariaDB
Apache/2.4.52

**Comment by susnux** [comment]
What browser are you using (+ version)? Because Every version I checked (28.0.5 and later) correctly have the `title` prop set so that the native browser tooltip is shown.

**Comment by kimimaru4000** [comment]
Hey @susnux, I'm using Firefox 128.0.2 and I'm now on Nextcloud 29. I see that when I use a brand new Firefox profile, the issue doesn't occur. However, since I'm self-hosting Nextcloud, I'm wondering why the same Firefox settings don't work with this feature on versions after 27. Is there something in particular Nextcloud needs for this to work that my Firefox settings could be breaking?

I see a lot of `NetworkError` messages in the Firefox console. Here are a few:
```
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: http://my.infrastructure/core/css/server.css?v=d4936e67-0
Source Map URL: server.css.map

Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: http://my.infrastructure/apps/text/js/text-files.js?v=d4936e67-0
Source Map URL: text-files.js.map?v=1eca470737eaeb62ed78
```

Since all these files are minified it's hard to tell what I should be looking for.

**Comment by skjnldsv** [comment]
> Is there something in particular Nextcloud needs for this to work that my Firefox settings could be breaking?

I see no reason why. I also cannot reproduce the issue.
Can you inspect the element, with right click and see if the title is set for you?

![image](https://github.com/user-attachments/assets/4964c4df-4ee6-41ad-a2fb-bc6599498e7e)

**Comment by kimimaru4000** [comment]
Yeah, I see the title element in the inspector. Turns out it also doesn't show these titles for other elements like GitHub comment timestamps.

**Comment by skjnldsv** [comment]
Then it's a browser/os issue :shrug: :confused:

**Comment by susnux** [comment]
Sounds like cache issue / browser profile issue.
