### ISSUE TITLE
API ocs/v1.php/cloud/users/

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/server#4445]
I have several user with **crash at login** with the new version Nextcloud iOS 2.17

I have found a issue with my Nextcloud 11 :

1) I create a user **M**arino password blablblaa with Admin group on Nextcloud Server.

2) Insert in Nextcloud iOS new user credential **M**arino  (case sensitive ?!)  password blablabla, the API ocs/v1.php/cloud/users/ return :

```
2017-04-22 12:51:43.917 Nextcloud[34280:994288] [LOG] User Profile : {
    ocs =     {
        data =         {
            displayname = Marino;
            email = "<null>";
            enabled = true;
            quota =             {
                free = 35686019072;
                quota = "-3";
                relative = "0.02";
                total = 35693093802;
                used = 7074730;
            };
        };
        meta =         {
            itemsperpage = "";
            message = OK;
            status = ok;
            statuscode = 100;
            totalitems = "";
        };
    };
}
```

3) If I creata a user **m**arino (case sensitive ?!) password blablabla , the API ocs/v1.php/cloud/users/ return :

```
2017-04-22 13:01:56.587 Nextcloud[34316:1000569] [LOG] User Profile : {
    ocs =     {
        data =         {
            displayname = Marino;
            email = "<null>";
            enabled = true;
            quota =             (
            );
        };
        meta =         {
            itemsperpage = "";
            message = OK;
            status = ok;
            statuscode = 100;
            totalitems = "";
        };
    };
}

```
Now quota is NULL and iOS crash !

This is a log of a user : 

![image1](https://cloud.githubusercontent.com/assets/8616947/25312202/9ed4c07a-2813-11e7-901e-69e26f56cad0.PNG)

**Comment by MorrisJobke** [comment]
cc @rullzer @nickvergessen @icewind 1991
