### ISSUE TITLE
[Bug]: Autofill “Share label” and “Set password” fields when editing a shared link

### ISSUE THREAD

**Issue by urfin73** [nextcloud/server#44451]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In nextcloud version 28.0.3, I discovered an unpleasant feature when editing custom permissions for a shared link.
The “Link name” and “Set password” fields are filled in automatically and are taken from the nextcloud user name and password saved by the browser.

### Steps to reproduce

1. The shared link is configured to "Always ask for password" 
2. Create new share link for file or folder (We do not specify “Link name”)
3. Select edit Custom permissions" for this link
4. The “Link name” and “Set password” fields are filled in automatically and are taken from the nextcloud user name and password saved by the browser.

### Expected behavior

The “Link name” and “Set password” fields must be empty

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by shk3bq4d** [comment]
Hello, I upgraded yesterday from 26.0.12 to 27.1.7 and have since witnessed the exact same problem.

**Comment by Flow-Gee** [comment]
I also have this annoying bug in version 28.0.3 using Microsoft Edge Version 122.0.2365.92

Every time I enter the edit view of a share with "Custom Permissions" MS Edge auto fills and therefore overwrites the share's password with the Nextcloud user password:
![image](https://github.com/nextcloud/server/assets/1423887/57426f5d-ab64-40e9-9509-56decb795005)

**Comment by rrroig** [comment]
Same here. Annoying bug. Too much JavaScript... Please keep it simple.

**Comment by susnux** [comment]
What you see there is not Nextcloud filling out the fields but your browser from the saved passwords, not much we can do there.

**Comment by urfin73** [comment]
> not much we can do there.

You can change the names of input fields to prevent the browser from auto-filling them.

**Comment by urfin73** [comment]
> мало что мы там можем сделать

I will, of course, turn off autofill. But there are many users, such as accountants, managers. What should we do with them?

**Comment by urfin73** [comment]
Is it possible to name the input fields differently, without using the words “label” and “password”, so that the browser does not use auto-substitution?

**Comment by susnux** [comment]
I pushed a fixed waiting for reviews in #44575 :)
