### ISSUE TITLE
Web access to calendar CalDAV address should generate "Nextcloud" error message

### ISSUE THREAD

**Issue by spreedniels** [nextcloud/server#4446]
Not an error but error message may be improved and changed to "Nextcloud". 
Current response of Web browser access to the calendar's CalDAV URL is:  
"This is the WebDAV interface. It can only be accessed by WebDAV clients such as the ownCloud desktop sync client."

May be updated to "Nextcloud" instead.

All versions, all browsers.

**Comment by LukasReschke** [comment]
Will be fixed with Nextcloud 12 (ref https://github.com/nextcloud/server/commit/07b35b7bae3c3bc684209eb4db20943276afff85)
