### ISSUE TITLE
[Bug]: unable to see nor navigate into newly created folders from the copy/move modal

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/server#44482]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I want to create a folder which I want to move/copy a file into, this newly created folder does not appear.
So I can't navigate into it.

### Steps to reproduce

1. Click move a file
2. Click the New button, type in a folder name, hit enter
3. the prompt stays open
4. type in a new folder name, hit enter
5. the prompt stays open
6. type in a new folder name, hit enter
7. escape the modal
8. refresh the page
9. Three folders has been created, and I could not move my file into them

### Expected behavior

newly created folders should appear in the folder list

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by maximelehericy** [comment]
@Pytal @sorbaugh

**Comment by jadjoud** [comment]
hello @maximelehericy 
can u please provide me with your nextcloud server version ?
