### ISSUE TITLE
Is there any way to attribute or multi directory to nextcloud

### ISSUE THREAD

**Issue by sinhkien** [nextcloud/server#44501]
I had a situation like this where I had 2 users
I can specify that user A will be created in folder A and B will be in folder B
Make sure this folder is the home folder so external storage cannot be used
Is there any way to handle this problem?

I use Nextcloud version 28.0.2
OS: Rockylinux 9

**Comment by solracsf** [comment]
Please head to https://help.nextcloud.com for these questions. Thanks. 👍
