### ISSUE TITLE
Can't upload photos from the app(android)

### ISSUE THREAD

**Issue by svesve** [nextcloud/server#4450]
### Steps to reproduce
1. Auto upload photos from android app

### Expected behaviour
Take a photo, wait until it upload to my nextcloud instance

### Actual behaviour
Trying to autoupload photos from the phone, when I've take a photo, after 10-30 sec autouploader starts, but, after about 20-40 seconds it shows me an error, that photo can't be uploaded. If I retry upload manually from the app, upload starts without any error.
### Server configuration

**Operating system**: Ubuntu 14.04.3 LTS

**Web server:** nginx/1.4.6

**Database:** mysql  Ver 14.14 Distrib 5.6.35-80.0,

**PHP version:** PHP 5.6.29-1+deb.sury.org~trusty+1 (cli)

**Nextcloud version:** Nextcloud 11.0.2 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from an older Nextcloud

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - calendar
  - encryption
  - external
  - federation
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - user_external
  - user_ldap
  - user_saml

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "oc9zk3zlm9df",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.drozdin.ru"
        ],
        "datadirectory": "\/home\/***REMOVED SENSITIVE VALUE***\/cloud_data",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Moscow",
        "installed": true,
        "loglevel": 0,
        "logfile": "\/home\/cloud\/logs\/owncloud.log",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_from_address": "da",
        "mail_domain": "***REMOVED SENSITIVE VALUE***.com",
        "mail_smtphost": "mail.***REMOVED SENSITIVE VALUE***.com",
        "mail_smtpport": "25",
        "theme": "",
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "updater.release.channel": "stable"
    }
}

</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### Web server error log
<details>
<summary>Web server error log</summary>

188.1.22.19 - user[23/Apr/2017:12:28:27 +0300] "HEAD /remote.php/webdav/Photos//IMG_20170423_122409.jpg HTTP/1.1" 404 0 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

{"reqId":"02LSIJaEXiuTc2rG0Qwl","remoteAddr":"188.1.22.19","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name Photos\\\/IMG_20170423_122409.jpg could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/cloud\\\/data\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(81): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('Photos\\\/IMG_2017...')\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/home\\\/cloud\\\/data\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/home\\\/cloud\\\/data\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/home\\\/cloud\\\/data\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(253): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response), false)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpHead(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/home\\\/cloud\\\/data\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/home\\\/cloud\\\/data\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:HEAD', Array)\\n#8 \\\/home\\\/cloud\\\/data\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/home\\\/cloud\\\/data\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/home\\\/cloud\\\/data\\\/remote.php(165): require_once('\\\/home\\\/cloud\\\/dat...')\\n#11 {main}\",\"File\":\"\\\/home\\\/cloud\\\/data\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":173,\"User\":\"test\"}","level":0,"time":"2017-04-23T12:28:27+03:00","method":"HEAD","url":"\/remote.php\/webdav\/Photos\/\/IMG_20170423_122409.jpg","user":"test","version":"11.0.2.7"}

</details>

patch [#3757](https://github.com/nextcloud/server/pull/3757 ) not help me

**Comment by mario** [comment]
What version of Android? What version of app? Which phone? :)

**Comment by svesve** [comment]
android 6.0.1 Xiaomi Redmi 3S, app version 1.4.2

**Comment by MorrisJobke** [comment]
Please open this in https://github.com/nextcloud/android/issues Thanks
