### ISSUE TITLE
"Delete Calendar" Issue

### ISSUE THREAD

**Issue by cal940** [nextcloud/server#4451]
Can't delete calender in NC 11.0.2 Stable (see Screenshot)

![](http://i.imgur.com/fbSlKxt.jpg)

**Comment by MariusBluem** [comment]
This is an issue in the calendar app http://github.com/nextcloud/calendar and not in the server-part, this repository is about 😉 Please open a new issue over there, and thank you very much for reporting that. I can reproduce that 😅

**Comment by georgehrke** [comment]
@cal940 And please actually make use of the issue template. There is a reason its there ;)
