### ISSUE TITLE
Configuration parameter "enable_certificate_management" without any effect

### ISSUE THREAD

**Issue by jn-se** [nextcloud/server#4452]
The 'enable_certificate_management' configuration parameter in the config.php does not have any impact on the administration interface. There is no possibility to configure certificates.

Parameter is documented at https://docs.nextcloud.com/server/11/admin_manual/configuration_server/config_sample_php_parameters.html

### Steps to reproduce
1. Add the following line to the config.php

`'enable_certificate_management' => true,`

### Expected behaviour
An administration interface to configure custom certificates.

### Actual behaviour
No configuration options shown on the administration pages.

### Server configuration

**Operating system**: Ubuntu 14.04
**PHP version:** 7.x
**Nextcloud version:** 11.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Comment by MorrisJobke** [comment]
This setting was removed and the entries to configure certificates will only show up if this is actually used. They are currently only used by the files external app. So once the files external is enabled the SSL configuration is possible.

**Comment by MorrisJobke** [comment]
Documentation is fixed with #4800

**Comment by jn-se** [comment]
Thank you @MorrisJobke
