### ISSUE TITLE
[Bug]: File app detailed info side pane not localized

### ISSUE THREAD

**Issue by yatli** [nextcloud/server#44557]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![image](https://github.com/nextcloud/server/assets/20684720/5dbac2a8-3173-42be-8e61-5028198918a9)

### Steps to reproduce

1. Create a new user, set locale to Chinese (Simplified)
2. Upload some images
3. In the Files app, right click -> detailed info, observe "Current version" and the rough time info in English.

### Expected behavior

I believe at least the rough time info (like "1 year ago") is already localized in other places.

### Installation method

Community Docker image

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Reproduced in 28.
But looks correct in 29.

**Comment by skjnldsv** [comment]
Fixed already, I guess that was a matter of time before the translations got done
![Image](https://github.com/user-attachments/assets/99111cbf-d996-448e-9f75-c3e096cfcd57)
