### ISSUE TITLE
Share thumbnails together with the shared folder

### ISSUE THREAD

**Issue by scansse** [nextcloud/server#4455]
When sharing a folder with other users, these users have to generate their own version of the thumbnails of these files (I am mostly sharing pictures). This seems to me both a waste of storage space and a waste of time to produce the thumbnails. 

### Expected behaviour
When I share a folder, the user/group I share with should benefit from my already generated thumbnails.

### Actual behaviour
Currently the user that opens a shared folder for the first time has to regenerate its own version of thumbnails

**Comment by LukasReschke** [comment]
Previews are shared since Nextcloud 11. The gallery app will use shared previews starting in Nextcloud 12. (https://github.com/nextcloud/gallery/pull/187)
