### ISSUE TITLE
[Bug]: Moving a shared folder, duplicates it 

### ISSUE THREAD

**Issue by hamza221** [nextcloud/server#44554]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Moving a shared folder from the default path of an incoming share, duplicates it in the destination path

### Steps to reproduce

 
1. Bob creates folder "Shared_folder"
2. Bob shares the "Shared_folder" with Alice
3. Alice moves the "Shared_folder" from the default path of an incoming share., to one of her own directories in the cloud "dest_folder". 
4. Shared_folder appears both  on the default path and "dest_folder" and synchronises twice resulting in storage issues

### Expected behavior

Shared_folder appears only in dest_folder

### Installation method

None

### Nextcloud Server version

27

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by sorbaugh** [comment]
@emoral435 not 100% clear so far if frontend or backend related, maybe you can find out more?

**Comment by skjnldsv** [comment]
> ### Nextcloud Server version
> 27

@hamza221 can you confirm that again?

**Comment by skjnldsv** [comment]
No feedback, closing
