### ISSUE TITLE
[Bug]: Nextcloud Web Interface Slow

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/server#44563]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Noticing alot of lagg and slow on nextcloud dashbord and files. please see network ms times. Im running Nextcloud 29.0.0 RC1

Dashbord screen shot
<img width="1281" alt="Screenshot 2024-03-28 at 5 27 55 PM" 
src="https://github.com/nextcloud/server/assets/59488153/25142ddc-3553-446c-8d81-f47cf12f2cff">

Files Screenshot
<img width="1281" alt="Screenshot 2024-03-28 at 5 28 56 PM" src="https://github.com/nextcloud/server/assets/59488153/f4ce5b4f-f58e-4d71-a343-f2a2423270c5">

### Steps to reproduce

1. Noticing more lag on Google Chrome running on MacOS. Lagg only seems to happen with Nextcloud no other websites having issues

### Expected behavior

Should be snappy

Also Test this on the same MacOS running Firefox slowness seems to be better. Looks like it more slow with Chrome

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

master

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.0.14",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "simpleSignUpLink.shown": false,
        "skeletondirectory": "",
        "default_locale": "en_US",
        "default_phone_region": "US",
        "allow_local_remote_servers": true,
        "ffmpeg": "\/usr\/bin\/ffmpeg",
        "preview_max_memory": 1280,
        "enabledPreviewProviders": [
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Image",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\SVG",
            "OC\\Preview\\Font",
            "OC\\Preview\\MP3",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI",
            "OC\\Preview\\MOV",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\MSOfficeDoc"
        ],
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "587",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "loglevel": 2,
        "logtimezone": "America\/Chicago",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "maintenance_window_start": 1,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [
            "guest_app"
        ],
        "theme": "",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "beta",
        "memories.exiftool": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/exiftool-amd64-glibc",
        "memories.vod.path": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "defaultapp": "dashboard,files,memories,spreed,activity",
        "memories.gis_type": 1,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - bruteforcesettings: 2.9.0
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_automatedtagging: 1.19.0
  - files_downloadlimit: 2.0.0
  - files_external: 1.21.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - guests: 3.1.0
  - impersonate: 1.16.0
  - integration_onedrive: 3.2.0
  - integration_youtube: 0.2.1
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - nextcloud_announcements: 1.18.0
  - notifications: 2.17.0
  - notify_push: 0.6.10
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - photos: 2.5.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recognize: 6.1.1
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - richdocuments: 8.4.0-beta.2
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - spreed: 19.0.0-rc.1
  - support: 1.12.0
  - survey_client: 1.17.0
  - suspicious_login: 7.0.0
  - systemtags: 1.19.0
  - text: 3.10.0
  - theming: 2.4.0
  - twofactor_admin: 4.5.0
  - twofactor_backupcodes: 1.18.0
  - twofactor_nextcloud_notification: 3.9.0
  - twofactor_totp: 11.0.0-dev
  - twofactor_webauthn: 1.4.0
  - updatenotification: 1.19.1
  - user_ldap: 1.20.0
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0
Disabled:
  - circles: 29.0.0-dev (installed 27.0.1)
  - encryption: 2.17.0
  - memories: 7.0.2 (installed 7.0.2)
  - previewgenerator: 5.4.0 (installed 5.4.0)
  - sendent: 3.0.7 (installed 3.0.7)
  - theming_customcss: 1.15.0 (installed 1.15.0)
  - twofactor_email: 2.7.4 (installed 2.7.4)
```

**Comment by mhzawadi** [comment]
I have the same issue, but running v28.0.4. The update to v28 from v27 seems to have slowed nextcloud down, what I have seen is a lot of fliecache querys with every page load.

Not sue why nextcloud would query the filecache with every page page load, even looking at the deck app

**Comment by AndyXheli** [comment]
I can also confirm that this is happening on NC 28 servers, too.

**Comment by mhzawadi** [comment]
I have just updated group folders and that seems to improve the speed, seems group folders was running SQL for every page load

**Comment by RoseCoded** [comment]
I have the same issue on Ubuntu Server 24.04 with Apache2 and web installed nextcloud 29.0.2. it takes me about 20 minutes to load a page ---> fix this

**Comment by skjnldsv** [comment]
> it takes me about 20 minutes to load a page

if it takes 20 minutes that's definitely an issue on your server.
We are all using nc on various hardware, this issue is about a slight slowdown, (milliseconds according to the first post). Yours is completely different then :/

**Comment by skjnldsv** [comment]
@AndyXheli we improved a lot over the last patch releases of 28 and 29, do you still have issues?

**Comment by RoseCoded** [comment]
The issue is resolved.On Wed, 2024-07-31 at 08:58 -0700, John Molakvoæ wrote:> @AndyXheli we improved a lot over the last patch releases of 28 and> 29, do you still have issues?> —> Reply to this email directly, view it on GitHub, or unsubscribe.> You are receiving this because you commented.Message ID:>

**Comment by AndyXheli** [comment]
Running on Nc 30 right now but seems to but a lot better now
