### ISSUE TITLE
[Bug]: Thumbnail doesn't update when source image is changed

### ISSUE THREAD

**Issue by rightsaidfred99** [nextcloud/server#44630]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If you upload an image to Nextcloud (via external storage), the thumbnail will load as normal. 
However when you replace the source image, Nextcloud will sitll use the old thumbnail for the image. 

This wasn't the case a few years ago

### Steps to reproduce

1. Upload an image to NC via SMB or external storage method
2. Open NC on an iPad, goto the directory and the thumbnail will generate
3. Upload a new image or tweaked image to NC via SMB or external method, as long as original image is replace
4. Open NC again and the old image thumbnail will still be used even though NC will show the image is modified

### Expected behavior

NC should always be showing the thumbnail that represents the source image

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Other

### PHP engine version

PHP 8.3

### Web server

None

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by rightsaidfred99** [comment]
It happens on the macOS app, desktop (chrome or safari) which leads me to believe it might be a caching thing.

**Comment by ostasevych** [comment]
> Are you certain it's not your browser that simply cached the thumbnail? Force a refresh (e.g. in Chrome, press Ctrl-F5 to force a reload of images).

Actually, I experience the same. And I need manually click Ctrl-F5 each time after modifying the file.

**Comment by f0k** [comment]
NextCloud tells the browser that it can rely on the cached version for 24 hours, and only has to re-check with the server (with a conditional request) after that time has passed: https://github.com/nextcloud/server/blob/54afea4b01385106a241a5161b3894e669716107/apps/files_sharing/lib/Controller/PublicPreviewController.php#L136

**Comment by rightsaidfred99** [comment]
But if the source image changes, shouldn't there be a trigger where the thumbnail gets redone? I swear that used to happen years ago.

**Comment by f0k** [comment]
> But if the source image changes, shouldn't there be a trigger where the thumbnail gets redone?

The thumbnail probably gets redone, but your browser does not ask the server for it, only after 24 hours or when you press Ctrl+F5. The server sends a `Cache-Control: max-age=86400, must-revalidate` header, so the browser will not request the image from the server again for 24 hours (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching for all the details). Whether this is a too long timespan is discussable, of course. In a browser you can usually bypass the cache by using Ctrl+F5.

**Comment by szaimen** [comment]
Cc @nextcloud/server-frontend

**Comment by rightsaidfred99** [comment]
You can't Ctrl+F5 on an iPad or Android phone though?

**Comment by ostasevych** [comment]
> > But if the source image changes, shouldn't there be a trigger where the thumbnail gets redone?
> 
> The thumbnail probably gets redone, but your browser does not ask the server for it, only after 24 hours or when you press Ctrl+F5. The server sends a `Cache-Control: max-age=86400, must-revalidate` header, so the browser will not request the image from the server again for 24 hours (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching for all the details). Whether this is a too long timespan is discussable, of course. In a browser you can usually bypass the cache by using Ctrl+F5.

That is a bad behaviour. There are online graphic editors which easily update the picture on the fly. Why it is not possible to do that in this app?

**Comment by skjnldsv** [comment]
We usually add an etag to the preview fetch. At least the web interface does.
So it does fetch the new preview when the file changes.

@rightsaidfred99 you mentionned the ipad, you mean with the NC iOS app?

**Comment by rightsaidfred99** [comment]
@skjnldsv yes, the iOS app specifically. But the same thing also happens on the web interface I guess.

**Comment by skjnldsv** [comment]
Ah, it seems the webalso needs a fix, I thought we fixed it :thinking:

**Comment by f0k** [comment]
> We usually add an etag to the preview fetch. At least the web interface does. So it does fetch the new preview when the file changes.

The etag will not help here: Because of the `max-age=86400`, the client will not ask the server about the preview image for 24 hours. Only when the cached version is older than 24 hours (i.e., it is *stale*), it will send a conditional request to the server with the cached modification time and etag and then either only get a 304 not modified header (when the file has not changed), or a 200 response with the new preview image. If this is unintended, then the `cacheFor` call [cited above](https://github.com/nextcloud/server/issues/44630#issuecomment-2118028023) should get a much shorter max-age, or no max-age should be set at all.

**Comment by susnux** [comment]
> no max-age should be set at all

This is very bad and can lead to very high load of your webserver if you load a directory with a lot of images and navigation fast (and you have a large user base).

Instead we can use some kind of tag on the url like `preview.png?etag=xxxx` so the is a cache buster if the file changed.
