### ISSUE TITLE
[Bug]: Files navigation shares submenu entries not indented

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#44638]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![image](https://github.com/nextcloud/server/assets/925062/606b9aef-b986-4e61-9f01-53bbb2988f5c)

### Steps to reproduce

1. Open the "Shares" menu in the left navigation
2. See that the entries are not indented

### Expected behavior

Entries should be indented as before.

### Installation method

None

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by skjnldsv** [comment]
Wasn't that changed on purpose? :sweat_smile: 
I swear I saw a PR doing that specifically :thinking:

**Comment by SystemKeeper** [comment]
https://github.com/user-attachments/assets/c5318e49-ddaf-42ef-85db-bd7a0ca8abfc

Seems it is indented when you freshly load the page and then gets pushed to the left again.

**Comment by SystemKeeper** [comment]
I just noticed, this is only happening when the calendar app is enabled, it works correctly if not. The styles leak from 

https://github.com/nextcloud/calendar/blob/a8a23fdfb776e3b59eb2decb8af2bdf53a07b9a5/css/app-navigation.scss#L150

If calendar is disabled it looks correct:

<img width="298" alt="image" src="https://github.com/user-attachments/assets/9b8d181c-089d-4668-aea7-f3a659047a6f">


CC: @st3iny I think?
