### ISSUE TITLE
[Bug] i18n : wrong french label for leaving share

### ISSUE THREAD

**Issue by thopico** [nextcloud/server#44648]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi,

with last update (28.0.4), an error has been introduced. The label for leaving share has been replaced by one with opposite semantics. See screenshot

thank you :)

![image](https://github.com/nextcloud/server/assets/56619719/26e3d846-495f-4a41-913c-edb5f92206b4)

### Steps to reproduce

1. Share item with a user
2.try to leave the share after logging in as this other user

### Expected behavior

Label should be «Quitter ce partage»

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
Already fixed (next minor release).
![image](https://github.com/nextcloud/server/assets/12234510/5bfcb55e-9e8f-4e2f-b949-402dd94d4c73)
