### ISSUE TITLE
[Bug]: Can't share folders/files from webui, infinite load

### ISSUE THREAD

**Issue by dvdsnchzIT** [nextcloud/server#44646]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since I upgrade from 27.1.8 to 28.0.4, I can't share from webui, but it works from dolphin on kde plasma or apple finder with nextcloud desktop client.

On the webui, it keeps loading, nothing to see in the logs and nextcloud.log related.

I saw #42200 #42313 and #42650 but nothing changed trying differents options...

### Steps to reproduce

1. Go in the file app
2. Create a new folder/file, click on the "Person+" to open the share panel
3. Loop always loading

### Expected behavior

We should see the sharing menu

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.irsamc.ups-tlse.fr"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.4.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "ldapIgnoreNamingRules": false,
        "loglevel": 0,
        "theme": "",
        "maintenance": false,
        "maintenance_window_start": 4,
        "default_phone_region": "FR",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir ",
        "share_folder": "\/Shared",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "session_lifetime": 86400,
        "trashbin_retention_obligation": "auto",
        "updatechecker": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "sendmail",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "overwrite.cli.url": "https:\/\/cloud.irsamc.ups-tlse.fr",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "mail_smtpport": "587",
        "mail_sendmailmode": "smtp",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 1.5
        }
    }
}
```

### List of activated Apps

```shell
Enabled:
  - bookmarks: 13.1.3
  - bruteforcesettings: 2.8.0
  - calendar: 4.6.7
  - circles: 28.0.0
  - cloud_federation_api: 1.11.0
  - contacts: 5.5.3
  - dashboard: 7.8.0
  - dav: 1.29.1
  - drawio: 3.0.2
  - federatedfilesharing: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - forms: 4.1.1
  - groupfolders: 16.0.6
  - guests: 3.0.1
  - keeweb: 0.6.17
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - polls: 7.0.2
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - quota_warning: 1.19.0
  - registration: 2.4.0
  - related_resources: 1.3.0
  - richdocuments: 8.3.3
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - spreed: 18.0.5
  - support: 1.11.1
  - survey_client: 1.16.0
  - tasks: 0.15.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - activity: 2.20.0 (installed 2.20.0)
  - admin_audit: 1.18.0
  - comments: 1.18.0 (installed 0.2)
  - contactsinteraction: 1.9.0 (installed 1.9.0)
  - encryption: 2.16.0
  - federation: 1.18.0 (installed 0.0.4)
  - files_downloadactivity: 1.16.0 (installed 1.16.0)
  - files_external: 1.20.0
  - files_markdown: 2.4.1 (installed 2.4.1)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - firstrunwizard: 2.17.0 (installed 1.1)
  - recommendations: 2.0.0 (installed 2.0.0)
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0 (installed 0.2)
  - twofactor_totp: 10.0.0-beta.2
  - user_ldap: 1.19.0 (installed 0.5.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Nothing in data/nextcloud.log

I just have this in apache logs :

computer_ip - - [04/Apr/2024:10:02:50 +0200] "PROPFIND /remote.php/dav/files/dsanchez/20240402_test HTTP/1.1" 207 1603 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:124.0) Gecko/20100101 Firefox/124.0"
```

**Comment by joshtrichards** [comment]
And the Network tab?

**Comment by dvdsnchzIT** [comment]
The network tab :
![image](https://github.com/nextcloud/server/assets/75989144/87a81ea1-3067-4741-8c46-27abfb2981cb)

The admin/overview :
![image](https://github.com/nextcloud/server/assets/75989144/05a06373-62a8-490e-8bff-0f439a5f076d)

The log section :
![image](https://github.com/nextcloud/server/assets/75989144/62a369aa-8725-42ee-8fd1-669abbfa3679)
![image](https://github.com/nextcloud/server/assets/75989144/5d9cd18d-b68e-455b-8d03-644937bdeed6)

Errors not related to sharing a file or folder

**Comment by joshtrichards** [comment]
I'm not seeing the same problem under any test conditions so far.

What browser and browser version is this, specifically?

**Comment by bitfinity-nl** [comment]
Got exactly the same issues and errors, can't find the problem.

**Comment by DE-AI** [comment]
Same problem here with the exact same error messages like as [dvdsnchzIT](https://github.com/dvdsnchzIT)  has.
I already got problems with mimetypes after update because of missing mimetypes from the installed DrawIO app. After restoring the mimetypelist.js I got the hash issues solved, but after installing DrawIO the hash values are again wrong. 
```
 - INVALID_HASH:
    - core/js/mimetypelist.js:
      - expected: 550ab566d30693bfa24ec4b15d9df87731ae8a3be8f79dabf94757e5b8b20eec6e4b678f17af1718297f2872f6b04519eeb024d1dff11947f29da431c7f11201
      - current: 301654cbbe168b8723530db88fd2e40ad688f4e6b0bdaeade5b4fe34bd94d9d3cfe760821e97dc792e585d4b6ccff838597bfd46466bb07d30ff84df4cb79518
```
I guess this is unrelated to the issue here, just wanted to mention it because OC.MimeTypeList undefined sounds like it's related

**Comment by joshtrichards** [comment]
Does this remedy it?

`occ maintenance:repair`

Possibly also:

`occ maintenance:update-js`

If so, how precisely did you deploy the update and run the upgrader?

**Comment by dvdsnchzIT** [comment]
> Does this remedy it?
> 
> `occ maintenance:repair`
> 
> Possibly also:
> 
> `occ maintenance:mimetype:update-js` the correct arg
> 
> If so, how precisely did you deploy the update and run the upgrader?

Both commands change nothing here.

I deploy the upgrade and run the upgrader through my web client (firefox)

**Comment by pyte1** [comment]
I am affected by the same issue with one of my nextcloud instances. I see these errors in the console

```
TypeError: OC.MimeType is undefined
Error while loading the file data TypeError: this.$el.querySelector(...) is null
[ERROR] files: Error while opening sidebar
```

I don't know what causes this as the upgrade process and installed apps are the same across multiple installations, but not all are affected.

Version: Nextcloud Hub 7 (28.0.4)

**Comment by dvdsnchzIT** [comment]
It works again here, after I updated ```Talk``` and ```Nextcloud Office```, sorry I didn't test one by one :-/

**Comment by bitfinity-nl** [comment]
Thats's dumb! Updating all the apps (also talk) fixed my issue with the sharing tab in the webgui.

**Comment by pyte1** [comment]
I've tried updating all the apps and repair aswell but still the sharing does not work. However the errors in the console are different:

![grafik](https://github.com/nextcloud/server/assets/97283710/1a038c94-a73d-4f36-8798-3bf5fe3b3499)

**Comment by dvdsnchzIT** [comment]
> Everyone tried with the latest update please? 28.0.6 and 29.0.1 ?

My instance is fine on 28.0.6

**Comment by skjnldsv** [comment]
@dvdsnchzIT so you're still experiencing the issue?
If so, I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by dvdsnchzIT** [comment]
> @dvdsnchzIT so you're still experiencing the issue? If so, I will need your browser console log to investigate this issue. Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.
> How to access your browser console (Click to expand)

No it's resolved since I update Talk and Nextcloud office on april 12th : https://github.com/nextcloud/server/issues/44646#issuecomment-2052517687

**Comment by skjnldsv** [comment]
Alright, since the issue that @pyte1 mentionned is slightly different and also fixed, I'll close!
Thank you all for the help and report :hugs:

**Comment by dathbe** [comment]
> I've tried updating all the apps and repair aswell but still the sharing does not work. However the errors in the console are different:
> 
> ![grafik](https://private-user-images.githubusercontent.com/97283710/323241546-1a038c94-a73d-4f36-8798-3bf5fe3b3499.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NzUwMTIsIm5iZiI6MTcxNzc3NDcxMiwicGF0aCI6Ii85NzI4MzcxMC8zMjMyNDE1NDYtMWEwMzhjOTQtYTczZC00ZjM2LTg3OTgtM2JmNWZlM2IzNDk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDE1MzgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkYjRkOTQ3NzM3MjFmYjQyODk1OWM3NmM2OTE4ZWY3ZTYyNGQ2M2Y0ZjVmOWVhOTYwY2JkZWQ4MzQzNWU5NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S2VOkjvXCfePb68Qld-usW1mzCILrDibmBR_Cl8l85s)

I'm getting this same error as @pyte1.  Did you find a solution?
I opened a new issue, but thought maybe some who are watching this thread my have a solution.
