### ISSUE TITLE
[Bug]: Missing option to set share_folder in the configuration UI

### ISSUE THREAD

**Issue by galandilias** [nextcloud/server#44667]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I wanted to change the folder for default shares but I noticed there is no option for that in the UI. I do have such entry in oc_parameters table for my user - so I believe it was available in the past. I am aware that I am able to set the default in the config.php however this is not 'per user' option, which is not what I am looking for.

### Steps to reproduce

1. Go to the settings
2. Look for the option to configure shares
3. -> there is no option like this...

### Expected behavior

What I would appreciate is:
1. To have default shares already set in the configuration to dedicated folder (system folder with localization included - I see number of tickets where users are creating their share_folder with local name - that could be done on the side of the Nextcloud i.e. system name = 'shared-with-me' with automated localized labels i.e. 'Shared with me' for English
2. To have option in the User configuration UI to change this folder to the user preference.

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Good catch!

The option is supposed to be there under *Personal settings -> Sharing*. 

The code is still in place. Not sure where it went. Will look into it.
