### ISSUE TITLE
Can't reset password via email address (instead of username)

### ISSUE THREAD

**Issue by detm54** [nextcloud/server#4466]
### Steps to reproduce
1. Try to login with email address and wrong password
2. Click the "Wrong password. Reset it?" message
3. Error message appears: "Couldn't send reset email. Please make sure your username is correct."

### Expected behaviour
Send a reset password mail if there is an existing user with that specific email address.

### Actual behaviour
No mails are being sent because the controller only checks the UIDs, not the email addresses.

This is confusing for users/customers as they are allowed to login with either their username or email address but if they lose their passwords, they are only allowed to reset it via the UID.

### LostController.php

Okay, I'm cutting out the rest of the issue template here because it is unnecessary. The behaviour I am expecting is currently just not implemented.

Why not extend the **core/Controller/LostController.php** to check for valid email addresses aswell?

Well, theoretically there could be multiple accounts with the same mail address. So I would guess either allow password-reset for unique addresses only, or force them to be unique just like the UID system-wide?

Default:
```
/**
 * @param string $user
 * @throws \Exception
 */
protected function sendEmail($user) {
	if (!$this->userManager->userExists($user)) {
		throw new \Exception($this->l10n->t('Couldn\'t send reset email. Please make sure your username is correct.'));
	}
...
```
Approach:
```
/**
 * @param string $user
 * @throws \Exception
 */
protected function sendEmail($user) {
	if (!$this->userManager->userExists($user)) {
		// $user is actually the users mail address
		$userObjectByMail = $this->userManager->getByEmail($user);
		// allow reset only if mail address is unique
		if (count($userObjectByMail) == 1) {
			$user = array_values($userObjectByMail)[0]->getUID();
		} else {
			throw new \Exception($this->l10n->t('Couldn\'t send reset email. Please make sure your username is correct.'));
		}
	}
...
```
Thanks for feedback

**Comment by MorrisJobke** [comment]
Already fixed in the upcoming Nextcloud 12: #4123
