### ISSUE TITLE
Inconsistency in the Front-end

### ISSUE THREAD

**Issue by RayanBekri** [nextcloud/server#44704]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
while we was working on fixing #44487 & #44488. @jadjoud and I have identified an inconsistency: the menu is built using both Vue.js and jQuery. Despite functioning, this mix is not optimal for the project's long-term health.
**Describe the solution you'd like**
For solving the inconsistency, we suggest fully switching to Vue.js. This move aims to streamline the menu’s development by using a single framework, making it simpler to manage and potentially improving performance.

**Additional context**
here is the menu you can find it in users page
![image](https://github.com/nextcloud/server/assets/130870871/dd89773c-d6a2-4567-a7d6-3e1f14471a36)

**Comment by emoral435** [comment]
Closing
