### ISSUE TITLE
login spinner looks ugly

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#4470]
You only see it for a few seconds but it always disturbs me, look at the screenshot:

![login](https://cloud.githubusercontent.com/assets/1589737/25340234/60500ca4-2905-11e7-8070-4ff5631224a5.png)

You can almost see every individual pixel of the circle, by contrast the logout spinner looks much smoother:

![logout](https://cloud.githubusercontent.com/assets/1589737/25340286/8868c690-2905-11e7-9d6d-78e67bd5f7c9.png)

@nextcloud/designers anything we can do about it?

**Comment by MariusBluem** [comment]
> anything we can do about it?

If not, let's say we remove it completely because we have the "Logging in ..." which descibes the current state ;)

**Comment by MorrisJobke** [comment]
It still uses the old way for icon-loading... let me check if I can fix this.

**Comment by MorrisJobke** [comment]
> It still uses the old way for icon-loading... let me check if I can fix this.

Ah - this is because an input field can have the native CSS one, so it needs to fallback to the gif. Then we would need to do this in a different way or improve the quality of the gif.

**Comment by skjnldsv** [comment]
You can't have a good gif quality! :p 
The solution is pretty simple, apply the loader to a different element and not the input :)

**Comment by jancborchardt** [comment]
I think the easiest solution would be to convert the button from `<input>` to `<a class="button">`. @skjnldsv do you want to check that out?

**Comment by skjnldsv** [comment]
@jancborchardt still no time! :(
Barely have enough time to keep up the notifications and work here. Too much craziness at home and workplace these weeks :(

**Comment by MorrisJobke** [comment]
Fix is in #5972
