### ISSUE TITLE
Remove autosave from LDAP and add a save button

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#4476]
As I did predict last time already our horrible workaround to prevent browsers from entering values into password and username fields is not working.

This is not the first time that it broke, we have https://github.com/owncloud/core/pull/6350, https://github.com/owncloud/core/pull/9575 then also https://github.com/owncloud/core/issues/22091 and some more. Just use the search machine of your preference.

Considering that this breaks all the time and leads to a critical production outage I'm simply overruling @jancborchardt here and saying we need a save button on the LDAP wizard. Breaking because some browsers have now another approach to autofill is absolutely unacceptable. Having to press a single button is acceptable if it prevents critical data loss.

**Comment by MorrisJobke** [comment]
cc @nextcloud/ldap

**Comment by pagaille** [comment]
As and end user I was confronted with this horrible bug that involved many hours of headache. Please remove autosave from this wizard !

**Comment by jancborchardt** [comment]
Ok, let’s do it! :)

**Comment by pagaille** [comment]
Great ! And while we talk about it : the same behaviour shows up for the credential in the external storage module.

**Comment by blizzz** [comment]
I'd just add a save (perhaps reset?) button for the credentials only and keep the rest at is. OK?

**Comment by MorrisJobke** [comment]
> I'd just add a save (and perhaps reset?) button for the credentials only and keep the rest at is. OK?

Makes sense for me.

**Comment by XANi** [comment]
@blizzz we had same issue with autofill and ldap filters so please, make it manual save for all LDAP settings.

Basically someone that didn't logged for a long time logged into admin and it auto-filled old ldap filters and when just changing tabs is required for save you can guess what happened next.

**Comment by blizzz** [comment]
see #5568, feedback appreciated
