### ISSUE TITLE
[Bug]: Nextcloud share folder with users not support Chinese character

### ISSUE THREAD

**Issue by Banqc0621** [nextcloud/server#44764]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Operating system :
OpenEuler21
Web server:
httpd 2.4.43
Database:
mariadb 5.5.68
PHP version:
php7.0.33

I create a chinese folder ,called 舍棉衣外套采购申请单青年美科技,and share with vechie，and it works well .so I login as vechie,first time it works well ,
when I refresh the browser some times，the folder changed as follows ：

![image](https://github.com/nextcloud/server/assets/98104475/fe1b54cc-683a-406d-9dfd-1ba6c6c6305d)
![image](https://github.com/nextcloud/server/assets/98104475/c6a38764-8f88-448e-8549-b7e03e974082)
![image](https://github.com/nextcloud/server/assets/98104475/c6bb1724-9868-43f0-8b5a-5683fc710b60)

At present, I am doing the nextcloud data migration test before, and another nextcloud of the same version shows correct, how to solve this phenomenon? The newly built nexcloud will happen.

If a folder name starting with Chinese is shared with another account, the folder name seen by the other account will be changed to (1) (2). But the shared account folder name is normal.

The nextcloud forum found a problem with the same phenomenon, but no solution, link:https://help.nextcloud.com/t/nextcloud19-0-0-share-folder-with-users-not-support-chinese-character/86769

This problem phenomenon is not regular, some display correct, some display abnormal。
![459aad9f0a3af25d075f2f75c39bc6a](https://github.com/nextcloud/server/assets/98104475/41506856-7f45-46a6-b400-c28a96a09291)

### Steps to reproduce

1.该如何解决
2.该如何解决
3.该如何解决

### Expected behavior

The Chinese opening file of the shared folder can be correctly displayed, and the database table oc_share can be correctly displayed in Chinese.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Other

### PHP engine version

Other

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
1
```

### List of activated Apps

```shell
1
```

### Nextcloud Signing status

```shell
1
```

### Nextcloud Logs

```shell
1
```

### Additional info

1

**Comment by joshtrichards** [comment]
Given that you're running such an old version (v19) it's really hard to say.  In my limited testing in v28 I'm not able to reproduce this behavior.

> At present, I am doing the nextcloud data migration test before, and another nextcloud of the same version shows correct, how to solve this phenomenon?

Well, what's different about the Servers and configurations? Or maybe the migration itself is introducing an unexpected variable?

Ideas:

- compare your configurations
- confirm both servers have the same PHP modules (namely `intl`)
- monitor your browser console and browser Network console to try to see what's happening
- monitor your web server logs to try to see what's happening
- set Nextcloud `loglevel` to `0` to try to see what's happening
- turn on Nextcloud `debug` mode to try to see what's happening

Unfortunately, this here isn't a general support channel. We can only address bugs in currently supported versions. 

For general support you can use the Community Help Forum or make arrangements for Enterprise support (https://nextcloud.com/enterprise).

**Comment by Banqc0621** [comment]
Thank you for your answer. The configurations of the two servers tested were the same. As for the problem of shared folders, I re-built the server locally for testing. I found in the database table oc_share that every time files were shared to other users, the tables of other users were displayed correctly when they were entered and changed to (1) (2) when they were refreshed. The corresponding oc_share table contents are also (1) (2). Would like to ask if I should look up questions from database fields? The tests that you have just re-built locally do not involve migration. Currently in the forum and search Microsoft search found the same phenomenon of the question, but there is no solution.

**Comment by Banqc0621** [comment]
Thank you for your answer. The configurations of the two servers tested were the same. As for the problem of the shared folder, I re-built the server locally for the test. I found in the database table oc_share that every time files were shared to other users, the display of other users' login to the Web side was correct, and when the interface was refreshed, only the shared files beginning with Chinese characters became (1) (2). The corresponding oc_share table contents are also (1) (2). Would like to ask if I should look up questions from database fields? The tests that you have just re-built locally do not involve migration. Currently in the forum and search Microsoft search found the same phenomenon of the question, but there is no solution.

**Comment by Banqc0621** [comment]
For security reasons, the migrated new server uses the same version configuration as the original server httpd, mariadb,php, nextcloud. The original server does not have this problem, but the new server does. 

Then I deployed and built nextcloud on my local computer with the same configuration as the migrated new server, and found that this problem occurred when I built nextcloud on my local computer for many times.

**Comment by Banqc0621** [comment]
> 我是否正确理解此问题仅发生在您的测试服务器上？还是原始服务器也表现出相同的行为？
> 
> 您是如何迁移的？
> 
> > 目前在论坛和搜索Microsoft搜索中发现了同样现象的问题，但目前还没有解决办法。
> 
> 在Nextcloud的维护版本中？我只看到了引用的 v15 和 v19，它们没有得到维护。

The original v15 server of Nextcloud does not have the problem of abnormal Chinese beginning file. I think it has nothing to do with the version

**Comment by Banqc0621** [comment]
> 我是否正确理解此问题仅发生在您的测试服务器上？还是原始服务器也表现出相同的行为？
> 
> 您是如何迁移的？
> 
> > 目前在论坛和搜索Microsoft搜索中发现了同样现象的问题，但目前还没有解决办法。
> 
> 在Nextcloud的维护版本中？我只看到了引用的 v15 和 v19，它们没有得到维护。

Nextcloud的v15 和 v19，原服务器上搭建的并没有出现共享中文开头文件异常的问题。我想即使是版本的问题，应该也有解决办法，只是目前还没有找到

**Comment by susnux** [comment]
@Banqc0621 I can not reproduce this issue on any **supported** Nextcloud version. Please update to at least Nextcloud 27.

**Comment by Banqc0621** [comment]
It could be a problem with the httpd version, here I found a post with the same problem：

https://central.owncloud.org/t/owncloud10-4-1-share-folder-with-users-not-support-chinese-character/26933
