### ISSUE TITLE
[Bug]: Set reminder: file/folder  Incomple message after set an reminder

### ISSUE THREAD

**Issue by tuxmaster5000** [nextcloud/server#44775]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After setting an reminder for an file, an notification will pop up with an "place holder" instant the file name.
![Notidication](https://github.com/nextcloud/server/assets/837503/2be33af1-f882-445b-8460-5ad6e0bbbd8e)
 

### Steps to reproduce

1. Add an reminder for an file

### Expected behavior

That the notification text will contains the file name itself instant of  "{filename}"

### Installation method

Official All-in-One appliance

### Nextcloud Server version

27

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
See https://github.com/nextcloud/server/issues/44774
```

### List of activated Apps

```shell
See https://github.com/nextcloud/server/issues/44774
```

### Nextcloud Signing status

```shell
See https://github.com/nextcloud/server/issues/44774
```

**Comment by joshtrichards** [comment]
Also fixed these days. :)
