### ISSUE TITLE
[Bug]: French translation error in file app for "leaving this share"

### ISSUE THREAD

**Issue by tarradmac** [nextcloud/server#44780]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In the file app, when I want to leave a share document or folder, the option "Leave this share" is not correctly translate in french.
Is actually "Conserver ce partage" which means the opposite "Keep this share". It should be "Quitter ce partage"
Thanks

### Steps to reproduce

1. right clic on shared document or folder
2. go to last option for leaving the share
3. "Conserver ce partage" should be "Quitter ce partage"

### Expected behavior

Modifying translation

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by susnux** [comment]
Translations are handled on Transifex: https://app.transifex.com/nextcloud/nextcloud/
General informations: https://help.nextcloud.com/t/translation-knowledge-valid-for-the-entire-nextcloud-project-wiki/51550/27

So if you can provide the fixes yourself, I think they are happy to accept them over at transifex

**Comment by tarradmac** [comment]
I saw that someone already correct the translation. I am not regular with transifex.
But now I am.
