### ISSUE TITLE
[Bug]: Sharing files/folder with password - it uses the Nextcloud user password

### ISSUE THREAD

**Issue by psyca** [nextcloud/server#44781]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If i have saved my login informations for the nextcloud website/installation in my browser (firefox) - e.g. user "username" passwort "secret" - and i share a folder or file as link with password protection, nextcloud uses as default my passwort "secret", even if i choose to generate an own password. I have to open the menu for sharing the file again and replace the autofilled password with a new one.

### Steps to reproduce

1. Save your login credentials to your browser
2. Share a file/folder with external link and password protection
3. generate a password
4. after press "save" it uses my login password

### Expected behavior

Use the generated password instead my saved nextcloud login password

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment]
I assume it's the password manger that is prefilling the saved password.

cc @Fenn-CS @susnux

**Comment by susnux** [comment]
Fixed with https://github.com/nextcloud/server/pull/44575

Will be in 29 and 28.0.5
