### ISSUE TITLE
[Bug]: Button to copy the link to access your files via webdav does not work

### ISSUE THREAD

**Issue by linahamila** [nextcloud/server#44796]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The button to copy the WebDAV link in the Files Settings does not work. Clicking on the button does not copy the link, and a "clipboard is not available" message appears at the top right of the webpage.

### Steps to reproduce

1.Navigate to Files in the top bar.
2.Access Files Settings/WebDAV.
3.Click on the button to copy the link.

### Expected behavior

The link should be copied to the clipboard when clicking on the button.

### Installation method

Community Docker image

### Nextcloud Server version

master

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment]
Hi, please have a look at https://github.com/nextcloud/server/issues/40666
