### ISSUE TITLE
[Bug]: Drag and Drop is not working outside of a small area

### ISSUE THREAD

**Issue by pto199** [nextcloud/server#44793]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I go to drag and drop files, It does not work unless I drag them into a tiny rectangle box at the top of the screen.  I updated from an older versions of nextcloud and I could just drag files into the file list before.  

That small box forces me to scroll up or rearrange my windows that may be covering it before I can upload and is very inconvenient.  I assume this is a bug because it was working properly on my older version of Nextcloud

### Steps to reproduce

1. Drag and drop a file onto the page
2. File wont upload unless dropped into the small rectangle box at the very top of the file list

### Expected behavior

I should be able to drag new files to upload them anywhere within the files.

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Other

### PHP engine version

None

### Web server

Nginx

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

**Comment by wjstone** [comment]
Same issue after installing 28.04 in Ubuntu 22.04

**Comment by jadjoud** [comment]
Hello I tried it and I noticed that you can drop it into an existing folder but you are not anywhere as mentioned above

 
![Untitled video - Made with Clipchamp](https://github.com/nextcloud/server/assets/118366366/d5769057-0971-4b73-b561-2aede2a796d6)

**Comment by solracsf** [comment]
AFAIK, this is not a bug and it is **intended** _(yet I understand that the previous behaviour was better)_.
Maybe you can confirm this @susnux ?

**Comment by skjnldsv** [comment]
Intended. When you have a list longer than yours, you cannot reach the bottom to drop, the people will adjust, the same method is used in many competitors :)

**Comment by pto199** [comment]
> Intended. When you have a list longer than yours, you cannot reach the bottom to drop, the people will adjust, the same method is used in many competitors :)

Interesting.  Taking away functionality to be more like competitors.  I'm not sure which competitors either as I just checked One Drive and Google Drive and they both let you drop anywhere.

This is one of those things that happens to all software as time goes on and project managers/devs start to make software changes for changes sake.  Slowly chipping away until eventually the software becomes a bloated mess of a maze that nobody likes.

**Comment by skjnldsv** [comment]
@pto199 feel free to open a Pull request for this?
I'd be happy to assist and help get it merge, but this is not on the todo right now :shrug:
