### ISSUE TITLE
[Bug]: viewing photos via nextcloud files. If I scroll down and open and close a photo, it always brings me back to the top.

### ISSUE THREAD

**Issue by rajmondburgaj** [nextcloud/server#44792]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Everytime I have many photos in a directory, and I scroll down to a certain point and open an image and then close it, the view in the background jumps up and down. Sometimes goes up to the top, and sometimes just scrolls up to a point where my highlighted image section is out of viewpoint.

Same issue has been reported here: [viewing photos via nextcloud files. If I scroll down and open and close a photo, it always brings me back to the top.](https://help.nextcloud.com/t/viewing-photos-via-nextcloud-files-if-i-scroll-down-and-open-and-close-a-photo-it-always-brings-me-back-to-the-top/179960)

But as of now I don't see any work-around. 
This issue was not present in v27, but it's a regression in v28, most likely when the main view was rewritten in vujes.

### Steps to reproduce

Create a folder.
Upload many images, around 100 per se.
Scroll down to a point where you think could be the middle of all images.
Open one image and close it accordingly.
Check if the background view jumps up or down.

### Expected behavior

The view should stay in a fixed position when opening any image.

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.0

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "check_data_directory_permissions": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "AT",
        "trusted_domains": [
            "nextcloud.route-home.net",
            "100.126.116.160",
            "192.168.178.41"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.route-home.net",
        "overwritehost": "nextcloud.route-home.net",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "dbtype": "mysql",
        "version": "28.0.4.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": true,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "opcache.memory_consumption": 512,
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "apc.enable_cli": 1,
        "maintenance_window_start": 1
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - announcementcenter: 6.8.1
  - audioplayer: 3.4.1
  - calendar: 4.6.7
  - camerarawpreviews: 0.8.4
  - cloud_federation_api: 1.11.0
  - comments: 1.18.0
  - contacts: 5.5.3
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - nextcloud_announcements: 1.17.0
  - notifications: 2.16.0
  - oauth2: 1.16.3
  - password_policy: 1.18.0
  - photos: 2.4.0
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - richdocuments: 8.3.3
  - richdocumentscode: 23.5.1001
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - support: 1.11.1
  - survey_client: 1.16.0
  - systemtags: 1.18.0
  - tasks: 0.15.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_backupcodes: 1.17.0
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - workflow_pdf_converter: 1.13.0
  - workflowengine: 2.10.0
Disabled:
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - circles: 28.0.0 (installed 28.0.0)
  - deck: 1.12.2 (installed 1.12.2)
  - encryption: 2.16.0
  - files_external: 1.20.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - mail: 3.5.8 (installed 3.5.8)
  - notes: 4.9.4 (installed 4.9.4)
  - spreed: 18.0.6 (installed 18.0.6)
  - suspicious_login: 6.0.0
  - twofactor_totp: 10.0.0-beta.2
  - unsplash: 2.2.1 (installed 2.2.1)
  - user_ldap: 1.19.0
  - weather_status: 1.8.0 (installed 1.7.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by eastoid** [comment]
working temporary fix provided by @qibao07

comment out `this.scrollToFile(t,!1)` inside `/nextcoud_data/dist/files-main.js`

**Comment by joshtrichards** [comment]
Fixed in #48632

**Comment by fmalfatto** [comment]
I see that this bug  is been fixed so I would like to use the temporary fix from qibao07. Could someone help me showing how to edit in linux such .js file? It looks like compressed, so I fear to damage it with vi editing.
BTW I found it in /nextcloud/dist/ , not in /nextclod_data/dist/ that is non-exixtstent folder.
TY

**Comment by joshtrichards** [comment]
It'll be in the official release in a couple days: https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

> Could someone help me showing how to edit in linux such .js file? 

Please use the help forum for these types of queries (https://help.nextcloud.com). This channel is for development. Thanks!

**Comment by eastoid** [comment]
> I see that this bug is been fixed so I would like to use the temporary fix from qibao07. Could someone help me showing how to edit in linux such .js file? It looks like compressed, so I fear to damage it with vi editing. BTW I found it in /nextcloud/dist/ , not in /nextclod_data/dist/ that is non-exixtstent folder. TY


you need to find the `files-main.js` file, and open it with nano. then you can search (i believe ctrl+W) and put `this.scrollToFile(t,!1)` in, then delete the piece of text. make sure not to corrupt the JS syntax, only delete that text and a semicolon if there is one directly behind the text. save with ctrl+X. 
or just wait and update nextcloud to the new version.
