### ISSUE TITLE
Nextcloud and his problems are not solved.

### ISSUE THREAD

**Issue by ivandebian** [nextcloud/server#4480]
HI guys.

From maybe 1 month i install on clean nextcloud the latest version 11.0.2 and it was working, but strange things happends. First nextcloud and every linux person who write manual for linux don't explain it correctly. First nextcloud has doc.nextcloud.com where if you start read you can lost your life in reading in not understand, nextcloud write and write... " nextcloud - this is missing " WHat is missing ? how  to install this missing ... I have lost 1 month in looking and i tell you peoples if you want to lost your life install linux, if you want to have much free time in life install microsoft applications. microsoft is robber they robber the money but they make software that only click and install.
Now linux, has to compile, how to make and after that it don't work, i cant tell you too, the first time they comment linux is more stable and what you compile will work in other computers every thing in linux is LIE, i follow linuxfromscratch to install a up to date linux, and from 2 weeks i install it, there they comment good in the beginning and after that in the final they just stop explain and comment if you want to make modify read there, if you want to put and modifiy this and etc.... and where is the explain. So i just follow and linux form scratch start and comment it can't mount the root, from 2 weeks lost my time, reading and reading how to have linux up to date. Today there was new update 11.0.3 and what happend when i open my login nextcloud, put my passowrd it wait 1 minute or more minute to log in in nextcloud, after that when i try yo make nextcloud in android to work it comment that server timeout, and i see dav user... error this dav user error is from years in nextcloud and they don't repair the error, i read and read and no solution for dav user error, include there was some false solution to enter in /etc/var/www/nextlocud,3dparty/dev/... and go to server.php and then in line 494 to 496 to uncomment it, i try it and it don't work then again i restore the original server.php, today with the new version 11.0.3 the dev user error again don't work. THe more extrange is that nextcloud android only work in 4G mobile internet, if im in home it comment server timeout, i will not comment on what server im becouse the linux is OUTDATED in this linux, i like to install http2 and latest source but ubuntu has leaks of humankind data. Linus i can't see why you lost that the women destroy the linux, ubuntu, arch, fedora, red hat, debian, ubuntu is the latest version but it fail, debian has 8.7 and has outdated software, red hat the newest version, fedora... i have 20 windows opens and linux run slow and my computer is heavy, 8 gb .ram nvidia do i need to continue, i will continue, my linux is clean i delete, formate, chkdisk, fsck, check hard disk errors and install linux and what has happend open 20 windows it start work slow, i has windows 7 and i has 40 windows open and it work fast and 2 gb. ram of open windows. Now im thinkig to delete nextcloud from my server, nextcloud are the same broken, 3dparty dev, it is not app in nextcloud to update or change, it is 3dparty dev, dev come from nextcloud and nextcloud it don't repair the problem with the dav user problem or autentication, i has nextcloud news, nextcloud contacts and they all fail after 11.0.3 and when i switch in wifi. Now nextcloud don't has simple how to install nextcloud. nextcloud write on the humans they be protected what to install on ubuntu/debian, what they need to have everyrhing in fedora, in red hat, arch and etc. if the humans has linux that they can't update to the latest php 7 then make legacy to has the php 5, ubuntu is good but has humankind leaks information, nextcloud explain install mcrypt and how to install in ubuntu, i try install aptitude mcrypt and it comment mcrypt don't exist, i try install php5-mcrypt and it comment it don't exist, i try other php modules and it comment they don't exist. what is this. Now when i want to upload things on my linux server with nextcloud it simply upload all the directory, and i remember yestarday i upload 160 gb. and it fail, i put 2 gb. on upload, but why there is no unlimited upload. And other yestarday i see that owncloud has more applications than nextcloud and what i see is that nextcloud is the same as owncloud, pfuuu 
 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Bullnados** [comment]
best troll post since long time

**Comment by ivandebian** [comment]
best troll post since long time This is insult. In my defend i will say Bullnados YOUR FATHER is the best troll post since long time
Bullnados YOUR FATHER is the best troll post since long time
women start respect the men.

**Comment by Bullnados** [comment]
In other post u thin 1tb is 100000GB^^
So your are you shure u have enough computer basics to drive a server?

**Comment by LukasReschke** [comment]
This seems more suited for our forums: help.nextcloud.com
