### ISSUE TITLE
Can't enable apps after upgrade from 11.0.2.7 to 11.0.3.2 **Chrome only**

### ISSUE THREAD

**Issue by jteib** [nextcloud/server#4482]
### Steps to reproduce
1. In Chrome, Click on Admin>apps
2. Find an app that's disabled, or disable an enabled one.
3. Click "enable" to attempt to enable

### Expected behaviour

The app should enable and have a green outline saying "enabled"

### Actual behaviour

Error: this app cannot be enabled because it makes the server unstable

Message only shows up in Chrome as far as I know of.  Workaround: Use different browser to re-enable apps after upgrade if using Chrome.

### Server configuration

**Operating system**:

Ubuntu 16.10 x64

**Web server:**

Apache 2.4

**Database:**

Mysql 5.7 w/ MariaDB 

**PHP version:**

7.0

**Nextcloud version:** (see Nextcloud admin page)

11.0.3.2

**Updated from an older Nextcloud/ownCloud or fresh install:**

11.0.2.7

Apps:
Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - calendar
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_reader
  - files_retention
  - files_versions
  - keeweb
  - news
  - notes
  - user_external
  - user_ldap
  - user_saml
root@plex:/var/www/jamescloud#

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "htaccess.RewriteBase": "\/",
        "htaccess.IgnoreFrontController": true,
        "updatechecker": false,
        "instanceid": "ocjvf4iww3in",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/hdd",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "11.0.3.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "America\/New_York",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "loglevel": "2",
        "logfile": "\/hdd\/***REMOVED SENSITIVE VALUE***.log",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No

### Client configuration
**Browser:**

Chrome

**Operating system:**

Windows 10

**Comment by ivandebian** [comment]
one more person, nextcloud just broke my server. before 1 month maybe i had nextcloud installed and when i start investigate i see that nextcloud had much unresolved problems and one of them is dav user, other problem is when sync from android nextcloud in wifi it don't work it comment dav user or is misconfigured, the other is nextcloud don't want to make resume on upload, don't sync all files, upload only the new. nextcloud imagine you put 1 tb. of data and now you connect from 30 gb. hard disk when you start nextcloud windows client it is gonna sync all 1 tb. shits on your small 30 gb. hard disk. nextcloud do you know compare 1 tb. " 100000 gb. maybe " with 30 gb. and if you need to sync android calendar you need to install davdroid, if you need to sync files need to install nextcloud client, if you need to sync sms you need to install nextcloud sms and etc. google is bad, but they has one program for all, sync everything, and when google sync everything it don't download the 1 tb. 1000000 gb. on your 64 gb. hard disk mobile phone, it only accept the files that you want to sync and when you want to download you just go to google drive and download it. i have fear to use nextcloud.

**Comment by jteib** [comment]
Edit:  Seems to be an issue with handling php over reverse proxy, as direct connection still works fine.  Closing this out as the issue is only related to myself.  Adding websocket support for nginx vhost seemed to help:

 # WebSocket support (nginx 1.4)
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "upgrade";

Also, when attempting to configure nginx to serve static files, although unsucessful, when I switched my configuration back this issue went away.  I am not really sure what fixed it, nor how to recreate this issue yet.  Although I am closing this, if anyone has any feedback, please PM me on the issue as I would like to know exactly what happened here.
