### ISSUE TITLE
[Bug]: Federated file sharing plugin for Files app needs to be adjusted to the changes in Nextcloud 28

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#44824]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The federated file sharing plugin for Files app does the following things:
- Show a dialog to accept or decline pending remote shares if the Notifications app is disabled
- Reload the file list when a pending remote share is accepted (either from the mentioned dialog or from a notification)
- Add a remote public share if only _host_ rather than _user@host_ is set in _Add to your Nextcloud_ in the public share page

The plugin [is loaded using `OC.Plugins.register('OCA.Files.App', ...)`](https://github.com/nextcloud/server/blob/3b94da9c1d9869db35cf8b33da82119d93c1402f/apps/federatedfilesharing/js/external.js#L173), which requires `OC.Plugins.attach('OCA.Files.App', ...)` to be run in the Files app. However, it seems that after the Files app was moved to Vue the plugins are no longer attached ([the legacy code is still there](https://github.com/nextcloud/server/blob/262c84adfac3067af78a9c2907d83082bbab6355/apps/files/js/app.js#L138), but it is not run), so the federated file sharing plugin is never loaded. Unfortunately I did not find what is the current way to attach plugins to the Files app, so I can not fix it myself.

If that fix requires moving the code from the current raw JavaScript code to a built one with Webpack or something like that to be able to import other libraries it may be a good idea to also change from the [legacy listener](https://github.com/nextcloud/server/blob/3b94da9c1d9869db35cf8b33da82119d93c1402f/apps/federatedfilesharing/js/external.js#L86)s for notification actions [emitted on the body element](https://github.com/nextcloud/notifications/blob/c587c09d6186069e183decf9bdb13b6fb3ba4eab/src/Components/Action.vue#L130) to [the new one based on Nextcloud event bus](https://github.com/nextcloud/notifications/blob/c587c09d6186069e183decf9bdb13b6fb3ba4eab/src/Components/Action.vue#L127).

Independently of that reloading the file list may also need to be fixed, as `fileList.reload()` does not seem to be available in the new Files app.

Finally, [the condition](https://github.com/nextcloud/server/blob/3b94da9c1d9869db35cf8b33da82119d93c1402f/apps/federatedfilesharing/js/external.js#L81) to show the dialog to accept or decline pending remote shares if the Notifications app is disabled also needs to be fixed; this is unrelated to the changes in Nextcloud 28, and [there is a pull request to fix it in Nextcloud 27](https://github.com/nextcloud/server/pull/44823), but it would not make sense to fix it in Nextcloud 28 and later until loading the plugin is also fixed, as it would have no effect.

### Steps to reproduce

- Setup Nextcloud server A
- Setup Nextcloud server B
- Disable notifications app in server B
- In server A, share a file with user X of server B
- In server B, log in as user X
- Open the Files app

There is no dialog to accept the remote share

### Expected behavior

There is a dialog to accept the remote share. After accepting the share the file list is reloaded.

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by mickenordin** [comment]
This affects us, federated sharing is a crucial feature for us.
