### ISSUE TITLE
Introduce a notice for instant upload / drag&drop in below file list

### ISSUE THREAD

**Issue by eppfel** [nextcloud/server#4483]
As discussed in #4273 we want to break down @Espina2  ideas into smaller improvements. I propose to introduce the notice for drag & drop in the whitespace below the files. This is in particular helpful in public sharing / to non-nextcloud users.

Here is a quick sketch:
![files-drag drop](https://cloud.githubusercontent.com/assets/1899308/25372192/992a0388-2994-11e7-8518-29d9c6efd69b.png)

If the file list takes the whole height, the info could move directly above the first file as in @Espina2 proposal.

@nextcloud/designers

**Comment by Espina2** [comment]
@eppfel This will break as soon as you more projects or a smaller resolution.

**Comment by MorrisJobke** [comment]
I would also say, that it should be on the top and you should be able to remove it (setting a cookie for external users and a setting for internal ones). Just 2 rows at the top that say the same.

**Comment by jancborchardt** [comment]
Yup, agree with @MorrisJobke that it should be on the top of the file list, maximum 2 rows height, and with an x-Close button. Great work! :)

**Comment by jancborchardt** [comment]
@Espina2 as @eppfel said above:

> If the file list takes the whole height, the info could move directly above the first file as in @Espina2 proposal.

I do agree though that it should be on the top of the file list, maximum 2 rows height, and with an x-Close button. Then it’s always in the same place and doesn’t depend on the size of the view.

Great work! :)

**Comment by Espina2** [comment]
Also agree with the close button.

**Comment by jancborchardt** [comment]
As @eppfel suggested in https://github.com/nextcloud/server/issues/4011#issuecomment-301176358 we should do this as the first row of the files view, combined with the Upload function. (That is, clicking on it will open the dropdown with the filetypes.)

Wording could be:

> Choose files to upload or drag & drop

Maybe a bit shorter, but also we should include that you can create folders via that function. Maybe it even makes sense to directly show the most important functions like Upload file, New folder, and then a 3-dot menu for the rest? (Text files and Collabora filetypes)

**Comment by Espina2** [comment]
@jancborchardt 

> Upload file, New folder, and then a 3-dot menu for the rest?

Please don't do that, one of the problems that the actual UI have is **important** stuff hide on the three dots.

**Comment by jancborchardt** [comment]
@Espina2 if everything is important, nothing is important. There has to be some prioritization. And we have adding options for Spreadsheets, Documents, Presentation etc - no way we show that all in the UI without it being cluttered.

**Comment by skjnldsv** [comment]
Should the close button move it at the end of the file list?
Should we memorise the setting so if we refresh the drop is still gone?
There was an app by @rullzer and @tobiasKaminsky   where the drop was in the left sidebar. https://github.com/rullzer/dropit

Since dropping on low screen is anyway almost impossible, we could either:
1. Only have a drop on the left bottom (above the settings)
2. Have it above the file list and move it in the sidebar on close

**Comment by rullzer** [comment]
@skjnldsv there is no drop on the left in dropit. There is just the link to it there ;)

**Comment by skjnldsv** [comment]
@rullzer oh? I misunderstood, I thought you added a drop zone :)

**Comment by rullzer** [comment]
Yeah that was the plan. But my js fu failed me

**Comment by MorrisJobke** [comment]
This is also more about dropping in the current folder. You can also drop onto the files list: if it is a folder it is highlighted and you drop into it or if it is a file it will highlight the whole file list (IIRC) and then uploads in the current folder

**Comment by MorrisJobke** [comment]
Also the setting should be remembered- one per user - and the notice is then completely gone and not I. The bottom, or?

**Comment by skjnldsv** [comment]
To my view, the drop zone should not be gone completely. If the user closes it, we should ensure that if he wants it back, he should do it without too much difficulties :)
Nonetheless, couldn't we just set the whole blank area at the bottom as a drop zone?

**Comment by MorrisJobke** [comment]
> Nonetheless, couldn't we just set the whole blank area at the bottom as a drop zone?

But the whole app content (not the sidebars) is already a drop zone 🤔 What do you want to add here? This ticket is only about a little help text to make it more obvious.

**Comment by skjnldsv** [comment]
> What do you want to add here?

Just a more obvious text/div/whatever to be more explicit :)
