### ISSUE TITLE
[Bug]: Hash in filename (e.g. #foo.docx) breaks web interface download

### ISSUE THREAD

**Issue by wolfgang-braun** [nextcloud/server#44855]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Downloading a file that has a hash in the name doesn't work anymore when clicking on the file row.
Context menu / 3 dot menu -> download still works

### Steps to reproduce

1. Upload file `#foo.docx`
2. Click on file row to open it (in this case download it as file)
3. A file with the correct name is downloaded. It's corrupt because it has the following content:

> This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client

This is because the UI tries to download the folder, not the file.
This might be because it ignores everything in the URL that comes after `#` 

Note: This behavior can't be reproduced for PDFs when the PDF viewer is active.

### Expected behavior

1. Upload file '#foo.docx'
2. Click on file row to open (in this case download) it
3. A file with the correct name is downloaded. It's a copy of the uploaded file.

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by SubZero84** [comment]
Same when folder has # in name.

**Comment by SubZero84** [comment]
<img width="512" alt="image" src="https://github.com/nextcloud/server/assets/30059550/77953411-9f3e-444d-85c6-d54bb15e7d6a">
![image](https://github.com/nextcloud/server/assets/30059550/bb823f80-481a-4f86-8863-0eb25a901243)

**Comment by susnux** [comment]
Work around: Use the action (tree dot menu and then the "download" entry)
