### ISSUE TITLE
[Bug]: CSP for script-src with nonce on Yandex.Browser

### ISSUE THREAD

**Issue by alex-83748** [nextcloud/server#44872]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Files in Office Online are not opened in [Yandex.Browser](https://browser.yandex.ru), since it is not listed in the list of browsers with CSP v3 support.
![2024-04-17_10-41_1](https://github.com/nextcloud/server/assets/167289606/471c1ca9-bf62-4779-bdf9-7b96b3088378)

### Steps to reproduce

1. Go to any office files on Nextcloud with Yandex.Browser.
2. We get an error.

### Expected behavior

Please add the user agent to the list of compatible ones.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by susnux** [comment]
Fixed with https://github.com/nextcloud/server/pull/44412
