### ISSUE TITLE
[Bug]: click on a favorite folders shows an empty folder

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/server#44913]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

click on a favorite folders shows an empty folder:
![image](https://github.com/nextcloud/server/assets/87175513/8572160e-22c3-4e96-85da-47930f644880)

upon refresh, content is shown.

### Steps to reproduce

1. click on a folder you've set as favorite
2. the folder you clicked is shown as empty

### Expected behavior

folder content should be displayed at first try, not upon refresh

### Installation method

None

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

c.nc.c

**Comment by jadjoud** [comment]
Hello @maximelehericy 

I've actually reproduced the bug but I get a normal display of the favorite folder
Here's a recording
Please let me know if I'm reproducing it correctly.

![Untitled design](https://github.com/nextcloud/server/assets/118366366/15b4db89-ac89-4f7a-ae60-a8200a4067ad)

**Comment by maximelehericy** [comment]
I can't reproduce anymore. Will close it for now.
