### ISSUE TITLE
Make it easer to host "static" HTML5 apps

### ISSUE THREAD

**Issue by geiseri** [nextcloud/server#4492]
I want to use "draw.io" with nextcloud.  Draw.io [supplies some code to allow you to edit diagrams from WebDAV](https://github.com/jgraph/drawio-webdav).  It is trivial to unpack the source on a WebDAV server and run it.  My problem is with nextcloud.  It requires a lot of bootstrap code just to host a SPA with no backend code.  The simplest thing in my mind would be to allow for a specific folder to be "published" where it will serve that content like a normal static webserver.  I have not gotten it to work properly, but I _think_ I can emulate this behavior via the "remote.php" script, but the code looks messy and doesn't integrate nicely from the nextcloud menu.  Any ideas on this?

**Comment by geiseri** [comment]
I was wrong about remote.php, it sends down the mime-type of text/plain so the browser will not render it.  Maybe another approach would be to make a "kickstart" template that would make it easier for those of us who do not know PHP to wrap single page applications easier.

**Comment by ChristophWurst** [comment]
Take a look at https://docs.nextcloud.com/server/12/developer_manual/app/index.html. I think what you're trying to do should be implemented as a Nextcloud app.

**Comment by geiseri** [comment]
@ChristophWurst I did take a look at the developer's guide.  PHP really is not my strong suite and I am not interested in learning the nextcloud internals.  I do see how to work the REST api and am very comfortable with JS/HTML5 based single page apps though.  I will give it a try though since I really want to be able to use it with my nextcloud server :)

**Comment by ChristophWurst** [comment]
All you should need is

1. A template to generate your HTML. There you also add your scripts.
2. A controller with a single method where you return a template reesponse with the template name from 1.
3. A route definition to wire it up.
4. Registration of an app icon.

All these steps are covered by our developer manual and should be fairly easy.

I will close this ticket here because we use GitHub mainly for bug reports and feature requests. If you have further questions, please open a new topic at our forum help.nextcloud.com. Feel free to @mention me there if you need help :-)

**Comment by geiseri** [comment]
I still think this is a valuable feature to have.  Just because there are more and more SPAs appearing every day and the filestore backend of nextcloud provides a nice landing place.  In theory all it would need is to be able to flag a folder as being able to serve static content.  Right?

**Comment by ChristophWurst** [comment]
> In theory all it would need is to be able to flag a folder as being able to serve static content. Right?

Yeah but that is like opening a can of worms. Letting browsers execute files "served" by Nextcloud would potentially result in XSS issues. IMO Nextcloud is not the right software for this use case.
