### ISSUE TITLE
[Bug]: Dynamic Content Load Issue on Scrolling in Files View

### ISSUE THREAD

**Issue by bigcat88** [nextcloud/server#44934]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Upon initial login, the interface appears normal and functional. However, as soon as we start scrolling down, the files and folders begin to disappear and are replaced by empty spaces in the file list view. This issue also affects functionality; it becomes impossible to open folders or interact with the navigation elements on the left side. This problem persists across multiple user sessions and browsers.

**Nextcloud version:** 28.0.4

### Steps to reproduce

1. Login to user which has many folders and shares at the root folder
2. Scroll down in the WebUI

### Expected behavior

Everything should display normally

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

As soon as the first files disappear, see the following errors in the browser console:
```
TypeError: e is undefined
   VueJS 22
   _onScrollHandle VirtualList.vue:185
   onScroll VirtualList.vue:180
   mounted VirtualList.vue:158
   VueJS 18
   setRoot files.ts:49
   T pinia.mjs:1380
   fetchContent FilesList.vue:319
   currentView FilesList.vue:267
   VueJS 4
vue.runtime.esm.js:3065:16
```

Nextcloud is running behind a Cloudflare reverse proxy, in case that is relevant.

**Comment by Pytal** [comment]
This issue is for the files list

Could you fill in the bug report template in a new issue @mmmrein?

**Comment by skjnldsv** [comment]
Fixed in https://github.com/nextcloud/server/pull/45251
