### ISSUE TITLE
[Bug]: Dashboard widgets not showing on ipad server version 28.0.4

### ISSUE THREAD

**Issue by hilltopmediadesign** [nextcloud/server#44946]
[###](url) ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Dashboard widgets not showing on iPad. Main screen is blank. Navigation bar is showing. Working properly on desktop and Android mobile.

Working properly on v28.0.3

iPad OS 16.3.1
Safari Browser
iPad 6th Gen
![IMG_3331](https://github.com/nextcloud/server/assets/659569/f5f9889d-7d77-4b89-b295-c23424f73faa)

### Steps to reproduce

1. View Nextcloud Dashboard on iPad

### Expected behavior

Dashboard widgets appear.

### Installation method

Community Docker image

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "overwriteprotocol": "https",
        "upgrade.disable-web": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx.xxxx.com"
        ],
        "maintenance_window_start": 9,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.4.1",
        "overwrite.cli.url": "https:\/\/xxx.xxxx.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Comment by hilltopmediadesign** [comment]
Confirming this issue is fixed when updating to ipadOS 17 or higher.

**Comment by hilltopmediadesign** [comment]
Here’s the safari js debug for future reference:
[Error] SyntaxError: Invalid regular expression: invalid group specifier name
(anonymous function) (updatenotification-init.js:1)
[Error] SyntaxError: Invalid regular expression: invalid group specifier name
RegExp (core-common.js:2:3485291)
(anonymous function) (core-common.js:2:3485291)
r (core-unified-search.js:2:43840)
(anonymous function) (core-unified-search.js:2:7196)
r (core-unified-search.js:2:43840)
(anonymous function) (core-unified-search.js:2:44137)
(anonymous function) (core-unified-search.js:2:45355)
Global Code (core-unified-search.js:2:45360)
[Error] SyntaxError: Invalid regular expression: invalid group specifier name
RegExp (core-common.js:2:3485291)
(anonymous function) (core-common.js:2:3485291)
o (dashboard-main.js:2:124013)
(anonymous function) (dashboard-main.js:2:1100)
o (dashboard-main.js:2:124013)
(anonymous function) (dashboard-main.js:2:125513)
(anonymous function) (dashboard-main.js:2:124310)
(anonymous function) (dashboard-main.js:2:125527)
Global Code (dashboard-main.js:2:125532)

**Comment by skjnldsv** [comment]
Seems like a safari on iPadOS issue.
Literally all of our apps seems to throw an error from the log you posted.

Considering upgrading fixes it, I'll close that ticket then.

Thanks for the feedback @hilltopmediadesign! If we have more reports of it, we'll re-open :+1:
