### ISSUE TITLE
🪟📁📄 Ability to enforce windows compatible file names on the server

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#44963]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
In some scenarios with a large chunk of the user base being Windows users, using the Desktop client for example sync conflict can get created easily via the web interface, other clients or directly via any client software supporting WebDAV by creating files or folders that cannot be synced down to Windows ever.

**Describe the solution you'd like**
Add a setting to 'enforce windows compatible file names' on the server, so when the user tries to rename/create files/folders that would generate conflict when syncing, the server would prevent the action. This setting should be optional and needs to be turned on explicitly.
Also there is no logic expected to migrate existing data, just to prevent it from the moment on the setting is active.

- [ ] https://github.com/nextcloud/server/issues/40690 should be a stretch goal
- [x] define list invalid characters
- [ ] https://github.com/nextcloud/server/issues/45130

**Describe alternatives you've considered**
None, given the fact that the person creating a file/folder might not be the one being affected by it and the affected person might not have the permissions on the system to change the names, i.e. when shared read-only.

**Comment by tobiasKaminsky** [comment]
Subscribing myself, as I think this is then also a task for clients.
- If server returns a specific error message, clients should show a correct info
- if setting is enabled via capabilities, clients can directly prohibit renaming/creating such a file

**Comment by susnux** [comment]
@tobiasKaminsky we nee this implemented / fixed on the clients, server and webui are already done:
* Desktop: https://github.com/nextcloud/desktop/issues/6447
* Android: https://github.com/nextcloud/android/issues/12576
* iOS: https://github.com/nextcloud/ios/issues/2802

Implementation: Get the capability "forbidden_filename_characters" from the files app. This is an array of forbidden characters (could be multibyte characters, so it is an array of strings). If any of the strings in the array matches the *filename* it is considered invalid.

**Comment by SystemKeeper** [comment]
Besides some characters not allowed on windows,  there are more rules that need to be taken into account, e.g. a Filename is also not allowed to end with a dot or a space. There are also some reserved filenames.
See https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions for details.

**Comment by susnux** [comment]
Yes but having the forbidden characters implemented in clients is a good first step and also allows to configure other compatibility (like with some filesystems that forbid just `:`).

>  See https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions for details.

This is also only partially true, Windows supports a lot of naming things, but the Explorer simply does not, like trailing `.` is working just win32 API needs the `?` flag to disable path normalization (and of course Explorer fails to handle it).
Just like with Mac where some buggy GUI application forbid files with colon in the name, while on OS layer this is pretty fine.

But we probably should still enforce the character + the trailing space / dot rules. About the path length we can not do much, that depends on the users mount point and file type (e.g. for spreadsheets the table name counts into the path length 🤦).

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/blob/8c10c7809950ac1208f65d9949265b3247d08321/config/config.sample.php#L1972-L1983

**Comment by susnux** [comment]
Not only it is not only specific characters but also files and casing, and that list for characters is not complete (missing e.g. char 1-31).

**Comment by skjnldsv** [comment]
> You also can't have a space or a dot at the end of a folder name on Windows.

pretty sure we trim the names on NC side :thinking:

**Comment by AndyScherzinger** [comment]
> pretty sure we trim the names on NC side 🤔

created via "New" in the webUI
<img width="238" alt="2024-05-02 13_54_50-Files - Nextcloud – Mozilla Firefox" src="https://github.com/nextcloud/server/assets/1315170/7aba7e4d-ecaa-4fe4-9d16-8ee6f51f4853">
and also
<img width="144" alt="2024-05-02 13_56_11-Files - Nextcloud – Mozilla Firefox" src="https://github.com/nextcloud/server/assets/1315170/a5bc5d4f-b3e4-49bc-9aaf-c6d83036320a">

**Comment by susnux** [comment]
> pretty sure we trim the names on NC side 🤔

No, spaces are pretty valid on Mac and Linux. But we restrict even on Linux to not include ascii 0-31 (including tab).

**Comment by susnux** [comment]
After discussion with @Altahrim and @come-nc we came to the conclusion the best is to keep the configuration generic but just provide a "preset" for windows.
Meaning we have multiple options to fine tune our file restrictions:
- [x] Forbidden filename characters (already implemented by us)
- [x] Forbidden filenames (already implemented by us)
- [ ] Forbidden filename prefixes (needed for windows due to namespace support)
- [ ] Forbidden filename extensions (optional but makes sense to replace unused filename regex)

**Comment by jancborchardt** [comment]
> No, spaces are pretty valid on Mac and Linux.

@susnux but our client does not seem to sync these correctly? At least had an issue on a macOS device with some folders with trailing spaces not being synced. @tobiasKaminsky @mgallien

**Comment by tobiasKaminsky** [comment]
> > No, spaces are pretty valid on Mac and Linux.
> 
> @susnux but our client does not seem to sync these correctly? At least had an issue on a macOS device with some folders with trailing spaces not being synced. @tobiasKaminsky @mgallien

We discussed this in our planning meeting and I will create a Desktop issue for it.

**Comment by susnux** [comment]
@AndyScherzinger @jancborchardt 

How do we handle this use case:
1. No rules enabled
2. User uploads file that is not compatible but currently allowed
3. Admin enabled Windows support

Now the behavior can be:
1. No access to the files anymore
2. Readonly access with ability to rename
3. Update but not new files with those rules

**Comment by tobiasKaminsky** [comment]
Capabilities:
- provides 4 (above) options with each forbidden characters/patterns

Webdav:
- method: put, mkcol, copy, move
- if wrong character
- http 400 return, with sabre dav exception

OCS:
- find all endpoints, e.g. create new file from template via direct editing (/ocs/v2.php/apps/files/api/v1/directEditing/create)

@susnux checks if exception can be localised via http header 

I can provide a LTD with branch/app, so that we can all have the same state.

**Comment by AndyScherzinger** [comment]
@susnux I would say option (3). Why do you think it is hard? Wouldn't is just mean that while updating an existing file's content  the checks simply won't be executed?

So the checks would be on
* Create
* Move (including rename)

**Comment by susnux** [comment]
Status update:
- [x] The server now provides the capabilities to allow validation on clients
- [x] The server provides a new interface for filename validation that covers all of those points
- [ ] Web UI validates filenames (needs [this PR](https://github.com/nextcloud-libraries/nextcloud-files/pull/1013))
- [ ] Clients validate filenames based on capabilities (TBD?)
- [ ] Migrate all filename validation in server to the new interface
- [ ] Provide UI button to easily fill all config values for Windows support

**Comment by narcisgarcia** [comment]
I think #31663 proposed solutions are better for every scenario.
