### ISSUE TITLE
[Bug]: Events information leaked with shared calendars

### ISSUE THREAD

**Issue by section1** [nextcloud/server#45041]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When you shared a calendar and you have recursive events with option "When share show only busy" if you change a instance of the recurrent event the information of that event is leaked.

### Steps to reproduce

- User B shares the calendar with user C
- User A creates a recursively Event with user B as attendant and choose "When share show only busy"
- User C see that User B has an event an displays as "Busy". works fine
- User A change the time of an instance of the recursively event called "Secret Event"
- User C can see the full event in the shared calendar.

### Expected behavior

Show the event as "busy" and not leak information.

### Installation method

None

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by section1** [comment]
You can see that the instance that is modified(day 11) display the Full information of the event..the others days shows as "busy"


![leaked-event](https://github.com/nextcloud/server/assets/8985108/9fd18ac6-7cf4-4113-9ffb-2bebade8ba3f)

**Comment by kesselb** [comment]
Thanks, please submit your findings to https://hackerone.com/nextcloud/

**Comment by section1** [comment]
> Thanks, please submit your findings to https://hackerone.com/nextcloud/

done

**Comment by section1** [comment]
this is fixed in new versions
