### ISSUE TITLE
Details tab not closing / shows details for previous folder selected when browsing to another location

### ISSUE THREAD

**Issue by kartilana** [nextcloud/server#45061]
**Is your feature request related to a problem? Please describe.**
I don't know if it's a bug or an enhancement to be done. Sometimes employees are sharing the wrong folder using the sharing tab. This can lead to wrong contents to be shared.

Steps to reproduce : 
- Select a folder and click on Details. The Details tab related to the select folder is chown.
- Click on another folder.

Actual Result : The Details tab is still there and shows the previous folder selected.

Expected behaviour : The Details tab closes itself, or the Details tab shows the new selected folder instead.

Nextcloud version : Nextcloud Hub 8 (29.0.0) stable chanel

I hope i made myself clear enough. Many thanks for your job.

**Comment by susnux** [comment]
@nextcloud/designers for UX feedback:

What would you say is the expected behavior when having the sidebar open and navigate to another directory:
1. Sidebar closes
2. Sidebar stays open with old selected file / folder

**Comment by szaimen** [comment]
> 1. Sidebar closes

I'd go with this one :)
