### ISSUE TITLE
Incorrect File Details And Files After Alert

### ISSUE THREAD

**Issue by spit4520** [nextcloud/server#4506]
### Steps to reproduce
1. generate file on NFS or webserver itself. I used find hi / >> logs.txt logs.txt had permissions www-data for the user and group. The file was still owned by the above before during and after the command. 
2. navigate to the directory where the file is located in the web portal
3. either during the command operation or after it has completed click on the logs.txt file. 
4. Dismiss the "too big to display" prompt
5. observe that the size of the file is not less than 1 kb in size. The date on the file is also 47 years off.

### Expected behaviour
Tell us what should happen

I don't know if this is spec, but I expected the file to be persistently updating and even if not to be able to view the file in the browser the file size and date should have been accurate.

### Actual behaviour
Tell us what happens instead

the web front end did not accurately display the size of the file or the data, even when choosing to download the file. The system did not serve up a file to be downloaded. After refreshing the page and the file size being displayed correctly, then the file was accurately downloaded 

### Server configuration

stock other than 1 field added to stock config

filesystem_check_changes => 1

**Operating system**:
below is a list of OS's I checked this against before making this bug to help you expedite the process of patching the bug

ubuntu 16.04.2 LTS
RHEL 7.3
Centos 7.3

**Web server:**
Just Apache I didn't have enough time to check the rest
**Database:**
Mysql 
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
11.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install 
**Where did you install Nextcloud from:**
git clone and install
**Signing status:**
unsigned currently as I am just testing the system before I integrate it into my ecosystem

```
Login as admin user into your Nextcloud and access 
http://example.com/
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- FILE_MISSING
		- .htaccess
		- .user.ini

Raw output
==========
Array
(
    [core] => Array
        (
            [FILE_MISSING] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => 11e2db30f0cf23df1b5aa1cdf329a8c88d253f86e43f9e7af1b30969eb0175030103b138e2f7ab7608c902bbb57a5d578c2c0ca09f3abf2ef83415f4bc6f6e20
                            [current] => 
                        )

                    [.user.ini] => Array
                        (
                            [expected] => 467d4f028c447895716a2b7859ed6e569f8ee34b87b51d73dab2e6a9ca4fbe63172c7be3e365ae864a60408286afcce852dd38ee544b61685ed4ee5e021fecb0
                            [current] => 
                        )

                )

        )

)
```
</details>

**List of activated apps:**
default

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

fresh install non other than stock
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
fresh install non other than stock
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
I am using NFS I will have the system linked with LDAP and I am using AutoFS for logins on machines across the network. I need to set the system up so that the files available through the web browser and the desktop client are updated in real time for when massive log files are generated.

**Are you using encryption:** yes/no
again I am just tesing so SSL is not set up at this time, It would be a waste for just a test
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
currently no but I will be using LDAP
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Chrome, Firefox
**Operating system:**

ubuntu 16.04.2 LTS
RHEL 7.3
Fedora 25
Debian Weezy and Jessie

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
error log empty for apache
```
</details>

#### Nextcloud log (data/nextcloud.log)
<summary>{"reqId":"+M5or80pUYGBQDt1Jo+8","remoteAddr":"173.225.187.186","app":"PHP","message":"file_get_contents(\/var\/www\/html\/nextcloud\/.htaccess): failed to open stream: No such file or directory at \/var\/www\/html\/nextcloud\/lib\/private\/Setup.php#435","level":3,"time":"2017-04-25T10:43:17+00:00","method":"POST","url":"\/nextcloud\/index.php","user":"--","version":"11.0.3.2"}
{"reqId":"CudjtAD5bE7iBYLSmj2+","remoteAddr":"173.225.187.186","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/nextcloud\\\/index.php) cannot be processed by the script '\\\/nextcloud\\\/\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/base.php(962): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Request.php\",\"Line\":723}","level":3,"time":"2017-04-25T10:59:54+00:00","method":"GET","url":"\/nextcloud\/\/index.php","user":"sspitler","version":"11.0.3.2"}
{"reqId":"1qyDj+IX1\/1PJ6+nbyxs","remoteAddr":"173.225.187.186","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/nextcloud\\\/index.php) cannot be processed by the script '\\\/nextcloud\\\/\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/base.php(962): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Request.php\",\"Line\":723}","level":3,"time":"2017-04-25T11:00:10+00:00","method":"GET","url":"\/nextcloud\/\/index.php","user":"--","version":"11.0.3.2"}
{"reqId":"Ni\/\/pPWmybdMRYgCAY1f","remoteAddr":"173.225.187.186","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 405 The resource you tried to create already exists\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\MethodNotAllowed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(590): Sabre\\\\DAV\\\\Server->createCollection('Test', Object(Sabre\\\\DAV\\\\MkCol))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/n...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1157,\"User\":\"sspitler\"}","level":4,"time":"2017-04-25T17:32:30+00:00","method":"MKCOL","url":"\/nextcloud\/remote.php\/webdav\/Test","user":"sspitler","version":"11.0.3.2"} </summary>
</details>

Of all of the configurations for clients and servers. Personally the Ubuntu client and server configuration is the reason I reported this bug. I found this bug because I was trying to display in real time a log file in the web viewer and I found that even after the program that was generating the log has stopped generating the log the bug was still found with that file. Permissions were checked and all was good on the permissions side. If you want to contact me directly I can be reached at scott@novacomputing.org 

Thank you for looking into this

**Comment by MorrisJobke** [comment]
We don't support that files are directly updated on the storage by default. You can enable this in the config.php, but it will come with a bigger performance decrease, because then we can't rely on the DB but need to check the filesystem on every request. Another way would be to use the occ command with the `files:scan` operation after every change to properly propagate the changes.
