### ISSUE TITLE
The individuals who were shared something by email have no avatar even if one in addressbook

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#4507]
I noticed the contacts menu shows the avatar of ppl from the Contacts app but when I share a file with them, their email autocompletes but no avatar shows.

@schiessle maybe it is simple (take the code from @ChristophWurst ) maybe it is hard... ;-)

@nextcloud/designers

**Comment by rullzer** [comment]
Duplicate of https://github.com/nextcloud/server/issues/2514

**Comment by jancborchardt** [comment]
@jospoortvliet thanks for agreeing on a bunch of the issues I opened or commented on. ;D Please weigh in there directly. :)
