### ISSUE TITLE
Check/Uncheck button to install specific recommended app from "/apps/recommended" page

### ISSUE THREAD

**Issue by Rash419** [nextcloud/server#45084]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I just want to install Nextcloud Office from recommended apps but I need to install all of them. I know you can install app from "Apps".  But if we have option to check/uncheck particular apps it would be great 
![image](https://github.com/nextcloud/server/assets/26241069/273c0612-9261-4269-931f-e2ae75983ca9)

**Describe the solution you'd like**
There should be option to check/uncheck for individual recommended apps

**Comment by Rash419** [comment]
I will work on this, Thanks

**Comment by WesleyJammer** [comment]
Hey i am a student that is experiencing open source for the first time, and this issue looks interesting. I am curious if this issue is still open and i can have a look at it?

**Comment by joshtrichards** [comment]
It's still open. @Rash419 - are you still planning to dig into this?

**Comment by Rash419** [comment]
I wanted to check it but @WesleyJammer feel free work on this : )

**Comment by WesleyJammer** [comment]
@Rash419 Thank you verry much for your offering! if i am understanding correctly you want seperate check options for deciding wich of the recommended apps you want to install. @joshtrichards is there mabye more important information for me to know before it start on this issue?

**Comment by Rash419** [comment]
> @Rash419 Thank you verry much for your offering! if i am understanding correctly you want seperate check options for deciding wich of the recommended apps you want to install.
Exactly

**Comment by priyanshu2k3** [comment]
hey i think i have solved this but i am not able to check i have set up the app locally using the docker i am not able to figure out how to check

**Comment by priyanshu2k3** [comment]
is there any kind of group or community chat option for this

**Comment by WesleyJammer** [comment]
> hey i think i have solved this but i am not able to check i have set up the app locally using the docker i am not able to figure out how to check

okey, i was also working on this and i thought the issue was assigned to me?

**Comment by sanskar-soni-9** [comment]
@priyanshu2k3 @WesleyJammer are you still working on this?
