### ISSUE TITLE
[Bug]: Error: Undefined constant Symfony\Component\Console\Input\InputOption::VALUE_NEGATABLE

### ISSUE THREAD

**Issue by Quix0r** [nextcloud/server#45099]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading from 28 to 29, I got this error:
```
$ ./occ app:update --all
An unhandled exception has been thrown:
Error: Undefined constant Symfony\Component\Console\Input\InputOption::VALUE_NEGATABLE in /var/www/.../core/Command/Config/App/SetConfig.php:76
Stack trace:
#0 /var/www/.../apps/sharerenamer/vendor/symfony/console/Command/Command.php(77): OC\Core\Command\Config\App\SetConfig->configure()
#1 /var/www/.../core/Command/Config/App/SetConfig.php(41): Symfony\Component\Console\Command\Command->__construct()
#2 [internal function]: OC\Core\Command\Config\App\SetConfig->__construct()
#3 /var/www/.../lib/private/AppFramework/Utility/SimpleContainer.php(83): ReflectionClass->newInstanceArgs()
#4 /var/www/.../lib/private/AppFramework/Utility/SimpleContainer.php(128): OC\AppFramework\Utility\SimpleContainer->buildClass()
#5 /var/www/.../lib/private/AppFramework/Utility/SimpleContainer.php(146): OC\AppFramework\Utility\SimpleContainer->resolve()
#6 /var/www/.../lib/private/ServerContainer.php(173): OC\AppFramework\Utility\SimpleContainer->query()
#7 /var/www/.../lib/private/AppFramework/Utility/SimpleContainer.php(64): OC\ServerContainer->query()
#8 /var/www/.../lib/public/Server.php(55): OC\AppFramework\Utility\SimpleContainer->get()
#9 /var/www/.../core/register_command.php(96): OCP\Server::get()
#10 /var/www/.../lib/private/Console/Application.php(107): require_once('...')
#11 /var/www/.../console.php(112): OC\Console\Application->loadCommands()
#12 /var/www/.../occ(11): require_once('...')
```
But the constant is there, so it looks like Nextcloud (never done before) has loaded some other Symfony? I have already checked my include paths, there is no other installed.

### Steps to reproduce

1. I just upgraded from 28.0.5 to 29.0.0 release

### Expected behavior

The command should run with no flaws.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

29.0.0

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
See https://github.com/JonathanTreffler/sharerenamer/issues/270#issuecomment-2083716342
