### ISSUE TITLE
[Bug]: File URLs not backwards compatible after upgrade to Nextcloud Hub 7 (28.0.5)

### ISSUE THREAD

**Issue by calebjones** [nextcloud/server#45101]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I have a spreadsheet (ODS) that I have captured receipts in for the last few years. I've put links in that spreadsheet to the images or PDFs of the receipts. These URLs were formatted this way (from prior version - can't remember which version):

`https://[HOST]/index.php/apps/files/files?dir=/[DIR]&openfile=[FILEID]`

Since updating to Nextcloud Hub 7 (28.0.5), file URLs are formatted this way:

`https://[HOST]/index.php/apps/files/files/[FILEID]?dir=[DIR]&openfile=true`

The former URL no longer works and just opens the directory. The newer URL opens the file specified in the dir parameter.

### Steps to reproduce

1. Copy file URL for file (not share URL, but URL when hovering over file in directory) from older version (prior major version - can't remember which version produces older URL version)
2. Open the URL and note that Nextcloud opens the file.
3. Upgrade to Nextcloud Hub 7 (28.0.5)
4. Repeat step 2 (the same URL created from prior version) but note that it only opens the directory and not the file

### Expected behavior

File URLs from prior versions should open in Nextcloud Hub 7 (28.0.5) - backwards compatibility.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment]
Thanks for your report.

The internal link is backwards-compatible / stable.
Actual URLs used by the frontend probably not.

Example for internal link (you find them in the sharing tab):
`https://[HOST]/index.php/f/[FILEID]`

I don't see an issue here but will forward it to clarify.

**Comment by SystemKeeper** [comment]
If you have the links in a spreadsheet anyway and all your links end with "openfile=<fileid>" you could try to translate them to an internal link:

```
=CONCATENATE("https://[HOST]/index.php/f/", RIGHT(A1,LEN(A1)-SEARCH("openfile=", A1)-8))
```

<img width="1243" alt="image" src="https://github.com/nextcloud/server/assets/1580193/d06bbfe6-e713-424f-8a6f-236b977ed183">

Just quick and dirty, but might work.

**Comment by joshtrichards** [comment]
This has come up a couple times now. If nothing else might suggest an opportunity to clarify the documentation a bit.

**Comment by calebjones** [comment]
From a usability standpoint, when linking to files in a durable way is the recommendation to NOT right-click "Copy Link" when browsing files and hovering over a file? That seemed to be the most straightforward way to do it.

What is the best way to get the internal link?

**Comment by SystemKeeper** [comment]
> What is the best way to get the internal link for users browsing the file UI?

If you open the share tab in the right sidebar, there’s an option to copy „Internal link“

**Comment by blalyasar** [comment]
This problem still on Nextcloud 29.
How can I solve.
When I open excel file after save and turn back url is saved from cache and turn back this folder excel file is auto open .

**Comment by skjnldsv** [comment]
Should be fixed with upcoming release.
Many people had different expectations of the behavior when openfile is set. That led to many complicated discussions.

Thanks for understanding and your patience
