### ISSUE TITLE
Anonymous capabilities

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#4510]
The current capability endpoint is authenticated however it would make sense to also have an unauthenticated capability endpoint for clients that connect for the first time to auto discover endpoints.

Example use case:

1. Mobile client is openend
2. Server url is entered
3. Server is queries
4. The capabilities could tell the client:
 * Some generic server info (maybe the theme name etc)
 * Instance logo to display
 * where to authenticate

@LukasReschke as discussed.

**Comment by LukasReschke** [comment]
- Current timeout for brute-force protection

**Comment by tobiasKaminsky** [comment]
Can we expect this for 12.0.1?
It is important for many android users as the currently have troubles to login due to bruteforce...

**Comment by rullzer** [comment]
@tobiasKaminsky Probably not. it would be a new feature and backporting features is not something we want to do.

**Comment by tobiasKaminsky** [comment]
Ok, then we will use a workaround until the proper fix.

**Comment by rullzer** [comment]
Fixed with #5567
