### ISSUE TITLE
[Bug]: updater always proposes to update to new major release immediately, dispite stable channel

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/server#45111]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Of my five nextcloud instance, one has the odd habit of always wanting to update to a new major release immediately. Right now I see this: the updater proposes 29.0.0, while my other Nextcloud instances don't and instead wait for a few point releases.

![grafik](https://github.com/nextcloud/server/assets/3313208/28e01ac1-e6da-4259-8d7c-783318b65bd0)
 

### Steps to reproduce

I have no steps to reproduce this. For some reason, this one instance behaves differently from the others. I have no idea how to reproduce this, and I cannot seem to affect this behaviour in any way, as the interface already says that it follows the stable channel.

### Expected behavior

Update should follow the same pattern as on my other NC instances.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

27

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.****.org"
        ],
        "onlyoffice": {
            "jwt_header": "****"
        },
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "activity_use_cached_mountpoints": "true",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mysql.utf8mb4": true,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "default_phone_region": "PH",
        "version": "28.0.5.1",
        "overwrite.cli.url": "https:\/\/cloud.iprights.org",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "default_locale": "en_PH",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "587",
        "updater.release.channel": "stable",
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "maintenance_window_start": 22
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.20.0
  - admin_audit: 1.18.0
  - bruteforcesettings: 2.8.0
  - calendar: 4.7.1
  - circles: 28.0.0
  - cloud_federation_api: 1.11.0
  - collectives: 2.10.1
  - comments: 1.18.0
  - contacts: 5.5.3
  - contactsinteraction: 1.9.0
  - dashboard: 7.8.0
  - dav: 1.29.1
  - deck: 1.12.2
  - federatedfilesharing: 1.18.0
  - federation: 1.18.0
  - files: 2.0.0
  - files_fulltextsearch: 28.0.0
  - files_pdfviewer: 2.9.0
  - files_reminders: 1.1.0
  - files_sharing: 1.20.0
  - files_trashbin: 1.18.0
  - files_versions: 1.21.0
  - firstrunwizard: 2.17.0
  - forms: 4.2.3
  - fulltextsearch: 28.0.1
  - fulltextsearch_elasticsearch: 28.0.1
  - impersonate: 1.15.0
  - logreader: 2.13.0
  - lookup_server_connector: 1.16.0
  - mail: 3.6.0
  - nextcloud_announcements: 1.17.0
  - notes: 4.10.0
  - notifications: 2.16.0
  - notify_push: 0.6.10
  - oauth2: 1.16.3
  - onlyoffice: 9.2.0
  - password_policy: 1.18.0
  - photos: 2.4.0
  - picker: 1.0.8
  - polls: 7.0.3
  - privacy: 1.12.0
  - provisioning_api: 1.18.0
  - recommendations: 2.0.0
  - related_resources: 1.3.0
  - serverinfo: 1.18.0
  - settings: 1.10.1
  - sharebymail: 1.18.0
  - spreed: 18.0.7
  - support: 1.11.1
  - survey_client: 1.16.0
  - suspicious_login: 6.0.0
  - systemtags: 1.18.0
  - tasks: 0.15.0
  - text: 3.9.1
  - theming: 2.3.0
  - twofactor_admin: 4.5.0
  - twofactor_backupcodes: 1.17.0
  - twofactor_nextcloud_notification: 3.9.0
  - twofactor_totp: 10.0.0-beta.2
  - updatenotification: 1.18.0
  - user_status: 1.8.1
  - viewer: 2.2.0
  - weather_status: 1.8.0
  - workflowengine: 2.10.0
Disabled:
  - encryption: 2.16.0
  - files_external: 1.20.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - groupfolders: 16.0.6 (installed 16.0.6)
  - news: 24.0.0 (installed 24.0.0)
  - user_ldap: 1.19.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"ePUP5gGexnSP3GwtSsB5","level":0,"time":"2024-04-30T09:52:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\UpdateNotification\\ResetTokenBackgroundJob job with ID 128","userAgent":"--","version":"28.0.5.1","data":{"app":"cron"}}
{"reqId":"ePUP5gGexnSP3GwtSsB5","level":0,"time":"2024-04-30T09:52:03+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\UpdateNotification\\ResetTokenBackgroundJob job with ID 128 in 0 seconds","userAgent":"--","version":"28.0.5.1","data":{"app":"cron"}}
{"reqId":"ePUP5gGexnSP3GwtSsB5","level":0,"time":"2024-04-30T09:52:04+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 130","userAgent":"--","version":"28.0.5.1","data":{"app":"cron"}}
{"reqId":"ePUP5gGexnSP3GwtSsB5","level":0,"time":"2024-04-30T09:52:04+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 132","userAgent":"--","version":"28.0.5.1","data":{"app":"cron"}}
{"reqId":"ePUP5gGexnSP3GwtSsB5","level":0,"time":"2024-04-30T09:52:04+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 137","userAgent":"--","version":"28.0.5.1","data":{"app":"cron"}}
{"reqId":"ePUP5gGexnSP3GwtSsB5","level":0,"time":"2024-04-30T09:52:04+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\UserStatus\\BackgroundJob\\ClearOldStatusesBackgroundJob job with ID 137","userAgent":"--","version":"28.0.5.1","data":{"app":"cron"}}
{"reqId":"ePUP5gGexnSP3GwtSsB5","level":0,"time":"2024-04-30T09:52:04+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\UserStatus\\BackgroundJob\\ClearOldStatusesBackgroundJob job with ID 137 in 0 seconds","userAgent":"--","version":"28.0.5.1","data":{"app":"cron"}}
{"reqId":"ePUP5gGexnSP3GwtSsB5","level":0,"time":"2024-04-30T09:52:04+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 140","userAgent":"--","version":"28.0.5.1","data":{"app":"cron"}}
{"reqId":"ePUP5gGexnSP3GwtSsB5","level":0,"time":"2024-04-30T09:52:04+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 141","userAgent":"--","version":"28.0.5.1","data":{"app":"cron"}}
{"reqId":"ePUP5gGexnSP3GwtSsB5","level":0,"time":"2024-04-30T09:52:04+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job with ID 602","userAgent":"--","version":"28.0.5.1","data":{"app":"cron"}}
{"reqId":"ePUP5gGexnSP3GwtSsB5","level":0,"time":"2024-04-30T09:52:04+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\SuspiciousLogin\\BackgroundJob\\ETLJob job with ID 602","userAgent":"--","version":"28.0.5.1","data":{"app":"cron"}}
```

**Comment by joshtrichards** [comment]
> Update should follow the same pattern as on my other NC instances.

Major releases are published via staged roll-outs (https://docs.nextcloud.com/server/latest/admin_manual/release_schedule.html#release-channels). Not all instances will be offered the update at the same time. 

Also, one of the biggest factors is instance installation time so the same instances tend to get early offers in the current implementation:

https://github.com/nextcloud-releases/updater_server/blob/3a4a05140dff427487651598aaabd47ea689b732/src/Response.php#L71-L103

**Comment by vasyugan** [comment]
> > Update should follow the same pattern as on my other NC instances.
> 
> Major releases are published via staged roll-outs (https://docs.nextcloud.com/server/latest/admin_manual/release_schedule.html#release-channels). Not all instances will be offered the update at the same time.
> 
 
That's not the issue here. The point isn't that the upgrade to a particular version is offered at a different point in time, but that all my other instances **always skip 0.0 releases** and offer upgrades to a new major release only at the first point release, which, I assume, is the wanted behaviour for the stable channel.

**Comment by joshtrichards** [comment]
>all my other instances always skip 0.0 releases and offer upgrades to a new major release only at the first maintenance release, which, I assume, is the expected behaviour for the stable channel.

No. In general: 
- 30% of instances on the stable channel are offered x.y.0 - e.g. nextcloud-releases/updater_server#964
- Then when x.y.1 is published, 30% are offered that - e.g. nextcloud-releases/updater_server#971
- Within a couple weeks 70% are offered it - e.g. nextcloud-releases/updater_server#973
- Then when x.y.2 is published, 100% are offered it - e.g. nextcloud-releases/updater_server#989

It varies a bit IIRC, but that's the convention and based how v28 was rolled out.

> The point is not that the upgrade to a particular version is offered at a different point in time, but that all my other instances always skip 0.0 releases

Because of the way the staging probability works currently, it'll always be the same instances offered the update in the early part of the release cycle of any new major.

**Comment by vasyugan** [comment]
> > all my other instances always skip 0.0 releases and offer upgrades to a new major release only at the first maintenance release, which, I assume, is the expected behaviour for the stable channel.
> 
> No. In general:
> 
>     * 30% of instances on the stable channel are offered x.y.0 - e.g. [28.0.0 nextcloud-releases/updater_server#964](https://github.com/nextcloud-releases/updater_server/pull/964)
> 
>     * Then when x.y.1 is published, 30% are offered that - e.g. [28.0.1 nextcloud-releases/updater_server#971](https://github.com/nextcloud-releases/updater_server/pull/971)
> 
>     * Within a couple weeks 70% are offered it - e.g. [Bump staged rollout of 28 to 70% nextcloud-releases/updater_server#973](https://github.com/nextcloud-releases/updater_server/pull/973)
> 
>     * Then when x.y.2 is published, 100% are offered it - e.g. [28.0.2 nextcloud-releases/updater_server#989](https://github.com/nextcloud-releases/updater_server/pull/989)
> 
> 
> It varies a bit IIRC, but that's the convention and based how v28 was rolled out.
> 
> > The point is not that the upgrade to a particular version is offered at a different point in time, but that all my other instances always skip 0.0 releases
> 
> Because of the way the staging probability works currently, it'll always be the same instances offered the update in the early part of the release cycle of any new major.

Thanks for clearing that up. This is, I have to admit, unexpected, given that updating Nextcloud as soon as a new major release is out is, in my experience, asking for trouble. I've done it way too often in the past and more than once I paid quite a hefty price for doing so.
