### ISSUE TITLE
[Bug]: links to files from "shared with you" do not redirect correctly

### ISSUE THREAD

**Issue by grnd-alt** [nextcloud/server#45166]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

In the files Sections "shared with you" and "shared with others" the links to files are not handled correctly. Redirects of files do not open the files or the sidebar, and are not scrolled into view. For directories the parent directory is opened instead of the actual dir. The folder is also not scrolled into view.
When opening a folder the following error is thrown in browser console:
![Bildschirmfoto vom 2024-05-02 10-38-05](https://github.com/nextcloud/server/assets/56235737/9bd42353-d38d-4451-8af8-b6da09e17f18)

### Steps to reproduce

1. Have multiple files in personal view
2. Share at least one file/folder with someone else
3. Go to "Shared with others"
4. Click on one of the listed files/folders

### Expected behavior

Files should be opened and scrolled into view in the list. Folders should be opened itself instead of the parent directory.

### Version information
tested on: 27.1.9 working as expected
tested on: 28.0.3 not working as expected
tested on: c.nc.c 29.0.0.19 not working as expected
tested on: 30.0.0-dev not working as expected

**Comment by susnux** [comment]
What version of Nextcloud are you running?

**Comment by blizzz** [comment]
> What version of Nextcloud are you running?

He noted down versions in the last **Version information** section.

**Comment by susnux** [comment]
The error message about the error in the console is unrelated and should be fixed in the current branches.

But I can reproduce the error!

**Comment by susnux** [comment]
Things todo:
1. "open in files" action needs to set the `openFile=true` query
2. If the viewer can handle the file then directly open it in the current view.
