### ISSUE TITLE
[Bug]: link previews: internal links to folders don't work

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/server#45194]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

See below. Experienced on cloud.nextcloud.com on May 2, 2024 - [screen recording](https://github.com/nextcloud-gmbh/sysadmin/issues/1390)

### Steps to reproduce

1. copy internal link to a folder
2. put it in a collectives page, a talk chat, ...
3. click on the preview
4. do not select a file within that folder but click "open in files" 
5. you are not redirected to the folder

### Expected behavior

you should be redirected to the folder

### Installation method

None

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by mejo-** [comment]
While this problem is reproducible in Nextcloud 29 on our company instance, I was unable to reproduce locally with latest Nextcloud 30.

**Comment by alexanderdd** [comment]
fixed on c.nc.com 30.0.1
