### ISSUE TITLE
Expiration date of shared links is not set even when it's forced

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#4525]
### Steps to reproduce
1. Enforce expiration date in admin settings
2. Share a file via email or to a user on the server
3. Notice that expiration date is not set

### Expected behaviour
When sharing a link with expiration date (days) set, it should also apply when sending email links and to a user on the same server (haven't tested federated shares)

### Actual behaviour
Expiration date is not set either when you "set expiration date" nor "enforce expiration date".
Only works for public links.

### Server configuration

**Operating system**:
Ubuntu 16.04
**Web server:**
Apache 2.4
**Database:**
MysSQL 5.7
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
master git (20170425)

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - calendar: 1.5.2
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.2.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_sharing: 1.4.0
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - lookup_server_connector: 1.0.0
  - provisioning_api: 1.2.0
  - sharebymail: 1.2.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.0
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - testing
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocbmweud8okg",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/var\/www\/html\/server\/data",
        "overwrite.cli.url": "http:\/\/localhost\/server",
        "dbtype": "mysql",
        "version": "12.0.0.14",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "daniel",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "techandme.se",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.citynetwork.se",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

### Client configuration
**Browser:**
Chromium

**Operating system:**
Ubuntu 16.04
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"lImOn213fIdg2holvr7Q","level":3,"time":"2017-04-26T13:28:10+00:00","remoteAddr":"::1","user":"enoch85","app":"PHP","method":"GET","url":"\/server\/index.php\/apps\/calendar\/public\/OT866VZ49323WLAC","message":"Undefined index: defaultColor at \/var\/www\/html\/server\/apps\/calendar\/templates\/part.fullcalendar.php#28","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/57.0.2987.98 Chrome\/57.0.2987.98 Safari\/537.36","version":"12.0.0.14"}
{"reqId":"tGeJKSpEGzXBbKMjPXVC","level":3,"time":"2017-04-26T13:28:37+00:00","remoteAddr":"::1","user":"enoch85","app":"PHP","method":"GET","url":"\/server\/index.php\/apps\/calendar\/public\/OT866VZ49323WLAC","message":"Undefined index: defaultColor at \/var\/www\/html\/server\/apps\/calendar\/templates\/part.fullcalendar.php#28","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/57.0.2987.98 Chrome\/57.0.2987.98 Safari\/537.36","version":"12.0.0.14"}
{"reqId":"ztOwmpekkonb3G5YItk3","level":2,"time":"2017-04-26T13:36:32+00:00","remoteAddr":"::1","user":"--","app":"core","method":"POST","url":"\/server\/index.php\/login","message":"Login failed: 'c' (Remote IP: '::1')","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/57.0.2987.98 Chrome\/57.0.2987.98 Safari\/537.36","version":"12.0.0.14"}
```
</details>

**Comment by enoch85** [comment]
Same goes for sharing with users on the server. Haven't tested federated shares.

**Comment by enoch85** [comment]
Please remove the milestone if it doesn't belong there.

**Comment by MorrisJobke** [comment]
cc @schiessle @rullzer looks like a regressiong

**Comment by rullzer** [comment]
@schiessle did you consider this when adding the unified sharing stuff?

**Comment by Escubaer** [comment]
This sounds horrible. How did this pass QA? As an admin I need to 100% trust that the expiration date policy I define is adhered to. When will this be fixed? Patch for testing?

**Comment by schiessle** [comment]
It doesn't apply to other shares then public links because it is a public link setting and not a general sharing setting:

![sharing](https://user-images.githubusercontent.com/1589737/28120780-574927ba-6719-11e7-9f09-b0a482928674.png)

Share by mail will also continue to work if you disable "allow users to share via link" because share by mail is a separate share provider you can enable/disable independent from the public link share feature and has his own settings if you scroll down in the sharing settings:

![sharing2](https://user-images.githubusercontent.com/1589737/28120879-a305723a-6719-11e7-860f-90695c402dd8.png)

**Comment by enoch85** [comment]
Well the "it's a feature now a bug". 

I would like to add enforcing in all the other scenarios as well.
- Federated
- Mail

**Comment by schiessle** [comment]
> Federated

I don't think it makes sense for federated shares the same way it doesn't make sense for internal shares. People might be quite restrictive to public links but they don't want to apply or even enforce this for internal shares.

> Mail

For mail we could add a separate setting in the share by mail settings, see my second screenshot. There we also have the enforce password setting independent from the link share settings. This would be a new feature for Nextcloud 13.

**Comment by enoch85** [comment]
> This would be a new feature for Nextcloud 13.

Fine with me. :+1:

**Comment by mathiasconradt** [comment]
@schiessle 

Regarding

> It doesn't apply to other shares then public links because it is a public link setting and not a general sharing setting: [...]

Why is it only possible to set default expiration periods for public links and not for non-public shares? Shouldn't there be a config options for the latter as well somewhere? 

A user is asking for this and logically I don't know why it's not possible to basically set the same default options that are possible for public shares also to non-public shares.

**Comment by skjnldsv** [comment]
> Well then "it's a feature not a bug".
> 
> I would like to add enforcing expiry date in all the other scenarios as well.
> 
> * Federated
> * Mail

Mail: #11547 
User&federated: #13898
