### ISSUE TITLE
[Bug]: Error when updating to Nextcloud Version 29: InvalidArgumentException: Index name "share_id_index" for table "oc_onlyoffice_permissions" collides with the constraint on table "oc_federated_reshares".

### ISSUE THREAD

**Issue by ChangnamOfMyr** [nextcloud/server#45271]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I tried to update Nextloud to Version 29 via the Nexcloud Webinterface.
Then i got the following Error and the Updater said i should report this Error to this Community.

> Update vorbereiten
> Log-Level auf "debug" gesetzt
> Wartungsmodus eingeschaltet
> Reparaturschritt: Repair MySQL collation
> Reparaturinformation: All tables already have the correct collation -> nothing to do
> Reparaturschritt: Copy data from accounts table when migrating from ownCloud
> Reparaturschritt: Drop account terms table when migrating from ownCloud
> Das Datenbankschema wird aktualisiert
> Datenbank aktualisiert
> InvalidArgumentException: Index name "share_id_index" for table "oc_onlyoffice_permissions" collides with the constraint on table "oc_federated_reshares".

I saw a sililar post regarding an upgrade to Version 28 and tried to drop the index from the Database tables but the tables "oc_onlyoffice_permissions" and "oc_federated_reshares" seem to be empty.

### Steps to reproduce

1. Go to Nextcloud Settings
2. Click on Update

### Expected behavior

Updating successfully to version 29.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

PHP 8.1

### Web server

None

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

This form wants me to add a Configuration report and a list of activated apps, but i dont know how to get them as i dont have admin permissions on the Webserver.
The nextcloud Log is a 300Mb txt file and i cant copy it to this form as the Website crashes when i try to paste it here.

**Comment by joshtrichards** [comment]
Since this is in the OnlyOffice integration app you'll need to report this to them:

https://github.com/ONLYOFFICE/onlyoffice-nextcloud

It does look like they attempted to replace this overlapping index name, but I see the old one in a prior migration so maybe there's more to it. I didn't look too closely:

https://github.com/search?q=repo%3AONLYOFFICE%2Fonlyoffice-nextcloud%20share_id_index&type=code

> This form wants me to add a Configuration report and a list of activated apps, but i dont know how to get them as i dont have admin permissions on the Webserver.

That's fine since we likely won't need them now in this case, but for future reference the easiest way to do this is from the command line via the `occ` command. See https:://docs.nextcloud.com.

**Comment by joshtrichards** [comment]
Meant to add: If you need help cleaning up the database tables/indexes post a query on the [Community Help Forum](https://help.nextcloud.com)

**Comment by AndreasB92** [comment]
Could you maybe tell me in very simple language what I have to do here? I get the same error when I want to update to version 29. I don't even want to use Only Office App and deleted it but I still get that error and can only load previous backups.

**Comment by joshtrichards** [comment]
If you need help cleaning up the database tables/indexes post a query on the [Community Help Forum](https://help.nextcloud.com/)

**Comment by p4ck3t0** [comment]
Hi @AndreasB92 ,

I had the exact same issue. I resolved it by running the following query against my database (MariaDB):

```
DROP INDEX share_id_index ON oc_onlyoffice_permissions;
```

This query, drops the index for table `oc_onlyoffice_permissions`. Afterwards the migration runs through and everything seems to work.

Hope that helps.

**Comment by AlexFRAN** [comment]
> Hi @AndreasB92 ,
> 
> I had the exact same issue. I resolved it by running the following query against my database (MariaDB):
> 
> ```
> DROP INDEX share_id_index ON oc_onlyoffice_permissions;
> ```
> 
> This query, drops the index for table `oc_onlyoffice_permissions`. Afterwards the migration runs through and everything seems to work.
> 
> Hope that helps.

Thanks, you're a life saviour!

**Comment by CHunzinger** [comment]
@AndreasB92 

Thank you very much for this!
Updated 4 Nextcloud Sessions and one with this error.
Now it´s fine!!!
