### ISSUE TITLE
Hello, when using the command [given in the documentation](https://docs.nextcloud.com/server/latest/admin_manual/groupware/contacts.html#system-address-book), I get the following error:

### ISSUE THREAD

**Issue by exuded** [nextcloud/server#45285]
Hello, when using the command [given in the documentation](https://docs.nextcloud.com/server/latest/admin_manual/groupware/contacts.html#system-address-book), I get the following error:
![CleanShot 2024-05-13 at 11 56 35](https://github.com/nextcloud/server/assets/52626442/b70a60c4-14f9-4ef6-b950-1a0225c22745)

 I am a bit confused because in the command is no "-a" part

_Originally posted by @exuded in https://github.com/nextcloud/server/issues/39925#issuecomment-2107151889_

**Comment by joshtrichards** [comment]
You're missing a second dash: the parameter is `--value` not `-value`.
