### ISSUE TITLE
[Bug]: Running user:info on user who hasn't logged in creates a folder

### ISSUE THREAD

**Issue by Pytal** [nextcloud/server#45299]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When a user has been created but has not logged in, their home folder should not exist

### Steps to reproduce

1. Create a user `occ user:add --generate-password -- bob` (Do not try to access any user info through the web UI or otherwise)
2. Run `user:info <user>`

### Expected behavior

There is no user folder in the data directory

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Pytal** [comment]
cc @icewind1991

**Comment by joshtrichards** [comment]
The `data/user` directory gets created at account creation time. Behavior looks the same at least back as far back as I checked (v27)...

I presume you mean the `files` folder underneath? I'm not able to reproduce the `files` folder getting created merely by running the `occ user:info newuser` command.

**Comment by Pytal** [comment]
> The `data/user` directory gets created at account creation time. Behavior looks the same at least back as far back as I checked (v27)...

Yes, when creating in the web UI the folder is created but not through occ.

The steps to reproduce would be:

1. Create a user `occ user:add --generate-password -- bob` (Do not try to access any user info through the web UI or otherwise)
2. Run `user:info <user>`

**Comment by Pytal** [comment]
Behaviour seems a bit strange as a data access should not create anything but since this has behaved this way for a long time maybe not worth changing @icewind1991?

**Comment by joshtrichards** [comment]
Looks like the `getStorageInfo()` used by `user:info` calls `setupFS()` regardless of login status:

https://github.com/nextcloud/server/blob/2b2a866b05a371e0a15d83bfc54bebc33e74f2c5/core/Command/User/Info.php#L77-L94

Maybe?

```diff
diff --git a/core/Command/User/Info.php b/core/Command/User/Info.php
index a8fb62099e2..75060ec8e2e 100644
--- a/core/Command/User/Info.php
+++ b/core/Command/User/Info.php
@@ -74,7 +74,7 @@ class Info extends Base {
                        'enabled' => $user->isEnabled(),
                        'groups' => $groups,
                        'quota' => $user->getQuota(),
-                       'storage' => $this->getStorageInfo($user),
+                       'storage' => $user->getLastLogin() ? $this->getStorageInfo($user) : [],
                        'last_seen' => date(\DateTimeInterface::ATOM, $user->getLastLogin()), // ISO-8601
                        'user_directory' => $user->getHome(),
                        'backend' => $user->getBackendClassName()
```

> Yes, when creating in the web UI the folder is created but not through occ.

Oh, right. Guess those should be consistent too.

**Comment by Pytal** [comment]
Closing as discussed with @icewind1991
