### ISSUE TITLE
[Bug]: e.response.data.ocs error while setting link expiration date for folder 

### ISSUE THREAD

**Issue by archeoptah** [nextcloud/server#45292]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I keep getting errors “e.response.data.ocs” and “Error updating this share” when trying to set link expiration time for file drop folder via GUI. Logged as admin.
Clone of: https://help.nextcloud.com/t/e-response-data-ocs-error-while-setting-link-expiration-date-for-folder/192255 

### Steps to reproduce

1. Click on “open details” for folder in GUI
2. Click “sharing” → “customize link” → “advanced settings”
3. Select “set expiration date” and enter desired date (next week / next month)

### Expected behavior

Expected to set expiration date for file share link.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Other

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
activity: 2.20.0
admin_audit: 1.18.0
circles: 28.0.0-dev
cloud_federation_api: 1.11.0
comments: 1.18.0
contactsinteraction: 1.9.0
dashboard: 7.8.0
dav: 1.29.1
federatedfilesharing: 1.18.0
federation: 1.18.0
files: 2.0.0
files_accesscontrol: 1.18.0
files_antivirus: 5.4.2
files_external: 1.20.0
files_pdfviewer: 2.9.0
files_reminders: 1.1.0
files_retention: 1.17.1
files_sharing: 1.20.0
files_trashbin: 1.18.0
files_versions: 1.21.0
firstrunwizard: 2.17.0
logreader: 2.13.0
lookup_server_connector: 1.16.0
nextcloud_announcements: 1.17.0
notifications: 2.16.0
oauth2: 1.16.3
password_policy: 1.18.0
privacy: 1.12.0
provisioning_api: 1.18.0
recommendations: 2.0.0
related_resources: 1.3.0
serverinfo: 1.18.0
settings: 1.10.1
sharebymail: 1.18.0
support: 1.11.0
survey_client: 1.16.0
systemtags: 1.18.0
theming: 2.3.0
twofactor_backupcodes: 1.17.0
twofactor_totp: 10.0.0-beta.2
updatenotification: 1.18.0
user_ldap: 1.19.0
user_status: 1.8.1
viewer: 2.2.0
workflowengine: 2.10.0

Disabled:
bruteforcesettings: 2.8.0
encryption: 2.16.0
photos: 2.4.0
suspicious_login: 6.0.0
text: 3.9.1
weather_status: 1.8.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Additional info

OS: RedOS 7.3

**Comment by joshtrichards** [comment]
Based on the linked forum post, you're seeing this on v28.0.2. Please update to v28.0.5.

**Comment by archeoptah** [comment]
Thank you! Upgrading to newest minor version solved the issue.
