### ISSUE TITLE
Small fixes needed for federation / trusted servers

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#453]
- [ ] the »Trusted servers« header only needs to show up when there are actually trusted servers
- [ ] correct capitalization: »Trusted servers« with small »s«. We only ever capitalize the first word!
- [ ] call the button »+ Add trusted server instead of »+ Add ownCloud server« cause it’s not just limited to that.
- [ ] change the placeholder from »ownCloud server« to something like »Trusted server« or maybe »Nextcloud/ownCloud/Pydio server«. This is where the federation with Pydio also comes in, right?

cc @schiessle

**Comment by blizzz** [comment]
moving to 11

**Comment by MorrisJobke** [comment]
@rullzer @schiessle @nickvergessen @juliushaertl @ChristophWurst Some papercuts you maybe want to work on in the next days ;)

**Comment by nickvergessen** [comment]
Could have also fixed it yourself instead mentioning 5 people... holy moly

**Comment by MorrisJobke** [comment]
> Could have also fixed it yourself instead mentioning 5 people... holy moly

Sure - but I just went through tickets and quickly triaged them ;)
