### ISSUE TITLE
Files app: shared drive

### ISSUE THREAD

**Issue by fulldecent** [nextcloud/server#45314]
There is a set of features for managing access to files for a group called a "shared drive". This is a common paradigm that people understand and expect in group collaboration and workspace software. This issue serves to document and specify these features so that we may add them into Nextcloud where people are expecting them.

## The features

- [ ] Each shared drive is featured prominently in the file explorer
  - [ ] They look different than folders
  - [ ] They do not show up inside "my" folders "my documents" because they are owned by something bigger than you
- [ ] Permissions for the shared drive are set for the drive as a whole:
  - [ ] Super (can set permissions for others)
  - [ ] Read/write/delete
  - [ ] Read/write (but cannot delete existing files/folders)
  - [ ] Read only

## Story

Typically shared drives are set up for specific organizational teams, like "Marketing share drive" or "Finance shared drive".

These are so important, and coworkers are so dumb, that it is important to restrict against deleting things in these folders. 

Here is how this feature is implemented in Google Workspace:

![Screenshot 2024-05-14 at 11 39 55](https://github.com/nextcloud/server/assets/382183/a8d17759-d5fe-4579-a336-81e9f0eb4dd9)

Admin view:
![Screenshot 2024-05-14 at 11 41 12](https://github.com/nextcloud/server/assets/382183/35f322e8-81b3-4bd4-8673-933345c24b6c)

Here is how shared drives are implemented on OneDrive:

![Screenshot 2024-05-14 at 11 42 25](https://github.com/nextcloud/server/assets/382183/dd6de040-d071-46b0-a4b5-012e3cc19a59)

And if you have used Windows or DOS, they call them network drives.

![Screenshot 2024-05-14 at 11 44 16](https://github.com/nextcloud/server/assets/382183/8cbb0279-e63b-4d98-9991-69371bb99f93)

This feature is so popular that most companies name their shared drive "S://" because "s" stands for "shared".

---

In the demo account of Nextcloud, I do not see this feature:

![Screenshot 2024-05-14 at 11 44 56](https://github.com/nextcloud/server/assets/382183/1b55fa59-f0e1-4cc0-8c6f-a54ff75171df)

**Comment by solracsf** [comment]
You can't install apps on the Demo; you must install it (and any other apps) on your own server (or a managed provider).
https://apps.nextcloud.com/

**Comment by fulldecent** [comment]
Got it, thank you, I see this feature requires an extra install to use
