### ISSUE TITLE
Add contacts popover to other apps

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#4532]
We need to make the Contacts popover (when you click on an avatar/username) https://github.com/nextcloud/server/pull/4374 work in other main shipped apps like:
- [x] Activity app and sidebar tab @nickvergessen (implemented in 12) https://github.com/nextcloud/activity/pull/145
- [x] Notifications (implemented in 12)
- [x] Comments sidebar tab @schiessle  (implemented in 12)
- [x] Chat app @sualko https://github.com/nextcloud/jsxc.nextcloud/pull/13
- [x] Gallery share dialog @oparoz 
- …

Clients
- [x] Android app @tobiasKaminsky @AndyScherzinger @mario 
- [x] iOS app @marinofaggiana 
- [ ] desktop app (like in the sharing dialog) @rullzer 

And sooner or later also:
- [x] Mail @ChristophWurst 
- [x] Calendar @georgehrke 
- [x] Tasks @raimund-schluessler @Henni 
- …

cc @georgehrke would be cool if you can drive that.

**Comment by jancborchardt** [comment]
@georgehrke the Comments tab in the right sidebar of files also seems to miss the popover. cc @blizzz @nextcloud/javascript

**Comment by georgehrke** [comment]
> @georgehrke the Comments tab in the right sidebar of files also seems to miss the popover

@nickvergessen just discovered that it needs a reload at the moment. need to fix that

**Comment by jancborchardt** [comment]
Another important part where these actions should be available is in our clients for Android, iOS and desktop.

cc @tobiasKaminsky @AndyScherzinger @mario, @marinofaggiana and @rullzer the feature in question is the popover which appears on clicking any contact avatar / name in the web interface: 
https://github.com/nextcloud/server/pull/4374

Same actually for the contacts menu https://github.com/nextcloud/server/pull/3233 – this is something we could use in the mobile clients too for feature parity. An entry in the sidebar (for Android) and hte More-menu (for iOS) would be a good start.

cc @karlitschek 

Oh and by the way @georgehrke @ChristophWurst an important core action we still need in there is »Share« so you can share something user-centric. Then a filepicker would pop up and you could choose which file/folder you want to share.

**Comment by AndyScherzinger** [comment]
> An entry in the sidebar (for Android)

What would this entry do in the sidebar? The side bar is "just" the main menu / account switcher

**Comment by MorrisJobke** [comment]
@georgehrke @ChristophWurst @jancborchardt Any news on this? We are in feature freeze 🙈 That would mean all the not yet done stuff will be moved to 13.

cc @karlitschek

**Comment by MorrisJobke** [comment]
> @georgehrke @ChristophWurst @jancborchardt Any news on this? We are in feature freeze 🙈 That would mean all the not yet done stuff will be moved to 13.

At least for the server part, but it looks like it is done.

**Comment by georgehrke** [comment]
Yes, everything in core is done. What's missing now is adding the contacts menu popover to apps. I will send a PR for the gallery tomorrow.

**Comment by rullzer** [comment]
So how is this supposed to work from the clients?

Also as far as I can tell there is no public endpoint to get all this info. So that won't work either. Unless i missed something.

**Comment by MorrisJobke** [comment]
@karlitschek @jancborchardt Looks like the rest needs to be done in 13.

**Comment by jancborchardt** [comment]
@georgehrke any update on adding it to Gallery and other apps?

**Comment by georgehrke** [comment]
I will do Gallery in the next couple of days. Don't know about other apps. Calendar doesn't at the moment, but there is also no real list with avatars right now. (Sharing list and attendee list only show the name at the moment)

**Comment by jancborchardt** [comment]
@georgehrke ok, sounds good. Is it also possible that we change it from opening on click to opening on hover? This is how it works on platforms like Facebook, Twitter, Reddit etc. However with a ~1s delay so it doesn’t immediately show when you just move your cursor across the name.

**Comment by MorrisJobke** [comment]
Nothing specific to any NC version -> moving to 15 milestone.

**Comment by juliushaertl** [comment]
This is actually working in the places where our avatar component is used now.

**Comment by AndyScherzinger** [comment]
> This is actually working in the places where our avatar component is used now.

@juliushaertl while it hasn't been implemented on the clients as described in the initial issue text...

**Comment by juliushaertl** [comment]
Oh, my bad, sorry about that.
