### ISSUE TITLE
Files Link Renamer as a basic function

### ISSUE THREAD

**Issue by 8l4ckSh33p** [nextcloud/server#4536]
I find the function of rename very well. This should be integrated as a basic function.

See the OwnCloud app "Files Share Link Renamer" at https://apps.owncloud.com/content/show.php/Files+Share+Link+Renamer?content=174742

**Comment by MorrisJobke** [comment]
This is basically a user defined share link, right?

cc @jospoortvliet @jancborchardt @LukasReschke

**Comment by 8l4ckSh33p** [comment]
@MorrisJobke right!

**Comment by Happyfeet01** [comment]
would be nice.

**Comment by HanZ92** [comment]
I think this is a nice feature by very little effort. Definitely +1!

**Comment by jancborchardt** [comment]
I definitely agree, it’s very useful to generate links you want to share openly for a long time.

cc @LukasReschke for security concerns? ;)

**Comment by 8l4ckSh33p** [comment]
Optionally it is possible to replace the index.php in the link using mod_rewrite.

**Comment by MorrisJobke** [comment]
> Optionally it is possible to replace the index.php in the link using mod_rewrite.

What has this to do with the share token? This is already supported by today.

**Comment by 8l4ckSh33p** [comment]
Forget my post. I have not seen https://help.nextcloud.com/t/apache-rewrite-to-remove-index-php/658/2

**Comment by jancborchardt** [comment]
cc @fcturner of the app https://github.com/fcturner/sharerenamer :)

**Comment by mo0nsniper** [comment]
I would also be interested in the option to rename share links. 
Is there a way to do it currently?

**Comment by jospoortvliet** [comment]
Other than the mod_rewrite, no. It is a bit of a security issue. The app, which would indeed solve it for those willing to run the risk, has not been ported to Nextcloud and I can't tell you if it would work if you tried to change the values in info.xml - worth a try perhaps?

**Comment by mo0nsniper** [comment]
@jospoortvliet Thanks for the info. 
I have tried the sharerenamer app, I can enable it by editing info.xml, but unfortunately it doesn't work. When I try to rename a share it gives and error.

**Comment by jospoortvliet** [comment]
@mo0nsniper ah, too bad :( so the app will need a bit of work. Perhaps its author is willing to do that - if he/she is still active, the app hasn't been updated for a while and the github account is deleted :(

**Comment by jancborchardt** [comment]
Just for the record, the repo has seemingly moved to https://github.com/T-a-z/sharerenamer and the issues have been deactivated. The fork which makes the app work with Nextcloud is still at https://github.com/LazyShpee/sharerenamer thanks to @LazyShpee :)

**Comment by jospoortvliet** [comment]
Oh, great, didn't see that! @LazyShpee any chance we can convince you to upload it to apps.nextcloud.com?

**Comment by LazyShpee** [comment]
At first I only updated this app for my own personal needs and decided to fork instead of keeping it to myself. Glad people are happy about it, I'll see about uploading it to apps.nextcloud.com when I'll have some free time from my studies (^-^)b

**Comment by jospoortvliet** [comment]
@LazyShpee would be awesome, really ;-)

**Comment by yamlfd** [comment]
How can I install this addon from https://github.com/LazyShpee/sharerenamer?

**Comment by jospoortvliet** [comment]
Choose 'download' and put the files in the apps subfolder of nextcloud, make sure they are in a folder called 'sharerenamer' and all in there, not in another subfolder in there (like 'master'). Then make sure the files are owned by the webserver user (like, www-run or something) and you can enable the app in the app interface.

**Comment by yamlfd** [comment]
Many thanks - that works! I really hope this important feature goes into the core product very soon. I hate using external link shorteners.

**Comment by jospoortvliet** [comment]
@yamlfd as discussed, security will probably keep this out of core but as an app easily installed on the store it'd be great.

**Comment by yamlfd** [comment]
I do not see how this can change security. A custom path has a password for sharing and gives enough security. It's also not used for everything I think.

**Comment by jospoortvliet** [comment]
@yamlfd chosen paths can result in users, esp on large instances, finding other users' shared links. Same with third parties from the outside. I'm no expert and it isn't my decision so there's little point in arguing - I leave that to the experts ;-)

**Comment by yamlfd** [comment]
A permission make sense, so not everyone may create these nice links :-)

**Comment by jospoortvliet** [comment]
@LazyShpee hey please please put it in the Nextcloud app store! I get regularly asked, like today by @enoch85 ;-)

**Comment by enoch85** [comment]
Yeah for sure, would be super-duper-mega-awesome! :D

**Comment by yamlfd** [comment]
+1 from me, too. Works very well.

**Comment by jospoortvliet** [comment]
Once again, people asking for this! @LazyShpee put it in the app store if you can!

**Comment by HanZ92** [comment]
Anyone tried, if it works with Nextcloud 13?

**Comment by rocketskill** [comment]
@HanZ92 I updated my nextcloud to 13 version this week.
The Files Link Renamer app is not working anymore.
The app is desactivated and i can't activate it manually :/

**Comment by tepung** [comment]
@HanZ92 , @rocketskill , updated to nextcloud 13 just now .. sadly Files Link Renamer also not working anymore ..
This is a *must* have and favourite app ..
Hope @jancborchardt able to add it to app store, that will be a great add-on for nextcloud ..

Thanks a lot

**Comment by HanZ92** [comment]
It's still working! You just need to edit
sharerenamer\appinfo\info.xml

line 13
`max-version="12.0"`

Just set it to 13.0 and it will work again!

**Comment by tepung** [comment]
Thanks @HanZ92 .. confirm working .. now my nextcloud is perfect with it ..

**Comment by rocketskill** [comment]
Happy to hear that ! I'm gonna try to edit that today.
Thanks for the tip :)

**Comment by tepung** [comment]
and also works with **workin2gether** app, same method as @HanZ92 mentioned ..
i've used both of the apps ..

Thanks for the help ...

**Comment by tomas-chrastina** [comment]
For longtime shares this is a highly requested feature. Sure, I understand security concerns. But if we can restrict usage to custom user list (the same way as we can many applications now), who will use it with precausion, it would be fine. And IMHO it should always be admin' or user's decision, whether he will allow such feature knowing and evaluating all possible risk scenarios. But is should be core/internal app feature.

**Comment by jospoortvliet** [comment]
@tomas-chrastina it is the admin's choice - they can install the app. That's exactly what apps are for: things that don't work for the entire user base stay as apps. Calendar/Contacts aren't part of core and they are far more used and supported, so why should this be so special to be integrated...

**Comment by tomas-chrastina** [comment]
@jospoortvliet I have no problem at all to let it as application. But I would prefer it to be maintained by core nextcloud developers, as it's linked to core feature of nextcloud. I just wanted to pointed out, that there shouldn't be used argument based on security issues for not implementing such feature. Just create it in any way, and let us to decide whether it's safe for us. For example on my insance it would be really beneficial feature for many links I use for long-time sharing. 
So I don't oppose whether it would be core feature available through settings, or application. I even prefer application, as it can be enabled (if application is prepared this way) only for specific group of users. I just want it to be maintained by core developers, because this kind of feature has to be keep in mind in long term development.

**Comment by DecaTec** [comment]
Any news on this one, @LazyShpee ?
I'm looking for exactly this feature. At the moment, you could achieve something similar by editing NC's vHost for nginx. But this always requires administrative work for every shared link which should be more readable.

As the initial maintainer of the app (Fallon Turner) somehow dissapeared from GitHub and @LazyShpee hasn't released the app in the app store for some reason, just another question: 
What about the possibility if someone would fork the repo and release it in the app store? I'm not into the license details (AGPL) and I don't want to "steal" any work, so any advice would be much appreciated (@jospoortvliet, @MorrisJobke maybe?).

**Comment by jospoortvliet** [comment]
@DecaTec you, and anyone else, are absolutely welcome to take a copy of the code in your github repo, and offer it into the app store. You have to keep copyright assignment in the files, crediting the author(s), that is what you need to comply with the AGPL. In general, being 'just nice' tends to be enough: I would consider it polite to note who the original author is, and that is also enough.

So you can do this if you like :+1: I would use it on my private Nextcloud...

@tomas-chrastina the core developers generally work on what our customers pay them to work on - and they all run large installations, so they tend not to want this feature. I don't think it is thus likely that it becomes maintained by Nextcloud GmbH... Of course, if you're a customer, you can change that ;-)

**Comment by jospoortvliet** [comment]
(I close this because we don't want to do this from a security point of view and having this as an app for the people who really want it, despite that risk, is sufficient from my point of view)

**Comment by melyux** [comment]
It's not sufficient because the apps can't give you a mobile app option to do this. Which is where this would be used the most anyway.
