### ISSUE TITLE
Group restrictions for an app are lost when disabling it

### ISSUE THREAD

**Issue by zinks-** [nextcloud/server#4538]
### Steps to reproduce

1. Enable an app and chose the option to "Enable only for specific groups" (specifying 1+ valid group(s))
2. Disable the app
3. Enable the app again

*Notes:* 
- Steps 2 and 3 can be carried out using `occ app:` with the same result
- Between steps 2 and 3, if you don't refresh the page you'll notice that the group selector stays visible, with the groups you selected still shown. It is probably only a display bug and should warrant its own issue in the tracker.

### Expected behaviour
If the option of enabling "only for specific groups" was used before the app is disabled, enabling the app again should by default enabling it for the same previously chosen groups

### Actual behaviour
The app is enabled for all groups.

As apps are disabled during the update process, you're then forced to reconfigure the group permissions for each app.

### Server configuration

**Operating system**: Debian 8 "Jessie"

**Nextcloud version:** 11.0.3

**Comment by jancborchardt** [comment]
cc @icewind1991 @eppfel @LukasReschke this should ideally be preserved. :)

**Comment by szaimen** [comment]
Any update on this? 

In my experience for a good update script to work well all apps are disabled during upgrades so it removes the group limitations each time and I have to set them again.

I guess each app would need an addtional config:app entry for that feature which could be called e.g. "group_limitation"

**Comment by enoch85** [comment]
I may be wrong, but shouldn't that setting be saved in DB? 

Would be nice to see some progress here. Thanks! :)

**Comment by szaimen** [comment]
Will be fixed with https://github.com/nextcloud/server/pull/29020
