### ISSUE TITLE
Default share expiration cannot be removed when creating a share

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#45384]
## Steps to reproduce

1. Ensure "Set default expiration date for shares" is checked but expiration dates are not enforced
2. Create a new share to a user through the web UI
3. Remove the share expiration checkbox
4. Save the share
5. Edit the share again

## Current behaviour

The expiration date is still set

## Expected behaviour

The expiration date is not set as the user removed it

## Additional context

It seems the request to create the share doesn't have a expiration date in the request payload but the response is returning it, so either the backend needs some adjustment or the frontend code needs to ensure that a null/empty value is sent along

## Affected versions

master to stable27

**Comment by Fenn-CS** [comment]
Fixed in https://github.com/nextcloud/server/pull/44485

**Comment by Fenn-CS** [comment]
https://github.com/nextcloud/server/pull/44485 is now merged.
