### ISSUE TITLE
Nextcloud 28 and 29 : Properly pre-select new file and folder default name when creating them (for quick renaming)

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/server#45409]
**Renaming a new folder before creation :** 
- In Nextcloud 29, when we create a folder in “Files”, the folder name in the creation popup is not selected. This forces us to select the name, then proceed with renaming, and therefore affects the user experience.
- In Nextcloud 28, 27, the default name was selected, enabling on-the-fly renaming just before confirming (by pressing enter and clicking on the arrow).

**Renaming a new file before creation :** 
- In Nextcloud 28, when a file is created (for example, an odt file), the default file name and extension are selected, making it impossible to rename the file properly without first selecting the file name, without the extension. 
- In Nextcloud 29, nothing is pre-selected, so you have to select the file name with the mouse in order to proceed with renaming. 
- In Nextcloud 27, the file name (without extension) was selected, enabling on-the-fly renaming just before confirming (by pressing enter and clicking on the arrow).

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bravedave** [comment]
In the latest version this has got more difficult
- as said; _the text is not selected_
- but it is also _not focused_ on the field

Somehow you have to get focus to the field - when you click (with mouse), it opens the file (i.e. the event continues to bubble to the row, and the row click event is triggered)

The only way to rename it sometimes is to
- select the elipses to drop the menu
- hover on rename
- and press enter
- This selects the file as expected

**Comment by Mer0me** [comment]
Maybe related to https://github.com/nextcloud/server/issues/42813
