### ISSUE TITLE
preview directory in appdata_xxxx has grown over 120GB of Total size

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/server#45405]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

preview directory in appdata_xxxx has grown over 120GB of Total size

### Steps to reproduce

1. check the size on RHEL 8.9 with du -hs /appdata_xxxx/preview
2. size is over 120GB
3.

### Expected behavior

There should be a mechanism where the old, obsolete and/or long unused previews are automatically deleted. 

An admin should also be able to perform such an operation manually.

QUESTION:

1 - Is there such an automatic mechanism ?
2 - Is there a manual mechanism ?

I know, i could remove the oldest previews in the preview folder, run a fresh "occ files:scan-app-data" afterwards.

But i think there must be a more proper, stable way to do that !?

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

27

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
not relevant here

NC version":"27.1.9.1"
```

### Nextcloud Signing status

```shell
no errors
```

**Comment by joshtrichards** [comment]
> 1 - Is there such an automatic mechanism ?

Yes. It runs hourly: https://github.com/nextcloud/server/blob/master/lib/private/Preview/BackgroundCleanupJob.php

Are you getting any errors in your logs like perhaps was reported in #42540?

> 2 - Is there a manual mechanism ?

There is no single command that does this currently. Though this would be a reasonable enhancement.

**Comment by st3iny** [comment]
The job mentioned above will only clean previews of deleted files. There is no mechanism for deleting previews of old files.

**Comment by Githopp192** [comment]
@joshtrichards - no - as far i see i do not have those or some of those errors mentioned in #42540 

i analysed how many of directories i've got in the preview folder for every year:

[root@server ~]# grep ' 2010' /tmp/file_list_of_preview_dir|wc -l
0
[root@server ~]# grep ' 2017' /tmp/file_list_of_preview_dir|wc -l
357
[root@server ~]# grep ' 2018' /tmp/file_list_of_preview_dir|wc -l
925
[root@server ~]# grep ' 2019' /tmp/file_list_of_preview_dir|wc -l
8382
[root@server ~]# grep ' 2020' /tmp/file_list_of_preview_dir|wc -l
4292
[root@server ~]# grep ' 2021' /tmp/file_list_of_preview_dir|wc -l
345
[root@server ~]# grep ' 2022' /tmp/file_list_of_preview_dir|wc -l
224
[root@server ~]# grep ' 2023' /tmp/file_list_of_preview_dir|wc -l
248

so - i suppose the issue began on 2019/2020 within an earlier version of nextcloud

I did count all image files  [jpg/jpeg/png/gif/bmp/tiff/svg] for all users :

Totally 313 GB of used space for all images  - Nextcloud Preview will use 38% of space of them !
So, it is assumed, that the cleanup operation will not work as expected.

That means a manual (controlled by the cloud admin) mechanism for cleanup preview space is urgently needed.

**Comment by kesselb** [comment]
> i suppose the issue began on 2019/2020 within an earlier version of nextcloud

Please elaborate on the issue, what did you observe, what do you think is not right, what is an obsolete preview?

The expected behavior is: Previews are generated for supported file types. If the source file is deleted, the previews are removed as well. 

We don't track the last access for files, and therefore cannot know when a preview was accessed the last time.

**Comment by solracsf** [comment]
Please also note that the ratio is **not 1 preview per image**.
There are quite a few preview sizes generated per image (64x64, 356x356, 1024x768 and so on).
Also, not only image are taken into account (MP3, Vidos, PDF, and other too can count).

So, 38% is not a big number IMO.

See if needed:

https://github.com/nextcloud/server/blob/54afea4b01385106a241a5161b3894e669716107/config/config.sample.php#L1195-L1347

And https://github.com/nextcloud/previewgenerator (specially the _"I don't want to generate all the preview sizes"_ part).

**Comment by st3iny** [comment]
No, this will only replace the preview provider not the storage. Imaginary is an external service that offers great performance and a wide variety of supported preview formats.

It will not store your previews. Instead, it will process them on the fly and send them back to Nextcloud to be stored.

**Comment by Githopp192** [comment]
Thx @st3iny / Richard for this explanation :-)

**Comment by csware** [comment]
My previews folder grew over 250 GiB.

Was there a change recently in Nextcloud? IIRC Nextcloud used to generate previews only on demand (this is what I'd like to keep), but with 27/28/29 it seems to automatically generate previews as soon as a file is uploaded/changed (using Nextcloud Client noit the browser).

is there a way to get the old behavior back?

**Comment by st3iny** [comment]
Previews are still generated on demand. Nothing has changed about that.

**Comment by csware** [comment]
> Previews are still generated on demand. Nothing has changed about that.

Yep, but they should be only generated on demand.

Yesterday I disabled update generation (`'enable_previews' => false`), but still new previews are generated and showing up in the previews folder. Existing previews are still shown on the browser interface (that's ok) and the photo app shows no previews at all (and does not seem to generate new).

**Comment by provokateurin** [comment]
Closing in favor of https://github.com/nextcloud/server/issues/45962
