### ISSUE TITLE
[Bug]: [Version 29.0.0] Nextcloud Could not load at least one of your enabled two-factor auth methods. Please contact your admin.

### ISSUE THREAD

**Issue by ZiggiZagga** [nextcloud/server#45414]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After Upgrading from Version 28.0.5 to Version 29.0.0, Users are not able to login using  two-factor auth method "Email". Following Message gets displayed after entering correct username and password:
`Nextcloud Could not load at least one of your enabled two-factor auth methods. Please contact your admin.`

### Steps to reproduce

1. Start Nextcloud Server Version 28.0.5.
2. Create a User Group 2-FactAuth.
3. Enforce 2-factor auth for the group.
4. Add new Users to group and configure 2-factor auth method email for each user.
5. Test if everything is working as expected.
6. Upgrade to 29.0.0
7. Test again

### Expected behavior

1. The Email Provider should load as expected. 
2. The ability to setup 2-factor after first succesful login.

### Installation method

None

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

PHP 8.1

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment]
Configuration report missing 
App list missing 

I guess you are talking about twofactor_email? The app is unavailable for 29 and therefore got disabled during the update.
