### ISSUE TITLE
[Bug]:/index.php/apps/activity/all 

### ISSUE THREAD

**Issue by haoyuannov** [nextcloud/server#45416]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![bug](https://github.com/nextcloud/server/assets/76189568/4ae2554b-0e4d-4c25-a5db-df7ec08475f1)
![bug1](https://github.com/nextcloud/server/assets/76189568/cdaee3f5-dcae-43e1-b018-2a5db103bb1f)

### Steps to reproduce

I found that these icons on the activity page are all bad and have not been loaded. My website has a port, but the icon URL loaded does not include the port number.There is no port after the domain name of the activity link。

### Expected behavior

repair

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by susnux** [comment]
@haoyuannov Have setup your `trusted_domains` correctly? You need to add it with port there.
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#trusted-domains

---

If yes and it still not works you can use `overwritehost`:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#overwritehost

**Comment by haoyuannov** [comment]
> 设置正确了吗？您需要在那里添加端口。 https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#trusted-domains`trusted_domains`
> 
> 如果是，它仍然不起作用，您可以使用：https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#overwritehost`overwritehost`
Thank you, I solved the problem using the code `'overwritehost' => ' ',`
