### ISSUE TITLE
need to click twice to add first rule to File access control rule group

### ISSUE THREAD

**Issue by individual-it** [nextcloud/server#4542]
### Steps to reproduce
1. enable "File access control" app
2. add a rule group
3. click on "Add rule"

### Expected behaviour
a new rule line should be created and displayed

### Actual behaviour
nothing
need to click a second time to add the line
if a rule exists the next ones can be added by a single click

### Server configuration

**Operating system**:
 Debian 4.8.15-2~bpo8+2
**Web server:**
 Apache 2.0
**Database:**
 sqlite
**PHP version:**
 7.0.7-5
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 12.0 alpha (git master)
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated after pulling current master
**Where did you install Nextcloud from:**
git (master)
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - bruteforcesettings: 1.0.0
  - comments: 1.2.0
  - dav: 1.2.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.2
  - files_sharing: 1.4.0
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - lookup_server_connector: 1.0.0
  - provisioning_api: 1.2.0
  - sharebymail: 1.2.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.0
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - contacts
  - encryption
  - files_external
  - testing
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocy6ybr6vhoa",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/home\/artur\/www\/nextcloud-server\/data",
        "overwrite.cli.url": "http:\/\/localhost\/nextcloud-server",
        "dbtype": "sqlite3",
        "version": "12.0.0.15",
        "installed": true,
        "blacklisted_files": [
            ".htaccess",
            "c.png"
        ],
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
 FF 52.0.2
**Operating system:**
Debian

**Comment by jancborchardt** [comment]
cc @nickvergessen @MorrisJobke

**Comment by juliushaertl** [comment]
Obsolete though the new workflow ui
