### ISSUE TITLE
Filetype filters on top of the files list (doc, pdf, jpg, ...)

### ISSUE THREAD

**Issue by artonge** [nextcloud/server#45437]
@nextcloud/designers for mockups

**Comment by szaimen** [comment]
Example from google drive: 
![image](https://github.com/nextcloud/server/assets/42591237/dc0ec44a-f639-40cb-a3dc-26a16502b864)

**Comment by jospoortvliet** [comment]
@marcoambrosini wanted, in general, to also look at the search bar, but this brings in a whole 'what to do with search' discussion. Best that design comes up with a complete concept.

**Comment by artonge** [comment]
@nextcloud/designers can we have some proper mockups for that?

**Comment by marcoambrosini** [comment]
Kickoff call outcome @AndyScherzinger @artonge @susnux @szaimen 

* We start with filters but with taking into account that in the future we might add a search bar 
* More than just file type: also add people and modified like google 
* We keep the filters just above the files list and below all rich documents and recommended files
    **Open question: do these filters only filter the current folder or are they recursive?** 
E.g. when I filter for "documents" in a folder, do I see all documents in the whole folder tree or just the ones present in the current folder? From a UX perspective I think the former is the most beneficial, but it's much more difficult to achieve technically. It's also what our competitors do when using these filters. 
From a visual design perspective little will change regardless of what we choose so we go ahead with the mockups

Also cc @karlitschek and @jancborchardt 

### Current rough idea of the **worst case scenario** (Recommended files in root folder + rich workspaces enabled)

![Image](https://github.com/nextcloud/server/assets/26852655/f1623e57-1ddc-4626-b314-a43c3ab73e79)

### Current rough idea of the **best case scenario** (subfolder with no rich workspaces)

![Image](https://github.com/nextcloud/server/assets/26852655/24db7828-4377-4236-9d11-ec4029c24f75)

**Comment by jancborchardt** [comment]
@marcoambrosini seems good, some feedback:
- Can we just call it "Type" instead of "File type", much nicer and compact.
- The dropdowns have some uniform width which looks off with the extra whitespace between text and down arrow. Would look nicer if it’s only as wide as needed.
- How does it look when the dropdowns are opened? I assume either like in Google Drive or in our search, but would be good to clarify.



> Open question: do these filters only filter the current folder or are they recursive?
> E.g. when I filter for "documents" in a folder, do I see all documents in the whole folder tree or just the ones present in the current folder? From a UX perspective I think the former is the most beneficial, but it's much more difficult to achieve technically. It's also what our competitors do when using these filters. @susnux suggested that there could be a switch between current folder and all subfolder filtering.

I would first go with what is doable technically in a nice way, we can always improve on that. But no to a switch between modes here, that would needlessly complicate it.

**Comment by susnux** [comment]
>> susnux suggested that there could be a switch between current folder and all subfolder filtering.
> 
> I would first go with what is doable technically in a nice way, we can always improve on that. But no to a switch between modes here, that would needlessly complicate it.

To clarify for me it is about having two options:
1. **Filter** the *current* folder (e.g. if there are a lot of file, I know the folder but I just want to filter)
2. **Search** for something (e.g. search for a PDF somewhere in the file tree

**Comment by susnux** [comment]
Questions:
What file type filters do we use?
All types we found in the list? Or a generic list like
- folders
- documents (like office, spreadsheets and presentations)
- Images
- Videos
- Audio

(this list would be easy to implement)

Or more like specific files? (PDF, JPG...)

What does "Modified" filter? "yesterday" "last week"? 

People: Should this only filter the owner?

**Comment by jancborchardt** [comment]
@susnux for all of these, I would follow Google Drive’s lead since that’s the solution spearheading this. cc @marcoambrosini

**Comment by susnux** [comment]
I started implementing it, but have a question:
The mock up is using a drop down, shall we use it or go with actions?
Especially for user filtering a drop down would be a completely new component to allow two menu levels (1. user 2. "shared the file", "owned the file", etc)

With a drop down it looks like this:
[Screencast_20240605_223801.webm](https://github.com/nextcloud/server/assets/1855448/c4ee2340-f016-449f-bb12-e2843060bc59)

**Comment by marcoambrosini** [comment]
<img width="478" alt="Screenshot 2024-06-06 at 10 56 40" src="https://github.com/nextcloud/server/assets/26852655/6be552cb-5c1f-412c-9ed6-98929fb4afae">

Hi @susnux, I think we should go with actions like in the global search

**Comment by susnux** [comment]
@marcoambrosini with actions it could look like this:

https://github.com/nextcloud/server/assets/1855448/ad6d4116-c203-4a77-8e3c-3919939e13d4

**Comment by susnux** [comment]
> Could "Clear filter" go to the bottom of the action menu

Sure but then you need to scroll fully down to clear, is that ok?

**Comment by sorbaugh** [comment]
The related PR: https://github.com/nextcloud/server/pull/45708
