### ISSUE TITLE
Make the grid view more usable by handling longer filenames better

### ISSUE THREAD

**Issue by artonge** [nextcloud/server#45438]
Improve the overall design of the grid view.
@nextcloud/designers for mockups

* Main issue is that file names beyond ~10 characters can't be read. 
* If accessibility can be fixed/improved easily, do that too, but only as low priority.

**Comment by szaimen** [comment]
Example from google drive: 
![image](https://github.com/nextcloud/server/assets/42591237/81a0ea42-8162-4bd4-91a1-7cd8cd1d38c8)

**Comment by artonge** [comment]
@nextcloud/designers can we have some proper mockups for that?

**Comment by szaimen** [comment]
Example Dropbox:
| Grid view | Big grid view |
|---|---|
| ![image](https://github.com/nextcloud/server/assets/42591237/3a2c75d7-8c29-45fe-9b44-5b7b7e782fcc) | ![image](https://github.com/nextcloud/server/assets/42591237/d8858dfa-a744-4e76-a1b3-763c032b3d6a) |

**Comment by szaimen** [comment]
Onedrive:
![image](https://github.com/nextcloud/server/assets/42591237/72080dec-4569-4a5e-a27e-b28881fc5169)

**Comment by szaimen** [comment]
Penpot: 
![image](https://github.com/nextcloud/server/assets/42591237/e8c23e72-94ab-4562-9f6a-c0cae39f0280)

**Comment by marcoambrosini** [comment]
I like google's approach the best

**Comment by szaimen** [comment]
This is how the final mockup without previews looks:
![image](https://github.com/nextcloud/server/assets/42591237/2f82d769-475b-4717-9580-d93a9a29cac2)
and here with previews:
![image](https://github.com/nextcloud/server/assets/42591237/a66ba0a7-d879-4e49-b027-5719765c9dd7)

**Comment by jmigual** [comment]
I'm not sure whether I should open a new issue or not for this but in Nextcloud 29 at least, when filenames are very long it is not possible to see the full name on mobile in any place AFAIK.

**Comment by artonge** [comment]
@jmigual can you provide screenshots?
@nextcloud/designers ^

**Comment by jmigual** [comment]
Sure! Here they are:

![Screenshot_2024-10-02-13-30-45-15_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/856e1005-d103-4cf4-9f51-7a7d4033ce72)

![Screenshot_2024-10-02-13-30-39-46_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/user-attachments/assets/244d817c-c6a0-4c72-81e5-25ecc3155f6e)

The biggest problem IMO is that it's never possible to see the full name of the file. Not even on the details panel.
