### ISSUE TITLE
File request

### ISSUE THREAD

**Issue by artonge** [nextcloud/server#45446]
This is a modal dialog that helps a user create a file drop link & send it to people. A specific dialog makes it easier to find and use, and more visible to users. But the end result is 'just' a file drop link.

Similar to https://help.dropbox.com/share/create-file-request
Sub task: Enter name when you upload some files, sort in folder

Use case:
* university teacher requests homework from the students. The student has to enter their name. Their uploads are stored in subfolders by their name. Expiration date = deadline for homework turn in time!

Flow:
* Somewhere (maybe in the + menu) choose 'request a file'
* Give a title (will be the name of the file-drop link)
* Description (optional) (put in note to recipient)
* choose a location (folder) the files should go into
* choose if the files should go into a subfolder based on name of uploader (optional)
* choose deadline (optional but might be set by default) (goes into expiration date) - should have a warning that once the expiration date is hit, the request disappears and a new one has to be created.
* choose password (optional but might be enforced) 
* choose recipients (optional) - should be possible to be users/groups/email addresses (from address book?)
* click 'create' & get a link.
* would be good to go to the folder and how the file drop in the side bar, so the user also 'learns' where the link now is, where they can modify it etc.
* we should add a 'file requests' to the share sidebar, showing all file drop links
* We also need to make the share note much more visible to the recipient - it is now quite hidden. It should ideally also allow a bit more 'richness' in its markup, but that's not so critical.

**Comment by jospoortvliet** [comment]
Additional request - let's discuss how much of this we can do.

## Scenario

Teacher has to give homework to students. Google has a feature for this: the teacher selects a file, selects a group of students, and a deadline. Students each get a copy of the file and have until the deadline to finish the homework. This feature has been requested in Sweden and Denmark and also mentioned in other places. Even as blocker or a major boost vs competition.

Now this does NOT fully fit the file request feature as above, as that maps fully onto file-drop and thus would be a frontend-only task.

My thoughts on what probably needs doing for the "homework scenario":
* ability to attach a file to a file-drop, not just a 'note'. 

WIP

**Comment by sorbaugh** [comment]
PR that will close this issue: https://github.com/nextcloud/server/pull/46007
