### ISSUE TITLE
Notification when a user download or upload a file

### ISSUE THREAD

**Issue by artonge** [nextcloud/server#45449]
Add a checkbox in the share details that will result in a notification. Those notifications can already be configured in the personal notifications sections, so no need to specify nc notification or email.

- Per share settings to choose whether to have the notification
- Unsure: should it be also for internal? Request more input from other designers. Risk: user enables this on a folder that is widely shared in the org. If 250 clients then download that folder, the user will never recover from the notifications 😭 

What about false positive, do we count download as any GET on WebDAV, or do we limit it to the Download button?
Are we trying to count file access or actual downloads?

For internal shares? https://github.com/nextcloud/files_downloadactivity

**Comment by artonge** [comment]
- [ ] Add a setting in the shares sidebar
  - Find a proper name to reflect the actual feature to the user
  - One toggle to enable/disable notifications
- [ ] Create a notifications when an activity is created and when the share has notification enabled
  - Don't create new notification when a same notification is not read yet
  - Add the name of the users in the notification
    - Should be possible in some cases after the File request feature is implemented
  - Include link to navigate to the file
- Limitation on internal shares when the files get sync by a lot of Desktop client
  - We could filter by user agent
- How to differentiate between download and display. What is the reason for the notification. n°1 would be the easiest
  1. on access: view and download
  2. only on download
  3. only on view

**Comment by Volker-K** [comment]
In Addition: Enable any kind of notification when a file is uploaded to a folder that is shared by an external link. It is not clear to users why such a notification is possible for a share with a user, but not if a folder has been shared via an external link.

**Comment by sorbaugh** [comment]
@jancborchardt are we waiting for mock-ups for this?

**Comment by jospoortvliet** [comment]
No, it's an additional checkbox and a standard notification...

**Comment by jospoortvliet** [comment]
agreement to skip internal completely for now. Just focus on public link shares - files or folder - where enabling the "notify of changes" (text tbd) box will result in a notification when downloads or uploads (in a folder) take place.

**Comment by sit-vodi** [comment]
Hi folks,

I'd like to forward a feature request from our users.

It would be nice to get mail notifications for uploads to internally shared folders.
It would be exceptionally nice to turn those notifications on or off on a per folder/share basis.
