### ISSUE TITLE
Should not be able to mount a "Secure drop" share 

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#4546]
### Steps to reproduce
1. Share a folder with upload permissions
2. Share a folder with secure drop permissions
3. As user2 open the 1. public link and replace the sharingToken with the one from 2.
```xml
<input type="hidden" name="sharingToken" value="P8y3JlshoKFjf27" id="sharingToken">
```

### Expected behaviour
Error

### Actual behaviour
Works, you still dont see the files, but it spams the log with exceptions everytime you open your files.

@schiessle

**Comment by rullzer** [comment]
This is fixed already in master as far as I can see.
