### ISSUE TITLE
Upgrade from 11.0.2 to 11.0.3 failed because of MySQL alter table

### ISSUE THREAD

**Issue by Gardakant** [nextcloud/server#4548]
Using the updater I got this error when upgrading from 11.0.2 to 11.0.3.

Got this error:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_dav_shares` CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

Using Debian 8.7 with MySQL 5.5.55-0+deb8u1, apache2 2.4.10-10+deb8u8, php 5.6.30+dfsg-0+deb8u1

Updated from an older Nextcloud/ownCloud or fresh install: older

Installed 11.0.2 from sources from nextcloud website

List of apps:

root@host1:/var/www/nextcloud# sudo -u www-data php occ app:list
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - audioplayer
  - bookmarks
  - calendar
  - contacts
  - deck
  - delete_confirmation
  - direct_menu
  - encryption
  - external
  - files_accesscontrol
  - files_antivirus
  - files_automatedtagging
  - files_external
  - files_markdown
  - files_retention
  - nextant
  - notes
  - ocsms
  - ownbackup
  - ownpad
  - passwords
  - rainloop
  - richdocuments
  - spreedme
  - user_external
  - user_ldap
  - user_saml
root@host1:/var/www/nextcloud#

No encryption, no external storage, no external user backend

Nextcloud log:

{"reqId":"WQGvnNQr9goAACv3gfcAAAAB","remoteAddr":"X.X.X.X","app":"updater","message":"\\OC\\Repair::step: Repair step: Repair MySQL collation","level":1,"time":"2017-04-27T08:45:22+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=z4uRznwBaDpvfGn3hTSIdg7Kii4mF2vOPDjBKvqUlOM%3D%3AmL%2Bgq05GB2xXTQ7D9WzQB1%2Bu2hZcQyGFDlSRRr%2Fwwak%3D","user":"--","version":"11.0.2.7"}
{"reqId":"WQGvnNQr9goAACv3gfcAAAAB","remoteAddr":"X.X.X.X","app":"updater","message":"\\OC\\Repair::info: Repair info: Change row format for oc_dav_shares ...","level":1,"time":"2017-04-27T08:45:22+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=z4uRznwBaDpvfGn3hTSIdg7Kii4mF2vOPDjBKvqUlOM%3D%3AmL%2Bgq05GB2xXTQ7D9WzQB1%2Bu2hZcQyGFDlSRRr%2Fwwak%3D","user":"--","version":"11.0.2.7"}
{"reqId":"WQGvnNQr9goAACv3gfcAAAAB","remoteAddr":"X.X.X.X","app":"updater","message":"\\OC\\Repair::info: Repair info: Change collation for oc_dav_shares ...","level":1,"time":"2017-04-27T08:45:22+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=z4uRznwBaDpvfGn3hTSIdg7Kii4mF2vOPDjBKvqUlOM%3D%3AmL%2Bgq05GB2xXTQ7D9WzQB1%2Bu2hZcQyGFDlSRRr%2Fwwak%3D","user":"--","version":"11.0.2.7"}
{"reqId":"WQGvnNQr9goAACv3gfcAAAAB","remoteAddr":"X.X.X.X","app":"no app in context","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'ALTER TABLE `oc_dav_shares` CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;':\\n\\nSQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(178): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'ALTER TABLE `oc...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Repair\\\/Collation.php(93): Doctrine\\\\DBAL\\\\Statement->execute()\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Repair.php(94): OC\\\\Repair\\\\Collation->run(Object(OC\\\\Repair))\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(280): OC\\\\Repair->run()\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(140): OC\\\\Updater->doUpgrade('11.0.3.2', '11.0.2.7')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/core\\\/ajax\\\/update.php(194): OC\\\\Updater->upgrade()\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":116}","level":3,"time":"2017-04-27T08:45:22+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=z4uRznwBaDpvfGn3hTSIdg7Kii4mF2vOPDjBKvqUlOM%3D%3AmL%2Bgq05GB2xXTQ7D9WzQB1%2Bu2hZcQyGFDlSRRr%2Fwwak%3D","user":"--","version":"11.0.2.7"}
{"reqId":"WQGvnNQr9goAACv3gfcAAAAB","remoteAddr":"X.X.X.X","app":"core","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'ALTER TABLE `oc_dav_shares` CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;':\\n\\nSQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Statement.php(178): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'ALTER TABLE `oc...', Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Repair\\\/Collation.php(93): Doctrine\\\\DBAL\\\\Statement->execute()\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Repair.php(94): OC\\\\Repair\\\\Collation->run(Object(OC\\\\Repair))\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(280): OC\\\\Repair->run()\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(140): OC\\\\Updater->doUpgrade('11.0.3.2', '11.0.2.7')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/core\\\/ajax\\\/update.php(194): OC\\\\Updater->upgrade()\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":116}","level":3,"time":"2017-04-27T08:45:22+00:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=z4uRznwBaDpvfGn3hTSIdg7Kii4mF2vOPDjBKvqUlOM%3D%3AmL%2Bgq05GB2xXTQ7D9WzQB1%2Bu2hZcQyGFDlSRRr%2Fwwak%3D","user":"--","version":"11.0.2.7"}

**Comment by nickvergessen** [comment]
Please post the output of the config command as per issue template

**Comment by Gardakant** [comment]
Here is the info about that mysql table:

mysql> show create table oc_dav_shares;
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table         | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| oc_dav_shares | CREATE TABLE `oc_dav_shares` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `principaluri` varchar(765) DEFAULT NULL,
  `type` varchar(765) DEFAULT NULL,
  `access` smallint(6) DEFAULT NULL,
  `resourceid` int(10) unsigned NOT NULL,
  `publicuri` varchar(765) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `dav_shares_index` (`principaluri`,`resourceid`,`type`,`publicuri`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql>

**Comment by Gardakant** [comment]
@nickvergessen sorry, had forgoten it

root@host1:/var/www/nextcloud/data# cd ..
root@host1:/var/www/nextcloud# sudo -u www-data php occ config:list system
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "instanceid": "523c0911cd7fe",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "dbtype": "mysql",
        "version": "11.0.2.7",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "forcessl": true,
        "trusted_domains": [
            "nextcloud.thefox.com.fr",
            "localhost"
        ],
        "loglevel": 0,
        "mail_from_address": "fox",
        "mail_smtpmode": "smtp",
        "mail_domain": "thefox.com.fr",
        "mail_smtphost": "localhost",
        "mail_smtpport": "25",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\Memcached",
        "overwrite.cli.url": "https:\/\/nextcloud.thefox.com.fr",
        "logtimezone": "UTC",
        "updatechecker": false,
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
        "updater.release.channel": "stable",
        "htaccess.RewriteBase": "\/",
        "dbname": "my_owncloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "has_internet_connection": true,
        "check_for_working_webdav": true,
        "check_for_working_htaccess": true,
        "enable_previews": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
root@host1:/var/www/nextcloud#

**Comment by Gardakant** [comment]
Do you still need some more information ? just let me know

**Comment by nickvergessen** [comment]
Okay, seems to be caused by the mysql version you use.
Can you try adding:
```
[mysqld]
innodb_large_prefix=on
```
to your mysql config?

**Comment by Gardakant** [comment]
Just tried it but still no luck. That raised the limit, but it's still too short

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_dav_shares` CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;':

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 3072 bytes
Update failed

PS: the right syntax is innodb_large_prefix=1

**Comment by Gardakant** [comment]
Do you have any idea left ? my nextcloud is down for a few hours now ;)

**Comment by nickvergessen** [comment]
https://docs.nextcloud.com/server/11/admin_manual/maintenance/restore.html#restore-database

**Comment by nickvergessen** [comment]
I'd recommend to go back to 11.0.2 until a final solution was figured out.

**Comment by Gardakant** [comment]
outch, ok, what's the easiest way to rollbak ? I never had to rollback before

**Comment by nickvergessen** [comment]
Restore the files of 11.0.2 and the database back you did before the update.

The other thing you can try is https://docs.nextcloud.com/server/12/admin_manual/maintenance/mysql_4byte_support.html

**Comment by Gardakant** [comment]
Tried the 4byte support solution, tried to upgrade mysql to 5.6, tried to upgrade mysql to 5.7, all with no luck.
What version of MySQL does 10.0.3 work with ? :)

**Comment by nickvergessen** [comment]
5.7 works just fine here. However I have 5.7 + 4byte thing

**Comment by Gardakant** [comment]
could you show me a "show create table oc_dav_shares;" on your working 5.7 mysqld ?
thx

**Comment by Gardakant** [comment]
and the <declaration> part of <name>*dbprefix*dav_shares</name> into dav/appinfo/database.xml

**Comment by nickvergessen** [comment]
```sql
CREATE TABLE `oc_dav_shares` (
 `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
 `principaluri` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
 `type` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
 `access` smallint(6) DEFAULT NULL,
 `resourceid` int(10) unsigned NOT NULL,
 `publicuri` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
 PRIMARY KEY (`id`),
 UNIQUE KEY `dav_shares_index` (`principaluri`,`resourceid`,`type`,`publicuri`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPRESSED
```

didnt change database.xml

**Comment by Gardakant** [comment]
ok thx

**Comment by Gardakant** [comment]
ROW_FORMAT=COMPRESSED did the trick

**Comment by Gardakant** [comment]
before the alter maybe you shoud check if ROW_FORMAT is COMPRESSED or people could have the max key lengh error

**Comment by Gardakant** [comment]
To me issue can be closed.

**Comment by Gardakant** [comment]
utf8mb4 can break some applications by the way, like Passwords for example :/

SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'utf8_general_ci' is not valid for CHARACTER SET 'utf8mb4'

**Comment by nickvergessen** [comment]
Which password app is this?

**Comment by Gardakant** [comment]
https://github.com/fcturner/passwords

**Comment by Gardakant** [comment]
it's not an official app indeed, maybe you don't care about it anyway :)

**Comment by ChristophWurst** [comment]
> To me issue can be closed.

Okidoke :)
