### ISSUE TITLE
Nextlcloud 28.0.6 is offered although not pblished yet

### ISSUE THREAD

**Issue by hul51u** [nextcloud/server#45492]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I run NC 28.0.5.
Since today (or yesterday) an upgrade to NC 28.0.6 is offered.
NC 28.0.6 is not published yet. https://github.com/nextcloud/server/milestone/265

### Steps to reproduce

1.
2.
3.

### Expected behavior

an upgrade to NC 29 should be offered.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "XXXX.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "28.0.5.1",
        "overwrite.cli.url": "https:\/\/XXXX.de\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_phone_region": "DE",
        "theme": "",
        "loglevel": 3,
        "maintenance": false,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "preview_max_memory": 256,
        "updater.release.channel": "stable",
        "app_install_overwrite": {
            "0": "calendar",
            "1": "impersonate",
            "2": "extract",
            "3": "ransomware_protection",
            "4": "health",
            "7": "metadata"
        },
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "maintenance_window_start": 0
    }
}
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by mlsxlist** [comment]
I see on my Nextcloud 28.0.5 instance that 28.0.6 is offered, but I also see that in can be downloaded from https://download.nextcloud.com/server/releases/nextcloud-28.0.6.zip. Therefore I am wondering if this might be a temporary issue.

**Comment by LM-vb** [comment]
28.0.6 has been released yesterday, see https://github.com/nextcloud/server/releases/tag/v28.0.6

The upgrades (at least major versions, not sure about minor versions) are rolled out in waves, hence the upgrade to 29 is not offered to all Nextcloud instances at the same time. Just wait some time, the upgrade will be offered eventually.

**Comment by kesselb** [comment]
Thanks for the heads up :+1: 

Our release schedule: https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

28.0.6 was released yesterday as planned. 

I will let our release team know about the outstanding milestones update.
