### ISSUE TITLE
[Bug]: instance was upgraded to 28.0.6 -- now offers 29.0.1 but fails to upgrade

### ISSUE THREAD

**Issue by cmigliorini** [nextcloud/server#45491]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

- My NextCloud instance was up to date at 28.0.5
- the updater offered yesterday 2024-05-23 to upgrade to 28.0.6 -- worked like a charm,
- now the updated offers to upgrade to 29.0.1, but immediately says it's complete

Problem: neither version is officially out

### Steps to reproduce

1. use the updater to upgrade to 28.0.6
2. accept updater's offer to upgrade to 29.0.1

### Expected behavior

- Updater should not have offered 28.0.6.
- Updater should not offer 29.0.1, or it should install it

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REDACTED***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "28.0.6.1",
        "overwrite.cli.url": "***REDACTED***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_phone_region": "FR",
        "maintenance": false,
        "maintenance_window_start": 1,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\Krita",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font",
            "OC\\Preview\\Image"
        ],
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_max_filesize_image": 10,
        "filesystem_check_changes": 1,
        "theme": "",
        "loglevel": 1,
        "log_rotate_size": 10485760,
        "memories.exiftool": "\/data\/homes\/***REDACTED***\/nextcloud\/apps\/memories\/bin-ext\/exiftool-amd64-glibc",
        "memories.ffmpeg_path": "\/usr\/bin\/ffmpeg",
        "memories.ffprobe_path": "\/usr\/bin\/ffprobe",
        "memories.no_transcode": false,
        "memories.transcoder": "\/data\/homes\/***REDACTED***\/nextcloud\/apps\/memories\/exiftool-bin\/go-vod-amd64",
        "memories.qsv": false,
        "memories.vod.path": "\/data\/homes\/***REDACTED***\/nextcloud\/apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "preview_max_memory": 1024,
        "memories.vod.disable": false,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
{
    "apps": {
        "app:list": []
    }
}
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by skjnldsv** [comment]
Hmmm, the updater config looks alright :thinking:
https://github.com/nextcloud-releases/updater_server/blob/master/config/config.php

**Comment by skjnldsv** [comment]
Upgrading right now, let's see... :hourglass:

**Comment by skjnldsv** [comment]
Can't reproduce, being on 29.0.1 doesn't give me any new update.
```
Nextcloud Updater - version: v29.0.0-1-g9293bcb dirty

Current version is 29.0.1.
No update available.
Nothing to do.
```

**Comment by cmigliorini** [comment]
Alternatively, this might be considered an issue with 28.0.5 which updated to 28.0.6 although this version does not seem to be generally available (this is a screenshot taken a minute ago on the [Nextcloud page](https://nextcloud.com/changelog/#latest28))

![image](https://github.com/nextcloud/server/assets/3218916/754cc655-c973-4675-952c-4526a778609d)

**Comment by creopard** [comment]
@cmigliorini I just went the same upgrade path as you did: from 28.0.5 -> 28.0.6 -> 29.0.1
and it worked flawlessly.

However, I'm not on PHP 8.1 as in your setup, but on PHP 8.3. And instead on PostgreSQL, I'm on MariaDB.

>     * when I click on "Continue update", I'm sent back to home screen.

When I click on "Continue update", I'm greeted with the expected update screen and the installation finishes successfully:
![nc2901](https://github.com/nextcloud/server/assets/14175483/fe7b9f59-3cb9-45e1-9597-7b5d749c0477)

**Comment by cmigliorini** [comment]
did not realize PHP 8.1 was deprecated.. Tried 8.2 then 8.3 with no luck. Guess damage was done before -- unless it's Postgres... Don't want to go that route though. I'm not totally opposed to a manual upgrade but concerned it might fail as long as I don't understand what's really happening
