### ISSUE TITLE
[Bug]: log_rotate_size in config.php has no effect

### ISSUE THREAD

**Issue by toxpal** [nextcloud/server#45493]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Have multiple installations of NC on the same server. Everything works great except log_rotate_size option; it has no effect (happens with both v28 and v29). Tried these values:

```
'log_rotate_size' => 10 * 1024 * 1024,
'log_rotate_size' => 10485760
```

No effect, I see rotated logs (like nextcloud.log1) that are hundreds of MB in size. Even more interesting: I tried limiting log size to 1 MB (`'log_rotate_size' => 1 * 1024 * 1024`) and after upgrading to 29.0.1 today found that setting was auto-changed to 'log_rotate_size' => 5242880 in all NC installations.

### Steps to reproduce

1. Set log_rotate_size to 1 * 1024 * 1024 or 10 * 1024 * 1024
2. Check size of rotated logs, it exceeds this size.

### Expected behavior

NC should respect log_rotate_size option and never exceed specified size.

### Installation method

None

### Nextcloud Server version

29

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment]
> today found that setting was auto-changed to 'log_rotate_size' => 5242880 in all NC installations.

There is no code in nextcloud/server that would change that value. 

> Check size of rotated logs, it exceeds this size.

Rotation is done by a background job if the logfile is bigger than log_rotate_size. 
So it's expected that the files might grow bigger.

`occ background-job:list | grep Rotate` to find the job id.

`occ background-job:execute <jobId>` to run the job and print some stats.

I'm unable to reproduce, it works just fine with my dev setup.

**Comment by toxpal** [comment]
```
Job class:            OC\Log\Rotate
Arguments:            null
Type:                 job

Last checked:         2024-05-24T15:35:02+00:00
Reserved at:          -
Last executed:        2024-05-24T15:35:02+00:00
Last duration:        0

Job executed!
```

**Comment by oskarb** [comment]
Maybe it has something to do with what is responsible for actually executing the background jobs under Administration->Basic settings

<img width="1152" height="381" alt="Image" src="https://github.com/user-attachments/assets/d2a324d7-9276-49a3-86c3-4d9416f2bb3e" />
