### ISSUE TITLE
27.1.10 release please

### ISSUE THREAD

**Issue by Zweihorn** [nextcloud/server#45511]
Any idea or plans for an update to 2.7.10 in the next days please?

  * https://github.com/nextcloud/server/tags
  * https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

There were no pending bugs found marked for "27.1.10" in your issues by simple search apparently.

🌻

**Comment by MichaIng** [comment]
The PR to push RC2 is here: https://github.com/nextcloud/server/pull/45466
Not all open tasks need to be done for the release, but not sure which ones are blockers.

**Comment by joshtrichards** [comment]
Updater scheduled: https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule
