### ISSUE TITLE
[Bug]: While moving/copying a folder - clicking the New button does not refresh the UI and is unusable.

### ISSUE THREAD

**Issue by bigcat88** [nextcloud/server#45526]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I create a new folder while moving or copying files, the folder doesn’t appear  in Move/Copy dialog box.

However, the folder is created at the destination.

This will highly affect the user experience as move/copy is the core functionality.

### Steps to reproduce

1. Click Move/Copy on any file/folder
2. Once the dialog box appears, create new folder from the dialog box.
3. Folder will not appear in the dialog box until you move to Recent tab and switch back to All Files tab (means NC not refreshing the dialog box after creating the folder)

### Expected behavior

UI got refreshed after folder creation and new folder can be used as a destination

### Installation method

None

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Bug is reported for the version 28.0.5, but I checked 28.0.6 and it is present there too.

**Comment by bigcat88** [comment]
Partially related to this: https://github.com/nextcloud/server/issues/2742

**Comment by susnux** [comment]
https://github.com/nextcloud/server/pull/45575 by @Pytal
