### ISSUE TITLE
Header icons missing color inversion on bright theming

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#4552]
> ![bildschirmfoto vom 2017-04-27 13-46-17](https://cloud.githubusercontent.com/assets/213943/25481992/0e2f17ec-2b50-11e7-9c79-31573b7708aa.png)

App icons are black, right side icons are not

@nextcloud/designers

**Comment by jancborchardt** [comment]
@juliushaertl do we need to add a class here? :)

**Comment by juliushaertl** [comment]
Fixed with https://github.com/nextcloud/server/pull/4559
