### ISSUE TITLE
PHP error message appear after switching cron job from "AJAX"(default) to "Cron"

### ISSUE THREAD

**Issue by creopard** [nextcloud/server#4553]
These kind of error messages appear in the log after(!) switching from an AJAX cron job to a "real" cron job executing every 15 minutes!

### Steps to reproduce
1. Login to nextcloud to admin area
2. Set Cron from AJAX(default) to "Cron"
3. Setup a cron job in webhost admin panel executing every 15 minutes
4. Check logfile

### Expected behaviour
no errors should show up

### Actual behaviour
> Error	PHP	Undefined index: REQUEST_URI at /lib/base.php#177	2017-04-27T13**30**02+0200
> Error	PHP	Undefined index: REQUEST_METHOD at /lib/private/Route/Router.php#79	2017-04-27T13**30**02+0200
> Error	PHP	Undefined index: SCRIPT_NAME at /lib/private/AppFramework/Http/Request.php#713	2017-04-27T13**30**02+0200

> Error	PHP	Undefined index: REQUEST_URI at /lib/base.php#177	2017-04-27T13**15**02+0200
> Error	PHP	Undefined index: REQUEST_METHOD at /lib/private/Route/Router.php#79	2017-04-27T13**15**02+0200
> Error	PHP	Undefined index: SCRIPT_NAME at /lib/private/AppFramework/Http/Request.php#713	2017-04-27T13**15**02+0200

### Server configuration

**Operating system**:
RedHat
**Web server:**
Apache 2.4
**Database:**
10.1.22-MariaDB
**PHP version:**
7.0.18
**Nextcloud version:** (see Nextcloud admin page)
11.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
nextcloud homepage
**Signing status:**
No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.4.1
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### Nextcloud log (data/nextcloud.log)
> Error	PHP	Undefined index: REQUEST_URI at /lib/base.php#177	2017-04-27T13**30**02+0200
> Error	PHP	Undefined index: REQUEST_METHOD at /lib/private/Route/Router.php#79	2017-04-27T13**30**02+0200
> Error	PHP	Undefined index: SCRIPT_NAME at /lib/private/AppFramework/Http/Request.php#713	2017-04-27T13**30**02+0200

> Error	PHP	Undefined index: REQUEST_URI at /lib/base.php#177	2017-04-27T13**15**02+0200
> Error	PHP	Undefined index: REQUEST_METHOD at /lib/private/Route/Router.php#79	2017-04-27T13**15**02+0200
> Error	PHP	Undefined index: SCRIPT_NAME at /lib/private/AppFramework/Http/Request.php#713	2017-04-27T13**15**02+0200

**Comment by MorrisJobke** [comment]
@rullzer @nickvergessen any ideas?

**Comment by joephein** [comment]
I also get similar error messages using webcron. I would like to understand these and how to fix.

```
Error	PHP	Undefined index: REQUEST_URI at /home/joephein/public_html/lib/base.php#177	2017-05-15T14:00:05+0200
Error	PHP	Undefined index: REQUEST_METHOD at /home/joephein/public_html/lib/private/Route/Router.php#79
```

**Comment by nickvergessen** [comment]
comes up from time to time, but apparently those values should always be there:
http://php.net/reserved.variables.server

anyway will add some hardening
