### ISSUE TITLE
Test stability lately worse than normal?

### ISSUE THREAD

**Issue by joshtrichards** [nextcloud/server#45557]
Is it just me or are the tests particularly bad lately?

It's across the board but most notably:

- cypress <-- at first thought it was cache save/restore related but I see that part fails often and things still work so :man_shrugging: 
  - one key here to workaround: rerun *all* cypress jobs not just the failed ones (I think; or maybe this is only important for >24 hour old jobs)
- phpunit-mysql <-- gh workflow doesn't see the mysql container go healthy but it *does* go healthy from what I can tell
  - timing conflict between gh's health checks and the container ones?
- drone <-- group issues (maybe?)
  - random areas
  - silly stuff like being unable to resolve "github.com" 
  - this one is harsh because many of us can't re-run drone so a rebase is required with a full set of tests all over again

**Comment by SystemKeeper** [comment]
> * phpunit-mysql <-- gh workflow doesn't see the mysql container go healthy but it _does_ go healthy from what I can tell

Seems the workflow was not updated to the template:
See https://github.com/nextcloud/.github/blob/master/workflow-templates/phpunit-mysql.yml and https://github.com/nextcloud/spreed/pull/11627
