### ISSUE TITLE
Mentioned user not clickable after posting a comment

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#4555]
Page needs to be reloaded before this is possible.

**Comment by jancborchardt** [comment]
For me it wasn’t even possible for existing comments somehow … :/

**Comment by georgehrke** [comment]
> For me it wasn’t even possible for existing comments somehow … :/

Can you check if there is any js error and if the contacts menu popover is properly added to the DOM?

**Comment by MorrisJobke** [comment]
Fix is in #4746
