### ISSUE TITLE
[Bug]: APPs “Auf Gruppen beschränken” funktioniert nicht - v29.0.1

### ISSUE THREAD

**Issue by Kaelber** [nextcloud/server#45560]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Ich habe v29.0.1 als VM neu installiert und möchte wegen des Teilnehmerkreises die APPs definiert zugänglich machen. Dazu kann ich Gruppen anlegen, damit diese entsprechend bei jeder APP hinterlegt werden können, nachdem ich den Haken “Auf Gruppen beschränken” gesetzt habe.

Zum Problem: Auch wenn mit dem DropDown zunächst “Keine Ergebnisse” angezeigt wird, kann ich mit einem Anfangsbuchstaben doch eine Auswahl provozieren. Daraus lässt sich aber kein Eintrag übernehmen. Wenn ich eine Gruppe ausschreibe, bleibt diese zwar stehen, gehe ich dann auch aktualisieren, ist der Eintrag wieder weg und der Haken auch.

### Steps to reproduce

Auch wenn mit dem DropDown zunächst “Keine Ergebnisse” angezeigt wird, kann ich mit einem Anfangsbuchstaben doch eine Auswahl provozieren. Daraus lässt sich aber kein Eintrag übernehmen. Wenn ich eine Gruppe ausschreibe, bleibt diese zwar stehen, gehe ich dann auch aktualisieren, ist der Eintrag wieder weg und der Haken auch.

### Expected behavior

Beim DropDown sollten alle Gruppen angezeigt werden und wählbar sein. Die Auswahl bleibt bestehen und gespeichert.

### Installation method

Community VM appliance

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by SystemKeeper** [comment]
This is reproducible on master as well. Here's a screencast:

https://github.com/nextcloud/server/assets/1580193/e7f842b6-6f86-49b0-8c11-ac32290235fe

In my tests the groups were still saved, though, only the UI was not updates correctly.

**Comment by joshtrichards** [comment]
Duplicate of #46634
