### ISSUE TITLE
[Bug]: Can't share folders/files from webui, infinite load

### ISSUE THREAD

**Issue by dathbe** [nextcloud/server#45584]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Attempting to share or open file/folder info sidebar results in an infinite circling load.

I have read through #44646 .  I executed `occ maintenance:repair`.  It ran, but did not resolve the problem.  I executed `occ maintenance:update-js`, but got a "Command "maintenance:update-js" is not defined." error.

This comment in that thread seems to be the same issue I'm having https://github.com/nextcloud/server/issues/44646#issuecomment-2061300222.  I don't know if it was resolved.  

### Steps to reproduce

1.Log in
2.Attempt to share or "Open details" 
3.Endless circling in sidebar

### Expected behavior

Sidebar will open to either show file/folder details or sharing options.

### Installation method

Community Docker image

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 22.1 to 22.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "redacted",
            "redacted",
            "redacted"
        ],
        "dbtype": "mysql",
        "version": "29.0.1.1",
        "overwrite.cli.url": "https:\/\/redacted",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "enable_previews": "false",
        "default_phone_region": "ISO 3166-2:US",
        "app_install_overwrite": [
            "bruteforcesettings"
        ],
        "trashbin_retention_obligation": "auto, 90",
        "versions_retention_obligation": "auto, 90",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "upgrade.disable-web": true,
        "maintenance_window_start": 9,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - bruteforcesettings: 2.9.0
  - cloud_federation_api: 1.12.0
  - dav: 1.30.1
  - federatedfilesharing: 1.19.0
  - files: 2.1.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - guests: 3.1.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - nextcloud_announcements: 1.18.0
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - related_resources: 1.4.0
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - terms_of_service: 2.4.0
  - text: 3.10.0
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - twofactor_nextcloud_notification: 3.9.0
  - twofactor_totp: 11.0.0-dev
  - viewer: 2.3.0
  - workflowengine: 2.11.0
Disabled:
  - admin_audit: 1.19.0
  - circles: 29.0.0-dev (installed 22.1.1)
  - comments: 1.19.0 (installed 1.9.0)
  - contactsinteraction: 1.10.0 (installed 1.0.0)
  - dashboard: 7.9.0 (installed 7.0.0)
  - encryption: 2.17.0
  - federation: 1.19.0 (installed 1.9.0)
  - files_downloadlimit: 2.0.0 (installed 2.0.0)
  - files_external: 1.21.0
  - files_pdfviewer: 2.10.0 (installed 2.3.1)
  - files_reminders: 1.2.0 (installed 1.2.0)
  - photos: 2.5.0 (installed 1.1.0)
  - recommendations: 2.1.0 (installed 0.7.0)
  - support: 1.12.0 (installed 1.2.1)
  - survey_client: 1.17.0 (installed 1.7.0)
  - suspicious_login: 7.0.0
  - systemtags: 1.19.0 (installed 1.9.0)
  - updatenotification: 1.19.1 (installed 1.17.0)
  - user_ldap: 1.20.0
  - user_status: 1.9.0 (installed 1.2.0)
  - weather_status: 1.9.0 (installed 1.2.0)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
No related Nextcloud log errors or warnings that I'm seeing.
```

### Additional info

I am using the Linuxserver docker image.

My browser console logs are here (one from a Firefox-based browser, one from a Chrome-based browser):
![2024-05-30 07_45_31-Files - Beffa Law — LibreWolf](https://github.com/nextcloud/server/assets/14321825/2eb1839e-c969-4b51-bdb4-11b731145b5b)
![2024-05-30 07_48_31-Files - Beffa Law - Profile 1 - Microsoft​ Edge](https://github.com/nextcloud/server/assets/14321825/9c741e2b-9693-426c-99f9-f5e8f6c69fa1)

No issues listed in Security setup & warnings section of admin settings.

All my apps are updated, and I am not running Talk.

**Comment by susnux** [comment]
> . I executed `occ maintenance:update-js`, but got a "Command "maintenance:update-js" is not defined." error.

The correct name is 
`occ maintenance:mimetype:update-js`

**Comment by dathbe** [comment]
> The correct name is
> `occ maintenance:mimetype:update-js`

Didn't work.  Thanks though.

**Comment by susnux** [comment]
Can you please check your browser log for any failed requests? Especially JS?

**Comment by dathbe** [comment]
I'm not super familiar with browser logs, but in the Network tab (chrome-based browser), I get the following 404:

```
Request URL: https://fqd.tld/js/core/merged-template-prepend.js?v=f838eaa8-47
Request Method: GET
Status Code: 404 Not Found
Remote Address: 23.126.190.47:443
Referrer Policy: strict-origin-when-cross-origin
```

I do have some special headers set on my instance.  I'm going to try removing them and will let you know if that helps.

**Comment by dathbe** [comment]
> I'm going to try removing them and will let you know if that helps.

No luck.  I get the same error even when the custom headers are removed, and even when I access the instance directly (i.e., not through a reverse proxy...which is where the custom headers are implemented).

**Comment by joshtrichards** [comment]
https://github.com/linuxserver/docker-nextcloud/issues/410#issuecomment-2016605565

**Comment by susnux** [comment]
So it seems you could resolve the issue: https://github.com/nextcloud/server/issues/44128#issuecomment-2248920570

**Comment by dathbe** [comment]
Yes.
