### ISSUE TITLE
Email action added to contacts menu when adding an avatar.

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/server#4558]
A email action (empty email) is added to a user when you add an avatar picture to that user.

User 2 has only an avatar but no email address.
![screen shot 2017-04-27 at 17 19 41](https://cloud.githubusercontent.com/assets/4638605/25490858/722d0f42-2b6e-11e7-87b1-e1083add7a57.png)

**Comment by ChristophWurst** [comment]
I can reproduce this. Seems to only happen with local users, not with the ones from the contacts app. Apparently an empty email address is saved when the avatar image is updated.
