### ISSUE TITLE
[Bug]: Share Expire Not Based On Default Time Zone

### ISSUE THREAD

**Issue by alperozturk96** [nextcloud/server#45595]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The share expiry determination is being conducted based on UTC time, regardless of default time zone.

### Steps to reproduce

1. Set 'default_timezone' => 'Asia/Tokyo'
2. Check share expiration time

### Expected behavior

Share Expire must be based on given default time zone.

### Nextcloud Version

28.0.4

**Comment by joshtrichards** [comment]
Related PR: #46097

**Comment by alperozturk96** [comment]
Tested with v29.0.5.1 issue solved.
