### ISSUE TITLE
[Bug]: Extremely slow response to start loading the home page

### ISSUE THREAD

**Issue by ibahnasy** [nextcloud/server#45599]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nextcloud takes very long time to just starts loading the home page.

### Steps to reproduce

1. Type Nextcloud URL in the browser and hit enter.
2. Wait until it starts loading.

### Expected behavior

Server specs are enough and I have enabled PHP and static content caching so response time much faster than that.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "loglevel": 1,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.example.com",
        "trusted_domains": [
            "example.com",
            "nextcloud.example.com",
            "localhost",
            "Public_IP",
            "VPN_IP",
            "127.0.0.1"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin",
            "Users",
            "Fresh_Registration"
        ],
        "twofactor_enforced_excluded_groups": [],
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "allow_local_remote_servers": true,
        "mail_smtpsecure": "ssl",
        "mail_smtpstreamoptions": {
            "ssl": {
                "allow_self_signed": true,
                "verify_peer": false,
                "verify_peer_name": false
            }
        },
        "maintenance_window_start": 1,
        "app_install_overwrite": [
            "xwiki"
        ],
        "maintenance": false,
        "theme": "",
        "enforce_theme": "",
        "updater.release.channel": "stable"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - bruteforcesettings: 2.9.0
  - calendar: 4.7.4
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - collectives: 2.11.0
  - comments: 1.19.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - cospend: 1.6.1
  - dashboard: 7.9.0
  - dav: 1.30.1
  - deck: 1.13.0
  - encryption: 2.17.0
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_downloadlimit: 2.0.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - integration_jira: 1.1.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - mail: 3.6.1
  - nextcloud_announcements: 1.18.0
  - notes: 4.10.0
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - passwords: 2024.5.10
  - phonetrack: 0.8.1
  - photos: 2.5.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - qownnotesapi: 24.4.0
  - recommendations: 2.1.0
  - registration: 2.4.0
  - related_resources: 1.4.0
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - spreed: 19.0.1
  - support: 1.12.0
  - survey_client: 1.17.0
  - systemtags: 1.19.0
  - tasks: 0.16.0
  - text: 3.10.0
  - theming: 2.4.0
  - theming_customcss: 1.16.0
  - twofactor_backupcodes: 1.18.0
  - twofactor_totp: 11.0.0-dev
  - updatenotification: 1.19.1
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0
  - xwiki: 0.1.2
Disabled:
  - activity: 2.21.1 (installed 2.20.0)
  - admin_audit: 1.19.0
  - breezedark: 28.0.0 (installed 28.0.0)
  - files_external: 1.21.0
  - registertocontact: 0.0.1 (installed 0.0.1)
  - secrets: 1.5.2 (installed 1.5.2)
  - suspicious_login: 7.0.0 (installed 6.0.0)
  - text2image_stablediffusion: 1.0.2 (installed 1.0.2)
  - user_ldap: 1.20.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

See attached file below.

### Additional info

![Screenshot from 2024-05-31 13-28-47](https://github.com/nextcloud/server/assets/19417705/d0b3f4e0-3eea-4612-97c7-5e360e0ade75)

[nextcloud.log](https://github.com/user-attachments/files/15512750/nextcloud.log)

**Comment by joshtrichards** [comment]
> Nextcloud takes very long time to just starts loading the home page.

Since when? When did this behavior start for you? We need further context.

> and I have enabled PHP and static content caching

Can you be more specific? Are you saying you're not using our standard nginx config? What PHP values have you changed from their defaults?

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

I'm not aware about a general issue with 29 and the response times and also the response times on my development setup, with a good number of apps, is within the usual range. 

There are a couple of addresses in the trusted_domains list. In such scenarios, it sometimes happens that a request takes a wrong route. That would be my starting point to investigate. 

As it's unclear, if that's a bug, I would like to ask you to raise your question at https://help.nextcloud.com

**Comment by ibahnasy** [comment]
> > Nextcloud takes very long time to just starts loading the home page.
> 
> Since when? When did this behavior start for you? We need further context.
> 
> > and I have enabled PHP and static content caching
> 
> Can you be more specific? Are you saying you're not using our standard nginx config? What PHP values have you changed from their defaults?

This issue started since one of the updates in the 28 releases and till today.

I'm using the standard nginx configuration and all performance tuning recommendations.

**Comment by ibahnasy** [comment]
> There are a couple of addresses in the trusted_domains list. In such scenarios, it sometimes happens that a request takes a wrong route. That would be my starting point to investigate.

I never had trusted_domain list, just added them recently as a suggested workaround to enhance performance which didn't work too.
