### ISSUE TITLE
S3 causes an issue when no hostname is set.

### ISSUE THREAD

**Issue by thelfensdrfer** [nextcloud/server#45637]
https://github.com/nextcloud/server/blob/3bb0c9b012f0e87ccddd37e4782d3fb5ae2025a6/lib/private/Files/ObjectStore/S3ConnectionTrait.php#L74

But according to the docs, a hostname doesn't have to be set.

Message in the log: `Undefined array key "hostname" at /var/www/html/lib/private/Files/ObjectStore/S3ConnectionTrait.php#74`

Version: 29.0.1

**Comment by kesselb** [comment]
I guess we need a isset check. 
Mind to send a pull request?

cc @icewind1991 @artonge

**Comment by joshtrichards** [comment]
Our integration tests didn't catch it I guess because we test against Minio with a `hostname` set rather than AWS. 

Fix pending in #45649.

Thanks for reporting @thelfensdrfer. 

If you are able, appreciate a test of the fix in your environment.

**Comment by stszap** [comment]
We are on 29.0.1 too and are having the same problem. We can't do a clean install, unfortunately, but I was able to manually patch the file in question the same way ass in the PR above and the error messages stopped.
