### ISSUE TITLE
[Bug]: Naming File Version a number removes ability to edit version

### ISSUE THREAD

**Issue by grnd-alt** [nextcloud/server#45642]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When naming the version of a file to a number: e.g. 1.0
1) it gets renamed to 1 after refresh
2) the version can't be renamed as the input field is not rendered

Console throws:
t.innerversionlabel.trim is not a function
and: 
this.$refs.labelInput is not defined

### Steps to reproduce

1. create a file
2. open sharing side menu
3. go to versions
4. click `edit version name` in three dots menu
5. insert a float
6. reload page
7. try to edit version name

### Expected behavior

version name should stay editable
probably 1.0 should not be renamed to 1

### Nextcloud Server version

27, 28,29 master

**Comment by joshtrichards** [comment]
Reproduced in 29.0.1. Thanks for the report!

**Comment by sanskar-soni-9** [comment]
Hi @joshtrichards, looking for my first contribution

I found that server is saving and responding with correct version 
![240608_17h02m59s_screenshot](https://github.com/nextcloud/server/assets/88997516/ceef32ef-9c9a-46c0-8ea3-f0896c8502d1)

but it gets converted to int tpe in received response object
https://github.com/nextcloud/server/blob/49c42c36aedf69ea8393c6cbc4387e04adc84761/apps/files_versions/src/utils/versions.ts#L42

![240608_17h04m17s_screenshot](https://github.com/nextcloud/server/assets/88997516/7757fa9b-465d-487c-ae98-065628717994)

I fixed the renaming thing by formatting it to string in formatVersion function
