### ISSUE TITLE
Regression: automatic text color based on background does not apply to all CSS elements like previously

### ISSUE THREAD

**Issue by Gibibit** [nextcloud/server#45673]
**Describe the bug**
Using the Nextcloud snap, after the application being automatically updated a lot of text is suddenly black where previously it was white.

The theme being used is "System Default Theme", which sets it to use the "Dark theme" in my case.

**To Reproduce**
Use a dark background in Nextcloud.

**Expected behavior**
For the default font colors to stay the same in a minor patch.

**Screenshots**
Top left: the navigation bar color after being adjusted with a custom CSS override. These were also black after the update, and are only white due to my adjustments.

In de middle and top right: the dashboard header and system icons have become unreadable due to being black.
![image](https://github.com/nextcloud/richdocuments/assets/1710540/5b29750a-0d31-4a38-8ef7-385dff67424f)

The dashboard panels are still fine
![image](https://github.com/nextcloud/richdocuments/assets/1710540/5473e678-51a5-4dc2-af2e-b98baf2acf64)

**Client details:**
 - Firefox

## Server details

**Operating system**:
Linux 4.19.219-odroid-arm64 aarch64

**Database:**
Type: mysql
Version: 8.0.37

**PHP version:**
8.2.18

**Nextcloud version:**
Nextcloud 28.0.6

**Comment by susnux** [comment]
On Nextcloud 29 and older the color of the icons is calculated from the primary color.
Thus you need to select a dark primary color tp have white icons.
This is changed on Nextcloud 30 where background and primary color are different things.

Things are improved in 28.0.7 but for custom images until Nextcloud 30 you have to wisely choose a primary color. 

Ref https://github.com/nextcloud/server/pull/45552
