### ISSUE TITLE
[Bug]: Change Warn on excessive memory consumption in background jobs to info

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/server#45682]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description
Log file it getting spammed with these warning. i would recommended this to  info and not warning, 
Used memory grew by more than 10 MB when executing job OC\FilesMetadata\Job\UpdateSingleMetadata (id: 175902, arguments: ["usernae",1042806]): 26.1 MB (before: 10.7 MB)

### Steps to reproduce

N/A

### Expected behavior

Should not see this as a warning more info then a warning 

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

![image](https://github.com/nextcloud/server/assets/59488153/31ed58af-fe9d-4efa-b109-c1e9ebde33bf)

**Comment by solracsf** [comment]
Already on its way at https://github.com/nextcloud/server/pull/45530

**Comment by AndyXheli** [comment]
Hey @joshtrichards sorry to bother . 

Thanks for the update so under the Nc29 backport till shows 10mb but under the original pull the 10mb was changed to 50 ? 

![image](https://github.com/nextcloud/server/assets/59488153/d0ad3e7d-2ecc-41dd-8aa3-6678cbc25d22)

**Comment by joshtrichards** [comment]
@AndyXheli Indeed. Finally got around to addressing the failed automated backport draft just now. #45843. Will be merged into v29 branch after tests pass.

**Comment by AndyXheli** [comment]
Hi still seeing this on NC 29.0.4

```
{"reqId":"kImcJ5WNoR8EST80crIE","level":2,"time":"2024-07-28T21:17:03-05:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Cron job used more than 300 MB of ram after executing job OCA\\Recognize\\BackgroundJobs\\ClusterFacesJob (id: 226426, arguments: {\"userId\":\"admin\"}): 652.1 MB (before: 99.5 MB)","userAgent":"--","version":"29.0.4.1","data":{"app":"cron"},"id":"66a7bdec119fb"}

{"reqId":"IXdi9NgDcaj3o5rTidfQ","level":2,"time":"2024-07-28T21:01:47-05:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Cron job used more than 300 MB of ram after executing job OCA\\Recognize\\BackgroundJobs\\ClusterFacesJob (id: 226389, arguments: {\"userId\":\"admin\"}): 625.5 MB (before: 10.6 MB)","userAgent":"--","version":"29.0.4.1","data":{"app":"cron"},"id":"66a7bdec11a7f"}

```

**Comment by joshtrichards** [comment]
` OCA\\Recognize\\BackgroundJobs\\ClusterFacesJob `

@AndyXheli That's a job in the Recognize app. The issue here was just to clean things up to avoid too many false positives. The logging is legitimate. Issues with individual jobs need to diagnosed in relation to the individual apps providing the jobs to assess whether such high memory usage is expected or not/etc.

**Comment by AndyXheli** [comment]
Hi @joshtrichards thank you for the detailed explanation. Much appreciated

**Comment by luxzg** [comment]
Thanks Josh for explanation, but I am so going to swap that `$logger->` to debug in my instance first thing in the morning. Honestly, this is exactly material for debugging, for devs to get feedback and optimize or fix if possible. Average user will just have huge log file for nothing.

If it helps my culprit is `Cron job used more than 300 MB of ram after executing job OCA\Maps\BackgroundJob\AddPhotoJob` but even if it gets noticed I doubt it will be improved in next ~2 years.

**Comment by joshtrichards** [comment]
> If it helps my culprit is Cron job used more than 300 MB of ram after executing job OCA\Maps\BackgroundJob\AddPhotoJob but even if it gets noticed I doubt it will be improved in next ~2 years.

@luxzg If you feel up to it, probably worth reporting at https://github.com/nextcloud/maps since we can't address that here in `server`.
