### ISSUE TITLE
[Bug]: Disabling the preview does not stop the creation of the folder tree

### ISSUE THREAD

**Issue by devsamt** [nextcloud/server#45697]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I am encountering an issue: my NextCloud instance is installed on an ext4 partition with limited inode resources. The preview feature generates a very large number of folders that consume all available inodes and block the entire system. Despite disabling the preview feature in the configuration file, this folder tree continues to be created empty. Could you please fix the problem quickly?

For more information:
https://help.nextcloud.com/t/the-preview-feature-consumes-too-many-inodes/194129

### Steps to reproduce

1. `sudo -u www-data php /var/www/nextcloud/occ files:scan-app-data`
2. `df -i /dev/sda1`
3. `systemctl stop apache2`
4. `rm -rf /var/www/nextcloud/data/appdata_xxx/preview/*`
5. `sudo -u www-data php /var/www/nextcloud/occ files:scan-app-data`
6. `df -i /dev/sda1`
7. `systemctl start apache2`

### Expected behavior

Disabling the preview feature stops the creation of all files and folders, not just files.

### Installation method

None

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment]
True. 

With enabled_previews = false, no preview providers are registered and therefore not previews are generated. But currently some code before, like requesting a generator instance, creating the folder structure, BeforePreviewFetchedEvent still runs. 

The patch below should improve it. 

Wdyt @st3iny @come-nc? 

```
Index: lib/private/PreviewManager.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lib/private/PreviewManager.php b/lib/private/PreviewManager.php
--- a/lib/private/PreviewManager.php	(revision 858ba27835ed3e71ad34c9cc933467e98db14adf)
+++ b/lib/private/PreviewManager.php	(date 1717704971130)
@@ -50,6 +50,7 @@
 	private IServerContainer $container;
 	private IBinaryFinder $binaryFinder;
 	private IMagickSupport $imagickSupport;
+	private bool $enablePreviews;
 
 	public function __construct(
 		IConfig                  $config,
@@ -73,6 +74,7 @@
 		$this->container = $container;
 		$this->binaryFinder = $binaryFinder;
 		$this->imagickSupport = $imagickSupport;
+		$this->enablePreviews = $config->getSystemValueBool('enable_previews', true);
 	}
 
 	/**
@@ -86,7 +88,7 @@
 	 * @return void
 	 */
 	public function registerProvider($mimeTypeRegex, \Closure $callable): void {
-		if (!$this->config->getSystemValueBool('enable_previews', true)) {
+		if (!$this->enablePreviews) {
 			return;
 		}
 
@@ -101,7 +103,7 @@
 	 * Get all providers
 	 */
 	public function getProviders(): array {
-		if (!$this->config->getSystemValueBool('enable_previews', true)) {
+		if (!$this->enablePreviews) {
 			return [];
 		}
 
@@ -158,6 +160,7 @@
 	 * @since 11.0.0 - \InvalidArgumentException was added in 12.0.0
 	 */
 	public function getPreview(File $file, $width = -1, $height = -1, $crop = false, $mode = IPreview::MODE_FILL, $mimeType = null) {
+		$this->throwIfPreviewsDisabled();
 		$previewConcurrency = $this->getGenerator()->getNumConcurrentPreviews('preview_concurrency_all');
 		$sem = Generator::guardWithSemaphore(Generator::SEMAPHORE_ID_ALL, $previewConcurrency);
 		try {
@@ -181,6 +184,7 @@
 	 * @since 19.0.0
 	 */
 	public function generatePreviews(File $file, array $specifications, $mimeType = null) {
+		$this->throwIfPreviewsDisabled();
 		return $this->getGenerator()->generatePreviews($file, $specifications, $mimeType);
 	}
 
@@ -191,7 +195,7 @@
 	 * @return boolean
 	 */
 	public function isMimeSupported($mimeType = '*') {
-		if (!$this->config->getSystemValueBool('enable_previews', true)) {
+		if (!$this->enablePreviews) {
 			return false;
 		}
 
@@ -216,7 +220,7 @@
 	 * Check if a preview can be generated for a file
 	 */
 	public function isAvailable(\OCP\Files\FileInfo $file): bool {
-		if (!$this->config->getSystemValueBool('enable_previews', true)) {
+		if (!$this->enablePreviews) {
 			return false;
 		}
 
@@ -452,4 +456,13 @@
 			});
 		}
 	}
+
+	/**
+	 * @throws NotFoundException if preview generation is disabled
+	 */
+	private function throwIfPreviewsDisabled(): void {
+		if (!$this->enablePreviews) {
+			throw new NotFoundException('Previews disabled');
+		}
+	}
 }
```

**Comment by st3iny** [comment]
@kesselb I like it. I also tested it locally and it works fine. Do you mind opening a PR?

**Comment by didierm** [comment]
I applied the patch to 29.0.1, and it works beautifully.

We were hit by this in our use case : 
small (< 2GB) nextcloud data volumes (no local storage, many TBs of external (local network) storage), filling up with inodes (512 bytes/inode).

Thanks !

**Comment by pbuergi** [comment]
same problem here. Is there a fix coming for normal patching? (stable) Or how do we have to implement this?

**Comment by susnux** [comment]
@kesselb would you mind creating a PR from your patch?
