### ISSUE TITLE
Can't create calendars in webinterface with IE11 on Windows 10

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/server#457]
### Steps to reproduce
1. Install a fresh nextcloud
2. activate the calendar
3. now you can't create a new calendar (you can do nothing, you see every time a loading bar)

### Expected behaviour
create a new calendar or create Events in a calendar, but first I Need to create a calendar -> not possible

### Actual behaviour
a loading bar is shown all the time

### Server configuration
**Operating system**:
Ubuntu

**Web server:**
Aapache 2

**Database:**
MySQL 5.6

**PHP version:**
7.0.8

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 9.0.53 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
https://nextcloud.com/install/

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors have been found.
```
</details>

**List of activated apps:**
<details>
Default apps. I've only installed the calendar

```
If you have access to your command line run e.g.:
I don't have, it is a Webspace from a webhoster
```
</details>

**The content of config/config.php:**
default
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Internet Explorer 11

**Operating system:**
Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>
```
no permission to it
![calerror](https://cloud.githubusercontent.com/assets/1473674/16981273/2585e632-4e6a-11e6-9a78-811ea9ba5e3d.PNG)
![calerror](https://cloud.githubusercontent.com/assets/1473674/16981280/2d305b9c-4e6a-11e6-9632-d4e826d6e41a.PNG)
![calerror](https://cloud.githubusercontent.com/assets/1473674/16981285/31949a5e-4e6a-11e6-9204-581a565d1ff7.PNG)



```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
all 15 minutes: opendir(/tmp): failed to open dir: Permission denied at /www/htdocs/customer138958/cloud/lib/private/tempmanager.php#187
```
</details>

![calerror](https://cloud.githubusercontent.com/assets/1473674/16981289/3a5c2260-4e6a-11e6-81e7-1835639870a3.PNG)

**Comment by Dennis1993** [comment]
Same Problem in Tasks. Tasks not showing in IE11 and Edge. In Firefox or Safari it works!

**Comment by nickvergessen** [comment]
@georgehrke

**Comment by georgehrke** [comment]
IE is not supported
