### ISSUE TITLE
[Bug]: File versions expiration does not work properly

### ISSUE THREAD

**Issue by carhe** [nextcloud/server#45707]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The version expiration scheme described in <https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/file_versioning.html> does not work in all scenarios due to an incomplete condition in <https://github.com/nextcloud/server/blob/3bb0c9b012f0e87ccddd37e4782d3fb5ae2025a6/apps/files_versions/lib/Storage.php#L932> The condition should match the one in <https://github.com/nextcloud/server/blob/3bb0c9b012f0e87ccddd37e4782d3fb5ae2025a6/apps/files_versions/lib/Storage.php#L601>

### Steps to reproduce

1. set `versions_retention_obligation => 'auto, D'`
2. add and update a file several times to generate some versions in files_versions/...
3. wait some time and update again

Triggered by step 3, some of the existing versions should get removed following the [documented scheme](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/file_versioning.html). But this does not happen depending on factors that have to be clarified (see below). However, the expiration triggered by D works as expected.

### Expected behavior

Old versions get deleted as described in the [scheme](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/file_versioning.html).

### Installation method

Community Docker image

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

The reason for the problems is the incomplete condition mentioned in the bug description. After adding some log messages to Storage.php, I found that `$versionEntity->getMetadataValue('label')` returns `null` in my case, causing the deletion step to be skipped. I adjusted the condition to the mentioned one in `expireOlderThanMaxForUser()`, then expiration worked as expected.

I have no knowledge about the internal structures of Nextcloud, so I cannot tell under which circumstances `getMetadataValue('label')` returns `null`, but anyhow, I think the two mentioned conditions should be consistent.

**Comment by solracsf** [comment]
Cc @artonge

**Comment by carhe** [comment]
Sorry for the delay. So, I created PR #45932.
