### ISSUE TITLE
[Bug]: Numerical accounts show all files/folders in "Shared" status in the web UI

### ISSUE THREAD

**Issue by ywtoly** [nextcloud/server#45723]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Use accounts with all numerical symbols (e.g. 11223344), after logging in, all files and folders will be displayed as shared, and the first symbol of the account will be in English letters, which is normal.
![aaaaaaaa](https://github.com/nextcloud/server/assets/38350423/ebbade81-cb50-4e61-a880-6cfa2f7f8eee)

### Steps to reproduce

1. Login to the backend
2. Add users
3. Set the user account to 112233
4. Other arbitrary
5. Login using 112233
6. View the file list, which shows that all files are shared

### Expected behavior

"Shared" should not appear

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Thanks for the report! 
Reproduced.

**Comment by sanskar-soni-9** [comment]
Another string - number error, (for me 😁)

**Comment by skjnldsv** [comment]
@susnux this require a backport for 29 :warning:
