### ISSUE TITLE
occ upgrade from 11.0.2 to 11.0.3 showing no upgrade

### ISSUE THREAD

**Issue by paolomeraviglia** [nextcloud/server#4573]
OS: debian 8
php version 7.1

from web console I can use update app, from cli if I use occ upgrade, it says "nextcloud is already latest version".

**Comment by MorrisJobke** [comment]
> from cli if I use occ upgrade, it says "nextcloud is already latest version".

This only executes the upgrade migration code. But you could execute the updater.phar in the updater folder to update the code from the CLI.
