### ISSUE TITLE
Show default_enabled apps in apps management

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#4580]
With #3195 we have made the apps management more clearly and its more easy to find apps, even if you have enabled dozens of them ... For me, it is not understandable that apps which are default_enabled (files, dav, ..) are not shown in the apps management. Of course you can not disbale them, but as they are active - they should be listed, with all the given information (author, version number) ... what do you think? @MorrisJobke @nickvergessen @LukasReschke 

This is of course only for those apps, for which #4454 (app bundles + app store instead of shipping) isn't an option 😉

**Comment by nickvergessen** [comment]
I think you mean force enabled?

Default enabled is another story

**Comment by MariusBluem** [comment]
> I think you mean force enabled?

fair enough 😜

**Comment by eppfel** [comment]
But how do you manage those apps then? It is the apps management and as I understand those "forceemabled" apps do not have to be mangaged...
No updates, no diabling, just comes with the server release itself...

So, I propose leaving it as it is, because we introduce content that is not relevant.?

**Comment by jancborchardt** [comment]
I fully agree with @eppfel, we should leave it as it is. You can not disable or manage these apps anyway, so they should not clutter the list. We have enough small »apps« which are more like settings or features already.
