### ISSUE TITLE
Apps-Management doesn't show missing dependencies

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/server#4581]
Nextcloud 12 on the left, Nextcloud 11 on the right
<img width="1920" alt="apps - nextcloud chromium today at 2 18 43 pm" src="https://cloud.githubusercontent.com/assets/1250540/25528347/a2882c26-2c1d-11e7-8877-b72497e71462.png">

Nextcloud 12 only shows that you can't enable LDAP.
Nextcloud 11 gives you a reason why you can't enable LDAP.

I'd propose a tooltip on the enable button that shows missing dependencies

cc @nextcloud/designers

**Comment by jancborchardt** [comment]
I’d say it should be displayed directly, like the »New version available« message:
![capture du 2017-04-29 17-47-21](https://cloud.githubusercontent.com/assets/925062/25556804/eb321acc-2d03-11e7-8abb-b4ac6cc00b35.png)
(Cause a tooltip is quite hidden.)
Actually the `<div class="warning">` in the `<div class="actions">` can be used for that.

@georgehrke can you open a pull request for it?

**Comment by MorrisJobke** [comment]
Let's fix this first in master and then backport it

**Comment by MorrisJobke** [comment]
Fixed in #9565
