### ISSUE TITLE
Incorrect sorting by names of files with underscore

### ISSUE THREAD

**Issue by grenzverkehr** [nextcloud/server#45829]
Since version 29.0.2 files with underscores are sorted incorrectly.

![Unbenannt](https://github.com/nextcloud/server/assets/50242159/a6a71786-b489-487b-af4e-14bf18c43786)

### correct sorting (NC 29.0.0.19):
name.txt
name_01.txt
name_02.txt
name_03.txt

### incorrect sorting (NC 29.0.2.2):
name_01.txt
name_02.txt
name_03.txt
name.txt

**Comment by kesselb** [comment]
Related: https://github.com/nextcloud/server/pull/45419

cc @susnux

**Comment by grenzverkehr** [comment]
In 29.0.3 it is still not fixed.
Is https://github.com/nextcloud-libraries/nextcloud-files/pull/984 in 29.0.3 not included?

**Comment by susnux** [comment]
will be fixed with 29.0.4

**Comment by grenzverkehr** [comment]
Unfortunately, the problem still exists in version 29.0.4.

**incorrect sorting (NC 29.0.4.1):**

name_01.txt
name_02.txt
name_03.txt
name.txt

**Comment by susnux** [comment]
Sadly it got delayed a bit, the server PR is:
https://github.com/nextcloud/server/pull/46690
