### ISSUE TITLE
"es_MX" should be called like "Spanish (Mexico)"

### ISSUE THREAD

**Issue by benediktg** [nextcloud/server#4582]
In the personal nextcloud settings at the language selection there is an entry called "es_MX" which should be called like "Spanish (Mexico)".

![screenshot_20170428_145543](https://cloud.githubusercontent.com/assets/14795615/25529814/ff371940-2c23-11e7-9da2-191c14e6bbfe.png)

cc @MorrisJobke

**Comment by MorrisJobke** [comment]
Perfecto

**Comment by MorrisJobke** [comment]
I will take care of this. I guess we need to add a translators hint for this special translation item to brief the translators.

**Comment by MorrisJobke** [comment]
Fixed - the help text was already there, but the translation was changed wrongly 🙈
