### ISSUE TITLE
ErrorCall to a member function getUID() on nullError while running background job OCA\Theming\Jobs\MigrateBackgroundImages (id: 326308, arguments: {"stage":"prepare"})

### ISSUE THREAD

**Issue by kmorber** [nextcloud/server#45834]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello,

i receive the following error in log, frequently.

Nextcloud 29.0.2

ErrorCall to a member function getUID() on nullError while running background job OCA\Theming\Jobs\MigrateBackgroundImages (id: 326308, arguments: {"stage":"prepare"})

### Steps to reproduce

Fresh install

### Expected behavior

please fix this error

### Installation method

None

### Nextcloud Server version

29

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other

**Comment by joshtrichards** [comment]
Please provide the actual raw log entry. We need the full stack trace.

**Comment by kmorber** [comment]
{"reqId":"vHakpZoZU4kkV4sddWyW","level":3,"time":"2024-06-12T23:20:03+02:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job OCA\\Theming\\Jobs\\MigrateBackgroundImages (id: 326336, arguments: {\"stage\":\"prepare\"})","userAgent":"--","version":"29.0.2.2","exception":{"Exception":"Error","Message":"Call to a member function getUID() on null","Code":0,"Trace":[{"function":"OCA\\FileUploadNotification\\Hooks\\{closure}","class":"OCA\\FileUploadNotification\\Hooks\\UserHooks","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/lib/private/Hooks/EmitterTrait.php","line":105,"function":"call_user_func_array","args":[["Closure"],["*** sensitive parameters replaced ***"]]},{"file":"/var/www/html/nextcloud/lib/private/Hooks/PublicEmitter.php","line":40,"function":"emit","class":"OC\\Hooks\\BasicEmitter","type":"->","args":["\\OC\\Files","postWrite",["*** sensitive parameters replaced ***"]]},{"file":"/var/www/html/nextcloud/lib/private/Files/Node/Root.php","line":150,"function":"emit","class":"OC\\Hooks\\PublicEmitter","type":"->","args":["\\OC\\Files","postWrite",["*** sensitive parameters replaced ***"]]},{"file":"/var/www/html/nextcloud/lib/private/Files/Node/Node.php","line":133,"function":"emit","class":"OC\\Files\\Node\\Root","type":"->","args":["\\OC\\Files","postWrite",["*** sensitive parameters replaced ***"]]},{"file":"/var/www/html/nextcloud/lib/private/Files/Node/File.php","line":77,"function":"sendHooks","class":"OC\\Files\\Node\\Node","type":"->","args":[["postWrite"]]},{"file":"/var/www/html/nextcloud/lib/private/Files/SimpleFS/SimpleFile.php","line":92,"function":"putContent","class":"OC\\Files\\Node\\File","type":"->","args":["[]"]},{"file":"/var/www/html/nextcloud/apps/theming/lib/Jobs/MigrateBackgroundImages.php","line":175,"function":"putContent","class":"OC\\Files\\SimpleFS\\SimpleFile","type":"->","args":["[]"]},{"file":"/var/www/html/nextcloud/apps/theming/lib/Jobs/MigrateBackgroundImages.php","line":100,"function":"storeUserIdsToProcess","class":"OCA\\Theming\\Jobs\\MigrateBackgroundImages","type":"->","args":[[]]},{"file":"/var/www/html/nextcloud/apps/theming/lib/Jobs/MigrateBackgroundImages.php","line":79,"function":"runPreparation","class":"OCA\\Theming\\Jobs\\MigrateBackgroundImages","type":"->","args":[]},{"file":"/var/www/html/nextcloud/lib/public/BackgroundJob/Job.php","line":80,"function":"run","class":"OCA\\Theming\\Jobs\\MigrateBackgroundImages","type":"->","args":[["prepare"]]},{"file":"/var/www/html/nextcloud/lib/public/BackgroundJob/QueuedJob.php","line":57,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->","args":[["OC\\BackgroundJob\\JobList"]]},{"file":"/var/www/html/nextcloud/lib/public/BackgroundJob/QueuedJob.php","line":47,"function":"start","class":"OCP\\BackgroundJob\\QueuedJob","type":"->","args":[["OC\\BackgroundJob\\JobList"]]},{"file":"/var/www/html/nextcloud/cron.php","line":176,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->","args":[["OC\\BackgroundJob\\JobList"]]}],"File":"/var/www/html/nextcloud/apps/file_upload_notification/lib/Hooks/UserHooks.php","Line":59,"message":"Error while running background job OCA\\Theming\\Jobs\\MigrateBackgroundImages (id: 326336, arguments: {\"stage\":\"prepare\"})","exception":[],"CustomMessage":"Error while running background job OCA\\Theming\\Jobs\\MigrateBackgroundImages (id: 326336, arguments: {\"stage\":\"prepare\"})"},"id":"666a12cfd2bd8"}

**Comment by joshtrichards** [comment]
`apps/file_upload_notification`

Disable the file_upload_notification app. You must have force enabled it. It doesn't look like supports anything beyond v18 of Nc.

https://apps.nextcloud.com/apps/file_upload_notification

Next time fill out the entire bug reporting template please. :)
