### ISSUE TITLE
[Bug]: cannot set response code - headers already sent (PHP 8.3)

### ISSUE THREAD

**Issue by donniewr** [nextcloud/server#45835]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello, I'm encountering an error with shared links when using PHP 8.3. There are no errors when using PHP 8.2

```
{"reqId":"TtaAPaBHznnHcULJm2","level":3,"time":"2024-06-13T08:27:21+00:00","remoteAddr":"0.0.0.0","user":"--","app":"PHP","method":"GET","url":"/s/RcBt2ST2y5dpL/download?path=&files=","message":"http_response_code(): Cannot set response code - headers already sent (output started at /home/cloud/htdocs/cloud.domain.com/lib/private/Files/View.php:459) at /home/cloud/htdocs/cloud.domain.com/lib/private/legacy/OC_Template.php#257","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36","version":"29.0.2.2","data":{"app":"PHP"},"id":"646b0ae70a66"}
```

### Steps to reproduce

1. Use PHP 8.3
2. Share a video link (5+MB)
3. Access the link.
4. Check logs

### Expected behavior

No error.

### Installation method

Manual install with zip file.

### Nextcloud Server version

29

### Operating system

Ubuntu 24.04

### PHP engine version

PHP 8.3

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```
"system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.domain.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.2.2",
        "overwrite.cli.url": "https:\/\/cloud.domain.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "skeletondirectory": "",
        "default_language": "en",
        "knowledgebaseenabled": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updater.release.channel": "stable",
        "default_phone_region": "US",
        "theme": "",
        "loglevel": 2,
        "simpleSignUpLink.shown": false,
        "app_install_overwrite": [
            "group_default_quota",
            "breezedark",
            "transfer"
        ],
        "enforce_theme": "dark",
        "profile.enabled": false,
        "defaultapp": "files",
        "maintenance_window_start": 1
    }
}
```
### List of activated Apps

Files

### Nextcloud Signing status

Disabled

### Additional info

Cloudpanel.io control panel.

The error only seems to trigger with video files larger than 5MB.

**Comment by Owirtifo** [comment]
I have the same problem.

**Comment by joshtrichards** [comment]
Since you failed to fill out the issue template, this report will likely be closed.

Also, it's critical you include the entire raw log message. Though from the looks of the snippet you provided, I suspect you have other errors before this in your log.

Wild guess: when switching PHP versions at least one required PHP extension is missing. Your Nextcloud log will have further hints.

**Comment by joshtrichards** [comment]
This line of code only gets executed _after_ another error has occurred and been logged. Again, you didn't fill out the template. It could be as simple as your `loglevel` being set higher than the default, causing your logs to be missing the details to help troubleshoot your situation.

https://github.com/nextcloud/server/blob/b5275f703537f01fa27b042e1b619f56a223ab49/lib/private/legacy/OC_Template.php#L257

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#logging

Please fill out the missing elements of the form. We ask for that information to be able to help you.

**Comment by cfiehe** [comment]
We are facing the same issue in our Nextcloud instance.

**Comment by Ducknuke** [comment]
I have the same problem, I have hundreds of errors of this type in my log.
Nextcloud: 29.0.2.2
OS: Debian Linux 6.1.0
PHP: 8.3.8

**Comment by emgerber** [comment]
I have the  same issue. Also hundreds of error messages in the log.
Nextcloud: 29.03
OS: Debian GNU/Linux 12 (bookworm)
PHP: 8.3.8

Also strange is: As soon as I watch a video, the modified timestamp changes. This causes a wrong sort order. Then an error message is created. I also saw such interesting future timestamps, which are really strange:

![image](https://github.com/nextcloud/server/assets/59820400/2cec2f87-9213-403e-b9cc-bd7bf853171d)

**Comment by szaimen** [comment]
Cc @sorbaugh

**Comment by BlackWolfWoof** [comment]
Same issue here Nextcloud 28.0.3

**Comment by Deric-W** [comment]
Same issue here, using Nextcloud 29.0.3.4 with PHP 8.3.8 with Nginx on Linux (NixOS 24 .05).

**Comment by ketterl** [comment]
Well, I have the same issue:

```
[PHP] Fehler: http_response_code(): Cannot set response code - headers already sent (output started at /var/www/nextcloud/lib/private/Files/View.php:459) at /var/www/nextcloud/lib/private/legacy/OC_Template.php#257
	GET /s/WBYapggWeTaJ688/download?path=&files=
	von 123.123.123.123 von -- um 29.07.2024, 17:44:41
```

PHP 8.3.6 and Nextcloud 29.0.4 on Ubuntu 24.04

**Comment by Ogurtsov-D** [comment]
Same issue:

> http_response_code(): Cannot set response code - headers already sent (output started at /var/www/nextcloud/lib/private/Files/View.php:406) at /var/www/nextcloud/lib/private/legacy/OC_Template.php#257

Nextcloud 29.0.4
Ubuntu 22.04
PHP 8.3.10

**Comment by nicrame** [comment]
Same issue with older NC 28.0.9.

**Comment by brucifer-isp** [comment]
I have the same issue with NC 29.0.6, PHP 8.3.8, FreeBSD 13.1, Caddy 2.7.6

**Comment by Jane232** [comment]
Same problem here: NC 29.0.4, PHP 8.3, Ubuntu 24.04, Apache2

Similarly to OC seems to be occuring while playing video from share:
[PHP] Fehler: http_response_code(): Cannot set response code - headers already sent (output started at /var/www/nextcloud/lib/private/Files/View.php:459) at /var/www/nextcloud/lib/private/legacy/OC_Template.php#257
	GET /index.php/s/XXX/download?path=&files=XXX.MP4

**Comment by joshtrichards** [comment]
This error is coming up when PHP's `connection_status()` returns `CONNECTION_ABORTED`:

https://github.com/nextcloud/server/blob/a90f0a6b36deac85f7bbd8a0f04368ad30117637/lib/private/Files/View.php#L432-L436

This code was added via #40233. It's in most our recent majors: >=25.0.11, >=26.0.6, >=27.1.0, >=28.0.0 so it's been in the wild for awhile w/o reports until this June. The main difference is the increasing prevalence of PHP 8.3.

Are any of you experiencing this *not* using php-fpm?

**Comment by come-nc** [comment]
So, this is specific to Video playing then, right?
The point of detection of closed connection was to avoid to keep reading the video file when the user actually closed the page already. It also helped tremendously with performance when moving the cursor in the video because the browser close and opens lots of connections when doing that.

Can you be more clear about the error, what do you see on the screen, how does the page behave?
Or is the only problem a line in the logs?

**Comment by come-nc** [comment]
I can reproduce with stable29 and PHP 8.3, using a long video and moving the cursor in it. But it’s only an error in the log, it work fine apart from that. Gonna look into it.
It might be fixed already in master because the public link page was redone.

**Comment by come-nc** [comment]
Ok, so the issue is this:

1. The connection is aborted by the browser after a few bytes where already sent
2. The ConnectionLostException is thrown to abort the request
3. The Exception is caught by the caller and printErrorPage is called
4. printErrorPage attempts to set the HTTP response code to an error one but it’s too late.

I’m not sure what’s the clean way to fix it, it’s useless to catch the error and try to display it, the connection is already gone.
Maybe simply in printErrorPage check connection_status and do not bother if it’s closed?

**Comment by come-nc** [comment]
The following patch should do it: https://github.com/nextcloud/server/pull/47971.diff
