### ISSUE TITLE
[Bug]:   On OpenBSD, nextcloud package  has erroroneous config file  -- all occ commands are failing 

### ISSUE THREAD

**Issue by Monallabs** [nextcloud/server#45844]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Installed nextcloud-29 on openbsd via pkg_add. After starting php, even simple command: `doas -u www php occ config:list` is failing 
```bash
PHP Warning:  Module "imap" is already loaded in Unknown on line 0
PHP Warning:  Module "gmp" is already loaded in Unknown on line 0
PHP Warning:  Module "curl" is already loaded in Unknown on line 0
$CONFIG = array (
  'integrity.check.disabled' => true,
);
An unhandled exception has been thrown:
Exception: Config file has leading content, please remove everything before "<?php" in config.php in /var/www/nextcloud/lib/private/Config.php:257
Stack trace:
#0 /var/www/nextcloud/lib/private/Config.php(71): OC\Config->readData()
#1 /var/www/nextcloud/lib/base.php(150): OC\Config->__construct()
#2 /var/www/nextcloud/lib/base.php(622): OC::initPaths()
#3 /var/www/nextcloud/lib/base.php(1181): OC::init()
#4 /var/www/nextcloud/console.php(48): require_once('...')
#5 /var/www/nextcloud/occ(11): require_once('...')
 ```

### Steps to reproduce

1. obtain Openbsd 7.5  and move to snapshot branch 
2. doas pkg_add nextcloud
3. Configure and php (probably optional)
4. www php occ config:list

### Expected behavior

This is my first time installing nextcloud, so I don't know for sure, but if it works correctly then it should report config files.

### Installation method

Other Community project

### Nextcloud Server version

29

### Operating system

Other

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
This command itself is failing
```

### List of activated Apps

```shell
no apps activated so far.
```

### Nextcloud Signing status

```shell
not applicable
```

### Nextcloud Logs

```shell
not applicable
```

### Additional info

Seems like a packaging bug then an actual nextcloud bug

**Comment by susnux** [comment]
As the message says you should remove all content in the config file before the `<?php`.

But we can not do much about it, as it is a problem with a community package. 
I would recommend you to report it for openbsd
https://www.openbsd.org/report.html
