### ISSUE TITLE
Log-in page fonts/logo design

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#4585]
- [ ] Nextcloud logo too big https://github.com/nextcloud/server/pull/4910
- [x] Fonts incorrect 
- [x] Instance Name should be bold, slogan normal #4866

current `master`:
<img width="436" alt="bildschirmfoto 2017-04-28 um 21 37 09" src="https://cloud.githubusercontent.com/assets/19711361/25544496/035a989e-2c5b-11e7-879f-b40eb95a32aa.png">

latest `stable11`:
<img width="360" alt="bildschirmfoto 2017-04-28 um 21 38 40" src="https://cloud.githubusercontent.com/assets/19711361/25544527/29b94882-2c5b-11e7-9123-2e1c7477a1ed.png">

@jancborchardt @nextcloud/designers

**Comment by jancborchardt** [comment]
Huh, could this be related to the SCSS switch @skjnldsv?

Do you have any theming active @MariusBluem, or can you pinpoint a commit where this started to happen?

**Comment by MariusBluem** [comment]
> Do you have any theming active @MariusBluem, or can you pinpoint a commit where this started to happen?

The font stuff since quite a while ... did not report it, because I thought you all know 😜 No theming active 🤔

**Comment by jancborchardt** [comment]
> did not report it, because I thought you all know

Never expect this ;) Especially if there’s no existing issue.

Are you familiar with git bisect? Or do you want to learn it? ;) Finding out which commit caused it would be a great help, as I’m a bit busy today :\

**Comment by MorrisJobke** [comment]
@jancborchardt this is likely because the login page only uses the guests.css and some rules in there are in the wrong order. We tried to get everything in them at was on the page before but it seems something didn't made it. A bisect doesn't help that much. Better look into the "why are rules for font style not applied" instead of looking for the commit(which is 99.9% the scss one and reverting that is out of scope)

**Comment by MariusBluem** [comment]
#4694 does fix in in parts ... but the instance name (per default: "Nextcloud") is still not **bold** 😕 @rullzer

**Comment by MorrisJobke** [comment]
For me this is the case :confused:

**Comment by MorrisJobke** [comment]
Old vs new:

<img width="1000" alt="bildschirmfoto 2017-05-14 um 22 30 27" src="https://cloud.githubusercontent.com/assets/245432/26041750/fecca154-38f4-11e7-9ccf-508696cf766d.png">
<img width="1165" alt="bildschirmfoto 2017-05-14 um 22 30 38" src="https://cloud.githubusercontent.com/assets/245432/26041749/fec7236e-38f4-11e7-9387-d3495e53f057.png">

**Comment by MorrisJobke** [comment]
> Instance Name should be bold, slogan normal

Fix is in #4866

**Comment by jancborchardt** [comment]
> Nextcloud logo too big

Fix is at https://github.com/nextcloud/server/pull/4910, please review @juliushaertl @MorrisJobke @MariusBluem :)
