### ISSUE TITLE
User-selection sharing dropdown new design was reverted

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#4586]
`stable11` ✅:

<img width="366" alt="bildschirmfoto 2017-04-28 um 21 52 32" src="https://cloud.githubusercontent.com/assets/19711361/25544940/0803d002-2c5d-11e7-98ff-5933a142c307.png">

current `master` ❌:
<img width="373" alt="bildschirmfoto 2017-04-28 um 21 49 36" src="https://cloud.githubusercontent.com/assets/19711361/25544898/df9cfb3e-2c5c-11e7-8bd2-9cbabc8dbed0.png">

@jancborchardt @nextcloud/designers

**Comment by MorrisJobke** [comment]
Nice spot

**Comment by jancborchardt** [comment]
What the … how did this happen? :O

**Comment by MorrisJobke** [comment]
> What the … how did this happen? :O

I guess this is again one of the tiny spots we missed during the scss migration and merge of styles in one file. Happens and needs to be fixed.

**Comment by jancborchardt** [comment]
cc @skjnldsv do you by any chance have time to look into this since it’s related to the SCSS move? :)
