### ISSUE TITLE
User managenent polishing (Disable, ...)

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#4589]
Since #1234 is merged now, there are some design comments from my side:

- Icons for Everyone, Disabled and Enabled (Checkbox Icon, X-Icon, for Everyone I would recommend a list icon) - as we already have them on personal and admin settings.

- Introduce a space between Everyone, Disabled, Enabled and the Groups (like apps management between All apps, activated, ... and the categories from app store)

@jancborchardt @nextcloud/designers

**Comment by MorrisJobke** [comment]
Even if this is paper cuts, I would move this to 13. We can't fix everything in 12

**Comment by MariusBluem** [comment]
- maybe "icons for groups" (house, family, office, ...) and some other small pictograms which could be also used in sharing etc. 🤔

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers Anybody for this little polishing before the release?

**Comment by skjnldsv** [comment]
On it!

**Comment by MorrisJobke** [comment]
Let's move this to 14. 13 is already stuffed with a lot of new things.

**Comment by skjnldsv** [comment]
Okay, I'll leave my branch aside, it's not ready yet.

**Comment by skjnldsv** [comment]
Waiting for #8824 and then we'll go for this :)
