### ISSUE TITLE
Keynote files (.key) not syncing to server when created/changed on mac with OSX 10.12.4

### ISSUE THREAD

**Issue by LidhemRV** [nextcloud/server#4590]
### Steps to reproduce
1. Create a new keynote file and save in Nextcloud folder
2. Nextcloud desktop sync 2.2.4 will not upload the file to server (red x)
3. In the log an errormessage is displayed

### Expected behaviour
The file should be uploaded to the server. When i change the extension of the file from .key to something else (exempel .ppt) then the file syncs without a problem. The extension .key seems to trigger the issue.

### Actual behaviour
A red X appears and the file is not loaded to the server.

### Server configuration

Nextcloud sync 2.2.4 on OSX 10.12.4

**Web server:**

11.0.3

**Database:**

MySQL

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

Issue occurred in 11.0.2 and still there after updating to 11.0.3

**Where did you install Nextcloud from:**

Nextcloud

**Comment by gusarg81** [comment]
Hi,

    Same thing happens to me (even when I was using ownCloud). I have key files, thats belongs to OpenVPN certificates.

> Nextcloud,Error transferring gus.key - server replied: Locked

Currently, I am using Nextcloud v12.0.0

**Comment by MorrisJobke** [comment]
This seems to be a client issue then. If this also happens with an ownCloud server, could I ask you to report this in the client repo (we use the owncloud client quite unmodified regarding the sync algorithm): https://github.com/owncloud/client/issues

Thanks

**Comment by LidhemRV** [comment]
Hi, I reported it in the client repo and the problem was not with the client, but with the fact that my webhotel had Modsecurity enabled for my nextcloud server. Switched it off and all syncing works great now.
