### ISSUE TITLE
Contacts menu knows only one color for placeholder profile pictures

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#4591]
![img_0638](https://cloud.githubusercontent.com/assets/19711361/25553928/d250ac1e-2cc0-11e7-8007-f870922988b5.PNG)

Optimal would be, if the same colors from contacts app and everywhere else (sharing-dialog) would be used 😉 

@ChristophWurst

**Comment by irgendwie** [comment]
@jancborchardt There is no problem with that, since it could be possible that someone has two contacts with the same name! :wink: In the contacts app we use the uuid to generate the colors.

**Comment by jancborchardt** [comment]
@irgendwie @nextcloud/contacts but creating so many people called »New contact«? That doesn’t make a lot of sense. ;) Creating a new contact when there is already a »New contact« with no info should focus on that again.

**Comment by skjnldsv** [comment]
@jancborchardt Yep, it's an issue rails girls were working on. I don't know where we at at the moment :)

**Comment by juliushaertl** [comment]
I cannot reproduce this on 13 anymore.
