### ISSUE TITLE
login field placeholders look weird

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#45918]
Hi, just tested on daily.ltd2.nextcloud.com: the login field look weird:
![image](https://github.com/nextcloud/server/assets/42591237/2d2aa76b-109c-46b7-bb14-cdd8468fbc31)
cc @nextcloud/server-frontend @nextcloud/designers

**Comment by susnux** [comment]
Caused by the clickable area size and needs this to be fixed:
https://github.com/nextcloud-libraries/nextcloud-vue/pull/5694
