### ISSUE TITLE
Contacts menu should mention if a user has birthday

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#4592]
- a small 🎂 next to the users name
- maybe a red point (just like at the notifications-icon) which indicates, that there is something in contacts may require attention?

What do you think? @ChristophWurst

**Comment by jancborchardt** [comment]
Cute :D yeah, this is a great addition. People with birthdays in the coming week / 7 days could be pinned to the top of the list, and have the birthday cake to the name. And the red point is also good anyway since we will need that for when messages arrive etc. Will add the icon.

cc @Henni @irgendwie @skjnldsv of Contacts too. ;)

**Comment by skjnldsv** [comment]
What feedback should the icon have? Just a tooltip?

**Comment by jancborchardt** [comment]
The tooltip should maybe change from "Contacts" to "Contacts with birthdays" (in the future there will also be "New messages").

**Comment by ChristophWurst** [comment]
Important: we have to make sure that a user only sees birthdays of users/contacts that they are allowed to know the birth date. We have existing *bug reports* about users seeing other user's email address and this seems to be problematic in certain situations.

**Comment by MorrisJobke** [comment]
Most likely nothing for 14 -> moving to 15.

**Comment by szaimen** [comment]
Since we have the unified search now and it also shows the birthday of the contact you are looking for in the same search results, I guess this feature is already kind of implemented. Maybe we should think about removing the contacts menu, instead?

**Comment by ChristophWurst** [comment]
I'm fine if we close this. If it hasn't been done in such a long time then there doesn't seem to be much interest from anyone.

This is a nice to have, but nothing remotely critical.

**Comment by szaimen** [comment]
Okay. I had also the idea to remove the contacts menu app now that we have the unified search. Shall I open a new ticket for this?

**Comment by ChristophWurst** [comment]
I think that would need some discussion first. The concepts are not fully interchangeable. You don't see the same actions on search results that you see on contacts menu entries.
