### ISSUE TITLE
Add  Bulk Tagging on new Files app [28+]

### ISSUE THREAD

**Issue by luluwebmaster** [nextcloud/server#45935]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Hello everyone,

Since my recent update to Nextcloud 28, I’ve noticed a change in the file tagging functionality. Previously, I had the ability to tag multiple files simultaneously, but this feature seems to have disappeared since the update. This limitation is causing an inconvenience as I frequently use the tagging feature to organize my files.

**Describe the solution you'd like**
I would like to have the ability to tag multiple files simultaneously reinstated in Nextcloud 28.

**Describe alternatives you've considered**
Currently, the only alternative is to tag files individually, which is time-consuming and less efficient.

**Additional context**
Has anyone else encountered this issue? Is it a new feature introduced in version 28, or is it potentially a bug? If anyone has information on this matter or has found a solution, I would appreciate it if you could share. Otherwise, can we consider reporting this as a potential issue to the development team?

Thank you in advance for your responses and assistance!

**Comment by scintillae** [comment]
I see no way to give a reaction to this (it simply isn't an option presented to me).

However, bulk tagging ability is an important functionality of Nextcloud file management, and I believe it needs to be repaired and supported.

**Comment by luluwebmaster** [comment]
I just added it. It should be good now.

This is also an option that I would like to find again !

**Comment by moritzthecat** [comment]
absolutely required feature ... 
example: discuss a set of files for review. together with comments a must have for collaborative work esp. on set of many files, like photos.

**Comment by kesselb** [comment]
cc @sorbaugh @artonge

**Comment by artonge** [comment]
I guess it is a regression from the migration to vue.
Pull requests are welcome. It should be much easier than before to add this to the Files app :).

Steps would be:
1. Implement the `exec` and `execBatch` methods of the systemtag action: https://github.com/nextcloud/server/blob/42691661c429477fe3febad6fe2d48c4c958c08b/apps/systemtags/src/actions/inlineSystemTagsAction.ts#L32-L88
2. In those methods, open a modal displaying a form allowing the user to pick tags. Example from the new node action: https://github.com/nextcloud/server/blob/42691661c429477fe3febad6fe2d48c4c958c08b/apps/files/src/utils/newNodeDialog.ts#L32-L39
3. Then update the chosen tags with https://github.com/nextcloud/server/blob/42691661c429477fe3febad6fe2d48c4c958c08b/apps/systemtags/src/services/files.ts#L43-L56

**Comment by nousernameavailableanymore** [comment]
In which version will this be added again?
