### ISSUE TITLE
Can development Kkfileviwer plug

### ISSUE THREAD

**Issue by jack-taozhang** [nextcloud/server#45961]
### kkFileView

Document online preview project solution, built using the popular Spring Boot framework for easy setup and deployment. This versatile open source project provides basic support for a wide range of document formats, including:

- Supports Office documents such as doc, docx, xls, xlsx, xlsm, ppt, pptx, csv, tsv, , dotm, xlt, xltm, dot, xlam, dotx, xla, ,pages etc.
- Supports domestic WPS Office documents such as wps, dps, et , ett,  wpt.
- Supports OpenOffice, LibreOffice office documents such as odt, ods, ots, odp, otp, six, ott, fodt and fods.
- Supports Visio flowchart files such as vsd, vsdx.
- Supports Windows system image files such as wmf, emf.
- Supports Photoshop software model files such as psd ,eps.
- Supports document formats like pdf, ofd, and rtf.
- Supports software model files like xmind.
- Support for bpmn workflow files.
- Support for eml mail files
- Support for epub book documents
- Supports 3D model files like obj, 3ds, stl, ply, gltf, glb, off, 3dm, fbx, dae, wrl, 3mf, ifc, brep, step, iges, fcstd, bim, etc.
- Supports CAD model files such as dwg, dxf, dwf iges , igs, dwt , dng , ifc , dwfx , stl , cf2 , plt, etc.
- Supports all plain text files such as txt, xml (rendering), md (rendering), java, php, py, js, css, etc.
- Supports compressed packages such as zip, rar, jar, tar, gzip, 7z, etc.
- Supports image previewing (flip, zoom, mirror) of jpg, jpeg, png, gif, bmp, ico, jfif, webp, etc.
- Supports image information model files such as tif and tiff.
- Supports image format files such as tga.
- Supports vector image format files such as svg.
- Supports mp3,wav,mp4,flv .
- Supports many audio and video format files such as avi, mov, wmv, mkv, 3gp, and rm.
- Supports for dcm .
- Supports for drawio .

https://github.com/kekingcn/kkFileView

**Comment by kesselb** [comment]
Thank you, we will keep your suggestion in mind :+1:
