### ISSUE TITLE
Consider about showing SQLite info in "Security & setup warnings" instead of "Tips & tricks" 

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#4596]
As the memory cache info is also in the "Security & setup warnings"-section, I think we should do this too for SQLite-information, which is currently hidden under "Tips & tricks" 😉 

@jancborchardt @nickvergessen

**Comment by jancborchardt** [comment]
I think we consciously moved it from Security & setup warnings if I remember correctly. cc @karlitschek?

I’m fine either way.

**Comment by karlitschek** [comment]
i would leave it where it is to keep the warnings section clean. not a lot of people used sqlite by accident lately.

**Comment by jancborchardt** [comment]
Right – we have the giant warning on setup already. :)
