### ISSUE TITLE
»Email server« should be moved from »Additional settings« into »Server settings«?

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#4600]
The email server is pretty core and needed for password reset and email notifications. It should be in the first default entry »Server settings«, no?

cc @karlitschek @nickvergessen @LukasReschke @rullzer @MorrisJobke?

**Comment by nickvergessen** [comment]
Like the other product has it?

Well my main point here is, that in most environments you don't even need to touch it, or at most once. So don't care too much.

**Comment by jancborchardt** [comment]
You could say the same for Cron though, no?

I didn’t check another product, but it just seems that the status indicator that email is working (or not) should be more present. The easiest fix for now is moving it.

**Comment by nickvergessen** [comment]
Well cron has a status image sounds like a good first page feature, but email doesnt have any status indicator, anyway as said before im fine either way

**Comment by MorrisJobke** [comment]
> I didn’t check another product, but it just seems that the status indicator that email is working (or not) should be more present. The easiest fix for now is moving it.

And it's also not easy to get a status except we send an email, but then the status is in the inbox of the recipient and not the server.

**Comment by jancborchardt** [comment]
Okay anyway – are you vehemently opposed to put the Email server settings in the Basic settings? I would expect it there for first-time setup, or »Stuff which has to work« for sure.

cc @karlitschek

**Comment by karlitschek** [comment]
why do you mention me and 'vehemently oppose' in the same sentence? ;-) ;-) 
:+1: from me

**Comment by jancborchardt** [comment]
:DDD not because of that. So thaks for the feedback. ;)

**Comment by jancborchardt** [comment]
Ok, played around a bit but can’t figure out how to move it. Can someone help?

**Comment by MorrisJobke** [comment]
> Ok, played around a bit but can’t figure out how to move it. Can someone help?

There is somewhere an class implementing ISetting that defines the section it is in.

**Comment by MorrisJobke** [comment]
> There is somewhere an class implementing ISetting that defines the section it is in.

Wrong ... this is not yet ported. So either we change the way those settings are implemented (a bit of work - see https://github.com/nextcloud/server/pull/796/commits/3f9e1b3b45aa7a9c588e3023aeb9f99b28f714cf for example) - the problem there is, that we don't have an info.xml for the "settings" app (I would say we should move settings to the apps folder, because it actually is loaded as an app (but with a ton of special cases in the server to move that app directory to `settings/`) or it is not possible.

As this is also a bigger change I would avoid to do this that short before a release (even if we only tweak in the loading via ISetting) this is not worth the effort if we then touch it again to fix it properly for 13.

**Comment by jancborchardt** [comment]
Ok, then let’s do it for 13. And yep, moving all the `settings/` stuff to `apps/` seems to make sense since nowadays a bunch of our settings _are_ apps anyway.

**Comment by MorrisJobke** [comment]
> Ok, then let’s do it for 13. And yep, moving all the settings/ stuff to apps/ seems to make sense since nowadays a bunch of our settings are apps anyway.

That's not what I meant. I meant that the settings code is organised like an app. So we should not add more exceptions to the server but simply use it like a force enabled app.

**Comment by MorrisJobke** [comment]
Email settings are moved to the general server settings -> closing.
