### ISSUE TITLE
[Bug]: Missing database index for dav_shares resourceid, type and access

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#46015]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The database query
```sql
SELECT
  `publicuri`
FROM
  `oc_dav_shares`
WHERE
  (`resourceid` = ?)
  AND (`access` = ?)
```
does not always use an index:

![image](https://github.com/nextcloud/server/assets/1374172/5eb711ce-0f62-475f-8623-9375487c0353)

Query id is 03601b9aa9c7478bcc9506bd3b202407.

### Steps to reproduce

1. ???

### Expected behavior

Efficient queries

### Installation method

None

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ChristophWurst** [comment]
Query 257a6846e9aa2f42d6276e58c803e1e3 has a similar problem:

```sql
SELECT
  `dav_shares`.`principaluri`,
  `dav_shares`.`resourceid`
FROM
  `oc_dav_shares` `dav_shares`
WHERE
  (`dav_shares`.`type` = ?)
  AND (`dav_shares`.`resourceid` = ?)
```

![image](https://github.com/nextcloud/server/assets/1374172/018d5aca-0099-4155-89db-0f9c5991171f)

To improve both queries we will need two new indices:
* (resourceid, access)
* (resourceid, type)

**Comment by SebastianKrupinski** [comment]
@ChristophWurst should we do this automatically with a db migration? or is there another preferred method?

**Comment by ChristophWurst** [comment]
It depends (tm). If we can assume that the table is not insanely big we can apply the index with a migration. If the table is big we should only adapt the existing migration that creates the table. This will add the index for new setups. For existing ones we can use the "missing index" events/listeners.

**Comment by SebastianKrupinski** [comment]
Okay, I'll get working on it
