### ISSUE TITLE
Plugins are not activated after update

### ISSUE THREAD

**Issue by corvancrowing** [nextcloud/server#4601]
### Steps to reproduce
1. run any older version of nc (e.g. 11.0.2)
2. update via the web updater to a newer version (e.g. 11.0.3)
3.

### Expected behaviour
Update should (in my opinion) activate Plugins which have been activated before

### Actual behaviour
NC runs in standard mode like after a fresh install (concerning activated plugins)

### Server configuration

**Operating system**:
ubuntu 16.04 on cubiboard
Linux apps 3.4.39 #65 SMP PREEMPT Thu Apr 30 17:25:26 CST 2015 armv7l armv7l armv7l GNU/Linux
**Web server:**
Apache/2.4.18 (Ubuntu)
**Database:**
mysql  Ver 15.1 Distrib 10.0.24-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2
**PHP version:**
7.0.4-7ubuntu2

**Nextcloud version:** (see Nextcloud admin page)
11.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 11.0.2
**Where did you install Nextcloud from:**
downloaded tar from nc homepage
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - bookmarks: 0.9.1
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_downloadactivity: 1.0.1
  - files_external: 1.1.2
  - files_markdown: 1.0.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextant: 1.0.6
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - ownbackup: 17.3.0
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.1.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - files_retention
  - ocr
  - user_ldap
  - user_saml

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "oc7lwt40no7j",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "apps.lan",
            "dragonstone.ddnss.de",
            "www.familie-liedtke.net"
        ],
        "datadirectory": "\/mnt\/nextcloud",
        "overwrite.cli.url": "http:\/\/apps.lan\/nextcloud",
        "dbtype": "mysql",
        "version": "11.0.3.2",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_from_address": "nextcloud",
        "mail_domain": "familie-liedtke.net",
        "mail_smtphost": "mail.familie-liedtke.net",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** yes, but mounted smb via fuse

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

```


### Client configuration
**Browser:**
Chrome
**Operating system:**
Ubuntu 17.04

**Comment by corvancrowing** [comment]
List of activated apps is after I activated them again, but not activated for example were calendar, contacts, notes, nextant, ownbackup, two factor

**Comment by MorrisJobke** [comment]
We fixed this for 12 if you run PHP 7.0+.

**Comment by MorrisJobke** [comment]
> We fixed this for 12 if you run PHP 7.0+.

And the app is compatible and doesn't throw errors (of course).

**Comment by corvancrowing** [comment]
Cool, thx

**Comment by dmp1ce** [comment]
I am seeing this again on 14 release branch. Has this been reported again? I'm also using the docker image.

**Comment by MorrisJobke** [comment]
> I am seeing this again on 14 release branch. Has this been reported again? I'm also using the docker image.

Please open a new ticket with a reference to this one.
