### ISSUE TITLE
NC30 UI refresh cleanup

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/server#46016]
* https://github.com/orgs/nextcloud/projects/62/views/17?pane=issue&itemId=56918898

### Vue library 
Draft  https://github.com/nextcloud-libraries/nextcloud-vue/pull/5746

- [x] https://github.com/nextcloud-libraries/nextcloud-vue/pull/5766
- [x] https://github.com/nextcloud-libraries/nextcloud-vue/pull/5780#pullrequestreview-2185912459
- [x] https://github.com/nextcloud-libraries/nextcloud-upload/issues/1275
- [x] Input fields - text fields overall check
- [x] Adjust navigation toggle position
- [x] NcAppNavigationCaption height is off
- [x] New Item element styles are off
- [x] NcAppSidebar header star top aligned
- [x] NcAppSettingsDialog entries border radius ( https://github.com/nextcloud-libraries/nextcloud-vue/pull/5963 )
- [x] NcBreadcrumbs spacing between breadcrumbs and new button
- [x] NcDashboardWidgetItem reduce size
- [x]  https://github.com/nextcloud-libraries/nextcloud-vue/pull/5821#pullrequestreview-2185135874
- [x] Passwordfield jumps when activated
- [x] NcListIitem details elements are not all the way right aligned
- [x] NcInputfield height is too big
- [x] NcSelect, https://github.com/nextcloud-libraries/nextcloud-vue/pull/5883
- [x] NcDateTimePicker height is too big (deprecated)
- [x] https://github.com/nextcloud-libraries/nextcloud-vue/pull/5974
- [x] Standard radio set with alternative button style: border 1px and border radius element. Also center text
- [x] Standard switch is still 44px (@shgkme WIP)
- [x] NcChip remove pill shape, Advanced usage make avatar 20px and remove menu from it https://github.com/nextcloud-libraries/nextcloud-vue/pull/5924
- [x] https://github.com/nextcloud-libraries/nextcloud-vue/pull/5963
- [x] NcActionTextEditable regression submit button (deprecate)
- [x] NcAppNavigationSpacer use clickable-area/2 or --default-grid * smth

### Server
- [x] https://github.com/nextcloud/server/pull/46270
- [x] Bring headings down one step in size

###  Dashboard
- [x] https://github.com/nextcloud/server/pull/46201

### Updater & AIO 
- [x] https://github.com/nextcloud/all-in-one/issues/4955 cc @szaimen 

cc @jancborchardt @nimishavijay @susnux @ShGKme @skjnldsv

**Comment by come-nc** [comment]
![Copie d'écran_20240702_165458](https://github.com/nextcloud/server/assets/91878298/7dd12581-6f39-4f22-bf51-9f9e7f8c9f28)
Not sure if related but the **+** button for groups is misaligned

**Comment by marcoambrosini** [comment]
It looks like you didn't link the vue library master @come-nc

**Comment by susnux** [comment]
For testing master without linking we need: #46230

**Comment by hamza221** [comment]
@susnux #46230 is for stable29

**Comment by ChristophWurst** [comment]
>  NcBreadcrumbs spacing between breadcrumbs and new button

Not sure if related but the breadcrumbs jump a tiny bit at page load

![Bildschirmfoto vom 2024-07-16 13-28-01](https://github.com/user-attachments/assets/084a6011-0683-48a8-864a-be798fa1195e)
![Bildschirmfoto vom 2024-07-16 13-28-03](https://github.com/user-attachments/assets/8ad0e3e1-9d64-4346-bf4d-a15db40d1269)

IMO the alignment is better while the file list is loading

**Comment by ChristophWurst** [comment]
- [ ] HTML inputs have a 2px border radius, not ``var(--border-width-input, 2px)`` that is used in NcSelect. This creates inconsistency

https://github.com/nextcloud/server/blob/87dc0614d703536843b878808a2721899df798b4/core/css/inputs.scss#L246

**Comment by ChristophWurst** [comment]
> NcInputfield height is too big

Same as https://github.com/nextcloud/server/issues/46851?

**Comment by ChristophWurst** [comment]
- [ ] User menu has 44px entries

![image](https://github.com/user-attachments/assets/d5532366-bd82-4009-aa37-2eaa14e1d456)

**Comment by marcoambrosini** [comment]
@susnux @ShGKme @GVodyanov please update the checkboxes if you fix some of those things

**Comment by susnux** [comment]
> [ ] User menu has 44px entries

https://github.com/nextcloud/server/issues/46460

**Comment by skjnldsv** [comment]
![image](https://github.com/user-attachments/assets/87efd610-dcce-4699-af40-a39305d97d53)
Quota is looking weird

**Comment by ChristophWurst** [comment]
- [ ] Mobile apps menu toggle is not aligned with the app icons

![Bildschirmfoto vom 2024-08-05 09-52-16](https://github.com/user-attachments/assets/74344630-fddb-4b16-8fd1-f0a190efce68)

- [ ] App entries are not centered vertically
![Bildschirmfoto vom 2024-08-05 09-52-12](https://github.com/user-attachments/assets/4024485e-a414-433e-9ac9-3a5dca414740)

**Comment by ChristophWurst** [comment]
- [ ] *Share* button hover state in Files breadcrumbs

![image](https://github.com/user-attachments/assets/848c8423-c4c9-4bd8-a9a0-f15bd08097f0)

**Comment by ChristophWurst** [comment]
- [ ] Contacts menu handle scrolls on mobile

[Bildschirmaufzeichnung vom 2024-08-06 07-44-57.webm](https://github.com/user-attachments/assets/fb94e450-5347-4777-af79-3a00f2986d7a)

**Comment by ChristophWurst** [comment]
- [ ] Large radii and old buttons on upgrade page

![image](https://github.com/user-attachments/assets/e524d814-f719-4b3a-8606-754c956cf2b7)

**Comment by ChristophWurst** [comment]
> NcDateTimePicker height is too big

The picker needs a general design update for 30: https://github.com/nextcloud-libraries/nextcloud-vue/issues/5951

**Comment by ChristophWurst** [comment]
- [ ] Border radii when using keyboard navigation

![image](https://github.com/user-attachments/assets/5f32dd65-2748-488e-b596-45f0812f8690)
![image](https://github.com/user-attachments/assets/cbb5f9cb-19b1-450d-9975-7c9bfd6050c7)

**Comment by ChristophWurst** [comment]
- [ ] Main menu at the top right doesn't look very compact and there is too much space between the action icon and text

![image](https://github.com/user-attachments/assets/5d2ac53a-43b6-45c3-8e6b-9bd85e66a36e)

**Comment by ChristophWurst** [comment]
> Not sure if related but the breadcrumbs jump a tiny bit at page load

Still happening: when you click on *All files* there is a spinner at the top right and it makes the breadcrumbs jump down a few px

![Bildschirmfoto vom 2024-08-20 13-31-41](https://github.com/user-attachments/assets/ffcc7827-89ef-4b84-aba6-a9cf129b2eda)
![Bildschirmfoto vom 2024-08-20 13-31-39](https://github.com/user-attachments/assets/9a70b32c-83bf-4521-a0cc-c4336ce5bf76)

See the alignment of the nav toggle and the breadcrumbs. It's fine until the loading spinner shows.

**Comment by jancborchardt** [comment]
Also, that loading spinner makes the view toggle jump to the left, so it should be left of that toggle instead.

**Comment by ChristophWurst** [comment]
- [ ] Unfocused text inputs have a 2px border

https://github.com/nextcloud/server/blob/6d04ad829b2814090301b0101dc10fa0617dd783/core/css/inputs.scss#L256

This shows in apps too, like Mail

![image](https://github.com/user-attachments/assets/fd99976c-edc6-46ea-935f-ac9c754a93da)

**Comment by susnux** [comment]
@ChristophWurst 

> This shows in apps too, like Mail

I strongly recommend to use `NcInputField` for this:
https://github.com/nextcloud/mail/blob/62f1cec233ab92a311bcb0f70967d49f64bd1d8d/src/components/SearchMessages.vue#L8

**Comment by ChristophWurst** [comment]
Yep, agree. But vanilla inputs should also have the correct style.

**Comment by marcoambrosini** [comment]
Closing, moved few remaining things in new issues

**Comment by jancborchardt** [comment]
Great job everyone and especially @marcoambrosini for driving this. We came out with a really much more refined interface. :)
