### ISSUE TITLE
[Bug]: Some Korean translations on Transifex are not being reflected anymore.

### ISSUE THREAD

**Issue by proxima235** [nextcloud/server#46024]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After the release of version 28, I fixed some incorrect Korean translations on the 'Nextcloud upload library' project on Transifex. But I can't see any change during multiple minor releases and a major update(29).

Are there any additional tasks for translators to contribute these fixes to the Nextcloud project?

### Steps to reproduce

1.Set the language setting to Korean on your instance.
2.Make some changes inside the 'Nextcloud upload library' project.
3.Get a minor/major upgrade and check the displaying text on your Nextcloud.

### Expected behavior

Updates and releases should fix the texts that have been changed on the Transifex project.

### Installation method

Official All-in-One appliance

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Are the changes you made located in here?

https://github.com/nextcloud-libraries/nextcloud-upload/blob/main/l10n/ko.pot

**Comment by joshtrichards** [comment]
Fixed in #47367 

Underlying library needed to be bumped in stable29.

Will be released in 29.0.6 in a month or so. :)
