### ISSUE TITLE
Nextcloud 12 - Issues with Integrity Check and "X-Frame-Options"..."SAMEORIGIN"

### ISSUE THREAD

**Issue by riegercloud** [nextcloud/server#4605]
Hi Nextclouders,

I just installed Nextcloud 12 alpha (Nextcloud 12.0 alpha Build:2017-04-28T22:01:10+00:00 d4e5b1bf14a9dfd0a4ac09285d6e8e073f8a2d74), based on an ODroid C2, NGINX 1.13, Ubuntu 16.04.02 LTS x64,, PHP 7.1.4, mariadb 10.0.29 and ran into two issues:

- Some files have not passed the integrity check. Further information on how to resolve this issue can be found in our documentation. (List of invalid files… / Rescan…)

> Raw output
==========
Array
(
    [bruteforcesettings] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

- The "X-Frame-Options" HTTP header is not configured to equal to "SAMEORIGIN". This is a potential security or privacy risk and we recommend adjusting this setting. 

NGINX is configured properly using  "proxy_set_header X-Frame-Options "SAMEORIGIN; always;";"
![grafik](https://cloud.githubusercontent.com/assets/20593693/25558600/5cc92f74-2d2a-11e7-9a47-35820a0d31b3.png)

![grafik](https://cloud.githubusercontent.com/assets/20593693/25558515/dee8ac3e-2d28-11e7-9f79-3035db33e800.png)

This is a clone of my productiv Nextcloud 11.0.3 environment which is running without the issues above.

Cheers, Carsten

**Comment by MorrisJobke** [comment]
The `SAMEORIGIN, SAMEORIGN` looks wrong, but @LukasReschke can say more on this. In my instance it is only written once:

<img width="297" alt="bildschirmfoto 2017-05-01 um 00 33 55" src="https://cloud.githubusercontent.com/assets/245432/25571436/f766fd46-2e05-11e7-806b-5323e34314f0.png">

Maybe @josh4trunks knows why there is same origin listed twice in the headers for Nginx.

**Comment by josh4trunks** [comment]
@MorrisJobke Maybe it is being set twice because of `proxy_set_header X-Frame-Options "SAMEORIGIN; always;";"`.
@riegercloud I do not see this in the documentation, I'm not sure why you say this is "configured properly".

The documentation already has with `add_header X-Frame-Options "SAMEORIGIN";`

**Comment by riegercloud** [comment]
Hi and thanks for all the responses.
I am running NGINX 1.13 as  a reverse proxy.
My production system does not show the SAMEORIGIN twice either.
![grafik](https://cloud.githubusercontent.com/assets/20593693/25574309/7716f2f2-2e4d-11e7-9de4-8b0ddd289c89.png)

My Testcloud is installed in a subfolder, located on a second server. The main gateway.conf points to the second server - maybe it is related to that configuration?

The gateway.conf contains of
...
add_header Referrer-Policy "same-origin" always;
add_header X-Frame-Options "SAMEORIGIN" always;
...

The Nextcloud.conf's consists of:
...
server {
...
proxy_set_header X-Frame-Options "SAMEORIGIN; always;";
...
}
...
location ~* \.(?:css|js)$ {
...
proxy_set_header X-Frame-Options "SAMEORIGIN; always;";
...

I would provide more information if you are interested in - please let me know ;-)
...:::carsten

**Comment by josh4trunks** [comment]
Please try removing ` proxy_set_header X-Frame-Options "SAMEORIGIN; always;";`

**Comment by riegercloud** [comment]
I removed both entires in the testcloud.conf (Nextcloud 12)

![grafik](https://cloud.githubusercontent.com/assets/20593693/25575093/2de937be-2e54-11e7-97a3-9289166c6273.png)

and restarted the relevant services:
service nginx stop && service redis-server restart && service php7.1-fpm restart && service nginx start

![grafik](https://cloud.githubusercontent.com/assets/20593693/25575107/4f5a68dc-2e54-11e7-8b82-7418b3158670.png)

Unfortunately still the same behaviour. But i recognized the duplicate entries only appear for e.g. the login or file requests ![grafik](https://cloud.githubusercontent.com/assets/20593693/25574982/6d2efd9c-2e53-11e7-98ef-b9803f197f3c.png)
![grafik](https://cloud.githubusercontent.com/assets/20593693/25575032/b93e381a-2e53-11e7-8d99-2c3884a41e5e.png)

not for e.g. files 

![grafik](https://cloud.githubusercontent.com/assets/20593693/25575045/d34c0b42-2e53-11e7-802e-6ed1ef835f46.png)

could that point to tne root cause?

**Comment by riegercloud** [comment]
[gateway_conf.pdf](https://github.com/nextcloud/server/files/967498/gateway_conf.pdf)
[nextcloud_conf.pdf](https://github.com/nextcloud/server/files/967499/nextcloud_conf.pdf)
[ssl_conf.pdf](https://github.com/nextcloud/server/files/967500/ssl_conf.pdf)
[testcloud_conf.pdf](https://github.com/nextcloud/server/files/967501/testcloud_conf.pdf)

**Comment by josh4trunks** [comment]
Can you please post your configs in code blocks instead of PDFs?
Why do you have all of these proxy_set_header lines, when the documentation never uses them?

That is interesting, even with you SAMEORIGIN lines commented out, the header shows up.
Can you show the contents of your **fastcgi_params** file?

**Comment by riegercloud** [comment]
The documentation of what? Nextcloud?
The documentation didn't fit all my requirements and we did investigat with others in a more secure and more quicker environement.
 
fastcgi_params (default - no cahnges applied):

```
fastcgi_param  QUERY_STRING       $query_string;
fastcgi_param  REQUEST_METHOD     $request_method;
fastcgi_param  CONTENT_TYPE       $content_type;
fastcgi_param  CONTENT_LENGTH     $content_length;

fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
fastcgi_param  REQUEST_URI        $request_uri;
fastcgi_param  DOCUMENT_URI       $document_uri;
fastcgi_param  DOCUMENT_ROOT      $document_root;
fastcgi_param  SERVER_PROTOCOL    $server_protocol;
fastcgi_param  REQUEST_SCHEME     $scheme;
fastcgi_param  HTTPS              $https if_not_empty;

fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;

fastcgi_param  REMOTE_ADDR        $remote_addr;
fastcgi_param  REMOTE_PORT        $remote_port;
fastcgi_param  SERVER_ADDR        $server_addr;
fastcgi_param  SERVER_PORT        $server_port;
fastcgi_param  SERVER_NAME        $server_name;

fastcgi_param  REDIRECT_STATUS    200;
```

**Comment by josh4trunks** [comment]
yes i meant the nedtcloud documentation.
from what i am reading proxy_set_header sends these headers to the backend server (in this case php-fpm), I'm pretty sure you should be using addheader.

ok to clarify. you have an nginx instance running the gateway_conf configuration, then for the testcloud, nginx on another machine?

**Comment by josh4trunks** [comment]
im not sure hoe this double header is being generated. possibly a bug in nextcloud 12?

Im a bit lost in your setup but i do not think that could cause the double header.
you have a gateway (is this also running the ssl_conf) then 2 different ngjnx servers behind it. you also dodnt shoe you php-handler block, but i doubt that has an issue with it.

**Comment by josh4trunks** [comment]
ohh, i see where the ssl conf is included. disregard my previous question on that.

**Comment by riegercloud** [comment]
Server A (nc.c-rieger.de):
- gateway.conf
- ssl.conf 
points to
- nextcloud.conf (on Server A / root-folder)
- testcloud.conf (on Server B / as a subfolder -> nc.c-rieger.de/testcloud)

i will re-install Nextcloud 12 in a root-folder instead of a subfolder and will doublecheck. 
But as mentioned before, the same nginx-confguration is running well in the productive environment.
I guess, it is a bug in NC12. Maybe hardcoded?

Will be back with the testresults ... but i have to accompany my twins to their riding first.

**Comment by josh4trunks** [comment]
sounds good, I'm suspecting a bug here

**Comment by riegercloud** [comment]
I re-installed NC12 from scratch in the web-root (https://192.168.2.17/login) and took the configuration from Nextclouds-[Documentation](https://docs.nextcloud.com/server/11/admin_manual/installation/nginx_nextcloud_9x.html).

Unfortunately, i still ran in the same issues:

![grafik](https://cloud.githubusercontent.com/assets/20593693/25578602/a2219858-2e70-11e7-9fee-614abc1d65af.png)

So this must be related to NC12 and NGINX.
Does anybody have a look at the Integrity Failure as well?

**Comment by LukasReschke** [comment]
The `X-Frame-Options` header has been moved to the PHP processing and outside of `.htaccess` so that applications can decide themselves if they want to be iframed. For example for iframing a public Nextcloud calendar or so.

So the `X-Frame-Options` header should be dropped from the NGINX configuration as this would also make it impossible for applications to control themselves if they want to allow iframing.

**Comment by riegercloud** [comment]
OK, if removed from NGINX it works fine.
This should be documented properly and can be closed from my perspective.
But the other issues is still open.
Thank you @LukasReschke

**Comment by LukasReschke** [comment]
Potential patch at https://github.com/nextcloud/server/pull/4626

**Comment by MorrisJobke** [comment]
See https://github.com/nextcloud/documentation/issues/434 for the documentation update as well as the release notes

**Comment by LukasReschke** [comment]
New dailies are at https://download.nextcloud.com/server/daily/latest-master.tar.bz2

**Comment by sergeyklay** [comment]
@LukasReschke Thank  you!
