### ISSUE TITLE
Upgrade from 11.0.2 to .3 - file integrity problem - file missing- npm-debug.log

### ISSUE THREAD

**Issue by wgregori** [nextcloud/server#4607]
I went through the upgrade procedure (web interface) from 11.0.2 to 11.0.3.  All appeared to go with out a hitch. But now I get a security warning regarding file integrity problem.... 

Operating system: ubuntu 16.04, Nginx

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- tasks
	- FILE_MISSING
		- js/vendor/angular-ui-select/npm-debug.log

Raw output
==========
Array
(
    [tasks] => Array
        (
            [FILE_MISSING] => Array
                (
                    [js/vendor/angular-ui-select/npm-debug.log] => Array
                        (
                            [expected] => a697a632245b044cba1b8698ba645189a29d504c9991e45c3db5c114bb8b3c4a5d285885fac967ffb179d6c55ea81caa742c68417a2adcd64fe472a5e114203b
                            [current] => 
                        )

                )

        )

)

**Comment by MorrisJobke** [comment]
@lukasreschke

**Comment by MorrisJobke** [comment]
Ah ... this is for the tasks app - please report this there. It seems that the signature is wrong, because a non-packaged file was signed. https://github.com/nextcloud/tasks/issues
