### ISSUE TITLE
[Bug]: Scroll Bar Jumps After Closing Image Preview in Grid View

### ISSUE THREAD

**Issue by sword2020** [nextcloud/server#46084]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When querying files and switching to grid view, after previewing an image file and closing the preview window, the scroll bar does not return to its previous position and jumps away.
在查询文件并切换到网格视图时，预览图片文件后关闭预览窗口，滚动条不能恢复到之前的位置，会跳走。

### Steps to reproduce

1.Query files.
2.Switch to grid view.
3.Preview an image file.
4.Close the preview window.
5.Observe the scroll bar position.

### Expected behavior

The scroll bar should return to its previous position after closing the preview window, allowing users to continue browsing from where they left off.

### Installation method

None

### Nextcloud Server version

29

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.1

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 22 to 23)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by qibao07** [comment]
Regardless of grid view or list view, the scroll bars change after opening the picture and closing it. My version is nc28.

**Comment by joshtrichards** [comment]
Fixed in #48632
