### ISSUE TITLE
Is mobile or 3rd party access broken? 

### ISSUE THREAD

**Issue by rkkoszewski** [nextcloud/server#4608]
### Steps to reproduce
1. Install Nextcloud on a Raspberry Pi with Nginx 1.9
2. Try to login using the Nextcloud Android app or any third party client.

### Expected behaviour
User should be able to log in, download a file.

### Actual behaviour
Android device fails to login or download file.

In the **official Nextcloud Android app**, when I enter my Nextcloud domain, it says "An unknown error has occured".

When I use **Solid Explorer** and add my server as a OwnCloud server, I am able to login successfully and list files from my account, but when I try to download any file, it gives an error stating, an error with the network connection happened.

Finally, on my server logs I can see where the Nexctloud Android App was trying to access, like status.php and from my browser (desktop) I see a JSON string with no errors. The same goes for the URL that Solid Explorer is using to download a file, when I copy paste the URL from the logs to my browser and run it, the file downloads correctly.

When I try to access my Nextcloud server from Google Chrome (On the Android Device) I get a lot of Javascript error (Example: ... /apps/files/**undefined**/js/core/vendor/marked/marked.min.js?_=1493583236084...). I cannot see any files. BUT, when I select the "View page as in computer", the page loads correctly, and I can see all the files, preview and download them correctly.

It seems to try accessing some files that does not exist on the server like "/core/js/oc.js" and "apps/files/index.php/apps/gallery/config?extramediatypes=1" that returns a server error (In Nextcloud logs it appears as if some methods are missing)

With an other (older) Android device, I can access the page normally with Chrome (In mobile view). But the Nextcloud app has still issues downloading files. 

I have no clue where the issue is.

One thing to note is that I had Nextcloud 11.0.2 running a few days ago, and everything was working fine, till my SD card got corrupt. I decided to install the same system on an external HDD drive instead (clean install), and I installed everything again from scratch as I had it before on the SD card. This time I installed Nextcloud 11.0.3 directly. My SSL certificates have been renewed as I lost all files from the SD card. Clearing the cache on the mobile device browsers doesn't seem to change anything.

### Server configuration

**Operating system**: Debian Jessie (Raspian)

**Web server:** Nginx 1.9

**Database:** MySQL

**PHP version:** 7.0

**Nextcloud version:** 11.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh Install

**Where did you install Nextcloud from:** Official Website

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - apporder: 0.3.3
  - bookmarks: 0.9.1
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - direct_menu: 0.10.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_markdown: 1.0.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - previewgenerator: 1.0.5
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - ojsxc
  - templateeditor
  - user_external
  - user_ldap
  - user_saml

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/data\/***REMOVED SENSITIVE VALUE***\/",
        "overwrite.cli.url": "http:\/\/www.***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "11.0.3.2",
        "dbname": "db_nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "noreply",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "jekotheme"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** Chrome

**Operating system:** Windows

#### Web server error log
<details>
<summary>Web server error log</summary>

```
192.168.2.242 - - [30/Apr/2017:21:57:41 +0200] "GET /status.php HTTP/1.1" 200 155 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
192.168.2.242 - - [30/Apr/2017:21:57:41 +0200] "GET /status.php HTTP/1.1" 200 155 "-" "Mozilla/5.0 (Android) ownCloud-android/1.4.2"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Hajo1961** [comment]
I have the same issue, mobile devices can't connect, they timed out!

**Comment by sankayop** [comment]
Hi there,
got the same issue with android Kitkat.
I can access Nextcloud 11.0.3 via firefox and via online accounts.
configured with SSL certificates and Nginx.
Thanks for your help,

**Comment by Hajo1961** [comment]
I think I have found the problem. Do you also have a large actice directory associated with ldap? If I disable the ldap app it works fine. I believe it is a bug in the ldap connector.

Best reagrds 

Hajo

**Comment by sankayop** [comment]
Hi,
I don't think I got any Ldap app working but please could you tell me how to do this/check this so that I can see if it makes any difference.
I was also wondering where to find the log related to this "unknown error"...

Good day,

**Comment by Hajo1961** [comment]
@sankayop Have you disable the ldap app?

**Comment by sankayop** [comment]
@Hajo1961 Hi, thanks for your help but finally, I managed to get it right.
I started from a clean nginx.conf file found in Nextcloud's doc and it's now working.
When I migrated from Owncloud, I suppose I made a mess with the conf file...
So I didn't need to disable ldap (and don't know how to do it btw ;) )
Thanks anyway

**Comment by Hajo1961** [comment]
@sankayop Can you tell me what the difference between your old and your new config was?

**Comment by sankayop** [comment]
@Hajo1961 I'm sorry Hajo, I was so happy I just deleted the old file not to use it anymore... but it was actually the file from here: linoxide.com/storage/setup-owncloud-nginx-ssl-freebsd-11/ with a small add of this type: 
location / {
        index index.html index.htm index.php;
        try_files $uri $uri/ @handler;
        auth_basic "Restricted website - authorised access only";
        auth_basic_user_file /etc/nginx/.htpasswd;
    }
but It was a mess...

**Comment by rkkoszewski** [comment]
Hi, I finally managed to get the error log from the Nextcloud app. It seems like there is some kind of HTTP violation (Not sure what to do with that).

Here is the Log snippet:

```
05-04 16:59:51.264 31936  4341 D SimpleFactoryManager: getClientFor(OwnCloudAccount ... :
05-04 16:59:51.264 31936  4341 D OwnCloudClient #28: Creating OwnCloudClient
05-04 16:59:51.265 31936  4341 V SimpleFactoryManager:     new client {@www.mydomain.xt, 264774531}
05-04 16:59:51.268 31936  4341 D OwnCloudClient #28: REQUEST GET /status.php
05-04 16:59:51.270 31936  4341 D AdvancedSslSocketFactory: Creating SSL Socket with remote www.mydomain.xt:443, local null:0, params: org.apache.commons.httpclient.params.HttpConnectionParams@abac1a7
05-04 16:59:51.271 31936  4341 D AdvancedSslSocketFactory:  ... with connection timeout 5000 and socket timeout 5000
05-04 16:59:51.288 31936  4341 I ServerNameIndicator: SSLSocket implementation: com.android.org.conscrypt.OpenSSLSocketImpl
05-04 16:59:51.289 31936  4341 I ServerNameIndicator: SNI done, hostname: www.mydomain.xt
05-04 16:59:51.305  2044  2386 E FastThread: did not receive expected priority boost
05-04 16:59:51.400 31936  4341 E GetRemoteStatusOperation: Connection check at https://www.mydomain.xt: HTTP violation
05-04 16:59:51.400 31936  4341 E GetRemoteStatusOperation: org.apache.commons.httpclient.ProtocolException: Unable to parse header: # includeSubDomains; preload;
05-04 16:59:51.400 31936  4341 E GetRemoteStatusOperation:      at org.apache.commons.httpclient.HttpParser.parseHeaders(HttpParser.java:202)
05-04 16:59:51.400 31936  4341 E GetRemoteStatusOperation:      at org.apache.commons.httpclient.HttpMethodBase.readResponseHeaders(HttpMethodBase.java:1935)
05-04 16:59:51.400 31936  4341 E GetRemoteStatusOperation:      at org.apache.commons.httpclient.HttpMethodBase.readResponse(HttpMethodBase.java:1737)
05-04 16:59:51.400 31936  4341 E GetRemoteStatusOperation:      at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1098)
05-04 16:59:51.400 31936  4341 E GetRemoteStatusOperation:      at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
05-04 16:59:51.400 31936  4341 E GetRemoteStatusOperation:      at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
05-04 16:59:51.400 31936  4341 E GetRemoteStatusOperation:      at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
05-04 16:59:51.400 31936  4341 E GetRemoteStatusOperation:      at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
05-04 16:59:51.400 31936  4341 E GetRemoteStatusOperation:      at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:222)
05-04 16:59:51.400 31936  4341 E GetRemoteStatusOperation:      at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:192)
05-04 16:59:51.400 31936  4341 E GetRemoteStatusOperation:      at com.owncloud.android.lib.resources.status.GetRemoteStatusOperation.tryConnection(GetRemoteStatusOperation.java:87)
05-04 16:59:51.400 31936  4341 E GetRemoteStatusOperation:      at com.owncloud.android.lib.resources.status.GetRemoteStatusOperation.run(GetRemoteStatusOperation.java:192)
05-04 16:59:51.400 31936  4341 E GetRemoteStatusOperation:      at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
05-04 16:59:51.400 31936  4341 E GetRemoteStatusOperation:      at com.owncloud.android.operations.GetServerInfoOperation.run(GetServerInfoOperation.java:81)
05-04 16:59:51.400 31936  4341 E GetRemoteStatusOperation:      at com.owncloud.android.lib.common.operations.RemoteOperation.execute(RemoteOperation.java:136)
05-04 16:59:51.400 31936  4341 E GetRemoteStatusOperation:      at com.owncloud.android.services.OperationsService$ServiceHandler.nextOperation(OperationsService.java:482)
05-04 16:59:51.400 31936  4341 E GetRemoteStatusOperation:      at com.owncloud.android.services.OperationsService$ServiceHandler.handleMessage(OperationsService.java:418)
05-04 16:59:51.400 31936  4341 E GetRemoteStatusOperation:      at android.os.Handler.dispatchMessage(Handler.java:102)
05-04 16:59:51.400 31936  4341 E GetRemoteStatusOperation:      at android.os.Looper.loop(Looper.java:154)
05-04 16:59:51.400 31936  4341 E GetRemoteStatusOperation:      at android.os.HandlerThread.run(HandlerThread.java:61)
```

On the other hand, I found out what was causing the errors from the browser. It seems that while I was trying to make the Nextcould mobile app work, I shuffled some location settings in nginx, having  location ~* \.(?:css|js|woff|svg|gif) and location ~* \.(?:png|html|ttf|ico|jpg|jpeg)$ before the PHP handler. After putting those two location settings back to its place (Right at the bottom of the file) the browser version of Nextcloud works perfectly on the phone too now. But the mobile app is still unable to connect.

**Comment by rkkoszewski** [comment]
Ok, so after reading the error log several times I finally figured out what was going on. 

It seems that in the Nextcloud Nginx configuration example there was the line:
```
# add_header Strict-Transport-Security "max-age=15768000;
# includeSubDomains; preload;";
```

I uncomented the first statement without noticing that the line was continuing in the next line, and therefore a broken HTTP header was sent to the client. Changing that line to:
`add_header Strict-Transport-Security "max-age=15768000;";`
fixed the issue.

It seems that while redoing the whole process again I didn't read the conditions with the same detail as before. 

I would like to thank everybody who tried to help here.
So at the end, no bug, just human stupidity.

Greetings and thanks again.
