### ISSUE TITLE
[Bug]: Shared Folder Redirecting To Root Directory From "Shared with you" Section

### ISSUE THREAD

**Issue by alperozturk96** [nextcloud/server#46108]
### Bug description

User cannot be able to open folder from "Shared with you section" instead opening folder its redirecting to root directory and icon of the shared folder is not same. 

"Shared with you" inside this section shared folder have icon

"All files" inside this section shared folder dont have icon

https://github.com/nextcloud/server/assets/67455295/76d9f34e-42dc-4397-aaec-e42c1cf5c1cb

### Steps to reproduce

1. Share folder with different user
2. Login with other user credentials
3. Try to open shared folder

### Expected behavior

Shared folder must open itself from any section and icon must be same for the shared folder in any section.

### Nextcloud Server version

28.0.6

### Log

[nextcloud.log](https://github.com/user-attachments/files/15972396/nextcloud.log)

**Comment by Fenn-CS** [comment]
Not able to reproduce with current information.

**Comment by Fenn-CS** [comment]
Solved in https://github.com/nextcloud/server/pull/45611

**Comment by DaphneMuller** [comment]
@Fenn-CS do you have any timeline for this issue? The support ticket will reach it's SLA deadline in 5 working days.

**Comment by susnux** [comment]
@DaphneMuller next maintenance release will be 28.0.9, this would be the timeline for a fix here.
