### ISSUE TITLE
[Bug]: Error while running background job `OCA\\DAV\\Migration\\BuildSocialSearchIndexBackgroundJob`

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#46100]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Error logged after upgrading to 29.0.3

### Steps to reproduce

1. upgrade to 29.0.3
2. see error in the logs
```json
{
  "reqId": "625OdztVi2fbvKqsf9dR",
  "level": 3,
  "time": "2024-06-25T10:57:17+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "core",
  "method": "",
  "url": "--",
  "message": "Error while running background job OCA\\DAV\\Migration\\BuildSocialSearchIndexBackgroundJob (id: 976, arguments: {\"offset\":0,\"stopAt\":23})",
  "userAgent": "--",
  "version": "29.0.3.4",
  "exception": {
    "Exception": "TypeError",
    "Message": "OCA\\DAV\\CardDAV\\CardDavBackend::getUID(): Argument #1 ($cardData) must be of type string, resource given, called in /var/www/html/apps/dav/lib/CardDAV/CardDavBackend.php on line 708",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/apps/dav/lib/CardDAV/CardDavBackend.php",
        "line": 708,
        "function": "getUID",
        "class": "OCA\\DAV\\CardDAV\\CardDavBackend",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php",
        "line": 90,
        "function": "updateCard",
        "class": "OCA\\DAV\\CardDAV\\CardDavBackend",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/html/apps/dav/lib/Migration/BuildSocialSearchIndexBackgroundJob.php",
        "line": 53,
        "function": "buildIndex",
        "class": "OCA\\DAV\\Migration\\BuildSocialSearchIndexBackgroundJob",
        "type": "->",
        "args": [
          23,
          23
        ]
      },
      {
        "file": "/var/www/html/lib/public/BackgroundJob/Job.php",
        "line": 80,
        "function": "run",
        "class": "OCA\\DAV\\Migration\\BuildSocialSearchIndexBackgroundJob",
        "type": "->",
        "args": [
          [
            0,
            23
          ]
        ]
      },
      {
        "file": "/var/www/html/lib/public/BackgroundJob/QueuedJob.php",
        "line": 57,
        "function": "start",
        "class": "OCP\\BackgroundJob\\Job",
        "type": "->",
        "args": [
          [
            "OC\\BackgroundJob\\JobList"
          ]
        ]
      },
      {
        "file": "/var/www/html/lib/public/BackgroundJob/QueuedJob.php",
        "line": 47,
        "function": "start",
        "class": "OCP\\BackgroundJob\\QueuedJob",
        "type": "->",
        "args": [
          [
            "OC\\BackgroundJob\\JobList"
          ]
        ]
      },
      {
        "file": "/var/www/html/cron.php",
        "line": 177,
        "function": "execute",
        "class": "OCP\\BackgroundJob\\QueuedJob",
        "type": "->",
        "args": [
          [
            "OC\\BackgroundJob\\JobList"
          ]
        ]
      }
    ],
    "File": "/var/www/html/apps/dav/lib/CardDAV/CardDavBackend.php",
    "Line": 1477,
    "message": "Error while running background job OCA\\DAV\\Migration\\BuildSocialSearchIndexBackgroundJob (id: 976, arguments: {\"offset\":0,\"stopAt\":23})",
    "exception": [],
    "CustomMessage": "Error while running background job OCA\\DAV\\Migration\\BuildSocialSearchIndexBackgroundJob (id: 976, arguments: {\"offset\":0,\"stopAt\":23})"
  },
  "id": "667aa2fd69054"
}
```

### Expected behavior

should not log an error

### Installation method

Official All-in-One appliance

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ChristophWurst** [comment]
This is similar to https://github.com/nextcloud/server/issues/21696. The LONGTEXT column is apparently returned as string|resource but we expect it to always be string

**Comment by ashe0047** [comment]
Is there a fix coming soon for this bug?

**Comment by kelke** [comment]
I see a check next to  [nextcloud: increase to 29.0.3 #4886](https://github.com/nextcloud/all-in-one/issues/4818).
<img width="795" alt="image" src="https://github.com/user-attachments/assets/af848bb6-21c6-4aa6-81a2-f696dad97d34">

Does that mean this issue is ssolved?

**Comment by vladbejenaru** [comment]
> Does that mean this issue is solved?

This just completed the my collection of errors on a fresh upgrade to 29.0.6... tbh the other errors were on the 29.0.3... this is new ;-)

**Comment by wolandtel** [comment]
Still actual for 30.0.2:

> Background job OC\Core\BackgroundJobs\GenerateMetadataJob (id: 3466, arguments: null) ran for 16934 seconds                                             2024-11-15T02:09:39+00:00
> TypeError: OCA\DAV\CardDAV\CardDavBackend::getUID(): Argument #1 ($cardData) must be of type string, resource given, called in 
> /var/www/s.woland.me/apps/dav/lib/CardDAV/CardDavBackend.php on line 680 at apps/dav/lib/CardDAV/CardDavBackend.php line 1449

**Comment by szaimen** [comment]
🎉🎉🎉
