### ISSUE TITLE
ISSUE 45047  SUCKS 

### ISSUE THREAD

**Issue by cybergitti** [nextcloud/server#46131]
Many users that are hosting their NC instance are angry and can't help themselfs.
https://github.com/nextcloud/server/issues/45047

P L E A S E   make this Issue go away with the next Update.  Take your time to test on various hosted systems before you make valuable users go away from NC by this.

**Comment by solracsf** [comment]
Opening a new issue to talk about another issue will not help in any way.
This is a community project, hence 3 options here:
1. Wait for someone to fix it _(free, can be long)_
2. Fix it by yourself, or hire someone to do it for you _(paid, can be fast)_ 
3. Get a Nextcloud Professional Subscription: https://nextcloud.com/enterprise/ _(paid, can be fast)_
