### ISSUE TITLE
[App Files] Possibility to navigate indefinitely to the right with a Drag and drop

### ISSUE THREAD

**Issue by brice-shadow** [nextcloud/server#46181]
# Reproduction
**Reproducible ?**
- [x] Yes.
- [ ] No.

**Regularity ?**  
- [x] Always.
- [ ] Sometimes.
- [ ] Unable to reproduce.

**Regression ?**
- [x] Yes.
- [ ] No.
- [ ] New Feature.
 
**Steps to reproduce ?**

1. Open web app
2. Drag a file to the right

**Obtained Results :** The file view gets to the right indefinitely 

![Image](https://github.com/nextcloud/server/assets/173074264/ee94105b-41eb-4ec0-8831-4296c041772e)

# Environment and versions
| 27.1.7.3  |  |

**Browser used**
- [x] Chrome Windows
- [x] Firefox Windows
- [ ] Opera
- [ ] Safari

**Comment by AndyScherzinger** [comment]
This is (still) as far as I remember when originally raised not the case on a vanilla Nextcloud in grid (or list) view. So this is related to the customizing on top.

**Comment by maximelehericy** [comment]
@Jb-tauch-shadow I can't reproduce in latest 30, could you retry and tell us if that is fixed or not ?

**Comment by skjnldsv** [comment]
Same, I guess the new files app fixed it

**Comment by skjnldsv** [comment]
Please upgrade to 28 or above
