### ISSUE TITLE
[Bug]: Can't start Nextcloud because the version of the data (27.0.2.1) is more than one major version behind the docker image version (29.0.3.4) and upgrading more than one major version is not supported. Please run an image tagged for the major version 28 first.

### ISSUE THREAD

**Issue by drumstick77** [nextcloud/server#46198]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Can't start Nextcloud because the version of the data (27.0.2.1) is more than one major version behind the docker image version (29.0.3.4) and upgrading more than one major version is not supported. Please run an image tagged for the major version 28 first.

i tried standing this up using portainer on both stack script or creating container from scratch. this is a new installation of nextcloud. not sure what else to do as never had issues with nextcloud installation like this before.

### Steps to reproduce

Can't start Nextcloud because the version of the data (27.0.2.1) is more than one major version behind the docker image version (29.0.3.4) and upgrading more than one major version is not supported. Please run an image tagged for the major version 28 first.

i tried standing this up using portainer on both stack script or creating container from scratch. this is a new installation of nextcloud. not sure what else to do as never had issues with nextcloud installation like this before.

### Expected behavior

it should just start.

### Installation method

Community Docker image

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
See if this helps.
https://help.nextcloud.com/t/cant-start-nextcloud-because-the-version-of-the-data-is-higher-than-the-docker-image-version-and-downgrading-is-not-supported/109438/7

If not, you should post on the forum, not here. Thanks 👍
