### ISSUE TITLE
[Bug]: Group admins have more privileges than what the docs state

### ISSUE THREAD

**Issue by someone-somenet-org** [nextcloud/server#46253]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The docs state:
```
Group Admin
Group admins are granted administrative privileges on specific groups, and can add and remove users from their groups.
```

But it seems like group admins can do more like modify the username, password, email addresses or storage quotas of users in their groups, which sounds like a huge oversight and security issue to me.

### Steps to reproduce

1. Create group
2. Add userA to group
3. Add userB to group and make userB group admin
4. login as userB and goto user management
5. change userA's email-address or quota or username

### Expected behavior

Group admins being allowed to do exactly what the docs state: add and remove users from their groups and thats it.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by solracsf** [comment]
You're reading wrongly IMO. Even if it's not fully documented, it states:

> Group admins are granted administrative privileges

By "administrative privileges", it means username, password, email, quotas.

> and can add and remove users from their groups

Please note the "and".

**Comment by joshtrichards** [comment]
Thanks for your report, but the docs match the behavior. If you think the documentation could be clearer in some way about this topic, feel free to click *Edit on GitHub* in the upper right hand corner of the documentation to propose a possible change.

> which sounds like a huge oversight and security issue to me.

For future reference, there is a banner at the top of our bug reporting template that says this:

---

🚨 SECURITY INFO

If you are reporting a security concern, please report it via [our HackerOne page](https://hackerone.com/nextcloud) instead and review our [security policy](https://nextcloud.com/security/).
This allows us to coordinate the fix and release without potentially exposing all Nextcloud servers and users in the meantime.
It also may qualify your report for a bug bounty reward.
Thank you for helping make Nextcloud more secure!

---

**Comment by joshtrichards** [comment]
Clarification pending in: nextcloud/documentation#11956
