### ISSUE TITLE
[Bug]: Plain background broken on master/30

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#46277]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![background-color](https://github.com/nextcloud/server/assets/1315170/5082e15e-97b8-40ed-85c0-436b55731d90)

### Steps to reproduce

1. go to settings and choose any plain background color
2.
3.

### Expected behavior

plain background color being used

### Installation method

None

### Nextcloud Server version

master

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by szaimen** [comment]
cc @nextcloud/server-frontend

**Comment by AndyScherzinger** [comment]
cc @sorbaugh

**Comment by susnux** [comment]
@AndyScherzinger I tried to reproduce this issue but for me it works as expected I can not see the white background issue like in your screen cast.
Could you have a look at the browser console for any errors?

We also have Cypress tests for this and they also succeed :thinking:

**Comment by susnux** [comment]
But from the color picker in your screen recording I can tell that this is not current master. Does it work now or still the same issue?
As I can not reproduce this issue locally.

From the recording it seems like the value is correctly set but then either a background image or something else overwrites it...

**Comment by AndyScherzinger** [comment]
<img width="790" alt="2024-07-10 21_56_47-Appearance and accessibility - Nextcloud Daily – Mozilla Firefox" src="https://github.com/nextcloud/server/assets/1315170/eed5fa5d-69a4-4038-ba0f-57964494f6b4">

Just tested again on daily. Issue still present for me

**Comment by susnux** [comment]
Caused by the text app which is always loading this styles:
https://github.com/nextcloud/text/blob/837ca322c032da66220a81cae95125bce5dbd6a7/src/views/DirectEditing.vue#L128

cc @juliushaertl

**Comment by juliushaertl** [comment]
Fixed, thanks to @susnux in https://github.com/nextcloud/text/pull/6026
