### ISSUE TITLE
[Bug]: Dark icons color with some UI colors (from the default color palette)

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/server#46274]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Following last @AndyScherzinger comment in https://github.com/nextcloud/server/pull/43319), I open this new issue.  
IMO, the chosen color should be associated to white text and icons.
![2024-07-03_11-15](https://github.com/nextcloud/server/assets/33763786/c5cfedbe-f437-439e-b40a-95bb077d2e66)
![2024-07-03_11-16](https://github.com/nextcloud/server/assets/33763786/778816f1-9d31-4953-80d3-af1404a7088c)

### Steps to reproduce

1. Change UI color to dark cyan
2. Notice at least what's in above screenshots and conclude that it's not very readable

### Expected behavior

With that background color (and maybe some others = other colors should be checked), texts and icons should be white.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

28

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nc28.test.mydomain.fr"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "28.0.6.1",
    "overwrite.cli.url": "https:\/\/nc28.test.mydomain.fr",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "log_type": "file",
    "logfile": "\/var\/log\/nextcloud\/nc28.test.mydomain.fr\/nextcloud.log",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "password": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "dbindex": 1,
        "timeout": 0
    },
    "skeletondirectory": "",
    "logtimezone": "Europe\/Paris",
    "updater.release.channel": "beta",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "default_language": "fr",
    "default_phone_region": "FR",
    "defaultapp": "files",
    "trashbin_retention_obligation": "20,40",
    "versions_retention_obligation": "auto,40",
    "appstoreurl": "https:\/\/apps.nextcloud.com\/api\/v1",
    "check_for_working_wellknown_setup": false,
    "quota_include_external_storage": false,
    "cron_log": true,
    "has_internet_connection": true,
    "updatechecker": true,
    "appstoreenabled": true,
    "filelocking.enabled": true,
    "session_keepalive": true,
    "knowledgebaseenabled": true,
    "allow_user_to_change_display_name": true,
    "enable_previews": true,
    "enable_avatars": true,
    "auth.bruteforce.protection.enabled": true,
    "loglevel": 1,
    "log_rotate_size": 104857600,
    "mail_smtpauth": 1,
    "mail_smtpport": 465,
    "session_lifetime": 86400,
    "remember_login_cookie_lifetime": 1296000,
    "preview_max_filesize_image": 50,
    "activity_expire_days": 120,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "app_install_overwrite": [
        "admin_audit",
        "user_ldap",
        "workspace"
    ],
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "maintenance": false,
    "maintenance_window_start": 1
}
```

### List of activated Apps

```shell
Enabled:
 - activity: 2.20.0
 - admin_audit: 1.18.0
 - assistant: 1.0.8
 - bbb: 2.6.0
 - calendar: 4.7.2
 - circles: 28.0.0
 - cloud_federation_api: 1.11.0
 - collectives: 2.11.0
 - comments: 1.18.0
 - contacts: 5.5.3
 - contactsinteraction: 1.9.0
 - context_chat: 2.1.1
 - dashboard: 7.8.0
 - dav: 1.29.1
 - deck: 1.12.2
 - electronicsignatures: 3.0.0
 - federatedfilesharing: 1.18.0
 - federation: 1.18.0
 - files: 2.0.0
 - files_accesscontrol: 1.18.1
 - files_automatedtagging: 1.18.0
 - files_pdfviewer: 2.9.0
 - files_reminders: 1.1.0
 - files_sharing: 1.20.0
 - files_trashbin: 1.18.0
 - files_versions: 1.21.0
 - firstrunwizard: 2.17.0
 - groupfolders: 16.0.6
 - impersonate: 1.15.0
 - jitsi: 0.18.0
 - logreader: 2.13.0
 - lookup_server_connector: 1.16.0
 - mail: 3.6.0
 - nextcloud_announcements: 1.17.0
 - notifications: 2.16.0
 - oauth2: 1.16.3
 - onlyoffice: 9.2.0
 - password_policy: 1.18.0
 - photos: 2.4.0
 - privacy: 1.12.0
 - provisioning_api: 1.18.0
 - recommendations: 2.0.0
 - related_resources: 1.3.0
 - richdocuments: 8.3.5
 - serverinfo: 1.18.0
 - settings: 1.10.1
 - sharebymail: 1.18.0
 - support: 1.11.1
 - systemtags: 1.18.0
 - text: 3.9.1
 - theming: 2.3.0
 - twofactor_backupcodes: 1.17.0
 - updatenotification: 1.18.0
 - user_ldap: 1.19.0
 - user_status: 1.8.1
 - viewer: 2.2.0
 - weather_status: 1.8.0
 - workflow_pdf_converter: 1.13.0
 - workflow_script: 1.13.1
 - workflowengine: 2.10.0
 - workspace: 3.2.0
Disabled:
 - approval: 1.3.0
 - bruteforcesettings
 - encryption
 - files_external
 - survey_client: 1.16.0
 - suspicious_login
 - twofactor_totp
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Can be provided if necessary
```

### Additional info

Can be provided if necessary

**Comment by AndyScherzinger** [comment]
Also happening on master/30
<img width="964" alt="2024-07-03 11_40_05-Erscheinungsbild und Barrierefreiheit - Nextcloud Daily – Mozilla Firefox" src="https://github.com/nextcloud/server/assets/1315170/4926881d-13c5-480f-bec4-b19f4cd6331f">
<img width="966" alt="2024-07-03 11_41_19-Dateien - Nextcloud Daily – Mozilla Firefox" src="https://github.com/nextcloud/server/assets/1315170/97e632fe-4c7f-40ec-8952-460744e04242">

**Comment by susnux** [comment]
@AndyScherzinger for current master it works as expected (see below)

@Jerome-Herbinet thank you for the report, there are two things here on your screenshots:
1. The black color of the "current app" indicator on the main navigation, **this is a bug**
2. The black icons on the primary buttons, this *is not* a bug.

The icon / font color is chosen by accessibility constraints and white color does not have a high enough contrast on that background color:

bright text | dark text
---|---
![Screenshot 2024-07-03 at 11-55-46 WebAIM Contrast Checker](https://github.com/nextcloud/server/assets/1855448/874ad1b7-71fa-40bd-ad02-50224abc757d) | ![Screenshot 2024-07-03 at 11-55-55 WebAIM Contrast Checker](https://github.com/nextcloud/server/assets/1855448/d3675636-3f73-4422-b47d-23f2f321c335)

**Comment by Antreesy** [comment]
For the header icons, it's worth to mention it here as well:

Also reported in: https://github.com/nextcloud/notifications/issues/1962#issuecomment-2198027780
Should be consistent with nextcloud/vue 8.14.0 release and bump https://github.com/nextcloud-libraries/nextcloud-vue/pull/5747
After that, we need to check and adjust internal styles at server for components:
  - [ ] UnifiedSearch (NcHeaderMenu)
  - [ ] ContactsMenu (NcHeaderMenu)
  - [ ] Assistant (? but probably also NcHeaderMenu)
  - [ ] AppMenu (NcActions `aria-label="More apps"`)

**Comment by susnux** [comment]
> The black color of the "current app" indicator on the main navigation, **this is a bug**

This is already fixed with https://github.com/nextcloud/server/pull/45552 on Nextcloud 28.0.7

**Comment by susnux** [comment]
Fixed with theming changes in 30, for 29 this is expected behavior (fixed as good as possible in the components library).
