### ISSUE TITLE
[Bug]: Cannot rename files since Nc 29.0.3

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/server#46288]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When renaming a file, the file is opened instead

See screen recording.

[vokoscreenNG-2024-07-03_17-00-56.webm](https://github.com/nextcloud/server/assets/85954408/508699fb-ae68-471c-ac5a-889ff80b4e5e)

In the screen recording renaming is attempted four times, for just one of them the renaming is correct.

I think that it worked ok for 29.0.2

### Steps to reproduce

1. From the three dots menu, select "Rename"
2. Try to rename by clicking on the file name text area

### Expected behavior

The file is renamed

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 28.0.1 to 28.0.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Fixed in #46018
