### ISSUE TITLE
Remove jQuery Migrate

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#4628]
Ref http://research.insecurelabs.org/jquery/test/

**Comment by MorrisJobke** [comment]
* [ ] gallery app

<img width="1394" alt="bildschirmfoto 2017-05-01 um 17 31 44" src="https://cloud.githubusercontent.com/assets/245432/25593672/1526b5d6-2e94-11e7-894e-e88c4e254a26.png">

* [ ] calendar app (creating a event and selecting a date)

<img width="1356" alt="bildschirmfoto 2017-05-01 um 17 34 46" src="https://cloud.githubusercontent.com/assets/245432/25593777/81e44e04-2e94-11e7-8a68-546d0aed5715.png">

* [ ] contacts app (opening the web UI for contacts)

<img width="1353" alt="bildschirmfoto 2017-05-01 um 17 35 27" src="https://cloud.githubusercontent.com/assets/245432/25593820/a7bee5ee-2e94-11e7-9d41-54db5af40909.png">



That are the things I noticed by some clicking. We should simply drop it very early and ask the developers to check their apps. Contacts and Calendar seem to heavily use jquery-ui which uses many of the methods of the jquery-migrate file. 🙈

**Comment by MorrisJobke** [comment]
* [ ] files_pdfviewer when opening a PDF

<img width="1479" alt="bildschirmfoto 2017-05-01 um 17 45 07" src="https://cloud.githubusercontent.com/assets/245432/25594237/0f1ec2e4-2e96-11e7-820d-b520f4eda8f6.png">

**Comment by georgehrke** [comment]
> calendar app (creating a event and selecting a date)

FullCalendar comes even bundled with jQuery 3.2.1. Not sure why it's invoking jquery-migrate. Should simply work without it.

I think we can safely ignore the `attr() might use property instead of attribute` warning. The `jQuery.attrFn` and `jQuery.fn.load()` might be more tricky to fix.

**Comment by skjnldsv** [comment]
We should be able to remove it for 18 (calendar don't have it, gallery for 18, contacts don't have it...)

**Comment by deeztek** [comment]
I have the same question. We have a finding of jquery 2.1.4 on NC 22 from a pen test. Need to be able to answer why such a low version of jquery is used in NC.

**Comment by susnux** [comment]
https://github.com/nextcloud/server/pull/43469
