### ISSUE TITLE
App navigation styles: entries in folders not highlighted correctly, incorrect padding for entries with counters

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/server#4629]
This is on master

![news2](https://cloud.githubusercontent.com/assets/195053/25583501/539a686e-2e92-11e7-9e45-de8a6a327abd.png)

Which entry is active? egghead.io :)

The active styles dont seem to be set correctly for entries in folders.

Another thing that you notice is that entries with counters seem to incorrect right padding since the counters are painted over the text.

@jancborchardt

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
Fixed by @skjnldsv in https://github.com/nextcloud/server/pull/6399
