### ISSUE TITLE
[Bug]: timeout not set in S3Client

### ISSUE THREAD

**Issue by FedericoHeichou** [nextcloud/server#46303]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The timeout is not set in the S3Client options.  

https://github.com/nextcloud/server/blob/03d71e859cc28adcb774f60f4955b7ce0b41f716/lib/private/Files/ObjectStore/S3ConnectionTrait.php#L92-L103

If my s3 is unreachable and I run `occ file:scan`, it sets a lock on the file and hangs forever.  

Changing the options like this works
```
'http' => ['verify' => $this->getCertificateBundlePath(), 'connect_timeout' => 10, 'timeout' => 10],
```
But it does not log anything in the file:scan and it is not marked as an error (maybe this is normal).

### Steps to reproduce

1. Setup a external storage with type Amazon S3
2. Simulate a network problem
3. Do `occ files:scan`

### Expected behavior

There should be a (configurable) timeout and should raise a error.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
PR at https://github.com/nextcloud/server/pull/46317
