### ISSUE TITLE
updateFilecache with a custom mime-type doesn't always work

### ISSUE THREAD

**Issue by geiseri** [nextcloud/server#4631]
### Steps to reproduce
1. Add ' \OC::$server->getMimeTypeLoader()->updateFilecache($ext, $mimetypeId);` to a on install event for a custom application.  The full source for this can be found [at my project site](https://bitbucket.org/geiseri/nextcloud_drawio/src/69418fb60f7267deea20455bd1bbf3a44f381125/lib/Migration/AddMimetypeToFilecache.php?at=master&fileviewer=file-view-default#AddMimetypeToFilecache.php-20)
2. Open file manager and look at the type of the file.
3. Sometimes the custom file type comes back as octet-stream.

### Expected behaviour
It should always use the custom mime-type for that file extension

### Actual behaviour
Randomly the mime-type comes back as octet-stream, it sometimes can be fixed by disabling and enabling the app

### Server configuration

**Operating system**:
Ubuntu 16.04
**Web server:**
Apache

**Database:**
SQLite

**PHP version:**
7.0.15

**Nextcloud version:** (see Nextcloud admin page)
head 11stable from git

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
GitHub

It seems that the [keepweb](https://github.com/jhass/nextcloud-keeweb) app has the same problem and its a limitation of nextcloud.  Is there a better way to add custom mime-types for an application?

**Comment by MorrisJobke** [comment]
cc @nickvergessen @rullzer @icewind1991

**Comment by nickvergessen** [comment]
Fixed with https://github.com/nextcloud/server/pull/4810

**Comment by geiseri** [comment]
Is this something that can be backported?

**Comment by nickvergessen** [comment]
I think it's little and specific enough: https://github.com/nextcloud/server/pull/4913
