### ISSUE TITLE
message "The current PHP memory limit is below the recommended value of 512MB." should be omitted if memory limit is unlimited (-1)

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/server#46347]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the solution you'd like**

No message, if the php memory is set to unlimited = -1 , a number which is lower than 512MB

**Comment by solracsf** [comment]
This is already checked:

https://github.com/nextcloud/server/blob/03b1918c5852af63cb419a1cdf04e0ae499a0403/lib/private/MemoryInfo.php#L27
