### ISSUE TITLE
Speed up processing of VCFs when opening the contacts menu

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#4639]
Opening the contacts menu results for me to 627 calls to `Sabre\VObject\Parser\MimeDir::readLine` which takes alone around 0.75 seconds.

Ref https://blackfire.io/profiles/2a140454-bfeb-4241-90a3-a9c8012f81e2/graph

**Comment by jancborchardt** [comment]
Yup, I agree opening the Contacts menu is a tad slow now and we should look into ways how to speed it up. cc @ChristophWurst and @irgendwie @Henni maybe you can help regarding Contacts? :)

**Comment by rullzer** [comment]
Once I finish https://github.com/nextcloud/server/issues/4653 this should happen a lot less. Lets see how it is then.
