### ISSUE TITLE
Undefined index: name at /var/www/html/3rdparty/sabre/dav/lib/CardDAV/Xml/Filter/AddressData.php#56

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#4640]
> {"reqId":"24LSx6QaFI1HbCKLFkMB","level":3,"time":"2017-05-01T21:04:26+00:00","remoteAddr":"XXXXX","user":"jos","app":"PHP","method":"REPORT","url":"\/remote.php\/dav\/addressbooks\/users\/jos\/Nextcloud_shared_by_Nextcloud\/","message":"Undefined index: name at \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/CardDAV\/Xml\/Filter\/AddressData.php#56","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/534.34 (KHTML, like Gecko) akonadi_davgroupware_resource_1\/5.4.3 Safari\/534.34","version":"12.0.0.15"}

**Comment by MorrisJobke** [comment]
cc @rullzer @icewind1991 @georgehrke

**Comment by MorrisJobke** [comment]
I couldn't see this anymore in the logs :/

**Comment by timmmmmey** [comment]
Why is this one closed? I've got lots of them in combination with z-push and outlook.
`
{"reqId":"ZyX2LDJRJOUhPTm21eRh","level":3,"time":"2018-04-13T11:43:20+00:00","remoteAddr":"yyy.yyy.yyy.yyy","user":"xxx","app":"PHP","method":"REPORT","url":"\/owncloud\/remote.php\/dav\/addressbooks\/users\/xxx\/default\/","message":"Undefined index: name at \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/CardDAV\/Xml\/Filter\/AddressData.php#56","userAgent":"Z-Push CardDAV\/0.6.c","version":"13.0.1.1"}
`

**Comment by noci2012** [comment]
See: https://github.com/nextcloud/server/issues/7654 for more info.
