### ISSUE TITLE
'Delete user' button disappears off-screen

### ISSUE THREAD

**Issue by keunes** [nextcloud/server#4641]
### Steps to reproduce
1. have a small screen
2. look for the trash button in the admin's users screen
![screenshot from 2017-05-01 23-01-22](https://cloud.githubusercontent.com/assets/11229646/25595033/956f5f48-2ec3-11e7-8f70-db1cf92f5d87.png)

### Expected behaviour
Schrink location column

### Actual behaviour
Trash button disappears 'off screen', its very side only reachable when going full-screen in browser (F11) while still not being properly visible behaviour.

### Server configuration
**Nextcloud version:** 11.0.3 (stable)
**Updated from an older Nextcloud/ownCloud or fresh install:** fresh 11.0.2 install

### Client configuration
**Browser:** Firefox 53.0 (64-bit)
**Operating system:** Ubuntu 16.04

**Comment by jancborchardt** [comment]
That’s why by default, the location column is not visible. :) You can disable that column again in the bottom left settings – as it seems all the users are simply in their own subfolder of the same structure, not different paths.

**Comment by keunes** [comment]
Ah, yeah. I figured out that option (again) after posting this. Still it could be a nice tweak to shrink the other columns, or, now I think of it; to make the trash icon as an overlay at the right side of the row.

**Comment by MorrisJobke** [comment]
Sadly this is not that easy, because those columns also need their space. We have some ideas of a refreshed user management in mind, but nothing yet implemented. Stay tuned. I will close this ticket for now.
