### ISSUE TITLE
Updater needs to invalidate existing appstore cache

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#4642]
The updater needs to invalidate the existing locally appstore cache data.

**Comment by LukasReschke** [comment]
Also this causes "Repair warning: Could not install core app bundle: Could not download app bruteforcesettings". Just documenting this here so that people can find this when using the search app.

**Comment by LukasReschke** [comment]
Partially fixed with https://github.com/nextcloud/server/issues/4650 as in after update new apps are available from the app settings but this is not yet triggered on the install page. So reopening. But better than before :)

**Comment by rullzer** [comment]
Ok lets do it explicitly then...
