### ISSUE TITLE
Jumping to file directly is not working

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#4644]
When I click a link in the activity app to a file in a subfolder such as "Marketing/Blogs" then the file view opens and the file is displayed in the sidebar but the list of files is the one of my root folder. Also the DAV request is sent to the root folder.

**Comment by jancborchardt** [comment]
cc @icewind1991 @schiessle?

**Comment by icewind1991** [comment]
cant reproduce

**Comment by LukasReschke** [comment]
@icewind1991 open the activity app on c.nc.c and click a link to a file :wink:

**Comment by rullzer** [comment]
I can reproduce. It is a timing thing. I'll see if I can find which commit broke it...

**Comment by rullzer** [comment]
First bad commit 3f36548a6d7c67857bf8fed1de7a81828e4c14a3
