### ISSUE TITLE
[Bug]: "No files in here" after logging in, refresh logs me out, not able to login again

### ISSUE THREAD

**Issue by Japhys** [nextcloud/server#46441]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If I am able to login and [a lot of times I am not without restarting container](https://github.com/nextcloud/all-in-one/discussions/4656). I very often see "No file here" First time I saw this I nearly sh*t myself :) After a refresh most of the time I am being logged out and unable to login again. I need to restart docker containers to be able to login again (if I am lucky) and then pray files are visible. See also https://github.com/nextcloud/all-in-one/discussions/4656

### Steps to reproduce

1. login
2. No files
3. Refreshing logs me out of NC
4. Login is impossible
5. Restart containers
6. If I am lucky I can login and see files otherwise repeat 5

### Expected behavior

be able to login and see files :)

![2024-07-11_103437](https://github.com/nextcloud/server/assets/24695937/015c7040-1ea9-46a0-bafd-2cd9422c70af)

![Screenshot 2024-07-11 at 10-42-27 Inloggen – Nextcloud](https://github.com/nextcloud/server/assets/24695937/67336795-19fa-46a6-a16e-f3f22cce9fb2)

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Logs

I would love to include logs, if someone can direct me to the right logs that would be great.

**Comment by joshtrichards** [comment]
> I am also using NGINX proxy manager

Is *Cache Assets* on or off in NPM?

**Comment by Japhys** [comment]
@joshtrichards  Cache Assets is on

**Comment by joshtrichards** [comment]
Turn it off. That is the culprit.
