### ISSUE TITLE
[Bug]: "Could not find resource text/js/.js to load"

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/server#46502]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Over the last two days, I see this message recurring over and over in the log:

`{"reqId":"**","level":3,"time":"**","remoteAddr":"**","user":"**","app":"jsresourceloader","method":"GET","url":"/apps/files/","message":"Could not find resource text/js/.js to load","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0","version":"29.0.3.4","data":{"app":"jsresourceloader"},"id":"***"}`

### Steps to reproduce

This seems to be triggered whenever the affected user uses the files app

### Expected behavior

There should be no such warning

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 28.0.1 to 28.0.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.***.***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.3.4",
        "overwrite.cli.url": "https:\/\/cloud.***.***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "default_phone_region": "DE",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "activity_use_cached_mountpoints": "true",
        "htaccess.RewriteBase": "\/",
        "default_language": "de",
        "maintenance_window_start": 1,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - announcementcenter: 6.8.1
  - bruteforcesettings: 2.9.0
  - calendar: 4.7.11
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - collectives: 2.12.0
  - comments: 1.19.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - dav: 1.30.1
  - deck: 1.13.1
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_antivirus: 5.5.6
  - files_confidential: 3.0.2
  - files_downloadlimit: 2.0.0
  - files_external: 1.21.0
  - files_fulltextsearch: 29.0.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - forms: 4.2.4
  - fulltextsearch: 29.0.0
  - fulltextsearch_elasticsearch: 29.0.1
  - groupfolders: 17.0.1
  - htmlviewer: 29.2.0
  - impersonate: 1.16.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - nextcloud_announcements: 1.18.0
  - notes: 4.10.0
  - notifications: 2.17.0
  - notify_push: 0.6.12
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - photos: 2.5.0
  - polls: 7.1.3
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - richdocuments: 8.4.3
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - spreed: 19.0.5
  - support: 1.12.0
  - survey_client: 1.17.0
  - suspicious_login: 7.0.0
  - systemtags: 1.19.0
  - tables: 0.7.4
  - tasks: 0.16.0
  - text: 3.10.1
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - twofactor_nextcloud_notification: 3.9.0
  - twofactor_totp: 11.0.0-dev
  - updatenotification: 1.19.1
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0
Disabled:
  - dashboard: 7.9.0 (installed 7.9.0)
  - encryption: 2.17.0
  - user_ldap: 1.20.0
  - user_retention: 1.12.1 (installed 1.12.1)
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"MI5hhqgaSfORUVVjzHOj","level":3,"time":"2024-07-12T15:40:59+00:00","remoteAddr":"*.*.*.*, user":"**","app":"jsresourceloader","method":"GET","url":"/apps/files/","message":"Could not find resource text/js/.js to load","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0","version":"29.0.3.4","data":{"app":"jsresourceloader"},"id":"66914eb922784"}
```

**Comment by yward** [comment]
I had the same issue in nextcloud AIO
Turned out this is not a server issue, it's an app issue caused by the app "htmlviewer" the app is not commonly used as such the low number of reports.

I believe this should be posted in the app repo instead.

**Comment by skjnldsv** [comment]
> I believe this should be posted in the app repo instead.

:point_up:

**Comment by ninjazan420** [comment]
> I had the same issue in nextcloud AIO Turned out this is not a server issue, it's an app issue caused by the app "htmlviewer" the app is not commonly used as such the low number of reports.
> 
> I believe this should be posted in the app repo instead.

Being curious, how did you find the source of this error since there are no further informations in the logs?

**Comment by yward** [comment]
> > I had the same issue in nextcloud AIO Turned out this is not a server issue, it's an app issue caused by the app "htmlviewer" the app is not commonly used as such the low number of reports.
> > I believe this should be posted in the app repo instead.
> 
> Being curious, how did you find the source of this error since there are no further informations in the logs?

We opted not to use the app causing the error as we have other more secure ways to display html/php content (there is an app that allows you to display external links as iframe apps, as long as your remote server is secure and maintained by and you account from cross site vulnerabilities, it should be a safer way to go).

**Comment by yward** [comment]
> > I had the same issue in nextcloud AIO Turned out this is not a server issue, it's an app issue caused by the app "htmlviewer" the app is not commonly used as such the low number of reports.
> > I believe this should be posted in the app repo instead.
> 
> Being curious, how did you find the source of this error since there are no further informations in the logs?

@ninjazan420 basic plugin/app troubleshooting, clear the log disable all apps and enabled one by one while checking the log with each activation, and isolate the app that triggers it

**Comment by ninjazan420** [comment]
> > > I had the same issue in nextcloud AIO Turned out this is not a server issue, it's an app issue caused by the app "htmlviewer" the app is not commonly used as such the low number of reports.
> > > I believe this should be posted in the app repo instead.
> > 
> > 
> > Being curious, how did you find the source of this error since there are no further informations in the logs?
> 
> We opted not to use the app causing the error as we have other more secure ways to display html/php content (there is an app that allows you to display external links as iframe apps, as long as your remote server is secure and maintained by and you account from cross site vulnerabilities, it should be a safer way to go).

Alright, thank you very much :)

**Comment by devnoname120** [comment]
The culprit is in the htmlviewer app, file `lib/Listeners/LoadViewerListener.php`, line 53::

```php
            Util::addScript('text', null, Application::APP_ID);
```

https://git.mdns.eu/nextcloud/htmlviewer/-/blob/ac29e6a7cfe867dea3c87afe37d89ac15e272151/lib/Listeners/LoadViewerListener.php#L53

Maybe it's just an oversight?

cc @marius-wieschollek

**Comment by marius-wieschollek** [comment]
This is not an oversight, it's so i can force NC to load the app after mine and i can register a handler for html files.

**Comment by devnoname120** [comment]
@marius-wieschollek Pardon my ignorance but where can I Iearn more about the `text` app? I couldn't find a reference to it.
