### ISSUE TITLE
[Bug]: Talk Stun Server do not generate any request to connect

### ISSUE THREAD

**Issue by alexrahn71** [nextcloud/server#46530]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

We configured a Stun Server with Coturn, we reviewed the firewall configurations, everything is in order, we did countless communication tests, from the Nextcloud GUI when trying to connect to the STUN server it always failed, we did a tcdump from the server shell to capture the packets that They came out when making the connection request and did not capture any packets

### Steps to reproduce

1. Install Stun/coturn Server
2.Firewall Test
3.Install Talk
4.Set the STUN Sever
5.Try to connect (Fail)
6.tcpdump trying to capture packages (NO one)

### Expected behavior

connect to Stun server

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
Please use the forum for setup questions. Thanks.
https://help.nextcloud.com
