### ISSUE TITLE
[Bug]: "X minutes ago" should switch to "An hour ago" a lot earlier

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#46537]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![image](https://github.com/user-attachments/assets/5e26b3e6-c521-4d91-88b5-732870f59bc3)

^ this is weird. I would never phraze it like that as a human. IMO this should be *An hour ago* or *1.5 hours ago*

### Steps to reproduce

1. Modify a file
2. Wait 80 minutes

### Expected behavior

Human design

### Installation method

None

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
Can you give a try (and review) to https://github.com/nextcloud/server/pull/46574?

**Comment by ChristophWurst** [comment]
Are those strings not generated by the frontend code?

**Comment by solracsf** [comment]
My bad you're right, this function is only used for backend time displays... 🔮 
https://github.com/nextcloud/server/blob/4362ed53614c900c53986b694ea3eea3799ab9c1/apps/files/js/filelist.js#L1859

**Comment by skjnldsv** [comment]
https://github.com/nextcloud-libraries/nextcloud-vue/blob/master/src/components/NcDateTime/NcDateTime.vue and https://github.com/nextcloud-libraries/nextcloud-vue/blob/master/src/composables/useFormatDateTime.ts  ?

**Comment by skjnldsv** [comment]
This is what we use https://github.com/nextcloud/server/blob/aad09764cd67ab751444c74de8b5066ec5564626/apps/files/src/components/FileEntry.vue#L70

**Comment by susnux** [comment]
Probably a topic to bring up as UX with designers.
@nextcloud/designers

**Comment by susnux** [comment]
Another potential issue:
![4 weeks is shown](https://private-user-images.githubusercontent.com/44456699/346035203-49a3f6ce-7011-4f9b-a8e4-441136e71d6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDYyMTgsIm5iZiI6MTcyMzA0NTkxOCwicGF0aCI6Ii80NDQ1NjY5OS8zNDYwMzUyMDMtNDlhM2Y2Y2UtNzAxMS00ZjliLWE4ZTQtNDQxMTM2ZTcxZDZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE1NTE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZWM2ZmI0ZDA0ODk2YjQ1ZDBhODdjZjg3NDFhYjM1ZGJlNDc4M2ZiZWNhMjI4YmUyZDBjYTRlZjE0MGUxOTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0OYR_vkV0fzErcX7FaEu-iisf76qNPe4aSOu8fa6cro)

There should never be "4 weeks" but "1 month", 28 days are very near to a month.

**Comment by jancborchardt** [comment]
Agree with both @ChristophWurst's bug report on minutes and @susnux's point about 4 weeks being more readable as 1 month. :)
