### ISSUE TITLE
Images of profile pictures in VCF should be compressed by the server

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#4653]
For example the picture of Björn in the contacts menu is 1 MB big… – We should add caching (https://github.com/nextcloud/server/issues/4637) but also compress the images on the server.

**Comment by LukasReschke** [comment]
Resizing to max. 256px should be good enough for now.

**Comment by rullzer** [comment]
Mmmm so this is far from ideal. Since we don't want have this load on the server every time the contacts menu is opened as well. Resizing 20 images can easily kill all performance on a pi or something.

**Comment by jancborchardt** [comment]
Remember hidpi phones and that we could soon snyc this as the contact pictures. So while we can show a compressed version depending where it’s viewed, the original should be kept.

**Comment by rullzer** [comment]
@jancborchardt we won't modify the original image. But the current state of the contacts menu is just insane and kills all performance on slower connections. >5mb to show me 9 little images is just insane.
