### ISSUE TITLE
[Bug]: Dashboard with default background shows low resolution logo as full size background

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#46541]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Chrome:

![Bildschirmfoto vom 2024-07-15 17-08-46](https://github.com/user-attachments/assets/2668da6d-c42b-437b-8ebe-cbe71c5a1edb)

Firefox:

![Bildschirmfoto vom 2024-07-15 17-08-39](https://github.com/user-attachments/assets/c00f637b-96ef-4f23-92b9-b85bd240178c)

### Steps to reproduce

1. Log into Nextcloud daily

### Expected behavior

Good design

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by susnux** [comment]
Anything you configured in the user / admin theming? Is everything there set to default?

**Comment by ChristophWurst** [comment]
I'm not aware of setting anything myself

![image](https://github.com/user-attachments/assets/160f32c1-98f9-4e13-85cf-ac4e0d6b904e)

**Comment by susnux** [comment]
The image is wrong also in the settings for you (can not reproduce this), have you tried to force clear the cache?

**Comment by ChristophWurst** [comment]
![image](https://github.com/user-attachments/assets/ea1ea103-7060-4272-9cd1-8afb562dd83b)

tried hard refresh. no changes

**Comment by ChristophWurst** [comment]
The URL `/apps/theming/img/background/jenna-kim-the-globe.webp` is broken. It returns a 32x32 PNG with the Nextcloud icon.

**Comment by ChristophWurst** [comment]
Chrome confirms

![image](https://github.com/user-attachments/assets/876b6abf-89cc-49b7-9b0d-02f6acd26530)

**Comment by susnux** [comment]
How do you deploy? Could you try this PR?

https://github.com/nextcloud/server/pull/46543

**Comment by ChristophWurst** [comment]
^ @tobiasKaminsky for the daily ltd

**Comment by susnux** [comment]
Seems to be the Caddy server in front is not serving it correctly

**Comment by tobiasKaminsky** [comment]
> ^ @tobiasKaminsky for the daily ltd

Timewise daily I cannot do such manual checkouts, only if it is very urgent.

**Comment by susnux** [comment]
We can wait for tomorrow and see if it fixes it, but if not then I guess the Caddy config needs adjustments (I have no idea about caddy :sweat_smile: )

**Comment by tobiasKaminsky** [comment]
Caddy is hardly configured:
```
daily.ltd2.nextcloud.com {
    reverse_proxy localhost:11037
}
```

**Comment by tobiasKaminsky** [comment]
Did a git pull, as PR was already merged.
Looks good now?

**Comment by ChristophWurst** [comment]
Yes looks gut now

**Comment by transducer** [comment]
I still experience this issue on Nextcloud 31.0.6. In Firefox 139.0.4 aarch64 the background is logo.svg.

<img width="1700" alt="Image" src="https://github.com/user-attachments/assets/771943b2-3ac0-4072-9a95-167c90084ffc" />

**Comment by transducer** [comment]
Removing the "background and login image" at /settings/admin/theming fixed the issue.

<img width="1193" alt="Image" src="https://github.com/user-attachments/assets/7e851df8-9130-468d-9272-70175953dda1" />

Strange though this was the default.
