### ISSUE TITLE
[Bug]: Increased space between apps and name when hovering the apps menu

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#46542]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

30:
![Bildschirmfoto vom 2024-07-15 17-17-12](https://github.com/user-attachments/assets/121d7983-2806-4283-a559-4ff30016f556)
29:
![Bildschirmfoto vom 2024-07-15 17-17-04](https://github.com/user-attachments/assets/73761288-3807-40de-9b40-525cbbd26c70)

### Steps to reproduce

1. Log into Nextcloud daily
2. Hover the app menu

### Expected behavior

Good design

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Tested with FF on Linux

**Comment by ChristophWurst** [comment]
@marcoambrosini @susnux can you confirm or is this intentional?

**Comment by marcoambrosini** [comment]
@ChristophWurst not intentional

**Comment by susnux** [comment]
Well both there is a feature where apps can set a unread notification which is shown on the app menu then.
The space is needed to not overlay the text with the unread notification.

**Comment by ChristophWurst** [comment]
Related: we lost the smooth transition

| 29 | 30 |
|--------|--------|
| [Bildschirmaufzeichnung vom 2024-07-31 11-27-09.webm](https://github.com/user-attachments/assets/3537b23d-2c93-4aaf-a55b-fc5b7fd83ca8) | [Bildschirmaufzeichnung vom 2024-07-31 11-27-30.webm](https://github.com/user-attachments/assets/67029285-f3fb-4f07-948b-0fb45f84646e) |

**Comment by jancborchardt** [comment]
Agree with @ChristophWurst, looks strange that both the space is too big and the animation is missing.

@susnux do you have a screenshot how it looks like with the unread notification? Couldn't it just be a circle/bubble (red or otherwise) on the top right of the app icon, like for the notifications icon?

Cc @sorbaugh as this is a high visibility design regression.
