### ISSUE TITLE
blank HTML code for write permission on NC12 Beta1

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/server#4655]
I have downloaded the current Beta 1 of NC12. After downloading I opened the website to install NextCloud. The following error occurs:

![image](https://cloud.githubusercontent.com/assets/1473674/25612842/6ef2850c-2f2c-11e7-9fd4-88891be97fa4.png)

After I set the permission for the Folder, the same Problem is here:

![image](https://cloud.githubusercontent.com/assets/1473674/25613000/09f72620-2f2d-11e7-9b77-203ac57499bd.png)

The link is not correctly shown.

**Comment by ChristophWurst** [comment]
Originates from https://github.com/nextcloud/server/blob/94c2f12226ed005fc2a1e9c440ec70346e9c272a/lib/private/Config.php#L245-L254

**Comment by ChristophWurst** [comment]
Possibly a regression of https://github.com/nextcloud/server/pull/4130
cc @LukasReschke @MorrisJobke

**Comment by ChristophWurst** [comment]
Effected template: https://github.com/nextcloud/server/blob/94c2f12226ed005fc2a1e9c440ec70346e9c272a/core/templates/error.php#L6

**Comment by LukasReschke** [comment]
This should not be reverted as this easily leads to a XSS vulnerability. Let's remove the `<a href` and just add the link as plaintext at the end of the string.

**Comment by MorrisJobke** [comment]
Fi is in #4753
