### ISSUE TITLE
NC12 Beta 1 text files opens in Collabora Online instead of text editor

### ISSUE THREAD

**Issue by guddl** [nextcloud/server#4658]
### Steps to reproduce
1. Use Nextcloud 12 Beta 1
2. Klick on a text file to edit it

### Expected behaviour
The text file should open in the oldschool text editor

### Actual behaviour
The text file opens in Collabora Office

**Comment by jancborchardt** [comment]
Yes, normal txt files should definitely not need to load the full Collabora.

Can you check it out @rullzer @icewind1991? :)

**Comment by LukasReschke** [comment]
Well. Collabora has added the mimetypes as compatible. So they will open with that.

Complain to the richdocuments app 😉 

Ref https://github.com/nextcloud/richdocuments/commit/829b2b77b977102c4df0c1657b1bd7bc68c876ba

**Comment by jancborchardt** [comment]
Opened the issue at https://github.com/nextcloud/richdocuments/issues/43
