### ISSUE TITLE
[Bug]: Clicking in filename while renaming not possible

### ISSUE THREAD

**Issue by ElSi-DVT** [nextcloud/server#46586]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When renaming a file or folder, it was possible to click onto a position of the current filename to select a position.
But now instead of setting the cursor, the folder or file is opened.

![grafik](https://github.com/user-attachments/assets/d144d2ad-0e77-4f1f-a2a6-db1e46cd97b2)

### Steps to reproduce

1. Select a file or folder and click on the three dots.
2. Click on "Rename".
3. Try to click on the current name of the file.

### Expected behavior

Like in the previous versions the cursor position should be set and not the file opened.

### Nextcloud Server version

28.0.7

**Comment by StefInP** [comment]
I have the same issue with NC 29.0.3

**Comment by solracsf** [comment]
Fixed in 28.0.8/29.0.4.
