### ISSUE TITLE
Array to string conversion at /var/www/nextcloud/apps/dav/lib/CalDAV/Activity/Backend.php#561

### ISSUE THREAD

**Issue by olegchensky** [nextcloud/server#46601]
### Steps to reproduce

1. It is enough to create a new event, and we receive 7–15 entries in log.
2.
3.

### Expected behavior

no errors

### Actual behaviour

errors in log

### Calendar app version

last, today updated

### Web server

Apache

### Database engine version

MariaDB

### PHP engine version

PHP 8.2

### Updated from an older installed version or fresh install

None

**Comment by miaulalala** [comment]
Please post your Nextcloud version

**Comment by olegchensky** [comment]
29.0.4

**Comment by dwaxweiler** [comment]
This might be a duplicate of https://github.com/nextcloud/server/issues/37025.

**Comment by joshtrichards** [comment]
Duplicate of #37025
