### ISSUE TITLE
Unfavorable representation of errors during Bundle install, debatable behaviour

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#4661]
Somewhere on some demo, I tried to install the Enterprise bundle. It would not enable LDAP, because php-ldap was not installed. 

What happened: First app was installed, then the LDAP backend failed, and installation of others was cancelled. The error was presented like this (replacing the LDAP backend entry):

![bundle-install-issue](https://cloud.githubusercontent.com/assets/2184312/25618709/482accd8-2f48-11e7-811f-53f5a10cb8e5.png)

My expectation: Install all other apps. The error could be shown inline, but over the whole width and perhaps with a (light) red or yellow background.

**Comment by MorrisJobke** [comment]
cc @LukasReschke @eppfel

**Comment by eppfel** [comment]
Yes, the error should get more width 😁 
Try to have a look the next days...

cc @jancborchardt @nextcloud/designers

**Comment by MorrisJobke** [comment]
@blizzz @eppfel Moved to 12.0.1

**Comment by MorrisJobke** [comment]
Let's fix this in master first and then backport

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by szaimen** [comment]
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!
