### ISSUE TITLE
[Bug]: Missing breadcrumb ellipsis -> Grid view button pushed out of view

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#46635]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Long breadcrumbs are not limited in length. They can take up too much space:

![Bildschirmfoto vom 2024-07-19 13-15-59](https://github.com/user-attachments/assets/cf10b42d-06dd-4d28-a7f4-5ed33a66e0fb)

### Steps to reproduce

1. Create a deep hierarchy with long folder names
2. Navigate to it

### Expected behavior

Responsive design

### Installation method

None

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by skjnldsv** [comment]
Looks more like a component issue? @raimund-schluessler

**Comment by raimund-schluessler** [comment]
I would say the component works as intended, but it's not used "correctly". The breadcrumbs component takes as much space as it is given, which means its container needs to be sized adequately. Currently, `.files-list__breadcrumbs` (the breadcrumbs top element), is instructed to take 100 % of the parents width, which pushes the grid view button out. Applying `width: calc(100% - 64px);` (taking into account the button size and the additional margin of 10 px) would fix this issue, but it feels a bit "hacky". Adjusting the flex layout would probably be better. But see here anyway:

Without the `calc`:
![Screenshot 2024-07-29 at 09-10-10 Dateien - Nextcloud](https://github.com/user-attachments/assets/223e022a-ec6b-4c06-aa73-0797f6782776)

And with `width: calc(100% - 64px);`:
![Screenshot 2024-07-29 at 09-10-33 Dateien - Nextcloud](https://github.com/user-attachments/assets/6f516736-f1d7-4ee8-9cd9-b4a160f4a5e1)

**Comment by skjnldsv** [comment]
Not really, we are using automated flex. Width 100% is expected as `flex-shrink` is enabled.
![image](https://github.com/user-attachments/assets/5fcaba2b-aa15-4555-abfb-1cbc5c6c4ddb)

The breadcrumbs are designed (in Files), to take all the remaining space after all elements are layed out. The Buttons have a flex shring/grow set to 0. Only the breadcrumbs is allowed to resize. That is the clean way. Using calc is not :)

**Comment by raimund-schluessler** [comment]
I know calc is not the way, that's what I meant with "hacky" 😉

However, the flex layout does not work properly here, for some reason. The breadcrumbs container has a 100% parent width without shrinking or respecting its siblings.

**Comment by raimund-schluessler** [comment]
@skjnldsv I had a look again. The problem why the breadcrumbs container `.files-list__breadcrumbs` does not shrink, is that the flex specification states to not shrink a flex item below the minimum size of its child, see https://www.w3.org/TR/css-flexbox-1/#min-size-auto and https://www.bigbinary.com/blog/understanding-the-automatic-minimum-size-of-flex-items.

We either have to set `min-width: 0;` (or any other reasonable value) or `overflow: hidden;` for the breadcrumbs container `.files-list__breadcrumbs` here:

https://github.com/nextcloud/server/blob/6680dd4182962a3d684b8fb1c4bde1a8e5ee5c81/apps/files/src/components/BreadCrumbs.vue#L269-L275

![grafik](https://github.com/user-attachments/assets/21948c68-d026-4842-b7cc-77176a0a52d1)

Result:
![grafik](https://github.com/user-attachments/assets/55b16910-4174-4570-97fa-1fbd77d4dbd7)

@skjnldsv Is that fine for you?

**Comment by skjnldsv** [comment]
> @skjnldsv Is that fine for you?

Nice catch! Seems like it was forgotten!
Let's go for the `min-width: 0;` :+1:
