### ISSUE TITLE
Update with disabled app store

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#4663]
* install stable11
* disable App Store in config.php via `'appstoreenabled' => false,`
* make sure that bruteforcesettings app is not available in any apps folder
* checkout master
* run upgrade

## Expected

* update runs fine

## Actual

* `Repair warning: Could not install core app bundle: Could not download app bruteforcesettings`
* but somehow the update says that everything is fine, is this wanted?

```
Updating <theming> ...
Updated <theming> to 1.3.0
Repair warning: Could not install core app bundle: Could not download app bruteforcesettings
Update successful
Turned off maintenance mode
Reset log level
```

```
{"reqId":"98eOtY7PlhccyvtaFm6Q","level":1,"time":"2017-05-02T13:53:35+00:00","remoteAddr":"","user":"--","app":"updater","method":"--","url":"--","message":"\\OC\\Repair::step: Repair step: Install new core bundle components","userAgent":"--","version":"11.0.3.2"}
{"reqId":"98eOtY7PlhccyvtaFm6Q","level":2,"time":"2017-05-02T13:53:36+00:00","remoteAddr":"","user":"--","app":"updater","method":"--","url":"--","message":"\\OC\\Repair::warning: Repair warning: Could not install core app bundle: Could not download app bruteforcesettings","userAgent":"--","version":"11.0.3.2"}
```

cc @LukasReschke @rullzer

**Comment by LukasReschke** [comment]
> but somehow the update says that everything is fine, is this wanted?

Yes. That's just a warning, stuff won't break or so. You just have fewer functionality :-)

**Comment by MorrisJobke** [comment]
> Yes. That's just a warning, stuff won't break or so. You just have fewer functionality :-)

Okay, then this is expected behaviour. We should document this nevertheless. Let me add it to the release notes.

**Comment by MorrisJobke** [comment]
> Okay, then this is expected behaviour. We should document this nevertheless. Let me add it to the release notes.

https://github.com/nextcloud/documentation/pull/436
