### ISSUE TITLE
[Bug]: File comments broken

### ISSUE THREAD

**Issue by kesselb** [nextcloud/server#46630]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The comments for files section is broken

```
TypeError: f is not a constructor
    mount comments-activity-tab.ts:24
    NextJS 26
    mounted SidebarTab.vue:104
    VueJS 16
index-BK2GMarY.mjs:2:23954
    NextJS 29
    mounted SidebarTab.vue:104
    VueJS 16
```

### Steps to reproduce

1. Login to Nextcloud
2. Open files app
3. Open sidebar
4. Change to activity tab
5. The field to write a comment is missing

[Screencast from 2024-07-19 11-57-04.webm](https://github.com/user-attachments/assets/a7958d3b-a3c3-4f3e-a75a-1227629d53f6)

### Expected behavior

Able to leave a comment ;)

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

Firefox Developer Edition 128.0b9

**Comment by kesselb** [comment]
cc @nextcloud/server-frontend

**Comment by susnux** [comment]
Regression of https://github.com/nextcloud/server/pull/45848

**Comment by graffio-m** [comment]
Installed on vps linux.
[Nextcloud Hub 9](https://nextcloud.com/) (30.0.5)

Same problems. Comments app is enable, but in the sidebar there is no comments area.

**Comment by susnux** [comment]
> Same problems. Comments app is enable, but in the sidebar there is no comments area.

If you have the activity app installed it is combined in the activity tab.
Otherwise please open a new issue.
