### ISSUE TITLE
[Bug]: Delayed visual feedback when uploading a large folder via drag and drop

### ISSUE THREAD

**Issue by kesselb** [nextcloud/server#46641]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

There's a delay between dragging the folder and a visual feedback.

### Steps to reproduce

1. Have a folder with ~4000 images
2. Drag the folder to Nextcloud
3. It takes about 15 seconds until there's some visual feedback

Nextcloud 28:

[9664472 28.webm](https://github.com/user-attachments/assets/64f03d1c-1635-41fd-a77d-1540160d9133)

Nextcloud 27:

[9664472 27.webm](https://github.com/user-attachments/assets/3c1201aa-d8fc-4bbc-9989-7a0b20843ebb)

### Expected behavior

Feedback that the data is processed. 

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

https://github.com/nextcloud/server/blob/5b7dcc1427e996a3154761877d1e11463ed4bef4/apps/files/src/services/DropServiceUtils.ts#L99

The above log message appears when you drop the folder and therefore we should be able to provide some visual feedback already (e.g. we processing the folder, stay tuned ....)

**Comment by susnux** [comment]
This is only drag and drop, not on folder upload using the menu?

**Comment by kesselb** [comment]
> This is only drag and drop, not on folder upload using the menu?

Good point. 

I don't think it's faster when using the upload files menu.

[Screencast from 2024-07-22 17-07-22.webm](https://github.com/user-attachments/assets/b718f373-5af2-4ab3-9aa7-ccacbc69adda)

**Comment by sorbaugh** [comment]
cc @skjnldsv maybe a regression?

**Comment by susnux** [comment]
This is solved with nextcloud-upload v1.5.0 (once it is released). Tested it locally already and there is no delay anymore.

**Comment by susnux** [comment]
ref: https://github.com/nextcloud-libraries/nextcloud-upload/pull/1342

**Comment by kesselb** [comment]
Is the fix backportable to 28?

**Comment by susnux** [comment]
yes

**Comment by susnux** [comment]
31, 30, 29 fixed. Backport for 28 in #48946
