### ISSUE TITLE
[Bug]: Deleted items shows random number (timestamp) after item name

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/server#46657]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If I delete a folder/file, the name of this looks like:
![image](https://github.com/user-attachments/assets/e72e72f9-56ff-460b-b6da-ca61e28aa8c3)

### Steps to reproduce

1. Update to 29.0.4
2. Delete a folder
3. Go to the trashbin

### Expected behavior

no random suffix like .d1721463802

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 28.0.1 to 28.0.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by skjnldsv** [comment]
@susnux did we break the displayname recently?

**Comment by susnux** [comment]
> did we break the displayname recently?

Not really but we fixed showing them, maybe this is already fixed with https://github.com/nextcloud/server/pull/46694

**Comment by solracsf** [comment]
@susnux manually applied https://github.com/nextcloud/server/pull/46694 on v29, trash items still outputs the timestamp.
