### ISSUE TITLE
[Bug]: Renamed files are not refreshed in the web interface + side weird issues

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#46660]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When a file is renamed, old file name remains unless page is maually refresh or browsed aways.

There are alow ohter side weird issues; if selecting renamed file, we have the option to remove it from favourites, while file isn't there (!!) and also if deleting it, it reamains on the interface (but is deleted). 🤒 

### Steps to reproduce

1. Right click on a file
2. Rename it
3. See old file name

![image](https://github.com/user-attachments/assets/929f0618-17ac-4f8c-a593-bf15885ed71c)

### Expected behavior

New file name is visible. Reproducible in 28 and 29.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

29

### Additional info

https://github.com/user-attachments/assets/1adfa50b-27a7-457b-ad28-8ee07a7c646d

**Comment by chrissi55** [comment]
Can confirm this behaviour.
Problems began with update from 29.0.3 to 29.0.4, so seems to be related to only the newest version of NC.

Also posted here:
https://help.nextcloud.com/t/since-update-to-nc-29-0-4-weird-update-behaviour-for-folders-and-file-re-name/198545/4

**Comment by Mer0me** [comment]
see also https://github.com/nextcloud/server/issues/42813

**Comment by artem-bm** [comment]
Also present in the NC 28.0.8
