### ISSUE TITLE
[Bug]: Cannot upload files with mtime set to a small value

### ISSUE THREAD

**Issue by felix-walter** [nextcloud/server#46675]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When uploading files with a small modification timestamp such as `1`, Nextcloud returns the following error:

> X-OC-MTime header must be a valid positive integer

Sometimes, only a generic HTTP 500 error is shown by the web interface and the user needs to check the network requests in the dev. console to see the error message.

This prevents uploading files built with [Nix](https://nixos.org/) without previously changing the modification time for any of those files: Nix sets the timestamp to `1` for ensuring reproducible builds.

The bug occurs due to the [check](https://github.com/nextcloud/server/blob/master/apps/dav/lib/Connector/Sabre/MtimeSanitizer.php#L20) in `apps/dav/lib/Connector/Sabre/MtimeSanitizer.php` introduced in 69b8044b8f957c5a74396025608dd513c8f7ff7d.

As small timestamps such as `1` are perfectly valid values for the modification timestamp, they should be allowed.

### Steps to reproduce

1. Create a file with a low modification timestamp, e.g., via `touch -m -t 197001010100.01 abc.txt`; or build something with Nix and try to upload the result.
2. Try to upload the file, e.g., using the web interface.

### Expected behavior

The files are uploaded successfully and the small timestamp value is preserved.

### Installation method

Official All-in-One appliance

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
The original check for this predates that. It's from #30114. I believe it may have been originally driven by the mtime matter that arose in late 2021 (with the Desktop client). I don't recall the specifics, but we might be able to make the sanitize check more specific these days.

**Comment by skjnldsv** [comment]
This is a wontfix. This measure was taken to fix an important bug which invalid mtimes could trigger a massive file deletion

**Comment by felix-walter** [comment]
Maybe an option in this case would be to show a somewhat sensible error message in the web UI instead of just a HTTP 500? Something such as "The file you are trying to upload has an unsupported modification date, please change it before uploading."?

It took me quite some time to figure out the cause of the issue here.
