### ISSUE TITLE
The {DAV:}property-search element must contain one {DAV:}match and one {DAV:}prop element

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#4668]
```
Sabre\DAV\Exception\BadRequest: HTTP/1.1 400 The {DAV:}property-search element must contain one {DAV:}match and one {DAV:}prop element
[internal function] Sabre\DAVACL\Xml\Request\PrincipalPropertySearchReport xmlDeserialize(Object(Sabre\Xml\Reader))
/var/www/html/3rdparty/sabre/xml/lib/Reader.php - line 246: call_user_func(Array, Object(Sabre\Xml\Reader))
/var/www/html/3rdparty/sabre/xml/lib/Reader.php - line 71: Sabre\Xml\Reader->parseCurrentElement()
/var/www/html/3rdparty/sabre/xml/lib/Service.php - line 118: Sabre\Xml\Reader->parse()
/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 714: Sabre\Xml\Service->parse('<?xml version="...', '/remote.php/dav...', NULL)
[internal function] Sabre\DAV\CorePlugin->httpReport(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method REPORT', Array)
/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/html/apps/dav/lib/Server.php - line 244: Sabre\DAV\Server->exec()
/var/www/html/apps/dav/appinfo/v2/remote.php - line 33: OCA\DAV\Server->exec()
/var/www/html/remote.php - line 162: require_once('/var/www/html/a...')
{main}
```

> {"reqId":"ibyUrSZ0Ot1c5HN5KFyD","level":4,"time":"2017-05-02T17:25:26+00:00","remoteAddr":"XXXXXXX","user":"matthias","app":"webdav","method":"REPORT","url":"\/remote.php\/dav\/principals\/groups\/","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 The {DAV:}property-search element must contain one {DAV:}match and one {DAV:}prop element\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAVACL\\\\Xml\\\\Request\\\\PrincipalPropertySearchReport::xmlDeserialize(Object(Sabre\\\\Xml\\\\Reader))\\n#1 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/xml\\\/lib\\\/Reader.php(246): call_user_func(Array, Object(Sabre\\\\Xml\\\\Reader))\\n#2 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/xml\\\/lib\\\/Reader.php(71): Sabre\\\\Xml\\\\Reader->parseCurrentElement()\\n#3 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/xml\\\/lib\\\/Service.php(118): Sabre\\\\Xml\\\\Reader->parse()\\n#4 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(714): Sabre\\\\Xml\\\\Service->parse('<?xml version=\\\"...', '\\\/remote.php\\\/dav...', NULL)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#8 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Server.php(244): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#11 \\\/var\\\/www\\\/html\\\/remote.php(162): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/Xml\\\/Request\\\/PrincipalPropertySearchReport.php\",\"Line\":106,\"User\":\"matthias\"}","userAgent":"iOS\/10.3.1 (14E304) dataaccessd\/1.0","version":"12.0.0.16"}

**Comment by MorrisJobke** [comment]
cc @icewind1991 @georgehrke

**Comment by MorrisJobke** [comment]
Doesn't happen anymore with the current iOS app.
