### ISSUE TITLE
[Bug]: using Indesign files

### ISSUE THREAD

**Issue by batland** [nextcloud/server#46697]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Good morning,
we tested nextcloud for its file management section and especially version management. Our business uses tools like Creative Cloud a lot, and I'm encountering a problem. in fact, the indesign suite does not modify the files but replaces the files each time they save. As it is a new file, there is no history. How to get around this problem? Thanks for your help

### Steps to reproduce

1. open file in indesign
2. save it
3. a new file replace the first one

### Expected behavior

no file versionning

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
This isn't a general support channel. Since this isn't a bug in Nextcloud Server, I suggest posting your query at the Nextcloud Help Forum - https://help.nextcloud.com or perhaps asking Adobe. Another option might be: https://nextcloud.com/enterprise/
