### ISSUE TITLE
Change label: "Allow Download"

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/server#46700]
This is only a small thing: When I share a folder there is the option to allow downloads. In German "Download erlauben".

I thought, this only applies for downloads from the browser. But it also disables half the sync function if you use the virtual file system. You can only see all folders and files, but you can't open them. The desktop client shows a complicated "Forbidden"-error message.

1. It would help if the label said "Allow Download/Sync" - "Download/Sync erlauben". 
2. It would be cool, if the error message in the desktop client was easier to understand: "Download/Sync disabled"

**Comment by Agnibaan** [comment]
should i work on this ? is it a necessary issue to fix?

**Comment by Agnibaan** [comment]
@joshtrichards   hello , can i get a confirmation for this?
