### ISSUE TITLE
[Bug]: File/Folder creation dialog's name is not selected by default in NC 28

### ISSUE THREAD

**Issue by kyteinsky** [nextcloud/server#46707]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The file/folder name is not selected in the "Create new folder" or "New text file" modal when the "New folder" or "New text file" button is clicked. See following pic.
It worked as expected in NC 27 and does work in NC 29. It is broken only in NC 28 and does not happen 100% of the time but reproducible.

![image](https://github.com/user-attachments/assets/a672d479-5818-4dbc-b496-1709e62a5490)

### Steps to reproduce

1. Go to the files app `https://example.nextcloud.tld/index.php/apps/files/files?dir=/`
2. Click on "New" button on the top
3. Click "New folder" button

### Expected behavior

The text should be pre-selected

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by SystemKeeper** [comment]
https://github.com/nextcloud/server/issues/45409

**Comment by kyteinsky** [comment]
thanks @SystemKeeper ! I somehow missed this with keyword search
