### ISSUE TITLE
Nextcloud Box not booting...

### ISSUE THREAD

**Issue by drabanus** [nextcloud/server#4671]
I received the Nextcloud Box yesterday, installed a RaspberryPi and inserted the micro SD card that came with the Nextcloud Box. After connecting according to the instructions, it does not boot up. When monitoring any output on the HDMI port, only a static rainbow-color square appears on the screen.

What could I have done wrong?

Regards and thanks in advance - David

**Comment by leopenausa** [comment]
Exactly the same issue here. Just got my box today, installed the RPi2 V1.2, followed the instructions and got a nice rainbow...nothing more.
Any help would be appreciated.

**Comment by rullzer** [comment]
@oparoz maybe you know?

**Comment by oparoz** [comment]
Please install the image for the Rasberry Pi3 on your SD card. P2 V1.2 uses the processor found in the Pi3.

Let me know how it goes.

**Comment by leopenausa** [comment]
Great thanks, the official link to that image?

**Comment by oparoz** [comment]
You can find images here:
https://download.nextcloud.com/server/images/

We have received a newer one, but it hasn't made it to our downloads servers yet.

**Comment by MariusBluem** [comment]
I think it is: https://download.nextcloud.com/server/images/

**Comment by leopenausa** [comment]
Flashing latest image renders same result. Rainbow screen.

**Comment by leopenausa** [comment]
I can confirm a Raspbian image file booted without problem in my RPi2.
Image from here>
https://ownyourbits.com/2017/02/13/nextcloud-ready-raspberry-pi-image/

There is something really wrong with the image on the Nextcloud server that
doesn't work with the RPi2 V1.2

**Comment by MorrisJobke** [comment]
This is the bug tracker and not the forum. Please continue the discussion in the forums: http://help.nextcloud.com
