### ISSUE TITLE
Dropdown in personal settings broken.

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#4672]
see:

![dropdown](https://cloud.githubusercontent.com/assets/1589737/25659237/1c4f4cd2-3007-11e7-8dd2-996ce8704f57.png)

tried with latest master.

cc @nextcloud/designers @nextcloud/javascript

**Comment by Dennis1993** [comment]
What? There is an Option to adjust the privacy? This function I have never noticed.

I have made a few ideas to show something better that you can adjust something. I hope that is okay for you. My ideas are to add a arrow to the settings menu and more all elements to the right position too. I have created a screenshot to show you what I mean. Whats you opinion? :)

Before:
![before](https://cloud.githubusercontent.com/assets/1473674/25668945/734f6ec4-3028-11e7-8226-358f0a42cfce.PNG)

After:
![after](https://cloud.githubusercontent.com/assets/1473674/25668944/734aa1a0-3028-11e7-9d72-8676df33e03e.jpg)

**Comment by raimund-schluessler** [comment]
I like the proposed improvements. Before I also didn't realize that there is something to adjust. With the changes it is clear that this is a dropdown.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by MorrisJobke** [comment]
But we maybe should separate the enhancement from the bug.

**Comment by schiessle** [comment]
@Dennis1993 I like your idea a lot! But priority number one should be to fix the bug for Nextcloud 12.

**Comment by Dennis1993** [comment]
@schiessle Yes, of course. I split this idea in a seperate ticket. 👍

**Comment by MorrisJobke** [comment]
Was broken by 637c75bca176d3ef7a06e8b4fa2d60fece1c89a7

**Comment by MorrisJobke** [comment]
#1234

**Comment by MorrisJobke** [comment]
Let me fix this.

**Comment by MorrisJobke** [comment]
Fix is in #4752
