### ISSUE TITLE
Redesign broken on mobile

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#46771]
Just tested on daily.ltd2.nextcloud.com:

![Screenshot_20240726_101124_Brave](https://github.com/user-attachments/assets/376b9267-7c3a-4aa3-a0a5-d1fde310dc07)
![Screenshot_20240726_101143_Brave](https://github.com/user-attachments/assets/7af9730e-c6ed-415a-9d9b-2d012d5dacc5)

FYI @nextcloud/designers

**Comment by szaimen** [comment]
Another thing: this files filter input box is not easy to discover on mobile as you have to open the sidebar first. (So basically you need to know that it is there):
![Screenshot_20240726_101458_Brave](https://github.com/user-attachments/assets/83e6e9b7-b971-492b-b077-3713350bd9fb)

**Comment by susnux** [comment]
> Another thing: this files filter input box is not easy to discover on mobile as you have to open the sidebar first. (So basically you need to know that it is there):

Was discussed during the development but decided that this is the best location.

> First screen shot

The border radius of the widgets?

> Second screenshot

The copped filter? Known, already fixed but needs a release of nextcloud-vue

**Comment by susnux** [comment]
> icons in the header are crowded with scrollbar

Nothing new, I am pretty sure I saw a bug report for this before.
But hard to find on GitHub :sweat_smile:

**Comment by marcoambrosini** [comment]
> Or we move it to the main content, next to the filter actions

I think we should do this. This is not a good look @jancborchardt

**Comment by jancborchardt** [comment]
@marcoambrosini @szaimen we discussed the location of the search field at length. The result was that the placement on top of the left navigation is a good standard – I communicated as much with you @marcoambrosini. On mobile we expect people to use our mobile apps if it comes to anything except the basics.

**Comment by jancborchardt** [comment]
@szaimen could you either open separate issues for the separate things, or make a list of what you identify? As @susnux already noted, it’s not easy to guess with just the screenshots.

**Comment by szaimen** [comment]
The points:
1. icons in the header are too crowded and a scollbar is shown
2. the border-radius is set to 0 for widgets on the dashboard
3. the Filter filenames input box is not easy to discover on mobile

**Comment by susnux** [comment]
Splitted the issue as this are 3 independent issues that will need to be tracked independent.

**Comment by szaimen** [comment]
Thanks ferdinand! Sorry will do so myself next time :)
