### ISSUE TITLE
Issues after update to 12.0

### ISSUE THREAD

**Issue by emillod** [nextcloud/server#4679]
### Steps to reproduce
1. Update to the newest version(12.0)

### Actual behaviour
After update i have notifications about errors with integrity checks:

> Technical information
> =====================
> The following list covers which files have failed the integrity check. Please read
> the previous linked documentation to learn more about the errors and how to fix
> them.
> 
> Results
> =======
> - direct_menu
> 	- EXCEPTION
> 		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
> 		- Certificate is not valid.
> 
> Raw output
> ==========
> Array
> (
>     [direct_menu] => Array
>         (
>             [EXCEPTION] => Array
>                 (
>                     [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
>                     [message] => Certificate is not valid.
>                 )
> 
>         )
> 
> )

### Server configuration
**Operating system**: Linux V43 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64

**Web server:** Apache/2.4.6 (CentOS) PHP/5.6.30 (apache2handler)

**Database:** mysql 5.5.52

**PHP version:** 5.6.30
Modules loaded: Core, date, ereg, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, exif, mcrypt, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlwriter, xsl, zip, mysql, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, json, mhash

**Nextcloud version:** 12.0 beta 1 - 12.0.0.16

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** 

**Signing status:**
<details>
	<summary>Signing status</summary>

```
{
    "direct_menu": {
        "EXCEPTION": {
            "class": "OC\\IntegrityCheck\\Exceptions\\InvalidSignatureException",
            "message": "Certificate is not valid."
        }
    }
}
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.5.1
 - admin_audit: 1.2.0
 - comments: 1.2.0
 - dav: 1.3.0
 - encryption: 1.6.0
 - external: 1
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_external: 1.3.0
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.0
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0

Disabled:
 - apporder
 - audioplayer
 - calendar
 - contacts
 - direct_menu
 - files_downloadactivity
 - files_reader
 - keeweb
 - mail
 - notes
 - ocsms
 - ojsxc
 - rainloop
 - richdocuments
 - twofactor_totp
 - user_external
 - user_ldap
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "192.168.0.43",
        "cloud"
    ],
    "datadirectory": "\/var\/www\/html\/data",
    "overwrite.cli.url": "http:\/\/192.168.0.43",
    "dbtype": "mysql",
    "version": "12.0.0.16",
    "dbname": "cloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "instanceid": "ocx61f2p80ze",
    "htaccess.RewriteBase": "\/",
    "auth.bruteforce.protection.enabled": false,
    "mail_smtpmode": "smtp",
    "updater.release.channel": "beta",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OCA\Files_External\Lib\Storage\FTP
    [2] => \OC\Files\Storage\DAV
    [3] => \OCA\Files_External\Lib\Storage\OwnCloud
    [4] => \OCA\Files_External\Lib\Storage\SFTP
    [5] => \OCA\Files_External\Lib\Storage\AmazonS3
    [6] => \OCA\Files_External\Lib\Storage\Dropbox
    [7] => \OCA\Files_External\Lib\Storage\Google
    [8] => \OCA\Files_External\Lib\Storage\Swift
    [9] => \OCA\Files_External\Lib\Storage\SFTP
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36

**Operating system:**

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	Insert your webserver log here
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
	Insert your Nextcloud log here
	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
	Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
	```
</details>

**Comment by MorrisJobke** [comment]
The direct menu doesn't make any sense anymore, because we integrated something very similar to the server.

Feel free to remove it and it should be fine then.

cc @juliushaertl correct me if I'm wrong.

**Comment by juliushaertl** [comment]
@MorrisJobke @emillod Right, direct_menu shouldn't be compatible with 12 anyway.

**Comment by tflidd** [comment]
I had the same error. Isn't there a better way to handle the error that the user directly knows what to do?

Why is it enabled when it isn't compatible? If it isn't enabled, why is there a code integrity error (for me it's more of an urgent problem that currently used code isn't correct), if it's not enabled a notice on the apps page is enough?

`direct_menu` is a popular app so many users will see this error.

@juliushaertl @MorrisJobke 

Besides of that, I upgraded with updater app from command line and it looks really good.

**Comment by juliushaertl** [comment]
I think I found why this is breaking. My build script is still using an old key to add a signature.json. I'll release a new version without this, then we should be safe for Nextcloud 12.

**Comment by MorrisJobke** [comment]
Thanks

**Comment by juliushaertl** [comment]
New version is pushed to the app store. I'll test as well when I upgrade some instances to the new beta.
