### ISSUE TITLE
[Bug]: Custom favicon is not used if user is not logged in

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#46832]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Custom favicon is not used if user is not logged in

### Steps to reproduce

1. User not logged in : `<link rel="icon" href="/core/img/favicon.ico">`
2. User logged-in : `<link rel="icon" href="/apps/theming/favicon/files?v=0c27b597">`

### Expected behavior

Custom favicon, if set, should always be used

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
I'm having a hard time reproducing this. :thinking: 

I'm seeing this on public pages:

```
<link rel="icon" href="/apps/theming/favicon?v=a8d7d7cc">
```

**Comment by solracsf** [comment]
I can't reproduce anymore either, assuming its fixed. 🏋️
