### ISSUE TITLE
[Bug]: File filter input has no visible label once it's filled

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#46854]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![image](https://github.com/user-attachments/assets/255253ca-8d4a-4291-b5f1-47ddcf726fda)

### Steps to reproduce

1. Open /apps/files
2. Enter text at the top left search input

### Expected behavior

Input label moves up (lie NcInputField)

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by susnux** [comment]
This is a library component (NcAppNavigationSearch), so moved here: https://github.com/nextcloud-libraries/nextcloud-vue/issues/5885
