### ISSUE TITLE
[Bug]: List/grid toggle jumps while loading

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#46856]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Default
![Bildschirmfoto vom 2024-07-29 16-55-30](https://github.com/user-attachments/assets/c15f6cd2-5fb4-4035-a2b8-baeb8a8812f9)
Loading
![Bildschirmfoto vom 2024-07-29 16-55-28](https://github.com/user-attachments/assets/f7ad3c1a-1447-4e55-b667-647f7bc4f0cb)
Loaded
![image](https://github.com/user-attachments/assets/0629ee8c-f138-4c9f-8e9f-f358884c4321)

### Steps to reproduce

1. Open Files
2. Click the toggle at the top right

### Expected behavior

Smooth transition

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by susnux** [comment]
Thank you, I was also about to create a report for this :sweat_smile: 

I think we should switch positions of the loading indicator and the toggle, because UI elements should never jump like this (e.g. you want to click and suddenly you clicked an element you did not expect).

**Comment by shinyb** [comment]
fix 46856
