### ISSUE TITLE
Unspecified share exception while disabling "can edit"

### ISSUE THREAD

**Issue by cebolina** [nextcloud/server#4686]
![sharingviamail](https://cloud.githubusercontent.com/assets/24696818/25692636/7ad21a58-30a4-11e7-875c-3ee962173fe9.jpg)
 
Unspecified share exception while disabling "can edit"

### Steps to reproduce
1. Sharing a Folder via E-Mail
2. Disabling Option "can edit"
3. Unspecified share exception (see screenshot)

### Expected behaviour
External User can only see and download files in the Folder

### Actual behaviour
External User can delete Files in the Folder and upload files to the Folder

**Nextcloud version:** (see Nextcloud admin page)
Nexcloud Version 11.0.3 (stable)
Hosted at all-inkl.com
konfig.php:
...
'datadirectory' => '/www/htdocs/w1234567/cloud/clouddata/data',
'tempdirectory' => '/www/htdocs/w1234567/cloud/cloud/tmp/',
'dbtype' => 'mysql',
'version' => '11.0.3.2',
...

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update from V 11.0.2

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:**
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by Taste-IT** [comment]
I can confirm that with same configuration on other hoster.

**Comment by victorbw** [comment]
i can confirm this also, having this system:
- root ubuntu 16.04.2 LTS, 
- php 7.0
- mysql 5.6
- apache2

**Comment by tsueri** [comment]
Same on Freebsd Jail with nextcloud 11.0.3

- 10.3-RELEASE
- php 5.6.30
- mariadb101-server-10.1.22_1
- apache24-2.4.25_1

encryption: No
external storage: yes (local)
external userbackend: no

**Comment by BurtGummer** [comment]
Same on Debian stable (Jessie).

**Comment by derWeihnachtsmann** [comment]
Same on Ubuntu 16.04 with nextcloud 11.0.3.2

PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )
mysql  Ver 14.14 Distrib 5.7.18, for Linux (x86_64)
Server version: Apache/2.4.18 (Ubuntu)
encryption: No
external storage: yes (local)
external userbackend: no

I am using an AD.

**Comment by soeffi** [comment]
+1. Same here with same configuration as described by OP.

**Comment by Taste-IT** [comment]
Hi,
i upgraded to Version 12 and this error seems to be solved.

**Comment by chrone81** [comment]
I got this error again on Nextcloud 12.0.4.

**Comment by skjnldsv** [comment]
Fixed since.
