### ISSUE TITLE
[future request] Treat skeleton files as themes files

### ISSUE THREAD

**Issue by KB7777** [nextcloud/server#4687]
Hello.

After upgrade to 11.0.3 skeleton files are overwritten to default ones. Is it intented or I miss something?
I know there is 'skeletondirectory' => '/path/to/nextcloud/core/skeleton' option for config.php, but it may be very surprised for admins, because there is no info about it during upgrade (or I miss some?).

Is it possible to treat skeleton files the same way as theme files?

Regards :)

**Comment by MorrisJobke** [comment]
> After upgrade to 11.0.3 skeleton files are overwritten to default ones. Is it intented or I miss something?

This is how our update works. If you want separate skeleton files use the config.php setting. Overwriting the folder `skeleton` has the same implications as overwriting any other file in Nextcloud - it needs to be cleared to be overwritten by the new code. 

I would vote against yet another way to do it. We have a way in place and that should be used.
