### ISSUE TITLE
Enhance the visibility of privacy settings menu

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/server#4688]
In #4672 the menu for the privacy settings is broken. I never realized that I can adjust these. One idea is to improve the icons. Please see the following post for more details:

https://github.com/nextcloud/server/issues/4672#issuecomment-298951861

My ideas to improve that:

Before:
![before](https://cloud.githubusercontent.com/assets/1473674/25668945/734f6ec4-3028-11e7-8226-358f0a42cfce.PNG)

After:
![after](https://cloud.githubusercontent.com/assets/1473674/25668944/734aa1a0-3028-11e7-9d72-8676df33e03e.jpg)

**Comment by MariusBluem** [comment]
Do you already have a working branch? If yes - mind open a PR 😍💪

**Comment by Dennis1993** [comment]
No, that's a photomontage :(

**Comment by eppfel** [comment]
Really like it. You need any help opening a PR @Dennis1993 ?

**Comment by Dennis1993** [comment]
@eppfel I can't program that in NextCloud :(
Maybe someone can make something out of my ideas.

**Comment by jancborchardt** [comment]
Awesome suggestion @Dennis1993! :) Maybe it’s time to learn HTML & CSS? It’s not that difficult, for example check https://www.codecademy.com/learn/web :)

**Comment by MorrisJobke** [comment]
Fixed with #5550
