### ISSUE TITLE
[Bug]: Missing Translation

### ISSUE THREAD

**Issue by TUCAOEVER** [nextcloud/server#46902]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![QQ_1722404092331](https://github.com/user-attachments/assets/d827be6c-b54c-412b-a229-05829b32cc5b)
If the edit time is "a few seconds ago" it will not be translated into users' language

### Steps to reproduce

1. Edit any file
2. Quit file editing
3. Check the row of "edit time"

### Expected behavior

It should be translable and in Chinese it should be "不久前"

### Installation method

Official All-in-One appliance

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "*.*.*.*",
            "cloud.promc.cn"
        ],
        "dbtype": "mysql",
        "version": "29.0.4.2",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/cloud.promc.cn",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "allow_local_remote_servers": true,
        "theme": "",
        "loglevel": 0,
        "memories.exiftool": "\/config\/www\/nextcloud\/apps\/memories\/bin-ext\/exiftool-amd64-musl",
        "memories.vod.path": "\/config\/www\/nextcloud\/apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "maintenance_window_start": 8,
        "upgrade.disable-web": false,
        "app_install_overwrite": [
            "memories",
            "richdocuments",
            "files_rightclick",
            "files_markdown"
        ],
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "timeout": 0,
            "dbindex": 0,
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "memories.db.triggers.fcu": true,
        "default_language": "zh_CN",
        "default_locale": "zh-cn",
        "default_phone_region": "CN"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - calendar: 4.7.7
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - cloud_py_api: 0.1.9
  - comments: 1.19.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - drawio: 3.0.2
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_markdown: 2.4.1
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - forms: 4.2.4
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - mediadc: 0.3.9
  - memories: 7.3.1
  - nextcloud_announcements: 1.18.0
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - photos: 2.5.0
  - previewgenerator: 5.6.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - richdocuments: 8.4.3
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - support: 1.12.0
  - survey_client: 1.17.0
  - systemtags: 1.19.0
  - text: 3.10.1
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - updatenotification: 1.19.1
  - user_status: 1.9.0
  - viewer: 2.3.0
  - workflowengine: 2.11.0
Disabled:
  - admin_audit: 1.19.0
  - bruteforcesettings: 2.9.0
  - encryption: 2.17.0
  - files_downloadlimit: 2.0.0 (installed 2.0.0)
  - files_external: 1.21.0
  - files_rightclick: 0.15.1 (installed 0.15.1)
  - notes: 4.10.1 (installed 4.10.1)
  - suspicious_login: 7.0.0
  - twofactor_totp: 11.0.0-dev
  - user_ldap: 1.20.0
  - weather_status: 1.9.0 (installed 1.8.0)
```

**Comment by susnux** [comment]
Translations are handled by the community on [Transifex](https://app.transifex.com/nextcloud/), this string is simply not yet translated.
Feel free to join on Transifex and provide the missing translations.

More information can also be found on our forum: https://help.nextcloud.com/c/translations/23

**Comment by TUCAOEVER** [comment]
> Translations are handled by the community on [Transifex](https://app.transifex.com/nextcloud/), this string is simply not yet translated. Feel free to join on Transifex and provide the missing translations.
> 
> More information can also be found on our forum: https://help.nextcloud.com/c/translations/23

Nope, i am currently the main reviewer and translater of Chinese localization work, and i have done serval checks. There is no phrase related to this

![QQ_1722820412867](https://github.com/user-attachments/assets/06984fbc-b562-47e3-9f14-462cefaa4db9)

**Comment by susnux** [comment]
> Nope, i am currently the main reviewer and translater of Chinese localization work, and i have done serval checks. There is no phrase related to this

That string comes from the `NcDatetime` component shared across server and apps in the vue library.
If I look for Chinese it is not translated currently:

https://app.transifex.com/nextcloud/nextcloud-vue/viewstrings/#zh_CN/94e9e2c9f998f38269769e8a40b18a59/472812780?q=text%3A'a+few+seconds'

**Comment by TUCAOEVER** [comment]
> > Nope, i am currently the main reviewer and translater of Chinese localization work, and i have done serval checks. There is no phrase related to this
> 
> That string comes from the `NcDatetime` component shared across server and apps in the vue library. If I look for Chinese it is not translated currently:
> 
> https://app.transifex.com/nextcloud/nextcloud-vue/viewstrings/#zh_CN/94e9e2c9f998f38269769e8a40b18a59/472812780?q=text%3A'a+few+seconds'

Oh, i missed that... Thx for answering!
