### ISSUE TITLE
Reload browser in sub folder moves you back to the root

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#4691]
Steps to reproduce:

1. Navigate to a sub-folder
2. reload the browser

Expected result:

You stay in the same folder

Actual result:

Root folder is shown but breadcrumbs still show the sub folder

**Comment by rullzer** [comment]
I think this is also solved by https://github.com/nextcloud/server/pull/4693

**Comment by rullzer** [comment]
#4693 is in
