### ISSUE TITLE
[Bug]: sharing with team does not respect "no download" setting

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/server#46920]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If you **share a folder/file with a team (formerly circles) and disallow download**, all files are just displayed, and download buttons are visible for images and for office documents. Only pdfviewer seems to respect the "no download" setting and disables the save button. The print button is still there, which does not make sense IMO.

### Context
If you share a folder/file via **link** (public share) and disallow download, everything works as expected: office files, pdfs, images will be displayed, but there is not download button anywhere. (yes I am aware that screenshots are still possible)

If you **share a folder/file with a group and disallow download**, office files can be viewed with collabora, but any other filetype cannot be displayed. You can disable files_pdfviewer, then collabora will open pdf files without download button. (IMO this doesn't make sense, users want to hide download buttons for the receiver, but still allow the receiver to view the file, otherwise it wouldn't make sense to share at all - but this should be discussed in the following issue links). Related: https://github.com/nextcloud-gmbh/customer-feature-requests/issues/658 and https://github.com/nextcloud/server/issues/41686

### Steps to reproduce

1. create team "Testteam" (formerly circles) with user A and user B
2. user A shares folder (containing .odt .md .jpg .pdf) with Testteam, removing the checkmark for the "allow download" setting
3. user B goes to shared folder
4. user B can open images, in top right ... menu there is a download button
5. user B can open office files, in File there is a download button
6. user B can open .md files,  in top right ... menu there is a download button
7. user B can open .pdf files, download button is disabled, but printing still possible

### Expected behavior

content is shown but download (and print) buttons are removed

### Installation method

None

### Nextcloud Server version

29.0.3

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

This was tested on ltd3.nextcloud.com today.

**Comment by juliushaertl** [comment]
I've been checking this on the richdocuments side but noticed a couple of odd things that point to server/files/circles related issues:

- The share attributes are not stored in the database for circle shares
  - I have no clue if that was by design when the disable download feature was added but it seems a bit like every share provider will need special handling, the same issue exists for talk
    - Might be an oversight by the sharing UI rewrite that the disable download option is now possible for all share types instead of just the ones form the default share provider
- Frontend: It is only possible to toggle the checkbox when creating a new share to a circle, but not when editing a share

Maybe @ArtificialOwl and @Fenn-CS have more insights there? 

cc @sorbaugh

**Comment by alexanderdd** [comment]
@Fenn-CS I am happy that you assigned yourself to this. To me this sounds like it should get high priority because of security, what do you think? Maybe we should add the security label?
