### ISSUE TITLE
Edit locally on public shares look broken

### ISSUE THREAD

**Issue by susnux** [nextcloud/server#46935]
### Bug description

* Left over from https://github.com/nextcloud/server/issues/43555 by @ChristophWurst 

![Bildschirmfoto vom 2024-02-13 17-50-23](https://github.com/nextcloud/server/assets/1374172/2882bf2e-5bcb-4d39-beb4-aced1eeb6797)

^ it shows and has a broken icon.

### Steps to reproduce

1. Share a folder by link and give write permission
2. Open the link
3. Open the actions menu of a file

### Expected behavior

No missing icon

**Comment by skjnldsv** [comment]
> * Left over from [[Bug]: "Edit locally" shown on public share with write permission #43555]

What is left over from it?
It's fixed :thinking:

**Comment by susnux** [comment]
> What is left over from it?

The broken icon was part of the issue and still broken.

**Comment by skjnldsv** [comment]
But we don't use url-icons anymore on the new Files app? :thinking: 
ALso the broken icon is because `OC.imagePath('files', 'computer.svg')` doesn't exist anymore :shrug:
