### ISSUE TITLE
[Bug]: icons in the header are too crowded and a scollbar is shown

### ISSUE THREAD

**Issue by susnux** [nextcloud/server#46997]
* Original report: https://github.com/nextcloud/server/issues/46771 by @szaimen 

The right header menu has a scrollbar on small mobile, this should instead go into an overflow menu.

![image](https://github.com/user-attachments/assets/f9c9acad-db56-4b09-879a-97ebfbe51c64)

**Comment by jancborchardt** [comment]
@susnux yeah, your idea of overflowing it into the account menu is nice. Another option, a more low-hanging fix, could be to reduce the horizontal spacing between the icons on mobile.

E.g. the notifications, contacts and account menu already seem to be "compressed", while only Assistant and search take up a lot of width. This could be compressed on mobile? (It is similar to how iOS does it with app titles on the home screen, where the font tracking is reduced first before ellipsis.)

**Comment by szaimen** [comment]
This seems to be fixed in master now :)
