### ISSUE TITLE
[Bug]: OCA\Intros\Listener\BeforeTemplateRenderedListener $argument 1 has to be string null given

### ISSUE THREAD

**Issue by wehowski** [nextcloud/server#47020]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

- E.g. the forms app forms throw error if guest visitor
- Log says: OCA\Intros\Listener\BeforeTemplateRenderedListener $argument 1 has to be string null given

As dirty patch solution I made the parameter nullable: 
````PHP
namespace OCA\Intros\Listener;

use OCA\Intros\AppInfo\Application;
use OCP\AppFramework\Http\Events\BeforeTemplateRenderedEvent;
use OCP\AppFramework\Services\IInitialState;
use OCP\EventDispatcher\Event;
use OCP\EventDispatcher\IEventListener;
use OCP\IConfig;
use OCP\IRequest;
use OCP\Util;

/**
 * @template-implements IEventListener<Event|BeforeTemplateRenderedEvent>
 */
class BeforeTemplateRenderedListener implements IEventListener {
	public function __construct(
		private ?string $userId,
		private IRequest $request,
		private IInitialState $initialState,
		private IConfig $config,
	) {
	}
````

Maybe team members can take a  look and/or provide a more correct fix?

### Steps to reproduce

1. Updated to last version (29.0.4)
2. Updated all apps
3. visiting a forms app form link as guest visitor (it may fail for other apps too?!)

### Expected behavior

Showing the forms to guests, not throwing the fatal error

### Installation method

None

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
What is the full stack RAW log ?

**Comment by wehowski** [comment]
[nextcloud.log](https://github.com/user-attachments/files/16487181/nextcloud.log)

**Comment by solracsf** [comment]
You should report this to https://framagit.org/framasoft/framaspace/custom-apps/intros

**Comment by wehowski** [comment]
Ok, sorry! Thank you, I removed tha app.
