### ISSUE TITLE
Improve templates management

### ISSUE THREAD

**Issue by Jerome-Herbinet** [nextcloud/server#47039]
Today (and for quite a long time), when I think that template management creates misunderstandings.

- As a user, as long as we have not specified a template folder, we are entitled to wonder if we have the right and the possibility to create a single template folder or to accumulate several because we have "create new templates folder" accessible via [+ New] at all levels of the tree.

- It is disturbing that the "create new templates folder" option disappears after specifying the template, because, what to do next? I think that we do not create a template folder every day and that since the system allows it to be created elsewhere than at the root (unless it is a bug and the specification can only be done at the root) and with a freely chosen name, we can forget where we created the folder (and what name it had) a few months or years ago (knowing that we rarely go back to manage the templates afterwards).

I propose the following new ergonomics:

- Left side panel: Addition of a "Templates" section that contains the templates, if the folder has been specified. If the folder has not been specified, a message must be displayed: "No template folder has been specified", then once done, "Your templates will be displayed here" as long as no template file has been deposited in the folder. Knowing that the folder may not be at the root and may have any name, the breadcrumbs must be displayed (to know what it is called and where it is)
![2024-08-05_14-58](https://github.com/user-attachments/assets/d14b9842-c74e-4173-b684-8c35f1d30276)

- In the folder navigation (main panel), no longer put "create new templates folder" in [+ New] but add an option to the context menu of the folders that would be called "Define as template folder". This option would never disappear and would allow you to change the template folder in 2 clicks, knowing that only one template folder can exist.
![2024-08-05_15-02](https://github.com/user-attachments/assets/bf99bf8a-5da5-49f0-a918-bb43697aaa07)

- If the active template folder is renamed or moved, it must continue to live and be accessible via the left side panel (currently, at the slightest renaming or moving of the folder, it loses its special status). If the folder is deleted, the templates are no longer accessible from the left side panel.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Jerome-Herbinet** [comment]
@nextcloud/designers

**Comment by nimishavijay** [comment]
Also see https://github.com/nextcloud/server/issues/46455

**Comment by lmarvaud** [comment]
Isn't it similar to : #33196 ?

**Comment by jancborchardt** [comment]
@Jerome-Herbinet is it fine if we close this in favor of https://github.com/nextcloud/server/issues/46455 since that is already planned out by @juliushaertl? Feel free to add a comment with anything that is missing there. :)

**Comment by Jerome-Herbinet** [comment]
> @Jerome-Herbinet is it fine if we close this in favor of #46455 since that is already planned out by @juliushaertl? Feel free to add a comment with anything that is missing there. :)

OK for me @jancborchardt :-)
