### ISSUE TITLE
[Bug]: FolderTree - if node has the same name, multiple are highlighted

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/server#47050]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When folders have the same name, it is possible to select multiple of them:

<img width="292" alt="image" src="https://github.com/user-attachments/assets/a7db0e63-08aa-4239-b69b-647ed200ffdd">

### Steps to reproduce

1. Have a folder "Info" inside a folder "Info"
2. Select the first folder "Info", then the second one

### Expected behavior

Only the last one should be selected

@Pytal 

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by Pytal** [comment]
Saw this before but since I adjusted the logic it does not reproduce, does this still occur for you @SystemKeeper?

**Comment by SystemKeeper** [comment]
No, seems to work fine now 👍
