### ISSUE TITLE
[Bug]: Advanced search does not focus input when opened

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#47056]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When opening the advanced search modal there is no focus on the search input. It makes searching very tedious.

### Steps to reproduce

1. Press *Ctrl+f* **OR** click on the magnifier icon at the top right

### Expected behavior

Adanced search opens, input field is focused

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

cc @Fenn-CS

**Comment by ChristophWurst** [comment]
@Fenn-CS are you able to reproduce this?

**Comment by Fenn-CS** [comment]
> @Fenn-CS are you able to reproduce this?

@ChristophWurst Just did.
