### ISSUE TITLE
[Bug]: Sharing icon missing from files after upgrade

### ISSUE THREAD

**Issue by nerrehmit** [nextcloud/server#47051]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

We noticed that the share icon is not present any more in the file overview some time after the upgrade to Nextcloud 29.

I found the same issue on the Community Forum where another user confirmed it but it did not gain traction and I did not manage to find a bug report about this.
Here is the issue in the Community Forum: https://help.nextcloud.com/t/share-icon-missing-after-upgrade/186086

It is still possible to share the files via the "3 dot menu" > "open details" > "sharing" tab but the old way with the sharing symbol being directly accessible was a lot quicker and more intuitive for the many users of our nextcloud instance.

### Steps to reproduce

1. Probably just have the newest Version V29 installed. Not sure about V28, but I'm fairly sure the old way was still available in V27

### Expected behavior

The share symbol is still directly visible on each file listing in the file browser and not hidden 3 clicks away.

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

29

### Operating system

RHEL/CentOS

### PHP engine version

None

### Web server

Nginx

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.4.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "nc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "appstoreenabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "skeletondirectory": "",
        "trashbin_retention_obligation": "30, 30",
        "loglevel": 1,
        "updater.release.channel": "stable",
        "theme": "",
        "allow_user_to_change_display_name": false,
        "lost_password_link": "disabled",
        "overwriteprotocol": "https",
        "oidc_login_client_id": "nextcloud",
        "oidc_login_client_secret": "764aeef3-67a3-48a1-b6c9-736300518d97",
        "oidc_login_provider_url": "***REMOVED SENSITIVE VALUE***",
        "oidc_login_button_text": "***REMOVED SENSITIVE VALUE***",
        "oidc_login_auto_redirect": "True",
        "oidc_login_redir_fallback": true,
        "oidc_login_disable_registration": false,
        "oidc_login_attributes": {
            "ldap_uid": "***REMOVED SENSITIVE VALUE***",
            "id": "***REMOVED SENSITIVE VALUE***",
            "mail": "email"
        },
        "maintenance": false,
        "versions_retention_obligation": "auto, 30",
        "defaultapp": "files,dashboard",
        "default_phone_region": "CH",
        "check_data_directory_permissions": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": "true",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "activity_expire_days": "90",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "twofactor_enforced": "true",
        "oidc_login_proxy_ldap": true,
        "oidc_login_use_id_token": true,
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "log_type_audit": "file",
        "logfile_audit": "\/var\/log\/nextcloud\/audit.log",
        "logfilemode": 416,
        "logtimezone": "Europe\/Zurich",
        "log_rotate_size": 104857600,
        "maintenance_window_start": 1
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - admin_audit: 1.19.0
  - bruteforcesettings: 2.9.0
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - collectives: 2.12.0
  - comments: 1.19.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - drawio: 3.0.2
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.0
  - files_downloadlimit: 2.0.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - forms: 4.2.4
  - impersonate: 1.16.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - nextcloud_announcements: 1.18.0
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - oidc_login: 3.1.1
  - password_policy: 1.19.0
  - photos: 2.5.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - richdocuments: 8.4.3
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - support: 1.12.0
  - survey_client: 1.17.0
  - systemtags: 1.19.0
  - text: 3.10.1
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - twofactor_totp: 11.0.0-dev
  - updatenotification: 1.19.1
  - user_ldap: 1.20.0
  - viewer: 2.3.0
  - workflowengine: 2.11.0
Disabled:
  - encryption: 2.17.0
  - files_external: 1.21.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - suspicious_login: 7.0.0
  - user_saml: 5.1.2 (installed 5.1.2)
  - user_status: 1.9.0 (installed 1.0.1)
  - weather_status: 1.9.0 (installed 1.0.0)
```

**Comment by joshtrichards** [comment]
> It is still possible to share the files via the "3 dot menu" > "open details" > "sharing" tab but the old way with the sharing symbol being directly accessible was a lot quicker and more intuitive for the many users of our nextcloud instance.

The person icon (with the `+` sign) immediately to the right of the circle in your linked forum post *is* the sharing icon. Or am I misunderstanding your report?

**Comment by nerrehmit** [comment]
Thanks for getting back so quickly. 
I should have been more precise sorry. 
The symbol (old or changed) is no longer present on a folder or a file that has been shared with you.

As you can see from my picture those folders and files were shared with me by an organizational user (data owner) called OA:

![grafik](https://github.com/user-attachments/assets/c8425d68-17f8-42cd-9c99-ff3fd0e8a4f9)

There I'm unable to quickly reshare those files via link. Resharing is allowed by OA for those folders.

The usecase we have internally is that most folders with company data are owned and shared by OA to all my users and then individual users create share links for certain files, videos etc. to reference them in other media/ chats/ wiki's

Previously there was the share icon present even if that file or folder was shared with you. Unfortunately I don't have a screenshot of how it looked before.

**Comment by solracsf** [comment]
The UI is the same on v28 on folders share with me.

![image](https://github.com/user-attachments/assets/d9a12dfc-50e7-482a-9e5a-3ee9deff14ae)

**Comment by q-wertz** [comment]
Maybe I misunderstand the problem, but when I click on the user symbol I directly get to the share sidebar.
In your case @nerrehmit this should be the encircled "OA"...

As you wrote your use case: Looks like a good use case for the [groupfolders app](https://github.com/nextcloud/groupfolders).

**Comment by skjnldsv** [comment]
> Maybe you mean those symbols? They are simply replaced by the user icon who shared the folder with you, but the functionality stays the same.

Yep, we had a slight moment where we showed both, but it was too crowded. We rolled back to showing the owner of the file instead of the sharing icon on specific cases.
Otherwise you can see it like the screenshot @q-wertz posted above 👍
