### ISSUE TITLE
rewrite of pretty urls doesn't work with php-fpm

### ISSUE THREAD

**Issue by simonbuehler** [nextcloud/server#4708]
### Steps to reproduce
1. use php-fpm, configure .htaccess , make it writable for nc user
2. browser webinterface
3.

### Expected behaviour
the "index,php" part should be rewitten

### Actual behaviour
pretty url doesn't work

### Server configuration

**Operating system**:
gentoo
**Web server:**
apache 2.4
**Database:**
mysql
**PHP version:**
php-fpm 5.6
**Nextcloud version:** (see Nextcloud admin page)
11
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated
**Where did you install Nextcloud from:**
updater
**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - audioplayer: 1.5.1
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - direct_menu: 0.10.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_downloadactivity: 1.0.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.4
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - ojsxc: 3.1.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - workflowengine: 1.1.1
Disabled:
  - documents
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - ownnote
  - shorten
  - user_ldap
  - user_saml

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "occ7545378ad",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.xxx.de"
        ],
        "datadirectory": "\/var\/www\/localhost\/htdocs\/nextcloud\/data",
        "dbtype": "mysql",
        "version": "11.0.3.2",
        "installed": true,
        "forcessl": false,
        "mail_domain": "xxx.de",
        "mail_from_address": "apache",
        "mail_smtpmode": "php",
        "preview_libreoffice_path": "\/usr\/bin\/loffice",
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_max_scale_factor": 10,
        "preview_max_filesize_image": 50,
        "loglevel": "3",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "{xxx.de:993\/imap\/ssl}"
                ]
            }
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.release.channel": "stable",
        "overwrite.cli.url": "https:\/\/www.xxx.de\/nextcloud",
        "htaccess.RewriteBase": "\/nextcloud"
    }
}

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** imap

### Logs
nothing logged

**Comment by MorrisJobke** [comment]
See documentation about `htaccess.RewriteBase` in https://docs.nextcloud.com/server/12/admin_manual/configuration_server/config_sample_php_parameters.html

After changing this value (as it looks in your config report) you need to run `occ maintenance:update:htaccess` to apply the new code to htaccess.

**Comment by simonbuehler** [comment]
sorry my bad,  but it doesn't work with the correct `htaccess.RewriteBase` either, please reopen

**Comment by simonbuehler** [comment]
@koehn how exactly did you solve this [there](https://help.nextcloud.com/t/apache-rewrite-to-remove-index-php/658/31) ?

**Comment by MorrisJobke** [comment]
> @koehn how exactly did you solve this there ?

Have you run `sudo -u www-data php occ maintenance:update:htaccess` because this works in many environments that we and other people have in use? Have you also set the `AllowOverwrite` in the apache config?

**Comment by simonbuehler** [comment]
its all set, i think its a issue under php-fpm

**Comment by MorrisJobke** [comment]
I also have php-fpm in use and it works here :/ also other users in the forums use this kind of setup.

Could I ask you to open a discussion about this in the forums? That's the better place to get help on setup issues, because from the implementation side it looks okay

**Comment by simonbuehler** [comment]
ok will try my luck there

**Comment by simonbuehler** [comment]
found a solution to the issue
[here](https://help.nextcloud.com/t/stop-inserting-index-php-with-apache-fastcgi/9543/12) maybe this should be added in the docs
