### ISSUE TITLE
Connection to server lost on certain filenames in Firefox

### ISSUE THREAD

**Issue by KreativeKrise** [nextcloud/server#4709]
### Steps to reproduce
1. Create a file with "*728x90.ext" or "*160x600.ext" (e.g. "lala_728x90.txt" or "160x600.jpg") as name. The format or extension of the file doesn't matter.
2. Upload the file using Firefox

### Expected behaviour
The file should be stored on the server.

### Actual behaviour
The message "Connection to server lost" appears and file was not stored on the server.

### Server configuration
**Operating system**:
Linux 4.9.12-gs #2 SMP Sat Feb 25 21:06:56 CET 2017 x86_64

**Web server:**
Apache (fpm-fcgi)

**Database:**
mysql 10.0.30

**PHP version:**
7.0.18
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, Reflection, session, standard, SimpleXML, sockets, mbstring, tokenizer, xml, cgi-fcgi, mysqlnd, apcu, bcmath, curl, dba, dom, enchant, fileinfo, gd, imagick, imap, intl, json, ldap, exif, mcrypt, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, soap, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache

**Nextcloud version:**
11.0.3 (stable) - 11.0.3.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:** 
nextcloud.com

**List of activated apps:**
<details>
<summary>App list</summary>
```
- activity: 2.4.1
- comments: 1.1.0
- dav: 1.1.1
- federatedfilesharing: 1.1.1
- federation: 1.1.1
- files: 1.6.1
- files_pdfviewer: 1.0.1
- files_sharing: 1.1.1
- files_texteditor: 2.2
- files_trashbin: 1.1.0
- files_versions: 1.4.0
- files_videoplayer: 1.0.0
- firstrunwizard: 2.0
- gallery: 16.0.0
- issuetemplate: 0.2.1
- logreader: 2.0.0
- lookup_server_connector: 1.0.0
- nextcloud_announcements: 1.0
- notifications: 1.0.1
- password_policy: 1.1.0
- provisioning_api: 1.1.0
- serverinfo: 1.1.1
- sharebymail: 1.0.1
- survey_client: 0.1.5
- systemtags: 1.1.3
- theming: 1.1.1
- twofactor_backupcodes: 1.0.0
- updatenotification: 1.1.1
- workflowengine: 1.1.1
```
</details>

**List of deactivated apps:**
<details>
<summary>App list</summary>
```
- admin_audit
- encryption
- external
- files_accesscontrol
- files_automatedtagging
- files_external
- files_retention
- templateeditor
- user_external
- user_ldap
- user_saml
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>
```
{
    "instanceid": "ocm9cfsgobyy",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "share.handbuch-experten.de"
    ],
    "datadirectory": "\/var\/www\/vhosts\/handbuch-experten.de\/share.handbuch-experten.de\/data",
    "overwrite.cli.url": "https:\/\/share.handbuch-experten.de",
    "dbtype": "mysql",
    "version": "11.0.3.2",
    "dbname": "admin_handbuchexperten_nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "updater.secret": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "127.0.0.1",
        "port": 6379
    }
}
```
</details>

**Are you using external storage, if yes which one:**
files_external is disabled

**Are you using encryption:**
no

### Client configuration
**Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0

**Operating system:**
Microsoft Windows 10

#### Web server error log
nothing relevant

#### Nextcloud log (data/nextcloud.log)
nothing relevant

#### Browser log
nothing relevant

**Comment by Stibila** [comment]
I experience exactly same problem with NC 11 and php 7.1.4

I tried testing environment NC 12 beta with php 7.0.15 and php 5.6.3 with same result. I tried only filename _lala_728x90.txt_.

**Comment by hkahl** [comment]
I can confirm that with nextcloud 11.0.3 (stable)

* cannot upload 'lala_728x90.txt'

Tested creating directories:

* cannot create directory 'Advertising_P_PICTURES'
* cannot create directory 'Advertising_P'
* cannot create directory 'Advertising_X'
* cannot create directory 'Advertising_'

* successfully created directory 'Advertisin_P'
* successfully created directory 'Advertisinn_P'

There are a lot of directories on my server that I am not able to open anymore through nextcloud.
I always get the message "connection to server lost". I set the nextcloud log level to debug, but nothing appears in the logs.

**Comment by hkahl** [comment]
Adblock Plus seems to cause the issue. That's why creating a directory with 'Advertising' in the name was not possible. Strange that somthing like 'lala_728x90.txt' is blocked by ADP.

Anyway, disabling Adblock Plus or adding the nextcloud server to the whitelist resolved the issue.
