### ISSUE TITLE
[Bug]: App name does not show fully on hover/focus of specific app

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#47101]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Long app names are ellipsized when we could make space for the one that is hovered/focused:
![image](https://github.com/user-attachments/assets/90fae4ff-126d-4851-aa27-032aec5e1ec5)

### Steps to reproduce

1. Have an app with a comparably long app name installed, e.g. Dashboard (default app), Collectives or Announcements
2. Notice not the full app name is shown
3. It doesn’t change when hovering/focusing the app name

### Expected behavior

In a previous version, the name of the current app and of the hovered/focused app was expanded to be fully visible:
![image](https://github.com/user-attachments/assets/447a3ce5-54ad-454e-9c24-6cd5404a9775)

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by jancborchardt** [comment]
So @karlitschek also reported that even Contacts and Calendar are already ellipsized by default (macOS with Safari). Probably we should reduce the default tracking a little bit, or increase the whitespace between the apps a tiny bit?

@susnux @marcoambrosini what do you think?

**Comment by susnux** [comment]
For calendar we just need a tiny bit more space (the 4px margin removed are enough):
![image](https://github.com/user-attachments/assets/f8dc9480-567a-4c63-b106-ca510124f339)

But 50px width is not much for text

**Comment by susnux** [comment]
So yes maybe we should increase the width to 55px?

Or complex solution: Do not show the neighbor names but instead always show the full app name (so it can not overflow the neighbor)

**Comment by susnux** [comment]
@jancborchardt 

I played with option2 and 2x 6px (12px more space as this also fixes dashboard):

before | after
---|---
![Screenshot 2024-08-07 at 12-43-04 Dashboard - Nextcloud Daily](https://github.com/user-attachments/assets/9bec3f77-6a49-4680-884c-9316389fb189)|![Screenshot 2024-08-07 at 12-48-27 Dashboard - Nextcloud Daily](https://github.com/user-attachments/assets/8ff42b59-4625-479f-a694-a7218fac447d)

**Comment by jancborchardt** [comment]
@susnux awesome – yep that’s exactly what I meant, the 2 solutions together are very nice! Meaning removing some margin by default, and having the focused app expand width at the cost of its neighbors.

**Comment by karlitschek** [comment]
https://github.com/user-attachments/assets/919c74ba-96d9-4cf4-87f3-9394967353c6

Looks good in general. Unfortunately I see a weird wobbly effect on mouse over

**Comment by AndyScherzinger** [comment]
Now that you say it, I also see that wobbly effect. @sorbaugh can you please create a ticket and align with @susnux so it can get fixed for next week's build?

**Comment by sorbaugh** [comment]
Tracked here :) https://github.com/nextcloud/server/issues/47148
