### ISSUE TITLE
[Bug]: Settings navigation items and buttons not correctly rounded

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#47107]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The navigation of settings and a bunch of buttons there still have old or mixed styles. See here where the rounding of both is too much.
(Also, the icon color of the buttons does not match the text color.)
![image](https://github.com/user-attachments/assets/07a24625-55d7-4168-a389-72c75d2c5684)

### Steps to reproduce

1. Open settings, for example at "Mobile & desktop"

### Expected behavior

The new style is used.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by susnux** [comment]
Fixed

![image](https://github.com/user-attachments/assets/4d61164f-2b3d-4648-8856-1c1cc543e62e)
