### ISSUE TITLE
[Bug]: Cannot rename file/folder in group folder

### ISSUE THREAD

**Issue by luka-nextcloud** [nextcloud/server#47104]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Users cannot rename files if right of delete file is inhibited in advanced authorization.

### Steps to reproduce

1. Create a group folder "GroupFolder1"
2. Create a group "Group1"
3. Assign user "UserA" to group "Group1"
4. Assign group "Group1" to "GroupFolder1"
5. Enable "advanced permissions" for group folder "GroupFolder1" and select "Group1"
6. Login as "UserA"
7. Access files
8. Open sharing tab of folder "GroupFolder1"
9. Add advanced permission for group "Group1". Allow read, write, create, share. Deny delete
10. Access folder "GroupFolder1"
11. Create any file/folder
12. Rename created file/folder

### Expected behavior

File/Folder can be renamed without any error.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by SystemKeeper** [comment]
See also
* https://github.com/nextcloud/groupfolders/issues/1646
* https://github.com/nextcloud/groupfolders/issues/859

**Comment by susnux** [comment]
Background:
Moving is just a composite of `copy the file` and `remove the original`, so a composite of `create` and `delete`.
(some storages might have only one operation for this, but that is not guaranteed)

**Comment by susnux** [comment]
(which also makes sense, because if you deny "delete" a rename basically deletes that file as that file is no longer accessible on that name)

**Comment by luka-nextcloud** [comment]
@susnux Thanks for your input. What you mentioned sounds reasonable to me. Rename action should require `create` and `delete` permissioins. I will close this issue and open a new issue with `Can rename file/folder in group folder without delete permission on 29 and master`. Do you agree?

**Comment by susnux** [comment]
Sounds good.

I mean I understand that this might be unexpected for some users, but I think this would introduce inconsistency between storages.

**Comment by luka-nextcloud** [comment]
Opened another issue instead: https://github.com/nextcloud/server/issues/47142
