### ISSUE TITLE
Encryption and external auth (like ldap)

### ISSUE THREAD

**Issue by himbeere** [nextcloud/server#4711]
nextcloud 11 here.

Hello Devs.

I guess i found a disadvantage of the current encryotion implementation. Our users coming from a LDAP backend. I considered turning on the encryption module but i guess i would have serious problems with decrypting the users files if the password changes on the the LDAP backend. Is that right? My understanding is it the private key is encrypted with the users password. 

Any hints?

thanks and cheers

**Comment by MorrisJobke** [comment]
> Any hints?

use master key encryption, which will be default with Nextcloud 13 (#5174)
