### ISSUE TITLE
[Bug]: Deleted files offer not-working "view-in-folder" action

### ISSUE THREAD

**Issue by susnux** [nextcloud/server#47115]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The file actions for deleted files offer the file action "view in folder" but that action does not work, it will redirect to files where of course no file is visible.

Is it intended to be called "Show source folder" or similar? Or should it not be shown at all?

![image](https://github.com/user-attachments/assets/dc25ee30-96b9-4306-ab74-3209102f2d93)

### Steps to reproduce

1. upload a file
2. delete the file
3. go to trash bin
4. click file actions

### Expected behavior

Either name it "Show source folder" or do not show it at all.

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

cc @skjnldsv

**Comment by skjnldsv** [comment]
It's a mistake, it should not be shown at all
It means the conditions are wrongly defined
https://github.com/nextcloud/server/blob/d0951b48be3a5ba5957c8a233be66dbc1d1af823/apps/files/src/actions/viewInFolderAction.ts#L16-L38

**Comment by skjnldsv** [comment]
We should check that the source is indeed at the root of the user folder too
