### ISSUE TITLE
autoupload

### ISSUE THREAD

**Issue by brjhaverkamp** [nextcloud/server#4712]
### Steps to reproduce
I have autoupload enabled for a while now.
Somehow last month it stopped working. Now it only uploads newer pictures I took, but the older ones remain in the queue with the message "Waiting to upload"

### Expected behaviour
All pictures in the queue upload one by one

### Actual behaviour
Whatever I try, the pictures in the queue don't upload

### Server configuration
Nextcloud server 11.0.2
**Operating system**:
Ubuntu Linux 16.04

Nextcloud android client 1.4.2
Android 7.0
Huawei P9 plus

**Comment by MorrisJobke** [comment]
Please report to the android repo: https://github.com/nextcloud/android/issues
