### ISSUE TITLE
Update from Nextcloud  10.0.5 -> 11.0.3

### ISSUE THREAD

**Issue by baumimwald** [nextcloud/server#4713]
### Steps to reproduce
1. Owncloud 9.1.4 -> Nextcloud 10.0.5
2. Nextcloud 10.0.5 -> Nextcloud 11.0.3

### Expected behaviour
After deleting the nextcloud 11 confs and data folder and replacing it with the folders from version 10.0.5 the updater shoud update all modules.

### Actual behaviour
Updater stops and says "Doctrine\DBAL\Schema\SchemaException: There is no column with name 'uid' on table 'oc_accounts"

### Server configuration

**Operating system**: Ubuntu 14.04.5 LTS 

**Web server:** Apache2

**Database:** mysql 5.6.33

**PHP version:** 7.0

**Nextcloud version:** (see Nextcloud admin page) 10.0.5 -> 11.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from Owncloud 9.1.3

**Where did you install Nextcloud from:** manual install via zip-file

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed -> Cannot access page

```
</details>

**List of activated apps:**
<details>
<summary>List of activated apps</summary>

```
Enabled:
  - activity: 2.3.2
  - calendar: 1.5.2
  - comments: 1.0.0
  - contacts: 1.5.3
  - dav: 1.0.1
  - encryption: 1.3.1
  - external: 1.2
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - gallery: 15.0.1
  - lookup_server_connector: true
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 0.3.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.5
  - templateeditor: 0.1
  - theming: 1.0.1
  - twofactor_backupcodes: true
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - firstrunwizard
  - logreader
  - nextcloud_announcements
  - sharebymail
  - user_external
  - user_ldap
  - user_saml

```
</details>

**Nextcloud configuration:**

<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "5140a4eb8729a",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "******\/owncloud\/data",
        "debug": false,
        "dbtype": "mysql",
        "version": "9.1.5.2",
        "installed": true,
        "maintenance": false,
        "loglevel": "2",
        "log_type": "owncloud",
        "logfile": "****owncloud.log",
        "logtimezone": "Europe\/Berlin",
        "log_authfailip": true,
        "forcessl": true,
        "theme": "",
        "maxZipInputSize": 0,
        "allowZipDownload": true,
        "check_for_working_htaccess": true,
        "check_for_working_webdav": true,
        "log_rotate_size": 1048576,
        "updatechecker": true,
        "has_internet_connection": true,
        "trusted_domains": [******
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.gmx.net",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "enable_previews": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "mail_from_address": "*****",
        "mail_domain": "GMX.de",
        "overwrite.cli.url": "https:\/****/owncloud",
        "forceSSLforSubdomains": true,
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/owncloud"
    }
}

</details>

<details>
<summary>Other info</summary>
**Are you using external storage, if yes which one:** No

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Using Webdav and Calddav features (if this was asked

### Client configuration
**Browser:** Firefox

**Operating system:**
Windows 7 

</details>

<details>
<summary>Screenshots</summary>
```
</details>

![image](https://cloud.githubusercontent.com/assets/7488845/25758083/7041b420-31cd-11e7-9ab6-89cc94ceca27.png)
![image](https://cloud.githubusercontent.com/assets/7488845/25759107/6ed579c4-31d1-11e7-8e39-d5abc701f8d4.png)

**Comment by ottopor** [comment]
I'm also facing the similar issue. I was using owncloud, upgraded owncloud to nextcloud 10.0.5 and it was working all fine. Then I tried to upgrade it to latest nextcloud version and found the same error (like baumimwald), and I can't roll back as it says downgrade is not supported. So my nextcloud instance is now broken. I would really appreciate on help to fix this.

**Comment by aoliynik** [comment]
I had the same issue when tested migration path from owncloud 9.1.5 to nextcloud 11.0.3. 
On 10.0.5 -> 11.0.3 step I've removed table oc_accounts from mysql database (actually it contained just admin user for my installation with user_ldap app) and upgrade went smooth after this.  I could login as admin after upgrade.

**Comment by ottopor** [comment]
Thank aoliynik, I built a local installation of nextcloud 10.0.5, and in that oc_accounts was empty (it has only two columns). I'll try your steps on the production and see what happens.

**Comment by ottopor** [comment]
And it worked. Thanks aoliynik.

**Comment by baumimwald** [comment]
Indeed it worked. Thanks. Although I do not understand the purpose of oc_accounts. Does anybody have an explanation?

**Comment by freibadschwimmer** [comment]
I am stuck with the same issue.
Upgrade path:
OC 9.1.5 --> NC 10.0.5
NC 10.0.5 --> NC 11.0.3

When attempting to upgrade from 10 to 11 I receive the error message.
My original oc_accounts, on which the upgrade routines complains, holds all the user information in different columns (username, email-address, display name, quota, storage location etc). 
I have an NC 11 installation which I installed from sratch. It only contains 2 columns (uid and data, whereas all the user information is in the data column).

Since NC10 seems to work fine and displays the user information correctly in the web interface, my s is that the NC 10.0.3 upgrade is not able to convert the oc_accounts into a proper format.

**Comment by Crante** [comment]
Hello
I found a simple solution that looks to work,
You need connect to your SQL base, for example via PhpMyAdmin,
Found oc_accounts table and in structure menu, modify id to uid .

After, i make again : sudo -u www-data php ./occ upgrade and it's work perfectly.
Hope to help someone.

**Comment by MorrisJobke** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
