### ISSUE TITLE
Wrong image URL in email

### ISSUE THREAD

**Issue by RobertSmits** [nextcloud/server#4715]
### Issue
Het images in the Nextcloud emails point to the wrong path when using system cron.
When using AJAX for corn jobs there is no problem.

### Steps to reproduce
1. Have cron jobs executed by system's cron
2. Have 'overwrite.cli.url' in config
3. Download a shared file/edit shared document
4. Receive email notification

### Expected behaviour
The images in the email point to the web location on the server
(http://nextcloud.example.com/core/img/logo.svg?v=51)

### Actual behaviour
The images in the email point to the path on the server
(/srv/nextcloud.example.com/core/img/logo.svg?v=51)

### Server configuration

**Operating system**: 
Ubuntu Server 17.04

**Web server:** 
Apache 2.4.25

**Database:** 
MariaDb 10.1.22

**PHP version:** 
7.0.15

**Nextcloud version:** 
12.0 Beta 1

**Updated from an older Nextcloud/ownCloud or fresh install:** 
Update from 11.x

**Where did you install Nextcloud from:** 
Archive from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.1
  - calendar: 1.5.2
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.2.0
  - notifications: 2.0.0
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - richdocuments: 1.1.26
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - socialsharing_diaspora: 1.0.1
  - socialsharing_email: 1.0.1
  - socialsharing_facebook: 1.0.1
  - socialsharing_googleplus: 1.0.1
  - socialsharing_twitter: 1.0.1
  - spreed: 2.0.0
  - survey_client: 1.0.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.0
  - twofactor_totp: 1.3.0
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - bookmarks
  - encryption
  - external
  - files_downloadactivity
  - files_external
  - systemtags
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
<?php
$CONFIG = array (
  'updatechecker' => true,
  'trusted_domains' =>
  array (
    0 => 'nextcloud.example.com',
  ),
  'datadirectory' => '/Nextcloud',
  'dbtype' => 'mysql',
  'version' => '12.0.0.16',
  'logtimezone' => 'UTC',
  'installed' => true,
  'appstore.experimental.enabled' => true,
  'mail_domain' => 'nextcloud.example.com',
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'nextcloud',
  'loglevel' => 2,
  'maintenance' => false,
  'theme' => '',
  'htaccess.RewriteBase' => '/',
  'overwrite.cli.url' => '/srv/nextcloud.example.com/',
  'updater.server.url' => 'https://updates.nextcloud.com/updater_server/',
  'updater.release.channel' => 'beta',
  'memcache.local' => '\OC\Memcache\APCu'
);
</details>

**Comment by LukasReschke** [comment]
overwrite.cli.url should also be set to https://nextcloud.example.com in your config.php :)
