### ISSUE TITLE
Smart Sync

### ISSUE THREAD

**Issue by Kycko** [nextcloud/server#4717]
Hello guys!
[Dropbox team launched Smart Sync](https://www.dropbox.com/business/smartsync) for Business users. I think it is a great feature to add it into nextcloud ^_^.

**Comment by JScharloo** [comment]
This would complete my life. I have a large private cloud that I whish to access native-alike (no web interface and preferably no dodgy DAV mounts) but syncing hundreds of GB's on each device is a no-go. Selective sync is an option but it will not show what is not synced, which is confusing.

All in all... +1!

**Comment by MorrisJobke** [comment]
cc @karlitschek

**Comment by karlitschek** [comment]
Agreed. This is on the roadmap for a long time.

**Comment by JScharloo** [comment]
@karlitschek As in, it has already been on the roadmap for a long time, or this is on the long-term (distant future) roadmap?

**Comment by karlitschek** [comment]
It has been on the roadmap for a long time :-) Hopefully someone volunteers soon to implement this

**Comment by lordfolken** [comment]
Please make this policy based. i.e. that i as an admin can define what can be synchronized and what not.

**Comment by JScharloo** [comment]
$40 for the lucky and loveley one that makes this :)

**Comment by AndrewBucklin** [comment]
Make that $100! ...I'll throw in $60 to the pot. 

(Windows preferably for me.)

**Comment by Kycko** [comment]
@JScharloo @AndrewBucklin wow, now I want to learn PHP and JavaScript xD

**Comment by JScharloo** [comment]
@Kycko If it was just PHP (and I had a little more time) I'd do it myself. But the desktop apps this enhancement relates to are written in different languages.

**Comment by derWalter** [comment]
where do you add the money? is there a way to "upload" money to a specific issue? :)

i would also throw in some money if possible!

**Comment by AndrewBucklin** [comment]
https://www.bountysource.com/issues/44909892-smart-sync
I haven't done it yet, as nobody has expressed interest and I don't want to tied up my $60.

**Comment by derWalter** [comment]
I am not so sure whats the way to go, have you read about the idea of a virtual file system (VFS)?
It was introduced as a research task for owncloud in 2016,
https://help.nextcloud.com/t/wishlist-ability-to-whitelist-files-as-well-as-folders-for-sync/3871/4

I would be in to drop some dough as well, but aiming for the best solution would be beneficial :)

**Comment by ickennio** [comment]
Would be great to have selective sync on nextcloud :) 👍

**Comment by derWalter** [comment]
After owncloud got it running: https://github.com/owncloud/client/issues/4342
can't next cloud just use their code?

**Comment by hoerup** [comment]
Owncloud have now released a pilot version of their VFS solution https://owncloud.org/news/owncloud-client-goes-virtual-sync-files-demand/

**Comment by michaelstingl** [comment]
related: https://github.com/nextcloud/desktop/issues/184

**Comment by jospoortvliet** [comment]
This has to be done in the clients. Of course, we test the code of ownCloud, we'll have to see if we ship it though as it has issues. But let's track this at the desktop client, not here.

**Comment by nc-ruppdi** [comment]
I dont see this feature listed in the roadmap plannings for NC20 and NC21 - did I miss something?
