### ISSUE TITLE
Link from user status to out of office settings

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/server#47187]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When people go on vacation, they usually set their user status to "Vacationing", but sometimes fail to set the OOO settings in `settings/user/availability`. 

**Describe the solution you'd like**
Maybe we could think about showing a link on the user status modal to the OOO settings or even showing the OOO settings directly when "Vacationing" is selected.

**Describe alternatives you've considered**
Leave everything as is and hope everyone remembers.

**Comment by nickvergessen** [comment]
yeah had the same idea. We should show a message when selecting the predefined "Vacationing" status

**Comment by SystemKeeper** [comment]
Maybe something for @nextcloud/designers ?

**Comment by szaimen** [comment]
I like the idea 👍

**Comment by nickvergessen** [comment]
> which team would this be part of?

Maksim and me maintain the app and can have a quick look

**Comment by Antreesy** [comment]
Should be enough? Or change it to `set absence period and replacement`?

![image](https://github.com/user-attachments/assets/1221f8a9-171e-4315-903f-2eff6e80ebf7)

**Comment by nickvergessen** [comment]
I would say "and replacement" and maybe we can add the `↗️` to mark it as a link?
