### ISSUE TITLE
Webdav: "No 'Authorization: Basic' header found" spamming in log

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/server#4720]
### Steps to reproduce
I can reproduce this error by syncing calendars with MacOS

### Expected behaviour
no errors

### Actual behaviour
The following error appears every 2 minutes

![unbenannt-1](https://cloud.githubusercontent.com/assets/1473674/25775668/bc082eba-32aa-11e7-832a-3e88e7f48df0.jpg)

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache 2.4

**Database:**
MySQL 5.7.15

**PHP version:**
7.0.14

**Nextcloud version:** (see Nextcloud admin page)
11.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
11.0.0 fresh, then update to 11.0.1, 11.0.2 and 11.0.3

**Where did you install Nextcloud from:**
NextCloud.com

**List of activated apps:**
Deleted files
file sharing
Gallery
log Reader
notifications
Password policy
PDF Viewer
share by mail
text Editor
theming
update notification
Video Player
calendar
contacts
TOTP

**Nextcloud configuration:**

$CONFIG = array (
'instanceid' => 'XXX',
'passwordsalt' => 'XXX',
'secret' => '/XXX/XXX/',
'trusted_domains' => 
array (
0 => 'XXX',
),
'datadirectory' => '/www/htdocs/XXX/XXX',
'overwrite.cli.url' => 'https://XXX',
'tempdirectory' => '/www/htdocs/XXX/XXX/tmp',
'dbtype' => 'mysql',
'version' => '11.0.3.2',
'dbname' => 'XXX',
'dbhost' => 'localhost',
'dbport' => '',
'dbtableprefix' => 'oc_',
'dbuser' => 'XXX',
'dbpassword' => 'XXX',
'logtimezone' => 'UTC',
'installed' => true,
'maintenance' => false,
'theme' => '',
'loglevel' => 0,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox 53.0.2

**Operating system:**
Windows 10

**Comment by schaefal** [comment]
Same behaviour to me. Log full of entrys, but not regulary. 
The error appears every time a client is syncing.

Additionally i can't configure CalDav on an Ipad (10.3.1) where it claims about the SSL connection. The existing connections on iPhone and Android are working so fare.

**--- System ---**
Apache 2.2
PHP 5.6.x
MySQL 5.5.x
Debian 7.11
Updated from Owncloud to Nextcloud 10, 11.x

**Comment by MorrisJobke** [comment]
This is debug log. Just increase the log level and you are fine.
