### ISSUE TITLE
Cannot Upgrade from Owncloud 10.0.0.12 to Nextcloud 11.0.3

### ISSUE THREAD

**Issue by tdm4** [nextcloud/server#4721]
When I try to upgrade from Ownclod 10.0.0.12 to Nextcloud 11.0.3, I get an error:

"Exception: Updates between multiple major versions and  downgrades are unsupported. Upgrade failed."

I was running Owncloud 9.1.4 before, but a package update upgraded it to 10.0.0.12 and I wanted to switch to Nextcloud. I also noticed Nextcloud 11.0.3 came out 3 days before Owncloud 10.0.0.. so I guess I'm going to have to wait for Nextcloud 12 to come out in order to upgrade to it?

The versioning scheme confuses me. :(

Would it be recommended I restore a backup from Owncloud 9.1.4 and then try to upgrade that to Nextcloud 11.0.3?

**Comment by MariusBluem** [comment]
> When I try to upgrade from Ownclod 10.0.0.12 to Nextcloud 11.0.3, I get an error:

This is intended behaviour: https://github.com/nextcloud/server/pull/3415

You will be able to migrate **ownCloud 10** to **Nextcloud 12** in the coming weeks, or by helping us testing our latest beta-release (migrate to Nextcloud 12 **now**): https://nextcloud.com/blog/nextcloud-12-beta-introduces-the-next-generation-of-secure-collaboration/

> Would it be recommended I restore a backup from Owncloud 9.1.4 and then try to upgrade that to Nextcloud 11.0.3?

Well ... this may be an option too 😉

**Comment by tdm4** [comment]
@MariusBluem Thanks for the info! I restored my Owncloud 9.1.4 backup from 4 weeks ago (I hadn't changed much data on it thankfully) and then upgraded to Nextcloud 11.0.3 and it worked a treat!

**Comment by MariusBluem** [comment]
Great 👍 Welcome in the awesome Nextcloud community 💪🙈
