### ISSUE TITLE
Log is filled with nouserexception

### ISSUE THREAD

**Issue by Temtaime** [nextcloud/server#4722]
Error while running background job (OC\User\NoUserException): Attempted to initialize mount points for null user and no user in session
OCA\Files_Versions\Command\Expire {
	fileName: "/FTP/_REMOVED",
	user: "admin"
}
/var/www/html/apps/files_versions/lib/Storage.php - line 104: OC\Files\Filesystem initMountPoints(false)
/var/www/html/apps/files_versions/lib/Storage.php - line 706: OCA\Files_Versions\Storage getUidAndFilename('/FTP/devar_kids...')
/var/www/html/apps/files_versions/lib/Command/Expire.php - line 62: OCA\Files_Versions\Storage expire('/FTP/...')
/var/www/html/lib/private/Command/CommandJob.php - line 35: OCA\Files_Versions\Command\Expire->handle()
/var/www/html/lib/private/BackgroundJob/Job.php - line 53: OC\Command\CommandJob->run('O 33 "OCA\\Files...')
/var/www/html/lib/private/BackgroundJob/QueuedJob.php - line 43: OC\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
/var/www/html/cron.php - line 128: OC\BackgroundJob\QueuedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
{main}

occ files_external:list

| 1        | /FTP        | FTP     | Username and password | host: "_REMOVED", root: "", secure: false, user: "_REMOVED", password: "***" | previews: false, filesystem_check_changes: 0 | admin |                   | Personal |

### Steps to reproduce
1. Add an FTP as external storage

### Expected behaviour
No error in the log

### Actual behaviour
Hundreds of errors in the log

### Server configuration

**Operating system**:
Linux

**Web server:**
Nginx

**Database:**
MariaDB

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
11.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
9.1.4

**Where did you install Nextcloud from:**
zip from downloads page

**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - audioplayer: 1.5.1
  - checksum: 0.3.4
  - comments: 1.1.0
  - dav: 1.1.1
  - direct_menu: 0.10.1
  - federatedfilesharing: 1.1.1
  - files: 1.6.1
  - files_automatedtagging: 1.1.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "ocikxtf5b3ao",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.acomirei.ru"
        ],
        "datadirectory": "\/var\/lib\/owncloud\/data",
        "check_for_working_htaccess": false,
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/lib\/owncloud\/apps",
                "url": "\/apps-appstore",
                "writable": true
            }
        ],
        "preview_max_x": 512,
        "preview_max_y": 512,
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/cloud.acomirei.ru",
        "dbtype": "mysql",
        "version": "11.0.3.2",
        "dbname": "c_nextcloud",
        "dbhost": "10.0.0.101",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_domain": "acomirei.ru",
        "mail_from_address": "cloud",
        "mail_smtphost": "10.0.0.101",
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "127.0.0.1",
            "port": 6379
        },
        "maintenance": false
    }
}

**Are you using external storage, if yes which one:** FTP

**Are you using encryption:** no

**Comment by MorrisJobke** [comment]
Please try again with 11.0.4 or 12.0.4 we fixed some stuff there, that looks like this.
