### ISSUE TITLE
Public API to file versions

### ISSUE THREAD

**Issue by caco3** [nextcloud/server#4724]
I would like to write a KDE 5 Dolphin integration to list and revert to previous versions of a file.
Is there an REST API available to access the version information like the sidebar does in the files app?

The documentation at https://docs.nextcloud.com/server/11/user_manual/files/version_control.html doesnt give any information on that.

**Comment by MorrisJobke** [comment]
cc @schiessle @rullzer Is this exposed via DAV or OCS?

**Comment by rullzer** [comment]
This is currently not exposed. However it would probabaly be good to do so. I guess webdav makes the most sense since serving binary data over OCS is terrible.

So to sum up

1. it is not there
2. it probably should be there
3. We should do this over DAV

**Comment by MorrisJobke** [comment]
@rullzer This is also wanted for Android (see #5761)

**Comment by rullzer** [comment]
Not yet writing docs is on my todo

**Comment by jospoortvliet** [comment]
> Great work!
> Looking forward to implement a KDE dolphin client for this.
> Is there already an API documentation available?
Any chance to integrate this in the desktop client and its dolphin integration?!?? There is a bunch of changes for the upcoming release introducing a sub menu... A 'versions' window  might fit there.
