### ISSUE TITLE
App update notification, yet no update button

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#4725]
### Steps to reproduce
1. NC notifies me that "action is required", so log into NC
2. Click on notification bell, it says an update for Two Factor U2F to version 1.3.1 is available.
3. Clicking on it takes me to Active Apps. Scroll down. "Two Factor U2F" is there, but only the deactivate button, no update button.

### Expected behaviour
Well, I'd like to update the app ...

### Actual behaviour
... but can't

### Additional information
I then tried to force the current version by deactivating, deleting, and reinstalling/activating the app. Result was, that instead of version 1.3.0 which I had before, I now have 1.2.0 ... and no update button.

### Server configuration
OS: debian 8, up-to-date
Web server: Apache 2.4
Database: mySQL 5.5
PHP version: 5.6
Nextcloud version: 11.0.3, updated from an older Nextcloud
Where did you install Nextcloud from: NC updater app
Signing status: "No errors have been found."

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - apporder: 0.3.3
  - audioplayer: 1.5.1
  - bookmarks: 0.9.1
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - direct_menu: 0.10.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - gallery: 16.0.0
  - keeweb: 0.3.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.4
  - notifications: 1.0.1
  - ownbackup: 17.3.0
  - ownpad: 0.5.7
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - systemtags: 1.1.3
  - tasks: 0.9.5
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.1.0
  - twofactor_u2f: 1.2.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - firstrunwizard
  - nextcloud_announcements
  - survey_client
  - templateeditor
  - user_external
  - user_ldap
  - user_saml

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto,90",
        "versions_retention_obligation": "90,auto",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "mydomain.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/mydomain.de\/cloud",
        "dbtype": "mysql",
        "version": "11.0.3.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_domain": "mydomain.de",
        "defaultapp": "calendar",
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "updater.release.channel": "stable"
    }
}

**Are you using external storage:** no
**Are you using encryption:** no
**Are you using an external user-backend:** no

### Client configuration
**Browser:** Firefox 53.0
**Operating system:** Linux Mint 18.1

#### Web server error log
"PROPFIND /cloud/remote.php/dav/files/myuser/ HTTP/1.1" 207 4791 "-" "Mozilla/5.0 (Linux) mirall/2.3.1 (Nextcloud)"

#### Nextcloud log (data/nextcloud.log)
(nothing)

#### Browser log
(did not collect this since it cannot be  a client issue)

**Comment by ChristophWurst** [comment]
> I then tried to force the current version by deactivating, deleting, and reinstalling/activating the app. Result was, that instead of version 1.3.0 which I had before, I now have 1.2.0 ... and no update button.

Sorry for the confusion. We hat some critical bugs in the 1.3.0 and 1.3.1 version of the app so that we had to remove the release from the app store to prevent that more installation update to it. Apparently the information about an available update for the app was cached (either on the nc instance or on the app store) and thus caused a wrong notification.

This shouldn't have happened with the usual flow. Thanks for reporting this though and again, sorry for the inconvenience.

**Comment by ChristophWurst** [comment]
FYI we're working on a fix for the U2F app and it will be available ASAP.

**Comment by nursoda** [comment]
Thanks a lot, Christoph. True, it seems to be a caching issue: Even after I deactivated AND deleted the app I get the notification. Now: How to get rid of that (using web interface, or occ if necessary)?

**Comment by ChristophWurst** [comment]
> How to get rid of it using web interface

cc @nickvergessen

**Comment by nickvergessen** [comment]
When you however a notification, there should be a ✖️  in the top right corner which you can use to delete a notification.

**Comment by nursoda** [comment]
That was probably too easy. Sorry! Will try next time I get a notification. Much easier that SQL CLI ;-)
