### ISSUE TITLE
[Bug]: File drop zone does not disappear when not dropping anything

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/server#47268]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The File drop zone in the files app does not disappear when not dropping anything

### Steps to reproduce

1. Drag a file over the files app in the browser
2. Upload zone appears
3. Drag it somewhere else without dropping it on the files upload zone
4. The upload zone will not disappear

### Expected behavior

The upload zone disappears

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by marcelklehr** [comment]
This is even an issue as far back as nc 28

**Comment by edward-ly** [comment]
I found that the issue is caused by `apps/files/src/components/BreadCrumbs.vue` not having listeners attached for the `dragleave` and `dragend` events.

Could someone in @nextcloud/files work on this and give an ETA on a fix?

**Comment by susnux** [comment]
@marcelklehr do you use Firefox? Because if using Firefox then this is a Browser bug and we implemented a work-around right now:
https://github.com/nextcloud/server/pull/47465

Can you check this fixes the problem for you?

**Comment by marcelklehr** [comment]
I'm no longer able to reproduce this on daily. Can we make sure to backport this to stable28?

**Comment by skjnldsv** [comment]
Done in https://github.com/nextcloud/server/pull/47639
