### ISSUE TITLE
[Bug]: No "Leave this share" context menu entry when in "Shared with you" view

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/server#47269]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Shared files displayed in "All files" in the files app have a context menu entry that reads "Leave this share".
The same files should have the same entry when viewing them in "Shared with you" in the files app.

### Steps to reproduce

1. Open files app
2. Go to "shared with you"
3. Open Three-dot-menu of a shared file 
4. See no "Leave this share" entry

### Expected behavior

There should be a "Leave this share" entry, same as in "All files"

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by marcelklehr** [comment]
This is even an issue on 28

**Comment by joshtrichards** [comment]
I believe this is what #47339 ended up addressing. Or is this something else, @marcelklehr?

**Comment by marcelklehr** [comment]
Yes
