### ISSUE TITLE
[Bug]: File entry context menu appears in wrong place

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/server#47270]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After having used the right click to open the context menu on a file entry, when you then use the three-dot menu on the same entry, the context menu will not open underneath the three-do menu but on the spot where you last right clicked.

### Steps to reproduce

1. Open the files app
2. Click on three dot menu of a file entry
3. Correct position of menu
4. Now, right click somewhere on the file entry
5. context menu opens underneath the mouse pointer
6. close the context menu
7. click on three dot menu of the same file entry
8. context menu opens at the spot where you right clicked last

### Expected behavior

Context menu should always open underneath the three dot menu, when clicking the three dot menu.

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by SystemKeeper** [comment]
Noticed the same: https://github.com/nextcloud/server/issues/46934

**Comment by marcelklehr** [comment]
Joint Marcel power :muscle:
