### ISSUE TITLE
Can file metadata be stored in S3 storage after configuring NextCloud to store as S3 storage

### ISSUE THREAD

**Issue by samfor12** [nextcloud/server#47299]
I have been doing an action recently. Due to my mistake in deleting the latest database, I can only restore to the most recent database backup. When re accessing NextCloud, it was found that some errors were reported when accessing files on NextCloud, all of which claimed that the stored data did not exist (partially).
1.Does this mean that the database stores metadata stored in S3 instead of being stored in S3?
2.Does this mean that I need to backup my database at all times?

Nextcloud logs are available anytime, if needed

**Comment by joshtrichards** [comment]
If you're referring to using S3 as *Primary Storage* (versus *External Storage*) this is all documented here:

https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/primary_storage.html

If you have general questions or troubleshooting needs, please use the help forum - https://help.nextcloud.com
