### ISSUE TITLE
[Bug]: Nextcloud not showing with cloudflare dns

### ISSUE THREAD

**Issue by jozua-dev** [nextcloud/server#47315]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi, everybody

i am currently building a nextcloud server at home and i am trying to use it with a cloudflare dns but unfortunately i only get a blank screen, no erros just the nextcloud background incl logo(see picture)
![image](https://github.com/user-attachments/assets/2f022124-46a4-4e80-8ef7-b9df65fc0297)
i have rocket loader off.
the login screen show with a free dns service from no-ip and a ssl from lets-encrypt

### Steps to reproduce

1.install ubuntu server
2.follow instructions-->https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-nextcloud-on-ubuntu-22-04

### Expected behavior

login screen showing to setup nextcloud further

### Installation method

Community SNAP package

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
Thanks for your report. However this appears to be a configuration/deployment matter rather than a bug. I suggest posting your query on the help forum - https://help.nextcloud.com
