### ISSUE TITLE
[Bug]: Files can be deleted through public read-only share link

### ISSUE THREAD

**Issue by DonMikone** [nextcloud/server#47317]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Whenever I share a folder (not a single file) with public share link (allow upload and edit unchecked), I can delete the displayed files through the public link by clicking on the three dots and select delete file. This is a severe security issue and makes Nextcloud unusable for me since everyone I send read-access links to can basically delete my files. 

### Steps to reproduce

1. Nextcloud client on macOS (with virtual files) -> Rightclick on folder -> Public link share (Allow upload and editing off)
2. Open copied link in browser
3. Click three dots next to file and select "delete file"

### Expected behavior

There should not be an option to delete or alter a file unless explicitly selected by the host.

### Installation method

None

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by kesselb** [comment]
Thanks for your report :+1: 

I'm unable to reproduce your finding with the upcoming Nextcloud 30.0.0 and Nextcloud 28.0.8. 

If you want to follow up on this one, please open a report at https://hackerone.com/nextcloud, so our security team can take a look.
