### ISSUE TITLE
Protect config files deployed via orchestration software

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#4732]
### Steps to reproduce

1. Deploy Nextcloud using Puppet
2. Go to the admin panel and make a change
3. Look at your config file

### Expected behaviour

The lines which come from the deployment script should never, ever change

### Actual behaviour

Things change

----

@schiessle

**Comment by MorrisJobke** [comment]
> The lines which come from the deployment script should never, ever change

That is not easily possible, because we simply use the PHP serialisation feature of PHP to create this file once a change happened. :/

**Comment by oparoz** [comment]
One solution which was discussed with @schiessle is to use a conf.d folder.

**Comment by nickvergessen** [comment]
You can prevent writing with:
https://github.com/nextcloud/server/blob/4d101ca2bec2f8b799535b35188755dbb01e9641/config/config.sample.php#L636-L646

**Comment by MorrisJobke** [comment]
Why a conf.d folder? Maybe deploy the changes to orchestration.config.php because all files that are ending on .config.php are merged and only config.php is written. That's also how I locally keep most of the settings but can easily reset the instance.

**Comment by MorrisJobke** [comment]
@nickvergessen but then you can't upgrade. :/

**Comment by oparoz** [comment]
> Maybe deploy the changes to orchestration.config.php because all files that are ending on .config.php are merged and only config.php is written

It doesn't work like this in reality. You sometimes end up with 2 keys for the same item, one in orchestration.config.php and one in config.php

**Comment by MorrisJobke** [comment]
> It doesn't work like this in reality. You sometimes end up with 2 keys for the same item, one in orchestration.config.php and one in config.php

Yes and the one from the orchestration.config.php is overwriting the one from config.php.

**Comment by MorrisJobke** [comment]
> Yes and the one from the orchestration.config.php is overwriting the one from config.php.

This is a working solution -> closing.

@oparoz If you have further questions about this: ping me, I'm happy to assist you and explain you more details about possible deployment scenarios.
