### ISSUE TITLE
Auto zoom when using Nextcloud on Safari iOS

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#47328]
I used our web interface a couple of times now on mobile safari and if feels quite strange and is partially also annoying that Safari is automatically zooming to input elements and also contenteditables (e.g. in text) when you focus them.

This used to work differently and in my perspective also should for a web app that is not a pure content page.

This was introduced in https://github.com/nextcloud/server/commit/ac736b2f82adfe73176fa78620e617ff17dbc91e as a accessibility fix where I still agree that manually zooming should be possible, however maybe we can get rid of the automatic zoomin.

I found https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone as a possible option.

@nextcloud/designers What do you think about that? Any arguments against changing this?

**Comment by susnux** [comment]
Tested a bit, all the meta solutions will break android.
So either:
1. Add that meta attribute only on ios (by user agent)
2. Increase our font size to 16px (Safari then does not auto zoom)
3. No zooming again (probably not good)

**Comment by jancborchardt** [comment]
@susnux solution 1 and 3 are the same though, no? Meaning blocking zoom on Safari, which is an issue for accessibility.

cc @marcoambrosini regarding the font size question, although we never were at 16px so it must always have happened.

**Comment by susnux** [comment]
@jancborchardt 1 means we keep the zooming behavior but set `maximum-scale=1` when UA is Safari.
This will stop auto-zoom on iOS but keep user zoom. But only works on Safari, on Chrome it breaks user zooming.

BTW 16px is the default font size of (every?) browser, benefit would be that the line height would be 24px instead of 22.5px (which looks sometimes odd due to the fraction).

**Comment by jancborchardt** [comment]
@susnux true, we just keep user-scalable. Then solution 1 sounds best and simplest, right? Seems fine to me :+1:

**Comment by juliushaertl** [comment]
Thanks so much for checking that out right away @susnux ❤️ 

Using the web UI is so much smoother now on iOS
