### ISSUE TITLE
Sharing with users disappear after link creation

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#4739]
Share a file with a single user, create a link share - share with single user is not longer visible;

Nextcloud 12 beta

<img width="372" alt="bildschirmfoto 2017-05-08 um 15 20 50" src="https://cloud.githubusercontent.com/assets/19711361/25805973/fab515c6-3401-11e7-8358-ce5e3ed570a6.png">

**Comment by rullzer** [comment]
Works here... 

* share with user
* Enable link share

I see both....

**Comment by MariusBluem** [comment]
Safari?

**Comment by rullzer** [comment]
Nope. Linux user

**Comment by MorrisJobke** [comment]
Tested with Safari and works:

<img width="641" alt="bildschirmfoto 2017-05-14 um 23 09 22" src="https://cloud.githubusercontent.com/assets/245432/26042372/6858da0c-38fa-11e7-8af5-1c21c0a5cf65.png">


Can't reproduce. Please retry with beta 2.
