### ISSUE TITLE
[Bug]: after entering file name, template modal takes ages to load

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/server#47416]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

when creating a new file, after clicking the + and entering the file name, the template modal takes ages to load (about 15s on c.nc.c).

In the meantime nothing happens, and eventually, the popup appears, allowing one to pick a template.

### Steps to reproduce

1. go to Files
2. click on + to create a new markdown file for example
3. enter a filename "I love nc30" for example and hit enter
4. wait
5. eventually, the template picker shows up.

### Expected behavior

template picker should show up way faster, and/or a loading item should also tell the user something is happening in the background.

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

c.nc.c

**Comment by sorbaugh** [comment]
@Pytal maybe we can schedule this?

**Comment by susnux** [comment]
@sorbaugh this is not a front end bug¹, the real problem is that `GET /ocs/v2.php/apps/files/api/v1/templates` takes for ages to load even with only few templates. Meaning the template backend suffers performance issues.

¹ Well we should show a loading indicator, maybe even open the dialog but with "loading templates <spinner>" inside?

**Comment by juliusknorr** [comment]
This should have been resolved in richdocuments by properly caching the extracted metadata from templates. 

@maximelehericy Please let us know if you still encounter this.

**Comment by maximelehericy** [comment]
hmmm, still taking some 7s...  @juliusknorr

**Comment by JL710** [comment]
> [@maximelehericy](https://github.com/maximelehericy) Please let us know if you still encounter this.

I use nextcloud aio and updated yesterday to 30.0.2 and have the same issue. It takes around 1,5 minutes for my system to get a response from `/ocs/v2.php/apps/files/api/v1/templates`.
