### ISSUE TITLE
[Bug]: Long footer may hide content information, e.g. on public upload folders

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#47426]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When opening a public link with a folder upload, the information about the uploaded files might not be visible. Please see the screencast – first window is current Nextcloud master, the other is NC 28.

[Screencast_20240822_155030.webm](https://github.com/user-attachments/assets/4e38772b-62f5-44ce-84bc-f0badb2e19fc)

### Steps to reproduce

0. Set a long slogan in the Theming settings
1. Share an upload-only folder via public link
2. Open that link on mobile, or in a browser size of a mobile browser
3. Upload a file

### Expected behavior

The list of uploaded files is clearly visible, at least it can be scrolled. 

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by susnux** [comment]
Just wanted to mention that we must not make the footer smaller, because it might contain legally required information.
(We just should make sure the main app content has enough padding on the bottom to compensate).
