### ISSUE TITLE
"php occ trashbin:cleanup" removes files_trashbin/files from filesystem

### ISSUE THREAD

**Issue by daniela-waranie** [nextcloud/server#4743]
After running this command :
`php occ trashbin:cleanup`

I get the following error (my data dir is /vagrant/data/owncloud):
`Error	PHP	opendir(/vagrant/data/owncloud/admin/files_trashbin/files): failed to open dir: No such file or directory at /var/www/nextcloud/lib/private/files/storage/local.php#100	2017-05-08T15:23:51+00:00	admin
`
The "trashbin:cleanup" removed files_trashbin/files dir in each user-dir.

While it can be easy repaired it should be fixed in occ.
By the way: would be nice if occ will be renamed to ncc. Next occ should issue a deprication warning before forwarding command to ncc - for a while.

**Comment by MorrisJobke** [comment]
cc @icewind1991 @schiessle

**Comment by daniela-waranie** [comment]
Background: i'm on a migration path from owncloud 8.2.11 to nextcloud 11.0.3. 
The first migration step was to migrate to nextcloud 9.0.58. I ran that "occ" command with nextcloud 9.0.58.

Even if support for nc9 is end-of-life i think "migration-support" should be still available, because nc9 is subject of the recommended migration path. The above command is a basic admin task.

**Comment by MorrisJobke** [comment]
> By the way: would be nice if occ will be renamed to ncc. Next occ should issue a deprication warning before forwarding command to ncc - for a while.

We know, but as of now this has no priority and only cause more confusion ;)

And you are right - the migration path should be kept stable.

**Comment by skjnldsv** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

I'm guessing we fixed this already as we create the dir if it is missing now.
