### ISSUE TITLE
[Bug]: custom mail template class is broken in 29.0.5

### ISSUE THREAD

**Issue by phreaker0** [nextcloud/server#47430]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I guess on code restructure one function call was forgotten to be adapted with the new logo parameters:
https://github.com/nextcloud/server/blob/5b8bbd375fefce3e9fb9564abcc395706bd1a622/lib/private/Mail/Mailer.php#L136

### Steps to reproduce

1. Use a custom "mail_template_class" for mailing
2. Upgrade to nextcloud v29.0.5
3. Creating shares errors out and lot's of errors in the log

### Expected behavior

Creating shares works without errors and no errors in the log with custom mail  template class.

### Installation method

Community Manual installation with Archive

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 28.0.1 to 28.0.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Logs

```shell
{"reqId":"U9sl2V4TMbKYY9EsDtlv","level":3,"time":"2024-08-22T13:35:06+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job OCA\\Activity\\BackgroundJob\\EmailNotification (id: 2, arguments: null)","userAgent":"--","version":"29.0.5.1","exception":{"Exception":"TypeError","Message":"OC\\Mail\\EMailTemplate::__construct(): Argument #4 ($logoWidth) must be of type ?int, string given, called in /var/www/nextcloud/lib/private/Mail/Mailer.php on line 136","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Mail/Mailer.php","line":136,"function":"__construct","class":"OC\\Mail\\EMailTemplate","type":"->"},{"file":"/var/www/nextcloud/apps/activity/lib/MailQueueHandler.php","line":324,"function":"createEMailTemplate","class":"OC\\Mail\\Mailer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/activity/lib/MailQueueHandler.php","line":124,"function":"sendEmailToUser","class":"OCA\\Activity\\MailQueueHandler","type":"->"},{"file":"/var/www/nextcloud/apps/activity/lib/BackgroundJob/EmailNotification.php","line":58,"function":"sendEmails","class":"OCA\\Activity\\MailQueueHandler","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/Job.php","line":80,"function":"run","class":"OCA\\Activity\\BackgroundJob\\EmailNotification","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":102,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":92,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":177,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/nextcloud/lib/private/Mail/EMailTemplate.php","Line":337,"message":"Error while running background job OCA\\Activity\\BackgroundJob\\EmailNotification (id: 2, arguments: null)","exception":[],"CustomMessage":"Error while running background job OCA\\Activity\\BackgroundJob\\EmailNotification (id: 2, arguments: null)"},"id":"66c754f1d3fbd"}
```

**Comment by kesselb** [comment]
Regression from https://github.com/nextcloud/server/pull/46419
