### ISSUE TITLE
Renamed nodes that are out of viewport keep renaming state

### ISSUE THREAD

**Issue by susnux** [nextcloud/server#47438]
> Just tried 29.0.5 and the bug is only partially fixed :
> - If you rename a file and the new name sends the file at the bottom of the list, not visible on screen, then the folder stays in edit mode and you need to reload the page.

_Originally posted by @Mer0me in https://github.com/nextcloud/server/issues/42813#issuecomment-2304590366_

---

1. Have a list with nodes 1 to 50
2. Rename 1 to 51, so it is moved to the very bottom.
3. Scroll down to it
4. See that rename state is still active

**Comment by Mer0me** [comment]
Still present on 29.0.7

**Comment by susnux** [comment]
As you can see the issue is still open so no fix yet.

**Comment by Mer0me** [comment]
Is it supposed to be fixed on 30.0.1 ? It's not...

**Comment by susnux** [comment]
No as you can see the backport is not yet merged, so earliest is 30.0.2.
Track progress in: https://github.com/nextcloud/server/pull/48731

**Comment by susnux** [comment]
This is was fixed and backports are expected to be merged in November maintenance releases (30.0.2 and 29.0.9).
If you experience a similar issue **after** updating to one of those issues, please open a *new* issue.
For general discussion please use: https://help.nextcloud.com/
