### ISSUE TITLE
Wrong documentation for OCP\Mail\Provider\IMessage / OCP\Mail\Provider\IMessageSend

### ISSUE THREAD

**Issue by kesselb** [nextcloud/server#47447]
Please change `@param` to `@return` for:

https://github.com/nextcloud/server/blob/0cab17bfe7825e49d3dd6608f20f46164c975e31/lib/public/Mail/Provider/IMessage.php#L46-L48

https://github.com/nextcloud/server/blob/0cab17bfe7825e49d3dd6608f20f46164c975e31/lib/public/Mail/Provider/IMessage.php#L66-L68

https://github.com/nextcloud/server/blob/0cab17bfe7825e49d3dd6608f20f46164c975e31/lib/public/Mail/Provider/IMessage.php#L86-L88

https://github.com/nextcloud/server/blob/0cab17bfe7825e49d3dd6608f20f46164c975e31/lib/public/Mail/Provider/IMessage.php#L106-L108

https://github.com/nextcloud/server/blob/0cab17bfe7825e49d3dd6608f20f46164c975e31/lib/public/Mail/Provider/IMessage.php#L126-L128

https://github.com/nextcloud/server/blob/0cab17bfe7825e49d3dd6608f20f46164c975e31/lib/public/Mail/Provider/IMessage.php#L146-L148

https://github.com/nextcloud/server/blob/0cab17bfe7825e49d3dd6608f20f46164c975e31/lib/public/Mail/Provider/IMessage.php#L169-L171

https://github.com/nextcloud/server/blob/0cab17bfe7825e49d3dd6608f20f46164c975e31/lib/public/Mail/Provider/IMessage.php#L189-L191

https://github.com/nextcloud/server/blob/0cab17bfe7825e49d3dd6608f20f46164c975e31/lib/public/Mail/Provider/IMessage.php#L209-L211

Please change `$options` to `$option`

https://github.com/nextcloud/server/blob/0cab17bfe7825e49d3dd6608f20f46164c975e31/lib/public/Mail/Provider/IMessageSend.php#L27-L31

Please backport to changes to stable30

**Comment by SebastianKrupinski** [comment]
Wow. How did I/we miss that! (face palm)

**Comment by SebastianKrupinski** [comment]
> Please change @param to @return for

Done

> Please change $options to $option

I changed the function variable to match the doc as there can be multiple options.
