### ISSUE TITLE
[l10n] Wording of file type filter "Pictures and images"

### ISSUE THREAD

**Issue by susnux** [nextcloud/server#47440]
Today I noticed that the translation is a bit weird in German: "Bilder und Abbildungen".
While this is technically correct, I think it is a bit misleading and probably should be "Bilder und Photos".
 
But maybe this is not just a problem with German, but maybe we should adjust the English term,
as this filter is intended to filter image files like PNG, photos like JPG or vector graphics like SVG.

Maybe change it?
Currently we use **"Pictures and images"**, how about **"Photos and images"**?
Or now that we have the whiteboard maybe also **"Photos and drawings"** (I have not checked if they are considered images or office documents).

Or maybe just **"Pictures"**?

English | German
---|---
![Screenshot 2024-08-23 at 00-00-34 Files - Nextcloud](https://github.com/user-attachments/assets/93e58091-c5dc-4c24-a560-104eb4f99789)|![Screenshot 2024-08-22 at 23-59-33 Dateien - Nextcloud](https://github.com/user-attachments/assets/8410498d-4295-49ad-8512-301c46198df5)

cc @nextcloud/designers @rakekniven

**Comment by jancborchardt** [comment]
Google Drive calls it "Photos & images" which we could do too. "Pictures" and "images" is too much the same thing, but I think it’s good to have the inclusion of both "photos" and "images" which can be anything like screenshots, icons etc.

**Comment by jancborchardt** [comment]
So:
- English: "Photos & images"
- German: "Fotos & Bilder"
