### ISSUE TITLE
[Bug]: "app cannot be enabled because it makes the server unstable" v29

### ISSUE THREAD

**Issue by githubbbie** [nextcloud/server#47444]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After installing Nextcloud using docker-compose, unning 29.0.1.1 and getting the error upon trying to download & enable apps:

"Error: This app cannot be enabled because it makes the server unstable"

![image](https://github.com/user-attachments/assets/bd461bde-5eb6-49c0-abc6-c35d55de9ac3)

```
$ cat /etc/lsb-release
DISTRIB_ID=Pop
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Pop!_OS 22.04 LTS"
```

Attaching my docker-compose.yml:
[docker-compose.yml.txt](https://github.com/user-attachments/files/16714365/docker-compose.yml.txt)

(remove the .txt to test)

Tested to downgrade to version 28 and got Nextcloud working.

BTW, I am running this on localhost HTTP without any reverse proxy. Running: localhost:8080

### Steps to reproduce

1. Run my docker-compose
2. Create default admin
3. Goto Disabled Apps, Try to Enable one (TOTP is what I tried)

### Expected behavior

Confirmed again this IS working for the latest version of the v28 series looks like: 28.0.9.1

Attaching my docker-compose.yml and hope this helps anyone:

[docker-compose.yml.txt](https://github.com/user-attachments/files/16715070/docker-compose.yml.txt)

### Installation method

Community Docker image

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
> 29.0.1.1

Is there a reason you're testing against an outdated v29 release rather than >= 29.0.4?

> Confirmed again this IS working for the latest version of the v28 series looks like: 28.0.9.1

Makes sense since this sounds like a bug we already fixed in [maintenance releases](https://docs.nextcloud.com/server/latest/admin_manual/release_schedule.html) we published for both 28 and 29. :-)

I suspect your problem will go away if you simply run an up-to-date 29 release.

P.S. Your `cron` container lacks appropriate volumes. It should contain the same volumes as your `app` container or you will run into problems.

**Comment by githubbbie** [comment]
> > 29.0.1.1
> 
> Is there a reason you're testing against an outdated v29 release rather than >= 29.0.4?

Running against what was the latest from docker hub. Looks like now for 29 series is 29.0.5:

https://hub.docker.com/_/nextcloud

> > Confirmed again this IS working for the latest version of the v28 series looks like: 28.0.9.1
> 
> Makes sense since this sounds like a bug we already fixed in [maintenance releases](https://docs.nextcloud.com/server/latest/admin_manual/release_schedule.html) we published for both 28 and 29. :-)
> 
> I suspect your problem will go away if you simply run an up-to-date 29 release.

Ok, took your advice and upgraded to latest in 29 series 29.0.5 from docker nextcloud.

After fixing a few issues after the update with internet access from my containers, this is working!

> P.S. Your `cron` container lacks appropriate volumes. It should contain the same volumes as your `app` container or you will run into problems.

Thanks! Fixed.

In the future, I will pay more attention to the updates and the various procedures in Nextcloud for updating instances.

CLOSING.
