### ISSUE TITLE
Hide two-factor auth filter in activities

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#4747]
* disable "Two-factor authentication" if none of those apps are enabled 
* see nextcloud/activity#150

cc @ChristophWurst

**Comment by LukasReschke** [comment]
Maybe just move this to a generic "security" category where we also could show logins and so on?

**Comment by ChristophWurst** [comment]
> Maybe just move this to a generic "security" category where we also could show logins and so on?

Fine by me. Where should I put that code? Currently I've [added the generic 2fa stuff to the backup codes](https://github.com/nextcloud/server/blob/9ad57cabc8aeaaf0565001936233979426d41a6a/apps/twofactor_backupcodes/lib/Activity/GenericProvider.php) app, but that doesn't really fit for generic security activities.

@LukasReschke @nickvergessen should I add a `security`, `security_activity`, `activity_security` or similar app?

**Comment by nickvergessen** [comment]
I'd say add it to the settings app, which already handles activities for email and password change:
https://github.com/nextcloud/server/blob/master/settings/Application.php#L115

**Comment by ChristophWurst** [comment]
> Maybe just move this to a generic "security" category where we also could show logins and so on?

Login activities sound like a nice enhancement. We could publish an activity whenever a browser session or device token is created. This is, however, something for NC13 I assume.
