### ISSUE TITLE
Call to undefined method OCA\LookupServerConnector\BackgroundJobs\RetryJob::shouldRun()

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#4756]
### Steps to reproduce
1. Update to nc12 beta1
2. Watch the log get spammed

### Expected behaviour
Clean log

### Actual behaviour
Get ``Call to undefined method OCA\LookupServerConnector\BackgroundJobs\RetryJob::shouldRun() at /var/www/nextcloud/apps/lookup_server_connector/lib/BackgroundJobs/RetryJob.php#57``

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**
5.6

**Nextcloud version:** (see Nextcloud admin page)
NC12 beta1

See https://github.com/nextcloud/server/blob/37b847ec48bab86f6d126f5c2185f0a5bc0a4267/apps/lookup_server_connector/lib/BackgroundJobs/RetryJob.php#L57
https://github.com/nextcloud/server/blob/37b847ec48bab86f6d126f5c2185f0a5bc0a4267/lib/private/BackgroundJob/Job.php doesn't have that method. Was it removed?

cc @schiessle @nickvergessen

**Comment by rullzer** [comment]
@schiessle

**Comment by benediktg** [comment]
I have Nextcloud 12 beta 2 and the same problem. As #4788 was merged yesterday I assume it will be contained in beta 3?

![screenshot_20170511_141501](https://cloud.githubusercontent.com/assets/14795615/25948835/afcafd86-3655-11e7-89ef-1190c364f146.png)
![screenshot_20170511_141453](https://cloud.githubusercontent.com/assets/14795615/25948836/afcbd09e-3655-11e7-9961-e28248e726f1.png)
![screenshot_20170511_141435](https://cloud.githubusercontent.com/assets/14795615/25948837/afd02248-3655-11e7-8b13-59f4a7d8d4bc.png)

**Comment by nickvergessen** [comment]
yes, sorry
