### ISSUE TITLE
[Bug]: [stable29] File not opened after creation in new Folders

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#47565]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When a user creates a file in the web interface, the file automatically opens. Unless, a folder is created before, then it does not work.

### Steps to reproduce

1. Go to Nextcloud Files
2. Create a new directory
3. Enter the new directory
4. Create a new (text) file

### Expected behavior

The expected behaviour is that the text editor opens automatically (as it does when in an old folder, or after reloading the page). But it does not. No errors are logged in the console. It smells like a state thing in the frontend.

### Installation method

None

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by artonge** [comment]
29 only.
This error is shown: https://github.com/nextcloud/server/blob/469e45877888bb2a0ea8387ebc3109b0650dd986/apps/files/src/components/FilesListVirtual.vue#L255-L256

**Comment by blizzz** [comment]
I saw the error only in one of a few cases and thought i clicked it wrong. Perhaps should check with the oculist, or i was too focused on the browser console.

**Comment by susnux** [comment]
Fixed by @artonge in https://github.com/nextcloud/server/pull/47571
