### ISSUE TITLE
[Bug]: "Exclude groups from password requirements" setting not saved

### ISSUE THREAD

**Issue by enjeck** [nextcloud/server#47569]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After setting `  'sharing.allow_disabled_password_enforcement_groups' => true,` in `config.php`, the "Exclude groups from password requirements" select shows up as expected. But when I enter a group there, it's not really saved. After reloading, set groups disappear. Also, the setting doesn't work as the groups are not actually excluded. 

## Video of the problem:

https://github.com/user-attachments/assets/4f8c3ff0-5c26-4a97-b4aa-a1650e503296

cc: @susnux , since you recently edited this. 

### Steps to reproduce

1. `'sharing.allow_disabled_password_enforcement_groups' => true,` in `config.php`
2. Visit /settings/admin/sharing
3. Enter groups in the "Exclude groups from password requirements"

### Expected behavior

The groups should be saved and visible after reloading. Plus, the groups should be excluded from the password requirement. 

### Installation method

None

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

I checked the requests, and see the request is made and claims to be successful. But apparently not? 

192.xxx.xx.x - - [28/Aug/2024:12:21:58 +0000] "POST /ocs/v2.php/apps/provisioning_api/api/v1/config/apps/core/shareapi_password_excluded_groups HTTP/1.1" 200 935 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36"

**Comment by provokateurin** [comment]
I'll take a look next week
