### ISSUE TITLE
[Bug]: Nextcloud 29 - No dialog for enable recovery key after activating default encryption module

### ISSUE THREAD

**Issue by roman-doubrava** [nextcloud/server#47580]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Dear Nextcloud team,
after a fresh installation of Nextcloud 29 and enabling default server encryption the dialogs for "Enable recovery key" and "Enable password recovery" are not show like spciefied here: 
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/encryption_configuration.html#enabling-users-file-recovery-keys

We tested also Logout and Login and new user creation, but non of these gets the message to set a recovery key initially.

Was the whole recovery key functionality dropped in Nextcloud 29 ?

Best regards

### Steps to reproduce

1. Install Nextcloud 29
2. Activate App default encryption module 
3. Enable Server side Encryption
4. Logout and Login 
5. Create New User and Login

### Expected behavior

1. Set Recovery Key section should be visible

### Installation method

Community Web installer on a VPS or web space

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
The recovery key is only applicable in per-user key mode. The default is master key. So it's expected behavior that you're not being prompted for it.

https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/encryption_details.html#key-type-master-key
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/encryption_details.html#key-type-recovery-key
