### ISSUE TITLE
[Bug]: Elements moving around in Grid View when scrolling

### ISSUE THREAD

**Issue by sorbaugh** [nextcloud/server#47599]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

See screencast:

https://github.com/user-attachments/assets/032802eb-e4fc-415e-b8a2-c7c8c469076a

### Steps to reproduce

1. Go to Files Tab (ideally a folder with lots of files)
2. Use the grid view 
3. Scroll down

### Expected behavior

Elements shouldn't shift around

### Installation method

None

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by artonge** [comment]
Can reproduce. I thought I had it fixed. Let me dive in it again.

**Comment by iw0nderhow** [comment]
Has the fix shipped already? The shifting happens to me with Nextcloud 30.0.1 in Firefox 132 as well as Safari 18.0.1

**Comment by dronnikovigor** [comment]
Same happens for me after upgrading to 30.0.2. Checked on Chrome & Safari.

**Comment by artonge** [comment]
Could be improved by https://github.com/nextcloud/server/pull/49561

**Comment by zeiseiwogn** [comment]
This issue came back with one of the last updates from Nextcloud.
