### ISSUE TITLE
Login image not shown in /settings/admin/theming

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#4759]
Can't really reproduce it reliably but on c.nc.c/settings/admin/theming the login image isn't shown for administrators anymore.

Any idea, @juliushaertl?

<img width="1112" alt="screen shot 2017-05-09 at 13 23 22" src="https://cloud.githubusercontent.com/assets/878997/25848454/b757bd9c-34ba-11e7-952b-13c3b420b2e8.png">

**Comment by juliushaertl** [comment]
Not sure what has caused this, but a fix is in #4772
