### ISSUE TITLE
[Bug]: Nextcloud 29 - No fileKey created after enabling server side encryption module

### ISSUE THREAD

**Issue by roman-doubrava** [nextcloud/server#47594]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Dear Nextcloud team,

when we install the latest Nextcloud 29 and enable default encryption module + server side encryption after uploading files, we are missing the fileKey as stated in the documentation: 
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/encryption_details.html#file-type-file-key-file

What we see on the server after uploading test files: 

Private public share key: data/files_encryption/OC_DEFAULT_MODULE/pubShare_xxx.privateKey
Public public share key: data/files_encryption/OC_DEFAULT_MODULE/pubShare_xxx.publicKey
Private public master key: data/files_encryption/OC_DEFAULT_MODULE/master_xxx.privateKey
Public public master key: data/files_encryption/OC_DEFAULT_MODULE/master_xxx.publicKey
Share keys for files owned by the user: data/<user>/files_encryption/keys/<file_path>/OC_DEFAULT_MODULE/master_xxx.shareKey

1) We would have expected one more fileKey file in: data/<user>/files_encryption/keys/files/<file_path>/OC_DEFAULT_MODULE/fileKey"

2) We would like to test a manual decryption like used here: https://github.com/syseleven/nextcloud-tools/blob/master/debug/decrypt-file.php which expects the fileKey as well.

Best regards
User

### Steps to reproduce

1. Install Nextcloud 29
2. Activate App default encryption module
3. Enable Server side Encryption
4. Upload some files into the server
5. No fileKey is generated in data/<user>/files_encryption/keys/files/<file_path>/OC_DEFAULT_MODULE/fileKey"

### Expected behavior

fileKey file is generated in data/<user>/files_encryption/keys/files/<file_path>/OC_DEFAULT_MODULE/fileKey" for each encrypted file

### Installation method

None

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
The recovery tools you linked to are the old ones (you'll note there is a banner saying they're archived). The correct up-to-date ones are here:

https://github.com/nextcloud/encryption-recovery-tools

The filekey isn't relevant / and the updated version of the recovery tool was updated to handle the changes. (i.e. see https://github.com/nextcloud/server/pull/37243#issuecomment-1633664923)
