### ISSUE TITLE
Regarding the issue of environment variables related to the container version of NextCloud

### ISSUE THREAD

**Issue by samfor12** [nextcloud/server#47630]
Dear Nextcloud developers
May I ask what environment variables related to the container version of NextCloud can be set.
for example
```
MYSQL_DATABASE
MYSQL_PASSWORD
etc.....
```
Thank you
Wishing you all a wonderful day
Send from SAM

**Comment by joshtrichards** [comment]
This is not a support channel. Help questions should be posted to the help forum - https://help.nextcloud.com

Please refer to the documentation[^1]: https://github.com/nextcloud/docker/?tab=readme-ov-file#auto-configuration-via-environment-variables 

[^1]: (at least if that's the image you're using; there are multiple images)
