### ISSUE TITLE
[Bug]: accounts -> error message as group manager when you are not allowed to fetch the line manager details

### ISSUE THREAD

**Issue by kesselb** [nextcloud/server#47642]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

[Screencast from 2024-08-30 15-51-30.webm](https://github.com/user-attachments/assets/47d20e04-721a-42d7-b231-357a6dcfb6e8)

### Steps to reproduce

1. Have Admin, Alice (group manager for A-Team), Bob (member of A-Team), Jim (member of A-Team), Tom (**not** a member of A-Team)
2. Admin: Set Tom as line manager for Bob
3. Alice: Login and open the account section
4. See a warning 

### Expected behavior

No warning

**Comment by sorbaugh** [comment]
cc @Pytal can you triage? 🙏

**Comment by Pytal** [comment]
Reproduced 🤔
