### ISSUE TITLE
ownbackup causing integrity and internal errors on Nextcloud 12

### ISSUE THREAD

**Issue by joekerna** [nextcloud/server#4765]
### Steps to reproduce
1. Activate ownbackup app
2. click on _Additional settings_ in the admin section

### Expected behaviour
The _Additional settings_ section should appear

### Actual behaviour
An internal server error appears

> Anforderungskennung: 2UwA3TjFmoTXkWO7k9bT

### Server configuration

**Operating system**: Ubuntu 17.04

**Web server:** Nginx

**Database:** Mysql

**PHP version:** 7.1.5

**Nextcloud version:** 12 Beta 2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Web Updater

**Signing status:**
<details>
<summary>Signing status</summary>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- ownbackup
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.

Raw output
==========
Array
(
    [ownbackup] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate is not valid.
                )

        )

)
```
</details>

**Are you using external storage, if yes which one:** Dropbox

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox 49.9.0 ESR

**Operating system:** Windows 10

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Exception: The requested uri(/settings/admin/ocs/v2.php/apps/notifications/api/v2/notifications) cannot be processed by the script '/apps/notifica')

    /var/www/nextcloud/lib/base.php - line 927: OC\AppFramework\Http\Request->getRawPathInfo()
    /var/www/nextcloud/index.php - line 40: OC handleRequest()
    {main}



OCP\AppFramework\QueryException: Could not resolve AppName! Class AppName does not exist

    /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 117: OC\AppFramework\Utility\SimpleContainer->resolve('AppName')
    /var/www/nextcloud/lib/private/ServerContainer.php - line 116: OC\AppFramework\Utility\SimpleContainer->query('AppName')
    /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 66: OC\ServerContainer->query('AppName')
    /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 96: OC\AppFramework\Utility\SimpleContainer->buildClass(Object(ReflectionClass))
    /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php - line 117: OC\AppFramework\Utility\SimpleContainer->resolve('OCA\\OwnBackup\\C...')
    /var/www/nextcloud/lib/private/ServerContainer.php - line 116: OC\AppFramework\Utility\SimpleContainer->query('OCA\\OwnBackup\\C...')
    /var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php - line 410: OC\ServerContainer->query('OCA\\OwnBackup\\C...')
    /var/www/nextcloud/apps/ownbackup/admin.php - line 19: OC\AppFramework\DependencyInjection\DIContainer->query('\\OCA\\OwnBackup\\...')
    /var/www/nextcloud/lib/private/legacy/app.php - line 727: include('/var/www/nextcl...')
    /var/www/nextcloud/settings/Controller/AdminSettingsController.php - line 102: OC_App getForms('admin')
    /var/www/nextcloud/settings/Controller/AdminSettingsController.php - line 93: OC\Settings\Controller\AdminSettingsController->getLegacyForms()
    /var/www/nextcloud/settings/Controller/AdminSettingsController.php - line 73: OC\Settings\Controller\AdminSettingsController->getSettings('additional')
    [internal function] OC\Settings\Controller\AdminSettingsController->index('additional')
    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\AdminSettingsController), 'index')
    /var/www/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\AdminSettingsController), 'index')
    /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OC\\Settings\\Con...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /var/www/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /var/www/nextcloud/lib/base.php - line 975: OC\Route\Router->match('/settings/admin...')
    /var/www/nextcloud/index.php - line 40: OC handleRequest()
    {main}
```
</details>

This is in reference to pbek/ownbackup#18:

Activating ownbackup on Nextcloud 12 causes integrity errors (see log above) and it also causes the _Additional settings_ section to fail.

Deactivating the app enables the _Additional settings_ section again, the integrity errors remain.

**Comment by JSoko** [comment]
* Just go to apps
* deactivate it
* deinstall it
* install and activate it
* run the integry-check again

**Comment by MorrisJobke** [comment]
You need to install the app from the App Store to have a proper signature. Installing the git version is usually not working, because once a file changes the signature is invalid.

If I understand it correctly this problem was when installing the app via a github zip file. 

I wil close this, if this was the App Store install, then we are happy to look into this again. 

Thanks

**Comment by Laupe** [comment]
@MorrisJobke This error also occurs when downloading from App Store. 

```
root@private:/home/cloud_sudo -u www-data php /home/apps/cloud/occ integrity:check-app qownnotesapi
  - EXCEPTION:
    - class: OC\IntegrityCheck\Exceptions\InvalidSignatureException
    - message: Certificate is not valid.
```

https://github.com/pbek/qownnotesapi/issues/12

I have a problem with multiple applications.

I have done the exact procedure described by @JSoko

**Comment by joekerna** [comment]
@MorrisJobke you misunderstood me. I did download the app from the appstore. I only went to github to create the issue because I thought it was an issue with the app itself.
I tried @JSoko 's suggestion but without success.

I think you should reopen the issue.
Thanks

**Comment by nursoda** [comment]
This bug addresses TWO issues:
* signature/integrity of ownbackup
* app or signature causing additional settings section to crash
I think they should be separated.

Concerning the integrity, there's another bug (in ownbackup issues) already: https://github.com/pbek/ownbackup/issues/10
Concerning the crash, I just added another bug (duplicate?) since I did not deduct from the title of this bug that it is related to admin settings: https://github.com/nextcloud/server/issues/4823

**Comment by MorrisJobke** [comment]
> since I did not deduct from the title of this bug that it is related to admin settings: #4823

Then close this one here and go for #4823

**Comment by pbek** [comment]
The settings crash was handled in <https://github.com/pbek/ownbackup/issues/17> but the InvalidSignatureException is still there. It's the same with https://github.com/pbek/qownnotesapi/. Both apps are in the NC store, were signed with a ownCloud certificate and did work until NC 11.
