### ISSUE TITLE
 How to edit a file without any extension (ie README for ex) ?

### ISSUE THREAD

**Issue by ericxuo** [nextcloud/server#4768]
Hi,

This post is a copy/paste from this one : https://help.nextcloud.com/t/how-to-edit-a-file-without-extension-ie-readme/12065

I have 2 files in my nextcloud repository. One named myfile.txt, the other README.
Both are pure text files.
When I click on the first one, an editor window opens and I can modify the file.
For the README file, I can only save it on my computer (and modify it with my favorite text editor).
If I rename the README file under README.txt, then the nextcloud editor window opens.
My question : how to be able to edit (with the nextcloud editor) a file that does not have an extension.

From the answer to my previous post, it seems that mime types are determined from file extension. Is it possible to add the possibility to get them from (for example) the linux 'file' command ?

Regards.

Xuo.

**Operating system**:
Mageia 5
**Web server:**
Apache
**PHP version:**
php5
**Nextcloud version:** (see Nextcloud admin page)
11.0.3
Updated from an older Nextcloud version.

**Comment by MorrisJobke** [comment]
Currently this is not possible, because we do mime type detection based on extension. cc @rullzer

**Comment by ericxuo** [comment]
Hi,

Thank you for your answer. It's so bad, but do you plan to add/modify this feature in the future ?

Regards.

Xuo.

**Comment by MorrisJobke** [comment]
> Thank you for your answer. It's so bad, but do you plan to add/modify this feature in the future ?

It's currently not on our todo list, because that would mean to parse somehow the file and that is a lot harder to accomplish. Also we would then need to rescan all existing files.

But maybe @karlitschek or @icewind1991 has some insights into this.

**Comment by ericxuo** [comment]
OK. 

Regards.

Xuo.
