### ISSUE TITLE
[Bug]: Not possible to undo "unshare from me" if the calendar was shared to a group.

### ISSUE THREAD

**Issue by cyrillappert** [nextcloud/server#47694]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When a calendar is shared by the owner with a group and then unshared by one of the users, there is no way to retrieve that calendar for that user in the group except by sharing it directly with that person. If that specific share is deleted by the calendar owner, the calendar goes missing again, even though the user belongs to the group. The system seems to remember that the calendar was previously unshared.

### Steps to reproduce

1. Create a calendar and share it with a group.
2. Have one user from that group unshare the calendar.
3. Observe that there is no way to restore access to that calendar for the user, except by sharing it directly with them.
If the calendar owner deletes this direct share, the calendar goes missing again, despite the user being part of the group.

### Expected behavior

There should be an unshared calendar section in the settings where all the unshared calendars are listed and can be re-followed.

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

Oracle

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/server/issues/45783 IMO

**Comment by cyrillappert** [comment]
You are right. Sorry, I'll close.
