### ISSUE TITLE
[Bug]: Therefor it must be able to resolve and connect to at least one its `trusted_domains` or the `overwrite.cli.url`.

### ISSUE THREAD

**Issue by Azgar1998** [nextcloud/server#47718]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hello,

I updated from version 28.0.9 to 29.0.6. When I look at the configuration showers, I have lots of warnings and an error which I think is related:

> Your web server is not yet properly configured for file synchronization because the WebDAV interface appears not to work. To enable this verification, you must ensure that your web server can connect to itself. Therefore, it must be able to resolve and connect to at least one of its "trusted_domains" or "overwrite.cli.url".

> Your web server is not configured to provide `.js.map` files. Without these files, JavaScript source maps will not work properly, making it more difficult to troubleshoot and resolve any issues.
It is possible to check Javascript support via one of your `trusted_domains` or `overwrite.cli.url`. This may result from a server-side DNS mismatch or an outgoing firewall rule. Please manually check if your web server serves `.mjs` files using the JavaScript MIME type. To allow this check, you must ensure that your web server can connect to itself. It must therefore be able to resolve and connect to at least one of its `trusted_domains` or the URL `overwrite.cli.url`.

> Your web server is not properly configured to resolve "/ocm-provider/", "/ocs-provider/". This is probably related to a web server configuration that has not been updated to directly deliver this folder. Please compare your configuration with the rules rewritten in “.htaccess” for Apache or those contained in the Nginx documentation. For Nginx, the lines requiring an update are typically those starting with “location ~”. For more information, see the documentation ↗.
your web server is not configured correctly to resolve `.well-known` URLs, failed at: `/.well-known/webfinger` For more information, see the documentation ↗.

> Unable to verify that your web server serves security headers correctly, unable to request `/index.php/heartbeat` For more information, see the documentation ↗.

I looked elsewhere but without success

thank you for your help

### Steps to reproduce

1. trusted domain domain.com, domain, 127.0.0.1, localhost: without success
2. 'overwrite.cli.url' => 'https://127.0.0.1' (i tested with "domain" and "domain.com") in config.php: without success
3. in web server, i tested wget https://127.0.0.1 dans  https://domain.com : success

### Expected behavior

![image](https://github.com/user-attachments/assets/633907be-472d-4f58-b7b2-f297d4083b7b)

nextcloud 29.0.6
apache: 2.4
Ubuntu 22.04 LTS

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [X] SSO - SAML
- [ ] Other

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.1
  - files_downloadlimit: 2.0.0
  - files_external: 1.21.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - nextcloud_announcements: 1.18.0
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - photos: 2.5.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - support: 1.12.0
  - survey_client: 1.17.0
  - systemtags: 1.19.0
  - text: 3.10.1
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - updatenotification: 1.19.1
  - user_ldap: 1.20.0
  - user_saml: 6.2.0
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0
Disabled:
  - admin_audit: 1.19.0
  - bruteforcesettings: 2.9.0
  - encryption: 2.17.0
  - suspicious_login: 7.0.0
  - twofactor_totp: 11.0.0-dev
```

**Comment by joshtrichards** [comment]
This isn't a support channel. Please post your query at the help forum - https://help.nextcloud.com

**Comment by Azgar1998** [comment]
I found where it came from. We use a proxy which is entered in config.php. when I removed it all the aleters disappeared. are you sure this is not a bug?

Is there a way to bypass the proxy for this case?

Without the proxy the instance does not have access to the internet

**Comment by rdratlos** [comment]
In fact, it is a (minor) bug. Sys admins rely on Nextcloud's automatic checks and regard errors and warnings printed as to be taken seriously. Automatic checks are not documented well and even when using debug level not logged. The consequence is flooding of Nextcloud community and tracking systems.

@Azgar1998: Your the man. The deficient tests silently introduced in one of the upgrades really try to use configured proxies when testing the own server. What do we learn? If you require a proxy (e. g. for upgrade checks, apps, etc.) do not miss this in config.php:
```
  'proxyexclude' =>
  array (
    0 => '.domain.tld',
    1 => 'localhost',
    2 => '127.0.0.1',
    3 => '10.16.0.0/16',
  ),

```
Hope this helps others who upgraded without thinking and came accross some red messages.
