### ISSUE TITLE
[Bug]: rename(/var/log/nextcloud.log,/var/log/nextcloud.log.1): Permission denied

### ISSUE THREAD

**Issue by Stifler6996** [nextcloud/server#47725]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I receive this error every minute in the log:

`rename(/var/log/nextcloud.log,/var/log/nextcloud.log.1): Permission denied at /var/www/nextcloud/lib/public/Log/RotationTrait.php#51
`

The thing about this error is, that is a link. It is not a file. The link in /var/log is a hard link to /var/www/nextcloud/data/nextcloud.log

Now in /var/www/nextcloud/data/ I am seeing the log rotation is successful (ie: I have several gziped nextcloud.log.1.gz type files, and a live nextcloud.log.

So why is RotationTrait.php trying to rename my link in /var/log? This seems to been happening for quite some years.

![image](https://github.com/user-attachments/assets/0e96c233-9c56-4c9d-baf8-436e2482e99b)

### Steps to reproduce

I am not entirely sure how to reproduce this. I have had this install for a great many years, and I have done nothing in regards to configuration regarding a) logging or where it originally went and b) have done nothing with fail2ban configuration (if it is even automatically installed?).

I have read old closed topics regarding permissions on the files, which have been fixed a long time ago and I can confirm that my permissions on the /var/www/nextcloud/data/ are www-data:www-data. The link also happens to be www-data:www-data but this is not relevant since its a link!

### Expected behavior

Don't try to rename my static link in /var/log.

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Cannot load Zend OPcache - it was already loaded
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nc.fuzzylogic.tech",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "29.0.6.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "timeout": 1.5
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "timeout": 1.5,
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "logfile": "\/var\/log\/nextcloud.log",
        "mysql.utf8mb4": true,
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "default_phone_region": "AU",
        "app_install_overwrite": [
            "weather",
            "documentserver_community",
            "apporder",
            "breezedark",
            "files_fulltextsearch_tesseract",
            "files_rightclick",
            "llm"
        ],
        "allow_local_remote_servers": true,
        "maintenance_window_start": "15",
        "memories.exiftool": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/exiftool-amd64-glibc",
        "memories.vod.path": "\/var\/www\/nextcloud\/apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.vod.ffmpeg": "\/usr\/bin\/ffmpeg",
        "memories.vod.ffprobe": "\/usr\/bin\/ffprobe",
        "enabledPreviewProviders": [
            "OC\\Preview\\Movie",
            "OC\\Preview\\Image",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\TIFF"
        ],
        "memories.db.triggers.fcu": true,
        "memories.gis_type": 1
    }
}
```

### List of activated Apps

```shell
Cannot load Zend OPcache - it was already loaded
Enabled:
  - admin_audit: 1.19.0
  - apporder: 0.15.0
  - assistant: 1.1.0
  - bookmarks: 14.2.4
  - breezedark: 29.0.0
  - bruteforcesettings: 2.9.0
  - calendar: 4.7.16
  - cloud_federation_api: 1.12.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - cookbook: 0.11.1
  - dashboard: 7.9.0
  - dav: 1.30.1
  - documentserver_community: 0.1.18
  - external: 5.4.0
  - federatedfilesharing: 1.19.0
  - files: 2.1.1
  - files_3dmodelviewer: 0.0.14
  - files_downloadlimit: 2.0.0
  - files_external: 1.21.0
  - files_fulltextsearch: 29.0.1
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - fulltextsearch: 29.0.1
  - fulltextsearch_elasticsearch: 29.0.1
  - geoblocker: 0.5.14
  - gptfreeprompt: 1.0.2
  - integration_openai: 2.0.3
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - memories: 7.3.1
  - notes: 4.10.1
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - onlyoffice: 9.3.0
  - password_policy: 1.19.0
  - previewgenerator: 5.6.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recognize: 7.1.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - spreed: 19.0.8
  - suspicious_login: 7.0.0
  - text: 3.10.1
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - updatenotification: 1.19.1
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0
Disabled:
  - activity: 2.21.1 (installed 2.15.0)
  - circles: 29.0.0-dev (installed 22.1.1)
  - comments: 1.19.0 (installed 1.12.0)
  - encryption: 2.17.0 (installed 2.3.0)
  - federation: 1.19.0 (installed 1.3.0)
  - llm: 1.2.1 (installed 1.2.1)
  - nextcloud_announcements: 1.18.0 (installed 1.2.0)
  - photos: 2.5.0 (installed 1.4.0)
  - sharebymail: 1.19.0 (installed 1.17.0)
  - support: 1.12.0 (installed 1.10.0)
  - survey_client: 1.17.0 (installed 1.1.0)
  - systemtags: 1.19.0 (installed 1.12.0)
  - twofactor_totp: 11.0.0-dev
  - user_ldap: 1.20.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
{"reqId":"mT7xDSO8RABaSpIvU8QL","level":3,"time":"2024-09-04T05:26:02+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"rename(/var/log/nextcloud.log,/var/log/nextcloud.log.1): Permission denied at /var/www/nextcloud/lib/public/Log/RotationTrait.php#51","userAgent":"--","version":"29.0.6.1","data":{"app":"PHP"},"id":"66d7ef90250d8"}
{"reqId":"mT7xDSO8RABaSpIvU8QL","level":3,"time":"2024-09-04T05:26:02+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"rename(/var/log/nextcloud.log,/var/log/nextcloud.log.1): Permission denied at /var/www/nextcloud/lib/public/Log/RotationTrait.php#51","userAgent":"--","version":"29.0.6.1","data":{"app":"PHP"},"id":"66d7ef90250d8"}
{"reqId":"7hkfEuTtX1hdrsoOgY9Q","level":3,"time":"2024-09-04T05:25:02+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"rename(/var/log/nextcloud.log,/var/log/nextcloud.log.1): Permission denied at /var/www/nextcloud/lib/public/Log/RotationTrait.php#51","userAgent":"--","version":"29.0.6.1","data":{"app":"PHP"},"id":"66d7ef9025505"}


(Repeats every 60 seconds)
```

**Comment by kesselb** [comment]
I assume your log file is greater than 100mb and therefore log rotation want's to rename the file to `nextloud.log.1`.

Solution 1: Disable the log rotation by adding ` log_rotate_size => 0,` to your config.php
Solution 2: Make it possible for the Nextcloud user to create the file nextcloud.log.1

**Comment by kesselb** [comment]
> But Nextcloud seems to want to also "rotate" the static link. 
> "logfile": "\/var\/log\/nextcloud.log",

You configured Nextcloud to use the hardlink in /var/log. 

> I have several gziped nextcloud.log.1.gz type files

We don't have a feature to compress logfiles.

**Comment by Stifler6996** [comment]
> You configured Nextcloud to use the hardlink in /var/log.
I have configured nothing relating to logs.

>> I have several gziped nextcloud.log.1.gz type files

> We don't have a feature to compress logfiles.

Are you retarded? THIS ERROR IS BEING REPORTED IN YOUR FUCKING LOGS IN NEXTCLOUD.

I've had enough of your boneheaded attitude. Someone else can bring this up, and hopefully it is allocated to someone less braindead than you.

I have already found an alternative to nextfagged.

**Comment by kesselb** [comment]
That was rude, don't you think?

Please look at our https://nextcloud.com/contribute/code-of-conduct/ before you comment on one of our repositories again. 

> So why is RotationTrait.php trying to rename my link in /var/log? This seems to been happening for quite some years.

The RotationTrait rotates the log file if the size exceeds a given size. The implementation is simple, take the path, append .1 and rename.[^1] 

The path, to the log file, is taken from the configuration file "config.php". According to your configuration report, it's set to "/var/log/nextcloud.log". Therefore, the RotationTrait tries to rotate it.

> Now in /var/www/nextcloud/data/ I am seeing the log rotation is successful (ie: I have several gziped nextcloud.log.1.gz type files, and a live nextcloud.log.

We don't have a feature to compress log files (=> .gz files). If you see files in your log's folder ending with .gz that might be a different service like logrotate?

I guessed, from the provided information, that you configured an external service for the log rotation and recommend turning the log rotation in Nextcloud off. 

[^1]: https://github.com/nextcloud/server/blob/e37a88225d302b2a84855d1ef00035549bffed90/lib/public/Log/RotationTrait.php#L32-L33
