### ISSUE TITLE
Contacts menu entry to small when no contact option given

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#4773]
They should all have the same height. 

![2017-05-09-183506_355x315_scrot](https://cloud.githubusercontent.com/assets/3404133/25861972/b461c598-34e6-11e7-82a0-bb0edb760d8f.png)

@nextcloud/designers

**Comment by MorrisJobke** [comment]
@nextcloud/designers A small paper cut issue for the release polishing phase 😉

**Comment by kcskou** [comment]
By the way it looks like it has already been fixed as I cannot reproduce issue on Firefox 57.0.3 (64-bit).
![contacts-have-same-height](https://user-images.githubusercontent.com/3045168/34453844-d88da45c-ed12-11e7-84cb-2c7ad5dca436.png)

**Comment by juliushaertl** [comment]
Yes, seems to be fixed.
