### ISSUE TITLE
[Bug]: sometimes, uploading a large file fails

### ISSUE THREAD

**Issue by fred-c1** [nextcloud/server#47744]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Failure / error message at the end of the upload (see log below)

but sometimes it works OK.

### Steps to reproduce

1. upload a large (about 1GB) file by draging it from Windows desktop to the ***/apps/files/*** web page
2. at the end of the transfert an error message appears

### Expected behavior

No failure

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
Don't know how to do this.
Configuration = new (1 week ) AIO install on Raspberry Pi 4B (4GB RAM) + external USB drive only for datadir
```

### List of activated Apps

```shell
Don't know how to do this.
Configuration = new (1 week ) AIO install on Raspberry Pi 4B (4GB RAM) + external USB drive only for datadir
```

### Nextcloud Signing status

```shell
logged as admin
```

### Nextcloud Logs

```shell
[webdav] Error: Could not open file
	MOVE /remote.php/dav/uploads/admin/web-file-upload-2307288b9569478e/.file
	from 192.168.1.1 by admin at 1 sept. 2024, 17:02:00


[no app in context] Error: Could not open file
	MOVE /remote.php/dav/uploads/admin/web-file-upload-2307288b9569478e/.file
	from 192.168.1.1 by admin at 1 sept. 2024, 17:02:00
```

### Additional info

Thanks in advance

**Comment by joshtrichards** [comment]
>  - [x] This is a bug, not a question or a configuration/webserver/proxy issue.

Please troubleshoot your situation at the help forum before reporting as a bug - https://help.nextcloud.com

> Don't know how to do this.

`occ config:list system`
`occ app:list`

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html#config-commands
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html#apps-commands
https://github.com/nextcloud/all-in-one#how-to-run-occ-commands
