### ISSUE TITLE
Command "maintenance:singleuser" is not defined

### ISSUE THREAD

**Issue by Laupe** [nextcloud/server#4778]
### Steps to reproduce
1. `sudo -u www-data php /home/apps/cloud/occ maintenance:singleuser --on`
2. `sudo -u www-data php /home/apps/cloud/occ maintenance:singleuser --off`

### Expected behaviour
Turns on and turns on one user mode according to the [documentation](https://docs.nextcloud.com/server/12/admin_manual/configuration_server/occ_command.html#maintenance-commands)
```
sudo -u www-data php occ maintenance:singleuser --on
Single user mode enabled

sudo -u www-data php occ maintenance:singleuser --off
Single user mode disabled
```

### Actual behaviour

**Command "maintenance:singleuser" is not defined.**
```
[Symfony\Component\Console\Exception\CommandNotFoundException]
  Command "maintenance:singleuser" is not defined.
  Did you mean one of these?
      maintenance:update:htaccess
      maintenance:repair
      maintenance:mode
      maintenance:mimetype:update-js
      maintenance:mimetype:update-db
      maintenance:data-fingerprint

```

### Server configuration

**Operating system**:
Linux Debian 8

**Web server:**
Apache 2.4

**PHP version:**
5.6

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 12.0 beta 2

**Comment by nickvergessen** [comment]
The functionality has been removed, because it was not working as intended.
I will adjust the documentation, thanks for the hint.
