### ISSUE TITLE
[Bug]: Dashboard widgets text is doubled in Firefox

### ISSUE THREAD

**Issue by JuganD** [nextcloud/server#47793]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The titles of the widgets on the Dashboard are doubled.
![image](https://github.com/user-attachments/assets/e4c8dabe-0b35-40e6-8470-bf8dffd1411a)

The widget titles are also doubled in the customization window:
![image](https://github.com/user-attachments/assets/5898e9e2-a7c2-4a48-a32f-8a26d9ff08a9)

Tested with 2 different profiles, as well as newly created account - it happens on all of them.
It's not occurring in Chrome and Opera GX.

### Steps to reproduce

1. Start Firefox
2. Go to your Nextcloud dashboard
3. Widget titles are doubled

### Expected behavior

The titles should not be doubled.

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - bruteforcesettings: 2.9.0
  - circles: 29.0.0-dev
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.1
  - files_downloadlimit: 2.0.0
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - nextcloud_announcements: 1.18.0
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - photos: 2.5.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - support: 1.12.0
  - survey_client: 1.17.0
  - systemtags: 1.19.0
  - text: 3.10.1
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - updatenotification: 1.19.1
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0
Disabled:
  - admin_audit: 1.19.0
  - encryption: 2.17.0
  - files_external: 1.21.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - suspicious_login: 7.0.0
  - twofactor_totp: 11.0.0-dev
  - user_ldap: 1.20.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

**Comment by susnux** [comment]
Which version of Firefox do you use?

**Comment by JuganD** [comment]
Firefox version is 130.0 64-bit.

**Comment by susnux** [comment]
> Firefox version is 130.0 64-bit

Windows?

I can not reproduce this, might very likely be a browser bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1831523
or
https://bugzilla.mozilla.org/show_bug.cgi?id=1772176

**Comment by JuganD** [comment]
Yes, i'm on Windows.

Just noticed the origin of these texts - they are the labels of the icons. But instead of the icon being displayed, it just renders the label text.

**Comment by susnux** [comment]
This happens because the browser can not fetch the icons and thus uses the fallback alt text.

I still can not reproduce this with Firefox 129. Can you check your browser dev tools console if there are any issues?
This more seems like some issue with your browser, like a plugin that blocks some requests to the icons.

**Comment by JuganD** [comment]
Good point! Noticed something in the network tab. It seems that it is requesting all those missing resources towards `http`, instead of `https`.

My NC instance is running in a Docker container, using the `nextcloud:latest` image and it is behind a reverse proxy, which is handling the certificates and effectively making it `https`.
The reverse proxy is targeting the port 80 of the container, but actually port 80 is forbidden on the reverse proxy itself. Any request to it gets 308 and is redirected to the `https` version of the same URL.

Firefox:
![image](https://github.com/user-attachments/assets/bba7f6af-ce6c-459e-a440-bc82b6b26c02)

When I open the URL of any of those failed requests, it follows the 308 and successfully displays the image:
![image](https://github.com/user-attachments/assets/9e999289-747e-46c1-9b85-596cf61dce95)

I have this configuration in the `config.php` file:
```
'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => '<hostname>.<domainname>.com',
    2 => '<domainname>.com',
  ),
  'overwrite.cli.url' => 'https://<hostname>.<domainname>.com',
```

Chrome has no issue with this.. I'm not sure why, it could be that it follows the 308's during resource loading, not sure.
I don't understand why any requests would choose to go to `http`, is there a way to force all of them to go to `https` instead?
I was left with the impression that the `overwrite.cli.url` config is doing just that.

**Comment by susnux** [comment]
> I was left with the impression that the `overwrite.cli.url` config is doing just that.

No this is just for when you use `OCC` or when a cron job generates an URL.
For all other URLs it is not used.

Meaning you should properly pass the protocol to Nextcloud, e.g. with NGinx:

```
       fastcgi_param SERVER_NAME $server_name;
       fastcgi_param SERVER_PORT $server_port;
       fastcgi_param SERVER_PROTOCOL $server_protocol;
       fastcgi_param HTTPS on;
```

Also refer to the manual: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/reverse_proxy_configuration.html (e.g. `overwriteprotocol`).
For more configuration issues, please ask at [help.nextcloud.com](https://help.nextcloud.com/)
