### ISSUE TITLE
Update HSTS preloading recommendation in hardening section of the admin manual

### ISSUE THREAD

**Issue by lgarron** [nextcloud/server#4779]
An article on your site contains a recommended HSTS header value that includes `preload` in the only example: https://docs.nextcloud.com/server/9/admin_manual/configuration_server/harden_server.html

This is going to [shoot developers in the foot](https://crbug.com/527947), and also doesn't guarantee preloading unless someone submits the site to hstspreload.org separetely. See https://hstspreload.org/#opt-in (and https://github.com/chromium/hstspreload.org/issues/68)
Could you update your guide to remove it, or list two examples, the second of which explains preloading and links to hstspreload.org?

(I tried pinging at https://twitter.com/Nextclouders/status/805161033975398400 and emailing the contact address on your site, but that hasn't resulted in a response over the last 6 months.)

**Comment by MorrisJobke** [comment]
Ummm ... @LukasReschke didn't we talked about this yesterday?

@lgarron sorry for the unresponsiveness

**Comment by MorrisJobke** [comment]
@MariusBluem Do you want to update the documentation for this?

**Comment by MorrisJobke** [comment]
Fix is in https://github.com/nextcloud/documentation/pull/462
