### ISSUE TITLE
Mute notifications for individual shares

### ISSUE THREAD

**Issue by Solar-Simon** [nextcloud/server#47799]
**Is your feature request related to a problem? Please describe.**
I have notifications on for 'A file or folder shared by mail or by public link was downloaded'
In general I want it like that. But for some shares with bigger groups or lots of downloads its just to many notifications.

**Describe the solution you'd like**
When sharing, under "custom permissions" there could be a field "[ ] no notifications"

**Describe alternatives you've considered**
Maybe there is a way to cluster notifications

**Comment by joshtrichards** [comment]
Duplicate of #40930
