### ISSUE TITLE
Fatal error: Class 'RedisCluster' not found

### ISSUE THREAD

**Issue by chenzhizhuan** [nextcloud/server#4780]
Fatal error: Class 'RedisCluster' not found in /Applications/AMPPS/www/nextcloud-server/config/config.php on line 1081

Thanks

**Comment by MorrisJobke** [comment]
> Fatal error: Class 'RedisCluster' not found in /Applications/AMPPS/www/nextcloud-server/config/config.php on line 1081

Please install php redis module in version 2.2.8+ for PHP 5.6 or 3.0.0+ for PHP 7.0+
