### ISSUE TITLE
global addressbook

### ISSUE THREAD

**Issue by volker-raschek** [nextcloud/server#4781]
Hello, 
it's only a question and not an issue.

I use nextcloud 11.0.3 and I have in my share option a checkbox named 'Globale Suche und ein öffentliches Adressbuch für Benutzer' in german. 

What does it mean? What it this for a function and how can I benefit from this feature?

Volker

**Comment by MariusBluem** [comment]
Hi Volker,

The Lookup-Server can be used by Nextcloud to find remote users that can be used for federated sharing. This is useful for autocompletion in the sharing dialog to get the federation ID. Users can optionally decide to publish their sharing ID to be found by others. **Think about it as a kind of public sharing telephone book.**

In your personal settings you can set, which of your profile-data stay private, which will be available only for users on your own server, and which you want to publish on Nextcloud Lookup-Server (only possible if you have set the setting above).
