### ISSUE TITLE
"Start update" button not working when updating from NC 12 beta1 to beta2

### ISSUE THREAD

**Issue by LEDfan** [nextcloud/server#4782]
### Steps to reproduce
1. Run NC 12 beta 1
2. Get a notification for an update to beta 2
3. Open the updater
4. Click the "Start update" button

### Expected behaviour
The update process should start.

### Actual behaviour
Nothing happens, no errors in console, no HTTP requests etc

### Server configuration

**Operating system**: Centos 7.3

**Web server:** Apache 2.4.6

**Database:** Mariadb (Ver 15.1 Distrib 5.5.52-MariaDB)

**PHP version:** 7.1.3

**Nextcloud version:** Nextcloud 12 beta 1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from ownCloud 6 or something like that :smile:

**Where did you install Nextcloud from:** From the tarball

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.1
  - calendar: 1.5.2
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_downloadactivity: 1.1.1
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.4
  - news: 11.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.2.0
  - notifications: 2.0.0
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.0
  - twofactor_totp: 1.3.0
  - updatenotification: 1.2.0
  - user_external: 0.4
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - external
  - firstrunwizard
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oc971b311343434349a1",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xx.be"
        ],
        "datadirectory": "\/srv\/xxx.be\/data",
        "dbtype": "mysql",
        "version": "12.0.0.16",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "maxZipInputSize": 0,
        "allowZipDownload": true,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "app.mail.server-side-cache.enabled": true,
        "trashbin_retention_obligation": "auto",
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": {
            "0": "OC\\Preview\\PNG",
            "1": "OC\\Preview\\JPEG",
            "2": "OC\\Preview\\GIF",
            "11": "OC\\Preview\\Illustrator",
            "12": "OC\\Preview\\Postscript",
            "13": "OC\\Preview\\Photoshop",
            "14": "OC\\Preview\\TIFF"
        },
        "singleuser": false,
        "htaccess.RewriteBase": "\/",
        "overwrite.cli.url": "https:\/\/xxx.be",
        "appstore.experimental.enabled": true,
        "loglevel": 2,
        "updater.release.channel": "beta",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 52.1.0 and  Chrome 58.0.3029.96 

**Operating system:** openSUSE Leap 42.2

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Nothing related
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Nothing related
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
JQMIGRATE: Migrate is installed, version 1.4.0
```
</details>

Note that there seems to be no event listener on the button at all:
![selectie_636](https://cloud.githubusercontent.com/assets/2996275/25886702/20074a66-355f-11e7-8c4f-ae42dba14721.png)

I hope it's not a stupid error on my side :see_no_evil:

**Comment by fethomm** [comment]
I can confirm this, same behaviour. Worked fine from 11.0.3 to 12 b1. This is on Debian Testing, with any browser.

**Comment by rullzer** [comment]
It is caused by one of our security hardenings. @LukasReschke is already working on a fix.

**Comment by LukasReschke** [comment]
You can still update by opening `/updater/index.php` directly in your browser or use the CLI updater.

**Comment by fethomm** [comment]
That does not work for me, the secret is invalid. I used the one from config.php and created a new one. No dice :(

**Comment by LukasReschke** [comment]
You can also apply the patch from https://github.com/nextcloud/server/pull/4762/files which should make the updater accessible again via one-click button.

**Comment by chrissi55** [comment]
Can confirm the behaviour, that nor the Button neither the direct link "/updater/index.php" ist working since 12 beta 1.

I did the upgrade manually by copying the files to the webroot dir and used php occ commands ...

**Comment by ET-Bent** [comment]
Same issue from NC 12 beta 2 --> NC 12 beta 3

**Comment by MorrisJobke** [comment]
> Same issue from NC 12.0.0. beta 2 --> NC 12.0.0 beta 3

See https://github.com/nextcloud/server/issues/4504#issuecomment-301821770 for instructions.




> (Do I get a T-Shirt now? :P )

I guess not, because we noticed it seconds after the beta 2 release and also fixed it in the meantime, but this is up to @jospoortvliet. 😉

**Comment by ET-Bent** [comment]
@MorrisJobke Thanks for the fast reply. No worries I already saw that.

For me and potential future time travelers `sudo -u www-data php updater/updater.phar` did the trick.

The t-shirt thing was more a joke yet I would love to run around advertising Nextcloud on my body ;)

**Comment by MorrisJobke** [comment]
> For me and potential future time travelers sudo -u www-data php updater/updater.phar did the trick.

Or that 👍 That works as well.

**Comment by MorrisJobke** [comment]
> The t-shirt thing was more a joke yet I would love to run around advertising Nextcloud on my body ;)

@jospoortvliet  😉

**Comment by narcisgarcia** [comment]
I solved by adding this Content-Security-Policy parameter:
`script-src 'unsafe-inline'`
