### ISSUE TITLE
Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [nextcloud/server#47835]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing NextCloud application as shown [here](https://elest.io/open-source/nextcloud). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

**Comment by susnux** [comment]
(side note: You misspelled Nextcloud on your website, it is written "Nextcloud" not "NextCloud".)

**Comment by kaiwalyakoparkar** [comment]
Hey @susnux thanks for the information. We will get this updated asap :)
