### ISSUE TITLE
[Bug]: Refused to load the script 'https://onlyoffice-prod.xxxx.com/web-apps/apps/api/documents/api.js' because it violates the following Content Security Policy directive: "script-src-elem 'strict-dynamic' 'nonce-lo11xxxxx=' https://onlyoffice-prod.xxxx.com/". Note that 'strict-dynamic' is present, so host-based allowlisting is disabled.

### ISSUE THREAD

**Issue by ntuwang** [nextcloud/server#47885]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

when i try open excel, it show onlyoffice canot be reached
![image](https://github.com/user-attachments/assets/7ef3fcb9-505a-4f84-89dd-e9d0b7c5c9f5)

### Steps to reproduce

enable onlyoffice app

### Expected behavior

how to fix

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
Please report to OnlyOffice repo or at https://help.nextcloud.com as this is probably a setup issue. Thanks 👍

**Comment by daddy32** [comment]
I'm also experiencing this and can probably rule out configuration issue, as this stopped working without configuration being changed.

I think this may be a bug on a side of nextcloud, maybe caused by the change of "$strictDynamicAllowedOnScripts = true;" [1], as mentioned in issue 45127 [2]

[1] - https://github.com/nextcloud/server/commit/e231abd9bfac66e69db810c986792f9ba1a9d581
[2] - https://github.com/nextcloud/server/issues/45127
