### ISSUE TITLE
theming: black logo elements are transparent in favicon

### ISSUE THREAD

**Issue by violoncelloch** [nextcloud/server#4796]
### Steps to reproduce
1. create a logo with black elements
2. us theming in upload section to add the logo
3. wait until favicon is updated

### Expected behaviour
Black elements should stay black, transparent parts should be backgrounded with the theming color

### Actual behaviour
on the background color, only the border of the black element is black, inside is completly transparent

### Server configuration

**Operating system**: Debian Jessie

**Web server:** Apache

**Database:** MySQL 10

**PHP version:** 5.6

**Nextcloud version:** 11.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Comment by MorrisJobke** [comment]
cc @juliushaertl

**Comment by juliushaertl** [comment]
@jones4410 What filetype are you using? Can you post an example file that will fail?

**Comment by jones4410** [comment]
png...
just created an example file 
![testlogo](https://cloud.githubusercontent.com/assets/22591354/25960092/3376b164-3676-11e7-9d76-9b073696b3a0.png)
And a link to the original file: https://nc.violoncello.ch/s/cq3x0bX29XozKnU
hope this will help...
background (nextcloud colour) is a orange (#F06000)

**Comment by jones4410** [comment]
![touchicon-settings](https://cloud.githubusercontent.com/assets/22591354/25960446/3b85e6c6-3677-11e7-885b-db18dc4befd2.png)
this is the output

**Comment by juliushaertl** [comment]
@violoncelloch A fix is in https://github.com/nextcloud/server/pull/6457. Testing and review is very welcome.
