### ISSUE TITLE
Upgrade causes external storage folders to be deleted from sync clients

### ISSUE THREAD

**Issue by plinss** [nextcloud/server#4806]
### Steps to reproduce
1. Configure external storage folder for user (issue found with "local" external storage, didn't test with other types)
2. Sync files in external storage folder with client (tested with ownCloud client V2.3.1 and V2.3.2 on OSX)
3. Upgrade server (found on 11.0.1 -> 11.0.2 upgrade and 11.0.2 -> 11.0.3 upgrade)

### Expected behaviour
Synced data on client machine should remain consistent

### Actual behaviour
External folders are deleted from client machines and removed from sync immediately after upgrade.
Manually turning the external folders back on in the sync client causes the external folders to re-download.

Apparently the external folders are not available either during the upgrade or for a period of time after maintenance mode is turned back on.

### Server configuration
**Operating system**: Linux cloud 4.9.0-2-amd64 #1 SMP Debian 4.9.18-1 (2017-03-30) x86_64

**Web server:** nginx/1.13.0 (fpm-fcgi)

**Database:** mysql 10.1.22

**PHP version:** 7.0.16-3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 11.0.3 (stable) - 11.0.3.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgraded from ownCloud

**Where did you install Nextcloud from:** nextcloud.com

**List of activated apps:**
<details>
    <summary>App list</summary>

Enabled:
 - activity: 2.4.1
 - admin_audit: 1.1.0
 - audioplayer: 1.5.1
 - calendar: 1.5.2
 - comments: 1.1.0
 - contacts: 1.5.3
 - dav: 1.1.1
 - encryption: 1.4.1
 - federatedfilesharing: 1.1.1
 - federation: 1.1.1
 - files: 1.6.1
 - files_external: 1.1.2
 - files_markdown: 1.0.1
 - files_pdfviewer: 1.0.1
 - files_reader: 1.0.4
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - firstrunwizard: 2.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.6.4
 - nextcloud_announcements: 1.0
 - notes: 2.2.0
 - notifications: 1.0.1
 - password_policy: 1.1.0
 - provisioning_api: 1.1.0
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - spreed: 1.2.0
 - survey_client: 0.1.5
 - systemtags: 1.1.3
 - tasks: 0.9.5
 - templateeditor: 0.2
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - twofactor_totp: 1.1.0
 - updatenotification: 1.1.1
 - workflowengine: 1.1.1

Disabled:
 - documents
 - external
 - files_accesscontrol
 - files_automatedtagging
 - files_retention
 - music
 - user_external
 - user_ldap
 - user_saml
</details>

**The content of config/config.php:**
<details>
    <summary>Config report</summary>

```
{
    "instanceid": "ocd6tly2mdcn",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.*redacted*.com"
    ],
    "datadirectory": "\/var\/www\/data",
    "overwrite.cli.url": "https:\/\/cloud.*redacted*.com",
    "dbtype": "mysql",
    "version": "11.0.3.2",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "mail_from_address": "cloud",
    "mail_smtpmode": "php",
    "mail_domain": "cloud.*redacted*.com",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "session_lifetime": 86400,
    "maintenance": false,
    "appstore.experimental.enabled": true,
    "loglevel": 2,
    "theme": "",
    "trashbin_retention_obligation": "auto",
    "updatechecker": false,
    "htaccess.RewriteBase": "\/",
    "mysql.utf8mb4": true,
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** \OC\Files\Storage\Local

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:53.0) Gecko/20100101 Firefox/53.0

**Operating system:** macOS 10.12.4

**Comment by MorrisJobke** [comment]
cc @icewind1991 @rullzer

**Comment by rullzer** [comment]
I think this is fixed by @LukasReschke with some endpoints not properly having the maintenance mode
