### ISSUE TITLE
[Bug]: "Administration settings" and "Apps" are not shown on mobile devices

### ISSUE THREAD

**Issue by BJKle** [nextcloud/server#48117]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After updating my server to version 30.
When logging on with an admin account on a mobile device (iOS or iPadOS) the normal "user menu" is only available. Any "Administration settings" are not found.
The same user on a PC and it is working (all in the same network!).

### Steps to reproduce

1. logon to NC using an admin account
2. try to select "Administration settings"
3. Selection is limited

### Expected behavior

I can use all the admin 

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by BJKle** [comment]
![PC](https://github.com/user-attachments/assets/1317e570-51af-42ac-912c-73befc0e4eeb)

### **PC Version**


![mobile](https://github.com/user-attachments/assets/09d1b5d1-d0fc-49c1-bf87-a38c0b8b0848)

### **Mobile version**

**Comment by sorbaugh** [comment]
cc @Pytal maybe an easy fix?

**Comment by Pytal** [comment]
I cannot reproduce this

Does this repro after clearing cache and re-logging in @BJKle?

**Comment by BJKle** [comment]
I deleted all history. 
It‘ happens on all my devices. iPad or iPhone, both with ios/ipados 18.
When I connect to another NC with 29.0.3 as admin, it is working. It must be NC 30.

**Comment by BJKle** [comment]
Now it is gone on my Desktop PC as well.
Tried with different browsers.
Added an admin via occ-command
No admin menu items shown.
Please help.

**Comment by BJKle** [comment]
I figured it out. Id had to do with the update to iOS/iPadOS 18. The devices identified themselves with an "external" ip-address, wich is not in the allowed ip-range for admins.
Sorry for the trouble I may have caused.
