### ISSUE TITLE
ICEWIND issue error code 104 (unspecified error type)

### ISSUE THREAD

**Issue by ranch137** [nextcloud/server#4814]
Nextcloud version 11.0.3
Operating system and version Ubuntu 16.04 LTS and Debian 8.6
PHP version: Both 7.0 and 5.6
Is this the first time you've seen this error?: No

To reproduce:
Mount remote drive with hidden files on it (I have a NAS that has a ".DS_Store" file in the root directory)

Test:
Tested in both Debian and Ubuntu (16.04) with a fresh install of v11.0.3.  Connecting to a NAS via SMB.

Research:
Error is in the icewind/NativeState.php file... gives smbclient_state_errno = 104 which isn't specifically trapped (so drops to unknown error return) and causes the connection to fail. If I change to just return success for this error it all seems to work. Can this error be safely ignored.

Line 35 of NativeState.php collects the error. Trace is via smbclient_getxattrib request with the path for a hidden file.

What is Error Number 104 in ICEWIND and can it safely be ignored?

**Comment by rullzer** [comment]
@icewind1991 please have a look

**Comment by icewind1991** [comment]
`104` is `Connect reset` meaning that there is probably either a network issue or the smb server having issues

**Comment by ranch137** [comment]
@icewind1991 would it be safe to just ignore the error?  

The SMB server is an Apple Timecapsule serving up the SMB share and didn't have this issue in OC 9.1 prior to upgrading to NC 11.0.3.

**Comment by MorrisJobke** [comment]
Could you retry with 12.0.2+ because we improved the SMB handling there. If there are still issues we are happy to reopen this issue here. Thanks
