### ISSUE TITLE
BackgroundJob API is unusable

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/server#4818]
The public background job API is afaik used by specifying this in your info.xml

```xml
<background-jobs>
    <job>OCA\News\Cron\Updater</job>
</background-jobs>
```

Then the specified class has to implement this interface https://github.com/nextcloud/server/blob/master/lib/public/BackgroundJob/IJob.php

As you may have noticed the public interface is absolutely unusable, that's why there is https://github.com/nextcloud/server/blob/master/lib/private/BackgroundJob/Job.php

Anyone who wants to implement something using the cronjob API however has to duplicate your code because the class lives in the private namespace. Would it be possible to give us mortal app devs access to a saner interface which works with DI :D?

```php
interface IBackgroundJob {
    function run();
}
```

That can be used like this?

```php
class Updater implements OCP\BackgroundJob\IBackgroundJob {
    public function __construct(UpdateService $updater) {
        $this->updater = $updater;
    }

    public function run() {
        $this->updater->updateFeeds();
    }
}
```

@LukasReschke @MorrisJobke @ChristophWurst

**Comment by nickvergessen** [comment]
The current implementation has DI and it works quite nice.

As for cleaner interface, feel free to move the existing abstract jobs to the public api and thats it?

**Comment by BernhardPosselt** [comment]
Should be fine, why not simply create:

```php
namespace OCP\BackgroundJob;

abstract class BackgroundJob extends OC\BackgroundJob {}
```

Interfaces can be changed later then (if needed at all, it's probably too late to clean up this mess anyways)
