### ISSUE TITLE
[Bug]: Missing v30.0.0 Release set as Latest

### ISSUE THREAD

**Issue by calvin-li-developer** [nextcloud/server#48198]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hey,
It seems like the v30.0.0 tag is there but is not released for v30.0.0 on GitHub nextcloud/server repo page.

This is similar to https://github.com/nextcloud/server/issues/39845

### Steps to reproduce

see description and https://github.com/nextcloud/server/issues/39845 and https://github.com/nextcloud/server/issues/41172

and https://github.com/nextcloud/server/issues/42462

### Expected behavior

One of the following:
Releases on Github repo as new versions get tagged

### Nextcloud Server version

30

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by regs01** [comment]
Isn't it's just not released yet?

**Comment by calvin-li-developer** [comment]
> Isn't it's just not released yet?

It is released 5 days ago. 

See release link:
https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by joshtrichards** [comment]
Cc: @Altahrim

**Comment by tiredofit** [comment]
The tag has been created just not the release. This is causing confusion among version update checkers and other automated systems.

**Comment by joshtrichards** [comment]
https://github.com/nextcloud/server/releases/tag/v30.0.0
