### ISSUE TITLE
upgrade from 11.03 to 12.0B2 Dutch language and share days field is to small

### ISSUE THREAD

**Issue by JK74** [nextcloud/server#4819]
I just upgraded from 11.03 to 12.0B2 without problems using the web updater. it was finished in a few mintues. My system is all set to Dutch language/localization.

I noticed that the date field for expired days on the share is so small that its not readable any longer. see screenshot. I tested this against IE/FF/Chr.

just cosmetic defect to my thinking.
![share_days_invisible](https://cloud.githubusercontent.com/assets/17946255/25972201/51e4cc5c-369f-11e7-8b67-63c4d318ae93.PNG)

**Comment by MorrisJobke** [comment]
Fix is in #4822
