### ISSUE TITLE
PostgreSQL: faulty database connection upon completing installation wizard

### ISSUE THREAD

**Issue by pmattern** [nextcloud/server#482]
Using PostgreSQL the first database connection upon completing the installation wizard ("Finish setup") is faulty both in current master checkouts and 9.0.53.

Both 020a2a6 and 9.0.53 first try to connect to database "postgres" instead of their dedicated one according to the PostgreSQL server's logs. As for the Git checkout this results in failure and a warning
![nextcloud_postgres-installation-credentials_020a2a6](https://cloud.githubusercontent.com/assets/9860801/17004196/3ab63984-4ed4-11e6-879b-7c463bb20a0d.png)
In 9.0.5{3,2} the installation wizard of which [still needs the vendor specific "psql" driver](https://github.com/nextcloud/server/issues/367) an attempt to connect to database "postgres" is made as well but it's followed by some other connection attempt and the resulting warning is
![nextcloud_postgres-installation-credentials_9 0 52](https://cloud.githubusercontent.com/assets/9860801/17004204/43f7c35a-4ed4-11e6-90d9-b9cc6aa7c224.png)
Unlike the findings with branch master this isn't reproducible 100% but happens most of the time, so far I failed to figure out the exact conditions.
Both times `config.php` is written but incomplete, in particular `dbpassword` and `installed` are missing. The correct dedicated database of Nextcloud is filed in `dbname`, though. 

Arch Linux x86_64, hence PostgreSQL 9.5.3, PHP 7.0.8 and Apache 2.4.23 using the PHP module. Database server on an other host than the one running Apache / Nextcloud, credentials definitely valid as verified by invoking `psql` from the latter.

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by bauna** [comment]
I'm experiencing the same issue deploying on a virtual machine on Amazon EC2. I can login to Postgresql instance from the same vm and create tables, but nextcloud installer(from web and command line) says that credentials are not valid. On command line I tried with option "-vvv" to get more info but I got the same message. The installation with mysql works as expected.
 
These the versions on my VM:
Ubuntu 14.04
PHP 5.5.9-1ubuntu4.19
Nextcloud version 9.0.53
Apache 2.4.7-1ubuntu4.13
PosrgreSQL 9.5.2

Thanks!

**Comment by ramondg** [comment]
+1

**Comment by MorrisJobke** [comment]
> +1

@ramondg Could you test the changes in #497? Thanks :)

**Comment by pmattern** [comment]
There seems to be a small remnant.

Right upon clicking the wizard's `Finish setup` button there's still the error message
> FATAL:  no pg_hba.conf entry for host "fd99:aaaa:bbbb:2:5054:ff:fe12:213", user "u_nextcloud1", database "postgres", SSL off

in the PostgreSQL server's log, where the database name is wrong but the other credentials are correct.
Error messages other than this don't seem to exist, even when `log_min_messages = debug5` is set in `postgresql.conf`, and I couldn't see any problem corresponding with the message running the wizard or Nextcloud itself either.
So not sure about the impact.

Arch Linux x64-64, Apache 2.4.25, PHP 7.1.1, PostgreSQL 9.6.1, Nextcloud b5990b7.

**Comment by go2sh** [comment]
This is a postgres error unrelated to nextcloud. You use a ip address to connect to postgres which is not allowed in  the `pg_hba.conf` file. Usually only local host is allowed to connect.
See https://www.postgresql.org/docs/9.6/static/auth-pg-hba-conf.html for more information about the correct configuration.

**Comment by pmattern** [comment]
> This is a postgres error unrelated to nextcloud. [...]

The finding has exactly nothing to do with `pg_hba.conf` which is configured properly. How else should everything except the error message work fine?
Rather, as written in my previous post as well, the point is the wrong database name "postgres" that Nextcloud is using for whatever reason.

**Comment by go2sh** [comment]
@pmattern 
Yes, but that is no real error. You can safely ignore that error. I took a look at the code and nextcloud connects to the postgres database to check whether it has access to it, to check for the db user, and to create it eventually. See:
https://github.com/nextcloud/server/blob/master/lib/private/Setup/PostgreSQL.php
