### ISSUE TITLE
[Bug]:  Misiing Nectcloud.oc_jobs

### ISSUE THREAD

**Issue by canx35** [nextcloud/server#48243]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After the update i became a error. The oc_jobs is missing and i cant fix it

Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: All tables already have the correct collation -> nothing to do

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Exception: Database error when running migration 28000Date20240828142927 for app core There is no table with name "nextcloud.oc_jobs" in the schema.

or in terminal:

Exception: Database error when running migration 28000Date20240828142927 for app core
There is no table with name "nextcloud.oc_jobs" in the schema.
Update failed

### Steps to reproduce

1.in terminal occ upgrade 
2.or i update the OAuth 2.0 (oauth2) app and the error came 

### Expected behavior

i dont know

### Nextcloud Server version

29

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
> After the update i became a error. The oc_jobs is missing and i cant fix it

Please post on the help forum for technical support: https://help.nextcloud.com
