### ISSUE TITLE
[Bug]: Creating a new document doesn't do anything / Content-Security-Policy violation

### ISSUE THREAD

**Issue by micah** [nextcloud/server#48250]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

If I click the "+ New" button and then in the drop-down select document, I get a box that pops up that asks me for a name:

![screenshot-2024-09-20-174051](https://github.com/user-attachments/assets/dedabd46-9d6c-47b3-8b3c-2b0e2ec9a8cd)

I enter a name, click Create. The box closes, and nothing happens. No new document is created.

This happens with every type of document that I can pick in that drop-down. I can create a new folder without a problem.

This problem happened after upgrading to Nextcloud 30.

### Steps to reproduce

1. Click "+ New"
2. Pick document type
3. Put a name in the modal
4. Click Create

Nothing happens.

### Expected behavior

A new document should be created.

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "enable_previews": true,
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "filesystem_check_changes": 0,
        "activity_expire_days": 14,
        "knowledgebaseenabled": false,
        "auth.bruteforce.protection.enabled": true,
        "default_phone_region": "US",
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "cron_log": true,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\***REMOVED SENSITIVE VALUE***/\/nextcloud",
        "htaccess.RewriteBase": "\/nextcloud",
        "dbtype": "mysql",
        "mail_smtpdebug": true,
        "version": "30.0.0.14",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "timeout": 1.5
        },
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "theme": "",
        "trashbin_retention_obligation": "auto, 7",
        "updater.release.channel": "stable",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "encryption.legacy_format_support": false,
        "encryption.key_storage_migrated": false,
        "app_install_overwrite": [
            "onlyoffice"
        ],
        "maintenance": false,
        "config_is_read_only": true
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 3.0.0
  - admin_audit: 1.20.0
  - calendar: 5.0.0
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contacts: 6.1.0
  - contactsinteraction: 1.11.0
  - cospend: 2.0.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - encryption: 2.18.0
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - nextcloud_announcements: 2.0.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - onlyoffice: 9.3.0
  - password_policy: 2.0.0
  - photos: 3.0.2
  - polls: 7.2.3
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - support: 2.0.0
  - survey_client: 2.0.0
  - systemtags: 1.20.0
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - twofactor_totp: 12.0.0-dev
  - updatenotification: 1.20.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - bruteforcesettings: 3.0.0 (installed 2.4.0)
  - circles: 30.0.0-dev (installed 0.21.4)
  - files_external: 1.22.0
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - impersonate: 1.17.0 (installed 1.17.0)
  - suspicious_login: 8.0.0
  - tasks: 0.16.1 (installed 0.16.1)
  - twofactor_nextcloud_notification: 4.0.0
  - twofactor_u2f: 6.3.1 (installed 6.3.0)
  - twofactor_yubikey: 0.4.1 (installed 0.4.1)
  - user_ldap: 1.21.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
I see nothing added to the logs when I perform this action
```

**Comment by joshtrichards** [comment]
> I enter a name, click Create. The box closes, and nothing happens. No new document is created.

I can't reproduce this. 

Please check your browser inspector while trying to reproduce this behavior. Specifically check the *Network* tab for failed transactions. Also check the *Console* tab for other indications of what may be going on.

To keep things simple, test with *New text file*. After entering the name you are supposed to get prompted for the template.

I would also suggest checking *Admin settings->Overview* for any warnings or errors.

**Comment by micah** [comment]
Thanks for the response. I've just done as you asked, and I can see the following show up:

```
Uncaught (in promise) TypeError: this.$refs.picker is undefined
    open newFromTemplate.ts:27
    handler newFromTemplate.ts:58
    onClick index-DNLyAvkP.mjs:1157
    click index-DNLyAvkP.mjs:1353
    VueJS 4
    onClick actionText-fFcUPi2g.mjs:77
    handleClick NcActionButton.mjs:131
    VueJS 33
```

I also see that dist/3235-3235.js?v=62df9e6af427989f039f failed to load due to CSP, and a few others as well:

Content-Security-Policy: The page’s settings blocked a script (script-src-elem) at apps/related_resources/js/vendors-node_modules_nextcloud_vue_dist_Components_NcRelatedResourcesPanel_mjs.related_resources.js from being executed because it violates the following directive: “script-src 'nonce-***removed possible sensitive content***='”

When I do a `curl -I` on the server to get the headers, I see it has: `content-security-policy: default-src 'self'; script-src 'self' 'nonce-gu09IiuLpJ9vqrETX4qdpdCtS8YL8YGFxyUcOhXcdQ4='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';`

I'm not setting CSP in the nginx configuration.

**Comment by joshtrichards** [comment]
What is the `Content-Security-Policy` header when you're logged in (on initial the *Files* page)? You can see it by checking the first `GET` transaction that comes up under the *Network* tab in the browser inspect under the *Headers* / Responses Headers.

**Comment by micah** [comment]
It appears to be:

```
content-security-policy
	default-src 'none';base-uri 'none';manifest-src
        'self';script-src
        'nonce-7L30ujCL8e9tKVsYl3XblNfvmbnMNWkwaNn5QDenfQg=';style-src
        'self' 'unsafe-inline';img-src 'self' data: blob:
        https://*.tile.openstreetmap.org;font-src 'self'
        data:;connect-src 'self';media-src 'self';frame-src
        'self';frame-ancestors 'self';worker-src 'self';form-action
        'self'
```

**Comment by joshtrichards** [comment]
Please look closer at your *Networks* tab to see if there are a mixture of http and https transactions or similar being blocked.

Are you always accessing your instance via the same URL?

Are you accessing your instance via https:// or http://? (your config suggests an `http://` is in use sometimes).

I suspect this is a config matter that may need to be troubleshooted via the help forum: https://help.nextcloud.com

**Comment by micah** [comment]
On 2024-09-22 09:33:54, Josh wrote:
> Please look closer at your *Networks* tab to see if there are a mixture of http and https transactions or similar being blocked.

I looked at every transaction in the Networks tab after the files area
has been loaded, and when I've attempted to create a file. Every single
one of them has "Scheme: https"

> Are you always accessing your instance via the same URL?

Yes, I am.

> Are you accessing your instance via https:// or http://? (your config suggests an `http://` is in use sometimes).

https:// only

In fact, I have Firefox HTTPS-only mode enabled.

> I suspect this is a config matter that may need to be troubleshooted via the help forum: https://help.nextcloud.com

That may be true, but this configuration has not changed for many
nextcloud versions, and this only broke when I updated to 30, so
something changed in 30.

**Comment by joshtrichards** [comment]
It's possible it's being triggered by OnlyOffice. There is a newer version (9.4.0) out that specifically has a CSP hotfix in it and is supposedly compatible with Nc v30 (see ONLYOFFICE/onlyoffice-nextcloud#1020). The version you have installed is 9.3.0 which was not released for Nc v30. It looks like you have it force enabled based on `app_install_overwrite`.


Given the place where you're seeing this error, it's possible it's related.

**Comment by micah** [comment]
On 2024-09-22 14:34:18, Josh wrote:
> It's possible it's being triggered by OnlyOffice. There is a newer version (9.4.0) out that specifically has a CSP hotfix in it and is supposedly compatible with Nc v30 (see ONLYOFFICE/onlyoffice-nextcloud#1020). The version you have installed is 9.3.0 which was not released for Nc v30. It looks like you have it force enabled based on `app_install_overwrite`.
>
>
> Given the place where you're seeing this error, it's possible it's related.

That does indeed appear to be the problem! I've updated the OnlyOffice
plugin and now the issue is no more.

Thank you for your help. I'll close this issue.

**Comment by joshtrichards** [comment]
Glad to hear it!
