### ISSUE TITLE
App description not available for local apps

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#4827]
@eppfel This was introduced with #3195

@nextcloud/designers Any idea how to bring this back? Currently there is only the app name and the version.

**Comment by MorrisJobke** [comment]
Possible solutions:

* Detail pages for apps #3193
* Show app details in apps management via right sidebar #2138

**Comment by eppfel** [comment]
Yes, this was intentional to force development on one of these two solutions...
So far it seems #2138 is preferred. And as the grid layout still has the description, this would be a perfect reason to start. No promises though 😆

**Comment by MorrisJobke** [comment]
> Yes, this was intentional to force development on one of these two solutions...

Okay ... this failed, because we are shortly before the RC 🙈

**Comment by jancborchardt** [comment]
Ok, I closed the »detail page« issue in favor of the more specific #app-sidebar solution where we can reuse components. https://github.com/nextcloud/server/issues/2138

As it is so close to RC/Release we could develop a simple solution with the sidebar to make it as backportable as possible. Would that work @MorrisJobke @karlitschek?

To do:

- [ ] Include #app-sidebar element in the apps management – only needed on the local apps categories for now
- [ ] Make it show on click of the app row (except enable/disable button of course)
- [ ] Close on click of the top right close button (just like in Files)
- [ ] Use same layout as Files app / App management view of the remote apps: with icon/screenshot on top, name below, and all info like description directly below that. No expanding/collapsing needed here, the view can scroll.

What do you think?

**Comment by MorrisJobke** [comment]
> As it is so close to RC/Release we could develop a simple solution with the sidebar to make it as backportable as possible. Would that work @MorrisJobke @karlitschek?

Too late -> moved to 13 and then we can think about what we backport.

**Comment by jancborchardt** [comment]
So what do you think about the proposal above?

**Comment by eppfel** [comment]
I support the proposal. I would have done it no other way, but I have no time to focus on implementing something like this util June.

**Comment by nickvergessen** [comment]
@jancborchardt do you have a short term proposal to bring back the app descriptions in 12?
We can't backport a new sidebar and should maybe fix this in 12.0.1

Really helps new users if they can read in short descriptions what the shipped apps do.

**Comment by nickvergessen** [comment]
Nextcloud 13: I'm all for the sidebar, sounds good and makes sense.

**Comment by jancborchardt** [comment]
Short term could be to put the descriptions below the app name. That will make the list quite crowded again though. We could put a triangle-down icon next to each title and when clicked, the description will reveal below it.

What do you think?

**Comment by nickvergessen** [comment]
>  We could put a triangle-down icon next to each title and when clicked, the description will reveal below it.

Sounds good 👍

**Comment by MorrisJobke** [comment]
As 13 is close to the release I will move this again - 14 it is now 🙈

**Comment by eppfel** [comment]
I question the relevance of this...
Are there users complaining?

**Comment by MorrisJobke** [comment]
> Show app details in apps management via right sidebar #2138

Let's close this ticket in favour of #2138
