### ISSUE TITLE
"An unknown error has occurred" UPLOAD NEXTCLOUD FILES

### ISSUE THREAD

**Issue by teyek** [nextcloud/server#48276]
Someone please help!!!!
i tried to upload files but this error pop-up

here some logs

[no app in context] Error: Sabre\DAV\Exception\BadRequest: Expected filesize of 113311744 bytes but read (from Nextcloud client) and wrote (to Nextcloud storage) 92278736 bytes. Could either be a network problem on the sending side or a problem writing to the storage on the server side. at <<closure>>

0. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 151
   OCA\DAV\Connector\Sabre\File->put()
1. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1098
   OCA\DAV\Connector\Sabre\Directory->createFile()
2. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 504
   Sabre\DAV\Server->createFile()
3. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
   Sabre\DAV\CorePlugin->httpPut()
4. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 472
   Sabre\DAV\Server->emit()
5. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 253
   Sabre\DAV\Server->invokeMethod()
6. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 321
   Sabre\DAV\Server->start()
7. /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php line 85
   Sabre\DAV\Server->exec()
8. /var/www/nextcloud/remote.php line 172
   require_once("/var/www/nextcl ... p")
   
   * I tried
   
   upload_max_filesize = 500G
   post_max_size = 500G
   
   Set LimitRequestBody:

apache

<Directory /var/www/nextcloud/>
    ...
    LimitRequestBody 536870912000  # 500 GB in bytes
    ...
</Directory>

**Comment by solracsf** [comment]
Please ask for help with your setup at https://help.nextcloud.com Thanks 👍
