### ISSUE TITLE
(Dutch) language issue: 'updated' should be 'update' (infinitive)

### ISSUE THREAD

**Issue by keunes** [nextcloud/server#4833]
When a new app has an update available, in the appstore in Nextcloud it says 'bijgewerkt' (= 'updated') where it should say 'bijwerken' (= 'update'). In Transifex, however, there doesn't seem to be a string for that.

So I have the feeling a new string should be added in the appstore, 'update', which is displayed if there's a new update available and you can click on the button to start the process. After that's done, it should/could say 'updated'.
### Server configuration
**Nextcloud version:** 11.0.3 (stable)
**Updated from an older Nextcloud/ownCloud or fresh install:** fresh upon
**Where did you install Nextcloud from:** website zip

[Should've made a screenshot, but forgot. Will do next time if still needed then.]

**Comment by MorrisJobke** [comment]
I guess this was fixed in transifex in the meantime. Please report if this is also the case for 11.0.4.

Thanks
