### ISSUE TITLE
Files contributor week brainstorm ideas

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/server#48346]
- [ ] 1. ✔️✔️✔️✔️✔️  Real search (not filtering)  
- [ ] 2. ✔️✔️ New button not prominent enough  
- [ ] 3. ✔️✔️ Click to select and not click to enter (Not brought up by Marco, not voted by Marco 😉 )  
- [ ] 4. ✔️ pdf editing features: creating, merging, splitting, filling, save a copy, etc.  
- [ ] 5. ✔️ Favourites are not that easy to see  
- [ ] 6. ✔️ Duplicate detection  
- [ ] 7. ✔️ Recommended files as landing page with really meaningful recommendations  
- [ ] 8. ✔️ Allow moving files with flows  
- [ ] 9. ✔️ Translation of files like Deepl (creates a new translated file)  
- [ ] 10. ✔️ Good backup strategy built into Nextcloud  
- [ ] 11. ✔️ Size of thumbnail adjustment in web client  
- [ ] 12. ✔️ My files always on top (recent , favourites). Now to many clicks to get to what I need.  
- [ ] 13. Native handling in files explorer, ctrl-c ctrl-x ctrl-v  
- [ ] 14. Rich workspaces are not useful to me, I’d rather not have them  
- [x] 15. Camera scanner for mobile clients, to scan documents and convert to pdf, etc ✅ feature already exists
- [ ] 16. Input a date and find a file from that date (especially photos)  
- [ ] 17. Better support for non latin characters (currently sync errors can happen with Turkish chars for example, some African language also affected)  
- [ ] 18. photo backup for mobile client like one drive (automatic without having to configure syncs)  
- [ ] 19. “Cleaning” functionality, flag things that are not in use  
- [ ] 20. Reliable large operations (copy, move, etc)  
- [ ] 21. File size not discoverable  
- [ ] 22. OCC command to se which files are not shared with someone else  
- [ ] 23. Desktop client: allow to deselect files in the root folder so they don’t get synced  
- [ ] 24. It’s weird and confusing that there’s 2 versions of the desktop client

FYI @jancborchardt  @nimishavijay @sorbaugh

**Comment by marcoambrosini** [comment]
@sorbaugh could you please work with your team to link existing issues to each item and or create new ones if you think it's needed?

**Comment by jancborchardt** [comment]
Closed as duplicate of https://github.com/nextcloud/server/issues/48396
