### ISSUE TITLE
[Minor, Idea] Change default Nextcloud Folder for multi-user clients

### ISSUE THREAD

**Issue by FelixOliverLange** [nextcloud/server#4834]
Hi there,
yesterday we encountered a minor issue with one of our clients: The user had added two accounts on his device, but not changed the default folder during the Setup. The result was that both users where linked to C:\Users\<Username>\Nextcloud\ 
Therefor data was duplicated into both users, sending the data of the users private user to a shared user of a group (yes, that was as bad as it sounds).
This is not hard to resolve, but very, very bad UX with potential data leakage. Possibly it would be better to let the Nextcloud defualt folder be 
C:\Users\<Username>\Nextcloud\<Nextcloud-Username>\
For each User. Doing so would allow multi-users to not care about changing standard paths, and enhance UX. 
Kind regards,
Felix

**Comment by bpcurse** [comment]
Good point. Sounds like a simple and effective solution to me.

**Comment by MorrisJobke** [comment]
As we use basically the ownCloud client with some branding on top I would recommend to place this in the upstream issue tracker. It is also not bound to Nextcloud or ownCloud and a good fit there: https://github.com/owncloud/client/issues

Thanks
