### ISSUE TITLE
[Bug]:  IPv6 and Federated Shares not working

### ISSUE THREAD

**Issue by AlexKid007** [nextcloud/server#48360]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

As the old bug ticket is closed but federation share with IPv6 only servers is still not working I open a new one as mentioned in [
IPv6 support for Federated Shares](https://github.com/nextcloud/server/issues/30757)

### Steps to reproduce

1. add trusted IPv4 server on IPv6 only server --> server is listed 
2. add trusted IPv6 only server on IPv4 server --> no server to federate with found
3. add trusted IPv6 only server on IPv6 only server --> no server to federate with found

### Expected behavior

all servers are listed after adding

### Nextcloud Server version

29.0.6

### Operating system

Debian/Ubuntu --> Docker | image: nextcloud:apache

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB 10.6

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```shell
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.alexkid.duckdns.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.6.1",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/nextcloud.alexkid.duckdns.org",
        "overwritehost": "nextcloud.alexkid.duckdns.org",
        "overwriteprotocol": "https",
        "allow_local_remote_servers": true,
        "maintenance_window_start": 1,
        "default_phone_region": "DE",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "backup",
            "duplicatefinder",
            "keeweb",
            "hsts"
        ],
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "memories.exiftool": "\/var\/www\/html\/custom_apps\/memories\/bin-ext\/exiftool-amd64-glibc",
        "memories.vod.path": "\/var\/www\/html\/custom_apps\/memories\/bin-ext\/go-vod-amd64",
        "memories.exiftool_no_local": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image"
        ],
        "memories.gis_type": 1,
        "upgrade.disable-web": true
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 2.21.1
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contacts: 6.0.0
  - contactsinteraction: 1.10.0
  - dashboard: 7.9.0
  - dav: 1.30.1
  - deck: 1.13.2
  - duplicatefinder: 1.2.5
  - federatedfilesharing: 1.19.0
  - federation: 1.19.0
  - files: 2.1.1
  - files_downloadlimit: 2.0.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - firstrunwizard: 2.18.0
  - hsts: 0.9.0
  - keeweb: 0.6.20
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - memories: 7.4.1
  - nextcloud_announcements: 1.18.0
  - notes: 4.11.0
  - notifications: 2.17.0
  - oauth2: 1.17.0
  - password_policy: 1.19.0
  - photos: 2.5.0
  - previewgenerator: 5.6.0
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recognize: 7.1.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharebymail: 1.19.0
  - support: 1.12.0
  - survey_client: 1.17.0
  - systemtags: 1.19.0
  - text: 3.10.1
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - updatenotification: 1.19.1
  - user_status: 1.9.0
  - viewer: 2.3.0
  - weather_status: 1.9.0
  - workflowengine: 2.11.0
Disabled:
  - admin_audit: 1.19.0
  - bruteforcesettings: 2.9.0
  - circles: 29.0.0-dev (installed 29.0.0-dev)
  - encryption: 2.17.0
  - files_external: 1.21.0
  - files_pdfviewer: 2.10.0 (installed 2.10.0)
  - suspicious_login: 7.0.0
  - twofactor_totp: 11.0.0-dev
  - user_ldap: 1.20.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```shell
Fehler | federation | HintException | No server to federate with found
```

**Comment by joshtrichards** [comment]
Do you have the full log entry (stack trace)?

**Comment by AlexKid007** [comment]
`{"reqId":"nD2AwMyU9wpolFTXBWpR","level":3,"time":"2024-09-26T05:15:35+00:00","remoteAddr":"172.18.0.1","user":"AlexKid","app":"federation","method":"POST","url":"/index.php/apps/federation/trusted-servers","message":"No Nextcloud server.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36","version":"29.0.6.1","exception":{"Exception":"GuzzleHttp\\Exception\\ConnectException","Message":"cURL error 7: Failed to connect to alexkid3.duckdns.org port 443 after 5 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://alexkid3.duckdns.org//status.php","Code":0,"Trace":[{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","line":158,"function":"createRejection","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","line":110,"function":"finishError","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::","args":[["GuzzleHttp\\Handler\\CurlHandler"],"*** sensitive parameters replaced ***",["GuzzleHttp\\Handler\\CurlFactory"]]},{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php","line":47,"function":"finish","class":"GuzzleHttp\\Handler\\CurlFactory","type":"::","args":[["GuzzleHttp\\Handler\\CurlHandler"],"*** sensitive parameters replaced ***",["GuzzleHttp\\Handler\\CurlFactory"]]},{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":142,"function":"__invoke","class":"GuzzleHttp\\Handler\\CurlHandler","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/Http/Client/DnsPinMiddleware.php","line":123,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php","line":35,"function":"OC\\Http\\Client\\{closure}","class":"OC\\Http\\Client\\DnsPinMiddleware","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":31,"function":"__invoke","class":"GuzzleHttp\\PrepareBodyMiddleware","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php","line":71,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php","line":66,"function":"__invoke","class":"GuzzleHttp\\RedirectMiddleware","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/HandlerStack.php","line":75,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php","line":333,"function":"__invoke","class":"GuzzleHttp\\HandlerStack","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php","line":169,"function":"transfer","class":"GuzzleHttp\\Client","type":"->","args":["*** sensitive parameters replaced ***","*** sensitive parameters replaced ***"]},{"file":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php","line":189,"function":"requestAsync","class":"GuzzleHttp\\Client","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/Http/Client/Client.php","line":230,"function":"request","class":"GuzzleHttp\\Client","type":"->","args":["*** sensitive parameters replaced ***","https://alexkid3.duckdns.org//status.php",["/var/www/html/resources/config/ca-bundle.crt",3,3,[true],["Nextcloud Server Crawler","gzip"],"And 1 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/html/apps/federation/lib/TrustedServers.php","line":173,"function":"get","class":"OC\\Http\\Client\\Client","type":"->","args":["https://alexkid3.duckdns.org//status.php",[3,3]]},{"file":"/var/www/html/apps/federation/lib/Controller/SettingsController.php","line":88,"function":"isNextcloudServer","class":"OCA\\Federation\\TrustedServers","type":"->","args":["https://alexkid3.duckdns.org/"]},{"file":"/var/www/html/apps/federation/lib/Controller/SettingsController.php","line":55,"function":"checkServer","class":"OCA\\Federation\\Controller\\SettingsController","type":"->","args":["https://alexkid3.duckdns.org/"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"addServer","class":"OCA\\Federation\\Controller\\SettingsController","type":"->","args":["https://alexkid3.duckdns.org/"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Federation\\Controller\\SettingsController"],"addServer"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Federation\\Controller\\SettingsController"],"addServer"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":331,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Federation\\Controller\\SettingsController","addServer",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["federation.settings.addserver"]]},{"file":"/var/www/html/lib/base.php","line":1058,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/federation/trusted-servers"]},{"file":"/var/www/html/index.php","line":49,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php","Line":210,"message":"No Nextcloud server.","exception":{},"CustomMessage":"No Nextcloud server."}}
{"reqId":"nD2AwMyU9wpolFTXBWpR","level":3,"time":"2024-09-26T05:15:35+00:00","remoteAddr":"172.18.0.1","user":"AlexKid","app":"federation","method":"POST","url":"/index.php/apps/federation/trusted-servers","message":"No server to federate with found","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36","version":"29.0.6.1","exception":{"Exception":"OCP\\HintException","Message":"No server to federate with found","Code":0,"Trace":[{"file":"/var/www/html/apps/federation/lib/Controller/SettingsController.php","line":55,"function":"checkServer","class":"OCA\\Federation\\Controller\\SettingsController","type":"->","args":["https://alexkid3.duckdns.org/"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":232,"function":"addServer","class":"OCA\\Federation\\Controller\\SettingsController","type":"->","args":["https://alexkid3.duckdns.org/"]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":138,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Federation\\Controller\\SettingsController"],"addServer"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":184,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[["OCA\\Federation\\Controller\\SettingsController"],"addServer"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":331,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Federation\\Controller\\SettingsController","addServer",["OC\\AppFramework\\DependencyInjection\\DIContainer"],["federation.settings.addserver"]]},{"file":"/var/www/html/lib/base.php","line":1058,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/federation/trusted-servers"]},{"file":"/var/www/html/index.php","line":49,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/apps/federation/lib/Controller/SettingsController.php","Line":91,"Hint":"Es wurde kein Server zum Verbinden per Federation gefunden","message":"No server to federate with found","exception":{},"CustomMessage":"No server to federate with found"}}`

**Comment by joshtrichards** [comment]
```
   "Exception": "GuzzleHttp\\Exception\\ConnectException",
    "Message": "cURL error 7: Failed to connect to alexkid3.duckdns.org port 443 after 5 ms: Couldn't connect to server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://alexkid3.duckdns.org//status.php",
```
I'm not sure what that prior linked report was (since it doesn't look like it was resolved within the Issue itself unfortunately), but this looks different. On the surface this appears to just be a standard connectivity matter (between the app container that generated that log and the remote host `https://alexkid3.duckdns.org`.

It's failing nearly immediately. We don't do anything special curl-wise that should interact with IPv6.

Can you try the following from *within* Nextcloud app container?

The output of any of the following should be informative (mostly just interested in the first ~6 lines or so):
 
`curl -v -I https://alexkid3.duckdns.org`

Or, even better, force v6 + full target URL:

`curl -6 -v -I https://alexkid3.duckdns.org/status.php`

Might also be worth checking:

`curl -v -I https://cloud.nextcloud.com`
`curl -6 -v -I https://cloud.nextcloud.com`

If all of the above **succeed** (via IPv6) from the container: If there is a bug, I'd expect it to be in the DNS Pinning maybe so you can try (only temporarily!) disabling it in your `config.php` by setting `dns_pinning` to `false` (+either giving it ~60s for the config change to get picked up or restarting the app container) then re-testing the federation transaction.

**Comment by AlexKid007** [comment]
`curl -v -I https://alexkid3.duckdns.org
*   Trying [2a00:6020:49bd:9e00:7a17:fa70:3f6c:89b1]:443...
* Immediate connect fail for 2a00:6020:49bd:9e00:7a17:fa70:3f6c:89b1: Network is unreachable
* Failed to connect to alexkid3.duckdns.org port 443 after 5 ms: Couldn't connect to server
* Closing connection 0
curl: (7) Failed to connect to alexkid3.duckdns.org port 443 after 5 ms: Couldn't connect to server`

`curl -6 -v -I https://alexkid3.duckdns.org/status.php
* Could not resolve host: alexkid3.duckdns.org
* Closing connection 0
curl: (6) Could not resolve host: alexkid3.duckdns.org`

`curl -v -I https://cloud.nextcloud.com
*   Trying 116.202.53.135:443...
* Connected to cloud.nextcloud.com (116.202.53.135) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=cloud.nextcloud.com
*  start date: Sep 26 08:03:28 2024 GMT
*  expire date: Dec 25 08:03:27 2024 GMT
*  subjectAltName: host "cloud.nextcloud.com" matched cert's "cloud.nextcloud.com"
*  issuer: C=US; O=Let's Encrypt; CN=E6
*  SSL certificate verify ok.
* using HTTP/2
* h2h3 [:method: HEAD]
* h2h3 [:path: /]
* h2h3 [:scheme: https]
* h2h3 [:authority: cloud.nextcloud.com]
* h2h3 [user-agent: curl/7.88.1]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x556ab8dc6ce0)
> HEAD / HTTP/2
> Host: cloud.nextcloud.com
> user-agent: curl/7.88.1
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/2 302
HTTP/2 302
< content-security-policy: default-src 'self'; script-src 'self' 'nonce-7iA7Yun3Yt5nW7q/AJvKv7zqgMeMwK+oqqK05XdqzO8='; style-src '                                     self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; b                                     ase-uri 'self';
content-security-policy: default-src 'self'; script-src 'self' 'nonce-7iA7Yun3Yt5nW7q/AJvKv7zqgMeMwK+oqqK05XdqzO8='; style-src 'se                                     lf' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; bas                                     e-uri 'self';
< content-type: text/html; charset=UTF-8
content-type: text/html; charset=UTF-8
< date: Thu, 26 Sep 2024 17:32:40 GMT
date: Thu, 26 Sep 2024 17:32:40 GMT
< location: https://cloud.nextcloud.com/login
location: https://cloud.nextcloud.com/login
< referrer-policy: no-referrer
referrer-policy: no-referrer
< server: Caddy
server: Caddy
< set-cookie: oc_sessionPassphrase=4RPLybPNz1ww1%2FBU3qj5XHr2hHNMCX%2BGqgHQ4cjugTjTO23nPyQ%2FDBjHMcvUQ%2FD9iQY7FJEX0nyvAA7uwYT8PLZ                                     Ib8NWQfl4EWKGj4EDLymZ8eod2DLTSxdvioQF3F8g; path=/; secure; HttpOnly; SameSite=Lax
set-cookie: oc_sessionPassphrase=4RPLybPNz1ww1%2FBU3qj5XHr2hHNMCX%2BGqgHQ4cjugTjTO23nPyQ%2FDBjHMcvUQ%2FD9iQY7FJEX0nyvAA7uwYT8PLZIb                                     8NWQfl4EWKGj4EDLymZ8eod2DLTSxdvioQF3F8g; path=/; secure; HttpOnly; SameSite=Lax
< set-cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
set-cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
< set-cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
set-cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
< set-cookie: ocmk9xspynvl=63badd7fc63748b2a897e4b9a4567e08; path=/; secure; HttpOnly; SameSite=Lax
set-cookie: ocmk9xspynvl=63badd7fc63748b2a897e4b9a4567e08; path=/; secure; HttpOnly; SameSite=Lax
< x-content-type-options: nosniff
x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
x-frame-options: SAMEORIGIN
< x-permitted-cross-domain-policies: none
x-permitted-cross-domain-policies: none
< x-powered-by: PHP/8.1.2-1ubuntu2.18
x-powered-by: PHP/8.1.2-1ubuntu2.18
< x-robots-tag: noindex, nofollow
x-robots-tag: noindex, nofollow
< x-xss-protection: 1; mode=block
x-xss-protection: 1; mode=block

<
* Connection #0 to host cloud.nextcloud.com left intact`

`curl -6 -v -I https://cloud.nextcloud.com

*   Trying [2a01:4f8:231:37ef::2]:443...
* Immediate connect fail for 2a01:4f8:231:37ef::2: Network is unreachable
* Failed to connect to cloud.nextcloud.com port 443 after 4 ms: Couldn't connect to server
* Closing connection 0
curl: (7) Failed to connect to cloud.nextcloud.com port 443 after 4 ms: Couldn't connect to server`

with ` 'dns_pinning' => 'false' ` in config.php
`curl -6 -v -I https://alexkid3.duckdns.org/status.php
*   Trying [2a00:6020:49bd:9e00:7a17:fa70:3f6c:89b1]:443...
* Immediate connect fail for 2a00:6020:49bd:9e00:7a17:fa70:3f6c:89b1: Network is unreachable
* Failed to connect to alexkid3.duckdns.org port 443 after 3 ms: Couldn't connect to server
* Closing connection 0
curl: (7) Failed to connect to alexkid3.duckdns.org port 443 after 3 ms: Couldn't connect to server
`

**Comment by joshtrichards** [comment]
Okay, thanks for checking that. 

Doesn't appear to be a bug in Nextcloud. Your environment appears to be lacking IPv6 connectivity. At a minimum your Docker environment (or at least the virtual network associated with your Nextcloud stack) doesn't have functioning IPv6.

You'll have to troubleshoot your situation in greater depth. 

You might try asking for assistance on the help forum (https://help.nextcloud.com), but this isn't really a Nextcloud matter at all from the looks of it.

**Comment by AlexKid007** [comment]
your are right 

```
 curl -6 -v -I https://cloud.nextcloud.com
*   Trying [2a01:4f8:231:37ef::2]:443...
* Connected to cloud.nextcloud.com (2a01:4f8:231:37ef::2) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_128_GCM_SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=cloud.nextcloud.com
*  start date: Sep 26 08:03:28 2024 GMT
*  expire date: Dec 25 08:03:27 2024 GMT
*  subjectAltName: host "cloud.nextcloud.com" matched cert's "cloud.nextcloud.com"
*  issuer: C=US; O=Let's Encrypt; CN=E6
*  SSL certificate verify ok.
* using HTTP/2
* h2h3 [:method: HEAD]
* h2h3 [:path: /]
* h2h3 [:scheme: https]
* h2h3 [:authority: cloud.nextcloud.com]
* h2h3 [user-agent: curl/7.88.1]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x562d76c99ce0)
> HEAD / HTTP/2
> Host: cloud.nextcloud.com
> user-agent: curl/7.88.1
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/2 302
HTTP/2 302
< content-security-policy: default-src 'self'; script-src 'self' 'nonce-Xzoz64TDheJTP9HukIS30dQEt3pYRLArNVX2JHtYQws='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';
content-security-policy: default-src 'self'; script-src 'self' 'nonce-Xzoz64TDheJTP9HukIS30dQEt3pYRLArNVX2JHtYQws='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';
< content-type: text/html; charset=UTF-8
content-type: text/html; charset=UTF-8
< date: Thu, 26 Sep 2024 18:26:00 GMT
date: Thu, 26 Sep 2024 18:26:00 GMT
< location: https://cloud.nextcloud.com/login
location: https://cloud.nextcloud.com/login
< referrer-policy: no-referrer
referrer-policy: no-referrer
< server: Caddy
server: Caddy
< set-cookie: oc_sessionPassphrase=ORDkgELLXb2IIbxCrteDcFSzimn8Nu0N40Bs9YIQglMtl3W2ntZi1IJsKRTVRHubOcMOtGBbnKhv6nkZtZ6K0OzD1PgEcdNL5z%2FbeYWG7Fy16SgfZjGbovik0WT8W2Y%2B; path=/; secure; HttpOnly; SameSite=Lax
set-cookie: oc_sessionPassphrase=ORDkgELLXb2IIbxCrteDcFSzimn8Nu0N40Bs9YIQglMtl3W2ntZi1IJsKRTVRHubOcMOtGBbnKhv6nkZtZ6K0OzD1PgEcdNL5z%2FbeYWG7Fy16SgfZjGbovik0WT8W2Y%2B; path=/; secure; HttpOnly; SameSite=Lax
< set-cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
set-cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
< set-cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
set-cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
< set-cookie: ocmk9xspynvl=1e63a7117775e8790dd7149f4548e013; path=/; secure; HttpOnly; SameSite=Lax
set-cookie: ocmk9xspynvl=1e63a7117775e8790dd7149f4548e013; path=/; secure; HttpOnly; SameSite=Lax
< x-content-type-options: nosniff
x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
x-frame-options: SAMEORIGIN
< x-permitted-cross-domain-policies: none
x-permitted-cross-domain-policies: none
< x-powered-by: PHP/8.1.2-1ubuntu2.18
x-powered-by: PHP/8.1.2-1ubuntu2.18
< x-robots-tag: noindex, nofollow
x-robots-tag: noindex, nofollow
< x-xss-protection: 1; mode=block
x-xss-protection: 1; mode=block

<
* Connection #0 to host cloud.nextcloud.com left intact
```
but now I'm no longer able to reach my nextcloud, I have to find a working solution.
Thank you very much for your support
