### ISSUE TITLE
logo alignment issue on new password for new user without password created

### ISSUE THREAD

**Issue by JK74** [nextcloud/server#4836]
NC12.0B2

I created a new user without e-mail. 
The user needs to logon then using the link in the invite e-mail to generate an password. however the logo is now not aligned and it looks a bit 'uggly'. If the logo is very big in size (see other posting) then its even more worse but for now this topic is only adressing the mis-aligned logo to be not above the password reset (like it normally is during logon)  but through it. see picture attached.
![new_password_for_new_user_logon_logo_out_of_sync](https://cloud.githubusercontent.com/assets/17946255/25992963/a02aa594-3708-11e7-8520-ad332d84f102.PNG)

**Comment by LukasReschke** [comment]
Please provide an example link to your instance as well as more information on your version, whether you use theming or the theming app, etc.

**Comment by JK74** [comment]
shared to Lukas on e-mail due to privacy

**Comment by JK74** [comment]
this can be closed; the only minor defect now is that disabled users have an cosmetic alignment issue that  their account shows at the left side of the screen as disabled user. this can be closed
