### ISSUE TITLE
Layout of error page broken

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#4837]
The layout of the error pages is broken:

core/template/403.php:

![forbidden error](https://cloud.githubusercontent.com/assets/1589737/25994878/0c8da9be-3710-11e7-9ce2-c8f11e31b0f5.png)

core/template/error.php

![error page](https://cloud.githubusercontent.com/assets/1589737/25994889/1bebaba4-3710-11e7-9515-ff536b6181db.png)

cc @nextcloud/designers

**Comment by eppfel** [comment]
I can not reproduce the error pages, because I only get redirects and not error pages...
How do I reproduce the error?

**Comment by MorrisJobke** [comment]
> core/template/403.php:

This is not supported anymore. We always render it through index.php.

**Comment by MorrisJobke** [comment]
> core/template/error.php

Same here. Not supported.

**Comment by MorrisJobke** [comment]
See https://github.com/nextcloud/server/issues/3847

**Comment by MorrisJobke** [comment]
This is the 404 page I got when going to a non existing share:

![bildschirmfoto 2017-05-12 um 11 16 38](https://cloud.githubusercontent.com/assets/245432/26007053/8ed5da92-3704-11e7-9a8b-37a8ed2879dd.png)

**Comment by MorrisJobke** [comment]
> The layout of the error pages is broken

@schiessle How did you get there?

**Comment by MorrisJobke** [comment]
https://github.com/nextcloud/documentation/pull/392/files

**Comment by schiessle** [comment]
@MorrisJobke looked for a existing template and used it here: https://github.com/nextcloud/server/pull/4704/commits/63593f9245a40e5667e393b2b92bc7361d38a08e#diff-652646310472be421d6b80289b907cb8R167

So I will use something different here.
