### ISSUE TITLE
[Bug]: Exception: Database error when running migration The column "scheduled_at" on table "oc_taskprocessing_tasks" already exists.

### ISSUE THREAD

**Issue by re-boek** [nextcloud/server#48372]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I try to upgrade after migration to a new Server.
The following error appears.
Exception: Database error when running migration 30000Date20240708160048 for app core The column "scheduled_at" on table "oc_taskprocessing_tasks" already exists.
I I've tried  to find a workaround for this error on google but can't find anything about it.
I I've searched https://help.nextcloud.com also.
Is there a way to manipulate the db before upgrading so that the upgrade runs through?
For me it is hard to say if it is a bug or I did something wrong.....
Thanks and best regards.

### Steps to reproduce

1. Migrated data-folder like it is described in your documentation (Backup/restore)
2. Dumped and restored mariadb-server database like it is described in your documentation (Backup/restore)
3. In the end it is a move from LTS 18.04 to 24.04....so not sure if you will call it bug...or just out of scope...

### Expected behavior

get the db upgraded ....

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
> When I try to upgrade after migration to a new Server.

Is Nextcloud functioning pre-upgrade (running v29) on the new server?

That is, I presume you moved to the new server (same Nextcloud versions on both) first?

That column in the error `scheduled_at` wasn't added until v30. Are you sure an upgrade hasn't already been ran against this db somehow?

I see you mentioned checking the help forum. Did you post there for help? If so, please include the link to the thread.

**Comment by CHA23x** [comment]
I am seeing exactly the same issue with my installation. I am on NC since version 14 or so with the same parameters like re-boek. Never tried an update to v30 before, but now I have the same error message.

**Comment by CHA23x** [comment]
![image](https://github.com/user-attachments/assets/3038e879-5c61-4e60-8ce2-bc0f89297c01)

**Comment by Krautmaster** [comment]
having the same error and im stuck. How to solve. 30.0.1 stuck as well.

**Comment by luckydogxf** [comment]
Same here. I'm upgrading from 29.09 to 30.02. How to resolve it ?
