### ISSUE TITLE
[Bug]: OCC command not working

### ISSUE THREAD

**Issue by Donixon** [nextcloud/server#48382]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Server was upgraded to 30.0.0, the overview gave some warnings that I needed to "occ db:add-missing-indices", went to the container cli and like always, put in the command. This time it gave en error (on all OCC commands):
```
root@nextcloud-web:/# occ                                                        
An unhandled exception has been thrown:                                          
OCP\HintException: [0]: Downgrading is not supported and is likely to cause unpre
dictable issues (from 30.0.0.14 to 29.0.4.1) ()  
```

### Steps to reproduce

1. Open up terminal of the docker nextcloud container
2. Put in any OCC command (example: occ db:add-missing-indices)
3. It spits out the error above.

### Expected behavior

To just run the OCC command, like it always did.

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
> Open up terminal of the docker nextcloud container

Which Docker image? I don't believe this looks like any of ours.

> `Downgrading is not supported and is likely to cause unpredictable issues (from 30.0.0.14 to 29.0.4.1) ()`

The first number is the value of `version` from your active config, while the second is from your installation directory in `/version.php`. The output suggests that the v30 upgrade was ran against your config, but that your installation code base was then swapped back to your older one.  (There are other possible explanations though).

This sounds like a support matter related to your Docker volumes or something along those lines. You'll need to troubleshoot this matter via the help forum: https://help.nextcloud.com. When you do so, I encourage you to include your Docker Compose file for context.

**Comment by Donixon** [comment]
Oke, you talked about the volumes and then it rang a bell. I put 2 containers next to each other to test v30 of NC. I forgot about this because i named both containers somewhat the same (lazy). I went into the wrong container to fix the errors with OCC. No idea what went wrong there, but stopped both containers, started the correct one and it works now (???)

My excuse for my dumbness and wasting your time, but it is fixed!

Great response time you got btw, appreciated!
