### ISSUE TITLE
Recommendation for php.ini mistake in nc 12 beta 2

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#4838]
The admin screen warns about unoptimized php settings, but the first value mentioned seems broken:
```php_value opcache.enable=on```
That should, I believe, be:
```php_value opcache.enable=1```

This is Nextcloud 12 Beta 2.

See:
![screenshot_20170509_124940](https://cloud.githubusercontent.com/assets/551757/25995082/edaa9498-3710-11e7-99e4-59a036ae3b33.png)

**Comment by riegercloud** [comment]
yes: https://github.com/nextcloud/documentation/issues/450
Do i get a t-shirt please?!?
i would really really appreciate: need XL-shirt

**Comment by MorrisJobke** [comment]
> php_value opcache.enable=on

I did this by intention. I set it to 1 on PHP 5.6 and 7.0. In one of them the opcache was not activated. With `on` it worked fine. Even if the PHP documentation says something different I would stick to that, because I ran into issues with `1` which was fixed with the `on`.

**Comment by MorrisJobke** [comment]
> That should, I believe, be:

Never believe and always test ;)

**Comment by riegercloud** [comment]
>1 
is working properly. 
i maintain a lot of server running with that value as i wrote here and on my blog. 

additionaly on shared server hosted by aal-inkl.com

...:::carsten

**Comment by MorrisJobke** [comment]
> i maintain a lot of server running with that value as i wrote here and on my blog.
> additionally on shared server hosted by all-inkl.com and 1&1.

Is this always PHP 7.1 and PHP 7.0 or also older PHP?

**Comment by riegercloud** [comment]
I do not have an environment < PHP7 anymore. So to be honest - i cannot state.

**Comment by MorrisJobke** [comment]
> I do not have an environment < PHP7 anymore. So to be honest - i cannot state.

Okay ... let me try to find one and test this again.

**Comment by JSoko** [comment]
the (wrong) hint with opcache=on persists in NC12RC4...

**Comment by MorrisJobke** [comment]
Fix is in #5014 and #515
