### ISSUE TITLE
pasword change filed broken on personal page

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#4839]
If you try to change your password on the personal page, first everything looks OK:

![pass1](https://cloud.githubusercontent.com/assets/1589737/25996498/e3a28576-3717-11e7-8da6-90a5ec4c4aa0.png)

but if you try to look at the password you just entered, the password-strength-indicator moves to the top:

![pass2](https://cloud.githubusercontent.com/assets/1589737/25996508/f70edf92-3717-11e7-8d74-6b35aa072c6d.png)

cc @nextcloud/designers

**Comment by eppfel** [comment]
```HTML
<div class="personal-show-container">
  <label for="pass2" class="hidden-visually">New password: </label>
  <input type="password" id="pass2" name="newpassword" placeholder="New password" data-typetoggle="#personal-show" autocomplete="off" autocapitalize="none" autocorrect="off"  style="display: none;"><div class="strengthify-wrapper" data-strengthifyfor="pass2" title="" data-original-title="Very weak password" aria-describedby="tooltip862577">
  <div class="strengthify-bg" style="opacity: 1;"></div><div class="password-bad strengthify-container" style="opacity: 1; width: 25%;"></div><div class="strengthify-separator" style="left: 25%; opacity: 1;"></div><div class="strengthify-separator" style="left: 50%; opacity: 1;"></div><div class="strengthify-separator" style="left: 75%; opacity: 1;"></div><div class="strengthify-tiles" style="opacity: 1;"></div></div><div class="tooltip fade bottom in" role="tooltip" id="tooltip862577" style="top: 34px; left: 2px; display: block;"><div class="tooltip-arrow" style="left: 50%;"></div><div class="tooltip-inner">Very weak password</div></div>
  <input type="text" name="newpassword-clone" autocomplete="off" placeholder="New password" style="display: inline-block;">
  <input type="checkbox" id="personal-show" name="show"><label for="personal-show" class="personal-show-label"></label>
</div>
```

The `input[type="text"]` with the clear text sits under the strengthify `div`. When it would sit on top, it works.

```HTML
<div class="personal-show-container">
  <input type="text" name="newpassword-clone" autocomplete="off" placeholder="New password" style="display: inline-block;">
  <label for="pass2" class="hidden-visually">New password: </label>
  <input type="password" id="pass2" name="newpassword" placeholder="New password" data-typetoggle="#personal-show" autocomplete="off" autocapitalize="none" autocorrect="off"  style="display: none;"><div class="strengthify-wrapper" data-strengthifyfor="pass2" title="" data-original-title="Very weak password" aria-describedby="tooltip862577">
  <div class="strengthify-bg" style="opacity: 1;"></div><div class="password-bad strengthify-container" style="opacity: 1; width: 25%;"></div><div class="strengthify-separator" style="left: 25%; opacity: 1;"></div><div class="strengthify-separator" style="left: 50%; opacity: 1;"></div><div class="strengthify-separator" style="left: 75%; opacity: 1;"></div><div class="strengthify-tiles" style="opacity: 1;"></div></div><div class="tooltip fade bottom in" role="tooltip" id="tooltip862577" style="top: 34px; left: 2px; display: block;"><div class="tooltip-arrow" style="left: 50%;"></div><div class="tooltip-inner">Very weak password</div></div>
  <input type="checkbox" id="personal-show" name="show"><label for="personal-show" class="personal-show-label"></label>
</div>
```
The strengthify is injected after pass2, but I could not find, where the `input[type="text"]` is injected.

Relevant files: 
- `settings/templates/personal.php` 
- `settings/js/personal.js`

**Comment by MorrisJobke** [comment]
moved to 12.0.1

**Comment by AykutCevik** [comment]
I also have a similar issue regarding the password change:
If I enter a long password (longer than input width) and want to review it moving the caret with the keyboard arrow keys, the strength indicator becomes on top of the input field:


![kapture 2017-05-28 at 13 33 09](https://cloud.githubusercontent.com/assets/1965251/26528350/356017ea-43aa-11e7-9628-c77193d08f7b.gif)

**I also would like to suggest another workflow for the password change.** Add one more field to verify the newly entered password (repeat new password). I have file encryption enabled and recovery set to false which means if I make a mistake while entering the password once all my data will be lost unrecoverable.
Or do I miss something here?
Also viewing the plain text of the password to review it is not always a suitable solution.

**Comment by eppfel** [comment]
@AykutCevik Can you open a new issue for your wokflow suggestion/critique? This issue is for a particular bug.
