### ISSUE TITLE
Better UI for managing and applying tags ?

### ISSUE THREAD

**Issue by kbeerepoot** [nextcloud/server#4842]
Would it be possible to create a better system for managing and applying tags?

My problem is that the list of possible tags gets quite long for me. Various items in the tag list can refer to completely different contexts but are all in just one long alfabetical list. Grouping items based on context in the tag list can only be done by incorporating the grouping in the names of the items, which creates new problems.

**Comment by Spartachetto** [comment]
I do share the point raised by @kbeerepoot .
I restrain myself to use fully the tag system in Nextcloud just to avoid to have a huge and unmanageable list of tags

I doubt that a better interface could solve completely the problem. In a discussion on help.nextcloud I proposed a hierarchical structure for tags. Here is the link: [ Possibility of a Hierarchical structure for tags](https://help.nextcloud.com/t/possibility-of-a-hierarchical-structure-for-tags/4509).

Someone proposed (also or instead...) to use files metadata: [Files extended metadata](https://help.nextcloud.com/t/files-extended-metadata/2487), and @oparoz was coordinating an effort in that direction: [MediaMetadata app to extract and store meta data from media files](https://help.nextcloud.com/t/mediametadata-app-to-extract-and-store-meta-data-from-media-files/1601)

I may be wrong, but I think that an improvement of the tagging system requires a bit of discussion to understand the right direction... (@jancborchardt and @nickvergessen could be interested, maybe)

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest and no respond since around 2 years. Please reopen if you still want to implement this.

**Comment by Spartachetto** [comment]
Glad to see that this issue was reopen.
I still think that all the tag related issues (see #4699 ) identify a sector that is in need of "care", and I seem to remember that @skjnldsv does agree

**Comment by skjnldsv** [comment]
Summarized in https://github.com/nextcloud/server/issues/4699
