### ISSUE TITLE
[Bug]: Uploading a new Background Image displays error "conflict between new type (mixed) and old type (string)"

### ISSUE THREAD

**Issue by Elendiir1970** [nextcloud/server#48436]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi,
several people seem to have problems when changing the background image. See the last comments in #45083.
Since nobody has added the issue to the list I just did it.
After upgrading my docker image to the nextcloud version 30.0 I am not able to change the background image anymore. If I do so the image will be uploaded but is not applied. Instead I do get an error "conflict between new type (mixed) and old type (string)".

A screenshot showing the error from the menu Desgin is attached
![conflict_message](https://github.com/user-attachments/assets/d3df2eca-c3a1-4b0d-8443-a165e7bb1e80)

### Steps to reproduce

1. Open Management Seeting 
2. Select Design
3. Upload a new background image (i tried a 8MB *.jpg)
4. Error message should appear

### Expected behavior

The uploaded image should be used as new background image.

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

None

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [X] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
I suspect this only happens if there was a custom image prior to the upgrade. On a new installation (the handiest test environment I have on-hand), this doesn't seem to be a problem (which make sense given what I understand to be the underlying cause).

It's possible a temporary workaround would be to use the back arrow / reset to default and/or trash option for the existing image before uploading a new one.

**Comment by Elendiir1970** [comment]
Hi Josh,
you are right. I have upgrade my docker image with the old image set. This did work fine. After the update to version 30 the background image still got displayed. 
But now changing the image is not possible anymore. I also tried to delete/remove the old image. This worked as expected. I now have a background consisting out of a single solid color. But I am not able to change the background image. When I do so the error messages appears.
Cheers
Fritz

**Comment by Elendiir1970** [comment]
The back arrow does reset the image to default. But still I do get the same error:
![conflict_message](https://github.com/user-attachments/assets/1d97a2e9-ea9c-4eb8-aef3-011b6e225b02)

**Comment by kesselb** [comment]
cc @nextcloud/server

**Comment by AnonymousX86** [comment]
Issue is still present in [this build of 30.0](https://github.com/linuxserver/docker-nextcloud/pkgs/container/nextcloud/282225669?tag=30.0.0).
![Image](https://github.com/user-attachments/assets/75079ee0-6eda-417d-9eb5-295f0116a78b)
I have already tried removing and uploading once more. Even with Nextcloud restart.

**Comment by joshtrichards** [comment]
> Issue is still present in this build of 30.0.

Well, yeah. Because that's the release with the bug in it. :-) The fix is merged and will be in the next maintenance release (30.0.1):

https://github.com/nextcloud/server/pull/48452

**Comment by AlexTsuke** [comment]
Guessing we just got to wait for a maintenance release and we should be good to go?

Just found it odd that it was going good until now it suddenly started doing this.
