### ISSUE TITLE
Suggest servers to trust based on existing federated shares

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#4844]
* from #2672 
* in the federation section show suggestions for trusted servers based on received/send shares sorted by usage stats

cc @schiessle @jancborchardt

**Comment by jancborchardt** [comment]
Yup. Interface-wise they could be shown as ghost-entries on the bottom of the trusted servers list with `opacity: .5;` and a button »Add as trusted« to the right of it.

Sounds good @schiessle?

**Comment by MorrisJobke** [comment]
Most likely nothing for 14 -> moving to 15.

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by MorrisJobke** [comment]
I would close it. The trusted servers are very limited especially as they exchange their user base - so typically the admin knows all the related server.
