### ISSUE TITLE
During update: Specified key was too long

### ISSUE THREAD

**Issue by qaxcftz** [nextcloud/server#4846]
### Steps to reproduce
1. update nc 12.0.1 to nc 12.0.2 
2. install update with update button
3. fail

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Das Datenbankschema wird aktualisiert
Datenbank aktualisiert
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
Das Update ist fehlgeschlagen.

most of features into nc 12.0.1 are enabled, such as calendar and contacts but doesnt work at 12.0.1

Server: qnap nas TVS-682 firmwar 4.3.3
Webserver: apache
Database: mariadb 
PHP version 5.6

I hope this information are enough.

**Comment by MorrisJobke** [comment]
cc @nickvergessen @georgehrke

**Comment by qaxcftz** [comment]
the problem is located by UNIQUE INDEX addressbook_index (principaluri, uri) 
principaluri and uri TYP VARCHAR with size of 255, VARCHAR use 3 byte per CHAR 255*3 = 765 *2 =1530 that is more as 1000 bytes per index.

solution: use only the first 150 char by index UNIQUE `addressbook_index` (`principaluri`(150), `uri`(150))

my manual  created table statement:
CREATE TABLE `nextcloud`.`test` ( `id` BIGINT UNSIGNED NULL AUTO_INCREMENT , `principaluri` VARCHAR(255) NULL DEFAULT NULL , `displayname` VARCHAR(255) NULL DEFAULT NULL , `uri` VARCHAR(255) NULL DEFAULT NULL , `description` VARCHAR(255) NULL DEFAULT NULL , `synctoken` INT UNSIGNED NOT NULL DEFAULT '1' , PRIMARY KEY (`id`), UNIQUE `addressbook_index` (`principaluri`(150), `uri`(150))) ENGINE = MyISAM CHARSET=utf8 COLLATE utf8_bin;

**Comment by nickvergessen** [comment]
well you can also enable innodb_large_prefix:
https://dev.mysql.com/doc/refman/5.7/en/innodb-restrictions.html
> If innodb_large_prefix is enabled (the default), the index key prefix limit is 3072 bytes for InnoDB tables that use DYNAMIC or COMPRESSED row format. If innodb_large_prefix is disabled, the index key prefix limit is 767 bytes for tables of any row format. 

Also make sure your row format is compressed:
https://github.com/nextcloud/server/issues/4548

**Comment by Alixerid** [comment]
I had this issue, too, when trying to add 4 Byte support to the mysql database and followed the instructions of the official server admin manual: https://docs.nextcloud.com/server/12/admin_manual/configuration_database/mysql_4byte_support.html 
Bottom line is: there is a typo in the instructions. The line
`innodb_large_prefix=on` should read `innodb_large_prefix=1` instead.
Mysql ignores "on" as value and then people get the described problems because large prefix is actually not enabled despite the change in the config file.

**Comment by nickvergessen** [comment]
Hmm we had true, then 1 now "on"... and it's always not working for someone...
But https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix states the default of this Boolean is `ON`.

I don't know what to trust anymore....

**Comment by Alixerid** [comment]
Sorry for the confusion. Here are more details on my experience:
The option innodb_large_prefix defaults to TRUE in mysql 5.7. I am running version 5.5.55 where innodb_large_prefix defaults to FALSE according to the docs. Hence, I need to set the value manually in my.cnf.

I had put `ON` in my.cnf and restarted mysqld. Then `mysqld --help --verbose` gave me the error:
> 170620  21:15:08 [Warning] /usr/sbin/mysqld: ignoring option '--innodb-large-prefix' due to invalid value 'on'

When I changed the value in my.cnf to `1` the option was read and set correctly. 

I do not understand why ON is not accepted by mysql 5.5.55. The [docs](https://dev.mysql.com/doc/refman/5.5/en/option-modifiers.html) state the contrary: 
> As of MySQL 5.5.10, the values ON, TRUE, OFF, and FALSE are also recognized for boolean options (not case sensitive).

Anyways, maybe changing the nextcloud docs to 1 would prevent people from running into this problem, too?

**Comment by nickvergessen** [comment]
sounds good, want to send a PR to the docs to change it?
