### ISSUE TITLE
new user with same name as a before deleted one inherits personal info

### ISSUE THREAD

**Issue by mind22** [nextcloud/server#4848]
### Steps to reproduce
1. Create new test account
2. Login and upload picture + create personal infos + Logout
3. Delete test account
4. Create test account with same name but different (or same) password

### Expected behaviour
I think this should be handled as a new account.

### Actual behaviour
The test account in step 4. inherits the personal infos and profile picture from the one filled in step 2.

### Server configuration

**Operating system:** Ubuntu Server 16.04.2 LTS

**Web server:** nginx 1.10.0

**Database:** mysql 10.0.29

**PHP version:** 7.0.15

**Nextcloud version:** 11.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 11

**Where did you install Nextcloud from:** official homepage

**Comment by MorrisJobke** [comment]
similar to #1557 

cc @nickvergessen @rullzer @ChristophWurst
