### ISSUE TITLE
[Bug]: file name is not showing NC28.0.10

### ISSUE THREAD

**Issue by 007Poe** [nextcloud/server#48482]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [X] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The file name is not showing when saving the file after editing file in NC28.0.10.
File name is showing after reload the browser using F5.

I reported about this bug on forum.
https://help.nextcloud.com/t/file-name-is-not-showing-in-nc28/205288

### Steps to reproduce

1.Create a new test.ods file.
 
![image](https://github.com/user-attachments/assets/ad5901f7-6897-4ed0-a4b3-1c088c920bf8)

2.Open test.ods and edit file.
   
![image](https://github.com/user-attachments/assets/05ab8170-446a-4dc2-9155-2ab12c9d14e7)

3.Save and Close test.ods
![image](https://github.com/user-attachments/assets/d1096945-12bf-46b5-bf57-fdf79f5ae7ba)
File name is not showing..

4. Reload browser by using F5.
    
![image](https://github.com/user-attachments/assets/20ce508f-8cf7-480e-abcf-ac5e33289af6)

File name is showing after reload the browser using F5...

you can check from this video.
https://www.dropbox.com/scl/fi/3l65218o56sgfyllzzgpx/evidence.mkv?rlkey=5nxmo0k5hhrm7h7eok9y4hq0h&st=iwpfffhx&dl=0

And I reported about this bug on forum.
https://help.nextcloud.com/t/file-name-is-not-showing-in-nc28/205288

### Expected behavior

File name displays after editing file.

### Nextcloud Server version

28

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [X] Other

**Comment by joshtrichards** [comment]
I'm unable to reproduce this behavior. The filename always is visible as expected.

Are you sure you're not doing any custom css or something? 

I do notice something odd in your video: When you are creating a new spreadsheet, after you click *Create* you're being returned to the file list rather than Office opening immediately. That's not the behavior I have nor would expect.

You didn't fill out the entire support template so unfortunately we can only speculate.

**Comment by joshtrichards** [comment]
Can you create an issue for the other matter (deleted file / appearing multiple times) you mentioned in that thread on the forum? I am able to reproduce that one, but we need to handle it separately so it needs its own Issue.

**Comment by 007Poe** [comment]
> I'm unable to reproduce this behavior. The filename always is visible as expected.
> 
> Are you sure you're not doing any custom css or something?
> 
> I do notice something odd in your video: When you are creating a new spreadsheet, after you click _Create_ you're being returned to the file list rather than Office opening immediately. That's not the behavior I have nor would expect.
> 
> You didn't fill out the entire support template so unfortunately we can only speculate.

  Thank you for your check. 

  Sorry, sir,
  The filename display problem is my fault.  
  I did the following to fix the problems when upgrading from NC27 to NC28.0.10.
![Image](https://github.com/user-attachments/assets/f96a06fc-3236-46ec-a708-d34735b7d00c)

1.   sudo cp -pi /var/www/html/nextcloud/core/js/mimetypelist.js /var/backups/nextcloud/mimetypelist.js.$(date +%Y%m%d)
2.   sudo cp -pi /var/www/html/nextcloud/core/js/mimetypelist.js /var/www/html/nextcloud/mimetypelist.js.$(date +%Y%m%d)
3.   https://github.com/nextcloud/server/blob/stable28/core/js/mimetypelist.js
4.   nano /var/www/html/nextcloud/mimetypelist.js
5.  sudo -u www-data diff -u /var/www/html/nextcloud/core/js/mimetypelist.js /var/www/html/nextcloud/mimetypelist.js> 
6.  mimetypelist.patch
7.  sudo -u www-data diff -u /var/www/html/nextcloud/core/js/mimetypelist.js /var/www/html/nextcloud/mimetypelist.js.fixed > 
8.  mimetypelist-test.patch
9.  cat mimetypelist.patch
10.   sudo patch -d /var/www/html/nextcloud/core/js < /var/www/html/nextcloud/mimetypelist.patch 
11.   sudo -u www-data diff -u /var/backups/nextcloud/mimetypelist.js.$(date +%Y%m%d) 
12.   /var/www/html/nextcloud/core/js/mimetypelist.js
13.   ls -l /var/www/html/nextcloud/core/js/mimetypelist.js
14.   sudo -u www-data php /var/www/html/nextcloud/occ maintenance:repair --include-expensive
15.   rm -rf mimetypelist.js.date
16.   rm -rf mimetypelist.patch 
17.   rm -rf core/img/filetypes/dwb.svg
18.   rm -rf core/img/filetypes/drawio.svg
19.   rm -rf mimetypelist.js.fixed
20.   sudo -u www-data php /var/www/html/nextcloud/occ maintenance:repair --include-expensive
21.   systemctl restart apache2
 
 **Without patching on NC28.0.10, the filename is always visible.**

**Comment by 007Poe** [comment]
> deleted file / appearing multiple times

Of course I created about this topic.
https://github.com/nextcloud/server/issues/48657
