### ISSUE TITLE
Support PostgreSQL 17

### ISSUE THREAD

**Issue by wrenix** [nextcloud/server#48495]
Current i got a Warning:

> PostgreSQL version "17.0" detected. PostgreSQL >=12 and <=16 is suggested for best performance, stability and functionality with this version of Nextcloud.

**Comment by LM-vb** [comment]
Do you see any negative effects on your NC instance when running PostgreSQL 17?

**Comment by js-d-coder** [comment]
I am running Nextcloud 30 and have used v29 on Postgresql 17, I did not face any issue.

**Comment by chrissi55** [comment]
upgraded the 16 main cluster to 17 and made some adjustments following several performance settings frome here

https://pgtune.leopard.in.ua/#/

Running fast and good as far as i have observed at the moment.

**Comment by GreyXor** [comment]
same here, no issues on my nextcloud 30 + pg17

**Comment by fenvarien** [comment]
No issues with Nextcloud 30.0.2 and PostgreSQL 17.
