### ISSUE TITLE
Group Folder icon not applying theme

### ISSUE THREAD

**Issue by mrnoisytiger** [nextcloud/server#4849]
### Steps to reproduce
1. Enable Group Folders and create one
2. Apply custom theme color
3. Navigate to group folder

### Expected behaviour
Group folder takes on the custom theme color

### Actual behaviour
Group folder does not have a custom color

### Server configuration

**Operating system**: Ubuntu 16.04 LTS

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.0

**Nextcloud version:** (see Nextcloud admin page) 12 beta 2

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Where did you install Nextcloud from:** Zip file on website

![untitled](https://cloud.githubusercontent.com/assets/12619586/26017714/dc602d4c-371f-11e7-974f-ba82156e9d83.jpeg)

**Comment by MorrisJobke** [comment]
cc @juliushaertl @daita

**Comment by juliushaertl** [comment]
This was already fixed here https://github.com/nextcloud/groupfolders/commit/642833fe8c88b0dfc325e47f1f4f36bbc54921ca 

I guess there will be a new version of groupfolders released for the final Nextcloud 12 release.

**Comment by MorrisJobke** [comment]
@LukasReschke
