### ISSUE TITLE
Link tags to other objects

### ISSUE THREAD

**Issue by Spartachetto** [nextcloud/server#4850]
I had an idea that could be interesting to explore.

In some cases it could be useful to link the tags to other objects of the nextcloud instance.

The better example is a link with contacts. 
I do not mean tagging a contact, but "saying" to Nextcloud that the tag "John" is linked to the contact "John Doe" with a telephone number, an email, ...
This means that when I tag a photo or a document with the tag "John", the photo is linked to the contact.

Use cases:

- It could possibly help #4842
- It could be linked to some sharing behaviour
- In the future it could be useful for the use of Nextcloud as a communication platform

Another possible "link" is between a tag and a "place" defined in the map app.

**Comment by MorrisJobke** [comment]
cc @blizzz @nickvergessen @karlitschek

**Comment by karlitschek** [comment]
very interesting idea! i like this

**Comment by Spartachetto** [comment]
I happened to read the "Diary" feature proposed for the gallery (https://github.com/nextcloud/gallery/issues/232) and I wonder if it can be considered connected to this one.

The idea proposed by @tobiasKaminsky is to combine the calendar and the gallery/images into a diary.

There are two interesting links to my idea

1. they are talking of a "link of different objects" like me
2. Imagine if Nextcloud could use the link between tags and contacts and places and ... to display a "Diary" with all the above info together! It would be extremely cool! 

If you are interested I am available to discuss what are the use cases, how to display information, ...
Just let me know!

**Comment by Spartachetto** [comment]
A further element: I made the hypothesis of a "link" between a tag and a "place" defined in the map app. 
Here are the links to some related issues in the map app repository:

- Events on the map (https://github.com/nextcloud/maps/issues/3)
- Add support for Geo Information in contacts (https://github.com/nextcloud/maps/issues/16)
- interaction between events, contacts and other info via the map (https://github.com/nextcloud/maps/issues/18)

HTH!

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest and no respond since around 2 years. Please reopen if you still want to implement this.
