### ISSUE TITLE
Add X-NC-Disable-Scheduling property to allow skipping scheduling deliveries

### ISSUE THREAD

**Issue by miaulalala** [nextcloud/server#48528]
When syncing with a different Calendar sever that PUTs all events, including the already delivered scheduling events for ATTENDEEs, the scheduling logic shouldn't trigger local delivery again.

Add the X-NC-Disable-Scheduling property that will skip both the SchedulingPlugin and the IMipPlugin so users don't get notified twice.

**Comment by SebastianKrupinski** [comment]
@miaulalala  do we need to back port this?

**Comment by miaulalala** [comment]
Yes, currently supported versions pls 🙏
