### ISSUE TITLE
Updating to 11.0.3 messed up everything

### ISSUE THREAD

**Issue by andre-paulo98** [nextcloud/server#4855]
### Steps to reproduce
When updating from 11.0.2 to 11.0.3 

### Actual behaviour
Its stuck on Move new files in place
http://i.imgur.com/VT79ySf.png
files on the folder are really messed up 
http://i.imgur.com/BnsSdJ1.png
That is the folder where was the nextcloud site

### Server configuration

**Operating system**: Ubuntu 16

**Web server:** Apache

**Database:** MySQL

**PHP version:**  7.0.15

**Nextcloud version:** 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from ownCloud

**Where did you install Nextcloud from:** Not sure but most likely from download.nextcloud.com

**List of activated apps:**
<details>
<summary>App list</summary>
Installation is messed up. Can't check
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
Installation is messed up. Can't check
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:**  No

### Client configuration
**Browser:** Chrome 58.0.3029

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Sat May 13 19:13:24.120982 2017] [authz_core:error] [pid 14391] [client X:X] AH01630: client denied by server configuration: /var/www/X/public/data/.ocdata
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
can't access
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
http://i.imgur.com/LlCbJC6.png
```
</details>

**Comment by MorrisJobke** [comment]
This seems to be an updater problem. Could you provide us with the updater.log in the data directory?

**Comment by andre-paulo98** [comment]
Here it is: https://gist.github.com/andre-paulo98/8d8fd1be1929447388ffb377ba3fe954

**Comment by MorrisJobke** [comment]
looks like the updater was stopped in the middle. Have you lost the connection to the server while having the browser page open? (because it looks like that)

Ways to continue updater:

* go to `/var/www/cloud.X/public/updater` on the command line and execute `php updater.phar` as the web server user (typically prefix this with `sudo -u www-data` for Ubuntu for example)
* open https://example.org/updater/index.php and follow the instructions there

Then the update process should continue.

**Comment by andre-paulo98** [comment]
I dont think that i lost connection during the update.
But your solution did the trick. Thank you very much 😄

**Comment by Hanzei** [comment]
I run into the same problem. But because the updater deleted some old files and the crashed I can't finish the update. `php updater.phar` prints out:
````
Start update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔] Check for expected files
[✔] Check for write permissions
[✔] Enable maintenance mode
[✔] Create backup
[✔] Downloading
[✔] Extracting
[✔] Replace entry points
[✘] Delete old files failed
core/shipped.json is not available

Update failed. To resume or retry just execute the updater again.
````

**Comment by MorrisJobke** [comment]
Could I ask you to open this as an issue in the updater bug tracker? https://GitHub.com/nextcloud/updater

**Comment by Hanzei** [comment]
@MorrisJobke sure

**Comment by PanicDriven** [comment]
I had this exact same problem from 11.0.4 to 11.0.5. I created a shipped.json file in my nextcloud/core/ and set permissions to 777 for shipped.json. This worked and let me complete the update after rerunning the updater but resulted in this: 

[✔] Check for expected files
[✔] Check for write permissions
[✔] Enable maintenance mode
[✔] Create backup
[✔] Downloading
[✔] Extracting
[✔] Replace entry points
[ ] Delete old files ...PHP Warning:  Invalid argument supplied for foreach() in phar:///var/www/nextcloud/updater/updater.phar/lib/Updater.php on line 592
[✔] Delete old files
[✔] Move new files in place
[✔] Done

Not sure what that means... but nextcloud show i'm on 11.0.5 now.
