### ISSUE TITLE
Nextcloud show up

### ISSUE THREAD

**Issue by SGirl-Zockt** [nextcloud/server#48562]
Greetings,

I have Update my Desktop Client yesterday and now i dont show up next to the Network Symbol like i placed it, its comepley gone there.

in German:
Gestern hab ich auf diese Verison des Desktop Clienten geupdatet jetzt fehlt mir das Ican von Nextclound da wo auch das Icon fürs Netzwerk ist.

Grettings
SGirl

**Comment by joshtrichards** [comment]
https://help.nextcloud.com
