### ISSUE TITLE
Layout glitches with NC 12 - "ResourceLocator can not find a web root"

### ISSUE THREAD

**Issue by derkostka** [nextcloud/server#4857]
### Steps to reproduce
1. Log into Nextcloud, Tested: Chrome & Safari on Mac OS
2.
3.

### Expected behaviour
To see the usual beautiful layout of the files-app

### Actual behaviour
Several glitches. The load spinner is not correct, the files list is nearly not usable

### Server configuration

**Operating system**: 
Ubuntu 16.04

**Web server:** 
Apache 2.4

**Database:** 
MySQL

**PHP version:** 
7.1

**Nextcloud version:** 
Daily (12.05.2017), also visible on NC 12 Beta 2

**Updated from an older Nextcloud/ownCloud or fresh install:** 
Updated from Stable 11

**Where did you install Nextcloud from:**
Manual Download of the .zip provided in the updater app

<img width="544" alt="screenshot at mai 13 21-32-49" src="https://cloud.githubusercontent.com/assets/8389316/26028603/71dcf8a0-3824-11e7-9dc0-02beb0032edd.png">

<img width="717" alt="screenshot at mai 13 21-32-28" src="https://cloud.githubusercontent.com/assets/8389316/26028604/76a4852e-3824-11e7-8379-eaedad39162c.png">

Log:
> 
{"reqId":"y9AFFKQxvwgEEJ3TOYOa","level":3,"time":"May 16, 2017 08:16:32","remoteAddr":"127.0.0.1","user":"admin","app":"lib","method":"GET","url":"\/apps\/files\/","message":"ResourceLocator can not find a web root (root: \/var\/www\/nextcloud\/apps\/files, file: css\/files\/merged.css, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36","version":"12.0.0.19"}

**Comment by derkostka** [comment]
Any hint or idea on what to do ? I already cleared the browser cache. I am using http 2.0 and php 7.1.

Performance seems normal, however the layout is barely usable, seems that something is missing at my installation.

**Comment by MorrisJobke** [comment]
Anything suspicious in the network console of the dev tools in your browser? Anything in the JS console of the web dev tools?

**Comment by tessus** [comment]
@derkostka out of curiosity: do you see the same glitches when you use http/1.1?

I've noticed that you're using http2 and I've had unresolvable issues with h2 myself, thus I'm interested in all bugs that involve h2.

@MorrisJobke it's not my intention to hijack this thread. I would have sent an email to the OP, but there's no email in the OP's profile.

**Comment by MorrisJobke** [comment]
> @MorrisJobke it's not my intention to hijack this thread. I would have sent an email to the OP, but there's no email in the OP's profile.

No worries. That could be a possible reason for this. Nevertheless I run the same with Nginx and HTTP 2 and it works fine 🙈

**Comment by tessus** [comment]
> Nevertheless I run the same with Nginx and HTTP 2 and it works fine

Yea, you or oparoz mentioned Apache had a problem with h2. But I was debugging it and couldn't find any issues. I also tried several versions of mod_http2. Maybe I'll shoot Stefan Eissing an email, but for that I should be sure that h2 is the culprit. And, if @derkostka has also a problem with h2, it's more likely an Apache/h2 issue...

**Comment by derkostka** [comment]
Thank you for the hints. Let me comment on them one by one:

a) @tessus : I´ve disabled h2, no change. However i have had it enabled on NC11 a while back. The performance is visibly better with h2. I am running it on Apache 2.4.25 Ubuntu 16.04 sources, using famous Sury´s repository: https://launchpad.net/~ondrej

b) @MorrisJobke The console seems fine. However i noticed that starting with NC 12, first totp auth response takes about 20 seconds. Secondly, i am always directed to: "/apps/files/?dir=/&fileid=560475", where i see the list of files and the warning "Die Datei überschreitet die Maximalgröße für Uploads auf diesem Server." at the very end.

If you want to take a look by yourself:

https://cloud.sebastiankostka.de/login

user: tester
pwd: *Test2017

https://launchpad.net/~ondrej

**Comment by derkostka** [comment]
Some more logs complaining about a missing web-root:

> {"reqId":"rt0IrwhqoLMCvmdOfHIa","level":3,"time":"May 15, 2017 19:45:06","remoteAddr":"127.0.0.1","user":"tester","app":"lib","method":"GET","url":"\/apps\/files\/","message":"ResourceLocator can not find a web root (root: \/var\/www\/nextcloud\/apps\/files_sharing, file: css\/files_sharing\/mergedAdditionalStyles.css, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36","version":"12.0.0.19"}
{"reqId":"rt0IrwhqoLMCvmdOfHIa","level":3,"time":"May 15, 2017 19:45:06","remoteAddr":"127.0.0.1","user":"tester","app":"lib","method":"GET","url":"\/apps\/files\/","message":"ResourceLocator can not find a web root (root: \/var\/www\/nextcloud\/apps\/files_texteditor, file: css\/files_texteditor\/merged.css, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36","version":"12.0.0.19"}
{"reqId":"JTjTSLZBHjQNuCcZZ6f7","level":3,"time":"May 15, 2017 19:45:54","remoteAddr":"127.0.0.1","user":"tester","app":"lib","method":"GET","url":"\/apps\/files\/","message":"ResourceLocator can not find a web root (root: \/var\/www\/nextcloud\/apps\/files, file: css\/files\/merged.css, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36","version":"12.0.0.19"}
{"reqId":"JTjTSLZBHjQNuCcZZ6f7","level":3,"time":"May 15, 2017 19:45:54","remoteAddr":"127.0.0.1","user":"tester","app":"lib","method":"GET","url":"\/apps\/files\/","message":"ResourceLocator can not find a web root (root: \/var\/www\/nextcloud\/apps\/files_sharing, file: css\/files_sharing\/mergedAdditionalStyles.css, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36","version":"12.0.0.19"}
{"reqId":"JTjTSLZBHjQNuCcZZ6f7","level":3,"time":"May 15, 2017 19:45:55","remoteAddr":"127.0.0.1","user":"tester","app":"lib","method":"GET","url":"\/apps\/files\/","message":"ResourceLocator can not find a web root (root: \/var\/www\/nextcloud\/apps\/files_texteditor, file: css\/files_texteditor\/merged.css, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_12_4) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36","version":"12.0.0.19"}

**Comment by tessus** [comment]
@derkostka 
> I´ve disabled h2, no change. However i have had it enabled on NC11 a while back. The performance is visibly better with h2.

Yep, that's why I wanted to switch to h2, but it doesn't work for me. It works on all my other web apps, but nextcloud. Since it works for you, I will have to do some more debugging....

Cheers.

**Comment by derkostka** [comment]
Okay i have done a re-install on the same setup in order to test if it is a configuration issue. It seems to be, the test installation works fine --> I will close this ticket, thanks for your ideas.

**Comment by derkostka** [comment]
For the record: I have had the folder "/var/www" moved to a slow, encrypted external SD card and symlinked to /var/www/ The issue got resolved once i moved it back to the internal storage.

**Comment by ldapomni** [comment]
Bug. If symlink to NC12  (example /www/nextcloud link to /srv/www/htdocs/nextcloud) get throw in log 'ResourceLocator can not find a web root'. CSSResourceLocator work correct only if path in config file is absolute.

**Comment by derkostka** [comment]
closed --> will be solved wirh #5057
