### ISSUE TITLE
Do not allow empty name in theming app

### ISSUE THREAD

**Issue by ishanloya** [nextcloud/server#4858]
If the name is blank in the admin theming section, the slogan should not be preceded by a hyphen

**Comment by MorrisJobke** [comment]
cc @juliushaertl @nickvergessen for theming in general and the theming app in specific

**Comment by nickvergessen** [comment]
Not sure if we should support empty name. It causes awkward stuff all around (email captions, etc)

**Comment by willpittman432** [comment]
Hey I would like to try and help with this issue. I have never contributed to an open source project and have been looking into some beginner-level issues to try and help out with.

**Comment by juliushaertl** [comment]
@willpittman432 Sorry for the late reply. If you're still interested, feel free to go ahead and submit a pull request. If you need any advice while implementing this, feel free to ask.

**Comment by sagorika1996** [comment]
Can I take up this issue?

**Comment by juliushaertl** [comment]
@sagorika1996 Sure, if you have any questions feel free to ask here or join our developers IRC channel: https://riot.im/app/#/room/#freenode_#nextcloud-dev:matrix.org
