### ISSUE TITLE
[Bug]: False alarm for Your web server is not yet properly set up to allow file synchronization, because the WebDAV interface seems to be broken.

### ISSUE THREAD

**Issue by catarse-natural** [nextcloud/server#48593]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Since migrating to NC29.0.0 there have been several new issues with Security & setup warnings since the mechanism changed for extenal checks. I followed all upgrade documentation for migration here [Upgrade to Nextcloud 28 — Nextcloud latest Administration Manual latest documentation 99](https://docs.nextcloud.com/server/latest/admin_manual/release_notes/upgrade_to_28.html#setup-checks).

Having that said, I am having since 29.0.7 (also tested on 29.0.8RC1) a red error message:
Your web server is not yet properly set up to allow file synchronization, because the WebDAV interface seems to be broken. To allow this check to run you have to make sure that your webserver can connect to itself. Therefor it must be able to resolve and connect to at least one its `trusted_domains` or the `overwrite.cli.url`.

I checked my config.php and actually I use a domain (no subfolder) with apache in the front.

### Steps to reproduce

1. Just check Security & setup warnings.

### Expected behavior

No warning or a more descriptive reason for the error.

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 28.0.1 to 28.0.2)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "my.domain.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "29.0.8.0",
        "overwrite.cli.url": "https:\/\/my.domain.org",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "BE",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "0"
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "maintenance_window_start": 2,
        "updater.release.channel": "beta"
    }
}
```
### List of activated Apps

I belive not relevant.

### Nextcloud Signing status

No errors have been found.

### Nextcloud Logs

No errors in the last days.

**Comment by joshtrichards** [comment]
What does the output of the following (executed from the server itself) return?

```
 curl -i -X PROPFIND https://my.domain.org/remote.php/webdav
```

It should be either a 401 or a 207.

**Comment by catarse-natural** [comment]
@joshtrichards I see a strange result since from outside and from the browser my certificate is perfectly valid issued by Let's Encrypt. 

```
curl -i -X PROPFIND https://nuvemd.duckdns.org/remote.php/webdav
curl: (60) SSL certificate problem: self signed certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

I did not find in the documentation any new requirements for how certificates should be generated. Am I missing something?

**Comment by joshtrichards** [comment]
Nextcloud doesn't have anything to do with certificate generation (nor HTTPs configuration) unless you're using an AIO deployment.

You'll have to debug your infrastructure. Perhaps post a query on the help forum - https://help.nextcloud.com

Wild guess: I have no idea where you're terminating your HTTPS, but make sure `my.domain` resolves to the same thing (DNS) when queried from your actual server where you ran the `curl` command as it does from the outside world.
