### ISSUE TITLE
[Bug]: Universal search shows "Mobile & desktop" even if the settings section is empty

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#48591]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The personal settings section "Mobile & desktop" (ID: `sync-clients`) is provided by the server, but only populated by apps like first run wizard or Talk. If there is not content, then this section will also not be shown. Now, when searching for "sync" in the universal search, this settings entry is shown in the results. Clicking on it brings the user to an empty page. Cf. screen recording.
https://github.com/user-attachments/assets/0864ef2a-e3e4-4f47-880c-7cc1dc888702

### Steps to reproduce

1. Make sure to have first run wizard and talk disabled
2. open universal search and look for "sync"
3. Clock on the "Mobile & desktop" result

### Expected behavior

The settings section is not presented in the search results when it does not have content.

### Nextcloud Server version

30

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by sorbaugh** [comment]
@Pytal could you take a look? 🙏
