### ISSUE TITLE
[Bug]: Image previews truncated

### ISSUE THREAD

**Issue by neunzehnachtneun** [nextcloud/server#48607]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi,
I am not quite sure, what causes this issue. I uploaded 200 jpg-images. While the previews are generated fine in most cases, some are truncated. I already tried regenerating the previews, but without access.

See https://cumulus.neunzehnachtneun.de/s/Ham3ztr7wDHwXz5

### Steps to reproduce

1. Upload lots of pictures
2. Open the folder
3. See some image previews truncated

### Expected behavior

Previews should show the whole image.

### Nextcloud Server version

30

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.neunzehnachtneun.de",
            "cirrus.neunzehnachtneun.de",
            "cumulus.neunzehnachtneun.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "debug": false,
        "installed": true,
        "maintenance": false,
        "overwrite.cli.url": "https:\/\/cirrus.neunzehnachtneun.de",
        "version": "30.0.0.14",
        "default_language": "en",
        "default_locale": "de_DE",
        "htaccess.RewriteBase": "\/",
        "knowledgebaseenabled": true,
        "lost_password_link": "disabled",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "simpleSignUpLink.shown": false,
        "cipher": "AES-256-CFB",
        "loglevel": 0,
        "logfile": "\/home\/neunzehn\/data\/nextcloud.log",
        "logtimezone": "Europe\/Berlin",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "calendar",
            "onlyoffice"
        ],
        "theme": "",
        "encryption.legacy_format_support": false,
        "default_phone_region": "DE"
    }
}

### List of activated Apps

Enabled:
  - activity: 3.0.0
  - bruteforcesettings: 3.0.0
  - calendar: 5.0.0
  - circles: 30.0.0-dev
  - cloud_federation_api: 1.13.0
  - contacts: 6.1.0
  - contactsinteraction: 1.11.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - nextcloud_announcements: 2.0.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - photos: 3.0.2
  - previewgenerator: 5.6.0
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - support: 2.0.0
  - survey_client: 2.0.0
  - tasks: 0.16.1
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - updatenotification: 1.20.0
  - viewer: 3.0.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - admin_audit: 1.20.0
  - comments: 1.20.1 (installed 1.20.1)
  - encryption: 2.18.0 (installed 2.9.0)
  - end_to_end_encryption: 1.16.1 (installed 1.16.1)
  - files_external: 1.22.0
  - mail: 4.0.1 (installed 4.0.1)
  - suspicious_login: 8.0.0
  - systemtags: 1.20.0 (installed 1.20.0)
  - twofactor_nextcloud_notification: 4.0.0
  - twofactor_totp: 12.0.0-dev
  - user_ldap: 1.21.0
  - user_status: 1.10.0 (installed 1.10.0)
  - weather_status: 1.10.0 (installed 1.10.0)

### Nextcloud Signing status

No errors have been found.

### Nextcloud Logs

{"reqId":"Zv6RH538r7N9IUfWVWwB9wAAAMA","level":3,"time":"2024-10-03T14:42:34+02:00","remoteAddr":"87.162.81.110","user":"sebastian","app":"PHP","method":"GET","url":"/core/preview?fileId=43871&x=32&y=32&mimeFallback=true&v=161837&a=0","message":"fwrite(): Write of 7548 bytes failed with errno=12 Cannot allocate memory at /var/www/virtual/neunzehn/html/lib/private/Log/File.php#58","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0","version":"30.0.0.14","data":{"app":"PHP"}}
{"reqId":"Zv6RH5gW9vb0jEGg8E6AiQAAAIg","level":3,"time":"2024-10-03T14:42:37+02:00","remoteAddr":"87.162.81.110","user":"sebastian","app":"PHP","method":"GET","url":"/core/preview?fileId=43947&x=32&y=32&mimeFallback=true&v=a33025&a=0","message":"fwrite(): Write of 10611 bytes failed with errno=12 Cannot allocate memory at /var/www/virtual/neunzehn/html/lib/private/Log/File.php#58","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0","version":"30.0.0.14","data":{"app":"PHP"}}
{"reqId":"Zv6RH5gW9vb0jEGg8E6AiAAAAJU","level":3,"time":"2024-10-03T14:42:38+02:00","remoteAddr":"87.162.81.110","user":"sebastian","app":"PHP","method":"GET","url":"/core/preview?fileId=44050&x=32&y=32&mimeFallback=true&v=09abe2&a=0","message":"fwrite(): Write of 435 bytes failed with errno=12 Cannot allocate memory at /var/www/virtual/neunzehn/html/lib/private/Log/File.php#58","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0","version":"30.0.0.14","data":{"app":"PHP"}}
{"reqId":"Zv6RH5gW9vb0jEGg8E6AigAAAJc","level":3,"time":"2024-10-03T14:42:38+02:00","remoteAddr":"87.162.81.110","user":"sebastian","app":"PHP","method":"GET","url":"/core/preview?fileId=44156&x=32&y=32&mimeFallback=true&v=46f0f8&a=0","message":"fwrite(): Write of 7548 bytes failed with errno=12 Cannot allocate memory at /var/www/virtual/neunzehn/html/lib/private/Log/File.php#58","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0","version":"30.0.0.14","data":{"app":"PHP"}}
{"reqId":"Zv6RLpgW9vb0jEGg8E6AoAAAAIQ","level":3,"time":"2024-10-03T14:42:59+02:00","remoteAddr":"87.162.81.110","user":"sebastian","app":"PHP","method":"GET","url":"/core/preview?fileId=44042&x=32&y=32&mimeFallback=true&v=26dd49&a=0","message":"file_get_contents(): Read of 1766 bytes failed with errno=14 Bad address at /var/www/virtual/neunzehn/html/lib/private/Preview/Generator.php#241","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:130.0) Gecko/20100101 Firefox/130.0","version":"30.0.0.14","data":{"app":"PHP"}}
{"reqId":"Zv6SdZgW9vb0jEGg8E6CjAAAAJE","level":3,"time":"2024-10-03T14:47:55+02:00","remoteAddr":"87.162.81.110","user":"--","app":"PHP","method":"GET","url":"/apps/files_sharing/publicpreview/cJxEX2LfitgCPgH?fileId=44186&file=%2F24-08-24%20-%20Jana%20Ralf%2099%20%5Brgb%5D%2FIMG_02-1P5A1190.jpg&c=bae904b17f4be55a8fd7246b55eb03dd&x=563&y=563","message":"fwrite(): Write of 675 bytes failed with errno=12 Cannot allocate memory at /var/www/virtual/neunzehn/html/lib/private/Log/File.php#58","userAgent":"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36 OPR/84.0.0.0","version":"30.0.0.14","data":{"app":"PHP"}}
{"reqId":"Zv6Sdvg7yo2SDa1XTDNHBgAAAEw","level":3,"time":"2024-10-03T14:48:04+02:00","remoteAddr":"87.162.81.110","user":"--","app":"PHP","method":"GET","url":"/apps/files_sharing/publicpreview/cJxEX2LfitgCPgH?fileId=44078&file=%2F24-08-24%20-%20Jana%20Ralf%2099%20%5Brgb%5D%2FIMG_06-1P5A1214.jpg&c=6881d0ae37d7830206b22719bed56208&x=563&y=563","message":"fwrite(): Write of 684 bytes failed with errno=12 Cannot allocate memory at /var/www/virtual/neunzehn/html/lib/private/Log/File.php#58","userAgent":"Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36 OPR/84.0.0.0","version":"30.0.0.14","data":{"app":"PHP"}}

**Comment by joshtrichards** [comment]
> `fwrite(): Write of 684 bytes failed with errno=12 Cannot allocate memory`

I don't think this is bug on this end (though anything is possible). Your server appears to have a memory constraint/utilization problem. Enough so that it's probably even running out of swap (or doesn't have any).

**Comment by solracsf** [comment]
See also these params:

https://github.com/nextcloud/server/blob/05886d281d4c9c9b980dc50eaf551f4c3b28b3ef/config/config.sample.php#L1284-L1303

**Comment by neunzehnachtneun** [comment]
Maybe you are right. Eventhough I am using nextcloud for five years on my uberspace, I never ran in issues like that.

In the end I found a workaround: I [regenerated all previews](https://github.com/nextcloud/previewgenerator) and also limited the size to 1024 pixels. Seems fine so far.
