### ISSUE TITLE
WebDav client `gvfs` get stuck at files/ in WebDav root with 405 Not Allowed

### ISSUE THREAD

**Issue by Sprinterfreak** [nextcloud/server#48602]
If for instance on Ubuntu, WebDav is used to access files directly on the Nextcloud server via gvfs, the mounted root will be /remote.php/dav/.
Only on first access, nautilus (the file explorer of gnome) goes to the full path like /remote.php/dav/files/user/. When the previously mounted share is navigated to again, nautilus will show the contents of /remote.php/dav/.

Unfortunately there is no way to get to the user's home at files/user/ again, because if You navigate into files/, the server will respond with 405 "Not Allowed".

There are two possible solutions, I can think of, to solve this issue:
- list the logged-in users folder in /remote.php/dav/files
- redirect the WebDav-Client from files/ to files/user/, instead of returning "Not Allowed"

**Comment by susnux** [comment]
This sounds more like a bug in gvfs, as you should be able to set the root directory (that is the path including the user) and then no requests should be made to some arbitrary parent of the root directory.

**Comment by joshtrichards** [comment]
Please provide precise reproduction steps. I use GNOME Files (Nautilus) daily and have never encountered this problem.

**Comment by Sprinterfreak** [comment]
@susnux  I don't think the fault is on gvfs's site. The mechanic behind it is, you always have to mount the root of a resource, before You can access files inside. I would agree on blaming the fault on people who decided to take away the address bar from nautilus.

@joshtrichards  Steps to reproduce: (Ubuntu)
Open nautilus, click on "+ Andere Orte" in the left navigation. A bar appears on the bottom stating "Mit Server verbinden".
Put in the url for webdav from Your nextcloud instance, replacing "https://" by "davs://" (davs://cloud.tld/remote.php/dav/files/user)
Nautilus mounts the share to `/run/user/1000/gvfs/dav\:host\=cloud.tld\,ssl\=true\,prefix\=%2Fremote.php%2Fdav/`in the background and initially navigates to the path inside the resource `files/user/`
If You then close the window or navigate anywhere else, open a new window or use the "save as" dialoge of any other application, then navigate into the still mounted share, You end up in the dav root from where You would have to navigate into files/user/ again. Which ends in 405 "Not allowed" at files/

**Comment by susnux** [comment]
> Nautilus mounts the share to `/run/user/1000/gvfs/dav\:host\=cloud.tld\,ssl\=true\,prefix\=%2Fremote.php%2Fdav/`in the background

I think this is the problem, the prefix should include the user.

> The mechanic behind it is, you always have to mount the root of a resource

Yes but the root here is the `dav/files/user/` there is no other root

**Comment by joshtrichards** [comment]
Still can't reproduce it, sorry. :)

Mine maintains the appropriate path. Here's the one generated from your reproduction steps (on Debian 12 for the record):

`'dav:host=nc-test.internal,port=4080,ssl=false,prefix=%2Fremote.php%2Fdav%2Ffiles%2Fncuser'`

**Comment by Sprinterfreak** [comment]
So here is the webserver access log.
```
1.2.3.4 - - [07/Oct/2024:23:09:40 +0200] "OPTIONS /remote.php/dav/files/user HTTP/1.1" 401 616 "-" "gvfs/1.44.1" "-"
1.2.3.4 - user [07/Oct/2024:23:09:41 +0200] "OPTIONS /remote.php/dav/files/user HTTP/1.1" 200 0 "-" "gvfs/1.44.1" "-"
1.2.3.4 - user [07/Oct/2024:23:09:41 +0200] "PROPFIND /remote.php/dav/files/user HTTP/1.1" 207 264 "-" "gvfs/1.44.1" "-"
1.2.3.4 - user [07/Oct/2024:23:09:41 +0200] "OPTIONS /remote.php/dav/files/ HTTP/1.1" 200 0 "-" "gvfs/1.44.1" "-"
1.2.3.4 - user [07/Oct/2024:23:09:41 +0200] "PROPFIND /remote.php/dav/files/ HTTP/1.1" 207 262 "-" "gvfs/1.44.1" "-"
1.2.3.4 - user [07/Oct/2024:23:09:42 +0200] "OPTIONS /remote.php/dav/ HTTP/1.1" 200 0 "-" "gvfs/1.44.1" "-"
1.2.3.4 - user [07/Oct/2024:23:09:42 +0200] "PROPFIND /remote.php/dav/ HTTP/1.1" 207 258 "-" "gvfs/1.44.1" "-"
1.2.3.4 - user [07/Oct/2024:23:09:42 +0200] "OPTIONS /remote.php/ HTTP/1.1" 404 4633 "-" "gvfs/1.44.1" "-"
1.2.3.4 - user [07/Oct/2024:23:09:42 +0200] "PROPFIND /remote.php/dav/files/user HTTP/1.1" 207 397 "-" "gvfs/1.44.1" "-"
1.2.3.4 - user [07/Oct/2024:23:09:42 +0200] "PROPFIND /remote.php/dav/files/user HTTP/1.1" 207 397 "-" "gvfs/1.44.1" "-"
1.2.3.4 - user [07/Oct/2024:23:09:42 +0200] "PROPFIND /remote.php/dav/files/user HTTP/1.1" 207 397 "-" "gvfs/1.44.1" "-"
1.2.3.4 - user [07/Oct/2024:23:09:42 +0200] "PROPFIND /remote.php/dav/files/user/Sync HTTP/1.1" 207 386 "-" "gvfs/1.44.1" "-"
1.2.3.4 - user [07/Oct/2024:23:09:42 +0200] "PROPFIND /remote.php/dav/files HTTP/1.1" 207 298 "-" "gvfs/1.44.1" "-"
1.2.3.4 - - [07/Oct/2024:23:09:43 +0200] "PROPFIND /remote.php/dav/ HTTP/1.1" 207 294 "-" "gvfs/1.44.1" "-"
1.2.3.4 - user [07/Oct/2024:23:09:43 +0200] "PROPFIND /remote.php/dav/files/user HTTP/1.1" 207 397 "-" "gvfs/1.44.1" "-"
1.2.3.4 - user [07/Oct/2024:23:09:43 +0200] "PROPFIND /remote.php/dav/files/user HTTP/1.1" 207 397 "-" "gvfs/1.44.1" "-"
```
Seems like gvfs devs are really proud of their new feature to traverse the resource, finding the root.
At least gvfs v1.44.1 probes the server, finding the best mode. This looks very deliberate, instead of a bug. I guess an issue in the gvfs community won't get very far. I'm pretty sure debian will also break in future releases when they catch up with more recent packages.

**Comment by Sprinterfreak** [comment]
Based on observations, I found a solution to hotfix this in my webserver config by
```
location = /remote.php/dav/files/ {
    return 404;
}
```
This breaks the service discovery gvfs automatically does, by overriding the 405 "Not Allowed" with 404 "Not Found".

**Comment by joshtrichards** [comment]
gvfs in Debian 12 is 1.50.3. :-)

I don't have time to look any closer tonight, but there look like a couple interesting items in the CHANGELOG >1.44.1:

https://gitlab.gnome.org/GNOME/gvfs/-/blob/master/NEWS

**Comment by susnux** [comment]
> Based on observations, I found a solution to hotfix this in my webserver config by
> 
> ```
> location = /remote.php/dav/files/ {
>     return 404;
> }
> ```
> 
> This breaks the service discovery gvfs automatically does, by overriding the 405 "Not Allowed" with 404 "Not Found".

So as said this seems like a gvfs bug, they should consider the 405 also an error to abort their "smart" detection.
If you enter a path they should consider that the root, if they do some "smart" things there they should handle all HTTP errors as errors and only consider the parent path.

**Comment by Sprinterfreak** [comment]
@susnux I also filed a bug there now. https://gitlab.gnome.org/GNOME/gvfs/-/issues/769

**Comment by Sprinterfreak** [comment]
Indeed this was a bug in older versions of gvfs and has allready been fixed.
There are of course still distros out there which don't have this pulled in yet.
