### ISSUE TITLE
[feature]: Add back `data-app-id` for app menu entries

### ISSUE THREAD

**Issue by Popyllol** [nextcloud/server#48645]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi nextcloud-team!

We use data-app-id for hiding menu items by CSS that could not be disabled as app like the _files_ app.
Before nextcloud 30 we could use the _data-app-id_ which seems to be gone.
We need any constant identifier over the versions to do our CSS magic.
So could you please readd it to the code?

Thank you
   Lars

### Steps to reproduce

nextcloud 29.* : 
       `<li data-v-62f74e6b="" data-app-id="files" class="app-menu-entry">...</li>`

upgrade to nextcloud: 30.0.0.14 :
     ` <li data-v-22dcd4f7="" data-v-7661a89b="" class="app-menu-entry">...</li>`

### Expected behavior

A constant identifier for menu items like before : `<li data-v-62f74e6b="" data-app-id="files" class="app-menu-entry">...</li>`

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.1

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

$ occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "30.0.0.14",
        "overwrite.cli.url": "https:\/\/kalender2020-0.unibw-hamburg.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance_window_start": 4,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "defaultEntity": "Helmut-Schmidt-Universit\u00e4t",
        "defaultName": "HSU",
        "defaultapp": "calendar",
        "defaultSlogan": "Cloud-Dienste unter Ihrer Kontrolle",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "loglevel": 0,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "theme": "",
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "auth.bruteforce.protection.enabled": "false",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "logfilemode": 416,
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 104857600,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "sort_groups_by_name": false,
        "tempdirectory": "\/var\/www\/tmp",
        "blacklisted_files": [
            ".htaccess"
        ],
        "cipher": "AES-256-CFB",
        "debug": false,
        "ldapUserCleanupInterval": 51,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "user_ldap.enable_medial_search": true,
        "skeletondirectory": "",
        "part_file_in_storage": true,
        "default_locale": "de_DE",
        "default_language": "de",
        "maintenance": false,
        "updatechecker": true,
        "updater.server.url": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "has_internet_connection": true,
        "data-fingerprint": "c2ecfd3cc03596e4fd43950daff35f4d",
        "proxy": "",
        "default_phone_region": "DE"
    }
}

### List of activated Apps

$ occ app:list
Enabled:
  - calendar: 5.0.0
  - cloud_federation_api: 1.13.0
  - contacts: 6.1.0
  - contactsinteraction: 1.11.0
  - dav: 1.31.1
  - event_update_notification: 2.5.0
  - federatedfilesharing: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - oauth2: 1.18.1
  - provisioning_api: 1.20.0
  - related_resources: 1.5.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - theming: 2.5.0
  - theming_customcss: 1.17.0
  - twofactor_backupcodes: 1.19.0
  - updatenotification: 1.20.0
  - user_ldap: 1.21.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0

**Comment by kesselb** [comment]
cc @nextcloud/server-frontend

**Comment by susnux** [comment]
This is not part of any public API, same with CSS classes. Internal HTML structure can change at any point.

You can current change the default app or the order of the app menu (so you can move the apps to the very end).
If that does not work for you could use the `href` attribute as selector, but this is similar dirty.

In general what is the use case? You can disable the apps for specific groups instead? Hiding it from the menu will still allow users to access the app.

**Comment by skjnldsv** [comment]
See https://github.com/nextcloud/server/issues/42328 and the closing comment.

Like @susnux said, not an official API, we cannot ensure it will not be removed at some point in the future (purposely or unpurposely anyway)

Closing

**Comment by Popyllol** [comment]
To answer the question even if you have closed this issue:
We use on different instances different parts of nextcloud and we have server where the fileservice is not wanted.
So we block /index.php/apps/files.* by rules in the webserver and until now we hide the files-button to not let the users run in the url which is denied. As you can't hide it by any app I know we hide it via CSS which worked fine for us until now.
I cannot understand why you cannot provide a static id to let people do some CSS magic.
Greetings,
   Lars

**Comment by susnux** [comment]
@Popyllol as said CSS classes are not stable, same with other selectors, they might exist or not.
But as a tip: For Nextcloud 30 you could use:

```css
.app-menu-entry:has(a[href*="apps/files"]) {
  display: none;
}
```

**Comment by Popyllol** [comment]
Thank you!
This works fine for me.
