### ISSUE TITLE
[Bug]: `[object Object]` show in place of headings on 'Your apps' page, app details panel, description tab

### ISSUE THREAD

**Issue by gerhardt-bergmann** [nextcloud/server#48661]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading from Nextcloud 29 to Nextcloud 30, the headings included in the `appinfo/info.xml` file, like `### Features`, `## Known issues`, etc. are rendered correctly on the app store page, as `<h3>`, `<h2>`, etc., but are rendered as '[object Object]' on 'Your apps' page, app details panel, description tab, as shown on the right side of this picture:

![Image](https://github.com/user-attachments/assets/9c2aadf7-87f5-4c4b-9ada-6a308bb311cf)

### Steps to reproduce

1. Install the Cospend app.
2. Click on your profile picture on the upper bar, choose 'Apps', on the left panel click on 'Your apps'.
3. On the 'Your apps' page click on 'Cospend', then, on the right hand slide-in panel, click on the 'Description' tab.

### Expected behavior

The first line of the description should read 'Nextcloud Cospend' and not '[object Object]'.

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Additional info

There are no log errors.

**Comment by Bestora** [comment]
![Image](https://github.com/user-attachments/assets/a0b3346c-e91d-42a1-b303-080229f2467d)
The Headings seems to be broken.

**Comment by Bestora** [comment]
The implementation of the markdown renderer and the docs of that library are different.
I changed that affected part, but found another one. 

![Image](https://github.com/user-attachments/assets/187e4125-0f17-41ac-a755-60f88682b649)
https://github.com/nextcloud/server/blob/7e99fd31eaef82abbed6d53de27de75752faf67a/apps/updatenotification/src/composables/useMarkdown.ts#L31

I'm still fresh to nextcloud, I can't find the usage of this one.

**Comment by TRIPLE-ADE** [comment]
can you assign this to me would love to work on it
