### ISSUE TITLE
Nextcloud and MariaDB/MySQL Supported versions page

### ISSUE THREAD

**Issue by Justinzobel** [nextcloud/server#48680]
https://github.com/nextcloud/server/wiki/Releases-and-PHP-versions is great to see what versions of PHP are supported by each version of Nextcloud, could this be duplicated to create a page for MariaDB/MySQL versions that are supported?

**Comment by joshtrichards** [comment]
It could be, but this stuff is all already covered in the docs: https://docs.nextcloud.com

Just creates more stuff to maintain/keep up-to-date/etc. :)

**Comment by Justinzobel** [comment]
> https://docs.nextcloud.com/

Anywhere specifically?

**Comment by joshtrichards** [comment]
https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html

**Comment by Justinzobel** [comment]
Thanks!
