### ISSUE TITLE
[feature request] Defend from crypto trojans

### ISSUE THREAD

**Issue by KB7777** [nextcloud/server#4868]
So, WannaCrypt is collecting now blood harvest.
Unfortunatelly there is no prevention utility with Nextcloud to defend from crypto trojans...

Yes, we have got history and versioning, but they are limited with quota range for users.

I have some ideas to defend from crypto trojans:

1. Exclude history and versioning files from users quota, moving it to new space; administrator should have to set it for some days, weeks, months maybe.
2. Allways keep at least one (last one) version of every file as was mention in this thread -- https://help.nextcloud.com/t/file-versioning-app-delete-question-ransomeware-protection/5059
3. After mass files changing notify client that maybe something strange is happen with the sync folder or files.
4. ....

It would be very secure to has the way to prevent data loss from such attacks.

EDIT: There is another "bug" with using File Access Control as a defender -- https://help.nextcloud.com/t/virus-encoder-and-nextcloud/10594

Regards.

**Comment by rullzer** [comment]
While I get the use case. I do not think there is any way in which we can do this right. 

To be fair if you want your data to be safe from this kind of trojans you should have a backup (and no Nextcloud is not a backup it is file sync and share :wink:). I recommend to have a backup even if there were no trojans.

If you have some incremental backup utility backups are fast and quick. And you make sure that a trojan can't just decrypt and delete your data.

**Comment by MorrisJobke** [comment]
> tacks.
> 
> EDIT: There is another "bug" with using File Access Control as a defender -- https://help.nextcloud.com/t/virus-encoder-and-nextcloud/10594

Please report this.


And as @rullzer said - detecting such stuff is really hard and can go horrible wrong. Just use offsite backups
