### ISSUE TITLE
Duplicate files in display after creation

### ISSUE THREAD

**Issue by xFaBx** [nextcloud/server#4869]
Hi, I think i've found a visualization problem.

### Steps to reproduce
1. click on an existing file
2. click on the "tab" sharing
3. add a txt file from the +

### Expected behaviour
One file created

### Actual behaviour
One file created but 2 visualized. After page reload the problem goes away.

### Server configuration

Shared Hosting

**Operating system**:
?
**Web server:**
Apache
**Database:**
SQlite3 3.8.10

**PHP version:**
5.6.28

**Nextcloud version:** (see Nextcloud admin page)
12b2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Both fresh and upgraded

**Where did you install Nextcloud from:**
Zipped sources

**Signing status:**

<details>
<summary>Signing status</summary>
No errors have been found.
*****but  .htaccess signature modified ****
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => '',
  ),
  'datadirectory' => '',
  'overwrite.cli.url' => '',
  'dbtype' => 'sqlite3',
  'version' => '12.0.0.18',
  'installed' => true,
  'integrity.check.disabled' => false,
  'htaccess.IgnoreFrontController' => false,
  'updater.release.channel' => 'beta',
  'mail_from_address' => '',
  'mail_smtpmode' => 'php',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_domain' => '',
);

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox, Chrome, Opera
**Operating system:** Windows 10

**Comment by josheliason** [comment]
Same duplicate file issue experienced in Nextcloud 12.0.0. After page reload there is only one file. Occurs in Chrome 60.0.3112.78, Firefox 54.0, and IE 11.0.9600.18738.

Steps to reproduce:
- create a text using the +, editor opens
- close editor
- click on newly created file, editor opens
- close editor
- same file shows twice in file system UI (see image)

![image](https://user-images.githubusercontent.com/15785483/28971194-ba7c496e-78f0-11e7-8be7-f0acc07d6628.png)

**Comment by MorrisJobke** [comment]
Please update to 12.0.2. We did some fixes for this problem. If this still happens we are happy to reopen this. Also existing files should be fixed during the upgrade.

**Comment by Buptle** [comment]
This error is reproduced in 12.0.3 with Korean file name link
filename : 파일이름.txt

English file name works fine.

![image](https://user-images.githubusercontent.com/12868014/31805158-99271a56-b599-11e7-8229-c7525ce3e430.png)
