### ISSUE TITLE
Nextcloud/ Server 

### ISSUE THREAD

**Issue by GGMONMINI** [nextcloud/server#48715]
# Nextcloud DevContainer

## Usage

Make sure you have the [VSCode DevContainer](https://code.visualstudio.com/docs/devcontainers/containers) extensions installed. If you open the project, VSCode will ask you if you want to open it inside of the DevContainer. If that's not the case, use <kbd>F1</kbd>&rarr;*Dev Containers: Open Folder in Container*.

Alternatively open the project directly in [GitHub Codespaces](https://github.com/features/codespaces).

That's already it. Everything else will be configured automatically by the Containers startup routine.

## Credentials

On first start the Container installs and configures Nextcloud with the following credentials:

**Nextcloud Admin Login**

Username: `admin` <br>
Password: `admin`

**Postgres credentials**

Username: `postgres` <br>
Password: `postgres` <br>
Database: `postgres`

## Services

The following services will be started:

| Service | Local port | Description |
|---------|------------|-------------|
| Nextcloud (served via Apache) | `80` | The main application |
| Mailhog | `8025` | SMTP email delivery for testing |
| Adminer | `8080` | Database viewer. Use credentials from above and connect to `localhost` to get access to the NC database | 

## Permissions

The container runs with the user `devcontainer` who is also running the Apache2 process. All mounted source files have
proper permissions so that this user can access everything which is inside the current workspace. If you need to
get root permissions for whatever reason, use `sudo su` or `sudo <command>` (for example `sudo service apache2 restart`).
Everything else (like building the application, adjusting files, ...) should be done as `devcontainer` user.

## NodeJs and NVM

The container comes with [`nvm`](https://github.com/nvm-sh/nvm) and Node 16 installed. This should be sufficient to
build Nextcloud Core sources via `make`. If you need a different Node Version (for example for
app development), you can easily switch between different versions by running:

```bash
# Install and use Node 14
nvm install 14
nvm use 14

# Check version 
node -v

# Switch back to Node 16
nvm use 16

# Check version
node -v
```

Note that `nvm` is only installed for the user `devcontainer` and won't work out of the box for
any other user.

## Debugging

The Apache webserver is already configured to automatically try to connect to a debugger process
listening on port `9003`. To start the VSCode debugger process, use the delivered debug profile `Listen for XDebug`.
After you started the VSCode debugger, just navigate to the appropriate Nextcloud URL to get your
debug hits.

**Comment by joshtrichards** [comment]
Did you mean to post this?

**Comment by GGMONMINI** [comment]
SoundCloud Go and SoundCloud DJ Terms of Use
https://soundcloud.com/go-terms-of-use

These SoundCloud Go and SoundCloud DJ Terms of Use (the "SoundCloud Go/DJ Terms") are in addition to, and are part of and are governed by, the SoundCloud Terms of Use (the "Terms of Use") together with our Community Guidelines and any other terms specifically referred to in any of those documents ("the Documents") and they are supported by our Privacy Policy and Cookies Policy. In the event of a conflict between these SoundCloud Go/DJ Terms and the Terms of Use, these SoundCloud Go/DJ Terms shall control only with respect to your use of SoundCloud Go and SoundCloud DJ. Capitalized terms used in these SoundCloud Go/DJ Terms not specifically defined in these SoundCloud Go/DJ Terms, shall have the meanings given to the applicable capitalized terms in the Terms of Use.

SoundCloud Go and SoundCloud DJ subscriptions
Certain features of the Platform are only available to registered users who purchase a SoundCloud Go or a SoundCloud Go+ subscription (“SoundCloud Go”) or a SoundCloud DJ subscription (“SoundCloud DJ”). These SoundCloud Go/DJ Terms provide a few additional terms that apply to the purchase of a SoundCloud Go subscription (a "Go Subscription"), the purchase of a SoundCloud Go+ subscription (a "Go+ Subscription") and a purchase of a SoundCloud DJ subscription (a “DJ Subscription”), and to Gift Codes related to it, including, among other things, terms relating to payment, the conclusion, renewal, switch and termination of your Go, Go+ or DJ Subscription, your right of withdrawal during the first 14 days of your Subscription, and certain technical usage limitations.

SoundCloud Go and DJ features and prices
A detailed description of SoundCloud Go and SoundCloud DJ, including the price and the features associated with it, is available on our SoundCloud Go and SoundCloud DJ landing page (the "landing page"). Please read this information in addition to the SoundCloud Go/DJ Terms and supporting Documents carefully. If you do not agree to, or understand, any of the provisions set out on the Landing Page, you should not purchase a SoundCloud Go, a SoundCloud Go+ or a DJ Subscription. All prices include VAT or other sales tax where applicable unless otherwise stated.

Purchase of SoundCloud Go and SoundCloud DJ
To purchase a SoundCloud Go, Go+ or DJ Subscription, simply select SoundCloud Go, Go+ or DJ, from the Landing Page on desktop or android, enter your payment details, and then click the purchase or, if applicable, the trial button. Please see the Term and Renewal as well as the Trials and Special Offers section below which states that fees will be automatically taken via your specified payment method on the expiry of the free trial period unless you cancel your trial Go, GO+ or DJ Subscription earlier.

Conclusion of contract and start of Go, Go+ or DJ Subscription
Selecting the plan and submitting your payment information is an offer to conclude a self-renewing contract with SoundCloud. If you sign up to receive a free trial Go, Go+ or DJ Subscription, or purchase a Go, Go+ or DJ Subscription, by clicking the purchase or trial button, you affirmatively acknowledge your agreement to these SoundCloud Go/DJ Terms, and you are agreeing to be bound by a self-renewing contract with SoundCloud for the purchase of the applicable Go, Go+ or DJ Subscription. You can review your purchase before clicking on the trial or purchase button. The contract itself is not concluded and the Go, Go+ or DJ Subscription is not effective until you receive confirmation from us via email or until we activate your Go, Go+ or DJ Subscription, which ever happens first. Once your payment has been received or in case of a Trial the payment information has been received and processed to verify validity of your payment information, your Go, Go+ or DJ Subscription will be activated, and we will send confirmation of your effective Go, Go+ or DJ Subscription with a copy of these SoundCloud Go/DJ Terms by email to the address associated with your account.

As noted above, the contract for your Go, Go+ or DJ Subscription is concluded when you receive our confirmation email, or when we activate the Go, Go+ or DJ Subscription, if this happens first, not when you make submit your payment information. Subject to availability, you may choose to select a different language to purchase a Go, Go+ or DJ Subscription by changing the language in the settings on the Platform.

Term and renewal
If you purchase a Go, Go+ or DJ Subscription, your Go, Go+ or DJ Subscription will be for a 30-day period, and your Go, Go+ or DJ Subscription will thereafter renew automatically for additional 30-day periods. SoundCloud will automatically charge your payment account the associated Go, Go+ or DJ Subscription fee on the date of commencement of each applicable 30-day renewal period, unless you cancel your Subscription before the applicable day of renewal. You can cancel your Go, Go+ or DJ Subscription at any time from the “SoundCloud Go” or “SoundCloud DJ” tab on your Subscriptions page on the Website. The date of renewal of your Go, Go+ or DJ Subscription is also displayed under the “SoundCloud Go” or “SoundCloud DJ” tab on your Go, Go+ or DJ Subscriptions page, so you can keep track of your Go, Go+ or DJ Subscription.

AUTOMATIC RENEWAL: AS STATED ABOVE, IF YOU DO NOT CANCEL YOUR GO, GO+ OR DJ SUBSCRIPTION PRIOR TO THE COMMENCEMENT OF AN APPLICABLE 30-DAY RENEWAL PERIOD, WE WILL AUTOMATICALLY CHARGE YOUR PAYMENT ACCOUNT AT THE BEGINNING OF EACH SUCCESSIVE 30-DAY PERIOD.

Payment
Fees for your Go, Go+ or DJ Subscription are payable in advance and will be charged at the time the contract is concluded or renewed as described above, except for applicable Trials. Payment can be made by Visa, Mastercard, American Express or PayPal and/or any other payment method that is presented to you during the purchase process. Your payment details and other information you choose to provide will be treated in accordance with our Privacy Policy. We only accept credit cards issued in territories where the Go, Go+ or DJ Subscription is available.

Purchasing a Go, Go+ or DJ Subscription in addition to your "Pro" or "Pro Unlimited" plan
If you already subscribe to a "Pro" or "Pro Unlimited" plan with SoundCloud, if you wish to purchase a SoundCloud Go, Go+ or DJ Subscription in addition to your “Pro” or “Pro Unlimited” plan, you may do so at any time from the Pro page on the Website. The account information associated with your “Pro” or “Pro Unlimited” plan will be used in connection with your Go, Go+ or DJ Subscription, however, the pricing and features associated with your Go, Go+ or DJ Subscription will run independently from your "Pro" or "Pro Unlimited" plan.

In-app purchase via the Apple App Store
If you subscribe to SoundCloud Go or Go+ via the SoundCloud In-App purchase, the terms and conditions of the Apple app store through which you make the purchase will apply with respect to your purchase, including the payment process and payment terms as well as your right to opt-out and cancel, as applicable.

Trials and special offers, advance payment
We may offer customers who purchase a Go, Go+ or DJ Subscription for the first time an option to use SoundCloud Go or SoundCloud DJ on a trial basis free of charge (a "Trial"), at a reduced price (“Special Offer”) or to pay for Go, Go+ or DJ Subscription periods in advance (“Advanced Payment”) (and each subject to additional terms and restrictions as may apply from time to time as indicated in connection with the offering). The offering provided in connection with a Trial may include the right to cancel the applicable Go, Go+ or DJ Subscription without being charged during the Trial period. In case of a Special Offer, the offering may include the right to cancel the applicable Go, Go+ or DJSubscription without being charged the regular Go, Go+ or DJ Subscription fee for the subsequent Go, Go+ or DJ Subscription period. In case of Advanced Payment for Go, Go+ or DJ Subscription periods, the offering may include the right to cancel the applicable Go, Go+ or DJ Subscription to the end of the Go, Go+ or DJ Subscription period(s), which were already paid without being charged the regular Go, Go+ or DJ Subscription fee for any subsequent Go, Go+ or DJ Subscription period.

However, any applicable cancellation must occur prior to the end of the respective Trial or Special Offer period. The Trial or Special Offer period, its terms and conditions as well as its availability will remain at all times at SoundCloud’s sole discretion. We may provide conditions for eligibility for a Trial or Special Offer and may ask you to provide us with your payment details in order to subscribe to a Trial or Special Offer, and we may require that you consent to be charged (regular) Go, Go+ or DJ Subscription fees if you do not cancel your Go, Go+ or DJ Subscription prior to the end of the Trial period or Special Offer period. You can cancel your Trial Go, Go+ or DJ Subscription or the Special Offer Go, Go+ or DJ Subscription by clicking the „Cancel Subscription“ button in the “SoundCloud Go” or “SoundCloud DJ” section of your Subscriptions page on the Website. If you do not cancel your Go, Go+ or DJ Subscription prior to the end of a Trial period or a Special Offer period, your Go, Go+ or DJ Subscription will automatically renew for consecutive 30-day periods, as described above, and Go, Go+ or DJ Subscription fees, as provided at the time of the Trial offering or such of the Special Offer, may be automatically charged to your specified payment account at the time the Go, Go+ or DJ Subscription is automatically renewed. For the avoidance of doubt, a Trial offer is limited to one SoundCloud Go and one SoundCloud Go+ and one SoundCloud DJ trial per user per year.

Additional terms and conditions may apply to Trial and Special Offers as indicated at the offering.

Upgrading and Downgrading between Subscriptions
You can upgrade or downgrade between a Go, Go+ and DJ Subscription at any time on your Subscriptions page on the Website or on the Subscriptions tab in your mobile apps. If you upgrade or downgrade you will immediately be charged the difference in price or you will immediately be refunded. This is determined based on how far you are into your initial Go, Go+ or DJ Subscription at the time you upgrade or downgrade. Your renewal date of your Go, Go+ or DJ Subscription will switch to the day you changed your Subscription. Any refund related to a change from a DJ to a Go+ or a Go+ to Go Subscription will go back to the payment method used at the time of your purchase of DJ or Go+. You will be entitled to use your new Go or Go+ or DJ Subscription immediately after you make the change. If you are in a Trial, you will only be able to upgrade from a SoundCloud Go 7-day trial to a SoundCloud Go+ or DJ 30-day trial. If you upgrade anytime within your 7-day SoundCloud Go trial period you will forfeit any remaining days in your 7-day trial period and start your new 30-day SoundCloud Go+ or DJ trial immediately. If you are in a Trial you will not be able to downgrade from a SoundCloud Go+ or SoundCloud DJ 30-day trial at any time. At the end of the Trial, you will be charged the renewal price for your subscription you switched to.

If you are an Apple device user and upgrade or downgrade your Go or Go+ Subscription via the SoundCloud In-App purchase, the terms and conditions of the Apple app store through which you make the purchase will apply. If you purchased your initial Go Subscription directly via SoundCloud (on web, mobile web or Android) but decide to upgrade to a Go+ Subscription on your iOS device via the Apple In-App purchase, your initial Go Subscription will end immediately. Any remaining term on it will not be redeemable or refundable by us. You will start an entirely new subscription via the Apple App Store. You will have immediate access to your new Go+ Subscription.

Right of withdrawal
In addition to Trial offers, under European law you also have a legal right to withdraw from your purchase of a SoundCloud Go, Go+ or DJ Subscription or a gift code within fourteen (14) days of your purchase, as set out below:

Model instructions on withdrawal
You have the right to withdraw from this contract within 14 days without giving any reason. The withdrawal period will expire after 14 days from the day of the conclusion of the contract.

To exercise the right of withdrawal, you must inform us

SoundCloud Global Limited & Co. KG, Rheinsberger Str. 76/77, 10115 Berlin, Germany
Fax: +49 30 577 098 860, contact@soundcloud.com
of your decision to withdraw from this contract by an unequivocal statement (e.g. a letter sent by post, fax or e-mail). You may use the attached model withdrawal form, but it is not obligatory. To meet the withdrawal deadline, it is sufficient for you to send your communication concerning your exercise of the right of withdrawal before the withdrawal period has expired.

Effects of withdrawal
If you withdraw from this contract, we will reimburse to you all payments received from you, including the costs of delivery (with the exception of the supplementary costs resulting from your choice of a type of delivery other than the least expensive type of standard delivery offered by us), without undue delay and in any event not later than 14 days from the day on which we are informed about your decision to withdraw from this contract. We will carry out such reimbursement using the same means of payment as you used for the initial transaction, unless you have expressly agreed otherwise; in any event, you will not incur any fees as a result of such reimbursement. If you requested to begin the performance of services during the withdrawal period, you shall pay us an amount which is in proportion to what has been provided until you have communicated us your withdrawal from this contract, in comparison with the full coverage of the contract.

The withdrawal procedures described above only apply to Go, Go+ or DJ Subscriptions that are purchased directly from SoundCloud. If you have purchased your Go, Go+ or DJ Subscription via an app store, please explicitly state so when you contact us and we will provide you with further details on how to claim your refund.

Following receipt of your notice of withdrawal, SoundCloud will downgrade your SoundCloud Go, Go+ or DJ Subscription to a free account. If you wish to delete your account altogether, you can do this from your Settings page on the Website.

Authorizations
We reserve the right to offer and provide access to SoundCloud Go or SoundCloud DJ in certain territories only. Whereas SoundCloud Go+ and SoundCloud DJ give you access to our full catalog, availability of Content for listening offline is subject to the respective permission of the applicable rights holder, which may be withheld by the applicable rights holder in its discretion. This is necessary to ensure protection of copyright of other user’s Content in accordance with the Terms of Use, e.g. when a user chooses to not make their Content available for listening offline. In addition, if you save any Content for offline listening, this Content will only be available to you during the term of your Go, Go+ or DJ Subscription and, following the cancellation or expiration of your Go, Go+ or DJ Subscription, any Content you have saved for offline listening may be deleted by SoundCloud in its discretion.

Use of your devices: usage limitations
In order to be able to provide you with the SoundCloud Go or SoundCloud DJ features, you authorize us to make use of the processing power and storage of the devices you use to log in to SoundCloud. Your Go, Go+ or DJ Subscription can be used on up to three different devices at a time, although streaming while you’re logged in is limited to one device at a time. Subject any applicable restrictions relating to offline saved Content, and provided that you limit your use of SoundCloud Go or SoundCloud DJ to three devices, you will be able to listen to any offline Content through all three devices but only through one at the same time. If you exceed this three device limit and try to log into SoundCloud Go or SoundCloud DJ via an additional device, we will provide you with the option to decide which of the devices will be authorized for your Go, Go+ or DJ Subscription. Access from non-authorized devices will be restricted. We will notify you in this case to ensure that your SoundCloud Go and SoundCloud DJ was accessed on that new device with your consent.

Please make sure to log in to your SoundCloud account at least once during each of your 30-day Go, Go+ or DJ Subscription periods to ensure your Collection remains available for offline listening on your device. Otherwise, Content you select for offline listening will be automatically removed from your device after 30 days.

SoundCloud Go and SoundCloud DJ are currently compatible with internet enabled computers and Android and iOS smartphones and iOS tablets. SoundCloud Go and SoundCloud DJ require a device running iOS8 (or later) or Android 4.40 (or later) operating system. Although we are working to ensure that SoundCloud Go and SoundCloud DJ are compatible across various devices, we cannot guarantee that they will work on all devices and it is your responsibility to ensure that you are able to comply with the relevant system requirements as described above or with respect to your SoundCloud DJ Subscription of the third party features as required by the third party product. Your use of SoundCloud Go and SoundCloud DJ and enjoyment of its features and content hosted or made available through it may vary in functionality, availability and quality depending on the type of device you use.

Our rights to terminate the contract
SoundCloud may suspend or terminate your Go, Go+ or DJ Subscription if SoundCloud determines, in its reasonable discretion, that you have repeatedly breached the SoundCloud Go/DJ Terms and/or the additional Documents. Please note we do not offer refunds to SoundCloud Go, Go+ or DJ Subscription holders whose accounts are terminated as a result of repeated infringement of the SoundCloud Go/DJ Terms and/or additional Documents. For more information please see the sections entitled “Repeat Infringers” and “Termination” in the SoundCloud Terms of Use.

SoundCloud also reserves the right to suspend your Go, Go+ or DJ Subscription in the event that we are prohibited from taking payment via the method specified in the “Payment” section. We will notify you of any failure to take payment and resultant suspension of your Go, Go+ or DJ Subscription. You must then provide an alternative and satisfactory payment method within seven days of notification of suspension. In the event that you do not provide a satisfactory payment method, SoundCloud reserves the right to terminate your Go, Go+ or DJ Subscription.

Changes to pricing and features
We may occasionally need to change the features made available with SoundCloud Go and SoundCloud DJ and/or change the price charged for your Go, Go+ or DJ Subscription or offer promotions. In the event of any increase in the price or material reduction in the features of your Go, Go+ or DJ Subscription, we will communicate these change(s) to you at least six (6) weeks in advance and the changes will only take effect with respect to any renewal of your Go, Go+ or DJ Subscription following the applicable six (6) week period. You can cancel your Go, Go+ or DJ Subscription prior to the effective date of the changes by clicking the "Cancel Subscription" button on the “SoundCloud Go” or “SoundCloud DJ” tab on your Subscriptions page on the Website. If you do not cancel your Go, Go+ or DJ Subscription prior to the applicable effective date of the changes, your Go, Go+ or DJ Subscription will be modified to reflect the applicable change to the SoundCloud Go or Soun
