### ISSUE TITLE
[Bug]: File list filter by "People" button localization issue

### ISSUE THREAD

**Issue by falghamdi125** [nextcloud/server#48733]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

FileListFilter translation does not get the `People` button translation from the correct source. 
Currently, the `files_sharing` app tries to get the account filter button from `files` app but the needed string is added to `files_sharing` locale files.

<img width="344" alt="image" src="https://github.com/user-attachments/assets/82c42af8-c4e1-4bd4-aa09-4e7ddac093c8">

### Steps to reproduce

1. Change the interface language to any language other than English.

### Expected behavior

Get the string for the designated locale file. 

### Nextcloud Server version

master

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by susnux** [comment]
Thank you for your report, I could reproduce it.

**Comment by falghamdi125** [comment]
Fix #48688
