### ISSUE TITLE
[Bug]: dns_get_record(): A temporary server error occurred. Nextcloud want SOA not the A Record

### ISSUE THREAD

**Issue by thejoe8495** [nextcloud/server#48742]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I searched weeks ago why my nextcloud is realy realy slow, i open the files tab and the Talk App.
Today i found it in this line:
https://github.com/nextcloud/server/blob/923ce7b93727edaba4509f605a270bc619479640/lib/private/Http/Client/DnsPinMiddleware.php#L41

I have no idea why nextcloud query the SOA record? 
I tried many linux distributations but every give me an error on this commands.

host -t SOA nextcloud.com
;; communications error to 8.8.8.8#53: timed out
;; communications error to 8.8.8.8#53: timed out
;; no servers could be reached

dig SOA nextcloud.com
;; communications error to 8.8.8.8#53: timed out
;; communications error to 8.8.8.8#53: timed out
;; communications error to 8.8.8.8#53: timed out

; <<>> DiG 9.18.28-1~deb12u2-Debian <<>> @10.10.10.1 SOA nextcloud.com
; (1 server found)
;; global options: +cmd
;; no servers could be reached

### Steps to reproduce

1. Share an folder per federate cloud link in your own cloud
2. open files in recieved cloud, the file listing takes long time about 30 seconds to 1 minute
3. in the systemlogs you find dns_get_record(): A temporary server error occurred. at /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#96
4. Change the DNS_SOA to DNS_A
5. open files in recieved cloud, the file listing takes unter 5 seconds

### Expected behavior

Quick loading ;)

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Logs

{"reqId":"KHKFq6m6hEpAJRxuwcx8","level":3,"time":"2024-10-16T21:01:10+00:00","remoteAddr":"x.x.x.x","user":"Joe","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/Joe/","message":"dns_get_record(): A temporary server error occurred. at /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#96","userAgent":"Mozilla/5.0 (Linux) mirall/3.11.0git (Nextcloud, linuxmint-6.8.0-45-generic ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"30.0.0.14","data":{"app":"PHP"}}
{"reqId":"KHKFq6m6hEpAJRxuwcx8","level":3,"time":"2024-10-16T21:01:20+00:00","remoteAddr":"x.x.x.x","user":"Joe","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/Joe/","message":"dns_get_record(): A temporary server error occurred. at /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#96","userAgent":"Mozilla/5.0 (Linux) mirall/3.11.0git (Nextcloud, linuxmint-6.8.0-45-generic ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"30.0.0.14","data":{"app":"PHP"}}
{"reqId":"VlUtgFqJ7PGLRvWzQjVk","level":3,"time":"2024-10-16T21:01:40+00:00","remoteAddr":"x.x.x.x","user":"Joe","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/Joe/","message":"dns_get_record(): A temporary server error occurred. at /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#96","userAgent":"Mozilla/5.0 (Linux) mirall/3.11.0git (Nextcloud, linuxmint-6.8.0-45-generic ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"30.0.0.14","data":{"app":"PHP"}}
{"reqId":"VlUtgFqJ7PGLRvWzQjVk","level":3,"time":"2024-10-16T21:01:50+00:00","remoteAddr":"x.x.x.x","user":"Joe","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/Joe/","message":"dns_get_record(): A temporary server error occurred. at /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#96","userAgent":"Mozilla/5.0 (Linux) mirall/3.11.0git (Nextcloud, linuxmint-6.8.0-45-generic ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"30.0.0.14","data":{"app":"PHP"}}

### Additional info

Change this line from DNS_SOA to DNS_A
https://github.com/nextcloud/server/blob/923ce7b93727edaba4509f605a270bc619479640/lib/private/Http/Client/DnsPinMiddleware.php#L41
I tried 4 server and a local installation of my laptop with mint, the latest test was an complete new installed debian server latest patches. All have the same long loading error.

**Comment by kesselb** [comment]
Thanks for your bug report 👍 

> I have no idea why nextcloud query the SOA record?

For the minimum ttl.

>  A temporary server error occurred.

That's an issue on your end, I'm not aware that we can do anything about it. 

`dig SOA nextcloud.com` and `dig SOA nextcloud.com @8.8.8.8` work fine over here and therefore something for your sysadmin to resolve.

**Comment by thejoe8495** [comment]
Sorry but i dont unterstand? You can't get an SOA entry for an subdomain. You can get only an SOA Entry for a Top Level Domain.
When you want to get cloud.nextcloud.com there will be never a SOA entry. So only toplevel domains work with this function.
And yes it can be that i to dumb to install all my server but additional the query is wrong.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/923ce7b93727edaba4509f605a270bc619479640/lib/private/Http/Client/DnsPinMiddleware.php#L35-L41
 
=> https://3v4l.org/ubfAp0#v8.3.12
