### ISSUE TITLE
Sabre\DAV\Exception\UnsupportedMediaType: HTTP/1.1 415 Validation error in iCalendar: ATTACH MUST NOT appear more than once in a VALARM component

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#4874]
On c.nc.c with @oparoz's calendar:

```
/var/www/html/3rdparty/sabre/dav/lib/CalDAV/Plugin.php - line 772: Sabre\CalDAV\Plugin->validateICalendar('BEGIN VCALENDAR...', 'calendars/olivi...', false, Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response), false)
[internal function] Sabre\CalDAV\Plugin->beforeWriteContent('calendars/olivi...', Object(OCA\DAV\CalDAV\CalendarObject), 'BEGIN VCALENDAR...', false)
/var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 1127: Sabre\Event\EventEmitter->emit('beforeWriteCont...', Array)
/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 513: Sabre\DAV\Server->updateFile('calendars/olivi...', 'BEGIN VCALENDAR...', NULL)
[internal function] Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method PUT', Array)
/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/html/apps/dav/lib/Server.php - line 245: Sabre\DAV\Server->exec()
/var/www/html/apps/dav/appinfo/v2/remote.php - line 33: OCA\DAV\Server->exec()
/var/www/html/remote.php - line 162: require_once('/var/www/html/a...')
{main}
```

> {"reqId":"mos7dqVkCSCcpuuI4nRg","level":4,"time":"2017-05-15T09:39:26+00:00","remoteAddr":"XXX","user":"olivier","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/calendars\/olivier\/vacations_shared_by_Nextcloud\/20170418T171142Z-4f2b412a84c9a52d.ics","message":"Exception: {\"Message\":\"HTTP\\\/1.1 415 Validation error in iCalendar: ATTACH MUST NOT appear more than once in a VALARM component\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\UnsupportedMediaType\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php(772): Sabre\\\\CalDAV\\\\Plugin->validateICalendar('BEGIN:VCALENDAR...', 'calendars\\\/olivi...', false, Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response), false)\\n#1 [internal function]: Sabre\\\\CalDAV\\\\Plugin->beforeWriteContent('calendars\\\/olivi...', Object(OCA\\\\DAV\\\\CalDAV\\\\CalendarObject), 'BEGIN:VCALENDAR...', false)\\n#2 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1127): Sabre\\\\Event\\\\EventEmitter->emit('beforeWriteCont...', Array)\\n#4 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->updateFile('calendars\\\/olivi...', 'BEGIN:VCALENDAR...', NULL)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#8 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Server.php(245): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#11 \\\/var\\\/www\\\/html\\\/remote.php(162): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#12 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/Plugin.php\",\"Line\":917,\"User\":\"olivier\"}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko\/20100101 Thunderbird\/45.8.0 Lightning\/4.7.8","version":"12.0.0.18"}

**Comment by enoch85** [comment]
Is this to any help maybe? https://github.com/nextcloud/contacts/issues/206

**Comment by georgehrke** [comment]
@MorrisJobke @rullzer 
I guess this is a general question we need to discuss:
- be very strict and return error messages when calendar data is incorrect
or
- be forgiving and also accept calendar (/addressbook data), thats parseable, but technically invalid

The latter will force us to revisit every manipulation / check of calendar data on the server, because certain presumptions we have now (because we are so strict), may not be the case when we are more forgiving.

**Comment by enoch85** [comment]
@georgehrke For Thunderbird I recommend Cardbook, I even think it's documented in the Nextcloud documentation.

**Comment by enoch85** [comment]
Yup it is: https://docs.nextcloud.com/server/12/user_manual/pim/sync_thunderbird.html

**Comment by georgehrke** [comment]
But this is about Lightning and CalDAV 😉
Also similar errors, as you pointed out, may occur for CardDAV.

**Comment by mfechner** [comment]
I see the same problem.
Get a calendar alarm display in Thunderbird and snooze it for one day, that next day it is displayed you cannot close it anymore.

**Comment by georgehrke** [comment]
@mfechner Please report this bug to Lightning. As the error report says, there is a validation error in the calendar data => Thunderbird is not sending valid ics data.

(Would be great if you could post a link to the mozilla bug tracker afterwards for reference.)

**Comment by danielkesselberg** [comment]
Why is this a lightning issue? 

> "ATTACH MUST NOT appear more than once in a VALARM" 

> Conformance: This property can be specified multiple times in a "VEVENT", "VTODO", "VJOURNAL", or "VALARM" calendar component

**Comment by georgehrke** [comment]
@danielkesselberg Please don't withhold the last part of the sentence:

```
  Conformance:  This property can be specified multiple times in a
      "VEVENT", "VTODO", "VJOURNAL", or "VALARM" calendar component with
      the exception of AUDIO alarm that only allows this property to
      occur once.
```

**Comment by danielkesselberg** [comment]
Ok. Just one more question. In VALARM attach should be allowed zero or n times right? https://github.com/nextcloud/3rdparty/blob/b995ca8b8c7f69a180ad6fb49989ad3e35b1367e/sabre/vobject/lib/Component/VAlarm.php#L137 but here is defined zero or once.

**Comment by skjnldsv** [comment]
Most likely.
Bug is closed, let's close here as well. Never seen this issue happening again so far.
