### ISSUE TITLE
[Bug]: Calendar: Rescheduling of meetings invited from Outlook not working

### ISSUE THREAD

**Issue by beyertom** [nextcloud/server#48741]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [ ] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I am experiencing an issue where **updates** to meetings sent from Outlook to Nextcloud do not reflect in the Nextcloud calendar entry

### Steps to reproduce

1. Create a meeting in an external Outlook/Exchange account and invite a Nextcloud email address (e.g., Sunday at 13:00).
2. Accept the meeting in Nextcloud via the Mail App by clicking the “Accept” button.
3. A message appears in the Mail App stating, “You accepted this invitation.”
4. The meeting is successfully scheduled for Sunday at 13:00 in the Nextcloud Calendar App.
5. Update the meeting time in the external Outlook/Exchange account to, for example, Saturday at 14:00.
6. An email arrives in the Nextcloud Mail App, but it does not provide an “Accept Invite” button. Instead, it immediately states, “You accepted this invitation.”
7. The meeting remains scheduled for Sunday at 13:00 in the Nextcloud Calendar App.

### Expected behavior

At step 6, the email should indicate that this is an update to an existing meeting. You will have two options:

Accept: This will update the meeting in your calendar to Saturday at 13:00.
Decline: This will delete the meeting from your calendar.

### Nextcloud Server version

30

### Operating system

Other

### PHP engine version

PHP 8.3

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report
```json
{
    "system": {
        "apps_paths": [
            {
                "path": "\/nix\/store\/1rpzv4bkyym74wj5pkbf0say7kjgbndq-nextcloud-30.0.0-with-apps\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/nix\/store\/1rpzv4bkyym74wj5pkbf0say7kjgbndq-nextcloud-30.0.0-with-apps\/nix-apps",
                "url": "\/nix-apps",
                "writable": false
            },
            {
                "path": "\/nix\/store\/1rpzv4bkyym74wj5pkbf0say7kjgbndq-nextcloud-30.0.0-with-apps\/store-apps",
                "url": "\/store-apps",
                "writable": true
            }
        ],
        "appstoreenabled": false,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "log_type": "syslog",
        "loglevel": 2,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "profile.enabled": false,
        "default_phone_region": "DE",
        "maintenance_window_start": 1,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "version": "30.0.0.14",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "maintenance": false,
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ]
    }
}
```

### List of activated Apps
```
Enabled:
  - activity: 3.0.0
  - bruteforcesettings: 3.0.0
  - calendar: 5.0.0
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contacts: 6.1.0
  - contactsinteraction: 1.11.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - federatedfilesharing: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - lookup_server_connector: 1.18.0
  - mail: 4.0.1
  - nextcloud_announcements: 2.0.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - support: 2.0.0
  - systemtags: 1.20.0
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - updatenotification: 1.20.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - admin_audit: 1.20.0
  - circles: 30.0.0-dev (installed 28.0.0-dev)
  - encryption: 2.18.0
  - federation: 1.20.0 (installed 1.18.0)
  - files_external: 1.22.0
  - logreader: 3.0.0 (installed 2.13.0)
  - photos: 3.0.2 (installed 2.4.0)
  - survey_client: 2.0.0 (installed 1.16.0)
  - suspicious_login: 8.0.0
  - twofactor_nextcloud_notification: 4.0.0
  - twofactor_totp: 12.0.0-dev
  - user_ldap: 1.21.0
```

### Nextcloud Signing status

No errors have been found.

### Additional info

I posted this topic also to the community forum, but i think its a bug, therefore here is the better place: https://help.nextcloud.com/t/calendar-rescheduling-of-meetings-invited-from-outlook-not-working/206850

**Comment by kesselb** [comment]
cc @miaulalala @st3iny @SebastianKrupinski

**Comment by kesselb** [comment]
Thanks for your report 👍 

Your case sounds like https://github.com/nextcloud/mail/issues/8458. 

This should be resolved by https://github.com/nextcloud/server/pull/47826 and https://github.com/nextcloud/mail/pull/10116 with one of the upcoming releases of Nextcloud then.

**Comment by beyertom** [comment]
Thank you very for the quick response. As its already covered by the other tickets, should I close this one?

**Comment by SebastianKrupinski** [comment]
Resolved: https://github.com/nextcloud/mail/pull/10116
