### ISSUE TITLE
[Bug]: Fatal error, Uncaught Error due to guzzlehttp

### ISSUE THREAD

**Issue by benginoe** [nextcloud/server#48768]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Nextcloud doesnt work due to "Fatal error: Uncaught Error: Failed opening required '/var/www/vhosts/XXXXXXX/httpdocs/3rdparty/composer/../guzzlehttp/promises/src/functions_include.php'" respectively:  "Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Package operations: 1 install, 0 updates, 0 removals
  - Installing bamarni/composer-bin-plugin (1.8.2): Extracting archive
Generating optimized autoload files
Class FeedBackHandler located in ./core/ajax/update.php does not comply with psr-4 autoloading standard (rule: OC\Core\ => ./core). Skipping.
> [ $COMPOSER_DEV_MODE -eq 0 ] || composer bin all install
[bamarni-bin] Could not find any bin namespace.
> composer dump-autoload --no-dev
Generating optimized autoload files
Class FeedBackHandler located in ./core/ajax/update.php does not comply with psr-4 autoloading standard (rule: OC\Core\ => ./core). Skipping.
Generated optimized autoload files containing 2002 classes"

### Steps to reproduce

1. Upgraded to 30, error already occured, tried to upgrade to 30.0.1, error still exists

### Expected behavior

No fatal error and normal loading of Nextcloud.

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by joshtrichards** [comment]
> Upgraded to 30, error already occured, tried to upgrade to 30.0.1, error still exists

Upgraded how? Where/when are you seeing these errors?

Also what installation method?

**Comment by benginoe** [comment]
Upgrade via shell, but also when I want to clean install from zip. 

I see the errors whenever i try to access the frontend, the other one is with "composer install"

**Comment by joshtrichards** [comment]
Please be precise. What commands?

There is no method of installing or upgrading Nextcloud that involves using composer.

**Comment by benginoe** [comment]
Upgrade with "updater.phar --no-backup" 

the composer thing was just to try to fix the issue by my-self, but didnt work.

**Comment by joshtrichards** [comment]
Please post on the help forum to get some assistance with troubleshooting your installation/setup:

https://help.nextcloud.com

**Comment by benginoe** [comment]
Issue could be resolved and should be not relevant for 30.0.1, sorry for inconvenience!!!!

**Comment by benginoe** [comment]
Issue could be resolved and should be not relevant for 30.0.1, sorry for inconvenience!!!!
