### ISSUE TITLE
[Bug]: Can't create / delete tags

### ISSUE THREAD

**Issue by intervisionlord** [nextcloud/server#48761]
I was forced to re-create the topic because the problem was not solved and no one wanted to re-open the previous topic.

#46365

**Comment by joshtrichards** [comment]
What version of Nextcloud Server? I can't reproduce this.

**Comment by intervisionlord** [comment]
> What version of Nextcloud Server? I can't reproduce this.

29.0.7 for now

![Image](https://github.com/user-attachments/assets/436f258c-6fb3-461d-8419-0e8c8e079425)

**Comment by joshtrichards** [comment]
I don't see a problem. That isn't where you create or edit tags.

**Comment by intervisionlord** [comment]
> That isn't where you create or edit tags.

What do you mean?

**Comment by joshtrichards** [comment]
What part of the screenshot you posted is demonstrating a bug?

**Comment by intervisionlord** [comment]
> What part of the screenshot you posted is demonstrating a bug?

This is "Files" -> left menu -> Tags

**Comment by intervisionlord** [comment]
> I understand. But what do you think is a bug about it? The tags are shown, correct?
> 
> Tags are managed (set/created/deleted) by going to:
> 
> * _Details_ / the sidebar on individual files/folders and selecting the 3-dot menu
> * _Administration Settings->Basic settings_

This is where the problem lies - in the interface.

The presence of the "Add" button in the tags section gives a false assumption that a new tag can be added from here.
And the error that this button displays about insufficient rights is confusing - why are there no rights to add tags.

It turns out that this button does not apply to tags, but to files, but it is difficult to guess either because of the interface problem or because the tag management is logically located in the files section.
