### ISSUE TITLE
[Bug]: Alot of FILE_MISSING with `bamarni/composer-bin-plugin`

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#48773]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After a fresh install of Nextcloud 30.0.1 I get this: https://pastebin.com/XUMg1uwe

### Steps to reproduce

1. Install Nextcloud with the Nextcloud VM scripts
2. Choose defaults
3. Login and run the setup check

### Expected behavior

No errors since the VM only does everything with `./occ`.

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "10.100.99.107",
            "nextcloud",
            "90.230.110.139"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "30.0.1.2",
        "overwrite.cli.url": "https:\/\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "0",
            "dbindex": "0",
            "timeout": "0.5",
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "upgrade.disable-web": true,
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": "2",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "maintenance_window_start": 2,
        "mail_smtpmode": "smtp",
        "remember_login_cookie_lifetime": "1800",
        "log_rotate_size": "10485760",
        "trashbin_retention_obligation": "auto, 60",
        "versions_retention_obligation": "auto, 180",
        "activity_expire_days": "120",
        "simpleSignUpLink.shown": false,
        "default_phone_region": "se",
        "logtimezone": "Europe\/Stockholm",
        "htaccess.RewriteBase": "\/",
        "preview_concurrency_new": "4",
        "preview_concurrency_all": "8",
        "enabledPreviewProviders": [
            "OC\\Preview\\Imaginary",
            "OC\\Preview\\Image",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\Movie",
            "OC\\Preview\\Krita",
            "OC\\Preview\\ImaginaryPDF"
        ],
        "preview_imaginary_url": "***REMOVED SENSITIVE VALUE***",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "preview_max_memory": "256",
        "maintenance": false
    }
}

### List of activated Apps

Enabled:
  - activity: 3.0.0
  - admin_audit: 1.20.0
  - app_api: 4.0.0
  - bruteforcesettings: 3.0.0
  - calendar: 5.0.1
  - circles: 30.0.0-dev
  - cloud_federation_api: 1.13.0
  - collectives: 2.14.4
  - comments: 1.20.1
  - contacts: 6.1.0
  - contactsinteraction: 1.11.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - deck: 1.14.1
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - mail: 4.0.2
  - nextcloud_announcements: 2.0.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - photos: 3.0.2
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - support: 2.0.0
  - survey_client: 2.0.0
  - systemtags: 1.20.0
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - updatenotification: 1.20.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - encryption: 2.18.0
  - extract: 1.3.6
  - files_external: 1.22.0
  - suspicious_login: 8.0.0
  - twofactor_nextcloud_notification: 4.0.0
  - twofactor_totp: 12.0.0-dev
  - user_ldap: 1.21.0

### Nextcloud Signing status

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.
 
Results
=======
- suspicious_login
    - FILE_MISSING
        - vendor/bamarni/composer-bin-plugin/.makefile/touch.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario0/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario1/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario10/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario11/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario12/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario2/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario3/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario5/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario6/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario7/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario8/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario9/script.sh
        - vendor/rubix/tensor/.github/workflows/ci-ext.sh
- photos
    - FILE_MISSING
        - build-js/npm-post-build.sh
- deck
    - FILE_MISSING
        - .devcontainer/setup.sh
- mail
    - FILE_MISSING
        - l10n/preproc.sh
        - vendor/bamarni/composer-bin-plugin/.makefile/touch.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario0/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario1/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario10/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario11/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario12/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario2/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario3/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario5/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario6/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario7/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario8/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario9/script.sh
- calendar
    - FILE_MISSING
        - vendor/bamarni/composer-bin-plugin/.makefile/touch.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario0/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario1/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario10/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario11/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario12/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario2/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario3/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario5/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario6/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario7/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario8/script.sh
        - vendor/bamarni/composer-bin-plugin/e2e/scenario9/script.sh
- twofactor_nextcloud_notification
    - FILE_MISSING
        - build-js/npm-post-build.sh
- collectives
    - FILE_MISSING
        - vendor/predis/predis/docker/unstable_cluster/create_cluster.sh
- recommendations
    - FILE_MISSING
        - build-js/npm-post-build.sh
- files_pdfviewer
    - FILE_MISSING
        - build-js/npm-post-build.sh
- related_resources
    - FILE_MISSING
        - build/npm-post-build.sh
 
Raw output
==========
Array
(
    [suspicious_login] => Array
        (
            [FILE_MISSING] => Array
                (
                    [vendor/bamarni/composer-bin-plugin/.makefile/touch.sh] => Array
                        (
                            [expected] => d28bd83c3e865caca37e54b29e3a07879fb02e1780c4c344c6a498591fc11ceb3e927f160728811797f9fa8c7695696b169ee16cfdbe5c58568367cc4c353010
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario0/script.sh] => Array
                        (
                            [expected] => 5ccb610fe2c0c10d41e1ddb08ba733f0335935c3d78eff8b08fddb5897b0ba024de21ffa57244452569d67cee199a5998a607fc922a551e1e4d307082e2f214c
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario1/script.sh] => Array
                        (
                            [expected] => 6341889bb4ac7db801493b3a70498596c337b59786c91fa5630ebcb5e637764843c24e530b8bb258938115614b0777d642941c9e32b04b763584e37613d73459
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario10/script.sh] => Array
                        (
                            [expected] => 86b27023fd07647739764221036a778b86ca62a666eeba07a85a89aa3471ca5e7e3e9dce02356359b7485907600612ebd5821aade3acdbfd8c4bb03b8d3d74d3
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario11/script.sh] => Array
                        (
                            [expected] => 4a10e2b8829ddc18254be14793cb8f2795123effce00a2bebbd981e4a1f1a0dd6710bdce39bf6f1807508339382bbad49f7250cc0aa14c661b0a2b8e4bb6a39c
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario12/script.sh] => Array
                        (
                            [expected] => 53d6501288006412a99570caecfaaf83e2347d70be1e81665a70c3bcc056e487b5cd9a744c71425b91112e8bc85029d473552f59cc9fec98aeb9103069f8bb6e
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario2/script.sh] => Array
                        (
                            [expected] => 04a2fe8b4ca90b7a575e02959f8d48fd2b81fd95588ce53ef6fc5f351fb3a6184c5d25ee1d84fc0944e0e8bb0d16731ccb379857e25df2720979f8a0de2852f3
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario3/script.sh] => Array
                        (
                            [expected] => c34adbe363bb5462b207b10844d1f43d22986cfe521314224d8bea50cc23c770fee7b1601e0926d8a0877b075a2e98cdb3f73094d1e49bee6efcd03ef77872ff
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario5/script.sh] => Array
                        (
                            [expected] => 9160730cb306f99beac21ee9941abf1e6d6320005295e5c5658e6897625bb9fd7a47775fa62792e05376a7e89c2a2416b5941c2f66308acd258fb013faea496c
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario6/script.sh] => Array
                        (
                            [expected] => 10a84109f284d4dd0d3ae999efb429a977421a0f33048a63ca3c2b1bd8243414e4371a44958ff8d24e48376ce17f9203ebeccaff1d33a51eb833403e85a2b46d
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario7/script.sh] => Array
                        (
                            [expected] => 9fc9f67633c7d09f2b9605216f0d672eca8c0ed8f9ab824eb2cb164b76a53bfe7857a3b8a679e31a9a8a4a39a01497ee18b95190dd481a45b00dbac55ec5cac2
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario8/script.sh] => Array
                        (
                            [expected] => cd473f273a143ce08a8928f1040ad213a4f6b130d9d75ddf14ab6fc0fa4c6d1e41883f716267c0e8d5975f817d5074788a25ec9e85808425f1fa92ec210bb266
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario9/script.sh] => Array
                        (
                            [expected] => f636569c0ca7a5951b1d686b881ef45125221c2abf6b2b82fe945c5652852f9be37419ffc7e51ca8a63e516f80a5c259a37a780daa44e8aecf2b949b0af91078
                            [current] => 
                        )
 
                    [vendor/rubix/tensor/.github/workflows/ci-ext.sh] => Array
                        (
                            [expected] => 9b6cb083482b92051b69b5eafbb6444706592b97e7da40f8db7d4e0a9d09b22e7b0bdfcdd9a735d2e8449b31dbb27ccbc2cee57ab5bc26f2de8e35a6534175c7
                            [current] => 
                        )
 
                )
 
        )
 
    [photos] => Array
        (
            [FILE_MISSING] => Array
                (
                    [build-js/npm-post-build.sh] => Array
                        (
                            [expected] => f4d96811c6b081ce2301f12abbbd07e392c4992cba1f2e44705367caae3d8fd95cacf47b8a3c85a20f30c20fa64faa8c61ba57da7230a0fabda88ba088f2229a
                            [current] => 
                        )
 
                )
 
        )
 
    [deck] => Array
        (
            [FILE_MISSING] => Array
                (
                    [.devcontainer/setup.sh] => Array
                        (
                            [expected] => 0057fa2521c9445d11f0c56a83a75eb170e9e9152ab77c95b28eaa3ecaafbdd4ca87e3c129b39f4128106083230a6a80ffcc05f8b3e31f8c1446b22ada711ea5
                            [current] => 
                        )
 
                )
 
        )
 
    [mail] => Array
        (
            [FILE_MISSING] => Array
                (
                    [l10n/preproc.sh] => Array
                        (
                            [expected] => bb803c9955991be2acf6fb955673e4e19aa04d9b27a8e780cf5a92a2fe94dcd3bc15772ddb10197422e7247596a2546828f093848efd8c69d387d5b356604616
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/.makefile/touch.sh] => Array
                        (
                            [expected] => d28bd83c3e865caca37e54b29e3a07879fb02e1780c4c344c6a498591fc11ceb3e927f160728811797f9fa8c7695696b169ee16cfdbe5c58568367cc4c353010
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario0/script.sh] => Array
                        (
                            [expected] => 5ccb610fe2c0c10d41e1ddb08ba733f0335935c3d78eff8b08fddb5897b0ba024de21ffa57244452569d67cee199a5998a607fc922a551e1e4d307082e2f214c
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario1/script.sh] => Array
                        (
                            [expected] => 6341889bb4ac7db801493b3a70498596c337b59786c91fa5630ebcb5e637764843c24e530b8bb258938115614b0777d642941c9e32b04b763584e37613d73459
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario10/script.sh] => Array
                        (
                            [expected] => 86b27023fd07647739764221036a778b86ca62a666eeba07a85a89aa3471ca5e7e3e9dce02356359b7485907600612ebd5821aade3acdbfd8c4bb03b8d3d74d3
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario11/script.sh] => Array
                        (
                            [expected] => 4a10e2b8829ddc18254be14793cb8f2795123effce00a2bebbd981e4a1f1a0dd6710bdce39bf6f1807508339382bbad49f7250cc0aa14c661b0a2b8e4bb6a39c
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario12/script.sh] => Array
                        (
                            [expected] => 53d6501288006412a99570caecfaaf83e2347d70be1e81665a70c3bcc056e487b5cd9a744c71425b91112e8bc85029d473552f59cc9fec98aeb9103069f8bb6e
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario2/script.sh] => Array
                        (
                            [expected] => 04a2fe8b4ca90b7a575e02959f8d48fd2b81fd95588ce53ef6fc5f351fb3a6184c5d25ee1d84fc0944e0e8bb0d16731ccb379857e25df2720979f8a0de2852f3
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario3/script.sh] => Array
                        (
                            [expected] => c34adbe363bb5462b207b10844d1f43d22986cfe521314224d8bea50cc23c770fee7b1601e0926d8a0877b075a2e98cdb3f73094d1e49bee6efcd03ef77872ff
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario5/script.sh] => Array
                        (
                            [expected] => 9160730cb306f99beac21ee9941abf1e6d6320005295e5c5658e6897625bb9fd7a47775fa62792e05376a7e89c2a2416b5941c2f66308acd258fb013faea496c
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario6/script.sh] => Array
                        (
                            [expected] => 10a84109f284d4dd0d3ae999efb429a977421a0f33048a63ca3c2b1bd8243414e4371a44958ff8d24e48376ce17f9203ebeccaff1d33a51eb833403e85a2b46d
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario7/script.sh] => Array
                        (
                            [expected] => 9fc9f67633c7d09f2b9605216f0d672eca8c0ed8f9ab824eb2cb164b76a53bfe7857a3b8a679e31a9a8a4a39a01497ee18b95190dd481a45b00dbac55ec5cac2
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario8/script.sh] => Array
                        (
                            [expected] => cd473f273a143ce08a8928f1040ad213a4f6b130d9d75ddf14ab6fc0fa4c6d1e41883f716267c0e8d5975f817d5074788a25ec9e85808425f1fa92ec210bb266
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario9/script.sh] => Array
                        (
                            [expected] => f636569c0ca7a5951b1d686b881ef45125221c2abf6b2b82fe945c5652852f9be37419ffc7e51ca8a63e516f80a5c259a37a780daa44e8aecf2b949b0af91078
                            [current] => 
                        )
 
                )
 
        )
 
    [calendar] => Array
        (
            [FILE_MISSING] => Array
                (
                    [vendor/bamarni/composer-bin-plugin/.makefile/touch.sh] => Array
                        (
                            [expected] => d28bd83c3e865caca37e54b29e3a07879fb02e1780c4c344c6a498591fc11ceb3e927f160728811797f9fa8c7695696b169ee16cfdbe5c58568367cc4c353010
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario0/script.sh] => Array
                        (
                            [expected] => 5ccb610fe2c0c10d41e1ddb08ba733f0335935c3d78eff8b08fddb5897b0ba024de21ffa57244452569d67cee199a5998a607fc922a551e1e4d307082e2f214c
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario1/script.sh] => Array
                        (
                            [expected] => 6341889bb4ac7db801493b3a70498596c337b59786c91fa5630ebcb5e637764843c24e530b8bb258938115614b0777d642941c9e32b04b763584e37613d73459
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario10/script.sh] => Array
                        (
                            [expected] => 86b27023fd07647739764221036a778b86ca62a666eeba07a85a89aa3471ca5e7e3e9dce02356359b7485907600612ebd5821aade3acdbfd8c4bb03b8d3d74d3
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario11/script.sh] => Array
                        (
                            [expected] => 4a10e2b8829ddc18254be14793cb8f2795123effce00a2bebbd981e4a1f1a0dd6710bdce39bf6f1807508339382bbad49f7250cc0aa14c661b0a2b8e4bb6a39c
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario12/script.sh] => Array
                        (
                            [expected] => 53d6501288006412a99570caecfaaf83e2347d70be1e81665a70c3bcc056e487b5cd9a744c71425b91112e8bc85029d473552f59cc9fec98aeb9103069f8bb6e
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario2/script.sh] => Array
                        (
                            [expected] => 04a2fe8b4ca90b7a575e02959f8d48fd2b81fd95588ce53ef6fc5f351fb3a6184c5d25ee1d84fc0944e0e8bb0d16731ccb379857e25df2720979f8a0de2852f3
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario3/script.sh] => Array
                        (
                            [expected] => c34adbe363bb5462b207b10844d1f43d22986cfe521314224d8bea50cc23c770fee7b1601e0926d8a0877b075a2e98cdb3f73094d1e49bee6efcd03ef77872ff
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario5/script.sh] => Array
                        (
                            [expected] => 9160730cb306f99beac21ee9941abf1e6d6320005295e5c5658e6897625bb9fd7a47775fa62792e05376a7e89c2a2416b5941c2f66308acd258fb013faea496c
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario6/script.sh] => Array
                        (
                            [expected] => 10a84109f284d4dd0d3ae999efb429a977421a0f33048a63ca3c2b1bd8243414e4371a44958ff8d24e48376ce17f9203ebeccaff1d33a51eb833403e85a2b46d
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario7/script.sh] => Array
                        (
                            [expected] => 9fc9f67633c7d09f2b9605216f0d672eca8c0ed8f9ab824eb2cb164b76a53bfe7857a3b8a679e31a9a8a4a39a01497ee18b95190dd481a45b00dbac55ec5cac2
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario8/script.sh] => Array
                        (
                            [expected] => cd473f273a143ce08a8928f1040ad213a4f6b130d9d75ddf14ab6fc0fa4c6d1e41883f716267c0e8d5975f817d5074788a25ec9e85808425f1fa92ec210bb266
                            [current] => 
                        )
 
                    [vendor/bamarni/composer-bin-plugin/e2e/scenario9/script.sh] => Array
                        (
                            [expected] => f636569c0ca7a5951b1d686b881ef45125221c2abf6b2b82fe945c5652852f9be37419ffc7e51ca8a63e516f80a5c259a37a780daa44e8aecf2b949b0af91078
                            [current] => 
                        )
 
                )
 
        )
 
    [twofactor_nextcloud_notification] => Array
        (
            [FILE_MISSING] => Array
                (
                    [build-js/npm-post-build.sh] => Array
                        (
                            [expected] => f4d96811c6b081ce2301f12abbbd07e392c4992cba1f2e44705367caae3d8fd95cacf47b8a3c85a20f30c20fa64faa8c61ba57da7230a0fabda88ba088f2229a
                            [current] => 
                        )
 
                )
 
        )
 
    [collectives] => Array
        (
            [FILE_MISSING] => Array
                (
                    [vendor/predis/predis/docker/unstable_cluster/create_cluster.sh] => Array
                        (
                            [expected] => 65af3d1c198aa88a1fd73d0b249e33e20ade7bdc53e9e86040fd08b414dea4d1c791eae9855d6bc96b406a46aa08666fb1905747d34fb44ae5703b077f4ef99e
                            [current] => 
                        )
 
                )
 
        )
 
    [recommendations] => Array
        (
            [FILE_MISSING] => Array
                (
                    [build-js/npm-post-build.sh] => Array
                        (
                            [expected] => f4d96811c6b081ce2301f12abbbd07e392c4992cba1f2e44705367caae3d8fd95cacf47b8a3c85a20f30c20fa64faa8c61ba57da7230a0fabda88ba088f2229a
                            [current] => 
                        )
 
                )
 
        )
 
    [files_pdfviewer] => Array
        (
            [FILE_MISSING] => Array
                (
                    [build-js/npm-post-build.sh] => Array
                        (
                            [expected] => f4d96811c6b081ce2301f12abbbd07e392c4992cba1f2e44705367caae3d8fd95cacf47b8a3c85a20f30c20fa64faa8c61ba57da7230a0fabda88ba088f2229a
                            [current] => 
                        )
 
                )
 
        )
 
    [related_resources] => Array
        (
            [FILE_MISSING] => Array
                (
                    [build/npm-post-build.sh] => Array
                        (
                            [expected] => f4d96811c6b081ce2301f12abbbd07e392c4992cba1f2e44705367caae3d8fd95cacf47b8a3c85a20f30c20fa64faa8c61ba57da7230a0fabda88ba088f2229a
                            [current] => 
                        )
 
                )
 
        )
 
)

### Nextcloud Logs

 NotFoundException /appdata_oc2jdg7b0n8o/theming/global
Error while running background job OCA\Theming\Jobs\MigrateBackgroundImages (id: 129, arguments: {"stage":"prepare"})

**Comment by kesselb** [comment]
Thanks for the report 👍 

`mail/appinfo/signature.json` indeed contains the hashes for the files in vendor-bin, however they are not shipped and therefore the warning.

**Comment by enoch85** [comment]
> Maybe antivirus blocking .sh files?

You mean on the server or the webUI (client computer connecting)?

There's no antivirus at all actually. Not on the server and not on the connecting laptop. The laptop is Ubuntu 22.04, and server a 24.04 minimal, with only the listed apps installed, nothing else.

Thanks for looking into this!

**Comment by kesselb** [comment]
We guess that something on your end does delete those .sh files. They are part of the release file and therefore also in the list of expected files/hashes.

**Comment by enoch85** [comment]
Aaaah, now I think I know where the bugs comes from. 

Will investigate.

**Comment by kesselb** [comment]
Logged issues to clean up our releases:

- https://github.com/nextcloud/deck/issues/6420
- https://github.com/nextcloud/photos/issues/2687
- https://github.com/nextcloud/files_pdfviewer/issues/1072
- https://github.com/nextcloud/related_resources/issues/494
- https://github.com/nextcloud/twofactor_nextcloud_notification/issues/913
- https://github.com/nextcloud/recommendations/issues/803
- https://github.com/nextcloud/collectives/issues/1541
