### ISSUE TITLE
[Bug]: "Local" option to add external drive is not present

### ISSUE THREAD

**Issue by loddi-o** [nextcloud/server#48771]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I am running Nextcloud in a docker container in my openmediavault 7 (debian) server, I used the official AIO installer.
As you can see, there is not a "Local" option to mount my Local drives. I have admin privileges, and I am under "Administrator" with an admin account (default admin one). 
In the nextcloud-aio-mastercontainer container command line, i can see all the files in the drives mounted correctly.
![Image](https://github.com/user-attachments/assets/400b1fcc-842a-4591-ad64-731dc2edb4d2)

### Steps to reproduce

Install Nextcloud via official AIO container, run it.
Login via portainer, edit the nextcloud-aio-mastercontainer volumes like in the picture below
![Image](https://github.com/user-attachments/assets/87efb7ef-d54c-4529-8b7d-e1d18585abb8)

Specify in "host section" the mount points of the drives you want to share with nextcloud.

Go back in nextcloud and enable the "external drive" option (not sure if that's how it is called in English).
As administrator, login into https://.../settings/admin/overview.

### Expected behavior

"Local" option to mount local drives/folder should be there according to Nextcloud documentation.

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

root@nas-di-lorenzo:/# sudo -u www-data php occ config:list system
Could not open input file: occ
root@nas-di-lorenzo:/# php occ config:list system
Could not open input file: occ
root@nas-di-lorenzo:/# ./occ config:list system
bash: ./occ: File o directory non esistente
#even with a local user i havce the same output

### List of activated Apps

root@nas-di-lorenzo:/# sudo -u www-data php occ app:list
Could not open input file: occ
root@nas-di-lorenzo:/# php occ app:list
Could not open input file: occ
root@nas-di-lorenzo:/# ./occ app:list
bash: ./occ: File o directory non esistente

### Nextcloud Signing status

No errors have been found.

### Nextcloud Logs

root@nas-di-lorenzo:/# cat data/nextcloud.log
cat: data/nextcloud.log: File o directory non esistente

### Additional info

I also tried different browsers

**Comment by joshtrichards** [comment]
```
root@nas-di-lorenzo:/# sudo -u www-data php occ config:list system
Could not open input file: occ
root@nas-di-lorenzo:/# php occ config:list system
Could not open input file: occ
root@nas-di-lorenzo:/# ./occ config:list system
bash: ./occ: File o directory non esistente
#even with a local user i havce the same output
```

See https://github.com/nextcloud/all-in-one#how-to-run-occ-commands

**Comment by joshtrichards** [comment]
And for your main matter: https://github.com/nextcloud/all-in-one?tab=readme-ov-file#how-to-allow-the-nextcloud-container-to-access-directories-on-the-host
