### ISSUE TITLE
Error 403 + HTML response from API when trying to create new user

### ISSUE THREAD

**Issue by leonklingele** [nextcloud/server#4878]
Steps to reproduce:

1. Open `/settings/users` in your browser
2. Create a new user `test` with password `test`
3. Receive 403 response from the `/settings/users/users` API endpoint which returns some HTML:

```html
..
	<li class='error'>
		Zugriff verboten<br>
		<p class='hint'></p>
	</li>
..
```

Affected version: Nextcloud version 11.0.3 (stable)

I already showed this to @schiessle but we were not able to reproduce this on his machine.
We boiled down the issue to the 'Password rules' options in the admin settings. The issue does not occur when the new user's password fulfills all requirements specified there.

Initially reported by @vaneslie

**Comment by rullzer** [comment]
Are you running nginx by any chance?
Remove the `error_page` lines from your config.

**Comment by leonklingele** [comment]
@rullzer thanks, that fixed the issue. Now the API is properly returning JSON.
The `error_page` directives were recommended for Nextcloud 10.
