### ISSUE TITLE
Possibility to go above the quota

### ISSUE THREAD

**Issue by sowjanyakch** [nextcloud/server#48789]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [ ] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

The system is incorrectly calculating the quota usage when performing file delete and restore operations. This can lead to exceeding the allocated quota, potentially saturating the S3 storage.

### Steps to reproduce

1. Create a test user with 1GB quota.
2. Upload a file of 500MB to S3.
3. Copy the uploaded file and delete the original file.
4. Create another copy of the file and delete the original copied file.
5. Create another copy of the file.
6. Restore the first two delete files.
7. Quota is shown as 2GB, exceeding the allocated limit.

### Expected behavior

The quota should not exceed 1 GB in any given case.

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by sorbaugh** [comment]
@Pytal can you check if this is related to the trash-restoration functionality? 🙏

**Comment by Pytal** [comment]
Deleted files are automatically cleaned up by a background job whenever the quota is exceeded until the quota is met.

Although the quota may be exceeded temporarily, the next run of the background job, see https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html for setting the interval between jobs, will remedy this.
