### ISSUE TITLE
Personal settings: User details not saved when auto completed

### ISSUE THREAD

**Issue by leonklingele** [nextcloud/server#4879]
Steps to reproduce:

1. Open your personal settings
2. Empty the email field
3. Double click in it (should bring up the autocompletion suggestions from your browser if an entry is available)
4. Click on one of these suggestions
5. No API call is made / the email address will not be updated

Affected version: Nextcloud version 11.0.3 (stable)

**Comment by MorrisJobke** [comment]
cc @schiessle

**Comment by MorrisJobke** [comment]
cc @nextcloud/javascript

**Comment by skjnldsv** [comment]
Fixed a while back
