### ISSUE TITLE
Impersonating new LDAP user fails

### ISSUE THREAD

**Issue by mrnoisytiger** [nextcloud/server#4882]
### Steps to reproduce
1. Link Nextcloud to LDAP with users
2. Have a user account that has never logged in with Nextcloud directly
3. Attempt to impersonate that user
4. Receives Internal Server Error

### Expected behaviour
Nextcloud should set up a base folder structure if a user has never logged in before.

### Actual behaviour
Internal Server Error.

	OCP\Files\NotFoundException: 

    /var/www/nextcloud/apps/files/lib/Controller/ViewController.php - line 130: OC_Helper getStorageInfo('/', false)
    /var/www/nextcloud/apps/files/lib/Controller/ViewController.php - line 159: OCA\Files\Controller\ViewController->getStorageInfo()
    [internal function] OCA\Files\Controller\ViewController->index('', '', NULL, false)
    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Files\Controller\ViewController), 'index')
    /var/www/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files\Controller\ViewController), 'index')
    /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('ViewController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /var/www/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /var/www/nextcloud/lib/base.php - line 975: OC\Route\Router->match('/apps/files/')
    /var/www/nextcloud/index.php - line 40: OC handleRequest()
    {main}

### Server configuration

**Operating system**: Ubuntu 16.04LTS

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7

**Nextcloud version:** (see Nextcloud admin page) 12 beta 2

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Comment by LukasReschke** [comment]
Thanks. Tracking at https://github.com/nextcloud/impersonate/issues/5
