### ISSUE TITLE
[Bug]: audit.log does not correctly log failed login attempts (as it did before), needed for fail2ban

### ISSUE THREAD

**Issue by tgoeg** [nextcloud/server#48826]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

This is a follow-up to #493
https://github.com/nextcloud/server/issues/493#issuecomment-276749313 shows a (2017) working fail2ban config when failed logins were still logged as such.
This is not the case anymore, as a current 30.0.1.2 installation only logs the following in `audit.log` when attempting a wrong login:

```
{"reqId":"lWcRea3NyRfNB68OAQzv","level":1,"time":"2024-10-21T07:21:57+00:00","remoteAddr":"10.0.0.1","user":"--","app":"admin_audit","method":"POST","url":"/index.php/login","message":"Login attempt: \"eviluser\"","userAgent":"Mozilla/5.0 (X11; Linux x86_64)","version":"30.0.1.2","data":{"app":"admin_audit"}}
```

which is exactly the same as a successful login (a second line is logged in that case, stating the login was successful).
No log entries whatsoever in `nextcloud.log`.

Please bring back differentiated log stanzas when bruteforcing the login form.
I am well aware that nextcloud has its own bruteforce protection, but in a high-bandwidth scenario it does not help you at all if every bad request has to be handled by the web server, PHP and the DB. You need to stop this at the network level, and fail2ban is one such option. If you want to go further and stop it in a different network component, you also need this log data.

### Steps to reproduce

1. Install latest NC.
2. Configure audit logging.
3. Try to log in with a wrong user.
4. Profit.

### Expected behavior

Log files (nextcloud.log or audit.log?) should contain an entry clearly showing the login has failed.

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Enabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report
```
{
    "system": {
        "config_is_read_only": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "30.0.1.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": false,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "log_type": "file",
        "log_rotate_size": 10000000,
        "loglevel": 1,
        "logfile": "***REMOVED SENSITIVE VALUE***/nextcloud.log",
        "logfilemode": 384,
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "log_type_audit": "file",
        "log_rotate_size_audit": 10000000,
        "logfile_audit": "***REMOVED SENSITIVE VALUE***/audit.log",
        "logfilemode_audit": 384,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpstreamoptions": {
            "ssl": {
                "allow_self_signed": true,
                "verify_peer": false,
                "verify_peer_name": false
            }
        },
        "maintenance": false,
        "updater.release.channel": "stable",
        "trashbin_retention_obligation": "auto, 14",
        "mail_sendmailmode": "smtp",
        "app_install_overwrite": [
            "impersonate",
            "spreed",
            "files_accesscontrol",
            "quota_warning",
            "richdocuments"
        ],
        "encryption.key_storage_migrated": false,
        "defaultapp": "files",
        "data-fingerprint": "f6b9874ea721c2b292b953f6e2a84ace"
    }
}
```
### List of activated Apps
```
Enabled:
  - activity: 3.0.0
  - admin_audit: 1.20.0
  - app_api: 4.0.0
  - calendar: 5.0.1
  - circles: 30.0.0-dev
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contacts: 6.1.0
  - contactsinteraction: 1.11.0
  - dav: 1.31.1
  - encryption: 2.18.0
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_accesscontrol: 1.20.1
  - files_downloadlimit: 3.0.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - groupquota: 0.2.1
  - impersonate: 1.17.0
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - nextcloud_announcements: 2.0.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - photos: 3.0.2
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - quota_warning: 1.20.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - serverinfo: 2.0.0
  - settings: true
  - sharebymail: 1.20.0
  - support: 2.0.0
  - survey_client: 2.0.0
  - systemtags: 1.20.0
  - text: 4.1.0
  - theming: 2.5.0
  - theming_customcss: 1.17.0
  - twofactor_backupcodes: 1.19.0
  - updatenotification: 1.20.0
  - user_ldap: 1.21.0
  - user_usage_report: 1.14.0
  - viewer: 3.0.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - bruteforcesettings: 3.0.0 (installed 2.4.0)
  - dashboard: 7.10.0 (installed 7.3.0)
  - files_downloadactivity: 1.17.0 (installed 1.17.0)
  - files_external: 1.22.0 (installed 1.11.1)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - files_trackdownloads: 1.11.0 (installed 1.10.0)
  - spreed: 20.0.1 (installed 20.0.1)
  - suspicious_login: 8.0.0
  - twofactor_nextcloud_notification: 4.0.0
  - twofactor_totp: 12.0.0-dev
  - user_status: 1.10.0 (installed 1.0.1)
  - weather_status: 1.10.0 (installed 1.0.0)
```
### Nextcloud Signing status

No errors have been found.

### Nextcloud Logs
```
{"reqId":"lWcRea3NyRfNB68OAQzv","level":1,"time":"2024-10-21T07:21:57+00:00","remoteAddr":"10.0.0.1","user":"--","app":"admin_audit","method":"POST","url":"/index.php/login","message":"Login attempt: \"eviluser\"","userAgent":"Mozilla/5.0 (X11; Linux x86_64)","version":"30.0.1.2","data":{"app":"admin_audit"}}
```

**Comment by szaimen** [comment]
FYI @come-nc

**Comment by joshtrichards** [comment]
> https://github.com/nextcloud/server/issues/493#issuecomment-276749313 shows a (2017) working fail2ban config when failed logins were still logged as such.

Note we have actual documentation covering fail2ban here: https://docs.nextcloud.com/server/latest/admin_manual/installation/harden_server.html#setup-fail2ban

>  This is not the case anymore, as a current 30.0.1.2 installation only logs the following in audit.log when attempting a wrong login:

The `nextcloud.log` is where this has always been logged.

And this works for me just fine in 30.0.1. :-)

```
{"reqId":"bOPpnrYe6icY2en4M6by","level":2,"time":"2024-10-21T14:02:50+00:00","remoteAddr":"x.x.x.x","user":"--","app":"no app in context","method":"POST","url":"/login","message":"Login failed: slfjsdf (Remote IP: x.x.x.x)","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:XXX.X) Gecko/20100101 Firefox/XXX.X","version":"30.0.1.2","data":[]}
```

**Comment by tgoeg** [comment]
Sigh... if only the updater wouldn't always change permissions of `nextcloud.log` in a secure setup where files are not owned by `www-data`. But that's a different story.
Sorry for the noise, indeed works.

However, shouldn't this be part of `audit.log` (as well) if the login attempts are indeed logged there?

**Comment by joshtrichards** [comment]
> Sigh... if only the updater wouldn't always change permissions of nextcloud.log in a secure setup where files are not owned by www-data. 

Can you elaborate? We only set the `logfilemode` in one spot AFAIK:

https://github.com/nextcloud/server/blob/432ea6e714362ef89e38887c8889bf653516cad4/lib/private/Log/File.php#L44-L57

Updating doesn't change permissions on the log file (at least not directly) in any way I can think of. 

>`         "logfilemode": 384,`

So `0600` in octal: `-rw-------`. I presume you're manually changing permissions outside of Nextcloud then? Can't you just change this to the desired permissions?

**Comment by tgoeg** [comment]
Right, it's not updating. And it is not a manually triggered cron run. But something constantly changes the file modes (of log files and data directories of users) and I couldn't quite get to the base of it up until NC 26, then I had to focus on other projects. Maybe it is fixed now, I am in the process of verifying it.
The `logfilemode` was just a remnant of some old try on this dev instance. I searched for it yesterday (https://duckduckgo.com/?t=ffab&q=%22logfilemode%22+nextcloud&ia=web) and could not find any mention of it anymore, so I thought it wasn't a valid config value anymore. It's strange that the docs do not seem to get indexed by search engine(s). Thanks for the link!

It now switched to the much more logical octal representation and will keep an eye on it.

I always end up fighting nextcloud permissions as I want a (non-webserver-)user owned installation as with any other webservice I host.
I simply don't understand why I should risk letting the webserver potentially write its own code.
There's a standard user, say `nextcloud`, that owns all files (and may write them as well), and it is part of the webservers user group.
Only logfiles, uploads and cache may be written by the webserver (user). This vastly reduces the attack surface of any web service.

But nextcloud does not seem to be designed for this kind of setup.
Whenever I update using `occ` with user `nextcloud`, I have to do a lot of trickery before, as the update process won't accept e.g. `config.php` being read only for the webserver but r/w for user `nextcloud` and just go ahead and update stuff. That is, up until NC26.
Maybe things improved, I'll have to check that.

Another thing is cron runs.
The data directory has mode `2770` and is owned by `nextcloud`:`www-data`.
However, I could not find a way for cron runs to use a proper umask to make directories keep those permissions. They always end up as `2755`, trashbin deletion or thumbnail generation won't work afterwards, etc.

There are open tickets for several aspects of this, but I need to find the time to dig deeper again, which is hard with no human resources available for everyday sysadmin tasks..

EDIT: The proper `logfilemode` `0620` seems to work now, some cron run has changed it to this very mode, so I am somewhat optimistic.

The original issue of this ticket is therefore fixed, thanks. However, I think I'll open another one questioning whether `audit.log` should not contain entries for failed logins. It contains attempts, and the very nature of an audit log should be to log potentially harmful actions, at least that's my understanding.

**Comment by tgoeg** [comment]
For anyone running into this:
You have to set `loglevel` to `2` or lower for nextcloud to actually log failed logins.
I reverted to `3` after testing of various issues and suddenly fail2ban tests would fail again. This is not part of the documentation and needs updating.
I'll submit a ticket and a PR.
