### ISSUE TITLE
[Bug]: Show default expiration date on public share link creation

### ISSUE THREAD

**Issue by sowjanyakch** [nextcloud/server#48860]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

A default 7-day expiration is set for shares, but many users don’t notice it when creating shares. This leads to issues when shares expire, especially if the link was shared widely.

### Steps to reproduce

1. Create a public share link.
2. Default expiration date is not shown in the share creation dialog.

 ![Image](https://github.com/user-attachments/assets/ddf18585-4939-46f7-bdf9-f3589fbb43d9)

### Expected behavior

Default expiration date should be shown in the share creation dialog.

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

PHP 8.2

### Web server

None

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

{
   "instanceid": "***REMOVED SENSITIVE VALUE***",
   "passwordsalt": "***REMOVED SENSITIVE VALUE***",
   "secret": "***REMOVED SENSITIVE VALUE***",
   "trusted_domains": [
   ],
   "datadirectory": "***REMOVED SENSITIVE VALUE***",
   "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
   "dbtype": "mysql",
   "version": "28.0.10.2",
   "dbname": "***REMOVED SENSITIVE VALUE***",
   "dbhost": "***REMOVED SENSITIVE VALUE***",
   "dbtableprefix": "oc_",
   "dbuser": "***REMOVED SENSITIVE VALUE***",
   "dbpassword": "***REMOVED SENSITIVE VALUE***",
   "logtimezone": "Europe\/Berlin",
   "loglevel": 2,
   "log_authfailip": true,
   "log_rotate_size": 104857600,
   "installed": true,
   "memcache.local": "\\OC\\Memcache\\APCu",
   "mail_smtpmode": "smtp",
   "mail_from_address": "***REMOVED SENSITIVE VALUE***",
   "mail_domain": "***REMOVED SENSITIVE VALUE***",
   "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
   "mail_smtpport": "25",
   "force_language": "de_DE",
   "skeletondirectory": "",
   "singleuser": false,
   "maintenance": false,
   "updatechecker": false,
   "trashbin_retention_obligation": "30, 40",
   "htaccess.RewriteBase": "\/",
   "memcache.locking": "\\OC\\Memcache\\Redis",
   "redis": {
       "host": "***REMOVED SENSITIVE VALUE***",
       "port": 0
   },
   "updater.release.channel": "enterprise",
   "simpleSignUpLink.shown": false,
   "sort_groups_by_name": true,
   "mail_sendmailmode": "smtp",
   "theme": "",
   "defaultapp": "files",
   "mysql.utf8mb4": true,
   "default_phone_region": "DE",
   "maintenance_window_start": 2,
   "preview_max_memory": 256,
   "profile.enabled": false,
   "mail_template_class": "OCA\\EmailTemplateTLRZ\\EMailTemplate",
   "default_language": "de_DE",
   "memcache.distributed": "\\OC\\Memcache\\Redis",
   "htaccess.IgnoreFrontController": true,
   "updater.server.url": "***REMOVED SENSITIVE VALUE***",
   "trusted_proxies": "***REMOVED SENSITIVE VALUE***"
}

### List of activated Apps

Enabled:
- activity: 2.20.0
- announcementcenter: 7.0.0
- bruteforcesettings: 2.8.0
- calendar: 4.7.16
- circles: 28.0.0
- cloud_federation_api: 1.11.0
- collectives: 2.14.4
- comments: 1.18.0
- contacts: 5.5.3
- contactsinteraction: 1.9.0
- dashboard: 7.8.0
- dav: 1.29.2
- deck: 1.12.5
- email_template_tlrz: 1.0.1
- external: 5.3.1
- federatedfilesharing: 1.18.0
- federation: 1.18.0
- files: 2.0.0
- files_antivirus: 5.5.7
- files_pdfviewer: 2.9.0
- files_reminders: 1.1.0
- files_sharing: 1.20.0
- files_trashbin: 1.18.0
- files_versions: 1.21.0
- forms: 4.2.4
- logreader: 2.13.0
- lookup_server_connector: 1.16.0
- nextcloud_announcements: 1.17.0
- notifications: 2.16.0
- oauth2: 1.16.4
- password_policy: 1.18.0
- photos: 2.4.0
- provisioning_api: 1.18.0
- recommendations: 2.0.0
- related_resources: 1.3.0
- richdocuments: 8.3.11
- security_guard: 1.2.1
- serverinfo: 1.18.0
- settings: 1.10.1
- sharebymail: 1.18.0
- spreed: 18.0.11
- support: 1.11.1
- survey_client: 1.16.0
- systemtags: 1.18.0
- tasks: 0.16.1
- text: 3.9.2
- theming: 2.3.0
- twofactor_backupcodes: 1.17.0
- twofactor_totp: 10.0.0-beta.2
- updatenotification: 1.18.0
- user_status: 1.8.1
- user_usage_report: 1.12.1
- viewer: 2.2.0
- weather_status: 1.8.0
- workflowengine: 2.10.0

Disabled:
- admin_audit: 1.18.0
- encryption
- files_confidential
- files_external
- files_lock
- firstrunwizard: 1.1
- globalsiteselector
- privacy: 1.1.0
- suspicious_login
- user_ldap
- user_saml

### Nextcloud Signing status

* SIP dialin is disabled
* SIP dialout is disabled

**Comment by skjnldsv** [comment]
More of an enhancement I'd say.
