### ISSUE TITLE
VA-API设备（/dev/dri/renderD128）权限不正确

### ISSUE THREAD

**Issue by wangruiqi-git** [nextcloud/server#48883]
I deploy my nextcloud like this
`docker run -d --restart=always --device=/dev/dri:/dev/dri:rw --name nextcloud2  -p 7680:80 -p 7681:443 -v /app/nextcloud:/var/www/html  -v /media/app/nextcloud_data/data:/var/www/html/data m.daocloud.io/docker.io/nextcloud`
then， every time I restart my container，renderD128 is reseted like this：
`www-data@60323fcdb204:/dev/dri$ ls -al
crw-rw---- 1 root   103 226, 128 Oct 24 16:40 renderD128`
application “memories” have no access to renderD128.
so， I need to 
`docker exec -it -u 33 nextcloud30 /bin/bash`
and chmod 777
I wonder if I use in a wrong way，anyway to solve it simply
![Image](https://github.com/user-attachments/assets/f0854e91-ecb2-4353-a74e-33f2de2ea743)

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue, I would like to ask you to raise your question at https://help.nextcloud.com
