### ISSUE TITLE
[Bug]: Setup CSP "Content Security Policy" missing in Nextcloud manual

### ISSUE THREAD

**Issue by carloscomputer** [nextcloud/server#48911]
### ⚠️ This issue respects the following points: ⚠️

- [ ] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [ ] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

CSP missing in Nextcloud Nginx docs configuration manual: 
https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html#nginx-configuration
Nginx:
```
add_header Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline' https:; script-src 'self' 'unsafe-eval' 'unsafe-inline' https:; font-src 'self' data:; img-src 'self' data: blob:; connect-src 'self' wss:; frame-src 'self';" always;
```

For Apache it shlould work with:

```
<IfModule mod_headers.c>
    Header always set Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline' https:; script-src 'self' 'unsafe-eval' 'unsafe-inline' https:; font-src 'self' data:; img-src 'self' data: blob:; connect-src 'self' wss:; frame-src 'self';"
</IfModule>
```

### Steps to reproduce

1.
2.
3.

### Expected behavior

edit your nginx.conf 

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Signing status

No errors have been found.

### Additional info

nginx.conf:
```
add_header Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline' https:; script-src 'self' 'unsafe-eval' 'unsafe-inline' https:; font-src 'self' data:; img-src 'self' data: blob:; connect-src 'self' wss:; frame-src 'self';" always;
```

For Apache it shlould work with:

```
<IfModule mod_headers.c>
    Header always set Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline' https:; script-src 'self' 'unsafe-eval' 'unsafe-inline' https:; font-src 'self' data:; img-src 'self' data: blob:; connect-src 'self' wss:; frame-src 'self';"
</IfModule>
```

**Comment by SystemKeeper** [comment]
Why posting twice? https://help.nextcloud.com/t/csp-content-security-policy-missing-in-nextcloud-manual/207822

**Comment by solracsf** [comment]
Agree, this is handled directly in Server code, not by the webserver itself.

**Comment by joshtrichards** [comment]
Indeed. This isn't missing. CSP is managed by Nextcloud itself. Doing this on your web server will break things; various apps update dynamically it as needed.

If you're not seeing the header in your environment it's likely a configuration matter of a different sort. Post for help on the help forum.
