### ISSUE TITLE
nc 12 beta3 error in opcache-warning

### ISSUE THREAD

**Issue by JSoko** [nextcloud/server#4891]
After upgrading from 11.03 to 12 beta 3
in the adminpanel it shows the following hint.
opcache.enable=On is wrong. It should be opcache.enable=1

---
PHP Opcache ist nicht korrekt eingerichtet. Für bessere Leistung empfehlen wir ↗ folgende Einstellungen in der php.ini:

opcache.enable=On
opcache.enable_cli=1
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=10000
opcache.memory_consumption=128
opcache.save_comments=1
opcache.revalidate_freq=1

**Comment by ChristophWurst** [comment]
This was added in Nextcloud 12: https://github.com/nextcloud/server/pull/3489

cc @MorrisJobke

**Comment by ChristophWurst** [comment]
Basically, this is what @nickvergessen noticed in https://github.com/nextcloud/server/pull/3489/files#r102667433

**Comment by ChristophWurst** [comment]
This is a duplicate of https://github.com/nextcloud/server/issues/4838
