### ISSUE TITLE
Progress bar message completely wrong with multi-GB file upload

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#4895]
### Steps to reproduce

1. Create a 11GB file
2. Upload it
3. Watch the progress bar

### Expected behaviour

The bar should move and the page should constantly try to evaluate how much time it will take and update the message

### Actual behaviour

The progress bar moves all right, but the message is stuck to "in a few seconds".

### Server configuration

**Nextcloud version:** 12

### Client configuration
**Browser:** Chrome

**Operating system:** Win10

**Comment by enoch85** [comment]
The Nextcloud (ownCloud) Client does the calculations properly, would it be possible to copy settings from there to the Web GUI progress bar?

**Comment by oparoz** [comment]
This has been fixed via https://github.com/nextcloud/server/pull/5177
