### ISSUE TITLE
[Bug]: "edit locally" Dialog makes no sense

### ISSUE THREAD

**Issue by ne0YT** [nextcloud/server#48972]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Just have to get this off my heart: It's a usability thing not a crashing bug, but it's a pretty bad one and it's built as if it's meant that way, which makes zero sense if you plan to use Nextcloud for real work.
---------------------------

after the file opens it will ask if it worked but the dialog doesn't make much sense. the option which implies to edit the file online instead will try to open it locally another time.. the other dialog which implies we want to try again opens it in Nextcloud Office.. and closing the dialog also opens it in the online Office.

### Steps to reproduce

1. right click a file and choose "edit locally"
2. after the file opens it will ask if it worked but the dialog is doesn't make much sense. the option which implies to edit the file online instead will try to open it locally another time.. the other dialog which implies we want to try again opens it in Nextcloud Office.. and closing the dialog also opens it in the online Office.
3. either you got the file open twice now.. (1* locally 1* in the online office) maybe you had to click twice to open it once (offline office knows it's already open)

### Expected behavior

1. I don't see any dialog if it works / I'm able to smh disable this dialog serverside.
2. If I chose to have the dialog the buttons should make sense. Especially the closing one should not result in another action.
3. To really work with "edit files locally" I would need to be able to set it as the primary option on-click for filetypes i can define serverside.
4. To really work with "edit files locally" I should be able to set the option as the first or 2nd on a right-click.

### Nextcloud Server version

29

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [x] SSO - SAML
- [ ] Other

### Configuration report

{
    "system": {
        "one-click-instance": true,
        "one-click-instance.user-limit": 100,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "check_data_directory_permissions": false,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "overwritehost": "nc.mydomain.tld",
        "overwriteprotocol": "https",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "nc.mydomain.tld"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "29.0.8.1",
        "overwrite.cli.url": "https:\/\/nc.mydomain.tld\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2,
        "log_type": "file",
        "logfile": "\/var\/www\/html\/data\/nextcloud.log",
        "log_rotate_size": 10485760,
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "jpeg_quality": 60,
        "enabledPreviewProviders": {
            "1": "OC\\Preview\\Image",
            "2": "OC\\Preview\\MarkDown",
            "3": "OC\\Preview\\MP3",
            "4": "OC\\Preview\\TXT",
            "5": "OC\\Preview\\OpenDocument",
            "6": "OC\\Preview\\Movie",
            "7": "OC\\Preview\\Krita"
        },
        "enable_previews": true,
        "upgrade.disable-web": true,
        "mail_smtpmode": "smtp",
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 30",
        "activity_expire_days": 30,
        "simpleSignUpLink.shown": false,
        "share_folder": "\/Shared",
        "one-click-instance.link": "https:\/\/nextcloud.com\/all-in-one\/",
        "upgrade.cli-upgrade-link": "https:\/\/github.com\/nextcloud\/all-in-one\/discussions\/2726",
        "updatedirectory": "\/nc-updater",
        "maintenance_window_start": 100,
        "allow_local_remote_servers": true,
        "davstorage.request_timeout": 3600,
        "htaccess.RewriteBase": "\/",
        "dbpersistent": false,
        "auth.bruteforce.protection.enabled": false,
        "ratelimit.protection.enabled": true,
        "files_external_allow_create_new_local": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "jsloader",
            "extract",
            "user_ldap"
        ],
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "skeletondirectory": "",
        "enforce_theme": "light-highcontrast",
        "DOMAIN": "nc.mydomain.tld"
    }
}

### List of activated Apps

Enabled:
  - activity: 2.21.1
  - bookmarks: 14.2.6
  - cloud_federation_api: 1.12.0
  - comments: 1.19.0
  - contactsinteraction: 1.10.0
  - dav: 1.30.1
  - deck: 1.13.2
  - external: 5.4.1
  - extract: 1.3.6
  - federatedfilesharing: 1.19.0
  - files: 2.1.1
  - files_downloadlimit: 2.0.0
  - files_fulltextsearch: 29.0.1
  - files_lock: 29.0.1
  - files_pdfviewer: 2.10.0
  - files_reminders: 1.2.0
  - files_sharing: 1.21.0
  - files_trashbin: 1.19.0
  - files_versions: 1.22.0
  - fulltextsearch: 29.0.1
  - fulltextsearch_elasticsearch: 29.0.1
  - groupfolders: 17.0.5
  - logreader: 2.14.0
  - lookup_server_connector: 1.17.0
  - notifications: 2.17.0
  - notify_push: 0.7.0
  - oauth2: 1.17.1
  - polls: 7.2.4
  - privacy: 1.13.0
  - provisioning_api: 1.19.0
  - recommendations: 2.1.0
  - related_resources: 1.4.0
  - richdocuments: 8.4.8
  - secrets: 2.1.1
  - serverinfo: 1.19.0
  - settings: 1.12.0
  - sharelisting: 1.2.0
  - spreed: 19.0.10
  - systemtags: 1.19.0
  - text: 3.10.1
  - theming: 2.4.0
  - twofactor_backupcodes: 1.18.0
  - user_ldap: 1.20.0
  - user_saml: 6.3.0
  - user_status: 1.9.0
  - viewer: 2.3.0
  - workflowengine: 2.11.0
Disabled:
  - admin_audit: 1.19.0 (installed 1.19.0)
  - bruteforcesettings: 2.9.0
  - circles: 29.0.0-dev (installed 29.0.0-dev)
  - dashboard: 7.9.0 (installed 7.9.0)
  - encryption: 2.17.0
  - federation: 1.19.0 (installed 1.19.0)
  - files_external: 1.21.0
  - firstrunwizard: 2.18.0 (installed 2.18.0)
  - nextcloud-aio: 0.6.0
  - nextcloud_announcements: 1.18.0 (installed 1.18.0)
  - password_policy: 1.19.0 (installed 1.19.0)
  - photos: 2.5.0 (installed 2.5.0)
  - sharebymail: 1.19.0 (installed 1.19.0)
  - support: 1.12.0 (installed 1.12.0)
  - survey_client: 1.17.0 (installed 1.17.0)
  - suspicious_login: 7.0.0
  - twofactor_totp: 11.0.0-dev
  - weather_status: 1.9.0 (installed 1.9.0)

### Nextcloud Signing status

No errors have been found.

### Nextcloud Logs

-

### Additional info

I had my own nextcloud client handling files for me using windows and linux webdav backends. but since under windows there were a lot of bugs (on linux it was working perfectly) and jsloader addon doesn't work anymore I now need to switch to the official client.

**Comment by joshtrichards** [comment]
Related to your report: #49034

**Comment by skjnldsv** [comment]
@ne0YT what phrazing would you use then?
Can you suggest an example? :)

**Comment by skjnldsv** [comment]
Fix proposal here: https://github.com/nextcloud/server/pull/49150

**Comment by ne0YT** [comment]
Yeah the button triggers were all wrong. text is good fix proposal looks good to me, but.. 
I would really like to disable the dialog all together smh.. because for me it works every time and then to click another time or something is just weird if you're working with it..

**Comment by ne0YT** [comment]
@skjnldsv 
any idea how i could manage this with my js injecton? :)
:
To really work with "edit files locally" I would need to be able to set it as the primary option on-click for filetypes i can define serverside.
To really work with "edit files locally" I should be able to set the option as the first or 2nd on a right-click.

I didn't have any success so far with those..
