### ISSUE TITLE
Make it possible to enforce a maximum expiry date for public links

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#4899]
### Steps to reproduce

1. As an admin, enforce an expiry date
2. As a user, share a file via public link

### Expected behaviour

I should be able to select a custom expiry date which is not beyond what was set by the admin

### Actual behaviour

I cannot set my own expiry date

**Comment by enoch85** [comment]
Related https://github.com/nextcloud/server/issues/4525

**Comment by daita** [comment]
It seems to be working like defined as _Expected behaviour_ on NC12

**Comment by oparoz** [comment]
Fixed in 12. Thanks for the heads up.
