### ISSUE TITLE
Native zip/unzip in Nextcloud Files

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/server#48999]
I have searched Nextcloud issues. But i only found closed issues and not workling apps in the Nextcloud store.

**No native zip/unzip in Nextcloud Files**
Other file management systems have got native zip/unzip. In Nextcloud you can instlal e.g. [Archive Manager](https://apps.nextcloud.com/apps/files_archive) (not the right function), [Zipper](https://apps.nextcloud.com/apps/files_zip) (only zip not unzip) or [Extract](https://apps.nextcloud.com/apps/extract) (outdated).

**Native zip/unzip in Nextcloud Files**
It would be cool to insert native zip/unzip in Nextcloud Files. I think it is easy because of php-function for zip/unzip. Also the other apps are not needed anymore. Because for download the zip function is already in Nextcloud files included.

**Alternative**
Old other not working apps, upload and download single files.

**configuration**
Maybe because of security it would be nice to activate/deactivate zip/unzip in **config.php**.

There is also a discussion: https://help.nextcloud.com/t/how-to-unzip-an-archive-in-nextcloud/153760

**Comment by ShGKme** [comment]
- Duplication of https://github.com/nextcloud/server/issues/1573

**Comment by joshtrichards** [comment]
Also nextcloud/files_zip#32 is an open enhancement Issue for adding extraction.

The Zipper app has the advantage of handling things in the background so it's a cleaner user experience for large archives.
