### ISSUE TITLE
Download button on share view has strange color

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#4902]
Master after installation, this looks really odd:
![screen shot 2017-05-16 at 16 21 03](https://cloud.githubusercontent.com/assets/878997/26110823/b4df20a2-3a53-11e7-80a2-b8ef6331288e.png)

cc @nextcloud/designers @juliushaertl

**Comment by MorrisJobke** [comment]
I guess this is a feature, or isn't it?

**Comment by LukasReschke** [comment]
cc @jancborchardt Is it?

**Comment by jancborchardt** [comment]
Agree with @LukasReschke it looks strange – also saw it earlier today. Fix at https://github.com/nextcloud/server/pull/4911
