### ISSUE TITLE
[Bug]: occ reports unhandled exception about TypeError in construction of BackgroundService (OCP\IConfig, OC\AppConfig)

### ISSUE THREAD

**Issue by damien-sorin** [nextcloud/server#49037]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi,

I am trying to upgrade my nextcloud instance from 29.0.8 to 30.0.1 as described in 

https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html

On Step 15, before issuing the upgrade command I testing if occ is working at all by simply running occ without arguments with the folllowing output:

```
An unhandled exception has been thrown:

TypeError: OCA\Theming\Service\BackgroundService::__construct():
    Argument #3 ($config) must be of type OCP\IConfig, OC\AppConfig given, 
    called in lib/private/Server.php on line 1153 
    and defined in apps/theming/lib/Service/BackgroundService.php:186

Stack trace:
    #0 lib/private/Server.php(1153): OCA\Theming\Service\BackgroundService->__construct()
    #1 lib/private/AppFramework/Utility/SimpleContainer.php(153): OC\Server->OC\{closure}()
    #2 3rdparty/pimple/pimple/src/Pimple/Container.php(122): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}()
    #3 lib/private/AppFramework/Utility/SimpleContainer.php(120): Pimple\Container->offsetGet()
    #4 lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query()
    #5 lib/private/AppFramework/Utility/SimpleContainer.php(42): OC\ServerContainer->query()
    #6 lib/private/Console/Application.php(37): OC\AppFramework\Utility\SimpleContainer->get()
    #7 [internal function]: OC\Console\Application->__construct()
    #8 lib/private/AppFramework/Utility/SimpleContainer.php(61): ReflectionClass->newInstanceArgs()
    #9 lib/private/AppFramework/Utility/SimpleContainer.php(106): OC\AppFramework\Utility\SimpleContainer->buildClass()
    #10 lib/private/AppFramework/Utility/SimpleContainer.php(124): OC\AppFramework\Utility\SimpleContainer->resolve()
    #11 lib/private/ServerContainer.php(155): OC\AppFramework\Utility\SimpleContainer->query()
    #12 lib/private/AppFramework/Utility/SimpleContainer.php(42): OC\ServerContainer->query()
    #13 lib/public/Server.php(39): OC\AppFramework\Utility\SimpleContainer->get()
    #14 console.php(77): OCP\Server::get()
    #15 occ(11): require_once('...')
```

So, I am not able to upgrade because occ throws this exception.

Looking at the related files lib/private/Server.php and apps/theming/lib/Service/BackgroundService.php

I can see this call (.../lib/private/Server.php, line 1153)

```
$backgroundService = new BackgroundService(
                $c->get(IRootFolder::class),
                $c->getAppDataDir('theming'),
                $c->get(IAppConfig::class),
                $c->get(\OCP\IConfig::class),
                $c->get(ISession::class)->get('user_id'),
        );
```

to this function (.../apps/theming/lib/Service/BackgroundService.php, line 186)

```
public function __construct(
                IRootFolder $rootFolder,
                IAppData $appData,
                IConfig $config,
                ?string $userId,
                ThemingDefaults $themingDefaults)
{
                if ($userId === null) {
                        return;
                }

                $this->rootFolder = $rootFolder;
                $this->config = $config;
                $this->userId = $userId;
                $this->appData = $appData;
                $this->themingDefaults = $themingDefaults;
}
```

From my point of view, this looks like as there are the wrong parameters given in call-side.

### Steps to reproduce

1. do the steps 1-14 from this guide: https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html
2. run occ without any arguments

### Expected behavior

occ will run normal and shows available occ commands

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [x] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

 activity/
 admin_audit/
 bruteforcesettings/
 circles/
 cloud_federation_api/
 comments/
 contacts/
 contactsinteraction/
 dashboard/
 dav/
 encryption/
 federatedfilesharing/
 federation/
 files/
 files_downloadlimit/
 files_external/
 files_pdfviewer/
 files_reminders/
 files_sharing/
 files_trashbin/
 files_versions/
 firstrunwizard/
 groupfolders/
 hedgenext/
 keeweb/
 logreader/
 lookup_server_connector/
 nextcloud_announcements/
 notifications/
 oauth2/
 onlyoffice/
 password_policy/
 photos/
 privacy/
 provisioning_api/
 recommendations/
 related_resources/
 serverinfo/
 settings/
 sharebymail/
 support/
 survey_client/
 suspicious_login/
 systemtags/
 text/
 theming/
 twofactor_backupcodes/
 twofactor_totp/
 updatenotification/
 user_ldap/
 user_status/
 viewer/
 weather_status/
 workflowengine/

### Nextcloud Logs

there are no logs written

**Comment by joshtrichards** [comment]
> to this function (.../apps/theming/lib/Service/BackgroundService.php, line 186)

Please see https://github.com/nextcloud/server/blob/v30.0.1/apps/theming/lib/Service/BackgroundService.php

You'll notice it does not match yours. It sounds like you didn't completely replace everything. Check step 10 on the linked docs. If you need additional assistance, please use the help forum since this is not a bug - https://help.nextcloud.com.

**Comment by damien-sorin** [comment]
@joshtrichards 
thanks a lot - it was indeed a problem in my process of updating, leaving the theming app at the old version 2.4.0 from nextcloud 29.0.8 🤦

sorry for that, but I really did not get it without your hint of false version of the file!
