### ISSUE TITLE
Upload as guest to shared folder leads to invalid signature exception

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#4903]
Copied from https://help.nextcloud.com/t/default-encryption-module-upload-as-guest-to-encrypted-shared-user-folder-not-working/12501:

> -As a Nextcloud-User i share a folder with possibility to upload and edit files in that folder for guests.
> -i did send the created link to a GUEST (a non User).
> -the Guest does upload a file to that shared folder.
> -The files is always corrupt. the guest cannot download the file. the User can also not download the file.
> -Uploading something to that folder as USER works fine. Downloading the file (which was uploaded by the user) will work even from guest-side.
> -the only thing that is not possible, is to upload Files as a Guest.

I can reproduce this, note that you need to use a private browser session otherwise the file is accessible if you upload as logged-in user on the shared link. The reporter claims this a regression from 10.0.5 to 11.0.3

![exception](https://cloud.githubusercontent.com/assets/878997/26111105/7cd11eee-3a54-11e7-9569-a641c68b69e4.png)

**Comment by LukasReschke** [comment]
cc @nextcloud/encryption

**Comment by LukasReschke** [comment]
This is caused because the version in the `encrypted` integer isn't increased in the filecache. Investigating…

**Comment by LukasReschke** [comment]
6d5adb8b8f12bbfda71044ede557973fed50b240 is the breaking commit.

@icewind1991 Please take a look. Thanks. Reverting your commit fixes this issue. Also, we really should add integration tests when changing file system internals 🙈 

@karlitschek Another FYI regarding QA, we need automated integration tests as even 3 line changes as above can lead to data loss.

```
➜  stable9 git:(6d5adb8b8f) ✗ git bisect bad
6d5adb8b8f12bbfda71044ede557973fed50b240 is the first bad commit
commit 6d5adb8b8f12bbfda71044ede557973fed50b240
Author: Robin Appelman <robin@icewind.nl>
Date:   Mon Apr 10 15:19:21 2017 +0200

    Dont use the permissions mask while scanning

    Signed-off-by: Robin Appelman <robin@icewind.nl>

:040000 040000 b1ccd3122909a21caa67eaea64d3e6b95286bebf df55c26c6e18f1e279ce60764d3245a8cebb8257 M	lib
:040000 040000 05baccac9c64c1713f4c77de301c6acfa43e6be5 80dded4fa766bbe7841b118c0dcb9af4a2e545e6 M	tests
```

**Comment by nickvergessen** [comment]
See https://github.com/nextcloud/server/pull/4792

**Comment by nickvergessen** [comment]
Cache wrappers are ignored, see the automated tagging issue linked in the PR

**Comment by hoyalu** [comment]
Forgive my not fully understanding the details of this issue, but is there a workaround? I had someone upload a lot of data to my server. Is it lost or can I somehow recover it? (Except for asking the person to upload it again once this bug is solved of course.)

**Comment by LukasReschke** [comment]
@hoyalu In the `oc_filecache` table find the file and change the `encrypted` value from `0` to `1`.

**Comment by hoyalu** [comment]
Thank you, will try – with 171 files… :-(
