### ISSUE TITLE
[Bug]:  admin selects apps menu gets error message "An error occurred during the request. Unable to proceed."

### ISSUE THREAD

**Issue by snetAT** [nextcloud/server#49042]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After upgrading to 30.0.2 RC1, the error message “An error occurred during the request. Unable to proceed” appears in the apps menu.

### Expected behavior

apps management works

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Nginx

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [x] Other

### Configuration report

{
    "system": {
        "allowed_admin_ranges": [
            "127.0.0.1\/8",
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx.xx",
            "x.x.x.x"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "allow_local_remote_servers": true,
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "version": "30.0.2.0",
        "overwrite.cli.url": "https:\/\/xxx.xx",
        "overwriteprotocol": "https",
        "htaccess.IgnoreFrontController": false,
        "check_for_working_htaccess": true,
        "dbtype": "pgsql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbport": "5432",
        "installed": true,
        "default_phone_region": "AT",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 0
        },
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "lost_password_link": "disabled",
        "htaccess.RewriteBase": "\/",
        "session_lifetime": 86400,
        "remember_login_cookie_lifetime": 1296000,
        "updater.release.channel": "beta",
        "app_install_overwrite": [
            "user_external",
            "files_bpm",
            "to_gif_example"
        ],
        "log_type": "file",
        "loglevel": 2,
        "updatechecker": true,
        "defaultapp": "dashboard",
        "maintenance": false,
        "theme": "",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpdebug": false,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "gs.enabled": false,
        "gs.federation": "internal",
        "maintenance_window_start": "01:00",
        "user_backends": [
            {
                "class": "\\OCA\\UserExternal\\API",
                "arguments": [
                    "https:\/\/api.xxx.xx\/nxc\/login",
                    false
                ]
            }
        ],
        "forbidden_filename_basenames": [
            "con",
            "prn",
            "aux",
            "nul",
            "com0",
            "com1",
            "com2",
            "com3",
            "com4",
            "com5",
            "com6",
            "com7",
            "com8",
            "com9",
            "com\u00b9",
            "com\u00b2",
            "com\u00b3",
            "lpt0",
            "lpt1",
            "lpt2",
            "lpt3",
            "lpt4",
            "lpt5",
            "lpt6",
            "lpt7",
            "lpt8",
            "lpt9",
            "lpt\u00b9",
            "lpt\u00b2",
            "lpt\u00b3"
        ],
        "forbidden_filename_characters": [
            "<",
            ">",
            ":",
            "\"",
            "|",
            "?",
            "*",
            "\\",
            "\/"
        ],
        "forbidden_filename_extensions": [
            " ",
            ".",
            ".filepart",
            ".part"
        ],
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR",
            "HTTP_X_FORWARDED_FOR"
        ]
    }
}

### List of activated Apps

Enabled:
  - activity: 3.0.0
  - bruteforcesettings: 3.0.0
  - calendar: 5.0.1
  - circles: 30.0.0
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contacts: 6.1.0
  - contactsinteraction: 1.11.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - deck: 1.14.1
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - forms: 4.3.2
  - groupfolders: 18.0.3
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - mail: 4.0.2
  - nextcloud_announcements: 2.0.0
  - notes: 4.11.0
  - notifications: 3.0.0
  - notify_push: 0.7.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - photos: 3.0.2
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - richdocuments: 8.5.2
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - spreed: 20.0.1
  - support: 2.0.0
  - survey_client: 2.0.0
  - systemtags: 1.20.0
  - tables: 0.8.1
  - tasks: 0.16.1
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - updatenotification: 1.20.0
  - user_external: 3.4.0
  - user_migration: 7.0.1
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - whiteboard: 1.0.4
  - workflowengine: 2.12.0
Disabled:
  - admin_audit: 1.20.0
  - app_api: 4.0.0 (installed 4.0.0)
  - calendar_resource_management: 0.8.0
  - encryption: 2.18.0
  - files_external: 1.22.0
  - suspicious_login: 8.0.0
  - theming_customcss: 1.17.0
  - twofactor_nextcloud_notification: 4.0.0
  - twofactor_totp: 12.0.0-dev
  - user_ldap: 1.21.0

### Nextcloud Logs

{ "reqId": "RV0wSx4hrAVMbvsdPEcO", "level": 3, "time": "2024-11-01T14:20:07+00:00", "remoteAddr": "x.x.x.x", "user": "admin", "app": "index", "method": "GET", "url": "/settings/apps/list", "message": "OCA\\Settings\\Controller\\AppSettingsController::createProxyPreviewUrl(): Argument #1 ($url) must be of type string, array given, called in /var/www/html/apps/settings/lib/Controller/AppSettingsController.php on line 259 in file '/var/www/html/apps/settings/lib/Controller/AppSettingsController.php' line 245", "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36", "version": "30.0.2.0", "exception": { "Exception": "Exception", "Message": "OCA\\Settings\\Controller\\AppSettingsController::createProxyPreviewUrl(): Argument #1 ($url) must be of type string, array given, called in /var/www/html/apps/settings/lib/Controller/AppSettingsController.php on line 259 in file '/var/www/html/apps/settings/lib/Controller/AppSettingsController.php' line 245", "Code": 0, "Trace": [ { "file": "/var/www/html/lib/private/AppFramework/App.php", "line": 161, "function": "dispatch", "class": "OC\\AppFramework\\Http\\Dispatcher", "type": "->" }, { "file": "/var/www/html/lib/private/Route/Router.php", "line": 302, "function": "main", "class": "OC\\AppFramework\\App", "type": "::" }, { "file": "/var/www/html/lib/base.php", "line": 1001, "function": "match", "class": "OC\\Route\\Router", "type": "->" }, { "file": "/var/www/html/index.php", "line": 24, "function": "handleRequest", "class": "OC", "type": "::" } ], "File": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php", "Line": 146, "Previous": { "Exception": "TypeError", "Message": "OCA\\Settings\\Controller\\AppSettingsController::createProxyPreviewUrl(): Argument #1 ($url) must be of type string, array given, called in /var/www/html/apps/settings/lib/Controller/AppSettingsController.php on line 259", "Code": 0, "Trace": [ { "file": "/var/www/html/apps/settings/lib/Controller/AppSettingsController.php", "line": 259, "function": "createProxyPreviewUrl", "class": "OCA\\Settings\\Controller\\AppSettingsController", "type": "->", "args": [ "*** sensitive parameters replaced ***" ] }, { "file": "/var/www/html/apps/settings/lib/Controller/AppSettingsController.php", "line": 304, "function": "fetchApps", "class": "OCA\\Settings\\Controller\\AppSettingsController", "type": "->" }, { "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php", "line": 208, "function": "listApps", "class": "OCA\\Settings\\Controller\\AppSettingsController", "type": "->" }, { "file": "/var/www/html/lib/private/AppFramework/Http/Dispatcher.php", "line": 114, "function": "executeController", "class": "OC\\AppFramework\\Http\\Dispatcher", "type": "->" }, { "file": "/var/www/html/lib/private/AppFramework/App.php", "line": 161, "function": "dispatch", "class": "OC\\AppFramework\\Http\\Dispatcher", "type": "->" }, { "file": "/var/www/html/lib/private/Route/Router.php", "line": 302, "function": "main", "class": "OC\\AppFramework\\App", "type": "::" }, { "file": "/var/www/html/lib/base.php", "line": 1001, "function": "match", "class": "OC\\Route\\Router", "type": "->" }, { "file": "/var/www/html/index.php", "line": 24, "function": "handleRequest", "class": "OC", "type": "::" } ], "File": "/var/www/html/apps/settings/lib/Controller/AppSettingsController.php", "Line": 245 }, "message": "OCA\\Settings\\Controller\\AppSettingsController::createProxyPreviewUrl(): Argument #1 ($url) must be of type string, array given, called in /var/www/html/apps/settings/lib/Controller/AppSettingsController.php on line 259 in file '/var/www/html/apps/settings/lib/Controller/AppSettingsController.php' line 245", "exception": {}, "CustomMessage": "OCA\\Settings\\Controller\\AppSettingsController::createProxyPreviewUrl(): Argument #1 ($url) must be of type string, array given, called in /var/www/html/apps/settings/lib/Controller/AppSettingsController.php on line 259 in file '/var/www/html/apps/settings/lib/Controller/AppSettingsController.php' line 245" } }

**Comment by joshtrichards** [comment]
Wild guess from a quick look: we need to backport #48912 to v30

**Comment by snetAT** [comment]
> Backport pending in [#49044](https://github.com/nextcloud/server/pull/49044) if you feel like testing it.

Thanks patch works .
