### ISSUE TITLE
[Bug]: Update to 29.0.8 failed due to index name "nid" collision with constraint

### ISSUE THREAD

**Issue by VolkerKamin** [nextcloud/server#49052]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

While updating to 29.0.8 (in a chain after doing a few overdue updates just before, but with a minute between each update), my system got stuck. The error message specifically asked me to report this here.

I have limited access to the system (web hoster), but I am a computer scientist and the support of my hoster is rather responsive and forthcoming.

I have the option to just go back to a backup, but I'd rather fix the issue.

```text
Aktualisierung auf 29.0.8
InvalidArgumentException: Index name "nid" for table "WX19z_social_3_stream" collides with the constraint on table "WX19z_social_3_cache_actor".

Detaillierte Protokollmeldungen 
Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: All tables already have the correct collation -> nothing to do

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Datenbank aktualisiert

InvalidArgumentException: Index name "nid" for table "WX19z_social_3_stream" collides with the constraint on table "WX19z_social_3_cache_actor".

Das Update ist fehlgeschlagen. Bitte melden Sie dieses Problem an die [Nextcloud Community](https://github.com/nextcloud/server/issues).
```

### Steps to reproduce

1. Go to my domain, which presents the self-updater as expected.
2. Execute self-update by clicking the button.
3. Watch the error message come up.

### Expected behavior

Finish the update as per usual.

### Nextcloud Server version

28

### Operating system

None

### PHP engine version

PHP 8.1

### Web server

None

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by solracsf** [comment]
This seem related to Social app, not Server. Like https://github.com/nextcloud/social/issues/1871
Please report there.

**Comment by joshtrichards** [comment]
https://github.com/nextcloud/server/issues/41253#issuecomment-1853559554

https://github.com/nextcloud/server/issues/41253#issuecomment-1863186978

Don't hesitate to pop into the help forum (https://help.nextcloud.com) if still stuck.
