### ISSUE TITLE
Enhance upload progressbar (UX) on web uploads

### ISSUE THREAD

**Issue by TheJonyT** [nextcloud/server#49078]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Currently, user feedback on uploads through the web interface is limited. There is no indication of which files have been uploaded or are in the queue, making it difficult for users to determine which files have been successfully uploaded and which have not or even if all files have been picked up for upload. Additionally the progress bar gets lost when you switch to different folders or apps in Nextcloud.

**Describe the solution you'd like**
I would appreciate providing users with more information about their uploading files. Google Drive, for example, has an approach that lists all files and folders queued for upload and shows their progress. This makes it easier for users to see which files have been successfully picked up and uploaded. Additionally, uploads persist as long as you remain on Google Drive, allowing users to continue working while files upload in the background.
If Nextcloud could implement features like this it would greatly enhance the UX for its users, which cannot access logs etc.

**Describe alternatives you've considered**
I searched the App Store for an app that could provide the enhancements described, but I couldn’t find any options along those lines.

I would really like to see this feature in the future. 

Thank you!

**Additional context**
Here are some screenshots on Google Drive's approach (as described above):
![Image](https://github.com/user-attachments/assets/2dad126f-cb14-4008-909b-360ca6659757)
![Image](https://github.com/user-attachments/assets/6f65139d-98bf-4c8c-b80b-cd89a3da4440)

**Comment by MrRinkana** [comment]
Sounds like this: https://github.com/nextcloud/server/issues/41790

**Comment by TheJonyT** [comment]
@MrRinkana perfect! Thanks for pointing that out, I wasn't aware that there was already a suggestion for it🙂
