### ISSUE TITLE
[Bug]: cron error after upgrade to v30.0.1.2

### ISSUE THREAD

**Issue by JustinWuCN** [nextcloud/server#49088]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

my nextcloud is use pacman install on archlinux.
at the last week , i upgrade system, the nextcloud upgrade to V30.0.1.2.
on this version, cron task error every 5 min.

the error log like this

```
{"reqId":"X4TozJ451rxzohvGN57B","level":0,"time":"2024-11-05T07:55:13+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"dirty table reads: SELECT * FROM `*PREFIX*jobs` WHERE (`reserved_at` <= :dcValue1) AND (`last_checked` <= :dcValue2) ORDER BY `last_checked` ASC LIMIT 1","userAgent":"--","version":"30.0.1.2","exception":{"Exception":"Exception","Message":"dirty table reads: SELECT * FROM `*PREFIX*jobs` WHERE (`reserved_at` <= :dcValue1) AND (`last_checked` <= :dcValue2) ORDER BY `last_checked` ASC LIMIT 1","Code":0,"Trace":[{"file":"/usr/share/webapps/nextcloud/lib/private/DB/ConnectionAdapter.php","line":50,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":292,"function":"executeQuery","class":"OC\\DB\\ConnectionAdapter","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/BackgroundJob/JobList.php","line":192,"function":"executeQuery","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/usr/share/webapps/nextcloud/cron.php","line":148,"function":"getNext","class":"OC\\BackgroundJob\\JobList","type":"->"}],"File":"/usr/share/webapps/nextcloud/lib/private/DB/Connection.php","Line":402,"message":"dirty table reads: SELECT * FROM `*PREFIX*jobs` WHERE (`reserved_at` <= :dcValue1) AND (`last_checked` <= :dcValue2) ORDER BY `last_checked` ASC LIMIT 1","tables":["oc_appconfig","oc_jobs","oc_user_status"],"reads":["oc_jobs"],"exception":{},"CustomMessage":"dirty table reads: SELECT * FROM `*PREFIX*jobs` WHERE (`reserved_at` <= :dcValue1) AND (`last_checked` <= :dcValue2) ORDER BY `last_checked` ASC LIMIT 1"}}
```

### Steps to reproduce

1.use `pacman -Syu` upgrade system
2.run `occ upgrade`
3.the nextcloud.log fill the error.

### Expected behavior

no error on cron task

### Nextcloud Server version

30

### Operating system

Other

### PHP engine version

PHP 8.3

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Nextcloud Logs

{"reqId":"VHD8eCNAeir2sMZBXW9u","level":0,"time":"2024-11-05T08:00:13+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job OC\\Core\\BackgroundJobs\\CleanupLoginFlowV2 (id: 1929, arguments: null)","userAgent":"--","version":"30.0.1.2","data":{"app":"cron"}}
{"reqId":"VHD8eCNAeir2sMZBXW9u","level":0,"time":"2024-11-05T08:00:13+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"dirty table reads: SELECT * FROM `*PREFIX*jobs` WHERE (`reserved_at` <= :dcValue1) AND (`last_checked` <= :dcValue2) AND (`time_sensitive` = :dcValue3) ORDER BY `last_checked` ASC LIMIT 1","userAgent":"--","version":"30.0.1.2","exception":{"Exception":"Exception","Message":"dirty table reads: SELECT * FROM `*PREFIX*jobs` WHERE (`reserved_at` <= :dcValue1) AND (`last_checked` <= :dcValue2) AND (`time_sensitive` = :dcValue3) ORDER BY `last_checked` ASC LIMIT 1","Code":0,"Trace":[{"file":"/usr/share/webapps/nextcloud/lib/private/DB/ConnectionAdapter.php","line":50,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":292,"function":"executeQuery","class":"OC\\DB\\ConnectionAdapter","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/BackgroundJob/JobList.php","line":192,"function":"executeQuery","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/usr/share/webapps/nextcloud/cron.php","line":148,"function":"getNext","class":"OC\\BackgroundJob\\JobList","type":"->"}],"File":"/usr/share/webapps/nextcloud/lib/private/DB/Connection.php","Line":402,"message":"dirty table reads: SELECT * FROM `*PREFIX*jobs` WHERE (`reserved_at` <= :dcValue1) AND (`last_checked` <= :dcValue2) AND (`time_sensitive` = :dcValue3) ORDER BY `last_checked` ASC LIMIT 1","tables":["oc_appconfig","oc_jobs","oc_direct_edit","oc_user_status"],"reads":["oc_jobs"],"exception":{},"CustomMessage":"dirty table reads: SELECT * FROM `*PREFIX*jobs` WHERE (`reserved_at` <= :dcValue1) AND (`last_checked` <= :dcValue2) AND (`time_sensitive` = :dcValue3) ORDER BY `last_checked` ASC LIMIT 1"}}
{"reqId":"VHD8eCNAeir2sMZBXW9u","level":0,"time":"2024-11-05T08:00:13+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job OC\\TextToImage\\RemoveOldTasksBackgroundJob (id: 1932, arguments: null)","userAgent":"--","version":"30.0.1.2","data":{"app":"cron"}}
{"reqId":"VHD8eCNAeir2sMZBXW9u","level":0,"time":"2024-11-05T08:00:13+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"dirty table reads: SELECT * FROM `*PREFIX*jobs` WHERE (`reserved_at` <= :dcValue1) AND (`last_checked` <= :dcValue2) AND (`time_sensitive` = :dcValue3) ORDER BY `last_checked` ASC LIMIT 1","userAgent":"--","version":"30.0.1.2","exception":{"Exception":"Exception","Message":"dirty table reads: SELECT * FROM `*PREFIX*jobs` WHERE (`reserved_at` <= :dcValue1) AND (`last_checked` <= :dcValue2) AND (`time_sensitive` = :dcValue3) ORDER BY `last_checked` ASC LIMIT 1","Code":0,"Trace":[{"file":"/usr/share/webapps/nextcloud/lib/private/DB/ConnectionAdapter.php","line":50,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":292,"function":"executeQuery","class":"OC\\DB\\ConnectionAdapter","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/BackgroundJob/JobList.php","line":192,"function":"executeQuery","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/usr/share/webapps/nextcloud/cron.php","line":148,"function":"getNext","class":"OC\\BackgroundJob\\JobList","type":"->"}],"File":"/usr/share/webapps/nextcloud/lib/private/DB/Connection.php","Line":402,"message":"dirty table reads: SELECT * FROM `*PREFIX*jobs` WHERE (`reserved_at` <= :dcValue1) AND (`last_checked` <= :dcValue2) AND (`time_sensitive` = :dcValue3) ORDER BY `last_checked` ASC LIMIT 1","tables":["oc_appconfig","oc_jobs","oc_direct_edit","oc_user_status"],"reads":["oc_jobs"],"exception":{},"CustomMessage":"dirty table reads: SELECT * FROM `*PREFIX*jobs` WHERE (`reserved_at` <= :dcValue1) AND (`last_checked` <= :dcValue2) AND (`time_sensitive` = :dcValue3) ORDER BY `last_checked` ASC LIMIT 1"}}
{"reqId":"VHD8eCNAeir2sMZBXW9u","level":0,"time":"2024-11-05T08:00:13+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"CLI cron call has selected job OCA\\AppAPI\\BackgroundJob\\ExAppInitStatusCheckJob (id: 9794, arguments: null)","userAgent":"--","version":"30.0.1.2","data":{"app":"cron"}}
{"reqId":"VHD8eCNAeir2sMZBXW9u","level":0,"time":"2024-11-05T08:00:13+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Starting job OCA\\AppAPI\\BackgroundJob\\ExAppInitStatusCheckJob (id: 9794, arguments: null)","userAgent":"--","version":"30.0.1.2","data":{"app":"cron"}}
{"reqId":"VHD8eCNAeir2sMZBXW9u","level":0,"time":"2024-11-05T08:00:13+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished job OCA\\AppAPI\\BackgroundJob\\ExAppInitStatusCheckJob (id: 9794, arguments: null) in 0 seconds","userAgent":"--","version":"30.0.1.2","data":{"app":"cron"}}
{"reqId":"VHD8eCNAeir2sMZBXW9u","level":0,"time":"2024-11-05T08:00:13+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"dirty table reads: SELECT * FROM `*PREFIX*jobs` WHERE (`reserved_at` <= :dcValue1) AND (`last_checked` <= :dcValue2) AND (`time_sensitive` = :dcValue3) ORDER BY `last_checked` ASC LIMIT 1","userAgent":"--","version":"30.0.1.2","exception":{"Exception":"Exception","Message":"dirty table reads: SELECT * FROM `*PREFIX*jobs` WHERE (`reserved_at` <= :dcValue1) AND (`last_checked` <= :dcValue2) AND (`time_sensitive` = :dcValue3) ORDER BY `last_checked` ASC LIMIT 1","Code":0,"Trace":[{"file":"/usr/share/webapps/nextcloud/lib/private/DB/ConnectionAdapter.php","line":50,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php","line":292,"function":"executeQuery","class":"OC\\DB\\ConnectionAdapter","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/BackgroundJob/JobList.php","line":192,"function":"executeQuery","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/usr/share/webapps/nextcloud/cron.php","line":148,"function":"getNext","class":"OC\\BackgroundJob\\JobList","type":"->"}],"File":"/usr/share/webapps/nextcloud/lib/private/DB/Connection.php","Line":402,"message":"dirty table reads: SELECT * FROM `*PREFIX*jobs` WHERE (`reserved_at` <= :dcValue1) AND (`last_checked` <= :dcValue2) AND (`time_sensitive` = :dcValue3) ORDER BY `last_checked` ASC LIMIT 1","tables":["oc_appconfig","oc_jobs","oc_direct_edit","oc_user_status"],"reads":["oc_jobs"],"exception":{},"CustomMessage":"dirty table reads: SELECT * FROM `*PREFIX*jobs` WHERE (`reserved_at` <= :dcValue1) AND (`last_checked` <= :dcValue2) AND (`time_sensitive` = :dcValue3) ORDER BY `last_checked` ASC LIMIT 1"}}
{"reqId":"ScT3L0ClP0ON1DYvYPV7","level":0,"time":"2024-11-05T08:12:44+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"The loading of lazy AppConfig values have been requested","userAgent":"--","version":"30.0.1.2","exception":{"Exception":"RuntimeException","Message":"ignorable exception","Code":0,"Trace":[{"file":"/usr/share/webapps/nextcloud/lib/private/AppConfig.php","line":1180,"function":"loadConfig","class":"OC\\AppConfig","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppConfig.php","line":193,"function":"loadConfigAll","class":"OC\\AppConfig","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/AppConfig.php","line":1366,"function":"getAllValues","class":"OC\\AppConfig","type":"->"},{"file":"/usr/share/webapps/nextcloud/core/Command/Config/ListConfigs.php","line":121,"function":"getFilteredValues","class":"OC\\AppConfig","type":"->"},{"file":"/usr/share/webapps/nextcloud/core/Command/Config/ListConfigs.php","line":79,"function":"getAppConfigs","class":"OC\\Core\\Command\\Config\\ListConfigs","type":"->"},{"file":"/usr/share/webapps/nextcloud/3rdparty/symfony/console/Command/Command.php","line":298,"function":"execute","class":"OC\\Core\\Command\\Config\\ListConfigs","type":"->"},{"file":"/usr/share/webapps/nextcloud/core/Command/Base.php","line":161,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->"},{"file":"/usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php","line":1040,"function":"run","class":"OC\\Core\\Command\\Base","type":"->"},{"file":"/usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php","line":301,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php","line":171,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/usr/share/webapps/nextcloud/lib/private/Console/Application.php","line":183,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->"},{"file":"/usr/share/webapps/nextcloud/console.php","line":87,"function":"run","class":"OC\\Console\\Application","type":"->"},{"file":"/usr/share/webapps/nextcloud/occ","line":11,"args":["/usr/share/webapps/nextcloud/console.php"],"function":"require_once"}],"File":"/usr/share/webapps/nextcloud/lib/private/AppConfig.php","Line":1194,"message":"The loading of lazy AppConfig values have been requested","exception":{},"CustomMessage":"The loading of lazy AppConfig values have been requested"}}

**Comment by solracsf** [comment]
These aren't errors.
https://help.nextcloud.com/t/dirty-table-reads-excessive-logging-reproducible/194809
