### ISSUE TITLE
Problem upgrading NextCloud

### ISSUE THREAD

**Issue by progressguide** [nextcloud/server#4908]
I use the built-in updater to update NextCloud from 11.0.2 to 11.0.3 but I get an error that says:

```
Check for expected files
The following extra files have been found:
- softver.txt
- error_log
```

I tried deleting the error_log then re-dun the updater but I still get the same error. What can I do to update NextCloud?

**Comment by MorrisJobke** [comment]
Seems that some other program (maybe you web server) creates those files. Check the webserver configuration to not write those files.

For more help ask in the forums: https.//help.nextcloud.com
