### ISSUE TITLE
make changes to users.

### ISSUE THREAD

**Issue by Newyork311** [nextcloud/server#4909]
### Expected behaviour
In server any problem but in other pc, I cant do any change of users, I try in diferents browsers and reset factory and any solutions.

### Actual behaviour
In Administrator page have issue creating new groups, en change passsword to existing users o modify something, always say confirmation of password admin, I put one millon times and never do the changes always says that. I just can make any changes on the server but, On my pc dont allow make any changes using admin user.

**Operating system*Centos 6.8 2016 x86_64 x86_64 x86_64 GNU/Linux
*:

**Web server:*
Server version: Apache/2.2.15 (Unix)
Server built:   Mar 22 2017 06:52:55
*

**Database:*mysql  Ver 14.14 Distrib 5.5.54, for Linux (x86_64) using readline 5.1
*

**PHP version:*PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/apc.so' - /usr/lib64/php/modules/apc.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP 5.6.30 (cli) (built: Jan 19 2017 22:50:24)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Nextcloud version:** (11.0.3)

**Where did you install Nextcloud from:*Download from web page*

Login as admin user into your Nextcloud and access

**Comment by githubos1** [comment]
difficult to understand what your problem is, but did you check you config.php ??
Look for the following line:
'allow_user_to_change_display_name' => false,

I had a similar sounding problem ... If this is set to "FALSE", no user entry could be changed.. not even by ADMINS..

'allow_user_to_change_display_name' => true,        will allow changes again !!

Regards

**Comment by MorrisJobke** [comment]
> I had a similar sounding problem ... If this is set to "FALSE", no user entry could be changed.. not even by ADMINS..
> 
> 'allow_user_to_change_display_name' => true, will allow changes again !!

Yep - sounds like that. Closing
