### ISSUE TITLE
EventReminderJob SQL Exception

### ISSUE THREAD

**Issue by michaelfliegner** [nextcloud/server#49101]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

{"reqId":"bK8aeCSjJPBlke0KFfTm","level":3,"time":"2024-11-05T16:36:19+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":"Error while running background job OCA\\DAV\\BackgroundJob\\EventReminderJob (id: 13, arguments: null)","userAgent":"--","version":"30.0.0.14","exception":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing a query: SQLSTATE[42803]: Grouping error: 7 ERROR:  column \"cr.id\" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: SELECT \"cr\".*, \"co\".\"calendardata\", \"c\".\"displayname\", \"c\".\"...\n               ^","Code":7,"Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1943,"function":"convert","class":"Doctrine\\DBAL\\Driver\\API\\PostgreSQL\\ExceptionConverter","type":"->","args":[["Doctrine\\DBAL\\Driver\\PDO\\Exception"],["Doctrine\\DBAL\\Query"]]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1885,"function":"handleDriverException","class":"Doctrine\\DBAL\\Connection","type":"->","args":[["Doctrine\\DBAL\\Driver\\PDO\\Exception"],["Doctrine\\DBAL\\Query"]]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1106,"function":"convertExceptionDuringQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":[["Doctrine\\DBAL\\Driver\\PDO\\Exception"],"SELECT \"cr\".*, \"co\".\"calendardata\", \"c\".\"displayname\", \"c\".\"principaluri\", \"cr\".\"notification_date\", \"cr\".\"event_hash\", \"cr\".\"type\" FROM \"oc_calendar_reminders\" \"cr\" INNER JOIN \"oc_calendarobjects\" \"co\" ON \"cr\".\"object_id\" = \"co\".\"id\" INNER JOIN \"oc_calendars\" \"c\" ON \"cr\".\"calendar_id\" = \"c\".\"id\" WHERE \"cr\".\"notification_date\" <= ? GROUP BY \"cr\".\"event_hash\", \"cr\".\"notification_date\", \"cr\".\"type\"",[1730824579],[2]]},{"file":"/var/www/html/lib/private/DB/Connection.php","line":415,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT \"cr\".*, \"co\".\"calendardata\", \"c\".\"displayname\", \"c\".\"principaluri\", \"cr\".\"notification_date\", \"cr\".\"event_hash\", \"cr\".\"type\" FROM \"oc_calendar_reminders\" \"cr\" INNER JOIN \"oc_calendarobjects\" \"co\" ON \"cr\".\"object_id\" = \"co\".\"id\" INNER JOIN \"oc_calendars\" \"c\" ON \"cr\".\"calendar_id\" = \"c\".\"id\" WHERE \"cr\".\"notification_date\" <= ? GROUP BY \"cr\".\"event_hash\", \"cr\".\"notification_date\", \"cr\".\"type\"",[1730824579],[2],null]},{"file":"/var/www/html/lib/private/DB/ConnectionAdapter.php","line":50,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT \"cr\".*, \"co\".\"calendardata\", \"c\".\"displayname\", \"c\".\"principaluri\", \"cr\".\"notification_date\", \"cr\".\"event_hash\", \"cr\".\"type\" FROM \"oc_calendar_reminders\" \"cr\" INNER JOIN \"oc_calendarobjects\" \"co\" ON \"cr\".\"object_id\" = \"co\".\"id\" INNER JOIN \"oc_calendars\" \"c\" ON \"cr\".\"calendar_id\" = \"c\".\"id\" WHERE \"cr\".\"notification_date\" <= :dcValue1 GROUP BY \"cr\".\"event_hash\", \"cr\".\"notification_date\", \"cr\".\"type\"",[1730824579],[2]]},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":272,"function":"executeQuery","class":"OC\\DB\\ConnectionAdapter","type":"->","args":["SELECT `cr`.*, `co`.`calendardata`, `c`.`displayname`, `c`.`principaluri`, `cr`.`notification_date`, `cr`.`event_hash`, `cr`.`type` FROM `*PREFIX*calendar_reminders` `cr` INNER JOIN `*PREFIX*calendarobjects` `co` ON `cr`.`object_id` = `co`.`id` INNER JOIN `*PREFIX*calendars` `c` ON `cr`.`calendar_id` = `c`.`id` WHERE `cr`.`notification_date` <= :dcValue1 GROUP BY `cr`.`event_hash`, `cr`.`notification_date`, `cr`.`type`",[1730824579],[2]]},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":249,"function":"executeQuery","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[["OC\\DB\\ConnectionAdapter"]]},{"file":"/var/www/html/apps/dav/lib/CalDAV/Reminder/Backend.php","line":53,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/CalDAV/Reminder/ReminderService.php","line":104,"function":"getRemindersToProcess","class":"OCA\\DAV\\CalDAV\\Reminder\\Backend","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/BackgroundJob/EventReminderJob.php","line":50,"function":"processReminders","class":"OCA\\DAV\\CalDAV\\Reminder\\ReminderService","type":"->","args":[]},{"file":"/var/www/html/lib/public/BackgroundJob/Job.php","line":61,"function":"run","class":"OCA\\DAV\\BackgroundJob\\EventReminderJob","type":"->","args":[null]},{"file":"/var/www/html/lib/public/BackgroundJob/TimedJob.php","line":83,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->","args":[["OC\\BackgroundJob\\JobList"]]},{"file":"/var/www/html/lib/public/BackgroundJob/TimedJob.php","line":73,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->","args":[["OC\\BackgroundJob\\JobList"]]},{"file":"/var/www/html/cron.php","line":162,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->","args":[["OC\\BackgroundJob\\JobList"]]}],"File":"/var/www/html/3rdparty/doctrine/dbal/src/Driver/API/PostgreSQL/ExceptionConverter.php","Line":87,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDO\\Exception","Message":"SQLSTATE[42803]: Grouping error: 7 ERROR:  column \"cr.id\" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: SELECT \"cr\".*, \"co\".\"calendardata\", \"c\".\"displayname\", \"c\".\"...\n               ^","Code":7,"Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":132,"function":"new","class":"Doctrine\\DBAL\\Driver\\PDO\\Exception","type":"::","args":[["PDOException",["42803",7,"ERROR:  column \"cr.id\" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: SELECT \"cr\".*, \"co\".\"calendardata\", \"c\".\"displayname\", \"c\".\"...\n               ^"]]]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1099,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->","args":[]},{"file":"/var/www/html/lib/private/DB/Connection.php","line":415,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT \"cr\".*, \"co\".\"calendardata\", \"c\".\"displayname\", \"c\".\"principaluri\", \"cr\".\"notification_date\", \"cr\".\"event_hash\", \"cr\".\"type\" FROM \"oc_calendar_reminders\" \"cr\" INNER JOIN \"oc_calendarobjects\" \"co\" ON \"cr\".\"object_id\" = \"co\".\"id\" INNER JOIN \"oc_calendars\" \"c\" ON \"cr\".\"calendar_id\" = \"c\".\"id\" WHERE \"cr\".\"notification_date\" <= ? GROUP BY \"cr\".\"event_hash\", \"cr\".\"notification_date\", \"cr\".\"type\"",[1730824579],[2],null]},{"file":"/var/www/html/lib/private/DB/ConnectionAdapter.php","line":50,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT \"cr\".*, \"co\".\"calendardata\", \"c\".\"displayname\", \"c\".\"principaluri\", \"cr\".\"notification_date\", \"cr\".\"event_hash\", \"cr\".\"type\" FROM \"oc_calendar_reminders\" \"cr\" INNER JOIN \"oc_calendarobjects\" \"co\" ON \"cr\".\"object_id\" = \"co\".\"id\" INNER JOIN \"oc_calendars\" \"c\" ON \"cr\".\"calendar_id\" = \"c\".\"id\" WHERE \"cr\".\"notification_date\" <= :dcValue1 GROUP BY \"cr\".\"event_hash\", \"cr\".\"notification_date\", \"cr\".\"type\"",[1730824579],[2]]},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":272,"function":"executeQuery","class":"OC\\DB\\ConnectionAdapter","type":"->","args":["SELECT `cr`.*, `co`.`calendardata`, `c`.`displayname`, `c`.`principaluri`, `cr`.`notification_date`, `cr`.`event_hash`, `cr`.`type` FROM `*PREFIX*calendar_reminders` `cr` INNER JOIN `*PREFIX*calendarobjects` `co` ON `cr`.`object_id` = `co`.`id` INNER JOIN `*PREFIX*calendars` `c` ON `cr`.`calendar_id` = `c`.`id` WHERE `cr`.`notification_date` <= :dcValue1 GROUP BY `cr`.`event_hash`, `cr`.`notification_date`, `cr`.`type`",[1730824579],[2]]},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":249,"function":"executeQuery","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[["OC\\DB\\ConnectionAdapter"]]},{"file":"/var/www/html/apps/dav/lib/CalDAV/Reminder/Backend.php","line":53,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/CalDAV/Reminder/ReminderService.php","line":104,"function":"getRemindersToProcess","class":"OCA\\DAV\\CalDAV\\Reminder\\Backend","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/BackgroundJob/EventReminderJob.php","line":50,"function":"processReminders","class":"OCA\\DAV\\CalDAV\\Reminder\\ReminderService","type":"->","args":[]},{"file":"/var/www/html/lib/public/BackgroundJob/Job.php","line":61,"function":"run","class":"OCA\\DAV\\BackgroundJob\\EventReminderJob","type":"->","args":[null]},{"file":"/var/www/html/lib/public/BackgroundJob/TimedJob.php","line":83,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->","args":[["OC\\BackgroundJob\\JobList"]]},{"file":"/var/www/html/lib/public/BackgroundJob/TimedJob.php","line":73,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->","args":[["OC\\BackgroundJob\\JobList"]]},{"file":"/var/www/html/cron.php","line":162,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->","args":[["OC\\BackgroundJob\\JobList"]]}],"File":"/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php","Line":28,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[42803]: Grouping error: 7 ERROR:  column \"cr.id\" must appear in the GROUP BY clause or be used in an aggregate function\nLINE 1: SELECT \"cr\".*, \"co\".\"calendardata\", \"c\".\"displayname\", \"c\".\"...\n               ^","Code":"42803","Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":130,"function":"execute","class":"PDOStatement","type":"->","args":[null]},{"file":"/var/www/html/3rdparty/doctrine/dbal/src/Connection.php","line":1099,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->","args":[]},{"file":"/var/www/html/lib/private/DB/Connection.php","line":415,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["SELECT \"cr\".*, \"co\".\"calendardata\", \"c\".\"displayname\", \"c\".\"principaluri\", \"cr\".\"notification_date\", \"cr\".\"event_hash\", \"cr\".\"type\" FROM \"oc_calendar_reminders\" \"cr\" INNER JOIN \"oc_calendarobjects\" \"co\" ON \"cr\".\"object_id\" = \"co\".\"id\" INNER JOIN \"oc_calendars\" \"c\" ON \"cr\".\"calendar_id\" = \"c\".\"id\" WHERE \"cr\".\"notification_date\" <= ? GROUP BY \"cr\".\"event_hash\", \"cr\".\"notification_date\", \"cr\".\"type\"",[1730824579],[2],null]},{"file":"/var/www/html/lib/private/DB/ConnectionAdapter.php","line":50,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["SELECT \"cr\".*, \"co\".\"calendardata\", \"c\".\"displayname\", \"c\".\"principaluri\", \"cr\".\"notification_date\", \"cr\".\"event_hash\", \"cr\".\"type\" FROM \"oc_calendar_reminders\" \"cr\" INNER JOIN \"oc_calendarobjects\" \"co\" ON \"cr\".\"object_id\" = \"co\".\"id\" INNER JOIN \"oc_calendars\" \"c\" ON \"cr\".\"calendar_id\" = \"c\".\"id\" WHERE \"cr\".\"notification_date\" <= :dcValue1 GROUP BY \"cr\".\"event_hash\", \"cr\".\"notification_date\", \"cr\".\"type\"",[1730824579],[2]]},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":272,"function":"executeQuery","class":"OC\\DB\\ConnectionAdapter","type":"->","args":["SELECT `cr`.*, `co`.`calendardata`, `c`.`displayname`, `c`.`principaluri`, `cr`.`notification_date`, `cr`.`event_hash`, `cr`.`type` FROM `*PREFIX*calendar_reminders` `cr` INNER JOIN `*PREFIX*calendarobjects` `co` ON `cr`.`object_id` = `co`.`id` INNER JOIN `*PREFIX*calendars` `c` ON `cr`.`calendar_id` = `c`.`id` WHERE `cr`.`notification_date` <= :dcValue1 GROUP BY `cr`.`event_hash`, `cr`.`notification_date`, `cr`.`type`",[1730824579],[2]]},{"file":"/var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php","line":249,"function":"executeQuery","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[["OC\\DB\\ConnectionAdapter"]]},{"file":"/var/www/html/apps/dav/lib/CalDAV/Reminder/Backend.php","line":53,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/CalDAV/Reminder/ReminderService.php","line":104,"function":"getRemindersToProcess","class":"OCA\\DAV\\CalDAV\\Reminder\\Backend","type":"->","args":[]},{"file":"/var/www/html/apps/dav/lib/BackgroundJob/EventReminderJob.php","line":50,"function":"processReminders","class":"OCA\\DAV\\CalDAV\\Reminder\\ReminderService","type":"->","args":[]},{"file":"/var/www/html/lib/public/BackgroundJob/Job.php","line":61,"function":"run","class":"OCA\\DAV\\BackgroundJob\\EventReminderJob","type":"->","args":[null]},{"file":"/var/www/html/lib/public/BackgroundJob/TimedJob.php","line":83,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->","args":[["OC\\BackgroundJob\\JobList"]]},{"file":"/var/www/html/lib/public/BackgroundJob/TimedJob.php","line":73,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->","args":[["OC\\BackgroundJob\\JobList"]]},{"file":"/var/www/html/cron.php","line":162,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->","args":[["OC\\BackgroundJob\\JobList"]]}],"File":"/var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","Line":130}},"message":"Error while running background job OCA\\DAV\\BackgroundJob\\EventReminderJob (id: 13, arguments: null)","exception":[],"CustomMessage":"Error while running background job OCA\\DAV\\BackgroundJob\\EventReminderJob (id: 13, arguments: null)"},"id":"672a4a4daf805"}

### Steps to reproduce

1.
2.
3.

### Expected behavior

Shouldn't

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### List of activated Apps

abled:
  - activity: 3.0.0
  - admin_audit: 1.20.0
  - announcementcenter: 7.0.1
  - bruteforcesettings: 3.0.0
  - calendar: 5.0.1
  - checksum: 1.2.5
  - circles: 30.0.0-dev
  - cloud_federation_api: 1.13.0
  - collectives: 2.14.4
  - comments: 1.20.1
  - contacts: 6.1.0
  - contactsinteraction: 1.11.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - deck: 1.14.1
  - drawio: 3.0.3
  - end_to_end_encryption: 1.16.1
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_antivirus: 5.6.0
  - files_confidential: 3.0.3
  - files_downloadlimit: 3.0.0
  - files_fulltextsearch: 30.0.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_retention: 1.19.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - fulltextsearch: 30.0.0
  - fulltextsearch_elasticsearch: 30.0.0
  - groupfolders: 18.0.3
  - integration_google: 3.1.0
  - intros: 1.0.2
  - libresign: 10.0.2
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - mail: 4.0.2
  - memories: 7.4.1
  - nextcloud-aio: 0.6.0
  - nextcloud_announcements: 2.0.0
  - notes: 4.11.0
  - notifications: 3.0.0
  - notify_push: 0.7.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - photos: 3.0.2
  - polls: 7.2.4
  - previewgenerator: 5.6.0
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - quota_warning: 1.20.0
  - recognize: 8.1.1
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - richdocuments: 8.5.2
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - smb_test: 0.3.10
  - snappymail: 2.38.2
  - spreed: 20.0.1
  - support: 2.0.0
  - survey_client: 2.0.0
  - systemtags: 1.20.0
  - tables: 0.8.1
  - tasks: 0.16.1
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - twofactor_totp: 12.0.0-dev
  - twofactor_webauthn: 2.0.0
  - user_migration: 7.0.1
  - user_saml: 6.3.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - whiteboard: 1.0.4
  - workflow_script: 1.15.0
  - workflowengine: 2.12.0
Disabled:
  - encryption: 2.18.0
  - files_external: 1.22.0
  - integration_gitlab: 3.1.2 (installed 3.1.2)
  - signlive: 0.9.9 (installed 0.9.9)
  - suspicious_login: 8.0.0
  - twofactor_nextcloud_notification: 4.0.0
  - user_ldap: 1.21.0

**Comment by kesselb** [comment]
Thanks for your bug report.

Fixed in 30.0.1 with https://github.com/nextcloud/server/pull/48211.
