### ISSUE TITLE
Add a job to clear the old (<NC25) CSS cache (one-time)

### ISSUE THREAD

**Issue by Justinzobel** [nextcloud/server#49108]
In the `occ maintenance:repair` job I see `JS cache cleared` but it would be nice to also clear the CSS cache as well.

**Comment by solracsf** [comment]
What CSS cache?
JS cache is handled here: https://github.com/nextcloud/server/blob/master/lib/private/Template/JSCombiner.php

Note we're talking about server-side caches, not client side.

Please fix me if I'm wrong and point me to the right direction.

**Comment by Justinzobel** [comment]
I mean the `appdata_xxxxx/css` folder in the Nextcloud data folder on the server.

**Comment by joshtrichards** [comment]
There isn't one these days. It was removed in NC25: #32261

https://github.com/nextcloud/server/blob/f4058a2432f748ffff6d7e45f2fb79ca383f8dd1/lib/private/Template/SCSSCacher.php#L101

**Comment by SimJoSt** [comment]
I'm happy I found this issue, as I found the same folder with CSS from old uninstalled apps.
Apparently the cleanup task mention in the issue comment linked before was not implemented.
