### ISSUE TITLE
Template picker UX improvements

### ISSUE THREAD

**Issue by juliusknorr** [nextcloud/server#49109]
After discussion with @marcoambrosini and @pedropintosilva we agreed that the template picker dialog has some UX issues:

After entering the name you get a list of templates:
![Image](https://github.com/user-attachments/assets/2110e1a8-544b-416f-8261-c9e211f42089)

Currently the list is acting like a option element where you select a template and then need to click create. We got multiple reports that this is not intuitive.

I see the following options
- Support double clicking on a template (this could be a very quick win)
- Make the template previews act like buttons that immediately create the file on click
  - Might be debatable if we should remove the create button or keep it to still have a primary flow to continue creating without selecting any specific template (empty file)

@elzody @nimishavijay Would be curious about your thoughts here as well

**Comment by jancborchardt** [comment]
> Support double clicking on a template (this could be a very quick win)

Yeah, fully agree with that, simple quick win in the short term.
If we stick with the 2-step flow, one of the templates (probably the blank one initially, and in the future the last one used) should also be selected by default.

> Make the template previews act like buttons that immediately create the file on click 

Seems fine as well to be honest, way more direct and quick flow.

**Comment by luka-nextcloud** [comment]
> Support double clicking on a template (this could be a very quick win)

I agree with this option.

**Comment by marcoambrosini** [comment]
I like both options, but if we keep the create button, we should also have a selected state always active, so these would behave effectively like a radio group. Otherwise this UI would be a bit ambiguous. 

Apple pages below for reference:

![Image](https://github.com/user-attachments/assets/b12644e1-98ad-4d56-8066-ab74140bf2e3)

**Comment by juliusknorr** [comment]
I also checked on the web:
- Google docs has no selection but single click creates the document
- Apple pages on the web does it with a select, highlight and create option.
- Onedrive creates on single click but has dedicated [buttons they show on hover](https://github.com/user-attachments/assets/1b5fb016-6e08-42b2-80d3-66a8014e0d86)


The active style we already have, but maybe it is not obvious enough? 

![Image](https://github.com/user-attachments/assets/c49fb981-5797-408a-9632-daf45983beae)



I'd say lets stick with the create button and do a first step and we can see if we still get usability complaints afterwards:
- Make double click work on the template files
- If you select a template file and click it for the second time, we can also consider that a confirmation

**Comment by marcoambrosini** [comment]
What I mean is that ideally by default one of them should always be highlighted, either blank or last used

**Comment by juliusknorr** [comment]
Yes, blank one is highlighted by default already
