### ISSUE TITLE
[Bug]: Input fields icon positioning in RTL mode

### ISSUE THREAD

**Issue by alsulami1** [nextcloud/server#49113]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I've found a minor bug in the newly introduced RTL mode for languages such as Arabic. When switching the UI language to Arabic
Input fields icons are positioned to the right, this position doesn't align with expectations for a fully RTL-supported interface.

![Image](https://github.com/user-attachments/assets/a2287099-bf57-43dd-8839-b6e690175252)
![Image](https://github.com/user-attachments/assets/8808acd4-b9df-4ef7-ab8d-229a86e50e86)

### Steps to reproduce

Change Nextcloud language to an RTL language (arabic here as an example)
Use Nextcloud

### Expected behavior

![Image](https://github.com/user-attachments/assets/6c839090-dffa-4c46-8e94-8eacc045362e)
![Image](https://github.com/user-attachments/assets/d52444ae-e79f-4470-92b0-a5a3cfddd7a7)

### Nextcloud Server version

master

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by susnux** [comment]
Moved to components: https://github.com/nextcloud-libraries/nextcloud-vue/issues/6198
