### ISSUE TITLE
Syncing files over 90GB becomes very slow

### ISSUE THREAD

**Issue by cndingwei** [nextcloud/server#49121]
When the file synchronization exceeds 90GB, it becomes very slow, and the Nextcloud client (installed on WIndows Server 2019) may even exit directly. Is there any good solution? I googled various methods and tried them, but the problem could not be solved.
Same environment (server and configuration), owncloud has no problem.

**Comment by joshtrichards** [comment]
Please post your question on the help forum - https://help.nextcloud.com

And/or fill out the actual Issue template so we have more context. If your situation is specific to the Desktop client, the place to report it is https://github.com/nextcloud/desktop
