### ISSUE TITLE
Feature Request: RDP-App for Nextcloud

### ISSUE THREAD

**Issue by FlorianTaut** [nextcloud/server#4912]
Some of you may know Cozy.io

They have an app for integrated rdp connections.
probably something like guacamole: https://github.com/apache/incubator-guacamole-server

Dont you guys think this would be nice for nextcloud too?

The Producer of the app published to source here: https://github.com/citronneur/mstsc.js
Maybe somebody wants to try building such an App for Nextcloud 12 or 13...

I would try it by my self but i'm new to coding and think this point is way to hard for newbies :smile: 

I give myself a shot and try to build something!

**Comment by LukasReschke** [comment]
I'd say this is something that should rather be discussed on help.nextcloud.com

**Comment by MorrisJobke** [comment]
> The Producer of the app published to source here: https://github.com/citronneur/mstsc.js
> Maybe somebody wants to try building such an App for Nextcloud 12 or 13...
> 
> I would try it by my self but i'm new to coding and think this point is way to hard for newbies 😄

Yep - an app makes sense. As this is the server component here. It would be good to either discuss this in the forums. This is neither an bug nor an enhancement for the server component itself.

I will close this one here. If somebody wants to work on this: go for it 🚀

**Comment by markusbegerow** [comment]
fyi https://github.com/markusbegerow/nextcloud-web-rdp
