### ISSUE TITLE
[Bug]: The "Update all" button to update all apps does not work

### ISSUE THREAD

**Issue by LM-vb** [nextcloud/server#49144]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

On NC 30.0.2

When updates to several apps are available, a button "Update all" appears on the Apps > Updates page. However, clicking on this button does not trigger an update of all the apps but seems to do nothing. Clicking on the "Update to ..." button of the respective apps works as expected.

Console gives the following error when clicking the "Update all" button:
![Image](https://github.com/user-attachments/assets/29c22815-9b10-4e3f-bb86-6d3164aa3021)

### Steps to reproduce

1. Wait for updates for several apps
2. Click on "Update all" on the Apps > Updates page
3. No updates to the apps are applied

### Expected behavior

All apps should be updated.

### Nextcloud Server version

30

### Operating system

Other

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

PostgreSQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            ***REMOVED SENSITIVE VALUE***
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "default_phone_region": "DE",
        "version": "30.0.2.2",
        "overwrite.cli.url": ***REMOVED SENSITIVE VALUE***,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "skeletondirectory": "",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "timeout": 0
        },
        "session_lifetime": 3600,
        "session_keepalive": false,
        "tempdirectory": ***REMOVED SENSITIVE VALUE***,
        "remember_login_cookie_lifetime": 0,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "maintenance": false,
        "theme": "",
        "loglevel": 1,
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "default_language": "en",
        "default_locale": "en_GB",
        "knowledgebaseenabled": false,
        "simpleSignUpLink.shown": false,
        "auth.webauthn.enabled": false,
        "updater.release.channel": "stable",
        "trashbin_retention_obligation": "auto, 7",
        "versions_retention_obligation": "auto, 7",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance_window_start": 2,
        "preview_max_filesize_image": 100
    }
}

### List of activated Apps

Enabled:
  - activity: 3.0.0
  - admin_audit: 1.20.0
  - announcementcenter: 7.0.1
  - app_api: 4.0.0
  - bruteforcesettings: 3.0.0
  - checksum: 1.2.5
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contactsinteraction: 1.11.0
  - dav: 1.31.1
  - federatedfilesharing: 1.20.0
  - files: 2.2.0
  - files_downloadlimit: 3.0.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - files_zip: 2.1.0
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - nextcloud_announcements: 2.0.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - photos: 3.0.2
  - previewgenerator: 5.6.0
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - quota_warning: 1.20.0
  - related_resources: 1.5.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - support: 2.0.0
  - survey_client: 2.0.0
  - systemtags: 1.20.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - updatenotification: 1.20.0
  - viewer: 3.0.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - circles: 30.0.0 (installed 22.1.1)
  - contacts: 6.0.0 (installed 6.0.0)
  - dashboard: 7.10.0 (installed 7.0.0)
  - encryption: 2.18.0
  - federation: 1.20.0 (installed 1.10.1)
  - files_automatedtagging: 1.19.0 (installed 1.19.0)
  - files_external: 1.22.0
  - firstrunwizard: 3.0.0 (installed 2.9.0)
  - impersonate: 1.17.0 (installed 1.17.0)
  - recommendations: 3.0.0 (installed 0.8.0)
  - suspicious_login: 8.0.0
  - text: 4.1.0 (installed 3.1.0)
  - theming_customcss: 1.17.0 (installed 1.17.0)
  - twofactor_nextcloud_notification: 4.0.0
  - twofactor_totp: 12.0.0-dev
  - user_ldap: 1.21.0
  - user_status: 1.10.0 (installed 1.0.1)
  - weather_status: 1.10.0 (installed 1.0.0)

**Comment by tocsinde** [comment]
Got exactly the same error while trying to remove deactivated apps.

**Comment by joshtrichards** [comment]
> Got exactly the same error while trying to remove deactivated apps.

#49193

**Comment by gelbphoenix** [comment]
As seen by the three issues closed on [Nov 19, 2024](https://github.com/nextcloud/server/issues/49144#event-1685690691) the issue persists in version 30.0.2 and didn't made it into that release.

For NC admins looking at this issue: Please wait until the release of a possible version 30.0.3 (and the update of your NC to said version) as that version could bring this bug fix.

**Comment by j-lakeman** [comment]
Or meanwhile with access to the server: `occ app:update --all`

**Comment by Lawkss** [comment]
Still broken in 30.0.3

**Comment by susnux** [comment]
> Still broken in 30.0.3

Yes as you can see in the pull request, it is merged for 30.0.4

**Comment by susnux** [comment]
This issue was resolved on current master branch and backported to Nextcloud 30.0.4
If you encounter a similar bug after updating to 30.0.4, please open a new ticket.

For general discussions please use [our forums](https://help.nextcloud.com/).
