### ISSUE TITLE
Nextcloud Outlook connector requires SOAP extension for PHP

### ISSUE THREAD

**Issue by LevAnni777** [nextcloud/server#49154]
Hi,

Nextcloud Outlook connector requires SOAP extension for PHP. I think that the soap extension will be useful for other tools as well. Please add this extension.

![Image](https://github.com/user-attachments/assets/d55a8abe-c3e8-4968-8941-a698a5138435)

Thanks

**Comment by joshtrichards** [comment]
> I think that the soap extension will be useful for other tools as well. Please add this extension.

So install it. We don't control your server. :-)
