### ISSUE TITLE
Password reset mail not using user's language

### ISSUE THREAD

**Issue by scf-wgross** [nextcloud/server#4915]
### Steps to reproduce
1. Enter wrong password and then press password reset button
2. Receive password reset link via e-mail
3.

### Expected behaviour
E-mail should use user's language

### Actual behaviour
E-mail uses instead default language (as acquired from browser?)

### Server configuration

**Operating system**:
OpenLeap 42.2

**Web server:**
Apache 2.4.23-8.3.1

**Database:**
Maria-DB 10.0.29-18.1

**PHP version:**
php 7.0.7-14.3.1

**Nextcloud version:** (see Nextcloud admin page)
11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
OpenSuse repository

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Mozilla Firefox 53.0

**Operating system:**
Windows 7 Pro 64bit

### Logs
No relevant entries in these log files

**Comment by MorrisJobke** [comment]
cc @nickvergessen haven't you fixed this for 11?

**Comment by scf-wgross** [comment]
User's language is used with share links sent by e-mail, but then the user is already logged in.

**Comment by nickvergessen** [comment]
Well it uses the browsers language, since the user is not logged in. We can of course change it and use the language the potential user had selected. But not really a but for me.

**Comment by nickvergessen** [comment]
We can easily change the language of the actual text, however there is currently no option to set the language for the header/footer stuff.

**Comment by scf-wgross** [comment]
Well, you're right, it's really not such a big thing. It stems from our rather special situation of a lab with people speaking different languages sharing a local PC to access their data.
