### ISSUE TITLE
Which apps support encryption?

### ISSUE THREAD

**Issue by github3845** [nextcloud/server#49169]
I hope this is the right place to tell about my experience with nextcloud. I have been using it on and off since its inception. However, I stopped using it because from what i remember:
- it does not support delta sync (not sure if it resumes interrupted transfers, probably not?)
- per-user key encryption was deprecated (it's not anymore? hopefully?)
- **E2E encryption does not work in the browser and is unreliable**
- **contacts and other apps are not encrypted in any way, for example also the smtp/imap password in the mail app, or thumbnails generated by the gallery app**
- it did not support syncing a folder on Android (which it now finally does woohoooo!!!)
- it does not have (official or working) external storage apps for cheap and/or popular cloud storage providers (google drive, opendrive, jottacloud, etc)
- the activity app keeps a cleartext log of files/file names that were there, even after they are deleted

Please correct me, if I am wrong about any of these things.

So.. does the new photos app support the server key/user key encryption? Does it still generate unencrypted thumbnails? What about the tags it generates?

 What about the email app? Does it still store the imap login info in plaintext? 

Is the activity app history encrypted now?

Which apps support encryption?

Thanks

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by joshtrichards** [comment]
Hi @github3845!

All reasonable questions, but your query would be best posted at the community forum: https://help.nextcloud.com
