### ISSUE TITLE
↔️ Make app order configurable

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#4917]
Edit by @jancborchardt with spec:

- **In general, remember that regular users rarely change anything. As such this is a feature for quite advanced people and it is an investment to maintain and test this properly.**
- The app sorting we talk about should be purely user-side. Admins already have means to shuffle apps around, either in the code or using the apporder app. Also, admins should not dictate the personal order of things in your Nextcloud.
- Moving apps should happen via drag&drop directly in the top bar.
- For keyboard accessibility, we could also think about making it possible to move an app by focusing it, then using the arrow keys (if need be with Ctrl or Shift as modifier). Is there a standard there?
- The default order still needs to make sense.
- The app which is sorted first should automatically be used as the default app.
- If an app disables the app which is sorted first (or if it breaks after update) the next app should simply take its place.
- "Reset to default" isn’t really necessary, as you can simply drag something back.
- Changing maximum of displayed apps via dragging the "More" button could be possible. But better to do it in a separate pull request.

What you can do to help:

- :computer: Dive into the code and make this happen. Please follow the spec outlined above, and remember to work step-by-step. :+1: 
- :money_with_wings: Donate to the [bounty for this issue on Bountysource](https://www.bountysource.com/issues/45281242-make-app-order-configurable). :slightly_smiling_face: 

---------------------------

Admins should be able to

- set an default order for apps
- set, whether users should be allowed to change the order of the apps

If users are allowed to change the order by themself, this configuration should be handles via drag-and-drop in the app menu.

We could use https://github.com/juliushaertl/apporder/ as base ...
Follow up: https://github.com/juliushaertl/apporder/issues/29

@juliushaertl @nextcloud/designers

**Comment by hitam4450** [comment]
I certainly agree! :thumbsup:

**Comment by dan-nkl** [comment]
> Each user should be able to reaarange its app order
But only if allowed to! 😄

**Comment by jancborchardt** [comment]
So this would be another cool modification of @juliushaertl to include in the core server. :)

Some considerations:

- We should decide if this should be an admin setting at all or only on the user side.
- We need to make sure apps aren’t moved by accident.
- The default order still needs to make sense.
- The app which is sorted first should automatically be used as the default app.
- (Another relevant means of sorting could be frequency of use, although that will result in the list jumping around a lot in the beginning.)

**Comment by pixelipo** [comment]
Adding one more point to your considerations, @jancborchardt 

- what if user (or admin) disables app which is sorted first (or if it breaks after update)

**Comment by jancborchardt** [comment]
@pixelipo in that case the next app should take its place, probably simplest solution. Maybe there should be some feedback, but that's a slightly different topic.

**Comment by patschi** [comment]
Because of recent discussion in #5135 any handling of maximum shown apps could be take into consideration as well - fixed or even in a more dynamic way, maybe manageable for each user. For example by moving the "more apps"-toggle to the left/right to show less or more apps. Or may it be out-of-scope of this implementation? If so, we could at least keep it in mind for any upcoming versions.

**Comment by olantrust** [comment]
Great enhancement.
1) Will this view be scalable, with perhaps a slide scaler?
That would make it significantly more useful (including for those with different sight or different screen sizes). 
2) Will there be the ability here (or elsewhere) to create preview plugins (as available in KDE's Dolphin for example), to help with visual search/recognition before opening a file?

**Comment by jancborchardt** [comment]
@patschi it's out of scope in general cause it's a very edge-case customization option which will mainly increase the amount of stuff we need to test and can possibly break. This, apart from the nicer UX, is a big reason why we reduce options and make the defaults great. :)

**Comment by tomastd** [comment]
One question, how can a user reset a customized app ordering? 
It would be nice to have a "reset to default" option, isn't it?

**Comment by phlegx** [comment]
News about this feature?

**Comment by danger89** [comment]
I really would love to see this behavior become part of the core of Nextcloud (by default).

**Comment by jancborchardt** [comment]
I will now hide every non-contributing comment. What you can do instead:

- :computer: Dive into the code and make this happen. All the pointers should be in the thread above. :+1: 
- :money_with_wings: Donate to the [bounty for this issue on Bountysource](https://www.bountysource.com/issues/45281242-make-app-order-configurable). :slightly_smiling_face:

**Comment by jancborchardt** [comment]
Also updated the original post with specification and answer to all considerations raised.

**Comment by damago1** [comment]
Please add the possibility to change default app without having to go to config.php. This should be in GUI. 
The lastes upgrade brought mandatory dashboard. Many users would like to get rid of this 'improvement' and go to Nextcloud directly after login withoug having to extra click on the files icon.

**Comment by szaimen** [comment]
from Julius:

> A proper way would be to ensure that the order can somehow already be handled on the backend side where the apps are sorted already by their predefined order https://github.com/nextcloud/server/blob/da01494a372c5b780ee76807325001afd1190b11/lib/private/NavigationManager.php#L136

> One fairly straight forward attempt might be to emit an event in the server that an app like apporder can then listen to and adjust the navigation, I'm happy to hand over the app and release keys if anyone wants to start working on that, but cleaner would be to implement the sorting directly in server (https://github.com/nextcloud/server/issues/4917)

**Comment by Luticus** [comment]
Just found out that apporder doesn't and won't ever work on nc25+. Features I severely miss are the option to adjust the default order of apps both globally and per user, and the ability to hide app icons while leaving the app enabled. For instance I use the keeweb app to allow users to manipulate keepass databases they have in their NC, but I don't want/need the icon for the app cluttering up my app list for all users. Please consider integrating the full functionality of this app into the standard NC interface as these are features that seem extremely useful, by allowing admins to provide interfaces that are less complex for their users when possible.

**Comment by nawordar** [comment]
> For keyboard accessibility, we could also think about making it possible to move an app by focusing it, then using the arrow keys (if need be with Ctrl or Shift as modifier). Is there a standard there?

The only place where moving something using is possible using keyboard, is moving browser tabs: <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>Page Up</kbd>/<kbd>Page Down</kbd>. If we implemented changing order using keyboard, we would be more accessible than most apps!

Maybe <kbd>Ctrl</kbd> + <kbd>←</kbd>/<kbd>→</kbd>? It normally skips over words in things like `<textarea/>` or text editors, so it doesn't conflict.

Or maybe some "Edit app menu" button? After pressing that button, pressing <kbd>Enter</kbd> wouldn't launch an app, but instead would select the app and pressing left and right arrow would move it. Pressing <kbd>Esc</kbd> or <kbd>Enter</kbd> would exit the icon moving mode.

The editing app menu mode could also be used for hiding icons in a similar way is it is implemented in Firefox. When in that mode, a box with hidden app icons would show up below the app bar. To hide an app icon, just drag it to that box or press the <kbd>↓</kbd> key.

**Comment by adripo** [comment]
> Just found out that apporder doesn't and won't ever work on nc25+. Features I severely miss are the option to adjust the default order of apps both globally and per user, and the ability to hide app icons while leaving the app enabled. For instance I use the keeweb app to allow users to manipulate keepass databases they have in their NC, but I don't want/need the icon for the app cluttering up my app list for all users. Please consider integrating the full functionality of this app into the standard NC interface as these are features that seem extremely useful, by allowing admins to provide interfaces that are less complex for their users when possible.

@jancborchardt I was wondering if there is any **roadmap** or update on this functionality. The Apporder features are crucial to me and this lack of updates is hindering my transition to nc25.

**Comment by ardarandir** [comment]
This app seems to provide the desired functionality and much more: https://apps.nextcloud.com/apps/side_menu

**Comment by joskapista44** [comment]
> This app seems to provide the desired functionality and much more: https://apps.nextcloud.com/apps/side_menu

Not really. If you don't want a new menu on the side just to configure the normal menu, it's not a solution, sorry.

**Comment by m-a-v** [comment]
You can have both.

![image](https://user-images.githubusercontent.com/16197536/222928800-638f090c-0f49-457c-8df9-df196ae0dd0a.png)

 But I agree a simple solution with simple reordering would also do it. This should be configurable without an additional app.

**Comment by pbek** [comment]
How can you have both? Did I miss a setting?

**Comment by m-a-v** [comment]
You can find it in the detailed settings of the top menu (I am using Nextcloud 25.0.4 and Custom Menu 3.6.0).

![image](https://user-images.githubusercontent.com/16197536/222945641-7ca260b3-b818-440c-8994-a2d16e0fe3a4.png)

**Comment by pbek** [comment]
Hah, really! In the admin settings, not the personal settings! Thank you very much, you made my day!

**Comment by m-a-v** [comment]
You're welcome. It's like using a sledgehammer to crack a nut, but it solves the problem.

**Comment by Baptistou** [comment]
> Another possible workaround would be the use of the app "[Custom CSS](https://apps.nextcloud.com/apps/theming_customcss)" I used the following style to hide the music button and put the activity app at the end of the list:

This is an interesting workaround, however CSS cannot solve the issue about keyboard navigation like AppOrder does. See explaination here : [The order property and accessibility](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Ordering_Flex_Items#the_order_property_and_accessibility)

We need either to reorder the navigation bar on server side or to inject custom JavaScript and modify DOM on page load :confused:

**Comment by jancborchardt** [comment]
Discussed with @andyscherzinger and @karlitschek
- This is a user-setting only, no admin setting
- First sorted app will be default app (if set, it will override the default app config setting)
- This has to be a settings block in "Appearance and accessibility", similar to the sorting in "Artificial Intelligence" or the column sorting in Tables so it is both accessible via mouse and keyboard. No sorting by drag & drop directly in the navigation

@nextcloud/designers this would be ready for picking up for a mockup. :)

**Comment by szaimen** [comment]
I can take this over :)

**Comment by szaimen** [comment]
🎉🎉🎉
