### ISSUE TITLE
[Bug]:

### ISSUE THREAD

**Issue by jfsalzmann** [nextcloud/server#49191]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Immediatly after upgrading from Nextcloud 29 to 30, log files became out of control as a giant amount of errors started to be logged, as far as I can see in every moment of accessing any Nextcloud site. 

No error is displayed anywhere in the Nextcloud web UI, nor is any error visible in the mobile apps so far. But I feel that Nextcloud became significantly slower. The only thing that made me aware of the issue initially was this note in the Admin status overview:

```
There are some warnings regarding your setup.
- 1 error in the logs since 9 November 2024, 21:01:57
- [...]
```

Which is an ironic understatement, I figured: logs are so immensely full of errors that after one day, the log file size became 30G+ (see below). 

I discovered that I appearently can change the log level in the Nextcloud configuration, which will hopefully fix the space consumption issue. Log level was set to "debug", which may be a problem in itself as I'm almost certain that I have never set or changed that setting actively, is this the default then?

I have no idea what causes the error or what the error message(s) mean. I'm the kind of nextcloud admin that has no deep understanding of what's happening under the hood.

Also see my comments in the pasted logs below. 

### Steps to reproduce

n/a

### Expected behavior

n/a

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MySQL

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REDACTED***",
            "www.***REDACTED***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REDACTED***",
        "dbtype": "mysql",
        "version": "30.0.2.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "***REDACTED***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "tempdirectory": "***REDACTED***\/data\/tmp\/",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "htaccess.IgnoreFrontController": true,
        "theme": "",
        "loglevel": 2,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "maintenance": false,
        "mysql.utf8mb4": true,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "trashbin_retention_obligation": "30,60",
        "versions_retention_obligation": "30,60",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "maintenance_window_start": 1,
        "defaultapp": "files,dashboard",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

### List of activated Apps

```shell
Enabled:
  - activity: 3.0.0
  - app_api: 4.0.0
  - audioplayer: 3.4.1
  - bruteforcesettings: 3.0.0
  - calendar: 5.0.1
  - camerarawpreviews: 0.8.6
  - circles: 30.0.0
  - cloud_federation_api: 1.13.0
  - comments: 1.20.1
  - contacts: 6.1.0
  - contactsinteraction: 1.11.0
  - dashboard: 7.10.0
  - dav: 1.31.1
  - deck: 1.14.1
  - federatedfilesharing: 1.20.0
  - federation: 1.20.0
  - files: 2.2.0
  - files_automatedtagging: 1.20.0
  - files_downloadlimit: 3.0.0
  - files_external: 1.22.0
  - files_pdfviewer: 3.0.0
  - files_reminders: 1.3.0
  - files_sharing: 1.22.0
  - files_trashbin: 1.20.1
  - files_versions: 1.23.0
  - firstrunwizard: 3.0.0
  - groupfolders: 18.0.3
  - logreader: 3.0.0
  - lookup_server_connector: 1.18.0
  - music: 2.0.1
  - nextcloud_announcements: 2.0.0
  - notes: 4.11.0
  - notifications: 3.0.0
  - oauth2: 1.18.1
  - password_policy: 2.0.0
  - photos: 3.0.2
  - privacy: 2.0.0
  - provisioning_api: 1.20.0
  - recommendations: 3.0.0
  - related_resources: 1.5.0
  - serverinfo: 2.0.0
  - settings: 1.13.0
  - sharebymail: 1.20.0
  - support: 2.0.0
  - survey_client: 2.0.0
  - systemtags: 1.20.0
  - tasks: 0.16.1
  - text: 4.1.0
  - theming: 2.5.0
  - twofactor_backupcodes: 1.19.0
  - updatenotification: 1.20.0
  - user_status: 1.10.0
  - viewer: 3.0.0
  - weather_status: 1.10.0
  - webhook_listeners: 1.1.0-dev
  - workflowengine: 2.12.0
Disabled:
  - admin_audit: 1.20.0
  - encryption: 2.18.0
  - extract: 1.3.6 (installed 1.3.6)
  - files_downloadactivity: 1.16.0 (installed 1.16.0)
  - files_markdown: 2.4.1 (installed 2.4.1)
  - files_rightclick: 0.15.1 (installed 1.6.0)
  - rainloop: 7.2.6 (installed 7.2.6)
  - suspicious_login: 8.0.0
  - twofactor_nextcloud_notification: 4.0.0
  - twofactor_totp: 12.0.0-dev
  - unsplash: 2.2.1 (installed 2.2.1)
  - uploaddetails: 0.1.3 (installed 0.1.3)
  - user_ldap: 1.21.0
```

### Nextcloud Signing status

```shell
No errors have been found.
```

### Nextcloud Logs

```json
(I will only post the smallest set of errors, no point to upload or copy/paste the 30G logs. It always repeats again anyways, even in the same order. All the errors below have a time stamp in exactly the same second. New errors keep coming in even while starring at the web app log page, almost making it crash...)

Debug	no app in context	
OCA\Activity\NotificationGenerator::prepare() threw \InvalidArgumentException which is deprecated. Throw \OCP\Notification\UnknownNotificationException when the notification is not known to your notifier and otherwise handle all \InvalidArgumentException yourself.

Debug	no app in context	
OCA\Text\Notification\Notifier::prepare() threw \InvalidArgumentException which is deprecated. Throw \OCP\Notification\UnknownNotificationException when the notification is not known to your notifier and otherwise handle all \InvalidArgumentException yourself.

Debug	no app in context	
OCA\NextcloudAnnouncements\Notification\Notifier::prepare() threw \InvalidArgumentException which is deprecated. Throw \OCP\Notification\UnknownNotificationException when the notification is not known to your notifier and otherwise handle all \InvalidArgumentException yourself.

Debug	no app in context	
OCA\FirstRunWizard\Notification\Notifier::prepare() threw \InvalidArgumentException which is deprecated. Throw \OCP\Notification\UnknownNotificationException when the notification is not known to your notifier and otherwise handle all \InvalidArgumentException yourself.

Debug	no app in context	
OCA\Deck\Notification\Notifier::prepare() threw \InvalidArgumentException which is deprecated. Throw \OCP\Notification\UnknownNotificationException when the notification is not known to your notifier and otherwise handle all \InvalidArgumentException yourself.

Debug	no app in context	
OCA\Calendar\Notification\Notifier::prepare() threw \InvalidArgumentException which is deprecated. Throw \OCP\Notification\UnknownNotificationException when the notification is not known to your notifier and otherwise handle all \InvalidArgumentException yourself.

Debug	no app in context	
OCA\AppAPI\Notifications\ExAppNotifier::prepare() threw \InvalidArgumentException which is deprecated. Throw \OCP\Notification\UnknownNotificationException when the notification is not known to your notifier and otherwise handle all \InvalidArgumentException yourself.

Debug	app_api	
ExApp "survey_client" not found.
```

### Additional info

File size of log files

```
ssh-******@******:~/hosts/******/data$ du -sh ./*
[...]
2,7G    ./nextcloud.log
33G     ./nextcloud.log.1
[...]
```

**Comment by joshtrichards** [comment]
> I have no idea what causes the error or what the error message(s) mean. I'm the kind of nextcloud admin that has no deep understanding of what's happening under the hood.

They're not errors, but debug messages.

> I discovered that I appearently can change the log level in the Nextcloud configuration, which will hopefully fix the space consumption issue. Log level was set to "debug", which may be a problem in itself as I'm almost certain that I have never set or changed that setting actively, is this the default then?

This would be why you saw those log entries. And, no, the default is `2` (WARN level) not DEBUG.

> New errors keep coming in even while starring at the web app log page,

Is it possible you inadvertently toggled on debug level logging from Web UI? In addition to changing it directly in your `config.php`, it's possible to change it there.

**Comment by jfsalzmann** [comment]
Thanks for the comments. As I wrote, I can definetely say that I have never changed the log level. Even if I would have done so, I would probably not have expected to end up with a 30G log file within 24h after a major version update... :)

In any case, I can happily report that both log file size & the recent post-update performance issues seem resolved since I changed the log levels.

**Comment by susnux** [comment]
Glad to hear that it fixed for you now!
