### ISSUE TITLE
Missing secure flag on session cookie

### ISSUE THREAD

**Issue by wizzn** [nextcloud/server#4920]
### Steps to reproduce
1. `curl -v https://your-nextcloud-domain.here`
2. Have a look at `Set-Cookie: INSTANCE_ID:RANDOM_COOKIE_STRING`
(example: `< Set-Cookie: INSTANCE_ID=q5l0sfo60g756jg8jutu5r59d4; path=/; HttpOnly`)
3. Check that the `Secure` attribute is not set
4. Validate that `https://observatory.mozilla.org/analyze.html?host=your-nextcloud-domain.here` reports something like this: _Cookies set without using the Secure flag, but transmission over HTTP prevented by HSTS_

### Expected behaviour
Session cookie should (like the other cookies) contain a secure flag

### Actual behaviour
Session cookie does not contain secure flag

### Server configuration

**Operating system**:
Debian Linux 

**Web server:**
nginx/1.6.2

**Database:**
mysql/5.5.55

**PHP version:**
PHP 5.6.30

**Nextcloud version:**
11.0.3 (production)

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - audioplayer: 1.5.1
  - calendar: 1.5.2
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.1.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml

**Nextcloud configuration:**
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "some.domain",
            "www.some.domain"
        ],
        "datadirectory": "\/ncdata",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "11.0.3.2",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "open_basedir": "\/dev\/urandom",
        "instanceid": "someInstanceId",
        "mail_from_address": "nextcloud",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_domain": "some.domain",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "smtp.some-hoster.domain",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "appstore.experimental.enabled": false,
        "updater.release.channel": "production"
    }
}
**Are you using encryption:**
no

### Client configuration
Google Chrome 59.0.3071.47

**Operating system:**
macOS

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by LukasReschke** [comment]
The secure flag is set after authentication and the session ID is regenerated, so while a minor annoyance there is no big issue here as an attacker would also require the oc_sessionPassprase.
