### ISSUE TITLE
[Bug]: Cannot remove app

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#49255]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When trying to remove a disbled app from the web interface, the UI is not reactive, and the action is not executed. Instread a JS error appears in the browser console:

```
TypeError: this.$store.dispatch(...) is undefined
    NextJS 11
        remove
        click
        hn
        n
        hn
        $emit
        click
        hn
        n
        _wrapper
        r
sentry.js:2:62546
```

Not sure is is sentry, or rather an issue in the apps maangement. I suppose the later though.

Seen on c.nc.c

### Steps to reproduce

1. Have a disabled apps
2. Go to "Apps" → "Disabled apps"
3. Click on "Remove" against that app

### Expected behavior

The app is being removed.

### Nextcloud Server version

30

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

**Comment by blizzz** [comment]
Works on master though. Maybe indeed sentry, @ChristophWurst ?

**Comment by ChristophWurst** [comment]
sentry proxies console.* apis to capture logs. It's a bit misleading because it shows as the logging script. Inspect the trace and you should find the actually logging script.

**Comment by LM-vb** [comment]
Duplicate of #49193?

**Comment by blizzz** [comment]
> sentry proxies console.* apis to capture logs. It's a bit misleading because it shows as the logging script. Inspect the trace and you should find the actually logging script.

![Image](https://github.com/user-attachments/assets/59c2017d-5f1e-47e5-bb6a-1d0d6aa155ff)

that's all and looks quite generic. best guess again apps management. Maybe in connection with external apps?

**Comment by blizzz** [comment]
> Duplicate of [#49193](https://github.com/nextcloud/server/issues/49193)?

I looked at a few other issues… but missed this one  – thanks! Yes, the web part looks the same. Closing therefore.
