### ISSUE TITLE
[Bug]: Error occurred whilst checking server setup (NC 30.0.2)

### ISSUE THREAD

**Issue by wrogner** [nextcloud/server#49286]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

After Upgrade to 30.0.2 the security check provides the following warning:

![Image](https://github.com/user-attachments/assets/fc2b6d9b-0095-4eda-86ed-9b23681a4850)

"Error occurred whilst checking server setup"

### Steps to reproduce

1. upgraded from 29.x -> 30.0.2 (using web updater)
2.-> Administration - Overview

### Expected behavior

Either get a list of issues that can be fixed or 
get status OK

### Nextcloud Server version

30

### Operating system

Other

### PHP engine version

PHP 8.2

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json
Nextcloud installed on Synology NAS from zip
```

### List of activated Apps

```shell
No apps installed
```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

**Comment by kesselb** [comment]
Something in the logs?

**Comment by wrogner** [comment]
I reproduced the effect by going to Overview (15 Nov 10:05):
Error message: Error occurred whilst checking server setup

No message in the logs (tab Logging), last entry 14 Nov 2024, 15:17:22.

**Comment by kesselb** [comment]
Thank you for reporting this issue  :+1: 

I will need your browser console log to investigate this issue.  Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.
</details>

**Comment by wrogner** [comment]
![Image](https://github.com/user-attachments/assets/dcd94bf9-741c-4851-ac9a-2b7f00aff2e7)

This is it.

**Comment by kesselb** [comment]
Check your webserver log's for the gateway timeout. You may have to increase the timeouts if the setup check needs a bit to finish. I'm closing the issue as the provided logs do not look like a bug in Nextcloud, but a configuration issue.

**Comment by wrogner** [comment]
There is not a single entry in the logs and no log specifically for this web portal.

OpenProject provides a log, like other portal based web services. Nextcloud does not.

I should note that I run Nextcloud on a Synology NAS (installed from ZIP).

Having played around a little, there seems no functional deficits or performance penalties.
It could be configuration issues but I run NC out of the box (zip).

Thanks for your help/support.
