### ISSUE TITLE
Uses internal IP for Logo and Background image when connecting through any other domain

### ISSUE THREAD

**Issue by PhilsLab** [nextcloud/server#4928]
### Expected behaviour
Tell us what should happen

### Actual behaviour
I accessed the webpage externally through my domain, this is what i got:
![image](https://cloud.githubusercontent.com/assets/15452526/26172888/390cb56e-3b4a-11e7-8c1b-ba3593a1ceaa.png)
The Nextcloud logo and background are not loaded.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache2

**Database:**
MySQL 5.5

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
12.0beta3

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
manually

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - admin_notifications: 1.0.0
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_downloadactivity: 1.1.1
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - groupfolders: 1.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.0
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - encryption
  - survey_client
  - user_external

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "oclzcuizekhm",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.phils-lab.net",
            "phils-lab.net",
            "192.168.3.3",
            "appnextcloud.phils-lab.int",
            "cloud.phils-lab.int"
        ],
        "datadirectory": "\/mnt\/nc_storage",
        "dbtype": "mysql",
        "version": "12.0.0.20",
        "dbname": "nextcloud",
        "dbhost": "192.168.3.2:3306",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "OC\\Memcache\\APCu",
        "mail_from_address": "cloud",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "phils-lab.net",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "beta",
        "maintenance": false,
        "loglevel": 2,
        "skeletondirectory": "\/mnt\/nc_skeleton",
        "ldapUserCleanupInterval": 5,
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font"
        ],
        "overwrite.cli.url": "http:\/\/192.168.3.3",
        "overwritehost": "cloud.phils-lab.net"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
Chrome fully-patched, mozilla firefox fully patched

**Operating system:**
Windows 10

#### Browser log
<details>
<summary>Browser log</summary>

![image](https://cloud.githubusercontent.com/assets/15452526/26172888/390cb56e-3b4a-11e7-8c1b-ba3593a1ceaa.png)
</details>

**Comment by ChristophWurst** [comment]
> "overwrite.cli.url": "http://192.168.3.3"

Please set that to your actual domain/URL. This should fix your issue.

**Comment by PhilsLab** [comment]
Unfortunately i already tried that, but nothing changed. It's only visible via 192.168.3.3, but not on any other domain, no matter which domain is configured in `overwrite.cli.url`.

**Comment by PhilsLab** [comment]
I found out something very weird by further testing:

Logo + Background were uploaded via 192.168.3.3.
--> not visible on external link

I connected via the external URL and dropped in a picture for only the **logo**
--> the Logo, **and** the background are now visible on 192.168.3.3 and the external URL, but not via the local hostname of my nextcloud instance.

Seems to be a real bug, not a misconfiguration, i guess.

**Comment by PhilsLab** [comment]
After a few reloads, both the logo and the background became invisible at 192.168.3.3...
browser log now shows the pictures are loaded via the external url:

**Comment by PhilsLab** [comment]
I just upgraded to beta4, tested uploading the theming images from different URLs, and the problem still persists.

**Comment by luisnabais** [comment]
I have the same issue. If the images show in external URL, they don't in the internal IP.

**Comment by juliushaertl** [comment]
Should be fixed by #5429 as well.
