### ISSUE TITLE
Undefined offset: 0 at /var/www/html/lib/private/Preview/GeneratorHelper.php#69	

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#4930]
On c.nc.c:

> {"reqId":"kj2YxTeFdK9Ap0TWvcl5","level":3,"time":"2017-05-17T21:52:07+00:00","remoteAddr":"","user":"--","app":"PHP","method":"--","url":"--","message":"Undefined offset: 0 at \/var\/www\/html\/lib\/private\/Preview\/GeneratorHelper.php#69","userAgent":"--","version":"12.0.0.20"}

**Comment by LukasReschke** [comment]
@rullzer Seems to be triggered by your preview generator app? As remote address is empty :)

**Comment by rullzer** [comment]
I smell some corrupt file again... no real way to fix it. And note that it would also be triggered if we would navigate to that directory and request a preview...

**Comment by rullzer** [comment]
Lets close this as I have no idea why or how to trigger it reliably (without uploading broken image files)
