### ISSUE TITLE
[Bug]: Searching for a user to share to no longer works

### ISSUE THREAD

**Issue by damienvidalcabm** [nextcloud/server#49312]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

![Image](https://github.com/user-attachments/assets/e401a979-a87a-4af0-a415-88a43a05bba5)
Hello
When you share a file with a user.
The search to assign a user to the share no longer works.
Thank you
Kind regards

### Steps to reproduce

1. Share a document (ex : ODT file)
2. Search a user
3. wait ... wait ... wait ...

### Expected behavior

Docker host : Debian 11
Docker container host : Debian 12 + PHP 8.3 + Apache2.4
Docker container DB : Ubuntu LTS + MariaDB 10.11LTS

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

**Comment by joshtrichards** [comment]
Unable to reproduce this behavior. You didn't provide much to go on since you left most of the bug report template empty. Please check your browser inspector (particularly the *Network* and *Console* tabs) while reproducing the problem in your environment. Also please check your Nextcloud Server log.

**Comment by damienvidalcabm** [comment]
![Image](https://github.com/user-attachments/assets/e7972aec-8a42-4111-b686-6c44c0f4c49d)

**Comment by damienvidalcabm** [comment]
Into the file "nextcloud/log"


{"reqId":"uXON9FkWnoAZbCF5X8Gt","level":0,"time":"2024-11-15T15:37:40+00:00","remoteAddr":"10.6.1.213","user":"root","app":"no app in context","method":"GET","url":"/index.php/apps/files/api/v1/stats","message":"Calling OCP\\DB\\QueryBuilder\\IQueryBuilder::orX without parameters is deprecated and will throw soon.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36 Edg/130.0.0.0","version":"30.0.2.2","exception":{"Exception":"Exception","Message":"No parameters in call to OC\\DB\\QueryBuilder\\ExpressionBuilder\\ExpressionBuilder::orX","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/apps/circles/lib/Db/CoreQueryBuilder.php","line":1355,"function":"orX","class":"OC\\DB\\QueryBuilder\\ExpressionBuilder\\ExpressionBuilder","type":"->"},{"file":"/var/www/html/nextcloud/apps/circles/lib/Db/CoreQueryBuilder.php","line":1122,"function":"limitInitiatorVisibility","class":"OCA\\Circles\\Db\\CoreQueryBuilder","type":"->"},{"file":"/var/www/html/nextcloud/apps/circles/lib/Db/CircleRequest.php","line":166,"function":"limitToInitiator","class":"OCA\\Circles\\Db\\CoreQueryBuilder","type":"->"},{"file":"/var/www/html/nextcloud/apps/circles/lib/Service/CircleService.php","line":525,"function":"getCircles","class":"OCA\\Circles\\Db\\CircleRequest","type":"->"},{"file":"/var/www/html/nextcloud/apps/circles/lib/CirclesManager.php","line":326,"function":"getCircles","class":"OCA\\Circles\\Service\\CircleService","type":"->"},{"file":"/var/www/html/nextcloud/apps/deck/lib/Service/CirclesService.php","line":98,"function":"getCircles","class":"OCA\\Circles\\CirclesManager","type":"->"},{"file":"/var/www/html/nextcloud/apps/deck/lib/Db/BoardMapper.php","line":114,"function":"getUserCircles","class":"OCA\\Deck\\Service\\CirclesService","type":"->"},{"file":"/var/www/html/nextcloud/apps/deck/lib/Sharing/DeckShareProvider.php","line":701,"function":"findBoardIds","class":"OCA\\Deck\\Db\\BoardMapper","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Share20/Manager.php","line":1216,"function":"getSharedWith","class":"OCA\\Deck\\Sharing\\DeckShareProvider","type":"->"},{"file":"/var/www/html/nextcloud/apps/files_sharing/lib/MountProvider.php","line":49,"function":"getSharedWith","class":"OC\\Share20\\Manager","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/Config/MountProviderCollection.php","line":72,"function":"getMountsForUser","class":"OCA\\Files_Sharing\\MountProvider","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/Config/MountProviderCollection.php","line":129,"function":"getMountsFromProvider","class":"OC\\Files\\Config\\MountProviderCollection","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/SetupManager.php","line":203,"function":"addMountForUser","class":"OC\\Files\\Config\\MountProviderCollection","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/SetupManager.php","line":306,"function":"OC\\Files\\{closure}","class":"OC\\Files\\SetupManager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/lib/private/Files/SetupManager.php","line":202,"function":"setupForUserWith","class":"OC\\Files\\SetupManager","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/SetupManager.php","line":380,"function":"setupForUser","class":"OC\\Files\\SetupManager","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/Mount/Manager.php","line":75,"function":"setupForPath","class":"OC\\Files\\SetupManager","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/View.php","line":1344,"function":"find","class":"OC\\Files\\Mount\\Manager","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Files/Filesystem.php","line":681,"function":"getFileInfo","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/legacy/OC_Helper.php","line":475,"function":"getFileInfo","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/html/nextcloud/apps/files/lib/Controller/ApiController.php","line":314,"function":"getStorageInfo","class":"OC_Helper","type":"::"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":208,"function":"getStorageStats","class":"OCA\\Files\\Controller\\ApiController","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":114,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":161,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/nextcloud/lib/base.php","line":1001,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/nextcloud/index.php","line":24,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/nextcloud/lib/private/DB/QueryBuilder/ExpressionBuilder/ExpressionBuilder.php","Line":87,"message":"Calling OCP\\DB\\QueryBuilder\\IQueryBuilder::orX without parameters is deprecated and will throw soon.","exception":{},"CustomMessage":"Calling OCP\\DB\\QueryBuilder\\IQueryBuilder::orX without parameters is deprecated and will throw soon."}}

**Comment by joshtrichards** [comment]
Those 500 internal server errors are definitely the problem, but you'll need to find the log entries associated with them. The log entry you shared is unrelated and is only showing because you appear to have debug level logging on. I'd set the loglevel to something reasonable (2 is the default) then reproduce the original problem. The 500 error will be logged somewhere (probably the Nextcloud log).

**Comment by damienvidalcabm** [comment]
Hello,

With the loglevel = 2, I see 

<:"An exception occurred while executing a query: SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'utf8mb4_general_ci' is not valid for CHARACTER SET 'utf8mb3'","userAgent":"Mozilla/5.0

Thanks

**Comment by damienvidalcabm** [comment]
Re ! Josh,
I find a Nextcloud command : sudo -u www-data php occ maintenance:repair --include-expensive
It's the solution.
