### ISSUE TITLE
[Bug]: Changing TaskProcessing selects wrong provider

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/server#49335]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Select the fake provider for testing in the UI, see that the request still contains the OpenAI provider

### Steps to reproduce

https://github.com/user-attachments/assets/71e7376c-8712-408a-9e47-fd29dee0a602

Note: It's also happening the other way around. If I select OpenAI, the fake provider is set.

**Comment by marcelklehr** [comment]
Can you share the video as a gif maybe? I can't watch it :/
