### ISSUE TITLE
beta 4 update failed

### ISSUE THREAD

**Issue by igrekbs** [nextcloud/server#4934]
### Steps to reproduce
1. Manual update with cli from Nextcloud 12 betta 2  to beta 4
2. Access to main page

### Actual behaviour
Nothing happens

### Logs
<details>
<summary>Stack trace</summary>

sudo -u www-data php occ maintenance:repair
An unhandled exception has been thrown:
TypeError: Argument 2 passed to OCA\Theming\Util::__construct() must implement interface OCP\Files\IRootFolder, instance of OC\App\AppManager given, called in /var/www/nextcloud/lib/private/Server.php on line 860 and defined in /var/www/nextcloud/apps/theming/lib/Util.php:49
Stack trace:
0 /var/www/nextcloud/lib/private/Server.php(860): OCA\Theming\Util->__construct(Object(OC\AllConfig), Object(OC\App\AppManager), Object(OC\Files\AppData\AppData))
1 /var/www/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
2 /var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(115): Pimple\Container->offsetGet('ThemingDefaults')
3 /var/www/nextcloud/lib/private/ServerContainer.php(116): OC\AppFramework\Utility\SimpleContainer->query('ThemingDefaults')
4 /var/www/nextcloud/lib/private/Server.php(1641): OC\ServerContainer->query('ThemingDefaults')
5 /var/www/nextcloud/lib/private/Console/Application.php(59): OC\Server->getThemingDefaults()
6 /var/www/nextcloud/console.php(90): OC\Console\Application->__construct(Object(OC\AllConfig), Object(Symfony\Component\EventDispatcher\EventDispatcher), Object(OC\AppFramework\Http\Request), Object(OC\Log))
7 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
8 {main}
</details>

**Comment by juliushaertl** [comment]
Looks like something went wront when you replaced the files. 
I seems that apps/theming/lib/Util.php is still an old version from before beta 4.

How did you put the extracted archive in place?

**Comment by igrekbs** [comment]
Hello!

It's my mistake! It wasn't able to update from b2 to b4 through web updater (it seems some errors here) and I decided to copy old (b2) app folder to new (b4) nextcloud root folder during cli update!

Thank for your reply! Now it's ok!
