### ISSUE TITLE
Migrate from OwnCloud 10

### ISSUE THREAD

**Issue by GnaXi** [nextcloud/server#4935]
I would love to move from ownCloud to Nextcloud, but it doesn't seem possible at the moment.
Will it be made possible at any point, or would I have to start from scratch?

**Comment by nickvergessen** [comment]
Hi @GnaXi we are working on it. The upcoming 12.0.0 release will have a migration option from ownCloud 10.0.0

For ownCloud 9.1 migration is easily possible to Nextcloud 10

We will update https://nextcloud.com/migration/ "Upgrade path" as soon as the release is out.

**Comment by GnaXi** [comment]
Thank you for the quick feedback @nickvergessen ! :)
Do you have an ETA for 12.0.0?

**Comment by nickvergessen** [comment]
As per https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule it's planned for this month ;)

**Comment by GnaXi** [comment]
Woohoo! Thanks :D

**Comment by dpointk** [comment]
Hey, just wanted to +1. I've upgraded our ownCloud server and then we found out about nextcloud... The feature set looks amazing. Can't wait to upgrade.

**Comment by GnaXi** [comment]
Do we know if it would work with the current Nextcloud 12 beta?

**Comment by nickvergessen** [comment]
beta 4 does not work, account data (email, user display name, avatar) are lost :(

But it is fixed in the latest daily build. If you want to try a test migration with it, that would be really awesome:
https://download.nextcloud.com/server/daily/latest-stable12.zip

But be sure to only do this in a copy, or prepare backups so you can roll-back.

**Comment by GnaXi** [comment]
I'll give it a try! Are the migration instructions the same as for ownCloud 9 -> Nextcloud 11 ?

**Comment by nickvergessen** [comment]
Yeah, see https://nextcloud.com/migration/

**Comment by GnaXi** [comment]
Seems like the migration was a success! :D
Will we later be able to upgrade from beta to release?

**Comment by nickvergessen** [comment]
I think you have to do it manually, because you used a daily build, but you should be able to update, yes.

**Comment by GnaXi** [comment]
Something has gone wrong. After about a minute I loose access to the Nextcloud webinterface and I have to restart apache on my server to regain access. Only to regain the same issue after a minute.
There is all of a sudden an apache2 process on the server taking up 100% of the CPU owned by www-data.

**Comment by nickvergessen** [comment]
Yeah maybe because you hit the personal page.
Apply https://github.com/nextcloud/server/pull/4949/files to fix the issue

**Comment by GnaXi** [comment]
I've now applied the fix, but the issue remains the same.

**Comment by GnaXi** [comment]
Nevermind me! For some reason I decided to only apply half of the fix "authToken" instead of "authtoken" :P

**Comment by GnaXi** [comment]
Now been running for 9 hours and everything is running perfect. Consider me a happy camper! :D

**Comment by GnaXi** [comment]
Everything is still working perfectly except from one thing, that I'm not even sure is related, but might be worth looking into, as it doesn't seem like anyone else on Nextcloud 12 is having issues with the Android app.
https://github.com/nextcloud/android/issues/1028

The ownCloud android app was having no issues connecting to the server before i migrated, but the Nextcloud android app can't seem to connect at all.

**Comment by jospoortvliet** [comment]
That last thing was fixed and migration works so let's close this issue. 12.0.1 will be able to migrate ownCloud 10.0.1 and 10.0.2...

**Comment by GnaXi** [comment]
Yes, everything is working exceptionally! :)

**Comment by jospoortvliet** [comment]
@GnaXi Great work helping us test this. You might have heard of a t-shirt-for-upgrade-testing, perhaps we should just say that this is covered with that and give you one. Interested? :shirt: if so mail me, first name at nextcloud.com :smile:

**Comment by GnaXi** [comment]
I had no idea, but I would be honored to wear some nextcloud merch! :D
