### ISSUE TITLE
Add an option to disable Federation related apps when has_internet_connection is set to false

### ISSUE THREAD

**Issue by lemiceo** [nextcloud/server#49360]
**Is your feature request related to a problem? Please describe.**
Hello ! If not used, both `cloud_federation_api `and `federatedfilesharing` could be disabled.

**Describe the solution you'd like**
Allow `php occ app:disable cloud_federation_api` and `php occ app:disable federatedfilesharing`

**Describe alternatives you've considered**

- Adding CSS to hide the related features to user
- Modifying the corresponding php files to remove related calls

**Additional context**
Nextcloud instance is intranet only : `php occ config:system:set has_internet_connection --type=boolean --value=false`

**Comment by kesselb** [comment]
This sounds like a great feature, but currently there are no plans to implement it. Therefore, I will close this ticket for now. This does not mean we don't want this feature, but it is not on our list of things to do soon.
