### ISSUE TITLE
Automatically retry to upload files in case of failure

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#4937]
### Steps to reproduce

1. Upload a file
2. Disconnect router
3. Reconnect router

### Expected behaviour

The upload should fail and then try again X more times. It should succeed once the router has been reconnected

### Actual behaviour

The upload fails and that's it.
I disconnected the router as an example. The idea is to survive a failure in case the network isn't great.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. 
If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
