### ISSUE TITLE
No initial entry highlighted in User management settings

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#4938]
By default, the group »Everyone« is opened. However it is not highlighted in the settings.

The default entry (in this case »Everyone«) should be highlighted by setting the `.active` class to the element with the ID `#everyonegroup`.

cc @nextcloud/javascript

**Comment by jancborchardt** [comment]
@LukasReschke any reference to what it was fixed by? Without comment I'm assuming this was closed by accident?

**Comment by MorrisJobke** [comment]
<img width="438" alt="bildschirmfoto_2017-06-12_um_17_36_44" src="https://user-images.githubusercontent.com/245432/27058269-c3b0395c-4f95-11e7-8b6f-f319f74bb31a.png">

**Comment by LukasReschke** [comment]
![2017-06-13_00-38-29](https://user-images.githubusercontent.com/878997/27058330-cf503812-4fd0-11e7-910e-f4a0172a1a19.png)

**Comment by jancborchardt** [comment]
Ugh … neither of the stupid two Android apps I use for Github exposes that info. Sorry and thanks! :)

**Comment by LukasReschke** [comment]
😄

**Comment by MorrisJobke** [comment]
😆

**Comment by MorrisJobke** [comment]
> Ugh … neither of the stupid two Android apps I use for Github exposes that info. Sorry and thanks! :)

Use the github mobile page - it works nice.

**Comment by blizzz** [comment]
>  Use the github mobile page - it works nice.

For basic reading, otherwise it is also a pain ;)

**Comment by jancborchardt** [comment]
Yeah … it's veeery slow, and doesn't have any of the things like labeling, milestones, not even @mention-suggestions etc unless you switch to desktop view. ;)
