### ISSUE TITLE
[Bug]: Nonstandard server port ignored, redirecting to :443  same as #44071

### ISSUE THREAD

**Issue by wangmice** [nextcloud/server#49393]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

use nginx 1.27，enable tlsv1.3，listen quic on port 40000,
use curl or chrome to browe the site, it return 302 to the 443 port.
this has reported on [https://github.com/nextcloud/server/issues/44071](url) #44071 but the issue is locked

### Steps to reproduce

1.use nginx 1.27，enable tlsv1.3，listen quic on port 40000,
2.use curl or chrome to browe the site, it return 302 to the 443 port.
this has reported on [https://github.com/nextcloud/server/issues/44071](url) #44071 

I change the nginx config seems  to fix, please check it .
add this line in the php block:
`fastcgi_param HTTP_HOST $host:$server_port;`

### Expected behavior

redirect to the right server port not 443

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Nginx

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

**Comment by solracsf** [comment]
Well, the issue is locked because it has been demonstrated that this is indeed a configuration (or external software to Nextcloud, like webserver/proxy/protocol) issue.

Please head to https://help.nextcloud.com to help you further debug your setup. Thanks 👍
