### ISSUE TITLE
Remove/Deactivation of the E-Mail-Server functionality

### ISSUE THREAD

**Issue by Ch3ck3rM0n** [nextcloud/server#49394]
Hi Team,

I have been used Nextcloud since v17 (so a long time) on web storage of my provider. To save money I decided now to move the Nextcloud form the external provider server to my internal home server, which is also available from the internet. The transfer worked well and my Nextcloud is still available over web. At home I do not have a private mail server.

So now I have the problem, that I still get from Nextcloud the warning/error message in logs and overview what the "E-Mail-Server" configured under "Generals" is not setup. It tells me I need to set it up to get mails for example for passwort reset.

The clue is, I don't need that feature to my nextcloud. I have fully controll of the whole server and in anykind of trouble like passwort reset and so on, I do fix it on Linux console. This "E-Mail-Server"-feature makes sense to people who are using more user and manage Nextcloud out of the GUI, but not for me and the everyday warning is annoying.

So please give me/us an option to remove or just disable it, so we don't get any warnings in the logs/overview anymore.

Thanks in advance.

Manuel

**Comment by kesselb** [comment]
I guess you can use the null mailtransport as soon as Nextcloud 31 is released: https://github.com/nextcloud/server/pull/48977

**Comment by Ch3ck3rM0n** [comment]
Thanks, so I wait for the release in February :)

**Comment by joshtrichards** [comment]
Haven't tested this, but should also just be able to "fake" the test result by setting the `emailTestSuccessful` app (`core`) value to `1` according to the test:

https://github.com/nextcloud/server/blob/3822db51742eb12c67b525cab80ec0699e011684/apps/settings/lib/SetupChecks/EmailTestSuccessful.php#L41


... via `occ config:app:set`
