### ISSUE TITLE
encryption:enable-master-key can not be called headless automated

### ISSUE THREAD

**Issue by markus7811** [nextcloud/server#4940]
Running an automated setup vial cloudformation i want to enable encryption at installation time. Calling occ encryption:enable-master-key wants input - option -v or -n doesn't work. It would be nice, if this would be possible.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
