### ISSUE TITLE
[Bug]: Synchronization issues when editing markdown files and switching tabs between edits

### ISSUE THREAD

**Issue by neonmate** [nextcloud/server#49439]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

I'm using a managed Nextcloud Hub 8 (29.0.5) instance. Since a few months I noticed synchronization issues when editing markdown files and switching between tabs.

### Steps to reproduce

1. Open a markdown file
2. Write some content (it gets synchronized)
3. Switch to another tab
4. Switch back to the markdown file and write some content (is not possible to synchronize anymore)

Symptoms when entering a state, where synchronization is not possible anymore:

- Still POST requests are send e.g. `POST https://cloud.paradieschen-augsburg.de/apps/text/session/267823/sync` and return the status 200
- The check icon does not get a blue indicator of unsaved changes
- Pressing the check icon does not trigger any requests (dead state)

### Expected behavior

1. Open a markdown file
2. Write some content (it gets synchronized)
3. Switch to another tab
4. Switch back to the markdown file and write some content (it gets synchronized)

### Nextcloud Server version

29

### Additional info

I don't have access to the server itself as I'm using a managed Nextcloud Hub 8. Still I can try to provide any client site information you need as long as the don't include any confidential information of the instance itself. The resulting data loss is a big thing for me and my colleagues. We use different operating system and different browser. The behavior is in all browsers the same. The issue does not occur for the mobile clients (iOS and Android).

Workaround:

Copy the whole pad when you notice the broken state. Reload the page. Paste the content.

**Comment by XueSheng-GIT** [comment]
Should be fixed with latest versions already. I suggest to update the nc instance.

**Comment by neonmate** [comment]
@XueSheng-GIT Can you tell me the commit or the release tag, that fixes this issue? Thanks!

**Comment by XueSheng-GIT** [comment]
If I remember correctly, it was fixed in the text repo. Please search over there.

**Comment by neonmate** [comment]
Nice, thanks for hint! Then it is fixed in 29.0.6, https://github.com/nextcloud/text/issues/6280.
