### ISSUE TITLE
Tag UI missing 

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#4944]
### Steps to reproduce
1. Try to tag a file that has no tags yet in the UI

### Expected behaviour
Click on the Tags label and add them

### Actual behaviour
Tag label is missing

The problem is, that the `Tag` label is somehow removed from the UI. You can see it show up for a split second:
https://github.com/nextcloud/server/blob/a06398f804fa95ec8b6d9249a3c3c571fe4cb4b8/apps/systemtags/js/systemtagsinfoview.js#L151

@ChristophWurst you have some minutes to check this before the final?

**Comment by nickvergessen** [comment]
Git bisect:
```
17a31a51c62e36500f59b3c2d385ab79258f6bb6 is the first bad commit
commit 17a31a51c62e36500f59b3c2d385ab79258f6bb6
Author: Vinc... Pe... <pv...1@ow...om>
Date:   Wed Aug 17 12:25:58 2016 +0200

    Fix share indicator handling
    
    Properly update the fileInfoModel with the updated share types, which
    also updates the file list row indicator properly
```

🙈

**Comment by nickvergessen** [comment]
I split the code into:
```
				fileInfoModel.set('shareTypes', shareModel.getShareTypes());
				fileInfoModel.set('icon', $tr.attr('data-icon'));
```
second line was there before and works, as soon as the first line is enabled the tag ui is killed...

**Comment by ChristophWurst** [comment]
> @ChristophWurst you have some minutes to check this before the final?

I will try to find some time tomorrow morning. Can't promise it though.

**Comment by ChristophWurst** [comment]
@nickvergessen could you please tell me which *tab label* you're referring to. I cannot really see the issue. Is it the icon in the sidebar?

**Comment by nickvergessen** [comment]
Yes, compare the sidebar on master against `git checkout master@{2017-04-01}`

**Comment by nickvergessen** [comment]
Here is current master when the file has no tag:
> ![files_-_nextcloud_-_2017-05-19_08 58 52](https://cloud.githubusercontent.com/assets/213943/26236655/c4205476-3c71-11e7-80a1-f47db7f64889.png)

When you uncomment line https://github.com/nextcloud/server/blob/17a31a51c62e36500f59b3c2d385ab79258f6bb6/apps/files_sharing/js/share.js#L196-L196 with two slashes, you get:
> ![files_-_nextcloud_-_2017-05-19_08 57 27](https://cloud.githubusercontent.com/assets/213943/26236643/b573c23c-3c71-11e7-97f9-c6cd327aeecb.png)


If the item already had an icon, all is good, because we dont show the label but the box directly:
> ![files_-_nextcloud_-_2017-05-19_08 58 01](https://cloud.githubusercontent.com/assets/213943/26236614/89b75b72-3c71-11e7-8fa6-333d77d515e9.png)

**Comment by nickvergessen** [comment]
Okay it happens when the share view is opened, so in case you have activity or comments on, you need to switch to the sharing tab.
