### ISSUE TITLE
"update all" applications button unresponsive

### ISSUE THREAD

**Issue by leolivier** [nextcloud/server#49453]
Context: Using NC30.0.3 using latest community docker image from docker hub

When I have several applications to be updated, I get a list of these applications with an update button for each one and above that, there is an "update all" button (I use a French version so the English labels might be a bit different) 
![Image](https://github.com/user-attachments/assets/198f7006-e799-4dae-9fb0-869bff47d830)

The "update to vxxx" button of each application is working fine but the "update all" button is not responding when clicking it.

**Comment by joshtrichards** [comment]
Duplicate of #49144

> Using NC30.0.3

I assume you mean 30.0.2. ;-)

**Comment by leolivier** [comment]
Sorry @joshtrichards , you're right, 30.0.2 yes, I was a bit in advance :)
I didn't see the duplicate as I searched only in open issues...

**Comment by joshtrichards** [comment]
>  I didn't see the duplicate as I searched only in open issues...

Thanks for the reminder. We actually have a pending PR (to switch the search link in the issue template to open+closed) that I needed to follow-up on still. ;)
