### ISSUE TITLE
Internal Server Error when uploading files on external store with web client

### ISSUE THREAD

**Issue by reneglauser** [nextcloud/server#4945]
Nextcloud version (eg, 11.0.3):
Operating system and version (eg, Ubuntu 16.04):
Apache version (eg, Apache 2.4.18): 
PHP version (eg, 5.6): 7.0.15
Is this the first time you've seen this error?: yes

The issue you are facing:
Every time I want to upload a file to Nextocloud with the web-interface I get an "internal server error". The files is uploaded correctly but it seems that there might be a bug.....

The output of your Nextcloud log in Admin > Logging:
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE "oc_filecache" SET "mtime"=? WHERE ("mtime" <> ? OR "mtime" IS NULL) AND "fileid" = ? ' with params ["1493729604.474", "1493729604.474", 88767]: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "1493729604.474"

/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 128: Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
/var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - line 836: Doctrine\DBAL\DBALException driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'UPDATE "oc_file...', Array)
/var/www/nextcloud/lib/private/DB/Connection.php - line 194: Doctrine\DBAL\Connection->executeQuery('UPDATE "oc_file...', Array, Array, NULL)
/var/www/nextcloud/lib/private/Files/Cache/Cache.php - line 312: OC\DB\Connection->executeQuery('UPDATE "oc_file...', Array)
/var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheWrapper.php - line 138: OC\Files\Cache\Cache->update(88767, Array)
/var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheWrapper.php - line 138: OC\Files\Cache\Wrapper\CacheWrapper->update(88767, Array)
/var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheWrapper.php - line 111: OC\Files\Cache\Wrapper\CacheWrapper->update(88767, Array)
/var/www/nextcloud/lib/private/Files/View.php - line 1533: OC\Files\Cache\Wrapper\CacheWrapper->put('IT-STP-Nst-006 ...', Array)
/var/www/nextcloud/lib/private/Files/View.php - line 567: OC\Files\View->putFileInfo('/rgl/files/Info...', Array)
/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php - line 209: OC\Files\View->touch('/Informatik/IT-...', '1493729604.474')
/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 137: OCA\DAV\Connector\Sabre\File->put(Resource id #32)
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1072: OCA\DAV\Connector\Sabre\Directory->createFile('test.xml', Resource id #32)

**Comment by MorrisJobke** [comment]
Will be fixed in the upcoming 11.0.4 - see #4919

**Comment by catbou** [comment]
I also have this "internal server error" issue in 11.0.5 when drag & drop a file in the browser. 
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE "oc_filecache"
I've checked the View.php file which contains this line
$this->putFileInfo($path, array('mtime' => floor($mtime)))
