### ISSUE TITLE
[Bug]: No parameters in Call to ExpressionBuilder

### ISSUE THREAD

**Issue by solick** [nextcloud/server#49455]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Hi since upgrade to NEX Hub 9 I get frequent messages like this:

`[no app in context] Fehlersuche: Calling OCP\DB\QueryBuilder\IQueryBuilder::orX without parameters is deprecated and will throw soon.
	GET /ocs/v2.php/apps/notifications/api/v2/notifications
	

`

Because the is no app related (no app in context) I have no clue where this is coming from.

Kind regards

### Steps to reproduce

1. Upgrade from Hob 8 to Hub 9 (could also be an issue under Hub 8)
2.
3.

### Expected behavior

No frequent error messages

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Upgraded to a MAJOR version (ex. 28 to 29)

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [x] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

**Comment by joshtrichards** [comment]
That is only logged if you have debug level logging (`0`) on:

https://github.com/nextcloud/server/blob/1005efdfd37295dcce5162094227d671e8aacafc/lib/private/DB/QueryBuilder/ExpressionBuilder/ExpressionBuilder.php#L66

The default is `2`: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#log-level
