### ISSUE TITLE
"Remove" button in "Disabled apps" page doesn't work

### ISSUE THREAD

**Issue by ozgurkazancci** [nextcloud/server#49452]
Hello,

I'd like to report that;

"Remove" buttons in /settings/apps/disabled never work under 30.0.2.

It just does nothing.

Chrome's browser console tab reports this error whenever "Remove" is clicked:

https://i.ibb.co/RgSnLSN/console-tab.png

Regards.

**Comment by joshtrichards** [comment]
Duplicate of #49193
