### ISSUE TITLE
opcache prevents maintenance site from appearing

### ISSUE THREAD

**Issue by mind22** [nextcloud/server#4946]
### Steps to reproduce
1. activate opcache like mentioned in admin properties
2. activate maintenance mode with occ command

### Expected behaviour
Maintenance sitemap should appear preventing user from login/work

### Actual behaviour
You can use nextcloud as usual.

### Server configuration

**Operating system**: Ubuntu 16.04.2 LTS

**Web server:** nginx

**Database:** mariadb 10.0.29

**PHP version:** 7.0.15

**Nextcloud version:** NC 12 beta 4

**Updated from an older Nextcloud/ownCloud or fresh install:** from 11.0.3 to 12b3 to 12b4

**Where did you install Nextcloud from:** official

**Comment by rullzer** [comment]
Can you post your opcache config? Because your opcache should notice relatively quickly (like within a few seconds) that it needs to reload the config.php

**Comment by mind22** [comment]
Ah ok sry. I had two more settings activated because of the reference in the Nextcloud 12 Documentation. There is a link in the docu to the side [https://www.scalingphpbook.com/blog/2014/02/14/best-zend-opcache-settings.html](url)

And because of this i had additionally activated:

opcache.fast_shutdown=1
opcache.validate_timestamps=0

Now the sitemap appears as it should be.
