### ISSUE TITLE
[Bug]: Release 29.0.9 missing on https://download.nextcloud.com/

### ISSUE THREAD

**Issue by HB9HIL** [nextcloud/server#49498]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Release 29.0.9 is missing on the download server

![Image](https://github.com/user-attachments/assets/e0d566d9-b4d7-4bd6-a0e1-bc4b16a5ee53)

![Image](https://github.com/user-attachments/assets/5d659429-f601-4bbd-8362-0b31d3eedabd)

![Image](https://github.com/user-attachments/assets/6b5ef110-1f3d-4e79-bae7-e6f2c7b5345d)

![Image](https://github.com/user-attachments/assets/f01dfdb5-ce23-4186-9ba1-9a6638dd56af)

### Steps to reproduce

Try to update Nextcloud from 29.0.8 to 29.0.9 

### Expected behavior

Release Files should be available

### Additional info

None of my system configurations are relevant for this bug.

**Comment by HB9HIL** [comment]
And how can I update my Instance then when the Updater tells me first to 29.0.9 before moving on to 30...

**Comment by pachulo** [comment]
One of the maintainers of the nextcloud snap here. [We had some discussion on what to do with this release](https://github.com/nextcloud-snap/nextcloud-snap/issues/2955), because of that regression.

> 29.0.9 was removed due to an issue with files_pdfviewer.

Wouldn't it make more sense to do a hot-fix release? I mean, [this update was announced with the following header](https://nextcloud.com/blog/november-maintenance-updates-for-nextcloud-hub-7-8-and-9/):
> If you are using Nextcloud Hub 7, 8 or 9, we strongly recommend you to update to version 28.0.12, 29.0.9 or 30.0.2 respectively. Maintenance updates include important bug fixes, stability and security upgrades. It is a quick and safe process, as always!

**Comment by HB9HIL** [comment]
> > And how can I update my Instance then when the Updater tells me first to 29.0.9 before moving on to 30...
> 
> The updater_server [was updated yesterday](https://github.com/nextcloud-releases/updater_server/pull/1139/files), and should offer 30 for instances running 29.0.8. If not, that might be a caching issue or a bug.

Well then I tried exactly between removing the release and updating the updater_server. Now it shows 30.0.2

**Comment by blizzz** [comment]
We added an info the forums. Better late then never, right 🙊 

https://help.nextcloud.com/t/29-0-9-pulled-from-download-servers/210877
