### ISSUE TITLE
[Bug]: SFTP external storage backend does not respect port setting

### ISSUE THREAD

**Issue by chaosgrid** [nextcloud/server#49499]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

See https://github.com/nextcloud/server/blob/01b2ae4e4e47a58e3036184bbd52d8fdd76ee412/apps/files_external/lib/Lib/Storage/SFTP.php#L67

The port is exclusively extracted from the hostname, the port setting is completely ignored. You have to encode the port in the hostname by appending :port 

### Steps to reproduce

1. Set up port in external storage SFTP backend config (not via the hostname string)
2. It still connects at standard port (22).

### Expected behavior

It should respect the port setting of course.

### Nextcloud Server version

30

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

**Comment by joshtrichards** [comment]
Thanks. We're aware: #49296.

**Comment by chaosgrid** [comment]
Ah sorry, for some reason did not find the other issue!
