### ISSUE TITLE
Group restriction are not saved

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#4952]
### Steps to reproduce
1. upgrade to NC12b4
2. open apps
3. restrict "password policy" or "text editor" app to group admin (check mark in checkbox, select admin group)
4. reload apps page

### Expected behaviour
password policy app should be set to group admin only

### Actual behaviour
checkmark is removed

### Server configuration
**Operating system**: debian 8.8, up-to-date
**Web server:** apache 2.4
**Database:** mySQL 5.5
**PHP version:** 5.6
**Nextcloud version:** 12.0 beta 4, updated from NC 11.0.3
**Where did you install Nextcloud from:** NC updater app (beta channel)
**Signing status:** "No errors have been found." (after removing(!) ownbackup, rescanning, and reinstalling it)
**List of activated apps:** Irrelevant here
**Nextcloud configuration:** Should be irrelevant here
**Are you using external storage:** no
**Are you using encryption:** no
**Are you using an external user-backend:** no

### Client configuration
Irrelevant here.

#### Web server error log
nothing during above actions

#### Nextcloud log (data/nextcloud.log)
nothing during above actions

#### Browser log
nothing during above actions

**Comment by MariusBluem** [comment]
Generally not an issue with server issue. files_texteditor and password_policy are more or less standalone apps, you'll find over here:

files_texteditor: https://github.com/nextcloud/files_texteditor
password_policy: https://github.com/nextcloud/password_policy

They are allowing group restrictions per `info.xml`. If this is not working, we may want to consider about disallowing this restriction, or implement it (if possible) 🤔 @MorrisJobke

**Comment by nursoda** [comment]
I am sorry for posting in the wrong repo. I did search but overlooked that I would have had to search for "password_policy", not "password policy". Maybe it's a good idea to make sure that the app names a user sees within NC appear in the GitHub descriptions on [https://github.com/nextcloud](https://github.com/nextcloud).

As for the reported bug itself, does your last comment mean that it (partly) also is a server issue? If not, please close and I'll reopen in those repos.

**Comment by MariusBluem** [comment]
Repo names are = with the folder name of the app (nextcloud/apps) = appid 

> As for the reported bug itself, does your last comment mean that it (partly) also is a server issue? If not, please close and I'll reopen in those repos.

I'll leave this open, because I think it makes no sense to open this (small) bug two times in those repositories. I'd say we'll track this over here for now.

**Comment by MorrisJobke** [comment]
@MariusBluem I guess I need to disagree with you. This issue actually looks like the group restriction itself is not working. Because the setting doesn't seem to be saved.

cc @nickvergessen @rullzer @icewind1991 for the group restriction

**Comment by MorrisJobke** [comment]
Okay I tested it and there is no request send out that would save the group restriction. Let me check on that.

**Comment by MorrisJobke** [comment]
@nursoda Congratulations! You won a Nextcloud T-Shirt for spotting this! 😉 Write an email with the address you want to have it shipped including type of cut (male, female) and size (S, M, L, XL, ...) to jos  <at> nextcloud . com

Thanks for helping us making Nextcloud better :)

**Comment by MorrisJobke** [comment]
cc @jospoortvliet

**Comment by nursoda** [comment]
Fix works for me as expected / as it should. Thanks, that was quick :-)

**Comment by jospoortvliet** [comment]
@nursoda did you mail me already with your address?? I don't think so, but if I missed it, say so! If you didn't, do :dancer:

**Comment by nursoda** [comment]
I already receiced my shirt, i'ts still in the laundry, though. Will wear it proudly ;-) A big THANKS -- to you and the team.
