### ISSUE TITLE
[Bug]: Error opening DICOM files in a shared fold which remove the permission for download

### ISSUE THREAD

**Issue by snakesgun** [nextcloud/server#49555]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Same issue as https://github.com/nextcloud/server/issues/19572 but for DICOM (.dcm) files viewed in DICOM viewer app.

Operating system: Linux 4.19.107-Unraid x86_64

Web server: nginx

Database: MariaDb 11.3.2

Nextcloud version: 30

Updated from an older Nextcloud/ownCloud or fresh install: fresh install

Where did you install Nextcloud from: docker

### Steps to reproduce

 - Share folder containing DICOM (.dcm) files with users in the platform by using adding user function. Sample files attached for you to test: [DICOM sample.zip](https://github.com/nextcloud/server/files/4519367/DICOM.sample.zip)
 - uncheck allow download and sync
 - In user who receive the share fold, they could not read dicom file due to the platform forbid the download and report 403.

continual loading in dicom viewer

### Expected behavior

DICOM viewer app opens DICOM file in browser

### Nextcloud Server version

30

### Operating system

Debian/Ubuntu

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Fresh Nextcloud Server install

### Are you using the Nextcloud Server Encryption module?

Encryption is Disabled

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

**Comment by joshtrichards** [comment]
Please report this to the maintainers of the DICOM viewer app: https://github.com/ayselafsar/dicomviewer/issues
