### ISSUE TITLE
LDAP : No display members of groupe in user management panel / oc_ldap_group_members table / reproducible case

### ISSUE THREAD

**Issue by adrienfr44** [nextcloud/server#4958]
Hello,

I am very embarrassed, I look from my side for a month but I definitely do not understand the "problem" (but i reproduce it easly). @blizzz  (and others), an expert explanation would be really great :)

## Context
A new job -> a new important ldap tree (in production), no nextcloud installed.
Similar tests (and results) on fresh install nc11x or 12x with correct configuration backend ldap (I do not transmit all the configuration at the moment to lighten the message) 

Structure on my openldap production : 

  |-- ou=Groupes,dc=xxxxxxx,dc=xx 
  |  _(one posixGroup for testing - (details of ldif structure below) )_  
  |  _view of list in ldapclient :_ 
  | --->  cn=test_groupe

  |-- ou=Utilisateurs,dc=xxxxxxx,dc=xx 
  |   _( **+2500** inetOrgPerson  - (details of ldif structure below) )_     
  |   _view top of list in ldapclient :_ 
  | ---> uid=admin_ldap
  | ---> uid=test_ldap
  | ---> uid=1001201611
  | ---> uid=1001201611
  | ---> uid=100201606
  | ---> uid=1002201611
  | ---> uid=1003201611
  | ---> uid=1004201611
  | ---> uid=1005201611
  | ---> uid=1006201611
  | ---> uid=1007201611
  | ---> uid=1008201611
  | ---> uid=1009201611
  | ---> uid=1010201611
  | ---> uid=1011201611
  | ---> uid=101201606
  | ---> uid=1012201611
 | ---> uid=1013201611
 | ---> uid=1014201611
 |  ....

Group (test_groupe) structuration :
```
dn: cn=test_groupe,ou=Groupes,dc=xxxxxxx,dc=xx
cn: test_groupe
description: test
gidnumber: 10
memberuid: admin_ldap
memberuid: 1001201611
objectclass: posixGroup
```

User (admin_ldap, test_ldap) structuration : 
```
dn: uid=admin_ldap,ou=Utilisateurs,dc=xxxxxxx,dc=xx
cn: admin_ldap
givenname: 
jpegphoto:: 
mail: admin_ldap@admin_ldap.fr
objectclass: inetOrgPerson
sn: admin_ldap
uid: admin_ldap


dn: uid=test_ldap,ou=Utilisateurs,dc=xxxxxxx,dc=xx
cn: test_ldap
givenname: 
jpegphoto:: 
mail: test_ldap@admin_ldap.fr
objectclass: inetOrgPerson
sn: test_ldap
uid: test_ldap
```

All other users structuration, **uid is a number**:
```
dn: uid=1001201611,ou=Utilisateurs,dc=xxxxxxx,dc=xx
cn: toto TITI
givenname: toto
jpegphoto:: 
mail: toto@titi.fr
objectclass: inetOrgPerson
sn: TITI
uid: 1001201611
```

## Inital result

In user management panel
* In "Everyone" view, it's ok perfect
* In "test_groupe" view, only appears ldap_admin (**1001201611 does not appear**)  

In database : 
* For information, oc_ldap_group_members : 
```
+--------------+---------------+
| owncloudname | owncloudusers |
+--------------+---------------+
| test_groupe| a:1:{i:0;s:14:"admin_ldap";}     |
```

In log
* For information, in log, i have promptly the [“Sizelimit exceeded” message](https://docs.nextcloud.com/server/12/admin_manual/configuration_user/user_auth_ldap.html?highlight=ldap#troubleshooting-tips-and-tricks)

`
Error	PHP	ldap_search(): Partial search results returned: Sizelimit exceeded at /var/www/html/nextcloud12/server/apps/user_ldap/lib/LDAP.php#293
`

## Tests/Results (that make me crazy)
1/ Add test_ldap user as memberuid of test_group
Result : In "test_groupe" view, **appears immediatly** ldap_admin **and test_admin**

2/ Add any of the other users (with numeric uid) as memberuid of test_group
Result : In "test_groupe" view, appears ldap_admin and test_admin **only** (**no other user (with numeric uid) does not appear**)  

3 / Modify user "dn: uid=1001201611,ou=Utilisateurs,dc=xxxxxxx,dc=xx" , rename uid by "doh"
( in the same time, remplace memberuid:1001201611 by memberuid:doh in test_groupe)
```
dn: uid=doh,ou=Utilisateurs,dc=xxxx,dc=xxx
cn: toto TITI
givenname: toto
jpegphoto:: 
mail: toto@titi.fr
objectclass: inetOrgPerson
sn: TITI
uid: doh
```
Result : In "test_groupe" view, **appears immediatly**  ldap_admin and test_admin **and doh** .....

4/ Modify user "dn: uid=doh,ou=Utilisateurs,dc=xxxxxxx,dc=xx" , rename uid by "1"
( in the same time, remplace memberuid:doh by memberuid:1in test_groupe)
```
dn: uid=1,ou=Utilisateurs,dc=xxxxxxx,dc=xx
cn: toto TITI
givenname: toto
jpegphoto:: 
mail: toto@titi.fr
objectclass: inetOrgPerson
sn: TITI
uid: 1
```
Result : In "test_groupe" view, appears ldap_admin and test_admin **only** (**doh disappears immediatly**)  ...

## Conclusion
In hope to receive your lights here  (i don't know if it's a pagination openldap problem or a nextcloud code problem with a numeric uid or other explanation ...)
Thank you
Adrian

**Comment by blizzz** [comment]
@adrienfr44 i have a suspicion… is the DN "uid=1001201611,ou=Utilisateurs,dc=xxxx,dc=xxx" in total  longer than 255 characters? It won't fit in  the DB table 🙊  Cf. https://github.com/nextcloud/server/issues/2213

There would not be an easy fix for this, because we'd need to change the database structure, and store and operate with  hashes. At least, as most obvious way to deal with it.

**Comment by adrienfr44** [comment]
In my real case, DN is always lower 255 characters
Correct size : 
* Ou=Utilisateurs,dc=xxxxxxx,dc=xx  ( 32 characters)
* uid=iiiiaaaamm (max 10 characters)

**Comment by adrienfr44** [comment]
note : thanks for quicly radvice
note 2 : i specially examined this issue https://github.com/nextcloud/server/issues/2990 and i test too with your getUserGroupMemberships.php script

**Comment by adrienfr44** [comment]
It's finally not a minor bug. On the nextcloud11 and 12 this causes an impossibility for the admin group (manage on ldap for me) to correctly administrate nextcloud
For Nextcloud 12 this has impact with the new user management.

In short, as long as the oc_ldap_group_members table is not enriched normally, it's not easy. :(

Ps: Impossible for me to rename 3000 ldap accounts to prevent uid values ​​from being numbers

	
owncloudname
owncloudusers

test
a:0:{}

admin
a:1:{i:0;s:14:"administrateur";}

**Comment by blizzz** [comment]
It's been a while, but since there were several fixes with UIDs consisting only of numbers in server. Perhaps that fixed it?
