### ISSUE TITLE
Clean up after unchecking directory (Selective Sync, OSX)

### ISSUE THREAD

**Issue by madorian** [nextcloud/server#4959]
Is this the proper bug tracker to report bugs on the OSX client? Is there a separate github for the Mac OSX client?

on Mac OSX, if you uncheck a directory to not sync it, is it not supposed to remove the file/directory pretty much immeditely?

if not, then how can you expedite the process of removing it from the local file system? How long after it has been unchecked is it removed from the file system? Is there a way to perfom this action immediately?

**Comment by LukasReschke** [comment]
Please report client issues at https://github.com/nextcloud/client_theming

**Comment by madorian** [comment]
ok, thanks
