### ISSUE TITLE
Accepting federated share is broken

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#4961]
### Steps to reproduce
1. Share file from instance B with user on instance A
2. On instance A click "accept" in the notification

### Expected behaviour
Share is accepted

### Actual behaviour

Notification disappears and reappears after reload 

Network console:
Request to /ocs/v1.php/apps/files_sharing/api/v1/remote_shares/pending/19 returns HTTP 200 but without content

cc @schiessle @nextcloud/sharing 

### Server configuration
**Operating system**: Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64

**Web server:** Apache/2.4.10 (Debian) (apache2handler)

**Database:** mysql 5.5.55

**PHP version:** 7.0.18-1~dotdeb+8.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, igbinary, mysqlnd, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, json, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 12.0 beta 4 - 12.0.0.21

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** release beta 4

**Signing status:**
<details>
	<summary>Signing status</summary>

```

```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>

```
Enabled:
 - activity: 2.5.2
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.2
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - deck: 0.1.4
 - drawio: 0.8.6
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_downloadactivity: 1.1.1
 - files_external: 1.3.0
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - groupfolders: 1.0.2
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.6.4
 - news: 11.0.0
 - nextcloud_announcements: 1.1
 - notes: 2.2.0
 - notifications: 2.0.0
 - password_policy: 1.2.2
 - previewgenerator: 1.0.6
 - provisioning_api: 1.2.0
 - richdocuments: 1.12.27
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - spreed: 2.0.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0

Disabled:
 - admin_audit
 - apporder
 - bookmarks
 - circles
 - direct_menu
 - encryption
 - gpxpod
 - ojsxc
 - sharerenamer
 - user_external
 - user_ldap
```

</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "oc4e6adde34d",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
    ],
    "datadirectory": "\/var\/owncloud\/data",
    "dbtype": "mysql",
    "version": "12.0.0.21",
    "dbname": "cloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "ldapIgnoreNamingRules": false,
    "forcessl": true,
    "mail_from_address": "no-relpy",
    "mail_smtpmode": "php",
    "mail_domain": "example.com",
    "theme": "",
    "maintenance": false,
    "secret": "***REMOVED SENSITIVE VALUE***",
    "session_lifetime": 604800,
    "session_keepalive": true,
    "memcache.local": "\\OC\\Memcache\\Redis",
    "loglevel": 0,
    "filesystem_check_changes": "0",
    "trashbin_retention_obligation": "auto",
    "filelocking.enabled": "true",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "localhost",
        "port": 6379
    },
    "updatechecker": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\Illustrator",
        "OC\\Preview\\Photoshop",
        "OC\\Preview\\SVG"
    ],
    "apps_paths": [
        {
            "path": "\/var\/www\/nextcloud\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/nextcloud\/apps-extra",
            "url": "\/apps-extra",
            "writable": true
        }
    ],
    "integrity.check.disabled": false,
    "defaultapp": "apporder",
    "debug": false,
    "updater.release.channel": "beta",
    "htaccess.RewriteBase": "\/",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OCA\Files_External\Lib\Storage\FTP
    [2] => \OC\Files\Storage\DAV
    [3] => \OCA\Files_External\Lib\Storage\OwnCloud
    [4] => \OCA\Files_External\Lib\Storage\SFTP
    [5] => \OCA\Files_External\Lib\Storage\AmazonS3
    [6] => \OCA\Files_External\Lib\Storage\Dropbox
    [7] => \OCA\Files_External\Lib\Storage\Google
    [8] => \OCA\Files_External\Lib\Storage\Swift
    [9] => \OCA\Files_External\Lib\Storage\SFTP
    [10] => \OCA\Files_External\Lib\Storage\SMB
    [11] => \OCA\Files_External\Lib\Storage\SMB
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36

**Operating system:**

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
       Nothing there
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
        Nothing there
	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
	Nothing there.
	```
</details>

**Comment by LukasReschke** [comment]
cc @schiessle

**Comment by LukasReschke** [comment]
Potential dupe of https://github.com/nextcloud/server/issues/3455?

**Comment by nickvergessen** [comment]
Just tested and works fine, but the file list doesn't reload anymore when you are browsing it atm. Response is:
```xml
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message>OK</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data/>
</ocs>
```

Also tested without notifications app and also works there.

**Comment by juliushaertl** [comment]
Sorry I was checking the wrong logfile when submitting the issue. There is an entry 

```
{
  "reqId": "oP3WFYzUU6CDYeftSXOz",
  "level": 3,
  "time": "2017-05-20T08:41:12+00:00",
  "remoteAddr": "89.13.130.235",
  "user": "jus",
  "app": "PHP",
  "method": "POST",
  "url": "\\/ocs\\/v1.php\\/apps\\/files_sharing\\/api\\/v1\\/remote_shares\\/pending\\/21",
  "message": "TypeError: Argument 3 passed to OC_Helper::buildNotExistingFileNameForView() must be an instance of OC\\Files\\View, null given, called in \\/var\\/www\\/nextcloud\\/lib\\/private\\/legacy\\/helper.php on line 323 at \\/var\\/www\\/nextcloud\\/lib\\/private\\/legacy\\/helper.php#333",
  "userAgent": "Mozilla\\/5.0 (X11; Linux x86_64) AppleWebKit\\/537.36 (KHTML, like Gecko) Chrome\\/58.0.3029.81 Safari\\/537.36",
  "version": "12.0.0.21"
}
```
Instance A is on RC2
Instance B is on master

Sharing from instance A to instance B works as expected but not the other way round.

**Comment by juliushaertl** [comment]
Ok, its a duplicate of #3455 -> closing here
