### ISSUE TITLE
Re/sharing group for group sharing management

### ISSUE THREAD

**Issue by narcisgarcia** [nextcloud/server#49619]
When a user has a resource because of group membership (p.e. someone shared a folder to your group and not to you account), the re-sharing should be a group matter and not only by user who performed re-sharing.

This way, any member of target group can see re-sharing condition and modify it.

EXAMPLE:

- There is a group called "friends" with members "john" "mary" "alan"
- "john" shares a folder to group "friends", allowing them to reshare.
- "mary" reshares that folder to "oscar"

Either "john" or "alan" should be able to see folder as reshared to "oscar", and they also should be able to un-reshare same as "mary" can. Because it's a group matter and not a single user matter.

**Comment by solracsf** [comment]
What you're searching for is [GroupFolders](https://apps.nextcloud.com/apps/groupfolders) I think.

**Comment by narcisgarcia** [comment]
> What you're searching for is [GroupFolders](https://apps.nextcloud.com/apps/groupfolders) with ACLs enabled I think.

Thank you. I've registered there a question about this:
https://github.com/nextcloud/groupfolders/issues/3456

**Comment by narcisgarcia** [comment]
- Test with Nextcloud server 31: Other authorized users can see a _Shared_ contition, who made the sharing, and seem to be able to unshare. Fine.
- Test with Debian (trixie/testing): Nextcloud desktop client 3.16.4: Other authorized users can see, on synchronized content, a subtile _Shared_ icon variant (really subtile), but when opening context-menu "Sharing options" there is not appearing any information, same as it doesn't were shared by anyone.

**Comment by provokateurin** [comment]
@narcisgarcia please open a new issue in the desktop repository.

I will lock this issue as any further discussion should always happen in new issues.
