### ISSUE TITLE
Nextcloud version 30.0.3 disabled many apps as "incompatible app"

### ISSUE THREAD

**Issue by ozgurkazancci** [nextcloud/server#49671]
Hi,

Updated my nextcloud instance from 30.0.2 to the recently-released 30.0.3 version, got the apps below disabled with the message;

Disabled incompatible app: calendar
Disabled incompatible app: contacts
Disabled incompatible app: files_downloadactivity
Disabled incompatible app: files_frommail
Disabled incompatible app: jitsi
Disabled incompatible app: mail
Disabled incompatible app: notes
Disabled incompatible app: passwords
Disabled incompatible app: quota_warning
Disabled incompatible app: richdocuments
Disabled incompatible app: side_menu
Disabled incompatible app: spreed
Disabled incompatible app: theming_customcss

How may I re-enable them again, if possible? Any idea would be much appreciated.

Regards.

**Comment by ozgurkazancci** [comment]
Yes, here how it goes;

```
sudo -u www php occ app:enable calendar
Could not download app calendar
```

nextcloud.log file reports;

```
"app":"appstoreFetcher","method":"GET","url":"/settings/apps/list","message":
"Response from appstore is invalid, apps could not be retrieved. Try again later.",

","app":"appstoreFetcher","method":"","url":"--","message":
"Response from appstore is invalid, apps could not be retrieved. Try again later.",

```

**Comment by tmknight** [comment]
What about `install`: https://docs.nextcloud.com/server/19/admin_manual/configuration_server/occ_command.html#apps-commands:~:text=Download%20and%20install%20an%20app

Also, are/were the incompatible apps indicated on the administration settings/overview page under update?

**Comment by blizzz** [comment]
@ozgurkazancci  apparently apps.nextcloud.com is not reachable from your server? Or was your server rate-limited?

**Comment by ozgurkazancci** [comment]
My server was probably unreachable towards apps.nextcloud.com
