### ISSUE TITLE
[Bug]: Cannot remove applications from UI

### ISSUE THREAD

**Issue by ibaraki-douji** [nextcloud/server#49686]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When clicking the button to remove an application, nothing happen on the UI and i have an error inside the devtools
![Image](https://github.com/user-attachments/assets/e484700e-3da2-410a-b3b3-b081dfc7a650)

### Steps to reproduce

1. Upgrade to 30.0.3.X (idk if it happen on older versions)
2. Go to your applications
3. Remove an application and check your devtools

### Expected behavior

The application should be deleted (or the password confirmation popup should show)

### Nextcloud Server version

30

### Is this bug present after an update or on a fresh install?

After an update, but didn't check if it was working before the update

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

**Comment by poupounetjoyeux** [comment]
Hello,

Same here in v30.0.3
Expected to be fixed by https://github.com/nextcloud/server/pull/49209 but the issue still remaining

**Comment by solracsf** [comment]
> Expected to be fixed by [#49209](https://github.com/nextcloud/server/pull/49209) but the issue still remaining

This PR is v30.0.**4** only.

**Comment by solracsf** [comment]
Fixed by https://github.com/nextcloud/server/pull/49216

**Comment by poupounetjoyeux** [comment]
Okay, my bad, saw it previously in the v30.0.3 milestones

So i'll just wait for the v30.0.4

Thanks you 😁

**Comment by ibaraki-douji** [comment]
Can confirm, it works with 30.0.4, thx guys
