### ISSUE TITLE
v28.0.13 and v30.0.3 not available anymore (v29.0.10 is OK)

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#49696]
v28.0.13 has been published and available to upgrade some hours, but it's not available anymore at https://download.nextcloud.com/server/releases/ _(and of course links are broken at https://nextcloud.com/changelog/#latest28 too)_

It's still available here on Github releases.

Is this on purpose?
Cc @blizzz

**Comment by XueSheng-GIT** [comment]
Seems those releases have been withdrawn:
https://help.nextcloud.com/t/28-0-13-and-30-0-3-withdrawn/211672
