### ISSUE TITLE
Hooks are triggered for chunking paths

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#4971]
1. use 12.0.0 rc1
2. Set up a sync client
3. Upload a file that needs chunking

### Expected
One final activity

### Actual
tones of logs:
> Undefined offset: 3 at /var/www/html/apps/activity/lib/FilesHooks.php#620

\+ one final activity.

I fixed the activity app to not react on path `null` anymore with https://github.com/nextcloud/activity/pull/156
But I think the hooks should not be triggered at all.

cc @icewind1991

**Comment by iMocW** [comment]
Leave a note:
#5433 #5185

**Comment by danger89** [comment]
Related?
https://github.com/nextcloud/activity/issues/163#issuecomment-330256351

**Comment by szaimen** [comment]
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!
