### ISSUE TITLE
[Bug]: Uninstalling apps does not work after update to nc 30.0.2

### ISSUE THREAD

**Issue by JL710** [nextcloud/server#49721]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

When I try to uninstall/remove an app I get a js error and nothing happens.

### Steps to reproduce

1. Click on remove for one of your apps

### Expected behavior

I would expect it to uninstall the app.

### Nextcloud Server version

30

### Additional info

This is the js error that pops up in my browser console.
```
TypeError: this.$store.dispatch(...) is undefined
    remove AppManagement.js:219
    click AppDetailsTab.vue:1
    VueJS 86
    init vue-router.esm.js:3005
    init vue-router.esm.js:3004
    updateRoute vue-router.esm.js:2414
    transitionTo vue-router.esm.js:2263
    confirmTransition vue-router.esm.js:2402
    a vue-router.esm.js:2084
    a vue-router.esm.js:2091
    Ee vue-router.esm.js:2095
    confirmTransition vue-router.esm.js:2396
    a vue-router.esm.js:2084
    a vue-router.esm.js:2088
    _ vue-router.esm.js:2384
    g vue-router.esm.js:2162
    _ vue-router.esm.js:2362
    a vue-router.esm.js:2087
    a vue-router.esm.js:2091
    a vue-router.esm.js:2091
    a vue-router.esm.js:2091
    a vue-router.esm.js:2091
    a vue-router.esm.js:2091
    Ee vue-router.esm.js:2095
    confirmTransition vue-router.esm.js:2392
    transitionTo vue-router.esm.js:2260
[vue.runtime.esm.js:3065:16](webpack:///nextcloud/node_modules/vue/dist/vue.runtime.esm.js)
    VueJS 89
    init vue-router.esm.js:3005
    init vue-router.esm.js:3004
    updateRoute vue-router.esm.js:2414
    transitionTo vue-router.esm.js:2263
    confirmTransition vue-router.esm.js:2402
    a vue-router.esm.js:2084
    a vue-router.esm.js:2091
    Ee vue-router.esm.js:2095
    confirmTransition vue-router.esm.js:2396
    a vue-router.esm.js:2084
    a vue-router.esm.js:2088
    _ vue-router.esm.js:2384
    g vue-router.esm.js:2162
    _ vue-router.esm.js:2362
    a vue-router.esm.js:2087
    a vue-router.esm.js:2091
    a vue-router.esm.js:2091
    a vue-router.esm.js:2091
    a vue-router.esm.js:2091
    a vue-router.esm.js:2091
    Ee vue-router.esm.js:2095
    confirmTransition vue-router.esm.js:2392
    transitionTo vue-router.esm.js:2260
```

**Comment by solracsf** [comment]
Duplicat of https://github.com/nextcloud/server/issues/49686 and similar to https://github.com/nextcloud/server/issues/49689
