### ISSUE TITLE
Download nextcloud-30.0.3.zip not available

### ISSUE THREAD

**Issue by scheltwort-its** [nextcloud/server#49743]
There is currently no download file available at https://download.nextcloud.com/server/releases/nextcloud-30.0.3.zip

**Comment by 4001982248998** [comment]
See #49678

**Comment by solracsf** [comment]
https://help.nextcloud.com/t/28-0-13-and-30-0-3-withdrawn
Wait for 30.0.4, will be made available in the next hours/days.
