### ISSUE TITLE
webdav with 1und1 provider smartdrive

### ISSUE THREAD

**Issue by hstinux** [nextcloud/server#498]
I added as admin the external storage ( webdav ) sd2dav.1und1.de with username and password and secure https .
The green points appears, but if I want to access this storage. There is the error message: the folder can not be accessed.
### Server configuration

**Operating system**:
    debian jessie (hardware banana pi)

**Web server:**
  Apache/2.4.10 (Debian)
**Database:**
  sqlite

**PHP version:**
   php 5.6.23

**Nextcloud version:** (see Nextcloud admin page)
   9.0.53

**Updated from an older Nextcloud/ownCloud or fresh install:**
   fresh install

**Comment by hstinux** [comment]
owncloud.log:

"reqId":"um8bveeRvCwTR6WqDTdh","remoteAddr":"149.236.160.250","app":"PHP","message":"Undefined index: {DAV:}status at \/var\/www\/html\/nextcloud\/3rdparty\/sabre\/dav\/li$
{"reqId":"um8bveeRvCwTR6WqDTdh","remoteAddr":"149.236.160.250","app":"PHP","message":"Undefined offset: 1 at \/var\/www\/html\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Xm$
{"reqId":"um8bveeRvCwTR6WqDTdh","remoteAddr":"149.236.160.250","app":"webdav","message":"Exception: {\"Message\":\"We hit the end of the document prematurely. This likely m$

**Comment by cptshit** [comment]
I'm using Nextcloud 11 with the client (2.2.4) and the client gives me the error message: "server replied: Internal Server Error"

**Comment by testos77** [comment]
The bug exists for some time (owncloud 8.2 -> 9.0). Here're the reports:
https://github.com/owncloud/core/issues/24066
I can confirm the buggy webdav behaviour with 1und1 on my own nextcloud 11.0.1 installation.

**Comment by jensdoecke** [comment]
Same here. I wrote an e-mail to the 1&1 Support with my litmus-log.

**Comment by MorrisJobke** [comment]
Not much we can do here. 1und1 needs to fix the webdav first to follow the specs. I will close this for now.
