### ISSUE TITLE
Yumisign breaks Nextcloud Upgrade to 29.0.10

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/server#49814]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

https://github.com/YumiSign-Organization/yumisign_nextcloud/issues/1

### Steps to reproduce

Nextcloud Upgrade from 29.0.9 to 29.0.10

### Expected behavior

Apps should not (be able to) BREAK Nextcloud Upgrades

### Nextcloud Server version

29

### Operating system

RHEL/CentOS

### PHP engine version

PHP 8.3

### Web server

Apache (supported)

### Database engine version

MariaDB

### Is this bug present after an update or on a fresh install?

Updated from a MINOR version (ex. 28.0.1 to 28.0.2)

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

**Comment by solracsf** [comment]
> Apps should not (be able to) BREAK Nextcloud Upgrades

They don't if you disable them first. Apps execute code, so this can't be avoided.

To be handled upstream at https://github.com/YumiSign-Organization/yumisign_nextcloud/issues/1

**Comment by Githopp192** [comment]
Thanks @solracsf - so disabling ALL Apps before any Nextcloud Upgrade - is this the best practice Nextcloud would suggest/propose  way to go ?

**Comment by solracsf** [comment]
No, the way to go is:

- Test on a non-production environnent
- Ensure compatibilities and bug-free
- Upgrade on production

**Comment by Githopp192** [comment]
> No, the way to go is:
> 
> * Test on a non-production environment
> * Ensure compatibilities and bug-free
> * Upgrade on production

thx - yes, that's the way i normally do

Best
Mike
