### ISSUE TITLE
[Bug]: Broke copying a page from one collective to another when encryption is enabled

### ISSUE THREAD

**Issue by mejo-** [nextcloud/server#49883]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

PR #49695 broke copying a page from one collective to another when encryption is enabled.

Copying a page inside one collective still works as expected. Collectives folders are separate mountpoints, so it's most likely because the copy happens between two mountpoints.

Reverting e7b882dd22474c4c1b22912e629694cb9a80b69b (the commit from PR #49695) fixes the issue.

Cc @come-nc and @icewind1991 as you're the author of #49695.

### Steps to reproduce

1. Enable encryption
2. Create two collectives
3. Copy a page from one collective to another using the Collective UI
4. The request succeeds and the copied page exists in the filesystem, but doesn't appear in files or collectives

Probably the file gets copied on the filesystem but not in the filecache? 🤔 

### Expected behavior

Copying from one collective to another should work.

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

**Comment by come-nc** [comment]
According to my testing this is specific to pages in the root of their collective.

Seems to be fixed by:
```diff
diff --git a/lib/private/Files/Cache/Updater.php b/lib/private/Files/Cache/Updater.php
index 42812dbc882..03681036aa2 100644
--- a/lib/private/Files/Cache/Updater.php
+++ b/lib/private/Files/Cache/Updater.php
@@ -186,6 +186,9 @@ class Updater implements IUpdater {
        public function copyFromStorage(IStorage $sourceStorage, string $source, string $target): void {
                $this->copyOrRenameFromStorage($sourceStorage, $source, $target, function (ICache $sourceCache, ICacheEntry $sourceInfo) use ($target) {
                        $parent = dirname($target);
+                       if ($parent === '.') {
+                               $parent = '';
+                       }
                        $parentInCache = $this->cache->inCache($parent);
                        if (!$parentInCache) {
                                $parentData = $this->scanner->scan($parent, Scanner::SCAN_SHALLOW, -1, false);
```

@icewind1991 Not sure if that is the best fix?

**Comment by mejo-** [comment]
> Seems to be fixed by:

Confirmed, fixes the issue with Collectives 🙏
