### ISSUE TITLE
Nextcloud 12 RC2 - Internal Server Error on Activity page

### ISSUE THREAD

**Issue by Bloodsoul** [nextcloud/server#4990]
### Steps to reproduce
1. Update to RC2 (I did via Web Updater from beta2)
2. Open Acitivty page

### Actual behaviour
It will lead to an internal server error page instead.

### Server configuration

**Operating system**:
FreeBSD 11

**Web server:**
Apache 2.4.25

**Database:**
MariaDB 10.1.23

**PHP version:**
PHP 7.1.5

**Nextcloud version:** (see Nextcloud admin page)
12.0 RC2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 12.0 Beta2

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.2
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - deck: 0.1.4
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - groupfolders: 1.0.2
  - impersonate: 1.0.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - news: 11.0.1
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - rainloop: 4.28.1
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
</details>

### Client configuration
**Browser:**
Firefox 53.0.3

**Operating system:**
Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>
Nothing to see here.
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
ArgumentCountError: Too few arguments to function OC\ServerContainer::getAppContainer(), 1 passed in /usr/local/www/nextcloud/lib/private/ServerContainer.php on line 124 and exactly 2 expected

    /usr/local/www/nextcloud/lib/private/ServerContainer.php - line 124: OC\ServerContainer->getAppContainer('settings')
    /usr/local/www/nextcloud/lib/private/Activity/Manager.php - line 288: OC\ServerContainer->query('OC\\Settings\\Act...')
    /usr/local/www/nextcloud/lib/private/Activity/Manager.php - line 308: OC\Activity\Manager->getFilters()
    /usr/local/www/nextcloud/apps/activity/lib/Data.php - line 348: OC\Activity\Manager->getFilterById('all')
    /usr/local/www/nextcloud/apps/activity/lib/Controller/Activities.php - line 77: OCA\Activity\Data->validateFilter('all')
    [internal function] OCA\Activity\Controller\Activities->showList('all')
    /usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
    /usr/local/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Activity\Controller\Activities), 'showList')
    /usr/local/www/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Activity\Controller\Activities), 'showList')
    /usr/local/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('ActivitiesContr...', 'showList', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /usr/local/www/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /usr/local/www/nextcloud/lib/base.php - line 1000: OC\Route\Router->match('/apps/activity/')
    /usr/local/www/nextcloud/index.php - line 40: OC handleRequest()
    {main}
</details>

#### Browser log
<details>
<summary>Browser log</summary>
Nothing to see here.
</details>

**Comment by mind22** [comment]
#4991

**Comment by himbeere** [comment]
Activity Page works for me on RC2.

**Comment by Bloodsoul** [comment]
Seems to be fixed for updates launched later today. I changed the file according to the change in this commit:
https://github.com/nextcloud/server/commit/a411adee6cfce713aee2a6f35b0930022018d194
