### ISSUE TITLE
German translation missing comma and dot

### ISSUE THREAD

**Issue by hul51u** [nextcloud/server#49911]
https://github.com/nextcloud/server/blob/master/apps/encryption/l10n/de.json line 40

"Die Aktivierung dieser Option verschlüsselt alle Dateien die auf dem Hauptspeicher gespeichert sind, ansonsten werden nur Dateien auf dem externen Speicher verschlüsselt"

should be

"Die Aktivierung dieser Option verschlüsselt alle Dateien, die auf dem Hauptspeicher gespeichert sind, ansonsten werden nur Dateien auf dem externen Speicher verschlüsselt."

**Comment by solracsf** [comment]
Please submit a fix at https://explore.transifex.com/nextcloud/nextcloud/
Thanks 👍
