### ISSUE TITLE
hot to set memory limitation?

### ISSUE THREAD

**Issue by georgy62** [nextcloud/server#49912]
Hallo, 
After installing Nextcloud using a routine provided by the hosting provider, I initially had a storage quota of 50 GB. Since then, the quota has been increased, but the folder view still shows a limit of 50 GB in the bottom left corner. Once this limit is reached, I receive corresponding warnings from Nextcloud, even though more storage is now available. No storage restrictions are configured in the user settings. In a second installation, which was set up with a larger storage quota from the beginning, Nextcloud correctly displays only the used storage space without showing a fixed limit. 
Ultimately the question is: How do I set the storage limit from 50 GB to 250 GB?
Please note the following screenshots:
Installation with memory limit 50 GB:
![Image](https://github.com/user-attachments/assets/a4e78e17-4f8a-4a5d-af18-3052fd9359fc)
Installation mit Speicherbegrenzung 250 GB
![Image](https://github.com/user-attachments/assets/36cfe5e1-4f58-479b-a6e4-aa50b832dc45)

Thank you for your advice

**Comment by solracsf** [comment]
Please reach https://help.nextcloud.com thanks 👍
