### ISSUE TITLE
[Bug]: Folder description (RichWorkspace) not shown up right after created for non-English language

### ISSUE THREAD

**Issue by luka-nextcloud** [nextcloud/server#49930]
### ⚠️ This issue respects the following points: ⚠️

- [x] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [x] This issue is **not** already reported on [Github](https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Abug) OR [Nextcloud Community Forum](https://help.nextcloud.com/) _(I've searched it)_.
- [x] Nextcloud Server **is** up to date. See [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) for supported versions.
- [x] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### Bug description

Folder description (RichWorkspace) is not shown up right after it's created for non-English language.

### Steps to reproduce

1. Go to personal setting and change language to other language
2. Go to Files
3. Click `New` menu and select option correspond to `Add folder description`

### Expected behavior

Markdown file is created and RichWorkspace component is shown up.

### Nextcloud Server version

master

### Operating system

None

### PHP engine version

None

### Web server

None

### Database engine version

None

### Is this bug present after an update or on a fresh install?

None

### Are you using the Nextcloud Server Encryption module?

None

### What user-backends are you using?

- [ ] Default user-backend _(database)_
- [ ] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other

### Configuration report

```json

```

### List of activated Apps

```shell

```

### Nextcloud Signing status

```shell

```

### Nextcloud Logs

```json

```

### Additional info

Reproducible on 28, 29, 30, master

**Comment by kesselb** [comment]
Isn't that an issue with the text app? ;)

**Comment by luka-nextcloud** [comment]
Yes, will reopen it on text app.
