### ISSUE TITLE
Add Zip/Unzip Functionality for NC 30+

### ISSUE THREAD

**Issue by sol8712** [nextcloud/server#49975]
The solution in the past for not adding zip/unzip to core features was that there's another app that can handle this function #1573.

The app that solved the past issue has not been updated in a year and is now no longer a solution for current Nextcloud versions.

For me personally this issue, along with the various desktop app issues, leads to a situation where ive had zero options for moving large numbers of files to Nextcloud for almost 2 months now with no solution even in sight.
I could work around multiple other Nextcloud issues if i could zip/unzip on the server.

**Comment by solracsf** [comment]
See https://github.com/nextcloud/server/issues/48999
That issue was closed very recently for the very same reason.

**Comment by sol8712** [comment]
Would it be possible to reopen #1573?
As the solution that closed it is no longer a working solution?

**Comment by joshtrichards** [comment]
>  As the solution that closed it is no longer a working solution?

nextcloud/files_zip#32 is an open enhancement Issue for adding extraction.
