### ISSUE TITLE
File view: Double click and right click

### ISSUE THREAD

**Issue by maprambo** [nextcloud/server#5]
Afaik since ownCloud 8.2 there is a side panel with extra information. Since then, friends of mine had problems opening files and folder in the web interface. In most native file browsers you have to double click to open a file or folder - why not doing this in Nextcloud, too? 
Another thing is that all the options for sharing, renaming, downloading and so on should also be accessible via right click.
Both these small changes would improve the navigation and make Nextcloud feel more native.

**Comment by mar1u5** [comment]
I think that could cause browser or os specific problems. Especially on mobile devices. I don't know whether we should introduce right- or double-click actions and menus 😕

cc @nextcloud/designers

**Comment by maprambo** [comment]
I've thought of that. These users can still use the "three-dot-menu", can't they?

**Comment by BernhardPosselt** [comment]
Sure you can maintain a mouse and a touch version where in the mouse version everything is delegated to a menu opened by a right click while the touch version has separate buttons.

Turns out maintaining two different interaction models is just very, very cumbersome. It's much easier to find the common ground and make it work well for both platforms.

**Comment by maprambo** [comment]
Wouldn't it be possible to save all menu entries in one database and then specify where every entry should appear?

**Comment by BernhardPosselt** [comment]
No need to save it in the database at all ;)

Building, testing and maintaining the UI while keeping both designs consistent is the real challenge

**Comment by maprambo** [comment]
I just thought of the three-dot-menu to be displayed at the position of the mouse (same css class etc., but with all entries). I'm sorry, I think I'm too dumb to understand the problem here.

**Comment by jancborchardt** [comment]
As @mar1u5 and @BernhardPosselt already mentioned, there are severe maintenance problems with it.

Apart from that, double-click is used _nowhere_ in browsers and usually is used for marking text, so it will likely lead to issues. Also, neither double-click nor right-click is easily discoverable, so we should not use it.

**Comment by jancborchardt** [comment]
Aah ok so I mean the right-cick thing we might be able to do, displaying the 3-dot-menu at the position of the cursor. @BernhardPosselt @MorrisJobke @Henni do you think this is doable?

**Comment by BernhardPosselt** [comment]
Won't this still break the context menu as in prevent you from copy text?

**Comment by jancborchardt** [comment]
But in the list there’s nothing to copy. If you really want to copy the filename, you can rename and then copy. Marking by dragging is not possible anyway because of drag&drop kicking in.

**Comment by Bullnados** [comment]
Something new here? I think the right click menu replace the standard browser right click menu, I'm right?
Little bit like the Dropbox Web-Interface

**Comment by jasonbayton** [comment]
Adding some activity to this as I'd like to see right-click menus implemented 👍

**Comment by jancborchardt** [comment]
This sounds like a good Javascript starter issue.

- Step 1: on right-click of a row, toggle the actions menu
- Step 2: show the actions menu at the place of the cursor

@jasonbayton @Bullnados @maprambo please let your programmer friends know of this issue if you want to push development. :) We are an open source project and everyone can contribute.

**Comment by jancborchardt** [comment]
After much deliberation I think it’s best to not even make right-click any part of Nextcloud. For a few simple reasons:
- If it works in one place, people expect it to work everywhere.
- We have to check a ton of menus to make them show on right-click. 3-dot menus in all different apps etc.
- If it doesn’t work somewhere, people will be confused or frustrated.

It’s pretty much impossible to make sure all apps follow suit on this. For the little gain this gives us it’s not worth the risk at all.
