### ISSUE TITLE
File name error tooltip not updated

### ISSUE THREAD

**Issue by phil-davis** [nextcloud/server#5001]
### Steps to reproduce
1. login to the web UI
2. create 2 files
3. start renaming one file
4. delete the name completely (Error shown: 'File name cannot be empty.')
5. type the name of the other file

### Expected behaviour
Error should be updated to: 'xxxxx already exists'

### Actual behaviour
Error shown: 'File name cannot be empty.'
Same problem the other way around, if you first make a conflicting name & then empty it, the conflicting error message will stay

### Server configuration
NextCloud 11.0.2 but actually happens on any version.

**Comment by MorrisJobke** [comment]
Fixed in #5000

**Comment by phil-davis** [comment]
Backport to stable12 in #5026
