### ISSUE TITLE
12 RC3 garbled text in admin sidebar

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/server#5011]
### Steps to reproduce
1. Log into admin
2. Click usage survey 
3. Possibly, click it again once loaded, as it sometimes doesn't show up immediately

Result:

![image](https://cloud.githubusercontent.com/assets/3178412/26287103/17b5a4f0-3e6c-11e7-900b-2df1ba80deb6.png)

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7

**Nextcloud version:** (see Nextcloud admin page) 12 RC3

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgrade from beta1

**Comment by jasonbayton** [comment]
Can replicate in 12.

**Comment by MorrisJobke** [comment]
Which browser and is this still an issue? Right click this and click "Inspect element" (Chrome, Safari, Firefox). What element is there?

**Comment by jasonbayton** [comment]
Chrome, I can no longer replicate it :)
