### ISSUE TITLE
Update from 10.0.1-10.0.5 via webinterface

### ISSUE THREAD

**Issue by Khain667** [nextcloud/server#5018]
### Steps to reproduce
1. Start Webupdater
2. Watch it fail
3.

### Expected behaviour
Update to version 10.0.5

### Actual behaviour
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SET unique_checks=1': SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

Preparing update
Set log level to debug
Turned on maintenance mode
Checking whether the database schema can be updated (this can take a long time depending on the database size)
[1 / 27]: Checking table oc_appconfig
[2 / 27]: Checking table oc_storages
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SET unique_checks=1': SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
### Server configuration

**Operating system**:
Jail in freenas 9.10.2

**Web server:**
Build in the jail
**Database:**
Build in the jail
**PHP version:**
Build in the jail
**Nextcloud version:** (see Nextcloud admin page)
10.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**
10.0.1
**Where did you install Nextcloud from:**
Freenas plugin repository
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SET unique_checks=1': SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

Preparing update
Set log level to debug
Turned on maintenance mode
Checking whether the database schema can be updated (this can take a long time depending on the database size)
[1 / 27]: Checking table oc_appconfig
[2 / 27]: Checking table oc_storages
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SET unique_checks=1': SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

**Are you using encryption:** no

**Are you using an external user-backend, no

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

**Comment by Khain667** [comment]
I tried the cli update, to do that I had to do a chmod +x occ. now I get Possible CSRF attack. Connection will be closed. in the webbrowser. 

in cli I get nextcloud_1:/usr/local/www/nextcloud # ./occ upgrade
env: php: No such file or directory

**Comment by Khain667** [comment]
Several hours later I managed to get further without making any changes.

Preparing update
Set log level to debug
Turned on maintenance mode
Checking whether the database schema can be updated (this can take a long time depending on the database size)
[1 / 27]: Checking table oc_appconfig
[2 / 27]: Checking table oc_storages
[3 / 27]: Checking table oc_mounts
[4 / 27]: Checking table oc_mimetypes
[5 / 27]: Checking table oc_filecache
[6 / 27]: Checking table oc_group_user
[7 / 27]: Checking table oc_group_admin
[8 / 27]: Checking table oc_groups
[9 / 27]: Checking table oc_preferences
[10 / 27]: Checking table oc_properties
[11 / 27]: Checking table oc_share
[12 / 27]: Checking table oc_jobs
[13 / 27]: Checking table oc_users
[14 / 27]: Checking table oc_authtoken
[15 / 27]: Checking table oc_bruteforce_attempts
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SET unique_checks=1': SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

**Comment by Khain667** [comment]
A few more tries shows it stops at different intervals, I'm guessing it is related to timeouts. Any advice where I can increase these timeouts?

**Comment by MorrisJobke** [comment]
General error: 2006 MySQL server has gone away 

This indicates, that the mysql server stopped working. Nothing we can do. Please look into the mysql server logs and check for the issue there.
