### ISSUE TITLE
3dots-menu to small for long app-names

### ISSUE THREAD

**Issue by JSoko** [nextcloud/server#5021]
### Steps to reproduce
With long app-names (Telefon-Synchronisation)
the 3dots menue isn't wide enough and shows a scrollbar.

Perhaps the menu should be made responsible?

As a a solution I changed the german translation to Telefon-Sync
https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/$/107222840?q=phone%20Sync
https://www.transifex.com/nextcloud/nextcloud/translate/#de/$/107222840?q=Phone%20sync

![grafik](https://cloud.githubusercontent.com/assets/5583290/26294373/6a1abd50-3ec3-11e7-9393-605977a8ef75.png)

### Expected behaviour
Menu should be responsible

### Actual behaviour
Menu shows a scrollbar at the buttom

### Server configuration
**Operating system**: Linux nc-vm 4.8.0-46-generic #49~16.04.1-Ubuntu SMP Fri Mar 31 14:51:03 UTC 2017 x86_64

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.18

**PHP version:** 7.0.15-0ubuntu0.16.04.4
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, redis, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, ldap, exif, mcrypt, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, shmop, SimpleXML, smbclient, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 12.0.0 - 12.0.0.28

**Updated from an older Nextcloud/ownCloud or fresh install: update from older NC

**Where did you install Nextcloud from:** 
Updater
**Signing status:**
<details>
	<summary>Signing status</summary>

```
[]
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - announcementcenter: 3.1.0
 - bookmarks: 0.10.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - deck: 0.1.4
 - external: 2.0.2
 - federatedfilesharing: 1.2.0
 - files: 1.7.2
 - files_downloadactivity: 1.1.1
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - gallery: 17.0.0
 - impersonate: 1.0.1
 - issuetemplate: 0.2.1
 - keeweb: 0.3.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - news: 11.0.1
 - nextcloud_announcements: 1.1
 - notes: 2.2.0
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - ocsms: 1.12.0
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - richdocuments: 1.12.27
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - spreed: 2.0.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0

Disabled:
 - audioplayer
 - encryption
 - federation
 - files_external
 - firstrunwizard
 - spreedme
 - user_external
 - user_ldap
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "loglevel": 2,
    "maintenance": false,
    "theme": "scloud",
    "integrity.check.disabled": false,
    "default_language": "de_DE",
    "logtimezone": "Europe\/Berlin",
    "log_rotate_size": 500000,
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "activity_expire_days": 33,
    "trusted_domains": {
        "0": "localhost",
        "1": "192.168.1.233",
        "3": "XXXXXXXet"
    },
    "trashbin_retention_obligation": "auto, 10",
    "versions_retention_obligation": "auto, 21",
    "datadirectory": "\/media\/nc1\/data",
    "overwrite.cli.url": "https:\/\/XXXXXt\/",
    "dbtype": "mysql",
    "version": "12.0.0.28",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "ocq6gzv14h2p",
    "appstore.experimental.enabled": "true",
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "\/var\/run\/redis\/redis.sock",
        "port": 0,
        "timeout": 0,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "htaccess.RewriteBase": "\/",
    "mysql.utf8mb4": true,
    "mail_smtpmode": "smtp",
    "mail_smtphost": "smtp.1und1.de",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "no-reply",
    "mail_domain": "oXXXXXe",
    "mail_smtpport": "587",
    "updater.release.channel": "stable",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0

**Operating system:**

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	Insert your webserver log here
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
	Insert your Nextcloud log here
	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
	Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
	```
</details>

**Comment by rullzer** [comment]
@nextcloud/designers

**Comment by jancborchardt** [comment]
Good catch! Yes we should ellipsize the app name here.

> As a a solution I changed the german translation to Telefon-Sync

@JSoko thanks a lot! :)

**Comment by SparkPlug911** [comment]
HI, I would like to take this on, but I cannot reproduce the issue? I have signed up on the site and am yet to find the three dots menu

**Comment by jancborchardt** [comment]
@SparkPlug911 where did you sign up? Best install Nextcloud locally for development. The 3-dots menu shows up when you have more apps installed than fit the width. You can also try making the window more narrow to make the menu appear.

**Comment by SparkPlug911** [comment]
@jancborchardt Upon reading your answer, and on reading the issue again, I have realised that I do not possess the technical skills required to set up Nextcloud locally for development, let alone add apps to it. However I have solved the issue, (I reproduced it [here](https://codepen.io/SparkPlug911/pen/YVogdm) on codepen). You just need to add the line `overflow-wrap: break-word` to the **parent div** and you should be all set. You can add `overflow-x:hidden` also, for fallback browsers. Hope that helps.

**Comment by jancborchardt** [comment]
@SparkPlug911 you could edit the CSS file with the Github online editor and open a pull request which can then be reviewed. :) This is the CSS file in question: https://github.com/nextcloud/server/blob/master/core/css/header.scss
