### ISSUE TITLE
unlink(cloud/themes/example/core/templates/lostpassword/email.php): No such file or directory at /cloud/apps/templateeditor/lib/mailtemplate.php#127 

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/server#503]
### Steps to reproduce
1. Select a mail template in admin-panel
2. select in the left menu "example" and in the right any template
3. now click on "reset" (Zurücksetzen in German)

### Expected behaviour
Tell us what should happen
the button should not displayed, because I've no template to reset (thats the default one)

### Actual behaviour
Tell us what happens instead
error message in log

### Server configuration
**Operating system**:
Ubuntu

**Web server:**
Apache 2.4

**Database:**
MySQL 5.6.

**PHP version:**
7.0.8

**Nextcloud version:** (see Nextcloud admin page)
9.0.53 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
nextcloud.com

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
nothing
```
</details>

**List of activated apps:**
<details>
Default apps with calendar app
</details>

**The content of config/config.php:**
<details>
Default, no changes
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
IE11 and Microsoft Edge

**Operating system:**
Windows 10

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
unlink(/cloud/themes/example/core/templates/lostpassword/email.php): No such file or directory at /cloud/apps/templateeditor/lib/mailtemplate.php#127 
```
</details>

**Comment by MorrisJobke** [comment]
Fix is in https://github.com/nextcloud/templateeditor/pull/10
