### ISSUE TITLE
English (British English) language option not available after update to NC12

### ISSUE THREAD

**Issue by kchan101** [nextcloud/server#5030]
### Steps to reproduce
1. Go to Personal settings and click on Language dropdown
2.
3.

### Expected behaviour
There should be English (British English) option as per NC11

### Actual behaviour
Current value is displayed as en_GB

### Server configuration

**Operating system**: Fedora 25

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.0.18

**Nextcloud version:** (see Nextcloud admin page) NC12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from NC 11

**Where did you install Nextcloud from:** Web updated

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - calendar: 1.5.3
  - circles: 0.9.6
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - impersonate: 1.0.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.2.0
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - passman: 2.1.2
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - socialsharing_email: 1.0.1
  - spreed: 2.0.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```{
    "system": {
        "instanceid": "************",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.co.uk"
        ],
        "datadirectory": "\/export\/data\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/example.co.uk\/nextcloud",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "clouddb",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "defaultapp": "calendar,files",
        "updater.release.channel": "beta",
        "mail_smtpmode": "smtp",
        "mail_from_address": "nextcloudtest",
        "mail_domain": "example.co.uk",
        "mail_smtphost": "xxx.xxx.xxx.xxx",
        "mail_smtpport": "25",
        "mail_smtpauthtype": "LOGIN",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
```
</details>

### Client configuration
**Browser:** Firefox

**Operating system:** Fedora 25

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Nothing relevant
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Nothing relevant
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Nothing relevant
```
</details>

**Comment by kchan101** [comment]
Looks like en_GB.js and en_GB.json in core/l10n are missing from nextcloud-12.0.0.zip

**Comment by pghope** [comment]
Same issue after (graphical/web) upgrade from NC11

**Comment by KingPrawn22** [comment]
Showing as en_GB for myself also, though the calendar is showing Sunday as the first day of the week instead of Monday, which I've been told is default for English (US) so there doesn't seem to be a UK option any more.

**Comment by KenBW2** [comment]
@KingPrawn22 That's what I was seeing: en_GB as the language and Sunday as first day of week.

I changed it to English (US) in the hope that I could trigger it back to English (UK) but as soon as I switched away, en_GB disappeared from the list.

Switching to German does indeed put the calendar back to Monday-as-first-day (as well as 24 hour times).

**Comment by KingPrawn22** [comment]
@KenBW2 Exactly what happened to me. Unfortunately I can't read German, but setting it to Greek (which I can read a little of) seems to fix it also. Will try and stick with that until English (UK) returns.

**Comment by koebi001** [comment]
I did copy core/l10n/en_GB.js and core/l10n/en_GB.json from nextcloud 11 as a workaround a did not see any side effects till now

**Comment by mtbf99** [comment]
For a stupid bug an idiot solution:
1. copy the files en_GB.* from apps/files/l10n to core/l10n
2. Go to personal settings and select the Language English GB

**Comment by KingPrawn22** [comment]
Working with that fix, @mtbf99. Much obliged!

**Comment by CHBMB** [comment]
@mtbf99 Thanks for this.  Very grateful!

**Comment by gorankav** [comment]
Same issue with Slovene language.
Was 'sl' until changed to English, now can't change back

**Comment by gorankav** [comment]
mtbf99's solution works.
Hope this is just a temporary workaround.

**Comment by MorrisJobke** [comment]
Should not be a problem anymore with the upcoming 12.0.3: https://github.com/nextcloud/server/blob/stable12/core/l10n/en_GB.js

The files are now there. Sorry for the inconvenience.
