### ISSUE TITLE
Changelog outdated

### ISSUE THREAD

**Issue by pludi** [nextcloud/server#5032]
CHANGELOG.md still has the state of NC11.0.0 as of December 2016. By now there were 3 minor and one major update. At least list the commit messages for the changes done between releases.

**Comment by pludi** [comment]
See also nextcloud/nextcloud.com#473

**Comment by LukasReschke** [comment]
Dupe of https://github.com/nextcloud/nextcloud.com/issues/473, no need to have multiple issues.

**Comment by MariusBluem** [comment]
Well... we may want to remove the CHANGELOG.md form `nextcloud/server` and link to the `nextcloud/nextcloud.com` changelog (which needs an update too 😅) @LukasReschke @jospoortvliet

**Comment by jospoortvliet** [comment]
Yes and yes. Sorry, I haven't updated the changelog yet 👎 will work on it next week though - help welcome 😸
