### ISSUE TITLE
NC12 Fresh installation won't create database

### ISSUE THREAD

**Issue by victorbw** [nextcloud/server#5034]
### Steps to reproduce
1. Fresh download of NC12 Final
2. Unpack & set up webserver
3. finalization via web-ui 

### Expected behaviour
Nextcloud should create database with new user (oc_administrator, as it was in 11 and before) when mysql root-user and password is given

### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/8447071/26309048/cf48185c-3efb-11e7-9766-41f944626230.png)

### Server configuration

**Operating system**: Ubuntu 16.04x64 Server LTS

**Web server:** Apache 2.4.18

**Database:** MySQL 5.7.18

**PHP version:** 7,0

**Nextcloud version:** 12

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Where did you install Nextcloud from:** Source *.tar

**Comment by enoch85** [comment]
Let's keep it in #5049 Thanks! :)

**Comment by victorbw** [comment]
but i was first, lol. ;)
