### ISSUE TITLE
Theming: Background image

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#5035]
I am currently developing the usage of the background image for android app and I have some questions:
- How can I know if the background image has been changed? The url stays the same.
- Is there a way to get a resized version of it? I want to prevent that some admin uses a 2mb image and this gets loaded into our app as this costs data and reduces the speed of opening the sidebar.

**Comment by enoch85** [comment]
cc @marinofaggiana

**Comment by juliushaertl** [comment]
> How can I know if the background image has been changed? The url stays the same.

The URL should at least have a different cachebuster value e.g. v=1. Can you check that?

> Is there a way to get a resized version of it? I want to prevent that some admin uses a 2mb image and this gets loaded into our app as this costs data and reduces the speed of opening the sidebar.

The background image will be scaled to 1920px width and saved as jpeg with 75% quality on upload. Not sure if that is enough or if we should add some endpoint to request smaller versions. @nextcloud/theming

**Comment by LukasReschke** [comment]
> Is there a way to get a resized version of it? I want to prevent that some admin uses a 2mb image and this gets loaded into our app as this costs data and reduces the speed of opening the sidebar.

Can't you do that in a background job or so? :)

**Comment by marinofaggiana** [comment]
Download the image in background, not in main thread, when done refresh

**Comment by tobiasKaminsky** [comment]
It is not about UI lagging but about preserving bandwidth.
But if it is scaled down, I think is enough.
@juliushaertl indeed there is a "v=9" in the url, so this is enough to see updated background images.
