### ISSUE TITLE
Test that server code can be migrated from

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#5039]
* test that the code works for migrating to - see #5038 
* test that the code works - currently already done
* decrease version number in config.php and run a upgrade to verify that the code can me upgraded *from* to test that the updater is not broken by any change (like it was in beta1)

cc @LukasReschke

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by MorrisJobke** [comment]
Still valid, but mostly tested in the updater code base.
