### ISSUE TITLE
Users can upload, though memory is full (trick)

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/server#504]
### Steps to reproduce
1. set for Tests the quota to 10 MB
2. upload files to the message: "Memory full"
3. delete some files (the files are now in the tras bin)
4. now the user can upload more files
5. restore the files from the trashbin
6. the user can now use more quota!
### Expected behaviour

Tell us what should happen
The user needs a message, that the upload is not possible, because the quota from the storage AND the TRASHBIN is to much
### Actual behaviour

Tell us what happens instead
The user can upload more and more files
### Server configuration

**Operating system**:
Ubuntu

**Web server:**
Apache 2.4

**Database:**
MySQL 5.6.

**PHP version:**
7.0.8

**Nextcloud version:** (see Nextcloud admin page)
9.0.53 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
nextcloud.com

**List of activated apps:**
<details>
Default apps with calendar app

**The content of config/config.php:**
<details>
default

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:**
IE11

**Operating system:**
Windows 10
![uploaderror](https://cloud.githubusercontent.com/assets/1473674/17026996/593eff10-4f62-11e6-9245-00bf13d7225a.PNG)

**Comment by MorrisJobke** [comment]
@schiessle @nickvergessen @icewind1991 There was a reason to remove trashbin stuff from quota? Wasn't there an additional rule that drops stuff from the trashbin if the content is more than x% of the total volume or the quota is reached?

**Comment by MorrisJobke** [comment]
And I also have in mind, that we only do a soft quota to not hardly kill files, but allow a slight overflow of the quota.

**Comment by rullzer** [comment]
Well quota is a tricky thing right. If you want to enforce quota as in actual disk space used then we also need to start counting versions, previews etc.

**Comment by Dennis1993** [comment]
> Well quota is a tricky thing right. If you want to enforce quota as in actual disk space used then we also need to start counting versions, previews etc.

I know what you mean. I've tested it again and I can upload as much as I want. Now I have 30 MB of 10 MB used.

Maybe it is better to monitor the trash with. The versions of files is ok in my opinion because it is always one and the same file. But now users can upload other files as much as they want.
But we can discuss about that :)
Maybe it is a better way monitor the versions too? Or give users a Special percentage to use more space with versions. If I have 10 MB space, so I can use 11 MB (10%) or so.

Thanks for our answer!

**Comment by MorrisJobke** [comment]
> But now users can upload other files as much as they want.
> But we can discuss about that :)

Not really, because the trashbin get's emptied when the quota is reached while uploading (I guess at 95% it is the case.

**Comment by skjnldsv** [comment]
@rullzer, @MorrisJobke  a simple disk space check before upload could be nice?

**Comment by MorrisJobke** [comment]
> @rullzer, @MorrisJobke a simple disk space check before upload could be nice?

Sounds easy, but the actual code and scenarios aren't :/. I tried this multiple times in the past but there was always another case that failed the attempt.
