### ISSUE TITLE
Android App:  Auto upload Video, missing leading slash in subfolders year+month

### ISSUE THREAD

**Issue by Slevin90** [nextcloud/server#5041]
### Steps to reproduce
1. In Android App for Nextlcloud,  under settings, activate direct Upload for Video + usage of Subfolders based on Year/month
2. Same upload folder (incl use for subfolders based on year+month) for Fotos
3.

### Expected behaviour
Tell us what should happen
in folder   /Uploads  you should see subfolders per Year and month
Both Video and Foto are in the same folder if they are uploaded in the same year/month

### Actual behaviour
Tell us what happens instead
Fotos show up like  /Uploads/2017/05/
But Videos go to  /Uploads2017/05/

### Server configuration
**Operating system**:
Android 5.0.1
Nextcloud app v1.4.2
**Web server:** lighttpd/1.4.35
**Database:**  mysql 5.5.53
**PHP version:** PHP Version 7.0.14-2
**Nextcloud version:** 11.0.3   (latest stable)
**Updated from an older Nextcloud/ownCloud or fresh install:**  Upgraded since v10

**Comment by jasonbayton** [comment]
This may be better placed in /nextcloud/android/issues

**Comment by MorrisJobke** [comment]
Please reopen in https://github.com/nextcloud/android/issues

@tobiasKaminsky @AndyScherzinger for maybe a quick triage ;)
