### ISSUE TITLE
Security & setup warnings > Which php.ini to edit?

### ISSUE THREAD

**Issue by lepidas** [nextcloud/server#5044]
Ubuntu 16.04, php7, apache
I got this warning after updating to 12 (from 11.3 - everything went well, I lost the T-shirt).
But I got this waring from NextCloud installation:
Security & setup warnings

```
It's important for the security and performance of your instance that everything is configured correctly. To help you with that we are doing some automatic checks. Please see the Tips & Ticks section and the documentation for more information.

    The PHP Opcache is not properly configured. For better performance we recommend ↗ to use following settings in the php.ini:

    opcache.enable=1
    opcache.enable_cli=1
    opcache.interned_strings_buffer=8
    opcache.max_accelerated_files=10000
    opcache.memory_consumption=128
    opcache.save_comments=1
    opcache.revalidate_freq=1

Please double check the installation guides ↗, and check for any errors or warnings in the log.
```
The question is, which php.ini is this refering to? 
/etc/php/7.0/cli/php/ini?
or 
/etc/php/7.0/apache2/php.ini?

I guess it's /etc/php/7.0/apache2/php.ini? should be edited but maybe could be written to the instructions

**Comment by patschi** [comment]
`/etc/php/7.0/apache2/php.ini` should be fine when you're using apache2 as your webserver.

But it should be possible to dynamically show the path to the correct PHP.ini to edit using [function.php-ini-loaded-file](https://secure.php.net/manual/en/function.php-ini-loaded-file.php).
