### ISSUE TITLE
Optimize upgrade process in container/stateless system situations

### ISSUE THREAD

**Issue by robert-scheck** [nextcloud/server#5045]
### Expected behaviour
Please provide a way to e.g. migrate user installed apps and themes from the previous Nextcloud version to the current one while having in mind that everything except `config`, `apps` and `themes` might be part of a container or read-only environment.

### Actual behaviour
Before Nextcloud 12 it was possible to just extract or to copy a new Nextcloud version over the existing one. While this might be not great, it simply worked. Since Nextcloud 12, there is code signing which complains about "unnecessary" files (files that no longer exist in the new version, but existed in the previous version). Thus this method does not work any longer.

On the other hand, there are directories that can be removed and replaced during upgrades, but other directories contain content that should be kept persistently (especially in container or stateless system situations), these are e.g. `config`, `apps` and `themes`.

However, these before mentioned directories contain both, "standard" files delivered by Nextcloud itself and "dynamic" content (e.g. user installed apps). So wiping `apps` and `themes` during upgrades is not a good idea. But the manual upgrade process does not provide helpers or tools to easily detect and migrate such user installed apps and themes, leading to manual work (that's unfortunately also what the documentation says at this point).

While some could argument to use the webbased or the command line updater, I am failing to see how these would work in especially container situations (or other hardened environments), where either (maybe) everything except `config`, `apps` and `themes` is read-only or simply otherwise separated (e.g. Nextcloud in container image vs. persistent data in separate volume).

Finally, when having the goal to auto-upgrade lots of Nextcloud installations without any manual interaction for both, admins and end users, but having a hardened environment and allowing users to install own apps and themes, there is IMHO currently a gap on system administration side, that should be covered in the future.

Separating "standard" apps and themes from user installed ones into different paths could be an option (or making them somehow else in a scriptable way detectable). Or providing a tool to clean up "unnecessary" files. Or an updater (or an updater option) only covering the "standard" apps and themes.

**Comment by nickvergessen** [comment]
You can specify a second apps directly which is outside of your container to handle user installed apps (that's what I do on my instance).

However I don't use a theme, so I don't know there.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest and no respond since around 2 years. Please reopen if you still want to implement this.
