### ISSUE TITLE
Spinning wheel on installation process

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/server#5046]
### Steps to reproduce
1. download the NextCloud-12.0.0.zip from NextCloud.com
2. unzip and start installation

### Expected behaviour
No spinng Wheel at the bottom. The loading bar should be shown after the click on the button

### Actual behaviour
A spinning wheel is shown

### Server configuration

**Operating system**:
Ubuntu 17.04

**Web server:**
Apache 2.4

**Database:**
MySQl 5.7

**PHP version:**
PHP 7.1

**Nextcloud version:** (see Nextcloud admin page)
12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Where did you install Nextcloud from:**
NextCloud.com

### Client configuration
**Browser:**
Firefox 53.0.3

**Operating system:**
Windows 10

![image](https://cloud.githubusercontent.com/assets/1473674/26322375/1d5c2234-3f2b-11e7-8971-2a99e85298ff.png)

**Comment by juliushaertl** [comment]
This is already fixed in stable12/13 and on master
