### ISSUE TITLE
Can't password protect shares because password email is sent from account email address

### ISSUE THREAD

**Issue by linucksrox** [nextcloud/server#5047]
### Steps to reproduce
1. Share any document by typing the email address in the sharing dialog box
2. Check the password protect box, setting a password then pressing Tab
3. Receive an error message: "Expected response code 250 but got code "553", with message "553 Relaying disallowed as [username] (profile email address)"

### Expected behaviour

1. **The link should be protected with the password that was set.**
1. The email should be sent from the system account, like any other notification email.
1. If something fails, at least record it in the logs for future reference.

### Actual behaviour
This error appears, **the link is not protected**, and _nothing is recorded in the logs_.

### Server configuration

**Operating system:** Ubuntu 16.04

**Nextcloud version:** 12.0

**Comment by jospoortvliet** [comment]
@schiessle is this a known issue?

**Comment by schiessle** [comment]
@linucksrox thanks for your bug report, maybe you can test the fix and report back if it works for you: https://github.com/nextcloud/server/pull/5303

**Comment by linucksrox** [comment]
@schiessle Thanks, I applied the changes and everything seems to work correctly now!
