### ISSUE TITLE
Add "Include Reshares" checkbox to "Shared to others" page

### ISSUE THREAD

**Issue by PhrozenByte** [nextcloud/server#5051]
The `OCA\Files_Sharing\Controller\ShareAPIController::getShares()` function (the endpoint of the `shares` API call) of NextCloud's core app `files_sharing` already supports returning reshares ([L577-L583](https://github.com/nextcloud/server/blob/v12.0.0/apps/files_sharing/lib/Controller/ShareAPIController.php#L577-L583)), but there's currently no way in the webapp to use this (hidden) functionality.

I therefore suggest adding a simple checkbox to the "Shared to others" page to make this functionality accessible (simply try adding the `reshares=true` parameter to the request, e.g. in [L169-L173 of `js/sharedfilelist.js`](https://github.com/nextcloud/server/blob/v12.0.0/apps/files_sharing/js/sharedfilelist.js#L169-L173) - it will work just fine!). 

**Reasoning:** Especially in corporate environments, one must be able to comprehend who has access to his files. By enabling reshares, one gets notified when someone reshares a file or directory, but the reshare won't show up in the "Shared to others" page at the moment (however, the reshare will indeed show up in the "Shares" details of the particular file or directory, but you obviously must know what file/directory has been reshared to find this info). Adding a simple checkbox to the "Shared to others" page allows one to easily retrieve a *actually complete* list of all shares.

**Comment by MorrisJobke** [comment]
Isn't this now shown already? @rullzer

**Comment by skjnldsv** [comment]
Yes, we already show reshared files iirc

**Comment by PhrozenByte** [comment]
@skjnldsv No, Nextcloud doesn't show reshared files. Create a "Test" folder with a "Sub-Test" folder inside using user A, share "Test" with user B and let user B reshare "Test/Sub-Test" with user C. The latter won't show up in the shares list of user A.

Can you reopen this issue?

**Comment by skjnldsv** [comment]
Ah, I misunderstood, you want a new section on the left?

**Comment by PhrozenByte** [comment]
Either a new section or just a small checkbox or something.

**Comment by skjnldsv** [comment]
Not sure if we really want that, but I'll leave that opened for now :)

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
