### ISSUE TITLE
Debug info page for faster, easier and higher quality issue reports

### ISSUE THREAD

**Issue by Bugsbane** [nextcloud/server#5054]
The issue template to file a new issue here, can take 20-30 minutes just to fill out, which is seriously offputting when considering sharing a problem with the project.

Now, I understand that having all of the information is useful to devs to not get caught under a flood of poorly triaged, missing-info bug reports.

Might I suggest we have a page which lists as much of the debug information needed in one place, as technically possible (also sanitized). Joomla ( http://joomla.org ) already does this and it works really well there, lowering the barrier for users to submit high quality issue reports with all the information needed by devs without further triage.

Heck, we could even have it preformatted in Markdown so it could just be copied and pasted to here (or just have that in a scrollbox).

**Comment by ChristophWurst** [comment]
> Heck, we could even have it preformatted in Markdown so it could just be copied and pasted to here (or just have that in a scrollbox).

I assume https://apps.nextcloud.com/apps/issuetemplate is what you're looking for :-)

But I agree, filling out the issue template manually is a tedious and error-prone (people mess up the markdown syntax) process.

**Comment by jasonbayton** [comment]
Agreed, anything to make this process better is welcomed. We could also potentially use it on the forums, too.

**Comment by Bugsbane** [comment]
> I assume https://apps.nextcloud.com/apps/issuetemplate is what you're looking for :-)

Exactly, but imagine that automatically filled out with the answers, so all that was needed was to copy and paste. :)

**Comment by Bugsbane** [comment]
> I assume https://apps.nextcloud.com/apps/issuetemplate is what you're looking for :-)

Uh, yeah, that does look like what I'm after! I'll look into this as soon as I can (I'm currectly hamstrung by a bug which won't let me install apps...)

**Comment by MorrisJobke** [comment]
https://github.com/nextcloud/issuetemplate
