### ISSUE TITLE
NC 12:  Cant use my own themes under folder /Themes

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/server#5055]
### Steps to reproduce
cd %nextcloud12%/themes

copy my theme inside
and configuring the config.php to use the theme

### Expected behaviour
the theme do no more apply

### Actual behaviour
the collored setup with a possible to setting up a picture

### Server configuration

**Operating system**:
Openmandriva 3.0

**Web server:**
http://blackysgate.net/phpinfo.php

**Database:**
10.1.22-MariaDB 

**PHP version:**
PHP Version 7.0.17

**Nextcloud version:** (see Nextcloud admin page)
12

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
nextcloud.com
**Signing status:**

</details>

the other don't need.

best regards
Blacky

**Comment by JSoko** [comment]
See
https://github.com/nextcloud/server/issues/5036

**Comment by juliushaertl** [comment]
@JSoko Yep, closing in favour of #5036

**Comment by blackcrack** [comment]
ehh, yupp :) +1
but good to know, to be i am not the only :))))))))))
