### ISSUE TITLE
Nextcloud 12 is way more prone to Sever Cache Missconfiguration than NC 11

### ISSUE THREAD

**Issue by Maulwurf16** [nextcloud/server#5058]
Issue, created due to this forum thread:

https://help.nextcloud.com/t/after-update-nc12-white-webpage/12905/7

I had my sever apcu cache missconfigurated. First, the modul php-apc wasn't installed (my fault) and the config.php had this line:

`'memcache.local' => '\\OC\\Memcache\\APC',`

However, NC 11.0.3.2 did not bother and worked just well.
NC12.0.0.29 showed a blank white page after upgrade, letting me dive into the apache error logs to find out what was wrong.

Edit: included link to forum thread

**Comment by jasonbayton** [comment]
This could be a good thing, after all I'd like to know if I've mis-configured the server, however a blank page is not helpful, agreed.

**Comment by szaimen** [comment]
I think there were some improvements concerning this in the meantime.
