### ISSUE TITLE
Undefined index: federationId

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#5059]
Just to quickly dump this in. On my 12.0.0.29 I get this from ``VerifyUserData.php`` background job. No traceback atm.

``Undefined index: federationId at /path/to/nextcloud/settings/BackgroundJobs/VerifyUserData.php#234``

@schiessle 

UPDATE: possible is connected to my attempt to verify me with my website. Didn't work, apparently, need to look into why. However, copying the snippet and file name is quite unfriendly.

**Comment by linucksrox** [comment]
I'm still seeing this error logged after having disabled the federation app, and that seems strange to me. I don't use federation, and besides clients connecting to sync (no files are changing), these logs keep rolling in. This is after upgrading to 12.0.0.29

**Comment by patschi** [comment]
Adding some sanity checks in the mentioned file `VerifyUserData.php` on `line 234` should do it:
Changing from:
```php
if ($body['federationId'] === $cloudId) {
```

to
```php
if (is_array($body) && isset($body['federationId'] && $body['federationId'] === $cloudId) {
```

**Comment by blizzz** [comment]
@patschi mind creating a pull request? :)

**Comment by patschi** [comment]
As I'm currently not at home and not having a Git client around here, I've went with using GitHub Web :) (Now just hope I've done everything right creating a PR as the NC-team wishes.)

**Comment by blizzz** [comment]
@patschi Cool, thanks! Looks good from my POV, ideally @schiessle gives his final OK.
