### ISSUE TITLE
Upgrade from 11.0.3 to 12.0.0 fails

### ISSUE THREAD

**Issue by 9R** [nextcloud/server#5064]
### Steps to reproduce
1. Follow the upgrade process as described in documentation. Manual and build-in updater (via shell and webinterface) lead to the same result.

### Expected behaviour

Successful upgrade

### Actual behaviour

 occ upgrade throws an exception:
  `Exception: Updates between multiple major versions and downgrades are unsupported.
Update failed`

I ran into this problem on multiple installations. The only way to recover is to delete the nextcloud folder restore from backup.

### Server configuration

**Operating system**:
debian jessie 

**Web server:**
apache 2.2

**Database:**

sqlite

**PHP version:**

php 5.6.30

**Nextcloud version:** (see Nextcloud admin page)

Trying to upgrade to 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**

old version: 11.0.3

**Where did you install Nextcloud from:**

manual install with .zip from nextcloud.com

**Signing status:**

No errors have been found.

**List of activated apps:**

Enabled:
  - activity: 2.4.1
  - calendar: 1.5.3
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - external: 1.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notes: 2.2.0
  - notifications: 1.0.1
  - ocsms: 1.12.0
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: true
Disabled:
  - admin_audit
  - audioplayer
  - encryption
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - user_external
  - user_ldap
  - user_saml

**Nextcloud configuration:**

{
    "system": {
        "dbtype": "sqlite3",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/ncdata",
        "version": "11.0.3.2",
        "installed": true,
        "theme": "",
        "trusted_domains": [
            "example.com"
        ],
        "forcessl": true,
        "mail_from_address": "nc",
        "mail_smtpmode": "smtp",
        "mail_domain": "example.com",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "overwrite.cli.url": "https:\/\/example.com",
        "logtimezone": "UTC",
        "appstore.experimental.enabled": true,
        "loglevel": 0,
        "trashbin_retention_obligation": "auto",
        "maintenance": false,
        "htaccess.RewriteBase": "\/",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "updater.release.channel": "stable",
        "mail_smtphost": "example.com",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

**Are you using external storage, if yes which one:** 
no
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

**Comment by 9R** [comment]
By now I was able to upgrade using the dirty work around from this discussion:

https://help.nextcloud.com/t/cannot-manually-upgrade-from-11-0-3/13054/5

After initial testing everything seems to work ok.

If anyone is interested in finding the root cause of the problem, I still have a backup of the non-working state & can run some tests.

**Comment by TraceyC77** [comment]
This is affecting multiple users, as well as folks migrating from OwnCloud. I found two forums threads discussing the same error.

https://help.nextcloud.com/t/migrating-from-owncloud-to-nextcloud/551/122
https://help.nextcloud.com/t/cannot-manually-upgrade-from-11-0-3/13054/5

**Comment by MorrisJobke** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.

We fixed a lot of problems here and 12.0.12 is enabled for migrations from many ownCloud versions.
