### ISSUE TITLE
App uploads photos twice

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#5068]
* enable auto upload (I'm not sure if it was auto upload or a manual upload, but will check again)
* having some files to be uploaded
* check the server logs:
   * PUT -> response 201 (new file created)
   * PUT to the same file -> response 204 (file overwritten) -> not needed
   * GET to the same file -> not needed

cc @marinofaggiana

**Comment by rullzer** [comment]
@MorrisJobke wrong repo :wink: ?

**Comment by marinofaggiana** [comment]
? please

**Comment by MorrisJobke** [comment]
Yes :/

**Comment by MorrisJobke** [comment]
Yep - https://github.com/nextcloud/ios/issues/245
