### ISSUE TITLE
NC12 ignores custom mail templates for the activity app

### ISSUE THREAD

**Issue by BenS89** [nextcloud/server#5069]
**Steps to reproduce:**

 - Create a custom mail template for the activity app under /themes/customTheme/apps/activity/templates/email.notification.php
- configure your custom theme in the nextcloud config
- Do something and wait for the activity app so send notification mails

**Expected behavior:**
The notification mail uses the configured template (as it was in NC11)

**Actual behaviour:**
The configured template gets ignored. The mail includes the default template text.

Enabled apps:
Calendar 	1.5.3
Contacts 1.5.3

PHP-Version: 7.1.1
OS: Embedded QNAP-Linux

**Comment by LukasReschke** [comment]
Please file activity issues at https://github.com/nextcloud/activity
