### ISSUE TITLE
Images not displayed in Gmail emails

### ISSUE THREAD

**Issue by stephanedupont** [nextcloud/server#5075]
Hello,

The new Nextcloud 12 emails are nice, but images are not displayed in Gmail, as Google is not handling (and not planning to handle) SVG images in their new "proxy" thing.

Source: https://stackoverflow.com/questions/20815613/svg-images-blocked-by-gmail-proxy

Screenshot: 
![image](https://cloud.githubusercontent.com/assets/5102441/26361352/05ae70fa-3fdb-11e7-9222-63fbbeacbacf.png)

Thank you,

**Comment by LukasReschke** [comment]
Do you have a custom theming image? If so you may want to use a PNG version of it.

**Comment by StephaneDupont** [comment]
For the icon on top of the email, yes, I changed the logo via the admin settings.

But for the download icon, no, not at all.

**Comment by LukasReschke** [comment]
Ah. Right the icons must also all be PNGs.

cc @nickvergessen

**Comment by nickvergessen** [comment]
Hmpf :/ so we have to break the API? Or can we have an endpoint that converts svg to png?
But I guess that would only work with imagick?

**Comment by StephaneDupont** [comment]
@LukasReschke I changed the logo to use a PNG version of it, but it's much blurrier than the SVG one. Not ideal!

**Comment by MorrisJobke** [comment]
> @LukasReschke I changed the logo to use a PNG version of it, but it's much blurrier than the SVG one. Not ideal!

No matter if we or you create a PNG out of it. We need to check what size fits best. Maybe you should create a PNG in higher resolution.

**Comment by StephaneDupont** [comment]
@MorrisJobke the higher the resolution, the blurrier it is. I tried with a 2000, 1000 and 400px wide logos, and the 400px wide gets the better result. I'm guessing the resize algorithm is not great and blurs things?

**Comment by elpraga** [comment]
Is it possible to change the `.svg` to `.png` by hand for now? Which file should I edit? I tried to look for the template, but I wasn't able to find it. 

Gmail not displaying the icons doens't look very professional (and users think something is broken in Nextcloud, not in gmail.)

**Comment by nickvergessen** [comment]
Well you would need to edit all files that implement the OCA\Activity\IProvider interface and you also need to create the png versions of all images that are being linked.

**Comment by elpraga** [comment]
How can I find what  files implement the OCA\Activity\IProvider interface? Yes, of course, I'd have to convert the `.svg` to `.png` by hand in order to use them..

**Comment by elpraga** [comment]
`grep -r "IProvider" *` in `apps/activity/` shows only one possible file `lib/Extension/LegacyParser.php`, but there are no mentions of `.svg` files. Could you give me a hint where to look @nickvergessen ?

**Comment by nickvergessen** [comment]
> ![bildschirmfoto vom 2017-06-19 16-19-22](https://user-images.githubusercontent.com/213943/27289736-4b3018f0-550b-11e7-98f1-7636fd9013a0.png)

In those files look for `setIcon(`

**Comment by elpraga** [comment]
Thanks!
