### ISSUE TITLE
Propatch to birthday calendar returns 404

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/server#5077]
### Steps to reproduce
1. Activate or deactivate (show/hide) the birthday contacts
2. Check the console logs

### Expected behaviour
Http code returned should be something like 200.

### Actual behaviour
Http code is 404, returning the following error message :
```
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<s:exception>Sabre\DAV\Exception\NotFound</s:exception>
<s:message>Node with name 'contact_birthdays' could not be found</s:message>
</d:error>
```
The calendar of birthday contacts **is correctly hidden/shown**.

### Server configuration

**Operating system**: Debian Jessie

**Web server:** nginx

**Database:** Mysql

**PHP version:** 7.0

**Nextcloud version:** (see Nextcloud admin page) 11.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 11

### Client configuration
**Browser:** Chrome / Firefox

**Operating system:** GNU/Linux

#### Web server error log
Nothing relevant.

#### Nextcloud log (data/nextcloud.log)
Nothing relevant (loglevel 2)

#### Browser log
See above.
</details>

**Comment by georgehrke** [comment]
I'm almost certainly sure this is related to this line: https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/Calendar.php#L119

It should have an else block, that adds write-properties permission.
Will send a PR
