### ISSUE TITLE
Files app screen broken - 12.0.0.29 - php 7.1.4 - seems css problem

### ISSUE THREAD

**Issue by pongraczi** [nextcloud/server#5081]
### Steps to reproduce
1. Just login and start Files app. Screen is broken as shown on the attached screenshot.

### Expected behaviour
It should be unbroken with nice list, actions etc.

### Actual behaviour
Check the attached screenshot. It is a mess.
![kijeloles_257](https://cloud.githubusercontent.com/assets/5891983/26366832/c81e1e72-3fec-11e7-9929-61e594a7bb04.png)

### Server configuration

**Operating system**:
Debian 8.

**Web server:**
Apache

**Database:**
Mariadb

**PHP version:**
7.1.4

**Nextcloud version:** (see Nextcloud admin page)
12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:**
OC 9.0.9 -> OC 9.1 -> OC 10.0 -> NC 12.0.0.29 

**Where did you install Nextcloud from:**
Downloaded directly from nextcloud website.

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - announcementcenter: 3.1.0
  - bookmarks: 0.10.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - deck: 0.1.4
  - encryption: 1.6.0
  - external: 2.0.2
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.4
  - news: 11.0.1
  - nextcloud_announcements: 1.1
  - notes: 2.2.0
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.1
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_external: 0.4
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - sensorlogger
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "XXXXXXX",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/XXXXXX\/web\/cbox\/data",
        "overwritewebroot": "\/cbox",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "XXXXXXXX",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "hu_HU",
        "theme": "",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\Memcached",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "trusted_domains": [
            "cbox.hu"
        ],
        "mail_smtpmode": "smtp",
        "mail_from_address": "cbox",
        "mail_domain": "XXXXXXXX",
        "mail_smtphost": "localhost",
        "mail_smtpport": "25",
        "loglevel": 3,
        "overwrite.cli.url": "\/cbox",
        "custom_csp_policy": "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *",
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "apps_paths": [
            {
                "path": "\/var\/www\/XXXXX\/web\/cbox\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "trashbin_retention_obligation": "auto",
        "versions_retention_obligation": "30, auto",
        "singleuser": false,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir ",
        "appstore.experimental.enabled": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable"
    },
    "apps": {
        "Object": {
            "enabled": "no"
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.5.2",
            "types": "filesystem"
        },
        "admin_dependencies_chk": {
            "enabled": "no",
            "installed_version": "0.02",
            "ocsid": "166041",
            "types": ""
        },
        "announcementcenter": {
            "enabled": "yes",
            "installed_version": "3.1.0",
            "ocsid": "173921",
            "signed": "true",
            "types": "logging"
        },
        "appframework": {
            "enabled": "no",
            "installed_version": "0.104",
            "ocsid": "162405",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "237"
        },
        "bookmarks": {
            "enabled": "yes",
            "installed_version": "0.10.0",
            "ocsid": "168710",
            "types": ""
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.0.2",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.5.3",
            "ocsid": "168707",
            "signed": "true",
            "types": ""
        },
        "chat": {
            "backend_xmpp_enabled": "1",
            "enabled": "no",
            "installed_version": "0.4.0.0",
            "ocsid": "166443",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "logging"
        },
        "configreport": {
            "enabled": "yes",
            "installed_version": "0.1.1",
            "types": "filesystem"
        },
        "contacts": {
            "backend_ldap": "false",
            "enabled": "yes",
            "installed_version": "1.5.3",
            "ocsid": "168708",
            "signed": "true",
            "types": ""
        },
        "core": {
            "OC_Channel": "stable",
            "backgroundjobs_mode": "cron",
            "default_encryption_module": "OC_DEFAULT_MODULE",
            "enable_external_storage": "yes",
            "encryption_enabled": "no",
            "global_cache_gc_lastrun": "1447020902",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1393596785.18",
            "lastcron": "1495559702",
            "lastupdateResult": "[]",
            "lastupdatedat": "1495555425",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_core.css": "\/core\/minimizer.php",
            "remote_core.js": "\/core\/minimizer.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "scss.variables": "XXXXXXXXXX",
            "shareapi_allow_mail_notification": "yes",
            "shareapi_allow_public_notification": "yes",
            "shareapi_allow_public_upload": "no",
            "shareapi_default_expire_date": "yes",
            "shareapi_only_share_with_group_members": "yes",
            "updater.secret.created": "XXXXXXXXXX",
            "vendor": "nextcloud"
        },
        "dav": {
            "buildCalendarSearchIndex": "yes",
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "deck": {
            "enabled": "yes",
            "installed_version": "0.1.4",
            "types": ""
        },
        "documents": {
            "converter": "local",
            "converter_url": "http:\/\/XXXXXXXX",
            "enabled": "no",
            "installed_version": "0.13.1",
            "ocsid": "168711",
            "types": "",
            "unstable": "false"
        },
        "encryption": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "masterKeyId": "mfadfasfsafsadf",
            "publicShareKeyId": "pufadfsadfsadfasf",
            "recoveryKeyId": "refasdfasdfasfsadf",
            "types": "filesystem"
        },
        "example-theme": {
            "enabled": "no",
            "installed_version": "1.0.0",
            "types": "theme"
        },
        "external": {
            "enabled": "yes",
            "installed_version": "2.0.2",
            "max_site": "1",
            "sites": "{\"1\":{\"icon\":\"\",\"lang\":\"\",\"type\":\"link\",\"id\":1,\"name\":\"F\",\"url\":\"https:\\\/\\\/XXXXXX\\\/\"}}",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "authentication"
        },
        "files": {
            "backgroundwatcher_previous_file": "320",
            "backgroundwatcher_previous_folder": "346",
            "cronjob_scan_files": "500",
            "default_quota": "5 GB",
            "enabled": "yes",
            "installed_version": "1.7.2",
            "types": "filesystem"
        },
        "files_embeddedvideo": {
            "enabled": "no",
            "installed_version": "0.0.7",
            "types": ""
        },
        "files_external": {
            "allow_user_mounting": "yes",
            "enabled": "yes",
            "installed_version": "1.3.0",
            "ocsid": "166048",
            "types": "filesystem",
            "user_mounting_backends": "\\OC\\Files\\Storage\\AmazonS3,\\OC\\Files\\Storage\\Dropbox,\\OC\\Files\\Storage\\FTP,\\OC\\Files\\Storage\\Google,\\OC\\Files\\Storage\\Swift,\\OC\\Files\\Storage\\OwnCloud,\\OC\\Files\\Storage\\SFTP,\\OC\\Files\\Storage\\DAV"
        },
        "files_locking": {
            "enabled": "no",
            "installed_version": "",
            "types": "filesystem"
        },
        "files_mv": {
            "enabled": "no",
            "installed_version": "0.7.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "yes",
            "installed_version": "1.4.0",
            "outgoing_server2server_share_enabled": "yes",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.4.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.1",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "17.0.0",
            "types": ""
        },
        "galleryplus": {
            "enabled": "no",
            "installed_version": "15.0.0",
            "ocsid": "169116",
            "types": ""
        },
        "journal": {
            "enabled": "no",
            "installed_version": "0.4.1",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "yes",
            "installed_version": "0.6.4",
            "types": ""
        },
        "market": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        },
        "mindmap": {
            "enabled": "no",
            "installed_version": "0.8.1",
            "types": "filesystem"
        },
        "music": {
            "enabled": "no",
            "installed_version": "0.3.5",
            "types": "filesystem"
        },
        "news": {
            "enabled": "yes",
            "installed_version": "11.0.1",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.1",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "2.2.0",
            "ocsid": "174554",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.0.5",
            "types": "authentication"
        },
        "ownnote": {
            "enabled": "no",
            "folder": "Jegyzetek",
            "installed_version": "1.08",
            "types": ""
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.2.2",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "no",
            "installed_version": "1.2.0",
            "types": "prevent_group_restriction"
        },
        "rainloop": {
            "enabled": "no",
            "installed_version": "3.3",
            "rainloop-autologin": "",
            "types": ""
        },
        "search_lucene": {
            "enabled": "no",
            "installed_version": "0.6.0",
            "ocsid": "168709",
            "types": "filesystem"
        },
        "sensorlogger": {
            "enabled": "no",
            "installed_version": "0.0.4",
            "types": ""
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "sharelinks": {
            "enabled": "no",
            "installed_version": "1.1.0",
            "ocsid": "170527",
            "types": ""
        },
        "spreed": {
            "enabled": "yes",
            "installed_version": "2.0.1",
            "types": "prevent_group_restriction"
        },
        "startitadmin": {
            "documents": "save_path"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.9.5",
            "ocsid": "164356",
            "types": ""
        },
        "tasks_enhanced": {
            "enabled": "no",
            "installed_version": "0.4.1",
            "types": ""
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "theming": {
            "cachebuster": "3",
            "enabled": "yes",
            "installed_version": "1.3.0",
            "name": "cBox",
            "slogan": "Biztons\u00e1gos hely az adataidnak",
            "types": "logging",
            "url": "https:\/\/XXXXX\/cbox"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "",
            "update_check_errors": "0"
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        },
        "user_external": {
            "enabled": "yes",
            "installed_version": "0.4",
            "ocsid": "166060",
            "types": "authentication,prelogin"
        },
        "user_ldap": {
            "enabled": "no",
            "enforce_home_folder_naming_rule": "",
            "installed_version": "0.9.0",
            "types": "authentication"
        },
        "user_webdavauth": {
            "enabled": "no",
            "installed_version": "1.1.0.1",
            "ocsid": "166062",
            "types": "authentication"
        },
        "videos": {
            "enabled": "no",
            "installed_version": "1.0",
            "ocsid": "161584",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "164319": {
            "enabled": "no",
            "ocsid": "164319"
        }
    }
}

</details>

**Are you using encryption:** yes/no
No.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.

### Client configuration
**Browser:**
Chromium. Firefox.

**Operating system:**
Linuxmint 18.1 (aka Ubuntu 16.04)

#### Web server error log
<details>
<summary>Web server error log</summary>
Almost only this kind of error message.

[Tue May 23 19:36:49.956504 2017] [autoindex:error] [pid 14527] [client 176.63.144.100:35428] AH01276: Cannot serve directory /var/www/XXX/cbox/apps/external/img/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive
[Tue May 23 19:36:53.696496 2017] [autoindex:error] [pid 14527] [client 176.63.144.100:35428] AH01276: Cannot serve directory /var/www/XXX/cbox/apps/external/img/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive
</details>
#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"dwScvNOgN4MHpV2wEtYN","level":3,"time":"2017-05-23T17:36:25+00:00","remoteAddr":"176.63.yyy.yyy","user":"userXXXX","app":"lib","method":"GET","url":"\/cbox\/index.php\/apps\/files\/","message":"ResourceLocator can not find a web root (root: \/var\/www\/XXXXXX\/web\/cbox\/apps\/files, file: index.php\/css\/files\/merged.css, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"12.0.0.29"}
{"reqId":"dwScvNOgN4MHpV2wEtYN","level":3,"time":"2017-05-23T17:36:25+00:00","remoteAddr":"176.63.yyy.yyy","user":"userXXXX","app":"lib","method":"GET","url":"\/cbox\/index.php\/apps\/files\/","message":"ResourceLocator can not find a web root (root: \/var\/www\/XXXXXX\/web\/cbox\/apps\/files_sharing, file: index.php\/css\/files_sharing\/mergedAdditionalStyles.css, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"12.0.0.29"}
{"reqId":"dwScvNOgN4MHpV2wEtYN","level":3,"time":"2017-05-23T17:36:25+00:00","remoteAddr":"176.63.yyy.yyy","user":"userXXXX","app":"lib","method":"GET","url":"\/cbox\/index.php\/apps\/files\/","message":"ResourceLocator can not find a web root (root: \/var\/www\/XXXXXX\/web\/cbox\/apps\/files_texteditor, file: index.php\/css\/files_texteditor\/merged.css, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"12.0.0.29"}
{"reqId":"ZWOf5D2FlC4H57ypxLd6","level":3,"time":"2017-05-23T17:36:40+00:00","remoteAddr":"176.63.yyy.yyy","user":"userXXXX","app":"lib","method":"GET","url":"\/cbox\/index.php\/apps\/files\/","message":"ResourceLocator can not find a web root (root: \/var\/www\/XXXXXX\/web\/cbox\/apps\/files, file: index.php\/css\/files\/merged.css, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"12.0.0.29"}
{"reqId":"ZWOf5D2FlC4H57ypxLd6","level":3,"time":"2017-05-23T17:36:40+00:00","remoteAddr":"176.63.yyy.yyy","user":"userXXXX","app":"lib","method":"GET","url":"\/cbox\/index.php\/apps\/files\/","message":"ResourceLocator can not find a web root (root: \/var\/www\/XXXXXX\/web\/cbox\/apps\/files_sharing, file: index.php\/css\/files_sharing\/mergedAdditionalStyles.css, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"12.0.0.29"}
{"reqId":"ZWOf5D2FlC4H57ypxLd6","level":3,"time":"2017-05-23T17:36:40+00:00","remoteAddr":"176.63.yyy.yyy","user":"userXXXX","app":"lib","method":"GET","url":"\/cbox\/index.php\/apps\/files\/","message":"ResourceLocator can not find a web root (root: \/var\/www\/XXXXXX\/web\/cbox\/apps\/files_texteditor, file: index.php\/css\/files_texteditor\/merged.css, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"12.0.0.29"}
{"reqId":"FDYya4yJxEaIO6n4I1Yt","level":3,"time":"2017-05-23T17:36:49+00:00","remoteAddr":"176.63.yyy.yyy","user":"userXXXX","app":"lib","method":"GET","url":"\/cbox\/index.php\/apps\/files\/?dir=\/Jegyzetek","message":"ResourceLocator can not find a web root (root: \/var\/www\/XXXXXX\/web\/cbox\/apps\/files, file: index.php\/css\/files\/merged.css, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"12.0.0.29"}
{"reqId":"FDYya4yJxEaIO6n4I1Yt","level":3,"time":"2017-05-23T17:36:49+00:00","remoteAddr":"176.63.yyy.yyy","user":"userXXXX","app":"lib","method":"GET","url":"\/cbox\/index.php\/apps\/files\/?dir=\/Jegyzetek","message":"ResourceLocator can not find a web root (root: \/var\/www\/XXXXXX\/web\/cbox\/apps\/files_sharing, file: index.php\/css\/files_sharing\/mergedAdditionalStyles.css, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"12.0.0.29"}
{"reqId":"FDYya4yJxEaIO6n4I1Yt","level":3,"time":"2017-05-23T17:36:49+00:00","remoteAddr":"176.63.yyy.yyy","user":"userXXXX","app":"lib","method":"GET","url":"\/cbox\/index.php\/apps\/files\/?dir=\/Jegyzetek","message":"ResourceLocator can not find a web root (root: \/var\/www\/XXXXXX\/web\/cbox\/apps\/files_texteditor, file: index.php\/css\/files_texteditor\/merged.css, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"12.0.0.29"}

</details>

#### Browser log
<details>
<summary>Browser log</summary>
It will be not so useful for you, as it is in Hungarian. But all lines from css are errors, declarations dropped.  They cannot decode the value of parameters, seems the css messed up.
I translated back to English some messages to get the meaning.

Unknown property: „zoom”.  Declaration dropped.  select2.css:9:8
Expected deklaráció helyett „*” található.  Ugrás a következő deklarációra.  select2.css:10:4
Unknown property: „user-select”.  Declaration dropped.  select2.css:49:25
Error a(z) „background-image” értékének értelmezése közben.  Declaration dropped.  select2.css:53:78
Expected „none”, egy URL vagy szűrőfüggvény helyett „progid” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  select2.css:55:12
Error a(z) „background-image” értékének értelmezése közben.  Declaration dropped.  select2.css:65:78
Expected „none”, egy URL vagy szűrőfüggvény helyett „progid” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  select2.css:67:12
Expected „none”, egy URL vagy szűrőfüggvény helyett „alpha(” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  select2.css:128:12
Error a(z) „background-image” értékének értelmezése közben.  Declaration dropped.  select2.css:193:78
Expected „none”, egy URL vagy szűrőfüggvény helyett „progid” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  select2.css:195:12
Error a(z) „background” értékének értelmezése közben.  Declaration dropped.  select2.css:239:114
Error a(z) „background” értékének értelmezése közben.  Declaration dropped.  select2.css:251:116
Error a(z) „background-image” értékének értelmezése közben.  Declaration dropped.  select2.css:275:78
Expected „none”, egy URL vagy szűrőfüggvény helyett „progid” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  select2.css:277:12
Error a(z) „background-image” értékének értelmezése közben.  Declaration dropped.  select2.css:287:75
Expected „none”, egy URL vagy szűrőfüggvény helyett „progid” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  select2.css:289:12
Unknown property: „user-select”.  Declaration dropped.  select2.css:350:25
Unknown property: „user-select”.  Declaration dropped.  select2.css:529:25
Expected „none”, egy URL vagy szűrőfüggvény helyett „progid” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  select2.css:532:12
Expected médiafunkciónév helyett „-webkit-min-device-pixel-ratio” található.  select2.css:633:24
Expected „none”, egy URL vagy szűrőfüggvény helyett „Alpha(” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  jquery-ui.css:49:8
Expected „none”, egy URL vagy szűrőfüggvény helyett „alpha(” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  jquery-ui.css:538:9
Expected „none”, egy URL vagy szűrőfüggvény helyett „Alpha(” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  jquery-ui.css:918:8
Expected „none”, egy URL vagy szűrőfüggvény helyett „Alpha(” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  jquery-ui.css:925:8
Expected „none”, egy URL vagy szűrőfüggvény helyett „Alpha(” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  jquery-ui.css:929:8
Expected „none”, egy URL vagy szűrőfüggvény helyett „Alpha(” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  jquery-ui.css:1177:9
Expected „none”, egy URL vagy szűrőfüggvény helyett „Alpha(” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  jquery-ui.css:1184:9
Expected „none”, egy URL vagy szűrőfüggvény helyett „alpha(” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  versions.css:20:9
Expected „none”, egy URL vagy szűrőfüggvény helyett „alpha(” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  versions.css:31:9
Unknown property: „user-select”.  Declaration dropped.  style.css:75:4494
Ismeretlen pszeudoosztály vagy pszeudoelem „-webkit-full-screen”.  A szabálykészlet figyelmen kívül hagyva rossz szelektor miatt.  style.css:75:4793
Expected „none”, egy URL vagy szűrőfüggvény helyett „progid” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  style.css:91:9
Unknown property: „-moz-border-radius”.  Declaration dropped.  style.css:53:19
Expected „none”, egy URL vagy szűrőfüggvény helyett „alpha(” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  style.css:186:9
Expected „none”, egy URL vagy szűrőfüggvény helyett „alpha(” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  style.css:207:9
Unknown property: „user-select”.  Declaration dropped.  slideshow.css:16:12
Error a(z) „background” értékének értelmezése közben.  Declaration dropped.  comments.css:98:13
Error a(z) „background” értékének értelmezése közben.  Declaration dropped.  comments.css:99:13
Expected „none”, egy URL vagy szűrőfüggvény helyett „progid” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  comments.css:101:9
Unknown property: „-moz-box-shadow”.  Declaration dropped.  comments.css:168:16
Expected „none”, egy URL vagy szűrőfüggvény helyett „alpha(” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  gallerybutton.css:152:9
Ismeretlen pszeudoosztály vagy pszeudoelem „-webkit-scrollbar”.  A szabálykészlet figyelmen kívül hagyva rossz szelektor miatt.  server.css:1:1999
Ismeretlen pszeudoosztály vagy pszeudoelem „-webkit-scrollbar-track-piece”.  A szabálykészlet figyelmen kívül hagyva rossz szelektor miatt.  server.css:1:2029
Ismeretlen pszeudoosztály vagy pszeudoelem „-webkit-scrollbar-thumb”.  A szabálykészlet figyelmen kívül hagyva rossz szelektor miatt.  server.css:1:2090
Ismeretlen pszeudoosztály vagy pszeudoelem „-webkit-search-cancel-button”.  A szabálykészlet figyelmen kívül hagyva rossz szelektor miatt.  server.css:1:3517
Unknown property: „user-select”.  Declaration dropped.  server.css:1:3816
Unknown property: „user-select”.  Declaration dropped.  server.css:1:6082
Unknown property: „user-select”.  Declaration dropped.  server.css:1:6365
Unknown property: „user-select”.  Declaration dropped.  server.css:1:7198
Unknown property: „user-select”.  Declaration dropped.  server.css:1:8128
Unknown property: „list-style-indent”.  Declaration dropped.  server.css:1:8235
Unknown property: „appearance”.  Declaration dropped.  server.css:1:25903
Unknown property: „user-select”.  Declaration dropped.  server.css:1:26523
Unknown property: „-moz-border-radius”.  Declaration dropped.  server.css:1:44733
Expected médiafunkciónév helyett „-webkit-max-device-pixel-ratio” található.  server.css:1:56728
Unknown property: „user-select”.  Declaration dropped.  server.css:1:58107
Expected szín helyett „top” található.  Error a(z) „background-image” értékének értelmezése közben.  Declaration dropped.  server.css:1:60190
Error a(z) „background-image” értékének értelmezése közben.  Declaration dropped.  server.css:1:60310
Fityegő kombinátor.  A szabálykészlet figyelmen kívül hagyva rossz szelektor miatt.  server.css:1:60494
Error a(z) „text-overflow” értékének értelmezése közben.  Declaration dropped.  server.css:1:62959
Expected „none”, egy URL vagy szűrőfüggvény helyett „alpha(” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  server.css:1:70559
Expected „none”, egy URL vagy szűrőfüggvény helyett „alpha(” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  server.css:1:70980
Unknown property: „-moz-box-shadow”.  Declaration dropped.  server.css:1:72118
Error a(z) „display” értékének értelmezése közben.  Declaration dropped.  server.css:1:73936
Unknown property: „line-break”.  Declaration dropped.  server.css:1:75777
Expected „none”, egy URL vagy szűrőfüggvény helyett „alpha(” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  server.css:1:76011
Expected „none”, egy URL vagy szűrőfüggvény helyett „alpha(” található.  Error a(z) „filter” értékének értelmezése közben.  Declaration dropped.  server.css:1:76058
JQMIGRATE: Migrate is installed, version 1.4.0  core.js:7:542
Unknown property: „user-select”.  Declaration dropped.  files:1:351
Unknown property: „user-select”.  Declaration dropped.  files:1:989
Unknown property: „appearance”.  Declaration dropped.  files:1:4070
Unknown property: „user-select”.  Declaration dropped.  files:1:4278
</details>

**Comment by ldapomni** [comment]
Look as Issue #5057?

**Comment by pongraczi** [comment]
Yes, it seems the same. As I can see in my server, only Files app affected.
Anyway, in my browser log I can see a lot of unknown/dropped css properties etc.

**Comment by pongraczi** [comment]
Ok, it seems lot of properties does not supported by firefox.

**Comment by callmemagnus** [comment]
The display is also broken on Chromium.

**Comment by MorrisJobke** [comment]
Will be fixed in 12.0.1 and 13.0.0.

And also note: update from OC10 to NC 12 is not yet fully supported.
