### ISSUE TITLE
Cannot sync NC Calendar with Google Calendar

### ISSUE THREAD

**Issue by GillesMoyse** [nextcloud/server#5086]
### Context
I've got 3 calendars attached to my user. Some are shared with other users on my NC (thomas and melchior), some are shared publicly. "Gilles (Récital)" and "Gilles (perso)" belong to the user "gilles" and "Récital (Calendar)" is shared by another user.

<img width="220" src="https://cloud.githubusercontent.com/assets/18755733/26394014/e9066692-406b-11e7-84ce-6416d61a400b.jpg">

I want to share "Gilles (perso)" with a Google Calendar user.

### Steps to reproduce
1. Get the link for "Gilles (perso)"
<img width="220" src="https://cloud.githubusercontent.com/assets/18755733/26394055/10e44814-406c-11e7-8d3e-f6b7821ebcc5.jpg">
2. In Google Calendar, copy the link in Other Calendars / Add by URL
<img width="300" src="https://cloud.githubusercontent.com/assets/18755733/26394116/326ebf28-406c-11e7-9d6b-167db24a45c8.jpg">
3. Error "Could not fetch the URL" in Google Calendar

### Expected behaviour
The shared calendar should appear in Google Calendar

### Actual behaviour
It does not

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
NextCloud v11.0.3, Calendar App v1.5.3

Integrity test : 
```
No errors have been found.
```

**Are you using encryption:** yes

**Are you using an external user-backend:** no

### Client configuration
**Browser:** Firefox 53.0.2

**Operating system:** Windows 10 version 1703 OS Build 15063.296

**Comment by EMiT57** [comment]
Hi,

The share is https://framagenda.org/index.php/apps/calendar/p/xxxxxxxxxxxxxxxxx
and if you use this link in in G Calendar -> no error, but no result :(

But on this share adress they are a button with and other link like webcal://framagenda.org/remote.php/dav/public-calendars/xxxxxxxxxxxxxxxx?export
and if you use this link in G Calendar, all work fine

Regards

**Comment by GillesMoyse** [comment]
Hi,

thanks for the tip, unfortunately I still have the same error on Google Calendar...

**Comment by MorrisJobke** [comment]
@georgehrke Any idea?

**Comment by georgehrke** [comment]
You have to publicly share the calendar and ics link you can find on the public sharing site.

The link u used is only meant for you and can only be accessed with your username / password

**Comment by georgehrke** [comment]
Can you manually access the dav public calendars link? 

Are there any error logs in the server when you add it to google?

**Comment by prky** [comment]
I had the same issue, and discovered that the URL Google Calendar requires is a modifying the webcal URL to replace webcal:// with https:// (or http:// if you're not using SSL).

So, what worked for me in Google Calendar to add as a URL was:

https://domain.com/remote.php/dav/public-calendars/xxxxxxxxxxxxxxxx?export

**Comment by GillesMoyse** [comment]
My NextCloud instance is hosted, so I can't access to the logs or DB.

I tried every address I could fetch from the calendar app:
- Primary CalDAV address: https://cloud.recital.ai/remote.php/dav/
- Link under the calendar: https://cloud.recital.ai/remote.php/dav/calendars/gilles/gilles-perso/
- OS/OS X CalDAV address: https://cloud.recital.ai/remote.php/dav/principals/users/gilles/
- Address next to "Public access": https://cloud.recital.ai/index.php/apps/calendar/p/AA1LMYCH88WYP5Y6

None of them work. It is killing me, but I'll go back to Google. I can't afford to spend so much time configuring basic functionalities.

**Comment by georgehrke** [comment]
https://cloud.recital.ai//remote.php/dav/public-calendars/AA1LMYCH88WYP5Y6?export works, as described by @prky

**Comment by GillesMoyse** [comment]
Very strange, it does not work, neither for me nor for my girlfriend. When we "Add by URL" the address we still have the error "We could not parse the calendar at the URL requested.". Does it work for you on your Google Agenda?

**Comment by georgehrke** [comment]
The url itself is correct, but i can't use it in google calendar either.

I guess its related to this: https://support.google.com/calendar/answer/45654?vid=0-672238030094-1504364668494&visit_id=1-636399614749886905-461172282&rd=1

> Google Calendar only works with  files that are one megabyte (1MB) or smaller.

Your file is 3.35MB

**Comment by GillesMoyse** [comment]
I also tried this option, exporting the whole calendar and import it in Google, but faced the 1MB limit too. What I'd like to do though is to sync the calendar - but the link does not work either. @prky, does the full link I provided work on your Google agenda, i.e. can you retrieve my events from your google agenda?

**Comment by prky** [comment]
@GillesMoyse If I try and add your calendar by URL (https://cloud.recital.ai/remote.php/dav/public-calendars/AA1LMYCH88WYP5Y6?export) it attempts to load the calendar, then responds "We could not parse the calendar at the URL requested" - presumably due to it being 3.5MB with over 7000 entries in it.

Unfortunately that's a limitation on the Google side (1MB limit) not NextCloud.

If you want to import, perhaps try splitting it into multiple files as suggested at https://productforums.google.com/forum/?hl=en#!category-topic/calendar/calendar-not-loading/EqOUPboHrmU ?

**Comment by GillesMoyse** [comment]
Ok, thanks a lot, it's working! I first tried with another smaller calendar and it worked, so I removed older events using my desktop email client and it's working now.

By the way, could you please remove the calendar links form your previous comments, so that my calendar access is not accessible from anywhere...:)

**Comment by georgehrke** [comment]
> By the way, could you please remove the calendar links form your previous comments, so that my calendar access is not accessible from anywhere...:)

Done, but you might still want to consider unpublishing and publishing the calendar again, so it gets a new token.

**Comment by GillesMoyse** [comment]
Thanks a lot, I didn't know we could change the token this way...

**Comment by Brice187** [comment]
@georgehrke does your subscribed NC-Calendar gets updated on google, if you create a new event? I think after the initial sync there is no further synchronization. :-(

**Comment by benyanke** [comment]
Maybe I'm missing something, but is there any solution other than setting to public? that's not something I'm willing to do...

I also have the issue of the one-time sync, and not updating after that. Perhaps a cache header is being set wrong, or is it google's issue?

**Comment by Brice187** [comment]
i have no solution, therefore i am using google till this issue may get fixed.

**Comment by torstenfabricius** [comment]
As far as I see it, there are issues on the Google side and not on the NC side.
Google likely has no interest to fix this type of issues, when users deside to use Google until Google stops breaking things.
Google is not payed by your wallet, but with your data.
Rather think about not using Google until Google fix the issue ...

Just my 2 ct.
