### ISSUE TITLE
Typo within test mail

### ISSUE THREAD

**Issue by patschi** [nextcloud/server#5087]
### Steps to reproduce
1. Go to Admin area > Additional settings
2. Send test mail
3. Receive test mail

### Expected behaviour
To get a test mail.

### Actual behaviour
Got a test-mail, with strange "1" in the welcome header:
![image](https://cloud.githubusercontent.com/assets/2029878/26396369/518033ea-4073-11e7-858d-7c606a45f13b.png)

I started a search myself to find out where this "1" comes from, but I couldn't find the right file within this jungle of PHP files :) Possible it's the current user id?

### Server configuration
*Info stripped as it may not be really related to the issue*

**Operating system**: Ubuntu

**Web server:** nginx

**Database:** MariaDB

**PHP version:** PHP 7.0

**Nextcloud version:** 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** Nextcloud site

**Comment by dan-nkl** [comment]
Should be this file:
https://github.com/nextcloud/server/blob/master/settings/Controller/MailSettingsController.php#L152

**Comment by patschi** [comment]
As I'm aware of translations will be handled using transifex and imported automatically from there. So I guess translation fixes should done directly on https://www.transifex.com/nextcloud/nextcloud/language/de_DE/. 
But I'm not sure how this all is exactly handled here.

**Comment by dan-nkl** [comment]
I'm new to this and I don't know how this is handled ¯\_(ツ)_/¯
Just hopping that the Pull Request will help fixing the issue faster.

**Comment by JSoko** [comment]
The error was in the translation:
![grafik](https://cloud.githubusercontent.com/assets/5583290/26450438/beab3796-4157-11e7-8bcb-700216593715.png)
It's now corrected...

Thanks for reporting!
