### ISSUE TITLE
Bearer auth backend causes problems with several dav clients

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#5088]
The topic is getting way too much replies:
https://help.nextcloud.com/t/nc12-authentication-issue-with-cardav-caldav-and-sogo-connector/12924/

We need to find a way for this, so it doesn't break all the clients anymore.

cc @LukasReschke

**Comment by GieltjE** [comment]
#5092 Appears to be a duplicate or at least directly related.

**Comment by nickvergessen** [comment]
Yeah, see the link to the forum above for a temporary workaround

**Comment by LukasReschke** [comment]
Does reordering the auth mechanisms help or should we do something _REALLY_ hacky and prevent the second Authenticate header?

Note that this really is more of a bug in the clients… but well, if apparently all clients implement such stuff incorrectly 🙈

**Comment by nickvergessen** [comment]
Reordering doesn't seem to help, because the order is different on the dav/ endpoint, but many people also have problems on that one.

**Comment by LukasReschke** [comment]
K, we'll then just pretend to only do Basic Auth 🙈

**Comment by Aehrraid** [comment]
Thanks for bringing this in 12.0.1. When will this be released? Where can I find a release-plan for minor updates? The topic is quite important for me. 
I found https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule and https://github.com/nextcloud/server/milestone/25 but those didn't help a lot.

**Comment by nickvergessen** [comment]
@Aehrraid you can also just fix it manually right now with:
https://help.nextcloud.com/t/nc12-authentication-issue-with-cardav-caldav-and-sogo-connector/12924/9

the "average" release cycle is 4weeks
