### ISSUE TITLE
Calendar and contact synchronisation with Thunderbird broken after migration to Nextcloud 12.0.0

### ISSUE THREAD

**Issue by foliz** [nextcloud/server#5092]
### Steps to reproduce
I successfully migrated from Nextcloud 11.0.2 to 12.0.0 (on 3 different instances).
To see my calendars and contacts on my laptop running `OS X 10.11.6`, I am using `Thunderbird 51.1.1` using `Lightning 5.4.1.1` and `Inverse SOGo Connector 31.0.0`.

### Expected behaviour
Calendars and contacts synchronisation should work.

### Actual behaviour
Calendars and contacts synchronisation does not happened any more, on any of the 3 instances.

### Server configuration

**Operating system**: Linux

**Web server:** Apache

**Database:** PostgreSQL 9.6.1

**PHP version:** 7.1.0

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 10.0.2

**Where did you install Nextcloud from:** Web Installer

**Signing status:**
```
No errors have been found.
```

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 53.0.3

**Operating system:** OS X 10.11.6

**Comment by GieltjE** [comment]
We are experiencing the same issues, it's broken for all clients we have (including outlook).
Everything returns http status 401.

"PROPFIND /remote.php/dav/calendars/GieltjE/werk-1/ HTTP/2.0" 401 557 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Thunderbird/52.1.1 Lightning/5.4.1.1"
"GET /remote.php/dav/calendars/GieltjE/werk-1/ HTTP/1.1" 401 8914 "-" "Microsoft Office/16.0 (Windows NT 10.0; Microsoft Outlook 16.0.4498; Pro)"

**Comment by nickvergessen** [comment]
Closing as duplicate
