### ISSUE TITLE
Hide contact icon when contacts app is disabled

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/server#5096]
The contact icon on the upper right corner is shown, even if contacts app is disabled.

### Expected behaviour
Icon should be hidden, because there are no contacts

### Actual behaviour
![image](https://cloud.githubusercontent.com/assets/16019165/26409210/33e6df0a-40a0-11e7-99b8-0a35e3b2b853.png)

### Server configuration

**Operating system**: CentOS 7

**Web server:** Apache

**Database:** MySQL/MariaDB

**PHP version:** 7.0

**Nextcloud version:** (see Nextcloud admin page) 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** OC 9.1 -> NC 10 -> NC 11 -> NC 12

**Where did you install Nextcloud from:** tar.bz2 file from website

**Are you using an external user-backend, if yes which one:** LDAP/Active Directory

**Comment by MariusBluem** [comment]
Hmm... The contacts menu does not only show contacts from the contacts app 😉 It does also show local users. We may want to hide the contacts menu if you are the only user 🤔 - but we may need this menu for Federation reasons in the future...

@ChristophWurst

**Comment by BornToBeRoot** [comment]
@MariusBluem we are using the LDAP backend and have no local users. Maybe add an option to disable/hide it via config.php ?

**Comment by MariusBluem** [comment]
Ok. THX. Closing in favor of #4656

**Comment by christiantosta** [comment]
I'm using JSLoader App to remove that icon. Install it and add the code below to that configuration:

> $('.icon-contacts.menutoggle').remove()
