### ISSUE TITLE
External storage not accessible on certain clients when "session credentials" is used (LDAP)

### ISSUE THREAD

**Issue by Larx** [nextcloud/server#5098]
### Steps to reproduce
1. Add an external storage (in my case: SFTP) and don't supply username/password, but use "session credentials"
2. Access NextCloud with e.g. FireFox on Linux, Android, Windows, or via Gnome GOA WebDAV: Works as expected.
3. Access NextCloud with the AndroidClient or e.g. Foldersync: The external storage does not show up.

### Expected behaviour
The external storage should be accessible with all clients.

### Actual behaviour
Certain (Android??) clients don't show the storage.

### Server configuration

**Operating system**:
openSUSE 42.2
**Web server:**
Apache2.4
**Database:**
MySQL
**PHP version:**
7
**Nextcloud version:** (see Nextcloud admin page)
12
**Updated from an older Nextcloud/ownCloud or fresh install:**
11 (latest version)
**Where did you install Nextcloud from:**
openSUSE build service
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

I know I had this problem already with a previous Next- (or Own-)Cloud version. However, I cannot find that anymore on the net.

**Comment by Larx** [comment]
This might be an LDAP problem. LDAP login from my desktop devices takes very long, but works. All accesses from Android (be it client or browser based) time out. (They partially worked when reporting the bug, I guess some caching was still active)

Error message when logging in (successfully) from desktop:
ldap_search(): Partial search results returned: Sizelimit exceeded at /srv/www/htdocs/nextcloud/apps/user_ldap/lib/LDAP.php#293

Error message when (failing) logging in from Android:

Warning	core	Login failed: 'user' (Remote IP: '????')	2017-05-25T10:15:35+0200
Warning	user_ldap	Bind failed: 49: Invalid credentials

The LDAP setting has worked for all previous own/nextcloud versions and still works for all other applications using it.
Bind user is unencrypted/anonymous with no password at all.
The LDAP server is just a family thing, i.e. it only has 6 user entries in it, so it should be manageable...

**Comment by Larx** [comment]
I now also lost LDAP access with my desktop computer. Seems that some cache was still working and has now expired.

So summary: I can no longer access NC with LDAP users over WebDAV. Login over the web interface seems to work, but takes ages (if LDAP is enabled, it takes ages for both LDAP and local NC users).

Known issue?

**Comment by Larx** [comment]
`Sabre\DAV\Exception\ServiceUnavailable: HTTP/1.1 503 OC\ServerNotAvailableException: Connection to LDAP server could not be established

    /srv/www/htdocs/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php - line 199: OCA\DAV\Connector\Sabre\Auth->check(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /srv/www/htdocs/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php - line 150: Sabre\DAV\Auth\Plugin->check(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    [internal function] Sabre\DAV\Auth\Plugin->beforeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /srv/www/htdocs/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /srv/www/htdocs/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466: Sabre\Event\EventEmitter->emit('beforeMethod', Array)
    /srv/www/htdocs/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /srv/www/htdocs/nextcloud/apps/dav/appinfo/v1/webdav.php - line 71: Sabre\DAV\Server->exec()
    /srv/www/htdocs/nextcloud/remote.php - line 162: require_once('/srv/www/htdocs...')
    {main}`

**Comment by skjnldsv** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
