### ISSUE TITLE
Not syncing with S3 after upgrade to 12.0.0

### ISSUE THREAD

**Issue by judgej** [nextcloud/server#5101]
### Steps to reproduce
1. Installed 11.0.0 intially
2. Took online upgrades through 11.0.5(?) to 12.0.0
3. Amazon S3 external storage is showing no files.
4. Adding a file *does* show up in the bucket when looked at through the Amazon control panel.

### Expected behaviour
Let's see the files on S3! I've got 5000 of the, in 169 diectories, nested four deep.

### Actual behaviour
As described above.

### Server configuration

**Operating system**: Linux

**Web server:** CentOS

**Database:** MySQL

**PHP version:** 5.6 FastCGI

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 11.0.0

**Where did you install Nextcloud from:** Initially the single PHP script through the web browser. The update through the web browser too.

Okay - getting bored now, and I need to go. I'll post the logged message further down.

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

This shows up in the log entries for each time I try to view the S2 external storage files:

    Undefined index: lastmodified at /var/www/vhosts/my-web-root/apps/files_external/lib/Lib/Storage/AmazonS3.php#273

^^ I'm guessing this is the key point, and I can supply further details on request.

**Comment by judgej** [comment]
Changing this bit of code where the error is reported gets the files displaying again:

```php
				$stat['size'] = $result['ContentLength'] ? $result['ContentLength'] : 0;
				if ($result['Metadata']['lastmodified']) {
					$stat['mtime'] = strtotime($result['Metadata']['lastmodified']);
				} else {
					$stat['mtime'] = strtotime($result['LastModified']);
				}
```

to

```php
				$stat['size'] = $result['ContentLength'] ? $result['ContentLength'] : 0;
				if (! empty($result['Metadata']['lastmodified'])) { // catch not set as well as not true
					$stat['mtime'] = strtotime($result['Metadata']['lastmodified']);
				} else {
					$stat['mtime'] = strtotime($result['LastModified']);
				}
```

**Comment by judgej** [comment]
Oh, issue #3673 says that nothing should touch the bucket other than Nextcloud. Wasn't expecting that. I thought it could be used as an external service in the same way that an external local file system could be used to dump files into. Guess I'm going to have to rethink how I use this tool.

**Comment by MorrisJobke** [comment]
> Oh, issue #3673 says that nothing should touch the bucket other than Nextcloud. Wasn't expecting that. I thought it could be used as an external service in the same way that an external local file system could be used to dump files into. Guess I'm going to have to rethink how I use this tool.

Correct. It is only used with file IDs for example and Nextcloud will not detect changes, because this would cause a whole new set of problems.

Closing this.
