### ISSUE TITLE
X-XSS-Protection header invalid (NextCloud 12.0.0.29)

### ISSUE THREAD

**Issue by naksitrallid** [nextcloud/server#5102]
.htaccess contains:

Header set X-XSS-Protection "1; mode=block"

which is not valid. Chrome and probably some others (i used Chrome 58.0.3029.110) report semicolon is missing. have to be:

Header set X-XSS-Protection "1; mode=block;"

**Comment by LukasReschke** [comment]
As per https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection this seems to be correct without `;` at the end and I also don't get the error. Are you sure it's not a plugin messing around?
