### ISSUE TITLE
Broken apps - MIME type ('text/html') is not executable

### ISSUE THREAD

**Issue by C0rn3j** [nextcloud/server#5103]
 pacman -Q nextcloud   
nextcloud 12.0.0-1

Chrome console with the errors - https://i.imgur.com/ZOO7Knn.png

This may happen because of my stricter nginx settings

https://observatory.mozilla.org/analyze.html?host=cloud.c0rn3j.com

**Comment by LukasReschke** [comment]
Please instruct your web server to serve JavaScript files with its proper mime-type, we forbid mimetype sniffing so this likely won't work.

**Comment by C0rn3j** [comment]
In my `/etc/nginx/mime.types`
is a line saying
`application/javascript js;`

I've tried adding

`add_header  Content-Type    application/x-javascript;`

in the     `location ~* \.(?:css|js|woff|svg|gif)$ {` block, which resulted in many other warnings, but the angular .js files still get reporteda as text/html, I don't know how to proceed.

I've also tried including the `/etc/nginx/mime.types` file in various places without any results.

**Comment by C0rn3j** [comment]
I am still having this issue, not a fan of the insta close.

https://gitlab.com/C0rn3j/configs/blob/master/rpi3/nginx.conf

https://gitlab.com/C0rn3j/configs/blob/master/rpi3/nextcloud.conf

These are my webserver configs, feel free to point out my mistake.

**Comment by C0rn3j** [comment]
Solved.

https://help.nextcloud.com/t/all-extra-apps-fails-to-load-due-to-mime-type-mismatch/21111

You can't place an extra apps folder outside the nextcloud root directory without adding an appropriate nginx block.
