### ISSUE TITLE
NC12, Adding user not possible

### ISSUE THREAD

**Issue by michaelletzgus** [nextcloud/server#5114]
Stable 12.0.0.29 (upgrade from 11.3 via upgrade app), trying to add an user.

1. js-console:
TypeError: result.responseJSON is undefined[Weitere Informationen]  users.js:1050:7

2. network-console, xhr request:
https://<server>/settings/users/users results in 403 forbidden
HTTP response contains the "Zugriff verboten, CSRF check failed" page

Update: The request header does not contain the nc_samesitecookie options, only the __HOST-prefixed ones. Current master does send the unprefixed nc_samesitecookie options and user adding works.

3. server error log: nothing

4. server acces log:
only https://<server>/settings/users/users

Findings so far:
* Problem is initially "caused" by by password policy app
* User can't  see this because the error message does never reach the screen
=> Adding users is working correctly
=> password policy app might work correct, too (problem with error messages)
=> Message is not forwarded properly in UsersControler.php, catch, Line 404

**Comment by LukasReschke** [comment]
I bet you use Nginx, please check https://github.com/nextcloud/documentation/pull/392 and make sure to always keep your Nginx config up-to-date or use a Apache, our recommended web server, where we actually can control such things via `.htaccess`.

**Comment by michaelletzgus** [comment]
Thanks for the hint - this resolves the missing message.
Now I have message like

`Fehler beim Anlegen des Benutzers: {message}`
