### ISSUE TITLE
Profile picture scrolling issues

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#5119]
Have a look:

<img width="260" alt="bildschirmfoto 2017-05-26 um 10 17 32" src="https://cloud.githubusercontent.com/assets/19711361/26487134/729da22e-41fe-11e7-8536-f9485f492a9a.png">

...seems to be only appearing with Safari.

@ChristophWurst @nextcloud/designers

**Comment by jancborchardt** [comment]
@MariusBluem any way you can debug with Safari?

**Comment by MorrisJobke** [comment]
Fix is in #7303
