### ISSUE TITLE
Dynamically set maxApps display

### ISSUE THREAD

**Issue by patschi** [nextcloud/server#5121]
Idea would be basically to be able to set the amount of apps to be shown by default in the headers.  Currently only 8 apps are going to be displayed, more apps will be displayed in the "More apps" dropdown.

Everything seems to be handled dynamically via JS already, just  `var maxApps = 8;` variable in [/core/js/js.js#L1514](https://github.com/nextcloud/server/blob/6d9cb62f79a634aaf68daa8abb786bf7f92a0c0a/core/js/js.js#L1514) needs to be defined over PHP.

**Comment by wwwindisch** [comment]
Does a higher default value cause any negative side effects? I've set it to `var maxApps = 32;` and everything seems to work as expected:
All of my activated apps (currently 14) are shown in fullscreen mode in the top bar. When I resize the browser window, they get automatically grouped into the "More apps" dropdown.

What I mean: Is it even necessary to define maxApps over PHP? Or would a higher default value (as a quick, straight forward solution) solve the issue as well?

**Comment by juliushaertl** [comment]
@jancborchardt @nextcloud/designers any opinion on that? For me it would also make sense to just remove the maximum apps limit, since we reduce the showed apps depending on the screen space already.
