### ISSUE TITLE
Missing remoteshare name in activity notification mail

### ISSUE THREAD

**Issue by patschi** [nextcloud/server#5125]
### Steps to reproduce
1. Getting informed about any activity by mail

### Expected behaviour
To know which remote share of the activity mail.

### Actual behaviour
Missing remote share name in mail, seen here:
![image](https://cloud.githubusercontent.com/assets/2029878/26491761/3a1d0b52-4211-11e7-90d6-143be55c184e.png)

Additionally showing the image fails as well. It seems it tries to load the SVG image over the internet, IMHO it should be directly integrated within the mail using base64?

### Server configuration

**Operating system**: Ubuntu 16.04 LTS
**Web server:** nginx
**PHP version:** 7.0
**Nextcloud version:** Nextcloud 12.0.0.29
**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Comment by patschi** [comment]
I've found the line of the origin translation, everything seems to be right there. Something failed when retrieving the `file`-Array-Key by `getParsedParameters()` of the `IEvent $event`: [/stable12/apps/files_sharing/lib/Activity/Providers/RemoteShares.php#L94](https://github.com/nextcloud/server/blob/stable12/apps/files_sharing/lib/Activity/Providers/RemoteShares.php#L94)

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
Should be solved since a long time
