### ISSUE TITLE
Error 500 with NC 12 and PHP 7.1.5

### ISSUE THREAD

**Issue by jamfx** [nextcloud/server#5130]
Hi, I am Running a NC 12 with  PHP-Version 5.6 .
I wanted to upgrade (update) my PHP-Version to 7.1.5. When I do so, I got an Error 500 and Nextcloud is not loading. 

### Steps to reproduce
1. Run a NC-Server with php lower then 7
2. Upgrade to 7.1.5
3. Reload page --> See Error 500 with following Logentry:

### Expected behaviour
Page should reload nice and smooth. :)

### Actual behaviour
I get an Error 500

### Server configuration
Debian
Apache2 

**Database:**
MySQL

**PHP version:**
5.6. --> Error on switching to 7+

**Nextcloud version:** 
12.0.0

**Where did you install Nextcloud from:**
From Nexctloud.com

**List of activated apps:**
Activity
Auditing / Logging
Clllaborative tags
Comments
Deleted files
Federation
Filesharing
First run wizzard
Gallery
Log Reader
Monitorein
Nexcloud Announcement
Notifications
Password Policy
PDF Viewer
Share by Mail
Text editor
Theming
Update Notification
Usage Survey
Version
Video Player
Activities for shared file downloads
Bookmarks
Brute Force Settings
Calendar
Contacts
Notizen
Tasks

**Nextcloud configuration:**
CONFIG: <?php
$CONFIG = array (
  'instanceid' => 'MYID',
  'passwordsalt' => 'MYSALTHERE',
  'trusted_domains' => 
  array (
    0 => 'MYSERVERDOMAIN.DE',
  ),
  'datadirectory' => '/users/MYUSERNAME/MYSERVERDOMAIN.DE/data',
  'dbtype' => 'mysql',
  'version' => '12.0.0.29',
  'dbname' => 'MYDBNAME',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'MYDBUSER',
  'dbpassword' => 'MYDBPASSWD',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'secret' => 'MYSECRET',
  'forceSSLforSubdomains' => true,
  'loglevel' => 0,
  'trashbin_retention_obligation' => 'auto',
  'overwrite.cli.url' => 'https://MYSERVERDOMAIN.DE',
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
Firefox / Chrome

Hopefully I did not forget anything. Please let me know, what I can do.
Thanks.
JamFX

**Comment by creopard** [comment]
Although it won't help you much, but NC 12.0 runs here flawlessly using PHP 7.1.5. 
Did you do an upgrade from a former version or is it a new installation?
You can also try messing around with the .htaccess file as it contains specific sections for PHP5 and PHP7.

**Comment by juliushaertl** [comment]
@jamfx Can you provide the log files of your Nextcloud and web server?

**Comment by creopard** [comment]
Also have a look at #5058

**Comment by jamfx** [comment]
Hi everybody, thanks for your patients
@creopard Thanks for the info :)
@juliushaertl 
There you go:
Webserver-LOG:
[Fri May 26 14:23:58.830255 2017] [fcgid:warn] [pid 8045:tid 2892950336] [client IPADRESS:41911] mod_fcgid: stderr: PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory in /users/MYUSERNAME/MYSERVER/lib/private/DB/Connection.php:61
[Fri May 26 14:23:58.830262 2017] [fcgid:warn] [pid 8045:tid 2892950336] [client IPADRESS:41911] mod_fcgid: stderr: Stack trace:
[Fri May 26 14:23:58.830267 2017] [fcgid:warn] [pid 8045:tid 2892950336] [client IPADRESS:41911] mod_fcgid: stderr: #0 /users/MYUSERNAME/MYSERVER/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()
[Fri May 26 14:23:58.830273 2017] [fcgid:warn] [pid 8045:tid 2892950336] [client IPADRESS:41911] mod_fcgid: stderr: #1 /users/MYUSERNAME/MYSERVER/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()
[Fri May 26 14:23:58.830279 2017] [fcgid:warn] [pid 8045:tid 2892950336] [client IPADRESS:41911] mod_fcgid: stderr: #2 /users/MYUSERNAME/MYSERVER/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()
[Fri May 26 14:23:58.830285 2017] [fcgid:warn] [pid 8045:tid 2892950336] [client IPADRESS:41911] mod_fcgid: stderr: #3 /users/MYUSERNAME/MYSERVER/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()
[Fri May 26 14:23:58.830291 2017] [fcgid:warn] [pid 8045:tid 2892950336] [client IPADRESS:41911] mod_fcgid: stderr: #4 /users/MYUSERNAME/MYSERVER/lib/private/DB/Connection.php(148): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)
[Fri May 26 14:23:58.830297 2017] [fcgid:warn] [pid 8045:tid 2892950336] [client IPADRESS:41911] mod_fcgid: stderr: #5 /users/MYUSERNAME/MYSERVER/3rdparty/do in /users/MYUSERNAME/MYSERVER/lib/private/DB/Connection.php on line 61
[Fri May 26 14:24:30.818422 2017] [fcgid:warn] [pid 8046:tid 2892950336] [client IPADRESS:41912] mod_fcgid: stderr: PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory in /users/MYUSERNAME/MYSERVER/lib/private/DB/Connection.php:61
[Fri May 26 14:24:30.818464 2017] [fcgid:warn] [pid 8046:tid 2892950336] [client IPADRESS:41912] mod_fcgid: stderr: Stack trace:
[Fri May 26 14:24:30.818471 2017] [fcgid:warn] [pid 8046:tid 2892950336] [client IPADRESS:41912] mod_fcgid: stderr: #0 /users/MYUSERNAME/MYSERVER/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()
[Fri May 26 14:24:30.818478 2017] [fcgid:warn] [pid 8046:tid 2892950336] [client IPADRESS:41912] mod_fcgid: stderr: #1 /users/MYUSERNAME/MYSERVER/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()
[Fri May 26 14:24:30.818509 2017] [fcgid:warn] [pid 8046:tid 2892950336] [client IPADRESS:41912] mod_fcgid: stderr: #2 /users/MYUSERNAME/MYSERVER/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()
[Fri May 26 14:24:30.818517 2017] [fcgid:warn] [pid 8046:tid 2892950336] [client IPADRESS:41912] mod_fcgid: stderr: #3 /users/MYUSERNAME/MYSERVER/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()
[Fri May 26 14:24:30.818523 2017] [fcgid:warn] [pid 8046:tid 2892950336] [client IPADRESS:41912] mod_fcgid: stderr: #4 /users/MYUSERNAME/MYSERVER/lib/private/DB/Connection.php(148): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)
[Fri May 26 14:24:30.818529 2017] [fcgid:warn] [pid 8046:tid 2892950336] [client IPADRESS:41912] mod_fcgid: stderr: #5 /users/MYUSERNAME/MYSERVER/3rdparty/do in /users/MYUSERNAME/MYSERVER/lib/private/DB/Connection.php on line 61
[Fri May 26 14:24:30.818535 2017] [fcgid:warn] [pid 8046:tid 2892950336] [client IPADRESS:41912] mod_fcgid: stderr: PHP Fatal error:  Uncaught Doctrine\\DBAL\\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory in /users/MYUSERNAME/MYSERVER/lib/private/DB/Connection.php:61
[Fri May 26 14:24:30.818542 2017] [fcgid:warn] [pid 8046:tid 2892950336] [client IPADRESS:41912] mod_fcgid: stderr: Stack trace:
[Fri May 26 14:24:30.818547 2017] [fcgid:warn] [pid 8046:tid 2892950336] [client IPADRESS:41912] mod_fcgid: stderr: #0 /users/MYUSERNAME/MYSERVER/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()
[Fri May 26 14:24:30.818553 2017] [fcgid:warn] [pid 8046:tid 2892950336] [client IPADRESS:41912] mod_fcgid: stderr: #1 /users/MYUSERNAME/MYSERVER/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()
[Fri May 26 14:24:30.818559 2017] [fcgid:warn] [pid 8046:tid 2892950336] [client IPADRESS:41912] mod_fcgid: stderr: #2 /users/MYUSERNAME/MYSERVER/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()
[Fri May 26 14:24:30.818565 2017] [fcgid:warn] [pid 8046:tid 2892950336] [client IPADRESS:41912] mod_fcgid: stderr: #3 /users/MYUSERNAME/MYSERVER/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\\DBAL\\Connection->getDatabasePlatform()
[Fri May 26 14:24:30.818571 2017] [fcgid:warn] [pid 8046:tid 2892950336] [client IPADRESS:41912] mod_fcgid: stderr: #4 /users/MYUSERNAME/MYSERVER/lib/private/DB/Connection.php(148): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)
[Fri May 26 14:24:30.818577 2017] [fcgid:warn] [pid 8046:tid 2892950336] [client IPADRESS:41912] mod_fcgid: stderr: #5 /users/MYUSERNAME/MYSERVER/3rdparty/do in /users/MYUSERNAME/MYSERVER/lib/private/DB/Connection.php on line 61

Nextcloud-Log:
I'm sorry. I can not find any related info at this Timecode. Only some login-Failures from known clients somehow around this time.. 

If it is absolutely necessary I would try to 
a) clear logs
b) switch to PHP 7.1.5
c) read out the logs
d) Switch back to my old PHP-Version
e) post them here :)
I will have to ask the admin to do so. Hopefully you can use this log so far.
JamFX

**Comment by enoch85** [comment]
@jamfx To me this looks like a DB connection error.

Have you installed `php-mysql`?

**Comment by jamfx** [comment]
I use a self compiled PHP 7.1. MySQL support is included. I successfully tested a mysqli connection.

**Comment by jamfx** [comment]
Is there anything I can do to provide more info? Any suggestions about this? 
Thanks 
JamFX

**Comment by creopard** [comment]
You will also require the PHP module "pdo_mysql"

**Comment by jamfx** [comment]
Thank you. This hint lead me to the source of the problem. I have to use "127.0.0.1" instead of "localhost" as db host in my configuration. This seems to be an MySQL PDO issue. See https://stackoverflow.com/questions/1819592/error-when-connecting-to-mysql-using-php-pdo

**Comment by 0E800** [comment]
Thank you jamfx for the clear and to the point fix. 
Im currently hosting 4 different opensource projects on the same server and each domain has been impacted and required some small tweak, after upgrading to php 7.1.x
I must be getting better at my google searches, this link was at the top of my google search
 `nexcloud php 7 500`
