### ISSUE TITLE
Deleted files root direcotry navigation icon change request

### ISSUE THREAD

**Issue by kaksikanaa** [nextcloud/server#5132]
### Steps to reproduce
1. Open files app
2. Go to Deleted Files (this feature must be enabled)
3.  Try to navigate back to files app root directory by clicking the home icon on the  top left corner on the main window .

### Expected behaviour
Most people expected that by clicking the home icon they could navigate back to the Files app root directory.

### Actual behaviour
You are still in the Deleted files root directory. 
It seems to be quite often hard to understand that's not working and you have to click All Files link in further left on the left side window.  If there is a need to keep the link to the Deleted files root directory (when there are whole directories in the Deleted files root directory), would it be more clear to change the icon to Trash bin icon instead of Home icon? Then users have a visual aid to understand where they are  and start looking for another way to find they way back to the Files root directory when needed.

**Nextcloud version:
Every version.

**Comment by nickvergessen** [comment]
It works quite fine here, the logo redirects me to `index.php` which then loads the file list.
The file app icon loads the normal file list.

Please check your browsers console (F12) for any errors that prevent the redirect.

**Comment by kaksikanaa** [comment]
Ok, I've tryed that but now errors on Firefox console. The link for the home button is

https://somedomain.com/not-default-directory/nextcloud/index.php/apps/files?view=trashbin&dir=/

and so it does not change the view to the files root directory.

**Comment by kaksikanaa** [comment]
Please check the attached short video (change .zip -> .mp4 should be virus free)
[console.zip](https://github.com/nextcloud/server/files/1069172/console.zip)
 about this, no errors on the console while trying to click the home icon on the deleted files folder.

**Comment by kaksikanaa** [comment]
Afterwards I've noticed that when switching between app there is this error in the console:
"DevTools failed to parse SourceMap: https://k1.zzzzzzzzzzzzzzzz.com/core/vendor/jquery/dist/jquery.min.map"
Could that be some way related to this=

**Comment by MorrisJobke** [comment]
> Could that be some way related to this?

No - unrelated and only relevant for development.

**Comment by MorrisJobke** [comment]
I also can't reproduce this anymore. Check which apps you have enabled and maybe disable them step by step (at least the 3rdparty apps, that are not shipped in the release tar ball). Maybe one of them is hijacking the item.

If this still is a problem and you have more information we will reopen this ticket.
