### ISSUE TITLE
Comments behaving different with shares on external storage

### ISSUE THREAD

**Issue by reneglauser** [nextcloud/server#5133]
#### First Case
1. Mount some external smb/cifs storages (eA, eB, eC)
2. Give access to eA, eB to all users and eC only for one specific user u1
3. Place comments for files on eA and eB that could be accessed by all users.
4. To see other users comments, users go to their "Activity - Panel / All activities". Unfortunately comments on files are not visible in this view "All activities"
4. The comments are only visible if users go to the specific file-folder, where they can see that there is a new activity on a specific file.

#### Second Case
1. u1 shares the location eC with user u2
2. then again u1 and u2 places comments for files on eC.
3. Those comments are visible as expected in the view "All activities" for both users u1 and u2 without need to go to the specific folder on eC.

### Expected behaviour
all comments should be visible in the view "All activities" independently of the physical location ore the way they are shared with other users.

### Actual behaviour
only comments are visible in locations shared explicitely with a user or group

### Server configuration

**Operating system**: 
Ubuntu 16.0.4

**Web server:**
Apache

**Database:**
postgresql 

**PHP version:**
7.0.18

**Nextcloud version:** (see Nextcloud admin page)
12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgrade from NC 11

**Where did you install Nextcloud from:**
zip-file

**Signing status:**
No errors have been found.

**List of activated apps:**

  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.4
  - files_automatedtagging: 1.2.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - onlyoffice: 1.0.4
  - ownpad: 0.5.9
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - user_saml: 1.3.2
  - workflowengine: 1.2.0

**Nextcloud configuration:**
    "system": {
        "updatechecker": false,
        "instanceid": ".........",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.66",
            "cloud.domain.com"
        ],
        "datadirectory": "\/nextcloud_data",
        "dbtype": "pgsql",
        "version": "12.0.0.29",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "maintenance": false,
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_from_address": "cloud",
        "mail_domain": "domain.com",
        "mail_smtphost": "192.168.0.202",
        "mail_smtpport": "25",
        "theme": "swisslux",
        "ldapUserCleanupInterval": 51,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "overwriteprotocol": "https",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "production",
        "filelocking.enabled": true,
        "filelocking.ttl": 3600,
        "overwrite.cli.url": "https:\/\/cloud.domain.com",
        "activity_expire_days": 365

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ldap

#### LDAP configuration (delete this part if not used)
+-------------------------------+-------------------------------------------------------------------------------+
| Configuration                 |                                                                               |
+-------------------------------+-------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                             |
| hasPagedResultSupport         |                                                                               |
| homeFolderNamingRule          |                                                                               |
| lastJpegPhotoLookup           | 0                                                                             |
| ldapAgentName                 | user@domain.local                                                  |
| ldapAgentPassword             | ***                                                                           |
| ldapAttributesForGroupSearch  | description                                                                   |
| ldapAttributesForUserSearch   | displayName;mail;givenName;sn                                                 |
| ldapBackupHost                |                                                                               |
| ldapBackupPort                |                                                                               |
| ldapBase                      | DC=domain,DC=local                                                          |
| ldapBaseGroups                | OU=DOMAIN Gruppen,DC=domain,DC=local                                      |
| ldapBaseUsers                 | OU=DOMAIN Benutzer,DC=domain,DC=local                                     |
| ldapCacheTTL                  | 600                                                                           |
| ldapConfigurationActive       | 1                                                                             |
| ldapDefaultPPolicyDN          |                                                                               |
| ldapDynamicGroupMemberURL     |                                                                               |
| ldapEmailAttribute            | mail                                                                          |
| ldapExperiencedAdmin          | 0                                                                             |
| ldapExpertUUIDGroupAttr       |                                                                               |
| ldapExpertUUIDUserAttr        |                                                                               |
| ldapExpertUsernameAttr        | sAMAccountName                                                                |
| ldapGidNumber                 | gidNumber                                                                     |
| ldapGroupDisplayName          | description                                                                   |
| ldapGroupFilter               | (&(|(memberOf=CN=owncloud_group,OU=DOMAIN Ressource,DC=domain,DC=local))) |
| ldapGroupFilterGroups         |                                                                               |
| ldapGroupFilterMode           | 1                                                                             |
| ldapGroupFilterObjectclass    | group                                                                         |
| ldapGroupMemberAssocAttr      | member                                                                        |
| ldapHost                      | host.domain.local                                                           |
| ldapIgnoreNamingRules         |                                                                               |
| ldapLoginFilter               | (&(|(objectclass=person))(samaccountname=%uid))                               |
| ldapLoginFilterAttributes     |                                                                               |
| ldapLoginFilterEmail          | 0                                                                             |
| ldapLoginFilterMode           | 0                                                                             |
| ldapLoginFilterUsername       | 1                                                                             |
| ldapNestedGroups              | 1                                                                             |
| ldapOverrideMainServer        |                                                                               |
| ldapPagingSize                | 500                                                                           |
| ldapPort                      | 389                                                                           |
| ldapQuotaAttribute            |                                                                               |
| ldapQuotaDefault              | 1 GB                                                                          |
| ldapTLS                       | 0                                                                             |
| ldapUserDisplayName           | cn                                                                            |
| ldapUserDisplayName2          |                                                                               |
| ldapUserFilter                | (|(objectclass=person))                                                       |
| ldapUserFilterGroups          |                                                                               |
| ldapUserFilterMode            | 1                                                                             |
| ldapUserFilterObjectclass     | person                                                                        |
| ldapUuidGroupAttribute        | auto                                                                          |
| ldapUuidUserAttribute         | auto                                                                          |
| turnOffCertCheck              | 1                                                                             |
| turnOnPasswordChange          | 0                                                                             |
| useMemberOfToDetectMembership | 1                                                                             |
+-------------------------------+-------------------------------------------------------------------------------+

### Client configuration
**Browser:**
Chrome, Firefox

**Operating system:**
WIndows 10

#### Web server error log
no specific logs

**Comment by nickvergessen** [comment]
Is this the same as https://github.com/nextcloud/activity/issues/45 ?

**Comment by MorrisJobke** [comment]
> Is this the same as nextcloud/activity#45 ?

As there was no comment on this, let's assume it and track it over there.
