### ISSUE TITLE
Nextcloud can not handle folder names containing question marks

### ISSUE THREAD

**Issue by markwatney2016** [nextcloud/server#5134]
### Steps to reproduce
1. create a directory (in a shared folder) with a question mark in it's name (e.g. `foo?`)
2. sync -> no problem
3. rename this file in your nextcloud directory on your local computer -> seems to work
4. sync -> fails

### Steps to reproduce
1. create a directory (in a shared folder) with a question mark in it's name (e.g. `foo?`)
2. sync -> no problem
3. try to rename this folder in the web gui -> fails
4. try to sync as another user (with whom these folders are shared) -> fails

### Server configuration

**Operating system**:

Gentoo Base System release 2.2

**Web server:**

Apache

**Database:**

Type: sqlite3
Version: 3.8.10
Size: 14.7 MB

**PHP version:**

PHP 7.0.6

**Nextcloud version:** (see Nextcloud admin page)

12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**

Updated

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocn2ffwx0ask",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.mydomain.at"
        ],
        "datadirectory": "\/kunden\/489031_6020\/webseiten\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/nextcloud.mydomain.at",
        "dbtype": "sqlite3",
        "version": "12.0.0.29",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_from_address": "foo.bar",
        "mail_smtpmode": "php",
        "mail_domain": "protonmail.com"
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

### Client configuration
**Browser:**

Chrome 58

**Operating system:**

Mac OSX 10.12.5

**Comment by nickvergessen** [comment]
Works quite fine here, with mysql. But maybe it's sqlite related.

**Comment by MorrisJobke** [comment]
We fixed the escaping in the web UI in stable12 recently. At least 12.0.2 works totally fine here. Could you retry and if it still happens we will reopen the issue.

Thanks for the report.
