### ISSUE TITLE
Status on OCR

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#5136]
A while back I proposed a plugin that would function like an OCR, scanning documents in a particular directory and pulling various details from set regions that are the same for the documents to be indexed. Last I seen of it was that it was accepted and would be implemented but after that I haven't heard anything so I wanted to see what is the status of that proposed function?

**Comment by flo269** [comment]
Do you mean something like this? https://apps.nextcloud.com/apps/ocr

**Comment by c0fe** [comment]
Maybe I will have to try it out.

**Comment by joshtrichards** [comment]
* https://apps.nextcloud.com/apps/files_fulltextsearch_tesseract
* https://github.com/nextcloud/files_fulltextsearch_tesseract
* https://apps.nextcloud.com/apps/workflow_ocr
* https://github.com/R0Wi-DEV/workflow_ocr
