### ISSUE TITLE
Feature Proposal: Online Document Creation and Signing

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#5139]
I am proposing a feature for Nextcloud server, to support the creation of basic forms and/or support document signing like HelloSign, DocuSign and RightSignature just to name a few paid services. This would be along to create document versions for specific clients out of a template document and have an automatic email sent that can be customized to a specified email address requesting signature.

**Comment by MorrisJobke** [comment]
This should be implemented as a separate app. Please seek for help in the forums in this case: https://help.nextcloud.com/c/feature/app-ideas

Thanks

**Comment by wayneoutthere** [comment]
this is a SUPER great idea! I was just searching online and there is *nothing* out there in the free/open world.  This would be phenomenal as a business owner and realtor. I thank all in advance who might work on this

**Comment by Steven-Harris** [comment]
Sorry to bump and a closed issue but, I really think this should be re-opened. When you take in consideration the other apps in features included in the nextcloud solution I believe this feature would be well received

**Comment by angelo666** [comment]
Yes , that would be a great functionality. Don't close this issue. That's an important functionality in nextcloud.

**Comment by c0fe** [comment]
@MorrisJobke maybe reconsider?

**Comment by kiplingw** [comment]
I could definitely use this. I find DocuSign, HelloSign, and other platforms I have relied on are just awful. This should be implemented as an "app".

**Comment by kikislater** [comment]
Please re open
