### ISSUE TITLE
Shared folders created in NC 11 no longer accessible in NC 12

### ISSUE THREAD

**Issue by fcrespel** [nextcloud/server#5140]
### Steps to reproduce
1. As "User 1", share a folder with a group in Nextcloud 11.0.3
2. Upgrade to Nextcloud 12.0.0
3. As "User 2" (member of the aforementioned group), try to access the shared folder in the Files app.

Note that I did not reproduce from scratch, this is just what I did with my existing installation.
Sharing a folder from Nextcloud 12.0.0 works correctly, only existing shared folders from 11.0.3 (all of them) seem to encounter this issue.

### Expected behaviour
User 2 should see files from the shared folder.

### Actual behaviour
User 2 sees the following error message at the top: "Storage is temporarily not available".

### Server configuration

**Operating system**: openSUSE Leap 42.1

**Web server:** Apache 2.4.25

**Database:** MySQL 5.6.36

**PHP version:** 5.6.30

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 11.0.3

**Where did you install Nextcloud from:** official ZIP file, manually

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
<pre>
Enabled:
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextant: 1.0.8
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - previewgenerator: 1.0.6
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - socialsharing_email: 1.0.1
  - socialsharing_facebook: 1.0.1
  - socialsharing_googleplus: 1.0.1
  - socialsharing_twitter: 1.0.1
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - activity
  - admin_audit
  - circles
  - encryption
  - user_external
</pre>
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
<pre>
{
    "system": {
        "datadirectory": "\/home\/domains\/crespel.me\/apps\/owncloud-data",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "installedat": "1328114342.2546",
        "lastupdatedat": "1335471354.6449",
        "dbname": "crespel-nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "versions": "false",
        "loglevel": "2",
        "instanceid": "50771963173ee",
        "maintenance": false,
        "maxZipInputSize": 268435456,
        "allowZipDownload": true,
        "theme": "",
        "forcessl": false,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcached_server": [
            "localhost",
            11211
        ],
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "trusted_domains": [
            "cloud.crespel.me"
        ],
        "ldapIgnoreNamingRules": false,
        "overwritewebroot": "",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "nextcloud",
        "mail_smtpmode": "php",
        "mail_domain": "crespel.me",
        "trashbin_retention_obligation": "auto",
        "filesystem_check_changes": 1,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "asset-pipeline.enabled": true,
        "overwrite.cli.url": "https:\/\/cloud.crespel.me"
    }
}
</pre>
</details>

**Are you using external storage, if yes which one:** Dropbox but not in this particular case

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
<pre>
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                                                         |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                           |
| hasPagedResultSupport         |                                                                                                                                                             |
| homeFolderNamingRule          |                                                                                                                                                             |
| lastJpegPhotoLookup           | 0                                                                                                                                                           |
| ldapAgentName                 |                                                                                                                                                             |
| ldapAgentPassword             | ***                                                                                                                                                         |
| ldapAttributesForGroupSearch  |                                                                                                                                                             |
| ldapAttributesForUserSearch   |                                                                                                                                                             |
| ldapBackupHost                |                                                                                                                                                             |
| ldapBackupPort                |                                                                                                                                                             |
| ldapBase                      | dc=forge,dc=crespel,dc=me                                                                                                                                   |
| ldapBaseGroups                | ou=groups,dc=forge,dc=crespel,dc=me                                                                                                                         |
| ldapBaseUsers                 | ou=users,dc=forge,dc=crespel,dc=me                                                                                                                          |
| ldapCacheTTL                  | 600                                                                                                                                                         |
| ldapConfigurationActive       | 1                                                                                                                                                           |
| ldapDefaultPPolicyDN          |                                                                                                                                                             |
| ldapDynamicGroupMemberURL     |                                                                                                                                                             |
| ldapEmailAttribute            | mail                                                                                                                                                        |
| ldapExperiencedAdmin          | 0                                                                                                                                                           |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                             |
| ldapExpertUUIDUserAttr        |                                                                                                                                                             |
| ldapExpertUsernameAttr        | uid                                                                                                                                                         |
| ldapGidNumber                 | gidNumber                                                                                                                                                   |
| ldapGroupDisplayName          | cn                                                                                                                                                          |
| ldapGroupFilter               | (|(cn=collegues-cgi)(cn=famille)(cn=friends)(cn=global-admins)(cn=kcommunity)(cn=owncloud-users))                                                           |
| ldapGroupFilterGroups         | collegues-cgi;famille;friends;global-admins;kcommunity;owncloud-users                                                                                       |
| ldapGroupFilterMode           | 0                                                                                                                                                           |
| ldapGroupFilterObjectclass    |                                                                                                                                                             |
| ldapGroupMemberAssocAttr      | member                                                                                                                                                      |
| ldapHost                      | 127.0.0.1                                                                                                                                                   |
| ldapIgnoreNamingRules         |                                                                                                                                                             |
| ldapLoginFilter               | (&(&(|(objectclass=inetOrgPerson))(|(memberof=cn=owncloud-users,ou=groups,dc=forge,dc=crespel,dc=me)))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                                                                                             |
| ldapLoginFilterEmail          | 1                                                                                                                                                           |
| ldapLoginFilterMode           | 0                                                                                                                                                           |
| ldapLoginFilterUsername       | 1                                                                                                                                                           |
| ldapNestedGroups              | 0                                                                                                                                                           |
| ldapOverrideMainServer        | 0                                                                                                                                                           |
| ldapPagingSize                | 500                                                                                                                                                         |
| ldapPort                      | 10389                                                                                                                                                       |
| ldapQuotaAttribute            |                                                                                                                                                             |
| ldapQuotaDefault              |                                                                                                                                                             |
| ldapTLS                       | 0                                                                                                                                                           |
| ldapUserDisplayName           | displayname                                                                                                                                                 |
| ldapUserDisplayName2          |                                                                                                                                                             |
| ldapUserFilter                | (&(|(objectclass=inetOrgPerson))(|(memberof=cn=owncloud-users,ou=groups,dc=forge,dc=crespel,dc=me)))                                                        |
| ldapUserFilterGroups          | owncloud-users                                                                                                                                              |
| ldapUserFilterMode            | 0                                                                                                                                                           |
| ldapUserFilterObjectclass     | inetOrgPerson                                                                                                                                               |
| ldapUuidGroupAttribute        | auto                                                                                                                                                        |
| ldapUuidUserAttribute         | auto                                                                                                                                                        |
| turnOffCertCheck              | 0                                                                                                                                                           |
| turnOnPasswordChange          | 0                                                                                                                                                           |
| useMemberOfToDetectMembership | 1                                                                                                                                                           |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
</pre>
</details>

### Client configuration
**Browser:** Firefox 53.0.3

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>
(No error in relevant time frame)
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
<pre>
{"reqId":"Z127IJN5M03oAs834A1G","level":4,"time":"2017-05-26T20:55:37+00:00","remoteAddr":"2001:41d0:8:4695::1","user":"acrespel","app":"webdav","method":"PROPFIND","url":"\/remote.php\/webdav\/2017%20Sicile","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Storage is temporarily not available\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/domains\\\/crespel.me\\\/apps\\\/nextcloud-12.0.0\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(966): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('2017 Sicile')\\n#1 \\\/home\\\/domains\\\/crespel.me\\\/apps\\\/nextcloud-12.0.0\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1665): Sabre\\\\DAV\\\\Server::getPropertiesIteratorForPath('2017 Sicile', Array, 1)\\n#2 \\\/home\\\/domains\\\/crespel.me\\\/apps\\\/nextcloud-12.0.0\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(355): Sabre\\\\DAV\\\\Server->generateMultiStatus(Object(Generator), false)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/home\\\/domains\\\/crespel.me\\\/apps\\\/nextcloud-12.0.0\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/home\\\/domains\\\/crespel.me\\\/apps\\\/nextcloud-12.0.0\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#6 \\\/home\\\/domains\\\/crespel.me\\\/apps\\\/nextcloud-12.0.0\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/home\\\/domains\\\/crespel.me\\\/apps\\\/nextcloud-12.0.0\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(71): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/home\\\/domains\\\/crespel.me\\\/apps\\\/nextcloud-12.0.0\\\/remote.php(162): require_once('\\\/home\\\/domains\\\/c...')\\n#9 {main}\",\"File\":\"\\\/home\\\/domains\\\/crespel.me\\\/apps\\\/nextcloud-12.0.0\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":162,\"User\":\"acrespel\"}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko\/20100101 Firefox\/53.0","version":"12.0.0.29"}
</pre>
</details>

#### Browser log
<details>
<summary>Browser log</summary>
<pre>
Method: PROPFIND
URL: https://cloud.crespel.me/remote.php/webdav/2017 Sicile
Response code: 503 Service Unavailable
Response body:
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\ServiceUnavailable</s:exception>
  <s:message>Storage is temporarily not available</s:message>
</d:error>
</pre>
</details>

**Comment by nickvergessen** [comment]
I think this should be more caused by ldap, then sharing

**Comment by fcrespel** [comment]
After further investigation in the database, shares that no longer work are linked to oc_filecache entries with a storage starting with "local::", while new shares that work are linked to a "home::" storage.

I manually updated all oc_filecache entries pointing to "local::" storage to the "home::" equivalent, and affected users can now access shares again.

**Comment by detm54** [comment]
I discovered a similar issue after upgrading from 11.0.2 to 12.0.

I am not able to upload any file or create new subfolders in shared folders regardless wether I'm the share owner or a sharee. If I unshare the folders, I can upload new files and the subfolders I tried to create earlier are now visible and accessible.

Sometimes I get following error in nextcloud.log: Path '$mypath' is not accessible or present !!!"

**Comment by detm54** [comment]
Btw this only happens with parent folders which have been shared before the upgrade. If I share new folders, everything works fine.

**Comment by MorrisJobke** [comment]
cc @nextcloud/ldap @nextcloud/sharing

**Comment by blizzz** [comment]
Given https://github.com/nextcloud/server/issues/5140#issuecomment-307630639 it sounds more like a faulty transition regarding storages table. @icewind1991

**Comment by ChristophWurst** [comment]
As the version of the software you've reported this for has reached *end of life*, I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen.
