### ISSUE TITLE
occ files:scan should block background scan vice versa

### ISSUE THREAD

**Issue by MichaIng** [nextcloud/server#5148]
### Steps to reproduce
1. `occ files:scan --all`
2. Wait for nextcloud cronjob execution.
3. Check running processes + nextcloud debug log for both files scans to run simultaneously.

### Expected behaviour
Every execution of files scans should block additional execution attempt.

### Actual behaviour
At least the manual `occ files:scan --all` does not block the nextcloud cronjob files scan.

### Server configuration

**Operating system**:
Raspberry Pi DietPi (Raspbian Jessie) up-to-date
Kernel 4.9.30-v7+

**Web server:**
Apache 2.4.10

**Database:**
mariadb 10.0.30

**PHP version:**
5.6.30-0+deb8u1

**Nextcloud version:**
12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
dietpi-software

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - activity: 2.5.2
  - calendar: 1.5.3
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_downloadactivity: 1.1.1
  - files_sharing: 1.4.0
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - gallery: 17.0.0
  - impersonate: 1.0.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ownbackup: 17.5.0
  - ownnote: 1.08
  - previewgenerator: 1.0.6
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - tasks: 0.9.5
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "...",
        ],
        "datadirectory": "\/mnt\/sda\/ncdata",
        "overwrite.cli.url": "http:\/\/...",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "...",
        "trashbin_retention_obligation": "disabled",
        "versions_retention_obligation": "disabled",
        "loglevel": 0,
        "maintenance": false
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
Opera 46.0.2602.0 (PGO)

**Operating system:**
Windows 10 1703

**Comment by MorrisJobke** [comment]
It blocks properly on per file/folder level due to our file locking itself. So this is not a problem anymore.
