### ISSUE TITLE
Detail panel only shows 1 share when there are multiple

### ISSUE THREAD

**Issue by aproposnix** [nextcloud/server#5150]
![selection_043](https://cloud.githubusercontent.com/assets/6204273/26541516/40587280-4456-11e7-81ee-203630132702.png)

### Steps to reproduce
1. Add more than 1 share (I shared with 4 groups)
2. Only 1 of the shares is shown

### Expected behavior
I should see all of the groups I have shared with. 

### Actual behavior
I only see the most recent share. This has caused issues because I couldn't see that I had shared with someone who had restricted rights. If I would have seen all of the shares, it wouldn't have been problematic. 

### Server configuration
**Operating system**: Linux server-us05.server.plus 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64

**Web server:** Apache (apache2handler)

**Database:** mysql 10.1.23

**PHP version:** 5.6.30
Modules loaded: Core, date, ereg, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, ldap, memcache, exif, mcrypt, mysqlnd, mysql, mysqli, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, SimpleXML, soap, sockets, sqlite3, tokenizer, xml, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, mhash, ionCube Loader, Zend Guard Loader, Zend OPcache

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated
**Where did you install Nextcloud from:** 
Zip file

**Signing status:**
<details>
	<summary>Signing status</summary>

```
[]
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - admin_notifications: 1.0.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - deck: 0.1.4
 - drawio: 0.8.8
 - external: 2.0.3
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_accesscontrol: 1.2.4
 - files_automatedtagging: 1.2.2
 - files_downloadactivity: 1.1.1
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - impersonate: 1.0.1
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - rainloop: 4.28.1
 - registration: 0.2.3
 - richdocuments: 1.12.31
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_email: 1.0.1
 - spreed: 2.0.1
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0

Disabled:
 - encryption
 - files_external
 - survey_client
 - user_external
 - user_ldap
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "ocdzwwwgq2hd",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nsa.gov"
    ],
    "datadirectory": "\/home\/hmhazksq\/nextclouddata",
    "overwrite.cli.url": "http:\/\/nsa.gov",
    "dbtype": "mysql",
    "version": "12.0.0.29",
    "dbname": "hmhazksq_next934",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_from_address": "do_not_reply",
    "mail_domain": "nsa.gov",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "mail.nsa.gov",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "loglevel": 3,
    "maintenance": false,
    "updater.release.channel": "production",
    "theme": ""
}
```
</details>

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Operating system:**

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	Insert your webserver log here
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
	Insert your Nextcloud log here
	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
	Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
	```
</details>

**Comment by nickvergessen** [comment]
Is there an JS error in your browsers console?

**Comment by aproposnix** [comment]
In the browser console I see only the following: 

Firefox: 
![selection_049](https://cloud.githubusercontent.com/assets/6204273/26682843/29dd780a-46e2-11e7-9a20-e648b938317d.png)

Chrome: 
![selection_048](https://cloud.githubusercontent.com/assets/6204273/26682853/34d16ab4-46e2-11e7-83a0-764ea774371e.png)

**Comment by MorrisJobke** [comment]
cc @nextcloud/sharing

**Comment by skjnldsv** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Comment by aproposnix** [comment]
I can confirm, that on v16, it works as expected. Thanks everyone.
