### ISSUE TITLE
Versions for delted folder is not being delted

### ISSUE THREAD

**Issue by hchaase** [nextcloud/server#5151]
### Steps to reproduce
1. make a dir with files in it
2. make changes to it
3. delte the folder
4. check via ftp or other. in the versions dir, the versions for the deleted dir is still there

### Expected behaviour
 when deleting a folder form the web UI and deleting form the trash bin, the versions for that should also be deleted

### Actual behaviour
folder is deleted, but the versions are still on the server.

### Server configuration
**Operating system**: Linux linux100.unoeuro.com 2.6.32-673.26.1.lve1.4.27.el6.x86_64 #1 SMP Sun May 7 19:22:54 EDT 2017 x86_64

**Web server:** Apache (litespeed)

**Database:** sqlite3 3.8.10

**PHP version:** 5.6.30
Modules loaded: Core, date, ereg, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gettext, gmp, SPL, iconv, session, intl, json, ldap, mbstring, mcrypt, mssql, standard, mysqlnd, mysqli, mysql, PDO, pdo_dblib, pdo_mysql, PDO_ODBC, pdo_sqlite, Phar, Reflection, imap, SimpleXML, soap, exif, tokenizer, xml, xmlreader, xmlwriter, xsl, zip, litespeed, memcache, redis, imagick, ionCube Loader

**Nextcloud version:** 11.0.3 (stable) - 11.0.3.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
update from owncloud and normal updateds from nextcloud
**Where did you install Nextcloud from:** 

**Signing status:**
<details>
	<summary>Signing status</summary>

```
{
    "core": {
        "INVALID_HASH": {
            "core\/doc\/admin\/_static\/img\/note_pencil.svg": {
                "expected": "78b9df57afe9468145e6e375cd1f61274b269b9c3019726a99e043ae952367acf53cf471cbc5b3dcca2e68367c2c4422d4a9f9a9fdbb11f9b962845ac77857de",
                "current": "97117ce2827cc1b742678b52fc100de1e7d3fdb1adeea04a301c012e7f95b66e10a369c6a83ba89a707c4232b5e31fba3d5e58b0e0d970f22031d0704eebb5a9"
            },
            "core\/doc\/admin\/_static\/img\/warning.svg": {
                "expected": "e8647b47ef1531b8c2fcdd51f76996fe85476467fc694540f3dcf8ce7e7da489e99edae5a158742da71c07dc09ccfaf721f01c1c4bda3f5bae9b711981b71a1b",
                "current": "85687f19cf204716e9b1c608682aa22c045b6f8284a3496db07f13200952491bfea54deee7ef11115c0dedfd87443c7022ef05792892a8a984866752c8ec5726"
            },
            "core\/doc\/admin\/_static\/style.css": {
                "expected": "894b1bea3e2b6bc61824ffebc081339a6caf0b57cda7fa9b9c9a5965e2a165dc177055db176cb535ef465c927b4bc4848802fe3e1b0fb709194b3cb7d2f90f8d",
                "current": "5d9fbe71f0eae36c5a9c50f98733cc9e7a5bc7b2b56e3937c4431cf5e54649667bbe8f5900cdcbfbaa8b1eb8d5476d42a278d210c38110411885ad818e3a963a"
            },
            "core\/fonts\/LICENSE.txt": {
                "expected": "4cc5a12bfe984c0a50bf7943e2d70a948d520ef423677c77629707aace3a95aa378d205de929105d644680679e70ef2449479b360ad44896b75bafed66613272",
                "current": "98f6b79b778f7b0a15415bd750c3a8a097d650511cb4ec8115188e115c47053fe700f578895c097051c9bc3dfb6197c2b13a15de203273e1a3218884f86e90e8"
            },
            "core\/vendor\/jsTimezoneDetect\/jstz.js": {
                "expected": "ece74dd6f5fc9587cf167dd17df51b66f70bd711f445da8d1d21bb1b0570f3c97b25d3ece110b08e2f2b294369d9b775cc169b666840a5b769ba338aa6d73d48",
                "current": "beae737d18aae6e8c5fdfb0bf3389b687ec746e6b334185710cc5b8f45b73b3c57442db541807ab440b55517ef2d138f4c40148abafcb6462481016b617e1f53"
            }
        }
    },
    "files_external": {
        "INVALID_HASH": {
            "3rdparty\/Dropbox\/API.php": {
                "expected": "a6866ef3ceeb26d9d4b2ccc343aeaf626c82f03e279962bc7d761a68e87e5a7916ff0bcf7a350e20889557336ed9c5dd1651cfe513fa04bb8a03cd6d8f9cc484",
                "current": "917eed2c4f6359a4d0b8658a36404c83344b0bf72ccda614dd59f97d099b3d9ef4e86691401c64d3754c3f7e0fa163eab946a25dbc7bc65e1694ffd47a054317"
            }
        }
    }
}
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.4.1
 - comments: 1.1.0
 - dav: 1.1.1
 - external: 1.2
 - federatedfilesharing: 1.1.1
 - federation: 1.1.1
 - files: 1.6.1
 - files_automatedtagging: 1.1.1
 - files_external: 1.1.2
 - files_pdfviewer: 1.0.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - firstrunwizard: 2.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.1
 - keeweb: 0.3.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.0
 - notifications: 1.0.1
 - onlyoffice: 1.0.2
 - ownbackup: 17.3.0
 - password_policy: 1.1.0
 - provisioning_api: 1.1.0
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - survey_client: 0.1.5
 - systemtags: 1.1.3
 - templateeditor: 0.2
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - updatenotification: 1.1.1
 - workflowengine: 1.1.1

Disabled:
 - admin_audit
 - calendar
 - contacts
 - direct_menu
 - encryption
 - files_accesscontrol
 - files_markdown
 - files_retention
 - gpxpod
 - user_external
 - user_ldap
 - user_saml
 - weather
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "ocw06tiwubxz",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "hc-haase.dk"
    ],
    "datadirectory": "\/var\/www\/hc-haase.dk\/public_html\/omnidata\/data",
    "overwrite.cli.url": "http:\/\/hc-haase.dk\/omnidata",
    "dbtype": "sqlite3",
    "version": "11.0.3.2",
    "logtimezone": "UTC",
    "installed": true,
    "theme": "",
    "loglevel": 3,
    "maintenance": false,
    "mail_smtpmode": "sendmail",
    "mail_from_address": "hc",
    "mail_domain": "hc-haase.dk",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OCA\Files_External\Lib\Storage\FTP
    [2] => \OC\Files\Storage\DAV
    [3] => \OCA\Files_External\Lib\Storage\OwnCloud
    [4] => \OCA\Files_External\Lib\Storage\SFTP
    [5] => \OCA\Files_External\Lib\Storage\AmazonS3
    [6] => \OCA\Files_External\Lib\Storage\Dropbox
    [7] => \OCA\Files_External\Lib\Storage\Google
    [8] => \OCA\Files_External\Lib\Storage\Swift
    [9] => \OCA\Files_External\Lib\Storage\SFTP
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko/20100101 Firefox/52.0

**Operating system:**

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	Insert your webserver log here
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
	Insert your Nextcloud log here
	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
	Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
	```
</details>

**Comment by nickvergessen** [comment]
Works fine here.

Can you take a look at the nextcloud.log if that has some errors logged?
