### ISSUE TITLE
Mail template editor missing in default installation

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/server#5152]
Mail template editor is missing in default installation of nextcloud 12.

### Steps to reproduce
1. Install nextcloud 12.0.0

### Expected behaviour
There should be a template editor in the admin settings.

### Actual behaviour
There is no mail template editor. Not available via apps.nextcloud.com .

### Server configuration

**Operating system**: CentOS 7

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.0

**Nextcloud version:** (see Nextcloud admin page) 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** OC 9 -> NC 10 -> NC 11

**Where did you install Nextcloud from:** .tar.bz2-file  from the website

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_antivirus: 1.0.0.0
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - impersonate: 1.0.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - calendar
  - comments
  - contacts
  - encryption
  - federation
  - files_external
  - files_pdfviewer
  - files_trashbin
  - files_versions
  - files_videoplayer
  - firstrunwizard
  - gallery
  - systemtags
  - updatenotification
  - user_external
```
</details>

**Comment by NiTRoeSE** [comment]
I have exactly the same issue, no mail template editor in admin settings.

```
Operating system: CentOS 7

Web server: Apache

Database: MariaDB

PHP version: 7.0

Nextcloud version: (see Nextcloud admin page) 12.0.0

Updated from an older Nextcloud/ownCloud or fresh install: OC 9 -> NC 10 -> NC 11
```

**Comment by elpraga** [comment]
In my case it is missing as well. Have you any clue how to edit the email templates?

**Comment by BornToBeRoot** [comment]
@elpraga  You can download the mail template editor from here (https://github.com/nextcloud/templateeditor) and copy it under /../nextcloud/apps 

Enable it in your app/admin page

Note the version (stable11 or stable12) depends on your NC version.

**Comment by rrosko** [comment]
Unable to ENABLE via app page. It's listed but the enable button is greyed out and only remove is available. No mail editor functionality found on any of the Admin pages

**Comment by Hanisch-IT** [comment]
same as @rrosko

**Comment by MorrisJobke** [comment]
See #5180 - this app is not supported anymore, because we updated the way email templates works. We will update the documentation soon.

**Comment by skerbis** [comment]
And now? How can we change the Templates?

**Comment by daniel-wtd** [comment]
@MorrisJobke And the alternative is?

**Comment by MorrisJobke** [comment]
Use a mail template class to overwrite the key parts https://github.com/nextcloud/server/blob/master/config/config.sample.php#L981

**Comment by skerbis** [comment]
seems not to be an easy way. Do you have an example. It's about text. We want to change the text. 

Now we get Hallo User ... 
We need to have Hallo Herr / Frau User...

**Comment by MorrisJobke** [comment]
@nickvergessen Didn't you had an example blog post?

**Comment by splitt3r** [comment]
https://github.com/nextcloud/templateeditor/issues/23#issuecomment-328175633 this comment is a good point to get started 😁
