### ISSUE TITLE
Invitation e-mail is not send if organizer e-mail contains capital letter

### ISSUE THREAD

**Issue by brunt82** [nextcloud/server#5154]
### Steps to reproduce
1. Configure Outlook 2016 for IMAP and enter a capital letter into e-mail address (e.g. Test1@test.de)
2. Install and configure CalDavSynchronizer to use with Nextcloud (disable the checkbox "Set SCHEDULE-AGENT=CLIENT" in the advanced settings of CalDavSynchronizer).
3. Open a new appointment and click on "Invite participants"
4. Have a look at the (already entered) organizer: it should start with the previous entered capital letter
5. Enter a second participant (e.g. test2@test.de), which is also an Nextcloud user. Be sure to enter only lowercase letters.

### Expected behaviour
Nextcloud should send an invitation e-mail containing the event and add the new event to the calendar of the second user (test2@test.de).

### Actual behaviour
Nextcloud does not send an invitation and the the event cannot be found within the calendar of the second user.

### Additional information

1.  Keep in mind that the expected behavior works as soon as I change the e-mail address within the IMAP settings of Outlook. 
2. When I enter as participant an e-mail address with a capital letter, Nextcloud does not send an invitation e-mail and the event does not appear within the calendar (supposedly because Nextcloud does not know the user?). 

### Server configuration

**Operating system**: Ubuntu 16.04.2 LTS

**Web server:** Apache/2.4.18

**Database:**  sqlite3, Version: 3.11.0

**PHP version:** 7.0.15

**Nextcloud version:** 12.0

**Updated from an older Nextcloud/ownCloud or fresh install:** First install was a 12 beta, which was upgraded to the current version last week.

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - files_external
  - spreed
  - user_external
</details>

**Nextcloud configuration:**
<details>
<summary>Nextcloud configuration</summary>
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud-test.test.de"
        ],
        "datadirectory": "\/nextcloud-data",
        "overwrite.cli.url": "http:\/\/nextcloud-test.test.de",
        "dbtype": "sqlite3",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "127.0.0.1",
        "dbport": "",
        "dbtableprefix": "oc_",
        "instanceid": "och55ujpywqp",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 2,
        "maintenance": false,
        "updater.release.channel": "stable",
        "mail_from_address": "no-reply",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "test.de",
        "theme": ""
    }
}
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration 
<details>
<summary>LDAP config</summary>
+-------------------------------+-----------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                     |
+-------------------------------+-----------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                                                   |
| hasPagedResultSupport         |                                                                                                     |
| homeFolderNamingRule          |                                                                                                     |
| lastJpegPhotoLookup           | 0                                                                                                   |
| ldapAgentName                 | uid=readonly,ou=special-users,dc=test=de                                                       |
| ldapAgentPassword             | ***                                                                                                 |
| ldapAttributesForGroupSearch  |                                                                                                     |
| ldapAttributesForUserSearch   | sn;givenName;uid;mail                                                                               |
| ldapBackupHost                |                                                                                                     |
| ldapBackupPort                |                                                                                                     |
| ldapBase                      | dc=test,dc=de                                                                                     |
| ldapBaseGroups                | ou=groups,dc=test,dc=de                                                                           |
| ldapBaseUsers                 | ou=users,dc=test,dc=de                                                                            |
| ldapCacheTTL                  | 600                                                                                                 |
| ldapConfigurationActive       | 1                                                                                                   |
| ldapDefaultPPolicyDN          |                                                                                                     |
| ldapDynamicGroupMemberURL     |                                                                                                     |
| ldapEmailAttribute            | mail                                                                                                |
| ldapExperiencedAdmin          | 1                                                                                                   |
| ldapExpertUUIDGroupAttr       | cn                                                                                                  |
| ldapExpertUUIDUserAttr        | uid                                                                                                 |
| ldapExpertUsernameAttr        |                                                                                                     |
| ldapGidNumber                 | gidNumber                                                                                           |
| ldapGroupDisplayName          | cn                                                                                                  |
| ldapGroupFilter               | (&(|(objectclass=groupOfUniqueNames))(!(cn=studenten*)))                                            |
| ldapGroupFilterGroups         |                                                                                                     |
| ldapGroupFilterMode           | 0                                                                                                   |
| ldapGroupFilterObjectclass    |                                                                                                     |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                        |
| ldapHost                      | ldaps://idm.test.de                                                                          |
| ldapIgnoreNamingRules         |                                                                                                     |
| ldapLoginFilter               | (&(&(objectclass=inetOrgPerson)(mail=*)(!(mail=*@domain.edu))(!(mail=*@domain2.de)))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                     |
| ldapLoginFilterEmail          | 0                                                                                                   |
| ldapLoginFilterMode           | 0                                                                                                   |
| ldapLoginFilterUsername       | 1                                                                                                   |
| ldapNestedGroups              | 0                                                                                                   |
| ldapOverrideMainServer        |                                                                                                     |
| ldapPagingSize                | 500                                                                                                 |
| ldapPort                      | 636                                                                                                 |
| ldapQuotaAttribute            |                                                                                                     |
| ldapQuotaDefault              |                                                                                                     |
| ldapTLS                       | 0                                                                                                   |
| ldapUserDisplayName           | mail                                                                                                |
| ldapUserDisplayName2          |                                                                                                     |
| ldapUserFilter                | (&(objectclass=inetOrgPerson)(mail=*)(!(mail=*@domain.edu))(!(mail=*@domain2.de)))              |
| ldapUserFilterGroups          |                                                                                                     |
| ldapUserFilterMode            | 0                                                                                                   |
| ldapUserFilterObjectclass     |                                                                                                     |
| ldapUuidGroupAttribute        | auto                                                                                                |
| ldapUuidUserAttribute         | auto                                                                                                |
| turnOffCertCheck              | 0                                                                                                   |
| turnOnPasswordChange          | 0                                                                                                   |
| useMemberOfToDetectMembership | 1                                                                                                   |
+-------------------------------+-----------------------------------------------------------------------------------------------------+
</details>

### Client configuration
**Browser:** no Browser, mail client: Outlook 2016

**Operating system:** Windows 7

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by brunt82** [comment]
I suppose that this behaviour has been applied from Owncloud: https://github.com/owncloud/core/issues/10102

**Comment by nickvergessen** [comment]
I'm not completly sure. It works for me with lower and upper case emails also when I enter the wrong on, it is automatically corrected.
Adding to the calendar of the users also works, so I assume it's an issue with your user backend

**Comment by brunt82** [comment]
"when I enter the wrong on, it is automatically corrected."
Was does this mean? Where? Outlook? Or web app? What was wrong and how it is corrected automatically?

**Comment by nickvergessen** [comment]
A different casing of the email  in the calendar invitation

**Comment by brunt82** [comment]
I'm afraid that we speak about different things - or I described it wrong. :-(

First of all I set a capital letter into the e-mail address of the IMAP settings. See following screenshot (sorry, German only), there are three important fields:
1. "Ihr Name" = display name
2. "E-Mail-Adresse" = e-mail address from which the e-mails will be send
3. "Benutzername" = user login to IMAP
![outlook_settings](https://cloud.githubusercontent.com/assets/26540488/26676588/968e4d4a-46c8-11e7-8481-33a1fdebe0a8.jpg)
To check all fields simultaneously, every field get another capital letter.

When I now open a new event and click on the meeting planer, Outlook already added the current user as organizer. It uses the information from the IMAP settings. See second screenshot:
![meeting_planer](https://cloud.githubusercontent.com/assets/26540488/26676708/31f37198-46c9-11e7-899f-9659bb2b9cec.jpg)
As you can see, it shows the display name ("gRoup..."). But as soon as I right click on it and show the properties, the second message box ("E-Mail-Eigenschaften" = e-mail properties) is displayed. There you can see, which e-mail address is used for the display name. It is the like in the IMAP settings.

When this e-mail address sends a event to another user, NC will not send any e-mail notification. If I change it to lower case, the notification is send successfully.

Because the e-mail address is entered while configuring Outlook, I don't understand how it is automatically corrected....

**Comment by brunt82** [comment]
Another hint: The IMAP-server is connected to the same LDAP. So Outlook is able to login with this user name ("grOup..") without any error... But because of the many components (Outlook > IMAP server > LDAP) it may no significance about the backend.

**Comment by brunt82** [comment]
I ask our LDAP admin. The mail-attribute in our LDAP (= OpenDJ) is set to caseIgnoreIA5Match (as specified here: https://tools.ietf.org/html/rfc4524#section-2.16)

**Comment by brunt82** [comment]
The behavior still exists in NC 12.0.8 as described: As soon as I enter a capital letter into the e-mail address of the account settings of the Outlook user (= the sender address in an appointment), Nextcloud will not notice the new appointment and therefore neither create an invitation email nor display the event in the calender of the recipient(s). 

In NC 13.0.3 the error behavior is still the same (with capital letter in sender address = no email, no calender entry). But if I create the appointment without capital letters in the sender address, NC will NOT display any appointment in the calender of the recipients (the email is sent). <-- because of this new behavior I will have a second look on this version. Anyhow the original error case still exist, therefore it should be reopened.
