### ISSUE TITLE
Feature Request - Disable/Hide "Stay logged in" checkbox

### ISSUE THREAD

**Issue by BornToBeRoot** [nextcloud/server#5156]
I currently hiding the "Stay logged in" checkbox from my users via the custom css-file.

It' would be great if i could disable/hide the checkbox with the config-file, since i don't want my users to stay logged in (Especially when they log in from outside our network).

Maybe there are other users here, for which that might be useful.

**Comment by GitHubUser4234** [comment]
This is a duplicate issue of #1358

**Comment by Wikinaut** [comment]
👍

**Comment by MorrisJobke** [comment]
Duplicate of #1358
