### ISSUE TITLE
Change calendar owner

### ISSUE THREAD

**Issue by brunt82** [nextcloud/server#5158]
Hi,

I could not find any possibility to change the owner of a calendar. Following use case:

User A creates a calendar and shared it with a group B. But as soon as User A leaves the company, the calendar may be lost, because the user is disabled in LDAP and his data will be deleted from Nextcloud.

As administrator I need any kind of possibility to either change the owner of the calendar to another group member or (maybe better) create a calendar which is assigned to a group. I think for the first step it would suffice if the current owner can set a new owner.

(Yes, a possible workaround could be the creation of a group-user, but this would be too much effort.)

Thanks and regards, 
Brunt

**Comment by MariusBluem** [comment]
@georgehrke

**Comment by georgehrke** [comment]
Definitely a legitimate use case. 

@brunt82 would an occ command (command line) be enough for you?

**Comment by brunt82** [comment]
Yes, I think this would help much.

**Comment by tcitworld** [comment]
This would require having the internal uri of the calendar, which can be sometimes different from the display name. Or maybe we could first search display names and suggest the internal uris ?

**Comment by edrush** [comment]
+1

**Comment by brunt82** [comment]
Any updates for this issue?

**Comment by alexboorman** [comment]
+1

**Comment by MorrisJobke** [comment]
Fixed by #5881
