### ISSUE TITLE
Bring back the old way of counting storage

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#5159]
For some time now the storage has been shown as "Unlimited" instead of the actual size. I would like the old way to become the standard again where I could see how much storage I actually had in total.

So instead of:
`Used 376 GB of Unlimited` I would like `Used 376 GB of 1000 GB`

**Comment by MariusBluem** [comment]
Storage should show that, was is configured. But this has to consistent. For example, clients like iOS or Android are never showing unlimited. They are showing the actual quota (filesystem). The WebUI shows "Unlimited" but the quota bar in the background shows something totally different 😬

**Comment by idenkov** [comment]
Just upgraded to version 12.0.0 and I see 1.2 gb of 230gb, and I use well over 100gb for sync. 
Also the admin section shows I don't have the header "X-Frame-Options", and I do.
The upgrade should have been to 11.0.3 - that what was shown in the backend on stable channel, also the latest version on the changelog here - https://nextcloud.com/changelog/

**Comment by enoch85** [comment]
Fixed by https://github.com/nextcloud/server/pull/5305 maybe?

**Comment by MorrisJobke** [comment]
> Fixed by #5305 maybe?

Mostly - for the APIs see #8838 -> thus closing
