### ISSUE TITLE
Spinner on black is low resoulution

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#5161]
Please check this video: https://cloud.techandme.se/s/ErPC7cvzABL8s38

**Nextcloud 12.0.0**

**Comment by ViRPo** [comment]
This looks like this loading animation is anti-aliased for light background
I can recreate spinning animation and export them in high resolution

This would include files:
`core\img\loading.gif
core\img\loading-dark.gif
core\img\loading-small.gif
core\img\loading-small-dark.gif`

I would go for same/similar look but cannot guarantee 100% accuracy unless I am provided with source images, if there are any

**Comment by MorrisJobke** [comment]
Fixed in #5972
