### ISSUE TITLE
Collabora Online Does not work

### ISSUE THREAD

**Issue by jsargent7089** [nextcloud/server#5162]
### Steps to reproduce
1.Try to edit a document

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:

**Web server:

**Database:**

**PHP version:7.0

**Nextcloud version:12.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:new install

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```Internal Server Error
The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

Technical details
Remote Address: 10.20.0.20
Request ID: qieml7JGTaPP3WQFHHDP
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by jsargent7089** [comment]
Error	richdocuments	GuzzleHttp\Exception\RequestException: cURL error 51: SSL: no alternative certificate subject name matches target host name 'onlyoffice.techpit.us'
/var/www/html/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 103: GuzzleHttp\Exception\RequestException wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\RingException))
/var/www/html/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
/var/www/html/3rdparty/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
/var/www/html/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
/var/www/html/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
/var/www/html/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
/var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php - line 165: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
/var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125: GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
/var/www/html/lib/private/Http/Client/Client.php - line 138: GuzzleHttp\Client->get('https //onlyoff...', Array)
/var/www/html/apps/richdocuments/lib/WOPI/DiscoveryManager.php - line 84: OC\Http\Client\Client->get('https //onlyoff...')
/var/www/html/apps/richdocuments/lib/WOPI/Parser.php - line 41: OCA\Richdocuments\WOPI\DiscoveryManager->get()
/var/www/html/apps/richdocuments/lib/TokenManager.php - line 94: OCA\Richdocuments\WOPI\Parser->getUrlSrc('application/vnd...')
/var/www/html/apps/richdocuments/lib/Controller/DocumentController.php - line 108: OCA\Richdocuments\TokenManager->getToken(*** sensitive parameters replaced ***)
[internal function] OCA\Richdocuments\Controller\DocumentController->index('106038')
/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/var/www/html/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Richdocuments\Controller\DocumentController), 'index')
/var/www/html/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Richdocuments\Controller\DocumentController), 'index')
/var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Richdocumen...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/html/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/html/lib/base.php - line 1000: OC\Route\Router->match('/apps/richdocum...')
/var/www/html/index.php - line 40: OC handleRequest()
{main}

**Comment by jsargent7089** [comment]
Error	no app in context	Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "theming.Theming.getLogo" as such route does not exist.
/var/www/html/lib/private/Route/Router.php - line 339: Symfony\Component\Routing\Generator\UrlGenerator->generate('theming.Theming...', Array, 1)
/var/www/html/lib/private/URLGenerator.php - line 70: OC\Route\Router->generate('theming.Theming...', Array)
/var/www/html/apps/theming/lib/ThemingDefaults.php - line 156: OC\URLGenerator->linkToRoute('theming.Theming...')
/var/www/html/lib/public/Defaults.php - line 186: OCA\Theming\ThemingDefaults->getLogo(true)
/var/www/html/core/templates/layout.guest.php - line 45: OCP\Defaults->getLogo()
/var/www/html/lib/private/Template/Base.php - line 176: include('/var/www/html/c...')
/var/www/html/lib/private/Template/Base.php - line 151: OC\Template\Base->load('/var/www/html/c...', NULL)
/var/www/html/lib/private/legacy/template.php - line 202: OC\Template\Base->fetchPage(NULL)
/var/www/html/lib/private/legacy/template.php - line 224: OC_Template->fetchPage()
/var/www/html/lib/private/Template/Base.php - line 132: OC_Template->fetchPage()
/var/www/html/core/templates/403.php - line 7: OC\Template\Base->printPage()
{main}

**Comment by zinks-** [comment]
The first line of your first log post is `Error richdocuments GuzzleHttp\Exception\RequestException: cURL error 51: SSL: no alternative certificate subject name matches target host name 'onlyoffice.techpit.us'`

You need to fix your certificate so that the hostname you use is covered.

**Comment by enoch85** [comment]
@jsargent7089 Are you running Ubuntu 16.04? If yes, then you can use the scripts for an easy install: https://github.com/nextcloud/vm/blob/master/apps/collabora.sh

**Comment by nickvergessen** [comment]
Closing as per above

**Comment by jsargent7089** [comment]
I have fixed all issues. thank you for all your help
