### ISSUE TITLE
Webupload stucks at ~20%

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#5163]
### Steps to reproduce
1. open nextcloud in web browser (chromium)
2. upload a file

### Expected behaviour
- upload should work fine

### Actual behaviour
- see upload stuck at ~20%

No errors in any log file.

### Server configuration

**Operating system**:

**Web server:**
Apache

**Database:**

**PHP version:**
php7

**Nextcloud version:** (see Nextcloud admin page)
NC12

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment]
Works fine here. Anything in your browser console? Does the upload still work in the end? Which file size are you trying?

**Comment by tobiasKaminsky** [comment]
Sorry for the late reply, but I was on vacation with such an awful and buggy internet :/

Here are my tests with a reliable internet connection: 
Chromium stucks at ~20%
Firefox can upload the whole file, but then the file vanishes and I see 
```
{"reqId":"vIodsOUmfFRPGcMGKZrg","level":4,"time":"2017-06-10T06:16:31+00:00","remoteAddr":"92.192.50.150","user":"tobi","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/folder/file.pdf","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 \\\"file.pdf\\\" is locked\",\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\FileLocked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(151): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #21)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1095): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('FILE...', Resource id #21)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('26. Mai - 09. J...', Resource id #21, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(71): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/nextcl...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":176,\"User\":\"tobi\"}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"12.0.0.29"}
```

**Comment by tobiasKaminsky** [comment]
@nickvergessen anything I can help you with debugging it?

**Comment by nickvergessen** [comment]
I dont have a lot JS expericence, so not sure I can be helpful debugging this.

But IIRC the upload timing was touched recently, correct @nextcloud/javascript ?

**Comment by MorrisJobke** [comment]
> But IIRC the upload timing was touched recently, correct @nextcloud/javascript ?

Correct. @tobiasKaminsky Is this reproducible on different NC instances or only in one? Any specific file I can test this with?

**Comment by tobiasKaminsky** [comment]
It seems to be only my instance and only with chromium...

**Comment by MorrisJobke** [comment]
@tobiasKamnisly Could you send me some credentials so that I can test this?

**Comment by MorrisJobke** [comment]
@tobiasKamnisky Could you send me some credentials so that I can test this?

**Comment by MorrisJobke** [comment]
Mmmh ... could you turn of the HTTP2 support. On Safari I get a "HTTP/2.0 423" error and Chrome needs to be completely restarted after this happens. I guess this is a setup issue with your Apache.

**Comment by MorrisJobke** [comment]
After disabling HTTP 2 it works again. That means it's a configuration problem with this specific setup. I will have a look at this together with Tobias during our next meeting. Closing this one here.
