### ISSUE TITLE
nextcloud 12 changing emails on users?

### ISSUE THREAD

**Issue by alexweirig** [nextcloud/server#5169]
After we installed nextcloud 12 in test (upgrade from 11.0.3) some users complain about getting the following emails:
Email address changed for Nadine Gaasch
Owncloud Admin changed your email address on https://nextcloud.technolink.lu:8443/. If you did not request this, please contact an administrator.
The new email address is muriel.achour@technolink.lu

### Steps to reproduce
1. installed nc 12 upgrade from 11.0.3
2. users complain

### Expected behaviour
emails should not be changed

### Actual behaviour
not sure what is happening ... emails are not changed in LDAP

same configuration as in #5168

**Comment by nickvergessen** [comment]
Fix is in https://github.com/nextcloud/server/pull/5126/files
And will come with 12.0.1
