### ISSUE TITLE
Heavy CPU-load with video-calls

### ISSUE THREAD

**Issue by Hoerli1337** [nextcloud/server#5171]
### Steps to reproduce
If i use the new videocall-function with 3 guys, the cpu is heavily utilized.
I run a Linux Ubuntu 16 Server with Plesk Onyx. I use nginx for the Cloud.

The CPU is at 100% (of 400%) if we send 2 Videosstreams and he use PHP-FPM with Apache2 and not nginx.

Is this a problem of NextCloud or Plesk?
Does the plugin only forward the streams or are they encoded directly on the server?

### Expected behaviour
Use nginx and not apache2 :)

### Server configuration

**Operating system:** Linux Ubuntu 16.04 LTS 64bit

**Web server:** Apache2 + nginx

**Database:** MySQL

**PHP version:** 7.1.5

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from NextCloud 11

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
**No errors have been found.**
```
</details>

**Comment by nickvergessen** [comment]
Which video calls app? The one with the go server, or the php only version?

**Comment by Hoerli1337** [comment]
I use the php only.

**Comment by MorrisJobke** [comment]
This is an issue with the video calls app: https://github.com/nextcloud/spreed We are aware of this and try to get it resolved. May I ask you to report it in the apps bug tracker? https://github.com/nextcloud/spreed/issues

Thanks
