### ISSUE TITLE
ArgumentCountError: Too few arguments to function OC\Files\Storage\Wrapper\Wrapper::file_put_contents() with notes app

### ISSUE THREAD

**Issue by midluk** [nextcloud/server#5176]
I recently installed the notes app from nextcloud app store and when new notes are created, they are not displayed directly in the notes app and a server error is written to the log file.
As the error is produced in some core file of nextcloud (after a few function calls), I choose to report it here, but the root cause might be the notes app doing something not foreseen in the API (apparently it tries to create an empty file with NULL passed as content).

### Steps to reproduce
1. Install Notes app from nextcloud app store
2. go to "Notes app"
3. click "New note"

### Expected behaviour
- A new note should be created and displayed, and be editable
- No error should be put into the log file

### Actual behaviour
- An empty note is created, but not displayed until the app is reloaded
- A error in app "index" is logged:
"ArgumentCountError: Too few arguments to function OC\Files\Storage\Wrapper\Wrapper::file_put_contents(), 1 passed in /var/www/nextcloud/lib/private/Files/View.php on line 1132 and exactly 2 expected"
<details>
<summary>backtrace</summary>

```
    /var/www/nextcloud/lib/private/Files/View.php - line 1132: OC\Files\Storage\Wrapper\Wrapper->file_put_contents('files/Notes/New...')
    /var/www/nextcloud/lib/private/Files/View.php - line 679: OC\Files\View->basicOperation('file_put_conten...', '/lukas/files/No...', Array, NULL)
    /var/www/nextcloud/lib/private/Files/Node/File.php - line 64: OC\Files\View->file_put_contents('/lukas/files/No...', NULL)
    /var/www/nextcloud/apps/notes/service/notesservice.php - line 152: OC\Files\Node\File->putContent(NULL)
    /var/www/nextcloud/apps/notes/controller/notescontroller.php - line 88: OCA\Notes\Service\NotesService->update(189, NULL, 'lukas')
    [internal function] OCA\Notes\Controller\NotesController->create(NULL)
    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Notes\Controller\NotesController), 'create')
    /var/www/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Notes\Controller\NotesController), 'create')
    /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Notes\\Contr...', 'create', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
    [internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
    /var/www/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
    /var/www/nextcloud/lib/base.php - line 1000: OC\Route\Router->match('/apps/notes/not...')
    /var/www/nextcloud/index.php - line 40: OC handleRequest()
    {main}
```
</details>

### Server configuration

**Operating system**:
Centos 7

**Web server:**
apache 2.4.6

**Database:**
Mariadb 5.5.52

**PHP version:**
7.1.4

**Nextcloud version:** (see Nextcloud admin page)
12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install of 12.0.0

**Where did you install Nextcloud from:**
official tar.bz2

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.2.0
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```
</details>

**Are you using external storage, if yes which one:**
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** 
no

### Client configuration
**Browser:**
Firefox 53.0.2
**Operating system:**
Fedora 25

**Comment by nickvergessen** [comment]
Please report the issue to the notes app team:
https://github.com/nextcloud/notes/
