### ISSUE TITLE
NC12.0 NL missing at profile page: phone, address, website, twitter

### ISSUE THREAD

**Issue by JK74** [nextcloud/server#5178]
[nextcloud.txt](https://github.com/nextcloud/server/files/1039343/nextcloud.txt)
NC12.0 upgraded from 11.03 Dutch language.
ubuntu 16.04 with apache

After another upgrade from 11.03 to 12.0 I see that profile page is missing the fields for Phone Number, Address, Website & Twitter.

see picture attached. How do I get this recovered?
edit1: nextcloud.log file can be shared in private on request.
thnx, Jeroen
![nc12_profile_page_isues](https://cloud.githubusercontent.com/assets/17946255/26589442/5f49c09c-4558-11e7-8a18-76c664d80f5c.png)

**Comment by nickvergessen** [comment]
The strings were not translated on our translation platform on the release day. They are now, so they will be dutch again in 12.0.1

**Comment by JK74** [comment]
@nickvergessen I'm running now on 12.0.2 and I see it on my admin account but my 'normal' user account still does not have the fields. How could this happen?

**Comment by JK74** [comment]
@nickvergessen can we re-open or should I resubmit a new ticket? thnx!

**Comment by nickvergessen** [comment]
> ![bildschirmfoto vom 2017-09-06 10-52-34](https://user-images.githubusercontent.com/213943/30102985-92c493a2-92f1-11e7-98c4-1f2e07f360e9.png)

Works pretty fine here.

If this is still an issue, please post a new complete issue and fill out the issue template.

**Comment by JK74** [comment]
@nickvergessen I will post a new issue but I like to keep it open then until its really resolved? The last time it was closed before a fix was in place (v12) and when I tested it inside V12 it was showing like above aka still broken. thnx!
