### ISSUE TITLE
Adding self to CSP fails

### ISSUE THREAD

**Issue by sualko** [nextcloud/server#5179]
### Steps to reproduce
Put the following into your `app.php`:
```
$policy = new OCP\AppFramework\Http\ContentSecurityPolicy ();
$policy->addAllowedScriptDomain('\'self\'');
\OC::$server->getContentSecurityPolicyManager()->addDefaultPolicy($policy);
```

### Expected behaviour
`'self'` in the csp header

### Actual behaviour
No `'self'` (e.g. on all shares).

### Server configuration

**PHP version:** 7.0.19

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

### Dirty fix
If you add `'self' ` (please note the following space `'self'_`) everything works as expected.

cc @LukasReschke 
ref sualko/owncloud_piwik#30

**Comment by ChristophWurst** [comment]
Is this still an issue? Have you tried changing the CSP directly on the response object? I use something similar in an [app of mine](https://github.com/ChristophWurst/nextcloud_sentry/blob/7ba53cd6f114b9489ae662818222227757697546/lib/AppInfo/Application.php#L94-L106) and it just works fine :man_shrugging:

**Comment by rullzer** [comment]
I guess this is because we unset self when we use the nonce.

**Comment by rullzer** [comment]
Yep verified that that is it.
Please set the proper nonce and it should all work.
