### ISSUE TITLE
e-mail template change not available any longer?

### ISSUE THREAD

**Issue by JK74** [nextcloud/server#5180]
[nextcloud.txt](https://github.com/nextcloud/server/files/1039342/nextcloud.txt)

NC12.0 upgraded from 11.03 Dutch language.
ubuntu 16.04 with apache

With NC11.03 we could edit the e-mail template but it was not working for dutch localization. Now with NC12 it seems we have no way at all to customize e-mail templates.
How can we edit email templates for new invites? As example to mention what the server URL is or where additional help can be gathered or where an customized documentation for install can be found.

how should or could we changed e-mail templates (for Dutch language) in NC12.

edit: according to admin guide p92 there should be an section for e-mail template but its not on my setup:
_In addition to providing the email templates, this feature enables you to apply any preconfigured themes to the email.
To modify an email template to users:
1. Access the Admin page.
2. Scroll to the Mail templates section.
3. Select a template from the drop-down menu.
4. Make any desired modifications to the template_

edit2: nextcloud.log file can be shared in private on request.
Thnx & cheers, jeroen

**Comment by nickvergessen** [comment]
cc @MorrisJobke for the new IEmailTemplate stuff

**Comment by hubertbanas** [comment]
Is there any updates on this issue?

**Comment by Hanisch-IT** [comment]
im also interested in this, i have no idea how i can customize the email templates... Thedeveloper manual is not right https://docs.nextcloud.com/server/12/developer_manual/core/theming.html. There is no email templating section in the admin page. Im useing 12.0.1.

**Comment by JK74** [comment]
@nickvergessen Is there any update available?

**Comment by abnewkirk** [comment]
This seems like a bug based off documentation, and I'd certainly like this feature. I do see that this was converted to an enhancement. Where is this feature on the roadmap?

**Comment by JK74** [comment]
In short: especially on the nextcloud invitation e-mail I really need an 1 or 2 lines of text added to the invite to make it more meaningfull and customized for my audience; how can I do that today now that the e-mail template is gone ? and I can't change jason file easily to get lines added.... @nickvergessen @tflidd

**Comment by herrfeuer** [comment]
I support that Issue. Please add at least 2 Lines to to the Documentation where to start and which Files to edit.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/templateeditor/issues/23 is a good read and should give hints where to start

**Comment by JK74** [comment]
@nickvergessen  I'm now a bit confused as this issue is now closed but pointing to another thread #5180 however that thread is now pointing as well back to this one. The circle is round but still no fix? Or a future enhancement? Or do we get 2 more lines in the admin page that can be included in the invite e-mail for new users? Please advise as this is confusing. thanks!
