### ISSUE TITLE
No update shown

### ISSUE THREAD

**Issue by rugk** [nextcloud/server#5188]
### Steps to reproduce
1. In v11.0.2 go to the update menu and have "stable" selected.

### Expected behaviour
Show me "NextCloud 12.0 is available".

### Actual behaviour
Instead it shows: "This version is up to date."
And it also shows that the check is up-to-date.

**Comment by patschi** [comment]
NC12 is currently in staged rollout to 15% of the users. So it may take some time until you receive the update aswell. You may [manually upgrade](https://docs.nextcloud.com/server/12/admin_manual/maintenance/manual_upgrade.html) your installation, but I'd recommend to just wait and let the updater finally do the work.

**Comment by rugk** [comment]
Okay.
