### ISSUE TITLE
Favicon color is a bit off?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#5193]
I noticed it on my bookmarks, since 12 the app icon is used, but the blue tone is wrong. It is `#5980C2` while the theme is `#0182C9`
> ![bildschirmfoto vom 2017-05-31 12-44-17](https://cloud.githubusercontent.com/assets/213943/26628715/6f19fc38-45ff-11e7-9731-836ccdc45d32.png)

@juliushaertl

**Comment by juliushaertl** [comment]
Can you check what color the icon has if you download it manually from index.php/apps/theming/icon

Looks more like a browser caching issue to me.

**Comment by juliushaertl** [comment]
I did some testing and it seems that this is caused by the browser resizing the icon to 16x16px. The theming app should create a favicon file in ico format that contains various sizes. I'll look into that.

**Comment by jancborchardt** [comment]
For the record, the correct Nextcloud color is `#0082c9` :) (not 01…)
