### ISSUE TITLE
Neither the web GUI or file sync works after upgrade from 11 to 12 Nextcloud

### ISSUE THREAD

**Issue by walec51** [nextcloud/server#5194]
Logs from file sync:

Error	remote	TypeError: Argument 1 passed to OCA\Activity\FilesHooks::generateRemoteActivity() must be of the type array, null given, called in /www/walczak_files/files-www/apps/activity/lib/FilesHooks.php on line 198	2017-05-31T12:55:01+0200
Error	PHP	Undefined index: ownerPath at /www/walczak_files/files-www/apps/activity/lib/FilesHooks.php#198	2017-05-31T12:55:01+0200
Error	PHP	Undefined index: remotes at /www/walczak_files/files-www/apps/activity/lib/FilesHooks.php#198	2017-05-31T12:55:01+0200
Error	no app in context	Exception:	2017-05-31T12:55:01+0200
Error	PHP	filesize(): stat failed for /www/walczak_files/data/adam/files/produkcja/Podsumowanie suszenia i obr�bki.xlsx at /www/walczak_files/files-www/lib/private/Files/Storage/Local.php#161

Logs from JavaScript console:

client.js?v=a173b97…-2:270 Uncaught (in promise) URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at Client._parseFileInfo (client.js?v=a173b97…-2:270)
    at client.js?v=a173b97…-2:389
    at Function._.map._.collect (core.js?v=a173b97…-2:185)
    at Client._parseResult (client.js?v=a173b97…-2:388)
    at client.js?v=a173b97…-2:450
    at <anonymous>

Both seam to fail on file path with characters specific to the polish language.

**Comment by nickvergessen** [comment]
Can you post the character which causes the problem here?

**Comment by walec51** [comment]
ó or ż

**Comment by walec51** [comment]
Did you manage to reproduce the problem?

**Comment by nickvergessen** [comment]
No, works fine here.

**Comment by MorrisJobke** [comment]
Looks like a problem with the database encoding or filesystem. DO you have information regarding that? (Another reason to fill out the issue template 😉 )
