### ISSUE TITLE
Download Administrator Manual in PDF

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#5196]
Hi, 
what is the URL of the current Administrator Manual (version 12) in PDF ?

regards, hitam4450

**Comment by patschi** [comment]
First hit with Google when searching for "nextcloud administrator manual pdf": https://docs.nextcloud.com

**Comment by hitam4450** [comment]
Hi, this URL i know already from another issue! Its the **USER** and not The **ADMINISTRATOR** Manual of server 12  ! being legible definitely helps in life !

**Comment by patschi** [comment]
Sorry, you're right, my fault. I copied the wrong link, just watch one line below "User Manual" and you may find the admin manual pointing to: https://docs.nextcloud.org/server/12/Nextcloud_Server_Administration_Manual.pdf
