### ISSUE TITLE
Download Administrator Manual in PDF - II

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#5197]
Hi, after being redirected to download the User Manual of Server Version 12 a **second time**(see: https://github.com/nextcloud/server/issues/5196), i asked Master Google about the PDF Administrator Manual of Server 12 ,received the following links for the obsolete versions 9 & 11a, dated May, 31 2017  ! Great Job to publish an obsolte manual(s) at a almost current date! But not the URL of Version 12!

Could someone present a URL the download the CURRENT (VERSION12) ADMINISTRATOR Manual in PDF ?

Many, many thanks in advance!
regards, hiatm4450

![nc_9_manual](https://cloud.githubusercontent.com/assets/9738727/26638773/4dff296e-4623-11e7-8dde-197c3a726a46.png)

![nc_admin11](https://cloud.githubusercontent.com/assets/9738727/26638903/a769354e-4623-11e7-9a87-2e1d512e964a.png)

**Comment by MariusBluem** [comment]
URL to admin manual: https://docs.nextcloud.com/server/12/Nextcloud_Server_Administration_Manual.pdf

**Comment by hitam4450** [comment]
Thanks for the URL!
regards, hitam4450
