### ISSUE TITLE
External storage connection is not SSL encrypted by default

### ISSUE THREAD

**Issue by M4xAmmo** [nextcloud/server#5199]
### Steps to reproduce
1. Create an External storage with SSL available (eg. FTP).

### Expected behaviour
Encryption (SSL in this case) schould be preselected.

### Actual behaviour
Encryption (SSL in this case) schould is not preselected.

**Comment by szaimen** [comment]
Are you talking about the button here?
![image](https://user-images.githubusercontent.com/42591237/121339658-fdd92380-c91e-11eb-9b3a-c3c705e71568.png)
I think it is already good enough visible so that you don't miss it.

**Comment by M4xAmmo** [comment]
> Are you talking about the button here?
> ![image](https://user-images.githubusercontent.com/42591237/121339658-fdd92380-c91e-11eb-9b3a-c3c705e71568.png)
> I think it is already good enough visible so that you don't miss it.

Tanks for answering, I completely forgot, that i opened this in the first place. 

Yes, this is the button I'm talking about. My point is not the visibility, but the fact that the default value is the insecure way of doing it. I'd prefer unencrypted not to be the default selection.

**Comment by szaimen** [comment]
@storage
