### ISSUE TITLE
Get own documentation up and running

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#52]

**Comment by mar1u5** [comment]
Should we simply fork `owncloud/documentation`?

**Comment by LukasReschke** [comment]
Yes. But also the screenshots needs to be updated as well as "ownCloud" replaced through "Nextcloud" in the user-facing text. Additionally remove all Enterprise Apps documentation parts.

Any help utmostly welcome on that one… Otherwise we likely won't have any documentation in our 9.0 release and only for 10.0 🙈

**Comment by LukasReschke** [comment]
And if you fork please just pull the whole repository locally and then create a new repo on GitHub and push all branches. :-)

**Comment by mar1u5** [comment]
Like that: https://github.com/nextcloud/documentation 😉 ...If yes, i will start with rebranding.
Screenshots repository is already up, and we only need to fill it with new screenshots :)

**Comment by LukasReschke** [comment]
> Like that: https://github.com/nextcloud/documentation 😉 ...If yes, i will start with rebranding.
> Screenshots repository is already up (but not forked!), and we only need to fill it with new screenshots :)

🚀 ⭐ ❤️ 🎉  - Awesome stuff! If you could go over the stable9 repo this would be super awesome. We might even have proper documentation then for the 9 release 🎉

**Comment by mar1u5** [comment]
Should we remove the old branches (8,7,6, ...) 😕

**Comment by mar1u5** [comment]
**How to handle the parts where ownCloud 8 is mentioned?**

- Remove
- Call it ownCloud 
- Call it Nextcloud (which would be strange for 8.2 😜)#

**Which version numbers should i use?**

- 9 instead of 9.0
- 10 instead of 9.1

**Old branches**

Should we remove stable7, stable8, ... (because they are simply not existing 😉)

**Documentation of Enterprise-stuff**

Should we completely remove it, or should we leave it in, because we rewrite these features?

cc @LukasReschke

**Comment by WebSpider** [comment]
Let me know if help is needed, i have no problem helping, but two persons working on the same thing is a waste of time :)

**Comment by LukasReschke** [comment]
On my mobile atm, so please excuse my short response :)

> Parts where oC 8 is mentioned

Remove.

> Version numbers

9 instead of 9.x and master will be 10

> Old branches

Kill it with :fire: 

> Enterprise stuff

Remove. The rewrites have the same functionality but another (better, see for example files_drop) user interface. Not having them closed allows us to integrate the studf way better.

> Master or stable9

At the moment we are aiming for getting a Nc 9 out very soon, likely next week already. Master is still 2-3 months ago, so in my opinion we should first work on Nc 9 docs as that is what users will see.

**Comment by mar1u5** [comment]
working on that: https://github.com/nextcloud/documentation/tree/this-is-nextcloud

**Comment by LukasReschke** [comment]
@karlitschek Seems like we might even get some decent documentation earlier than expected then 😄 

Any chance you can configure `docs.nextcloud.org` or so to point to .138? :-)

**Comment by karlitschek** [comment]
done :-)

**Comment by mar1u5** [comment]
Should it not be "doc.nextcloud.com" ... already changed to that everywhere 😭 @karlitschek

**Comment by karlitschek** [comment]
Yes. it should. Because of a super stupid limitation of the current dns provider i can't do that. Let me think about an option

**Comment by karlitschek** [comment]
ok. i looked again for options and there is unfortunately nothing we can do for now. In about one month we move to a different provider which removed this limitation. Unfortunately we can't do before that.

**Comment by mar1u5** [comment]
Then ... We wait :wink: ... And we stay at the adresses i've mentioned above.
Please Review the user_manual :wink:

**Comment by MorrisJobke** [comment]
Documentation related stuff should be handled in https://github.com/nextcloud/documentation/ -> closing this here

**Comment by MorrisJobke** [comment]
Thanks a lot @mar1u5
