### ISSUE TITLE
We always get the app description of the latest version

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#5202]
1. Install Nextcloud 11
2. Go to the app list
3. Go to multimedia
4. See this in the spreed apps description: 
![before](https://cloud.githubusercontent.com/assets/45821/26652192/58e8c7dc-464f-11e7-8283-d9f4a9088105.png)
5. Enable app
6. Now see description: 
![before2](https://cloud.githubusercontent.com/assets/45821/26652220/71050f06-464f-11e7-9576-46dd70942331.png)

I can't really check if this happens on master. But I suspect the issue to still be there.

**Comment by MorrisJobke** [comment]
The App Store only provides one description as far as I know - cc @BernhardPosselt 

Nothing we can do here.

**Comment by BernhardPosselt** [comment]
Exposing the description per app version really blows up the json response size even if it wasn't changed, therefore it's only persisted once. Unsure if gzip solved this issue. Based on your needs we could save it on the version as well but only new uploads will be affected

**Comment by MorrisJobke** [comment]
I still think that we could leave it as it is, because it usually affects only a very limited set of apps and versions.

**Comment by skjnldsv** [comment]
> I still think that we could leave it as it is

closing then
