### ISSUE TITLE
Can't create users in GUI, only with OCC

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#5206]
### Steps to reproduce
1. Do a fresh install of Nextcloud
2. Try to create a new user in the GUI
3. It asks for password
4. Enter (correct) password

### Expected behaviour
It should be possible to create users in GUI

### Actual behaviour
I can only create users with OCC

https://cloud.techandme.se/s/Co5m3nF1V1DpAZw

### Server configuration

**Operating system**:
Ubuntu Server 16.04
**Web server:**
Apache 2.4
**Database:**
MySQL 5.7
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
12.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
The Nextcloud VM (Nextcloud download server)
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Default apps plus contacts and calendar
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "updatechecker": false,
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "192.168.10.100",
            "domain.com"
        ],
        "datadirectory": "\/var\/ncdata",
        "overwrite.cli.url": "https:\/\/domain.com",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "nextcloud_db",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Stockholm",
        "installed": true,
        "instanceid": "ocltdh1j5uif",
        "mail_smtpmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "info",
        "mail_domain": "domain,com",
        "mail_smtpsecure": "ssl",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0,
            "dbindex": 0
        },
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "loglevel": 2,
        "theme": ""
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 10
#### Web server error log
<details>
<summary>Web server error log</summary>

```
No errors
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No errors
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment]
Works fine here, with having to enter the password and without

**Comment by nickvergessen** [comment]
Can you use a JS debugger on https://github.com/nextcloud/server/blob/4fa817039451982b2ff8d7f6267a2770af594ca4/settings/js/users/users.js#L978-L988
And also watch which requests are sent in the network console of your browser?

**Comment by enoch85** [comment]
@nickvergessen Same for me, works on my cloud but behaves strange on a customers NC as you can see in the video. Regarding the JS debugger, how do I use that more specifically?

Maybe try other browsers as well...

I will work more with this cloud this weekend so I can do more tests then.

**Comment by enoch85** [comment]
Seems like a temporary issue, it's working now.

**Comment by enoch85** [comment]
Same as this: https://github.com/nextcloud/server/issues/2734

**Comment by msiemea** [comment]
Same issue with the latest Ubuntu ova. areas where a admin is needed a popup comes for a password. No password is accepted. time is synchronized. Change group to admin group. Fillout email server details.
