### ISSUE TITLE
Shared content deleted from local computer when server put in maintenance mode

### ISSUE THREAD

**Issue by jsalatiel** [nextcloud/server#5208]
### Steps to reproduce
1. Have a computer with owncloud-client synced and one folder with big files shared with you by someone else.
2. Put the server in maintenance mode using sudo -u www-data php occ maintenance:mode --off

### Expected behaviour
The owncloud-client should just lost connection or just stay idle

### Actual behaviour
The shared folder will be deleted from the computer running owncloud-client, and it will be redownloaded when the server leaves maintanance mode. If the shared folder is big , it will take lot of time to redownload it.

### Server configuration

**Operating system**: debian jessie

**Web server:** 
apache 2.4.10-10+deb8u8

**Database:** 
mysql-server                          5.5.55-0+deb8u1

**PHP version:**
5.6.30+dfsg-0+deb8u1

**Nextcloud version:** (see Nextcloud admin page)
11.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/

**Comment by nickvergessen** [comment]
I experienced the same issue in the past. This should be a client issue.
@rullzer did we report it somewhere?

**Comment by Bubu** [comment]
This seems to be a similar/same problem to what I wrote about here: https://help.nextcloud.com/t/on-upgrade-to-nc12-clients-locally-delete-content-from-shared-folder/13386

I wasn't sure where I should report it (client vs. server).

**Comment by AndrewBucklin** [comment]
Also experiencing the same issue; I would image it's a client issue. What's the correct procedure for getting this moved to the correct location?

**Comment by szaimen** [comment]
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!
