### ISSUE TITLE
Update Notification is displayed multiple times

### ISSUE THREAD

**Issue by ungesundes-halbwissen** [nextcloud/server#521]
### Steps to reproduce
1. Install NC 10 Beta
2. Activate App Gallery Plus
3. As Gallery plus currently needs server version below 10, it cannot be updated, hence, shows the error

### Expected behaviour
Display " You have 1 (App) update vailable" once

### Actual behaviour
the message on top (centralized) gets copied below each information banner multiple times

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:**

**Database:** MySQL

**PHP version:** 7.0

**Nextcloud version:** 10.0 Beta

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install with existing DB

![nc-update](https://cloud.githubusercontent.com/assets/20168451/17053298/a0dae0f6-5001-11e6-88d1-1bda53bd8dd1.PNG)

**Comment by nickvergessen** [comment]
Well our internal version is 9.1, so that update should work.

**Comment by ungesundes-halbwissen** [comment]
Max Version expected by Gallery+ is 9.0.99, but this isn't the Problem really. I meant to report the multiple instances of the update notifications. Sorry if I didn't manage to make that clear

**Comment by nickvergessen** [comment]
You should be able to use https://github.com/oparoz/galleryplus/releases/tag/v9.1.0 in Nextcloud 10.
Other then that, we are getting rid of the notification in Nextcloud 11 with switching to the new appstore.

So I'm closing this.
