### ISSUE TITLE
LDAP: use NC User instance to store displayname etc.

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#5212]
Otherwise, CardDAV thing is not being updated. affected down to 11.

Needs moving away from user_ldap entries in preference (→ some cleaning up) for this features

**Comment by TheMrApostel** [comment]
Maybe an option to check already integrated ldap user for changes (e.x. new email address) would also be great?

**Comment by blizzz** [comment]
* [x] for quota we do this already
* [ ] for displayname this would be delegated back to the backend → pointless. However, this is where the change-hook is emitted, too. 
* [x] for email we do this already

so essentially, it is the one adjustment. which should also update the system addressbook.

**Comment by blizzz** [comment]
Last bit done in #12054
