### ISSUE TITLE
Video preview (transcoded mp4) in the thumbnails folder

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#5218]
### Steps to reproduce

When you uploaded a video in large resolution (4K for example) - video player will not play it smoothly (especially on slow internet connection) - due to the size of video. Similar problem is when your movie is in the format not supported by browsers.

### Expected behaviour

We can transcode uploaded movies to smaller size and the correct format and save it in the thumbnails folder (we have to do it async in the background process) then the video player will be playing transcoded video (if available, else original video).

Proposition for transcoding movie (when: `'enable_movie_transcode' => true` is enabled in the config file) that should work with ffmpeg and avconv:

https://github.com/lenz1111/core/compare/master...lenz1111:video_transcode

This is example of using preview video in files_videoplayer:

https://github.com/lenz1111/files_videoplayer/compare/master...lenz1111:video_transcode

--------

Try again - I fixed my code:
1. set in config.php:

```
'enable_previews' => true,
'preview_max_x' => 640,
'preview_max_y' => 640,
'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Movie',
    1 => 'OC\\Preview\\Image',
  ),
  'enable_movie_transcode' => true,
```

(enable preview and set size of preview video)
2. Make sure you have working _ffmpeg_ / _avconv_ in your system (recommended _ffmpeg_)
3. Upload video - after upload _ffmpeg_ should start in background and then it should create file preview.mp4 in thumbnails/ folder
4. If file preview.mp4 exists - files_videoplayer should use it for preview

Patch:
Tested with current owncloud/master owncloud/files_videoplayer/master 
[video_trancode_patch.zip](https://github.com/owncloud/core/files/272641/video_trancode_patch.zip)

**This issue is copied from https://github.com/owncloud/core/issues/24480**

**Comment by enoch85** [comment]
This issue is requested by a customer of mine.

**Comment by rprieto** [comment]
I would really like having transcoded videos and previews as well. At the moment, the behaviour is confusing as the videos appear in file mode, but not in gallery mode. If a user browses in gallery-mode only they might simply think there are no videos.

To add another point of view: I'm looking at Next Cloud to share mostly-static folders with photos and videos, mounted as *External Storage* from AWS S3. Generating the transcoded video / thumbnails in the background sounds great. Another option is to allow the admin to provide their own. I'd be quite happy to transcode the videos and generate the previews before uploading, I just need to know where to store them (in the external storage? primary storage? which location?). The advantage is that my NextCloud server can be very lightweight - no need to pay for a large VPS with high CPU/memory to do a few video transcodes every week, when most of the time it will simply be idle or serving static data.

**Comment by sturze** [comment]
Yup! Me too! 1080p drains my volume on mobile quite fast. Also it's annoying to wait till my DSLR Pics are loaded on my Phone. Feels like 1990 🙈 
thumbs up for transcoding/thumbnails! 👍

**Comment by worldwar345** [comment]
I’m finding the issue with video files not being displayed while in gallery view still exists as  rprieto stated in his comment 7 months ago... I have a fresh install of Nextcloud running Ubuntu 16.04 nginx php7.2 APCu and Redis running with Unix Socket all configured properly as far as I can tell. First run videos through handbrake and make sure to hit the Web Optimized button before uploading to your server will probably help most people a little. But even at that the video playback over the web is very slow. File transfers as well run at about 400-500kb/s with my cpu practically running idle.. I would think that if the transfer/streaming speed was increased video and image speed would also no longer be an issue. And in my case I would happily trade cpu for some kind of transcoding as mentioned to help.

**Comment by lenz1111** [comment]
I can create video preview functionality in recent version of NextCloud but I need to know where to store preview... (`data/appdata_<instanceid>/preview`?)?

**Comment by shankari** [comment]
nextcloud admins, this sounds like a cool feature - the previews would help both help us figure out what the video is, and make it easier to send videos on messaging apps, specially to countries with spotty internet access

What is blocking the merge? is it primarily testing? I'd be happy to test and report issues if that is the case.

**Comment by wiswedel** [comment]
> What is blocking the merge?

@shankari Has there been a pull request yet? Please link it here.

**Comment by shankari** [comment]
@wiswedel I don't think there is an official PR, but it looks like @enoch85 has uploaded a patch https://github.com/owncloud/core/files/272641/video_trancode_patch.zip

**Comment by skjnldsv** [comment]
I think we can close as this deserve its own app clearly.
For the preview, you can still [have this enabled for mp4 files](https://www.allerstorfer.at/nextcloud-install-preview-generator/) (as well as others mie types)

But I'd unfortunately say that trans-coding will not come into server.
Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by meonkeys** [comment]
Would on-the-fly transcoding fit into this issue as well? That would be a useful CPU- or GPU-intensive option for folks that preferred it.

**Comment by enoch85** [comment]
@meonkeys Please open a separate issue. This one is closed since over a year.

Thanks!
