### ISSUE TITLE
Update from nextcloud 11.0.3 to final 12 not possible

### ISSUE THREAD

**Issue by hotschmaster23** [nextcloud/server#5220]
### Steps to reproduce
1. PHP 7.0.18-0ubuntu0.16.04.1
2. Server version: Apache/2.4.18 (Ubuntu)
3. 10.0.29-MariaDB-0ubuntu0.16.04.1 
4. nextcloud version 11.0.3

### Expected behaviour
solution for this update behavior 

### Actual behaviour
Wanted to upgrade from 11.0.3 as nextcloud team is telling we should always keep the installation updated and no bigger version steps should be done.
Update app is not working. Why are you programming an update app when this is not working correctly. My installation is telling me also when i am issueing the command 
sudo -u www-data php /var/www/nextcloud/occ upgrade
Nextcloud is already latest version
Also with the commandline it is not possible to update to nextcloud 12
It takes me 1 week to setup nextcloud with all necessary security configurations, backupconfigurations and modsecurity to have a stable installation.
Is the only update way to install everything new? sorry but that is not acceptable.

### Server configuration

1. PHP 7.0.18-0ubuntu0.16.04.1
2. Server version: Apache/2.4.18 (Ubuntu)
3. 10.0.29-MariaDB-0ubuntu0.16.04.1 
4. nextcloud version 11.0.3
5. 4.8.0-53-generic #56~16.04.1-Ubuntu 

**Updated from an older Nextcloud/ownCloud or fresh install:**
update from nextcloud 11.0.3 to final 12

sudo -u www-data php occ status --output=json
{"installed":true,"version":"11.0.3.2","versionstring":"11.0.3","edition":""}

**Where did you install Nextcloud from:**
downloaded from your webpage

**Signing status:**

**Comment by LukasReschke** [comment]
The Nextcloud 12 update is only issued to around 15% of users right now. Please stay patient or switch the channel temporarily to beta to get a quicker update.

Also `occ upgrade` is only for upgrades once the code has been replaced. Use `php updater/updater.phar` instead.

**Comment by cyBea** [comment]
Is there a way to know the percentage of updated instances?
How long can it take till I get update notification for my instance?
Now its 3. of July and i still got no notification...

**Comment by hotschmaster23** [comment]
Have updated to nextcloud 12 so automatic is not needed. Change to beta und update it to 12 there are no big issues.

**Comment by knttr** [comment]
By now 11.04 is installed and still no stable channel update to the current 12.02 is available via the integrated updater.
When will the stable release to Nextcloud 12 be available. Where can we find information on the progress with regards to expected updates in the various channels?

**Comment by FvdLaar** [comment]
By now I'am running Nextcloud 11.0.5 and still my Update Channel doesn't show any 12 version (not even after choosing "beta". Could it be that there is an other issue with the web based updater in 11.0.5?

**Comment by knttr** [comment]
I was able to update to 12.0.2 after updating to11.0.5  (or was it 11.0.4) using the web based updater in both cases. I am using the stable channel only.
(Meanwhile I've updated to 12.0.3 .)

**Comment by FvdLaar** [comment]
After reboot of my server (needed because some Linux updates) and revisiting the Nextcloud Administrator pages I now see version 12.0.3 (but I need to set Cron to AJAX, refresh the pages a few times and choose Beta as stream). Strange.

**Comment by FvdLaar** [comment]
And it seems to work. Thanx all ;-)
