### ISSUE TITLE
Latest stable version not correct

### ISSUE THREAD

**Issue by alve89** [nextcloud/server#5228]
Hey guys,

why is the latest stable version on nextcloud.com v12.0.0 but the administration area of my instance displays v11.0.3 as latest?

**Comment by LukasReschke** [comment]
https://nextcloud.com/blog/welcome-to-nextcloud-12/

> You can find Nextcloud 12 on our download page. You can follow the manual upgrade procedure or use our built in updater, either from the graphical console or the command line. Note that we do a staged roll-out: only 15% of the users on Nextcloud 11.0.3 on the Stable release channel currently receive an update notification for Nextcloud 12. If you wish to update with the updater even though there is no notification, you can set the channel to beta, reload the page and proceed to upgrade. After the upgrade set the channel back to stable!

**Comment by LukasReschke** [comment]
Also, this question has been asked a lot of times before in our forums, Github (e.g. https://github.com/nextcloud/server/issues/5220 the ticket just closed before this one, etc.)
