### ISSUE TITLE
Share password by mail send on behalf issue

### ISSUE THREAD

**Issue by hgooijen** [nextcloud/server#5233]
our emailserver settings are set to SMTP and mails are send by our exchange server.
When sharing a file by mail, the mail is send by the standard mailuser set in the emailserver settings.
When "send password by mail" is active, a second mail is send with the password in it. this mail however is send by the standard mailuser on behalf of the user sharing the file. the standard mailuser does not have the permission the send in behalf of the user sending the share.
This also causes emails to be marked as spam at te receiving party, because of SPF errors.

Is it possible to change the settings so the password mail is send, just like the share mail?

**Comment by blizzz** [comment]
@nextcloud/sharing @schiessle

**Comment by PVince81** [comment]
this issue is very old and probably outdated

please try again with NC 22.2.0 and if the issue persists there, feel free to reopen
