### ISSUE TITLE
Unit tests won't run with phpunit > 5.4

### ISSUE THREAD

**Issue by sonologic** [nextcloud/server#5235]
### Steps to reproduce
1. Checkout owncloud server repo
2. Configure according to the installation manual
3. curl -sSL https://phar.phpunit.de/phpunit.phar -o phpunit.phar
4. php ./phpunit.phar -c tests/phpunit-autotest.xml

### Expected behaviour
Test-cases are running

### Actual behaviour
Error thrown:
`PHP Warning:  require_once(PHPUnit/Autoload.php): failed to open stream: No such file or directory in /home/gmc/src/3rdparty/nextcloud/nextcloud-git/tests/bootstrap.php on line 18
PHP Fatal error:  require_once(): Failed opening required 'PHPUnit/Autoload.php' (include_path='/home/gmc/src/3rdparty/nextcloud/nextcloud-git/3rdparty/pear/console_getopt:/home/gmc/src/3rdparty/nextcloud/nextcloud-git/3rdparty/pear/pear_exception:/home/gmc/src/3rdparty/nextcloud/nextcloud-git/3rdparty/pear/archive_tar:/home/gmc/src/3rdparty/nextcloud/nextcloud-git/3rdparty/pear/pear-core-minimal/src:/home/gmc/src/3rdparty/nextcloud/nextcloud-git/apps') in /home/gmc/src/3rdparty/nextcloud/nextcloud-git/tests/bootstrap.php on line 18
`

### Server configuration

**Operating system**:
Ubuntu 16.04.2 LTS

**Web server:**
n/a

**Database:**
postgresql-9.5 (but any will do)

**PHP version:**
PHP 7.0.18-0ubuntu0.16.04.1

**Nextcloud version:** (see Nextcloud admin page)
stable12 branch or master branch

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
github

**Signing status:**
<details>
<summary>Signing status</summary>

```
Integrity checker has been disabled. Integrity cannot be verified.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_sharing: 1.4.0
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - lookup_server_connector: 1.0.0
  - news: 11.0.4
  - oauth2: 1.0.5
  - provisioning_api: 1.2.0
  - sharebymail: 1.2.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - testing
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "och1bhpuvt0a",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/home\/gmc\/src\/3rdparty\/nextcloud\/data-folder",
        "overwrite.cli.url": "http:\/\/localhost\/nextcloud-git",
        "dbtype": "pgsql",
        "version": "12.0.0.29",
        "dbname": "nextcloud-git",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
n/a

**Operating system:**
Ubuntu 16.04.2 LTS

#### Web server error log
<details>
<summary>Web server error log</summary>

```
n/a
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
n/a
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
n/a
```
</details>

**Comment by sonologic** [comment]
See also https://github.com/symfony/symfony/issues/21534 for a similar issue elsewhere.

**Comment by sonologic** [comment]
The problem is here: https://github.com/nextcloud/server/blob/master/tests/bootstrap.php#L17

The class PHPUnit_Framework_TestCase no longer exists but is now namespaced as \PHPUnit\Framework\TestCase

**Comment by rullzer** [comment]
I run now with phpunit 5.6 so seems we can close this.
