### ISSUE TITLE
Lower default logging level in future releases?

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/server#5236]
In a few instances of NC12 I've spun up, logging appears to be at `debug` by default in Settings > Logging. That doesn't appear to be dissimilar from NC11 however the amount of logs generated appears to have increased with 12 on the debugging level, whether intentionally or not.

Generally, debugging only needs to be enabled when actively troubleshooting an issue, with info, warning and error covering off the important messages that need to come through. 

Debugging enabled by default is likely information overload.

![disable_debugging](https://cloud.githubusercontent.com/assets/3178412/26744803/67a3f9b8-47df-11e7-9341-d7b2c57614bf.gif)

**Comment by MichaIng** [comment]
Is this also true for clean installations? The updater changes loglevel to debug and does not change it back at least since nextcloud 12. But actually I like to review the update process in the log directly afterwards and then change the loglevel back to "Warning" manually.

**Comment by jasonbayton** [comment]
Not sure actually. 11 was set to debug, though that was an update. The 2 12s I checked I believe one was a clean install.

**Comment by skjnldsv** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.

**Comment by MichaIng** [comment]
@skjnldsv 
Jep, logging is reverted after update has finished here as well.
