### ISSUE TITLE
Desktop Sync client ignores deselection of root folder for sync, syncs anyways

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/server#5239]
This is using the demo.nextcloud.com instance as of June 2 2017, using the NextCloud client 2.3.1 on Ubuntu Linux. I have also observed this in ownCloud with the ownCloud desktop sync client.

When I initially connect the sync client to the nextCloud instance, I tell it to sync a specific sub-folder, and intentionally de-select the root folder. There are files in there I don't want to have synced. Yet, they get synced anyways, and behave as if they are supposed to be synced.

Modifications, deletions, creations and such of files in the root are synced, be it in the folder on the computer, or in the webGUI at the root of the account. The content I care about is synced, but the content in the root should not be synced to the computer, since I configured the client as such.

This is a problem because content is being synced that is intentionally not told to be synced. This can lead to accidents of all kinds, deletions, modifications, etc.

I for one don't want the sync of the root folder, when I tell it to not sync it.

**Comment by blizzz** [comment]
Sounds essentially like https://github.com/owncloud/client/issues/3361

**Comment by BloodyIron** [comment]
Sure does! Are you getting the issue yourself?

**Comment by BloodyIron** [comment]
Well I and my clients are not okay with it. We keep accidentally deleting files that we didn't expect to sync because it's not behaving like it's being instructed. Where exactly should this issue be posted? I didn't see a more appropriate place.

**Comment by blizzz** [comment]
Well, it is already posted, as pointed out.
