### ISSUE TITLE
“Authentication Required” prompt after upgrade to 12.0.0 does not work

### ISSUE THREAD

**Issue by rapadu** [nextcloud/server#5240]
##Hello, 

since I updated to NC 12 I can't use the built in authentication to change any settings. It won't work for any user. Wanted to create a new App-Password, but it won't accept my authentication. It display's nothing, not a single error.  Since I can't activate the Issues Template I'm gonna write some information down. 

## What happend 
Authentication Required prompt won't accept my password. No errors too 

## Does this happens always? 
Yes and for every user 

## How did you the update 
Via the Web updater

## Server 
OS: Ubuntu 16.04 LTS 
PHP: 7.0.18
DB: 10.0.29-MariaDB
Webserver: Apache 2

If you need more information just let me know. 
Greetings 
Rapadu

# Update
I used a backup and started the upgrade from 11 to 12 again. Now everything works. I did no changes to the OS itself.

**Comment by MorrisJobke** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
