### ISSUE TITLE
Feature Request - Re-organize or Hide application icons in Direct_Menu

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#5242]
### Steps to reproduce
[1. Attempt to drag and drop an app icon in the direct menu to re-order](http://imgur.com/a/QlS56)
2. Look under administrative settings for personalization of the Direct_Menu

### Expected behaviour
Applications icons can be re-ordered
Direct_Menu can be personalized

### Actual behaviour
Nothing happens. No personalization is available.

**Comment by georgehrke** [comment]
please reopen in  https://github.com/juliushaertl/apporder
