### ISSUE TITLE
OpenWeatherMap API Key not saveable

### ISSUE THREAD

**Issue by Elleni57** [nextcloud/server#5243]
### Steps to reproduce
1. Pasting OpenWeatherMap API Key
2.Pushing save button
3.

### Expected behaviour
OpenWeatherMap API Key saved, thus enabling me to use weather app

### Actual behaviour
Nothing happens, when pushing save button

### Server configuration
**Operating system**: Linux itsrv1 4.8.17-hardened-r2 #1 SMP Sun Jan 29 14:50:59 CET 2017 x86_64

**Web server:** Apache (apache2handler)

**Database:** mysql 10.0.30

**PHP version:** 5.6.30-pl0-gentoo
Modules loaded: Core, date, ereg, libxml, openssl, pcre, sqlite3, zlib, bz2, ctype, curl, dba, dom, fileinfo, filter, gd, gettext, hash, iconv, SPL, json, mbstring, mcrypt, mysql, mysqli, session, PDO, pdo_mysql, pdo_sqlite, standard, posix, pspell, Reflection, Phar, SimpleXML, sockets, imap, tokenizer, xml, xmlreader, xmlwriter, zip, apache2handler, apcu, uploadprogress, apc, Zend OPcache

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** 

**Signing status:**
<details>
	<summary>Signing status</summary>

```
"Integrity checker has been disabled. Integrity cannot be verified."
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.5.2
 - admin_notifications: 1.0.0
 - announcementcenter: 3.1.0
 - audioplayer: 2.0.1
 - bookmarks: 0.10.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - checksum: 0.3.4
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - deck: 0.1.4
 - external: 2.0.3
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_accesscontrol: 1.2.4
 - files_automatedtagging: 1.2.2
 - files_downloadactivity: 1.1.1
 - files_markdown: 1.0.1
 - files_pdfviewer: 1.1.1
 - files_reader: 1.0.4
 - files_retention: 1.1.2
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - groupfolders: 1.0.2
 - impersonate: 1.0.1
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - news: 11.0.5
 - nextcloud_announcements: 1.1
 - notes: 2.2.0
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - ocsms: 1.12.0
 - password_policy: 1.2.2
 - previewgenerator: 1.0.6
 - provisioning_api: 1.2.0
 - quota_warning: 1.0.0
 - rainloop: 5.0.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_email: 1.0.1
 - spreed: 2.0.1
 - spreedme: 0.3.9
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - weather: 1.4.2
 - workflowengine: 1.2.0
 - workin2gether: 0.9.6

Disabled:
 - admin_audit
 - encryption
 - files_external
 - mail
 - user_external
 - user_ldap
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "ocv03tzqr9fr",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "ncloud.mydomain.com"
    ],
    "datadirectory": "\/home\/oc_data",
    "overwrite.cli.url": "https:\/\/ncloud.mydomain.com",
    "dbtype": "mysql",
    "version": "12.0.0.29",
    "dbname": "ncloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "integrity.check.disabled": true,
    "mail_from_address": "admin",
    "mail_smtpmode": "php",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "mydomain.com",
    "maintenance": false
}
```
</details>

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0

**Operating system:**

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	Insert your webserver log here
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
	Insert your Nextcloud log here
	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
	Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
	```
</details>

**Comment by MariusBluem** [comment]
Wrong repo: https://github.com/nextcloud/weather
See: https://github.com/nextcloud/weather/issues/35
