### ISSUE TITLE
Nextcloud does not switch Primary Storage?

### ISSUE THREAD

**Issue by bearmoo-repo** [nextcloud/server#5248]
### Steps to reproduce
1. edit config.php(Added:)
'objectstore' => array(
        'class' => 'OC\\Files\\ObjectStore\\S3',
        'arguments' => array(
                'bucket' => 'nextcloud',
                'autocreate' => true,
                'key'    => 'EJ39ITYZEUH5BGWDRUFY',
                'secret' => 'M5MrXTRjkyMaxXPe2FRXMTfTfbKEnZCu+7uRTVSj',
                'hostname' => 'example.com',
                'port' => 1234,
                'use_ssl' => true,
                'region' => 'optional',
                // required for some non amazon s3 implementations
                'use_path_style'=>true
        ),
),
2. save the the file.
3. open nextcloud in the browser check to see if the files get written into the s3 bucket.

### Expected behavior
Tell us what should happen
Expected nextcloud to leverage the bucket instead of the local fs.

### Actual behaviour
Tell us what happens instead
nextcloud still uses the local fs instead of the s3 bucket.

### Server configuration

**Operating system**:
Centos 7.2

**Web server:**
Apache 2.4 + php-fpm

**Database:**
MariaDB

**PHP version:**
5.6
**Nextcloud version:** (see Nextcloud admin page)
12.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from owncloud 9.

**Where did you install Nextcloud from:**
though the cli

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - calendar: 1.5.3
  - contacts: 1.5.3
  - dav: 1.3.0
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreedme: 0.3.9
  - survey_client: 1.0.0
  - twofactor_backupcodes: 1.1.1
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - comments
  - encryption
  - federation
  - firstrunwizard
  - gallery
  - systemtags
  - theming
  - updatenotification
  - user_external
  - user_ldap
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{
    "system": {
        "instanceid": "ocetlt2fynm7",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com"
        ],
        "datadirectory": "\/var\/www\/html\/nextcloud_data",
        "overwrite.cli.url": "example.com",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "owncloud",
        "dbhost": "10.42.241.154",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "maintenance": false,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "slave.cache-service",
            "port": 6379
        },
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "nextcloud-data",
                "autocreate": false,
                "key": "xxx",
                "secret": "yyy",
                "hostname": "example.com",
                "port": 9000,
                "use_ssl": true,
                "region": "optional",
                "use_path_style": true
            }
        }
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
yes, webdav

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
No errors show up?

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by roslum** [comment]
I have the very same problem, although mine is a fresh install, ubuntu 16.04

**Comment by blizzz** [comment]
Log files, etc?

@icewind1991

**Comment by MorrisJobke** [comment]
This is more a problem of the documentation on how to set it up - I will close this ticket in favour of #5865
