### ISSUE TITLE
proposal

### ISSUE THREAD

**Issue by yangfanv** [nextcloud/server#5253]
Sorry, that's a suggestion. I'm installing this server side with the debiam8.8 version, when the lamp environment. Upload, install files, decompression, encountered problems can not access, and finally check the permissions, for small white, the first is to check the system problems, and finally suggest that this has a wrong measures. This is Baidu translation, some inconsistencies, please understand.

**Comment by blizzz** [comment]
I'm installing this server side with the debiam8.8 version, when the lamp environment. Upload, install files, decompression,

I understand you uploaded and unzipped the tarball, correct?

> encountered problems can not access

The webinterface does not open, and perhaps shows an error?  Which one?

> and finally check the permissions, for small white, the first is to check the system problems, and finally suggest that this has a wrong measures.

The web user needs to be able to access the data. On Debian it is probably www-data, so change the file ownership to this user.

**Comment by MorrisJobke** [comment]
Please ask for help in the forums: help.nextcloud.com
