### ISSUE TITLE
Shared WebCal calendar not writable

### ISSUE THREAD

**Issue by alve89** [nextcloud/server#5258]
Hey guys,

I shared a calendar with its link: webcal://mynextcloudinstance.tld/remote.php/dav/public-calendars/THERANDOMSTRING?export and imported it in Outlook. But there the calendar is not writable. Is it possible to solve this problem and make it writable?

**Comment by georgehrke** [comment]
Webcal is not writable by design. 
You need to use the CalDAV endpoint, when you want read-write access to a calendar.

**Comment by alve89** [comment]
Alright. But Outlook doesn't support CalDAV I think. So it's not working. Thanks anyway.

**Comment by georgehrke** [comment]
@alve89 There is a CalDAV Plugin for Outlook. Let me check for a link ...

**Comment by georgehrke** [comment]
https://nextcloud.com/blog/nextcloud-offers-caldav-synchronizer-for-outlook-users/

**Comment by alve89** [comment]
You don't need to. I'm using Outlook on my business PC with no admin rights and quite restrictive security guidelines...

**Comment by georgehrke** [comment]
I'm afraid you won't be able to have write access to your calendars in that case.

**Comment by alve89** [comment]
I'm to. Thank you!
