### ISSUE TITLE
Does it makes sense to show the group membership in the personal settings?

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#5260]
While implementing a config switch to hide the group membership in the personal settings (https://github.com/nextcloud/server/pull/5259) I wonder if this should be the default.

I never really looked at it, only now that I developed the config switch (which might already be an indicator of its usefulness). While looking at it in more detail I have to confess that it clutters the personal page without adding anything useful for the user. They can't change it. So what is the user supposed to do with this information? Maybe it would be a good idea to hide it by default?

Just wandering, maybe I miss something... What do you think? @jancborchardt @rullzer @blizzz @nickvergessen @MorrisJobke  @nextcloud/designers 

![groups1](https://cloud.githubusercontent.com/assets/1589737/26819579/d47585bc-4a9f-11e7-81a8-1562c26f348d.png)

vs

![group2](https://cloud.githubusercontent.com/assets/1589737/26819582/dab084f4-4a9f-11e7-9bd4-eda16a52e01a.png)

**Comment by MariusBluem** [comment]
This sharing/collaboration aspect of system groups is mostly replaced by Circles and system groups are mostly used for administrative tasks (user management), the user does and should not care about. This is why I see no reason to keep them in the personal settings. I'd vote for remove them here and extend Circles instead.

**Comment by blizzz** [comment]
Nevertheless there might still be systems were groups are setup by the admin and used for sharing etc. It is otherwise hard to guess which groups you can share to. I'd keep it on by default for now, and would reconsider in a year or so.

**Comment by schiessle** [comment]
> It is otherwise hard to guess which groups you can share to.

Valid point. On the other hand user can not only share with their own groups. So they have to guess it anyway.

**Comment by blizzz** [comment]
> Valid point. On the other hand user can not only share with their own groups. So they have to guess it anyway.

Depending on the configuration, they might only share with(in) their own groups.

**Comment by nickvergessen** [comment]
Maybe show the groups when sharing is limited to groups you are a member of?

**Comment by nickvergessen** [comment]
But I'm also fine with killing it completely

**Comment by jancborchardt** [comment]
It comes down to why we have this. It’s good to know what you are part of so you know with which groups you could share. :)

Some improvements we could think of:
- Simple: On hover show the members of that group. Kind of like we do for our group video calls.
- More advanced: Maybe even think about putting it in the files sidebar as a »Groups« entry so you could focus on what is going on in that specific group context.

**Comment by Daksol** [comment]
**Strongly disagree with removing this information**, given that there is nowhere else where a user can get that info without going via Administrators. Our organisation rely on the Group Folder functionality where Group membership is central.

Thanks,

**Comment by jancborchardt** [comment]
Yep, also still my comment from https://github.com/nextcloud/server/issues/5260#issuecomment-307148419 is current → closing.
