### ISSUE TITLE
Deleting files does not work when its done from the Mac Desktop client

### ISSUE THREAD

**Issue by walec51** [nextcloud/server#5262]
### Expected behaviour
When a file gets deleted on a Mac with the dekstop client i also gets deleted on the server.

### Actual behaviour
Deletion is noted in the Activities view but the file is still visible in the folder in web ui.
When I try to delete it there I get an error:

 Fatal	webdav	OCA\DAV\Connector\Sabre\Exception\FileLocked: HTTP/1.1 423 "marketing/gazety/boksy-reklamowe/edytowalne/reklama-5-150x110-edyt.ai" is locked

Nextcloud client and sever version: 11

**Comment by blizzz** [comment]
A file is locked when write access is happening, and if not unlocked automatically, the lock should disappear after 30min. did you try again?

**Comment by MorrisJobke** [comment]
No response on this: I assume it is not happening anymore: closing
