### ISSUE TITLE
[Previews][Question] Possibility to move previews to a fresh install/oc_filecache db?

### ISSUE THREAD

**Issue by MichaIng** [nextcloud/server#5264]
Is it possible to move the `preview` folder inside `appdata_<instanceid>` to a fresh nextcloud installation with fresh databases and reread them via `occ files:scan-app-data`?

The previews seem to be sorted inside folders with file ID as folder name, if I get it right? And these IDs seem to be just counted from 1 to X upwards in the order they are scanned/created. So in a fresh install, using `occ files:scan` to recreate the file database, the files could be scanned in a different order or even files could be changed, removed or added, which should result in different file IDs. This would make the preview folder useless, even might show wrong previews for files, if it gets just copied into the new appdata folder.

Am I right so far with this assumption, or is there some magic check/correction done by `occ files:scan-app-data` to connect the available previews correctly?

In case, as preview generation can take much time, it would be nice to have this possibility, e.g. by sorting the previews in a different way, by information that enables an automated connection based on just the original file itself, instead of the database.

**Comment by rullzer** [comment]
The only connection that is there is the fileid. So if you get a new database this connection is lost and you'll have to regenerate your previews.

This is the same for shares etc. If you just move the files and rescan they also can't appear.

**Comment by MichaIng** [comment]
Thanks for clarification.
