### ISSUE TITLE
Change oc to nc

### ISSUE THREAD

**Issue by GitHubUser4234** [nextcloud/server#527]
In several place "oc" is still used, e.g. default table prefixes and first two letters of instanceid in config.php. This might not be of high priority, but nevertheless especially the default table prefixes might leave question marks in new users' heads :smile:

**Comment by MorrisJobke** [comment]
> In several place "oc" is still used, e.g. default table prefixes and first two letters of instanceid in config.php. This might not be of high priority, but nevertheless especially the default table prefixes might leave question marks in new users' heads 😄

This will completely break existing instances. We need to think about this a lot and provide a very robust migration path. I don't think it is a good idea to change this for all instances, but we should change the default setting for new instances as a first step ;)

**Comment by MorrisJobke** [comment]
We stick for now with what we have and maybe evaluate later to move more stuff over.
