### ISSUE TITLE
Show personal details even if they are not updatable

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#5275]
With the introduction of the global scale there is following configuration:

```
'gs.enabled' => true,
'gs.federation' => 'internal',
```

With this all inputs fields for the lookup server (phone number, website, address, twitter) on the personal page are hidden. We should maybe show them without the input field but only as text if they are set. In this way the user sees what data is associated to it's account if it is set by the admin somehow.

cc @schiessle @oparoz @nickvergessen

**Comment by nickvergessen** [comment]
Fine by me to display them if they are set.

**Comment by schiessle** [comment]
hm, the problem is that at the moment we only query the lookup server one you want to share with someone but we don't check the lookup server regularly for changes of the user data and sync them back to the Nextcloud server.

**Comment by schiessle** [comment]
While thinking about it. The email address is normally also configured in the user management and we copy if from there already, right? So we don't need to query the lookup server to get at least this value.

I'm quite sure that this is true for LDAP, right @blizzz 
@MorrisJobke would this also work in your case?

**Comment by nickvergessen** [comment]
@schiessle we don't have to sync anything from the lookup server. Just show the local data in the personal page?!

**Comment by blizzz** [comment]
What @nickvergessen says :)

**Comment by schiessle** [comment]
@nickvergessen yes, as said in my second comment... If we have them locally already through the user management it is fine

**Comment by nickvergessen** [comment]
they can be set via provisioning with an admin account. So we just display them from the accounts table. 👍

**Comment by MorrisJobke** [comment]
> they can be set via provisioning with an admin account. So we just display them from the accounts table. 👍

Exactly - that's what we are doing and that would solve this issue.
