### ISSUE TITLE
files_external always downloads whole file from locally mounted rclone fuse storage

### ISSUE THREAD

**Issue by tvvid** [nextcloud/server#5279]
### Steps to reproduce
1. download https://rclone.org/ and mount /local_folder from any of supported cloud storage
2. add this /local_folder, which now represents data on cloud storage, to external storage in admin page
3. upload some few GB video mp4 file to it, and try to preview or download and stop after few seconds

### Expected behaviour
when you stop in bmon should not be RX data running server should not continuously download those files when you stopped

### Actual behaviour
actual behaviour is that in bmon, even after you stop previewing, disconnect your local pc from internet, vps is still downloading this file cause you have to restart php service to kill those remote connection, only after killing or restarting php RX is stopped.

### Server configuration

ubuntu 16.04

**Web server:**
nginx

**Database:**
mariadb

**PHP version:**
php7.0-fpm

**Nextcloud version:** (see Nextcloud admin page)
12
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh
**Where did you install Nextcloud from:**
official website

**Comment by tvvid** [comment]
And this is not vps rclone fuse or unionfs-fuse issue. nor nginx nor proxy buffering.
It is definitely files_external issue.
Because i also have installed preview plugin and enabled movie preview.
And in that case preview plugin does not try to download whole file, in bmon it takes only few bytes to generate preview and transfer stops.
But files_external transfer does not stop until it download whole few GB file.

**Comment by tvvid** [comment]
its probably sabre dav fault.
It wants to read whole post data from php://input

**Comment by tvvid** [comment]
i have checked inside php files.
When i changed ignore_user_abort(true) to (false) inside:
/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php = NOT HELPED
/var/www/nextcloud/apps/dav/appinfo/v2/remote.php = NOT HELPED
/var/www/nextcloud/lib/private/legacy/files.php = NOT HELPED

/var/www/nextcloud/lib/private/Files/View.php - YES - HELPED, now it works fine but is that really ok?

**Comment by blizzz** [comment]
>  When i changed ignore_user_abort(true) to (false) inside:

That's a contact mine, anything could happen if request are not properly handled but cancelled inbetween.

@icewind1991

**Comment by ErAzOr2k** [comment]
Are there any news for this issues? I'm exactly in the same situation. I'm running fuse (rclone) as data folder. Nextcloud always loads the whole file, even when stopping download on client or stopping a video.
