### ISSUE TITLE
Problem with contacts in the Menubar in NC12 with IE11

### ISSUE THREAD

**Issue by Stabre** [nextcloud/server#5281]
### Steps to reproduce
1.Open Webinterface on NC12 with Microsoft Internet Explorer 11
2. click on contacts in the right Conner of the menubar and the contacts are loaded
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
The Contacts reloaded every view seconds and the user is not able to select any contact
in Chrome and Mozilla there isn´t any reloading every view seconds
### Server configuration

**Operating system**:
Debian 8

**Web server:**
Apache2
**Database:**
MariaDB
**PHP version:**
5.4
**Nextcloud version:** (see Nextcloud admin page)
12.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
11.0
**Where did you install Nextcloud from:**
nextcloud.com
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://bcloud.buerkle-gmbh.de/index.php/settings/integrity/failed 
paste the results here.
``
`No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by blizzz** [comment]
@nextcloud/javascript

**Comment by blizzz** [comment]
and or perhaps @nextcloud/contacts

**Comment by herrfeuer** [comment]
I can confirm This Bug with NC12, IE11, nginx on Centos7.

**Comment by jacestk** [comment]
same thing here with Centos7!
Someone can telle me what apps/modules is generating this list?

**Comment by herrfeuer** [comment]
@jacestk start searching in contactmenu.js. i tried to switch back to that version worked in nc11 but no success.

**Comment by jacestk** [comment]
Yep thanx, found it after some reseach... line 296
```
_onSearch: _.debounce(function() {
			this.trigger('search', this.$('#contactsmenu-search').val());
		}, 700),
```
if you replace the timer value "700" by "5000" for example, the list appears but the research don't work anymore until the end of the time.
So the problem is from the trigger or _debounce function... Have to investigate a bit more...

**Comment by jacestk** [comment]
here my awful patch:
```
	_onSearch: _.debounce(function(){
			if (this.fixie11 !== this.$('#contactsmenu-search').val() ) {
				this.fixie11 = $('#contactsmenu-search').val();
				this.trigger('search', this.$('#contactsmenu-search').val());
			}
		}, 700),
```
Another problem appears: the first time you click onto the contacts icon, the list is "empty" (only a empty div is sended). Still working on it

**Comment by blizzz** [comment]
@ChristophWurst  mind having a look? ^

**Comment by ChristophWurst** [comment]
Found it: we're focussing the input field after rending the list of contacts. Since IE11 apparently has a bug where it triggers the 'input' even whenever a input gets focus, this causes an endless loop. Looks like M$ doesn't care about the bug and it's not being fixed: https://connect.microsoft.com/IE/feedback/details/810538/ie-11-fires-input-event-on-focus

However, I think I can add a little *fix* to this. Won't be the best UX, but it will at least not keep reloading all the time …

**Comment by ChristophWurst** [comment]
Fix can be found at https://github.com/nextcloud/server/pull/6795
