### ISSUE TITLE
Provide Calendar API

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/server#5282]
Just like the Contacts API, the server should provide a Calendar API to allow apps to access the user's calendar.

In it's first iteration (Nextcloud 13), it should be enough to provide read-only access.

API design is open for discussion, but should imho follow the contacts api.

**Comment by tcitworld** [comment]
Is the Contacts API reference published somewhere to check consistency ?

**Comment by georgehrke** [comment]
Not that I am aware of :/

**Comment by LucileDT** [comment]
The :book: documentation of the Calendar API can be found in the [developer manual](https://docs.nextcloud.com/server/13/developer_manual/api/OCP/Calendar/index.html).
