### ISSUE TITLE
Allow to set width of vertical panes if text is longer in left pane especially

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/server#5283]
This request was originally made for the News app, but I was redirected here to post this. 
Link here: https://github.com/nextcloud/news/issues/180

The issue is that the fixed width of the panes is too small for longer texts especially in the left one (for example long feed names in the News app). I made a screenshot to illustrate the problem:

![snapshot3](https://user-images.githubusercontent.com/10073629/26877797-5b20f966-4b8b-11e7-9d1e-bd321ae9d991.png)

The left pane is too narrow to show the full length of the feed name, but on the right is a lot of unused whitespace. The text also overlaps with the menus. Maybe it would be possible to change the width of the panes by the user with the mouse?

**Comment by blizzz** [comment]
@nextcloud/designers @nextcloud/javascript

**Comment by jancborchardt** [comment]
Ability to arbitrarily change sizes of this bar will result in a bunch of issues ranging from simply looking silly with too much whitespace, to being too narrow and messing with the layout.

Right now every app has a common base to work on, and that is good. Flexibility would have to be tested across such a huge matrix of apps, screen sizes, languages (for text length) and devices that it will be a nightmare to maintain properly and make it look nice.
