### ISSUE TITLE
Apps adding navigation entry via appinfo.xml do not respect group limit

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#5286]
### Steps to reproduce
1. Install an app that makes use of #2822 like news 
https://github.com/nextcloud/news/blob/master/appinfo/info.xml#L50-L55
2. Limit app to certain groups

### Expected behaviour
Navigation icon should be hidden for users that are not in those groups

### Actual behaviour
Navigation item is visible for all users

**Comment by nickvergessen** [comment]
@juliushaertl can you test https://github.com/nextcloud/server/pull/5617 please?
Thanks
