### ISSUE TITLE
Can we have telephone links in the search/dropdown list in NC12?

### ISSUE THREAD

**Issue by NoMoreNicksLeft** [nextcloud/server#5290]
### Steps to reproduce
1. Run Nextcloud.
2. Install the contacts app, add contacts.
3. Use the dropdown list.

### Expected behaviour
A tiny telephone icon should appear next to those contacts that have phone numbers, and it should use the standard tel://+18001234567 telephone url. These seem to work with many apps already (Skype, Facetime, etc) on the desktop.

I don't believe many people use fax machines anymore, but if they have these I don't see how useful those would be... a quick google search didn't reveal any off-the-shelf software that would make use of it (even though rfc2806 defines url schemes for it).

### Actual behaviour
Only icons for email (and possibly video, if you have the chat plugin installed) show.

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)

NC 12+

**Comment by georgehrke** [comment]
I wrote an app for that: https://github.com/georgehrke/nextcloud-telephoneProvider

Will publish it on the appstore once I have the signing certificate.
