### ISSUE TITLE
SyntaxErrorException maria db while updatingto nextcloud 12

### ISSUE THREAD

**Issue by davidpeach** [nextcloud/server#5293]
### Steps to reproduce
1. Have Nextcloud 11.0.2 installed
2. Use updater to update to 12.0
3. Click Start update when going back into nextcloud

### Expected behaviour
Update to version 12

### Actual behaviour
I get the following error: 

Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'DELETE FROM `oc_reader_bookmarks` b WHERE b.file_id = ?' with params [188]: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'b WHERE b.file_id = '188'' at line 1

### Server configuration

**Operating system**: Ubuntu 16.04 Server

**Web server:** Apache 2

**Database:** Maria DB

**PHP version:** 7.0

**Nextcloud version:** (see Nextcloud admin page) 11.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** updating 

**Where did you install Nextcloud from:** cant remember

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by blizzz** [comment]
seems to be caused by a third party app? Coz, I don't know where the table ``oc_reader_bookmarks`` comes from. The log line is missing details. Could you complete your issue report?

**Comment by MorrisJobke** [comment]
@davidpeach @nemesi2017 What app is this reader? It looks like there is a bug in it?
