### ISSUE TITLE
Add admin activities like "User account added (or removed)" to activity stream

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/server#5294]
As an admin, I also want to be informed about relevant admin-related activities such as adding or removing user accounts.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.

**Comment by nickvergessen** [comment]
admin_audit gives access to this kind of information
