### ISSUE TITLE
Internal server error when using PostgreSQL as backing DB and uploading to an external SMB/CIFS storage.

### ISSUE THREAD

**Issue by fayf** [nextcloud/server#5297]
### Steps to reproduce
1. I am using postgres as the backing DB, and I have an external storage share set up using SMB
2. I try to upload a file to the external share

### Expected behaviour
The upload should succeed.

### Actual behaviour
I get an "Internal Server Error" message, but upon refresh the file upload has succeeded anyway.

### Server configuration
**Operating system**: Linux cf62e725620d 4.9.0-0.bpo.3-amd64 #1 SMP Debian 4.9.25-1~bpo8+1 (2017-05-19) x86_64

**Web server:** Apache/2.4.10 (Debian) (apache2handler)

**Database:** pgsql PostgreSQL 9.6.3 on x86_64-pc-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit

**PHP version:** 7.1.5
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, exif, gd, intl, ldap, mcrypt, memcached, mysqli, pdo_mysql, pdo_pgsql, pgsql, redis, zip, Zend OPcache

**Nextcloud version:** 11.0.3 (stable) - 11.0.3.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Using the official Docker image

**Signing status:**
<details>
	<summary>Signing status</summary>

```
No errors have been found.
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>

```
Enabled:
 - activity: 2.4.1
 - comments: 1.1.0
 - dav: 1.1.1
 - external: 1
 - federatedfilesharing: 1.1.1
 - federation: 1.1.1
 - files: 1.6.1
 - files_downloadactivity: 1.0.1
 - files_external: 1.1.2
 - files_pdfviewer: 1.0.1
 - files_sharing: 1.1.1
 - files_texteditor: 2.2
 - files_trashbin: 1.1.0
 - files_versions: 1.4.0
 - files_videoplayer: 1.0.0
 - firstrunwizard: 2.0
 - gallery: 16.0.0
 - issuetemplate: 0.2.1
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.0
 - notifications: 1.0.1
 - password_policy: 1.1.0
 - provisioning_api: 1.1.0
 - serverinfo: 1.1.1
 - sharebymail: 1.0.1
 - survey_client: 0.1.5
 - systemtags: 1.1.3
 - theming: 1.1.1
 - twofactor_backupcodes: 1.0.0
 - updatenotification: 1.1.1
 - user_external: 0.4
 - workflowengine: 1.1.1

Disabled:
 - admin_audit
 - encryption
 - files_accesscontrol
 - files_automatedtagging
 - files_retention
 - templateeditor
 - user_ldap
 - user_saml
```

</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "oc40kfksk5eo",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.1.132",
        "nextcloud.int.fayf.net",
        "nextcloud.fayf.net"
    ],
    "datadirectory": "\/var\/www\/html\/data",
    "overwrite.cli.url": "http:\/\/192.168.1.132",
    "dbtype": "pgsql",
    "version": "11.0.3.2",
    "dbname": "nextcloud",
    "dbhost": "192.168.1.131",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "user_backends": [
        {
            "class": "OC_User_SMB",
            "arguments": [
                "192.168.1.50"
            ]
        }
    ]
}
```
</details>

**Are you using external storage, if yes which one:**
Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OCA\Files_External\Lib\Storage\FTP
    [2] => \OC\Files\Storage\DAV
    [3] => \OCA\Files_External\Lib\Storage\OwnCloud
    [4] => \OCA\Files_External\Lib\Storage\SFTP
    [5] => \OCA\Files_External\Lib\Storage\AmazonS3
    [6] => \OCA\Files_External\Lib\Storage\Dropbox
    [7] => \OCA\Files_External\Lib\Storage\Google
    [8] => \OCA\Files_External\Lib\Storage\Swift
    [9] => \OCA\Files_External\Lib\Storage\SFTP
    [10] => \OCA\Files_External\Lib\Storage\SMB
    [11] => \OCA\Files_External\Lib\Storage\SMB
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** SMB

### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

**Operating system:**

#### Web server error log
<details>
	<summary>Web server error log</summary>

	192.168.1.128 - - [08/Jun/2017:06:39:11 +0000] "PUT /remote.php/webdav/Home/OW%20S5.txt HTTP/1.0" 500 1065 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>

	Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE "oc_filecache" SET "mtime"=? WHERE ("mtime" <> ? OR "mtime" IS NULL) AND "fileid" = ? ' with params ["1496685869.428", "1496685869.428", 79055]: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "1496685869.428"
	/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 128: Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
	/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - line 836: Doctrine\DBAL\DBALException driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'UPDATE "oc_file...', Array)
	/var/www/html/lib/private/DB/Connection.php - line 194: Doctrine\DBAL\Connection->executeQuery('UPDATE "oc_file...', Array, Array, NULL)
	/var/www/html/lib/private/Files/Cache/Cache.php - line 312: OC\DB\Connection->executeQuery('UPDATE "oc_file...', Array)
	/var/www/html/lib/private/Files/Cache/Wrapper/CacheWrapper.php - line 138: OC\Files\Cache\Cache->update(79055, Array)
	/var/www/html/lib/private/Files/Cache/Wrapper/CacheWrapper.php - line 111: OC\Files\Cache\Wrapper\CacheWrapper->update(79055, Array)
	/var/www/html/lib/private/Files/View.php - line 1533: OC\Files\Cache\Wrapper\CacheWrapper->put('OW S5.txt', Array)
	/var/www/html/lib/private/Files/View.php - line 567: OC\Files\View->putFileInfo('/andrew/files/H...', Array)
	/var/www/html/apps/dav/lib/Connector/Sabre/File.php - line 209: OC\Files\View->touch('/Home/OW S5.txt', '1496685869.428')
	/var/www/html/apps/dav/lib/Connector/Sabre/Directory.php - line 137: OCA\DAV\Connector\Sabre\File->put(Resource id #80)
	/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 1072: OCA\DAV\Connector\Sabre\Directory->createFile('OW S5.txt', Resource id #80)
	/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 525: Sabre\DAV\Server->createFile('Home/OW S5.txt', Resource id #80, NULL)
	[internal function] Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
	/var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
	/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method PUT', Array)
	/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
	/var/www/html/apps/dav/appinfo/v1/webdav.php - line 60: Sabre\DAV\Server->exec()
	/var/www/html/remote.php - line 165: require_once('/var/www/html/a...')
	{main}
</details>

#### Browser log
<details>
	<summary>Browser log</summary>

	I don't think this is necessary since it's a server side issue.
</details>

**Comment by sf-janz** [comment]
Hi @fayf! This looks an awful lot like #4794 
But there's an workaround you could try. Check #4794 for details.

**Comment by fayf** [comment]
Applied the patch and it works fine now. Thanks!

**Comment by blizzz** [comment]
Closing as fixed
