### ISSUE TITLE
Upgrade issue 9.0.50 -> 10.0beta: undefined method during federations upgrade

### ISSUE THREAD

**Issue by jowi24** [nextcloud/server#531]
### Steps to reproduce
1. `./occ upgrade` with an existing 9.0.50 nextcloud installation

### Expected behaviour
No errors during upgrade.

### Actual behaviour
Getting error:

```
Updating <federation> ...
An unhandled exception has been thrown:
Error: Call to undefined method OCA\Federation\AppInfo\Application::setupCron() in /home/rk/nextcloud.test/apps/federation/appinfo/update.php:23
Stack trace:
#0 /home/rk/nextcloud.test/lib/private/legacy/app.php(1197): include()
#1 /home/rk/nextcloud.test/lib/private/Updater.php(374): OC_App::updateApp('federation')
#2 /home/rk/nextcloud.test/lib/private/Updater.php(251): OC\Updater->doAppUpgrade()
#3 /home/rk/nextcloud.test/lib/private/Updater.php(150): OC\Updater->doUpgrade('9.1.0.13', '9.0.50.0')
#4 /home/rk/nextcloud.test/core/Command/Upgrade.php(290): OC\Updater->upgrade()
#5 /home/rk/nextcloud.test/3rdparty/symfony/console/Command/Command.php(259): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /home/rk/nextcloud.test/3rdparty/symfony/console/Application.php(844): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /home/rk/nextcloud.test/3rdparty/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /home/rk/nextcloud.test/3rdparty/symfony/console/Application.php(123): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /home/rk/nextcloud.test/lib/private/Console/Application.php(145): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/rk/nextcloud.test/console.php(92): OC\Console\Application->run()
#11 /home/rk/nextcloud.test/occ(11): require_once('/home/rk/nextcl...')
```
### Server configuration
**Operating system**:
Linux 4.6.2
**Web server:**
nginx 1.11.2
**Database:**
mariadb 10.1.14
**PHP version:**
php 7.0.9
**Nextcloud version:** (see Nextcloud admin page)
10.0beta
**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgrade from 9.0.50
**Where` did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by jowi24** [comment]
I could not reproduce the issue - my second try to upgrade the instance worked!

**Comment by LukasReschke** [comment]
I got some other reports of this. Reopening.

**Comment by LukasReschke** [comment]
Ok. I think this is caused because the linked file "appinfo/update.php" in "Error: Call to undefined method OCA\Federation\AppInfo\Application::setupCron() in /home/rk/nextcloud.test/apps/federation/appinfo/update.php:23" wasn't deleted. That explains it :)

**Comment by nikaro** [comment]
I just tried to update to version 10 and i get this error. What is the fix ?

**Comment by jowi24** [comment]
In my case, following the instructions here https://docs.nextcloud.com/server/9/admin_manual/maintenance/manual_upgrade.html solved the issue.

**Comment by enaut** [comment]
The fix is to actually follow the update instructions and delete/move everything besides data/ and config/ and only then extract the archive.
I faced the same problem and it worked after I reread the instructions carefully.

**Comment by nikaro** [comment]
Yes, carefully following the manual upgrade instructions worked. I don't know what did i do wrong before… :-/
