### ISSUE TITLE
Skeleton should not create files in shared folder

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#5312]
1. Have a shared folder "Photos" to a group
2. Create a new user and login
3. The normal skeleton files are copied into the share instead a different folder

This seems odd. Can we have it instead in a way of creating a new folder or so for this stuff?

**Comment by MorrisJobke** [comment]
The code can be found in here: https://github.com/nextcloud/server/blob/87aeae21e33947c3116eb3070bb19bd892c6f46b/lib/private/User/Session.php#L489

**Comment by szaimen** [comment]
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!
