### ISSUE TITLE
Nexcloud 11 upgrade to 12 workaround

### ISSUE THREAD

**Issue by dziustino** [nextcloud/server#5313]
After upgrade from Nexcloud 11 to 12 version with updater. And admin panel could not be reached. Gave Internal Server Error.

Nexcloud:
  - installed: true
  - version: 12.0.0.29
  - versionstring: 12.0.0
  - edition:

System:
  - Ubuntu 16.04.2 LTS
  - PHP 7.0.18-0ubuntu0.16.04.1
  - 10.0.29-MariaDB
  - Apache/2.4.18 (Ubuntu)

Pretty error format:

> Type: OCP\AutoloadNotAllowedException
> Code: 0
> Message: Autoload path not allowed: /var/www/nextcloud/apps/onlyoffice/lib/adminsettings.php
>  File: /var/www/nextcloud/lib/autoloader.php
> 

Not so pretty:

> {"reqId":"ckJflwhjUkoQFInqyVq6","level":3,"time":"June 09, 2017 08:48:28","remoteAddr":"<IP-REMOVED-FROM-PUBLIC>","user":"administrator","app":"index","method":"GET","url":"\/index.php\/settings\/admin","message":"Exception: {\"Exception\":\"OCP\\\\AutoloadNotAllowedException\",\"Message\":\"Autoload path not allowed: \\\/var\\\/www\\\/nextcloud\\\/apps\\\/onlyoffice\\\/lib\\\/adminsettings.php\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/autoloader.php(158): OC\\\\Autoloader->isValidPath('\\\/var\\\/www\\\/nextcl...')\\n#1 [internal function]: OC\\\\Autoloader->load('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#2 [internal function]: spl_autoload_call('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(94): ReflectionClass->__construct('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(117): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->resolve('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/ServerContainer.php(132): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(261): OC\\\\ServerContainer->query('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Settings\\\/Manager.php(352): OC\\\\Settings\\\\Manager->query('OCA\\\\\\\\Onlyoffice\\\\\\\\...')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/settings\\\/Controller\\\/AdminSettingsController.php(138): OC\\\\Settings\\\\Manager->getAdminSettings('server')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/settings\\\/Controller\\\/AdminSettingsController.php(72): OC\\\\Settings\\\\Controller\\\\AdminSettingsController->getNavigationParameters('server')\\n#10 [internal function]: OC\\\\Settings\\\\Controller\\\\AdminSettingsController->index('server')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\AdminSettingsController), 'index')\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\AdminSettingsController), 'index')\\n#14 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Settings\\\\\\\\Con...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#15 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#16 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#17 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(1000): OC\\\\Route\\\\Router->match('\\\/settings\\\/admin')\\n#18 \\\/var\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#19 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/autoloader.php\",\"Line\":134}","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36","version":"12.0.0.29"}

Workaround:
 DELETE FROM `oc_admin_settings` WHERE `class` LIKE '%Onlyoffice%'

seems that it fixed the issue for now. But might be inturesting to take a look. (I have a db dump when it didn't work). Hope it is useful.

**Comment by blizzz** [comment]
I guess the bug should be reported to OnlyOffice (too).

OTOH we should not fail so hard in this case.

**Comment by MorrisJobke** [comment]
> I guess the bug should be reported to OnlyOffice (too).

Not really - is a server issue. See #7230 for a fix.
