### ISSUE TITLE
Sync issues with BlackBerry Z30

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#532]
As reported [here](https://plus.google.com/b/104036748063781940910/114258049928799413804/posts/YWVb85trNWm)

### Steps to reproduce
1. Add calendar to blackberry calendar app
2. Make changes to an entry

### Expected behaviour
Changes should sync

### Actual behaviour
They don't

### Server configuration
**Operating system**:
Linux

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)
9.0.x

**Calendar version:** (see ownCloud apps page)
Latest

**Updated from an older ownCloud or fresh install:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**
Blackberry 10 OS 10.3.2.2836

**CalDAV-clients:**
Built in client

### Logs
App and server logs here:
https://steinerichs.ddns.net/index.php/s/u85uVuTRwuej85Q
password blackberrydebug

**Comment by Lord-Protector** [comment]
I can't confirm it on my BlackBerry Q10 (also 10.3.2.2836).
But I noticed another bug. After sync I edit it on my BB and then on server I got not just edited, but another new copy with changes. So I got old copy and new edited copy. And suddenly BB see only newer.

**Comment by nickvergessen** [comment]
Closing as per above

@Lord-Protector sounds like an issue with the calendar app you are using
