### ISSUE TITLE
Properly replace open graph favicon

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#5322]
https://github.com/nextcloud/server/blob/ad24b86013d60e7efe2487ae06478f624b01824f/apps/files_sharing/lib/Controller/ShareController.php#L375-L380 is not replacing the OpenGraph favicon so when sharing to Twitter, Facebook or some other place parsing it the icon will still show the Nextcloud logo.

We should probably use `\OCA\Theming\Controller\IconController::getTouchIcon` here if available.

**Comment by JaredBoone** [comment]
@MorrisJobke I'd like favicon-fb.png to be overridden by the favicon specified in the Theming app. It's not currently the case (as of 15.0.2). Who should I talk to about that and how can I help? Thanks!

**Comment by MorrisJobke** [comment]
cc @juliushaertl 

@JaredBoone Could you also open a separate ticket for this. It seems the old icon is used there as well for untamed instances.

**Comment by juliushaertl** [comment]
@JaredBoone Yes, please open a new ticket for this. If you want to look into fixing this, the relevant code part where the icons are replaced is here: https://github.com/nextcloud/server/blob/master/apps/theming/lib/ThemingDefaults.php#L337-L342
