### ISSUE TITLE
call_user_func() expects parameter 1 to be a valid callback,

### ISSUE THREAD

**Issue by Tealk144** [nextcloud/server#5325]
### Steps to reproduce
I do nothing but my log get spaamed, every second 10 lines of this:

### Error message
{"reqId":"OXx1THz2YZNL6uw7UArt","level":3,"time":"10.06.17 13:22:26","remoteAddr":"162.158.89.236","user":"Tealk","app":"PHP","method":"PROPFIND","url":"\/remote.php\/webdav\/Pen%20and%20Paper\/P%26P%20Regelwerke\/New%20World%20of%20Darkness\/World%20of%20Darkness","message":"call_user_func() expects parameter 1 to be a valid callback, class 'OCA\\QuotaWarning\\AppInfo\\Application' does not have a method 'login' at \/var\/www\/nextcloud\/lib\/private\/legacy\/hook.php#106","userAgent":"--","version":"12.0.0.29"}

### Server configuration
**Operating system**: Linux Anzah-Cloud 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64

**Web server:** Apache/2.4.10 (Debian) (apache2handler)

**Database:** mysql 5.7.18

**PHP version:** 7.1.6-1+0~20170609083833.26+jessie~1.gbpa2f43a
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, geoip, gettext, iconv, igbinary, intl, json, exif, mcrypt, msgpack, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, memcached, Zend OPcache

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** 

**Signing status:**
<details>
	<summary>Signing status</summary>

```
[]
```

</details>

**List of activated apps:**
<details>
	<summary>App list</summary>
```
Enabled:
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - admin_notifications: 1.0.0
 - bookmarks: 0.10.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - deck: 0.1.4
 - encryption: 1.6.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_downloadactivity: 1.1.1
 - files_pdfviewer: 1.1.1
 - files_reader: 1.0.4
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - issuetemplate: 0.2.1
 - keeweb: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.6.4
 - news: 11.0.5
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - quota_warning: 1.0.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_email: 1.0.1
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.0
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
 - workin2gether: 0.9.6

Disabled:
 - files_external
 - gallery
 - user_external
 - user_ldap
```
</details>

**The content of config/config.php:**
<details>
	<summary>Config report</summary>

```
{
    "instanceid": "ocz6kekhpjaq",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "anzah.cloud"
    ],
    "datadirectory": "\/home\/anzahcloud",
    "overwrite.cli.url": "https:\/\/anzah.cloud",
    "dbtype": "mysql",
    "version": "12.0.0.29",
    "dbname": "anzahcloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Berlin",
    "installed": true,
    "forcessl": true,
    "asset-pipeline.enabled": true,
    "theme": "",
    "log_type": "owncloud",
    "logfile": "\/home\/anzahcloud\/nextcloud.log",
    "loglevel": 2,
    "syslog_tag": "ownCloud",
    "logdateformat": "d.m.y H:i:s",
    "log_query": false,
    "cron_log": true,
    "log_rotate_size": 104857600,
    "overwritehost": "anzah.cloud:443",
    "overwriteprotocol": "https",
    "versions_retention_obligation": "auto, 120",
    "trashbin_retention_obligation": "auto, 60",
    "mail_from_address": "noreply",
    "mail_smtpmode": "smtp",
    "mail_domain": "anzahcraft.de",
    "maintenance": false,
    "updatechecker": false,
    "appstore.experimental.enabled": true,
    "enable_previews": true,
    "preview_max_x": 2048,
    "preview_max_y": 2048,
    "preview_max_filesize_image": 50,
    "preview_max_scale_factor": 10,
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir ",
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\PDF"
    ],
    "memcache.local": "\\OC\\Memcache\\APCu",
    "blacklisted_files": [
        ".htaccess"
    ],
    "minimum.supported.desktop.version": "2.2.2",
    "assetdirectory": "\/var\/www\/nextcloud",
    "activity_expire_days": 365,
    "htaccess.RewriteBase": "\/",
    "mail_smtpauth": 1,
    "mail_smtphost": "s95.goserver.host",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "singleuser": false,
    "mysql.utf8mb4": true
}
```
</details>

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.114 Safari/537.36 Vivaldi/1.9.818.50

**Operating system:**

#### Web server error log
<details>
	<summary>Web server error log</summary>
	```
	Insert your webserver log here
	```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
	<summary>Nextcloud log</summary>
	```
	Insert your Nextcloud log here
	```
</details>

#### Browser log
<details>
	<summary>Browser log</summary>
	```
	Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
	```
</details>

**Comment by patschi** [comment]
I'm seeing the same behavior on my installation as well. As this error is being produced by the QuotaWarning app and not from the nextcloud server itself, you may please re-create this issue over here: [nextcloud/quota_warning/issues](https://github.com/nextcloud/quota_warning/issues).

**Comment by blizzz** [comment]
what @patschi says, please report at the app → closing.
