### ISSUE TITLE
Force Sync Automatically

### ISSUE THREAD

**Issue by budimanjojo** [nextcloud/server#5327]
### Steps to reproduce
1. Copy and replace different file with the same name

### Expected behaviour
File has been changed, sync the new file 

### Actual behaviour
The file remains in the old version until I click the "Force Sync" button on the desktop client. Is there anyway I can at least make it force sync all the time? 

### Server configuration

**Operating system: Ubuntu 16.04**

**Web server: Apache2** 

**Database: Mariadb/mysql 10.0.29** 

**PHP version: PHP 7.0.18** 

**Nextcloud version: 12**

**fresh install:**

**Where did you install Nextcloud from:** Ubuntu repo

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found. 
</details>

### Client configuration
**Browser: Chromium** 

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by jasonbayton** [comment]
This may be better suited to https://github.com/nextcloud/client_theming/issues
Can you create the issue there please?

**Comment by budimanjojo** [comment]
Okay, I will. I'll close the issue here for now, thanks :)
