### ISSUE TITLE
Consider about icon for "Security"-section in personal settings

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#5332]
Currently used: `/settings/img/toggle-filelist.svg`
Does not look that good if we call the section "Security". I would expect the lock from `/settings/img/password.svg` ... Like that:

<img width="242" alt="bildschirmfoto 2017-06-10 um 21 54 58" src="https://user-images.githubusercontent.com/19711361/27005882-b8075bcc-4e27-11e7-9989-67cd455b3de8.png">

Unfortunately this lock is already in use for 2fa-backup section and external storages SSL-section 🙄 Maybe we should change these two icons there or integrate everything into a single "Security"-section (splitting up personal settings into multiple pages as for admins)

@nextcloud/designers

**Comment by jancborchardt** [comment]
You are right: We should use that icon for the security section (please open a PR to change it, easy fix ;) and then group all the security-related things there. :)

We should then also move forward with combining the Personal and Admin settings.

cc @blizzz @ChristophWurst

**Comment by blizzz** [comment]
Mind adding this to https://github.com/nextcloud/server/pull/4890?

**Comment by jancborchardt** [comment]
Fixed by https://github.com/nextcloud/server/pull/7116, no?
