### ISSUE TITLE
Search contacts feature is leaking data

### ISSUE THREAD

**Issue by remidebette** [nextcloud/server#5333]
Hi all.
Thanks for the awesome software.

The "search contact" feature appeared with Nextcloud 12 as a menu on the top right.
As of now I think it represents a serious security threat.
Indeed, users in different groups, who are not expected to be in contact with one another, can now see everyone's mail address and nextcloud ID
At the very least it represents a leak of personal data to persons who are potentially strangers to the Users, without them knowing about it.

It would be fine if the admin user could control the group level at which users could search each other for instance.

But right now even the admin mail/Nextcloud ID is in the wild (!!) 
On some configurations it is an issue.
Please provide at least a method to deactivate this feature temporarily.

EDIT: Even disabled users appear in the "search contact". Which means some people who left the website could still have their personal mail shared with potential strangers unknowingly

Mentions [here](https://help.nextcloud.com/t/bug-in-search-contacts-v12/13770) and [there](https://help.nextcloud.com/t/search-contacts/13818)

### Steps to reproduce
1. Connect with any non-admin user to its nextcloud account
2. Click on the top right to the "search contact" menu

### Expected behaviour
Not all the other users of the instance should be listed there.

### Actual behaviour
1. Search for the admin username (For instance)
2. You can now see his mail and you only miss its password to take the control of the instance (simplifies a potential brute-force attack)

**Comment by BornToBeRoot** [comment]
There is a feature request/bug: https://github.com/nextcloud/server/issues/4656

**Comment by remidebette** [comment]
It is very surprising that this issue was known during the beta and still made it to production. I consider this as a security issue

**Comment by blizzz** [comment]
@ChristophWurst

**Comment by ChristophWurst** [comment]
I'd say this is a duplicate of https://github.com/nextcloud/server/issues/5107.

**Comment by blizzz** [comment]
Then, closing in favor of #5107
