### ISSUE TITLE
Show 3 latest contacts/circles or groups

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#5335]
The sharing with user dropdown should be expanded by default and show the latest and/or often used contacts, circles and groups.

- When the file is already shared, the dropdown can be closed

@schiessle @jancborchardt

**Comment by skjnldsv** [comment]
@ChristophWurst @juliushaertl we have this, right?

**Comment by ChristophWurst** [comment]
Yep, done with https://github.com/nextcloud/server/pull/14180
