### ISSUE TITLE
Move link sharing into share with user-dropdown

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#5336]
Unify all sharing options into one single menu.

<img width="406" alt="bildschirmfoto 2017-06-11 um 09 20 20" src="https://user-images.githubusercontent.com/19711361/27009153-3845e678-4e87-11e7-842b-bc55c4a235d4.png">

- Would give the possibility to have multiple link shares with different permissions and possibilities to revoke
- To not hide this option too much, we would need the default expanded menu from #5335

**Comment by schiessle** [comment]
Looks like a nice idea, I like it!

**Comment by MariusBluem** [comment]
> To not hide this option too much, we would need the default expanded menu from #5335

⬆️ @schiessle

**Comment by MariusBluem** [comment]
As discussed @jancborchardt

**Comment by MorrisJobke** [comment]
Let's link @jancborchardt's response in the [client repo](https://github.com/nextcloud/client/issues/158#issuecomment-362926764):

Here's the mockup for sharing, to combine users and links :)
![](https://cloud.nextcloud.com/s/rg3M3m7SYrW6gXg/preview)
https://cloud.nextcloud.com/s/rg3M3m7SYrW6gXg

**Comment by jancborchardt** [comment]
@MorrisJobke @schiessle @juliushaertl would anyone of you be up for working on this together before and/or at the hackweek? :)

**Comment by MorrisJobke** [comment]
> @MorrisJobke @schiessle @juliushaertl would anyone of you be up for working on this together before and/or at the hackweek? :)

Maybe also one of @skjnldsv and @danxuliu could join :)

**Comment by MariusBluem** [comment]
Moved to https://github.com/nextcloud/server/issues/11169 🙃
