### ISSUE TITLE
Advanced sharing options margin

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#5337]
Margin between the advanced sharing options does not match with other places :)

<img width="203" alt="bildschirmfoto 2017-06-11 um 11 29 48" src="https://user-images.githubusercontent.com/19711361/27009897-750c3276-4e99-11e7-96cd-f726c1f947fd.png">

@nextcloud/designers @jancborchardt

**Comment by jancborchardt** [comment]
Yeah, that indeed seems like an awful lot of wbitespace. Which browser is this?

**Comment by MariusBluem** [comment]
Safari 11 ...

**Comment by MariusBluem** [comment]
any news on this :(

**Comment by MariusBluem** [comment]
Just reproduced, that this is happening on Firefox too ... so I think this is not a browser-specific problem. @skjnldsv What do you think? Is it easy to fix this? 😅 

<img width="378" alt="bildschirmfoto 2017-12-13 um 17 11 01" src="https://user-images.githubusercontent.com/19711361/33949021-a1a555bc-e028-11e7-96d4-7fe6ac917792.png">

**Comment by MorrisJobke** [comment]
If I remove https://github.com/nextcloud/server/blob/66391d65a68d89f5351c1be7810cd4abd0e82989/core/css/share.scss#L94-L98 then this is fixed.

**Comment by skjnldsv** [comment]
Disable the gallery app. :)

**Comment by MariusBluem** [comment]
> Disable the gallery app. :)

Not really 😱 This did work :D

**Comment by MorrisJobke** [comment]
Right - I was wrong - it is this part:

https://github.com/nextcloud/gallery/blob/3618fc1a28fd9ae064bb157703eb0ef878789d35/css/share.css#L61-L67

**Comment by skjnldsv** [comment]
Sorry I was late to the party! 😆

**Comment by skjnldsv** [comment]
Fixed already

**Comment by skjnldsv** [comment]
Oups, nope, I tought it was! 

Fix in https://github.com/nextcloud/gallery/pull/399

**Comment by MorrisJobke** [comment]
Fixed in master and will be backported to 13.
