### ISSUE TITLE
Bug: Navigation icon text in personal settings changing with translation?

### ISSUE THREAD

**Issue by janis91** [nextcloud/server#5339]
I have a question regarding an issue reported to me:
https://github.com/janis91/ocr/issues/91

I wonder if this the right way to do it:
https://github.com/janis91/ocr/pull/92/files

I would say no. I shouldn't be forced to add a class declaration for each and every translation.

I think this can be fixed here instead of the other way.

Can you confirm?

**Comment by janis91** [comment]
I tested it with federated cloud for example.. If someone translates "Federated Cloud" to something else "Lorem Ipsum" for example, the icon will not be displayed anymore, because the `nav-icon-*` class changes from `nav-icon-federated-cloud` to `nav-icon-lorem-ipsum`.
I think this is not the intended behavior.

**Comment by blizzz** [comment]
Adding an ``data-anchor-name`` should do the trick, e.g. https://github.com/nextcloud/activity/blob/master/templates/settings/form.php#L28

**Comment by janis91** [comment]
Thanks. I'll close this then.
