### ISSUE TITLE
"Unspecified share exception" instead of proper 404 page on unknown public share tokens

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#5346]
* open a public share page with a not available share token - like http://example.org/s/abcdef
* expected: get a proper 404 page
* actual: get a "Unspecified share exception"

![bildschirmfoto 2017-06-12 um 11 18 12](https://user-images.githubusercontent.com/245432/27043832-132f1a50-4f61-11e7-9948-ad10be30eb7b.png)

Ideas when this came in?

@nextcloud/sharing @nickvergessen

**Comment by MorrisJobke** [comment]
cc @oparoz

**Comment by nickvergessen** [comment]
Yeah https://github.com/nextcloud/server/blob/f707a40f19b81876b455066106416c64366b1d19/lib/private/Share20/DefaultShareProvider.php#L809-L815 would need some dedicated message. Not sure why this was not done, but I guess there is no reason?
