### ISSUE TITLE
Upload bar is not themed

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#5348]
* theme the color of your Nextcloud via the theming app
* expected: upload bar also uses this color
* actual: upload bar is still in Nextcloud blue

<img width="650" alt="bildschirmfoto 2017-06-12 um 12 01 41" src="https://user-images.githubusercontent.com/245432/27045608-04da51e4-4f67-11e7-96df-ffa304f45f8e.png">

cc @nextcloud/theming

**Comment by juliushaertl** [comment]
jquery-ui-fixes.css should be migrated to use SCSS variables in order to fix this.

**Comment by MorrisJobke** [comment]
Fixed in #6341
