### ISSUE TITLE
Manually scanned files can't dragged around

### ISSUE THREAD

**Issue by patschi** [nextcloud/server#5357]
### Steps to reproduce
1. Put file directly in data folder of an user
2. Rescan using `php occ files:scan <user>`
3. Switch to webinterface

### Expected behaviour
File should be able to drag around in the frontend

### Actual behaviour
File can't been dragged around:
![ezgif com-optimize](https://user-images.githubusercontent.com/2029878/27060427-18e396f2-4fdd-11e7-9bc4-ede0704e358d.gif)

### Server configuration
**Operating system**: Ubuntu 16.04
**Web server:** nginx
**Database:** MariaDB
**PHP version:** 7.0
**Nextcloud version:** 12.0.0.29
**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Comment by blizzz** [comment]
Sorry, this is not a supported scenario.

**Comment by sf-janz** [comment]
@blizzz It should be. Consider disaster recovery, i.e. restoring a file level backup of the data folder.

**Comment by patschi** [comment]
I agree. As `files:scan` is an official command and its work is scanning files, the scanned files actually should work in the webinterface as well. Maybe at least assign `low` priority as this scenario may be rare, IMHO. But anyway, your decision, blizz :)

**Comment by blizzz** [comment]
It's not supported to randomly put files into the folder… should not circumvent Nextcloud. but i reopen. @icewind1991 any thoughts?

**Comment by icewind1991** [comment]
Is the permissions on the file correct? if you click the 3 dots does it give the "move" option?

**Comment by patschi** [comment]
Oh. I'm so sorry about that, it was my fault! You were absolutely right.
As I did not see any warnings or something else I didn't know what its causing. Totally forgot about checking the permissions server-side. File was owned by the user who wget'ed the file, forgot to change the user then. Correcting the user owner and rescanning did the job. Working now.

Sorry! Closing this now.
