### ISSUE TITLE
Versioning Problems: 10 vs 9.1

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/server#536]
The version is defined in the version.php file: https://github.com/nextcloud/server/blob/stable10/version.php#L28

Internally version 10 is defined as 9.1, however the version string reports 10.

This can cause the following issues:
* App developers add 10 as owncloud min version inside their info.xml
* People will generate the wrong app templates using ocdev/ncdev
* App Store will have to translate the owncloud min version using a hard coded map (9.1 becomes 10, 10 becomes 11, 10.1 becomes 12, ...). Personally I see this as a horrible impediment for getting the store live.

Here are a couple of ways how this could be handled:

1. Retract version 10 and use 9.1 so everything aligns with ownCloud

2. Change the internal version to 10

3. Change the internal version to 10 and adjust the requirements check to also include a nextcloud element e.g. 

```xml
<info>
<dependencies>
    <owncloud min-version="9.1"/>
    <!-- we also use platform for the new app store, however you could also use nextcloud -->
    <platform min-version="10"/>  
</dependencies>
</info>
```

Downsides:

1. would be the best case since no further action is required but would likely lead to bad PR. However you could argue that you talked to the ownCloud guys and decided to not break APIs, so you also needed to readjust the version number

2. The worst solution imo since app devs absolutely lose the control to require an api level. The old app store is still used by ownCloud or Nextcloud so you'd have to live with breaking one or the other.

3. Would require you to add an additional element and checks. You would also need to internally translate ownCloud versions to Nextcloud versions. The app store would hard require the platform/nextcloud min-version which would force people to readjust their apps before publishing to the new store. If we want something graceful the app store would also need to implement a conversion between owncloud and nextcloud elements which would also suck.

pick your poison

@LukasReschke @karlitschek @MorrisJobke @jospoortvliet

**Comment by karlitschek** [comment]
This is a known issue. The version number of this release is 10. It is called 10 in the UI, marketing, website, stable10 branches and so on. Unfortunately we have to call it 9.1 in the versions.php to not break compatibility with all the 3rdparty apps out there. 
This will be solved once we have 11 later this year but unfortunately for now this is the best option. Similar like certain Windows version are also call something else internally. Yes I know it sucks. But I hope the developers will understand this.

**Comment by BernhardPosselt** [comment]
OK so this will be done only for one version?

**Comment by BernhardPosselt** [comment]
So basically this is only a one time thing and 11 will report 11?

**Comment by MorrisJobke** [comment]
> So basically this is only a one time thing and 11 will report 11?

If I understand this correct then yes.

**Comment by BernhardPosselt** [comment]
OK closing then, tools and app store will provably be not ready for 10 so we don't have to add exceptions :)
