### ISSUE TITLE
GUI bug on authentication required

### ISSUE THREAD

**Issue by wilhil** [nextcloud/server#5368]
### Steps to reproduce
1. Go to settings and create a new user
2. Get the password wrong

### Expected behaviour
When a password is required to change a setting, the box should have the "Cancel" or "Confirm" buttons

### Actual behaviour
If you get the password incorrect, it changes from "Cancel" and "Confirm" to "No" and "Yes"

### Server configuration

**Operating system**:
Ubuntu 16.04 LTS
**Web server:**
Apache
**Database:**
Sqlite3 (testing only)
**PHP version:**
7.0.18
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 12.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
home page
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_external: 0.4
  - workflowengine: 1.2.0
Disabled:
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

{
    "system": {
        "instanceid": "ocgg72f2njgu",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xx.xx.xx.xx"
        ],
        "datadirectory": "\/var\/www\/html\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/xx.xx.xx.xx\/nextcloud",
        "dbtype": "sqlite3",
        "version": "12.0.0.29",
        "installed": true
    
</details>

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Chrome
**Operating system:**
Win 10
### Logs
#### Web server error log

**Comment by wilhil** [comment]
![image](https://user-images.githubusercontent.com/2283808/27076869-45b0d28c-5026-11e7-9ff5-36290ec720ef.png)
![image](https://user-images.githubusercontent.com/2283808/27076874-4827804c-5026-11e7-99aa-907fc25c4f74.png)

**Comment by dardelet** [comment]
Do you get this bug every time you try to create a new user and enter the wrong password ? 

I can't seem to be able to reproduce it consistently. Happened once and now its fine.
