### ISSUE TITLE
manifest.json not using data from theme

### ISSUE THREAD

**Issue by fancycode** [nextcloud/server#5371]
### Steps to reproduce
1. Use a theme that has a custom title, name and logo.
2. Check the app manifest that is loaded from `/core/img/manifest.json`.

### Expected behaviour
The name and logo should be used from the theme.

### Actual behaviour
Name and logo are hardcoded to `Nextcloud` and the Nextcloud logo. I also tried putting a `manifest.json` in `core/img` of my theme. If the ` manifest.json` can be themed otherwise, I didn't find any documentation about it.

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
12.0.0

**Comment by juliushaertl** [comment]
@fancycode manifest.json was for android webapps, right?

**Comment by fancycode** [comment]
Yes, it's on mobile devices it's used if you add a bookmark to website to your home screen. See https://w3c.github.io/manifest/ for details.

**Comment by juliushaertl** [comment]
>  I also tried putting a manifest.json in core/img of my theme. 
@fancycode  That works as expected here. Can you check that again?

Anyhow we sould have a manifest.json being generated for the theming app settings.

**Comment by juliushaertl** [comment]
https://github.com/nextcloud/server/pull/6451 will add support for the theming app.

@fancycode It was indeed missing on the login page. That is also fixed in https://github.com/nextcloud/server/pull/6451
