### ISSUE TITLE
Contacts can't handle contact picture if TYPE is missing

### ISSUE THREAD

**Issue by minils** [nextcloud/server#539]
### Steps to reproduce
1. Import a VCF File including contacts with the tag

```
PHOTO;ENCODING=BASE64;JPEG:/9j/...
```

(Some programs omit the TYPE= attribute)
2. Contact pictures don't get included.
### Expected behaviour

The pictures should still be imported.
If the first line of the picture is:

```
PHOTO;ENCODING=BASE64;JPEG:/9j/...
```

instead of:

```
PHOTO;ENCODING=BASE64;TYPE=JPEG:/9j/...
```
### Actual behaviour

The pictures are not imported at all.
### Server configuration

**Operating system**: Debian 8

**Web server:** nginx 1.6.2 

**Database:** mysql 5.5.50-0+deb8u1

**PHP version:** PHP 5.6.23-0+deb8u1

**Nextcloud version:** 9.0.52

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from ownCloud 9.0.2

**Where did you install Nextcloud from:** From tar ball

**List of activated apps:**
<details>
<summary>

App list</summary>

```
Enabled:
  - activity: 2.2.1
  - admin_audit: 1.0.0
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - password_policy: 1.0.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - theming: 0.1.0
  - updatenotification: 0.1.0
```

</details>
### Client configuration

**Browser:** Mozilla Firefox 47.0.1

**Operating system:** Fedora 24

**Comment by MorrisJobke** [comment]
cc @georgehrke

**Comment by skjnldsv** [comment]
> ```
> PHOTO;ENCODING=BASE64;JPEG:/9j/...
> ```



> ```
> PHOTO;ENCODING=BASE64;TYPE=JPEG:/9j/...
> ```

Neither of them are valid according to the rfc.
https://tools.ietf.org/html/rfc6350#section-6.2.4
https://tools.ietf.org/html/rfc2426#section-3.1.4

So we are compliant with the carddav rules
