### ISSUE TITLE
Federated shares should use share_folder config setting

### ISSUE THREAD

**Issue by xraMsamohT** [nextcloud/server#540]
### Expected behavior

Remote shares should use the _"default folder for shared files and folders other than root"_.
The received file should be stored in the defined folder.

https://github.com/nextcloud/server/blob/stable9/config/config.sample.php#L1066-L1069

### Actual behavior

The received files stored in the root.
### Steps to reproduce the behavior
1. Create a federated file share on server one.
2. Accept the remote file share on server two.
3. On server two, take a look into the _share folder_, defined in `config.php`.
### Server configuration

**Nextcloud version:**
9.0.53 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
ownCloud 9.0.3 -> Nextcloud 9.0.50 -> … -> 9.0.53

**List of activated apps:**
<details>
<summary>

App list</summary>

```
  …
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  …
  - files_sharing: 0.9.1
  …
```

</details>

**The content of config/config.php:**
<details>
<summary>

Config report</summary>

```
  …
  'share_folder' => '/Shared',
  …
```

</details>

---

Is it a _bug_, a _feature_, or _by design_?

**Comment by nickvergessen** [comment]
I'd say by design and IIRC the setting is deprecated.

@schiessle @rullzer

**Comment by MorrisJobke** [comment]
> I'd say by design and IIRC the setting is deprecated.

Really? Since when?

**Comment by schiessle** [comment]
No, it is not deprecated... I think it would make sense to use it for federated shares as well.

**Comment by xraMsamohT** [comment]
Do we have a chance to see this issue fixed in v12?

**Comment by MorrisJobke** [comment]
I don't think so, because we have still a lot of other stuff to do for v12

**Comment by xraMsamohT** [comment]
Any news about this issue?
