### ISSUE TITLE
Contacts can't handle quoted printables

### ISSUE THREAD

**Issue by minils** [nextcloud/server#541]
Contacts app can't handle quoted printables in CSV files:

```
N;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:=4A=6F=73=C3=A9;;;;
FN;CHARSET=UTF-8;ENCODING=QUOTED-PRINTABLE:=4A=6F=73=C3=A9=20
```

Results in a contact called **=4A=6F=73=C3=A9** but should actually be called **José**.

**Comment by MorrisJobke** [comment]
This is the same as https://github.com/owncloud/contacts/issues/399

@karlitschek @LukasReschke How should we address this?

**Comment by karlitschek** [comment]
Hmm. What do you suggest?

**Comment by MorrisJobke** [comment]
> Hmm. What do you suggest?

I would try to fix this upstream (owncloud/contacts). No need to fork the contacts app now. We have plenty of work already ;)

**Comment by Mebus** [comment]
I still get the QUOTED-PRITNABLE error. Is it possible to fix this?

Mebus

**Comment by skjnldsv** [comment]
https://github.com/sabre-io/dav/issues/857#issuecomment-229055478
