### ISSUE TITLE
After editing a favorite with the build in editor, the favorite is not at the top anymore

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#5410]
### Steps to reproduce
1. Mark two files as favorite and have more files in the list
2. Edit one of the two files with the files texteditor
3. Save the file and close the editor

### Expected behaviour
The file should still be in the top

### Actual behaviour
The file is sorted by name only into the other non-favorited files

@nextcloud/javascript 

PS: @danxuliu do you want to be part of the `nextcloud/javascript` team?

**Comment by danxuliu** [comment]
The sort comparator used for the file list [checks the `isFavorite` attribute of the `FileInfo` objects](https://github.com/nextcloud/server/blob/0a3d9f25c14c7e9f06efdff765c26149370df382/apps/files/js/filelist.js#L1569). When the file list is loaded [`OC.Files.Client.getFolderContents()` is called](https://github.com/nextcloud/server/blob/0a3d9f25c14c7e9f06efdff765c26149370df382/apps/files/js/filelist.js#L1627), which eventually parses the response from the server and [sets the `isFavorite` attribute](https://github.com/nextcloud/server/blob/0a3d9f25c14c7e9f06efdff765c26149370df382/core/js/files/client.js#L307) in the FileInfo objects that in the end [are sorted and set in the file list](https://github.com/nextcloud/server/blob/0a3d9f25c14c7e9f06efdff765c26149370df382/apps/files/js/filelist.js#L1700).

The editor does not use the `FileInfo` objects from the file list, but a `FileInfoModel` instead. The file list is extensible through plugins (like the _Tags_ plugin which provides both the tags and favorite features), so when the [FileInfoModel for certain file is created](https://github.com/nextcloud/server/blob/0a3d9f25c14c7e9f06efdff765c26149370df382/apps/files/js/filelist.js#L452) the plugins can extend the attributes provided to the `FileInfoModel` by redefining `elementToFile`. However, the _Tags_ plugin does not set the `isFavorite` attribute in [its `elementToFile` function](https://github.com/nextcloud/server/blob/0a3d9f25c14c7e9f06efdff765c26149370df382/apps/files/js/tagsplugin.js#L162), so the `FileInfoModel` used by the editor does not have that attribute. When [the editor is closed its `FileInfoModel` is updated](https://github.com/nextcloud/files_texteditor/blob/master/js/editor.js#L614), which causes [the row for the file to be updated too in the file list](https://github.com/nextcloud/server/blob/0a3d9f25c14c7e9f06efdff765c26149370df382/apps/files/js/filelist.js#L462). In the end this causes [the sort comparator to be called](https://github.com/nextcloud/server/blob/0a3d9f25c14c7e9f06efdff765c26149370df382/apps/files/js/filelist.js#L1937) with a `FileInfo` object derived from the `FileInfoModel`, so it will not have the `isFavorite` attribute and thus whether the file is a favorite or not will not be taken into account when sorting.

The proper solution is not to add the `isFavorite` attribute as needed when the `elementToFile` function of the _Tags_ plugin is called, though; as already said, whether a file is a favorite or not is not part of the core features of the file list, but something provided by a plugin. Thus, the sort comparator defined in the core file list should take into account only those attributes known to the core file list, but that comparator should be extensible by plugins like the `elementToFile` function or the parsing of the WebDAV response using `FileInfoParser` objects.

Having said that...  a file list plugin needing to customize the sorting order of the files seems like a corner case (I can not think of any other example besides sorting the favorites on top), so maybe it is better to still take into account in the sort comparator of the core file list whether the file is a favorite or not like it is done now and defer making it extensible until there is another use case for that.

In any case, setting the `isFavorite` attribute does not belong to the `_parseFileInfo` function of `OC.Files.FileInfo` like it is done now, and it should be moved to the `FileInfoParser` provided by the _Tags_ plugin (and called from the `_parseFileInfo` function). Moreover, it is probably not needed to set that attribute anyway (nor in the `elementToFile` function), as the sort comparator can check instead whether the `tags` attribute contains the special `OC.TAG_FAVORITE` or not.

Any thoughts on all this?

@nickvergessen 
>  PS: @danxuliu do you want to be part of the nextcloud/javascript team?

Feel free to add me if you want ;)

**Comment by nickvergessen** [comment]
> whether a file is a favorite or not is not part of the core features of the file list, but something provided by a plugin. 

Yes and no. While it is designed like a plugin, it's part of the core feature list and can't even be disabled. So when that is an incorrect but possible solution which is simple enough for 12, we could do that and do the proper fix for 13.
