### ISSUE TITLE
Strange event triggering on user management

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#5412]
### Steps to reproduce
1. Load user management after being logged in at least 30 minutes (or adjust https://github.com/nextcloud/server/blob/944738c71d0b47b26223251f942e06045ae6286e/core/js/js.js#L1664-L1664)
2. Click on the selector for group/admin group for a different user
3. Observe `Invalid quota value: "admin"`

Removing https://github.com/nextcloud/server/blob/4fa817039451982b2ff8d7f6267a2770af594ca4/settings/js/users/users.js#L165 resolves this issue.
Can someone have a look? @nextcloud/javascript

**Comment by MorrisJobke** [comment]
User management got migrated to Vue.js completely so it's unlikely that this is still the case in 14. Closing.
