### ISSUE TITLE
HTTP Range header support

### ISSUE THREAD

**Issue by arnaudmm** [nextcloud/server#5413]
Hi,

It looks like xsendfile or X-Accel-Redirect is not supported in Nextcloud (so nginx or apache could manage themself the acceptance of range header)

Is Nextcloud supposed to respect HTTP Range header ? From my point of view it's like it's totally ignoring it.

The problem is my users can't pause/resume download AND Akamai need this headers respected to work.

Any clue on that ?

Thanks

**Comment by MorrisJobke** [comment]
> Is Nextcloud supposed to respect HTTP Range header ? From my point of view it's like it's totally ignoring it.

It is supported in all WebDav resources and the PDF viewer or the music app already use that.



> The problem is my users can't pause/resume download AND Akamai need this headers respected to work.

We don't support Akamai in front of your Nextcloud because URLs are not yet unique to users and Akamai then doesn't know that there are different files for different users on the same URL.

**Comment by arnaudmm** [comment]
And what about supporting pause/resume download?

**Comment by jasonkuehl** [comment]
Is this still true that Nextcloud and Akamai are not supported?

**Comment by xpader** [comment]
Looks like it's still not supported, view big pdf file in nextcloud is horrible.

**Comment by joshtrichards** [comment]
@xpader: The PDF viewer uses Mozilla's `pdf.js`:

- https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#pdfjs-is-fetching-the-entire-pdf-file-from-a-server-can-it-fetch-only-the-required-portions-for-rendering
- https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support
- https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#what-types-of-pdf-files-are-slow-in-pdfjs-can-i-optimize-a-pdf-file-to-make-pdfjs-faster
