### ISSUE TITLE
Feature Request: Upload Videos from Nextcloud to YouTube

### ISSUE THREAD

**Issue by M2k80** [nextcloud/server#5414]
hello, i hope i am right here.

It would be very nice, if i could upload videos from nextcloud directly to my youtube account.
I dont know if that is possible or not?

i already wrote about here https://help.nextcloud.com/t/upload-from-nextcloud-to-youtube/13942

**Comment by MariusBluem** [comment]
This is more something for an separate app, which could be integrated into the Files-app ;)

**Comment by MorrisJobke** [comment]
> This is more something for an separate app, which could be integrated into the Files-app ;)

Correct. Nothing for the server component itself.
