### ISSUE TITLE
Migration script may download incompatible Nextcloud version

### ISSUE THREAD

**Issue by Morganlej** [nextcloud/server#5425]
The migration script from https://nextcloud.com/migration/ should check compatibility before downloading or doing anything else.

Example: Currently ownCloud 9.1.6 is latest point release, and corresponding Nextcloud (10.0.6) do not exist yet.

Real world issue: https://help.nextcloud.com/t/migration-from-owncloud-9-1-6-to-nextcloud-10-0-5-fails/13523

This issue is cloned from closed https://github.com/nextcloud/nextcloud.com/issues/497

linucksrox commented there:
 I also think the file that performs this check is located at /server/lib/private/Updater.php on lines 205-222.
https://github.com/nextcloud/server/blob/b4f36d44c43aac0efdc6c70ff8e46473341a9bfe/lib/private/Updater.php#L205-L222

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
There is a patch in the repo for this already.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/owncloud-web-migrator/pull/2
