### ISSUE TITLE
Synchronization Laptop/Cloud

### ISSUE THREAD

**Issue by StrangeMonkey** [nextcloud/server#5427]
Hi,

I've an isue with my synchronization.

Actually i have use the Nextcloud application for Ubuntu to synchronize one folder.
This folder is share with another user of my cloud.

In this folder i have another folders.
1. The synchronization on the cloud is good the folder "Schéma" is on my cloud since my Laptop
2. On my laptop i copy all the files in a folder "Schémas"
3. Now i have two folder "Schémas" and "Schéma"
4. On my laptop i decided to delete "Schémas" but the synchronization doesn't work

My issue : 
- On my computer the folder "Schéma" is deleted
- On my cloud the folder "Schéma" is undeletable, when i refresh the webpage it appears again...
- My desktop application notify me that it can't synchronize the folder "Schéma"

On my Nextcloud access log i had a 404 code in my log for the delete action.
On my Nextloud data-folder, in my user directory, the folder "Schéma" doesn't exists...

My collegue a deleted the folder "Schéma" on his laptop and he hasn't any problem with is synchronization...

If you had any idea or if you need any information.

### Server configuration

**Operating system**: Xubuntu 

**Web server:** Ubuntu 

**Database:** MariaDB

**PHP version:** PHP 7.0

**Nextcloud version:** 12

**Where did you install Nextcloud from:** zip from the official website (Apache tutorial)

Thank you for helping
StrangeMonkey

**Comment by M2k80** [comment]
maybe your problem is like explained here https://docs.nextcloud.com/server/9/user_manual/files/deleted_file_management.html

or try
ssh to your server and go to nextcloud folder and
sudo occ files:cleanup
sudo occ files:scan --all

**Comment by StrangeMonkey** [comment]
Thanks for answering,

I'd try your method. Now the synchronization through the app doesn't alert me of an error. 
Already the file is already in my webUI.

I'm actually reading the documentation.

If it doesn't work, i'll notify here.

StrangeMonkey

**Comment by StrangeMonkey** [comment]
After reading i can't apply any of these solutions.

Issue now : 
- Folder "Schéma" is always extisting on WebUI but not on my laptop or in my personnal data folder in the nextcloud data folder.
- Synchronizing on my laptop doesn't raise an alert 
- When deleting the folder from the WebUI, the "Schéma" folder disapear, but it is not in the trash and if i refresh the page, it reappears..

StrangeMonkey

**Comment by MorrisJobke** [comment]
cc @icewind1991 @rullzer

**Comment by skjnldsv** [comment]
@StrangeMonkey I'm guessing you found a solution now?
Things are working fine?

**Comment by MorrisJobke** [comment]
As there is no feedback since a while and we can't reproduce the issue I will close this ticket. If this is still happening please feel free to reopen.
