### ISSUE TITLE
X-Frame-Options set to Deny issues a security warning

### ISSUE THREAD

**Issue by rpadovani** [nextcloud/server#543]
If I set _X-Frame-Option_ to DENY I have the error

> The "X-Frame-Options" HTTP header is not configured to equal to "SAMEORIGIN". This is a potential security or privacy risk and we recommend adjusting this setting.

This doesn't make any sense, since DENY isn't  a security risk

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by LukasReschke** [comment]
Please use SAMEORIGIN. DENY breaks some functionality of Nextcloud and is unsupported.
