### ISSUE TITLE
Breadcrumb glitch in trashbin for sub folders

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#5431]
* delete a folder
* open trashbin view
* open this deleted folder
* expected: breadcrumbs look normale
* actual: breadcrumbs are glitchy ... the separator overlaps the folder name

<img width="655" alt="bildschirmfoto 2017-06-15 um 23 25 34" src="https://user-images.githubusercontent.com/245432/27211904-1dfd7e22-5222-11e7-9e1f-5e567f50fdf3.png">

cc @nextcloud/designers @juliushaertl @danxuliu @skjnldsv

**Comment by pixelipo** [comment]
@MorrisJobke can you please test this issue on https://github.com/nextcloud/server/pull/5229 ?

**Comment by MorrisJobke** [comment]
Indeed fixed by #7051
