### ISSUE TITLE
Nextcloud won't upload larger files

### ISSUE THREAD

**Issue by jangrimm** [nextcloud/server#5438]
### Steps to reproduce
I try to upload a file 200 MB large (not that big, thus), yet I can't get it done. Neither via nextcloud web, WebDAV nor nextcloud client. I properly set up the php.ini configuration and everything around. 

1. Install nextcloud and try to upload the file

### Expected behaviour
The file is uploaded

### Actual behaviour
Web: It uploads, but finally nothing happens. After the (upload) process, just nothing
WebDAV on Windows: I/O Device Error
Nextcloud Client: Nothing happens (the nextcloud log doesn't say anything else)

### Server configuration

**Operating system**: Deb 8

**Web server:** Plesk's apache

**Database:** mysql

**PHP version:** 7

**Nextcloud version:** (see Nextcloud admin page) latest

**Updated from an older Nextcloud/ownCloud or fresh install:** -

**Where did you install Nextcloud from:** setup.php

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** -

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** -

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by sunjam** [comment]
Hi, there is a maximum file size option under **Admin** > **Additional Settings**.  Please take a look at what it is currently set to.  Fyi, _I set mine to 2gb_.  Be sure to post back the solution if you find it. :)

Also, here is a way to upload maximum upload filesize in Apache
- vim /etc/php*/apache2/php.ini
- vim /etc/php*/apache2/php.ini
-    Find upload_max_filesize and change it (along with post_max_size)
-    Save the file
-    Restart apache2
-    Edit admin settings in NC to reflect php.ini

[Here is a link to a forum discussion about changing **Maximum File Upload** size on Nextcloud.](https://help.nextcloud.com/t/maximum-upload-size/665/6)

**Comment by benbrummer** [comment]
For Plesk use following Settings:
PHP:
Leave everything default, except:
max_execution_timem => 3600
max_input_time => 3600
open_basedir => add ":/dev/urandom:/proc/meminfo" to the end of line

Additional directives:
opcache.enable_cli=1
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=10000
opcache.memory_consumption=128
opcache.save_comments=1
opcache.revalidate_freq=1

As @sunjam mentioned change Setting under Admin > Additional Settings.

**Comment by MorrisJobke** [comment]
I assume this is fixed with the latest hints. I will close this. If there are still problems with it, please first checkout the forums for help: https://help.nextcloud.com/ because this looks more like a setup problem, than a real bug.
