### ISSUE TITLE
LDAP Integration Tests fail due to autoloader

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#544]
For example, I want to run ``/apps/user_ldap/tests/IntegrationLib/IntegrationTestAccessGroupsMatchFilter.php`` the test will fail with:

``` 
PHP Fatal error:  Class 'OCA\User_LDAP\Tests\Integration\AbstractIntegrationTest' not found in /srv/http/nextcloud/master/apps/user_ldap/tests/Integration/Lib/IntegrationTestAccessGroupsMatchFilter.php on line 31
```

I failed to figure out how the paths are constructed by the autoloader (as in have not seen where OCA stuff is registered as PSR-4 thingy):

```
[0] => /srv/http/nextcloud/master/apps/user_ldap/tests/integration/abstractintegrationtest.php
[1] => /srv/http/nextcloud/master/apps/user_ldap/lib/tests/integration/abstractintegrationtest.php
```

Anyway, to make the test run again, I need a line like

```diff
diff --git a/apps/user_ldap/tests/Integration/Lib/IntegrationTestAccessGroupsMatchFilter.php b/apps/user_ldap/tests/Integration/Lib/IntegrationTestAccessGroupsMatchFilter.php
index 4fcc833..ca89700 100644
--- a/apps/user_ldap/tests/Integration/Lib/IntegrationTestAccessGroupsMatchFilter.php
+++ b/apps/user_ldap/tests/Integration/Lib/IntegrationTestAccessGroupsMatchFilter.php
@@ -23,11 +23,12 @@
 
 namespace OCA\User_LDAP\Tests\Integration\Lib;
 
-
 use OCA\User_LDAP\Tests\Integration\AbstractIntegrationTest;
 
 require_once __DIR__  . '/../../../../../lib/base.php';
 
+\OC::$composerAutoloader->addPsr4('OCA\\User_LDAP\\Tests\\', \OC::$SERVERROOT . '/apps/user_ldap/tests/', true);
+
 class IntegrationTestAccessGroupsMatchFilter extends AbstractIntegrationTest {
 
    /**
```

in test file.

I am doubtful whether this is the best approach. Opinions, @rullzer @nickvergessen ?

**Comment by rullzer** [comment]
Do you run the using phpunit directly?

If the app is enabled it should be allowed to autoload.

**Comment by blizzz** [comment]
@rullzer not unit tests, nothing do with phpunit. Running directly from cli. App is enabled.

**Comment by nickvergessen** [comment]
Tests is only registered in phpunit:
https://github.com/nextcloud/server/blob/0215b004da6af887b3e3efa28c425d41a1c76b9b/lib/private/legacy/app.php#L172-L174

So you can also `define('PHPUNIT', true);`, or you use another constant and we add it there as well

**Comment by blizzz** [comment]
@nickvergessen this helps, thx
