### ISSUE TITLE
Avoid weird failure for missing bucket in multibucket setup

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#5445]
* having a multi bucket setup with i.e. 4 buckets
* only provision 3 of those 4 buckets (i.e bucket-0, bucket-1 and bucket-3)
* upload some files
* wait for error after upload/download because some files are uploaded into the non-existent bucket 2
* expected: no entries in the file cache (just true errors for the clients/app/web)
* actual: upload works halfway and there are ghost file cache entries to non-existent files (need to be cleaned by `occ files:scan --all`)

cc @LukasReschke @icewind1991

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
