### ISSUE TITLE
occ maintenance:repair should fix missing directories in user data directories.

### ISSUE THREAD

**Issue by JoveToo** [nextcloud/server#5446]
### Steps to reproduce
1. delete "data/user/files"
2. run occ files:scan -all -> error
3. run occ maintenance:repair
4. run occ files:scan -all -> still error

### Expected behaviour
maintenance:repair should restore obviously missing and required directories.

optionally, the core file module should restore the missing directory.

### Actual behaviour
directory is not restored and error can only be recovered from manually.

**Comment by MorrisJobke** [comment]
> delete "data/user/files"

Don't do this.



> maintenance:repair should restore obviously missing and required directories.

Not really. It repairs known bugs and not stuff that the admin randomly deletes.

**Comment by JoveToo** [comment]
> > delete "data/user/files"
>
> Don't do this.

Not deliberately, no. I am unsure how this directory got deleted, probably when I was messing around trying to get migrated from owncloud or perhaps when I was trying to get those files stored on a different logical volume. These things happen.

In any case, the result was a permissions error. I had to strace the php binary to find out that the error was thrown because the scripts tried to access a directory that didn't exist. If you don't want maintenance::repair to automatically correct such flaws, so be it but then accurate error reporting would be very helpful.
