### ISSUE TITLE
Error moving / renaming folders NC 12.0.0 (stable)

### ISSUE THREAD

**Issue by metro2030** [nextcloud/server#5448]
As reported on [forum](https://help.nextcloud.com/t/error-moving-or-renaming-folders-ncv12/13603)

Nextcloud version: 12.0.0
Operating system and version: Alpine Linux 3.6
Apache or nginx version: Nginx 1.13.1
PHP version: 7.1.5
Is this the first time you've seen this error?: No (only in 12.0.0)

Can you reliably replicate it? (If so, please outline steps):

I try to move a folder / or rename it

The issue you are facing:

Move failure / Rename failure

The output of your Nextcloud log in **Admin > Logging**:

> Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'UPDATE `oc_filecache` SET `storage` = ?, `path_hash` = MD5(CONCAT(?, SUBSTR(`path`, ?))), `path` = CONCAT(?, SUBSTR(`path`, ?)) WHERE (`storage` = ?) AND (`path` LIKE ?)' with params [4, "files\/\u0423\u043d\u0438\u0432\u0435\u0440\/3 \u043a\u0443\u0440\u0441\/_Done\/\u0424\u0438\u0437\u0440\u0430", 41, "files\/\u0423\u043d\u0438\u0432\u0435\u0440\/3 \u043a\u0443\u0440\u0441\/_Done\/\u0424\u0438\u0437\u0440\u0430", 41, 4, "files\/\u0423\u043d\u0438\u0432\u0435\u0440\/3 \u043a\u0443\u0440\u0441\/\u0424\u0438\u0437\u0440\u0430\/%"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-a94af5108d5b6274ef4dd6d5aa0c4fd7' for key 'fs_storage_path_hash'

and then

> Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'UPDATE `oc_filecache` SET `storage` = ?, `path_hash` = MD5(CONCAT(?, SUBSTR(`path`, ?))), `path` = CONCAT(?, SUBSTR(`path`, ?)) WHERE (`storage` = ?) AND (`path` LIKE ?)' with params [4, "files_trashbin\/files\/\u0424\u0438\u0437\u0440\u0430.d1496598954", 47, "files_trashbin\/files\/\u0424\u0438\u0437\u0440\u0430.d1496598954", 47, 4, "files\/\u0423\u043d\u0438\u0432\u0435\u0440\/3 \u043a\u0443\u0440\u0441\/\\_Done\/\u0424\u0438\u0437\u0440\u0430\/%"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-9c5afe57996360b82993a994e1499bb6' for key 'fs_storage_path_hash'`

The output of your config.php file in `/path/to/nextcloud` (make sure you remove any identifiable information!):
```

    <?php
    $CONFIG = array (
      'datadirectory' => '/data',
      'apps_paths' =>
      array (
        0 =>
        array (
          'path' => '/nextcloud/apps',
          'url' => '/apps',
          'writable' => false,
        ),
        1 =>
        array (
          'path' => '/apps2',
          'url' => '/apps2',
          'writable' => true,
        ),
      ),
      'instanceid' => '*value removed*',
      'passwordsalt' => '*value removed*',
      'secret' => '*value removed*',
      'trusted_domains' =>
      array (
        0 => 'cloud.*value removed*',
      ),
      'overwrite.cli.url' => 'http://cloud.*value removed*',
      'dbtype' => 'mysql',
      'version' => '12.0.0.29',
      'dbname' => 'nextcloud',
      'dbhost' => 'nextcloud-db',
      'dbport' => '',
      'dbtableprefix' => 'oc_',
      'dbuser' => '*value removed*',
      'dbpassword' => '*value removed*',
      'logtimezone' => 'Europe/Moscow',
      'installed' => true,
      'mail_from_address' => 'no-reply',
      'logdateformat' => 'Y-m-d H:i:s',
      'memcache.distributed' => '\\OC\\Memcache\\Redis',
      'memcache.locking' => '\\OC\\Memcache\\Redis',
      'memcache.local' => '\\OC\\Memcache\\APCu',
      'redis' =>
      array (
        'host' => 'redis',
        'port' => 6379,
      ),
      'mail_smtpmode' => 'smtp',
      'mail_smtpsecure' => 'tls',
      'mail_domain' => 'cloud.*value removed*',
      'mail_smtpauthtype' => 'PLAIN',
      'mail_smtpauth' => 1,
      'mail_smtphost' => 'mx.*value removed*',
      'mail_smtpport' => '587',
      'mail_smtpname' => 'no-reply@cloud.*value removed*',
      'mail_smtppassword' => '*value removed*',
      'theme' => '',
      'loglevel' => 2,
      'maintenance' => false,
    );
```

**Comment by jospoortvliet** [comment]
Filecache error, summoning @icewind1991

**Comment by carboneater** [comment]
Looks like I reported (part of) the same issue in #5477 
( I accidentally noticed that triggering it can cause this bug to happen. )

**Comment by MorrisJobke** [comment]
> Looks like I reported (part of) the same issue in #5477

Okay - let's focus on the issue there and then check if it still happens later on.

**Comment by kilosens** [comment]
same problem when renaming folder, logging appended. 
use redis for filelock and local cache

Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'UPDATE `oc_filecache` SET `storage` = ?, `path_hash` = MD5(CONCAT(?, SUBSTR(`path`, ?))), `path` = CONCAT(?, SUBSTR(`path`, ?)) WHERE (`storage` = ?) AND (`path` LIKE ?)' with params [3, "files_trashbin\/files\/\u6b27\u6bd4\u7279\u8ba1\u7b97\u673a\u534f\u8bae.d1503742634", 41, "files_trashbin\/files\/\u6b27\u6bd4\u7279\u8ba1\u7b97\u673a\u534f\u8bae.d1503742634", 41, 3, "files\/\u6b27\u6bd4\u7279\/\u6b27\u6bd4\u7279\u8ba1\u7b97\u673a\u534f\u8bae\/%"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-808090c5f7c1f9e1bd39a0636513e7b5' for key 'fs_storage_path_hash'

    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 128: Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - line 1015: Doctrine\DBAL\DBALException driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'UPDATE `oc_file...', Array)
    /var/www/nextcloud/lib/private/DB/Connection.php - line 213: Doctrine\DBAL\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)
    /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php - line 208: OC\DB\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)
    /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 213: Doctrine\DBAL\Query\QueryBuilder->execute()
    /var/www/nextcloud/lib/private/Files/Cache/Cache.php - line 545: OC\DB\QueryBuilder\QueryBuilder->execute()
    /var/www/nextcloud/lib/private/Files/Cache/Cache.php - line 484: OC\Files\Cache\Cache->moveFromCache(Object(OC\Files\Cache\HomeCache), 'files/\xE6\xAC\xA7\xE6\xAF\x94\xE7\x89\xB9...', 'files_trashbin/...')
    /var/www/nextcloud/lib/private/Files/Cache/Wrapper/CacheWrapper.php - line 188: OC\Files\Cache\Cache->move('files/\xE6\xAC\xA7\xE6\xAF\x94\xE7\x89\xB9...', 'files_trashbin/...')
    /var/www/nextcloud/lib/private/Files/Cache/Updater.php - line 196: OC\Files\Cache\Wrapper\CacheWrapper->move('files/\xE6\xAC\xA7\xE6\xAF\x94\xE7\x89\xB9...', 'files_trashbin/...')
    /var/www/nextcloud/apps/files_trashbin/lib/Trashbin.php - line 267: OC\Files\Cache\Updater->renameFromStorage(Object(OCA\FilesAccessControl\StorageWrapper), 'files/\xE6\xAC\xA7\xE6\xAF\x94\xE7\x89\xB9...', 'files_trashbin/...')
    /var/www/nextcloud/apps/files_trashbin/lib/Storage.php - line 247: OCA\Files_Trashbin\Trashbin move2trash('\xE6\xAC\xA7\xE6\xAF\x94\xE7\x89\xB9/\xE6\xAC\xA7\xE6\xAF...', false)
    /var/www/nextcloud/apps/files_trashbin/lib/Storage.php - line 189: OCA\Files_Trashbin\Storage->doDelete('files/\xE6\xAC\xA7\xE6\xAF\x94\xE7\x89\xB9...', 'rmdir')
    /var/www/nextcloud/apps/files_accesscontrol/lib/StorageWrapper.php - line 73: OCA\Files_Trashbin\Storage->rmdir('files/\xE6\xAC\xA7\xE6\xAF\x94\xE7\x89\xB9...')
    /var/www/nextcloud/lib/private/Files/View.php - line 1132: OCA\FilesAccessControl\StorageWrapper->rmdir('files/\xE6\xAC\xA7\xE6\xAF\x94\xE7\x89\xB9...')
    /var/www/nextcloud/lib/private/Files/View.php - line 348: OC\Files\View->basicOperation('rmdir', '/\xE6\xAC\xA7\xE6\xAF\x94\xE7\x89\xB9/\xE6\xAC\xA7\xE6...', Array)
    /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 303: OC\Files\View->rmdir('/\xE6\xAC\xA7\xE6\xAF\x94\xE7\x89\xB9/\xE6\xAC\xA7\xE6...')
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php - line 179: OCA\DAV\Connector\Sabre\Directory->delete()
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 287: Sabre\DAV\Tree->delete('\xE6\xAC\xA7\xE6\xAF\x94\xE7\x89\xB9/\xE6\xAC\xA7\xE6\xAF...')
    [internal function] Sabre\DAV\CorePlugin->httpDelete(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method DELETE', Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 71: Sabre\DAV\Server->exec()
    /var/www/nextcloud/remote.php - line 162: require_once('/var/www/nextcl...')
    {main}

**Comment by jospoortvliet** [comment]
@kilosens - 12.0.2? If not, it is most likely fixed there.

**Comment by kilosens** [comment]
@jospoortvliet thanks, just update to 12.0.2, it seems no longer appear.
