### ISSUE TITLE
OCR all images without changing image files

### ISSUE THREAD

**Issue by thibaultmol** [nextcloud/server#545]
Hi,

I'm used to using Google Drive and a really nice feature is having all your image files being OCR'ed in the background without actually changing the files.
If I have a JPG with the word Decathlon on it somewhere, I can just search in Google Drive for Decathlon and it'll find it. Is this possible in Nextcloud without actually changing any files like in Google Drive?

Thanks!
Thibault

**Comment by MorrisJobke** [comment]
This should be implemented as a separate app and not in the server's core component.
