### ISSUE TITLE
Shared calendars not visible by default

### ISSUE THREAD

**Issue by tom-georg** [nextcloud/server#5451]
My organisation shares a calendar with very important entries.  However whenever a normal member (not admin) clicks on his calendar app, that shared calendar is not visible by default. 

Every employee always needs to click the shared calendar to make it visible. Since people are likely to forget clicking there, they miss important dates.
### Steps to reproduce
1. Create a calendar
2. Share the calendar
3. The calendar needs to be activated every time a user clicks on the shared calendar.

### Expected behaviour
Once clicked on, a calendar should always be visible.

### Actual behaviour
Every time you click on your calendar app, the shared calendar is not visible.

**Comment by MorrisJobke** [comment]
Could you please report this in https://github.com/nextcloud/calendar/issues

cc @georgehrke for some triage

**Comment by georgehrke** [comment]
As Morris said, please report it in the calendar repo and please use the full issue template.
You didn't even tell us what Nextcloud / calendar version you use ;)

**Comment by georgehrke** [comment]
(and please add more detailed reproduction information. is it a group or a user share? is it read-write or read-only?)
