### ISSUE TITLE
Issue with custom datadirectory for admin user

### ISSUE THREAD

**Issue by rev138** [nextcloud/server#5453]
### Steps to reproduce
1. configure a non-standard datadirectory in config.php
2. log in as 'admin'
3. Try to upload a file or open one of the files from skeleton

### Expected behaviour
Uploads should work, all files shown should be accessible.

### Actual behaviour
Looking on the filesystem, the files from skeleton seem to be copied to [nextcloud root]/data/admin/files, not the [custom datadirectory]/admin/files

The  skeleton files are visible in the Files app, but NC complains they don't exist if you try to open them. Also, trying to upload a file fails with "Forbidden".

If you create a new folder, this works, and you can upload new files and upload them as normal. The uploaded files go to [custom datadirectory]/admin/files like one would expect. The files in [nextcloud root]/data/admin/files remain visible but inaccessible.

If I create a new user and log in, their skeleton files are copied to [custom datadirectory]/admin/files and can be accessed normally. This seems to only occur with the automaticall created 'admin' user.

### Server configuration

**Operating system**: Debian jessie

**Web server:** Nginx 1.6.2

**Database:** Mariadb 10

**PHP version:** 5.7

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Where did you install Nextcloud from:** Official tarball

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - calendar: 1.5.3
  - circles: 0.10.0
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.4
  - files_automatedtagging: 1.2.2
  - files_pdfviewer: 1.1.1
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - groupfolders: 1.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ojsxc: 3.2.1
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - richdocuments: 1.12.33
  - serverinfo: 1.2.0
  - spreed: 2.0.1
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - files_external
  - firstrunwizard
  - sharebymail
  - survey_client
  - updatenotification
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "trusted_domains": [
            "gibber.test",
            "example.onion"
        ],
        "datadirectory": "\/opt\/nextcloud-data",
        "skeletondirectory": "\/opt\/nextcloud-data\/skeleton_files",
        "enable_previews": true,
        "token_auth_enforced": true,
        "filelocking.enabled": true,
        "updatechecker": false,
        "upgrade.disable-web": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "redis",
            "port": 6379
        },
        "enabledPreviewProviders": [
            "OC\\Preview\\Image"
        ],
        "htaccess.RewriteBase": "\/",
        "mail_smtpmode": "smtp",
        "mail_smtpauth": false,
        "mail_from_address": "no-reply",
        "mail_domain": "gibber.test",
        "mail_smtphost": "postfix",
        "mail_smtpport": "25",
        "theme": "pancrypticon",
        "default_language": "en",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "mariadb",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "occv4vsp8h13"
    }
}
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome 56

**Operating system:** Fedora 25

#### Web server error log
<details>
<summary>Web server error log</summary>
Logs disabled
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"Zy6yMMMGMytgF2fCt8Md","level":4,"time":"2017-06-18T01:00:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"--","url":"--","message":"Not installed","userAgent":"--","version":""}
{"reqId":"UIuVNVUmhhv9u6eqLz4G","level":3,"time":"2017-06-18T01:10:02+00:00","remoteAddr":"172.18.0.8","user":"admin","app":"PHP","method":"POST","url":"\/heartbeat","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/59.0.3071.86 Safari\/537.36","version":"12.0.0.29"}
{"reqId":"JR5aZ4hymu0p7BXj5u2h","level":3,"time":"2017-06-18T01:22:03+00:00","remoteAddr":"172.18.0.8","user":"test","app":"PHP","method":"POST","url":"\/heartbeat","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/59.0.3071.86 Safari\/537.36","version":"12.0.0.29"}
</details>

**Comment by jospoortvliet** [comment]
Did you already log in as Admin? The thing is, changing the data directory AFTER installation isn't supported... Well, you can try, but you get issues like the one you describe.

https://help.nextcloud.com/t/is-there-a-safe-and-reliable-way-to-move-data-directory-out-of-web-root/3642/4 for example.

It isn't impossible, but you have to modify the database:

1. Make sure no cron job is running anymore
2. Stop apache
3. Move dir
4. Change config entry
5. In oc_storages change the path on the local::/old-data-dir/ entry
6. Restart apache

And it is still a hack ;-)

If you did install your system fresh and before logging in the first time already had this problem, reopen please!

**Comment by rev138** [comment]
This is from a fresh install, without modifying the config after login. Thanks.

**Comment by peturbg** [comment]
rev138 i see that you are with old version of debian. there is debian 9, with all bug fix, i have http2 and nextcloud works in http2, it could help include make fast transport. so update to debian 9 and try agin. when i was on debian 8.8 there was problems with nextcloud, include mysql, bevouse debian 8.8 come with old mysql version.  goodluck man
