### ISSUE TITLE
Safari : network connection was lost

### ISSUE THREAD

**Issue by oliverpool** [nextcloud/server#5454]
### Steps to reproduce
1. Setup a nextcloud (12.0.0) instance on an ovh "pro hosting" (https://www.ovh.de/hosting/hosting-pro.xml)
2. Visit the login URL with safari (on iOS 10.3.2 for iPhone)

### Expected behaviour

Login page should be displayed

### Actual behaviour

```
Safari cannot open the page because the network connection was lost
```

However if I visit an non existing page (`/404` for instance), I see the nextcloud 404 page.

### Investigations

It works fine with Chromium on Linux.

The `login` page headers contain `Content-Length` (and no `Transfer-Encoding:chunked`).
The `404` page headers contain `Transfer-Encoding:chunked` (and no `Content-Length`).

When requesting the `login` page with cURL, it indicates at the end 
```
curl: (18) transfer closed with 7453 bytes remaining to read
```
No such warning is reported on the `404` page

---

### Server configuration

Taken from: http://cluster020.hosting.ovh.net/infos/

**Operating system: Linux**

**Web server: Apache/2.2.22**

**Database: Mysql**

**PHP version: 7.1.1**

**Nextcloud version: 12.0.0**

**Updated from an older Nextcloud install**

**Where did you install Nextcloud from: manual update method**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have 
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - news: 11.0.5
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - firstrunwizard
  - survey_client
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocob0062v4da",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.pfad.fr"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.pfad.fr",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_domain": "pfad.fr",
        "mail_from_address": "oliverpool",
        "mail_smtpmode": "php",
        "updater.release.channel": "stable"
    }
}
```
</details>

**Are you using external storage: no**

**Are you using encryption:** no

**Are you using an external user-backend: no**

### Client configuration
**Browser: Safari**

**Operating system: iOS10.3.2 on iPhone SE**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
XXX.XXX.XXX.XXX cloud.pfad.fr - [18/Jun/2017:10:30:58 +0200] "GET /index.php/login HTTP/1.1" 200 1894 "-" "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like Mac OS X) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.0 Mobile/14F89 Safari/602.1"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Nothing relevent
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Safari cannot open the page because the network connection was lost
```
</details>

**Comment by peturbg** [comment]
hmmmm safari, maybe this is ssl certificate problem. what kind version of linux you have. mysql, php7.1.1, strange, did you compile php 7.1.1, for mysql what version is, in debian jessie there is much problems, jessir has old packages and when you need something new it just dont work  becouse debian has old packages. now i have http2 active. i have comouter with ubuntu 17.04 and today i see curl -V and it comment http2 dont exist, why ubuntu 17.04 it more new than debian 9 and ubuntu just dont want to have curl http2 support but debian 9 has curl, but ubuntu 17.04 it the same version with debian 9 and ubuntu has prohibited, forbidden to compile http2. goodluck man, and update to the new versions, i dont know why, peoples do programs and they works on the old computer, when updates come the developers make programs and remove the older working for the olders comouters this is bad, becouse if developers make new program developers need to g

**Comment by oliverpool** [comment]
I found a workaround by modifying the `.htaccess`. I added the following line at the end:

```
Header always unset Content-Length
```
