### ISSUE TITLE
only want to thanks and read the above text

### ISSUE THREAD

**Issue by peturbg** [nextcloud/server#5455]
i jist wsnt to say thanks. i just enable http2 and it was great it just works. nextcloud for android just sucks, 1.4.3 you have to put more things.  i just confugure ssl to works with 384 bytes, but i cant get it to works with blowfish. i yes i just remember i has issue that something happends with the songs on cyrilic i have enable cyrilix but it dont work. guys i just remember, when i open nextcloud on android and choose for example photo.jpg it download and syncronize the inage on the mobile phone, for that i stop to use nextcloud for android. so now when a person open some file, nextcloud need to ask him if he want to download and sync, now in nextcloud for android there will be peoples who want to press on file download and sync, for that put in nextcloud android a bytton for who want to choose when pres on some file what automaticaly to do nextcloud to dont download or to autonagicaly download. now if you have 30 mb. pdf and you are on mobile internet and you just need to see this 30 mb. pdf nextcloud will download this 30 mb. and if you have data plan with 2 gb. it will go fast. now if all humankind have unlimited internet and free, then i like to download 30 mb. but when there is internet data plan, it will robbee your internet data. when you just need to see 1 page or 2 pages from this 30 mb. pdf. this is for now thanks guys

**Comment by MorrisJobke** [comment]
Hi @peturbg 

those are 5 different issues in one. Also splitting up PDFs to save download volume is not that easy.

I will close this ticket - please open separate tickets for the issues with a clear user story. And for the SSL issue I would ask you to go to the forums and ask for help there: https://help.nextcloud.com
