### ISSUE TITLE
Can't play MP4 video in MiuiBrowser

### ISSUE THREAD

**Issue by yp05327** [nextcloud/server#5467]
I'm sorry to ask this question,but I really want to know why this happened.

I can't play MP4 video in Miui's (XiaoMi cellphone's ROM, it's Android) default browser, it always shows "The video could not be loaded, either because the server or network failed or because the format is not supported", then I try to play the same video in Safari(iPad) and Chrome(another cellphone, not Miui but Android), these two plays well.
Then I search for the answer, finally I find a website: http://php.weilomo.com/html/index.html
(from https://github.com/videojs/video.js/issues/2945)
The cellphone running Miui can play the MP4 video of this website, so I think this problem isn't caused by  "the format is not supported" probably or nextcloud and this website uses different decoder.

So I open this issues.

### Steps to reproduce
1. upload a mp4 video
2. open the mp4 video in the Miui's default browser

###Behaviour
It will show "The video could not be loaded, either because the server or network failed or because the format is not supported"
there are two images:
https://github.com/yp05327/images/blob/master/111.jpg
https://github.com/yp05327/images/blob/master/222.jpg

### Server configuration

**Operating system**: Ubuntu/Linaro 4.9.4-2ubuntu1~16.04

**Web server**: Apache/2.4.18 (Ubuntu)

**Database**: mysqld 5.7.18-0ubuntu0.16.04.1

**PHP version**: PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )

**Nextcloud version**: 11.0.3 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install**: from 11.0.2

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

### Client configuration
**Browser:** Miui's default browser v8.5.14

**Operating system:** Miui 8.2.1.0 

#### Web server access log
The name of video is too long, so I cahnged to xxxxx.mp4.
Miui Browser:
"GET /remote.php/webdav/xxxxx.mp4 HTTP/1.1" 503 4426 "-" "Mozilla/5.0 (Linux; Android 4.4.4; HM NOTE 1LTE Build/KTU84P; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.146 Mobile Safari/537.36"

Safari on Mac(This can play so it is the right log I think):
"GET /remote.php/webdav/xxxxx.mp4 HTTP/1.1" 206 1364 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4"
"GET /remote.php/webdav/xxxxx.mp4 HTTP/1.1" 206 93401 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4"
"GET /remote.php/webdav/xxxxx.mp4 HTTP/1.1" 206 93545 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4"
"GET /remote.php/webdav/xxxxx.mp4 HTTP/1.1" 206 1292034 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4"
"GET /remote.php/webdav/xxxxx.mp4 HTTP/1.1" 206 842161 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4"
"PROPFIND /remote.php/webdav/%E6%97%A5%E5%89%A7%20%E7%95%AA%E7%BB%84/%E6%88%91%E6%98%AF%E4%BD%A0%E7%9A%84%E5%91%BD%E4%B8%AD%E6%B3%A8%E5%AE%9A HTTP/1.1" 207 13176 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4"
"GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F%E6%97%A5%E5%89%A7%20%E7%95%AA%E7%BB%84%2F%E6%88%91%E6%98%AF%E4%BD%A0%E7%9A%84%E5%91%BD%E4%B8%AD%E6%B3%A8%E5%AE%9A HTTP/1.1" 200 1169 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4"
"GET /remote.php/webdav/xxxxx.mp4 HTTP/1.1" 206 109473 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4"

#### Nextcloud log (data/nextcloud.log)
no strange log(I use a new account to test this issue, and there's no log of this account in data/nextcloud.log)

#### Browser log
Sorry, I don't know how to get this browser's log.

**Comment by Schmuuu** [comment]
Hi,

I'm using the audio-player app and having this app enabled, I have an audio-player section under my personal settings (your.domain.com/settings/personal)
This section contains a part: "Your browser supports the following file formats: ..."
For me there is mp4 listed as supported for the different browser I use, and I can actually view mp4 files directly on my server. So this could be a good hint. If it doesn't list mp4 there, but below under "not supported file formats", there is a higher chance, that it is actually the browser having this problem.
However if mp4 format is listed as supported but still doesn't play, it could be the used codec used in that video.

**Comment by yp05327** [comment]
@Schmuuu 
Thanks for your comment.

First, I found my personal settings url is domain.com/index.php/settings/personal, and if visit  domain.com/settings, the server will show the file list of (root of nextcloud)/settings, this is bad. I don't know whether it is a bug or just because of the wrong web server config.(my config is Options FollowSymlinks, I think it should not show the file list, but it shows, so strange.)

Next, I have installed audio-player and enabled, version is 1.5.1, but I can't found "Your browser supports the following file formats: ..."

This is all of them:

> Audio Player
> 
> Search for audio files in :  
> This setting specifies which folder is scanned for audio files. Without a selection, the whole data folder is scanned.
> To exclude a folder, you have to create a .noaudio file inside that folder. This is also necessary in subfolders, to exclude them.
> 
> Cyrillic Support:  
> Activate this setting if cyrillic characters are not recognized correctly. This makes the indexing slower!
> Read more

**Comment by MorrisJobke** [comment]
> The cellphone running Miui can play the MP4 video of this website, so I think this problem isn't caused by "the format is not supported" probably or nextcloud and this website uses different decoder.

Please download this video and test it on your Nextcloud instances as well. MP4 is only the container format and it could contain videos of different codecs. So I guess the problem is that the codec is not properly supported.

If chrome and safari plays the video just well it is also not a problem of Nextcloud but of the browser.

**Comment by aohanhongzhi** [comment]
I can play the video on the browser such as chrome foxfire.but I can't download any video from nextcloud.
when I play video on app,video will be download first,then will be play normally.but I found the video file in my file explorer ，but I can't open it in my player.I upload the mp4 from my phone ,then I download it from nextcloud ,but I can't play it with my player.I guess the video file format has been changed.how to solve the problem?
