### ISSUE TITLE
PDF Viewer cannot display PDF document out of search result list (JPEG is working fine)

### ISSUE THREAD

**Issue by Chingato** [nextcloud/server#5468]
If I try to open a PDF document out of the search result the PDF cannot be displayed. It only works if the search is started from within the folder where the PDF is located.
For JPG document the search and display action is working fine. The search index is created by Nextant and a local running Solr

Displayed error:
***PDF.js Version 1.4.20 (build: b15f335)***
***Nachricht: Missing PDF "http://192.168.253.22/cloud/remote.php/webdav/test.pdf".***

### Steps to reproduce
1. Upload a PDF document with text layer to a subfolder below the root hierarchy
2. Wait until it is indexed for fulltext search
3. start the search from within the root folder
4. Click on the document within the search result list
5. PDF document cannot be displayed -> **error message is displayed**

------

6. Start the search from within the folder where the PDF document is located
7. click on the PDF document within the search result list
8. PDF is displayed correctly

### Expected behaviour
The identified PDF document should be displayed independently from which folder the user started the search.

### Actual behaviour
The PDF document is only displayed (out of the search result list) if the search has been started while the user is already within the folder where the PDF document is located.

The issue only occurs with PDF documents. JPG documents are working and can be displayed out of the search result list independently from the folder from where the user started the search.

**Displayed** error message:**
`PDF.js Version 1.4.20 (build: b15f335)
Nachricht: Missing PDF "http://192.168.253.22/cloud/remote.php/webdav/test.pdf".`

### Server configuration

**Operating system**:
Debian 8 (Jessie) - basis is OSMC media center derivative

**Web server:**
Apache/2.4.10 (Debian) 

**Database:**
10.0.30-0+deb8u2

**PHP version:**
7.0.19-1 (cli)

**Nextcloud version:** (see Nextcloud admin page)
12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh installation

**Where did you install Nextcloud from:**
from the ZIP file that can be downloaded

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
`No errors have been found.`

**List of activated apps:**
 Activity
2.5.2
 
Collaborative tags
1.2.0
 
Comments
1.2.0
 
Deleted files
1.2.0
 
Federation
1.2.0
 
File sharing
1.4.0
 
First run wizard
2.1
 
Gallery
17.0.0
 

Log Reader
2.0.0
 

Monitoring
1.2.0
 

Nextcloud announcements
1.1
 
Notifications
2.0.0
 
Password policy
1.2.2
 

PDF viewer
1.1.1
 

Share by mail
1.2.0
 
Text editor
2.4.1
 

Theming
1.3.0
 
Update notification
1.2.0
 

Usage survey
1.0.0
 

Versions
1.5.0
 
Video player
1.1.0
 

Brute-force settings
1.0.2

Files automated tagging
1.2.2

Nextant
1.0.8

Retention
1.1.2

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_automatedtagging: 1.2.2
  - files_pdfviewer: 1.1.1
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextant: 1.0.8
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.253.22",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/opt\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/192.168.253.22\/cloud",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": "0",
        "logdateformat": "F d, Y H:i:s"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.5.2",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "22"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.0.2",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "logging"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1496562303.4744",
            "lastcron": "1497891604",
            "lastupdateResult": "[]",
            "lastupdatedat": "1497891422",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "scss.variables": "26d45a3be5c8771d91b6fb7e1cfca089",
            "vendor": "nextcloud"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.7.2",
            "types": "filesystem"
        },
        "files_automatedtagging": {
            "enabled": "yes",
            "installed_version": "1.2.2",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_retention": {
            "enabled": "yes",
            "installed_version": "1.1.2",
            "types": "filesystem"
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.4.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.1",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "17.0.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "authentication"
        },
        "nextant": {
            "configured": "1",
            "enabled": "yes",
            "index_bookmarks_last": "1497824104",
            "index_bookmarks_needed": "0",
            "index_delay_max": "2",
            "index_delay_min": "1",
            "index_files_filters_audio": "0",
            "index_files_filters_extensions": ".csv",
            "index_files_filters_image": "1",
            "index_files_filters_office": "1",
            "index_files_filters_pdf": "1",
            "index_files_filters_text": "1",
            "index_files_last": "1497852014",
            "index_files_needed": "0",
            "index_live": "2",
            "index_locked": "0",
            "installed_version": "1.0.8",
            "resource_level": "2",
            "solr_core": "nextant",
            "solr_timeout": "30",
            "solr_url": "http:\/\/127.0.0.1:8983\/solr\/",
            "types": "filesystem",
            "use_cron": "1"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.1",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.0.5",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.2.2",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "prevent_group_restriction"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "logging"
        },
        "theming": {
            "backgroundMime": "image\/jpeg",
            "cachebuster": "5",
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "notify_groups": "[]",
            "types": "",
            "update_check_errors": "0"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        }
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No, only local storage

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox 54
Google Chrome 58

**Operating system:**
Windows 10

#### Nextcloud log (data/nextcloud.log)

> {"reqId":"Zqbzlal2z7czDsIjwj2s","level":0,"time":"June 19, 2017 17:19:09","remoteAddr":"192.168.253.35","user":"Tom","app":"webdav","method":"GET","url":"\/cloud\/remote.php\/webdav\/test.pdf","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 File with name test.pdf could not be located\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(81): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('test...')\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/html\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(71): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/html\\\/cloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/html\\\/c...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/ObjectTree.php\",\"Line\":173,\"User\":\"Tom\"}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/58.0.3029.110 Safari\/537.36","version":"12.0.0.29"}

**Comment by Chingato** [comment]
wx56 reported a very similar issue:
https://help.nextcloud.com/t/pdf-cannot-be-opened-out-of-the-search-result-list-error-message-missing-pdf/14178/3

But on standaard Nextcloud, not using Nextant.
Nextcloud 12.0.0 on Raspbian GNU/Linux 8 (jessie)

    create a pdf file in a sub-directory under root
    click it ... and it opens fine
    put a tag T on it
    go the home dir and search by tag for the tag T
    pdf is found, but when clicked on, the pdf is not shown with a similar error
    check: go to the subdir and click on the pdf and it wil show correctly

Somewhere the notion of the existence of the subdir is lost when trying to open the pdf from the tag search result list.

The file is at
https://myserver.lan/remote.php/webdav/Administratie/magweg05.pdf

The error is
PDF.js v1.4.20 (build: b15f335)
Message: Missing PDF "https://myserver.lan/remote.php/webdav/magweg05.pdf".

**Comment by daita** [comment]
https://github.com/nextcloud/files_pdfviewer/pull/33

**Comment by MorrisJobke** [comment]
> nextcloud/files_pdfviewer#33

Fixed with that PR

**Comment by m4ntic0r** [comment]
updated nextcloud to 12.0.1 and problem is gone!
