### ISSUE TITLE
mount.cifs as data directory

### ISSUE THREAD

**Issue by Speedy1991** [nextcloud/server#5471]
Just a question:

Are there any disadvantages using a mounted cifs folder as root data path?

I have a StorageBox with following setup:

`<username>.domain.com/<remote_folder> <local_folder>      cifs    iocharset=utf8,rw,credentials=<credentialsfile>,uid=<uid>,gid=<gid>,file_mode=0660,dir_mode=0770 0       0`

E.g.: `'datadirectory' => '<local_folder>'`

**Comment by benyanke** [comment]
Would permissions be an issue? This seems like NFS would be a better candidate for this sort of situation.

Other than permissions, it seems it would probably work fine

**Comment by Speedy1991** [comment]
My Hosting Provider doesn't support NFS, only FTPS, SCP, SAMBA, CIFS, WebDAV. I think CIFS is the best case in this scenario. But if there is a good reason i can change this :)

**Comment by e-alfred** [comment]
This question seems far more appropriate for https://help.nextcloud.com?

**Comment by MorrisJobke** [comment]
> This question seems far more appropriate for https://help.nextcloud.com?

Correct.

Mounting on any filesystem on the operating system level shouldn't be a problem in general.
