### ISSUE TITLE
Add the filename to the share link

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#5475]
When sharing a file by link it maybe is useful to add the filename to the link itself. Just to better identify what is behind this link. I think it doesn't even need to have an impact on the actual sharing, but should just help to identify the content if you only have the links.

Something like 

* https://cloud.example.org/s/lc3cANiTLMXfgzo#test.avi
* https://cloud.example.org/s/lc3cANiTLMXfgzo#expenses.docx

@nextcloud/designers @nextcloud/sharing What do you think?

**Comment by enoch85** [comment]
Just the file ending in case the file name is very long (it would make a long link name).

**Comment by MorrisJobke** [comment]
> Just the file ending in case the file name is very long (it would make a long link name).

We could also ellipsize:  https://cloud.example.org/s/lc3cANiTLMXfgzo#this is a long file... .docx

**Comment by MorrisJobke** [comment]
> We could also ellipsize: https://cloud.example.org/s/lc3cANiTLMXfgzo#this-is-a-long-file....docx

And of course replace all non-native URL characters with nothing and spaces with dashes.

**Comment by enoch85** [comment]
@MorrisJobke Yes, that's an option indeed.

**Comment by patschi** [comment]
I'd personally prefer using `/´ instead of the `#` symbol: (while making the filename optional)
https://cloud.example.org/s/qyMiz3koTqYIQoS/nextcloud-12.zip
https://cloud.example.org/s/qyMiz3koTqYIQoS/download/nextcloud-12.zip

* Looks better IMHO
* Works better when downloading file directly using `wget` by using the direct download link:
  * some CLIs probably may not like the `#`
  * `wget` or `curl` may correctly interpret the appending filename, because it's part of the URL

**Comment by jancborchardt** [comment]
Agree with @MorrisJobke and @patschi – adding the filename is good, but it should always be optional. That is, links without it shouldn’t break, or when the file is renamed.

**Comment by MorrisJobke** [comment]
> Agree with @MorrisJobke and @patschi – adding the filename is good, but it should always be optional. That is, links without it shouldn’t break, or when the file is renamed.

Correct. And using the anchor this will not have any effect.

**Comment by rullzer** [comment]
Sure..

I'd go for the anchor. As indeed lets not fuck with the routes. Also we already set the content disposition header. Using <url>/download/Long...filename.txt I do not want something downloaded as that.

'Simplest' would be I guess to extend the shareAPI. Right now there is the URL attribute there. Just adding it there would work. Altough it would then force everybody to use it.

**Comment by skjnldsv** [comment]
And much easier to implement! ^^

**Comment by schiessle** [comment]
Is it a real problem we are trying to solve here. I'm not against it in general. But I fear that once we show the filename people will complain that the link contain the old file name after renaming the file.

Just want to avoid to creating more problems, user wishes and complexity in the long run without a need.

**Comment by MariusBluem** [comment]
For sharing reasons, links should be as short as possible 🤔 It should make no difference what is behind the anchor# ... after a filename has changed, the anchor should be changed too 😉

**Comment by jancborchardt** [comment]
The problem we’re trying to solve is having the link be a bit more transparent as to what hides behind it.

A certain competitor called Dropbox also does that, and it’s a nice thoughtful enhancement.

**Comment by mahnunchik** [comment]
Just a copy from #6463

> Make links to image/file preview portable between tabs or users.

### Steps to reproduce
1. Open image in shared folder. Url will be like following: `http://example.com/index.php/apps/files/?dir=/test&fileid=100#/test/Layout.png`
2. Copy link.
3. Open in different tab or under another user that has access to the folder.

### Expected behaviour
Image preview opens.

### Actual behaviour
File listing opens.

**Comment by rullzer** [comment]
@skjnldsv just fix it! :wink:

**Comment by sergeych** [comment]
So, after a year, is there any way to make direct download links that will save to either source file name or some other file name? Or we have to look for alternatives?

**Comment by MorrisJobke** [comment]
Most likely nothing for 14 -> moving to 15.

**Comment by biva** [comment]
Hello, 
Regarding this debate, I think this app is very interesting: https://github.com/LazyShpee/sharerenamer

> This is an add-in to the Files app, which allows you to customize your share tokens, so your links can be https://cloud.ex/s/bachelorparty instead of https://cloud.ex/s/qPv1SwbU5M2YEoJZ. Just share a file or folder (or click an already shared one) and a new button will appear below the share link URL in the sidebar of the Files app.

I like this approach. @LazyShpee do you plan to make a version for NC14?

**Comment by biva** [comment]
FYI, and thanks to Alfred in https://help.nextcloud.com/t/nextcloud-url-shortener/10855/7, I found this wonderful app, available under Tools in the Nextcloud app store: https://apps.nextcloud.com/apps/sharerenamer and https://github.com/DecaTec/sharerenamer

**Comment by jancborchardt** [comment]
@biva that is indeed nice, but a different topic. :)

**Comment by Papyruse** [comment]
Any update about this feature ?

**Comment by jancborchardt** [comment]
@Papyruse if there’s any updates on any issue, the issues will be updated. :) Currently no one is working on it and anyone is welcome to pick this up.

**Comment by hwalinga** [comment]
Just a FYI for the people in this thread, but this feature is removed again in the latest version of Nextcoud and there is no intention to bring it back: https://github.com/nextcloud/server/issues/53761
