### ISSUE TITLE
Contact import fails silently on OS X

### ISSUE THREAD

**Issue by dhowe** [nextcloud/server#5478]
### Steps to reproduce
1. Export contacts as .vcf file in OS X contacts app
2. Go to nextcloud contacts, settings, and try to import

### Expected behaviour
Contacts are imported

### Actual behaviour
Nothing. Blank screen

### Server configuration

**Operating system**: ubuntu 16.04

**Web server:** apache

**Database:** MySql

**PHP version:** 7

**Nextcloud version:** 12

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/

**Signing status:** checked sha256

<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "ldap" namespace.     

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** Chromium

**Operating system:** OSX 10.10.5

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
cc @georgehrke

**Comment by memen45** [comment]
Same issue here. Exported from Android 6.0 phone to a .vcf file of about 60 kB and ~240 contacts. Imported the same way as ts. Left panel keeps loading forever, while opening a new tab does not show any contacts at all.

Nextcloud server version: 12.03

**Comment by skjnldsv** [comment]
Closign as this is an old one and we have fixed/changed this on the 3.x version already
