### ISSUE TITLE
Wish: create users with an email address rather than an initial password

### ISSUE THREAD

**Issue by FlorentBecker** [nextcloud/server#5481]
When creating users in the "users" menu, as an administrator, it would be more ergonomic if, instead of setting their initial password, I could set their email address. Nextcloud would then send them an invitation mail with an activation link like the one in password reminder emails. That way,
* as an administrator, I don't need to select a password for my users
* no user is created without an email address, so all can ask for a password reminder if they need
* users don't need to go to the preferences to set their email address and change their password

**Comment by sf-janz** [comment]
This is already implemented. Check the "Settings" Dialog in the User section:
![Screenshot](https://i.imgur.com/XbyD9UQ.png)

**Comment by FlorentBecker** [comment]
Thanks, sorry for the noise
