### ISSUE TITLE
broken Sync with IOS App PDF Expert

### ISSUE THREAD

**Issue by critzinger** [nextcloud/server#5486]
Hello everybody,

We have been using the IOS App PDF Expert for a long time to synchronize with our Nextcloud.
Up to version 11.0.3 there were no problems.

After an update to version 12.0.0 we now have the following problem.

Pdf files are recognized as folders and can not be opened.

Up to version 11.0.3 it worked without problems.

There were some changes in version 12.0.0 in the webdav server side

Do you have any solution for me?

### Steps to reproduce
1. Sync PDF Files with IOS App PDF Expert
2. in PDF Expert PDF Files recognized as folder
3. open pdf files over webdav sync with PDF Expert fails

### Expected behaviour
1. Sync PDF Files with IOS App PDF Expert
2. in PDF Expert PDF Files recognized as PDF Documents
3. open pdf files over webdav sync with PDF Expert success

### Actual behaviour
1. Sync PDF Files with IOS App PDF Expert
2. in PDF Expert PDF Files recognized as folder
3. open pdf files over webdav sync with PDF Expert fails

### Server configuration

**Operating system**: Debian 8

**Web server:** apache 2.4

**Database:** mysql

**PHP version:** 7

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** update from 11.0.3

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/

<details>
<summary>Signing status</summary>
No errors have been found.

</details>

<details>
<summary>App list</summary>

Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_trashbin: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextant: 1.0.8
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx.de"
        ],
        "datadirectory": "\/var\/www\/html\/owncloud\/data",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "de",
        "activity_expire_days": 30,
        "appcodechecker": false,
        "appstore.experimental.enabled": true,
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "assetdirectory": "\/var\/www\/html\/owncloud",
        "asset-pipeline.enabled": true,
        "check_for_working_htaccess": true,
        "check_for_working_webdav": true,
        "filesystem_check_changes": 1,
        "forcessl": true,
        "loglevel": 2,
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "Europe\/Berlin",
        "log_query": false,
        "cron_log": true,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "theme": "",
        "trashbin_retention_obligation": "auto, 30",
        "updatechecker": true,
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
        "updater.release.channel": "stable",
        "versions_retention_obligation": "auto, 30",
        "htaccess.RewriteBase": "\/owncloud",
        "skeletondirectory": "",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** PDF Expert

**Operating system:** IOS 10.3

#### Web server error log
<details>
<summary>Web server error log</summary>

No errors have been found.
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

No errors have been found.
</details>

#### Browser log
<details>
<summary>Browser log</summary>

No errors have been found.
</details>

one false example (PDF files recognized as Folders):

![pdf-expert1](https://user-images.githubusercontent.com/16885644/27334406-830ba564-55c9-11e7-9368-90b570335849.JPG)

one right example (PDF files recognized as PDF files):

![pdf-expert2](https://user-images.githubusercontent.com/16885644/27334405-8308cc72-55c9-11e7-9938-ab7073432f2f.JPG)

**Comment by critzinger** [comment]
Is it possible that the following article describes the same problem?

https://github.com/nextcloud/server/issues/5088

**Comment by critzinger** [comment]
Hello everbody,

now i have answer from app developer:

> Thank  you for your patience while the case investigation. Our QA team checked the case and stated that the issue relates to your specific server. Our app displays the file as folder as this information is sent from server.
At this moment, there is not much we can improve on our end. I would recommend that you contact your network administrator with the inquiry to improve the server behavior. 


does anyone can help me how i can find out what is the problem with webdav in nc12?

**Comment by critzinger** [comment]
the fix for the Problem is: #28341

**Comment by TravelTrader** [comment]
Morning from Germany. I have this same issue. I'm working with PDF Expert iOS-App and I edit and mark PDFs without any problems while they're on iCloud but I cannot edit PDFs on my Nextcloud. Not by connection to webDAV, not through FTP-connection.

> the fix for the Problem is: owncloud/core#28341

Here the file `Server.php` is mentioned I do not find in `/lib/composer/sabre/dav/lib/DAV/Server.php`. Can anyone help me to edit and mark my PDFs on my Nextcloud? Would be great!

**Comment by TravelTrader** [comment]
After this problems happened now I do not have any access with my iOS-Apps. I didn't change any settings or config.php-lines ... what happened? What changed?
