### ISSUE TITLE
Nextcloud 12.0 first-run installation fails at creating database

### ISSUE THREAD

**Issue by WereCatf** [nextcloud/server#5487]
On a fresh Ubuntu 17.04 install the first-run installation of Nextcloud 12.0 works fine with MariaDB, but if doing the same with MySQL it fails with "SQLSTATE[HY000] [1049] Unknown database 'nextcloud'" Doing the installation from the web-wizard or from CLI changes nothing, it's the same result.

Manually creating the database before running the installer works.

MySQL-version is 5.7, PHP is 7.0.18-0ubuntu0.17.04.1

**Comment by MorrisJobke** [comment]
> Manually creating the database before running the installer works.

Please have a look at the Nextcloud log. It looks like the entered user does not have enough rights.
