### ISSUE TITLE
Make WebDav available for public/password-protected shared links

### ISSUE THREAD

**Issue by zeus86** [nextcloud/server#5496]
Correct me if i'm wrong, but as it seems to me WebDav only sems to work for oldfashioned folders, shared by or to a user, but not "userless" shares like if you share a folder or file by a link.

wouldn't it be nice to be able to access "public" shares by webdav/webdavs also? i'd really appreciate this, because i would have need for this. working around that would be a hassle indeed.

... using NC 11 right now.

**Comment by zeus86** [comment]
maybe with something like user:<hashed_part_of_the_url> and pass:<pass_of_the_share> or something like that.

**Comment by Schmuuu** [comment]
Hi zeus86,

afaik your right, it doesn't work yet. So you should rather post a pull request instead of an issue ;)

While I fear such a feature will not come, one good solution for you might be the guest app:
https://github.com/nextcloud/guests
There you have an account (guest) and hence it should be possible to access the accounts' data via webdav.
Unfortunately the guest app is not released yet, but might come soon.

**Comment by zeus86** [comment]
> afaik your right, it doesn't work yet. So you should rather post a pull request instead of an issue ;)
yeah, but unfortunately i'm an admin (and mostly a betatester obviously) rather than a dev, so i won't be capapble of fixing this unfortunately, but a mod could flag this thread as " feature request" then.

**Comment by loelkes** [comment]
https://docs.nextcloud.com/server/12/user_manual/files/access_webdav.html

Docs for NC12 says it's possible. 

This works for me:
`curl -k -T {} -u "shareid:" -H 'X-Requested-With: XMLHttpRequest' https://cloud.foobar.de/public.php/webdav/{}`

Mounting the share via the OSX 10.13.1 "Connect to Server" says "There was a problem...". Tested with and without password protected share, share is read/write enabled.

**Comment by zeus86** [comment]
@loelkes uhm, i will definately test this out, thanks for the advice.

**Comment by Govikk** [comment]
@loelkes It works very well for me. 

However there is a small problem. According to given link the only way to pass share id is an user name.  It is not convenient in some cases. It would be much better if share id was passed via URL. 

Eg. I want  NC to host eclipse plugin site. There could be more than one plugin site on server and they could not be distinguished as all of them has the same URL.

**Comment by landryb** [comment]
The documentation says it should work, when browsing the public share in a web browser i can see the web ui doing a `PROPFIND /remote.php/webdav/` with a basic auth header (supposedly constructed with the share name and the share password ?) and getting a 207 code, the xml returned correctly list the files..

so it **should** work, but trying to browse https://url/public.php/webdav/ via cadaver or gvfs (and authenticated with the share name as dav username, and the share password as dav password) only returns 401 codes on the `PROPFIND /remote.php/webdav/` request, same thing with curl, sabredav returns unauthenticated

```
$curl -X PROPFIND -u LK5KdDpJR9kWZk4 https://xxxx/public.php/webdav/         
Enter host password for user 'LK5KdDpJR9kWZk4':
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message/>
</d:error>

**Comment by landryb** [comment]
Ok, it only works if you toggle `outgoing_server2server_share_enabled` in `files_sharing` config to true, as https://docs.nextcloud.com/server/14/user_manual/files/access_webdav.html#accessing-public-shares-over-webdav specifies (the 12 doc didnt precise it...)

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
