### ISSUE TITLE
Remove some branches

### ISSUE THREAD

**Issue by mar1u5** [nextcloud/server#55]
I think there is no reason for keeping `stable8` and all the other outdated branches we will not maintain?

cc @LukasReschke

**Comment by irgendwie** [comment]
We could also think about removing the old releases, since there is no release yet and it may be confusing for some people.

**Comment by mar1u5** [comment]
I agree :+1:

**Comment by mar1u5** [comment]
cc @karlitschek @MorrisJobke

**Comment by MorrisJobke** [comment]
And those branches could be fetched from owncloud anyway. But maybe we want to keep them for the furture to be able to also checkout old ownCloud versions independent from the ownCloud repo 😕

**Comment by mar1u5** [comment]
Why should we :confused:

**Comment by MorrisJobke** [comment]
> Why should we 😕

Customers 😉  (you not, but we as employees 😝 )

**Comment by rullzer** [comment]
https://github.com/nextcloud/server/branches/all <-- seems clean enough now :wink:
