### ISSUE TITLE
Email content for password reset/renewal is wrong

### ISSUE THREAD

**Issue by GitHubUser4234** [nextcloud/server#5500]
Hi,

Since in NC12 there is a feature which sends out emails on password change. The content of the email depends on whether it was a PASSWORD_CHANGED_SELF or a PASSWORD_RESET (see source code [here](https://github.com/nextcloud/server/blob/master/settings/Hooks.php#L93)).

The problem is that in user_ldap's [RenewPasswordController](https://github.com/nextcloud/server/blob/master/apps/user_ldap/lib/Controller/RenewPasswordController.php), a password is changed also, but when the Hooks class is [called](https://github.com/nextcloud/server/blob/master/settings/Hooks.php#L92), `$this->userSession->getUser()` is null and it thus sends out an email with the wrong content (PASSWORD_RESET, but should be PASSWORD_CHANGED_SELF).

I have tested two different code pieces added at [line 143](https://github.com/nextcloud/server/blob/master/apps/user_ldap/lib/Controller/RenewPasswordController.php#L143) in the RenewPasswordController to solve the problem, but in vain:

1)  Add `$this->session->set('user_id', $user);`. Result: After a successful password change, there is a "Logout occurred" message in the server logs. And in the Hooks class, `$this->userSession->getUser()` is null which again leads to the wrong PASSWORD_RESET email content being sent out.

2) Add `$this->userSession->setUser($this->userManager->get($user));`. Result: After a successful password change, `$this->userSession->getUser()`  has a correct value in the Hooks class and the correct PASSWORD_CHANGED_SELF email content is sent out. However all the values set into the session after the added code piece in the RenewPasswordController, e.g. lines [146](https://github.com/nextcloud/server/blob/master/apps/user_ldap/lib/Controller/RenewPasswordController.php#L146),  [152](https://github.com/nextcloud/server/blob/master/apps/user_ldap/lib/Controller/RenewPasswordController.php#L152) and  [157](https://github.com/nextcloud/server/blob/master/apps/user_ldap/lib/Controller/RenewPasswordController.php#L157), are lost once the RedirectResponse is executed. This doesn't fail in scenario 1).

How could the ultimate goal be achieved to send out the correct email content?

@rullzer: We talked briefly in IRC, as a session guru, I guess this might be a question for you 😄 

@blizzz: for your reference also, thanks 🐱 

Edit: I found the wrong email content also when performing the usual reset password function (LostController).

**Comment by blizzz** [comment]
hm, why is ``onChangeEmail`` relevant? Or you probably refer to https://github.com/nextcloud/server/blob/master/settings/Hooks.php#L92  instead of line 156.

Is this issue limited to the LDAP backend or also affects local users?

**Comment by GitHubUser4234** [comment]
> hm, why is onChangeEmail relevant? Or you probably refer to https://github.com/nextcloud/server/blob/master/settings/Hooks.php#L92 instead of line 156.

Oh, thanks for the hint, i slipped to a different location as the code looks so similar 😆 I corrected the lines above to spare others from getting confused, too.


> Is this issue limited to the LDAP backend or also affects local users?

The RenewPasswordController is only used to handle LDAP password expiry, so seems there is no comparable use case for local users available. Changing passwords from within the personal page works however, no matter LDAP or local user.

**Comment by GitHubUser4234** [comment]
I found the wrong email content also when performing the usual reset password function (LostController).

**Comment by blizzz** [comment]
Perhaps it is sufficient to omit " reset by an administrator", as do not know the source of the event at this point.

**Comment by GitHubUser4234** [comment]
> Perhaps it is sufficient to omit " reset by an administrator", as do not know the source of the event at this point.

Yes, this way it would at least not be wrong and misleading 👍

**Comment by szaimen** [comment]
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!
