### ISSUE TITLE
Select2 broken on 12 - Can not unselect items on multi-select anymore

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#5510]
We use select2 in many locations:
* Automated tagging (assign tag block)
* Group selection for:
  - Sharing disabled for groups
  - Update notification group
  - Announcement center posting group
* System tag assignments

In all those places you can not unselect an item. When you click on it, it will select the next item, until there are no items left over.
This is crucial for those features and needs immediate fixing for 12.0.1 and backporting to 11 as well

@nextcloud/javascript

**Comment by nickvergessen** [comment]
Regression from https://github.com/nextcloud/server/commit/66258f55e63ed460d2967a6541b77cf2fc3e5361

**Comment by nickvergessen** [comment]
One fix would be to remove all `.select2*` styling from `input.scss`.
However I think @jancborchardt wants the styling so we need someone to look into this:

1. Either bring back the `X` on the items, or
2. Allow unselecting by clicking on the items in the dropdown.

I think option 2 is the better one, but it's above my JS knowledge

**Comment by jancborchardt** [comment]
Yeah, clicking on an item again should absolutely work for deselecting. Just like with a normal select.

**Comment by nickvergessen** [comment]
@danxuliu maybe also something for you?
