### ISSUE TITLE
No 'Authorization: Bearer' header found.

### ISSUE THREAD

**Issue by Krassmus** [nextcloud/server#5512]
### Steps to reproduce
1. Have an oauth 2 access token and try to access nextcloud via webdav.
2. create a curl-request with the "Authorization: Bearer xyz" header where `xyz` is the access token.

### Expected behaviour
I should have got access to the web dav objects

### Actual behaviour
Nextcloud tells me en error message 
    <?xml version="1.0" encoding="utf-8"?>
    <d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
      <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
      <s:message>No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured</s:message>
    </d:error>

But it's from! I have clearly added the header with bearer token (but not basic auth).

### Server configuration

**Operating system**:
ubuntu
**Web server:**
apache
**Database:**
mysql
**PHP version:**
5.5
**Nextcloud version:** (see Nextcloud admin page)
12
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh
**Where did you install Nextcloud from:**
manually
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
ssl
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
php curl
**Operating system:**
ubuntu
#### Web server error log
no log error at that time

I thought this could be related to #5372 but the fix there didn't seem to work for me.

**Comment by Krassmus** [comment]
Edit: I do get a "Login failed: 'CxiRWaDhH7ffGQLuog7dH5E8oXJyU94VexxxxxxLcSupBDwRDKRi0ey0' (Remote IP: '78.47.9.104')" log entry, when I try to receive a refresh token. Might that be the problem?

**Comment by rullzer** [comment]
@LukasReschke wasn't this some apache thing?

**Comment by Krassmus** [comment]
I actually use an apache.

**Comment by LukasReschke** [comment]
This will only work if you have mod_rewrite and mod_env enabled and available as well as allowed the `.htaccess` that we ship (`AllowOverride All`). Apache strips the `Authorization: Bearer`.

**Comment by LukasReschke** [comment]
As alternative just use Basic auth and use the token as user password.

**Comment by Krassmus** [comment]
Alright! That seemed to solve the problem. Maybe the admin-page for the nextcloud oauth app could throw a warning if those mods aren't enabled.

Anyway: **Thank you!** I wouldn't have guessed that in a million years.

**Comment by m1cka** [comment]
Hi,
@Krassmus , 
maybe you can paste/show your .htaccess?
@LukasReschke  i use apache too. where need to add   Header always set? in apache  conf or in nextcloud .htaccess?

**Comment by havrla** [comment]
Heloo,

same problem after install package php-pear-Auth-SASL   on system Centos7 with php71w   and NC12.0.6

Recovery from snapshot :-), remove package no effect.

Havrla

**Comment by karankotz** [comment]
@Krassmus  Can you please provide more details on how you solved this problem, I have been struggling with this since long time!

**Comment by Krassmus** [comment]
Hi @karankotz , this comment by Lukas helped me out:

> This will only work if you have mod_rewrite and mod_env enabled and available as well as allowed the .htaccess that we ship (AllowOverride All). Apache strips the Authorization: Bearer.

The apache stripped away a header which I was sending. Without this header the error-reporting `No 'Authorization: Bearer' header found.` makes truly sense. Nextcloud can't receive the token, when it has been flushed by the webserver. So have a look at your apache config. Or do you use nginx or stuff?

**Comment by karankotz** [comment]
@Krassmus 
I have followed the below steps (I am using Ubuntu): 

1> Enabled the mod_env and mod_rewrite (following the steps at http://www.iasptk.com/enable-apache-mod_rewrite-ubuntu-14-04-lts)

2> Created the .htaccess at the path /var/www/html/ and added "RewriteEngine on".

Still I have the same error after restarting the apache2 service.

**Comment by Krassmus** [comment]
Does your apache have the `AllowOverride All` statement in the directory statement? Maybe your .htaccess file is not evaluated at all by the apache?

**Comment by karankotz** [comment]
@Krassmus 
I have added the `AllowOverride All` for the directory settings at the path /etc/apache2/apache2.conf.

Can you please share which OAuth token are you using ? How are you getting the token?

I have configured the Nextcloud with Keycloak and using the access token generated from the keycloak server for this nextcloud server which is configured as the client.

**Comment by ymybe** [comment]
@karankotz 

hi, sorry to bother, but i had a similar issue after migrating to docker everthing with my NC the following solved the stripping of the Authentication header in my case:
 
```
RewriteEngine on
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]
```


in my site-enabled.conf

[](http://sabre.io/dav/webservers/)

**Comment by zahradehghanpur** [comment]
@karankotz I have the same problem as you , I tried all the comments above but didn't work . Is your problem solved?

**Comment by gerroon** [comment]
I am haivng the same issue when trying to use Rclone against Mextcloud 18 webdav on Debian Testing +Apache2.

Any recommendations?

**Comment by DanScharon** [comment]
does #23920 fix this?
