### ISSUE TITLE
No permission to use Camera and Mikrofon

### ISSUE THREAD

**Issue by temporaryuser11** [nextcloud/server#5513]
### Steps to reproduce
1. I use NC12 beta on my RPI3 
2. As browser used Chrome in Germany, lanuage-setting: Deutsch
3. If you go on the NC-site to the app "Videoanrufe", there is no permission to use kamera and mikrofon. "Fehler beim Zugriff auf Mikrofon & Kamera". There is no way to say Chrome that it´s okay to use them.

### Expected behaviour
The app should work!

### Actual behaviour
"Fehler beim Zugriff auf Mikrofon & Kamera"
### Server configuration
standart
**Operating system**:
Raspberry Pi3
**Web server:**
apache2
**Database:**
mysql
**PHP version:**
php5
**Nextcloud version:** (see Nextcloud admin page)
12.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from NC11.0.3
**Where did you install Nextcloud from:**
?
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment]
Issue should be reported at https://github.com/nextcloud/spreed/issues

However I can not reproduce the issue. After a little moment I see a popup from chrome asking for those permissions.
