### ISSUE TITLE
Upgrade fails 10.0.5 to 11.0.3 

### ISSUE THREAD

**Issue by eshattow** [nextcloud/server#5515]
### Steps to reproduce
1. Manual upgrade 10.0.5 to 11.0.3

### Expected behaviour
Normal procedure for manual upgrade.

### Actual behaviour
Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'ALTER TABLE oc_accounts ADD PRIMARY KEY ("uid")': SQLSTATE[23505]: Unique violation: 7 ERROR: could not create unique index "oc_accounts_pkey" DETAIL: Key (uid)=() is duplicated.

Detailed logs 
Preparing update
Set log level to debug
Turned on maintenance mode
Updating database schema
Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'ALTER TABLE oc_accounts ADD PRIMARY KEY ("uid")': SQLSTATE[23505]: Unique violation: 7 ERROR: could not create unique index "oc_accounts_pkey" DETAIL: Key (uid)=() is duplicated.

### Server configuration

**Operating system**: Debian GNU/Linux 8 
Linux s2 2.6.32-042stab116.1 #1 SMP Wed May 4 16:21:02 MSK 2016 x86_64 GNU/Linux

**Web server:** apache2 2.4.10-10+deb8u8

**Database:** postgresql 9.4+165+deb8

**PHP version:** libapache2-mod-php5 5.6.30+dfsg-0+deb8u1

**Nextcloud version:**  Nextcloud 10.0.5 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from ownCloud

**Where did you install Nextcloud from:** Download tar.bz2 from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.3.2
  - comments: 1.0.0
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.1
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - user_external
  - user_ldap
  - user_saml
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "ocywhj8defsc",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "oc.ai6fs.net"
        ],
        "datadirectory": "\/home\/web\/nextcloud-data",
        "overwrite.cli.url": "http:\/\/oc.ai6fs.net",
        "dbtype": "pgsql",
        "version": "9.1.5.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 2,
        "maintenance": false,
        "htaccess.RewriteBase": "\/",
        "theme": ""
    }
}
</details>

**Are you using external storage, if yes which one:** local separate nextcloud-data directory

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
<details>
<summary>LDAP config</summary>
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "ldap" namespace.          
</details>

### Client configuration
**Browser:** chromium 59.0.3071.86-1

**Operating system:** Debian GNU/Linux 9
Linux zontar 4.11.0-trunk-amd64 #1 SMP Debian 4.11-1~exp2 (2017-05-05) x86_64 GNU/Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
[nextcloud-log.txt](https://github.com/nextcloud/server/files/1095947/nextcloud-log.txt)
</details>

#### Browser log
<details>
<summary>Browser log</summary>
</details>

**Comment by jospoortvliet** [comment]
Can anyone reproduce this? @MorrisJobke if you have time perhaps...

**Comment by MorrisJobke** [comment]
> Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'ALTER TABLE oc_accounts ADD PRIMARY KEY ("uid")': SQLSTATE[23505]: Unique violation: 7 ERROR: could not create unique index "oc_accounts_pkey" DETAIL: Key (uid)=() is duplicated.

@nickvergessen Looks like we have a unique constraint on uid while owncloud doesn't and then there could be one key multiple times. An idea how to detect and clean this up?

@eshattow could you have a look at the oc_accounts table? Best would be of course a dump of this table before the update. Is this possible (anonymised of course).

**Comment by nickvergessen** [comment]
> Looks like we have a unique constraint on uid while owncloud doesn't and then there could be one key multiple times. An idea how to detect and clean this up?

We drop this table on migration from owncloud, so should not be a problem....
https://github.com/nextcloud/server/blob/c6b7204fcbd4556f7e5c5d7c6b541beed631a86d/lib/private/Repair/Owncloud/SaveAccountsTableData.php#L82

**Comment by MorrisJobke** [comment]
> Manual upgrade 10.0.5 to 11.0.3

Ah right - we only support the upgrade from ownCloud 10 to 12, right?

**Comment by jospoortvliet** [comment]
Actually if you are on oC 10 you're supposed to go to Nextcloud 10 first, then to Nc 11 then 12.

**Comment by MorrisJobke** [comment]
> We need to document this more clearly, I think.

@jospoortvliet Please open a ticket in documentation.

**Comment by jospoortvliet** [comment]
@MorrisJobke we already explain this on nextcloud.com/migration, I will edit it a bit. and https://github.com/nextcloud/documentation/blob/master/admin_manual/maintenance/migrating_owncloud.rst is already as clear as it can be.

**Comment by eshattow** [comment]
This was from NextCloud 10 to NextCloud 11, after possibly a failed upgrade from OwnCloud 9.1;  I've dropped the oc_accounts table in psql and now the upgrade proceeds normally. Thanks for the help everyone!
