### ISSUE TITLE
WebRTC, webtorrent download assist

### ISSUE THREAD

**Issue by zanglerecke** [nextcloud/server#5522]
Some idea:

### Expected behaviour
Acutally i had a lot of downloads of video content (legal one, videos of dance competitions). Files are big (most of them are in the range of 100MB to 1GB).

using a torrent like concept it could reduce the load on the server, and enhance download speed.
[https://webtorrent.io]

-> someone downloads a file, and junks of it will be transfered to the next user.... and so on.

THIS IS JUST AN IDEA, i have no clu about how to implement it, but i want to share it. maybe someone is interested in that.

**Comment by tflidd** [comment]
You can use syncthing to sync files directly between different clients. You need to install a client on your server as well and you can then use the local folder as external storage in Nextcloud.

There is a longer thread on the client bug tracker: https://github.com/owncloud/client/issues/230

**Comment by zanglerecke** [comment]
but this solution is a dirty hack, as the storage of syncthing  and next/owncloud are shared, and a new nextcloud installation wouldnt recognize new files....

and anybody who is downloading a shared link has to install the syncthing software.

my proposal was to allow anybody who downloads using the webinterface to participate in the torrent-like concept. -> implementation in the website/download page

**Comment by tflidd** [comment]
> my proposal was to allow anybody who downloads using the webinterface to participate in the torrent-like concept. -> implementation in the website/download page

You include this in your browser, do you know a working implementation? Webtorrent? https://github.com/webtorrent/webtorrent

**Comment by MorrisJobke** [comment]
I don't think that distributing the Nextcloud files via some sort of peer2peer network (torrent or webrtc) makes a lot of sense.

cc @karlitschek 

I would close this ticket.

**Comment by karlitschek** [comment]
Yes. Not sure this makes a lot of sense because I are talking mainly about personal files here and not mass downloads. But maybe I'm missing the point here. +1 for closing this

**Comment by MorrisJobke** [comment]
> Yes. Not sure this makes a lot of sense because I are talking mainly about personal files here and not mass downloads. But maybe I'm missing the point here. +1 for closing this

If there is another use case where this makes a lot of sense we are open for proposals, but as of now I would close this ticket.

Thanks for the idea sharing anyways :)

**Comment by zanglerecke** [comment]
As mentioned above, it would have made sense in my case. (Yes it is some sort of mass download)
To share huge files with a lot of persons. Most of them where downloaded simultaneous in the first two days. Afterwards this feature would not have any benefit for the downloads.
