### ISSUE TITLE
Issues after renaming an already shared folder...

### ISSUE THREAD

**Issue by githubos1** [nextcloud/server#553]
### Steps to reproduce
1.create a new folder and add some files (in my case jpgs)
2.share this folder with a group
3.rename this folder 

### Expected behaviour
Renaming should be automatically happen in all shared accounts of the shared group

### Actual behaviour
No renaming takes place...and previously existing users (in the group) can still use and view the shared content...

BUT, newly created - and added to the shared group- users (after the renaming took place) can see the OLD (before renaming) folder and containing files (icons and filenames) but have no access and get error messages

i.e.
Sorry, this file could not be found.

	Reasons might be:
	the wrong file ID was provided
            the file was removed
            the file is corrupt 
            the encryption key is missing
	
             Here is the error message returned by the server: 
             There was a problem accessing the file (404)
         For more information, please contact your friendly ownCloud administrator.

AFTER deleting the share and re-sharing, issue is solved...

### Server configuration
**Operating system**:

**Web server:**  HostedServer ALL-INKL

**Database:**  MYSQL

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page) 9.051

**Updated from an older Nextcloud/ownCloud or fresh install:**  opdated from OWNCLOUD 9.021

**Where did you install Nextcloud from:**  

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
> Renaming should be automatically happen in all shared accounts of the shared group

No. This is a feature, because a user can rename the received share. If we would update this name then it would get overwritten. All subfolders have the same naming in all shares, but the root folder not.

**Comment by githubos1** [comment]
Please read the whole thing....  that behaviour was not my real issue (although I believe it is one !!)

But what's happening to newly added/created users to the group after the renaming is a BIG issue !!

**Comment by MorrisJobke** [comment]
Ah, you have encryption enabled? Then adding new users to a group doesn't allow them to access files/folders that are shared with that group before they are added to the group. This is a know limitation of the encryption. This has nothing to do with the renaming and also happens if the rename wasn't done. https://docs.nextcloud.com/server/9/user_manual/files/encrypting_files.html#sharing-encrypted-files

cc @schiessle

**Comment by githubos1** [comment]
yes I do ...  damn .... :-)  I guess you mean the server sided encryption ??  right ?

**Comment by MorrisJobke** [comment]
> yes I do ... damn .... :-) I guess you mean the server sided encryption ?? right ?
> 
> not the external storage encryption..

It is both the same, but the external storage encryption is only for a specific storage ;)

There is a plan to address this issue, but it involves a lot of work to do it right :(
