### ISSUE TITLE
/dev/urandom warning seems unnecessary 

### ISSUE THREAD

**Issue by dchest** [nextcloud/server#5530]
Hello,

I've noticed there's a check for existence of `/dev/urandom` (pointed out by [this article](https://blog.housingsklave.at/?p=100)):

* https://github.com/nextcloud/server/blob/69b65042858eb8436a91af511c5e77cfeefff924/core/js/setupchecks.js#L107
* https://github.com/nextcloud/server/blob/e9b00f84b85e97283b83cf951f9bd262e627ae9a/settings/Controller/CheckSetupController.php#L147

It outputs *"/dev/urandom is not readable by PHP which is highly discouraged for security reasons. Further information can be found in our documentation"*.

However in PHP 7 on most recent platforms `/dev/urandom` is not used, and this check is confusing, especially in OpenBSD, as its web server is always chrooted, so there's no `/dev/urandom`. PHP 7 `random_bytes` and `random_int` use:

* `getrandom` on recent Linux
* `CryptGenRandom` on Windows
* `arc4random` on OpenBSD and NetBSD

On platforms that read randomness from `/dev/urandom` (like older Linux versions), the inability to open it by `random_bytes` will throw an exception: https://github.com/php/php-src/blob/696bd37e6757d77dc7ed44f3ea6451944ebaba96/ext/standard/random.c#L150

Since Nextcloud's SecureRandom uses `random_int`, it will throw if it fails to generate random bytes.

Proposal: instead of checking for existence of `/dev/urandom`, check if SecureRandom can successfully generate random bytes. This should be a setup error, not just a warning.

**Comment by binarious** [comment]
`getrandom` uses `/dev/urandom` [by default](http://man7.org/linux/man-pages/man2/getrandom.2.html):

> By default, getrandom() draws entropy from the urandom source (i.e.,
       the same source as the /dev/urandom device).

**Comment by dchest** [comment]
@binarious it uses the *same source* of entropy as /dev/urandom, it doesn't actually opens the file.
