### ISSUE TITLE
v12 with autoconfig.php always shows loading indicator before install

### ISSUE THREAD

**Issue by kyrofa** [nextcloud/server#5532]
The [Nextcloud snap](https://github.com/nextcloud/nextcloud-snap) uses autoconfig.php to pre-configure the database. In Nextcloud v11, that made the initial visit to Nextcloud (where one creates the admin user/installs Nextcloud) look like this:

![screenshot from 2017-06-24 08-26-58](https://user-images.githubusercontent.com/946674/27509681-3e06da38-58b7-11e7-8b62-32b31d44c599.png)

Very nice. v12 works the same way, except the loading indicator that typically shows up once one hits "Finish setup" is always present:

![screenshot from 2017-06-24 08-25-08](https://user-images.githubusercontent.com/946674/27509688-5635bbf6-58b7-11e7-9818-9def27c2877d.png)

### Steps to reproduce
1. Setup NC12's autoconfig.php such that the only thing you see on the setup page is a prompt for the admin username/password. Or optionally, just install the snap based on the daily latest stable 12 tarball:
    $ sudo snap install nextcloud --channel=12/edge
2. Visit localhost (or wherever you have it installed)
3. Notice the loading indicator spinning already.

### Expected behaviour
The loading indicator to be properly hidden, ala NC11.

### Actual behaviour
The loading indicator is not hidden, and shows when you first visit Nextcloud.

### Server configuration

**Operating system**:

Ubuntu 16.04

**Web server:**

Apache 2.4

**Database:**

MySQL

**PHP version:**

7.0.20

**Nextcloud version:** (see Nextcloud admin page)

12 daily

**Updated from an older Nextcloud/ownCloud or fresh install:**

Fresh

**Where did you install Nextcloud from:**

The snap.

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

config.php:
```
<?php
$CONFIG = array (
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/snap/nextcloud/current/htdocs/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/snap/nextcloud/current/nextcloud/extra-apps',
      'url' => '/extra-apps',
      'writable' => true,
    ),
  ),
  'supportedDatabases' =>
  array (
    0 => 'mysql',
  ),
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '/tmp/sockets/redis.sock',
    'port' => 0,
  ),
  'instanceid' => 'ocyv0a1214oc',
);
```

autoconfig.php:
```
<?php

$snap_name = getenv('SNAP_NAME');

$data_path = '/var/snap/'.$snap_name.'/current';

$database_password = trim(file_get_contents($data_path . '/mysql/nextcloud_password'));

$AUTOCONFIG = array(
'directory' => getenv('NEXTCLOUD_DATA_DIR'),

'dbtype' => 'mysql',

'dbhost' => 'localhost:'.getenv('MYSQL_SOCKET'),

'dbname' => 'nextcloud',

'dbuser' => 'nextcloud',

'dbpass' => $database_password,
);
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

No

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No

### Client configuration
**Browser:**

Firefox 54

**Operating system:**

Ubuntu 16.04

#### Browser log
<details>
<summary>Browser log</summary>

```
Javascript console log:

Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.  (unknown)
JQMIGRATE: Migrate is installed, version 1.4.0  core.js:7:542
```
</details>

**Comment by kyrofa** [comment]
@jospoortvliet this issue may interest you.

**Comment by kyrofa** [comment]
I see similar things when browsing the list of apps. Not sure if this is the same issue or a new one.

![screenshot from 2017-06-24 08-56-02](https://user-images.githubusercontent.com/946674/27509876-021e8698-58bb-11e7-8f1e-da94fcf393a4.png)

**Comment by kyrofa** [comment]
Any chance this could be looked at for 12.0.2?

**Comment by jospoortvliet** [comment]
Yeah, that'd be good. Not sure if anyone has time. @MorrisJobke you might be able to debug... ?

**Comment by IPv777** [comment]
Same issue with fresh files of NC.
https://screenshots.firefoxusercontent.com/images/0fe65a7d-3acf-465a-b951-d14ee784710b.png

**Comment by Tschlienger** [comment]
Same thing here like @IPv777 ...
Unable to install nextcloud because of the loading icon on the installer page.
Tried both zip and web installer, also with full permission (777) to the nextcloud folder.

![image](https://user-images.githubusercontent.com/11772968/31026372-8348407e-a546-11e7-8a46-23059cad59d1.png)

**Comment by kyrofa** [comment]
I suspect this is because the scss is not compiled until Nextcloud is actually "installed" which is after this step. `core/css/guest.css` probably needs to account for this spinner.

**Comment by MorrisJobke** [comment]
Backport to stable12 is in #7095
