### ISSUE TITLE
Custom Theme:  Custom UI Icons not appearing

### ISSUE THREAD

**Issue by rebeccaformfx** [nextcloud/server#5533]
### Steps to reproduce
1.  Activate custom theme with custom UI icons in core/img/filtetypes/ 
2. Disable 'Theming' app
3. Clear cache and log into NextCloud 

### Expected behaviour
The filetype icons from my theme should override old filetype icons

### Actual behaviour
The filetype icons are the old icons

### Server configuration

**Operating system**:    

**Web server:**   Apache 2.2.32

**Database:**   mySQL 5.6.32

**PHP version:**   PHP 5.6.29

**Nextcloud version:** (see Nextcloud admin page)  11.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**   fresh install

**Where did you install Nextcloud from:**  Nextcloud.com PHP bundle

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Default list
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
No, its installed on a shared BlueHost server
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**  Google Chrome and Safari, latest

**Operating system:**  Mac OS 10.12.3

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by juliushaertl** [comment]
Running the occ command from here should fix that: https://docs.nextcloud.com/server/12/developer_manual/core/theming.html#how-to-update-custom-mimetype-icons
