### ISSUE TITLE
"shared by link" doesn't show folder or files shared via email.

### ISSUE THREAD

**Issue by OlivierS1** [nextcloud/server#5537]
### Steps to reproduce
1. Access Web interface
2. Share a folder with email address
3. Go to "shared by link" page
4. The content of the page will only display shares that have been done with the "Share link" process.

### Expected behaviour
Tell us what should happen
The page should also include shares created through the email sharing process.
If not, then another share status page should be added to list the relevant contnents.

### Actual behaviour
The page doesn't show links entered via email but only the one that have a public share done through "Share link".

### Server configuration

**Operating system**: FreeBSD owncloud 10.3-STABLE FreeBSD 10.3-STABLE #0 41eb257(9.10.2-STABLE): Mon Mar  6 17:03:14 UTC 2017     root@gauntlet:/freenas-9.10-releng/_BE/objs/freenas-9.10-releng/_BE/os/sys/FreeNAS.amd64 amd64

**Web server:** nginx/1.12.0 (fpm-fcgi)

**Database:** mysql 10.1.23

**PHP version:** 7.0.19
Modules loaded: Core, date, libxml, pcre, Reflection, SPL, hash, session, cgi-fcgi, standard, bz2, ctype, curl, dom, mbstring, fileinfo, filter, gd, mysqlnd, iconv, intl, json, exif, mcrypt, openssl, PDO, posix, SimpleXML, xml, xmlwriter, zip, zlib, pdo_mysql, redis, wddx, xmlreader, xsl, apcu, Zend OPcache

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Comment by MorrisJobke** [comment]
cc @nextcloud/sharing

**Comment by skjnldsv** [comment]
Fixed now
