### ISSUE TITLE
Issues after renaming an already shared folder..  2nd.. refinement  (Re. my BugReport #553)

### ISSUE THREAD

**Issue by githubos1** [nextcloud/server#554]
### Steps to reproduce
1. create a new folder & add files (jpgs in my case)
2. OWNER shares this folder with an existing GROUP  
3. OWNER renames the already shared folder
4. ADMIN adds newly created users to the GROUP
5

### Expected behaviour
All GROUP users should have access to the by OWNER shared files and folders - regardless of when they have been added by ADMIN to the GROUP

### Actual behaviour
NEWLY created users added to the GROUP after the shared folder has been renamed by OWNER  can see the shared folder and files icons and filenames (without previews though) and when trying to open those files only get ERROR messages like:
-----------------------
Sorry, this file could not be found.

Reasons might be:
the wrong file ID was provided
        the file was removed
        the file is corrupt 
        the encryption key is missing

         Here is the error message returned by the server: 
         There was a problem accessing the file (404)
     For more information, please contact your friendly ownCloud administrator.
---------------------------------------

Previously existing users do not see this issue

### Server configuration
**Operating system**:

**Web server:** HOSTED SERVER "ALL-INKL"

**Database:** MYSQL

**PHP version:** 7.08

**Nextcloud version:** (see Nextcloud admin page) 9.051

**Updated from an older Nextcloud/ownCloud or fresh install:** OwnCloud 9.021

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by icewind1991** [comment]
Can't reproduce this

**Comment by githubos1** [comment]
Just got the info that it has to do with server sided encryption ON... it's aparently a known issue - if you add users after sharing encrypted files and those users have not created their own encryption keys yet...  ... so I guess this solves my issue :-)  although it's not a nice behaviour...


comment to my previous issue #553:
 
MorrisJobke commented 12 minutes ago
-----------------------------------
Ah, you have encryption enabled? Then adding new users to a group doesn't allow them to access files/folders that are shared with that group before they are added to the group. This is a know limitation of the encryption. This has nothing to do with the renaming and also happens if the rename wasn't done. https://docs.nextcloud.com/server/9/user_manual/files/encrypting_files.html#sharing-encrypted-files

**Comment by MorrisJobke** [comment]
> although it's not a nice behaviour...

There is a plan to address this, but it involves a lot of work to do it right :(

**Comment by githubos1** [comment]
at least I know now that this is not due to a wrong setup of my server nor has to do with a faulty migration from OwnCloud or faulty database (my biggest concearn)  ;-)

Thank's a lot

Oliver
