### ISSUE TITLE
FEATURE REQUEST: local update reposity folder

### ISSUE THREAD

**Issue by nielsd** [nextcloud/server#5540]
Dear Nextcloud Devels,

it would be very helpful - and saves you a lot of downloads from your FTP/HTTP-Fileservers - if there would be a config file option for a local "download" repository folder. Alternatively it allows the usage of a alternative HTTP and/or FTP (base) URL too.

This could work in two ways:

Variant A.)
Any download (signed and over a Nextcloud instance) is permanently saved within this folder. If the updater of another instance (with access to that filesystem folder) find's the requested file within that folder, it uses this "Local copy". If not, it loads from the public sites (as today).

Variant B.)
Only the Admin has the ability to save (officially) Nextcloud Tarballs within this "shared" filesystem folder and if an updater of an instance find's the requested file within that folder - it uses the file instead of fetching it remotely.

I assume there are many virtual host / multi installations of Nextcloud out there within the same machine or subnet / LAN and it makes no sense to download the Nextcloud Tarballs for 10+ Nextcloud Instances from the same machine or LAN within a provider / hosting network.

If it help's anyone here, i would implement it and provide a patch.

many thanks for your time,

Niels.

**Comment by e-alfred** [comment]
Sound like a great idea. Another use case would be tightly firewalled/air-gapped systems. An admin would have less trouble upgrading all instances with this.

**Comment by MorrisJobke** [comment]
Just specify another updater server in config.php and run it with your own links: https://github.com/nextcloud/updater_server
