### ISSUE TITLE
Draw.io diagramm opened with text editor when the file is set as favorite

### ISSUE THREAD

**Issue by DiGGeR2** [nextcloud/server#5541]
### Steps to reproduce
1.Create a new diagramm (with Draw.io app installed)
2.Make the saved diagram as favorit document
3.Open this diagram in the favorit folder... It's open with XML viewer :(

### Expected behaviour
The XML should open with the Draw.io app like it is when document is not in favorit folder

### Actual behaviour

The XML document is opened with the integrated text editor

### Server configuration

**Nextcloud version: 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install: fresh install

**Comment by splitt3r** [comment]
https://github.com/pawelrojek/nextcloud-drawio/issues/16 sounds quite the same?

**Comment by poVoq** [comment]
Check your mimetypealiases.json and mimetypemapping.json files. For me it was just a misconfiguration of those.

**Comment by DiGGeR2** [comment]
Hello, ok I've found these 2 files in nextcloud/resources/config/ , could you give me the right values for the xml extension please ?

**Comment by poVoq** [comment]
Try deleting them. For this plug-in they are not needed. You probably tried to add custom mime-types to your site previously.
