### ISSUE TITLE
[External Storage Support] CREATE TABLE error

### ISSUE THREAD

**Issue by artemanufrij** [nextcloud/server#5544]
On activating, NC12 throws following error:
```An exception occurred while executing 'CREATE TABLE `oc_external_mounts` (`mount_id` BIGINT AUTO_INCREMENT NOT NULL, `mount_point` VARCHAR(128) NOT NULL, `storage_backend` VARCHAR(64) NOT NULL, `auth_backend` VARCHAR(64) NOT NULL, `priority` INT DEFAULT 100 NOT NULL, `type` INT NOT NULL, PRIMARY KEY(`mount_id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_external_mounts' already exists```

I never used it before

**Comment by nickvergessen** [comment]
You can manually delete the table and reenable the app, if you are sure it's not used yet.
We will properly fix this with nextcloud 13 and migrations.

**Comment by MorrisJobke** [comment]
> You can manually delete the table and reenable the app, if you are sure it's not used yet.
> We will properly fix this with nextcloud 13 and migrations.

Closing then.
