### ISSUE TITLE
Sharing via ocs: no meaningful error message when password requirement is not met

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#5545]
- enable password protection with e.g. 8 chars limit
- use android / ocs to share a file via link
- get "only" a 401 back and no infos about the requirements not met

Ref: https://github.com/nextcloud/android/issues/1089

**Comment by tobiasKaminsky** [comment]
@schiessle this is solved via ocs2, right?

**Comment by schiessle** [comment]
This should also work with OCSv1 as well. If I enforce a password for link shares and try to create a link share with a password < 8 chars:

````
curl -X POST http://admin:admin@localhost/master/ocs/v1.php/apps/files_sharing/api/v1/shares -d path=welcome.txt -d shareType=3 -H "Ocs-ApiRequest:true" -d password="ncjdshf"
````

I get this response:

````
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>403</statuscode>
  <message>Password need to be at least 8 characters long</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data/>
</ocs>
````

The only difference is the HTTP status code, with OCSv1 you get 401 and with OCSv2 the 403 which is also encoded in the json.

**Comment by tobiasKaminsky** [comment]
> The only difference is the HTTP status code, with OCSv1 you get 401 and with OCSv2 the 403 which is also encoded in the json.

And this is why it helped for android to switch to ocsv2.
Thanks
