### ISSUE TITLE
Apps files from theme are being ignored

### ISSUE THREAD

**Issue by rebeccaformfx** [nextcloud/server#5554]
### Steps to reproduce
1.  Employ custom theme
2.  Attempt to override one of the enabled apps on my NextCloud install (breadcrumb.js, for example) by creating {{themename}}>apps>files>js>breadcrumb.js to my theme
3.  (I just added a console.log() command to print to console)

### Expected behaviour
Tell us what should happen

breadcrumb.js file in my theme should override the root file

### Actual behaviour
Tell us what happens instead

NextCloud ignores my theme file

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by rebeccaformfx** [comment]
I've seen a number of other bugs on OwnCloud's github about this problem.  Hopefully NextCloud can address this where OwnCloud has failed.  https://github.com/owncloud/core/issues/8626

**Comment by MorrisJobke** [comment]
In general I don't like to allow overwriting of our code. This is basically patching our code which could cause severe problems.

cc @LukasReschke @nickvergessen @rullzer @nextcloud/theming 

I would vote for not allow such behaviour. If you want to mess with that code: apply patches - yes it is bad, but randomly replacing files from within a theme is not better at all.

**Comment by LukasReschke** [comment]
> I would vote for not allow such behaviour. If you want to mess with that code: apply patches - yes it is bad, but randomly replacing files from within a theme is not better at all.

👍

**Comment by juliushaertl** [comment]
Makes sense to remove support for that. But it should then also be removed from the documentation.

**Comment by rebeccaformfx** [comment]
Understood as to why this is on principal a bad idea.  That being said, I would suggest to please limit the amount of times that inline CSS styles and image paths are created from JS files within apps.  It makes it very hard to making a thorough visual theme since these paths are un-overridable without changing the JS file.

**Comment by rebeccaformfx** [comment]
Example being the breadcrumbs asset.  Custom CSS does not affect this asset since it is an `img` and I cannot change the written path in the app JS file to write it to the screen the way I want it, so i have to run a setInterval function to constantly swap the image source.  Really messy

**Comment by MorrisJobke** [comment]
> Example being the breadcrumbs SVG home icon asset. Custom CSS does not affect this asset since it is an img and I cannot change the written path in the breadcrumbs.js app file to write it to the screen the way I want it in my theme, so i have to run a setInterval function to constantly swap the image source. Really messy

This is then a really specific problem and we need to work on this. Could you open an ticket, that describes this and then we can look into how to make theming this icon easier.

**Comment by rebeccaformfx** [comment]
There are other areas of the app that do this.  For example, the colors of the values under the `Size` and `Modified` columns in the Files app are written inline through the Files app JS files and cannot be overwritten by CSS.   Instead of inline CSS you should add a class that can be overriden through CSS.
