### ISSUE TITLE
Function getPreviewFolder take a long time with large folder

### ISSUE THREAD

**Issue by pulcov** [nextcloud/server#5555]
Function getPreviewFolder take 40-45s if preview folder have a lot of subfolders (In my case more than 26000 subfolders).

[Generator.php#L107](https://github.com/nextcloud/server/blob/master/lib/private/Preview/Generator.php#L107)

Is it possible to create more subfolders ?
Exemple :
Change **appdata_xxxxxxxxxxxx/preview/102776** to **appdata_xxxxxxxxxxxx/preview/7/6/102776**

Thank you

**Comment by MorrisJobke** [comment]
cc @rullzer

**Comment by raoulbhatia** [comment]
I think this would be a worth-while change that would increase the performance of nextcloud.

The exact implementation might vary, i.e. I think that we could use 2- or 3- digit directories, i.e.
appdata_xxxxxxxxxxxx/preview/**102776** --> appdata_xxxxxxxxxxxx/preview/**76/27/102776**

Raoul

**Comment by raoulbhatia** [comment]
@rullzer you are the creator of the preview generator app - any thoughts from your side, especially on how to handle a potential migration?

**Comment by skjnldsv** [comment]
Fixed in recent nc versions
