### ISSUE TITLE
Overview of all shared files

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#5559]
What we are missing is a simple overview of all shared files regardless if shared with you, by you or by link. Right now we only have the specific views. Oftentimes you might not know how it was shared, but you just want an overview.

Especially with the upcoming entry for pending & rejected shares https://github.com/nextcloud/server/issues/2192 we also need one simple main entry to show _all_ shares. The others can be sub-entries like subfolders in the Mail or News app.

cc @nextcloud/sharing

**Comment by schiessle** [comment]
> What we are missing is a simple overview of all shared files regardless if shared with you, by you or by link.

I see the use case to have a view of all files shared by the user (link, federated, user, groups).

But what's the use case to have a view which mixes all files I have shared with all files I received? For me both groups are so much out of context that I don't see a use case for it.

**Comment by jancborchardt** [comment]
Dropbox for example doesn't differentiate at all between shared with you and by you. Often it's collaborative folders where the original starter doesn't matter.

The point is to have an overview of everything which is not only private to you.

**Comment by MorrisJobke** [comment]
Was started in #6686 if somebody wants to have a look at some first steps to start with.

**Comment by MorrisJobke** [comment]
Nothing for 14 it seems -> moved to 15
