### ISSUE TITLE
Notification emails on mobile devices / other sizes

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#5563]
Currently it seems like the notification emails have difficulty being displayed on mobile devices or other sizes. Considering the majority of people use the internet through mobile devices now, we should improve that. :) Some examples:

Geary on Gnome with narrow width:
![screenshot from 2017-06-29 16-42-30](https://user-images.githubusercontent.com/925062/27693918-e6722ce0-5cea-11e7-9125-39ef47ca91f1.png)

K9-Mail / K9 Material on Android, the main styling doesn’t even show:
![screenshot_2017-06-29-16-42-08](https://user-images.githubusercontent.com/925062/27693919-e67744be-5cea-11e7-8d73-f3f2a42d28a0.png)

Nextcloud Mail in Chrome on a narrow screen, way too big and none of the text shows:
![screenshot from 2017-06-29 16-44-58](https://user-images.githubusercontent.com/925062/27693920-e677b64c-5cea-11e7-8fe3-ff89134be580.png)

@Espina2 could you look into that? :) cc @nextcloud/designers

**Comment by Espina2** [comment]
@jancborchardt the source code I posted the emails are 100% responsive. I don't even know where to start...

**Comment by jancborchardt** [comment]
Can you reproduce the issues, or is it working with the software you are viewing emails with? Maybe it's a problem with each of the mail apps, also since there are different issues with each one. :)

Also cc @ChristophWurst @Gomez @lcalaresu of our Mail app.

**Comment by jancborchardt** [comment]
Can’t reproduce this issue anymore so it must have been fixed meanwhile, or maybe it was some server error.
