### ISSUE TITLE
webdav broken on v12

### ISSUE THREAD

**Issue by NodokaMurmevent** [nextcloud/server#5572]
i cannot use *dav.

i try a clean install from v12 and i cannot sync any data, strangly if i wipe all and try the v11 all work perfectly.

### Steps to reproduce
1. install nextcloud v12
2. use kmail or thunderbird (try with linux and windows 10)
3. try to connect calendar or other *dav

### Expected behaviour
connect and sync data successfully

### Actual behaviour
401 server error wong username/password

### Server configuration

**Operating system**:
Debian Strech
**Web server:**
Apache/2.4.25
**Database:**
MariaDB 10
**PHP version:**
7.0.19-1
**Nextcloud version:** (see Nextcloud admin page)
12
**Updated from an older Nextcloud/ownCloud or fresh install:**
test for update and fresh

**Where did you install Nextcloud from:**
zip archive

**litmus rapport test :**
<details>
<summary>litmus -k https://cloud.symphonie-of-code.fr/remote.php/webdav/ </summary>
-> running `basic':
 2. options............... WARNING: server does not claim Class 2 compliance
    ...................... pass (with 1 warning)

<- summary for `basic': of 16 tests run: 16 passed, 0 failed. 100.0%
-> 1 warning was issued.
-> running `copymove':

<- summary for `copymove': of 13 tests run: 13 passed, 0 failed. 100.0%
-> running `props':

18. propget............... 
18. propget............... FAIL (Property {http://example.com/neon/litmus/}high-unicode had value ????, expected 𐀀)

<- summary for `props': of 30 tests run: 29 passed, 1 failed. 96.7%
-> running `locks':

 2. options............... WARNING: server does not claim Class 2 compliance
    ...................... pass (with 1 warning)
    ...................... 
 3. precond............... SKIPPED (locking tests skipped,
server does not claim Class 2 compliance)
-> 1 test was skipped.
<- summary for `locks': of 3 tests run: 3 passed, 0 failed. 100.0%
-> 1 warning was issued.
-> running `http':

 2. expect100............. 
 2. expect100............. SKIPPED (skipping for SSL server)

-> 1 test was skipped.
<- summary for `http': of 3 tests run: 3 passed, 0 failed. 100.0%
</details>

**Signing status:**

No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>
```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.2.0
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
```
</details>

**Nextcloud configuration :**
<details>
<summary>Config report</summary>
```
{
    "system": {
        "instanceid": "ocql59dzz3qd",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.symphonie-of-code.fr"
        ],
        "datadirectory": "\/home\/cloud",
        "overwrite.cli.url": "https:\/\/cloud.symphonie-of-code.fr",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
try to use Webdav

### Client configuration
**Browser:**
firefox 55
**Operating system:**
KDE neon

#### Web server error log
nothing interesting

#### Nextcloud log (data/nextcloud.log)
[nextcloud.zip](https://github.com/nextcloud/server/files/1115472/nextcloud.zip)

#### Browser log
nothing

**Comment by Udera** [comment]
Without looking into your logs, there has been a fix on the authentication with caldav/carddav in NC 12. It will be in the next minor release, you might take a look in the fix if it works for you as well:
https://github.com/nextcloud/server/pull/5386

**Comment by MorrisJobke** [comment]
Please retry with 12.0.1. Thanks
