### ISSUE TITLE
Integrity check false alert on fresh installation

### ISSUE THREAD

**Issue by MarcinOrlowski** [nextcloud/server#5578]
I am doing fresh automated install of NextCloud and each time it reports integrity check issue:

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- lib/private/oc_tmp_zJAacJ-.tar.gz

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [lib/private/oc_tmp_zJAacJ-.tar.gz] => Array
                        (
                            [expected] => 
                            [current] => .....
                        )
                )
        )
)
```

The trick is that the file does not exists and as name suggests it is probably something that existed during installation, so the bug is most likely in the order of operations as integrity should checked after all temp files are removed. 

Rescan solves the issue

**Comment by jospoortvliet** [comment]
A timing issue then - as a rescan happens automatically after some time anyway, I'm not sure we have to do anything here.

**Comment by MarcinOrlowski** [comment]
While this is not the highest priority, I think it should be addressed as this may give false impression the instalation is i.e. "doctored"

**Comment by jospoortvliet** [comment]
@LukasReschke anything we can/should do here?

**Comment by LukasReschke** [comment]
How did you do that automated installation? The file there is not generated by us as neither our web installer nor our regular updater uses the TAR file.

**Comment by MarcinOrlowski** [comment]
I wrote Ansible playbook for that. The location of this temp file made me think that it is part your installer process, yet I will check now to ensure this is correct assumption

**Comment by yhoyhoj** [comment]
This is still an issue on Nextcloud 16.0.1.

The instance was installed manually using the tar.gz file downloaded on the official website. The erver is a Synology box running Apache 2.4 with PHP 7.2.

**Comment by kesselb** [comment]
> This is still an issue on Nextcloud 16.0.1.
> 
> The instance was installed manually using the tar.gz file downloaded on the official website. The server is a Synology box running Apache 2.4 with PHP 7.2.

Please don't respond to closed and stale issues. This issue is closed since 2017. There is a similar issue for newer versions https://github.com/nextcloud/server/issues/15681 or create a new issue.
