### ISSUE TITLE
ESET two step verification

### ISSUE THREAD

**Issue by Zulgrib** [nextcloud/server#558]
### Steps to reproduce

1- Log into your account
2- Be not greeted by ESET two factor auth while it could have been possible
### Expected behaviour

If ESET two step verification is available, user should receive an SMS with a code or open the eset 2 step auth app to get a temporary code
### Actual behaviour

You just get into your account
### Server configuration

**Operating system**:
32&64-bit versions of Microsoft Windows Server 2003, 2003 R2, 2008, 2008 R2, 2012, 2012 R2

More info about ESET two step auth here
http://www.eset.com/us/products/secure-authentication/

**Comment by MorrisJobke** [comment]
This should be implemented as app. See the other twofactor_* apps as example for this: https://github.com/nextcloud/twofactor_totp
