### ISSUE TITLE
login screen location

### ISSUE THREAD

**Issue by jsargent7089** [nextcloud/server#5582]
where is the login.html located

**Comment by dardelet** [comment]
There is no login.html but there is a [core/templates/login.php](https://github.com/nextcloud/server/blob/master/core/templates/login.php)

Is that what you were looking for ?

**Comment by jsargent7089** [comment]
no that not what im looking for. i edited that and nothing changed

**Comment by jsargent7089** [comment]
im trying to edit the login page

**Comment by DevGoslinga** [comment]
Restart your web server and clear browser cache.

**Comment by jsargent7089** [comment]
did not work

**Comment by DevGoslinga** [comment]
What exactly do you want to change?

**Comment by jsargent7089** [comment]
I want to reorder some of the links

**Comment by MorrisJobke** [comment]
> There is no login.html but there is a core/templates/login.php

That is the file. We only have this and apps could also inject some links there.
