### ISSUE TITLE
MariaDB SSL-Config breaks Nextcloud-Installation

### ISSUE THREAD

**Issue by anicoa** [nextcloud/server#5587]
### Steps to reproduce
1. Configure MariaDB with SSL support
2. Configure SSL-Support in ./config/config.php

`  'dbdriveroptions' => 
  array (
    1009 => '/etc/mysql/ssl/ca-cert.pem',
    1007 => '/etc/mysql/ssl/client-key.pem',
    1008 => '/etc/mysql/ssl/client-cert.pem',
  ), `

3. Start installation of nextcloud via web frontend

### Expected behaviour
- creation of database with schema-data, creation of tables etc.

### Actual behaviour

- Error message "SQLSTATE[HY000] [2002]" without further information in web frontend
- no further information in mariadb-, nextcloud-, php-, nginx-logs
- no creation of tables in database
- mysql-user gets created, user rights on database are granted

The call of self::getMDB2SchemaManager() in /lib/private/legacy/db.php line 172 is not successful.
After removing of ssl-config everything works as expected.

### Server configuration

**Operating system**: Ubuntu Server 16.04

**Web server:** nginx/1.10.3 (Ubuntu)

**Database:** 10.2.6-MariaDB-10.2.6+maria~xenial-log

**PHP version:** 7

**Nextcloud version:** 12

**Updated from an older Nextcloud/ownCloud or fresh install:** no

**Where did you install Nextcloud from:** source-packages

### Client configuration
**Browser:** Chrome, Firefox, Safari

**Operating system:** OS X

Further informations can be provided as needed

**Comment by ChristophWurst** [comment]
I'm closing this ticket because it hasn't received any updates in a long time. If this is still relevant, feel free to re-open or file a new ticket.

Thank you.
