### ISSUE TITLE
Bulk download for file versions

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/server#5588]
Coming from that feature request in the nextcloud forum: https://help.nextcloud.com/t/bulk-download-of-file-versions/14699

For different reasons it would be neccesary to review changes in file versions. For this I would like to see the possibility to download selected or all versions of a file at once. 

The feature request is to add the function of bulk operations (i.e. download or delete) selected or all file versions. I am not sure, but deletion maybe a dangerous operation for that.

Example in the picture. 

![grafik](https://user-images.githubusercontent.com/26707476/27772484-b4e127a0-5f63-11e7-9a9c-5529c2aede92.png)

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

</details>
