### ISSUE TITLE
Double settings entries in different parts of UI

### ISSUE THREAD

**Issue by Espina2** [nextcloud/server#5589]
In the current UI and since I remember to use Nextcloud I see two entries for settings, one on the bottom left, and another on the top right. Both have the same icon, but different behaviour. On the bottom left, the one setting we have is show hidden files, and one link to what I think is not even a setting "WebDAV". My suggestion is to move the settings that are on bottom for the settings area, since we don't expand panel any other place (correct me if I am wrong) and that unifies the User Interaction already on the app, and at the same site improve the User experience since We have all the settings in one place.

@nextcloud/designers @jancborchardt

**Comment by jancborchardt** [comment]
All user settings related to an app are in the bottom left area. The top right are 1) Personal settings in general and 2) Admin settings which only admins can see.

> since we don't expand panel any other place (correct me if I am wrong) 

We do this in basically every app: Mail, Calendar, Contacts, Tasks, Activity, etc.
And these are often things you want to change quickly (like showing hidden files) and then back. And you don't want to need to search through lots of other settings for it. They are deliberately placed in the context of the app. :)

**Comment by Espina2** [comment]
@jancborchardt 
What is the difference from User setting to Personal Settings? I think the Hidden files is a nice to have, why not remove the WebDav link and just have show/hidden files instead of the menu settings?

**Comment by jancborchardt** [comment]
> What is the difference from User setting to Personal Settings?

What do you mean by that? Personal settings are the settings concerning the user.

> I think the Hidden files is a nice to have, why not remove the WebDav link and just have show/hidden files instead of the menu settings?

Because as said, we have a settings section in almost every app. There might be more settings in the future for Files, and directly showing a setting in the sidebar is not really the proper place.

**Comment by Espina2** [comment]
> Because as said, we have a settings section in almost every app. There might be more settings in the future for Files, and directly showing a setting in the sidebar is not really the proper place.

This is exactly what I am saying!!

**Comment by jancborchardt** [comment]
There seems to be a misunderstanding. You proposed to

> just have show/hidden files instead of the menu settings

But since there might be more settings in the future and since every other app has this menu and makes use of it, the menu needs to stay.
