### ISSUE TITLE
Don't ask for a preview if we know we can't generate one.

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#559]
### Steps to reproduce
1. Open the web developer console and switch to the network tab
1. Open a folder containing files with exotic file extensions (.lnk per example)

### Expected behaviour

Only files of a media type which is supported by the preview system (and enabled classes) should be allowed to ask for a preview

### Actual behaviour

Every files is asking for a preview, leading to a lot of wasted resources when the file is not of a supported media type.
Even with parallel request processing, it can lead to too many requests, which then slow down the experience, especially on low powered devices.

### Concept

1. Send a list of supported media types to JS 
1. We should only ask for a preview if the media type of the file is on that list

I thought we already had what we need in PHP, but I don't think we do.
In `OCP\IPreview` we can get the list of providers or ask if a media type is supported by the Preview system, which then caches the answer.

While looking for solutions, I stumbled upon the forgotten [`previewSupported`](
https://github.com/nextcloud/server/blob/8c7d7d7746e76b77ad86cee3aae5dbd4d1bcd896/apps/files_sharing/lib/Controllers/ShareController.php#L299) on the public share list, so maybe we could take the same approach and request for that information to be sent for each file which would make it easy to know when to ask for a preview.

----
@rullzer @longsleep

**Comment by rullzer** [comment]
Maybe an extra webdav property would make sense here.

**Comment by oparoz** [comment]
@rullzer - Any cons to that approach?

**Comment by rullzer** [comment]
Well you have to request it explictly. And it puts a little bit of extra calculation on the server. But that way also other clients (mobile/desktop) can find out if they can request a preview. So from my POV well worth it.

**Comment by oparoz** [comment]
Very true about other clients, saving bandwidth and time on high latency networks.

**Comment by oparoz** [comment]
Thanks for the fix @icewind1991 !
