### ISSUE TITLE
Cannot access contacts via cardDAV

### ISSUE THREAD

**Issue by tsjfd** [nextcloud/server#5592]
### Steps to reproduce
1. install contacts app in nextcloud 11.0.3
2. add a new user 'kontakte' and copy the url for contacts
3. In Thunderbird / cardbook add a new addressbook  and choose the copied URL (https://MYSERVER/remote.php/dav/addressbooks/users/kontakte/contacts/) and enter username / password for nextcloud user 'kontakte'.

### Expected behaviour
Get access to contacts

### Actual behaviour
Error message in cardbook that access is not possible. It seems to be that the request is made by user 'kontakte' but nextcloud searches for the calendar using user 'admin' which results in a failure. Please have a look in the nextcloud log below. Accessing the contacts of the 'admin' user works. It seems to be that nextcloud always uses the admin account independently of the requested user. The cardbook request does not contain the admin user.

### Server configuration

**Operating system**: FreeBSD 11

**Web server:** nginx

**Database:** mysql

**PHP version:** 5.6.30

**Nextcloud version:** 11.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** pkg

**Signing status:**

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>contacts, calendar</summary>
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
$CONFIG = array (
  'instanceid' => 'XXX',
  'passwordsalt' => 'XXX',
  'secret' => 'XXX',
  'trusted_domains' => 
  array (
	  0 => 'XXX'
  ),
  'datadirectory' => '/usr/local/www/nextcloud/data',
  'overwrite.cli.url' => 'https://XXX',
  'dbtype' => 'mysql',
  'version' => '11.0.3.2',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => 'XXX',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => "0"
);
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Thunderbird 52.1.1

**Operating system:** Ubuntu 16.04

#### Web server error log
<details>
<summary>Web server error log</summary>

```
XXX - kontakte [03/Jul/2017:12:12:21 +0200] "PROPFIND /remote.php/dav/addressbooks/users/kontakte/contacts/ HTTP/1.1" 404 254 "-" "Thunderbird CardBook/19.7 Lightning/5.4.1.1"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"lhdPl9RMdefFjxXtvPQZ","remoteAddr":"XXX","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 Addressbook with name 'contacts' could not be found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/DavAclPlugin.php(85): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\DavAclPlugin->checkPrivileges('addressbooks\\\/us...', '{DAV:}read', 1, true)\\n#1 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\DavAclPlugin->propFind(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\CardDAV\\\\AddressBook))\\n#2 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1035): Sabre\\\\Event\\\\EventEmitter->emit('propFind', Array)\\n#4 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(955): Sabre\\\\DAV\\\\Server->getPropertiesByNode(Object(Sabre\\\\DAV\\\\PropFind), Object(OCA\\\\DAV\\\\CardDAV\\\\AddressBook))\\n#5 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(336): Sabre\\\\DAV\\\\Server->getPropertiesForPath('addressbooks\\\/us...', Array, 1)\\n#6 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPropFind(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#8 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PROPFIND', Array)\\n#9 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(231): Sabre\\\\DAV\\\\Server->exec()\\n#11 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#12 \\\/usr\\\/local\\\/www\\\/nextcloud\\\/remote.php(165): require_once('\\\/usr\\\/local\\\/www\\\/...')\\n#13 {main}\",\"File\":\"\\\/usr\\\/local\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/DavAclPlugin.php\",\"Line\":65,\"User\":\"admin\"}","level":0,"time":"2017-07-03T10:12:21+00:00","method":"PROPFIND","url":"\/remote.php\/dav\/addressbooks\/users\/kontakte\/contacts\/","user":"admin","version":"11.0.3.2"}
```
</details>

**Comment by tsjfd** [comment]
The URL was wrong! If I use https://MYSERVER/remote.php/carddav/addressbooks/kontakte/contacts/ it works... better documentation needed?

**Comment by creopard** [comment]
With NC12, Thunderbird v52 and addon Cardbook v19.7, the original posted URL scheme also works
https://server/remote.php/dav/addressbooks/users/username/Kontakte/
