### ISSUE TITLE
Ellipsis not working in all cases

### ISSUE THREAD

**Issue by pixelipo** [nextcloud/server#5594]
Noticed a resizing problem at certain combinations of folder name length and browser width (tested on Firefox):

Everything looks fine @320px:
![image](https://user-images.githubusercontent.com/4129927/27734615-dc040772-5d9b-11e7-97a1-7dea460b0fcb.png)

but there is a problem @480px:
![image](https://user-images.githubusercontent.com/4129927/27734635-fee1dd1e-5d9b-11e7-97d6-8bf9de708e13.png)

This happens when current folder has a very long filename. It seems that it's not ellipsized "soon enough"

CC @nextcloud/designers

**Comment by comradekingu** [comment]
@pixelipo I don't understand the problem. What would you expect it to look like?

**Comment by pixelipo** [comment]
It should ellipsize the title in the second screenshot because otherwise the "New" button drops into a second line

**Comment by jancborchardt** [comment]
This is related to the position of the upload button and the upload bar right next to it.

We can consider moving upload to the content area instead:
https://github.com/nextcloud/server/issues/4011#issuecomment-301176358

One issue is that it will not be easily available when scrolled down. (Also if we put it in the left navigation, it's too hidden on mobile.)

Maybe a floating action button on the bottom right like Android would work? My worry is that it doesn't align with the desktop view and thus will result in confusion.

**Comment by skjnldsv** [comment]
This should be fixed since my latest update on the breadcrumbs algorithm! Is this still occurring @pixelipo? :)

**Comment by MorrisJobke** [comment]
Can now be read in the collapsed menu:
![bildschirmfoto 2018-04-03 um 11 14 02](https://user-images.githubusercontent.com/245432/38240549-2914d1b8-3730-11e8-9daf-1402e2c618c4.png)
