### ISSUE TITLE
Popover for "new" on mobile can be out of screen

### ISSUE THREAD

**Issue by pixelipo** [nextcloud/server#5595]
There's an issue with popover on certain mobile sizes:
![image](https://user-images.githubusercontent.com/4129927/27734744-9ae6debc-5d9c-11e7-9cb4-e82289c9da6b.png)

popover requires at least 176px, and this is more than the space left over by breadcrumbs.

CC @nextcloud/designers

**Comment by jancborchardt** [comment]
Yeah, the popover should always be pretty much centered below the button, also to make it look better. Is there any sizing issue when doing it like that?

**Comment by jancborchardt** [comment]
I’d say a nice fix (also looks better visually) is to make the popover centered below the button.

#4011 I would consider separate, and speculative – because we have to solve how we display it on mobile first. Hiding in the app-navigation is not so good.
