### ISSUE TITLE
Nextcloud gets very slow since upgrade to 12.0.0

### ISSUE THREAD

**Issue by CordlessWool** [nextcloud/server#5597]
### Steps to reproduce
It is hard to produce, it is most time slow, but sometimes I am able to log in. Most time log in via web interface is possible but very slow (it takes minutes) for my account. The admin account is a bit faster but do also contain no data. My account protect more than 50GB. 

Directly after the upgrade I recognized no speed changes, but it seems to getting more worse.

### Expected behaviour
Login should be done in seconds and clients shouldn't be running in timeout
Have no speed problems with nextcloud 11.0.0, 11.0.1, 11.0.2 and 11.0.3 only deleting folders was slow with them and need much of memory

### Actual behaviour
Login is very slow
I try to increase usable memory for php but do not affect also restarting is not affecting

### Server configuration

**Operating system**:
Official docker container with version 12.0.0-fpm running Debian Jessi with latest updates as host 

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from nextcloud 11.0.3

**Where did you install Nextcloud from:**
docker hub

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**
Most ups also run with nextcloud 11.0.3 also removed some
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - drawio: 0.8.8
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_downloadactivity: 1.1.1
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - keeweb: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.4
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - socialsharing_diaspora: 1.0.1
  - socialsharing_email: 1.0.1
  - socialsharing_facebook: 1.0.1
  - socialsharing_googleplus: 1.0.1
  - socialsharing_twitter: 1.0.1
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.0
  - twofactor_u2f: 1.3.2
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - announcementcenter
  - files_accesscontrol
  - files_automatedtagging
  - onlyoffice
  - user_external
  - user_ldap

<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
Internal Information are replaced

  "system": {
        "instanceid": "instanceid",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "external ip",
            "internal ip"
        ],
        "datadirectory": "\/var\/www\/html\/data",
        "overwrite.cli.url": "external ip",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "dbname",
        "dbhost": "db ip",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "mail from",
        "mail_domain": "mail domain",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtphost",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "redis ip",
            "port": redis port,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 2
        },
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ]
    },

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
i am integrated dropbox and ftp but ftp is not working correct (is not reload data if open it) but also not work with nextcloud 11.0.3

**Are you using encryption:** yes/no
yes

[nextcloud_log.txt](https://github.com/nextcloud/server/files/1120624/nextcloud_log.txt)

**Comment by enoch85** [comment]
Have you set the Bruteforce app to allow local IPs or IPs that you use when you login?

Btw, 12.0.1 is out.

**Comment by CordlessWool** [comment]
It is only time by time, but I changed my nginx setting and it seems to be faster. Short time after I chnged the nginx settings I upgrade to 12.0.1. At first days it was slow again, but now it seems to be nextcloud is working normal. 

I think it should be working normal now. The problem was that nextcloud only get the ip of the nginx server and detected a brute force attack.
