### ISSUE TITLE
Contacts duplicate after upgrade to Nextcloud 12.0

### ISSUE THREAD

**Issue by ClepToManix** [nextcloud/server#5599]
### Steps to reproduce
Nothing to reproduce

### Actual behaviour
After i upgraded to version 12.0 all my contacts are duplicate in the contact seach bar.
Also my activity mails are sent twice
### Server configuration
nothing changed
**Operating system**:
Ubuntu 16.04
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
PHP 7.0
**Nextcloud version:** (see Nextcloud admin page)
12.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from an older Nextcloud
**Where did you install Nextcloud from:**
Updater
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
no result
</details>

**List of activated apps:**
<details>
<summary>Calendar</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

Here is an Screenshot of my problem:
![nextcloud](https://user-images.githubusercontent.com/25910686/27820328-724ac554-609e-11e7-93a6-da13e2c39c87.PNG)

**Comment by MorrisJobke** [comment]
cc @ChristophWurst @nickvergessen

**Comment by nickvergessen** [comment]
Sounds like an issue with the database returning duplicate entries on all ends?
I can not reproduce this on any end.

So unless you can provide more info I don't see a way we can help here.

**Comment by MorrisJobke** [comment]
No info so far: we are welcome to reopen this one here. Until then we will close this ticket.

**Comment by Hardy4next** [comment]
Please reopen it. We have the same Problem on Nextcloud 13. I don't know if this was already in Nextcloud 12.
![duplicated_contcts_next13](https://user-images.githubusercontent.com/36501132/36249413-ec51d970-123a-11e8-8552-b03539f5933b.png)
We use LDAP/AD-Integration, but all Contacts are dublicated (AD-Users and local Users)
Any idea to fix it?

Need any informations?

Greets Hardy

**Comment by raydelgg** [comment]
Nextcloud 13, new install, debian 9, ldap integration, same problem
