### ISSUE TITLE
Wrong redirect after login

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#560]
See https://github.com/owncloud/core/pull/25600

**Comment by mar1u5** [comment]
I think we will do a downstream from ownCloud before we release Nextcloud 10 so that we have 9.1.1 as base, which will be released in the next days by the ownClouders :wink:

**Comment by nickvergessen** [comment]
its already fixed downstream ;)

**Comment by MorrisJobke** [comment]
> its already fixed downstream ;)

@nickvergessen What is this ticket then about?

**Comment by nickvergessen** [comment]
To not forget to pull?

**Comment by MorrisJobke** [comment]
> downstream

We are downstream and they are upstream 😉 

That's why I was confused 😝
