### ISSUE TITLE
Error: cannot call methods on progressbar prior to initialization; attempted to call method 'value'

### ISSUE THREAD

**Issue by mehdi-song** [nextcloud/server#5602]
hi
when i upload files , in JavaScript console log (firefox) i see some errors like below:

![nc1](https://user-images.githubusercontent.com/19924924/27825270-440d137e-60c4-11e7-823b-07337bb58a86.png)

[java--.txt](https://github.com/nextcloud/server/files/1121702/java--.txt)

Operating system:
Centos 6.8 x64
Web server:
Server version: Apache/2.2.15 (Unix)
Database:
mysql 5.4
PHP version:
5.6
nextCloud version: 
12.0.1
Updated from an older nextCloud or fresh install:
Fresh install
Where did you install nextCloud from:
https://nextcloud.com/install/#instructions-server

**Comment by MorrisJobke** [comment]
We fixed quite some stuff there in the upcoming 12.0.3. Could I ask you to check it once that is out (or test the daily-stable12 tar ball)? I will close this for now and if it happens again we can have another look at this.

Thanks
