### ISSUE TITLE
Can't mount SMB storage

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#5604]
I tested it with Nextcloud 11.0.3 and the stable12 branch. Every time with the latest version of files_externals.

I set up a Samba server with following minimal configuration (otherwise I kept the default settings from Ubuntu):

````
[Nextcloud]
path = /home/schiesbn/smb
read only = no
writable = yes
browseable = yes
valid users = user1
create mask = 0640
directory mask = 0750
````

and created a user "user1" with `smbpasswd -a user1`

Using the command `smbclient -L //smbserver -U user1` on the Nextcloud server I can also access the samba server successfully. 

I have install "php-smbclient" on the nextcloud server, as recommended.

If I try to configure the external storage in the admin settings I get this error message in the Samba log and the indicator turns red:

````
[2017/07/04 14:20:19.314218,  3] ../auth/ntlmssp/ntlmssp_server.c:452(ntlmssp_server_preauth)
  Got user=[] domain=[] workstation=[] len1=0 len2=0
[..]
[2017/07/04 14:20:19.315249,  3] ../source3/auth/auth.c:178(auth_check_ntlm_password)
  check_ntlm_password:  Checking password for unmapped user []\[]@[] with the new password interface
[2017/07/04 14:20:19.315337,  3] ../source3/auth/auth.c:181(auth_check_ntlm_password)
  check_ntlm_password:  mapped user is: [UBUNTU]\[]@[]
[2017/07/04 14:20:19.315368,  3] ../source3/auth/auth.c:249(auth_check_ntlm_password)
  check_ntlm_password: guest authentication for user [] succeeded
````

Looks like Nextcloud sends a empty username to the samba server (although I added the right username to the configuration dialog)

I also tried to remove "php-smbclient" and configure the samba mount again. Now I get this error:

````
[2017/07/04 14:28:52.898910,  3] ../auth/ntlmssp/ntlmssp_server.c:452(ntlmssp_server_preauth)
  Got user=[GUEST] domain=[WORKGROUP] workstation=[POTATO] len1=24 len2=236
[2017/07/04 14:28:52.900640,  3] ../source3/auth/auth.c:178(auth_check_ntlm_password)
  check_ntlm_password:  Checking password for unmapped user [WORKGROUP]\[GUEST]@[POTATO] with the new password interface
[2017/07/04 14:28:52.900807,  3] ../source3/auth/auth.c:181(auth_check_ntlm_password)
  check_ntlm_password:  mapped user is: [UBUNTU]\[GUEST]@[POTATO]
[2017/07/04 14:28:52.900998,  3] ../source3/auth/check_samsec.c:400(check_sam_security)
  check_sam_security: Couldn't find user 'GUEST' in passdb.
[2017/07/04 14:28:52.901153,  2] ../source3/auth/auth.c:315(auth_check_ntlm_password)
  check_ntlm_password:  Authentication for user [GUEST] -> [GUEST] FAILED with error NT_STATUS_NO_SUCH_USER
[2017/07/04 14:28:52.901306,  3] ../source3/auth/auth_util.c:1602(do_map_to_guest_server_info)
  No such user GUEST [WORKGROUP] - using guest account
````

At the end it result in the same error. But this time it looks like the Nextcloud server sends the username "GUEST" to the samba server, even if added "user1" in the configuration dialog.

cc @icewind1991

**Comment by icewind1991** [comment]
What is the files_external configuration? (`occ files_external:export`)

**Comment by schiessle** [comment]
````
[
    {
        "mount_id": 1,
        "mount_point": "\/smb",
        "storage": "\\OCA\\Files_External\\Lib\\Storage\\SMB",
        "authentication_type": "password::password",
        "configuration": {
            "host": "192.168.56.102",
            "share": "Nextcloud",
            "root": "\/",
            "domain": "",
            "user": "schiesbn",
            "password": "nextcloud"
        },
        "options": {
            "encrypt": true,
            "previews": true,
            "enable_sharing": false,
            "filesystem_check_changes": 1,
            "encoding_compatibility": false
        },
        "applicable_users": [],
        "applicable_groups": []
    }
]

````

**Comment by Zjemm** [comment]
I have exactly the same issue, my SMB shares stopped working with the above symptons

**Comment by catdevelopment** [comment]
same problem here

**Comment by osscombat** [comment]
Same problem. Smb shares on Windows 10 b1703, NC 12.0.0 is hosted on Fedora 26, php-smbclient 0.9.0-1.fc26. Shares could be mounted using smbclient binary or via autofs without any problems.

**Comment by MorrisJobke** [comment]
@icewind1991 🏓

**Comment by Zjemm** [comment]
Looks like it's solved when filling in the domain Field

**Comment by osscombat** [comment]
yes, domain field should be filled in with the id host, it was windows10 in my case

**Comment by catdevelopment** [comment]
my setup: arch linux with samba 4.6.76
my machine's name: myserver.mydomain.local

i filled the field in NC as usual, in addition i filled the domain field with 'mydomain.local'

this does not work for me :(

**Comment by MorrisJobke** [comment]
Please ask first in the forums for help about the setup: https://help.nextcloud.com
