### ISSUE TITLE
Default allow GET POST PUT DELETE via .htaccess

### ISSUE THREAD

**Issue by wilfreddijksman** [nextcloud/server#5609]
After I installed a fresh Nextcloud installation via DirectAdmin Softaculous Auto Installer it takes several days to get Nextcloud working properly. Main issue were 403 errors in the JavaScript when moving, deleting files, closing the first time wizard, etc. Problem was the methods PUT and DELETE where by default **not** allowed on my (shared) server. I've fix this by adding the following to the .htaccess file in the root of Nextcloud:

```
<Limit GET POST PUT DELETE>
   Allow from all
</Limit>
```

I suggest to add this code by default to the .htaccess files to prevent problems described as above for other users.

### Steps to reproduce
1. Install Nextcloud on a server where PUT and DELETE are by default **not** allowed.
2. Try to move, delete files, close the first time wizard, etc.
3. Check the browser console for errors (see image).

![schermafbeelding 2017-07-05 om 09 38 29](https://user-images.githubusercontent.com/1773594/27854208-21d13176-6166-11e7-9c34-a662fa469e7d.png)
#### Translations screenshot
Kon map "Test" niet aanmaken => Unable to create folder "test"

### Expected behaviour
Move, delete files, close the first time wizard, etc.

### Actual behaviour
Error message (unable to create/forbidden), see screenshot and console.

### Server configuration

**Operating system**:
Linux Redhat (version unknown)
**Web server:**
Apache/2
**Database:**
MySQL
**PHP version:**
7.0.19
**Nextcloud version:**
12.0.0.29
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
DirectAdmin Softaculous Auto Installer
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Activity 2.5.2
Default encryption module 1.6.0
Deleted files 1.2.0
File sharing 1.4.0
First run wizard 2.1
Gallery 17.0.0
Log Reader 2.0.0
Monitoring 1.2.0
Nextcloud announcements 1.1
Notifications 2.0.0
Password policy 1.2.2
PDF viewer 1.1.1
Share by mail 1.2.0
Text editor 2.4.1
Theming 1.3.0
Update notification 1.2.0
Usage survey 1.0.0
Versions 1.5.0
Video player 1.1.0
Brute-force settings 1.0.2
Markdown Editor 1.0.1
Two Factor TOTP Provider 1.3.0
Auditing / Logging 1.2.0
Collaborative tags 1.2.0
Comments 1.2.0
External storage support 1.3.0
External user support 0.4
Federation 1.2.0
LDAP user and group backend 1.2.1
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => '******',
  'passwordsalt' => '******',
  'secret' => '******',
  'trusted_domains' => 
  array (
    0 => '******',
  ),
  'datadirectory' => '/home/******/domains/******/nextclouddata',
  'overwrite.cli.url' => 'https://******',
  'dbtype' => 'mysql',
  'version' => '12.0.0.29',
  'dbname' => '******',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '******',
  'dbpassword' => '******',
  'installed' => true,
  'default_language' => 'nl',
  'session_lifetime' => 60*20,
  'mail_domain' => '******',
  'mail_from_address' => 'nextcloud',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => '******',
  'mail_smtpport' => '465',
  'mail_smtptimeout' => 5,
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpname' => '******@******',
  'mail_smtppassword' => '******',
);
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Safari 10.1.1 (12603.2.4) for Mac
_Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/603.2.4 (KHTML, like Gecko) Version/10.1.1 Safari/603.2.4_

**Operating system:**
MacOS 10.12.5

#### Web server error log
_none_

#### Nextcloud log (data/nextcloud.log)
_none_

#### Browser log
<details>
<summary>Browser log</summary>

```
Failed to load resource: the server responded with a status of 403 (Forbidden)    http://******/remote.php/webdav/file
Failed to load resource: the server responded with a status of 403 (Forbidden)    http://******/remote.php/webdav/folder
```
</details>

**Comment by wilfreddijksman** [comment]
Suggested solution is deprecated:

> The directives provided by mod_access_compat have been deprecated by mod_authz_host. Mixing old directives like Order, Allow or Deny with new ones like Require is technically possible but discouraged. This module was created to support configurations containing only old directives to facilitate the 2.4 upgrade. Please check the upgrading guide for more information.

Source: https://httpd.apache.org/docs/2.4/mod/mod_access_compat.html

**Comment by wilfreddijksman** [comment]
As far as I understand the Apache documentation the only possible solutions with mod_authz_core.c are:
1. `Require all granted`
2. `Require method GET POST OPTIONS etc.`

Both solutions have down sides.
1. May undo for example an `Require valid-user` set up elsewhere.
2. Blocks all methods that are not in the list (in the example above for example PUT) and allows methods that may be blocked elsewhere.

Do someone have a better solution? If no I think it is better to close this issue.

**Comment by skjnldsv** [comment]
Relevant: #6449 ?
It also talk about mod_authz_core

**Comment by skjnldsv** [comment]
No solutions. Please use traditional nc installs as well as proper .htaccess generation (see docs).
All works fine for default standard setups
