### ISSUE TITLE
trust private non-experimental apps

### ISSUE THREAD

**Issue by andreas-p** [nextcloud/server#561]
There's a stalled issue https://github.com/owncloud/core/issues/17123 for OC about this.

Any app that's not uploaded, reviewed and rated is marked experimental and will be disabled after any core update. This very annoying for private apps that aren't candidates for official review.

The issue stated above mentions to mark those apps shipped in info.xml, but apparently this doesn't work any more (OC9/NC10). The <shipped> option would override any review and official ship flag in the app itself, which doesn't look desirable, it probably was removed for security reasons. 

So there should be another way to individually trust an app, either by some file like shipped.json for core apps now, or following @oparoz proposal to have a separate apps_path configured that's marked trusted (+1 from me for that).

**Comment by nickvergessen** [comment]
I guess both ways work, either a second shipped.json that is checked in addition to the normal shipped.json, or the folder separation.

No strong opinion here.

**Comment by andreas-p** [comment]
New versions same "disabled after upgrade" problem, so I decided to create a pull request https://github.com/nextcloud/server/pull/1527 . It implements the 'trust' keyword in apps_paths, which seems to me a little more natural and easier to maintain than another .json file.

**Comment by MorrisJobke** [comment]
This is now the default in 11 if you run on PHP 7. Only there we are able to check if the app could cause issues with the updater.

**Comment by MorrisJobke** [comment]
> This is now the default in 11 if you run on PHP 7. Only there we are able to check if the app could cause issues with the updater.

Sorry - I meant Nextcloud 12. See #239
