### ISSUE TITLE
Radiobuttons not align correctly since Nc 12

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#5611]
Since the merge of the personal and the admin settings the radio-buttons are now longer align correctly, see:

![checkboxes](https://user-images.githubusercontent.com/1589737/27857894-a0067fb2-6173-11e7-81e1-34464ad92949.png)

You can see this if you enable server side encryption in the admin settings, load the "default encryption module" app, re-login, go to the admin settings -> encryption -> enable the recovery key and then go to the personal settings -> security

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
@Henni you worked on the checkboxes, mind having a look at that? cc @blizzz can you think of anything you changed during the merge which could have affected this?

**Comment by Henni** [comment]
These inputs don't use the custom radio buttons.
This could be solved by applying `class="radio"` to both inputs.

**Comment by blizzz** [comment]
>  cc @blizzz can you think of anything you changed during the merge which could have affected this?

I did not modify any class names or such. Did not knowingly kick out any css file either.

**Comment by blizzz** [comment]
@schiessle I am happy that I am in the position to tell you: it is not a regression. At least  not from Nc 12. Since, in Nc 12 it looks broken the same way.

Admin:

![spectacle q12038](https://user-images.githubusercontent.com/2184312/27956885-1af63664-631c-11e7-9a49-2d0383186940.png)

Personal:

![spectacle c12038](https://user-images.githubusercontent.com/2184312/27956936-4f4cb154-631c-11e7-8d11-0b803abeed66.png)

**Comment by blizzz** [comment]
In Nc 11 it looks proper.

The difference is: in master (and i guess 12, did not verify, but i be surprised if it was different) is that a rule in core/css/inputs.css defines a min-height of 32px for the elements ``select``, ``button``, ``textarea`` and 🥁 ``input``. Disabling this real aligns text and checkbox properly. Last related commit is https://github.com/nextcloud/server/commit/05f39906166432676c7fce90b7b30cecc14798c0

Needs a proper CSS fix. I assume other things break when removing the min-height, but I also did not come far when  playing with line-height and vertical-align for the label.

**Comment by pixelipo** [comment]
That looks like a strange way to normalize - I mean, `width: 130px;`?

`min-height` shouldn't be necessary, but it will be hell to test all instances where this declaration is used...
