### ISSUE TITLE
Broken app update notification

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#5627]
Today I got on Nextcloud 11.0.3 a notification that there is a update for the Notes app.

This is how it looked in the web interface:

![update info](https://user-images.githubusercontent.com/1589737/27901175-4929fcdc-6231-11e7-9afd-232413d3011b.png)

and this is the notification on the Nextcloud Desktop client 2.3.2:

![update notes deskop](https://user-images.githubusercontent.com/1589737/27901195-71334c60-6231-11e7-8a5c-34e2103779f2.png)

Any idea what's wrong here?

**Comment by MorrisJobke** [comment]
Haven't seen this for a while. Let's close this for now.

Or did you @nickvergessen ?

**Comment by nickvergessen** [comment]
I never have seen this.
