### ISSUE TITLE
Was access to generic S3 storage removed?

### ISSUE THREAD

**Issue by febs** [nextcloud/server#5632]
According to the official documentation, it used to be possible to use Amazon S3 "or compliant" storage:

![image](https://user-images.githubusercontent.com/604435/27909218-f2534246-624f-11e7-8d32-9bc7748361ca.png)

The "region" field is marked as optional and the storage name is "Amazon S3 and compliant".

Now, in version 12, it is called only "Amazon S3" and the "Region" field is not optional:
![image](https://user-images.githubusercontent.com/604435/27909303-54b10270-6250-11e7-897f-4b3e237b0b99.png)

Is it still possible to add any S3 storage (like, an on-premise one), and how? Or was that support removed for any reason?

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by icewind1991** [comment]
The region field is still optional and s3 compatible server are still supported
