### ISSUE TITLE
Allow associating tags in gallery (tile) view and in the image fullscreen view

### ISSUE THREAD

**Issue by Tormen** [nextcloud/server#5634]
This specific enhancement request can be seen as part of the more general issue #4842 

### Steps to reproduce
1. login
2. upload images
3. visit /apps/gallery/#
4. Try to associate a tag to an image

### Expected behaviour
There should be:
* in the tile gallery view to select (multiple) and associate tags
* in the tile gallery view to right click an image and select "associate tags"
* in the fullscreen view of a single image have an entry "tags" in the misc menu "..." or ideally right away a button with a tags-icon (like you have the share-icon)

Clicking on it should make a div visible (like you already do for the sharing) which should contain:
* an autocomplete textbox allowing to search and select tags
* and to help with quickly selecting tags:
** a list of the last 5-10(?) used tags (this should include freshly created, but not yet associated tags) - timestamp of creation and timestamp of tag-association should be sorted and top 5-10 should be displayed (REASONING: if the user just used some tags, maybe he/she wants to continue doing so)
** a list of the top 5-10 most used (manually(!) associated) tags (REASONING: if there are tags a person applies OFTEN, then maybe it is likely that the person wants to apply this tag again)
This 

### Actual behaviour
I could not find any way to associate tags from the gallery view.
And looking at simply the file-names of smartphone image files, does not tell me how the picture looks like and hence what tags I would like to associate to the file ;)

### Server configuration

**Operating system**: Centos 7.3

**Web server:** Nginx + FPM php7

**Database:** mariadb

**PHP version:** 7

**Nextcloud version:** v12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** download latest zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocoeiy4ke5qw",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/usr\/share\/nginx\/html\/nextcloud\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpdebug": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "gmail.com",
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local only

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:** firefox

**Operating system:** archlinux 64bit

**Comment by MorrisJobke** [comment]
This needs to be done in the gallery app itself. Could I ask you to open this in the gallery app bug tracker? https://github.com/nextcloud/gallery/issues

Thanks
