### ISSUE TITLE
[sharebymail] Add "reply-to"-tag to emails sent to person a file is shared to

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#5637]
If you share a file with a user by the sender is:

`Max Mustermann via Nextcloud` 

From a user-perspective, I'd expect replying to this email does send to the users-mail address (if provided in personal settings) and not send to "noreply@cloud.example.com". Of course we cannot send by this user-defined email address, since we would then need to ask for SMTP-credentials 😏

But what about providing the users-mail address as `reply-to`-tag in the email? Would that work?

@schiessle

**Comment by schiessle** [comment]
Should already be there, see: https://github.com/nextcloud/server/blob/master/apps/sharebymail/lib/ShareByMailProvider.php#L411

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/pull/24978
