### ISSUE TITLE
Remote share emails doesn't show what's shared.

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#5639]
![screenshot from 2017-07-06 18 42 49](https://user-images.githubusercontent.com/4511254/27922384-27945d16-627b-11e7-995e-47e6fb972e31.png)

@MorrisJobke You implemented this, maybe you know what's wrong?

NC 12.0.0

**Comment by MorrisJobke** [comment]
cc @nickvergessen @schiessle @nextcloud/sharing

**Comment by schiessle** [comment]
@enoch85 is is correctly displayed in the web interface?

**Comment by enoch85** [comment]
@schiessle Good question. Yes they are.

![screenshot from 2017-07-07 16 50 06](https://user-images.githubusercontent.com/4511254/27963152-6654944e-6334-11e7-8cd3-3f24dbbacdd1.png)

**Comment by nickvergessen** [comment]
Please try daily or current master

**Comment by enoch85** [comment]
@nickvergessen `git clone https://github.com/nextcloud/server.git` I guess?
