### ISSUE TITLE
App Category Newest + Updated

### ISSUE THREAD

**Issue by dragonchaser** [nextcloud/server#5647]
Featurerequest: It would be nice to have two extra categories in the app administration page for "Recently Updated" and "New" apps.

**Comment by MorrisJobke** [comment]
@nextcloud/designers Do you have an opinion on this? I would like to not add to many categories there, but maybe "featured" instead of "new" makes sense?

**Comment by dartcafe** [comment]
Why not a category "All apps" - which I am missing personally - and make it sortable by rating / name / last update?

**Comment by MorrisJobke** [comment]
The all apps is somehow solved in 13: #126

The sorting is part of #3194

Let's continue in #3194 for the app management general enhancement ticket and close this one here for now.
