### ISSUE TITLE
https = (blocked:csp)

### ISSUE THREAD

**Issue by jacekjaros** [nextcloud/server#5651]
Hi,

I use Varnish and Hitch which rewrite http traffic to https (by default). In my nextcloud I set options to force https protocol but some elements are still served via http (instead of https) and browser block them because of Content Security Policy.

### Steps to reproduce
1. Open login page in browser :)

### Expected behaviour
I should get wallpaper and logo at login page

### Actual behaviour
Browser block 
```
http://my.nextcloud.domain/index.php/apps/theming/loginbackground?v=16
and
http://my.nextcloud.domain/core/img/logo.svg?v=16
```

### Server configuration

**Operating system**:
Dabian 8

**Web server:**
- hitch (port 443) - proxy all traffic to varnish
- varnish (port 80, rewrite all http requests to https, proxy traffic to apache)
- apache (port 81)

**Database:**
Postgresql

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Where did you install Nextcloud from:**
Git

### config.php
```
  'overwrite.cli.url' => 'https://my.nextcloud.domain',
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'overwriteprotocol' => 'https',
```

**Comment by MorrisJobke** [comment]
> 'forcessl' => true,
>   'forceSSLforSubdomains' => true,

We don't have those config switches. So those are not needed.

**Comment by MorrisJobke** [comment]
Try also set the the `X-Forwarded-Proto` header in your proxy to indicate the protocol, because we also use that.

I guess somewhere in your proxy chain this information gets lost.

Please also ask for help in the forums, because this is more a setup/configuration issue, than an actual bug: https://help.nextcloud.com/
