### ISSUE TITLE
Reanimate Imprint 2

### ISSUE THREAD

**Issue by hollerauer** [nextcloud/server#5652]
Original issue (https://github.com/nextcloud/server/issues/5626) was closed in favor of a pull request (https://github.com/nextcloud/apps/pull/36), which was also closed because it was not bug free.

The workaround (use external site) is not meeting the "high standards for quality" (@MariusBluem), which nextcloud is trying to achieve, at all.

Please find a solution how to bring the functionality the imprint app once had back to latest NC release!

This is not a nice to have feature, but a must have for every private or public installation, which can be accessed web based.

**Comment by LukasReschke** [comment]
Please track this in the apps repository or the forum instead the server issue tracker. Thank you.

**Comment by hollerauer** [comment]
I've to admit that this is the wrong place for this issue. Will post it in nextcloud/apps repository
