### ISSUE TITLE
Checkboxes don't work if white theming color

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#5654]
1. Use FFFFFF as theming color
2. Open sharing admin page

<img width="777" alt="screen shot 2017-07-08 at 12 25 37" src="https://user-images.githubusercontent.com/878997/27984521-9ebbea0e-63d8-11e7-9812-276e48271c86.png">

**Comment by MorrisJobke** [comment]
🙈 

cc @juliushaertl @nextcloud/designers Ideas?

**Comment by juliushaertl** [comment]
Hm, that is a regression maybe from the move to SCSS. We had a fallback for bright colors in Nc11. I'll have a look.

**Comment by MariusBluem** [comment]
P.S: Same for RadioBoxes ;)

**Comment by tobiasKaminsky** [comment]
As we use in android client also the theming, this looks kind of ugly ;-)
@juliushaertl can you explain me how you handle the fallback on bright colors?
We have a threshold to distinguish if we use black or white font, but I am unsure if (and how) we can use this.

![2017-08-11-100235](https://user-images.githubusercontent.com/5836855/29205393-d7e5eb36-7e7c-11e7-8f9e-d35840d72ddf.png) ![2017-08-11-100825](https://user-images.githubusercontent.com/5836855/29205438-151f7db4-7e7d-11e7-8bd9-89ae46f68802.png)

**Comment by juliushaertl** [comment]
> As we use in android client also the theming, this looks kind of ugly ;-)
> @juliushaertl can you explain me how you handle the fallback on bright colors?
> We have a threshold to distinguish if we use black or white font, but I am unsure if (and how) we can use this.

This is basically what is used in the theming app to check if a color is to bright:
https://github.com/nextcloud/server/blob/master/apps/theming/lib/Util.php#L78-L85

**Comment by tobiasKaminsky** [comment]
I used this one: https://github.com/nextcloud/server/blob/master/apps/theming/lib/Util.php#L63

We currently "only" have one check "isDarkTheme" which is using 0.5 as theshold.

**Comment by juliushaertl** [comment]
invertTextColor is used to check if the text on a background that has the primary color needs to be black or white. 

elementColor is meant to set the primary color to grey **for some ui elements** that would not be visible if the theming color is to bright. This mechanism is currently broken (that is what this issue is about).

**Comment by MorrisJobke** [comment]
@juliushaertl but it works for the login button for example. There the button is then grey instead of white. 🤔

**Comment by MorrisJobke** [comment]
Fixed in #6082

**Comment by MorrisJobke** [comment]
Backport to stable12 is in #6359
