### ISSUE TITLE
QR codes for login details

### ISSUE THREAD

**Issue by GIJack** [nextcloud/server#5659]
I would like a format for setting up an account on an android phone from a QR code on the server web page.

Ideally, that the "new app password" link would create a QR code with an embedded

**Comment by MorrisJobke** [comment]
cc @nextcloud/android @nickvergessen @LukasReschke

**Comment by AndyScherzinger** [comment]
Sorry @MorrisJobke ... https://github.com/nextcloud/android/pull/253 we implemented and shipped support for this (in case a QR reader is installed om the phone) nearly a year ago 😁

**Comment by tobiasKaminsky** [comment]
Damn...I was too late ;-)

**Comment by AndyScherzinger** [comment]
Took me a while to find the pull request again ;) - Implemented in last year's hack week at the Nextcloud conference 🚀

**Comment by AndyScherzinger** [comment]
@MorrisJobke you still need to implement the server side...

**Comment by AndyScherzinger** [comment]
also pining @nextcloud/ios for custom URL support

@MorrisJobke We do something like this:
```
nextcloud://login/user:<username>&password:<password>&server:<serveraddress>
```

While atm we use cloud:// which is a build config value so we should decide which one to use and if the URL pattern is fine for everyone. We should keep the "login" key word so we can add further magic urls e.g. for app deep links :)

**Comment by mario** [comment]
@AndyScherzinger the server already implements (and the client, to a degree) support for web-based login via nc://login/ mechanism, so I guess the pattern is nc:// ;)

The iOS app implements the same :)

**Comment by GIJack** [comment]
simply use:

qrencode url:username:password -o code.png

and just embed the resulting qrcode into the webpage. Easy.

**Comment by ChristophWurst** [comment]
Duplicate of https://github.com/nextcloud/server/issues/429.
