### ISSUE TITLE
File link open file list instead of the file

### ISSUE THREAD

**Issue by grasph** [nextcloud/server#5661]
### Steps to reproduce

1. Create a demo instance
2. Open details dialog of Nextcloud Manual.pdf
3. Click on the copy link icon and copy the link
4. Open the link with your browser.

### Expected behaviour

The file should be opened, showing the manual in the above example

### Actual behaviour

Opens the directory containing the files.

### Server configuration

Reproduced on a demo instance created on July 9, 17.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```

</details>

### Client configuration

**Browser:**

Firefox 52.2.0

**Operating system:**

Debian Jessie

**Comment by MorrisJobke** [comment]
Duplicate of https://github.com/nextcloud/server/issues/1467
