### ISSUE TITLE
Moving a shared folder deletes all documents inside that folder using the Desktop Client for the Mac

### ISSUE THREAD

**Issue by mm8974** [nextcloud/server#5674]
### Steps to reproduce using Finder on the Mac in conjunction with the Mac Nextcloud Desktop client
1. Have an administrative user create a new folder "Project1" and share it with a group of five people
2. Have one of the users drop 8.9 gigabytes of data (1,400 files) from a Dropbox folder into this new "Project1" folder
3. That user later creates a folder to organizer their folders call "Projects".   I refer to this as organization folders.  They are folders inside the root of the Nextcloud shared folder but they are not shared with anyone else.
4. They then drag and drop the "Project1" folder into "Projects" to move "Project1" from the root of the Nextcloud shared folder.
5. Folders and documents that were in the "Project1" folder are deleted from all people who share that folder and have it synched to their computers using the Nextcloud desktop app.
6. Log into the Nextcloud webgui and look for the files as a normal user.  Nothing there
7. Log into the Nextcloud webgui as the user that deleted the files and try to undelete them.  Nothing is recoverable.
8. Log into the Nextcloud webgui as the admin user that owns the "Project1" folder and try to undelete anything.  Nothing is recoverable and folder is empty.

### Expected behaviour
When a folder is shared with a user, it appears in the root of the Nextcloud sync folder.  We have the ability to create a folder for organizing folders shared with me.  On a Mac using the Finder, I simply create a new folder called "Projects" and I drag and drop the shared folder from the root of the Nextcloud shared folder into "Projects".   We have done this numerous times with no problems.  However...

### Actual behaviour
Last Friday morning a user moved a shared folder "Project1" with 8.9 GB of data and 1,400 files into "Projects" and the server received a 'delete' command and that deleted all of the files out of the server and all users running the Nextcloud desktop client.  The Activity app shows that the end user deleted the files and they have been removed from the server and were not available for recovery in Deleted Items.

### Server configuration

**Operating system**: 
Amazon AMI Linux 2017.03 - Linux version 4.9.27-14.31.amzn1.x86_64

**Web server:**
Apache - Apache/2.4.25 (Amazon)

**Database:**
mysqld  Ver 5.5.56 for Linux on x86_64 (MySQL Community Server (GPL))

**PHP version:**
PHP 5.6.30 

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud server version - 11.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgraded from ownCloud 8.2 to Nexcloud 9.0.54 manually while referencing https://help.nextcloud.com/t/migrating-from-owncloud-to-nextcloud/551
Upgraded from Nextcloud 9 > Nextcloud 10 manually also
Upgraded from Nextcloud 10.0.2 to Nextcloud 11.0.1 using the updater gui
Upgraded from Nextcloud 11.0.1 to Nextcloud 11.0.2 and later 11.0.3 using the updater gui

**Where did you install Nextcloud from:**
We installed Nextcloud using downloads from the nextcloud.com website or via the updater service

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_external: 0.4
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - files_automatedtagging
  - files_retention
  - gallery
  - user_ldap
  - user_saml
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oc703c434955",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "zzz.com",
            "zzz2.com"
        ],
        "datadirectory": "zzz",
        "dbtype": "mysql",
        "version": "11.0.3.2",
        "installed": true,
        "forcessl": true,
        "maxZipInputSize": 838860800,
        "allowZipDownload": true,
        "theme": "pkdocs",
        "maintenance": false,
        "mail_smtpmode": "php",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "user_webdavauth_url": "https:\/\/fileserver.zzz.com",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "cron_log": true,
        "dbname": "zzz",
        "dbhost": "zzz",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trashbin_retention_obligation": "auto",
        "updater.release.channel": "stable",
        "updatechecker": true,
        "knowledgebaseenabled": true,
        "skeletondirectory": "\/var\/www\/html\/nextcloud\/core\/skeleton"
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
We use Safari and Google Chrome however the issues have been with the Nextcloud Mac client version - 2.2.4 (build 1).

**Operating system:**
macOS version - 10.12.5

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Fri Jul 07 14:10:47.738323 2017] [:error] [pid 12788] Exception TypeError: "'NoneType' object is not callable" in <bound method Cursor.__del__ of <MySQLdb.cursors.Cursor object at 0x55aa82d13e90>> ignored
[Fri Jul 07 14:27:24.261185 2017] [:error] [pid 22391] Exception TypeError: "'NoneType' object is not callable" in <bound method Cursor.__del__ of <MySQLdb.cursors.Cursor object at 0x55aa83226390>> ignored
[Fri Jul 07 17:25:37.763487 2017] [:error] [pid 24037] Exception TypeError: "'NoneType' object is not callable" in <bound method Cursor.__del__ of <MySQLdb.cursors.Cursor object at 0x55aa8368cf10>> ignored
[Fri Jul 07 17:26:05.099763 2017] [:error] [pid 24401] Exception TypeError: "'NoneType' object is not callable" in <bound method Cursor.__del__ of <MySQLdb.cursors.Cursor object at 0x55aa83396f10>> ignored
[Fri Jul 07 17:27:33.463613 2017] [:error] [pid 24216] Exception TypeError: "'NoneType' object is not callable" in <bound method Cursor.__del__ of <MySQLdb.cursors.Cursor object at 0x55aa833dbe90>> ignored
[Fri Jul 07 19:00:44.035636 2017] [core:notice] [pid 15545] AH00052: child pid 8363 exit signal Segmentation fault (11)
[Fri Jul 07 19:00:46.073690 2017] [core:warn] [pid 15545] AH00045: child process 8364 still did not exit, sending a SIGTERM
[Fri Jul 07 19:00:48.086989 2017] [core:warn] [pid 15545] AH00045: child process 8364 still did not exit, sending a SIGTERM
[Fri Jul 07 19:00:50.092432 2017] [core:warn] [pid 15545] AH00045: child process 8364 still did not exit, sending a SIGTERM
[Fri Jul 07 19:00:52.101663 2017] [core:error] [pid 15545] AH00046: child process 8364 still did not exit, sending a SIGKILL
[Fri Jul 07 19:00:53.123362 2017] [mpm_prefork:notice] [pid 15545] AH00169: caught SIGTERM, shutting down
[Fri Jul 07 19:00:55.157698 2017] [suexec:notice] [pid 8819] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Fri Jul 07 19:00:55.437079 2017] [auth_digest:notice] [pid 8820] AH01757: generating secret for digest authentication ...
[Fri Jul 07 19:00:57.104266 2017] [mpm_prefork:notice] [pid 8820] AH00163: Apache/2.4.25 (Amazon) OpenSSL/1.0.1k-fips mod_wsgi/3.5 Python/2.6.9 PHP/5.6.30 configured -- resuming normal operations
[Fri Jul 07 19:00:57.104325 2017] [core:notice] [pid 8820] AH00094: Command line: '/usr/sbin/httpd'
[Fri Jul 07 21:47:39.338140 2017] [:error] [pid 770] Exception TypeError: "'NoneType' object is not callable" in <bound method Cursor.__del__ of <MySQLdb.cursors.Cursor object at 0x55b7a2b273d0>> ignored
[Sat Jul 08 16:09:18.749252 2017] [:error] [pid 23345] Exception TypeError: "'NoneType' object is not callable" in <bound method Cursor.__del__ of <MySQLdb.cursors.Cursor object at 0x55b7a52a32d0>> ignored
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
There is nothing during the time of this problem.
```
</details>

####Web Admin GUI Logging Errors
<details>
<summary> Admin GUI Logging Errors</summary>

```
Error    PHP    Call to a member function getCache() on null at /var/www/html/nextcloud/apps/files_sharing/lib/Cache.php#69    2017-07-07T16:42:06-0600
```
</details>

**Comment by mm8974** [comment]
Had a similar situation last week where a user renamed a subfolder and it was deleted on all other computers that were synching that folder.

**Comment by MorrisJobke** [comment]
We fixed this in 12.0.1 - Could you try it with this version again? I will close this ticket. If this still is a problem we will reopen it.

**Comment by tessus** [comment]
@MorrisJobke did you also fix this in 11.0.4?

**Comment by MorrisJobke** [comment]
> @MorrisJobke did you also fix this in 11.0.4?

Sadly I can't say that, because I can't find the PR anymore (at least not quickly). I only know for sure, that we fixed it in stable12 and don't know if it was also ported to stable11, but I guess so.

**Comment by major5012** [comment]
Please reopen this ticket as a similar problem has occurred on our systems.  This time while running server 12.0.3 and the current macOS desktop client 2.3.3 (build 84).

https://help.nextcloud.com/t/moving-a-shared-folder-breaks-the-link-to-the-shared-folder-and-deletes-files/24935

**Comment by major5012** [comment]
Lots of these Fatal webdav errors in the log:

Fatal | webdav | Sabre\DAV\Exception\MethodNotAllowed: The resource you tried to create already exists/NCPATH/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 590: Sabre\DAV\Server->createCollection('files/USERWITHPROBLEMS/A...', Object(Sabre\DAV\MkCol))[internal function] Sabre\DAV\CorePlugin->httpMkcol(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/NCPATH/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)/NCPATH/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method MKCOL', Array)/NCPATH/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/NCPATH/apps/dav/lib/Server.php - line 258: Sabre\DAV\Server->exec()/NCPATH/apps/dav/appinfo/v2/remote.php - line 33: OCA\DAV\Server->exec()/NCPATH/remote.php - line 162: require_once('/NCPATH/...'){main}
-- | -- | --

**Comment by major5012** [comment]
And this one:


Error | no app in context | Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`parent`,`checksum`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0' with params ["1", "2", 1513640546, -1, "5a385262a4314", 1513640546, 31, 140696, "", "c271eb30d44d23a7e0601fc109a81953", "files_versions\/Active Projects\/ONE_OF_PROBLEM_SHARED FOLDERS", 37, 37, "c271eb30d44d23a7e0601fc109a81953"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '37-c271eb30d44d23a7e0601fc109a81953' for key 'fs_storage_path_hash'
-- | -- | --

**Comment by major5012** [comment]
Is this similar?  https://help.nextcloud.com/t/nextcloud-client-move-shared-folder/21471
