### ISSUE TITLE
Avoid look-alike characters in shared link token

### ISSUE THREAD

**Issue by m-khvoinitsky** [nextcloud/server#5688]
From time to time, I need to manually type a shared link. Such situations are usually rare but urgent.

Bonus point: use only lowercase alphabetical characters, i. e. no uppercase and no digits because it impedes typing the token especially on mobile touchscreen keyboard.

It's better to make token longer to have same complexity rather than use bigger but inconvenient character sets.

This issue duplicates Discourse topic: https://help.nextcloud.com/t/feature-request-avoid-look-alike-characters-in-shared-link-token/15227 — I haven't found consistent way of making feature requests, I apologize for the extra noise.

**Comment by MorrisJobke** [comment]
cc @nextcloud/sharing @nextcloud/designers

**Comment by jancborchardt** [comment]
Yes, absolutely. We use a function like that for the Video calls app share link, right @ivansss @nickvergessen?

Could we move that to core so we can use it for file share links @schiessle and for others like Calendar share links @georgehrke

**Comment by nickvergessen** [comment]
Is it really necessary to ping 4 people for something like this? 😿

**Comment by jancborchardt** [comment]
Since we want it done in _both_ sharing links and Calendar links, and the implenentation comes from another app - yes.

That's how remote communication works, no need to be grumpy. ;) I also get a lot of notifications.

**Comment by georgehrke** [comment]
cc @tcitworld about public calendar sharing

**Comment by tcitworld** [comment]
https://github.com/nextcloud/server/pull/5734#issuecomment-315755720
