### ISSUE TITLE
WebLogin Flow for android

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#5693]
This is how the weblogin flow looks like on android:
- enter url
- webview with login opens
- grant access
- enter credentials
![2017-07-12-122055](https://user-images.githubusercontent.com/5836855/28114405-0fdc5842-6701-11e7-9d63-59ac6fad4d5b.png) ![2017-07-12-122106](https://user-images.githubusercontent.com/5836855/28114404-0fd50100-6701-11e7-9e58-3dc27d433acb.png)
![2017-07-12-122119](https://user-images.githubusercontent.com/5836855/28114402-0fb7fd1c-6701-11e7-8ce0-e88a673125eb.png) 

I think this a bit confusion for a new user. On second screen "Mozilla/5.0 (Android) ownCloud-android/1.4.3" is shown. I know this is the user agent we send and that we still use owncloud for backward compatibility.
Also, at least for me, the order is not intuitive. You first have to login and then you are allowed to grant access.
@nextcloud/designers for input
Android pr: https://github.com/nextcloud/android/pull/1148

**Comment by jancborchardt** [comment]
Yeah, we should just call it "Nextcloud Android app" not the technical user agent.

Also it should have a h2 header: "Grant app access to account", or something similar.

(I assume the missing logo and the button color is cause of theming?)

**Comment by tobiasKaminsky** [comment]
While implementing it @LukasReschke had the idea that we should use the manufacture + phone device name as identifier, so this can better be distinguished on the authorized sessions section in personal settings. (Samsung S5, Oneplus 3, or similar)

Where should this h2 header be? as part of android ui oder as part of the server login page?

This is a screenshot from our cloud:
![2017-07-17-125017](https://user-images.githubusercontent.com/5836855/28265137-813ef3e6-6aee-11e7-89a8-caa92dd5655a.png)

**Comment by MorrisJobke** [comment]
> Where should this h2 header be? as part of android ui oder as part of the server login page?

Clearly server.

**Comment by MariusBluem** [comment]
Device should be called "**Max's** Galaxy S8" if possible ...

**Comment by tobiasKaminsky** [comment]
We do not know the user on this time... :-/

**Comment by MariusBluem** [comment]
...and renaming app passwords after that is not possible, right 😁

**Comment by tobiasKaminsky** [comment]
As this is in the personal page of an user, I guess that then all devices would be called "Max's Galaxy/iPhone/Tablet..." which than makes this a bit useless, or do I miss something?

**Comment by MariusBluem** [comment]
> As this is in the personal page of an user, I guess that then all devices would be called "Max's Galaxy/iPhone/Tablet..." which than makes this a bit useless, or do I miss something?

Agreed...

**Comment by tobiasKaminsky** [comment]
Tested it on a very low-end device, I get this:
![2017-07-18-155112](https://user-images.githubusercontent.com/5836855/28320734-9b2b270a-6bd1-11e7-9fdf-043c45a33a52.png) ![2017-07-18-155155](https://user-images.githubusercontent.com/5836855/28320735-9b38467e-6bd1-11e7-8d73-eb4ba08c34f4.png)

**Comment by MorrisJobke** [comment]
> Tested it on a very low-end device, I get this:

What screen size do you have?

**Comment by MariusBluem** [comment]
@tobiasKaminsky Is Android <4.3 still supported?

**Comment by tobiasKaminsky** [comment]
> What screen size do you have?

 240 x 320 px :fearful: 

> Is Android <4.3 still supported?

Yes, we currently support back to 4.0

**Comment by jancborchardt** [comment]
A small styling fix PR for the Access page is at https://github.com/nextcloud/server/pull/6091

**Comment by MorrisJobke** [comment]
This is fixed, right? The glitch should be addressed separately.
