### ISSUE TITLE
maj parametre webdavurl

### ISSUE THREAD

**Issue by fbclol** [nextcloud/server#5698]
Hello,

Update the webdavurl url in the html in my example:
Old: https://example.fb.fr/remote.php/webdav/
New: https://example.fb.fr/remote.php/dav/
<Input id = "webdavurl" xxxxxxx>

Update the technical documentation for the solution parameter on the certificate
Servercert is obsolete trust_ca_cert and use trust_server_cert for ssl self signed

Regards
Franck

**Comment by tflidd** [comment]
Thanks for the hint. Can you also link to the html example? If it is in the documentation, please put this directly in the documentation bugtracker https://github.com/nextcloud/documentation/issues

**Comment by fbclol** [comment]
I do not know how to link the document to the project

**Comment by MorrisJobke** [comment]
@fbclol Could I ask you to open this in the documentation repo? Thanks

https://github.com/nextcloud/documentation/issues
