### ISSUE TITLE
Because Ubuntu using UUID in fstab, update needed to Webdav Tutorial

### ISSUE THREAD

**Issue by qwertyuser1983** [nextcloud/server#5700]
Nextcloud-Snap user here, 

Please update https://docs.nextcloud.com/server/11/user_manual/files/access_webdav.html, 

for Creating WebDAV Mounts on the Linux Command Line part, to include how to set up with UUID, because it create problem in fstab, making system unable to boot normally. :(

 
### Steps to reproduce
1. Follow Creating WebDAV Mounts on the Linux Command Line part in https://docs.nextcloud.com/server/11/user_manual/files/access_webdav.html. At this time, system will complain cannot read line in fstab
2. Restart system

### Expected behaviour
Tell us what should happen
1. System boot normally

### Actual behaviour
Tell us what happens instead
1. System boot to emergency mode

### Server configuration

**Operating system**:
Bodhi Linux 16.04

**Web server:**
Personal PC

**Database:**
Nextcloud-Snap

**PHP version:**
Nextcloud-Snap

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud-Snap 11.03

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install

**Where did you install Nextcloud from:**
Nextcloud-Snap

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
Please ask in the forums for help about setup: https://help.nextcloud.com/
