### ISSUE TITLE
Add Search Functionality to the Nextcloud Apps Menu

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#5701]
### Expected behaviour in Nextcloud 12
[A Search bar on the left hand side of Nextcloud Apps.  Click for example.](http://imgur.com/a/3zkRu)

### Actual behaviour in Nextcloud 12
There is no search functionality, just various directories such as "Your Apps" and "Enabled Apps"

**Comment by tcitworld** [comment]
The search bar is at top right of the interface.

**Comment by sunjam** [comment]
[You sure about that?  I've never seen any search at the top right when browing through apps on my nextcloud.  Screen cap here.](http://imgur.com/a/Qn0rb)

**Comment by MorrisJobke** [comment]
Yes - it works (it is in the blue header):

![bildschirmfoto 2017-07-19 um 00 27 26](https://user-images.githubusercontent.com/245432/28342520-1418e656-6c19-11e7-841d-cf2e8db06873.png)
