### ISSUE TITLE
Error trying to install server in MySQL

### ISSUE THREAD

**Issue by AyelGoth** [nextcloud/server#5702]
Estoy tratando de instalar el servidor en el servidor web de internet. Pero me sale un mensaje de error sobre el servidor mysql. He revisado el servidor por PHPMyAdmin y puedo elegir crear la base de datos en utf8mb4. The error message is as follows:

Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2019] Can't initialize character set utf8mb4 (path: /usr/local/mysql/share/mysql/charsets/)

How can I do to install NextCloud manually?

**Comment by creopard** [comment]
NextCloud uses collation "utf8_bin" by default. Try to use this one.

**Comment by MorrisJobke** [comment]
> Error while trying to create admin user: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2019] Can't initialize character set utf8mb4 (path: /usr/local/mysql/share/mysql/charsets/)

By default we try to setup the database with the 4 byte UTF8 to also allow to store emojis. It looks like this character set is disabled in your setup.

**Comment by AyelGoth** [comment]
No, it is not disabled, I have the database configured in UTF8mb4.

**Comment by AyelGoth** [comment]
As you can see, the server allows me to configure the database in UTF8mb4 ... in fact I have created tables with this configuration. But the installation program will not let me.

![screenshot_20170714_020409](https://user-images.githubusercontent.com/5136303/28199011-c73f6a64-6838-11e7-8ec2-f0fc4bb2027c.png)

**Comment by MorrisJobke** [comment]
cc @nickvergessen Any idea?

**Comment by nickvergessen** [comment]
No, but I guess there is a problem with the mysql configuration.
I would suggest to test whether installing with utf8_bin works.

**Comment by MorrisJobke** [comment]
No feedback since 1 month - closing.
