### ISSUE TITLE
Can't use external S3 non-AWS storage

### ISSUE THREAD

**Issue by febs** [nextcloud/server#5706]
I am trying to use an S3 external storage which is not an Amazon AWS one.

I got SSL certificate errors on the nextcloud logs until I added the certificate of the CA that signed the S3 server certificate to this file:

` ./apps/files_external/3rdparty/aws-sdk-php/Guzzle/Http/Resources/cacert.pem`

From that moment onwards, nextcloud stopped logging anything about it, but I still can't use the external storage.
The status icon remains red as pictured:
![image](https://user-images.githubusercontent.com/604435/28158829-46e32770-67bb-11e7-8e3b-def25e6e5349.png)

But I get no explicit error message, so I'm completely stuck and clueless.

Operating system: Ubuntu Xenial
Web server: Apache 2.4.18
Database: MySQL
PHP version: 7.0
Nextcloud version: 12.0.0
Fresh install from .zip file.

Thanks,

**Comment by paolopi** [comment]
Ciao,
which log, web server or nextcloud?
you should see something in nextcloud log data/nextcloud.log

**Comment by MorrisJobke** [comment]
Please also provide the S3 backend you are using. As there was no feedback since a month I will close this. We will reopen once more info is available.
