### ISSUE TITLE
Directory descriptions

### ISSUE THREAD

**Issue by 9662** [nextcloud/server#5716]
I apologise if this is the wrong place for this, but I wonder if the following feature would make a good candidate for improvement, or perhaps it is already implement by some app.

This is my proposed requirement:

> As a user who creates directory hierarchies for others to access and drop files in, in some cases I would like the client interface to show an arbitrary, user-entered description of the currently displayed directory.

For implementation examples, see [Apache's mod_autoindex](https://httpd.apache.org/docs/2.4/mod/mod_autoindex.html#readmename) or Github / GitLab's handling of `README.md` files.

**Comment by MorrisJobke** [comment]
Duplicate of #2426
