### ISSUE TITLE
Huge Preview Folder - 44GB - How to clean up?

### ISSUE THREAD

**Issue by m4ntic0r** [nextcloud/server#5717]
I used the "Preview Generator" App from https://github.com/rullzer/previewgenerator and let it run: preview:generate-all

So this command created **A LOT** of previews and different sizes i dont really need. I only need the very small preview for the "files" app.

**My appdata_.../preview folder is now 44GB big!**

How can i clean up this folder? I dont know what will happen if i just delete all the content of preview folder. I dont want to have a broken nextcloud environment.

I dont want to try to create pre-previews again, only to clean up this unnecessary previews.

My version is 11.0.3 (stable)

**Comment by MorrisJobke** [comment]
cc @rullzer

**Comment by lukasb314** [comment]
I'm also interested in this.

Also, there is this bug, that preview files are not being deleted, after deleting the actual file:
https://github.com/nextcloud/server/issues/5558
These unused previews might use also a lot of disk space as well.

**Comment by influenist** [comment]
Guys? No reply since July 17!

**Comment by rullzer** [comment]
You could try to delete the content of the preview folder and then running `./occ files:scan-app-data`. But no quarantees.

Also deleted files are properly cleaned up now.

**Comment by lukasb314** [comment]
> Also deleted files are properly cleaned up now.

Really, since when is that? I didn't realize that. Thanks!

**Comment by Bagorolin** [comment]
how about previews that are generated for files from an external share? I deleted those in the share directly but still the previews are still there. But I do not want to delete all previews and regenerate all. Rahter only the obsolete previews should be deleted...

**Comment by bakkegaard** [comment]
I could really use a `./occ gallery:delete-thumbnails --all` feature. 
Although I haven't contributed to Nextcloud server so far, I would like to give it shot, and try to implement this. But I need some guidance on where to start?

**Comment by barrydegraaff** [comment]
Yeah, I was thinking about replacing my 500GB SSD because of it getting almost full, turns out, that 50% of the disk is used by nextclouds appdata folder...

[bar@bartop ~]$ du -hs /var/www/html/nextcloud/data/user1@barrydegraaff.tk/
38G	/var/www/html/nextcloud/data/user1@barrydegraaff.tk/

[bar@bartop ~]$ du -hs /var/www/html/nextcloud/data/user2@barrydegraaff.tk/
209G	/var/www/html/nextcloud/data/user2@barrydegraaff.tk/

[bar@bartop ~]$ du -hs /var/www/html/nextcloud/data/appdata_***************/
167G	/var/www/html/nextcloud/data/appdata_****************/

[bar@bartop ~]$ df -h
/dev/mapper/vg_slowstore-docs     459G  418G   41G  92% /var/www/html/nextcloud/data

I know I can remove the appdata folder, and then it will be automatically re-generated. But that means 2 weeks of full cpu power on mariadb and a huge disk load. And slow Nextcloud page loads.

Wonder if a max preview setting on the instance will help...
https://docs.nextcloud.com/server/12/admin_manual/configuration_files/previews_configuration.html

**Comment by barrydegraaff** [comment]
I am setting 

      'preview_max_x' => 100,
      'preview_max_y' => 100,

Then ran:

      sudo -u apache php occ config:system:delete instanceid

Then removing the appdata folder, and revisited nextcloud, a new appdata folder appears, running rm -Rf on the old one. 

/dev/mapper/vg_slowstore-docs     459G  252G  208G  55% /var/www/html/nextcloud/data

Boom empty disk, off course the loading of image galeries in the UI is dog slow now, but it is what it is I guess.

**Comment by danielkesselberg** [comment]
Please don't recommend other users to unset the instanceid and delete their appdata folder. Like @rullzer suggested above:  

> You could try to delete the content of the preview folder and then running `./occ files:scan-app-data`. But no quarantees.
> 
> Also deleted files are properly cleaned up now.

**Comment by bakkegaard** [comment]
> Please don't recommend other users to unset the instanceid and delete their appdata folder. Like @rullzer suggested above:
> 
> > You could try to delete the content of the preview folder and then running `./occ files:scan-app-data`. But no quarantees.
> > Also deleted files are properly cleaned up now.

Is this actually a valid solution? 
Would it be okay to create a `./occ files:delete-all-previews` command that just deleted the preview folder and then runs `./occ files:scan-app-data`?

**Comment by skewty** [comment]
I too would like an `/snap/bin/nextcloud.occ preview:delete-all-previews`
There doesn't seem to be any "official" way to do this AFAIK.

I changed the preview_max_x/y settings and want to re-create my previews..  How would I do this?

**Comment by GuyPaddock** [comment]
This worked for me:

> You could try to delete the content of the preview folder and then running `./occ files:scan-app-data`. But no quarantees.
> 
> Also deleted files are properly cleaned up now.

**Comment by skjnldsv** [comment]
Yes, closing.
Better is to remove the folder and if you want you can pre-generate the preview with the occ command and the https://github.com/rullzer/previewgenerator app

**Comment by spantaleev** [comment]
Is it safe to delete the preview directory now?

Do we need to run `occ files:scan-app-data` after that as [per this comment](https://github.com/nextcloud/server/issues/5717#issuecomment-357605516) or will it be okay without it?

**Comment by skjnldsv** [comment]
You still need to update the app data.
Warning, depending on the size of your instance, it can be very expensive.
Nonetheless, a deleted file also gets its preview deleted now. SO if you really need to cleanup the preview folder, you should never have to clean it again

**Comment by J0WI** [comment]
> you can pre-generate the preview with the occ command and the https://github.com/rullzer/previewgenerator app

Beware of https://github.com/rullzer/previewgenerator/issues/156

@skjnldsv would be great to have this in https://github.com/nextcloud/documentation

**Comment by barrydegraaff** [comment]
Preview generator is very slow, eats a shit load of resources. Without pre-generation, if there is a lot of media in your instance, you will experience freezes in the NC App on mobile devices, and if the max settings are not set, even the web-ui is barely usable.

   'preview_max_x' => 400,
   'preview_max_y' => 400,
   'preview_max_scale_factor' => 1.5,

Also in older releases previews needed to be generated for ALL users, even if they have a share that contains all the data to be pre-generated. Aka same thumbnail is generated for each user. Not sure if that is fixed now.

**Comment by kesselb** [comment]
@barrydegraaff is your comment related to the actual issue here? You can report an issue https://github.com/nextcloud/server/issues/new/choose any time.
