### ISSUE TITLE
Shared via link: + button is too near to cloud name

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#5720]
When opening a link to a shared folder the "+" button is too near to the logo link and this leads to acciddently open the startsite instead of the "upload" popup.
As the startsite of the cloud is not that relevant, I suggest to remove this link.

As discussed, @MorrisJobke.

![screenshot_20170713-231357](https://user-images.githubusercontent.com/5836855/28188321-073b71ec-6822-11e7-9541-722b0a755f19.png)

**Comment by MorrisJobke** [comment]
Fix for this is in #5827
