### ISSUE TITLE
Problem Upgrade Owncloud 10.0.2.1 to Nexcloud 11.0.0

### ISSUE THREAD

**Issue by cbacigalupo** [nextcloud/server#5722]
Upgrade problem 

> Actualice a 11.0.0

Doctrine\DBAL\Schema\SchemaException: There is no column with name 'uid' on table 'oc_accounts'.

Registros detallados 
Preparando la actualización
Establecer el nivel de registro a depuración
Modo mantenimiento activado
Actualizando el esquema del base de datos
Doctrine\DBAL\Schema\SchemaException: There is no column with name 'uid' on table 'oc_accounts'.

Server config:
Debian 9 Testing
4.9.0-3-amd64

Apache
Server version: Apache/2.4.25 (Debian)
Server built:   2017-06-20T19:29:11

Mariadb
mariadb  Ver 15.1 Distrib 10.1.23-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

PHP 
PHP 7.0.19-1 (cli) (built: May 11 2017 14:04:47) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.19-1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by tflidd** [comment]
From OC 10 you should only migrate to NC 12. When NC 11 was released, there was no corresponding version on ownCloud (they skipped the OC 9.2 release), and with OC 10, there are probably some changes in the database compared to NC 11.

Check when the ownCloud major version was release (e.g. OC 10), then choose the major NC version that was released after that (e.g. NC 12).
