### ISSUE TITLE
Admin group show with ldap instead of 'no group'

### ISSUE THREAD

**Issue by sirio81** [nextcloud/server#5726]
### Steps to reproduce
1. Configure LDAP with a domain controller
2. Configure one or more domain user to be used by nextcloud
3. In nextcloud user page, click on the Groups list box
4. The box will change from 'no group'  to 'admin'.
5. Switch to another page and back to 'Users' page.
6. The box now is showing 'no group'

### Expected behaviour
Tell us what should happen

### Actual behaviour
Always show 'no-group'.

### Server configuration

**Operating system**: ubuntu 16.04

**Web server:** apache 2.4

**Database:** mariadb 10.0

**PHP version:** 7.0.18

**Nextcloud version:** 11.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** tar.gz

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:** LDAP
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.2
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_saml

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "ocqq0yiey7i8",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxxxxxxxxxx.com"
        ],
        "datadirectory": "\/var\/www\/xxxxxxx\/data",
        "overwrite.cli.url": "http:\/\/xxxxxxxxxx.com",
        "dbtype": "mysql",
        "version": "11.0.3.2",
        "dbname": "xxxxxxx",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\APCu"
    }
}

</details>

**Are you using external storage, if yes which one:** no
**Are you using encryption:** yes/no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

+-------------------------------+-----------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                                   |
+-------------------------------+-----------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                 |
| hasPagedResultSupport         |                                                                                                                                   |
| homeFolderNamingRule          |                                                                                                                                   |
| lastJpegPhotoLookup           | 0                                                                                                                                 |
| ldapAgentName                 | CN=acacloud,OU=Service,OU=ACA,DC=mydomain,DC=com                                                                                   |
| ldapAgentPassword             | ***                                                                                                                               |
| ldapAttributesForGroupSearch  |                                                                                                                                   |
| ldapAttributesForUserSearch   |                                                                                                                                   |
| ldapBackupHost                |                                                                                                                                   |
| ldapBackupPort                |                                                                                                                                   |
| ldapBase                      | DC=mydomain,DC=com                                                                                                                 |
| ldapBaseGroups                | DC=mydomain,DC=com                                                                                                                 |
| ldapBaseUsers                 | DC=mydomain,DC=com                                                                                                                 |
| ldapCacheTTL                  | 60                                                                                                                                |
| ldapConfigurationActive       | 1                                                                                                                                 |
| ldapDynamicGroupMemberURL     |                                                                                                                                   |
| ldapEmailAttribute            | mail                                                                                                                              |
| ldapExperiencedAdmin          | 0                                                                                                                                 |
| ldapExpertUUIDGroupAttr       |                                                                                                                                   |
| ldapExpertUUIDUserAttr        |                                                                                                                                   |
| ldapExpertUsernameAttr        | sAMAccountName                                                                                                                    |
| ldapGroupDisplayName          | cn                                                                                                                                |
| ldapGroupFilter               |                                                                                                                                   |
| ldapGroupFilterGroups         |                                                                                                                                   |
| ldapGroupFilterMode           | 0                                                                                                                                 |
| ldapGroupFilterObjectclass    |                                                                                                                                   |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                                                      |
| ldapHost                      | 192.168.253.8                                                                                                                     |
| ldapIgnoreNamingRules         |                                                                                                                                   |
| ldapLoginFilter               | (&(&(|(objectclass=person))(|(|(memberof=CN=cloudusers,OU=Gruppi,DC=mydomain,DC=com)(primaryGroupID=8888))))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                                                   |
| ldapLoginFilterEmail          | 0                                                                                                                                 |
| ldapLoginFilterMode           | 0                                                                                                                                 |
| ldapLoginFilterUsername       | 1                                                                                                                                 |
| ldapNestedGroups              | 0                                                                                                                                 |
| ldapOverrideMainServer        |                                                                                                                                   |
| ldapPagingSize                | 500                                                                                                                               |
| ldapPort                      | 389                                                                                                                               |
| ldapQuotaAttribute            |                                                                                                                                   |
| ldapQuotaDefault              |                                                                                                                                   |
| ldapTLS                       | 0                                                                                                                                 |
| ldapUserDisplayName           | displayName                                                                                                                       |
| ldapUserDisplayName2          |                                                                                                                                   |
| ldapUserFilter                | (&(|(objectclass=person))(|(|(memberof=CN=cloudusers,OU=Gruppi,DC=mydomain,DC=com)(primaryGroupID=8888))))                         |
| ldapUserFilterGroups          | cloudusers                                                                                                                        |
| ldapUserFilterMode            | 0                                                                                                                                 |
| ldapUserFilterObjectclass     | person                                                                                                                            |
| ldapUuidGroupAttribute        | auto                                                                                                                              |
| ldapUuidUserAttribute         | auto                                                                                                                              |
| turnOffCertCheck              | 0                                                                                                                                 |
| turnOnPasswordChange          | 0                                                                                                                                 |
| useMemberOfToDetectMembership | 1                                                                                                                                 |
+-------------------------------+-----------------------------------------------------------------------------------------------------------------------------------+

</details>

### Client configuration
**Browser:** 54.0.1 (32 bit)

**Operating system:** windows 10

![immagine](https://user-images.githubusercontent.com/2992550/28208876-3b1cefea-6890-11e7-8efe-a900bc63cb50.png)

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by blizzz** [comment]
Do I understand correctly, that the problem is that the user was not added to the admin group? Or is it a plain visual issue? And can you reproduce it on Nc 14?
