### ISSUE TITLE
File listing crashes when a folder name contains quotes

### ISSUE THREAD

**Issue by daniellienert** [nextcloud/server#5747]
### Steps to reproduce
1. Create a folder containing quotes like `"test"` locally and get it synced
2. Go to the folder containing the `"test"` folder
3. The file list is empty, javascript throws the error:

![image](https://user-images.githubusercontent.com/642226/28250984-55933e7a-6a74-11e7-9226-6488fbdd22e0.png)

### Expected behaviour
Folder gets listed along with the other content of the parent folder.

### Actual behaviour
Nothing gets listed

### Server configuration

**Operating system**:
FreeBSD

**Web server:**
nginx

**Database:**
MySQL

**PHP version:**
7.0.17

**Nextcloud version:** (see Nextcloud admin page)
11.01 stable

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**
Chrome (latest)

**Operating system:**
MacOSX Sierra

#### Browser log
<details>
<summary>Browser log</summary>

jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.0
js.js:2139 Deprecation warning: tipsy is deprecated. Use tooltip instead.
jQuery.fn.tipsy @ js.js:2139
js.js:2139 Deprecation warning: tipsy is deprecated. Use tooltip instead.
jQuery.fn.tipsy @ js.js:2139
jquery.min.js:2 Uncaught (in promise) Error: Syntax error, unrecognized expression: tr[data-file=""TEST Folder""]
    at Function.ga.error (jquery.min.js:2)
    at ga.tokenize (jquery.min.js:2)
    at Function.ga [as find] (jquery.min.js:2)
    at a.fn.init.find (jquery.min.js:2)
    at a.fn.init.a.fn.find (jquery-migrate.min.js:2)
    at FileList._createRow (filelist.js?v=6f142f6c57eef6a0109913ea761a1352:1178)
    at FileList.fileList._createRow (tagsplugin.js?v=6f142f6c57eef6a0109913ea761a1352:142)
    at FileList.fileList._createRow (filesplugin.js?v=6f142f6c57eef6a0109913ea761a1352:77)
    at FileList.fileList._createRow (share.js?v=6f142f6c57eef6a0109913ea761a1352:38)
    at FileList._renderRow (filelist.js?v=6f142f6c57eef6a0109913ea761a1352:1364)

</details>

**Comment by MorrisJobke** [comment]
I could not reproduce anymore with 12.0.2. We did some fixes there in the escaping. Could you please check if it is still broken for your case? Thanks
