### ISSUE TITLE
Avatar API: generate image if no user defined image is available & versioning

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#5750]
If you open https://cloud.cloud.com/avatar/$username/$pixel for avatar there is either the resized user image or {"data":{"displayname":"tobi"}}. 
Instead of the displayname there should be an image with the auto generated color and the first letter.

For easier versioning control it would be great if the resulting url also has the version number, so that we can easier control the versioning, e.g. query for "tobi" returns /tobi/1 or /tobi/2.

@LukasReschke

**Comment by MorrisJobke** [comment]
> For easier versioning control it would be great if the resulting url also has the version number, so that we can easier control the versioning, e.g. query for "tobi" returns /tobi/1 or /tobi/2.

What do you mean by that? How should you know what the current version number is?

cc @rullzer for the preview - currently we generate the letter and color completely in CSS - should we maybe discontinue this one as well? It makes just little sense to duplicate the logic in JS and PHP.

**Comment by tobiasKaminsky** [comment]
We use glide lib to download and cache images and here is mentioned that they use the url to invalidate/cache the images:
https://github.com/bumptech/glide/wiki/Caching-and-Cache-Invalidation

> The String returned from the [`getId()`](http://bumptech.github.io/glide/javadocs/latest/com/bumptech/glide/load/data/DataFetcher.html#getId()) method in DataFetcher. Typically DataFetchers simply return the result of calling `toString()` on your data model, so the string version of your `URL` if you provide a `URL`, or the file path if you provide a `File` etc.

So if we ask for /avatar/tobi and get back /avata/tobi/1 .... Right now I see your point...
This cannot work :-/

Do you have any other idea how to detect if the avatar image is outdated?

**Comment by MorrisJobke** [comment]
> So if we ask for /avatar/tobi and get back /avata/tobi/1 .... Right now I see your point...
> This cannot work :-/

usually we have a cache buster for this as well on the web (the hash of the version number of the app this resource is in). Which will update on an app update ;)

**Comment by rullzer** [comment]
I think this would make sense. Would also make @LukasReschke happy since then we'd not leak the full name (Which is the case now if you don't have an avatar).

@tobiasKaminsky the avatar already has caching and an etag. So already enough to check. Personally I'm not a big fan to extend the logic beyond that. If you have to wait 15 minutes to see your avatar updated so be it ;)

**Comment by rullzer** [comment]
Ok so I've been thinking a bit more about this. And just returning the image is a bit silly. As we really only need the color and the first letter. Which is tiny. If we send the image it gets (relatively) big and bloated again.

**Comment by tobiasKaminsky** [comment]
For client side it still would be great to have an image as otherwise every client has to re-implement the same logic for generating "round avatar with correctly computed color and first letter".

**Comment by MorrisJobke** [comment]
> For client side it still would be great to have an image as otherwise every client has to re-implement the same logic for generating "round avatar with correctly computed color and first letter".

I can fully understand this, and the current API also feels quite cumbersome, that we return over a single API one time a photo and in the other cases JSON text. :/ Maybe we can return the color code and letter in this case as a possible compromise?

**Comment by tobiasKaminsky** [comment]
Still weird to have two different response types ;-)

**Comment by juliushaertl** [comment]
Maybe we can just return a svg with the colored circle and the first letter? That way it won't be that bloated and it should be fairly easy to generate.

**Comment by MorrisJobke** [comment]
> Maybe we can just return a svg with the colored circle and the first letter? That way it won't be that bloated and it should be fairly easy to generate.

But on Android SVGs are already hard and iOS doesn't support it natively and needs to re-render it locally. :/

**Comment by juliushaertl** [comment]
> But on Android SVGs are already hard and iOS doesn't support it natively and needs to re-render it locally. :/

Ok, wasn't aware of that. I would have expected it to work there fine. :see_no_evil:

**Comment by tobiasKaminsky** [comment]
I do not fully understand why we are talking about "bloated" avatars for the "circle with letter" as every other real avatar will be way bigger. And I guess we can cache those placeholder avatars in the same way?

--> show always an icon as this is what is expected (at least for me) for the api

**Comment by tobiasKaminsky** [comment]
We are currently improving avatar handling on android side, so can we please get a decision and the a PR for this? Would be awesome!

And to cite myself: --> show always an icon as this is what is expected (at least for me) for the api

**Comment by LukasReschke** [comment]
Okay. We'll always have to show an icon, also for https://github.com/nextcloud/richdocuments/pull/130. I'll work on that.

**Comment by rullzer** [comment]
Ok lets do it. We can always later improve for the web by serving svg's if the correct accept header is set so we can do autoscaling etc.

**Comment by MorrisJobke** [comment]
Fixed by #6876
