### ISSUE TITLE
Errors when creating groups from the user list.

### ISSUE THREAD

**Issue by jzawer** [nextcloud/server#5751]
### Steps to reproduce
1. Login as Administrator.
2. Go to Users.
3. On one user add a new group.
4. In left panel, the new group appear twice.

### Expected behaviour
When you create group from user you should see only once in left panel.

### Actual behaviour
When you create group from user you see the new group twice.

![grupoduplicado](https://user-images.githubusercontent.com/15221566/28266427-1324a3f4-6af5-11e7-99ec-96689c630d59.png)

### Server configuration.
**Nextcloud version:** 12

**Comment by rpirritano** [comment]
@MorrisJobke,
I am a new contributor, if this is still available, I can take it?

**Comment by MorrisJobke** [comment]
> @MorrisJobke,
> I am a new contributor, if this is still available, I can take it?

Hi @rpirritano sure :) If you have questions, feel free to ask here or go to our IRC channel #nextcloud-dev on freenode.

**Comment by rpirritano** [comment]
@MorrisJobke , I have been going through the documentation to install the dev environment, any links to resources that you can provide would be great, in case I am missing one of them.

**Comment by rpirritano** [comment]
@MorrisJobke ,

  Quick question from investigating the issue.  It seems that addGroup is being called twice in the multiSelect (users.js line 500).  After the createCallback: addGroup is called, addGroup is then called again from the oncheck: addUserToGroup.  Any information to why addUserToGroup is running addGroup again?

**Comment by MorrisJobke** [comment]
> Any information to why addUserToGroup is running addGroup again?

@blizzz Do you know more on this one?

**Comment by blizzz** [comment]
> @blizzz Do you know more on this one?

Not by heart, but it does not sound right. Perhaps it is a side effect cause by some other changes on the road.
