### ISSUE TITLE
Error: Default encryption module not loaded

### ISSUE THREAD

**Issue by sushidave** [nextcloud/server#5755]
The log file is full of the same error messages.
- Default encryption app is activated.
- Server-side encryption is activated in the settings.
- Default encryption module is selected in the settings.
- Storage encryption is activated in the settings.

Nextcloud version: 11.0.3
Operating system and version: Linux 3.10.0-514.16.1.el7.x86_64
Apache or nginx version: Apache
PHP version: 5.6.26

Is this the first time you've seen this error?:
Yes

Steps to replicate:
1. Login as admin.
2. Open the log file.

The issue you are facing:
Errors in the error log, see below.

The output of your Nextcloud log:
Error Default encryption module not loaded 2017-06-11T23:44:34+0200
Error Default encryption module not loaded 2017-06-11T23:44:34+0200
Error Default encryption module not loaded 2017-06-11T23:44:34+0200
Error Default encryption module not loaded 2017-06-11T23:44:34+0200
Error Default encryption module not loaded 2017-06-11T23:44:34+0200
Error Default encryption module not loaded 2017-06-11T23:44:34+0200
Error Default encryption module not loaded 2017-06-11T23:44:34+0200
Error Default encryption module not loaded 2017-06-11T23:44:34+0200
Error Default encryption module not loaded 2017-06-11T23:44:34+0200
Error Default encryption module not loaded 2017-06-11T23:44:34+0200
Error Default encryption module not loaded 2017-06-11T23:44:33+0200
(etc.)

The output of your config.php file in /path/to/nextcloud:
<?php
$CONFIG = array (
'instanceid' => 'oc**********',
'passwordsalt' => '********************************************',
'secret' => '****************************************************************',
'trusted_domains' =>
array (
0 => 'cloud.********.',
),
'datadirectory' => '/home/httpd/vhosts/*********./cloud_data',
'dbtype' => 'mysql',
'version' => '11.0.3.2',
'dbname' => '**********_cloud',
'dbhost' => 'localhost',
'dbtableprefix' => 'oc_',
'dbuser' => '********',
'dbpassword' => '*******************************',
'logtimezone' => 'UTC',
'installed' => true,
'forcessl' => true,
'memcache.local' => '\OC\Memcache\ArrayCache',
'mail_smtpmode' => 'smtp',
'mail_from_address' => '********',
'mail_domain' => '*******.',
'mail_smtpauthtype' => 'LOGIN',
'mail_smtphost' => '*****************',
'mail_smtpport' => '25',
'overwrite.cli.url' => 'https://cloud.*******.:443',
'overwriteprotocol' => 'https',
'theme' => '',
'loglevel' => 2,
'maintenance' => false,
);

(Copied from https://help.nextcloud.com/t/error-default-encryption-module-not-loaded/13948)

**Comment by schiessle** [comment]
But beside the error message it works? Can you upload and download files? Are the files stored encrypted?

**Comment by sushidave** [comment]
@schiessle Thank you for your prompt answer. Yes, up- and downloading works and the files are stored encrypted.

(What doesn't work is sharing files from another NC instance with users of this NC instance. They get the invitations but after accepting they are not displayed. Not sure if this is related to this error message.)

**Comment by Nebucatnetzer** [comment]
Happens here as well.
What I'm experiencing is that I can't open a shared link when I'm logged in however that might be an additional problem.

**Comment by schiessle** [comment]
> Thank you for your prompt answer. Yes, up- and downloading works and the files are stored encrypted.

Strange, can you find out which operation triggers this error message? I just tried to upload/download, edit and share a encrypted file but couldn't trigger the error message.

> What doesn't work is sharing files from another NC instance with users of this NC instance. They get the invitations but after accepting these files are not displayed. Not sure if this is related to this error message.

I think that's something different. I would recommend to add a separate issue and mention me, then we can investigate.

**Comment by schiessle** [comment]
> What I'm experiencing is that I can't open a shared link when I'm logged in however that might be an additional problem.

Works here as well. The only thing I could see is that the previews for public links are broken if you are logged in with a different user while opening the link. Fix is already here: https://github.com/nextcloud/server/pull/5803

**Comment by sushidave** [comment]
> Strange, can you find out which operation triggers this error message? I just tried to upload/download, edit and share a encrypted file but couldn't trigger the error message.

@schiessle It appears that the logged in (admin) user with whom I'm checking the log triggers the error message because when the user is logged out no error messages are produced. If it's of any help here is a record from the downloaded log file:

`{"reqId":"WXC4bWgHGUJqFs7W2nRt3AAAABc","remoteAddr":"___.___.__.___","app":"core","message":"Default encryption module not loaded","level":3,"time":"2017-07-20T14:04:29+00:00","method":"GET","url":"\/index.php\/settings\/admin\/log\/download","user":"adminsushi","version":"11.0.3.2"}`

There are multiple of those for every second and the log file's size is 190 MB large now.

**Comment by MorrisJobke** [comment]
> Fix is already here: #5803

Closing

**Comment by sushidave** [comment]
> What doesn't work is sharing files from another NC instance with users of this NC instance. They get the invitations but after accepting these files are not displayed. Not sure if this is related to this error message.
> 
> I think that's something different. I would recommend to add a separate issue and mention me, then we can investigate.

@schiessle see issue #2919
