### ISSUE TITLE
LDAPS Password forgotten when verify loginname text box changed

### ISSUE THREAD

**Issue by rogersia** [nextcloud/server#5756]
I have set up the Nextcloud server using the LDAP/AD Integration plugin and it has all been working as expected using LDAP.

I have just installed certificates into both LDAP servers, to be able to run LDAPS and have configured the LDAPS connection to the main server using the same username / password that was on the LDAP server and port 636.

The green dot at the bottom of the page shows that it has connected to the LDAPS server correctly and I click continue.

I then select the AD group from the list of groups and click verify settings and count users.  It then thinks about it and says 10 users found, and the green configuration ok dot is still showing.

I then click continue which goes to the login attributes tab and leave all settings as default.  

When I click on the test loginname box to type a username, and type the username, the message box shows a popup message covering the "verify settings" button

If I click on the empty area below the LDAP/AD integration plugin box, all of the tabs at the top of the screen grey out apart from the server tab and the green configuration OK dot changes to the red incorrect configuration dot.

If I then click on the server tab again, the LDAP password is no longer in the password box.

If I do not click on any empty area, and wait for the second for the popup box to disappear, I can then click verify settings and the message appears confirming if it is a valid user or not, and the password does not disappear (and the configuration ok stays with the green dot).

### Expected behaviour
If you click the white area away from the "Test loginname" box after entering text, instead of clicking the "verify settings" button the LDAP password should not be lost

### Actual behaviour
If you click the white area away from the "Test loginname" box after entering text, instead of clicking the "verify settings" button the LDAP server password is lost

If you click the verify settings button after typing into the test loginname box, it all works correctly

Edit: 
I have just managed to also replicate it by typing into the test loginname and clicking the verify settings box without clicking off away from the text box first.

### Server configuration

**Operating system**:
Centos 7

**Web server:**
Apache 

**Database:**
MySQL Server

**PHP version:**
7.1

**Nextcloud version:** (see Nextcloud admin page)
12.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated when Nextcloud 12 was released.

**Where did you install Nextcloud from:**
Downloaded from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

deleted files
gallery
ldap user and group back end
log reader
monitoring
password policy
pdf viewer
text editor
theming
update notification
versions
video player
two factor TOTP provider
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>


    "system": {
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbtableprefix": "oc_",
        "default_language": "en",
        "defaultapp": "files",
        "logtimezone": "UTC",
        "loglevel": "0",
        "ldapIgnoreNamingRules": false,
        "ldapUserCleanupInterval": 90,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "maintenance": false,
        "trusted_proxies": [
            xxx.xxx.xxx.xxx
        ],
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "installed": true,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "stable"

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Yes: Active Directory
LDAP > Advanced Tab > Group-Member Association  : member (AD)

### Client configuration
**Browser:**
Microsoft Edge

**Operating system:**
Windows 10
</details>

**Comment by LukasReschke** [comment]
cc @blizzz

**Comment by blizzz** [comment]
If it is still an issue,

> When I click on the test loginname box to type a username, and type the username, the message box shows a popup message covering the "verify settings" button

could your provide a screenshot? Which browser do you use?

I could not reproduce this behaviour.

**Comment by MorrisJobke** [comment]
Hey, this issue has been closed because the label `needs info` is set and there were no updates for 24 days. Feel free to reopen this issue if you deem it appropriate.
