### ISSUE TITLE
Hardcode certificate bundle for update notifications 

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#5766]
To avoid issues such as resulting in missing update notifications https://github.com/nextcloud/server/issues/4978

**Comment by skjnldsv** [comment]
@MorrisJobke @blizzz @nickvergessen @rullzer still relevant?

**Comment by MorrisJobke** [comment]
> @MorrisJobke @blizzz @nickvergessen @rullzer still relevant?

I don't think so.
