### ISSUE TITLE
Dedicated theming app logo for the login page

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#5779]
We now got multiple times the request to have a dedicated logo for the login page and not share the one in the top left.

Does this make sense or would it clutter the theming app too much? Would it make sense to have it hidden in an advanced section? I'm not 100% sure, but I usually want to try to avoid recommending the old themes, because they tend to break more often.

@nextcloud/theming @karlitschek @juliushaertl @jancborchardt

**Comment by MariusBluem** [comment]
I think this makes sense, and I would really love to see this personally 👍

Problem is, that if we are starting creating more and more custom options for logos (login page vs. header) there is also more stuff which needs to be maintained with every single update 😏 The nice thing about the theming-app is, that favicons, Logos in various sizes etc. are rendered nearly automatically ;) ... without the need to upload the logo in multiple sizes.

Theming-app should *not* be a frontend for the old themes with all these custom options.

**Comment by MorrisJobke** [comment]
> The nice thing about the theming-app is, that favicons, logos in various sizes etc. are rendered nearly automatically ;) ... without the need to upload the logo in multiple sizes.

We need to add maybe a check that just says: " ✔️ Imagick detected - favicon will be generated automatically" or ":x: Imagick not loaded - install ABC to have the favicon generated automatically", because currently this is a bit erratic 😉

**Comment by MorrisJobke** [comment]
> Theming-app should not be a frontend for the old themes with all these custom options.

Correct, but it should provide the useful stuff. And the old themes are basically bad because of the way it allows to overwrite templates and stuff like that and not because of the theme class in my opinion.

**Comment by karlitschek** [comment]
No strong opinions here. :-) Would be cool to have I guess :-)

**Comment by schiessle** [comment]
Initially it sounds like a good idea, but I also share @MariusBluem concerns. Once you can upload a separate image for the login page and the header bar people will ask for a separate logo for the email header, the favicon, etc.

Even if people don't ask for it, also if we have only two images (header and login screen) which one should we use to generate the favicon, email header,...

I fear that once we add it we will end up with many more feature request to tweak all the stuff I just mentioned and probably more.

**Comment by LukasReschke** [comment]
> I fear that once we add it we will end up with many more feature request to tweak all the stuff I just mentioned and probably more.

👍

**Comment by MorrisJobke** [comment]
Just another comment:

> But separated favicon|top left logo|login logo is still appreciated. Maybe generation of favicon based on the icon style "top left logo" is ok. It is preferred to use 500px+ login logos with text etc. This is suboptimal for favicon generation.

Sadly I also have no better idea to make it simple but powerful. Maybe we need to allow that themes can only contain files that should be overwritten and can be loaded in addition to the theming app. I just want to give people the power and maintainability of the theming app + some under the hood modifications for static assets like images (no CSS or HTML juggling, because this caused too much trouble in the past).

**Comment by MorrisJobke** [comment]
Or does the current theme allow to simply specify the colours and they are then used in our SCSS compiler?

**Comment by pixelipo** [comment]
If in core we use logo for both places, than theming should also use logo. Theming should not affect basic structure of the app.

(I think) I understand the use case here - e.g. "iconified-logo" vs "logo-with-a-title" - but if we want to support that, we should either use that concept in core as well, or add a possibility in theming to toggle title (it would be hidden by default) on the login page.

**Comment by jancborchardt** [comment]
I wouldn’t put it in theming since then we need to maintain a whole bunch of special cases yet again. We might get small requests here and there but for the majority using the same logo works well and is simple and nice.

What I’d say is enough that if you add a separate file called logo-login.svg/png into the img folder, that should get picked up by theming. If there is none, just use the normal logo. (We had that in the past where we still separated logo and logo-wide, but I think that was removed.)

**Comment by MorrisJobke** [comment]
We don't support to place random files in random folders. That would just not work. We should have a defined way. And even then we need to support it properly. 😉

**Comment by jancborchardt** [comment]
Well that’s what I’m saying: Back in the day we had both logo.svg (used on log in) and logo-wide.svg (used in header). They happened to be the same logo by default. If someone wanted to use different logos, they could.

But it seems like too much of an edgecase that we should introduce and maintain an additional setting in our nice and simple theming settings.

**Comment by juliushaertl** [comment]
> But it seems like too much of an edgecase that we should introduce and maintain an additional setting in our nice and simple theming settings.

With that being said. Let's close this. It is still always possible to build a custom theme to achieve separate logos there.
