### ISSUE TITLE
Fold the workflow rules by default

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#578]
In case you have more then one simple rule, the table of option might become rather huge.
So my suggestion would be, to fold the actual checks in div and hide it.
Only the title should be visible, when you click on it, the div enrolls and on successful save we can close it again?

**Comment by leniquenoralez** [comment]
I can work on this

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
