### ISSUE TITLE
Allow to theme the iOS/Android app store links

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#5780]
It would be nice to allow to theme the links to the Android and iOS app via the theming app. I guess it is fine to not have a UI for this and only set two values in the DB and if those are present the theming app uses them instead of the default ones.

@nextcloud/theming @juliushaertl @LukasReschke Is this okay? This would avoid that customers with branded apps need to use themes and can use the advantages of the theming app + use the customised links.

**Comment by MorrisJobke** [comment]
Maybe reveal the entries if the DB entries are set, but don't show them if they are not set before via an SQL statement.

**Comment by MariusBluem** [comment]
Why don’t we create an addon-app *with* frontend like https://github.com/juliushaertl/theming_customcss 🤔 Even if the use-case is small, I am not a friend of hiding such options too much ... if no frontend, ping me for documenting this 😅

**Comment by MorrisJobke** [comment]
> Why don’t we create an addon-app with frontend like https://github.com/juliushaertl/theming_customcss 🤔 Even if the use-case is small, I am not a friend of hiding such options too much ... if no frontend, ping me for documenting this 😅

Because the theming app provides a theme class and then you need to inject the values into that theme class from another app ... even more dirty code.

**Comment by MariusBluem** [comment]
Understand ... THX.

**Comment by rullzer** [comment]
Well we can just use the occ commands for now... let me prepare a PR.
