### ISSUE TITLE
Activity uses absolute URL for images and did fail with reverse proxy

### ISSUE THREAD

**Issue by rebruCH** [nextcloud/server#5799]
First - nextcloud is easy to use, and i moved this evening from owncloud without any big problems.

But there is a bug in the activity feed - you're using absolute url instead of relative. Similiar to the problem with squid, but only on the activity feed - so its not in general - its only a mistake (in my opinion) in building src links ( absolute instead of // or relative, so the protocol is not hardcoded in relation of the host)

The problem is, when you use nextcloud with http served over a reverse proxy (ssl offloading - and dont argue about security, because the nextcloud server is on a not connected vSwitch in ESXi and the reverse proxy is connected to this vSwitch too and connected to internet (behind a firewall))

I would say, use src="//xy.svg" as the url instead of absolute or even use relative links - because the problem exists only in the activity feed. The rest of the wonderful NC is working like expected and i didnt see this behaviour at another location in the NC.

My installation specs are:

Debian 8.8 64
Apache 2.4.10/PHP 5.6.30
NC 12
MariaDB 10.0
( DRBD active/active Cluster (pacemaker/coro) with OCFS2 and Galera )

**Comment by LukasReschke** [comment]
If you use a reverse proxy make sure to set https://github.com/nextcloud/server/blob/ac969cfbb6ec65150f296bcba1685ecffa5c73e7/config/config.sample.php#L1429-L1448 as well as set the `X-FORWARDED-PROTO` header to `https` or configure `overwriteprotocol`.

Anyways, this is more of a setup related question => https://help.nextcloud.com
