### ISSUE TITLE
ERROR: PHP imap extension is not installed

### ISSUE THREAD

**Issue by yamlfd** [nextcloud/server#5808]
### Steps to reproduce
1. Install Debian 9
2. apt-get install php7.0-imap
3. Configure user_external addon to use IMAP

### Expected behaviour
No "PHP imap extension is not installed" error, as it IS installed.

### Actual behaviour
Authentication with PHP-IMAP ist not possible.

### Server configuration

**Operating system**: Debian 9.0

**Web server:** Apache 2.4

**Database:** MariaDB

**PHP version:** 7.0.x

**Nextcloud version:** 12.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Next Cloud Website

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
user_external 
</details>

**Comment by LukasReschke** [comment]
Please reopen at https://github.com/nextcloud/apps, also note that user_external is not really maintained.
