### ISSUE TITLE
Problems with external ftp

### ISSUE THREAD

**Issue by CordlessWool** [nextcloud/server#5810]
I  have had some problems with external ftp storage. I try some path combination and solve the problem for me, maybe it will help you to fix the problem. 

When I inserted the the ftp-sever it said the connection was ok, but nothing was displayed. So I try some combinations with sub folders, but it loads only once at adding but not when I changed the folder to one I Added before. Then I set a /folder/. path, then it is loading every time I changed the folders in the settings but no updates. My last combination, which works for me is a slash (ip-addr:port/) after the server address and ./. as folder path. So now, the folder is updating when I insert files form outside nextcloud. 

Upload was never a problem. If I added some files inside Nextcloud they always appear on ftp.

My current system is nextcloud 12 official docker container.
But I had the problem already with nextcloud 11 all versions.
I use a vsftp server

**Comment by CordlessWool** [comment]
Ok the work around also works only for a while and now it is frozen. Also very interesting is, that if I change the path something outer like ./ instead of ./. the folder is updated once. If I rewrite the path as ./. it is shows all files as the were before changing the path to ./

**Comment by ekgermann** [comment]
Similar problem here.  NextCloud 12.0.2 install from zip.

Two external ftp sites linked to it.  It "works" the first time, but any change to the underlying FTP structure (new files, folders, etc) are not reflected in the NC virtual folder.  Only shows what was originally there.

What can I do to assist in debugging this?

**Comment by j-ed** [comment]
Nextcloud version: 12.0.3

I've fiddled around with my Pure-FTP server to understand what happens when a FTP share is accessed.
First I created a new share `/ftpdir` and adjusted the Nextcloud mount settings. I found out that these seem to be the normal commands which are executed to check if files on a FTP share have been changed and to kick-off a rescan:
```
[INFO] New connection from 192.168.xxx.xxx
[DEBUG] Command [user] [juergen]
[DEBUG] Command [pass] [<*>]
[INFO] juergen is now logged in
[DEBUG] Command [cwd] [/ftpdir/]
[DEBUG] Command [type] [I]         # sets the type of file to be transferred: I - image (binary data)
[DEBUG] Command [size] [/ftpdir/]  # returns the size of the remote file
[DEBUG] Command [mdtm] [/ftpdir/]  # returns the last-modified time of the given file on the remote host
[INFO] Logout.
```
Unfortunately the `ftp_size()` and `ftp_mdtm()` functions/commands seem not to work on directories on all file servers, like the Pure-FTPd, so that no values are returned. Checking the PHP manual confirms my finding (*see: http://php.net/manual/en/function.ftp-mdtm.php* -> **Note: ftp_mdtm() does not work with directories.**)
Then I tried to read the directory content using the `ftp_rawlist()` function and to my surprise valuable
information was returned, like the type (file or directory) or the last modification date/time. I double-checked this by uploading a new file to the "ftpdir" directory and then re-requested the information, which showed an updated time stamp.
```
array(3) {
  [0]=> string(68) "drwxr-xr-x 2 29 users 4096 Sep 25 17:13 ftpdir"
  [1]=> string(93) "-rw-r--r-- 1 29 users 44775 Oct 28 2015 picture-1.jpg"
  [2]=> string(79) "-rw-r--r-- 1 29 users 643111 Oct 28 2015 picture-2.jpg"
} 
```
Based on that I would assume that changing the FTP check routine a little bit could solve the described problem.

**Comment by ekgermann** [comment]
Wanted to add this is still an issue with 13.0.0 

However, if you do an "occ files:scan --all" it does pick up the changes.  Running that as a cron job seems to get around the issue, but wondering if there is a better way that will pick up the files more directly without doing a periodic file scan?

**Comment by j-ed** [comment]
It might be possible that the problem is related to https://github.com/nextcloud/server/issues/3660 which describes another Pure-FTP access problem.

**Comment by Katkoac** [comment]
still an issue with 13.0.6.1.
I see SIZE and MDTM being tried on a directory and failing on a vsftpd server:

```
Wed Oct 10 23:26:54 2018 [pid 1770] [nextcloud] FTP command: Client "192.168.160.100", "SIZE /"
Wed Oct 10 23:26:54 2018 [pid 1770] [nextcloud] FTP response: Client "192.168.160.100", "550 Could not get file size."
Wed Oct 10 23:26:54 2018 [pid 1770] [nextcloud] FTP command: Client "192.168.160.100", "MDTM /"
Wed Oct 10 23:26:54 2018 [pid 1770] [nextcloud] FTP response: Client "192.168.160.100", "550 Could not get file modification time."
```

I think the underlying problem is already properly described by j-ed **_ftp_mdtm() does not work with directories_**

**Comment by martoneACN** [comment]
Any luck with this issue? I am on ver 14. Still a problem.

**Comment by danielkesselberg** [comment]
Hmm. `ftp_mdtm()` is not called afaik. Maybe `state` is the problem here: https://github.com/nextcloud/server/blob/0215b004da6af887b3e3efa28c425d41a1c76b9b/apps/files_external/lib/Lib/Storage/StreamWrapper.php#L126-L128

```
		if ($this->is_dir($path)) {
			return false;
		}
		return stat($this->constructUrl($path));
```

Could you change it like above and try again?

**Comment by j-ed** [comment]
I've just checked the patch but it causes the following message when I try to access a ftp share:
```
Es ist ein Fehler mit folgender Meldung aufgetreten:Leere Antwort vom Server erhalten.
Do you want to review mount point config in personal settings page?
```

**Comment by johnbraker** [comment]
Same problem here - is there a solution yet i havn't found?

**Comment by szaimen** [comment]
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!
