### ISSUE TITLE
Send the username to Apache via the apache_note method

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#5814]
[`apache_note`](https://secure.php.net/manual/en/function.apache-note.php) is used by PHP to communicate with Apache. I'm not sure if there is a NGINX equivalent.

Would it be possible to modify base with something like this to send the username to Apache?

```
if(\OC_User::isLoggedIn()){ apache_note( 'username', \OC_User::getUser() ); }
elseif(!empty($_SERVER['PHP_AUTH_USER'])){ apache_note( 'username', $_SERVER['PHP_AUTH_USER'] ); }
```

This is then retrieved on the Apache side like this

```
LogFormat "%h %l %u %{username}n %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
```

Could an app deliver the same result or is it loaded too late to cover all calls?

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.

**Comment by arnaudpn** [comment]
Hi,

This is a useful feature imho. Apache access logs should always contain the username of the logged in user.
Currently, username appears only in the apache logs if the connection comes from a nextcloud app but not when connecting from a browser.
