### ISSUE TITLE
Nextcloud 12.0.0 copying an empty folder does not work

### ISSUE THREAD

**Issue by tedd77** [nextcloud/server#5828]
### Steps to reproduce
1. Create an empty folder on your computer
2. Drag it into nextcloud
3. No error produced nor the folder will show into nextcloud

### Expected behaviour
Tell us what should happen
When draging a file or folder into nextcloud you should be able to see it

### Actual behaviour
Tell us what happens instead
Process is normal however no outcome 0byte file or folder will not show

### Server configuration

VM machine downloaded from techandme.se for latest version 12.0.0

Should I access the nextcloud with ssh
I can create the file or folder with 0bytes , however I need to run the occ command in order to be able to display on nextcloud web page.

This problem has been there since the early days.
Why would someone need to create empty folders ? 
The answer is when you have a template (say accounting folder) in that template you need to populate the months and inside the months you need different folders for purchase and others.... 
So instead of doing it for every month and every year and every user it is simple to create once for one user and populate as a template for the rest of users...

**Comment by MorrisJobke** [comment]
Which browser do you use?

Because usually no browser supports dropping of empty folders. :/

**Comment by tedd77** [comment]
Ah! I am using firefox.

**Comment by MorrisJobke** [comment]
> Ah! I am using firefox.

Yep - last time I tried Firefox was not able to give any event if the folder was empty (to be more specific: it only gave event data for files and their full path to get folder names out of this).

So sadly this is technically not possible. :/
