### ISSUE TITLE
webdav showing http url, instead of https, reverse proxy freenas

### ISSUE THREAD

**Issue by BetaLeaf** [nextcloud/server#5829]
So I have run into a bit of an issue when setting up NextCloud. Here is my setup.

I have a FreeNAS server that I have set up. I am using the NextCloud plugin. The plugin by default only uses http. NextCloud is in its own separate jail. In another separate jail, I have a nginx reverse proxy set up to redirect requests from ```https://freenas.betaleaf.net/cloud``` to ```http://192.168.0.3/cloud```. This works fine and https loads fine as well. The problem is the webdav url is not correct. It is showing the webdav url as ```http://freenas.betaleaf.net/cloud/remote.php/webdav/``` instead of ```https://freenas.betaleaf.net/cloud/remote.php/webdav/```

Below I have attached the relevant files. If someone could please look at them and tell me what is wrong with it, I would be extremely grateful. I am extremely new to freenas, but have some experience with ubuntu. I always look for an opportunity to learn.

[web server configs.zip](https://github.com/nextcloud/server/files/1166968/web.server.configs.zip)

![img](https://drive.google.com/uc?id=0ByILJfRaEBfkVFFoQndDbF9PbVU)

**Comment by LukasReschke** [comment]
Please open an issue at help.nextcloud.com. That seems more setup related as you probably miss some proxy related settings.

**Comment by BetaLeaf** [comment]
Actually, I fixed it by adding the following line to my config.php:
`  'overwriteprotocol' => 'https',`
I just forgot to close this issue. Sorry.
