### ISSUE TITLE
Cant execute occ command

### ISSUE THREAD

**Issue by HerleX** [nextcloud/server#5842]
### Steps to reproduce
1. Install nextcloud on Webstation/Synology
2. Try to execute ssh command  
`sudo -u http php /volume1/web/nextcloud/occ status`

### Actual behaviour
When executing the occ status command or any other occ command, i am getting the following error message:

> An unhandled exception has been thrown:
> exception 'Exception' with message 'Environment not properly prepared.' in /volume1/web/nextcloud/lib/private/Console/Application.php:145
> Stack trace:
> #0 /volume1/web/nextcloud/console.php(91): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
> #1 /volume1/web/nextcloud/occ(11): require_once('/volume1/web/ne...')

### Server configuration

**Operating system**: Synology DSM newest version

**Web server:** Apache 2

**Database:** Sqlite3 12.0.0.29

**PHP version:** php5.6.11

**Nextcloud version:** nextcloud 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

Hope you can help me with the error message

**Comment by HerleX** [comment]
Is there somebody who can help me?

**Comment by 4oo4** [comment]
What are the directory permissions/ownership for `/volume1/web/nextcloud`? Is it just the `occ` command that's not working or are you also having issues when you try to access it via the web?

**Comment by HerleX** [comment]
i set all directory permissions to 777 for testing purposes.
As shown in the command before i am trying to execute `occ` with the http user. This user also has full ownership over the nextcloud directory.

This is my config.php

```
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => '192.168.178.20',
	1 => 'xxx.de',
  ),
  'datadirectory' => '/volume1/web/nextcloud/data',
  'overwrite.cli.url' => 'http://192.168.178.20/nextcloud',
  'dbtype' => 'sqlite3',
  'version' => '12.0.0.29',
  'installed' => true,
);
```

**Comment by tcitworld** [comment]
> i set all directory permissions to 777 for testing purposes.

You shouldn't. Nextcloud checks that the `config.php` file isn't writeable for anyone. 

Please post the output of `ls -alh` inside `/volume1/web/nextcloud`.

You may try `sudo -i -u http php ./occ` instead.

**Comment by HerleX** [comment]
`sudo -i -u http php ./occ` doesn't give any output in the console.

Output as requested:

```
drwxrwxrwx 15 http http 4.0K Jun 22 14:08 .
drwxrwxrwx  8 root root 4.0K Jul 29 12:34 ..
drwxrwxrwx 31 http http 4.0K Jun 22 14:06 3rdparty
drwxrwxrwx 37 http http 4.0K Jun 22 14:10 apps
-rwxrwxrwx  1 http http 8.7K May 22 10:25 AUTHORS
drwxrwxrwx  2 http http 4.0K Jul 29 18:30 config
-rwxrwxrwx  1 http http 3.7K May 22 10:25 console.php
drwxrwxrwx 16 http http 4.0K Jun 22 14:06 core
-rwxrwxrwx  1 http http 5.0K May 22 10:25 cron.php
drwxrwx---  5 http http 4.0K Aug  1 12:31 data
-rwxrwxrwx  1 http http  41K May 22 10:25 db_structure.xml
-rwxrwxrwx  1 http http 2.8K Jun 22 14:10 .htaccess
-rwxrwxrwx  1 http http  179 May 22 10:25 index.html
-rwxrwxrwx  1 http http 2.5K May 22 10:25 index.php
drwxrwxrwx  3 http http 4.0K Jun 22 14:06 l10n
drwxrwxrwx  6 http http 4.0K Jun 22 14:06 lib
-rwxrwxrwx  1 http http  283 May 22 10:25 occ
drwxrwxrwx  2 http http 4.0K Jun 22 14:05 ocs
drwxrwxrwx  2 http http 4.0K Jun 22 14:05 ocs-provider
-rwxrwxrwx  1 http http 3.1K May 22 10:25 public.php
-rwxrwxrwx  1 http http 5.2K May 22 10:25 remote.php
drwxrwxrwx  4 http http 4.0K Jun 22 14:07 resources
-rwxrwxrwx  1 http http   26 May 22 10:25 robots.txt
drwxrwxrwx 14 http http 4.0K Jun 22 14:06 settings
-rwxrwxrwx  1 http http 2.1K May 22 10:25 status.php
drwxrwxrwx  3 http http 4.0K Jun 22 14:06 themes
drwxrwxrwx  2 http http 4.0K Jun 22 14:06 updater
-rwxrwxrwx  1 http http  163 May 22 10:25 .user.ini
-rwxrwxrwx  1 http http  388 May 22 10:27 version.php
```

**Comment by MorrisJobke** [comment]
As this more looks like a setup issue, I would like to ask you to ask for more help in the forums. https.//help.nextcloud.com

Once you have exact steps how to reproduce the issue we can have a look at it and how to fix this problem over here.

Thanks
