### ISSUE TITLE
possibility of admin lock-out during update

### ISSUE THREAD

**Issue by leggewie** [nextcloud/server#5848]
I ran into this issue during an update from NC9 to NC10.  As far as I know, NC enters maintenance mode early on during the update request and when everything is finished the web page asks whether maintenance mode should now be turned off.  This can lead to the admin locking themselves out.

Steps:
1. run the updater via the web interface index.php/settings/admin#updater
2. pull the ethernet cable or turn off the wifi half-way through
3. wait for an error to show on the web page
4. you are now locked out of NC unless you happen to have CLI access to the server

**Comment by MorrisJobke** [comment]
There is nothing we can do here. You can update the config/config.php and remove the maintenance mode flag there. Then the web UI should be accessible again (and maybe ask for another update).

**Comment by leggewie** [comment]
Thank you for your comment.  I disagree with the "There is nothing we can do here" but I guess the hint to look at config/config.php and make the necessary edit there is enough for those who run into this problem in the future and do not have CLI access on their installation (the majority, I would assume).

**Comment by MorrisJobke** [comment]
We don't know if the user is logged in, because we cannot check the DB for the needed session info and we should not allow anonymous users to disable the maintenance mode. :/

**Comment by leggewie** [comment]
Thank you for your reply.

I guess that that particular option has its problems to make it unsuitable.  That's no proof there is nothing you can do.  There could be a timeout on the upgrade maintenance mode procedure (although that might have other problems a mere user like me would be unaware of).  Maybe there is another idea.  I'm just not buying the "nothing we can do".

Again, I guess the impact of the problem is much lower than I thought it would be, if it can be dealt with on the filesystem level without CLI to the shell.  Your explanation is good enough for me and I am sure google will index this solution in no time.

**Comment by MorrisJobke** [comment]
> I'm just not buying the "nothing we can do".

true, but there is not much we can do, except some super complex way to deal with the "you are running an update and something fails and you need to update one line" ... you should be on the server anyways to have a look at the log file.

**Comment by leggewie** [comment]
Well, I did have CLI access so it's OK.  I was thinking of the people who install on shared hosting without such access.  For them it's pray and hope.  And in this case potentially futile if connection is interrupted (which unfortunately happens often where I am).
