### ISSUE TITLE
Remove LibreOffice previews

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#5849]
Do we still need the code related to:

> /**
>  * custom path for LibreOffice/OpenOffice binary
>  *
>  * Defaults to ``''`` (empty string)
>  */
> 'preview_libreoffice_path' => '/usr/bin/libreoffice',
> /**
>  * Use this if LibreOffice/OpenOffice requires additional arguments.
>  *
>  * Defaults to ``''`` (empty string)
>  */
> 'preview_office_cl_parameters' =>
> 	' --headless --nologo --nofirststartwizard --invisible --norestore '.
> 	'--convert-to pdf --outdir ',

...is unneeded since we have Collabora, isn't it?

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by MorrisJobke** [comment]
@georgehrke

**Comment by georgehrke** [comment]
AFAIK the collabora app doesn't provide previews for open document files, so yes, we still need it

**Comment by MariusBluem** [comment]
😢
