### ISSUE TITLE
`\OC\AppFramework\Http\Request::getRawPathInfo` does not correctly parse app name from URLs with "."

### ISSUE THREAD

**Issue by ostrolucky** [nextcloud/server#5853]
\OC\AppFramework\Http\Request::getRawPathInfo apparently does not work correctly with dots in path.

In remote.php $request->getPathInfo() for this path:

`https://example.com/remote.php/dav/files/gadelat/Dropbox/src/php/AppEventDispatcher/vendor/kevinlebrun`
it will return
`/dav/files/gadelat/Dropbox/src/php/AppEventDispatcher/vendor/kevinlebrun`,

but this path
`https://example.com/remote.php/dav/files/gadelat/Dropbox/src/php/AppEventDispatcher/vendor/kevinlebrun/colors.php/`
will return
`remote.php/dav/files/gadelat/Dropbox/src/php/AppEventDispatcher/vendor/kevinlebrun/colors.php/`

which causes it to not find correct app and therefore returns 502 error

**Comment by sylvainmetayer** [comment]
I tried to reproduce the test case in `tests/lib/AppFramework/Http/RequestTest.php` however this seems to work fine. 

```php
	/**
	 * @return array
	 */
	public function genericPathInfoProvider() {
		return [
			['/remote.php/dav/files/gadelat/Dropbox/src/php/AppEventDispatcher/vendor/kevinlebrun', 'remote.php', '/dav/files/gadelat/Dropbox/src/php/AppEventDispatcher/vendor/kevinlebrun'],
			['/remote.php/dav/files/gadelat/Dropbox/src/php/AppEventDispatcher/vendor/kevinlebrun/colors.php/', 'remote.php', '/dav/files/gadelat/Dropbox/src/php/AppEventDispatcher/vendor/kevinlebrun/colors.php/'],
		];
	}

```

Does this bug still exists or has it been fixed since ?

**Comment by ostrolucky** [comment]
No idea. But since this is such an old issue, let's just close
