### ISSUE TITLE
If no file is tagged with a specific tag, that tag should be removed

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#586]
Currently there can be »empty« tags. Once you typed the tag in the tags field of a file, it will start to exist, even if you remove it from the field directly after.

This is especially annoying for the tags search then where choosing an empty tag just shows the message »No files found for the selected tags«.

As soon as there is no file associated with a tag anymore, the tag is not needed and should be deleted.

**Comment by nickvergessen** [comment]
:-1: 

When you have files_accesscontrol or files_automatedtagging rules depend on such tags they should not be deleted automatically.

Also note, that the tags can be used for other things as well (announcements, whatever).

So automatic deletion is becoming way to complex for live operation. Maybe we could try a repair-step on update, but even then accesscontrol and automatedtagging cases are hard to detect as well as other use-cases of system tags.

**Comment by nickvergessen** [comment]
One idea, ask stuff like workflowengine to create tag assignments when a tag is used, so "tag the rule with the tag itself"
Then we might be able to add something like "is the tag assigned to anything" and if not, delete the tag, that might work, but breaks the current behaviour

**Comment by mar1u5** [comment]
https://github.com/owncloud/core/issues/22942

**Comment by jancborchardt** [comment]
> Then we might be able to add something like "is the tag assigned to anything" and if not, delete the tag

Yeah, that’s what I meant. Of course if it’s in use for something, then it should be preserved. But currently you end up with a lot of dead tags.

**Comment by MorrisJobke** [comment]
This is part of #1465
