### ISSUE TITLE
ServiceUnavailable

### ISSUE THREAD

**Issue by cld0815** [nextcloud/server#5860]
Logging:

Sabre\DAV\Exception\ServiceUnavailable:Â HTTP/1.1 503 Could not open file/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 85:  OCA\DAV\Connector\Sabre\File->get()[internal function] Sabre\DAV\CorePlugin->httpGet(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:  call_user_func_array(Array, Array)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:  Sabre\Event\EventEmitter->emit('method GET', Array)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:  Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 71:  Sabre\DAV\Server->exec()/var/www/nextcloud/remote.php - line 162:  require_once('/var/www/nextcl...'){main}
--

**Comment by MorrisJobke** [comment]
Please fill out the issue template:

https://raw.githubusercontent.com/nextcloud/server/master/issue_template.md

Especially the version number, installed apps, full logs, and steps to reproduce helps us to tackle this problem.

This part of the log line sadly doesn't help us.

I will close this ticket until the requested information are available.
