### ISSUE TITLE
Test\Share\ShareTest doesnt close cursors

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#5862]
When I run this test on oracle it dies because it reaches the max. open cursors which is 300 by default in XE and cant be changed. 
The rest works fine.

This test file is the "integration-alike unit tests" file. I tried to look for issues but couldn't really find any. For now I deleted the file locally so I can run the other tests.

@rullzer @schiessle can the integration tests be deleted because we have real integration tests in the meantime?
If not we need to have a look in the case a bit more, before we can run it on our CI.

**Comment by MorrisJobke** [comment]
@rullzer @nickvergessen @schiessle Is this something that could be done in the 13 cycle or not?

**Comment by nickvergessen** [comment]
IIRC the file is going to die anyway in the future when sharing is completly done with the new manager.
So maybe it's not worth the troubles
