### ISSUE TITLE
SWIFT object storage as external storage is broken in Nextcloud11

### ISSUE THREAD

**Issue by rontrompert** [nextcloud/server#5866]
### Steps to reproduce
1.Mount SWIFT object storage as external storage
2.Upload a directory with files and subfolders with files in it using something like rclone. This produces output like:

ron@LLT0024:~$ swift list maersk2
1st_file.txt
2nd_file.txt
another_directory/3rd_file.txt

3. Look at the web interface

### Expected behaviour
The following should be shown:
1st_file.txt
2nd_file.txt
another_directory

### Actual behaviour
1st_file.txt
2nd_file.txt

### Server configuration

**Operating system**:
CentOS 7.3.1611
**Web server:**
apache 2.4.6

**Database:**
mariadb-5.5
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
11
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh
**Where did you install Nextcloud from:**
tarball
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors found
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - gallery: 16.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - sharebymail: 1.0.1
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
SWIFT
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by icewind1991** [comment]
Is it only a problem with files that weren't added trough Nc? can you upload file (and then access those files) trough Nc?

**Comment by rontrompert** [comment]
An object store does not have a directory tree like structure. You have containers or buckets and you have objects. Nothing more. Suppose you have this on your local file system:

file1
file2
dir1
    file3
    file4
    file5
dir2
    file6

Syncing this with an object store (outside of nextcloud) you should get the following objects in your container:

file1
file2
dir1/file3
dir1/file4
dir1/file5
dir2/file6

When you couple the SWIFT object store with nextcloud you would only see this in the web interface:

file1
file2

Nothing more.

When dealing with an object store like SWIFT, a slash in a file name is not something to be worried about. It looks like nextcloud is choking on this. 

When I couple a SWIFT container to nextcloud and create files and folders through the web interface, everything is fine.

Cheers,

Ron

**Comment by rontrompert** [comment]
Basically a structure like this:
dir1
- file1
becomes the object:
dir1/file1

**Comment by SURFsara-e-infra** [comment]
This is still not fixed in 12.0.3. When creating a directory with a file in it in NC you see the following object in the object store:

directory/
directory/file

Uploading  a directory with a file in it with a tool like rclone you will get:

directory/file

and this remains unvisible in NC. However, when I created the directory "directory" in the NC web I/F, I suddenly do see:

directory/
directory/file

**Comment by SURFsara-e-infra** [comment]
I have done some more investigation. SWIFT has these pseudo-hierarchical folders. Clients fail to implement this consistently. 

Uploading a directory with a file in it (directory/file), you see the following:

rclone gives:

directory/file

but fails to generate the directory/ object.

duck gives:

directory
directory/file

Where "directory" has the content-type: application/directory. 

Neither of the structures above are picked up by Nextcloud. However when I create zero-byte object "directory/" with a "content-type: httpd/unix-directory" myself everything is fine and I see directories and files pop up in Nextcloud. 

How to solve this? Beats me. On one hand it would be good if there was some kind of standard on how to implement a pseudo-hierarchy of folders in object stores. Then you cloud beat client developers over the head with them not being compliant with the standard if things don't work. 

On the other hand, Nextcloud could "fix" this by assuming that when encountering object names like "directory/file" there should als be a zero-byte object named "directory/" with content-type httpd/unix-directory and create it if it does not exist.

**Comment by wiswedel** [comment]
Is this still happening on 16.0.1?

**Comment by MorrisJobke** [comment]
Should work in the meantime.

**Comment by fthouvenin** [comment]
This also doesn't work in v17...
