### ISSUE TITLE
Content Security Policy Headers and multiple trusted_domains

### ISSUE THREAD

**Issue by awlx** [nextcloud/server#5873]
Hi everybody,

I got some complains of users that Nextcloud is not working anymore as in showing a blank page or not being able to login anymore. 

I inspected the issue and saw, that Chrome forbids some content because of CSP violation. It happens for every trusted_domain except the "0" domain. Because background images and .js scripts seem to get delivered from the first domain in the array and thus are blocked.

It's nearly the same issue as here https://github.com/nextcloud/server/issues/4840 only that no Cloudflare is involved just more than one domain name.

http://i.imgur.com/iuWeGmC.png

Maybe it's a new bug?

**Comment by LukasReschke** [comment]
Duplicate of https://github.com/nextcloud/server/issues/5329 aka will be fixed with 12.0.1 (https://github.com/nextcloud/server/pull/5584)

**Comment by Zyplonox** [comment]
Im using apache 2.4.27 on a ubuntu 17.10 machine with MySQL and php 7.1.11. My Nextcloud version is 12.0.3. If i set the Content Security Policy Header i cant press the login button anymore. I used this to set the CSP: 
Header unset Content-Security-Policy
Header add Content-Security-Policy "default-src 'self'"
Header unset X-Content-Security-Policy
Header add X-Content-Security-Policy "default-src 'self'"
Header unset X-WebKit-CSP
Header add X-WebKit-CSP "default-src 'self'"


![1](https://user-images.githubusercontent.com/23319188/33034434-12efbb4e-ce28-11e7-9d04-4544bfe8a128.png)
![2](https://user-images.githubusercontent.com/23319188/33034435-13134ffa-ce28-11e7-9556-992d90a208b2.png)

Regards
