### ISSUE TITLE
"Allow editing" on a file doesn't work

### ISSUE THREAD

**Issue by meaz** [nextcloud/server#5876]
I'm on nextcloud 12.
When you want to share a file, it is possible to choose "allow editing" as you can see here: 
![](https://framapic.org/4UmhYUN9ZgZ6/nwUZx5mXtRoP)

Here, I shared "text.txt". However, it doesn't work when I open the link provided: I can download the text.txt, not edit it.

**Comment by rullzer** [comment]
Well you actually can. Just the https://github.com/nextcloud/files_texteditor doesn't work on the public page to edit

**Comment by meaz** [comment]
So the only way to edit a file that someone share is to have a nextcloud account?

**Comment by MorrisJobke** [comment]
> So the only way to edit a file that someone share is to have a nextcloud account?

Or use collabora that supports to edit office documents. This is currently the only supported file type.
