### ISSUE TITLE
Updater fails on OVH shared hosting

### ISSUE THREAD

**Issue by ElementW** [nextcloud/server#5878]
### Steps to reproduce
1. Buy an OVH "Perso" (`perso2014`) hosting plan
2. Install Nextcloud 11.0.0 (stable) using the PHP online installer file
3. Try to run the updater

### Actual behaviour
4. Be greeted by the following

> To login you need to provide the unhashed value of "updater.secret" in your config file.
> If you don't know that value, you can access this updater directly via the Nextcloud admin screen or generate your own secret:
`php -r '$password = trim(shell_exec("openssl rand -base64 48"));if(strlen($password) === 64) {$hash = password_hash($password, PASSWORD_DEFAULT) . "\n"; echo "Insert as \"updater.secret\": ".$hash; echo "The plaintext value is: ".$password."\n";}else{echo "Could not execute OpenSSL.\n";};'`

5. Do what is said
6. Have the updater fail to do any of its job, the "Login" button only sending you back to the admin page

### Expected behaviour

Updater should run

### Server configuration

**Operating system**: Debian GNU/Linux 8.8 (jessie)

**Web server:**  Apache/2.2.22

**Database:** MySQL 5.6.34-log

**PHP version:** 7.1.3

**Nextcloud version:** 11.0.0 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** PHP online installer file

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
$CONFIG = array (
  'instanceid' => '[ID]',
  'passwordsalt' => '[SALT]',
  'secret' => '[SECRET]',
  'trusted_domains' => 
  array (
    0 => '[DOMAIN]',
  ),
  'datadirectory' => '[ROOT]/data',
  'overwrite.cli.url' => '[DOMAIN]',
  'dbtype' => 'mysql',
  'version' => '11.0.0.10',
  'dbname' => '[DBNAME]',
  'dbhost' => '[DBHOST]',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '[DBUSER]',
  'dbpassword' => '[DBPASSWORD]',
  'logtimezone' => 'UTC',
  'installed' => true,
  'htaccess.RewriteBase' => '/',
  'theme' => '[THEME]',
  'updater.secret' => '[HASH]',
);
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Logs

data/nextcloud.log: no relevant entries

<details>
<summary>data/updater.log</summary>

```
2017-07-25T22:02:19+0200 qtkjJGYBrt [info] request to updater
2017-07-25T22:02:19+0200 qtkjJGYBrt [info] currentStep()
2017-07-25T22:02:19+0200 qtkjJGYBrt [info] show HTML page
2017-07-25T22:02:19+0200 qtkjJGYBrt [info] current version: 11.0.0 build time: 2016-12-13T13:24:49+00:00 ed7b18799f7d57ab9346e224b4dcea0961c9537f
```
</details>

**Comment by Swiiney** [comment]
Same here for update from 12.0.0 to 12.0.1.

Managed to do the update manually from 11.0.0 to 12.0.0 by uploading source to web server then heading my browser to the nextcloud homepage.

**Comment by MorrisJobke** [comment]
The updater doesn't show an update yet. What steps of the updater fail? And what are then the entires in the updater log?

Please report this to https://github.com/nextcloud/updater

Thanks

**Comment by Swiiney** [comment]
Done as [https://github.com/nextcloud/updater/issues/137](https://github.com/nextcloud/updater/issues/137)
