### ISSUE TITLE
Updater fails updating themeing

### ISSUE THREAD

**Issue by sebastianheyn** [nextcloud/server#5879]
### Steps to reproduce
1. update from 11.2 to 12 as suggested by the auto updater
2. wait for update to finish
3. updating apps

### Expected behaviour
Tell us what should happen
 should work

### Actual behaviour
Tell us what happens instead

Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'DELETE FROM `oc_reader_bookmarks` b WHERE b.file_id = ?' with params [93]: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'b WHERE b.file_id = '93'' at line 1

### Server configuration

**Operating system**: Gentoo Linux

**Web server:** Apache 2.4.25

**Database:**  MariaDB 10.0.30

**PHP version:** PHP 7.0.15

**Nextcloud version:** (see Nextcloud admin page)
12.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
11.2

**Where did you install Nextcloud from:**
updater in the admin area

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

</details>

 sudo -u apache ./occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <theming> ...
Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'DELETE FROM `oc_reader_bookmarks` b WHERE b.file_id = ?' with params [93]:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'b WHERE b.file_id = '93'' at line 1
Update failed
Maintenance mode is kept active
Reset log level

**Comment by sebastianheyn** [comment]
solution:  sudo -u apache ./occ app:disable files_reader

**Comment by juliushaertl** [comment]
This is no problem of the server component of Nextcloud, it is an issue of the files_reader app. Please open an issue in the app repo.
