### ISSUE TITLE
Cron jobs do not exit

### ISSUE THREAD

**Issue by fossxplorer** [nextcloud/server#5880]
I had around 600k entries in the oc_jobs table and now it's down to ~200. The cron was running fine, but now that the oc_table contains small amount of records, some of the cron jobs never exit. 
At max i've seen 5 jobs running at the same time. Crons are run every 15min in my system.
I've enabled debugging inside the cron.php:
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\Federation\\BackgroundJob\\RequestSharedSecret job with ID 1734675","level":0,"time":"2017-07-26T08:39:17+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\Passman\\BackgroundJob\\ExpireCredentials job with ID 1751208","level":0,"time":"2017-07-26T08:39:17+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"passman","message":"Passman cron test","level":1,"time":"2017-07-26T08:39:17+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}

{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\Passman\\BackgroundJob\\ExpireCredentials job with ID 1751208","level":0,"time":"2017-07-26T08:39:17+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807529","level":0,"time":"2017-07-26T08:39:17+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807529","level":0,"time":"2017-07-26T08:39:27+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807530","level":0,"time":"2017-07-26T08:39:27+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807530","level":0,"time":"2017-07-26T08:39:27+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1795364","level":0,"time":"2017-07-26T08:39:27+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1795364","level":0,"time":"2017-07-26T08:39:27+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807535","level":0,"time":"2017-07-26T08:39:27+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807535","level":0,"time":"2017-07-26T08:39:32+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807536","level":0,"time":"2017-07-26T08:39:32+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807536","level":0,"time":"2017-07-26T08:39:32+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807537","level":0,"time":"2017-07-26T08:39:32+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807537","level":0,"time":"2017-07-26T08:39:42+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1795365","level":0,"time":"2017-07-26T08:39:42+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1795365","level":0,"time":"2017-07-26T08:39:42+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807407","level":0,"time":"2017-07-26T08:39:42+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807407","level":0,"time":"2017-07-26T08:39:42+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1778480","level":0,"time":"2017-07-26T08:39:42+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1778480","level":0,"time":"2017-07-26T08:39:43+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807575","level":0,"time":"2017-07-26T08:39:43+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807575","level":0,"time":"2017-07-26T08:39:48+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807408","level":0,"time":"2017-07-26T08:39:48+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807408","level":0,"time":"2017-07-26T08:39:48+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807409","level":0,"time":"2017-07-26T08:39:48+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807409","level":0,"time":"2017-07-26T08:39:48+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807538","level":0,"time":"2017-07-26T08:39:48+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807538","level":0,"time":"2017-07-26T08:39:48+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807539","level":0,"time":"2017-07-26T08:39:48+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807539","level":0,"time":"2017-07-26T08:39:53+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OC\\Authentication\\Token\\DefaultTokenCleanupJob job with ID 1731634","level":0,"time":"2017-07-26T08:39:53+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OC\\Authentication\\Token\\DefaultTokenCleanupJob job with ID 1731634","level":0,"time":"2017-07-26T08:39:53+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\UpdateNotification\\Notification\\BackgroundJob job with ID 1731636","level":0,"time":"2017-07-26T08:39:53+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\UpdateNotification\\Notification\\BackgroundJob job with ID 1731636","level":0,"time":"2017-07-26T08:39:53+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807413","level":0,"time":"2017-07-26T08:39:53+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807413","level":0,"time":"2017-07-26T08:39:53+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807540","level":0,"time":"2017-07-26T08:39:53+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807540","level":0,"time":"2017-07-26T08:39:53+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807541","level":0,"time":"2017-07-26T08:39:53+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807541","level":0,"time":"2017-07-26T08:39:53+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807414","level":0,"time":"2017-07-26T08:39:53+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807414","level":0,"time":"2017-07-26T08:39:58+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807415","level":0,"time":"2017-07-26T08:39:58+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807415","level":0,"time":"2017-07-26T08:39:59+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\Files\\BackgroundJob\\DeleteOrphanedItems job with ID 1728188","level":0,"time":"2017-07-26T08:39:59+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\Files\\BackgroundJob\\DeleteOrphanedItems job with ID 1728188","level":0,"time":"2017-07-26T08:39:59+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\Federation\\SyncJob job with ID 1728191","level":0,"time":"2017-07-26T08:39:59+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\Federation\\SyncJob job with ID 1728191","level":0,"time":"2017-07-26T08:39:59+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807573","level":0,"time":"2017-07-26T08:39:59+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807573","level":0,"time":"2017-07-26T08:39:59+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807574","level":0,"time":"2017-07-26T08:39:59+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807574","level":0,"time":"2017-07-26T08:40:04+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807576","level":0,"time":"2017-07-26T08:40:04+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807576","level":0,"time":"2017-07-26T08:40:04+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OC\\Command\\CommandJob job with ID 1815312","level":0,"time":"2017-07-26T08:40:04+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OC\\Command\\CommandJob job with ID 1815312","level":0,"time":"2017-07-26T08:40:05+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807416","level":0,"time":"2017-07-26T08:40:05+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807416","level":0,"time":"2017-07-26T08:40:05+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807577","level":0,"time":"2017-07-26T08:40:05+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807577","level":0,"time":"2017-07-26T08:40:05+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807578","level":0,"time":"2017-07-26T08:40:05+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807578","level":0,"time":"2017-07-26T08:40:10+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1758170","level":0,"time":"2017-07-26T08:40:10+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1758170","level":0,"time":"2017-07-26T08:40:10+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807579","level":0,"time":"2017-07-26T08:40:10+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1807579","level":0,"time":"2017-07-26T08:40:10+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1758171","level":0,"time":"2017-07-26T08:40:10+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OCA\\LookupServerConnector\\BackgroundJobs\\RetryJob job with ID 1758171","level":0,"time":"2017-07-26T08:40:10+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OC\\Command\\CommandJob job with ID 1815313","level":0,"time":"2017-07-26T08:40:10+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OC\\Command\\CommandJob job with ID 1815313","level":0,"time":"2017-07-26T08:40:10+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OC\\Command\\CommandJob job with ID 1815314","level":0,"time":"2017-07-26T08:40:10+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Finished OC\\Command\\CommandJob job with ID 1815314","level":0,"time":"2017-07-26T08:40:10+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}
{"reqId":"+fvjVD\/uqb20kGhpuEaD","remoteAddr":"","app":"cron","message":"Run OC\\Command\\CommandJob job with ID 1815315","level":0,"time":"2017-07-26T08:40:10+00:00","method":"--","url":"--","user":"--","version":"11.0.2.7"}

### Steps to reproduce
1.Run NC cron jobs every 15min for at lest couple of hours
2.Check the running php processes to find out that there are multiple of cron jobs still running instead of just 1
3.

### Expected behaviour
Tell us what should happen
Expect the cron jobs to terminate when there are not many records in oc_jobs
### Actual behaviour
Tell us what happens instead
Multiple cron jobs are running. 
oc_jobs has < 210 records and many of them are of type OCA\LookupServerConnector\BackgroundJobs\RetryJob. Last record of this type:
mysql# select * from oc_jobs where class like "%Lookup%"
120. row ***************************
          id: 1812562
       class: OCA\LookupServerConnector\BackgroundJobs\RetryJob
    argument: {"dataArray":{"message":{"data":{"federationId":"ncuser11@cloud.mydomain.com","name":"","email":"","address":"","website":"cloud.com","twitter":"","phone":""},"type":"lookupserver","signer":"ncuser11@cloud.mydomain.com","timestamp":1500921133},"signature":"blabla=="},"retryNo":5}
    last_run: 1501058330
last_checked: 1501058330
 reserved_at: 0
120 rows in set (0.00 sec)

### Server configuration

**Operating system**:
C7.3
**Web server:**
Nginx
**Database:**
MariaDB 10.1
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
versionstring: 11.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
Github
*
EDIT 1: The memory usage when there are 3 crons running at the same time is ~8GB :(
 
@nickvergessen

**Comment by nickvergessen** [comment]
@schiessle

**Comment by MorrisJobke** [comment]
I would say that his is, because the jobs run longer and will run until there is no matching cron job anymore. A matching cron job is a cron job that was not executed in the last x minutes, where x is the interval for this cron job. This could happen if there are for example 2 cron jobs, that have an interval of 5 minutes, but both run 6 minutes. Maybe we should just quit the process every x executions to avoid memory leakage. Sounds like the poor mans solution, but it may actually help in this scenario.

**Comment by MorrisJobke** [comment]
@fossxplorer Is this still a problem in your case?

**Comment by nickvergessen** [comment]
We stop the execution after 14 minutes currently:
https://github.com/nextcloud/server/blob/1c38a83927ba318b1ef5115c0fe2fda0cdb5e454/cron.php#L132

And per our docs the cron should spawn all 15, so that sounds good.

If there is still an issue, feel free to reopen
