### ISSUE TITLE
Error in German translation [Administration - Teilen]

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#5904]
Enclosed you'll find the screen shot of the German translation  Vertrauenswürdige Server:

Actually I am using nextcloud version 12.0, however I found myself thrown back to owncloud,  as you can notice from the screen shot!

regard,
hitam4450
![nc_federation](https://user-images.githubusercontent.com/9738727/28666165-89a694d2-72c6-11e7-816e-031fd095ea18.png)

**Comment by MorrisJobke** [comment]
Let me check that. 😉

**Comment by MorrisJobke** [comment]
Thanks - fixed. Should be included in the upcoming 12.0.1
