### ISSUE TITLE
Naming of the owncloud.db - nextcloud.database

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#5906]
Hi, another obstacle is the naming of the owncloud (nextcloud).db database in nextcloud/data folder!

The same holds true for the oc_ prefix for the mysql database shouldn't it be nc_ ???

reagrds, hitam4450

![nextloud-data](https://user-images.githubusercontent.com/9738727/28669262-da1f1f30-72d3-11e7-9400-e5b1520ed054.png)

**Comment by MorrisJobke** [comment]
> The same holds true for the oc_ prefix for the mysql database shouldn't it be nc_ ???

Correct, but the migration path is really hard, because not all DBs support easy and fast renaming. So we sticked to the old names, because they are rarely seen. (same goes for the PHP namespace ;))
