### ISSUE TITLE
[stable12] Federated share icon is missing in Swedish translation

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#5911]
This is what it looks like on 12.0.1RC3 in `Personal settings`

![screenshot from 2017-07-27 22 42 22](https://user-images.githubusercontent.com/4511254/28691419-295465d0-731d-11e7-8c70-dad3ffc862e8.png)

As you can see the icon is missing. Is this a Transifex error or is it in the server code? It works with English translation.

**Comment by MorrisJobke** [comment]
Fix is in #5914

**Comment by rullzer** [comment]
#5914  is in
