### ISSUE TITLE
UI problem in sharing options

### ISSUE THREAD

**Issue by GitHubUser4234** [nextcloud/server#5916]
Hi,

In NC12, after a user has unchecked "Can create" checkbox in the sharing options of a folder, it looks like he cannot uncheck the "Can change" checkbox subsequently. The whole page has to be refreshed for him to be able to uncheck the "Can change" checkbox also. If the page is not refreshed, the only thing that visibly happens is that all checkboxes are disabled briefly and then enabled again.

**Comment by MariusBluem** [comment]
Could you please follow our issue template in the future? This helps us to reproduce issues more effective and faster ;) Please provide us some details about your environment (browser, ...), thanks!

**Comment by GitHubUser4234** [comment]
@MariusBluem Here is a gif where the issue can be quickly seen (takes a while to load). Unchecking a checkbox works only after a whole page refresh and only once:

![ice_video_20170731-150249 1](https://user-images.githubusercontent.com/16538178/28767076-e7611246-7604-11e7-98e5-e2eb56834128.gif)



Browsers used: Chrome 60.0.3112.78 and Firefox 54.0.1

**Comment by guiweber** [comment]
I am also seeing this on my setup. Let me know if more information would help.

### Server configuration

**Operating system**: Fedora 26
**Web server: Apache 2.4.27
**Database: MariaDB
**PHP version: 7.1.8
**Nextcloud version:** 12.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 12.0.0
**Where did you install Nextcloud from:** Web Installer

### Client configuration
**Browser:** Firefox 55.0.2
**Operating system:** Windows 10

**Comment by MorrisJobke** [comment]
Maybe somebody from @nextcloud/javascript want to look into this

**Comment by skjnldsv** [comment]
Can't reproduce on 13.
The can edit check is behaving as required.

**Comment by MorrisJobke** [comment]
@skjnldsv Could you test 12 as well please? :)

**Comment by skjnldsv** [comment]
Can confirm on stable12!

**Comment by blizzz** [comment]
Fix in https://github.com/nextcloud/server/pull/7211
