### ISSUE TITLE
Warning: PHP Opcache not properly configured

### ISSUE THREAD

**Issue by JMCA2** [nextcloud/server#5917]
From: https://help.nextcloud.com/t/warning-php-opcache-not-properly-configured/18637

> On the Admin panel the following warning is shown:
> 
> PHP Opcache is not properly configured
> I created a php.ini file on the Nextcloud folder, with the following content:
> 
> opcache.enable=1
> opcache.enable_cli=1
> opcache.interned_strings_buffer=8
> opcache.max_accelerated_files=10000
> opcache.memory_consumption=128
> opcache.save_comments=1
> opcache.revalidate_freq=1
> But the error is still showing.
> 
> Any ideas?
> 
> Shared Hosting
> Nextcloud version: 12
> Apache: 2.4 (CloudLinux)
> PHP version: 7.1

**Comment by gabrielelucci** [comment]
Hi, I had a similar issue with my Nextcloud 12 instance running on Ubuntu 16.04. I managed to get rid of the warning by appending 
```
opcache.enable=1
opcache.enable_cli=1
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=10000
opcache.memory_consumption=128
opcache.save_comments=1
opcache.revalidate_freq=1
```
to  `/etc/php/7.0/mods-available/opcache.ini` (path may vary depending on the distro).

Not sure if it's the right thing to do, but it worked **for me**. Hope this helps.

**Comment by JMCA2** [comment]
@gabrielelucci 
Hey, thanks for your idea.

Unfortunately, I don't have access to such directory as the installation is running on shared hosting.

**Comment by gabrielelucci** [comment]
@JMCA2 
Oh sorry, didn't read it was on shared hosting. I think you should ask your shared hosting provider if it's possible and how to  enable OPcache

**Comment by JMCA2** [comment]
@gabrielelucci 
OPCache is shown as enabled (and with recommended settings) according to the output of phpinfo(), yet NextCloud shows the warning

**Comment by enoch85** [comment]
@JMCA2 Ask your hosting provider to do [this](https://github.com/nextcloud/vm/blob/master/nextcloud_install_production.sh#L307-L320) + `sudo service apache2` restart and the warning will disappear.

**Comment by JMCA2** [comment]
@enoch85 I use litespeed, not Apache.

phpinfo() is showing OPCache as enabled and running with the recomended settings, though.

But the Warning is still showing

**Comment by JMCA2** [comment]
I've just noticed there are several entries like the following one, on the Logging area of the Admin section:

`Error | PHP | Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) at Unknown#0`

**Comment by JMCA2** [comment]
I have tried to remove the `opcache.enable 1` part, as per [@jamin587 suggestion on the forum](https://help.nextcloud.com/t/warning-php-opcache-not-properly-configured/18637/10?u=jmc), and now the warning is not showing.

Any idea why this might be required for the warning to stop showing?

**Comment by enoch85** [comment]
@JMCA2 Either you have it configured in a seperate file, or you have it configured globally. Probably it was enabled in both places and that's why you got the error. It's a PHP setting, not a Nextcloud setting.

Can we close this now?

**Comment by JMCA2** [comment]
@enoch85 Yes, thank you
