### ISSUE TITLE
Password change through API

### ISSUE THREAD

**Issue by GitHubUser4234** [nextcloud/server#5918]
Hi,

I couldn't find any existing discussion about this, so in this issue I'd like to test the waters in terms of feasibility of allowing users to change their password through API. WebDAV protocol doesn't provide a method for this feature, but the REST API looks like a way to achieve this. 

Making it possible to change the password through only an API call would certainly require to think this through security-wise, e.g. there probably wouldn't be a request token protecting the method etc... But still it doesn't have to mean implementing such feature isn't feasible.

There are use-cases where automated file interchange processes have to renew their passwords automatically, be it voluntarily for security reasons or because LDAP passwords expire.

Would be glad to hear your opinions, thanks 😸

**Comment by MorrisJobke** [comment]
This is covered by the rate limiting of the OCS API, right? @LukasReschke

**Comment by MorrisJobke** [comment]
> This is covered by the rate limiting of the OCS API, right? @LukasReschke

Closing.

**Comment by GitHubUser4234** [comment]
@MorrisJobke  Would you please explain why this got closed???

**Comment by MorrisJobke** [comment]
> @MorrisJobke Would you please explain why this got closed???

We have an API for changing the password https://docs.nextcloud.com/server/12/admin_manual/configuration_user/user_provisioning_api.html#edit-data-of-a-single-user and the security thing is covered by the rate limiting of the OCS API.
