### ISSUE TITLE
Allow encryption of contacts/parts of contacts via gpg/keybase or other.

### ISSUE THREAD

**Issue by mannp** [nextcloud/server#5926]
As the encryption module doesn't really add value according to most threads that I have read, perhaps allow users to encrypt all or part of a contacts details so confidential data is secured in case the nextcloud server is compromised.

The QNotes app does similar by allowing the importing of a keybase or gpg key and a button press allows encryption/decryption of that data. 

Thanks for your consideration

**Comment by MariusBluem** [comment]
Closing in favor of #5927 ... same for CardDAV ;)

**Comment by mannp** [comment]
I separated them as I presumed contacts and calendar were developed by different people.

Easy way to get the issues count down I guess.

**Comment by MariusBluem** [comment]
Please see my comment on #5927 ... CalDAV (Calendar) and CardDAV (Contacts) backends are part of the same app ... called `dav`
