### ISSUE TITLE
Support for multiple primary storage?

### ISSUE THREAD

**Issue by bearmoo-repo** [nextcloud/server#5928]
Hi,

I was wondering if there is support for multiple primary storage. For example:
'objectstore' => array(
        'class' => 'OC\\Files\\ObjectStore\\Swift',
        'arguments' => array(
                'username' => 'username',
                'password' => 'Secr3tPaSSWoRdt7',
                // the container to store the data in
                'bucket' => 'nextcloud',
                'autocreate' => true,
                'region' => 'RegionOne',
                // The Identity / Keystone endpoint
                'url' => 'http://example.com/v2.0',
                // optional on some swift implementations
                'tenantName' => 'username',
                'serviceName' => 'swift',
                // The Interface / url Type, optional
                'urlType' => 'internal'
        ),
        'class' => 'OC\\Files\\ObjectStore\\S3',
        'arguments' => array(
                'bucket' => 'nextcloud',
                'autocreate' => true,
                'key'    => 'EJ39ITYZEUH5BGWDRUFY',
                'secret' => 'M5MrXTRjkyMaxXPe2FRXMTfTfbKEnZCu+7uRTVSj',
                'hostname' => 'example.com',
                'port' => 1234,
                'use_ssl' => true,
                'region' => 'optional',
                // required for some non amazon s3 implementations
                'use_path_style'=>true
        ),

),

I am looking to migrate user data from one storage to another, or if anything expand storage for nextcloud to use.

**Comment by LukasReschke** [comment]
Multiple storages are not possible but you can use multiple buckets.  https://docs.nextcloud.com/server/11/admin_manual/configuration_files/primary_storage.html#multibucket-object-store
