### ISSUE TITLE
Can not enable local apps that are not present on the app store

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/server#5929]
I'm currently updating the app tutorial: https://github.com/nextcloud/app-tutorial

When I try to enable the app locally I'm getting: Could not download app notestutorial

Seems to work for News so my guess is that you can only enable apps locally that are present on the app store

I'm on the latest stable12 branch btw

**Comment by mwaeckerlin** [comment]
I can enable my local test app if it is in the `apps` dir and the `appinfo/info.xml` is correct.

**Comment by BernhardPosselt** [comment]
@mwaeckerlin are you on the latest stable12 branch?

**Comment by mwaeckerlin** [comment]
Yes, now I am on the latest stable OC12 release tag. Yes it works on OC11 and OC12.

I use: `https://download.nextcloud.com/server/releases/latest.tar.bz2`

Downloaded today.

**Comment by BernhardPosselt** [comment]
Ok, cloned everything again and it works now :)
