### ISSUE TITLE
Check password after second factor code entered

### ISSUE THREAD

**Issue by florealcab** [nextcloud/server#5935]
For now, server check password before second factor code was entered. Doing that, a hacker can try to find the password regardless of the second factor security. When he find it, he can now try to find a valid second factor code. So, using two factor authentication is less useful.

Solution: ask for the code of the second factor authentication without checking the password. Then check password AND second authentication code. If one of them is wrong, say that one of them is wrong, iwthout specifying which one.

Other tools working like this: rainloop (https://www.rainloop.net/), a SSH connexion on a server with TOTP enabled.

**Comment by ChristophWurst** [comment]
cc @nextcloud/security

**Comment by rullzer** [comment]
IMO this would not be a good idea:

* We already have brute force protection on the login pages
* 2FA is also affected by this

On top of that this would give away which users are using 2FA and which are not. Which is something we don't want to leak.

**Comment by nickvergessen** [comment]
Yeah the biggest issue is, that we don't know if 2FA is enabled for the user which the visitor has not yet submitted to the server.

**Comment by ChristophWurst** [comment]
As mentioned above this is not how we want to structure the 2FA login flow from both a technical as well as a UX perspective.

To be technically correct: even if you switched the order, the password would be effectively become your *second factor*. You wouldn't gain any security. Someone could then argue that it would be easy to guess the 2FA challenge without knowing the password.

I'm closing this therefore.
