### ISSUE TITLE
CSPv3 and web worker

### ISSUE THREAD

**Issue by sualko** [nextcloud/server#5936]
### Steps to reproduce
1. Use a web worker which calls `importScripts`
2. Try to use this web worker in a CSPv3 capable browser e.g. chromium

### Expected behaviour
Web worker should be executed without errors.

### Actual behaviour
We get an error like:
```
dsa-webworker.js:36 Refused to load the script 'http://localhost/nextcloud/apps/ojsxc/js/jsxc/dev/lib/otr/vendor/salsa20.js' because it violates the following Content Security Policy directive: "script-src 'nonce-YlBkdzRRNVpHVkNQKzJZc2ZSWmxlRzNBZXdkd1hjZnJGV05tMjJJMDI2OD06SzVGSW8xOFFLQ2ZNdWlKTExEa0NDenJ2UG0wSmJmQ0pRQThobWlsSHMrQT0=' 'unsafe-eval'".
```

### Server configuration

**Nextcloud version:** 13

cc @LukasReschke 

I tried to disable the use of nonces by calling:
```
$policy = new \OCP\AppFramework\Http\EmptyContentSecurityPolicy();
$policy->useJsNonce(null);
```
but this gets overwritten in [SecurityMiddleware.php#L219](https://github.com/nextcloud/server/blob/8c5062794f3abc157e48af2cf4bc3c0dfe570cbe/lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php#L219). I also tried to add all ww dependencies with `OCP\Util::addScript`, but Chromium refused the script nonetheless.

**Comment by LukasReschke** [comment]
I wouldn't recommend to disable JS nonces, can you share the code that you want to execute? I can then see what policy may be best there. (ideally, as an app that I can just git clone 😉 )

**Comment by sualko** [comment]
App: https://github.com/nextcloud/jsxc.nextcloud/releases/tag/v3.3.0-beta.1
Web worker: https://github.com/nextcloud/jsxc.nextcloud/blob/v3.3.0-beta.1/build/js/jsxc/lib/otr/build/dsa-webworker.js

**Comment by sualko** [comment]
If you clone the repo, just use the `build` folder as root for the app (aka rename build to ojsxc).

**Comment by sualko** [comment]
Maybe [worker-src](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/worker-src) comes in handy? I will do some tests, but I assume this directive is not meant for imported scripts.

**Comment by sualko** [comment]
As expected, worker-src didn't work.

**Comment by cluxter** [comment]
I confirm the same bug here on my side, Nextcloud 12.0.2

**Comment by sualko** [comment]
Any update on how to use web workers with this strict csp?

**Comment by rullzer** [comment]
NC15 has the ability to set a workerSrc in the CSP:)

**Comment by sualko** [comment]
@rullzer That's nice, but as stated the worker src is not working. Even if it's set the browser will refuse to load the script.

**Comment by rullzer** [comment]
@sualko do you have a branch somewhere where I can take a look?

**Comment by sualko** [comment]
As linked above:

App: https://github.com/nextcloud/jsxc.nextcloud/releases/tag/v3.3.0-beta.1
Web worker: https://github.com/nextcloud/jsxc.nextcloud/blob/v3.3.0-beta.1/build/js/jsxc/lib/otr/build/dsa-webworker.js
