### ISSUE TITLE
TESTS-ACCEPTANCE=login not working

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#5950]
Ref https://drone.nextcloud.com/nextcloud/server/523/43

No idea why. But either we fix it or we disable the test to prevent more mistakes such as https://github.com/nextcloud/server/pull/5949 …

**Comment by LukasReschke** [comment]
`\OC\User\Manager::$backends` is empty and thus `\OC\User\Manager::get` returns `null` at https://github.com/nextcloud/server/blob/5185a3c0c957bc01f159118a32a0a4aaf1f23532/lib/private/User/Manager.php#L140

**Comment by LukasReschke** [comment]
Found the breaking commit … Preparing a PR and thinking how to add integration tests to this case…

**Comment by LukasReschke** [comment]
Fix at https://github.com/nextcloud/server/pull/5951 … now let's see how to get integration tests here 😄

**Comment by MorrisJobke** [comment]
> now let's see how to get integration tests here 😄

Wasn't the reason for this issue, that the integration tests failed? 🤔

**Comment by LukasReschke** [comment]
> Wasn't the reason for this issue, that the integration tests failed? 🤔

I wouldn't call an acceptance test that randomly covers this specific issue adequate integration tests for the whole user management API. But yes, the acceptance tests called an API which didn't work. But for proper integration tests I'd expect tests against every single API in the user mgmt.

**Comment by LukasReschke** [comment]
So yes: Awesome that the test caught this, but would be more awesome to rely on a test suite that tests the whole `\OC\Settings\Controller\ChangePasswordController` :)

**Comment by LukasReschke** [comment]
Our cyclomatic complexity on `\OC\Settings\Controller\ChangePasswordController::changeUserPassword` alone  is 20 conditions and 19 paths as per https://scrutinizer-ci.com/g/nextcloud/server/code-structure/master/operation/OC%5CSettings%5CController%5CChangePasswordController%3A%3AchangeUserPassword 🙈
