### ISSUE TITLE
Error while searching for User to share Folder with

### ISSUE THREAD

**Issue by Dirk23** [nextcloud/server#5961]
### Steps to reproduce
This may be only reproducible on my Server
1. Login as User
2. Create a Folder or choose a existing one
3. klick the sharing Button
4. enter Name of local User I want to share that folder with

### Expected behaviour
There should be a list of user like the name I entered

### Actual behaviour
nothing happens. In the Logfile are errors listed that seem to be related to that problem

### Server configuration

**Operating system**: Ubuntu 16.04 LTS

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 7.0

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Update, original from Owncloud to NC11 to NC12. I also needed to migrate this NC Install to a other server, because of Harddisk problems.

**Where did you install Nextcloud from:**
Download from Nextcloud Website and manually installed.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocddxk6acff3",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.7.21",
            "cloud.myurl.de"
        ],
        "datadirectory": "\/var\/cloud\/data",
        "overwrite.cli.url": "http:\/\/192.168.7.21\/nextcloud",
        "overwritehost": "cloud.myurl.de",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "htaccess.RewriteBase": "\/nextcloud\n",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "user",
        "mail_domain": "merl.de",
        "mail_smtpauth": 1,
        "mail_smtphost": "192.168.7.12",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```
</details>

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

</details>

### Client configuration
**Browser: any

**Operating system:** any

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT `c`.`carddata`, `c`.`uri` FROM `oc_cards` c WHERE `c`.`id` IN (SELECT DISTINCT `cp`.`cardid` FROM `oc_cards_properties` cp WHERE (`cp`.`addressbookid` = ?) AND ((`cp`.`name` = ?) OR (`cp`.`name` = ?)) AND (`cp`.`value` COLLATE utf8mb4_general_ci LIKE ?))' with params ["2", "CLOUD", "FN", "%dirk%"]: SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'utf8mb4_general_ci' is not valid for CHARACTER SET 'utf8'
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Dirk23** [comment]
i fixed it, but I don't think that this is the best way. I enabled Emoji Support because I just wanted to change caracter set the collation and so I found [this](https://docs.nextcloud.com/server/11/admin_manual/maintenance/mysql_4byte_support.html). after following these instructions my search works fine now. Maybe only executing the occ repair should have done it too, but I can't confirm.

**Comment by nc0815** [comment]
I had the same issue. But running occ repair did not help for me. I seems that it was related to user id at database which where not found at the lookup. I have changed name of the failed user and the renamed back to current value. This udated row at database and set correct uid.
