### ISSUE TITLE
Description in below file/folder names 

### ISSUE THREAD

**Issue by mara21** [nextcloud/server#5962]
I thing will be nice to have option to add descriptions to folder or file and this description to be shown in small text area below the file/folder name ([EXAMPLE](https://help.nextcloud.com/uploads/default/original/2X/c/ca85eb44843bd7731e11ddf74c5ff1fec2bda987.png)).
Best regards,
M. Iliev

**Comment by LukasReschke** [comment]
Duplicate of #2426
