### ISSUE TITLE
CSS #oc-dialog-filepicker-content: wrong display of date

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/server#5968]
The date information is positioned not correctly. Same on 12.0.0 and 12.0.1 RC4

![grafik](https://user-images.githubusercontent.com/26707476/28938513-979f36f2-788e-11e7-9105-9def13c84fb3.png)

Adding following CSS fixes the display:
`#oc-dialog-filepicker-content .filelist .date {
	display: table-cell;
	position: initial;
}`

![grafik](https://user-images.githubusercontent.com/26707476/28938583-c4266c18-788e-11e7-9349-e239cb92645d.png)

I am no css pro, so maybe there will be another or better fix for this.

Problem was visible in the mail add, when trying to svae an attachment to files.

**Comment by MorrisJobke** [comment]
@dartcafe Which browser do you use? I can't reproduce this on master. I tested Safari, Chrome and Firefox.

**Comment by MorrisJobke** [comment]
I even tested Edge and it works fine there.

**Comment by juliushaertl** [comment]
As stated in the PR:

> That issue seems to be related only to the mail app, so i guess we should try to fix it over there. All other file choosers work as expected.

**Comment by dartcafe** [comment]
I looked for a file picker in another app, but I didn't find. :-) Any hint? 

Issue in mail app is reproducible in Safari (iPad) Firefox (iPad and Windows), Chrome (Windows) and Edge.

**Comment by dartcafe** [comment]
Ha. As I write it down, I found it in the files app, when rying to move a file. I will make a new PR in the mail app repository. Thanks for review.

**Comment by MorrisJobke** [comment]
@dartcafe To trigger it type this in the console in your webdev tools in the browser:


```js
OC.dialogs.filepicker('A')
```
