### ISSUE TITLE
Loading/working icon position is off by 1 pixel in core CSS rules

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#5970]
The loading/working icon is created using a squared element with totally round borders and an infinite rotation animation. When using absolute positioning the element is relative to its containing block, and its top and left attributes define the position of the top left corner of its bounding box (including the border). The loading/working icon is an _::after_ pseudo-element and it is thus positioned relative to the element it belongs to (that is, the element that uses `class="loading-icon"`); the top and left attributes of the icon are set to `50%`, so the top left corner of its bounding box would be centered in the element it belongs to. However, it also uses a negative margin, which should align the center of the icon with the center of its element.

I have noticed that the loading/working icon position is off by 1 pixel in the core CSS rules: [the size of the large icon is 30px](https://github.com/nextcloud/server/blob/bb865a55febe7b712a0e6cc7e1e93034f60a0e8b/core/css/icons.scss#L47) and [the size of the small icon is 14px](https://github.com/nextcloud/server/blob/bb865a55febe7b712a0e6cc7e1e93034f60a0e8b/core/css/icons.scss#L72), [both with a 2px border](https://github.com/nextcloud/server/blob/bb865a55febe7b712a0e6cc7e1e93034f60a0e8b/core/css/icons.scss#L59), thus the total size is 34px and 18px. However, [the margin used to center the large icon is -16px](https://github.com/nextcloud/server/blob/bb865a55febe7b712a0e6cc7e1e93034f60a0e8b/core/css/icons.scss#L49) and [the margin used to center the small icon is -8px](https://github.com/nextcloud/server/blob/bb865a55febe7b712a0e6cc7e1e93034f60a0e8b/core/css/icons.scss#L74), which would be the right values if the total size was 32px and 16px, but not 34px and 18px.

Current margin:
![before-loading](https://user-images.githubusercontent.com/26858233/28939684-6a5c843e-7892-11e7-966c-69369e6b16fa.png)
![before-loading-box](https://user-images.githubusercontent.com/26858233/28939689-6db5d07c-7892-11e7-9006-890b8fdb8824.png)

Fixed margin (-17px and -9px):
![after-loading](https://user-images.githubusercontent.com/26858233/28939672-5be0a4bc-7892-11e7-87b2-44417b49c33c.png)
![after-loading-box](https://user-images.githubusercontent.com/26858233/28939675-60d916a2-7892-11e7-8cda-2e31209777f2.png)

@nextcloud/designers, are you aware of this? Is this a (really minor, I know :-P ) bug, or is this on purpose? Am I missing something?

**Comment by MorrisJobke** [comment]
> I have noticed that the loading/working icon position is off by 1 pixel in the core CSS rules: the size of the large icon is 30px and the size of the small icon is 14px, both with a 2px border, thus the total size is 34px and 18px. However, the margin used to center the large icon is -16px and the margin used to center the small icon is -8px, which would be the right values if the total size was 32px and 16px, but not 34px and 18px.

I would say: fix this margin-off-by-one bug. It should be completely center to look also visually nice.

**Comment by jancborchardt** [comment]
Yup, agree with @MorrisJobke. Great detail find @danxuliu! :)

**Comment by MorrisJobke** [comment]
@danxuliu Could you open a PR for that?

**Comment by skjnldsv** [comment]
I love those kind of things! :D 
Nice catch @danxuliu

**Comment by pixelipo** [comment]
By the way, I would rather fix this by making the total size 16 and 32px instead of using custom margin sizes

**Comment by jancborchardt** [comment]
@pixelipo I think it's done this way because it looks nicer in combination with the 32px/16px icons we use.

In any case, @danxuliu want to open a PR for this? ;)
