### ISSUE TITLE
Preview of theming does not work anymore

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#5975]
* change a value in the theming app
* wait for it to be saved
* then the "Loading preview" will show up
* actual: it loads endlessly and if you look at the network it will show you a 404 on `css/core/server.css`
* expected: the server.css is properly loaded and the loading spinner goes away

Problem: The server.css is in my instance for example served under `css/core/72408cbdff8901cd16b886aeabcc367c-server.css` - I guess the `reloadStylesheets()` method needs an adjustment to fetch the current name of this an reload that css.

https://github.com/nextcloud/server/blob/3470d0a44ea2b7a477af407b3d9abee81de071e3/apps/theming/js/settings-admin.js#L44-L65

cc @danxuliu @juliushaertl @nextcloud/theming 

Valid for at least master.

**Comment by danxuliu** [comment]
I was already working on fixing this ;-)

**Comment by juliushaertl** [comment]
Also broken on 12.0.1 RC4

**Comment by MorrisJobke** [comment]
Fix is in #5981

**Comment by nursoda** [comment]
Seems I'm hit by this in NC17, too. Standard setup of nginx/mariadb/apcu/redis on Arch.

I get 404 for https://test.seyfarth.de/apps/theming/styles?reload=1570557643276.
FX_DevConsoleNetwork says "cache-control: no-cache, no-store, must-revalidate".

@fduraibi What do you mean by disabling cache? Redis? Not an option except for debugging :-)
