### ISSUE TITLE
Undefined index: uidnext When Using Mail App

### ISSUE THREAD

**Issue by circlenaut** [nextcloud/server#5987]
### Steps to reproduce
1. Install Mail App
2. Add multiple IMAP Internet Accounts
3. Browse mail; error pops up in log

### Expected behaviour
The log should be free of errors

### Actual behaviour
I get the following error in the log:
Undefined index: uidnext at /var/www/nextcloud/apps/mail/lib/Account.php#701

### Server configuration

**Operating system**: Ubuntu 16.04 Server

**Web server:**
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-07-27T14:34:01

**Database:**
Your MariaDB connection id is 1076
Server version: 10.0.31-MariaDB-0ubuntu0.16.04.2 Ubuntu 16.04

**PHP version:**
PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
**Nextcloud version:** (see Nextcloud admin page)
12 RC5
**Updated from an older Nextcloud/ownCloud or fresh install:**
12 stable --> RC4 --> RC5
**Where did you install Nextcloud from:**
Git

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**
root@cloud:/var/www/nextcloud# sudo -u www-data php occ app:list
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - audioplayer: 2.0.2
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - checksum: 0.3.5
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - deck: 0.2.1
  - drawio: 0.8.8
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.4
  - files_downloadactivity: 1.1.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - groupfolders: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.5
  - nextant: 1.0.8
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - onlyoffice: 1.1.3
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - socialsharing_email: 1.0.1
  - socialsharing_facebook: 1.0.1
  - socialsharing_googleplus: 1.0.1
  - spreed: 2.0.1
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.0
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - encryption
  - files_external
  - registration
  - user_external
  - user_ldap

``

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "ocbihr9vsn1t",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.com",
            "cloud.example.me"
        ],
        "datadirectory": "\/cloud\/mount",
        "dbtype": "mysql",
        "version": "12.0.1.4",
        "dbname": "nextcloud",
        "dbhost": "localhost:5432",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "maintenance": false,
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "webmaster",
        "mail_domain": "example.com",
        "overwrite.cli.url": "https:\/\/cloud.example.com",
        "overwriteprotocol": "https",
        "updater.release.channel": "beta",
        "loglevel": 3,
        "theme": "",
        "htaccess.RewriteBase": "\/",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
Yes, LUKS mounted container

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
Any

**Operating system:**
Windows 10/7
#### Web server error log
<details>
<summary>Web server error log</summary>

Undefined index: uidvalidity at /var/www/nextcloud/apps/mail/lib/Account.php#700

#### Nextcloud log (data/nextcloud.log)
{"reqId":"WXQpgC06PdMAAHim1aYAAAAM","level":3,"time":"2017-07-23T04:44:10+00:00","remoteAddr":"172.56.31.136","user":"circlenaut","app":"PHP","method":"POST","url":"\/apps\/mail\/accounts","message":"fsockopen(): unable to connect to mx2.zoho.com:143 (Connection timed out at \/var\/www\/nextcloud\/apps\/mail\/lib\/Service\/AutoConfig\/ConnectivityTester.php#45","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko\/20100101 Firefox\/54.0","version"

**Comment by LukasReschke** [comment]
Please reopen at https://github.com/nextcloud/mail
