### ISSUE TITLE
Feature request: custom knowledgebase url

### ISSUE THREAD

**Issue by zeigerpuppy** [nextcloud/server#5988]
In Nextcloud 12, it would be useful to be able to specify custom URLs or paths for the knowledgebase items. 
We host nextcloud and would like to direct users to some custom information that refers to the features as they are specifically installed and configured on our server.
At the moment I have kludged this by having a static directory replacing the docs, but I'm sure there's a better way!

**Comment by LukasReschke** [comment]
You can have your own URL by implementing your own theme https://github.com/nextcloud/server/blob/21f2fe5cb97985596879032d1191612cab31b9d5/themes/example/defaults.php#L63-L69
