### ISSUE TITLE
Do not get data via webdav

### ISSUE THREAD

**Issue by aimuz** [nextcloud/server#5996]
I want to develop a theme, but I do not want to use this webdav interface, I think this seems to be small for the memory server can not cope with, and feel that this is synchronous, rather than asynchronous, when a request is blocked, others seem unable to visit, Sometimes. When I have a large number of files inside a folder is always loaded. Until all the files are displayed. I do not want that, I need a page that can be paged. So I would like to ask if there are APIs for RESTful API design specifications. Then my theme is combined with this API. I looked at the official API documentation, but there was no such API

**Comment by MorrisJobke** [comment]
We will only support WebDAV as API for files, because maintaining 2 APIs that serve the same content would be bad.


cc @icewind1991 or @rullzer for more, but I guess that's how it is.
