### ISSUE TITLE
Manual Upgrade from 10 to 12 'nextcloud.oc_accounts' doesn't exist

### ISSUE THREAD

**Issue by ladrua** [nextcloud/server#5999]
### Steps to reproduce
1. Download new version of nextcloud.
2. Replace files, and keep config.php
3. Run `occ upgrade`

### Expected behaviour
Upgrade and let me go on with my life.

### Actual behaviour
Get error 
```
Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM `oc_accounts` WHERE `user_id` IS NOT NULL LIMIT 1':

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_accounts' doesn't exist
Update failed
```

### Server configuration

**Operating system**:
Ubuntu 14.04.5 / docker image
**Web server:**
Apache2.4
**Database:**
MySql 5.7
**PHP version:**
PHP 7.0
**Nextcloud version:** (see Nextcloud admin page)
12.0.0.39
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 10.0.0
**Where did you install Nextcloud from:**
self made docker image, grab stable sources from website.
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
  - activity: 2.3.2
  - calendar: 1.4.1
  - comments: 1.0.0
  - contacts: 1.5.1
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - lookup_server_connector: true
  - mail: 0.6.0
  - notifications: 0.3.0
  - oauth2: true
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - theming: 1.0.1
  - twofactor_backupcodes: true
  - updatenotification: 1.0.1
  - user_ldap: 1.0.1
  - workflowengine: 1.0.1
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Comment by LukasReschke** [comment]
So you updated from an Nextcloud 10.0.0 to Nextcloud 12.0.0? From those versions exactly?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/pull/5695 should fix this, however I never found a way to create this issue without running master code, so I did no backport

**Comment by nickvergessen** [comment]
@ladrua if you add the 3 lines from https://github.com/nextcloud/server/pull/5695/files to `lib/private/Repair/Owncloud/SaveAccountsTableData.php` it should work just fine

**Comment by ladrua** [comment]
Thanks @nickvergessen that worked just fine!
