### ISSUE TITLE
disabling previews makes gallery app show no files

### ISSUE THREAD

**Issue by outsinre** [nextcloud/server#6000]
### Steps to reproduce
1. 'enable_previews' => false,
2. Click Gallery app.

### Expected behaviour
Gallery app should show media files (i.e. jpg).

### Actual behaviour
Gallery app tells:

>No media files found
>Upload new files via drag and drop or by using the [+] button above

What is worse, newly uploaded jpg through + button in Gallery app won't show up either.

### Server configuration

**Operating system**: CentOS 7 64-bit

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.0

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Comment by MorrisJobke** [comment]
This is because the gallery uses the preview generator. cc @oparoz @rullzer 

I guess there is no way around this.

**Comment by outsinre** [comment]
@MorrisJobke 

Disabling previews improves Nextcloud performance greatly. If there is no way, I have to disable Gallery app.

**Comment by rullzer** [comment]
No way around as far as I know. It is intentional so it does not try to load a screen full of 20mega pixel images.

**Comment by MorrisJobke** [comment]
> No way around as far as I know. It is intentional so it does not try to load a screen full of 20mega pixel images.

Yes. Sadly this will not be handled, because either you allow previews and then can run the gallery or not.

Regarding performance: yes it "improves" but on the other side it decreases UX, because a user needs to open all images to see, what they are about and has no small preview of it.
