### ISSUE TITLE
Opening local copies of direct links

### ISSUE THREAD

**Issue by 9662** [nextcloud/server#6005]
My requirement:

> As a Nextcloud server, Nextcloud desktop client and Nextcloud Android client user, I would like that when following a direct link (e.g., `https://cloud.example.com/f/16350`) on a locally synchronised cloud, I would have the choice to navigate to / open the local copy of that resource.

I am aware that this may be feasible in Android by implementing changes to the local client, while on desktop clients it may be quite a bit more challenging. Nevertheless, I feel this would be an important feature in terms of improving usability and effective remote collaboration.

**Comment by MorrisJobke** [comment]
cc @karlitschek @rullzer

**Comment by ChristophWurst** [comment]
I'm closing this ticket because it hasn't received any updates in a long time. If this is still relevant, feel free to re-open or file a new ticket.

Thank you.

**Comment by 9662** [comment]
@ChristophWurst still entirely relevant, in my view. Why not just reopen this issue?

I admit that I don't have any good ideas on how to do it in a clean and UX-satisfactory way. Closest that I could get was fantasising about a browser add-on, but the user would need to configure the URL(s) of the locally sync'ed clouds. Then it would also probably require installing a schema handler in the browser or OS.

The flow could be like this:

Assume a user with two locally sync'ed clouds:

* `https://cloud.example.com/` → `/home/user/COM/`
* `https://cloud.example.net/` → `/home/user/NET/`
* `https://nuage.example.net/` is a CNAME for `https://cloud.example.net/`

1. User installs add-on / schema handler
2. User configures add-on by entering the three above URLs and their respective local directories
3. User follows a link such as `https://cloud.example.com/f/123`
4. Add-on detects that this *could* correspond to a locally sync'ed file (the user may be using partial synchronisation) and offers a choice to open local or view in browser.
5. If view in browser is chosen, the user follows the same workflow as usual (logging in, etc.)
6. If view local, the add-on would have to figure out a way to cause the local file to be opened, if it exists. One possible way would be by means of redirecting to a custom schema, such as `x-nextcloud://cloud.example.com/f/123` that gets picked up by the relevant handler, but I haven't fully thought this through.

**Comment by szaimen** [comment]
As far as I know, opening internal links with the android app already works. -> closing.

**Comment by maninthemiddle01** [comment]
[#51851](https://github.com/nextcloud/server/issues/51851) as well as the open issues [https://github.com/nextcloud/android/issues/1069](https://github.com/nextcloud/android/issues/1069) and [https://github.com/nextcloud/android/issues/5915](https://github.com/nextcloud/android/issues/5915) could be referenced.
