### ISSUE TITLE
Send notification about own activity setting in personal setting is ignored unless also set globally

### ISSUE THREAD

**Issue by elpraga** [nextcloud/server#6011]
Nextcloud 12.01

### Steps to reproduce
1. uncheck "send notification about own activity" in the admin page
2. check "send notification about own activity" in the personal page
3. no emails are sent

### Expected behaviour
emails regarding personal activity are sent when set in the personal page

### Actual behaviour
emails are note sent

**Comment by LukasReschke** [comment]
Please reopen at https://github.com/nextcloud/activity, thanks!
