### ISSUE TITLE
Repairs Steps not executed when re-enabling a disabled app

### ISSUE THREAD

**Issue by daita** [nextcloud/server#6015]
### Steps to reproduce
1. Disable an app
2. Downgrade the installed_version in oc_appconfig
3. Enable the app

### Expected behaviour
I should be redirected to the upgrade page of Nextcloud so that the repair steps would be initiated

### Actual behaviour
A popup is telling me that I will be redirected 
![image](https://user-images.githubusercontent.com/1038617/29039231-b7d21286-7baa-11e7-8f56-d280dfac6600.png)

Redirection is done on the same page, the installed_version in oc_appconfig is updated but not Repair/Update script have been called.

### Server configuration

**Operating system**: Linux/Debian

**Web server:** Apache2

**Database:** MariaDB

**PHP version:** 

**Nextcloud version:** 12.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** zip file on nc.com + web update 

**Signing status:** good.

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:                                                                                                                                                                          
  - activity: 2.5.2                                                                                                                                                               
  - admin_notifications: 1.0.0                                                                                                                                                    
  - announcementcenter: 3.1.0                                                                                                                                                     
  - bookmarks: 0.10.1                                                                                                                                                             
  - bruteforcesettings: 1.0.2                                                                                                                                                     
  - calendar: 1.5.3                                                                                                                                                               
  - circles: 0.12.2                                                                                                                                                               
  - comments: 1.2.0                                                                                                                                                               
  - contacts: 1.5.3                                                                                                                                                               
  - dav: 1.3.0                                                                                                                                                                    
  - deck: 0.2.1                                                                                                                                                                   
  - federatedfilesharing: 1.2.0                                                                                                                                                   
  - federation: 1.2.0                                                                                                                                                             
  - files: 1.7.2                                                                                                                                                                  
  - files_pdfviewer: 1.1.1                                                                                                                                                        
  - files_sharing: 1.4.0                                                                                                                                                          
  - files_texteditor: 2.4.1                                                                                                                                                       
  - files_trashbin: 1.2.0                                                                                                                                                         
  - files_versions: 1.5.0                                                                                                                                                         
  - files_videoplayer: 1.1.0                                                                                                                                                      
  - firstrunwizard: 2.1                                                                                                                                                           
  - gallery: 17.0.0                                                                                                                                                               
  - logreader: 2.0.0                                                                                                                                                              
  - lookup_server_connector: 1.0.0                                                                                                                                                
  - mood: 0.3.1                                                                                                                                                                   
  - nextant: 1.0.8                                                                                                                                                                
  - notes: 2.3.1                                                                                                                                                                  
  - notifications: 2.0.0                                                                                                                                                          
  - oauth2: 1.0.5                                                                                                                                                                 
  - ocsms: 1.12.0                                                                                                                                                                 
  - onlyoffice: 1.1.3                                                                                                                                                             
  - password_policy: 1.2.2                                                                                                                                                        
  - previewgenerator: 1.0.6                                                                                                                                                       
  - provisioning_api: 1.2.0                                                                                                                                                       
  - rainloop: 5.0.0                                                                                                                                                               
  - serverinfo: 1.2.0                                                                                                                                                             
  - sharebymail: 1.2.0                                                                                                                                                            
  - survey_client: 1.0.0                                                                                                                                                          
  - systemtags: 1.2.0                                                                                                                                                             
  - tasks: 0.9.5                                                                                                                                                                  
  - theming: 1.3.0                                                                                                                                                                
  - twofactor_backupcodes: 1.1.1                                                                                                                                                  
  - updatenotification: 1.2.0                                                                                                                                                     
  - workflowengine: 1.2.0              
Disabled:                                                                                                                                                                         
  - admin_audit                                                                                                                                                                   
  - apporder                                                                                                                                                                      
  - encryption                                                                                                                                                                    
  - external                                                                                                                                                                      
  - files_accesscontrol                                                                                                                                                           
  - files_automatedtagging                                                                                                                                                        
  - files_external                                                                                                                                                                
  - files_retention                                                                                                                                                               
  - mail                                                                                                                                                                          
  - nextcloud_announcements                                                                                                                                                       
  - richdocuments                                                                                                                                                                 
  - templateeditor                                                                                                                                                                
  - user_external                                                                                                                                                                 
  - user_ldap                                                                                                                                                                     
  - user_saml                                                                                                                                                                     
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "oczu1yt4x4w4",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.artificial-owl.com"
        ],
        "datadirectory": "\/home\/www\/cloud.artificial-owl.com\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.artificial-owl.com\/",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "12.0.1.5",
        "dbname": "artificialowl_cloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 1,
        "updater.release.channel": "production",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** firefox

**Operating system:** linux (mint 18.2)

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
Not sure why, but sounds like another reason for https://github.com/nextcloud/server/issues/5964
