### ISSUE TITLE
Disable mass download button on shares

### ISSUE THREAD

**Issue by yamlfd** [nextcloud/server#6016]
I'm using nextcloud to share image galleries. The idea is to only show the image gallery and do not allow everyone to fully download the images with a single click. This means the download links need to be removed.

Is there an app for this or can you add this small but very important feature, please?

**Comment by LukasReschke** [comment]
This is currently not something that we consider part of our standard software. You can however achieve that by programming a small app that removes the button or write a small CSS custom theme for it.

**Comment by yamlfd** [comment]
This could be an optional setting on share form. Very simple in core.

Can you tell me how I'm able to alter the share form and override the files with custom files? I'm doing lots of drupal development, but have not seen any hook_form_alter or theme override functions in your software. I have also not seen a theme engine... theming of nextcloud seems to be limited to 5/6 config options.

**Comment by hjochman** [comment]
This patch removes the Download buttons for the N15 Gallery app

[gallery_no_download.patch.txt](https://github.com/nextcloud/server/files/2783860/gallery_no_download.patch.txt)
