### ISSUE TITLE
Remember the current directory when switching apps (Files/Gallery)

### ISSUE THREAD

**Issue by heinrichmartin** [nextcloud/server#6021]
### Steps to reproduce
1. Browse to a directory in the Files app.
2. Switch to the Gallery app.

### Expected behaviour
The Gallery app opens the recently visited directory.

### Actual behaviour
The Gallery app opens the user's home directory.

### Notes
I will happily add configuration details if relevant, but I assume that this is a feature request rather than a bug. It looks like nextcloud does not have the concept of a "current directory" or at least does not forward URL parameters between apps.
Also note that the Files app and the Gallery app seem to use different mechanisms to track the current item: `files/?dir=X&fileid=N` vs `gallery/#X`

### Workaround
Note that these two apps provide icons to seamlessly switch between them: Use the dedicated "switch view" feature instead of the Direct Menu app.

**Comment by SlavikCA** [comment]
> ### Workaround
> Note that these two apps provide icons to seamlessly switch between them: Use the dedicated "switch view" feature instead of the Direct Menu app.

@heinrichmartin ,
Can you please elaborate on workaround:
Where do you find "icons to seamlessly switch"?
I can't find.

**Comment by j-ed** [comment]
> Also, comparing path, they seems to be structured and encoded differently:
> https://cloud.aidcim.org/index.php/apps/gallery/#TeamDrives%2FProjects%2FPROJECTS%202018%2FKazakhstan%2FEaster%202018%20KZ%2FPetropavlovsk
> 
> vs
> 
> https://cloud.aidcim.org/index.php/apps/files/?dir=/TeamDrives/Projects/PROJECTS%202018/Kazakhstan/Easter%202018%20KZ/Petropavlovsk&fileid=2531491

Due to the fact that the trick is already done when pressing the ![20190106_nc_pic_switch](https://user-images.githubusercontent.com/2572764/50736196-acab2f80-11ba-11e9-8dbb-0a30e9bc1c66.png) -button in the files app and the ![20190106_nc_file_switch](https://user-images.githubusercontent.com/2572764/50736201-c9476780-11ba-11e9-9f28-d356a2e48d97.png)-button in the gallery app, it shouldn't be a unresolvable problem.

**Comment by AInteriorB** [comment]
That will be up to date again due to the new introduced grid view. One is not able anymore to switch between file and gallery view. Is there a way to have the old behaviour again?

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
