### ISSUE TITLE
Upgrade to 12.0.1 takes to long for Web GUI

### ISSUE THREAD

**Issue by ThomasSteinbach** [nextcloud/server#6027]
### Steps to reproduce
1. Start upgrade from 12.0.0 to 12.0.1 on Web GUI
2. Reload Browser after Upgrade
3. Wait for final upgrade steps

### Expected behaviour
Nextcloud should properly be upgraded to 12.0.1 and working

### Actual behaviour
The upgrader fails and Nextcloud resides in maintainance mode

### Server configuration

official Docker Image with seperate MySQL instance / monstly default configuration

### My investigation

After the failed online upgrade I started the `./occ upgrade` procedure by hand on the server. The upgrade seems to work but still takes a lot of time. The last line displayed after the upgrade seems hanging is:

    Checked for update of app "workflowengine" in appstore

After further investigation the MySQL instance is on high CPU load and processing following queries during the upgrade (example output, heavy shortened and anonymized):

```
mysqladmin -p -i 2 --verbose processlist

...
Sending data | SELECT `fileid` FROM `oc_filecache` WHERE (`storage` = '6') AND (`path` = 'files/xxx/xxx Sundh�user See/xxx Sundh�user See-318-2.JPG')
Sending data | SELECT `fileid` FROM `oc_filecache` WHERE (`storage` = '6') AND (`path` = 'files/xxx/xxx Sundh�user See/xxx Sundh�user See-318.NEF')
updating | UPDATE `oc_filecache` SET `path` = 'files/xxx/xxx Sundh�user See/xxx Sundh�user See-320-2.NEF', `path_hash` = MD5('files/xxx/xxx Sundh�user See/xxx Sundh�user See-320-2.NEF'), `storage` = '6' WHERE `fileid` = '303297'
...
```

However the upgrade is running since 3 hours and still running. It seems that the Web Updater wouldn't wait that long for the upgrade finished.

**Comment by noresistence** [comment]
Looks like my issue is the same: https://github.com/nextcloud/server/issues/6017

**Comment by ThomasSteinbach** [comment]
Sorry - duplicate of #6017
