### ISSUE TITLE
Video sizing on the public share page

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#603]
When sharing a video via link, the size of the video container should be the same as the video, or maximally the width of the viewport. Currently it looks like this:
![capture du 2016-07-27 14-47-01](https://cloud.githubusercontent.com/assets/925062/17175665/176d4d0c-5409-11e6-9e68-fee345174be9.png)
(Whereas the actual video is a lot bigger.)

cc @oparoz @Instagit @schiessle

**Comment by icewind1991** [comment]
No way around this really since we don't know the video size until we start playing

**Comment by jancborchardt** [comment]
Maybe then we should up the default size to something more reasonable or bigger? What’s a good default? Maybe 1280*720, or maximum the width of the viewport? cc @MorrisJobke

**Comment by jancborchardt** [comment]
Youtube default seems to be 854*480px, we could go for that.

**Comment by jancborchardt** [comment]
Fix at https://github.com/nextcloud/server/pull/625
