### ISSUE TITLE
Granular Permissions on App Passwords

### ISSUE THREAD

**Issue by benyanke** [nextcloud/server#6030]
App passwords, in a sense, are like API keys for the "normal" user - they allow access to a resource without sharing the main account password. Frequently, at least in my usecase, app passwords are used for single-purpose software or situations (for example, a task-list or calendar client app).

I'd like to propose that app passwords be assigned granular permissions, which would allow one to set up, for example, a calendar app which can only access your calendar, instead of everything on the server.

Starting out, it could be as simple as:

* One blanket permission for each app (one for calendar, one for tasks, etc) - perhaps breakout read and write?
* File reading
* File writing/modification
* Account Administration/Ability to Log in (as opposed to WebDAV access)

As such, an example permission list on a typical NextCloud instance might look like:

- [x] App: Calendar
- [ ] App: Tasks
- [x] App: Notes
- [ ] File Read
- [ ] File Write and Modification
- [ ] Log-in

**Comment by j-ed** [comment]
I found several other app password related issues which could possibly summarized under this issue too:
- https://github.com/nextcloud/server/issues/6376 App password restrictions for specific nextcloud apps
- https://github.com/nextcloud/server/issues/3228 App passwords should be optional
- https://github.com/nextcloud/server/issues/2866 Allow to restrict app password data access

**Comment by ChristophWurst** [comment]
>     * #6376 App password restrictions for specific nextcloud apps

Was just about to comment that :+1: 

Let's continue there :wink:
