### ISSUE TITLE
Security-icon is not fitting on Personal-settings page

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#6033]
It should be the twofactor_backupcodes one ;) Backup codes should get another icon. This is only an issue with Nextcloud 12 ... with the unified settings-page in Nextcloud 13 this is solved ... but should be fixed for 12 anyway I think :)

<img width="250" alt="bildschirmfoto 2017-08-08 um 17 20 20" src="https://user-images.githubusercontent.com/19711361/29079622-edcec2c2-7c5d-11e7-890f-d357bbd3f282.png">

**Comment by MorrisJobke** [comment]
Fix is in #7116

**Comment by jancborchardt** [comment]
Fix merged
