### ISSUE TITLE
User shouldn't be shown in contactlist if the account is deactivated

### ISSUE THREAD

**Issue by EasyPeasy1** [nextcloud/server#6038]
Hi,

### Expected behaviour
1. Deactivate a user account
2. Search for the user account of the deactived user
![image](https://user-images.githubusercontent.com/24621703/29090042-ab82526e-7c7e-11e7-9fff-6b428d916740.png)
3. User shouldn't be shown in the contact menu

### Actual behaviour
3. User is available in the contact menu

Nextcloud version: 12.0.1

**Comment by MorrisJobke** [comment]
cc @ChristophWurst @georgehrke

**Comment by ChristophWurst** [comment]
Is this still an issue? IIRC this has been fixed but I can't find it in the code right now. @EasyPeasy1 could you lease re-verify?

**Comment by MorrisJobke** [comment]
Works for me in the latest versions so I will close this for now. If this is still an issue for you feel free to comment here.
