### ISSUE TITLE
just say thank you

### ISSUE THREAD

**Issue by peturbg** [nextcloud/server#6042]
and please be forever free, happen what happen be forever free and dont sell your asses " ass " to cia, nsi, fbi and governments. Make all programs that you make free and force corporarions only buy your programs. force university too pay money for use nextcloud and all applications. and it go ehy. public servants, universitis and rich peoples, they gain more than 3000 euros and when they work in public servants, they robbery only company to give them free programs and for normal peoples it cost money, example windows 7 legal dvd with legal key becore 2 years it cost more 200 euros and for public sercants, university, police peoples and they are free. THIS IS DISCRIMINATIONS. so expensive programs for normal peoples and  the same programs for public servants free. THIS IS DISCRIMINATIONS. IN THE LAW WE EVERY HUNANKIND IS EQUAL. so if public servants use free programs then normal peoples need too to use free programs. nextcloud MAKE ALL NEXTCLOUD WITH ALL MODULES FREE and force public servants, university and etc. and when they try install your products FORCE THEM pay you monthly and anual money, include nextcloud force them send you identifications cards in photo and sign from public servants and from public workers so they can certificate and make data base that normal peoples can consult 7 days, 24 hours, 365 days. governments and all public workers need to be forced be transparency fail the normal peoples too will not be transparency. the public servants, the public workers works for the normal peoples and normal peoples wants to know where they money go and not to go in robbery. and nextcloud make nextcloud operarion system and make encryption extreme so include military cant brake it. normal peoples wants freedom.

**Comment by MorrisJobke** [comment]
Thanks

**Comment by skjnldsv** [comment]
Thank you!
