### ISSUE TITLE
Integrated User documentation is not translated

### ISSUE THREAD

**Issue by JSoko** [nextcloud/server#6044]
### Steps to reproduce
1. Click on the integrated Help
2. Choose "Dokumentation für Benutzer" (User Documentation)
3. Texts under https://xxx.xx/settings/help?mode=user are in english and not translated
see: https://help.nextcloud.com/t/gibt-es-deutsche-hilfetexte-fuer-benutzer/19217

### Expected behaviour
Should be translated with transifex (yes, I know it will be much work...)

### General server configuration

**Operating system:** Linux nc-vm 4.8.0-46-generic #49~16.04.1-Ubuntu SMP Fri Mar 31 14:51:03 UTC 2017 x86_64

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.19

**PHP version:** 7.0.18-0ubuntu0.16.04.1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - apache2handler
 - redis
 - mysqlnd
 - PDO
 - xml
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - iconv
 - imap
 - intl
 - json
 - ldap
 - exif
 - mcrypt
 - mysqli
 - pdo_mysql
 - pdo_pgsql
 - pdo_sqlite
 - pgsql
 - Phar
 - posix
 - readline
 - shmop
 - SimpleXML
 - smbclient
 - sockets
 - sqlite3
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - libsmbclient
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.1 - 12.0.1.5

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:**  Updater

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - announcementcenter: 3.1.0
 - apporder: 0.4.0
 - audioplayer: 2.0.2
 - bookmarks: 0.10.1
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - deck: 0.2.1
 - external: 2.0.3
 - federatedfilesharing: 1.2.0
 - files: 1.7.2
 - files_downloadactivity: 1.1.1
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - gallery: 17.0.0
 - impersonate: 1.0.1
 - issuetemplate: 0.2.2
 - keeweb: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - news: 11.0.5
 - nextcloud_announcements: 1.1
 - notes: 2.3.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - ocsms: 1.12.0
 - password_policy: 1.2.2
 - piwik: 0.3.1
 - polls: 0.7.3
 - previewgenerator: 1.0.6
 - provisioning_api: 1.2.0
 - radio: 0.5.0
 - richdocuments: 1.12.34
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_email: 1.0.1
 - spreed: 2.0.1
 - spreedme: 0.3.11
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - encryption
 - federation
 - files_external
 - firstrunwizard
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "loglevel": 2,
    "maintenance": false,
    "theme": "scloud",
    "integrity.check.disabled": false,
    "default_language": "de_DE",
    "logtimezone": "Europe\/Berlin",
    "log_rotate_size": 500000,
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "activity_expire_days": 33,
    "trusted_domains": {
        "0": "localhost",


    },
    "trashbin_retention_obligation": "auto, 10",
    "versions_retention_obligation": "auto, 21",
    "datadirectory": "\/media\/nc1\/data",

    "dbtype": "mysql",
    "version": "12.0.1.5",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "ocq6gzv14h2p",
    "appstore.experimental.enabled": "true",
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "\/var\/run\/redis\/redis.sock",
        "port": 0,
        "timeout": 0,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "htaccess.RewriteBase": "\/",
    "mysql.utf8mb4": true,
    "mail_smtpmode": "smtp",
    "mail_smtphost": "smtp.1und1.de",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "no-reply",

    "mail_smtpport": "587",
    "updater.release.channel": "production"
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0

**Operating system:** YOUR ANSWER HERE

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
There was even the try to translate this, but it a major workload and it will be super fast out of date: https://github.com/nextcloud/documentation/tree/master/user_manual_de

This is more documentation issue and nothing for the server.

**Comment by rakekniven** [comment]
Hello @MorrisJobke 

We shoud start this issue again where? In which repo?
https://github.com/nextcloud/documentation/issues ?

So language teams should be able to translate official docs. 
Do you have an idea how to add translations to Transifex?
With Transifex we could use our i18n team.

**Comment by chris246** [comment]
This is still an open issue.
I didn't find a followup discussion in the documentation repository.

As the user documentation is now fully translated [1], it would be great, if the Nextcloud server could be shipped with the localized version of the user documentation and choose the language based on the preferred user's locale (browser or individual setting).

[1] https://explore.transifex.com/nextcloud/nextcloud-user-documentation/
