### ISSUE TITLE
Fatal error - Sabre\VObject\InvalidDataException: Unsupported VALUE parameter for DTEND property. You supplied ""

### ISSUE THREAD

**Issue by nephilim75** [nextcloud/server#6053]
### Steps to reproduce
1. import *.ics-file (calendar)
2.
3.

### Expected behaviour

It should import the calendar without showing errors in log and while import of the calendar.

### Actual behaviour
When the import is done an error message is coming up. It inform about partial import but with amount of errors. These mentioned amount is one row in error log.
But the appointments are present and visible.

### Server configuration

**Operating system**: Raspbian GNU/Linux 8 (jessie)"

**Web server:** nginx/1.6.2

**Database:** MySQL/5.5.57

**PHP version:** 5.6.30

**Nextcloud version:** 11.0.4.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh installation

**Where did you install Nextcloud from:** wget https://download.nextcloud.com/server/releases/latest-11.zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - calendar: 1.5.3
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - encryption: 1.4.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.1.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - activity
  - admin_audit
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/media\/usbhdd-a\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "11.0.4.1",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APC",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2
    }
}

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 54

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
2017/08/09 07:54:51 [error] 915#0: *5973 access forbidden by rule, client: ***classified***, server: ***classified***, request: "GET /data/htaccesstest.txt HTTP/1.1", host: "***classified***"
2017/08/09 09:51:55 [error] 914#0: *7714 upstream timed out (110: Connection timed out) while reading response header from upstream, client: ***classified***, server: ***classified***, request: "MOVE /remote.php/dav/uploads/***classified***/9897143$
2017/08/09 09:51:59 [error] 912#0: *7614 upstream timed out (110: Connection timed out) while reading response header from upstream, client: ***classified***, server: ***classified***, request: "MOVE /remote.php/dav/uploads/***classified***/3200263$
2017/08/09 10:01:31 [error] 914#0: *9752 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: ***classified***, server: ***classified***, request: "GET /logout?requesttoken=***classified***
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

![grafik](https://user-images.githubusercontent.com/19992865/29124977-b9f9e360-7d1a-11e7-97ed-c628f344dec3.png)

</details>

**Comment by LukasReschke** [comment]
Can you by any chance share the relevant ICS file with us? 

cc @georgehrke

**Comment by georgehrke** [comment]
Looks like `DTEND;TZID=Europe/Berlin;VALUE=:2017...`

@nickvergessen Does this ring any bell? This seems familiar to me

**Comment by nephilim75** [comment]
This is really sensitive private data. Don't want to share them public. Any address I can send it to?

Kind regards
//neph
-- 
Von unterwegs...

Am 15. August 2017 18:14:11 MESZ schrieb Lukas Reschke <notifications@github.com>:
>Can you by any chance share the relevant ICS file with us? 
>
>cc @georgehrke

**Comment by nickvergessen** [comment]
You can send it to `<my github name>@nextcloud.com`

**Comment by nephilim75** [comment]
Just sent per mail to provided mail address.

**Comment by nickvergessen** [comment]
I can not reproduce the issue with the Unsupported VALUE.

I only get `Sabre\VObject\Recur\NoInstancesException: This recurrence rule does not generate any valid instances`

That is due to the fact that there is an event in the ics file which is reoccuring, but has no time in the future, only in the past.

If you still get the other issue, we would need the file that was actually imported, not the one which was generated afterwards, because in the file you emailed me there is nothing wrong with the DTEND

**Comment by skjnldsv** [comment]
:trumpet: @georgehrke

**Comment by georgehrke** [comment]
> Unsupported VALUE parameter for DTEND property

Looks like your Calendar data contained something like:
`DTEND;VALUE=:2019...`

Whatever program you exported it from creates malformed calendar data. Server does not accept broken calendar data, works as expected.

I opened a ticket in the library (to be) used by the calendar app so we sanitise it there before importing. I don't see a need to fix it in the server though.
