### ISSUE TITLE
setup max upload file limited failed

### ISSUE THREAD

**Issue by aabbbaabbb** [nextcloud/server#6058]
Steps to reproduce

I follow the video to setup nextcloud
https://www.youtube.com/watch?v=nXr_muYB6xI

change conf of /etc/php/7.0/apache2/php.ini
memory_limit = 2500MB
post_max_size = 2400MB
upload_max_filesize = 2300MB

restart apache2

login to NC by admin and change admin->additional settings->file dandling->Maximum upload size 
change to 2300MB

upload a 4GB file 

upload success

Expected behaviour
cannot upload bigger than 2300 MB file

Actual behaviour
upload a 4GB file success

No errors in any log file.

Server configuration

Operating system: ubuntu 16.04 LTS

Web server : Apache2

Database :Mysql

PHP version :php7

Nextcloud version: 12.0.0

Updated from an older Nextcloud/ownCloud or fresh install:fresh install

Are you using encryption: no

Browser: Google Chrome

Operating system:ubuntu 16.04 LTS

**Comment by MorrisJobke** [comment]
> login to NC by admin and change admin->additional settings->file dandling->Maximum upload size
> change to 2300MB

This is not an actual restriction, but an maximum limit that is raised. That means, that this only was one  possible issue, that would forbid to upload bigger files. It was never meant in a way that quota for example does. And this setting will go once we have chunked upload in the web UI as well. It is only a technical limitation not a business logic.

The reason it work for you: in other configuration files (apache/php) this is set to a higher limit and therefor works.

Closing as non-issue.
