### ISSUE TITLE
Content-Type null on external webdav

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#6059]
Ref: https://github.com/nextcloud/android/issues/468#issuecomment-321267591
Steps
- link to an external web dav (not sure if other externals are also affected)
- create a file without an extension
- do a PROPFIND on the folder

Working file:
```
<d:response>
		<d:href>/remote.php/webdav/WebDAV/first_created_file.txt</d:href>
		<d:propstat>
			<d:prop>
				<d:getlastmodified>Wed, 09 Aug 2017 12:42:32 GMT</d:getlastmodified>
				<d:getcontentlength>28</d:getcontentlength>
				<d:resourcetype/>
				<d:getetag>&quot;1c-5565169dd3e00&quot;</d:getetag>
				<d:getcontenttype>text/plain</d:getcontenttype>
			</d:prop>
```

Non working file:
```
<d:response>
		<d:href>/remote.php/webdav/WebDAV/second_created_file</d:href>
		<d:propstat>
			<d:prop>
				<d:getlastmodified>Wed, 09 Aug 2017 12:43:11 GMT</d:getlastmodified>
				<d:getcontentlength>29</d:getcontentlength>
				<d:resourcetype/>
				<d:getetag>&quot;1d-556516c3055c0&quot;</d:getetag>
				<d:getcontenttype></d:getcontenttype>
			</d:prop>
```

--> as you can see the conent-type is empty/null
On an internal storage it is in this case: "application/octet-stream"

@MorrisJobke

**Comment by MorrisJobke** [comment]
cc @rullzer

**Comment by mvdwater** [comment]
I have a problem with Nextcloud 12.0.4 which could be related to this issue.

I have an external Webdav mount for which folders turn up empty ('no files here') when a file with unknown file type is in the folder. If I remove the file or rename the file to a 'known' file type the folder will suddenly show its contents.
The behavior looks much like the referenced Android behavior, but I'm actually seeing it in the web view. The android app however has identical behavior (also there the files are not shown).

**Comment by rullzer** [comment]
Assinging to myself so I'll finally look into this once 13 is out.

**Comment by tobiasKaminsky** [comment]
*silently ping @rullzer*

**Comment by szaimen** [comment]
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!
