### ISSUE TITLE
"Only preview" option for shared multimedia files and download limit count

### ISSUE THREAD

**Issue by kaksikanaa** [nextcloud/server#6063]
We need this option when sharing draft videos or music to the customers for a comment. They should only have a possibility to view or listen video/voice (mp4, mp3) files from the linked page but there should not be any download option in that page nor in the player. Best option would be if there could be some code to prevent too easily to find the linked file from the linked page source code and prevent mechanism for just right click the mouse button in browser on top of the video and just choose to Save as -option...

So it would be very helpful if there could be a new option in sharing link to mp4 and mp3 files  (or even PDF which nowadays usually opens in the browser)
[ ] Only preview (no download)
 
Other needed option is download limit count 
__ Allowed downloads (max count)

BR

**Comment by MorrisJobke** [comment]
I guess we will not something like this. The right click thingy is a lot of snake oil and removing the download button on an already downloaded asset. Sounds weird to me. :/

cc @karlitschek

**Comment by karlitschek** [comment]
Yes. I don't think we should add more sharing options. it is already quite complex. This feature could maybe done with a special theme or app.

**Comment by kaksikanaa** [comment]
Ok, thank you for your comments -> We have to continue to use Pydio in these needs then (they have done this quite good way).  And Morris, we meant to prevent the customer downloading the draft asset till it is the final version of it (video, music etc.). This is quite basic need in all the creative organizations where we are facing problems when customer shares draft file to everyone and many mistakes happens because of that behavior. The download limit count would be the second best option for this.

**Comment by kaksikanaa** [comment]
Just noticed that the Seafile server has this feature also like Pydio does. Any possibility to add this feature to Nextcloud as well? The code and mechanism can be seen on those projects as a example?
