### ISSUE TITLE
After Upgrade 12.0.0 => 12.0.1 favicon on login-page is not themed anymore

### ISSUE THREAD

**Issue by benbrummer** [nextcloud/server#6068]
After upgrade favicon on login-page is not themed anymore.
favicon urls:
https://<nextcloud>/core/img/favicon.ico
https://<nextcloud>/core/img/favicon-touch.png

Favicon for files, gallery and so on is still themed
https://<nextcloud>/apps/theming/favicon/files?v=45

The one from settings was on login page before upgrade
https://files.pinteam.eu/apps/theming/favicon/settings?v=45

**Comment by MorrisJobke** [comment]
cc @juliushaertl

**Comment by juliushaertl** [comment]
Please fill out the issue template to provide some more information about your setup and possible errors in the logfiles.

**Comment by benbrummer** [comment]
Since the update to 12.0.2 the problem is not there anymore.
