### ISSUE TITLE
Name and status in top right dropdown menu

### ISSUE THREAD

**Issue by archont00** [nextcloud/server#6069]
### Steps to reproduce
1. Login to nextcloud

### Expected behaviour
The user should be able to see his login name, avatar or whatever that makes clear who is logged in.

If not directly in top bar, then at least in the drop-down menu of the "settings" icon. Displaying there an empty avatar and text Personal ("Osobní") has no informational value.

### Actual behaviour
User name is not displayed.

### Server configuration

**Operating system**:
Alpine Linux

**Web server:**
Nginx

**Nextcloud version:**
12.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
12.0
**Where did you install Nextcloud from:**
wonderfall/nextcloud docker image

![nextcloud 12 0 1 - missing username](https://user-images.githubusercontent.com/937861/29171876-523d1804-7dde-11e7-8ace-17607faa0b5b.png)

**Comment by MorrisJobke** [comment]
@nextcloud/designers because we intentionally removed it. Wasn't the plan to add this as first entry in the gear icon?

**Comment by jancborchardt** [comment]
> The user should be able to see his login name, **avatar** or whatever that makes clear who is logged in.

If the avatar is set, then it is shown instead of the gearwheel icon.

We could add it as the first entry of the gear icon, but it would just duplicate the link to »Settings«. We could say »Log out `username`« on the bottom, but then the menu would get very wide.

What do the other @nextcloud/designers think?

**Comment by MariusBluem** [comment]
![eb570c82-c335-4408-8343-cb19bbd70f6e](https://user-images.githubusercontent.com/19711361/29242490-9c8bfbc6-7f8e-11e7-9201-175024f60fbb.png)

**Comment by MariusBluem** [comment]
- Maybe replace the gear with the initials (as on sharing or personal settings page too) to indicate better who is logged in ;)

**Comment by jancborchardt** [comment]
> Maybe replace the gear with the initials (as on sharing or personal settings page too) to indicate better who is logged in ;)

We tried that out, it looked strange. We tried it with white circle around white initial, white filled circle with primary colored initial, and colored filled circle with initial (like elsewhere) – all looked weird and didn’t make it obvious for new users where settings are. This settings icon is very nice for the first run experience.

But yeah, the proposal to add the name and online status etc is where we can go. However we don’t have online status or anything like that yet. ;)

**Comment by compumatter** [comment]
Not sure if this is the right place for this but I would like to add this as a feature I would like.  Since I administer multiple user accounts at my company there is on easy way to know who's account I'm logged into without logging into their profile.   It would be nice in the menu at the top

**Comment by gitwolf1060** [comment]
Just upgraded from 12.0.1 to 12.0.4, and now the menu is missing. I do have the search icon and the "imprint" in the top right corner. Disabling the imprint app via CLI does not help. The "delete *.css" workaround did not help either. The ff workaround code line is by now part of the installation anyway. The browser is irrelevant, firefox, chrome, konqueror, qupzilla on linux and ff and edge on win10 all yield the same result. 
Any new ideas anyone how to approach the issue, please?

**Comment by MariusBluem** [comment]
Please open a new issue for this @gitwolf1060

**Comment by rullzer** [comment]
We show the avatar now

**Comment by MorrisJobke** [comment]
let's close this for now and focus on more specific items if there is still a problem with this approach.

**Comment by MorrisJobke** [comment]
> But yeah, the proposal to add the name and online status etc is where we can go. However we don’t have online status or anything like that yet. ;)

Or do we still want to add this? @jancborchardt @nextcloud/designers

**Comment by jancborchardt** [comment]
Yeah, I'd say this is still relevant, and the proposal by @MariusBluem is also quite specific. As we move more into communication, you need to know quickly how you appear to others (in picture, name, profile data etc.).

**Comment by MorrisJobke** [comment]
Most likely nothing for 14 -> moving to 15.

**Comment by skjnldsv** [comment]
What is the status here then?
Should we add an entry with the username?

**Comment by MorrisJobke** [comment]
@nextcloud/designers Should we do this or not?

**Comment by jancborchardt** [comment]
Yes, the proposal by @MariusBluem at https://github.com/nextcloud/server/issues/6069#issuecomment-321992303 is basically what we should do – simply add an entry on the top with avatar and name.

It should be combined with "Settings" as it would just go to the same place.

**Comment by MorrisJobke** [comment]
Let's move it to 17.

**Comment by MorrisJobke** [comment]
Implemented in 20.
