### ISSUE TITLE
Show phpinfo configuration or make it possible to configure the integrity checker to ignore certain files? 

### ISSUE THREAD

**Issue by radoeka** [nextcloud/server#6070]
### Steps to reproduce
1. Install php script phpinfo.php in nextcloud folder
2. The script calls phpinfo()
3. Login into the web admin portal

### Expected behaviour
Nextcloud integrity checker should ignore this file.  E.g. because the file added to nextcloud configuration to be ignored.  Or the files is provided by default by nextcloud.

### Actual behaviour
Nextcloud 12.0.1 reports an integrity warning / error

### Server configuration

**Operating system**: linux
**Web server:** apache
**Database:** sqlite3
**PHP version:** 7.0.7
**Nextcloud version:** 12.0.1

Or is there another way to show the php configuration via nextcloud?

See also:
https://help.nextcloud.com/t/is-it-possible-to-configure-the-integrity-checker-to-ignore-certain-files/19387

**Comment by MorrisJobke** [comment]
The idea of the integrity checker is to detect if there are files, that may interfere with the Nextcloud. As far as I remember it was not planned to allow "exceptions" from this. Please put those files in a separate directory outside of nextcloud and make it accessible there if you really need it.

cc @LukasReschke

**Comment by radoeka** [comment]
> Please put those files in a separate directory outside of nextcloud and make it accessible there if you really need it.

Not possible as nextcloud is de root of the server.  Any directory is to be added in the nextcloud environment.  Hence an exception is needed.  The phpinfo I needed to determine which php modules are installed / available during install and upgrade times.

It should be possible to whitelist files.

**Comment by LukasReschke** [comment]
We won't support whitelisting as the integrity checker is also meant as a support tool. In this case I'd recommend to live with the warning (which is only visible for administrators).
