### ISSUE TITLE
Little 1 in the middle of the Personal page

### ISSUE THREAD

**Issue by Trevelian** [nextcloud/server#6074]
### Steps to reproduce
1. Go to the Personal page of a user
2. Scroll down and see a little 1 on the Webpage
![screenshot from 2017-08-10 19-08-29](https://user-images.githubusercontent.com/4093808/29182895-f4d5c922-7e00-11e7-9731-9376610f6c40.png)

![screenshot from 2017-08-10 19-24-00](https://user-images.githubusercontent.com/4093808/29183062-8f048c90-7e01-11e7-9e86-9f88269b88c0.png)

### Expected behaviour
No "1" :-p

### Server configuration

**Operating system**:
Archlinux
**Web server:**
Apache
**Database:**
Mariadb
**PHP version:**
7.1
**Nextcloud version:** (see Nextcloud admin page)
12.0.1
**Where did you install Nextcloud from:**
from nextcloud.com

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.6.4
  - news: 11.0.5
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - passman: 2.1.4
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.0
  - workflowengine: 1.2.0
```

### Client configuration
**Browser:**
Firefox
**Operating system:**
Archlinux / W10

**Comment by brantje** [comment]
Happens here too:
![image](https://user-images.githubusercontent.com/2758767/29222162-b0d11c60-7ec1-11e7-8065-13fe8e599529.png)

NC 12.0.1

**Comment by nickvergessen** [comment]
Seems like it's an `echo` couldnt find any var_dump

**Comment by MorrisJobke** [comment]
Could you disable apps step by step and check again to know which app does this. Looks like an app registers on the personal settings page and somehow prints the number.

**Comment by Trevelian** [comment]
@MorrisJobke Hello, the little 1 appear with the "Passman" application.

**Comment by MorrisJobke** [comment]
Then please report this to passman. Nothing we can do in the server here. :/

https://github.com/nextcloud/passman/issues

@brantje
