### ISSUE TITLE
Sessions and App Passwords not working on personal page

### ISSUE THREAD

**Issue by linucksrox** [nextcloud/server#6077]
### Steps to reproduce
1. Upgrade from 11.03 to 11.04
2. Upgrade from 11.04 to 12.01
3. Go to the personal settings page

### Expected behaviour
Sessions and App Passwords should appear

### Actual behaviour
There is a loading circle overlapping the text in both of these sections, and it continues for at least several minutes (I don't think it's actually loading anything).

![image](https://user-images.githubusercontent.com/5169868/29191417-a0b16b22-7deb-11e7-975f-e523b8109994.png)

### Server configuration

**Operating system**: Ubuntu 16.04.3 64bit

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.0

**Comment by MorrisJobke** [comment]
Could you open the web developer tools of your browser and open the network tab. Reload the page and check the "XHR" section in the network tab for entries. Maybe there are some red ones.

**Comment by linucksrox** [comment]
Everything is green in the XHR section, even after reloading the page and waiting several minutes. I'm not sure where else to look.

**Comment by eggithub** [comment]
related to #6139? I see my sessions but my app passwords vanished after an upgrade from 12.0.0 to 12.0.1, persists in 12.0.2

made a post a while back, maybe also related?  #4535

**Comment by linucksrox** [comment]
I updated twofactor_totp to 1.3.1, and Nextcloud to 12.02. I'm not sure which one fixed the issue, but everything works again on the Personal page.
