### ISSUE TITLE
Wrong User Manual version in Nextcloud version 11.0.4 server download files

### ISSUE THREAD

**Issue by igitigt** [nextcloud/server#6081]
### Steps to reproduce
1. Download https://download.nextcloud.com/server/releases/nextcloud-11.0.4.tar.bz2  or https://download.nextcloud.com/server/releases/nextcloud-11.0.4.zip
2. Open downloaded archive and extract file /nextcloud/core/skeleton/Nextcloud Manual.pdf
3. Open extracted pdf file

### Expected behaviour
Pdf should contain Nextcloud User Manual Release 11

### Actual behaviour
Pdf contains Nextcloud User Manual Release 12

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by LukasReschke** [comment]
Will be fixed in Nextcloud 12 and newer. As this is a minor issue I'm not going to adjust the release script for older releases and risk potential breakage.

Thanks for the report.
