### ISSUE TITLE
Slow loading of NextCloud 12.0.1

### ISSUE THREAD

**Issue by Rouzax** [nextcloud/server#6083]
### Steps to reproduce
1. Install fresh NC instance with new DB
2. Go to the logon page

http://i.imgur.com/Jgdgjny.gif

### General server configuration

**Operating system:** Linux 2.6.32-673.26.1.lve1.4.27.el6.x86_64 #1 SMP Sun May 7 19:22:54 EDT 2017 x86_64

**Web server:** Apache (cgi-fcgi)

**Database:** mysql 10.0.31

**PHP version:** 7.1.7
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - sqlite3
 - zlib
 - bz2
 - calendar
 - ctype
 - curl
 - hash
 - filter
 - ftp
 - gettext
 - gmp
 - SPL
 - iconv
 - pcntl
 - readline
 - Reflection
 - session
 - standard
 - shmop
 - SimpleXML
 - mbstring
 - tokenizer
 - xml
 - cgi-fcgi
 - apcu
 - imagick
 - mysqli
 - Phar
 - bcmath
 - imap
 - mysqlnd
 - posix
 - tidy
 - dom
 - json
 - fileinfo
 - gd
 - PDO
 - soap
 - xmlreader
 - sockets
 - xmlrpc
 - exif
 - pdo_mysql
 - xmlwriter
 - mcrypt
 - xsl
 - memcached
 - pdo_sqlite
 - zip
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.1 - 12.0.1.5

**Updated from an older Nextcloud/ownCloud or fresh install:
Fresh install as well as old Ownlcloud instance

**Where did you install Nextcloud from:
Zip file from Nextcloud.com

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** yes but also without

**Are you using an external user-backend, if yes which one:
No
<details>
        <summary>No errors have been found.</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - bruteforcesettings: 1.0.2
 - comments: 1.2.0
 - dav: 1.3.0
 - encryption: 1.6.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_audit
 - files_external
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "ocff4pqhq5es",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.mgdn.nl",
        "www.cloud.mgdn.nl"
    ],
    "datadirectory": "\/home\/mgdn\/public_html\/_clouddata",
    "overwrite.cli.url": "http:\/\/cloud.mgdn.nl",
    "dbtype": "mysql",
    "version": "12.0.1.5",
    "dbname": "mgdn_cloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_from_address": "info",
    "mail_smtpmode": "php",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "cloud.mgdn.nl"
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Operating system:** Windows 10

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Empty log file
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Schmuuu** [comment]
Hi,

It looks like you're not using any caching. Caching improves the performance of NC drastically. Please have a look at the Admin Guide:
https://docs.nextcloud.com/server/12/admin_manual/configuration_server/server_tuning.html

Especially Redis and Memcache are to topics to look into. Once configured you can define the caching in the nextcloud/config/config.php
like:
```
  'filelocking.enabled' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '/var/lib/redis/redis.sock',
    'port' => 0,
    'timeout' => 0,
    'dbindex' => 0,
  ),
```
Filelocking is not really caching, but while it is enabled by default and puts a lot load on the Database it is highly suggested to use Caching with APCu or Redis as well.

**Comment by Rouzax** [comment]
I'm running on a shared hosting and don't have Redis or memcache

**Comment by aronovgj** [comment]
Try this

https://github.com/nextcloud/server/issues/2272#issuecomment-303319082

**Comment by Rouzax** [comment]
Will I still be able to update to new versions with that patch?

**Comment by aronovgj** [comment]
As I said in the issue below you will have to remove the patch file, update and then reapply the patch.

**Comment by Rouzax** [comment]
It seems to ba a bit faster, will do some more testing over the coming days to evaluate.
Thanks for your help.

**Comment by MorrisJobke** [comment]
For setup issues please ask for help in the forums: https://help.nextcloud.com we also list a wide variety of steps to increase performance in our documentation. Thanks
