### ISSUE TITLE
Upgrading to 12.0.1 vanishes onlyoffice option from the dropdown and memcache.local gives blank pages

### ISSUE THREAD

**Issue by zenny** [nextcloud/server#6086]
Hi,

$1 After upgrading to 12.0.1, the onlyoffice drop down option against the related documents that should appear after enabling the onlyoffice plugin vanished.

$2 Enabling memcache.local in config.php outputs blank pages no matter whichever cache server chosen between ACPu and Redis! 

Cheers,
/z

**Comment by zenny** [comment]
No. 2 solved. 

After appending config.php with:

```
'memcache.local'=> '\OC\Memcache\APCu',
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\OC\Memcache\Redis',
   'redis' => 
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0.0,
  ),
```

I have to restart nginx, php-fpm7 and redis server (rc-service <servicename> restart in alpine linux) to make the Issue no. 2 work. 

Two links were extremely helpful:
https://wiki.archlinux.org/index.php/Nextcloud#Some_files_upload.2C_but_give_an_error_.27Integrity_constraint_violation....27
https://help.nextcloud.com/t/nextcloud-und-redis-memcache-local-memcache-locking/1124

**Comment by blizzz** [comment]
One issue per problem, please… about the OnlyOffice thing, I don't really understand what it is about. Whether it's a wrong behaviour in Nc or the app itself. If latter, the bug should be reported against the app, not Nextcloud.

If you get a blank page after configuring redis, typically the configuration is wrong. This includes permission errors as reported. Imho this is also something better discussed on https://help.nextcloud.com.
