### ISSUE TITLE
"Personal Info" update fails

### ISSUE THREAD

**Issue by NightWorx** [nextcloud/server#6087]
When trying to update "personal info", changes are gone after page reload.
changing entries has following effect:
Name -> nothing happens
Email -> confirmation mail sent
Phone, Address, Website, Twitter -> checkmark appears
However, after page reload, all fields are still empty.

a look in DB oc_accounts table shows the JSON structure as following:
`{"displayname":{"value":"","scope":"contacts"},
"address":{"value":"","scope":"private"},
"website":{"value":"https://example.org","scope":"private","verified":"0"},
"email":{"value":example@example.org,"scope":"contacts","verified":"0"},
"avatar":{"scope":"contacts"},"phone":{"value":"","scope":"private"},
"twitter":{"value":"@twitterhandle","scope":"private","verified":"0"}}`

note: email is NOT set in quotes (for whatever reason)
`"value":"example@example.org",`
adding quotes like shown in example above will fix this issue and updating remaining entries works after that.

**Comment by tcitworld** [comment]
Please provide browser and nextcloud logs.
