### ISSUE TITLE
Information about last cronjob no longer shown in admin page ...

### ISSUE THREAD

**Issue by chrissi55** [nextcloud/server#6088]
### Steps to reproduce
1. activate debug mode in loglevel
2. login to my cloud as admin
3. go to the admin pages where usually my information about last cron activity is shown
4. tried to figure out via support forum before
https://help.nextcloud.com/t/cron-information-seems-to-be-hidden/19034/8

### Expected behaviour
![cron_not-missing](https://user-images.githubusercontent.com/22561479/29239750-d04eafd2-7f55-11e7-9a26-1934d1670cd1.jpg)

### Actual behaviour
![cron_missing](https://user-images.githubusercontent.com/22561479/29239754-dce47240-7f55-11e7-99cb-83f8d4a4b4de.jpg)

### Server configuration

**Operating system**: ubuntu-server 17.04 

**Web server:** nginx 1.13.4-1

**Database:** MariaDB 10.1.25

**PHP version:** 7.1.8

**Nextcloud version:** (see Nextcloud admin page) 12.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 12.0.0

**Where did you install Nextcloud from:** source tar.gz via instruction from here
https://www.c-rieger.de/nextcloud-installation-guide/

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
"No errors have been found."
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_downloadactivity: 1.1.1
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - passman: 2.1.4
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - rainloop: 5.0.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.0
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

<?php
$CONFIG = array (
  'instanceid' => 'HIDDEN',
  'passwordsalt' => 'HIDDEN',
  'secret' => 'HIDDEN',
  'trusted_domains' =>
  array (
    0 => 'MY.DOMAIN',
    1 => 'MY.LOCAL.SERVER-IP',
  ),
  'datadirectory' => '/media/cloud/data',
  'overwriteprotocol' => 'https',
  'overwrite.cli.url' => '/',
  'dbtype' => 'mysql',
  'version' => '12.0.1.5',
  'dbname' => 'HIDDEN',
  'dbhost' => '127.0.0.1',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'HIDDEN',
  'dbpassword' => 'HIDDEN',
  'mysql.utf8mb4' => true,
  'htaccess.RewriteBase' => '/',
  'logtimezone' => 'Europe/Berlin',
  'logfile' => '/media/cloud/data/nextcloud.log',
  'log_rotate_size' => 10485760,
  'cron_log' => false,
  'installed' => true,
  'filesystem_check_changes' => 1,
  'quota_include_external_storage' => false,
  'knowledgebaseenabled' => false,
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0.0,
  ),
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_from_address' => 'HIDDEN',
  'mail_domain' => 'MY.DOMAIN',
  'mail_smtphost' => 'HIDDEN',
  'mail_smtpport' => '465',
  'maintenance' => false,
  'integrity.check.disabled' => false,
  'updater.release.channel' => 'stable',
  'enable_previews' => true,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    4 => 'OC\\Preview\\XBitmap',
    5 => 'OC\\Preview\\MarkDown',
    6 => 'OC\\Preview\\MP3',
    7 => 'OC\\Preview\\TXT',
    8 => 'OC\\Preview\\Movie',
  ),
  'loglevel' => 2,
);

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

local (2nd Drive)
WebDAV 

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                                                                  |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                                    |
| hasPagedResultSupport         |                                                                                                                                                                      |
| homeFolderNamingRule          | attr:samaccountname                                                                                                                                                  |
| lastJpegPhotoLookup           | 0                                                                                                                                                                    |
| ldapAgentName                 | MY.LDAP.ADMIN.EMAILADRESS                                                                                                                                                  |
| ldapAgentPassword             | ***                                                                                                                                                                  |
| ldapAttributesForGroupSearch  |                                                                                                                                                                      |
| ldapAttributesForUserSearch   |                                                                                                                                                                      |
| ldapBackupHost                |                                                                                                                                                                      |
| ldapBackupPort                |                                                                                                                                                                      |
| ldapBase                      | dc=MY,dc=DOMAIN                                                                                                                                                     |
| ldapBaseGroups                | dc=MY,dc=DOMAIN                                                                                                                                                     |
| ldapBaseUsers                 | dc=MY,dc=DOMAIN                                                                                                                                                     |
| ldapCacheTTL                  | 600                                                                                                                                                                  |
| ldapConfigurationActive       | 1                                                                                                                                                                    |
| ldapDefaultPPolicyDN          |                                                                                                                                                                      |
| ldapDynamicGroupMemberURL     |                                                                                                                                                                      |
| ldapEmailAttribute            | mail                                                                                                                                                                 |
| ldapExperiencedAdmin          | 0                                                                                                                                                                    |
| ldapExpertUUIDGroupAttr       | cn                                                                                                                                                                   |
| ldapExpertUUIDUserAttr        | cn                                                                                                                                                                   |
| ldapExpertUsernameAttr        | cn                                                                                                                                                                   |
| ldapGidNumber                 | gidNumber                                                                                                                                                            |
| ldapGroupDisplayName          | cn                                                                                                                                                                   |
| ldapGroupFilter               | (&(|(objectclass=group))(|(cn=Domänen-Benutzer)))                                                                                                                    |
| ldapGroupFilterGroups         | Domänen-Benutzer                                                                                                                                                     |
| ldapGroupFilterMode           | 0                                                                                                                                                                    |
| ldapGroupFilterObjectclass    | group                                                                                                                                                                |
| ldapGroupMemberAssocAttr      | member                                                                                                                                                               |
| ldapHost                      | DC.MY.DOMAIN                                                                                                                                                   |
| ldapIgnoreNamingRules         |                                                                                                                                                                      |
| ldapLoginFilter               | (&(&(|(objectclass=user))(|(|(memberof=CN=CLOUDGROUP,CN=Users,DC=MY,DC=DOMAIN)(primaryGroupID=3106))))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                                                                                                      |
| ldapLoginFilterEmail          | 1                                                                                                                                                                    |
| ldapLoginFilterMode           | 0                                                                                                                                                                    |
| ldapLoginFilterUsername       | 1                                                                                                                                                                    |
| ldapNestedGroups              | 0                                                                                                                                                                    |
| ldapOverrideMainServer        |                                                                                                                                                                      |
| ldapPagingSize                | 500                                                                                                                                                                  |
| ldapPort                      | 389                                                                                                                                                                  |
| ldapQuotaAttribute            |                                                                                                                                                                      |
| ldapQuotaDefault              |                                                                                                                                                                      |
| ldapTLS                       | 0                                                                                                                                                                    |
| ldapUserDisplayName           | displayname                                                                                                                                                          |
| ldapUserDisplayName2          |                                                                                                                                                                      |
| ldapUserFilter                | (&(|(objectclass=user))(|(|(memberof=CN=CLOUDGROUP,CN=Users,DC=MY,DC=DOMAIN)(primaryGroupID=3106))))                                                                   |
| ldapUserFilterGroups          | CLOUDGROUP                                                                                                                                                              |
| ldapUserFilterMode            | 0                                                                                                                                                                    |
| ldapUserFilterObjectclass     | user                                                                                                                                                                 |
| ldapUuidGroupAttribute        | auto                                                                                                                                                                 |
| ldapUuidUserAttribute         | auto                                                                                                                                                                 |
| turnOffCertCheck              | 0                                                                                                                                                                    |
| turnOnPasswordChange          | 1                                                                                                                                                                    |
| useMemberOfToDetectMembership | 1                                                                                                                                                                    |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------+

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** Chromium , Edge, SRWare Iron

**Operating system:** ZorinOS 12.1, Windows 10, Linuxmint 18.2

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
Aug 12 09:45:01 MYSERVER CRON[11297]: (www-data) CMD (php -f /var/www/nextcloud/cron.php > /dev/null 2>&1)
Aug 12 10:00:01 MYSERVER CRON[11378]: (www-data) CMD (php -f /var/www/nextcloud/cron.php > /dev/null 2>&1)
Aug 12 10:15:01 MYSERVER CRON[11488]: (www-data) CMD (php -f /var/www/nextcloud/cron.php > /dev/null 2>&1)
Aug 12 10:30:01 MYSERVER CRON[11498]: (www-data) CMD (php -f /var/www/nextcloud/cron.php > /dev/null 2>&1)
Aug 12 10:45:01 MYSERVER CRON[11600]: (www-data) CMD (php -f /var/www/nextcloud/cron.php > /dev/null 2>&1)
Aug 12 11:00:01 MYSERVER CRON[11613]: (www-data) CMD (php -f /var/www/nextcloud/cron.php > /dev/null 2>&1)
Aug 12 11:15:01 MYSERVER CRON[11726]: (www-data) CMD (php -f /var/www/nextcloud/cron.php > /dev/null 2>&1)
Aug 12 11:30:01 MYSERVER CRON[11753]: (www-data) CMD (php -f /var/www/nextcloud/cron.php > /dev/null 2>&1)
Aug 12 11:45:01 MYSERVER CRON[11846]: (www-data) CMD (php -f /var/www/nextcloud/cron.php > /dev/null 2>&1)
Aug 12 12:00:01 MYSERVER CRON[11870]: (www-data) CMD (php -f /var/www/nextcloud/cron.php > /dev/null 2>&1)
Aug 12 12:15:01 MYSERVER CRON[12349]: (www-data) CMD (php -f /var/www/nextcloud/cron.php > /dev/null 2>&1)
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
</details>

Debug	cron	Run OCA\User_LDAP\Jobs\UpdateGroups job with ID 236	2017-08-08T07:00:01+0200
Debug	cron	Finished OC\Authentication\Token\DefaultTokenCleanupJob job with ID 234 in 0 seconds	2017-08-08T07:00:01+0200
Debug	cron	Invalidating remembered session tokens older than 2017-07-24T05:00:01+00:00	2017-08-08T07:00:01+0200
Debug	cron	Invalidating session tokens older than 2017-08-07T05:00:01+00:00	2017-08-08T07:00:01+0200
Debug	cron	Run OC\Authentication\Token\DefaultTokenCleanupJob job with ID 234	2017-08-08T07:00:01+0200
Debug	cron	Finished OCA\UpdateNotification\ResetTokenBackgroundJob job with ID 221 in 0 seconds	2017-08-08T07:00:01+0200
Debug	cron	Run OCA\UpdateNotification\ResetTokenBackgroundJob job with ID 221	2017-08-08T07:00:01+0200
Debug	cron	Finished OC\Log\Rotate job with ID 310 in 0 seconds	2017-08-08T07:00:01+0200
Debug	cron	Run OC\Log\Rotate job with ID 310	2017-08-08T07:00:01+0200
Debug	cron	Finished OCA\Passman\BackgroundJob\ExpireCredentials job with ID 281 in 0 seconds	2017-08-08T07:00:01+0200
Debug	cron	Run OCA\Passman\BackgroundJob\ExpireCredentials job with ID 281	2017-08-08T07:00:01+0200
Debug	cron	Finished OCA\Files\BackgroundJob\CleanupFileLocks job with ID 7 in 0 seconds	2017-08-08T07:00:01+0200
Debug	cron	Run OCA\Files\BackgroundJob\CleanupFileLocks job with ID 7	2017-08-08T07:00:01+0200
Debug	cron	Finished OCA\Files\BackgroundJob\ScanFiles job with ID 5 in 0 seconds	2017-08-08T07:00:01+0200
Cronjob of 7:00 at 8/8/2017 so that fits to my settings crontab => every 15 min
Debug	core	Scss is disabled for /var/www/nextcloud/core/css/share.scss, ignoring	2017-08-08T07:05:25+0200
Debug	core	Scss is disabled for /var/www/nextcloud/core/css/server.scss, ignoring	2017-08-08T07:05:25+0200

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
> 'cron_log' => false,

If this is set to false it will not log info about successful cron runs. I don't properly know why this setting exist at all, but this is the reason it is not shown in your instance. Remove that line and it should show up again.

Let me look into this.

**Comment by MorrisJobke** [comment]
See #6158 for an improvement on this.
