### ISSUE TITLE
Cant delete Folder

### ISSUE THREAD

**Issue by Tealk** [nextcloud/server#6092]
### Steps to reproduce
Delete a Folder

### Expected behaviour
The folder sould get deleted

### Actual behaviour
Error: "Cant delete Folder"

{"reqId":"028LR2NMwWk4MFOJYQXQ","level":4,"time":"12.08.17 23:41:10","remoteAddr":"79.200.70.45","user":"Tealk","app":"webdav","method":"MKCOL","url":"\/remote.php\/webdav\/Pen%20and%20Paper\/P%26P%20Chars\/Tealk\/Free%20Fate","message":"Exception: {\"Message\":\"HTTP\\\/1.1 409 Parent node does not exist\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\Conflict\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(590): Sabre\\\\DAV\\\\Server->createCollection('Pen and Paper\\\/P...', Object(Sabre\\\\DAV\\\\MkCol))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(71): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/nextcl...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1166,\"User\":\"Tealk\"}","userAgent":"--","version":"12.0.0.29"}

### General server configuration

**Operating system:** Linux Anzah-Cloud 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64

**Web server:** Apache/2.4.10 (Debian) (apache2handler)

**Database:** mysql 5.7.19

**PHP version:** 7.1.8-2+0~20170804100723.7+jessie~1.gbpae7f04
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - apache2handler
 - mysqlnd
 - PDO
 - xml
 - apcu
 - apc
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - geoip
 - gettext
 - iconv
 - igbinary
 - intl
 - json
 - exif
 - mcrypt
 - msgpack
 - mysqli
 - pdo_mysql
 - Phar
 - posix
 - readline
 - shmop
 - SimpleXML
 - sockets
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - memcached
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:** YOUR ANSWER HERE

**Where did you install Nextcloud from:**  YOUR ANSWER HERE

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** YOUR ANSWER HERE (LDAP/ActiveDirectory/Webdav/...)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - admin_notifications: 1.0.0
 - apporder: 0.4.0
 - bookmarks: 0.10.1
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - encryption: 1.6.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_downloadactivity: 1.1.1
 - files_pdfviewer: 1.1.1
 - files_reader: 1.0.4
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - groupfolders: 1.1.0
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.6.4
 - news: 11.0.5
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - quota_warning: 1.0.1
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_email: 1.0.1
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.0
 - twofactor_u2f: 1.3.2
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - deck
 - files_external
 - gallery
 - keeweb
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "ocz6kekhpjaq",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "anzah.cloud"
    ],
    "datadirectory": "\/home\/anzahcloud",
    "overwrite.cli.url": "https:\/\/anzah.cloud",
    "dbtype": "mysql",
    "version": "12.0.0.29",
    "dbname": "anzahcloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Berlin",
    "installed": true,
    "forcessl": true,
    "asset-pipeline.enabled": true,
    "theme": "",
    "log_type": "owncloud",
    "logfile": "\/home\/anzahcloud\/nextcloud.log",
    "loglevel": 2,
    "syslog_tag": "ownCloud",
    "logdateformat": "d.m.y H:i:s",
    "log_query": false,
    "cron_log": true,
    "log_rotate_size": 104857600,
    "versions_retention_obligation": "auto, 120",
    "trashbin_retention_obligation": "auto, 60",
    "mail_from_address": "noreply",
    "mail_smtpmode": "smtp",
    "mail_domain": "anzahcraft.de",
    "maintenance": false,
    "updatechecker": false,
    "appstore.experimental.enabled": true,
    "enable_previews": true,
    "preview_max_x": 2048,
    "preview_max_y": 2048,
    "preview_max_filesize_image": 50,
    "preview_max_scale_factor": 10,
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore -convert-to pdf -outdir ",
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\PDF"
    ],
    "memcache.local": "\\OC\\Memcache\\APCu",
    "blacklisted_files": [
        ".htaccess"
    ],
    "minimum.supported.desktop.version": "2.2.2",
    "assetdirectory": "\/var\/www\/nextcloud",
    "activity_expire_days": 365,
    "htaccess.RewriteBase": "\/",
    "mail_smtpauth": 1,
    "mail_smtphost": "s95.goserver.host",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "singleuser": false,
    "mysql.utf8mb4": true
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.91 Safari/537.36 Vivaldi/1.92.917.39

**Operating system:** YOUR ANSWER HERE

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
cc @icewind1991 @rullzer

**Comment by skjnldsv** [comment]
I never seen this one anywhere else.
My guess is a weird upgrade or a failed deletion somehow.
Scanning the files with occ files:scan should recheck everything.
If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
