### ISSUE TITLE
Upgrade to 12.0.1 - Not enough disc space

### ISSUE THREAD

**Issue by florianrusch** [nextcloud/server#6096]
### Steps to reproduce
1. Try to upgrade from 12.0 to 12.0.1 at an environment with not enough disc space.

### Expected behavior
I would expect that there comes an error message.

### Actual behavior
At the gui updater, I got some kind of curl error message. (Sorry, I didn't test any further)
With the CLI updater, I've got the message below. The updater ignored the warning and just went to the next step.
<kbd>
![image](https://user-images.githubusercontent.com/1724759/29253647-3b744b5e-8083-11e7-8c04-7b639da88e41.png)</kbd>

### Short explanation
We are using NC as a WebUI for our SMB-Shares. So the users got from us a quota from <10MB. The whole `var` folder on our system lays on an extra partition with just 2.8 GB space.
So when there are some bigger log files and also some backups from NC them self, then is there not enough disc space to backup the NC instance, download the new version and extract it.

We could handle the problem with some log cleanup. But it would maybe be an improvement if the updated could handle this type of problems.

### Server configuration

**Operating system**: Debian Stretch
**Web server:** Nginx
**Database:** MySQL
**PHP version:** 5.6.30
**Nextcloud version:** 12.0 -> 12.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 12.0 to 12.0.1

**Where did you install Nextcloud from:** Web
**Are you using external storage, if yes which one:** SMB
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** LDAP

**Comment by MorrisJobke** [comment]
Moved to the updater repo: https://github.com/nextcloud/updater/issues/154
