### ISSUE TITLE
Users uploading large files to my Nextcloud instance through the web interface are getting a "Locked" error message and their upload does not complete.

### ISSUE THREAD

**Issue by pgauret** [nextcloud/server#6107]
### Steps to reproduce
1. Log in the NC web interface
2. Upload a file that will take more than a couple of hours to upload (e.g. over 600 MB on a 1Mbit/s uplink)

### Expected behaviour
Upload starts, progress counter works. File is successfuly uploaded.

### Actual behaviour
Upload starts, progress counter works. After a while getting a "Locked" message in the browser window (screenshot attached). File is not successfuly uploaded.

I've applied documented settings for large files. Doing a little testing shows that the issue is triggered by the DURATION the files takes to upload rather than by its size. The issue appears if an upload is taking more than a couple of hours. The same client uploading the same file works flawlessly using a network link with fast upload (e.g. 40Mbit/s fibre)

Things I've tried without success:

- Fiddling around with php.ini values. Currently using:

upload_max_filesize 40000M
post_max_size 40000M
max_input_time 30000
max_execution_time 30000 
gc_maxlifetime 30000
session.gc_maxlifetime = 30000
opcache.enable=1
opcache.enable_cli=1
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=10000
opcache.memory_consumption=128
opcache.save_comments=1
opcache.revalidate_freq=1

- Switching to Redis for locking 

- Upgrading from NC 11 to NC 12

- Trying other OS / browser combinations (Safari, IE, Chrome, Windows, OSX ...)

- Using a webdav client (CarotDAV) to upload

The NC instance is behind an Apache reverse proxy terminating SSL, using the following rules for Nextcloud:

      ProxyPass /nextcloud  http://nextcloud/nextcloud
      ProxyPassReverse /nextcloud  http://nextcloud/nextcloud
      
      
Could not find any relevant error messages in the logs. 
 
I'm running out of ideas here. Happy to troubleshoot further / run any tests if needed.

Server information details

### General server configuration

**Operating system:** Linux vm8 4.10.0-26-generic #30-Ubuntu SMP Tue Jun 27 09:30:12 UTC 2017 x86_64

**Web server:** Apache/2.4.25 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.19

**PHP version:** 7.0.22-0ubuntu0.17.04.1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - apache2handler
 - mysqlnd
 - PDO
 - xml
 - apcu
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - iconv
 - igbinary
 - json
 - ldap
 - exif
 - mysqli
 - pdo_mysql
 - Phar
 - posix
 - readline
 - redis
 - shmop
 - SimpleXML
 - sockets
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install: FRESH INSTALL

**Where did you install Nextcloud from:**  Downloaded release

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one: LDAP (OpenLDAP

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - calendar: 1.5.3
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.6.4
 - news: 11.0.5
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - user_ldap: 1.2.1
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_audit
 - encryption
 - files_external
 - survey_client
 - user_external
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "xxxxxxx",
    "overwriteprotocol": "https",
    "htaccess.RewriteBase": "\/nextcloud",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "www.xxxxxxxxx.net"
    ],
    "datadirectory": "\/data\/nextcloud",
    "overwrite.cli.url": "https:\/\/www.xxxx.net\/nextcloud",
    "dbtype": "mysql",
    "dbname": "nextcloud",
    "dbhost": "db.xxxx.net",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "version": "12.0.0.29",
    "mysql.utf8mb4": true,
    "filelocking.enabled": true,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "localhost",
        "port": 6379,
        "timeout": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

<details>
        <summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36

**Operating system:** YOUR ANSWER HERE

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>
<img width="1383" alt="nc screenshot" src="https://user-images.githubusercontent.com/5214927/29279221-7972cacc-8117-11e7-8853-b8afb14d697d.png">

**Comment by LukasReschke** [comment]
cc @icewind1991

**Comment by NiTRoeSE** [comment]
Any news about this ? I run in the same problem, big files > 8GB are always locked so that a upload of such files fails.

**Comment by pgauret** [comment]
Issue disappeared with upgrade to NC13 beta. Closing.

**Comment by nick4fake** [comment]
Issue is still there :(
