### ISSUE TITLE
Can't use upgrade app to move from 11.0.4 to 12.0.1

### ISSUE THREAD

**Issue by J-A-M** [nextcloud/server#6109]
The index for upgrade paths in 11.0.4 is missing 12.0.1 as an option, even though 12.0.0 entered a stable state in May (it's August now) and 12.0.1 more recently.
12.x is listed as the latest production release on Nextcloud website.
Upgrader app docs say it handles upgrade paths to 12 but this does not seem to be the case.

The only 12.x stream offered is 12.0.2 beta - which is is not what I would like to role out.

Will an upgrade to 11.0.5 (beta) have a 12.0.1 (stable) option?

I know a work round would be to do a manual install.

Perhaps there should be a 'platform' channel as well as a 'stable' channel?

### Steps to reproduce (starting at 11.0.4)
1. Menu - Admin -> Upgrade
2. Select upgrade channel (see below)
3.

### Expected behaviour
Should list latest stable and/or production release (12.0.1 at time of writing)

### Actual behaviour
Beta - 12.0.2
Daily - 11.0.4 daily
Stable - No updates available
Production - 11.0.4 production

### Server configuration

**Operating system**:
Linux / Ubuntu 16.04.2
**Web server:**
Apache 2.4
**Database:**
MYSQL
**PHP version:**
7.0.22
**Nextcloud version:** (see Nextcloud admin page)
11.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgraded from 11.0.3
**Where did you install Nextcloud from:**
Nextcloud
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Integrity checker has been disabled. Integrity cannot be verified.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - encryption: 1.4.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_accesscontrol: 1.1.2
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.2
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - external
  - files_automatedtagging
  - files_retention
  - templateeditor
  - user_external
  - user_saml

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

{
    "system": {
        "instanceid": "oc6mbqioegls",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.8"
        ],
        "datadirectory": "\/mnt\/data\/nextcloud",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "overwrite.cli.url": "http:\/\/192.168.1.8\/nextcloud",
        "dbtype": "mysql",
        "version": "11.0.4.1",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "loglevel": 2,
        "updater.release.channel": "production",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
> Will an upgrade to 11.0.5 (beta) have a 12.0.1 (stable) option?

We are not 100% sure, if the update works fine in all scenarios so we disabled the updater for now until we are really sure, that it will not cause problems. Especially since a few users reported some hiccups. As of now you need to run the manual step update if you want to go to 12.0.2. For 11.0.3 to 11.0.4 the updater should work fine as well as for 12.0.0/1 to 12.0.2. Only the update path of 11 -> 12 was disabled for now.
