### ISSUE TITLE
S3 won't connect as external storage

### ISSUE THREAD

**Issue by declanmarks** [nextcloud/server#6113]
I am trying to connect my Amazon S3 to my Nextcloud instance but I keep getting errors. It suggests that your are not using the latest authentication method.

These are the errors I keep receiving.

Error | files_external | Exception: Creation of bucket failed. The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. | 2017-08-10T13:09:53+0100
-- | -- | -- | --
Error | files_external | Aws\S3\Exception\InvalidRequestException: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256. | 2017-08-10T13:09:53+0100

Nextcloud version: 12.0.2

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by forever-sumit** [comment]
Hi,
I'm also getting the same issue. My bucket is in "US East (Ohio)" region

**Comment by heyiswas** [comment]
Same here in version 12.0.2. I'm using EU Frankfurt as region, which only supports V4 of the authorization mechanism. See also: https://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4#26538266

**Comment by icewind1991** [comment]
There is an open PR for updating the s3 library which should fix this: https://github.com/nextcloud/server/pull/4410

Please help by testing out the PR

**Comment by MorrisJobke** [comment]
Fixed via #4410
