### ISSUE TITLE
Add link to Changelog in update notification section

### ISSUE THREAD

**Issue by MegaV0lt** [nextcloud/server#6117]
### Steps to reproduce
1. Go to the updater when there is a new version

### Expected behaviour
Ther should be an extra link to the changelog of the new version

### Actual behaviour
No changelog on the updater

![auswahl_20170815_09 38 06](https://user-images.githubusercontent.com/2804301/29307220-444639bc-81a1-11e7-84c6-36360952803c.png)

**Comment by MorrisJobke** [comment]
This should be shown one step earlier in the update notification app. see also nextcloud/updater#61

cc @nickvergessen

**Comment by d3xt3r1232** [comment]
Hello, can I take this one?

**Comment by MorrisJobke** [comment]
> Hello, can I take this one?

Sure - the link should be in the request from the server.

**Comment by MorrisJobke** [comment]
Looks like you need to adjust https://github.com/nextcloud/updater/blob/master/index.php#L233-L255

**Comment by d3xt3r1232** [comment]
@MorrisJobke Thank you for claryfying the problem :)

**Comment by violoncelloch** [comment]
@MorrisJobke 
Does the updater server present a changelog we could link to?
Or should we just link to `https://nextcloud.com/changelog/` or to the specific part like `https://nextcloud.com/changelog/#14-0-3`?

**Comment by MorrisJobke** [comment]
> @MorrisJobke
> Does the updater server present a changelog we could link to?
> Or should we just link to `https://nextcloud.com/changelog/` or to the specific part like `https://nextcloud.com/changelog/#14-0-3`?

There is none shipped in the response. So I guess the only way is to generate the link like you described.

**Comment by nickvergessen** [comment]
That also makes more sense, because we don't ship future changelogs *hint hint* xD
