### ISSUE TITLE
Libreoffice / Collabora office in Docker Container

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/server#613]
i say it very easy ..

Dockercontainer it is a crap and i want not use, i bet, 
a couple of users want it also not, in "own/NextCloud"
from an couple of sides is a docker this container imposed, constrained /forced
and this is not okey ..
or hey, why do you not nextcoud in an docker container ?
why do you not Libreoffice give as a real plugin for the cloud.

"you want use Libreoffice, you have take the docker .."

bah this docker is crap !

best regards
Blacky

**Comment by MorrisJobke** [comment]
Currently docker is the only from our perspective useful way to set it up easily. The docker container uses the official LibreOffice source code and compiles it into the binary. We don't want to build the packages for all the linux distros out there (and we also don't have the man power to do so). Beside that you could compile it yourself or pay Collabora to do so for you. 

@blackcrack And BTW: It's not fair, that we do the work and you simply complain that we don't do even more work, because we did this for free before and could do even more work for free.

I will close this here as I pointed out what other ways could be taken to get a working LibreOffice setup..

**Comment by blackcrack** [comment]
Hi morris :)

it's not a thing of fairness, it's a thing of usablety  or like i can say it.. 
an pointing out on/of it .
some persons don't understand how works docker and makes more work as an 
starter of Nextcloud who build up his own server and dont know how docker works..

so why do it not works with a tar.gz, extracting in the Apps folder or more easy, download
with the Pluginmanager and let decompress into the apps folder, so, why not in this way..

And okey, you are the programmer , but i am one of the Users who use this, so, you 
can programming many, but if it is use from the normally users.. so have the normally users nothing from it, Administrators who work every day with it, they know how it work but the normal user who easy need to it get in a really easy way..

this docker move it in an other level , an level who it mus be know more as just, installing and using, this makes to a level for Administrators where supports everyday and working every day
with Infrastructures .. it is this docker an dollop .. but for they are who not everyday
working with Servers it is this more hard to understand how this works and need the real
pluginsolution .

So you can complain you how little I would appreciate your work,
but this i don't do Morris, you should see the other thing.. behind of it.
I have view the many commits and postings, via github -> mail,
you have done a huuuge work and really damn good work with the whole changes on NextCloud !

But.. the docker .. it is not good ! Also if it have Libreoffice code on it..
and makes therewith also not better .. Docker is docker.. 
you know .. so, not agro agains, also not trolling against,
i am pointing out  it  only !

so, why do it not works as an tar.gz packet ?
installing locally libre office and use it via cloud plugin.
or a fully implementation packet as html5 and java .  
And this later works also anywhere .. maybe..

best regards
Blacky

**Comment by MorrisJobke** [comment]
> so why do it not works with a tar.gz, extracting in the Apps folder or more easy, download
> with the Pluginmanager and let decompress into the apps folder, so, why not in this way..

Because it's not that simple to run a compiler and install all the dependencies in the correct version and fire up a binary to listen on a given port.


It's not that simple as you think with "download and run" ... there is more behind it and to manage all of this Docker was the tool of choice. We don't have the time and man power to do it in another way for now.

**Comment by MorrisJobke** [comment]
> installing locally libre office and use it via cloud plugin.
> or a fully implementation packet as html5 and java .

That's not how software deployment work. You don't throw in the Tech Stack you want to run it on, but you need to use the Tech Stack it is programmed in. You could try to run this in a JRE, but this won't work, because this is not a Java application.

**Comment by blackcrack** [comment]
Thank you for the explanation, but must or, should work in a more easy way for easy
implementing in - cloud.. and not directly in an "extra" program , this case it is coming as the Extra DB server was developement .. mysql befor was work with textdb on the webserver, now exist for it sqlite, the orginal programmers have now build up mariadb .. and so on.. i know, it's developement ever more and huge, but we should look for hold at all easy and not so complicate, because more complicated more space for injection and other things .. hmmm.... and thus throwing more and more shadow for dark things .. so, 
it mus give a possible for hold this more easy.. and also more easy handle for the users who want include the online version of Libre office .. in any way..  .. :)

best regards
Blacky

**Comment by MorrisJobke** [comment]
> it must give a possible for hold this more easy.. and also more easy handle for the users who want include the online version of Libre office .. in any way.. .. :)

You can also browse the internet in a text based browser totally fine, but then you also should not complain that there aren't no videos or images. Sometimes a bigger tech stack is needed to accomplish the stuff you want to do. And LibreOffice Online is a bit more than a static web server can serve.

**Comment by jospoortvliet** [comment]
@blackcrack the source code is on the web: https://github.com/LibreOffice/online

feel free to grab the pieces and create packages or a nice tarball that works.

**Comment by blackcrack** [comment]
well, and therefore a own Project, for also makes possible with lynx, w3m and co
creating also otd and using libreoffice, but how many want include videos and pictures 
in a document if they want only write plain textfiles or only based letters in otd 
and whant it save, the Videos and pictures it is of course more effort due ..
this is clear :) .. so why then start with the bigger things and not start with a small like "documents" and build more and more up .. hey, with the whole plugins in Apache it's possible to handle really many but then it is dependent in apache and webservers with plugins.
Well.. but it should work .. but i have not the experience for build up some Project and i am can not programming.. this is also some thing, i am to old for starting it.. and i have my own space where i am jump around :) collecting programs (now only OpenSource and freeware, it's give enough;)  now.. ) and something like Doublecommander, Totalcommander.. Reactos and so on.. so ..i keep stay in the "do not programing" part and be only a extended User :) with a Openmandriva Server on the basement ;) 

And by the way, we have today x86_64 mashins and the Server be in able to do 
more as in the past day's ;)

So, why not 3-6 programms as Webapplications where be collecting in an Office Suite.
So, an Writer, Calc and other Webaplications as a Officesuite
it should be in able Via Browser to working, creating/changing and saving different documents
where it is highest compatible to Libre Office Program/OfficeSuite but as Webapplication as Officesuite for all and open Source .. and this.. binding in in - cloude ..

(on writing this , have Jospoortvliet cmment it .. : 1. i am not a programmer, 2. i going in the next time making money.. again and have no more time for it.. i was more as 13-16 years workless.. but now want i make a bit money ang have no more the time for invest this into the web.. i have helped to build this up in the past times 0X, but now should i look for have a bit money ;) i can give ideas, suggestion now for make it or many better but more today not .. pity but i should do for me self now too a little bit :) so, less time for the web.. )

best regards
Blacky

**Comment by MorrisJobke** [comment]
> well, and therefore a own Project, for also makes possible with lynx, w3m and co
> creating also otd and using libreoffice, but how many want include videos and pictures 
> in a document if they want only write plain textfiles or only based letters in otd 
> and whant it save, the Videos and pictures it is of course more effort due ..
> this is clear :) .. so why then start with the bigger things and not start with a small like "documents" and build more and more up .. hey, with the whole plugins in Apache it's possible to handle really many but then it is dependent in apache and webservers with plugins.

This was not about including videos into a document but about the same problems. You want to have something that works better and makes your life easier, but don't want to use higher level software stack. It is currently simply not possible to provide it in another way.

> So, why not 3-6 programms as Webapplications where be collecting in an Office Suite.
> So, an Writer, Calc and other Webaplications as a Officesuite

Because it is not that easy as you think. Yes it is only text, but it needs to be rendered in the exact same way on all platforms ...

End of discussion here. We will not provide something different for now.
