### ISSUE TITLE
 Big profile picture slowdown login

### ISSUE THREAD

**Issue by DOWAIZA** [nextcloud/server#6133]
Hello,
I have recognized a behavior with the profile pictures. If a user sets a profile picture, it doesn’t matter if the picture is uploaded or picket up from the files app, the login will be slowdown, if the picture is too large. I have tested this behavior with a 8,5MB picture, the login will take round about 55 seconds. This seems to be too long for the latest windows Nextcloud client, the authentication is not possible, I guess there is a timeout. If I use a picture around 300KB the login take not perceptible longer then without a profile picture. Further tests have shown that this behavior only occurs with LDAP users.
Is there a way to change the maximal picture size from 20MB to a more appropriate size?
Another thing I have tried to bypass this problem by setting this option in the config.php:
“‘enable_avatars’ => false,”
But the users a still able to set and change their profile picture.

Tanks for the Help!
Best,

**Comment by MorrisJobke** [comment]
> Another thing I have tried to bypass this problem by setting this option in the config.php:
> “‘enable_avatars’ => false,”
> But the users a still able to set and change their profile picture.

This is not available anymore as setting.

Let me check on the profile picture size. What request takes that long? Is it the PROPFIND against the WebDAV API?

**Comment by DOWAIZA** [comment]
I don´t know which request takes that long. At the website login with a browser it stuck at the “Login” screen. With the windows desktop client it stuck at the authentication window.

**Comment by nickvergessen** [comment]
For me the login works quite well.
Can you check your nextcloud.log file as well as your servers error log?

**Comment by MorrisJobke** [comment]
I'm closing this due to the lack of information. We will reopen once the information is available.

What would help is the information that is listed in the network tab of the web developer tools in your browser. Open them and then load the page. You will see a lot of requests and their duration. Check which one takes the longest.
