### ISSUE TITLE
Does not automaticaly upgrade if a second app directory is present

### ISSUE THREAD

**Issue by freeeflyer** [nextcloud/server#6135]
### Steps to reproduce
1. read the documentation
2. move non core app to a second directory (app2/ in my case)
3. try to update

### Expected behaviour
Should update the server
### Actual behaviour
says apps2 directory is present and does not update

### Server configuration

**Operating system**:
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
**Web server:**
apache2                            2.4.7-1ubuntu4.16
**Database:**
postgresql-9.1                     9.1.14-0ubuntu0.12.04

**PHP version:**
libapache2-mod-php7.0              7.0.21-1~ubuntu14.04.1+deb.sury.org+1

**Nextcloud version:** (see Nextcloud admin page)
12.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated since at least Owncloud 7

**Where did you install Nextcloud from:**
wget ... owncloud-xx.xx.zip 
+ Documentation

**Comment by LukasReschke** [comment]
The updater included in 12.0.1 ignores custom apps folders as per https://github.com/nextcloud/updater/pull/130. This means for future updates you should not receive this warning.

**Comment by freeeflyer** [comment]
Cool. thanks

**Comment by freeeflyer** [comment]
It seems that it's not the case ..
![2017-09-25 11_50_29-https___cloud xoop org_index php_settings_admin - iron](https://user-images.githubusercontent.com/12149490/30802859-159256f2-a1e8-11e7-8ffd-70909338f278.png)
