### ISSUE TITLE
stat(): SSL operation failed with code 1. 

### ISSUE THREAD

**Issue by dylib** [nextcloud/server#6137]
### Steps to reproduce
1. Add external storage with FTP with TLS/SSL

### Expected behaviour
External storage should connect with FTP with TLS/SSL

### Actual behaviour
Nextcloud cannot connect with FTP with TLS/SSL

### Server configuration

**Operating system**:
centos-release-7-3.1611.el7.centos.x86_64

**PHP version:**
7.0.21

**Nextcloud version:** (see Nextcloud admin page)
12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
--

**Where did you install Nextcloud from:**
Github repo

**Are you using external storage, if yes which one:** local/smb/sftp/...
I would like to...
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

**Operating system:**
Linux ns3145166.ip-87-98-216.eu 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here

Error | PHP | stat():  stat failed for ftps://xxx:xxx@foobar.com:2222/ at  /var/www/vhosts/website/httpsdocs/nextcloud/apps/files_external/lib/Lib/Storage/StreamWrapper.php#127 | 2017-08-14T19:09:26-0700
-- | -- | -- | --
Error | PHP | stat():  SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate  verify failed at  /var/www/vhosts/website/httpsdocs/nextcloud/apps/files_external/lib/Lib/Storage/StreamWrapper.php#127
```
</details>

**Comment by tflidd** [comment]
> SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

Do you use an official certificate at your FTP server?

**Comment by dylib** [comment]
@tflidd: Which FTP server are you meaning? The external FTP does not use and SSL certificate as far as I know, and the one on the NextCloud server is a valid letsencrypt cert.

**Comment by MorrisJobke** [comment]
> SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

This looks like the certificate is wrong or invalid. Please check the forums for help. Check also your PHP that it uses the system certificates to verify SSL certs so that the let's encrypt cert can be properly verified. We only use the stuff that PHP knows.

See https://github.com/nextcloud/server/blob/master/apps/files_external/lib/Lib/Storage/FTP.php#L115
