### ISSUE TITLE
ugrade from 12.0.1 to 12.0.2 failed

### ISSUE THREAD

**Issue by cpu2910** [nextcloud/server#6140]
1. Started web-update from 12.0.1 to 12.0.2
2. The update said: Failed

Error | updater | \OC\Updater::failure: notifications: Failed to enable app notifications | 2017-08-15T22:13:33+0200
-- | -- | -- | --
Error | notifications | OC\HintException: Failed to enable app notifications/var/www/owncloud/lib/private/Installer.php - line 501:  OC\Installer  installShippedApp('notifications')/var/www/owncloud/lib/private/Updater.php - line 272:  OC\Installer  installShippedApps(true)/var/www/owncloud/lib/private/Updater.php - line 130:  OC\Updater->doUpgrade('12.0.2.0', '12.0.1.5')/var/www/owncloud/core/ajax/update.php - line 206:  OC\Updater->upgrade(){main}

The app 'notifications' wasn't active before the update, neither is it after the update

Despite of this message everything seems to work fine.

### Server configuration
debian 9 stretch

Apache 2.4.25

Maria-DB 10.1.23

PHP 7.0.22

12.0.2 (after the update)
Updated from 12.0.1.5

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.

**List of activated apps:**
sudo -u www-data php occ app:list
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - qownnotesapi: 17.5.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_trashbin
  - files_versions
  - notifications
  - user_external
  - user_ldap

**Comment by Lstt2005** [comment]
I support. The same problem...Ubuntu 16.04.3 Nextcloud 12.0.1-12.0.2

**Comment by LukasReschke** [comment]
@nickvergessen Any ideas?

**Comment by cpu2910** [comment]
Is it possible to clone this issue?
I just updated from 12.0.2 to 12.03.
same environment and same error as before.

**Comment by danielkesselberg** [comment]
https://github.com/nextcloud/server/issues/11648#issuecomment-431148222
