### ISSUE TITLE
No release announcements for minor releases

### ISSUE THREAD

**Issue by michaellass** [nextcloud/server#6142]
Since registering to the release announcement newsletter, at least two minor versions (12.0.1, 12.0.2) were released without any notice. Also, Nextcloud itself did not send out emails when new versions were released although the corresponding group was set up to get emails for new releases. Using the test functionality in the admin panel shows that sending emails works perfectly in principle.

### Steps to reproduce
1. Register for the release announcements newsletter
2. Setup Nextcloud so that certain users get an email on new versions
3. Receive no information about new releases whatsoever, from neither of those two sources

### Expected behavior
There needs to be some way of being informed about new releases. Either Nextcloud itself should inform the administrator about new releases or the release announcement list should work reliably. Actually, both of these options should work reliably.

### Actual behavior
I'm registered since 13.06.2017 for the announcement list and never received any email. Also, the Nextcloud installation did not send out any emails regarding new releases.

I removed all remaining parts of the bug template since they seem to be irrelevant to this issue. I'll be glad to provide any detailed information if necessary though.

**Comment by MorrisJobke** [comment]
@jospoortvliet your topic

**Comment by jospoortvliet** [comment]
The 12.0.1 announcement newsletter was delayed due to work on 12.0.2 and that is delayed due to us being too busy with the conference... but I do want to sent it out today... sorry.

**Comment by michaellass** [comment]
Thanks for the response. A small delay for the announcements is not a problem of course.

Still, I wonder if there is a problem with the update notifications. I checked my nextcloud.log and it shows that the OCA\UpdateNotification\Notification\BackgroundJob has run every day. Also, I could see pending updates when looking into the admin panel. Still, there was never an email sent out to users of the admin group as expected:
![bildschirmfoto 2017-08-16 um 11 41 22](https://user-images.githubusercontent.com/11042539/29357460-ee5ab0dc-8277-11e7-930b-f29b5d823eea.png)
Any idea what could be the issue here?

**Comment by MorrisJobke** [comment]
> Still, there was never an email sent out to users of the admin group as would be expected:

There are no emails send out. It's only the notification in the top right (the little bell) in the web UI or in the desktop client.

**Comment by michaellass** [comment]
Oh, i totally misinterpreted that setting. Sorry for the noise. In case someone stumbles over this in future, there is already a feature request about email notifications for pending upgrades: #3596
