### ISSUE TITLE
it shows  "Failed to load resource: net::ERR_TOO_MANY_REDIRECTS"

### ISSUE THREAD

**Issue by mysteryHJJ** [nextcloud/server#6144]
when I use nextcloud into my site iframe , it works ok in firefox , but in google.it takes errors like these
![image](https://user-images.githubusercontent.com/18051097/29345628-92d10d92-8272-11e7-9031-98693650f52a.png)

**Comment by MorrisJobke** [comment]
Looks like there is a setup issue. Please ask for help in the forums: https://help.nextcloud.com/
