### ISSUE TITLE
updater app ignores proxy server from configuration

### ISSUE THREAD

**Issue by ArnY** [nextcloud/server#6147]
If the outdated nextcloud instance requires an http proxy to reach internet and if this proxy is actually properly configured in the instance's configuration the updater app will fails downloading the package from nextcloud's servers. the updater app doesn't use the configured proxy

For example in updater/index.php:
```php
                $curl = curl_init();
                curl_setopt_array($curl, [
                        CURLOPT_RETURNTRANSFER => 1,
                        CURLOPT_URL => $updateURL,
                        CURLOPT_USERAGENT => 'Nextcloud Updater',
                ]);
                $response = curl_exec($curl);
```
Same problem in the updater.phar file.

Tested with nextcloud 12.

**Comment by MorrisJobke** [comment]
Will come with the new updater that is shipped in 12.0.1+ - https://github.com/nextcloud/updater/pull/80
