### ISSUE TITLE
Nextcloud sometimes decides 0Kb placeholder files should replace other files.

### ISSUE THREAD

**Issue by Windyo** [nextcloud/server#6152]
### Steps to reproduce
1. Set up a new Nextcloud instance
2. Transfer local data (a lot of files of varying sizes is needed, as the bug only appears on select instances) to the drive that Nextcloud will be using
3. Launch occ scan
4. Point the Nextcloud client to the folder where the data was originally from
5. Wait for all ongoing operations to finish, then launch a client sync.

### Expected behaviour
1. Client should find files equal, mark sync done, and finish sync operation with no file transfers.

### Actual behaviour
1. Client does not recognize equal files and procedes to download/upload them
2. Client sometimes decides that the server version is better and overwrittes local file. About 60% of these overwritten files are 0Kb files
4. Client then reuploads the 0Kb file, replacing the valid file on server.
5. Data is lost.

### Server configuration

**Operating system**:
NextCloudPi

**Web server:**
Raspberry Pi 3

**Database:**
MariaDB 10

**PHP version:**
PHP 7.0 

**Nextcloud version:** (see Nextcloud admin page)
12.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh

**Where did you install Nextcloud from:**
https://ownyourbits.com/2017/02/13/nextcloud-ready-raspberry-pi-image/

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:** 
no

**Comment by MorrisJobke** [comment]
This only happens on the client itself? On the server there is still the properly sized version?

cc @rullzer @pfiff45

**Comment by Windyo** [comment]
Both. On files affected, client will replace both client and server with 0kb files.

**Comment by Windyo** [comment]
I'm going to close this as i can't reproduce this now and couldn't reproduce it for some time.
