### ISSUE TITLE
Theming App: Add option to change Favicons

### ISSUE THREAD

**Issue by Af0x** [nextcloud/server#6153]
Hello,

I want to suggest adding options for changing the favicon(s) within the theming app.

Regards,

Af0x

**Comment by MorrisJobke** [comment]
The theming app generates favicon out of the logo on the fly if the imagick PHP extension is enabled.

**Comment by Af0x** [comment]
I have the imagick extension installed but it doesn´t seem to work in 12.0.1.

**Comment by MorrisJobke** [comment]
cc @juliushaertl
