### ISSUE TITLE
Can't access to old revision/version of a file (Collabora)

### ISSUE THREAD

**Issue by OrpheeGT** [nextcloud/server#6155]
### Steps to reproduce
1. Try to access an old version of a Collabora document online

It does not always happens, it seems to happen on older revisions, or there is some kind of expiration time ?

### Expected behaviour
Download all revision

### Actual behaviour
Error 403 

### Server configuration

Ubuntu 16.04

Apache

MySQL

PHP 7

Nextcloud 12.0.2

Updated from 12.0.1, updated from 11.x

```
Login as admin user into your Nextcloud and access 
No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - keeweb: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ocsms: 1.12.0
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - quota_warning: 1.0.1
  - ransomware_protection: 1.0.1
  - richdocuments: 1.12.34
  - serverinfo: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.1
  - twofactor_u2f: 1.3.2
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - federation
  - files_external
  - nextcloud_announcements
  - sharebymail
  - survey_client
  - systemtags
  - user_external
  - user_ldap

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - keeweb: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ocsms: 1.12.0
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - quota_warning: 1.0.1
  - ransomware_protection: 1.0.1
  - richdocuments: 1.12.34
  - serverinfo: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.1
  - twofactor_u2f: 1.3.2
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - federation
  - files_external
  - nextcloud_announcements
  - sharebymail
  - survey_client
  - systemtags
  - user_external
  - user_ldap

sudo -u www-data php occ config:list system
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocsakd3h08iv",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "obfuscated"
        ],
        "datadirectory": "\/var\/www\/public\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/obfuscated\/nextcloud",
        "dbtype": "mysql",
        "version": "12.0.2.0",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "appstore.experimental.enabled": true,
        "mysql.utf8mb4": true,
        "updater.release.channel": "stable",
        "dbname": "nextcloud",
        "dbhost": "127.0.0.1",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "nextcloud",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "obfuscated",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "obfuscated",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
Chromium

Windows

### Logs
Uncaught Error: Access to undeclared static property: OC\Files\Filesystem::$normalizedPathCache in /var/www/public/nextcloud/lib/private/Files/Filesystem.php:804 Stack trace: #0 /var/www/public/nextcloud/lib/private/Files/View.php(2032): OC\Files\Filesystem::normalizePath('/Orphee/files/C...') #1 /var/www/public/nextcloud/lib/private/Files/View.php(1170): OC\Files\View->unlockFile('/Covoiturage/su...', 1) #2 [internal function]: OC\Files\View->OC\Files\{closure}() #3 /var/www/public/nextcloud/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure)) #4 [internal function]: Icewind\Streams\CallbackWrapper->stream_close() #5 {main} thrown at /var/www/public/nextcloud/lib/private/Files/Filesystem.php#804

**Comment by OrpheeGT** [comment]
More logs : 

{"reqId":"WZRfclt5SrEAACl9ZgEAAAAI","level":4,"time":"2017-08-16T15:06:27+00:00","remoteAddr":"93.174.144.114","user":"Orphee","app":"webdav","method":"GET","url":"\/nextcloud\/remote.php\/webdav\/Covoiturage\/suivi%20covoiturage.ods?downloadStartSecret=0xgb5rhn9aj","message":"Exception: {\"Exception\":\"OCP\\\\Encryption\\\\Exceptions\\\\GenericEncryptionException\",\"Message\":\"Bad Signature\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/public\\\/nextcloud\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Crypt.php(463): OCA\\\\Encryption\\\\Crypto\\\\Crypt->checkSignature('hFiGQpGRdLMsg9c...', '\\\\xB5\\\\xFB\\\\x01\\\\x9C\\\\xB3\\\\x9F`\\\\xAA\\\\xA2\\\\x84\\\\xBC\\\\xB7\\\\x1FI\\\\xF8...', '174c2c8619cccfa...')\\n#1 \\\/var\\\/www\\\/public\\\/nextcloud\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Encryption.php(378): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('hFiGQpGRdLMsg9c...', '\\\\xB5\\\\xFB\\\\x01\\\\x9C\\\\xB3\\\\x9F`\\\\xAA\\\\xA2\\\\x84\\\\xBC\\\\xB7\\\\x1FI\\\\xF8...', 'AES-256-CTR', 16, 0)\\n#2 \\\/var\\\/www\\\/public\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(460): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt(*** sensitive parameters replaced ***)\\n#3 \\\/var\\\/www\\\/public\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(291): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#4 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#5 \\\/var\\\/www\\\/public\\\/nextcloud\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(83): fread(Resourceid #31, 8192)\\n#6 \\\/var\\\/www\\\/public\\\/nextcloud\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(91): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#7 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#8 \\\/var\\\/www\\\/public\\\/nextcloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #34, Resource id #37, '36450')\\n#9 \\\/var\\\/www\\\/public\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(498): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#10 \\\/var\\\/www\\\/public\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/public\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(71): Sabre\\\\DAV\\\\Server->exec()\\n#12 \\\/var\\\/www\\\/public\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/public...')\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/public\\\/nextcloud\\\/apps\\\/encryption\\\/lib\\\/Crypto\\\/Crypt.php\",\"Line\":483}","userAgent":"Mozilla\/5.0 (Windows NT 6.1) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3140.0 Safari\/537.36","version":"12.0.2.0"}
{"reqId":"WZRfdFt5SrEAACl9ZgIAAAAI","level":3,"time":"2017-08-16T15:06:29+00:00","remoteAddr":"93.174.144.114","user":"Orphee","app":"PHP","method":"GET","url":"\/nextcloud\/remote.php\/webdav\/Covoiturage\/suivi%20covoiturage.ods?downloadStartSecret=0xgb5rhn9aj","message":"Uncaught Error: Access to undeclared static property: OC\\Files\\Filesystem::$normalizedPathCache in \/var\/www\/public\/nextcloud\/lib\/private\/Files\/Filesystem.php:804\nStack trace:\n#0 \/var\/www\/public\/nextcloud\/lib\/private\/Files\/View.php(2032): OC\\Files\\Filesystem::normalizePath('\/Orphee\/files\/C...')\n#1 \/var\/www\/public\/nextcloud\/lib\/private\/Files\/View.php(1170): OC\\Files\\View->unlockFile('\/Covoiturage\/su...', 1)\n#2 [internal function]: OC\\Files\\View->OC\\Files\\{closure}()\n#3 \/var\/www\/public\/nextcloud\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(109): call_user_func(Object(Closure))\n#4 [internal function]: Icewind\\Streams\\CallbackWrapper->stream_close()\n#5 {main}\n  thrown at \/var\/www\/public\/nextcloud\/lib\/private\/Files\/Filesystem.php#804","userAgent":"Mozilla\/5.0 (Windows NT 6.1) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3140.0 Safari\/537.36","version":"12.0.2.0"}

**Comment by MorrisJobke** [comment]
This is provided by the rich documents app and seems to be an interference between encryption and collabora. Could you open an issue in https://github.com/nextcloud/richdocuments? Thanks.
