### ISSUE TITLE
12.0.2 After upgrade files missing and button "upgrade" doesn't work

### ISSUE THREAD

**Issue by dirigit** [nextcloud/server#6159]
### Steps to reproduce
1. Upgrade to 12.0.2 is announced in backend
2. start upgrader

### Expected behaviour
Upgrader should install all new files

### Actual behaviour
Files are missing, i.e. lib/autoloader.php

After manual copying all files from distribution button "Upgrade" does not work (no reaction).

Direct call to updater via Browser wants to have a password. This doesn't accept the password. Neither known one nor new created.

Had to fix .htaccess again (overwritten by updater). RewriteBase was deleted at least.

### Server configuration

**Operating system**:
Debian
**Web server:**
Apache
**Database:**
mysql
**PHP version:**
7.0.22
**Nextcloud version:** (see Nextcloud admin page)
12.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
12.0.1
**Where did you install Nextcloud from:**
distribution

**Comment by MorrisJobke** [comment]
> Files are missing, i.e. lib/autoloader.php

Then that file was somehow deleted. Definitely not by the updater.



> After manual copying all files from distribution button "Upgrade" does not work (no reaction).

The updater itself only does copying files. Then the upgrade of the server itself happens (with migration steps and repair steps etc)



> Direct call to updater via Browser wants to have a password. This doesn't accept the password. Neither known one nor new created.

This is not your user password, but the created one, that usually is the same as this little button does, but the manual steps are described on the page itself. As you already copied the files, you can skip the updater and directly go to the upgrade page.



> Had to fix .htaccess again (overwritten by updater).

Yes. We overwrite it on upgrade.

> RewriteBase was deleted at least.

You can set this in the config.php. See config.sample.php.
