### ISSUE TITLE
Ctrl-click on entries in the user menu will keep spinner spinning

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#616]
When you Ctrl-click on entries in the Apps menu on the top left, the spinner does not show and the menu closes directly – which is the correct behavior.

When you Ctrl-click on entries in the User menu on the top right, the menu stays open and the spinner is shown indefinitely. This should be fixed to behave as the apps menu does. :)

cc @nextcloud/javascript

**Comment by MorrisJobke** [comment]
See https://github.com/owncloud/core/pull/23914 for the implementation in the apps menu

**Comment by jancborchardt** [comment]
cc @ChristophWurst since you fixed it for the apps menu. ;)
