### ISSUE TITLE
Chat does not work when username contains '@'

### ISSUE THREAD

**Issue by alxarce** [nextcloud/server#6174]
### Steps to reproduce
1. Create users:
       Create two users accounts with username contains '@' like **abc@test.com** and **cde@test.com**

2. Enable **JavaScript XMPP Chat**  (v 3.2.1)
3. Configure **JavaScript Xmpp Client** as **Internal**

4. Login with:  **abc@test.com** and **cde@test.com**, start a chat and send a messages between this accounts

	
### Expected behaviour
Messages sent from **abc@test.com** to **cde@test.com** are sent successfully

### Actual behaviour
Messages sent from **abc@test.com** to **cde@test.com** do not arrive

### Server configuration
Operating system: Ubuntu 16.04
Nextcloud version: 12.0.2
Database: Postgresql 9.6
Web server: Nginx
PHP version: 7.0

**Comment by LukasReschke** [comment]
Please reopen at https://github.com/nextcloud/jsxc.nextcloud
