### ISSUE TITLE
update circles --> db error --> NC stays in maintenance mode

### ISSUE THREAD

**Issue by miconx** [nextcloud/server#6175]
1. i made  a normal upgrade of the circles app (i use nextcloud 12.0.2) 

sudo -u www-data php /usr/local/bin/occ upgrade

Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'ALTER TABLE oc_circles_members ADD "user_type" SMALLINT NOT NULL':

SQLSTATE[23502]: Not null violation: 7 ERROR:  column "user_type" contains null values
Update failed

**Comment by LukasReschke** [comment]
Probably related to https://github.com/nextcloud/server/issues/6163

**Comment by LukasReschke** [comment]
cc @daita

**Comment by daita** [comment]
there is a quick fix there: https://github.com/nextcloud/circles/issues/117#issuecomment-323299738

I'll check for the real source of the issue.
