### ISSUE TITLE
jQuery UI not themed by theming app on 12 + master

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#6178]
This is a regression from https://github.com/nextcloud/server/issues/830

<img width="1608" alt="screen shot 2017-08-18 at 13 10 54" src="https://user-images.githubusercontent.com/878997/29456610-bf4caf8e-8416-11e7-90a3-e7dc2b421af1.png">

cc @nextcloud/theming

**Comment by MorrisJobke** [comment]
Fixed in #6341
