### ISSUE TITLE
File Access Control not consistently between "Files" & "Gallery"

### ISSUE THREAD

**Issue by timboven** [nextcloud/server#6181]
Not sure if this is either a bug or an enhancement - I noticed an issue while using the File Access Control-plugin and the behavior of this config between multiple apps.
I have a shared folder that is accessible by multiple types of users:
1) full read/write users
2) full read only users
3) limited read only users
But at this moment is isn't possible to hide for this last set of users that we have some content related to xyz as the Files & activity-plugins are showing any kind of activity - even if the user doesn't have access.

### Steps to reproduce
1. Create a shared folder
2. create a folder "A" & "B" under this share
3. tag "A"  as "protected"
4. upload a photo in A and another one in B (optional)
5. use the "File Access Control"-plugin to block access to "protected" if you are not in the admin-group (could be any group you want)
6. Create a new user (user B) that also has access to that shared folder, but isn't an admin
7. Check the contents of the folder with this user B through the gallery app (only folder B is visible)
8. Check the contents of the folder with this user B through the file app (both folders are visible)

### Expected behaviour
From a security point of view, I would expect that if user B doesn't have access to a given folder - that he wouldn't see it either. (e.g. only the name of the folder itself could already expose sensitive info)
Note: the same is true for the activity tracker!

### Actual behaviour
The folders are visible but when you click them, you go back to the root-folder and get a error that you do not have access.

### Server configuration
**Nextcloud version: 12.0.2
**Updated from an older Nextcloud/ownCloud or fresh install: updated
**Where did you install Nextcloud from: docker

**Comment by nickvergessen** [comment]
As per the documentation https://docs.nextcloud.com/server/12/admin_manual/file_workflows/access_control.html#denied-access
Listing of blocked items is not blocked.

The reason why the gallery app hides the item is, because it is "empty" in terms of "has no readable content". You can also test this, by creating an empty folder. It will also not show up in the gallery view.
