### ISSUE TITLE
.htaccess overwrote after upgrade

### ISSUE THREAD

**Issue by chezyann** [nextcloud/server#6184]
Hi,

I’ve just installed Nextcloud 12.0.1 and edited the .htaccess BELOW the mention “#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####”.

I upgraded Nextcloud to version 12.0.2 via the web interface.

Unfortunately everything located BELOW the specific mention disappeared…

Maybe upgrades may just copy-paste the ending lines from the good old one .htaccess ?

This is pretty annoying since each upgrade leads to a security issue.

This problem is closed to #132

**Comment by MorrisJobke** [comment]
Duplicate of #4669

See https://github.com/nextcloud/server/issues/4769#issuecomment-322219262 for details
