### ISSUE TITLE
After migration from owncloud 9.0.6 to nextcloud 12.0.1 avatars are not shown any more in User management

### ISSUE THREAD

**Issue by Klakla2** [nextcloud/server#6188]
### Steps to reproduce
1. Install owncloud 9.0.6
2. Upload photo for at least one User and check, that it is displayed in User management
3. Upgrade to nextcloud 12.0.1 (in my case  owncloud 9.0.6 -> nextcloud 9.0.58 -> nextcloud 10.0.6 -> nextcloud 11.0.4 -> nextcloud 12.0.1)
4. Everything is OK besides check display in User management

### Expected behaviour
All Avatars visible in Owncloud 9.0.6 should also be visible in nextcloud 12.0.1

### Actual behaviour
All users are only shown by the first letter, none with an Avatar
But in Contacts  app the Avatar from owncloud 9.0.6 IS visible !!!

And it is possible to upload a photo for all users (both for those who had no photo before and fopr those, which had a photo before). That photo is then displayed as avatar in User management. (Could not try for someone who had a photo before, yet)

### General server configuration

**Operating system:** Linux s1151 2.6.32.71-kvm-32cpu-06 #1 SMP Fri Dec 2 15:35:31 CET 2016 x86_64

**Web server:** Apache (fpm-fcgi)

**Database:** mysql 5.5.28

**PHP version:** 5.6.30-pl0-gentoo
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - ereg
 - libxml
 - openssl
 - pcre
 - sqlite3
 - zlib
 - bcmath
 - bz2
 - calendar
 - ctype
 - curl
 - dba
 - dom
 - hash
 - fileinfo
 - filter
 - ftp
 - gd
 - gettext
 - gmp
 - SPL
 - iconv
 - session
 - intl
 - json
 - ldap
 - mbstring
 - mcrypt
 - mssql
 - standard
 - mysqlnd
 - mysqli
 - odbc
 - pcntl
 - mysql
 - PDO
 - pdo_dblib
 - pdo_mysql
 - PDO_ODBC
 - pdo_pgsql
 - pdo_sqlite
 - pgsql
 - Phar
 - pspell
 - readline
 - Reflection
 - imap
 - shmop
 - SimpleXML
 - soap
 - sockets
 - exif
 - sysvmsg
 - sysvsem
 - sysvshm
 - tidy
 - tokenizer
 - wddx
 - xml
 - xmlreader
 - xmlrpc
 - xmlwriter
 - xsl
 - zip
 - cgi-fcgi
 - mhash
 - ionCube Loader
 - Zend Guard Loader
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.1 - 12.0.1.5

**Updated from an older Nextcloud/ownCloud or fresh install:** owncloud 9.0.6

**Where did you install Nextcloud from:**  Updater app - console.php had to be modified, because I do not have python extensions installed

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

<details>
        <summary>Signing status</summary>

```
{
    "core": {
        "INVALID_HASH": {
            "console.php": {
                "expected": "b9dd35cf66b04664ae54fb52bd19fb6213b9d3c687a539c9b4ad12aa07a3ac2d90e0605ceabf3b1af17d540df452ac416c224c4702ab5b9d6f1d41d75796c083",
                "current": "4e1575330aeb435236d30a98ff03bea76caa3537e014ec7fdfd0cb1b6a86831ab71f647da3f35b2db85a11c5e6608e96b5020c5e42769b13b241fd402d592a02"
            }
        }
    }
}
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - announcementcenter: 3.1.0
 - bookmarks: 0.10.1
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - gpxedit: 0.0.7
 - gpxmotion: 0.0.4
 - gpxpod: 2.1.4
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notes: 2.3.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_notifications
 - encryption
 - files_external
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "oceb02bf0b57",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.adfc-berlin.de"
    ],
    "datadirectory": "\/html\/owncloud\/data",
    "dbtype": "mysql",
    "version": "12.0.1.5",
    "dbname": "usr_p106485_7",
    "dbhost": "db1117.mydbserver.com",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_from_address": "cloud",
    "mail_smtpmode": "smtp",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "adfc-berlin.de",
    "loglevel": 3,
    "mail_smtphost": "mail.adfc-berlin.de",
    "mail_smtpport": "587",
    "mail_smtpauth": true,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "forcessl": true,
    "activity_expire_days": 90,
    "maintenance": false,
    "theme": "",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trashbin_retention_obligation": "auto",
    "updater.release.channel": "production",
    "overwrite.cli.url": "https:\/\/cloud.adfc-berlin.de"
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; rv:54.0) Gecko/20100101 Firefox/54.0

**Operating system:** Windows 10

**Comment by LukasReschke** [comment]
There's a repair step that should add the avatars properly again. 

A) Does the admin page show that the cronjob was running?
B) Do the avatars reappear after some time?

**Comment by Klakla2** [comment]
A) yes - it shows 'just now', but it is not configured to run cron. It is
configured as Ajax.
B) They did not reappear (upgrade was done 13th of August).

Am 22.08.2017 6:40 vorm. schrieb "Lukas Reschke" <notifications@github.com>:

There's a repair step that should add the avatars properly again.

A) Does the admin page show that the cronjob was running?
B) Do the avatars reappear after some time?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nextcloud/server/issues/6188#issuecomment-323917356>,
or mute the thread

**Comment by Klakla2** [comment]
Could I get an update please  - or is the info provided not sufficient?

**Comment by MorrisJobke** [comment]
@rullzer You did the avatar migration, right?

**Comment by Klakla2** [comment]
Any news on this? The status 'needs info' seems inappropriate to me.

**Comment by rullzer** [comment]
Well there was a job to do avatar migration but that should have kicked in by now. Can you check your oc_jobs table to see if there is a job with Avatar in it in there?

**Comment by Klakla2** [comment]
I exported oc_jobs as .sql and checked content in editor.
There are several jobs - e.g. DeleteOröhanedItems, but no job matching avatar or anything similar.

**Comment by Klakla2** [comment]
We are now on Nextcloud 12.0.6.
I think that the issue might be closed.
I now see several avatars, but I am not 100% sure, that these  have not been recreated manually.
