### ISSUE TITLE
cannot update database

### ISSUE THREAD

**Issue by toodr** [nextcloud/server#6191]
### Steps to reproduce
1. I'm trying to update to 12.0.2
2. But I'm getting this error:
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_mimetypes CHANGE `mimetype` `mimetype` VARCHAR(255) DEFAULT '' NOT NULL': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
3. The server is 10.0.32-MariaDB and the database default-character-set = utf8mb4
4. The update querry is trying to change the mimetype column from 191 to 255 bits and this causes this error. 
5. In the config.php there is a line 'mysql.utf8mb4' => true,

### Expected behaviour
The update querry should honor the setting 'mysql.utf8mb4' => true, in config.php and should read smth. like 'ALTER TABLE oc_mimetypes CHANGE `mimetype` `mimetype` VARCHAR(191) DEFAULT '' NOT NULL'

### Actual behaviour
the update stalled with the above quoted error 

### Server configuration

**Slackware current 64bit**:

**Apache/2.4.27 (Unix) OpenSSL/1.0.2l PHP/5.6.31**

**Database:** 10.0.32-MariaDB and the database default-character-set = utf8mb4

**PHP version:**PHP/5.6.31

**Nextcloud version:**12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Nextcloud website , downloaded 

</details>

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
if you use mysql 4byte support, please be sure that you have completed all steps from https://docs.nextcloud.com/server/11/admin_manual/maintenance/mysql_4byte_support.html

**Comment by toodr** [comment]
Thank you very much!
All done now.
I didn't know that there were such instructions ...
