### ISSUE TITLE
e-mail notifications for activities are not received 

### ISSUE THREAD

**Issue by JK74** [nextcloud/server#6204]
### Steps to reproduce
1. enable for your user all activities to be coming in on e-mail (by default is almost dis-disabled.
Then do any of below actions:
a. make a new directory and share the directory with an existing user
b. make an reaction to an uploaded file from the user that uploaded it where e-mail noticiation for reactions is enabled
c. upload a new file to an folder shared by the other user to you

### Expected behaviour
I should get an e-mail letting me know about the reaction, file uploaded or shared directory with me. Now I don't get anything. We only see e-mails coming in on new accounts created or for password resets.

### Actual behaviour
nothing happens no e-mails nothing.

### General server configuration

**Operating system:** Linux nextcloud 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.19

**PHP version:** 7.0.22-0ubuntu0.16.04.1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - apache2handler
 - mysqlnd
 - PDO
 - xml
 - apcu
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - iconv
 - igbinary
 - json
 - exif
 - mysqli
 - pdo_mysql
 - Phar
 - posix
 - readline
 - redis
 - shmop
 - SimpleXML
 - sockets
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.2 - 12.0.2.0

**Updated from an older Nextcloud/ownCloud or fresh install: from 11.0 > 11.x > 12.0 > 12.0.1 12.0.2

**Where did you install Nextcloud from:**  local storage

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OCA\Files_External\Lib\Storage\FTP
    [2] => \OC\Files\Storage\DAV
    [3] => \OCA\Files_External\Lib\Storage\OwnCloud
    [4] => \OCA\Files_External\Lib\Storage\SFTP
    [5] => \OCA\Files_External\Lib\Storage\AmazonS3
    [6] => \OCA\Files_External\Lib\Storage\Dropbox
    [7] => \OCA\Files_External\Lib\Storage\Google
    [8] => \OCA\Files_External\Lib\Storage\Swift
    [9] => \OCA\Files_External\Lib\Storage\SFTP
    [10] => \OCA\Files_External\Lib\Storage\SMB
    [11] => \OCA\Files_External\Lib\Storage\SMB
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** YOUR ANSWER HERE (LDAP/ActiveDirectory/Webdav/...)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - admin_notifications: 1.0.0
 - announcementcenter: 3.1.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - circles: 0.12.4
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - external: 2.0.3
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_automatedtagging: 1.2.2
 - files_downloadactivity: 1.1.1
 - files_external: 1.3.0
 - files_pdfviewer: 1.1.1
 - files_retention: 1.1.2
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - groupfolders: 1.1.0
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notes: 2.3.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - quota_warning: 1.0.1
 - ransomware_protection: 1.0.1
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - spreed: 2.0.1
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - activitylog
 - encryption
 - files_antivirus
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "ocaacnf00r5p",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "xxx.xxx",
        "xxx.xx",
        "192.168.x.x",
        "192.168.x.x"
    ],
    "datadirectory": "\/xxx",
    "overwrite.cli.url": "https:\/\/xxx\/xxx",
    "dbtype": "mysql",
    "version": "12.0.2.0",
    "dbname": "xxx",
    "dbhost": "xxx",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Berlin",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": "true",
    "redis": {
        "host": "\/var\/run\/redis\/redis.sock",
        "port": 0,
        "timeout": 0
    },
    "session_lifetime": 3600,
    "htaccess.RewriteBase": "\/nextcloud",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "noReply",
    "mail_domain": "xxx",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "xxx",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 0,
    "cron_log": true,
    "log_rotate_size": 104857600,
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\Movie"
    ],
    "preview_max_filesize_image": 200,
    "updater.secret": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "singleuser": true,
    "updater.release.channel": "production"
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36

**Operating system:** YOUR ANSWER HERE

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
What type of background job do you have configured? See https://docs.nextcloud.com/server/12/admin_manual/configuration_server/background_jobs_configuration.html for details about the differences and how to set them up.

**Comment by JK74** [comment]
cron

# m h  dom mon dow   command
*/15 * * * * php -f /var/www/nextcloud/cron.php

**Comment by MorrisJobke** [comment]
For the cron issue please ask for help in the forums, because this seems to be a setup issue.

For the icons it looks like you have not configured your servers URL properly. See the option `overwrite.cli.url` in config.sample.php for additional info. Then the images should also be displayed properly.

**Comment by JK74** [comment]
@MorrisJobke 
Thanks again for the guidance !

I looked at my overwrite.cli.url  and it was correctly name to 'https://myserver.info/nextcloud' I even changed  it to 'http://myserver.info.nextcloud' but it did not help.

Then I looked at my apache conf as there is what I do the static redirecto from http to https::
<VirtualHost *:80>
   ServerName cloud.nextcloud.com
   Redirect permanent / https://cloud.nextcloud.com**/**
</VirtualHost>

Then I noticed I was missing on the end of the redirect permanent the backslash "/". So I changed that!
However I'm now still beeing confronted with app likes activity that does not show the activity icon correcty because my URL get mapped server**.infonextcloud/**apps/announcementcenter/img/announcementcenter-dark.svg
I have re-looked at my ssl redirect etc. but I'm now really lost where if forgot or need to add this / to get the announcement center icon to work. can you give me a little guidance?

**Comment by MorrisJobke** [comment]
cc @nickvergessen
