### ISSUE TITLE
Question: How to remove the Memberlist

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/server#6206]
I plan to give somenot realy good nown People accest to a created Guest-account on my nextcloud. So they schould not be allowed to see other members in this cloud. How could I remove this icon?
![2017-08-21 14_51](https://user-images.githubusercontent.com/7795891/29520332-f0860f84-8680-11e7-8099-ac72c91e3ff6.jpg)

**Comment by MorrisJobke** [comment]
This is currently not possible. You can disable the enumeration of users in the admin sharing settings. Then you need to enter the full name/email address to share with somebody.
