### ISSUE TITLE
Use HTTP2 server push to improve load times

### ISSUE THREAD

**Issue by nachoparker** [nextcloud/server#6214]
Hi, 

This is a paste of my suggestion [in this comment](https://github.com/nextcloud/server/issues/3790#issuecomment-317953318) as a separate request.

To complement my [message](https://github.com/nextcloud/server/issues/2272#issuecomment-317949685) on the other post I would like to suggest that some sort of [HTTP2 server push ](https://en.wikipedia.org/wiki/HTTP/2_Server_Push) is implemented on the server side.

This will allow HTTP2 enabled servers to push assets to the browser even before it fully computes `index.php` and requests them. Note that assets can be _preloaded_ or _prefetched_, and we can even _preconnect_ to the server to save TCP connection time.

Also, it should be quite simple to implement. In the case of the [NextCloudPi web interface](https://ownyourbits.com/2017/07/24/nextcloupi-gets-a-web-interface/) (quite a simple example), it amounts to [one line](https://github.com/nextcloud/nextcloudpi/blob/master/ncp-web/index.php#L35)

```
header("Link: </minified.js>; rel=preload; as=script;,</ncp.js>; rel=preload; as=script;,</ncp.css>; rel=preload; as=style;,</ncp-logo.png>; rel=preload; as=image;, </loading-small.gif>; rel=preload; as=image;, rel=preconnect href=ncp-launcher.php;");
```

, and the result on a **very slow** QEMU ARM instance ( gray ball means pushed )

![web-push](https://user-images.githubusercontent.com/21343324/28606064-651f777e-71d5-11e7-976e-c94c0b1fa38b.jpg)

There's some informative links at the bottom of the blog post.

**Comment by MorrisJobke** [comment]
Regarding the server push: we need to track which assets are already delivered to the specific client to not push all assets that are already cached in the browser. 

Regarding the preloading header: yes it may help, but currently we first want to focus on bundling JS files and reduce the number of assets first, because it has a bigger gain in performance first. So we should focus on the low hanging fruits.

See #4045

I hope this is understandable.

**Comment by nachoparker** [comment]
> Regarding the server push: we need to track which assets are already delivered to the specific client to not push all assets that are already cached in the browser.

Please, don't disregard this too easily. The browser/client automatically cancels the push with a `RST_STREAM` frame when the asset is found in its cache, so cached stuff is not pushed again.

See

https://en.wikipedia.org/wiki/HTTP/2_Server_Push
https://stackoverflow.com/questions/29352282/does-the-browser-cancel-server-push-when-a-resource-is-in-cache
https://www.daveyshafik.com/archives/69603-http2-server-push-youre-doing-it-all-wrong.html


> we should focus on the low hanging fruits.

100% aggree, and I know the issue of loading time is being addressed. HTTP2 server push would come after that.

Still I think it would be of value. Any chance to leave it open until its time?

**Comment by hoellen** [comment]
I think there are more use cases than just loading time. If HTTP2 Push would be supported, there could be push notification for the (Android) Talk App and Client **without** Google dependencies (F-Droid version). Also the Desktop-Client could be sync immediately instead of a pull every 30 sec. Just to name a few :)

**Comment by ad-m** [comment]
>  If HTTP2 Push would be supported, there could be push notification for the (Android) Talk App and Client without Google dependencies (F-Droid version).
>  Also the Desktop-Client could be sync immediately instead of a pull every 30 sec. Just to name a few :)
> HTTP/2 Server Push[1] is not a notification mechanism from server to client. Instead, pushed resources are used by the client when it may have otherwise produced a request to get the resource anyway; this can result in wasted bandwidth if said pushed resources go unused by the client, however. 

( https://en.wikipedia.org/wiki/HTTP/2_Server_Push )

Notifications in 2018 year should be made via websocket / [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) connection .  It seems to me that maintaining such in mobile devices can be quite expensive and have an impact on the operation of the device on the battery.

**Comment by nachoparker** [comment]
Exactly. HTTP2 push is not about push notifications, but about faster load times.

**Comment by Gatak** [comment]
> Regarding the server push: we need to track which assets are already delivered to the specific client to not push all assets that are already cached in the browser.
> 
> Regarding the preloading header: yes it may help, but currently we first want to focus on bundling JS files and reduce the number of assets first, because it has a bigger gain in performance first. So we should focus on the low hanging fruits.
> 
> See #4045
> 
> I hope this is understandable.

It seems as it should be possible to set a cookie with an appropriate for the current generation of css and js. If the browser request contain this id you simply do not push the same resource again.

**Comment by jack9603301** [comment]
Support for http2 server resource push technology will help to maximize the optimization technology of http2 and facilitate faster loading (resources can be actively transmitted from the server rather than actively requested by the client, saving the time of client resource queuing and request)

**Comment by skjnldsv** [comment]
cc @ChristophWurst  ?
With https://github.com/nextcloud/push ?

**Comment by ChristophWurst** [comment]
no, HTTP2 server push is something completely unrelated.

**Comment by skjnldsv** [comment]
I read too quickly :wink:

**Comment by SimJoSt** [comment]
As [Chromium is removing support for HTTP/2 push](https://groups.google.com/a/chromium.org/g/blink-dev/c/K3rYLvmQUBY/m/vOWBKZGoAQAJ?pli=1) I believe this issue can be closed.

**Comment by debian-user-france1** [comment]
> As [Chromium is removing support for HTTP/2 push](https://groups.google.com/a/chromium.org/g/blink-dev/c/K3rYLvmQUBY/m/vOWBKZGoAQAJ?pli=1) I believe this issue can be closed.

Nobody uses Chromium - even if it isn't bad to add push (by setting etc)

**Comment by Ich5003** [comment]
> > As [Chromium is removing support for HTTP/2 push](https://groups.google.com/a/chromium.org/g/blink-dev/c/K3rYLvmQUBY/m/vOWBKZGoAQAJ?pli=1) I believe this issue can be closed.
> 
> Nobody uses Chromium - even if it isn't bad to add push (by setting etc)

As Chromium is the base of the Chrome, Opera, Edge and many more browsers none of those browsers support http/2 push anymore so it's useless to add http/2 push.

**Comment by debian-user-france1** [comment]
Yeah... but Safari and Firefox still support it
