### ISSUE TITLE
Circle-app has an error when upgrading to 12.0.2

### ISSUE THREAD

**Issue by frogueat** [nextcloud/server#6219]
### Steps to reproduce
1. Have an nextcloud 12 instance (in my case with an postgres db), circles app activated an circles allready existing
2. make the upgrade
3. boom

### Expected behaviour
The upgrade adds an attribute to a table with not null declared. but if there are allread in the table, this db-execution fails.

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:
ubuntu
**Web server:**
apache
**Database:**
postgresql
**PHP version:**
7
**Nextcloud version:** (see Nextcloud admin page)
12.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
update
**Where did you install Nextcloud from:**
nextcloud server
</details>

**Comment by MariusBluem** [comment]
Please open your issue over this repository, since the Circles app is an separate application inside the Nextcloud ecosystem. THX!

https://github.com/nextcloud/circles/
