### ISSUE TITLE
failuer of database converter with calender app

### ISSUE THREAD

**Issue by craff** [nextcloud/server#6222]
After a long upgrade path:
owncloud 8.2 => nextcloud 9 => ... nextcloud 12 (and owncloud was before regularly upgraded)
I tried to convert the sqlite database to mysql and got a failure (see below).

After investigation, there were tuples
(christophe,calendar,currentview,...)
and
(christophe,calendar,currentView,...)
with just a case change, giving a UniqueConstraintViolationException.
This was probably a old configuration using 'currentview' intead of 'currentView' ... 

[Doctrine\DBAL\Exception\UniqueConstraintViolationException]                                         
  An exception occurred while executing 'INSERT INTO `oc_preferences` (`userid`, `appid`, `configkey`  
  , `configvalue`) VALUES(?, ?, ?, ?)' with params ["christophe", "calendar", "currentView", "month"]  
  :                                                                                                    
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'christophe-calendar-currentV  
  iew' for key 'PRIMARY' 
  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'christophe-calendar-currentV  
  iew' for key 'PRIMARY'
  [PDOException]                                                                                       
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'christophe-calendar-currentV  
  iew' for key 'PRIMARY'

**Comment by craff** [comment]
Note: removing the wrong entry solved the problem and I could convert my database in the end

**Comment by MorrisJobke** [comment]
Hard to detect and needs to be resolved by the admin to delete not the wrong data :/

I guess we can't do much here - sorry for that.

cc @nickvergessen
