### ISSUE TITLE
Unable to upload files to NextCloud

### ISSUE THREAD

**Issue by cardinalfan1** [nextcloud/server#6223]
### Steps to reproduce
1. Create local mountpoint "/cloud" which is connected to NFS mount
2. Create external storage "/cloud" as a local mount
3. Try and upload a file using the web GUI to this mount

### Expected behaviour
File should be able to upload

### Actual behaviour
Get error message:
```Not enough free space, you are uploading 115 KB but only 0 B is left```

### Server configuration

**Operating system**: Ubuntu/ Docker container official nextcloud image

**Web server:** Apache (as part of official docker image)

**Database:** Mariadb

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page) 12

**Updated from an older Nextcloud/ownCloud or fresh install:** no

**Where did you install Nextcloud from:** docker image

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "oco5dalaluhd",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "<url>"
        ],
        "datadirectory": "\/var\/www\/html\/data",
        "overwrite.cli.url": "<url>",
        "dbtype": "mysql",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "appserver_mariadb_nextcloud_1:3306",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** yes, local (which is connected to NFS mount)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome

**Operating system:** Windows

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
<empty>
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
> Not enough free space, you are uploading 115 KB but only 0 B is left

Please verify that your NFS storage is actually writable and has free space left. This looks like the external storage reports, that there is 0 bytes left on the device.
