### ISSUE TITLE
Email accounts colors

### ISSUE THREAD

**Issue by joaojotta** [nextcloud/server#6226]
So, this doesn't need a lot to understand.

**Issue**/Request, there's simply no way to customize colors on different email accounts on the Mail app. It's just setup randomly by default (or generated by the email account name).
This caused me to have **all 3 accounts with the same color**.

Any way to add this?

Thank you!

**Comment by MorrisJobke** [comment]
Please open this in the bug tracker of the mail app: https://github.com/nextcloud/mail/issues

Thanks :)
