### ISSUE TITLE
Wrong link? or No configuration for External storage

### ISSUE THREAD

**Issue by xayane** [nextcloud/server#6227]
### Steps to reproduce
1.As admin user go to Files page
2.On the left sidebar, click on External storage section
3.Click on 'You can add external storages in the personal settings' link

### Expected behaviour
it should be configuration of external storages?

### Actual behaviour
personal info with no external storages

### Server configuration

**Operating system**: Ubuntu Server 16.04.3

**Web server: Apache

**Database: mariaDB

**PHP version: 7.0

**Nextcloud version:12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install: nextcloud 12.0.1=>12.0.2

**Where did you install Nextcloud from: download from nextcloud.com. 

**Signing status: No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

  - activity: 2.5.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "10.0.0.1",
            "10.0.0.156",
            "guuu.gq"
        ],
        "datadirectory": "\/home\/uk\/share\/bakup\/nextcloud\/data\/",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "12.0.2.0",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "ocuod1bejug1",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "127.0.0.1",
            "port": 6379
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}

**Are you using external storage, if yes which one: nfs /home/uk/share/

**Are you using encryption: no

**Are you using an external user-backend, if yes which one: no

### Client configuration
**Browser: chrome 60.0.3112.78
![external storage](https://user-images.githubusercontent.com/9472580/29600277-88769c3c-8807-11e7-8458-a5deca7b3571.gif)

**Operating system: windows 10 pro

logs is huge, which one is useful?...

**Comment by thebitbrine** [comment]
Have the same problem
did you solve it?
