### ISSUE TITLE
Doctrine\DBAL\Exception\DriverException [...] SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query during update to 11.4

### ISSUE THREAD

**Issue by orsotron** [nextcloud/server#6230]
### Steps to reproduce
1. Ran the update of nextcloud 11.4 with automatic updater
2. Asked to return to the homepage for update of DB
3. Clicked on "run update"

### Expected behaviour
Hopefully, Correctly updated...

### Actual behaviour
Error is returned in the "blue cloudy homepage":

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON c.constraint_name = k.constraint_name AND c.table_name = 'oc_filecache' */ WHERE k.table_name = 'oc_filecache' AND k.table_schema = 'nextcloud' /*!50116 AND c.constraint_schema = 'nextcloud' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL': SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query

Detailed error stack:

Preparazione dell'aggiornamento
Imposta il livello del log per il debug
Modalità di manutenzione attivata
Aggiornamento schema database
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON c.constraint_name = k.constraint_name AND c.table_name = 'oc_filecache' */ WHERE k.table_name = 'oc_filecache' AND k.table_schema = 'nextcloud' /*!50116 AND c.constraint_schema = 'nextcloud' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL': SQLSTATE[HY000]: General error: 2013 Lost connection to MySQL server during query

### Server configuration

**Operating system**:

raspberrypi, raspbian jessie

**Web server:**

apache2

**Database:**

Mysql

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

11.3

**Updated from an older Nextcloud/ownCloud or fresh install:**

Updated

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
We can't do much here - the connection got closed for some external reasons. You can only re-run the update and it will continue where it stopped.
