### ISSUE TITLE
could not send invitation mail to attendees if email-address is already in use

### ISSUE THREAD

**Issue by bergart** [nextcloud/server#6235]
### Steps to reproduce
1. create 2 users (nc1, nc2) and add for both the same mail address
2. go (nc1) to the calendar app, create a new event with nc2 as an attendee
3. click create

### Expected behaviour
A ics attached inline mail shoud be send to the attendees.

### Actual behaviour
No notification/mail arrived. If all users have a different mail address it seems to work.

### Server configuration
**Operating system**:  Linux 4.10.0-32-generic #36~16.04.1-Ubuntu x86_64

**Web server:** nginx/1.10.3 (Ubuntu)

**Database:** MariaDB v.10.0.31

**PHP version:** 7.0.22

**Nextcloud version:** 13

**Updated from an older Nextcloud/ownCloud or fresh install:**  fresh install

**Where did you install Nextcloud from:** https://github.com/nextcloud/server

**Comment by tflidd** [comment]
If you are not planning to contribute as a developer, you shouldn't use the version from the github-master-branch. Rather use NC 12 (get from: https://nextcloud.com/changelog).

An option was added that users can not only use their user name but also their mail address to log in. Not sure if using one address for two users can create a problem here. Make sure there is no problem either.

**Comment by MorrisJobke** [comment]
cc @georgehrke

**Comment by leonklingele-work** [comment]
The issue here is that Nextcloud allows multiple users to configure the same email address. Email addresses should be unique amongst users.

**Comment by MorrisJobke** [comment]
> The issue here is that Nextcloud allows multiple users to configure the same email address. Email addresses should be unique amongst users.

Email addresses cannot be guaranteed to be unique, because they can come from multiple backends and then resolving this is not easily possible :/

**Comment by alexknobbe** [comment]
I think it's normal to have the email address unique.
When you have users in the system and you have the option to login with your username than this should be active for one account.

**Comment by georgehrke** [comment]
Having unique email addresses for each user is a fundamental requirement for calendar scheduling. A setup, where non-unique email-addresses are present, is not supported.

As @MorrisJobke explained in https://github.com/nextcloud/server/issues/6235#issuecomment-327479895, we can not directly enforce that, but i will add a health check that will cover most cases: https://github.com/nextcloud/server/issues/17146
