### ISSUE TITLE
checkbox and text has not the same line height 

### ISSUE THREAD

**Issue by bergart** [nextcloud/server#6238]
### Steps to reproduce
1. add a new event in your calendar app and hit the more button to add an attendee 
2. click on the attendee and look at the upcoming line with the checkbox

### Expected behaviour
same line height

### Actual behaviour
not the same line height (see image)

**Nextcloud version:** 12 and above

![selection_008](https://user-images.githubusercontent.com/22152652/29618753-6dcca090-8819-11e7-8335-8249b144a300.png)

**Comment by leonklingele-work** [comment]
@bergart this should have been reported on the [calendar app project](https://github.com/nextcloud/calendar).
