### ISSUE TITLE
Google Drive filenames with slashes cannot be accessed

### ISSUE THREAD

**Issue by Xenopathic** [nextcloud/server#6246]
I've linked Google Drive with Nextcloud, and it mostly works, however the sync client craps out on a particular file with slashes in the filename which I also cannot access in the web UI, and is named incorrectly in Nextcloud. Renaming the file in Google Drive to replace the slashes fixes the issue.

Example: a document named 'Meeting 8/11/15' will show up as '15.odt' in Nextcloud, and cannot be accessed (file not found when attempting to).

Seems like there might be some naive basenaming going on, taking everything after the last slash to be the filename? I can't see a clean solution for this, since synchronising such a file will break things even if the web UI could display the slashes, and any attempt to replace the slashes with something else will require mapping in the file cache (bad!). At least a better solution would be to filter out these files entirely, so they cannot be seen or interacted with in Nextcloud.

Nextcloud 12.0.0

**Comment by nickvergessen** [comment]
As far as I remember this problem always existed and files with slashes were just hidden in the past

**Comment by jospoortvliet** [comment]
@Xenopathic hey dude coming to the conference?

/me accepts a slap for being ENTIRELY off-topic and abusing github for chat

**Comment by e-alfred** [comment]
I have the same problem at times. Renaming helps. Is this related to the client not allowing these files like descibed here:

https://doc.owncloud.org/desktop/2.2/architecture.html?highlight=ignored#ignored-files

Aside from that this seems to be a duplicate of https://github.com/nextcloud/server/issues/4028.

**Comment by Xenopathic** [comment]
@jospoortvliet Sorry, I'm working in London this summer 😞 Hopefully next year though!

**Comment by jospoortvliet** [comment]
@Xenopathic well you could perhaps make up for it by joining us at a hackweek, would be cool. Dunno when the next is but will announce as soon as I know. Also - working? Why not for us 🥇

**Comment by y0va** [comment]
Still like to sync with non-techies... :)

**Comment by MorrisJobke** [comment]
As this is a separate app: please report it in that repo https://github.com/NastuzziSamy/files_external_gdrive/
