### ISSUE TITLE
Tags icon is too bright

### ISSUE THREAD

**Issue by mar1u5** [nextcloud/server#626]
To solve #232, #311 introduced a new icon for the tags app (which is very nice). The problem is, that the color is still not matching with the other icons in the sidebar 😁 The grey is too bright.

<img width="293" alt="tags_icon_export" src="https://cloud.githubusercontent.com/assets/19711361/17209437/50736762-54bd-11e6-970c-e71bac515d24.png">

@jancborchardt @Bugsbane @nextcloud/designers

**Comment by jancborchardt** [comment]
Ah – that’s because it should be black instead of grey :) The greying is handled via CSS. Can you change that @Bugsbane?

**Comment by Bugsbane** [comment]
I'd already adjusted the icon to a black, optimized version in my own repo, but I've also made a number of unfinished changes on my repo for another issue, so I'm not entirely sure how to do a pull request via Github just for that one file change, and not the others.

Anyone's welcome to commit the file at https://github.com/Bugsbane/server/blob/master/apps/files/img/recent.svg though

**Comment by mar1u5** [comment]
@Bugsbane I will cherry-pick your commit to another branch on my fork 😉 For the future: Fix unrelated bugs in seperate branches, so that you can commit them seperate.

**Comment by mar1u5** [comment]
Damn... We are talking about **tags** here and not about **recent**-file listing 😁 @Bugsbane 
Did I missed anything. Closed the PR because of this 😢

**Comment by Bugsbane** [comment]
Ah, sorry! I was working on both icons and got mixed up. Cherry pick these commits for a black version of the tag icon (SVG and PNG):
https://github.com/Bugsbane/server/commit/f56e5866dedf519213202c3283ed694cf436e99d
https://github.com/Bugsbane/server/commit/b41c4aa892bd641b602aff83dff7ec67e9888070

**Comment by mar1u5** [comment]
@Bugsbane THX. Please check this again. Do we need the png. Should it not be 16x16.

**Comment by Bugsbane** [comment]
*sigh* Clearly I should be sleeping instead of committing! Yes it should be 16x16px. My understanding is that the PNG's are used as a fallback on older IE's that don't support SVG. Not sure if that's still relevant, though. Anyway, here's the 16x16px version:
https://github.com/Bugsbane/server/commit/0b502af2cb66ea2476356ad282401eeabd7a991b

**Comment by mar1u5** [comment]
May I ask you to make your commit (png and svg replacing) to this branch: `fix-tags-icon` :facepunch:

**Comment by Bugsbane** [comment]
https://github.com/nextcloud/server/commit/9a9b78252f85c1e29a6879329b6850cf47a98b7d

**Comment by mar1u5** [comment]
Fixed by #764
