### ISSUE TITLE
Full quota results in zero-size documents after saving with Collabora Online

### ISSUE THREAD

**Issue by skylarmt** [nextcloud/server#6266]
### Steps to reproduce
1. Create/upload files
2. Lower user quota so that the account is over the limit
3. Edit a document in Collabora Online

### Expected behavior
Saving the document should fail because "Your storage is full, files can not be updated or synced anymore!"

### Actual behavior
The document is now a zero-byte file, which is obviously not good

### Server configuration

**Operating system**: Ubuntu 16.04.3

**Web server:** Apache 2.4

**Database:** MariaDB

**PHP version:** 7.0

**Nextcloud version:** 12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-12.0.2.zip

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - admin_notifications: 1.0.0
  - apporder: 0.4.0
  - audioplayer: 2.0.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - checksum: 0.3.5
  - circles: 0.12.4
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - defaultgroup: 0.3.0
  - drop_account: 0.0.4
  - encryption: 1.6.0
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.4
  - files_clipboard: 0.6.4
  - files_external: 1.3.0
  - files_markdown: 1.0.1
  - files_pdfviewer: 1.1.1
  - files_reader: 1.0.4
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - keeweb: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.7.0
  - metadata: 0.5.0
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ownbackup: 17.5.0
  - passman: 2.1.4
  - password_policy: 1.2.2
  - piwik: 0.3.1
  - provisioning_api: 1.2.0
  - quota_warning: 1.0.1
  - ransomware_protection: 1.0.1
  - richdocuments: 1.12.34
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - socialsharing_diaspora: 1.0.1
  - socialsharing_email: 1.0.1
  - socialsharing_facebook: 1.0.1
  - socialsharing_googleplus: 1.0.1
  - socialsharing_twitter: 1.0.1
  - spreed: 2.0.1
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - telephoneprovider: 1.0.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.1
  - twofactor_u2f: 1.3.3
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - dashboard
  - mood
  - ojsxc
  - rainloop
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "oc28jm7144k5",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "dontsell.me"
        ],
        "datadirectory": "\/var\/custdata",
        "overwrite.cli.url": "https:\/\/dontsell.me",
        "dbtype": "mysql",
        "version": "12.0.2.0",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "mail_from_address": "noreply",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "dontsell.me",
        "updater.release.channel": "stable",
        "app.mail.accounts.default": {
            "email": "%USERID%@dontsell.me",
            "imapHost": "imap.dontsell.me",
            "imapPort": 993,
            "imapUser": "%USERID%@dontsell.me",
            "imapSslMode": "ssl",
            "smtpHost": "smtp.dontsell.me",
            "smtpPort": 25,
            "smtpUser": "%USERID%@dontsell.me",
            "smtpSslMode": "ssl"
        },
        "maintenance": false
    }
}
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 55.0.2

**Operating system:** Linux Mint 18.2/Ubuntu 16.04

### Logs

No relevant errors in logs

**Comment by MorrisJobke** [comment]
This is more a problem of the richdocuments app: https://github.com/nextcloud/richdocuments

Could you open it there, so that app can properly handle this case? Thanks

cc @timar @pranavk
