### ISSUE TITLE
Active sessions in personal settings should be sorted by date of usage

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/server#6274]
### Steps to reproduce
1. log in as User
2. go to you Settings
3. view you long Activitylist

### Expected behaviour
a framed activity list because with a long activitylisting it is the configurations/information page very long, this should be a bit cleaned up and therewith more clarly/clear
maybe add a textfild for searching directly in the activitys listing over the frame..

### Actual behaviour
loooong activity listing who it is not in a frame who it should bossibility
scrolling and searching for entrys..

### Server configuration

**Operating system**:
Open Mandriva Linux 3.0
**Web server:**
Apache, latest
**Database:**
mariadb
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
12.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated
**Where did you install Nextcloud from:**
your homepage

take a look, a picture say more as 1000 words and looking on the scrollbar

![screen 00000](https://user-images.githubusercontent.com/7925717/29750950-159c11a2-8b49-11e7-9766-647cf1f1ffdc.jpg)

**Comment by MorrisJobke** [comment]
I don't get what you want to do here? We will not add an iframe to the personal settings.

**Comment by blackcrack** [comment]
this long list makes all so huge, how can it reserved ? 
An own page for activity's  ?

best regards
Blacky

**Comment by MorrisJobke** [comment]
> this long list makes all so huge, how can it resolved ?
> An own page for activity's ?

I guess all you want is, that it scrolls, but there are more ways to scroll a container than an iframe. 😉 

cc @nextcloud/designers

**Comment by MorrisJobke** [comment]
I also update the title to make this more clear.

**Comment by juliushaertl** [comment]
We don't have scroll containers for lists anywhere in our UI and I see no real advantage in doing that. Also with the new settings view of Nextcloud 13 this will be a separate site with just the list on it, so it doesn't matter how long the list on the page is.

cc @nextcloud/designers

**Comment by blackcrack** [comment]
👍 ,
👍  @juliushaertl but the overview should given.. imho .. but well if it's an own page for the activitys it's pretty well :) (but if you klick on it and "woshhh" a mega long page for the activitys.. shold make like 
the build download page (as example) at reactos, activitys from up to : 
if you insert in this the textfild : https://reactos.org/getbuilds/
"75394 - 75694"
do you become the whole builds between 75394 up to 75694 to show,
if we have the possible like this to show activitys from up to : 
02.05.2017 - 02.05.2017 

for let see the activitys from 0:00 up to 0:00 (am - pm)
or in german from 00:00 up to 24:00 from 02.05.2017
so the activitys from 24h
or 
02.05.2017 - 03.05.2017 
48h activitys

default, the actual day's activitys

as suggestion/idea

best regards
Blacky

**Comment by MorrisJobke** [comment]
That makes sense, we should just sort the recent activities first and if you need more, scroll down, because it's the last on the page.

**Comment by jancborchardt** [comment]
Yeah, of course the most recent sessions should be up top. :)

Also, can we simplify the user agent string a bit? Instead of this Mozilla blabla can we just say: `Browser` on `operating system`?

Like:
> **Firefox** on Ubuntu
> **Safari** on iPhone
> etc

**Comment by skjnldsv** [comment]
It's fixed sicne a while now.
Sessions are sorted by date of usage.
![Capture d’écran_2019-06-05_11-39-13](https://user-images.githubusercontent.com/14975046/58946598-8e0b8d80-8786-11e9-8060-8ea64eb0634d.png)
