### ISSUE TITLE
Files app: scroll bar in Chromium is very thin

### ISSUE THREAD

**Issue by milankni** [nextcloud/server#6275]
### Steps to reproduce
1. Login to NC via Chromium web browser.
2. Open Files app / folder with items list longer than the screen height
3. Try to scroll down using mouse.

### Expected behaviour
On mouse hover, show a wider scroll bar.

### Actual behaviour
It is difficult to point the mouse cursor to the scroll bar thin just 4 pixels, especially on high dpi screen (it actually is wide just about 1.2 mm or so).
![screenshot from 2017-08-27 17-45-25](https://user-images.githubusercontent.com/937861/29751608-23409efc-8b50-11e7-8464-b70f48665cea.png)

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
12.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
From 12.0

**Where did you install Nextcloud from:**
wonderfall/nextcloud docker image

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
Seems like a good starter issue to experiment with increasing the scrollbar width (a bit) on hover.

**Comment by jancborchardt** [comment]
We could even think about using the perfect-scrollbar plugin: https://noraesae.github.io/perfect-scrollbar/

- Has good simple design
- Works the same on Firefox
- Vanishes the scrollbar when you don’t move the mouse or focus
- Increases the scrollbar when you hover over it

This seems to be exactly what we want. Anyone up for trying it out @nextcloud/javascript?

**Comment by skronenwerth** [comment]
#8730
