### ISSUE TITLE
Broken instance after Update

### ISSUE THREAD

**Issue by stefan-niedermann** [nextcloud/server#6277]
### Steps to reproduce
1. Install Nextcloud 12.0.1
2. Use Updater App to update to 12.0.2
3.

### Expected behaviour
After all checkmarks are done there are two buttons for maintenance mode. Clicking "deactivate maintenance mode" should initialize the update and show blue cloudy screen

### Actual behaviour
page stays empty (completely white), server responds with HTTP 500

### Server configuration

**Operating system**: Debian

**Web server:**  Apache 2.x

**Database:** MySQL 5

**PHP version:** 5.6.31

**Nextcloud version:** former 12.0.1, now hopefully 12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** updater app

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**

Sorry, no access.

<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
This is my php error log, i notice some "owncloud" strings here, where definitifely should be nextcloud.

```
[Tue Apr 28 10:52:31 2015] [error] [client 217.xxxxxxxx] Negotiation: discovered file(s) matching request: /var/www/xxxxx/owncloud/settings/admin (None could be negotiated)., referer: http://owncloud.xxxxxindex.php/settings/admin
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
many of those:
```
{"reqId":"NYIG6x2xjNTY0jTQmoKN","level":4,"time":"2017-08-27T16:36:39+00:00","remoteAddr":"84xxx","user":"xxx","app":"webdav","method":"PROPFIND","url":"\/remote.php\/dav\/files\/stefan\/","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Message\":\"System in maintenance mode.\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/xxx\\\/htdocs\\\/xxx\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/xxx\\\/htdocs\\\/xxx\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\\\/htdocs\\\/xxx\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/xxx\\\/htdocs\\\/xxx\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(253): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/xxx\\\/htdocs\\\/xxx\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/xxx\\\/htdocs\\\/xxx\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/xxx...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/xx\\\/htdocs\\\/xxx\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":82}","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.2 (Nextcloud)","version":"12.0.1.5"}
```
</details>

#### Browser log
nothing - http 500

**Comment by stefan-niedermann** [comment]
Can i savely replace the files with the backup-files created by updater app during the update-process?

**Comment by MorrisJobke** [comment]
> Can i savely replace the files with the backup-files created by updater app during the update-process?

Yes. But as always: keep your config and data dir untouched ;)

In the provided logs nothing useful can be found.

What is in the updater.log in the data dir?

**Comment by stefan-niedermann** [comment]
i'll check. in the meantime i installed the backed up version (worked good)

**Comment by MorrisJobke** [comment]
As there is no feedback on this one here I will close it for now. If there is more, we could reopen this ticket.
