### ISSUE TITLE
Updater is not responsible

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/server#6282]
### Steps to reproduce
1. Open the web updater from administration menu on a mobile device
2. Click Update

### Expected behaviour
Updater should be usable from mobile device, left cloumn should disappear or minimize.

### Actual behaviour
The left cloumn covers more than 75% of the screen (see screenshot) in landscape mode.

### Server configuration
**Nextcloud version:** (see Nextcloud admin page) 12.0.1

**Updated from older Nextcloud (12.0.0) :**
![grafik](https://user-images.githubusercontent.com/26707476/29769000-a80707a0-8be8-11e7-9d7f-32222d120a18.png)

**Comment by MariusBluem** [comment]
You should not update via an mobile device, since if something goes wrong - you will not be able to fix this easy 😝

**Comment by dartcafe** [comment]
Hey. Trust in the updater! :-)
Maybe, but the updater appears, even if I start it on mobile devices. So it should be usable, IMHO.

**Comment by juliushaertl** [comment]
This is the server repo. Please report the issue at https://github.com/nextcloud/updater

**Comment by dartcafe** [comment]
Argghhh. Thought, it belongs to the server..... Thanks!
