### ISSUE TITLE
Using Amazon S3 'autocreate => true' is not working

### ISSUE THREAD

**Issue by KroniK907** [nextcloud/server#6289]
In attempting to figure out why primary storage for Amazon S3 is not working I stumbled upon a bug in the S3 connection code.

[The Bug is located here](https://github.com/nextcloud/server/blob/master/lib/private/Files/ObjectStore/S3ConnectionTrait.php) on lines 98-100. 

If a user wishes to create an S3 bucket via the `autocreate => true` option they must specify a region, however the `createBucket` method run on line 98 requires the region to be passed if it is not being created in the default us-east-1 region. 

[AWS Documentation Here](http://docs.aws.amazon.com/aws-sdk-php/v2/guide/service-s3.html#creating-a-bucket-in-another-region)

Simple fix is to add the following line:

`'LocationConstraint' => empty($this->params['region']) ? 'us-east-1' : $this->params['region'],`

There is zero documentation that I can find of how to get the source up and running with composer/bower/node, and since I'm a bit of a newb when it comes to large scale web projects like this, I don't really understand how to properly run the unit tests etc to verify that my code addition works as expected, so I'd rather just ask one of you guys to please fix.

**Comment by KroniK907** [comment]
Actually now that I look carefully, the `autocreate => true` argument is not even used in the S3 code. It automatically creates a new bucket if it doesn't exist, even if `autocreate => false` is set.

**Comment by skjnldsv** [comment]
cc @icewind1991 ? :)

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
