### ISSUE TITLE
gallery controls do not work when not logged on

### ISSUE THREAD

**Issue by yoe** [nextcloud/server#6290]
### Steps to reproduce
1. Place some photos in a folder (at least two)
2. Create a share link for that folder's gallery
3. Open the share link in a browser (without logging on)
4. Click on any photo in the gallery
5. Click on the "start slide show", "next", or "previous" button in the photo view

### Expected behaviour
Another photo should load

### Actual behaviour
An error is logged in the Javascript console, and the photo does not move on to the next one (see below for the error)
### Server configuration

**Operating system**:
Debian Jessie
**Web server:**
Apache
**Database:**
PostgreSQL
**PHP version:**
5.6.30+dfsg-0+deb8u1 (default version in Debian jessie)
**Nextcloud version:** (see Nextcloud admin page)
12.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 11.something
**Where did you install Nextcloud from:**
packages at repo.morph027.de
**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - checksum: 0.3.5
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_markdown: 1.0.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - previewgenerator: 1.0.6
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.1
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "ocvpdgplv3bp",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.grep.be"
        ],
        "datadirectory": "\/srv\/nextcloud",
        "overwrite.cli.url": "https:\/\/nextcloud.grep.be",
        "dbtype": "pgsql",
        "version": "12.0.0.29",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "sendmail",
        "mail_from_address": "nextcloud",
        "mail_domain": "grep.be",
        "maintenance": false,
        "theme": "", 
        "loglevel": 2 
    }, 
    "apps": { 
        "activity": { 
            "types": "filesystem", 
            "enabled": "yes", 
            "installed_version": "2.5.2" 
        }, 
        "backgroundjob": { 
            "lastjob": "7" 
        }, 
        "bookmarks": { 
            "installed_version": "0.10.1", 
            "types": "", 
            "enabled": "yes" 
        }, 
        "bruteforcesettings": { 
            "installed_version": "1.0.2", 
            "types": "", 
            "enabled": "yes"
        },
        "calendar": {
            "types": "",
            "ocsid": "168707",
            "installed_version": "1.5.3",
            "enabled": "yes"
        },
        "checksum": {
            "installed_version": "0.3.5",
            "types": "filesystem",
            "enabled": "yes"
        },
        "comments": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "1.2.0"
        },
        "contacts": {
            "installed_version": "1.5.3",
            "types": "",
            "enabled": "yes"
        },
        "core": {
            "installedat": "1493709965.7514",
            "vendor": "nextcloud",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "lastupdateResult": "{\"version\":\"12.0.2.0\",\"versionstring\":\"Nextcloud 12.0.2\",\"url\":\"https:\\\/\\\/download.nextcloud.com\\\/server\\\/prereleases\\\/nextcloud-12.0.2.zip\",\"web\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/11\\\/admin_manual\\\/maintenance\\\/upgrade.html\",\"autoupdater\":\"1\",\"signature\":\"nnONX64IyHDi5cVkFDqRL109KQKQcc3WdSZQ0+NUA3JT9r3qyzdACRRDrBj9x\\\/Mt\\nqo0jXEcYyhBS5Mj74jJLWA8g+5SXWNwZKqnhv9ho5l9cApUXML0R3Za+nrOuJHMP\\nysI7bxpunc9NT\\\/oDngtrowTeQkhmtDdff6bsNJH4FdrbIrc0hfnpHgwSQUTkYy6z\\nmt5ISybwWmN0sqn3hy3HlOfMME88x7X4TtSVDxlQW86i+eKaLcgcLdZEyHXbLBnF\\nrGvgv80yeIkazhAXsaMDcjGtivmMhwk69B40tY1pU\\\/fZxSPaMPxFVa\\\/U5m5ApVxQ\\n2nojXLE71M7e7BIZFziJYA==\"}",
            "backgroundjobs_mode": "cron",
            "lastcron": "1503987304",
            "lastupdatedat": "1503987332",
            "shareapi_default_expire_date": "yes",
            "updater.secret.created": "1496231199",
            "moveavatarsdone": "yes",
            "previewsCleanedUp": "1",
            "installed.bundles": "[\"CoreBundle\"]",
            "oc.integritycheck.checker": "[]",
            "scss.variables": "c56b91933dd57defc96e49de70e920c4"
        },
        "dav": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.3.0",
            "buildCalendarSearchIndex": "yes"
        },
        "federatedfilesharing": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.2.0"
        },
        "federation": {
            "types": "authentication",
            "enabled": "yes",
            "autoAddServers": "1",
            "installed_version": "1.2.0"
        },
        "files": {
            "types": "filesystem",
            "enabled": "yes",
            "cronjob_scan_files": "500",
            "installed_version": "1.7.2"
        },
        "files_markdown": {
            "installed_version": "1.0.1",
            "types": "",
            "enabled": "yes"
        },
        "files_pdfviewer": {
            "ocsid": "166049",
            "types": "",
            "enabled": "yes",
            "installed_version": "1.1.1"
        },
        "files_sharing": {
            "types": "filesystem",
            "enabled": "yes",
            "lookupServerEnabled": "yes",
            "installed_version": "1.4.0"
        },
        "files_texteditor": {
            "ocsid": "166051",
            "types": "",
            "enabled": "yes",
            "installed_version": "2.4.1"
        },
        "files_trashbin": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.2.0"
        },
        "files_versions": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.5.0"
        },
        "files_videoplayer": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.1.0"
        },
        "firstrunwizard": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "2.1"
        },
        "gallery": {
            "types": "",
            "enabled": "yes",
            "installed_version": "17.0.0"
        },
        "githubmergetracker": {
            "installed_version": "0.0.15",
            "types": "",
            "enabled": "no"
        },
        "logreader": {
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "types": "",
            "enabled": "yes"
        },
        "lookup_server_connector": {
            "installed_version": "1.0.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "nextcloud_announcements": {
            "types": "logging",
            "enabled": "yes",
           "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "installed_version": "1.1"
        },
        "notifications": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "2.0.0"
        },
        "oauth2": {
            "installed_version": "1.0.5",
            "types": "authentication",
            "enabled": "yes"
        },
        "password_policy": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.2.2"
        },
        "previewgenerator": {
            "installed_version": "1.0.6",
            "types": "filesystem",
            "enabled": "yes"
        },
        "provisioning_api": {
            "types": "prevent_group_restriction",
            "enabled": "yes",
            "installed_version": "1.2.0"
        },
        "richdocuments": {
            "installed_version": "1.1.24",
            "types": "prevent_group_restriction",
            "enabled": "no"
        },
        "serverinfo": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.2.0"
        },
        "sharebymail": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.2.0"
        },
        "spreed": {
            "enabled": "yes",
            "types": "prevent_group_restriction",
            "installed_version": "2.0.1"
        },
        "survey_client": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.0.0",
            "last_sent": "1503393303",
            "last_report": "{\"id\":\"ocvpdgplv3bp\",\"items\":[[\"server\",\"version\",\"12.0.0.29\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_ava
tars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"none\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"
asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"none\"],[\"server\",\"debug\",\"no\"],[\"serve
r\",\"cron\",\"cron\"],[\"php\",\"version\",\"5.6.30\"],[\"php\",\"memory_limit\",-1],[\"php\",\"max_execution_time\",0],[\"php\",\"upload_max_filesize\",20971
52],[\"database\",\"type\",\"pgsql\"],[\"database\",\"version\",\"PostgreSQL 9.4.13 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bi
t\"],[\"database\",\"size\",95760148],[\"apps\",\"lookup_server_connector\",\"1.0.0\"],[\"apps\",\"logreader\",\"2.0.0\"],[\"apps\",\"files_pdfviewer\",\"1.1.1
\"],[\"apps\",\"files_texteditor\",\"2.4.1\"],[\"apps\",\"files_videoplayer\",\"1.1.0\"],[\"apps\",\"gallery\",\"17.0.0\"],[\"apps\",\"password_policy\",\"1.2.
2\"],[\"apps\",\"federatedfilesharing\",\"1.2.0\"],[\"apps\",\"provisioning_api\",\"1.2.0\"],[\"apps\",\"serverinfo\",\"1.2.0\"],[\"apps\",\"survey_client\",\"
1.0.0\"],[\"apps\",\"twofactor_backupcodes\",\"1.1.1\"],[\"apps\",\"updatenotification\",\"1.2.0\"],[\"apps\",\"federation\",\"1.2.0\"],[\"apps\",\"files\",\"1
.7.2\"],[\"apps\",\"activity\",\"2.5.2\"],[\"apps\",\"dav\",\"1.3.0\"],[\"apps\",\"files_sharing\",\"1.4.0\"],[\"apps\",\"files_trashbin\",\"1.2.0\"],[\"apps\"
,\"files_versions\",\"1.5.0\"],[\"apps\",\"sharebymail\",\"1.2.0\"],[\"apps\",\"workflowengine\",\"1.2.0\"],[\"apps\",\"comments\",\"1.2.0\"],[\"apps\",\"first
runwizard\",\"2.1\"],[\"apps\",\"nextcloud_announcements\",\"1.1\"],[\"apps\",\"notifications\",\"2.0.0\"],[\"apps\",\"systemtags\",\"1.2.0\"],[\"apps\",\"them
ing\",\"1.3.0\"],[\"apps\",\"richdocuments\",\"disabled\"],[\"apps\",\"bookmarks\",\"0.10.1\"],[\"apps\",\"checksum\",\"0.3.5\"],[\"apps\",\"contacts\",\"1.5.3
\"],[\"apps\",\"previewgenerator\",\"1.0.6\"],[\"apps\",\"tasks\",\"0.9.5\"],[\"apps\",\"files_markdown\",\"1.0.1\"],[\"apps\",\"calendar\",\"1.5.3\"],[\"apps\
",\"githubmergetracker\",\"disabled\"],[\"apps\",\"oauth2\",\"1.0.5\"],[\"apps\",\"bruteforcesettings\",\"1.0.2\"],[\"apps\",\"spreed\",\"2.0.1\"],[\"stats\",\
"num_files\",89096],[\"stats\",\"num_users\",3],[\"stats\",\"num_storages\",7],[\"stats\",\"num_storages_local\",1],[\"stats\",\"num_storages_home\",3],[\"stat
s\",\"num_storages_other\",3],[\"stats\",\"num_comments\",0],[\"stats\",\"num_comment_markers\",0],[\"stats\",\"num_systemtags\",0],[\"stats\",\"num_systemtags
_mappings\",0],[\"files_sharing\",\"num_shares\",21],[\"files_sharing\",\"num_shares_user\",14],[\"files_sharing\",\"num_shares_groups\",0],[\"files_sharing\",
\"num_shares_link\",1],[\"files_sharing\",\"num_shares_link_no_password\",1],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_
received\",0],[\"files_sharing\",\"permissions_3_15\",1],[\"files_sharing\",\"permissions_0_31\",8],[\"files_sharing\",\"permissions_0_17\",2],[\"files_sharing
\",\"permissions_0_19\",4],[\"files_sharing\",\"permissions_4_15\",6],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}"
        },
        "systemtags": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "1.2.0"
        },
        "tasks": {
            "installed_version": "0.9.5",
            "types": "",
            "enabled": "yes"
        },
        "theming": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "1.3.0"
        },
        "twofactor_backupcodes": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.1.1"
        },
        "updatenotification": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.2.0",
            "core": "12.0.2.0",
            "calendar": "1.5.3",
            "notify_groups": "[]",
            "update_check_errors": "0",
            "checksum": "0.3.5",
            "bookmarks": "0.10.1"
        },
        "workflowengine": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.2.0"
        }
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:**
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:**
tried with at least firefox/Linux, google chrome/Linux, firefox/Android, google chrome/Android, firefox/Windows, google chrome/Windows
**Operating system:**
all
#### Web server error log
no error log entries appear
#### Nextcloud log (data/nextcloud.log)
no log entries appear
#### Browser log
<details>
<summary>Browser log</summary>
_next @ VM189 slideshowcontrols.js?v=84c7a2bb776a009e7b3ec72a62f61fd3-0:353
(anonymous) @ VM189 slideshowcontrols.js?v=84c7a2bb776a009e7b3ec72a62f61fd3-0:55
dispatch @ core.js?v=84c7a2bb776a009e7b3ec72a62f61fd3-0:3
r.handle @ core.js?v=84c7a2bb776a009e7b3ec72a62f61fd3-0:3
VM189 slideshowcontrols.js?v=84c7a2bb776a009e7b3ec72a62f61fd3-0:372 Uncaught TypeError: Cannot read property 'hideDropDown' of undefined
    at Controls._previous (VM189 slideshowcontrols.js?v=84c7a2bb776a009e7b3ec72a62f61fd3-0:372)
    at Controls.<anonymous> (VM189 slideshowcontrols.js?v=84c7a2bb776a009e7b3ec72a62f61fd3-0:55)
    at HTMLInputElement.dispatch (core.js?v=84c7a2bb776a009e7b3ec72a62f61fd3-0:3)
    at HTMLInputElement.r.handle (core.js?v=84c7a2bb776a009e7b3ec72a62f61fd3-0:3)
_previous @ VM189 slideshowcontrols.js?v=84c7a2bb776a009e7b3ec72a62f61fd3-0:372
(anonymous) @ VM189 slideshowcontrols.js?v=84c7a2bb776a009e7b3ec72a62f61fd3-0:55
dispatch @ core.js?v=84c7a2bb776a009e7b3ec72a62f61fd3-0:3
r.handle @ core.js?v=84c7a2bb776a009e7b3ec72a62f61fd3-0:3
</details>

**Comment by MorrisJobke** [comment]
This is a gallery app problem.

Looks like something like https://github.com/nextcloud/gallery/issues/286 but this is included in 12.0.2. Please search the issue tracker at https://github.com/nextcloud/gallery/issues and if there is no existing issue, please open one.

Thanks

**Comment by yoe** [comment]
Ah, but my server isn't running 12.0.2, because apparently there are no packages for 12.0.2 :-)

Upgraded through the webinterface, works now. Thanks!
