### ISSUE TITLE
Thunderbird/Lightning Events pop up after each caldav update

### ISSUE THREAD

**Issue by wenzel-k** [nextcloud/server#6291]
### Steps to reproduce
1. Import caldav calendar url to thunderbird/lightning as new calendar (network/caldav)
2. set update interval to 1 minute
3. create new event in now+1 minute

### Expected behaviour
When the alert dialog pops up and i minimize the alert window it should be hidden

### Actual behaviour
After each caldav update (every 1 minute) the window pups up again.

### Server configuration

**Operating system**:
Ubuntu Server 16
**Web server:**
latest https://github.com/nextcloud/docker image
**Database:**
sqlite
**PHP version:**
latest https://github.com/nextcloud/docker image
**Nextcloud version:** (see Nextcloud admin page)
latest https://github.com/nextcloud/docker image
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

The suggestion from [here](https://www.thunderbird-mail.de/forum/thread/76181-lightning-nextcloud-bei-jeder-kalender-synchronisation-wird-erinnerungsfenster-a/) to use path '/caldav/' instead of '/dav/' didn't help.

Thanks and best regards
Wenzel

**Comment by MorrisJobke** [comment]
cc @georgehrke

**Comment by georgehrke** [comment]
@wenzel-k Were you able to reproduce this behavior with other CalDAV servers too? 

The alarm is not triggered by the Nextcloud CalDAV server but Thunderbird decides on its own when to show alarms, so I rather think this is a bug in Thunderbird.
Did you try reporting it to Mozilla?

**Comment by wenzel-k** [comment]
After some days of living with an disabled notification i set the setting `calendar.network.multirealm` to true and the popups seem gone.

Thanks for your effort and best regards
Wenzel
