### ISSUE TITLE
Fatal Errors

### ISSUE THREAD

**Issue by doonya** [nextcloud/server#6299]
Hi,

I have this Fatals Errors

============================================================
Sabre\DAV\Exception\ServiceUnavailable: Could not open file

    /home/magpharm/public_html/cloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 85: OCA\DAV\Connector\Sabre\File->get()
    [internal function] Sabre\DAV\CorePlugin->httpGet(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /home/magpharm/public_html/cloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /home/magpharm/public_html/cloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method GET', Array)
    /home/magpharm/public_html/cloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /home/magpharm/public_html/cloud/apps/dav/appinfo/v1/webdav.php - line 71: Sabre\DAV\Server->exec()
    /home/magpharm/public_html/cloud/remote.php - line 162: require_once('/home/magpharm/...')
================================================================================================
Fatal	webdav	Sabre\DAV\Exception\Conflict: Parent node does not exist

    /home/magpharm/public_html/cloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 590: Sabre\DAV\Server->createCollection('PHYTOPHARM GAST...', Object(Sabre\DAV\MkCol))
    [internal function] Sabre\DAV\CorePlugin->httpMkcol(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /home/magpharm/public_html/cloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /home/magpharm/public_html/cloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method MKCOL', Array)
    /home/magpharm/public_html/cloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /home/magpharm/public_html/cloud/apps/dav/appinfo/v1/webdav.php - line 71: Sabre\DAV\Server->exec()
    /home/magpharm/public_html/cloud/remote.php - line 162: require_once('/home/magpharm/...')
    {main}

==============================================================================================================

Fatal	webdav	Sabre\DAV\Exception\BadRequest: expected filesize 505344 got 196608

    /home/magpharm/public_html/cloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1130: OCA\DAV\Connector\Sabre\File->put(Resource id #455)
    /home/magpharm/public_html/cloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 513: Sabre\DAV\Server->updateFile('Tr\xC3\xA9sorerie DFC...', Resource id #455, NULL)
    [internal function] Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /home/magpharm/public_html/cloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /home/magpharm/public_html/cloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method PUT', Array)
    /home/magpharm/public_html/cloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /home/magpharm/public_html/cloud/apps/dav/appinfo/v1/webdav.php - line 71: Sabre\DAV\Server->exec()
    /home/magpharm/public_html/cloud/remote.php - line 162: require_once('/home/magpharm/...')
    {main}

### General server configuration

**Operating system:** Linux dds.magpharm.com 2.6.32-642.11.1.el6.x86_64 #1 SMP Fri Nov 18 19:25:05 UTC 2016 x86_64

**Web server:** Apache/2.4.25 (Unix) OpenSSL/1.0.1e-fips mod_bwlimited/1.4 (cgi-fcgi)

**Database:** mysql 5.6.35

**PHP version:** 5.6.30
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - ereg
 - libxml
 - openssl
 - pcre
 - sqlite3
 - zlib
 - bcmath
 - calendar
 - ctype
 - curl
 - dom
 - fileinfo
 - filter
 - ftp
 - gd
 - hash
 - iconv
 - SPL
 - json
 - mbstring
 - mcrypt
 - session
 - standard
 - mysqlnd
 - mysqli
 - Phar
 - posix
 - Reflection
 - mysql
 - SimpleXML
 - sockets
 - imap
 - tidy
 - tokenizer
 - xml
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - cgi-fcgi
 - PDO
 - pdo_sqlite
 - apcu
 - pdo_mysql
 - apc
 - ionCube Loader
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.2 - 12.0.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:** YOUR ANSWER HERE

**Where did you install Nextcloud from:**  YOUR ANSWER HERE

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** YOUR ANSWER HERE (LDAP/ActiveDirectory/Webdav/...)

<details>
        <summary>Signing status</summary>

```
{
    "core": {
        "INVALID_HASH": {
            ".htaccess": {
                "expected": "da8e0075f23227b107fc705aa1b20378107d3a1c195d96ed13e5f4f25c38d6c660aab75be183ae5799a4ff7eae0ea739a14c944430ee8bb9e9a824235aa136eb",
                "current": "fd2dfca2e091ac8aa61c6f93296d7941739096102e7ba8ce32bf9b975fc5737a62bbe8bece57b89fb38740c6d47f3514226d71f1227fa5a7afd17a1757c7b888"
            }
        }
    }
}
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - admin_notifications: 1.0.0
 - announcementcenter: 3.1.0
 - bookmarks: 0.10.1
 - comments: 1.2.0
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - rainloop: 5.0.1
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_email: 1.0.1
 - socialsharing_facebook: 1.0.1
 - socialsharing_twitter: 1.0.1
 - survey_client: 1.0.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - bruteforcesettings
 - encryption
 - federation
 - files_automatedtagging
 - files_external
 - gallery
 - groupfolders
 - notes
 - ojsxc
 - systemtags
 - tasks
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "ocko7ozbgi0q",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.magpharm.com"
    ],
    "datadirectory": "\/home\/magpharm\/nextclouddata",
    "overwrite.cli.url": "https:\/\/cloud.magpharm.com",
    "dbtype": "mysql",
    "version": "12.0.2.0",
    "dbname": "magpharm_next223",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "loglevel": 3,
    "maintenance": false,
    "ldapIgnoreNamingRules": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "asset-pipeline.enabled": true,
    "theme": "",
    "enable_avatars": true,
    "filelocking.enabled": true,
    "filelocking.ttl": 3600,
    "mail_smtpmode": "smtp",
    "mail_from_address": "support",
    "mail_domain": "magpharm.com",
    "mail_smtphost": "mail.magpharm.com",
    "mail_smtpport": "26",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "check_for_working_webdav": false,
    "debug": true,
    "trashbin_retention_obligation": "auto",
    "updater.release.channel": "stable",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:54.0) Gecko/20100101 Firefox/54.0

**Operating system:** YOUR ANSWER HERE

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment]
Hi, please reopen a new issue if this is still happening:
1. Fill out the steps to reproduce
2. provide also any surrounding log messages from the log file
