### ISSUE TITLE
Optimizing the new login screen for light themes

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/server#6305]
Comming from #6303

### Expected behaviour
Darken elements on the page

### Actual behaviour
Some elements are not visible (texts, icons, etc.)

### Server configuration

**Nextcloud version:** 13.0.0 alpha Build:2017-08-29T22:01:17+00:00

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

The new login screen ist great, but maybe some enhancement is to be done, if a light theme is choosen. See examples below.

See examples:
![black_theme](https://user-images.githubusercontent.com/26707476/29857862-100e9f16-8d5b-11e7-96c4-50bc146d4280.png)
![white_theme](https://user-images.githubusercontent.com/26707476/29857865-14a0af92-8d5b-11e7-90af-ba1da870df65.png)
![yellow_theme](https://user-images.githubusercontent.com/26707476/29860328-18b248ce-8d66-11e7-89e3-c567798cd72f.png)

A suggestion (didn't get the background image to invert):
![white_theme_invert_a](https://user-images.githubusercontent.com/26707476/29860384-43f538f2-8d66-11e7-96c5-52180abb9d56.png)
Or maybe the input fields should just get a border instead of darkening them.

**Comment by juliushaertl** [comment]
Fix for that is also in https://github.com/nextcloud/server/pull/6082 Please help reviewing.

**Comment by juliushaertl** [comment]
Fixes with #6082
