### ISSUE TITLE
Email notification delay should have an option to be shortened

### ISSUE THREAD

**Issue by angerized** [nextcloud/server#6306]
### Steps to reproduce
1. Create a share with another user
2. Recipient is informed of this way too late

### Expected behaviour
At the very least shorten the notification delay (maybe add a 15 minutes option).
Idealy recipients should be informed instantly.

### Actual behaviour
Recipient is informed over an hour after the share has been established.

### Server configuration
Debian 9 64 bits
Nextcloud 12.0.2 fresh install
MariaDB 10.1.26
PHP 7

**Comment by angerized** [comment]
On [this](https://help.nextcloud.com/t/email-activity-notification/3543/5) page @Rello suggested to open a pull request with other options. But i'm not sure how to do this. But I suppose the code coud look something like that:

email_batch_time = 3600;
		if ($notify_setting_batchtime === UserSettings::EMAIL_SEND_FIFTEENMINUTES) {
			$email_batch_time = 900;
                } else if ($notify_setting_batchtime === UserSettings::EMAIL_SEND_DAILY) {
			$email_batch_time = 3600 * 24;
		} else if ($notify_setting_batchtime === UserSettings::EMAIL_SEND_WEEKLY) {
			$email_batch_time = 3600 * 24 * 7;
                }

**Comment by MorrisJobke** [comment]
This will be fixed in 12.0.3 There will be a dedicated sharing email.
