### ISSUE TITLE
Exclude .gz files from integrity check

### ISSUE THREAD

**Issue by Loki3000** [nextcloud/server#6310]
Nginx server has gzip_static module. That module suppose that beside of text files placed it's pregziped versions.
http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html
So after install or update NC I generate gziped versions of css, js, htm etc. And integrity check reports that it's extra files.

**Comment by MorrisJobke** [comment]
I don't like the idea that the web server places some new files into the code base. @LukasReschke Opinion on that?

@Loki3000 COuldn't the webserver store this somewhere else?

**Comment by rullzer** [comment]
I have to agree with @MorrisJobke here. Nextcloud is writen in php and extra files are a potential risks.

**Comment by Loki3000** [comment]
@MorrisJobke As I see, there is no way to put this files in another place.
I agree that foreign files in codebase is not to good. So I could offer some possible ways:
1. Exclude some types from integrity check. Bad way, I agree.
1a. Allow to admin to exclude some types from integrity check. A bit more secure, but almost the same as 1.
2. You can provide gzipped versions with source code. Like you make minifyed versions of js files.
3. Maybe allow to admin to make it's own integrity list.
3a. Allow to admin add to integrity list extra files (I dont know how to be with signing)
4. Check that extra files not executable and not writable for web server (it's also "half-solution" but it's may useful with 1.)

**Comment by MorrisJobke** [comment]
> You can provide gzipped versions with source code. Like you make minifyed versions of js files.

We don't do. We generate them on the server and cache them in the data directory.



> Maybe allow to admin to make it's own integrity list.

Then the whole point of the integrity check is useless. It's the "Nextcloud contributors signed that the files are not modified by a 3rdparty".

**Comment by Loki3000** [comment]
You can still checks source code of nextcloud and server admin can control extra files signed with his own sign. Other solution it's just disable integrity checks.

**Comment by MorrisJobke** [comment]
> You can still checks source code of nextcloud and server admin can control extra files signed with his own sign. Other solution it's just disable integrity checks.

Correct. So as of now I would say: disable integrity checks. Because adding another config flag doesn't really help here a lot.

**Comment by MorrisJobke** [comment]
And you seem to be sure about having it properly deployed anyways. The integrity check is there to have an easy way to verify that there are no leftovers from previous installations and make trouble shooting easy. So we still recommend to leave it enabled, but for this specific use case: disable it and run it only if you want to report issues and are requested to send the integrity check status.

**Comment by bcutter** [comment]
What about the ‘integrity.excluded.files’ array in config.php the Ownclouders have?
(just migrated to Nextcloud a few days ago and I´m missing this option quite well)

**Comment by Glandos** [comment]
For small installations without caching servers, like mine, it is really helpful to have pre-gzipped files. Of course, I can set a complex routing in nginx to serve those files from another path. But on the other hand, I think that gzip files are really harmless. In the best security point-of-view, if a file has the same filename with the `.gz` suffix as a valid file, plus it has the gzip magic number, it could be excluded from the `EXTRA_FILE` report.
I do understant it is a lot of work though. Both from the developer side and the execution time point of view.
