### ISSUE TITLE
Ubuntu client still has mentions of ownCloud

### ISSUE THREAD

**Issue by michaeldg** [nextcloud/server#6312]
Hi,

The nextCloud client in Linux (I run Ubuntu Gnome) produces some overlays. The overlays still show ownCloud, for example the overlay when there is a sync conflict.

I am using mailinabox, where they have nicely integrated nextcloud now. I don't know which exact version I am running but it could be slightly old.

Let me know if you need a screenshot.

Thanks,
Michaël

**Comment by MorrisJobke** [comment]
Please provide screenshots and steps how to reproduce. And report it in the client_theming repo: https://github.com/nextcloud/client_theming

**Comment by MorrisJobke** [comment]
Thanks for the report anyway :)

**Comment by michaeldg** [comment]
Allright, thank you for the quick response! It's a bit difficult to catch in a screenshot as the notification only appears a couple of seconds. Also thank you for pointing me to the right repo.

Keep up the good work!
