### ISSUE TITLE
'occ maintenance:install' sets 'overwrite.cli.url' to 'http://localhost'

### ISSUE THREAD

**Issue by mejo-** [nextcloud/server#6313]
Hello,

for some reason, `overwrite.cli.url` is always set to `http://localhost` after manual installation of Nextcloud via `occ maintennce:install`.

### Steps to reproduce
1. Download nextcloud-12.0.2.zip, unzip and move into folder
2. php occ maintenance:install --database=mysql --database-name=nextcloud --database-user=nextcloud --database-pass=... --admin-pass=...
3. cat config/config.php

```
[...]
  'overwrite.cli.url' => 'http://localhost',
[...]
```

### Expected behaviour
`overwrite.cli.url` should not be set

### Server configuration

**Operating system:** Debian 9.0 Stretch
**Web server:** Apache2
**Database:** MariaDB
**PHP version:** 7.0.19
**Nextcloud version:** 12.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install
**Where did you install Nextcloud from:** zip file

**Comment by Tsuroerusu** [comment]
I just recently ran into this with Nextcloud 13.0.1, and in addition the trusted domain was also set to "localhost". I would suggest that a simple parameter for the maintenance:install sub-command to specify the hostname be added.

**Comment by danielkesselberg** [comment]
Ref #10678 (

**Comment by minils** [comment]
> This needs to be fixed asap as it breaks the Nextloud 14 `occ` installation. You can't set pretty URLs because it expects a trailing slash in the end. I fixed it in the VM but would be nice with a fix in the server as well.

After upgrading to NC14 I tried to enable pretty URLs.
OMG took me some time to figure that out. The only problem was the missing `/` at the end of the url.
This is even wrong in the [manual](https://docs.nextcloud.com/server/14/admin_manual/installation/source_installation.html?highlight=pretty#pretty-urls-label)

**Comment by danielkesselberg** [comment]
@MorrisJobke has suggested another way here https://github.com/nextcloud/server/pull/11602#issuecomment-426773346 

Another approach could be by setting an environment var `NC_overwrite.cli.url`
