### ISSUE TITLE
very slow downloads via weblink

### ISSUE THREAD

**Issue by jiml8** [nextcloud/server#6314]
<!--
I have an instance of nextcloud that I use as a repository for downloads, and the downloads appear to be going very very slow. A 56 MB download just took 15 minutes to complete.

The connection is wired cable and capable of at least 10 Mb/sec (not sure exactly, but it will do that quite easily).

The hardware is a quad core phenom-II processor with 16 GB RAM connected through a 1 Gb ethernet connection. No other devices on the LAN experience similar issues, and the NAS that hosts the nextcloud instance also does not experience such an issue when downloads are done without using Nextcloud.

What is the solution?

Nextcloud version (eg, 10.0.2):11.03
Operating system and version (eg, Ubuntu 16.04): NAS4Free 11.0.0.4 (FreeBSD 11)
Apache or nginx version (eg, Apache 2.4.25): lighttpd 1.4.45
PHP version (eg, 5.6): 7.1.5
Is this the first time you’ve seen this error?: no

Can you reliably replicate it? (If so, please outline steps): yes
Push file to nextcloud server via a lan-local webdav connection
establish a share link
send share link to desired downloader
Download from elsewhere on the internet using either a web browser or curl
The issue you are facing:

The output of your Nextcloud log in Admin > Logging:

No logs available in the relevant time frame. Literally no entries.

The output of your config.php file in /path/to/nextcloud (make sure you remove any identifiable information!):
<?php $CONFIG = array ( 'instanceid' => (removed), 'passwordsalt' => (removed), 'secret' => (removed), 'trashbin_retention_obligation' => 'auto', 'trusted_domains' => array ( 0 => (removed) 1 => (removed) ), 'datadirectory' => '/mnt/VD01/owncloud_data', 'filesystem_check_changes' => 1, 'overwrite.cli.url' => (removed), 'dbtype' => 'sqlite3', 'version' => '11.0.3.2', 'installed' => true, 'forcessl' => true, 'memcache.local' => '\\OC\\Memcache\\APCu', 'mail_from_address' => (removed)', 'mail_smtpmode' => 'smtp', 'mail_smtpsecure' => 'ssl', 'mail_domain' => '(removed)', 'mail_smtpauthtype' => 'PLAIN', 'mail_smtpauth' => 1, 'mail_smtphost' => (removed)', 'mail_smtpport' => '465', 'mail_smtpname' =>(removed), 'mail_smtppassword' => (removed), 'loglevel' => 0, 'theme' => '', 'maintenance' => false, ); The output of your Apache/nginx/system log in `/var/log/____`: --- Remember, this information may be requested if it isn't supplied; for fastest response please provide as much as you can :heart: Feel free to use a pastebin service, otherwise log files can be indented with 4 spaces on each line to present them in a friendlier way on the forum.

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from older Nextcloud

**Where did you install Nextcloud from:** github

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - apporder: 0.3.3
  - audioplayer: 2.0.2
  - bookmarks: 0.10.1
  - comments: 1.1.0
  - contacts: 1.5.3
  - dav: 1.1.1
  - direct_menu: 0.10.2
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_mv: 0.8.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - ownbackup: 17.5.0
  - ownnote: 1.08
  - passman: 2.1.4
  - password_policy: 1.1.0
  - previewgenerator: 1.0.6
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - weather: 1.5.0
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - passwords
  - user_external
  - user_ldap
  - user_saml

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

yes  local/mnt/VD01/BitTorrent_Sync/laptop local/mnt/VD01/Videos /mnt/VD01/BitTorrent_Sync/Will
**Are you using encryption:** yes/no no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
webdav

### Client configuration
**Browser:**
either Safare or cURL
**Operating system:**
OSX
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
none
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by jiml8** [comment]
Well, I spent some time composing this, but apparently github thought I was a spambot, so when I submitted it, it vanished.

So I might get around to composing it again eventually.  But right now I am too pissed off.

**Comment by MorrisJobke** [comment]
> Apache or nginx version (eg, Apache 2.4.25): lighttpd 1.4.45

Could you try with apache or nginx? Beside that you could check out what a potential bottleneck is, by running the download with a profiler attached. Something like https://blackfire.io - beside that we don't see any conceptual problems in our code base.

**Comment by jiml8** [comment]
Nas4free is a packaged FreeBSD-based distribution intended for embedded installs.  There is no capability for this package to run nginx or apache; it runs lighttpd.  

My NAS, running this package, is basically an appliance, lacking any of the support required for general purpose computing.

While it would be possible to install (most probably) nginx, that would represent a fairly significant development/setup effort.

**Comment by MorrisJobke** [comment]
As we don't officially support Lighttpd I will close this ticket here. We can't see performance issues comparing the public share and authenticated way of downloading. Maybe as others that have use the same NAS4Free package to compare with their experiences. Otherwise I can only send you over to the forums to ask for help: https://help.nextcloud.com

This is a bug tracker to help developers get an overview of reproducible stuff that does not work as it should in our software.

Thanks
