### ISSUE TITLE
RSS is not updating anymore on Outlook restart

### ISSUE THREAD

**Issue by t347s** [nextcloud/server#6318]
### Steps to reproduce
1. Activity app > Settings > Enable RSS
2. Copy RSS generated link into Outlook
3. After is added the RSS flux is working until Outlook is restarted, on reopen the flux is not updated anymore and Outlook gives an error
4. Self-signed certificate
5. LDAP/AD integration

### Expected behaviour
The RSS should work everytime for a fast user files and folder changes knowledge 

### Actual behaviour
If Outlook is restarted is not updating anymore, the errors are:
Task 'RSS Feeds' reported error (0x800C0019) : 'Synchronization to RSS Feed:"https://subdomain.domain.ext/apps/activity/rss.php?token=oC9Gnj4T5PdM8PcKwLKvAcUSW3hotl" has failed. Outlook cannot download the RSS content from https://subdomain.domain.ext/apps/activity/rss.php?token=oC9Gnj4T5PdM8PcKwLKvAcUSW3hotl because of a problem connecting to the server.'

Task 'RSS Feeds' reported error (0x800C0019) : 'Unknown Error 0x800C0019'

#### What i tried
- accept certificate - YES - no result
- install certificate - YES - no result
- try multiple browsers/rss agregators - Firefox plugins, Chrome plugins - no result
- cron is running - YES

### General server configuration

**Operating system:** Linux nextcloud 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.19

**PHP version:** 7.0.22-0ubuntu0.16.04.1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - apache2handler
 - redis
 - mysqlnd
 - PDO
 - xml
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - iconv
 - imap
 - intl
 - json
 - ldap
 - exif
 - mcrypt
 - mysqli
 - pdo_mysql
 - pdo_pgsql
 - pdo_sqlite
 - pgsql
 - Phar
 - posix
 - readline
 - shmop
 - SimpleXML
 - smbclient
 - sockets
 - sqlite3
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - libsmbclient
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.2 - 12.0.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 12.0.0 to 12.0.1 to 12.0.2

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - admin_notifications: 1.0.0
 - announcementcenter: 3.1.0
 - apporder: 0.4.0
 - calendar: 1.5.3
 - comments: 1.2.0
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_accesscontrol: 1.2.4
 - files_clipboard: 0.6.4
 - files_downloadactivity: 1.1.1
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - gallery: 17.0.0
 - groupfolders: 1.1.0
 - impersonate: 1.0.1
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - news: 11.0.5
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - previewgenerator: 1.0.6
 - provisioning_api: 1.2.0
 - quota_warning: 1.1.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_email: 1.0.1
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - user_ldap: 1.2.1
 - workflowengine: 1.2.0
 - workin2gether: 0.9.6
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - contacts
 - dashboard
 - defaultgroup
 - encryption
 - files_external
 - files_retention
 - firstrunwizard
 - user_external
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.1; rv:55.0) Gecko/20100101 Firefox/55.0

**Operating system:** Windows

**Comment by MorrisJobke** [comment]
This is an issue with the activity app. Please report it in it's bug tracker: https://github.com/nextcloud/activity/issues

Thanks

cc @nickvergessen

**Comment by t347s** [comment]
In this case maybe "Issue reporting" app should give a corect link to every "Affected component" selected, beacause i made the corect selection (Activity) and that i ended here. And message "Issue to long to send over to GitHub" is irelevant when there is no posibility to connect with a github account.

**Comment by j-ed** [comment]
@t347s -> https://github.com/nextcloud/activity

**Comment by t347s** [comment]
Thank you j-ed,
I done that already, what i mean is that should be some modification in "Issue reporting" app. Thats all.

Have a nice day!

**Comment by MorrisJobke** [comment]
> In this case maybe "Issue reporting" app should give a corect link to every "Affected component" selected, beacause i made the corect selection (Activity) and that i ended here. And message "Issue to long to send over to GitHub" is irelevant when there is no posibility to connect with a github account.

cc @juliushaertl for feedback on the issue template app.

@t347s Sorry for the inconvenience. We try to improve here. :) Thanks for reporting it anyways 👍

**Comment by juliushaertl** [comment]
> In this case maybe "Issue reporting" app should give a corect link to every "Affected component" selected, beacause i made the corect selection (Activity) and that i ended here. And message "Issue to long to send over to GitHub" is irelevant when there is no posibility to connect with a github account.

Thanks for the hint with the issue link. I've created a patch to fix that in issuetemplate: https://github.com/nextcloud/issuetemplate/pull/30 We can transmit issue content to Github via HTTP GET parameter but that is limited in lenght. Anyhow I plan to add submission via the GitHub API in the future: https://github.com/nextcloud/issuetemplate/issues/10
