### ISSUE TITLE
507 insufficient storage when syncing a specific calendar after upgrade 11 -> 12

### ISSUE THREAD

**Issue by danielbierstedt** [nextcloud/server#6321]
After upgrading from 11 -> 12 using the web browser, I get a 507 error when syncing a specific calendar. A bunch of other calendars is OK. The message appears on my android, the sync software is DAVdroid by bitfire.at.

### Steps to reproduce
1. configure calendar sync using DAVdroid
2. wait for it
3.

### Expected behaviour
Sync without any message

### Actual behaviour
Sync works, but gives error messages at the client and on the server

### Server configuration

**Operating system**:
Synology NAS

**Web server:**

**Database:**
MariaDB

**PHP version:**
5.7

**Nextcloud version:** (see Nextcloud admin page)
12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 11.0.4

**Where did you install Nextcloud from:**
gzip

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>
Activity
Collaborative tags
Comments
Deleted files
File sharing
First run wizard
Gallery
Log Reader
Monitoring
Nextcloud announcements
Notifications
Password policy
Share by mail
Text editor
Theming
Update notification
Usage survey
Versions
Brute-force-settings
Calendar
Contacts

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
![nextcloud calendar sync error](https://user-images.githubusercontent.com/9999431/29925273-13d6d1da-8e60-11e7-9005-2305e8fc3b64.PNG)
[DAVdroid log.txt](https://github.com/nextcloud/server/files/1267168/DAVdroid.log.txt)

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
cc @georgehrke

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
