### ISSUE TITLE
User provisioning API Unauthorized - HTTP PUT request

### ISSUE THREAD

**Issue by FredHUET** [nextcloud/server#6324]
I read this closed issue : 
[https://github.com/nextcloud/server/issues/4158](url)

I have same issue on Nextcloud 12.0.0 and 12.0.2 

I can adduser, delete user but can't modify.

i try :
`curl -X PUT -v -H "OCS-APIRequest: true" -H "Content-Type: application/x-www-form-urlencoded" -F 'key="email"' -F 'value="Fred9876@provider.eu"' -u 'ADMINLOG:AdminPassword' https://url_nextcloud.eu/ocs/v1.php/cloud/users/Fred9876`
or v2
`curl -X PUT -v -H "OCS-APIRequest: true" -H "Content-Type: application/x-www-form-urlencoded" -F 'key="email"' -F 'value="Fred9876@provider.eu"' -u 'ADMINLOG:AdminPassword' https://url_nextcloud.eu/ocs/v2.php/cloud/users/Fred9876`

and i m getting :
`< HTTP/1.1 401 Unauthorized`

 ```
<?xml version="1.0"?>
 <ocs>
  <meta>
   <status>failure</status>
   <statuscode>997</statuscode>
   <message></message>
   <totalitems></totalitems>
   <itemsperpage></itemsperpage>
  </meta>
  <data/>
 </ocs>
```

I use docker image [https://hub.docker.com/r/wonderfall/nextcloud/](url)
Based on Alpine Linux.
Bundled with nginx and PHP 7.1

**Database:**
mariaBD

**PHP version:**
7.1

**Nextcloud version:** (see Nextcloud admin page)
12.0.2

**fresh install:**
Yes

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**Comment by rullzer** [comment]
Please try:

```
curl -X PUT -v -H "OCS-APIRequest: true" -d 'key=email' -d 'value=Fred9876@provider.eu' -u 'admin:admin' http://localhost/ocs/v1.php/cloud/users/user0
```

**Comment by FredHUET** [comment]
thank you very much :+1: :1st_place_medal: 
I've done so many trials in the last few days.
So, I went to CURL (which I do not know well).

Now I have only to translate in my language
