### ISSUE TITLE
After installation via CLI it says "ownCloud was succesfully installed"

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#633]
### Steps to reproduce
1. Install via CLI (occ)

### Expected behaviour
It should say that Nextcloud was successfully installed.

### Actual behaviour
It still says ownCloud

Don't know wich file this is in so that's why I haven't made a PR:

**Comment by juliushaertl** [comment]
@enoch85  take a look at core/Command/Maintenance/Install.php

Would be great if you create a pull request for that.
