### ISSUE TITLE
Undefined offset: 2

### ISSUE THREAD

**Issue by mikshepard** [nextcloud/server#6335]
### Steps to reproduce
1. Create External Storage mount (using "Local" mount in my case)
2. Set "Folder name" mountpoint to root "/"
3. Access External Storage folder in Nextcloud

### Actual behaviour
Folder contents can be viewed as expected, but logs show error with every access:

`Undefined offset: 2 at /var/www/nextcloud/apps/files_external/lib/Lib/Api.php#42`

[Here is commit](https://github.com/nextcloud/server/pull/3438) for using root as the mountpoint of an External Storage, if it helps.

### Server configuration

**Operating system**:
Debian Jessie

**Web server:**
Apache 2.4.10

**Database:**
MySQL 5.7.19

**PHP version:**
PHP 5.7.19

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
Source tarball

**Are you using external storage, if yes which one:** local/smb/sftp/...
Local

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

### Client configuration
**Browser:**
Opera/Firefox/Vivaldi

**Operating system:**
Windows 7

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"ZMOJj7hsiolJ3Wochbdo","level":3,"time":"2017-09-01T10:16:09-05:00","remoteAddr":"X.X.X.X","user":"admin","app":"PHP","method":"GET","url":"\/ocs\/v1.php\/apps\/files_external\/api\/v1\/mounts?format=json","message":"Undefined offset: 2 at \/var\/www\/nextcloud\/apps\/files_external\/lib\/Lib\/Api.php#42","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/60.0.3112.113 Safari\/537.36 Vivaldi\/1.93.947.3","version":"12.0.2.0"}"
```
</details>

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by icewind1991** [comment]
@mikshepard can you verify if https://github.com/nextcloud/server/pull/6574 fixes the problem for you

**Comment by mikshepard** [comment]
Yes, applied the patch 24 hours ago, logs are clean.  This seems to have resolved the issue.  Thank you!!
