### ISSUE TITLE
6GB upload ends with corrupted 4294967295 Bytes file

### ISSUE THREAD

**Issue by alexhass** [nextcloud/server#6338]
### Steps to reproduce
0. Configure upload limit to 10GB in nextcloud admin area
1. Upload a 6GB ZIP file
2. Upload finishs at 4294967295 Bytes
3. File is corrupted

### Expected behaviour
The file must not corrupted

### Actual behaviour
The ZIP is corrupted

### Server configuration

**Operating system**: Debian 9.1

**Web server:** Apache 2.4

**Database:** MariaDB

**PHP version:** 7.0.20 (x64)

**Nextcloud version:** 12.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 12.1

### Client configuration
**Browser:** Internet Explorer 11

**Operating system:** Windows

#### Web server error log
<details>
<summary>Web server error log</summary>

```
111.222.333.444 - uTOzjqvEa8lGI6O [01/Sep/2017:13:39:16 +0200] "PUT /public.php/webdav/foo.zip HTTP/1.1" 400 1414 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"d2XlL5dSZwxDvelrK1Iy","level":4,"time":"2017-09-01T11:39:39+00:00","remoteAddr":"111.222.333.444","user":"--","app":"webdav","method":"PUT","url":"\/public.php\/webdav\/foo.zip","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Message\":\"expected filesize 4294967295 got 79953920\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/nextcloud\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(151): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #97)\\n#1 \\\/srv\\\/www\\\/nextcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1096): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('foo.zip', Resource id #97)\\n#2 \\\/srv\\\/www\\\/nextcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('foo.zip', Resource id #97, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/srv\\\/www\\\/nextcloud\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/srv\\\/www\\\/nextcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/srv\\\/www\\\/nextcloud\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/srv\\\/www\\\/nextcloud\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/publicwebdav.php(107): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/srv\\\/www\\\/nextcloud\\\/html\\\/public.php(76): require_once('\\\/srv\\\/www\\\/nextcl...')\\n#9 {main}\",\"File\":\"\\\/srv\\\/www\\\/nextcloud\\\/html\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":151}","userAgent":"Mozilla\/5.0 (Windows NT 6.1; WOW64; Trident\/7.0; rv:11.0) like Gecko","version":"12.0.2.0"}
```
</details>

**Comment by MorrisJobke** [comment]
> expected filesize 4294967295 got 79953920

@icewind1991 There is this weird error message again. Maybe it's not only a problem of the network but of the actual PHP configuration?

cc @rullzer

**Comment by MorrisJobke** [comment]
ref #3852

**Comment by yamlfd** [comment]
But I configured php upload limit to 10gb?

What may cause this in php? I can check the config than...

**Comment by GetBoz** [comment]
I observe the same beahavour with this browser. And it's not new. I use encryption app.

Maybe it's because of the upload limit of IE11 ?
https://blogs.msdn.microsoft.com/ieinternals/2011/03/10/file-upload-and-download-limits/

Today, is Nextcloud designed to be able to upload >4GB files with IE11? Is the FileAPI used with IE11(see link) ?
At least, there should be something to avoid IE11 users to upload files larger than 4GB.

**Comment by kesselb** [comment]
Ref https://github.com/nextcloud/server/issues/15095

mod reqtimeout could be responsible for this error.

**Comment by skjnldsv** [comment]
Please don't use IE.
see https://github.com/nextcloud/server/issues/20855

**Comment by alexhass** [comment]
At least, there should be something to avoid IE11 users to upload files larger than 4GB.

**Comment by kesselb** [comment]
FYI: https://github.com/nextcloud/server/issues/12321

The log provided in the first post shows a request to a public share hence the reference to the other issue. I hope that at some point we will use chunks for file drops as well. Right now chunks are only used for users logged in.
