### ISSUE TITLE
'occ config:system:set' adds quotes around boolean values in config

### ISSUE THREAD

**Issue by quenenni** [nextcloud/server#6345]
### Steps to reproduce
1. sudo -u www-data php occ config:system:set appstoreenabled --value=false

### Expected behaviour
```
$CONFIG = array (
  ...
  'appstoreenabled' => false,

(without quotes around false)
```

### Actual behaviour
```
$CONFIG = array (
  ...
  'appstoreenabled' => 'false',

(with quotes around false)
```

With the quotes around false or true, it's not working as intended.
'false' -> appstore page shows all the cats in the left column.
false -> appstore page doesn't shows all the cats in the left column.

### Server configuration

**Operating system**: 
Debian  Stretch

**Web server:**
Nginx

**Database:**
MariaDb

**PHP version:**
PHP 7.0.19-1 (cli) (built: May 11 2017 14:04:47) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.19-1, Copyright (c) 1999-2017, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 12.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Both

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.3
  - checksum: 0.3.5
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_downloadactivity: 1.1.1
  - files_pdfviewer: 1.1.1
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - groupfolders: 1.1.0
  - lookup_server_connector: 1.0.0
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ownpad: 0.5.10
  - passman: 2.1.4
  - password_policy: 1.2.2
  - polls: 0.7.3
  - provisioning_api: 1.2.0
  - quota_warning: 1.1.0
  - ransomware_protection: 1.0.2
  - richdocuments: 1.12.34
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.1
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - files_external
  - firstrunwizard
  - impersonate
  - user_external
```
</details>

**Comment by quenenni** [comment]
I tested on the maintenance param, and it doesn't work either:
```
sudo -u www-data php occ config:system:set maintenance --value=true
Nextcloud is in maintenance mode - no app have been loaded

System config value maintenance set to string true
```
```
sudo -u www-data php occ config:system:set maintenance --value=false
Nextcloud is in maintenance mode - no app have been loaded

System config value maintenance set to string false
```

**Comment by juliushaertl** [comment]
Please read the documentation for occ: https://docs.nextcloud.com/server/12/admin_manual/configuration_server/occ_command.html#setting-a-single-configuration-value

Using the flag `--type=boolean` should fix your problem.
