### ISSUE TITLE
Cannot enable  External storage support

### ISSUE THREAD

**Issue by zhbbupt** [nextcloud/server#6347]
### Steps to reproduce
1. login 
2. open apps
3. enable External storage support

### Expected behaviour
enable External storage support

### Actual behaviour
get error and can not start this app

### Server configuration

**Operating system**: ubuntu mate 16.04

**Web server:** nginx

**Database:** sqlite

**PHP version:** php7.0

**Nextcloud version:** (see Nextcloud admin page) any version

**Updated from an older Nextcloud/ownCloud or fresh install:**fresh install

**Where did you install Nextcloud from:**manual install

**Comment by tflidd** [comment]
> get error and can not start this app

If you don't tell us the error and if you don't give your more details from your logfiles, it will be impossible to help you.
