### ISSUE TITLE
Include a timepicker into server

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/server#6348]
I think it would be reasonable to also have a timepicker similar to the datepicker directly in server. A timepicker is used in multiple apps, such as @nextcloud/calendar, @nextcloud/deck and @nextcloud/tasks and currently looks different in all three apps. Also, the timepicker https://github.com/fgelinas/timepicker currently used in these apps has not been updated for nearly 4 years and should therefore be replaced.

Calendar:
![screenshot-2017-9-3 kalender - nextcloud](https://user-images.githubusercontent.com/2496460/30002317-8af5dc96-90a6-11e7-864f-75af883f71a0.png)

Tasks:
![screenshot-2017-9-3 aufgaben - nextcloud](https://user-images.githubusercontent.com/2496460/30002319-91796c18-90a6-11e7-83e6-77c275d84b1c.png)

Hence, I think it would be a good idea to have a timepicker in server in order to have a maintained one that looks equal in all apps, especially with the redesigned datepicker https://github.com/nextcloud/server/pull/5713.

What do you think @nextcloud/designers ?

**Comment by juliushaertl** [comment]
It would absolutely make sense to have components like that in the server. @raimund-schluessler Do you have any suggestion of an alternative timepicker library? I searched a bit when integrating it into deck, but did not came up with something nice, so i ended up using the outdated one as well.

**Comment by dartcafe** [comment]
And there ist another one in the polls app. Having a server wide default option would be a good idea.

![grafik](https://user-images.githubusercontent.com/26707476/30004887-1d8a9030-90d7-11e7-80b2-a4028f7beec4.png)

**Comment by tcitworld** [comment]
At some point it would be nice to detect if the browser offers a native datetime picker : https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

**Comment by georgehrke** [comment]
Eventually we should definitely use the HTML5 inputs, but right now the implementation is still very rudimentary. Speaking about Chromium 61 on macOS, it offers a really bad UX.

- It doesn't actually offer a time selector although its datetime
- If I use the cursor keys to go from 12h to 1h it doesn't toggle AM/PM
- etc ...

![ead5e2d0-f331-421e-aa11-632cb446abfb](https://user-images.githubusercontent.com/1250540/30004985-10122042-90d9-11e7-90c3-823fbe1bb707.jpg)

**Comment by dartcafe** [comment]
Seems to be quite flexible. 
http://amsul.ca/pickadate.js/

**Comment by tcitworld** [comment]
Android support is just fine though.

**Comment by juliushaertl** [comment]
> Seems to be quite flexible.
> http://amsul.ca/pickadate.js/

That also seems to be unmaintained at the moment.

**Comment by pixelipo** [comment]
Support for `datetime-local` is very bad at the moment:
http://caniuse.com/#search=datetime-local

**Comment by raimund-schluessler** [comment]
I also don't have a good replacement to propose at the moment.

The one that shows up when you look for `jquery-timepicker` on NPM (https://github.com/wvega/timepicker) seems to be maintained still, but not very flexible (it seems that it can only show a list of times, but not a table for selection).

**Comment by jancborchardt** [comment]
Oh yes – holy hell the current timepicker is bad. Should I make a mockup akin to the datepicker or does some other @nextcloud/designers want to take a stab at it? :)

**Comment by raimund-schluessler** [comment]
I think a mockup for a new design would be nice.

But before implementing this in CSS we need to decide on the underlying javascript library.

**Comment by pixelipo** [comment]
Maybe something more _Material_-istic?

https://github.com/material-pickers/time

Doesn't seem to be super-active, but it's not dead either.

It is missing some interesting/important features, such as - use the already set time, start from current time, follow cursor, drag-and-release, animated marker, automatically move to minutes-selector after selecting hours. Perhaps the author would be interested in accepting contributions...

On the other hand, IMO this design is much more natural and faster compared to all the others mentioned :arrow_up: Plus it is the only one that allows selecting any of the 60 minutes included in the hour - this is a killer feature for me :1st_place_medal:

**Comment by raimund-schluessler** [comment]
> On the other hand, IMO this design is much more natural and faster compared to all the others mentioned ⬆️ Plus it is the only one that allows selecting any of the 60 minutes included in the hour - this is a killer feature for me 🥇

The demo on this page gives me a timepicker where I can only select full hours?! Am I missing something? 

![screenshot-2017-9-17 material pickers - time](https://user-images.githubusercontent.com/2496460/30520981-ea5337e4-9bb7-11e7-9be0-7f218a834c59.png)

**Comment by tcitworld** [comment]
The minutes picker shows up after clicking « ok ».

**Comment by dartcafe** [comment]
Any progression in chosing a default time picker?

**Comment by jancborchardt** [comment]
Slight visual design improvement to the timepicker at https://github.com/nextcloud/server/pull/7054, please review! :)

I would absolutely not go for an Android-style clock-face time picker for several reasons:
- Barely anyone is used to circular clocks anymore
- The distinction between AM and PM is super confusing
- Check out how iOS does it, much better – for Nextcloud 14 we should do it more like that
![](https://i.stack.imgur.com/QMDRD.png)

And that two times next to each other for Start time and End time. cc @raimund-schluessler @georgehrke

**Comment by MorrisJobke** [comment]
macOS:

especially a nice feature for the ending time:

<img width="375" alt="bildschirmfoto 2017-11-03 um 15 21 45" src="https://user-images.githubusercontent.com/245432/32378354-d3d5b498-c0aa-11e7-8724-14b6edea2a75.png">

**Comment by pixelipo** [comment]
@jancborchardt isn't the iOS solution very touchscreen-oriented?

**Comment by jancborchardt** [comment]
@pixelipo yes, forgot to add some details:
- The display of the current time should be an input field, for hour as well as minute.
- The minute picker could do jumps of 5 minutes instead of 1.

But yeah, on macOS there’s not even any kind of time picker, except that one for the ending time …

**Comment by raimund-schluessler** [comment]
I guess this is done now with https://github.com/nextcloud/vue-components?

**Comment by MorrisJobke** [comment]
> I guess this is done now with https://github.com/nextcloud/vue-components?

cc @skjnldsv @ChristophWurst

**Comment by skjnldsv** [comment]
Yes! :)
But it's not really into server. Though we should recommend using vue?

**Comment by jancborchardt** [comment]
We can consider this done and closed because the Vue component is available and real nice! :) And yes, we should recommend using Vue since it makes it much easier for app developers to provide a great UX.
