### ISSUE TITLE
[federation] can't establish a trusted connection

### ISSUE THREAD

**Issue by DJCrashdummy** [nextcloud/server#6349]
### Steps to reproduce
1. setup 2 instances of Nextcloud 12 and make your configurations
2. decide to connect them for easy sharing and interaction
3. add the complete URLs (https://cloud1.mydomain.tld/ or https://cloud.mydomain.tld/cloud2/) one after another in "Federation"

### Expected behaviour
like happened on the same instance (cloud1) with 2 other Nextclouds 11 before: after a while the orange indicator beside the URL should get green, trust the other instance and the users should get listed in the contacts-menu and wherever...

### Actual behaviour
1. after some time (more than one day) nothing happened, i decided to remove the URLs from the "Federation"-menu and start again. maybe i mistyped something or so...
2. after nearly a week the indicator on both instances are still orange and the other users don't appear at the other instance.
3. i had a closer look at the logs, and on cloud1 i saw a the following line: (not so good, but "ok"...)

Level | App | Message
-- | -- | --
Error | federation | remote  server (https://cloud.mydomain.tld/cloud2) didn't send a valid token  (got "nSWPMP5+sGKUbYyz" but expected "4YpNLGb4sW+9EJXg") while getting  shared secret

4. now what affirmed me thinking this is a bug, was a look at the logs on cloud2:

Level | App | Message
-- | -- | --
Error | federation | remote  server (https://cloud1.mydomain.tld) didn't send a valid token (got  "v0O2TDyuZQrHZF/l" but expected "") while getting shared secret

why the heck is **""** the expected token?!?
i have no idea what i may have done wrong...
- is it because cloud2 hasn't an own subdomain and/or an additional path
- is it because i use the IMAP-backend (configured to remove the domain from the login), so there are the same users on each cloud _(i don't think and hope so, that this is an issue!?)_
- is it because the parent path of cloud2 was password-protected some time ago (for sure i removed the protection before federation) _(cloud2 and other things under this domain are just for testing.)_

### Server configuration

**Operating system:** Linux 3.13.0-128-generic Ubuntu x86_64
(i think to remember my hoster told me it is Ubuntu 14.04)

**Web server:** Apache (fpm-fcgi)

**Database:** mysql 5.6.33

**PHP version:** 7.0.20-nmm1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - bcmath
 - bz2
 - calendar
 - ctype
 - dom
 - hash
 - filter
 - ftp
 - gettext
 - SPL
 - iconv
 - json
 - mbstring
 - posix
 - Reflection
 - session
 - standard
 - shmop
 - SimpleXML
 - soap
 - exif
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xml
 - xmlreader
 - xmlwriter
 - zip
 - cgi-fcgi
 - propro
 - raphf
 - http
 - mysqlnd
 - PDO
 - curl
 - fileinfo
 - gd
 - gender
 - gmp
 - htscanner
 - imagick
 - imap
 - interbase
 - intl
 - ldap
 - mailparse
 - mcrypt
 - mongodb
 - mysqli
 - OAuth
 - odbc
 - pdo_dblib
 - pdo_mysql
 - PDO_ODBC
 - pdo_pgsql
 - pdo_sqlite
 - pgsql
 - Phar
 - pspell
 - recode
 - SourceGuardian
 - sqlite3
 - tidy
 - xsl
 - ionCube Loader
```
</details>

**Nextcloud version:** 12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** updated just from 12.0.1

**Where did you install Nextcloud from:** hoster-script

**Signing status:**
```
No errors have been found.
```

**List of activated apps:**
<details>
<summary>App list</summary>

```
activity
bruteforcesettings
calendar
comments
contacts
dav
federatedfilesharing
federation
files
files_pdfviewer
files_sharing
files_texteditor
files_trashbin
files_versions
files_videoplayer
firstrunwizard
gallery
logreader
lookup_server_connector
nextcloud_announcements
notifications
oauth2
password_policy
provisioning_api
serverinfo
sharebymail
twofactor_backupcodes
updatenotification
user_external
workflowengine

apporder
checksum
files_downloadactivity
files_opds
files_reader
keeweb
metadata
notes
qownnotesapi
quota_warning
socialsharing_email
spreed
tasks
telephoneprovider

**Disabled:**
admin_audit
systemtags
encryption
files_external
user_ldap
theming
survey_client

ransomware_protection
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'xxxxxxxxxxxx',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'cloud.mydomain.tld',
  ),
  'datadirectory' => '/www/htdocs/server/nextcloud1/data',
  'overwrite.cli.url' => 'http://cloud.mydomain.tld/nextcloud1',
  'dbtype' => 'mysql',
  'version' => '12.0.2.0',
  'dbname' => 'dbname',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'xxxxx_',
  'mysql.utf8mb4' => false,
  'dbuser' => 'dbuser',
  'dbpassword' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'installed' => true,
  'default_language' => 'de',
  'allow_user_to_change_display_name' => false,
  'skeletondirectory' => '',
  'user_backends' => 
  array (
    0 => 
    array (
      'class' => 'OC_User_IMAP',
      'arguments' => 
      array (
        0 => '{mail.mydomain.tld:993/imap/ssl/novalidate-cert/readonly}INBOX',
        1 => 'mydomain.tld',
      ),
    ),
  ),
  'updater.release.channel' => 'production',
  'loglevel' => 2,
  'customclient_desktop' => 'https://nextcloud.com/install/#install-clients',
  'customclient_android' => 'https://f-droid.org/packages/com.nextcloud.client',
  'customclient_ios' => 'https://itunes.apple.com/us/app/nextcloud/id1125420102?mt=8',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/www/htdocs/server/nextcloud1/apps_neu',
      'url' => '/apps_neu',
      'writable' => true,
    ),
    1 => 
    array (
      'path' => '/www/htdocs/server/nextcloud1/apps',
      'url' => '/apps',
      'writable' => false,
    ),
  ),
  'memcache.local' => '\\OC\\Memcache\\ArrayCache',
  'theme' => '',
  'filesystem_check_changes' => 1,
  'tempdirectory' => '/www/htdocs/server/nextcloud1/tmp/',
  'maintenance' => false,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\MarkDown',
    4 => 'OC\\Preview\\Epub',
    5 => 'OC\\Preview\\FB2',
    6 => 'OC\\Preview\\PDF',
    7 => 'OC\\Preview\\OpenDocument',
    8 => 'OC\\Preview\\StarOffice',
    9 => 'OC\\Preview\\MSOfficeDoc',
    10 => 'OC\\Preview\\MSOffice2003',
    11 => 'OC\\Preview\\MSOffice2007',
  ),
);
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** IMAP

### Client configuration
**Browser:** Firefox 54.0 (64-Bit)

**Operating system:** Linux Mint 17 (based on Ubuntu 14.04)

**Comment by MorrisJobke** [comment]
cc @schiessle

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
