### ISSUE TITLE
does not allow me to create users

### ISSUE THREAD

**Issue by mama21mama** [nextcloud/server#6350]
[![imagebin](http://upimage.mamalibre.com.ar/up/ecde284ba53833e405278aadf020d705.png)](http://upimage.mamalibre.com.ar/#ecde284ba53833e405278aadf020d705.png)

[![imagebin](http://upimage.mamalibre.com.ar/up/0beb24198ea657467820aa1c1f2884d5.png)](http://upimage.mamalibre.com.ar/#0beb24198ea657467820aa1c1f2884d5.png)

:s

**Comment by MorrisJobke** [comment]
Please fill out the issue template: https://raw.githubusercontent.com/nextcloud/server/master/issue_template.md

**Comment by mama21mama** [comment]
OS: Debian stable
Web server: lighttpd
Database: MariaDB
Php: php7
Nextcloud: stable

**Comment by mama21mama** [comment]
solved:[ issues/283](https://github.com/nextcloud/server/issues/283#issuecomment-230441698)
```

mama@zeuza:/media/Disco160/www/nextcloud$ sudo -u www-data php occ user:add yesi
Enter password: 
Confirm password: 
The user "yesi" was created successfully

```

**Comment by mama21mama** [comment]
solved:[ issues/283](https://github.com/nextcloud/server/issues/283#issuecomment-230441698)
```

mama@zeuza:/media/Disco160/www/nextcloud$ sudo -u www-data php occ user:add yesi
Enter password: 
Confirm password: 
The user "yesi" was created successfully

```

**Comment by MorrisJobke** [comment]
> solved: issues/283

Okay - We plan to work on the mobile and responsive UI for the user management anyway, so I will close this ticket here then. Thanks for your report anyway. 👍
