### ISSUE TITLE
share missing after modification by owner

### ISSUE THREAD

**Issue by jknockaert** [nextcloud/server#6353]
### Steps to reproduce
1. create a text file on your computer
2. sync the text file to your nextcloud account (using the nextcloud desktop client)
3. share the text file with another account (read-only)
4. modify the text file on your computer
5. resync the modified file

### Expected behaviour
the other account should be able to access the modified text file

### Actual behaviour
the access through the other account doesn't work (both in the webinterface and over webdav)

### Server configuration

**Nextcloud version:** 12.0.2

**Are you using encryption:** yes

### Client configuration
**Operating system:** macOS sync client 2.3.0.4rc1

There may be a relation to #6183.

**Comment by blizzz** [comment]
@nextcloud/sharing

**Comment by jknockaert** [comment]
Issue still there in 12.0.3.

**Comment by jknockaert** [comment]
Issue still there in 15.0.5.

**Comment by skjnldsv** [comment]
Still here in nc 17? :see_no_evil:
