### ISSUE TITLE
Error incomplete/Incorrect ; Changing the password will result in data loss, because data recovery is not available for this user

### ISSUE THREAD

**Issue by Oclair** [nextcloud/server#6362]
NC 12.0.2
Affects all platforms
Affects all Clients
Affects you as well, error messages are important too!

**Error message does not relate to underlying problem, fix error messages to indicate underlying configuration and 3rd party app conflicts**

See example: https://www.dropbox.com/s/813t9opl52mo24b/Screen%20Shot%202017-09-04%20at%202.49.35%20PM.jpg?dl=0

**NOTE This bug deals with how errors do not include debug info that produces an error to admin web interface**
 
### Steps to reproduce
1. change user password via admin interface

OR

1. attempt to reset user password via client login

Basically the error message does not indicate the underlying problem, this is indicative of incomplete error message information that does not include debug data...

### Expected behaviour
The error message reveals the config or 3rd party plugin conflict preventing NC from performing a user password reset, or change a user password via admin interface

### Actual behaviour
A useless error message is printed without including the underlying debug info which exists for the error that produced it

### Server configuration

**Nextcloud version:**
12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
10.0, 11.0, 12.0

**Where did you install Nextcloud from:**
downloaded source nextcloud.com not pkg or port

**Comment by ChristophWurst** [comment]
As the version of the software you've reported this for has reached *end of life*, I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen.
