### ISSUE TITLE
Modernize style of 'Alternative Logins' buttons

### ISSUE THREAD

**Issue by leonklingele-work** [nextcloud/server#6367]
Apps can add their own 'Login' mechanism by using [`\OC_App::registerLogIn`](https://github.com/nextcloud/server/blob/d7d2d7c803b372278cd60a7af76e6a410dce046d/lib/private/legacy/app.php#L718) which displays a new button on the initial login page (see the following screenshot):

![nextcloud-alternative-login](https://user-images.githubusercontent.com/31063993/30065082-0e51a60c-9254-11e7-95ca-7471f6369f14.png)

These buttons have probably not been redesigned for years 🙀 

### How to reproduce

Install and enable the [Registration](https://github.com/pellaeon/registration) app.

**Comment by MorrisJobke** [comment]
Fix is in #6370
