### ISSUE TITLE
Hidden files are styled as file extensions

### ISSUE THREAD

**Issue by superDuperCyberTechno** [nextcloud/server#6373]
Really simple: In the GUI, hidden files are parsed as file extensions (getting class "extension"), quite likely because they begin with a period.

I have quite a few dot files synced, so I'd like them to be colored as regular files.

Bug or feature?

**Comment by MorrisJobke** [comment]
This was actually implemented as feature to have hidden files not that prominently listed.

cc @nextcloud/designers

**Comment by jancborchardt** [comment]
Yup, as @MorrisJobke said. Even when hidden files are displayed, this makes them easily distinguishable. It’s by design. :)
