### ISSUE TITLE
App password restrictions for specific nextcloud apps

### ISSUE THREAD

**Issue by e-markus** [nextcloud/server#6376]
Hi,
restricting app password permissions for filesystem has been implemented with #719. Thank you for that.
I am using mail and rainloop in my nextcloud environment. 

In this environment, I have security concerns giving 3rd party apps (e.g. for calendar) access to my nextcloud accounts because they could theoretically access the users e-mails.

Therefore I would like to deny 3rd party apps (or alternatively for all apps using app passwords) from accessing Mail.

**Comment by MorrisJobke** [comment]
cc @ChristophWurst @icewind1991

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by mcassaniti** [comment]
@szaimen Unless this feature has made its way into Nextcloud the issue is still relevant.

**Comment by scollovati** [comment]
This is relevant, but similar to this one https://github.com/nextcloud/server/issues/2866

**Comment by sunjam** [comment]
@scollovati might be implemeted through Scoped Oauth?
- https://github.com/nextcloud/server/issues/26233

Apologies for the aside everyone. :heart:

**Comment by jospoortvliet** [comment]
Let's close as duplicate of https://github.com/nextcloud/server/issues/2866 so we have one place to track...
