### ISSUE TITLE
{admin,personal}_sections and {admin,personal}_settings are cached inside DB

### ISSUE THREAD

**Issue by leonklingele-work** [nextcloud/server#6382]
The `appinfo/info.xml` file can be [used to extend](https://github.com/nextcloud/server/blob/2cb346114685ded69f5291812503c278298c1bce/apps/files_external/appinfo/info.xml#L29-L34) the `Personal Settings` and `Admin Settings` page:

```xml
<settings>
	<admin>OCA\Files_External\Settings\Admin</admin>
	<admin-section>OCA\Files_External\Settings\Section</admin-section>
	<personal>OCA\Files_External\Settings\Personal</personal>
	<personal-section>OCA\Files_External\Settings\PersonalSection</personal-section>
</settings>
```

What's the reason these options are also stored (cached?) inside the database?
This has already caused quite some confusion as these entries apparently only get refreshed if the app is updated. For example adjusting the `getPriority()` / `getSection()` return value of a `ISettings`-implementing class has no effect unless the app is updated.

Another problem is that old entries are not removed. Steps to reproduce: Remove some of the elements in `<settings>` and upgrade the app: The rows are still in the DB.

**Comment by leonklingele-work** [comment]
@nickvergessen FYI

**Comment by nickvergessen** [comment]
I vote to change this and make it behave like f.e. with the activity filters/providers/settings.
We read info.xml anyway all the time, so we can also then just register them on the settings manager and build them when needed from the files, instead of requiring the database?

**Comment by MorrisJobke** [comment]
@leonklingele-work Never just assign people. Usually assignments are done by the person itself and not by somebody else.

**Comment by blizzz** [comment]
> I vote to change this and make it behave like f.e. with the activity filters/providers/settings.
We read info.xml anyway all the time, so we can also then just register them on the settings manager and build them when needed from the files, instead of requiring the database?

Agreed, these involves also far less code paths and DB access and handling. 

> Steps to reproduce: Remove some of the elements in <settings> and upgrade the app: The rows are still in the DB.

They should have been removed, IIRC, at least after figuring out the classes cease to exist.
