### ISSUE TITLE
info.xml: Empty 'navigations' element should not produce error message in log

### ISSUE THREAD

**Issue by leonklingele-work** [nextcloud/server#6385]
## Steps to reproduce

1. Make an `info.xml` file include an empty 'navigations' element with a line break between the opening and closing bracket:
```xml
    <navigations>
    </navigations>
```

This will not work:
```xml
    <navigations></navigations>
```

2. Open a random Nextcloud page to trigger PHP execution

## Actual result

An error message is logged to the logfile:

```
{"reqId":"vzESQMd3uSKyEz65Z4AW","level":0,"time":"2017-09-06T16:25:25+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"PHP","method":"GET","url":"\/path\to\/nextcloud\/apps\/files\/","message":"Invalid argument supplied for foreach() at \/path\/to\/nextcloud\/lib\/private\/NavigationManager.php#240","userAgent":"..","version":"13.0.0.3"}
```

This is because if the `navigation` element is empty, for whatever reason `$info['navigations']` [here](https://github.com/nextcloud/server/blob/5d4540f179eb107a54f725adeebfbd5183870802/lib/private/NavigationManager.php#L233-L236) is a string (contains spaces and a newline character) instead of an array, thus passes the `empty($info['navigations'])` check and `foreach` receives a that string which yields the error.

**Comment by nickvergessen** [comment]
You should not have an empty navigations section in first place

Navigations is optional:
https://github.com/nextcloud/appstore/blob/df697b99237d22fbe730c327f2425638977de826/nextcloudappstore/api/v1/release/info.xsd#L54-L55

But within navigations there has to be at least one entry as per our specs:
https://github.com/nextcloud/appstore/blob/df697b99237d22fbe730c327f2425638977de826/nextcloudappstore/api/v1/release/info.xsd#L389-L394
