### ISSUE TITLE
user_ldap wizard has hard-coded 400 limit on the number of groups

### ISSUE THREAD

**Issue by eigood** [nextcloud/server#6387]
nextcloud-version: 12.0.2

apps/user_ldap/lib/Wizard.php sets $limit = 400.  But my remote Active Directory has 2957 groups.  The front-end doesn't implement paging, so I can't select the correct filter groups.

I have this fixed locally, but it leads to another bug(filing shortly)

**Comment by ChristophWurst** [comment]
Although this sounds like a nice feature, the number of requests for this are quite low. Currently there a no plans to implement such a feature, hence I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription (2957 groups sounds like an enterprise setup)  to get your features implemented.

Thank you :v:
