### ISSUE TITLE
user_ldap search() doesn't implement paging correctly

### ISSUE THREAD

**Issue by eigood** [nextcloud/server#6388]
nextcloud-version: 12.0.2

In search(), the passed in $limit is passed directly to executeSearch.  If the calling code has set $limit to 400, or to null, it does not get massaged.  count() a few lines above looks at ->connection->ldapPagingSize, and deals with that accordingly.

I have this fixed locally by implementing the same kind of logic as in ->count().  I now get 2957 groups in the front-end wizard.

**Comment by MorrisJobke** [comment]
Fixed with #6453
