### ISSUE TITLE
user_ldap wizard doesn't quote group names

### ISSUE THREAD

**Issue by eigood** [nextcloud/server#6389]
nextcloud-version: 12.0.2

Some of the groups returned from the remote server have '*()' in their name.  The AD administrators used '*' to make those groups sort first alphabetically. The wizard does *not* quote those values, and somewhere this causes a failure.

I haven't yet debugged where this problem is, but I do *not* end up seeing an ldap request to my local openldap proxy.  If I have a non-special group selected, I do see the ldap request, so the quoting needs to be implemented(I'm guessing in the front end).

I'll be working on this shortly.

**Comment by eigood** [comment]
I've got this fixed locally, but am trying to fix all the bugs before I send a MR.

**Comment by blizzz** [comment]
To confirm, I saw this today again on 16.0.1.

**Comment by skjnldsv** [comment]
Still occurring @blizzz ?
