### ISSUE TITLE
user_ldap: When no group is selected, but the right-arrow is clicked, [window] gets added to the filter

### ISSUE THREAD

**Issue by eigood** [nextcloud/server#6391]
nextcloud-version: 12.0.2

Load the wizard.  Go to the groups tab.  Wait for the list of groups to show up.  Do *not* select a group.  Click the right arrow.  See the [window] object in the selection.

I might get around to this locally.

**Comment by eigood** [comment]
I've got this fixed locally, but am trying to fix all the bugs before I send a MR.

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
