### ISSUE TITLE
user_ldap: recommends to have a local proxy cache, but this fails when large numbers are returned

### ISSUE THREAD

**Issue by eigood** [nextcloud/server#6392]
nextcloud-version: 12.0.2

This is not a pure nextcloud bug.  I configured a local openldap proxy around the remote Active Directory.  When nextcloud talks to the remote, I get 2957 groups.  When it talks to the local slapd, I also get 2957 groups.  In both cases, it's doing it $pageSize at a time(500).  However, when I enable slapo-pcache, the pageSize value is *ignored*, and I only get the maximum size allowed by the remote server(2000 in this case).

I'm currently talking with openldap upstream about this, but they seem to think it's an AD bug, and not a pcache bug.

My suggestion for nextcloud is to *not* recommend pcache until this is fixed, as doing so means that the resultset is *truncated*.  :(

**Comment by eigood** [comment]
Ok, good news.  openldap upstream has acknowledged the bug, and while it was initially closed, has been re-opened.

Here is the upstream link: https://www.openldap.org/its/index.cgi/Incoming?id=8724

**Comment by eigood** [comment]
This is mostly because the pcache example config for nextcloud only specifies a ttl for pcacheTemplate.  There are actually additional ttl options to be set(<negttl> <limitttl>).

**Comment by MorrisJobke** [comment]
> This is mostly because the pcache example config for nextcloud only specifies a ttl for pcacheTemplate. There are actually additional ttl options to be set( ).

@nextcloud/ldap What to do here?

**Comment by blizzz** [comment]
Uh, good question. Sounds indeed just like an issue on a 3rdparty and nothing we can do about. 

@eigood where did you see the pcache recommendation?

**Comment by blizzz** [comment]
As it is not an issue within Nc directly and I am not aware that we recommend pcache anywhere, I close this issue. If you disagree, we can reopen and discuss…
