### ISSUE TITLE
Can't delete permanently: "Permission denied"

### ISSUE THREAD

**Issue by biva** [nextcloud/server#6401]
### Steps to reproduce
1. Delete a folder (1.7 GB in my case)
2. Go to trashbin
3. Delete the folder from trash

### Expected behaviour
Folder is permanently deleted

### Actual behaviour
Error message: "Can't delete permanently"

Logs: 
```

Error | trashbin | can't delete /Alice.d1504790954/Alice-Backup//IMG_20151210_161610.jpg permanently. | 2017-09-07T15:43:45+0200
-- | -- | -- | --
Error | PHP | unlink(/media/raid/ncdata/data/etienne/files_trashbin/files/Alice.d1504790954/Alice-Backup/IMG_20151210_161610.jpg):  Permission denied at  /var/www/html/nextcloud/lib/private/Files/Storage/Local.php#220 | 2017-09-07T15:43:45+0200

```

For information:
- ```/media/raid/ncdata/data``` is my nextcloud data folder, outside of ```/var/www/html/nextcloud/```. www-data has ownership over this folder
- I had added this folder in the data folder manually, and performed a rescan (occ files:scan). It worked perfectly and I could see the folder in my web interface without issue.
- I was able to delete some files in a sub-folder "Boston" of this folder. But not able to delete "Boston" itself

### Server configuration

*Debian GNU/Linux 9.1 (stretch)
4.9.0-3-amd64
x86_64
Server version: Apache/2.4.25 (Debian)
Server built:   2017-07-18T18:37:33
PHP 7.0.19-1 (cli) (built: May 11 2017 14:04:47) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.19-1, Copyright (c) 1999-2017, by Zend Technologies
mariadb  Ver 15.1 Distrib 10.1.26-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
Nextcloud version 12.0.2
  - installed: true
  - version: 12.0.2.0
  - versionstring: 12.0.2
  - edition:

**Comment by MorrisJobke** [comment]
As this looks like a permission problem, please seek for help in the forums first, because they have there a lot of experience regarding troubleshooting of such issues: https://help.nextcloud.com/

Thanks

**Comment by biva** [comment]
Thanks! Done here: https://help.nextcloud.com/t/cant-delete-permanently-permission-denied/20653
