### ISSUE TITLE
user_ldap: Wizard::fetchGroups() has poor caching

### ISSUE THREAD

**Issue by eigood** [nextcloud/server#6409]
nextcloud-version: 12.0.2

In the fetchGroups function, it attempts to look for posixGroup, group, zimbraDistributionList, and groupOfNames.  Given the example slapd.conf proxy config, "group" and "zimbraDistributionList" are not defined as valid attributes, so slapo-pcache is not available to cache those values.

This shows up in the slapd debug output when it munged the filter: "(&(|(objectClass=posixGroup)(?objectClass=group)(?objectClass=zimbraDistributionList)(objectClass=groupOfNames))(cn=*))"

Those question marks signify that pcache doesn't know about those attributes.

**Comment by blizzz** [comment]
These requests are done on setting up an LDAP Connection, in order to autodetect the used group object classes. There is not just one LDAP server with a defined set of group objectclasses, but different implementations and customizations. Neither do I see a problem here nor a way to get around it.

**Comment by eigood** [comment]
Please don't close this, I have it fixed locally.  All I had to do was define those attributes in slapd.conf.

**Comment by eigood** [comment]
Meaning, my slapd+proxy+cache is actually caching that search.

**Comment by eigood** [comment]
Also meaning, I was to add a note to the docs saying that the proper way to make the pcache fast is to enable debugging in slapd, then watch what searches occur, and add the correct pcacheTemplate and/or attribute definitions.

**Comment by blizzz** [comment]
> Please don't close this, I have it fixed locally. All I had to do was define those attributes in slapd.conf.

That's great, however it does not relate to Nextcloud code base. 
> Also meaning, I want to add a note to the docs saying that the proper way to make the pcache fast is to enable debugging in slapd, then watch what searches occur, and add the correct pcacheTemplate and/or attribute definitions.

The documentation repo is here https://github.com/nextcloud/documentation/ I guess it makes more sense to have the issue open there?

Thanks for reporting anyhow! :)

**Comment by eigood** [comment]
I'd still like this kept open.  Hard-coding the list of group attributes is bad as well.  What if that became a configuration option?  Aka, not everyone has zimbra(zimbraDistributionList), nor active directory(user, group)

**Comment by eigood** [comment]
And good idea on the documentation repo, I've got almost all the wizard queries cacheable now.

**Comment by blizzz** [comment]
> I'd still like this kept open. Hard-coding the list of group attributes is bad as well. What if that became a configuration option? Aka, not everyone has zimbra(zimbraDistributionList), nor active directory(user, group)

Nor posixGroup :) That's what it exactly is for. Figuring out on setting up the Connection what is present. In normal operation, this won't be read anymore.
