### ISSUE TITLE
Nextcloud 11 - Upgrade to 12 failed - 

### ISSUE THREAD

**Issue by sebthesun** [nextcloud/server#6410]
Hi, 
I tried to upgrade my Nextcloud 11 to 12 with the web updater but, at the end, I got this error:

Mise à jour du schéma de la base de données
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_filecache ALTER mtime TYPE INT': SQLSTATE[22003]: Numeric value out of range: 7 ERROR: 
integer out of range

Before update version : 11.0.4

### Steps to reproduce
1.Simply follow the set in the upgrade process with the Updater 

### Expected behaviour
A functional Nextcloud 12 installation

### Actual behaviour
Upgrade fail with an sql error

### Server configuration

UBUNTU 16.04.3 x86_64

APACHE 2.4.18

PostgreSQL 9.5

PHP 7.0.22

nextcloud 11.0.4

fresh install

int

**Signing status:**
<details>
<summary>Signing status</summary>

Not available, unable to log in
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.4.1
  - calendar: 1.5.3
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - richdocuments: 1.11.33
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - spreed: 1.2.0
  - spreedme: 0.3.9
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 1.1.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "ocdn8gq560uz",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nc.example.com"
        ],
        "datadirectory": "\/var\/www\/nc.example.com\/data",
        "overwrite.cli.url": "https:\/\/nc.example.com",
        "dbtype": "pgsql",
        "version": "11.0.1.2",
        "dbname": "nc_example_com",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2
    }
}

</details>

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by MorrisJobke** [comment]
Looks like #2775

**Comment by MorrisJobke** [comment]
@nickvergessen: Do you have in idea what this is?

**Comment by MorrisJobke** [comment]
@sebthesun Could you provide the table definition from your postgres DB? Something like this will show it:

```postgres
\d+ oc_filecache
```

**Comment by sebthesun** [comment]
`                                                            Table "public.oc_filecache"
      Column      |          Type           |                           Modifiers                           | Storage  | Stats target | Description
------------------+-------------------------+---------------------------------------------------------------+----------+--------------+-------------
 fileid           | integer                 | not null default nextval('oc_filecache_fileid_seq'::regclass) | plain    |              |
 storage          | integer                 | not null default 0                                            | plain    |              |
 path             | character varying(4000) | default NULL::character varying                               | extended |              |
 path_hash        | character varying(32)   | not null default ''::character varying                        | extended |              |
 parent           | integer                 | not null default 0                                            | plain    |              |
 name             | character varying(250)  | default NULL::character varying                               | extended |              |
 mimetype         | integer                 | not null default 0                                            | plain    |              |
 mimepart         | integer                 | not null default 0                                            | plain    |              |
 size             | bigint                  | not null default 0                                            | plain    |              |
 mtime            | bigint                  | not null default 0                                            | plain    |              |
 storage_mtime    | bigint                  | not null default 0                                            | plain    |              |
 encrypted        | integer                 | not null default 0                                            | plain    |              |
 unencrypted_size | bigint                  | not null default 0                                            | plain    |              |
 etag             | character varying(40)   | default NULL::character varying                               | extended |              |
 permissions      | integer                 | default 0                                                     | plain    |              |
 checksum         | character varying(255)  | default NULL::character varying                               | extended |              |
Indexes:
    "oc_filecache_pkey" PRIMARY KEY, btree (fileid)
    "fs_storage_path_hash" UNIQUE, btree (storage, path_hash)
    "fs_parent_name_hash" btree (parent, name)
    "fs_storage_mimepart" btree (storage, mimepart)
    "fs_storage_mimetype" btree (storage, mimetype)
    "fs_storage_size" btree (storage, size, fileid)
`

**Comment by MorrisJobke** [comment]
@nickvergessen another DB issue :/

**Comment by nickvergessen** [comment]
Hmm, I'm not an expert for postgres, but it looks like integer columns have not size on postgres?
But the question is, why is it trying to update it anyway, because the Schema didn't change.

Side note: We changed the table for 13 to be bigint. So there should be no "integer out of range" error anymore.

**Comment by MorrisJobke** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
