### ISSUE TITLE
user_ldap: when in advanced group config mode, and searching in the frontend, the filter gets corrupted(sorta)

### ISSUE THREAD

**Issue by eigood** [nextcloud/server#6411]
nextcloud-version: 12.0.2

* Have more than 40 groups in ldap(as defined in wizardTabAbstractFilter.js)
* Add one from available, so it shows as selected.
* Do a search, type 1 character that is in an available set, but *not* in the selected set.
* Add a matching available item(click the right arrow)
* Watch as the filter displayed below no longer has the first selected option

This is due to:

* wizardTabAbstractFilter calling .empty(), then recreating the <option> based on it's local _options value, also based on the search.
* A trigger then happens, and this just reads all the select.option elements it can find.

My local fix does away with the .empty, and instead just does a .show()/.hide() as needed, based on the search that has been typed in.

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
