### ISSUE TITLE
NC12.0.2 Dutch flavor missing at profile page: phone, address, website, twitter  for normal users and ADMIN can't change it. #5178

### ISSUE THREAD

**Issue by JK74** [nextcloud/server#6425]
See: https://github.com/nextcloud/server/issues/5178
This issue was marked earlier as resolved in V12.0 but still not resolved.

### Steps to reproduce
1. go to personal page and observe that
1a: an admin sees the fields as address/twitter/phone/website but can't change
1b: an normal user does not have at all these 4 fields visible.

### Expected behaviour
Tell us what should happen
1a: admin should be able to see it and change the fields
1b: users should see those 4 missing fields and allowed to change it.

### Actual behaviour
1a: admin can't change his predefined fields I made in NC11 for twitter/address/website/phone
1b: normal user does not see any of those 4 fields.

See screenshot below from admin user:
![nextcloudprofil1](https://user-images.githubusercontent.com/17946255/30239144-673feac6-9556-11e7-9d9c-74870974c1fe.png)
see screenshot below from normal user:
![nextcloudprofil2](https://user-images.githubusercontent.com/17946255/30239145-674020a4-9556-11e7-8ee6-ea80adcb2950.png)

### General server configuration

**Operating system:** Linux nextcloud 4.4.0-93-generic #116-Ubuntu SMP Fri Aug 11 21:17:51 UTC 2017 x86_64

**Web server:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.19

**PHP version:** 7.0.22-0ubuntu0.16.04.1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - apache2handler
 - mysqlnd
 - PDO
 - xml
 - apcu
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - iconv
 - igbinary
 - json
 - exif
 - mysqli
 - pdo_mysql
 - Phar
 - posix
 - readline
 - redis
 - shmop
 - SimpleXML
 - sockets
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.2 - 12.0.2.0

**Updated from an older Nextcloud/ownCloud or fresh install: upgrade from 11.x

**Where did you install Nextcloud from: website for 11.x to 12.0 later on via web update 

**Are you using external storage, if yes which one: no
(
    [0] => \OC\Files\Storage\Local
    [1] => \OCA\Files_External\Lib\Storage\FTP
    [2] => \OC\Files\Storage\DAV
    [3] => \OCA\Files_External\Lib\Storage\OwnCloud
    [4] => \OCA\Files_External\Lib\Storage\SFTP
    [5] => \OCA\Files_External\Lib\Storage\AmazonS3
    [6] => \OCA\Files_External\Lib\Storage\Dropbox
    [7] => \OCA\Files_External\Lib\Storage\Google
    [8] => \OCA\Files_External\Lib\Storage\Swift
    [9] => \OCA\Files_External\Lib\Storage\SFTP
    [10] => \OCA\Files_External\Lib\Storage\SMB
    [11] => \OCA\Files_External\Lib\Storage\SMB
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** YOUR ANSWER HERE (LDAP/ActiveDirectory/Webdav/...)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - admin_notifications: 1.0.0
 - announcementcenter: 3.1.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - circles: 0.12.4
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - external: 2.0.3
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_antivirus: 1.1.0
 - files_automatedtagging: 1.2.2
 - files_downloadactivity: 1.1.1
 - files_external: 1.3.0
 - files_pdfviewer: 1.1.1
 - files_retention: 1.1.2
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - groupfolders: 1.1.0
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notes: 2.3.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - quota_warning: 1.1.0
 - ransomware_protection: 1.0.3
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - spreed: 2.0.1
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
 - workin2gether: 0.9.6
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - encryption
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "ocaacnf00r5p",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "www.xxx.info",
        "xxx.info",
        "192.168.x.x",
        "192.168.x.x"
    ],
    "datadirectory": "\/data",
    "overwrite.cli.url": "https:\/\/www.xxx.info\/nextcloud",
    "dbtype": "mysql",
    "version": "12.0.2.0",
    "dbname": "xx",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Berlin",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": "true",
    "redis": {
        "host": "\/var\/run\/redis\/redis.sock",
        "port": 0,
        "timeout": 0
    },
    "session_lifetime": 3600,
    "htaccess.RewriteBase": "\/nextcloud",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "noReply",
    "mail_domain": "xx.nl",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "smtp.xx.com",
    "mail_smtpport": "xxx",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 0,
    "cron_log": true,
    "log_rotate_size": 104857600,
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\Movie"
    ],
    "preview_max_filesize_image": 200,
    "maintenance": false,
    "theme": "",
    "singleuser": true,
    "updater.release.channel": "beta",
    "skeletondirectory": "\/data\/xxx\/files\/skeleton_nieuwe_gebruikers\/"
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36

**Operating system:** W10

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
> 1a: admin should be able to see it and change the fields

This should be a separate issue. But I guess it will not be easy to implement. :/ cc @schiessle

**Comment by MorrisJobke** [comment]
> 1a: an admin sees the fields as address/twitter/phone/website but can't change

How can an admin see this?

**Comment by JK74** [comment]
@morrisjobke well maybe his own personal items? Have you checked the url as well from previous post?

**Comment by JK74** [comment]
@morrisjobke well maybe his own personal items? Have you checked the url as well from previous post? 

And I do not  that agree on an feature thing; It's a bug already from 11.0 to 12.0 that I as admin could not see my own 4 fields and now I see my own 4 fields but I can't change them. Normal users don't see the 4 fields at all... so how could it be now an enhancement ? Or am I missing something in your thinking?

**Comment by MorrisJobke** [comment]
> And I do not that agree on an feature thing; It's a bug already from 11.0 to 12.0 that I as admin could not see my own 4 fields and now I see my own 4 fields but I can't change them. Normal users don't see the 4 fields at all... so how could it be now an enhancement ? Or am I missing something in your thinking?

Those missing 4 fields is clearly a bug. But that the admin should be able to also see the entries of all users and should be able to edit is a separate topic.

**Comment by JK74** [comment]
@MorrisJobke  is this fixed in NC13? just checking.... thnx

**Comment by JK74** [comment]
@MorrisJobke I still have this issue and I get a bit unhappy about it; when will this be fixed so I can re-edit it again? See attached pictures where I got triggered as your 13.0.3 updates showed that you can edit and change it but I still can't :( 
![nextcloud_admin_user](https://user-images.githubusercontent.com/17946255/41165240-6d58e058-6b3d-11e8-944a-40c56a0f62a9.PNG)
![nextcloud_standard_user](https://user-images.githubusercontent.com/17946255/41165242-6e761bf4-6b3d-11e8-94f6-ab6fa13723e2.PNG)

**Comment by MorrisJobke** [comment]
@rullzer @juliushaertl @danxuliu @skjnldsv Any idea what this is?

**Comment by juliushaertl** [comment]
@JK74 Are there any errors in the browser console or the Nextcloud log?

**Comment by JK74** [comment]
@juliushaertl  I don't see any errors in the browser console or are you looking for special values in the F12 developer mode?  I will send you offline our nextcloud log in private

**Comment by JK74** [comment]
resolved: see: https://help.nextcloud.com/t/cannot-edit-phone-address-website-or-twitter-account-info/32729/4

The setting I had to enable is in sharing > federation and then the bottom selection as in the post above.
I can then select as user to allow not to share, share to local contacts or share to global contact(s server)

**Comment by JK74** [comment]
closing per above
