### ISSUE TITLE
Give admin rights to a specific LDAP group

### ISSUE THREAD

**Issue by DBLouis** [nextcloud/server#6428]
My users are stored in an LDAP directory and I want to give admin permissions to some of them. I could manually put them in the default admin group of nextcloud but it would be more efficient to be able to select a group from LDAP as admin group. Could that be implemented?

**Comment by MorrisJobke** [comment]
I guess this is not possible, right @blizzz

**Comment by blizzz** [comment]
Not OOTB.

In 13 it is possible with  a custom group backend, since https://github.com/nextcloud/server/pull/5571 was merged.

The LDAP Backend could be extended with  providing the feature (pull requests welcome), it could also be considered for inclusion in #5321 (or a followup PR)

**Comment by xundeenergie** [comment]
This is also, what i need!

+1

**Comment by JoeKun** [comment]
I need this feature as well. Seems like one of the first thing anyone will bump against after configuring LDAP authentication for Nextcloud.

**Comment by gregharvey** [comment]
This would be nice, we also use Redmine which has this feature - you can specify the LDAP group containing your superusers and centrally control everything. +1 :-)

**Comment by FunkenTom** [comment]
I'm also looking for that feature.
As the LDAP Module handles the groups right, it would be in general a great idea/option if we can assign admin rights to a specific group.

+1

**Comment by blizzz** [comment]
For transparency, I will not have any time (not so soon) as being busy with different tasks/priorities. To get this implemented, the realistic options are to: 
a) develop this feature and open a pull request 
b) get in contact with Sales  

Cheers
Arthur

**Comment by MorrisJobke** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by Alkanna** [comment]
Hey, any plans to add this to the roadmap?

**Comment by blizzz** [comment]
Nope, https://github.com/nextcloud/server/issues/6428#issuecomment-487942872 is still valid

**Comment by TheDevilDan** [comment]
Hi,

What a pity, I think that many companies do not decide to take NextCloud because it does not meet the specifications of rights management (ACL) by AD with groups, it is a pity, we who wanted to administer this product with a group of administrator in the AD . Too bad...

**Comment by abctaylor** [comment]
You're potentially selling your product short my choosing not to make a very simple and basic change per what @TheDevilDan said. I suggest for you reconsider and add this to the base of the public tree and also your commercial GmbH stuff.

**Comment by sparky8251** [comment]
I mean, this is a very basic feature of LDAP. People likely aren't requesting it often because when they find out its not supported they realize you don't want to do it at all given how simple it is.

Hell, Jellyfin and Airsonic both let you do this and they are just media servers made by volunteers.

Please, really consider adding this in. Having half LDAP support like this is not cool.

**Comment by abctaylor** [comment]
I fully agree with @sparky8251 - this shouldn't take a lot of cycles of people's time and would be an essential feature for commercialization.

**Comment by blizzz** [comment]
Thanks all for the latest feedback. The state has not changed, this feature is not planned currently. If it is desired, please get into contact with our sales team, or contribute this feature yourself. Nextcloud is open source, after all.

**Comment by WorksAtAUni** [comment]
This would be huge... who wants to manually add people to the application admin group when you are dealing with more than 3?

**Comment by macwinnie** [comment]
Hi @azmeuk,

is there any progress until now? Do you have an idea about a timeline?

Thanks and best
Martin

**Comment by azmeuk** [comment]
Hello. I have been busy on other things so I did not worked on this.

**Comment by macwinnie** [comment]
By building LDAP-trees with nested groups, one could create a `admin` group for LDAP users independent of all other permission groups.

![example](https://user-images.githubusercontent.com/1001936/166825010-f3c499e7-3d5a-4eb7-9c8f-b568067dc8d1.png)

Now, the NextCloud knows 2 `admin` groups – and the LDAP one is not administrative ... =(

**Comment by l4b4r4b4b4** [comment]
indeed would be nice feature :)

What I do atm is to give different admin rights to different groups with Admin right delegation and privileged groups. Does not do the whole trick but it's something.
