### ISSUE TITLE
Locked file

### ISSUE THREAD

**Issue by CordlessWool** [nextcloud/server#6429]
### Steps to reproduce
1. moving files (folder with 1,8 GB and over 4000 files)
2. Ends with an error
3. Try to delete the destination fails and is still not deleteable

### Expected behaviour
destination folder should be delete able

### Actual behaviour
getting error message and log says that the file is locked

I also try to delete the lock table in mysql and rescaning all files. Also restart redis, but the folder is still not delete able and locked

### Server configuration
official docker container
**Operating system**:

**Web server:**

**Database:**
mysql 5.7.17

**PHP version:**
7.1.8

**Nextcloud version:** (see Nextcloud admin page)
12.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 12.0.1 history start at nextcloud 11 I think
**Where did you install Nextcloud from:**
hub.docker.com

**Nextcloud configuration:**
$CONFIG = array (
  'instanceid' => 'xxxxx',
  'passwordsalt' => 'xxxxxx',
  'secret' => 'xxxxx',
  'trusted_domains' => 
  array (
    0 => 'xxxxx',
    1 => 'xxxx',
  ),
  'datadirectory' => 'xxx',
  'overwrite.cli.url' => 'xxx',
  'dbtype' => 'mysql',
  'version' => '12.0.2.0',
  'dbname' => 'xxxxx',
  'dbhost' => 'xxxx',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxxxx',
  'dbpassword' => 'xxxxxxx',
  'logtimezone' => 'UTC',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'xxxx',
  'mail_from_address' => 'xxxxxx',
  'mail_domain' => 'xxxxx',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'xxxxx',
  'mail_smtpport' => 'xxxx',
  'mail_smtpname' => 'xxxxx',
  'mail_smtppassword' => 'xxxxx',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'xxxx',
    'port' => xxxx,
    'timeout' => xx,
    'password' => 'xxxxx',
    'dbindex' => x,
  ),
  'forwarded_for_headers' => 
  array (
    0 => 'HTTP_X_FORWARDED',
    1 => 'HTTP_FORWARDED_FOR',
  ),
  'maintenance' => false,
  'loglevel' => 2,
  'theme' => '',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'app.mail.imaplog.enabled' => false,
  'app.mail.smtplog.enabled' => false,
);

### Log

  | OCA\DAV\Connector\Sabre\Exception\FileLocked: "Education/HS-Esslingen/Hochschule" is locked/var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php - line 179:  OCA\DAV\Connector\Sabre\Directory->delete()/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 287:  Sabre\DAV\Tree->delete('Education/HS-Es...')[internal function] Sabre\DAV\CorePlugin->httpDelete(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:  call_user_func_array(Array, Array)/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:  Sabre\Event\EventEmitter->emit('method DELETE', Array)/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:  Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/var/www/html/apps/dav/appinfo/v1/webdav.php - line 71:  Sabre\DAV\Server->exec()/var/www/html/remote.php - line 162:  require_once('/var/www/html/a...'){main}
-- | --

**Comment by LukasReschke** [comment]
cc @icewind1991

**Comment by CordlessWool** [comment]
Update: Some hours after I wrote the issue, I am able to delete it without an error.

**Comment by Julianoe** [comment]
Hi ! @LukasReschke 
I had the exact same issue. Like really the same, logs are the same etc.. but waiting several hours did not do the drill.

My config is as follows:

- server is hosted on a dedicated server and i use Nextcloud through Docker containers
- i have a Nextcloud client installed on a Linux (Ubuntu) computer
- i have a Nextcloud client on a Windows PC

I sent a big file (3.2GB) through the Windows client and there was an error somewhere when i tried to delete it. I tried anywhere and it gives me an error. Trying to delete the file in the web admin returns "File locked" and the logs look the same as @CordlessWool ones

**Comment by MorrisJobke** [comment]
Related to #8723

**Comment by MorrisJobke** [comment]
Let's continue there.

**Comment by Cees2439867** [comment]
Good day to you,
Face simular problems here. Does it have do with load of the sever? Now I cannot bring over 15Mb to nextcloud and I loose trust in that the dat is safe. I dropped 16 MB in to the window from the server and it stops with error of file locked on the main directory.
![afbeelding](https://user-images.githubusercontent.com/33065120/42772415-a9423ff0-892a-11e8-8df4-11680556a0bc.png)
Please help!
