### ISSUE TITLE
Ability to sync ics feeds / webcal

### ISSUE THREAD

**Issue by monojp** [nextcloud/server#643]
Hi, sorry if I'm not playing by the rules by directly opening an issue with this enhancement idea. But I'm sure this came already up (didn't find an issue although) -  wouldn't it be a killer feature if nextcloud was able to sync external ics files / feeds? People would finally be able to e.g. import calendars with their national holidays or possibly their custom facebook calendar or here in Vienna we have an ics feed for some special garbage we need to put outside the door on the evening before they come to pick up..
Currently I'm using additional apps like [ICSdroid](https://icsdroid.bitfire.at/) which of course I have to setup on all my devices. I would love to have that directly in nextcloud on my server. People seemed to already came up with the same idea and found a kind of hacky solution via cronjobs and other tools https://forum.owncloud.org/viewtopic.php?f=8&t=11576 which I don't really like and I'm afraid they are prone to break on updates / API changes

UPDATE: looks like a client-version of this was implemented into the calendar app in https://github.com/nextcloud/calendar/releases/tag/v1.4.0

**Comment by ulfkosack** [comment]
I'm very interested in this feature to.

**Comment by danielbierstedt** [comment]
Only thing missing now is the ability to sync subscribed Calendars to your mobile.

**Comment by konfiot** [comment]
Yep, would be awesome

**Comment by monojp** [comment]
DAVDroid + ICSdroid does exactly this since a few releases ago, right? Honestly this is enough for me

**Comment by konfiot** [comment]
Yep, but it would be better if we could only use DAVDroid, and get rid of ICSdroid by importing the ics feeds directly with the CalDAV feeds

**Comment by georgehrke** [comment]
It was implemented in the calendar side.

Being able to sync it is in: #1497
