### ISSUE TITLE
Add me to the NC org so I can start contributing

### ISSUE THREAD

**Issue by kcskou** [nextcloud/server#6431]
Hello there!

So I was about to create a pull request for my first bug fix but realized that I couldn't push my branch.

### Expected behaviour
I can push my branch, so that I can create a pull request.

### Actual behaviour
I don't have write access to make that happen, of course :)

git push origin app-level-agnostic-sorting
Username for 'https://github.com': kcskou
Password for 'https://kcskou@github.com': 
remote: Permission to nextcloud/server.git denied to kcskou.
fatal: unable to access 'https://github.com/nextcloud/server.git/': The requested URL returned error: 403

Thanks!

cc @jancborchardt

**Comment by jancborchardt** [comment]
@kcskou done, welcome to Nextcloud! :) You are also very welcome to join our IRC channel #nextcloud-dev

**Comment by kcskou** [comment]
Thanks @jancborchardt ! I didn't know I could do that! Looking forward to making NC better with y'all :)
