### ISSUE TITLE
Copying of a folder with a deep hierarchy stops.

### ISSUE THREAD

**Issue by tsuneky** [nextcloud/server#6438]
### Steps to reproduce
1.Access to Nextcloud by web browser
2.Create a layered folder
3.Drag and drop the created folder

### Expected behaviour
It is copied normally.

### Actual behaviour
Stops when one file stored in the lower layer folder is copied.

### Server configuration
environment
CentOS 7.3
Nextcloud 12.0.2
nginx 1.13.5
PHP 7.1.9
mariadb5.5.52

APCu
redis

browser
Firefox 55.0.3

When logging in the browser and dragging and dropping the folder, it stops with the remaining time during the upload being displayed.
No errors etc are displayed in the log.

Specifically, it is as follows
```
<folder-a>
 |
 |_a.txt
 |
 |_<folder-b>
	|
	|_<folder-c>
	    |_b.txt
	    |_c.txt
```
When uploading <folder-a> by drag & drop, it stops when b.txt is copied
Also, if you delete a.txt, the problem does not occur and the upload is completed.

The same event could be confirmed on the demo site below.
https://demo.nextcloud.com

Problems do not occur with copy other than browser such as client application.

Is there no way to deal with it?
![nc12](https://user-images.githubusercontent.com/31760880/30254262-a3753a52-96d0-11e7-81e3-06b4aa805391.png)

**Comment by Mamyrusses** [comment]
I upvote for the resolution of this bug. Using Nextcloud is very compromised without it! Thanks

**Comment by skjnldsv** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
