### ISSUE TITLE
CalDAV / CardDAV shouldn't return 507 InsufficientStorage when user has exceeded their quota

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/server#6447]
### Steps to reproduce
1. Have an account with quota exceeded
2. Try to create an event in Nextcloud Calendar (but should be the same for other CalDAV clients).
Also the same for CardDAV.

### Expected behaviour
`PUT` request should end up successfully and the event should be created

### Actual behaviour
The event isn't created, a 507 error is returned:
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\InsufficientStorage</s:exception>
  <s:message/>
</d:error>
```
**Nextcloud version:** 12

Corresponding Nextcloud Calendar issue for error handling : https://github.com/nextcloud/calendar/issues/592

**Comment by skjnldsv** [comment]
@georgehrke still make sense?

**Comment by georgehrke** [comment]
@rullzer made some changes to the Quota Plugin two days after @tcitworld opened this ticket,
I will check if it is still valid (though looking at the changes i think it still is).

Related code:
1. https://github.com/nextcloud/server/blob/07ffe4a34a9b3e63f33603a2e2bd49ea98293d88/apps/dav/lib/Connector/Sabre/ServerFactory.php#L164
2. https://github.com/nextcloud/server/blob/07ffe4a34a9b3e63f33603a2e2bd49ea98293d88/apps/dav/lib/Connector/Sabre/QuotaPlugin.php
3. https://github.com/nextcloud/server/blob/07ffe4a34a9b3e63f33603a2e2bd49ea98293d88/apps/dav/lib/Server.php#L245

I guess we should generally omit the entire files initialisation if the request is made inside
`['addressbooks', 'calendars', 'public-calendars', 'system-calendars']`

@icewind1991 Any objections ^

**Comment by tcitworld** [comment]
Doesn't happen anymore on 24.
