### ISSUE TITLE
Filepicker: sort by modified date (or better: respect sorting as in files app)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#645]
Oftentimes you want to pick files you recently uploaded or updated, like in mail attachments. Hence it would be cool if there would be a way to sort by modified date. Maybe even better, respect the sorting of the folders exactly as in the Files app.

cc @icewind1991

**Comment by jancborchardt** [comment]
cc @ChristophWurst @nextcloud/javascript as this comes up all the time in the Mail app. Tagging as starter issue cause it might be an easy fix?

**Comment by MorrisJobke** [comment]
Most likely nothing for 14 -> moving to 15.
