### ISSUE TITLE
quota: unlimited value

### ISSUE THREAD

**Issue by mama21mama** [nextcloud/server#6450]
impossible to change the user quota per web interface. is there any way to change that value by sql or php console?

**Comment by MorrisJobke** [comment]
> impossible to change the user quota per web interface. is there any way to change that value by sql or php console?

SQL: not possible
OCC CLI tool: `occ user:setting USERNAME files quota "2 GB"`
OCS API: https://docs.nextcloud.com/server/12/admin_manual/configuration_user/user_provisioning_api.html#edit-data-of-a-single-user

**Comment by Raymo111** [comment]
@MorrisJobke Thanks for that OCC command! I spent the last hour trying to set primary admin quota to unlimited while keeping default at 1 GB, but I couldn't change admin quota from the UI. Lifesaver!

**Comment by rubo77** [comment]
if you use docker:

     docker exec --user www-data next_app_1 php occ user:setting USERNAME files quota "999 GB"
