### ISSUE TITLE
Sync on 3rd party SMB drive not working - with Desktop Client

### ISSUE THREAD

**Issue by mbst83r** [nextcloud/server#6454]
### Steps to reproduce
1. Install a third party storage SMB drive
2. Try to sync a folder inside the SMB drive with the Win10 Desktop Client
3. Select a file in the SMB drive, work in it and try to save it

### Expected behaviour
The file should be synced after saving to the SMB drive

### Actual behaviour
Sync errors and no sync to the SMB drive

### Server configuration

**Operating system**:
Ubuntu 16.04
**Web server:**
Apache 2
**Database:**
Mariadb
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
12.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh
**Where did you install Nextcloud from:**
official download from download.nextcloud.com
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oc5501XXXXXX",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "172.16.XX.XX",
            "filebox.XXX.XX"
        ],
        "datadirectory": "\/var\/www\/html\/nextcloud\/data1",
        "overwrite.cli.url": "http:\/\/172.16.XX.XX\/nextcloud",
        "dbtype": "mysql",
        "version": "12.0.2.0",
        "dbname": "nextcloud",
        "dbhost": "localhost:3306",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_from_address": "filebox",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "XXX.XX",
        "mail_smtphost": "172.16.XX.XX",
        "mail_smtpport": "25"
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes, smb

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
yes, Active Directory



### Client configuration
**Browser:**
Firefox 55.0.3
**Operating system:**
Windows 10
### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
NONE
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"f9xPzbYoXwJZ4jM9rknR","level":4,"time":"2017-09-11T12:40:19+00:00","remoteAddr":"87.137.XX.XX","user":"2073CA2E-5E8D-4648-84DB-07E37A3879DA","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/files\/2073CA2E-5E8D-4648-84DB-07E37A3879DA\/WinInst\/Ablaufplan\/Ablaufplan.xlsx","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Message\":\"Could not rename part file to final file\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1130): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #156)\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->updateFile('files\\\/2073CA2E-...', Resource id #156, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(253): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/html\\\/n...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":188}","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.2 (build 1) (Nextcloud)","version":"12.0.2.0"}
{"reqId":"wSVuuuBnB7iNesJILhku","level":3,"time":"2017-09-11T13:28:29+00:00","remoteAddr":"172.16.XX.XX","user":"Administrator","app":"PHP","method":"POST","url":"\/index.php\/apps\/user_ldap\/ajax\/wizard.php","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at \/var\/www\/html\/nextcloud\/apps\/user_ldap\/lib\/LDAP.php#293","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"12.0.2.0"}
{"reqId":"h4zAkBu3OfbjkhLJa4bq","level":3,"time":"2017-09-11T13:28:42+00:00","remoteAddr":"87.137.XX.XX","user":"2073CA2E-5E8D-4648-84DB-07E37A3879DA","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/files\/2073CA2E-5E8D-4648-84DB-07E37A3879DA\/WinInst\/Ablaufplan\/Ablaufplan.xlsx","message":"renaming part file to final file failed ($run: true, $renameOkay: false, $fileExists: true)","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.2 (build 1) (Nextcloud)","version":"12.0.2.0"}
{"reqId":"h4zAkBu3OfbjkhLJa4bq","level":4,"time":"2017-09-11T13:28:42+00:00","remoteAddr":"87.137.XX.XX","user":"2073CA2E-5E8D-4648-84DB-07E37A3879DA","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/files\/2073CA2E-5E8D-4648-84DB-07E37A3879DA\/WinInst\/Ablaufplan\/Ablaufplan.xlsx","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Message\":\"Could not rename part file to final file\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1130): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #156)\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->updateFile('files\\\/2073CA2E-...', Resource id #156, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/var\\\/www\\\/html\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Server.php(253): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/html\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/html\\\/n...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":188}","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.2 (build 1) (Nextcloud)","version":"12.0.2.0"}
{"reqId":"89F1sOjk9kkFmSbTpkMW","level":3,"time":"2017-09-11T13:29:04+00:00","remoteAddr":"172.16.XX.XX","user":"2073CA2E-5E8D-4648-84DB-07E37A3879DA","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/files\/2073CA2E-5E8D-4648-84DB-07E37A3879DA\/WinInst\/Ablaufplan\/Cine-Project-Aufgaben.xlsx","message":"renaming part file to final file failed ($run: true, $renameOkay: false, $fileExists: true)","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.2 (build 1) (Nextcloud)","version":"12.0.2.0"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
NONE```
</details>

**Comment by mbst83r** [comment]
Fatal | webdav | Sabre\DAV\Exception: Could not rename part file to final file | 2017-09-11T16:34:47+0200
-- | -- | -- | --
Error | webdav | renaming part file to final file failed ($run: true, $renameOkay: false, $fileExists: true) | 2017-09-11T16:34:47+0200

That's the log from the webinterface ;-) 

Thanks in advance.

**Comment by blizzz** [comment]
@icewind1991 any clue?

**Comment by jm009** [comment]
What do you mean by "third party storage SMB drive"?
Hidden in the log I see another thing:
{"reqId":"wSVuuuBnB7iNesJILhku","level":3,"time":"2017-09-11T13:28:29+00:00","remoteAddr":"172.16.XX.XX","user":"Administrator","app":"PHP","method":"POST","url":"/index.php/apps/user_ldap/ajax/wizard.php","message":"ldap_search(): Partial search results returned: Sizelimit exceeded at /var/www/html/nextcloud/apps/user_ldap/lib/LDAP.php#293","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0","version":"12.0.2.0"}
Do you use LDAP?
I am new to Nextcloud, so please forgive, if I am asking stupid questions.

**Comment by mbst83r** [comment]
Yes we use LDAP. 

The third party SMB drive is an shared SMB Drive from a Windows Server.

**Comment by Spinrad** [comment]
Same problem, and similar config : Nextcloud 12.0.4 (via snap), Ubuntu Xenial 16.04, linux 4.4.0-103-generic, Nextcloud client 2.3.3 , Samba version 4.3.11, openldap-2.4.28

**Comment by Orbital-Bit** [comment]
this appears to be the same issue reported in these posts; [8978](https://github.com/nextcloud/server/issues/8978), [8547](https://github.com/nextcloud/server/issues/8547), [9000](https://github.com/nextcloud/server/issues/9000), and [6900](https://github.com/nextcloud/server/issues/6900)

**Comment by MorrisJobke** [comment]
> this appears to be the same issue reported in these posts; 8978, 8547, 9000, and 6900

Let's close this as duplicate of #8978 (and the other ones linked in there)
