### ISSUE TITLE
Add preview support for .mp4 (.m4a) files.

### ISSUE THREAD

**Issue by xXSTrikeXx** [nextcloud/server#6455]
### Expected behaviour
Tell us what should happen
If you upload any .mp3 file, the preview is shown. But if you buy music over itunes in the .mp4 (.m4a) format no previews are shown. 
Would be nice to add support for showing previews for .mp4 files. (I have more music bought in .mp4 format then .mp3 ;) )

So it would be nice to see  .mp3 album covers and .mp4 album covers in one directory (e.g. music directory) ;)

### Server configuration

**Operating system**: Raspian

**Web server:** Apache 2.4

**Database:** MYSQL

**PHP version:** 7.0

**Nextcloud version:** 12.0.2

**Comment by skjnldsv** [comment]
Seems like we already have 
https://github.com/nextcloud/server/issues/14991
