### ISSUE TITLE
Automatic cleaning for trash

### ISSUE THREAD

**Issue by keRin7** [nextcloud/server#6456]
### Expected behaviour
Please do automatic cleaning of the user's trashbin.
Data that in the trashbin eats a lot of disk space. 
It is good to be able to change the lifetime of files in the trashbin via admins panel.

**Comment by Rayn0r** [comment]
There two occ commands to manage the contents of the trash bin:
```
trashbin
 trashbin:cleanup   Remove deleted files
 trashbin:expire    Expires the users trashbin
```
You can simply set up a cron job, to clean the trashbin...

**Comment by MorrisJobke** [comment]
There is a config.php option to set this up: https://docs.nextcloud.com/server/12/admin_manual/configuration_server/config_sample_php_parameters.html#deleted-items-trash-bin
