### ISSUE TITLE
Filepicker: multiselect

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#646]
Currently when wanting to attach multiple files to a mail in the Mail app, you need to pick all of them individually. This is very cumbersome, and multiselect should be possible.

A simple click on a file should select it (as is now possible) and clicking multiple files should select multiple. Clicking a file again unselects it. Files are uploaded when clicking the Choose button on the bottom right.

cc @nextcloud/javascript

**Comment by jancborchardt** [comment]
In use it needs to be specified if multiselect should be possible or not. For example the picker for the profile image in the personal settings should only supports singe-select.

**Comment by MorrisJobke** [comment]
The multiselect option in the file picker also does not work:

```JS
OCdialogs.filepicker(
  'abc',
  function(files){
    console.log(files);
  },
  true
);
```

This file picker should allow to select multiple files, but it does not.


cc @icewind1991 @nextcloud/javascript

**Comment by szaimen** [comment]
You can now select more than one file at a time by using the `ctrl` button -> closing
![image](https://user-images.githubusercontent.com/42591237/119122545-e51bd300-ba2e-11eb-97e1-cea37f4c9de4.png)
