### ISSUE TITLE
S3 as external vs S3 as primary

### ISSUE THREAD

**Issue by R-yogesh** [nextcloud/server#6461]
If S3 is charged in enterprise as primary, all would prefer to go S3 as external with Community edition,
What is the difference between using S3 as a primary storage and S3 as a external storage ?

**Comment by MorrisJobke** [comment]
> What is the difference between using S3 as a primary storage and S3 as a external storage ?

One is used as primary storage (all files and also thumbnails or other generated files) are stored in it. The external storage only provides a subfolder in a users directory being on S3.

Both versions are available in the Nextcloud server. There is no enterprise or community version. There is only Nextcloud 😉
