### ISSUE TITLE
Open the file or folder shared by the link in user's nextcloud if the user already has access

### ISSUE THREAD

**Issue by mahnunchik** [nextcloud/server#6462]
Open the file or folder shared by the link in user's nextcloud if the user already has access (read or write).

### Steps to reproduce
1. Share file or folder to the `user` (read or write access).
2. Share file or folder or any child item by link `http://example.com/index.php/s/jlkiRcc1XLphKuz`
3. Open the link under `user` account.

### Expected behaviour

The file or folder is oppened in user account.

### Actual behaviour

The file or folder is opened in some kind of incognito.

### Server configuration

**Operating system**: Ubuntu (Docker image `nextcloud:12.0.2`)

**Web server:** Apache

**Database:** mariadb

**PHP version:** `php:7.1-apache`

**Nextcloud version:** 12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** Docker hub

### Client configuration
**Browser:** Chrome and Firefox

**Operating system:** Ubuntu 16.04

**Comment by hajika** [comment]
> 3. Open the link under user account.

that means: using the link when you are logged in? 

I would not necessarily expect to open it within my account automatically. I would expect and prefer to see the normal "public" view. But I agree that there should be a button/link to change the view to the nextcloud account.

**Comment by mahnunchik** [comment]
> that means: using the link when you are logged in?

Yep, the same or different user.

I've faced with the following:

1. User opened sharing link multiple times and multiple times clicked to `Add to my Nexcloud button`.
1. So user has multiple copies of folder in additions to copy of folder shared by regular username. 😞 😥 

If nexcloud have `view to the nextcloud account` feature it will solve this issue.

**Comment by hajika** [comment]
we could replace the `Add to my Nextcloud` button by a `view in my Nextcloud Account` button in case the user is logged in because it does more sense this way. That would only be bad for users who are logged in and want to add the public link to another nextcloud server.

**Comment by mahnunchik** [comment]
Add to my Nextcloud - adds **copy** of public folder even user already has access to it (or added it before).

**Comment by hajika** [comment]
Thats why this button doesn't make sense in my opinion when the user is logged in and has access to the file.

**Comment by mahnunchik** [comment]
Another solution to button `view in my Nextcloud Account` is to show to the user full path to the files/folder in their nexcloud without any redirects.

So the "public" view will show:

* Just `/ Folder` if user does not have access.
* `/ Path / To / Folder` if user have access.

**Comment by mahnunchik** [comment]
Any news?

**Comment by szaimen** [comment]
For this feature, pleaase use the internal link. If the user already has acces, he/she will see the file internally. -> closing.
