### ISSUE TITLE
"Share owners may need to re-share files after encryption is enabled" - really?

### ISSUE THREAD

**Issue by hostingnuggets** [nextcloud/server#6465]
The Nextcloud administration manual at https://docs.nextcloud.com/server/12/admin_manual/configuration_files/encryption_configuration.html#sharing-encrypted-files mentions the following sentence when using the encryption app:

```
Share owners may need to re-share files after encryption is enabled;
```

I tested this fact and to my disappointment it is true... This is an administration nightmare if one has a Nextcloud installation with hundreds of shares and a big user base with new users getting added and removed on a daily basis.

Is there a good reason for this behavior? and would it not make more sense that this happens automatically instead of having to manually add a new user to the respective shares although this user already is in the relevant groups which the files/directories are shared with? I suppose there is a problematic technical reason why this is not the case if not please see this issue as a major feature request for anyone using the encryption app.

**Comment by MorrisJobke** [comment]
> I suppose there is a problematic technical reason why this is not the case if not please see this issue as a major feature request for anyone using the encryption app.

This is due to the way the encryption works. The users need to have their keys set up and when a share exists the owner of the file needs to be logged in to decrypt the file key and encrypt it also with the recipients key.

What is you use case for encryption in the first place? Because it protects only against a very specific thread especially when using a third party storage that is not on the same server as the Nextcloud code and that is run by a different administrator. Otherwise you still need to trust you admin. If you can trust your admin maybe a filesystem level encryption is better suited for you.

**Comment by hostingnuggets** [comment]
> This is due to the way the encryption works. The users need to have their keys set up and when a share exists the owner of the file needs to be logged in to decrypt the file key and encrypt it also with the recipients key.

So this means there could be a hook as soon as the user owning the shares logs it it could automatically decrypt his shared files and encrypt the files also using the new user's key? For my case that would work quite well as the user sharing all the files is the admin user and I need to be logged in as admin anyway in order to create a new user.

**Comment by MorrisJobke** [comment]
> So this means there could be a hook as soon as the user owning the shares logs it it could automatically decrypt his shared files and encrypt the files also using the new user's key?

Yes - but it sounds easier than it is. Pull requests are welcome anyway.

cc @nextcloud/encryption

**Comment by MorrisJobke** [comment]
As this sounds like a nice feature, the requests for this are quite low. If you run regularly in this issue the master-key version of there server side encryption might fit better into your workflow. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
