### ISSUE TITLE
User management: Show email column by default and also send email to new users

### ISSUE THREAD

**Issue by hajika** [nextcloud/server#6468]
### Steps to reproduce
1. open admin users page
2. try to create a new user account without password but with invitation email

### Expected behaviour
There should be a checkbox close to the create user dialog

### Actual behaviour
The checkbox for invitation email and automatic password generation is hidden in the left settings menu named "Send email to new user"

Users who want to create first new user accounts for their nextcloud wont check the settings menu because they wont expect a function like this there. The function should be closer to its actual impact.

Following this issue https://github.com/owncloud/core/issues/12603 the decision was made back then because the create user dialog could be overcrowded. I don't think that this would be a real problem, it could be done this way:

![screenshot_2017-09-12_17-45-52](https://user-images.githubusercontent.com/27491258/30335882-c3681852-97e3-11e7-9b35-3708d8f5531b.png)
![screenshot_2017-09-12_17-46-44](https://user-images.githubusercontent.com/27491258/30335885-c4423050-97e3-11e7-979d-574b32e048a8.png)

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
Well to be honest we should just show the email field by default (but make it optional), and when the email is set, automatically send an email to that user that they now have an account.

We can then get rid of the setting completely.
