### ISSUE TITLE
opening pdf within browser misplaces the multipe files dialog

### ISSUE THREAD

**Issue by hajika** [nextcloud/server#6469]
### Steps to reproduce
1. go to nextcloud file list
2. click pdf file that opens within browser
3. use back button
4. mark several files with `strg+click`

### Expected behaviour
the dialog "donwload delete" for multiple files should be shown as normal

### Actual behaviour
the dialog is misplaced and not shown completely
![screenshot_2017-09-12_19-05-28](https://user-images.githubusercontent.com/27491258/30339267-c3c4bf8e-97ee-11e7-8da1-5cda41f991f9.png)

### Server configuration
**Operating system**: Cent OS6
**Web server:** apache
**Database:** mysql
**PHP version:** 7
**Nextcloud version:** 12.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 12.0.0
**Browser:** Firefox 55.0.2 on Ubuntu 16.04

**Comment by blizzz** [comment]
@nextcloud/javascript

**Comment by skjnldsv** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
