### ISSUE TITLE
App tokens not working on OCS when Two-Factor-Auth enabled

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#6471]
Regression in current stable12 and probably master. Blocker for next release.

**Comment by LukasReschke** [comment]
RC2 version bump PR once this has been fixed is at https://github.com/nextcloud/server/pull/6472

**Comment by rullzer** [comment]
Fix for master in https://github.com/nextcloud/server/pull/6473
stable12 in https://github.com/nextcloud/server/pull/6474

**Comment by rullzer** [comment]
#6473 and #6474 are in
