### ISSUE TITLE
Error 503, timeout

### ISSUE THREAD

**Issue by chiarelli** [nextcloud/server#6475]
This is not a problem, but a support request.

My web server does not allow to execute (or modify) "max_execution_time" or "time_limit" of PHP script, with this, downloads that need more than 120 seconds (limit pre-established by the server) to complete I get error 503.

There would be a plugin (application) for NExtCloud that implements splitting the file into several pieces for sending in multiple requests to the server; and then join the pieces?

If this plugin does not exist, could you tell me if the webDAV protocol allows sending a file in several pieces? Because I intend to initiate the development of a plugin that implements file splitting.

**Comment by LukasReschke** [comment]
> This is not a problem, but a support request.

Please file such topics on https://help.nextcloud.com. Thanks.
