### ISSUE TITLE
NC12 - User Management API - Admin password timeout for POST requests

### ISSUE THREAD

**Issue by KurganFr** [nextcloud/server#6476]
### Steps to reproduce
1. Start official nextcloud Docker container
2. Create a NextCloud admin account through the web front-end
3. Wait over 30 minutes
4. Start Postman Chrome extension (or use alternative such a curl)
5. Send the following request:
```
Request type: POST
URL: http://<server IP and port>/ocs/v1.php/cloud/users
Headers:
  OCS-APIRequest:true
  Authorization:Basic 
  Content-Type:application/x-www-form-urlencoded
Body:
  userid:tom
  password:tst13579
```
For simplicity, here is the same request using curl:
```
curl -X POST \
  http://<IP>:<port>/ocs/v1.php/cloud/users \
  -H 'authorization: Basic <encrypted authentication token>' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/x-www-form-urlencoded' \
  -H 'ocs-apirequest: true' \
  -H 'postman-token: b0e89892-f4d1-4bab-9b18-206f5f80c654' \
  -d 'userid=tom&password=tst13579'
```

### Expected behaviour
The specified user should be created by the call to the user management API and the following response should be received:
```
<?xml version="1.0"?>
<ocs>
    <meta>
        <status>ok</status>
        <statuscode>100</statuscode>
        <message>OK</message>
        <totalitems></totalitems>
        <itemsperpage></itemsperpage>
    </meta>
    <data/>
</ocs>
```

### Actual behaviour
The user is not created. Instead, the following response is received:
```
<?xml version=“1.0”?>
 <ocs>
     <meta>
         <status>failure</status>
         <statuscode>997</statuscode >
         <message >Password confirmation is required</message>
         <totalitems></totalitems>
         <itemsperpage></itemsperpage>
     </meta>
     <data/>
 </ocs>
```

### Server configuration

All configuration is as per official nextcloud Docker container (accessed using Kitematic (Alpha)).

**Operating system**: Debian 2.4.10

**Web server:** Apache HTTPD

**Database:** SQLite 12.0.0.29

**PHP version:** 7.1.9

**Nextcloud version:** 12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** official nextcloud Docker container (using Kitematic (Alpha))

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Activity (2.5.2, Official)
Collaborative tags (1.2.0, Official)
Comments  (1.2.0, Official)
Deleted files  (1.2.0, Official)
Federation  (1.2.0, Official)
File sharing  (1.4.0, Official)
First run wizard (2.1, Official)
Gallery (17.0.0, Official)
Log Reader (2.0.0, Official)
Monitoring (1.2.0, Official)
Nextcloud announcements (1.1, Official)
Notifications (2.0.0, Official)
Password policy (1.2.2, Official)
PDF viewer (1.1.1, Official)
Share by mail (1.2.0, Official)
Text editor (2.4.1, Official)
Theming (1.3.0, Official)
Update notification (1.2.0, Official)
Usage survey (1.0.0, Official)
Versions (1.5.0, Official)
Video player (1.1.0, Official)
Brute-force settings (1.0.2)
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php $CONFIG = array ( 'memcache.local' => '\\OC\\Memcache\\APCu', 'apps_paths' => array ( 0 => array ( 'path' => '/var/www/html/apps', 'url' => '/apps', 'writable' => false, ), 1 => array ( 'path' => '/var/www/html/custom_apps', 'url' => '/custom_apps', 'writable' => true, ), ), 'instanceid' => '', 'passwordsalt' => '', 'secret' => '', 'trusted_domains' => array ( 0 => ':', ), 'datadirectory' => '/var/www/html/data', 'overwrite.cli.url' => 'http://:', 'dbtype' => 'sqlite3', 'version' => '12.0.0.29', ); 
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Google Chrome version 60.0.3112.113, Postman for Chrome extension version 5.2.0

**Operating system:** Windows 7 Enterprise Service Pack 1

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No server logs.
```
</details>

**Comment by nickvergessen** [comment]
Yeah, for some actions you need to reconfirm your password after 30 minutes.
However providing the userid and the password as basic auth should work just fine.

**Comment by KurganFr** [comment]
@nickvergessen - sorry for the delay in replying. Unfortunately, I am already providing the userid and password as basic auth as part of the headers to the API call, yet the API call is not working. Are you able to provide any further advice or information that would assist me in resolving this issue? Thanks again.

**Comment by msgbrr** [comment]
@KurganFr  Has a solution been found? I've been having the same problem but I couldn't solve it for three days.

**Comment by KurganFr** [comment]
@msgbrr No solution so far unfortunately, hence my replying to the topic yesterday. It is very much a showstopper for the project I am involved in. Are there any specific steps you tried to attempt to solve the issue? Thanks.

**Comment by msgbrr** [comment]
@KurganFr I have tried a lot of things and read the NextCloud documentation many times but I have the same problem and no solution.

**Comment by efontain** [comment]
Hello, i have the same problem, what's the point of having an API if you can use it for only 30min ? A lot of people have this problem for a year, an no one respond to them. Will you do something about that ?
I don't even see why you need to "confirm your password" when you actually send it in basic auth.

**Comment by Ferhat-C** [comment]
If you automatically store the cookies and provide them with your following HTTP requests you will have the problem that even if you provide the Authentication header inside the request it will see the session cookie first if the cookie is expired it will not keep checking for the Authentication header but instead assume that you were solely trying to authenticate with the session cookie because why else would you provide it, right?
What happens is that it directly decides that you session is expired and it respond with an error.
All you have to do is stop storing/providing cookies in your HTTP requests.

**Comment by donquixote** [comment]
> All you have to do is stop storing/providing cookies in your HTTP requests.

This is a bad solution, because requests without cookies are A LOT slower.
For me, I measure times like this for an api request to get the admin user data:
- Cookie auth: ~30ms
- Token auth: ~40ms
- Basic auth: ~260ms

The token auth is slower than cookie auth because it initializes the user and sets up the mount points via post_login hook.
Cookie auth skips all of that.
Basic auth has to validate the password, which must take time, otherwise it would not be safe.

Btw the token auth does not prevent from the "Password confirmation is required" on some routes. So it does not really solve anything.
