### ISSUE TITLE
First Run Wizard Displays Nextcloud Logo with Custom Theme

### ISSUE THREAD

**Issue by terrytibbles** [nextcloud/server#6478]
Hello,

When the themes are updated manually using the instructions [here](https://docs.nextcloud.com/server/12/developer_manual/core/theming.html), logging in for the first time still displays the Nextcloud logo and background (see attached).

Thanks.

![first-run-wizard-nextcloud-1](https://user-images.githubusercontent.com/25575702/30362428-9b5540be-988e-11e7-8b61-af5a0f7e90c6.png)

**Comment by LukasReschke** [comment]
Please file this issue at https://github.com/nextcloud/firstrunwizard

**Comment by MorrisJobke** [comment]
https://github.com/nextcloud/firstrunwizard/issues/48
