### ISSUE TITLE
New NC instance, Calendar & Contacts apps broken, no shared Cals nor Cards

### ISSUE THREAD

**Issue by backstube** [nextcloud/server#6482]
### Steps to reproduce
1. Install NC server from git repo
2. Install 3rd-Party folder likewise
3. perform NC setup run
4. do the usual configs as Admin (add users, sharing ticks, etc)
5. enjoy instantly working *DAV clients (on a few macOS and iOS systems)
6. Install calendar and contacts web apps from git repos into server/apps
7. enable them as admin
8. make sure "Allow apps to use the Share API" is ticked
9. web UI log in as a regular user, try to use Calendar or Contacts
10. Contacts: eternal spinning wheel
11. Calendar: broken UI (see attachment down below)

### Expected behaviour
Both web apps Calendar and Contacts would work, showing existing calendar entries and contacts that native OS apps do.

More than having web apps working, users want to share Contacts and Calendars. These features are missing.

### Actual behaviour
Like I said above, click on Contacts brings up a spinning wheel, no content at all. Calendar does something, but it appears to be broken. See attachment. Tested w/ several browsers, including FF, Safari, Iridium.

There apparently is no mechanism to share Contacts nor Calendars btwn users.

### Server configuration

**Operating system**: FreeBSD 11.1-RELEASE-p1

**Web server:** nginx 1.12.1

**Database:** sqlite3 3.20.0

**PHP version:** 5.6.31

**Nextcloud version:** 12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** git repo

**Signing status:**  "Integrity checker has been disabled. Integrity cannot be verified."

**List of activated apps:**
Enabled:
  - bookmarks: 0.10.1
  - calendar: 1.5.3
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_markdown: 2.0.0
  - files_sharing: 1.4.0
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - groupfolders: 1.1.0
  - lookup_server_connector: 1.0.0
  - metadata: 0.5.0
  - notes: 2.3.1
  - oauth2: 1.0.5
  - provisioning_api: 1.2.0
  - sharebymail: 1.2.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0

**Nextcloud configuration:**
<pre>
{
    "system": {
        "instanceid": "aabcdefghijklmn",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "sync.example.com"
        ],
        "datadirectory": "\/usr\/local\/www\/example.com\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/sync.example.com",
        "dbtype": "sqlite3",
        "version": "12.0.2.0",
        "installed": true,
        "mail_from_address": "nc",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "example.com",
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
}
</pre>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no file system encryption or in-app encryption, only transport (TLS)

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** FF, Safari, Iridium (kinda reduced Chrome)

**Operating systems:** OS X 10.11, 10.12, iOS

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

-----

![screen shot 2017-09-13 at 11 39 32](https://user-images.githubusercontent.com/5227989/30373521-dff4dd0e-9881-11e7-9b5a-9e4a5888fea6.png)

**Comment by LukasReschke** [comment]
Please don't install apps from Git without reading it's READMEs or Makefiles. For calendar you need to run make for example.
