### ISSUE TITLE
Integrity failed for calendar apps after upgrade 11.0.3 to 11.0.4

### ISSUE THREAD

**Issue by Nono-m0le** [nextcloud/server#6485]
Sadly, after an upgrade from 11.0.3 to 11.0.4, everything went fine except the integrity check for the agenda/calendar apps ...

only the .gitignore is flagged as missing file : 

Results
=======
- calendar
	- FILE_MISSING
		- .gitignore

Raw output
==========
Array
(
    [calendar] => Array
        (
            [FILE_MISSING] => Array
                (
                    [.gitignore] => Array
                        (
                            [expected] => 2ebfa9d965d970eb2f3356f80cbff785c90c9a0d7634b406e49cd4e311826eb4abb482d8be75557cff491837881af2795fc4bd3a8e8d42b24c56d3b53b9b5dee
                            [current] => 
                        )
                )
        )
)

**Comment by MorrisJobke** [comment]
Duplicate of https://github.com/nextcloud/calendar/issues/600

**Comment by Nono-m0le** [comment]
Hi,

It's indeed similar, just keep in mind, I didn't ask to upgrade the app, only the instance itself. Probably it has been triggered automatically ? (I used the updater.phar).

**Comment by MorrisJobke** [comment]
> It's indeed similar, just keep in mind, I didn't ask to upgrade the app, only the instance itself. Probably it has been triggered automatically ? (I used the updater.phar).

Yes the server checks for app updates on an upgrade of the server.

**Comment by StuartIanNaylor** [comment]
I am the same calendar is there but for some reason an error
