### ISSUE TITLE
Use dark icons for app management

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#649]
As a follow-up of https://github.com/nextcloud/server/pull/627 (white app menu with dark icons) it would be good for consistency if the app management would also use dark icons. Then we can also get rid of the strange grey box we needed to make the white icons visible.

@juliushaertl are you also up for this? ;) cc @nextcloud/designers

**Comment by juliushaertl** [comment]
I'm up for this. ;) But I'm still not sure how to solve this, mainly to keep compatibility to owncloud apps without adding to much extra stuff. My first thought was to add an icon-dark entry to every navigation entry. Then we could use icon-dark with a fallback to the inverted default icon.

```
  \OC::$server->getNavigationManager()->add(function () {
      $urlGenerator = \OC::$server->getURLGenerator();
      return [
          'id' => 'myapp',
          'order' => 10,
          'href' => $urlGenerator->linkToRoute('myapp.page.index'),
          'icon' => $urlGenerator->imagePath('myapp', 'app.svg'),
          'icon-dark' => $urlGenerator->imagePath('myapp', 'app-dark.svg'),
          'name' => \OC::$server->getL10N('myapp')->t('My App'),
      ];
  });
```

Does anyone see a problem with that implementation?

**Comment by Bugsbane** [comment]
Let me know if you need the actual SVG's modified to make them darker (ie if it's not being done in code), and I'll take care of it.

**Comment by raghunayyar** [comment]
I would like to take this up if no one is doing this. :-)

**Comment by raghunayyar** [comment]
Simply replacing the fill works for me. There is a PR already on this. ;)

**Comment by juliushaertl** [comment]
I'd propose to just keep with the white icons as svg files and use the color inversion trick (like here: https://github.com/nextcloud/server/blob/5d0f9dabf6ee6ca432e99ad8cb1170badfabfd62/core/templates/layout.user.php#L116-L119) to render them as black icons in the app management as well. 

Otherwise we would have some white icons on white background for apps we don't maintain.

**Comment by Bugsbane** [comment]
> I'd propose to just keep with the white icons as svg files and use the color inversion trick

Agreed. I suggested that earlier more as a hack for if we didn't find a better way, which we did.

**Comment by juliushaertl** [comment]
pr #834 
stable10 #897

**Comment by Mannshoch** [comment]
I would Like to use a dark color for the bar at top. How could I change to normal?

**Comment by jancborchardt** [comment]
@Mannshoch you probably use the »[Direct Menu](https://github.com/juliushaertl/direct_menu)« which conveniently enough is also developed by the awesome @juliushaertl ;)

@juliushaertl if that app is enabled, then for bright header bar colors it probably makes sense to use the dark icons just as we switch the font to black for better contrast.

**Comment by juliushaertl** [comment]
@jancborchardt That should already work like that :smile:

**Comment by jancborchardt** [comment]
@juliushaertl hehe! Nice :D  

@Mannshoch what’s your problem then?

**Comment by Mannshoch** [comment]
@jancborchardt  Yes, your Right I use  »[Direct Menu](https://github.com/juliushaertl/direct_menu)« in which CSS File do I have to manipulate this? Or would you maybe add a checkbox which allow to switch the color?

**Comment by juliushaertl** [comment]
@Mannshoch the color of the icons should be switched automatically if the chosen theming color is too bright. (If you are using direct_menu version 0.9.1 or later) Maybe opening an issue over at https://github.com/juliushaertl/direct_menu/ would be better then discussing here. :wink:
