### ISSUE TITLE
Duplicate Shared folders

### ISSUE THREAD

**Issue by christianh95** [nextcloud/server#6491]
### Steps to reproduce
1. Have shared folders
2. Update from NC Version 11.0.2 to 11.0.4 with the web updater

### Expected behaviour
Your data should stay the same as before

### Actual behaviour
I now have a duplicate of every shared folder. My NC-Instance has several users that don't have a quota, but several shared folders owned by a admin user. After the update, I have the following document root for every user:

* External Storage Folder
* Folder 1 (empty, user's private folder, didn't exist before)
* Folder 2 (empty, user's private folder, didn't exist before)
* Folder 1 (2) (original data, still shared folder)
* Folder 2 (2) (original data, still shared folder)

I tried deleting all shares and sharing them again, didn't work. I even deleted all shares ending with a (2) out of the mysql-table, nothing changes. Whenever I log in to one of the Users, they all have duplicate folders. The only one untouched is an external storage folder. Any ideas?

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
Update from 11.0.2 to 11.0.4

**Are you using external storage, if yes which one:**
yes, one local folder, it's the only one that kept it's state

**Comment by bat553** [comment]
Same problem here 
![capture du 2017-09-14 19-41-35](https://user-images.githubusercontent.com/4821770/30452311-bcd2d908-9984-11e7-97ba-656db5685148.png)

**Comment by LukasReschke** [comment]
This should be fixed with Nextcloud 12.0.2. Please reopen if you can reproduce this with Nextcloud 12.0.2.
