### ISSUE TITLE
Add "Action-icon" API

### ISSUE THREAD

**Issue by LEDfan** [nextcloud/server#6493]
To keep track of the idea to provide an API for this, inspired by #6426 

Currently we have the following icons on the right side of the Nextcloud header:
![selectie_709](https://user-images.githubusercontent.com/2996275/30413377-f2030e7a-991d-11e7-9f69-c3e41b294232.png)
The Chat and Notifications icon are inserted using JS, the searchbox and contactsmenu icon are coded into `layout.user.php`. As an app there is no API to insert these icons, and thus the order isn't guaranteed.

It would improve the cleanness and stability of the code if there was an official API to do this.
However, it isn't sure if it's a good idea to provide this API, since there are the normal app icons already (see https://github.com/nextcloud/server/issues/6426#issuecomment-329145871)

What do you think?

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
As said in that issue already:

> An API to inject icons there is not likely something we will do because we already have apps on the left, and having more on the right will lead to issues on smaller screens or mobile - and in general too much stuff floating around in the header.

For example even for the JSXC chat app, I would prefer if we can move almost all functionality that the right sidebar (roster view) of that app into the Contacts popover. And the rest like status, personal settings could go in the Personal menu like a first entry (as @MariusBluem also sketched somewhere before).

**Comment by MorrisJobke** [comment]
Let's focus on bringing it to the contacts popover and close this one here.

**Comment by skjnldsv** [comment]
Hum, I think it would be a good idea. We should advise against unnecessary use of icons on this section, but if an app wants to do it, at least we should provide a clean way for it to do so! :/

**Comment by MorrisJobke** [comment]
> Hum, I think it would be a good idea. We should advise against unnecessary use of icons on this section, but if an app wants to do it, at least we should provide a clean way for it to do so! :/

Let's do it once there is a good reason to add something there. Until then we have a lot of other things on our list ;)

**Comment by jancborchardt** [comment]
Agree with @MorrisJobke. Plus, if we provide a clean way of doing something, people _will_ do it. But we want to discourage adding more icons there. We are already fighting to properly integrating things which are all over the place (see the Files sidebar with the multiple tabs. :\
