### ISSUE TITLE
E-Mail-Server not working with Gmail

### ISSUE THREAD

**Issue by joekerna** [nextcloud/server#6494]
### Steps to reproduce
1. Turn off 2-Factor authentication and allow "insecure-apps" in Gmail
2. Enter SMTP Settings for Gmail according to [this](https://support.google.com/mail/answer/7126229?hl=en)
3. Click save

### Expected behaviour
Nextcloud should accept settings and be able to send Email Notifications and test eMail

### Actual behaviour
Error message (German):
Beim Senden der E-Mail ist ein Problem aufgetreten. Bitte überprüfe Deine Einstellungen. (Fehler: Connection could not be established with host smtp.gmail.com [ #0])

I remember it was working fine on a previous version of Nextcloud.
The issue does not seem to be the particular Gmail account because I've tried different accounts.

### Server configuration

**Operating system**: Ubuntu 17.04

**Web server:** Nginx 1.12.1

**Database:** MySQL

**PHP version:** 7.1.9.1

**Nextcloud version:** (see Nextcloud admin page) 12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated since Nextcloud 10 (I think)

**Where did you install Nextcloud from:** Nextcloud website

**Comment by joekerna** [comment]
I've managed to get it working with _postfix_ which is ok for me. It might still be helpful to have it working for users who are not experienced with postfix.

**Comment by LukasReschke** [comment]
This seems more like a configuration problem, please ask such questions at https://help.nextcloud.com.

**Comment by ApesRex** [comment]
Please open again!
I have the same problem with 15.0.4.

**Comment by joekerna** [comment]
For me it's still working with 15.0.4.  @ApesRex can you provide more information?

**Comment by aconitumnapellus** [comment]
> For me it's still working with 15.0.4. @ApesRex can you provide more information?

Not possible, log is empty, even after enabling the debug option for SMTP.
PHP-FPM Log is empty too, nginx says nothing. Its not possible to provide more information.

I try to increase the verbosity level till i get something.
