### ISSUE TITLE
Share info is overlapping filename when sidebar is opened

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#6498]
* having a received share (the name of the owner is shown in the file list)
* open the sidebar for this file
* actual: sometimes the filename is overlapped by the share info
* expected: filename should get cropped and an ellipsis should be added

![bildschirmfoto 2017-09-14 um 11 14 14](https://user-images.githubusercontent.com/245432/30421778-24253f98-993e-11e7-9712-bf03f98aab17.png)

----

![bildschirmfoto 2017-09-14 um 11 14 02](https://user-images.githubusercontent.com/245432/30421777-2401f70e-993e-11e7-946e-826302c8368d.png)

cc @nextcloud/designers Do you have an idea how to implement this?

**Comment by skjnldsv** [comment]
Switch to a full flex table? :D

**Comment by MorrisJobke** [comment]
> Switch to a full flex table? :D

Best would be a short term solution for stable12 as well and a proper solution like the flex table. :/

**Comment by skjnldsv** [comment]
I can't reproduce, the name is correctly ellipsed on my install.

**Comment by MorrisJobke** [comment]
> I can't reproduce, the name is correctly ellipsed on my install.

When opening the sidebar or when shrinking the window?

**Comment by skjnldsv** [comment]
Hum, if I shrink the window, I lose all of the buttons actually.
![capture d ecran_2017-09-14_11-50-12](https://user-images.githubusercontent.com/14975046/30423354-e1284cc6-9942-11e7-86c7-1e153b44933d.png)

**Comment by skjnldsv** [comment]
We should definitely rework on this from scratch.
To sketch everything and decide what we want to hide/show on smaller screens.

**Comment by jancborchardt** [comment]
I also can't reproduce this. But also what's the delete icon directly there in the row? Maybe it has to do with some customization?

**Comment by jancborchardt** [comment]
Ah ok, can see now. Seems we need to adjust the thresholds again. Will then also ellipsize the sharer name so it works with that.

**Comment by skjnldsv** [comment]
What do we want here then! :)
Do we want to see the full part of the table? like the size ... and so one? Or are we ok hiding it by the sidebar on narrow screens?

**Comment by jancborchardt** [comment]
@skjnldsv exactly: First, the modified & size info hides, then the sharer name too. All of this hides at once at the moment.

I’m looking into ellipsizing the sharer name currently.

**Comment by jancborchardt** [comment]
Fix is at https://github.com/nextcloud/server/pull/6506 :)
