### ISSUE TITLE
Internal Server Error on new installation of 10.0beta

### ISSUE THREAD

**Issue by atroxix** [nextcloud/server#650]
### Steps to reproduce
1. Install 10.0beta
2. Configure
3. Go to site

### Expected behaviour
Some setup page should be shown, I guess?

### Actual behaviour
Getting Internal Server Error

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache2

**Database:** MySQL 5.5.50

**PHP version:** 5.5.9

**Nextcloud version:** 

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** downloaded beta tar.bz2

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```

```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>
```
[Fri Jul 29 08:55:40.248737 2016] [:error] [pid 21098] [client 37.157.73.253:54746] PHP Warning:  Expected user_input to be a string, NULL given in /var/www/nextcloud-10.0beta/3rdparty/symfony/polyfill-php56/Php56.php on line 33, referer: https://mynextcloud/
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
{"reqId":"smXR9bDa\/soafwDvKTAA","remoteAddr":"37.157.73.253","app":"PHP","message":"session_name(): session.name cannot be a numeric or empty '' at \/var\/www\/nextcloud-10.0beta\/lib\/private\/Session\/Internal.php#45","level":3,"time":"July 29, 2016 07:55:40","method":"GET","url":"\/index.php","user":"--"}
{"reqId":"smXR9bDa\/soafwDvKTAA","remoteAddr":"37.157.73.253","app":"index","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Session has been closed - no further changes to the session are allowed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud-10.0beta\\\/lib\\\/private\\\/Session\\\/Memory.php(52): OC\\\\Session\\\\Memory->validateSession()\\n#1 \\\/var\\\/www\\\/nextcloud-10.0beta\\\/lib\\\/private\\\/Security\\\/CSRF\\\/TokenStorage\\\/SessionStorage.php(63): OC\\\\Session\\\\Memory->set('requesttoken', 'iFzt7nxlnWnFNdd...')\\n#2 \\\/var\\\/www\\\/nextcloud-10.0beta\\\/lib\\\/private\\\/Security\\\/CSRF\\\/CsrfTokenManager.php(57): OC\\\\Security\\\\CSRF\\\\TokenStorage\\\\SessionStorage->setToken('iFzt7nxlnWnFNdd...')\\n#3 \\\/var\\\/www\\\/nextcloud-10.0beta\\\/lib\\\/public\\\/Util.php(505): OC\\\\Security\\\\CSRF\\\\CsrfTokenManager->getToken(*** sensitive parameters replaced ***)\\n#4 \\\/var\\\/www\\\/nextcloud-10.0beta\\\/lib\\\/private\\\/legacy\\\/template.php(79): OCP\\\\Util::callRegister()\\n#5 \\\/var\\\/www\\\/nextcloud-10.0beta\\\/lib\\\/private\\\/legacy\\\/template.php(306): OC_Template->__construct('', 'error', 'guest')\\n#6 \\\/var\\\/www\\\/nextcloud-10.0beta\\\/lib\\\/base.php(678): OC_Template::printGuestPage('', 'error', Array)\\n#7 \\\/var\\\/www\\\/nextcloud-10.0beta\\\/lib\\\/base.php(1024): OC::init()\\n#8 \\\/var\\\/www\\\/nextcloud-10.0beta\\\/index.php(37): require_once('\\\/var\\\/www\\\/nextcl...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud-10.0beta\\\/lib\\\/private\\\/Session\\\/Memory.php\",\"Line\":119}","level":3,"time":"July 29, 2016 07:55:40","method":"GET","url":"\/index.php","user":"--"}
{"reqId":"smXR9bDa\/soafwDvKTAA","remoteAddr":"37.157.73.253","app":"PHP","message":"Expected user_input to be a string, NULL given at \/var\/www\/nextcloud-10.0beta\/3rdparty\/symfony\/polyfill-php56\/Php56.php#33","level":3,"time":"July 29, 2016 07:55:40","method":"GET","url":"\/index.php","user":"--"}
{"reqId":"Stu2KkDaSRCB9u\/oX5Id","remoteAddr":"","app":"PHP","message":"Expected user_input to be a string, NULL given at \/var\/www\/nextcloud-10.0beta\/3rdparty\/symfony\/polyfill-php56\/Php56.php#33","level":3,"time":"July 29, 2016 10:50:27","method":"--","url":"--","user":"--"}
```
</details>

@LukasReschke

**Comment by atroxix** [comment]
BTW, I got this error when I configured NextCloud manually in config.php. When I gave the www user write permissions to the config folder then it's OK.

So I guess I shouldn't have tried to configure it myself? :)

**Comment by tflidd** [comment]
> So I guess I shouldn't have tried to configure it myself? :)

Normally, you run the setup-script which creates a config.php. After that you can change settings and perhaps other options from config.php.sample. You can also use the occ-command to install Nextcloud if you intend to deploy a larger number of setups.

**Comment by MorrisJobke** [comment]
I get following when the config dir misses the write permission:

![bildschirmfoto 2016-09-14 um 09 33 40](https://cloud.githubusercontent.com/assets/245432/18503657/735bb1c8-7a5e-11e6-8680-3304775368cf.png)

@atroxix Does this still occur? I tested this by `chmod -w config/` and tried to setup Nextcloud. Please also provide some easy steps how you did it.

I will close this for now and we reopen this if there is more information.

**Comment by atroxix** [comment]
In my case the problem was purely error 500 not the one shown last, so for me the issue is resolved.
