### ISSUE TITLE
User management: Full name can not be changed

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#6505]
Current master. Try changing the full name of a user. The input field won’t disappear, and this is the error response:
![screenshot from 2017-09-14 15-46-42](https://user-images.githubusercontent.com/925062/30433289-62e54f5e-9964-11e7-9af3-7d457b07db25.png)

@icewind1991 @blizzz @rullzer

**Comment by MorrisJobke** [comment]
Looks like a fall out of #6406

Please try to reset nextcloud and test again.
