### ISSUE TITLE
Caldav - calendar sync on ios not working with special chars in password

### ISSUE THREAD

**Issue by btk999** [nextcloud/server#6510]
Hi,

not sure if im in the right section here, i just recognized a problem and wanted to let you know :)

The Caldav-Sync does not work on iphone with the provided link (in my case its https://cloud.abc.tld/remote.php/dav/principals/users/me/), if the user password contains a special char (in my case it was "ü").

So with **ü** in the pw: error msg on iphone, without (just Test123 for example) it works fine.

im using nextcloud 12.0.2 on nginx with the provided config of the nextcloud manual and mariadb, php7, no 2-factor-auth.

Maybe you can check this and see if you can reconstruct my issue?

Thanks!

**Comment by blizzz** [comment]
IIRC things can be difficult with Basic Auth and Umlauts/non-Latin1 characters. Best is you create an App password and use it instead.

**Comment by skjnldsv** [comment]
Solution is to use app password. Please do as this is the proper secure behaviour
