### ISSUE TITLE
Quota message displays incorrectly in Italian localization

### ISSUE THREAD

**Issue by FranceX** [nextcloud/server#6511]
### Steps to reproduce
1. Set quota to account,
2. With that account visit the profile page
2. Change language to Italian

### Expected behaviour
Quota message shows (xx%) in bold font

### Actual behaviour
Quota message shows (strong>xx%), no bold font
![schermata 2017-09-14 alle 17 53 19](https://user-images.githubusercontent.com/501958/30443834-37951088-9981-11e7-854b-332e7cc60cd9.png)

### Server configuration
New install in root folder with url rewrite (cf config underneath)

**Operating system**:
Ubuntu 16.04
**Web server:**
Apache 2.
**Database:**
mariadb-server
**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
12.0.2

**Where did you install Nextcloud from:**
tarball from nextcloud website

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - impersonate: 1.0.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - encryption
  - files_external
  - theming
  - twofactor_totp
  - twofactor_u2f
  - user_external
  - user_saml
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "nextcloud",
                "autocreate": true,
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "hostname": "***REMOVED SENSITIVE VALUE***",
                "port": 9001,
                "use_ssl": false,
                "use_path_style": true
            }
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "overwriteprotocol": "https",
        "trusted_domains": [
            ""***REMOVED SENSITIVE VALUE***""
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/my.hostname.com",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "12.0.2.0",
        "dbname": "nextcloud",
        "dbhost": "mysqlhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false
    }
}
</details>

### Client configuration
**Browser:**
Chrome & Safari
**Operating system:**
macOS 12

**Comment by FranceX** [comment]
BTW it seems a typo, It should be simply a question of changing 
`(strong>%s` %%</strong>) 
to
`(<strong>%s` %%</strong>)

in line 314 of 
https://github.com/nextcloud/server/blob/master/settings/l10n/it.js &
https://github.com/nextcloud/server/blob/master/settings/l10n/it.json

**Comment by rullzer** [comment]
We do our translations in transifex. I modified it there and should be synced this night.

**Comment by FranceX** [comment]
perfect! :)
