### ISSUE TITLE
Security missing .gitignore

### ISSUE THREAD

**Issue by mareb** [nextcloud/server#6513]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
After Update (via Web) to version 12.0.2 /index.php/settings/integrity/failed

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- calendar
	- FILE_MISSING
		- .gitignore

Raw output
==========
Array
(
    [calendar] => Array
        (
            [FILE_MISSING] => Array
                (
                    [.gitignore] => Array
                        (
                            [expected] => 2ebfa9d965d970eb2f3356f80cbff785c90c9a0d7634b406e49cd4e311826eb4abb482d8be75557cff491837881af2795fc4bd3a8e8d42b24c56d3b53b9b5dee
                            [current] => 
                        )

                )

        )

)

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**: Ubuntu 16.04.3 LTS

**Web server: Apache 2 **

**Database: MariaDB**

**PHP version: PHP 7.0.22** 

**Nextcloud version:** 12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 12.0

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by yan12125** [comment]
I was hit by the bug, too. I installed nextcloud and nextcloud-app-calendar from Arch Linux packages. [1][2]

The cause might be https://github.com/nextcloud/calendar/commit/bd798a42ca540abf067608fcc313c6897c7dfb57. As ```sign-app``` includes .gitignore while ```tar``` doesn't, installations from tarballs get missing-file errors, which is the case of the Arch Linux package.

[1] https://www.archlinux.org/packages/community/any/nextcloud/
[2] https://www.archlinux.org/packages/community/any/nextcloud-app-calendar/

**Comment by j-ed** [comment]
Best would be to address Calendar app problems under the Calendar repository (https://github.com/nextcloud/calendar/issues) and not the Server repository in the future. This might be the reason why you haven't seen the issue ticket https://github.com/nextcloud/calendar/issues/600 which already covers the described problem.

**Comment by yan12125** [comment]
Thanks for the link. I searched "signature.json" and "sign-app" in https://github.com/nextcloud/calendar/ and got nothing, so I wrongly thought no one reported it.

**Comment by yan12125** [comment]
Maybe a better fix is adding ```.gitignore``` to [ExcludeFileByNameFilterIterator](https://github.com/nextcloud/server/blob/master/lib/private/IntegrityCheck/Iterator/ExcludeFileByNameFilterIterator.php#L40-L45). ```.gitignore```  is not used at all for non-developers. And it saves app developers from being busy excluding the irrelevant file during packaging.

**Comment by MorrisJobke** [comment]
Duplicate of https://github.com/nextcloud/calendar/issues/600
