### ISSUE TITLE
Exclude skeleton directory from integrity check

### ISSUE THREAD

**Issue by afle** [nextcloud/server#6514]
### Steps to reproduce
1. delete files from core/skeleton/

### Expected behaviour
Example files in skeletons directoy shouldn't be included in integrity filecheck.

### Actual behaviour
Deleted files of skeleton directory causing a failure of integrity check:

FILE_MISSING:
core/skeleton/Documents/About.odt:
expected: 1cc2eae96696437edac41a8f9bc04a2ce2e8aac132cee19239222ef0f0ed0722a8279d6dae2073c230f9f2015f03559827a4bdd11ac068d2ee31f8bef9ec8b95
current:
core/skeleton/Documents/About.txt:
expected: 246d73856029aac8fb5cfda0644c473bcc519017b8284e0b850b67025562170cf4c1afa39f037cff3c9a331f85ab29266353de184c039907a54a680a54c15040
current:
core/skeleton/Photos/Coast.jpg:
expected: 2bb4fd0ca9fbcb71b3565f1c019233aac9d22d19e25a6c1afe1ba37dbe33a2d282ead22aafd6e5a012bb206c9606f1056d9f83955034a11d2c531d435f097933
current:
core/skeleton/Photos/Hummingbird.jpg:
expected: 4c5c440aabadb7bc084502513f34691754ad0cd5b7dc60af5294c5076e17e102d209b2fec4d1a1f38b940887c6f8eb16efa9240944116d17e6c4a36689987d84
current:
core/skeleton/Photos/Nut.jpg:
expected: 0a82a718fc89d438c5887bac2b4fe7f32ec39a3cf9aab38e7f544ed8493d328d2247fa4efa85d4caa650550c34f305ba7eb12973d2487e10507cb2ab0f38c122
current:

### Server configuration

**Operating system**: Ubuntu 16.04.3 LTS

**Web server:** Apache 2.4

**Database:** MariaDB

**PHP version:** 7.0.22

**Nextcloud version:** 12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 11.0.3

**Comment by MorrisJobke** [comment]
If you want to manipulate the skeleton files, then specify a different skeleton directory and place the files you want in there. And please put that dir outside of the nextcloud directory but still accessible by the web server user.

https://github.com/nextcloud/server/blob/master/config/config.sample.php#L241-L248

**Comment by bcutter** [comment]
What about the ‘integrity.excluded.files’ array in config.php the Ownclouders have?
(just migrated to Nextcloud a few days ago and I´m missing this option quite well)
