### ISSUE TITLE
External Storage: unable to stat mounted shared folders in vm (/mnt/hgfs)

### ISSUE THREAD

**Issue by NoFunk** [nextcloud/server#6516]
Hi all, in short I shared a folder from my Windows OS inside a Ubuntu Server 16.04.3 LTS VM, Nextcloud is in a docker container (image is nextcloud:latest so 12.0/apache) using different volumes for config, data, ... and the traffic is routed from nginx,

The mount on Ubuntu is: /mnt/hgfs/Comic and using external storage I am unable to get it working and unable to get the content of it. Also due to limitations with vmware I can't change the ownership of a mounted shared folder and its contents, it stays as root whatever I try so unable to get it owned by www-data (gid 33) unless mounted in a different directory see comment 2.

![844ce19fc13c38a6077d83c99bd0e5b1e8f1b965_1_690x124](https://user-images.githubusercontent.com/20627302/30476238-b54fe0ce-9a09-11e7-9521-11d94cb5516b.png)

![2017-09-14_18-05-27](https://user-images.githubusercontent.com/20627302/30476245-b85e327a-9a09-11e7-93ec-1db29b57749f.png)

When I use the full path: /mnt/hgfs/Comic it fails and returns:
`stat(): stat failed for /mnt/hgfs/Comic/ at /var/www/html/lib/private/Files/Storage/Local.php#135`

When I use the path /mnt/hgfs it fails and return:
`stat(): stat failed for /mnt/hgfs/ at /var/www/html/lib/private/Files/Storage/Local.php#135`

When I use the path /mnt/ it looks like working and doesn't throw an error, I can access the folder but it is empty: not getting the /hgfs/Comic

Any idea why it could fail ?

If I look at the error it points me toward line 135 of:
[https://github.com/nextcloud/server/blob/master/lib/private/Files/Storage/Local.php](https://github.com/nextcloud/server/blob/master/lib/private/Files/Storage/Local.php)

```
	public function stat($path) {
		clearstatcache();
		$fullPath = $this->getSourcePath($path); **---> This is line 135**
		$statResult = stat($fullPath);
		if (PHP_INT_SIZE === 4 && !$this->is_dir($path)) {
			$filesize = $this->filesize($path);
			$statResult['size'] = $filesize;
			$statResult[7] = $filesize;
		}
		return $statResult;
	}
```

Where the getSourcePath function is: 

```
	/**
	 * Get the source path (on disk) of a given path
	 *
	 * @param string $path
	 * @return string
	 * @throws ForbiddenException
	 */
	public function getSourcePath($path) {
		$fullPath = $this->datadir . $path;
		if ($this->allowSymlinks || $path === '') {
			return $fullPath;
		}
		$pathToResolve = $fullPath;
		$realPath = realpath($pathToResolve);
		while ($realPath === false) { // for non existing files check the parent directory
			$pathToResolve = dirname($pathToResolve);
			$realPath = realpath($pathToResolve);
		}
		if ($realPath) {
			$realPath = $realPath . '/';
		}
		if (substr($realPath, 0, $this->dataDirLength) === $this->realDataDir) {
			return $fullPath;
		}
		\OCP\Util::writeLog('core', "Following symlinks is not allowed ('$fullPath' -> '$realPath' not inside '{$this->realDataDir}')", \OCP\Util::ERROR);
		throw new ForbiddenException('Following symlinks is not allowed', false);
	}

```

Wondering if this could be somehow related to symlinks being set to false..

```
/**
 * for local filestore, we only have to map the paths
 */
class Local extends \OC\Files\Storage\Common {
	protected $datadir;
	protected $dataDirLength;
	protected $allowSymlinks = false;
	protected $realDataDir;

```

Structure:

```
nofunk@ubuntu:~$ df -hT
Filesystem     Type              Size  Used Avail Use% Mounted on
/dev/sda1      ext4               77G   22G   52G  30% /
...
vmhgfs-fuse    fuse.vmhgfs-fuse  1.9T  1.7T  125G  94% /mnt/hgfs

nofunk@ubuntu:~$ ll /mnt/
total 17
drwxr-xr-x  4 root root 4096 Sep 13 22:53 ./
drwxr-xr-x 23 root root 4096 Sep 14 00:52 ../
drwxr-xr-x  2 root root 4096 Sep 13 22:52 cdrom/
dr-xr-xr-x  1 root root 4192 Sep 15 11:56 hgfs/
nofunk@ubuntu:~$ ll /mnt/hgfs/
total 13
dr-xr-xr-x 1 root root 4192 Sep 15 11:56 ./
drwxr-xr-x 4 root root 4096 Sep 13 22:53 ../
drwxrwxrwx 1 root root 4096 Sep 12 13:52 Comic/
nofunk@ubuntu:~$ ll /mnt/hgfs/Comic/
total 165
drwxrwxrwx 1 root root  4096 Sep 12 13:52 ./
dr-xr-xr-x 1 root root  4192 Sep 15 11:56 ../
drwxrwxrwx 1 root root 12288 May 28 15:13 xxxx/
...
drwxrwxrwx 1 root root 32768 Jul 23 20:59 xxxx/
```

**Comment by NoFunk** [comment]
Ok so if I try to mount it directly in my Nextcloud data directory owned by www-data:

> sudo mount -t fuse.vmhgfs-fuse .host:/Comic /home/nofunk/docker/nextcloud/data/NoFunk/files/Comics/comic2 -o allow_other,uid=33,gid=33

It does not follow the symlink - which is by default. And the scan doesn't take them into effect either although correctly owned.

When I mount this directoy as /mount/comic directory & sub-directories owned by www-data:

> sudo mount -t fuse.vmhgfs-fuse .host:/Comic /mounts/comic -o allow_other,uid=33,gid=33

> nofunk@ubuntu:/mounts$ ll
> total 12
> drwxr-xr-x  3 root     root     4096 Sep 17 13:05 ./
> drwxr-xr-x 24 root     root     4096 Sep 17 13:05 ../
> drwxrwxrwx  1 www-data www-data 4096 Sep 12 13:52 comic/

and then specify /mounts/comic in External storage:
![2017-09-17_13-13-13](https://user-images.githubusercontent.com/20627302/30520268-8550c2e2-9baa-11e7-9446-24d57990a3bb.png)

Getting the same error:

> stat(): stat failed for /mounts/comic/ at /var/www/html/lib/private/Files/Storage/Local.php#135

It doesn't work either that way - So is there actually a way to have Nextcloud take into account shared folders within the VM or am I missing something ?

**Comment by NoFunk** [comment]
Using SFTP works though but not using local in External storage

**Comment by DeRain** [comment]
@NoFunk same issue here. I've user fuse for mounting s3 folder (because it's working pretty faster). Did you find solution for this?
