### ISSUE TITLE
Update to 12.0.2: Problems with oauth2 and calendar

### ISSUE THREAD

**Issue by MaWo2** [nextcloud/server#6519]
Hello everybody.

I have some problems with the update to NC 12.0.2. The oauth2 app cannot be activated and the calendar Triggers a Code-Integrity warning.

Best

MaWo2

### Steps to reproduce
1. NC 12.0.1 start Updater from Admin page (web updater from frontend)
2.
3.

### Expected behaviour
Update NC 12.0.1 to 12.0.2

### Actual behaviour
Update proceeded, but finished with warning:
"oauth2: Failed to enable app oauth2
Das Update ist fehlgeschlagen. Bitte melden Sie dieses Problem an die Nextcloud Community."

Refresh of the Maintenance-Mode-Screen logged me into the cloud again, but triggered the Warning "Bei der Code-Integritätsprüfung sind Probleme aufgetreten."

### Server configuration
Nextcloud-Provider: PixelX (Germany)

**Nextcloud version:** (see Nextcloud admin page)
12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 12.0.1.5

**Where did you install Nextcloud from:**
Web-Updater

### Error-Logs from Update-Process (only Errors, everything else was just "Info"):

Error updater \OC\Updater::failure: oauth2: Failed to enable app oauth2 2017-09-15T13:50:34+0200 

Error oauth2 OC\HintException: Failed to enable app oauth20./var/www/vhosts/mydomain.tld/httpdocs/lib/private/Installer.php - line 501:  OC\Installer installShippedApp('oauth2')
1./var/www/vhosts/mydomain.tld/httpdocs/lib/private/Updater.php - line 272:  OC\Installer installShippedApps(true)
2./var/www/vhosts/mydomain.tld/httpdocs/lib/private/Updater.php - line 130:  OC\Updater->doUpgrade('12.0.2.0', '12.0.1.5')
3./var/www/vhosts/mydomain.tld/httpdocs/core/ajax/update.php - line 206:  OC\Updater->upgrade()
4.{main}
 2017-09-15T13:50:34+0200 

Error PHP Cannot modify header information - headers already sent by (output started at /var/www/vhosts/mydomain.tld/httpdocs/lib/private/legacy/eventsource.php:76) at /var/www/vhosts/mydomain.tld/httpdocs/lib/private/User/Session.php#875 2017-09-15T13:50:23+0200 
Error PHP Cannot modify header information - headers already sent by (output started at /var/www/vhosts/mydomain.tld/httpdocs/lib/private/legacy/eventsource.php:76) at /var/www/vhosts/mydomain.tld/httpdocs/lib/private/User/Session.php#874 2017-09-15T13:50:23+0200 
Error PHP Cannot modify header information - headers already sent by (output started at /var/www/vhosts/mydomain.tld/httpdocs/lib/private/legacy/eventsource.php:76) at /var/www/vhosts/mydomain.tld/httpdocs/lib/private/User/Session.php#873 2017-09-15T13:50:23+0200 
Error PHP Cannot modify header information - headers already sent by (output started at /var/www/vhosts/mydomain.tld/httpdocs/lib/private/legacy/eventsource.php:76) at /var/www/vhosts/mydomain.tld/httpdocs/lib/private/User/Session.php#870 2017-09-15T13:50:23+0200 
Error PHP Cannot modify header information - headers already sent by (output started at /var/www/vhosts/mydomain.tld/httpdocs/lib/private/legacy/eventsource.php:76) at /var/www/vhosts/mydomain.tld/httpdocs/lib/private/User/Session.php#869 2017-09-15T13:50:23+0200 
Error PHP Cannot modify header information - headers already sent by (output started at /var/www/vhosts/mydomain.tld/httpdocs/lib/private/legacy/eventsource.php:76) at /var/www/vhosts/mydomain.tld/httpdocs/lib/private/User/Session.php#868 2017-09-15T13:50:23+0200 

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- calendar
	- FILE_MISSING
		- .gitignore

Raw output
==========
Array
(
    [calendar] => Array
        (
            [FILE_MISSING] => Array
                (
                    [.gitignore] => Array
                        (
                            [expected] => 2ebfa9d965d970eb2f3356f80cbff785c90c9a0d7634b406e49cd4e311826eb4abb482d8be75557cff491837881af2795fc4bd3a8e8d42b24c56d3b53b9b5dee
                            [current] => 
                        )

                )

        )

)
```

**List of activated apps:**
Activity 2.5.2
Collaborative tags 1.2.0
Comments 1.2.0
Default encryption module 1.6.0
Deleted files 1.2.0 
External storage support 1.3.0
Federation 1.2.0
File sharing 1.4.0
First run wizard 2.1
Gallery 17.0.0
Log Reader 2.0.0
Monitoring 1.2.0
Nextcloud announcements 1.1
Notifications 2.0.0
Password policy 1.2.2
PDF viewer 1.1.1
Share by mail 1.2.0
Text editor 2.4.1
Theming 1.3.0
Update notification 1.2.0
Usage survey 1.0.0
Versions 1.5.0
Video player 1.1.0
Brute-force settings 
Calendar 1.5.4
Checksum 0.3.5
Contacts 1.5.3
Notes 2.3.1
Tasks 0.9.5
Two Factor TOTP Provider 1.3.1
Two Factor U2F 1.3.3

**Are you using external storage, if yes which one:** webdav

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no
### Client configuration
**Browser:** IE11

**Operating system:** Windows 8.1 Pro 64

**Comment by MorrisJobke** [comment]
cc @ChristophWurst @LukasReschke @rullzer

**Comment by ChristophWurst** [comment]
I'm closing this ticket because it hasn't received any updates in a long time. If this is still relevant, feel free to re-open or file a new ticket.

Thank you.
