### ISSUE TITLE
[12.0.3RC2] Avatars in Activities tab are rendered kaput

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#6526]
![spectacle c29893](https://user-images.githubusercontent.com/2184312/30489535-bcce33ea-9a37-11e7-8f55-16ca5766cafe.png)

In the image source, the username is missing, e.g. ``/avatar//69`` is shown instead of ``/avatar/johndoe/69``

**Comment by MorrisJobke** [comment]
Let's move this over to 12.0.4

**Comment by blizzz** [comment]
Saw it also working again today on our instance.

**Comment by MorrisJobke** [comment]
Let's close it for now, because I can't reproduce here.
