### ISSUE TITLE
External storage issue

### ISSUE THREAD

**Issue by kennethlknight** [nextcloud/server#6529]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
when I click on the folder in the external storage section it should show the subfiles and folders

### Actual behaviour
when I click on the folder in external storage it just goes back to the files homepage in nextcloud. it doesn't open the folder at all. this is a folder that is connected through the smbclient

### Server configuration

**Operating system**: 
ubuntu 16.04

**Web server:**
apache

**Database:**
mysql maria

**PHP version:**7.0

**Nextcloud version:** (see Nextcloud admin page)
12

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
nextcloud website

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by xXSTrikeXx** [comment]
nothing in the logs? There should be a way to reproduce the mistake ;)

**Comment by kennethlknight** [comment]
Nothing in the logs. and I found out it work of the external share in on a Linux server but not if its on a windows server. and It's a really basic setup i didn't do any customization yet, so the reproducing should be easy i guess. its basic windows shares and basic nextcloud setup. I made sure that the credentials that I'm using have full access in the windows share.

**Comment by jm009** [comment]
It works, if the external share is on a Linux server.
It doesn't work, if the external share is on a Windows server. What Windows version is it?

**Comment by MorrisJobke** [comment]
We tried to reproduce this, but can't do so. Thus I will close this one here for now. Once you have more information about this we are happy to reopen this ticket and have another look for some suspicious configurations. Maybe you also want to seek for help in the setup in our forums at https://help.nextcloud.com
