### ISSUE TITLE
Sharing dropdown leaks email addresses of users in other groups

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#6530]
When a user has an email address set in her profile users in other groups can see her full name and email address through the sharing dropdown of the details view of the _Files_ app even if _"Restrict users to only share with users in their groups"_ is enabled in the _"Sharing"_ section of the administration settings.

It seems that _getEmail_ in _apps/files_sharing/lib/Controller/ShareesAPIController.php_ does not honour the _shareapi_only_share_with_group_members_ configuration value.

### Steps to reproduce
1. Log in as the admin and enable _"Restrict users to only share with users in their groups"_ in the _"Sharing"_ section of the administration settings
2. Create a user _group1-user1_ belonging to group _group1_
2. Create a user _group2-user2_ belonging to group _group2_
3. Log in as user _group1-user1_, open the _"Personal info"_ section of the settings, and set the full name to _group1-fullname1_ and the email address to _group1-mail1@settings.com_
4. Log in as user _group2-user2_ and open the _"Sharing"_ tab of the details view of the _Files_ app
5. In the sharing input field, type _full_ or _mail_

### Expected behaviour

No result appears in the sharing dropdown (like what happens after #5585 if _full_ or _mail_ is typed in the contacts menu instead).

### Actual behaviour

In both cases, _"group1-fullname1 (group1-mail1@settings.com)"_ appears in the dropdown, although that user belongs to a different group than the current user.

**Comment by BornToBeRoot** [comment]
Will this be fixed in NC12 ?

**Comment by danxuliu** [comment]
>  Will this be fixed in NC12 ?

Yes, once fixed for Nextcloud 13 it should be backported to Nextcloud 12.

**Comment by LEDfan** [comment]
This is the same bug which caused https://github.com/nextcloud/server/issues/7428 and is fixed in Nextcloud 12.0.5 and NC 13 beta 4.

**Comment by muppeth** [comment]
Sorry for reopening, but I just noticed that the dropdown still leaks data on nextcloud 12.05 It still autocompletes usernames (LDAP) even though autocompletion has been disabled in sharing settings.
