### ISSUE TITLE
txt(gbk_ansi) file preview have garbled

### ISSUE THREAD

**Issue by fcying** [nextcloud/server#6531]
### Steps to reproduce
1. upload test txt file
2. preview txt file

### Expected behaviour
display right.

### Actual behaviour
test file title is right, content have garbled.
txt create by windows default encoding is gbk_ansi.
if I change file encoding to utf-8, it display right.

gbk_ansi file:
![1](https://user-images.githubusercontent.com/106934/30510010-1d6a541a-9aef-11e7-94e5-74db0463dae4.png)

utf-8 file:
![2](https://user-images.githubusercontent.com/106934/30510012-22dff058-9aef-11e7-862b-8f80b4820cab.png)

test_file:
[test_file.zip](https://github.com/nextcloud/server/files/1308147/test_file.zip)

### Server configuration
docker nextcloud:latest
ubuntu 16.04
sqlite

**Comment by j-ed** [comment]
I had a look on your files on my server (LANG=C; LC_CTYPE=de_DE.UTF-8):
```
# file --mime-type --mime-encoding test_ansi_*txt
test_ansi_��-�.txt: text/plain; charset=iso-8859-1

# file --mime-type --mime-encoding test_utf_8_*txt
test_utf_8_��-�.txt: text/plain; charset=utf-8
```
Beside the fact that the files names aren't correctly displayed on my system the gbk_ansi file is recognized as normal iso-8859-1 encoded file. I wonder what mechanism can be used to reliable identify the base encoding of the file?! I think you have to wait for a comment of the Nextcloud specialists.

**Comment by fcying** [comment]
@j-ed  I open the file by gvim in windows10 or vim in ubuntu 16.04,  the file encoding is "cp936(gbk)"

![ansi](https://user-images.githubusercontent.com/106934/30520751-ddf71f22-9be6-11e7-88e0-dc63e15a0037.jpg)

use file --mime-type --mime-encoding, result same with you.

**Comment by nickvergessen** [comment]
Please reopen your issue in the text editor repository: https://github.com/nextcloud/files_texteditor
