### ISSUE TITLE
Importing adress book entries via cardav does not create database entries

### ISSUE THREAD

**Issue by janlimpens** [nextcloud/server#6535]
### Steps to reproduce
1. Create empty installation
2. Add contacts app
2. Create address book
3. Connect to address book via caldav client (in my case macos contacts app) and import entries

### Expected behaviour
Cardav should work, contacts should show up in nc contacts app, database should be populated

### Actual behaviour
Cardav is correctly populated, but no entries in the database were created, so there is nothing to show in the contacts app

Maybe I am getting this wrong, but where does nc actually store it's data? Everything seems to work cardav side, but, when I create an entry in the address book in the nc web app, it shows up in the oc_cards_properties table, but only the one, all other imported entries don't.

### Server configuration

**Operating system**: Centos 10

**Web server:** Nginx

**Database:** Postgres

**PHP version:** 7.1

**Nextcloud version:** 12.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Where did you install Nextcloud from:** From nc web site

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Standard + Contacts, Calendar, Remote Activities
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.4
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_downloadactivity: 1.1.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - socialsharing_email: 1.0.1
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "xxx",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx.xxx.com"
        ],
        "datadirectory": "\/home\/xxx\/webapps\/xxx\/data",
        "overwrite.cli.url": "https:\/\/nc.xxx.com",
        "dbtype": "pgsql",
        "version": "12.0.2.0",
        "dbname": "xxx_xxx",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "nc",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "xxx.com"
    }
}
```
</details>

**Comment by blizzz** [comment]
@skjnldsv any idea? at least where to locate the issue… server (which component) or contacts app?

**Comment by skjnldsv** [comment]
Is there an error in the browser console when you open the contact app? If the synchronization works with dav , then this is an issue on the contacts app side.

**Comment by janlimpens** [comment]
The cause of the problem was, that the mac carddav/caldav clients cannot connect to my nextcloud server. I checked with a different dav application and it worked as expected. So the error is elsewhere.
