### ISSUE TITLE
Popover/tooltip arrow should also have a shadow

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#6539]
The small arrow shown next to the popover menus and tooltips should also have a drop shadow.

![bildschirmfoto vom 2017-09-17 19-22-19](https://user-images.githubusercontent.com/3404133/30523205-97e429f2-9bdd-11e7-8d44-93c6e1ca2d47.png)
![bildschirmfoto vom 2017-09-17 19-21-01](https://user-images.githubusercontent.com/3404133/30523207-99669d50-9bdd-11e7-9ecf-a76e141ff362.png)

@nextcloud/designers

**Comment by juliushaertl** [comment]
Fixed with https://github.com/nextcloud/server/pull/6669

**Comment by skjnldsv** [comment]
Thx, missed that!
