### ISSUE TITLE
iphone client can't worker on haproxy server, web browser is usable

### ISSUE THREAD

**Issue by breath-co2** [nextcloud/server#6546]
When I use haproxy listen port 443 and reverse proxy port 80 to nextcloud server. In browser it is usable, but iphone client can't worker. I have installed the last version of haproxy, it is still can't worker.  

It's my haproxy config: 
```
frontend https_frontend
	bind 0.0.0.0:443 ssl crt /etc/haproxy/my.pem
	mode http
	option httpclose
	option forwardfor
	reqadd X-Forwarded-Proto:\ https
	default_backend web_server

backend web_server
	mode http
	server s1 10.0.1.2:80 check
	server s2  10.0.1.3:80 check backup
```

**Comment by LukasReschke** [comment]
Please open an issue at help.nextcloud.com. That seems more setup related.
