### ISSUE TITLE
OCP\Lock\LockedException: "/themedbackgroundlogo" is locked

### ISSUE THREAD

**Issue by steppperl** [nextcloud/server#6555]
### Steps to reproduce
1. Update from 11.0.3 (if I remember well) to 12.0.3RC2
2. Web-update started, stopped with failure "/themedbackgroundlogo" is locked
3.

### Expected behaviour
Web-update should be successfull

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.01

**Nextcloud version:** (see Nextcloud admin page) 12.0.3RC2

**Updated from an older Nextcloud/ownCloud or fresh install:** Update

**Where did you install Nextcloud from:** Automatic update channel

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Enabled:
  - activity: 2.5.2
  - audioplayer: 2.0.2
  - bookmarks: 0.10.1
  - calendar: 1.5.4
  - checksum: 0.3.5
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - deck: 0.2.1
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1                                                                                                            
  - files_sharing: 1.4.0                                                                                                              
  - files_texteditor: 2.4.1                                                                                                           
  - files_trashbin: 1.2.0                                                                                                             
  - files_versions: 1.5.0                                                                                                             
  - files_videoplayer: 1.1.0                                                                                                          
  - firstrunwizard: 2.1                                                                                                               
  - gallery: 17.0.0                                                                                                                   
  - gpxedit: 0.0.7                                                                                                                    
  - gpxpod: 2.1.4                                                                                                                     
  - logreader: 2.0.0                                                                                                                  
  - lookup_server_connector: 1.0.0                                                                                                    
  - mail: 0.6.4
  - metadata: 0.5.0
  - music: 0.4.4
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: true
  - ocsms: 1.12.1
  - password_policy: 1.2.2
  - polls: 0.7.3
  - previewgenerator: 1.0.6
  - provisioning_api: 1.2.0
  - radio: 0.6.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.1.1
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - activitylog
  - admin_audit
  - apporder
  - direct_menu
  - encryption
  - files_downloadactivity
  - registration
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
{
    "system": {
        "instanceid": "ocemu9gnn9xt",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "clowd.stepane.de"
        ],
        "datadirectory": "\/var\/www\/html\/clowdia.stepane.de\/data",
        "overwrite.cli.url": "https:\/\/www.stepane.de\/clowdia.stepane.de",
        "dbtype": "mysql",
        "version": "11.0.4.1",
        "dbname": "clowdia",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "clowdia",
        "mail_smtpmode": "php",
        "mail_domain": "stepane.de",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "beta"
    }
}

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
cc @icewind1991 @nextcloud/theming

**Comment by mforde84** [comment]
any update on this? im experiencing the same issue.

OCP\Lock\LockedException: "/themedbackgroundlogo" is locked
Detailed logs
Preparing update
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updated "federatedfilesharing" to 1.2.0
Updated "files_pdfviewer" to 1.1.1
Updated "files_texteditor" to 2.4.1
Updated "files_videoplayer" to 1.1.0
Updated "password_policy" to 1.2.2
Updated "provisioning_api" to 1.2.0
Updated "serverinfo" to 1.2.0
Updated "survey_client" to 1.0.0
[1 / 0]: Copy twofactor backup codes from legacy table
[2 / 0]: Copy twofactor backup codes from legacy table
[3 / 0]: Copy twofactor backup codes from legacy table
[4 / 0]: Copy twofactor backup codes from legacy table
[5 / 0]: Copy twofactor backup codes from legacy table
[6 / 0]: Copy twofactor backup codes from legacy table
[7 / 0]: Copy twofactor backup codes from legacy table
[8 / 0]: Copy twofactor backup codes from legacy table
[9 / 0]: Copy twofactor backup codes from legacy table
[10 / 0]: Copy twofactor backup codes from legacy table
[11 / 0]: Copy twofactor backup codes from legacy table
[12 / 0]: Copy twofactor backup codes from legacy table
[13 / 0]: Copy twofactor backup codes from legacy table
[14 / 0]: Copy twofactor backup codes from legacy table
[15 / 0]: Copy twofactor backup codes from legacy table
[16 / 0]: Copy twofactor backup codes from legacy table
[17 / 0]: Copy twofactor backup codes from legacy table
[18 / 0]: Copy twofactor backup codes from legacy table
[19 / 0]: Copy twofactor backup codes from legacy table
[20 / 0]: Copy twofactor backup codes from legacy table
[21 / 0]: Copy twofactor backup codes from legacy table
[22 / 0]: Copy twofactor backup codes from legacy table
[23 / 0]: Copy twofactor backup codes from legacy table
[24 / 0]: Copy twofactor backup codes from legacy table
[25 / 0]: Copy twofactor backup codes from legacy table
[26 / 0]: Copy twofactor backup codes from legacy table
[27 / 0]: Copy twofactor backup codes from legacy table
[28 / 0]: Copy twofactor backup codes from legacy table
[29 / 0]: Copy twofactor backup codes from legacy table
[30 / 0]: Copy twofactor backup codes from legacy table
[31 / 0]: Copy twofactor backup codes from legacy table
[32 / 0]: Copy twofactor backup codes from legacy table
[33 / 0]: Copy twofactor backup codes from legacy table
[34 / 0]: Copy twofactor backup codes from legacy table
[35 / 0]: Copy twofactor backup codes from legacy table
[36 / 0]: Copy twofactor backup codes from legacy table
[37 / 0]: Copy twofactor backup codes from legacy table
[38 / 0]: Copy twofactor backup codes from legacy table
[39 / 0]: Copy twofactor backup codes from legacy table
[40 / 0]: Copy twofactor backup codes from legacy table
[40 / 40]: Copy twofactor backup codes from legacy table
Updated "twofactor_backupcodes" to 1.1.1
Updated "updatenotification" to 1.2.0
Updated "files" to 1.7.2
Updated "activity" to 2.5.2
[0 / 0]: Fix broken values of calendar objects
Updated "dav" to 1.3.0
Updated "files_sharing" to 1.4.0
Updated "files_trashbin" to 1.2.0
Updated "files_versions" to 1.5.0
Updated "sharebymail" to 1.2.0
Updated "workflowengine" to 1.2.0
Updated "admin_audit" to 1.2.0
Updated "comments" to 1.2.0
Updated "firstrunwizard" to 2.1
Updated "nextcloud_announcements" to 1.1
Updated "notifications" to 2.0.0
Updated "systemtags" to 1.2.0
OCP\Lock\LockedException: "/themedbackgroundlogo" is locked

**Comment by mforde84** [comment]
Tried deleting the filelocks in the nextcloud database: 

use nextcloud;
delete from oc_file_locks where 1;

but now the integrity fails at the code integrity check

**Comment by juliushaertl** [comment]
Closing since it has not occued elsewhere and it will not happen on coming versions with #8070
