### ISSUE TITLE
Full path appears in web UI

### ISSUE THREAD

**Issue by esprit-libre** [nextcloud/server#6560]
### Steps to reproduce
1. Upload files through web UI

### Actual behaviour
Some files appear with their full path and in grey. This happens for only one path, others does not have such problem.
![image](https://user-images.githubusercontent.com/12149036/30584720-e3fc6748-9d2a-11e7-9635-bff6e4903eb5.png)

Even if these files are in grey and with full path, I can open them in web UI (tested with PDF) and everything appears normal when downloading with nextcloud-client.
Firefox and Chromium are concerned.
This nextcloud instance comes from an owncloud upgrade, but files concerned by this issue have been uploaded after upgrade operations.

I don't see anything in server log. I tried setting LogLevel to 0 and then navigating to one file, but no log appears for this.

Could be linked to #5477 but not sure.

### General server configuration

**Operating system:** Debian 9

**Web server:** Apache/2.4.25 (Debian) (apache2handler)

**Database:** MariaDB 10.1.26

**PHP version:** 7.0.19-1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - apache2handler
 - mysqlnd
 - PDO
 - xml
 - apcu
 - apc
 - bz2
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - iconv
 - intl
 - json
 - exif
 - mcrypt
 - mysqli
 - pdo_mysql
 - Phar
 - posix
 - readline
 - shmop
 - SimpleXML
 - sockets
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.0 - 12.0.0.29

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from oc9.1.5 -> nc10.0.5 -> nc11.0.3 -> nc12.0.0
But files concerned by the issue have been uploaded after upgrade.

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.3
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - quota_warning: 1.0.1
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_audit
 - encryption
 - files_external
 - files_videoplayer
 - mail
 - nextcloud_announcements
 - survey_client
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "trusted_domains": [
        "files.xyz.fr",
    ],
    "datadirectory": "\/var\/www\/donnees",
    "overwrite.cli.url": "https:\/\/files.xyz.fr",
    "dbtype": "mysql",
    "version": "12.0.0.29",
    "dbname": "xyz",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "forcessl": true,
    "default_language": "fr",
    "theme": "",
    "maintenance": false,
    "secret": "***REMOVED SENSITIVE VALUE***",
    "logfile": "\/var\/logs\/nextcloud\/files.xyz.fr.log",
    "loglevel": 2,
    "logtimezone": "Europe\/Paris",
    "log_rotate_size": "5242880",
    "minimum.supported.desktop.version": "2.0.0",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "trashbin_retention_obligation": "auto, 31",
    "versions_retention_obligation": "auto, 31",
    "activity_expire_days": 365,
    "upgrade.disable-web": true
}
```
</details>

**Comment by blizzz** [comment]
Please upgrade, fixed in a maintenance version of NC 12.

**Comment by esprit-libre** [comment]
Ok. I confirm that 12.0.2 is ok.
Thanks
