### ISSUE TITLE
Inbound federated share shows »Delete« instead of »Unshare« in menu

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#6584]
I want to unshare a federated share I got, but it saying »Delete« instead of »Unshare« makes me worry what will happen when I click it. Especially since I have full permissions.

Of course what should happen is simply remove it in my Nextcloud and unlink it from the person who shared it with me.

cc @nextcloud/sharing @schiessle

**Comment by MorrisJobke** [comment]
@schiessle If you are looking for an easy one ;)

**Comment by jancborchardt** [comment]
Or rather – @schiessle if you are looking for an easy one you can use to get someone involved in development. ;)
