### ISSUE TITLE
File Versions not visible on web interface

### ISSUE THREAD

**Issue by johannes314** [nextcloud/server#6589]
### Expected behaviour
I am expecting to see file versions on the webinterface but I don't
I already discussed it briefly at the nextcloud forum:
https://help.nextcloud.com/t/file-versioning-enabled-but-not-working/21146/5

### Actual behaviour
The file versions are created and I can find them in the file explorer but in the web interface there is no version history. There is just empty space.

### Server configuration
I am running a nextcloud 11.0.3 
**Operating system**:
Synology Diskstation with DSM 6.1.3
**Web server:**
Apache Apache 2.4.25
**Database:**
MAria DB
**PHP version:**
7
**Nextcloud version:** (see Nextcloud admin page)
11.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh installation
**Where did you install Nextcloud from:**
nextcloud web page

**Comment by nickvergessen** [comment]
Anything in your browsers console (F12) or your nextcloud.log file?

**Comment by riegercloud** [comment]
Hi @MorrisJobke and @nickvergessen
unfortunately i ran into the same issue with Nextclud 15.0.2.

Versions are stored in users files_version directory properly
![grafik](https://user-images.githubusercontent.com/20593693/51437977-2a386a80-1ca6-11e9-8907-851c0af8cac1.png)

but neither appear in the browser nor appear e.g. in collabora (i.e. gewicht.xlsx).
![grafik](https://user-images.githubusercontent.com/20593693/51437982-4f2cdd80-1ca6-11e9-9743-e77ccd1355bd.png)

Nothing was written to the nextcloud.log.

Nextcloud 15.0.2
PHP 7.3
MariaDB 10.3
Redis

**Comment by riegercloud** [comment]
Sorry, just found https://github.com/nextcloud/server/issues/13319
