### ISSUE TITLE
File list sometimes refreshes after closing picture or video viewer 

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#659]
I can’t reliably reproduce that yet for some reason. cc @oparoz @Instagit It’s very strange and rips you out of the flow when it happens. You expect the filelist to be directly there already, but instead sometimes a blank screen with just a spinner loading the folder shows.

It doesn’t seem to happen for the PDF viewer or text editor cc @tomneedham @nextcloud/javascript

**Comment by MorrisJobke** [comment]
> I can’t reliably reproduce that yet for some reason.

It refreshes always, because this was needed for IEs to properly handle the JS events after closing.

**Comment by jancborchardt** [comment]
So it `was` needed and we can get rid of it now?

**Comment by MorrisJobke** [comment]
> So it was needed and we can get rid of it now?

I think so. 😄

**Comment by oparoz** [comment]
Also, it works with some apps because they don't care at all about the History. So if you're on a tablet and press back, then things get messed up.

**Comment by Bugsbane** [comment]
> I think so. :smile:

Thank goodness! Most of my photos are all in the InstantUpload folder - thousands and thousands of them. It drives me crazy that just about any time I look at one of them, I end up having to spend 5 minutes, scrolling back to where I was up to again, just to start all over again when I look at the next photo. Then again, I never use IE.

**Comment by jancborchardt** [comment]
@oparoz can you remove that code then to fix it? :)

**Comment by oparoz** [comment]
https://github.com/owncloud/core/pull/27282

**Comment by MorrisJobke** [comment]
Fix is in #3686
