### ISSUE TITLE
Dialog css stuff not correctly loaded on public page?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#6601]
Compare logged in:
> ![bildschirmfoto vom 2017-09-21 14-40-44](https://user-images.githubusercontent.com/213943/30696185-10626a4c-9edb-11e7-9e45-2b4319f53c97.png)

And guest:
> ![bildschirmfoto vom 2017-09-21 14-40-04](https://user-images.githubusercontent.com/213943/30696198-214737d4-9edb-11e7-8155-9cff74159272.png)

@nextcloud/designers

**Comment by jancborchardt** [comment]
This should not be solved using a dialog but rather the same style of password input page which we use for password-protected shares.

**Comment by nickvergessen** [comment]
No, the dialog prompt should look the same for both, guests and users.

**Comment by MorrisJobke** [comment]
> No, the dialog prompt should look the same for both, guests and users.
> But on public pages the grey background is missing...

Really? There should be no prompt, but it should be inlined where the camera icon is. The pop up is not really needed. In the logged in way, you can inline it and in the guest mode as well.

**Comment by nickvergessen** [comment]
Please, this is not how video calls handles the password input.
This is about "public page is missing the grey background when there is a popup".

Nothing else.

**Comment by jancborchardt** [comment]
It _is_ about design. ;) And in this case a popup is not the correct and nicely integrated way to do stuff. It should absolutely be inlined under the camera icon as @MorrisJobke said. For guests it can be the same.

That way we can already show the own camera picture in the bottom left too.

**Comment by nickvergessen** [comment]
This issue is about the `OC.dialogs()` code not rendering the same for users and guests.
So please fix THE DIALOGS IN GENERAL to also show the grey background for guests, so apps can use the mechanisms we provide without having to copy half the CSS stuff over...

If you can not understand this, I will create a fake-empty app which opens a dialog for guests which is then also missing the grey background. Shall I waste these 3-4 hours, or can you understand this and fix the missing background independent from whether video calls should use it or not?
*sarcasm off, I'm going to ignore this issue now*
PLEASE FIX THIS.

For the video calls password input there is another issue in the respective repo:
https://github.com/nextcloud/spreed/issues/422
