### ISSUE TITLE
Can't access nextcloud 12.0.3

### ISSUE THREAD

**Issue by Ricardosgeral** [nextcloud/server#6604]
Hi
I had my nextcloud instance running for the last 2 months.
Well, I've updated successfully to NC 12.0.3 yesterday. No errors were reported. 
Today I noticed that the upgrade changed the upload_max_filesize to 512M. I've tried to change to 2GB but it didn't allowed. So i putted 1.9G and it accepted and automatically changed to 2G! 
Since that the server become unstable and then stopped completely, that is, can't access it from anywhere (web, android, windows)

I don't know if the problem is the 1.9 GB or something else.
I'm not competent in apache/PHP to now where to start, really.

need help here. :( 

--> 
### Steps to reproduce
1.open browser and open server (IP or url) 
2. firefox results in "unable to connect"
3. windows client results in " connection refused"

### Expected behaviour
it should open nextcloud login page

### Actual behaviour
can't access server

### Server configuration

**Operating system**:  - raspbian scretch

**Web server:** raspberry pi 3B

**Database:** MySQL

**PHP version:**PHP7

**Nextcloud version:** (NC 12.0.3)

**Updated from an older Nextcloud/ownCloud or fresh install: update from NC 12.0.2

**Where did you install Nextcloud from: image provided by nextcloudpi from Nacho parker

**Nextcloud configuration:**

<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "1": "192.168.1.6",
            "3": "ricarcloud.ddns.net",
            "4": "ricarcloud.ddns.net"
        },
        "datadirectory": "\/media\/myCloudDrive\/ncdata",
        "overwrite.cli.url": "https:\/\/ricarcloud.ddns.net",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "ocup3agyjd4f",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "overwriteprotocol": "https",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "ricarcloud",
        "mail_domain": "gmail.com",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2
    }
}


**Are you using external storage, if yes which one:** NO

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** NO

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

Insert your webserver log here
{"reqId":"WcLq0X8AAQEAAAMPEHgAAE8Y","level":1,"time":"2017-09-20T22:26:02+00:00"                                                                                                        ,"remoteAddr":"193.136.108.166","user":"--","app":"updater","method":"GET","url"                                                                                                        :"\/core\/ajax\/update.php?requesttoken=%2Bp8yLq6JzaYkd4UBLmkRNzpcpREc5QtnZKZax%                                                                                                        2FPn9Y8%3D%3AgrRgfeK%2F%2F%2BJuOf0uf1x0dBE6imJbrDtRNsoZ97Kvots%3D","message":"\\                                                                                                        OC\\Repair::step: Repair step: Add move avatar background job","userAgent":"Mozi                                                                                                        lla\/5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko\/20100101 Firefox\/55.0","versio                                                                                                        n":"12.0.2.0"}
{"reqId":"WcLq0X8AAQEAAAMPEHgAAE8Y","level":1,"time":"2017-09-20T22:26:02+00:00"                                                                                                        ,"remoteAddr":"193.136.108.166","user":"--","app":"updater","method":"GET","url"                                                                                                        :"\/core\/ajax\/update.php?requesttoken=%2Bp8yLq6JzaYkd4UBLmkRNzpcpREc5QtnZKZax%                                                                                                        2FPn9Y8%3D%3AgrRgfeK%2F%2F%2BJuOf0uf1x0dBE6imJbrDtRNsoZ97Kvots%3D","message":"\\                                                                                                        OC\\Repair::info: Repair info: Add background job","userAgent":"Mozilla\/5.0 (Wi                                                                                                        ndows NT 6.1; WOW64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"12.0.2.0                                                                                                        "}
{"reqId":"WcLq0X8AAQEAAAMPEHgAAE8Y","level":1,"time":"2017-09-20T22:26:02+00:00"                                                                                                        ,"remoteAddr":"193.136.108.166","user":"--","app":"updater","method":"GET","url"                                                                                                        :"\/core\/ajax\/update.php?requesttoken=%2Bp8yLq6JzaYkd4UBLmkRNzpcpREc5QtnZKZax%                                                                                                        2FPn9Y8%3D%3AgrRgfeK%2F%2F%2BJuOf0uf1x0dBE6imJbrDtRNsoZ97Kvots%3D","message":"\\                                                                                                        OC\\Repair::step: Repair step: Add preview cleanup background jobs","userAgent":                                                                                                        "Mozilla\/5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko\/20100101 Firefox\/55.0","v                                                                                                        ersion":"12.0.2.0"}
{"reqId":"WcLq0X8AAQEAAAMPEHgAAE8Y","level":1,"time":"2017-09-20T22:26:02+00:00"                                                                                                        ,"remoteAddr":"193.136.108.166","user":"--","app":"updater","method":"GET","url"                                                                                                        :"\/core\/ajax\/update.php?requesttoken=%2Bp8yLq6JzaYkd4UBLmkRNzpcpREc5QtnZKZax%                                                                                                        2FPn9Y8%3D%3AgrRgfeK%2F%2F%2BJuOf0uf1x0dBE6imJbrDtRNsoZ97Kvots%3D","message":"\\                                                                                                        OC\\Repair::step: Repair step: Fix potential broken mount points","userAgent":"M                                                                                                        ozilla\/5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko\/20100101 Firefox\/55.0","ver                                                                                                        sion":"12.0.2.0"}
{"reqId":"WcLq0X8AAQEAAAMPEHgAAE8Y","level":1,"time":"2017-09-20T22:26:02+00:00"                                                                                                        ,"remoteAddr":"193.136.108.166","user":"--","app":"updater","method":"GET","url"                                                                                                        :"\/core\/ajax\/update.php?requesttoken=%2Bp8yLq6JzaYkd4UBLmkRNzpcpREc5QtnZKZax%                                                                                                        2FPn9Y8%3D%3AgrRgfeK%2F%2F%2BJuOf0uf1x0dBE6imJbrDtRNsoZ97Kvots%3D","message":"\\                                                                                                        OC\\Repair::info: Repair info: No mounts updated","userAgent":"Mozilla\/5.0 (Win                                                                                                        dows NT 6.1; WOW64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"12.0.2.0"                                                                                                        }
{"reqId":"WcLq0X8AAQEAAAMPEHgAAE8Y","level":1,"time":"2017-09-20T22:26:02+00:00"                                                                                                        ,"remoteAddr":"193.136.108.166","user":"--","app":"updater","method":"GET","url"                                                                                                        :"\/core\/ajax\/update.php?requesttoken=%2Bp8yLq6JzaYkd4UBLmkRNzpcpREc5QtnZKZax%                                                                                                        2FPn9Y8%3D%3AgrRgfeK%2F%2F%2BJuOf0uf1x0dBE6imJbrDtRNsoZ97Kvots%3D","message":"\\                                                                                                        OC\\Repair::step: Repair step: Repair language codes","userAgent":"Mozilla\/5.0                                                                                                         (Windows NT 6.1; WOW64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"12.0.                                                                                                        2.0"}
{"reqId":"WcLq0X8AAQEAAAMPEHgAAE8Y","level":1,"time":"2017-09-20T22:26:02+00:00"                                                                                                        ,"remoteAddr":"193.136.108.166","user":"--","app":"updater","method":"GET","url"                                                                                                        :"\/core\/ajax\/update.php?requesttoken=%2Bp8yLq6JzaYkd4UBLmkRNzpcpREc5QtnZKZax%                                                                                                        2FPn9Y8%3D%3AgrRgfeK%2F%2F%2BJuOf0uf1x0dBE6imJbrDtRNsoZ97Kvots%3D","message":"\\                                                                                                        OC\\Repair::step: Repair step: Install new core bundle components","userAgent":"                                                                                                        Mozilla\/5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko\/20100101 Firefox\/55.0","ve                                                                                                        rsion":"12.0.2.0"}
{"reqId":"WcLq0X8AAQEAAAMPEHgAAE8Y","level":1,"time":"2017-09-20T22:26:02+00:00"                                                                                                        ,"remoteAddr":"193.136.108.166","user":"--","app":"updater","method":"GET","url"                                                                                                        :"\/core\/ajax\/update.php?requesttoken=%2Bp8yLq6JzaYkd4UBLmkRNzpcpREc5QtnZKZax%                                                                                                        2FPn9Y8%3D%3AgrRgfeK%2F%2F%2BJuOf0uf1x0dBE6imJbrDtRNsoZ97Kvots%3D","message":"\\                                                                                                        OC\\Repair::step: Repair step: Repair invalid paths in file cache","userAgent":"                                                                                                        Mozilla\/5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko\/20100101 Firefox\/55.0","ve                                                                                                        rsion":"12.0.2.0"}
{"reqId":"WcLq0X8AAQEAAAMPEHgAAE8Y","level":1,"time":"2017-09-20T22:26:02+00:00"                                                                                                        ,"remoteAddr":"193.136.108.166","user":"--","app":"updater","method":"GET","url"                                                                                                        :"\/core\/ajax\/update.php?requesttoken=%2Bp8yLq6JzaYkd4UBLmkRNzpcpREc5QtnZKZax%                                                                                                        2FPn9Y8%3D%3AgrRgfeK%2F%2F%2BJuOf0uf1x0dBE6imJbrDtRNsoZ97Kvots%3D","message":"\\                                                                                                        OC\\Repair::step: Repair step: Rename folder with user specific keys","userAgent                                                                                                        ":"Mozilla\/5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko\/20100101 Firefox\/55.0",                                                                                                        "version":"12.0.2.0"}
{"reqId":"WcLq0X8AAQEAAAMPEHgAAE8Y","level":1,"time":"2017-09-20T22:26:02+00:00"                                                                                                        ,"remoteAddr":"193.136.108.166","user":"--","app":"updater","method":"GET","url"                                                                                                        :"\/core\/ajax\/update.php?requesttoken=%2Bp8yLq6JzaYkd4UBLmkRNzpcpREc5QtnZKZax%                                                                                                        2FPn9Y8%3D%3AgrRgfeK%2F%2F%2BJuOf0uf1x0dBE6imJbrDtRNsoZ97Kvots%3D","message":"\\                                                                                                        OC\\Updater::startCheckCodeIntegrity: Starting code integrity check...","userAge                                                                                                        nt":"Mozilla\/5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko\/20100101 Firefox\/55.0                                                                                                        ","version":"12.0.2.0"}
{"reqId":"WcLq0X8AAQEAAAMPEHgAAE8Y","level":1,"time":"2017-09-20T22:26:25+00:00"                                                                                                        ,"remoteAddr":"193.136.108.166","user":"--","app":"updater","method":"GET","url"                                                                                                        :"\/core\/ajax\/update.php?requesttoken=%2Bp8yLq6JzaYkd4UBLmkRNzpcpREc5QtnZKZax%                                                                                                        2FPn9Y8%3D%3AgrRgfeK%2F%2F%2BJuOf0uf1x0dBE6imJbrDtRNsoZ97Kvots%3D","message":"\\                                                                                                        OC\\Updater::finishedCheckCodeIntegrity: Finished code integrity check","userAge                                                                                                        nt":"Mozilla\/5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko\/20100101 Firefox\/55.0                                                                                                        ","version":"12.0.2.0"}
{"reqId":"WcLq0X8AAQEAAAMPEHgAAE8Y","level":1,"time":"2017-09-20T22:26:25+00:00"                                                                                                        ,"remoteAddr":"193.136.108.166","user":"--","app":"updater","method":"GET","url"                                                                                                        :"\/core\/ajax\/update.php?requesttoken=%2Bp8yLq6JzaYkd4UBLmkRNzpcpREc5QtnZKZax%                                                                                                        2FPn9Y8%3D%3AgrRgfeK%2F%2F%2BJuOf0uf1x0dBE6imJbrDtRNsoZ97Kvots%3D","message":"\\                                                                                                        OC\\Updater::updateEnd: Update successful","userAgent":"Mozilla\/5.0 (Windows NT                                                                                                         6.1; WOW64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"12.0.3.3"}
{"reqId":"WcLq0X8AAQEAAAMPEHgAAE8Y","level":1,"time":"2017-09-20T22:26:25+00:00"                                                                                                        ,"remoteAddr":"193.136.108.166","user":"--","app":"updater","method":"GET","url"                                                                                                        :"\/core\/ajax\/update.php?requesttoken=%2Bp8yLq6JzaYkd4UBLmkRNzpcpREc5QtnZKZax%                                                                                                        2FPn9Y8%3D%3AgrRgfeK%2F%2F%2BJuOf0uf1x0dBE6imJbrDtRNsoZ97Kvots%3D","message":"\\                                                                                                        OC\\Updater::maintenanceDisabled: Turned off maintenance mode","userAgent":"Mozi                                                                                                        lla\/5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko\/20100101 Firefox\/55.0","versio                                                                                                        n":"12.0.3.3"}
{"reqId":"WcLq0X8AAQEAAAMPEHgAAE8Y","level":1,"time":"2017-09-20T22:26:25+00:00"                                                                                                        ,"remoteAddr":"193.136.108.166","user":"--","app":"updater","method":"GET","url"                                                                                                        :"\/core\/ajax\/update.php?requesttoken=%2Bp8yLq6JzaYkd4UBLmkRNzpcpREc5QtnZKZax%                                                                                                        2FPn9Y8%3D%3AgrRgfeK%2F%2F%2BJuOf0uf1x0dBE6imJbrDtRNsoZ97Kvots%3D","message":"\\                                                                                                        OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"Mozilla\                                                                                                        /5.0 (Windows NT 6.1; WOW64; rv:55.0) Gecko\/20100101 Firefox\/55.0","version":"                                                                                                        12.0.3.3"}
{"reqId":"WcOF738AAQEAACtb4T8AAAAN","level":2,"time":"2017-09-21T09:27:11+00:00"                                                                                                        ,"remoteAddr":"104.236.154.59","user":"--","app":"core","method":"GET","url":"\/                                                                                                        ","message":"Trusted domain error. \"104.236.154.59\" tried to access using \"79                                                                                                        .168.122.226\" as host.","userAgent":"Mozilla\/5.0 zgrab\/0.x","version":"12.0.3                                                                                                        .3"}

**List of activated apps:**
<details>
<summary>App list</summary>
contacts
trackphone
draw.io
orcid
and all the default ones

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

Enabled:
  - activity: 2.5.2
  - admin_notifications: 1.0.0
  - apporder: 0.4.0
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - drawio: 0.8.8
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_downloadactivity: 1.1.1
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - metadata: 0.5.0
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - orcid: 0.9.1
  - password_policy: 1.2.2
  - phonetrack: 0.0.3
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap
```

**Comment by j-ed** [comment]
If a problem appears after you've increased a parameter value you should reset it to the default value again.
Due to the fact that a Raspberry Pi has only limited physical memory available it isn't a good idea to play around with such high values.

**Comment by Ricardosgeral** [comment]
Well I changed the value in the Admin page. And didn't put a value higher than the max recommended.
Anyway I'm not convinced that that is the problem.
Really I don't know were to start to solve the server problem.

Some hints from you guys experts are appreciated.

Really want to save server

SAVE THE SERVER ;>)

**Comment by Ricardosgeral** [comment]
it seems that i've solved it by reiinstalling apache2

REINSTALL APACHE2:

To replace configuration files that have been deleted, without purging the package, you can do:

sudo apt-get -o DPkg::Options::="--force-confmiss" --reinstall install apache2

Now it works
