### ISSUE TITLE
After NC 12.0.3 upgrade news are no longer updated via cronjob

### ISSUE THREAD

**Issue by doitux** [nextcloud/server#6610]
### Steps to reproduce
1. Update to 12.0.3
2. Re-Enable the news app
3. Mark all unread messages as readed and wait for the cronjob to fetch fresh news 

### Expected behaviour
New news items should be fetched via cronjob as it works without problems in NC 12.0.2 

### Actual behaviour
Nothing happened. The news sources are no longer updated :-/

### General server configuration

**Operating system:** Linux vwp2527 4.4.74-1-xenu-static-he+1+ #2 SMP Mon Jun 26 12:35:59 CEST 2017 x86_64

**Web server:** Apache (apache2handler)

**Database:** sqlite3 3.8.7

**PHP version:** 5.6.31-he.0
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - ereg
 - libxml
 - openssl
 - pcre
 - dba
 - dom
 - fileinfo
 - filter
 - hash
 - json
 - bz2
 - posix
 - Reflection
 - SPL
 - SimpleXML
 - session
 - standard
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - xml
 - xmlreader
 - xmlwriter
 - apache2handler
 - apcu
 - imagick
 - bcmath
 - zlib
 - calendar
 - ctype
 - curl
 - mbstring
 - ftp
 - gd
 - geoip
 - gettext
 - iconv
 - imap
 - intl
 - ldap
 - exif
 - mcrypt
 - mysqlnd
 - mysqli
 - mysql
 - PDO
 - pdo_mysql
 - pdo_sqlite
 - PDFlib
 - tet
 - pspell
 - shmop
 - soap
 - sockets
 - sqlite3
 - suhosin
 - tidy
 - timezonedb
 - wddx
 - xmlrpc
 - xsl
 - zip
 - Phar
 - mhash
 - apc
 - ionCube Loader
 - Zend Guard Loader
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 12.0.2

**Where did you install Nextcloud from:**  Via Updater

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - audioplayer: 2.1.0
 - calendar: 1.5.5
 - comments: 1.2.0
 - contacts: 1.5.3
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_external: 1.3.0
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - news: 11.0.5
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_audit
 - bruteforcesettings
 - encryption
 - spreed
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "dbtype": "sqlite3",
    "version": "12.0.3.3",
    "logtimezone": "UTC",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "mail_from_address": "felix",
    "mail_smtpmode": "php",
    "updater.release.channel": "stable",
    "memcache.local": "\\OC\\Memcache\\APCu",
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/60.0.3112.113 Chrome/60.0.3112.113 Safari/537.36

**Operating system:** Linux

**Comment by doitux** [comment]
Today when i waked up i checked the cronjob update works fine again. Maybe a calendar/time(00:00) switch bug?

**Comment by nickvergessen** [comment]
Closing as per above.

If it again does not work, please report it to the news app developers 😉
