### ISSUE TITLE
Transparent profile pictures show up purple.

### ISSUE THREAD

**Issue by ZiiX** [nextcloud/server#6618]
When uploading a transparent profile pic, the transparent portion shows up purple.

**Comment by MorrisJobke** [comment]
cc @rullzer

**Comment by rullzer** [comment]
Mmmm we just use the default image processing.
@ZiiX can you share the picture you try it with?

**Comment by ZiiX** [comment]
Sure! this is when viewing from admin account of nextcloud.tld/settings/users
![profile pic](https://user-images.githubusercontent.com/2234740/30827660-b9ced8ec-a1ef-11e7-89ad-9609eee9f890.png)

![how it looks on admin screen](https://user-images.githubusercontent.com/2234740/30827684-d0843a1e-a1ef-11e7-97b0-c7c062f94637.png)

However, transparencies work fine on user personal profile page.
thanks for all the great work, y'all.

**Comment by rullzer** [comment]
Aaaah I see the issue, we first set the avatar (to show something) and then fetch the image. However since it is transparent it still show it...

**Comment by rullzer** [comment]
Fix is in #6658
