### ISSUE TITLE
Adjusted trash retention, filesize(): stat failed

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/server#6619]
![image](https://user-images.githubusercontent.com/3178412/30763962-c6ac81a6-9fe0-11e7-8ca4-1dd6dfdc77db.png)

With an exceptionally large volume I noticed files were sitting in the trashbin indefinitely. 
Because of this, I added: `'trashbin_retention_obligation' => 'auto, 30',`

Since then, my logs are filling with the above error.

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.1

**Nextcloud version:** (see Nextcloud admin page) 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Update

**Where did you install Nextcloud from:** Zip

**Are you using external storage, if yes which one:** sftp

**Are you using encryption:** no

**Comment by blizzz** [comment]
@schiessle

**Comment by bcutter** [comment]
Same for me. Too bad nothing happened since more than one year... how can I contribute?

**Comment by blizzz** [comment]
@icewind1991 perhaps?

**Comment by kesselb** [comment]
Still seeing this issue?
