### ISSUE TITLE
Profile picture survives deletion and recreation of account

### ISSUE THREAD

**Issue by minils** [nextcloud/server#6621]
### Steps to reproduce
1. Create account X and set a profile picture
2. Delete the account X
3. Create a new account X with the same username

### Expected behaviour
The profile picture is reset.

### Actual behaviour
The profile picture of the old account is visible

### Server configuration

**Operating system**: Fedora 26

**Web server:** Apache/2.4.27

**Database:** MariaDB/10.1.26-2.fc26

**PHP version:** 7.1.9-2.fc26

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 12.0.2

**Where did you install Nextcloud from:** nextcloud.com zip file

**Signing status:**

**List of activated apps:**
Enabled:                                                                                                                                                         
  - activity: 2.5.2                      
  - apporder: 0.4.0                      
  - bruteforcesettings: 1.0.2            
  - calendar: 1.5.5                      
  - comments: 1.2.0                      
  - contacts: 1.5.3                      
  - dav: 1.3.0                           
  - federatedfilesharing: 1.2.0          
  - federation: 1.2.0
  - files: 1.7.2
  - files_downloadactivity: 1.1.1
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - metadata: 0.5.0
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - previewgenerator: 1.0.6
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0

**Comment by rullzer** [comment]
Mmmm we should probabaly listen to some hook ;) Let me take care of this.

**Comment by rullzer** [comment]
PR in #6668
