### ISSUE TITLE
Settings menu layout is broken

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#6622]
on current master:
![bildschirmfoto vom 2017-09-23 11-06-12](https://user-images.githubusercontent.com/3404133/30771790-a719f174-a04f-11e7-9062-13ef63e69c10.png)

Seems to be related to #6399

@nextcloud/designers @skjnldsv

**Comment by skjnldsv** [comment]
Strange, I never notice this while testing! :O 
Thanks, will fix asap!
