### ISSUE TITLE
General question: Quota and mail

### ISSUE THREAD

**Issue by Extarys** [nextcloud/server#6629]
I would like to link a user to that same user's email address in Nextcloud Mail (without the need of logging in. It would be nice if there was some kind of quota progress bar when you click on the top right corner. 

The quota of the mail and the nextcloud should be togheter no?

I'm using iRedMail with NextCloud. I'm not sure how someone is supposed to make a mail server and everything else work together

**Comment by blizzz** [comment]
I guess this makes more sense in the mail repo… but i am not sure whether this makes sense in general. Or rather it's figuring out the quota from the mail servers…? Not sure this makes sense at all. @ChristophWurst

**Comment by ChristophWurst** [comment]
> I would like to link a user to that same user's email address in Nextcloud Mail (without the need of logging in.

Please see https://github.com/nextcloud/mail/pull/28. We do support this, but it's not yet documented – feel free to contribute documentation 😉 



> It would be nice if there was some kind of quota progress bar when you click on the top right corner.

We don't show quota at the moment, but it would be a nice enhancement to query this information. Please file a new ticket at https://github.com/nextcloud/mail/issues/new.

Thanks!

**Comment by Extarys** [comment]
@blizzz So questions doesn't make sense? What an "open" community.

@ChristophWurst The first link, wow! Thank you so much! I didn't find that one! :O
Also, Of course I'll add the suggestion, I jsut wasn't sure, I'm always quite shy to open an issue for a question or an enhancement because well, they aren't issues per-se.

Thanks for your time gentlements.

**Comment by blizzz** [comment]
> @blizzz So questions doesn't make sense? What an "open" community.

Never wrote anything like that. I was unsure about the idea, expressed it, and pulled in @ChristophWurst for a profound answer. 

Anyway, sorry for "sounding" harsh or unwelcoming, that wasn't my intention.

**Comment by Extarys** [comment]
> Not sure this makes sense at all.

Hmm... *Scratching head*, yea sorry I might have took it personally.
