### ISSUE TITLE
Perform an LDAP health check for Security and Setup warnings

### ISSUE THREAD

**Issue by askbow** [nextcloud/server#6635]
_This is more like a feature request._
### Expected behaviour
A warning should be displayed in "Admin->Basic Settings->Security & setup warnings"
in cases when LDAP server (if LDAP auth is configured) takes more than [1, 2, 5, 10] seconds to respond or is unresponsive.

### Actual behaviour
At the moment, it shows "All checks passed" despite our LDAP server being shaky and users experiencing problems logging-in to nextcloud (_they are blaming nextcloud, of course_).

### Server configuration

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install 12.0.2, 

**List of activated apps:**
<details>
<summary>LDAP user and group backend 1.2.1</summary>
</details>

### Motivation
To the users, a lagging LDAP server looks like issue #3645, with some other functions being slow as well (some pages took ages to display).
The users tend to blame nextcloud, although nextcloud seems to be feeling healthy.
An additional built-in check and a log message might help to direct the admin's debug efforts.

Personal note: _This morning we checked all the logs (no errors), restarted the server (no effect), changed load-balancers (no effect) etc, until the LDAP admin came to work and told us that there were problems with one of their servers this weekend._

**Comment by ChristophWurst** [comment]
Although this sounds like a nice feature, the number of requests for this are quite low. Currently there a no plans to implement such a feature, hence I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

Thank you :v:
