### ISSUE TITLE
Automaitc Upgrade process - Disable backup

### ISSUE THREAD

**Issue by Nono-m0le** [nextcloud/server#6636]
Would that be possible to be able to choose whenever we want to do a backup during a automatic upgrade ?
On my case, I'm taking care of the backup on the server side (cli) and I can't use the automatic upgrade process because the "Create backup" task systamtically failed for various reasons.

**Comment by MorrisJobke** [comment]
> On my case, I'm taking care of the backup on the server side (cli) and I can't use the automatic upgrade process because the "Create backup" task systamtically failed for various reasons.

What reasons? And please open this in the updater repo: https://github.com/nextcloud/updater

**Comment by Nono-m0le** [comment]
https://github.com/nextcloud/updater/issues/145
