### ISSUE TITLE
Auth Token Usage - IP Address/Location

### ISSUE THREAD

**Issue by fti7** [nextcloud/server#6639]
Hi,

on the Personal/Security View (Devices & Last Activitiy), it would really be useful to see which IP Address(es) used the Token recently.

With an GEOIP Database (Country-Level DBs arent that big) it would also allow to show the Country/Location of the Access to the End User.
Other Vendors like Dropbox are doing the same.

Advanced Security Features would like e.g. Mail Notifications if there are multiple IPs used from different Countries or a Login from an "unusual" Country etc.

BR,
Frank

**Comment by GLLM** [comment]
I second this feature request, mainly for the IP to be shown next to the session name when relevant (browser session).

Thanks.

**Comment by quentingosset** [comment]
actually this feature could be useful to facilitate the monitoring of a user security panel.

**Comment by ChristophWurst** [comment]
Although this sounds like a nice feature, the number of requests for this are quite low. Currently there a no plans to implement such a feature, hence I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

Thank you :v:
