### ISSUE TITLE
Recent photos messes up navigation

### ISSUE THREAD

**Issue by sub0ne** [nextcloud/server#6641]
just upgraded to 12.0.3 and the “Recent” folder seems to mess up the navigation.
 
### Steps to reproduce
1. go to folder “Photos”
2. go to folder “Recent”
3. go to folder “All files”

### Expected behaviour
The root folder should be displayed after click "All files"

### Actual behaviour
The "Photo" folder content is displayed, the navigation bar supposes I am in the root.

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** latest Apache

**Database:** latest MySQL

**PHP version:** latest PHP

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** yes, updated from 12.0.0

**Where did you install Nextcloud from:** command line

**Comment by MorrisJobke** [comment]
cc @icewind1991 @nextcloud/javascript

**Comment by sub0ne** [comment]
if you need any further information, let me know.

**Comment by sub0ne** [comment]
did some further research:

URL after opening: https://cloud.mbelz.de/index.php/apps/files/?dir=/&fileid=15
URL after clicking Photos: https://cloud.mbelz.de/index.php/apps/files/?dir=/Photos&fileid=27
URL after clicking Recent: https://cloud.mbelz.de/index.php/apps/files/?dir=/&view=recent
URL after clicking All files: https://cloud.mbelz.de/index.php/apps/files/?dir=/&fileid=15 but switches to 
                              https://cloud.mbelz.de/index.php/apps/files/?dir=/&fileid=27 instantly

You can see the URL with fileid 15 being loaded but in an instant it redirects (?) to fileid 27, what seems to be the Photos folder.

Changing the fileid to 15 loads the root folder. So something seems to be messed.

**Comment by sub0ne** [comment]
edit#2:
tried it with folders other than Photos and this issue seems to only affect the Photos folder. If you browse to any other folder you can switch back to the root folder.

BUT you still can see the previous folder being loaded for a part of a second and then being redirected to the root folder (id 15 in my case). 

Clicking All files:
ok: whatever folder to Recent to All files: show whatever folder (for a part of a second) and changes to root
wrong: Photos folder to Recent to All files: shows root (for a part of a second) and switches to Photos

**Comment by icewind1991** [comment]
When I follow the steps I can briefly see the Photos folder being loaded before it navigates to the root, it might be a race condition if your Photos folder takes a bit longer to load then other folders or something

**Comment by icewind1991** [comment]
Possible fix: https://github.com/nextcloud/server/pull/6683

**Comment by sub0ne** [comment]
#6683 does not fix this issue.
