### ISSUE TITLE
Do not allow to specify a colon within the dbhost

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#6642]
* the dbhost should not be allowed to hold a colon (except it is an IPv6 address and then at least needs to hold 7 `:` or at least `::`)
* also check this in the CLI tool (--database-host)

cc @icewind1991 @nickvergessen @rullzer

**Comment by kyrofa** [comment]
Why is this an issue? Unix sockets also contain colons, it's even [documented](https://docs.nextcloud.com/server/12/admin_manual/configuration_server/config_sample_php_parameters.html), which the PR fixing this issue broke.

**Comment by MorrisJobke** [comment]
> Why is this an issue? Unix sockets also contain colons, it's even documented, which the PR fixing this issue broke.

Valid point :/ We just had issues with a port that was added twice :/

**Comment by MorrisJobke** [comment]
Reverted for stable12 in #7102 and master in #7107
