### ISSUE TITLE
Do not invent new HTTP request methods (why "REPORT" instead of "POST"?)

### ISSUE THREAD

**Issue by jm009** [nextcloud/server#6644]
I am working on making Nextcloud running in the Tomcat webserver.
Tomcat uses org.apache.catalina.servlets.CGIServlet for running scripts.
The CGIServlet by default only handles GET, POST and HEAD requests.

For me it seems reasonable to add the WebDAV HTTP request methods (COPY, LOCK, MKCOL, MOVE, PROPFIND, PROPPATCH, UNLOCK) to CGIServlet.

I already created a patch to handle "PROPFIND".

And now I get aware, that Nextcloud needs "REPORT".
Why is that? Is "REPORT" used anywhere else outside the Nextcloud world?
Couldn't "PROPFIND https://.../nextcloud/remote.php/dav/addressbooks/users/admin/contacts/" just be replaced by a "POST" (not tomorrow ;-) but in version 14.0.0 ;-) )?

**Comment by LukasReschke** [comment]
There are a ton of other verbs as well, see http://ietf.org/rfc/rfc3253 for example…

I'd recommend just switching to NGINX or Apache instead…

**Comment by jm009** [comment]
Thank you for the link to rfc3253.
I was not aware, that there are so many verbs used elsewhere.
I am going to provide a patch to CGIServlet, that will make it configurable, what verbs to handle.
In my report there is a typo, I meant "REPORT (XHR) https://.../nextcloud/remote.php/dav/addressbooks/users/admin/contacts/".
