### ISSUE TITLE
SQL and php error in PDOStatement.php#91

### ISSUE THREAD

**Issue by BamiGorengo** [nextcloud/server#6648]
Hi, i switched from owncloud to nextcloud last month. Now i checked the errorlogs and found 2 errors:

> An exception occurred while executing 'SELECT `uid`, `displayname` FROM `EGUq6_users` WHERE LOWER(`uid`) = LOWER(?)' with params ["Butzback"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

> Error while sending QUERY packet. PID=31955 at /www/htdocs/w01750fc/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#91

The first message is i think because i use a uppercased B in my username... But why i can enter uppercase letters, when its not supported by nextcloud?

And the second error i dont understand. is this a bug?

Best Regards.

**Comment by MorrisJobke** [comment]
> MySQL server has gone away

That means, that the MySQL server does not respond anymore (maybe crashed). This is out of scope for us, because we can't do more than logging an error.

The second entry is basically a followup problem.
