### ISSUE TITLE
The quota button in the user settings table is not aligned vertically

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#6654]
To see the problem login as the admin and open the _Users_ settings.

Example:
![usertable-quota](https://user-images.githubusercontent.com/26858233/30875600-5d607a6a-a2f4-11e7-9e1d-a19bec94307d.png)

@nextcloud/designers

**Comment by danxuliu** [comment]
For your information, I noticed that this does not happen in the _stable12_ branch, so I have made a bisection and found that the issue was introduced in the commit 2e8e6f95b99151edc0b236e474b32f1760af006a; I leave the fixing for the CSS experts ;)

**Comment by rullzer** [comment]
@skjnldsv maybe ;)?

**Comment by skjnldsv** [comment]
@rullzer, sneaky sneaky! 😂

**Comment by skjnldsv** [comment]
The progressbar display on the quota button is broken. I can propose something like that instead
![capture d ecran_2017-09-27_14-45-54](https://user-images.githubusercontent.com/14975046/30914061-95993c0c-a392-11e7-8bf9-671f9a455a70.png)

I did it quickly, needs some adjustments, but overall, what do you think, :)

**Comment by MorrisJobke** [comment]
> I did it quickly, needs some adjustments, but overall, what do you think, :)

Looks good, but the bottom border should be visible and not covered.

**Comment by skjnldsv** [comment]
It will need https://github.com/nextcloud/server/pull/6669/commits/278241a19b7d21b272a4dc11a023534b33e29f06 for the design part though :)

**Comment by skjnldsv** [comment]
I'm onto something! Not quite pleased with the result yet! :)
![capture d ecran_2017-09-27_15-03-45](https://user-images.githubusercontent.com/14975046/30914794-19cd66c2-a395-11e7-977e-160d38a11bbf.png)

**Comment by jancborchardt** [comment]
Oh we have a progress bar there? Nice :D looks good @skjnldsv

**Comment by skjnldsv** [comment]
That's more like it!! 🚀 
@nextcloud/designers, what do you think? @jancborchardt @MorrisJobke ?
![capture d ecran_2017-09-27_15-18-15](https://user-images.githubusercontent.com/14975046/30915430-204cd972-a397-11e7-9f22-515a2313b646.png)

**Comment by MorrisJobke** [comment]
> That's more like it!! 🚀
> @nextcloud/designers, what do you think? @jancborchardt @MorrisJobke ?

Awesome :)

**Comment by skjnldsv** [comment]
Fix is  in #6669

**Comment by rullzer** [comment]
@skjnldsv remind me to buy you a beer when we meet in person :beers: !

**Comment by skjnldsv** [comment]
@rullzer no problem!! :p
But why??
