### ISSUE TITLE
NC 13 Alpha - Using custom theme not working properly

### ISSUE THREAD

**Issue by io-node** [nextcloud/server#6656]
### Steps to reproduce
1. Install NC 13 Alpha
2. Create custom theme folder with custom images (logo, favicon, etc)
3. Login to NC

### Expected behaviour
File view with menus as normal

### Actual behaviour
Internal server error. After removing /themes/[theme name]/core/img/logo.png it does work

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4.18

**Database:** MySQL 5.5.53

**PHP version:** 7.0.22

**Nextcloud version:** 13.0.0 alpha

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Command line on own server

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - admin_audit: 1.3.0
  - bookmarks: 0.10.1
  - comments: 1.3.0
  - dav: 1.4.3
  - deck: 0.2.3
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_sharing: 1.5.0
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - lookup_server_connector: 1.1.0
  - oauth2: 1.1.0
  - provisioning_api: 1.3.0
  - sharebymail: 1.3.0
  - systemtags: 1.3.0
  - theming: 1.4.0
  - twofactor_backupcodes: 1.2.2
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - testing
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "oc0j67ffum5w",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "testcloud.domain.tld"
        ],
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "datadirectory": "\/var\/www\/nextcloud-test\/data",
        "overwrite.cli.url": "https:\/\/testcloud.domain.tld",
        "dbtype": "mysql",
        "version": "13.0.0.4",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "192.168.7.244",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud-test.log",
        "loglevel": "2",
        "log_rotate_size": "104857600",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "overwritehost": "testcloud.domain.tld",
        "overwritewebroot": "\/",
        "overwritecondaddr": "^192\\.168\\.7\\.[1-254]$",
        "filesystem_check_changes": 1,
        "enable_previews": true,
        "preview_max_x": 800,
        "preview_max_y": 800,
        "preview_max_scale_factor": 4,
        "skeletondirectory": "\/media\/nextcloud\/skeleton",
        "session_keepalive": true,
        "activity_expire_days": 365,
        "theme": "wijman",
        "mail_smtpsecure": "tls",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF"
        ],
        "asset-pipeline.enabled": true,
        "share_folder": "\/Shares"
    }
}
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** N/A

### Client configuration
**Browser:** Google Chrome 61.0.3163.100 

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

192.168.7.241 - - [26/Sep/2017:20:50:51 +0100] "GET /index.php/apps/files/?dir=/ HTTP/1.1" 500 1209 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36"</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

{"reqId":"jhtUfyNPFls0cIsmuf1k","level":3,"time":"2017-09-26T19:50:51+00:00","remoteAddr":"192.168.7.241","user":"admin","app":"index","method":"GET","url":"\/index.php\/apps\/files\/?dir=\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotPermittedException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Files\\\/SimpleFS\\\/SimpleFile.php(104): OC\\\\Files\\\\Node\\\\File->delete()\\n#1 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(254): OC\\\\Files\\\\SimpleFS\\\\SimpleFile->delete()\\n#2 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(164): OC\\\\Template\\\\SCSSCacher->resetCache()\\n#3 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(109): OC\\\\Template\\\\SCSSCacher->variablesChanged()\\n#4 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Template\\\/CSSResourceLocator.php(99): OC\\\\Template\\\\SCSSCacher->process('\\\/var\\\/www\\\/nextcl...', 'core\\\/css\\\/jquery...', 'core')\\n#5 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Template\\\/CSSResourceLocator.php(56): OC\\\\Template\\\\CSSResourceLocator->cacheAndAppendScssIfExist('\\\/var\\\/www\\\/nextcl...', 'core\\\/css\\\/jquery...')\\n#6 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Template\\\/ResourceLocator.php(75): OC\\\\Template\\\\CSSResourceLocator->doFind('css\\\/jquery-ui-f...')\\n#7 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/TemplateLayout.php(225): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#8 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/TemplateLayout.php(170): OC\\\\TemplateLayout::findStylesheetFiles(Array)\\n#9 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/legacy\\\/template.php(206): OC\\\\TemplateLayout->__construct('user', 'files')\\n#10 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(157): OC_Template->fetchPage()\\n#11 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(113): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#12 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#13 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/base.php(1000): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#17 \\\/var\\\/www\\\/nextcloud-test\\\/index.php(40): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Files\\\/Node\\\/File.php\",\"Line\":122}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3163.100 Safari\/537.36","version":"13.0.0.4"}
{"reqId":"jhtUfyNPFls0cIsmuf1k","level":3,"time":"2017-09-26T19:50:52+00:00","remoteAddr":"192.168.7.241","user":"admin","app":"core","method":"GET","url":"\/index.php\/apps\/files\/?dir=\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotPermittedException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Files\\\/SimpleFS\\\/SimpleFile.php(104): OC\\\\Files\\\\Node\\\\File->delete()\\n#1 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(254): OC\\\\Files\\\\SimpleFS\\\\SimpleFile->delete()\\n#2 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(164): OC\\\\Template\\\\SCSSCacher->resetCache()\\n#3 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(109): OC\\\\Template\\\\SCSSCacher->variablesChanged()\\n#4 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Template\\\/CSSResourceLocator.php(99): OC\\\\Template\\\\SCSSCacher->process('\\\/var\\\/www\\\/nextcl...', 'core\\\/css\\\/jquery...', 'core')\\n#5 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Template\\\/CSSResourceLocator.php(56): OC\\\\Template\\\\CSSResourceLocator->cacheAndAppendScssIfExist('\\\/var\\\/www\\\/nextcl...', 'core\\\/css\\\/jquery...')\\n#6 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Template\\\/ResourceLocator.php(75): OC\\\\Template\\\\CSSResourceLocator->doFind('css\\\/jquery-ui-f...')\\n#7 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/TemplateLayout.php(225): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#8 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/TemplateLayout.php(170): OC\\\\TemplateLayout::findStylesheetFiles(Array)\\n#9 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/legacy\\\/template.php(206): OC\\\\TemplateLayout->__construct('user', 'files')\\n#10 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(157): OC_Template->fetchPage()\\n#11 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(113): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#12 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#13 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#14 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#15 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#16 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/base.php(1000): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#17 \\\/var\\\/www\\\/nextcloud-test\\\/index.php(40): OC::handleRequest()\\n#18 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Files\\\/Node\\\/File.php\",\"Line\":122}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3163.100 Safari\/537.36","version":"13.0.0.4"}
{"reqId":"jhtUfyNPFls0cIsmuf1k","level":3,"time":"2017-09-26T19:50:52+00:00","remoteAddr":"192.168.7.241","user":"admin","app":"core","method":"GET","url":"\/index.php\/apps\/files\/?dir=\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotPermittedException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Files\\\/SimpleFS\\\/SimpleFile.php(104): OC\\\\Files\\\\Node\\\\File->delete()\\n#1 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(254): OC\\\\Files\\\\SimpleFS\\\\SimpleFile->delete()\\n#2 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(164): OC\\\\Template\\\\SCSSCacher->resetCache()\\n#3 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(109): OC\\\\Template\\\\SCSSCacher->variablesChanged()\\n#4 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Template\\\/CSSResourceLocator.php(99): OC\\\\Template\\\\SCSSCacher->process('\\\/var\\\/www\\\/nextcl...', 'core\\\/css\\\/jquery...', 'core')\\n#5 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Template\\\/CSSResourceLocator.php(56): OC\\\\Template\\\\CSSResourceLocator->cacheAndAppendScssIfExist('\\\/var\\\/www\\\/nextcl...', 'core\\\/css\\\/jquery...')\\n#6 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Template\\\/ResourceLocator.php(75): OC\\\\Template\\\\CSSResourceLocator->doFind('css\\\/jquery-ui-f...')\\n#7 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/TemplateLayout.php(225): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#8 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/TemplateLayout.php(170): OC\\\\TemplateLayout::findStylesheetFiles(Array)\\n#9 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/legacy\\\/template.php(206): OC\\\\TemplateLayout->__construct('error', '')\\n#10 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Template\\\/Base.php(132): OC_Template->fetchPage()\\n#11 \\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/legacy\\\/template.php(350): OC\\\\Template\\\\Base->printPage()\\n#12 \\\/var\\\/www\\\/nextcloud-test\\\/index.php(68): OC_Template::printExceptionErrorPage(Object(OCP\\\\Files\\\\NotPermittedException))\\n#13 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud-test\\\/lib\\\/private\\\/Files\\\/Node\\\/File.php\",\"Line\":122}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3163.100 Safari\/537.36","version":"13.0.0.4"}
</details>

**Comment by MorrisJobke** [comment]
cc @nextcloud/theming

**Comment by juliushaertl** [comment]
I cannot reproduce this with the current master and the example theme. From the error messages it looks like there is an permission issue with your data/appdata_INSTANCEID/ directory so it can't delete the old cached scss files.

**Comment by io-node** [comment]
Yes sorry, for some reason when I tried to resolve it by changing the theme files it seems to now work with all the theme files in place.
