### ISSUE TITLE
Some events and contacts could not been synchronized - "Received CalDAV GET response without ETag"

### ISSUE THREAD

**Issue by hubertkn** [nextcloud/server#6657]
### Steps to reproduce
1. Create new event or contact in browser or phone
2. Start to synchronize between server and phone by the davdroid
3. Synchronization error " Received CalDAV GET response without ETag"

### Expected behaviour
To synchronize events and contact between server and phone

### Actual behaviour
Synchronization error, sometime some events and contacts are not passing

Davdroid info:
```
--- BEGIN DEBUG INFO ---
SYNCHRONIZATION INFO
Synchronization phase: 9
Account name: Kontakty (USER@SERVER wg)
Authority: com.android.contacts

REMOTE RESOURCE:
https://SERVER.eu/remote.php/dav/addressbooks/users/USER/contacts/9f933619-5b2e-4cb4-837d-57ec58a625be.vcf

EXCEPTION:
at.bitfire.dav4android.exception.DavException: Received CardDAV GET response without ETag for https://SERVER.eu/remote.php/dav/addressbooks/users/USER/contacts/9f933619-5b2e-4cb4-837d-57ec58a625be.vcf
	at at.bitfire.davdroid.syncadapter.ContactsSyncManager.downloadRemote(ContactsSyncManager.kt:330)
	at at.bitfire.davdroid.syncadapter.SyncManager.performSync(SyncManager.kt:155)
	at at.bitfire.davdroid.syncadapter.ContactsSyncAdapterService$ContactsSyncAdapter.sync(ContactsSyncAdapterService.kt:43)
	at at.bitfire.davdroid.syncadapter.SyncAdapterService$SyncAdapter.onPerformSync(SyncAdapterService.kt:62)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
```

9f933619-5b2e-4cb4-837d-57ec58a625be.vcf:
```
BEGIN:VCARD
VERSION:3.0
PRODID:-//Sabre//Sabre VObject 4.1.2//EN
UID:9f933619-5b2e-4cb4-837d-57ec58a625be
FN:Auto Nazwisko
N:Nazwisko;Auto;;;
TEL;TYPE=cell:xxx yyy 852
REV:20170926T065926Z
END:VCARD
```

Davdroid info:
```
SYNCHRONIZATION INFO
Synchronization phase: 9
Account name: USER@SERVER
Authority: com.android.calendar

REMOTE RESOURCE:
https://SERVER/remote.php/dav/calendars/USER/personal/Nextcloud-HEHX6GUXO973FKOUO4EQC.ics

EXCEPTION:
at.bitfire.dav4android.exception.DavException: Received CalDAV GET response without ETag for https://SERVER/remote.php/dav/calendars/USER/personal/Nextcloud-HEHX6GUXO973FKOUO4EQC.ics
	at at.bitfire.davdroid.syncadapter.CalendarSyncManager.downloadRemote(CalendarSyncManager.kt:140)
	at at.bitfire.davdroid.syncadapter.SyncManager.performSync(SyncManager.kt:155)
	at at.bitfire.davdroid.syncadapter.CalendarsSyncAdapterService$SyncAdapter.sync(CalendarsSyncAdapterService.kt:54)
	at at.bitfire.davdroid.syncadapter.SyncAdapterService$SyncAdapter.onPerformSync(SyncAdapterService.kt:62)
	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
```

Nextcloud-HEHX6GUXO973FKOUO4EQC.ics:
```
BEGIN:VCALENDAR
PRODID:-//Nextcloud calendar v1.5.5
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VEVENT
CREATED:20170926T202617
DTSTAMP:20170926T202617
LAST-MODIFIED:20170926T202617
UID:UFL8NVK33MN54PT7OPLMXB
SUMMARY:Test123
CLASS:PUBLIC
STATUS:CONFIRMED
DTSTART;VALUE=DATE:20170928
DTEND;VALUE=DATE:20170929
END:VEVENT
END:VCALENDAR
```

I have opened issue at davdroid forum (https://forums.bitfire.at/topic/1553/davdroid-nextcloud-some-events-and-contacts-could-not-be-synchronized) before updating to nc 12.0.3, and after update process when everything seemed to work correctly I have closed it. But this problem is periodically arise. And I don't know what is happening

### Server configuration
:
**Operating system**: Linux webm311.xxl.ha.ovh.net 4.4.67-ovh-vps-grsec-zfs-classid #1 SMP Thu May 11 18:47:35 CEST 2017 x86_64

**Web server:**

**Database:** MYSQL v.5.5.55

**PHP version:** 5.6.31

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 12.0.0 to 12.0.1 to 12.0.3

**Where did you install Nextcloud from:** 11.0.3

**Signing status:**
<details>
<summary>Signing status</summary>

```
Błąd przetwarzania XML: błąd składni
Obszar: http://example.com/index.php/settings/integrity/failed
Numer wiersza: 1, kolumna 1:
<!doctype html>
^
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
 Activity
2.5.2

Comments
1.2.0

Deleted files
1.2.0

External storage support
1.3.0

Federation
1.2.0

File sharing
1.4.0

First run wizard
2.1

Gallery
17.0.0


Log Reader
2.0.0


Monitoring
1.2.0


Nextcloud announcements
1.1

Notifications
2.0.0

Password policy
1.2.2


PDF viewer
1.1.1


Share by mail
1.2.0

Text editor
2.4.1


Theming
1.3.0

Update notification
1.2.0


Versions
1.5.0

Video player
1.1.0


AppOrder
0.4.0
Audio Player
2.1.0

Bookmarks
0.10.1
Brute-force settings
1.0.2
Calendar
1.5.5
Contacts
1.5.3
Dashboard
4.0.5
Flow Upload
0.0.5
GpxPod
2.2.0
Mail
0.7.3
Markdown Editor
2.0.1
News
11.0.5
Notes
2.3.1
Passman
2.1.4
Phone Sync
1.12.1
Radio
0.6.0
RainLoop
5.0.2
Ransomware protection
1.0.4

Tasks
0.9.5
Weather
1.5.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
  'dbtype' => 'mysql',
  'mysql.utf8mb4' => true,
  'version' => '12.0.3.3',
  'dbtableprefix' => 'nc11_',
  'logtimezone' => 'UTC',
  'installed' => true,
  'defaultapp' => 'apporder',
  'maintenance' => false,
  'debug' => false,
  'theme' => '',
  'loglevel' => 2,
  'app.mail.imaplog.enabled' => false,
  'app.mail.smtplog.enabled' => false,
  'updater.release.channel' => 'stable',
  'mail_from_address' => ' ',
  'mail_smtpmode' => 'php',
  'mail_domain' => ' .eu',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'ssl0.ovh.net',
  'mail_smtpport' => '465',
  'mail_smtpname' => ' @ .eu',
  'mail_smtppassword' => ' ',
  'mail_smtpauthtype' => 'LOGIN',
  'versions_retention_obligation' => '7, 8',
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** firefox 55.0.3 (64 bity)

**Operating system:** win7-64bit

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"WcqZ7QoAGxQAAF5RgAYAAABu","level":0,"time":"2017-09-26T18:18:21+00:00","remoteAddr":"37.47.167.53","user":"--","app":"PHP","method":"REPORT","url":"\/remote.php\/dav\/calendars\/USER\/personal\/","message":"A session had already been started - ignoring session_start() at \/home\/SERVER\/www\/chmura\/lib\/private\/Session\/Internal.php#172","userAgent":"DAVdroid\/1.8.1-gplay (2017\/09\/25; dav4android; okhttp3) Android\/5.1.1","version":"12.0.3.3"}
{"reqId":"WcqZ7QoAGxQAAF5RgAcAAABZ","level":0,"time":"2017-09-26T18:18:21+00:00","remoteAddr":"37.47.167.53","user":"--","app":"PHP","method":"REPORT","url":"\/remote.php\/dav\/calendars\/USER\/personal\/","message":"A session had already been started - ignoring session_start() at \/home\/SERVER\/www\/chmura\/lib\/private\/Session\/Internal.php#172","userAgent":"DAVdroid\/1.8.1-gplay (2017\/09\/25; dav4android; okhttp3) Android\/5.1.1","version":"12.0.3.3"}
{"reqId":"WcqZ7woAGxQAAF5RgA8AAABc","level":0,"time":"2017-09-26T18:18:23+00:00","remoteAddr":"37.47.167.53","user":"--","app":"PHP","method":"REPORT","url":"\/remote.php\/dav\/calendars\/USER\/praca\/","message":"A session had already been started - ignoring session_start() at \/home\/SERVER\/www\/chmura\/lib\/private\/Session\/Internal.php#172","userAgent":"DAVdroid\/1.8.1-gplay (2017\/09\/25; dav4android; okhttp3) Android\/5.1.1","version":"12.0.3.3"}
{"reqId":"WcqZ8AoAGxQAAF5RgBIAAABX","level":0,"time":"2017-09-26T18:18:24+00:00","remoteAddr":"37.47.167.53","user":"--","app":"PHP","method":"REPORT","url":"\/remote.php\/dav\/calendars\/USER\/praca\/","message":"A session had already been started - ignoring session_start() at \/home\/SERVER\/www\/chmura\/lib\/private\/Session\/Internal.php#172","userAgent":"DAVdroid\/1.8.1-gplay (2017\/09\/25; dav4android; okhttp3) Android\/5.1.1","version":"12.0.3.3"}
{"reqId":"WcqZ8QoAGxQAAF5RgBYAAABe","level":0,"time":"2017-09-26T18:18:25+00:00","remoteAddr":"37.47.167.53","user":"--","app":"PHP","method":"REPORT","url":"\/remote.php\/dav\/calendars\/USER\/rachunki\/","message":"A session had already been started - ignoring session_start() at \/home\/SERVER\/www\/chmura\/lib\/private\/Session\/Internal.php#172","userAgent":"DAVdroid\/1.8.1-gplay (2017\/09\/25; dav4android; okhttp3) Android\/5.1.1","version":"12.0.3.3"}
{"reqId":"WcqZ8goAGxQAAF5RgBsAAABm","level":0,"time":"2017-09-26T18:18:26+00:00","remoteAddr":"37.47.167.53","user":"--","app":"PHP","method":"REPORT","url":"\/remote.php\/dav\/calendars\/USER\/rachunki\/","message":"A session had already been started - ignoring session_start() at \/home\/SERVER\/www\/chmura\/lib\/private\/Session\/Internal.php#172","userAgent":"DAVdroid\/1.8.1-gplay (2017\/09\/25; dav4android; okhttp3) Android\/5.1.1","version":"12.0.3.3"}
{"reqId":"WcqZ8woAGxQAAF5RgB0AAABz","level":0,"time":"2017-09-26T18:18:27+00:00","remoteAddr":"37.47.167.53","user":"--","app":"PHP","method":"REPORT","url":"\/remote.php\/dav\/calendars\/USER\/rodzinny\/","message":"A session had already been started - ignoring session_start() at \/home\/SERVER\/www\/chmura\/lib\/private\/Session\/Internal.php#172","userAgent":"DAVdroid\/1.8.1-gplay (2017\/09\/25; dav4android; okhttp3) Android\/5.1.1","version":"12.0.3.3"}
{"reqId":"WcqZ9AoAGxQAAF5RgCMAAABp","level":0,"time":"2017-09-26T18:18:28+00:00","remoteAddr":"37.47.167.53","user":"--","app":"PHP","method":"REPORT","url":"\/remote.php\/dav\/calendars\/USER\/rodzinny\/","message":"A session had already been started - ignoring session_start() at \/home\/SERVER\/www\/chmura\/lib\/private\/Session\/Internal.php#172","userAgent":"DAVdroid\/1.8.1-gplay (2017\/09\/25; dav4android; okhttp3) Android\/5.1.1","version":"12.0.3.3"}
{"reqId":"WcqZ9goAGxQAAF5RgCYAAAB7","level":0,"time":"2017-09-26T18:18:30+00:00","remoteAddr":"37.47.167.53","user":"--","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/addressbooks\/users\/USER\/contacts\/","message":"A session had already been started - ignoring session_start() at \/home\/SERVER\/www\/chmura\/lib\/private\/Session\/Internal.php#172","userAgent":"DAVdroid\/1.8.1-gplay (2017\/09\/25; dav4android; okhttp3) Android\/5.1.1","version":"12.0.3.3"}
{"reqId":"WcqaKwoAPW8AAAedhdkAAAA1","level":0,"time":"2017-09-26T18:19:23+00:00","remoteAddr":"77.65.86.41","user":"USER","app":"PHP","method":"MKCOL","url":"\/remote.php\/dav\/files\/USER\/Tmp\/2017-09-26","message":"disk_free_space(): Value too large for defined data type at \/home\/SERVER\/www\/chmura\/lib\/private\/Files\/Storage\/Local.php#293","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.2 (build 1) (Nextcloud)","version":"12.0.3.3"}

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by donkeyDau** [comment]
I have the same issue syncing a my smartphone using davdroid and nexcloud 12.0.3. I'm syncing 2 calenders and one adressbook. First calender showing problems was a (read-only) shared calender. I disabled the sync for this and then the next showed the ETAG problem. Disable the second calender -> the adressbook showed the problem.

[debug1.txt](https://github.com/nextcloud/server/files/1381486/debug1.txt)
[debug2.txt](https://github.com/nextcloud/server/files/1381487/debug2.txt)
[debug3.txt](https://github.com/nextcloud/server/files/1381488/debug3.txt)

**Operating system:** Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-042stab123.1 x86_64)
**Web server:** Apache/2.4.7
**Database:** 5.5.57-0ubuntu0.14.04.1
**PHP version:** PHP 7.0.24-1+ubuntu14.04.1+deb.sury.org+1
**Nextcloud version:** 12.0.3

**Comment by piwats** [comment]
I ran into similar problems. Adding this to the config.php helped me:

```'auth.bruteforce.protection.enabled' => false,```

**Comment by hubertkn** [comment]
Thanks for the advice but unfortunately this hint was not help me.
I have also disabled the brutal-force settings, but it was not help either.

**Comment by brunt82** [comment]
I do not have such problems with Nextcloud / davdroid. Therefore I suppose an misconfiguration on your side. Nextcloud uses sabreDAV to provide the calendar / contacts. And SabreDAV always sends the Etag-header on a GET-request for a vcf/vcs. 

It would help much, if you can provide a tcpdump or wireshark log of the caldav/carddav synchronization, where you can see if the Etag-header was really not sent. Do you know fiddler? This local proxy may help you to create such a dump.

Besides: Check your webserver config file if there is any setting, which will prevent sending the header "Etag". Another idea: do you have any proxy, which forwards the requests? This could also prevent sending the header.

**Comment by donkeyDau** [comment]
I can try to get a dump (probably tomorrow). To disable the brute force did not help me either.
The interesting part is: It was working. I cannot really point at it but I think it failed since the update from 12.0.0 to 12.0.3.

**Comment by donkeyDau** [comment]
I fiddled a bit but I have to confess: I'm not really a network guy ... So creating such a dump will probably not happen (at least not from my side).

But I had a look in the apache log files and found such request after trying to sync the calendar:
> xxx.xxx.xxx.68 - username [26/Oct/2017:22:22:42 +0200] "PROPFIND /oc/remote.php/dav/calendars/username/personal/ HTTP/1.1" 207 5877 "-" "DAVdroid/1.8.1-ose (2017/09/26; dav4android; okhttp3) Android/7.1.2"
xxx.xxx.xxx.68 - username [26/Oct/2017:22:22:42 +0200] "REPORT /oc/remote.php/dav/calendars/username/personal/ HTTP/1.1" 207 2934 "-" "DAVdroid/1.8.1-ose (2017/09/26; dav4android; okhttp3) Android/7.1.2"
xxx.xxx.xxx.68 - username [26/Oct/2017:22:22:42 +0200] "PROPFIND /oc/remote.php/dav/calendars/username/username2_shared_by_fabi/ HTTP/1.1" 207 5886 "-" "DAVdroid/1.8.1-ose (2017/09/26; dav4android; okhttp3) Android/7.1.2"
xxx.xxx.xxx.68 - username [26/Oct/2017:22:22:43 +0200] "REPORT /oc/remote.php/dav/calendars/username/username2_shared_by_fabi/ HTTP/1.1" 207 2105 "-" "DAVdroid/1.8.1-ose (2017/09/26; dav4android; okhttp3) Android/7.1.2"
xxx.xxx.xxx.68 - username [26/Oct/2017:22:22:43 +0200] "GET /oc/remote.php/dav/calendars/username/username2_shared_by_fabi/Nextcloud-4USGIIAXWXKKWGUQNJQSD.ics HTTP/1.1" 200 1596 "-" "DAVdroid/1.8.1-ose (2017/09/26; dav4android; okhttp3)

Now I tried: `wget --save-headers --user=username --password=pass https://www.example.com/oc/remote.php/dav/calendars/username/username2_shared_by_username2/Nextcloud-4USGIIAXWXKKWGUQNJQSD.ics` and this is the result:
> HTTP/1.1 200 OK
Date: Thu, 26 Oct 2017 20:31:32 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Security-Policy: default-src 'none';
X-Frame-Options: SAMEORIGIN
Set-Cookie: oc9voww50jlr=be2n201loevifpgn27ip6njh66; path=/oc; secure; HttpOnly
Set-Cookie: cookie_test=test; expires=Thu, 26-Oct-2017 21:31:32 GMT; Max-Age=3600
Last-Modified: Thu, 26 Oct 2017 20:22:25 GMT
Content-Length: 689
Content-Disposition: attachment; filename*=UTF-8''Nextcloud-4USGIIAXWXKKWGUQNJQSD.ics; filename="Nextcloud-4USGIIAXWXKKWGUQNJQSD.ics"
OC-ETag: "4f73cb29cbac6fc2fb1a2543cccff77e"
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive
Content-Type: text/calendar; charset=utf-8; component=vevent

> BEGIN:VCALENDAR
PRODID:-//Nextcloud calendar v1.5.6
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VEVENT
CREATED:20171026T222209
DTSTAMP:20171026T222209
LAST-MODIFIED:20171026T222209
UID:GEC0AJKIDRYATZQYROKIH
SUMMARY:xxxxxxxxxxxxx
DTSTART;TZID=Europe/Berlin:20171129T190000
DTEND;TZID=Europe/Berlin:20171129T200000
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
END:VCALENDAR

So maybe it's not an Nextcloud but a Davdroid Issue? I doublechecked this by adding the calendar to my thunderbird and there all the syncing works.

**Comment by brunt82** [comment]
No, it is no Davdroid issue. But I'm not sure, if it comes from Nextcloud. As you can see, there is really no "Etag"-header, but a "OC-Etag"-header in your response. When I make the same request (GET ics from a shared calender), I receives both headers "Etag" and "OC-ETag" - both with the same value.

Have you send the request from your Nextcloud server (or from a machine within the same network) to ensure that no proxy could manipulate the response?

**Comment by donkeyDau** [comment]
No, I did it from my machine. But I repeated the request from the server itself and the result is (despite the date and the cookie) the same.

**Comment by brunt82** [comment]
Please check your apache configuration for these keys:

https://forum.owncloud.org/viewtopic.php?f=14&t=16800&start=10#p55688
https://httpd.apache.org/docs/trunk/mod/mod_deflate.html#deflatealteretag

**Comment by brunt82** [comment]
And ensure, that no compression is enabled (like deflate or gzip). But if you do not changed the header response, it seems that your apache does not compress anything.

**Comment by donkeyDau** [comment]
Thank you @brunt82: It's like you mentioned yesterday:

> Besides: Check your webserver config file if there is any setting, which will prevent sending the header "Etag".

I grepped yesterday through my configs but nothing showed up. Checking again today ("inspired" by the owncloud.org link) and it seems more thoroughly (case-insensitive, ... whatever) and my _./conf-available/security.conf_ showed up. And there the

> Header unset ETag
FileETag None

was set. Repeating the `wget`:

> HTTP/1.1 200 OK
Date: Fri, 27 Oct 2017 07:11:50 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Security-Policy: default-src 'none';
X-Frame-Options: SAMEORIGIN
Set-Cookie: oc9voww50jlr=6tbp4ncfboh4o7c49mnm1uf3n0; path=/oc; secure; HttpOnly
Set-Cookie: cookie_test=test; expires=Fri, 27-Oct-2017 08:11:51 GMT; Max-Age=3600
Last-Modified: Thu, 26 Oct 2017 20:22:25 GMT
ETag: "4f73cb29cbac6fc2fb1a2543cccff77e"
Content-Length: 689
Content-Disposition: attachment; filename*=UTF-8''Nextcloud-4USGIIAXWXKKWGUQNJQSD.ics; filename="Nextcloud-4USGIIAXWXKKWGUQNJQSD.ics"
OC-ETag: "4f73cb29cbac6fc2fb1a2543cccff77e"
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive
Content-Type: text/calendar; charset=utf-8; component=vevent

Here we can the OC-ETag and ETag. Final proof is still missing as I don't have my smartphone with me ...

But I'm a bit unsure as it was set in the _security.conf_ with the comment:

> # Setting this header will prevent MSIE from interpreting files as something
# else than declared by the content type in the HTTP headers.
# Requires mod_headers to be enabled.

Is this a security or a compatibilty issue (I don't care about MSIE)?

**Comment by brunt82** [comment]
Are you sure, that the comment refers to "Header unset ETag" and not to "Header set X-Content-Type-Options: "nosniff""?  
However: if you like to sync CalDAV/CardDAV, you need the ETag header. So, you have no other way as disabling the setting.

**Comment by donkeyDau** [comment]
Yes, this might be. Was not sure if the comment is just for that line or all following.

Anyway. Thanks a lot for your effort and patience @brunt82

**Comment by skjnldsv** [comment]
@georgehrke

**Comment by georgehrke** [comment]
I will close this issue, because it's old and hasn't received comments in almost two years.

If you still experience this issue __with the latest version__ of Nextcloud and __the latest version__ of davx5, please speak up and we will reopen.

Please comment using our [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) and __fill it completely__. I suspect this mostly to be a configuration problem, where your apache or NGINX reverse proxy drops certain headers.
