### ISSUE TITLE
problem with wanted varying permissions for complex structures

### ISSUE THREAD

**Issue by caterpi** [nextcloud/server#6663]
### Steps to reproduce
1. Create a folder and share it to another Nextcloud account without the permission to delete anything inside it.
2. Create another folder inside the folder (lets call them F, f) and share it to the same person, this time include the permission to delete something.

### Expected behaviour
The person the folders nowe have been shared to gets a new shared folder to his front page. When he tries to delete something in F nothing will happen. When he tries to delete something in f it works.

### Actual behaviour
Actually he gets both folders to his frontpage. When he navigates through F to f he is'nt able to delete anything, if he navigates directly from the frontpage to f, he is.

I'd really appreciate a feature to manage the permissions in more complex structures. It'd be a great improvement to this already nice cloud. 

### General server configuration

**Operating system:** Linux zhhocld1.zhh.funk 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64

**Web server:** Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/7.0.21 (apache2handler)

**Database:** mysql 5.5.52

**PHP version:** 7.0.21
<details>
        <summary>PHP-modules loaded</summary>

```
- Core
- date
- libxml
- openssl
- pcre
- zlib
- filter
- hash
- Reflection
- SPL
- session
- standard
- apache2handler
- apcu
- bz2
- calendar
- ctype
- curl
- dom
- mbstring
- fileinfo
- ftp
- gd
- gettext
- gmp
- iconv
- igbinary
- json
- ldap
- exif
- mcrypt
- mysqli
- PDO
- pdo_mysql
- pdo_sqlite
- Phar
- posix
- redis
- shmop
- SimpleXML
- sockets
- sqlite3
- sysvmsg
- sysvsem
- sysvshm
- tokenizer
- xml
- wddx
- xmlreader
- xmlwriter
- xsl
- memcached
- zip
- Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.2 - 12.0.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:** YOUR ANSWER HERE

**Where did you install Nextcloud from:**  YOUR ANSWER HERE

**Are you using external storage, if yes which one:** files_external is disabled

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** YOUR ANSWER HERE (LDAP/ActiveDirectory/Webdav/...)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
- activity: 2.5.2
- admin_audit: 1.2.0
- bruteforcesettings: 1.0.2
- comments: 1.2.0
- contacts: 1.5.3
- dav: 1.3.0
- encryption: 1.6.0
- external: 2.0.3
- federatedfilesharing: 1.2.0
- federation: 1.2.0
- files: 1.7.2
- files_pdfviewer: 1.1.1
- files_sharing: 1.4.0
- files_texteditor: 2.4.1
- files_trashbin: 1.2.0
- files_versions: 1.5.0
- files_videoplayer: 1.1.0
- firstrunwizard: 2.1
- gallery: 17.0.0
- issuetemplate: 0.2.2
- logreader: 2.0.0
- lookup_server_connector: 1.0.0
- mood: 0.3.2
- nextcloud_announcements: 1.1
- notifications: 2.0.0
- oauth2: 1.0.5
- password_policy: 1.2.2
- provisioning_api: 1.2.0
- serverinfo: 1.2.0
- sharebymail: 1.2.0
- survey_client: 1.0.0
- systemtags: 1.2.0
- theming: 1.3.0
- twofactor_backupcodes: 1.1.1
- twofactor_totp: 1.3.1
- updatenotification: 1.2.0
- user_ldap: 1.2.1
- workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
- circles
- files_external
- user_external
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "ocxabnyu06fe",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "zhhocld1.zhh.funk",
        "cloud.funk-gruppe.de",
        "download.nextcloud.com"
    ],
    "datadirectory": "\/nc_data",
    "overwrite.cli.url": "http:\/\/cloud.funk-gruppe.de\/",
    "dbtype": "mysql",
    "version": "12.0.2.0",
    "dbname": "nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "localhost",
        "port": 6379
    },
    "mail_smtpmode": "smtp",
    "mail_smtphost": "zhhmex10.zhh.funk",
    "mail_smtpport": "25",
    "mail_smtptimeout": 10,
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "funk-gruppe.de",
    "mail_from_address": "FunkCloud",
   "maintenance": false,
    "loglevel": 2,
    "theme": "funktheme"
}
```
</details>

<details>
        <summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:55.0) Gecko/20100101 Firefox/55.0

**Operating system:** YOUR ANSWER HERE

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
cc @nextcloud/sharing

**Comment by skjnldsv** [comment]
Duplicate of #4785
