### ISSUE TITLE
Deselecting Tag by mouseclick from large Tag list, associates different Tag from Tag list for file.

### ISSUE THREAD

**Issue by Archyver** [nextcloud/server#6665]
### Steps to reproduce
I apologize for not using the entire template, it just seemed redundant since it's your demo setup and I do not have the product installed myself

1. create 12 tags in the live demo system, can put them all on about.txt  1 2 3 4 5 6 a b c d e f
2. Click details of another file (about.odt) and associate the first tags you see in the drop down window 1 2 3 4 5 6 to this file, about.odt
3. Next Scroll down for the seventh spot to see what's there, my case it was 'a'
4. Scroll back up to the top choice in Tag Dropdown, mine was1,
5. Click on the first Tag associated with the file to attempt to remove it and see a different Tag be added instead.

### Expected behaviour
Tell us what should happen

-Clicking on a Tag that is already associated with a file/folder should deselect it, not select another Tag

### Actual behaviour
Tell us what happens instead

-Trying to Deselect the Tag in the first position '1' per my example of drop down instead adds the first unselected tag in the list.

### Server configuration
I was on your online Demo system, entries below are what I am running to access your server

**Operating system**:
Win10

**Nextcloud version:** (see Nextcloud admin page)
12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
no clue 

**Where did you install Nextcloud from:**
I didn't, running your live demo

**Console Log

DevTools failed to parse SourceMap: https://demo.nextcloud.com/eich1bi1/core/vendor/dist/purify.min.js.map

**Comment by nickvergessen** [comment]
Please update to 12.0.3
The issue has been solved there.
