### ISSUE TITLE
Only one ldap group assigned to the user

### ISSUE THREAD

**Issue by rgalexey** [nextcloud/server#6671]
### Steps to reproduce
1. Create multiple groups in Ldap and add user into each.
2. Go to users tab in Nextcloud
3. Only one group is show as asigned for group instead of multiple. Same time all groups are listed on  left side of UI. Same as they are listed in droprdown of groups for user. But only one has check box on.

### Expected behaviour
Multiple Ldap groups should shows as assigned to the user

### Actual behaviour
Only one group is show as asigned for group instead of multiple.

### Server configuration

**Operating system**:
Centos 7

**Web server:**
Apache 

**Database:**
Mysql

**PHP version:**
7.0.23

**Nextcloud version:** (see Nextcloud admin page)
12.0.2

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Openldap

**Comment by dnauck** [comment]
Hello,

this is afaik fixed by #6453
