### ISSUE TITLE
Dedicated favicon selection

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#6672]
Currently the favicon is generated via the logo that is uploaded to the theming app. Quite often the logo contains a name, which is not good to read in a favicon. Would it make sense to allow to upload a special favicon via the theming app. That is often requested and makes also sense from my point of view, because the favicon only holds the key part of the logo and the logo used in the login page and header can contain more details as well as the name.

Or is there another way to easily theme the favicon while still using the theming app?

Feedback is welcome here @nextcloud/designers @nextcloud/theming

**Comment by jancborchardt** [comment]
Could it be possible that even while using the theming app, custom img files in the theme would be respected? cc @juliushaertl

@MorrisJobke I'm not totally opposed, the thing is just that this is yet another small addition and they will pile up. :)

Maybe it would be best to add it to @juliushaertl's customcss theming app, and rename that to "Advanced theming" or so? Another candidate for an option there is also to have a separate logo for log in and header (which is kinda similar to here cause of the text vs no text logos).

What do you think?

**Comment by juliushaertl** [comment]
@MorrisJobke @jancborchardt It should already be possible to use a custom favicon from a theme together with the theming app. That should work fine with https://github.com/nextcloud/server/pull/5070, but it has not been backported to 12.

**Comment by juliushaertl** [comment]
> Maybe it would be best to add it to @juliushaertl's customcss theming app, and rename that to "Advanced theming" or so? Another candidate for an option there is also to have a separate logo for log in and header (which is kinda similar to here cause of the text vs no text logos).

That might be a good idea, to have a more advanced interface for replacing any image in the customcss app. But we should keep it simple to understand of course.

**Comment by jancborchardt** [comment]
> That might be a good idea, to have a more advanced interface for replacing any image in the customcss app. But we should keep it simple to understand of course.

@juliushaertl yeah, that’s why even there we should only add stuff which we heard from requests or issues, not just everything. :) That’s why I listed the 3 things: custom CSS, different logo for log in and header, and custom favicon.

Although as said, if we do the »different logo for header«, we could generate the favicon from there and that would probably already be good.

@MorrisJobke in any case, does the custom favicon together with theming app as @juliushaertl described work for that? https://github.com/nextcloud/server/pull/5070

**Comment by JK74** [comment]
@MorrisJobke "Currently the favicon is generated via the logo that is uploaded to the theming app." 

If that is the case then there is a bug as this is not happening. We have an custom logo uploaded but it did not change the favicon icon.

On the other hand a logo can be a rectangle while a favicon ico needs to be always a square. As such I would suggest as above done at ticket #6703  to have a seperate field added for the favicon icon in the themes suggestion.

thnx again for evaluating this request. 
Cheers!

**Comment by frisi** [comment]
computing the favicon out of a logo won't work in most cases (too much details)

:+1: for having a separate favicon or the possibility to additionally activate a filesystem theme and overwrite the different favicons (currently favicon-touch.png and favicon-mask.svg are used in 12.0.3) there.

**Comment by juliushaertl** [comment]
@jancborchardt Would you be fine with adding some advanced settings to the default theming app that are hidden by default and can be used just in case someone wants to tweak it a bit more?

Then we could add custom css, custom logo for login and a custom favicon to that section. I would really like to have this bundled with the main theming app, otherwise we would need a lot more logic to allow other apps changing images from the server.

**Comment by rullzer** [comment]
@juliushaertl that sounds like a good approach!

**Comment by jancborchardt** [comment]
@juliushaertl yes, that sounds good! Just make it a section below with "Advanced theming" as h2. No need to hide it.

**Comment by Wikinaut** [comment]
I suggest to have at least an option in config.php to allow admins to set different than the standard favicon urls. This is what for example MediaWiki has:

https://www.mediawiki.org/wiki/Manual:$wgFavicon:
``` 
$wgFavicon = "../favicon.ico";
```

**Comment by MariusBluem** [comment]
Will be fixed with https://github.com/nextcloud/server/pull/8540 😉

**Comment by Wikinaut** [comment]
Danke!

**Comment by MariusBluem** [comment]
> Danke!

Bitte 🇩🇪

**Comment by MorrisJobke** [comment]
Added to theming app #8540
