### ISSUE TITLE
CRITICAL:  Folder/Files are moved to Trash on Server when Sync Client is Restarted 

### ISSUE THREAD

**Issue by Nextcloud-User** [nextcloud/server#6679]
Scenario:   

* Nextcloud Sync Client isn't running
* Any folder under Sync Folder on local computer is removed to reclaim local drive space 
* Next time Nextcloud Sync Client is run and checks for updates on local sync folder, 
 -> it doesn't pop-up a warning and MOVES/TRASHES Folder on the Server Side <-

Possible Solution:

To protect data on server:

* When such changes are detected, offer user option to remove Folder from sync list and keep data intact on server-side.  In any case, A POP-UP WARNING should be presented

**Comment by rullzer** [comment]
Well this is just what the client does. It syncs both ways. If you remove folders locally it will sync that to the server.

Asking the user if changes should be propegated while the client is offline doesn't scale or work out.

If you don't want the files locally I suggest you mount webdav.

**Comment by ChristophWurst** [comment]
@Nextcloud-User you can selectively choose which folders should be synced by the client. Just unmark the ones you want to get rid of on the client side but not delete on the server.
