### ISSUE TITLE
'bruteforce_attempts' DB table populated if 'Basic Auth' enabled in web server

### ISSUE THREAD

**Issue by leonklingele-work** [nextcloud/server#6681]
### Steps to reproduce
1. Configure your webserver to require Basic Auth login
2. Set up a Nextcloud instance
3. Open Nextcloud Login page, authenticate with Basic Auth, but _don't_ try to log in into your Nextcloud account

### Expected behaviour
- `bruteforce_attempts` DB table should not be touched

### Actual behaviour
- A failed login is inserted to `bruteforce_attempts`, requests are throttled

### Server configuration

**Web server:**
nginx

**Nextcloud version:** (see Nextcloud admin page)
Git checkout, rev e5d39e63d15069d10fa723c34472be4b0b95d1ad

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"..","level":2,"time":"2017-09-28T10:26:33+00:00",
"remoteAddr":"..","user":"--","app":"core","method":"GET","url":"\/login",
"message":"Login failed: 'MY_BASICAUTH_USERNAME' (Remote IP: '..')",
"userAgent":"..","version":"13.0.0.4"}
```

**Comment by nickvergessen** [comment]
Our clients also use BasicAuth, so yes this needs to be logged?!

**Comment by leonklingele-work** [comment]
Then there should be an options to turn the feature off / make it opt-in.
My current workaround is to strip the `Authorization` header using nginx:
`proxy_set_header Authorization "";`

**Comment by LukasReschke** [comment]
We don't support deploying Nextcloud behind an additional basic authorization deployment. You may want to use SAML or some other kind of authentication mechanism here.
