### ISSUE TITLE
Add Release notes Infobutton to Apps page

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/server#6684]
In my Opinian there should be a requirement for a Release notes to get listed in Nextcloud Apps. But I would also agree with a optional release notes button if an update is available and the Update delivers a Release notes.

![grafik](https://user-images.githubusercontent.com/7795891/30971735-16f4e748-a469-11e7-86ef-6068899a311b.png)

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers for a nice way to integrate this

**Comment by jancborchardt** [comment]
Yeah, could be done via a popover / tooltip on hovering the update button.

**Comment by dnauck** [comment]
@jancborchardt i don't thin a hover / popover is very useful for a changelog that could be quiet large with upgrade and compatibility infos, etc.

I would like to see a separate/explicit button that opens the changelog (maybe a link to the github page/Changelog.md of the app, etc.)

**Comment by juliushaertl** [comment]
This should be in the sidebar related to the app, see https://github.com/nextcloud/server/issues/2138 for that.

**Comment by MorrisJobke** [comment]
> This should be in the sidebar related to the app, see #2138 for that.

I added it there - let's close this here and continue the discussion there.

**Comment by klawdhfzasjhaa** [comment]
Could someone please re-open this? It's still necessary to go to the App Store to see the changes.
#2138 and #9565 did not fix this. I my view, it does not need to be an infobutton, but a separate area below the discription text. Mockup is attached.
![relnotes](https://user-images.githubusercontent.com/2808094/65351170-ab565180-dbe7-11e9-99ac-4bbd556c3975.png)

**Comment by kesselb** [comment]
@klawdhfzasjhaa https://github.com/nextcloud/server/issues/9165

**Comment by klawdhfzasjhaa** [comment]
It's a pity, that this useful thing is waiting to be implemented for so long...
