### ISSUE TITLE
External storage encryption not working

### ISSUE THREAD

**Issue by MoeSattler** [nextcloud/server#6685]
### Steps to reproduce
1. Upload file to Dropbox
2. check dropbox

### Expected behaviour
When uploading a file to dropbox with encryption on, I shouldn't be able to see the file decrypted in dropbox

### Actual behaviour
I can see the file decrypted in dropbox

### Server configuration
<img width="1186" alt="screen shot 2017-09-28 at 16 25 44" src="https://user-images.githubusercontent.com/8615251/30972057-d5edf7f2-a469-11e7-88cc-7154da630937.png">
<img width="1166" alt="screen shot 2017-09-28 at 16 26 09" src="https://user-images.githubusercontent.com/8615251/30972060-d7dd4b26-a469-11e7-817f-576b6981aa53.png">
<img width="1151" alt="screen shot 2017-09-28 at 16 26 21" src="https://user-images.githubusercontent.com/8615251/30972062-d91f8c60-a469-11e7-8477-770e0f5eb684.png">
<img width="929" alt="screen shot 2017-09-28 at 16 26 29" src="https://user-images.githubusercontent.com/8615251/30972071-dc8a7b26-a469-11e7-8dfa-ac13c7e0163d.png">

**Comment by MorrisJobke** [comment]
> When uploading a file to dropbox with encryption on, I shouldn't be able to see the file decrypted in dropbox

Have you downloaded the file? We don't encrypt the filename, but only the content. It looks like that the file is not able to be read (no thumbnail in Dropbox).

**Comment by e-alfred** [comment]
You wont be able to access Dropbox anymore with Nextcloud until there is support added to it for Dropbox API v2. Dropbox shut down the old API on Sept. 28. See this issue:

https://github.com/nextcloud/server/issues/991

**Comment by MorrisJobke** [comment]
No feedback for 1 month - closing.
