### ISSUE TITLE
External site of Dropbox API v1(Oauth1) has been shutdown

### ISSUE THREAD

**Issue by jimmy5670** [nextcloud/server#6694]
The Dropbox official is already shutdown Oauth1 Authenticate, the Dropbox connect method must change.
![api v1 shutdown details dropbox developer blog](https://user-images.githubusercontent.com/30663643/30989503-899b3934-a4d0-11e7-81b4-8bab91aa8b59.png)

**Comment by umgfoin** [comment]
Expected and discussed here #991 .
