### ISSUE TITLE
External Storage Dropbox OAuth2

### ISSUE THREAD

**Issue by xXSTrikeXx** [nextcloud/server#6697]
Refered to #3039

https://blogs.dropbox.com/developers/2017/09/api-v1-shutdown-details/

The problem is, that OAuth1 was shutdowned by Dropbox. The good point is that Dropbox has created a migration guide:
https://www.dropbox.com/developers/reference/migration-guide

Maybe I find time and skill to do that, but don´t count on me, I´m very busy atm. ;)

**Comment by juliushaertl** [comment]
Duplicate of https://github.com/nextcloud/server/issues/991
