### ISSUE TITLE
calendar floods admin_audit log

### ISSUE THREAD

**Issue by RuudschMaHinda** [nextcloud/server#670]
### Steps to reproduce
1. enable admin_audit with loglevel 1
2. create calendar
3. use mac-os calendar to use created webdav calendar

### Expected behaviour
Login and syncing every 5 to 10 minutes
do I need to check MacOS calendar-App or nextcloud calendar
### Actual behaviour
Several logins within one minute

### Server configuration
**Operating system**:
freebsd
**Web server:**
nginx
**Database:**
MySQL
**PHP version:**
5.6
**Nextcloud version:** (see Nextcloud admin page)
9-0-53
**Updated from an older Nextcloud/ownCloud or fresh install:**
ownCloud upgrade
**Where did you install Nextcloud from:**
tar.gz

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"ILyqAqeu6L0nJqBB2TgJ","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:03:23+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar\/","user":"user.name"}
{"reqId":"dGAwHc0ggNPzkUM61x3W","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:03:24+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/","user":"--"}
{"reqId":"dGAwHc0ggNPzkUM61x3W","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:03:24+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/","user":"user.name"}
{"reqId":"KiI9T8cIErPKqlsBGz8J","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:03:25+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar-3_shared_by_admin.user\/","user":"--"}
{"reqId":"KiI9T8cIErPKqlsBGz8J","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:03:25+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar-3_shared_by_admin.user\/","user":"user.name"}
{"reqId":"TfSNoZcyUlvyyz4Xu6Yl","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:03:26+02:00","method":"PUT","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/owncloud-8b21d67902119f782adb218877832278.ics","user":"--"}
{"reqId":"TfSNoZcyUlvyyz4Xu6Yl","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:03:26+02:00","method":"PUT","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/owncloud-8b21d67902119f782adb218877832278.ics","user":"user.name"}
{"reqId":"bxa4UdQ97667+GwdOv5G","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:03:27+02:00","method":"GET","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/owncloud-8b21d67902119f782adb218877832278.ics","user":"--"}
{"reqId":"bxa4UdQ97667+GwdOv5G","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:03:27+02:00","method":"GET","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/owncloud-8b21d67902119f782adb218877832278.ics","user":"user.name"}
{"reqId":"+oZtehG5Lx9er9vphqRe","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:03:28+02:00","method":"REPORT","url":"\/remote.php\/caldav\/principals\/user.name\/","user":"--"}
{"reqId":"+oZtehG5Lx9er9vphqRe","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:03:28+02:00","method":"REPORT","url":"\/remote.php\/caldav\/principals\/user.name\/","user":"user.name"}
{"reqId":"NqdWrFNB+hPeUBZl\/KuQ","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:03:29+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/","user":"--"}
{"reqId":"NqdWrFNB+hPeUBZl\/KuQ","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:03:29+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/","user":"user.name"}
{"reqId":"qpXxFYv5Tsr9HLUHuOKW","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:03:30+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/","user":"--"}
{"reqId":"qpXxFYv5Tsr9HLUHuOKW","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:03:30+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/","user":"user.name"}
{"reqId":"CX\/VV\/6J7hMVCtSkDsr1","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:03:31+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/","user":"--"}
{"reqId":"CX\/VV\/6J7hMVCtSkDsr1","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:03:31+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/","user":"user.name"}
{"reqId":"JOGb0DFzCshrTRpij1vC","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:03:32+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/principals\/users\/admin.user\/","user":"--"}
{"reqId":"JOGb0DFzCshrTRpij1vC","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:03:32+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/principals\/users\/admin.user\/","user":"user.name"}
{"reqId":"HLAUudF5q4J0vlAddX1T","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:03:33+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar-2_shared_by_admin.user\/","user":"--"}
{"reqId":"HLAUudF5q4J0vlAddX1T","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:03:33+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar-2_shared_by_admin.user\/","user":"user.name"}
{"reqId":"Lhp9z9zGuipOhD78NAHg","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:03:34+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/","user":"--"}
{"reqId":"Lhp9z9zGuipOhD78NAHg","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:03:34+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/","user":"user.name"}
{"reqId":"a5VRzXgm3nwDxQe2kq6W","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:03:35+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/principals\/users\/admin.user\/","user":"--"}
{"reqId":"a5VRzXgm3nwDxQe2kq6W","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:03:35+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/principals\/users\/admin.user\/","user":"user.name"}
{"reqId":"6JVsjo95cao8nJL3rHkQ","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:03:36+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar-3_shared_by_admin.user\/","user":"--"}
{"reqId":"6JVsjo95cao8nJL3rHkQ","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:03:36+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar-3_shared_by_admin.user\/","user":"user.name"}
{"reqId":"WuRimRPIN\/qZo7ijekkW","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:03:37+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar\/","user":"--"}
{"reqId":"WuRimRPIN\/qZo7ijekkW","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:03:37+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar\/","user":"user.name"}
{"reqId":"0JIloHndCh8spWBP6HiK","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:03:38+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar\/","user":"--"}
{"reqId":"0JIloHndCh8spWBP6HiK","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:03:38+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar\/","user":"user.name"}
{"reqId":"7Eg4IScssBw7DOurbhRA","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:03:39+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/","user":"--"}
{"reqId":"7Eg4IScssBw7DOurbhRA","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:03:39+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/","user":"user.name"}
{"reqId":"gLN6V3LMF8Vd+K8GdaFJ","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:03:40+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar-2_shared_by_admin.user\/","user":"--"}
{"reqId":"gLN6V3LMF8Vd+K8GdaFJ","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:03:40+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar-2_shared_by_admin.user\/","user":"user.name"}
{"reqId":"t7lJeVcB3aAygUWDVn83","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:03:41+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar-3_shared_by_admin.user\/","user":"--"}
{"reqId":"t7lJeVcB3aAygUWDVn83","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:03:41+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar-3_shared_by_admin.user\/","user":"user.name"}
{"reqId":"E0RYK+XqWS4C27mU4\/0p","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:03:42+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/","user":"--"}
{"reqId":"E0RYK+XqWS4C27mU4\/0p","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:03:42+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/","user":"user.name"}
{"reqId":"COy8qy89L+78P9WqtV40","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:03:44+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/","user":"--"}
{"reqId":"COy8qy89L+78P9WqtV40","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:03:44+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/","user":"user.name"}
{"reqId":"stNxOrw7Eo14wrsnu+bO","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:03:59+02:00","method":"REPORT","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/","user":"--"}
{"reqId":"stNxOrw7Eo14wrsnu+bO","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:04:00+02:00","method":"REPORT","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/","user":"user.name"}
{"reqId":"yAi7xgNhIf7UJA1phI7V","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:04:01+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar\/","user":"--"}
{"reqId":"yAi7xgNhIf7UJA1phI7V","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:04:01+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar\/","user":"user.name"}
{"reqId":"VdiSY6fH30wE135azPOE","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:04:02+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar\/","user":"--"}
{"reqId":"VdiSY6fH30wE135azPOE","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:04:02+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar\/","user":"user.name"}
{"reqId":"ydMlAeKLV1mM7AsjCXcg","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:04:03+02:00","method":"REPORT","url":"\/remote.php\/caldav\/principals\/user.name\/","user":"--"}
{"reqId":"ydMlAeKLV1mM7AsjCXcg","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:04:03+02:00","method":"REPORT","url":"\/remote.php\/caldav\/principals\/user.name\/","user":"user.name"}
{"reqId":"ZW6Po3y09BH4d8qnmDH\/","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:21:24+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/","user":"--"}
{"reqId":"ZW6Po3y09BH4d8qnmDH\/","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:21:24+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/","user":"user.name"}
{"reqId":"g2jIdsX7Z3x3UyuV5n8J","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:21:25+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/","user":"--"}
{"reqId":"g2jIdsX7Z3x3UyuV5n8J","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:21:25+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/","user":"user.name"}
{"reqId":"RIhzEjvxukimyMbz4uS1","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:21:26+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/","user":"--"}
{"reqId":"RIhzEjvxukimyMbz4uS1","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:21:26+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/","user":"user.name"}
{"reqId":"Mq\/iqd4Nh4gV8jv5AQEc","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:21:27+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/","user":"--"}
{"reqId":"Mq\/iqd4Nh4gV8jv5AQEc","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:21:27+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/","user":"user.name"}
{"reqId":"OGUKQALuYT04\/BXzKU+F","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:21:28+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar-2_shared_by_admin.user\/","user":"--"}
{"reqId":"OGUKQALuYT04\/BXzKU+F","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:21:28+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar-2_shared_by_admin.user\/","user":"user.name"}
{"reqId":"oZ6DV4XYlPZvey9+4tMW","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:21:29+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar\/","user":"--"}
{"reqId":"oZ6DV4XYlPZvey9+4tMW","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:21:29+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar\/","user":"user.name"}
{"reqId":"bKeU83NYWM7xlAPEClOw","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:21:30+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar-3_shared_by_admin.user\/","user":"--"}
{"reqId":"bKeU83NYWM7xlAPEClOw","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:21:30+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar-3_shared_by_admin.user\/","user":"user.name"}
{"reqId":"Pju+jkJ0omEGb+JM6VUH","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:39:24+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/","user":"--"}
{"reqId":"Pju+jkJ0omEGb+JM6VUH","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:39:24+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/","user":"user.name"}
{"reqId":"BBPxTnx3jaZvK0OeziWf","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:39:25+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/","user":"--"}
{"reqId":"BBPxTnx3jaZvK0OeziWf","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:39:25+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/","user":"user.name"}
{"reqId":"grJrnx4jYi7BgBGYkB0F","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:39:26+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/","user":"--"}
{"reqId":"grJrnx4jYi7BgBGYkB0F","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:39:26+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/","user":"user.name"}
{"reqId":"nZkzIYHFDto4EB5nVsLS","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:39:26+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/","user":"--"}
{"reqId":"nZkzIYHFDto4EB5nVsLS","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:39:27+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/","user":"user.name"}
{"reqId":"8IQtv+P3\/x8nE25EhRD5","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:39:28+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar-2_shared_by_admin.user\/","user":"--"}
{"reqId":"8IQtv+P3\/x8nE25EhRD5","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:39:28+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar-2_shared_by_admin.user\/","user":"user.name"}
{"reqId":"4jIgPfRm80+IeKERCUXv","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:39:29+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar\/","user":"--"}
{"reqId":"4jIgPfRm80+IeKERCUXv","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:39:29+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar\/","user":"user.name"}
{"reqId":"VMmZXnfjiXZsUZtuxRHF","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:39:30+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar-3_shared_by_admin.user\/","user":"--"}
{"reqId":"VMmZXnfjiXZsUZtuxRHF","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:39:30+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar-3_shared_by_admin.user\/","user":"user.name"}
{"reqId":"DsdtBpRkex\/3pEviHYWw","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:39:31+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/","user":"--"}
{"reqId":"DsdtBpRkex\/3pEviHYWw","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:39:31+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/","user":"user.name"}
{"reqId":"gVe5Zey39e3dtNXYEPjD","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:39:32+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/","user":"--"}
{"reqId":"gVe5Zey39e3dtNXYEPjD","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:39:32+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/","user":"user.name"}
{"reqId":"WSuF2lh24vdYPf2xF4wS","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:39:38+02:00","method":"REPORT","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/","user":"--"}
{"reqId":"WSuF2lh24vdYPf2xF4wS","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:39:38+02:00","method":"REPORT","url":"\/remote.php\/caldav\/calendars\/user.name\/defaultcalendar\/","user":"user.name"}
{"reqId":"SnybUFa7xFetkDudnXmF","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:39:39+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar\/","user":"--"}
{"reqId":"SnybUFa7xFetkDudnXmF","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:39:39+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar\/","user":"user.name"}
{"reqId":"3QtRVKr8FNsnIjCB7JlD","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:39:40+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar\/","user":"--"}
{"reqId":"3QtRVKr8FNsnIjCB7JlD","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:39:40+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/project-calendar\/","user":"user.name"}
{"reqId":"dpZ39qguOx7n6gYWRb38","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:57:24+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/","user":"--"}
{"reqId":"dpZ39qguOx7n6gYWRb38","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login successful: \"user.name\"","level":1,"time":"2016-07-30T11:57:24+02:00","method":"PROPFIND","url":"\/remote.php\/caldav\/calendars\/user.name\/","user":"user.name"}
{"reqId":"dAd0Or7S7+gq84WaWY3k","remoteAddr":"95.90.XXX.XXX","app":"admin_audit","message":"Login attempt: \"user.name\"","level":1,"time":"2016-07-30T11:57:25+02:00","method":"PROPPATCH","url":"\/remote.php\/caldav\/calendars\/user.name\/","user":"--"}
</details>

**Comment by mar1u5** [comment]
I think from the function-side this behavior is correct ... if you use some log reader software - you may fade them out 😁

**Comment by RuudschMaHinda** [comment]
Thanks, so maybe a different, more fine grained log level system might be interesting then. 
I don't know if this suggestion is serious or feasable, just popped into my head.

But I will also look into that Calendar App on MacOS, since this is the only user that generates these many entries. Got to see what happens when more people wake up from their vacation.

Thanks again!
