### ISSUE TITLE
Log 2FA failed attempts for better security measures

### ISSUE THREAD

**Issue by Berzerker** [nextcloud/server#6702]
I would suggest an enhancement to add 2FA (for example, twofactor_totp, @ChristophWurst), or perhaps any third-party app, to be able to write to nextcloud.log. This would allow usage with third-party security tools such as fail2ban.

**Comment by ChristophWurst** [comment]
That would be a nice enhancement. In fact, it's easy to add. https://github.com/nextcloud/server/blob/master/lib/private/Authentication/TwoFactorAuth/Manager.php#L233-L236 is where we handle failed attempts (we show in in your activity log already). The class already has an instance of `ILogger` injected via the constructor, so all that's left is a call to `$this->logger->warning(…)` 😉

**Comment by Berzerker** [comment]
Submitted #6710 to solve this. :)

**Comment by ChristophWurst** [comment]
You're awesome :rocket:

**Comment by rullzer** [comment]
Done in https://github.com/nextcloud/server/pull/7916
