### ISSUE TITLE
favicon icon not in theme; enhancement request for GUI addition 

### ISSUE THREAD

**Issue by JK74** [nextcloud/server#6703]
See: https://docs.nextcloud.com/server/12/admin_manual/configuration_server/theming.html

NC 12.0.3.
I can change the favicon.* in the core folder but what about making it a standard icon that I could upload in the GUI at the admin settings? In that way I don't have to change it over again each time after an upgrade?
So beside the upload we have already for logo / login screen do an favicon file upload?

thanx, Jeroen

**Comment by juliushaertl** [comment]
duplicate of https://github.com/nextcloud/server/issues/6672
