### ISSUE TITLE
[NC 11 alpha] occ command line tool displays ownCloud instead of Nextcloud

### ISSUE THREAD

**Issue by sndrr** [nextcloud/server#671]
### Steps to reproduce
1. go to the installed NC root directory
2. start the occ command line tool (i.e. sudo -u www-data ./occ)
3. observe that the output uses the wording "ownCloud"

### Expected behaviour
When grepping for cloud, it should output with Nextcloud.
```
user@host:/var/www/nextcloud$ sudo -u www-data ./occ | grep -i cloud
  db:convert-type                     Convert the Nextcloud database to the newly configured one
```

### Actual behaviour
When grepping for cloud, it outputs ownCloud
```
user@host:/var/www/nextcloud$ sudo -u www-data ./occ | grep ownCloud
  db:convert-type                     Convert the ownCloud database to the newly configured one
```
### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
11.0 alpha
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
git
```
user@host:/var/www/nextcloud$ git describe
warning: tag 'v9.0.1beta2' is really 'v9.1.0beta2' here
v9.0.1beta2-1045-g3b386af
```

**Comment by icewind1991** [comment]
Fixed with #672
