### ISSUE TITLE
External storage support [dropbox api]

### ISSUE THREAD

**Issue by kanenses** [nextcloud/server#6713]
External Storage do not work anymore with dropbox, api v1 as been shutdown from dropbox, please update it to api v2

can read more about, here:
https://blogs.dropbox.com/developers/2017/09/api-v1-shutdown-details/

thank you

**Comment by xXSTrikeXx** [comment]
duplicate of #9912

**Comment by tflidd** [comment]
closing as a duplicate of https://github.com/nextcloud/server/issues/991
