### ISSUE TITLE
Downloading multiple files through a zip file gives an inconsisten zip archive

### ISSUE THREAD

**Issue by Titan-C** [nextcloud/server#6716]
### Steps to reproduce
1. Select more than one file. 
2. Use the download button to download the generated zip file
3. Open the zip file

### Expected behaviour
The zip file shall open without errors with the selected files for download and allow the user to extract all files locally

### Actual behaviour
I can not even open the file. I get the error:

```
Loading the archive /tmp/mozilla_me0/Photos.zip failed with the following error:
Failed to open archive: Zip archive inconsistent
```

### Server configuration

This happens on your live demo. Just launch an instance and try. I don't have a personal nextcloud install.

**Comment by j-ed** [comment]
I've just tried to replicate this by using the short-term test access from `https://demo.nectcloud.com` without success. I selected all three image files in the Photos folders and downloaded them as zip-file. Then I open the archive file using **7-zip v16.04** without any problem.

**Comment by nickvergessen** [comment]
Also works fine here, downloaded with firefox and unpacked with archive manager (gnome)

**Comment by Titan-C** [comment]
I don't understand where the error is, probably in the way the file is created, neither I'm sure this is the place to file the issue but it keeps showing up for me.

I'm in archlinux
- Download with firefox 55.0.3(64-bit) from `https://demo.nextcloud.com`
- Try to open with ark v17.08.1, gives error:
  `Failed to open archive: Zip archive inconsistent`
- Try to open with p7zip v16.02, there is no newer port in linux, gives error:
```bash
7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,12 CPUs Intel(R) Xeon(R) CPU E5-2609 v3 @ 1.90GHz (306F2),ASM,AES-NI)

Scanning the drive for archives:
1 file, 2360847 bytes (2306 KiB)

Extracting archive: Photos.zip

ERRORS:
Headers Error

--
Path = Photos.zip
Type = zip
ERRORS:
Headers Error
Physical Size = 2360847
64-bit = +

    

Archives with Errors: 1

Open Errors: 1
```
- using unzip does not seem to give an error.
