### ISSUE TITLE
Changing LDAP user Full Name

### ISSUE THREAD

**Issue by pc-maniac** [nextcloud/server#6719]
### Steps to reproduce
1. Configure LDAP autentification
2. Create a user on LDAP server
3. Login to NextCloud with login/password from LDAP
4. Change user FullName on the LDAP server
5. Logoff/Logon user on NextCloud, goto to personal settings - old FullName appears.

### Expected behaviour
If FullName updated from LDAP and admin can see it, all other users need to see this new user FullName.

### Actual behaviour
When I changed FullName of user on the LDAP server, this FullName appears on the users admin page, but in user's personal settings page still displays old FullName.

### Server configuration
Ubuntu Server 16.04 LTS x86-64
NextCloud v12.0.0 clean install

**Comment by MorrisJobke** [comment]
@blizzz Could this be a caching issue?

**Comment by blizzz** [comment]
Sounds like that, except for

>  this FullName appears on the users admin page, but in user's personal settings page still displays old FullName.

**Comment by pc-maniac** [comment]
If some additional details needed, I can provide it.

**Comment by blizzz** [comment]
I'd need to allocate some time to reproduce and check this. It's not very high on my priorities right now, tbh. If you're familiar with PHP… ?

**Comment by pc-maniac** [comment]
> If you're familiar with PHP… ?
Basic level

**Comment by zinsserzh** [comment]
The same thing happened to me. I found a quick fix. In the admin's user list page, click on each of the users whose name has been changed in ldap, and then press enter. Then the name is also changed in nextcloud's system. However, this is just a dirty workaround.

**Comment by blizzz** [comment]
Mh, does anybody still experience this? I was never able to reproduce this. There was a similar case when the name was not being updated in the local addressbook, but that sounds a bit different to what was described here.

**Comment by johkoenig** [comment]
This issue is still present on Nextcloud 14.0.3 in combination with a Windows Server 2016 AD/LDAP. 
The old information is shown in the "personal information" page of each user. Also, when opening the "contact search" by clicking on the button right next to the users avatar on the upper right corner, the old user names of the other LDAP users are also listed.

**Comment by blizzz** [comment]
Alright, those are fixed with https://github.com/nextcloud/server/pull/12054 (→ next maintenance releases)
