### ISSUE TITLE
formatTimeSpan() and formatDateSpan() always present past time spans

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/server#6722]
Maybe more a personal problem: When I want to calculate a time span via **relative_modified_date()** , the return value is always a span that directs to the past, even if the time span is in the future. Not sure, if this intended or if it could be enhanced. 

https://github.com/nextcloud/server/blob/9236733a838c91d8b275404f5f3497ddd200686e/lib/private/DateTimeFormatter.php#L208

https://github.com/nextcloud/server/blob/9236733a838c91d8b275404f5f3497ddd200686e/lib/private/DateTimeFormatter.php#L148

**Comment by blizzz** [comment]
Fixed by #6837
