### ISSUE TITLE
Does not automaticaly upgrade if a second app directory is present

### ISSUE THREAD

**Issue by freeeflyer** [nextcloud/server#6723]
This issue is identical to issue nextcloud/server/issues/6135 which applied to NC 12.0.1.
The resolution said "The updater included in 12.0.2 ignores custom apps folders as per nextcloud/updater#130. This means for future updates you should not receive this warning."

Sorry 12.0.2 still has the issue: 

![image](https://user-images.githubusercontent.com/12149490/31072104-ef5e4a16-a766-11e7-88ef-de42995b8f06.png)

Steps to reproduce

read the documentation
move non core app to a second directory (app2/ in my case)
try to update
Expected behaviour

Should update the server

Actual behaviour

says apps2 directory is present and does not update

Server configuration

Operating system:
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
Web server:
apache2                            2.4.27-5.1+ubuntu14.04.1+deb.sury.org+1
Database:
postgresql-9.1                     9.1.14-0ubuntu0.12.04

PHP version:
libapache2-mod-php7.0              7.0.23-1+ubuntu14.04.1+deb.sury.org+1

Nextcloud version: (see Nextcloud admin page)
12.0.2
Updated from an older Nextcloud/ownCloud or fresh install:
Updated since at least Owncloud 7

Where did you install Nextcloud from:
wget ... owncloud-xx.xx.zip

Documentation

**Comment by nickvergessen** [comment]
is apps2 register in your config.php?

**Comment by freeeflyer** [comment]
indeed..

`  array (
    0 =>
    array (
      'path' => '/<my-path>/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/<my-path>/apps2',
      'url' => '/apps2',
      'writable' => true,
    ),
  ),`

**Comment by freeeflyer** [comment]
Hello ? Is the configuration I posted ok ?

**Comment by nickvergessen** [comment]
`<my-path>` is the same for both?

**Comment by freeeflyer** [comment]
Yes.. It should not ?

**Comment by nickvergessen** [comment]
Ah now I see the thing.
Well 12.0.2 was a special release (which was not planned) to only fix one issue.
So the new updater was only added in 12.0.3

If you still get the error on 12.0.3 to 12.0.4, please report again

**Comment by freeeflyer** [comment]
Ok but you've just blown your chance to give the same reason next time :D
