### ISSUE TITLE
no nextcloud/data/ directory

### ISSUE THREAD

**Issue by drewgreat** [nextcloud/server#6726]
### Steps to reproduce
1. Download zip/tar.bz2
2. Extract
3. chown the directory
4. Server 503 errors because there is no nextcloud/data/nextcloud.log

### Expected behaviour
I don't know. I suppose I would expect the zip file to contain all the necessary files.

### Actual behaviour
503 error.

### Server configuration

**Operating system**:
FreeBSD
**Web server:**
Nginx
**Database:**
Not sure of the database version, hasn't been configured at this point anyway
**PHP version:**
7.1
**Nextcloud version:** (see Nextcloud admin page)
12.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh
**Where did you install Nextcloud from:**
nextcloud.com

**List of activated apps:**
None

**Nextcloud configuration:**
Can't configure

**Are you using external storage, if yes which one:** local/smb/sftp/...
I hope to

**Are you using encryption:** yes/no
Nope

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Nope

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
2017/10/01 19:57:54 [error] 95218#100779: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught ErrorException: fopen(/usr/local/www/nextcloud/data/nextcloud.log): failed to open stream: No such file or directory in /usr/local/www/nextcloud/lib/private/Session/Internal.php:150
Stack trace:
#0 [internal function]: OC\Session\Internal->trapError(2, 'fopen(/usr/loca...', '/usr/local/www/...', 132, Array)
#1 /usr/local/www/nextcloud/lib/private/Log/File.php(132): fopen('/usr/local/www/...', 'a')
#2 [internal function]: OC\Log\File::write('PHP', 'ErrorException:...', 3)
#3 /usr/local/www/nextcloud/lib/private/Log.php(307): call_user_func(Array, 'PHP', 'ErrorException:...', 3)
#4 /usr/local/www/nextcloud/lib/private/Log.php(165): OC\Log->log(3, 'ErrorException:...', Array)
#5 /usr/local/www/nextcloud/lib/private/Log/ErrorHandler.php(81): OC\Log->critical('ErrorException:...', Array)
#6 [internal function]: OC\Log\ErrorHandler::onException(Object(ErrorException))
#7 {main}
  thrown in /usr/local/www/nextcloud/lib/private/Session/Internal.php on line 150
```
</details>

#### Nextcloud log (data/nextcloud.log)
HA!  This file is the problem.  That's cute.
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment]
@LukasReschke anything changed in packaging lately?
I think it was there before, but 12.0.3 does not contain it anymore.

**Comment by MorrisJobke** [comment]
@rullzer @nickvergessen It was not there at all. Neither in 9, 10, or 11. Should we really add it? Usually it shows that the directory is missing. The error message only show the results of another error that should be logged.

**Comment by xfisthebest** [comment]
well, im using the latest nextcloud.. in users page i see users data directory.. but when i try to open in filemanger there is no such directory of data where user data is stored.. but on site it shows that data stored in that directory...?

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
