### ISSUE TITLE
Resume chunked uploads

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#673]
Hi,

I have developed the resuming of chunked uploads in android.
Currently I store the upload id and the successful chunks. With these infos I can skip the successful parts and just upload the remaining ones.
To simplify the client code I thought of this:
- use a reproducable id and not random id as now
- allow to get the current successfull chunks as a list
  With both enhancement the client does not need to store any information about the upload.

**Comment by PhenX** [comment]
This feature is a must-have for big files.
I integrated such a feature with this library which works like a charm : http://resumablejs.com/

**Comment by jancborchardt** [comment]
This seems often requested – @karlitschek @LukasReschke @MorrisJobke @rullzer any plan here, maybe for 13?

**Comment by cowai** [comment]
@jancborchardt For the web UI owncloud is doing a PR here: https://github.com/owncloud/core/pull/26306
I think it is mostly finished.

**Comment by karlitschek** [comment]
Yes. Improvement a lot of people want.

**Comment by oparoz** [comment]
@icewind1991 told us that this would have the side-effect of preventing large files from being uploaded as they would have to be held in memory to be chunked. So we should find a way for the uploader to adapt its behaviour and not always use chunked mode.

**Comment by rullzer** [comment]
@tobiasKaminsky if you are using the new chunking ng this is available. What is the webdav endpoint the android client uses?

**Comment by tobiasKaminsky** [comment]
/remote.php/webdav

**Comment by tcitworld** [comment]
Will this be into 13 ? I'll try to integrate ownCloud's work this week-end maybe.

**Comment by MorrisJobke** [comment]
At least the chunked upload is downstreamed: #7056

**Comment by greinick** [comment]
Any news on that topic? Timeline? Status? Priority? How may I help in testing?

As this would be a big positiv step forward in our daily business it would be nice to have some information if possible.

As well it would be nice for anonymous uploads too and an overview how much percent is already uploaded.

Thanks a lot an regards.

**Comment by MorrisJobke** [comment]
> Any news on that topic? Timeline? Status? Priority? How may I help in testing?

Currently it's just a proposal, not yet on the roadmap and not not worked on. If you want to have this feature in a short period of time Nextcloud GmbH offers consulting work for features like this. Feel free to contact the sales team here: https://nextcloud.com/enterprise/buy/

**Comment by tobiasKaminsky** [comment]
We have now chunked uploads in Android client, which is using the chunking api: https://docs.nextcloud.com/server/stable/developer_manual/client_apis/WebDAV/chunking.html

**Comment by juliushaertl** [comment]
@tobiasKaminsky Repoening, as it is not yet implemented in the web ui

**Comment by Cinerar** [comment]
Just a suggestion, take a look at https://tus.io/

**Comment by tobiasKaminsky** [comment]
I fear that this is not possible to use as we need to rely on our dav protocol.

**Comment by pankid** [comment]
Would be amazing to have this in the web UI. Been having issues lately with large file uploads with the file drop feature over less than ideal wifi. Played with [psitransfer](https://github.com/psi-4ward/psitransfer) which uses tus.io, and worked even with me turning on and off my wifi card repeatedly.

**Comment by electrofloat** [comment]
> @tobiasKaminsky Repoening, as it is not yet implemented in the web ui

Any news on this?

**Comment by tobiasKaminsky** [comment]
Not from my (client team lead) side. 
It is implemented on all clients, but not on web.
That is why it is in server repository.
So I cannot share any news on this…

**Comment by manolopm** [comment]
I would like to try to work on this or at least clarify a little bit to help someone to finish it.
@tobiasKaminsky could you point me how did you do in the android client?
I've seen old web client create and md5+time, the new one creates a random string.

**Comment by susnux** [comment]
How to do it: https://docs.nextcloud.com/server/stable/developer_manual/client_apis/WebDAV/chunking.html

WebUI is also using the new API and retry failed chunks only public shares are missing.
