### ISSUE TITLE
Loss of performance on Login after upgrade from NC10 + LDAP to NC 12 + LDAP

### ISSUE THREAD

**Issue by rogerfv1** [nextcloud/server#6732]
### Steps to reproduce

1. Upgrade or Install NC12
2.  Enable/Configure user_ldap plugin
3. Properly configure cache settings:
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>  array (    'host' => 'IP',    'port' => 6379,  ),
4. Run Login/Logout tests

### Expected behaviour
Time to Logon/Logoff should remain similiar to previous versions.

### Actual behaviourProblem:
Login/Logout is slower than previous versions (ex: NC10).

### Server configuration

**Operating system**: Debian 8

**Web server:** Apache 2.4

**Database:** Postgresql 9.4

**PHP version:** php 5.6

**Nextcloud version:** 12.0.3

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

We verified that the number of ldap operations has increased from 13 to 35 during the entire login process. Thus, the ldap response time has also increased.
It appears that the cache for ldap operations only works after 60s. 
For example: If the logout occurs before 60s then nextcloud makes operations to ldap server. After 60s, no ldap operations are made.

These are the results we got in our tests.

Login LDAP Operation | NC10.05 | NC11.04 | NC12.03  
-- | -- | -- | --
Ldap bind | 5 | 15 | 14
Ldap unbind | 5 | 15 | 14
Ldap search | 3 | 8 | 7
Total | 13 | 38 | 35

Logout before 1minute | NC10.05 | NC11.04 | NC12.03
-- | -- | -- | --
Ldap bind | 0 | 2 | 2
Ldap unbind | 0 | 2 | 2
Ldap search | 0 | 1 | 1
Total | 0 | 5 | 5

Logout after 1minute | NC10.05 | NC11.04 | NC12.03
-- | -- | -- | --
Ldap bind | 0 | 0 | 0
Ldap unbind | 0 | 0 | 0
Ldap search | 0 | 0 | 0
Total | 0 | 0 | 0

**Is that the expected behaviour? Or could this be a cache problem?**

**Comment by nickvergessen** [comment]
@blizzz any idea?

**Comment by blizzz** [comment]
Depends on the whole setup. There was nothing that changed login fundamentally within the LDAP backend, but already the 5 LDAP binds on login are too many. 2, or 3, yes. Unless the connections gets lost inbetween. That might be also the case when initiated from the LDAP server, if it has a time-out configured. Or, if more than one LDAP server connection is configured. 

I agree that it looks suspiciously as if caching  is in effect only with a delay (for which there is neither reason nor logic on our side).

**Comment by rogerfv1** [comment]
Hi,

Maybe the issue is a missing setLastCheck in "public function generateToken".

File: lib/private/Authentication/Token/DefaultTokenProvider.php
Function:  public function generateToken

--- lib/private/Authentication/Token/DefaultTokenProvider.php.old	2017-10-18 12:32:13.440589464 -0200
+++ lib/private/Authentication/Token/DefaultTokenProvider.php	2017-10-18 12:25:05.112589464 -0200
@@ -93,6 +93,7 @@
 		$dbToken->setType($type);
 		$dbToken->setRemember($remember);
 		$dbToken->setLastActivity($this->time->getTime());
\+		$dbToken->setLastCheck($this->time->getTime());
 
 		$this->mapper->insert($dbToken);

**Comment by rogerfv1** [comment]
These are the results we got after patch.

Login | NC10.05 | NC11.04 | NC12.03 | OC10.03 | NC12.03 + pacth
-- | -- | -- | -- | -- | --
Ldap bind | 5 | 15 | 14 | 2 | 2
Ldap unbind | 5 | 15 | 14 | 2 | 2
Ldap search | 3 | 8 | 7 | 1 | 1
  |   |   |   |   |  
Logout (before 1minute) | NC10.05 | NC11.04 | NC12.03 | OC10.03 | NC12.03 + pacth
Ldap bind | 0 | 2 | 2 | 0 | 0
Ldap unbind | 0 | 2 | 2 | 0 | 0
Ldap search | 0 | 1 | 1 | 0 | 0
  |   |   |   |   |  
Logout (after 1minute) | NC10.05 | NC11.04 | NC12.03 | OC10.03 | NC12.03 + pacth
Ldap bind | 0 | 0 | 0 | 0 | 0
Ldap unbind | 0 | 0 | 0 | 0 | 0
Ldap search | 0 | 0 | 0 | 0 | 0

**Comment by blizzz** [comment]
@ChristophWurst can you evaluate the proposed change on DefaultTokenProvider, please? ^

**Comment by ChristophWurst** [comment]
@blizzz the proposed patch makes a lot of sense. I don't see a reason for checking the token right upon creation. It still should be valid and thus this check is unnecessary.

@rogerfv1 could you please submit this patch as a pull request? Thanks a lot for digging into this.

**Comment by fgsl** [comment]
Hi, @ChristophWurst and @blizzz. @rogerfv1 asked me to submit change and I did it.

**Comment by ChristophWurst** [comment]
Thank you very much @fgsl. I will try to allocate some time to look into this next week as it seems the tests are failing now. Should be easy to fix though 😉
