### ISSUE TITLE
calendar sharing with user who has his displayname set leads to error

### ISSUE THREAD

**Issue by trupf** [nextcloud/server#6741]
### Steps to reproduce
1. create user in nextcloud and set the display name
2. logout and log in as different user
3. go to calendar app and share the calendar with above user
4. give permission for modification of calendar entries to that user

### Expected behaviour
The user should see the shared calendar and be able to add/delete/modify entries

### Actual behaviour
The user can only read the calendar. 
As far as I can see there is an additional wrong entry created in the mysql databeas table "oc_dav_shares" which uses the displayname of the user instead of the user uid. A second entry for the same user with correct uid but only read permissions is also there. If you correct this directly via sql commands the user has full access as expected. 

### Server configuration

**Operating system**:
Debian stretch

**Web server:**
nginx

**Database:**
MariaDB 10.1.26

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 12.0.2

**Where did you install Nextcloud from:**
updated via web interface (with each version update....)
installed from https://download.nextcloud.com/server/releases/latest-11.tar.bz2

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - audioplayer: 2.1.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.5
  - comments: 1.2.0
  - contacts: 1.5.3
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ocsms: 1.12.1
  - phonetrack: 0.0.5
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - tasks: 0.9.5
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - files_pdfviewer
  - files_versions
  - firstrunwizard
  - logreader
  - password_policy
  - previewgenerator
  - systemtags
  - theming
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "integrity.check.disabled": true,
        "instanceid": "oc85ae6e4789",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "trhome.my-router.de",
            "nas.tr-home.de",
            "nas",
            "localhost"
        ],
        "datadirectory": "\/var\/ocdata",
        "overwrite.cli.url": "https:\/\/trhome.my-router.de\/owncloud",
        "dbtype": "mysql",
        "dbname": "nextcloud",
        "dbhost": "127.0.0.1",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "version": "12.0.3.3",
        "appstoreenabled": true,
        "appstore.experimental.enabled": true,
        "appstoreurl": "https:\/\/api.owncloud.com\/v1",
        "apps_paths": [
            {
                "path": "\/var\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "enable_previews": true,
        "enable_avatars": true,
        "preview_max_scale_factor": 1,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": "0.0"
        },
        "installed": true,
        "default_language": "de",
        "mail_domain": "nas2.tr-home.de",
        "mail_smtpmode": "sendmail",
        "mail_from_address": "trnextcloud",
        "trashbin_retention_obligation": "32,auto",
        "version_retention_obligation": "32,auto",
        "syslog_tag": "nextCloud",
        "logtimezone": "Europe\/Berlin",
        "loglevel": 2,
        "debug": true,
        "logfile": "\/tmp\/var\/log\/nginx\/nextcloud.log",
        "forcessl": true,
        "maintenance": false,
        "asset-pipeline.enabled": false,
        "quota_include_external_storage": false,
        "theme": "",
        "updatechecker": true,
        "filesystem_check_changes": 1,
        "updater.release.channel": "stable"
    }
}
</details>

**Are you using external storage, if yes which one:**
local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by nickvergessen** [comment]
Actually the calendar app sends a wrong request...

Maybe the dav backend should check if the user/group exists, but also the calendar should send the user id not the display name @georgehrke

**Comment by georgehrke** [comment]
It uses the display name? wut?

Okay, that's obviously not how its supposed to be ...
Looking into it.

**Comment by georgehrke** [comment]
fix is in https://github.com/nextcloud/calendar/pull/623
