### ISSUE TITLE
Feature request: write the same information in Syslog.php and in File.php

### ISSUE THREAD

**Issue by GustavoSLinden** [nextcloud/server#6747]
Hi,
I would like to request that the same information sent to File log should be sent to Syslog log. On our server we are using syslog and there isn't much information written to log. So, to help audit and debuging, on each update we copy & paste the function `write()` from `nextcloud/lib/private/Log/File.php` to `nextcloud/lib/private/Log/Syslog.php`.
Server configuration

**Operating system:** Debian 8

**Web server:** Apache 2.4

**Database:** Postgresql 9.4

**PHP version:** php 5.6

**Nextcloud version:** 12.0.3

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Comment by nickvergessen** [comment]
You mean like the time, ip and other info?

**Comment by GustavoSLinden** [comment]
Yes,
exactly that.

For example, these fields are written on File but not in Syslog:

     $entry = compact(
            'reqId',
            'level',
            'time',
            'remoteAddr',
            'user',
            'app',
            'method',
            'url',
            'message',
            'userAgent',
            'version'
        );

**Comment by jbrrrr** [comment]
I support this request.
If you log into syslog, you do not receive the reqId and cannot identify the log entry if a user reports a problem with this reqId.

**Comment by joshtrichards** [comment]
Implemented by #16416 and was officially released in NC17.
