### ISSUE TITLE
Nextcloud freezes on app update when app is not downloadable on Github

### ISSUE THREAD

**Issue by aronovgj** [nextcloud/server#6748]
### Steps to reproduce
1. Have issues downloading an app from Github
2. Have a new version of the app available
3. Update the app via browser interface

### Expected behaviour
- Nextcloud should be operable at least while the download is not finished
- Something should be indicating what is happening (e.g. download completed 0%)
- Download should time out (did not have the patience to figure out if that happens)
- Don't go into maintenance mode as long as non-critical stuff is happening (like downloading the app)

### Actual behaviour
- Nextcloud is stuck during download 
- As the download never finishes, NC can't be used
- Nextcloud seems to go into maintenance mode immediatelly but is not reachable during download
- To get NC working I have to kill 443/tcp, restart nginx, restart php and get NC out of maintenance mode

To see the thread I am referring to, see [this](https://help.nextcloud.com/t/contacts-2-0-0-released/21834/5?u=aronovgj)

**Comment by skjnldsv** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
