### ISSUE TITLE
Feature request: Remote download from webgui

### ISSUE THREAD

**Issue by larsemil** [nextcloud/server#6753]
This is a feature request.

### Expected behaviour
Somewhere in nextcloud web gui there should be a possibility to input an url. Nextcloud will then download it and put into downloads. Its status should be logged in activites.

**Comment by nickvergessen** [comment]
We had this in the past, and IIRC it was removed for security reasons? @LukasReschke

**Comment by MorrisJobke** [comment]
See https://github.com/owncloud/core/pull/210 for a part of the discussion.

We removed it because it would allow to run into DoS attacks and other potentially risky attack vectors.

Thus I will close this.

**Comment by MorrisJobke** [comment]
The request came in multiple times. Maybe others have more details.

**Comment by Bubu** [comment]
Here's more context on the removal of this feature: https://github.com/owncloud/core/issues/13326
