### ISSUE TITLE
Search API

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#676]
Hey guys, for android I would like to implement a real search. Is there already a API for this? It needs to take a search string and returns a list of files available for the user that match the query.

**Comment by LukasReschke** [comment]
Ref https://github.com/owncloud/core/issues/25373

**Comment by LukasReschke** [comment]
So at the moment there doesn't seem an official API to be existent. Thoughts on that, cc @schiessle @MorrisJobke?

**Comment by tobiasKaminsky** [comment]
Maybe we can talk about this at the conference? :)

**Comment by MorrisJobke** [comment]
> Maybe we can talk about this at the conference? :)

@tobiasKaminsky Could you put it on your conference list?

**Comment by tobiasKaminsky** [comment]
Actually I had have it already on the android todo list: https://github.com/nextcloud/android/issues/179 ;)

**Comment by Bugsbane** [comment]
Hopefully, this will become something that can be extended beyond files, too. For example, in the web UI if you open the contacts app and search, you don't just get a list of files from the files app. I understand that right now, the android app only handles files, so just a list of files makes sense now, but it would be useful to be able to search all of your Nextcloud from the app.

**Comment by supportreq** [comment]
@LukasReschke are we seeing this in the near future?

**Comment by LukasReschke** [comment]
> @LukasReschke are we seeing this in the near future?

Not on the roadmap but contributions are always welcome 😉

**Comment by supportreq** [comment]
frankly not sure how to implement it but can you guide me.. do i need to make a plugin? or how do i go out.. i just want it to allow searching in all possible directories for the file/folder name..

**Comment by MorrisJobke** [comment]
@mario @marinofaggiana this is the ticket for the search API (it still is in planning, so there is no API spec yet)

**Comment by MorrisJobke** [comment]
@karlitschek @LukasReschke Who works on the search API on the server side?

**Comment by mario** [comment]
@MorrisJobke it should be @icewind1991 :)

**Comment by marinofaggiana** [comment]
Urgent, please 👍

**Comment by MorrisJobke** [comment]
The WIP PR for the server is here: https://github.com/nextcloud/server/pull/3360

**Comment by MorrisJobke** [comment]
> The WIP PR for the server is here: #3360

@marinofaggiana There you can also find the documentation and an example.

**Comment by MorrisJobke** [comment]
PR:

* main #3360
* favourite search #3772
* fix ordering #3824

Pending issues:

* [x] #3815
