### ISSUE TITLE
error by Deck update

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/server#6762]
newest nextcloud
on Openmandriva 3.0
_______

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT DISTINCT(TABLE_NAME) AS `table` FROM INFORMATION_SCHEMA . COLUMNS WHERE TABLE_SCHEMA = ? AND (COLLATION_NAME <> 'utf8_bin' OR CHARACTER_SET_NAME <> 'utf8') AND TABLE_NAME LIKE "oc_%"' with params ["nextcloud"]: SQLSTATE[HY000]: General error: 1 Can't create/write to file '/tmp/#sql_1174_0.MAI' (Errcode: 2 "No such file or directory")
Detaillierte Protokollmeldungen
Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT DISTINCT(TABLE_NAME) AS `table` FROM INFORMATION_SCHEMA . COLUMNS WHERE TABLE_SCHEMA = ? AND (COLLATION_NAME <> 'utf8_bin' OR CHARACTER_SET_NAME <> 'utf8') AND TABLE_NAME LIKE "oc_%"' with params ["nextcloud"]: SQLSTATE[HY000]: General error: 1 Can't create/write to file '/tmp/#sql_1174_0.MAI' (Errcode: 2 "No such file or directory")
Das Update ist fehlgeschlagen. Bitte melde dieses Problem an die Nextcloud Community.

______________

mach ich doch glatt :)
i do it just in time :)

best regards
blacky

**Comment by nickvergessen** [comment]
> Can't create/write to file '/tmp/#sql_1174_0.MAI'

Please google and repair your MySQL/Maria database
