### ISSUE TITLE
Cannot run files_external:notify with credentials saved in database

### ISSUE THREAD

**Issue by eddik1970** [nextcloud/server#6765]
### Steps to reproduce
1. Set up Windows share as External Storage with credentials saved in database
2. Sync with Windows Client. New files deep in structure wont sync 
3. Run occ files_external:notify -v <mount_id>

### Expected behaviour
Files that changes should be listed

### Actual behaviour
Error:  
  Error while trying to create storage 
  Username and/or password required

If adding --user and --pass (manual page says --username but that wont work)
  Error while running self-test, no changes detected
  [Icewind\SMB\Exception\ConnectionException]
  Connection not valid

### Server configuration

**Operating system**: 
Centos 7 with REMI PHP 7 (7.0.24)

**Web server:** 
Apache (httpd-2.4.6-67.el7.centos.2.x86_64)

**Database:**
Mariadb (mariadb-server-5.5.56-2.el7.x86_64)

**PHP version:**
7.0.24 

**Nextcloud version:** (see Nextcloud admin page)
12.0.3 

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 12.0.2 which had the same problem

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-12.0.2.zip

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - audioplayer: 2.1.0
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_reader: 1.0.4
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - deck
  - encryption
  - nextant
  - ransomware_protection
  - user_external

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "ocke90mcit25",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.xxxxxxx.no"
        ],
        "datadirectory": "\/var\/www\/html\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/cloud.sp-asp.no\/nextcloud",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "post",
        "mail_domain": "xxxxxxx.no",
        "mail_smtphost": "xxxxxx.xxxx.farm",
        "mail_smtpport": "25",
        "trusted_proxies": [
            "10.238.1.250",
            "10.250.0.2"
        ],
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "maintenance": false,
        "theme": "",
        "loglevel": 0
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
SMB 

**Are you using encryption:** yes/no
No 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP 

### Client configuration
**Browser:**
Windows Client 2.3.2 

**Operating system:**
Windows 7/10

**Comment by eddik1970** [comment]
I suppose this is correct, because multiple users would be using the same mount_ids.

**Comment by urbenlegend** [comment]
I see the same issue when attempting to setup a notify on my external SMB storage. Running Fedora 26 with Apache 2.4.29, PHP 7.1.11, and Nextcloud 12.0.3

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
