### ISSUE TITLE
URL in PDF file not clickable

### ISSUE THREAD

**Issue by djermann** [nextcloud/server#6771]
A customer noticed that URLs in PDF files, which get uploaded to Nextcloud, do not get detected automatically, so one can not click on them like a link. Therefore, I want to request this feature.

### Steps to reproduce
1. Create a PDF file with a URL inside that is not a hyperlink, just plain text.
2. Upload it to Nextcloud.
3. Open it in the web interface of Nextcloud.

### Expected behaviour
The URL should be clickable like a link.

### Actual behaviour
The URL is not clickable.

**Comment by nickvergessen** [comment]
I tried with https://www.antennahouse.com/XSLsample/pdf/sample-link_1.pdf and it works quite fine here.
So the issue is, that your PDF does not promote the thing as a link. Nothing nextcloud can/should fix.

Apart from this your bug is better placed in the https://github.com/nextcloud/files_pdfviewer repository. but they should give you the same reply

**Comment by djermann** [comment]
I did not mean a hyperlink inside the PDF file, I just meant when you copy a URL to a PDF file as plain text like in this file: https://cloud.woelkli.com/s/goZfWzip8qP8mLd
If you download this file and open it with chromium for example, the URL is clickable, but within Nextcloud it isn't.

I will open this issue in the files_pdfviewer repository.

Thank you

**Comment by nickvergessen** [comment]
yeah let chrome do chrome stuff,
any normal PDF viewer has this not clickable too, I tried all 3 I have here on linux.
If you want to make it clickable in the PDF, make it clickable in the source before generating the pdf. See https://gradcollege.okstate.edu/sites/default/files/PDF_linking.pdf

**Comment by djermann** [comment]
Yeah this is clear to me. 
Our customer just noticed that in DropBox, Apple Preview and Adobe Acrobat Reader the URL is clickable, but in Nextcloud it is not, therefore I want to request this feature in Nextcloud, too.
