### ISSUE TITLE
Share & Delete

### ISSUE THREAD

**Issue by PhrozenByte** [nextcloud/server#6777]
Nextcloud is a great tool to share files with others. But there's some very common use case/workflow that can't be realized with Nextcloud: "Share & Delete"

I suggest adding a checkbox to the "Share with" dialog described as "Remove file after sharing". You can't check "Remove file after sharing" and uncheck "Allow reshares" at the same time.

If User A shares a file or folder with User B and checks the "Remove file after sharing" checkbox, the file/folder immediately appears in User B's file list as "shared by User A". After a short waiting period (e.g. one hour, allowing User A to change the options; the waiting period might be subject of a server-side setting), Nextcloud moves the file/folder from User A's file list to User A's trashbin. However, the file/folder still shows up in User B's file list as a ordinary file/folder that was "shared by User A" and remains accessible. ~~As soon as User B uploads a new version of the file/folder, the "shared by User A" information disappears (this feature is IMO not strictly necessary).~~ If User A shares a file/folder with multiple users or a group, Nextcloud creates copies of the file/folder for all "target" users. Deduplication (i.e. not creating `n` copys of the file/folder when it was shared with `n` users and having just one copy of the file/folder on the filesystem) is appreciated, but IMO not strictly necessary.

~~If a user shares a file/folder with a public link and sets a expiry date, the "Remove file after sharing" checkbox appears. If the user checks this checkbox, nothing happens at first, but as soon as the expiry date is reached, Nextcloud automatically moves the file/folder to the user's trashbin.~~

**Reasoning:** Just think of the good old email as file sharing instrument: You simply attach a file and send it. You can now delete the attached file and the recipient still receives the file. This is very common especially in corporate environments: Someone wants to share some files with someone else (e.g. a employee wants to send the result of a task to his supervisor), without the demand to keep the sent file ("throw away" files). This isn't possible with Nextcloud, you can indeed share a file, but you'll have to keep it until the recipient saved it to some other place. You even don't have any possibility to know *when* this is going to be true. So it "spams" your cloud's file list for ever.

**#edit 2017-10-09:** Struck out some optional features which might confuse the reader, not strictly necessary for a first implementation, might get implemented later.

**Comment by nickvergessen** [comment]
I'm not sure, this sounds very specific.

Maybe if "remove later" is an option you can use the retention feature?
https://docs.nextcloud.com/server/12/admin_manual/file_workflows/retention.html

**Comment by PhrozenByte** [comment]
The idea is primarily to represent the good-old email based file sharing: You send a file and that's it, you can delete the sent file, no more trash laying around on your computer. That's currently not possible with Nextcloud, if User A deletes a shared file in his cloud (no matter manually or via the rentention app), the file also disappears from User B's cloud. Think of it like some sort of "upload a file to someone else's cloud" (even though this isn't strictly true, it might help to understand what I'm trying to achieve with this idea).

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by npelov** [comment]
I'm sure a lot of people would like to have that. Even though it's not requested too often people would use it if it's there. However I think the check box should be next to "set expiration date" and it should be labeled as "Delete on expire"

**Comment by VBlack2019** [comment]
A much needed feature

**Comment by prolibre** [comment]
+1 A much needed feature

**Comment by trollagit** [comment]
+1 A much needed feature
