### ISSUE TITLE
Create Web Installer script

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#678]
Hi, to facilitate the setup of Nextcloud t for "**New**" installations it might be very helpful to use a web based installer script (similar to the one from OC) ! 

regards, hitam4450

**Comment by mar1u5** [comment]
Mhmm ... I've also thought about that, but ... Uploading a Archive and unpack is also not soo complex :stuck_out_tongue_winking_eye: 

I'll talk to some Nextclouders about that tomorrow at the Hackweek :wink:

**Comment by hitam4450** [comment]
Ok, Well I am looking forward to receiving your valuable comments and hope to see a script aroiund, soon.

regards, hitam4450

**Comment by mar1u5** [comment]
As discussed with @karlitschek and @LukasReschke

**Comment by karlitschek** [comment]
Very cool!  👍

**Comment by hitam4450** [comment]
Well, then lets see and try for the version 1.0.........  hopefully soon.....

**Comment by mar1u5** [comment]
The web installer is finished now: https://github.com/nextcloud/web-installer

Please test 💪 THX @MorrisJobke @LukasReschke

**Comment by hitam4450** [comment]
Hi, I did a test installation, worked fine without any problems...all NextCloud Branding!

Perfect!

regards, hitam4450
