### ISSUE TITLE
Accept regular internal shares

### ISSUE THREAD

**Issue by lvarnava** [nextcloud/server#6781]
Nextcloud 12.0.3

In the case when I share with users of my nextcloud,
"file sharing" loads the file into the user directory without asking permission, the desktop client downloads it to the PC automatically.

**Comment by nickvergessen** [comment]
The sync client has a setting up to which new folders are automatically downloaded.

However "accepting" of normal shares is also on the todo (can't find the issue right now, but maybe @schiessle knows)

**Comment by lvarnava** [comment]
I agree, the client acts in this case correctly

**Comment by jospoortvliet** [comment]
Fixed in https://github.com/nextcloud/server/pull/18385
