### ISSUE TITLE
Error with PHP7.2

### ISSUE THREAD

**Issue by Slam2** [nextcloud/server#6786]
Hi !

Nextcloud are not compatible with PHP7.2. I've a error when installing from scratch : 
`2017/10/08 20:28:15 [error] 30740#30740: *4876 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot use result of built-in function in write context in /home/www-cloud/3rdparty/pear/archive_tar/Archive/Tar.php on line 639" while reading response header from upstream, client: 5.49.x.x, server: cloud.fqdn.net, request: "POST /index.php HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "cloud.fqdn.net"`

Thanks !

**Comment by rullzer** [comment]
What version of nextcloud are you running?

**Comment by nickvergessen** [comment]
Yeah, our current stable release does not support php 7.2:
https://github.com/nextcloud/server/blob/stable12/index.php#L36-L42

But support should come with Nextcloud 13
