### ISSUE TITLE
Nextcloud encryption, protection from server compromise

### ISSUE THREAD

**Issue by amocrenco** [nextcloud/server#6789]
Seems that this statement from Nextcloud 12 documentation

> The encryption app does not protect your data if your Nextcloud server is compromised, and **it does not prevent Nextcloud administrators from reading user’s files**.
> 
> *https://docs.nextcloud.com/server/12/admin_manual/configuration_files/encryption_configuration.html, warning section*

contradicts this statement from the same page

> If you lose your Nextcloud password, then you lose access to your encrypted files. If one of your users loses their Nextcloud password their files are **unrecoverable**. You cannot reset their password in the normal way; you’ll see a yellow banner warning “Please provide an admin recovery password, otherwise all user data will be lost”.
>
> *https://docs.nextcloud.com/server/12/admin_manual/configuration_files/encryption_configuration.html#enabling-users-file-recovery-keys*

If I understand it correctly, the math is the following:

#### Encryption (authentication is omitted)

`E(p, k1, k2)` results in `c`

#### Decryption (integrity checks are omitted)

`D(c, k1 or k2)` results in `p`

##### Where

E - encryption function (AES-256 is used)
D - decryption function
k1 - key derived from user password
k2 - recovery key
c - ciphertext
p - plaintext

### My question

If I backup & delete k2 from server, the following statement 

> The encryption app does not protect your data if your Nextcloud server is compromised, and **it does not prevent Nextcloud administrators from reading user’s files**.
> 
> *https://docs.nextcloud.com/server/12/admin_manual/configuration_files/encryption_configuration.html, warning section*

becomes false. 

Everything will continue to function correctly (encryption, decryption, plaintext authentication, integrity checks, sharing, etc.), and files **will be secure in case of server compromise**.

If it is true, than I'd suggest correcting the documentation.

### Context

I am investigating self-hosted file cloud options for my organization.

**Comment by rullzer** [comment]
The issue with server side encryption is that the key is stored on the server. Even if the key is protected with a password the server still has access to it the server does the encrypting and decrypting of the files.

So a rouge sysadmin could just modify the code to write the plain text key somewhere to be able to access all your data. And you would have no idea.

Of course if you are a good sysadmin and don't do this. If a users loses the password to their key (and there is no recovery key) then the files will not be accessible.

I hope this explain it a bit more.

**Comment by amocrenco** [comment]
What I discovered by exploring the source code:

## Encryption in NextCloud

### Terms

k1 - user private key
k2 - user public key
k3 - recovery private key
k4 - recovery public key
E - encryption function
D - decryption function
p - plaintext
c - ciphertext
pass1 - user password
pass2 - recovery password
derivedpass1 = pbkdf2 sha256 derived pass1
derivedpass2 = pbkdf2 sha256 derived pass2

### Encryption

User files are encrypted with RSA.

E(p, k2, k4) = c

* k1 is AES-256 encrypted with derivedpass1
* k3 is AES-256 encrypted with derivedpass2

Data integrity is ensured HMAC-SHA256

k1 and k2 are created on user first login if home dir encryption is enabled in Nextcloud.

### Decryption

User files are encrypted with RSA.

D(c, k1, k3) = p

* k1 is stored on server AES-256 encrypted
* k3 is stored on server AES-256 encrypted

Only by knowing pass1/pass2 an attacker can decrypt the `c`.

pass1 is only stored in a hashed form.

pass2 is not stored at server side at all.

Therefore compromise of the server files/keys will not lead to files compromise.

**Comment by rullzer** [comment]
Yes the password is not stored. but is still presented to the server on login. If you have a sysadmin with bad intentions there is nothing stopping them from logging your password.

**Comment by amocrenco** [comment]
> If you have a sysadmin with bad intentions

Its not relevant for organizations, where we have file integrity checks, IDS/IPS in place. As an organization we are really concerned about ciphertext/keys/server compromise. We will be able to detect changes to nextcloud source code / ssh logins / commands executed / intrusions / etc. Given the current scheme, nextcloud provides enough confidentiality to state that "**server compromise does not lead to files compromise**".
