### ISSUE TITLE
No possibility to upload images to publicly shared gallery with upload enabled

### ISSUE THREAD

**Issue by mimi89999** [nextcloud/server#6794]
### Steps to reproduce
1. Create a folder and put in it images. Share it enabling upload.
2. Logout and open the shared link. Change view to gallery from files view. 
3. Notice the upload button in gallery view missing. Users are unaware that they need to change to files view before being able to upload. They think it is not possible to upload images.

### Expected behaviour
There should also be an upload button in gallery view.

### Actual behaviour
The upload button in gallery is missing.

### Server configuration

Not sure if it is a bug or missing feature. If I get feedback that it is a bug on my side, I will add my config info to the issue.

**Comment by nickvergessen** [comment]
Please report to the gallery app repository:
https://github.com/nextcloud/gallery

**Comment by mimi89999** [comment]
Sorry.

**Comment by nickvergessen** [comment]
No problem at all :slightly_smiling_face:

**Comment by mimi89999** [comment]
Issue does already exist: https://github.com/nextcloud/gallery/issues/54

(adding for reference for other people like me who don't know where to report...)
