### ISSUE TITLE
Versions doesn't remove old file versions as documented

### ISSUE THREAD

**Issue by fireba11** [nextcloud/server#6797]
### Steps to reproduce
1. set something like 'versions_retention_obligation' => 'auto,90',
2. have a (rather large in relation to quota) file updated regularly
3. watch user folder size in the filesystem

### Expected behaviour
As documented at https://docs.nextcloud.com/server/12/admin_manual/configuration_files/file_versioning.html if over 50% of user quota not used for the current versions (documentation may need some clarification there ..) delete versions from oldest to newest untill under 50% of "free" quota space.

### Actual behaviour
As my monitoring of the size of user data folders shows clearly once cleanup is triggered it seems to remove ALL old versions.
Note: That user account only has a single file.

### Server configuration

**Operating system**:
debian 9.1
**Web server:**
apach2
**Database:**
mariadb
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
12.0.3.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
yes, lots. startion from ownCloud 6.0 :-D
**Where did you install Nextcloud from:**
**List of activated apps:**
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - calendar: 1.5.5
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by nickvergessen** [comment]
Duplicate of https://github.com/nextcloud/server/issues/6731

**Comment by fireba11** [comment]
Please reopen since it is clearly **not** a duplicate, thanks.

**Comment by fireba11** [comment]
Issue is stll happening in 13.0.4
