### ISSUE TITLE
»Redirecting« view in auth flow is a bit broken

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#6798]
This is the »Redirecting …« part of the auth flow, it seems a bit broken without logo and improper positioning:
![screenshot_2017-10-03-21-30-23](https://user-images.githubusercontent.com/925062/31355800-f8910116-ad3b-11e7-82a9-dd7c4b0dd58b.png)

The template seems fine. Any idea what could cause this?

**Comment by rullzer** [comment]
I think this is fixed already in master... 

![4](https://user-images.githubusercontent.com/45821/38442179-c58d56aa-39e7-11e8-838a-2e77a3014398.png)
