### ISSUE TITLE
[SECURITY] Two Accounts Suddenly got Merged, Critical Security Breach

### ISSUE THREAD

**Issue by madorian** [nextcloud/server#6800]
The worst thing happened today.

I received a call from a client that suddenly found files from another user in his sync directory. When I logged into the server these directories were not there.

I then looked at the other users account and both in the web console and in the users sync directory, I found all the files and directories of the first user.

These two people have not shared any files with eachother and not transferred the files or directories to eachother; they don’t even know how to do that.

How can this possibly happen? This is like the most serious breach of security I’ve ever seen. They don’t even have eachothers passwords.

Has anyone seen anything like this?

This is a hosted Nextcloud server. It's updated now to latest version, but I believe it ran version 11 when this occured yesterday. I will confirm this and report back. 

I will get as many logs as I can and update this ticket as we go along, but I just need to start somewhere, cause I'm mighty confused now. 

First of all, I would like to just start somewhere and I start with a directory called "FOOBAR" in USER0 sync directory. This FOOBAR directory belongs to USER1 and has not been shared to USER0. Now, is there a log that can show me when and how this directory appeared in USER0 directory?

**Comment by nickvergessen** [comment]
Please provide more info:
1. Which user backend are you using
2. Which exact version of Nextcloud was running
3. Do you use external storage backends

**Comment by madorian** [comment]
1. what is user backend?
2. it's just been upgraded to 12.0.3, but it seems the problem is still alive
3. there are no external storage backends. 

Today I saw this message in the client log: 

||12 Monkeys TV Series Indtro.mp3|INST_NEW|Up|1463765339||273481||6|Fortsett svartelisting: Error transferring https://cloud.leet.as/remote.php/dav/files/bar/12 Monkeys TV Series Indtro.mp3 - server replied: Forbidden (Permission 
denied to create file (filename 12 Monkeys TV Series Indtro.mp3))|403|0|0|||INST_NONE|

I'm logged in as user "foo" and apparently it's trying to write to user "bar". 

How in the world can this happen? 

There are no suspicious log entries when I log in as admin and view the log. 

Many of my users has also reported the message that goes along the lines of "all files were deleted on the server; click to keep them". When I log into their account, nothing has happened on the server and no log entries. 

This is just crazy; how can I figure out what's going on?

**Comment by madorian** [comment]
so, the nextcloud client is trying to write into another users directory on the server. Fortunately it was stopped by some permissions, but in the original report, I reported that it actually managed to write into another users directory. I had to clean out files on the other users sync directory. What's even more alarming was that the files didn't exist on the server itself.
