### ISSUE TITLE
No error message when trying to save a locked document from a SMB external storage with Collabora Online

### ISSUE THREAD

**Issue by fifh** [nextcloud/server#6804]
### Steps to reproduce

SMB external storage needed

1. User A opens the document test.odt directly on the windows server or from a network drive or from a UNC path, with LibreOffice. 
a `.~lock.test.odt#` file is created in the same folder.
2. User B opens the same document with Collabora Online from a SMB external storage in Nextcloud, whatever the type of authentication used
3. User B modifies the document and save it (the document is still open by user A with LibreOffice)

### Expected behaviour

User B should receive a error message because the document is locked on the server and B can't save it

### Actual behaviour

B can save the document and exit Collabora Online without any warning, but all the modifications made by B will be lost.

The admin_audit app logs "File updated" and then "File written", which is false.

Not sure if it's a Collabora Online or Nextcloud bug, but as Nextcloud manages the storage, I think that Nextcloud should do the job.

### General server configuration

**Operating system:** Linux 3.10.0-514.6.2.el7.x86_64 #1 SMP Thu Feb 23 03:04:39 UTC 2017 x86_64

**Web server:** Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 PHP/7.1.5 (fpm-fcgi)

**Database:** mysql 5.5.52

**PHP version:** 7.1.5

**LibreOffice Online version:** Collabora Online 2.1.3

**Windows server:** Windows server 2012 R2

<details>
        <summary>PHP-modules loaded</summary>

 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - cgi-fcgi
 - bz2
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - iconv
 - intl
 - json
 - ldap
 - exif
 - mcrypt
 - mysqlnd
 - PDO
 - apcu
 - posix
 - shmop
 - SimpleXML
 - sockets
 - sqlite3
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - xml
 - xmlwriter
 - xsl
 - mysqli
 - pdo_mysql
 - pdo_sqlite
 - wddx
 - xmlreader
 - apc
 - zip
 - Phar
 - Zend OPcache
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.2 - 12.0.2.0

**Updated from an older Nextcloud/ownCloud or fresh install:** regularly updated since ownCloud 8

**Where did you install Nextcloud from:**  
tar.gz from web site

**Are you using external storage, if yes which one:** 
    [0] => \OC\Files\Storage\Local
    [10] => \OCA\Files_External\Lib\Storage\SMB

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** 
OpenLdap + Active Directory

**Signing status**
No errors have been found.

<details>
        <summary>Enabled apps</summary>

 - activity: 2.5.2
 - admin_audit: 1.2.0
 - admin_notifications: 1.0.0
 - announcementcenter: 3.1.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.5
 - circles: 0.12.4
 - comments: 1.2.0
 - contacts: 2.0.1
 - dashboard: 4.0.5
 - dav: 1.3.0
 - deck: 0.2.4
 - external: 2.0.3
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_accesscontrol: 1.2.5
 - files_automatedtagging: 1.2.2
 - files_clipboard: 0.6.4
 - files_downloadactivity: 1.1.1
 - files_external: 1.3.0
 - files_pdfviewer: 1.1.1
 - files_retention: 1.1.2
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - groupfolders: 1.1.0
 - impersonate: 1.0.1
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - news: 11.0.5
 - nextant: 1.0.8
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - piwik: 0.3.1
 - provisioning_api: 1.2.0
 - quota_warning: 1.1.0
 - richdocuments: 1.12.35
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_email: 1.0.1
 - spreed: 2.0.1
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - user_ldap: 1.2.1
 - workflowengine: 1.2.0
 - zimbradrive: 0.8.15
</details>

<details>
        <summary>Disabled apps</summary>

 - encryption
 - user_external
 - user_saml
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "debug": true,
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "test.arawa.fr",
    ],
    "datadirectory": "\/var\/www\/html\/nextcloud\/data",
    "overwrite.cli.url": "https:\/\/test.arawa.fr",
    "dbtype": "mysql",
    "version": "12.0.2.0",
    "dbname": "owncloud",
    "dbhost": "localhost",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Paris",
    "loglevel": 1,
    "log_rotate_size": 10485760,
    "log_rotate_sizerotation": 10485760,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "session_keepalive": true,
    "installed": true,
    "appstore.experimental.enabled": true,
    "ldapIgnoreNamingRules": false,
    "theme": "",
    "maintenance": false,
    "activity_expire_days": 100,
    "trashbin_retention_obligation": "auto,20",
    "versions_retention_obligation": "auto,20",
    "htaccess.RewriteBase": "\/",
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "contact",
    "mail_domain": "hemmel.fr",
    "mail_smtpauth": 1,
    "mail_smtphost": "ssl0.ovh.net",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "skeletondirectory": "",
    "ldapUserCleanupInterval": 5,
    "log_query": true,
    "mysql.utf8mb4": true,
    "user_backends": [
        {
            "class": "OCA\\ZimbraDrive\\Auth\\ZimbraUsersBackend",
            "arguments": []
        }
    ]
}
```
</details>

<details>
        <summary>LDAP config s00</summary>

```
- hasMemberOfFilterSupport
- hasPagedResultSupport
- homeFolderNamingRule
- lastJpegPhotoLookup           : 0
- ldapAgentName                 : ***
- ldapAgentPassword             : ***
- ldapAttributesForGroupSearch
- ldapAttributesForUserSearch   : displayName;mail
- ldapBackupHost
- ldapBackupPort
- ldapBase                      : dc=arawa,dc=fr
- ldapBaseGroups                : dc=arawa,dc=fr
- ldapBaseUsers                 : dc=arawa,dc=fr
- ldapCacheTTL                  : 600
- ldapConfigurationActive       : 1
- ldapDefaultPPolicyDN
- ldapDynamicGroupMemberURL
- ldapEmailAttribute            : mail
- ldapExperiencedAdmin          : 0
- ldapExpertUUIDGroupAttr
- ldapExpertUUIDUserAttr
- ldapExpertUsernameAttr        : uid
- ldapGidNumber                 : gidNumber
- ldapGroupDisplayName          : cn
- ldapGroupFilter               : (&(|(objectclass=posixGroup)))
- ldapGroupFilterGroups
- ldapGroupFilterMode           : 0
- ldapGroupFilterObjectclass    : posixGroup
- ldapGroupMemberAssocAttr      : memberUid
- ldapHost                      : ***
- ldapIgnoreNamingRules
- ldapLoginFilter               : (&(|(objectclass=inetOrgPerson))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))
- ldapLoginFilterAttributes
- ldapLoginFilterEmail          : 1
- ldapLoginFilterMode           : 0
- ldapLoginFilterUsername       : 1
- ldapNestedGroups              : 0
- ldapOverrideMainServer
- ldapPagingSize                : 500
- ldapPort                      : 389
- ldapQuotaAttribute            : quota
- ldapQuotaDefault              : 500 MB
- ldapTLS                       : 0
- ldapUserDisplayName           : displayName
- ldapUserDisplayName2
- ldapUserFilter                : (|(objectclass=inetOrgPerson))
- ldapUserFilterGroups
- ldapUserFilterMode            : 0
- ldapUserFilterObjectclass     : inetOrgPerson
- ldapUuidGroupAttribute        : auto
- ldapUuidUserAttribute         : auto
- turnOffCertCheck              : 0
- turnOnPasswordChange          : 0
- useMemberOfToDetectMembership : 1
```
</details>

<details>
        <summary>LDAP config s01 : AD</summary>

```
- hasMemberOfFilterSupport      : 1
- hasPagedResultSupport
- homeFolderNamingRule
- lastJpegPhotoLookup           : 0
- ldapAgentName                 : ***
- ldapAgentPassword             : ***
- ldapAttributesForGroupSearch
- ldapAttributesForUserSearch   : displayName;mail;cn
- ldapBackupHost
- ldapBackupPort
- ldapBase                      : OU=arawa,DC=ad,DC=arawa,DC=fr
- ldapBaseGroups                : OU=Groups,OU=arawa,DC=ad,DC=arawa,DC=fr
- ldapBaseUsers                 : OU=Users,OU=arawa,DC=ad,DC=arawa,DC=fr
- ldapCacheTTL                  : 30
- ldapConfigurationActive       : 1
- ldapDefaultPPolicyDN
- ldapDynamicGroupMemberURL
- ldapEmailAttribute            : mail
- ldapExperiencedAdmin          : 0
- ldapExpertUUIDGroupAttr
- ldapExpertUUIDUserAttr        : sAMAccountname
- ldapExpertUsernameAttr        : sAMAccountname
- ldapGidNumber                 : gidNumber
- ldapGroupDisplayName          : cn
- ldapGroupFilter               : (&(|(objectclass=group)))
- ldapGroupFilterGroups
- ldapGroupFilterMode           : 0
- ldapGroupFilterObjectclass    : group
- ldapGroupMemberAssocAttr      : member
- ldapHost                      : ***
- ldapIgnoreNamingRules
- ldapLoginFilter               : (&(|(objectclass=person))(samaccountname=%uid))
- ldapLoginFilterAttributes
- ldapLoginFilterEmail          : 0
- ldapLoginFilterMode           : 0
- ldapLoginFilterUsername       : 1
- ldapNestedGroups              : 0
- ldapOverrideMainServer
- ldapPagingSize                : 500
- ldapPort                      : 389
- ldapQuotaAttribute
- ldapQuotaDefault              : 500 MB
- ldapTLS                       : 0
- ldapUserDisplayName           : displayName
- ldapUserDisplayName2
- ldapUserFilter                : (&(|(objectclass=person)))
- ldapUserFilterGroups
- ldapUserFilterMode            : 0
- ldapUserFilterObjectclass     : person
- ldapUuidGroupAttribute        : auto
- ldapUuidUserAttribute         : auto
- turnOffCertCheck              : 0
- turnOnPasswordChange          : 0
- useMemberOfToDetectMembership : 1
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0

**Operating system:** Linux (Kubuntu 17.04, Mint), Windows 10

### Logs

<details>
        <summary>Web server error log</summary>

nothing

</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
{"reqId":"WdyMy-JyOubFXdazjyc@xwAAAFI","level":1,"time":"2017-10-10T11:03:09+02:00","remoteAddr":"149.202.187.248","user":"pbernard","app":"admin_audit","method":"POST","url":"\/apps\/richdocuments\/wopi\/files\/47094_ocisk9esiwsh\/contents?access_token=arhLGRFj5r7zOydd151ofpskB0sSiugd&access_token_ttl=0&permission=edit","message":"File updated: \"\/projet_GesFin\/specifications\/test.odt\"","userAgent":"--","version":"12.0.2.0"}
{"reqId":"WdyMy-JyOubFXdazjyc@xwAAAFI","level":1,"time":"2017-10-10T11:03:09+02:00","remoteAddr":"149.202.187.248","user":"pbernard","app":"admin_audit","method":"POST","url":"\/apps\/richdocuments\/wopi\/files\/47094_ocisk9esiwsh\/contents?access_token=arhLGRFj5r7zOydd151ofpskB0sSiugd&access_token_ttl=0&permission=edit","message":"File written to: \"\/projet_GesFin\/specifications\/test.odt\"","userAgent":"--","version":"12.0.2.0"}
```
</details>

<details>
        <summary>Browser log</summary>

Nothing in particular

</details>

**Comment by blizzz** [comment]
@icewind1991

**Comment by fifh** [comment]
I have a test platform where we can reproduce this bug. If someone is interested I could create an account on this platform to test or debug

**Comment by blizzz** [comment]
Or perhaps this is rather related to richdocuments, @timar ?

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
