### ISSUE TITLE
Password Reset is not user friendly

### ISSUE THREAD

**Issue by ccoenen** [nextcloud/server#6808]
The way to reset your password is not user friendly. I just added 20 users to my instance, and had the people reset their passwords. Suffice it to say this did not go well.

One of the biggest problems is this "button"

![password reset](https://user-images.githubusercontent.com/124909/31432335-a723de8e-ae76-11e7-9c52-2277e87aca83.png)

It is not understood as a button or link. People see this message, but they do not think they could click it.
-> **It needs to be distinguishable as something that can be done**

Also, people who _know_ they forgot their password don't ever reach this message. Normal people don't entertain the idea of _intentionally_ giving a bad password, just to _possibly_ reset their passwords.
-> **Nextcloud needs an explicit "forgot your password?" link**

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by ccoenen** [comment]
could somebody post a screenshot of how it looks after that pull request?

**Comment by skjnldsv** [comment]
@ccoenen It's more like a flow... A screenshot won't really gives that much of credit to this pr! :/

**Comment by ccoenen** [comment]
The point is: from what I can tell in that PR, I'm not sure if this ticket is really fully resolved. And as it's probably only ever going to the next major release, I'm not very happy to wait until NC14 until it's fully resolved.

**Comment by skjnldsv** [comment]
@ccoenen Please feel free to test it yourself and provide a pr if this doesn't fit your need. :)

**Comment by MorrisJobke** [comment]
The "forgot password" link is below the input now:

<img width="967" alt="bildschirmfoto 2017-11-14 um 18 41 49" src="https://user-images.githubusercontent.com/245432/32795294-8d07a12e-c96b-11e7-9ddb-7ab83243d972.png">

The remaining steps are just polished a bit.

**Comment by ccoenen** [comment]
Thanks!
