### ISSUE TITLE
Disabled Users not visible

### ISSUE THREAD

**Issue by ajeoc** [nextcloud/server#6809]
### Steps to reproduce
1. Log in as Admin
2. Go to Users and Disable an existing User (or create a new User to Test this)
3. On the left pane select the Group "Disabled"
![2017-10-11 11_57_27-oc_disabledusers-notvisible](https://user-images.githubusercontent.com/15652395/31434125-c40fd8c2-ae7b-11e7-8074-67ee47084528.png)

### Expected behaviour
The Group "Disabled" should list disabled User Accounts

### Actual behaviour
The Group "Disabled" doesn't list the disabled Users. The amount (number) of disabled Users is visible.

### Server configuration

**Operating system**: CentOS Linux release 7.4.1708 (Core)

**Web server:** Apache/2.4.6 (CentOS)

**Database:** 5.5.56-MariaDB MariaDB Server

**PHP version:** PHP 5.6.31

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
oC8.0 --> oC8.1 --> oC8.2 --> oC9.0 --> nC9.0 --> nC10.0 --> nC11.0 --> nC12.0 

**Where did you install Nextcloud from:**

**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - encryption
  - files_external
  - firstrunwizard
  - gallery
  - theming
  - user_external
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "ocnibw9w9uqp",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "192.168.200.15",
                    ],
        "datadirectory": "\/home\/share\/data",
        "overwrite.cli.url": "http:\/\/localhost\/owncloud",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "share",
        "mail_domain": "xxx",
        "mail_smtphost": "192.168.200.14",
        "mail_smtpport": "25",
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "loglevel": 2,
        "default_language": "en",
        "allow_user_to_change_display_name": false,
        "updatechecker": false,
        "check_for_working_htaccess": true,
        "logtimezone": "Europe\/Zurich",
        "maintenance": false,
        "theme": "cst",
        "singleuser": false,
        "trashbin_retention_obligation": "30, 31",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** IE 11, Firefox 56

**Operating system:** Windows 7

#### Browser log

Note:
Somehow related to Issue #6217 but less steps to reproduce
Re-enabling disabled users with OCC command works

**Comment by nickvergessen** [comment]
Works fine here with a full admin.

Can you try a hard refresh too?

**Comment by ajeoc** [comment]
How to "hard refresh"? Thanks

**Comment by nickvergessen** [comment]
Ctrl + F5

But when it is still the case after reopening the browser then it might be a different story.

**Comment by ajeoc** [comment]
Doesn't help.
You remember this one https://github.com/owncloud/core/issues/20303#issuecomment-154354167 ?
Could it be related???
The disabled Users are called test, testuser, testuser2
In the Database, in which Table should Disabled be? Can't find it when doing: select * from oc_groups

**Comment by nickvergessen** [comment]
Well it uses a fake group and then loops over all users and filters them manually:
https://github.com/nextcloud/server/blob/5a257cec634fd04a628ef1cfba6fe0ee6a14216c/settings/Controller/UsersController.php#L305-L318

**Comment by hubertbanas** [comment]
Is there any updates on this issue?

**Comment by ajeoc** [comment]
From my side no. I still experience this issue on my productive platform.

**Comment by hubertbanas** [comment]
Yeah, I experience this bug here as well.

**Comment by supremesyntax** [comment]
Also here with NC 12.0.3 (Updated from 11.0.5)

**Comment by MattyShires** [comment]
Same issue on 12.0.4, using an LDAP back-end for users, all users and groups are correctly detected but will not show up in the disabled users list if they are disabled, running the "occ user:enable {username}" will make them visible again.

**Comment by michag86** [comment]
I think this #7292 can fix the problem. I've tested this on 12.0.4 successfully. Not shure if this also works with ldap back end.

**Comment by MorrisJobke** [comment]
Fixed by #7292 in 13 and will be fixed in 12.0.6 with #8006

**Comment by mathias-b** [comment]
Hello,

I have exactly the same issue but with Nginx, PHP-FPM and MariaDB. This doesn't generate logs and I really don't know where to look to debug.

I upgraded to v13 and the problem still occur.

Thanks in advance,

**Comment by mathias-b** [comment]
@michag86 as full admin.

**Comment by ajeoc** [comment]
I can confirm it's fixed in nC13 and nC12.0.5 Build:2018-02-28T01:02:27+00:00 (nC12.0.6 will fix this too) for the Group Admin. Disabled Users are listed now.
But for the Full Admin the Category Disabled still shows no Users.
So this is not fixed!

**Comment by michag86** [comment]
Hmmm. I cannot confirm this. Tested with NC13 and NC 12.0.5 (Fix from 12.0.6 applied).
If you use the developer mode from the browser, what is the response from:
``[nextcloudurl]/settings/users/users?offset=0&limit=50&gid=_disabledUsers&pattern=``  ?

Normally this should look like this:
``[{"name":"testuser","displayname":"testuser","groups":["Test-Group"],"subadmin":[],"quota":"5 GB","quota_bytes":5368709120,"storageLocation":"\/var\/www\/htdocs\/nextcloudrootdir\/data\/testuser","lastLogin":0,"backend":"Database","email":"","isRestoreDisabled":false,"isAvatarAvailable":true,"isEnabled":false,"size":0}]``
@ajeoc @mathias-b

**Comment by ajeoc** [comment]
I don't have anything related there:
![2018-03-02 17_21_27-users](https://user-images.githubusercontent.com/15652395/36910640-94432654-1e41-11e8-8238-22599e30a3a9.png)

**Comment by michag86** [comment]
Can you switch to network and click on Disabled again? There should be such a request.

**Comment by ajeoc** [comment]
![2018-03-05 10_22_23-users](https://user-images.githubusercontent.com/15652395/36967308-a6bfd708-205f-11e8-8c8c-370b0f326211.png)

**Comment by michag86** [comment]
The response in the right side would be interesting.

**Comment by ajeoc** [comment]
See here:
![2018-03-05 14_51_44-users](https://user-images.githubusercontent.com/15652395/36978535-0749737a-2085-11e8-9c6e-c000a15316ca.png)

Thank you

**Comment by ajeoc** [comment]
@MorrisJobke 
It's not fixed. Can you reopen?

**Comment by MorrisJobke** [comment]
> It's not fixed. Can you reopen?

The issue in here is fixed. You seem to have a different cause and should be a separate ticket. Please also fill out the issue template when opening the new ticket.
