### ISSUE TITLE
TypeError: Argument 2 passed to OCA\Files_Sharing\Controller\ShareController::fileListDownloaded() must be of the type array, integer given, called in /var/www/nextcloud/apps/files_sharing/lib/Controller/ShareController.php on line 490

### ISSUE THREAD

**Issue by TimoPax** [nextcloud/server#6820]
Hi,

under the following circumstances I'm receiving the following error:

TypeError: Argument 2 passed to OCA\Files_Sharing\Controller\ShareController::fileListDownloaded() must be of the type array, integer given, called in /var/www/nextcloud/apps/files_sharing/lib/Controller/ShareController.php on line 490

###Sets to reproduce
1. Create a new folder, e.g. "test"
2. Share this folder via link
3. Below the folder "test", create a subfolder with only numbers, e.g. "20171012"
4. Put a few files within the subfolder, e.g. 4 files
5. Logout and enter the link for step 2. into your browser (you should see the subfolder 20171012 now)
6. Click at the subfolder 20171012
7. Select all 4 files
8. Click "Download" (Note: Not the download button on within the header (that one works), but the download button on top of the filelist (where the filesize is behind the button).

More comments:
- If the subfolder includes a character, the error doesn't occur
- If you select not all files, e.g. just 3 out of 4 the error doesn't occur

### Expected behaviour
Download the selected files

### Actual behaviour
"Internal Server Error
The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log."

### Server configuration
- Nextcloud 11.0.5
- Apache 2.4.25
- Debian
- PHP 7.0.19
- mysql 10.1.22
- Started with a fresh install of 11.0.2->11.0.3->11.0.4->11.0.5

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - activitylog: 0.0.1
  - bookmarks: 0.10.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - files: 1.6.1
  - files_downloadactivity: 1.0.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notes: 2.3.1
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1

**Nextcloud configuration:**
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/nextclouddata\/",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "11.0.5.1",
        "dbname": "NextCloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "production"
    }

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Tried with Firefox, IE, Edge

**Operating system:**
Windows 10

#### Web server error log
No errors

#### Nextcloud log (data/nextcloud.log)
--> log file is empty.
Log for nextcloud web frontend:
TypeError: Argument 2 passed to OCA\Files_Sharing\Controller\ShareController::fileListDownloaded() must be of the type array, integer given, called in /var/www/nextcloud/apps/files_sharing/lib/Controller/ShareController.php on line 490

**Comment by blizzz** [comment]
@rullzer @schiessle

**Comment by rullzer** [comment]
O my bet is that this is some js parsing magic... I'll take a look later

**Comment by rullzer** [comment]
PR with a fix in #7016
