### ISSUE TITLE
moving shared directories on masterkey encrypted setup.

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#6827]
This issue is only on encrypted systems an issue

1. Try to move directory from one shared sub directory to another
2. Task fails

### Expected behaviour
Directory successfully moved.

### Actual behaviour

> {"reqId":"oXaSbKuf2oLHihJpV5aW","level":3,"time":"2017-10-13T13:00:58+02:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"user","app":"PHP","method":"POST","url":"\/index.php\/apps\/files_clipboard\/ajax\/clipboard.php","message":"fclose() expects parameter 1 to be resource, string given at \/var\/www\/filecloud.domain.net\/htdocs\/lib\/private\/Files\/Storage\/Wrapper\/Encryption.php#750","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.13; rv:56.0) Gecko\/20100101 Firefox\/56.0","version":"12.0.2.0"}
> {"reqId":"oXaSbKuf2oLHihJpV5aW","level":3,"time":"2017-10-13T13:00:58+02:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"user","app":"index","method":"POST","url":"\/index.php\/apps\/files_clipboard\/ajax\/clipboard.php","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\\\/user\\\/files\\\/Photos\\\/Abuse\\\/Anfragen\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/filecloud.domain.net\\\/htdocs\\\/lib\\\/private\\\/Files\\\/Node\\\/Folder.php(133): OC\\\\Files\\\\Node\\\\Root->get('\\\/user\\\/files\\\/P...')\\n#1 \\\/var\\\/www\\\/filecloud.domain.net\\\/htdocs\\\/lib\\\/private\\\/Encryption\\\/File.php(90): OC\\\\Files\\\\Node\\\\Folder->get('\\\/Photos\\\/Abuse\\\/A...')\\n#2 \\\/var\\\/www\\\/filecloud.domain.net\\\/htdocs\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(257): OC\\\\Encryption\\\\File->getAccessList('\\\/user\\\/files\\\/P...')\\n#3 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_open('ocencryption:\\\/\\\/', 'w', 0, NULL)\\n#4 \\\/var\\\/www\\\/filecloud.domain.net\\\/htdocs\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(198): fopen('ocencryption:\\\/\\\/', 'w', false, Resource id #75)\\n#5 \\\/var\\\/www\\\/filecloud.domain.net\\\/htdocs\\\/lib\\\/private\\\/Files\\\/Stream\\\/Encryption.php(180): OC\\\\Files\\\\Stream\\\\Encryption::wrapSource(Resource id #74, Resource id #75, 'ocencryption', 'OC\\\\\\\\Files\\\\\\\\Stream...', 'w')\\n#6 \\\/var\\\/www\\\/filecloud.domain.net\\\/htdocs\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(461): OC\\\\Files\\\\Stream\\\\Encryption::wrap(Resource id #74, 'files\\\/Photos\\\/Ab...', '\\\/user\\\/files\\\/P...', Array, 'user', Object(OCA\\\\Encryption\\\\Crypto\\\\Encryption), Object(OC\\\\Files\\\\Storage\\\\Home), Object(OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption), Object(OC\\\\Encryption\\\\Util), Object(OC\\\\Encryption\\\\File), 'w', 0, 0, 0, true)\\n#7 \\\/var\\\/www\\\/filecloud.domain.net\\\/htdocs\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(744): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->fopen('files\\\/Photos\\\/Ab...', 'w')\\n#8 \\\/var\\\/www\\\/filecloud.domain.net\\\/htdocs\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(642): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->copyBetweenStorage(Object(OCA\\\\Files_Sharing\\\\SharedStorage), 'Abuse\\\/Anfragen\\\/...', 'files\\\/Photos\\\/Ab...', false, false)\\n#9 \\\/var\\\/www\\\/filecloud.domain.net\\\/htdocs\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(737): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->copyFromStorage(Object(OCA\\\\Files_Sharing\\\\SharedStorage), 'Abuse\\\/Anfragen\\\/...', 'files\\\/Photos\\\/Ab...', false, false)\\n#10 \\\/var\\\/www\\\/filecloud.domain.net\\\/htdocs\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(642): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->copyBetweenStorage(Object(OCA\\\\Files_Sharing\\\\SharedStorage), 'Abuse\\\/Anfragen', 'files\\\/Photos\\\/Ab...', false, false)\\n#11 \\\/var\\\/www\\\/filecloud.domain.net\\\/htdocs\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(737): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->copyFromStorage(Object(OCA\\\\Files_Sharing\\\\SharedStorage), 'Abuse\\\/Anfragen', 'files\\\/Photos\\\/Ab...', false, false)\\n#12 \\\/var\\\/www\\\/filecloud.domain.net\\\/htdocs\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(642): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->copyBetweenStorage(Object(OCA\\\\Files_Sharing\\\\SharedStorage), 'Abuse', 'files\\\/Photos\\\/Ab...', false, false)\\n#13 \\\/var\\\/www\\\/filecloud.domain.net\\\/htdocs\\\/lib\\\/private\\\/Files\\\/View.php(909): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->copyFromStorage(Object(OCA\\\\Files_Sharing\\\\SharedStorage), 'Abuse', 'files\\\/Photos\\\/Ab...')\\n#14 \\\/var\\\/www\\\/filecloud.domain.net\\\/htdocs\\\/apps\\\/files_clipboard\\\/ajax\\\/clipboard.php(48): OC\\\\Files\\\\View->copy('\\\/user\\\/files\\\/s...', '\\\/user\\\/files\\\/P...')\\n#15 \\\/var\\\/www\\\/filecloud.domain.net\\\/htdocs\\\/lib\\\/private\\\/Route\\\/Route.php(155) : runtime-created function(1): require_once('\\\/var\\\/www\\\/filecl...')\\n#16 [internal function]: __lambda_func(NULL)\\n#17 \\\/var\\\/www\\\/filecloud.domain.net\\\/htdocs\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func('\\\\x00lambda_519', Array)\\n#18 \\\/var\\\/www\\\/filecloud.domain.net\\\/htdocs\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_cli...')\\n#19 \\\/var\\\/www\\\/filecloud.domain.net\\\/htdocs\\\/index.php(48): OC::handleRequest()\\n#20 {main}\",\"File\":\"\\\/var\\\/www\\\/filecloud.domain.net\\\/htdocs\\\/lib\\\/private\\\/Files\\\/Node\\\/Root.php\",\"Line\":200}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.13; rv:56.0) Gecko\/20100101 Firefox\/56.0","version":"12.0.2.0"}

### Server configuration
12.0.2

**Operating system**:
Linux

**Web server:**
Apache-2.4

**Database:**
Maria

**PHP version:**
7.1

**Nextcloud version:** (see Nextcloud admin page)
12.0.2

I guess this is a known limitation?

thanks and cheers

**Comment by nickvergessen** [comment]
@schiessle can you have a look?

**Comment by schiessle** [comment]
can't reproduce it. Feel free to re-open if this is still an issue with the latest version of Nextcloud
