### ISSUE TITLE
NC12, pdf.js "invalid top-level pages dictionary"

### ISSUE THREAD

**Issue by BurtGummer** [nextcloud/server#6828]
Hello,

i have many pdf files, nextcloud can't open:

![image](https://user-images.githubusercontent.com/1249295/31546465-bbe6f884-b023-11e7-9812-9b01cbec5194.png)

Other (pdf) files are ok (for example, if i create one with Word 2013). "PDF Creator" was "Nuance PDF Create". If i open the pdf's with the browser or a reader everything works. But NextCloud 12.0.3 shows the error. 

There are no errors in the nextcloud.log if i open such a pfd.

Any ideas?

Because the pdf is not copyfree i cant upload a file.

**Comment by nickvergessen** [comment]
Please report your issue to https://github.com/nextcloud/files_pdfviewer if it does not exist there already
