### ISSUE TITLE
Shared calendar is not editable despite checked "can edit" checkbox

### ISSUE THREAD

**Issue by chkl** [nextcloud/server#6838]
Hi
since I couldn't find this bug (or feature?) originally described [here](https://help.nextcloud.com/t/calendar-share-works-but-no-edit-write-access-with-some-users/21441) I'm opening this.

 

 
### Steps to reproduce
1. Create a calendar
2. Share to user X (not a group) with checked "can edit" box
3. Log in as that user

### Expected behaviour
The calendar should be editable by user X

### Actual behaviour
It appears under "Subscriptions" and is not editable.

### Server configuration

**Operating system**: Debian 9

**Web server:** Apache

**Database:** Postgresl

**PHP version:** 7

**Nextcloud version:** (12.0.3)

**Comment by svenXY** [comment]
confirmed here.

**Comment by georgehrke** [comment]
dup of https://github.com/nextcloud/calendar/issues/606
