### ISSUE TITLE
Nextcloud got internal Server error after update APP:OnlyOFFICE, need to remove this APP completely

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/server#6839]
<!--
Thanks for reporting issues back to Nextcloud! This is the issue tracker of Nextcloud, if you have any support question please check out https://nextcloud.com/support

### Steps to reproduce
1. Activate ONLYOffice
2. Logon as admin
3. Jump to Admin Panel
4. Recover from this Situation only possible, after Deinstalling ONLYOiffice completely (Remove APP)

Result:

Interner Serverfehler
Der Server hat einen internen Fehler und konnte Deine Anfrage nicht vervollständigen.
Bitte wende dich an den Serveradministrator, wenn dieser Fehler mehrfach auftritt, gebe bitte die, unten stehenden, technischen Details in Deinem Bericht mit an.
Weitere Details können im Server-Protokoll gefunden werden.

Technische Details
Entfernte Adresse: xx.xx.xx.xx.
Anfragekennung: jPAd5E9ka4PyGRqq3qsA

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### General server configuration

**Operating system:** FreeBSD Nextcloud 11.0-STABLE FreeBSD 11.0-STABLE #0 r321665+25fe8ba8d06(freenas/11.0-stable): Mon Sep 25 06:24:11 UTC 2017     root@gauntlet:/freenas-11-releng/freenas/_BE/objs/freenas-11-releng/freenas/_BE/os/sys/FreeNAS.amd64 amd64

**Web server:** Apache/2.4.27 (FreeBSD) OpenSSL/1.0.2j-freebsd PHP/7.0.21 (apache2handler)

**Database:** mysql 10.2.7

**PHP version:** 7.0.21
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - pcre
 - Reflection
 - SPL
 - hash
 - session
 - apache2handler
 - standard
 - apcu
 - bz2
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - filter
 - gd
 - mysqlnd
 - iconv
 - intl
 - json
 - exif
 - mcrypt
 - openssl
 - PDO
 - posix
 - SimpleXML
 - xml
 - xmlwriter
 - zip
 - zlib
 - memcached
 - pdo_mysql
 - wddx
 - xmlreader
 - xsl
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** YOUR ANSWER HERE

**Where did you install Nextcloud from:**  YOUR ANSWER HERE

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OC\Files\Storage\DAV
    [2] => \OCA\Files_External\Lib\Storage\OwnCloud
    [3] => \OCA\Files_External\Lib\Storage\SFTP
    [4] => \OCA\Files_External\Lib\Storage\AmazonS3
    [5] => \OCA\Files_External\Lib\Storage\Dropbox
    [6] => \OCA\Files_External\Lib\Storage\Google
    [7] => \OCA\Files_External\Lib\Storage\Swift
    [8] => \OCA\Files_External\Lib\Storage\SFTP
    [9] => OCA\SharePoint\Storage\Storage
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** YOUR ANSWER HERE (LDAP/ActiveDirectory/Webdav/...)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - announcementcenter: 3.1.0
 - apporder: 0.4.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.5
 - circles: 0.12.4
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - deck: 0.2.4
 - external: 2.0.3
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_clipboard: 0.6.4
 - files_external: 1.3.0
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - impersonate: 1.0.1
 - issuetemplate: 0.2.2
 - keeweb: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mood: 0.3.2
 - music: 0.5.3
 - nextcloud_announcements: 1.1
 - notes: 2.3.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - ownbackup: 17.5.0
 - passman: 2.1.4
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - quota_warning: 1.1.1
 - rainloop: 5.0.3
 - ransomware_protection: 1.0.4
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - sharepoint: 1.0.2
 - socialsharing_diaspora: 1.0.1
 - socialsharing_email: 1.0.1
 - socialsharing_facebook: 1.0.1
 - socialsharing_googleplus: 1.0.1
 - socialsharing_twitter: 1.0.1
 - spreed: 2.0.1
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - tasks: 0.9.5
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_audit
 - appvncsafe
 - audioplayer
 - documents
 - encryption
 - mail
 - ojsxc
 - spreedme
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": true,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "\/tmp\/redis.sock",
        "port": 0,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***",
        "timeout": 1.5
    },
    "instanceid": "ocnudqtqmhau",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "xxxx",
        "xxxx",
        "xxxx"
    ],
    "datadirectory": "\/media",
    "overwrite.cli.url": "http:\/\/7cloud.zapto.org",
    "dbtype": "mysql",
    "version": "12.0.3.3",
    "dbname": "nextcloud",
    "dbhost": "localhost:\/tmp\/mysql.sock",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 1,
    "updater.release.channel": "stable",
    "auth.bruteforce.protection.enabled": true,
    "check_for_working_htaccess": true,
    "data-fingerprint": "0d5047d1213fda4b9abc01d8dc96ca65",
    "mail_from_address": "NextCloud",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "7cloud.zapto.org",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "mail.shinternet.ch",
    "mail_smtpport": "587",
    "session_lifetime": 7200,
    "session_keepalive": false
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36 Edge/15.15063

**Operating system:** YOUR ANSWER HERE

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment]
You need to be more specific when you are trying to report a problem.

If the problem is only related to the OnlyOffice app, please report it there:
https://github.com/ONLYOFFICE/onlyoffice-owncloud

Otherwise open a new issue and fill out the required information.

**Comment by Githopp192** [comment]
HI Joad .. thx4your answer to this. I really do appreciate the work you do to Support the NextCloud Community.

You're right .. Application issues should be reported to the Application Line .. but, i think, whenever Applications have a severe sight effect, that important Nextcloud functionalities do not work anymore, then this becomes an issue to the NextCloud itself .. this could be a design Problem or else.

Applications should never touch the Core System stability. When they do .. there is a common Problem with the App design .. 

Of Course i will/or can open an OnlyOFFICE CASE, too.
Let me know, when i can give further infomrations.

It seems, that by upgrading OnlyOffice the ADMIN context into the NextCloud ADMIN page got lost .. and that caused NextCloud to Crash.

Thx
Mike

=====================================

Here are more Details about >


Error | no app in context | OCP\AppFramework\QueryException: Could not resolve   OCA\Onlyoffice\AdminSettings! Class OCA\Onlyoffice\AdminSettings does not   exist | 2 hours ago
-- | -- | -- | --
Error | no app in context | OCP\AppFramework\QueryException: Could not resolve   OCA\Onlyoffice\AdminSettings! Class OCA\Onlyoffice\AdminSettings does not   exist | 2 hours ago
Error | no app in context | OCP\AppFramework\QueryException: Could not resolve   OCA\Onlyoffice\AdminSettings! Class OCA\Onlyoffice\AdminSettings does not   exist | 2 hours ago
Error | no app in context | OCP\AppFramework\QueryException: Could not resolve   OCA\Onlyoffice\AdminSettings! Class OCA\Onlyoffice\AdminSettings does not   exist | 2 hours ago
Error | no app in context | OCP\AppFramework\QueryException: Could not resolve   OCA\Onlyoffice\AdminSettings! Class OCA\Onlyoffice\AdminSettings does not   exist | 2 hours ago
Error | no app in context | OCP\AppFramework\QueryException: Could not resolve   OCA\Onlyoffice\AdminSettings! Class OCA\Onlyoffice\AdminSettings does not   exist | 2 hours ago
Error | no app in context | OCP\AppFramework\QueryException: Could not resolve   OCA\Onlyoffice\AdminSettings! Class OCA\Onlyoffice\AdminSettings does not   exist |
