### ISSUE TITLE
Is it possible to merge this PR from Owncloud? I'm getting the same error users reported on OC 

### ISSUE THREAD

**Issue by leonidasv** [nextcloud/server#6843]
I'm getting pretty the same error reported here: https://github.com/owncloud/client/issues/5712

After reading the conversation, I saw that a PR was made to fix this: https://github.com/owncloud/core/pull/28238/files

So, is it possible to merge the same modifications into Nextcloud? I could fork, merge and start a new PR for Nextcloud, but I have no means to test if it works, since the server reporting the error is a production one. Could anyone help me on this?

**Comment by nickvergessen** [comment]
The issue has been fixed with Nextcloud 12.0.0, 8 months ago.
Which version are you running?

**Comment by leonidasv** [comment]
Hmm, I'm running v12.0.2. Still seeing this issue.

**Comment by nickvergessen** [comment]
Well since we copied the fix and it seems to not help,
I guess it would be good if you fill out the issue template and describe again what you are doing and what is (not) happening etc with giving the infos about all your versions and the logs.

**Comment by leonidasv** [comment]
Ok, thanks.
