### ISSUE TITLE
Setting ldapIgnoreNamingRules does not wrong

### ISSUE THREAD

**Issue by joshuaavalon** [nextcloud/server#6851]
### Steps to reproduce
1. Set config.php `'ldapIgnoreNamingRules' => true,`
2.  Add throw exception to see the value in log

### Expected behaviour
https://github.com/nextcloud/server/blob/66a5a45c503269699666df61c605d67f3c72c7c0/apps/user_ldap/lib/Access.php#L1252

should be `true`.

### Actual behaviour
Not `true` (Seems to be `null`)

### Server configuration

**Operating system**: alpine

**Web server:** nginx

**Database:** SQLITE

**PHP version:**  7

**Nextcloud version:** Nextcloud 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**  Fresh install

**Where did you install Nextcloud from:**  linuxserver/nextcloud docker

**Signing status:**
<details>
<summary>Signing status</summary>

```
N/A
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
    'debug' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'datadirectory' => '/data',
  'trusted_domains' => 
  array (
    0 => '192.168.1.95:8443',
  ),
  'overwrite.cli.url' => 'https://192.168.1.95:8443',
  'dbtype' => 'sqlite3',
  'version' => '12.0.3.3',
  'installed' => true,
  'ldapIgnoreNamingRules' => true,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
);
```
</details>

**Are you using external storage, if yes which one:**  No

**Are you using encryption:**  No

**Are you using an external user-backend, if yes which one:**  LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
N/A
```
</details>

### Client configuration
**Browser:** N/A

**Operating system:** N/A

#### Web server error log
<details>
<summary>Web server error log</summary>

```
N/A
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
N/A
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
N/A
```
</details>

**Comment by MorrisJobke** [comment]
cc @nextcloud/ldap

**Comment by blizzz** [comment]
whee, that issues was buried for more than 4 years. Should have abandoned this setting :D  ;)

@joshuaavalon should be fixed with https://github.com/nextcloud/server/pull/8122, can you test?

**Comment by MorrisJobke** [comment]
@blizzz Could this be catched a bit more nicely without this weird error message?
