### ISSUE TITLE
Filepicker's 'Choose' button looks broken if no file is selected

### ISSUE THREAD

**Issue by leonklingele-work** [nextcloud/server#6852]
Using latest master, e964f83f28c49402678478774a2d1f62b02205d8.

### Steps to reproduce
1. Open the Nextcloud file picker: `OC.dialogs.filepicker('Title', function(file) { }, false, null);`
2. Notice the 'Choose' button looking broken (see screenshot attached)

No file is selected:
![filepicker-no_file_selected](https://user-images.githubusercontent.com/31063993/31658533-8d8804ae-b331-11e7-9282-a89d67bd52ff.png)

A file is selected:
![filepicker-file_selected png](https://user-images.githubusercontent.com/31063993/31658544-97d12148-b331-11e7-9824-930cb36cefd4.png)

@nextcloud/designers

**Comment by mehrdaad** [comment]
@leonklingele-work hey, How to open filepicker from another webapp to choose a file? have any info on that? @nextcloud/designers

**Comment by leonklingele-work** [comment]
@mehrdaad see __step 1.__ of my __Steps to reproduce__ above.

**Comment by mehrdaad** [comment]
@leonklingele-work Don't think that's what I'm looking for. The end goal is to open Nextcloud's file picker from another application. Like what Google drive or Dropbox provide.

**Comment by leonklingele-work** [comment]
@mehrdaad that is unrelated to this issue here. Please open a separate one to track your feature request.

**Comment by mehrdaad** [comment]
@leonklingele-work I know, but though you might be informed about it. please answer if you can.  
https://github.com/nextcloud/server/issues/6911

**Comment by jancborchardt** [comment]
@leonklingele-work do you think increasing the opacity a bit would be nicer? If so, which value do you think fits?

**Comment by skjnldsv** [comment]
Fixed since 15
