### ISSUE TITLE
Question - Sharing Folders

### ISSUE THREAD

**Issue by Artapel** [nextcloud/server#6856]
Hi Guys.

Please do not stone me for this Q

I, for the life of me, cannot seem to figure out how to share one or more folders between multiple users on nextcloud.

As an admin, i created a group called "Technical" and added 5 technical users.
How do i share the "Technical" folder between the 5 technical users i just created.

Googling has giving me a bunch or results and some refer to "the normal way". But i cant seem to find the button that does it "the normal way"

Advice would be appreciated

Thanks guys

**Comment by nickvergessen** [comment]
Click on share icon in the file row, type their name into the input field.
> ![bildschirmfoto vom 2017-10-18 10-52-53](https://user-images.githubusercontent.com/213943/31709561-a97f0b14-b3f2-11e7-80b9-01373f4765ae.png)
