### ISSUE TITLE
Add support (directly or via plugin) to hide folders from sync clients/webdav

### ISSUE THREAD

**Issue by michae1ho11ey** [nextcloud/server#6858]
## Feature Request
Please add support for hiding folder(s) of choice from the desktop/mobile sync clients and WebDAV view. The folder would never be hidden in the Web UI.

### Implementation
* A folder can be personally selected to be hidden from the three dots folder options in the Files app.
* Add support for hiding a folder globally under both the Group Folders and External Storage apps via the Admin settings for the respective apps.
* If an individual still wants to sync the hidden folder, they can override global settings by navigating to the hidden folder in the Files app and uncheck the hidden option.

## Use Case One
I have a group folder, Media, where I store all of my family photos. Under that folder I have a folder called 'Photo Library' with all the pictures I've ever taken. This Media folder collectively is around 100 GBs.

When I finished uploading all of the older pictures to the folder 'Photo Library' every desktop client immediately started downloading and filled up the hard drive of every computer in my home. I then had to scramble between every machine and every user on every machine and deselect the 'Photo Library' folder from the sync settings then manually remove that directory to clear up drive space. It would've been much easier to just hide that folder from the web UI when creating the Group Folder since I knew from the start that none of the computers on the network had space for that folder.

## Use Case Two
I recently installed the Pico CMS app and discovered that this tool uses two different directories; `apps/Pico_CMS/` and a folder of choice (`Websites/`). The 'apps/Pico_CMS' folder is set to hold app settings whereas the second folder holds the content of the website. Since the settings of the app aren't needed for my personal use it would be nice to hide the 'apps' folder from being synced.

It would also be nice to have an app settings folder, like 'apps/', that more complex NC apps and 3rd party integrations can default to storing customized settings there.

## Use Case Three
My primary computer is a Mac. Apple introduced a feature a few years ago called Hand Off. To summarize the feature, any app that supports this Hand Off feature, syncs its application state data to iCloud so no matter what platform you launch the app from the state of where it was from a different platform is available. This location on iCloud is not viewable to users who sync their iCloud files to their computers.

So having support to hide folders would allow for similar state saving features for future apps. 

## Use Case Four
NC's sync system is great for keeping the current version of a file available everywhere. Some people also try to use NC as a backup location until they accidentally delete a file and the Desktop Sync agent does the same with the file on the NC server. If someone where to create a client backup app that allows setting up a backup endpoint that stores several versions of a file and makes them available even if the file is deleted from the client.

However, storing the backup in the users Files apps creates an issue of syncing the backed up files back down to the client machine and filling up their hard drive. But if a user had a 'backup/' directory in their NC Files app that was marked hidden, the Backup app could store all of the files and the versions there without the backed up files being synced back to the client machine.

**Comment by wiswedel** [comment]
Maybe you can live with a workaround via https://github.com/nextcloud/files_accesscontrol?

Just tag the folders to be not downloaded and then disallow accessing them by client.

**Comment by michae1ho11ey** [comment]
@wiswedel That would be a okay workaroud, assuming it would work.
I just tried the following steps and the folder I tagged still synced.

1. Pause sync on my desktop client
2. Created a folder called 'Apps' with the `no-sync` tag
3. Created a file access rule:
    - File system tag > is tagged with > no-sync
    - Request user agent > is > Desktop client (built-in preset)
    - Request user agent > is > iOS client (built-in preset)
4. Resumed syncing on desktop client

The idea I was hoping for, was the native clients can't pull it down, but I could still use it via the web. In the workflow example they block the Mozilla user agent, but I use Firefox, so using that would block web access as well. I should also note, before adding the user agent lines, I just has the tag line and it did block access to that folder (both via the sync client and the web), so I know at least that line works.

I should note that removing the 'Desktop client' and 'iOS client' and using the Mozilla user agent line, as seen in the [workflow example](https://nextcloud.com/wp-content/themes/next/assets/img/features/FileAccessControl-at-home.png?x22777) it still allows the syncing of the folder and it's contents.

**Comment by wiswedel** [comment]
@michae1ho11ey 
The rules are ANDed (all criteria must apply).
Your set could never match, since you're not accessing the file with desktop AND iOS at the same time.

In order to restrict access with any of the four predefined client types, you need to configure four separate rule sets - one for each client type.

**Comment by michae1ho11ey** [comment]
🤦‍♂ I guessed it was an AND situation but didn't think about the competing agents invalidating the rule. I added just the desktop client in and it worked. Thanks for the heads up.
