### ISSUE TITLE
Also support to backport translations

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#686]
- get po files for all stable branches & master
- upload this to master
- generate the json/js files for all stable branches & master based on this

@MariusBluem

**Comment by MorrisJobke** [comment]
We should use `msgcat --use-first *.pot > merged.pot` to combine POT files. (`msgcat` is part of the `gettext-devel` package.

See http://stackoverflow.com/a/4053017/520507

**Comment by MorrisJobke** [comment]
As a first step I implemented to extract the translations from old versions: https://github.com/nextcloud/docker-ci/commit/5c3f0818af2a0d05c6365b6536ce496d7bbcf3cf

I would like to let this run and wait for the old translations to come in (I don't want to fiddle around just to extract the translations that were done for the old releases but then were dropped from transifex). Then translators can translate and I would add to also bring updated translations to stable branches. (most likely stable10 only for now)

**Comment by MariusBluem** [comment]
Any way to get Nextcloud 10 translated for 10.0.1 in a more proper way ... There are still some untranslated strings in **German** (...which is a common language 😜) @MorrisJobke

**Comment by MorrisJobke** [comment]
> Any way to get Nextcloud 10 translated for 10.0.1 in a more proper way ... There are still some untranslated strings in German (...which is a common language 😜)

core is already backported - only the non-server repos are not backported yet.

**Comment by MorrisJobke** [comment]
This should be mainly done. If an app needs this special backporting then ping me
