### ISSUE TITLE
Cannot remove "Can reshare" tick

### ISSUE THREAD

**Issue by Artapel** [nextcloud/server#6862]
Hi Guys. Noob here

I cannot seem to get the "Can reshare" tick to go away. it keeps adding itself after unticking it. Is there a trick to do this.
The same behaviour accurs when im trying to remove the  "Share Link" tick

![image](https://user-images.githubusercontent.com/18235030/31713681-4db52126-b3ff-11e7-9410-2c701d48d04d.png)

Are there any Gurus that can please advise me?

**Comment by georgehrke** [comment]
@Artapel please use the entire issue template and provide all logs asked for.

**Comment by MorrisJobke** [comment]
Seems to be #5916 which is fixed in the meantime.
