### ISSUE TITLE
Can not use page up/pagedown/up/down to scroll in files_app 

### ISSUE THREAD

**Issue by jsalatiel** [nextcloud/server#6863]
### Steps to reproduce
1. Login in webinterface
2. Enter in a directory with a great number of files/directories or  the root folder if it has lots of file (bigger than screen height)
3. Try scrolling using the keyboard. (PgUp/PgDown/Up/Down)

### Expected behaviour
You should be able to scroll down or up using the keyboard

### Actual behaviour
Scrolling wont work using the keyboard. It will only work using mouse scroll. 
Tested on firefox 56 and chrome 60 ( BOTH ON LINUX)

### Server configuration

**Operating system**:
Debian GNU/Linux 9

**Web server:**
Apache 2.4.25

**Database:**
mariadb 10.1.26

**PHP version:**
7.0.19

**Nextcloud version:** (see Nextcloud admin page)
12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

### Client configuration
**Browser:** Firefox 56 or Chrome 60

**Operating system:**
Linux Mint 18

**Comment by nickvergessen** [comment]
You can, but first you need to `Tab` until you are in the files list.

The rest should be dealt with in #1444

**Comment by Pistos** [comment]
Sorry to necrobump a very old issue, but the main UX issue persists even to recent versions like 28.0.2. I understand that I can Tab-key or mouse click to activate the file list, and *then* we can use Page Up and Page Down. However, I would argue that this is still poor UX. If I navigate to a part of Nextcloud whose main body content is a large list, I expect that I would be able to use the Page keys immediately, without 5+ Tab key presses, or having to move the mouse cursor and click to a specific spot which does not also activate something else (such as incidentally opening the file sidebar). This should especially be the case when no other part of the UI is long enough to need scrolling in its DOM container (e.g. the left sidebar). In such cases, literally nothing else in the UI needs page movement except the file list, so nearly all users would think that the obvious behaviour should be that the file list is paged when one presses those keys.

Nextcloud's behaviour should be that, if the current keyboard focus is on something which has no use for Page Up or Down keypresses, it should forward those keypresses to the main content area (which is the right-side file list when navigating the Files part of Nextcloud). Perhaps there might be edge cases where this ought not apply, but my point is that what normal end users would expect seems very clear here.
