### ISSUE TITLE
Group admin should have optional access to files of all group members

### ISSUE THREAD

**Issue by tischenko** [nextcloud/server#6866]
Hi,

We faced a quite specific use-case and would like to know about any possible solutions.

There is a considerable amount of user groups with 10-20 users in each. Every group member has access only to its personnel files. Also, each group has 1-2 admins, and these admins should have access to all the files of all group members.
I assume that it's possible to solve this problem with share feature but in this case, we need a way to create such shares in a bulk mode (API?).

Are there any other ways to achieve that?

Thanks.

**Comment by Slevin7** [comment]
Isn't it easier if the admin create all Folder and share with the people in the group?
So he have access to all the data.

**Comment by nickvergessen** [comment]
> Isn't it easier if the admin create all Folder and share with the people in the group?

That is exactly what I would suggest.
You can even create the folders and shares via APIs.

For folders it's WebDAV and for the shares a simple curl command against our API should do:
https://docs.nextcloud.com/server/12/developer_manual/core/ocs-share-api.html#create-a-new-share

But giving group admins full access to all members by default is not an option.

**Comment by tischenko** [comment]
Thanks, this looks good. I will try that option.
