### ISSUE TITLE
Find an app by name within nextcloud

### ISSUE THREAD

**Issue by hajika** [nextcloud/server#6868]
When Iam searching for an app that has a specific name on page `settings/app`, I cant just use the search function because it will only search in the current page. And because there is no page for "all apps", I have to get through each category before I can find the app by name.

There needs t be a possibility to find and install an app within nextcloud by simple name search. Even when one finds the app by name on https://apps.nextcloud.com/apps, there is no information in what category its hidden.

**Comment by georgehrke** [comment]
@jancborchardt

**Comment by nickvergessen** [comment]
Maybe the app store can display the categories? @BernhardPosselt

**Comment by BernhardPosselt** [comment]
This is about the nextcloud server right?

**Comment by nickvergessen** [comment]
The request yes, but it would also help, if e.g. https://apps.nextcloud.com/apps/admin_notifications would tell you in which category you would find the app on the server
https://github.com/nextcloud/admin_notifications/blob/master/appinfo/info.xml#L11-L12

**Comment by BernhardPosselt** [comment]
Should be available in the downloaded apps.json, see **categories** in http://nextcloudappstore.readthedocs.io/en/latest/restapi.html#get-all-apps-and-releases

**Comment by nickvergessen** [comment]
yeah, but the appstore UI doesnt show it ;)

**Comment by BernhardPosselt** [comment]
Ah ok :)

File an issue in the issue tracker please

**Comment by jancborchardt** [comment]
Absolutely agree, had the same issue recently.

- The search should also search through appstore apps below / after the local results (without blocking the local search of course)
- There should be a sidebar entry "App store" above the categories which lists all apps from the app store, sorted by rating.

**Comment by hajika** [comment]
> Maybe the app store can display the categories?
eh ok, that would help for the workaround a bit, but the real problem is not the website but the here addressed nextcloud server :)

**Comment by vitaliis** [comment]
+1. Also had this issue. Found this https://github.com/nextcloud/appstore/issues/528. It would help to workaroud the problem. But showing a category is generally a good idea.

Another possible solution to this problem:
* If search in one category did not give any results, try to search through "all apps". The same way as it is done for files (e.g. 7 search results in other folders)

**Comment by jospoortvliet** [comment]
Yeah, searching all apps would be a huge help. And perhaps an 'all apps' category, too? Ref https://twitter.com/SisimBiva/status/981547010221314048

**Comment by BloodyIron** [comment]
Not being able to search for all has wasted a good amount of my time already. I don't know how the apps are categorised, and often I'll find apps in a section that doesn't make sense to me. Having search all really is needed, otherwise the search is useless IMO.

**Comment by MorrisJobke** [comment]
Fixed with #9565
