### ISSUE TITLE
Show apps with updates at the top of the apps list

### ISSUE THREAD

**Issue by sealne** [nextcloud/server#6871]
It would make things easier when there is an update for an app if apps with updates were shown at the top of the apps settings list

### Steps to reproduce
1. Click on notice about app update available in web interface
2. Scroll through list of apps hunting for it
3. Click update

### Expected behaviour
In the list of apps in settings any with updates are shown at top to make them easy to find

### Actual behaviour
Have to hunt through the list of apps until you find the one(s) with an update button

### Server configuration

**Nextcloud version:** 12.0.3

**Comment by nickvergessen** [comment]
We added a special section for the next major release: #6739
