### ISSUE TITLE
WebDAV external storage not always online

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#6872]
### Steps to reproduce
1. Connect Yandex.Disk as WebDAV via external storage app as Nextcloud root folder.
2. Use Nextcloud as usual.

### Expected behaviour
External storage should always accessible and available.

### Actual behaviour
Sometimes storage is missing and not accessible (via web version or sync clients). Access is restored on visiting user profile and check external storage availability manually (clicking green dot) or using occ files_external:verify command. For temporary workaround I used this command scheduled by cron for execute every 1 minute.

### General server configuration

I replaced with *** some sensitive server info (IP, domain etc).

**Operating system:** Linux *** 4.4.0-96-generic #119-Ubuntu SMP Tue Sep 12 14:59:54 UTC 2017 x86_64

**Web server:** Apache/2.4.18 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.0.2g (apache2handler)

**Database:** mysql 5.7.19

**PHP version:** 7.0.22-0ubuntu0.16.04.1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - apache2handler
 - inotify
 - mysqlnd
 - PDO
 - xml
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - iconv
 - igbinary
 - imap
 - intl
 - json
 - ldap
 - exif
 - mcrypt
 - mysqli
 - pdo_mysql
 - pdo_sqlite
 - Phar
 - posix
 - pspell
 - readline
 - redis
 - shmop
 - SimpleXML
 - soap
 - sockets
 - sqlite3
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 10.x > 11.x > 12.x

**Where did you install Nextcloud from:**  Official site

**Are you using external storage, if yes which one:** \OC\Files\Storage\DAV

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - apporder: 0.4.0
 - audioplayer: 2.1.0
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.6
 - checksum: 0.3.5
 - contacts: 2.0.1
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_clipboard: 0.6.4
 - files_downloadactivity: 1.1.1
 - files_external: 1.3.0
 - files_markdown: 2.0.1
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.2
 - keeweb: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - mail: 0.7.3
 - metadata: 0.5.0
 - news: 11.0.5
 - notes: 2.3.1
 - oauth2: 1.0.5
 - ocsms: 1.12.1
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - quota_warning: 1.1.1
 - radio: 0.6.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - socialsharing_email: 1.0.1
 - socialsharing_facebook: 1.0.1
 - socialsharing_twitter: 1.0.1
 - tasks: 0.9.5
 - telephoneprovider: 1.0.0
 - theming: 1.3.0
 - theming_customcss: 1.0.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.1
 - updatenotification: 1.2.0
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_audit
 - comments
 - encryption
 - files_versions
 - nextcloud_announcements
 - notifications
 - survey_client
 - systemtags
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "ochz7eaxszq3",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***"
    ],
    "datadirectory": "\/home\/admin\/web\/***\/public_html\/nc\/data",
    "overwrite.cli.url": "https:\/\/***\/nc",
    "dbtype": "mysql",
    "version": "12.0.3.3",
    "dbname": "admin_nextcloud",
    "dbhost": "localhost",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "localhost",
        "port": 6379
    },
    "updater.release.channel": "production",
    "preview_max_x": 100,
    "preview_max_y": 100,
    "maintenance": false,
    "quota_include_external_storage": true,
    "trashbin_retention_obligation": "2, 7",
    "theme": "",
    "loglevel": 2
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36

**Operating system:** Windows 7 or 10

### Logs

<details>
        <summary>Web server error log</summary>

```
195.***.180 - serenitatis [18/Oct/2017:16:10:05 +0300] "PROPFIND /nc/remote.php/dav/files/serenitatis/%D0%90%D1%80%D1%85%D0%B8%D0%B2%D1%8B/Lazarus HTTP/1.0" 500 1090 "-" "Mozilla/5.0 (Windows) mirall/2.3.2 (build 1) (Nextcloud)"
```
		
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
{"reqId":"dW8tYnS8B24nHff8E5lX","level":3,"time":"2017-10-18T13:10:06+00:00","remoteAddr":"185.***.162","user":"serenitatis","app":"no app in context","method":"PROPFIND","url":"\/nc\/remote.php\/dav\/files\/serenitatis\/%D0%90%D1%80%D1%85%D0%B8%D0%B2%D1%8B\/Lazarus","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\StorageNotAvailableException\",\"Message\":\"Sabre\\\\HTTP\\\\ClientHttpException: Service Unavailable\",\"Code\":1,\"Trace\":\"#0 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(279): OC\\\\Files\\\\Storage\\\\DAV->convertException(Object(Sabre\\\\HTTP\\\\ClientHttpException), '\\\\xD0\\\\x90\\\\xD1\\\\x80\\\\xD1\\\\x85\\\\xD0\\\\xB8\\\\xD0\\\\xB2\\\\xD1\\\\x8B\\\/La...')\\n#1 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(320): OC\\\\Files\\\\Storage\\\\DAV->propfind('\\\\xD0\\\\x90\\\\xD1\\\\x80\\\\xD1\\\\x85\\\\xD0\\\\xB8\\\\xD0\\\\xB2\\\\xD1\\\\x8B\\\/La...')\\n#2 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(220): OC\\\\Files\\\\Storage\\\\DAV->file_exists('\\\\xD0\\\\x90\\\\xD1\\\\x80\\\\xD1\\\\x85\\\\xD0\\\\xB8\\\\xD0\\\\xB2\\\\xD1\\\\x8B\\\/La...')\\n#3 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(220): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->file_exists('\\\\xD0\\\\x90\\\\xD1\\\\x80\\\\xD1\\\\x85\\\\xD0\\\\xB8\\\\xD0\\\\xB2\\\\xD1\\\\x8B\\\/La...')\\n#4 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(241): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->file_exists('\\\\xD0\\\\x90\\\\xD1\\\\x80\\\\xD1\\\\x85\\\\xD0\\\\xB8\\\\xD0\\\\xB2\\\\xD1\\\\x8B\\\/La...')\\n#5 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(220): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->file_exists('\\\\xD0\\\\x90\\\\xD1\\\\x80\\\\xD1\\\\x85\\\\xD0\\\\xB8\\\\xD0\\\\xB2\\\\xD1\\\\x8B\\\/La...')\\n#6 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/Files\\\/View.php(1136): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->file_exists('\\\\xD0\\\\x90\\\\xD1\\\\x80\\\\xD1\\\\x85\\\\xD0\\\\xB8\\\\xD0\\\\xB2\\\\xD1\\\\x8B\\\/La...')\\n#7 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/Files\\\/View.php(532): OC\\\\Files\\\\View->basicOperation('file_exists', '\\\/\\\\xD0\\\\x90\\\\xD1\\\\x80\\\\xD1\\\\x85\\\\xD0\\\\xB8\\\\xD0\\\\xB2\\\\xD1\\\\x8B\\\/L...')\\n#8 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(285): OC\\\\Files\\\\View->file_exists('\\\/\\\\xD0\\\\x90\\\\xD1\\\\x80\\\\xD1\\\\x85\\\\xD0\\\\xB8\\\\xD0\\\\xB2\\\\xD1\\\\x8B\\\/L...')\\n#9 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(105): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->childExists('Lazarus')\\n#10 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAVACL\\\/Plugin.php(878): Sabre\\\\DAV\\\\Tree->nodeExists('files\\\/serenitat...')\\n#11 [internal function]: Sabre\\\\DAVACL\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#13 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#14 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#15 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/apps\\\/dav\\\/lib\\\/Server.php(258): Sabre\\\\DAV\\\\Server->exec()\\n#16 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#17 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/remote.php(162): require_once('\\\/home\\\/admin\\\/web...')\\n#18 {main}\",\"File\":\"\\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php\",\"Line\":838}","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.2 (build 1) (Nextcloud)","version":"12.0.3.3"}
```
</details>

<details>
        <summary>Browser log</summary>

Not necessary.

</details>

**Comment by serenitatis** [comment]
Also I have same problem with errors:
`{"reqId":"JSeylMSIy8hFH1f6fWGc","level":3,"time":"2017-10-26T17:16:16+00:00","remoteAddr":"***","user":"serenitatis","app":"files_external","method":"PUT","url":"\/nc\/remote.php\/webdav\/%D0%90%D0%B2%D1%82%D0%BE%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0\/Redmi%20Note%203%20Pro\/\/IMG_20171023_081129.jpg-chunking-2110305055-7-5","message":"Unknown SSL protocol error in connection to webdav.yandex.ru:443 ","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/2.0.0","version":"12.0.3.3"}
{"reqId":"JSeylMSIy8hFH1f6fWGc","level":3,"time":"2017-10-26T17:16:16+00:00","remoteAddr":"***","user":"serenitatis","app":"no app in context","method":"PUT","url":"\/nc\/remote.php\/webdav\/%D0%90%D0%B2%D1%82%D0%BE%D0%B7%D0%B0%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0\/Redmi%20Note%203%20Pro\/\/IMG_20171023_081129.jpg-chunking-2110305055-7-5","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\StorageNotAvailableException\",\"Message\":\"Sabre\\\\HTTP\\\\ClientException: Unknown SSL protocol error in connection to webdav.yandex.ru:443 \",\"Code\":1,\"Trace\":\"#0 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(281): OC\\\\Files\\\\Storage\\\\DAV->convertException(Object(Sabre\\\\HTTP\\\\ClientException), '\\\\xD0\\\\x90\\\\xD0\\\\xB2\\\\xD1\\\\x82\\\\xD0\\\\xBE\\\\xD0\\\\xB7\\\\xD0\\\\xB0\\\\xD0\\\\xB3\\\\xD1...')\\n#1 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(320): OC\\\\Files\\\\Storage\\\\DAV->propfind('\\\\xD0\\\\x90\\\\xD0\\\\xB2\\\\xD1\\\\x82\\\\xD0\\\\xBE\\\\xD0\\\\xB7\\\\xD0\\\\xB0\\\\xD0\\\\xB3\\\\xD1...')\\n#2 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(220): OC\\\\Files\\\\Storage\\\\DAV->file_exists('\\\\xD0\\\\x90\\\\xD0\\\\xB2\\\\xD1\\\\x82\\\\xD0\\\\xBE\\\\xD0\\\\xB7\\\\xD0\\\\xB0\\\\xD0\\\\xB3\\\\xD1...')\\n#3 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(241): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->file_exists('\\\\xD0\\\\x90\\\\xD0\\\\xB2\\\\xD1\\\\x82\\\\xD0\\\\xBE\\\\xD0\\\\xB7\\\\xD0\\\\xB0\\\\xD0\\\\xB3\\\\xD1...')\\n#4 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(220): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->file_exists('\\\\xD0\\\\x90\\\\xD0\\\\xB2\\\\xD1\\\\x82\\\\xD0\\\\xBE\\\\xD0\\\\xB7\\\\xD0\\\\xB0\\\\xD0\\\\xB3\\\\xD1...')\\n#5 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/Files\\\/View.php(1136): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->file_exists('\\\\xD0\\\\x90\\\\xD0\\\\xB2\\\\xD1\\\\x82\\\\xD0\\\\xBE\\\\xD0\\\\xB7\\\\xD0\\\\xB0\\\\xD0\\\\xB3\\\\xD1...')\\n#6 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/Files\\\/View.php(532): OC\\\\Files\\\\View->basicOperation('file_exists', '\\\/\\\\xD0\\\\x90\\\\xD0\\\\xB2\\\\xD1\\\\x82\\\\xD0\\\\xBE\\\\xD0\\\\xB7\\\\xD0\\\\xB0\\\\xD0\\\\xB3...')\\n#7 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(285): OC\\\\Files\\\\View->file_exists('\\\/\\\\xD0\\\\x90\\\\xD0\\\\xB2\\\\xD1\\\\x82\\\\xD0\\\\xBE\\\\xD0\\\\xB7\\\\xD0\\\\xB0\\\\xD0\\\\xB3...')\\n#8 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(105): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->childExists('IMG_20171023_08...')\\n#9 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(506): Sabre\\\\DAV\\\\Tree->nodeExists('\\\\xD0\\\\x90\\\\xD0\\\\xB2\\\\xD1\\\\x82\\\\xD0\\\\xBE\\\\xD0\\\\xB7\\\\xD0\\\\xB0\\\\xD0\\\\xB3\\\\xD1...')\\n#10 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#12 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#13 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#15 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/remote.php(162): require_once('\\\/home\\\/admin\\\/web...')\\n#16 {main}\",\"File\":\"\\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php\",\"Line\":841}","userAgent":"Mozilla\/5.0 (Android) ownCloud-android\/2.0.0","version":"12.0.3.3"}`

and

`{"reqId":"0Lztsd6jFb0lCltLMAh5","level":3,"time":"2017-10-26T20:09:17+00:00","remoteAddr":"***","user":"serenitatis","app":"files_external","method":"GET","url":"\/nc\/index.php\/apps\/files_external\/userstorages\/20?testOnly=true","message":"Failed to connect to webdav.yandex.ru port 443: Connection timed out","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3163.100 Safari\/537.36","version":"12.0.3.3"}
{"reqId":"0Lztsd6jFb0lCltLMAh5","level":3,"time":"2017-10-26T20:09:17+00:00","remoteAddr":"***","user":"serenitatis","app":"no app in context","method":"GET","url":"\/nc\/index.php\/apps\/files_external\/userstorages\/20?testOnly=true","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\StorageNotAvailableException\",\"Message\":\"Sabre\\\\HTTP\\\\ClientException: Failed to connect to webdav.yandex.ru port 443: Connection timed out\",\"Code\":1,\"Trace\":\"#0 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(281): OC\\\\Files\\\\Storage\\\\DAV->convertException(Object(Sabre\\\\HTTP\\\\ClientException), '')\\n#1 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php(577): OC\\\\Files\\\\Storage\\\\DAV->propfind('')\\n#2 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/Files\\\/Storage\\\/Common.php(444): OC\\\\Files\\\\Storage\\\\DAV->stat('')\\n#3 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/apps\\\/files_external\\\/lib\\\/config.php(233): OC\\\\Files\\\\Storage\\\\Common->test(false, 'true')\\n#4 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(256): OC_Mount_Config::getBackendStatus('\\\\\\\\OC\\\\\\\\Files\\\\\\\\Stora...', Array, false, 'true')\\n#5 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/StoragesController.php(305): OCA\\\\Files_External\\\\Controller\\\\StoragesController->updateStorageStatus(Object(OCA\\\\Files_External\\\\Lib\\\\StorageConfig), 'true')\\n#6 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/apps\\\/files_external\\\/lib\\\/Controller\\\/UserStoragesController.php(107): OCA\\\\Files_External\\\\Controller\\\\StoragesController->show('20', 'true')\\n#7 [internal function]: OCA\\\\Files_External\\\\Controller\\\\UserStoragesController->show('20', 'true')\\n#8 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#9 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Files_External\\\\Controller\\\\UserStoragesController), 'show')\\n#10 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files_External\\\\Controller\\\\UserStoragesController), 'show')\\n#11 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Files_Exter...', 'show', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#12 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#13 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#14 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/files_ext...')\\n#15 \\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/index.php(48): OC::handleRequest()\\n#16 {main}\",\"File\":\"\\\/home\\\/admin\\\/web\\\/***\\\/public_html\\\/nc\\\/lib\\\/private\\\/Files\\\/Storage\\\/DAV.php\",\"Line\":841}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3163.100 Safari\/537.36","version":"12.0.3.3"}`

I can't see any errors or abnormal activity on web-server log. Also I can access to Yandex.Disk via other WebDAV apps. Very annoying problem :(

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by icewind1991** [comment]
> Unknown SSL protocol error in connection to webdav.yandex.ru:443

Looks like yandex (or the connection from you server to yandex) is having issues which causes NC to flag the storage as being unavailable, once the storage is marked as unavailable NC will only be re-checked after 10min

**Comment by ChristophWurst** [comment]
ghost -> close
