### ISSUE TITLE
Do not check for shipped apps in the app store

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#6874]
When running an update, Nextcloud checks for app updates in the store. Core apps like dav/files/... are not going to be updated though the store, so the check is not necessary there.

![bildschirmfoto von 2017-10-19 11-49-24](https://user-images.githubusercontent.com/3404133/31765173-cfef404e-b4c3-11e7-91d9-89f2981b0d32.png)

**Comment by MorrisJobke** [comment]
Some of them are now shipped via the appstore 😉 Let's keep it as it is for now.
