### ISSUE TITLE
Feature Request: Import Tasks

### ISSUE THREAD

**Issue by TheCopartnery** [nextcloud/server#6877]
Upon exporting my calendar and tasks from Google Apps (it appears the only method by which to do this is to export one iCal file for the calendar and a separate iCal file for tasks) I have been unable to find a way to import the tasks.

Calendar features a 'Settings & Import' feature at the bottom left of the screen; however, Tasks only shows 'Settings', with no import feature.

A comment in the owncloud tasks repo https://github.com/owncloud/tasks/issues/156#issuecomment-143863827 suggested that importing was possible by uploading the file and then clicking on it form the files app; however, this only displays the text of iCal file.

Here are some other references requesting the ability to import tasks, either via iCal, or even through a CSV or multiline import.
https://help.nextcloud.com/t/batch-add-tasks-or-import-csv/18799
https://github.com/owncloud/tasks/issues/271

Posting here rather than directly to the Tasks repo as when creating a new issue there the boilerplate text states that Migration and CalDAV issues belong in Core. Please advise if this is better posted to the Tasks repo.

**Comment by blizzz** [comment]
>Posting here rather than directly to the Tasks repo as when creating a new issue there the boilerplate text states that Migration and CalDAV issues belong in Core. Please advise if this is better posted to the Tasks repo.

@georgehrke what do you think?

**Comment by georgehrke** [comment]
@TheCopartnery You can import tasks via the calendar app. if you want the tasks app itself to offer an import feature, please open a feature request in the task's app repository.
