### ISSUE TITLE
[Suggestion] Nice urls: make share links becoming nice

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/server#6881]
Currently, share links are ugly, example ```https://www.example.org/owncloud/index.php/s/hash1234```.

Would it be possible - how ? - to change the software and server setup to obtain "nice urls" like
```https://www.example.org/owncloud/hash1234``` ?

**Comment by Slevin7** [comment]
i would love to see an option where you can make your own links like:
https://example.org/nextcloud/importantstuff.
i know it could be easier to "guess" an url but with password protection i think this could be nice

**Comment by MorrisJobke** [comment]
This is already possible: Check out the documentation for pretty URLs: https://docs.nextcloud.com/server/12/admin_manual/installation/source_installation.html#pretty-urls

**Comment by Wikinaut** [comment]
@MorrisJobke Danke, thanks. I cannot know everything....

**Comment by Sanookmakmak** [comment]
@MorrisJobke Yes, it's already possible but the pretty URL funktion does only rewrite index.php of the URL but not the long letters-and-numerbs-combination of shared files, e.g. https://example.org/nextcloud/s/Sv1b7krAUqmF8QQ can not be rewritten to https://example.org/nextcloud/s/my_shared_file

**Comment by aguilaair** [comment]
@Sanookmakmak Have you find a way to do it?

**Comment by Sanookmakmak** [comment]
Unfortunately not, with "pretty URLs" they mean only rewriting of index.php as @MorrisJobke mentioned above.

No idea why this issue has been closed. Sorry @aguilaair

**Comment by kesselb** [comment]
> Currently, share links are ugly, example `https://www.example.org/owncloud/index.php/s/hash1234`.
> 
> Would it be possible - how ? - to change the software and server setup to obtain "nice urls" like
> `https://www.example.org/owncloud/hash1234` ?

I guess the issue is closed because the initial question is answered. There is another issue for custom share links but i could not find it :(

**Comment by aguilaair** [comment]
@kesselb For reference, this is the file i think you meant: https://help.nextcloud.com/t/custom-share-links/2729

**Comment by Franciscorssm24** [comment]
There is an app in Nextcloud that lets you change the way the hyperlink looks after the "/s/" (shared) part.

It's the "ShareRenamer" (not official)

**Comment by Wikinaut** [comment]
ShareRenamer works well, I can confirm.

**Comment by intervisionlord** [comment]
> 
> 
> ShareRenamer works well, I can confirm.

Not now. With new versions of NC it does not work anymore.

**Comment by phuongdzu** [comment]
https://domain.com/hash/filename.ext is better
