### ISSUE TITLE
NC 11.0.5: Internal Server Error while drag & drop a file from file explorer in browser.

### ISSUE THREAD

**Issue by catbou** [nextcloud/server#6883]
Internal Server Error while drag & drop a file from file explorer in browser. After refresh I can see the file is copied. 
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE "oc_filecache" SE
### Steps to reproduce
1.Drag&drop file from file explorer into browser

### Expected behaviour
File is uploaded without errors and is shown in the folder

### Actual behaviour
Internal server error is displayed. After refresh I can see the file.

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:**Apache 2.4.7

**Database: Postgresql:** 9.6

**PHP version:**7.0.16

**Nextcloud version:** 11.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 11.0.3

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** s3

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** ActiveDirectory

### Client configuration
**Browser:** Several: Firefox, Chrome, IE

**Operating system:** Windows xx

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```

  | Doctrine\DBAL\Exception\DriverException: An  exception occurred while executing 'UPDATE "oc_filecache" SET  "path_hash" = ?, "path" = ?, "parent" = ?, "name" = ?, "mimepart" = ?,  "mimetype" = ?, "size" = ?, "mtime" = ?, "storage_mtime" = ?,  "encrypted" = ?, "etag" = ?, "permissions" = ?, "checksum"=? WHERE  ("path_hash" <> ? OR "path" <> ? OR "parent" <> ? OR  "name" <> ? OR "mimepart" <> ? OR "mimetype" <> ? OR  "size" <> ? OR "mtime" <> ? OR "storage_mtime" <> ? OR  "encrypted" <> ? OR "etag" <> ? OR "permissions" <> ?  OR "checksum" <> ? OR "path_hash" IS NULL OR "path" IS NULL OR  "parent" IS NULL OR "name" IS NULL OR "mimepart" IS NULL OR "mimetype"  IS NULL OR "size" IS NULL OR "mtime" IS NULL OR "storage_mtime" IS NULL  OR "encrypted" IS NULL OR "etag" IS NULL OR "permissions" IS NULL OR  "checksum" IS NULL) AND "fileid" = ? ' with params  ["f4adb1bc5a0a5eb7955698e65055044c",  "files\/Openstack\/RVTools_tabvCD.csv", 2740, "RVTools_tabvCD.csv", 10,  11, 428529, "1506924557.501", 1508427421, 0, "59e8c69d61745", 27, null,  "f4adb1bc5a0a5eb7955698e65055044c",  "files\/Openstack\/RVTools_tabvCD.csv", 2740, "RVTools_tabvCD.csv", 10,  11, 428529, "1506924557.501", 1508427421, 0, "59e8c69d61745", 27, null,  3939]:  SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  invalid input  syntax for integer: "1506924557.501"
-- | --

</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by BODYA7979** [comment]
Hello, i have this and other similar bugs too, maybe related to webdav.

When creating folder:
![2017-10-21 14 58 13](https://user-images.githubusercontent.com/2007334/31851855-d04d9d10-b676-11e7-85f1-fdff1a174937.png)

When creating or uploading file have these errors:
![2017-10-21 14 59 42](https://user-images.githubusercontent.com/2007334/31851862-ea980142-b676-11e7-8e3a-c3709201a374.png)
![2017-10-21 15 01 00](https://user-images.githubusercontent.com/2007334/31851869-1d57eed0-b677-11e7-9abb-0c523243b8f3.png)

When editing txt file from web interface:
![2017-10-21 15 00 13](https://user-images.githubusercontent.com/2007334/31851866-0a560182-b677-11e7-8584-9552875833ca.png)

have no idea what causing this issues, can't work with this problems!


Server configuration
Operating system: Ubuntu 16.04
**Web server:**Apache 2.4.18
Database: MySQL 5.7.19
**PHP version:**7.1.10, also tried 5.6.31
Nextcloud version: 12.0.3
Updated from an older Nextcloud/ownCloud or fresh install: Updated from Nextcloud 11
Where did you install Nextcloud from: updated to nextcloud through updater from owncloud
<details>
  <summary>App list:</summary>
  Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - admin_notifications: 1.0.0
  - audioplayer: 2.2.0-alpha.3
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.6
  - checksum: 0.3.5
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_clipboard: 0.6.4
  - files_downloadactivity: 1.1.1
  - files_external: 1.3.0
  - files_external_sia: 0.1.2
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.1.1
  - files_reader: 1.0.4
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - groupfolders: 1.1.0
  - impersonate: 1.0.1
  - impress: true
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - metadata: 0.5.0
  - nextcloud_announcements: 1.1
  - nextnote: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ocdownloader: 1.5.4
  - ocsms: 1.12.1
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - quota_warning: 1.1.1
  - radio: 0.6.0
  - rainloop: 5.0.3
  - search_lucene: true
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - socialsharing_diaspora: 1.0.1
  - socialsharing_email: 1.0.1
  - socialsharing_facebook: 1.0.1
  - socialsharing_googleplus: 1.0.1
  - socialsharing_twitter: 1.0.1
  - spreed: 2.0.1
  - survey_client: 1.0.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - theming_customcss: 1.0.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.1
  - updatenotification: 1.2.0
  - user_external: 0.4
  - weather: 1.5.0
  - workflowengine: 1.2.0
</details>
<details>
<summary>
Config report:
</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "dbserver",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "cloud",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcached_servers": [
            [
                "127.0.0.1",
                11211
            ]
        ],
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "dbindex": 0
        },
        "enable_previews": true,
        "preview_max_filesize_image": "15",
        "enabledPreviewProviders": {
            "0": "OC\\Preview\\PNG",
            "1": "OC\\Preview\\JPEG",
            "2": "OC\\Preview\\GIF",
            "3": "OC\\Preview\\BMP",
            "6": "OC\\Preview\\TXT",
            "7": "OC\\Preview\\MarkDown",
            "14": "OC\\Preview\\PDF",
            "16": "OC\\Preview\\Font",
            "17": "OC\\Preview\\TIFF",
            "18": "OC\\Preview\\SVG"
        },
        "overwriteprotocol": "https",
        "ldapIgnoreNamingRules": false,
        "maintenance": false,
        "app.mail.server-side-cache.enabled": true,
        "appstore.experimental.enabled": true,
        "htaccess.RewriteBase": "\/",
        "log_rotate_size": 1000000000,
        "filesystem_check_changes": 1,
        "asset-pipeline.enabled": false,
        "debug": false,
        "singleuser": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable"
    }
}
</details>

Are you using external storage, if yes which one: none

Are you using encryption: no

Are you using an external user-backend, if yes which one: none

**Comment by BODYA7979** [comment]
update: found solution - I disabled an app "search_lucene" and all works properly

**Comment by catbou** [comment]
I don't have this app enabled so it has to be something else.

**Comment by blizzz** [comment]
@catbou what are your enabled apps? what's in the log?

**Comment by catbou** [comment]
Which log do you mean/need? I appended the error in the nextcloud log above. It's this one:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE "oc_filecache" SET "path_hash" = ?, "path" = ?, "parent" = ?, "name" = ?, "mimepart" = ?, "mimetype" = ?, "size" = ?, "mtime" = ?, "storage_mtime" = ?, "encrypted" = ?, "etag" = ?, "permissions" = ?, "checksum"=? WHERE ("path_hash" <> ? OR "path" <> ? OR "parent" <> ? OR "name" <> ? OR "mimepart" <> ? OR "mimetype" <> ? OR "size" <> ? OR "mtime" <> ? OR "storage_mtime" <> ? OR "encrypted" <> ? OR "etag" <> ? OR "permissions" <> ? OR "checksum" <> ? OR "path_hash" IS NULL OR "path" IS NULL OR "parent" IS NULL OR "name" IS NULL OR "mimepart" IS NULL OR "mimetype" IS NULL OR "size" IS NULL OR "mtime" IS NULL OR "storage_mtime" IS NULL OR "encrypted" IS NULL OR "etag" IS NULL OR "permissions" IS NULL OR "checksum" IS NULL) AND "fileid" = ? ' with params ["f4adb1bc5a0a5eb7955698e65055044c", "files/Openstack/RVTools_tabvCD.csv", 2740, "RVTools_tabvCD.csv", 10, 11, 428529, "1506924557.501", 1508427421, 0, "59e8c69d61745", 27, null, "f4adb1bc5a0a5eb7955698e65055044c", "files/Openstack/RVTools_tabvCD.csv", 2740, "RVTools_tabvCD.csv", 10, 11, 428529, "1506924557.501", 1508427421, 0, "59e8c69d61745", 27, null, 3939]: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "1506924557.501"


These are the enabled apps:
Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - onlyoffice: 1.1.4
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - user_ldap: 1.1.2
  - workflowengine: 1.1.1

**Comment by blizzz** [comment]
> Invalid text representation: 7 ERROR: invalid input syntax for integer: "1506924557.501"

For whatever reason the mtime is not an integer, but a float number. I guess you can do it for micro-precision, but I doubt we do it. Unless it comes from the filesystem?

@icewind1991

**Comment by MorrisJobke** [comment]
We haven't seen this since the last report here. I will close this ticket for now. If this is still happening we can look into this again.
