### ISSUE TITLE
Quota overwritten for ldap users if default is set in LDAP settings

### ISSUE THREAD

**Issue by Glosshead** [nextcloud/server#6886]
### Steps to reproduce
1. Set up default quota in LDAP settings
2. Sync users
3. Change quota for any of LDAP user
4. After time quota value will be overwritten with default parameter from LDAP settings

### Server configuration

**Operating system**: CentOS Linux release 7.4.1708 (Core)

**Web server:** nginx/1.13.6

**Database:** 10.2.9-MariaDB

**PHP version:** PHP 7.1.10

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-12.0.3.tar.bz2

**Comment by blizzz** [comment]
> Change quota for any of LDAP user

Locally, not on LDAP  I guess? Then, this works as it is intended. If you decide to control  the quote via LDAP, it can only be changed there, too. IIRC there is also a similar report.

**Comment by Glosshead** [comment]
@blizzz I wrote about local LDAP settings. I've set up a default quota value for LDAP users but for few of them needs more disk space than others. 

So I've expected that default quota value should have lower priority against the value that admin could set to user in Users settings.

**Comment by blizzz** [comment]
> So I've expected that default quota value should have lower priority against the value that admin could set to user in Users settings.

Nope, it is not tracked what the  source of settings is and would be a hell to do so. If you decide to control it via LDAP, you solely do it on LDAP. Local settings will then always be overwritten.

**Comment by MorrisJobke** [comment]
This can only be configured as an LDAP attribute. Setup the default LDAP quota and if you want to change the quota specify it in LDAP via an attribute itself.

**Comment by James9074** [comment]
Myself (and likely many others) have no access to write/modify my org's fairly large AD structure, so I'm constantly juggling and resetting quotas for people like this. Perhaps we could try and detect a quota outside the default for ldap and nextcloud's regular default and leave it be upon LDAP sync/login with an optional setting? 

[In this block](https://github.com/nextcloud/server/blob/9be6050cc42c2760bd2276942a24ba3db288b551/apps/user_ldap/lib/User/User.php#L522) (or line 530 below it) I'd grab the user's current quota and verify it's not the default or the Nextcloud default quota.

Thoughts on if that would wreck anything else, anyone?

**Comment by blizzz** [comment]
@James9074 then leave the quota attribute and default empty in the ldap config. then nextcloud native mechanism works again.

**Comment by James9074** [comment]
Oh wow, didn't realize that. Thanks!
