### ISSUE TITLE
Add LDAP expired password attribute check

### ISSUE THREAD

**Issue by espro** [nextcloud/server#6887]
This is an improvement request

Right now the only method for managing locked out LDAP accounts is via an OpenLDAP ppolicy. FreeIPA however utilizes 389DS and its password policy is limited to a Kerberos tree. However, users have attributes on them with timestamps which manage lockouts. It would be a simple thing for Nextcloud to allow an admin to define the user attribute which contains a lockout timestamp and disallow logins based on this.

E.g., "uid=jsmith,cn=users,cn=accounts,cn=ipa,cn=example,cn=com" has an attribute 'krbPasswordExpiration' which contains the value '20171020150000Z'.

Nextcloud could allow you to define an expired password attribute, and disallow access to an account if the current time is later than the attribute. For flexibility a datestamp format string could be defined in another field to allow matching a greater variety of attributes

**Comment by blizzz** [comment]
> Nextcloud could allow you to define an expired password attribute, and disallow access to an account if the current time is later than the attribute. 

Actually, the LDAP server should deny bind (login) in that case.

**Comment by espro** [comment]
FreeIPA does not limit binding in the case of its Kerberos attributes as a bind is required to update a password when an admin reset it. They have a [6-year old ticket](https://pagure.io/freeipa/issue/1539) about trying to figure out what they want to do about this. I don't expect this situation to change any time soon

**Comment by blizzz** [comment]
🙈 nevertheless the authentication is something the server should do. Adding this to Nextcloud would be a hack and not a proper solution. Of course it is a pity that they are stuck for about 6 years with that problem :(

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by blizzz** [comment]
As said with https://github.com/nextcloud/server/issues/6887#issuecomment-339267112 I do not think the solution is us implementing what FreeIPA should do → closing.
