### ISSUE TITLE
Excluding Directories and Blacklisting Files on Nextcloud

### ISSUE THREAD

**Issue by tujian** [nextcloud/server#6888]
Hello,

I would like to exclude directories for file:scan command in nextcloud, but found out this is available in owncloud only.

As stated in the [owncloud manual](https://doc.owncloud.org/server/latest/admin_manual/configuration/server/excluded_blacklisted_files.html),

> Impact on System Performance
If you have a filesystem mounted with 200,000 files and directories and 15 snapshots in rotation, you would now scan and process 200,000 elements plus 200,000 x 15 = 3,000,000 elements additionally. These additional 3,000,000 elements, 15 times more than the original quantity, would also be available for viewing and synchronisation. Because this is a big and unnecessary overhead, most times confusing to clients, further processing can be eliminated by using excluded directories.

this is a essential functionality for such use case.

More discussions could be found in [owncloud issue](https://github.com/owncloud/core/pull/15478).

It would be great if there is a plan on implementing this. Thanks!

**Comment by blizzz** [comment]
@icewind1991

**Comment by tujian** [comment]
Any update on this issue? Will there be any schedule?

**Comment by blizzz** [comment]
@icewind1991 can tell something substantial about it, he's on vacation for now however.

**Comment by icewind1991** [comment]
https://github.com/nextcloud/files_excludedirs handles this

**Comment by kzhui125** [comment]
@icewind1991 it doesn't work.

**Comment by helmut72** [comment]
> https://github.com/nextcloud/files_excludedirs handles this

You should reopen this issue because files_excludedirs doesn't work with newer Nextcloud versions.

**Comment by blizzz** [comment]
@helmut72 https://github.com/nextcloud/files_excludedirs/issues/7

**Comment by NickBolles** [comment]
Did anyone find a solution for this with newer nextcloud versions? I want to ignore my `node_modules` folders because they make file scans take forever and I don't care about them in nextcloud.

**Comment by LucaNerlich** [comment]
> 
> 
> Did anyone find a solution for this with newer nextcloud versions? I want to ignore my `node_modules` folders because they make file scans take forever and I don't care about them in nextcloud.

did you ever figure out a solution? adding 'node_modules' to the ignore files list in the windows app doesnt seem to work.

**Comment by GRArmstrong** [comment]
Would also be keen to see a solution to this problem, got Nextcloud on my Synology NAS and I have an external local directory which contains Synology's `@eaDir` directories. I'd like Nextcloud to not include them on the server.

**Comment by ikogan** [comment]
For me, nextcloud is having fun with recursive symbolic links and zfs snapshot directories. This exclude really is essential.

**Comment by GuyPaddock** [comment]
Please give this unsigned release a spin; should work on 23x.:
https://github.com/Inveniem/nextcloud-files-excludedirs/releases/tag/v1.0.0-beta

I've provided updated docs in my fork of the Readme (specifically, how it works with existing vs. newly-added files):
https://github.com/Inveniem/nextcloud-files-excludedirs/blob/master/README.md

Feedback is welcome here:
https://github.com/Inveniem/nextcloud-files-excludedirs/issues

I'll have to look into publishing an official, signed package because I wasn't the original author of this one -- I just updated the work of others.
