### ISSUE TITLE
App Metadata - Min Version Rename

### ISSUE THREAD

**Issue by Henni** [nextcloud/server#689]
Inside of the appinfo/info.xml there is the following code as [documented here](https://docs.nextcloud.com/server/10/developer_manual/app/info.html)
```xml
<owncloud min-version="6.0.4" max-version="8"/>
```
It would be great if this would be replaced with:
```xml
<nextcloud min-version="6.0.4" max-version="8"/>
```

This would allow app developers to set dependencies on *cloud versions depending on which of them is installed.

Example:
I would like to set the max-version for the [notes app](https://github.com/owncloud/notes), which should look like this:
```xml
<dependencies>
   <owncloud min-version="8.1" max-version="9.2"/>
   <nextcloud min-version="8.1" max-version="10.0"/>
</dependencies>
```

**Comment by icewind1991** [comment]
Master already supports this iirc

**Comment by schiessle** [comment]
We had the same idea before but decided to keep it the way it is for now, in order not to break compatibility with ownCloud.

Now we just map the versions to make sure to detect the dependencies correctly. https://github.com/nextcloud/server/pull/556

**Comment by MorrisJobke** [comment]
See https://github.com/nextcloud/server/pull/556#discussion_r72139010 for the discussion about the separate nextcloud tag
