### ISSUE TITLE
Get App PIN by normal login/rest call

### ISSUE THREAD

**Issue by gsantner** [nextcloud/server#6895]
Hi there, I tried to figure out how to programmatically get an App Pin, looked through docs and issues and didnt find anything so far. So I got an App which I want to authenticate to clients nextcloud. (And to use Notes API <https://github.com/nextcloud/notes/wiki/API-0.2>) Because I dont want to store the normal password I want to make sure that authentication works by an different revokeable password, therefore app pin.

So, how do I get such a pin programmatically now? I was looking for something to make an REST call to and get at successfull authentication (with normal username/password) an App PIN. 
So far I only found it doable by letting users manually go to their personal page do copy and paste...but this is not the solution. Can you give me details how to make this possible...without storing real password? 

### Server configuration

**Operating system**: Deb9

**Web server:** Apache2

**Database:**MySql

**PHP version:**7

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**not related

**Where did you install Nextcloud from:**archive

**Comment by blizzz** [comment]
@ChristophWurst

**Comment by ChristophWurst** [comment]
IIRC we don't have a programmatic way of obtaining an app password at the moment. There's an oauth2 app included in the Nextcloud server but I don't know how far that could be used for that either https://github.com/nextcloud/server/tree/master/apps/oauth2.

The only thing that *could* be helpful is the login flow mechanism we use for mobile devices where they authenticate in a web view and the application gets an app password on successful login. @rullzer could know more on that topic.

Also see https://github.com/nextcloud/server/pull/4704 for related tickets.

**Comment by rullzer** [comment]
Our new flow is really only something for native applications as you need to be able to register an url handler.

Now we could of course add an API that would return a new App Token. However, this API already won't work for people that have 2-factor-auth enabled. I do think it is good practice in this use case to have people generate a password.

Of cours such an endpoint could still be usefull to that 3rdpart desktop apps etc can make sure on first use to generate a new password.

@LukasReschke any opinion on this?

**Comment by gsantner** [comment]
"wont work for 2fa" --> how can even e.g. the Notes application work than? as it seems to only support user/pw

**Comment by rullzer** [comment]
Because the AppPassword are special passwords that do not require 2FA and they are limited in other ways.

**Comment by MorrisJobke** [comment]
> Now we could of course add an API that would return a new App Token. However, this API already won't work for people that have 2-factor-auth enabled. I do think it is good practice in this use case to have people generate a password.

Makes sense. I will close this ticket here then.
