### ISSUE TITLE
Error modifying file in External Storage (SMB)

### ISSUE THREAD

**Issue by jivarson** [nextcloud/server#6900]
### Steps to reproduce
1. Mount an external SMB-share to an NC 12.0.3-installation
2. Create a textfile
3. Try to overwrite file either through webdav or webgui.

### Expected behaviour
The file should be overwritten since permissions allows it

### Actual behaviour
Internal server error.
File isnt updated.
Neither from webgui nor webdav

### Server configuration

**Operating system**: OpenSuse Leap 42.2

**Web server:** Apache 2.4.23

**Database:** MariaDB 10.0.31

**PHP version:** 7.1.10

**Nextcloud version:** 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 12.0.2

**Where did you install Nextcloud from:** Installed from Official tarball, upgraded through webgui

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - audioplayer: 2.1.0
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.6
  - checksum: 0.3.5
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - deck: 0.2.4
  - drawio: 0.8.8
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_automatedtagging: 1.2.2
  - files_clipboard: 0.6.4
  - files_external: 1.3.0
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.7.3
  - metadata: 0.5.0
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - polls: 0.8.0
  - provisioning_api: 1.2.0
  - richdocuments: 1.12.35
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.1
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - telephoneprovider: 1.0.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.1
  - twofactor_u2f: 1.3.3
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - dashboard
  - encryption
  - end_to_end_encryption-only-files
  - federation
  - files_trashbin
  - firstrunwizard
  - keeweb
  - ocsms
  - password_policy
  - survey_client
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "<REMOVED>",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "<REMOVED>"
        ],
        "datadirectory": "\/srv\/www\/htdocs\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/<REMOVED>.org",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "ncdb",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "updater.release.channel": "stable",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "nextcloud",
        "mail_domain": "<REMOVED>",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2
    }
}

</details>

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

[Sun Oct 22 11:37:11.041277 2017] [authz_core:error] [pid 3755] [client 192.168.1.208:19109] AH01630: client denied by server configuration: /srv/www/htdocs/nextcloud/data/.ocdata
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

{"reqId":"ztlqIyTLmMZuxj1gwIFY","level":3,"time":"2017-10-22T09:37:22+00:00","remoteAddr":"192.168.1.208","user":"j0e","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/Dokument\/apa.txt","message":"renaming part file to final file failed ($run: true, $renameOkay: false, $fileExists: true)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.3.3"}
{"reqId":"ztlqIyTLmMZuxj1gwIFY","level":4,"time":"2017-10-22T09:37:22+00:00","remoteAddr":"192.168.1.208","user":"j0e","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/Dokument\/apa.txt","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Message\":\"Could not rename part file to final file\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1130): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #17)\\n#1 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->updateFile('Dokument\\\/apa.tx...', Resource id #17, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/remote.php(162): require_once('\\\/srv\\\/www\\\/htdocs...')\\n#8 {main}\",\"File\":\"\\\/srv\\\/www\\\/htdocs\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":188}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.3.3"}
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by blizzz** [comment]
@icewind1991

**Comment by thechonta** [comment]
Hello, Nextcloud 13 is out now but external Storages are unusable.
The only Version of Nextcloud that works as well with external Storages is Nextclout 11.
It is regardles of LDAP or direkt SMB share, it is not possible to sync an edited file.
Please someone repair this.

With kind regards

Chonta

**Comment by fafische** [comment]
I can not confirm this generally. When working direktly in external storage everythings works fine (NC13.0.1, local folder as external storage). 
But: when sharing an external folder it is not possible to share with permissions for edit or delete. Syncronising the share of an external folder will be a problem because of that.

**Comment by Orbital-Bit** [comment]
same issue reported in these posts; [8978](https://github.com/nextcloud/server/issues/8978)[8547](https://github.com/nextcloud/server/issues/8547)[9000](https://github.com/nextcloud/server/issues/9000)

**Comment by MorrisJobke** [comment]
> same issue reported in these posts; #8978, #8547, and #9000

Let's close then this one here as duplicate of one of the mentioned ones.

**Comment by MorrisJobke** [comment]
Let's continue this in #8978
