### ISSUE TITLE
NL translation issue + clarification for enforce password security

### ISSUE THREAD

**Issue by radoeka** [nextcloud/server#6902]
### Steps to reproduce
1.  Go to https://<server>/settings/admin/sharing
2. Language set to Dutch
3.

### Expected behaviour
Afdwingen wachtwoord beveiliging 
should be printed with spaces, not one long word

Perhaps some help text can be added, explaining what happens when this is enabled?
When/where is the password security enforced?  

### Actual behaviour
printed is: Afdwingenwachtwoordbeveiliging 

### Server configuration

**Operating system**: linux

**Web server:** apache

**Database:** sqlite3 

**PHP version:** 7.0.7

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** update

**Where did you install Nextcloud from:** nextcloud

**Comment by radoeka** [comment]
Found the string:
apps/sharebymail/l10n/nl.js:    "Enforce password protection" : "Afdwingenwachtwoordbeveiliging"

**Comment by tflidd** [comment]
It's handled in transifex. @rakekniven can you help?

**Comment by rakekniven** [comment]
Fixed string at Transifex. 
Option is forcing user to set password when sharing content by link via email.
