### ISSUE TITLE
Share link leaks owner user id and displayname

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/server#6904]
In the Webpage source code, I found data which should not be present when a nextcloud directory or file is shared via a shared link:

```data-owner-display-name="John Doe" data-owner="John Doe" data-name="thisDirectory"```

When sharing parts of a Nextcloud data area, Nextcloud should never leak any internal information.

**Comment by sphrak** [comment]
Can confirm this issue aswell on `12.0.3`. Agree this should not be shared.

**Comment by MorrisJobke** [comment]
This is also shown on the public share page and by intention to personalise and give the recipient context.

![bildschirmfoto 2017-10-24 um 13 48 21](https://user-images.githubusercontent.com/245432/31941411-048d6112-b8c2-11e7-9e0c-025241c8c2a3.png)

**Comment by Wikinaut** [comment]
I do no think, that a secure tool like Nextcloud should reveal the owner names to everyone whom you send a shared link.

Therefore I wish a public discussion about this issue.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers @rullzer @nickvergessen @LukasReschke @schiessle @karlitschek What do you think about this?

I tend to say, that if you share something with somebody the other person should see that this is from me and give the recipient this context. If you don't want that to be exposed, then use a password protected share or don't enter you real name into Nextcloud.

**Comment by skjnldsv** [comment]
I agree that leaking the username is a security flaw. Display the real name would be fine. Reveal nothing is best. Why do we have those info here?

**Comment by Wikinaut** [comment]
@MorrisJobke When you post a shared link on for example Twitter, you don't want tell the world your real name. I would really like to see a broader discussion here. It was a good idea to fork from owncloud, and now we can listen to users and developers, please keep listening to the users.

@LukasReschke Please state your view as a security-aware person. I personally regard it as an #epicfail if internal data can be seen on a shared-link webpage.

**Comment by nickvergessen** [comment]
Just for the record, if at all this is a privacy issue, not a security issue.

But then again, you got the link from that person or another one. Why should the name be a secret?

Showing the name was added by morris, reviewed by lukas, so I guess opinions are good:
https://github.com/nextcloud/server/pull/5827

**Comment by skjnldsv** [comment]
Hum, the username isn't really leaked. It's just that a new user have its Full name set to its username by default (until changed by the user itself).

**Comment by Wikinaut** [comment]
@skjnldsv  It _is_ the username.

```data-owner-display-name="John Doe" data-owner="John Doe" data-name="thisDirectory"```

**Comment by skjnldsv** [comment]
No, it's the Full name. You can't connect with "John Doe".

**Comment by Wikinaut** [comment]
@nickvergessen I agree, that it is an privacy issue, but as there is no Privacy label and I did not wanted to add such a label., I decided for Security.

**Comment by Wikinaut** [comment]
@skjnldsv Wrong, I *can* !!!!

**Comment by Wikinaut** [comment]
@skjnldsv I have a migrated-owncloud-installation and I have usernames with spaces in it.

**Comment by nickvergessen** [comment]
Doesn't matter, user ids are not a secret per se. As mentioned above we use this to reduce the user fraud risk a bit. Also you know the user somewhat because they shared the link with you, so I don't really see a huge problem here.

Also you could have merged those 3 comments into one...

Anyway

**Comment by enoch85** [comment]
> can !!!!

Wow, harsh.

**Comment by jancborchardt** [comment]
Yeah, can only agree with the comments above. It's very important for context where the link actually comes from. We do this for file drop (upload only) shares also, even with avatar. It helps make Nextcloud more appealing and useful as an alternative for a broader audience.
