### ISSUE TITLE
how to share folders to few users using  mysql?

### ISSUE THREAD

**Issue by m1cka** [nextcloud/server#6907]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
there is possible make sharing in mysql cli? i want to share ~200 diff folders to few users, by clicking in web, it takes a lot of time.

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**: centos 7.4

**Web server:** apache

**Database:** mysq-5.7

**PHP version:** 7.1

**Nextcloud version:** latest

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Comment by rullzer** [comment]
You can use the share API: https://docs.nextcloud.com/server/12/developer_manual/core/ocs-share-api.html
