### ISSUE TITLE
Don't register logrotate on each request

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#6909]
In base.php for each and every single request we try to add a logrotate job. See https://github.com/nextcloud/server/blob/master/lib/base.php#L873

If you have enabled log rotate this results in an extra query per requests (to see if the job is already inserted).

Proposal:

* Get rid of the code
* Add an `./occ` command to enable/disable logrotate
* Add an command on the admin page to enable/disable logrotate

**Comment by MorrisJobke** [comment]
Better proposal:

* add it to a general info.xml like all the background jobs for normal apps 😉

**Comment by rullzer** [comment]
There is no general info.xml ;)

But we could just add it on install and inert it with a repair step. And be done with it...
