### ISSUE TITLE
Please reopen issue 5107 Privacy enhancements for contacts menu

### ISSUE THREAD

**Issue by lamixer** [nextcloud/server#6912]
Please reopen issue 5107 Privacy enhancements for contacts menu

it is not solved and is a major privacy issue for some users of Nextcloud. Thank you.

**Comment by blizzz** [comment]
The fix is merged and will be release with 12.0.4 https://github.com/nextcloud/server/pull/6554

If it does not fix your issue, please feel free to open a new issue.

**Comment by lamixer** [comment]
Thanks ... sorry I didn't follow the progress of the issue and fix correctly. I'm glad the fix is coming soon.
