### ISSUE TITLE
Config Param 'overwritecondaddr' not working

### ISSUE THREAD

**Issue by ghmax** [nextcloud/server#6914]
### Steps to reproduce
1. clean install nextcloud
2. add conditional overwrite settings to config.php 
   'overwritehost' => 'my.domain.com',
   'overwritecondaddr' => '^192\.168\.0\.1$',

### Expected behaviour
Hostname should be overwritten when request comes in via 192.168.0.1, otherwise NOT.

### Actual behaviour
Hostname is always overwritten

### Server configuration

**Operating system**:
official Docker Image on different Docker Hosts

**Nextcloud version:** (see Nextcloud admin page)
12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Where did you install Nextcloud from:**
docker

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => '192.168.99.100:9000',
  ),
  'datadirectory' => '/var/www/html/data',
  'overwrite.cli.url' => 'http://192.168.99.100:9000',
  'dbtype' => 'sqlite3',
  'version' => '12.0.3.3',
  'installed' => true,
  
   'overwritecondaddr' => '^192\.168\.99\.11$',
   'overwritehost' => 'my.domain.com',
  
);
```
</details>

### Code causing Troubles...
Problem is in File .../lib/private/AppFramework/Http/Request.php in Method 'private function isOverwriteCondition($type = '')' ... type is empty when checking for e.g. Host-Override in Method 'getOverwriteHost' ... so with empty type check override method (isOverwriteCondition) always returns true cause of:

...
return $regex === '//' || preg_match($regex, $remoteAddr) === 1 || $type !== 'protocol';
...

-> type === '' ... so $type !== 'protocol' is always true ... so method always returns true in this case.

**Comment by blizzz** [comment]
>  'overwritecondaddr' => '^192.168.0.1$',

dots are not escaped. Please have a second look at the doc

```
/**
 * This option allows you to define a manual override condition as a regular
 * expression for the remote IP address. For example, defining a range of IP
 * addresses starting with ``10.0.0.`` and ending with 1 to 3:
 * ``^10\.0\.0\.[1-3]$``
```

Does it help?

**Comment by ghmax** [comment]
Hello,

no - that does not help. I already 'dotted' the 'overwritecondaddr' => '^192\.168\.99\.11$',

Look at the code in https://github.com/nextcloud/server/blob/master/lib/private/AppFramework/Http/Request.php -- there is the expression: $this->isOverwriteCondition() with empty params within getOverwriteHost() -- which always returns true - what is not what we should expect... (in my understanding)

	/**
	 * Check overwrite condition
	 * @param string $type
	 * @return bool
	 */
	private function isOverwriteCondition($type = '') {
		$regex = '/' . $this->config->getSystemValue('overwritecondaddr', '')  . '/';
		$remoteAddr = isset($this->server['REMOTE_ADDR']) ? $this->server['REMOTE_ADDR'] : '';
		return $regex === '//' || preg_match($regex, $remoteAddr) === 1
		|| $type !== 'protocol';
	}

so a call to:

	/**
	 * Returns the overwritehost setting from the config if set and
	 * if the overwrite condition is met
	 * @return string|null overwritehost value or null if not defined or the defined condition
	 * isn't met
	 */
	private function getOverwriteHost() {
		if($this->config->getSystemValue('overwritehost') !== '' && $this->isOverwriteCondition()) {
			return $this->config->getSystemValue('overwritehost');
		}
		return null;
	}

always returns the configured value and so hostname replacement always takes place. Even if it should not be the case.

**Comment by blizzz** [comment]
@LukasReschke ^

**Comment by mxvin** [comment]
Alright then, anybody can make some hotfixes according this bugs? ;)

**Comment by danielwbn** [comment]
I think two things need to be fixed here:

1. what @ghmax described, $this->isOverwriteCondition() will ALWAYS return True

**Comment by blizzz** [comment]
@danielwbn you can simply drop ``|| $type !== 'protocol'``. It was a left over when the forcessl option was removed, which was an essential part of that check. It should all have gone.

**Comment by kylemart** [comment]
I'm surprised this hasn't been addressed already. Is anyone working on this, or should I take a swing at it?

**Comment by blizzz** [comment]
> I'm surprised this hasn't been addressed already. Is anyone working on this, or should I take a swing at it?

Please :)

**Comment by Petersoj** [comment]
+1
I sometimes want to access my Nextcloud instance on my LAN instead of through my reverse proxy!

**Comment by Nero10578** [comment]
Is this still not fixed? Having a headache changing this and that trying to be able to access my nextcloud via LAN IP and also through my nginx reverse proxy for WAN connections. Problem is my ISP modem isn't allowing loopback so to access my own nextcloud I have to freaking use a VPN and access through my domain for WAN access through nginx.

**Comment by pavelkryl** [comment]
Guys, we've got 2022, and this 4-year old bug is still there? Could someone have a look at it?

**Comment by pavelkryl** [comment]
Could I get access to your repo to be able to push a branch/pull request with a fix?

Note: why was my yesterday comment marked as 'spam'

**Comment by blizzz** [comment]
> Could I get access to your repo to be able to push a branch/pull request with a fix?

You don't need to have push access to create a pull request. You can do the changes in your fork and open a PR against this repo. You'll be invited nevertheless.

> Note: why was my yesterday comment marked as 'spam'

The content of the comment was not exactly providing value to this issue. The commandeering question (as i perceived it) was rude. Open source software means to make the software work for you needs and contribute back the enhancements or fixed, but not demanding work done.

**Comment by pavelkryl** [comment]
> You don't need to have push access to create a pull request. You can do the changes in your fork and open a PR against this repo. You'll be invited nevertheless.
 

Thanks for the instructions, I've just created the PR, so I would be pleased if somebody can have a look at it.

> The content of the comment was not exactly providing value to this issue. The commandeering question (as i perceived it) was rude. Open source software means to make the software work for you needs and contribute back the enhancements or fixed, but not demanding work done.

Well, I don't see much difference between @Nero10578's last comment and mine. But that's not important, I guess.

**Comment by blizzz** [comment]
> Well, I don't see much difference between @Nero10578's last comment and mine. But that's not important, I guess.

Fixed ;)

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by Nihlus** [comment]
This remains an issue for me on 25.0.4.

**Comment by gulyo** [comment]
Hey All,
I confirm the issue exists in 26.0.1.1

**Comment by nosalorenz** [comment]
+1. The issue still exists also in NC 27!

**Comment by nosalorenz** [comment]
I still have this issue!
