### ISSUE TITLE
webDAV search : crash iOS Parser

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/server#6925]
I have a issue with NC 12.0.3 with external resource, this is the response

```
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:card="urn:ietf:params:xml:ns:carddav" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
	<d:response>
		<d:href>/remote.php/dav/files/marino.faggiana//testNCADMIN//</d:href>
		<d:propstat>
			<d:prop>
				<d:resourcetype>
					<d:collection />
				</d:resourcetype>
				<oc:fileid>188712</oc:fileid>
				<d:getetag>&quot;59ede801b4487&quot;</d:getetag>
				<oc:size>172071</oc:size> 

```

Response : **//testNCADMIN//** ??? why //

@icewind1991 @mario can you make a test ?

**Comment by rullzer** [comment]
While it is weird. And we should look into it. This should also be handled properly by the IOS parser.

**Comment by marinofaggiana** [comment]
@rullzer all the old driver owncloud is to rewrite .... bur for now this is the parser ...

**Comment by marinofaggiana** [comment]
@rullzer news here ?

**Comment by skjnldsv** [comment]
Still happening ? :)

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
