### ISSUE TITLE
Tag all releases, also in the stable branch

### ISSUE THREAD

**Issue by gioele** [nextcloud/server#6937]
The current stable release, version `12.0.3.3`, does not appear in the [list of releases on GitHub](https://github.com/nextcloud/server/releases), nor in the [list of tags in the Git repository](https://github.com/nextcloud/server/tags) or in the [changelog](https://nextcloud.com/changelog/).

Could you please tag also micro relases, at least in the Git repository?

Tagging micro releases creates a simple machine-readable list of actual versions that can be used in various tools to check (passively) if local installations are up to date or packages need to be rebuilt.

**Comment by nickvergessen** [comment]
You have to look for 3 numbers only. 12.0.3 is the visual version number and therefor the tag name: https://github.com/nextcloud/server/releases/tag/v12.0.3

the last `.3` is just the internal number. It's increased everytime a background job, repair step or anything else regarding the database or some other systems changed.

**Comment by gioele** [comment]
hi @nickvergessen, my problem is that I'd like to receive a notification from our notification system whenever any update is available. Without a tag or something like this this is not possible.

Or are you suggesting that these micro versions can simply be ignored and not installed?

**Comment by nickvergessen** [comment]
Yes ignore the micro version. The are not part of our release number. There is only one released 12.0.3 version, and its internal version number is 12.0.3.3
