### ISSUE TITLE
Appstore disappears / cURL error 28: Connection timed out after 10001 

### ISSUE THREAD

**Issue by msrv** [nextcloud/server#6938]
### Steps to reproduce
1. Go to Apps page
2. Try to find the Appstore
3. Appstore is missing

### Expected behaviour
Appstore should show

### Actual behaviour
Appstore missing, Log shows error: cURL error 28: Connection timed out after 10001 

### Server configuration

**Operating system**: Debian 9.2

**Web server:** Apache 2.4.25

**Database:** Mariadb 10.1.26 (Debian)

**PHP version:** 7.0

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install: Fresh install

**Where did you install Nextcloud from:** zip archive

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**
<details>
<summary>
Enabled:
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - sharebymail: 1.2.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - activity
  - admin_audit
  - comments
  - encryption
  - federation
  - files_external
  - firstrunwizard
  - serverinfo
  - survey_client
  - systemtags
  - theming
  - user_external
  - user_ldap
</summary>
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***"
        ],
        "datadirectory": "\/srv\/nx-data\/",
        "overwrite.cli.url": "***",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
    }
}

```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

### Client configuration
**Browser:** Chome latest

**Operating system:** Windows 10 FCU

#### Web server error log
<details>
<summary>No error shown</summary>
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
GuzzleHttp\Exception\ConnectException: cURL error 28: Connection timed out after 10001 milliseconds
/srv/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 103: GuzzleHttp\Exception\RequestException wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\ConnectException))
/srv/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
/srv/www/nextcloud/3rdparty/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
/srv/www/nextcloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
/srv/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
/srv/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
/srv/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 165: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
/srv/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125: GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
/srv/www/nextcloud/lib/private/Http/Client/Client.php - line 138: GuzzleHttp\Client->get('https //apps.ne...', Array)
/srv/www/nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php - line 99: OC\Http\Client\Client->get('https //apps.ne...', Array)
/srv/www/nextcloud/lib/private/App/AppStore/Fetcher/AppFetcher.php - line 66: OC\App\AppStore\Fetcher\Fetcher->fetch('', '')
/srv/www/nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php - line 162: OC\App\AppStore\Fetcher\AppFetcher->fetch('', '')
/srv/www/nextcloud/lib/private/Installer.php - line 394: OC\App\AppStore\Fetcher\Fetcher->get()
/srv/www/nextcloud/settings/Controller/AppSettingsController.php - line 312: OC\Installer isUpdateAvailable('files_versions', Object(OC\App\AppStore\Fetcher\AppFetcher))
[internal function] OC\Settings\Controller\AppSettingsController->listApps('enabled')
/srv/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/srv/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Settings\Controller\AppSettingsController), 'listApps')
/srv/www/nextcloud/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Settings\Controller\AppSettingsController), 'listApps')
/srv/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OC\\Settings\\Con...', 'listApps', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/srv/www/nextcloud/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/srv/www/nextcloud/lib/base.php - line 1004: OC\Route\Router->match('/settings/apps/...')
/srv/www/nextcloud/index.php - line 48: OC handleRequest()
{main}
```
</details>

**Comment by mathong** [comment]
API is down :( 
```
$ curl -I https://apps.nextcloud.com/api/v1/categories.json
HTTP/1.1 503 Service Unavailable
$  curl -I https://apps.nextcloud.com/
HTTP/1.1 200 OK
```

**Comment by MorrisJobke** [comment]
cc @LukasReschke :/

**Comment by Raindeer44** [comment]
I'm getting the same problem on my Nextcloud server, and I get the same `503` from the API.

**Comment by nickvergessen** [comment]
This happened last week as well. A restart helped.

Maybe the appstore needs a different fix...

**Comment by nickvergessen** [comment]
@MorrisJobke any idea?
```irc
[16:40:35] <BernhardPosselt> nickvergessen: you guys need to do a deployment
[16:41:26] <BernhardPosselt> nickvergessen: that error is already fixed btw
[16:42:12] <BernhardPosselt> nickvergessen: reason is that there are now enough apps for the performance bug to cause time outs
```

**Comment by kao98** [comment]
I'm getting the same error right now.

https://apps.nextcloud.com/api/v1/platform/12.0.3/apps.json seems to be down.

**Comment by kao98** [comment]
As we're waiting the appstore to be fixed, as a workaround, is there a manual way to install apps?

**Comment by Wikinaut** [comment]
Same error here. Please fix.

**Comment by eppfel** [comment]
@kao98 You can always install the apps by downloading it to your installations /apps folder. Some might to build before, but most work out of the box. Check the respective github pages. Normally you find those from the appstore: https://apps.nextcloud.com/

**Comment by eppfel** [comment]
As for the error, I feel at least we should catch the error properly and display a mesage: Not able to reach the appstore right now.
... or something.

**Comment by jospoortvliet** [comment]
I created an issue for our sysadmin team to deploy the latest version of the app store as @BernhardPosselt suggested on IRC 🎉

**Comment by MorrisJobke** [comment]
Appstore was updated and brought back online. Everything should work now.
