### ISSUE TITLE
Cannot specify last name in Contacts

### ISSUE THREAD

**Issue by jellium** [nextcloud/server#694]
Please see https://github.com/nextcloud/server/issues/688 for my config.

The "N" vCard field (which stands for name as in last name) of new contacts is empty when exporting the address book as a vcf file. The contact name, even though it is written as Firstname Lastname is exported solely in the "FN" field (which stands for first name).

As a consequence, using CardDav instance or directly importing the vcf file elsewhere than in Nextcloud results in a wrong displayed name as opposed to the one displayed in the Contacts application within Nextcloud.

Thanks for all the work and wonderfull app. I hope the above information are enough to make a point.

**Comment by phsc** [comment]
This is already fixed in the contacts app itself (see https://github.com/owncloud/contacts/pull/437). Unfortunately, there was no official contacts app release since this fix. I'm also waiting for this feature, but would prefer to use an official release instead of git master.

**Comment by nickvergessen** [comment]
Closing as per above
