### ISSUE TITLE
Upgrade button missing for app with upgrade notification

### ISSUE THREAD

**Issue by freeeflyer** [nextcloud/server#6948]
### Steps to reproduce
1. Wait for app upgrade notification
2. Click to get to app list

### Expected behaviour
Application on list should show an upgrade button.

### Actual behaviour
Application does not show upgrade button.

### Server configuration

**Operating system**:
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

**Web server:**
apache2                            2.4.29-0.1+ubuntu14.04.1+deb.sury.org+2

**Database:**
postgresql-9.1                     9.1.14-0ubuntu0.12.04

**PHP version:**
libapache2-mod-php7.0              7.0.24-1+ubuntu14.04.1+deb.sury.org+1

**Nextcloud version:** (see Nextcloud admin page)
12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated regularly from owncloud 7

**Where did you install Nextcloud from:**
Tar gz

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.5
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - gpxedit: 0.0.7
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ocsms: 1.12.1
  - ownbackup: 17.5.0
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - richdocuments: 1.12.35
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "513a41c01c4fb",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/production\/cloud.xoop.org-ssl\/data",
        "dbtype": "pgsql",
        "version": "12.0.3.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "loglevel": 1,
        "theme": "",
        "trusted_domains": [
            "cloud.xoop.org"
        ],
        "mail_smtpmode": "php",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "appcodechecker": true,
        "updatechecker": true,
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
        "has_internet_connection": true,
        "check_for_working_webdav": true,
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/api.nextcloud.com\/v1",
        "apps_paths": [
            {
                "path": "\/var\/www\/production\/cloud.xoop.org-ssl\/www\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/production\/cloud.xoop.org-ssl\/www\/apps2",
                "url": "\/apps2",
                "writable": true
            }
        ],
        "customclient_desktop": "https:\/\/nextcloud.com\/install\/#install-clients",
        "customclient_android": "https:\/\/play.google.com\/store\/apps\/details?id=com.nextcloud.client",
        "customclient_ios": "https:\/\/itunes.apple.com\/us\/app\/nextcloud\/id1125420102?mt=8",
        "overwrite.cli.url": "https:\/\/cloud.xoop.org"
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
srware iron Version 61.0.3200.0 (Build de développement) (64 bits)

**Operating system:**
Mac OS 10.13
#### Web server error log
<details>
<summary>Web server error log</summary>

```
83.201.114.154 - - [25/Oct/2017:08:36:20 +0200] "GET /index.php/settings/apps HTTP/1.1" 200 5929 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3200.0 Iron Safari/537.36"
83.201.114.154 - - [25/Oct/2017:08:36:21 +0200] "GET /index.php/core/js/oc.js?v=d700134cb65f07e91bab941338982664 HTTP/1.1" 200 4550 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3200.0 Iron Safari/537.36"
83.201.114.154 - - [25/Oct/2017:08:36:21 +0200] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1410 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3200.0 Iron Safari/537.36"
83.201.114.154 - - [25/Oct/2017:08:36:21 +0200] "GET /index.php/settings/apps/list?category=installed HTTP/1.1" 200 61270 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3200.0 Iron Safari/537.36"
83.201.114.154 - - [25/Oct/2017:08:36:21 +0200] "GET /index.php/settings/apps/categories HTTP/1.1" 200 2007 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3200.0 Iron Safari/537.36"```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"7fZpBO5purJfkp6wX59h","level":3,"time":"2017-10-25T06:34:50+00:00","remoteAddr":"83.201.114.154","user":"freeflyer","app":"appstoreFetcher","method":"GET","url":"\/index.php\/settings\/apps\/list?category=installed","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\ConnectException\",\"Message\":\"cURL error 28: Connection timed out after 10000 milliseconds\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(103): GuzzleHttp\\\\Exception\\\\RequestException::wrapException(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Ring\\\\Exception\\\\ConnectException))\\n#1 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#2 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/3rdparty\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(25): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n#3 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#4 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#5 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(134): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#6 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(165): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#7 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(125): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#8 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/lib\\\/private\\\/Http\\\/Client\\\/Client.php(138): GuzzleHttp\\\\Client->get('https:\\\/\\\/apps.ne...', Array)\\n#9 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/lib\\\/private\\\/App\\\/AppStore\\\/Fetcher\\\/Fetcher.php(99): OC\\\\Http\\\\Client\\\\Client->get('https:\\\/\\\/apps.ne...', Array)\\n#10 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/lib\\\/private\\\/App\\\/AppStore\\\/Fetcher\\\/AppFetcher.php(66): OC\\\\App\\\\AppStore\\\\Fetcher\\\\Fetcher->fetch('\\\"2017-10-22 00:...', '[{\\\"id\\\":\\\"contact...')\\n#11 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/lib\\\/private\\\/App\\\/AppStore\\\/Fetcher\\\/Fetcher.php(162): OC\\\\App\\\\AppStore\\\\Fetcher\\\\AppFetcher->fetch('\\\"2017-10-22 00:...', '[{\\\"id\\\":\\\"contact...')\\n#12 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/lib\\\/private\\\/Installer.php(394): OC\\\\App\\\\AppStore\\\\Fetcher\\\\Fetcher->get()\\n#13 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/settings\\\/Controller\\\/AppSettingsController.php(291): OC\\\\Installer::isUpdateAvailable('nextcloud_annou...', Object(OC\\\\App\\\\AppStore\\\\Fetcher\\\\AppFetcher))\\n#14 [internal function]: OC\\\\Settings\\\\Controller\\\\AppSettingsController->listApps('installed')\\n#15 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#16 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\AppSettingsController), 'listApps')\\n#17 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\AppSettingsController), 'listApps')\\n#18 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Settings\\\\\\\\Con...', 'listApps', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#19 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#20 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#21 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/settings\\\/apps\\\/...')\\n#22 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/index.php(48): OC::handleRequest()\\n#23 {main}\",\"File\":\"\\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":49}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3200.0 Iron Safari\/537.36","version":"12.0.3.3"}
{"reqId":"HNxhF72yaqkBJnsnKWNu","level":3,"time":"2017-10-25T06:34:50+00:00","remoteAddr":"83.201.114.154","user":"freeflyer","app":"appstoreFetcher","method":"GET","url":"\/index.php\/settings\/apps\/categories","message":"Exception: {\"Exception\":\"GuzzleHttp\\\\Exception\\\\ConnectException\",\"Message\":\"cURL error 28: Operation timed out after 0 milliseconds with 0 out of 0 bytes received\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(103): GuzzleHttp\\\\Exception\\\\RequestException::wrapException(Object(GuzzleHttp\\\\Message\\\\Request), Object(GuzzleHttp\\\\Ring\\\\Exception\\\\ConnectException))\\n#1 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(132): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#2 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/3rdparty\\\/react\\\/promise\\\/src\\\/FulfilledPromise.php(25): GuzzleHttp\\\\RequestFsm->GuzzleHttp\\\\{closure}(Array)\\n#3 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/3rdparty\\\/guzzlehttp\\\/ringphp\\\/src\\\/Future\\\/CompletedFutureValue.php(55): React\\\\Promise\\\\FulfilledPromise->then(Object(Closure), NULL, NULL)\\n#4 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Message\\\/FutureResponse.php(43): GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureValue->then(Object(Closure), NULL, NULL)\\n#5 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/RequestFsm.php(134): GuzzleHttp\\\\Message\\\\FutureResponse::proxy(Object(GuzzleHttp\\\\Ring\\\\Future\\\\CompletedFutureArray), Object(Closure))\\n#6 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(165): GuzzleHttp\\\\RequestFsm->__invoke(Object(GuzzleHttp\\\\Transaction))\\n#7 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Client.php(125): GuzzleHttp\\\\Client->send(Object(GuzzleHttp\\\\Message\\\\Request))\\n#8 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/lib\\\/private\\\/Http\\\/Client\\\/Client.php(138): GuzzleHttp\\\\Client->get('https:\\\/\\\/apps.ne...', Array)\\n#9 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/lib\\\/private\\\/App\\\/AppStore\\\/Fetcher\\\/Fetcher.php(99): OC\\\\Http\\\\Client\\\\Client->get('https:\\\/\\\/apps.ne...', Array)\\n#10 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/lib\\\/private\\\/App\\\/AppStore\\\/Fetcher\\\/Fetcher.php(162): OC\\\\App\\\\AppStore\\\\Fetcher\\\\Fetcher->fetch('\\\"2017-05-26 04:...', '[{\\\"id\\\":\\\"auth\\\",\\\"...')\\n#11 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/settings\\\/Controller\\\/AppSettingsController.php(139): OC\\\\App\\\\AppStore\\\\Fetcher\\\\Fetcher->get()\\n#12 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/settings\\\/Controller\\\/AppSettingsController.php(157): OC\\\\Settings\\\\Controller\\\\AppSettingsController->getAllCategories()\\n#13 [internal function]: OC\\\\Settings\\\\Controller\\\\AppSettingsController->listCategories()\\n#14 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#15 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\AppSettingsController), 'listCategories')\\n#16 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\AppSettingsController), 'listCategories')\\n#17 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Settings\\\\\\\\Con...', 'listCategories', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#18 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#19 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#20 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/settings\\\/apps\\\/...')\\n#21 \\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/index.php(48): OC::handleRequest()\\n#22 {main}\",\"File\":\"\\\/var\\\/www\\\/production\\\/cloud.xoop.org-ssl\\\/www\\\/3rdparty\\\/guzzlehttp\\\/guzzle\\\/src\\\/Exception\\\/RequestException.php\",\"Line\":49}","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_13_0) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3200.0 Iron Safari\/537.36","version":"12.0.3.3"}
```
</details>

![capture d ecran 2017-10-25 a 08 20 41](https://user-images.githubusercontent.com/12149490/31983925-bc877fb2-b95f-11e7-9a8b-cc3bb2487039.png)

**Comment by freeeflyer** [comment]
![capture d ecran 2017-10-25 a 08 20 41](https://user-images.githubusercontent.com/12149490/31983955-d0603042-b95f-11e7-840f-cae6dcfbb5b6.png)

**Comment by nickvergessen** [comment]
Can you inspect the HTML whether this is a problem of overlapping buttons

**Comment by freeeflyer** [comment]
Sorry I cannot do it anymore it has just become ok. Maybe a cache issue..
