### ISSUE TITLE
_onShow is not called on FileList objects from plugins the first time they are shown

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#6955]
While reviewing #6869 I have noticed that [`_onShow`](https://github.com/nextcloud/server/blob/f392e78d5b525abbb04057b91c0adfba212c00c4/apps/files/js/filelist.js#L566) is not called on `FileList` objects from plugins the first time they are shown.

`_onShow` is set as a handler for the `show` event in [the _constructor_ (so to speak) of `FileList`](https://github.com/nextcloud/server/blob/f392e78d5b525abbb04057b91c0adfba212c00c4/apps/files/js/filelist.js#L336). However, _FileList_ objects in plugins are not created until the `show` event is triggered on their placeholder HTML element for the first time (see, for example, [_RecentPlugin_](https://github.com/nextcloud/server/blob/2e3114cc28b44468d449838c3b75ed7e4e5decea/apps/files/js/recentplugin.js#L27) or [_TrashBin_](https://github.com/nextcloud/server/blob/6c5696d3a84ff71fc5ddb53b490bbc77f5c119f5/apps/files_trashbin/js/app.js#L102)).

Since #4693 `reload` is not called on the file lists the first time `_onShow` is called, which together with `_onShow` not being called the first time the file list is shown causes `reload` (and, since #6683, `_setCurrentDir`) not being called the second time that the file list is shown (read it slowly, it makes sense :-P ).

The page title is set by [`setPageTitle`](https://github.com/nextcloud/server/blob/f392e78d5b525abbb04057b91c0adfba212c00c4/apps/files/js/filelist.js#L903), which is called from [`_setCurrentDir`](https://github.com/nextcloud/server/blob/f392e78d5b525abbb04057b91c0adfba212c00c4/apps/files/js/filelist.js#L1575-L1580) (the `if` clause is not really needed because `undefined` and an empty string are the same for `setPageTitle`, but that is a different matter :-P ). _RecentPlugin_ and _TrashBin_ rely on `_setCurrentDir` being called when shown for the page title to be set (either directly or, in the case of _RecentPlugin_, through [`reload`](https://github.com/nextcloud/server/blob/2139a031e706e256eee1e4f8cfc6cea06cf8cb9f/apps/files/js/recentfilelist.js#L80)), but all the above causes the page title to not be set in the following scenario:

1. Open the Files app
2. Click on _Recents_ on the navigation bar
3. Click on _All files_ on the navigation bar
4. Click again on _Recents_ on the navigation bar

The page title would not be set either if _Deleted files_ was clicked the two times instead of _Recents_. Other sections are not affected due to different code paths being followed. Note, however, that further changes to other sections and back to _Recents_ or _Deleted files_ would set the page title as expected (due to `_onShow_` now being called).

**Comment by skjnldsv** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
