### ISSUE TITLE
occ upgrade is outdated

### ISSUE THREAD

**Issue by andre-paulo98** [nextcloud/server#6960]
### Steps to reproduce
1.  `sudo -u www-data php ./occ upgrade`

### Expected behaviour
Update nextCloud from 11.0.5.1 to 12.0.3

### Actual behaviour
I have the notification to update on the webpage, but all the times i tried to update from the webpage it breaks. So i tried to do from the command line now, but i keep getting "Nextcloud is already latest version"

### Server configuration

**Operating system**: Ubuntu 16

**Web server:** Apache2

**Database:** MySQL 14.14

**PHP version:** 7.0.22

**Nextcloud version:** 11.0.5.1

**Updated from an older Nextcloud/ownCloud or fresh install:** older Nextcloud

**Where did you install Nextcloud from:** zip file i think

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - onlyoffice
  - spreed
  - theming
  - user_external
  - user_ldap
  - user_saml

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "therewasavaluehere",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "domain"
        ],
        "datadirectory": "\/var\/www\/cloud\/public\/data",
        "overwrite.cli.url": "http:\/\/cloud",
        "dbtype": "mysql",
        "version": "11.0.5.1",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "appstore.experimental.enabled": true,
        "loglevel": 0,
        "mail_smtpmode": "smtp",
        "mail_from_address": "myemail",
        "mail_domain": "gmail.com",
        "maintenance": false,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "theme": "",
        "updater.release.channel": "stable"
    }
}

```
</details>

**Are you using external storage, if yes which one:** nope

**Are you using encryption:** nope

**Are you using an external user-backend, if yes which one:** command line

**Comment by MorrisJobke** [comment]
> I have the notification to update on the webpage, but all the times i tried to update from the webpage it breaks. So i tried to do from the command line now, but i keep getting "Nextcloud is already latest version"

This command does not update the code itself it only runs the migration scripts.

See https://docs.nextcloud.com/server/12/admin_manual/maintenance/update.html#using-the-command-line-based-updater for details on how to update the code on the command line.
