### ISSUE TITLE
Direct download on password protected share redirects to share page

### ISSUE THREAD

**Issue by linucksrox** [nextcloud/server#6961]
Nextcloud 12.0.3

When sending a direct download link (e.g. https://cloud.mydomain.com/898d8d9sf/download) on a password protected share, the user is redirected to https://cloud.mydomain.com/898d8d9sf/authenticate where they enter the correct password. Then the user is redirected to https://cloud.mydomain.com/898d8d9sf

In my opinion this should go back to https://cloud.mydomain.com/898d8d9sf/download where they never have to see or think about manually downloading documents, which is the whole point of the direct link.

**Comment by MorrisJobke** [comment]
cc @nextcloud/sharing
