### ISSUE TITLE
Public pages not accessible, when app is restricted to groups

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/server#6962]
Affected Apps are at least Gallery, Calendar, Polls
### Steps to reproduce
1. Limit access to app to defined group(s)
2. Use the share function of the app (i.e. via link)
3. Open the shared link as a not logged in user

### Expected behaviour
Error: App is not enabled

### Actual behaviour
Open the shared page instead

### Server configuration

**Nextcloud version:** 12 and 13

See https://github.com/nextcloud/polls/issues/189

**Comment by eneiluj** [comment]
This problem also affects GpxPod, GpxMotion and PhoneTrack.

With PhoneTrack it even makes it impossible to use the app if it is restricted to a group because the logging URLs (to log positions) are public.

**Comment by MorrisJobke** [comment]
> Also, this issue is a duplicate of #5309.

Let's close it as duplicate for now.

**Comment by MorrisJobke** [comment]
Fixed with https://github.com/nextcloud/server/pull/8593 in 14.

**Comment by MorrisJobke** [comment]
> Fixed with #8593 in 14.

Only partially - see https://github.com/nextcloud/server/issues/5309#issuecomment-371067318
