### ISSUE TITLE
Accepting a remote share ends with "Failed to perform action"

### ISSUE THREAD

**Issue by annando** [nextcloud/server#6964]
### Steps to reproduce
1. Click on the notifications
2. Click on "accept" 

### Expected behaviour
The remote share should be accepted.

### Actual behaviour
The message "Failed to perform action" appears.

### Server configuration

**Operating system**:
Linux kernel version 3.10.102 on a Synology DS412+

**Web server:**
Apache 2.2

**Database:**
MariaDB 5

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment]
Are you "accepting" in the web UI or the browser?

Also please check your nextcloud.log file on the server (see data/) and your browsers console when it happens in the browser.

**Comment by annando** [comment]
What do you mean with "web UI" and "browser"? Where is the difference? I had this in the notification at the top right where updates are announced as well.

The nextcloud.log is full of messages like this:
`
{"reqId":"Gz7ntJ5Ktu4iBIe3e8KF","level":4,"time":"2017-10-31T20:37:39+00:00","remoteAddr":"a.b.c.d","user":"icarus","app":"webdav","method":"PROPFIND","url":"\/remote.php\/webdav\/","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Message\":\"System in maintenance mode.\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\MaintenancePlugin->checkMaintenanceMode(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/web\\\/Nextcloud\\\/webroot\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/web\\\/Nextcloud\\\/webroot\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(466): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/web\\\/Nextcloud\\\/webroot\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/web\\\/Nextcloud\\\/webroot\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/web\\\/Nextcloud\\\/webroot\\\/remote.php(162): require_once('\\\/web\\\/Nextcl...')\\n#6 {main}\",\"File\":\"\\\/web\\\/Nextcloud\\\/webroot\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/MaintenancePlugin.php\",\"Line\":82}","userAgent":"Mozilla\/5.0 (Macintosh) mirall\/2.2.4 (build 1) (Nextcloud)","version":"12.0.3.3"}
`

I currently can't reproduce the issue above. Some time later I had some popup message with this "remote share" stuff. This I was able to accept.

Possibly this is connected to some other issue: I cannot do an update per web as well, only per command line. Maybe this is caused by my setup: Nextcloud is running on my NAS at home which is not connected directly to the internet but via another server that redirects the requests.

**Comment by nickvergessen** [comment]
Yeah sorry, I ment to write "web UI" or "desktop client".... 😿 

Anyway when it works now, it might be related to a downtime on the federated share you got. There has to be a connection to the server in order to be able to accept it.
