### ISSUE TITLE
Idle Logout Doesn't Happen

### ISSUE THREAD

**Issue by ateam-adam** [nextcloud/server#6965]
### Steps to reproduce
1. Set session_lifetime to 600 seconds
2. Set session_keepalive to false

### Expected behaviour
The user is logged out after 10 minutes

### Actual behaviour
The user is not logged out

I suspect this is because of the notifications API/AJAX stuff going on behind the scenes which is keeping the session alive but maybe this is being taken into account and the problem lies elsewhere.

### Server configuration

**Operating system**: FreeBSD

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.1.10

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - encryption
  - files_external
  - impersonate
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oc50olvbmzu4",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "files.xxxxxx.com"
        ],
        "datadirectory": "\/htwritable\/data",
        "overwrite.cli.url": "https:\/\/files.xxxxxxxxxxxxx.com",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "nextcloud",
        "dbhost": "127.0.0.1",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "files",
        "mail_domain": "files.xxxxxxxxxxx.com",
        "mail_smtphost": "127.0.0.1",
        "mail_smtpport": "25",
        "skeletondirectory": "\/htwritable\/skeleton",
        "session_lifetime": 600,
        "session_keepalive": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** Local

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox and Chrome

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
<empty>
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
GET XHR https://files.xxxxxxxxxx.com/ocs/v2.php/apps/notifications/api/v2/notifications [HTTP/1.1 200 OK 413ms]
GET XHR https://files.xxxxxxxxxx.com/ocs/v2.php/apps/notifications/api/v2/notifications [HTTP/1.1 200 OK 508ms]
GET XHR https://files.xxxxxxxxxx.com/ocs/v2.php/apps/notifications/api/v2/notifications [HTTP/1.1 200 OK 324ms]
GET XHR https://files.xxxxxxxxxx.com/ocs/v2.php/apps/notifications/api/v2/notifications [HTTP/1.1 200 OK 332ms]
GET XHR https://files.xxxxxxxxxx.com/index.php/apps/files/ajax/getstoragestats.php [HTTP/1.1 200 OK 339ms]
GET XHR https://files.xxxxxxxxxx.com/ocs/v2.php/apps/notifications/api/v2/notifications [HTTP/1.1 200 OK 331ms]
GET XHR https://files.xxxxxxxxxx.com/ocs/v2.php/apps/notifications/api/v2/notifications [HTTP/1.1 200 OK 536ms]
GET XHR https://files.xxxxxxxxxx.com/ocs/v2.php/apps/notifications/api/v2/notifications [HTTP/1.1 200 OK 289ms]
GET XHR https://files.xxxxxxxxxx.com/ocs/v2.php/apps/notifications/api/v2/notifications [HTTP/1.1 200 OK 373ms]
GET XHR https://files.xxxxxxxxxx.com/ocs/v2.php/apps/notifications/api/v2/notifications [HTTP/1.1 200 OK 328ms]
GET XHR https://files.xxxxxxxxxx.com/ocs/v2.php/apps/notifications/api/v2/notifications [HTTP/1.1 200 OK 318ms]
GET XHR https://files.xxxxxxxxxx.com/ocs/v2.php/apps/notifications/api/v2/notifications [HTTP/1.1 200 OK 323ms]
GET XHR https://files.xxxxxxxxxx.com/ocs/v2.php/apps/notifications/api/v2/notifications [HTTP/1.1 200 OK 385ms]
GET XHR https://files.xxxxxxxxxx.com/ocs/v2.php/apps/notifications/api/v2/notifications [HTTP/1.1 200 OK 503ms]
GET XHR https://files.xxxxxxxxxx.com/ocs/v2.php/apps/notifications/api/v2/notifications [HTTP/1.1 200 OK 347ms]
GET XHR https://files.xxxxxxxxxx.com/index.php/apps/files/ajax/getstoragestats.php [HTTP/1.1 200 OK 331ms]
GET XHR https://files.xxxxxxxxxx.com/ocs/v2.php/apps/notifications/api/v2/notifications [HTTP/1.1 200 OK 318ms]
GET XHR https://files.xxxxxxxxxx.com/ocs/v2.php/apps/notifications/api/v2/notifications [HTTP/1.1 200 OK 329ms]
GET XHR https://files.xxxxxxxxxx.com/ocs/v2.php/apps/notifications/api/v2/notifications [HTTP/1.1 200 OK 312ms]
```
</details>

**Comment by MorrisJobke** [comment]
cc @nickvergessen @LukasReschke 

I would say that this is how it works now. If there is a request send, then the session timeout is shifted.

**Comment by ateam-adam** [comment]
Yeah I hear you but it effectively makes auto-logging out impossible which is something out client needs.  Is it possible to disable those background AJAX scripts easily that I'm missing to avoid it?

**Comment by nickvergessen** [comment]
You can disable background polling, but this is nothing we can do for everyone.
Just set this line here to 660000:

https://github.com/nextcloud/notifications/blob/23b0b293b385ee8033ed9b4458d8e4ad16388188/js/app.js#L19-L20

then the next polling will happen after 11 minutes and therefor you timed out already.

**Comment by ykcab** [comment]
did we ever got a fix for this? the issue persist in version 13.0.2. Can't we just edit the log in session in the log in index page?

**Comment by blizzz** [comment]
@nickvergessen has a proposed fix in https://github.com/nextcloud/notifications/pull/130 if you mind testing

**Comment by nickvergessen** [comment]
@ateam-adam you had any chance to test the fix?

**Comment by nickvergessen** [comment]
Will be fixed in 14
