### ISSUE TITLE
Nextcloud does not accept all file suffixes.  Is there a solution?

### ISSUE THREAD

**Issue by jiml8** [nextcloud/server#6968]
I would love to move my development directory for a specific project onto my nextcloud instance in my NAS so that I could work from anywhere and have my work automatically synced.

However, nextcloud is routinely deleting any file I upload with the suffix .inc and this makes it impossible for me to achieve my goal. I have a few dozen PHP files that are used as library files and are identified with the suffix .inc.

Why is nextcloud not agnostic on file identifiers, and is there anything I can do about this?

**Comment by nickvergessen** [comment]
By default we only block uploading `.htaccess` files:
https://github.com/nextcloud/server/blob/030d85bc9cc8328e4a6db57b255abd541e05b643/lib/private/Files/Filesystem.php#L619

Please fill out more information of the issue template.

**Comment by jiml8** [comment]
Problem turned out to be the webserver, which was set to block .inc files.
