### ISSUE TITLE
Show e-mail address while sharing folder to user

### ISSUE THREAD

**Issue by brunt82** [nextcloud/server#6971]
### Steps to reproduce
1. Use LDAP as user backend
 -  configure in LDAP > Advanced > Directory Settings > User Display Name Field: set LDAP attribute with first and last name, e.g. "CN"
- do **not** configure LDAP > Advanced > Directory Settings > 2nd User Display Name Field: with an LDAP attribute with e-mail address, like "mail"
2. Share a file / folder and enter a user name

### Actual behaviour
It is only displayed the user name. It is impossible to differ between persons with the same name. When the user exists twice in LDAP with two email addresses, it is impossible to select the correct mail.

### Expected behaviour
The user name is displayed with his email address (the mouse-over shows the display name <- is this changeable?)

### Additional
As you can suppose from the description above I already tested the possibility to add the mail-attribute into the "2nd User Display Name Field" as it is provided as example. This works as desired for sharing: the user name will be displayed followed by the mail address in brackets. 

But this user name is also used by other apps and leads to undesired behavior:
1. Mail app: the sender will send mails from "Max Muster (Max.muster@mail.com) \<max.muster@mail.com>" (See https://github.com/nextcloud/mail/issues/576)
2. SabreDAV: the organizer will be "Max Muster (Max.muster@mail.com):mailto:max.muster@mail.com", which is displayed in the caldav clients.
3. Maybe more..

So the initial idea to improve the user behavior while sharing is good, but it only works there. Maybe there is another solution? 

### Server configuration

**Operating system**: Debian 9

**Web server:** Apache 2.4

**Database:** MariaDB

**PHP version:** 7.1

**Nextcloud version:** (see Nextcloud admin page) 12.0.3

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.

**Comment by brunt82** [comment]
Maybe because it is already implemented...

**Comment by szaimen** [comment]
That's excactly why I am cleaning up old issues :)
