### ISSUE TITLE
Kodi/VLC integration

### ISSUE THREAD

**Issue by kbaegis** [nextcloud/server#698]
**Feature Request/Idea**
Kodi or VLC streaming integration would be a very nice feature.  Using nextcloud as a host for video content has become one of our primary use cases on our deployment, and it would be wonderful if we could stream content to Kodi from NextCloud or the other way around.  I'm not experienced enough with coding and video codecs to do this myself.

**Comment by WebSpider** [comment]
You can mount NextCloud as a webdav share from within Kodi, and that way do what you want?

http://kodi.wiki/view/WebDAV

**Comment by kbaegis** [comment]
Beautiful :) Thanks!

**Comment by borekon** [comment]
It is not working for me, it throws a 503 error. 
With owncloud everything was OK (last week moved from owncloud to nextcloud)

**Comment by kylepwarren** [comment]
I too was unable to do it. I'm pretty sure my nextcloud is 100% https[port 443], I don't know how to make kodi do that for webdav, seems to be trying port 80 or something. note: libre office webdav config just worked, first try (to the same next cloud server)
