### ISSUE TITLE
Add an "Updates pending" category to the apps list categories (left pane links)

### ISSUE THREAD

**Issue by MagicFab** [nextcloud/server#6985]
At https://nextcloud.domain/index.php/settings/apps it's possible to filter the apps listing by several criteria:

- https://nextcloud.domain/index.php/settings/apps?category=enabled#
- https://nextcloud.domain/index.php/settings/apps?category=auth#
- etc.

It would be very useful to have a direct link to an "Updates pending" category listing all the apps that require updating.

**Comment by juliushaertl** [comment]
Thanks for reporting @MagicFab This has already been added in #6739

**Comment by MagicFab** [comment]
My search skills failed me, sorry!.. and thank you. Can't wait for NC13.
