### ISSUE TITLE
Integration of VoIP Communication

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#699]
Hi,

How about initiating a VoIP communication starting e.g. from the Contacts app for further enhancement of the "open Source" idea ?
Could be started form a separate app as well ???

As a sample how about : http://www.linphone.org/, or Skype ??
Further reading: https://de.wikipedia.org/wiki/Liste_von_VoIP-Software

Would love to discuss with you!

regards, hitam4450

**Comment by mar1u5** [comment]
We are also have an partnership with **spreed**, which does quit what you are talking about. 
>  Adding to the Spreedbox support for communication through browsers or mobile apps is the optional SIP Gateway support, enabling web conferencing participants to dial in through a more traditional telephone connection. It is also possible to dial out from the nice Spreed interface to land or mobile lines!

Learn more: https://nextcloud.com/spreedbox/

**Comment by MorrisJobke** [comment]
There is also a spreed app to have an integration into nextcloud. We are currently try to improve the UX.
