### ISSUE TITLE
Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction

### ISSUE THREAD

**Issue by alexknobbe** [nextcloud/server#7005]
### Steps to reproduce
1. removing multiple files

### Expected behaviour
Fast remove

### Actual behaviour
The remove for every second file takes time and the log shows the following error.

tail -f /var/log/nginx/error.log
#6 [internal fu" while reading response header from upstream, client: 109.69.230.220, server: start.boxu.nl, request: "PUT /remote.php/dav/fil                                                                                               es/btslogisticsfotos/Fotos/JS%20GREENSTAR/25-10%20(4).JPG HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.boxu.sock:", host: "start.b                                                                                               oxu.nl"
2017/10/30 08:48:41 [error] 8921#8921: *610137 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[40001]:                                                                                                Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction in /var/www/html/3rdparty/doctrine/dbal/lib/Do                                                                                               ctrine/DBAL/Driver/PDOStatement.php:91
Stack trace:
#0 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(NULL)
#1 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1006): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /var/www/html/lib/private/DB/Connection.php(213): Doctrine\DBAL\Connection->executeUpdate('UPDATE `oc_file...', Array, Array)
#3 /var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(208): OC\DB\Connection->executeUpdate('UPDATE `oc_file...', A                                                                                               rray, Array)
#4 /var/www/html/lib/private/DB/QueryBuilder/QueryBuilder.php(213): Doctrine\DBAL\Query\QueryBuilder->execute()
#5 /var/www/html/lib/private/Lock/DBLockingProvider.php(278): OC\DB\QueryBuilder\QueryBuilder->execute()
#6 [internal fu" while reading response header from upstream, client: 46.44.173.251, server: start.boxu.nl, request: "GET /avatar/aknobbe/32?v                                                                                               =2 HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.0-fpm.boxu.sock:", host: "start.boxu.nl"

### Server configuration

**Operating system**: 
Ubuntu 16.10

**Web server:** 
NGING 1.10

**Database:** 
MySQL

**PHP version:**
PHP 7

**Nextcloud version:** (see Nextcloud admin page)
12.0.3

**Comment by DMWOO7** [comment]
I had this issue to and was able to solve it by setting [transaction isolation level](https://github.com/owncloud/core/issues/20555#issuecomment-157331571) globally.

**Comment by nickvergessen** [comment]
Duplicate: https://github.com/nextcloud/server/issues/3453
