### ISSUE TITLE
Expiry date calendar for shares is misplaced

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#7007]
* create a share
* open the menu of that share
* activate the expiry date
* actual: calendar widget is misplaced
* expected: calendar widget is positioned correctly

![bildschirmfoto 2017-10-30 um 09 32 02](https://user-images.githubusercontent.com/245432/32162087-04ccd10e-bd58-11e7-9056-2c79819d4dba.png)

It is also unrelated to #6976 because it was broken before

cc @nextcloud/javascript @skjnldsv @jancborchardt

**Comment by jancborchardt** [comment]
Also there is way too much whitespace in the popover. Should be a date input field below the option only, and the datepicker originating from there.

**Comment by skjnldsv** [comment]
@MorrisJobke Damn, I was sure I fixed this in a pr somewhere! :O
It's related to https://github.com/nextcloud/server/commit/82a52a8f1706c83915e4462bc6845da7eb33acfd#commitcomment-25212534

**Comment by MorrisJobke** [comment]
@nextcloud/designers This is still an issue 😢

**Comment by jancborchardt** [comment]
Also cc @pixelipo since he worked on the datepicker :)

**Comment by juliushaertl** [comment]
The positioning is also wrong if the remaining space under the input field is not big enough for the datepicker: Issue in deck https://github.com/nextcloud/deck/issues/365 but it also occurs in files

![](https://screenshots.firefoxusercontent.com/images/39d888ee-e062-452f-a5de-2a3fd47ba62a.png)

**Comment by pixelipo** [comment]
@juliushaertl I'm not really sure that that is a bug - it happens only when there is not enough screen space to render the popover. If it didn't do that, then the calendar would be partially hidden and thus unusable. I agree that it doesn't look great but utility is more important than aesthetics...

**Comment by pixelipo** [comment]
@MorrisJobke regarding the original bug this issue is about, I created a work-in-progress PR that should solve it: #7595

**Comment by MorrisJobke** [comment]
Fix for this is in #7477
