### ISSUE TITLE
Dev work inside apps is overwritten by marketplace app version

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#7011]
As @Henni wrote in https://github.com/nextcloud/contacts/issues/305#issuecomment-339470033

> I lost my work when my dev instance overwrote my git repository during an update... 😢 

This shouldn’t happen.

@ChristophWurst suggested:

> It's simple: if an app is downgraded, then don't replace it. Alternatively, don't run the update everything that can be updated after an app update/downgrade.

I added:

> or is it possible to check if the app is checked out via git? In that case it should of course not be upgraded with one from the app store.

**Comment by jancborchardt** [comment]
Who can help here @rullzer @schiessle @ChristophWurst?

**Comment by MorrisJobke** [comment]
> or is it possible to check if the app is checked out via git?

Not that easy, because you never know where the `.git` folder for example is placed.

Maybe we should disable app store updates if the update channel is `git`? On the other side: testing this feature and finding bugs in it is also quite hard. :/

**Comment by jancborchardt** [comment]
> Not that easy, because you never know where the .git folder for example is placed.

For the main apps though it’s directly in the root folder of the app, no?

What do you think about @ChristophWurst’s solution?

**Comment by MorrisJobke** [comment]
> For the main apps though it’s directly in the root folder of the app, no?

Sure, but what about for example the social sharing apps it is in a parent folder. And getting all this in our code feels cumbersome.

**Comment by MorrisJobke** [comment]
> It's simple: if an app is downgraded, then don't replace it. Alternatively, don't run the update everything that can be updated after an app update/downgrade.

Sometimes it's also an upgrade, because you forgot to pull and a new release is already in the app store 😉

**Comment by MorrisJobke** [comment]
But yes - downgrades should not be done, because this really does not make sense and also would brick that app.

**Comment by jancborchardt** [comment]
So do we have a dead-simple first solution for 13?

Would be good if app devs lile @Henni and @ChristophWurst don't randomly lose their work because of a core issue. ;)

**Comment by MorrisJobke** [comment]
Fix is in #7505

**Comment by skjnldsv** [comment]
> Fix is in #7505

Nice, I forgot there was an issue about this! :)
