### ISSUE TITLE
Nextcloud 12.0.3 and Calendar/Addressbook-App in MacOS High Sierra

### ISSUE THREAD

**Issue by gpassmann** [nextcloud/server#7015]
Tried two days to sync Addressbook und Calendar of my new MacBook Air with MacOS High Sierra. 

Nextcloud gave me the wrong path to sync. The functional path for syncing is:

/"YourNextcloudFolder"/remote.php/dav/principals/users/"YourNextcloudUserName"/

And the ServerAdress is only the server, e.g. "example.com" without http or https

Best regards

Gerd Passmann

 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Nextcloud should tell me the right path for MacOS for Configuring my connection

### Actual behaviour
I got following pathes from my Nextcloud instance:

https://"my server"/nextcloud/remote.php/dav/addressbooks/users/"myuser"/contacts/ (it's wrong)
and
https://"my server"/nextcloud/remote.php/dav/principals/users/"myuser"/ (this is correct)

### Server configuration

**Operating system**: Linux Mint

**Web server:** Apache2

**Database:** MySQL 5

**PHP version:** 7.0

**Nextcloud version:** (see Nextcloud admin page) 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:**
from Nextcloud.com, not repository of Linux Distribution
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by georgehrke** [comment]
Calendar app shows the correct url,
only affects Contacts app, please report it at https://github.com/nextcloud/contacts
