### ISSUE TITLE
Error while updating with the web browser updater (from 11 to 12.0.3)

### ISSUE THREAD

**Issue by frlacf** [nextcloud/server#7019]
Hi everyone,

I don't know if anyone can help me but, this is the error I got when I tried to update my server. Normally, when I use the web browser updater, I don't have any error and everything is fine. Somehow, this time, I got the following error. 

If there is anyone who knows how fix this or to revert the process and get back to the last version, it would be very appreciated.

![bug_summary](https://user-images.githubusercontent.com/26498281/32201684-b6616b0e-bdae-11e7-9b76-cd95db7e3376.png)

**Comment by nickvergessen** [comment]
Please report your issue to https://github.com/pellaeon/registration
