### ISSUE TITLE
Contact's anniversary not displayed

### ISSUE THREAD

**Issue by pixelipo** [nextcloud/server#7025]
### Steps to reproduce
1. Add `Anniversary` field to a contact in the Contacts app
2. Go to that date in the Calendar app

### Expected behaviour
Anniversary should be displayed

### Actual behaviour
Anniversary is not visible in the calendar

This field is next to useless if it's shown in a calendar. I'm not sure if it's a bug or a feature request, so I'm leaving labeling to others.

**Comment by georgehrke** [comment]
Bug, because it was supposedly implemented by https://github.com/nextcloud/server/pull/1742

**Comment by georgehrke** [comment]
@pixelipo What version are u running on?

**Comment by j-ed** [comment]
@pixelipo I've just run a test with Nextcloud 12.0.3 and Contacts app 2.0.1 and all three date types are correctly shown in the birthday calendar:

Birthday: ![20171031_geburtstag](https://user-images.githubusercontent.com/2572764/32230238-fab632b8-be52-11e7-9c92-6fadf9e25e8a.png)
Deathday: ![20171031_todestag](https://user-images.githubusercontent.com/2572764/32230261-058adbbc-be53-11e7-9baa-fb1c2cfec431.png)
Anniversary: ![20171031_jahrestag](https://user-images.githubusercontent.com/2572764/32230276-105e7a58-be53-11e7-9562-3899ba6cb3fd.png)

**Comment by pixelipo** [comment]
Ok, that was weird. Now all the dates are displayed properly in Calendar app...Ghost in the machine :scream: 

Closing
