### ISSUE TITLE
Possible password exposing bug

### ISSUE THREAD

**Issue by duderino416** [nextcloud/server#7031]
I have been deploying and destroying Nextcloud(current stable from main site .zip) in some containers the last 2 days,I  noticed that on the first load during database setup when the Setup button is pressed the password is passed to Firefox's "Save password" dialog but to the username field in plain text.

 
### Steps to reproduce
1. Unzip(nextcloud-12.0.3.zip) into /www/
2. Fill out username/password & database setup information
3. Complete setup and the password entered for the admin account appears in the username dialogue of Firefox (v56.0) (64-bit) (Ubuntu) 

### Expected behaviour
Password remains hidden if passed to browser at all

### Actual behaviour
Password is displayed in plain text in Firefox username field.

### Server configuration
Apache2 serving Nextcloud nextcloud-12.0.3

**Operating system**:
Ubuntu 16.04 Host > LXD Container (Privileged) Base container 61d54418874f (Public)
**Web server:**
Apache2.4
**Database:**
MySql 5.7
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
12.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install
**Where did you install Nextcloud from:**
Downloaded zip from nextcloud.com
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
Fixed by #7709
