### ISSUE TITLE
Internal error while downloading folder as zip with only digits in the name via share as link

### ISSUE THREAD

**Issue by gvozdarev-sa** [nextcloud/server#7036]
### Steps to reproduce
1. Create folder e.g. 'parent'
2. Create folder in 'parent 'with name containing only digits e.g. '1' and some files in it
3. Share 'parent' folder via link
4. Go to '1' folder
5. Trying to download this folder using zip archive

### Expected behaviour
Downloading this folder

### Actual behaviour
Internal error
and message in the log
{ ...download?dir=parent&files=1","message":"Exception: 
{\"Exception\":\"TypeError\",\"Message\":\"Argument 2 passed to OCA\\\\Files_Sharing\\\\Controller\\\\ShareController::fileListDownloaded() must be of the type array, integer given, called in \\\/var\\\/www\\\/cloud\\\/apps\\\/files_sharing\\\/lib\\\/Controller\\\/ShareController.php on line 491\",\"Code\":0,\"Trace\":\"#0 ...}

### Server configuration

**Operating system**:
Linux
**Web server:**
Nginx
**Database:**
MariaDB 10.1.26

**PHP version:**
7.0.23
**Nextcloud version:** (see Nextcloud admin page)
12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated step by step from Nextcloud 9

**Comment by rullzer** [comment]
Already fixed with https://github.com/nextcloud/server/pull/7016
