### ISSUE TITLE
Timeout when accessing the admin panel because of big logfile

### ISSUE THREAD

**Issue by H4ndl3** [nextcloud/server#704]
### Steps to reproduce
1. Create a large logfile (mine was >1MB)
2. Try to access admin panel

Because the logfile is so big I run into a timeout using nginx and php5-fpm. I think this should be handled differently because in my case #680 still fills the logfile even when the loglevel is set to 4. I can use a cronjob to clear the logfile for the time being but that doesn't help others who might run into the same problem some day.

**Comment by nickvergessen** [comment]
Well just make use of the log rotation feature?
https://github.com/nextcloud/server/blob/master/config/config.sample.php#L637-L644

**Comment by icewind1991** [comment]
I've had no issues working with multi GB logfiles in the past

**Comment by H4ndl3** [comment]
@nickvergessen I somehow forgot about that, thanks for pointing me in the right direction. But I'm still wondering how @icewind1991 has no issues with huge logfiles while I run into timeouts with comparably small ones. Any suggestion where I could look for the cause? System is the one described in #680 and I'm using the nextcloud nginx config. Would setting `fastcgi_request_buffering` to `off` help? The debian nginx version unfortunately doesn't support it yet.

@icewind1991 it might be something specific to my setup. While loading the admin panel php5-fpm used up all CPU power of the container. However, I'm quite certain that it was the log files fault because after I cleared it the admin panel loaded instantly.
