### ISSUE TITLE
use RELATED instead of RELATIONSHIP

### ISSUE THREAD

**Issue by CardBook** [nextcloud/server#7043]
Hi Folks

why do you use the key word RELATIONSHIP instead of RELATED as defined in the vCard norm (https://tools.ietf.org/html/rfc6350#page-42) ?

I cannot add this RELATIONSHIP into CardBook (https://addons.mozilla.org/fr/thunderbird/addon/cardbook/)

**Comment by LukasReschke** [comment]
cc @nextcloud/contacts Thoughts? :)

**Comment by skjnldsv** [comment]
Is this related to server? I'm not sure!

**Comment by CardBook** [comment]
ah sorry, I've not created at the correct place : may you move it to nextcloud/contacts ?

**Comment by irgendwie** [comment]
ref. https://github.com/nextcloud/contacts/issues/426 - we already have an issue over there where I was asking exactly the same thing! :wink:

**Comment by skjnldsv** [comment]
Don't worry @CardBook. :)

**Comment by CardBook** [comment]
I trust you guys :)
