### ISSUE TITLE
Removing folder with 9.8GB of images fails 

### ISSUE THREAD

**Issue by fmikker** [nextcloud/server#7052]
It seems like the deletion of large folders containing many files has performance issues, since the memory limit in php is exhausted.
If I select the same folder and deletes it again, it seems like the folder is moved to the trash bin, but this takes no time at all
### Steps to reproduce
1. Create a folder in Nextcloud and add photos and folders with a total size of 9.8GB
2. Navigate to the folder in question in the webui
3. Mark the folder
4. Press delete, and wait, wait, and wait.
5. Get a error message saying: Folder "name" could not be deleted.

### Expected behaviour
The folder should have been deleted, no warnings printed in the log.

### Actual behaviour
The folder was not deleted, and Nextcloud prints the following in the logs:
```/var/log/httpd/ssl_error_log:
[Thu Nov 02 23:39:10.561526 2017] [:error] [pid 32326] [client 192.168.1.3:33520] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/nextcloud/lib/private/Files/Node/Root.php on line 200
```
*The same issue occurs when deleting the folder from a desktop sync client.*
### Server configuration

**Operating system**:
CentOS Linux release 7.4.1708 (Core) 
**Web server:**
httpd-2.4.6-67.el7.centos.6.x86_64
**Database:**
mariadb-server-5.5.56-2.el7.x86_64
**PHP version:**
rh-php70-php-7.0.10-2.el7.x86_64
**Redis Version**
redis-3.2.10-2.el7.x86_64
**Nextcloud version:** (see Nextcloud admin page)
12.0.3.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 11.x
**Where did you install Nextcloud from:**
Downloaded tar archive from webpage.
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.6
  - cms_pico: 0.9.6
  - comments: 1.2.0
  - contacts: 2.0.1
  - dashboard: 4.0.5
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - news: 11.0.5
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - previewgenerator: 1.0.7
  - provisioning_api: 1.2.0
  - ransomware_protection: 1.0.5
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - encryption
  - federation
  - files_external
  - files_versions
  - impersonate
  - systemtags
  - user_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "updatechecker": false,
        "instanceid": "ocf4rcw3qjw1",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com",
        ],
        "datadirectory": "\/var\/www\/html\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/example.com\/cloud",
        "htaccess.RewriteBase": "\/cloud",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Stockholm",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "cloud",
        "mail_domain": "example.com",
        "mail_smtphost": "mail.example.com",
        "mail_smtpport": "587",
        "loglevel": 2,
        "has_internet_connection": true,
        "maintenance": false,
        "theme": "",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "knowledgebaseenabled": true,
        "updater.release.channel": "stable",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "log_rotate_size": 104857600
    }
}

```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:**
Firefox 56.0
**Operating system:**
Fedora 26
#### Web server error log
<details>
<summary>Web server error log</summary>

```
/var/log/httpd/ssl_error_log:

[Thu Nov 02 23:39:10.561526 2017] [:error] [pid 32326] [client 192.168.1.3:33520] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/nextcloud/lib/private/Files/Node/Root.php on line 200
[Thu Nov 02 23:49:07.042636 2017] [:error] [pid 24244] [client 192.168.1.3:33792] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) in /var/www/html/nextcloud/lib/private/Files/Node/Root.php on line 200
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"WfueLmlBVYznqG4u4LcBIgAAAAE","level":3,"time":"2017-11-02T23:39:10+01:00","remoteAddr":"192.168.1.3","user":"username","app":"PHP","method":"DELETE","url":"\/cloud\/remote.php\/dav\/files\/user\/Photos\/2016","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) at \/var\/www\/html\/nextcloud\/lib\/private\/Files\/Node\/Root.php#200","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.3.3 (Nextcloud)","version":"12.0.3.3"}
{"reqId":"Wfuf-6ct6bDQosR-Bzn7BgAAAAI","level":3,"time":"2017-11-02T23:49:07+01:00","remoteAddr":""192.168.1.3,"user":"username","app":"PHP","method":"DELETE","url":"\/cloud\/remote.php\/webdav\/Photos\/2016","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) at \/var\/www\/html\/nextcloud\/lib\/private\/Files\/Node\/Root.php#200","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64; rv:56.0) Gecko\/20100101 Firefox\/56.0","version":"12.0.3.3"}

```
</details>

**Comment by Simonmicro** [comment]
You can see the error by yourself: The PHP-script has tried to use too much of your server-RAM. You could try to allocate more memory for your script or delete the content step-by-step:

At file /etc/php/php.ini or /etc/php4/php.ini or /etc/php4/php.ini or /etc/php/apache2/php.ini:
;memory_limit = 16M ; Maximum amount of memory a script may consume (16MB)
memory_limit = 32M

**Comment by LukasReschke** [comment]
@icewind1991 Why do we allocate more than 512MB of RAM for this operation?

**Comment by Simonmicro** [comment]
Well, it because in linne 200 and further the script build a ADT list of all files in the folder. It seems there are so many of them, that this datatype crashes the PHP script...

**Comment by fmikker** [comment]
@Simonmicro I'm aware on how to work around the problem, but that is no long term solution since the root cause is a ineffective function in the application that utilizes too much memory.
I have experience from other applications that has the same problem, and it needs to be adressed.

Thank you for taking this seriously @LukasReschke

**Comment by Simonmicro** [comment]
@fmikker
At the moment I can't view your solution or the code but I think there are two ways to fix it:
1(slowest): Call for every file directly a delete function. But that will slow down the script enormously.
2(async): Lets create a tempoary file with all neccessary information to identify the file to deletion. (Then remove it out of the database for the webinterface.) Give that file to the cronjob or similar. We can do that with every file operation - move, copy or delete.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by fmikker** [comment]
I can confirm that this issue is not present in Nextcloud 24.0.8, thank you for your hard work with Nextcloud!

Out of curiosity; how was this performance issue addressed, and when?

**Comment by szaimen** [comment]
> Out of curiosity; how was this performance issue addressed, and when?

No idea, sorry.

But great that it works now! :)
