### ISSUE TITLE
Nextcloud webDAV not supporting SSO?

### ISSUE THREAD

**Issue by mehrdaad** [nextcloud/server#7062]
### Steps to reproduce
1. Install Nextcloud 
2. Setup SSO for nextcloud
2. Navigate to ``remote.php/webdav``

### Expected behaviour  
It should Authentication user via SSO.

### Actual behaviour  
It asks for basic user/pass authentication.

### Detailed explanation:  
I've setup a cas server to authenticate users with it.  I've also installed Nextcloud SSO package to authenticate users with that protocol too.  
Now I expect that NextCloud's webDAV protocol should authenticate users that way but it asks for username and password.  
How should I config Nextcloud to use SSO?

### Server configuration

**Operating system**:
Windows 10
**Web server:**
Centos 
**Database:**
Sqlite
**PHP version:**
7.0.25
**Nextcloud version:** (see Nextcloud admin page)
12.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
no
**Nextcloud version:**  
12.0.3

**Comment by LukasReschke** [comment]
SSO for WebDAV is not supported at the moment. To use SSO in WebDAV you need to use the client login flow that we're currently implementing in our clients. – However, native WebDAV clients likely won't support our flow.

**Comment by jlallana** [comment]
I had a similar case with software that I developed. What should be done in my opinion would be the following. The place to have the following url: https: // myserver / webdav, with username and password, should be something like: http: // myserver / webdav / {random-application-token} without any kind of authentication. This would force the user to enter via web authenticating with any protocol and obtain the private link to their webdav unit.

**Comment by theoneandonly-vector** [comment]
it needs to be an option to only allow app-tokens!

**Comment by TowelDude** [comment]
For anyone looking for a way to do something as such 
I managed to connect Authnetik as SAML SSO Provider to my Nextcloud instance, then used WebAppPassword NC app to create access tokens to WebDav and it works, with the SSO credentials.

Links:

- https://gitlab.tugraz.at/dbp/nextcloud/webapppassword
- https://blog.cubieserver.de/2022/complete-guide-to-nextcloud-saml-authentication-with-authentik/
- https://goauthentik.io/

I havent tried, but you also have MFA features on Authentik. Maybe you can combine that with SAML/Openid SSO
Hope it helps anyone in the future, goodluck!
