### ISSUE TITLE
Sync via DavDroid broken

### ISSUE THREAD

**Issue by theScrabi** [nextcloud/server#7063]
Every time I try to delete, or create anything on my OpenTasks using DavDroid, no change gets synchronized with my nextcloud installation. Also thunderbird takes forever to synchronize a change, and when I change something on the webfrontend, the first change gets commited the rest not.

**Comment by georgehrke** [comment]
@theScrabi Please use the issue template. You didn't even mention what version u use ...

**Comment by theScrabi** [comment]
### Steps to reproduce
1. Update task todo using OpenTasker and DavDroid on Android

### Expected behaviour
Task should be updated on Nextcloud

### Actual behaviour
After next sync every change is lost

### Server configuration

**Operating system**:
Ubuntu 16.04.3 LTS

**Web server:**
Apache/2.4.18

**Database:**
mysqld 5.7.19

**PHP version:**
Zend Engine v3.0.0  with Zend OPcache v7.0.22

**Nextcloud version:** (see Nextcloud admin page)
12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Where did you install Nextcloud from:**
downloaded from website

**Comment by georgehrke** [comment]
Did you check for log messages?

**Comment by MorrisJobke** [comment]
I'm closing this due to the lack of information. We will reopen once the information is available. Especially the nextcloud.log file is of special interest here. Thanks
