### ISSUE TITLE
 Failed to generate translation templates (pot file) for my app

### ISSUE THREAD

**Issue by eneiluj** [nextcloud/server#7068]
### Steps to reproduce
1. install liblocale-po-perl gettext on server's system
2. go to /path/to/nextcloud/apps/myapp/l10n/
3. run ```perl /path/to/nextcloud/l10n/l10n.pl read```

### Expected behaviour
Template translation files should be produced in templates directory.

### Actual behaviour
templates directory is empty.

### Server configuration

**Operating system**:
Ubuntu 17.10

**Web server:**
Apache 2

**Database:**
SQlite3

**PHP version:**
7.1

**Nextcloud version:** (see Nextcloud admin page)
12.0.3.3

So i checked in /l10n/l10n.pl and i think there is a mistake at line 19 : 

```if( $i eq 'l10n' && !$ignore ){```
should be
```if( $i ne 'l10n' && !$ignore ){```

Directories should be considered by ```crawlPrograms``` function except ```l10n``` or if they are ignored.

**Comment by eneiluj** [comment]
One more thing : app developer documentation of NC version 12 says the "read" action is supposed to produce one single .pot template file. After my quick fix, it produces three templates : 

* templates.pot
* js.pot
* appinfo.pot

but it does not merge them into APPNAME.pot

**Comment by MorrisJobke** [comment]
We updated the guide: https://docs.nextcloud.com/server/14/developer_manual/app/l10n.html

But we are also happy to just do it in our transifex organization and just do an automatic sync to your app repo. 😉
