### ISSUE TITLE
External storage google drive works from admin pane not from user pane

### ISSUE THREAD

**Issue by arjanvs** [nextcloud/server#7069]
401. That’s an error.

Error: invalid_client

The OAuth client was not found.
Request Details

    response_type=code
    redirect_uri=https://example.com/nextcloud/index.php/settings/personal
    client_id= 65408516092-l4mrbk5uth3agitcu6et6bqtidvm4913.apps.googleusercontent.com
    scope=https://www.googleapis.com/auth/drive
    access_type=offline
    approval_prompt=force

That’s all we know.

**Comment by MorrisJobke** [comment]
Please fill out the issue template: https://github.com/nextcloud/server/blob/master/issue_template.md

The google drive integration had some problems and google drive has some hard limitations: #5815

**Comment by arjanvs** [comment]
If I read the other issue correct google drive only works from admin pane and not user, right? This is a Google feature, right?
