### ISSUE TITLE
Unable to upload big files using SWIFT as primary storage

### ISSUE THREAD

**Issue by SURFsara-e-infra** [nextcloud/server#7070]
### Steps to reproduce
1. Upload a 6GB file
2.
3.

### Expected behaviour
File should be uploaded

### Actual behaviour
I have tried to upload a  6GB file using webdav. The upload terminated with the following error message: 
<s:message>Client error response
[status code] 413
[reason phrase] Request Entity Too Large
[url] https://proxy.swift.surfsara.nl/v1/KEY_2455981381c14392a1bfa281bc3dd484/nextcloud_57/urn:oid:365</s:message>
Probably related to [#6105](https://github.com/nextcloud/server/issues/6105) but for the sake of completeness I submit this one as well.

### Server configuration

**Operating system**:
CentOS7.3
**Web server:**
apache 2.4.6
**Database:**
MariaDB 5.5
**PHP version:**
7
**Nextcloud version:** (see Nextcloud admin page)
12.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh
**Where did you install Nextcloud from:**
tarball
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
NA
**Operating system:**
NA
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
There was nothing relevant there.
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
{"reqId":"Wf7RJjxT@CjiDOHAWW6LDAAAAC0","level":4,"time":"2017-11-05T08:52:39+00:00","remoteAddr":"145.100.5.231","user":"ron","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/bigfile","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\",\"Message\":\"Client error response\\n[status code] 413\\n[reason phrase] Request Entity Too Large\\n[url] https:\\\/\\\/proxy.swift.surfsara.nl\\\/v1\\\/KEY_2455981381c14392a1bfa281bc3dd484\\\/nextcloud_57\\\/urn:oid:365\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud12\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(159): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->convertToSabreException(Object(Guzzle\\\\Http\\\\Exception\\\\ClientErrorResponseException))\\n#1 \\\/var\\\/www\\\/nextcloud12\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(151): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #110)\\n#2 \\\/var\\\/www\\\/nextcloud12\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1096): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('bigfile', Resource id #110)\\n#3 \\\/var\\\/www\\\/nextcloud12\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(525): Sabre\\\\DAV\\\\Server->createFile('bigfile', Resource id #110, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/nextcloud12\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/nextcloud12\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/nextcloud12\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/var\\\/www\\\/nextcloud12\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/nextcloud12\\\/remote.php(162): require_once('\\\/var\\\/www\\\/nextcl...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud12\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":567}","userAgent":"curl\/7.19.7 (x86_64-redhat-linux-gnu) libcurl\/7.19.7 NSS\/3.27.1 zlib\/1.2.3 libidn\/1.18 libssh2\/1.4.2","version":"12.0.3.3"}
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by LukasReschke** [comment]
cc @icewind1991 Thoughts?

**Comment by vpecinka** [comment]
I have the same problem, we have limit 500 MB/object in our swift storage. I put local swift proxy on webserver. It is written in python using swiftclient library and is using segmented upload to to object storage.

However, I have noticed that at least web upload sends large data dividend into 10MB parts stored in /uploads/userid/web-file-upload-* (in the oc_filecache). Then it postprocess those parts...

That means, that I have already these parts in my swift storage. The idea is simple - let's keep these uploaded segments in swift, post "manifest file" to the swift stated, that these parts make the final file and just "replace" links in of_filecache pointing to those parts with final oc_filecache record pointing to the manifest file.

This is what python swiftclient does when using segmented upload.

**Comment by kesselb** [comment]
Should be fixed by https://github.com/nextcloud/server/pull/18955.
