### ISSUE TITLE
Some sub-Folders on SMB/CIFS External Storage are read only. (You don't have permissions to upload or create files here.)

### ISSUE THREAD

**Issue by ogarcia** [nextcloud/server#708]
From https://github.com/owncloud/core/issues/24608

### Steps to reproduce
1. create new connection from OwnCloud to an existing SMB share (External Storage)
2. when browsing SMB storage with WebUI some sub-folders are read only. these display "You don't have permissions to upload or create files here." but in these 'Read Only' folders, the sub-folders continue to work as expected.
3. syncning with Client shows error - "not allowed because you don't have permission to add files in that folder", but can sync sub-folders of these.

### Expected behaviour
Folder and its contents should be changeable by user

### Actual behaviour
user can't edit contents of some folders, user can read contents, 
user can edit sub-folders of these read only folders.
user receives;
"You don't have permissions to upload or create files here." or "not allowed because you don't have permission to add files in that folder"

The details are same of referred issue.

**Comment by MorrisJobke** [comment]
Fixed with #465
