### ISSUE TITLE
Logon with email address is case sensitive

### ISSUE THREAD

**Issue by JamesWaldron** [nextcloud/server#7084]
### Steps to reproduce
1. Create a test user. 
2. Attempt to logon as the test user with its email address but use different case compared to what was used when creating the user. Logon fails
3. Attempt to logon using the same case that was used on user creation and the logon succeeds.

### Expected behaviour
Successful logon

### Actual behaviour
Failed logon

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.1

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - admin_notifications: 1.0.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.5
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_automatedtagging: 1.2.2
  - files_downloadactivity: 1.1.1
  - files_pdfviewer: 1.1.1
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - encryption
  - federation
  - files_external
  - firstrunwizard
  - gallery
  - registration
  - sharebymail
  - twofactor_totp
  - user_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocihlyxg8dpb",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "172.16.97.61"
        ],
        "datadirectory": "\/netapp\/send-ehcp_data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "nextcloudsenddb",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "send_ehcp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "forcessl": true,
        "overwriteprotocol": "https",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "skeletondirectory": "",
        "maintenance": false,
        "loglevel": 0,
        "theme": "",
        "updater.release.channel": "stable",
        "ldapIgnoreNamingRules": false
    }
}

```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome

**Operating system:** Win7

**Comment by JamesWaldron** [comment]
I can see the following being queried on the database when attempting to logon using an email address - 
SELECT `userid` FROM `oc_preferences` WHERE `appid` = 'settings' AND `configkey` = 'email' AND `configvalue` = 'Someone@EMAIL.COM'

Presumably this can be changed to this to get around the case sensitivity - 

SELECT `userid` FROM `oc_preferences` WHERE `appid` = 'settings' AND `configkey` = LOWER('email') AND `configvalue` = LOWER('Someone@EMAIL.COM')

Will need some advise on how and where to make this change?

**Comment by nickvergessen** [comment]
The main issue is, that not all occurances of `getUsersForUserValue` may be okay with lowering the values before comparison

**Comment by JamesWaldron** [comment]
Currently, I have got around the issue by changing function getUsersForUserValue so that it does lower the values. So far I haven't had any complaints that anything isn't working?

**Comment by rullzer** [comment]
This is also hurting when resetting using reset password.

**Comment by rullzer** [comment]
I'd say we just add another helper function that does lower case search.
