### ISSUE TITLE
Calendar delegation

### ISSUE THREAD

**Issue by labor4** [nextcloud/server#7085]
According to
[http://sabre.io/dav/caldav-proxy/](http://sabre.io/dav/caldav-proxy/)
.. sabredav supports the delegation of calendars from the client-side via caldav

however in Nextcloud/OwnCloud this seems not implemented.
Do you plan to integrate this in the near future?

Ps: I managed to test it with [Baikal](https://github.com/sabre-io/Baikal)

### Steps to reproduce
1. Create multiple Users on NC
2. Apple iCal/Calendar Settings -> Accounts -> Delegations (dont know the english word)
3. Searches live on server for matched Users

The query server-side appears with something like:

`[06/Nov/2017:16:56:10 +0100] "REPORT /basedir/remote.php/dav/principals/users/MYUSER/calendar-proxy-write/ HTTP/1.1" 404 1604 "-" "Mac+OS+X/10.13 (17A405) CalendarAgent/399"
`

**Operating system**:
Ubuntu Server 16 LTS
**Web server:**
Apache2 latest today
**Database:**
mysql
**PHP version:**
7.0
**Server version:** (see your admin page)
NC12.0.3
**Calendar version:** (see the apps page)
Calendar 1.5.6
**Updated from an older installed version or fresh install:**
fresh

```
http://example.com/index.php/settings/integrity/failed says:
No errors have been found.
```

**Comment by Malauch** [comment]
Is there any plan to add this function in nearest future? Maybe Nextcloud 16? It would be great new feature for CalDAV in Nextcloud.

**Comment by abombelli** [comment]
Any news on this?

**Comment by j-ed** [comment]
@Malauch Just for the records, it is very unlikely that this feature will be added to NC16 because there is already a feature freeze 😉

**Comment by skjnldsv** [comment]
@georgehrke :)

**Comment by georgehrke** [comment]
Instructions about implementation can be found at http://sabre.io/dav/caldav-proxy/
Corresponding RFC: https://github.com/apple/ccs-calendarserver/blob/master/doc/Extensions/caldav-proxy.txt
