### ISSUE TITLE
Validation error in iCalendar: ENCODING=QUOTED-PRINTABLE is not valid for this document type.

### ISSUE THREAD

**Issue by tomghyselinck** [nextcloud/server#7088]
I use Evolution e-mail client on Fedora Linux 26.

When I try to import the given ICS file, I get an error back from the server: "415 Unsupported Media Type"

### Steps to reproduce
1. Add the calendar to your Online Accounts in GNOME.
2. Enable calender sync
3. Try to import the ICS via you e-mail client (Evolution).

### Expected behaviour
I expect the calender item to be added :-)

### Actual behaviour
I get an error back from the server: "415 Unsupported Media Type"

### Server configuration

**Operating system**:
Debian 9

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.x

**Nextcloud version:**
12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from ownCloud 9.0.x

**Where did you install Nextcloud from:**
Via web GUI updater

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by LukasReschke** [comment]
cc @georgehrke

**Comment by LukasReschke** [comment]
Can you by any chance share the ICS file with us?

**Comment by tomghyselinck** [comment]
My Excuses,
I also came to the conclusion today that I forgot to add the ICS :-)
Please find it in attachment.
With best regards,Tom.

On Tue, 2017-11-07 at 09:08 +0000, Lukas Reschke wrote:
> Can you by any chance share the ICS file with us?
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/nextcloud
> /server","title":"nextcloud/server","subtitle":"GitHub
> repository","main_image_url":"https://cloud.githubusercontent.com/ass
> ets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in GitHub","url":"https://gi
> thub.com/nextcloud/server"}},"updates":{"snippets":[{"icon":"PERSON",
> "message":"@LukasReschke in #7088: Can you by any chance share the
> ICS file with us?"}],"action":{"name":"View Issue","url":"https://git
> hub.com/nextcloud/server/issues/7088#issuecomment-342419288"}}}
-- 
Tom Ghyselinck <tom.ghyselinck@linbox.be>

**Comment by georgehrke** [comment]
@tomghyselinck I'm afraid GitHub doesn't allow to attach files via email. You have to use the web interface to upload a file. Thx!

**Comment by tomghyselinck** [comment]
Hi @georgehrke ,

I've seen it too. I edited my comment and added the ICS content.

**Comment by tomghyselinck** [comment]
Hi @georgehrke ,

I have another ICS file causing the same issue

With best regards,
Tom.

[absence_171117_10965764.zip](https://github.com/nextcloud/server/files/1468392/absence_171117_10965764.zip)

**Comment by Mebus** [comment]
Ok. When will this be fixed? I get files with 

"ENCODING=QUOTED-PRINTABLE is not valid for this document type"

quite often.

Mebus

**Comment by georgehrke** [comment]
As mentioned earlier, `QUOTED-PRINTABLE` is not part of the iCalendar standard. 
See https://tools.ietf.org/html/rfc5545#section-3.1.3
The only allowed encoding is `BASE64`.

Please find out what software is creating this faulty calendar-data and report a bug to them. 
Thx!

**Comment by northben** [comment]
I am receiving this error from .vcs files downloaded from delta.com. It's an airline reservation.

```
BEGIN:VCALENDAR
PRODID:-//Microsoft Corporation//Outlook 11.0 MIMEDIR//EN
VERSION:2.0
METHOD:PUBLISH
BEGIN:VEVENT
DTSTAMP:20220704T135707
DTSTART:20220824T154000-0500
DTEND:20220824T180900-0500
DESCRIPTION;ENCODING=QUOTED-PRINTABLE:Review=20check-in=20requirements=20for=20your=20airport=20at=20http://www.delta.com/traveling_checkin/itineraries_checkin/requirements/index.jsp=0D=0A=0D=0AItinerary=20Details:=0D=0A=0D=0AAeromexico=20AM=202686=0D=0AFlight:=202686=0D=0ADeparts:=20Benito=20Juarez=20Intl=20Arpt=20on=20Wed,=2024=20Aug=202022=203:40=20PM=0D=0AArrives:=20Austin-Bergstrom=20International=20on=20Wed,=2024=20Aug=202022=206:09=20PM=0D=0A=0D=0AAll=20times=20are=20local.=0D=0A=0D=0ATo=20add=20your=20full=20itinerary=20to=20your=20Outlook=20calendar,=20choose=20save=20to=20download=20the=20file=20to=20your=20computer=20and=20then=20import=20it=20from=20within=20Outlook.=20For=20more=20information,=20please=20see=20the=20Help=20section=20of=20Microsoft=20Outlook.
LOCATION;ENCODING=QUOTED-PRINTABLE:Benito Juarez Intl Arpt
SUMMARY;ENCODING=QUOTED-PRINTABLE:Your Itinerary: MEX-AUS, XXXXXX
PRIORITY:1
UID:TKTNO-DELTA_MEX_AUS_0704202213574
SEQUENCE:0
BEGIN:VALARM
TRIGGER:-PT1440M
ACTION:DISPLAY
DESCRIPTION:Reminder
END:VALARM
STATUS:CONFIRMED
CATEGORIES:Travel
END:VEVENT
END:VCALENDAR
```

**Comment by flottes** [comment]
hey, i hate to comment on a closed issue but i ran across the same problem today. 

My problem is also: "DESCRIPTION;ENCODING=QUOTED-PRINTABLE"....

I then looked into RFC 5545 and I think "QUOTED-PRINTABLE" is definitely allowed.

@georgehrke says that the only allowed encoding is BASE64. But that is only true for binary content. The inline encoding for 8bit text is described here: https://datatracker.ietf.org/doc/html/rfc5545#section-3.2.7

There it says `"8bit" text encoding is defined in [RFC2045]` where QUOTED-PRINTABLE is defined: https://datatracker.ietf.org/doc/html/rfc2045#section-6.7

So could the issue be reopened?

PS: I'm a big believer in sticking strictly to standards. With Nextcloud, however, it has often fallen on my toes, especially in the DAV area, because Kopano, for example, adds custom fields to contacts. Moving from Kopano to Nextcloud then becomes extremely difficult, as many contacts have to be reworked by hand. We are currently planning to move our company structure to Nextcloud, but if we then have a system that is not compatible with anything, only because it strictly adheres to standards, but nowhere else, then we have to consider another platform. 

Translated with www.DeepL.com/Translator (free version)
