### ISSUE TITLE
"Start Update" page accessible for everyone

### ISSUE THREAD

**Issue by sh903** [nextcloud/server#7099]
### Steps to reproduce
1. Nextcloud administration panel: Trigger update for new version
2. After downloading is complete, the admin is told to point browser to Nextcloud instance
3. Web interface shows a button "Start Update"
![bildschirmfoto 2017-11-07 um 11 49 40](https://user-images.githubusercontent.com/33452506/32493125-0ea1dc7c-c3bd-11e7-8659-6a288611f72e.png)

### Expected behaviour
Only the Nextcloud admin should have access to this page and be able to trigger the update by pressing the button, perhaps by inserting the admin password again

### Actual behaviour
Everyone using the web interface is allowed to start the update, which can happen when the user (accidentally) points to the Nextcloud URL during the update. Our users will be quite confused should they see this message.

### Server configuration

**Operating system**:
Ubuntu LTE 16.04
**Web server:**
Apache 2.4.18
**Database:**
mariadb 10.0.31
**PHP version:**
7.0.22
**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated
**Where did you install Nextcloud from:**
github
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - announcementcenter: 3.1.0
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_antivirus: 1.1.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - onlyoffice: 1.1.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - quota_warning: 1.1.1
  - ransomware_protection: 1.0.5
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - calendar
  - encryption
  - files_external
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oc00w6e44kbu",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "sfb1015.cloud.uni-freiburg.de"
        ],
        "datadirectory": "\/var\/ncld",
        "overwrite.cli.url": "https:\/\/sfb1015.cloud.uni-freiburg.de",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "sfb1015_nxtcld",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "inf",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "mail.sfb1015.uni-freiburg.de",
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.uni-freiburg.de",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}


```
</details>

**Are you using external storage, if yes which one:** nfs

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** No

**Comment by LukasReschke** [comment]
At the moment this is the expected behaviour. For bigger instances we'd encourage using the shipped upgrader tool via CLI (`php updater/updater.phar`).
