### ISSUE TITLE
Impersonate error with 2FA enabled users

### ISSUE THREAD

**Issue by zeigerpuppy** [nextcloud/server#7103]
### Steps to reproduce
1. create group 2FA 
2. enable 2FA for that group with the plugin
3. create user with 2FA allowed
4. in the admin "user" settings, attempt to impersonate that user
5. error returned (some details obfuscated)

```
Internal Server Error

The server encountered an internal error and was unable to complete your request.

Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.

More details can be found in the server log.

Technical details

    Remote Address: 128.250.0.###
    Request ID: 1ygqvDoj###h2g3Sdudz
```

Reloading does not help, but using the back operation in the browser it is possible to get to the impersonated user.

The error only occurs with users who have 2FA support enabled (note that in this example, the user has not actually set up 2FA yet).

### Server configuration

**Operating system**: Debian Jessie

**Web server:** Apache2

**Database:** Mariadb

**PHP version:** 7.0.20-2

**Nextcloud version:** 12.0.3

**Comment by LukasReschke** [comment]
Please file this at https://github.com/nextcloud/impersonate - thanks! :)

**Comment by zeigerpuppy** [comment]
thanks for the link, I have filed it there: https://github.com/nextcloud/impersonate/issues/15
