### ISSUE TITLE
Redirect page in new weblogin flow should be themed

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#7104]
During registration on android we see for a short time the default color (blue).

Themed weblogin page:
![screenshot_20171108_092405](https://user-images.githubusercontent.com/5836855/32538729-50142750-c467-11e7-9c61-5f4d3164b865.png)

Redirect page:
![screenshot_20171108_093010](https://user-images.githubusercontent.com/5836855/32538749-6d472188-c467-11e7-8c3e-5b13112d7c1c.png)

**Comment by MorrisJobke** [comment]
cc @juliushaertl @skjnldsv

**Comment by MorrisJobke** [comment]
Backport to stable12 in #7114

**Comment by tobiasKaminsky** [comment]
Works on android as expected.
Thank you 🎉
