### ISSUE TITLE
Weblogin flow: login button shortly wrong color

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#7105]
Given a themed weblogin page, you can see for a very short time a wrong color when pressing the login button.

![screenshot_20171108_092427](https://user-images.githubusercontent.com/5836855/32538848-c231daee-c467-11e7-87e6-8ac47ffbd134.png) ![screenshot_20171108_092825](https://user-images.githubusercontent.com/5836855/32538849-c2b23234-c467-11e7-8eab-a75139dae8e4.png)

**Comment by MorrisJobke** [comment]
@skjnldsv @juliushaertl

**Comment by skjnldsv** [comment]
@tobiasKaminsky Can't reproduce. What version are you using?

**Comment by tobiasKaminsky** [comment]
@skjnldsv latest master with android emulator (Android 7)

**Comment by skjnldsv** [comment]
This is strange. There is an issue with ios though.
![img_20171108_113710](https://user-images.githubusercontent.com/14975046/32544603-332a060c-c479-11e7-8dca-36be545e645a.jpg)

**Comment by juliushaertl** [comment]
@tobiasKaminsky I cannot reproduce this with master and current playstore version. Can this be a caching issue in your android simulator?

**Comment by tobiasKaminsky** [comment]
I tried it with a samsung s5 and there was also for a very short time a blue button (previously it was themed to white).
I do not know if this can be a caching issue...

**Comment by rullzer** [comment]
Should be fixed with https://github.com/nextcloud/server/pull/7110 and https://github.com/nextcloud/server/pull/7111

**Comment by tobiasKaminsky** [comment]
Indeed I now cannot see the wrong color anymore 👍
