### ISSUE TITLE
Always prompt password input

### ISSUE THREAD

**Issue by zdl411437734** [nextcloud/server#7106]
### Steps to reproduce
1. login in
2. click add user
3. show this image
<img width="1272" alt="1" src="https://user-images.githubusercontent.com/1592355/32538698-7c36d1c4-c42c-11e7-9c3f-4d48a7e7dc84.png">

4.i input password ,but Always prompt password input,when i not input nothing click ok ,Nothing happened

5.i look logs

GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 10000 milliseconds with 0 out of 0 bytes received
/var/www/html/nextCloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 103: GuzzleHttp\Exception\RequestException wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\ConnectException))
/var/www/html/nextCloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
/var/www/html/nextCloud/3rdparty/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(Array)
/var/www/html/nextCloud/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
/var/www/html/nextCloud/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
/var/www/html/nextCloud/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
/var/www/html/nextCloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 165: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
/var/www/html/nextCloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125: GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
/var/www/html/nextCloud/lib/private/Http/Client/Client.php - line 138: GuzzleHttp\Client->get('https //apps.ne...', Array)
/var/www/html/nextCloud/lib/private/App/AppStore/Fetcher/Fetcher.php - line 99: OC\Http\Client\Client->get('https //apps.ne...', Array)
/var/www/html/nextCloud/lib/private/App/AppStore/Fetcher/AppFetcher.php - line 66: OC\App\AppStore\Fetcher\Fetcher->fetch('', '')
/var/www/html/nextCloud/lib/private/App/AppStore/Fetcher/Fetcher.php - line 162: OC\App\AppStore\Fetcher\AppFetcher->fetch('', '')
/var/www/html/nextCloud/lib/private/Installer.php - line 394: OC\App\AppStore\Fetcher\Fetcher->get()
/var/www/html/nextCloud/apps/updatenotification/lib/Notification/BackgroundJob.php - line 258: OC\Installer isUpdateAvailable('survey_client', Object(OC\App\AppStore\Fetcher\AppFetcher))
/var/www/html/nextCloud/apps/updatenotification/lib/Notification/BackgroundJob.php - line 155: OCA\UpdateNotification\Notification\BackgroundJob->isUpdateAvailable('survey_client')
/var/www/html/nextCloud/apps/updatenotification/lib/Notification/BackgroundJob.php - line 79: OCA\UpdateNotification\Notification\BackgroundJob->checkAppUpdates()
/var/www/html/nextCloud/lib/private/BackgroundJob/Job.php - line 59: OCA\UpdateNotification\Notification\BackgroundJob->run(NULL)
/var/www/html/nextCloud/lib/private/BackgroundJob/TimedJob.php - line 54: OC\BackgroundJob\Job->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
/var/www/html/nextCloud/cron.php - line 147: OC\BackgroundJob\TimedJob->execute(Object(OC\BackgroundJob\JobList), Object(OC\Log))
{main}
   

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:
centos
**Web server:**
nginx
**Database:**
sqlite
**PHP version:**
php7-1-11
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 12.0.3

please help me ! thanks

**Comment by rullzer** [comment]
My bet it is the local time vs server time issue. @nickvergessen didn't we run into this already some time ago?

**Comment by zdl411437734** [comment]
@rullzer  Thank you for solving my problem

**Comment by zdl411437734** [comment]
@rullzer I want to have a git/SVN control plugin to manage git/SVN content

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/blob/d790c27a19494346bc7293bee00026201f2910f0/core/js/js.js#L1680-L1683

I guess we should store the current time from JS/php in the js on load and take it into account at https://github.com/nextcloud/server/blob/d790c27a19494346bc7293bee00026201f2910f0/core/js/js.js#L1680-L1683

**Comment by Abijeet** [comment]
@nickvergessen - I'll take this up.
