### ISSUE TITLE
Broken html Tags in Theming --> Slogan String

### ISSUE THREAD

**Issue by dahmen** [nextcloud/server#7108]
### Steps to reproduce
1. Login in WebUI
2. go to Config
3. Theming
4. Edit slogan
5. put in there an `<a href=...>` html tag to link to an impressum (important in germany to link a impressum)
6. save and logout
7. no link on the bottom of Logon site. You see the html code like `<a href=...>` 

### Expected behaviour
I expected to have a html link to my impressum.

### Actual behaviour
I only see the html Code an there is no link.
So i can´t run NC in germany - german law...

### Server configuration
Debian 8
Apache 2
mySQL
PHP Version 7.1.3
Nextcloud version: 12.0.3
Updated from an older Nextcloud

**Comment by LukasReschke** [comment]
This is expected behaviour. We don't support HTML tags in the slogan.
