### ISSUE TITLE
Prevent timeouts with Litespeed

### ISSUE THREAD

**Issue by kaymes** [nextcloud/server#7122]
### Steps to reproduce
1. Run Nextcloud with Litespeed
2. Upload a large file through the desktop client
3. See it fail and wonder.
4. Look in the log files and see a 500 internal server error on the final MOVE request
5. Perform the MOVE request by hand using curl and see a message "This request takes too long to process, it is timed out by the server. [...]"

### Expected behaviour
The file should have been moved to its final destination

### Actual behaviour
Litespeed timed out the php script and the connection to the client before the file was assembled and copied to its final destination.

### Server configuration

**Operating system**:
Linux

**Web server:**
Litespeed

**Database:**
Mysql

**PHP version:**
7.1

**Nextcloud version:** (see Nextcloud admin page)
12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Where did you install Nextcloud from:**
tar file

### Workaround
As explained on https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:php:run-without-timeouts , Litespeed's timeouts can be prevented using a simple .htaccess rule.

```
<IfModule Litespeed>
  <IfModule mod_rewrite.c>
    RewriteRule .* - [E=noabort:1, E=noconntimeout:1]
  </IfModule>
</IfModule>

```
The rule as shown above has two effects: 
1) The php script continues if the client closes its connection
2) The connection doesn't time out.

I'm not 100% sure whether 1) is actually the desired behaviour for NextCloud, but 2) certainly is.

Thus, NextCloud should include the above directive or something similar in its .htaccess file.

**Comment by MorrisJobke** [comment]
> RewriteRule .* - [E=noabort:1, E=noconntimeout:1]

@LukasReschke Does it make sense to add this?

**Comment by MorrisJobke** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement it. Thus I will close this ticket for now. This does not mean we don't want this, but it is simply not on our roadmap for the near future. If somebody wants to work on this nevertheless we are happy to assist and help out.
