### ISSUE TITLE
Sharing files to a public Email Address - Editing is not possible

### ISSUE THREAD

**Issue by ExaconAT** [nextcloud/server#7126]
### Steps to reproduce
1. Logged on with an existing Local or LDAP user via Nextcloud Webinterface
2. Shared the file via Email and checked Editing Allowed
3. Opened the Filelink (no Login) and tried to Edit
4. Tested with odt and txt file

### Expected behaviour
Open the Link and edit the file on the fly or with an edit button

### Actual behaviour
1. Received the E-Mail with a Link
2. Clicked the Link
3. File comes up in Browser and download is possible
4. No editing Button

### Server configuration

**Operating system**: Ubuntu 16.04 LTS

**Web server:** Apache2 .4.18

**Database:** MariaDB 10.0.31

**PHP version:**PHP 7.0.22

**Nextcloud version:** 12.03 Stable

**Updated from an older Nextcloud/ownCloud or fresh install:** No

**Where did you install Nextcloud from:**
Nextcloud.com

**Admin Settings Tab**
All checks passed.

**List of activated apps:**
<details>
<summary>App list</summary>
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - files_external
  - user_external
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - files_external
  - user_external
{
    "system": {
        "instanceid": "ocm2546lszfb",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/data\/data",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
</details>

**Are you using external storage, if yes which one:** local /data/data

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** **LDAP/ActiveDirectory/Webdav**

<details>
<summary>LDAP config</summary>

+-------------------------------+-----------------------------------------------------------------+
| Configuration                 | s01                                                             |
+-------------------------------+-----------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                               |
| hasPagedResultSupport         |                                                                 |
| homeFolderNamingRule          |                                                                 |
| lastJpegPhotoLookup           | 0                                                               |
| ldapAgentName                 | **REMOVED**                                   |
| ldapAgentPassword             | ***                                                             |
| ldapAttributesForGroupSearch  |                                                                 |
| ldapAttributesForUserSearch   |                                                                 |
| ldapBackupHost                |                                                                 |
| ldapBackupPort                |                                                                 |
| ldapBase                      | dc=**REMOVED**,dc=local                                              |
| ldapBaseGroups                | ou=nc,dc=**REMOVED**,dc=**REMOVED**;ou=devel,dc=**REMOVED**,dc=local            |
| ldapBaseUsers                 | dc=**REMOVED**=local                                              |
| ldapCacheTTL                  | 600                                                             |
| ldapConfigurationActive       | 1                                                               |
| ldapDefaultPPolicyDN          |                                                                 |
| ldapDynamicGroupMemberURL     |                                                                 |
| ldapEmailAttribute            |                                                                 |
| ldapExperiencedAdmin          | 0                                                               |
| ldapExpertUUIDGroupAttr       |                                                                 |
| ldapExpertUUIDUserAttr        | samAccountName                                                  |
| ldapExpertUsernameAttr        |                                                                 |
| ldapGidNumber                 | gidNumber                                                       |
| ldapGroupDisplayName          | cn                                                              |
| ldapGroupFilter               | (&(|(objectclass=group)))                                       |
| ldapGroupFilterGroups         |                                                                 |
| ldapGroupFilterMode           | 0                                                               |
| ldapGroupFilterObjectclass    | group                                                           |
| ldapGroupMemberAssocAttr      | uniqueMember                                                    |
| ldapHost                      | **REMOVED**                                        |
| ldapIgnoreNamingRules         |                                                                 |
| ldapLoginFilter               | (&(&(|(objectclass=user)))(|(samaccountname=%uid)(|(cn=%uid)))) |
| ldapLoginFilterAttributes     | cn                                                              |
| ldapLoginFilterEmail          | 0                                                               |
| ldapLoginFilterMode           | 0                                                               |
| ldapLoginFilterUsername       | 1                                                               |
| ldapNestedGroups              | 0                                                               |
| ldapOverrideMainServer        |                                                                 |
| ldapPagingSize                | 500                                                             |
| ldapPort                      | 389                                                             |
| ldapQuotaAttribute            |                                                                 |
| ldapQuotaDefault              |                                                                 |
| ldapTLS                       | 0                                                               |
| ldapUserDisplayName           | displayname                                                     |
| ldapUserDisplayName2          |                                                                 |
| ldapUserFilter                | (&(|(objectclass=user)))                                        |
| ldapUserFilterGroups          |                                                                 |
| ldapUserFilterMode            | 0                                                               |
| ldapUserFilterObjectclass     | user                                                            |
| ldapUuidGroupAttribute        | auto                                                            |
| ldapUuidUserAttribute         | auto                                                            |
| turnOffCertCheck              | 0                                                               |
| turnOnPasswordChange          | 0                                                               |
| useMemberOfToDetectMembership | 1                                                               |
+-------------------------------+-----------------------------------------------------------------+

</details>

### Client configuration
**Browser:** Firefex 56.0.2 (64-Bit)

**Operating system:** Windows 10 Enterprise

**Comment by nickvergessen** [comment]
You should be able to upload the file again.
So yeah online editing is missing, but download-edit-upload should work just fine.

**Comment by ExaconAT** [comment]
Ok example:

User 1 has an nextcloud acc
User 2 has no nextcloud acc

User 1 asks User 2 to edit a .txt on his nextcloud Server.
User 2 says Ok np.
User 1 Shares the Link to User 2 (editing enabled)
User 2 tells User 1 he can only download the file

User 1 is unsatisfied because it definately shows "Editing Allowed"

This button is useless in my opinion until editing is possible.

**Comment by MorrisJobke** [comment]
The editing is only available for a limited set of files. For example if you have collabora online installed in your instance all office documents allow editing for file links. For other files we try to improve the situation by providing the proper editors. For example in #1571

I would close this here for now and would ask you to open tickets for file types that should be supported/are missing in your opinion.

Thanks
