### ISSUE TITLE
App idea: NextDrop

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#7134]
Same like pastebin / pasteboard, but within nextcloud to keep things private:
- one specific page, where you can upload a file or copy a text snippet in it.
- file gets saved / text snippet saved in file
- public link is generated & directly shown
- files are deleted after x days (customizable)
- folder should not be visible / syncable

Currently it just takes too long to give a file / text to someone and you have to maintain (delete) it.

What do you think?

**Comment by rullzer** [comment]
I have always loved zerobin. Even better to share 1 time stuff. As you can end to end encrypt it ;)

But back on topic.


What you'd need:

* App that exposes 'NextDrop' capability + endpoint
* An endpoint to drop text/file
  - gives back a link
  - allows you to specify stuff like
    - delete after first read
    - delete after x days
* An endpoint to retrieve

in theory of course most of this can already be handled if you'd automate the flow with the existing stuff. But I can see the need for some standardized api.

**Comment by tobiasKaminsky** [comment]
This is done by my hero of the week @rullzer here: https://github.com/rullzer/nextdrop
