### ISSUE TITLE
Workflow engine check "file name"

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#7136]
It would be nice if files could be automatically tagged based on their file name.
Ref: https://github.com/nextcloud/files_automatedtagging/issues/40

**Comment by mathiasconradt** [comment]
@nickvergessen The same feature would be nice for the File Access Control app. Should I open a ticket at that repo as well (if it doesn't exist there yet), or can you handle this one here also for the FAC app at the same time?

**Comment by nickvergessen** [comment]
The engine which is in the server repo is used by both apps. So fixing it for one will also fix it for the other

**Comment by mathiasconradt** [comment]
Wildcards should be supported at best, not only absolute filenames/paths. Something like 

```
*-secret.docx
Something-*.pptx
```

to be really useful.

**Comment by nickvergessen** [comment]
Regex is supported.
