### ISSUE TITLE
Theming App - Import and Export Themes

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#7139]
### Steps to reproduce
1. Go to enabled Theming App in Nextcloud 12.0.3

### Expected behaviour
User can import or export themes, including the default.  This will make it easy to backup, restore and share themes between Nextcloud instances.
All themes are stored in an accessible folder within Nextcloud.

### Actual behaviour
There is no clear way to import or export themes, which would include: Name, Web address, Slogan, Color, Logo and Login image.
Theme elements such as Logo and Login image must be uploaded.
No clearly accessible directory for storing Nextcloud themes.

**Comment by juliushaertl** [comment]
I see no real usecase in exporting/importing themes. Theming configuration is usually setup once per setup and most likely not changed.

You can still use the old theme mechanism where you can create a custom theme and store it in the `themes/` directory. That way you can easily share a common theme between multiple instances.

**Comment by sunjam** [comment]
@juliushaertl Can the theme directory be stored within a sync'ed directory of nextcloud itself?

**Comment by juliushaertl** [comment]
Not that I'm aware of. Themes are server specific settings and directories are synced by user, so I see no real benefit in doing that. Also you need to have your nextcloud setup in order to sync the directories.

In case you need to have the same theme for different instances, I think having a git repository for the theme is the best solution.

**Comment by sunjam** [comment]
Hi Julius,
    
From the user / casual admin perspective it would be great to have the ability to easily import / export / share themes.  The selfhosting crowd appreciates being able to personalize their software.  They also like to show off and share their creations.  [People have already developed an app for switching to different wallpaper images on each login from a 3rd party service, which would be just as popular if it simply pulled images from a local directory in the Files app.](https://apps.nextcloud.com/apps/unsplash)
    
Making these actions easier makes the user experience more appealing... it is a small thing, but I'd love the ability to create a shareable theme, share it to another Nextcloud instance + allow them to easily install with no manual input on their end.

**Comment by juliushaertl** [comment]
>  People have already developed an app for switching to different wallpaper images on each login from a 3rd party service, which would be just as popular if it simply pulled images from a local directory in the Files app.

Anyone who's interested is free to start developing an app that does that.

> From the user / casual admin perspective it would be great to have the ability to easily import / export / share themes. The selfhosting crowd appreciates being able to personalize their software. They also like to show off and share their creations.

> Making these actions easier makes the user experience more appealing... it is a small thing, but I'd love the ability to create a shareable theme, share it to another Nextcloud instance + allow them to easily install with no manual input on their end.

I think that should be also doable from an app perspective. But form the server part I don't think we should invest time here. A lot more code required to be maintained for a very small usecase and benefit.
