### ISSUE TITLE
Enabling apps issue

### ISSUE THREAD

**Issue by DrTechdom** [nextcloud/server#7141]
### Steps to reproduce
1. Go to Apps as administrator
2. Try to enable an app (ex. tasks)
3. When asked for your password type it in

### Expected behaviour
The app should enable

### Actual behaviour
The same dialog appears forever asking for a password, sometimes with cancel confirm buttons, some times yes and no buttons. The app is never enabled

### Server configuration

**Operating system**:
Ubuntu 16.04.3 LTS

**Web server:**
Apache 2

**Database:**
MySQL

**PHP version:**
6.1

**Nextcloud version:** (see Nextcloud admin page)
12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
installed from apt-get

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**

<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - admin_notifications: 1.0.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.6
  - checksum: 0.3.5
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - groupfolders: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - metadata: 0.6.0
  - music: 0.5.3
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - previewgenerator: 1.0.7
  - provisioning_api: 1.2.0
  - richdocuments: 1.12.36
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - socialsharing_facebook: 1.0.1
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - activitylog
  - audioplayer
  - encryption
  - files_downloadactivity
  - files_external
  - keeweb
  - mail
  - ocr
  - ojsxc
  - onlyoffice
  - passman
  - phonetrack
  - rainloop
  - spreed
  - spreedme
  - tasks
  - twofactor_totp
  - twofactor_u2f
  - user_external
  - user_ldap
  - weather

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => 'cloud.*****.com',
    1 => '****.com',
    2 => 'office.****.com',
  ),
  'datadirectory' => '/webs/nextcloud-data',
  'overwrite.cli.url' => 'https://cloud.****.com',
  'dbtype' => 'mysql',
  'version' => '12.0.3.3',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'logtimezone' => 'UTC',
  'installed' => true,
  'htaccess.RewriteBase' => '/',
  'maintenance' => false,
  'filelocking_enabled' => false,
  'memcached_servers' =>
  array (
    0 =>
    array (
      0 => '127.0.0.1',
      1 => 11211,
    ),
  ),
  'theme' => '',
  'loglevel' => 1,
);
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
chrome

**Operating system:**
ubuntu

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
none
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

{"reqId":"dZKt3gCk5qSCEwqKHX8K","level":2,"time":"2017-11-11T05:05:21+00:00","remoteAddr":"192.168.1.208","user":"ryan","app":"core","method":"POST","url":"\/login\/confirm","message":"Login failed: 'ryan' (Remote IP: '192.168.1.208')","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3163.100 Safari\/537.36","version":"12.0.3.3"}
{"reqId":"VLK1wn9SDwinm0BoRsfs","level":2,"time":"2017-11-11T05:05:26+00:00","remoteAddr":"192.168.1.208","user":"ryan","app":"core","method":"POST","url":"\/login\/confirm","message":"Login failed: 'ryan' (Remote IP: '192.168.1.208')","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3163.100 Safari\/537.36","version":"12.0.3.3"}
{"reqId":"nb9Ke8EWGBI1id23iGyP","level":2,"time":"2017-11-11T05:05:43+00:00","remoteAddr":"192.168.1.208","user":"ryan","app":"core","method":"POST","url":"\/login\/confirm","message":"Login failed: 'ryan' (Remote IP: '192.168.1.208')","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3163.100 Safari\/537.36","version":"12.0.3.3"}
{"reqId":"TrXuZmJ6lXfBMmRTP7Bi","level":1,"time":"2017-11-11T05:09:30+00:00","remoteAddr":"192.168.1.208","user":"--","app":"admin_audit","method":"POST","url":"\/login","message":"Login attempt: \"ryan\"","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3163.100 Safari\/537.36","version":"12.0.3.3"}
{"reqId":"TrXuZmJ6lXfBMmRTP7Bi","level":1,"time":"2017-11-11T05:09:30+00:00","remoteAddr":"192.168.1.208","user":"ryan","app":"admin_audit","method":"POST","url":"\/login","message":"Login successful: \"ryan\"","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/61.0.3163.100 Safari\/537.36","version":"12.0.3.3"}

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

JQMIGRATE: Migrate is installed, version 1.4.0
DevTools failed to parse SourceMap: https://cloud.theveselyfamily.com/core/vendor/purify.min.js.map
</details>

**Comment by juliushaertl** [comment]
I remember some issues with that if the server and client time are not in sync. Can you check that?

**Comment by DrTechdom** [comment]
That was it... a simple date/time issue.. thank you for the reply
