### ISSUE TITLE
After Login to Nextcloud Webinterface - Site appears without graphics

### ISSUE THREAD

**Issue by Knot3n** [nextcloud/server#7143]
Hello,

my problem ist after the installation of nextcloud, i have this strange problem.

https://imgur.com/Rv301wg

I see some things but the graphics are not loaded.

Permissions are right like from the manual .. php -v = 5.6.30 all needed modules are installed. 

Can someone pls help me .. im stuckin with this since 2 days and i have no clue ..

Greets

**Comment by juliushaertl** [comment]
Please fill out the issue template to provide some more information about your setup, specially log messages from nextcloud/browser.

**Comment by Knot3n** [comment]
PHP-Memory was set too low ... (32 MB) . set it to 128 and it works flawless .. should be in the howto's ...

**Comment by juliushaertl** [comment]
See https://docs.nextcloud.com/server/12/admin_manual/installation/system_requirements.html#memory
