### ISSUE TITLE
Build from source 

### ISSUE THREAD

**Issue by mehi-shokri** [nextcloud/server#7145]
### Steps to reproduce
1. Clone nextcloud's server repo
2. Run ``$ git submodule update --init``
3. Setup a basic server

### Expected behaviour
Nextcloud should work correctly and without any errors.
### Actual behaviour
I see bunch of javascript errors in console. my guess is that dependant libraries is not provided/installed correctly.  
Also application doesn't function correctly. although page loads successfully, but clicking on settings icon or other icons does not perform an action.
Console is:  
```
Uncaught ReferenceError: jQuery is not defined
Uncaught ReferenceError: OCA is not defined
Uncaught ReferenceError: $ is not defined
Uncaught TypeError: Cannot read property 'Share' of undefined
```
and so more.  

My best guess is that, there is another step to build nextcloud from it's source. that isn't provided in the documentation.  
### Server configuration

**Operating system**: CentOS 7-4.1708.el7.centos.x86_64

**Web server:** Apache 2.4.6

**Database:** Sqlite

**PHP version:** 7.0

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh clone install

**Where did you install Nextcloud from:** ``https://github.com/nextcloud/server``

**List of activated apps:** 
```
Enabled:
  - comments: 1.3.0
  - dav: 1.4.5
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_sharing: 1.5.0
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - lookup_server_connector: 1.1.0
  - oauth2: 1.1.0
  - provisioning_api: 1.3.0
  - sharebymail: 1.3.0
  - systemtags: 1.3.0
  - theming: 1.4.0
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - dorna
  - encryption
  - files_external
  - testing
  - user_ldap
```

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'ocu8pxbsuuco',
  'passwordsalt' => 'pjK8Pl2t0za1RoRxggkDjPFI7+GZsg',
  'secret' => 'By57iDOgJUc8+9VbGSQUxNqVYx2+gTeTu9ujFcO4fM/x+2lh',
  'trusted_domains' => 
  array (
    0 => '192.168.10.10',
  ),
  'datadirectory' => '/var/www/nc-data',
  'overwrite.cli.url' => 'http://192.168.10.10/server',
  'dbtype' => 'sqlite3',
  'version' => '13.0.0.5',
  'installed' => true,
);

```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chrome 62.0.3202.89 (Official Build) (64-bit)

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
 No error occurred while running NC
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
 
```
 Empty
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
core.js:10189 Uncaught SyntaxError: Invalid or unexpected token
merged-template-prepend.js?v=4a03124252976e2827863aa90af1f9c2-0:236 Uncaught ReferenceError: jQuery is not defined
    at merged-template-prepend.js?v=4a03124252976e2827863aa90af1f9c2-0:236
search.js:391 Uncaught ReferenceError: OCA is not defined
    at search.js:391
    at search.js:392
backgroundjobs.js:23 Uncaught ReferenceError: $ is not defined
    at backgroundjobs.js:23
merged-share-backend.js:14 Uncaught TypeError: Cannot read property 'Share' of undefined
    at merged-share-backend.js:14
    at merged-share-backend.js:80
jquery-ui-fixes.js:5 Uncaught ReferenceError: jQuery is not defined
    at jquery-ui-fixes.js:5
fileinfo.js:144 Uncaught SyntaxError: Unexpected end of input
client.js:840 Uncaught SyntaxError: Invalid or unexpected token
contactsmenu.js:527 Uncaught SyntaxError: Invalid or unexpected token
merged-index.js?v=4a03124252976e2827863aa90af1f9c2-0:17 Uncaught ReferenceError: OCA is not defined
    at merged-index.js?v=4a03124252976e2827863aa90af1f9c2-0:17
    at merged-index.js?v=4a03124252976e2827863aa90af1f9c2-0:314
app.js:11 Uncaught ReferenceError: OCA is not defined
    at app.js:11
sharedfilelist.js:30 Uncaught ReferenceError: _ is not defined
    at sharedfilelist.js:30
    at sharedfilelist.js:426
app.js:14 Uncaught ReferenceError: OCA is not defined
    at app.js:14
filelist.js:41 Uncaught ReferenceError: _ is not defined
    at filelist.js:41
    at filelist.js:367
oc-backbone-webdav.js:363 Uncaught TypeError: Cannot read property 'Backbone' of undefined
    at oc-backbone-webdav.js:363
merged.js:12 Uncaught ReferenceError: OCA is not defined
    at merged.js:12
    at merged.js:19
external.js:20 Uncaught ReferenceError: OCA is not defined
    at external.js:20
    at external.js:175
additionalScripts.js:13 Uncaught ReferenceError: _ is not defined
    at additionalScripts.js:13
    at additionalScripts.js:293
merged.js:15 Uncaught TypeError: Cannot read property 'Backbone' of undefined
    at merged.js:15
    at merged.js:76
merged.js:15 Uncaught TypeError: Cannot set property 'SystemTags' of undefined
    at merged.js:15
    at merged.js:56
merged.js:12 Uncaught ReferenceError: OCA is not defined
    at merged.js:12
    at merged.js:99
theming:2 Uncaught ReferenceError: OCA is not defined
    at theming:2
    at theming:10
```
</details>

**Comment by juliushaertl** [comment]
It should work fine without any further steps. Are you sure this happens on a complete clean install or have you already done some modifications, as it is indicted by the other issues you have opened?

**Comment by mehrdaad** [comment]
@juliushaertl  nope, this was my first try.  
Before adding any library I cloned it from here, ran ``$ git submodule update --init`` and navigate to the site.  
Page loads indeed, I even setup admin user/pass and data directory.  
But then when I navigate to my storage, I get the mentioned console errors.

**Comment by mehrdaad** [comment]
@juliushaertl  also, downloading app from https://download.nextcloud.com/server/releases/nextcloud-12.0.3.zip and setting debug causes so many files to throw exception.  
Message of all exceptions is:  

    Uncaught ReferenceError: OC is not defined

Can confirm it?

**Comment by juliushaertl** [comment]
No works fine here. Please check your browsers network console for errors. It might be an issue with your webserver config. Can you also check if it loads fine when running the php internal webserver via `php -S 0.0.0.0:8080` in the source folder

**Comment by viamage** [comment]
Bump, I have the same after installing nextcloud manually and migrating (latest) owncloud data, config and database. 
!()[https://i.keios.eu/jz/ffs-2018-01-06-23-05-00.png]

No errors in Network tab. Using Nginx with config provided in documentation.

**Comment by blizzz** [comment]
closing, as you got it working

**Comment by alexamanov** [comment]
I had the same problem.
In my case, the problem was in the nginx config.
in this block: location ~* \.(?:css|js)$
