### ISSUE TITLE
Where is moment library initialized

### ISSUE THREAD

**Issue by mehrdaad** [nextcloud/server#7147]
As far as I know, there is a ``core.json`` file which is used to list dependencies.  
But I can't find where moment is required and initialized.  
In all js files, moment is only called, so the question remains where momment is initialized, and made global?  
What I want to do is to use [moment-jalali](https://github.com/jalaali/moment-jalaali) instead of moment.  
So where should I initialize ``moment-jalali`` instead of ``moment``

**Comment by juliushaertl** [comment]
You need to enable the debug mode to get automatic loading of vendor files from core.json. As already said, please ask further questions regarding development in the forum or irc channel. 😉
