### ISSUE TITLE
Add external dependency to js file

### ISSUE THREAD

**Issue by mehrdaad** [nextcloud/server#7149]
Apparently all of Next Cloud's external js dependencies are available through global variables.  
I'm curious where are these global variables assigned?  
Also  I want to add another dependency to JS files. so I copied the package into ``core/vendor`` dir and added that file to the "vendor" property in ``core.json``.  
After going through these steps, I expect that the added library's export default's be available as global variable. But it is not.  
So which part am I doing wrong?  
If question is vague, ask to explain further.  
thank you

**Comment by juliushaertl** [comment]
You need to enable the debug mode to get automatic loading of vendor files from core.json. As already said, please ask further questions regarding development in the forum or irc channel. 😉
