### ISSUE TITLE
ignoring .snapshots to allow upgrades with btrfs

### ISSUE THREAD

**Issue by krodelabestiole** [nextcloud/server#7153]
You recommend to use btrfs as a backup solution for Nextcloud.

The problem is, on one hand snapper cannot be configured to create `.snapshots` directories in any other directory than the one you want to backup.
https://github.com/openSUSE/snapper/issues/54
And on the other hand, Nextcloud refuses to upgrade with a directory it doesn't recognize at its root :
```
Check for expected files
The following extra files have been found:
.snapshots
```
Is there a workaround to this issue ?

**Comment by LukasReschke** [comment]
> Is there a workaround to this issue ?

Just backup the data directory and not the web root.

**Comment by krodelabestiole** [comment]
i think it's a terrible idea for a backup because the data directory is related to the database, and the database is related to the nextcloud files/version and the apps files/versions.

therefore when you have to restore the data directory, you also want to restore the apps in the same state and same version they were before, the same configuration etc.

**Comment by krodelabestiole** [comment]
@LukasReschke could you re-open please ?

I don't think moving snapshots out of nextcloud directories would either be a good solution : having the subvolumes in the exact same directories they are versioning is the cleanest way I can picture.

**Comment by de-souza** [comment]
Creating snapshots of `/var/www/nextcloud/data/` instead of `/var/www/nextcloud/` didn't work for me: the web updater failed creating a backup with the error

```
RecursiveDirectoryIterator::__construct(/var/www/nextcloud/updater/../data/.snapshots): failed to open dir: Permission denied
```

I solved this problem by creating snapshots of the parent directory `/var/www/` instead.
