### ISSUE TITLE
Add hex color truncates pasted color

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#7158]
- Open up theming setting as admin
- paste hex color, e.g. #99CC00
- see that it is truncated to #99CC0 as only 6 digits are allowed

--> Either allow both for input #99CC00 and 99CC00
--> Or delete "#", so that pasting #99CC00 is 99CC00

**Comment by MorrisJobke** [comment]
cc @nextcloud/theming @skjnldsv

**Comment by Abijeet** [comment]
@skjnldsv - If you haven't started development on this can I take it over?

I'll take a look at it sometime next week.
