### ISSUE TITLE
Breadcrumbs ··· menu not closable, New menu outside visible area

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#7159]
### Steps to reproduce
1. Fresh clone of Nextcloud master
2. Create couple of nested folders, so that the placeholder (···) is added in the breadcrumbs and the "new file/folder button" is as much to the right as possible
3. click on the ··· in the breadcrums to open menu
4. click on the ··· in the breadcrums to close menu
5. open the  "new file/folder" popup by clicking on that button

### Expected behaviour

The popupmenu from the breadcrumbs toggles it state accordingly after each click.

The items of the "new file/folder" menu are visible.

### Actual behaviour

The popupmenu from the breadcrumbs opens, but when trying to close it, it fades away and is shown  again. (it  can only be hidden when clicking on  some blank space)

The contents of the menu are out of the visible browser area.

See video: https://o.schiwon.me/s/ZXBuYcggzzqn6Bm

Happens with both  Firefox 57 and Chromium.

See https://github.com/nextcloud/server/pull/7051#issuecomment-343448179 ff

@skjnldsv @MorrisJobke

**Comment by skjnldsv** [comment]
Can you give us more details about your environment? Apache? Nginx?
Linux ? Mac ?

**Comment by blizzz** [comment]
Apache with mod_php, PHP 7.1, on Linux (Antergos, which is Arch based), checked with both MySQL and sqlite,

**Comment by rullzer** [comment]
I can reproduce locally. It is a pure js thing it seems.

@danxuliu it looks very similar to the bug you fix on the sharing page.

**Comment by skjnldsv** [comment]
Still happening?

**Comment by blizzz** [comment]
@skjnldsv yes, it's still happening, exactly as described.

https://github.com/nextcloud/server/pull/7051#issuecomment-343448179 might still be of interest
