### ISSUE TITLE
Move new user creation from header row into button in sidebar

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#7162]
Currently we have these strange always-there fields in the user management.

Instead we should have a button in the top of the left navigation called "Add user". That would add a new row in the content area on top of the table, with empty fields and dropdowns using default values, with the username field focused.

**Comment by MorrisJobke** [comment]
A nice thing with this would be that it would also allow to specify the display name out of the box.

**Comment by skjnldsv** [comment]
I will do it for 14! :)

**Comment by MorrisJobke** [comment]
We maybe should also overhaul how the user management is implemented in JS - because this is quite a mess nowadays :/

**Comment by skjnldsv** [comment]
Do you suggest we drop the js? Or rebuild it?

**Comment by MorrisJobke** [comment]
> Do you suggest we drop the js? Or rebuild it?

Look at how it works now, because there were quite a lot bugs with it and if we touch it that much, we can also check how to work on those bugs.

**Comment by jancborchardt** [comment]
This is also related to »Show email column by default and also send email to new users« #6468 cause if we move to directly inserting a new row, the email field will be there too.
