### ISSUE TITLE
Allow to search for email address in user management

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#7175]
* followup to #1749 
* similar to the fix in #7169

**Comment by Abijeet** [comment]
I would like to take a crack at this sometime next week.

**Comment by Abijeet** [comment]
Hi @MorrisJobke  - I'm noticing that the `users` table does not have the email column. The email is currently being stored in the `accounts` table. I may be missing something straight forward. 

Using SQLite.

**Comment by MorrisJobke** [comment]
You need to join the preferences table to get the email address

**Comment by Abijeet** [comment]
Ok, thanks.
