### ISSUE TITLE
Database error after migration

### ISSUE THREAD

**Issue by StrangeMonkey** [nextcloud/server#7176]
Good Morning,

My mistake appears when migrate nextcloud instance from server to another

### Steps to reproduce
1. Install new Nextcloud
2. Copy /var/lib/mysql/nextclouddbname

### Expected behaviour
At the login page, after entering admin password, it should print me the nextcloud instance of the account.

### Actual behaviour
I have this error message : 
"An exception occurred while executing 'SELECT `uid`, `displayname` FROM `oc_users` WHERE LOWER(`uid`) = LOWER(?)' with params ["Admin"]:

SQLSTATE[42S02]: Base table or view not found: 1932 Table 'nextcloud.oc_users' doesn't exist in engine"

### Server configuration

**Operating system**:
Raspbian Stretch lite

**Web server:** NGINX

**Database:** MARIADB

**PHP version:** PHP7.0

**Nextcloud version:** (see Nextcloud admin page) 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh nextcloud package install but database migration. 

**Where did you install Nextcloud from:** ZIP package

**Are you using external storage, if yes which one:** /home/$USER/data-folder

**Are you using encryption:** No

### Client configuration
**Browser:** FireFox, Chrome, Safari

**Operating system:** Ubuntu 16.04 LTS / iOS 9

### Logs
I have this error message : 
"An exception occurred while executing 'SELECT `uid`, `displayname` FROM `oc_users` WHERE LOWER(`uid`) = LOWER(?)' with params ["Admin"]:

SQLSTATE[42S02]: Base table or view not found: 1932 Table 'nextcloud.oc_users' doesn't exist in engine"

Thanks for reading and helping,
StrangeMonkey

**Comment by MorrisJobke** [comment]
Please check the database for a table named oc_users. It seems that is not available. For further help maybe ask in the forums: https://help.nextcloud.com

Maybe also try to use mysqldump to migrate the database.
