### ISSUE TITLE
XMPP Chat sidebar covers Hordemail Reply and Send buttons

### ISSUE THREAD

**Issue by goldstar611** [nextcloud/server#7179]
### Steps to reproduce
1. Install XMPP chat plugin
2. Install Mail plugin
3. Compose a new email and make sure the XMPP chat side bar (default to right hand) is showing the contacts list
4. Notice that the "Send" or "Reply" buttons are covered by the XMPP chat side bar

### Expected behaviour
"Send" and "Reply" buttons should move to the left when XMPP chat sidebar is expanded

### Actual behaviour
XMPP chat sidebar covers "Send" and "Reply" buttons

### Server configuration

**Operating system**: Ubunu Server 16.04

**Web server:**
Apache 2

**Database:**
SQLite3

**PHP version:**
7.1

**Nextcloud version:** (see Nextcloud admin page)
12

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-12.0.3.tar.bz2

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - admin_notifications: 1.0.0
  - announcementcenter: 3.1.0
  - calendar: 1.5.6
  - checksum: 0.3.5
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - drawio: 0.8.8
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_clipboard: 0.6.4
  - files_external: 1.3.0
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.1.1
  - files_reader: 1.0.4
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - groupfolders: 1.1.0
  - keeweb: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.7.4
  - news: 11.0.5
  - nextcloud_announcements: 1.1
  - notes: 2.3.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ocdownloader: 1.5.4
  - ojsxc: 3.3.1
  - ownpad: 0.5.10
  - password_policy: 1.2.2
  - previewgenerator: 1.0.7
  - provisioning_api: 1.2.0
  - quota_warning: 1.1.1
  - radio: 0.6.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.1
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "abc",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "abc.com",
            "www.abc.com"
        ],
        "datadirectory": "\/var\/www\/html\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/abc.com\/nextcloud",
        "dbtype": "sqlite3",
        "version": "12.0.3.3",
        "installed": true,
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "webmaster",
        "mail_domain": "abc.com"
    }
}

```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

</details>

### Client configuration
**Browser:** Firefox

**Operating system:** Xubuntu

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No Errors
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No Errors
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
N/A
```
</details>

**Comment by MorrisJobke** [comment]
This needs to be addressed on one of those apps. Most likely in the chat app. Please report it there. https://github.com/nextcloud/jsxc.nextcloud/issues
