### ISSUE TITLE
Search field

### ISSUE THREAD

**Issue by Tarotb** [nextcloud/server#7180]
When your logged in as a user there is a search field on the right top corner. Could this be added in the next update for a shared link? I’m already waiting for this options sinds early this year. A option would be the “quest app” but this seems to be on hold.

As a workaround, I’ve created a shared user account for them to pass around, but this account doesn’t prevent them to delete the share. 

Kind regards,
Taro

**Comment by MorrisJobke** [comment]
Duplicate of #1794
