### ISSUE TITLE
External Sites as default APP

### ISSUE THREAD

**Issue by maesitopi** [nextcloud/server#7182]
### Steps to reproduce
1.Enabling External Sites & add a Website
2.Configure external sites as default app in config.phh
3.Access nextcloud Default Page

### Expected behaviour
The External Site which has been defined should be shown at logon or by pressing the home button in nextcloud.

### Actual behaviour
Nextcloud switches to the "files" app, as it cannot access to the external sites. Surely because the external sites are seperated in numbers like:

- external/1
- external/2
- ...and so on

There has been a Pull request on owncloud for this issue: https://github.com/owncloud/core/pull/28962

Tried following config.php Settings:
defaultapp' => 'external'
'defaultapp' => 'external/1'
'defaultapp' => 'external?id=1'

### Server configuration
**Operating system**: Ubuntu 16.04

**Nextcloud version:** 12.0.3

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by MorrisJobke** [comment]
Fixed in 13: https://github.com/nextcloud/external/pull/51
