### ISSUE TITLE
Shared File / Folder as Group Admin can be de-shared from Group Member

### ISSUE THREAD

**Issue by ExaconAT** [nextcloud/server#7185]
### Steps to reproduce
1. Shared a File / Folder from Group Admin A to Group
2. Disabled editing
3. Logged in as User B (Group Member)
4. Removed the File / Folder from his share

### Expected behaviour
No de-sharing should be possible

### Actual behaviour
User B has no shared Folder / File anymore and cant access the "Group Folder" from his account.

### Server configuration

**Operating system**: 16.04 LTS

**Web server:** Actual Apache2

**Database:** Actual MariaDB

**PHP version:** Actual PHP7

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** no

**Where did you install Nextcloud from:** nextcloud.com

**Comment by MorrisJobke** [comment]
cc @nextcloud/sharing

**Comment by rullzer** [comment]
This is by design. If you receive a share you can always unshare it.

What you are looking for is probably the groupfolders app.
