### ISSUE TITLE
integrity check fails on nearly every file after fresh 12.0.3 install from zip

### ISSUE THREAD

**Issue by rseffner** [nextcloud/server#7187]
### Steps to reproduce
1. download from https://download.nextcloud.com/server/releases/nextcloud-12.0.3.zip
2. unzip (and chown if you run php-fcgid as I do)
3. go through setup

### Expected behaviour
I expect to get no integrity errors in an absolutely fresh install.

### Actual behaviour
I got a huge list of integrity erross with empty "expected" hash.
e.g.:
- EXTRA_FILE:
    - nextcloud/updater/updater.phar:
      - expected:
      - current: 9f4209e127db9fcf622fd34c522c178b6afedff98036203c8d5714b80d163ca743ba475ba4ed7f7ad904f8b6e24e8041d5196654dee3cf10fdb16316708b4ec3
    - nextcloud/updater/index.php:
      - expected:
      - current: f51f0b54900f445b22fdd400c3abf569e2710251449c839ab574d0a7c1d45ffa10bba89310611ffc27c3308c9f3455aaf73b2726efa5f78fed3e8b51f7a13157
    - nextcloud/apps/files_pdfviewer/appinfo/routes.php:
      - expected:
      - current: 1d6c6762aeef98a3ffe2c8af27e9e7924edb7259b0188f31b40f7ede88cd20a575f3ae1dcf14d6386927df6b6cc86541683d99f9ea405c257fd41ba9ceead57f
    - nextcloud/apps/files_pdfviewer/appinfo/signature.json:
      - expected:
      - current: 45969bf69968ba325470ef45ccdcc5890490e7296f65e4c02d3fec7d9cbb2b594a75061fa6f7210d4695c6eee7cd26222eb2add152d30d81261e60a6cd8e6c97
    - nextcloud/apps/files_pdfviewer/appinfo/app.php:
      - expected:
      - current: 0cb9cea9e901b9598981865168af09af6e901cf1c4c2167d4bcb229abef7db583936c857e404ac6078f3ef9ef6a334fe87ed5ed872736bc76bda09f18d092327
    - nextcloud/apps/files_pdfviewer/appinfo/info.xml:
      - expected:
      - current: 26fea4c4a78b6565a20be39c9b151d4ca2cbb47afecbd386fc060634e85484159ef69ea369d592db1315a97b021863518b1e0410e997cdf43ad10d31d1f5e876
    - nextcloud/apps/files_pdfviewer/js/previewplugin.js:
      - expected:
      - current: 40ce0bfcdf9e2d06bf4a69cab435cf303175f779867be02b63a7a66c4f14ac9e05b701af0cab2863254b19ba43416da1b5f3fa44f3981ee9b1c4e90a265419e7
    - nextcloud/apps/files_pdfviewer/js/workersrc.js:
      - expected:
      - current: 2fc54012ef096e04a0153c24336b15d03b943a4d73effbb19728cab4c805c4c5923b0fe21285a6de1f9267d3a9268cacff41f30bf558940e4a607e223704cc43
    - nextcloud/apps/files_pdfviewer/templates/viewer.php:
      - expected:
      - current: 97d35fb352aa46abf01bff489e91c4dc9aa30ce460e8c6b488a496a1b056711da492b44cd01d269c11a8b98719d53a69059e5778ce1ac745aeaf04352b9faee4
    - nextcloud/apps/files_pdfviewer/.github/contributing.md:
      - expected:
      - current: ebee5064631b92f13584a913ec4674ba52e7cf3a5ae01e1cf9dd514ed80061e5e918b4d09da0d5390778f245c5fcbcc6c082ad486ef3b1b50e47b842fce38968
    - nextcloud/apps/files_pdfviewer/.github/issue_template.md:
      - expected:
      - current: 8851208a407774aba0e69b002f286449697f57bce07167b601936c96289345f96e43153adf2819a5e5f316fb86757dae9df59f1853200798f9a0c1eee8ffd02b
    - nextcloud/apps/files_pdfviewer/img/app.svg:
      - expected:
...
    - nextcloud/apps/files_texteditor/js/core/vendor/ace-builds/src-noconflict/snippets/rst.js:
      - expected:
      - current: 1b43bffda14f6731294883f7fdf023d45fe5dac3bf66cdd49cb67cb80c23a93920bcaa4e6f8b243f5cf9e03dec682e2551b4768d59b80f8f3e993361fece8b39
    - nextcloud/apps/files_texteditor/js/core/vendor/ace-builds/src-noconflict/snippets/stylus.js:
      - expected:
      - current: b946629496b97b6e901d59d423ca990d1d99f595c6347e6b46cb2f59dc5fb11be2f793b3104347c0b8865604af3216f57e23f115140e6732248f8723224fdedd
    - nextcloud/apps/files_texteditor/js/core/vendor/ace-builds/src-noconflict/snippets/velocity.js:
      - expected:
...
    - nextcloud/themes/example/core/img/logo-icon.png:
      - expected:
      - current: a3502ae4658b77be5fe7d9df1002cc7a4c54223b681fd06ce37f17ad0d715123a6fb091231ecc9a63cf3c39bdcd12f1c99d0e8b52b19773eae01529a104c3be5
    - nextcloud/themes/example/core/img/favicon-touch.png:
      - expected:
      - current: 1ae7963ebd236eb274e0bcfcc90561dd083671f4aa674ac9bf068945cd83ea9dc5c96e3792405d5b1f904908af66120329234dd8e7128e68ed353f254a857ca9
    - nextcloud/themes/example/core/css/server.css:
      - expected:
      - current: 7cf53b4a99f280427376280c0fdb925a52e64e84fe70c83f5988a08a332bd99eab0d4824598b9882671bc2f06076f589b276e2c40ddc424a8a3a613c4d7920ad
    - nextcloud/themes/README:
      - expected:
      - current: 902ad902d14772f4030f4e8aaec8707ada9904c7e59913057769a55b694986df3f6aad04ed66fb7175d2dbe89b0ce014b80c3737306b3cb61e87f947c7664ee2

### Server configuration

**Operating system**: debian 8.9 x64

**Web server:** apache 2.4.10-10+deb8u11

**Database:** mysql 5.5.58-0+deb8u1

**PHP version:** 7.0.25-1~dotdeb+8.1

**Nextcloud version:** (see Nextcloud admin page) 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** no, fresh install from zip

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:** : its too much

</details>

**List of activated apps:** 
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** chrome / firefox

**Operating system:** win10 x64

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"Wgw58pBMThEAAHWHXF8AAAAU","level":3,"time":"2017-11-15T12:58:41+00:00","remoteAddr":"213.187.xxx.xxx","user":"cloudadmin","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"Invalid argument supplied for foreach() at \/var\/www\/webs\/xxx\/cloud\/lib\/private\/Template\/SCSSCacher.php#145","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.3.3"}
```
</details>

**Comment by MorrisJobke** [comment]
> I got a huge list of integrity erross with empty "expected" hash.

That's weird. Could you send the `core/signature.json` file?

cc @LukasReschke

**Comment by rseffner** [comment]
What a fast reply, thanks.

as requested [signature.zip](https://github.com/nextcloud/server/files/1474942/signature.zip)

**Comment by MorrisJobke** [comment]
This looks like you have a folder called "nextcloud" that holds the same files as well. Remove this folder and rerun the check from the admin settings to fix the issue.

**Comment by rseffner** [comment]
Sorry for my post here. I've overseen that - you are rigth, there was an unneded subfolder.
