### ISSUE TITLE
Update doesn't trigger rebuild of merged js files

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#7198]
![bildschirmfoto vom 2017-11-16 11-47-58](https://user-images.githubusercontent.com/3404133/32907686-319904bc-cb01-11e7-80f7-3dd25637d114.png)

### Steps to reproduce
1. Update from 12.0.3 to 13.0.0-beta1

### Expected behaviour
JavaScript files should be regenerated automatically

### Actual behaviour
This only happens when debug mode is set to false. If debug mode is enabled, it loads the new js files as expected.
I could not reproduce this locally but i guess that is because i don't have any caching setup for that atm.
The old files are loaded. After removing appdata_*/js/, deleting redis cache it works fine again.

cc @rullzer for the merged js stuff.

### General server configuration

**Operating system:** Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u2 (2017-06-26) x86_64

**Web server:** Apache/2.4.10 (Debian) (apache2handler)

**Database:** mysql 5.5.58

**PHP version:** 7.0.24-1~dotdeb+8.1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - apache2handler
 - igbinary
 - mysqlnd
 - PDO
 - xml
 - apcu
 - apc
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - iconv
 - imagick
 - json
 - exif
 - mysqli
 - pdo_mysql
 - Phar
 - posix
 - readline
 - redis
 - shmop
 - SimpleXML
 - sockets
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 13.0.0 Beta 1 - 13.0.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** YOUR ANSWER HERE

**Where did you install Nextcloud from:**  YOUR ANSWER HERE

**Are you using external storage, if yes which one:** Array
(
    [0] => \OC\Files\Storage\Local
    [1] => \OCA\Files_External\Lib\Storage\FTP
    [2] => \OC\Files\Storage\DAV
    [3] => \OCA\Files_External\Lib\Storage\OwnCloud
    [4] => \OCA\Files_External\Lib\Storage\SFTP
    [5] => \OCA\Files_External\Lib\Storage\AmazonS3
    [6] => \OCA\Files_External\Lib\Storage\Swift
    [7] => \OCA\Files_External\Lib\Storage\SFTP
    [8] => \OCA\Files_External\Lib\Storage\SMB
    [9] => \OCA\Files_External\Lib\Storage\SMB
)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** YOUR ANSWER HERE (LDAP/ActiveDirectory/Webdav/...)

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.6.1
 - apporder: 0.4.0
 - bookmarks: 0.10.1
 - calendar: 1.5.6
 - cms_pico: 0.9.6
 - comments: 1.3.0
 - contacts: 2.0.1
 - dav: 1.4.5
 - deck: 0.2.7
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_external: 1.4.1
 - files_markdown: 2.0.1
 - files_pdfviewer: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - groupfolders: 1.1.0
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.7.4
 - metadata: 0.6.0
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.1
 - notifications: 2.1.0
 - oauth2: 1.1.0
 - polls: 0.8.0
 - provisioning_api: 1.3.0
 - richdocuments: 1.12.36
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - telephoneprovider: 1.0.0
 - theming: 1.4.1
 - theming_customcss: 1.0.0
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - admin_audit
 - admin_notifications
 - audioplayer
 - bruteforcesettings
 - circles
 - dashboard
 - disablecontactsmenu
 - drawio
 - encryption
 - external
 - files_accesscontrol
 - files_automatedtagging
 - files_downloadactivity
 - gpxedit
 - gpxmotion
 - gpxpod
 - news
 - ojsxc
 - passman
 - password_policy
 - previewgenerator
 - sharerenamer
 - socialsharing_email
 - spreed
 - tasks
 - user_external
 - user_ldap
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.REMOVED",
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "13.0.0.6",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "ldapIgnoreNamingRules": false,
    "forcessl": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "php",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "secret": "***REMOVED SENSITIVE VALUE***",
    "session_lifetime": 604800,
    "session_keepalive": true,
    "memcache.local": "\\OC\\Memcache\\Redis",
    "loglevel": 0,
    "filesystem_check_changes": "0",
    "trashbin_retention_obligation": "auto",
    "filelocking.enabled": "true",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "updatechecker": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\Illustrator",
        "OC\\Preview\\Photoshop",
        "OC\\Preview\\SVG"
    ],
    "apps_paths": [
        {
            "path": "\/var\/www\/nextcloud\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/nextcloud\/apps-extra",
            "url": "\/apps-extra",
            "writable": true
        }
    ],
    "integrity.check.disabled": false,
    "defaultapp": "apporder",
    "debug": true,
    "updater.release.channel": "beta",
    "overwrite.cli.url": "https:\/\/cloud.REMOVED",
    "htaccess.RewriteBase": "\/",
    "mysql.utf8mb4": true
}
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.89 Safari/537.36

**Operating system:** YOUR ANSWER HERE

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by rullzer** [comment]
mmm strange. since we check mtimes etc.

Could you check the appdata_*/js folder for a file that is still old. And check the deps file.
The mtimes should match your current files.

Also checking your memcache for the same if you can.

**Comment by juliushaertl** [comment]
@rullzer I tried to reproduce this with my backup, but this time the update went though fine. No idea why this happened on the first run. 😕
