### ISSUE TITLE
Gallery Error

### ISSUE THREAD

**Issue by GamesBannerNetwork** [nextcloud/server#7202]
Hello.

We have several security groups through which access to files for users is granted. They are called usr, mgr, adm. The usr group includes all users who can view the access folder, but can not delete files and share them. Users of the mgr group are members of the usr group and can share and delete files, adm have full access.
When a user from the group mgr goes to a shared folder and tries to open it through the gallery, the window simply hangs with a white screen. The browser console generates errors, it is written below.
JQMIGRATE: Migrate is installed, version 1.4.0
DevTools failed to parse SourceMap: https://cloud.domain/core/vendor/purify.min.js.map
(index):76 Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://cloud.domain/apps/files/".
merged.js?v=6c8c459a52fb8e6451b8776297fff8f1-0:2158 Uncaught TypeError: Cannot read property 'length' of undefined
    at View._setupButtons (merged.js?v=6c8c459a52fb8e6451b8776297fff8f1-0:2158)
    at View.viewAlbum (merged.js?v=6c8c459a52fb8e6451b8776297fff8f1-0:1879)
    at View.init (merged.js?v=6c8c459a52fb8e6451b8776297fff8f1-0:1842)
    at Object.refresh (merged.js?v=6c8c459a52fb8e6451b8776297fff8f1-0:374)
    at window.onhashchange (merged.js?v=6c8c459a52fb8e6451b8776297fff8f1-0:118)
    at Object.<anonymous> (merged.js?v=6c8c459a52fb8e6451b8776297fff8f1-0:51)
    at Object.<anonymous> (core.js?v=6c8c459a52fb8e6451b8776297fff8f1-0:2)
    at j (core.js?v=6c8c459a52fb8e6451b8776297fff8f1-0:2)
    at Object.fireWith [as resolveWith] (core.js?v=6c8c459a52fb8e6451b8776297fff8f1-0:2)
    at Object.<anonymous> (core.js?v=6c8c459a52fb8e6451b8776297fff8f1-0:2)

### Steps to reproduce
Create folder "root"
Create a folder "test"
Create groups "usr" and "mgr"
Create two users ut1 ut2
Both add to the group "usr" and ut2 in the group "mgr"
Give permissions without the ability to delete the group "usr" on the folder "root"
Give full rights to the group "mgr" on the folder "test"
Upload several image files to the test folder
Log in as user ut2
Open the folder "test" from the home directory that appeared there after the sharing
Click on the gallery icon at the top to see image file preview

### Expected behaviour
FIle previews must open

### Actual behaviour
Just white screen.

Hello.
We have several security groups through which access to files for users is granted. They are called usr, mgr, adm. The usr group includes all users who can view the access folder, but can not delete files and share them. Users of the mgr group are members of the usr group and can share and delete files, adm have full access.
When a user from the group mgr goes to a shared folder and tries to open it through the gallery, the window simply hangs with a white screen. The browser console generates errors, they will be written below.
JQMIGRATE: Migrate is installed, version 1.4.0
DevTools failed to parse SourceMap: https://cloud.domain/core/vendor/purify.min.js.map
(index):76 Resource interpreted as Stylesheet but transferred with MIME type text/html: "https://cloud.domain/apps/files/".
merged.js?v=6c8c459a52fb8e6451b8776297fff8f1-0:2158 Uncaught TypeError: Cannot read property 'length' of undefined
    at View._setupButtons (merged.js?v=6c8c459a52fb8e6451b8776297fff8f1-0:2158)
    at View.viewAlbum (merged.js?v=6c8c459a52fb8e6451b8776297fff8f1-0:1879)
    at View.init (merged.js?v=6c8c459a52fb8e6451b8776297fff8f1-0:1842)
    at Object.refresh (merged.js?v=6c8c459a52fb8e6451b8776297fff8f1-0:374)
    at window.onhashchange (merged.js?v=6c8c459a52fb8e6451b8776297fff8f1-0:118)
    at Object.<anonymous> (merged.js?v=6c8c459a52fb8e6451b8776297fff8f1-0:51)
    at Object.<anonymous> (core.js?v=6c8c459a52fb8e6451b8776297fff8f1-0:2)
    at j (core.js?v=6c8c459a52fb8e6451b8776297fff8f1-0:2)
    at Object.fireWith [as resolveWith] (core.js?v=6c8c459a52fb8e6451b8776297fff8f1-0:2)
    at Object.<anonymous> (core.js?v=6c8c459a52fb8e6451b8776297fff8f1-0:2)
### Steps to reproduce
Create folder "root"
Create a folder "test"
Create groups "usr" and "mgr"
Create two users ut1 ut2
Both add to the group "usr" and ut2 in the group "mgr"
Give permissions without the ability to delete the group "usr" on the folder "root"
Give full rights to the group "mgr" on the folder "test"
Upload several image files to the test folder
Log in as user ut2
Open the folder "test" from the home directory that appeared there after the sharing
Click on the gallery icon at the top to see image file preview

### Expected behaviour
FIle previews must open

### Actual behaviour
Just white screen.

### General server configuration

**Operating system:** Linux gbn-cloud-01 4.4.0-98-generic #121-Ubuntu SMP Tue Oct 10 14:24:03 UTC 2017 x86_64

**Web server:** nginx/1.12.0 (fpm-fcgi)

**Database:** pgsql PostgreSQL 9.5.10 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit

**PHP version:** 7.1.11-1+ubuntu16.04.1+deb.sury.org+1
<details>
        <summary>PHP-modules loaded</summary>

```
 - Core
 - date
 - libxml
 - openssl
 - pcre
 - zlib
 - filter
 - hash
 - Reflection
 - SPL
 - session
 - standard
 - cgi-fcgi
 - PDO
 - xml
 - apcu
 - bz2
 - calendar
 - ctype
 - curl
 - dom
 - mbstring
 - fileinfo
 - ftp
 - gd
 - gettext
 - gmp
 - iconv
 - igbinary
 - imagick
 - imap
 - intl
 - json
 - ldap
 - exif
 - mcrypt
 - pdo_pgsql
 - pgsql
 - Phar
 - posix
 - readline
 - redis
 - shmop
 - SimpleXML
 - smbclient
 - sockets
 - sysvmsg
 - sysvsem
 - sysvshm
 - tokenizer
 - wddx
 - xmlreader
 - xmlwriter
 - xsl
 - zip
 - libsmbclient
 - Zend OPcache
```
</details>

### Nextcloud configuration

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install:** YOUR ANSWER HERE

**Where did you install Nextcloud from:**  Official site

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

<details>
        <summary>Signing status</summary>

```
[]
```
</details>

<details>
        <summary>Enabled apps</summary>

```
 - activity: 2.5.2
 - admin_audit: 1.2.0
 - audioplayer: 2.2.0
 - comments: 1.2.0
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - files: 1.7.2
 - files_downloadactivity: 1.1.1
 - files_external: 1.3.0
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - issuetemplate: 0.2.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - provisioning_api: 1.2.0
 - quota_warning: 1.1.1
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - updatenotification: 1.2.0
 - user_ldap: 1.2.1
 - workflowengine: 1.2.0
```
</details>

<details>
        <summary>Disabled apps</summary>

```
 - bruteforcesettings
 - encryption
 - federation
 - files_markdown
 - keeweb
 - notes
 - ownpad
 - password_policy
 - user_external
```
</details>

<details>
        <summary>Content of config/config.php</summary>

```
{
    "instanceid": "oce7uc89f5tz",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "files.office.gamesbannernet.com",
        "cloud",
        "192.168.214.5",
        "192.168.214.2",
        "cloud.domain",
        "ip-adress"
    ],
    "datadirectory": "\/var\/www\/cloud-storage",
    "version": "12.0.3.3",
    "dbtype": "pgsql",
    "dbhost": "192.168.214.2",
    "dbname": "owncloud",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "installed": true,
    "default_language": "en",
    "defaultapp": "files",
    "knowledgebaseenabled": true,
    "enable_avatars": true,
    "allow_user_to_change_display_name": true,
    "remember_login_cookie_lifetime": 1296000,
    "session_lifetime": 86400,
    "session_keepalive": true,
    "token_auth_enforced": false,
    "auth.bruteforce.protection.enabled": true,
    "skeletondirectory": "\/var\/www\/cloud\/core\/skeleton",
    "mail_domain": "gamesbannernet.com",
    "mail_from_address": "nextcloud",
    "mail_smtpdebug": false,
    "mail_smtpmode": "smtp",
    "mail_smtphost": "127.0.0.1",
    "mail_smtpport": 25,
    "mail_smtptimeout": 10,
    "mail_smtpsecure": "",
    "mail_smtpauth": false,
    "mail_smtpauthtype": "PLAIN",
    "trashbin_retention_obligation": "auto",
    "versions_retention_obligation": "auto",
    "appcodechecker": true,
    "updatechecker": true,
    "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
    "has_internet_connection": true,
    "check_for_working_webdav": true,
    "check_for_working_wellknown_setup": true,
    "check_for_working_htaccess": true,
    "config_is_read_only": false,
    "log_type": "owncloud",
    "logfile": "\/var\/www\/cloud-storage\/owncloud.log",
    "loglevel": 3,
    "syslog_tag": "Nextcloud",
    "logdateformat": "F d, Y H:i:s",
    "logtimezone": "ETC\/GMT",
    "log_query": true,
    "cron_log": true,
    "log_rotate_size": 1024000,
    "customclient_desktop": "https:\/\/nextcloud.com\/install\/",
    "customclient_android": "https:\/\/play.google.com\/store\/apps\/details?id=com.nextcloud.client",
    "customclient_ios": "https:\/\/itunes.apple.com\/us\/app\/nextcloud\/id1125420102?mt=8",
    "appstoreenabled": true,
    "appstoreurl": "https:\/\/api.owncloud.com\/v1",
    "appstore.experimental.enabled": false,
    "apps_paths": [
        {
            "path": "\/var\/www\/cloud\/apps",
            "url": "\/apps",
            "writable": true
        }
    ],
    "enable_previews": true,
    "preview_max_x": 2048,
    "preview_max_y": 2048,
    "preview_max_scale_factor": 10,
    "preview_max_filesize_image": 50,
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore --convert-to pdf --outdir ",
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown"
    ],
    "comments.managerFactory": "\\OC\\Comments\\ManagerFactory",
    "systemtags.managerFactory": "\\OC\\SystemTag\\ManagerFactory",
    "maintenance": false,
    "singleuser": false,
    "enable_certificate_management": false,
    "sharing.managerFactory": "\\OC\\Share20\\ProviderFactory",
    "sqlite.journal_mode": "DELETE",
    "supportedDatabases": [
        "sqlite",
        "mysql",
        "pgsql",
        "oci"
    ],
    "tempdirectory": "\/var\/www\/cloud-storage\/temp-cloud",
    "hashingCost": 10,
    "blacklisted_files": [
        ".htaccess"
    ],
    "share_folder": "\/",
    "theme": "",
    "cipher": "AES-256-CFB",
    "minimum.supported.desktop.version": "1.7.0",
    "quota_include_external_storage": false,
    "filesystem_check_changes": 0,
    "part_file_in_storage": true,
    "mount_file": "\/var\/www\/nextcloud\/data\/mount.json",
    "filesystem_cache_readonly": false,
    "0": [],
    "forwarded_for_headers": [
        "HTTP_X_FORWARDED",
        "HTTP_FORWARDED_FOR"
    ],
    "max_filesize_animated_gifs_public_sharing": 10,
    "filelocking.enabled": true,
    "filelocking.ttl": 300,
    "upgrade.disable-web": false,
    "debug": false,
    "data-fingerprint": "",
    "copied_sample_config": false,
    "updater.release.channel": "stable",
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "redis": {
        "host": "127.0.0.1",
        "port": 6379,
        "timeout": 0
    },
    "overwrite.cli.url": "https:\/\/cloud.domain"
}
```
</details>

<details>
        <summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36 OPR/48.0.2685.52

**Operating system:** YOUR ANSWER HERE

### Logs

<details>
        <summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

<details>
        <summary>Nextcloud log (data/nextcloud.log)</summary>

```
Insert your Nextcloud log here
```
</details>

<details>
        <summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by LukasReschke** [comment]
This seems like a setup related issue in your web server config, please ask for more help on help.nextcloud.com
