### ISSUE TITLE
Set file/folder sync priority

### ISSUE THREAD

**Issue by alexbixor** [nextcloud/server#7204]
Hi,

It wold be very nice if we could set a sync priority to folders and/or files.

This would bue extremely useful in situations where large updates happen but some updates need to be synced as quickly as possible.

Is this something you are looking to implement?

Thanks.

**Comment by LukasReschke** [comment]
I supposed that we are unlikely to do so as this clutters the user-interface massively and would be a feature only used by a minority of users.

That said, this would also be a client issue and not one for the server. Closing thus.
