### ISSUE TITLE
Improvements to the share file interface

### ISSUE THREAD

**Issue by childnode** [nextcloud/server#721]
### Steps to reproduce
1. visit your own cloud
2. share a file via link
3. open the link of the shared file/folder
### Expected behaviour

the button

```
                    <button id="save-button">Add to your Nextcloud</button>
```

in the upper bar :
should either be renamed to "Add to another nextCloud" (to be less specific in the "what's yours" way) and / or be hidden (by extending [this condition](https://github.com/nextcloud/server/blob/stable10/apps/files_sharing/templates/public.php#L61)) for files I self shared and I self visit while I'm still logged in. In that case, the "your Nextcloud" is the cloud I actually visit.. and might be irritating
yes, might be someway picky .. but that's how end-users think of

another related case is visiting the site if another user of the same instance shared a file with me.
Perhaps instead of hiding the button, I might be redirected to the "shared with me" tree in the instance with deep-dive to the shared file, so I instantly can continue to copy / move the file...

vice versa there (viewing a shared file in the "shared with me" or "shared from me" tree) should be a new button "view shared file/folder as public user" with redirect to the "shortcut" page (where auto-return should be stopped by e.g. adding `?redirect=false` to the "shared link". Aktually you have to click on the "shared" link, copy the link from the sidebar, open a new tab / goto location header, paste the short-url, enter ...

**Comment by jancborchardt** [comment]
Yeah, good point. When you are logged in and view a public share link of a file you own, the »Add to your Nextcloud« button should not show. Or be disabled & greyed out with a tooltip »This file is already in your Nextcloud« so you know the functionality is there.

@schiessle @nickvergessen can we make this happen?

**Comment by schiessle** [comment]
> Yeah, good point. When you are logged in and view a public share link of a file you own, the »Add to your Nextcloud« button should not show. Or be disabled & greyed out with a tooltip »This file is already in your Nextcloud« so you know the functionality is there.

This should be relatively easy... Will look into it on Monday.

Just one thought for you, @jancborchardt over the weekend :wink: It could be possible that userA creates a share link of one of his files because he want to add it to his second Nextcloud (e.g. from the company to his private instance or from the instance of his sports club to his private instance...). If the idea described above is implemented userA would need to trick the Nextcloud server by create a link, log-out, open the link, add it to the other Nextcloud, login again. So in this case it would make it harder to achieve the desired result. I know, probably nothing which happens every day but still possible. So I'm not 100% sure if we should try to know more than the user. Maybe it is better to detect if the user tries to mount a file he already knows back to the exact same instance and user account and block this?

**Comment by childnode** [comment]
I doubt, I'm some way misunderstood ;)
yes, I scribbled some ideas, some of them are possible but perhaps not applicable to all users.
I follow @schiessle to first start thinking about the use cases in detail
perhaps a table might help

**_current behaviour_**

 | (1) logged in user | (2) anonymous / guest user
------------ | ------------ | -------------
(A) shared file in list view | manage file | access denied | 
(B) public link | view file & add button | view file & add button | 
(C) add file to cloud via button | shown in public view | shown in public view | 

**_possible improved behaviour_**


 | logged in user | anonymous / guest user
------------ | ------------ | -------------
(A) shared file in list view | _manage file_ + direct link \| redirect to public view | _access denied_ || redirect to public view | 
(B) public link | _view file_ \| redirect \| direct link to list shared file list view & _add_ grayed out but not disabled _button_ if file is not shared by myself (depending on how the final implementation is, it needs a redirect interruptor for case A1<->B1). | view file & add button + login button | 
(C) add file to cloud via button | _shown in public_ and list view, grayed out in public view | _shown in public view_ |

**Comment by jancborchardt** [comment]
@schiessle what came of this by the way? :) Or how do we proceed here @nextcloud/sharing?

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
