### ISSUE TITLE
WebDAV URL contains server port

### ISSUE THREAD

**Issue by realies** [nextcloud/server#7213]
After setting up latest Nextcloud using the server's local IP for access via the webserver I had to add a trusted https proxy access domain to the config file. It was added as `the.domain:443` and later on changed to not contain the port number.

Unfortunately now the [WebDAV](https://github.com/nextcloud/server/blob/master/apps/files/templates/appnavigation.php#L44)  and [monitoring](url) links looks like `https://the.domain:443/...` within Nextcloud. Tried scraping the server files and database for the string without any luck.

Is it perhaps cached somewhere? How to fix?

PS: Using the server info dashboard also displays the link with :443 at the end based on the [$_['ocs']](https://github.com/nextcloud/serverinfo/blob/master/templates/settings-admin.php#L73) variable.

**Comment by LukasReschke** [comment]
Please fill out the issue template. Thanks.

**Comment by realies** [comment]
### Steps to reproduce
1. Install Nextcloud with the domain name in the config as `domain.com:443`
2. Remove `:433` from domain string
3. Look at specific link boxes within Nextcloud containing a formatted server url string

### Expected behaviour
It is expected for the string to be formatted as `https://domain.com/something`

### Actual behaviour
Instead, it is `https://domain.com:443/something`

### Server configuration

**Operating system**: Latest Docker CE based on Alpine Linux

**Web server:** Nginx

**Database:** Mariadb

**PHP version:**
7.1

**Nextcloud version:**
12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:** 
https://hub.docker.com/r/linuxserver/nextcloud/

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Comment by LukasReschke** [comment]
Can you also post your config file? Thanks a lot! :)

**Comment by MorrisJobke** [comment]
Missing information -> closing then.

**Comment by realies** [comment]
```<?php
$CONFIG = array (
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'datadirectory' => '/data',
  'instanceid' => 'removed',
  'passwordsalt' => 'removed',
  'secret' => 'removed',
  'trusted_domains' => 
  array (
    0 => '192.168.1.10:444',
    1 => 'my.domain.com',
  ),
  'dbtype' => 'mysql',
  'version' => '12.0.3.3',
  'dbname' => 'nextcloud',
  'dbhost' => '192.168.1.10:3306',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'removed',
  'dbpassword' => 'removed',
  'installed' => true,
  'updater.release.channel' => 'stable',
  'maintenance' => false,
  'theme' => '',
  'overwrite.cli.url' => 'https://my.domain.com',
  'loglevel' => 2,
  'updater.secret' => 'removed',
);
```

**Comment by MorrisJobke** [comment]
This looks good. Maybe set up the `overwrite...` configs to specify the exact URLs: https://github.com/nextcloud/server/blob/master/config/config.sample.php#L398-L442

**Comment by realies** [comment]
The result is the same even when `overwrite.cli.url` is removed from the config and the Nextcloud container restarted. I am not sure where the `https://my.domain.com:443` URL comes from, searching the database for the string results in nothing.

**Comment by MorrisJobke** [comment]
> 'trusted_domains' => 
>   array (
>     0 => '192.168.1.10:444',

The first entry confuses me. Could you drop the port there? Or move the domain one to position 0 and the IP one to position 1?

**Comment by realies** [comment]
This is rather irrelevant. Removed it from the array and placed the domain at the first position, restarted the container, no change to the odd URLs.

**Comment by MorrisJobke** [comment]
It just uses the URL generator in: https://github.com/nextcloud/serverinfo/blob/6025651988914b06e9815c2ecbb0f398bae1e11a/lib/Settings/AdminSettings.php#L92

And this itself also uses only the `getBaseURL`:

https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/lib/private/URLGenerator.php#L219-L236

Which then could use the first in the list of trusted_domains:

https://github.com/nextcloud/server/blob/ca70694502301a60d615d1bb9dff304a41c86a51/lib/private/AppFramework/Http/Request.php#L828-L857

Or the host that is provided in the header. Do you run this behind a proxy or something similar?

**Comment by realies** [comment]
Nextcloud is behind a Nginx proxy. Could [this](https://github.com/linuxserver/docker-letsencrypt/blob/master/root/defaults/proxy.conf#L14) be the problem?

**Comment by MorrisJobke** [comment]
> Nextcloud is behind a Nginx proxy. Could this be the cause?

Very likely. That is the problem and is triggered by the proxy setup, because the web server thinks, that this is his outside URL. It can be overwritten by setting `overwritehost` and `overwriteprotocol`.

**Comment by realies** [comment]
I don't think `proxy_set_header Host` should contain the `$server_port` anyways. But that is another discussion. I can confirm that the URLs have changed to what is expected when `$server_port` is gone from the host header. Thanks for the help.

**Comment by melikyuksel** [comment]
What is the solution to this? I'm also using nginx reverse proxy, and my share links and WebDAV are always http://domain.com:443/ instead of https://domain/. I removed the $server_port from the host header as @realies wrote, but then Nextcloud responded with an HTTP error code saying the server couldn't understand the request.

**Comment by yerbolkhassen** [comment]
@melikyuksel @realies @MorrisJobke has anyone found a solution. I am facing the exact same problem.

**Comment by melikyuksel** [comment]
@yerbolkhassen I solved it by editing the `config.conf` file and adding the variables `overwritehost` and `overwriteprotocol` like so:

```
  'overwritehost' => 'nextcloud.baldwin.melik.me',
  'overwriteprotocol' => 'https',
```

**Comment by yerbolkhassen** [comment]
@melikyuksel thanks a million! this solved for me.
just to note for consistency: the config is in config/config.php
