### ISSUE TITLE
Error messages are shown again after having been acknowledged

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/server#7214]
### Steps to reproduce
1. Modify a file or add an additional file to trigger an integrity check error
2. Acknowledge the error that is shown on top of the web UI by clicking the "X"

### Expected behaviour
Error message shouldn't be shown again for the actual session.

### Actual behaviour
Error message keeps popping up as soon as any action is taken (e.g. switch to another app).

This happens on Nextcloud 12.0.3 (stable)

**Comment by LukasReschke** [comment]
The integrity error message is shown purposedly to administrators to indicate that they're running unsupported configurations. Note that regular users won't see that one.

**Comment by bpcurse** [comment]
I'm sorry to comment again in this closed topic, but if this happens during the same session again and again after clicking the "x" behind the message, of what use is the "close" button then?

I have an Issue (additional file https://github.com/nextcloud/server/issues/7132) that cannot be solved at the moment, that seems to have no impact on the Nextcloud instance and that I am aware of (as admin user), so repeating this Info (during the same web session) is not helpful.
