### ISSUE TITLE
server on aarch64: open_basedir

### ISSUE THREAD

**Issue by alexandre1985** [nextcloud/server#7215]
### Steps to reproduce
Just installed the server on Arch Linux following the arch linux wiki and opened for the first time on http://localhost/nextcloud

### Expected behaviour
It shouldn't appear the message that it appears

### Actual behaviour
It gives me this message:  
`It seems that this Nextcloud instance is running on a 32-bit PHP environment and the open_basedir has been configured in php.ini. This will lead to problems with files over 4 GB and is highly discouraged. Please remove the open_basedir setting within your php.ini or switch to 64-bit PHP.`
I do have a 32 bit php but the open_basedir is not set.
Is it save to ignore this warning? Or will I have problems with files over 4GB?
### Server configuration

**Operating system**:
Arch Linux for arm
**Web server:**
apache
**Database:**
mysql
**PHP version:**
php 7 32bit
**Nextcloud version:** (see Nextcloud admin page)
12.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
using pacman -S nextcloud
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by LukasReschke** [comment]
> Is it save to ignore this warning? Or will I have problems with files over 4GB?

Yes. You will have issues. That said, our forum is a better place for this as this is likely a PHP misconfiguration on your side.
