### ISSUE TITLE
Custom Group-Member association field

### ISSUE THREAD

**Issue by konfiot** [nextcloud/server#7216]
Hello, I use Nextcloud 12 with LDAP integration, and I would like to put a custom Group-Member association field (RestrictedMemberOf) but I cannot because you can only select from a given list of fields (memberOf, gidNumber, ...)
Would it be possible to put a custom field ?

**Comment by LukasReschke** [comment]
This is more suited for our forums at help.nextcloud.com. Thanks a lot!
