### ISSUE TITLE
Decrypt a file when username and password known

### ISSUE THREAD

**Issue by sm-iitk** [nextcloud/server#7217]
While testing encryption i found one issue and want to solve that.
1) I have an encryption (default) enabled fresh installation on centos7, mariadb, php 7.1 with nextcloud 12.0.3.3.
2) I wanted to move a large no of files from one directory to another (is it possible via GUI?). But to make it short (now i know it is a mistake) I did that  on the server directly from command line (mv command) in user directory.
3)After I found the file are not working in the new directory, i also tried to move back.
4) Disabling encryption, decrypt by user password does not work.
 5) I tried https://github.com/arno01/ocdec, but has following error
----------------------------------------------------------
hex string is too long
invalid hex iv value
unable to load Private Key
140189224130464:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:707:Expecting: ANY PRIVATE KEY
decryptFile():: The User Private Key is not good. Are you sure your ownCloud User Login password is correct?
---------------------------------------------------------
I want to decrypt the files. I have full access to the system.
Any support from next cloud team or community is appreciated.

Thanks

**Comment by LukasReschke** [comment]
This is more suited for our forums at help.nextcloud.com
