### ISSUE TITLE
Filter filenames by pattern - not working on Gentoo/Funtoo

### ISSUE THREAD

**Issue by llitz** [nextcloud/server#7219]
Gentoo/Funtoo linux uses webapp-config application to manage software installation. The current filter out of files is only working as exact match and this doesn't work.

Suggestion is to modify the owncloud patch (replacing owncloud with nextcloud) https://github.com/owncloud/core/commit/bf72f47c34b6e2579cfcbdcf4a582e42fd67c181

To fix the problem

### Expected behaviour
Do not trigger the security integrity on Gentoo based deployments for .webapp-nextcloud file

### Actual behaviour
Security Integrity check Fails

**Comment by skjnldsv** [comment]
Fixed in https://github.com/nextcloud/server/commit/abb56c72e1d63fe0e70e82c2b12032e0f923d191
