### ISSUE TITLE
Possibility to exclude sub(sub)-folders from user/group-sharing

### ISSUE THREAD

**Issue by Ninos** [nextcloud/server#7220]
A possibility would be awesome to exclude sub(sub)-folders from user/group-sharings.

### Reason
Lots of companies want to exclude users/groups the possibility to access some sub(sub)-folders (e.g. some specific projects, board documents, ...). They can share each subfolder, but that has following disadvantages:
1. Folder structure is not the same anymore for users/groups, because you need to share every single sub- or subsub-folder. With just excluding a subfolder the folder-structure will stay the same, just the excluded folder is missing.
2. New sub(sub)-folders in shared-folder will automatically be included into share. Sharing every sub(sub)-folder by its own for security reasons (see reason 1) will force admin, to also share the newly created sub(sub)-folder.

### Related
https://help.nextcloud.com/t/groupfolder-with-subtree-access-rights/23563

**Comment by LukasReschke** [comment]
Very closely related to https://github.com/nextcloud/server/issues/6050, closing as duplicate thus.
