### ISSUE TITLE
Can not detect https with CloudFlare Flexible SSL

### ISSUE THREAD

**Issue by ovear** [nextcloud/server#7221]
Hello, i found that it seems that NextCloud can not work with CloudFlare Flexible SSL fine after a unknown update. When i use Flexible SSL, NextCloud still use http://domain as a base domain, which caused "Content Security Policy" failed.
This solution is to use "X-Forwarded-Proto" to detect protocol, but NextCloud won't trust this at default, and 'trusted_proxies' section doesn't support CIRD which means there is no good method to add any public cdn ip range to this list.
https://github.com/nextcloud/server/issues/6550

### Steps to reproduce
1. Turn on CloudFlare Flexible
2. Open your website
3. That's it

### Expected behaviour
NextCloud use https://domain as a base domain.

### Actual behaviour
NextCloud use http://domain as a base domain.

### Server configuration

**Operating system**: Centos 6

**Web server:** Apache 2.4

**Database:** MySQL 5.7

**PHP version:** 5.6.30

**Nextcloud version:** (see Nextcloud admin page) 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** No

**Where did you install Nextcloud from:** Official website

**Signing status:**
<details>
<summary>Signing status</summary>

**Comment by MorrisJobke** [comment]
Please use the overwrite config options:

https://github.com/nextcloud/server/blob/master/config/config.sample.php#L391-L406

and 

https://github.com/nextcloud/server/blob/master/config/config.sample.php#L427-L435

If you need further help with your setup, please ask in the forums for help first: https://help.nextcloud.com/
