### ISSUE TITLE
Implement Cache-Control: immutable

### ISSUE THREAD

**Issue by mfr-itr** [nextcloud/server#7224]
### Steps to reproduce
1. Reload a nextcloud page, for example the Files app

### Expected behaviour
The js and css files have a file hash in the URL, for example `/css/core/eb4f51d7ec0ed68ba27ebcd1548755aa-server.css?v=a08c1ea900eef4f5e2c1cd1fd55d4117-0`. The browser shouldn't have to validate its cache since the file will never change.

### Actual behaviour
The browser issues a request, with a 304 response from the server

### Solution
Implement the [Cache-Control: immutable](https://bitsup.blogspot.fr/2016/05/cache-control-immutable.html) Cache-Control extension.

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
12.0.3

### Client configuration
**Browser: Firefox 57**

**Operating system: Archlinux**

It could also help with https://github.com/nextcloud/server/issues/2272.

**Comment by rullzer** [comment]
I'll look into this for NC14. We have to make sure it also still works in development so that the hash changes often enough (or just not be immutable when we are in debug mode?)

**Comment by mfr-itr** [comment]
Yes, it should only be on release mode.

**Comment by Yamakaky** [comment]
In fact, it shouldn't change anything since the hash in the file name changes after each modification. The link in the HTML will change, referencing the new file.
`immutable` should of course only be enabled for files with a hash in the file name, of course.

**Comment by mfr-itr** [comment]
Nice!
