### ISSUE TITLE
OCS Share API data empty

### ISSUE THREAD

**Issue by dachinat** [nextcloud/server#7227]
I have created several users and shared files between them

A request to `curl --http1.1 -u myadminuser:myadminpass -X GET 'https://myhost.com/ocs/v2.php/apps/files_sharing/api/v1/shares' -H "OCS-APIRequest: true"`

Results

```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>200</statuscode>
  <message>OK</message>
 </meta>
 <data/>
</ocs>
```

I have tried this according to

https://docs.nextcloud.com/server/12/developer_manual/core/ocs-share-api.html#ocs-share-api

There are no examples though. Could this be because I don't pass `userid`? Title in documentation says `Get all shares from the user.` but way how to pass `userid` in query is not documented

**Comment by dachinat** [comment]
I have just found out that `userid` comes from user:password I authenticate on request. This is kind of strange, being an administrator I would expect to get shares of different users with an API.

**Comment by rullzer** [comment]
The API works as intended. You get the shares for the current user.

What you are looking for is something else and should probably be implemented as an app. As I do not plan to clutter the ShareAPI even more.
