### ISSUE TITLE
Contacts not showing up in contacts app

### ISSUE THREAD

**Issue by jankkm** [nextcloud/server#723]
Since upgrading to nextcloud from owncloud 8.x I have problem with the contacts app. It is running on a shared hosting.
I have 462 contacts in my address book synced between multiple Apple devices which still works fine but the contacts web app just shows "No contacts in here". If I remove about 20 contacts it works and it does not matter which contacts I remove so this is not about a faulty contact.
I think this must be something with caching and the cache is probably too small to load all the contacts. This was not the case on owncloud 8.x

Any idea what the issue could be? Or how to get any more information? There is nothing interesting in the log.

**Comment by juliangieseke** [comment]
Bug @ Apple, try using the iOS&OSX caldav url shown in calendars.

**Comment by nickvergessen** [comment]
Can you check the database, whether the entries have been copied over?
Old table names `oc_contacts_addressbooks` + `oc_contacts_cards`,
new names `oc_addressbooks` + `oc_cards`

**Comment by jankkm** [comment]
@juliangieseke This is not it. The Applications by apple work fine. It is the web interface that doesn't.

@nickvergessen I checked: the new tables have been created and the new entries are copied over. The old tables still exist too.

I don't know if I described it clearly enough: It actually does work if there is less entries in the address book. I can just delete about 20 entries and it all works.

**Comment by nickvergessen** [comment]
AH, maybe it just takes too long to return them all and the UI gives up before

**Comment by nickvergessen** [comment]
Anyway, in this case it is a problem of the UI app and not of the DAV backend, so I'm closing this here.
Feel free to create an issue over in the contacts repo:
https://github.com/owncloud/contacts

**Comment by jankkm** [comment]
It does seem like that. Thanks.

**Comment by StephenVictor** [comment]
@jankkm Did you open an issue for this at https://github.com/nextcloud/contacts? I'm experiencing this issue with a new install of nextcloud 10.0.1, so I don't think it's just related to upgrading from owncloud.

**Comment by jankkm** [comment]
@StephenVictor I did open an issue over there:
https://github.com/owncloud/contacts/issues/478
The contacts app can't handle address books that are more than about 10mb in size. Apparently there are not too many people with a lot of photos in their address books
