### ISSUE TITLE
webdav was working, now almost unusably slow

### ISSUE THREAD

**Issue by kylepwarren** [nextcloud/server#7232]
I'm trying to think of what's changed...:
- I moved a bunch of files around
- I changed my password (I thought, maybe some brute force rate limiting could end up being the cause because of this, if the rate limit is per username, not ip...)**

libre office will eventually load paths, but it's extra slow, like >1 minute on LAN, when a day ago was <30 seconds even for the larger dirs. Other programs seem to reach some timeout before anything happens.

Any ideas?

update: I was just thinking, I have a reverse proxy going to this server, so all the IPs end up being the same**. I did notice the linux desktop "app[?]" connected right away when I temporarily disabled the 'brute force' prevention plugin. Also, later on, the file browser I have... what ever come with mate, started opening davs:// addresses (to the next cloud server I'm talking about) much faster. Libre office, still works, but it's still SLOW. slower than it was. I'm adding files always, just crossed[passed] around 35GB when this got so slow... 

Kodi wont connect now. 
I'm not 100% sure, but it seemed like libre office was still connecting before I put in the new, that I changed it to, password. Maybe it asked to to reenter it and I don't remember. 

I tried installing opcache and redis to see if that would help. It made the web ui way faster, but **didn't** seem to help with webdav.

**Comment by MorrisJobke** [comment]
> I changed my password (I thought, maybe some brute force rate limiting could end up being the cause because of this, if the rate limit is per username, not ip...)**

You could test this by disabling the brute force protection:

https://github.com/nextcloud/server/blob/master/config/config.sample.php#L232-L239

**Comment by kylepwarren** [comment]
I did, mentioned lower down in the [first/original] post:

> update: I was just thinking, I have a reverse proxy going to this server, so all the IPs end up being the same**. I did notice the linux desktop "app[?]" connected right away when I temporarily disabled the 'brute force' prevention plugin. 

It seemed to help the linux desktop app, but not libre office(still slow), or kodi (timeout)

**Comment by tflidd** [comment]
Can you check on your server logs if the clients try to access some resources with old passwords (4xx-errors). Did you monitor your server, CPU at 100%?

**Comment by kylepwarren** [comment]
It started working much better later on. *suspicion* There was something probably trying to access it w/ old password. However even after I disabled bruteforce protection it continued being pretty unresponsive for a while. I think the next day I restarted the server and things worked much more smoothly. I do still have intermittent access issues, mostly via webdav. Sometimes connections that have been working just stop working for 10 or 15 minutes. **There were lines in the error log about bad user/password**, but b/c of reverse proxy I don't really know where they were from, don't feel like checking the proxies logs, not even sure if it keeps that granularity very long, or if it would be useful. And I'm not sure which resource was being used, but the **system load was extremely high** during the most prolonged webdav outage. **note**: I have MUCH less ram then on recommendations, I think like 1.3GB.

**Comment by kylepwarren** [comment]
Thanks for the advice. I've set up the rp in the config, now the admin general page says this: "The reverse proxy headers configuration is incorrect, or you are accessing Nextcloud from a trusted proxy. If you are not accessing Nextcloud from a trusted proxy". That's a pretty big _or_. Maybe it will [somehow] help with the bruteforce rate limit issue, if that was the issue. The logs I was looking in before were apache access and php error. I don't think this will change anything in either of them. ...What difference should I notice when the reverse proxy is configured[in the config.php]? thanks
