### ISSUE TITLE
Weblogin flow: remove "stay logged in"

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#7234]
Add a new account on android and see this:

![2017-11-21-121420](https://user-images.githubusercontent.com/5836855/33069731-ba3ec484-ceb5-11e7-8b83-74470d420519.png)

"stay logged in" is confusing, so it should be removed.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by MorrisJobke** [comment]
Fixed by #7590
