### ISSUE TITLE
user_external not updated in 13.0.0beta1 tarball

### ISSUE THREAD

**Issue by Sp1l** [nextcloud/server#7237]
### Steps to reproduce
1. Install 13.0.0 BETA 1
2. php ./occ upgrade
3.

### Expected behaviour
Upgrade success

### Actual behaviour
```
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
UnexpectedValueException: The files of the app "user_external" were not correctly replaced before running the update
Update failed
Maintenance mode is kept active
Reset log level
```
After patching apps/user_external/appinfo/info/xml
> <nextcloud min-version="12" max-version="13" />
I can continue with the upgrade. The app isn't updated for 13 yet https://github.com/nextcloud/apps/blob/master/user_external/appinfo/info.xml

### Server configuration

**Operating system**: FreeBSD 11.1-p1 amd64

**Web server:** Apache 2.4.29 HTTP/2

**Database:** MariaDB 10.2.10

**PHP version:** 7.1.11

**Nextcloud version:** 13.0.0beta1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 12.0.3

**Where did you install Nextcloud from:**
FreeBSD package, generated from https://download.nextcloud.com/server/prereleases/nextcloud-13.0.0beta1.bz2

**Signing status:**
<details>
<summary>Signing status</summary>

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- twofactor_totp
	- INVALID_HASH
		- appinfo/info.xml
- user_external
	- INVALID_HASH
		- appinfo/info.xml

Raw output
==========
Array
(
    [twofactor_totp] => Array
        (
            [INVALID_HASH] => Array
                (
                    [appinfo/info.xml] => Array
                        (
                            [expected] => 74790f511d0da5d40ea352f690032db642cf211c1ef971bd7a3eaf376e479fe55c86257383a448260219cf662faad1d6757309786b93dc9fabb20d4d2f02a7a7
                            [current] => 14a3e8e93dbf88af3201de9cc3c898dafbc1cfc72f510956e2481497519c5bebf95198bbaf39b0becfe491ff8783e59618ff48e9b45ce6b432cd04d2b5228491
                        )

                )

        )

    [user_external] => Array
        (
            [INVALID_HASH] => Array
                (
                    [appinfo/info.xml] => Array
                        (
                            [expected] => e39e187850edf4ddaf8502085a5521fd2cd1bfe57f6bb908bbf9914d0cfc8593ab4aaecbc550d47108a5269f2dc63e66f15a6b5f70c1826dccb68b8bf5853bd1
                            [current] => dce0b2bdc946b836f18ee5eb4c26ac05e1fcc369404805e74f75a18901041b8fad4f5b735df93f764117ced975768e622e27df884045166e12da96e5ef458540
                        )

                )

        )

)
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
@LukasReschke Is this shipped for some reason?

**Comment by MorrisJobke** [comment]
Fix is in https://github.com/nextcloud/apps/pull/43
