### ISSUE TITLE
Share still exists after source file gets deleted

### ISSUE THREAD

**Issue by Emi94** [nextcloud/server#7238]
### Steps to reproduce
1. Share a file with a user
2. Delete the shared file

### Expected behaviour
Share should be deleted from DB

### Actual behaviour
Share still exists in DB table oc_share

### Server configuration

**Operating system**:Ubuntu 16.04
**Web server**:Apache2
**Database**:PostgreSQL
**PHP version**:php 7.0
**Nextcloud version**: 12.0.3
**Updated from an older Nextcloud/ownCloud or fresh install**:updated from older nextcloud
**Where did you install Nextcloud from**:https://nextcloud.com/install/
**Are you using an external user-backend, if yes which one**: LDAP

This lead to one user having a broken share in "Shared with others" folder:
![errant_folder](https://user-images.githubusercontent.com/11816318/33074701-d7c21cd0-cecf-11e7-88b4-4108de3c9984.jpg)
I managed to get rid of it by manually deleting the share from DB table oc_share. 

I would recommend for nextcloud to check when deleting a file, if it is shared. If yes then delete the share from DB too.

**Comment by LukasReschke** [comment]
cc @schiessle @icewind1991

**Comment by skjnldsv** [comment]
Still happens

**Comment by joepitt91** [comment]
A cron based check as well as on delete would be good, e.g. if users have shared something on external storage and the shared folder gets deleted or moved outside of Nextcloud

**Comment by aignerat** [comment]
just ran into that issue and got some ideas I want to point out:

if trashbin is active only delete share when the file gets finally removed
if trashbin is not active delete shares on file-removal

In that step it would be great to validate possible errors from remnants. I had the idea to move the filecache, storage and shares from the oc-tables to oc_xxx_remnants. That way the stability of the system's services like fulltextsearch could be better, even without removing remnants.

**Comment by nikkilocke** [comment]
When is this going to be fixed?
What measures can I take to remove the shares of deleted folders from 1,000 users, because someone shared a folder then deleted the folder without unsharing it first?

**Comment by kesselb** [comment]
cc @skjnldsv I removed the milestone. Please reschedule ;)

**Comment by chaosgrid** [comment]
I think this bug has been fixed for normal files (could not reproduce), but files within group folders still have this problem when using trashbin/deleted files app. See #29328

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by LM-vb** [comment]
This still/again (?) happens on 29.0.3 for both files and folders.

At least orphaned links can be deleted on the command line now: `occ sharing:delete-orphan-shares`

**Comment by szaimen** [comment]
Hi, please open a new issue for this. Thanks!
