### ISSUE TITLE
Repair steps in dav app likely not used

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/server#724]
I was reading through the info parser to find out more about the repair steps and stumbled over https://github.com/nextcloud/server/blob/stable10/lib/private/App/InfoParser.php#L128 which uses **step** as element name for the class to be executed.

However the dav app (only app which uses repair steps) uses **job** https://github.com/nextcloud/server/blob/stable10/apps/dav/appinfo/info.xml#L25 

This looks like a copy paste error, correct? 

@DeepDiver1975 @MorrisJobke @nickvergessen @PVince81

**Comment by nickvergessen** [comment]
yes :+1:  :see_no_evil:
