### ISSUE TITLE
Input field for comments is not disabled when a new comment is being sent

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#7240]
Since [the change of the text area to a content editable div](https://github.com/nextcloud/server/commit/ec5607544c32797901f82c4e06161938a50fe322) the input field is no longer disabled while a new comment is being sent.

The problem seems to come from [trying to disable the div still using the _disable_ property](https://github.com/nextcloud/server/blob/2b4b3b1986e58305c08941f77a693a80cc3d5b85/apps/comments/js/commentstabview.js#L623); I guess that the right way to disable a content editable div would be by setting `contenteditable=false`, but that would need support in the [core input.scss file](https://github.com/nextcloud/server/blob/bd7d0de86f93bcdf0a521544a92795d5725f57f4/core/css/inputs.scss) so it has the same appearance of an input field with the _:disabled_ pseudo-class.

@blizzz @nextcloud/designers

**Comment by jancborchardt** [comment]
@danxuliu @blizzz if you open a PR to fix the Javascript, we can add the CSS fix there too. :)

**Comment by danxuliu** [comment]
>  if you open a PR to fix the Javascript, we can add the CSS fix there too. :)

I take your word: #7266 ;-)
