### ISSUE TITLE
New shares should be added at the top of the list

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#7242]
### Steps to reproduce

1. Open the sidebar to share a file that has already been shared 20 times
2. Share the file

### Expected behaviour

I should see the share I've just created at the top of my list of shares for that file

### Actual behaviour

I can't see the new share because it's been added at the bottom of the list and the sidebar only shows me the top 10 (?) shares

**Comment by skjnldsv** [comment]
Fixed with https://github.com/nextcloud/server/pull/15719
