### ISSUE TITLE
Wrong position of the contacts menu for comment authors

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#7250]
In the _Comments_ app the contacts menu is shown when clicking on the name of a comment author (and which is not the current user). However, since commit 2348d14e48d2482343bcc111347efcdd53c0faf8 from #7051 (great work, by the way ;-) ), the menu appears in a wrong position.

@skjnldsv

Before commit:
![contactsmenu-before](https://user-images.githubusercontent.com/26858233/33138661-5986e35a-cfab-11e7-952e-67fb3902d01f.png)

After commit:
![contactsmenu-after](https://user-images.githubusercontent.com/26858233/33138684-61923414-cfab-11e7-8d42-463e99ebe061.png)

**Comment by skjnldsv** [comment]
> great work, by the way
Thanks 😊 

Fix is in #7251
