### ISSUE TITLE
Tooltips shown in a notification alter its layout

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#7253]
The notification received when the user is mentioned in a comment contains the name of the file where she was mentioned, and hovering on the name shows a tooltip with the full path to the file.

However, when the tooltip is shown the layout of the notification changes (in the screenshots below notice how _comment_ appears in the second line, and the tooltip arrow in fact points to the previous position of the file name).

That layout change causes a "jumpy" effect: if you hover on the file name the tooltip is shown, but then the position of the file name changes, which could cause the cursor to no longer be hovering on the file name, which would cause the tooltip to be hidden and that would cause the file name position to change again, thus making the cursor to be hovering on the file name, which would show the tooltip...

@nextcloud/designers 

Tooltip not shown:
![notification-tooltip-hidden](https://user-images.githubusercontent.com/26858233/33157588-7be66c42-d003-11e7-9ed0-932dd0134f7e.png)

Tooltip shown:
![notification-tooltip-shown](https://user-images.githubusercontent.com/26858233/33157589-7e52d114-d003-11e7-914e-e3f107b7475d.png)

**Comment by jancborchardt** [comment]
Is this rather an issue for https://github.com/nextcloud/notifications ? Or does it also happen in comments etc?

**Comment by danxuliu** [comment]
>  Is this rather an issue for https://github.com/nextcloud/notifications ?

:facepalm: Indeed, it is an issue for https://github.com/nextcloud/notifications I thought they were part of the server... It was late, I was sleepy, don't judge me :-P

Here it is: nextcloud/notifications#100
