### ISSUE TITLE
Self mentions are allowed during edition but not in final comment

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#7254]
Self mentions behaviour should be unified, either by disabling them during edition or by enabling them in final comments.

@blizzz

![comment-self-mention](https://user-images.githubusercontent.com/26858233/33157799-fbe80314-d004-11e7-90e1-1e2e9f5c12a5.png)

**Comment by blizzz** [comment]
they should be filtered out. That's why it does not work in the final comments. Github does not list offer yourself for completion, however does it when rendering. Exactly vice-versa to what we have now ;) Turning it around does not since you don't (necessarily) know your userid. So I guess we should filter it out, instead of allowing it, to follow our original path. Confirmed, @jancborchardt ?

**Comment by jancborchardt** [comment]
Yeah, yourself should of course be filtered out of the suggestions, just like in sharing.

However it's fine to show it markupped when you mention yourself in the finalized comment (maybe also when you do it while writing, but not if it's extra work to check).

**Comment by nickvergessen** [comment]
Well if it was allowed, you could click on the user name there and get teh user info popup which allows you to email, talk, ... people on the instance, so I could see usecases for it.

**Comment by jancborchardt** [comment]
@nickvergessen yeah, this is about self-mentions though – and mailing or Talk-ing to yourself is not really a thing? ;)

When you click on your own name/avatar, the dropdown options should rather be show as "It's you" and "Edit profile". cc @georgehrke

**Comment by nickvergessen** [comment]
Maybe I misunderstood, I thought the problem is that for everyone the dropdown is not rendered if author === mentioned.
Or is it dropdown not rendered if mentioned === current user?

**Comment by danxuliu** [comment]
@nickvergessen 
>  I thought the problem is that for everyone the dropdown is not rendered if author === mentioned.

You are right, self mentions are not rendered either when seen by other users, as [if _author === mentioned_ the mentions is filtered by the server](https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/lib/private/Comments/Comment.php#L236).

>  Or is it dropdown not rendered if mentioned === current user?

Originally I was referring to the inconsistent behaviour in this case; in any case I agree that self mentions should be rendered at least when seen by a different user.
