### ISSUE TITLE
Invalid HTML markup for mentioned users in comments

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#7255]
User mentions contain a `div` element (the avatar) inside a `span` element (the wrapper for both avatar and user name) [in the list of mention suggestions](https://github.com/nextcloud/server/blob/2b4b3b1986e58305c08941f77a693a80cc3d5b85/apps/comments/js/commentstabview.js#L199-L213) and [in the mentions themselves](https://github.com/nextcloud/server/blob/2b4b3b1986e58305c08941f77a693a80cc3d5b85/apps/comments/js/commentstabview.js#L442-L453).

I do not know if it would be better to show the avatar using a `span` or to change its parent `span` elements to `div` elements (which would require some CSS changes too); however, the contacts menu element, which is a `div`, is created inside the wrapper for both avatar and user name, so maybe the second alternative is better to also solve this markup problem.

@blizzz @jancborchardt

**Comment by pixelipo** [comment]
I think `.avatar` should be `span` in both cases - same as in core/js/share.js (line 210) In fact, semantically, it should be `span` even more than in the Files app because it is fully in-line content.

I'm not sure what to do about the popover, though :disappointed: 

Also, there is another parent span `.atwho-inserted` that looks like it should be removed or merged with the `.avatar-name-wrapper`

**Comment by blizzz** [comment]
Actually I copy-pasted 🙊 the avatar-formatting-HTML from somewhere else. Best would be to get this consolidated and reusable in one place. The div then can be transformed to span, I guess. 

> Also, there is another parent span .atwho-inserted that looks like it should be removed or merged with the .avatar-name-wrapper

That's from the Notification-Insertion lib, and is being auto-created. And it contains more than just the .avatar-name-wrapper, so leave it.

**Comment by skjnldsv** [comment]
Not seeing this anymore.
![Capture d’écran_2019-06-06_16-41-05](https://user-images.githubusercontent.com/14975046/59041954-e7081e00-8879-11e9-8584-0bfbd176b739.png)
