### ISSUE TITLE
Small adjustments needed to the login screen

### ISSUE THREAD

**Issue by pixelipo** [nextcloud/server#7265]
Copied from https://github.com/nextcloud/server/pull/7249#issuecomment-346616212

OK, here's my ~~review~~ opinion. I'm adding it as a comment since it's not breaking issues, but I would like to see these fixed:

1. Logo is too high up; actually, its distance from top is OK, but now it's too far from the `form` itself:
![image](https://user-images.githubusercontent.com/4129927/33174321-d5f68a7e-d057-11e7-94af-59d462ad5bb1.png)
I would remove 16px top+bottom margins from `form {}` in guest.css since they don't seem needed
2. Is there a reason why `footer` has `height: 70px`? We can easily remove it (I think) and change the `p.info {margin: 0 auto; padding-top: 20px;` to simpler `p.info {margin: 20px auto;}` Added advantage to these changes would mean that the whole page would fit nicely on 320*480 screen:
![image](https://user-images.githubusercontent.com/4129927/33174595-fec88136-d058-11e7-9d0b-da60bbbba8b7.png)

3. "Wrong password " warning is above the `#submit# button, but the `#lost-password` warning is bellow - makes no sense at all:
![image](https://user-images.githubusercontent.com/4129927/33174522-b2ccac9e-d058-11e7-9fc5-ab578401541d.png)
4. Additionally, "Lost Password" warning also has `opacity: .7;` added to it for some reason.

**Comment by rpirritano** [comment]
@pixelipo  Is this still available?  If so I can take it?

**Comment by pixelipo** [comment]
Yes it is, @rpirritano - be my guest :)

**Comment by rpirritano** [comment]
@pixelipo , 
For item #3 above, do you want the Wrong Password warning to no longer appear on that page or do you just want it to remain, but right above lost-password warning?

**Comment by pixelipo** [comment]
Ot should definitely appear under all the buttons. Ideally, it should also disappear as soon as "Forgot password?" button is clicked. That way, only one error should be visible at any given moment.

**Comment by rpirritano** [comment]
I completed all the above changes, submitted the pull request.

**Comment by juliushaertl** [comment]
Fixed with #7650
