### ISSUE TITLE
Changed LDAP group name doesn't appear in nextCloud

### ISSUE THREAD

**Issue by stephan-a** [nextcloud/server#7267]
Renaming a LDAP group doesn't get visible in nextCloud.

 
### Steps to reproduce
1. Login with LDAP user "testuser" which is a member of the LDAP group "testgroup"
2. Rename the LDAP group "testgroup" to "testgroup-renamed"
3. Login again with user "testuser" and check the group name inside "Personal"

### Expected behaviour
The following text gets displayed under "Personal / Groups": You are member of the following groups: **testgroup-renamed**

### Actual behaviour
Under "Personal / Groups" the following text is displayed: You are member of the following groups: **testgroup**
In the list of users ("Users") the old group name is still displayed, too.

**What's really interesting**: I've had a look at the database table "oc_ldap_group_mapping". In the column "ldap_dn" the new CN of the group is displayed, but in column "owncloud_name" there is still the old group name. So nextCloud definitely knows that this is the same group. Otherwise I would expect an additional group "testgroup-renamed" next to "testgroup". But there is only one, so why nextCloud doesn't update the internal/displayed group name as well?
Is there any possibility to trigger the update of LDAP group names in nextCloud?

### Server configuration

**Operating system**: Ubuntu 16.04.3 LTS

**Web server:** Apache/2.4.18

**Database:** MySQL 5.7.20

**PHP version:** 7.0.22

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from v11.0.3

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory

**Comment by MorrisJobke** [comment]
cc @nextcloud/ldap

**Comment by blizzz** [comment]
Long story short,  there is no support for group display names. The current names work as IDs.

Actually, there is some in the  backing infrastructure,  but nothing really that supports it. It is a reasonable wish and this could be looked into for 14 (if someone™️ can spend some time on it).

**Comment by stephan-a** [comment]
That would be great if anyone could spend time on that enhancement, thank you.

In our case the names of the LDAP groups created when we set up the nextCloud instance (okay, at that time it was ownCloud) are no longer meaningful enough and have a different spelling, so we wanted to change them recently to make them look the same in spelling and make them more meaningful.

**Comment by vahem2lu** [comment]
Just edit displayName in AD/LDAP and you're good to go, yes?

**Comment by DanScharon** [comment]
Is there any progress on this? Is there still no support for group display names?

**Comment by blizzz** [comment]
Please test https://github.com/nextcloud/server/issues/7267

**Comment by blizzz** [comment]
Done for Nc 17
