### ISSUE TITLE
Share icons overlay breadcrumbs and popover menu

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#7270]
Breadcrumbs:

![bildschirmfoto vom 2017-11-23 17-25-26](https://user-images.githubusercontent.com/3404133/33187434-fd6ff538-d091-11e7-8923-45516c124350.png)

Add new popover menu:
![bildschirmfoto vom 2017-11-23 17-26-04](https://user-images.githubusercontent.com/3404133/33187435-fd8c4918-d091-11e7-9355-d64732f1407b.png)

@nextcloud/designers

**Comment by MorrisJobke** [comment]
How to see those avatars in the file list? I only have them in the "shared by/with you" sections.

**Comment by juliushaertl** [comment]
@MorrisJobke They appear on items that were shared with me by other users on beta1. Both on the shared folder as well as all files inside of the folder.

**Comment by rullzer** [comment]
I think this is fixed on master.... @juliushaertl can you confirm?

**Comment by juliushaertl** [comment]
Yes, works fine on master now.
