### ISSUE TITLE
drag and drop problem

### ISSUE THREAD

**Issue by diegogregisdavila** [nextcloud/server#7278]
### Steps to reproduce
1. Create a "xpto" file at the root of the user.
2. Create a "abcd" directory at the root of the user.
3. create a directory on the client machine / desktop with the name "xpto" with some content.
4. Access the chrome and drag and drop the "xpto" directory from your desktop to the "abcd" directory from the root of the user.

### Expected behaviour
nexcloud should upload the directory normally.
### Actual behaviour
In the web application nextcloud (12.0.3) a file with the name "xpto" was created in the root of the user. After that, a directory with the name "abcd" was created in the root of the user.
This is done by creating a directory on the workstation (ubuntu 16 x64) with the name "xpto" and adding any content.
Now when drang and drop from the "xpto" directory created on the workstation and its contents to the directory created in nextcloud "abcd" from the root of the user is generated, the following error is generated on the user screen for each file inside the directory: "Unauthorized".

Extra Information:
If the user before doing the drag and drop access the directory "abcd" in the web application nextcloud the action works normally.

### Server configuration

**Operating system**: Debian GNU/Linux 8.8 (jessie) x86_64 3.16.0-4-amd64

**Web server:**  apache2  2.4.10-10+deb8u11  amd64   Apache HTTP Server

**Database:** postgresql-9.4  9.4.15-0+deb8u1

**PHP version:**   php5   5.6.30+dfsg-0+deb8u1

**Nextcloud version:**  12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**   fresh install

**Where did you install Nextcloud from:** 

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
 No errors have been found.

</details>

**List of activated apps:**
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - onlyoffice: 1.1.4
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - sharebymail: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "123456789",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "enable_avatars": false,
        "trusted_domains": [
            "127.0.0.1",
            "my_domain1",
            "my_domain2"
        ],
        "trusted_proxies": [
            "IP"
        ],
        "datadirectory": "\/opt\/data\/my_folder",
        "overwrite.cli.url": "https:\/\/my_domain",
        "dbtype": "pgsql",
        "version": "12.0.3.3",
        "dbname": "db_name",
        "dbhost": "IP:5432",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "overwriteprotocol": "https",
        "loglevel": 1,
        "asset-pipeline.enabled": false,
        "ldapIgnoreNamingRules": false,
        "ldapUserCleanupInterval": 0,
        "mail_smtpmode": "smtp",
        "mail_from_address": "root",
        "mail_domain": "mail.domain",
        "mail_smtphost": "host_smtp",
        "mail_smtpport": "25",
        "has_internet_connection": false,
        "trashbin_retention_obligation": "30, auto",
        "trashbin_auto_expire": true,
        "activity_expire_days": 30,
        "check_for_working_htaccess": true,
        "enable_previews": false,
        "theme": "mydrive",
        "default_language": "pt_BR",
        "maintenance": false,
        "help": "https:\/\/my_domain\/html",
        "3rdpartyroot": "\/var\/www\/nextcloud\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "versions_retention_obligation": "30, auto",
        "tempdirectory": "\/tmp",
        "syslog_tag": "nextcloud",
        "log_type": "syslog",
        "minimum.supported.desktop.version": "2.0.0",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "IP",
            "port": 6379
        },
        "htaccess.RewriteBase": "\/",
        "updatechecker": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "sharing.minSearchStringLength": 3,
        "appstoreenabled": false
    }
}

<details>
<summary>Config report</summary>

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** yes - nfs

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** yes - LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Google Chrome - 54.0.2840.100 (64-bit)

**Operating system:**
   Ubuntu 16 (64-bit)

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
[23/Nov/2017:17:17:51 -0200] 127.0.0.1 - - ip_server 119947 154841 "MKCOL /remote.php/webdav/abcd HTTP/1.1" "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36" 405 247 
[23/Nov/2017:17:17:51 -0200] 127.0.0.1 - - ip_server 119947 160696 "PROPFIND /remote.php/webdav/abcd HTTP/1.1" "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36" 207 925 
[23/Nov/2017:17:17:51 -0200] 127.0.0.1 - - ip_server 119960 267700 "MKCOL /remote.php/webdav/abcd/xpto HTTP/1.1" "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36" 201 - 
[23/Nov/2017:17:17:51 -0200] 127.0.0.1 - - ip_server 119960 100765 "PUT /remote.php/webdav/abcd/xpto/zimbra_talk_download_2018.png HTTP/1.1" "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36" 401 222 
[23/Nov/2017:17:17:51 -0200] 127.0.0.1 - - ip_server 119960 95285 "PUT /remote.php/webdav/abcd/xpto/firefox_56.png HTTP/1.1" "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36" 401 222 
[23/Nov/2017:17:17:52 -0200] 127.0.0.1 - - ip_server 119960 106895 "PUT /remote.php/webdav/abcd/xpto/Logo%20Drive%203.png HTTP/1.1" "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36" 401 222 
[23/Nov/2017:17:17:52 -0200] 127.0.0.1 - - ip_server 119960 96357 "PUT /remote.php/webdav/abcd/xpto/users.png HTTP/1.1" "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36" 401 222 
[23/Nov/2017:17:17:52 -0200] 127.0.0.1 - - ip_server 119960 153949 "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2F HTTP/1.1" "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.100 Safari/537.36" 200 231
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
<10>1 2017-11-23T17:15:37.166310-02:00 server-name nextcloud 119955 - -  {webdav} {"reqId":"7I8GMn7qAramEgTACdZh","level":4,"time":"2017-11-23T19:15:37+00:00","remoteAddr":"127.0.0.1","user":"my_user","app":"webdav","method":"MKCOL","url":"\/remote.php\/webdav\/abcd","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\MethodNotAllowed\",\"Message\":\"The resource you tried to create already exists\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(590): Sabre\\\\DAV\\\\Server->createCollection('abcd', Object(Sabre\\\\DAV\\\\MkCol))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/nextcl...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1181}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/54.0.2840.100 Safari\/537.36","version":"12.0.3.3"}
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by MorrisJobke** [comment]
@rullzer

**Comment by putt1ck** [comment]
Possibly related (12.04): if you drag and drop a folder to a sub folder, UI creates the sub-subfolder but not all the file content, and an "unauthorized" pop-up occurs for each failed file in the drag and dropped folder (see attached screenshot).

![image](https://user-images.githubusercontent.com/2872580/35679392-c5c7ab3c-074e-11e8-8bcc-636d3bf77e10.png)

Each file displays the uploading process before the unauthorized message. Files that fail are not uploaded (not present in server file system).

Associated log error is:
"app":"webdav","method":"MKCOL","url":"\/nextcloud\/remote.php\/webdav\/Test%20dragdrop%20folder\/sub%20folder","message":"Exception: {\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\MethodNotAllowed\",\"Message\":\"The resource you tried to create already exists\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(590): Sabre\\\\DAV\\\\Server->createCollection('Test dragdrop f...', Object(Sabre\\\\DAV\\\\MkCol))\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpMkcol(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:MKCOL', Array)\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(76): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/nextcloud\\\/remote.php(162): require_once('\\\/var\\\/www\\\/nextcl...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php\",\"Line\":1181}"

**Comment by putt1ck** [comment]
The issue remains in 13RC4, symptoms identical but the error popup now reads "CSRF check not passed"

**Comment by putt1ck** [comment]
Suggested fix: prevent dropping of folders to sub folders (as with trad file explorer software the accidental dropped in the wrong subfolder is one of the biggest sources of "my files have been lost" user reports)

**Comment by diegogregisdavila** [comment]
tks.
