### ISSUE TITLE
File picker dialog is missing buttons in latest Nextcloud 13 Beta

### ISSUE THREAD

**Issue by onny** [nextcloud/server#7282]
Hey,
the file picker dialog is missing a close or save button:
![2017-11-22-125411_swaygrab](https://user-images.githubusercontent.com/757752/33126343-747aa31c-cf84-11e7-94ac-efb245416502.png)
I'm using Nextcloud Beta 13 and the latest mail app (from git).

Best regards,
Jonas

**Comment by MorrisJobke** [comment]
It is there in files:

```js
OCdialogs.filepicker();
```

![bildschirmfoto 2017-11-27 um 08 02 45](https://user-images.githubusercontent.com/245432/33254535-6fc28db2-d349-11e7-8ed7-a54e5d269933.png)


@nextcloud/mail Maybe it's how you call the file picker?

**Comment by ChristophWurst** [comment]
Yup, seems like we call it with more parameters: https://github.com/nextcloud/mail/blob/c1287afc8e5ecb497dca90ce634d693b342edd7a/js/controller/messagecontroller.js#L124-L146

**Comment by MorrisJobke** [comment]
But even then the button is there on master:

![bildschirmfoto 2017-11-27 um 08 23 31](https://user-images.githubusercontent.com/245432/33255111-4bc41aea-d34c-11e7-9afd-30d5a3b043b5.png)

```js
OC.dialogs.filepicker(
				t('mail', 'Choose a folder to store the attachment in'),
				function(path) {
					if (typeof callback === 'function') {
						callback();
					}
					Radio.message.request('save:cloud', account,
						folder, messageId, attachmentId, path).then(function() {
						if (saveAll) {
							Radio.ui.trigger('error:show', t('mail', 'Attachments saved to Files.'));
						} else {
							Radio.ui.trigger('error:show', t('mail', 'Attachment saved to Files.'));
						}
						resolve();
					}, function() {
						if (saveAll) {
							Radio.ui.trigger('error:show', t('mail', 'Error while saving attachments to Files.'));
						} else {
							Radio.ui.trigger('error:show', t('mail', 'Error while saving attachment to Files.'));
						}
						reject();
					});
				}, false, 'httpd/unix-directory', true);
```

**Comment by ChristophWurst** [comment]
@MorrisJobke you're right. It's definitely only happening in Mail. There seem to be other issues too 
![bildschirmfoto von 2017-11-27 08-35-19](https://user-images.githubusercontent.com/1374172/33255518-5547b368-d34e-11e7-8957-db2bac310bfa.png)

Let's continue in https://github.com/nextcloud/mail/issues/626.
