### ISSUE TITLE
Client rescans+downloads all the files after a encrypt-all/decrypt-all

### ISSUE THREAD

**Issue by Ninos** [nextcloud/server#7283]
### Expected behaviour

The occ encrypt-all/decrypt-all is used to encrypt/decrypt all the files of user(s). It is mostly used when an admin want to enable/disable server-side encryption.
encrypt-all/decrypt-all only encrypts/decrypts the files but they shall be seen has unchanged by the user (modified date).
So after a encrypt-all/decrypt-all, the client shall not reload all the files.

### Actual behaviour

After having occ encrypt-all/decrypt-all users, the client reloads ALL the files, the files modified date is changed.

### Steps to reproduce
1. Files decrypted/encrypted on the server
2. Start a procedure to encrypt-all/decrypt-all via shell
3. When encrypt-all/decrypt-all is finished, client starts to sync ALL the files, whatever they have changed or not.

### Server configuration

Operating system: DEBIAN 8
Web server: APACHE 2
Database: MYSQL
PHP version: 7.0
nextcloud version: 12

Storage backend (external storage): NONE

PS: This issue was copied from https://github.com/owncloud/client/issues/5686

**Comment by MorrisJobke** [comment]
> After having occ encrypt-all/decrypt-all users, the client reloads ALL the files, the files modified date is changed.

@schiessle @icewind1991 Could we turn this off?

**Comment by Croydon** [comment]
This is really annoying as it can cause huge amounts of traffic.

**Comment by icewind1991** [comment]
The encryption app would either have to set all etags back after writing to the files, or bypass the etag updates altogether when doing it's decryption (meaning probably having to work directly with the underlying storage)

**Comment by danger89** [comment]
Is it solved by ownCloud issue https://github.com/owncloud/client/issues/5686? They are checking the hashes now..

**Comment by skjnldsv** [comment]
@nextcloud/desktop is this fixed from https://github.com/owncloud/client/issues/5686 ?

**Comment by er-vin** [comment]
> @nextcloud/desktop is this fixed from [owncloud/client#5686](https://github.com/owncloud/client/issues/5686) ?

Yes, checked the code just now and the client should be verifying mtime and hash before a download (corresponding code is from 2017).
