### ISSUE TITLE
Encryption/Decryption not working on versioned files

### ISSUE THREAD

**Issue by Ninos** [nextcloud/server#7284]
### Expected behaviour

The occ encrypt-all/decrypt-all is used to encrypt/decrypt all the files of user(s). It is mostly used when an admin want to enable/disable server-side encryption.
encrypt-all/decrypt-all shlould also encrypt/decrypt the versioned files. So after a encrypt-all/decrypt-all, the client shall also be able to open versioned files.

### Actual behaviour

After having occ encrypt-all/decrypt-all users, the client cannot access versioned files anymore or versioned files are not encrypted (encrypt-all).

### Steps to reproduce
1. Files decrypted/encrypted on the server
2. Start a procedure to encrypt-all/decrypt-all via shell
3. When encrypt-all/decrypt-all is finished, versioned files should be encrypted/decrypted, but are not.

### Server configuration

Operating system: DEBIAN 8
Web server: APACHE 2
Database: MYSQL
PHP version: 7.0
nextcloud version: 12

Storage backend (external storage): NONE

PS: I think it's a general problem with encryption and versioned files (think versioned files are always untouched, just an old copy...). May this problem also exists with encryption enabled and changed shared keys...

**Comment by Ninos** [comment]
May related #7283

**Comment by MorrisJobke** [comment]
cc @nextcloud/encryption

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
