### ISSUE TITLE
No progress bar during file upload using Microsoft Edge

### ISSUE THREAD

**Issue by Goore25** [nextcloud/server#7286]
### Steps to reproduce
Just use Microsft Edge for uploading file to Nextcloud server.
I tired with:
Win10 (Creators Fall Update 1709, build 16299.19) and MS Edge 41.16299.15.0 (EdgeHTML 16.16299)
Win10 (1703, build15063.726) and MS Edge 40.15063.674.0 (EdgeHTML 15.15063)

### Expected behaviour
Progress bar should show the upload status graphically

### Actual behaviour
There is only text message for wating xxx minutes or a few seconds

### Server configuration

**Operating system**: Ubuntu 16.04.3

**Web server:** Apache 2.4.18

**Database:** MySQL

**PHP version:** 7.0.22

**Nextcloud version:** (see Nextcloud admin page) 12.0.3, 12.0.4RC1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install from OVA, the updated to 12.0.4RC1

**Where did you install Nextcloud from:** https://www.techandme.se/nextcloud-vm/

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Enabled:
  - announcementcenter: 3.1.1
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_automatedtagging: 1.2.2
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_trashbin: 1.2.0
  - groupfolders: 1.1.0
  - impersonate: 1.0.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - previewgenerator: 1.0.7
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
         ],
        "datadirectory": "\/var\/ncdata",
        "overwrite.cli.url": "https:\/\/nextcloud\/",
        "dbtype": "mysql",
        "version": "12.0.4.0",
        "dbname": "nextcloud_db",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "log_rotate_size": "10485760",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "htaccess.RewriteBase": "\/",
        "loglevel": "2",
        "log_type": "file",
        "logfile": "\/var\/ncdata\/nextcloud.log",
        "logtimezone": "Europe\/Prague",
        "mail_from_address": "share",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "",
        "mail_smtphost": "",
        "mail_smtpport": "25",
        "knowledgebaseenabled": false,
        "skeletondirectory": "\/var\/www\/nextcloud\/core\/skeleton_icz",
        "updater.release.channel": "beta",
        "default_language": "en",
        "force_language": "en",
        "theme": ""
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

Win10 (Creators Fall Update 1709, build 16299.19) and MS Edge 41.16299.15.0 (EdgeHTML 16.16299)
Win10 (1703, build15063.726) and MS Edge 40.15063.674.0 (EdgeHTML 15.15063)

Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
For me there is a upload bar on master (upcoming 13):

![bildschirmfoto 2017-11-27 um 08 19 38](https://user-images.githubusercontent.com/245432/33254984-bd846ffa-d34b-11e7-8694-4c77da1601e8.png)

Seems to be related to 12. There is only a "Uploading...". I would close this as fixed in 13, because we did some restructuring of how the upload works now and not backport this new feature.

**Comment by Goore25** [comment]
Hi, I tried today with version 13.0.0.6 (13.0.0 Beta1 from 3.12.2017 - Daily) and there is no progress bar in MS Edge again...
