### ISSUE TITLE
Error when Uploading to shared-folder mounted as external smb-storage

### ISSUE THREAD

**Issue by rgl1234** [nextcloud/server#7290]
### Steps to reproduce
1. Mount External-SMB Storage as admin-User from Windows-Server
2. Share a Folder X as admin-User to normal-user with edit-permissions
3. upload a file as normal-user to newly-shared folder (or place a comment on file in the newly-shared folder)

### Expected behaviour
Upload of files should work without any problems or errors as normal user to the shared folder

### Actual behaviour
Upload is working, but I always get the following error in the nextcloud-logs when I upload a sample-file to a sample shared folder "Einkauf":

Error | no app in context | Icewind\SMB\Exception\NotFoundException: Invalid request for **/Einkauf/Einkauf/**sample.png (NotFoundException)
-- | -- | --

I recognized this error, as I tried to activate an "automated tagging rule" for some file types. Always when the rule applies to a specific file, I get an "internal server error" message in the browser together with the above error-message and the following additional error-message in the log files:

Fatal | webdav | Icewind\SMB\Exception\NotFoundException: Invalid request for **/Einkauf/Einkauf/** (NotFoundException)
-- | -- | --

As you can see in the error messages, there must be an error with the links. The folder-name "Einkauf" pops-up twice in the path.... I think there is something wrong....

### Server configuration

**Operating system**: Ubuntu 16.04.03

**Web server:** Apache

**Database:** Postgresql

**PHP version:** 7.0.22

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** upgrade

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

**No errors have been found.**

</details>

**List of activated apps:**

Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - admin_notifications: 1.0.1
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_automatedtagging: 1.2.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - groupfolders: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ownpad: 0.5.10
  - passman: 2.1.4
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - user_saml: 1.4.0
  - workflowengine: 1.2.0
Disabled:
  - encryption
  - onlyoffice
  - user_external


**Nextcloud configuration:**

{
    "system": {
        "updatechecker": false,
        "instanceid": "ocl5pu635tr9",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.1",
            "host.nextcloud.domain",
        ],
        "datadirectory": "\/nextcloud_data",
        "dbtype": "pgsql",
        "version": "12.0.3.3",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "maintenance": false,
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_from_address": "cloud",
        "mail_domain": "nextcloud.domain",
        "mail_smtphost": "192.168.0.1",
        "mail_smtpport": "25",
        "skeletondirectory": "",
        "ldapUserCleanupInterval": 51,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "overwriteprotocol": "https",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "production",
        "filelocking.enabled": true,
        "filelocking.ttl": 3600,
        "overwrite.cli.url": "https:\/\/host.nextcloud.domain",
        "activity_expire_days": 365,
        "lost_password_link": "http:\/\/host.nextcloud.domain",
        "log_rotate_size": 10485760
    }
}


**Are you using external storage, if yes which one:** 
**smb**

**Are you using encryption:** 
**no**

**Are you using an external user-backend, if yes which one:** 
**LDAP**

#### LDAP configuration (delete this part if not used)

### Client configuration
**Browser:**
chrome, firefox

**Operating system:**

**Comment by reneglauser** [comment]
It seems that I have diferent other problems related to that issue. E.g. there are no notifications created for activites of the normal-user inside the shared smb-folder. There are always error-messages inside the log as mentioned above.

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.

**Comment by susobaco** [comment]
I have the same error with the latest version of nextcloud 19.0.2
