### ISSUE TITLE
googledrive: gdoc-file is shown as odt-file ending in webinterface

### ISSUE THREAD

**Issue by SGatBugs** [nextcloud/server#7291]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
gdoc-file shall be shown as gdoc-file ending in webinterface

### Actual behaviour
gdoc-file is shown as odt-file ending in webinterface

### Server configuration

**Operating system**: Univention Corporate Server 4.2

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** Univentions App Center

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
> gdoc-file shall be shown as gdoc-file ending in webinterface

Why? AFAIK it is an odt file. 😕

**Comment by SGatBugs** [comment]
Where do you have this information from?

Google speaks of converting odt files to Google Docs (see https://support.google.com/docs/answer/6055139?hl=en):
"File types you can convert to Docs, Sheets, or Slides
These are the file types that can be converted to Google Docs, Sheets, and Slides:
    Documents: .doc (if newer than Microsoft® Office 95), .docx, .docm .dot, .dotx, .dotm, .html, plain text (.txt), .rtf, .**odt**"
 
BTW. *.gdoc is only a Metafile:
http://www.file-extension.org/extensions/gdoc

Google Drive is showing a *.gdoc and Google's sync client is downloading a *.gdoc, so I expect NextCloud Server and Client  to do the same. BTW. NextCloud Client is not downloading *.gdoc files. And renaming a gdoc file in the server's web interface changes the shown file ending from *.odt to *.odt.odt and the renamed document cannot be opened in by Google Docs.

**Comment by y0va** [comment]
> And renaming a gdoc file in the server's web interface changes the shown file ending from *.odt to *.odt.odt and the renamed document cannot be opened in by Google Docs.

Same here on Nextcloud Server 12.0.5
Client 2.3.3
