### ISSUE TITLE
Support syncing macOS Finder file tags

### ISSUE THREAD

**Issue by alexhaas** [nextcloud/server#7294]
As far as I can tell, Nextcloud does not support syncing tags that are added to files in Finder on macOS (https://support.apple.com/en-us/HT202754). Since Dropbox supports syncing these tags, I think it would be extremely beneficial to add this to the Nextcloud feature set. 

### Steps to reproduce
1. Install Nextcloud on more than one Mac.
2. Add a tag to a synced file. 
3. Tag never syncs to other computers.

### Expected behaviour
The tags should be synced (like Dropbox).

### Actual behaviour
Nothing happens.

### Server configuration

**Operating system**: macOS 10.13.1

**Web server:** nginx

**Database:** SQLite

**PHP version:** 7.1.7

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Docker hub

**Comment by MorrisJobke** [comment]
Please report this in the client repo: https://github.com/nextcloud/client/issues
