### ISSUE TITLE
Case-sensitive LDAP

### ISSUE THREAD

**Issue by Peter2121** [nextcloud/server#7299]
There is a function `sanitizeDN($dn)` in Helper.php of apps/user_ldap/lib. This function processes DNs got from LDAP and makes them low-case:
`$dn = mb_strtolower($dn, 'UTF-8');`
This transformation should be optional, as OpenLDAP is often case-sensitive (OU in particular). A checkbox in 'Advanced' options of LDAP would be nice.

**Comment by LukasReschke** [comment]
cc @nextcloud/ldap

**Comment by blizzz** [comment]
@Peter2121 OU is case insensitive as defined in the LDAP core schema. What LDAP server are we talking about? 

In general sanity is necessary, because in some places different formats are returned even from the same server. I am not eager to soften it up again just because.

**Comment by Peter2121** [comment]
I have the case on OpenLDAP installed on Debian 8.
I don't say that it is not necessary in general, you should just give a possibility to disable it using Web interface for those who know what he is doing. For the moment I've just commented the line out and it works fine. Otherwise it does not work. ldap_search does not work neither with OU lower-case.

**Comment by Peter2121** [comment]
In general, you never know how an LDAP server is configured. It CAN be out of any standard. I think that NextCloud should give a possibility to an 'advanced' user to adapt NextCloud to his LDAP configuration.

**Comment by blizzz** [comment]
> It CAN be out of any standard.

Sure… in OpenLDAP's case here it was specifically changed to react like this. Actually I didn't know that OpenLDAP would let you do that. The only argument pro is, that it is not actually specified to be case insensitive, while it is common practice. Overriding standardized attributes however is nothing that i would consider to either expect nor respect.

Honestly, I don't really want to get down that way and re-open a can of worms and also support and maintain it.

**Comment by Peter2121** [comment]
Honestly, I don't understand what issue could be potentially caused by conditional removing the lower-case transform. It touch the data we get FROM user's LDAP. I just propose to keep it intact, nothing more. And yes, there is no standard that defines case-(in)sensitivity of LDAP data. So if NextCloud support the both cases - it cannot be worse than today ;)

> Overriding standardized attributes

As you said, there is NO standard here.

**Comment by blizzz** [comment]
> Honestly, I don't understand what issue could be potentially caused by conditional removing the lower-case transform. It touch the data we get FROM user's LDAP. I just propose to keep it intact, nothing more.

Yes, it's probably safe. We had the issues that the same server sometimes composed with and without whitespaces around commas, for instance. As soon as the next LDAP implementation, lower or upper cases it in some scenarios for the fun of it, you're back in wonderland. 

>>    Overriding standardized attributes

> As you said, there is NO standard here.

OU is specified in RFC 4519, see: https://tools.ietf.org/html/rfc4519#section-2.20 It inherits from "name": https://tools.ietf.org/html/rfc4519#section-2.18 which is case insensitive.

**Comment by Peter2121** [comment]
OK, it seems that it should be case-insensitive. 
I'll digg a little to understand why the OUs are case-sensitive in my case.

**Comment by blizzz** [comment]
Let me close it for now, can reopen if necessary
