### ISSUE TITLE
Log access to preview images

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#73]

**Comment by blizzz** [comment]
More an enhancement than a bug, no?

**Comment by LukasReschke** [comment]
Fair enough.

**Comment by rullzer** [comment]
Assigning to myself so i remember to look at it when touching previews anyways

**Comment by mammuth** [comment]
According to the PR this should be in 11.0.2, right?

I'm currently running 11.0.2 but the admin audit app does not log anything, when I click on an image file which opens in the gallery preview. Other file accesses (like pdf files) are logged correctly.
