### ISSUE TITLE
Update nextcoud guzzle 3rdparty library to version 6

### ISSUE THREAD

**Issue by marc-henri** [nextcloud/server#7302]
Hello,
### Expected behaviour
GuzzleHttp version 6

### Actual behaviour
We’ve create a nextcloud apps for quering zendesk API.
We have tried to use Curl with integrated GuzzleHttp library, but zendesk API need a higher version than the one embedded in Nextcloud 12.
So the Zendesk API (https://github.com/zendesk/zendesk_api_client_php) is requiring a more recent GuzzleHttp library.
Is there still no way to use a different version of GuzzleHttp in our apps ?
When do you think to upgrade this library in nextcloud core ?

### Server configuration

**Operating system**: GNU Linux Debian 9.2
**Web server:** Apache 2.4.10
**Database:** MariaDB 10.0.32
**Nextcloud version:** 12.0.0

Best regards

**Comment by MorrisJobke** [comment]
> When do you think to upgrade this library in nextcloud core ?

Once we drop support for PHP 5.6 😢 Because Guzzle 6 only supports PHP 7+

**Comment by MorrisJobke** [comment]
> Once we drop support for PHP 5.6 😢 Because Guzzle 6 only supports PHP 7+

It seems that I was wrong: https://github.com/nextcloud/3rdparty/issues/49

**Comment by MorrisJobke** [comment]
Done for 14: #8259

**Comment by marc-henri** [comment]
It's very strange.
There's some time that the master branch of the git repository integrates Guzzle in version 6.3.0, but I do not see anything coming about the different stable publications. Yet the commit #8259 (https://github.com/nextcloud/server/pull/8259) indicates that it is operational.
What should be done to incorporate this change into the next release?
