### ISSUE TITLE
Documentation on regenerating `secret` in config.php

### ISSUE THREAD

**Issue by artiommocrenco** [nextcloud/server#7311]
### Steps to reproduce
1. Make your secret public
2. Have fun regenerating it

### Expected behaviour
Easy `occ` command to regenerate secret

### Actual behaviour
Still have no solution

### Server configuration

**Nextcloud version:** 12

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

So the question is... how to regenerate nextcloud secret **and regenerate all associated tokens, hashes, etc.**?

Encryption is turned off.

Also asked on IRC, no solution.

Thanks in advance.

**Comment by LukasReschke** [comment]
I'm afraid, changing the secret is at the moment not supported. Note that a leaked secret alone won't allow an attacker to take over your instance.

One possibility would be to completely install a new instance and manually migrate the data. For our Global Scale component we're working on user migrations, but we're not there yet.

**Comment by artiommocrenco** [comment]
thanks, @LukasReschke 

Couldn't this be a feature/documentation request then?
