### ISSUE TITLE
No folders moved in the cloud

### ISSUE THREAD

**Issue by Seba5120** [nextcloud/server#7320]
**## Hello**

**### Expected behaviour
Tell us what should happen:
Cloud directories should be available.**

**### Actual behaviour
Tell us what happens instead:**

I installed the nextcloud on Raspberry PI3.
Everything runs fine, adds files via www and from android application.
Unfortunately there are no files that have been copied locally by file explorer.
Permissions are assigned the same as all directories.

### Server configuration
**Operating system**:
Raspbian GNU/Linux 8 
**Web server:**
Apache2
**Database:**
mysql 5.5.57
**PHP version:**
7,0,19
**Nextcloud version:** (see Nextcloud admin page)
11.0.2

**Please help, I can not handle it.**

**Comment by MorrisJobke** [comment]
Hi @Seba5120 this is a bug tracker. Could I ask you to seek for help in our forums: https://help.nextcloud.com

Thanks
