### ISSUE TITLE
Administrators should be able to edit the file sync blacklist in the web UI, blacklist should be annotated

### ISSUE THREAD

**Issue by despens** [nextcloud/server#7335]
When files do not get synced because they match a blacklist entry, and a system administrator knows that for example `.htaccess` files pose no danger on their current install (nginx, object storage used instead of file system, etc), there is no clear way to change the blacklist.

Also, it is unclear why some of the rules exist, so it is difficult to make a decision on their usefulness. The blacklisting rules would benefit from an annotation field, i.e.

- `.htaccess` — Apache server configuration files, might pose a danger to nextcloud instances running on an Apache web server. Click here to learn if you're running Apache. 
- `Thumbs.db` — Microsoft Windows specific thumbnail cache; is rebuilt automatically when users browse a directory with Explorer, no need to sync.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.

**Comment by szaimen** [comment]
See 
![image](https://user-images.githubusercontent.com/42591237/119789328-416d6f80-bed3-11eb-94c9-b00288472df3.png)
