### ISSUE TITLE
Integration tests fail sometimes

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#734]
https://drone.weasel.rocks/nextcloud/server/823

> `Merging shares for recipient when shared from outside with user then group and recipient renames in between`
> build/integration/features/sharing-v1.feature:907

That test seems to be not reliable? can you have a look @rullzer

**Comment by rullzer** [comment]
yeah I noticed this as well. But actually have no idea why it sometimes fails. it seems to be something with the login stuff... but I'll try to figure it out.

**Comment by rullzer** [comment]
Fixed by https://github.com/nextcloud/server/pull/1880
