### ISSUE TITLE
Show circle name in details of a shared file (group user)

### ISSUE THREAD

**Issue by fgsl** [nextcloud/server#7340]
### Steps to reproduce
1. Install app [circles ](https://apps.nextcloud.com/apps/circles)
2. Log in as admin user
3. Create a private circle 
4. Add users to that circle
5. Log out
6. Log in as one of created circle users
7. Upload a file
8. Share file to created circle
9. Log out
10. Log in as another of created circle users
11. Open details of shared file
12. Click on tab Sharing

### Expected behaviour
When a file is shared for a circle (created by circles app), details of file must show name of circle, except for circles of type 'Personal'.

### Actual behaviour
When a file is shared for a circle, none of circle users see this information in details of file.

**Nextcloud version:** 13.0.0 Beta 1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install 

**Where did you install Nextcloud from:** Github 

Related to issue #6959

**Comment by MorrisJobke** [comment]
cc @daita server or circle issue?

**Comment by ChristophWurst** [comment]
@daita :ping_pong: please update us on the status. Should this be reported at the circles repo?

**Comment by daita** [comment]
@ChristophWurst thanks for the ping !

**Comment by skjnldsv** [comment]
This is your friendly yearly ping! :bellhop_bell: 
What is the status @daita approve? Deny? Move to the circle repo?

**Comment by ChristophWurst** [comment]
2019-09 :ping_pong:

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
