### ISSUE TITLE
Tooltips in personal settings don't get translations

### ISSUE THREAD

**Issue by mjanssens** [nextcloud/server#7345]
### Steps to reproduce
1. Go to Personal settings
2. Click on icon next of "Full Name"
3. Tooltip is shown with 3 options.
4. options are in english, not local language, although the rest of the page is translated well
5. happens with all icons with these 3 options.

### Expected behaviour
Translated text should be shown in tooltip

### Actual behaviour
Tooltip language stays English

I think something in settings/js/federationscopemenu.js doesn't work right for the translations to apply.
I checked settings/l10n/nl.js and the translations are there. (dutch is my configured language)

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Comment by MorrisJobke** [comment]
Fix is in #7346

**Comment by mjanssens** [comment]
Thank you!
