### ISSUE TITLE
Bad behavior with a collabora plugin

### ISSUE THREAD

**Issue by zden2k** [nextcloud/server#7358]
Nextcloud has bad behavior with a Collabora plugin, see more on incuded gif

### Steps to reproduce
1. import document odt for example
2. click on checkbox to download
3. enter into collabora
4. exit
5.  click on checkbox to download again, menu for download is outside of Nextcloud screen

![out-6_1](https://user-images.githubusercontent.com/25531350/33439999-27daf888-d5ef-11e7-9d2d-86d8993c687f.gif)

### Server configuration

**Operating system**: debian9

**Web server:** nginx  1.10.3-1

**Database:** mariadb 10.1.26-0+deb9u1

**PHP version:** 7.0.19-1

**Nextcloud version:** 12.03

### Browsers

**Browsers:** Chromium - Version 53.0.2785.143 Built on 8.6, running on Debian 8.6 (64-bit) and also Firefox(iceweasel) 45.6.0esr-1~deb8u

**Comment by paescuj** [comment]
Already experienced the same thing, but couln't reproduce it.

**Comment by LukasReschke** [comment]
Please reopen at https://github.com/nextcloud/richdocuments. Thanks :)

**Comment by zden2k** [comment]
ok, https://github.com/nextcloud/richdocuments/issues/142
