### ISSUE TITLE
WebDAV PROPFIND results in 503 from browser

### ISSUE THREAD

**Issue by perry-mitchell** [nextcloud/server#7365]
### Steps to reproduce
1. Open demo account on Nextcloud service
2. Make XHR request (PROPFIND) to Nextcloud WebDAV, to either of the following URLs:
  - `https://demo.nextcloud.com/aipeev4r/remote.php/dav/files/admin/`
  - `https://demo.nextcloud.com/aipeev4r/remote.php/webdav/`

### Expected behaviour
A successful PROPFIND request+response (contents of root returned)

### Actual behaviour
I receive a 503 service unavailable:

![image](https://user-images.githubusercontent.com/3869469/33516648-ffd0b9a4-d77e-11e7-8ecd-83c39abd433e.png)

Using the following request headers:

```
PROPFIND /aipeev4r/remote.php/dav/files/admin/ HTTP/1.1
Host: demo.nextcloud.com
Connection: keep-alive
Content-Length: 0
accept: */*
Origin: chrome-extension://bhjndcjjaoehhegenhjgihoamlngkbbd
authorization: Basic YWRtaW46YWRtaW4=
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
depth: 1
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.8
Cookie: oc_sessionPassphrase=OdKOymloOyyBsRarho80%2FkJiEEqgUoJgGaBvt5nTCtZsWgMmIFHDr3kI%2BuRYFhJyGn9c8QIaJk5Q9Y0P2sM3dBWCwO6XoABxA4RaqQkTpUaxzeExjNGAtYZcA9bQZJNt; oc36ouklzxpc=daiiuu0vb21sm1aaic5bjifq22; PHPSESSID=fdsbguccp5gdjpnukdq8fcujsp
```

### Server configuration

**Operating system**: _As on demo.nextcloud.com._

**Web server:** _As on demo.nextcloud.com._

**Database:** _As on demo.nextcloud.com._

**PHP version:** _As on demo.nextcloud.com._

**Nextcloud version:** 12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** No

**Where did you install Nextcloud from:** _Not applicable_

_(Rest of the items omitted due to them being generically configured by the Nextcloud demo service)_.

An exported HAR of the request can be found [here](https://pastebin.com/q0vk6ivc).

We've been trying to integrate Nextcloud + [Buttercup](https://buttercup.pw) for many months now, to no avail. It works fine on the NodeJS (server) side, through WebDAV, but not when running in the browser. Previously we've seen CORS problems, and now we're seeing these 503s. We've tried the original `example.com/remote.php/webdav` URLs and the newer `example.com/remote.php/dav/files/admin/` URLs (found in 12.0 docs). Both produce the same result.

I would love to work through this with someone, but I'm not sure how easy that might be. It's very frustrating and we'd love to keep Nextcloud integration, but if it works everywhere except for in the browser, we might consider dropping support in the near future. Any help would really, be greatly appreciated 😊.

**Comment by perry-mitchell** [comment]
Exported as a cURL request for completeness:

```shell
curl 'https://demo.nextcloud.com/aipeev4r/remote.php/dav/files/admin/' -X PROPFIND -H 'Cookie: oc_sessionPassphrase=OdKOymloOyyBsRarho80%2FkJiEEqgUoJgGaBvt5nTCtZsWgMmIFHDr3kI%2BuRYFhJyGn9c8QIaJk5Q9Y0P2sM3dBWCwO6XoABxA4RaqQkTpUaxzeExjNGAtYZcA9bQZJNt; oc36ouklzxpc=daiiuu0vb21sm1aaic5bjifq22; PHPSESSID=fdsbguccp5gdjpnukdq8fcujsp' -H 'Origin: chrome-extension://bhjndcjjaoehhegenhjgihoamlngkbbd' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.8' -H 'authorization: Basic YWRtaW46YWRtaW4=' -H 'accept: */*' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36' -H 'Connection: keep-alive' -H 'Content-Length: 0' -H 'depth: 1' --compressed
```

**Comment by perry-mitchell** [comment]
Turns out stupidity was at fault this time! I was trying to use `node-fetch` (npm library) to make the request, which has known issues with Nextcloud.

**Comment by JamesCoyne** [comment]
I'm having the same issue. I'd love to see a solution if there is one.
