### ISSUE TITLE
No icons in app categories "security" and "games" [NC13beta1]

### ISSUE THREAD

**Issue by tflidd** [nextcloud/server#7366]
### Steps to reproduce
1. Login
2. Go to apps page

### Expected behaviour
See all categories with icons.

### Actual behaviour
There is no icon for security and games. This hole doesn't look good. For security, there is already an icon in the admin-section. Perhaps you need to design a new one for games, or don't show it since there are no apps in this category yet.

![screenshot from 2017-12-02 17-17-00](https://user-images.githubusercontent.com/8111200/33517466-0405d15c-d785-11e7-9f4d-5ed15f804e7c.png)

## Server configuration detail

**Operating system:** Debian 8

**Webserver:** Apache/2.4.10 (Debian) (apache2handler)

**Database:** mysql 10.0.32

**PHP version:** 7.0.26-1~dotdeb+8.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, igbinary, mysqlnd, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, imap, intl, json, exif, mcrypt, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.0 Beta 1 - 13.0.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_notifications: 1.0.1
 - apporder: 0.4.0
 - audioplayer: 2.2.1
 - bookmarks: 0.10.1
 - calendar: 1.5.6
 - circles: 0.13.6
 - comments: 1.3.0
 - contacts: 2.0.1
 - dav: 1.4.5
 - deck: 0.2.7
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_accesscontrol: 1.3.0
 - files_automatedtagging: 1.3.0
 - files_external: 1.4.1
 - files_markdown: 2.0.1
 - files_pdfviewer: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - githubmergetracker: 0.0.18
 - groupfolders: 1.1.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.7.5
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.1
 - notifications: 2.1.0
 - oauth2: 1.1.0
 - passman: 2.1.4
 - password_policy: 1.3.0
 - previewgenerator: 1.0.7
 - provisioning_api: 1.3.0
 - ransomware_protection: 1.1.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - systemtags: 1.3.0
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - twofactor_u2f: 1.4.0
 - updatenotification: 1.3.0
 - user_external: 0.4
 - user_usage_report: 1.0.1
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - encryption
 - survey_client
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "my.cloud.local"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/my.cloud.local\/nextcloud",
    "htaccess.RewriteBase": "\/nextcloud",
    "dbtype": "mysql",
    "version": "13.0.0.6",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "user_backends": [
        {
            "class": "OC_User_IMAP",
            "arguments": [
                "{my.cloud.local:993\/imap\/ssl}"
            ]
        }
    ],
    "updater.release.channel": "beta",
    "loglevel": 0,
    "log_rotate_size": 10485760,
    "maintenance": false,
    "allow_user_to_change_display_name": true,
    "theme": "",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0
    }
}
```
</details>

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by MariusBluem** [comment]
Done with https://github.com/nextcloud/server/pull/7189 :)
