### ISSUE TITLE
2FA auth code settings on "additional settings" instead of "security" [NC13beta1]

### ISSUE THREAD

**Issue by tflidd** [nextcloud/server#7367]
### Steps to reproduce
1. Login, go to personal settings page
2. search where to set 2FA

### Expected behaviour
I would expect the settings in the "security" section. And you can already set backup codes for 2FA authentication there!

### Actual behaviour
You have to go to "additional settings".

Either put all 2FA stuff into the security section (where it belongs). Or if you prefer to put it to "additional settings", please group the second factor backup codes with the setup of auth codes.

In my case: U2F is active (TOTP is not available yet on NC13).

@ChristophWurst

**Comment by ChristophWurst** [comment]
Fixed by https://github.com/nextcloud/twofactor_u2f/pull/72 and https://github.com/nextcloud/twofactor_totp/pull/197. Not all has been released yet, but I'll do that soon.

Thanks for reporting.
