### ISSUE TITLE
PHP 7.0+ for Nextcloud 14

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#7368]
I want to bring up the topic of raising the PHP version to 7.0. I collected a list of released PHP packages for the main distributions:

* [Ubuntu 16.04 (xenial)](https://packages.ubuntu.com/xenial/php): **7.0**
* [Debian 9 (stretch)](https://packages.debian.org/stretch/php): **7.0**
* [SUSE Linux Enterprise Server 12 (Web and Scripting Module)](https://scc.suse.com/docs/lifecycle/sle/12/modules): **7.0**
* [CentOS/Red Hat 7](http://mirror.centos.org/centos/7/os/x86_64/Packages): **5.4**
* [CentOS/Red Hat 7 with RHSCL](https://developers.redhat.com/products/softwarecollections/updates/): **7.1**

As you need to use RHSCL anyways on Red Hat to run Nextcloud 13 and before, it only make sense to also raise the required version for Nextcloud. The main reason behind this is proper type hinting of scalar types as well as strict typing. Just today there was another possible bug that would have been found by our CI if strict typing would be set: https://github.com/nextcloud/server/pull/7351#discussion_r154321149

Compare https://3v4l.org/dmBJK (without strict typing) to https://3v4l.org/msAEZ (with strict typing).

Opinions on this? I guess it is a good way to move forward with our quality goals.

cc @rullzer @LukasReschke @schiessle @karlitschek @blizzz @skjnldsv @juliushaertl @icewind1991 @ChristophWurst @daita @danxuliu

**Comment by splitt3r** [comment]
Even 7.0 has only 11 month left -> http://php.net/supported-versions.php

**Comment by karlitschek** [comment]
@splitt3r We have to check the supported situation in distribution. Which is usually different then from upstream.

**Comment by karlitschek** [comment]
O.K. Let's move to 7.0+ for 14

**Comment by LukasReschke** [comment]
Oye! _NOW_ the fun stuff starts? ;-)

**Comment by MorrisJobke** [comment]
> Even 7.0 has only 11 month left

Our goal is to have a supported version on which Nextcloud runs on all major distributions. Because this is the place where Nextcloud runs and it would not make it easier to get Nextcloud running if you need to find 3rdparty packages or compile PHP yourself. (Not even thinking about security and upgrade problems afterwards with those setups).

**Comment by rullzer** [comment]
Yes please. I think this can really harden our software!

I'm fine with 7.0 for now. We can review for 15 what the state is then.

**Comment by tflidd** [comment]
In NC13, could we put in a notification/warning on the admin page for users with PHP<7.0 that this is the last version supporting php 5.6 and that PHP 7.0+ is required for the next major release? This way they are noticed early enough to plan an upgrade.

**Comment by MorrisJobke** [comment]
> In NC13, could we put in a notification/warning on the admin page for users with PHP<7.0 that this is the last version supporting php 5.6 and that PHP 7.0+ is required for the next major release? This way they are noticed early enough to plan an upgrade.

Could you make a ticket for this. You could also assign me there. Thanks
