### ISSUE TITLE
Shadow on "Auth required"-promt

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#7372]
<img width="421" alt="bildschirmfoto 2017-12-03 um 16 23 32" src="https://user-images.githubusercontent.com/19711361/33526787-59ae5978-d846-11e7-8c74-3e6f79aad8ff.png">

**version:** 13.0 beta1
**browser:** safari 11.0.1

**Comment by MorrisJobke** [comment]
Fixed by #7177
