### ISSUE TITLE
Using macOS Keychain as password manager uses password as username

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#7373]
**macOS-version:** 10.13.1
**Safari-version:** 11.0.1
**Nextcloud version:** 13.0 beta1

![dez -03-2017 16-31-33](https://user-images.githubusercontent.com/19711361/33526884-a7cf099e-d847-11e7-9306-6644daf6d4ee.gif)

**Comment by MorrisJobke** [comment]
Works for me - it looks like this was saved in a different place wrongly. Maybe in the admin settings? At least if I save it from the login panel directly it works without problems.

**Comment by MorrisJobke** [comment]
Also similar to #6821 but in this case I think this is caused by an input field either in the user management or in the personal settings.

**Comment by MorrisJobke** [comment]
@MariusBluem Could you still reproduce this?

**Comment by rullzer** [comment]
Since no dev can properly reproduce to debug... lets move out of 13

**Comment by ChristophWurst** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen.
