### ISSUE TITLE
Position of Gallery-button and inconsistent behavior on hover

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#7374]
**Safari-version:** 11.0.1
**Nextcloud-version:** 13.0 beta1

![dez -03-2017 16-39-12](https://user-images.githubusercontent.com/19711361/33526949-9c0f2278-d848-11e7-9931-89711807cdfe.gif)

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers @oparoz

**Comment by pixelipo** [comment]
It should be done with margin-left:auto, but the problem is that it's always renderer `before` the Add button.
I think this requires rethinking the JS method responsible for painting the gallery-button

**Comment by skjnldsv** [comment]
I'll take a look if you want @pixelipo

**Comment by skjnldsv** [comment]
Please review :) https://github.com/nextcloud/gallery/pull/336 & #7478
