### ISSUE TITLE
[personal settings] Move "Sync-clients" section to "Security"

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#7375]
The personal-settings menu "Sync-clients" has too less information and functions to require having an own menu-point. We should add it to "Security" and rename it to "Security & Clients" ;) 

"Security" is currently more or less "Sessions & clients" anyway so it would match perfect.

<img width="899" alt="bildschirmfoto 2017-12-03 um 16 42 19" src="https://user-images.githubusercontent.com/19711361/33526968-f29d5074-d848-11e7-9da2-a88a6885d7d4.png">

_The button for showing the firstrunwizard again can be moved to "Additional settings"_

**Nextcloud-version:** 13.0 beta1

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers @jospoortvliet  @karlitschek Opinions on this?

**Comment by karlitschek** [comment]
Not sure. I see the point that the page looks a bit empty. But Clients and Security don't really fit together. Is it possible to do it the other way around and add more useful information to the clients page? Explain what they do? How to configure? Calendar/Contacts? ...

**Comment by jancborchardt** [comment]
Agree with @karlitschek here. Instructions on how to set up Calendar and Contacts sync could be described directly there.

This could also be a great page to showcase some curated 3rd-party apps for Android, iOS, and desktop. Like for News, Notes, Bookmarks, SMS, Tasks etc.

**Comment by MorrisJobke** [comment]
They are now in the devices section -> closing.
