### ISSUE TITLE
Sharing settings are wrong positioned on big screens

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#7376]
<img width="717" alt="bildschirmfoto 2017-12-03 um 17 01 01" src="https://user-images.githubusercontent.com/19711361/33527134-ba5bd426-d84b-11e7-8313-6ea8b5166567.png">

**Nextcloud-version:** 13.0 beta1
**Safari-version:** 11.0.1

**Comment by MorrisJobke** [comment]
I guess this is because the layout is still with percentages instead of proper flex box or similar. So this is only a problem on wide screens. I guess we are only able to fix this by restructuring the whole sidebar. I will move this to 14 then, because it works and just needs to be polished a lot ;)

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by skjnldsv** [comment]
It will be fixed with the sidebar standard for 14!

**Comment by jancborchardt** [comment]
Yeah, we need to define a max width for the right sidebar much like for the left app-navigation (which is 250px). I’d go for the same value, what do you think @skjnldsv?

**Comment by skjnldsv** [comment]
@jancborchardt should be good yeah! There is a lot to be discussed about this though :p

**Comment by MorrisJobke** [comment]
@skjnldsv Was this somehow fixed recently during the whole restructuring?

**Comment by skjnldsv** [comment]
@MorrisJobke sidebar standard has been postponed to 15

**Comment by jancborchardt** [comment]
This has been fixed by @juliushaertl (at least @skjnldsv and I think so :D)

**Comment by juliushaertl** [comment]
Cannot remember, but it works fine on master. :grin:
