### ISSUE TITLE
Add possibility to un-favorite file by clicking on the star

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#7377]
<img width="224" alt="bildschirmfoto 2017-12-03 um 17 04 05" src="https://user-images.githubusercontent.com/19711361/33527154-0b779c64-d84c-11e7-9185-06e18607a956.png">

**Nextcloud-version:* 13.0

**Comment by MorrisJobke** [comment]
I would not do that ...


cc @nextcloud/designers

**Comment by jancborchardt** [comment]
Yes, I wouldn't do it either because:

- It will need to have 44*44 area of clickability which extends well beyond the icon which will lead to misclicks, especially on mobile.
- A toggle-action like this should be toggleable then, but then we need to introduce a grey star again - nope.
