### ISSUE TITLE
[personal settings] Move "Change password" to "Security"-settings 

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#7378]
I think a password is not related to "Personal information" but more to "Security". We could add it as a section there. It should be clear, that this is a special kind of data - not like your twitter profile name :D

<img width="1109" alt="bildschirmfoto 2017-12-03 um 17 07 26" src="https://user-images.githubusercontent.com/19711361/33527191-9863d868-d84c-11e7-8b55-85f487f65e00.png">

**Comment by MorrisJobke** [comment]
@juliushaertl @skjnldsv Does one of you want to look into this?

**Comment by juliushaertl** [comment]
Yes, makes sense to me. I will have a look into that.

**Comment by MorrisJobke** [comment]
@nextcloud/designers Does this still make sense? I think this is a nice and small polishing part that could still be done for 14.
