### ISSUE TITLE
Decrypt object on swift > 30k

### ISSUE THREAD

**Issue by vilisseranen** [nextcloud/server#7382]
Hi,

I am having issues with swift as external storage when encryption is enabled. I am not able to decode an object larger than 30k.

### Steps to reproduce
1. Upload an object to swift (50k was enough in my case)
2. Download the object
3. The download fails (in the NextCloud UI, we can see a MissingSignature error being thrown)

Note: the thumbnails are obviously also not generated for these files.

### Expected behaviour
Download of the file should be correct and thumbnails should be properly generated.

### Actual behaviour
Object is download up to about 30k and thumbnails are not generated.

### Server configuration

**Operating system**: Ubuntu 17.10

**Web server:** apache 2.4.27-2ubuntu3

**Database:** mysqld 5.7.20-0ubuntu0.17.10.1

**PHP version:** 7 (1:7.1+54ubuntu1)

**Nextcloud version:** 12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.6
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - deck: 0.2.8
  - drawio: 0.8.8
  - encryption: 1.6.0
  - federatedfilesharing: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.7.5
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - passman: 2.1.4
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.2
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - unsplash: 1.0.5
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - federation
  - polls
  - richdocuments
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oc04w2bkpcaz",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/media\/raid-volume01\/nextcloud",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "12.0.3.3",
        "dbname": "nextcloud",
        "dbhost": "localhost:3306",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 1,
        "maintenance": false
    }
}

```
</details>

**Are you using external storage, if yes which one:** openstack swift

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

The main error I got was:

"OCP\Encryption\Exceptions\GenericEncryptionException: Missing Signature"

After some digging I found out that the problem involved an issue in how the stream is retrieve from swift. Because the objects are encrypted using 8k blocks, you need to retrieve the same size of blocks if you want to be able to decode the object properly. When using swift non-encrypted, the size of the blocks does not matter and the blocks are just concatenated. When using encryption, if the size of the block that is received does not match 8k, the system is not able to find the signature and the error "OCP\Encryption\Exceptions\GenericEncryptionException: Missing Signature" is thrown.

This is an example of the size of blocks I am getting when trying to download a 50k image, encoded:

```
[Sun Dec 03 17:29:38.303797 2017] [php7:notice] [pid 5486] [client 192.168.1.1:50525] lena - data_len: 8192
[Sun Dec 03 17:29:38.304042 2017] [php7:notice] [pid 5486] [client 192.168.1.1:50525] lena - data_len: 8192
[Sun Dec 03 17:29:38.305263 2017] [php7:notice] [pid 5486] [client 192.168.1.1:50525] lena - data_len: 8192
[Sun Dec 03 17:29:38.305478 2017] [php7:notice] [pid 5486] [client 192.168.1.1:50525] lena - data_len: 8192
[Sun Dec 03 17:29:38.313352 2017] [php7:notice] [pid 5486] [client 192.168.1.1:50525] lena - data_len: 8192
[Sun Dec 03 17:29:38.313528 2017] [php7:notice] [pid 5486] [client 192.168.1.1:50525] lena - data_len: 8192
[Sun Dec 03 17:29:38.321249 2017] [php7:notice] [pid 5486] [client 192.168.1.1:50525] lena - data_len: 8192
[Sun Dec 03 17:29:38.329378 2017] [php7:notice] [pid 5486] [client 192.168.1.1:50525] lena - data_len: 8192
[Sun Dec 03 17:29:38.329552 2017] [php7:notice] [pid 5486] [client 192.168.1.1:50525] lena - data_len: 8192
[Sun Dec 03 17:29:38.337263 2017] [php7:notice] [pid 5486] [client 192.168.1.1:50525] lena - data_len: 7602
```

The result is the image attached
![lenna 25](https://user-images.githubusercontent.com/4092920/33530589-aa486a50-d84f-11e7-95dc-d238e2497a45.jpg)

I fixed this issue in this commit: https://github.com/vilisseranen/server/commit/2c820d1c52a3ddfce167ef9f6246bf10cfe5e120

One issue, I could not use stream_eof and had to write the ugly condition line 91. Also, I took the code for this in the RetryWrapper code.

If somebody could help me write a clean fix for this that would be really appriciated.

Thanks,

**Comment by rullzer** [comment]
@icewind1991 ^^

**Comment by icewind1991** [comment]
@vilisseranen can you test https://github.com/nextcloud/server/pull/7387?

**Comment by vilisseranen** [comment]
Will do, thanks.

**Comment by vilisseranen** [comment]
@icewind1991 #7387 seems to work fine thanks. I am closing the issue.

**Comment by rullzer** [comment]
Lets keep it open for other to find and close it once #7387 is merged :wink:
