### ISSUE TITLE
Integrity constraint violation: 19 NOT NULL constraint failed: oc_filecache.storage_mtime

### ISSUE THREAD

**Issue by MarioKlebsch** [nextcloud/server#7389]
### Steps to reproduce
Upgraded Nextcloud via web interface.

### Expected behaviour
After upgrade has been installed, the upgrade process should be performed on the web interface

### Actual behaviour
Internal Server Error is shown on the login web page

### Server configuration

**Operating system**:
Linux 4.4.39
**Web server:**
Apache/2.4.27 (Unix)
**Database:**
sqlite3
**PHP version:**
7.1
**Nextcloud version:** (see Nextcloud admin page)
12.0.4.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
12.0.3
**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - calendar: 1.5.6
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - mail: 0.7.5
  - nextcloud_announcements: 1.1
  - notes: 2.3.2
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - bruteforcesettings
  - encryption
  - files_external
  - firstrunwizard
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "ocgwps286fzc",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx",
            "xxx"
        ],
        "datadirectory": "\/var\/www\/localhost\/htdocs\/xxx\/data",
        "overwrite.cli.url": "https:\/\/xxx\/xxx",
        "has_internet_connection": true,
        "dbtype": "sqlite3",
        "version": "12.0.4.3",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "xxx",
        "mail_domain": "xxx.xxx",
        "default_language": "de",
        "appstoreenabled": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 1,
        "appstore.experimental.enabled": true,
        "updater.release.channel": "stable",
        "mail_smtphost": "localhost",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "activity": {
            "installed_version": "2.5.2",
            "types": "filesystem",
            "enabled": "yes"
        },
        "admin_audit": {
            "installed_version": "1.2.0",
            "types": "logging",
            "enabled": "yes"
        },
        "backgroundjob": {
            "lastjob": "27"
        },
        "bruteforcesettings": {
            "installed_version": "1.0.2",
            "enabled": "no",
            "types": ""
        },
        "calendar": {
            "installed_version": "1.5.6",
            "enabled": "yes",
            "types": ""
        },
        "comments": {
            "installed_version": "1.2.0",
            "types": "logging",
            "enabled": "yes"
        },
        "contacts": {
            "installed_version": "2.0.1",
            "enabled": "yes",
            "types": "",
            "ocsid": "168708"
        },
        "core": {
            "installedat": "1455439394.3311",
            "lastupdatedat": "0",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "lastcron": "1512418504",
            "shareapi_allow_public_upload": "no",
            "shareapi_allow_resharing": "no",
            "shareapi_only_share_with_group_members": "yes",
            "outgoing_server2server_share_enabled": "no",
            "incoming_server2server_share_enabled": "no",
            "lastupdateResult": "{\"version\":\"12.0.4.3\",\"versionstring\":\"Nextcloud 12.0.4\",\"url\":\"https:\\\/\\\/download.nextcloud.com\\\/server\\\/releases\\\/nextcloud-12.0.4.zip\",\"web\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/11\\\/admin_manual\\\/maintenance\\\/upgrade.html\",\"autoupdater\":\"1\",\"signature\":\"pdpExf2i5sgwNzkP7fcOKWBcMoZzsSe8PwjZYYi0ZFlUqayQMnlVqmZ0Lc\\\/hBWg\\\/\\nAAuiH+WViv\\\/dHfxECMlcHTVBFABCn8qqHlfllfEoLVGI2V3GoOOYdij72N5pFm3Z\\n8A8ccUEHso3QjdhiwcofSyJ5vxWdJZvruNIdW9M+UfW3Sm98HYoirRUEdvEBKJzZ\\nOOkWI1NexeTzPBErQneNvI1iXl5LSV9Ert4HfIVkMA8Wfpvt8X6tH7G5pGpBrky3\\nnc4UiS2SHl724076KdRNT3amt3XvhkSs6WukH6hAxiWIvygBVRYbAE2tUW+7UPoh\\n1lfbqYRCWrhsrulksMda\\\/A==\"}",
            "backgroundjobs_mode": "cron",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "public_calendar": "calendar\/share.php",
            "public_caldav": "calendar\/share.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "repairlegacystoragesdone": "yes",
            "updater.secret.created": "1512416545",
            "vendor": "nextcloud",
            "moveavatarsdone": "yes",
            "previewsCleanedUp": "1",
            "installed.bundles": "[\"CoreBundle\"]",
            "scss.variables": "82575d5a3dc7a586d901b5eb0aa8da56",
            "umgmt_show_email": "true",
            "umgmt_show_last_login": "true",
            "umgmt_show_backend": "false",
            "umgmt_show_storage_location": "false",
            "oc.integritycheck.checker": "[]"
        },
        "dav": {
            "installed_version": "1.3.0",
            "types": "filesystem",
            "enabled": "yes",
            "buildCalendarSearchIndex": "yes"
        },
        "federatedfilesharing": {
            "installed_version": "1.2.0",
            "types": "",
            "enabled": "yes"
        },
        "federation": {
            "installed_version": "1.2.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "files": {
            "installed_version": "1.7.2",
            "types": "filesystem",
            "enabled": "yes",
            "cronjob_scan_files": "500"
        },
        "files_pdfviewer": {
            "installed_version": "1.1.1",
            "ocsid": "166049",
            "types": "",
            "enabled": "yes"
        },
        "files_sharing": {
            "installed_version": "1.4.0",
            "types": "filesystem",
            "enabled": "yes",
            "outgoing_server2server_share_enabled": "no",
            "incoming_server2server_share_enabled": "no",
            "lookupServerUploadEnabled": "no"
        },
        "files_texteditor": {
            "installed_version": "2.4.1",
            "ocsid": "166051",
            "types": "",
            "enabled": "yes"
        },
        "files_trashbin": {
            "installed_version": "1.2.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_versions": {
            "installed_version": "1.5.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "files_videoplayer": {
            "installed_version": "1.1.0",
            "types": "",
            "enabled": "yes"
        },
        "files_videoviewer": {
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": "",
            "enabled": "no"
        },
        "firstrunwizard": {
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": "",
            "enabled": "no"
        },
        "gallery": {
            "installed_version": "17.0.0",
            "types": "",
            "enabled": "yes"
        },
        "logreader": {
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "types": "",
            "enabled": "yes",
            "levels": "01111"
        },
        "lookup_server_connector": {
            "installed_version": "1.0.0",
            "types": "authentication",
            "enabled": "yes"
        },
        "mail": {
            "installed_version": "0.7.5",
            "enabled": "yes",
            "types": ""
        },
        "nextcloud_announcements": {
            "installed_version": "1.1",
            "types": "logging",
            "enabled": "yes",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100"
        },
        "notes": {
            "installed_version": "2.3.2",
            "enabled": "yes",
            "types": "",
            "ocsid": "174554"
        },
        "notifications": {
            "installed_version": "2.0.0",
            "types": "logging",
            "enabled": "yes"
        },
        "oauth2": {
            "installed_version": "1.0.5",
            "types": "authentication",
            "enabled": "yes"
        },
        "password_policy": {
            "installed_version": "1.2.2",
            "types": "",
            "enabled": "yes"
        },
        "provisioning_api": {
            "installed_version": "1.2.0",
            "types": "prevent_group_restriction",
            "enabled": "yes"
        },
        "serverinfo": {
            "installed_version": "1.2.0",
            "types": "",
            "enabled": "yes"
        },
        "sharebymail": {
            "installed_version": "1.2.0",
            "types": "filesystem",
            "enabled": "yes"
        },
        "survey_client": {
            "installed_version": "1.0.0",
            "types": "",
            "enabled": "yes",
            "encryption": "no",
            "files_sharing": "no",
            "apps": "no",
            "php": "no",
            "server": "no",
            "database": "no",
            "stats": "no"
        },
        "systemtags": {
            "installed_version": "1.2.0",
            "types": "logging",
            "enabled": "yes"
        },
        "templateeditor": {
            "installed_version": "0.2",
            "types": "",
            "enabled": "no"
        },
        "theming": {
            "installed_version": "1.3.0",
            "types": "logging",
            "enabled": "yes",
            "url": "",
            "cachebuster": "14",
            "name": "",
            "slogan": "",
            "backgroundMime": "image\/jpeg",
            "color": "#2B6CB5",
            "logoMime": "image\/png"
        },
        "twofactor_backupcodes": {
            "installed_version": "1.1.1",
            "types": "",
            "enabled": "yes"
        },
        "updatenotification": {
            "installed_version": "1.2.0",
            "types": "",
            "enabled": "yes",
            "core": "12.0.4.3",
            "update_check_errors": "0",
            "mail": "0.7.5",
            "calendar": "1.5.6",
            "contacts": "2.0.1",
            "notes": "2.3.2"
        },
        "updater": {
            "installed_version": "0.6",
            "types": "",
            "enabled": "no"
        },
        "user_external": {
            "installed_version": "0.4",
            "ocsid": "166060",
            "types": "authentication,prelogin",
            "enabled": "no"
        },
        "workflowengine": {
            "installed_version": "1.2.0",
            "types": "filesystem",
            "enabled": "yes"
        }
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

  There are no commands defined in the "ldap" namespace.   
</details>

### Client configuration
**Browser:**
Safari

**Operating system:**
MacOSX

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

#### Exception caught in index.php:
PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_filecache.storage_mtime in 
/localhost/htdocs/xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
 Stack trace: #0 /localhost/htdocs/xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(91): PDOStatement->execute(Array)
 #1 /localhost/htdocs/xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(849): Doctrine\DBAL\Driver\PDOStatement->execute(Array)
 #2 /localhost/htdocs/xxx/lib/private/DB/Connection.php(192): Doctrine\DBAL\Connection->executeQuery('UPDATE "oc_file...', Array, Array, NULL)
 #3 /localhost/htdocs/xxx/lib/private/Files/Cache/Cache.php(320): OC\DB\Connection->executeQuery('UPDATE "oc_file...', Array)
 #4 /localhost/htdocs/xxx/lib/private/Files/Cache/Scanner.php(276): OC\Files\Cache\Cache->update(1571, Array)
 #5 /localhost/htdocs/xxx/lib/private/Files/Cache/Scanner.php(216): OC\Files\Cache\Scanner->addToCache('appdata_ocgwps2...', Array, 1571)
 #6 /localhost/htdocs/xxx/lib/private/Files/Cache/Scanner.php(322): OC\Files\Cache\Scanner->scanFile('appdata_ocgwps2...', 3, 1570, Object(OC\Files\Cache\CacheEntry), false)
 #7 /localhost/htdocs/xxx/lib/private/Files/Cache/Updater.php(124): OC\Files\Cache\Scanner->scan('appdata_ocgwps2...', false, 3, false)
 #8 /localhost/htdocs/xxx/lib/private/Files/View.php(321): OC\Files\Cache\Updater->update('appdata_ocgwps2...', 1512417586)
 #9 /localhost/htdocs/xxx/lib/private/Files/View.php(1171): OC\Files\View->writeUpdate(Object(OCA\Files_Trashbin\Storage), 'appdata_ocgwps2...')
 #10 /localhost/htdocs/xxx/lib/private/Files/View.php(699): OC\Files\View->basicOperation('file_put_conten...', '/appdata_ocgwps...', Array, '(function($) {\n...')
 #11 /localhost/htdocs/xxx/lib/private/Files/Node/File.php(64): OC\Files\View->file_put_contents('/appdata_ocgwps...', '(function($) {\n...')
  #12 /localhost/htdocs/xxx/lib/private/Files/SimpleFS/SimpleFile.php(95): OC\Files\Node\File->putContent('(function($) {\n...') 
  #13 /localhost/htdocs/xxx/lib/private/Template/JSCombiner.php(167): OC\Files\SimpleFS\SimpleFile->putContent('(function($) {\n...') 
  #14 /localhost/htdocs/xxx/lib/private/Template/JSCombiner.php(89): OC\Template\JSCombiner->cache('/localhost/htdo...', 'merged-template...', Object(OC\Files\SimpleFS\SimpleFolder)) 
  #15 /localhost/htdocs/xxx/lib/private/Template/JSResourceLocator.php(112): OC\Template\JSCombiner->process('/localhost/htdo...', 'core/js/merged-...', 'core') 
  #16 /localhost/htdocs/xxx/lib/private/Template/JSResourceLocator.php(68): OC\Template\JSResourceLocator->cacheAndAppendCombineJsonIfExist('/localhost/htdo...', 'core/js/merged-...') 
  #17 /localhost/htdocs/xxx/lib/private/Template/ResourceLocator.php(76): OC\Template\JSResourceLocator->doFind('js/merged-templ...') 
  #18 /localhost/htdocs/xxx/lib/private/TemplateLayout.php(249): OC\Template\ResourceLocator->find(Array) 
  #19 /localhost/htdocs/xxx/lib/private/TemplateLayout.php(132): OC\TemplateLayout::findJavascriptFiles(Array) 
  #20 /localhost/htdocs/xxx/lib/private/legacy/template.php(205): OC\TemplateLayout->__construct('guest', '') 
  #21 /localhost/htdocs/xxx/lib/private/Template/Base.php(132): OC_Template->fetchPage() 
  #22 /localhost/htdocs/xxx/lib/base.php(408): OC\Template\Base->printPage() 
  #23 /localhost/htdocs/xxx/lib/base.php(301): OC::printUpgradePage() 
  #24 /localhost/htdocs/xxx/lib/base.php(962): OC::checkUpgrade() 
  #25 /localhost/htdocs/xxx/index.php(48): OC::handleRequest() 
  #26 {main}
    
Next Doctrine\DBAL\Driver\PDOException: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_filecache.storage_mtime in 
/localhost/htdocs/xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:93
Stack trace: #0 /localhost/htdocs/xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(849): Doctrine\DBAL\Driver\PDOStatement->execute(Array) 
#1 /localhost/htdocs/xxx/lib/private/DB/Connection.php(192): Doctrine\DBAL\Connection->executeQuery('UPDATE "oc_file...', Array, Array, NULL) 
#2 /localhost/htdocs/xxx/lib/private/Files/Cache/Cache.php(320): OC\DB\Connection->executeQuery('UPDATE "oc_file...', Array) 
#3 /localhost/htdocs/xxx/lib/private/Files/Cache/Scanner.php(276): OC\Files\Cache\Cache->update(1571, Array) 
#4 /localhost/htdocs/xxx/lib/private/Files/Cache/Scanner.php(216): OC\Files\Cache\Scanner->addToCache('appdata_ocgwps2...', Array, 1571) 
#5 /localhost/htdocs/xxx/lib/private/Files/Cache/Scanner.php(322): OC\Files\Cache\Scanner->scanFile('appdata_ocgwps2...', 3, 1570, Object(OC\Files\Cache\CacheEntry), false) 
#6 /localhost/htdocs/xxx/lib/private/Files/Cache/Updater.php(124): OC\Files\Cache\Scanner->scan('appdata_ocgwps2...', false, 3, false) 
#7 /localhost/htdocs/xxx/lib/private/Files/View.php(321): OC\Files\Cache\Updater->update('appdata_ocgwps2...', 1512417586) 
#8 /localhost/htdocs/xxx/lib/private/Files/View.php(1171): OC\Files\View->writeUpdate(Object(OCA\Files_Trashbin\Storage), 'appdata_ocgwps2...') 
#9 /localhost/htdocs/xxx/lib/private/Files/View.php(699): OC\Files\View->basicOperation('file_put_conten...', '/appdata_ocgwps...', Array, '(function($) {\n...') 
#10 /localhost/htdocs/xxx/lib/private/Files/Node/File.php(64): OC\Files\View->file_put_contents('/appdata_ocgwps...', '(function($) {\n...') 
#11 /localhost/htdocs/xxx/lib/private/Files/SimpleFS/SimpleFile.php(95): OC\Files\Node\File->putContent('(function($) {\n...') 
#12 /localhost/htdocs/xxx/lib/private/Template/JSCombiner.php(167): OC\Files\SimpleFS\SimpleFile->putContent('(function($) {\n...') 
#13 /localhost/htdocs/xxx/lib/private/Template/JSCombiner.php(89): OC\Template\JSCombiner->cache('/localhost/htdo...', 'merged-template...', Object(OC\Files\SimpleFS\SimpleFolder)) 
#14 /localhost/htdocs/xxx/lib/private/Template/JSResourceLocator.php(112): OC\Template\JSCombiner->process('/localhost/htdo...', 'core/js/merged-...', 'core') 
#15 /localhost/htdocs/xxx/lib/private/Template/JSResourceLocator.php(68): OC\Template\JSResourceLocator->cacheAndAppendCombineJsonIfExist('/localhost/htdo...', 'core/js/merged-...') 
#16 /localhost/htdocs/xxx/lib/private/Template/ResourceLocator.php(76): OC\Template\JSResourceLocator->doFind('js/merged-templ...') 
#17 /localhost/htdocs/xxx/lib/private/TemplateLayout.php(249): OC\Template\ResourceLocator->find(Array) 
#18 /localhost/htdocs/xxx/lib/private/TemplateLayout.php(132): OC\TemplateLayout::findJavascriptFiles(Array) 
#19 /localhost/htdocs/xxx/lib/private/legacy/template.php(205): OC\TemplateLayout->__construct('guest', '') 
#20 /localhost/htdocs/xxx/lib/private/Template/Base.php(132): OC_Template->fetchPage() 
#21 /localhost/htdocs/xxx/lib/base.php(408): OC\Template\Base->printPage() 
#22 /localhost/htdocs/xxx/lib/base.php(301): OC::printUpgradePage() 
#23 /localhost/htdocs/xxx/lib/base.php(962): OC::checkUpgrade() 
#24 /localhost/htdocs/xxx/index.php(48): OC::handleRequest() 
#25 {main}

Next Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'UPDATE "oc_filecache" SET "etag" = ?, "storage_mtime" = ?, "checksum"=? WHERE ("etag" <> ? OR "storage_mtime" <> ? OR "checksum" <> ? OR "etag" IS NULL OR "storage_mtime" IS NULL OR "checksum" IS NULL) AND "fileid" = ? ' with params ["46f82d1cd7b969e0c309b30ffcf53072", null, "", "46f82d1cd7b969e0c309b30ffcf53072", null, "", 1571]: SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_filecache.storage_mtime in /localhost/htdocs/xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:54 

Stack trace: #0 /localhost/htdocs/xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException)) 
#1 /localhost/htdocs/xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'UPDATE "oc_file...', Array) 
#2 /localhost/htdocs/xxx/lib/private/DB/Connection.php(192): Doctrine\DBAL\Connection->executeQuery('UPDATE "oc_file...', Array, Array, NULL) 
#3 /localhost/htdocs/xxx/lib/private/Files/Cache/Cache.php(320): OC\DB\Connection->executeQuery('UPDATE "oc_file...', Array) 
#4 /localhost/htdocs/xxx/lib/private/Files/Cache/Scanner.php(276): OC\Files\Cache\Cache->update(1571, Array) 
#5 /localhost/htdocs/xxx/lib/private/Files/Cache/Scanner.php(216): OC\Files\Cache\Scanner->addToCache('appdata_ocgwps2...', Array, 1571) 
#6 /localhost/htdocs/xxx/lib/private/Files/Cache/Scanner.php(322): OC\Files\Cache\Scanner->scanFile('appdata_ocgwps2...', 3, 1570, Object(OC\Files\Cache\CacheEntry), false) 
#7 /localhost/htdocs/xxx/lib/private/Files/Cache/Updater.php(124): OC\Files\Cache\Scanner->scan('appdata_ocgwps2...', false, 3, false) 
#8 /localhost/htdocs/xxx/lib/private/Files/View.php(321): OC\Files\Cache\Updater->update('appdata_ocgwps2...', 1512417586) 
#9 /localhost/htdocs/xxx/lib/private/Files/View.php(1171): OC\Files\View->writeUpdate(Object(OCA\Files_Trashbin\Storage), 'appdata_ocgwps2...') 
#10 /localhost/htdocs/xxx/lib/private/Files/View.php(699): OC\Files\View->basicOperation('file_put_conten...', '/appdata_ocgwps...', Array, '(function($) {\n...') 
#11 /localhost/htdocs/xxx/lib/private/Files/Node/File.php(64): OC\Files\View->file_put_contents('/appdata_ocgwps...', '(function($) {\n...') 
#12 /localhost/htdocs/xxx/lib/private/Files/SimpleFS/SimpleFile.php(95): OC\Files\Node\File->putContent('(function($) {\n...') 
#13 /localhost/htdocs/xxx/lib/private/Template/JSCombiner.php(167): OC\Files\SimpleFS\SimpleFile->putContent('(function($) {\n...') 
#14 /localhost/htdocs/xxx/lib/private/Template/JSCombiner.php(89): OC\Template\JSCombiner->cache('/localhost/htdo...', 'merged-template...', Object(OC\Files\SimpleFS\SimpleFolder)) 
#15 /localhost/htdocs/xxx/lib/private/Template/JSResourceLocator.php(112): OC\Template\JSCombiner->process('/localhost/htdo...', 'core/js/merged-...', 'core') 
#16 /localhost/htdocs/xxx/lib/private/Template/JSResourceLocator.php(68): OC\Template\JSResourceLocator->cacheAndAppendCombineJsonIfExist('/localhost/htdo...', 'core/js/merged-...') 
#17 /localhost/htdocs/xxx/lib/private/Template/ResourceLocator.php(76): OC\Template\JSResourceLocator->doFind('js/merged-templ...') 
#18 /localhost/htdocs/xxx/lib/private/TemplateLayout.php(249): OC\Template\ResourceLocator->find(Array) 
#19 /localhost/htdocs/xxx/lib/private/TemplateLayout.php(132): OC\TemplateLayout::findJavascriptFiles(Array) 
#20 /localhost/htdocs/xxx/lib/private/legacy/template.php(205): OC\TemplateLayout->__construct('guest', '') 
#21 /localhost/htdocs/xxx/lib/private/Template/Base.php(132): OC_Template->fetchPage() 
#22 /localhost/htdocs/xxx/lib/base.php(408): OC\Template\Base->printPage() 
#23 /localhost/htdocs/xxx/lib/base.php(301): OC::printUpgradePage() 
#24 /localhost/htdocs/xxx/lib/base.php(962): OC::checkUpgrade() 
#25 /localhost/htdocs/xxx/index.php(48): OC::handleRequest() 
#26 {main}Internal Server Error The server encountered an internal error and was unable to complete your request. Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report. More details can be found in the server log.

Next Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing '
UPDATE "oc_filecache" 
   SET "etag" = ?, 
       "storage_mtime" = ?, 
       "checksum"=? 
WHERE ("etag" <> ? OR 
       "storage_mtime" <> ? OR 
       "checksum" <> ? OR 
       "etag" IS NULL OR 
       "storage_mtime" IS NULL OR 
       "checksum" IS NULL) AND "fileid" = ? ' 
with params ["2059b968db70b099bce5565211845027", null, "", "2059b968db70b099bce5565211845027", null, "", 1571]:

SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_filecache.storage_mtime 
in /localhost/htdocs/xxx/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractSQLiteDriver.php:54

Why is the 2nd param null?

**Comment by blizzz** [comment]
@icewind1991

**Comment by MarioKlebsch** [comment]
In the mean time I found out, the problem was triggered by a missing entry 
> disable_functions = exec

in php.ini.

This caused problems in lib/private/LargeFileHelper.php:
>        public function getFileMtime($fullPath) {
>                if (\OC_Helper::is_function_enabled('exec')) {
>                        $os = strtolower(php_uname('s'));
>                        if (strpos($os, 'linux') !== false) {
>                                return $this->exec('stat -c %Y ' . escapeshellarg($fullPath));
>                        }
>                }
>
>                return filemtime($fullPath);
>        }

The code is running chroot()ed and neither /bin/sh nor stat is available. So exec will fail, but this error seems to be unnoticed. Nothing about this problem was written the the log files. :-(
>        protected function exec($cmd) {
>                $result = trim(exec($cmd));
>                return ctype_digit($result) ? 0 + $result : null;
>        }

exec() is called passing only a single parameter, but it must be called with three parameters to being able to return errors.

**Comment by skjnldsv** [comment]
Closing then as it is a php.ini config issue
