### ISSUE TITLE
set default_language in first logging

### ISSUE THREAD

**Issue by universcom** [nextcloud/server#7394]
Hi dears. I install nextcloud12 and want set my default_language to Persian. I set default_language to "fa" in config.php in config directory. but not working and my language is English. please help me to my users in first start use Persian language.

**Comment by blizzz** [comment]
>  * This sets the default language on your Nextcloud server, using ISO_639-1
 * language codes such as ``en`` for English, ``de`` for German, and ``fr`` for
 * French. It overrides automatic language detection on public pages like login
 * or shared items. User's language preferences configured under "personal ->
 * language" override this setting after they have logged in.

I guess with a fresh (test) user, Farsi will be set. If you want to be very very drastic and stric, you can enforce farsi by ``'force_language' => 'fa'`` in the config.php.

**Comment by MorrisJobke** [comment]
The default_language is only used when there is none present in the user settings or the browser. Otherwise those are used (in that order).
