### ISSUE TITLE
Horizontal scaling - file locking not working?

### ISSUE THREAD

**Issue by ddecaro94** [nextcloud/server#7398]
Hi,
I have a fresh install of Nextcloud 12.0.3 inside an LXD container, using another LXD container for MySQL server and one for the Redis cache. The data folder is a smb share in the private network. To host an onlyoffice server under the same local network (having different host name) i configured an haproxy container in tcp mode in order to route the requests based on the SSL SNI, and everything works like a charm.

Lately i have tried, out of pure curiosity, if it could be possible to scale the nextcloud install on multiple LXD containers: I duplicated exactly the same image that was working and added to the haproxy backend to be balanced. The data directory was mounted in the same way it was on the first container, caching and db are external, it was looking like there was a chance for it to work.

Instead i noticed that when I'm reloading the page, once every two requests the page loading fails, moreover i cannot access logs anymore. Is there any file locking issue on the smb share that should be considered? Should i execute the file scan? The data of the two instances should be in sync (except for the applications and their data), how can i scale horizontally?

Thank you very much.

### Server configuration

**Operating system**:
Ubuntu 17.10
**Web server:**
Apache 2.4
**Database:**
MySQL 5.7
**PHP version:**
7.1
**Nextcloud version:** (see Nextcloud admin page)
12.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh
**Where did you install Nextcloud from:**
Manual install

**Comment by blizzz** [comment]
Is file locking set up in your config.php accordingly?

**Comment by ddecaro94** [comment]
Yes, at least i believe so, this is my current config.php

<?php
$CONFIG = array (
  'instanceid' => 'oc2umolwrkhi',
  'passwordsalt' => 'G8yyTvLtHH2h8X00Tp2eXPEBfklCNP',
  'secret' => '3u+X9bg0xO66Cxj4jTnDfCcdRg100jyWQ5dl15wnxmVOiEcB',
  'trusted_domains' =>
  array (
    0 => 'nextcloud.local',
    1 => '******',
  ),
  'datadirectory' => '/share',
  'overwrite.cli.url' => 'http://nextcloud.station',
  'dbtype' => 'mysql',
  'version' => '12.0.3.3',
  'dbname' => 'nextcloud',
  'dbhost' => 'mysql:3306',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => '****',
  'installed' => true,
  'updater.release.channel' => 'stable',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'redis' =>
  array (
    'host' => 'redis',
    'port' => 6379,
    'timeout' => 0.0,
  ),
  'htaccess.RewriteBase' => '/',
  'mail_from_address' => 'admin',
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_domain' => '****',
  'loglevel' => 0,
  'mail_smtpsecure' => 'tls',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpport' => '587',
  'mail_smtpname' => '****',
  'mail_smtppassword' => '****',
);

Am I currently misconfigured for horizontal scaling? Can it be something about the instance id and secret? (being the instances following the first clones of the main one, their config.php is exactly the same)

**Comment by MorrisJobke** [comment]
> Lately i have tried, out of pure curiosity, if it could be possible to scale the nextcloud install on multiple LXD containers: I duplicated exactly the same image that was working and added to the haproxy backend to be balanced. The data directory was mounted in the same way it was on the first container, caching and db are external, it was looking like there was a chance for it to work.

The load balancing needs to happen via sticky sessions for example. You could configure HAProxy in a way to inject those and redirect the users to the very same instances. Otherwise you need to use a shared session pool. Then the load balancing should work just fine.

The config.php needs to be exactly the same on all hosts. Keep in mind to run the update only on one machine and after the update copy over the config.php to all other nodes.

For further help on this setup issue I would ask you to seek for help in the forums, where are some posts about scaling Nextcloud: https://help.nextcloud.com

Thanks

**Comment by bmullan** [comment]
@ddecaro94 
I'd like to ask if you have documented your steps to install all of this in LXD containers.   The reason I ask is that I am the moderator of the LXD sub-reddit and it would be awesome if the instructions for how to install NextCloud, MySQL and ReDis could be posted there for others to follow?

If not the instructions, if you have a blog post somewhere documenting your installation you could just post the link to your Blog post?

https://www.reddit.com/r/LXD/

Just thought I'd ask... thanks
Brian

**Comment by ddecaro94** [comment]
@bmullan
Hi Brian,

Unfortunately I didn't document the installation anywhere, but as soon as I have time I'm thinking to repeat the process to clean all the mess that I have created on the system installing by trial and error, I'll surely be careful about documenting the process and making it available on the sub-reddit.

Have a nice evening,

Daniele
