### ISSUE TITLE
Add Automatic Tagging

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#74]
I requested this on Owncloud but it went nowhere. The feature is to implement automatic tagging for specific files. Say I have a section for invoices and for that section I want the files to be scanned to pull specific information from it. Let's say for example, I want it to scan and pull the invoice number for one tag, the customer name for another tag, total for a third tag automatically. This is assuming that all invoice pages would have the same base template. Would this be a possibility?

**Comment by mar1u5** [comment]
Should be covered by **workflow engine** ,or not? @nickvergessen

**Comment by nickvergessen** [comment]
Hmm well, we can not read the file content in the current position.
But that also sounds like something different then the actual auto tagging from https://github.com/nextcloud/files_automatedtagging

**Comment by c0fe** [comment]
@nickvergessen any recommendation on the best way to read the files?

**Comment by nickvergessen** [comment]
Wait for Nextcloud 10, you can not use it before anyway

**Comment by nickvergessen** [comment]
Closing since that is implemented

**Comment by DarkknightAK** [comment]
is it possible to define also a filename something like *importend
