### ISSUE TITLE
External Auth (e.g OAuth) for one time file shares

### ISSUE THREAD

**Issue by mciverza** [nextcloud/server#740]
### Expected behaviour

**Feature request**: related to "**share with link**" whereby an external ID provider could be used instead of (only) a password. 

Use case: user1 sends a file to someone with a microsoft liveID.  NextCloud offloads the user verification to Microsoft, and if a positive ID response is received the file can be downloaded by the user.   

Security issue it solves: avoids having passwords, because then users simply email the password to the recipient, which would defeat the security benefit of the password.  

This is a follow on from a discussion in #nextcloud-dev on Freenode IRC, with assistance from @MariusBluem 
### Actual behaviour

Link is emailed, but the link password still needs to be sent to the intended recipient.
### Alternative solution:

Temporary account creation. Automatic creation of user with external authentication against Google/Twitter/MS account when a share for that "email" address is created. Once the file has been retrieved or the link timeout expires, the account gets deleted from the NextCloud server.

(It is understood that each possible external auth provider would need to have been already configured by the administrators of the NextCloud server)

**Comment by MorrisJobke** [comment]
The plain one time share link is discussed in #6841

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest and no respond since around 2 years. Please reopen if you still want to implement this.
