### ISSUE TITLE
Theming on light color

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#7401]
On a very light color, the icons are white, but I think they should be black, or?

![image](https://user-images.githubusercontent.com/5836855/33621717-094dce80-d9ec-11e7-8b30-5b729975cd05.png)
@juliushaertl @nextcloud/theming 

Color is: F9FF00

**Comment by sunjam** [comment]
Allowing clients to optionally set their own custom color from a hex color wheel would be ideal.  This is also exactly what is already done for the background color itself.

**Comment by juliushaertl** [comment]
@sunjam Setting color will not work, since we just invert the icons we have. Changing to custom colors would be a quite big adjustment. Besides that the theming app should provide great default theming without having to mess with many settings.

**Comment by tobiasKaminsky** [comment]
I tested it with latest master and color #F9FF00.
The top left icons are still white, but top right (search, contacts) are black.

Is it also possible that the default logo is turned to black if needed?
![image](https://user-images.githubusercontent.com/5836855/34758867-1e9f9558-f5d9-11e7-841e-04169d0d2c27.png)

**Comment by MorrisJobke** [comment]
Nope the logo is the logo and will not be adjusted magically. If you theme your Nextcloud you should also adjust the logo to match.

**Comment by juliushaertl** [comment]
> I tested it with latest master and color #F9FF00.
> The top left icons are still white, but top right (search, contacts) are black.

That's actually an regression. I wonder why this didn't happend to me when testing. Let me have a look.

**Comment by MorrisJobke** [comment]
A - I mixed up the top left icons (app icons) with the actual logo (also in the top left) - sorry

**Comment by tobiasKaminsky** [comment]
> Nope the logo is the logo and will not be adjusted magically

This is fine for me. It was just an idea :-)

**Comment by juliushaertl** [comment]
Finally fixed with #7767
