### ISSUE TITLE
Dismiss All Notifications

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#7403]
Hi, I'm requesting the ability to Dismiss All Notifications in bulk rather than individually dismissing each one by clicking on the top right corner.
![dismiss-all](https://user-images.githubusercontent.com/1787238/33629196-0fcc0cf6-d9b8-11e7-8ea0-42fe2f2a5a13.png)

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers for ideas how to implement this

**Comment by skjnldsv** [comment]
Shouldn't this be in https://github.com/nextcloud/notifications? :)

**Comment by enoch85** [comment]
Cred to @nachoparker for implementing that in the nPi.

**Comment by MorrisJobke** [comment]
> Shouldn't this be in https://github.com/nextcloud/notifications? :)

You are right - I thought it is part of the server repo. 

@sunjam Could I ask you to open this over there? Thanks 👍
