### ISSUE TITLE
Request: Adjust Admin Settings Scroll bar position.

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#7405]
It'd be helpfiul to be able to select and re-position the admin scroll bar.  It is currently fixed in place and adds a lot of white space, which makes the Nextcloud window wider than my max screen resolution of 1366 x 768.
![resize-bar](https://user-images.githubusercontent.com/1787238/33631256-e2a26bba-d9be-11e7-92be-b7dc4944a463.png)

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers 

We collapse this automatically once a given width is reached. Looks like your window is a bit wider. Still I don't know if it makes sense to collapse it earlier. 🤔

**Comment by sunjam** [comment]
I'm actually thinking about just grabbing it and adjusting the width to
right or left by drag and drop.  Collapsing the menu would be interesting
(perhaps if fully dragged to the left).

**Comment by skjnldsv** [comment]
I don't get what is this issue about! 🙈🤔

**Comment by skjnldsv** [comment]
The vertical spacing to avoid the scrollbar?

**Comment by jancborchardt** [comment]
@sunjam the left navigation is standardized across all components and apps and to have the same width everywhere so you can always expect the content to be in the same place. It might add a bit of whitespace, but also nicely visually separates the navigation from content.

**Comment by sunjam** [comment]
@jancborchardt The menu actually doesn't look good on my thinkpad at 1366x768.  That is why I opened the issue.  I appreciate the follow up, but to be clear... the window is larger than my maximum resolution and is therefore not easy to navigate.  I have to shrink the font very, very small in order to see all of the admin settings in the external storage menu.

**Comment by skjnldsv** [comment]
@sunjam could you post a full screenshot?
Are you talking about width or height?
