### ISSUE TITLE
Add support for HEIF/HEVC

### ISSUE THREAD

**Issue by EricKerby** [nextcloud/server#7406]
HEIF and HEVC image and video files are now becoming increasingly prevalent with the latest moves by Apple to embrace the standards on the latest iOS and mac OS versions. Dropbox has a help page on the formats here: https://www.dropbox.com/help/photos-videos/ios-formats. Nextcloud should add support for previewing/displaying images and videos in these formats in the web interface and mobile apps.

**Comment by c0fe** [comment]
Second that enhancement here, it would be quite helpful since I already work with those formats.

**Comment by tflidd** [comment]
There were some discussions on the forum about it. The format seems to be patent-protected and it could be legally difficult to implement this:
https://help.nextcloud.com/t/ios11-heic-heif-format/20368

In the ios client it is solved in that way that you can choose to upload everything in jpg:
https://help.nextcloud.com/t/warning-for-ios-11-heic-and-hevc-formats-unsupported/21229

**Comment by hoellen** [comment]
I just want to let you know that Google introduce HEIF support with Android P and Windows will support it nativly, too. 
https://www.cnet.com/news/windows-supports-heif-space-squeezing-photo-format/

**Comment by c0fe** [comment]
@LukasReschke would this be a candidate for Milestone Version 14?

**Comment by steiny2k** [comment]
Just wanted to point you to upstream attempts to tackle the issue on the server side (on-the-fly preview generation using a recent version ImageMagick, generating .jpg thumbnails):
https://github.com/owncloud/gallery/issues/737
https://github.com/owncloud/core/pull/30093
https://github.com/owncloud/core/pull/30108

I think this could also be tackled as an app similar to CameraRawPreviews (or even be integrated to the it):
https://github.com/cowai/camerarawpreviews

**Comment by MorrisJobke** [comment]
Fixed in #10526

**Comment by freekvh** [comment]
Sorry to respond to this old feature, but for me this has never worked. I Don't see previews of heic images on Firefox on Windows, Safari on iOS or in the Nextcloud app on iOS. In the app the live image will play, but only when I hold my finger onto a sort of template preview, I never see any real previews.

Am I missing something?

**Comment by acsfer** [comment]
Run the following to check if you have HEIC support in your PHP:
`php -r 'phpinfo();' | grep HEIC`

If not: https://eplt.medium.com/5-minutes-to-install-imagemagick-with-heic-support-on-ubuntu-18-04-digitalocean-fe2d09dcef1

**Comment by freekvh** [comment]
> Run the following to check if you have HEIC support in your PHP:
> 
> `php -r 'phpinfo();' | grep HEIC`
> 
> 
> 
> If not: https://eplt.medium.com/5-minutes-to-install-imagemagick-with-heic-support-on-ubuntu-18-04-digitalocean-fe2d09dcef1

Thanx, this is helpful, however, not so much in a container environment (unless I start building them myself). I would like this to become part of the existing container offering. Or perhaps there can be a method to so low level plugins from outside the container.

**Comment by jsixface** [comment]
I use the `nextcloud:stable-fpm` image and It has the HEIC support 
```
 $docker exec -it nextcloud bash
www-data@a29fc6a2dbbd:~/html$ php -r 'phpinfo();' | grep HEIC
ImageMagick supported formats => 3FR, ............, HEIC, HISTOGRAM,.................., YUV
```

**Comment by freekvh** [comment]
> 
> 
> I use the `nextcloud:stable-fpm` image and It has the HEIC support 
> 
> ```
> 
>  $docker exec -it nextcloud bash
> 
> www-data@a29fc6a2dbbd:~/html$ php -r 'phpinfo();' | grep HEIC
> 
> ImageMagick supported formats => 3FR, ............, HEIC, HISTOGRAM,.................., YUV
> 
> ```
> 
> 

So, does it work for you? Do you have heic previews? If so I'll try migrating soon.
