### ISSUE TITLE
IE11 with white theming doesn't show black app icons

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#7408]
Safari ✅:

![bildschirmfoto 2017-12-06 um 10 03 41](https://user-images.githubusercontent.com/245432/33654050-42494358-da6f-11e7-8b02-efd683725682.png)

Edge ✅:

<img width="884" alt="bildschirmfoto 2017-12-06 um 10 17 28" src="https://user-images.githubusercontent.com/245432/33654055-466a37bc-da6f-11e7-91cf-f409c3ca2341.png">

IE 11 :x::

<img width="884" alt="bildschirmfoto 2017-12-06 um 10 17 52" src="https://user-images.githubusercontent.com/245432/33654065-4b99919c-da6f-11e7-9f5f-4312d6df0769.png">

Also happens on stable12.

cc @nextcloud/designers @nextcloud/theming 

@jancborchardt Could you have a look at this?

**Comment by MariusBluem** [comment]
The theming-icon looks a bit pixelated on Edge too :(

**Comment by MorrisJobke** [comment]
> The theming-icon looks a bit pixelated on Edge too :(

That's due to the shitty resolution of the VM. This ticket is about the non-visible app icons on IE11.

**Comment by juliushaertl** [comment]
I thought that was already fixed some time ago, let me check what's wrong there.

**Comment by jancborchardt** [comment]
This is because `filter` as we use is not compatible with IE11 as discussed in https://github.com/nextcloud/server/issues/5593, right? I checked around and saw this [blog post](http://www.cssjunction.com/plugins/css3-filter-invert-support-in-internet-explorer-10/) which refers to this jQuery plugin to make it work for IE11 and IE 10: https://shekhardesigner.github.io/InvertImages/

@juliushaertl but if you can make it work without JS I guess that’s preferable. (cc @pixelipo @skjnldsv cause you were also involved in the issue discussion I mentioned.)

**Comment by skjnldsv** [comment]
Not fond of the jquery plugin. 
We could use svg filters https://jsfiddle.net/g97e26pa/180/

**Comment by MorrisJobke** [comment]
> Not fond of the jquery plugin.
> We could use svg filters https://jsfiddle.net/g97e26pa/180/

I would also use only a minimal approach - if we have sag filters that only apply to IE -> perfect.

**Comment by pixelipo** [comment]
plugin mentioned by @jancborchardt does exactly that, @skjnldsv @MorrisJobke :) It applies SVG filter to SVG icons in IE, while "falling back" to default CSS3 filters for other browsers (Firefox, Chrome, Edge).

There's no way we can implement SVG filters selectively without JS. In addition, this solution doesn't mean that we have to apply filters directly inside SVG files (which would cause them to double in filesize and add some maintenance overhead).

**Comment by pixelipo** [comment]
[Code](https://github.com/shekhardesigner/InvertImages/blob/master/jquery.invertImages.js) in that plugin is quite simple and less than 2 kB  minimized. We could also work out our own, simplified method and add it straight into our JS code (so that we don't have to worry about source)

**Comment by skjnldsv** [comment]
> There's no way we can implement SVG filters selectively without JS. In addition, this solution doesn't mean that we have to apply filters directly inside SVG files (which would cause them to double in filesize and add some maintenance overhead).

We could also directly add this in the app menu generator, and not use anything. We won't have svgs to maintains at all and we should be able to apply the filter with css too (without the filter css3)

**Comment by pixelipo** [comment]
Yes, that's what I wrote in my previous comment, @skjnldsv ;) 

But I'm worried that we might already have a similar problem with #7319 as well. Can anyone test Talk and Gallery apps in master on IE11?

**Comment by skjnldsv** [comment]
> Yes, that's what I wrote in my previous comment, @skjnldsv ;)

🙈

> But I'm worried that we might already have a similar problem with #7319 as well. Can anyone test Talk and Gallery apps in master on IE11?

Yup, it should probably also be an issue there

**Comment by pixelipo** [comment]
I could add that code, but it would be blind, since I can't test on IE11...

**Comment by skjnldsv** [comment]
@pixelipo time for a vm! 😆

**Comment by pixelipo** [comment]
@skjnldsv no
![image](https://user-images.githubusercontent.com/4129927/34213636-1bc02800-e5a0-11e7-98fa-4a4249712c30.png)

**Comment by MorrisJobke** [comment]
> @pixelipo time for a vm! 😆

VMs can be downloaded from http://modern.ie 😉
