### ISSUE TITLE
Input field for comments no longer shows warnings about comment length

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#7414]
Since [the change of the text area to a content editable div](https://github.com/nextcloud/server/commit/ec5607544c32797901f82c4e06161938a50fe322) the input field for comments no longer shows a warning when nearing or exceeding the maximum allowed comment length.

The problem seems to come from [trying to get the div contents still using `val()`](https://github.com/nextcloud/server/blob/e428ef9d75d8b6ffe92bc9335f587fd934c10bc8/apps/comments/js/commentstabview.js#L515); `val()` returns the actual contents of the input field only when called on form elements (like `input`, `select` or `textarea`), but not when called on content editable divs. In that later case `text()` should be used instead.

The unit tests did not catch the problem because even if `val()` does not return the contents of the element it returns any value previously set through `val("whatever")`; as [the unit tests use `val("whatever")`](https://github.com/nextcloud/server/blob/2b4b3b1986e58305c08941f77a693a80cc3d5b85/apps/comments/tests/js/commentstabviewSpec.js#L329-L352) and the code under test uses `val()` the tests passed, masking the undesired use of `val()` and `val("whatever")` on a `div` element.

In other cases ([restore original comment when cancelling](https://github.com/nextcloud/server/blob/2b4b3b1986e58305c08941f77a693a80cc3d5b85/apps/comments/tests/js/commentstabviewSpec.js#L516-L536), [do not create a comment with invalid length](https://github.com/nextcloud/server/blob/2b4b3b1986e58305c08941f77a693a80cc3d5b85/apps/comments/tests/js/commentstabviewSpec.js#L299-L314) and [do not submit an edited comment with invalid length](https://github.com/nextcloud/server/blob/2b4b3b1986e58305c08941f77a693a80cc3d5b85/apps/comments/tests/js/commentstabviewSpec.js#L563-L578)) the tests failed silently because `val("whatever")` does not modify the contents of the content editable div. In the first case that makes the test invalid (as nothing was changed and thus the cancellation did nothing regarding the contents), and in the second and third it caused that when the form was submitted the input field was empty, which [prevents the comment from being sent](https://github.com/nextcloud/server/blob/e428ef9d75d8b6ffe92bc9335f587fd934c10bc8/apps/comments/js/commentstabview.js#L643).

When fixing the issues above note that the length checks must take into account the length of the message in plain text (that is, with the mention elements replaced by their _@ userId_ equivalent). Calling `_commentBodyHTML2Plain` each time a new character is typed could be taxing for browsers in low-end systems, so a more advanced approach may be needed (although that is just pure speculation; I have not tested it, and the performance could be fine even in that case).

Finally note that the length checks should be done not only when a character is typed, but also when a mention is autocompleted; this case is probably already supported thanks to the `change` event being handled too by `_onTypeComment`, but better verify it to be sure once the other issues are fixed :-)

**Comment by rullzer** [comment]
PR in #7648
