### ISSUE TITLE
WebDav still works with PHP 7.2

### ISSUE THREAD

**Issue by Ricain** [nextcloud/server#7415]
Hello,

I am part of the unfortunate ArchLinux community who upgraded PHP to 7.2 when NC12 is not compatible... See #7384 for more details!

When I open NC, I have the following message:
`This version of Nextcloud is not compatible with PHP 7.2.
You are currently running 7.2.0.`

So I expect NC not to work at all. Fortunately for me, NC Android Apps and desktop sync agents can still access data on my server.

It is not suppose to works but it does so that make it a bug :wink:

PS: thank to NextCloud developers and community for a such great app!! :relaxed:

**Comment by rullzer** [comment]
woeps... let me fix this...

**Comment by MorrisJobke** [comment]
Fixed in #8216 and will be shipped with 12.0.6

**Comment by Ricain** [comment]
Thank
