### ISSUE TITLE
Public shared gallery in grid view, IE can`t scroll

### ISSUE THREAD

**Issue by gregecslo** [nextcloud/server#7416]
Hi!

You create gallery 20+ images.
Then you share it and open link.
Change to grid mode and scroll down.
With EDGE, FF, CHROME it works just as expected but with IE it`s stuck, see attached image.
![nc_scroll](https://user-images.githubusercontent.com/17081737/33714580-c6531e04-db4f-11e7-88e6-c0dc25406c38.PNG)

Using 12.0.4 NC and latest IE.

Owncloud had same issue some time ago...

Thanks!

**Comment by MorrisJobke** [comment]
As this is the gallery app, could I ask you to open this ticket in the gallery bug tracker: https://github.com/nextcloud/gallery/issues

Thanks
