### ISSUE TITLE
Allow to set language in the user management

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#7424]
* as an admin it would be nice to set the language of a user in the user management

**Comment by rullzer** [comment]
@skjnldsv since you are touching this recently

**Comment by skjnldsv** [comment]
Granted! :D

**Comment by skjnldsv** [comment]
Boop! 
![capture d ecran_2018-04-07_12-41-39](https://user-images.githubusercontent.com/14975046/38454112-0fcc5b02-3a61-11e8-9cd5-c2e71c89fa9f.png)

**Comment by skjnldsv** [comment]
@MorrisJobke the language column is hidden by default! 😉
