### ISSUE TITLE
NC 13 Beta 1 occ repair error

### ISSUE THREAD

**Issue by mind22** [nextcloud/server#7438]
### Steps to reproduce
1. use occ maintenance:repair in the terminal

### Expected behaviour
repairing :)

### Actual behaviour
Exception throw

**Error message**
<details>
An unhandled exception has been thrown:
Error: Call to a member function isEnabledForUser() on null in /var/www/nextcloud/core/Command/Maintenance/Repair.php:89

Stack trace:
#0 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(264): OC\Core\Command\Maintenance\Repair->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#1 /var/www/nextcloud/3rdparty/symfony/console/Application.php(874): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#2 /var/www/nextcloud/3rdparty/symfony/console/Application.php(228): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Maintenance\Repair), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#3 /var/www/nextcloud/3rdparty/symfony/console/Application.php(130): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#4 /var/www/nextcloud/lib/private/Console/Application.php(173): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

#5 /var/www/nextcloud/console.php(96): OC\Console\Application->run()

#6 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')

#7 {main}

</details>

### Server configuration

**Operating system**: Ubuntu 16.04.1

**Web server:** nginx

**Database:** mariadb

**PHP version:** 7.1

**Nextcloud version:** 13b1

**Updated from an older Nextcloud/ownCloud or fresh install:** NC12 RC

**Where did you install Nextcloud from:** official

</details>

**Are you using encryption:** no

**Comment by tflidd** [comment]
Duplicate of https://github.com/nextcloud/server/issues/7309 ?

**Comment by mind22** [comment]
Ah yes you are right, seems to be the same. Then iam gonna close this here.
