### ISSUE TITLE
Thunderbird Attachment support

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/server#744]
A possibility for uploading files and use fillink in the own Nextcloud,
so, a support for large files (or all files) for uploading at first in the NextCloud
and use this in thunderbird as "filelink" /download-url 
and the store it in in the on cloud, with this it is possible for 
uploading and linking in on thunderbird mailing and have 
a small and and fast Mail-file without any big file into
but it is linking in from the nextcloud,as attachment..

best regards
Blacky

**Comment by tflidd** [comment]
ref: https://help.nextcloud.com/t/are-you-using-thunderbirds-filelink-feature-should-there-be-nextcloud-support/1935

**Comment by blackcrack** [comment]
should be updatet and namechange,
but thank you, nice :)

best regards
Blacky

**Comment by nickvergessen** [comment]
Let's track this in the forum, since there are more comments already.
