### ISSUE TITLE
NC12.0.4 - undefined index in UpdateChecker.php

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#7442]
## Expected behavior
No errors should belogged.

## Current behavior
The following errors were logged after upgrading from v12.0.3 to v12.0.4:
```
Error	PHP	Undefined index: autoupdater at ../apps/updatenotification/lib/UpdateChecker.php#49
Error	PHP	Undefined index: url at ../apps/updatenotification/lib/UpdateChecker.php#53
```
### Steps to reproduce
1. Upgrade to v12,0.4 and check the log file.

#### Server Configuration
OS: Linux 3.16.50
Web server: Apache2 2.4.29
Database: MariaDB 10.0.32
PHP version: 5.6.29
Nextcloud version: 12.0.4

#### Client Configuration
Browser: Mozilla Firefox 57.0.2
Operating system: Windows 7

**Comment by MorrisJobke** [comment]
Fix is in #7562
