### ISSUE TITLE
Show more information on webinterface why app can't be enabled

### ISSUE THREAD

**Issue by tflidd** [nextcloud/server#7443]
### Steps to reproduce
1. Try to install app, download source
2. Go to apps page, enable button is not active

### Expected behaviour
When I try to enable the app via occ, it shows me that I'm missing some dependencies (in case of the news app it was the library iconv.

### Actual behaviour
The enable button is just grey and can't be activated.

### Server configuration

**Operating system**: FreeBSD 11

**Web server:** Apache

**PHP version:** 5.6

**Nextcloud version:** 13 beta 1

**Comment by MorrisJobke** [comment]
Duplicate of #4581
