### ISSUE TITLE
Quota 0 issues: Avatar and AudioPlayer scan

### ISSUE THREAD

**Issue by azuledu** [nextcloud/server#7444]
In Nextcloud 12.0.4, there are several problems selecting "Couta 0 B" in users options:
- Avatars: it is not possible to upload a profile picture. A "Invalid image" error is shown.
- AudioPlayer: It is not possible to scan music files. It found 0 files.

I think that maybe the problem it is related with the "cache" directory on every user directory. Both apps (AudioPlayer and avatars) need to write something there but this is not possible with a 0 bytes quota. 

Maybe the 0 bytes quota should apply only for files directory and not for cache directory.

Thanks.

**Comment by MorrisJobke** [comment]
cc @rullzer looks like the previews that are stored in the app data folder.

cc @icewind1991 for the quota stuff
