### ISSUE TITLE
Update 12.0.3 12.0.4 SQLSTATE[23000] :Integrity constraint violation

### ISSUE THREAD

**Issue by hstinux** [nextcloud/server#7446]
### Steps to reproduce
1. try to update form versin 12.0.3 to 12.0.4
2. web updater 
3. ./occ upgrade
both ends up with the error below

### Expected behaviour
Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO oc_news_items (id, guid_hash, fingerprint, content_hash, rtl, search_index, guid, url, title, author, pub_date, updated_date, body, enclosure_mime, enclosure_link, feed_id, status, last_modified) SELECT id, guid_hash, fingerprint, content_hash, rtl, search_index, guid, url, title, author, pub_date, updated_date, body, enclosure_mime, enclosure_link, feed_id, status, last_modified FROM __temp__oc_news_items':

SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_news_items.feed_id
Update failed

### Server configuration

**Operating system**:
debian 8.0
**Web server:**
apache2
**Database:**
sqlite
**PHP version:**
 5.6.30
**Nextcloud version:** (see Nextcloud admin page)
12.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
BananaPi

**List of activated apps:**
Enabled:
  - activity: 2.5.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - spreed: 2.0.2
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - calendar
  - contacts
  - encryption
  - gallery
  - music
  - news
  - radio
  - user_external
  - user_ldap
  - weather

**Nextcloud configuration:**
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "instanceid": "ochh336i6ix7",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "stinux.duckdns.org",
            "192.168.178.9"
        ],
        "datadirectory": "\/mnt\/sata\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/stinux.duckdns.org\/nextcloud",
        "dbtype": "sqlite",
        "version": "12.0.3.3",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "newsletter",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "smtp.1und1.de",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
firefox 7.0.2

**Comment by MorrisJobke** [comment]
This is a bug in the news app - please report in the news app bug tracker: https://github.com/nextcloud/news/issues

Thanks
