### ISSUE TITLE
Web Updater is showing next step as succeeded although it wasn't before

### ISSUE THREAD

**Issue by GiantCrocodile** [nextcloud/server#7447]
### Steps to reproduce
1. Run Updater to update from v12.0.3 to v12.0.4
2. It fails at step creating backup with a timeout
3. I disabled maintenance mode via shell console and command `sudo -u nginx php occ maintenance:mode --off` and ran updater again

This time the backup step was done and it failed at extracting. After trying it again (maintenance mode wasn't enabled) it went ahead and finished. NextCloud instance seems healthy after login and going into admincp.

### Expected behaviour
The updater either reports wrong status or it skips the step because if you retry it was succeeded as status although it did fail.

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**: Debian 9

**Web server:** Nginx

**Database:** Postgresql

**PHP version:** 

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:** old, updated from v12.0.3

**Where did you install Nextcloud from:** I just used web installer and first time install was from zip archive from official website.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.7
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - survey_client
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** Firefox

**Comment by MorrisJobke** [comment]
Could you remove the .step file in `data/updater-INSTANCEID/.step` and retry the update. Then all steps should be executed again.

**Comment by MorrisJobke** [comment]
Is there anything in the updater.log, the nextcloud.log or the web server log file?

**Comment by GiantCrocodile** [comment]
There were no errors found in the logs and I can't retry it for you because I finished my update by retrying step by step and thus the update was finished.

**Comment by MorrisJobke** [comment]
As we can't reproduce and there are no logs I will close this ticket for now. Once this happens again we can have another look at the issue.
