### ISSUE TITLE
Folder deleted when renaming on a case-insensitive filesystem

### ISSUE THREAD

**Issue by nalt** [nextcloud/server#7452]
### Steps to reproduce
1. Server storage resides on a cifs/smb mount. The filesystem is case-insensitive.
2. On the client, create a folder "a", put a file, wait to sync
3. Rename the folder to "A"

### Expected behaviour
Folder "a" should be renamed to "A"

### Actual behaviour
The folder "a" is completely deleted, all files are gone!

### Server configuration

**Operating system**: Ubuntu / official Docker image

**Database:** MariaDB

**Nextcloud version:** 12.0.3

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Are you using external storage, if yes which one:** smb, via OS mount

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Nextcloud client 2.2.4 

**Operating system:** MacOS

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here

Error | core | unable to rename, file does not exists : files/a
-- | -- | --

```
</details>

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by nalt** [comment]
Here is a minimal test case:

- Create case-insensitive filesystem, e.g. JFS with -O:
`dd if=/dev/zero of=disk bs=1M count=512`
`mkfs.jfs -O disk `
`mkdir ~/mnt-disk ; sudo mount disk ~/mnt-disk`
`sudo touch ~/mnt-disk/a`
`sudo touch ~/mnt-disk/A`
`sudo chown www-data ~/mnt-disk/`
You should see only file `a`
- Start Nextcloud
`docker run -p 8060:80 -v ~/mnt-disk:/var/www/html/data nextcloud`
- Setup admin account
- Connect Nextcloud client (I used Ubuntu verison)
- Create a directory `a`, add a file into it, wait to sync
- Rename this directory to `A`
- The directory will be deleted on the server.

The web client refuses to rename the folder, which is also not entirely correct, but at least no data are lost.

**Comment by nalt** [comment]
Can anyone think of a quick workaround for this? We continue to loose files because of this bug. It's just hard for our users to remember that fixing the capitalization of a file is absolutely forbidden.

**Comment by nalt** [comment]
This bug is still there in the current version. Could anyone point to the rough location in the code where a rename is handled? I would have a look at it.

**Comment by nalt** [comment]
The file is deleted at:
https://github.com/nextcloud/3rdparty/blob/b0f180458ab55af9d6a1550f2b62dee3fdc6e1ef/sabre/dav/lib/DAV/CorePlugin.php#L641

But even if this line is commented out, the file is still deleted at:
https://github.com/nextcloud/server/blob/9834f33d56f64f63b0f05c149418b2c83d5fa37d/lib/private/Files/Storage/Local.php#L255

If both lines are commented out, the file ends up being copied though.

**Comment by tessus** [comment]
@MorrisJobke @icewind1991 is there an update on this?

This seems like a serious bug, especially since data loss is involved.

**Comment by hevisko** [comment]
Is there a functional solution to handle this syncing between case-sensitive and case-insensitive clients ?
Been bitten by similar issues today on NC 24

**Comment by techadmin-localbit** [comment]
Hello, we are experiencing the same bug. We've also Nextcloud connected to a samba folder. When a user on the windows changes a file or folder from "a" to "A" the file or folder gets deleted. The sync client reports an error but it still gets deleted. 
We're using the version 24.0.8

**Comment by szaimen** [comment]
Hi, please update to 25.0.7 or better 26.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 26-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
