### ISSUE TITLE
Nextcloud 13 expects FreeType support to be enabled in PHP GD

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#7454]
Since #6876 the system running Nextcloud should have FreeType support enabled in PHP GD; otherwise [`imagettfbbox`](https://github.com/nextcloud/server/blob/66f523e13ff98aef8cdca9f449df7353dcf60da7/lib/private/Avatar.php#L252) and [`imagettftext`](https://github.com/nextcloud/server/blob/66f523e13ff98aef8cdca9f449df7353dcf60da7/lib/private/Avatar.php#L258) would not be available (as explained in [PHP Documentation](http://php.net/manual/en/function.imagettftext.php#refsect1-function.imagettftext-notes)) and the request to get the avatar would fail with an internal error.

This only affects auto-generated avatars, and does not prevent Nextcloud from running, so it should be notified to the admin in the settings page when the requirement is not met.

**Comment by rullzer** [comment]
PR in #7480
