### ISSUE TITLE
Resolution of login screen picture

### ISSUE THREAD

**Issue by hillebr** [nextcloud/server#7459]
Nextcloud version (eg, 10.0.2): 12.0.4
Operating system and version (eg, Ubuntu 16.04): Debian 9
Apache or nginx version (eg, Apache 2.4.25): Apache/2.4.25 (Debian)
PHP version (eg, 5.6): PHP 7.0.26-1~dotdeb+8.1 (cli) ( NTS )
Is this the first time you’ve seen this error?: no error
Can you reliably replicate it? (If so, please outline steps): load Login screen

The issue you are facing:
When using the theming options and implementing a login screen picture Apache will resize the resolution of the picture down to somewhat blurry at high resolution screens (e.g. 4K or 3440 x 1440).
Is there any option to prevent this resizing?

The output of your Nextcloud log in Admin > Logging: n/a
The output of your config.php file in /path/to/nextcloud (make sure you remove any identifiable information!): n/a
The output of your Apache/nginx/system log in /var/log/____: n/a

https://help.nextcloud.com/t/resolution-of-login-screen-picture/24151

**Comment by hillebr** [comment]
from: juliushaertl Designer & app developer
11h

Yeah, we resize the image to 1920x1080 if I remember correctly, but we should support higher resolutions there. @Rene_Hillebrand please open an issue at the server repository on GitHub.

**Comment by MorrisJobke** [comment]
cc @nextcloud/theming
