### ISSUE TITLE
Files don't get deleted locally when using Minio as an Object Store

### ISSUE THREAD

**Issue by dachinat** [nextcloud/server#7463]
I have configured Nextcloud to use local Minio server, created files appear in given data directory (i.e.: urn:oid:7074  urn:oid:7096) but these fails don't get deleted when removing corresponding files with Nextcloud UI.

### Steps to reproduce
1. Install local Minio server and client

	* https://dl.minio.io/server/minio/release/linux-amd64/minio
	* https://dl.minio.io/client/mc/release/linux-amd64/mc

2. Successfully start Minio service with assigned data directory

3. Configure Nextcloud to use Minio object store

```
'objectstore' =>
  array (
    'class' => 'OC\\Files\\ObjectStore\\S3',
    'arguments' =>
    array (
      'bucket' => 'nextcloud',
      'autocreate' => true,
      'key' => 'YOUR_KEY',
      'secret' => 'YOUR_SECRET',
      'hostname' => 'YOUR_IP',
      'port' => YOUR_PORT,
      'use_ssl' => false,
      'region' => 'optional',
      'use_path_style' => true,
    ),
  )
```

4. Open console and navigate to Nextcloud bucket in your Minio storage directory and `ls`

5. Create a file with your Nextcloud account using UI

6. `ls` again to confirm a file has been created

7. Now delete a created file with your Nextcloud UI

8. `ls` again and you will see that newly created file has no been deleted

### Expected behaviour

When you delete a file with Nextcloud UI a file in minio directory has to be destroyed as well.

### Actual behaviour

When you create a file with Nextcloud UI, a file *i.e.: urn:oid:6951* is added to Minio data directory, but when you delete it form UI file remains there.

### Server configuration

**Operating system**:

CentOS Linux release 7.4.1708 (Core)

**Web server:**

nginx
Version: nginx/1.12.2

**Database:**

MariaDB Server
Version: 10.2.11

**PHP version:**

7.1.11

**Nextcloud version:** (see Nextcloud admin page)

12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**

Updated from older Nextcloud install

**Where did you install Nextcloud from:**

https://download.nextcloud.com/server/releases

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
- activity: 2.5.2
  - admin_notifications: 1.0.1
  - comments: 1.2.0
  - dav: 1.3.0
  - encryption: 1.6.0
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - quota_warning: 1.1.1
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - unsplash: 1.0.5
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/data\/nextcloud",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": "***REMOVED SENSITIVE VALUE***"
        },
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "nextcloud",
                "autocreate": true,
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "hostname": "***REMOVED SENSITIVE VALUE***",
                "port": ***REMOVED SENSITIVE VALUE***,
                "use_ssl": false,
                "region": "optional",
                "use_path_style": true
            }
        },
        "asset-pipeline.enabled": "true",
        "skeletondirectory": "",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": "1",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "enable_previews": false,
        "updater.release.channel": "stable"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

Using local installation of Minio and objectstore for this. Nothing more.

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No.

### Client configuration
**Browser:**

Google Chrome
Version: 63.0.3239.84 (Official Build) (64-bit)

**Operating system:**

MacOS High Sierra
10.13.2 Beta

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Web server error log is empty
```
</details>

**Comment by rullzer** [comment]
Did you also empty the trashbin?

**Comment by dachinat** [comment]
@rullzer No, I have just checked and files from Minio directory got removed as I emptied a trash bin.

I guess this is an expected behavior, I'm really thankful for your response.
