### ISSUE TITLE
serverinfo needs to be accessible via token or IP whitlist

### ISSUE THREAD

**Issue by colttt** [nextcloud/server#7474]
Hello,

for monitoring purposes it would be very useful to have access to the nextcloud serverinfo via token or IP whitelist (like gitlab: https://docs.gitlab.com/ce/user/admin_area/monitoring/health_check.html). At the moment I need to login with admin rights.

It would be also usefull to have 2 URLs, one in XML format and the other in JSON.

best regards

**Comment by MorrisJobke** [comment]
> It would be also usefull to have 2 URLs, one in XML format and the other in JSON.

That is already possible - just append `?format=json` and it will give you a JSON object.



> for monitoring purposes it would be very useful to have access to the nextcloud serverinfo via token or IP whitelist (like gitlab: https://docs.gitlab.com/ce/user/admin_area/monitoring/health_check.html). At the moment I need to login with admin rights.

There was already such an request in https://github.com/nextcloud/serverinfo/issues/100
