### ISSUE TITLE
background-image of transparent image previews doesn't repeat and gets stretched

### ISSUE THREAD

**Issue by derRAV3N** [nextcloud/server#7486]
### Steps to reproduce
1. Upload transparent image to nextcloud
2. Open the uploaded image in the image preview
3. Hover over the image to enable the background-image

### Expected behaviour
The transparent part of the image should be covered by those squares that indicate transparency (I did view this by disabling `background-size` in the CSS inspector, but that only fixes it until you hover again):
<img width="895" alt="screenshot_2017-12-13 15 05 06_i9vr5s" src="https://user-images.githubusercontent.com/12349529/33942736-28f8dbfe-e017-11e7-8725-b9261b308c29.png">

### Actual behaviour
The resource-image is stretched as big as the image is:
<img width="920" alt="screenshot_2017-12-13 15 02 44_dufbkg" src="https://user-images.githubusercontent.com/12349529/33942609-be6b319c-e016-11e7-9988-37e1fd0340e6.png">

### Server configuration

**Operating system**: Ubuntu Server 16.04 LTS

**Web server:** Apache 2

**Database:** MySQL 5.7.20

**PHP version:** 7.0.22

**Nextcloud version:** 12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Yes, updated from some old ownCloud to nextCloud 9/10, then 11, 12 and now 12 > 12.0.4.

**Where did you install Nextcloud from:**
nextcloud.com

### Client configuration
**Browser:** Chrome 62.0.3202.94 and Firefox 57.0.2

**Operating system:** macOS 10.13.1 (17B1003), Windows 10 1709

**Comment by MorrisJobke** [comment]
looks like a gallery thing.

cc @pixelipo @skjnldsv @oparoz

**Comment by oparoz** [comment]
Would probably be best to open in nextcloud/gallery

**Comment by MorrisJobke** [comment]
Fix is in https://github.com/nextcloud/gallery/pull/341

**Comment by MorrisJobke** [comment]
Will be fixed in 13.
