### ISSUE TITLE
Files suddenly block

### ISSUE THREAD

**Issue by voxdemonix** [nextcloud/server#7489]
Hello.

I use nextcloud for hosting some log's files, they are really often edit/purge by clients (they never remove the files). Often the files become block : i can read it but not edit, not remove, nothing else other than read.
For can re-use them, i need to remove manually them of the file system of the server, lunch a scan with nextcloud CLI  and recreat them.

-If i try to remove them from davfs2 client, the command line respond "Invalid Argument". In the WEBUI for the concerned files i can only showing infos or download, not other actions.
-If i try to edit them with a client (echo '' > /media/file ), the client can view the effect during some second (cache i think), and after some second the "original" file re coming.

Sometime for random static files, i can't delete them with webui/davfs2, i need remove them manually too via the filesystem of the server and lunch a new scan.

**Comment by MorrisJobke** [comment]
What client do you use? Are they writing to the same file? cc @icewind1991
