### ISSUE TITLE
Position of datepicker

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#7492]
version: 13.0 beta3
browser: safari 11.0.2

<img width="415" alt="bildschirmfoto 2017-12-13 um 17 07 10" src="https://user-images.githubusercontent.com/19711361/33948814-2d3525fe-e028-11e7-8c65-a327000a5990.png">

@nextcloud/designers

**Comment by MorrisJobke** [comment]
Duplicate of #7007

**Comment by MariusBluem** [comment]
thx.
