### ISSUE TITLE
Deleting profile pictures is not possible

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#7500]
Deleting a profile picture should go back to the automated-generated profile picture, which should not be removeable ;)

![b2d6d8b8-0f9f-4306-9a96-700c7d545b08](https://user-images.githubusercontent.com/19711361/33964362-73245960-e058-11e7-8895-31f24248e7c0.jpeg)

@rullzer

**Comment by rullzer** [comment]
Lets tackle in #7498 as well

**Comment by skjnldsv** [comment]
@MariusBluem why would you want to remove this beautiful squirrel?! :D

**Comment by MorrisJobke** [comment]
Ummm .. that is then a regression. There was a button for deletion available. 🤔

**Comment by skjnldsv** [comment]
There is, it is just hidden:

https://github.com/nextcloud/server/blob/8c915baa3438c26454b7614ea03d4dadabcda5d5/settings/templates/settings/personal/personal.info.php#L83

https://github.com/nextcloud/server/blob/7a05cf300c6b3d4bdfff1bb61aa39822ff88fb8b/settings/js/settings/personalInfo.js#L63

**Comment by MorrisJobke** [comment]
Fix is in #7498
