### ISSUE TITLE
tempdirectory is not used (snap install)

### ISSUE THREAD

**Issue by qm2k** [nextcloud/server#7503]
### Steps to reproduce
1. Install Nextcloud via snap on a system with limited space on root filesystem.
2. Set `tempdirectory` in `config.php` pointing to `/media/temp`
3. Upload large file.
4. Monitor space usage, files in `/media/temp`, `/var/snap/nextcloud/common/nextcloud/tmp`

### Expected behaviour
File gets uploaded successfully, space on root filesystem is not used.

### Actual behaviour
Temporary file is created in `/var/snap/nextcloud/common/nextcloud/tmp`, not in `/media/temp`, then upload fails when system runs out of space.

(Note that config below does not contain tempdirectory since I'm filling this issue via Issue reporting app on production system where it is already deleted, but it was set with exactly this command (taken from bash history:
```
nextcloud.occ config:system:set tempdirectory --value '/media/temp'
```
and the system was rebooted before tests.)

## Server configuration detail

**Operating system:** `Linux 4.4.0-103-generic #126-Ubuntu SMP Mon Dec 4 16:23:28 UTC 2017 x86_64`

**Webserver:** Apache/2.4.28 (Unix) (fpm-fcgi)

**Database:** mysql 5.7.18

**PHP version:** 7.0.25
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, ctype, curl, dom, hash, fileinfo, filter, gd, SPL, iconv, intl, json, mbstring, mcrypt, PDO, session, pdo_sqlite, posix, Reflection, standard, SimpleXML, mysqlnd, exif, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, redis, Zend OPcache

**Nextcloud version:** 12.0.4 - 12.0.4.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from version 11 by snapd.

**Where did you install Nextcloud from:** snap

<details><summary>Signing status</summary>

No errors have been found.
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.5.2
 - apporder: 0.4.1
 - bruteforcesettings: 1.0.2
 - calendar: 1.5.7
 - comments: 1.2.0
 - contacts: 2.0.1
 - dav: 1.3.0
 - federatedfilesharing: 1.2.0
 - federation: 1.2.0
 - files: 1.7.2
 - files_clipboard: 0.6.4
 - files_pdfviewer: 1.1.1
 - files_sharing: 1.4.0
 - files_texteditor: 2.4.1
 - files_trashbin: 1.2.0
 - files_versions: 1.5.0
 - files_videoplayer: 1.1.0
 - firstrunwizard: 2.1
 - gallery: 17.0.0
 - groupfolders: 1.1.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.0.0
 - nextcloud_announcements: 1.1
 - notifications: 2.0.0
 - oauth2: 1.0.5
 - password_policy: 1.2.2
 - provisioning_api: 1.2.0
 - serverinfo: 1.2.0
 - sharebymail: 1.2.0
 - spreed: 2.0.2
 - survey_client: 1.0.0
 - systemtags: 1.2.0
 - theming: 1.3.0
 - twofactor_backupcodes: 1.1.1
 - twofactor_totp: 1.3.1
 - workflowengine: 1.2.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - mail
 - radio
 - registration
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "apps_paths": [
        {
            "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
            "url": "\/extra-apps",
            "writable": true
        }
    ],
    "supportedDatabases": [
        "mysql"
    ],
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "\/tmp\/sockets\/redis.sock",
        "port": 0
    },
    "instanceid": "oc45f8iuvd3p",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "server.example.com",
        "cloud.example.com"
    ],
    "datadirectory": "\/media\/user-data\/",
    "dbtype": "mysql",
    "version": "12.0.4.3",
    "dbname": "nextcloud",
    "dbhost": "localhost:\/tmp\/sockets\/mysql.sock",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_from_address": "nextcloud",
    "mail_domain": "example.com",
    "mail_smtphost": "smtp.example.com",
    "mail_smtpport": "587",
    "overwriteprotocol": "https",
    "overwritewebroot": "\/nextcloud",
    "default_language": "ru",
    "htaccess.RewriteBase": {
        "\/nextcloud": ""
    },
    "trusted_proxies": [
        "10.1.2.3"
    ],
    "overwritehost": "cloud.example.com",
    "mail_smtpsecure": "tls",
    "overwrite.cli.url": "https:\/\/cloud.example.com\/nextcloud",
    "skeletondirectory": "",
    "loglevel": 2,
    "maintenance": false,
    "tempdirectory": "\/media\/temp"
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0

**Operating system:** Ubuntu 16.04

**Comment by rullzer** [comment]
Please fill at https://github.com/nextcloud/nextcloud-snap

**Comment by qm2k** [comment]
It's been some time and I no longer administer the service in question. Whoever still needs to upload large files to Nextcloud are welcome to reopen the issue where necessary.
