### ISSUE TITLE
Different button height for add to nextcloud / dl button

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/server#7507]
There is a 1px difference between the button height (looks quite strange if you notice it :D):

![buttons](https://user-images.githubusercontent.com/1869584/33984048-8f9165c6-e0b6-11e7-8b51-8d4d43e52ab3.png)

But it´s solved in Nc 13 anyway :)

**Comment by MorrisJobke** [comment]
Yes - we fixed this lately sadly the backport isn't that easy, because it was a major rework of the CSS. :(

I hope it's okay to close this ticket here.

Thanks for the report anyway :)
