### ISSUE TITLE
Settings button is invisible

### ISSUE THREAD

**Issue by joekerna** [nextcloud/server#7508]
### Steps to reproduce
1. Install Nextcloud 13 Beta 3
2. Log in

### Expected behaviour
Settings button should be visible at the top right corner

### Actual behaviour
Settings button is not visible, menu can be accessed though

![2017-12-14_11h02_45](https://user-images.githubusercontent.com/23077594/33986607-60ca8d6e-e0be-11e7-96ef-bd438d9a92ea.png)

### Server configuration

**Operating system**: Ubuntu 17.10

**Web server:** Nginx 1.12

**Database:** MySQL

**PHP version:** 7.1.12

**Nextcloud version:** 13 Beta 3

**Updated from an older Nextcloud/ownCloud or fresh install:** Update

**Where did you install Nextcloud from:** Nextcloud website

### Client configuration
**Browser:** Firefox on Windows and Mac

**Operating system:** Windows 10 / Mac High Sierra

**Comment by MorrisJobke** [comment]
This looks like the avatar generation failed. Could you check the nextcloud.log

**Comment by joekerna** [comment]
Scss is disabled for /var/www/nextcloud/core/css/jquery.ocdialog.scss, ignoring
Scss is disabled for /var/www/nextcloud/core/css/share.scss, ignoring
Scss is disabled for /var/www/nextcloud/core/css/server.scss, ignoring
> {"reqId":"dWoU0gjeYzVHZu20IgMz","level":0,"time":"2017-12-14T12:40:00+01:00","remoteAddr":"194.39.218.10","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/jquery-ui-fixes.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko\/20100101 Firefox\/52.0; Firefox 52.5.0 - 111512-1800920044-1.38","version":"13.0.0.8"}
> {"reqId":"dWoU0gjeYzVHZu20IgMz","level":0,"time":"2017-12-14T12:40:00+01:00","remoteAddr":"194.39.218.10","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/server.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko\/20100101 Firefox\/52.0; Firefox 52.5.0 - 111512-1800920044-1.38","version":"13.0.0.8"}
> {"reqId":"dWoU0gjeYzVHZu20IgMz","level":0,"time":"2017-12-14T12:40:00+01:00","remoteAddr":"194.39.218.10","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/share.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko\/20100101 Firefox\/52.0; Firefox 52.5.0 - 111512-1800920044-1.38","version":"13.0.0.8"}
> {"reqId":"dWoU0gjeYzVHZu20IgMz","level":0,"time":"2017-12-14T12:40:00+01:00","remoteAddr":"194.39.218.10","user":"--","app":"core","method":"GET","url":"\/login","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/jquery.ocdialog.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64; rv:52.0) Gecko\/20100101 Firefox\/52.0; Firefox 52.5.0 - 111512-1800920044-1.38","version":"13.0.0.8"}

**Comment by joekerna** [comment]
The issue is still there in Nextcloud 13 Beta 4

**Comment by joekerna** [comment]
Issue is gone in Nextcloud 13 RC1.


Thank you!
