### ISSUE TITLE
Configure extra Mail-Headers for SMTP

### ISSUE THREAD

**Issue by FrankGiesecke** [nextcloud/server#7515]
It would be great if an administrator can specify some extra mail headers for sending email over SMTP.
So it would be possible to use external mail providers like SendGrid which allows to specify and use templates for email.

For further information see [Using the SMTP API ](https://sendgrid.com/docs/API_Reference/SMTP_API/using_the_smtp_api.html).

This feature request will notably support SendGrid. By adding some extra mail headers, many mail systems can be used.

**Comment by MorrisJobke** [comment]
@FrankGiesecke Cheers to a fellow Chemnitz guy ;)

For send grid it needs then this as additional headers, right?

```
X-SMTPAPI: abc
```

In the documentation it looks like the passed parameter is dynamic and holds the email details. i guess then it would be better to have a dedicated Sendgrip option, or am I wrong here?

**Comment by dmaroulidis** [comment]
Nope, I think a dedicated Sendgrid option is better.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
