### ISSUE TITLE
Nextcloud 13 beta3 updating files

### ISSUE THREAD

**Issue by 00tiagopolicarpo00** [nextcloud/server#7516]
### Steps to reproduce
1. Update files from client desktop to server
[nextcloud.log](https://github.com/nextcloud/server/files/1559786/nextcloud.log)
![selection_095](https://user-images.githubusercontent.com/23580329/34000111-4306936a-e0e4-11e7-9f6d-e6a742a5ae28.png)

2.
3.

webdav	Sabre\DAV\Exception: An exception occurred while executing 'INSERT INTO "oc_filecache" ("mimepart","mimetype","mtime","size","etag","storage_mtime","permissions","parent","checksum","path_hash","path","name","storage") SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM "oc_filecache" WHERE "storage" = ? AND "path_hash" = ? HAVING COUNT(*) = 0' with params [1, 2, 1513265309, -1, "5a32989d29f51", 1513265309, 31, 20182, "", "a452a31376c08c2005c8bb52bf40a063", "files_encryption\/keys\/files\/apps\/colibri.bak\/plugins\/colibri.rcp_9.4.3\/rcp\/colibri\/workbench\/preferences\/tabelas\/bancos\/contasbancarias\/shell", "shell", 4, 4, "a452a31376c08c2005c8bb52bf40a063"]: SQLSTATE[23505]: Unique violation: 7 ERROR: duplicate key value violates unique constraint "fs_storage_path_hash" DETAIL: Key (storage, path_hash)=(4, a452a31376c08c2005c8bb52bf40a063) already exists.

    /var/websites/www/localhost/apps/dav/lib/Connector/Sabre/File.php - line 221: OCA\DAV\Connector\Sabre\File->convertToSabreException(Object(Doctrine\DBAL\Exception\UniqueConstraintViolationException))
    /var/websites/www/localhost/apps/dav/lib/Connector/Sabre/Directory.php - line 151: OCA\DAV\Connector\Sabre\File->put(Resource id #27)
    /var/websites/www/localhost/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096: OCA\DAV\Connector\Sabre\Directory->createFile('Contasbancarias...', Resource id #27)
    /var/websites/www/localhost/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 525: Sabre\DAV\Server->createFile('files/tiagopoli...', Resource id #27, NULL)
    [internal function] Sabre\DAV\CorePlugin->httpPut(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/websites/www/localhost/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/websites/www/localhost/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method PUT', Array)
    /var/websites/www/localhost/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/websites/www/localhost/apps/dav/lib/Server.php - line 281: Sabre\DAV\Server->exec()
    /var/websites/www/localhost/apps/dav/appinfo/v2/remote.php - line 35: OCA\DAV\Server->exec()
    /var/websites/www/localhost/remote.php - line 164: require_once('/var/websites/w...')
    {main}

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## Server configuration detail

**Operating system:** Linux 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64

**Webserver:** nginx/1.10.3 (fpm-fcgi)

**Database:** pgsql PostgreSQL 9.5.10 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609, 64-bit

**PHP version:** 7.0.22-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, imap, intl, json, ldap, exif, mcrypt, mysqli, pdo_mysql, pdo_pgsql, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.0 Beta 3 - 13.0.0.8

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - admin_notifications: 1.0.1
 - announcementcenter: 3.1.1
 - bookmarks: 0.10.1
 - calendar: 1.5.7
 - caniupdate: 0.1.1
 - circles: 0.13.6
 - comments: 1.3.0
 - contacts: 2.0.1
 - dashboard: 4.0.5
 - dav: 1.4.5
 - deck: 0.2.7
 - encryption: 2.0.0
 - end_to_end_encryption: 1.0.1
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_accesscontrol: 1.3.0
 - files_automatedtagging: 1.3.0
 - files_downloadactivity: 1.2.0
 - files_frommail: 0.1.0
 - files_pdfviewer: 1.2.0
 - files_sharing: 1.5.0
 - files_snapshots: 0.1.1
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - groupfolders: 1.1.0
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.7.6
 - metadata: 0.6.0
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - orcid: 0.9.1
 - ownbackup: 17.5.0
 - password_policy: 1.3.0
 - polls: 0.8.0
 - provisioning_api: 1.3.0
 - quota_warning: 1.2.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - telephoneprovider: 1.0.1
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - files_external
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/localhost",
    "dbtype": "pgsql",
    "version": "13.0.0.8",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "updater.release.channel": "beta",
    "logtimezone": "UTC",
    "loglevel": 2,
    "log_rotate_size": 50,
    "force_language": "pt_PT",
    "mail_smtpmode": "smtp",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "has_internet_connection": true,
    "auth.bruteforce.protection.enabled": true,
    "check_for_working_htaccess": true,
    "check_for_working_wellknown_setup": true,
    "check_for_working_webdav": true,
    "theme": "",
    "preview_max_x": 512,
    "preview_max_y": 512,
    "preview_max_scale_factor": 1,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "timeout": 0,
        "dbindex": 0
    },
    "updater.secret": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this part if not used)</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0

**Operating system:** 

## Logs

<details><summary>Browser log</summary>

```
Insert your webserver log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by 00tiagopolicarpo00** [comment]
Log Nextcloud
[nextcloud.log](https://github.com/nextcloud/server/files/1559797/nextcloud.log)

**Comment by MorrisJobke** [comment]
cc @rullzer @pfiff45 @icewind1991

**Comment by 00tiagopolicarpo00** [comment]
Now i change on redis to socket.

**Comment by 00tiagopolicarpo00** [comment]
Now i change on redis to socket.

**Comment by MorrisJobke** [comment]
No feedback since a month -> will close this.
