### ISSUE TITLE
Access to external Samba file shares broken

### ISSUE THREAD

**Issue by ryannix123** [nextcloud/server#7518]
If you mount an SMB file share you can no longer access it through the web GUI. However, file sync seems to be unaffected.

CentOS 7.4
Maria DB 10.1
PHP 7.1 (Remi)

**Comment by sengst** [comment]
Same Problem here, you can open the share by opening in a new tab but not by a simple click. Tried with different browsers, desktop and mobile.

**Comment by vnpenguin** [comment]
I confirm this issue on SMB external storage.
CentOS 7 + PHP 7.2 + NextCloud 13 beta3

**Comment by icawebdesign** [comment]
Confirming the same.

- Debian 9
- PHP 7.1.12
- Nextcloud 13 beta.3

Nothing's changed (shares-wise) since before the v13 upgrade.

**Comment by MorrisJobke** [comment]
We changed quite some stuff in the underlying SMB library with the latest maintenance releases. Could you try again with 13.0.4 and report if this is fixed?

Until then I will close this for now.

**Comment by ryannix123** [comment]
@MorrisJobke I'm sorry but this is still broken in 13.0.4

**Comment by ryannix123** [comment]
@MorrisJobke 
Fatal | webdav | Icewind\SMB\Exception\Exception: Unknown error (104) for /nix_owncloud/home/nextcloud/public_html/apps/files_external/3rdparty/icewind/smb/src/Exception/Exception.php - line 35: Icewind\SMB\Exception\Exception unknown('/nix_owncloud', 104)/home/nextcloud/public_html/apps/files_external/3rdparty/icewind/smb/src/NativeState.php - line 49: Icewind\SMB\Exception\Exception fromMap(Array, 104, '/nix_owncloud')/home/nextcloud/public_html/apps/files_external/3rdparty/icewind/smb/src/NativeState.php - line 61: Icewind\SMB\NativeState->handleError('/nix_owncloud')/home/nextcloud/public_html/apps/files_external/3rdparty/icewind/smb/src/NativeState.php - line 275: Icewind\SMB\NativeState->testResult(false, 'smb //resfiles....')/home/nextcloud/public_html/apps/files_external/3rdparty/icewind/smb/src/NativeShare.php - line 262: Icewind\SMB\NativeState->getxattr('smb //resfiles....', 'system.dos_attr...')/home/nextcloud/public_html/apps/files_external/3rdparty/icewind/smb/src/NativeFileInfo.php - line 104: Icewind\SMB\NativeShare->getAttribute('/nix_owncloud', 'system.dos_attr...')/home/nextcloud/public_html/apps/files_external/3rdparty/icewind/smb/src/NativeFileInfo.php - line 123: Icewind\SMB\NativeFileInfo->getMode()/home/nextcloud/public_html/apps/files_external/lib/Lib/Storage/SMB.php - line 485: Icewind\SMB\NativeFileInfo->isHidden()/home/nextcloud/public_html/lib/private/Files/Storage/Common.php - line 142: OCA\Files_External\Lib\Storage\SMB->isUpdatable('')/home/nextcloud/public_html/lib/private/Files/Storage/Common.php - line 162: OC\Files\Storage\Common->isCreatable('')/home/nextcloud/public_html/lib/private/Files/Storage/Common.php - line 662: OC\Files\Storage\Common->getPermissions('')/home/nextcloud/public_html/lib/private/Files/Storage/Wrapper/Wrapper.php - line 581: OC\Files\Storage\Common->getMetaData('')/home/nextcloud/public_html/lib/private/Files/Storage/Wrapper/Availability.php - line 463: OC\Files\Storage\Wrapper\Wrapper->getMetaData('')/home/nextcloud/public_html/lib/private/Files/Storage/Wrapper/Wrapper.php - line 581: OC\Files\Storage\Wrapper\Availability->getMetaData('')/home/nextcloud/public_html/lib/private/Files/Cache/Scanner.php - line 112: OC\Files\Storage\Wrapper\Wrapper->getMetaData('')/home/nextcloud/public_html/lib/private/Files/Cache/Scanner.php - line 150: OC\Files\Cache\Scanner->getData('')/home/nextcloud/public_html/lib/private/Files/Cache/Scanner.php - line 336: OC\Files\Cache\Scanner->scanFile('', 3, -1, NULL, true)/home/nextcloud/public_html/lib/private/Files/View.php - line 1326: OC\Files\Cache\Scanner->scan('', false)/home/nextcloud/public_html/lib/private/Files/View.php - line 1369: OC\Files\View->getCacheEntry(Object(OCA\Files_Trashbin\Storage), '', 'ResFiles')/home/nextcloud/public_html/apps/dav/lib/Connector/Sabre/ObjectTree.php - line 157: OC\Files\View->getFileInfo('/rtn361/files/R...')/home/nextcloud/public_html/3rdparty/sabre/dav/lib/DAV/Server.php - line 967: OCA\DAV\Connector\Sabre\ObjectTree->getNodeForPath('ResFiles')/home/nextcloud/public_html/3rdparty/sabre/dav/lib/DAV/Server.php - line 1666: Sabre\DAV\Server->getPropertiesIteratorForPath('ResFiles', Array, 1)/home/nextcloud/public_html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 359: Sabre\DAV\Server->generateMultiStatus(Object(Generator), false)[internal function] Sabre\DAV\CorePlugin->httpPropFind(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/home/nextcloud/public_html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)/home/nextcloud/public_html/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method PROPFIND', Array)/home/nextcloud/public_html/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))/home/nextcloud/public_html/apps/dav/appinfo/v1/webdav.php - line 80: Sabre\DAV\Server->exec()/home/nextcloud/public_html/remote.php - line 164: require_once('/home/nextcloud...'){main}
-- | -- | --

**Comment by skjnldsv** [comment]
Still broken?
Sorry, our samba/external is quite overloaded and this issue is not in the priority list :(
