### ISSUE TITLE
Favorites in '...' menu looks wrong

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#7520]
Feel free to close this issue, if you think this was already discussed enough. I didn't saw any discussion about it so far, so I want to rise my concerns.

With Nextcloud 13 we moved favorites to the '...' menu. This is how it looks:

![favorites](https://user-images.githubusercontent.com/1589737/34002511-0ca0facc-e0f3-11e7-9319-4526906af53d.png)

Two thinks which confuses me the first time I saw it:

1. Why is it the only item with a color icon? This looks strange. I would suggest to use a monochrome icon like for all other actions as well

2. Why is it at the top? I don't think that this is the operation you want to do most of the time you open the menu. I think "Details" should continue to stay at the top.

cc @nextcloud/designers @jancborchardt

**Comment by skjnldsv** [comment]
Agree with both.

**Comment by jancborchardt** [comment]
I'm ok with moving it to the second position, after details.

The coloring was added to better discern the entries. Favorites have a clear color-coding, and I'm thinking of doing the same for Delete (dark red). In a list of 6 actions (possibly more depending which app injects stuff) this really helps do things quickly, and makes the interface more helpful & less bland.

**Comment by MariusBluem** [comment]
https://github.com/nextcloud/server/issues/7379

**Comment by jancborchardt** [comment]
@MariusBluem what's your point though? :) It's separate suggestions?

**Comment by skjnldsv** [comment]
Can we take a position here, it's an easy fix and will lower our issues count :)

**Comment by jancborchardt** [comment]
We had this for some time now and as favoriting is not used so often it’s really good in the menu as compared to outside. Also allows us to have the exact same menu entries in the right-click menu → Closing.
