### ISSUE TITLE
Upload existing file - conflicting file dialog not useable

### ISSUE THREAD

**Issue by jgrete** [nextcloud/server#7521]
### Steps to reproduce
1. Generate a file on the server.
2. Download this file, change it (not important). The filename must stay the same.
3. Upload to the same you've downloaded the file from

### Expected behaviour
A dialogbox appears telling about conflicting files. It is possible to check two options and choose which files to keep and go further on.

### Actual behaviour
first server with PHP 7...: behaviour as expected
second server with PHP 5.6 : dialogbox is not useable, i.e. you can not check checkboxes, you can not click anything. In fact the only option is, to click the browsers back button or reload the page.  

### Server configuration

**Operating system**: Linux OpenSUSE 42.3

**Web server: apache

**Database: mysql/mariadb

**PHP version:5.6/7.0 (see above)

**Nextcloud version:12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install: Updated from 12.0.3

**Where did you install Nextcloud from:nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
-- nothing --
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.5.2
  - admin_audit: 1.2.0
  - apporder: 0.4.1
  - bookmarks: 0.10.1
  - bruteforcesettings: 1.0.2
  - checksum: 0.3.5
  - circles: 0.13.6
  - comments: 1.2.0
  - dav: 1.3.0
  - delete_confirmation: true
  - drop_account: 0.0.6
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_automatedtagging: 1.2.2
  - files_clipboard: 0.6.4
  - files_downloadactivity: 1.1.1
  - files_external: 1.3.0
  - files_markdown: 2.0.1
  - files_pdfviewer: 1.1.1
  - files_reader: 1.0.4
  - files_retention: 1.1.2
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - groupfolders: 1.1.0
  - impersonate: 1.0.1
  - issuetemplate: 0.3.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - metadata: 0.6.0
  - nextcloud_announcements: 1.1
  - notes: 2.3.2
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - ownbackup: 17.5.0
  - password_policy: 1.2.2
  - polls: 0.8.0
  - previewgenerator: 1.0.7
  - provisioning_api: 1.2.0
  - qownnotesapi: 17.5.0
  - quota_warning: 1.1.1
  - ransomware_protection: 1.0.5
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - socialsharing_email: 1.0.1
  - spreed: 2.0.2
  - spreedme: 0.3.11
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_external: 0.4
  - user_usage_report: 1.0.1
  - workflowengine: 1.2.0
  - workin2gether: 0.9.6
Disabled:
  - admin_notifications
  - encryption
  - gallery
  - user_ldap

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "oxxxxxxxx4",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.xxxxxx.de",
            "19x.xx.xx.xxx",
            "localhost",
            "127.0.0.1",
            "192.168.253.134"
        ],
        "datadirectory": "\/srv\/oc_data",
        "overwrite.cli.url": "https:\/\/cloud.xxxxxxxx.de\/owncloud",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "dbname": "gxxxxxx_db",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbdriveroptions": {
            "1002": "SET wait_timeout = 28800"
        },
        "log_type": "owncloud",
        "logfile": "\/srv\/oc_data\/owncloud.log",
        "loglevel": 5,
        "syslog_tag": "Owncloud",
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "Europe\/Berlin",
        "cron_log": false,
        "log_rotate_size": 10485760,
        "installed": true,
        "maintenance": false,
        "theme": "gp3",
        "skeletondirectory": "",
        "mail_from_address": "oc.admin",
        "mail_smtpmode": "smtp",
        "mail_domain": "gxxxxxd.de",
        "default_language": "de_DE",
        "trashbin_retention_obligation": "auto, 30",
        "trashbin_auto_expire": true,
        "updatechecker": false,
        "enable_certificate_management": true,
        "htaccess.RewriteBase": "\/owncloud",
        "filelocking.enabled": true,
        "mail_smtphost": "xxxx.xxxxx.de",
        "mail_smtpport": "25",
        "updater.release.channel": "stable",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Epub",
            "OC\\Preview\\FB2",
            "OC\\Preview\\PDF",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007"
        ]
    }
}

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:no

**Are you using encryption:no

**Are you using an external user-backend, if yes which one:no

</details>

### Client configuration
**Browser:Firefox/Chromium

**Operating system:Linux/Windows

#### Web server error log
<details>
<summary>Web server error log</summary>

no relevant entries

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

no relevant entries
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```

a) The javascript console log
Insert your browser log here, this could for example include:
DEPRECATED: please use generatePreviewUrl() from an OCA.Files.FileList instance
merged-index.js:10098:4
File.lastModifiedDate sollte nicht mehr verwendet werden. Verwenden Sie File.lastModified stattdessen.
merged-template-prepend.js:734


b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
I don't see how the PHP version could affect the JS code in that matter. @danxuliu @ChristophWurst Do you have an idea here?

**Comment by jgrete** [comment]
Absolutely no idea. I just listed differences between a working and a not working instance I recognized as such. I'm neither a JS nor PHP programmer, so I could only report some facts.

**Comment by MorrisJobke** [comment]
@jgrete Could you provide a test instance/account on those two instances so we could have a look at the difference in the resulting HTML/JS?

**Comment by danxuliu** [comment]
Maybe a PHP 7 only code slipped somewhere, causing an internal error to be returned for certain request and that in turn causing a JavaScript error because a valid object was expected and it has an undefined value instead?

Anyway I could not reproduce it on PHP 5.6, so that is just wild guessing :-(

**Comment by jgrete** [comment]
Sorry, I'm late...
@MorrisJobke Yes I'll do that in a few hours (7..8pm). Could you provide me with an e-mail address so I can send you the URLs and account data (or any other not so publlic way :-) )?
I've attached a screenshot of the dialogbox. It is grayed and not useble (as I told above)
Regards
Juergen
![2018-01-09 10_25_16-test - dateien - gp-cloud](https://user-images.githubusercontent.com/14105933/34714156-d7205632-f528-11e7-9408-d15b100d60d4.png)

**Comment by jgrete** [comment]
@danxuliu Thank you for trying that. I wasn't aware of this issue before version 12.0.4 but I don't know wether it exists before.  Maybe it's an issue with other software on the VM, the different php versions are a wild guess on my side. I'm quite sure that we had no problem in older versions.

**Comment by MorrisJobke** [comment]
> @MorrisJobke Yes I'll do that in a few hours (7..8pm). Could you provide me with an e-mail address so I can send you the URLs and account data (or any other not so publlic way :-) )?

See my github profile 😉

**Comment by jgrete** [comment]
Are there any news 'bout this issue? I'm going to ugrade my private cloud to nextcloud rc1 on next weekend. If you need more time for looking into the issue I wouldn't do that of course (don't want to push :-) )
Regards
Juergen

**Comment by jgrete** [comment]
Why is the "need info" label still attached?? What kind of additional info do you need?

**Comment by MorrisJobke** [comment]
> Why is the "need info" label still attached?? What kind of additional info do you need?

Currently we haven't had time to look into this. I will re-evaluate once I have a free time slot. Thanks for your help.

**Comment by jgrete** [comment]
OK, thank you very much. Both accounts mentioned are still open. If there are any information I could deliver, please tell me. We've planned to update to 12.0.5 within a few weeks. Maybe things will change then.
Regards
Jürgen

**Comment by jgrete** [comment]
Ok, nothing happend since severeal weeks. I'm closing this issue. No success so far
