### ISSUE TITLE
after ldap configuration changed to remove groups, groups remain, invisible from the user manager but appear to users

### ISSUE THREAD

**Issue by ArnY** [nextcloud/server#7522]
### Steps to reproduce
1. Set up ldap authentication with groups (group filter + group base DN in the advanced settings, etc.)
2. Decide you didn't need the groups, remove the group filter, group base dn, etc. from the configuration. In the ldap/AD configuration form, the "Verify settings and count the groups" button says "0 groups found." The groups disappear as expected from the user manager and the users remain.

### Expected behaviour
Everything should be fine and life should be great. Ldap groups shouldn't appear when you type in their name in the sharing boxes

### Actual behaviour
Life sucks and ldap groups appears when you type their exact name, not when you type part of the name like users. 

 In the ldap configuration, I see that nextcloud fills the group base DN with the base DN if it's empty. No group are available in this DN, groups are outside of the configured base DN and user base DN.

New ldap groups don't show up, the remaining groups are remnants that should have been purged.

In the database:

```
MariaDB [cloudprod]> select * from oc_groups;
+-------+
| gid   |
+-------+
| admin |
+-------+
1 row in set (0.00 sec)

MariaDB [cloudprod]> select count(*) from oc_ldap_group_mapping;
+----------+
| count(*) |
+----------+
|     5427 |
+----------+
1 row in set (0.00 sec)

MariaDB [cloudprod]> select count(*) from oc_ldap_group_members;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)

```

### Server configuration

**Operating system**: Deban 9

**Web server:** apache 2.4

**Database:** mariadb 10.1.23 / Galera 3

**PHP version:** 7.0

**Nextcloud version:** (see Nextcloud admin page) 12.0.4 and 13 beta1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 12.0.3

**Where did you install Nextcloud from:** sources from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.5.2
  - apporder: 0.4.1
  - bruteforcesettings: 1.0.2
  - comments: 1.2.0
  - dav: 1.3.0
  - external: 2.0.3
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - impersonate: 1.0.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - quota_warning: 1.1.1
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - twofactor_backupcodes: 1.1.1
  - twofactor_totp: 1.3.1
  - twofactor_u2f: 1.4.0
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - systemtags
  - theming
  - user_external

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+-------------------------------------------------------------------------+
| Configuration                 |                                                                         |
+-------------------------------+-------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                       |
| hasPagedResultSupport         |                                                                         |
| homeFolderNamingRule          | attr:uid                                                                |
| lastJpegPhotoLookup           | 0                                                                       |
| ldapAgentName                 | cn=cloud,ou=authldap,dc=univ-nantes,dc=fr                               |
| ldapAgentPassword             | ***                                                                     |
| ldapAttributesForGroupSearch  | cn                                                                      |
| ldapAttributesForUserSearch   | mail;uid;gecos;sn                                                       |
| ldapBackupHost                |                                                                         |
| ldapBackupPort                |                                                                         |
| ldapBase                      | ou=users,ou=comptes,xxxxxxxxxxx                                |
| ldapBaseGroups                | ou=users,ou=comptes,xxxxxxxxxx                               |
| ldapBaseUsers                 | ou=users,ou=comptes,xxxxxxxxxxxx                                |
| ldapCacheTTL                  | 600                                                                     |
| ldapConfigurationActive       | 1                                                                       |
| ldapDefaultPPolicyDN          |                                                                         |
| ldapDynamicGroupMemberURL     |                                                                         |
| ldapEmailAttribute            | mail                                                                    |
| ldapExperiencedAdmin          | 1                                                                       |
| ldapExpertUUIDGroupAttr       |                                                                         |
| ldapExpertUUIDUserAttr        | uid                                                                     |
| ldapExpertUsernameAttr        | uid                                                                     |
| ldapGidNumber                 | gidNumber                                                               |
| ldapGroupDisplayName          | cn                                                                      |
| ldapGroupFilter               |                                                                         |
| ldapGroupFilterGroups         |                                                                         |
| ldapGroupFilterMode           | 0                                                                       |
| ldapGroupFilterObjectclass    |                                                                         |
| ldapGroupMemberAssocAttr      |                                                                         |
| ldapHost                      | ldaps://xxxxxxxxxxxxx                                   |
| ldapIgnoreNamingRules         |                                                                         |
| ldapLoginFilter               | (&(|(dynaEtat=N)(dynaEtat=D)(dynaEtat=R))(unCloudActif=TRUE)(uid=%uid)) |
| ldapLoginFilterAttributes     |                                                                         |
| ldapLoginFilterEmail          | 0                                                                       |
| ldapLoginFilterMode           | 0                                                                       |
| ldapLoginFilterUsername       | 1                                                                       |
| ldapNestedGroups              | 0                                                                       |
| ldapOverrideMainServer        |                                                                         |
| ldapPagingSize                | 500                                                                     |
| ldapPort                      | 636                                                                     |
| ldapQuotaAttribute            |                                                                         |
| ldapQuotaDefault              | 100G                                                                    |
| ldapTLS                       | 0                                                                       |
| ldapUserDisplayName           | displayName                                                             |
| ldapUserDisplayName2          | uid                                                                     |
| ldapUserFilter                | (&(|(dynaEtat=N)(dynaEtat=R)(dynaEtat=D))(unCloudActif=TRUE))           |
| ldapUserFilterGroups          |                                                                         |
| ldapUserFilterMode            | 0                                                                       |
| ldapUserFilterObjectclass     |                                                                         |
| ldapUuidGroupAttribute        | auto                                                                    |
| ldapUuidUserAttribute         | auto                                                                    |
| turnOffCertCheck              | 0                                                                       |
| turnOnPasswordChange          | 0                                                                       |
| useMemberOfToDetectMembership | 1                                                                       |
+-------------------------------+-------------------------------------------------------------------------+

```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
no errors.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
nothing to shw
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by blizzz** [comment]
> Life sucks 

sorry bout that :(

> and ldap groups appears when you type their exact name, not when you type part of the name like users.

where?

> In the ldap configuration, I see that nextcloud fills the group base DN with the base DN if it's empty. No group are available in this DN, groups are outside of the configured base DN and user base DN.

Yeah, don't worry about the DN, the filter is the crucial part. When no  filter is set,  groups aren't used. At least it should be like that :)

> New ldap groups don't show up, the remaining groups are remnants that should have been purged.

There is no clean up mechanism at this point, they'd just lie around. Would make sense add it of course. However, they should not be reused.

**Comment by ArnY** [comment]
> and ldap groups appears when you type their exact name, not when you type part of the name like users.

When sharing a file. In the contact search field. Typing the first characters doesn't trigger suggestions for groups, but as soon as you've typed the whole name, the group shows up.

> Yeah, don't worry about the DN, the filter is the crucial part. When no filter is set, groups aren't used. At least it should be like that :)

That's also what I thought, but actually they still show up. We ended up deleting them manually from the oc_ldap_group_mapping table. Users were complaining when sharing with those empty groups.

**Comment by blizzz** [comment]
> That's also what I thought, but actually they still show up. We ended up deleting them manually from the oc_ldap_group_mapping table. Users were complaining when sharing with those empty groups.

This won't clean up group shares, for instance, you'll have some dead entries lying around in the DB now. But, you can try to create and delete a local group with the same name, as workaround.

**Comment by ArnY** [comment]
> This won't clean up group shares, for instance, you'll have some dead entries lying around in the DB now. 

Actually, we caught the bug before opening the service to our users, only a few group share were made by our testing team and removed before we deleted the groups.

**Comment by blizzz** [comment]
@djgreg13 that's different to what @ArnY described. 
 
What was not kept on your move is the UUID of the entry.  Since the DN changed, this is by default used to look up users and groups when the previous DN is not available anymore, resulting in new users/groups when no matching UUID was found.

**Comment by djgreg13** [comment]
@blizzz the dn has not changed, the only change is the address of ldap server, we added a reverse proxy for aggregate twos AD, so the base DN of existing AD is the same. So all my groups disappear, but still visible in database and nextcloud reimport groups of my filter with _2 suffix.

Summary :
The original server has groups into this dn : ou=Groups,ou=Data,dc=domain,dc=local
On the new server, groups still have this dn ou=Groups,ou=Data,dc=domain,dc=local but the proxy aggregate users and group from a second ad with basedn dc=subdomain,dc=domain,dc=local. So i have adapted the group filter to keep only groups of first domain (ou=Groups,ou=Data,dc=domain,dc=local)
The groups of ou=Groups,ou=Data,dc=domain,dc=local are duplicated.

**Comment by blizzz** [comment]
Then compare the oc_ldap_group_mappings table and see what's listed there. Since entries are identified by their DN and their UUID if there was no match.

**Comment by djgreg13** [comment]
@blizzz thanks you, i have repaired the database, this is result of a bad mapping on the reverse of uuid field due to a ugly encoding from the ad :) i removed all groups ended by _2 and fixed the reverse and the original map reworks :)

**Comment by blizzz** [comment]
> ugly encoding from the ad

oh, yeah, that's awesome. not.

glad it helped to get it flying again!
