### ISSUE TITLE
user mentions in comments

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#753]
I see it split in those sub tasks:
- [x] 1. After posting a comment containing a valid username prepended by an @ (`@foobar`) the user (if existing & having access to the file) gets a notification about a comment where he is mentioned. This does not happen when editing comments. (This was worked on in https://github.com/owncloud/core/pull/24495) 
  **PR at https://github.com/nextcloud/server/pull/1449**
- [x] 2. When presenting the comment, the client should replace the username with the corresponding display name. The web UI should do this at first. In edit mode, the `@username` format is used (for now). 
  **PR at #1738**
- [ ] 3. When writing or editing a comment and typing an @ in the beginning of a word followed by another character an auto-complete is offered. It only includes users that have access to the file. Results are supposed to show up with a slight delay. For scaling reasons, it needs to be figured out whether all possible users are fetched in the background in advance, or on demand (like search dialog).
- [x] 4. The comments API is extended so that the Comment instance also offers a list of username-displayname combinations for the users mentioned in it. The list is empty, if not user is mentioned. This allows the client to replace the `@username` without looking up display names at the ownCloud server in seperate steps. I.e. the WebDAV resource returns this information just as well.
  **PR at #1738**

Further desired additions, might be out of scope for this stage:
- [ ] subscription system
- [ ] open sidebar and comments tab after clicking on notification, and …
- [ ] … also highlight the corresponding mention (cf. https://github.com/nextcloud/server/pull/1449#issuecomment-250115930)

**Comment by blizzz** [comment]
PR implementing the first part: https://github.com/nextcloud/server/pull/1449

**Comment by blizzz** [comment]
After talking to @LukasReschke, a subscription model would be totally fancy as well, so that notifications will happen on subsequent comments, without the need to mention users again. A step 5.

**Comment by MorrisJobke** [comment]
@blizzz Could I ask you to create a ticket for 12 that sums up what is left here? Thanks :)

**Comment by blizzz** [comment]
@MorrisJobke here we go: https://github.com/nextcloud/server/issues/2443

Closing this one here therefore.
