### ISSUE TITLE
13.0.0 Beta 3: Wrong paths in App CSS files with multiple app_paths

### ISSUE THREAD

**Issue by zauguin** [nextcloud/server#7534]
### Steps to reproduce
1. Open the Polls App without any existing polls (the same problem exists for example with the Mail App)

### Expected behaviour
In the middle of the screen, there is the icon of the polls app.

### Actual behaviour
There is no icon. There is no problem with the icon in the navigation bar on the top.

After looking at the CSS code, there is
```css
mask: url('../../apps/apps2/polls/css/../img/app-logo-polls.svg') no-repeat 50% 50%;
```
It should be
```css
mask: url('../../apps2/polls/css/../img/app-logo-polls.svg') no-repeat 50% 50%;
```

### Server configuration

Multiple app paths are set in the config.php:

<details>

```php
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/.../apps3',
      'url' => '/apps3',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/.../apps2',
      'url' => '/apps2',
      'writable' => true,
    ),
    2 =>
    array (
      'path' => '/.../nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
  ),
```

</details>

**Operating system**:
Arch Linux

**Web server:**
nginx

**Database:**
mariaDb

**PHP version:**
7.2.0

**Nextcloud version:** (see Nextcloud admin page)
13.0.0 Beta 3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 13.0.0 Beta 1, Version 12 was installed before.

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

**Comment by MorrisJobke** [comment]
cc @skjnldsv
