### ISSUE TITLE
The Delete action is not available in the file list header on narrow screens

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#7539]
When the window width is 688px or less and one or more files and/or folders are selected the _Delete_ action is not available in the file list header.

![files-header-delete-not-available](https://user-images.githubusercontent.com/26858233/34050037-bf580dce-e1b9-11e7-937c-2ab875f42782.png)

@nextcloud/designers

**Comment by Abijeet** [comment]
I'll take this up.
