### ISSUE TITLE
The file list is partially visible behind the header

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#7540]
When the files vertically overflow the list and the list is scrolled its contents are partially visible behind the file list header.

Origin:
![files-header-origin](https://user-images.githubusercontent.com/26858233/34050279-a1382d1e-e1ba-11e7-8fd3-1e587e52ef93.png)

Scrolled:
![files-header-scrolled](https://user-images.githubusercontent.com/26858233/34050295-a84569b4-e1ba-11e7-803e-8a24dc852f21.png)

@nextcloud/designers

**Comment by jancborchardt** [comment]
It is intended to be slightly visible, however only _very_ slightly with high opacity of the breadcrumb and multiselect bar. Kind of like in iOS - ideally we can use CSS3 blur effect even.
