### ISSUE TITLE
Emoji picker for comments, Talk, etc.

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#7541]
Chat services like Slack, Skype etc. offer an easy way to add emojis to messages by providing an emoji button, usually on the right side of the input field:
![](https://get.slack.help/hc/article_attachments/115014883106/emoji-menu.png)

I looked around a bit for plugins, and the only one which is nice (has good layout and search) and _doesn’t_ require React is https://github.com/mervick/emojionearea

(Related to "reactions" in the Talk app, where this should also be possible: https://github.com/nextcloud/spreed/issues/364)

 cc @nextcloud/javascript @nextcloud/talk

**Comment by blizzz** [comment]
Slack does? But useful in any case, until it's properly integrated into browsers by default.

**Comment by blizzz** [comment]
Actually the at.who plugin used for mentions can do the same, you only need to know the hotkey like on Github. Would keep the UI,lean, but perhaps less friendly

**Comment by jancborchardt** [comment]
@blizzz yes, Slack is where the screenshot is from. Emoji picker with icon is also present in Twitter and basically all messengers.

**Comment by blizzz** [comment]
Ha, never spotted it. Always pasted them :) but barely using Slack anyway, it's IRC on LSD.

**Comment by nickvergessen** [comment]
Just for the record, "Reactions" for Talk will be a limited and predefined set of reactions (similar to the reactions on github and the old spreed service).

But yeah, for chat and comments.

Would also be nice if we do it in a way, so it is easily reusable by apps (announcements, tasks and calendar for descriptions?, etc.)

**Comment by blizzz** [comment]
Reactions could be implemented as another type of comments, since we have the "verb" pattern. Verb could be just "reaction", the object the comment it is applied on. And have the emoji as message. 

This  would not require to extend the existing comments in a weird way. And actually this could go into a separate  app (the alternative would be server to be reusable).

**Comment by nickvergessen** [comment]
With

> Would also be nice if we do it in a way, so it is easily reusable by apps (announcements, tasks and calendar for descriptions?, etc.)

I ment the emoji picker with this. Let's not talk about other non-existing features in here, to keep it nice and simple 😉

**Comment by skjnldsv** [comment]
@nickvergessen this should go with the external modules discussion! :)

**Comment by skjnldsv** [comment]
@nickvergessen this should go with the external modules discussion! :)

**Comment by szaimen** [comment]
I think this is at least already implemented in Talk -> closing.

**Comment by nickvergessen** [comment]
https://nextcloud-vue-components.netlify.app/#/Components/Pickers?id=emojipicker
