### ISSUE TITLE
Folders named "logs" do not get synced with desktop client

### ISSUE THREAD

**Issue by Wrumm** [nextcloud/server#7542]
### Steps to reproduce
1. Create a folder named "logs" in any currently synced folder 
2. Put any file(s) into that new folder e.g. a create a new text file names "test.txt"
3. The error below in the sync client occurs

### Expected behaviour
Folders named "logs" are synced as all other folders between the desktop client and the server

### Actual behaviour
Content in a folder named "logs" is not synced with the error message on the client "server replied: Method not allowed" . 

### Server configuration

**Operating system**:
OpenSuse Leap 42.3
Docker 17.04.0-ce

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.1.2

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated over long period and several versions

**Where did you install Nextcloud from:**
Docker image from docker hub

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - activity: 2.5.2
  - bruteforcesettings: 1.0.2
  - calendar: 1.5.7
  - comments: 1.2.0
  - contacts: 2.0.1
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_accesscontrol: 1.2.5
  - files_external: 1.3.0
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - lookup_server_connector: 1.0.0
  - news: 11.0.5
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - tasks: 0.9.5
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - logreader
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

"system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "server",
            "192.168.178.25:28447",
            "192.168.178.25"
        ],
        "datadirectory": "\/var\/www\/html\/data",
        "overwrite.cli.url": "\/nextcloud",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "dbname": "owncloud_db",
        "dbhost": "mysql",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "nextcloud",
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "log_type": "syslog",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": 2,
        "syslog_tag": "nextcloud",
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "Europe\/Berlin",
        "log_query": false,
        "cron_log": false,
        "maintenance": false,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtptimeout": 30,
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "share_folder": "\/Shared",
        "theme": "",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "mysql.utf8mb4": true
    }

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Not involved here

**Operating system:**
Windows 10 1703

#### Web server error log
<details>
<summary>Web server error log</summary>

No log entries 

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

None at this point in time
Several entries of this below but that is a known php issue:
{PHP} Narrowing occurred during type inference. Please file a bug report on bugs.php.net at /var/www/html/lib/composer/composer/ClassLoader.php#444

</details>

#### Dekstop client
In the Window it is shown: "server replied: Method not allowed"
Client issue created and got the feedback:
"Method not allowed" is ALWAYS a server-side issue.

[https://github.com/owncloud/client/issues/6247#issuecomment-352004813](https://github.com/owncloud/client/issues/6247#issuecomment-352004813)

**Comment by brunt82** [comment]
Without a server or client log it is difficult to help here. I suppose it has nothing to do with Nextcloud but with your apache configuration... e.g. like https://github.com/owncloud/core/issues/8536

**Comment by Wrumm** [comment]
Thanks, the hints helped a lot. Was a clear admin error. 
I had an error in the configuration of the revers proxy.
