### ISSUE TITLE
No error message while user creation an password policy not matched

### ISSUE THREAD

**Issue by theLine** [nextcloud/server#7544]
### Steps to reproduce
1. Password Policy is set  
   *See Screenshot "screen-01-admin-password-policy"*
2. Create a user and enter a password in admin panel that does not match the password policy.  
   For example:  
   Username: test  
   Password: 1234
3. No error message will be shown  
   

### Expected behaviour
Display an error message that shows why the user can't be created

### Actual behaviour
No error message visible to the user in frontend.  
The AJAX request will return the status code 403, thus an error occurs while processing the actual error message.  
*See Screenshots "screen-02-javascript-error", "screen-03-network-error"*  
The actual error message will be shown when creating a user with `occ`  
*See Screenshot "screen-04-create-user-occ"*

### Server configuration

**Operating system**: docker container

**Web server:** nginx

**Database:** MariaDB 10.1.29

**PHP version:** 7.1.9

**Nextcloud version:** 12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:**
https://hub.docker.com/r/linuxserver/nextcloud

#### Browser log
<details>
<summary>Browser log</summary>

```
users.js?v=b3dafb6fac3a546cd674c7d3fc58a207-0:1050 Uncaught TypeError: Cannot read property 'message' of undefined
    at Object.<anonymous> (users.js?v=b3dafb6fac3a546cd674c7d3fc58a207-0:1050)
    at j (core.js?v=b3dafb6fac3a546cd674c7d3fc58a207-0:2)
    at Object.fireWith [as rejectWith] (core.js?v=b3dafb6fac3a546cd674c7d3fc58a207-0:2)
    at x (core.js?v=b3dafb6fac3a546cd674c7d3fc58a207-0:4)
    at XMLHttpRequest.<anonymous> (core.js?v=b3dafb6fac3a546cd674c7d3fc58a207-0:4)
```
</details>

#### Screenshots
<details>
<summary>Screenshots</summary>

**screen-01-admin-password-policy**
![screen-01-admin-password-policy](https://user-images.githubusercontent.com/2531075/34063225-f9ba43ce-e1f0-11e7-9ebe-b3790455086b.png)

**screen-02-javascript-error**
![screen-02-javascript-error](https://user-images.githubusercontent.com/2531075/34063226-f9d5eaac-e1f0-11e7-93e6-b58d4cb0e79c.png)

**screen-03-network-error**
![screen-03-network-error](https://user-images.githubusercontent.com/2531075/34063227-f9f35cea-e1f0-11e7-93d4-db21cc954daf.png)

**screen-04-create-user-occ**
![screen-04-create-user-occ](https://user-images.githubusercontent.com/2531075/34063228-fa0c737e-e1f0-11e7-9c78-a469b705e509.png)

</details>

**Comment by tflidd** [comment]
related? https://github.com/nextcloud/password_policy/issues/32

**Comment by MorrisJobke** [comment]
> related? nextcloud/password_policy#32

Seems to be like this. Please remove those config line and it should work.
