### ISSUE TITLE
[Clarification Request or Bug] Pretty Urls does not work for me

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/server#7547]
I followed the instructions on https://docs.nextcloud.com/server/12/admin_manual/installation/source_installation.html#pretty-urls but this does not work for me.

My system uses a subdomain like 

```https://cloud.example.com``` 

and an Apache vhost which then accesses the installation on

```/var/www/html/nextcloud```

My Apache documentroot is set directly to ```/var/www/html/nextcloud```.

So I coded

```
  'overwrite.cli.url' => 'https://cloud.example.com',
  'htaccess.RewriteBase' => '/',
```
in my ```config.php```.

Url are still like this:

```https://cloud.example.com/index.php/s/Ylg9a123xX4gUZ1```

I expected Urls like

```https://cloud.example.com/Ylg9a123xX4gUZ1```

Pls. can someone assist?

**Comment by tflidd** [comment]
Did you update your .htaccess file?

`sudo -u www-data php /var/www/nextcloud/occ maintenance:update:htaccess`

If it still does not work, I'd try to restart the webserver and clean the browser cache.

**Comment by Wikinaut** [comment]
I did all these steps already; will investigate further.

Additional information (also updated above):
My Apache documentroot is set directly to ```/var/www/html/nextcloud```.

**Comment by tflidd** [comment]
And your link should change into this
https://cloud.example.com/s/Ylg9a123xX4gUZ1

Did you try this link manually if it works?

**Comment by MorrisJobke** [comment]
This is better to be discussed in the forums: https://help.nextcloud.com

It works on many instances and looks like a setup issue.

Thanks
