### ISSUE TITLE
[NC13 Beta3] OC\Repair\NC11\CleanPreviewsBackgroundJob error

### ISSUE THREAD

**Issue by MichaIng** [nextcloud/server#7548]
### Steps to reproduce
1. Install a fresh Nextcloud
2. Upgrade to v13 Beta 3 via web updater
3. Configure system cron
4. Watch Nextcloud error log after first cron execution.

### Expected behaviour
Just debug logs of cron background job executions

### Actual behaviour
`Fatal cron Argument 5 passed to OC\Repair\NC11\CleanPreviewsBackgroundJob::__construct() must implement interface OCP\IUserManager, none given, called in /var/www/nextcloud/lib/private/Server.php on line 1102`

### Server configuration

**Operating system**: tested on Raspbian Stretch and Buster

**Machine**: VirtualBox VM

**Web server:** Apache 2.4.25 and 2.4.29

**Database:** MariaDB 10.1.26 and 10.1.29

**PHP version:** mod-php 7.0.19 and 7.0.26

**Nextcloud version:** 13.0.0 Beta 3

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from fresh Nextcloud 12.0.4

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/latest-12.zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
not integrity check errors
```
</details>

**List of activated apps:**
<details>
<summary>Apps list</summary>
```
Enabled:
  - activity: 2.6.1
  - dav: 1.4.5
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - twofactor_backupcodes: 1.2.3
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - comments
  - encryption
  - federation
  - files_external
  - files_pdfviewer
  - files_sharing
  - files_texteditor
  - files_trashbin
  - files_versions
  - files_videoplayer
  - firstrunwizard
  - password_policy
  - sharebymail
  - survey_client
  - systemtags
  - theming
  - updatenotification
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "*"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/localhost\/nextcloud",
        "dbtype": "mysql",
        "version": "13.0.0.8",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updater.release.channel": "beta",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 1
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Fatal | cron | Argument 5 passed to OC\Repair\NC11\CleanPreviewsBackgroundJob::__construct() must implement interface OCP\IUserManager, none given, called in /var/www/nextcloud/lib/private/Server.php on line 1102
-- | -- | --
```
</details>

**Comment by enoch85** [comment]
Related: #7309
