### ISSUE TITLE
Verifiable releases based on strong cryptography

### ISSUE THREAD

**Issue by ypid** [nextcloud/server#755]
Could you please consider doing the following steps to improve authenticity and security for the users and the development process of NextCloud:
- [x] Sign git tags, GitHub also supports this and shows nice "Verified" badges then. Example: https://github.com/opening-hours/opening_hours.js/releases
    This allows devs and users to ensure that no one tampered with the release as the platform where you host your source code is not under your control (and even if it where …)
    According to your [last release](https://github.com/nextcloud/server/releases/tag/v9.0.53) you are already doing that :+1:
- [x] Upload the release public key(s) on https://sks-keyservers.net/ Currently only found on: https://nextcloud.com/nextcloud.asc
    This ensures that the public keys are available for everyone
- [ ] Mention `gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 28806A878AE423A28372792ED75899B9A724937A` on the website instead of downloading both files from the same origin.
- Additional for the developers consider to signed and verify git commits (a few devs are already doing this :+1:)

Related to: https://github.com/nextcloud/vm/issues/11
Related to: https://github.com/owncloud/core/issues/25710

Refs:
- https://github.com/debops/ansible-owncloud/pull/44#discussion_r73707876

**Comment by icewind1991** [comment]
cc @LukasReschke

**Comment by ypid** [comment]
Just saw that in https://github.com/nextcloud/docker that signature checking is done following best practices by using `gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 28806A878AE423A28372792ED75899B9A724937A` Very nice work gentleman :+1:

**Comment by MorrisJobke** [comment]
> Mention gpg --keyserver ha.pool.sks-keyservers.net --recv-keys 28806A878AE423A28372792ED75899B9A724937A on the website instead of downloading both files from the same origin.

@jospoortvliet Could you add this to the download page?

@LukasReschke Does that make sense?

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by jospoortvliet** [comment]
final piece fixed in https://github.com/nextcloud/nextcloud.com/commit/4e18c7b04a80457efd1806a61c7b81c328fd5a97
