### ISSUE TITLE
end_to_end_encryption app not loading

### ISSUE THREAD

**Issue by srtate** [nextcloud/server#7551]
### Steps to reproduce
1. Make a fresh install of 13.0.0beta3
2. Go into the Apps settings (Files category)
3. Notice screenshot image doesn't load for end_to_end_encryption
4. Try to Enable anyway...

### Expected behaviour
App should install

### Actual behaviour
The request for the screenshot returns "File not found" and trying to enable the app anyway results in a message of "Could not download app end_to_end_encryption"

For the screenshot, the URL embedded into the request (pointing to the screenshot on github) is correct, and works directly, but does not work when going through usercontent.apps.nextcloud.com

### Server configuration

**Operating system**:
Ubuntu 16.04.3

**Web server:**
apache 2.4.18-2

**Database:**
MySQL

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
13.0.0beta3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/prereleases/

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>
No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
cc @schiessle

**Comment by rullzer** [comment]
I just tested this. I can install the app from the appstore just fine... @srtate can you test again?

**Comment by srtate** [comment]
The behavior is different now. The app does install, but it still isn't loading the app image from the app store. That's a huge improvement (installing the app), so this problem doesn't affect functionality. Still an issue though. Screenshot:

![screenshot from 2017-12-19 17-31-13](https://user-images.githubusercontent.com/10100502/34182258-7f146000-e4e3-11e7-92cb-6eb189755519.png)

**Comment by rullzer** [comment]
Mmmm that seems to be an issue with the appstore. Lets debug that

**Comment by rullzer** [comment]
@BernhardPosselt seems that https://usercontent.apps.nextcloud.com/aHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL25leHRjbG91ZC9lbmRfdG9fZW5kX2VuY3J5cHRpb24vbWFzdGVyL3NjcmVlbnNob3RzL2UyZWUtZmlsZWxpc3RpbmcucG5n returns a 404... while (base64 decoded) https://raw.githubusercontent.com/nextcloud/end_to_end_encryption/master/screenshots/e2ee-filelisting.png is valid...

**Comment by rullzer** [comment]
Fix for the proxy in https://github.com/nextcloud/usercontent.apps.nextcloud.com/pull/1
