### ISSUE TITLE
Upgrade to 12.0.4 failed 

### ISSUE THREAD

**Issue by svn-webmaster** [nextcloud/server#7552]
Hi,

I was trying to upgrade nextcloud from 12.0.3.3 to 12.0.4. The upgrade was successfully up to the following issue during the last steps in the web-updater:

`Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_appconfig` (`appid`,`configkey`,`configvalue`) SELECT ?,?,? FROM `oc_appconfig` WHERE `appid` = ? AND `configkey` = ? HAVING COUNT(*) = 0' with params ["core", "oc.integritycheck.checker", "[]", "core", "oc.integritycheck.checker"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
Detaillierte Protokollmeldungen
Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Das Datenbankschema wird aktualisiert
Datenbank aktualisiert
Suche nach einer Aktualisierung für die App "activity" im App-Store
App-Store auf Aktualalisierung für die App "activity" geprüft
Suche nach einer Aktualisierung für die App "bruteforcesettings" im App-Store
Aktualisiere die App "bruteforcesettings" aus dem App-Store
App-Store auf Aktualalisierung für die App "bruteforcesettings" geprüft
Suche nach einer Aktualisierung für die App "comments" im App-Store
App-Store auf Aktualalisierung für die App "comments" geprüft
Suche nach einer Aktualisierung für die App "dav" im App-Store
App-Store auf Aktualalisierung für die App "dav" geprüft
Suche nach einer Aktualisierung für die App "external" im App-Store
App-Store auf Aktualalisierung für die App "external" geprüft
Suche nach einer Aktualisierung für die App "federatedfilesharing" im App-Store
App-Store auf Aktualalisierung für die App "federatedfilesharing" geprüft
Suche nach einer Aktualisierung für die App "federation" im App-Store
App-Store auf Aktualalisierung für die App "federation" geprüft
Suche nach einer Aktualisierung für die App "files" im App-Store
App-Store auf Aktualalisierung für die App "files" geprüft
Suche nach einer Aktualisierung für die App "files_pdfviewer" im App-Store
App-Store auf Aktualalisierung für die App "files_pdfviewer" geprüft
Suche nach einer Aktualisierung für die App "files_sharing" im App-Store
App-Store auf Aktualalisierung für die App "files_sharing" geprüft
Suche nach einer Aktualisierung für die App "files_texteditor" im App-Store
App-Store auf Aktualalisierung für die App "files_texteditor" geprüft
Suche nach einer Aktualisierung für die App "files_trashbin" im App-Store
App-Store auf Aktualalisierung für die App "files_trashbin" geprüft
Suche nach einer Aktualisierung für die App "files_versions" im App-Store
App-Store auf Aktualalisierung für die App "files_versions" geprüft
Suche nach einer Aktualisierung für die App "files_videoplayer" im App-Store
App-Store auf Aktualalisierung für die App "files_videoplayer" geprüft
Suche nach einer Aktualisierung für die App "firstrunwizard" im App-Store
App-Store auf Aktualalisierung für die App "firstrunwizard" geprüft
Suche nach einer Aktualisierung für die App "gallery" im App-Store
App-Store auf Aktualalisierung für die App "gallery" geprüft
Suche nach einer Aktualisierung für die App "logreader" im App-Store
App-Store auf Aktualalisierung für die App "logreader" geprüft
Suche nach einer Aktualisierung für die App "lookup_server_connector" im App-Store
App-Store auf Aktualalisierung für die App "lookup_server_connector" geprüft
Suche nach einer Aktualisierung für die App "nextcloud_announcements" im App-Store
App-Store auf Aktualalisierung für die App "nextcloud_announcements" geprüft
Suche nach einer Aktualisierung für die App "notifications" im App-Store
App-Store auf Aktualalisierung für die App "notifications" geprüft
Suche nach einer Aktualisierung für die App "oauth2" im App-Store
App-Store auf Aktualalisierung für die App "oauth2" geprüft
Suche nach einer Aktualisierung für die App "password_policy" im App-Store
App-Store auf Aktualalisierung für die App "password_policy" geprüft
Suche nach einer Aktualisierung für die App "provisioning_api" im App-Store
App-Store auf Aktualalisierung für die App "provisioning_api" geprüft
Suche nach einer Aktualisierung für die App "serverinfo" im App-Store
App-Store auf Aktualalisierung für die App "serverinfo" geprüft
Suche nach einer Aktualisierung für die App "sharebymail" im App-Store
App-Store auf Aktualalisierung für die App "sharebymail" geprüft
Suche nach einer Aktualisierung für die App "survey_client" im App-Store
App-Store auf Aktualalisierung für die App "survey_client" geprüft
Suche nach einer Aktualisierung für die App "systemtags" im App-Store
App-Store auf Aktualalisierung für die App "systemtags" geprüft
Suche nach einer Aktualisierung für die App "theming" im App-Store
App-Store auf Aktualalisierung für die App "theming" geprüft
Suche nach einer Aktualisierung für die App "twofactor_backupcodes" im App-Store
App-Store auf Aktualalisierung für die App "twofactor_backupcodes" geprüft
Suche nach einer Aktualisierung für die App "updatenotification" im App-Store
App-Store auf Aktualalisierung für die App "updatenotification" geprüft
Suche nach einer Aktualisierung für die App "workflowengine" im App-Store
App-Store auf Aktualalisierung für die App "workflowengine" geprüft
Code-Integrität wird überprüft
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_appconfig` (`appid`,`configkey`,`configvalue`) SELECT ?,?,? FROM `oc_appconfig` WHERE `appid` = ? AND `configkey` = ? HAVING COUNT(*) = 0' with params ["core", "oc.integritycheck.checker", "[]", "core", "oc.integritycheck.checker"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
Das Update ist fehlgeschlagen. Bitte melde dieses Problem an die Nextcloud Community.`

**Comment by MorrisJobke** [comment]
> 2006 MySQL server has gone away

Your MySQL server has gone away. Without the DB reachable we can't do much. Please make sure that the DB is running and reachable and try the update again.
