### ISSUE TITLE
Limit external storage usage to groups

### ISSUE THREAD

**Issue by realies** [nextcloud/server#7559]
Would it be possible to introduce the ability to limit external storage usage to certain user groups?

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by ChristophWurst** [comment]
I'm closing this ticket because it hasn't received any updates in a long time. If this is still relevant, feel free to re-open or file a new ticket.

Thank you.

**Comment by Fregf** [comment]
Bug should be reopened because functionality is still missing.

I would also like to have this.
