### ISSUE TITLE
[occ] Hide "not installed" info on "occ maintenance:install"

### ISSUE THREAD

**Issue by MichaIng** [nextcloud/server#7563]
It's just a minor, but users might be confused, if during e.g. installation scripts the message `Nextcloud is not installed - only a limited number of commands are available` appears, where it actually should be/have been installed.

The message makes sense, if occ runs as something else than installation command, but on `occ maintenance:install ...` this could be hidden.

**Comment by MorrisJobke** [comment]
Implemented in #7939
