### ISSUE TITLE
Warning: Narrowing occurred during type inference. Please file a bug report on bugs.php.net in /home/kmccoy42/public_html/plazafitnessperformance.com/wp-content/plugins/LayerSlider/layerslider.php on line 64 I am getting this issue on my website which was recently moved to a new server. How can i fix this issue ??

### ISSUE THREAD

**Issue by haroonahmad194** [nextcloud/server#7565]
Warning: Narrowing occurred during type inference. Please file a bug report on bugs.php.net in /home/kmccoy42/public_html/plazafitnessperformance.com/wp-content/plugins/LayerSlider/layerslider.php on line 64
I am getting this issue on my website which was recently moved to a new server. How can i fix this issue ??

**Comment by rullzer** [comment]
This will be fixed with the next release of php.
Also ti seems this is not a nextcloud issue here.
