### ISSUE TITLE
Create a folder and share link programatically

### ISSUE THREAD

**Issue by NeoJones** [nextcloud/server#7571]
Hi,
I uploaded and installed nextcloud on my subdomain. Iam the owner of the domains.
If I would like to **create a new folder and share this folder** (to public with a url), I can do this in nextcloud directly via mouse clicks - no problem.
So is it possible to make that programatically with php? If yes, wich steps must i do?

For example:
1. create a folder (mkdir)
2. register that folder somewhere...?
3. create a public link for sharing that folder...?
4. ...?

I hope you can help me. Sorry for my bad english.
Best regards

**Comment by blizzz** [comment]
Please open a thread on the forums https://help.nextcloud.com, which is the more appropriate place for questions like this. Thanks!
