### ISSUE TITLE
NC13b3 regression: Theming glitch with Logo

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#7575]
### Steps to reproduce
1. Have 12.0.4 themed, with Logo, like
   https://datenschutz-individuell.de/cloud/index.php/apps/theming/logo?v=7   
![grafik](https://user-images.githubusercontent.com/8425483/34159710-71bf7e8a-e4ca-11e7-9a43-ec0f41051cd8.png)

2. Share a folder by link, protect it with a password, like
   https://datenschutz-individuell.de/cloud/index.php/s/KSitgWbdLfj2BXo
3. Logo is double/overlayed, see Screenshot
![grafik](https://user-images.githubusercontent.com/8425483/34159609-25f2278c-e4ca-11e7-8efd-962bcbeb2953.png)

### Expected behaviour
Logo should be displayed correctly (once).

### Actual behaviour
Logo is displayed incorrectly (overlayed, twice).

### Server configuration
**Operating system**: Debian Stretch (up to date)
**Web server:** Apache 2.4.10
**Database:** MySQL 5.5.58
**PHP version:** 5.6.30

**Nextcloud version:** 13.0.0 Beta 3
**Updated from an older Nextcloud/ownCloud or fresh install:** Upgraded from 12.0.4
**Where did you install Nextcloud from:** admin page / installer
**Signing status:** no errors upon signing: http://example.com/index.php/settings/integrity/failed reports "No errors have been found."

**List of activated apps:** irrelevant?!
**Nextcloud configuration:**
<details>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto,90",
        "versions_retention_obligation": "90,auto",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "datenschutz-individuell.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/datenschutz-individuell.de\/cloud",
        "dbtype": "mysql",
        "version": "13.0.0.8",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": "calendar",
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "updater.release.channel": "beta",
        "mail_smtpauthtype": "LOGIN"
    }
}
</details>

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 57 / Chrome 63
**Operating system:** W10

#### Browser log: No entry in Firefox browser console.

**Comment by blizzz** [comment]
@nextcloud/theming

**Comment by MorrisJobke** [comment]
This is because there is a background image and an `<img>` tag.

**Comment by MorrisJobke** [comment]
Also the CSS looks like it duplicates stuff.
![bildschirmfoto 2017-12-19 um 15 23 45](https://user-images.githubusercontent.com/245432/34161336-a1642af4-e4d0-11e7-9e17-23ad4e8da16f.png)

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers for the HTML/CSS

**Comment by pixelipo** [comment]
Looks rather like a @nextcloud/theming issue

**Comment by pixelipo** [comment]
While testing this I found out that the default logo is not loaded:
![image](https://user-images.githubusercontent.com/4129927/34164618-4cb15040-e4da-11e7-94cb-dbb0b23063f5.png)
because the svg image path in CSS is not correct...

**Comment by juliushaertl** [comment]
We also use a img tag on the login page to make sure the logo is scaled nicely when it is not in landscape format: https://github.com/nextcloud/server/pull/4632/files#diff-20abc3ec8914f60360246ff607542301R43 I guess we should adapt that to the files_sharing public page as well.
