### ISSUE TITLE
RFE: Limit visibility of users, e.g. to those users that belong to the same group or circle

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#7579]
### Steps to reproduce
1. Install Nextcloud, add some users that belong to different groups, like different customers
2. Use any share or communication feature, ALL users present in the SERVER are shown to any user

### Expected behaviour
I'd like to be able to limit the other NC users presented to a user, e.g. for shares I create for different customers. This would also be nice in a NC for private use if one adds friends and family users that do not know each other.

### Actual behaviour
Any user that has a login is available in the list, e.g. when sharing a file, and in the "Contact list".

**Comment by nursoda** [comment]
I consider this a privacy issue. (I add this since there are quite some NC blog entries on GDPR.)

**Comment by nursoda** [comment]
I admit that there ARE cases though where one sets up different groups to enable delegated administration but one wants to share between these groups. So the question is HOW to implement this limitation. One way could be a global switch. If then one user wants to share with or contact a member of another group, this would need to be handled "as external user". I don't know if that's feasible at all.

**Comment by MorrisJobke** [comment]
This is possible: you could limit the autocomplete for sharing to the groups a user is in. This can be found in the sharing section of the admin settings. Just enable it and the users only get the list of autocomplete for people in the same groups.

You could also disable the autocomplete completely there.

**Comment by nursoda** [comment]
Thanks, I'll try. And sorry for not having found this myself.

**Comment by MorrisJobke** [comment]
> Thanks, I'll try. And sorry for not having found this myself.

Don't worry :)

**Comment by nursoda** [comment]
I played a bit with autocomplete FOR SHARING off, and it does NOT match my need at all: I still can see all users in the contacts list.

What I want to avoid is to set up (and maintain) a cloud for all my customers.

One of my customers uses NC to share documents with suppliers, customers, in internal projects with partners. All of theses guys don't know each other, and should NOT see each other AT ALL. In such cases, it's NOT an option to set up 3,17, or 192 NC instances!

I see the other case, too, but I consider this a typical case where NC is used in companies today.

Please reopen this bug for discussion.

**Comment by MorrisJobke** [comment]
> I played a bit with autocomplete FOR SHARING off, and it does NOT match my need at all: I still can see all users in the contacts list.

It should be fixed in 12.0.4 do you run this already?

**Comment by nursoda** [comment]
I did, but I migrated all instances to 13b3 already ... and it does NOT work there! Regression?
Even if it does, my remark remains that I consider this rather a workaround.

**Comment by MorrisJobke** [comment]
> Therefore I consider switching autocomplete off completely rather a workaround. But OK, it's there, I'll use it. Thanks!

This is also possible. Just use the other setting to disable autocomplete.

The setting is called "Allow username autocompletion in share dialog. If this is disabled the full username or email address needs to be entered."

Then the users are not visible anymore:

Before
![bildschirmfoto 2017-12-19 um 17 22 53](https://user-images.githubusercontent.com/245432/34167203-58ee8344-e4e1-11e7-8ad6-225f4e1c7df8.png)

After
![bildschirmfoto 2017-12-19 um 17 22 47](https://user-images.githubusercontent.com/245432/34167202-58ce25c2-e4e1-11e7-9705-b8a27f12a267.png)

**Comment by nursoda** [comment]
Thanks, got it. I can use that. However, it's not what I think would suit the usecase: When sharing a file or folder, users from one customer would either see nothing and need to guess usernames (or use email addresses -> external links?) or see the names of all users registered, no matter whether they are in teir group or another. So that settings don't fulfil this usecase, do they?

**Comment by funkytraffic** [comment]
See also #5107
