### ISSUE TITLE
drop old calendar and contacts tables

### ISSUE THREAD

**Issue by JSoko** [nextcloud/server#758]
With ownCloud 9.0 contacts and calendar data were migrated over to the new core tables.
As far as I can see following tables should be dropped while upting to ownCloud 9.1:
_clndr_calendars, clndr_objects, clndr_share_event, clndr_share_calendar, clndr_repeat, contacts_addressbooks, contacts_cards_
Will these tables be dropped by upgrading to Nextcloud 10? Shall they be dropped manual?
Did I miss something?

see also: 
https://github.com/owncloud/core/issues/21889
https://github.com/owncloud/core/pull/24166

**Comment by phsc** [comment]
Nextcloud 10 is based on Owncloud 9.1 and therefore these tables are already part of the repair step during the migration. See the following source: [DropOldTables.php](https://github.com/nextcloud/server/blob/master/lib/private/Repair/DropOldTables.php)

**Comment by MorrisJobke** [comment]
Yes. This will be in Nextcloud 10.
