### ISSUE TITLE
Request: Please apply for the IFTTT Platform

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#7584]
[IFTTT platform is available for projects with a public API and Oauth2, allowing them to communication with other pieces of software using conditional statements](https://platform.ifttt.com/apply?level=partner).  I politely asked for more info on how Nextcloud could actually be integrated...  I was told someone from the Nextcloud organization would need to contact IFTTT through this site to get the process started.

**Comment by MorrisJobke** [comment]
> IFTTT platform is available for projects with a public API and Oauth2, allowing them to communication with other pieces of software using conditional statements. I politely asked for more info on how Nextcloud could actually be integrated... I was told someone from the Nextcloud organization would need to contact IFTTT through this site to get the process started.

I guess this needs to be done by each instance of Nextcloud independently, because each one has a different API endpoint. Also this should be implemented as an app and not in the server itself.

Thanks for the feedback anyways and we are happy to assist if help is needed to get this as a feature.

I will close this in here, because this is the bug tracker of the server core and the integration should be implemented as a dedicated app.

**Comment by sunjam** [comment]
@MorrisJobke 
Hi, I understand this does not fit under server core, but would you be willing to contact IFTTT and find more information to share on what is needed for further development... I'm happy to do it, but I'm just a user.  [Discussion on this integration can be found on the Nextcloud Help page here](https://github.com/joeplus/nextcloud-ifttt) and [a rough github page for possible implementation can be found here.](https://github.com/joeplus/nextcloud-ifttt)

**Comment by MorrisJobke** [comment]
> Discussion on this integration can be found on the Nextcloud Help page here and a rough github page for possible implementation can be found here.

Both of your links point to a app repo, but I don't know why we should contact IFTTT, somebody needs to dig into how IFTTT works and if there are specific problems then we could help. I don't see how blindly apply for something that does not exist yet would help here.

**Comment by Escubaer** [comment]
Yes, this would be a great feature. I am politely begging the Nextcloud developers to apply. And where do we track this if not here? Please don't close, but show us a proper place for the discussion!

**Comment by pixelipo** [comment]
IFTTT works more or less by connecting to one API to another one. So basically, as soon as certain NC component contains an API, it is compatible with IFTTT. 
I think this most NC apps are at least planning to introduce an API, but most of them don't have it.

**Comment by Spartachetto** [comment]
@MorrisJobke, I get the reasons for which you closed this issue yet, if you deem it meaningful, this could become an overview issue to track the development of the different APIs that are developed or will be developed in Nextcloud (server AND apps).

This could help who is interested in IFTTT or in the open-source alternatives Node-Red, Huginn, Trigger Happy or Beehive

**Comment by sunjam** [comment]
For reference, here is the [open integration issue 272 on Trigger Happy](
https://github.com/foxmask/django-th/issues/272) for Nextcloud and Owncloud.
