### ISSUE TITLE
Rename tag textbox too big

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/server#7586]
### Steps to reproduce
1. Add a tag to a file
2. Edit the tag from the tag auto complete

### Expected behaviour
The textbox should fit into the autocomplete selection box.

### Actual behaviour
The textbox is too big for the  autocomplete selection box.

### Server configuration

**Nextcloud version:** Nc 13 beta 3

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** from git

### Client configuration
**Browser:** FF 57

**Operating system:** Windows 10

![tags](https://user-images.githubusercontent.com/1869584/34215404-866b3d2a-e5a5-11e7-95ff-315bc99b1130.png)

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
@splitt3r this should be a simple CSS fix by adjusting the width or margin. Do you want to open a pull request? :)

**Comment by splitt3r** [comment]
Ok, will have a look at it.
