### ISSUE TITLE
Sharing link causes encyrption module not enabled message. its never been enabled. 

### ISSUE THREAD

**Issue by twotwenty** [nextcloud/server#759]
Hi,
I switched from owncloud 9 to nextcloud 9 and the upgrade worked flawlessly. 
but now when I try to share files or folders via link sharing ("Link teilen" checkbox) an error message pops up: https://cloud.0010.ca/index.php/s/l4Tzh2EdXAtLcNv

How I think I got to my issue.
1. check off encryption in admin area of owncloud 8 but never enable the module 
2. cannot disable encryption even though nothing has yet been encypted 

here is a link to a discussion about this issue that brought me here
https://help.nextcloud.com/t/error-when-i-share-files-folders-via-link/1658

I'll attempt to reproduce this issue pure in nextcloud 9

**Comment by blizzz** [comment]
@twotwenty i get an access denied error on that clipular page

@nextcloud/encryption

**Comment by twotwenty** [comment]
https://cloud.0010.ca/index.php/s/l4Tzh2EdXAtLcNv

**Comment by LukasReschke** [comment]
cc @schiessle

**Comment by schiessle** [comment]
You enabled encryption in the admin settings, so Nextcloud assume that you want to encrypt your files. The admin settings warns you that this is a one-way setting. 

You now have to disable it manually:

````
UPDATE oc_appconfig set configvalue='no' where configkey='encryption_enabled' and appid='core';
````

**Comment by schiessle** [comment]
@twotwenty please let us know if disabling encryption on the database level solved the problem.

**Comment by twotwenty** [comment]
Yes this has corrected my issue thank you.

**Comment by jknockaert** [comment]
@LukasReschke What will we do with this one? We could just close it, but I remember that even as a contributor to the encryption app I was puzzled by this setup. I guess there's an opportunity to improve the admin user interface.

**Comment by blizzz** [comment]
@schiessle shouldn't there be a GUI-possibility to turn it off, possibly?

**Comment by MorrisJobke** [comment]
> @LukasReschke What will we do with this one? We could just close it, but I remember that even as a contributor to the encryption app I was puzzled by this setup. I guess there's an opportunity to improve the admin user interface.

There is no easy way to turn it off (or to know when there didn't happen any encryption yet, so it's still possible) - so we added this huge red warning:

<img width="998" alt="bildschirmfoto 2017-01-24 um 20 58 11" src="https://cloud.githubusercontent.com/assets/245432/22276240/f49bbdce-e277-11e6-8d20-7eeb2ffb46ff.png">


We discussed this quite often and it's super hard to detect if turning off is still easily possible and not run into data that is still encrpted but can't be decrypted because the encryption is disabled.

That said: I will close this ticket - the behaviour is the best we could come up with :(

**Comment by jknockaert** [comment]
@MorrisJobke I was more thinking of integrating the multi-step enabling approach to encryption. It should be either "on" or "off". The current approach where you can turn it "on" but then still don't have encryption doesn't make sense from a user point of view. And it is especially confusing as the separate steps are not grouped together on the same page. Or do I miss out on something here?
