### ISSUE TITLE
Background job doesn't run: Enhance error message, add trouble shooting procedure

### ISSUE THREAD

**Issue by sushidave** [nextcloud/server#7596]
Hey,

As the News app doesn't update its feeds on two Nextcloud 12 installations I checked the admin pages and noticed this message:

**"Letzte Aufgaben-Ausführung lief Vor 5 Monaten. Etwas scheint falsch zu sein."** i

It seems to be a background job issue and not something specific to the News app. 

Then clicked the "i" next to it and was taken to "Defining Background Jobs" of the documentation which informs on the type of jobs but doesn't help to solve the issue - it's a dead end. So I suggest to enhance the error message with more specific information and with a reference to a trouble shooting guide.

What's the procedure to solve such a background job issue?

 
### Steps to reproduce
see above

### Expected behaviour
Cron should run or the error message should be more specific and refering to trouble shooting procedure.

### Actual behaviour
- Cron seems to have an issue.
- Admin page shows an unspecific error.
- No trouble shooting procedure

### Server configuration

**Operating system**:
Linux --- 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 

**Web server:**

**Database:**
mysql 10.1.29

**PHP version:**
5.6.32

**Nextcloud version:** (see Nextcloud admin page)
12.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Activity
Auditing / Logging
Collaborative tags
Comments
Deleted files
Federation
File sharing
First run wizard
Gallery
Log reader
Monitoring
Nextcloud announcements
Notifications
Password policy
PDF viewer
Share by mail
Text editor
Theming
Update notification
Usage survey
Versions
Video player
AppOrder
Audio Player
Bookmarks
Brute-force-settings
Calendar
Contacts
Deck
Keeweb
Mail
Music
News
Radio
Tasks
Video calls
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => '***',
  'passwordsalt' => '***',
  'secret' => '***',
  'trusted_domains' => 
  array (
    0 => 'cloud.domain.tld',
  ),
  'datadirectory' => '/home/httpd/vhosts/domain.tld/data',
  'dbtype' => 'mysql',
  'version' => '12.0.3.3',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '***',
  'dbpassword' => '***',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 2,
  'maintenance' => false,
  'htaccess.RewriteBase' => '/',
  'forcessl' => true,
  'memcache.local' => '\\OC\\Memcache\\ArrayCache',
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => '***',
  'mail_smtpport' => '465',
  'mail_smtpsecure' => 'ssl',
  'mail_from_address' => 'nextcloud',
  'mail_domain' => '***',
  'overwrite.cli.url' => 'https://cloud.domain.tld:443',
  'overwriteprotocol' => 'https',
  'theme' => '',
  'mail_smtpauth' => 1,
  'mail_smtpname' => '***',
  'mail_smtppassword' => '***',
  'updater.secret' => '***',
);
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Warning: mod_fcgid: stderr: PHP Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"WjuWjg244V14P1W73AMtQwAAABY","level":3,"time":"2017-12-21T11:10:06+00:00","remoteAddr":"185.110.91.143","user":"abc","app":"PHP","method":"POST","url":"\/apps\/deck\/cards","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","userAgent":"Mozilla\/5.0 (Windows NT 6.1; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.3.3"}
{"reqId":"WjuaB6lKcwCptw4oLMDCGwAAAAM","level":3,"time":"2017-12-21T11:24:55+00:00","remoteAddr":"185.110.91.143","user":"def","app":"PHP","method":"POST","url":"\/heartbeat","message":"Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php:\/\/input stream instead. at Unknown#0","userAgent":"Mozilla\/5.0 (Windows NT 6.1; WOW64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.3.3"}
```
</details>

**Comment by gratuxri** [comment]
Hello, does this exist nowaday with uptodate nextcloud, php and mysql, if not, please close this issue.

**Comment by sushidave** [comment]
@gratuxri 
Hey, thanks for asking. 
I just rechecked the upgraded installations. They are now on version 17 and the message doesn't appear. Thanks!
