### ISSUE TITLE
Setup translation system

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#76]
Workflow should be:

- [x] Initial import of the ownCloud translation
- Custom languages get translated there
- [x] Translations are fetched from there and will be put into git automatically

Also add back https://github.com/nextcloud/server/pull/75#discussion_r66933227

See also https://help.nextcloud.com/t/translations-transifex/149

**Comment by mar1u5** [comment]
Will Files Drop be translated in Nextcloud 9, because we have no Transifex yet :confused:

**Comment by MorrisJobke** [comment]
> Will Files Drop be translated in Nextcloud 9, because we have no Transifex yet 😕

@LukasReschke is working on this already ;)

**Comment by AndyScherzinger** [comment]
Sounds good to me, only thing that hasn't been mentioned but would be great to have is a bot that pushes the translation changes to their respective repositories.

**Comment by mar1u5** [comment]
Just for my ToDo:

- [ ] Replace Transifex Link in **CONTRIBUTING.md** as soon as it is ready 😉

**Comment by mar1u5** [comment]
⚠️ Another problem is, that **files drop** is currently not translated 😁

**Comment by MorrisJobke** [comment]
Regarding the rebranding: Could we try to do a search and replace for ownCloud to %s in the translations and hook in there the instance name of the theme? I could look into this soonish :) Then we could make use of all existing translations and import them afterwards

**Comment by mar1u5** [comment]
#234 is a great example to what happens without an translation system :stuck_out_tongue_winking_eye: ... Discussions about the german language in seperate issues on GitHub :smile:

**Comment by AndyScherzinger** [comment]
Would we redo the translations or just import all language actually present and go on from there because else we loose all the languages (quite some on Android)

**Comment by LukasReschke** [comment]
> Would we redo the translations or just import all language actually present and go on from there because else we loose all the languages (quite some on Android)

Import. Just need to figure out how/when to do that properly … if anybody has some time to spent and wants to have fun with Transifex, let me know 😉

**Comment by AndyScherzinger** [comment]
Never worked with transifex except registering an account. This does get more import since future releases merging all the open PRs/branches for the Android app will add to the need for the translation system. If it works like Crowdin you have to define the languages to be available and then upload the file(s) per language.

**Comment by mar1u5** [comment]
Or we create an repo for translations here on GitHub :grin: ... Not as nice as having Transifex ... But ... Yeah ... Better than nothing ... And easier for an first time :wink:

**Comment by ungesundes-halbwissen** [comment]
@mar1u5: for the record: I have looked for a translation system prior to posting in issue #234 and it was only because I didn't know where else to put it that I misused github for this :-P

**Comment by mar1u5** [comment]
@ungesundes-halbwissen Aboulutely correct. We have currently no better place for that :sweat_smile: ...as long as we have no Translation System this is the correct and only working way to do that :grin:

**Comment by MorrisJobke** [comment]
I will today try to get a l10n system setup :)

**Comment by MorrisJobke** [comment]
I imported now all translations from the server repository into transifex. https://www.transifex.com/nextcloud/nextcloud/languages/

Feel free to request for getting into a translation Team. As of now @LukasReschke @jospoortvliet and I can give you the needed rights :)

I will setup a cron job to fetch the translations from there and put them into the git repository.

**Comment by ungesundes-halbwissen** [comment]
Cool! Thanks for all your effort!
On my way :-)

**Comment by AndyScherzinger** [comment]
@MorrisJobke can we have the same thing for Android :) Just sent a "Join Team" request for the server and I could then take care of uploading the files for Android if the project is set up and I have the permission to do so (can be revoked afterwards, I don't care).

**Comment by MorrisJobke** [comment]
@AndyScherzinger What files are needed to be uploaded (as resources) and where should the result be put? Then I set up a cron job to do this automatically ;)

**Comment by AndyScherzinger** [comment]
@MorrisJobke a bit tricky... ;) 
The following file strings.xml 
in the following folders in the folder in https://github.com/nextcloud/android/tree/master/res which start with values-* with values being the English master files to be excluded: values-sw360dp, values-large-land, values-v11, values-v19, values-v21, values-v9. -* defines the language/variant

**Comment by MorrisJobke** [comment]
> so basically the same thing ownCloud has been running and still is.

Do you know if this is somewhere open source?

**Comment by MorrisJobke** [comment]
> Do you know if this is somewhere open source?

Got them. It was only the plain transifex client. I pushed the translation sources and also existing translations :)

**Comment by AndyScherzinger** [comment]
The only thing I found is https://github.com/owncloud/administration/tree/master/jenkins/translation_sync
A quick look seemed this is not for Android though :(

**Comment by MorrisJobke** [comment]
> I pushed the translation sources and also existing translations :)

See https://www.transifex.com/nextcloud/nextcloud/android/

**Comment by AndyScherzinger** [comment]
Oh, okay :+1:  Nice :tada:

**Comment by AndyScherzinger** [comment]
will this then also get pushed back to the repo?

**Comment by MorrisJobke** [comment]
> will this then also get pushed back to the repo?

I will set up a cron job for that.

**Comment by AndyScherzinger** [comment]
You are awesome @MorrisJobke :+1: :+1: :+1: 
I'll update the repo README to refer to transifex + URL :rocket:

**Comment by mar1u5** [comment]
Will we import translations into 9.0.52 😁 New features (Theming, ...) seems to be untranslated in RC1 :(

**Comment by MorrisJobke** [comment]
> Will we import translations into 9.0.52

This is always hard, because we then need to merge the stable9 and the master translations somehow :(

**Comment by mar1u5** [comment]
Keep in mind that end-users **need** a full translated piece of software :wink:

**Comment by LukasReschke** [comment]
I guess this is done, @MorrisJobke ?
