### ISSUE TITLE
External storage won't reflect changes on the storage 

### ISSUE THREAD

**Issue by Nottt** [nextcloud/server#7603]
### Steps to reproduce

1. Add a external unionfs folder as external storage
2. Delete or add files, move stuff around
3. NextCloud won't reflect this even after a long time of waiting, and even restarting the docker container

### Expected behaviour
The web interface should reflect the changes made on the folder, in real time or in a reasonable time. 

### Actual behaviour
Web interface does not reflect changes in the folder. 

### Server configuration

**Operating system**: Ubuntu Server 16.04

**Web server:** Nginx 

**Database:** Mariadb latest docker

**PHP version:** PHP 7.1.9 

**Nextcloud version:** Nextcloud 12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** No

**Where did you install Nextcloud from:** Docker*

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Could not retrieve on my docker
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
Could not find a way to retrieve it on my docker
or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** Yes, a unionfs folder joining a read-only folder with a read-write folder, path being /mnt/unionfs/

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** Not sure. 

### Client configuration
**Browser:** Version 63.0.3239.84 (Official Build) (64-bit)

**Operating system:** Windows 7

#### Web server error log
<details>
<summary>Web server error log</summary>

[error.log](https://github.com/nextcloud/server/files/1580307/error.log)

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

[nextcloud.log](https://github.com/nextcloud/server/files/1580302/nextcloud.log)
</details>

I have many other docker applications that uses the same /unionfs folder, and none has issues dealing with changes in real time so I'm not sure why this is happening only with nextcloud.

Any help is appreciated! Thanks,

**Comment by MorrisJobke** [comment]
You could enable the "Check on every direct access" in the external mount settings: https://docs.nextcloud.com/server/12/admin_manual/configuration_files/external_storage_configuration_gui.html#mount-options

Nevertheless this would only solve part of the problem. As the check of the whole filesystem could be a very resource intensive process, it was disabled and only put in place for accessing a folder (but without checking subfolders). If you want to scan for new files, please use the `occ files:scan /PATH/TO/MOUNT` command line tool.

**Comment by Nottt** [comment]
I already have check for changes on every direct access and it still won't work. Is there any other way to fix this without having to use a terminal every time something changes in my external mount?

**Comment by MorrisJobke** [comment]
Not really - we romeved it because scanning it all the time just kills the performance and made it unusable. You could setup a Cron job for this scanning

**Comment by Nottt** [comment]
If at least it worked as expect, is fine, but I can upload stuff, delete & all form of interacting with the external storage and it just won't update changes. But okay thanks

**Comment by MorrisJobke** [comment]
This is then a separate problem. Could you create a ticket for this then?

**Comment by Nottt** [comment]
Can this please be fixed or something be made to be automatic? I don't understand much of nextcloud and I don't even know how I would run that command using the nextcloud docker... It's getting to the point I can't use nextcloud at all since files won't change
