### ISSUE TITLE
Type in Dutch translation - ocumentatie in stead of documentatie

### ISSUE THREAD

**Issue by radoeka** [nextcloud/server#7604]
### Steps to reproduce
1. GoTo https:///settings/admin
2. First line at the the webpage, has incorrect translation

### Expected behaviour
Text has: Tips & Trucs sectie en de ocumentatie voor meer informatie.

### Actual behaviour
Text should be: Tips & Trucs sectie en de documentatie voor meer informatie.
(added 'd' to documentation)

Nextcloud version: 12.0.4

Text is found in: ./settings/l10n/nl.json and ./settings/l10n/nl.js:

"It's important for the security and performance of your instance that everything is configured correctly. To help you with that we are doing some automatic checks. Please see the Tips & Ticks section and the documentation for more information." : "Voor beveiliging en prestaties van je server is het belangrijk dat alles goed is geconfigureerd. Om je hierbij te helpen doen we paar automatische controles. Bekijk de Tips & Trucs sectie en de ocumentatie voor meer informatie.",

Please correct.

**Comment by rullzer** [comment]
Thanks!

Fixed on transifex. Should be synced tomorrow and will be in the next releases.

**Comment by radoeka** [comment]
Thanks
