### ISSUE TITLE
LDAP login attributes not updating.

### ISSUE THREAD

**Issue by Jookadin** [nextcloud/server#7606]
### Steps to reproduce
1. Add new group under Users and Groups in LDAP configuration.

### Expected behaviour
The login attributes filter should update with the new group that was just added.

### Actual behaviour
The login attributes filter stays the same, resulting in the new groups users being added, but are not able to login.

### Workaround
It was possible to get the login attributes to update by removing the LDAP/AD-username checkmark, and adding it again.

## Server configuration detail

**Operating system:** Linux 4.8.0-49-generic #52~16.04.1-Ubuntu SMP Thu Apr 20 10:55:59 UTC 2017 x86_64

**Webserver:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.20

**PHP version:** 7.0.22-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, redis, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, ldap, exif, mcrypt, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, shmop, SimpleXML, smbclient, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 12.0.3 - 12.0.3.3

**Updated from an older Nextcloud/ownCloud or fresh install: Updated

**Where did you install Nextcloud from: TechandMe VM image

**Comment by MorrisJobke** [comment]
cc @nextcloud/ldap

**Comment by blizzz** [comment]
Comes with 13 https://github.com/nextcloud/server/pull/7321
