### ISSUE TITLE
Replace PhantomJS with Cypress

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/server#7607]
I just stumbled upon this blogpost from Gitlab and was wondering if this will become necessary here as well: https://about.gitlab.com/2017/12/19/moving-to-headless-chrome/

Looks like PhantomJS will not be developed further https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE and if I am not wrong it is used here as well. So in the long run, it might need to be replaced with headless chrome?!

PS: I am not really familiar with PhantomJS, so please excuse if I got something wrong here.

**Comment by MorrisJobke** [comment]
cc @nextcloud/javascript

**Comment by blizzz** [comment]
Yes, PhantomJS was abandoned, sooner or later it needs to re replaced. Firefox can also run in headless mode, whether it is installable on a headless machine idk. In general, yes, we need to move somewhere.

**Comment by MorrisJobke** [comment]
See #8357 and #8258 - cc @juliushaertl

**Comment by juliushaertl** [comment]
karma has a chrome headless launcher, so it should not be to hard to switch. 

https://github.com/nextcloud/server/blob/a18a853e68573d1df18f5e9c322ee27236152ee0/tests/karma.config.js#L301

**Comment by juliushaertl** [comment]
I recently stumbled across [cypress](https://www.cypress.io/), which is a combination of test framework/assertion library with mocking support that uses chrome headless and seems to work on firefox support as well: https://github.com/cypress-io/cypress/issues/1096

Right now I'm trying to use it for some testing on the deck app, and until now I'm really impressed how nice things work there. Maybe it is worth to consider this for the server in some parts as well.

**Comment by raimund-schluessler** [comment]
Since we use cypress for the vue-components now as well, I guess this will be the way to go.

**Comment by skjnldsv** [comment]
We shoud also replace our acceptance tests with cypress :)

**Comment by juliushaertl** [comment]
Moving to headless chrome as a first step in https://github.com/nextcloud/server/pull/24872

**Comment by joshtrichards** [comment]
PhantomJS seems basically gone from server. Only references of consequence across the entire org that I see are:

- docker-ci Dockerfile (an environment variable?)
- mail
- integration_whiteboard
- gallery (archived)

**Comment by skjnldsv** [comment]
Closing then
