### ISSUE TITLE
dav exception on every update

### ISSUE THREAD

**Issue by okias** [nextcloud/server#761]
### Steps to reproduce
1. update nextcloud or owncloud to another minor or major version
2. in browser, update fails
3. in occ from ssh it passes with error

dav: An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':

### Server configuration
**Operating system**:
Gentoo amd64
**Web server:**
nginx version: nginx/1.11.2
**Database:**
mysqld 10.0.26-MariaDB
**PHP version:**
PHP 5.6.24-pl0-gentoo (cli) (built: Aug  7 2016 02:26:18) 
**Nextcloud version:** (see Nextcloud admin page)
10.0-beta
**Updated from an older Nextcloud/ownCloud or fresh install:**
9.0.4
**Where did you install Nextcloud from:**
webapp-config (gentoo portage)

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - comments: 0.3.0
  - contacts: 1.3.1.0
  - dav: true
  - federatedfilesharing: 0.3.0
  - federation: 0.1.0
  - files: 1.5.1
  - files_external: 0.6.0
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.10.0
  - files_texteditor: 2.1
  - files_trashbin: 0.9.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - gallery: 15.0.0
  - news: 8.8.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 0.5.0
  - systemtags: 0.3.0
  - templateeditor: 0.1
  - theming: 0.2.0
  - updatenotification: 0.2.1
Disabled:
  - calendar
  - encryption
  - external
  - firstrunwizard
  - mail
  - tasks
  - user_external
  - user_ldap
  - user_saml
</details>

Every previous owncloud update since 9.0.0 i getting this error. After moving to NextCloud 10-beta I still get this message. All old addressbook tables are dropped, new address book is created and functional, where could be problem? I guess I forgot remove something which makes updater always want create table...

dav: An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':

SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_addressbooks' already exists

**Comment by mar1u5** [comment]
Could I ask you to fill out the issue template :wink:

**Comment by okias** [comment]
I filled few more information.

Generally I just need information, where is check (what DB entry or file) which leads to owncloud/nextcloud trying create table again. I dropped all calendar & contacts data from owncloud 8.x series...

**Comment by okias** [comment]
Probably also fixed by #1025 , I'll reopen in case it persist.

**Comment by ezraholm50** [comment]
Could you help me with the fix please? I can't seem to run the commands, don't have the know how... Also the script provided doesn't work or probably I'm doing something wrong.
