### ISSUE TITLE
ldap_control_paged_result_response(): No server controls in result at /var/www/html/nextcloud/apps/user_ldap/lib/LDAP.php#74

### ISSUE THREAD

**Issue by narutobaka** [nextcloud/server#7610]
### Steps to reproduce
1. LDAP Configuration OK
2. Authentification with an LDAP user OK
3. But in log i get this : Error PHP	ldap_control_paged_result_response(): No server controls in result at /var/www/html/nextcloud/apps/user_ldap/lib/LDAP.php#74

### Expected behaviour
If my LDAP configuration is correct, why this error message?

### Actual behaviour
Just lots of Error log ligne 

### Server configuration

**Operating system**:
CentOS Linux release 7.4.1708 (Core)

**Web server:**
Server version: Apache/2.4.6 (CentOS)

**Database:**
Version du serveur : 10.0.33-MariaDB-wsrep - MariaDB Server, wsrep_25.21.rc3fc46e Galera Cluster

**PHP version:**
PHP 7.1.11 (cli)

**Nextcloud version:** (see Nextcloud admin page)
$OC_Version = array(12,0,4,3);

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
curl -o nextcloud-12-latest.tar.bz2 https://download.nextcloud.com/server/releases/latest-12.tar.bz2

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

Enabled:
  - activity: 2.5.2
  - comments: 1.2.0
  - dav: 1.3.0
  - federatedfilesharing: 1.2.0
  - federation: 1.2.0
  - files: 1.7.2
  - files_pdfviewer: 1.1.1
  - files_sharing: 1.4.0
  - files_texteditor: 2.4.1
  - files_trashbin: 1.2.0
  - files_versions: 1.5.0
  - files_videoplayer: 1.1.0
  - firstrunwizard: 2.1
  - gallery: 17.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.1
  - notifications: 2.0.0
  - oauth2: 1.0.5
  - password_policy: 1.2.2
  - provisioning_api: 1.2.0
  - serverinfo: 1.2.0
  - sharebymail: 1.2.0
  - survey_client: 1.0.0
  - systemtags: 1.2.0
  - theming: 1.3.0
  - twofactor_backupcodes: 1.1.1
  - updatenotification: 1.2.0
  - user_ldap: 1.2.1
  - workflowengine: 1.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{
    "system": {
        "instanceid": "ocovhuc7ct32",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud1.ac-caen.fr"
        ],
        "datadirectory": "\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/nextcloud1.ac-caen.fr\/nextcloud",
        "dbtype": "mysql",
        "version": "12.0.4.3",
        "dbname": "nextcloud",
        "dbhost": "sqlgal.in.ac-caen.fr:3306",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "proxy": "proxy.ac-caen.fr:8080",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "loglevel": 4
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Oracle Directory Server

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
+-------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                                                                    |
+-------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                                                                                                                  |
| hasPagedResultSupport         |                                                                                                                                                                    |
| homeFolderNamingRule          | attr:uid                                                                                                                                                           |
| lastJpegPhotoLookup           | 0                                                                                                                                                                  |
| ldapAgentName                 |                                                                                                                                                                    |
| ldapAgentPassword             | ***                                                                                                                                                                |
| ldapAttributesForGroupSearch  |                                                                                                                                                                    |
| ldapAttributesForUserSearch   | uid;cn                                                                                                                                                             |
| ldapBackupHost                |                                                                                                                                                                    |
| ldapBackupPort                |                                                                                                                                                                    |
| ldapBase                      | ou=personnels EN,ou=ac-caen,ou=education,o=gouv,c=fr                                                                                                               |
| ldapBaseGroups                | ou=personnels EN,ou=ac-caen,ou=education,o=gouv,c=fr                                                                                                               |
| ldapBaseUsers                 | ou=personnels EN,ou=ac-caen,ou=education,o=gouv,c=fr                                                                                                               |
| ldapCacheTTL                  | 600                                                                                                                                                                |
| ldapConfigurationActive       | 1                                                                                                                                                                  |
| ldapDefaultPPolicyDN          |                                                                                                                                                                    |
| ldapDynamicGroupMemberURL     |                                                                                                                                                                    |
| ldapEmailAttribute            | mail                                                                                                                                                               |
| ldapExperiencedAdmin          | 1                                                                                                                                                                  |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                                    |
| ldapExpertUUIDUserAttr        |                                                                                                                                                                    |
| ldapExpertUsernameAttr        | uid                                                                                                                                                                |
| ldapGidNumber                 | gidNumber                                                                                                                                                          |
| ldapGroupDisplayName          | cn                                                                                                                                                                 |
| ldapGroupFilter               |                                                                                                                                                                    |
| ldapGroupFilterGroups         |                                                                                                                                                                    |
| ldapGroupFilterMode           | 0                                                                                                                                                                  |
| ldapGroupFilterObjectclass    |                                                                                                                                                                    |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                                                                                       |
| ldapHost                      | ldap.ac-caen.fr                                                                                                                                                    |
| ldapIgnoreNamingRules         |                                                                                                                                                                    |
| ldapLoginFilter               | (&(|(&(grade=522*)(|(discipline=0011X)(discipline=Y0011)(discipline=0012X)(discipline=Y0012))(finfonction=X)(!(rne=X))(mail=*))(uid=blods)(uid=npenot))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                                                                                    |
| ldapLoginFilterEmail          | 0                                                                                                                                                                  |
| ldapLoginFilterMode           | 0                                                                                                                                                                  |
| ldapLoginFilterUsername       | 1                                                                                                                                                                  |
| ldapNestedGroups              | 0                                                                                                                                                                  |
| ldapOverrideMainServer        |                                                                                                                                                                    |
| ldapPagingSize                | 500                                                                                                                                                                |
| ldapPort                      | 389                                                                                                                                                                |
| ldapQuotaAttribute            |                                                                                                                                                                    |
| ldapQuotaDefault              |                                                                                                                                                                    |
| ldapTLS                       | 0                                                                                                                                                                  |
| ldapUserDisplayName           | cn                                                                                                                                                                 |
| ldapUserDisplayName2          |                                                                                                                                                                    |
| ldapUserFilter                | (|(&(grade=522*)(|(discipline=0011X)(discipline=Y0011)(discipline=0012X)(discipline=Y0012))(finfonction=X)(!(rne=X))(mail=*))(uid=blods)(uid=npenot))              |
| ldapUserFilterGroups          |                                                                                                                                                                    |
| ldapUserFilterMode            | 0                                                                                                                                                                  |
| ldapUserFilterObjectclass     |                                                                                                                                                                    |
| ldapUuidGroupAttribute        | auto                                                                                                                                                               |
| ldapUuidUserAttribute         | auto                                                                                                                                                               |
| turnOffCertCheck              | 0                                                                                                                                                                  |
| turnOnPasswordChange          | 0                                                                                                                                                                  |
| useMemberOfToDetectMembership | 1                                                                                                                                                                  |
+-------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------+

</details>

### Client configuration
**Browser:**
Firefox ESR 52.5.2 (32 bits)

**Operating system:**
Windows 7

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
No error log

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
Error PHP ldap_control_paged_result_response(): No server controls in result at /var/www/html/nextcloud/apps/user_ldap/lib/LDAP.php#74

It seems that i get the php error when i have this in ldap result :
limit 500 offset 0
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
no error log

</details>

**Comment by MorrisJobke** [comment]
Looks similar to #7662 - cc @nextcloud/ldap

**Comment by blizzz** [comment]
Nope, the LDAP server seems not to support Paged Results. Setting paged chunk size in advanced to 0 would prevent using them.

**Comment by narutobaka** [comment]
Hi 

Is there a way to avoid this log?

cordialy

**Comment by narutobaka** [comment]
Hi,
I come back on this problem that I solve.
Our LDAP don't support ldap_control_paged_result_response().
So i disable the "ldapPagingSize" ldap parameter from default 500 value to 0 value.
And no more problem nor log of ldap_control_paged_result_response().
cordialely
