### ISSUE TITLE
Feature request: Sync existing

### ISSUE THREAD

**Issue by rkarlsba** [nextcloud/server#7616]
### Steps to reproduce
1. Create account
2. Connect to account with a well-used phone
3. Wait for it to synchronise existing pictures

### Expected behaviour
It does synchronise things

### Actual behaviour
It doesn't synchronise things

### Server configuration (etc)
Not relevant, since this happens on all versions I've tested, with both the owncloud and the nextcloud client. I've seen a few bug reports like this, but they seem to be just closed without any reason, so I wonder why this feature hasn't been addressed after *years* of talk about it. It really can't be that hard.

If it is, for some reason, not will for writing this, does anyone have a way to bypass this without uploading every picture manually? It'll take ages!

**Comment by rullzer** [comment]
Please fill this in the https://github.com/nextcloud/android or https://github.com/nextcloud/ios repo
