### ISSUE TITLE
Error pages ignore user theme image [Includes fix]

### ISSUE THREAD

**Issue by Bugsbane** [nextcloud/server#762]
Currently, if the user sets a background image in the theming section, the login page (rightly) looks like this:
![login](https://cloud.githubusercontent.com/assets/401733/17471330/61a2d5ca-5d11-11e6-93ec-29d8bb36d3d9.png)

but whenever the user hits any kind of error Nextcloud ignores the users theming and shows this:
![error](https://cloud.githubusercontent.com/assets/401733/17471347/7d8c518a-5d11-11e6-92a2-1f05a9dc2a1c.png)

With two commits from my branch though, instead error pages are correctly themed, like so:
![error-themed](https://cloud.githubusercontent.com/assets/401733/17471501/bebc159a-5d12-11e6-9449-1790cdb198ff.png)

The sexy part of this is that if the themed image doesn't exist (eg. the theme app is uninstalled) it gracefully falls back to the current behaviour.

The single line change can be found in the following two commits (yeah, I screwed up the first one) in my repo:
https://github.com/Bugsbane/server/commit/d0c2cf3b86521b1d449caa83f0a07b342bcbd711
https://github.com/Bugsbane/server/commit/45e7934ccb46278066b419fe1cbc1907e98e1bf6

I'm just not doing a PR as I'm currently making a lot of other changes to styles.css and committing the whole file in it's current state would break all kinds of stuff, and my Git-fu is not yet strong enough to know a way around it. :(

So could I get this looked at by our illustrious @nextcloud/designers and merged if it all looks good?

**Comment by Bugsbane** [comment]
OK, I managed to "get my Git on" and figure out how to make a proper PR with just the changes needed. It can be seen [here](https://github.com/nextcloud/server/pull/765).

**Comment by MorrisJobke** [comment]
Open PR: https://github.com/nextcloud/server/pull/765#issuecomment-238160556

**Comment by juliushaertl** [comment]
@Bugsbane I can't reproduce the issue, in case of the file not found error message, the background image is rendered fine on latest master.

**Comment by Bugsbane** [comment]
@juliushaertl The question is though, which background image are you getting? The issue is that error messages display Nexcloud's default background image, rather than the one set by the user in the theming area.

The only thing needed to reproduce is to request a page of nextcloud that doesn't exist, eg mycloud.com/sufneosyfhdhjghmonkeymonkeyjuliusisawesome42

**Comment by juliushaertl** [comment]
@Bugsbane I've just checked again to verify, on all stable9/stable10/master:
I've set a custom background image and opened a non existing page and the custom background is shown. 
![2016-08-09-215800_954x440_scrot](https://cloud.githubusercontent.com/assets/3404133/17531563/b070efe0-5e7c-11e6-9f81-2b7d9dddcc70.png)

**Comment by Bugsbane** [comment]
OK.... I guess someone already put in a fix before, as it definitely doesn't do that on my install of 9.0.53. Cool beans. I guess we can close this down.
