### ISSUE TITLE
NextCloud Server Listener 

### ISSUE THREAD

**Issue by ibr123** [nextcloud/server#7622]
Hi,

I have seen at the [link](https://github.com/nextcloud/server/blob/master/apps/comments/lib/Activity/Listener.php) that there is a class for listening to the server, but in the developer documentation i didn't find any an external app or server that exposes this class so it will enable the listening to the server, at admin lever not user level

Is there a possible way to do that?

Thanks in advance

**Comment by MorrisJobke** [comment]
You can use the event dispatcher in the php code of a nextcloud app to listen to events. This is not exposed to an general HTTP API. If you are looking for the comments you can access them via Webdav per file: https://github.com/nextcloud/server/issues/7315#issuecomment-347468998
