### ISSUE TITLE
Add multiple files to favorites 

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#7627]
See proposed mockup:

<img width="1011" alt="bildschirmfoto 2017-12-26 um 18 35 06" src="https://user-images.githubusercontent.com/19711361/34361590-add28cfe-ea6b-11e7-9700-aa48fde52bef.png">

- Nextcloud 13

**Comment by weeman1337** [comment]
I'll take this one.

**Comment by MorrisJobke** [comment]
Most likely nothing for 14 -> moving to 15.

**Comment by MorrisJobke** [comment]
@weeman1337 You still can continue to think about this and work on this, but it will then be integrated into 15 first.

**Comment by tobiasKaminsky** [comment]
Once this is in, we should also do this on client-side

**Comment by MorrisJobke** [comment]
> Once this is in, we should also do this on client-side

You can already do this. It only needs a client side implementation. For multiple files/folder moves we trigger just multiple MOVE requests from the frontend, which allows proper UI feedback as well. The favorites already can be tagged via the PROPPATCH method. The only problem here is that the activity is not yet implemented. See #26393

**Comment by tobiasKaminsky** [comment]
So there will be no new endpoint to pass bunch of file so mark them as favorited?

**Comment by MorrisJobke** [comment]
> So there will be no new endpoint to pass bunch of file so mark them as favorited?

Correct - only multiple PROPPATCH requests.

**Comment by szaimen** [comment]
@weeman1337 Any update here?

**Comment by tobiasKaminsky** [comment]
Still a valid enhancement, no idea why bot closed this.

**Comment by tobiasKaminsky** [comment]
@skjnldsv is there a specific new API to bulk add files to favorite, or is it "just" doing it one by one?

**Comment by skjnldsv** [comment]
For now one-by-one.

If I start adding dedicated APIs, I will ping the client team, I'll keep that in mind, no worries :)
https://github.com/nextcloud/server/blob/0411cc64aaaaa42ae23b4d5e216f16d481f20819/apps/files/src/actions/favoriteAction.ts#L99-L102
