### ISSUE TITLE
Create Folders when moving files

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#7629]
Currently it is not possible to create folders in the filepicker, so it is not possible to move files to non-existing folders :(

<img width="636" alt="bildschirmfoto 2017-12-26 um 20 44 35" src="https://user-images.githubusercontent.com/19711361/34363589-a904d224-ea7d-11e7-972f-ceb3dde0fc84.png">

What do you think @nextcloud/designers

**Comment by skjnldsv** [comment]
Definitely a lacking feature :)

**Comment by jancborchardt** [comment]
Absolutely. There should be an "Add folder" button in the breadcrumbs just like in Files. Probably makes sense to have a new Folder+ icon for this so it can be just an icon.

(Btw @MariusBluem the copy/move icons should be next to each other, not above/below. Could you open an issue about it?)

**Comment by fermulator** [comment]
PS: I have a some screenshot mockups of the "story/issue" + "proposal" in #11727.
