### ISSUE TITLE
After the server is configured with the ldap server, the number of users in the user list is not displayed

### ISSUE THREAD

**Issue by ziqingshi** [nextcloud/server#7630]
### Steps to reproduce
The server is configured with the ldap server, the number of users in the user list is not displayed.
### Expected behaviour
The number of users in the user list is displayed.

### Actual behaviour
The number of users in the user list is not displayed.
![image](https://user-images.githubusercontent.com/34739130/34368157-a97b7644-eaec-11e7-9c66-75caf4831a8d.png)

**Comment by rullzer** [comment]
@blizzz for ldap magic

**Comment by blizzz** [comment]
That's disabled on purpose, because it would kill performance.
