### ISSUE TITLE
Logging - logdateformat - Possible Options

### ISSUE THREAD

**Issue by vermaden** [nextcloud/server#7632]
Hi,

for Nextcloud 12.x what are ALL possible options for the 'logdateformat' option?

Regards.

**Comment by ChristophWurst** [comment]
See https://docs.nextcloud.com/server/12/admin_manual/configuration_server/config_sample_php_parameters.html#logging

**Comment by vermaden** [comment]
Ok, that is clear to me now.

Tell me then, how to set logging for BOTH file (nextcloud.log) and syslog?

The documentation says that its possible to use either file or syslog.

Thanks.

**Comment by ChristophWurst** [comment]
Please see the forum http://help.nextcloud.com/ for those questions. Thanks.

**Comment by vermaden** [comment]
Ok, thank You for help.

**Comment by vermaden** [comment]
Ok, thank You for help.

Thread for reference:
https://help.nextcloud.com/t/nextcloud-logging/25190
