### ISSUE TITLE
Use theme colour for upload progress bar

### ISSUE THREAD

**Issue by realies** [nextcloud/server#7636]
Currently, despite the custom theme colour, the upload progress bar in the web UI stays blue.

**Comment by juliushaertl** [comment]
@realies Thanks for reporting. Unfortunately I'm unable to reproduce this on current master. Please fill out the issue template to provide some more details on your setup.

**Comment by juliushaertl** [comment]
Closing this since I could not reproduce that and missing issue template. Feel free to reopen with more details provided.

**Comment by realies** [comment]
@juliushaertl, unfortunately this is still the case with 12.0.5. It is reproducible when you set the theming color to `#000000`.

<img width="326" alt="screen shot 2018-01-24 at 14 04 39" src="https://user-images.githubusercontent.com/5107843/35331361-c2a81404-010f-11e8-8ade-7d3ce1925ec8.png">

**Comment by juliushaertl** [comment]
@realies Thanks, yes I can reproduce that in 12.0.6.

**Comment by realies** [comment]
@juliushaertl, good to see that you have reproduced it. Please re-open the issue.

**Comment by juliushaertl** [comment]
@realies Ah sorry, forgot to hit that button as well :wink:

**Comment by MorrisJobke** [comment]
@juliushaertl I will move this to 12.0.7, okay?

**Comment by juliushaertl** [comment]
Sure.

**Comment by brunt82** [comment]
I thought this issue was fixed with https://github.com/nextcloud/server/pull/8022?

**Comment by juliushaertl** [comment]
:see_no_evil: Thanks @brunt82 

Actually fixed with 12.0.6
