### ISSUE TITLE
Redirect to "/apps/files" instead of 404 -> upload via webdav (app) not working

### ISSUE THREAD

**Issue by Mr-Maniac** [nextcloud/server#7639]
### Steps to reproduce
1. Start upload in WebDAV client (e.g. Nextcloud app)
2.
3.

### Expected behaviour
Upload via webdav should work. When a file does not exists, nextcloud server should return HTTP code 404

### Actual behaviour
1. WebDAV Client (Nextcloud App and Windows 10 Explorer) are requesting new filename to see, if file already exists (e.g. HEAD /remote.php/webdav/Folder/File.ext)
2. Nextcloud server redirects to /apps/files/ with 302
3. WebDAV Client follows redirect and gets 200 (File exists)
4. Client chooses new filename (File (2).ext) and tries again (goto 1)
Windows 10 Explorer sends a PROPFIND request to /apps/files/ and gets a 405 (Method not allowed)

### Server configuration

**Operating system**: Gentoo Linux (Kernel 4.14.8)

**Web server:** Apache 2.4.29

**Database:** PostgreSQL

**PHP version:** 7.2 (also happened with 7.1.12)

**Nextcloud version:** 12.0.0.4 and 13.0.0 beta 3

**Updated from an older Nextcloud/ownCloud or fresh install:** Originally installed from ZIP and upgraded via web updater ever since

**Where did you install Nextcloud from:** ZIP Package from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - calendar: 1.5.7
  - comments: 1.3.0
  - contacts: 2.0.1
  - dav: 1.4.5
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - survey_client
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***MY_DOMAIN***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwritewebroot": "",
        "htaccess.RewriteBase": "\/",
        "overwrite.cli.url": "https:\/\/nextcloud.mad-ftp.dyndns.org",
        "dbtype": "pgsql",
        "version": "13.0.0.8",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "asset-pipeline.enabled": true,
        "default_language": "de",
        "maintenance": false,
        "theme": "",
        "mail_smtpauthtype": "LOGIN",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "updater.release.channel": "beta"
    }
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Nextcloud App or accessing non-existing js/image file via any browser

**Operating system:** any

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No error log, but example apache access_log as attachment: 
[nextcloudApacheAccess.log](https://github.com/nextcloud/server/files/1592053/nextcloudApacheAccess.log)

```
</details>

**Comment by Mr-Maniac** [comment]
In Nextcloud 12 this issue only arises, when "htaccess.RewriteBase" is set in config.php - /core/templates/403.php and /core/templates/404.php should be excluded from rewriting with a RewriteCond

In Nextcloud 13 this issue always arises, since ErrorDocument is set to /

**Comment by Mr-Maniac** [comment]
I've manually patched my Nextcloud installation so that I can upload again:
1. Reverted changes in core/templates/404.php from commit https://github.com/nextcloud/server/commit/0de90cfc672ebb8bb7c8ffa01d40380715c42f94
2. Manually added following line in .htaccess (should be done in lib/private/Setup.php instead):
RewriteCond %{REQUEST_FILENAME} !core/templates/404.php$

Now the upload works again. And even with RewriteBase enabled (pretty urls / index.php free)

**Comment by MorrisJobke** [comment]
> /core/templates/403.php and /core/templates/404.php should be excluded from rewriting with a RewriteCond

We removed this on purpose. Those files should not be used to present a 404 page. The controller itself should render the 404 page.

**Comment by MorrisJobke** [comment]
The general issue here looks like an issue with how the web server is set up. Could you check the apache config?

Also I could not reproduce the issue with your setup. Using something like `https://nextcloud.mad-ftp.dyndns.org/remote.php/webdav/abc/def` and then I get a proper 403 error message.

**Comment by MorrisJobke** [comment]
Also when testing this locally it works fine. An URL like `http://192.168.99.100/server/remote.php/webdav/abcsdfakjlkashdfg` gives me a 404 error code and not an redirect.

**Comment by Mr-Maniac** [comment]
Okay, after searching and trying out a lot, I've found out, that the apache directive "ProxyErrorOverride On" caused this. I've used this directive, since my own page did not always show my custom 404 page and with this directive, it worked.
Now, I get the 404 error from sabredav and not, like before, that from nextcloud itself.
Thank you for the help. It seems to work now.
