### ISSUE TITLE
No access to full cifs/smb drive 

### ISSUE THREAD

**Issue by 3Dscrewer** [nextcloud/server#7640]
How to get access to full drive cifs/smb drive
In Nextcloud there is the question for a folder, but if you like to give access to a whole drive there is no possibility. I have tried .. and / and \ even // and \\ didn't work.
Ok, I can move all Files into a subfolder, but in this case I have to configure a lots of Apps in a new way. I have asked this question in the Forum, but get no answer ....

**Comment by MorrisJobke** [comment]
`/` should work. cc @icewind1991

**Comment by 3Dscrewer** [comment]
Here I have made Screenshots. As suggested, I have tried the single Slash as well.
See comments I've made at the pictures. I have captured the 1st picture before I have assigned "Files" to admin Group. 


![1](https://user-images.githubusercontent.com/34925249/34482570-26bac01c-efb9-11e7-972e-fabda1a1b886.png)
![2](https://user-images.githubusercontent.com/34925249/34482571-26dd8700-efb9-11e7-9b8d-e385e0796bea.png)
![3](https://user-images.githubusercontent.com/34925249/34482572-26f5103c-efb9-11e7-8986-7c66677f4a92.png)
![4](https://user-images.githubusercontent.com/34925249/34482573-270d7820-efb9-11e7-9901-06b7fe83d9a2.png)
![5](https://user-images.githubusercontent.com/34925249/34482574-2726f200-efb9-11e7-8da7-03afcb823e08.png)

**Comment by icewind1991** [comment]
What smb storage server are you using, I have no problem with mounting the root of the share with either a win10 or samba server by leaving the subfolder empty

![](https://screenshots.firefoxusercontent.com/images/fdb32803-bdad-46d7-b381-afa1f7e53b23.png)

**Comment by 3Dscrewer** [comment]
Is not working for me. 
When i have created a Folder in NC and named "Files"
`sudo mount -t cifs -o user=hes,domain=XXXXX //192.168.178.25/Filebase /var/ncdata/ncadmin/files/Files`

and starting a filescan
sudo -u www-data php occ files:scan --all -v

I have the drive, but the scan will take more than 3h

I have bought the Hyper-V Image at techandme.se but he is answering no questions. He said the VM has build in smb/cifs support, but in my opinion it has not. I have installed samba and there was no message that it is already there, I have tried cifs-utils with same result. But I have no clue how to set up the samba.conf my question at Nextcloud Forum is still not answered.
Since I have the Fall Creator Update at my W10P I have activated the smb/cifs and Linux support. Since that I have access to my NTFS Drives in Host Maschine. Folders no Problem, mounting the whole drive, no problem, but inside Nextcloud no ....

**Comment by icewind1991** [comment]
Ok, so you're using win10 as the smb server?

Have you tried leaving the folder field empty?

> I have installed samba and there was no message that it is already there

I don't know the details of the VM image, but you might have installed the samba server while the client was already available, since you can mount folders on the share that seems to be the case

**Comment by 3Dscrewer** [comment]
First thank you for your time ...
No leaving that field empty doesn't work
Yes, the Host of the VM is W10Pro, that's the only Version with Hyper-V support.
But once again, in November there was a big Fall Creator Update (for W10), but I didn't receive it.
So I was asking around and I get the Hint that W10Pro has since this big update cifs/smb support and Linux support AND it has SSH (Beta) but I had to activate it in (W10) System Setting. Since that minute I have the update I can use the mount command and not before.
So it might be, that the fault is in W10 cifs/smb support.
Tomorrow I will get a new DSL Line, so I have to do a lot of small jobs and since I have learned a lot about Linux, I will try a new clean setup and it's the only Case to find out if smb support is available by default (in the VM)

**Comment by 3Dscrewer** [comment]
Sorry for the delay.
I didn't know that there are several ways to bind the Host SMB/CIFS to Nextcloud and that there is no need to have Samba, smbclient, cifs-utils or something like that. Sorry for that.
I have done another clean setup and the problem still exists. No access to the full drive.
@enoch85 wrote to me there is php7.0-smbclient installed, so @icewind1991 you may probably have a different setup?
Anyway, since I am using a VM Version, the Drive I want to use is one of the Host Drives and obligatory present when VM is running. So I wrote it (now with smbclient ;-) ) into fstab and it is now available. That is not what I wanted, but hopefully there will be another way in future.
Thanks everyone for your help and I will ask for apologize waisting your time, sorry ....

**Comment by MorrisJobke** [comment]
Let's close this ticket here then.
