### ISSUE TITLE
After configuring the LDAP service, the number of users is not visible

### ISSUE THREAD

**Issue by HandsomeBoby** [nextcloud/server#7641]
### Steps to reproduce
1.Configure the LDAP service
2.Open the user list
3.The number of people at the user list is not visible

such as：
This is not configured service：
![image](https://user-images.githubusercontent.com/19202505/34428165-dc4dd1ea-ec84-11e7-8be5-c662e6b1be32.png)
After configuration will become like this：
![image](https://user-images.githubusercontent.com/19202505/34428231-a4e5d9ae-ec85-11e7-9460-9cbfeb67efa7.png)

expected outcome：
The number of users is displayed normally

**Comment by rullzer** [comment]
See https://github.com/nextcloud/server/issues/7630#issuecomment-354271334
