### ISSUE TITLE
Unable to sync files : "Sabre\DAV\Exception\BadRequest: expected filesize 4848862 got 3112960"

### ISSUE THREAD

**Issue by venkat118** [nextcloud/server#7642]
Actual behaviour
Files are not synced

Expected behaviour
Files to be synced

Steps to reproduce
Upload a file
Environment data
Android version:

Device model:

Stock or customized system:

Nextcloud app version: 2.3.3

Nextcloud server version:12.0.4

Logs
Nextcloud log (data/nextcloud.log)
Sabre\DAV\Exception\BadRequest: expected filesize 4848862 got 3112960

Insert your Nextcloud log here

**Comment by tflidd** [comment]
There are a few things in the configuration that can cause this issue:
https://forum.owncloud.org/viewtopic.php?f=17&t=32517

If none of these tips works, we probably need much more information (web server used, reverse proxies, their settings, ...)

**Comment by MorrisJobke** [comment]
Closing for now - we can reopen if the mentioned post does not solve the issue.

**Comment by joekerna** [comment]
Is it possible to find out, which file the message is talking about?
