### ISSUE TITLE
Nextcloud 13: Scrolling broken in News app

### ISSUE THREAD

**Issue by BernhardPosselt** [nextcloud/server#7643]
Latest master (ea858fcb553aff59f50e4dcabc42fc8c7c2f200d) on both server and News

See https://github.com/nextcloud/news/issues/239 for more details

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by skjnldsv** [comment]
Not really the place for this no?
We updated the guidelines based on the new app list, apps needs to update to match our requirements :)

**Comment by BernhardPosselt** [comment]
@skjnldsv feel free to fix it in all apps ;)

**Comment by skjnldsv** [comment]
@BernhardPosselt I did on most of them, but it's far from broken for everyone, I helped on calendar for the app navigation, contacts as a pr open end ready to merge. So far news is the only one we have that broke that hard (apparently, I did not test it) I'm already working on all apps after standardisation I have no time to fix all of them :/

**Comment by BernhardPosselt** [comment]
position: relative on #app-content-wrapper is what broke things.

**Comment by LEDfan** [comment]
Removing the `display: flex` on `#app-content-wrapper` fixes the loading of new items for me (compact mode) . See https://github.com/nextcloud/news/issues/245#event-1412334032

**Comment by LEDfan** [comment]
Removing the `display: flex` on `#app-content-wrapper` fixes the loading of new items for me (compact mode) . See https://github.com/nextcloud/news/issues/245#event-1412334032

**Comment by jancborchardt** [comment]
@LEDfan @BernhardPosselt a pull request to fix it, including testing with other apps like Contacts, Calendar, Mail, Notes etc is much appreciated. :)

**Comment by rullzer** [comment]
Since this is apparently the new guidelines. And it is on the todo list of @skjnldsv . Let close this.

**Comment by skjnldsv** [comment]
@rullzer well, we can let it opened while we wait for my fix!

**Comment by rullzer** [comment]
ok fair enough just let me remove it from the 13 milestone then :P
