### ISSUE TITLE
Not-Accessible remote share causes high slowdowns (and timeouts)

### ISSUE THREAD

**Issue by krombel** [nextcloud/server#7645]
### Steps to reproduce
1. add a remote share
2. shutdown or the server of the remote share (or let it respond 404)
3. experience HIGH loading times with even failing times

### Expected behaviour
I just get an error that the share is not available anymore or similar

### Actual behaviour
The access of (nearly) all pages becomes unusable slow (timeouts)
The client was not throwing any errors as it handles them silently I think

**Nextcloud version:** (see Nextcloud admin page)
12.0.4 and 13.0 beta 3 (updated to see if the update would resolve the issue)

#### Web server error log
from time to time I see 
```
504 Gateway timeout
```
for the following requests:
```
/css/core/578c904904b0a852aad8a5b9acbd3044-share.css?v=97d63a6b-17
/js/core/merged-share-backend.js?v=97d63a6b-17 
```
#### Browser log
requests of
`/ocs/v1.php/apps/files_sharing/api/v1/remote_shares?format=json&include_tags=true`
are returning (after a long delay 2,5 minutes; only viewable after increasing timeouts)
```json
{
    "ocs": {
        "meta": {
            "status": "failure",
            "statuscode": 998,
            "message": "Invalid query, please check the syntax. API specifications are here: http:\/\/www.freedesktop.org\/wiki\/Specifications\/open-collaboration-services. DEBUG OUTPUT:\n"
        },
        "data": []
    }
}
```

#### What have I done to resolve the issue
I could not list the shares on the webapp so I deleted that share from the database directly.

```sql
SELECT * FROM oc_share_external;
DELETE FROM oc_share_external WHERE id=<id of the share that is offline>;
```
After that the speed of the webpage is "back to normal"

**Comment by rullzer** [comment]
Fixed in master so should be in the next beta/rc (and thus NC 13): https://github.com/nextcloud/server/pull/7485/commits/3b343e287fa18683a1070af26d93916f68a9fea2

**Comment by krombel** [comment]
Haven't found the issue for that...
So this is a duplicate of #7001

**Comment by rullzer** [comment]
yep, hopefully we can release an update soon in the new year. So you can test :)

**Comment by krombel** [comment]
The share that causes the issue will not reappear. So removing the share just fixed it.
Therefore this is not that critical and I cannot test it anymore (without spinning another instance up)
I opened the issue for "longterm-enhancement" :)
So thanks for having a fix implemented even before I requested it :innocent:
