### ISSUE TITLE
Delete button as far as possible from selection box

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#7647]
Select a file in the web UI on the left. You'll find the delete button (and other buttons) totally on the right. You will probably not even notice they just appeared... @waazdakka pointed this out and I even had to look for the delete button myself...

Maybe it's simplistic to put them on the left, but... Better ideas?

@nextcloud/designers

**Comment by jancborchardt** [comment]
This should be symmetric to the normal file list entries, with the actions in a 3-dot-menu. In this case the 3-dot-icon can be directly right next to the "2 folders & 5 files" text.

Also makes it work better on mobile where the 3 icons are close together without labels. On desktop, the 3-dot-icon could have a label like "Actions".

**Comment by jancborchardt** [comment]
Also cc @Abijeet who implemented this :)

**Comment by jospoortvliet** [comment]
That would indeed help a lot, I think... @waazdakka agreed?

**Comment by Abijeet** [comment]
This is what I'm going to be doing in a separate PR - 

1. On mobile the actions - Move to, download and delete will be going into a 3-dot-menu.
2. Ensure that the *Delete* label should be right of the icon, like with the other icons on all resolutions.

Note that if we go with the above changes there will be some HTML that will be duplicated.

**Comment by Abijeet** [comment]
@MorrisJobke - These changes will not be minor, not sure if I'd label this as papercut.

**Comment by Abijeet** [comment]
Maybe someone from the JS team can help me on this one.

For the new dropdown needed on lower resolutions, I'm planning to do the following,

1. Create a new Backbone View to handle the dropdown needed on this one.
2. Some of the methods in `filelist.js` such as `_onClickDownloadSelected`, `_onClickCopyMoveSelected`, `_onClickDeleteSelected` etc will have to be be made "public" so that the other component can use this.
3. Will initialize the view similar to the NewFileMenu dropdown.

Thoughts?

**Comment by jancborchardt** [comment]
@Abijeet the changes you mention sound perfect! :)

Maybe @skjnldsv @juliushaertl or @pixelipo can help with the JS?

**Comment by Abijeet** [comment]
Finally got round to working on this. 

I've added the actions menu on the normal view as well and displaying it right next to the "1 folder and 1 file" selected text. Not a huge fan of this approach though. I feel the move or copy, delete and  download icons appearing earlier were clearer than this and felt more intuitive, especially on a large monitor. 

![screenshot-localhost-2018 05 27-18-35-38](https://user-images.githubusercontent.com/1685517/40586213-0010081e-61dd-11e8-81bb-16ca7f0d74dd.png)

@jancborchardt / @nextcloud/designers - What do you think?

**Comment by jancborchardt** [comment]
@Abijeet looks good! :) Only a detail: The triangle should be in the middle of the box, pointing towards the 3-dot-icon.

Regarding showing the contents of the actions menu earlier – sure: We could show »Move or copy« outside of the menu (left of it, with text) on a bigger screen. But more than 1 action outside the menu is too much.

**Comment by skjnldsv** [comment]
> @Abijeet looks good! :) Only a detail: The triangle should be in the middle of the box, pointing towards the 3-dot-icon.

Documentation: https://docs.nextcloud.com/server/13/developer_manual/design/popovermenu.html
:)

**Comment by jancborchardt** [comment]
@skjnldsv in the alignment it says `Right is by default` – seems it should be centered by default for sure, and right as an option, just like left. :)

**Comment by Abijeet** [comment]
> The triangle should be in the middle of the box, pointing towards the 3-dot-icon.

@jancborchardt - Done

Here are a few screenshots,

## Laptop

![screenshot from 2018-06-02 21-02-40](https://user-images.githubusercontent.com/1685517/40878028-540fb8ae-66a8-11e8-92fe-e2d464670a4e.png)

## Mobile

### Landscape
![localhost_nextcloud_index php_apps_files__dir _ iphone 6_7_8 plus](https://user-images.githubusercontent.com/1685517/40878020-2da19570-66a8-11e8-9a73-ceeecec7abcb.png)

### Potrait
![localhost_nextcloud_index php_apps_files__dir _ iphone 6_7_8 plus 1](https://user-images.githubusercontent.com/1685517/40878032-65f70bda-66a8-11e8-9785-c5cb82b0dab8.png)
