### ISSUE TITLE
Slogan background on Safari in iOS

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/server#7652]
iOS: 12.2.1 on an iPhone SE (latest version)
NextCloud: 12.0.4 (latest version)
PHP: 7.1.11
MySQL: 5.7.20

If I open the page with safari, the slogan has a background color.

![image-1](https://user-images.githubusercontent.com/1473674/34454029-11f8b07a-ed62-11e7-8546-624eb4973619.jpg)

**Comment by MorrisJobke** [comment]
@MariusBluem Could you verify this? For me this is not the case :(

**Comment by Dennis1993** [comment]
I tested it in your demo. There is the same blue box shown on iPhone :) I can't verify that at the moment why the blue box is showing. Maybe because I have to scroll there...

**Comment by MariusBluem** [comment]
Works fine for me.

**Comment by Dennis1993** [comment]
In 12.0.5 the problem is solved with my iPhone SE! :D
Thanks!
