### ISSUE TITLE
Issue upgrading: Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'CREATE UNIQUE INDEX fs_storage_path_hash ON oc_filecache (storage, path_hash)': SQLSTATE[23000]: Integrity constraint violation: 19 indexed columns are not unique

### ISSUE THREAD

**Issue by maxwellwhite** [nextcloud/server#7653]
### Steps to reproduce
1. Upgrade
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:

**Web server:**

**Database:**
Default 

**PHP version:**
7

**Nextcloud version:** (see Nextcloud admin page)
Updating to newest

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by maxwellwhite** [comment]
As an alternative, can someone show me how to revert to the backup version and I can just not upgrade? It successfully backed up but I don't know how to return to the backup version

**Comment by MorrisJobke** [comment]
cc @icewind1991 @nickvergessen

**Comment by MorrisJobke** [comment]
@maxwellwhite From which to which version was the upgrade? Could you post the nextcloud log?

**Comment by nickvergessen** [comment]
Can you run the following command and post the result here?
```sql
SELECT COUNT(*) AS duplicates, path, storage
FROM oc_filecache
GROUP BY storage, path
HAVING duplicates > 1
```

**Comment by MorrisJobke** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
