### ISSUE TITLE
Activity: TOTP log messages do not get translation

### ISSUE THREAD

**Issue by mjanssens** [nextcloud/server#7657]
In activity log the TOTP logon messages are not translated and stay English although translations are available.
Could this be same issue as https://github.com/nextcloud/server/issues/7345?
In settings/Activity/SecurityProvider.php I see "core" being used.

**Comment by rullzer** [comment]
Yes that seems similar. I'll take care. Thnx for noticing.

**Comment by MorrisJobke** [comment]
Fix is in #7659
