### ISSUE TITLE
Sabre: Incorrect string value

### ISSUE THREAD

**Issue by Priebojp** [nextcloud/server#7661]
Hello,

If i want to sync a calendar event through CalDav from EmClient i got an Exception.
The problem is with table "oc_calendarobjects_props"  and Sabre.
This function "apps/dav/lib/CalDAV/CalDavBackend.updateProperties()" try to save a UTF-8 converted text into db but they save only the first xy char of the text. 
And this is the problem. Because after the Split of the text there is a chance of get Incorrect string.

Text:
Obchod pouze baby ideálně kolem 30ti možná po mateřské
Ohodnocení Obchodniček - dodržet parametry ale velmi motivační musí při dobrém výkonu dosáhnout 100% při vynikajícím 120%
Podřídit veškerou kontrolu kontrole parametrů
Co nejví

Expected decode:
\x4f\x62\x63\x68\x6f\x64\u20\x70\x6f\x75\x7a\x65\u20\x62\x61\x62\x79\u20\x69\x64\x65\xc3\xa1\x6c\x6e\xc4\x9b\u20\x6b\x6f\x6c\x65\x6d\u20\x33\x30\x74\x69\u20\x6d\x6f\xc5\xbe\x6e\xc3\xa1\u20\x70\x6f\u20\x6d\x61\x74\x65\xc5\x99\x73\x6b\xc3\xa9\x0a\x4f\x68\x6f\x64\x6e\x6f\x63\x65\x6e\xc3\xad\u20\x4f\x62\x63\x68\x6f\x64\x6e\x69\xc4\x8d\x65\x6b\u20\x2d\u20\x64\x6f\x64\x72\xc5\xbe\x65\x74\u20\x70\x61\x72\x61\x6d\x65\x74\x72\x79\u20\x61\x6c\x65\u20\x76\x65\x6c\x6d\x69\u20\x6d\x6f\x74\x69\x76\x61\xc4\x8d\x6e\xc3\xad\u20\x6d\x75\x73\xc3\xad\u20\x70\xc5\x99\x69\u20\x64\x6f\x62\x72\xc3\xa9\x6d\u20\x76\xc3\xbd\x6b\x6f\x6e\x75\u20\x64\x6f\x73\xc3\xa1\x68\x6e\x6f\x75\x74\u20\x31\x30\x30\x25\u20\x70\xc5\x99\x69\u20\x76\x79\x6e\x69\x6b\x61\x6a\xc3\xad\x63\xc3\xad\x6d\u20\x31\x32\x30\x25\x0a\x50\x6f\x64\xc5\x99\xc3\xad\x64\x69\x74\u20\x76\x65\xc5\xa1\x6b\x65\x72\x6f\x75\u20\x6b\x6f\x6e\x74\x72\x6f\x6c\x75\u20\x6b\x6f\x6e\x74\x72\x6f\x6c\x65\u20\x70\x61\x72\x61\x6d\x65\x74\x72\xc5\xaf\x0a\x43\x6f\u20\x6e\x65\x6a\x76\xc3\xad

Actual decode:
\x4f\x62\x63\x68\x6f\x64\x20\x70\x6f\x75\x7a\x65\x20\x62\x61\x62\x79\x20\x69\x64\x65\xc3\xa1\x6c\x6e\xc4\x9b\x20\x6b\x6f\x6c\x65\x6d\x20\x33\x30\x74\x69\x20\x6d\x6f\xc5\xbe\x6e\xc3\xa1\x20\x70\x6f\x20\x6d\x61\x74\x65\xc5\x99\x73\x6b\xc3\xa9\x0a\x4f\x68\x6f\x64\x6e\x6f\x63\x65\x6e\xc3\xad\x20\x4f\x62\x63\x68\x6f\x64\x6e\x69\xc4\x8d\x65\x6b\x20\x2d\x20\x64\x6f\x64\x72\xc5\xbe\x65\x74\x20\x70\x61\x72\x61\x6d\x65\x74\x72\x79\x20\x61\x6c\x65\x20\x76\x65\x6c\x6d\x69\x20\x6d\x6f\x74\x69\x76\x61\xc4\x8d\x6e\xc3\xad\x20\x6d\x75\x73\xc3\xad\x20\x70\xc5\x99\x69\x20\x64\x6f\x62\x72\xc3\xa9\x6d\x20\x76\xc3\xbd\x6b\x6f\x6e\x75\x20\x64\x6f\x73\xc3\xa1\x68\x6e\x6f\x75\x74\x20\x31\x30\x30\x25\x20\x70\xc5\x99\x69\x20\x76\x79\x6e\x69\x6b\x61\x6a\xc3\xad\x63\xc3\xad\x6d\x20\x31\x32\x30\x25\x0a\x50\x6f\x64\xc5\x99\xc3\xad\x64\x69\x74\x20\x76\x65\xc5\xa1\x6b\x65\x72\x6f\x75\x20\x6b\x6f\x6e\x74\x72\x6f\x6c\x75\x20\x6b\x6f\x6e\x74\x72\x6f\x6c\x65\x20\x70\x61\x72\x61\x6d\x65\x74\x72\xc5\xaf\x0a\x43\x6f\x20\x6e\x65\x6a\x76\xc3

And the problem is this char "\xc3" and the reason of "General error: 1366 Incorrect string value: '\xC3' for column 'value' at row 1"

### Steps to reproduce
1. Sync calendar with CalDav.
2. Create new event with this text
"Obchod pouze baby ideálně kolem 30ti možná po mateřské
Ohodnocení Obchodniček - dodržet parametry ale velmi motivační musí při dobrém výkonu dosáhnout 100% při vynikajícím 120%
Podřídit veškerou kontrolu kontrole parametrů
Co nejví" - without quote
3. sync with server

### Expected behaviour
save the event

### Actual behaviour
Throw Exception.

### Server configuration

**Operating system**:

**Web server:**

**Database:** MySql 5.7.15-9-log

**PHP version:** 7.1.6

**Nextcloud version:** 12.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
2 Month old install

**Comment by MorrisJobke** [comment]
cc @georgehrke

**Comment by georgehrke** [comment]
@Priebojp Can you please provide proper log files? 
Where exactly is that exception thrown? (File and line number)
Is there a stack trace available? 
...

**Comment by Priebojp** [comment]
[nextcloud.log](https://github.com/nextcloud/server/files/1600034/nextcloud.log)
Thank you.

**Comment by georgehrke** [comment]
```
{"reqId":"WktDxn8AAQEAAEvGBB4AAAAB","level":4,"time":"2018-01-02T08:33:10+00:00","remoteAddr":"109.71.213.15","user":"hortova@exteco.eu","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/calendars\/hortova@exteco.eu\/personal\/56f47109-4785-468b-80e1-31f8e352907a.ics","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_calendarobjects_props` (`calendarid`, `objectid`, `name`, `parameter`, `value`) VALUES(?, ?, ?, ?, ?)' with params [\\\"9\\\", 6827, \\\"DESCRIPTION\\\", null, \\\"\\\\x50\\\\x4f\\\\x20\\\\x54\\\\x45\\\\x4c\\\\x45\\\\x46\\\\x4f\\\\x4e\\\\x55\\\\x0a\\\\x0a\\\\x43\\\\x4f\\\\x4d\\\\x41\\\\x50\\\\x20\\\\x50\\\\x52\\\\x41\\\\x48\\\\x41\\\\x20\\\\x73\\\\x2e\\\\x72\\\\x2e\\\\x6f\\\\x2e\\\\x0a\\\\x49\\\\xc4\\\\x8c\\\\x4f\\\\x3a\\\\x20\\\\x36\\\\x32\\\\x35\\\\x37\\\\x39\\\\x35\\\\x39\\\\x32\\\\x0a\\\\x56\\\\x6c\\\\x61\\\\x73\\\\x74\\\\x6e\\\\xc3\\\\xad\\\\x6b\\\\x3a\\\\x20\\\\x47\\\\x61\\\\x62\\\\x72\\\\x69\\\\x65\\\\x6c\\\\x61\\\\x20\\\\x48\\\\x6f\\\\x72\\\\x74\\\\x6f\\\\x76\\\\xc3\\\\xa1\\\\x0a\\\\x57\\\\x65\\\\x62\\\\x3a\\\\x20\\\\x77\\\\x77\\\\x77\\\\x2e\\\\x63\\\\x6f\\\\x6d\\\\x61\\\\x70\\\\x70\\\\x72\\\\x61\\\\x68\\\\x61\\\\x2e\\\\x63\\\\x7a\\\\x0a\\\\x54\\\\x79\\\\x70\\\\x20\\\\xc3\\\\xba\\\\xc4\\\\x8d\\\\x74\\\\x75\\\\x3a\\\\x20\\\\x50\\\\x6f\\\\x74\\\\x65\\\\x6e\\\\x63\\\\x69\\\\x61\\\\x6c\\\\x6e\\\\xc3\\\\xbd\\\\x20\\\\x7a\\\\xc3\\\\xa1\\\\x6b\\\\x61\\\\x7a\\\\x6e\\\\xc3\\\\xad\\\\x6b\\\\x0a\\\\x4f\\\\x62\\\\x72\\\\x61\\\\x74\\\\x3a\\\\x20\\\\x31\\\\x32\\\\x33\\\\xc2\\\\xa0\\\\x30\\\\x36\\\\x35\\\\xc2\\\\xa0\\\\x30\\\\x30\\\\x30\\\\x20\\\\x43\\\\x5a\\\\x4b\\\\x20\\\\x32\\\\x30\\\\x31\\\\x35\\\\x0a\\\\x0a\\\\x50\\\\x6f\\\\x7a\\\\x6e\\\\xc3\\\\xa1\\\\x6d\\\\x6b\\\\x61\\\\x3a\\\\x20\\\\x50\\\\x72\\\\xc5\\\\xaf\\\\x6d\\\\x79\\\\x73\\\\x6c\\\\x20\\\\x2d\\\\x20\\\\x76\\\\xc3\\\\xbd\\\\x72\\\\x6f\\\\x62\\\\x61\\\\x20\\\\x72\\\\x65\\\\x67\\\\x75\\\\x6c\\\\x61\\\\x63\\\\xc3\\\\xad\\\\x20\\\\x61\\\\x20\\\\x74\\\\x76\\\\x61\\\\x72\\\\x6f\\\\x76\\\\x65\\\\x6b\\\\x20\\\\x70\\\\x72\\\\x6f\\\\x20\\\\x72\\\\x6f\\\\x7a\\\\x76\\\\x6f\\\\x64\\\\x79\\\\x0a\\\\x0a\\\\x53\\\\x70\\\\x6f\\\\x6c\\\\x65\\\\xc4\\\\x8d\\\\x6e\\\\x6f\\\\x73\\\\x74\\\\x20\\\\x43\\\\x4f\\\\x4d\\\\x41\\\\x50\\\\x20\\\\x70\\\\x61\\\\x74\\\\xc5\\\\x99\\\\xc3\\\"]:\\n\\nSQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\\\xC3' for column 'value' at row 1\",\"Code\":0,\"Trace\":\"#0 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1015): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/lib\\\/private\\\/DB\\\/Connection.php(213): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\\n#3 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(208): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\\n#4 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(213): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/CalDavBackend.php(2037): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/CalDavBackend.php(1034): OCA\\\\DAV\\\\CalDAV\\\\CalDavBackend->updateProperties('9', '56f47109-4785-4...', 'BEGIN:VCALENDAR...')\\n#7 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/CalendarObject.php(106): OCA\\\\DAV\\\\CalDAV\\\\CalDavBackend->updateCalendarObject('9', '56f47109-4785-4...', 'BEGIN:VCALENDAR...')\\n#8 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1130): Sabre\\\\CalDAV\\\\CalendarObject->put('BEGIN:VCALENDAR...')\\n#9 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->updateFile('calendars\\\/horto...', 'BEGIN:VCALENDAR...', NULL)\\n#10 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#12 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#13 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Server.php(258): Sabre\\\\DAV\\\\Server->exec()\\n#15 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#16 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/remote.php(162): require_once('\\\/nfsmnt\\\/hosting...')\\n#17 {main}\",\"File\":\"\\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":116}","userAgent":"eM Client\/7.1.30794.0","version":"12.0.4.3"}
```

So it's not directly related to Sabre/DAV but simply a database error.

**Comment by MorrisJobke** [comment]
```
SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\\\xC3' for column 'value' at row 1
```

**Comment by Priebojp** [comment]
I think its a problem with how they save the text in DB.
Because the last character is "í" with UTF-8 code "\xc3\xad"
but the DB got only half of that character "\xc3" 
Or this is what i see on my cloude.

How can i fix this problem? or is this realy a DB problem?

**Comment by rullzer** [comment]
Could this not just be utf8 issue?

@Priebojp can you post the output of

```sql
show table status like 'oc_calendarobjects_props'
```

**Comment by Priebojp** [comment]
My whole DB are in utf8mb4.

`Name:oc_calendarobjects_props
Engine:InnoDB
Version:10
Row_format:Compressed
Rows:1789
Avg_row_length:68
Data_length1789:122880
Max_data_length:0
Index_length:163840
Data_free:0
Auto_increment:4850
Create_time:2017-12-14 12:29:29
Update_time:NULL
Check_time:NULL
Collation:utf8mb4_bin
Checksum:NULL
Create_options:row_format=COMPRESSED
Comment:`

**Comment by Priebojp** [comment]
Any suggestion how can i fix it? 

Example: 
User1 has a Calendar1;
User2 has a Calendar2;
Both sides share the calendar

User1 create Event with User2 as Participants.
This is still ok and User1 see in his own calendar the event, and the shared Calendar2 too.
User2 same.

But after User1 change something in that Event User2 get this error message.

`{"reqId":"Wl78SX8AAQEAAZQ@uFEAAAAB","level":4,"time":"2018-01-17T07:33:30+00:00","remoteAddr":"109.71.213.15","user":"email","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/calendars\/email\/personal\/4822eb78-dde1-4f68-ad6a-439bde2d87a9.ics","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_calendarobjects_props` (`calendarid`, `objectid`, `name`, `parameter`, `value`) VALUES(?, ?, ?, ?, ?)' with params [\\\"9\\\", 7276, \\\"DESCRIPTION\\\", null, \\\"\\\\x50\\\\x4f\\\\x20\\\\x45\\\\x4d\\\\x41\\\\x49\\\\x4c\\\\x55\\\\x0a\\\\x0a\\\\x50\\\\x4f\\\\x45\\\\x58\\\\x20\\\\x56\\\\x65\\\\x6c\\\\x6b\\\\xc3\\\\xa9\\\\x20\\\\x4d\\\\x65\\\\x7a\\\\x69\\\\xc5\\\\x99\\\\xc3\\\\xad\\\\xc4\\\\x8d\\\\xc3\\\\xad\\\\x2c\\\\x61\\\\x2e\\\\x73\\\\x2e\\\\x0a\\\\x0a\\\\x49\\\\xc4\\\\x8c\\\\x4f\\\\x3a\\\\x20\\\\x32\\\\x35\\\\x35\\\\x31\\\\x38\\\\x33\\\\x35\\\\x36\\\\x0a\\\\x56\\\\x6c\\\\x61\\\\x73\\\\x74\\\\x6e\\\\xc3\\\\xad\\\\x6b\\\\x3a\\\\x20\\\\x47\\\\x61\\\\x62\\\\x72\\\\x69\\\\x65\\\\x6c\\\\x61\\\\x20\\\\x48\\\\x6f\\\\x72\\\\x74\\\\x6f\\\\x76\\\\xc3\\\\xa1\\\\x0a\\\\x57\\\\x65\\\\x62\\\\x3a\\\\x20\\\\x68\\\\x74\\\\x74\\\\x70\\\\x3a\\\\x2f\\\\x2f\\\\x77\\\\x77\\\\x77\\\\x2e\\\\x70\\\\x6f\\\\x65\\\\x78\\\\x2e\\\\x63\\\\x7a\\\\x0a\\\\x0a\\\\x54\\\\x79\\\\x70\\\\x20\\\\xc3\\\\xba\\\\xc4\\\\x8d\\\\x74\\\\x75\\\\x3a\\\\x20\\\\x50\\\\x6f\\\\x74\\\\x65\\\\x6e\\\\x63\\\\x69\\\\x61\\\\x6c\\\\x6e\\\\xc3\\\\xbd\\\\x20\\\\x7a\\\\xc3\\\\xa1\\\\x6b\\\\x61\\\\x7a\\\\x6e\\\\xc3\\\\xad\\\\x6b\\\\x0a\\\\x4f\\\\x62\\\\x72\\\\x61\\\\x74\\\\x3a\\\\x20\\\\x0a\\\\x20\\\\x20\\\\x20\\\\x20\\\\x36\\\\x36\\\\x37\\\\xc2\\\\xa0\\\\x38\\\\x34\\\\x39\\\\xc2\\\\xa0\\\\x30\\\\x30\\\\x30\\\\x2c\\\\x30\\\\x20\\\\x4b\\\\xc4\\\\x8d\\\\x2c\\\\x20\\\\x32\\\\x30\\\\x31\\\\x35\\\\x0a\\\\x0a\\\\x50\\\\x6f\\\\x7a\\\\x6e\\\\xc3\\\\xa1\\\\x6d\\\\x6b\\\\x61\\\\x3a\\\\x20\\\\x76\\\\xc3\\\\xbd\\\\x72\\\\x6f\\\\x62\\\\x6f\\\\x75\\\\x20\\\\x65\\\\x78\\\\x74\\\\x72\\\\x75\\\\x64\\\\x6f\\\\x76\\\\x61\\\\x6e\\\\xc3\\\\xbd\\\\x63\\\\x68\\\\x20\\\\x73\\\\x6e\\\\x61\\\\x63\\\\x6b\\\\x73\\\\xc5\\\\xaf\\\\x20\\\\x61\\\\x20\\\\x63\\\\x65\\\\x72\\\\x65\\\\xc3\\\\xa1\\\\x6c\\\\x6e\\\\xc3\\\\xad\\\\x63\\\\x68\\\\x20\\\\x76\\\\xc3\\\\xbd\\\\x72\\\\x6f\\\\x62\\\\x6b\\\\xc5\\\"]:\\n\\nSQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\\\xC5' for column 'value' at row 1\",\"Code\":0,\"Trace\":\"#0 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(1015): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/lib\\\/private\\\/DB\\\/Connection.php(213): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\\n#3 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Query\\\/QueryBuilder.php(208): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\\n#4 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/lib\\\/private\\\/DB\\\/QueryBuilder\\\/QueryBuilder.php(213): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/CalDavBackend.php(2040): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/CalDavBackend.php(1037): OCA\\\\DAV\\\\CalDAV\\\\CalDavBackend->updateProperties('9', '4822eb78-dde1-4...', 'BEGIN:VCALENDAR...')\\n#7 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/CalDAV\\\/CalendarObject.php(106): OCA\\\\DAV\\\\CalDAV\\\\CalDavBackend->updateCalendarObject('9', '4822eb78-dde1-4...', 'BEGIN:VCALENDAR...')\\n#8 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1130): Sabre\\\\CalDAV\\\\CalendarObject->put('BEGIN:VCALENDAR...')\\n#9 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->updateFile('calendars\\\/horto...', 'BEGIN:VCALENDAR...', NULL)\\n#10 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#12 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#13 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/apps\\\/dav\\\/lib\\\/Server.php(258): Sabre\\\\DAV\\\\Server->exec()\\n#15 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(33): OCA\\\\DAV\\\\Server->exec()\\n#16 \\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/remote.php(162): require_once('\\\/nfsmnt\\\/hosting...')\\n#17 {main}\",\"File\":\"\\\/nfsmnt\\\/hosting1_1\\\/5\\\/7\\\/57c92ba1-ce7b-45d2-8e72-f6e245605d3f\\\/exteco.eu\\\/sub\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":116}","userAgent":"eM Client\/7.1.31849.0","version":"12.0.4.3"}`

**Comment by georgehrke** [comment]
We will have to use `mb_substring` instead of a simple `substr` here: https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/CalDavBackend.php#L2256

What does the length of database fields refer to? Bytes or the actual number of characters, even if characters are 4 byte UTF characters?

maybe @nickvergessen knows ^

**Comment by Priebojp** [comment]
Default length of "value" in DB is 255 i think.
i changed it to "varchar(500)" for test but it didnt help.

**Comment by georgehrke** [comment]
@Priebojp yes, that's expected. The issue is not the database but the line of code i referenced.

**Comment by nickvergessen** [comment]
hmm, indeed mb_* fixes this, I always thought intl would help there too...

Btw this is not a problem with the lenght, but with the invalid sequence `\xC3` which is no valid 3-byte character. So it reports that the second part of the 4-byte character is missing.

**Comment by MorrisJobke** [comment]
@nickvergessen @georgehrke Will this be ready by later today or should we move it to 13.0.2? nextcloud/server#8748

**Comment by nickvergessen** [comment]
No, this needs a general solution for all places where we trim input before the database
