### ISSUE TITLE
Popover misplaced in user management

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/server#7682]
### Steps to reproduce
1. Open user management
2. Click on the more icon for a user

### Expected behaviour
The popover should be positioned correctly

### Actual behaviour
The popover isn´t positioned correctly (a bit to high)

## Server configuration detail

**Operating system:** Linux

**Webserver:** Apache (CentOS)

**Database:** sqlite3 3.7.17

**PHP version:** 7.1.12

**Nextcloud version:** 13.0.0 Beta 3

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** git

<details><summary>List of activated apps</summary>

```
Enabled:
 - comments: 1.3.0
 - dav: 1.4.5
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_sharing: 1.5.0
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - issuetemplate: 0.3.0
 - lookup_server_connector: 1.1.0
 - oauth2: 1.1.0
 - provisioning_api: 1.3.0
 - sharebymail: 1.3.0
 - systemtags: 1.3.0
 - theming: 1.4.1
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - testing
 - user_ldap
```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "sqlite3",
    "version": "13.0.0.8",
    "installed": true
}
```
</details>
<br>
What it looks like:

![user management](https://user-images.githubusercontent.com/1869584/34320388-9b959f1e-e7f9-11e7-8681-c3089c34e23e.png)

What it should look like:

![files](https://user-images.githubusercontent.com/1869584/34522402-b51c0d8c-f092-11e7-928f-37ec23494ada.png)
  
Ref #7617

**Comment by MariusBluem** [comment]
@nextcloud/designers

**Comment by michag86** [comment]
Is this problem still existing?
With NC 13 RC2 I cannot confirm this:
![grafik](https://user-images.githubusercontent.com/6691165/35287102-e8e10e5e-0061-11e8-8013-467aa09555de.png)
Tested with Firefox ESR 52

**Comment by splitt3r** [comment]
You are right 👍
