### ISSUE TITLE
Possibility to cleanup versions per path

### ISSUE THREAD

**Issue by biva** [nextcloud/server#7687]
I'd like to cleanup the old versions for a specific path. It's now possible to do it for a specific user:
`sudo -u www-data php occ versions:cleanup john`

But I'd like to specify also a path. Like the file:scan function:
`sudo -u www-data php occ files:scan --path="/john/files/Pictures" john`

Then we would have something like:
`sudo -u www-data php occ versions:cleanup --path="john/files_versions/Pictures" john`

My use-case: a program modified all the pictures of a specific folder. I downloaded all the files directly from the server in order to recover the former version. But now I'd like to cleanup the old versions, specifically for this folder.

Manual is here: https://docs.nextcloud.com/server/12/admin_manual/configuration_server/occ_command.html#versions-label

**Comment by biva** [comment]
I'm wondering what would happen if I manually delete the folder : `rm -r john/files_versions/Pictures`? How would Nextcloud clean its database in order to delete entries related to the deleted versions?

**Comment by biva** [comment]
Probably related to https://github.com/nextcloud/server/issues/7285 and https://github.com/nextcloud/server/issues/1258 and https://github.com/nextcloud/server/issues/7473

**Comment by MorrisJobke** [comment]
cc @icewind1991 @schiessle

**Comment by icewind1991** [comment]
> How would Nextcloud clean its database in order to delete entries related to the deleted versions?

You would need to run `occ files:scan --path /john/files_versions/Pictures` to update the filesystem index

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by acsfer** [comment]
@biva check https://github.com/nextcloud/server/pull/27408
