### ISSUE TITLE
Allow apps to add dav collections

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#7689]
We have an event now to add plugins by apps.

https://github.com/nextcloud/server/blob/5011142024a2563ac162e17417dd9b7edcae0ff5/apps/dav/lib/Server.php#L178

However, it would also make sense to allow apps to register collections on the new dav endpoint:

So basically in

https://github.com/nextcloud/server/blob/5011142024a2563ac162e17417dd9b7edcae0ff5/apps/dav/lib/RootCollection.php#L109

This would allow us to start writing dav endpoints for trashbin and versions etc.

The way I see it there are two approaches here:

1. Dispatch an event
  * Pro: Very easy
  * Con: How to make sure 3rdparty app doesn't hijack the versions/trashbin endpoints?
2. Add and entry in info.xml there is then a sort of collections manager?
  * Pro: We can give higher preference to "official" apps.
  * Cons: more enginering work

Opinions: @MorrisJobke @nickvergessen @blizzz @schiessle @georgehrke

**Comment by juliushaertl** [comment]
#6835 also allows adding collections to the root collection, so this is basically the second approach, but currently it is indeed possible to overwrite "official" collections from within apps.

https://github.com/nextcloud/server/blob/5011142024a2563ac162e17417dd9b7edcae0ff5/apps/dav/lib/Server.php#L276-L278
https://github.com/nextcloud/appstore/pull/527/files#diff-d37c6b239400622b3c3d8738037e9bddR288

**Comment by rullzer** [comment]
Mmmm how did I miss that :P
