### ISSUE TITLE
Linux Distribution Packages for Nextcloud

### ISSUE THREAD

**Issue by andyxh** [nextcloud/server#7690]
Hello Everyone, 

Is there a way for the dev team to make Linux Distribution Packages like owncloud has. I've attached a link below of what im talking about.  I think it would be a awesome idea for some to install nextcloud and all of it's Packages with a few commands

https://download.owncloud.org/download/repositories/9.0/owncloud/

![image](https://user-images.githubusercontent.com/24574019/34541795-467ec7d6-f09f-11e7-9b73-b2e215f7bdd1.png)

**Comment by MorrisJobke** [comment]
Hi @andyxh 

we had a lot of problems with maintaining the packages in the past and thus decided to work on our core competence: writing a PHP web application (and not building packages for multiple distributions). We are nevertheless happy to help maintainers of distributions to ship Nextcloud as a package, but we think that the way to install and update Nextcloud should be based on our release tar ball. This is the most flexible way and can be used by many other tools around deployment (like docker, config script, config management tools, packages, etc). It was just a decision on our side, that we spend our time better with fixing bugs than working on packages. Sorry for the bad news for you.

If you need  assistance in the upgrade behaviour we could recommend the built-in updater. It already served a lot of successful and easy updates ;)

**Comment by andyxh** [comment]
I completely understand but for someone that dosen't know anything about setting up the system from the start it would be nice to have some simple instructions.  What you think?

**Comment by MorrisJobke** [comment]
We have detailed instructions for the installation via snap or via the manual way over here: https://docs.nextcloud.com/server/12/admin_manual/installation/source_installation.html#example-installation-on-ubuntu-16-04-lts-server

Does this help you?

**Comment by andyxh** [comment]
Oh thank you! that works, i already have a server but i'd like to learn more about it :)
