### ISSUE TITLE
Do not regenerate the preview on a rename

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#7700]
* having a file with a preview
* rename the file
* actual: preview is hidden behind a spinner and then downloaded again
* expected: preview just stays

The reason for this is, that the preview is actually requested based on the filename and not on the fileid (it is nevertheless stored under the fileid and thus not re-generated).

Before and after rename URL:

```
http://192.168.99.100/server/core/preview.png?file=%2FBildschirmfoto+2017-11-30+um+23.09.2822.png&c=64e26567fd27cdb34123247436d80d29&x=32&y=32&forceIcon=0
http://192.168.99.100/server/core/preview.png?file=%2FBildschirmfoto+2017-11-30+um+23.09.28224.png&c=64e26567fd27cdb34123247436d80d29&x=32&y=32&forceIcon=0
```

cc @rullzer @nextcloud/javascript

**Comment by rullzer** [comment]
Well yes. Solution would be to create a new endpoint that accepts a file id. This would not be hard to do. (actually fairly easy).

This might be enough. Since then the browser knows the fileid hasn't changed so the fetch of the preview is instance (since we cache it :P)
