### ISSUE TITLE
Offline files can not be downloaded

### ISSUE THREAD

**Issue by vscwjm** [nextcloud/server#7715]
I suspect it is a PHP-caused problem.
Below is the log.

http://cloud2.wangjiaming.org/index.php/s/gqkMT577NMnrNo3

Please help analyze and solve the problem。
     Thanks.

**Comment by MorrisJobke** [comment]
It looks like your mysql server was not reachable: `Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_preferences` (`userid`, `appid`, `configkey`, `configvalue`) VALUES(?, ?, ?, ?)' with params ["wang", "core", "lang", "zh_CN"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away`

Please check that it is available and then also fill out the issue template to provide all the needed information to help you.
