### ISSUE TITLE
Inconsistent appearance of the password strength bar

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#7719]
The password strength bar during the installation appears [centered on the password input](https://github.com/nextcloud/server/blob/21fbcba68d3ce49bf31960276c0cbfe0f158dda4/core/css/guest.css#L292-L298) (although it is 1px off to the right, as the bar width is 250px with a margin of 15px and the password input width is 249px with a padding of 10px and a margin of 5px ;-) ), but in the user settings it appears [aligned to the left and covers only half of the password input](https://github.com/nextcloud/server/blob/a79d276324f1c5e44aec9a54c909ca47b31fb532/settings/css/settings.scss#L1119-L1124).

Installation:
![strengthify-installation](https://user-images.githubusercontent.com/26858233/34635435-75ab4e3e-f28f-11e7-8231-fd7017b8590c.png)

User settings:
![strengthify-settings](https://user-images.githubusercontent.com/26858233/34635437-77e6c7fa-f28f-11e7-8f76-f2da295bc3e0.png)

The password strength bar [is also used in the LDAP app](https://github.com/nextcloud/server/blob/1d8e73b10843d60789010008902017530f8b2121/apps/user_ldap/css/renewPassword.css#L6-L11), but I have not checked its appearance.

@nextcloud/designers

**Comment by jancborchardt** [comment]
Should definitely be centered in the user settings, yes. :)

For installation it looks nice right now, but we could also put it in the standard popup.

**Comment by asterlilly** [comment]
Dawn Re Meiring Gamberg says "hey you,  get off my (cloud). I mean, internet accounts. Thank you. Love, Venus
