### ISSUE TITLE
The screen looks strange when I connect to nextcloud on a browser other than Chrome.

### ISSUE THREAD

**Issue by moodcela** [nextcloud/server#7722]
The screen looks strange when I connect to nextcloud on a browser other than Chrome.
Edge and Explorer can not even log in. And the screen looks strange too.

What is the cause of the problem?

Nextcloud version 12.0.4

chrome
![chrome](https://user-images.githubusercontent.com/20749641/34646101-e3c3e7e6-f3a2-11e7-8302-4e945fcbe57d.PNG)

Edge
![edge](https://user-images.githubusercontent.com/20749641/34646103-f1608a76-f3a2-11e7-8a72-5567f91090c9.PNG)

Explorer
![explorer](https://user-images.githubusercontent.com/20749641/34646105-f7b67764-f3a2-11e7-97f8-ca303b9a4615.PNG)

  
  Edge error screenshot
![edgeerror](https://user-images.githubusercontent.com/20749641/34647011-0d42ee7a-f3ba-11e7-8b64-094295a7ca6f.PNG)

**Comment by MorrisJobke** [comment]
Looks like your web server is configured wrongly. All browsers report non-successful requests for all the assets (like JS and CSS). If I do a curl request against `/core/css/jquery.ocdialog.css` on your domain for example I get: `curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)`

Please check the docs for how to set it up properly https://docs.nextcloud.com/server/12/admin_manual/installation/nginx.html and ask for help in the forums if this doesn't work: https://help.nextcloud.com
